{100}{}{Você vê um técnico.}
{101}{}{Você vê um técnico de computador.}
{102}{}{Você vê alguém vestindo um jaleco de laboratório completo, com bolso e um protetor de estoque de canetas.}
{103}{}{Bom dia, soldado.}
{104}{}{Por favor, não toque em nada.}
{105}{}{Vocês grunhidos não deveiam estar aqui.}
{106}{}{Você está fora do uniforme. }
{107}{}{É melhor você se adequar. Arsenal está no corredor do lado esquerdo.}
{108}{}{Você está tendo uma grande chance de estar fora de uniforme. Melhor você informar ao fornecimento.}
{109}{}{Quem diabos são vocês... Alerta! Intrusos!}
{110}{}{Temos sido infiltrados! Alerta!}
{111}{}{Vários intrusos! Soar o alarme!}
{112}{}{Merda! Obter as cópias de segurança iniciado.}
{113}{}{Encerrar todas as operações secretas.}
{114}{}{Proteger o sistema e habilitar todas as senhas de segurança.}
{115}{}{Eu sou um cientista, não um lutador!}
{116}{}{O extremo pontilhado com o diodo laser vai para o inimigo. Em seguida, puxe o gatilho.}
{117}{}{Ajuda! Ajuda! Para o laboratório de informática!}
