{170}{}{Você habilmente pegar o bloqueio no armário.}
{171}{}{A sua falta de habilidade tem obstruído o bloqueio no armário.}
{172}{}{Você não pegar o bloqueio no armário.}
{173}{}{ habilmente pega o bloqueio no armário.}
{174}{}{'s falta de habilidade tem obstruído o bloqueio no armário.}
{175}{}{ não conseguiu pegar o bloqueio no armário.}
{176}{}{Você arrombou a fechadura da porta.}
{177}{}{Você pressiona suas costas enquanto tenta abrir o bloqueio e
  toma um ponto de dano.}
{178}{}{Você pressiona suas costas enquanto tenta abrir o bloqueio e toma }
{179}{}{ pontos de dano.}
{180}{}{Você é muito fraco para ultrapassar o bloqueio.}
{181}{}{ arrombou a fechadura da porta.}
{182}{}{ machuca as costas enquanto tenta arrombar a fechadura e recebe 
 pontos de dano.}
{183}{}{ massageia suas costas enquanto tenta abrir o bloqueio e toma }
{184}{}{ pontos de dano.}
{185}{}{ é muito fraco para ultrapassar o bloqueio.}
{186}{}{ machuca as costas enquanto tenta arrombar a fechadura e recebe 
 pontos de dano.}
{187}{}{ pressiona suas costas enquanto tenta abrir o bloqueio e toma}
{188}{}{ pontos de dano.}
{189}{}{Você bloqueia habilmente o armário.}
{190}{}{Você não bloqueia o armário.}
{191}{}{ habilmente bloqueia o armário.}
{192}{}{ falha ao bloquear o armário.}
{203}{}{O armário parece estar bloqueado.}
{800}{}{Você recuperou o fob.}
{810}{}{Você recuperou os planos.}
{820}{}{Você recuperou o K-9 motivador.}
