{100}{}{Você vê um guarda.}
{150}{}{O guarda guarda a igreja velha.}
{151}{}{[FALAR]}
{152}{}{Como você se atreve a mostrar o seu rosto novamente!}
{153}{}{[Feito]}
{154}{}{Ho! Ninguém entra no armazém da família Wright à noite!}
{155}{}{Bem, o próprio Sr. Wright me enviou uma missão. Se você não sabe sobre isso, muito ruim.}
{156}{}{Eu vou voltar amanhã.}
{157}{}{Eu preciso chegar lá agora.}
{158}{}{[Olhando nervoso] Desculpe...eu não sabia. Você tem algum papel?}
{159}{}{Por favor! Você pode mesmo ler?}
{160}{}{Não, ele não me deu nenhum.}
{161}{}{Deixei-os de volta com minha guarda. Eu vou buscá-los.}
{162}{}{Você não pode entrar sem documentos.}
{163}{}{Aqui está a minha autorização! Ataque!}
{164}{}{Eu vou voltar.}
{165}{}{[Vergonha] Não...hum...tudo bem, basta ir em na...}
{166}{}{Obrigado.}
{167}{}{Assim que se fala.}
{168}{}{O que vocês querem?}
{169}{}{Precisamos ir para dentro.}
{170}{}{Fomos enviados aqui pelo chefe.}
{171}{}{Eu teria ouvido se um grupo foi enviado aqui. Saia!}
{172}{}{Fora com a sua cabeça!}
{173}{}{OK, OK, nós estamos indo.}
{174}{}{Qual é o seu negócio aqui?}
{175}{}{Eu preciso ir para dentro.}
{176}{}{Eu fui enviado no negócio oficial pelo chefe. Fique de lado!}
{177}{}{Removendo a cabeça dos seus ombros.}
{178}{}{Desculpe, lugar errado.}
{179}{}{Olá novamente. Você pode ir em frente.}
{180}{}{Obrigado.}
{181}{}{Ei, fique longe da porta!}
{182}{}{Não toque na porta novamente, a menos que você queira problemas.}
{183}{}{Eu vejo você tocar nessa porta novamente, você vai pegar uma bala na cabeça.}
{184}{}{Hey, o que você pensa que está fazendo?}
{185}{}{Eu já tive o suficiente de você.}
{186}{}{Desculpa; Posso deixar você entrar, mas seus amigos terão de esperar lá fora.}
{187}{}{Apenas um de vocês são permitidos por vez.}
{200}{}{Boa noite.}
{201}{}{Boa tarde.}
{202}{}{Bom dia.}
{203}{}{Apenas termine seu negócio, obrigado.}
{250}{}{Você sabe, amigo, já tive o suficiente da sua merda!}
{251}{}{Você sabe, puta, eu já tive o suficiente de sua merda!}
{252}{}{[FIM]}
