{100}{}{Um homem em armadura de energia.}
{101}{}{Arthur, filho de Uther Pendragon.}
{102}{}{Seu vôo é baixo.}
{103}{}{Salve, viajantes. Meu nome é Arthur, filho de Uther Pendragon, da Irmandade do Aço. Nós
  estão em busca da Granada de mão sagrada de Antioquia. Você viu isso?}
{104}{}{Santo o que de quem?}
{105}{}{Resposta do jogador}
{106}{}{Agnu.}
{107}{}{Não há tempo para falar. Estamos em busca.}
{108}{}{Buscamos a Granada de Mão Sagrada de Antioquia.}
{109}{}{Para a Irmandade do Aço!}
{110}{}{Hmm ... Andorinha africana ou europeia?}
{111}{}{Ei agora! Isso não é seu, não é?}
{112}{}{Eu estou avisando. Mantenha as suas mãos para si mesmo.}
{113}{}{É isso. O suficiente é suficiente.}
{114}{}{A Granada de mão sagrada de Antioquia? Por que, é apenas a maior mão, arma anti-pessoal
  de seu tipo.}
{115}{}{Por que você procurar por uma arma terrível?}
{116}{}{Nós da Irmandade do Aço procuramos encontrar esta arma mais devastadora de nossos antepassados, e
  assegurar daqueles que abusariam do poder da Sagrada Grade Mágica de Antioquia.}
{117}{}{Por quê?}
{118}{}{Bem...porque a Irmandade do Aço é dedicada a proteger os fracos e indefesos, e essa coisa podia machucar
 alguém.}
{119}{}{Por quê?}
{120}{}{Umm ... porque é realmente a única coisa moral a fazer.}
{121}{}{Por quê?}
{122}{}{Wha ... um ... Olhe agora, estamos muito ocupados. Você vai nos ajudar ou não? Você viu
  a Granada de mão sagrada de Antioquia ou não?}
{123}{}{Sim.}
{124}{}{Não.}
{125}{}{Bem, por que você não disse? Se você pudesse nos dizer onde, vamos sair e você pode obter
  De volta ao que quer que você esteja fazendo.}
{126}{}{[Você aponta em uma direção aleatória.]}
{127}{}{Certo então. Obrigado pela ajuda. Algo para o seu problema.}
{128}{}{Esperar! Eu também estou em uma missão. Procuro o sagrado GECK. Você já viu?}
{129}{}{Bem, não há sentido em continuar essa conversa. Vamos embora. }
{130}{}{[FIM]}
{131}{}{Sangrento camponês!}
{132}{}{[FIM]}
{133}{}{GECK, você disse? Por que sim, nós temos dois deles. Não precisa de outro. Agradece a todos a mesma
  Apesar.}
{134}{}{Já que você tem dois deles, talvez você poderia me dar um.}
{135}{}{Não. Não. Não conseguiria fazer isso. Não seria correto terminar sua busca facilmente. Há mais alguns
 daquele jeito. Vá buscar o seu próprio. [Ele aponta uma direção da mesma maneira que você apontou quando você
 disse-lhe onde estava a Granada Mágica de Antioquia.]}
{136}{}{[FIM]}
{200}{}{Você fala a língua do rei?}
{201}{}{Hellooo.}
{202}{}{Ei, estou aqui.}
{203}{}{Se você pudesse poupar um momento do seu tempo.}
{204}{}{Ahem.}
{205}{}{Agora vamos. Não me ignore.}
{206}{}{Porfavooooor! Eu preciso perguntar uma coisa importante.}
{207}{}{Bem, devemos continuar nossa busca pela Granada de Mãos de Antioquia. Venha, Patsy.}
{300}{}{Nossa missão foi cumprida!}
{301}{}{Arthur, ao seu serviço.}
