{100}{}{Você vê um enorme tijolo de um homem.}
{101}{}{Você vê um enorme tijolo de um homem.}
{102}{}{Ele é um gigante de um homem e provavelmente come pessoas como você para o café da manhã.}
{103}{}{Velho, você VAI vir com a gente.}
{104}{}{Nos deixe em paz. Nunca apoiarei a causa de seus superiores.}
{105}{}{Eu não vou perguntar de novo. Venha agora, ou você vai ser feito um exemplo.}
{106}{}{Prefiro que o conhecimento eu tenha desapareça comigo no túmulo.}
{107}{}{Que assim seja. Mate todos.}
{108}{}{Este não é seu caso. Vire-se e vá embora.}
{109}{}{Você parece encontrar algumas pessoas no lugar errado na hora errada.}
