{100}{}{Você vê um homem vestindo armadura de couro.}
{101}{}{Você vê Kaga.}
{102}{}{Ele está vestindo uma armadura de couro e tem um irritante hábito de falar sobre si mesmo em terceira pessoa.}
{103}{}{Esta será a última vez que Kaga te encontra.}
{104}{}{Depois de Kaga matá-lo, ele vai queimar Arroyo até o chão.}
{105}{}{Sinta a ira de Kaga!}
{106}{}{Eu sou o grande Kaga!}
{107}{}{Kaga é para ser temido por todos.}
{108}{}{Kaga terá sua cabeça para um troféu.}
{109}{}{Rendição e sua morte será rápida.}
{110}{}{Kaga estará de volta!}
{111}{}{Você não pode matar o grande Kaga!}
{112}{}{Você tem sorte Kaga tem negócios em outro lugar.}
{113}{}{Kaga irá encontrá-lo novamente.}
{120}{}{É esse cara Kaga de novo.}
{150}{}{[Um guerreiro alto e poderosamente construído está diante de você, seus olhos chamejam de ódio enquanto ele olha para você.] Então, eles expulsaram Kaga, então, consideram você o Escolhido? Ha! Você acha que ser o neto do Morador do Vault faz você especial ?! Você acha que é melhor do que eu, Kaga o Grande ?!}
{151}{}{Bem, eu SOU o Escolhido, não sou?}
{152}{}{Ei agora, segure um segundo. Nunca disse que era melhor do que você.}
{160}{}{Esse título vai significar nada quando Kaga rasga a cabeça dos seus ombros!}
{161}{}{Nenhuma palavra pode salvar sua pele. Com sua morte, a honra de Kaga deve ser restaurada. Kaga vai agora vingar-se!}
{200}{}{Ooglie?}
{201}{}{O que!? Eles escolheram * você * para ser o Escolhido? Oh meu, eles ficaram desesperados.}
{202}{}{Eu não gosto. Você parece mal.}
{203}{}{Kaga nem sequer se incomodará em falar com você ainda mais. Prepare-se para morrer nas mãos de Kaga!}
