{100}{}{Você vê um pequeno rugrat.}
{101}{}{Você vê Melchior, Jr.}
{150}{}{Ele parece um risonho, garoto de olhos grandes.}
{200}{}{Olá! Eu sou Melchior, Jr.}
{201}{}{Meu pai é mineiro. Seu nome é Melchior assim como o meu.}
{202}{}{Meu pai é um bom mineiro, mas ele quer ser um mago.}
{203}{}{O nome artístico do papai é Melchior, o Magnífico.}
{204}{}{Seu melhor truque foi puxando um rato de um chapéu.}
{205}{}{Ele saiu com alguns homens vestidos com roupas de metal.}
{206}{}{Espero que o pai volte logo. Sinto falta de seus truques mágicos.}
{207}{}{Eu vou ser um grande mágico como meu pai.}
