{100}{}{Você vê um Garimpeiro.}
{101}{}{Segure-o ali mesmo, estranho! Eu não estou acostumado a emboscar estranhos, mas eu preciso de suprimentos e eu
  não posso deixar minha reivindicação. Quer fazer um comércio rápido?}
{102}{}{Com certeza.}
{103}{}{Eu não tenho nada para negociar. Desculpe.}
{104}{}{Booga.}
{105}{}{Que sorte de sorte. Você não pode falar, você pode? Não posso falar, não posso dizer a ninguém onde minha reivindicação
  é. Vamos trocar.}
{106}{}{[Troca]}
{107}{}{OK, saia! E é melhor não contar a ninguém onde é minha reivindicação.}
{108}{}{[Fim]}
{109}{}{Eu acho que é melhor você continuar se movendo.}
{110}{}{Nós não temos mais nada para falar.}
{111}{}{Em seu caminho!}
{112}{}{Vá buscá-los.}
{113}{}{Não é possível que você diga a ninguém onde está minha reivindicação.}
{114}{}{Por que você me atacou?}
{115}{}{Agora eu tenho que matar você.}
{116}{}{Eu só queria um pouco de suprimentos.}
{117}{}{Você pode ter minha reivindicação!}
{118}{}{Misericórdia!}
