{100}{}{Você vê um spammer com aspecto patético.}
{110}{}{Você vê absolutamente nada de interesse.}
{120}{}{Será que vai haver uma versão para Mac?}
{121}{}{Eu quero multi-jogador!}
{122}{}{Eu odeio todos vocês!}
{123}{}{Ahhh!}
{124}{}{Você não pode me machucar!}
{125}{}{Eu sou o Grim Reaper, você não pode me matar. Não sou engraçado.}
{126}{}{Eu quero um tanque!}
{127}{}{Onde está a minha moto-serra?}
{128}{}{Não me machucar.}
{129}{}{Eu não quero ser um idiota.}
{130}{}{Eu não queria dizer aquelas ameaças de morte.}
{131}{}{Eu lamento, Buffy!}
{132}{}{Eu lamento, sujo! Eu só queria ser notado.}
{133}{}{Eu quero uma versão on-line!}
