{100}{}{Você vê ... um modelo de herói branco.}
{101}{}{Você vê um homem branco pesadamente musculoso em um macacão Vault 13. Ele está sorrindo e rindo enquanto ele
  conta sua história.}
{102}{}{Você vê um modelo de herói branco. Ele está sorrindo e rindo.}
{103}{}{Você vê um modelo de herói branco. Ele está sorrindo e rindo.}
{104}{}{Então...o meu jogador foi TÃO estúpido, que...}
{105}{}{Obtenha isso, obtenha isso - ele acha que a munição de espingarda é o chip de água, e ele leva de volta para
  O Supervisor ...}
{106}{}{Que idiota!}
{107}{}{Eu tive um daqueles jogadores "violentos, idiotas como uma pedra" que me corroam. E deixe-me dizer-lhe ...}
{108}{}{Foi divertido por um tempo, mas fica velho rápido. Há apenas tanta coisa para fazer antes de você
  ficar cansado.}
{109}{}{Nós passamos três horas na tela do personagem antes de o meu jogador finalmente ter decidido
  na verdade * jogar * o jogo.}
{110}{}{Ian era mais perigoso para *mim* do que os inimigos que estávamos a lutar. Espero que ele esteja morto, onde quer que ele
  esteja. }
{111}{}{Confira os músculos neste modelo de personagem que eu tenho. É tão exagerado, é ridículo!}
