{100}{}{Você vê um computador grande.}
{101}{}{Você vê o Sr. Chemmie!}
{102}{}{Um grande computador de elaboração para drogas.}
{200}{}{Olá, usuário! Eu sou o farmacêutico do futuro, Sr. Chemmie! Como posso ajudá-lo?!}
{201}{}{O que fazer?}
{210}{}{Eu faço drogas! Todos os tipos de drogas! Quando a vida te derrubar, o Sr. Chemmie está aqui para buscá-lo! Como o Sr. Chemmie trabalha ?! É simples! Tudo que você precisa é algum conhecimento científico e os ingredientes certos, então deixe o resto comigo! Continue! Me dê uma chance! E crianças, lembre-se de pedir a Mamãe ou Papai permissão antes de jogar com o Sr. Chemmie!}
{211}{}{Tudo bem, vou dar uma chance.}
{212}{}{Talvez mais tarde.}
{220}{}{Tudo bem! Vamos fazer drogas! O que você gostaria de criar?!}
{221}{}{Stimpak}
{222}{}{Super Stimpak}
{223}{}{Veneno}
{224}{}{Antídoto Do Veneno}
{225}{}{Kit De Primeiros Socorros}
{226}{}{Saco do médico}
{227}{}{Buffout}
{228}{}{Mentats}
{229}{}{Psycho}
{230}{}{Ótima escolha! Para fazer um Stimpak, por favor me alimente: uma Flor Broc, uma Raiz Xander e uma agulha Hypodermic vazia! Yum-yum!}
{231}{}{Fazer uma stimpak.}
{232}{}{Eu não tenho esses agora.}
{233}{}{Voltar para o menu.}
{240}{}{Ótima escolha! Para fazer um Super Stimpak, por favor me alimente: um Stimpak comum, um pedaço de fruta e um Nuka Cola! Yum-yum!}
{241}{}{Faça uma Super Stimpak.}
{250}{}{Ótima escolha! Para fazer Psycho, por favor me alimente: uma caixa de Mentats, um Buffout, um pedaço de Fruta e um Stimpak! Yum-yum!}
{251}{}{Faça um Psycho.}
{260}{}{Ótima escolha! Para fazer alguns Mentats, por favor me alimente: um Kit de Primeiros Socorros, um pedaço de Fruta e uma garrafa de Booze! Yum-yum!}
{262}{}{Fazer algumas Mentats.}
{263}{}{Sair}
{270}{}{Ótima escolha! Para fazer um saco de doutor, por favor me alimente: um Stimpak, um kit de primeiros socorros, uma agulha hipodérmica vazia e um antídoto venenoso! Yum-yum!}
{272}{}{Fazer Saco de um Médico.}
{280}{}{Ótima escolha! Para fazer um kit de primeiros socorros, por favor me alimente: um Stimpak, uma agulha Hypodermic vazia, um antídoto de veneno e um Rad Away! Yum-yum!}
{282}{}{Faça um Kit de Primeiros Socorros.}
{290}{}{Ótima escolha! Para fazer Veneno, por favor me alimente: uma agulha Hypodermic vazia, uma Cauda de Escorpião e uma Nuka Cola! Yum-yum!}
{292}{}{Fazer algum veneno.}
{300}{}{Grande escolha! Para fazer Buffout, por favor, me alimentar: um Kit de Primeiros Socorros, uma garrafa de Cerveja e um Nuka Cola! O Yum-yum!}
{302}{}{Fazer Buffout.}
{310}{}{Grande escolha! Para fazer Rad-X, por favor, me alimentar: um Kit de Primeiros Socorros e um Nuka Cola! O Yum-yum!}
{312}{}{Fazer um Rad-X.}
{320}{}{Grande escolha! Para fazer Rad Away, por favor, me alimentar: um Nuka Cola, uma agulha Hipodérmic Vazia e um Stimpak! O Yum-yum!}
{322}{}{Fazer um Rad Away.}
{330}{}{Grande escolha! Para fazer um Antídoto do Veneno, por favor, me alimentar: uma Cauda de Escorpião e uma garrafa de Booze! O Yum-yum!}
{331}{}{Fazer O Antídoto Do Veneno.}
{340}{}{Oh garoto! Um pedido especial! Que tipo de droga especial você gostaria que o Sr. Chemmie criasse para você hoje ?!}
{341}{}{Maconha.}
{342}{}{Químicos do médico.}
{343}{}{Meu amigo Cassidy tem um problema com seu coração. Você pode fazer algo para ajudá-lo?}
{344}{}{Inibidores da síndrome de rejeição ambiental.}
{350}{}{Esse é seu dia de sorte! Eu tenho produtos químicos suficientes em meus tanques de armazenamento para fazer isso! Você gostaria que o Sr. Chemmie os fizesse por você ?!}
{351}{}{Criar.}
{352}{}{Voltar para o Menu Principal.}
{360}{}{Uh-oh! Desculpe, mas não tenho mais os produtos químicos necessários para criar esses!}
{370}{}{Seleção criada! Foi divertido! Colecione o item da máquina! Obrigado por usar o Sr. Chemmie! Vamos fazer drogas novamente em algum momento!}
{371}{}{Mais Opções.}
{375}{}{O Sr. Chemmie gosta de ajudar! Eu posso criar uma substância chamada nitroglicerina, que irá controlar um batimento cardíaco irregular e prevenir ataques cardíacos!}
{380}{}{Rad-X}
{381}{}{Rad Away}
{382}{}{Algo Especial}
{383}{}{Nada}
{390}{}{Esse é seu dia de sorte! Tenho apenas produtos químicos suficientes em meus tanques de armazenamento para fazer um lote de ERSIs! Você gostaria que o Sr. Chemmie os fizesse por você ?!}
{391}{}{Criar.}
{392}{}{Sair.}
