{100}{}{Você vê uma porta.}
{101}{}{Você vê uma porta eletrônica.}
{102}{}{Você vê uma porta eletrônica com uma substituição, ativada por voz, bloqueio.}
{200}{}{Confirme o código:}
{201}{}{XY104FD}
{202}{}{BFN12}
{203}{}{Aberto}
{204}{}{Trigo}
{205}{}{Abre}
{206}{}{[FIM]}
{300}{}{Código de porta incorreto. Porta bloqueada. Entre em contato com o chefe de Relações Públicas para o código de substituição.}
{301}{}{[FIM]}
{400}{}{Confirme o código de substituição.}
{401}{}{[FIM]}
{402}{}{Esta porta está bloqueada eletronicamente.}
{403}{}{Destrancando a porta. Obrigado e tenha um dia agradável.}
{404}{}{[FIM]}
{500}{}{Não existe nenhum bloqueio para escolher.}
