{100}{}{Você vê um casal estranhamente saudável.}
{101}{}{Você vê Juan Cruz e Vikki Goldman, dois dos mais conhecidos astros de filmes de New Reno.}
{102}{}{Você vê um homem de cabelo escuro e uma mulher loira, ambos extremamente cativantes. Eles passam uma sensação vulgar de "venha cá".}
{103}{}{Ele: Oi! Eu sou Juan Cruz! Ela: E eu sou Vikki Goldman! Ambos: Nós somos celebridades! E nós apoiamos a Hubologia! Ambos: Por favor, note que quaisquer semelhanças entre nós e pessoas ou instituições, vivas ou mortas, é mera coincidência.}
{104}{}{Hã? Cuz? Doldnan?}
{105}{}{Celebridades? O que os torna celebridades?}
{106}{}{Semelhanças? Como assim?}
{107}{}{Eu quero me tornar um Hubologista. Como eu entro?}
{108}{}{Ei Vikki, o Dave H. está apaixonado por você.}
{109}{}{Beleza. Tenho que ir.}
{110}{}{Ele: Uma pobre criança das terras de ninguém. Ela: Talvez um alinhamento ajudaria? Ele: Sim. Ei, você. Você gostaria de fazer um alinhamento?}
{111}{}{Simmm!}
{112}{}{Não!}
{113}{}{Ela: Eu espero que tenha te ajudado. Boa sorte em suas viagens!}
{114}{}{Xau!}
{115}{}{Com certeza ajudou!}
{116}{}{Ele: Se você não quer nossa ajuda... Ela: ... então nós não podemos te ajudar. Tchau tchau.}
{117}{}{Adeus!}
{118}{}{Ele: Ta vendo? Os as coisas que aprendi no Hub mostraram seu valor novamente!}
{119}{}{Eu tenho algumas perguntas.}
{120}{}{Valeu! Tchau!}
{121}{}{Ela: Nós estávamos no ramo dos filmes em New Reno. Nós fizemos centenas de filmes, alguns deles considerados clássicos, como "Top Bam - Nádegas Indomáveis", "Negócio Excitado" e "Dias de Submissão". Por isso nós somos celebridades.}
{122}{}{Ele: Mas, como um membro da industria dos filmes, você já sabia disso.}
{123}{}{É legal finalmente poder dar rostos aos nomes.}
{124}{}{Quem se importa com o que VOCÊ recomenda? Não sou eu que deveria tomar minhas próprias decisões?}
{125}{}{Entendo. Bom, eu tenho mais algumas perguntas para você.}
{126}{}{Obrigado, tchau.}
{127}{}{Ela: Ah, sim, você definitivamente deveria tomar suas próprias decisões. Ele: E com as dicas do mais recente livro do Hub, você pode aprender como tomar a decisão CERTA!}
{128}{}{O livro mais recente dele? Ele não está morto?}
{129}{}{A decisão "certa". Claro. Mas e quanto ao livre arbítrio?}
{130}{}{Parece ótimo. Como eu participo?}
{131}{}{Certo. Eu tenho mais perguntas.}
{132}{}{Direito. Tchau.}
{133}{}{Ele: Mais perguntas? Nós temos todas as respostas! Providas pelas graças da Grande Roda, é claro.}
{134}{}{Como eu participo?}
{135}{}{O que os torna celebridades?}
{136}{}{Eu não deveria tomar minhas próprias decisões ao invés de seguir celebridades?}
{137}{}{Como eu participo?}
{138}{}{Ei Vikki, o Dave H. está apaixonado por você.}
{139}{}{Não, sem mais perguntas.}
{140}{}{Ela: [olhar vazio] Ele: Obrigado.}
{141}{}{Err... Eu tenho algumas perguntas.}
{142}{}{Isso é tudo! Até logo!}
{143}{}{Ele: Morto? Ha ha! Talvez. Nós acreditamos que ele teve seus neurodynos alinhados e foi se juntar ao Pai Estrela. Ela: Nós temos uma vasta quantidade de anotações e manuscritos escritos por Hub, com isso espalharemos suas palavras. Ele: Por exemplo, nós encontramos esse trecho que diz "2 duz. ovos/Leite/TP. Obviamente isso é importante e precisa ser ouvido.}
{144}{}{Err... ok. Eu tenho mais perguntas.}
{145}{}{Como é, só porque algum maluco escreveu qualquer porcaria vocês sentem a necessidade de publicar TUDO que ele escreveu?}
{146}{}{Sim! Louvado seja o Hub! Eu vejo a luz! Como eu participo?}
{147}{}{Direito. Tchau.}
{148}{}{Ele: Sim. Alguns podem até pensar que nós nos assemelhamos com certas pessoas. Ela: Mas a verdade é que é mera coincidência.}
{149}{}{Ufa. Bem, isso tirou um peso das minhas costas. Eu tenho mais perguntas.}
{150}{}{Entendi. Até logo.}
{151}{}{Ela: É claro que você possui livre arbítrio. Você tem a escolha de permitir que seus neurodynos sejam preenchidos com a imundície desse mundo. Ele: Você tem a opção de viver uma vida sem felicidade, uma vida sem sentido nessa corrida sem fim. Ambos: Ou você pode alcançar uma maior compreensão da vida através da Grande Roda.}
{152}{}{Neurodynos? O que é isso?}
{153}{}{Parece ótimo. Como eu participo?}
{154}{}{Hum. Acho que eu prefiro a corrida sem fim.}
{155}{}{Tá certo. Bem, tenho que ir.}
{156}{}{Ela: Como ousa chamar o Hub (louvado seja seu nome) de maluco? Aqui dentro? Na fortaleza dos devotados aos seus ensinamentos? Ele: Caia fora daqui. Se você falar com alguém no seu caminho para fora, você será castigado. Infiel. Ambos: Vai tarde.}
{157}{}{Talvez seja melhor eu pular neles. Eu sempre odiei seus filmes mesmo. Vamos ver vocês atuarem em uma cena de morte.}
{158}{}{Seus filmes são uma bosta. Tchau.}
{159}{}{Adeus.}
{160}{}{Ela: Neurodynos são a essência das almas destruídas na Grande Guerra, poluindo sua essência espiritual e te guiando para o mau caminho. Ele: Se você quiser saber mais sobre os nossos ensinamentos, você terá que se juntar à nossa igreja.}
{161}{}{Sim, isso parece fascinante.}
{162}{}{Eu ouvi dizer que isso era ficção científica, mas eu não sabia o quanto. Esse Hub deve ter sido um grande maluco.}
{163}{}{Bem, eu certamente estou curioso sobre o que você tem para me mostrar. Conte comigo.}
{164}{}{Hum. Nem, agora não. Entretanto, eu tenho mais perguntas.}
{165}{}{Hum... tenho que ir. Tchau.}
{166}{}{Ele: Isso é muito idealista de sua parte. Ela: Muito culto. Ele: Nós oferecemos nossas opiniões para as pessoas - e se as nossas celebridades podem atrair mais fiéis, estamos ansiosos para usá-las.}
{167}{}{Tenho outras perguntas.}
{168}{}{Estou interessado em participar.}
{169}{}{Entendo. Bem, até mais.}
{170}{}{Ele: Bem, é muito simples. Nós apenas lhe damos este holodisco informativo. Ela: ... você assiste um filmezinho... Ele: ... aí então você fala com o AHS-7! Ela: Fácil, não é?}
{171}{}{Vamos lá.}
{172}{}{Acho que não estou pronto para isso.}
{173}{}{Ela: Esse é um direito seu. Ele: E eu espero que você entenda que você não está autorizado a vagar pela nossa base. Ela: Então é melhor você sair - os guardas provavelmente vão atirar em você caso fique por aqui.}
{174}{}{Caramba, valeu. Me convidam para participar e atiram em mim caso eu não aceite? Que belo gesto.}
{175}{}{Então acho que é melhor eu atirar em vocês primeiro.}
{176}{}{To caindo fora daqui.}
{177}{}{Ele: Essa é sua última chance de mudar de ideia. Ela: Nós odiaríamos que algo de ruim te acontecesse.}
{178}{}{Que se dane.}
{179}{}{Certo. Como eu participo?}
{180}{}{Algo de ruim está prestes a acontecer com VOCÊ.}
{181}{}{Nem. Eu prefiro correr esse risco. Té mais.}
{182}{}{Ele: Nós fizemos tudo o que podemos por você. Ela: Boa sorte em suas viagens.}
{183}{}{Adeus!}
{184}{}{Ela: Dave? O cara da informática? Ele: Ha ha! Que perdedor! Vikki é minha, toda minha - de jeito nenhum ele vai... me perdoe, isso é energia negativa que estou canalizando. Eu devo ter sujado meus neurodynos. Ela: [sussurra para você] Eu acho que Dave é um fofo, mas nada pode acontecer enquanto Juan estiver por perto. Ele: Ufa. Meus neurodynos estão limpos novamente.}
{185}{}{Bem, eu tenho mais perguntas.}
{186}{}{Isso é tudo. Tchau.}
{187}{}{Ela: Isso não foi tão ruim, foi? Ele: Agora vá falar com o AHS-7 e nós seremos companheiros na Hubologia! Ela: Estou tão animada! Ele: Conseguir novos recrutas me deixa com tesão. Ela: Oh, doçura... Ele: Oh, querida...}
{188}{}{Eu volto mais tarde.}
{189}{}{Ele: Que pena. Ela: Você está comprometido agora.}
{190}{}{-FEITO-}
{191}{}{Ele: Você fez uma escolha que vai mudar a sua vida. Ela: Infelizmente, foi a escolha errada. Ambos: Guardas! Guardas!}
{192}{}{Porra.}
{193}{}{Ele: Saudações,}
{194}{}{Então o que eu faço agora que sou um Hubologista?}
{195}{}{Como faço para me juntar a vocês?}
{196}{}{Isso era tudo que eu queria. Até logo!}
{197}{}{}
{198}{}{}
{199}{}{Ele: Você poderia falar com Harry Foguete na superfície. Talvez ele precise de ajuda. Ela: Ou você poderia falar com o AHS-7 ou o AHS-9. Eles geralmente têm idéias. Ele: Ou você pode assistir ao Cine-Oração. Ela: Ou você poderia causar discórdia entre os inimigos da Grande Roda.}
{200}{}{Agradeço. Como eu faço para me unir a vocês?}
{201}{}{Obrigado. Isso é tudo que eu queria saber.}
{202}{}{Ela: Por mais triste que seja - porque o Pai Estrela sabe que você é uma gracinha - nós provavelmente não deveríamos. Ele: Mas estamos ambos lisonjeados. Ela: Talvez outra hora nós poderíamos ir todos até New Reno e filmar um filme juntos.}
{203}{}{Ah, tudo certo. O que mais tem para fazer como um Hubologista?}
{204}{}{Ah, tudo certo. Até logo.}
{205}{}{Ela: Mentir faz mal para seus neurodynos. Ele: É verdade. Ela: É por isso que eu devo ser honesta e dizer que eu não te acho atraente. Ele: Porém mesmo assim nós te amamos como um colega seguidor do Hub!}
{206}{}{Nossa, obrigado. Então o que mais tem para fazer como um Hubologista?}
{207}{}{Que seja. [murmurando] babacas.}
{208}{}{Saudações, novatos!}
{209}{}{Eu sou Vikki Goldman!}
{210}{}{E eu sou Juan Cruz!}
{211}{}{Nós somos celebridades, como vocês sabem.}
{212}{}{Nós achamos que a Hubologia é o caminho certo.}
{213}{}{Nós SABEMOS que a Hubologia é o caminho certo.}
{214}{}{Eu posso fritar insetos com minhas habilidades mentais!}
{215}{}{Eu fico bem de chapéu de papel alumínio!}
{216}{}{Talvez se você se esforçar em melhorar a si mesmo, você possa se associar à nós.}
{217}{}{Com certeza nós gostaríamos disso.}
{218}{}{Sim. Nós estamos sempre a procura de novos amigos...}
{219}{}{... contanto que eles estejam dispostos a melhorar a si mesmos.}
{220}{}{E tenham a classificação tão boa quanto a nossa.}
{221}{}{Nós somos AHS-5.}
{222}{}{Um dia você poderá tornar-se AHS-5 também.}
{223}{}{Se você nos doar muito dinheiro, você poderá se tornar AHS-5 ainda mais rápido.}
{224}{}{Mas não fique achando que só queremos você pelo seu dinheiro.}
{225}{}{Não, nós queremos te AJUDAR.}
{226}{}{E é disso que se trata a Hubologia.}
{227}{}{[aplausos]}
{228}{}{. Eu espero que vocês estejam aprendendo bem. Ela: Nós temos tantas... muitas... esperanças em vocês.}
{229}{}{Lição 1: Aqui é onde está a eternidade, a Grande Roda. [aponta para algo] E aqui é onde nós estamos. [aponta para algo] Agora tudo que temos que fazer é uma longa jornada e nos unirmos aos nossos irmãos estrelados ao fim do caminho.}
{230}{}{Cara, nós vamos precisar de muitos sapatos.}
{231}{}{Ele: Agora vá falar com AHS-7 e nós seremos companheiros de Hubologia! Ela: Estou tão empolgada! Ele: Conseguir novos recrutas me deixa com tesão. Ela: Oh, docinho. Ele: Oh, querida...}
