{100}{}{Você vê um guarda com roupas soltas, usando um olhar de tédio cauteloso.}
{101}{}{Você vê um guarda do palácio.}
{102}{}{Você vê um guarda do palácio carregando uma arma de aparência perigosa.}
{103}{}{Apenas continue andando e não haverá problema.}
{104}{}{Você tem negócios aqui?}
{105}{}{Estamos de olho em você.}
{106}{}{Não tente nada engraçado.}
{107}{}{Tratar o nosso povo com respeito.}
{108}{}{Não toque nisso. É seu último aviso.}
{109}{}{Fique longe daí.}
{110}{}{Um passo atrás, forasteiro.}
{111}{}{Se afaste bem lentamente.}
{112}{}{Nem pense nisso.}
{113}{}{Pare aí. Agora.}
{114}{}{Morra, inimigo do povo!}
{115}{}{Estou te mandando para o inferno do metal quente!}
{116}{}{Que o Buda tenha piedade do seu espírito!}
{117}{}{Sofra, inimigo!}
