{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê a estação biológica.}
{102}{}{Você vê um terminal de computador em funcionamento.}
{103}{}{Olá. Por favor, confirme sua identidade.}
{104}{}{[Oooh! Olhe todas essas luzes ofuscantes!]}
{105}{}{::adivinhar a senha::}
{106}{}{INTLVR-Dnky-Pnch-98790}
{107}{}{::hackear o computador::}
{108}{}{Desconectar}
{109}{}{Informação a procurar: -Programa Botânico- -Programa Genético- -Programa Xeno-}
{110}{}{Programa Botânico.}
{111}{}{Programa Genético.}
{112}{}{Xeno program.}
{113}{}{Nota pessoal.}
{114}{}{Desativar estação.}
{115}{}{Senha incorreta. Favor falar com o administrador do sistema. Até logo.}
{116}{}{::hackear o computador::}
{117}{}{::sair::}
{118}{}{Alerta de intruso ativado. Desligando. Tenha um bom dia.}
{119}{}{-pronto-}
{120}{}{(after about twenty minutes, you discover this: Initial results of botanical radiation disruption prove unpromising. Dr. Sheng develops radiation resistant plant-life - unpleasant side-effects follow. Resultant plant life deemed too dangerous. Sheng insists on pursuing line and mixing it with genetic program.)}
{121}{}{Programa Genético.}
{122}{}{Xeno program.}
{123}{}{Nota pessoal.}
{124}{}{Voltar.}
{125}{}{(cerca de vinte minutos depois você juntou estas informações: Usando o básico do vírus FEV, Dr. Long Wang está convencido do sucesso em criar soldados mutantes. Ele criou um soro que forneceu resultados interessantes em roedores. Ele injetou em si mesmo e se desfez em gosma. Dr. Sheng desativou os inquéritos. Com a morte do Dr. Long, Dr. Shendg está no comando. Sheng exige foco na radiação consumida por plantas.)}
{126}{}{Programa Botânico.}
{127}{}{Xeno program.}
{128}{}{Nota pessoal.}
{129}{}{Voltar.}
{130}{}{"O conteúdo no qual esperávamos estabelecer séries de experimentos significativos desapareceram, presumo que ainda destruídos ou roubados por Hubologistas. Investigações mais profundas fracassaram. Until such time as further specimens are obtained, this database will remain inoperative."#essa última parte aí tá osso.
- Dr. Sheng}
{131}{}{Programa Botânico.}
{132}{}{Programa Genético.}
{133}{}{Nota pessoal.}
{134}{}{Voltar.}
{135}{}{Dr. Wong: Novo cabeça do Projeto Biológico, junto com a Pesquisa Física.
Dr. Sheng: Cabeça do Projeto Biológico até dois meses atrás. One month sabbatical with new "botany sentience serum" accounted for; further absence a puzzle. Dr. Wong assumes control of Biology Program.
Dr. Long: Recently deceased via FEV serum.}
{136}{}{Programa Botânico.}
{137}{}{Programa Genético.}
{138}{}{Xeno program.}
{139}{}{Voltar.}
{140}{}{Estação desativada.}
{141}{}{Ativar estação.}
{142}{}{-sair-}
{143}{}{[Seus dedos digitam a senha correta nas teclas... sua sorte é incrível!]}
{144}{}{-mais-}
{145}{}{O computador não responde a nenhum comando.}
{146}{}{Você não consegue achar nenhum lugar pra colocar isso.}
