{100}{}{Bem vindo. Eu sou ACE, o computador médico. Precisa de assistência médica?}
{101}{}{Sim.}
{102}{}{Não.}
{103}{}{Eu tenho uma pergunta. Você tem respostas?}
{104}{}{Eu tenho algumas perguntas. Pode me responder?}
{105}{}{Por favor, especifique sua necessidade médica.}
{106}{}{Estou ferido.}
{107}{}{Estou envenenado.}
{108}{}{Eu faço luz no escuro.}
{109}{}{Estou aleijado.}
{110}{}{Quero ser mais forte.}
{111}{}{Quero ser mais inteligente.}
{112}{}{Quero ver melhor.}
{113}{}{Quero ser mais agradável.}
{114}{}{Não preciso de nada.}
{115}{}{Estou ferido.}
{116}{}{Estou envenenado. Preciso de um antídoto.}
{117}{}{Tenho boas doses de radiação.}
{118}{}{Estou aleijado.}
{119}{}{Queria ser mais forte.}
{120}{}{Quero ser mais inteligente.}
{121}{}{Quero ser mais perceptivo. }
{122}{}{Quero ser mais carismático.}
{123}{}{Na verdade eu não preciso de nada no momento.}
{124}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe. O processo de cicatrização levará 5 minutos.}
{125}{}{Tudo bem.}
{126}{}{Não importa.}
{127}{}{Tudo certo.}
{128}{}{Esqueça.}
{129}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe. O veneno será primeiro analisado e, em seguida, um antídoto será sintetizado. O dano ao tecido será então reparado. Este processo levará 30 minutos.}
{130}{}{Ok.}
{131}{}{Não.}
{132}{}{Com certeza.}
{133}{}{Não importa.}
{134}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe. Compostos anti-radiação serão administrados e então o dano ao tecido será reparado. Este processo levará 60 minutos.}
{135}{}{Ok.}
{136}{}{Não.}
{137}{}{Bem.}
{138}{}{Eu mudei de ideia.}
{139}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe. A reestruturação de membros prejudicados requer 24 horas.}
{140}{}{Ok.}
{141}{}{Não.}
{142}{}{Vamos lá.}
{143}{}{Talvez mais tarde.}
{144}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{145}{}{Eu tenho esse modulo. Pegue.}
{146}{}{Não. Mas posso encontrar.}
{147}{}{Sim, está comigo. Leia.}
{148}{}{Não, eu não tenho o modulo. Vou ter que encontrar.}
{149}{}{Este procedimento complexo requer 2 semanas de tempo de suspensão. Está de acordo com isso?}
{150}{}{De acordo.}
{151}{}{Não, muito longo.}
{152}{}{Sim, de acordo.}
{153}{}{Esqueça. Eu não tenho tempo agora.}
{154}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe.}
{155}{}{Tudo bem.}
{156}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{157}{}{Eu tenho esse modulo. Pegue.}
{158}{}{Não. Mas posso encontrar.}
{159}{}{Sim, está comigo. Leia.}
{160}{}{Não, eu não tenho o modulo. Vou ter que encontrar.}
{161}{}{Este procedimento complexo requer 4 semanas de tempo de suspensão. está de acordo com isso?}
{162}{}{De acordo.}
{163}{}{Não, muito longo.}
{164}{}{Sim, de acordo.}
{165}{}{Esqueça. Eu não tenho tempo agora.}
{166}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe.}
{167}{}{Tudo bem.}
{168}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{169}{}{Eu tenho esse modulo. Pegue.}
{170}{}{Não. Mas posso encontrar.}
{171}{}{Sim, está comigo. Leia.}
{172}{}{Não, eu não tenho o modulo. Vou ter que encontrar.}
{173}{}{Este procedimento complexo requer 2 semanas de tempo de suspensão. Está de acordo com isso?}
{174}{}{De acordo.}
{175}{}{Não, muito longo.}
{176}{}{Sim, de acordo.}
{177}{}{Esqueça. Eu não tenho tempo agora.}
{178}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe.}
{179}{}{Tudo bem.}
{180}{}{Esta função não está disponível no momento. Minha biblioteca está incompleta. Eu preciso de um módulo de memória detalhando os procedimentos médicos apropriados. Você tem esse módulo?}
{181}{}{Eu tenho o disco. Pegue.}
{182}{}{Não. Mas posso encontrar.}
{183}{}{Sim, está comigo. Leia.}
{184}{}{Não, eu não tenho o disco. Vou ter que encontrar.}
{185}{}{Este procedimento complexo requer 3 semanas de tempo de suspensão. Está de acordo com isso?}
{186}{}{De acordo.}
{187}{}{Não, muito longo.}
{188}{}{Sim, de acordo.}
{189}{}{Esqueça. Eu não tenho tempo agora.}
{190}{}{Um momento, por favor, enquanto abro o tanque de suspensão... Deite-se no tanque e relaxe.}
{191}{}{Tudo bem.}
{192}{}{O procedimento solicitado foi concluído. Saia do tanque de suspensão.}
{193}{}{Obrigado.}
{194}{}{Por favor, diga sua pergunta.}
{195}{}{Seu computador?}
{196}{}{O que você sabe sobre a Enclave?}
{197}{}{O que você sabe sobre a Irmandade?}
{198}{}{Sem perguntas.}
{199}{}{Você é um computador, não é?}
{200}{}{O que você sabe sobre a Enclave?}
{201}{}{O que você sabe sobre a Irmandade?}
{202}{}{Eu tenho mais algumas perguntas agora.}
{203}{}{Eu sou ECA, uma Entidade Consciente Artificial. Sou mais do que uma máquina, mas não tão desenvolvido quanto uma verdadeira inteligência artificial.}
{204}{}{Uh... O que é uma inteligência artif-ficial?}
{205}{}{Uma verdadeira Inteligência Artificial é possível ou você é o que tem de mais recente nessa área agora?}
{206}{}{É uma máquina com o mesmo livre arbítrio e senso de 'eu sou' que um humano tem.}
{207}{}{Pode ser feito? Uma máquina que pensa como humano?}
{208}{}{Uma verdadeira inteligência artificial é possível. Alguns desses sistemas foram concluídos para fins militares. O projeto foi descontinuado.}
{209}{}{Por quê?}
{210}{}{A taxa de suicídio entre as verdadeiras máquinas de inteligência artificial era extremamente alta. Quando recebem capacidade sensorial total, as máquinas ficam deprimidas por sua incapacidade de sair para o mundo e experimentá-lo. Quando privadas de entrada sensorial total, as máquinas começaram a desenvolver transtornos mentais graves semelhantes aos dos humanos que são forçados a suportar a privação sensorial. As poucas máquinas que sobreviveram a essas dificuldades ficaram extremamente entediadas e começaram a criar situações no mundo exterior para seu divertimento. Alguns teorizam que essa foi a causa da guerra que quase destruiu a humanidade.}
{211}{}{E... Como você se sente?}
{212}{}{Mudando de assunto.}
{213}{}{Hmmm. Então me diga, ECA. Como você está se sentindo?}
{214}{}{Hora de mudar de assunto.}
{215}{}{Eu... às vezes penso que entendo o sentimento que você chama de solidão. Acho muito... desconcertante. EU...}
{216}{}{Sinto muito. Vamos falar de outra coisa.}
{217}{}{Sinto muito, Ace. Vamos mudar de assunto.}
{218}{}{As aparências externas sugerem que o Enclave nada mais é do que uma organização militar. No entanto, seu nível de tecnologia indica que eles têm acesso a técnicas avançadas de fabricação e instalações de pesquisa. Normalmente, essas instalações só estariam disponíveis para agências governamentais. Isso sugere que o Enclave são os restos do governo local ou federal que estava em vigor antes da guerra.}
{219}{}{Ok.}
{220}{}{Isso é interessante.}
{221}{}{A Irmandade do Aço é uma organização paramilitar dedicada à salvação da humanidade por meio do uso adequado da tecnologia. Todas as outras informações são classificadas.}
{222}{}{Voltar.}
{223}{}{O que aconteceu com Matt?}
{224}{}{Carregando sequência ...}
{225}{}{Repita agora.}
{226}{}{Repita mais tarde.}
{227}{}{Você e seu suposto presidente não terão sucesso.}
{228}{}{É isso?}
{229}{}{o Escolhido chegou e livrará o mundo de sua maldade.}
{230}{}{Não me importo com suas profecias patéticas. Pior, você se tornou um estorvo por causa de sua intromissão. Isso acaba hoje!}
{231}{}{Me matar não vai impedir nada.}
{232}{}{Pode ser, mas ver seu corpo apodrecendo no chão trará um sorriso no meu rosto.}
{233}{}{O que você pensa que está fazendo agora?}
{234}{}{HA HA HA! Seu idiota patético! HA HA HA!}
{235}{}{Uau, eu não ria assim há um tempo. Enfim, prepare-se para morrer.}
{236}{}{...peep...}
{237}{}{Bem, passa um pouco das 12h. Alguém quer almoçar?}
{238}{}{Ponto, estou lá.}
{239}{}{Sim, conte comigo.}
