{100}{}{Você vê um sistema de entrada sem chave. Uma placa diz "Use Tanker Fob aqui"}
{101}{}{Você vê um sistema de entrada sem chave. Uma placa diz "Use Tanker Fob aqui"}
{102}{}{Este console tem uma placa preta presa a ele com uma luz vermelha na parte superior. Uma placa diz "Use Tanker Fob aqui"}
{103}{}{Este console tem uma placa preta presa a ele com uma luz verde na parte superior. Uma placa diz "Use Tanker Fob aqui"}
{104}{}{[clique] A luz no painel preto fica verde.}
{105}{}{[clique] A luz no painel preto fica vermelha.}
{106}{}{Nada acontece.}
{107}{}{Isso não funciona.}
{108}{}{É um sistema de porta sem chave remoto. Isso geralmente requer algum tipo de chave magnética.}
