{100}{}{Você vê um estranho large molerat.}
{101}{}{Você vê O Cérebro.}
{102}{}{Você vê um enorme, albino molerat. Ele parece ter um crânio inchado e tem uma aparência particularmente
 inteligente.}
{110}{}{Você é mais imprudente do que a maioria do seu tipo para cruzar no meu caminho. Agora você deve morrer.}
{120}{}{Eu não sei como você chegou aqui - mas deve ser capaz de encontrar o mesmo caminho de volta.}
{121}{}{Eu não tenho tempo para suas incomodações. Estou planejando uma maneira de dominar o mundo. Vá embora.}
{122}{}{Não me incomode. Não vou alertá-lo de novo.}
{123}{}{Já chega. Zomak! Mate-o para mim!}
{130}{}{A Renovação lhe é permitida. Mas você não a conseguirá enquanto não reparar nosso Reator
 Nuclear. (para ele mesmo) Humanos... São tão decepcionantes... }
{131}{}{Concertar o Reator Nuclear?}
{132}{}{Ah sim. Bem, vou indo então. Tchau.}
{140}{}{Eu sinto o cheiro de um dos meus Talismans em você, mas não me lembro de ter lhe dado um.}
{141}{}{Eu o achei.}
{142}{}{Hum, você deve ter se esquecido.}
{143}{}{É só meu pós-barba. Rato Velho —- gostou dele?}
{144}{}{Eu matei um dos seus zangões e peguei isso de seu corpo ainda quente.}
{145}{}{Peguei em uma vila perto de Vault City. As pessoas de lá disseram que seus seguidores deixaram isso com eles.}
{150}{}{Está pronto para tornar-se um de nós?}
{151}{}{Eu nasci pronto. Onde eu assino?}
{152}{}{Você quer dizer, tornar-me um rato gigante?}
{153}{}{Eu não quero parte alguma do que você é.}
{154}{}{Quem somos nós, hã, quero dizer, vocês?}
{160}{}{Para sobreviver, tanto Gecko quanto Vault City vão precisar cooperar. Vault City precisa da 
 energia do nosso Reator Nuclear para poder expandir, e nós precisamos da tecnologia médica de Vault City.A menos
 que ambos cooperem, ambas as cidades vão estagnar. Vault City precisa nos ajudar a repara nossa Usina.}
{161}{}{Como você vai convencê-los a fazer isso?}
{170}{}{Eu sou conhecido simplesmente como O Cérebro. Um tributo à minha genialidade. Algumas coisas em Gecko e um pouco mais
 fora da cidade fazem minha fama.}
{171}{}{Mas você é apenas um rato gigante.}
{172}{}{Você disse algo sobre juntar-se a você?}
{180}{}{Não me importa onde você o encontrou. A questão é se você pretende juntar-se a nós e usá-lo
 seriamente. }
{181}{}{Juntar-me a vocês? O que quer dizer com isso?}
{182}{}{Eu prefiro limpar sua gaiola a  me juntar a vocês.}
{183}{}{Depende. As patrulhas de Vault City continuam sendo atacadas por ratos toupeira. Presumo que você esteja por trás disso?}
{184}{}{Claro que estou. Tudo parte do meu grande plano para dominar o mundo. Eu não esperaria que um cérebro humano deficiente como o seu entendesse. Mas, ai de mim, qual é a sua preocupação?}
{185}{}{Eu só quero que seus ratos toupeira parem de atacar as patrulhas de Vault City.}
{186}{}{Você? Interessante... Tudo bem, proponho um acordo, humano. Devo atender ao seu pedido, *se* você completar uma certa tarefa para mim.}
{187}{}{O que você quer que eu faça?}
{188}{}{Olha, nós tínhamos um acordo - eu conserto o reator, e você tira seus bichos daqui. Eu fiz minha parte no trato, agora é a sua vez.}
{189}{}{O reator está consertado, sim. Mas está otimizado? Não, creio que não. Eu disse que cancelaria meus ratos toupeira quando você *concluísse* a tarefa. Terminar pela metade não é bom para mim.}
{190}{}{Bem, como parte do meu plano de governar o mundo, eu pretendo recompensar meus seguidores ghouls achando um
 modo de recuperar a humanidade deles.}
{191}{}{Como você vai fazer isso?}
{200}{}{Quando eu unir Gecko e Vault City sob o meu comando, vou dedicar os laboratórios médicos de Vault City
 para buscar um meio de reverter os efeitos da radiação que transformou as pessoas em ghouls. Eles serão
 renovados, renascidos como humanos mais uma vez.}
{201}{}{Isso não soa tão mal.}
{210}{}{O Ankh é um símbolo da vida. A partir do momento em que lhe dou esse talismã, você será um de nós. E seus
 companheiros irão ajudá-lo para chegar ao camindo da Renovação. Mas tenha cuidado para quem você o
 mostra.}
{211}{}{Você está pronto para aceitar a Renovação e usar o Talismã Ankh?}
{212}{}{Certo, eu vou aceitar o seu talismã.}
{213}{}{Eu não quero me Renovar. Gosto de mim do jeito que sou. Não quero seu talismã.}
{214}{}{Renovação? Como assim?}
{220}{}{Aqueles tolos de Vault City apenas assinaram seus mandatos de morte destruindo nosso reator.}
{221}{}{Agora eu tenho que pensar em outro meio de dominar o mundo. Saia.}
{222}{}{Já tive o bastante de sua intromissão desagradável. Zomak! Mate esse tolo para mim.}
{230}{}{Reparar o reator foi o primeiro e importante passo. Mais um é necessário para assegurar a
 sobrevivência de Gecko e Vault City.}
{231}{}{Mais um passo?}
{232}{}{Aren’t you the concerned citizen all of a sudden.}
{233}{}{Eu acho que já fiz o suficiente. Tchau.}
{234}{}{Por que um rato-gigante falante está tão preocupado com tudo isso?}
{240}{}{Você fez bem. Vault City e Gecko têm motivos para alegrarem-se. Com nosso reator funcionando
 com eficiência máxima, meu plano de dominar o mundo pode estar próximo de se realizar. Agora você pode ir. Tenho trabalho a
 fazer.}
{241}{}{Bem, eu não fiz isso pra você. Tchau..}
{242}{}{Grandes planos para um rato super-desenvolvido. Tchau.}
{250}{}{Bem, o reator está funcionando -- mas não eficientemente. Vamos precisar do computador central de Vault City
 para analisar o relatório computadorizado.}
{251}{}{O computador central de Vault City. Tenho certeza de que aquelas pessoas de mente aberta ficariam felizes em ajudar
 um rato-gigante mutante e uma cidade repleta de ghouls.}
{252}{}{Como você pretende fazer com que isso aconteça?}
{260}{}{Concerned citizen? In a way. In order to take over the world, I have to make sure that there’s
 something worth taking over. I need to build a strong powerbase using Gecko and Vault City.}
{261}{}{Um rato tramando dominar o mundo?}
{270}{}{Bem, apesar dos seus sentimentos sobre um roedor dominar o mundo, as ações que eu proponho beneficiarão
 milhares de cidadãos de Vault City e Gecko. Você pode não se importar comigo ou com meus motivos, mas ainda assim
 os resultados são promissores.}
{271}{}{Por que você não me conta sobre esse último passo e eu pensarei em ajudar.}
{272}{}{Eu tenho nojo só de pensar que eu já lhe ajudei de alguma forma. Eu estou indo.
 Tchau.}
{280}{}{Bem, eles deixarão se você mostrar a eles o quanto isso pode beneficiá-los. Nós temos um relatório
 econômico que prova que a otimização da usina atômica de Gecko irá beneficiar Vault City diretamente. Deixarei
 nossos companheiros aqui de Gecko saberem da sua missão.}
{281}{}{Eles darão a você um Hydroelectric Magnetosphere Regulator se puder provar os benefícios a Vault City. Eu preparei
 um relatório econômico que detalha como o reparo beneficia Vault City. Deixarei que
 nossos companheiros aqui de Gecko saibam de sua missão.}
{282}{}{Isso é ótimo, mas quem em Vault City poderia ao menos pensar em ler essa coisa?}
{283}{}{Por que você não fala com aquele velho chato, aquele saco fedido, o Festus, na  Usina e
 veja se ele cospe alguma informação útil daquele crânio podre. Ele deve saber os motivos para fazer a  otimização da Usina.
 Deixarei que nossos companheiros aqui de Gecko saberem da sua missão.}
{284}{}{Isso parece ser um boa idéia. Tchau.}
{290}{}{Acho que aquele McClure é o único membro do Concelho em Vault City com cérebro suficiente capaz de
 ver além de seus preconceitos. Ele lhe dará o que você precisa.}
{291}{}{De jeito nenhum eu serei o seu mensageiro.}
{292}{}{Bem, eu acho que vale a pena. Onde eu pego o disco?}
{300}{}{Você precisa ir um pouco acima, em junkyard. Procure um ghoul chamado Gordon. Ele tem o Economic
 Data Disk que você precisa. Você terá meu talismã, ele saberá que tem que te dar o disco.}
{301}{}{Que talismã?}
{310}{}{Você tem certeza que quer mandar os cidadão de ambas as cidades a uma morte lenta?}
{311}{}{Bem, eu acho que não. Certo, conte-me onde eu pego o disco.}
{312}{}{Melhor uma morte lenta a ser mandado por um rato. Tchau.}
{320}{}{(Sniff, sniff) Hmmm, Eu sinto o nítido aroma de Cheezy Poofs em você. Por acaso você
 não teria algum sobrando, teria? Eu simplesmente amo Cheezy Poofs.}
{321}{}{Hmm, não. Nenhum Cheezy Poofs aqui.}
{322}{}{Eu acho que poderia dividir um pouco de Cheezy Poofs.}
{330}{}{Agora você é um de nós. Filho, eu vou dominar o mundo e todos você serão Renovados.}
{331}{}{Hã, é. Qualquer coisa que você disser.}
{332}{}{Pronto. Já chega. Isso pára aqui. Alguém tem que dar um fim a sua existência... -—
 e esse alguém sou eu.}
{340}{}{Bem, eu suponho que não temos nada mais a dizer um ao outro. Mas você sabe que eu não
 posso permitir que você saia daqui vivo, a menos que você seja um de nós.}
{341}{}{Prefiro morrer a me juntar a você.}
{342}{}{Hmm, talvez eu tenha sido apressado em meu julgamento.}
{343}{}{Cai dentro, Willard.}
{350}{}{Seu tolo. Zomak! Mate esse intruso para mim.}
{360}{}{Vocês humanos tem tolerâncias limitadas. Eu poderia ter permanecido um rato se vocês
 não tivessem feito o melhor para destruir o mundo. Se não fosse pela radiação, eu não seria
 o que sou hoje.}
{361}{}{Explique-me isso, exatamente?}
{370}{}{Agora que tudo foi explicado a você, está pronto para se juntar a nós?}
{371}{}{Bem, eu suponho que sim.}
{372}{}{Estou convencido, tudo bem. Convencido de que eu tenho que dar o fora desse hospício.}
{380}{}{Eu era apenas um de muitos ratos normais em um laboratório de pesquisas avançadas. Então, um dia, houve
 explosões. Nossa gaiolas quebraram, e nós fomos encharcados com um tipo de fluido de uma enorme tina.}
{381}{}{Então o que ?}
{390}{}{Eu me arrastei para fora. Quando comecei a me recuperar, notei que eu tinha mudado. Eu tentei me comunicar com
 pessoas, mas elas só tentavam me matar. Humanos são muito violentos para sobreviver sob sua própria
 liderança -- mas essa é outra história. O primeiro passo é reparar o reator.}
{391}{}{Reparar o reator?}
{400}{}{Sim. Você deve pegar o Hydroelectric Magnetosphere Regulator em Vault City para poder reapara o reator de Gecko. Se não o fizer, Vault City vai, sem dúvida, atacar Gecko. É claro, destruindo o reator, eles se destinarão à ruina com o passar do tempo.}
{401}{}{Eles vão se condenar? O que quer dizer?}
{402}{}{Por que Vault City me daria uma peça da Usina de Gecko??}
{410}{}{Você tem que mostrá-los que isso os ajuda em seus interesses. Pessoas são fácilmente
 manipuladas quando se diz respeito a interesse próprio.}
{411}{}{Eu não acho que as pessoas em Vault City me darão a peça para sua usina atômica.}
{420}{}{Mas agora, você não tem nada a fazer?}
{421}{}{Hã, eu acho melhor eu ir buscar aquela coisa da usina. Tchau.}
{422}{}{Certamente que tenho. Eu tenho que dar o fora daqui.}
{430}{}{Meu nariz é muito eficaz. Estou certo de que você tem Cheezy Poofs. Dê-me um pouco. Por favor.}
{431}{}{O único jeito de você conseguir meu Cheezy Poofs é pegando-o dos meus dedos gelados e sem vida.}
{432}{}{Oh, ei. O que é isso no meu bolso? Na verdade acho que tenho um pouco de Cheezy Poofs. Você quer?}
{440}{}{(crunch, munch, crunch) Mmmm, eu amo Cheezy Poofs, eles são tão, bem, uh, Cheesy. Por causa disso, você
 deve se tornar um membro do meu culto especial, e pode me ajudar a dominar o mundo.}
{441}{}{(crunch, munch, crunch) Mmmm, eu amo Cheezy Poofs, eles são tão, bem, uh, Cheesy. Eu fui sábio ao
 permitir que você se juntasse ao meu culto. Você não tinha algo pra fazer?}
{442}{}{(crunch, munch, crunch) Mmmm, eu amo Cheezy Poofs, eles são tão, bem, uh, Cheesy.}
{443}{}{(crunch, munch, crunch) Mmmm, eu amo Cheezy Poofs, eles são tão, bem, uh, Cheesy.}
{444}{}{Uh...}
{450}{}{Que assim seja. Zomak! Mate este tolo para mim. Mas cuidado com o Cheezy Poofs!}
{460}{}{Você deve usar o Reactor Data disck no computador central de Vault City. Você pode entrar
 escondido e usá-lo, ou pode falar com McClure, se tiver o Economic Data disk.}
{461}{}{Economic Data disk?}
{462}{}{Ah, tudo bem.}
{463}{}{Apenas leve o Analyzed Reactor Data disk para o Festus e ele vai inserir a informação para fazer o
 reator funcionar eficientemente.}
{464}{}{Bem, quando pegar o Hydroelectric Magnetosphere Regulator em Vault City, traga de volta
 para o reator. Então você pode tentar convencer aquela lesma do Festus a instalar a peça, ou use o
 robô de manutenção para instalá-la, ou finalmente instale você mesmo, é claro - contanto
 que alguém faça o serviço está tudo bem.}
{465}{}{Como eu faço para pegar a peça em Vault City?}
{466}{}{Oh, entendo. Bem, agradeço a informação. Tchau.}
{467}{}{Festus é o velhote que comanda a usina atômica. Ele é velho, excêntrico e caduco, mas
 sabe bem como fazer a usina funcionar. O escritório dele fica na parte mais distante a sudeste
 da usina. Leve o disco para ele e ele saberá como usá-lo.}
{468}{}{Ah, entendi. Tchau.}
{500}{}{(metidando com ele mesmo) Muitas coisas aconteceram. Os tempos não são como eram antes. (suspiro) Sinto que
 meu único parente restante faleceu. Embora fosse louco, não queria que ele se fosse. Esperava que
 ele encontrasse a felicidade mesmo na sua velhice. (a você) Bem, chega dos meu tristes pensamentos.}
{501}{}{Uh, tudo bem.}
{504}{}{Um Hydroelectric Magnetosphere Regulator. Essa é a peça que você precisa pegar em
 Vault City. Então traga-a de volta aqui e instale-a no reator.}
{505}{}{Instalr a peça no reator? Como eu faço isso?}
{506}{}{Ah, tudo bem. Obrigado.}
{510}{}{A informação de otimização do reator foi gravada no disco que você pegou no Computador Central de
 Vault City. Agora tudo o que você deve fazer é levar o disco para aquele imbecil do Festus.
 Ou suponho que você mesmo use o disco no terminal de controle do robô do reator. Se você não puder
 melhor deixar pro Festus.}
{511}{}{Festus? Quem é ele?}
{512}{}{Ah, certo. Tchau.}
{600}{}{A Renovação lhe é permitida. Mas você não a conseguirá a não ser que se mova
 e repare nosso reator atômico. (para ele mesmo) Humanos... são tão decepcionantes.}
{601}{}{A Renovação está quase pronta, mas você não a conseguirá enquanto não usar o
 Reactor's Data disk no Computador Central de Vault City. Phah! Qualquer um pensaria que
 mesmo um humano entenderia isso.}
{602}{}{Você está muito perto de proporcionar os meios da Renovação para todos nós. Você só
 precisa dar o Data disk que você analizou para o Festus.}
{603}{}{Você sabe que deve pegar o Hydroelectric Magnetosphere Regulator
 em Vault City para instalá-lo em nosso reator atômico. --- Às vezes eu penso
 que a Renovação nunca acontecerá enquanto eu depender de humanos.}
{604}{}{Reparar o reator? Como assim?}
{605}{}{Usar o Reactor Data disk? Como farei isso?}
{606}{}{Tenho que dar ao Festus?}
{607}{}{Um Hydro-oquê? Hã?}
{608}{}{O que houve com o reator?}
{609}{}{Dar a quem?}
{610}{}{Ah sim. Bem, vou indo então. Tchau.}
{611}{}{Você precisa instalar o Regulador Hidrelétrico da Magnetosfera antes que a usina esteja operacional novamente.}
{620}{}{Eu sou conhecido simplesmente como O Cérebro. Um tributo à minha genialidade. Algumas coisas em Gecko e apenas um 
pouco mais fora da cidade fazem minha fama.}
{621}{}{Mas você é apenas um rato gigante.}
{622}{}{Você disse algo sobre juntar-se a você?}
{630}{}{As ações que eu proponho beneficiarão milhares de cidadãos de Vault City e Gecko. Você pode não 
 se importar comigo ou com meus motivos, mas ainda assim  os resultados
 são promissores.}
{631}{}{Você recebeu o Reactor Data disk, agora deve usá-lo.}
{632}{}{Você teve o Reactor Data disk analisado, agora deve fazer algo com ele.}
{633}{}{Nosso reator atômico precisa da peça para que possa funcionar
 eficientemente.}
{634}{}{Você adquiriu a informação que precisamos para otimizar o reator atômico. Agora,
 tudo o que você deve fazer é dá-la ao Festus.}
{635}{}{Por que você não me conta sobre seja lá o que for isso o que você está propondo.}
{636}{}{Usar o Reactor Data disk? Como eu farei isso?}
{637}{}{Bem, foi o que eu supus, mas o quê?}
{638}{}{Uma peça? Que tipo de peça?}
{639}{}{Por que você não me fala sobre esse último passo e eu pensarei em ajudá-lo.}
{640}{}{Dar a quem?}
{641}{}{Mais um passo?}
{650}{}{Bem, apesar dos seus sentimentos sobre um roedor dominar o mundo, as ações que eu proponho beneficiarão
 milhares de cidadãos de Vault City e Gecko. Você pode não se importar comigo ou com meus motivos, mas ainda assim
 os resultados são promissores.}
{651}{}{Você recebeu o Reactor Data disk, aogra deve fazer alguma coisa com ele.}
{652}{}{Você tem o Reactor Data disk analizado, agora deve usá-lo.}
{653}{}{Nosso reator atômico precisa da peça para que possa funcionar
 eficientemente.}
{654}{}{Por que você não me conta sobre essas ações que está propondo?}
{655}{}{Usar o Reactor Data disk? Como eu farei isso?}
{656}{}{Bem, foi o que eu supus, mas o quê?}
{657}{}{Como o quê?}
{658}{}{Uma peça? Que tipo de peça?}
{659}{}{Por que não me conta sobre esse último passo e eu pensarei em ajudá-lo?}
{670}{}{O reator, sempre o reator (suspiro). Volte quando tiver tido algum
 progresso nele.}
{671}{}{Volte mais tarde. Estou me comunicando com uma força maior, ou algo assim (hunf).}
{672}{}{Olha, se você não cancelar os ataques, as pessoas na vila podem acabar escravizadas por Vault City.}
{700}{}{Não tenho mais nada a dizer a você.}
{701}{}{Tudo bem, seu filho da puta nojento, agora tenho um novo acordo para você: ou você cancela seus roedores ou juro que explodirei essa porra de reator!}
{702}{}{Tudo bem, tudo bem... Considere feito. Apenas, não toque no reator. (resmunga) Malditos humanos psicóticos...}
{703}{}{Agora que estamos de acordo, o que você disse sobre a otimização?}
{704}{}{Está resolvido então. Adeus.}
{705}{}{Você chegou a um acordo sobre os ratos toupeira com o O Cérebro.}
{706}{}{As patrulhas de Vault City continuam sendo atacadas por ratos toupeira. Acredito que você esteja por trás disso?}
{707}{}{Você pede minha ajuda, mas deixa a tarefa pela metade. (para si mesmo) Típico humano. (para você) Otimize o reator, então, e só então, te ajudo.}
{708}{}{Depende. O que é?}
{709}{}{Escuta aqui, seu anormal. Você está realmente começando a me irritar. Você disse que seu "parente" chutou o balde... Bem, eu quero que você saiba - fui eu, quem se livrou dele. E agora acho que vou terminar o trabalho de tornar sua espécie extinta.}
{710}{}{Ouça aqui, seu rato radioativo. Você está realmente começando a me irritar. Acho que é hora de acabar com essa loucura.}
{711}{}{Eu preciso pensar sobre isso.}
{712}{}{Muito interessante... e eu pensei que você estava preocupado com o bem-estar de Vault City. De qualquer forma, a segurança daquela vila é parte integrante do meu plano. Portanto, concederei seu pedido, humano.}
{713}{}{Me parece que, por ter consertado e otimizado o reator, você merece minha ajuda. O que é que você quer?}
{714}{}{Obrigado! O que você estava falando sobre a otimização?}
{715}{}{Obrigado! Adeus.}
{716}{}{Parece que Gordon já deu a vocês este disco de dados econômicos de que falo. Leve-o para Vault City imediatamente.}
{717}{}{Eu estou trabalhando nisso.}
{718}{}{Eh, talvez mais tarde. Tchau.}
{719}{}{Você *deve* obter um Regulador Hidroelétrico da Magnetosfera de Vault City para consertar o reator Gecko. Se não o fizer, Vault City sem dúvida atacará o Gecko. Se você me ajudar, atenderei ao seu pedido. Então... você vai se juntar a nós?}
{720}{}{Muito bem, vou ajudá-lo.}
{721}{}{Não, foda-se cérebro de rato! Já vi o suficiente disso. Hora de morrer!}
{4211}{}{Uh, acho melhor eu ir buscar o disco do Gordon. Adeus.}
