{100}{}{Você vê alguém cuja pele foi gravemente queimada.}
{101}{}{Você vê um cidadão ghoul de Gecko.}
{102}{}{Você vê alguém cuja pele parece ter sido afetada com radiação. Tanta radiação deveria
 tê-lo matado, mas ele parece relativamente bem.}
{110}{}{A pessoa que você vê está emitindo uma luz fraca. Sua pele parece muito queimada.}
{111}{}{Você vê um ghoul resplandecente de Gecko.}
{112}{}{Você vê alguém que foi exposto a tanta radiação que está brilhando fracamente.
 Essa quantidade de radiação deveria tê-lo matado, mas ele parece relativamente bem.}
{120}{}{Obrigado por nos salvar de Vault City.}
{121}{}{Aqueles fanáticos em Vault City teriam nos matado se não fosse por você.}
{122}{}{Você é um herói.}
{123}{}{Você pode vir à minha casa para comer um ensopado de lagartixa a hora que quiser.}
{124}{}{Obrigado por consertar nosso reator.}
{125}{}{Parece mais frio agora, mas obrigado por consertar o vazamento do nosso reator.}
{126}{}{Obrigado por nos ajudar com aqueles fanáticos de Vault City por nós.}
{127}{}{Se você não nos ajudasse, Vault City teria nos destruído.}
{128}{}{Você é nosso herói.}
{129}{}{Obrigado novamente.}
{130}{}{Obrigado por sua ajuda.}
{131}{}{Você é o melhor. Obrigado.}
{132}{}{Muito bom para um pele lisa.}
{140}{}{Olá meu amigo de pele lisa.}
{141}{}{Bem vindo a Gecko.}
{142}{}{Olá, amigo.}
{143}{}{Você não como os outros pele lisa.}
{144}{}{Tem alguma coisa interessante lá pelo deserto?}
{145}{}{Olá.}
{146}{}{Fala fiote.}
{147}{}{Nosso reator atômico me faz brilhar de orgulho.}
{148}{}{Aqui nós dominamos o poder do átomo.}
{149}{}{Algum dia, outros serão capazes de usar nosso poder.}
{150}{}{Fico feliz que nem todos os pele lisa sejam como os de Vault City.}
{151}{}{Se as pessoal de Vault City fossem como você, não teríamos tretas com eles.}
{160}{}{Hmmph, outro pele lisa pilantra.}
{161}{}{Fala, pele lisa.}
{162}{}{Olá.}
{163}{}{O que é?}
{164}{}{Fique na boa enquanto estiver na cidade.}
{165}{}{Veio de longe para chegar aqui?}
{166}{}{Você parece ser de Vault City.}
{167}{}{Somos tolerantes aqui, mas não estúpidos, pele lisa.}
{168}{}{Fique longe de Vault City. Só tem porra louca por lá.}
{169}{}{Olá. O tempo está muito seco ultimamente.}
{180}{}{Estou com a garganta seca por causa do tempo.}
{181}{}{Droga, todas essas ervas daninhas.}
{182}{}{Acho que o reator atômico piora as ervas daninhas.}
{183}{}{Eu ouvi que tem algumas ervas estranhas que não são daninhas.}
{184}{}{Ouvi dizer que os tribais sabem chamar chuva.}
{185}{}{Boa colheita este ano.}
{186}{}{O milho está crescendo tão alto quanto um deathclaw.}
{187}{}{Os vegetais fazem bem para você.}
{188}{}{Nos preparando para a colheita.}
{189}{}{Precisamos de mais chuva.}
{200}{}{Estou de olho nesses brahmins.}
{201}{}{Esses brahmins são tão fofos. Não gosto da ideia de matá-los.}
{202}{}{Coceira no rego.}
{203}{}{Moo, moo, moo?}
{204}{}{Estou aqui há muito tempo.}
{205}{}{Esse cheiro é de você ou dos brahmins?}
{206}{}{Quase parece que eles sabem o que vai acontecer.}
{207}{}{Deram uma gorjeta ontem à noite.}
{208}{}{Alguns deles são muito mais fofos do que outros.}
{209}{}{Hmm, me pergunto por que ninguém monta nos bichos.}
{220}{}{Eai, pele lisa.}
{221}{}{Paga uma dose pra gente, pele lisa.}
{222}{}{Rapaz, estou com sede.}
{223}{}{Se acha bom demais para beber com a gente?}
{224}{}{Onde estão meus amigos, Johnny Stroller e Jim Bean?}
{225}{}{Eu quero o meu misturado, não moído.}
{226}{}{Peça a Wooz para te contar uma história.}
{227}{}{Vamos cantar uma canção.}
{228}{}{...E então as cabeças fazem o quê? Simplesmente não entendo Wooz.}
{229}{}{O que é uma maçã?}
{240}{}{Você é muito bom para um pele lisa.}
{241}{}{Pague outra rodada, pele lisa.}
{242}{}{./~ Como estou seco, como estou seco ... ./~}
{243}{}{Você parece uma ótima pessoa.}
{244}{}{Ei, cuidado com o rato.}
{245}{}{Eu me pergunto por que Skeeter nunca da um chego aqui?}
{246}{}{Estamos tentando criar um novo tipo de brahmin -- com apenas uma cabeça.}
{247}{}{Alguém deveria começar a fazer mais roupas aqui.}
{248}{}{Ooohh, breja da boa.}
{249}{}{Essa cerveja é ótima. E a água -- é muito mais.}
{260}{}{Você é o melhor pele lisa que já conheci.}
{261}{}{Mais suco brilhante! Mais suco brilhante!}
{262}{}{Paga outro, pele lisa?}
{263}{}{Aqueles pobres mutantes em Broken Hills.}
{264}{}{Ouvi dizer que os geckos são como nós. Alterado pela radiação.}
{265}{}{Nós apenas nos agarramos à vida aqui, como um pequeno gecko na parede.}
{266}{}{I hear Skeeter's building a giant robot.}
{267}{}{I heard that Chester's a spy for Vault City.}
{268}{}{I'd like to Renew into a smoothy.}
{269}{}{I swear I've seen things fly over us at night.}
{280}{}{I love you, man.}
{281}{}{Você é demais.}
{282}{}{Nuke Vault City 'til it glows!}
{283}{}{./~99 syringes of RadAway on the wall, 99 syringes... ./~}
{284}{}{./~ I've been working on the re-act-or, all the live-long day... ./~}
{285}{}{Before you, I wouldn't trust a smoothskin at all.}
{286}{}{I guess some of you smoothies are okay after all.}
{287}{}{We ought to go get Chester to drink with us.}
{288}{}{When I Renew, I want to turn out just like you.}
{289}{}{Sure glad our reactor's running.}
{290}{}{I must be drunk. Wooz is starting to make sense to me.}
{291}{}{I think I saw an apple once... or was it a banana?}
{300}{}{The reactor is working so good you can almost hear it hum.}
{301}{}{Thanks for working things out with Vault City for us.}
{302}{}{We're going to have so much power now.}
{303}{}{Not much longer until we can trade power to Vault City.}
{304}{}{Gosh, we're going to need a lot of Copper from Redding now.}
{305}{}{The reactor is working great now. Thanks.}
{306}{}{Você é demais.}
{307}{}{Thanks for fixing up our atomic reactor.}
{308}{}{Reactor's purring, just as nice as you please. Thanks.}
{309}{}{Você é o melhor pele lisa que já conheci.}
{320}{}{Renew, comrade. Renew!}
{321}{}{You are one of us.}
{322}{}{Hello, comrade. Renewal is at hand.}
{323}{}{We will all be one soon.}
{324}{}{He knows all. Worship his sleek fur.}
{325}{}{Damn cultists. Get out of here.}
{326}{}{Renew this (makes hand gesture), asshole.}
{327}{}{I've got your Renewal right here, pal.}
{328}{}{Can't turn around these days without stepping on another damn cultist.}
{329}{}{You'll never catch me worshipping some damn oversized rat.}
{340}{}{You ought to go see Lenny about those wounds.}
{341}{}{You look all banged up. Go see Lenny.}
{342}{}{You shouldn't wrestle with a deathclaw. Go see Lenny.}
{343}{}{Lenny's in Harold's office. You should have him take a look at those wounds.}
{344}{}{How'd you get all torn up like that?}
{345}{}{Ouch. You should go see Lenny.}
{346}{}{Lenny's in the settlement; go have him take a look at your injuries.}
{347}{}{I'd sure hate to see the other guy.}
