{100}{}{}
{101}{}{}
{102}{}{}
{103}{powr1}{ENCLAVE aqui. Por que seu sinal de vídeo não está funcionando?}
{104}{}{Uh, está funcionando normal. Estou te vendo.}
{105}{}{Está quebrado.}
{106}{}{Estamos trabalhando agora no link visual. Só queria testar.}
{107}{}{(Desconectando.)}
{108}{powr2}{O que aconteceu?}
{109}{}{Uh, estamos todos bem aqui. Como você está?}
{110}{}{Aqui é caau, rit, sss, pu-, - Câmbio.}
{111}{}{Eu sou o Escolhido, tome cuidado com sua língua.}
{112}{}{Este é o relatório da Unidade Três.}
{113}{powr3_c}{Bem, sua unidade ainda não parece estar operacional. Quem é?}
{114}{powr3a}{Não faz diferença nenhuma. Eu ainda não estou entendendo nada. Quem é você?}
{115}{}{Por favor repita. Câmbio.}
{116}{}{Eu poderia te dizer, mas então teria que te matar.}
{117}{}{Eu sou o Escolhido.}
{118}{}{Bem, isso não difícil, não é? Nada funciona do jeito certo.}
{119}{}{Isso é o que eu sei e você deve verificar. Tchau.}
{120}{powr3b_b}{Do que você está falando? Q-quem é?}
{121}{}{Eu poderia te dizer, mas então teria que te matar.}
{122}{}{Eu sou o Escolhido.}
{123}{}{Bem, isso não difícil, não é? Nada funciona do jeito certo.}
{124}{}{Isso é o que eu sei e você deve verificar. Tchau.}
{125}{powr4a_a}{O presidente! Eu, uh...}
{126}{powr4b_b}{Oh? Engraçadão, hein? Olha, estou te rastreando agora mesmo, parceiro. Veremos como você se sente inteligente com a segurança interna no seu cangote. Idiota!}
{127}{powr4c_a}{Já cansei dessas besteiras. Você gostaria de jogar se-esquive-dos-raios-de-plasma com o esquadrão? Hein?}
{128}{}{Ei, desculpe, eu não queria te chatear.}
{129}{}{Consigo rastrear você e te mostrar onde enfiá-lo.}
{130}{}{Você está me rastreando? Bem, estou fazendo a mesma coisa com você, amigão.}
{131}{}{Eu adoraria ficar por aqui e trocar uma ideia com seus amiguinhos sobre aquele chá de panela que vocês estão planejando, mas tenho coisas melhores para fazer com meu tempo. Falou.}
{132}{}{Bem, eu, uh, eu tenho que ir. Adeus.}
{133}{powr5_a}{Experimente o lucro.}
{134}{}{Pronto... isso deve bastar. Melhor agora?}
{135}{}{Gain? What am I'm supposed to gain? I keep pretty active; I don't think I can gain anything.}
{136}{}{I'll just try back later. Goodbye.}
{137}{powr6_a}{Chosen One, huh? Well, uh, pardon me for not blowing sunshine up your ass, but I'm a little too busy for this, your highness.}
{138}{}{Kneel before me and I may spare your life. Gee, I like the sound of that.}
{139}{}{I no longer insist upon genuflecting. A slight bow to kiss my ring should be sufficient.}
{140}{}{Uh, I meant I was the one *chosen* to fix the comm-unit. Seems like nothing works anymore.}
{141}{}{Well, I think I've had just about enough of your insolence. Goodbye, peasant.}
{142}{powr7_a}{Unit Three? I thought you were still at Navarro base?}
{143}{}{Navarro base? Oh yeah, Navarro base. That's where we are. Sure. I knew that.}
{144}{}{No, we had to get out of there.}
{145}{}{Your signal's breaking up. Goodbye.}
{146}{powr8_a}{Huh, ain't it the truth. Just don't let anyone who's got the President's ear hear that. You'll be making cattle-runs to New Reno 'til the end of time, pal.}
{147}{}{The President?}
{148}{}{Only got two legs. I'd be pretty tired by the time I got there.}
{149}{}{Well, no rest for the wicked. I better get back to fixing this. Goodbye.}
{150}{powr9_a}{Yeah, that's a new one. Since my video's working you can see I'm rolling on the floor here. It does seem like everything's a damn secret though, huh? All the special ops on the mainland. I don't see how anything gets done.}
{151}{}{On the mainland? Why, where are you?}
{152}{}{Well, it's like that all over.}
{153}{powr10_a}{Yeah, you know how unhappy he gets when people complain. He takes it personal, like it's a loyalty thing. Maybe that just goes with being the President of the United States. Or what's left of 'em.}
{154}{}{The President of the United States?}
{155}{}{I didn't vote for him. I thought he was too interested in getting laid. I prefer a candidate that's too old to get it up anymore--keeps their mind on the job more.}
{156}{}{Maybe so. You know, I better get back to work. Goodbye.}
{157}{powr11}{Oh, very funny. But you'd have a great place to recover from your run -- at least from what I hear.}
{158}{}{So you're not in New Reno then?}
{159}{}{Well, I better get back to work. Gotta get this link fixed. Goodbye.}
{160}{powr12}{The President of the United-fucking-States-of-America. Who'd you think I was talking about? Who the fu - Who is - What - I should kick your fucking ass, who is this?}
{161}{}{Eu sou o escolhido. Beije meus pés. }
{162}{}{Eu sou o Escolhido.}
{163}{}{I'm the President. You're in a heap of trouble.}
{164}{}{You're not important enough for that information.}
{165}{}{Uh, I better be going. Lots of work to do here. Goodbye.}
{166}{powr13}{This is ENCLAVE main comm. ...But you should know that. Who are you?}
{167}{}{Oh, I'm just... hey, you ever notice that cooked gecko tastes kind of like brahmin butt. }
{168}{}{I'm the Chosen One and you'll learn to remember that.}
{169}{}{Nobody important. Goodbye.}
{170}{powr14}{Ah, a few more moments and I'll have your sorry ass in a sling. Hey, wait a minute. This can't be right... I've got you somewhere on the mainland.}
{171}{}{That's right, sucker. Right where you can't get me.}
{172}{}{That can't be right. I'm at the comm desk right across the hall from you....Made you look. What a rube.}
{173}{}{Yeah, I'm at the Poseidon Oil power plant number 12. Come and get me.}
{174}{powr15}{I've got you, at Poseidon Oil, reactor number 5. Ah, well, why don't you just sit tight and I'll order up a little celebration for ya. Including fireworks.}
{175}{}{Oh, goodie. I just lo-ove fireworks. Send me a lot.}
{176}{}{I'm the Chosen One. You just better make sure you say that with a smile.}
{177}{}{I'm not anyone important. I'm going to go now. Goodbye.}
{178}{powr16_a}{Yeah well, whoever you are, I just dispatched a verti-assault team to your location. Have a nice day.}
{179}{}{Gee, if the video worked you could see me tremble.}
{180}{}{And what are they going to do?}
{181}{}{Well, I better get going then. I'd hate for them to show up before I get the red carpet all unrolled. Goodbye.}
{182}{powr17}{Usually they just go in shooting. They let someone else sift through the ashes to figure out what was going on.}
{183}{}{Yeah, well, they aren't going to catch me.}
{184}{}{Oh, now you've got me all scared. I need to change my undies.}
{185}{}{Well, I'd hate to think I spent all day yesterday polishing my guns for nothing.}
{186}{}{Yeah, sure. I've killed better. Goodbye.}
{187}{powr18}{Goodbye. Next news on you will be when I read the after-action report.}
{188}{}{What? You can read!}
{189}{}{Yeah, sure whatever.}
{190}{}{Hey, you just went on my list.}
{191}{powr19_a}{You had to get out? Why? You're on the coast. You got great defenses. I didn't hear anything about that....Hey, who the hell is this anyway?}
{192}{}{I am the great and powerful Willie. Kneel before me and entreat my forgiveness and I may yet spare thee.}
{193}{}{Nobody important. Where's this Navarro again?}
{194}{}{Yeah, well, we took Navarro and I found those nude pictures of your mother. Or was that just your dad cross-dressing again? No wonder you're so fucking ugly. Goodbye, asshole.}
{195}{powr20}{Yeah, you can say that again. And everything's always tighter out here at ENCLAVE and the fuckin' President's watching us like a hawk.}
{196}{}{The President?}
{197}{}{Out here? Where are you exactly?}
{198}{}{Well, that's how things go. Well, I better get back to work. Goodbye.}
