{100}{}{Você vê um ghoul vestindo roupas velhas e manchadas de graxa.}
{101}{}{Você vê Skeeter, o ghoul especialista.}
{102}{}{Você vê um ghoul sujo, mas de aparência inteligente, vestindo um macacão engordurado com um micrômetro
 saindo do bolso.}
{110}{}{Apenas não toque em nada - você pode se machucar.}
{111}{}{Achei que os tribais não fossem sofisticados.}
{112}{}{Você pode ver. Poderia aprender algo, mas eu duvido.}
{113}{}{Bem, você não é grande coisa.}
{114}{}{Você está apenas fingindo ser burro ou é realmente tão burro assim?}
{120}{}{Engraçado você ter perguntado isso. Veja, os carros usam células de combustível substituíveis, ou baterias, como combustível. O que 
 normalmente quebrava era o Controlador de célula de combustível. A maioria dos mecânicos amadores supõem 
 que seja a própria bateria. Mas você sabe o que as coisas fazem, não sabe?}
{121}{}{Não, eu não. O que você quer dizer?}
{122}{}{Isso significa que você tem um controlador de célula de combustível?}
{130}{}{Bom, assumindo que nem tudo é descartável entre nós. Quer pegar? Essa ainda é uma boa, não é? 
 Heh heh! Eu não uso isso há anos.}
{131}{}{Uh, obrigado pela lição. Agora, você tem um controlador de célula de combustível?}
{140}{}{Sim. Claro que sim. Está bem aqui. Pronto para ser colocado no carro. Você tem um carro?}
{141}{}{Eu sei onde tem um. Quanto vai me custar para pegar aquele controlador de célula de combustível?}
{142}{}{Eu posso ter um. Eu gosto dessas peças antigos. Quanto custa o controlador de célula de combustível?}
{143}{}{Gostaria de ter um. Se eu encontrar, saberei onde encontrar um novo Controlador de célula de combustível. Adeus.}
{144}{}{Na verdade, tenho outra pergunta para você.}
{150}{}{Bem, dinheiro é bom, mas preciso de mais alguma coisa agora. Algo que não posso conseguir sozinho.}
{151}{}{Do que precisa?}
{160}{}{Beleza. Você tem meu regulador de plasma. Obrigado. Agora te devo um trabalho de graça. Com o que você 
 quer que eu trabalhe? Eu te diria quanto ia fica, mas esse já está pago.}
{161}{}{Vejamos no que você pode trabalhar.}
{162}{}{Acho que vou pensar sobre isso. Tchau.}
{170}{}{Obrigado por consertar nosso reator atômico. Esse lugar precisa de um bom trabalho. Eu os ensinaria isso, mas
 eles não confiam mais em mim lá. Eles têm aquele safado tagarela do Festus fazendo todo o trabalho.}
{171}{}{Bem, fiquei feliz em ajudar. Mas agora eu preciso de algo.}
{172}{}{Com certeza teria sido mais fácil se eles deixassem você consertar. Bem, está feito agora. Até logo.}
{180}{}{Você já recebeu meu Transformador Trifásico de Plasma?}
{181}{}{Ainda não, mas ainda estou trabalhando nisso. Deixe eu perguntar outra coisa.}
{182}{}{Ainda não, mas eu vou. Adeus.}
{190}{}{Olá, sou Skeeter. Eu conserto e junto as coisas aqui.}
{191}{}{Olá. O que você está procurando?}
{192}{}{Precisa de algo?}
{200}{}{Você já ouviu falar de algo chamado Kit de Criação do Jardim do Éden?}
{201}{}{Você tem uma bateria que eu possa usar para consertar um carro?}
{202}{}{Tenho algumas coisas que quero que dê uma olhada.}
{203}{}{O que você faz aqui?}
{204}{}{Hã, eu só estava dando uma olhada por aqui. Tchau.}
{210}{}{O que você quer que eu olhe?}
{211}{}{Você está pronto para eu colocar minhas mãos em algo? O que você quer que eu olhe agora?}
{212}{}{Eu tenho esse telescópio.}
{213}{}{Tenho um "X"}
{214}{}{Tenho um "X"}
{215}{}{Tenho um "X"}
{216}{}{Tenho um "X"}
{217}{}{Posso trocar as peças mais tarde?}
{218}{}{Não preciso de nada agora. Adeus.}
{220}{}{Hmm, posso acoplar esta mira que você tem ao seu rifle.}
{221}{}{Eu posso acoplar esta mira a um de seus rifles. Com qual deles você quer que eu faça?}
{222}{}{Quanto vai custar para acoplar esta mira ao meu rifle de caça?}
{223}{}{Quanto vai custar para acoplar esta mira ao meu rifle de assalto?}
{224}{}{Quanto vai custar para acoplar esta mira ao meu Rifle Sniper?}
{225}{}{Deixe eu perguntar sobre outro item.}
{226}{}{Acho que é tudo que preciso saber. Adeus.}
{230}{}{Hmm, pensei que sim. Sabe, não posso fazer nada com o seu [Selected partname]. Você precisa 
 de algo mais para que eu faça algo com ele.}
{231}{}{Hmm, então seria um item diferente?}
{232}{}{Que peça eu preciso?}
{233}{}{Acho melhor voltar quando tiver outra coisa. Adeus.}
{240}{}{Aqui está. Acho que isso deve funcionar bem. Algo mais?}
{241}{}{Sim, você poderia dar uma olhada em outro item para mim?}
{242}{}{É tudo que preciso agora. Obrigado e até.}
{250}{}{Hmm, você não tem dinheiro suficiente para cobrir os gastos desse trabalho. Tem alguma outra coisa 
 que você quer que eu dê uma olhada?}
{251}{}{Quanto custaria para combinar outra coisa?}
{252}{}{Acho que não. Obrigado mesmo assim. Adeus.}
{260}{}{Normalmente eu só trabalho com sucatas. Desmontagem e remontagem de quase tudo... 
 como regra geral. Fazendo funcionar melhor... às vezes. Me mantendo fora de problemas. Sabe o que eu quero dizer?}
{261}{}{Suponho. Deixe eu perguntar outra coisa.}
{262}{}{Bem, acho melhor eu ir fazer um negócio. Adeus.}
{270}{}{Você atrás de um GECK, hein? Bem, eu não sei direito onde você pode encontrar uma dessas
 coisas. Eu sei que Vault City provavelmente tinha um.}
{271}{}{Vault City tinha um?}
{272}{}{Hmm. Bem, deixe eu perguntar outra coisa então.}
{273}{}{Bem, é melhor eu continuar procurando. Adeus.}
{280}{}{Quase certeza que eles tinham. É por isso que eles estão na vida boa, certeza não é porque eles sabem o que
 estão fazendo. É porque o GECK começou suas plantações e fez a cidade funcionar quando eles saíram da
 Vault.}
{281}{}{Quem teria um GECK não utilizado?}
{290}{}{Bem, deixe-me pensar agora. Pelo que me lembro, a maioria das Vaults deveria ter um GECK.
 Você pode tentar procurar em outra Vault por aí.}
{291}{}{Obrigado pelo conselho. Deixe eu perguntar outra coisa.}
{292}{}{Certo, é melhor eu procurar então. Adeus.}
{300}{}{Para ser honesto com você, te direi não. Se eu não tiver todas as peças, me da 
 a impressão que sempre esta faltando alguma coisa. Sabe o que quero dizer?}
{301}{}{Ei, você quer dizer que faz isso sem nem pensar?}
{302}{}{Então que tal dar uma olhada em outra coisa?}
{303}{}{Bem, acho que faz sentido. É melhor eu procurar outra peça. Até mais.}
{310}{}{Bem, sim. Mas, veja você, é uma suposição correta. É sim. Sabe o que eu quero dizer?}
{311}{}{Na verdade eu nem sei o que você quer dizer, mas acho que vou procurar outra parte. Falou.}
{312}{}{Então que tal dar uma olhada em outra coisa?}
{313}{}{Bem, acho que faz sentido. É melhor eu procurar outra peça. Até mais.}
{320}{}{Hoje em dia, boas ferramentas são mais difíceis de achar do que peças. Eu preciso de um novo Super-kit de Ferramentas.
 Snap-sumthin é melhor marca.}
{321}{}{Um novo kit de ferramentas? Onde consigo isso?}
{330}{}{Acho que o melhor lugar para conseguir seria em alguma loja de em algum canto de Vault City. Eles têm
 todos os tipos de ferramentas, mas com certeza não venderiam para um ghoul, pode esquecer.}
{331}{}{Então, você quer que eu lhe traga um Super-kit de Ferramentas, e você me dá a peça do carro?}
{340}{}{Exatamente. Este é o acordo. Um Super-kit de Ferramentas em troca de um Controlador de Célula de Combustível.}
{341}{}{Me parece um acordo justo. Me deixe perguntar outra coisa.}
{342}{}{Mas e se eu fizer isso da maneira mais fácil? Eu te mato e pego a parte de que preciso.}
{343}{}{Vou dar uma volta e pensar sobre isso. Até mais.}
{360}{}{Entendi. Você poderia tentar, talvez. Mas, falando sério, você pode ter uma pequena surpresa. eu
 posso ser mais forte do que você pensa. Desse jeito você estaria cortando sua própria garganta. Consigo
 ser muito bom manuseando objetos. É sempre bom tem em quem experimentar alguns novos, não é?}
{361}{}{Well, maybe you're right. I'll let you live, for now. Tell me something else, though. }
{362}{}{You sure have a lot of answers, don't you? Hope you have an answer for what's in the afterlife,
 'cause I'm sending you there -- right now.}
{363}{}{I'll have to think about that one. Goodbye, for now. }
{370}{}{I see that you've got a mighty fine tool kit there. Snap-off, ain't it? I'll trade you this Fuel
 Cell Controller for it.}
{371}{}{Hey there! Yur back with my repair kit. Mmm, Snap-off -- they're the best. Ready to trade?}
{372}{}{Estamos de acordo.}
{373}{}{Not right now. I'm holding on to this for a while. Goodbye.}
{380}{}{That's a mighty fine trade. You should be able to jist plug that sucker in and git your car
 a'workin'.}
{381}{}{That's a mighty fine trade. You should be able to jist plug that sucker in and git your car
 a'workin'. You know I could do you another favor by fixin' up some of yur stuff for free, too.}
{382}{}{Really? For free, huh? What do I need to do for you?}
{383}{}{Deixe-me perguntar-lhe algo mais.}
{384}{}{I'm going to go try that right away. Goodbye.}
{390}{}{Well, ya see, I need a darn 3-Step Plasma Transformer. An the only place I can figger to git one
 is from the supply room.}
{391}{}{Why don't you just get it from there, then?}
{400}{}{I kinda wore out my welcome there. An it was only a little fire, too. Coulda happened to jist
 anyone. Anyhow, they won't let me anywhere's inside the reactor building now. I need someone else to
 git my part for me. }
{401}{}{How do I get the Plasma Transformer for you?}
{410}{}{Youz gotta git yourself a Supply Requisition Form. Once you have that, jist give it to Jeremy in
 the Supply Room and he'll give you any darn thing you want. You can get Supply Requisitions from
 Harold or Festus.}
{411}{}{Where are Harold and Festus and will they just give me the form I need?}
{420}{}{Harold's in the Settlement, and Festus is in the reactor control room. But you might have to
 kind of get the forms on the sly, if ya know what I mean.}
{421}{}{You mean I have to steal the Requisition Form, don't you?}
{430}{}{Well, err, yeah. I guess so. You might ask them, but I wouldn't put your chances too high there.}
{431}{}{Well, I'll see what I can find out.}
{432}{}{I don't think I want any part of this. Goodbye.}
{440}{}{Didja come here to take me up on that work I owe you?}
{441}{}{I sure did. Let me see what you can work on for me.}
{442}{}{Not yet. Just came by to see if you're still here. Well, Goodbye for now.}
{450}{}{I'm sorry. You don't have anything that I can use that with. Anything else?}
{451}{}{Take a look at something else I have.}
{452}{}{I guess that's it for now. Goodbye.}
{460}{}{Let's see. It's going to cost you $[Cost of combining item a with item b]. Do you want to do
 that?}
{461}{}{Yes. I do. Thanks.}
{462}{}{I don't think that I want to do that after all. What about something else?}
{463}{}{I guess I don't want you to work on anything right now after all. Goodbye.}
{470}{}{Once I put things together they stay put. You cain't pull 'em apart later and attach 'em to
 other things. Better pick right the first time, I guess.}
{471}{}{OK, I understand. Take a look at something for me, then.}
{472}{}{I guess I don't want you to work on anything right now after all. Goodbye.}
{500}{}{I was wunderin' where the heck my Repair Kit is. You did say you were gonna git it, didn't ya?
 I cain't rightly do much fer ya without that. Sorry. Should be plenty of 'em available in Vault City.}
{501}{}{I'll have to come back when I have that. Goodbye.}
{502}{}{I don't think I need your help with anything right now, anyway. Goodbye.}
{600}{}{O que você quer que eu olhe?}
{601}{}{I have a pistol here and I was wondering....}
{602}{}{It sure looks as though you could bolt an accessory to this long arm here.}
{603}{}{Sometimes I like to get up close and personal. Anything you can do to improve my powered melee weapon?}
{604}{}{Uh, maybe later. Let me ask you about something else.}
{605}{}{Não preciso de nada agora. Adeus.}
{610}{}{[Spots your magnum revolver.] I can rig a speed loader on that there magnum for $}
{611}{}{Hmm, that Desert Eagle would sure be a sweet rig with an expanded magazine. I can do that for $}
{612}{}{Put the speed loader on the magnum.}
{613}{}{Expand the magazine in my Desert Eagle here.}
{614}{}{Actually, I had another weapon in mind....}
{615}{}{Hmm, let me ask you about something else.}
{616}{}{Maybe I'll come back later on.}
{617}{}{Too rich for my blood. I'll be back when I have more cash.}
{620}{}{[Skeeter studies your long arm, and nods slowly.]}
{621}{}{I can put a nice all-weather scope on that hunting rifle for $}
{622}{}{Nothing like having an assault rifle with an expanded magazine. I can fix
 yours up with one for $}
{623}{}{That FN FAL is a good gun. Hey, I got a low-light scope for that. It's yours
 for $}
{624}{}{All right then... put a scope on the Colt hunting rifle.}
{625}{}{Expand the magazine of the AK-112 assault rifle.}
{626}{}{Attach that low-light scope on the FN FAL.}
{627}{}{Too rich for my blood. I'll be back when I have more cash.}
{630}{}{You want that melee weapon juiced up? I can *supercharge* it for $}
{631}{}{Com certeza.}
{640}{}{[Skeeter takes the item and looks it over with a weird gleam in his
 eye.] Well, this is a mite challengin', but I think I can fix this up real nice
 for ya. Just sit tight for a while. [Skeeter takes the weapon over to his
 workbench and locks it in a really big vise.]}
{641}{}{Tudo bem.}
{650}{}{[As you wait you can see Skeeter's back as he works on your weapon. You
 don't know exactly what he's doing but that weird chuckle and all the pounding are
 making you nervous.]}
{651}{}{Aguarde...}
{660}{}{[More pounding and cackling as you wait some more....]}
{661}{}{[You whistle tunelessly and make shadow-puppets against the back wall of
 Skeeter's workshop....]}
{670}{}{There you go. [You wake suddenly as Skeeter takes your weapon from the
 workbench - you can see a number of small shiny, metal parts lingering on the
 bench as Skeeter returns your weapon to you.] That *should* do it, I reckon. Give
 'er a try.}
{671}{}{Thanks. Can you upgrade any of my other weapons?}
{672}{}{Thanks, Skeeter. Uh, let me ask you something else.}
{673}{}{Thanks, Skeeter. I'll go try it out.}
{680}{}{[Spots your magnum revolver.] I can rig a speed loader on that there magnum for free.}
{681}{}{Hmm, that Desert Eagle would sure be a sweet rig with an expanded magazine. I can do that for free.}
{682}{}{I can put a nice scope all-weather on that hunting rifle for free.}
{683}{}{Nothing like having an assault rifle with an expanded magazine. I can fix
 yours up with one for free.}
{684}{}{That FN FAL is a good gun. Hey, I got a low-light scope for that. It's yours
 for free.}
{685}{}{You want that melee weapon juiced up? I can *supercharge* it for free.}
{700}{}{You delivered the part to Skeeter.}
{710}{}{You delivered the repair kit to Skeeter.}
{5500}{}{.}
