{100}{}{Você vê um ghoul maior do que o habitual.}
{101}{}{Você vê Zomak, conhecido por alguns como Destruidor.}
{102}{}{Você vê um ghoul grande e robusto cuja face, sob uma testa serveramente inclinada, reflete uma vasta
 reserva de estupidez suprema.}
{110}{}{Renew, camarada! Eu sou Zomak. Alguns me chama de Zomak, o Destruidor. O que você quer aqui?}
{111}{}{Renew, camarada! O que você quer? Diga para Zomak, o Destruidor, o que você veio fazer aqui.}
{112}{}{Renu!}
{113}{}{Ook?}
{114}{}{Eu estou apenas olhando ao redor.}
{115}{}{Eu quero a renewal.}
{116}{}{Eu peguei o caminho errado.}
{120}{}{É melhor você dar uma olhada em outro lugar, ou Zomak vai te mostrar as estrelas.}
{130}{}{Então você deve ver Ele.}
{131}{}{Ele? Onde está ele?}
{132}{}{Não sou digno de vê-lo. Adeus.}
{140}{}{É ele quem concede o esclarecimento. É ele quem promete a renewal para todos os que o seguirem.}
{141}{}{Bem, eu estou quase pronto pra Renewal. Onde ele está?}
{142}{}{Parece outro babaca pra mim. Estou saindo fora.}
{150}{}{Bem, ele está atrás... Ei! Quem é você mesmo?}
{151}{}{Eu sou apenas um andarilho.}
{152}{}{Sou o Chosen One.}
{153}{}{Estou aqui apenas por minha renovação anual.}
{154}{}{Está certo. Eu só gostaria de fazer algumas perguntas.}
{160}{}{Bem, ande pra fora daqui, então.}
{161}{}{Hã, certo. Tchau.}
{170}{}{Bem, nesse caso... entre. Ele está na próxima sala. Não o deixe esperando.}
{171}{}{Eu não. Eu vou direto. Adeus.}
{172}{}{Eu posso voltar mais tarde. Tchau.}
{180}{}{Bem, você pode escolher ir embora. Saia daqui.}
{181}{}{Tudo bem.}
{200}{}{Sim, você podem todos receber a Renewal lá dentro.}
{201}{}{Tudo bem.}
{210}{}{Ook? O que você quer dizer com isso? Você é idiota?}
{211}{}{Goop?}
{220}{}{Saia daqui. O cérebro não perde tempo com gente como você.}
{221}{}{Ok, estou indo agora.}
{230}{}{Não tem mais nada aqui a não ser o covil do Brain. Cara, você é um idiota.}
{231}{}{O Cérebro?}
{232}{}{Eu só estava te testando. Você passou. Agora me deixa entrar.}
{233}{}{Acho que me confundi. Deve ser toda essa radiação. Tchau.}
{240}{}{Opa. Hã, não há nada aqui. Nada mesmo. Agora vá embora.}
{241}{}{Tem certeza de que não há nada aqui?}
{242}{}{Certo. Tchau.}
{250}{}{Sim. Certeza absoluta. Agora saia.}
{251}{}{Bem, se você está dizendo. Tchau.}
{260}{}{Ah, he, he... é. Eu sabia disso. Humm, bem, er, eu passei? }
{261}{}{Claro que sim. Agora me deixe entrar.}
{262}{}{Não, você falhou e agora eu tenho que te denunciar.}
{270}{}{Certo, então. Você pode entrar.}
{271}{}{Certo. Tchau.}
{280}{}{Você tem o sinal. Pode entrar.}
{281}{}{entraaaá.}
{282}{}{Sinal?}
{283}{}{Tema o sinal! Tchau.}
{290}{}{Sim, o talismã sagrado da Renewal. Renew, camarada! Renew!}
{291}{}{Yes... Reno to you, too. Goodbye.}
{300}{}{Renew, irmão. Você pode passar.}
{301}{}{Renew, irmã. Você pode passar.}
