{100}{}{Você vê uma pessoa entediada usando uma armadura de couro.}
{101}{}{Você vê Max, o guarda da caravana.}
{102}{}{Você vê uma pessoa empoeirada e entediada usando uma armadura de couro. Pelo cheiro de brahmin 
 e pelo andar confiante, é claramente um guarda de caravana.}
{103}{}{Posso te ajudar com alguma coisa?}
{104}{}{Urg?}
{105}{}{Tra-balho aqui!}
{106}{}{Quem é você?}
{107}{}{O que você pode me dizer sobre Chad?}
{108}{}{Não tenho paciência para idiotas. Foi mal, amigo, vai achar outro pateta pra brincar com você.}
{109}{}{::sniff::}
{110}{}{Sou o Max. Sou um dos guardas da caravana.}
{111}{}{O que você pode me dizer sobre Chad?}
{112}{}{Obrigado. Tchau.}
{113}{}{Honestamente? Eu nem ligo pro cara. Ultimamente, ele tem jogado muitas moedas. Quero dizer, claro, 
 ele é o mestre da caravana, então faz sentido para ele pegar uma parte maior - eu entendo isso. Mas não tem como ele 
 estar *tão* carregado. Eu acho que seria interessante dar uma olhada em seus discos.}
{114}{}{Marcus me disse que suspeita que Chad roubou parte do dinheiro da caravana que deveria ir para Broken Hills.
 Eu disse que investigaria.}
{115}{}{Obrigado. Tchau.}
{116}{}{Obrigado, estou feliz que acabou. É melhor você cuidar de suas costas.}
{117}{}{Adeus.}
{118}{}{Ele é um inimigo! Morra!}
{119}{}{Oops.}
{120}{}{[Abaixa a voz e olha em volta.] Deve ser isso. Na verdade, eu era um guarda na última corrida de urânio 
 para Gecko e ouvi Chad discutindo com seu representante ghoul. Aparentemente, Broken Hills havia aumentado 
 o preço do urânio, e o ghoul não estava muito feliz com isso. Então eu ouvi Chad explicar para ele que nosso 
 suprimento de urânio estava diminuindo graças a uma greve recente dos mineiros, mas o fato é que nunca teve uma greve.}
{121}{}{Sério? Então por que você não passou isso pro Marcus?}
{122}{}{Tá ficando louco? Chad tem costas quentes aqui nessa cidade. Se eu abrir o bico muitos vão vir caindo de pau pra cima de mim. Puts, eu posso até ser morto.}
{123}{}{Hmm, então talvez eu pudesse dizer algo para Marcus. Até porque eu não pretendo ficar por aqui muito mais tempo.}
{124}{}{Ei, faça o que você achar que precisa ser feito, só não me arraste pra isso. Na verdade, nunca tivemos essa conversa, OK?}
{125}{}{Não há problema. Tchau.}
{126}{}{Na verdade, tem mais uma coisa. Eu sei que Chad mantém registros de todas as transações que faz. Ele é muito 
 neurótico com isso. Na verdade, o cara é tão louco que aposto que ele ainda tem registros de todo o dinheiro que andou 
 vasculhando. O problema é que ele tranca todas essas coisas em sua casa do outro lado da cidade, e não tem como 
 entrar lá - seu sistema de segurança é muito complexo. Novamente, nunca tivemos essa conversa.}
{127}{}{Eu me viro com isso. Obrigado pela informação.}
{128}{}{Sistema complexo? Como vou entrar então?}
{129}{}{[Max pensa por um momento.] Tudo bem, ouça. Você parece alguém em quem posso confiar. A porta da casa de 
 Chad é trancada usando o sistema de travamento não eletrônico mais avançado que existe - é realmente uma beleza. Eu 
 sei porque eu mesmo projetei. É que antes de ser guarda de caravana, trabalhei como chaveiro. Agora, como presumo 
 que você precisará entrar naquela casa, vou te explicar como abrir esse tipo de fechadura.}
{130}{}{(Max termina de explicar o sistema de travamento uns 5 minutos depois.) Pronto, isso já deve ser o suficiente pra saber como entrar.
 Com essas dicas até um novato pode abrir uma dessas fechaduras. Tenha cuidado agora. Ah, e nunca tivemos essa conversa.}
{131}{}{Não se preocupe. Muito brigado pela ajuda.}
{200}{}{Você aprende sobre a recente saída de Chad das caravanas Gecko.}
