{100}{}{Você vê um ghoul gorduroso e suado.}
{101}{}{Você vê Eric.}
{102}{}{Você vê um ghoul gorduroso e suado. Ele parece bastante infeliz.}
{103}{}{Como se esta cidade precisasse de mais azar. Como se *eu* precisasse de mais.}
{104}{}{Entra! Feche essa porta direito! Não deixe as moscas entrarem!}
{105}{}{Moscas? F-f-f!}
{106}{}{Tudo bem, tudo bem. Não precisa gritar.}
{107}{}{Você está gritando comigo?}
{108}{}{Vou deixar entrar tudo que é mosca se eu que quiser. Fracassado.}
{109}{}{De acordo, até logo.}
{110}{}{Feche a porta! Por favor! Vá embora e leve essas malditas moscas com você!}
{111}{}{Tudo bem!}
{112}{}{Desculpe, estou um pouco nervoso, muitas moscas e nenhum ar condicionado. Se eu tivesse um pouco mais de força, poderia me livrar deles... mas não tenho.}
{113}{}{Quem é você?}
{114}{}{Como você consegue a energia?}
{115}{}{Por que as moscas estão vindo aqui?}
{116}{}{Você poderia tentar tomar banho, sabe.}
{117}{}{Que azar para você hein amigão.}
{118}{}{Hum, nossa, que pena. }
{119}{}{Há uma estação geradora de energia que controla a energia da cidade. Se você pudesse apenas ir lá e só pedir permissão para me dar um pouco mais de energia para o meu ar condicionado, eu ficaria grato.}
{120}{}{Quão grato? Dinheiro ou equipamento?}
{121}{}{Sim, vou fazer isso por você.}
{122}{}{Sem tempo, irmão. Talvez mais tarde.}
{123}{}{Tá loucão? Nada disso. Talvez você fique tão triste que morra. Faça um favor ao mundo.}
{124}{}{Elas vêm aqui, não me pergunte por que, exalo nutrientes para as moscas. Meu corpo está cheio de comida para eles, e esse suor só piora.}
{125}{}{Isso é bem desagradável. Não dá pra tomar um banho ou algo assim?}
{126}{}{Então, estarei te fazendo um favor, matando você.}
{127}{}{Entendo. Isso é mais do que eu precisava saber. Adeus.}
{128}{}{Já tentei isso, já tentei de tudo. A única coisa que mantém as moscas longe de mim é não suar... e quando eu não tenho energia suficiente para me refrescar, não consigo.}
{129}{}{Eu vejo. Eu tenho mais perguntas.}
{130}{}{Entendo, adeus.}
{131}{}{Sim?}
{132}{}{Conversei com Brian e ele disse que as frações de energia são tão ajustadas que ele não pode permitir que você aumente sua parte.}
{133}{}{De onde vêm as moscas?}
{134}{}{Você já tentou tomar banho?}
{135}{}{Onde está o gerador de energia?}
{136}{}{Quem é você?}
{137}{}{É muito melhor aqui. Confortável?}
{138}{}{Nada. Esqueça.}
{139}{}{Eu poderia arranjar alguma coisinha para você como recompensa. Não posso prometer muito, mas também não é um grande favor.}
{140}{}{Temos um acordo. Apenas se certifique de ter algo para mim quando eu receber a energia para você.}
{141}{}{Eu farei isso de graça. Sem custo.}
{142}{}{Esqueça, eu não quero fazer isso.}
{143}{}{Vou pensar sobre isso.}
{144}{}{Eu não posso te dizer o quanto sou grato a você. Me de um toque quando terminar para que eu possa ligar o ar condicionado e tomar um banho.}
{145}{}{Eu farei. Mas eu tenho algumas perguntas.}
{146}{}{Eu farei, até logo.}
{147}{}{Por favor, não demore muito com isso... Estou ficando muito cansado de todas essas moscas.}
{148}{}{Claro. Eu tenho mais umas perguntas.}
{149}{}{Certo. Eu aviso você.}
{150}{}{Muito obrigado pela sua compaixão. Ah, isso é sarcasmo, caso você não tenha notado. Cai fora da minha casa.}
{151}{}{Por que você não morre e vai direto pro capeta?}
{152}{}{Até logo, senhor das moscas!}
{153}{}{O gerador de energia está à sua esquerda quando você chega em Broken Hills. É controlado por um cara chamado Brian, um filho da puta preguiçoso que fica vadiando o tempo todo.}
{154}{}{Parece um trabalho de verdade, obrigado. Eu tenho mais perguntas.}
{155}{}{Entendo. Bem isso é tudo por agora.}
{156}{}{Eu sou o Eric. Dirigia o hotel da cidade, mas tive que vendê-lo por causa do meu problema com as mosca. Eu também dirigia a taverna, mas precisei sair dela também, pelo mesmo motivo. Finalmente, eu costumava ligar o gerador, mas as moscas continuam entrando nele.}
{157}{}{Quantos empregos. Eu tenho mais perguntas.}
{158}{}{Entendo. Até mais!}
{159}{}{Ele disse isso, não foi? Bem, diga a ele que o gerador é movido por urânio e que a minúscula quantidade de energia de que preciso mal seria registrada no gerador. E diga a ele que quero minha energia!}
{160}{}{Farei! Bom discurso!}
{161}{}{Eu direi a ele. Tenho outras perguntas.}
{162}{}{Claro. Tchau.}
{163}{}{Deu certo com o gerador? Muito obrigado. Não consigo nem descrever o quanto sou grato pelo que você fez.}
{164}{}{A maneira mais comum de agradecer é com uns presentinhos, pode ser dinheiro ou equipamentos.}
{165}{}{Não precisa, estou feliz com seus agradecimentos.}
{166}{}{Francis, o mutante, tem um punho de força. Ele continua apostando em competições de queda de braço. O problema é ser mais forte do que ele. Se você estiver interessado, posso lhe dar alguns comprimidos devem te dar uma vantagem sobre ele.}
{167}{}{Claro.}
{168}{}{Prefiro dinheiro, se você tiver.}
{169}{}{Eu não quero uma recompensa.}
{170}{}{Essas pílulas são chamadas de buffouts. Elas vão aumentar sua força, mas sua mente vai sofrer um pouco. Não tome muitos ou você pode ficar viciado. Boa sorte com o punho!}
{171}{}{Obrigado! Até mais!}
{172}{}{Você acha que pode me ajudar com o meu problema com as mosca? Eu ficaria muito grato.}
{173}{}{O quanto agradecido?}
{174}{}{Claro.}
{175}{}{Vou pensar sobre isso.}
{176}{}{De jeito nenhum.}
{177}{}{Aqui está tudo que tenho... $ 150. Obrigado.}
{178}{}{Não, obrigado. Adeus.}
{179}{}{Então, estou duplamente grato. Oh... Ouvi dizer que você está procurando um GECK. Tente perguntar ao redor no NCR, fica ao sul.}
{180}{}{Valeu! Tchau!}
{181}{}{Ai sim. As moscas diminuíram, o ar está fresco e estou menos suado. Todo mundo sai ganhando!}
{182}{}{De acordo. Bom, isso é tudo, até mais!}
{183}{}{Você vê um homem gorduroso e suado. Ele parece bastante confortável.}
