{100}{}{Você vê um ghoul. Neste momento ele está debaixo do para-choque dianteiro.}
{101}{}{Você vê Lumpy. Você espera que ele esteja bem.}
{102}{}{Você vê um ghoul que parece estar com uma bela dor. Talvez se você não fosse um barbeiro
 poderia ter evitado isso.}
{103}{}{Oooooh! Tudo pisca!}
{104}{}{Ai! Minha sacroilíaca!}
{105}{}{Alguém viu minha vesícula biliar?}
{106}{}{Minha coluna! Minha coluna!}
{107}{}{Estou indo até você, Elizabeth!}
{108}{}{Médico...}
{109}{}{Alguém poderia me ajudar? Não consigo ler o número da placa.}
{110}{}{Ei, amigo!}
{111}{}{Ei, moça!}
{112}{}{O nome é Lumpy. Você poderia me ajudar aqui um momento?}
{113}{}{Ouchie. Tudo bem, Lumpy?}
{114}{}{Meu Deus! Está tudo bem, Lumpy?}
{115}{}{Ops...}
{116}{}{Ah, tudo é rosa. Se eu não tiver várias fraturas expostas e um enfeite de capuz alojado vários centímetros na minha bunda, está tudo bem.}
{117}{}{Ahhh. Precisa de ajuda?}
{118}{}{Bom. Tchau.}
{119}{}{Tudo bem, relaxa. Você precisa de mim para alguma coisa?}
{120}{}{Graças a Deus. Eu pensei que você poderia estar em perigo. Bem, vejo você mais tarde.}
{121}{}{[Lumpy te olha nos olhos silenciosamente. Ele pisca... Duas vezes.]}
{122}{}{Ahhh... pergunta idiota. Sim?}
{123}{}{Vou tomar isso como um sim.}
{124}{}{Você tem razão, sim! Eu mal consigo me mexer! Agora preste atenção, eu não estou choramingando.
 Já tive machucados piores. Isso não é nada comparado com aquela confusão de anos atrás com aquele
 caminhão de Cola do sul. Você deveria ter visto, garoto! Tampinhas por todo lugar!}
{125}{}{Aaahhh. Divertiiido!}
{126}{}{Caramba! Imagine alguém correndo com isso no deserto! Ele teria ficado rico!}
{127}{}{Pode apostar. Arrgh! Ow! Eu odeio estragar nossa conversa fantástica, mas se você puder me ajudar a sair de baixo desse para-choque, eu agradeceria.}
{128}{}{Tem certeza?}
{129}{}{Tem certeza? Acho que você não deveria se mover.}
{130}{}{Ah, não se preocupe com isso. Uma hora tudo volta ao lugar.}
{131}{}{OK. Prepare você!}
{132}{}{Tudo bem. Prepare-se!}
{133}{}{Sim, ops! Onde que você aprendeu a dirigir?}
{134}{}{Sozinho.}
{135}{}{Na verdade eu sou autodidata.}
{136}{}{Ah, tá explicado.}
{137}{}{Oh. Tudo bem?}
{138}{}{Oh... bem, eu... hmmmm. Você... você está bem?}
{139}{}{Eu falei. 'Precisamos de sinais de trânsito', foi o que eu disse. Mas eles ouviram? Nããão... deixa o velho Lumpy pra lá!}
{200}{}{Oh, merda!}
{201}{}{Ei. Eu bati no homem fedido.}
