{100}{}{Você vê um mutante em roupas empoeiradas segurando uma picareta.}
{101}{}{Você vê um mutante mineiro.}
{102}{}{Você vê um mutante em roupas empoeiradas segurando uma picareta. Pelos calos em suas
 mãos e a expressão cansada, você descobre que esse mutante deve ser um mineiro. Além de cansado, ele parece um pouco confuso.}
{103}{}{O que você quer?}
{104}{}{Ag-ag! Ooo!}
{105}{}{Ork! Ooky!}
{106}{}{Dallo?}
{107}{}{Dallo!}
{108}{}{O que há para fazer por aqui?}
{109}{}{Quem é você?}
{110}{}{Ah, bom, um idiota. Afetado pela radiação, hein, cara? Não consigo entender nada, não posso te ajudar.}
{111}{}{Eu disse que não posso te ajudar! Vá embora e encha o saco de outro!}
{112}{}{O que há para fazer? Bem, a mina fechou porque não temos um purificador de ar que preste. Tem
 o salão, os caravaneiros e o armazém geral. É isso aí. Espere, sobre o que estávamos conversando
 mesmo?}
{113}{}{Com quem eu falo sobre a mina?}
{114}{}{Onde está o salão?}
{115}{}{Onde estão os caravaneiros?}
{116}{}{Onde fica o armazém geral?}
{117}{}{Obrigado. Tchau.}
{118}{}{Apenas um dos mineiros. Você quer alguém importante?}
{119}{}{Sim.}
{120}{}{Não.}
{121}{}{Adeus.}
{122}{}{Os agitadores da cidade são Marcus, que é uma espécie de prefeito e xerife, Zaius, que é o capataz
 da mina, e Chad, que dirige a caravana. Phil, o barman, é o líder dos ghouls, eu acho... se você pode dizer
 que eles têm um líder. Quem era você, aliás?}
{123}{}{Onde eu posso achar o Marcus?}
{124}{}{Onde posso encontrar Zaius?}
{125}{}{Onde posso encontrar Cameron?}
{126}{}{Onde posso encontrar Chad?}
{127}{}{Onde posso encontrar Phil?}
{128}{}{Obrigado. Tchau.}
{129}{}{Se você acha que pode ajudar na mina, vá falar com Zaius. Ele geralmente está na cabana do
 capataz do lado de fora da mina, mas meio puto porque o purificador de ar foi desligado. Algo mais?}
{130}{}{Phil, o ghoul, administra o salão. Ele é meio que o porta-voz dos ghouls da cidade. Você pode
 encontrá-lo a leste do banco. Algo mais?}
{131}{}{Chad dirige as caravanas para fora de seu lugar na extremidade sudoeste da cidade. Algo mais?}
{132}{}{Liz, que é um tipo decente para um humano, administra o armazém a oeste do banco. Algo mais?}
{133}{}{Tudo bem então. Até logo.}
{134}{}{Cameron é o líder dos humanos normais aqui. Ele não gosta muito de mutantes ou ghouls, mas nos
 trata bem. Ele é um político, então você geralmente o encontra no banco ou no bar. Às vezes você
 pode até encontrá-lo trabalhando no ferreiro. Algo mais? O que eu estava fazendo? Ah sim... então... mais alguma
 coisa?}
{135}{}{Marcus é nosso líder, ele ajudou a fundar Broken Hills. Normalmente você pode encontrá-lo
 no banco ou na prisão. Algo mais?}
{136}{}{Ganancioso da porra. Você sabe o quanto trabalhamos duro? Espero que você apodreça.}
{137}{}{Obrigado pelo minério!}
{138}{}{Não acredito que a mina explodiu, vamos todos morrer de fome agora. Aquela mina era a
 única coisa que mantinha essa cidade funcionando. Bem, pelo menos posso ficar velho sem ter que trabalhar...}
{139}{}{Filho da puta! Morra!}
{140}{}{Obrigado por consertar a mina, devemos uma a você por isso. O que posso fazer por você?}
{141}{}{Quem é você?}
{142}{}{O que há para fazer nesta cidade?}
{143}{}{Nada.}
{144}{}{Devemos a você por nos salvar daqueles babacas da NCR. Valeu, cara. O que posso fazer por você?}
{145}{}{Quem é você?}
{146}{}{O que há para fazer nesta cidade?}
{147}{}{Nada.}
