{100}{}{Você vê um cavalheiro ágil e baixo.}
{101}{}{Você vê Micky, o caçador de tesouros.}
{102}{}{Esse homem minúsculo parece amigável e corajoso. Seu olhar fixo parece estar procurando porobjetos brilhantes.}
{103}{}{Olá! 'Cê não viu nenhuma jóia ou metal precioso por aí, viu?}
{104}{}{Mais uma vez, você me dá a graça da sua presença. Veio me alertar de algum tesouro escondido por aí?}
{105}{}{Então, alguma riqueza que você precisa rastrear? Eu sou o melhor dos melhores!}
{106}{}{Nium tizoro hoje.}
{107}{}{Sim. Precisar sua ajuda.}
{108}{}{Quem ser você?}
{109}{}{Adeus.}
{110}{}{Não, nada por hoje. Se eu cruzar com algum eu aviso.}
{111}{}{Bem, na verdade, sim. Eu acho que você seria o parceiro perfeito para uma, como posso dizer, "união empreendedora".}
{112}{}{Qual é o seu nome?}
{113}{}{Não importa.}
{114}{}{Eu? Eu sou o Micky, o alegre e suave Caçador de Tesouros de Broken Hills.}
{115}{}{Caçadô?}
{116}{}{Tchau-tchau.}
{117}{}{Caçador de tesouros?}
{118}{}{Que legal. Bom dia.}
{119}{}{Não me diga que nunca ouviu falar de mim!? Você nunca ouviu os contos do Micky Veloz? De suas
 batalhas armadas, ação e grandes pilhagens?}
{120}{}{Não.}
{121}{}{Creio que não tive o prazer.}
{122}{}{Bem, você é quem está perdendo. Qualquer dia desses eu te conto os detalhes sangrentos.}
{123}{}{Legaaaal.}
{124}{}{Aguardarei anciosamente.}
{125}{}{Hum... eu não deveria ter ficado surpreso. O mercado para Caçador de Tesouros caiu nos últimos
 anos. Toda essa morte e fome e luta-pela-sobevivência acabou com o senso de aventura das pessoas. Mantenha-me
 em mente no entanto, se pintar alguma coisa.}
{126}{}{Beleza.}
{127}{}{Você será o primeiro da minha lista.}
{128}{}{Sério?! Que legal! O que é? Ouro? Jóias? Artefatos sagrados?}
{129}{}{Dinhero pá caramba.}
{130}{}{Dexa pra lá..}
{131}{}{Aparentemente, uma grande quantia de dinheiro. O suficiente para viver confortavelmente por um bom tempo.}
{132}{}{Bem, na verdade, acho que vou trabalhar sozinho mais um pouco.}
{133}{}{Uau! Era por isso que eu estava esperando. O que me diz? Parceiros 50/50?}
{134}{}{É!}
{135}{}{Não. Tchau.}
{136}{}{Isso aí.}
{137}{}{Pensando bem, acho que vou tentar fazer isso sozinho. Te vejo depois.}
{138}{}{Excelente! Qual é a história? Onde estão os caras maus? O que 'cê quer que eu faça?}
{139}{}{Vem cumigo! Ir lugar escuro.}
{140}{}{Vamos dizer que você vai gastar um tempo numa "caverna" local.}
{141}{}{Legal! Apenas me indique as direções!}
{142}{}{Onde tesoro? Centro da cidade?}
{143}{}{Bem, eu não tenho certeza. Me disseram que eu poderia achar um tesouro por aqui.}
{144}{}{O quê? No centro da cidade? Rá! Seja lá quem for que te disse isso ou está mentindo ou é louco. Com
 exceção dos lugares mais inacessíveis e húmidos de Broken Hills, eu já estive por quase
 toda a cidade e não achei nada. Estou até pensando em me mudar.}
{145}{}{Que pena. Tchau-tchau.}
{146}{}{É uma pena. Eu realmente tinha esperanças. Tchau então.}
