{100}{}{Você vê um homem com o conjunto usando vestindo é um avental de couro.}
{101}{}{Você vê Balthas o curtidor.}
{102}{}{Você vê um homem alto e musculoso que parece e tem cheiro de couro.}
{151}{}{Meu filho foi morto por engano na luta .}
{152}{}{Eu não posso suportar viver sem Jonny.}
{153}{}{[Sob]}
{154}{}{Encontre conosco lá em baixo, para o Santo Farm. Nós vamos atacar os fantasmas.}
{155}{}{Olá, Balthas é meu nome. Eu trabalho com a retirada de couro aqui em Modoc. Posso ajudar?}
{156}{}{Você parece um pouco preocupado; Há algo de errado?}
{157}{}{Eu gostaria de ver seus produtos.}
{158}{}{Você já viu um relógio de ouro por aí em algum lugar?}
{159}{}{Volto mais tarde.}
{160}{}{Estou à procura de um item chamado de GECK. Você por acaso sabe alguma coisa sobre isso, ou como eu
  posso obter um?}
{161}{}{GECK?}
{163}{}{Com o que posso ajudar?}
{168}{}{Só estou olhando, obrigado.}
{171}{}{Sorte para encontrar Jonny?}
{172}{}{Eu encontrei este na parte inferior do poço seco antigo. Uma parte do poço tinha caído, ele foi nos escombros. Sinto muito, mas eu acredito que Jonny está morto.}
{173}{}{Não, nada ainda.}
{175}{}{Obrigado por devolver meu filho para mim. Não há nenhuma maneira que eu posso recompensá-lo, mas por favor, tome este
  armadura de couro, como agradecimento. Estive a experimentar com um novo processo de cura; Acho que você vai encontrar este
  armaduras muito durável, e, além disso - olhar você realmente é bom nisso.}
{176}{}{Obrigado por salvar o meu filho!}
{177}{}{Por favor, me deixe com a minha dor.}
{178}{}{Jonny is alive! Some people called Slags have rescued him. If you can wait just a little longer,
 I'm working on a way to get Jonny back home to you.}
{179}{}{Jonny está vivo! Algumas pessoas te chamam de Escória por tê-lo resgatado. Se você puder esperar um pouco mais,
Eu estou trabalhando em uma maneira de obter Jonny de volta a casa para você.}
{180}{}{Entendo; Desculpe incomodá-lo.}
{181}{}{Hein? Olha, eu não discuto minha vida pessoal com estranhos. Você tem algum negócio comigo ou
  não?}
{182}{}{Perdoe-me, meu nome é}
{183}{}{. Agora que estamos devidamente apresentados, você parece incomodado.}
{184}{}{Sim, eu estou interessado em alguns artigos de couro.}
{186}{}{Eu acho que não.}
{187}{}{Será que quis dizer }
{188}{}{? Sim, eu acho que eu ouvi falar de você. Um dos guardas em uma caravana mencionado algo de bom
  sobre uma pessoa com esse nome. Eu sei que você acabou de conhecer, mas eu poderia realmente usar o seu
  socorro.}
{189}{}{Por que você não me fala qual é seu problema, que talvez eu vou ser capaz de ajudar.}
{190}{}{Eu tenho meus próprios problemas, desculpe .}
{191}{}{[Ele pega um cinzel de metal e começa a torcer-lo ansiosamente. Para seu espanto, o cinzel começa
a dobrar como massa de vidraceiro. Forte] Meu menino cara!, Jonny, está faltando! Ele saiu para jogar há alguns dias e
nunca mais voltou. Nós temos procurado em todos os lugares, mas ainda não o encontramos.}
{192}{}{Onde é que Johnny jogar normalmente? Será que ele costuma jogar com outra pessoa?}
{193}{}{Sinto muito pelo seu filho, mas o que eu poderia fazer?}
{194}{}{Isso é horrível! Mas eu só parei para olhar alguns artigos de couro. Eu não suponho que eu poderia
  ver alguns de suas mercadorias?}
{195}{}{Oooh! Olhe para o tempo. Eu tenho que ir.}
{196}{}{Isso quer dizer que você vai me ajudar? Obrigado! Jonny foi visto pela última vez brincando com cowboys e índios
  seu cão Laddie em frente. Os dois eram inseparáveis; na verdade, é assim que soube que algo estava
  errado. Um dia, Laddie voltou sem Jonny. Nós temos procurado desde então. Tome Laddie com
  você; talvez os dois de você será capaz de encontrar Jonny.}
{197}{}{Bem, você tem o ar de um viajante experiente. Com suas habilidades, talvez você vai ser capaz de
  rastrear o meu filho.}
{198}{}{Bem, sim! Eu sou um rastreador bastante hábil, se eu digo assim sou eu. Ok, eu vou ajudar.}
{199}{}{Flattery levarão a lugar nenhum. Olha, eu preciso lhe fazer algumas perguntas.}
{200}{}{Minhas orações são respondidas! Tome Laddie com você; talvez ele possa ajudar. Por Favor
  apresse-se!}
{201}{}{Bem, talvez você tenha razão. Obrigado pela atenção.}
{202}{}{Já ouvi falar de você. Olha, eu não quero nenhum problema; Somos uma comunidade pacífica. Vamos apenas manter
  o assunto para negócios, OK?}
{203}{}{Eu tenho algumas perguntas para você.}
{204}{}{Eu não tenho qualquer negócio com você por enquanto. Tchau.}
{205}{}{Bem ... Eu estou preocupado com o meu filho desaparecido, Jonny. Nós temos procurado em todos os lugares, mas ainda não conseguiu encontrar
  ele. Temo que os animais selvagens talvez pegou.}
{206}{}{Talvez eu possa ajudar. Eu faço um monte de viajar; Eu vou manter um vigia para o seu menino.}
{208}{}{Eu realmente aprecio isso. Cada pequena ajuda. Nesse meio tempo, você teve algum
  negócio comigo?}
{210}{}{Não, não realmente. Eu estarei indo agora, obrigado.}
{211}{}{Desculpe, eu nunca ouvi falar disso.}
{214}{}{Hehehe. Tem Old Cornelius tenho você olhar para seu relógio de bolso, também? Não, você não vai encontrá-lo aqui.
Aquele velho galego acabou de sair de algum lugar e esqueceu.}
{215}{}{Obrigado de qualquer maneira, vou continuar procurando. Tchau}
{216}{}{[Ele olha para você sorri de perto e então.] Por que seja um bom menino e correr para fora
  e jogar?}
{217}{}{[Ele olha para você sorri de perto e então.] Por que não é uma boa menina e correr para fora
  e jogar?}
{218}{}{Por favor, continue procurando. Eu sei que ele ainda está vivo, eu posso sentir isso!}
{219}{}{Isso é arma do BB Jonny tudo certo. Noooooooooooooooooooo! [Balthas rompe e começa a chorar
  incontrolavelmente.]}
{220}{}{Eu sabia Jonny não estava morto! Você diz que eu tenho que esperar ... Eu não entendo! Ele está ferido? Meus instintos
  dizer-me para ir para o meu filho, mas eu sinto que você tem o melhor interesse do meu filho no coração. Por favor, depressa, e trazê-
  meu filho de volta para mim.}
{221}{}{Oh não! Não os fantasmas! Eu sabia que deveria ter queimado aquele lugar até o chão. Eu não vou deixá-los
  levar o meu menino ... Eu estou indo para ajudar o Jonny nas costas, custe o que custar. Tenho certeza que os moradores de Modoc
  iram me ajudar a conseguir o meu filho de volta! Encontre conosco no Santo Farm. Vamos matá-los todos!}
{230}{}{Você voltou em segurança Jonny volte para Modoc.}
{240}{}{Por favor, traga meu filho de volta para mim de forma segura.}
{2199}{}{Isso é arma do BB de Johnny tudo bem ... Eu não acredito que ele está morto. Por favor, continue olhando para o meu menino. Tenho certeza que ele ainda está lá fora.}
