{100}{}{Você vê um cartão de revendedor.}
{101}{}{Você vê um Monte de Três Cartas.}
{150}{}{Você vê um velho magro com o rosto queimado de sol. Ele é tão magro que parece uma tripa escorrida.}
{151}{}{Você vê um Monte de Três Cartas. Ele vasculha a rua, mancha e acena com a cabeça.}
{152}{}{Você vê um Monte de Três Cartas. Ele vasculha a rua, mancha e acena com a cabeça.}
{200}{}{Não entendo como perdi...}
{201}{}{Apenas continue andando... Monte não está funcionando hoje.}
{202}{}{Eu bati na carta errada?}
{203}{}{Como aquele tribal estúpido continuou escolhendo a carta certa?}
{205}{}{Heeeey! Herói! Você fez bem, muito bem.}
{206}{}{::Faz o sinal de positivo pra você::}
{207}{}{::Sorri, acena com a cabeça::}
{208}{}{Você fez bem, herói. Você fez bem.}
{215}{}{Onde diabos estão minhas cartas? Estavam AGORA aqui.}
{216}{}{Malditos gnomos do carro, agora eles vão atrás das minhas cartas de baralho.}
{220}{}{Ei, amigo, não se preocupe com os cassinos, venha brincar com o Monte.}
{221}{}{Quer arriscar, amigo? As melhores chance em New Reno! Vamos lá...}
{222}{}{Você, amigo. Você parece um cara de sorte, bora lá.}
{223}{}{Alguém que queira jogar? Seg-ay grátis, seg-ay grátis.}
{224}{}{Venha e jogue. No outro dia, ele pegou 50 fichas de mim, fácil.}
{225}{}{Fácil, basta adivinhar a Rainha, Rainha vermelha, e você ganha. Facinho.}
{226}{}{Você é alérgico a dinheiro fácil? Então venha aqui.}
{227}{}{Todo mundo está ganhando hoje... você quer ser o próximo?}
{228}{}{Os cassinos vão te enganar, te roubar... Monte te trata bem, te dá uma chance justa.}
{229}{}{Quer arriscar, moça? As melhores chances em New Reno! Vamos lá...}
{230}{}{Você é alérgico a dinheiro fácil, moça? Então venha aqui.}
{231}{}{Você, querida. Você parece uma garota de sorte, vamos lá.}
{232}{}{Ei, moça, não se preocupe com os cassinos. Venha brincar com o Monte.}
{233}{}{O Monte não está aberto para jogos hoje, amigo; minhas malditas cartas sumiram.}
{234}{}{(O velho sorri e a pele ao redor dos olhos se enruga.) Quer brincar, amigo?}
{235}{}{(O velho sorri, e a pele ao redor dos olhos se enruga.) Quer brincar, moça?}
{236}{}{(O velho sorri, e a pele ao redor de seus olhos se enruga.) Quer jogar, herói?}
{237}{}{(Monte sorri, e a pele ao redor de seus olhos se enruga.) Quer jogar, amigo?}
{238}{}{(Monte sorri, e a pele ao redor de seus olhos se enruga.) Quer jogar, moça?}
{239}{}{(Monte sorri, e a pele ao redor de seus olhos se enruga.) Quer jogar, herói?}
{240}{}{Monte de Três Cartas é o nome, e o jogo é o mesmo que o nome. Coloque 20 fichas e vamos direto ao assunto.}
{241}{}{Seu trapaceiro. Você não joga limpo}
{242}{}{Ok, aqui me ferra, não tenho certeza de quantos 20 são, então aqui está um monte}
{243}{}{Uh, estou lisonjeado, mas eu não quero ir direto ao assunto agora... falooou}
{244}{}{Desliga}
{245}{}{Vamos Jogar.}
{246}{}{Uh, descer para o que?}
{247}{}{Conheço bem esse jogo. Vamos lá.}
{248}{}{Monte de três cartas, eh? Você coloca três cartas viradas para baixo, embaralha e eu escolho uma carta. Se for a carta certa - o que não será, já que você a embaralhou na palma da mão - então eu ganho. Não, obrigado, amigo.}
{249}{}{Monte de três cartas, eh? Você coloca três cartas viradas para baixo, embaralha e eu escolho uma carta. Se for a carta certa - o que não será, já que você a embaralhou na palma da mão - então eu ganho. Não, obrigado, amigo.}
{250}{}{Hoje não, valeu.}
{251}{}{Descer para o quê? O jogo, claro!}
{252}{}{Veja... (mostra três cartas)... uma delas é uma dama. Eu as coloco viradas para baixo, embaralhei, então você escolhe qual é a rainha. Se você acertar, ganhou.}
{253}{}{Tão simples, cara.}
{254}{}{Tão simples, filha.}
{255}{}{Eu não jogo com um trapaceiro como você.}
{256}{}{Poderia explicar as regras novamente?}
{257}{}{Parece bastante simples, vamos jogar. Aqui estão 20 fichas.}
{258}{}{Hoje não, valeu.}
{260}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas, depois as joga no chão e as embaralha por alguns segundos.)}
{261}{}{Então... qual é a rainha, cara?}
{262}{}{Então... qual é a rainha, moça?}
{263}{}{(Você acha que é a da esquerda.)}
{264}{}{(Você acha que é a do meio.)}
{265}{}{(Você acha que é a da direita.)}
{266}{}{(Você não sabe. As cartas se moveram muito rápido.)}
{267}{}{Esc Esqerda}
{268}{}{O meio ai}
{269}{}{Din direta}
{270}{}{A da esquerda.}
{271}{}{A da direita.}
{272}{}{A do meio.}
{280}{}{(Monte vira a carta. É a }
{281}{}{Desculpe, cara, não foi dessa vez, mas você chegou PERTO.}
{282}{}{Desculpe, moça, não foi dessa vez, mas você chegou PERTO.}
{283}{}{Opa, você tem um bom olho para isso. Quer tentar novamente?}
{284}{}{Seu trapaceiro. Você não joga limpo}
{285}{}{Ok, aqui me ferra, não tenho certeza de quantos 20 são, então aqui está um monte}
{286}{}{Nâ-oo GOSTO desse jogo TCHAUUU}
{287}{}{Eu não jogo com um trapaceiro como você.}
{288}{}{Certo. Aqui estão 20 fichas.}
{289}{}{Não, obrigado.}
{300}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas e as coloca no chão. Ao fazer, ele pega uma carta, tão rápido que você quase a perde. Ele então começa a embaralhar por alguns segundos.)}
{301}{}{Então... qual é a rainha, cara?}
{302}{}{Então... qual é a rainha, moça?}
{303}{}{Você coloca em sleevie weevie, não joga limpo}
{304}{}{Esc Esqerda}
{305}{}{O meio ai}
{306}{}{Din direta}
{307}{}{Vagabundo PILANTRA. Eu vi você segurar aquela carta, me devolva o dinheiro antes que eu te apague aqui na rua.}
{308}{}{Aquele em sua manga.}
{309}{}{A da esquerda.}
{310}{}{A da direita.}
{311}{}{A do meio.}
{320}{}{O que você disse, colega?}
{321}{}{O que você disse, senhora?}
{322}{}{Você está me acusando de trapacear?}
{323}{}{Uh-uh. TRAPACERO}
{324}{}{Nuh-uh! Nuh-uh! Não fique bravo. Eu indo.}
{325}{}{Sim.}
{326}{}{Que vá à merda, fique com o dinheiro, estou saindo fora.}
{330}{}{Olha, eu não tenho tempo para perdedores bunda mole. Você paga seu dinheiro e arrisca,
 só. Se você quer JOGAR, tudo bem, mas se você só vai ficar com graça quando perder,
 então saia!}
{331}{}{EU QUEBRAR VOCÊ}
{332}{}{Nuh-uh! Nuh-uh! Não fique bravo. Eu indo.}
{333}{}{É isso. Você está morto.}
{334}{}{Tudo bem, tudo bem, foi mal. Aqui estão 20 fichas. Vamos jogar de novo.}
{335}{}{Foda-se. Fique com o dinheiro, estou saindo fora.}
{340}{}{(Você entrega o dinheiro. Monte acena com a cabeça, depois bate as cartas e as embaralha por alguns segundos.)}
{341}{}{Então... qual é a rainha, cara?}
{342}{}{Então... qual é a rainha, moça?}
{343}{}{(Monte está usando seu baralho normal! Você precisa roubar o outro baralho dele para completar a troca.)}
{344}{}{Você coloca em sleevie weevie, não joga limpo}
{345}{}{Esc Esquerda}
{346}{}{O meio ai}
{347}{}{Din direta}
{348}{}{Vagabundo PILANTRA. Eu vi você segurar aquela carta, me devolva o dinheiro antes que eu te apague aqui na rua.}
{349}{}{Aquele em sua manga.}
{350}{}{A da esquerda}
{351}{}{A da direita.}
{352}{}{A do meio.}
{360}{}{(Você entrega o dinheiro. Monte acena com a cabeça, mostra as cartas, depois as joga no chão e as embaralha por alguns segundos.)}
{361}{}{(Você entrega o dinheiro. Monte parece desconfortável.) Uh... tudo bem... (Monte coloca as cartas no chão e as embaralha.)}
{362}{}{Então... qual é a rainha, cara?}
{363}{}{Então... qual é a rainha, moça?}
{364}{}{(Monte está usando o baralho marcado. Qualquer escolha é a certa.)}
{365}{}{Esqueda! Esq-erda!}
{366}{}{Direta! Di-reira!}
{367}{}{Meio! Mei!}
{368}{}{Oh, eu não sei... a da esquerda.}
{369}{}{Hmmmm... talvez a da direita?}
{370}{}{Puxa, não tenho certeza... acho que é a do meio.}
{375}{}{(Monte vira a carta. É a rainha de copas. O bixo ficou em choque.) Uh...? Heh. Eh...}
{376}{}{acho que você ganhou, cara.}
{377}{}{acho que você ganhou, senhora.}
{378}{}{(Ele entrega o dinheiro com relutância.)}
{379}{}{De novo! De novo!}
{380}{}{Obrigado, já vou agora}
{381}{}{Eai, vamos jogar de novo? Vamos, Monte. Nem comecei a aquecer.}
{382}{}{Bom, obrigado, Monte. Até mais.}
{385}{}{(Monte vira a carta. É a rainha de copas. Ele fica em choque.) Uh...? Eh... ah...}
{386}{}{acho que você ganhou, cara.}
{387}{}{acho que você ganhou, senhora.}
{388}{}{Mas isso me limpa... (Olha para você fracamente) Mais alguma coisa que eu possa fazer por você?}
{389}{}{De boa, eu tava upando um EXP extra. Tchau. Tchau.}
{390}{}{O que você conseguiu?}
{391}{}{Por que você não me dá algumas informações?}
{392}{}{Esquece, Monte. Te chamaremos ainda hoje.}
{400}{}{(Parece aflito.) Eh... bem, eu tenho algo... mas vale MUITO mais do que você ganhou... ainda assim...}
{401}{}{Sério? O que é?}
{402}{}{Se vale a pena para você mais do que a morte na Gólgota porque ficou endividado, problema seu. Se eu fosse
 você, pensaria mais sobre isso.}
{404}{}{Eh... hmnnn... depende do que você quer saber.}
{405}{}{Você sabe quem espanou o filho do Wright? O fez O.D. no Jet?}
{406}{}{Sabe onde posso encontrar um cara chamado Pretty Boy Lloyd?}
{407}{}{Sabe onde tá meu carro, Monte?}
{408}{}{Tem alguma coisa que você acha que eu deveria saber?}
{409}{}{Nada não, Monte. Estamos quites. Até mais.}
{415}{}{Eh... bem... olhe, você não ouviu nada de mim, mas eu aposto no Renesco, aquele babaca que tem a farmácia no lado oeste.
 Não tenho certeza se ele vendeu para o garoto, mas ele sabe de alguma coisa. Isso é tudo que eu vou dizer.}
{416}{}{Tudo bem então, Monte. Estamos quites.}
{420}{}{Eh... bem... (parece que ele tem uma luta interior) ...olha, você não ouviu isso de mim, mas se eu fosse
 você, daria uma olhada no porão do Desperado.}
{421}{}{Tudo bem então, Monte. Estamos quites.}
{425}{}{(Aperta os olhos e se inclina) Eu perguntaria ao velho Jules na frente da cidade. Nada passa
 sem ele saber... e se aconteceu, então ele teria um dedo nisso, entendeu o que estou dizendo?}
{426}{}{Tudo bem então, Monte. Estamos quites.}
{430}{}{Bem... conhece aquele tal Eldridge que dirige a New Reno Arms? Ele diz que faz upgrades em armas, mas nunca o
 vejo fazer nada da vida. Talvez seja bom dar uma olhada na casa dele... mas você não ouviu isso de mim.}
{431}{}{Tudo bem então, Monte. Estamos quites.}
{435}{}{(Monte franze a testa quando te vê.) Olha, não vou fazer nenhum jogo hoje, certo? Saia.}
{436}{}{Posso comprar aquele cartão que você me mostrou antes?}
{437}{}{Procuro algumas informações...}
{438}{}{Tudo bem, Monte. Eu vou embora... por enquanto.}
{440}{}{Não, não vou me livrar disso, esquece. É um item AUTENTICO do pré-guerra... um pedacinho da história. NEM VEM.}
{441}{}{Você está me fazendo OUTRA oferta? Já te disse que não estou vendendo.}
{442}{}{Que tal mil fichas? Eu tenho comigo. Tudo isso em troca desse cartão.}
{443}{}{Nem mesmo por 750 fichas?}
{444}{}{Que tal 500 fichas?}
{445}{}{250 fichas parece bom?}
{446}{}{OK. Eu tinha algumas outras perguntas...}
{447}{}{Deixa pra lá, Monte. Estou fora daqui.}
{450}{}{Está surdo? Essa quantia nem é suficiente para me interessar.}
{451}{}{Que tal eu sugerir outra quantia...?}
{452}{}{Eu tenho mais algumas perguntas...}
{453}{}{Deixa pra lá, Monte. Estou fora daqui.}
{460}{}{Bem, não é tão caro para mim. É seu, amigo. (Ele olha para a direita e para a esquerda, depois se abaixa e tira a
 bota. Ele torce o calcanhar e tira uma carta de baralho de dentro.) Aqui está. Tome conta disso.}
{461}{}{Eu tenho mais algumas perguntas...}
{462}{}{Obrigado, Monte. Sempre será prazer.}
{465}{}{(Carranca) O que eu digo depende do que você quer saber. E não será barato.}
{466}{}{Você sabe quem espanou o filho do Wright? O fez O.D. no Jet?}
{467}{}{Sabe onde posso encontrar um cara chamado Pretty Boy Lloyd?}
{468}{}{Sabe onde tá meu carro, Monte?}
{469}{}{Tem alguma coisa que você acha que eu deveria saber?}
{470}{}{Deixa pra lá, Monte. Estou fora daqui.}
{475}{}{Não vou tocar nesse assunto da Gólgota. Vá dar uma passeada.}
{476}{}{Olha, esse assunto é só uma má notícia. Deixa pra lá, está bem?}
{477}{}{Está me fazendo outra oferta? Olha, eu disse que NÃO vou falar sobre isso.}
{478}{}{Mil fichas mudam sua ideia? Eu tenho aqui.}
{479}{}{Nem mesmo por 750 fichas?}
{480}{}{Que tal 500 fichas?}
{481}{}{250 fichas parece bom?}
{482}{}{Uh... Gólgota?}
{483}{}{Eu tenho mais algumas perguntas...}
{484}{}{Deixa pra lá, Monte. Estou fora daqui.}
{490}{}{(Balança a cabeça.) De jeito nenhum. Falar sobre isso pode matar alguém, começando por mim. Esqueça.}
{491}{}{Que tal se eu te oferecesse isso...}
{492}{}{Eu tenho mais algumas perguntas...}
{493}{}{Deixa pra lá, Monte. Estou fora daqui.}
{495}{}{Eh... bem... isso é um monte de fichas. (Lambe os lábios. Ele parece estar lutando uma batalha interna... mas dura pouco.) Olha, você não ouviu isso de mim...}
{496}{}{Entendido, prossiga.}
{500}{}{(Risos) Talvez eu tenha ouvido alguma coisa, talvez não. Diga um preço.}
{501}{}{Tudo bem... Diga um preço.}
{502}{}{Que tal mil fichas? Eu tenho comigo.}
{503}{}{Nem mesmo por 750 fichas?}
{504}{}{Que tal 500 fichas?}
{505}{}{250 fichas parece bom?}
{506}{}{Eu tenho mais algumas perguntas...}
{507}{}{Deixa pra lá, Monte. Estou fora daqui.}
{510}{}{Ah! Você não pode comprar um balde de mijo com isso. Esqueça.}
{511}{}{Que tal se eu te oferecesse isso...}
{512}{}{Eu tenho mais algumas perguntas...}
{513}{}{Deixa pra lá, Monte. Estou fora daqui.}
{515}{}{Tá certo. (Sorri maliciosamente.) Olha, você não ouviu isso de mim, mas se eu fosse você, eu olharia o porão do Desperado na Virgin Street. Há muitos "ratos" lá, se você me entende.}
{516}{}{Eu tenho mais algumas perguntas...}
{517}{}{Entendi. Obrigado.}
{520}{}{(Encolhe os ombros) Talvez eu saiba algo sobre isso, talvez não. Me fale um preço e talvez eu tenha algo a dizer.}
{521}{}{Tudo bem... Diga um preço.}
{522}{}{Que tal mil fichas? Eu tenho comigo.}
{523}{}{Nem mesmo por 750 fichas?}
{524}{}{Que tal 500 fichas?}
{525}{}{250 fichas parece bom?}
{526}{}{Eu tenho mais algumas perguntas...}
{527}{}{Deixa pra lá, Monte. Estou fora daqui.}
{530}{}{(Aperta os olhos, se inclina) Por essa quantia, não sei de nada.}
{531}{}{Que tal se eu te oferecesse isso...}
{532}{}{Eu tenho mais algumas perguntas...}
{533}{}{Deixa pra lá, Monte. Estou fora daqui.}
{535}{}{Isso mesmo... (cerra os olhos, se inclina) ...eu perguntaria ao velho Jules na frente da cidade.
 Nada passa por ele... e se aconteceu, então deve ter um dedo nele, entendeu o que eu disse?}
{536}{}{Eu tenho mais algumas perguntas...}
{537}{}{Tudo bem então, Monte. Obrigado.}
{540}{}{(Dá de ombros) Eu ouço coisas, eu vejo coisas. Por 200 fichas, talvez você possa ouvir um pouco da minha experiência, entendeu o que eu disse?}
{541}{}{Aqui estão as 200 fichas.}
{542}{}{Te dou 150.}
{543}{}{100 fichas ou nada.}
{544}{}{Eu tenho mais algumas perguntas...}
{545}{}{Deixa pra lá, Monte. Estou fora daqui.}
{550}{}{Você é surdo? EU DISSE 200 fichas, só com isso.}
{551}{}{Tá bom. Tome as 200 fichas.}
{552}{}{Eu tenho mais algumas perguntas...}
{553}{}{Deixa pra lá, Monte. Estou fora daqui.}
{555}{}{Feito. (Monte se aproxima) Bem, conhece aquele cara Eldridge, que comanda a New Reno Arms?
 Ele DIZ que faz melhorias em armas, mas eu nunca o vejo fazer nada. Talvez você possa dar uma olhada... mas você não ouviu isso de mim.}
{556}{}{Eu tenho mais algumas perguntas...}
{557}{}{Compreendido, tenha um bom dia.}
{560}{}{O cemitério ao sul da cidade. Fede até quase você perder a consciência, isso é certo.}
{561}{}{Oh, eu vejo. Agora, sobre o garoto Wright...}
{562}{}{Esqueça o garoto Wright. Eu tinha outras perguntas...}
{563}{}{Tudo bem então, Monte. Obrigado.}
{565}{}{Minhas apostas são em Renesco, aquele velho fudido que gerencia a farmácia na zona
 oeste. Eu não tenho certeza se ele vendeu algo para o garoto, mas ele sabe de ALGUMA COISA. (Olha ao redor) Isso é tudo que vou dizer.}
{566}{}{Eu tenho mais algumas perguntas...}
{567}{}{Tudo bem então, Monte. Obrigado.}
{570}{}{(Ele olha ao redor, depois se abaixa e tira a bota. Ele torce o calcanhar e tira um cartão... no cartão está um homem com
 um chapéu estranho, empunhando um porrete.) Interessado? São lembranças genuínas do pré-guerra.}
{571}{}{Não, eu já tenho itens suficientes no inventário... Prefiro ouvir algumas informações.}
{572}{}{Certo. Por que não? Isso vai resolver as coisas entre nós.}
{573}{}{Desculpe, cara, sem fichas, sem jogo. Volte quando tiver alguma coisa.}
{574}{}{Desculpe, querida, sem fichas, sem jogo. Volte quando tiver alguma coisa.}
{575}{}{Sim, talvez na próxima.}
{576}{}{Na maciota, você troca o baralho de cartas de Monte pelo baralho marcado.}
{600}{}{espadas}
{601}{}{copas}
{602}{}{ouro}
{603}{}{paus}
{604}{}{dois}
{605}{}{três}
{606}{}{quatro}
{607}{}{cinco}
{608}{}{seis}
{609}{}{sete}
{610}{}{oito}
{611}{}{nove}
{612}{}{dez}
{613}{}{ de }
