{100}{}{Você vê uma atriz porno.}
{150}{}{Você vê uma gostosinha. Ela parece estar falando sozinha.}
{151}{}{Parece que ela está memorizando algumas falas. Ela acaba desistindo, faz um "O" com a boca e começa a balançar a cabeça.}
{152}{}{Você vê uma atriz porno. Ela te deixa no vaco.}
{200}{}{Suponho que devo te agradecer por salvar o mundo, mas prefiro dar um metão bem bem selvagem com você.
 Pode ser?}
{201}{}{Ouvi dizer que você é o fodão que chutou a bunda da Enclave.}
{202}{}{Caras que chutam esse governo maligno da Enclave me deixam molhadinha.}
{203}{}{Ouvi dizer que os Brothers estão procurando por você. Eles querem fazer um filme baseado nas suas aventuras.}
{210}{}{Acho que devo te agradecer por salvar o mundo. Uh... valeu.}
{211}{}{Ouvi dizer que foi você quem chutou a bunda da Enclave. Impressionante.}
{212}{}{Ouvi dizer que os Irmãos estão te procurando. Eles querem fazer um filme baseado em suas aventuras. Você poderia tentar me encaixar em alguma parte...?}
{220}{}{Poderia, POR FAVOR, parar de andar com esse treco que você está vestindo? Estou tentando decorar minhas falas.}
{221}{}{Volte para o seu Fallout 4, isso aqui é o Fallout 2! É um RPG!}
{222}{}{Você está compensando alguma coisa que falta?}
{230}{}{Como vai, }
{231}{}{Olhando melhor, }
{232}{}{Ei, gracinha! Você está se cuidando?}
{233}{}{Eles não me PAGAM o suficiente.}
{234}{}{Vamos ver… "Oh Deus"… "Mete fundo…" Droga! Qual é a próxima fala?!}
{235}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{236}{}{Vamos ver... (consulta o roteiro)... ele entra, transamos. Entendi.}
{237}{}{Eu quero fazer algo mais direto.}
{238}{}{Graças a Deus eles finalmente instalaram aquela cabeceira acolchoada.}
{239}{}{Eu não sei o que os Corsican Brothers viram nela...}
{240}{}{Eu gostaria que ela fosse embora para sempre.}
{241}{}{Ela pega no meu estilo.}
{242}{}{Oh, ela é uma devoradora de homens, uma canibal insaciável.}
{243}{}{Hummf. Lixo do caralho.}
{244}{}{Ela é tão talentosa quanto uma pedra. E duas vezes mais feia.}
{250}{}{Como vai, }
{251}{}{Agora TEM encrenca na qual eu quero me meter.}
{252}{}{Procurando por mim?}
{253}{}{Por que você não vem aqui com mais freqüência?}
{254}{}{Tenho uma vaga que você pode preencher.}
{255}{}{Já estava na hora de um homão da porra aparecer aqui...}
{256}{}{Vamos ver... "Oh Deus"... "Mete mais..." Droga! Qual é a próxima fala?}
{257}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{258}{}{Vamos ver... (consulta o roteiro)... ele entra, transamos. Entendi.}
{259}{}{Eu quero fazer algo mais direto.}
{260}{}{Graças a Deus eles finalmente instalaram aquela cabeceira acolchoada.}
{265}{}{Como vai, }
{266}{}{Agora TEM encrenca na qual eu quero me meter.}
{267}{}{Procurando por mim?}
{268}{}{Por que você não vem aqui com mais freqüência?}
{269}{}{Tenho uma vaga que você pode preencher.}
{270}{}{Já estava na hora de um homão da porra aparecer aqui...}
{271}{}{Vamos ver... "Oh Deus"... "Mete mais..." Droga! Qual é a próxima fala?}
{272}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{273}{}{Vamos ver... (consulta o roteiro)... ele entra, transamos. Entendi.}
{274}{}{Eu quero fazer algo mais direto.}
{275}{}{Graças a Deus eles finalmente instalaram aquela cabeceira acolchoada.}
{280}{}{Que cheiro é esse?}
{281}{}{Genial, mais um tribal comedor de bosta.}
{282}{}{Não fala comigo.}
{283}{}{Vamos ver..."Oh deus"... "Mete fundo..." Droga! Qual é a próxima fala?}
{284}{}{Sim, mas qual é a minha MOTIVAÇÃO para esta cena?}
{285}{}{Vamos ver... (Consulta o roteiro)... ele entra, transamos. Entendi.}
{286}{}{Eu quero fazer algo mais direto.}
{287}{}{Graças a Deus eles finalmente instalaram aquela cabeceira acolchoada.}
{288}{}{Preferia que não falasse comigo diretamente. Fale mentalmente e depois imagine minha resposta.}
{289}{}{Quem é você?}
{290}{}{Você é da equipe de limpeza?}
{295}{}{Você não é meio baixinho para um soldado?}
{296}{}{Aihhhhhh! O que você está tentando fazer? Me dar um AVC?! Saia daqui!}
{297}{}{Você saiu de qual filme? O Dia em que a Terra Parou? Saia daqui!}
{298}{}{Poderia, POR FAVOR, parar de andar com esse treco que você está vestindo? Estou tentando decorar minhas falas.}
{299}{}{Você está compensando alguma coisa que falta?}
{305}{}{Como vai, }
{306}{}{Quer me ajudar a ensaiar minhas falas?}
{307}{}{Quer tomar uma ducha comigo antes da próxima cena?}
{308}{}{Eu amo essa coisa que você faz com a língua.}
{309}{}{Faço o papel do estudante de intercambio francês da porta da frente.}
{310}{}{Você é o mordomo ou o motorista na cena 3?}
{311}{}{Você pode me passar um pouco de Jet?}
{312}{}{Esses takes são muito longos... eles me deixaram esgotada.}
{313}{}{Acho que FINALMENTE vamos fazer uma cena juntos.}
{314}{}{Meus namorados não sabem que eu trabalho aqui. Não que eu me importe com o que eles acham.}
{315}{}{Eu não vi os irmãos por aqui... tente o escritório, beleza?}
{316}{}{Não importa onde você bota, só se certifique de que a câmera tirou a melhor foto.}
{317}{}{Você é um homem de paixão e mistério. Um homem de luxúria.}
{318}{}{Bem, vamos fazer de um jeito mais confortável para você.}
{319}{}{Estarei pronta para a próxima cena assim que tomar um banho longo e quente.}
{320}{}{Eu sou uma mãe para todos aqueles que precisam de amor.}
{321}{}{Você vai ser uma estrela. Uma estrela, uma estrela grande e brilhante.}
{322}{}{Você é mais quente que um vulcão em um dia ruim.}
{323}{}{Adoro quando você faz o sotaque espanhol.}
{324}{}{Está muito bem, docinho.}
{330}{}{::Te ignora::}
{331}{}{Você é a garota francesa ou a garota russa na próxima cena?}
{332}{}{Eu gostaria que o controle de natalidade fosse um pouco mais confiável.}
{333}{}{Você roubou meus saltos altos?}
{334}{}{Estou me sentindo um pouco cansado... tem algum jet?}
{335}{}{Hmphhh!}
{336}{}{Não, me desculpe, amor. Não sei onde estão os Irmãos.}
{337}{}{Te mostrar onde é a saída?}
{338}{}{Você engordou um pouco?}
{339}{}{Você poderia, por favor, recuar um pouco. Seu... cheiro... me deixa enjoada.}
{340}{}{Ouvi dizer que os Irmãos vão dispensar seus serviços. Sinto muito, sinto MESMO.}
{341}{}{Se alguém tão sem talento como você consegue fazer isso, eu posso fazer coisas melhores.}
{342}{}{Sua bunda é gordinha! Que fofo!}
{343}{}{Acho que não é muito difícil fazer parte desta indústria.}
{344}{}{*Eu* não disse nada sobre você ser gorda ou feia. Deve ter sido outra pessoa.}
{345}{}{Ouvi dizer que nenhum ator quer trabalhar com você.}
{346}{}{Você não tomou banho antes de vir?}
{350}{}{Como vai, }
{351}{}{Quer sair do boxe e entrar no pornô? É a mesma coisa, só o palco que é diferente.}
{352}{}{Quer pular no ringue comigo, campeão?}
{353}{}{Quer lutar, campeão?}
{354}{}{Cuidado com o mastigador. Ele é maluco, tentou até morder minha orelha.}
{355}{}{Quer me ajudar a ensaiar minhas falas?}
{356}{}{Você pode me passar um pouco de Jet?}
{357}{}{Esses takes são muito longos... eles me deixaram esgotada.}
{358}{}{Você quer provar algo da cozinha?}
{359}{}{Você tem um belo conjunto.}
{360}{}{Meus namorados não sabem que eu trabalho aqui. Não que eu me importe com o que eles acham.}
{361}{}{Depois não tenho nada, no caso de você estar procurando companhia.}
{362}{}{Você quer se meter no negócio? Bem vindo a bordo.}
{363}{}{Belo material o que você tem aí.}
{364}{}{Você deveria estar no pornô. Você tem o corpo pra isso.}
{365}{}{Você tem um belo conjunto.}
{366}{}{Depois não tenho nada, no caso de você estar procurando companhia.}
{367}{}{Eu falar de você. Você é }
{368}{}{Seu chefe mandou você me buscar?}
{369}{}{Você está tentando conseguir uma transa de mim? Vá em frente.}
{370}{}{O chefe nunca me mencionou?}
{380}{}{What's it like boxing?}
{381}{}{Cuidado com o mastigador. Ele é maluco, tentou até morder minha orelha.}
{382}{}{Love your outfit. Tres chic.}
{383}{}{That outfit looks great on you.}
{384}{}{What do you wa... oh! Ma'am! Welcome to the studio.}
{385}{}{Meus namorados não sabem que eu trabalho aqui. Não que eu me importe com o que eles acham.}
{386}{}{Um... you couldn't set me up with a little Jet, could you, ma'am?}
{387}{}{Esses takes são muito longos... eles me deixaram esgotada.}
{388}{}{Am I doing anything later? Er... no, ma'am. Not at all.}
{389}{}{What's it like working for the boss?}
{390}{}{The boss ever talk about me?}
{395}{}{Look, bondage and S&M are on Wednesdays only. Now squeak your leather ass outta here.}
{396}{}{I seriously doubt the Brothers are looking for another leather act after that Happily Leather After fiasco.}
{397}{}{Please stop bothering me. I'm trying to memorize these lines.}
{398}{}{I THOUGHT I smelled leather. I thought it was a couch.}
{399}{}{Look, leather bunny, if you don't have your own whip, the Brothers won't even give you the time of day.}
{410}{}{You? No thanks. I could have better sex with my lipstick.}
{411}{}{Why don't you go amuse yourself with a pencil sharpener?}
{412}{}{I don't have time to have a boring meaningless conversation with you right now.}
{413}{}{I don't care if you can hammer a six inch spike through a board with your penis. Now get lost.}
{414}{}{Sex? No, I'm married, otherwise I still wouldn't.}
{415}{}{I don't date white guys.}
{416}{}{You couldn't possibly be better than my shower massager.}
{417}{}{You don't look like you could support my shopping habit.}
{418}{}{Honey, you couldn't afford me.}
{419}{}{I'm just looking for the right guy. Thanks for keeping me company till he shows up.}
{420}{}{You're not going to have any luck getting into my pants. There's only room for one asshole in there.}
{421}{}{I'm sorry, I thought you were good looking, but I was mistaken.}
{422}{}{Você? Desculpe, eu NUNCA estive com tanto desespero.}
{423}{}{I haven't seen the Brothers around... now don't bother me. I'm an actress.}
{424}{}{Por favor... sem autógrafos.}
{425}{}{I really want to direct.}
{426}{}{I'm dancing at the casinos on Thursday. Catch my act and bring some chips.}
{427}{}{You couldn't possibly imagine the stress of my life.}
{428}{}{Meus namorados não sabem que eu trabalho aqui. Não que eu me importe com o que eles acham.}
{429}{}{PLEASE stop bothering me. I'm trying to memorize these lines.}
{430}{}{Se estiver procurando trabalho, fale com os Brothers.}
{431}{}{Você é a nova excitadora?}
{432}{}{You the new janitor? I don't imagine what else you could be.}
{433}{}{If you're the new janitor, you could start by wiping my ass.}
{434}{}{I haven't seen the Brothers around, girl... now don't bother me. I'm an actress.}
{435}{}{Please, girl... no autographs.}
{436}{}{MAYBE if you cleaned yourself up some more, you could be a fluffer.}
{437}{}{Sorry, no, I couldn't be a lesbian for less than 200 chips. For you, 300.}
{438}{}{I'm dancing at the casinos on Thursday. Catch my act and bring some chips.}
{439}{}{Girl, YOU couldn't possibly imagine the stress of my life.}
{1230}{}{?}
{1231}{}{.}
{1250}{}{?}
{1265}{}{?}
{1305}{}{?}
{1350}{}{?}
{1367}{}{, aren't you?}
