{100}{}{You see one of Bishop's men.}
{150}{}{You see a rugged looking man dressed in leather armor. Numerous scars and gunshot wounds
 cover his body.}
{151}{}{You see one of Bishop's men. He is scanning the area and fingering his weapon.}
{200}{}{Ei! }
{201}{}{::cheers::}
{202}{}{::palmas::}
{203}{}{::whistles::}
{205}{}{Como diabos você vai no banheiro com essa coisa?}
{210}{}{Bela arma, }
{215}{}{Uh, why are you sneaking around, }
{216}{}{Uh, hey, }
{220}{}{Yo, }
{221}{}{Ei, }
{222}{}{Ei, }
{225}{}{You just walked into the wrong place, dipshit.}
{226}{}{Well, look at the brass balls on this son of a bitch... get, boy, before we gun you down.}
{227}{}{Esse cara tá procurando problemas...}
{228}{}{I hear the }
{229}{}{You better leave, }
{230}{}{Ora ora, se não é }
{231}{}{Didn't think members of family }
{232}{}{You just walked into the wrong place, bitch.}
{233}{}{Well, look at the swagger on this bitch...}
{234}{}{Get, girl. Before we gun you down.}
{235}{}{This bitch's asking for trouble...}
{236}{}{I hear the }
{250}{}{Yo, champ. No weapons in here, 'kay?}
{251}{}{Yo, champ! Put that weapon away.}
{252}{}{Ei, }
{255}{}{What are you sneaking around for?}
{256}{}{Are you trying to avoid your fans?}
{257}{}{Uh, why all the secrecy?}
{260}{}{Yo, }
{261}{}{Yo, }
{265}{}{Yo, lover-boy. No weapons in here, 'kay?}
{266}{}{Ei, }
{267}{}{Yo, }
{268}{}{Honey, you can't be carryin' weapons in here. Heh-heh... you're deadly enough as it is.}
{269}{}{Ei, }
{275}{}{Honey, with a body like that, you won't be able to sneak anywhere.}
{280}{}{Love the films, }
{281}{}{Loved you in Great Balls for Hire.}
{282}{}{Loved you in Good Will Humping.}
{283}{}{I'm a big fan of your work in Pokeahotass.}
{284}{}{Loved "Vault Sex-Teen." It was inspiring. A cinematic tour-de-force.}
{285}{}{::Assobios::}
{295}{}{You looking to fill a grave in Golgotha, slaver? Put that thing away.}
{296}{}{Put that weapon away, slaver, or I'll use you for target practice.}
{297}{}{Slaver, you better secure that weapon right NOW.}
{300}{}{You looking to fill a grave in Golgotha, slaver? Stop sneaking around.}
{301}{}{Stop sneaking around, slaver, or I'll use you for target practice.}
{302}{}{Maybe you better go back to ninja school, slaver - now stop sneaking around.}
{303}{}{Slaver, you better stop that sneaking around shit right NOW.}
{305}{}{You looking to fill a grave in Golgotha, tribal? Put that thing away.}
{306}{}{Put that weapon away, tribal, or I'll use you for target practice.}
{307}{}{Tribal, you better secure that weapon right NOW.}
{310}{}{You looking to fill a grave in Golgotha, tribal? Stop sneaking around.}
{311}{}{Stop sneaking around, tribal, or I'll use you for target practice.}
{312}{}{Maybe you better go back to ninja school, tribal - now stop sneaking around.}
{313}{}{Tribal, you better stop that sneaking around shit right NOW.}
{315}{}{Get that robot outta here. Now.}
{316}{}{Get that robot outta here before we turn it into a trashcan fire.}
{317}{}{That robot's gonna be spare parts if it stays.}
{320}{}{I *thought* I smelled mutant. You better get his yellow ass outta here.}
{321}{}{You and your mutant friend looking to get shot? Beat it.}
{322}{}{That mutant better get outta here right now, or we'll be mounting his head on a wall.}
{325}{}{Catch the fight last night?}
{326}{}{I'm hitting the Cat's Paw after work.}
{330}{}{I thought the President was a myth, a boogey man used to scare children.}
{331}{}{Parece que você voltou do inferno. Relaxe um pouco. Você merece.}
{332}{}{They were gonna dump some new virus into the air? Bastards. Hope you shot a few for me.}
{333}{}{You might want to replay the game as a different character.}
{334}{}{You've got some serious muscle to bust the Enclave like you did.}
{335}{}{Just wandering around after you're done, picking up some EXPs, huh? Well, please don't
 kill ME, 'kay?}
{336}{}{New Reno was designed by Chris Avellone and scripted by Tom French. Rumor has it they will
 marry soon.}
{337}{}{I hope I get to be a major character in Fallout 3, like Tandi or Ian. Being a thug sucks.}
{338}{}{Yeah, I scored with Tandi once. When she was young, I mean.}
{339}{}{That Lynette chick is in bad need of some lovin', y'know?}
{340}{}{Heard you busted up that Enclave down South. Pretty brave.}
{350}{}{Ei, }
{351}{}{Yo, }
{352}{}{Ei, }
{353}{}{I heard Tommy the Balls is back in town, checking up on things. Watch out for him.}
{354}{}{You see Tommy the Balls, stay outta his way.}
{355}{}{Put in a good word with Bishop for me?}
{356}{}{Nice threads. Wish I had it in good with the boss, too.}
{357}{}{Any tips for a fella like me?}
{358}{}{Family Bishop's been good to me.}
{359}{}{John Bishop is gonna rule this town.}
{360}{}{Everything's been pretty quiet today.}
{361}{}{Storm's coming.}
{362}{}{Stink from Golgotha was awful last night.}
{363}{}{When we gonna whack one of the other families?}
{364}{}{With you on our side, those other families don't stand a chance, boss.}
{365}{}{Get you anything, boss?}
{366}{}{Any word on the other families?}
{367}{}{Um, got any Jet?}
{368}{}{Com certeza eu gostaria de um copo...}
{369}{}{Mrs. Bishop was checking me out again. It makes me uncomfortable.}
{370}{}{Mrs. Bishop keeps looking at me like a slab of beef. I wish she'd realize that I just
 want to be held.}
{371}{}{That Bishop girl is one nice piece of ass.}
{372}{}{That Bishop girl is trouble.}
{373}{}{I heard one of the boys got the Bishop daughter drunk, and Mr. Bishop skinned him.}
{374}{}{If you talk to Bishop, stay away from the wife and daughter... nothing but trouble.}
{380}{}{Heard Mrs. Bishop was looking for you. Watch out, pal.}
{381}{}{Heard the Bishop daughter was looking for you. She's trouble.}
{382}{}{Você não parece tão forte, Sr. Prizefighter.}
{383}{}{You know, Family Bishop could really use someone like you. Tough. Uncompromising.}
{384}{}{You should talk to Bishop about a job.}
{385}{}{You might want to consider joining up with us. We're gonna rule New Reno.}
{386}{}{I got $20 riding on you!}
{387}{}{Ei, campeão! Aquela última luta foi ótima!}
{388}{}{Vi você lutando no ringue. Que belo gancho que você deu.}
{389}{}{You gonna take the fall? I got $30 riding on you.}
{390}{}{Quanto você pesa?}
{391}{}{Onde você trabalha fora do ringue?}
{392}{}{Cuidado com o Masticator. Ele é louco por orelhas.}
{393}{}{Eu te pagaria uma bebida se não tivesse perdido todo meu dinheiro apostando no seu oponente.}
{394}{}{Quer lutar?}
{395}{}{Você não parece ser tão forte, Srta. Gancho de esquerda.}
{396}{}{Posso ver seus músculos abdominais?}
{400}{}{Heard Mrs. Bishop was looking for you. Watch out, pal.}
{401}{}{Get me a job, pal? C'mon. I'm the king of studs.}
{402}{}{Love the films, }
{403}{}{Loved you in Great Balls for Hire.}
{404}{}{Loved you in Good Will Humping.}
{405}{}{I'm a big fan of your work in Pokeahotass.}
{406}{}{Loved "Vault Sex-Teen." It was inspired. A cinematic tour-de-force.}
{407}{}{Heard the Bishop daughter was looking for you. She's trouble.}
{408}{}{Got any openings at the studio?}
{409}{}{Loved "Vault Sex-Teen." It was inspired. A cinematic tour-de-force.}
{410}{}{I heard Tommy the Balls wants to give you a private screening.}
{411}{}{I loved your last film. Can I help you rehearse for the next one?}
{412}{}{Get me a job, and I'll show you some of my moves.}
{413}{}{When are you going to stop by and see me?}
{414}{}{Hey, you gonna dance here tonight?}
{415}{}{Looking deadly, sweetheart.}
{416}{}{Lady Luck gonna get jealous you keep coming around here.}
{420}{}{How are things up in the Den?}
{421}{}{That slaver brand hurt when you got it?}
{422}{}{I thought about becoming a slaver, but I hate all the traveling.}
{423}{}{You looking for the stables? That's where they keep most of the slaves.}
{424}{}{Being in the Bishop Family's a good gig.}
{425}{}{You bring a new crop of slaves in, or are you caravanning some out?}
{426}{}{You guys need to find some new stock... that last batch of slaves was piss-poor.}
{427}{}{You guys catch any more tribal slaves?}
{428}{}{What's the going rate for slaves nowadays?}
{429}{}{Slaves, brahmin, same thing.}
{440}{}{If you're looking for work, we could use someone like you. Talk to Mr. Bishop.}
{441}{}{You looking for work? You might want to talk to Mr. Bishop.}
{445}{}{Piss off, tribal.}
{446}{}{I ain't got no drugs for you, tribal.}
{447}{}{Go smoke your peace pipe, tribal.}
{448}{}{I DON'T feel like chatting. Beat it.}
{449}{}{Scram, tribal.}
{450}{}{You know who I am? I'm one of Bishop's men. Now fuck off.}
{451}{}{You looking to get me mad? You won't like me when I'm mad.}
{452}{}{Piss off before I use you for target practice.}
{453}{}{Looking for trouble? Keep talking to me, see what happens.}
{460}{}{I ain't looking for no tribal ass right now. Come back later.}
{461}{}{I ain't got time to do you right now, tribal. Why don't you come back later?}
{462}{}{No, I don't know where that is, now piss off! ::Stupid tribals.::}
{463}{}{Piss off, tribal.}
{464}{}{Bishops don't talk to tribal trash, we got better things to do.}
{465}{}{I ain't got no drugs for you, tribal.}
{466}{}{Go smoke your peace pipe, tribal.}
{467}{}{I DON'T feel like chatting. Beat it.}
{468}{}{Scram, tribal.}
{469}{}{You know who I am? I'm one of Bishop's men. Now fuck off.}
{470}{}{You looking to get me mad? You won't like me when I'm mad.}
{471}{}{Piss off before I use you for target practice.}
{472}{}{Looking for trouble? Keep talking to me, see what happens.}
{473}{}{I ain't beer-gogglin' that bad. Get lost.}
{474}{}{You got to be the ugliest tribal I've ever seen.}
{475}{}{Get out of here before I beat you uglier than you are.}
{476}{}{Go bark at someone drunker than me, bitch.}
{490}{}{I *thought* I smelled something rotting. Get that ghoul boy o' yours outta here.}
{491}{}{Tire esse ghoul fedorento daqui. Agora.}
{492}{}{Se esse ghoul não sair daqui em um minuto, vai ficar mais morto do que já está.}
{1200}{}{! Way to kick the Enclave's ass!}
{1210}{}{.}
{1215}{}{?}
{1216}{}{... why the secrecy?}
{1220}{}{, what's shaking?}
{1221}{}{, what you been up to?}
{1222}{}{! You been staying outta trouble?}
{1228}{}{ family is a bunch of pussies. What you think about that?}
{1229}{}{. Now.}
{1230}{}{. Ain't your family gonna be missing you?}
{1231}{}{ had time to do much more than kiss their bosses' ass.}
{1236}{}{ family is a bunch of pussies. Now I see it's true.}
{1252}{}{! You can't be showing weapons in here, awright?}
{1260}{}{. You taking care of yourself?}
{1261}{}{. What's up?}
{1266}{}{! You can't be showing weapons in here, awright?}
{1267}{}{! Put that weapon away.}
{1269}{}{! You can show your tits, but you can't show weapons in here, awright?}
{1280}{}{!}
{1350}{}{. What's going on?}
{1351}{}{. What's shaking?}
{1352}{}{. You been staying out of trouble?}
{1402}{}{!}
