{100}{}{Você vê um dos homens de Bishop.}
{150}{}{Você vê um homem de aparência robusta vestido com uma armadura de couro. Numerosas cicatrizes
 e ferimentos de bala cobrem o corpo dele.}
{151}{}{Você vê um dos homens de Bishop. Ele está examinando a área e dedilhando sua arma.}
{200}{}{Ei! }
{201}{}{::Felicidades::}
{202}{}{::palmas::}
{203}{}{::assobios::}
{205}{}{Como diabos você vai no banheiro com essa coisa?}
{210}{}{Bela arma, }
{215}{}{Ei, queria saber o que você faz se esgueirando, }
{216}{}{Uh, eai, }
{220}{}{Ei, }
{221}{}{Ei, }
{222}{}{Ei, }
{225}{}{Você acabou de entrar no lugar errado, idiota.}
{226}{}{Uau, olha que audácia desse filho da puta... sai fora, garoto, antes que você leve uns tiros.}
{227}{}{Esse cara tá procurando problemas...}
{228}{}{eu ouço o }
{229}{}{É melhor você ir embora, }
{230}{}{Ora ora, se não é }
{231}{}{Não acho que os membros da família }
{232}{}{Você acabou de entrar no lugar errado, vadia.}
{233}{}{Eita, olha à arrogância desta vadia...}
{234}{}{Some, garota. Antes que você leve uns tiros.}
{235}{}{Essa putinha está pedindo problemas...}
{236}{}{eu ouço o }
{250}{}{Ei, campeão. Sem armas aqui, ok?}
{251}{}{Ei, campeão! Largue essa arma.}
{252}{}{Ei, }
{255}{}{Por que você está se esgueirando?}
{256}{}{Você está se escondendo dos fãs?}
{257}{}{Uh, por que todo o sigilo?}
{260}{}{Ei, }
{261}{}{Ei, }
{265}{}{Ei, lindão. Sem armas aqui, ok?}
{266}{}{Ei, }
{267}{}{Ei, }
{268}{}{Querida, você não pode carregar armas aqui. Heh-heh... você já é mortífera o suficiente.}
{269}{}{Ei, }
{275}{}{Querida, com um corpo desse, você não poderá se esgueirar para lugar nenhum.}
{280}{}{Amei os filmes, }
{281}{}{Amei você em As Grandes Bolas de Fogo.}
{282}{}{Amei você em O Esfolador Indomável.}
{283}{}{Eu sou um grande fã do seu trabalho em Casa das Brasileirinhas.}
{284}{}{Adorei "Vault da putaria". Foi inspirador. Cinematografia de tour-de-force.}
{285}{}{::Assobios::}
{295}{}{Você está querendo encher uma tumba no Gólgota, traficante de escravos? Mantenha isso aí.}
{296}{}{Guarde essa arma, traficante de escravos, ou vou te usar de tiro ao alvo.}
{297}{}{Escravista, é melhor você guarda essa arma AGORA.}
{300}{}{Quer encher uma cova no Gólgota, traficante de escravos? Pare de se esgueirar.}
{301}{}{Pare de se esgueirar, traficante de escravos, ou vou te usar como tiro ao alvo.}
{302}{}{Talvez seja melhor você voltar para a Aldeia da Folha, traficante de escravos - agora pare de se esgueirar.}
{303}{}{Escravista, é melhor você parar com essa merda AGORA.}
{305}{}{Quer encher uma cova no Gólgota, tribal? Largue essa coisa.}
{306}{}{Guarde essa arma, tribal, ou te usarei como tiro ao alvo.}
{307}{}{Tribal, é melhor você guardar essa arma AGORA.}
{310}{}{Quer encher uma cova no Gólgota, tribal? Pare de se esgueirar.}
{311}{}{Pare de se esgueirar, tribal, ou te usarei como tiro ao alvo.}
{312}{}{Talvez seja melhor você voltar a Aldeia da Folha, tribal - agora pare de se esgueirar.}
{313}{}{Tribal, é melhor você parar com essa merda AGORA.}
{315}{}{Tire esse robô daqui. Agora.}
{316}{}{Tire esse robô daqui antes que ele vire alguma lata de lixo.}
{317}{}{Aquele robô vai virar peças de reposição se ficar aqui.}
{320}{}{Eu *pensei* ter cheirado um mutante. É melhor tirar a bunda amarela dele daqui.}
{321}{}{Você e seu amigo mutante querem levar um tiro? Vaza.}
{322}{}{É melhor esse mutante sair daqui agora, ou vamos pregar a cabeça dele na parede.}
{325}{}{Viu a luta de ontem a noite?}
{326}{}{Vou ir na Garra do Gato depois do trabalho.}
{330}{}{Eu pensei que o presidente era um mito, um bicho-papão usado para assustar as crianças}
{331}{}{Parece que você voltou do inferno. Relaxe um pouco. Você merece.}
{332}{}{Eles iam despejar um novo vírus no ar? Desgraçados. Espero que você tenha alvejado alguns deles por mim.}
{333}{}{Você pode querer repetir o jogo com um personagem diferente.}
{334}{}{Você deve ser um cara durão para explodir o Enclave como fez.}
{335}{}{Apenas vagando depois de zerar, pegando alguns XPs, né não? Bem, só não me mate,
 ok?}
{336}{}{New Reno foi desenhado por Chris Avellone e roteirizado por Tom French. Fiquei sabendo que
 vai ter casório em breve.}
{337}{}{Queria ser um personagem importante em Fallout 3, como Tandi ou Ian. Vai se fuder, Bethesda.}
{338}{}{Sim, eu marquei com Tandi uma vez. Quando ela era jovem, claro.}
{339}{}{Aquela garota Lynette está precisando muito de um pouco de amor, sabe?}
{340}{}{Ouvi dizer que você destruiu aquela Enclave no sul. Aí tem coragem.}
{350}{}{Ei, }
{351}{}{Ei, }
{352}{}{Ei, }
{353}{}{Ouvi dizer que Tommy the Balls está de volta à cidade, verificando as coisas. Cuidado com ele.}
{354}{}{Você vê Tommy the Balls, fique fora do caminho dele.}
{355}{}{Falou bem de mim para Bishop?}
{356}{}{Que sorte. Eu gostaria de poder me dar bem com o chefe.}
{357}{}{Alguma dica para um cara como eu?}
{358}{}{A Família Bishop tem sido boa para mim.}
{359}{}{John Bishop vai governar esta cidade.}
{360}{}{Está tudo de boa hoje.}
{361}{}{A tempestade está chegando.}
{362}{}{O fedor da Gólgota estava horrível ontem à noite.}
{363}{}{When we gonna whack one of the other families?}
{364}{}{With you on our side, those other families don't stand a chance, boss.}
{365}{}{Get you anything, boss?}
{366}{}{Any word on the other families?}
{367}{}{Um, got any Jet?}
{368}{}{Com certeza eu gostaria de um copo...}
{369}{}{Mrs. Bishop was checking me out again. It makes me uncomfortable.}
{370}{}{Mrs. Bishop keeps looking at me like a slab of beef. I wish she'd realize that I just
 want to be held.}
{371}{}{That Bishop girl is one nice piece of ass.}
{372}{}{That Bishop girl is trouble.}
{373}{}{I heard one of the boys got the Bishop daughter drunk, and Mr. Bishop skinned him.}
{374}{}{If you talk to Bishop, stay away from the wife and daughter... nothing but trouble.}
{380}{}{Heard Mrs. Bishop was looking for you. Watch out, pal.}
{381}{}{Heard the Bishop daughter was looking for you. She's trouble.}
{382}{}{Você não parece tão forte, Sr. Prizefighter.}
{383}{}{You know, Family Bishop could really use someone like you. Tough. Uncompromising.}
{384}{}{You should talk to Bishop about a job.}
{385}{}{You might want to consider joining up with us. We're gonna rule New Reno.}
{386}{}{I got $20 riding on you!}
{387}{}{Ei, campeão! Aquela última luta foi ótima!}
{388}{}{Vi você lutando no ringue. Que belo gancho que você deu.}
{389}{}{You gonna take the fall? I got $30 riding on you.}
{390}{}{Quanto você pesa?}
{391}{}{Onde você trabalha fora do ringue?}
{392}{}{Cuidado com o Masticator. Ele é louco por orelhas.}
{393}{}{Eu te pagaria uma bebida se não tivesse perdido todo meu dinheiro apostando no seu oponente.}
{394}{}{Quer lutar?}
{395}{}{Você não parece ser tão forte, Srta. Gancho de esquerda.}
{396}{}{Posso ver seus músculos abdominais?}
{400}{}{Heard Mrs. Bishop was looking for you. Watch out, pal.}
{401}{}{Get me a job, pal? C'mon. I'm the king of studs.}
{402}{}{Amei os filmes, }
{403}{}{Amei você em As Grandes Bolas de Fogo.}
{404}{}{Amei você em O Esfolador Indomável.}
{405}{}{Eu sou um grande fã do seu trabalho em Casa das Brasileirinhas.}
{406}{}{Loved "Vault Sex-Teen." It was inspired. A cinematic tour-de-force.}
{407}{}{Heard the Bishop daughter was looking for you. She's trouble.}
{408}{}{Got any openings at the studio?}
{409}{}{Loved "Vault Sex-Teen." It was inspired. A cinematic tour-de-force.}
{410}{}{I heard Tommy the Balls wants to give you a private screening.}
{411}{}{I loved your last film. Can I help you rehearse for the next one?}
{412}{}{Get me a job, and I'll show you some of my moves.}
{413}{}{When are you going to stop by and see me?}
{414}{}{Hey, you gonna dance here tonight?}
{415}{}{Looking deadly, sweetheart.}
{416}{}{Lady Luck gonna get jealous you keep coming around here.}
{420}{}{How are things up in the Den?}
{421}{}{That slaver brand hurt when you got it?}
{422}{}{I thought about becoming a slaver, but I hate all the traveling.}
{423}{}{You looking for the stables? That's where they keep most of the slaves.}
{424}{}{Being in the Bishop Family's a good gig.}
{425}{}{You bring a new crop of slaves in, or are you caravanning some out?}
{426}{}{You guys need to find some new stock... that last batch of slaves was piss-poor.}
{427}{}{You guys catch any more tribal slaves?}
{428}{}{What's the going rate for slaves nowadays?}
{429}{}{Slaves, brahmin, same thing.}
{440}{}{If you're looking for work, we could use someone like you. Talk to Mr. Bishop.}
{441}{}{You looking for work? You might want to talk to Mr. Bishop.}
{445}{}{Piss off, tribal.}
{446}{}{I ain't got no drugs for you, tribal.}
{447}{}{Go smoke your peace pipe, tribal.}
{448}{}{I DON'T feel like chatting. Beat it.}
{449}{}{Scram, tribal.}
{450}{}{You know who I am? I'm one of Bishop's men. Now fuck off.}
{451}{}{You looking to get me mad? You won't like me when I'm mad.}
{452}{}{Piss off before I use you for target practice.}
{453}{}{Looking for trouble? Keep talking to me, see what happens.}
{460}{}{I ain't looking for no tribal ass right now. Come back later.}
{461}{}{I ain't got time to do you right now, tribal. Why don't you come back later?}
{462}{}{No, I don't know where that is, now piss off! ::Stupid tribals.::}
{463}{}{Piss off, tribal.}
{464}{}{Bishops don't talk to tribal trash, we got better things to do.}
{465}{}{I ain't got no drugs for you, tribal.}
{466}{}{Go smoke your peace pipe, tribal.}
{467}{}{I DON'T feel like chatting. Beat it.}
{468}{}{Scram, tribal.}
{469}{}{You know who I am? I'm one of Bishop's men. Now fuck off.}
{470}{}{You looking to get me mad? You won't like me when I'm mad.}
{471}{}{Piss off before I use you for target practice.}
{472}{}{Looking for trouble? Keep talking to me, see what happens.}
{473}{}{I ain't beer-gogglin' that bad. Get lost.}
{474}{}{You got to be the ugliest tribal I've ever seen.}
{475}{}{Get out of here before I beat you uglier than you are.}
{476}{}{Go bark at someone drunker than me, bitch.}
{490}{}{I *thought* I smelled something rotting. Get that ghoul boy o' yours outta here.}
{491}{}{Tire esse ghoul fedorento daqui. Agora.}
{492}{}{Se esse ghoul não sair daqui em um minuto, vai ficar mais morto do que já está.}
{1200}{}{! Way to kick the Enclave's ass!}
{1210}{}{.}
{1215}{}{?}
{1216}{}{... why the secrecy?}
{1220}{}{, what's shaking?}
{1221}{}{, what you been up to?}
{1222}{}{! You been staying outta trouble?}
{1228}{}{ família é um bando de boiolas. O que você pensa sobre isso?}
{1229}{}{. Agora.}
{1230}{}{. Sua família não vai sentir sua falta?}
{1231}{}{ Ele não tinha tempo para fazer muito mais do lamber as bolas de seus chefes.}
{1236}{}{ família é um bando de boiolas. Agora vejo que é verdade.}
{1252}{}{! Você não pode ter armas à vista aqui, certo?}
{1260}{}{. Você está se cuidando?}
{1261}{}{. E aí?}
{1266}{}{! Você não pode ter armas à vista aqui, certo?}
{1267}{}{! Guarde essa arma.}
{1269}{}{! Você pode mostrar seus peitos, mas não pode mostrar armas aqui, certo?}
{1280}{}{!}
{1350}{}{. What's going on?}
{1351}{}{. What's shaking?}
{1352}{}{. You been staying out of trouble?}
{1402}{}{!}
