{100}{}{Você vê Bill.}
{150}{}{Você vê um homem velho com sobrancelhas brancas e espessas. Parece que ele precisa de uma bebida.}
{200}{}{::Tosse::}
{201}{}{::Olha para o barman::}
{202}{}{::Gestos para pedir outra bebida::}
{203}{}{::Olhar hostil::}
{210}{}{Desapareça, idiota.}
{220}{}{(O homem nem te olha quando você se aproxima dele. Ele está olhando para a parede atrás do bar.)}
{221}{}{Uh, ei, ouviu algum rumor ultimamente?}
{222}{}{Ei, o que você acha desses novos óculos que estou usando?}
{223}{}{Ei, você já matou alguém?}
{224}{}{(O deixa em paz.)}
{230}{}{Que tipo de pergunta idiota é essa?}
{231}{}{Ei, calma lá. Eu só estava curioso.}
{232}{}{Ok, bem, não importa então.}
{240}{}{Se cuida.}
{241}{}{Não antes de eu acabar com você.}
{250}{}{(O homem volta seu olhar para você.) Você parece um idiota.}
{251}{}{Ei, calma lá. Só estava pedindo sua opinião.}
{252}{}{Uh... Obrigado pela honestidade, Então.}
{260}{}{(Gestos para você ficar na sua e deixá-lo beber.)}
{261}{}{(O deixa em paz.)}
