{150}{}{You see a sunburned young man dressed in black leather and chains. His face is pock-marked
 with acne scars.}
{151}{}{You see Lil' Jesus Mordino.}
{152}{}{You see Lil' Jesus Mordino. He is dressed mostly in black leather and playing with one of his knives.}
{200}{}{E ae! }
{201}{}{Do caralho, }
{202}{}{::Faz o sinal de positivo pra você::}
{203}{}{::Assobios::}
{220}{}{Como você mija com um coisa dessas?}
{230}{}{Bela arma, }
{240}{}{Pra quê está se escondendo, hein, }
{250}{}{Wazzup, }
{251}{}{Heeey... }
{252}{}{Meeer-da, está quente.}
{253}{}{Heeey! Whacha been up to, }
{254}{}{Good to see you, }
{255}{}{Hey! Come and check out my new knife, }
{256}{}{What shit Dad got you doing now, }
{257}{}{We goin' out tonight, }
{258}{}{My knife needs some Bishop blood...}
{259}{}{Gonna carve up so many Salvatores they'll call me the "butcher"...}
{270}{}{Ei! Cabrón! Estás procurando pelo anjo da morte? Cai fora!}
{271}{}{You got some cojones coming in here, }
{272}{}{Hijo de una puta…}
{273}{}{You }
{274}{}{If you're still here when I finish my drink, I'm gonna carve my name on your face.}
{275}{}{::Starts playing with his knife threateningly.::}
{276}{}{Lookin for your hermana, }
{277}{}{Mas que po... Você! Você, o que está fazendo aqui?}
{278}{}{Ei! Puta! Estás procurando pelo anjo da morte? Cai fora!}
{279}{}{Thought they kept you locked up in the kennel, puta.}
{280}{}{If you ain't here to kiss my ass, }
{281}{}{Hija de una puta…}
{300}{}{Yo! Hombre, you can't be carrying that around in here.}
{301}{}{Ei! Amigo, guarde essa coisa antes que as pessoas comecem a ficar nervosas.}
{310}{}{Ei! Chica, você não pode andar aqui carregando essa coisa.}
{311}{}{Ei! Chica, guarde essa coisa antes que as pessoas comecem a ficar nervosas.}
{320}{}{Por que diabos você está se escondendo, }
{330}{}{Por que se esconde, chica? Com esse gancho direito que tem, deveria andar com orgulho.}
{340}{}{Onde você aprendeu a lutar, }
{341}{}{Você tem os cojones de um Mordino.}
{342}{}{A última luta foi épica, hombre.}
{343}{}{Voa como uma borboleta, pica como uma abelha. Esse é você, }
{344}{}{'Cê sabe, os Mordinos fariam bom uso de seus músculos, }
{345}{}{Bet on you, best money I ever placed. You were throwing hooks like nobody's business.}
{346}{}{Vi você lutar no ringue.}
{347}{}{Quanto você tem de envergadura, }
{348}{}{Qual foi sua estratégia, hein?}
{349}{}{Cuidado com o Masticator. Ele gosta de comer orelhas.}
{350}{}{Eu te pagaria uma bebida se não tivesse perdido todo meu dinheiro apostando no seu oponente.}
{351}{}{De onde você é, pra lutar assim? Você é bom. Digo, BOM.}
{352}{}{Onde aprendeu a lutar assim, chica? Você é violenta.}
{353}{}{Last fight was something out of a fucking epic, chica.}
{354}{}{Qual foi sua estratégia, hein? Precisa de um ajudante?}
{370}{}{Hey, hey, hey! Chica, you need to me to put that weapon away for you?}
{371}{}{O quê, você quer eu te reviste toda? Vamos lá, abaixe esse ferro antes que eu fique bravo.}
{390}{}{No way you're sneaking by Lil' Jesus with a bod like that, chica.}
{400}{}{Your film wasn't bad, but you obviously need a few pointers from me. ::Laughs::}
{401}{}{Ei, }
{402}{}{Estou pronto, preparado, coloque-me num filme, certo? Falamos no escritório, }
{403}{}{Eu sou o maior amante Latino. Não há amante Latino como eu.}
{404}{}{Fale de mim para os Brothers, }
{405}{}{Give a good word to the brothers for me, alright?}
{406}{}{Você está fazendo a coisa certa, lidando com os Mordinos.}
{407}{}{Need some drugs? Hootch? Some chips? I can set you up. I'm co-nnected, see?}
{408}{}{E então, que tal um filme nosso? Eu te trato bem, chica. Eu te mostro o que um amante Latino sabe fazer.}
{409}{}{Por que não passa aqui depois do trabalho?}
{410}{}{Você tem amigos?}
{411}{}{Precisa de Jet? Eu posso te arrumar, chica.}
{412}{}{Chica, não há nada que eu não faria por você... vamos lá, me dê um beijinho.}
{425}{}{Não ande com ferro por aqui, chapa. Guarde isso.}
{435}{}{Não fique se escondendo por aí, escravagista. Você está entre amigos.}
{445}{}{Ei! És burro ou o quê? Guarde essa coisa antes que yo tenha que te machucar.}
{446}{}{Estás procurando um caixão? Guarde essa coisa.}
{447}{}{Ei, chica! És burra ou o quê? Guarde essa coisa antes que yo tenha que te machucar.}
{455}{}{Por que diabos está se escondendo? Que levar um tiro?}
{460}{}{Por que está se escondendo, chica? Que levar um tiro?}
{465}{}{Tire essa lixeira rolante daqui.}
{466}{}{Robôs não são permitidos aqui. Caia fora.}
{467}{}{Esse robô vai virar sucata se ficar aqui.}
{475}{}{YO ACHO que senti cheiro de mutante. Tire ele daqui antes que fiquemos bravos.}
{476}{}{Gostas de mutantes? O lugar dele é LÁ FORA. Ou então...}
{477}{}{That mutant sticks around, he's gonna become target practice.}
{485}{}{YO ACHO que senti cheiro de carniça. Tire esse ghoul daqui.}
{486}{}{Tire esse ghoul fedorento daqui. Agora.}
{487}{}{Se esse ghoul não sair daqui em um minuto, vai ficar mais morto do que já está.}
{495}{}{Hey, you. C'mon over here and let me see that knife.}
{496}{}{Nice knife.}
{497}{}{Can I see that knife for a second?}
{505}{}{Hunh? }
{506}{}{Something you want, amigo?}
{507}{}{Something you want, chica?}
{508}{}{Hoo ooh?}
{511}{}{Cai fora}
{512}{}{Quem é você?}
{513}{}{Desculpe. Achei que você fosse outra pessoa.}
{522}{}{Eh...? You again? What do you want now?}
{523}{}{Heeeey... whatzzup, friend? Something on your mind?}
{524}{}{Me from under where}
{525}{}{Ay-me-go?}
{526}{}{Cheee-ka Cheeek-aaaah}
{529}{}{Eu tenho algumas perguntas…}
{530}{}{Deixa pra lá. Desculpe incomodá-lo.}
{540}{}{}
{541}{}{}
{542}{}{Hey, hey, hey! You're }
{544}{}{Fire it up fire it up}
{547}{}{Obrigado, pequeno Jesus. Ei, eu tenho algumas perguntas para você...}
{548}{}{Thanks for the compliment. I was just stopping by; I have to be going.}
{549}{}{Yeah, I don't need you to tell me that. Just watch yourself.}
{560}{}{Heeeey! How's it going, }
{562}{}{You being helped, or do I got to call over one of the putas ta get you set up? Ha!}
{563}{}{You being helped, or do I got to call over one of the waitresses ta get you set up? Ha!}
{567}{}{Não, eu tudo certo. Olhe, eu tenho algumas perguntas para você, Jesus...}
{568}{}{No, I'm good, thanks. Catch you later.}
{582}{}{Eh? You looking to deal, slaver? Got some stock you wanna unload?}
{583}{}{Me unload! Me unload!}
{586}{}{Sure. Are you the one to talk to?}
{587}{}{Agora não. Mas eu tenho algumas perguntas para você...}
{588}{}{Not right now. Maybe later.}
{600}{}{Heh. You been out squatting in the sun too long. Get.}
{601}{}{Eh... right. You take care, amigo. I'll catch you later.}
{602}{}{Eh... right. You take care, chica. I'll catch you later.}
{603}{}{Heh. Maybe you oughta go back out and squat in the sun, tribal. Clear the air in here.}
{604}{}{Okeee Doh-kee}
{620}{}{Cai fora daqui.}
{621}{}{Come around here again, and I'll fill you so full o' lead even Superman couldn't see through you.}
{622}{}{::Plays with knife threateningly::}
{623}{}{::Cospe no seu pé.::}
{624}{}{You look like someone who don't know when they're about to die.}
{625}{}{Beat it 'fore I waste you.}
{626}{}{Come around here again, and I'll gut you.}
{640}{}{(Picks fingernails with knife.) Questions... EVERYBODY got questions...}
{641}{}{(Picks his teeth with a dirty fingernail.) Yeah?}
{642}{}{Something on your mind?}
{643}{}{What was that you were saying about the Mordino Family again?}
{644}{}{Estou à procura de trabalho.}
{645}{}{What is there to do around New Reno to relax?}
{646}{}{You know anything about Richard Wright overdosing on Jet?}
{647}{}{Can you teach me knife fighting?}
{648}{}{Nevermind. Catch you later.}
{660}{}{Me? If you gotta ask... heh. Name's Jesus. Jesus Mordino. Same as my Dad, he's the BIG Jesus, head of the WHOLE Mordino family
 here in Reno. So most call me Lil' Jesus. Prevents confusion, y'know?}
{661}{}{Family Mordino? Who are they?}
{662}{}{I've heard about your family. I hear you guys are a force to be reckoned with.}
{663}{}{I'm looking for a job. Is Family Mordino hiring?}
{665}{}{Know what there is to do around New Reno to relax?}
{666}{}{Certo. Olha, eu tenho algumas perguntas...}
{680}{}{We Mordinos are gonna run New Reno... and Redding, too. You'll see.}
{681}{}{Family MORDINO? You been taking too much Jet, homes? We Mordinos run New Reno... and Redding, too.}
{682}{}{Family MORDINO? You been taking too much Jet, chica? We Mordinos run New Reno... and Redding, too.}
{683}{}{Sounds like the Mordino family is the one to hook up with... can you set me up?}
{684}{}{What do you mean about Redding?}
{685}{}{Redding? Where's that?}
{686}{}{Sounds like the Mordinos have a bright future. Say, I had some questions...}
{687}{}{You Mordinos talk big, but got small cojones. What you got to say about that, LITTLE Jesus?}
{700}{}{To the northwest, homes. }
{701}{}{To the northwest, chica. }
{702}{}{If you ain't been there, you ain't missing nothing. Bunch of no-neck miners who like to FLY, know what I'm saying?}
{703}{}{Not really. What do you mean?}
{704}{}{They're a bunch of drug addicts?}
{705}{}{Te ouço. Eu tenho algumas perguntas...}
{706}{}{I have to go. Later, Jesus.}
{720}{}{Bunch of no-neck miners, dig in the dirt, but they like to FLY, know what I'm saying?}
{740}{}{Them no-necks dig for gold, see, but what WE give them is better than gold, know what I'm saying? They give us ALL
 the gold they dig up just for a LEETLE Jet. Everybody happy.}
{742}{}{Parece que sim. Olha, eu tinha algumas perguntas...}
{760}{}{Well, when they got their first taste o' Jet, they were. You can't have just one.}
{761}{}{Where does the Jet come from?}
{762}{}{Eu ouço. Olha, eu tenho outras perguntas ..}
{780}{}{The Jet? It comes from HERE. See, we don't dig for gold, we MAKE it: liquid gold. Jet. Worth a fortune to the miners, costs
 next to nothing to make. We ship it to Redding, they shoot up, they fly, they ship us gold. That simple.}
{781}{}{How long has this been going on? It seems like you would have controlled all of Northern California by now if Jet was that
 addictive.}
{800}{}{You're right about that... see, we didn't always HAVE Jet. But we stumbled across this kid - he took a look at the shitty
 drugs we was selling and said he could do 'better.' And he did. Now he works for us. That simple.}
{801}{}{Who is this kid and where is he?}
{820}{}{Kid's name's Myron. As for where he IS, that's somethin' you don't need to know.}
{821}{}{Kid's name's Myron. We got him set up in the stables, north of town, testing new drugs. You could go over and see him if
 you want, but he's busy most of the time... either with the drugs or the women.}
{822}{}{Why don't you get smart and tell me anyway?}
{823}{}{Eu consegui. Eu tenho mais perguntas...}
{824}{}{Myron, huh? All right then, Jesus. Thanks for the conversation.}
{840}{}{The Desperado is the place to be, homes. We got the Jet, the games, the action... and we got all the putas you need
 right outside, wet and willing. Paradise, homes. Pair-a-dice.}
{841}{}{The Desperado is the place to be, chica. We got the Jet, the games, and the action. You
 ain't need to go nowhere else.}
{842}{}{So... you wanna re-lax, chica? Heh... then how 'bout you and me get down to some sweet love?}
{843}{}{Tempting, but I haven't got ten seconds for your sweet love right now, Little Jesus.}
{844}{}{Agradeço muito, mas não obrigado. Olha, eu tenho algumas perguntas.}
{846}{}{I'm looking for a job. Know of any place that's hiring?}
{847}{}{Thanks for the tip, thanks.}
{848}{}{Why don't you start without me? I have to go.}
{860}{}{Eh? What are you talkin ab --? (Gets it.) You fucking PUTA! You better get yo tramp ass outta here 'fore I carve you
 into so many pieces your own mother won't recognize you.}
{861}{}{Eh? What are you talkin ab --? (Gets it.) You better get your ass out here, homes, 'fore I take my knife and give
 you a second smile on that neck of yours.}
{862}{}{Try it and see what happens, LITTLE Jesus.}
{863}{}{Try it, and I'll add so many scars to your face you'll look like a jigsaw puzzle.}
{864}{}{Tranquilo... Eu só estava zuando.}
{865}{}{Frio. Eu tenha outras perguntas...}
{867}{}{I'm leaving. Great talking to someone as cultured as you.}
{880}{}{Ha! You all right, chica. You all right. Lil' Jesus gonna be keeping an eye on you... not that I couldn't help myself. What
 can I do for you?}
{881}{}{First thing you can do for me is keep your eyes to yourself, LITTLE Jesus. I'd sooner consider humping a rock before
 touching that cratered landscape you call a face.}
{882}{}{I'm looking for a job. Know of anyone who's hiring?}
{883}{}{Eu tenho mais algumas perguntas...}
{884}{}{Actually, I have to be going. Good talking to you, Jesus.}
{890}{}{(Checks you over, nods.) We're always looking for new blood...'specially new blood that's willing to spill blood, know what I'm saying? Go upstairs, talk to my Pa, tell him I sent you, and maybe we can do business.}
{891}{}{(Checks you over, shakes head.) We don't hire chicas...'cept in certain positions. Try Pa upstairs, tell him I sent you.
 Maybe you can do some business.}
{892}{}{Talvez sim. Olha, eu tenho outras perguntas...}
{893}{}{I'll go see him then. Later, Jesus.}
{900}{}{I don't know. You don't look too strong to me... maybe you should try somewhere else, homes.}
{901}{}{Naw... my mind's a blank. Our family ain't hiring, and the other families sooner'd kill you than listen to you. You
 outta luck, homes.}
{902}{}{Naw... I don't know of no place hiring. You might try and find a pimp, MAYBE earn some cash charging rent on yer
 ass, y'know?}
{903}{}{WE ain't hiring, but with a bod like that, you might try the Corsican Bros Studio up the street. (Grins.) But if you're looking
 for some quick chips, my room's upstairs...}
{904}{}{All right then. I had some other questions...}
{905}{}{Eh, eu passo. Tenho algumas perguntas...}
{906}{}{Prefiro que não, valeu. Eu tenho algumas perguntas para você, no entanto...}
{907}{}{Oh, I bet it WOULD be quick. No thanks.}
{908}{}{Nevermind then. Thanks anyway.}
{909}{}{No thanks. I better be going.}
{920}{}{Oh, so that makes it all better then, huh? (Spits at your feet.) Get the hell outta here 'fore I carve you.}
{921}{}{Just try it and see what happens... LITTLE Jesus.}
{922}{}{Calma, Jesus... Olha, eu tenho outras perguntas...}
{923}{}{Estou de saída.}
{924}{}{You spit on my shoe? You fuck! I'm gonna teach you a lesson about respect, mother fucker.}
{930}{}{No, not me... head on upstairs and see my Pa. He's the one you want to talk to.}
{931}{}{E você é...?}
{932}{}{Tudo bem então. Antes de ir, eu tinha algumas perguntas...}
{933}{}{Obrigado.}
{940}{}{FUCK you. Get outta my family's casino 'fore I carve my initials on your dead body.}
{942}{}{Don't you threaten me, Jesus.}
{943}{}{Calma lá - Eu tenho algumas perguntas...}
{944}{}{Calm down, Jesus. I'm leaving.}
{950}{}{That little piss-ass Wright kid? Ha! You trying to pin that shit on me? You outta luck; I ain't sorry the little
 fucker's dead, but I didn't have NOTHIN' to do with it.}
{951}{}{Oh, yeah? Well, the Mordinos are the biggest suppliers of Jet in New Reno. That makes you the first ones who are
 gonna take the blame.}
{952}{}{I don't believe you. I think you ARE the one responsible. You and the rest of the Mordinos.}
{953}{}{Quem você acha que pode ter feito isso?}
{954}{}{Ok... Olha, eu tenho outras perguntas...}
{955}{}{All right then. Just asking.}
{965}{}{(Eyes narrow.) Look now, I ain't had NOTHING to do with that kid's death. I don't know what you heard, but if I'd killed
 that kid, I woulda carved him up, not made him crash and burn on Jet, see?}
{966}{}{Yeah, so what if we take the blame? Don't mean we DID it. Little shit took too much. I ain't sorry he's dead. And
 if ol' man Wright starts throwing down, we'll bury him right next to his junkie kid.}
{967}{}{You're a real humanitarian, Jesus.}
{968}{}{That's a GREAT attitude, Jesus.}
{969}{}{You know who sold Richard the Jet that killed him?}
{970}{}{Bem, isso com certeza esclarece as coisas para mim. Eu tinha algumas outras perguntas...}
{971}{}{Thanks for the information, Jesus. You've been very helpful.}
{980}{}{Yeah, Renesco... the "Rocketman." Sells so much Jet, he could shoot you to the moon. He's on the west side, in Salvatore
 territory. He don't like the Wrights none, and his drugs ain't PURE, know what I'm saying?}
{981}{}{He can't be the only dealer in a town this size.}
{982}{}{Lado oeste, hein? Eu posso passar por lá. Eu tenho outras perguntas, no entanto...}
{983}{}{All right. I'll check it out. Thanks, Jesus.}
{990}{}{No, there's others, but Renesco's the one who done it.}
{991}{}{What makes you say that?}
{992}{}{Who are the other dealers?}
{993}{}{Sim, você já disse isso. Olha, eu tinha outras perguntas ..}
{994}{}{All right, Jesus. Thanks for the info.}
{1000}{}{CAUSE he's a half-blind cracker with a mean streak a mile wide that sells BAD SHIT, that's fucking why. You go see him,
 you see what he says about the Wright kid, and THEN you'll see I'm right.}
{1001}{}{What other dealers are there?}
{1002}{}{Eu faço isso. Olha, eu tenho outras perguntas ...}
{1003}{}{All right then, Jesus. I'll go check this Renesco out.}
{1010}{}{There's Jules, front of town, peddles mostly to newcomers... n' Jagged Jimmy J, up on 2nd street by the gym... can't
 miss that punk-ass cause he cut his face up one night while on Jet... it's so bad his entire face is all scars.}
{1011}{}{I hear you deal drugs, too, Jesus. How come YOUR name wasn't on that list?}
{1012}{}{What makes you think Renesco's responsible?}
{1013}{}{Interessante. Eu tinha outras perguntas...}
{1014}{}{Renesco, Jules and Jagged Jimmy J. Got it. Thanks for the information.}
{1020}{}{CAUSE, mother fucker, I AIN'T a dealer. }
{1021}{}{CAUSE I AIN'T a dealer, BITCH. }
{1022}{}{I may sell Jet sometimes, but I'm Lil' Jesus MORDINO, not some two-bit Jet-pushing punk that's got to addict ten
 customers a day just to make enough to eat. So FUCK you.}
{1023}{}{You better watch your mouth with me, Jesus.}
{1024}{}{Sussa, eu só estava curioso... Olha, eu tenho outras perguntas...}
{1025}{}{All right then. Thanks for the information.}
{1030}{}{(Lil' Jesus glances at the knife in your hand, shakes his head.) }
{1031}{}{(The man glances at the knife in your hand, shakes his head.) }
{1032}{}{*Tchhhh.* Don't you know how to HOLD a knife, homes? }
{1033}{}{*Tchhhh.* Don't you know how to HOLD a knife, chica? }
{1034}{}{Here, like this... (Adjusts your grip.) You need some instruction.}
{1035}{}{(Look at knife. Look at ugly man. Look at knife.) You touch }
{1036}{}{Kagagoogoo}
{1038}{}{Really? Can you teach me?}
{1040}{}{Na verdade, eu tenho algumas perguntas para você, Jesus...}
{1041}{}{Maybe some other time, thanks.}
{1050}{}{Hmmmmm...}
{1051}{}{I don't know, homes... I mean, I ain't got a lot of free time and knife fighting's an ART, y'know?}
{1052}{}{I don't know, chica... I mean, I ain't got a lot of free time and knife fighting's an ART, y'know?}
{1053}{}{I don't know, chica... I mean, I MIGHT be willing to make an exception for a woman such as yourself, but I ain't
 got a lot of free time... and knife fighting's an ART, y'know?}
{1054}{}{I'll give you a hundred chips.}
{1055}{}{I'll give you two hundred chips.}
{1056}{}{My lovemaking's an art, too. Wanna swap styles?}
{1058}{}{Na verdade, eu tinha algumas perguntas...}
{1059}{}{Some other time then... when I have enough chips to change your mind.}
{1060}{}{Maybe some other time then, thanks.}
{1070}{}{Hmmmmm. 200 and it's a deal.}
{1071}{}{Naw... I was thinking about something ELSE, y'know? (His eyes drift down your body, licks his chapped lips.)}
{1072}{}{Tell me you mean 200 chips. PLEASE tell me you mean 200 chips.}
{1073}{}{Oh, you were thinking of sex? Well, keep thinking, cause it ain't gonna happen.}
{1074}{}{Uh, okay. Let's do it. Anything for some added knife skill.}
{1075}{}{Tudo bem. Aqui está o dinheiro.}
{1076}{}{Nevermind. Uh, who are you, anyway?}
{1077}{}{Forget it. I had some other questions...}
{1079}{}{Maybe some other time, thanks. I REALLY have to be going.}
{1090}{}{Hmmmm... all right, yeah, I'll do it. You look like you might have the cojones for it. Look, now, the first thing you
 gotta do is...}
{1091}{}{Hmmmm... all right, yeah, I'll do it. You look like you might have the cojones for it... no offense. Look, now, the first
 thing you gotta do is...}
{1092}{}{(Smiles, displaying the rotted remains of his teeth.) All right, yeah, I'll do it. You got some time right NOW, chica?
 Then let's get down to business...}
{1093}{}{Tudo bem...}
{1643}{}{Who is this Mordino Family you were talking about?}
{2000}{}{Lil' Jesus shows you some vicious knife fighting tricks. You have become more skilled with knives.}
{2001}{}{At the cost of your dignity, you have become more skilled with knives. You also desperately want a shower.}
{5200}{}{! Way to kick the Enclave's ass!}
{5201}{}{, way to teach them dumb Enclave fucks how things are done DOWNTOWN.}
{5230}{}{.}
{5240}{}{? Os Mordinos andam de cabeça erguida.}
{5250}{}{?}
{5251}{}{! Que passa?}
{5253}{}{?}
{5254}{}{. Onde você esteve?}
{5255}{}{.}
{5256}{}{?}
{5257}{}{. You comin' wit us?}
{5271}{}{. Lose 'em and walk, or else.}
{5273}{}{s fuck with us, you'll be wormfood. Get outta here!}
{5276}{}{? She just got done kissing my ass. Now you better blow, too.}
{5280}{}{, you better leave.}
{5320}{}{? Com esse gancho direito que tem você deveria andar com a cabeça erguida.}
{5340}{}{? You're vicious. You got the MOVES, hombre.}
{5343}{}{.}
{5344}{}{. Se as outras famílias te virem, vão te enterrar em segundos.}
{5346}{}{. You were *wasting* that guy.}
{5347}{}{?}
{5380}{}{? Vamos, ajeita essa postura.}
{5401}{}{! Que passa? Você vai fala de mim pros Brothers ou não?}
{5402}{}{, bilheteria!}
{5404}{}{...c'mon. I can *do* it.}
{5542}{}{! The big ol' fighter! Man, you're good!}
{5543}{}{! The nasty chica fighter! You're good, chica!}
{5560}{}{? }
{6035}{}{'s hand No TOUCH }
{7035}{}{'s hand }
{8035}{}{ NO LIKE}
