{100}{}{Você vê... Sheb.}
{150}{}{You see a scrawny man in bright blue clothes. As if his clothes weren't loud enough, he is also bellowing at the top of his lungs.}
{200}{}{Bumbum, bumbum, buum-bum!}
{201}{}{Entrem, amantes do saque!}
{202}{}{Aqui na Garra da Gata estamos cortando os preços pela metade!}
{203}{}{Dê sua oferta em nossa principal seleção de espólio! É um estouro de espólios!}
{204}{}{We got white booty, black booty, southern booty, northern booty...}
{205}{}{We got hot booty, cold booty, we got fresh booty, we got...::snfff::...*smelly* booty...}
{206}{}{We got tribal booty, we got mutant booty, radscorpion booty, robot booty.}
{207}{}{Temos até espólio de brahmin , espólios de ghoul, espólios de deathclaws.}
{208}{}{Vamos lá, você quer espólios? Entrem, amantes do espólio!}
{209}{}{If we don't got it, you don't want it! Come on in, booty lovers!}
{210}{}{Attention booty shoppers! Take advantage of this booty sale!}
{211}{}{Buy one piece of booty at the regular price, n' you'll get another piece of booty of equal or lesser value for only a chip!}
{212}{}{Venha e ganhe loot em troca de uma tampa!}
{213}{}{Se você pode encontrar espólio mais barato em qualquer lugar... NOS DIGA!}
