{100}{}{Você vê um boxeador.}
{101}{}{You see Mike "the Masticator."}
{150}{}{Seus braços parecem toras de árvores.}
{151}{}{Parece que cada braço poderia dar a volta em um barril de petróleo.}
{152}{}{Parece que observo um oceano de músculos enquanto ele se move.}
{153}{}{Ele olha para sua orelha com cara de fome.}
{154}{}{Seu rosto parece um pedaço de carne crua.}
{158}{}{Hurgghhh}
{159}{}{Gunhrrhh}
{160}{}{Mike esmaga.}
{161}{}{Eu curto um sorvete de baunilha.}
{162}{}{Gnarrrr}
{163}{}{Nrrrurhhh}
{164}{}{Mike like ears.}
{165}{}{Ears mmmmmmm.}
{166}{}{Grrrrrr}
{167}{}{Gr. Gr? Grrrrrrr.}
{168}{}{Gr?}
{169}{}{Rrrgggg}
{170}{}{Eu como orelhas.}
{171}{}{Ears yum.}
{172}{}{Gr... grrrgr?}
{173}{}{Snrggg}
{174}{}{Eu odeio Robbin 'Givens.}
{175}{}{Grrrrrgrrrrgrrr... grrr... grrr... grr! Grr! Grrr?}
{176}{}{What does 'percentage' mean?}
{200}{}{::Mike cowers as you approach::}
{201}{}{::Mike whines as you approach::}
{202}{}{::Mike holds up his hands in surrender as you approach::}
{203}{}{Que fofo.}
{204}{}{Eu gosto das suas orelhas.}
{205}{}{Chega de conversa. Hora de dormir.}
{206}{}{Robin? That you?}
