{100}{}{Você chegou em uma planície desértica fora de New Reno.}
{110}{}{Você vê várias caixas repletas de produtos químicos.}
{120}{}{You see several crates filled with chemicals. You can't identify the chemicals,
 but they have been packed VERY carefully.}
{130}{}{Você vê um Vertibird.}
{140}{}{You see a Vertibird... an advanced form of helicopter. Unfortunately, you have no
 idea how to operate it.}
{150}{}{You have no idea how to operate it.}
{200}{}{(Esses caras me dão arrepios...)}
{201}{}{(Cala a boca. Lá vêm eles.)}
{202}{}{*Zztttt* Você tem a carga que pedimos? *Zzzttt*}
{203}{}{Yes, the chemicals are all here. You can check them if you like.}
{204}{}{*Zztttt* Isso não será necessário. *Zzzttt*}
{205}{}{*Zztttt* You know what will happen if the chemicals do not meet the specifications
 we requested. *Zzzttt*}
{206}{}{Right, of course. Uh, and you brought the lightbringers...?}
{207}{}{*Zztttt* As armas a laser estão em nosso compartimento de carga. *Zzzttt**}
{208}{}{*Zztttt* To ensure your cooperation, we will transmit the arming sequence for them
 once the chemicals are loaded. *Zzzttt*}
{209}{}{Uh... bem... tudo bem então. Carreguem ela, garotos --}
{210}{}{*Zztttt* Não. *Zzzttt*}
{211}{}{*Zztttt* We will load the cargo. *Zzzttt*}
{212}{}{Uh, right... right. Of course. Give them room, boys.}
{213}{}{All right; we're good here. The rest of you guards head back to Reno. We'll meet up with you.}
{250}{}{Olhem! Tem alguém nos espionando!}
{251}{}{Matem eles!}
{252}{}{Parece que temos um espião...!}
{253}{}{*Zztttt* Mission aborted. Cargo failsafe sequence engaged. *Zzzttt*}
{254}{}{*Zztttt* Terminate hostiles, then return to base. *Zzzttt*}
{300}{}{Não chegue perto daqueles caras de armadura. Eles podem te partir no meio.}
{301}{}{Volte para a posição.}
{302}{}{Stop twitching... those armored guys don't like it much.}
{350}{}{Merda! O que você está fazendo, imbecil?!}
{351}{}{Get back to your post! What the hell are you do --?!}
{352}{}{*Zztttt* Mission aborted. Cargo failsafe sequence engaged. *Zzzttt*}
{353}{}{*Zztttt* Terminate hostiles, then return to base. *Zzzttt*}
{400}{}{[Parece que tem uma porta. Abrir e embarcar?]}
{401}{}{Aham}
{402}{}{Cai fora}
{403}{}{Embarca no Vertibird.}
{404}{}{O deixa sozinho.}
{450}{}{[Depois de entrar no porão de carga, a porta se fecha atrás de você! Você tenta forçá-la a abrir, mas ele não se move.
 Enquanto você tenta pensar em uma saída, ouve os soldados blindados embarcarem no Vertibird, que então decola com você
 preso aí dentro!]}
{451}{}{Oh oh}
{452}{}{Oh, merda...}
{500}{}{These crates are filled with heavy metal canisters. Judging from the care packing
 them, you suspect that they contain some sort of hazardous chemicals.}
{550}{}{Now's probably not the best time to be striking up conversation.}
