{100}{}{Você um deathclaw enorme. O bicho tem músculos enormes, dentes afiados, e garras.}
{101}{}{Você vê Gruthar, líder dos deathclaws.}
{102}{}{Você vê o deathclaw mais impressionante que você poderia imaginar. A criatura deve ser única entre
 sua espécie.}
{103}{}{Não tenha medo de mim, humano, minha intenção não é te fazer mal. Eu sou Gruthar, líder deste
 bando deathclaw. Por que você veio aqui?}
{104}{}{Por que você veio aqui?}
{105}{}{Uh...}
{106}{}{Pra comer seu cu!}
{107}{}{Como é possível que um deathclaw fale... e tão bem?}
{108}{}{Quero saber o que aconteceu com as pessoas que viveram aqui.}
{109}{}{Estou procurando algo chamado GECK. Me disseram que eu poderia encontrar um aqui.}
{110}{}{Me disseram para eliminar um covil com deathclaws muito perigosos...}
{111}{}{Estou investigando incursões nas fazendas de brahmins locais. Você sabe algo sobre isso?}
{112}{}{Acho que vou embora agora.}
{113}{}{Você não é idiota, humano, eu posso ver a verdade disso em seus olhos. Por favor, não tente me enganar.
 Não tenho paciência para joguinhos.}
{114}{}{Muito bem. Se você deseja ser considerado um idiota, então que assim seja. Volte para ca
 se mudar de ideia.}
{115}{}{Minhas desculpas, você parece ser intelectualmente desafiador. Você não é uma ameaça para
 mim ou para o bando. Você é bem-vindo aqui e pode considerar este lugar um refúgio seguro do mundo
 exterior. Não prejudique ninguém, fique longe de problemas e você sempre será bem-vindo aqui.}
{116}{}{Me perdoe, não quero ser rude, mas não acho que isso seja relevante para nossa conversa. Eu
 posso falar em seu idioma e ler seus textos escritos. O que mais há pra dizer?}
{117}{}{Eu vejo.}
{118}{}{Não quero me intrometer, mas certamente você pode entender meu interesse neste assunto.}
{119}{}{Sim, bem, que tal me deixar decidir o que é ou não relevante?}
{120}{}{Sim, certamente posso. Muito bem, se nos despedirmos como amigos, humano, você deveria falar com
 Goris. Ele tem mais conhecimento nesse assunto do que eu. Ele geralmente pode ser encontrado na biblioteca da vault.}
{121}{}{Obrigado. Eu gostaria de conhecer Goris.}
{122}{}{Não tenho intenção de botar um deathclaw na minha lista de amigos. Tchau!}
{123}{}{Tudo certo.}
{124}{}{Eles se foram, humano. Não os matamos nem os levamos para casa, não é nosso jeito de
 matar. Entendo que você pode não acreditar em mim, mas espero que me julgue por minhas ações em
 relação a você e não por medo ou preconceito.}
{125}{}{Ei, talvez você pense que eu vou chutar o sua bunda?}
{126}{}{Você parece ser honrado, Gruthar.}
{127}{}{Sim, eu suponho.}
{128}{}{Um geck. Não é aquele calanguinho... não, espera... isso é um gecko. Lamento, mas não sei o que é
 um geck, nem onde se pode encontrar um.}
{129}{}{Sim, eu acredito que você mencionou isso uma vez antes. Não sei o que é um geck, nem onde
 pode ser encontrado.}
{130}{}{Você vai me deixar entrar para procurá-lo?}
{131}{}{Ei, aquele comentário sobre o lagarto foi muito engraçado. É seu parente?}
{132}{}{É óbvio que falar com você é perda de tempo. Adeus.}
{133}{}{Para ser honesto com você, nem eu tenho certeza do que é. Tudo bem para você se eu
 procurar?}
{134}{}{Sinto muito, mas não permito que qualquer um perambule por estes corredores. Sou
 responsável pela segurança de todos os que vivem aqui e devo ter cautela. No entanto, vou
 procurar esse geck e, se eu encontrar, avisarei.}
{135}{}{Sinto muito, mas não permito que qualquer um perambule por estes corredores. Sou
 responsável pela segurança de todos os que vivem aqui e devo ter cautela.}
{136}{}{Olhe, não é como se você fosse o dono do lugar. Talvez eu de uma olhada, goste você ou não!}
{137}{}{Entendo, Gruthar, e respeitarei seu desejo de privacidade.}
{138}{}{Entendo sua preocupação, você não me conhece bem o suficiente para confiar em mim. E se eu
 pudesse ajudá-lo de alguma forma e, em troca, você me permitisse dar uma olhada?}
{139}{}{(Gruthar olha fixamente para você por um momento.) Você estaria interessado em nos ajudar? Sim, não
 sinto maldade em você. Muito bem, depositarei minha confiança em você.}
{140}{}{(Gruthar olha fixamente para você por um momento.) Acho que não, eu posso sentir a maldade em
 você, humano. Não posso arriscar a vida daqueles que protejo me arriscando com você.}
{141}{}{Obrigado.}
{142}{}{Certo. Acho que uma lobotomia na base da bala é uma solução viável para o meu problema.}
{143}{}{Lamento que você se sinta assim, Gruthar.}
{144}{}{Eu vou embora, então.}
{145}{}{Existem muitas máquinas aqui, máquinas construídas por humanos. As mãos de Deathclaws não
 conseguem usar essas máquinas. No entanto, existe uma máquina que entende perguntas, pedimos que
 operasse as outras máquinas e ela obedeceu. Esta máquina não escuta mais, ela não executa mais as
 outras, agora estamos ficando sem comida e água. Até ordenei ataques às terras humanas para que
 possamos sobreviver. Não tenho orgulho disso e colocaria um fim agora se pudesse. Se você consertar
 esta máquina, poderei alimentar meu povo novamente, terei prazer em interromper os ataques. Aceita esse trato?}
{146}{}{Desculpe, não tenho ideia de como consertar uma coisa dessas.}
{147}{}{Não sou técnico, mas posso tentar.}
{148}{}{Hmm... parece que o módulo de reconhecimento de voz quebrou. Vamos dar uma olhada.}
{149}{}{Eu mudei de ideia. Vou ter que pensar um pouco mais sobre isso.}
{150}{}{Farei o que puder para ajudar.}
{151}{}{Eu me recuso a ajudar os deathclaws.}
{152}{}{Obrigado. A máquina está no centro de controle do Vault, no terceiro nível. Se você puder
 repará-la, por favor, faça. Estou colocando minha confiança em você. Por favor, não nos traia, você é bem vindo aqui.}
{153}{}{I won't let you down, Gruthar. You have my word on that.}
{154}{}{Thanks. I'll get on it.}
{155}{}{There really is one born every minute...}
{156}{}{I see... Well, deathclaws are dangerous by nature and great care must be taken when encountering
 them in the wild. However, I am certain that you have noticed that we are an exception. My pack poses
 no threat to you or your human communities. We have evolved beyond our base cousins and wish simply to
 be left alone.}
{157}{}{Uh... sim.}
{158}{}{Your heightened intellect could make you even more of a threat than the average deathclaw,
 Gruthar.}
{159}{}{I can see that you are not the savage killers that deathclaws are known to be.}
{160}{}{I have spent many sleepless nights, deep in thought, pondering just such issues. I have finally
 come to the conclusion that the burdens and responsibilities associated with the gift of intelligence
 are countless. There are only two choices available to any thinking being. Either accept life as it
 comes and make the best of it for yourself and others, or simply cease to be. I have chosen to accept
 the challenges of life. If this makes me a threat to humankind, then I pity the small mind that finds
 it so...}
{161}{}{Yes, well... I may have a small mind but I also have a BIG weapon.}
{162}{}{I couldn't agree with you more. I don't think you're a threat, Gruthar.}
{163}{}{Uh... yeah. What you said.}
{164}{}{(Gruthar pauses and seems to be carefully considering his response to you) I am sorry to say
 that I ordered the raids on the human lands. I am responsible for the lives of many here. We are
 running out of food, water, and other supplies. Until I can get the situation corrected, I need to take
 what I, a deathclaw, cannot ask humans for.}
{165}{}{Well, now that I know the source of the raids, I'll just eliminate it!}
{166}{}{I'm sorry to hear that. Is there some way that I may be able to help you so that you can stop
 the raids?}
{167}{}{I've heard enough for now. I need some time to think.}
{168}{}{I see...}
{169}{}{I am displeased with your decision but I accept it. You may leave, but please return if you
 reconsider.}
{170}{}{Feito.}
{171}{}{Hello}
{172}{}{No. I'll get to it, though.}
{173}{}{I'm sorry, Gruthar. The voice module has gone bad. I'll have to go get one.}
{174}{}{I do not understand the workings of such things but I trust you,}
{175}{}{Feito.}
{176}{}{I shall return, you have my word.}
{177}{}{Hello}
{178}{}{Não, eu ainda estou procurando.}
{179}{}{Yes, and here it is!}
{180}{}{}
{181}{}{You have restored my faith in humans. I thank you for all that you have done for the pack. Is
 there something that I can do for you in return?}
{182}{}{You said you would let me know if you found a GECK here. Did you locate one?}
{183}{}{Yes, I am looking for a GECK. I have been told that I could find it here. Do you know where it is?}
{184}{}{No, thank you. I have everything that I need.}
{185}{}{Ah, let me see. [He leaves, then returns a moment later, awkwardly clutching some kind of metallic case in his large claws.] Yes, there was a geck in the vault storage room. It is yours with many thanks.}
{186}{}{Yes, there was a geck in the vault storage room. However, it is missing. I am sorry
 that I cannot give it to you as a reward for all your generous help.}
{187}{}{Obrigado!}
{188}{}{Uh... that's okay. I'll try to locate one elsewhere.}
{189}{}{Hello again, human. I hope that you do not intend to play the fool with me.}
{190}{}{I want to apologize and start over, Gruthar.}
{191}{}{Sorry, I gotta go.}
{192}{}{Ah, desculpe.}
{193}{}{Saudações, humano. Você reconsiderou? Você vai me ajudar?}
{194}{}{De jeito nenhum. Eu só queria ouvir você assassinar um pouco mais a língua.}
{195}{}{Não, eu não penso assim.}
{196}{}{Sim, Gruthar. Vou te ajudar.}
{197}{}{Saudações, amigo. Checou a máquina?}
{198}{}{Ainda não, mas vou começar.}
{199}{}{Olá, meu amigo. Você salvou o pacote e nós agradecemos.}
{200}{}{}
{201}{}{}
{202}{}{Morra, humano traiçoeiro!}
{203}{}{}
{204}{}{}
{205}{}{Eu não tenho nada contra você, humano, e eu não quero ter. Estou tentando lidar de um modo civilizado.
 Por favor, retribua o favor!}
{206}{}{Tudo bem, vamos conversar então.}
{207}{}{Você é um Deathclaw e essa será sua sentença de morte... Isso é tudo!}
{208}{}{Desculpe, Gruthar. Vamos conversar.}
{209}{}{Que seja. Vou embora.}
{210}{}{Não. Eu sou o líder aqui, então eu que decido. Se você não gostar de alguma coisa, pode voltar para suas terras humanas!}
{211}{}{Chupa aqui oh!}
{212}{}{Certo, já vou indo.}
{213}{}{Claro, Gruthar. Eu me esqueci por um momento.}
{214}{}{Te garanto que não estava tentando ser engraçado ou brincar com você. Por favor, me desculpe se deixei
 essa impressão. Eu te ajudaria se pudesse.}
{215}{}{Bem, valeu.}
{216}{}{Desculpe, não queria ser impertinente.}
{217}{}{Esqueça essa pose civilizada, cara. Não funciona comigo.}
{218}{}{(Gruthar emite uma série de grunhidos guturais) Posso não ser o dono deste lugar, humano,
 mas é meu lar e o lar de outros que confiam em mim para protege-los. Não me force, ou qualquer um
 de nós a fazer alguma coisa que nos arrependeremos depois!}
{219}{}{Eu sinto muito; fui indelicado e ultrapassei os limites.}
{220}{}{Aperto você e todos que se parecem com você!}
{221}{}{Ha ha! Vou sair daqui.}
{222}{}{Obrigado. Por favor, vá para a sala de controle e substitua o módulo.}
{223}{}{Considere isso feito!}
{224}{}{}
{225}{}{Você não é bem-vindo aqui agora. Pode sair.}
{226}{}{Adeus.}
{227}{}{Adeus.}
{228}{}{Feito.}
{229}{}{Desculpas aceitas, humano. Tenha um bom dia!}
{230}{}{Feito.}
{231}{}{. Você examinou a máquina?}
{232}{}{. Vou esperar seu retorno.}
{233}{}{. Encontrou a peça para consertar a máquina?}
{234}{}{Uh, tudo bem.}
{235}{}{Espero que você esteja gostando da sua estadia.}
{236}{}{Infelizmente, tivemos que chegar a isso. Eu permiti que ele ficasse ileso, desde que ele não representasse nenhuma ameaça para o bando. Mas escolheu seu caminho, espero que entenda.}
{237}{}{Voce mau.}
{238}{}{Entendo, Gruthar.}
{239}{}{Sim. Matt não é bom.}
