{100}{}{Você vê um pequeno homem com um livro em suas mãos.}
{101}{}{Você vê Joseph, o herbalista.}
{102}{}{Você vê um homem baixo com um livro chamado "Ervas e seus usos medicinais".}
{103}{}{Olá, sou Joseph, o herbalista. Com o que posso ajudar?}
{104}{}{Tenho owie. Você conserta?}
{105}{}{Sinto icky. Você conserta?}
{106}{}{Eu gimp, você conserta?}
{107}{}{Tenho dúvidas. Tudo bem?}
{108}{}{Desculpe, eu vou.}
{109}{}{Eu estou ferido. Você pode me ajudar?}
{110}{}{Eu me sinto doente. Você pode me ajudar?}
{111}{}{Eu estou aleijado. Você pode me ajudar?}
{112}{}{Eu queria pedir-lhe algumas perguntas.}
{113}{}{Apenas dizer "olá".}
{114}{}{Desde já. Hmmm, você vai precisar levar um pouco disso. Vou aplicar este bálsamo na
 ferida. Agora é só deitar e descansar por algumas horas.}
{115}{}{Eu agradecer. Tchau.}
{116}{}{Obrigado, Doc. Eu me sinto muito melhor.}
{117}{}{Desde já. Hmmm, isso vai demorar um pouco, você terá que passar a noite aqui. Você vai
 precisar tomar isso, beba isso - tudo isso, eu sei que o gosto não ajuda. Agora, apenas deite
 e eu te acordo pela manhã.}
{118}{}{Me sinto bem. Tchau.}
{119}{}{Obrigado. Resolveu o problema.}
{120}{}{Lamento, mas não sou médico e não posso fazer cirurgias. Sugiro que você vá a uma das
 cidades maiores e consulte com um cirurgião. Tente a República da Nova Califórnia. É a leste daqui.}
{121}{}{Tudo bem. Tchau.}
{122}{}{Tudo bem. Obrigado de qualquer forma.}
{123}{}{O que você gostaria de saber?}
{124}{}{Seu prisioneiro?}
{125}{}{Você sai daqui quando quer?}
{126}{}{O que sabe dos deathclaws?}
{127}{}{Como você está aqui?}
{128}{}{Eu vou agora.}
{129}{}{Você é prisioneira aqui?}
{130}{}{Você pode sair daqui se você deseja?}
{131}{}{O que você pode me contar sobre os deathclaws?}
{132}{}{Como você chegou a estar aqui, em primeiro lugar?}
{133}{}{Obrigado pela informação. Eu vou estar indo agora.}
{134}{}{Não, eu não sou um prisioneiro, eu fico porque sou necessário aqui. Aprendi a aceitar o fato de que
 alguns de meus pacientes são deathclaws.}
{135}{}{Tudo bem. Precisa saber mais.}
{136}{}{Obrigado. Tchau.}
{137}{}{Isso é muito louvável.}
{138}{}{Eu vejo.}
{139}{}{Essa é uma decisão com a qual não concordo, mas é a sua vida.}
{140}{}{Sim, eu posso, e faço várias vezes. Eu tenho que colher minhas ervas de vez em quando
 e nunca me pararam, até costumava me perguntar se os deathclaws estavam me seguindo em segredo e
 se eles me impediriam ou não se eu tentasse sair. Então, um dia, coloquei a teoria à prova.}
{141}{}{Eu entendi. Vá agora.}
{142}{}{Precisa pedir mais.}
{143}{}{Foi uma escolha estúpida e você tem sorte de ter funcionado.}
{144}{}{Tudo certo.}
{145}{}{Boa ideia. Fico feliz em ver que funcionou.}
{146}{}{Bem, vamos ver... Deathclaws parecem ser camaleões mutantes de Jackson, a variedade com
 chifres. Há muitas semelhanças ainda presentes, mas um número ainda maior de diferenças, o fator
 de mutação é bastante alto. Esta espécie é altamente inteligente, equivalente a uma criança de
 oito anos, com alguns indivíduos atingindo o nível humano normal. Sua capacidade de aprendizado é
 muito alta e eles são capazes de pensar e raciocinar de forma abstrata.}
{147}{}{Uh... o que você disse.}
{148}{}{Tenho que ir agora.}
{149}{}{Uh-huh.}
{150}{}{Uau, estou impressionado com o seu conhecimento.}
{151}{}{Parece um monte de besteira para mim.}
{152}{}{Eu estava colhendo algumas ervas uma noite quando uma voz me chamou da escuridão. 'Tenho
 observado você', disse, 'e sei que você é um curador. Você é dedicado à sua arte o suficiente para curar
 algum que seja estranho a você? Alguém que muitos considerariam um inimigo?'}
{153}{}{Ugh.}
{154}{}{Obrigado. Eu vou embora agora.}
{155}{}{Que desperdício estar aqui quando você poderia estar ajudando os outros.}
{156}{}{Você é realmente um homem dedicado que merece reconhecimento.}
{157}{}{Interessante.}
{158}{}{Eu não vou ajudar alguém como você. Vá embora.}
{159}{}{Viajei para outra cidade e fiquei lá mais ou menos uma semana antes de voltar, quando voltei, fui
 muito bem recebido. Gruthar, o líder do bando, veio até mim em particular e me agradeceu pessoalmente
 por ter voltado. Não, eu realmente estou aqui porque quero estar.}
{160}{}{Embora não tenham cordas vocais, os deathclaws parecem imitar a fala humana da mesma forma que
 um papagaio. Ainda não descobri o mecanismo exato que faz isso, então não posso dizer mais nada
 concreto. Socialmente, são animais de carga com um código de ética muito rígido e são liderados
 por um 'macho alfa' que governa com o consentimento mútuo do bando. Eles parecem ser extremamente
 leais ao bando como um todo, os tratando como uma unidade familiar, em vez de terem famílias individuais como os humanos.}
{161}{}{Seu senso de certo e errado é muito bem definido, eles seguem um código de ética que é
 aplicado pelo bando completo. A violência nunca é usada como solução para um problema entre o bando,
 até onde pude ver. Não houve 'crimes capitais' cometidos aqui, então não posso dizer como eles
 são tratados. Hmmm, isso é tudo que consigo pensar por enquanto, espero que isso possa te ajudar.}
{162}{}{Respondi que respeitava todas as vidas e faria o possível para curar os feridos, independentemente
 de quem ou o que fossem. Achei que fosse algum ladrão ou assaltante que se machucou e precisava
 de um médico. Você não pode começar a imaginar minha surpresa quando um par de deathclaws
 saiu da noite com um companheiro ferido, alguém acertou um tiro muito bem. Eu disse a eles que não poderia
 trabalhar com ele onde estávamos, então eles me vendaram e me trouxeram aqui. Estou aqui desde aquele dia.}
