{100}{}{Você vê um pequeno homem com um livro em suas mãos.}
{101}{}{You see Joseph, the herbalist.}
{102}{}{You see a short man with a book called "Herbs and Their Medicinal Uses."}
{103}{}{Hello, I'm Joseph the herbalist. What can I help you with?}
{104}{}{Tenho owie. Você conserta?}
{105}{}{Sinto icky. Você conserta?}
{106}{}{Eu gimp, você conserta?}
{107}{}{Tenho dúvidas. Tudo bem?}
{108}{}{Desculpe, eu vou.}
{109}{}{Eu estou ferido. Você pode me ajudar?}
{110}{}{Eu me sinto doente. Você pode me ajudar?}
{111}{}{Eu estou aleijado. Você pode me ajudar?}
{112}{}{Eu queria pedir-lhe algumas perguntas.}
{113}{}{Apenas dizer "olá".}
{114}{}{Why, certainly. Hmmm. You'll need to take some of this. I'll apply this balm to the wound.
 Now just lie back and rest for a couple of hours.}
{115}{}{Eu agradecer. Tchau.}
{116}{}{Obrigado, Doc. Eu me sinto muito melhor.}
{117}{}{Why, certainly. Hmmm. This will take a while, so you'll have to stay here overnight. You'll
 need to take this, drink this -- all of it, I know it tastes foul. Now, just lie back and I'll wake
 you in the morning.}
{118}{}{Me sinto bem. Tchau.}
{119}{}{Thanks. That did the trick.}
{120}{}{I'm sorry, but I'm not a medical doctor and I can't perform surgery. I would suggest that you
 go to one of the bigger cities and see a surgeon. Try the New California Republic. It's east of here.}
{121}{}{Tudo bem. Tchau.}
{122}{}{Tudo bem. Obrigado de qualquer forma.}
{123}{}{O que você gostaria de saber?}
{124}{}{Seu prisioneiro?}
{125}{}{Você sai daqui quando quer?}
{126}{}{What you know about D'claws?}
{127}{}{Como você está aqui?}
{128}{}{Eu vou agora.}
{129}{}{Você é prisioneira aqui?}
{130}{}{Você pode sair daqui se você deseja?}
{131}{}{O que você pode me contar sobre os deathclaws?}
{132}{}{Como você chegou a estar aqui, em primeiro lugar?}
{133}{}{Obrigado pela informação. Eu vou estar indo agora.}
{134}{}{No, I'm not a prisoner. I stay because I'm needed here. I've learned to accept the fact that
 some of my patients are deathclaws.}
{135}{}{Tudo bem. Precisa saber mais.}
{136}{}{Obrigado. Tchau.}
{137}{}{Isso é muito louvável.}
{138}{}{Eu vejo.}
{139}{}{That's a decision that I can't agree with, but it's your life.}
{140}{}{Yes I can, and often do. I have to collect my herbs from time to time, and I've never been
 stopped. I used to wonder if the deathclaws were secretly following me and whether or not they would
 stop me if I tried to leave. So one day I put the theory to test.}
{141}{}{Eu entendi. Vá agora.}
{142}{}{Precisa pedir mais.}
{143}{}{You took a foolish chance and you're lucky it paid off.}
{144}{}{Tudo certo.}
{145}{}{Good idea. I'm glad to see it worked.}
{146}{}{Well, let's see... Deathclaws appear to be mutated Jackson's Chameleons, the horned variety.
 There are a lot of similarities still present, but an even greater number of differences. The mutation
 factor is quite high. This species is highly intelligent, about the equivalent of an eight-year-old,
 with some individuals reaching human normal level. Their learning capacity is very high and they are
 capable of abstract thought and reasoning.}
{147}{}{Uh... o que você disse.}
{148}{}{Tenho que ir agora.}
{149}{}{Uh-huh.}
{150}{}{Wow, I'm impressed with your knowledge.}
{151}{}{Sounds like a bunch of hogwash to me.}
{152}{}{I was gathering some herbs one night when a voice called to me out of the darkness. 'I have been
 watching you,' it said, 'and I know that you are a healer. Are you dedicated to your art enough to heal
 someone foreign to you? Someone whom many would consider an enemy?'}
{153}{}{Ugh.}
{154}{}{Obrigado. Eu vou embora agora.}
{155}{}{What a waste to be here when you could be helping others.}
{156}{}{You are truly a dedicated man who deserves recognition.}
{157}{}{Interessante.}
{158}{}{Eu não vou ajudar alguém como você. Vá embora.}
{159}{}{I traveled to another town and stayed there a week or so before returning. When I got back, I was
 warmly welcomed. Gruthar, the pack leader, came to me privately and personally thanked me for coming
 back. No, I am definitely here because I want to be.}
{160}{}{Although they do not have vocal chords, the deathclaws seem to mimic human speech much the same
 as a parrot does. I have yet to discover the exact mechanism behind this, so I am unable to say more at
 this time. Socially, they are pack animals with a very rigid code of ethics. They are led by an 'alpha
 male' who rules with the mutual consent of the pack. They appear to be extremely loyal to the pack as a
 whole, treating it as a family unit rather than having individual families as humans do.}
{161}{}{Their sense of right and wrong is very well defined. They do follow a code of ethics that is
 enforced by the pack as a whole. Violence is never used as a solution to a problem among the pack as
 far as I can see. There have been no 'capital crimes' committed here, so I can't say how those are
 handled. Hmmm. That's about all I can think of for now. I hope this helps you.}
{162}{}{I answered that I respected all life and would do my best to heal the injured, regardless of who
 or what they were. I thought it was some thief or raider who had gotten himself hurt and needed
 a doctor. You can't begin to imagine my surprise when a couple of deathclaws stepped out of the
 night with an injured companion. Somebody had shot him up real good. I told them I couldn't work on him
 where we were, so they blindfolded me and brought me here. I've been here from that day forward.}
