{100}{}{Você vê um garra mortal. Ele observa você com olhos estranhamente inteligentes.}
{101}{}{You see Jul, the Deathclaw.}
{102}{}{Você vê um típico garra mortal. A criatura é enorme, com um corpo poderoso, dentes afiados, e longas garras.}
{103}{}{Stop. You not go here. This place off limits.}
{104}{}{Tudo bem. - Me ir.}
{105}{}{O que este lugar?}
{106}{}{Quem é você?}
{107}{}{All right, I'll leave}
{108}{}{I go where I please, lizard breath!}
{109}{}{O que é este lugar?}
{110}{}{Quem é você?}
{111}{}{This hatchery. Pack mother inside. Eggs inside. I guard. All of pack guard.}
{112}{}{Me want talk mother.}
{113}{}{Quem é você?}
{114}{}{Eu vou agora.}
{115}{}{I'll be leaving then.}
{116}{}{Quem é você?}
{117}{}{I'd like to speak to the mother.}
{118}{}{I Jul. Pack warrior. I guard hatchery. I guard mother.}
{119}{}{Eu}
{120}{}{Eu vou agora.}
{121}{}{Guard mother important job. You important.}
{122}{}{Eu sou}
{123}{}{Guarding mother is a position of great responsibility. You must be an important pack member.}
{124}{}{I guess I'll be leaving now.}
{125}{}{You wait. I ask mother.}
{126}{}{Tudo bem.}
{127}{}{Mother say she talk to you. You go in. You not cause trouble. I not want hurt you, but I hurt
 you bad if you cause trouble.}
{128}{}{Mother say she talk to you. You go in but you go alone; friends stay here. You not cause
 trouble. I not want hurt you, but I hurt you bad if you cause trouble.}
{129}{}{Tudo bem.}
{130}{}{You think so? I not look at it that way. That make me feel good. I like. Thank you.}
{131}{}{You welcome. Me go now.}
{132}{}{Me want talk mother.}
{133}{}{You're welcome. I've got to go now.}
{134}{}{May I talk to mother?}
{135}{}{Lizard breath... Oh, I get it. Ha ha! Now you get this. I guard here because I meanest,
 toughest, ruthless son of bitch in whole damn vault. Screw with me, you screw with best.
 You leave here or I rip you head off and make you watch me crap down throat.}
{136}{}{Eu vou estar indo agora.}
{137}{}{Oh yeah? Let's see just how tough you are!}
{138}{}{It you again. What you want?}
{139}{}{Me say hi. Me go.}
{140}{}{Who you say you be?}
{141}{}{O que este lugar?}
{142}{}{Just dropped by to say hello.}
{143}{}{O que é este lugar?}
{144}{}{Who are you again?}
{145}{}{You already dead. You just too dumb to fall over.}
{146}{}{. Me want talk mother.}
{147}{}{, Jul, and I'd like to talk to the mother, please.}
