{100}{}{Você vê um deathclaw.}
{101}{}{Você vê Kerith, a mãe deathclaw.}
{102}{}{Você vê um típico deathclaw. A criatura é grande, com um corpo poderoso, dentes pontudos e garras
 longas. Esse parece ser uma fêmea, mas não se pode ter certeza. Você nota cicatrizes de vários machucados pelo seu corpo.}
{103}{}{A human visitor is an unexpected but not unwelcome event. I am Kerith.}
{104}{}{Com o que posso ajudar?}
{105}{}{You D'claw mother?}
{106}{}{Who D'claw father?}
{107}{}{Door look like crap. What happen?}
{108}{}{Who build nest room?}
{109}{}{Eu vou agora.}
{110}{}{Então, você é a mãe deathclaw?}
{111}{}{Quem é o pai deathclaw?}
{112}{}{What happened to the door? It looks like it has seen better days.}
{113}{}{Who built this hatchery?}
{114}{}{I'll be leaving now.}
{115}{}{Yes. I am the current pack mother. After my eggs hatch, the other mothers will have their turn.}
{116}{}{Tudo bem.}
{117}{}{Other mothers?}
{118}{}{Eu vejo.}
{119}{}{There are other mothers?}
{120}{}{Yes, there are more mothers. Should anything happen to me, one will be chosen to take my place.
 The pack must survive.}
{121}{}{Uh, me understand.}
{122}{}{Eu entendo.}
{123}{}{These eggs were sired by Gruthar, the pack leader. It is Gruthar who decides who will mate and
 who will not. The pack will be made strong by Gruthar.}
{124}{}{Uh, tudo bem.}
{125}{}{Hmmm. I see. Selective breeding to improve the strain.}
{126}{}{That is a painful memory. A treacherous human sneaked in here and planted a bomb among the eggs
 while I was asleep. Fortunately he was not as stealthy leaving and I awoke to find the bomb. There was
 not enough time to deal with the device properly, so I threw it at the door and placed myself between
 it and the eggs. The eggs and I survived. The door did not.}
{127}{}{What happen to human?}
{128}{}{How get by guard outside?}
{129}{}{Me got more questions.}
{130}{}{What happened to the person who did this?}
{131}{}{How did this person get by the guard outside?}
{132}{}{Tenho mais umas perguntas.}
{133}{}{His name is Matt, and he is a prisoner here. Personally, I wanted him dead -- but Gruthar would
 not allow it. I do not see the wisdom in this, but Gruthar's word is law and he will be obeyed. Should
 you talk to this human, take care. He cannot be trusted!}
{134}{}{How get by guard outside?}
{135}{}{Tudo bem.}
{136}{}{How did this person get by the guard outside?}
{137}{}{Tudo bem.}
{138}{}{The guard was added after this incident occurred. We were more trusting back then. Now we are
 more careful.}
{139}{}{What happen to human?}
{140}{}{Eu entendi.}
{141}{}{What happened to this person?}
{142}{}{Eu vejo.}
{143}{}{We built the cave portion, and a human friend installed the door. He got the parts from a settlement
 north-east of here.}
{144}{}{Que bom.}
{145}{}{That's nice.}
{146}{}{Hello again. It is good to see you. What can I help you with?}
{147}{}{Me just say hello. Me go now.}
{148}{}{Just saying hi. I'll be going now.}
{149}{}{It saddens me to have to kill you.}
