{100}{}{Você vê um garra mortal. Ele observa você com olhos estranhamente inteligentes.}
{101}{}{Você vê Valdis, o Deathclaw.}
{102}{}{Você vê um típico garra mortal. A criatura é enorme, com um corpo poderoso, dentes afiados,
 e longas garras.}
{103}{}{Saudações, humano.}
{104}{}{Como posso te ajudar?}
{105}{}{Quem é voce?}
{106}{}{O que você faz?}
{107}{}{Minha cabeça doi. Volto mais tarde}
{108}{}{Olá, quem é você?}
{109}{}{Qual é o seu trabalho?}
{110}{}{Sem ofensa para seus amigos Deathclaws, mas você parece mais... educado, entende?}
{111}{}{Bom, só passando o tempo.}
{112}{}{Eu me chamo Valdis. E você é...?}
{113}{}{Eu humano.}
{114}{}{Oooo! Algo brilhante. Eu vou.}
{115}{}{Ei, eu que estou fazendo as perguntas aqui.}
{116}{}{Tenho que ir.}
{117}{}{Prazer em conhecê-lo, sou}
{118}{}{Tenho-o.}
{119}{}{Atualmente, estou protegendo esta área da Vault contra qualquer pessoa não autorizada.}
{120}{}{Pessoa.. nao alto e risada?}
{121}{}{Ah... certo.}
{122}{}{Fala engraçado. Eu vou.}
{123}{}{Estou indo agora, Valdis.}
{124}{}{Eu vejo.}
{125}{}{Bem, você certamente parece conhecer bem o seu trabalho.}
{126}{}{Você tem o cérebro para decidir quem é ou não 'autorizado?'}
{127}{}{Sim, eu tenho. Eu também tenho cérebro suficiente para decidir quem é ou não um imbecil - e chego a
 conclusão que você é mestre nessa categoria! Agora, por que você não vai embora antes que eu dance na
 sua cara meia hora?}
{128}{}{Tudo certo.}
{129}{}{Lagarto mau. Agora vou disparar.}
{130}{}{Ei, me desculpe. Vou segurar minha língua a partir de agora.}
{131}{}{Sim. Somos bastante diversificados em nossos níveis de educação. Estou fazendo o meu melhor para
 continuar me aprimorando em meu tempo livre.}
{132}{}{Uma iguana com um objetivo. Que fofo.}
{133}{}{Você está indo bem.}
{134}{}{Esse é um excelente objetivo. Continue assim.}
{135}{}{Huh? Estou bem ciente de que você é humano. Eu estava perguntando sobre seu nome.}
{136}{}{Não perguntou nome, perguntou 'você é'. Eu humano.}
{137}{}{Eu sei. Eu apenas testava você. Uh... você passou.}
{138}{}{Ouvi alguém chamar. Eu vou.}
{139}{}{Entendo. Vamos tentar isso novamente. Olá, eu sou Valdis. Qual o seu nome?}
{140}{}{Eu}
{141}{}{Adeus.}
{142}{}{Pessoal não autorizado. Significa 'pessoas que não têm permissão para estar aqui.'}
{143}{}{Ok. Me entender.}
{144}{}{Eu terei outra daquelas dores de cabeça. Eu vou agora.}
{145}{}{Meu objetivo é manter o máximo de paciência possível, tendo em vista que você está sendo rude. Se você
 não pode lidar comigo civilizadamente, então, por favor, vá embora.}
{146}{}{Desculpe, vou tentar ser mais civilizado.}
{147}{}{Empurra.}
{148}{}{Sim.}
{149}{}{Bom dia pra você.}
{150}{}{Eu lamento o ocorrido, mas devo mata-lo.}
{151}{}{.}
