{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal de interface de voz.}
{102}{}{Você vê um terminal de computador padrão, modificado para comandos de voz.}
{103}{}{Você examina o terminal do computador, mas não consegue encontrar nada obviamente errado com ele.
 O que você faz?}
{104}{}{O golpeia de maneira "especial".}
{105}{}{O chuta de maneira "especial".}
{106}{}{Execute o programa de diagnóstico.}
{107}{}{Abre e o olha por dentro.}
{108}{}{O deixa sozinho.}
{109}{}{Você olha para o console por um tempo e decide o melhor local para dar um soco. Depois de
 dar o seu melhor 'isso vai consertar', o monitor pisca algumas vezes e depois se estabiliza.
 Não há outro efeito. O que faz?}
{110}{}{O chuta de maneira "especial".}
{111}{}{Execute o programa de diagnóstico.}
{112}{}{Abre e o olha por dentro.}
{113}{}{O deixa sozinho.}
{114}{}{Este método de reparo bem conhecido alcança dois resultados. Primeiro, o monitor parece
 enlouquecer por vários segundos e depois se estabiliza. Em segundo lugar, você ouve um tipo de som de
 metal quebrando e o painel que você chutou cai no chão. O que você faz?}
{115}{}{Execute o programa de diagnóstico.}
{116}{}{A maldita coisa está aberta. Poderia muito bem olhar para dentro.}
{117}{}{O deixa sozinho.}
{118}{}{Você tem certeza de que o sistema deve ter um conjunto de rotinas de diagnóstico disponíveis.
 No entanto, a entrada do teclado parece ter sido desativada. A unidade aceita apenas comandos de voz. O que você faz?}
{119}{}{A única coisa que resta é olhar para dentro.}
{120}{}{O deixa sozinho.}
{121}{}{Olhando para o monte de cabos e placas de circuito, você descobre que o sistema foi sabotado deliberadamente.
 Uma das placas de circuito, o módulo de reconhecimento de voz, não tem conserto e deve ser
 substituída. Agora tudo que você precisa fazer é encontrar um módulo de substituição.}
{122}{}{Feito.}
{123}{}{Feito.}
{124}{}{Você instala o módulo no terminal. O sistema é reparado.}
{125}{}{O terminal precisa de um módulo de reconhecimento de voz instalado antes de se tornar operacional.}
{126}{}{Feito.}
{127}{}{O sistema está funcionando bem agora.}
{128}{}{Acessando imagens de segurança, carregando reprodução holográfica...}
{129}{}{Você é o último, Gruthar. A mancha de sua espécie logo será limpa.}
{130}{}{Diga ao seu suposto presidente que ele vai queimar por isso.}
{131}{}{Qualquer que seja. Você nunca foi nada além de um animal falante.}
{132}{}{Talvez, mas fomos criados por meio dos seus experimentos. Você nos deu a vida!}
{133}{}{E agora te dou a morte.}
{134}{}{Pegue o corpo dele. O médico queria uma amostra.}
{135}{}{O sangue deles correrá como o Nilo!}
{200}{}{Bem-vindo, Morador da Vault. Para sua conveniência, este terminal Vault-Tec foi modificado para responder a comandos vocais. Por favor, vocalize seu comando agora.}
{201}{}{Oh, você me confundiu com outra pessoa. Você vê, eu não sou o Morador da Vault, eu sou o Escolhido. }
{202}{}{Execute o diagnóstico.}
{203}{}{Mude para o modo de entrada do teclado.}
{204}{}{Segurança de acesso ao material de arquivo.}
{205}{}{Termine a sessão.}
{206}{}{Urk?}
{210}{}{[Uma luz pisca no terminal enquanto faz vários cliques e sons giratórios. Após alguns segundos, o texto
 aparece no monitor.] Desculpe, não entendi seu comando. Por favor, repita seu comando, certificando-se de falar diretamente
 no microfone de forma clara e precisa. A Vault-Tec pede desculpas por qualquer inconveniente. Obrigado.}
{211}{}{Execute o diagnóstico.}
{212}{}{Mude para o modo de entrada do teclado.}
{213}{}{Segurança de acesso ao material de arquivo.}
{214}{}{Termine a sessão.}
{220}{}{Aguarde enquanto eu inicio as verificações de diagnóstico. A Vault-Tec agradece sua paciência... Obrigado por aguardar...
 Verificações de diagnóstico concluídas. Todos os sistemas estão funcionando corretamente. Afinal, você está usando Vault-Tec.}
{221}{}{Voltar.}
{222}{}{Termine a sessão.}
{230}{}{Mudando para o modo de interface manual... modo de interface manual iniciado. Para a conveniência de
 outros, este terminal reverterá automaticamente para o modo de interface vocal assim que você fizer logoff. Insira o comando.}
{231}{}{Banco de dados de pesquisa para qualquer coisa de interesse.}
{232}{}{Termine a sessão.}
{240}{}{Depois de pesquisar um pouco, você descobre três arquivos que podem valer a pena dar uma olhada: Guia
 de Sobrevivencia do Morador da Vault (versão resumida), Linha do Tempo da Vault 13 e Registros do Supervisor.}
{241}{}{Acesse o Guia de Sobrevivência do Morador da Vault (versão resumida). }
{242}{}{Acesso a linha do tempo da Vault 13. }
{243}{}{Acesso aos registros do Supervisor.}
{244}{}{Termine a sessão.}
{250}{}{Bem-vindo à Vault-13, a mais recente de uma série de obras de defesa pública da Vault-Tec, sua empreiteira preferida
 quando se trata do melhor em abrigos nucleares. Vault-Tec, o que temos de mais recente em casas.}
{251}{}{[MAIS]}
{252}{}{A série Vault de abrigos de sobrevivência foi projetada desde o início para fornecer a melhor chance de uma boa
 vida após o armagedom nuclear. É dever de todo cidadão americano aprender e usar as habilidades necessárias para uma vida confortável na Vault. O melhor lugar para começar é com uma descrição de sua nova casa.}
{253}{}{[MAIS]}
{254}{}{ESTATÍSTICAS IMPORTANTES DA VAULT 13
                                    Data de início da construção: agosto de 2063
                        Data de término da construção: março de 2069
                             Orçamento inicial: $ 400.000.000.000
                                Orçamento final, com juros: $ 645.000.000.000
                   Número total de ocupantes: 1.000 (na capacidade)
                 Duração total: 10 anos (na capacidade)
                            Número de alojamentos: 100 (beliches aquecidos necessários na capacidade máxima)}
{255}{}{[MAIS]}
{256}{}{Para ajudar osMoradores a registrar informações (as informações são extremamente valiosas, na verdade, podem
 ser a arma mais valiosa que temos contra o fim da civilização, então preste atenção!) A Vault-Tec selecionou as Industrias RobCo, criadora do RobCo Pip-Boy 2000 como o processador de informações pessoais de escolha para seus Moradores.}
{257}{}{[MAIS]}
{258}{}{O RobCo Pip-Boy 2000 é um dispositivo prático que você usa no pulso. É pequeno, especialmente para os padrões de hoje, e armazenará uma boa quantidade de informações para você. Usando gráficos modernos
 superluxuosos para começar! Consulte o manual do Pip-Boy para obter mais informações}
{259}{}{[MAIS]}
{260}{}{A chave para uma reintrodução bem-sucedida da civilização após uma guerra nuclear em grande escala são as pessoas. Aqui na Vault-Tec, estamos trabalhando para garantir que seus homens(e mulheres) estejam à altura da tarefa de trazer a América de volta dos mortos.}
{261}{}{[MAIS]}
{262}{}{Acreditamos que uma atitude positiva é uma das melhores ferramentas à nossa disposição. Se você encontrar qualquer outro morador da Vault mostrando uma atitude menos do que positiva, você é encorajado a denunciá-lo ao seu Supervisor. Lembre-se, uma vez que as portas são seladas, a palavra do Supervisor é lei.}
{263}{}{[MAIS]}
{264}{}{O Vault-13 vem preparada com o que há de mais moderno em equipamentos de sobrevivência. Os itens em seus contêineres de armazenamento durarão 1.000 pessoas em 10 anos em um ambiente confortável e moderno. Quando chegar a hora de deixar a Vault e voltar para reconstruir a América, seus amigos da Vault-Tec fornecerão tudo o que você precisar.}
{265}{}{[MAIS]}
{266}{}{Obrigado por reservar um tempo para ler o Guia de Sobrevivência do Morador da Vault (Versão Abreviada). Nós da Vault-Tec estamos confiantes de que você vai adorar sua nova residência subterrânea.}
{267}{}{Acesso a linha do tempo da Vault 13. }
{268}{}{Acesso aos registros do Supervisor.}
{269}{}{Termine a sessão.}
{270}{}{Ao ler o início da linha do tempo, você acha interessante que nenhuma razão é dada para o fato de a Vault não ter aberto 10 anos após a Grande Guerra, como foi originalmente projetado. }
{271}{}{[MAIS]}
{272}{}{Pesquisando mais, você não encontrará muito interesse até o ano de 2161, quando o único purificador de água em funcionamento da Vault quebra. Você sente uma onda de orgulho ao ler sobre seu avô ter sido selecionado para a importante tarefa de deixar a Vault e vasculhar o deserto em busca de um novo purificador de água. No entanto, parece um pouco estranho ver a lenda mais reverenciada de sua tribo contada em um formato simples de marcadores.}
{273}{}{[MAIS]}
{274}{}{Continuando na linha do tempo, você lê sobre o sucesso de seu avô e o subsequente exílio, e como vários outros moradores da Vault escolheram se juntar a ele em vez de permanecer em relativa segurança na Vault. Você também descobre que o Supervisor foi eventualmente julgado e executado pelos moradores restantes na vault.}
{275}{}{[MAIS]}
{276}{}{A entrada final na linha do tempo é datada de maio de 2242. Parece que, pela primeira vez, a Vault 13 recebeu um sinal de "tudo limpo" de uma fonte desconhecida. Depois de algum debate, os moradores da Vault decidiram abrir as portas dela e ver o que os esperava no mundo da superfície. Não há registro do que aconteceu com eles depois disso.}
{277}{}{Acesse o Guia de Sobrevivência do Morador da Vault (versão resumida). }
{278}{}{Acesso aos registros do Supervisor.}
{279}{}{Termine a sessão.}
{280}{}{Autorização necessária. Por favor, digite a senha. }
{281}{}{[VOLTAR]}
{282}{}{[Adivinha a senha]}
{283}{}{[Tenta hackear.]}
{284}{}{Termine a sessão.}
{290}{}{Incorreta. Por favor, digite a senha.}
{291}{}{[VOLTAR]}
{292}{}{[Adivinha a senha]}
{293}{}{[Tenta hackear.]}
{294}{}{Termine a sessão.}
{300}{}{Incorreta. Agora você está bloqueado para esses arquivos. A Vault-Tec pede desculpas por qualquer inconveniente.}
{301}{}{[VOLTAR]}
{302}{}{[Tenta hackear.]}
{303}{}{Termine a sessão.}
{310}{}{[Você tenta tudo o que pode pensar, mas não consegue acessar. Com um suspiro de derrota, você volta ao menu principal.]}
{311}{}{Execute o diagnóstico.}
{312}{}{Mude para o modo de entrada do teclado.}
{313}{}{Segurança de acesso ao material de arquivo.}
{314}{}{Termine a sessão.}
{320}{}{Senha correta. Todas as entradas, exceto uma, foram removidas do sistema. A entrada final nos Registros do Supervisor ainda está acessível.}
{321}{}{[Depois de vários longos minutos trabalhando com sua técnica mágica, você consegue abrir caminho até os Registros do Supervisor. No entanto, parece que todas as entradas, exceto a final, foram excluídas.]}
{322}{}{Tudo bem, vamos ver o que este Supervisor tinha a dizer. [Leia o registro.] }
{323}{}{Ah, tanto faz. [Encerrar.]}
{330}{}{É isso. Considere estas minhas palavras finais, pois duvido que viverei para escrever outra entrada. O povo da Vault falou, e eles deixaram bem claro que querem minha cabeça. Eu sabia que esse dia chegaria, desde que ELE conseguiu irritá-los fazendo o impossível. Claro, ele salvou todas as nossas vidas, mas também arruinou tudo.}
{331}{}{[MAIS]}
{332}{}{Que fique claro que tive pouca alegria em exilar nosso "grande herói", mas foi um assunto que não tive escolha. Suas aventuras no mundo exterior o mudaram demais, ele era uma ameaça muito grande para o projeto. Se eu tivesse deixado ele permanecer entre nós, ele poderia ter descoberto a verdadeira natureza das Vaults e comprometido o experimento. Mesmo que não o fizesse, pelo menos inspiraria outros a se aventurarem do lado de fora, o que seria tão ruim quanto.}
{333}{}{[MAIS]}
{334}{}{Ele simplesmente tinha que ir. Não havia outra opção. Mas mesmo isso não foi suficiente. Temo que o estrago já tenha sido feito. Permiti que seus partidários mais teimosos o seguissem para o exílio e depois tentei reafirmar meu controle sobre aqueles que permaneceram. Mas não adiantou - eu já tinha sido condenado. Que assim seja. A única coisa de que sou culpado é uma vida inteira de cumprir as exigências de nossa Grande Nação.}
{335}{}{[MAIS]}
{336}{}{Meu único arrependimento é que a Vault 13 provavelmente não concluirá o experimento social. Assim que eu for eliminado, tenho certeza de que os outros deixarão a Vault. Não imediatamente, é claro - eu os deixei com muito medo do mundo exterior. Mas, eventualmente, eles serão obrigados a superar esse medo. Tenho muito pouca fé de que a Vault 13 permanecerá fechado até 2277, como diz o experimento.}
{337}{}{[MAIS]}
{338}{}{Receio ter falhado no meu dever como Supervisor. Só posso esperar que o resto das Vaults envolvidas no Programa de Preservação Social tenham sido mais bem-sucedidos. Aos meus superiores, que tenho certeza que um dia lerão isto: perdoem-me. E que Deus abençoe a América.}
{339}{}{Procure quaisquer outros arquivos que contenham informações sobre "Programa de Preservação Social".}
{340}{}{Termine a sessão.}
{350}{}{Depois de horas vasculhando os arquivos do computador, você não consegue encontrar mais nada que mencione o Programa de Preservação Social. Ao desistir de sua busca, você promete nunca mais perder tanto tempo olhando para um monitor de computador.}
{351}{}{Termine a sessão.}
{360}{}{Depois de horas vasculhando os arquivos do computador, você consegue localizar alguns documentos ocultos sobre o Programa de Preservação Social. Ao lê-los, você descobre uma verdade bastante perturbadora sobre as Vaults: eles nunca tiveram a intenção de salvar a população dos Estados Unidos.}
{361}{}{[MAIS]}
{362}{}{Incrivelmente, todos as 122 Vaults públicos da Vault-Tec faziam parte de um grande experimento social orquestrado pelo governo dos EUA. Apenas 17 dessas Vaults, apelidados de "Vaults de Controle", foram projetados para funcionar corretamente (parece que a Vault 8 foi uma das poucas sortudas). O resto deveria ter várias falhas críticas, para que o governo pudesse estudar os ocupantes pré-selecionados e ver como eles reagiriam ao estresse das situações adversas e como eles seriam capazes de recolonizar uma vez que suas Vaults fossem abertos.}
{363}{}{[MAIS]}
{364}{}{Parece que o papel da Vault 13 no experimento era permanecer fechado por 200 anos para testar os efeitos do isolamento prolongado. Aparentemente, a quebra do purificador de água não foi intencional e forçou o Supervisor a improvisar, selecionando seu avô para sair e buscar um novo purificador. Depois de pesquisar um pouco mais, você consegue encontrar descrições de alguns dos outros experimentos da Vault.}
{365}{}{[MAIS]}
{366}{}{A porta da Vault 12 foi projetada para nunca fechar, para que os canalhas por trás desse experimento pudessem "estudar os efeitos da radiação na população selecionada". Lembrando um pouco mais sobre a lenda do seu avô, a Vault 12 estava localizado na cidade cheia de ghouls de Necropolis, onde o Morador da Vault finalmente encontrou o purificador. Parece bastante provável que os ghouls tenham sido o resultado desse experimento.}
{367}{}{[MAIS]}
{368}{}{A Vault 15, outro local chave na busca do Morador da Vault, seria habitado por pessoas com "ideologias radicalmente diversas" que seriam seladas na Vault juntas por 50 anos. A Vault 27 deveria ser propositadamente superlotado com 2.000 pessoas - o dobro da capacidade máxima, isso não poderia dar certo. A Vault 29 deveria ser preenchido apenas por menores de dezesseis anos, com seus pais "propositadamente redirecionados para outras Vaults".}
{369}{}{[MAIS]}
{370}{}{O experimento da Vault 34 envolveu abastecer um arsenal com armas e munição e, é claro, sem fechadura, que coisa meiga. A Vault 36 sofria de déficit de alimentos, e foi projetada para produzir apenas "um mingau ralo e aguado", enquanto a Vault 42 foi equipada apenas com iluminação fraca - nenhuma lâmpada de mais de 40 watts foi fornecida.}
{371}{}{[MAIS]}
{372}{}{O equipamento da Vault 53 foi projetado para quebrar a cada poucos meses. Embora reparáveis, as constantes avarias serviam para testar o estresse dos habitantes. Você se pergunta quantos mecânicos e técnicos especializados aquela Vault produziu. A Vault 55 teria todas as suas fitas de entretenimento removidas, enquanto a Vault 56 também teria todas as suas fitas de entretenimento removidas, com exceção de uma apresentando um humorista da Globo.}
{373}{}{[MAIS]}
{374}{}{A Vault 68 deveria ser ocupado por 999 homens e apenas uma mulher (PQP). Imagine os horrores que aconteceram lá... A Vault 69, por outro lado, seria ocupada por 999 mulheres e apenas um homem... interessante. As extrusoras de macacão do Vault 70 foram projetados para falhar após 6 meses. E, finalmente, a Vault 106 foi projetado para que, 10 dias após ser selado, começasse a "liberar drogas psicoativas no sistema de filtragem de ar".}
{375}{}{Termine a sessão.}
{500}{}{Você aprende sobre os Experimentos das Vaults e suas respectivas funções.}
{510}{}{Você aprende sobre a história da Vault 13 e o papel do Supervisor nos Experimentos das Vaults.}
{520}{}{Me desculpe, eu não entendi isso.}
{521}{}{Termine a sessão.}
{2541}{}{Espessura da porta: 4 jardas, aço
                                       Cobertura da Terra: 3.200.000 toneladas de solo, a 200 pés
           Sistema de controle de computador: máquina de pensar
                          Fonte de alimentação primária: geotérmica
                                Fonte de alimentação secundária: Sistemas de backup da General Atomics de Energia Nuclear
                                                         Requisitos de energia: 3,98mkw/dia
                                 Lojas: Equipamentos de construção completos, fazendas hidroagrícolas, sistema de purificação de água de rio subterrâneo,
 armamento defensivo para equipar 10 homens, arquivos de comunicação, sociais e de entretenimento (duração total)}
