{100}{}{Você vê uma pessoa abatida vestindo trajes de vault.}
{101}{}{Você vê um prisioneiro do Vault 13.}
{102}{}{Você vê uma pessoa muito pálida vestindo os trajes do Vault 13.}
{103}{}{Você vê uma pessoa da sua tribo.}
{104}{}{Você vê uma pessoa conhecida da sua tribo.}
{105}{}{Você vê uma pessoa da sua tribo, eles não parecem bons.}
{106}{}{Este local está muito enferrujado pra ser um vault.}
{107}{}{Acho que posso ouvir o oceano. }
{108}{}{Você falou com Martin Frobisher?}
{109}{}{Você deveria falar com o Martin.}
{110}{}{Martin é o nosso porta-voz, você deveria falar com ele.}
{111}{}{O sr. Frobisher está na primeira cela.}
{112}{}{Eles não tem nem fitas de entretenimento por aqui.}
{113}{}{Eu exijo falar com alguém sobre a qualidade da comida.}
{114}{}{Ótimo, agora eles nos ameaçam com selvagens estranhos.}
{115}{}{Você escapou?}
{116}{}{Como você saiu?}
{117}{}{Você se parece com o Chosen One.}
{118}{}{Você é- você é o Chosen One?}
{119}{}{Você deveria falar com a Elder.}
{120}{}{A Elder disse que você nos salvaria!}
{121}{}{Você já conversou com o Ancião?}
{122}{}{A Elder está na primeira cela. Você deveria falar com ela.}
{123}{}{Fale com a Elder.}
{124}{}{Livre-nos!}
{125}{}{Tira a gente daqui.}
{126}{}{Eu não suporto mais essas paredes.}
{127}{}{Eu gostaria muito de sentir o vento em meu rosto mais uma vez.}
{128}{}{Liberta a gente, Chosen One!}
{129}{}{O Chosen One está aqui!}
{130}{}{Solta a gente!}
{131}{}{Faça o que a Elder mandar.}
{132}{}{Tira a gente daqui antes que os maus espíritos voltem!}
{133}{}{Por favor, ajuda a gente, Chosen.}
{134}{}{Graças aos deuses, o Chosen One finalmente chegou.}
{135}{}{Ajuda a gente }
{136}{}{Liberta a gente }
{137}{}{Você está aqui, }
{138}{}{Você sabe o que fazer, então faça!}
{139}{}{Anda logo!}
{140}{}{Tira a gente daqui.}
{141}{}{Desligue a energia!}
{142}{}{Solta a gente.}
{143}{}{Vai, tira a gente daqui!}
{144}{}{Por favor, ajude-nos!}
{145}{}{Você é a nosso única esperança!}
{146}{}{Por favor, eu não agüento mais.}
{147}{}{Eu não quero tomar mais medicamentos. Não, não. Nãooooo!}
{148}{}{Os espíritos nos protegem!}
{149}{}{Onde estão os espíritos quando se precisa deles?}
{150}{}{Ajude-nos!}
{151}{}{Livre-nos!}
{152}{}{Eu quero ir pra casa.}
{153}{}{Primeiro a seca e agora isso.}
{154}{}{Chega de agulhas, chega!}
{155}{}{Eu não suporto isso! As paredes estão se fechando contra mim!}
{156}{}{(soluços, soluços)}
{157}{}{Deixe o meu povo partir!}
{158}{}{A Elder nos guia.}
{159}{}{Como nós ofendemos esses espíritos maus?}
{160}{}{Eu não ligo pra isso.}
{161}{}{Onde está o Martin?}
{162}{}{Isso realmente não é um vault.}
{163}{}{Tira a gente daqui!}
{164}{}{Olá? Olá!}
{165}{}{Eu vou insistir até ser libertado.}
{166}{}{Eu sou um cidadão dos Estados Unidos e exijo ver quem está no comando.}
{167}{}{Me deixa sair.}
{168}{}{Isso é tão chato.}
{169}{}{Chega de medicamentos. Eu não agüento mais.}
{170}{}{Eles não podem nos manter aqui pra sempre.}
{171}{}{A guerra não acabou?}
