{100}{}{Você vê um homem calvo em um bata de laboratório.}
{101}{}{Você vê Tom Murray, o chefe da Comissão de Energia Atômica.}
{102}{}{Você vê um velho muito nervoso em um jaleco imaculado.}
{103}{}{Minha máquina! Minha bela máquina se foi. (Soluço, soluço.)}
{104}{}{Estamos condenados.}
{105}{}{Sem o computador conectado, o reator vai derreter!}
{106}{}{Eu não sei nem nadar.}
{107}{}{Talvez eu possa consertá-lo...}
{108}{}{Por que o alarme está tocando?}
{109}{}{O que está acontecendo aqui?}
{110}{}{Não entre em pânico, ninguém. NÃO ENTRAR EM PÂNICO!!!!!!!!!!!!}
{111}{}{Certo, fiquem calmos. }
{112}{}{Talvez seja apenas um exercício.}
{113}{}{Volte para o nível de detenção.}
{114}{}{Você realmente pode notar a diferença.}
{115}{}{Sua testa incha terrivelmente.}
{116}{}{Você tem pouca capacidade craniana para fazer isso, né?}
{117}{}{Se você estiver bem, vou garantir que você receba um biscoito quando voltar para sua cela.}
{118}{}{Você aí, você não deveria usar essas coisas aqui.}
{119}{}{Eu vou usar minha armadura onde eu quiser}
{120}{}{Desculpe, senhor. Estou indo então.}
{121}{}{Você vai, eh? Bem, eu vou ter que te denunciar.}
{122}{}{Vá em frente, alegre meu dia.}
{123}{}{Ah, por favor, não faça isso, estou saindo agora. Tchau.}
{124}{}{Sou Tom Murray, chefe da Comissão de Energia Atômica, eu controlo nossa usina atômica aqui. E quem seria você e o que está fazendo aqui?}
{125}{}{Que diabos você quer agora?}
{126}{}{Preciso desligar seu reator atômico.}
{127}{}{Só estava curioso para saber como funciona o seu reator.}
{128}{}{Preciso te exterminar.}
{129}{}{Socorro! Me ajudem! Socorro!}
{130}{}{Intruso! Alerta!}
{131}{}{Corra por suas vidas! Os primitivos se soltaram!}
{132}{}{Guardas! Socoooooorrroooo!}
{133}{}{Alerta de intrusão! Alerta de intrusão!}
{134}{}{Desligar isso? Esta ficando maluco? Você não vai desligar o *meu* reator.}
{135}{}{Sim, eu vou. É melhor me dizer como, ou te mato aqui mesmo.}
{136}{}{Eu falei em desligar? Desculpe, só queria saber como funciona o seu reator.}
{137}{}{Ah, é seu? Me desculpe, eu não percebi isso. Bem, adeus então.}
{138}{}{Ok, eu faço isso por você. Mas se você tentar desligar muito rapidamente, ele vai superaquecer.}
{139}{}{Eu não me importo com isso. Apenas desligue o reator, ou te estripo como um peixe.}
{140}{}{Isso me parece perigoso. Bem, ok, apenas esqueça, tchau.}
{141}{}{Você está blefando, você não ousaria.}
{142}{}{Sim, eu faria. Se você não me ajudar, vai ser um homem morto.}
{143}{}{Tentei fazer você cooperar, mas não quis saber. Então, não posso deixar você soar o alarme. }
{144}{}{Ei, eu só estava brincando. Como funciona o seu reator?}
{145}{}{Yeah, I guess you're right. You better just keep quiet for a while after I'm gone though. Goodbye.}
{146}{}{Okay, okay. I'll do it. Just take it easy now. But I'm telling you - it's going to overheat as soon as I put the containment rods down. If we perform a crash shutdown like this we'll have to scram the whole reactor-or we better learn to speak Chinese.}
{147}{}{Yeah, whatever. Just shut the damn thing down right now!}
{148}{}{That sounds dangerous. Maybe I better look for another way. I sure don't want to hurt anything here. Goodbye.}
{149}{}{I'm not going to risk the lives of everyone here. No way. }
{150}{}{I'm sorry to hear that. I guess I'll have to kill you then. Nothing personal.}
{151}{}{How would that risk everyone's life? How does your reactor work anyway?}
{152}{}{I guess I'll just have to find another way to shut down the power. You better not make any noise after I'm gone. Goodbye.}
{153}{}{You got it. Okay, uh, slide this to green. (He fiddles with a control panel for a few minutes while he mutters to himself.) Okay, you got it, but it sure isn't going to stay stable for very long.}
{154}{}{You did the right thing. Now, I've got to be going. You better just keep quiet in here for a while.}
{155}{}{Good job. Now, I've got to kill you. Sorry, but I can't leave any witnesses.}
{156}{}{I've got to be going. Goodbye.}
{157}{}{I don't control that much of the reactor's operation. The central computer just north of the reactor controls most of the power plant functions. If that weren't there, we'd have no power at all.}
{158}{}{No power at all?}
{159}{}{Well, not enough for much. The lights, life-support, and defenses would work for a while but forcefields and other power intensive devices would be shut down immediately.}
{160}{}{Sounds as though you'd really be crippled.}
{161}{}{Well, it wouldn't be good. All kinds of watertight security doors close when that happens. No way in the world to open them once they're closed by the power shut-off. That's a safety feature.}
{162}{}{Interesting. There's something else I wanted to know though.}
{163}{}{That's all I need to know. Thanks you've been a big help. You just better keep quiet after I leave.}
{164}{}{Thanks. Too bad you won't live to see that. Goodbye.}
