{100}{}{Você vê uma secretária loira e gorduchinha em um vestido justo.}
{101}{}{Você vê a secretário particular e *pessoal* do presidente.}
{102}{}{Você vê uma estagiária gordinha, gostosinha, uh, secretária. Seu cabelo está um pouco bagunçado.}
{103}{}{Sim? O que você quer, meu bem?}
{104}{}{De novo não, acabei de limpar meu vestido.}
{105}{}{Então, o que o Sr. Importante está fazendo?}
{106}{}{Eles não o chamam de *Dick* Richardson atoa.}
{107}{}{Eu também sei digitar.}
{108}{}{Você deveria bater antes de entrar assim.}
{109}{}{Preciso de um enxaguante bucal.}
{110}{}{Onde está aquela toalha?}
{111}{}{Acho que está na hora de um aumento.}
{112}{}{Esses agentes do Serviço Secreto sempre precisam pairar assim?}
{113}{}{Volte mais tarde. Estou meio ocupada.}
{114}{}{Acho que não vou lavar este vestido, vão pegar nele de novo.}
{115}{}{O presidente diz que meu beijo é o melhor.}
{116}{}{Você não está me gravando, está?}
{117}{}{Onde estão minhas joelheiras? Heh, heh, apenas brincando.}
