{100}{}{Você vê um terminal.}
{101}{}{Você vê um terminal. Parece estar operacional.}
{102}{}{Você vê um DataPlex 2000 SmarTerminal, com 64k de RAM, é o que há de mais moderno em tecnologia de computadores - pena que não está funcionando agora.}
{103}{}{Você vê um DataPlex 2000 SmarTerminal, com 64k de RAM, é o que há de mais moderno em tecnologia de computadores.}
{104}{}{Bem-vindo ao PoseidoNet. Entrar na seleção do menu:}
{105}{}{Entrar.}
{106}{}{Ajuda.}
{107}{}{Terminar Sessão.}
{108}{}{Este terminal está passando um filme indiano, mas é muito chato.}
{109}{}{Este terminal está reproduzindo um programa sobre tiro ao alvo. Tudo o que você pode ver é um alvo.}
{110}{}{Este terminal mostra algum tipo de arte moderna - alguns trabalhos com muitas cores diferentes e listras.}
{111}{}{Você vê um terminal. Ele mostra pequenas bombas verdes movendo-se diagonalmente pela tela.}
{112}{}{Este terminal tem uma mensagem nele, "Agora é seguro desligar o computador." Você gostaria de saber o que isso significa.}
{113}{}{Você vê uma imagem em vermelho, verde e azul, pontinhos de luz combinados para formar uma imagem de alguma coisa...}
{114}{}{Tem um rosto horrível te olhando. Oh, espera ai, o terminal está desligado.}
{115}{}{Esta janela leva a uma dimensão escura além do tempo e do espaço.}
{116}{}{Este terminal contém uma mensagem; "Carregando Fenestra '98." O terminal está coberto por uma espessa camada de poeira.}
{117}{}{Este parece ser um terminal da marca Apricot. Está executando algo chamado Fallout 3. Parece bem capenga, nem história boa tem. Tomara que tenha mods pra melhorar.}
{118}{}{Insira a ID do usuário:}
{119}{}{(Deixe-me tentar isso) Listar usuários.}
{120}{}{(Sera que isso vai funcionar?) Smith, J.}
{121}{}{Voltar.}
{123}{}{Acho melhor fazer isso em outro lugar.}
{124}{}{Listagem (o terminal exibe uma lista de cerca de 500 nomes).}
{125}{}{Listagem (o computador exibe uma lista de nomes).}
{126}{}{Selecione ID de Usuário ou Desconectar:}
{127}{}{(Este tem acesso aceitável.) Smith, J.}
{128}{}{(Este parece ser especial.) Senha Presidencial - Substituição de Segurança.}
{129}{}{(Isto é melhor do que o acesso mediano.) Murray, T.}
{130}{}{(Este tem um bom acesso.) Curling, Dr. C.}
{131}{}{(Este parece ter um acesso muito bom.) Bird, D.}
{132}{}{(Talvez eu tente isso mais tarde.) Finalizar seção.}
{133}{}{Selecione: }
{134}{}{A. E. C.: Operações da usina de energia atômica, }
{135}{}{Estado de segurança?}
{136}{}{Baixar A. E. C.: Operações de usinas de energia atômica.}
{137}{}{Status de segurança.}
{138}{}{Voltar para a ID do usuário:}
{139}{}{Selecione: }
{140}{}{Nível de segurança: Status atual, }
{141}{}{Corpo Químico: Relatório de Status do Projeto, }
{142}{}{A. E. C.: Operações da usina de energia atômica, }
{143}{}{Estado de segurança?}
{144}{}{Segurança/Nível: Status Atual}
{145}{}{Baixar Corpo Quimico: Relatório de status do projeto.}
{146}{}{Baixar A. E. C.: Operações de usinas de energia atômica.}
{147}{}{Status de segurança.}
{148}{}{Voltar para a ID do usuário:}
{149}{}{Selecione: }
{150}{}{Estado da Nação: Situação Atual, }
{151}{}{Lista de palavras, }
{152}{}{Nível de segurança: Status atual, }
{153}{}{Corpo Químico: Relatório de Status do Projeto, }
{154}{}{A. E. C.: Operações da usina de energia atômica, }
{155}{}{Estado de segurança?}
{156}{}{Estado da Nação: Situação Atual}
{157}{}{Baixar lista de palavras.}
{158}{}{Segurança/Nível: Status Atual}
{159}{}{Baixar Corpo Quimico: Relatório de status do projeto.}
{160}{}{Baixar A. E. C.: Operações de usinas de energia atômica.}
{161}{}{Status de segurança}
{162}{}{Voltar para a ID do usuário:}
{163}{}{Selecione: Status de segurança?}
{164}{}{Status de segurança}
{165}{}{Final de acesso.}
{166}{}{Falha no download - Arquivo de Status de Segurança ausente.}
{167}{}{Estado da Nação: Situação Atual}
{168}{}{Baixar lista de palavras.}
{169}{}{Segurança/Nível: Status atual.}
{170}{}{Baixar Corpo Quimico: Relatório de status do projeto.}
{171}{}{Baixar A. E. C.: Operações de usinas de energia atômica.}
{172}{}{Voltar para a ID do usuário:}
{173}{}{Download completo.}
{174}{}{Baixar lista de palavras.}
{175}{}{Segurança/Nível: Status atual.}
{176}{}{Baixar Corpo Quimico: Relatório de Status do Projeto}
{177}{}{Baixar A. E. C.: Operações de Usina de Energia Atômica}
{178}{}{Status de segurança.}
{179}{}{Voltar para a ID do usuário:}
{180}{}{Download completo.}
{181}{}{Estado da Nação: Situação Atual}
{182}{}{Segurança/Nível: Status atual.}
{183}{}{Baixar Corpo Quimico: Relatório de Status do Projeto}
{184}{}{Baixar A. E. C.: Operações de Usina de Energia Atômica}
{185}{}{Status de segurança.}
{186}{}{Voltar para a ID do usuário:}
{187}{}{Nível do Quartel de Guarda: Torretas de segurança atualmente em status de alerta armado.}
{188}{}{Nível do Quartel de guarda: Torres de segurança atualmente em status Normal.}
{189}{}{Nível Quartel de Guarda: Torretas de segurança atualmente com status de Manutenção Desativada.}
{190}{}{Teste de Nível de Célula do Sujeito: Torretas de segurança atualmente em estado de Alerta Armado.}
{191}{}{Teste de Nível de Célula do Sujeito: Torretas de segurança atualmente em status Normal.}
{192}{}{Nível de Sujeito de Teste: Torretas de segurança atualmente com status de Manutenção Desativada.}
{193}{}{Área do Projeto de Pesquisa e Desenvolvimento: Torretas de segurança atualmente em estado de Alerta Armado.}
{194}{}{Área do Projeto de Pesquisa e Desenvolvimento: Torretas de segurança atualmente em status Normal.}
{195}{}{Área do Projeto de Pesquisa e Desenvolvimento: Torres de segurança atualmente em status Desativado para Manutenção.}
{196}{}{Área do Escritório Executivo: torres de segurança atualmente em estado de Alerta Armado.}
{197}{}{Área do Escritório Executivo: Torres de segurança atualmente em status Normal.}
{198}{}{Área do escritório executivo: torres de segurança atualmente com status de Desativada para Manutenção.}
{199}{}{Nível de Informação e Usina: Torres de segurança atualmente em status de Alerta Armado.}
{200}{}{Nível de Informação e Usina: Torretas de segurança atualmente em estado Normal.}
{201}{}{Nível de Informação e Usina: Torretas de segurança atualmente com status de Desativadas para Manutenção.}
{202}{}{Ajustar o nível de segurança.}
{203}{}{Estado da Nação: Situação atual}
{204}{}{Baixar lista de palavras.}
{205}{}{Baixar Corpo Quimico: Relatório de status do projeto.}
{206}{}{Baixar A. E. C.: Operações de usinas de energia atômica.}
{207}{}{Estado de segurança.}
{208}{}{Voltar para a ID do usuário:}
{209}{}{Download completo.}
{210}{}{Baixar Estado da Nação: Status atual.}
{211}{}{Baixar lista de palavras.}
{212}{}{Segurança/Nível: Status Atual}
{213}{}{Baixar A. E. C.: Operações de usinas de energia atômica.}
{215}{}{Status de segurança.}
{216}{}{Voltar para a ID do usuário:}
{217}{}{Download completo.}
{218}{}{Baixar Estado da Nação: Status atual.}
{219}{}{Baixar lista de palavras.}
{220}{}{Segurança/nível: Status atual}
{221}{}{Baixar Corpo Quimico: Relatório de status do projeto.}
{222}{}{Estado de segurança.}
{223}{}{Voltar para a ID do usuário:}
{224}{}{Este terminal atualmente está executando um diagnóstico profundo, tente outro terminal. Obrigado.}
{225}{}{Bem vindo ao sistema de ajuda PoseidoNet. Lamentamos que seus arquivos de ajuda estejam desatualizados e indisponíveis. Buscar atualização de arquivo de ajuda? (S/N)}
{226}{}{Sim.}
{227}{}{Não, atrás.}
{228}{}{A atualização do arquivo de Ajuda do usuário não está disponível com o software PoseidoNet de avaliação. Adquira a versão completa para acesso total a todas as atualizações adicionais. Seu período de teste para acesso ao PoseidoNet está atrasado há 59.439 dias.}
{229}{}{Retornar ao log.}
{230}{}{Finalizar seção.}
{231}{}{A substituição de segurança requer uma senha somente presidencial. Opções permitidas: Contra-Insurgência, Desligamento de Emergência dos Sistemas Defensivos.}
{232}{}{(Vou dar uma olhada neste.) Contra-insurgência.}
{233}{}{(Vou dar uma olhada neste.) Desligamento de Emergência dos Sistemas Defensivos.}
{234}{}{(Talvez eu deva tentar algo menos chamativo) Retorne à ID do usuário.}
{235}{}{(Acho que não quero mexer com isso agora.) Faça logoff.}
{236}{}{Contra-Insurgência. No caso de uma rebelião armada, o Cartão de Segurança Presidencial permite que os sistemas defensivos sejam ativados em todas as unidades anteriormente leais, mas agora ameaçadoras dentro de uma área. Os sistemas defensivos são programados para atacar primeiro o inimigo mais perigoso. Aviso! Nível operacional atual - apenas níveis de entrada!}
{237}{}{(Isso parece útil.) Ative o Protocolo de Contra-Insurgência.}
{238}{}{(Talvez eu tente em outra oportunidade.) Volte.}
{239}{}{(Não quero mais mexer com o computador agora.) Faça logoff.}
{240}{}{Senha de Segurança Presidencial reconhecida. Bom dia, Sr. Presidente.... Protocolo de emergência Contra-Insurgência iniciado... Alvo adquirido.}
{241}{}{(Acho que vou voltar para ver o que acontece).}
{242}{}{Senha de Segurança Presidencial reconhecida. Bom dia, Sr. Presidente.... Protocolo de Contra-Insurgência de Emergência iniciado...**Avaria**... Link de segurança offline neste nível. Envie o formulário FG-I-106-32-0635 para autorizar os serviços de reparo. Obrigado por usar outro excelente produto Vault-Tec. Bom dia.}
{243}{}{(Talvez funcione nos níveis de entrada. Hmm, isso deve significar a área logo antes do cais. Terei que tentar lá.) Volte para a ID do usuário.}
{244}{}{(O que mais que posso tentar?) Volte.}
{245}{}{Cartão de acesso de segurança presidencial necessário para acessar esta função. Cartão-chave não encontrado.}
{246}{}{(O que mais que posso tentar?) Volte.}
{247}{}{O desligamento dos Sistemas Defensivos de Emergência desliga temporariamente os sistemas de segurança ativos nível a nível. O desligamento inicia um procedimento de diagnóstico profundo antes de iniciar a reinicialização automática dos sistemas de segurança.}
{248}{}{(Isso parece bom para eu tentar.) Ative o desligamento de emergência dos sistemas defensivos.}
{249}{}{(Hmm, talvez eu tente isso em outro momento.) Volte.}
{250}{}{(Não quero mais mexer com o computador agora.) Faça logoff.}
{251}{}{Senha de Segurança Presidencial reconhecida. Bom dia, Sr. Presidente.... Desligamento de Emergência dos Sistemas Defensivos iniciado... Realizando diagnóstico profundo. Alfa....Bravo....Charlie....}
{252}{}{(Por alguma estranha razão, acho que não quero fazer isso agora.) Volte.}
{253}{}{(É melhor eu me apressar, enquanto essa coisa ainda está rodando esse diagnóstico). Saia.}
{254}{}{Senha de Segurança Presidencial não reconhecida. Acesso negado.}
{255}{}{(Hmm, me pergunto se posso enganar o scanner o fazendo pensar que tenho a chave invadindo o arquivo de acesso. Acho que vou tentar.)}
{256}{}{(Bem, valeu a pena tentar.) Volte.}
{257}{}{Foi detectado mau funcionamento na Chave de Acesso ao Scanner ... Reiniciando o scanner...}
{258}{}{(Essa é a minha chance, agora se eu conseguir o fazer pensar que reconheceu a Chave Presidencial...)}
{259}{}{(Droga, bem, nada arriscado...) Volte.}
{260}{}{Scanner reinicializado. Redigitalizando...}
{261}{}{(Aqui está o grande momento.) - Você digita febrilmente.}
{262}{}{Procedimento ilegal detectado. Mais acesso a este terminal foi negado... Alerta de manutenção enviado.}
{263}{}{Droga. não era isso que eu queria.}
{264}{}{Senha de Segurança Presidencial reconhecida. Bom dia, Sr. Presidente. (Sim! Agora vamos ver o que posso fazer...)}
{265}{}{(O que mais eu posso fazer?)}
{266}{}{Senha de Segurança Presidencial reconhecida. Bom dia, Sr. Presidente... Protocolo de Contra-Insurgência de Emergência iniciado... **Erro** Alvo não encontrado. Certifique-se de que os sensores estão funcionando corretamente. Caso contrário, envie o formulário FG-I-106-32-0635 para autorizar os serviços de reparo. Obrigado por usar outro excelente produto Vault-Tec. Bom dia.}
{267}{}{(Hmm... Talvez funcione assim que houver alguém realmente lá. Terei que tentar mais tarde.) Voltar para o ID de usuário.}
{268}{}{(O que mais que posso tentar?) Volte.}
