{100}{}{Você vê um miserável deformado.}
{101}{}{Você vê Rattray, o assistente corcunda do Dr. Johnson.}
{102}{}{Você vê um miserável, torto, corcunda e aleijado e com um caso grave de caspa.}
{103}{}{Ratt limpa muito bem, doutor.}
{104}{}{Seu pedaço de carne desprezível. }
{105}{}{Ratt tenta ajudar muito.}
{106}{}{Não sei por que tolero sua incompetência.}
{107}{}{Ratt sente muito, Ratt ser melhor.}
{108}{}{Que seja melhor, ou você vai pra rua novamente... estou sendo muito gentil.}
{109}{}{Não Doutor, não coloque Ratt para fora! Rat ser bom. Ratt promete.}
{110}{}{Ok, então eu quero ver você limpando tudo. Estou te avisando.}
{111}{}{Ratt ser muito bom. Rat não tem problemas. }
{112}{}{Sim, bem, cuide para que suas tarefas sejam feitas.}
{113}{}{Ratt limpa e limpa. Come todos os insetos ruins. Deixa casa limpa.}
{114}{}{E mais uma coisa, não quero ver você toda hora comendo esses besouros, ou baratas, ou sei lá o quê.}
{115}{}{O doutor não quer que Ratt se livre dos insetos? Ok, Ratt guarda bons insetos para o Doutor comer.}
{116}{}{Eu não quero comê-los, idiota! Só não quero ver você comê-los.}
{117}{}{Ratt não comer bichos?}
{118}{}{Isso mesmo, NÃO COMA INSETOS NA MINHA FRENTE. Eu não suporto mais essa coisa asquerosa.}
{119}{}{Ratt só chupa casquinhas crocantes então?}
{120}{}{NÃO! Não quero você mastigando insetos, chupando, lambendo ou qualquer outra coisa.}
{121}{}{Ratt não come insetos. Ratt cuida bem dos insetos do Doutor.}
{122}{}{Bem, agora que resolvemos isso... você limpou as prateleiras?}
{123}{}{Sim, doutor, Ratt limpa todas as prateleiras bonitas do doutor. Boas prateleiras, todas limpas.}
{124}{}{Muito bem, então. E o chão? Parece sujo.}
{125}{}{Ratt esfrega o chão de novo para o bom doutor. Não quero chão sujo para médico limpo.}
{126}{}{Hmm, suponho que você pensa que pode ficar deitado agora. É isso?}
{127}{}{Não Doutor, não, Ratt não faz isso de novo. Rat lembra.}
{128}{}{Apenas cuide para se manter ocupado, ou vou chicoteá-lo novamente. }
{129}{}{NÃO! Doutor, nada de chicote em Ratt. Ratt ser bom agora.}
{130}{}{Entenda isso: eu não gosto disso, mas você precisa de disciplina, Rattray. E precisa muito.}
{131}{}{Sim, doutor. O médico sempre sabe o melhor para Ratt.}
{132}{}{Contanto que você se lembre disso, Rattray. Deus sabe por que me preocupo tanto com você.}
{133}{}{Doutor bom homem, muito bom homem.}
{134}{}{Sim, suponho que sim, sem dúvida.}
{135}{}{I works 'ere for the Doctor.}
{136}{}{I clean up. Hokay?}
{137}{}{Heh, heh, heh. I found something to eat.}
{138}{}{I found a roach. Yummy.}
{139}{}{You want yummy roach to eat too? Ratt share.}
{140}{}{Doctor take good care of Ratt.}
{141}{}{Ratt bad but nice Doctor take good care of him anyway.}
{142}{}{Ratt always so stupid. Why me so stupid?}
{143}{}{Ratt sorry. Me no understand what you want.}
{144}{}{Doctor say Ratt not to talk to visitors.}
{145}{}{Ratt not say anything.}
{146}{}{Ratt not get in way. Ratt want help.}
{147}{}{You know where Doc go?}
{148}{}{Ratt not see Doc in longtime.}
{149}{}{Doc gone, Ratt sad.}
{150}{}{Who take care of Ratt now?}
{151}{}{Ratt keep house nice until Doctor back.}
