{100}{}{You see a dumpy-looking bald guy, polishing a glass.}
{101}{}{It's the bartender.}
{102}{}{He's a gruff-looking guy with a crooked nose and pinched up ears like he might have been a boxer years ago.}
{103}{}{What can I get you?}
{104}{}{Diga, foi você que fez Jack desistir, não foi? Esse foi um bom trabalho. Então o que você quer?}
{105}{}{Com certeza.}
{106}{}{Bebida.}
{107}{}{Quem é o grandalhão ali?}
{108}{}{O que tem para fazer nesta cidade?}
{109}{}{Adeus.}
{110}{}{Esse é Hoss, o filho da presidente Tandi. É um problema quando está bebendo, então eu ficaria longe dele se eu fosse você.}
{111}{}{Era Hoss, filho da presidente Tandi. Rapaz, você com certeza ama a bunda dele!}
{112}{}{President Tandi?}
{113}{}{Tough guy, eh? Thanks.}
{114}{}{Not much. If you're looking for trouble, go drink someplace else, like the Rawhide. If you're looking for work, there's the Westin place west of town. Heard some things about President Tandi looking for a specialist, too.}
{115}{}{Specialist?}
{116}{}{President Tandi?}
{117}{}{Obrigado.}
{118}{}{Daughter of President Aradesh, the guy who founded NCR. She's been president for years. Does a good job too.}
{119}{}{And she's looking for a specialist? What kind?}
{120}{}{Who's the big guy?}
{121}{}{Obrigado.}
{122}{}{Don't know. Gunther, her aide, probably does. He's down at the Hall of Congress.}
{123}{}{Who's the big guy?}
{124}{}{Obrigado.}
{125}{}{Would you like a drink?}
{126}{}{Com certeza.}
{127}{}{Não.}
{128}{}{Let me buy you a drink! I've been wanting to smack him around for years!}
{129}{}{I've got some questions.}
{130}{}{Good! Bye.}
{131}{}{Boy, you sure whooped Hoss's ass good! What can I get you?}
