{100}{}{Você vê um mutante, parece ser do tipo sociável.}
{101}{}{Esse é Lenny, lembra? O desagradável.}
{102}{}{Hoo, rapaz, esse tem tudo que precisa. Além de ser verde e feio, ele tem mais cicatrizes do que uma puta velha. É um lutador, com certeza.}
{103}{}{Eu sou Lenny e você é a escória do lago. Saia daqui.}
{104}{}{Por que está incomodando Lenny, seu vermezinho?}
{105}{}{O que você quer com Lenny, humano inútil?}
{106}{}{Continue com graça e você vai contar ao seu criador que Lenny te enviou.}
{107}{}{Prazer em te conhecer. Eu sou Lenny... você deve ser um idiota. Há, há!}
{108}{}{Diga ao seu mestre mutante que meu nome é Lenny, escravo.}
{109}{}{Ei, irmão mutante, Lenny quer saber por que você anda com esse verme humano?}
{110}{}{Lenny não fala com ninguém. Faz mutantes de escravos, escoria.}
{111}{}{Lenny diz que você e seu mutante chupador de rola, Tom, podem ir para a puta que pariu.}
{112}{}{Atenção. Lenny não é um mutante sociável como o que você tem agora.}
{113}{}{Ei, o pequeno rosto pálida está de volta!}
{114}{}{Saia daqui, humano.}
{115}{}{Some daqui, vagabundo.}
{116}{}{Qual é o problema? Precisa de alguém para trocar sua fralda?}
{117}{}{Você é tão esperto quanto uma pilha de tijolos, humano.}
