{100}{}{Você vê um homem corpulento e bem vestido se movendo com lentidão deliberada.}
{101}{}{É Merk - as pessoas por aqui o chamam de O Homem.}
{102}{}{Esse sujeito tem um ar de frieza e arrogancia, como se ele não visse diferença entre você e a mosca que acabou de esmagar entre os dedos.}
{103}{}{Hey, I've seen you in the movies! Come to show me some action, have you?}
{104}{}{Whaddya mean, disturbing my peace like this? Get outta here.}
{105}{}{Excuse me, I got business to conduct.}
{106}{}{You wanna talk business, see me at the Rawhide. Otherwise leave me alone.}
{107}{}{I've seen you on the silver screen, ain't I? You got impressive, uh, credentials.}
{108}{}{You got that certain look in your eyes. Stop by the Rawhide - I could always use somebody like you.}
{109}{}{Shit, what's that smell? Something just walked into the room.}
{110}{}{Vá buscar outro uísque, e rápido.}
{111}{}{Não tenho tempo agora.}
{112}{}{Eu sou um convidado aqui, pare de me incomodar.}
{113}{}{Ei, boneca, você é muito gostosinha. O gosto de Carlson está melhorando.}
{114}{}{Eu não faço negócios aqui.}
{115}{}{Eu não te conheço. Sou um homem de negócios respeitável.}
{116}{}{Ora, se não é o covarde. Vá em frente e me deixe em paz.}
{117}{}{Então, resolveu me procurar afinal, né, amor?}
{118}{}{Eu não sei nada sobre nada, entenda.}
{119}{}{O Veep não vai gostar que você incomode os convidados dele.}
{120}{}{Excelente licor que é servido aqui.}
{121}{}{Saia do meu caminho!}
{122}{}{Se queres falar com alguém, compre um amigo na Shopee.}
{123}{}{Não dou instruções nem devolvo o troco. Saia.}
{124}{}{O que é isso? Hora de socializar?}
{125}{}{Eu sou Merk. O que você quer?}
{126}{}{Você novamente?}
{127}{}{Bem, seja educado, punk, ou isso pode ficar feio.}
{128}{}{Oort.}
{129}{}{Estou procurando trabalho.}
{130}{}{Segundo as fontes, você é o homem certo para fazer negócios, se é que me entende.}
{131}{}{Dizem que você é o homem que roubou meu carro.}
{132}{}{Estou buscando informação.}
{133}{}{Alguns dizem que você pode saber algumas coisinhas sobre, vejamos, coisas que faltam em carros.}
{134}{}{Você de novo? O trabalho está feito?}
{135}{}{Glub.}
{136}{}{Não.}
{137}{}{Eu tenho algumas perguntas.}
{138}{}{Hum... Forte. Burro... Se você quer um emprego, fale com Mira. Entende? Mi-ra. Por ali.}
{139}{}{Like making noises? Will somebody get this brahmin turd out of here?}
{140}{}{Are you that stupid? You think I'm just gonna hire anybody? You work for me, you got to prove you're good for something.}
{141}{}{How about I just shoot Lenny, there? He deserves it.}
{142}{}{Prove like how?}
{143}{}{You know anybody who'd like some Jet, maybe?}
{144}{}{Listen, I'm}
{145}{}{Right. Like I got to prove myself to you. Forget you, slugwort.}
{146}{}{It was that goddamn Doofus, wasn't it? That little junkie talks too much for his own good. Tell you what - you cap him for me -- call it a favor -- and then we'll talk.}
{147}{}{Deal.}
{148}{}{Whoa - I'm not that cold-blooded!}
{149}{}{And they're gonna say you were a dumb ass. Boys-}
{150}{}{Interesting. Now who'd go saying something like that?}
{151}{}{Don't bullshit me, fat man. If I don't get back what's mine, somebody'll be shopping for your burial suit.}
{152}{}{Cute. You gonna answer my question or not?}
{153}{}{Oh, it's just something I heard. Just wanted to see what you'd say.}
{154}{}{Supposing I do know something. What of it?}
{155}{}{Now if a person had some things missing, do you suppose such a person could buy those things back?}
{156}{}{I want my shit back, fat man!}
{157}{}{How about I talk to the law?}
{158}{}{I'm tired of this. Boys - take care of our guest.}
{159}{}{I don't think Lenny would like that.}
{160}{}{Probably, but I wasn't asking him.}
{161}{}{Have it your way.}
{162}{}{True. Been too dull around here. Time for a little one-on-one in the basement. Come on, Lenny, I want to watch you kill this}
{163}{}{Like I've got problems that need solving.}
{164}{}{Como?}
{165}{}{Jet? Are you proposing something...?}
{166}{}{My friend here knows how to make it. Interested?}
{167}{}{Something illegal? No, I wouldn't do that.}
{168}{}{Intriguing. I'll give you $1000 for his services.}
{169}{}{Deal.}
{170}{}{No, I can't do that to a friend.}
{171}{}{Looks like we can do business, friend. Here's the deal - there's a loopy scientist in town - Dr. Henry. He's got some papers I'd like. I'll pay $1000 for them. Oh, and I don't want no harm to come to Dr Henry. He's useful alive. Interested? }
{172}{}{Eu estou trabalhando nisso.}
{173}{}{Não, não faz o meu estilo.}
{174}{}{Conhecimento custa dinheiro. Fui claro?}
{175}{}{"O preço da sabedoria é superior ao dos rubis."}
{176}{}{Tenho aqui $50.}
{177}{}{Esqueça.}
{178}{}{Ah, você é essa pessoa.}
{179}{}{Continuar}
{180}{}{Bem, no que me diz respeito, você é apenas um monte de esterco.}
{181}{}{Eu imaginei que você fosse um covarde.}
{182}{}{OK, sem problemas. Eu não quero nenhum problema. Vou te falar uma coisa, vou até mandar meus homens colocarem as coisas de volta onde as encontraram.}
{183}{}{É melhor assim, ou eu voltarei.}
{184}{}{Não me venha com essas histórias!}
{185}{}{Tal pessoa pode ser capaz de fazer.}
{186}{}{Agora, sugiro que saia.}
{187}{}{Por favor, chame os oficiais. Claro, suponho que você tenha evidências para apoiar essa acusação absurda.}
{188}{}{Sim, com certeza.}
{189}{}{Não importa.}
{190}{}{Como se houvesse um maldito Hubologista na cidade que me irritou. Assim que coçarem isso de novo, volte e fale comigo.}
{191}{}{Considere feito, eu tenho o coçador certo para ele, mas... o que é um Hubologista e onde posso encontrar um?}
{192}{}{Como você ousa falar contra a crença verdadeira!}
{193}{}{Desculpe, não me envolvo em guerras religiosas.}
{194}{}{Bem, eu sou um homem instruído. Qual é a sua pergunta?}
{195}{}{Pergunte a distância.}
{196}{}{Estou procurando a Vault 13.}
{197}{}{Já ouviu falar de um GECK?}
{198}{}{O que você sabe sobre um grupo chamado Rangers?}
{199}{}{O que você pode me dizer sobre um cara chamado Westin?}
{200}{}{Procuro informações sobre o vice-presidente Carlson.}
{201}{}{É isso.}
{202}{}{Seu pagamento permite uma pergunta. Outra te custará mais $50.}
{203}{}{Ok, aqui.}
{204}{}{Tenho todos os dados de que preciso.}
{205}{}{Acontece que eu tenho um mapa para o Vault 13, custa apenas 1.000 dólares. Está interessado?}
{206}{}{Claro. Eu vou levar.}
{207}{}{E aposto que você também vende gelo pra esquimó.}
{208}{}{Talvez mais tarde.}
{209}{}{É algum tipo de droga de New Reno? Eu nunca ouvi sobre isso.}
{210}{}{Nope. I've got some more questions, though.}
{211}{}{That's all I needed to know.}
{212}{}{Those bastards? Best stay out of my place or I'll put a hole in them.}
{213}{}{Bem, isso foi informativo. Outra pergunta.}
{214}{}{That's all I needed to know.}
{215}{}{O fazendeiro, hein? Veio aqui uma vez, quase batendo as botas. O médico da cidade teve que correr com alguns comprimidos - parece que Westin tem um problema cardíaco. Isso arruinou os negócios pelo resto da noite.}
{216}{}{Obrigado pela informação. Eu tenho mais algumas perguntas.}
{217}{}{That's all I needed to know.}
{218}{}{Como um bom cidadão, aplaudo a oposição de Carlson a qualquer influência de New Reno por aqui. Agora que Westin está morto, tenho ajudado na segurança do vice-presidente.}
{219}{}{Oh, bem, acho que nunca vou conhecer o homem. Também já ouvi falar muito dele.}
{220}{}{That's all I needed to know.}
{221}{}{Isso é tudo?}
{222}{}{Não, eu tenho mais algumas perguntas.}
{223}{}{Sim, por enquanto é isso.}
{224}{}{Ei, um homem tem que tentar. A Vault 13 é praticamente uma religião por aqui, eles até construíram uma estátua para algum otario que supostamente veio de lá. Isso é tudo que eu sei.}
{225}{}{Eu vendi um mapa para você. Tente usá-lo.}
{226}{}{Esse mapa não serviu? Desculpe, o cara jurou que era genuíno. Como eu poderia saber? Não sei onde fica a Vault 13.}
{227}{}{Eu tenho mais algumas perguntas.}
{228}{}{Isso é tudo que eu preciso saber.}
{229}{}{É o seguinte. Eu gosto do seu trabalho e Carlson precisa de outro guarda. Dê um tempinho e haverá um trabalho esperando por você lá embaixo.}
{230}{}{Estou nisso, Merk.}
{231}{}{Eu não preciso de um emprego. Obrigado de qualquer maneira.}
{232}{}{Excelente. Volte quando terminar.}
{233}{}{Isso é muito preocupante. Rapazes, o matem e recuperem esta prova.}
{234}{}{Suas patéticas tentativas de me intimidar são quase divertidas, mas agora sugiro que saia antes que eu me canse deste joguinho.}
{235}{}{Ah, eu ouvi a notícia. Você ainda está interessado em um emprego?}
{236}{}{Sim, estou cansado de regalias. Poderia fazer o trabalho.}
{237}{}{Não.}
{238}{}{O que voce pensa que está fazendo no meu lugar?}
{239}{}{Antes de eu cruzar a linha, não voltarei a fazer. Só preciso de um pouco do seu tempo.}
{240}{}{Eu farei o que eu quiser, sua doninha.}
{241}{}{Saia daqui, javali!}
{242}{}{Então o que você está fazendo aqui seu idiota? Se você quer me impressionar, faça direito!}
{243}{}{Não falo com você até que o trabalho esteja feito!}
{244}{}{Isso me decepciona, eu normalmente me livro de coisas que me decepcionam. No entanto, no seu caso, posso ser generoso. Apenas saia e não volte e eu vou esquecer tudo sobre isso.}
{245}{}{Então, aquele pequeno negócio com o Dr. Henry está feito?}
{246}{}{Sim, tenho os papéis que você quer.}
{247}{}{Não.}
{248}{}{Dias assim me deixam muito feliz. Bem, vamos concluir nossos negócios.}
{249}{}{Chegou ao meu conhecimento que o engenhoso médico expirou durante a sua visita. Isso foi contra minhas ordens. Para recuperar perdas futuras, acho que será necessário receber um reembolso.}
{250}{}{Olha, vou te dar 500 dólares e esquecemos tudo.}
{251}{}{Que se dane.}
{252}{}{Bem, boa sorte em suas aventuras. Não vejo razão para conversarmos de novo.}
{253}{}{Bem por mim.}
{254}{}{Trato feito, mas só porque eu gosto de você. Sugiro que não volte tão cedo.}
{255}{}{Acho que vou matar você, pegar meu dinheiro de volta e receber uma recompensa. Afinal, ser um bom cidadão é isso.}
{256}{}{Você novamente! MORRA!}
{257}{}{I thought I said don't bother me anymore.}
{258}{}{ and I'm a badass mofo. Just ask anybody.}
{259}{}{ guy.}
{260}{}{ chick.}
{261}{}{A Hubologist is a nut-case religious fanatic. It can be found at the church in town.}
{262}{}{Eu estou no meu caminho.}
{263}{}{I'm not talking to you until the job's done! I need those papers from Dr. Henry's place, pronto.}
{264}{}{No, but I need some information.}
{265}{}{I know Lenny's death ain't no accident, you bastard.}
{266}{}{Hey, that map was a fake.}
{267}{}{Well, what about the money I gave you.}
{268}{}{Like I said sorry it didn't pan out for you.}
{269}{}{Well how bout you eat this bullet for my trouble.}
{270}{}{Hmmphf.}
{271}{}{You have "taken care of" the Hubologist for Merk.}
{272}{}{You retrieved Dr. Henry's papers.}
{300}{}{Where the hell do you think you are going?! Try that again and I'll kick your ass.}
{301}{}{Eu avisei a você!}
