{100}{}{Você acha que, mesmo com cabelo verde e carrancuda, ela é a garçonete deste lugar.}
{101}{}{Essa é Mira. Ela está misturado um Rad-A-Waster.}
{102}{}{Bem, ela é jovem e atraente, mas há algo em olhar em seus olhos diz que ela não aceita nada de ninguém. O olhar e os nós dos dedos pontiagudos que ela usa em uma corrente em volta do pescoço.}
{103}{}{me chamo Mira. O que você quer, estranho?}
{104}{}{Olá de novo. O que vai ser?}
{105}{}{Bebida.}
{106}{}{Vault 13?}
{107}{}{GECK?}
{108}{}{Eu não me importo. Me de o especial da casa.}
{109}{}{Me passa uma gelada.}
{110}{}{Informação.}
{111}{}{Estou procurando trabalho.}
{112}{}{Bem, você não é o único! É assim que eu gosto deles.}
{113}{}{De volta?}
{114}{}{Yubba.}
{115}{}{Uau... você cuidou do Lenny. Incrível! Tome uma bebida da casa.}
{116}{}{O que você fez com Lenny - foi perverso!}
{117}{}{Oh, um conversador impressionante. O que quer pra hoje - um Radawaster? Só dez conto.}
{118}{}{Sim.}
{119}{}{Não.}
{120}{}{Vai comprar uma bebida? $10.}
{121}{}{Sim.}
{122}{}{Não.}
{123}{}{Um Radawaster chegando! $10.}
{124}{}{Tudo bem.}
{125}{}{Dez contos? Muita coisa pra mim.}
{126}{}{Claro, um dólar.}
{127}{}{Tudo bem.}
{128}{}{Muita grana pra mim.}
{129}{}{Você pode tentar Merk, ele esta na sala dos fundos.}
{130}{}{Não há nada para você aqui, estranho.}
{131}{}{Obrigado, eu acho.}
{132}{}{Então é isso, estranho?}
{133}{}{Vault 13?}
{134}{}{GECK?}
{135}{}{Tem um tempinho para algumas perguntas?}
{136}{}{Eu vou, tchauuu.}
{137}{}{Isso é tudo.}
{138}{}{Saia daqui, caloteiro!}
{139}{}{Claro, eu tenho algum tempo, é isso que os garçons sempre fazem. Mas não se iluda.}
{140}{}{Para você, eu sempre tenho tempo, baby. O que você quer?}
{141}{}{Com certeza.}
{142}{}{Me conte sobre esta cidade.}
{143}{}{Ja ouviu falar da Vault 13?}
{144}{}{Estou procurando uma coisa chamada GECK. Sabe alguma coisa sobre isso?}
{145}{}{Qual é o problema com esse tal de Merk?}
{146}{}{Tem um policial na cidade dizendo algumas coisas duras sobre você. Qual é o problema?}
{147}{}{Bem, isso acaba com nossas suposições.}
{148}{}{Se chama NCR. Costumava ser Shady Sands, mas após a derrota do Mestre, Aradesh e os outros fundaram a República. Agora, a NCR fica bem na fronteira. Tudo ao sul daqui é governado pela República.}
{149}{}{La vai um conselho: Não suje as mãos na cidade. Os tribunais não são muito amigáveis com os nossos tipos, se é que você me entende. Os cidadãos têm mais direitos do que você.}
{150}{}{Olha, isso é tudo que tenho a dizer sobre isso.}
{151}{}{Hmm.}
{152}{}{Mais algumas perguntas...}
{153}{}{Bem, obrigado. Vou me lembrar disso.}
{154}{}{Você é outro daqueles malucos procurando um tesouro perdido? Você deveria ir ver Bob Carne Seca no Rancho Westin. Ele está sempre falando sobre tesouros. Se bem que suportar suas histórias sóbrio é bem difícil.}
{155}{}{Batata? Eu vou.}
{156}{}{Mais algumas perguntas...}
{157}{}{Bem, obrigado. Vou me lembrar disso.}
{158}{}{Você me diz como fazer a mistura e eu faço para você.}
{159}{}{Sem bebida. GECK é.... GECK.}
{160}{}{Não é uma bebida. É um Kit de Criação do Jardim do Éden.}
{161}{}{Mais algumas perguntas...}
{162}{}{Bem, obrigado. Vou me lembrar disso.}
{163}{}{Ele é um cara legal, é meu chefe. O que você espera que eu diga?}
{164}{}{Mais algumas perguntas...}
{165}{}{Bem, obrigado. Vou me lembrar disso.}
{166}{}{Esse idiota... Foi apenas um divórcio conturbado, só isso.}
{167}{}{Bem, que tal falarmos de outra coisa?}
{168}{}{Bem, acho que vou indo.}
{169}{}{Ah, muito informativo. Olha, você pode tentar o Dr. Henry na cidade, mas eu tenho outras coisas para fazer, Dumbo.}
{170}{}{Kit de Criação do Jardim do Éden? Parece técnico. Tente procurar Dorothy, a engenheira da cidade. }
{171}{}{Mais algumas perguntas...}
{172}{}{Bem, obrigado. Vou me lembrar disso.}
{173}{}{Hum... trabalho? Quer emprego? Ajudar Mira?}
{174}{}{Sim.}
{175}{}{Não.}
{176}{}{Ouça: homem mau machucou Mira. Homem mau chamado Jack. Você machuca homem mau. Mira é como você e te dá uma bela arma. Bom?}
{177}{}{Sim.}
{178}{}{Não.}
{179}{}{Bom! Mira tem corda na parede. Vai a noite, você encontra a corda. Você se esgueira, vai para o lugar grande pelo portão. Você encontra Jack, você machuca Jack. Mira te dá uma arma.}
{180}{}{Você vai a noite e encontra a corda. Você vai escondido para o lugar grande pelo portão. Você encontra Jack. Você machuca Jack. Mira te dá uma arma. Agora vá embora. Me ver com você... não é bom. Você ajuda Mira e volta. Entendido?}
{181}{}{Mira ouviu que Jack se machucou. Bom trabalho, Dumbo. Aqui arma, você pega. Obrigado.}
{182}{}{Que se foda você também. Nunca vou me livrar daquele desgraçado.}
{183}{}{Você precisa falar com Merk, mas ele não está aqui. Volte a noite, ele tem mais tempo.}
{184}{}{Não sei o que você fez com Lenny, mas eu não ficaria por aqui. Isso não vai te deixar muito popular.}
{185}{}{Ei, eu avisei. Ah bem...}
{186}{}{Você é Mira, certo? Tem um policial que estava dizendo algo sobre você.}
{187}{}{Você Mira? Jack mau diz coisas.}
{188}{}{Aquele desgraçado do Jack? O que ele disse agora?}
{189}{}{Jack morto. Fez boom.}
{190}{}{Eu mato. Ele homem mau.}
{191}{}{Eu não me importaria com isso, ele está morto. Se explodiu na estação de energia.}
{192}{}{Agora não muito. Eu o matei.}
{193}{}{Tá brincando? Essa é a melhor notícia que recebi no dia! Espero que seu cérebro tenha pintado toda a parece, esse maldito psicopata mereceu. Pegue um Rad-a-Waster por minha conta.}
{194}{}{Gosto.}
{195}{}{Eu vou agora.}
{196}{}{Obrigado, eu acho. Diga, tem tempo para uma pergunta?}
{197}{}{Obrigado. Achei que você deveria saber.}
{198}{}{Você fez o que? Ah, se eu não estivesse de plantão, eu fecharia esse bar e... bom, te beijaria. Esse idiota mereceu. Na verdade, não conte a ninguém, mas eu esperava conseguir algum capanga estúpido para fazer o trabalho para mim. Tinha uma pequena recompensa reservada para isso, é sua agora. No que me diz respeito, você merece.}
{199}{}{Obrigado, eu acho. Diga, tem tempo para uma pergunta?}
{200}{}{Obrigado. Achei que você deveria saber.}
{201}{}{Dumbo, você me fez a mulher mais feliz que existe! Tenho um presentinho para você, bem aqui atrás do bar. É todo seu.}
{202}{}{Eu gosto Mira.}
{203}{}{Eu gosto arma. Eu vou, tchau.}
