{100}{}{Você vê um homem com roupas manchadas de graxa, provavelmente um mecânico.}
{101}{}{É o Rondo, dono desta espelunca.}
{102}{}{Você acha que ele é um mecânico, mas está usando uma arma que parece meio estranha.}
{103}{}{Saudações, Ranger. O tempo tem sido bom, espero.}
{104}{}{Algum dia vamos acabar com esses escravistas.}
{105}{}{Preciso caçar mais escravistas.}
{106}{}{Desculpe, não fazemos mais isso.}
{107}{}{Isso é propriedade privada. Se importa?}
{108}{}{I'm not taking any more work right now, okay?}
{109}{}{Hey, bastard, you shouldn't mess with the Rangers.}
{110}{}{Touch any of my stuff again and I am going to have to open up ole' bessy on you.}
