{100}{}{Você vê uma estranha coisa meio cachorro, meio metal. Parece estar ativado.}
{101}{}{É Robodog! O animal de estimação favorito de todos!}
{102}{}{Ou essa coisa é uma combinação horrível costurada de cachorro e máquina ou é toda máquina, habilmente feita para parecer um cachorro. É difícil dizer.}
{103}{}{Arf! <clique> Woof!}
{104}{}{...bzzzzzz...}
{105}{}{.whirrrrr... Eu não sou um cachorrinho.}
{106}{}{Grrrrrrrrrrrrrrrr--}
{107}{}{Woof! Wo-wo-wo-<clique>woof.}
{108}{}{<sprzzzt> Miau... erro.}
{109}{}{Barkbarkbarkbarkbarkbarkbark!}
{110}{}{Grrr...}
{111}{}{How-woooo! <clique-clique> How-wooo!}
{112}{}{Yipe! Yipe! Yipe!}
{113}{}{Perigo! Perigo!}
{114}{}{Rowf! <tick-tick-tick> Rowf!}
{115}{}{<whirrr> Não pássaro, nem avião, nem mesmo sapo, apenas o velho eu - Robocão! <clique>}
{116}{}{Rooby-Doo!}
{117}{}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{118}{}{Woof!}
{119}{}{GRRR-ROWF!}
{120}{}{Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{OK}
{122}{}{Acho que ainda não quero me juntar a você. Adeus.}
{123}{}{Rowf? <boing> Feio?}
{124}{}{Como você está?}
{125}{}{Eu preciso que você espere aqui até eu voltar.}
{126}{}{É isso por agora.}
{127}{}{<clique> choramingo}
{128}{}{Não importa.}
{129}{}{OK}
{130}{}{HP:}
{131}{}{Cybercão não pode mais ser consertado neste momento.}
{132}{}{Cybercão foi reparado parcialmente.}
{133}{}{O Cybercão foi todo consertado.}
{1000}{}{Au! Wo-wo-wo-<clique> au?}
{1100}{}{Arf! <clique> Woof!}
{1200}{}{Rowf? <boing> Feio?}
{1300}{}{<clique> choramingo.}
{1400}{}{How-woooo! <clique-clique> How-wooo!}
{1500}{}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{1600}{}{Eu removerei a coisa certa.}
{1700}{}{Arf-arf proximidade fechada.}
{1800}{}{Arf-arf proximidade média.}
{1900}{}{Arf-arf proximidade distante.}
{2000}{}{.whirrrrr... Eu não sou um cachorrinho.}
{2100}{}{GRRR-ROWF!}
{2200}{}{Au! Wo-wo-wo-<clique> au?}
{2204}{}{Ok, você está a uma boa distância agora.}
