{100}{}{Você vê um escravista carrancudo coberto de sujeira.}
{101}{}{Você vê um escravista de aparência dura. Ele parece estar no comando aqui.}
{102}{}{Você vê Don, o escravista responsável por este acampamento.}
{105}{}{Ei, que porra é essa!? Quem é você?}
{106}{}{Eu sou o seu pior pesadelo. Prepare-se para a morte!}
{107}{}{Metzger me enviou.}
{108}{}{Estou aqui para me unir.}
{109}{}{Uhh, não foi aqui que deixei meu carro...}
{200}{}{Você primeiro, babaca.}
{201}{}{Não tenho tempo para isto. Vamos, rapazes.}
{202}{}{Se juntar a nós? Isso não é a porra de um centro de recrutamento. Se você quiser se juntar aos escravistas, vá para
 Den e fale com Metzger. Agora você precisa de alguma coisa ou só está aqui para me irritar?}
{203}{}{Metzger te enviou? [Ele se mexe desconfortavelmente.] Não me diga que ele já quer mais escravos... pelo amor de Deus, enviamos uma remessa na semana passada.}
{300}{}{Na verdade sim, eu preciso de algo.}
{301}{}{Então, por que você está aqui?}
{302}{}{Acho que não preciso de mais nada.}
{303}{}{Bem, então dê o fora daqui. Você está invadindo e não é bem vindo aqui..}
{304}{}{Estou de saída.}
{305}{}{Oh, eu vou embora, mas não antes de matar todos vocês.}
{307}{}{De fato, ele faz. Ele vai entreter um figurão de New Reno e queria mais algumas garotas para a ocasião. Mas, ei, se você não pode me dar nenhuma... Tenho certeza que o chefe ficará emocionado quando eu voltar de mãos vazias.}
{308}{}{[O suor começa a se formar na cabeça tatuada do homem.] Ei, espere um segundo. Eu nunca disse que não poderia dar algumas. Na verdade, aqui, pegue a chave do barraco, é onde guardamos nossas, uh, favoritas. A escolha certa, você pode dizer. [Ele te entrega uma chave e sorri nervosamente.]}
{309}{}{Obrigado, vou falar bem de você. Tchau.}
{310}{}{Metzger te mandou, é? Eu pareço cego para você? Você nem está usando a porra da nossa marca. Não sei quem você é, mas você fala merda e está me fazendo perder tempo. Por isso, vai morrer. [Sinal para seus homens.] Vamos acabar com esse perdedor.}
{311}{}{Yeah right. You're full of shit and you're wasting my time. For that, you die. [Signals to his men.] Let's waste this loser.}
{400}{}{I'm busy. Go see Metzger in the Den if you want to do a run.}
{450}{}{Didn't I tell you to scram? We don't take too kindly to trespassers. Time to die.}
{500}{}{[FEITO]}
{600}{}{Agora é a hora que você vai morrer!}
{601}{}{Die Ranger scum!}
{800}{}{Umm... Give Metzger my regards.}
{900}{}{No, actually, he sent me to have a look at your stock. You see, I have very particular tastes, but I'm willing to
 pay a premium price.}
{901}{}{Bullshit. Metzger's never sent a customer out here before. I don't know what you're trying to pull, but you've
 got three seconds to get the fuck outta my face before I have my boys pump you full of lead.}
