{100}{}{Bem, pelo menos você tem uma corda de trabalho agora.}
{101}{}{O que deveria fazer.}
{102}{}{Ok, está faltando sua corda e um balde.}
{103}{}{O poço já está consertado. Lembra?}
{104}{}{Tem corda, mas falta o balde.}
{200}{}{Você vê um poço.}
{201}{}{É só um poço.}
{202}{}{Após uma inspeção mais detalhada, você vê que o poço não está funcionando. Talvez você possa consertar isso.}
{203}{}{O poço está funcionando novamente.}
