{100}{}{Você está precisando de algo?}
{101}{}{Sim, eu queria saber quem você está protegendo.}
{102}{}{Meu? Oh não, eu não preciso de nada. Tchau.}
{103}{}{Quem você guarda?}
{104}{}{Adeus!}
{110}{}{Eu sei que eles guardavam o líder da tribo, aquele que anda com espíritos. Muita honra o guardando, evita indesejados, como você. Agora saia.}
{111}{}{[FEITO]}
{120}{}{Eu digo para sair, mas você não escuta. Eu libero espíritos de fúria quando as pessoas não ouvem. Sugiro que você coloque seus pés fora, agora.}
{121}{}{[FEITO]}
{130}{}{Ouvi falar das boas ações que você tem feito. Olhe, eu estava errado sobre você. Me perdoe por ser um homem rude, amigo. Entre e veja o grande homem. Ele está esperando por você.}
{131}{}{Ouvi falar das boas ações que você tem feito, amigo. Entre e veja o grande homem, ele está esperando por você.}
{132}{}{Obrigado.}
{133}{}{Valeeeu.}
{140}{}{Saudações, amigo.}
{141}{}{Como vão as coisas, guerreiro?}
{142}{}{Vá em frente.}
{143}{}{Muito bem, guerreiro.}
{144}{}{Bom espiar de novo, amigo.}
{260}{}{Eu mato escravista!}
{300}{}{Você vê um tribal de aparência forte}
{301}{}{Você vê o guardião do líder da tribo.}
{302}{}{Este homem está observando você com um olhar penetrante. Claramente, ele está protegendo alguém importante.}
{500}{}{Seja sempre bem-vindo aqui, herói.}
