{100}{}{Você vê um guerreiro.}
{101}{}{Você vê Serin.}
{102}{}{Ele parece gravemente ferido e tem uma perna quebrada.}
{103}{}{Você vê Serin. Ele parece gravemente ferido e tem uma perna quebrada.}
{104}{}{Você vê Serin. Sua perna está enfaixada e ele está mancando.}
{105}{}{Você vê Serin. Ele parece melhor e está em um sono profundo.}
{106}{}{Você vê Serin. Parece que ele se recuperou bem.}
{200}{}{*ugh* Morra demônio!! Você não vai ser ta-}
{201}{}{Acalme-se, você está seguro agora. O gecko esta morto.}
{202}{}{O que!? Oh, louvado sejam os espíritos, amigo. Tive medo de estar acabado.}
{203}{}{O que aconteceu aqui?}
{204}{}{Jerem e eu vamos caçar toda semana. Tomou a passagem da caverna para o campo onde muitos geckos vagam. Hunt foi mal. Tive que correr. Muitos geckos com espíritos de fúria. Entramos na caverna. Começou a gritar por socorro. [Ele faz uma pausa por um momento e estremece de dor enquanto tenta esfregar a perna.]}
{205}{}{Por favor, continue.}
{206}{}{A passagem já estava à beira da destruição. Água vazando do córrego acima. Um passe mortal, mas um ótimo atalho para campos. Não mais. Veja, começamos a gritar como tolos e o teto desaba sobre nós.}
{207}{}{[Continuar]}
{208}{}{Pobre Jerem. Eu vi uma grande rocha esmagá-lo como um inseto. As pedras grandes não acertaram, mas a mordida do gecko sim. Bem quando penso que estou seguro, um gecko aparece do nada e dá uma grande mordida na perna. Me levou direto ao chão. Não tinha lança, pensei que o gecko estivesse me jantado com certeza. Mas os espíritos tinham outros planos. Trouxe uma grande pedra e esmago a cabeça do gecko. Mas esmagou minha perna também.}
{209}{}{[Continuar]}
{210}{}{Assim fico cravado no chão, sem lança. De repente, ouço algo vindo da escuridão até mim. Aproximou-se e vi que era um grande gecko zangado. As pedras caindo só estão deixando mais nervoso. Foi quando você entrou, amigo. Verdadeiramente, estou em dívida com você.}
{211}{}{Uau, que história. Parece que você tem muita sorte de estar vivo. Como está sua perna?}
{212}{}{Nada boa, amigo. Parece que a rocha era mais forte que o osso da minha perna. Duvido que me levante e saia logo.}
{213}{}{Não se preocupe, sou um médico experiente. Deixe eu dar uma olhada em sua perna e verei o que posso fazer.}
{214}{}{Não se preocupe, não devo ter problemas em carregá-lo para fora daqui. Então podemos pedir ao xamã para dar uma olhada em sua perna.}
{215}{}{Provavelmente deveríamos chamar um profissional para vir aqui e dar uma olhada. Vou rapidamente tentar encontrar alguma ajuda. A caverna parece estar vazia agora, então você deve ficar seguro aqui até eu voltar.}
{216}{}{Hmm... Acho que não sou forte o bastante para carregá-lo daqui, mas aposto que Sulik conseguiria. [Para Sulik] Vamos carregar esse cara daqui.}
{217}{}{Hmm... Eu não acho que sou forte o suficiente para carregar você daqui, mas aposto que Marcus poderia fazer isso. [Para Marcus] Vamos tirar esse cara daqui.}
{218}{}{[Você examina a perna do guerreiro. Está muito rasgada e o osso está aparecendo em algumas partes. Você habilmente coloca o osso de volta no lugar, estanca o sangramento, imobiliza a perna e começa a trabalhar para curá-la.]}
{219}{}{[Depois de cerca de 15 minutos de trabalho agonizante, a perna está em muito melhor forma. Parece que este homem será capaz de andar novamente.]}
{220}{}{Tudo bem, isso deve bastar. Você precisará de alguns dias de descanso para cicatrizar completamente. Não coloque muita pressão durante este tempo e você deve ficar bem.}
{221}{}{Espíritos santos possuem você, amigo! Eu que agradeço. Agora vou mancando até o xamã. Algumas boas ervas para aliviar a dor. Vejo você na vila, amigo.}
{222}{}{[Feito]}
{300}{}{Eu te agradeço, amigo. Vejo você de volta na aldeia.}
{400}{}{Muito obrigado, amigo. Verdadeiramente, você é abençoado pelos espíritos.}
{500}{}{zzzZZzzz...}
{501}{}{A mimir...}
{600}{}{Você cura a perna de Serin.}
{700}{}{Ele precisa de mais ajuda do que eu posso oferecer. É melhor eu ir.}
{1000}{}{Que bom estar espiando você, herói.}
{1001}{}{Eu nunca esqueço o que você fez por mim, herói.}
