{100}{}{You see a stern-looking guard.}
{101}{}{You see a mean-looking Vault City guard.}
{102}{}{Get on about your business.}
{103}{}{I think it's about time for you to leave.}
{104}{}{I don't like the looks of you.}
{105}{}{Tenha cuidado.}
{106}{}{Hello, Citizen.}
{107}{}{Nice to see you, Citizen.}
{108}{}{Busy day, Citizen?}
{109}{}{After you, Citizen.}
{110}{}{Olá, viajante.}
{111}{}{Be about your business, Outworlder.}
{112}{}{Pare de vagabundar.}
{113}{}{Talk to Wallace if you're lookin' to get into the City.}
{114}{}{Nothing to report, Captain.}
{115}{}{Just keeping an eye on things here, Captain.}
{116}{}{Vault City prevails, Capitão.}
{117}{}{Bom dia, Capitão.}
