{100}{}{Você vê uma mulher muito rígida. Ela parece que não relaxa há anos.}
{101}{}{Você vê Melinda, a chefe do escritório de boas-vindas.}
{102}{}{Olá, acho que nunca te vi por aqui antes. Bem-vindo a Vault City. Há
 algo em que eu possa ajudá-lo?}
{103}{}{Sim, em que mais posso ajudá-lo?}
{104}{}{Esta área cercada é a cidade?}
{105}{}{Estou a procura da Vault.}
{106}{}{Quem é você?}
{107}{}{Não, obrigado. Adeus.}
{108}{}{Isto Vauti Citi?}
{109}{}{Não, não... não deixe que o local te confunda. Você está
 atualmente no Pátio, a cidade real fica ao norte.}
{110}{}{Qual a diferença entre as duas áreas?}
{111}{}{Posso pedir mais uma coisa?}
{112}{}{Obrigado pela ajuda. Tchau.}
{113}{}{Brigadooo}
{114}{}{Nossa Vault? Está localizada dentro da cidade. No entanto, devo dizer
 que apenas Cidadãos são permitidos na Vault.}
{115}{}{Eu preciso entrar na Vault.}
{116}{}{Posso pedir mais uma coisa?}
{117}{}{Obrigado pela ajuda. Tchau.}
{118}{}{O meu nome? Ora, é Melinda. Sou a chefe do Escritório de Saudações de Vault City.}
{119}{}{Parece um trabalho difícil.}
{120}{}{Posso pedir mais uma coisa?}
{121}{}{Obrigado por sua ajuda.}
{122}{}{O Pátio é uma área onde protegemos os forasteiros menos afortunados. Muitos
 vivem sob nossa proteção e aumentam o esplendor de Vault City. O interioir é
 onde vivem os cidadãos da cidade.}
{123}{}{Por que apenas os cidadãos vivem no centro da cidade?}
{124}{}{Posso pedir mais uma coisa?}
{125}{}{Obrigado por sua ajuda.}
{126}{}{Sinto muito, mas como eu disse, apenas Cidadãos são permitidos na Vault.
 Não posso te conceder acesso. Fale com Wallace, nosso funcionário da alfândega.
 Ele pode ser capaz de ajudar. Você encontrará o escritório dele no extremo norte do Pátio.}
{127}{}{Posso pedir mais uma coisa?}
{128}{}{Obrigado pela ajuda. Tchau.}
{129}{}{Meu trabalho beneficia Vault City e tenho o privilégio de poder conversar
 com os viajantes sobre a grandeza da cidade.}
{130}{}{Oh, vamos lá, tem que ser um *pouco* chato às vezes.}
{131}{}{Posso pedir mais uma coisa?}
{132}{}{Obrigado por sua ajuda.}
{133}{}{Para construir uma vida melhor para todos, devemos estar atentos para nos
 proteger de influências externas.}
{134}{}{E é por isso que vocês se separam?}
{135}{}{Tenho muito orgulho do trabalho que faço para Vault City. Você
 terá que me desculpar, mas tenho alguns negócios muito urgentes para resolver. Bom dia.}
{136}{}{Não fazemos isso para *nós mesmos.* Fazemos isso para o bem de todos.}
{137}{}{Sim, claro que sim. Soa melhor dessa forma.}
{138}{}{Posso pedir mais uma coisa?}
{139}{}{Obrigado por sua ajuda.}
{140}{}{Você não parece capaz de entender o que estamos fazendo aqui.}
{141}{}{Você tem razão. Não consigo entender porque não faz nenhum *sentido.*}
{142}{}{Eu só estava curioso. Obrigado pela ajuda.}
{143}{}{Estou muito ocupado no momento. Fale com o Sub-Oficial de Boas Vindas
 se precisar de assistência.}
