{100}{}{Você vê um preso.}
{101}{}{Você vê um preso forasteiro.}
{102}{}{Bem, esta é a última vez que *eu* ignoro o toque de recolher.}
{103}{}{Mais outra semana e está de volta ao Centro de Alocação...}
{104}{}{Melhor continuar andando, amigo. Eles nos vêem conversando, nós dois
 estamos ferrados.}
{105}{}{Maldito Barkus, me segurando nesse lugar. Quando eu colocar minhas mãos nele...}
{106}{}{Queria nunca ter vindo pra Vault City. Cidade "livre"... que piada.}
{107}{}{Ao menos a comida não é ruim.}
