{100}{}{You see Randal, the Chief Amenities Officer.}
{101}{}{You see a middle-aged man with thinning black hair.}
{102}{}{You see Randal, the Chief Amenities Officer.}
{103}{}{You see a middle-aged man with thinning black hair.}
{104}{}{Congratulations, }
{105}{}{Way to put those Enclave assh-... er, jerks, in their place!}
{106}{}{I heard you kicked some major tail down south. Way to go.}
{107}{}{An intruder! Guards! Guards!}
{108}{}{Wh-?! A mutant! Guards!}
{109}{}{Wh-? A ghoul! Guards!}
{110}{}{Bom dia, Capitão.}
{111}{}{Vault City prevails, Capitão.}
{112}{}{Bom dia, Citizen.}
{113}{}{Vault City prevails, Citizen.}
{114}{}{Need to send distribution charts to Sub-Amenities Offices A and B...}
{115}{}{Need to compile the latest stock inventories and put them on the list server...}
{116}{}{I miss DOS. This new operating system makes it harder to enter lists.}
{117}{}{The First Citizen still needs those inventory lists...}
{118}{}{Sorry, we're closed for the evening. Come back in the morning.}
{119}{}{We're closed. I'm just compiling these lists before I head home.}
{120}{}{Hello there, stranger. Always a pleasure to see a new face. Name's Randal... I'm the Chief Amenities Officer. Need something?}
{121}{}{Gechkk}
{122}{}{Nooooooooo-pe}
{123}{}{Desliga}
{124}{}{Well, it depends. What is this place?}
{125}{}{Nothing today, actually.}
{126}{}{A GECK? That's a Garden of Eden Creation Kit, a kind of gray suitcase looking thing, right? I haven't heard anyone mention one of those in... well, since... almost forever.}
{127}{}{NEED Gechkkk}
{128}{}{Desliga}
{129}{}{Do you have one?}
{130}{}{Mind if I ask you something else?}
{131}{}{Bem, não importa então.}
{132}{}{Lamento dizer isso a você, amigo, mas não temos mais o nosso. Usamos para fazer Vault City...*poof.* Tudo se foi.}
{133}{}{PRECISO Gechkkk.}
{134}{}{Desliga}
{135}{}{Oh... bem, você conhece algum lugar que possa ter um?}
{136}{}{Mind if I ask you something else?}
{137}{}{Bem, deixa pra lá.}
{138}{}{Bem, hum. Aqui está o seu problema, a meu ver: o GECK é uma velha peça de tecnologia... tecnologia pré-guerra, na verdade. Você simplesmente não consegue mais "encontrá-los". Eles foram emitidos apenas para Vaults.}
{139}{}{PRECISO ir Valt.}
{140}{}{Desliga}
{141}{}{Você sabe onde posso encontrar outras vaults?}
{142}{}{Mind if I ask you something else?}
{143}{}{Bem, não importa então.}
{144}{}{Você pode escanear o computador central da Vault, ver se ele tem alguma coordenada para qualquer outra Vault. Duvido, mas não custa nada verificar.}
{145}{}{Bem, se você tivesse acesso ao nosso computador central da Vault, talvez encontrasse alguma menção a outras Vaults. Mas apenas cidadãos são permitidos na Vault.}
{146}{}{Tanques}
{147}{}{Mind if I ask you something else?}
{148}{}{Obrigado pela informação.}
{149}{}{Olá, bem-vindo de volta. Algo que eu possa fazer por você?}
{150}{}{Claro. O que está pensando?}
{151}{}{Gechkkk?}
{152}{}{Desliga}
{153}{}{Que lugar é esse mesmo?}
{154}{}{Por acaso você tem um GECK em estoque?}
{155}{}{Valerie no galpão de manutenção precisa de uma chave nova e um alicate.}
{156}{}{O Conselheiro McClure disse que você teria um... uh, hidro-magneto-não-sei-o-que que eu poderia pegar para a usina Gecko.}
{157}{}{O Conselheiro McClure disse que você teria um regulador hidroelétrico de magnetosfera em estoque que eu poderia ter.}
{158}{}{A Primeira Cidadã me enviou aqui para reivindicar minha recompensa.}
{159}{}{Nothing today, actually.}
{160}{}{Este é o Gabinete de Serviços. Tem o estoque típico... necessidades básicas de vida, alguns livros, manuais de "como fazer", algumas ferramentas, stimpacks, suprimentos médicos, isso e aquilo.}
{161}{}{Parece bom. Posso ver o que você tem em estoque?}
{162}{}{Você tem um GECK?}
{163}{}{Valerie no galpão de manutenção precisa de uma chave nova e um alicate.}
{164}{}{O Conselheiro McClure disse que você teria um... uh, hidro-magneto-não-sei-o-que que eu poderia pegar para a usina Gecko.}
{165}{}{O Conselheiro McClure disse que você teria um regulador hidroelétrico de magnetosfera em estoque que eu poderia ter.}
{166}{}{A Primeira Cidadã me enviou aqui para reivindicar minha recompensa.}
{167}{}{Se importa se eu fizer algumas outras perguntas?}
{168}{}{Eu posso estar de volta em outra hora.}
{169}{}{Bem, desculpe informar, mas só estou autorizado a fazer transações com Cidadãos. Sem ofensa a você, mas é regra, sabe? Você pode experimentar o Happy Alegre no pátio.}
{170}{}{Bem, desculpe informar, mas só estou autorizado a fazer transações com Cidadãos. Sem ofensa a você, mas é regra, sabe? Você pode experimentar o Happy Alegre no pátio.}
{171}{}{How can I become a Citizen?}
{172}{}{Mas... uh, eu sou um Cidadão. Você não se lembra de mim?}
{173}{}{Olha, meu dinheiro vale tanto quanto o de qualquer Cidadão.}
{174}{}{O Conselheiro McClure disse que você teria um regulador hidroelétrico de magnetosfera em estoque que eu poderia ter.}
{175}{}{A Primeira Cidadã me enviou aqui para reivindicar minha recompensa.}
{176}{}{Se importa se eu fizer algumas outras perguntas?}
{177}{}{Certo. Tchau.}
{178}{}{You can take the Citizenship test. Proconsul Gregory gives it to any Outsider who wants to become a Citizen. You should probably talk to First Citizen Lynette first, though. She kind of runs the show around here.}
{179}{}{All right. Where is she?}
{180}{}{I see. Mind if I ask you another question?}
{181}{}{Thanks for the information. I'll go look for her.}
{182}{}{Ela está no Prédio do Conselho... saia do prédio aqui, vire à direita e continue descendo a rua passando pelo parque. Você deve chegar direto nele.}
{183}{}{I see. Mind if I ask you another question?}
{184}{}{Thanks for the information. I'll go look for her.}
{185}{}{Sério? Não posso dizer que me lembro de você. Tem algum documento com você? Isso esclareceria o assunto.}
{186}{}{Não, eu não os tenho comigo agora.}
{187}{}{Sim. Aqui está.}
{188}{}{Deixa para lá. Falo com você mais tarde.}
{189}{}{Bem, deixe-me passar pelo leitor aqui, e vamos apenas garantir que tudo esteja em ordem. Não vai demorar, mas um momento.}
{190}{}{O qu-?! Hey! Devolva esses documentos!}
{191}{}{Uh... na verdade, não tenho tempo para comprar nada agora. Me deixe pegar os papéis de volta e vou embora.}
{192}{}{Tudo bem. Tenho certeza que está tudo em ordem.}
{193}{}{Bem... uh, tudo bem.}
{194}{}{Se importa se eu te fizer algumas perguntas?}
{195}{}{Vejo você mais tarde.}
{196}{}{Tudo confere, pegue de volta seus documentos. O que posso fazer por você?}
{197}{}{Let me see what you have in stock.}
{198}{}{Actually, do you mind if I ask you some questions instead?}
{199}{}{Nothing today, actually.}
{200}{}{So... you're Citizen }
{201}{}{Yeah, he said you'd be stopping by... }
{202}{}{Tudo certo.}
{203}{}{Actually, never mind, I'll come back later for it.}
{204}{}{Okay, here you go. One Hy-Mag. Kinda looks like a lava lamp, doesn't it? Oh, don't drop it... it's pretty fragile.}
{205}{}{Say, what else do you have in stock?}
{206}{}{Se importa se eu te fizer algumas perguntas?}
{207}{}{Thanks. I might stare at this for a few hours before taking it to the Gecko plant.}
{208}{}{Got it. Thanks for the part.}
{209}{}{Yeah, the First Citizen said you'd be stopping by... Captain. (Winks.) Let me tell you, Captain, you've got a BEAUTY waiting for you.}
{210}{}{Yeah, the First Citizen said you'd be stopping by. Well, let me tell you, friend, you got a BEAUTY waiting for you.}
{211}{}{O que é?}
{212}{}{Actually, keep it for me. I'll pick it up later.}
{213}{}{Nothing less than a Heckler and Koch G11, one of the best assault weapons ever made...(hefts weapon, passes it to you)...fires a 4.7 mm caseless cartridge, 50-round magazine. When it talks, people listen.}
{214}{}{I'll bet. Thanks.}
{215}{}{No problem. Plus, here... have a couple of frag grenades on me. Consider it my thanks for wiping out those raiders.}
{216}{}{Great. Can I see what else you have in stock?}
{217}{}{Posso fazer mais algumas perguntas?}
{218}{}{Thanks. I'll put them to good use.}
{219}{}{That'll do it for you, then?}
{220}{}{Se importa se eu fizer algumas outras perguntas?}
{221}{}{Yeah, that'll be it for today.}
{222}{}{Yeah, I know. I'm still waiting for the requisition lists to clear the server, but it's going to be a while. Don't know what to say. Things just take time.}
{223}{}{I see. Mind if I ask you some other questions?}
{224}{}{Maybe I can go find those tools somewhere else, then.}
{225}{}{!}
{226}{}{, huh? Wait one minute, and I'll go get you the Hydroelectric Magneto... uh, the Hy-Mag.}
{227}{}{, right? Wait one minute, and I'll go get you the Hydroelectric Magneto... uh, the Hy-Mag.}
{228}{}{Obrigado.}
{229}{}{[continuar]}
