{100}{}{You see Citizen Sergeant Stark.}
{101}{}{You see a huge black man in heavy armor. He's watching you carefully.}
{102}{}{You see Citizen Sergeant Stark.}
{103}{}{You see a huge black man in heavy armor. He's watching you carefully.}
{104}{}{Good job down south. Saw the fireworks all the way up here.}
{105}{}{Good day... sir.}
{106}{}{Vault City prevails... sir.}
{107}{}{Bom dia, Citizen.}
{108}{}{Vault City prevails, Citizen.}
{109}{}{You'll wish you stayed out of the city... Guards!}
{110}{}{Um mutante! Guardas!}
{111}{}{Um ghoul! Guardas!}
{112}{}{Need to compile those ammunition lists...}
{113}{}{Need to check the weapon lockers down in the Vault tomorrow...}
{114}{}{Maybe being in these cells will teach you to behave yourselves.}
{115}{}{And you'll STAY in these cells until the First Citizen pardons you.}
{116}{}{I'm sorry, Citizen, but no one's permitted in the Corrections Center after dark. Come back in the morning.}
{117}{}{It's past curfew. What are you still doing in the city?}
{118}{}{Yah!}
{119}{}{Uh, as a Citizen, I am allowed to be in the city after dark.}
{120}{}{I just had some business to take care of before I left.}
{121}{}{I'm leaving right now.}
{122}{}{Is that so? Well, I know EVERY Citizen in Vault City, and I don't recognize you. Where's your papers?}
{123}{}{You want them? Come get them.}
{124}{}{I don't have them on me.}
{125}{}{Aqui está.}
{126}{}{Then stop wasting my time, "Citizen." Come on, let's move it.}
{127}{}{Your business is over for the day. Come on, let's move it.}
{128}{}{I'm not going anywhere. You try and move me, you'll regret it.}
{129}{}{Tudo bem, eu vou.}
{130}{}{Captain. Can I help you... sir?}
{131}{}{Posso ajudá-lo, Cidadão?}
{132}{}{O que você quer?}
{133}{}{Yah!}
{134}{}{Desliga}
{135}{}{Quem é você?}
{136}{}{Nothing, sorry to disturb you.}
{137}{}{Come with me, boy. NOW.}
{138}{}{Venha comigo, moça. AGORA.}
{139}{}{Eu sair? Eu sair!}
{140}{}{EU NÃO VOU. AGORA.}
{141}{}{Você vai desejar ter ido embora.}
{142}{}{EU NÃO VOU.}
{143}{}{Sargento Stark... senhor. O senhor precisa de algo?}
{144}{}{Eu sou o Cidadão Sargento Stark, Cidadão. Tem algo em que eu possa ajudá-lo?}
{145}{}{Eu sou o Cidadão Sargento Stark, Forasteiro. O que você procura?}
{146}{}{O que você faz aqui?}
{147}{}{Você pode me dizer onde fica a Vault?}
{148}{}{Nothing, sorry to disturb you.}
{149}{}{Eu faço o SEU trabalho, senhor.}
{150}{}{I run the Corrections Center. And obey your orders, sir.}
{151}{}{I run the Corrections Center. Keep the Outworlders in line. Make sure the Servants behave. Organize patrols. Try and protect the city from raiders.}
{152}{}{Algum problema, sargento?}
{153}{}{Você quem invadiu o bar de Cassidy?}
{154}{}{Você já ouviu falar de um servo chamado Joshua?}
{155}{}{Patrulhas?}
{156}{}{Saqueadores?}
{157}{}{Sobre os saqueadores...}
{158}{}{Posso te fazer algumas perguntas?}
{159}{}{Obrigado. Adeus.}
{160}{}{Permissão para falar livremente, senhor.}
{161}{}{Concedido.}
{162}{}{Não. Eu tinha algumas outras perguntas primeiro.}
{163}{}{Hoje não, sargento.}
{164}{}{Você não MERECE o seu posto. Eu vivi em Vault City toda a minha vida. Os homens e mulheres sob MEU comando confiam em mim e me respeitam, não você... senhor.}
{165}{}{É por isso que preciso de você em seu posto, sargento. Não há dúvida de que você é capaz e conhece Vault City melhor do que eu. No entanto, obtive RESULTADOS e você NÃO. Nunca esqueça disso.}
{166}{}{Anotado, Sargento. Agora eu tenho algumas perguntas para você.}
{167}{}{Anotado, Sargento. Sugiro que engula sua atitude e continue fazendo seu trabalho. Bom dia.}
{168}{}{Entendido, senhor.}
{169}{}{Agora eu tenho algumas perguntas para você.}
{170}{}{Continue então, sargento.}
{171}{}{Sim, senhor. Conduzi uma batida autorizada no estabelecimento do Sr. Cassidy.}
{172}{}{Talvez seu amigo Cassidy não tenha te contado que tinha substâncias ilegais no local e que sua licença para distribuição de álcool havia expirado. Você se esqueceu de dizer isso ao seu amigo aqui, Cassidy?}
{173}{}{Cassidy disse que ele estava tudo pago e você invadiu a casa dele de qualquer forma.}
{174}{}{Esqueça. Eu tinha outras perguntas...}
{175}{}{Deixa pra lá então. Adeus.}
{176}{}{Não, senhor. O Sr. Cassidy não pagou sua taxa de licenciamento de álcool no mês, mas ainda estava vendendo no local. Sua lista de pagamentos está registrada no computador.}
{177}{}{Cassidy era culpado de posse sem licença. Se não gostar, pode sair de Vault City. Simples assim.}
{178}{}{I believe you, Sergeant. Well done. Now listen to me: I want you to pardon Mr. Cassidy, wipe his record clean, and pay him restitution for the damages you caused his establishment.}
{179}{}{You know, I think my fist and your face are about to have a conversation.}
{180}{}{Esqueça. Eu tinha outras perguntas...}
{181}{}{Não faz mal. Tchau.}
{182}{}{Thanks for looking out for me, friend. Stark's one stubborn sonuvabitch.}
{183}{}{Just try it. I'll look forward to putting trash like you and Cassidy in their place.}
{184}{}{Fine. I was looking forward to kicking your ass anyway.}
{185}{}{Esqueça. Eu tinha outras perguntas...}
{186}{}{Não faz mal. Tchau.}
{187}{}{Yes... SIR.}
{188}{}{NOW, Sergeant.}
{189}{}{Come on, Sergeant. Chop-chop.}
{190}{}{Here you are, SIR.}
{191}{}{Now I have some questions for you, Sergeant.}
{192}{}{Very good, Sergeant. Carry on.}
{193}{}{Yeah, he was that drunk Outworlder who struck one of my guards in that brawl in the Spittoon. He's over at the Servant Allocation Center getting... broken in. It's just down the street.}
{194}{}{I had another question...}
{195}{}{Hmmm. I'll head over there now.}
{196}{}{The Vault's right outside the door... sir.}
{197}{}{The Vault's right outside the door. Just tell the guards you're a Citizen, and they'll let you through.}
{198}{}{O Vault do outro lado da porta. Só cidadãos podem entrar lá, então não quero pegar você incomodando os guardas.}
{199}{}{Posso pedir mais uma coisa?}
{200}{}{But I am a Citizen.}
{201}{}{Como você se torna um cidadão?}
{202}{}{Obrigado. Adeus.}
{203}{}{Isso mesmo? Não te reconheço, e conheço todos os Cidadãos de Vault City.}
{204}{}{Aqui estão meus documentos. Acho que você vai encontrar tudo em ordem.}
{205}{}{Uh, não importa. Eu tinha outras perguntas...}
{206}{}{É melhor eu ir.}
{207}{}{Well, well, if it isn't those papers that were stolen last month. Looks like I finally found the culprit. Come with me, Outsider.}
{208}{}{Touch me, and you'll regret it.}
{209}{}{I'm going, I'm going. Stop pushing.}
{210}{}{I was BORN a Citizen. Interested in becoming a Citizen? Find a council member.}
{211}{}{Posso pedir mais uma coisa?}
{212}{}{I will, thanks. Goodbye.}
{213}{}{Yeah, what about them?}
{214}{}{I found their base.}
{215}{}{I wiped them out.}
{216}{}{Any idea where these raiders are striking from?}
{217}{}{Never mind. I had some questions...}
{218}{}{Forget it. Maybe we'll talk some other time.}
{219}{}{You did? Where is it?}
{220}{}{Yes, you said that before. You should tell the First Citizen if you haven't already.}
{221}{}{Down south, in a series of caves in the mountains. Here, let me point it out...}
{222}{}{I had some questions for you.}
{223}{}{All right. I'll go tell her.}
{224}{}{You wiped them out?}
{225}{}{Yes, you said that before. You should tell the First Citizen if you haven't already.}
{226}{}{Yeah, Vault City shouldn't have to worry about them anymore.}
{227}{}{I had some questions for you.}
{228}{}{All right. I'll go tell her.}
{229}{}{Go tell the First Citizen at once. She'll want to know about this immediately.}
{230}{}{I had some questions first.}
{231}{}{All right. I'll go tell her.}
{232}{}{Yeah, raiders. They've been hitting us pretty hard lately. (Frowns.) Why do you want to know about them?}
{233}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{234}{}{Eu estava apenas curioso.}
{235}{}{Never mind. I had some questions...}
{236}{}{Forget it. Maybe we'll talk some other time.}
{237}{}{O quê, você é algum tipo de bom samaritano? Eu não engulo.}
{238}{}{Eu não sou um samaritano. Na verdade, sou natural de Arroyo - é uma vila a oeste.}
{239}{}{Gostaria de ajudar se pudesse.}
{240}{}{Olha, eu já vi o suficiente no mundo para saber que ajudar as pessoas compensa no final quando você recebe ajuda.}
{241}{}{Never mind. I had some questions...}
{242}{}{Forget it. Maybe we'll talk some other time.}
{243}{}{O que, você veio aqui para ser um espertinho? É Isso?}
{244}{}{Oh sim? Bem, enfrentar esse bando de invasores pode ser mais do que você pode suportar.}
{245}{}{Não, mas se precisar de ajuda, estou à disposição.}
{246}{}{Eu ainda gostaria de tentar ajudar.}
{247}{}{Deixa pra lá então. Eu tinha algumas perguntas...}
{248}{}{Forget it. Maybe we'll talk some other time.}
{249}{}{Hmmm. Bem, não vou recusar nenhuma ajuda neste momento. Você encontra a base deles, ou melhor ainda, os elimine, vá contar a Primeira Cidadã.}
{250}{}{Actually, I already found their base.}
{251}{}{Actually, I wiped them out already.}
{252}{}{Any idea where these raiders are striking from?}
{253}{}{Certo. Eu tenho outras perguntas...}
{254}{}{Eu vou fazer isso.}
{255}{}{Curious, huh? So am I. Now, what do you know about the raiders?}
{256}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{257}{}{I don't know anything. That's why I'm asking you.}
{258}{}{Never mind. I had some questions...}
{259}{}{Forget it. Maybe we'll talk some other time.}
{260}{}{Não sabe de nada? Talvez eu te deixe aqui no Centro Correcional até você LEMBRAR de algo.}
{261}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{262}{}{Você me pegou. Obviamente sou cumplice dos invasores, me prenda.}
{263}{}{Olha, estou saindo daqui agora. Se você tentar me impedir, teremos problemas.}
{264}{}{Você já está com problemas. Quer piorar ainda mais?}
{265}{}{Não, gostaria de tentar encontrar a base deles, talvez parar os ataques se puder.}
{266}{}{Você me pegou. Obviamente sou cumplice dos invasores, me prenda.}
{267}{}{Estou indo embora. Você quer me parar? Vá em frente.}
{268}{}{Tudo bem, então...}
{269}{}{Hei! Hei! Eu não --}
{270}{}{Viva com isso, homem morto.}
{271}{}{Acho que não vamos abandonar o assunto tão facilmente. Agora... o que você sabe sobre os invasores?}
{272}{}{I'd like to try and find their base, maybe stop the attacks if I can.}
{273}{}{Eu estava apenas curioso.}
{274}{}{Olha, estou saindo daqui agora. Se você tentar me impedir, teremos problemas.}
{275}{}{Não sei, esses invasores não fazem muito sentido. SE eles são invasores.}
{276}{}{O que você quer dizer?}
{277}{}{Eu tenho mais algumas perguntas...}
{278}{}{Tenho que ir.}
{279}{}{Eles têm poder de fogo pesado, armamento caro. Eles conhecem táticas militares, ficam em formação. Eles nunca cruzam suas linhas de fogo, e sempre param de romper nossas defesas.}
{280}{}{Uh... eles param de romper as defesas?}
{281}{}{Eu tenho mais algumas perguntas...}
{282}{}{Tenho que ir.}
{283}{}{Eu os vi fazer isso. No último ataque, eles desativaram uma torreta laser no perímetro oeste. Eles tinham uma visão clara da cidade. Então eu vi um de seus "capitães" ORDENAR que eles recuassem. Não faz sentido.}
{284}{}{Alguma ideia de onde eles estão vindo?}
{285}{}{Hmmm. Eu tenho outras perguntas…}
{286}{}{Interessante. Eu tenho que ir.}
{287}{}{Não, essa é a parte mais frustrante. Eles continuam recuando para o sul. Não posso dispensar homens para patrulhar a área. Acho que os invasores têm algum guia nativo que os conduz pelos desfiladeiros do sul.}
{288}{}{Algum problema com o sul?}
{289}{}{Hmmm. Eu tenho outras perguntas…}
{290}{}{Interessante. Eu tenho que ir.}
{291}{}{Muitos lugares para se esconder se você não souber onde procurar. Esse lugar é lotado de cavernas.}
{292}{}{Eu provavelmente poderia encontrá-los.}
{293}{}{Eu tenho mais algumas perguntas...}
{294}{}{Hmmm. Vou me lembrar disso. Adeus.}
{295}{}{Vá em frente e tente, aposto que a única maneira de encontrá-los é se eles nos derem um mapa.}
{296}{}{Eu tenho mais algumas perguntas...}
{297}{}{Se for necessário... obrigado pela informação.}
{298}{}{Sim, temos um pequeno grupo de patrulhas. Mal posso dispensar os homens para proteger Vault City, muito menos fazer todo o reconhecimento que precisa ser feito.}
{299}{}{Recon-o-que?}
{300}{}{Eu viajo muito. Posso ajudar em alguma coisa?}
{301}{}{Lamento ouvir isso. Eu tinha outras perguntas...}
{302}{}{Deixa pra lá então. Adeus.}
{303}{}{Exploração.}
{304}{}{O que você quer dizer?}
{305}{}{Eu poderia fazer algum reconhecimento se você estiver com falta de pessoal.}
{306}{}{Esqueça. Eu tinha outras perguntas...}
{307}{}{Deixa pra lá então. Adeus.}
{308}{}{Não, você precisaria de um Pip-Boy para fazer o trabalho direito, e não posso emprestar um agora.}
{309}{}{Eu já tenho um Pip-Boy. É velho... e mal-humorado... e parece ter fios e botões arrancados por toda parte... mas funciona.}
{310}{}{Bem, tudo bem. Eu tinha outras perguntas...}
{311}{}{Deixa pra lá então. Adeus.}
{312}{}{Sim? Tem um mapa-múndi do norte da Califórnia instalado?}
{313}{}{Sim. Bem, pelo menos o que você pode ver por causa da incerteza com que ele mostra todo esse maldito lixo.}
{314}{}{Eu tenho um trabalho para você, então. Preciso de alguém para explorar o terreno ao redor de Gecko... aquele acampamento ghoul a nordeste. Inspecione os oito setores no mapa ao redor da cidade e depois reporte.}
{315}{}{Por quê?}
{316}{}{Sem problemas. Eu já explorei a área.}
{317}{}{Tudo bem. Voltarei quando tiver feito o reconhecimento da área.}
{318}{}{Pensando bem, conte comigo. Adeus.}
{319}{}{If they keep poisoning our groundwater, we may be forced to take military action.}
{320}{}{I want to see how much damage the plant meltdown caused to the area.}
{321}{}{We may be forced to take military action against them in the future, especially if they start poisoning the groundwater again.}
{322}{}{Now do you want the job or not?}
{323}{}{Yes. I've already scouted out the area, though.}
{324}{}{I'll take the job. I'll report back when I'm done.}
{325}{}{Eu aceito o trabalho. Mas eu tinha algumas perguntas primeiro...}
{326}{}{Não, obrigado. Talvez outra hora.}
{327}{}{Isso mesmo? Hehe. Bem... tudo bem então.}
{328}{}{Bom trabalho. Transfira a informação para o meu Pip-Boy, e vou registrá-la nos computadores da patrulha.}
{329}{}{Tudo bem...}
{330}{}{Essa informação parece boa, bom trabalho. Aqui está o seu pagamento... trezentos dólares.}
{331}{}{Tudo bem então... você tem mais trabalho para mim?}
{332}{}{Ótimo. Eu tinha algumas outras perguntas...}
{333}{}{Obrigado. Prazer em fazer negócios com você.}
{334}{}{Sim, na verdade... Preciso de alguém para viajar para a NCR. Ultimamente, tenho ouvido
 relatos de que a República pode estar aumentando o poderio militar. Verdade ou não, preciso de alguém para traçar uma rota até a NCR e relatar.}
{335}{}{Sem problemas. Já está feito.}
{336}{}{Basta viajar para a NCR e depois voltar?}
{337}{}{Esqueça. Eu tinha outras perguntas...}
{338}{}{No thanks. Goodbye.}
{339}{}{Isso é tudo que preciso. Estou mais interessado na rota do que na própria República, mas ainda precisarei que você entre na cidade assim que chegar lá.}
{340}{}{Sem problemas. Já está feito.}
{341}{}{I'll take the job. I'll report back when I'm done.}
{342}{}{Eu aceito o trabalho. Eu tinha algumas perguntas antes de sair...}
{343}{}{Não, obrigado. Eu tinha algumas outras perguntas...}
{344}{}{Acho que não quero esse trabalho. Talvez outra hora.}
{345}{}{Isso mesmo? Hehe.}
{346}{}{Tudo bem, então. Transfira a informação para o meu Pip-Boy, e vou registrá-la nos computadores da patrulha.}
{347}{}{Tudo certo.}
{348}{}{Essa informação parece boa, bom trabalho. Aqui está o pagamento por seus serviços, quinhentos dólares... Além disso, você pode achar isso útil.}
{349}{}{O que é?}
{350}{}{É um sensor de movimento Vault-Tec. Íamos desmontá-lo por partes, já que é muito velho para os nossos Pip-Boys, mas parece que é compatível com o seu modelo.}
{351}{}{Como funciona?}
{352}{}{Mantenha em sua mão e ele identificará os inimigos em sua área imediata ao usá-lo. Ou você pode ativar o automapa do Pip-Boy normalmente, então basta clicar no botão "scanner" e eles serão iluminados como um letreiro de néon.}
{353}{}{Obrigado, isso pode ser útil. Então, posso te fazer algumas outras perguntas?}
{354}{}{Te agradeço muito. Eu vou tentar.}
{355}{}{Olá... Capitão. Você queria alguma coisa?}
{356}{}{Olá novamente, Cidadão. Algo em que posso ajudá-lo?}
{357}{}{Você está de volta? Está perdido, ou precisa de alguma coisa?}
{358}{}{Como o que... senhor?}
{359}{}{Yes, Citizen. What did you want to know?}
{360}{}{Como o quê?}
{361}{}{Hep-Hep Schlep-Bep}
{362}{}{Desliga}
{363}{}{You got some kind of problem, Sergeant?}
{364}{}{Você quem invadiu o bar de Cassidy?}
{365}{}{Have you heard of a Servant named Joshua?}
{366}{}{O que você faz aqui?}
{367}{}{Você pode me dizer onde fica a Vault?}
{368}{}{I surveyed the area around Gecko for you.}
{369}{}{Got any more recon work for me?}
{370}{}{I plotted that route to NCR for you.}
{371}{}{Sobre os saqueadores...}
{372}{}{Never mind. Goodbye.}
{373}{}{Bom dia... senhora.}
{374}{}{Vault City prevails... ma'am.}
{375}{}{Captain. Can I help you... ma'am?}
{376}{}{Sergeant Stark... ma'am. Did you need something?}
{377}{}{I do YOUR job, ma'am.}
{378}{}{I run the Corrections Center. And obey your orders, ma'am.}
{379}{}{Permission to speak freely, ma'am.}
{380}{}{You don't DESERVE your post. I have lived in Vault City all my life. The men and women under MY command trust me and respect me, not you... ma'am.}
{381}{}{Understood, ma'am.}
{382}{}{Yes, ma'am. I conducted an authorized raid on Mr. Cassidy's establishment.}
{383}{}{No, ma'am. Mr. Cassidy had not paid his licensing fee for alcohol for the month, yet was still selling it on the premises. His list of payments are logged in the computer.}
{384}{}{Yes... MA'AM.}
{385}{}{Here you are, MA'AM.}
{386}{}{You pulled rank on Stark to help out your friend Cassidy.}
{387}{}{The Vault's right outside the door... ma'am.}
{388}{}{You have scouted Gecko for Vault City.}
{389}{}{You have scouted NCR for Vault City.}
{390}{}{Like what... ma'am?}
{391}{}{Yeah, there is something... I have been looking through your reconnaissance report and I found a small village nearby swarming with uhh..."mole rats", that's what the outsiders call them, right? I want you to go there and exterminate all those beasts.}
{392}{}{Just gun down a few rats? Ok, I'm on it.}
{393}{}{What for?}
{394}{}{E a expedição da NCR?}
{395}{}{Vou pensar sobre isso. Posso te fazer algumas perguntas?}
{396}{}{Não, não é o meu tipo de trabalho. Adeus.}
{397}{}{Excelente. Aqui, deixe eu te mostrar a localização exata da aldeia. [Stark marca a vila em seu mapa no Pip-Boy.] Te pago $750, basta voltar e pegar assim que terminar a tarefa. Mais uma coisa... se você não resolver isso em um mês, vou mandar um esquadrão lá para eliminar os monstros... e qualquer outra ameaça.}
{398}{}{Adeus.}
{399}{}{Para que? [Ele hesita por um momento, então franze a testa.] Não preciso explicar meus motivos para você. Eu dou ordens, e você recebe, é assim que funciona. Se você não quer o trabalho, enviarei um esquadrão para fazer... mas às vezes as coisas ficam um pouco "bagunçadas" quando solto meus garotos.}
{400}{}{Entendi. Eu aceito o trabalho.}
{401}{}{Está claro. O que há com aquela vila, afinal?}
{402}{}{Sobre a vila...}
{403}{}{Você matou todos aqueles ratos grandes e feios? Realmente?}
{404}{}{Me disseram que você planeja transformar as pessoas daquela vila em servos, e que os ratos toupeira estavam impedindo você de fazer isso, essa é a verdadeira razão que você queria que eles fossem exterminados.}
{405}{}{Sim.}
{406}{}{Ainda não.}
{407}{}{Oh, ficou sabendo disso, não é? Bem, você ouviu direito, é para o bem deles. Aqui, eles seriam bem alimentados e cuidados. Tenho certeza de que eles perceberam o quanto é melhor servir na grande Vault City do que morar naquela pequena vila com merda de rato até os joelhos.}
{408}{}{Eles estão felizes onde estão.}
{409}{}{Não importa. Você completará sua tarefa ou não?}
{410}{}{OK. Eu vou terminar ela.}
{411}{}{Não, não penso assim. }
{412}{}{Ótimo, volte quando terminar.}
{413}{}{Não importa, todos eles se tornarão servos da mesma forma. Estou enviando um esquadrão de luta para lá imediatamente. Em breve, não haverá mais nada em sua pequena aldeia.}
{414}{}{[FEITO]}
{415}{}{Volte quando tudo estiver pronto.}
{416}{}{Ótimo trabalho, soldado. Aqui estão seus $750, um pequeno preço a pagar por uma vila cheia de novos servos. Você prestou um grande serviço a Vault City.}
{417}{}{Espere, você nunca disse nada sobre fazer dos aldeões seus servos.}
{418}{}{Como queira. Adeus.}
{419}{}{É para o bem deles, uma vez que serão servos de Vault City, não haverá necessidade de lutar pela sobrevivência. Eles serão alimentados e cuidados. Em troca, eles trabalharão para o bem da cidade. Todos ganham.}
{420}{}{Isso é escravidão!}
{421}{}{Não é escravidão, mas uma coexistência mutuamente benéfica, uma simbiose, por assim dizer.}
{422}{}{Asqueroso! Adeus.}
{423}{}{Esses primitivos devem ter enlouquecido completamente. Eles obtiveram armas de algum lugar e começaram a atirar em nós à primeira vista! Então isso me ocorreu outro pensamento, que se dane eles. Afinal, não é como se estivéssemos escravos... quero dizer, servos.}
{424}{}{Que aldeia? Oh, aquela de quem pegamos nossos novos servos... e o que tem isso?}
{425}{}{Você diz o que!? Você escravizou todos eles?}
{426}{}{Eu sei quem lhes forneceu armas. Era aquele comerciante no pátio, Harry. }
{427}{}{Harry Alegre, isso você diz?... imagino que seja um daqueles canalhas no pátio. Ok, eu vou lidar com ele. Veremos como ele ficará "alegre" quando eu terminar. Quanto a você, pode pegar o que encontrar na loja dele como recompensa por ter me informado.}
{428}{}{Não sei por que, mas o procônsul McClure me ordenou que esperasse um pouco na questão da aldeia. Isso se aplica a você também. }
{429}{}{Hmm... Ok.}
{1215}{}{I convinced their guide to no longer lead them through the mountains. They will never find their way without him.}
{1224}{}{You did? So, they will no longer be a threat to us?}
{1251}{}{Actually, I already put a stop to them. I convinced their guide to no longer lead them through the mountains. They will never find their way without him.}
{1422}{}{Well, I agree. They're better off this way. Goodbye.}
