{100}{}{Ao entrar na pequena aldeia, seu nariz é entupido pelo cheiro familiar de roedor. Você vê vários ratos-toupeira andando por aí. Estranhamente, eles não parecem interessados em atacar você ou os camponeses que moram aqui.}
{101}{}{The village appears to be empty. The air reeks of rotting mole rat carcasses.}
{102}{}{The village has changed a lot since your last visit.}
{103}{}{Even more has changed since you were last here. It seems the protection of the mole rats has been replaced with a wall.}
{104}{}{Hey! Where'd everybody go?}
