{100}{}{Esse terminal está mostrando uma série de barras verdes que sobem e descem irregularmente.}
{101}{}{Você vê um terminal médico de Vault City. }
{102}{}{Esse terminal está mostrando uma série de barras verdes que sobem e descem irregularmente.}
{103}{}{Você poderá pegar mais informações deste terminal possuindo maior familiaridade científica.}
{104}{}{Você não consegue identificar como funciona este terminal.}
{105}{}{Porcaria de computadores.}
{106}{}{Você não consegue identificar como funciona este terminal.}
{107}{}{Pipó-pipó bizz}
{108}{}{Você conseguiu acessar os dados do terminal médico de Vault City. Embora a enterface seja muito complicada de entender,
e os dados parecem estar severamente danificados.}
{109}{}{Pesquisar arquivos de localização das Vaults.}
{110}{}{Pesquisar por arquivos que mencionam a GECK.}
{111}{}{Pesquisar na base de dados médica por alguma coisa interessante.}
{112}{}{Deslogar do terminal.}
{113}{}{Você não encontrou nenhuma mensão sobre as Vaults na base de dados.
Tem apenas informações médicas relatando anatomia, doenças conhecidas, tratamentos, remédios e implantes.}
{114}{}{Pesquisar por arquivos que mencionam a GECK.}
{115}{}{Pesquisar na base de dados médica por alguma coisa interessante.}
{116}{}{Deslogar do terminal.}
{117}{}{Você não encontrou nenhuma mensão sobre as Vaults na base de dados.
Tem apenas informações médicas relatando anatomia, doenças conhecidas, tratamentos, remédios e implantes.}
{118}{}{Pesquisar arquivos de localização das Vaults.}
{119}{}{Pesquisar na base de dados médica por alguma coisa interessante.}
{120}{}{Deslogar do terminal.}
{121}{}{Você pesquisa na base de dados médica, a terminologia é muito formal para o entendimento.
Se você possui conhecimento de medicina, não terá problemas para o entendimento.}
{122}{}{Continuar a pesquisa nos arquivos do computador.}
{123}{}{Deslogar do terminal.}
{124}{}{Você pesquisa na base de dados e nota as incriveis informações contidas nos arquivos.
As recentes pesquisas conduzidas em Vault City são fascinantes, e a técnologia médica está alem de qualquer coisa que você já viu.}
{125}{}{Você pesquisa no banco de dados outra vez, porem não descobre nada novo. Os esquemas mostrados são na maioria informações inúteis.
É possível que você tenha perdido algo, porem você acha que é pouco improvável.}
{126}{}{Você pesquisa na data base denovo... mais uma vez... porem nada novo.
Talvez se você pesquisar mais vinte vezes conseguirara encontrar alguma coisa.}
{127}{}{Nós estamos apenas brincando. Realmente não existe mais nada por aqui.
Talvez se você vasculhar os arquivos mais umas trinta vezes, você poderá encontrar algo enterrado bem fundo em um dos arquivos. Ha-ha.}
{128}{}{Hum... veja, vá jogar o resto do jogo. Você não pode ficar aqui para sempre.}
{129}{}{Esta bem. Continue olhando, pouco me importa.}
{130}{}{Você está apenas perdendo seu tempo.}
{131}{}{Sua inteligência é 4, certo?}
{132}{}{Deixe disso.}
{133}{}{Por que você não vai brincar com a enfermeira?}
{134}{}{Não tem nada aqui!}
{135}{}{Você procura nos arquivos e não encontra nada.}
{136}{}{Você pesquisa no terminal umas 53 vezes. Você não encontra nada que interessa.}
{137}{}{Só tem que pesquisa mais uma vez, não? Que coisa...}
{138}{}{Ok, olha. Esse é o grande secredo, tenha certesa de acessar o computador principal no terceiro level após você terminar o jogo.
Agora deslogue deste terminal e vá brincar lá fora.}
{139}{}{Você procura nos arquivos e não encontra nada.}
{140}{}{Continuar a pesquisa dos arquivos.}
{141}{}{Pesquisar na base de dados novamente para ter certesa que não passou nada despercebido.}
{142}{}{Continuar a pesquisa dos arquivos.}
{143}{}{Deslogar do terminal.}
{144}{}{Você passa uma hora estudando os arquivos. Você se aprofunda no banco de dados e localiza uma série de velhos documentos
contendo esquemas para uma espécia de "implante de combate."}
{145}{}{Estudar a informação do implante.}
{146}{}{O esquema detalha uma operação para a implantação de placas de impacto e membranas de dissipação térmica em um esqueleto humando.
Concedendo-lhe grande resistencia a danos físicos e calor. Parece um procedimento complicado.}
{147}{}{Faça uma anotação do mesmo e pesquise no banco de dados para mais informações.}
{148}{}{Gravar as informações e em seguida deslogar do terminal.}
{149}{}{Você voltou para o menu inicial. Uma série de arquivos e programas de pesquisa são listados na tela do terminal.}
{150}{}{Pesquisar por qualquer menção da Vault 13 nos arquivos.}
{151}{}{Pesquisar por qualquer referencia sobre a GECK.}
{152}{}{Pesquisar na base de dados médica por alguma coisa interessante.}
{153}{}{Deslogar do terminal.}
{200}{}{Você terminou de estudar o banco de dados médicos da Vault City.}
{201}{}{Seu amigo tenta fazer você se interessar na tela colorida que faz BIP BIP, porem você não imagina como se abre. Eventuamente você fica entediado e a deixa sózinha.}
{202}{}{Saindo fora.}
{203}{}{*Beep*}
{204}{}{*Biiiiip-boop*}
{205}{}{*Diiiii-doop*}
{206}{}{*Bee-Oop*}
{207}{}{*Beep*}
{208}{}{PING!}
{209}{}{Me desculpe Dave, eu não posso fazer isso.}
{210}{}{Perigo! Will Robinson!}
{211}{}{Trinta segundos para se afastar a uma distancia segura.}
{212}{}{PING! Eu falei!}
{213}{}{Favor remover seu cartão e retirar seu dinheiro.}
{214}{}{Jogo estranho. A única forma de ganhar e não jogar.}
