{100}{}{Voce ve um croupier.}
{101}{}{Você vê uma mesa de dados.}
{110}{}{Você vê uma garota.}
{111}{}{Voce ve uma mesa.}
{140}{}{Você vê uma mesa para jogar jogos de dados.}
{141}{}{Você vê uma mesa com coisas sobre ela.}
{150}{}{Você vê um dos crupiês do cassino.}
{151}{}{Você vê uma das crupiês do cassino. Ela gesticula para que você venha brincar.}
{152}{}{Você vê uma das crupiês do cassino. Seu vestido mal cobre seu corpo.}
{153}{}{Você vê uma das crupiês do cassino. Ela tem um monumental par de coxas.}
{154}{}{Você vê uma das crupiês do cassino. Ela pisca para você.}
{155}{}{Você vê uma das crupiês do cassino. Ela é muito cheirosa.}
{160}{}{Você vê uma mulher bonita.}
{161}{}{Ela está acenando para você vir.}
{162}{}{O vestido dela é meio pequeno.}
{163}{}{Ela tem alguns jogos legais.}
{164}{}{Ela pisca para você.}
{165}{}{Ela cheira muito bem.}
{175}{}{FALTAM DADOS!!!}
{176}{}{DADOS DEMAIS!!!}
{177}{}{The odds seem right ever since you switched the dice.}
{178}{}{As chances não são boas.}
{179}{}{Você não consegue calcular suas chances com certeza.}
{185}{}{The odds seem about right.}
{186}{}{Você não consegue calcular suas chances com certeza.}
{187}{}{As chances não são boas.}
{200}{}{::Assobios::}
{201}{}{::Palmas::}
{202}{}{::Assobios::}
{203}{}{}
{204}{}{Thought you'd forgotten about us while you were off saving the world.}
{215}{}{Olá, }
{216}{}{Se precisar de companhia mais tarde...}
{217}{}{Hey, you...[winks]...you looking to gamble?}
{218}{}{He looks so...[shivers]...dangerous.}
{219}{}{Bem vindo ao cassino, }
{220}{}{Fale bem de mim pro chefe, beleza?}
{221}{}{Olá, madame. Se eu puder ajudar em algo é só me dizer.}
{222}{}{Quer jogar, senhorita?}
{223}{}{She looks so...[shivers]...dangerous.}
{235}{}{Parece que este já está jogando com a vida.}
{236}{}{Uh, eu acho que ele entrou no cassino errado...}
{237}{}{Se ele não sair antes que os rapazes o vejam...}
{238}{}{Oh-oh. Problema...}
{239}{}{Parece que já esta jogando com a vida.}
{240}{}{Uh, eu acho que ela entrou no cassino errado...}
{241}{}{Se ela não sair antes que os rapazes a vejam...}
{250}{}{Ei, músculos. Você quer gastar algumas tampas?}
{251}{}{Hey, champ...[winks]...you looking to gamble?}
{252}{}{Hey, champ...[smiles]...wanna take a chance?}
{253}{}{Se precisar de companhia mais tarde...}
{254}{}{Me pergunto se eu deveria falar com ele...}
{255}{}{Ei, }
{256}{}{Se você quer ganhar algumas tampas, veio ao lugar certo.}
{257}{}{Dona Sorte está em casa esta noite... Somente vencedores!}
{258}{}{Adiante, }
{259}{}{Precisa de outra bebida?}
{260}{}{Bem vindo ao cassino, }
{261}{}{Olá, }
{262}{}{Com certeza quer jogar, }
{263}{}{Bem vindo ao cassino, }
{270}{}{Olá, estrela. Você quer gastar algumas tampas?}
{271}{}{Ei, }
{272}{}{Ei, }
{273}{}{Se você está querendo ganhar algumas tampas }
{274}{}{Dona Sorte está em casa esta noite... Somente vencedores!}
{275}{}{Adiante, }
{276}{}{Precisa de outra bebida?}
{277}{}{Bem vindo ao cassino, }
{278}{}{Hey there, Ms. Movie Star. Looking to spend a paycheck?}
{279}{}{Quer dançar essa noite?}
{290}{}{Ei, querida. Você quer gastar algumas tampas?}
{291}{}{Hey, sweetie...[winks]...you looking to gamble?}
{292}{}{Ei, docinho... [sorri]... quer arriscar?}
{293}{}{Se você quer ganhar algumas tampas, veio ao lugar certo.}
{294}{}{Dona Sorte está em casa esta noite... Somente vencedores!}
{295}{}{Vamos lá, ganhe algumas tampas.}
{296}{}{Precisa de outra bebida, docinho?}
{297}{}{Bem vindo ao cassino, docinho.}
{298}{}{Essa mesa é grátis se você quiser jogar...}
{299}{}{Ei, docinho. Você quer gastar algumas fichas?}
{300}{}{Quer jogar, docinho?}
{301}{}{Bem vindo ao cassino, docinho.}
{320}{}{[O croupier olha para você nervosamente, então morde o lábio.] Hum, façam suas apostas... aposta mínima $}
{321}{}{Faça sua aposta, senhor. Aposta mínima $}
{322}{}{Faça sua aposta, senhora. Aposta mínima $}
{323}{}{Façam suas apostas, aposta mínima $}
{324}{}{Eu meior que oce}
{325}{}{Eu jogo minha calça}
{326}{}{O que é esse jogo? Posso apostar pele de gecko? Eu tenho geck... ooooh... lindas luzes! [Afasta-se.]}
{327}{}{[Você tem $}
{328}{}{Aposta $}
{329}{}{Whoa, muita coisa para o meu gosto.}
{330}{}{Sem apostas hoje, obrigado.}
{331}{}{Uhhh, desculpe, eu não sei como jogar esses jogos malucos.}
{340}{}{Hum… Ouvi dizer que estão dando cérebros lá atrás. Talvez você devesse dar uma olhada.}
{341}{}{Muito bem, senhor. Volte logo.}
{342}{}{Muito bem, senhora. Volte logo.}
{343}{}{Tchaaaaau}
{344}{}{Diaaaaa. }
{345}{}{Uh… cérebro… o quê?! Eu vou ver!}
{350}{}{Muito bem, senhor. Volte logo.}
{351}{}{Muito bem, senhora. Volte logo.}
{352}{}{[A croupier levanta uma sobrancelha.] $}
{354}{}{Eu vou, obrigado.}
{355}{}{Talvez sim.}
{400}{}{Desculpe, mais sorte da próxima vez.}
{401}{}{Desculpe, senhor. Mais sorte da próxima vez.}
{402}{}{Desculpe, senhora. Mais sorte da próxima vez.}
{410}{}{Empate.}
{411}{}{Empate. Gostaria de tentar novamente, senhor?}
{412}{}{Empate. Gostaria de tentar novamente, senhora?}
{420}{}{Vencedor! Você dobrou seu dinheiro!}
{421}{}{Vencedor! Você dobrou seu dinheiro! Muito bem, senhor!}
{422}{}{Vencedora! Você dobrou seu dinheiro! Muito bem, senhora!}
{430}{}{Vencedor! Você triplicou seu dinheiro!}
{431}{}{Vencedor! Você triplicou seu dinheiro! A sorte está na casa esta noite! Muito bem, senhor!}
{432}{}{Vencedor! Você triplicou seu dinheiro! A sorte está em casa esta noite! Muito bem, senhora!}
{440}{}{Liga-o por um dia.}
{441}{}{Isso que é noite.}
{450}{}{Desculpe, esta mesa foi fechada. Alguém tem manipulado os dados.}
{451}{}{Desculpe, senhor, esta mesa foi fechada. Alguém tem manipulado os dados.}
{452}{}{Desculpe, senhora, esta mesa foi fechada. Alguém tem manipulado os dados.}
{453}{}{Uhhh, OK.}
{454}{}{Lamento ouvir isso. Obrigado.}
{2203}{}{! Bem-vindo ao cassino, herói!}
{2215}{}{. Posso te ajudar com *alguma coisa?*}
{2219}{}{.}
{2255}{}{. Procurando onde gastar algumas tampas?}
{2258}{}{, ganhe algumas tampas.}
{2260}{}{.}
{2261}{}{. Me diga se eu posso te ajudar com alguma coisa.}
{2262}{}{?}
{2263}{}{.}
{2321}{}{. faça suas apostas...}
{2327}{}{.] }
{2328}{}{.}
{2344}{}{ sempre pode usar novo item de inventário [Sair.]}
{2352}{}{? 'Muita coisa para o seu gosto?' [Zomba.] Amigo, você está na cidade errada.}
{2353}{}{? 'Muita coisa para o seu gosto?' [Zomba.] Meu bem, você está na cidade errada.}
