#############################################################
#  Message File: AIVase.msg                                 #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the dialog for a     #
#           new character from which is used by the         #
#           design tool. It will be updated using the       #
#           the tool. This is just a tool file, and not     #
#           meant to be used in the game.                   #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: December 04, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the item when     #
#  glanced and and examined.                                #
#############################################################

###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите простую вазу.}
{101}{}{Вы видите маленький сундук.}
{102}{}{Вы видите обожженную на солнце глиняную вазу.}
{103}{}{Вы видите сундук с травами шамана.}
{104}{}{Вы ловко крадете вещи шамана.}
###.Magnat.###...Added by Killap. Translated by Aliet (LevCorp-like). Done...########################
{105}{}{Вы умело заперли ящик.}
{106}{}{Вы умело открыли замок на ящике.}

