#############################################################
#  Message File: ZClDthCl.msg                               #
#                                                           #
#       Body Type:  Lesser Death Claw                       #
#       Combat AI: Death Claw AI                            #
#       Weapons:                                            #
#       HP: ?                                               #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: December 01, 1997                               #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
###.Magnat.###...Original 1C translation. Need no correction...########################
{100}{}{Вы видите Когтя Смерти.}
