{0}{}{SAUVEGARDER}
{1}{}{CHARGER JEU}
{2}{}{PREFERENCES}
{3}{}{QUITTER JEU}
{4}{}{TERMINER}
{100}{}{PREFERENCES DE JEU}
{101}{}{DIFFICULTE DU JEU}
{102}{}{DIFFICULTE COMBAT}
{103}{}{VIOLENCE}
{104}{}{MARQUAGE CIBLES}
{105}{}{EXAMEN EN COMBAT}
{106}{}{TEXTE DU COMBAT}
{107}{}{INJURES AU COMBAT}
{108}{}{FILTRE LANGAGE}
{109}{}{COURSE}
{110}{}{SOUS-TITRES}
{111}{}{MARQUAGE OBJETS}
{112}{}{VITESSE DU COMBAT}
{113}{}{AFFICHAGE DU TEXTE}
{114}{}{VOLUME AUDIO MASTER}
{115}{}{VOLUME MUSIQUE/VIDEO}
{116}{}{VOLUME EFFETS SONORES}
{117}{}{VOLUME VOIX}
{118}{}{LUMINOSITE}
{119}{}{SENSIBILITE DE LA SOURIS}
{120}{}{DEFAUT}
{121}{}{ANNULER}
{122}{}{Modifie la vitesse du joueur}
{123}{}{Pip-Boy speech}
{201}{}{Oui}
{202}{}{Non}
{203}{}{Facile}
{204}{}{Normal}
{205}{}{Difficile}
{206}{}{Facile}
{207}{}{Normal}
{208}{}{Dur}
{209}{}{Normal}
{210}{}{Rapide}
{211}{}{Prolixe}
{212}{}{Bref}
{213}{}{Cibles uniquement}
{214}{}{Aucune préférence.}
{215}{}{Minimum}
{216}{}{Maximum}
{217}{}{Lent}
{218}{}{Rapide}
{219}{}{Rapide}
{220}{}{Beaucoup}
{221}{}{Minimum}
{222}{}{Maximum}
{223}{}{Plus lumineux}
{224}{}{Maximum}
{300}{}{TERMINER}
{301}{}{PAUSE}
{1000}{}{Le menu des préférences n'est malheureusement }
{1001}{}{pas disponible dans la version de démo.}
