{100}{}{Métabofast}
{101}{}{La Châtaigne}
{102}{}{Gringalet}
{103}{}{Main-d'Or}
{104}{}{Finesse}
{105}{}{Kamikaze}
{106}{}{Main-Lourde}
{107}{}{Sang-Chaud}
{108}{}{Brute}
{109}{}{La-Poisse}
{110}{}{Bon Vivant}
{111}{}{Drug Reliant}
{112}{}{Drug Resistant}
{113}{}{Sex Appeal}
{114}{}{Compétence}
{115}{}{Talent}
{200}{}{Ton métabolisme est deux fois plus rapide que la normale. Cela se traduit par un affaiblissement de ta résistance aux radiations et au poison mais tu guéris plus rapidement.}
{201}{}{Un peu de lenteur mais une carrure imposante. Tu ne frappes pas si souvent mais à chaque fois, on le sent passer ! Le total de tes points d'action s'en trouve diminué mais ton niveau de force est accru.}
{202}{}{D'une taille certes plus modeste que les autres villageois, rien ne peut pourtant te freiner. Bien sûr, impossible de supporter de lourdes charges mais question d'agilité, tu n'as pas ton pareil.}
{203}{}{On ne peut pas dire que tu sois ambidextre. Les armes maniées d'une seule main, c'est ton rayon. Pour les autres, tu as un léger problème !}
{204}{}{Tes attaques sont portées avec finesse. Tu ne causes pas de gros dégâts mais les coups que tu portes sont souvent critiques.}
{205}{}{En ne prêtant pas attention aux menaces, tu peux agir beaucoup plus rapidement en combat. Cela réduit ta Classe d'armure à ce que tu portes, mais ton tour arrive plus rapidement en combat.}
{206}{}{Tu cognes plus fort, pas forcément mieux. Tes attaques sont brutales mais manquent de finesse. En Rixe, les coups que tu portes sont moins souvent critiques, mais tu infliges plus de dégâts.}
{207}{}{Tu n'as pas le temps de viser pour une attaque ciblée parce que tu attaques plus vite que les gens normaux. Cela te coûte un point d'action de moins pour utiliser les armes à feu et les armes de jet.}
{208}{}{Etrangement, les gens autour de toi meurent de façons très violentes. Tu vois toujours les gens mourir de la pire des façons possible.}
{209}{}{La bonne nouvelle, c'est que tes adversaires ont peu de chance de s'en sortir vivants. La mauvaise, c'est que c'est le même tarif pour toi ! Chaque échec au combat a une chance importante d'être "amélioré" en échec "Critique".}
{210}{}{Plus jeune, tu as beaucoup étudié. Pas forcément les techniques de combat. Tu débutes donc avec une capacité à combattre plus faible mais tes compétences Secourisme, Médecin, Discours et Troc sont renforcées.}
{211}{}{You are more easily influenced by drugs.  Your chance to be reliant by drug use is twice normal, but you recover faster from their ill effects.}
{212}{}{Drugs only affect you half as long as normal, but your chance to be reliant is also only 50% of normal.}
{213}{}{Tu as tout pour séduire. Les membres du sexe opposé te trouvent irrésistible. Attention toutefois à la jalousie de tes pairs...}
{214}{}{Grâce au temps que tu as passé à affiner tes compétences, tu gagnes 5 points de compétence en plus par niveau. Mais tu t'améliores moins vite. Tu gagneras une nouvelle aptitude tous les 4 niveaux au lieu de 3.}
{215}{}{Chez toi, tout est inné. Pas besoin d'affiner tes compétences. Tes statistiques de base sont toutes augmentées d'un point mais tu perds 10% sur tes compétences de départ et tu reçois 5 points de moins par niveau.}
