{100}{}{You see a computer monk.}
{101}{}{You see Brother Paul.}
{102}{}{This monk looks like a computer geek.}
{200}{}{Hi!}
{201}{}{Hello.}
{202}{}{Now, did I backup those computer files today...}
{203}{}{I'm sorry, but I don't have time for someone of your intelligence.}
{300}{}{Yes?}
{301}{}{You guys sure have a lot of computers here.}
{302}{}{What can you tell me about the Abbey?}
{303}{}{Tell me about your leader.}
{304}{}{Do you have any info about a GECK?}
{305}{}{Do you know where I could find Vault 13?}
{306}{}{Bye.}
{307}{}{I am in need of some specific information.}
{308}{}{Such as?}
{400}{}{Yes, we have. Too many, in my opinion. I can't express to you the tedium of having to back up all these files
 each and every day. There's just so much information to preserve, but, of course, it must be done.}
{401}{}{Of course. Anyway, I have some other questions.}
{402}{}{We are an independent community. Anyone is welcome as long as they behave themselves.}
{403}{}{Ok.}
{404}{}{The Abbot is a good spiritual leader, but he's been a little cranky since we lost Brother Thomas to the beast.}
{405}{}{What kind of beast?}
{406}{}{I haven't seen it, personally--there's nothing in the world that could get me to go down there and explore those
 caverns--but if I had to guess, I'd say it's probably just some overgrown radscorpion.}
{407}{}{If you haven't seen it, then what makes you think it's a radscorpion?}
{408}{}{Because I've heard sounds echoing up from the caves--the sounds of snapping claws and skittering legs.}
{409}{}{Right.}
{410}{}{In fact, we do. Take a look on that computer over there. Here, you can use this card to access our encrypted files. [He hands you an access card.]}
{411}{}{Wow, thanks a lot!}
{412}{}{I don't know anything about Vault 13, but there is Vault City down south. Maybe they have the info you need.}
{413}{}{Thanks.}
{414}{}{That computer near me should have the information you seek, but you'd need an access card to use it.
 We're very selective with who we give access to, but if you speak to the Abbot, perhaps he'll grant you permission.}
{415}{}{Ok, thanks.}
{420}{}{I'm guessing you've read a lot of books in your time. So I'm curious, what's the most fascinating thing you could tell me?}
{421}{}{Hmm, let's see. Did you know a notch in a tree will remain the same distance from the ground as the tree grows?}
{422}{}{Sure. If I come across anything like that, I'll be sure to let you know.}
{423}{}{Right... Well, I have some other questions.}
{424}{}{Would you? I'd appreciate that.}
{425}{}{No problem. I have some other questions.}
{426}{}{Any time. Well, see you around.}
{430}{}{I found some information about Botany that might interest you.}
{431}{}{Really?! That's great. Please, do tell immediately.}
{432}{}{Fascinating! I shall take this holodisk and add it to the computer database immediately. I appreciate you
 taking the time to find this for me. Thank you for collecting this for me.}
{433}{}{Well you see... Understanding habitat destruction and species extinction is dependent on an accurate and complete catalog of plant systematics and taxonomy. And then this means that...}
{434}{}{Any time. I have some other questions though.}
{435}{}{No problem. See you around.}
{436}{}{Fascinating! I appreciate you taking the time to find this for me. Please go and upload this information to our computers.}
{437}{}{No problem, I'll do that now. See you around.}
{500}{}{Stop that, moron!}
{550}{}{That computer near me should have some information about it. You now have access, so take a look for yourself.}
{600}{}{The Abbot gave me permission to access the computers here.}
{601}{}{Ah yes, I heard about what you did. Thanks for taking care of that situation. Here is the access key. (He hands you the key.) Enjoy!}
{602}{}{Thanks. See you around.}
{650}{}{Greetings traveler! I am Brother Paul and I am in charge of the collection of information for the Abbey. What can I do for you?}
{651}{}{Nice to meet you, Paul. I have some questions.}
{652}{}{Nothing. See you around.}
{4210}{}{Uh, no, I can't say I knew that. That's... interesting.}
{4211}{}{And did you know a cucumber is 96% water?}
{4212}{}{Wow, 96%, huh? Fascinating. But, um, what's a cucumber?}
{4213}{}{I've never seen one, but I've read about them. [He looks around nervously and lowers his voice.] I know we're
 not supposed to actually study these books, but when I was transcribing a book on botany, I just couldn't help but get
 sucked into it. The world of plants is simply captivating. Perhaps, if, during your travels, you happen upon some botany
 information, you could bring it to me? I'd be most grateful. Of course, it'd have to be our secret.}
{4220}{}{I don't think I want to contribute to your plant obsession. Sorry.}
{4221}{}{Oh, well then. Fine, forget I asked.}
{4222}{}{Let me ask you something else.}
