{100}{}{Você vê um velho curvado.}
{101}{}{O homem decrépito cheira a suor e possivelmente urina. Ele está vestido com trapos esfarrapados e enlameados e está carregando uma pá.}
{102}{}{Você vê Tom.}
{200}{}{[O velho sacode de surpresa quando ele vê que você se aproxima.] Uh, olha, eu realmente devo ir ...}
{201}{}{Agora você aguenta um minuto. [Você pega o homem pelo braço quando ele começa a se afastar.] Quem é você e o que você é?
  o que faz aqui a esta hora?}
{202}{}{O que? Por que, uh ... o nome é Tom e não pode um ancião desfrutar mais um passeio noturno sem responder um monte de
  questões?}
{203}{}{Não quando ele está passando como um ladrão e carregando uma pá.}
{204}{}{Tudo bem, mas por que você está carregando uma pá?}
{205}{}{Seja como for, estou saindo daqui.}
{206}{}{Deixa pra lá. Desculpe incomodá-lo.
}
{207}{}{Você quer dizer esta coisa? [Ele olha para a pá enferrujada em suas mãos.] Bem, uh, você nunca sabe quando você
  pode encontrar algo que precisa desenterrar. Sempre esteja preparado, eu digo.}
{208}{}{Encontrar alguma coisa, hein? Você quer dizer como algo em uma sepultura?}
{209}{}{Isso é um bom lema de fato. Bem, tome cuidado.}
{210}{}{(Os olhos de Tom se ampliam) Não tenho certeza do que você, uh, quer dizer.}
{211}{}{Tom, você está em um cemitério, você tem lama em cima de você, e já passa da meia-noite. Por que, mesmo Torr poderia desenhar uma conclusão a partir disso. É hora de começar a dar-me algumas respostas, Tom. Por que você iria desenterrar esses túmulos?}
{212}{}{[Ele coloca a pá e suspira.] Tudo bem, eu vou te contar. Meu corpo não é o que costumava ser. Não tenho trabalho,
  e nenhum meio real para obter comida. Eu sei que um ladrão de tumba não é algo que as pessoas admirem, mas tem sido uma maneira para mim
  conseguir algum dinheiro. Estou apenas tentando sobreviver ... Não quero fazer nenhum mal.}
{213}{}{Eu não acho que cavar túmulos é bom para um homem em sua condição. Dizer-te o que. Você estária morto
  fora daqui e vamos esquecer que essa conversa já aconteceu. Eu nunca mais quero ver o seu rosto, ok?}
{214}{}{[O velho parece que ele está prestes a protestar, então pára.] Tudo bem, você ganhou. Você viu a última do velho e pobre Tom.
  [Ele pega sua pá e alegra-se.]}
{215}{}{Pensando bem, talvez seja melhor para o mundo se eu te matar.}
{216}{}{Adeus Tom.}
{217}{}{Eu ouvi dizer que você também já foi roubar culturas do agricultor aqui.}
{218}{}{[O velho se agacha inconformadamente.] Eu não pude evitar! Eu estava com tanta fome e a comida parecia tão boa. Por favor,
  Não quero criar nenhum problema. Olha, vou embora e você não vai me ver aqui novamente. Eu prometo!}
{219}{}{Tudo bem, continue. Antes de mudar de ideia.}
{220}{}{Aguarde, não precisa de nada disso. Os Peterson são proprietários da fazenda aqui e são pessoas extremamente agradáveis. Sr. Peterson
  até se ofereceu para conversar com quem estava tomando suas colheitas e chegar a um acordo razoável. Vá falar com ele.
  Tenho certeza de que ele pode ajudá-lo de alguma forma.}
{221}{}{(Os olhos do homem velho se acendem.) Isso não soa como uma má idéia. Ei, obrigado. Talvez este mundo não seja tão
  cruel como pensei que fosse.}
{222}{}{Você tome cuidado em seguida, Tom. Vou verificar com você mais tarde e ver como as coisas estão indo.}
{223}{}{Espero que Peterson seja tão amigável como você diz que ele é.}
{300}{}{Você vê Tom. Ele está usando roupa de novo trabalhador e assobiando alegremente.}
{301}{}{Olá! Uau, você estava certo. O Sr. Peterson é um amigo gentil. Ele me perdoou pelo que fiz e até mesmo
  me ofereceu um trabalho ajudando no campo. Ele diz que depois de pagar as refeições que tomei, então vou começar a ganhar um
  salário semanal. Obrigado novamente por sua ajuda.}
{302}{}{De nada, Tom. Você cuida de si mesmo agora.}
{303}{}{Tudo bem, eu sei, espere um segundo. Quero lhe dar algo por ajudar um velho amigo como eu. Eu achei isto
  De um tumulo que eu tirei algumas semanas atrás. Eu não uso nada e espero que você possa.}
{304}{}{Obrigado, Tom. Eu tenho certeza que isso vai vir a calhar. Vejo você por ai.}
{305}{}{(O velho homem acena com a cabeça e volta para o que estava fazendo.)}
{306}{}{[FIM]}
{307}{}{Olá novamente. Obrigado por tudo!}
{308}{}{*Assobio*}
{400}{}{Vocês jovens nunca aprendem. Você não é meu chefe. Acho que vou acabar com você.}
{450}{}{Escute, eu escavei a minha quota de sepulturas. Eu sou um pouco de um cleptomaníaco. Qual é o seu motivo?}
{451}{}{Não estou familiarizado com a escavação de túmulos, Tom. Todo homem tem sua própria diversão. Agora você está no seu caminho.}
{1000}{}{Você descobre quem está cavando os túmulos e preparou Tom para uma nova vida.}
{1001}{}{Você descobre quem está cavando os túmulos.}
{1002}{}{Estou indo. Não há necessidade de apressar um homem velho.}
{1003}{}{Você vê Tom. Ele tem um sorriso no rosto e ele está vestindo roupas de novo trabalhador.}
{1004}{}{Ele parece estar em muito melhor condição e sorri quando você se aproxima.}
