{100}{}{Você vê uma mulher jovem.}
{101}{}{Você vê Chrissy, a filha de Rebecca.}
{102}{}{Você vê uma mulher muito jovem. Ela parece confiante e capaz de lidar com ela mesma em uma briga.}
{103}{}{Se você está aqui para tentar me violar, você estará vestindo suas bolas como uma gravata. Sacou?}
{104}{}{Deixe-me adivinhar. Os caras estão cansados de eu chutá-los onde dói, então eles o enviaram aqui para
  fazer algo obsceno. Bem, eu posso te machucar muito; Eu só preciso chutar mais alto. Sacou?}
{105}{}{Gravata?}
{106}{}{}
{107}{}{O que aconteceu aqui? Quem é você?}
{108}{}{}
{109}{}{Gostaria de saber quem você é e o que está acontecendo aqui.}
{110}{}{Sim. Um pano extravagante usado em volta do pescoço para decoração. É como um cachecol, mas para
homens. Agora, imagine-me chutando-te com tanta vontade que acabas vestindo o seu saco sobre o pescoço. Pegou
isso?}
{111}{}{Eu compreendo. Você não me machucou.}
{112}{}{Eu tenho a imagem; por favor, não me machucar.}
{113}{}{Ok, então por que você está aqui?}
{114}{}{}
{115}{}{Eu quero saber o que acontece aqui? Quem é você?}
{116}{}{}
{117}{}{Gostaria de saber quem você é e o que está acontecendo aqui.}
{118}{}{Realmente? Impressionante! Vamos lá.}
{119}{}{Tudo bem.}
{120}{}{Em poucas palavras, meu nome é Chrissy e eu sou do Squat. Eu estava explorando a semana passada quando eu
  descobri essa entrada lá fora. Eu pensei que poderia ser uma mina abandonada ou algo assim, então eu decidi
  Conferir. Bem, não é uma mina; É uma entrada secreta no Vault 15. O cofre está sendo
  usado como base para uma banda de invasores chamado Khans. Eles me pegaram passeando e seu líder, Darion, me trancou aqui.}
{121}{}{OK. Eu a levarei para casa.}
{122}{}{Tudo bem, eu vou levar você para casa.}
{123}{}{Bem, eu vou ser condenado. Hoje deve ser o meu dia de sorte. A que devo o prazer de te ver
  novamente?}
{124}{}{}
{125}{}{O que aconteceu aqui? Quem é você?}
{126}{}{}
{127}{}{Gostaria de saber quem você é e o que está acontecendo aqui.}
{128}{}{Por favor, leve-me para a minha mãe, Rebeca.}
{129}{}{Meu cavaleiro em armadura brilhante retorna. Bem, isso brilharia se você limpasse tudo de vez em
  enquando. Ah, e você pode querer considerar se banhar também. Então o que posso fazer por você?}
{130}{}{Eu apenas disse oi. Eu vou agora.}
{131}{}{Apenas pensei em dizer olá. Eu vou estar indo agora.}
{132}{}{Ei, eu sei que tenho uma boca grande, mas quero que saiba que estou muito grata por você salvar
  meu traseiro. Muito obrigado!}
{133}{}{Você é bem-vindo.}
{134}{}{Você é bem-vindo.}
{135}{}{As pessoas do Squat estão protegendo esses caras, ajudando-os a manter o cofre em segredo, mas eles
  não sabem o que realmente está acontecendo aqui. Darion nos disse que o cofre estava sendo reparado para que pudéssemos ter
  um lugar seguro para viver com muita comida e água, mas tudo é uma mentira. Eu estive lá e olhei
  por aí. O cofre está morto, e as máquinas de alimentos e água não funcionam. Nossa comida e água estão chegando
  dos despojos
  de ataques contra caravanas.}
{136}{}{Olha, eu tenho que ir para casa e avisar a todos sobre o que realmente está acontecendo aqui. Não podemos ajudar esses monstros. Você vai me levar para casa?}
