{100}{}{Você vê um terminal de computador.}
{101}{}{Você vê o terminal do computador do centro de controle.}
{102}{}{Você vê um terminal de computador padrão. Parece estar funcional e pronto para entrada.}
{103}{}{O terminal indica que o campo de força de segurança na entrada do cofre foi ativado
  agora que o poder foi restaurado.}
{104}{}{O terminal indica que todos os sistemas de segurança no cofre estão fora de linha devido ao poder
  falha.}
{105}{}{Desligue o campo de força.}
{106}{}{Ligue o campo de força.}
{107}{}{Feito.}
{108}{}{Você dá o comando para desativar o campo de força.}
{109}{}{Feito.}
{110}{}{Você dá o comando para ativar o campo de força.}
{111}{}{Feito.}
{112}{}{O terminal indica que o campo é desativado por acionamento manual.}
{113}{}{O terminal indica que o sistema de campo foi comprometido.}
{114}{}{O terminal indica que o sistema de campo está desligado.}
