{170}{}{You deftly pick the lock on the locker.}
{171}{}{Your lack of skill has jammed the lock on this locker.}
{172}{}{You fail to pick the lock on this locker.}
{173}{}{ deftly picks the lock on the locker.}
{174}{}{'s lack of skill has jammed the lock on this locker.}
{175}{}{ failed to pick the lock on this locker.}
{176}{}{Você arrombou a fechadura da porta.}
{177}{}{Você pressiona suas costas enquanto tenta abrir o bloqueio e
  toma um ponto de dano.}
{178}{}{Você pressiona suas costas enquanto tenta abrir o bloqueio e toma }
{179}{}{pontos de dano.}
{180}{}{Você é muito fraco para ultrapassar o bloqueio.}
{181}{}{arrombou a fechadura da porta.}
{182}{}{estica as costas enquanto tenta abater a fechadura e leva
  pontos de dano.}
{183}{}{pressiona suas costas enquanto tenta abrir o bloqueio e toma}
{184}{}{pontos de dano.}
{185}{}{ é muito fraco para ultrapassar o bloqueio.}
{186}{}{estica as costas enquanto tenta abater a fechadura e leva
  pontos de dano.}
{187}{}{pressiona suas costas enquanto tenta abrir o bloqueio e toma }
{188}{}{pontos de dano.}
{189}{}{You deftly lock the locker.}
{190}{}{You fail to lock the locker.}
{191}{}{ deftly locks the locker.}
{192}{}{ failed to lock the locker.}
{203}{}{The locker appears to be locked.}
{800}{}{You retrieved the fob.}
{810}{}{You retrieved the plans.}
{820}{}{You retrieved the K-9 motivator.}
