{100}{}{Você vê um homem baixo, com um espesso bigode.}
{101}{}{Você vê o Grande Ananias.}
{102}{}{Você vê um homem curto, de bigode, com um olhar um pouco furtivo para ele.}
{103}{}{Você! O que você quer fazer para o, anteriormente, Grande Ananias agora?}
{104}{}{Fique longe de mim!}
{105}{}{Vai arruinar o negócio de outra pessoa.}
{106}{}{Retire-o de outra pessoa.}
{107}{}{Você já fez o seu pior para mim.}
{108}{}{Apenas vá embora, você me causou bastante mal.}
{109}{}{Eu estou com tanta fome.}
{110}{}{Como vou alimentar a minha família agora?}
{111}{}{Você nasceu com um coração 12 de tamanhos muito pequenos.}
{112}{}{Não, meu amigo, uma MÚMIA! Direto das areias do Egito antigo para as areias dos Resíduos! Exclusivamente para você ver!}
{113}{}{OK, eu vou morder. Quanto ver o cadáver marcado?}
{114}{}{(para você mesmo) Hmm, uma múmia descreveria a maneira como um ghoul parece. Ok, eu gostaria de dar uma olhada - quanto?}
{115}{}{Já vi cadáveres suficientes. Adeus.}
{116}{}{Olá, bem-vindo, saudações! Eu sou o Grande Ananias (ele oferece um leve arco, com um floreio). Eu trago mistérios de amigos próximos e distantes. Mistérios de um mundo além do nosso ... do Submundo.}
{117}{}{Voltou para aprender sobre os mistérios do Grande Ananias do Submundo que você tem?}
{118}{}{Que tipo de mistérios?}
{119}{}{Uh, prazer em conhecê-lo, Mr. Grande Ânus...algo.}
{120}{}{Hmm, mistérios me fazer dormir desconfortavelmente, é melhor eu ir. Adeus.}
{121}{}{Passo até!}
{127}{}{Hoje, na sala de dentro, eu tenho, para os seus olhos exclusivamente...Jan-u-vinho Múmia Egípcia!}
{128}{}{Uma múmia?}
{129}{}{Uma múmia? Hmm, eu me pergunto se poderia ser.... Não, ninguém poderia ser tão estúpido.}
{130}{}{Não tenho interesse nesse tipo de coisa. Os cadáveres me assustam.}
{131}{}{Fora do caminho, você está bloqueando os clientes pagantes.}
{132}{}{Eu acho que isto não é para você.}
{133}{}{Por que você não leva seu pequeno ser tribal em outro lugar.}
{134}{}{Isto não é realmente para você.}
{135}{}{Eu vejo, hmmm, que tal IR (ele aponta) de DISTÂNCIA!}
{136}{}{Para uma pessoa da sua óbvia classe, ficaria feliz em mostrar este exemplar único e histórico para você por apenas US $ 25.}
{137}{}{OK, eu vou tossir a massa. Agora...Me Mostrar A Múmia!}
{138}{}{Eu não quero gastar muito. Eu acho que eu vou sobreviver sem ver a coisa. Adeus.}
{139}{}{Basta abrir a tampa do sarcófago e a maravilhosa Múmia será revelada, em toda a sua antiga glória, para você. Mas por favor, sem tocar, e, uh, sem fotografia instantânea.}
{140}{}{Grande.}
{141}{}{Ai está! A MÚMIA! (A porta do sarcófago se abre para revelar um cadáver dessecado, que se parece muito com um ghoul comum, parado em um sarcófago de papel mal pintado, estilhaçado e quebrado).}
{142}{}{Ai está! Apresentando, a MÚMIA! (uma porta de cripta se abre para revelar uma múmia egípcia de jan-u-wine em um sarcófago aberto que parece ter sido feita de ouro puro!)}
{143}{}{Ei, espere um minuto. Isso não é uma Múmia. Isso é um ghoul. WOODY! Ei WOODY! Isso é você?}
{144}{}{That sure looks like a ghoul to me.}
{145}{}{That's a mummy? I can't believe I just paid $25 to see a six-foot hunk of jerky. Goodbye.}
{146}{}{Wow, that's fantastic...I guess. (you look at the Mummy very intently for a while). Uh, thanks, Goodbye.}
{147}{}{(the Mummy, snorts, stretches languidly, and then looks at you with a sleepy blink to its eyes) Hello. (he says, sleepily)}
{148}{}{Holy shit! That *is* Woody! Run Woody, run for it! Well, uh, gimp for it then! Go Woody go!}
{149}{}{I assure you that the Mummy is, in fact, quite jan-u-wine.}
{150}{}{I don't think I believe you. Let me try something. WOODY! Hey WOODY! Is that you?}
{151}{}{Well, if you say so. But I sure think it looks like an ordinary ghoul. Goodbye.}
{152}{}{(Woody--for it is in fact Woody, not a Mummy, that stands somewhat drowsily before you--grabs the sides of the
 paper-
mache sarcophagus, lets out a shriek and runs for the door, leaving a trail of toilet-paper 'mummy-wrappings'
 and a hasty "Thankee kindly, Stranger!" behind him.)}
{153}{}{Hah! I knew it! You're finished in this town. You're not the Great Ananias anymore, you're just another ass.}
{154}{}{Go Woody go! Ahah! I knew it!}
{155}{}{(The Great Ananias shrugs) I knew I should have picked up that mono-headed Brahmin instead. Oh well, back to the drawing board.}
{156}{}{Mono-headed brahmin? Sure, who would ever believe that! Goodbye, you Charlatan.}
{157}{}{You woke up Woody the ghoul and freed him from indentured mummy-tude.}
{158}{}{I think I'd rather hear the ghost story.}
{200}{}{I know things that mere mortal man is not meant to know. Aiiieeee! Nyarloth...Oh, sorry (heh, heh). Got a little carried away
 there for a moment. I have tales of a Ghost that haunts these very grounds, as well as a Jan-u-wine Egypt-ee-an Mummy that you
 can see, right here in this marvelous sarcophagus.}
{201}{}{Tell me about the mummy. I'm just dying to hear more about that.}
{202}{}{I've just got to hear that ghost story. Uh, do I get a nice hot cup of cocoa to go with it?}
{203}{}{I don't think I have any more time to waste on whatever it is that you're hawking.}
{300}{}{Well, you see, (he motions you closer) there was once a great queen that ruled all of the surrounding town. She kept her
 throne by virtue of a special amulet that she kept around her neck at all times. Great stuff, huh?}
{301}{}{Uh, yeah. You bet. So this princess had a *magic* amulet. Oh, do go on. I just can't stand this level of suspense
 much longer (yawn).}
{302}{}{OK. I think I've heard just about enough. Goodbye.}
{400}{}{Well, I'll cut to the chase then. So, the evil wizard poisoned the young princess and took her amulet. She's been wandering
 around the room next door ever since. Well, uh, that is, just at the witching hour, anyway. That's why I keep the door locked.
 Pretty darn scary, huh?}
{401}{}{The ghost of an amuletless princess in the trashed room next door? That's it? I can't believe you're peddling *that* as a story.
 I'd rather hear about this stupid Mummy you're supposed to have here.}
{402}{}{OK. I think I've heard just about enough. Goodbye.}
