{100}{}{Você vê um homem magro, gorduroso.}
{150}{}{Você vê Flick, dando a sua virilha um raspador minucioso.}
{151}{}{Você vê um sujeito impuro com uma contração facial desagradável.}
{200}{}{Saia do heeya, você burro.}
{201}{}{Ei almôndega! Sim, você. Fuja heeya.}
{202}{}{Você é idiota ou estupido? }
{203}{}{Whatchur problema, hein?}
{204}{}{Ao inferno fora de heeya.}
{220}{}{Hey der, eu sou o Flick. Que merda você quer, hein?}
{221}{}{O que agora? Você ficou no meu tempo, heeya.}
{222}{}{Qual é a desse maluco, Flick?}
{223}{}{O que diabos você faz aqui?}
{224}{}{Estou à procura de um Vault - oh, sim, e um comerciante chamado Vic também. Sabe onde eles podem estar?}
{225}{}{Gostaria de trocar com você.}
{240}{}{Que tal fazê-lo para você, amigo?}
{241}{}{Na verdade, gostaria de dar uma olhada em seus produtos se puder.}
{242}{}{Na verdade, eu gostaria de lhe fazer uma pergunta.}
{243}{}{Que fez isso. Vejo você por aí Flick.}
{260}{}{Eu sou um fodido provedor, pensou Whaddya? Eu sou como um bom homem samurai-irã.}
{261}{}{Dizer o que?}
{262}{}{Yeah, uh, bem...deixe-me perguntar-lhe algo mais.}
{263}{}{Uh, oh. ESTÁ BEM. Adeus, Flick.}
{280}{}{Fornecendo-lhes pequenos paisanos.}
{281}{}{Vocês fornecem pequenos pianos?}
{290}{}{Pai-san-o, você sabe, as crianças. Meus filhos.}
{291}{}{Seus filhos?}
{292}{}{Bem, eu não estou realmente interessado em aulas de música para crianças. Deixe-me perguntar-lhe sobre outra coisa.}
{300}{}{Sim, bem, eles trabalham para mim. Eles me trazem coisas. Pequenas coisas. Você sabe.}
{301}{}{Uh, não.}
{302}{}{Ah, OK. Deixe-me perguntar-lhe algo mais.}
{303}{}{Ah, eu vejo. Bem, eu não quero atrapalhar seu estilo. Adeus.}
{315}{}{Eles me trazem coisas que eles acham. Pequenas e pequenas coisas. Coisas, ninguém já não usa mais. Em troca, eu cuido deles.}
{316}{}{Soa como um bom arranjo.}
{325}{}{(Flick dá de ombros) eu consigo OK.}
{326}{}{Deixe-me perguntar sobre outra coisa, então.}
{327}{}{Eles devem ter trazido a você algumas verdadeiras pechinchas. Vamos ver o que você tem.}
{328}{}{Apenas checando. Bem, adeus Flick.}
{340}{}{Do que você está falando? Você acha que eu sou uma maldito pirata estúpido? Algum estranho filio di puttana? Você acha que eu sou um palhaço? Estou aqui para divertir você, é isso?}
{341}{}{Uh, não. Desculpe, eu estava apenas curioso. Deixe-me perguntar-lhe sobre outra coisa.}
{342}{}{Sim, é verdade, merda. E nada vai me divertir mais do que a sua morte.}
{343}{}{Bem, se você vai ficar irritado com isso, eu vou embora.}
{360}{}{Vault, hein? Talvez mamãe saiba sobre isso, porque eu não. Mas aquele cara o Vic - ele eu sei. Metzger tem aquela porca pistola.}
{361}{}{Vic? Não é ele com você? Você é uma biota. Mas mamãe, ela eu sei.}
{362}{}{Quem é o Metzger?}
{363}{}{Quem é a mãe?}
{364}{}{Obrigado. Deixe-me perguntar-lhe algo mais.}
{365}{}{Obrigado, isso é tudo que eu preciso saber. Adeus.}
{380}{}{Mamãe dirige um lugar de comida no lado leste da cidade. Justo após o cemitério. Bom lugar, ela faz um bom macarrão, Mama Mia.}
{381}{}{Obrigado, e o Metzger que tem Vic?}
{382}{}{Obrigado. Deixe-me perguntar-lhe algo mais.}
{383}{}{Obrigado, isso é tudo que eu preciso saber. Adeus.}
{400}{}{Está certo. Metzger, esse estronzo, ele está morto. Não sei o que aconteceu com Vic.}
{401}{}{That Metzger, he's a real rompiballe, that one. Runs the Slaver's Guild. East side of town, just north of Momma's. Anyhow, he got Vic, I know.}
{402}{}{Thanks, now what about Momma?}
{403}{}{Obrigado. Deixe-me perguntar-lhe algo mais.}
{404}{}{Obrigado, isso é tudo que eu preciso saber. Adeus.}
{410}{}{Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with his presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.}
{411}{}{Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with her presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.}
{412}{}{Vocês fornecem pequenos pianos?}
{413}{}{You sound like you don't like the fact that the children are no longer roaming the streets.}
{420}{}{Hey, don't get me wrong. Life on the street is tough fer them kids, but it's the end of our little arrangement that gets me down.}
{421}{}{What arrangement?}
{422}{}{You mean them pickpocketing from people and bringing the items to you to sell.}
{430}{}{Don't you get smart with me asshole. The kids bring me items they *find.* I don't know where they get them and frankly, I don't give a fuck.}
{431}{}{Certo.}
{432}{}{You're full of it. I'm sick of skum like you who use people for their own benefit. Time to die!}
{440}{}{Pai-san-o, você sabe, as crianças. Meus filhos.}
{441}{}{And you have an arrangement with them?}
{450}{}{Eles me trazem coisas que eles acham. Pequenas e pequenas coisas. Coisas, ninguém já não usa mais. Em troca, eu cuido deles.}
{451}{}{Soa como um bom arranjo.}
{460}{}{Yeah...business was good 'til you came along. See, yer little stunt's gonna cost me. My business is gonna suffer thanks to you.
 Because of this, I don't really like you too much. In fact, I fuckin' hate you. But, I'm a business man, so if you need to barter,
 get to it. If not, fuck off.}
{461}{}{Alright, let's see what you have in stock then.}
{462}{}{I think I have all I need. Goodbye.}
{463}{}{I think I'll stay...and kick your ass.}
{470}{}{You again? You better be here to make some good trades, 'cause I'm getting real fuckin' sick of looking at you.
 In fact, I vomit in my mouth a little every time I see yer face. That's how much you disgust me. And if yer not here to
 trade, then I suggest you turn around and walk the fuck outta here.}
{471}{}{Let's trade.}
{472}{}{Apenas checando. Bem, adeus Flick.}
{480}{}{You done wastin' my time?}
{481}{}{Let me take another look.}
{482}{}{That should do it. Goodbye Flick.}
