{100}{}{You see a man wearing metal armor.}
{101}{}{Você vê Kaga.}
{102}{}{Yep, it's Kaga the not-so-great. He has metal armor and wants to kill you.}
{103}{}{You again!}
{104}{}{I grow tired of our constant meetings.}
{105}{}{Chosen One - hmph!}
{106}{}{Let's end this.}
{107}{}{You will regret you ever heard the name Kaga!}
{108}{}{My skills have increased since we last met.}
{109}{}{This is getting to be a bad habit.}
{110}{}{Kaga needs to train a little more.}
{111}{}{Kaga will return.}
{120}{}{So we meet again, Kaga.}
{150}{}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}
{160}{}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}
{200}{}{Ooglie?}
{201}{}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
