{100}{}{Você vê um homem vestindo o mínimo de roupa.}
{101}{}{Você vê Kaga.}
{103}{}{Ele está vestindo calças e parece que ele veio de uma tribo.}
{104}{}{Eu deveria ter sido o Escolhido!}
{105}{}{Como se atreve, Arroyo me expulsou da tribo.}
{106}{}{Eu terei minha vingança sobre você!}
{107}{}{Kaga vai mandar você para a próxima vida.}
{108}{}{Nós vamos nos encontrar novamente!}
{109}{}{Nunca fui espancado antes!}
{110}{}{Vou me dedicar para a sua destruição.}
{150}{}{[Um guerreiro alto e poderosamente construído está diante de você, seus olhos chamejam de ódio enquanto ele olha para você.] Então, eles expulsaram Kaga, então, consideram você o Escolhido? Ha! Você acha que ser o neto do Morador do Vault faz você especial ?! Você acha que é melhor do que eu, Kaga o Grande ?!}
{151}{}{Bem, eu SOU o Escolhido, não sou?}
{152}{}{Ei agora, segure um segundo. Nunca disse que era melhor do que você.}
{160}{}{Esse título vai significar nada quando Kaga rasga a cabeça dos seus ombros!}
{161}{}{Nenhuma palavra pode salvar sua pele. Com sua morte, a honra de Kaga deve ser restaurada. Kaga vai agora vingar-se!}
{200}{}{Ooglie?}
{201}{}{O que!? Eles escolheram * você * para ser o Escolhido? Oh meu, eles ficaram desesperados.}
{202}{}{Eu não gosto. Você parece mal.}
{203}{}{Kaga nem sequer se incomodará em falar com você ainda mais. Prepare-se para morrer nas mãos de Kaga!}
