{100}{}{Você vê um homem em armadura de metal.}
{101}{}{Você vê Matthew.}
{102}{}{Você vê um homem vestindo uma armadura de metal com uma insígnia de raio.}
{103}{}{Olá,}
{104}{}{. O que eu posso fazer por você?}
{105}{}{Você responder perguntas?}
{106}{}{Nada. Eu voltar mais tarde.}
{107}{}{Você pode começar respondendo algumas perguntas.}
{108}{}{Nada por enquanto. Eu volto mais tarde.}
{109}{}{Eu acho que você merece ter suas perguntas respondidas.}
{110}{}{Com o que posso ajudar?}
{111}{}{Quem é vocês?}
{112}{}{Por que ninguém fala de vocês?}
{113}{}{Por que só uma pessoa aqui?}
{114}{}{Eu vou agora.}
{115}{}{Quem são vocês?}
{116}{}{Por que ninguém por aí menciona vocês?}
{117}{}{Por que vocês só tem uma pessoa aqui?}
{118}{}{Tenho que ir.}
{119}{}{Nós somos uma organização paramilitar conhecida como Irmandade do Aço.}
{120}{}{O que irmandade faz?}
{121}{}{Ok - e o que é que vocês fazem?}
{122}{}{Houve um tempo em que eramos os únicos defensores da tecnologia deixados no planeta. Nós nos estabelecemos como o que poderia ser chamado de "Polícia da Tecnologia". Nós acumulamos o conhecimento antigo e distribuímos apenas em pequenas parcelas. Naturalmente, foi apenas para aqueles que sentimos que mereciam e que possuíam a sabedoria para utilizar tal conhecimento devidamente.}
{123}{}{E agora?}
{124}{}{Você disse 'houve um tempo.' Mas e agora?}
{125}{}{Alguns meses atrás nós nos deparamos com um grupo conhecido como o Enclave. Para nossa surpresa, seu nível de tecnologia superou até o nosso. Achamos isso bastante perturbador e consideramos contatá-los. No entanto, decidimos por um curso de ação mais cauteloso até que pudéssemos determinar exatamente quem era o Enclave, e qual o objetivo oculto de sua organização.}
{126}{}{Para isso, nós reativamos pequenos postos avançados próximos a áreas de atividade do Enclave, dos quais podemos observá-los com segurança. Atualmente, ativamos esses postos avançados no Den, na NCR e aqui em São Francisco.}
{127}{}{O que você aprender?}
{128}{}{Parece interessante. O que vocês descobriram?}
{129}{}{Descobrimos que o Enclave está envolvido fortemente com drogas, armas e escravos. No entanto, essas são apenas atividades insignificantes que fazem parte de algum objetivo maior, o qual nós falhamos em descobrir. Nós continuamos a observá-los.}
{130}{}{Por que você dizer tudo isso agora?}
{131}{}{Antes de prosseguirmos, por que me diz tudo isso agora?}
{132}{}{(suspiro) O Enclave desenvolveu tecnologia vertibird, máquinas voadoras que lhes permitem avançar profundamente em territórios próximos. Sem uma tecnologia similar para combater essa ameaça, a Irmandade seria incapaz de impedir uma invasão iniciada pelo Enclave. Precisamos obter a tecnologia vertibird, ou algo para usarmos contra ela.}
{133}{}{Recentemente, o Enclave estabeleceu uma base ao norte daqui chamada Navarro. Essa base é usada como ponto de parada para a manutenção e reabastecimento dos vertibirds. Acredito que nessa base podem haver diagramas dos vertibirds. Tudo que preciso é que alguém se infiltre na base, roube os diagramas e os traga para mim.}
{134}{}{Hum... eu fazer?}
{135}{}{Deixe-me adivinhar. Você quer que eu me infiltre nessa base por você.}
{136}{}{Deixe-me ser sincero com você,}
{137}{}{. A Irmandade do Aço não é mais tão poderosa quanto já foi. Nós acreditávamos ser a única fonte de tecnologia restante para a humanidade. Seguros destas crenças nós permitimos que nossa ordem se enfraquecesse ao longo dos anos. Agora nós não temos recursos à nossa disposição para lidar com o Enclave. Nós precisamos de sua ajuda.}
{138}{}{Eu estou preparado para fazer essa oferta. Cumpra essa missão para mim e eu irei lhe conceder acesso ao nosso entreposto aqui. O melhor da tecnologia da Irmandade estará exclusivamente disponível para você. E aí, o que me diz?}
{139}{}{Eu pensar sobre isso.}
{140}{}{Nunca. Eu ir em bora.}
{141}{}{Que diabos. Eu aceitar.}
{142}{}{Eu vou pensar sobre isso.}
{143}{}{De jeito nenhum. Vá arranjar outro otário.}
{144}{}{Que diabos. Eu devo estar doido, mas eu aceito.}
{145}{}{É justo. Volte aqui quando tiver tomado uma decisão.}
{146}{}{Tudo bem. Tchau.}
{147}{}{Ok, mas eu quer saber mais.}
{148}{}{Tudo bem. Te vejo por aí.}
{149}{}{Tudo bem, mas eu gostaria de saber mais alguns detalhes.}
{150}{}{Eu entendo a sua hesitação em aceitar uma missão como essa. Se você mudar de ideia por favor me avise.}
{151}{}{Tudo bem. Tchau.}
{152}{}{Ok, mas eu quer saber mais.}
{153}{}{Tudo bem. Te vejo por aí.}
{154}{}{Tudo bem, mas eu gostaria de saber mais alguns detalhes.}
{155}{}{Ótimo. Eis o que você precisa fazer. Vá até Navarro, infiltre-se na base e adquira os diagramas de vertibirds. Entregue os diagramas para mim.}
{156}{}{Ok. Hã... Como acha que eu pode fazer isso? É base militar.}
{157}{}{Ok. Eu ir agora.}
{158}{}{Tá certo, mas... De que maneira você acha que eu devo me aproximar? Afinal de contas é uma base militar.}
{159}{}{Certo. Vou dar um jeito nisso.}
{160}{}{Após a concluir sua missão, te concederei acesso às nossas instalações aqui. Enquanto isso, seria melhor se você começasse imediatamente. Obrigado,}
{161}{}{.}
{162}{}{Tudo bem. Tchau.}
{163}{}{Certo, mas quer saber mais.}
{164}{}{Certo, a gente se fala.}
{165}{}{Com certeza, mas eu gostaria de tirar mais algumas dúvidas.}
{166}{}{Nós temos essa base há anos. Ao preservá-la em um baixo nível e com o mínimo possível de funcionários para não chamar atenção, nós alcançamos o anonimato. Nós deixamos o Shi em paz, e eles nos deixam em paz.}
{167}{}{Eu achar...}
{168}{}{Sim, eu acho que eu entendo o que você quer dizer.}
{169}{}{Muitas pessoas em um lugar só atraem muita atenção. Uma pessoa em uma cidade cheia de pessoas é mais discreto.}
{170}{}{Tudo bem.}
{171}{}{Olá novamente. Existe algo em que eu possa te ajudar?}
{172}{}{Não, só disse oi.}
{173}{}{Sim. Você responder pergunta?}
{174}{}{Não, só estou de passagem.}
{175}{}{Sim, me tire algumas dúvidas.}
{176}{}{Olá. Você considerou a minha oferta?}
{177}{}{Não. Eu não pensou ainda.}
{178}{}{Sim. Eu aceitar serviço.}
{179}{}{Não, ainda não.}
{180}{}{Sim, eu acho que vou aceitar o serviço.}
{181}{}{Olá. Você mudou de ideia sobre minha oferta?}
{182}{}{Não.}
{183}{}{Sim. Eu aceita.}
{184}{}{Não, não mudei.}
{185}{}{Sim, eu aceito o serviço.}
{186}{}{Você terminou sua missão?}
{187}{}{Não, eu ainda fazendo isso.}
{188}{}{Eu conseguiu diagramas.}
{189}{}{Não, eu ainda estou trabalhando nisso.}
{190}{}{Eu trouxe os diagramas dos vertibirds para você.}
{191}{}{Bem, continue tentando. Eu sei que é uma missão difícil, mas eu acho que você pode dar um jeito nisso.}
{192}{}{Tudo bem.}
{193}{}{Ótimo trabalho! Me empreste os diagramas para que eu possa tirar uma cópia. E como prometido, eu lhe concederei acesso às nossas instalações. Muito obrigado.}
{194}{}{Você é bem-vindo.}
{195}{}{Você é bem-vindo.}
{196}{}{Navarro é relativamente nova e ainda não está completamente guarnecida. Minhas fontes me dizem que eles recebem novos recrutas de tempos em tempos. Talvez você possa se passar por um recruta recém chegado. Eu recomendaria isso.}
{197}{}{Navarro é relativamente nova e ainda não está completamente guarnecida. Minhas fontes me dizem que eles recebem novos recrutas de tempos em tempos. Talvez, se você for lá sozinho, você possa se passar por um recruta recém chegado. Seus amigos podem esperar aqui.}
{198}{}{Tudo bem.}
{199}{}{Você dizer 'fontes'. Quem ser elas?}
{200}{}{Tudo certo.}
{201}{}{Você mencionou suas 'fontes.' Quem seriam eles?}
{202}{}{Eu enviei uma agente para observar a base. Recentemente os relatórios dela pararam de chegar. Eu só posso presumir o pior. Por favor seja cauteloso.}
{203}{}{. Eu não aprecio enviar pessoas para a morte.}
{204}{}{Eu ser cuidadoso, obrigado.}
{205}{}{Serei cuidadoso, obrigado.}
{206}{}{Obrigado novamente pela ajuda. Você tem acesso total à nossas instalações agora.}
{207}{}{Isso é um escritório privado.}
{208}{}{Não há nada para você lá.}
{209}{}{Esta é uma propriedade privada, então, avance.}
{210}{}{Como você sabe quem eu sou?}
{211}{}{Como conhece eu?}
{212}{}{Nós sabemos de muitas coisas.}
{213}{}{Após concluir a missão com sucesso eu irei preparar o petroleiro para você partir, e lhe darei acesso a nossas instalações por aqui. Enquanto isso, seria melhor se você começasse imediatamente. Obrigado,}
{214}{}{Dnada.}
{215}{}{Excelente trabalho! Me empreste os diagramas para que eu faça uma cópia deles. E como prometido, eu vou garantir que o petroleiro esteja pronto para navegar até a plataforma de petróleo - é só ir até o computador no nível superior e apertar o botão de ligar. Também permito que você tenha acesso total às nossas instalações. Obrigado.}
{216}{}{Pur nada!}
{217}{}{Apenas passe por aquela porta ali, se quiser, ou suba até o petroleiro. Ele está pronto para zarpar. Boa sorte!}
{218}{}{Então, estou disposto a te fazer essa oferta. Execute esta missão para mim e eu irei preparar o petroleiro para você em sua jornada para o Enclave. O que me diz?}
{219}{}{Eu pensar sobre isso.}
{220}{}{Nunca. Eu ir em bora.}
{221}{}{Que diabos. Eu aceitar.}
{222}{}{Está bem. Agora vá.}
