{100}{}{Você vê um homem que se parece muito com um lojista.}
{101}{}{Você vê Lao Chou, o lojista.}
{102}{}{Você vê um homem em roupas funcionais e confortáveis.}
{103}{}{Saudações! Bem vindo à minha loja, Flying Dragon 8.}
{104}{}{O que posso fazer por você?}
{105}{}{Da aggle oo!}
{106}{}{Coisas!}
{107}{}{Quem é você?}
{108}{}{Estou procurando por algum equipamento.}
{109}{}{Estou procurando por alguma informação.}
{110}{}{Adeus.}
{111}{}{Você quer comprar algo?}
{112}{}{:: acene com a cabeça ::}
{113}{}{::balançar a cabeça::}
{114}{}{Isso é o que temos, então.}
{115}{}{[FEITO]}
{116}{}{Bem, temo que é tudo que posso fazer por você. Tenha um bom dia. }
{117}{}{[FEITO]}
{118}{}{Eu sou Lao Chou. Eu dirijo este estabelecimento, Flying Dragon 8, uma loja geral. Eu sou conhecido por trocar ... informação.}
{119}{}{Que tipo de informação?}
{120}{}{Entendo. Eu gostaria de algum equipamento.}
{121}{}{Pouco acontece nesta cidade que eu não conheço. Claro, você deve saber a pergunta certa a se fazer, sim? O que você precisa saber?}
{122}{}{Estou procurando algumas atualizações no meu equipamento.}
{123}{}{Onde posso encontrar planos de vertibird?}
{124}{}{Eu preciso encontrar combustível para o PMV Valdez.}
{125}{}{Eu entendo que preciso de um FOB para acessar o computador do Valdez.}
{126}{}{Eu preciso de algumas peças de computador para o PMV Valdez.}
{127}{}{Estou procurando por um baço.}
{128}{}{Eu ouvi que algumas máquinas voadoras trouxeram uma carga de aldeões por este caminho.}
{129}{}{Nada. Tchau.}
{130}{}{Fale com Crochet, no acampamento Hubologista. Ele é o cientista chefe deles.}
{131}{}{Obrigado. Eu preciso de mais informação.}
{132}{}{Obrigado. Tchau.}
{133}{}{Olhe para o norte, em Navarro. Há uma base escondida perto do posto de gasolina.}
{134}{}{Obrigado. Eu preciso de mais informação.}
{135}{}{Obrigado. Tchau.}
{136}{}{Você já tentou procurar nos antigos Refúgios? Eu ouvi dizer que eles são uma riqueza de informações e tecnologia dos antigos.}
{137}{}{Obrigado. Eu preciso de mais informação.}
{138}{}{Obrigado. Tchau.}
{139}{}{Um baço? Ha ha! Sim, Chip do Valdez perdeu o baço em um jogo de cartas no outro dia. Eu vendi para o Dr. Wong. Ele ficou fascinado por isso.}
{140}{}{Dr. Wong? Onde posso encontrá-lo?}
{141}{}{Como você perde um baço?}
{142}{}{Obrigado. Eu tenho mais perguntas.}
{143}{}{Ah, então Tchau.}
{144}{}{O Dr. Wong é o cientista chefe do Palácio de Aço. Procure-o lá.}
{145}{}{Como você perde um baço, aliás?}
{146}{}{Obrigado. Eu preciso de mais informação.}
{147}{}{Obrigado. Tchau.}
{148}{}{Ele estava bêbado. Muito, muito bêbado. Ele estava obcecado com o baço a noite toda. E então ele o aposta.}
{149}{}{Então você pegou o BAÇO dele?}
{150}{}{Eu vejo. Bem, eu tenho mais perguntas.}
{151}{}{Sim. Foi uma dívida. Ele é um homem honrado.}
{152}{}{Entendo. Eu preciso de mais informações.}
{153}{}{Você é um bastardo rude e doente, não é?}
{154}{}{Direito. Tchau.}
{155}{}{Você é uma pessoa desonrosa. Eu não quero você na minha loja. Volte outra hora.}
{156}{}{Seja o que for.}
{157}{}{Não. Eles vieram do norte e voaram sobre nós, indo para o mar.}
{158}{}{Além do horizonte? Como diabos eu chego lá?}
{159}{}{Sim, eles fizeram. Diga-me onde eles estão antes de eu abrir você como uma lata de sardinha.}
{160}{}{Bem... nenhum dos nossos barcos é capaz de percorrer essa distância. A menos que...}
{161}{}{A menos que...?}
{162}{}{Obrigado pela "ajuda". Eu vou procurar um conselho de verdade.}
{163}{}{... a menos que você consiga colocar o velho petroleiro nas docas funcionando. É um navio antigo, mas provavelmente ainda funciona com um pouquinho de trabalho em cima dele. Pergunte aos punks para mais informações.}
{164}{}{Obrigado. Eu preciso de mais informação.}
{165}{}{Obrigado. Tchau.}
{166}{}{Dizem que os Hubologistas conseguiram uma grande quantidade de combustível recentemente. Negocie com eles.}
{167}{}{Obrigado. Eu preciso de mais informação.}
{168}{}{Obrigado. Tchau.}
{169}{}{Você pode tentar alguns dos cientistas Shi no Palácio de Aço. Talvez eles possam ajudá-lo com suas necessidades de combustível.}
{170}{}{Obrigado. Eu preciso de mais informação.}
{171}{}{Obrigado. Tchau.}
{172}{}{Você é um inimigo do meu povo. Morra!}
{173}{}{Você fez bem para o meu pessoal ao matar o AHS-9. Espero poder ajudá-lo de alguma forma.}
{174}{}{Quem é você?}
{175}{}{Estou procurando por algum equipamento.}
{176}{}{Estou procurando por alguma informação.}
{177}{}{Adeus.}
{178}{}{Você já entregou aos Hubologistas. Não?}
{179}{}{Ah sim ... ah ... Posso perguntar outra coisa?}
{180}{}{Oh yeah...Bye.}
{200}{}{O que mais você pode me dizer sobre o petroleiro?}
{210}{}{Mesmo que você consiga trabalhar com o NavCom e abastecer o tanque, você ainda precisará de boa sorte
  se você realmente quer que o navio navegue novamente.}
{211}{}{O que você quer dizer com "boa sorte considerável"?}
{220}{}{Quero dizer, o pedaço de lixo é mais velho que a maioria dos ghouls. Seria um milagre se não afundasse em você. Isso é tudo
  Eu quis dizer.}
{221}{}{Tenho a sensação de que há algo que você não está me contando sobre o petroleiro.}
{230}{}{Perhaps there is. (smiles) Perhaps the wasteland has made you paranoid.}
{231}{}{Listen, I need to find my tribe. Those bastards who took them are dangerous and need to be stopped.}
{232}{}{Come on. What's so special about the tanker? We're just two people talking.}
{233}{}{You sure? I'll make it worth your while.}
{234}{}{I don't have time for these mind games. Goodbye.}
{240}{}{Bah. They are nothing. However, it's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{241}{}{Submarine?}
{250}{}{Let's talk, then. But there's nothing special about the tanker. I give you my word.}
{251}{}{What if I paid you to tell me?}
{260}{}{Hmm... Business has been slow lately. I could use more customers. Or a donation from a very generous one. Say, $2000?}
{261}{}{Here you go. But your information better be worth it.}
{262}{}{$1500 and that's my final offer.}
{263}{}{I don't think so. That's too much.}
{270}{}{(Lao Chou pockets the $2000.) It's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{271}{}{Submarine?}
{280}{}{We have nothing further to discuss, then.}
{281}{}{You sure? My lovely wife Miria will certainly make it worth your while.}
{282}{}{Adeus.}
{285}{}{You drive a hard bargain. Fine, $1500.}
{286}{}{Here you go. But your information better be worth it.}
{287}{}{(Lao Chou pockets the $1500.) It's not the tanker that's special. It's just a big rusty tanker like you said.
 Our submarine, on the other hand...}
{288}{}{Submarine?}
{290}{}{Well if you put it that way, I have been cooped up in this dusty shop for a long time. It has been a quite a while since
 I enjoyed the company of a charming woman like yourself.}
{291}{}{[CONTINUAR]}
{300}{}{[Hours past with no end in sight. You begin to suspect that Lao Chou may not be completely human. You black out, eventually.]}
{301}{}{hhh... What happened?}
{310}{}{You fainted as I moved us into the triple-lotus position, and I had to finish pleasuring myself with the grinning-panda kata.
 But a deal's a deal. It's not the tanker that's special -- it's just a big rusty tanker like you said. Our submarine, on the other hand...}
{311}{}{Submarine?}
{330}{}{I... don't think so.}
{331}{}{Don't try and fight it now. You want me and you know it.}
{340}{}{No, actually. You are not my type.}
{341}{}{Oh, I see. You're not into women.}
{350}{}{I am. I just do not find you very attractive. Perhaps if I were drunk.}
{351}{}{You're obviously blind. Whatever. It's your loss.}
{360}{}{What are you proposing? Ahh... well, I have been cooped up in this shop for a long time. I will reveal all I know
 in exchange for a sample of your lady friend's charms.}
{361}{}{Miria, honey... I guess you'll have to, erm, pump this guy for information.}
{362}{}{I was joking, old man. Like I'd let you make time with my wife... I'm leaving.}
{370}{}{[You wait outside and hear faint moans from inside the Flying Dragon 8. An hour passes, and then another. You
 bang on the door, shouting, "Hurry up in there!" Finally, the moans become a primal scream.]}
{371}{}{[Bang on the door] Hey, what are you two doing in there!?}
{380}{}{A smiling Lao Chou emerges from his bedroom, still pulling on his pants. A few moments later Miria stumbles out behind him, looking dazed and confused but deeply satisfied] Your wife is a great deal more experienced than she looks.}
{381}{}{I, erm, know. Now pull your damn pants up and tell me what's so special about the tanker.}
{390}{}{There's nothing special about the tanker. It's just a big rusty tanker like you said. Our submarine, on the other hand...}
{391}{}{Submarine?}
{400}{}{The Shi-Huang-Ti. My great grandfather, Ye Li, was its captain. He unleashed her nuclear fires like a horrible dragon upon California's coast.}
{401}{}{No shit.}
{410}{}{Ironically, a malfunctioning missile from our own ancestral nation went off course and exploded over the ocean near the submarine's location. The blast knocked out the Shi-Huang-Ti's systems, leaving Captain Ye Li and his crew stranded at sea.}
{411}{}{That's karma for you.}
{420}{}{But there was salvation. After weeks of drifting, the sub finally came to rest out in the shallow waters of the
 San Francisco bay. This city became our new home. We eventually restored the Shi-Huang-Ti; its targeting systems, its
 weapons. It has enough firepower to blow any potential invaders out of the water. So even if you got that old tanker
 running, it wouldn't get far, as the submarine will destroy any non-Chinese vessel that sails through the bay.}
{421}{}{That sounds like a problem alright. So how would I get to the submarine?}
{430}{}{You swim. Or take the motorboat at the docks. It is guarded, though, by one of our best soldiers, and he will
 not let an outsider like you past him.}
{431}{}{You have any idea how I can get past him then, without shooting him in the face?}
{440}{}{He's under strict orders to guard it 24/7. He will not let anyone without the right password through.}
{441}{}{I don't suppose you know it?}
{450}{}{That depends. I don't suppose you have $10000 to ensure the continued prosperity of my shop?}
{451}{}{Here's your $10000.}
{452}{}{That's outrageous for a simple password. I'll only go as high as $5000.}
{453}{}{Nenhum acordo.}
{460}{}{Ah, much appreciated. The password is XY8QIV2SHI. Others may be watching me after this, so don't forget the password. If ever we discuss it again, I'll need even more money for bribes.}
{461}{}{Obrigado. Adeus.}
{470}{}{You are a crafty one, I'll give you that. Fine. I accept your offer. The password is XY8QIV2SHI. Don't forget it, or you'll have buy it from me again.}
{471}{}{Obrigado. Adeus.}
{480}{}{Don't insult me with your meager offers. $10000. Take it or leave it.}
{481}{}{Fine. Here's your $10000.}
{482}{}{Nenhum acordo.}
{490}{}{Your loss then. I don't believe we have anything else to discuss. Goodbye.}
{491}{}{Adeus.}
