{100}{}{You see one of Klamath's citizens.}
{101}{}{You see one of Klamath's citizens.}
{150}{}{Why don't you go back to your tribe?}
{151}{}{I'll give you some pretty beads if you leave me alone.}
{152}{}{Nice tribal, good tribal, don't hurt me.}
{153}{}{I sure wish we had a wall around the town.}
{154}{}{I don't have anything to steal; go away.}
{155}{}{Why are you looking at me like that?}
{156}{}{Great, another tribal.}
{157}{}{Why don't you go back to the golden gecko?}
{158}{}{Just keep away from me.}
{159}{}{We don't need you stirring up trouble.}
{160}{}{You must have come north from the Den.}
{161}{}{Last thing we need is more like you.}
{170}{}{Hello there, stranger.}
{171}{}{I sure hope the trapping's good this season.}
{172}{}{Lots of brahmin going missing lately.}
{173}{}{(Crunch, crunch) Dunton's Drymeat sure is yummy.}
{174}{}{Did you come here to trade hides for firewater?}
{175}{}{I thought all your people put a bone through their noses.}
{176}{}{Watch out for the rats in Trapper Town.}
{177}{}{Now where'd I put those magic beans?}
{178}{}{Geckos taste just like canned chicken, if you cook them right.}
{179}{}{I'm going to relax at the Bathhouse.}
{180}{}{Watch out for the Duntons.}
{181}{}{Buckner house always gives me a fair price on my goods.}
{182}{}{Nice day today.}
{183}{}{You look like Sulik.}
{184}{}{I wonder where that idiot Torr has gone?}
{185}{}{The big secret is - hey, what's this in my pocket?!?}
{186}{}{No rest for the poor.}
{187}{}{My joints ache; weather must be changing.}
{188}{}{Wind's picking up a bit.}
{190}{}{Nice to see you.}
{191}{}{Any more like you at home?}
{192}{}{Hope you're enjoying Klamath.}
{193}{}{We could use a few more people of your caliber here.}
{194}{}{What's up, friend?}
{195}{}{Good fortune to you.}
{196}{}{If you need to buy anything, go to Buckner House.}
{197}{}{You're not like Sulik at all.}
{198}{}{You're the most civilized tribal I've ever met.}
{199}{}{Watch out for geckos that have changed color.}
{200}{}{Hello, traveler.}
{201}{}{Glad to have you in Klamath.}
{202}{}{Howdy, stranger.}
{203}{}{Watch out for those Duntons; they're dangerous.}
{204}{}{Trapper Town sure has a lot of rats.}
{1000}{}{Ancião}
{1001}{}{Fundador}
{1002}{}{Morador do Vault}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Escolhido}
{1007}{}{Xamã}
{1008}{}{Hakunin}
{1009}{}{Cura Em Pó}
{1010}{}{Ponte}
{1011}{}{Mynoc}
{1100}{}{O Ancião é a sua mãe, e o nosso líder.}
{1101}{}{Nosso grande ancestral que nos deu conhecimento.}
{1102}{}{O primeiro a lutar e a vitória sobre o caos.}
{1103}{}{Essa seria a nossa bela aldeia.}
{1104}{}{That's trading outpost a few days east of here.}
{1105}{}{O Vault é o paraíso.}
{1106}{}{Você é o Escolhido.}
{1107}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1108}{}{He heals us with his herbs and magic. He is in the north part
 of our village.}
{1109}{}{É um pó mágico que irá curá-lo, mas irá fazer você
  sonolento.}
{1110}{}{A Grande Ponte sai da nossa aldeia no sul.}
{1111}{}{Ele guarda a ponte que leva para a nossa aldeia.}
