{0}{}{Støílej dávkou}
{1}{}{Uteè z boje}
{2}{}{Volba druhu zbranì}
{3}{}{Vzdálenost}
{4}{}{Útoè na}
{5}{}{Drug Use}
{10}{}{KONEC}
{11}{}{Zrušit}
{99}{}{Nelze pouít.}
{100}{}{Vdy!}
{101}{}{Obèas a nestarej se, kdy mì náhodou trefíš}
{102}{}{Ujisti se nejdøív, e mì nezasáhneš}
{103}{}{Dávej pozor, a mì nezasáhneš}
{104}{}{Musíš si bıt absolutnì jistı, e mì nezasáhneš}
{200}{}{Kdo uteèe, ten vyhraje!}
{201}{}{Lepší ivı pes ne mrtvı lev}
{202}{}{Kdy zaèneš trochu krvácet}
{203}{}{Kdy se necítíš dobøe}
{204}{}{Kdy u je to váné}
{205}{}{Nikdy!}
{300}{}{ádné}
{301}{}{Chladné zbranì}
{302}{}{Chladné zbranì pøed støelnımi}
{303}{}{Støelné zbranì pøed chladnımi}
{304}{}{Støelné zbranì}
{305}{}{Boj beze zbranì}
{400}{}{Dr se poblí mì}
{401}{}{Útoè!}
{402}{}{Odstøeluj je pìknì z dálky}
{403}{}{Jak je ti libo}
{404}{}{Zùstaò na jednom místì}
{500}{}{Toho, kdo útoèí na mì}
{501}{}{Toho nejsilnìjšího}
{502}{}{Toho neslabšího}
{503}{}{Koho chceš}
{504}{}{Toho, kdo je nejblí}
{600}{}{Nic neber}
{601}{}{Stimpaky, kdykoliv máš zranìní}
{602}{}{Stimpaky, kdy máš váné zranìní}
{603}{}{Obèas si vezmi libovolnou drogu}
{604}{}{Vezmi si, co chceš a kdy chceš}
