#
# Item.c messages
#
{1}{}{Získáváš %d %s.}
{2}{}{Ztrácíš %d %s.}
{3}{}{Cítíš se lépe.}
{4}{}{Postihl tì prudký srdeèní záchvat z pøedávkování chemikáliemi.}
{5}{}{%s už není èím nabít.}
{6}{}{%s je zapnut.}
{7}{}{%s je vypnut.}
{8}{}{Pøejíždíš si Geigerovým poèítaèem po tìle. Display ukazuje: %d}
{9}{}{Tento pøedmìt se dá použít pouze z inventáøe.}
{10}{}{Nic se nestalo.}


# Fallout 2:
{50}{}{Vypadá to, že se nic nestalo.}


#
# Fallout 2
#
{500}{}{K nabití zbranì tu není dost svìtla.}
#
{600}{}{%s podléhá nepøíznivému úèinku chemikálií.}

# Weapon Damage strings
{800}{}{Lehké}
{801}{}{Støední}
{802}{}{Tìžké}
{803}{}{Extrémní}
# Weapon Range strings
{820}{}{Krátká}
{821}{}{Støední}
{822}{}{Dlouhá}