{1}{}{Získáváš %d %s.}
{2}{}{Ztrácíš %d %s.}
{3}{}{Cítíš se lépe.}
{4}{}{Postihl tě prudký srdeční záchvat z předávkování drogami.}
{5}{}{%s už není čím nabít.}
{6}{}{%s je zapnut.}
{7}{}{%s je vypnut.}
{8}{}{Přejíždíš si Geigerovým počítačem po těle. Display ukazuje: %d}
{9}{}{Tento předmět se dá použít pouze z inventáře.}
{10}{}{Nic se nestalo.}
{50}{}{Vypadá to, že se nic nestalo.}
{500}{}{K nabití zbraně tu není dost světla.}
{600}{}{%s podléhá nepříznivému účinku drog.}
{800}{Weapon Damage}{Lehké}
{801}{}{Střední}
{802}{}{Těžké}
{803}{}{Extrémní}
{820}{}{Krátká}
{821}{}{Střední}
{822}{}{Dlouhá}
