{100}{}{Koená zbroj}
{101}{}{Tvoje základní koená vıstroj. Peèlivì vyrobená z brahmíní kùe.}
{200}{}{Kovová zbroj}
{201}{}{Vyleštìné kovové pláty nahrubo pospojované do zbroje.}
{300}{}{Energo zbroj}
{301}{}{Hi-tech oblek s vlastním pohonem. Je napájen mikro-fúzním reaktorem s dostatkem paliva na sto let.}
{400}{}{Nù}
{401}{}{Ostrá bodná a seèná zbraò. Min. SÍ: 2.}
{500}{}{Tonfa}
{501}{}{Univerzální armádní a policejní obušek z tvrdého døeva. Min. SÍ: 3.}
{600}{}{Perlík}
{601}{}{Veliké kladivo s dlouhou rukojetí. Velmi oblíbená zbraò mezi svalovci. Min. SÍ: 6.}
{700}{}{Kopí}
{701}{}{Tyè s hrotem na konci. Násada je døevìná a hrot je vyroben z kalené oceli. Min. SÍ: 4.}
{800}{}{10mm pistole}
{801}{}{Samonabíjecí pistole Colt 6520 ráe 10mm. Kadı stisk spouštì automaticky nabije zbraò, dokud se nevyprázdní zásobník. Neumoòuje støelbu dávkou. Pouívá úèinnou 10mm munici. Min. SÍ: 3.}
{900}{}{10mm samopal}
{901}{}{Samopal H&K MP9 (10mm verze). Støednì velikı samopal schopnı støelby jednotlivımi ranami nebo dávkou. Min. SÍ: 4.}
{1000}{}{Lovecká puška}
{1001}{}{Poloautomatická puška Colt Rangemaster kalibr .223. Neumoòuje støelbu dávkou. Min. SÍ: 5.}
{1100}{}{Plamenomet}
{1101}{}{Plamenomet model Flambe 450. Chrlí krátké dávky extrémnì hoølavé tekutiny. Vyaduje speciální náplò. Min. SÍ: 6.}
{1200}{}{Gatling}
{1201}{}{Osobní gatling Rockwell CZ53. Nìkolikahlavòovı rotaèní kulomet, kterı støílí 5mm munici s kadencí více ne 60 000 ran za minutu. Min. SÍ: 7.}
{1300}{}{Raketomet}
{1301}{}{Raketomet Rockwell BigBazooka s luxusní 1,5 kg spouští. Odpaluje prùbojné nebo vıbušné rakety. Min. SÍ: 6.}
{1400}{}{Vıbušná raketa}
{1401}{}{Raketa s vysoce vıbušnou hlavicí.}
{1500}{}{Plazmová puška}
{1501}{}{Plazmová puška Winchester model P94. Tato odolná energetická zbraò vystøeluje èástice pøehøáté plazmy skrz supravodivou hlaveò. Napájena mikro-fúzními èlánky. Min. SÍ: 6.}
{1600}{}{Laserová pistole}
{1601}{}{Laserová pistole Wattz 1000. Jedná se o civilní model, tudí má niší vıkon ne armádní nebo policejní varianty. Napájena pomocí malıch energetickıch èlánkù. Min. SÍ: 3.}
{1700}{}{Kevlarová zbroj}
{1701}{}{Hi-tech zbroj vyrobená z pokroèilıch defenzívních polymerù.}
{1800}{}{Desert Eagle .44}
{1801}{}{Starobylá pistole Desert Eagle pouívající munici .44 magnum. Èasté pouívání ve filmech pozdního 20. století z ní udìlalo jednu z nejpopulárnìjších pistolí všech dob. Min. SÍ: 4.}
{1900}{}{Kámen}
{1901}{}{Prostì kámen. Upgradovanı model se vyrábí pod znaèkou ula-Inc. Min. SÍ: 1.}
{2000}{}{Páèidlo}
{2001}{}{Masivní kus tìkého kovu vyrobenı za úèelem vyuití pákového efektu. Nebo k rozbíjení hlav. Min. SÍ: 5.}
{2100}{}{Mosaznı boxer}
{2101}{}{Tvrzenı boxer, kterı je ve skuteènosti vyroben z oceli. Náprstníkové krouky chrání ruku a zpùsobují vìtší poranìní v boji beze zbranì. Min. SÍ: 1.}
{2200}{}{14mm pistole}
{2201}{}{Automatická pistole Sig-Sauer 14mm. Veliká zbraò urèená pro støelbu jednotlivımi ranami. Vıteèné zpracování. Min. SÍ: 4.}
{2300}{}{Útoèná puška}
{2301}{}{Útoèná puška AK-112 5mm. Stará armádní zbraò vyøazená v prùbìhu války. Schopná støelby jednotlivımi ranami nebo dávkou. Pouívá vysokorychlostní 5mm munici. Min. SÍ: 5.}
{2400}{}{Plazmová pistole}
{2401}{}{Plazmová pistole Glock 86. Navrena v Gaston Glock AI. Støílí malé èástice pøehøáté plazmy. Napájena malımi energetickımi èlánky. Min. SÍ: 4.}
{2500}{}{Granát (Tøíštivı)}
{2501}{}{Obyèejnı tøíštivı granát. Obsahuje malé mnoství vıbušniny, která roztrhne pláš na velké mnoství zraòujících støepin. Vybuchuje pøi nárazu. Min. SÍ: 3.}
{2600}{}{Granát (Plazmovı)}
{2601}{}{Magneticky uzavøená schránka s plazmou a iniciaèní vıbušninou. Pøi kontaktu vzniká oblak pøehøáté plazmy. Min. SÍ: 4.}
{2700}{}{Granát (Pulzní)}
{2701}{}{Elektromagnetickı pulzní granát vytváøející silné elektromagnetické pole v místì exploze. Nemá ádnı efekt na ivé tvory. Nárazová pojistka. Min. SÍ: 4.}
{2800}{}{Laserovı gatling}
{2801}{}{Rotaèní laser H&K L30. Urèen vıhradnì pro armádní pouití, avšak na zaèátku války byl teprve ve stádiu prototypu. Vìtší poèet hlavní umoòuje delší støelbu bez pøehøívání. Napájen mikro-fúzními èlánky. Min. SÍ: 6.}
{2900}{}{10mm JHP}
{2901}{}{Munice. Kalibr: 10mm, plášová expanzní støela.}
{3000}{}{10mm AP}
{3001}{}{Munice. Kalibr: 10mm, prùrazná støela.}
{3100}{}{.44 Magnum JHP}
{3101}{}{Plášové expanzní støely, kalibr .44.}
{3200}{}{Náplò do plamenometu}
{3201}{}{Tlaková nádoba obsahující vysoce hoølavou tekutinu pro plamenomet.}
{3300}{}{14mm AP}
{3301}{}{Velkoráová munice. Prùrazná 14mm.}
{3400}{}{.223 FMJ}
{3401}{}{Munice. Kalibr .223, celoplášová expanzní støela.}
{3500}{}{5mm JHP}
{3501}{}{Zásobník malé lehké munice. Kalibr: 5mm, plášová expanzní støela.}
{3600}{}{5mm AP}
{3601}{}{Zásobník malé lehké munice. 5mm prùrazná støela.}
{3700}{}{Raketa AP}
{3701}{}{Raketa s malım mnostvím vıbušniny. Navrena k proráení pancíøe.}
{3800}{}{Malı energetickı èlánek}
{3801}{}{Hermeticky uzavøenı zásobník energie.}
{3900}{}{Mikro-fúzní èlánek}
{3901}{}{Støednì veliká jednotka na vırobu energie. V podstatì miniaturní fúzní elektrárna.}
{4000}{}{Stimpak}
{4001}{}{A healing drug. When injected, the drug provides immediate healing of minor wounds.}
{4100}{}{Peníze}
{4101}{}{Legální platidlo postapokalyptického svìta.}
{4200}{}{Lednièka}
{4201}{}{Lednice. Chladící smìs u dávno vyprchala.}
{4300}{}{Chladící box}
{4301}{}{Starı chladící box. Panty jsou v dobrém stavu.}
{4400}{}{Chladící box}
{4401}{}{Starı chladící box. Panty jsou v dobrém stavu.}
{4500}{}{Vrhací nù}
{4501}{}{Nù speciálnì vyváenı pro vrhání. Vyroben z titanu a laserovì naostøen. Min. SÍ: 3.}
{4600}{}{Vak}
{4601}{}{Pytel prùmìrné velikosti. Utkán z brahmíní kùe.}
{4700}{}{Soupravu první pomoci}
{4701}{}{Malá souprava obsahující základní lékaøské vybavení jako jsou obinadla, náplasti, dezinfekèní prostøedky apod.}
{4800}{}{RadAway}
{4801}{}{Chemickı roztok, kterı na sebe váe radioaktivní èástice a pøirozenımi vyluèovacími cestami je odvádí pryè z tìla. Plnı úèinek vyaduje nìjakı èas.}
{4900}{}{Protijed}
{4901}{}{Láhev obsahující podomácku vyrobenı protijed. Mléènı roztok s plovoucími kousky radškorpioního masa.}
{5000}{}{Reserved Item}
{5001}{}{This is a reserved item. DO NOT USE.}
{5100}{}{Dynamit}
{5101}{}{Vysoce vıbušnı mix nitroglycerinu s hlinkou. Vèetnì èasovaèe.}
{5200}{}{Geigerùv poèítaè}
{5201}{}{Geiger-Müllerùv detektor radioaktivních èástic. Model Wattz Electronics C-Radz. Detekuje pøítomnost a mnoství radioaktivních èástic.}
{5300}{}{Mentats}
{5301}{}{A pillbox of mind-altering drugs. Increases memory related functions, and speeds other mental processes. Highly addictive.}
{5400}{}{Mizík}
{5401}{}{Osobní zneviditelòovací zaøízení RobCo Mizík 3001. Generuje modulující pole, které pøenáší odraené svìtlo z jedné strany objektu na druhou. Je zapnutı.}
{5500}{}{Vodní èip}
{5501}{}{Vodní èip firmy Vault-Tec. Obvykle bıvá zabalen po pìti v jedné krabici.}
{5600}{}{Psí známky}
{5601}{}{Sada vojenskıch identifikaèních známek. Jméno Dickinson a slovo Enkláva jsou stìí k pøeètení.}
{5700}{}{Štìnice}
{5701}{}{Miniaturní mikrofon a vysílaè.}
{5800}{}{Holopáska}
{5801}{}{Páska Wattz Electronics Holodisc. Je v opravdu špatném stavu.}
{5900}{}{Detektor pohybu}
{5901}{}{Detektor pohybu model Wattz Electronics C-U. Detekuje jakıkoliv pohyb biologického pùvodu v okruhu nìkolika metrù. Máš-li jej ve svém inventáøi, vyhneš se èastìji náhodnım setkáním (+20% ke schopnosti Pøeití v pustinì).}
{6000}{}{Knihovna}
{6001}{}{Døevìná knihovna.}
{6100}{}{Knihovna}
{6101}{}{Døevìná knihovna.}
{6200}{}{Knihovna}
{6201}{}{Døevìná knihovna.}
{6300}{}{Knihovna}
{6301}{}{Døevìná knihovna.}
{6400}{}{Knihovna}
{6401}{}{Døevìná knihovna.}
{6500}{}{Knihovna}
{6501}{}{Døevìná knihovna.}
{6600}{}{Stùl}
{6601}{}{Døevìnı stùl.}
{6700}{}{Stùl}
{6701}{}{Døevìnı stùl.}
{6800}{}{Prádelník}
{6801}{}{Døevìnı prádelník.}
{6900}{}{Prádelník}
{6901}{}{Døevìnı prádelník.}
{7000}{}{Prádelník}
{7001}{}{Døevìnı prádelník.}
{7100}{}{Ovoce}
{7101}{}{Podivnı kus ovoce. Bez konzervaèních látek a potravinového barviva.}
{7200}{}{Kuføík}
{7201}{}{Kuføík s cedulkou 'Made-in-the-USA'. Koenı. V dobrém stavu, ale s rozbitım èíselnım zámkem.}
{7300}{}{Velká encyklopedie vìdy}
{7301}{}{Nìkolik knih obsahujících informace z mnoha odlišnıch vìdeckıch odvìtví.}
{7400}{}{Koená bunda}
{7401}{}{Èerná bunda z hrubé kùe.}
{7500}{}{Univerzální kleštì}
{7501}{}{Sada náøadí obsahující nejrùznìjší uiteèné nástroje vèetnì kleští.}
{7600}{}{Skripta elektroniky}
{7601}{}{Studijní materiál pro studenty elektroniky. Poznámka na obalu øíká - "Probuïte v sobì mladého elektrotechnika!"}
{7700}{}{Elektronickı paklíè}
{7701}{}{Wattz Electronics mikromanipulaèní elektronickı paklíè. Pro odblokování elektronickıch zámkù a bezpeènostních systémù.}
{7800}{}{Rozmazanı obraz}
{7801}{}{Oèividnì velmi starı obraz nìjakého zpìváka. Rám je stále v dobrém stavu.}
{7900}{}{Svìtlice}
{7901}{}{Svìtlice. Na krátkou dobu vytvoøí intenzivní svìtlo. Papír je trochu opotøebovanı, ale jinak je v dobrém stavu. Aktivuje se pootoèením horní èásti.}
{8000}{}{Pøíruèka první pomoci}
{8001}{}{Skripta popisující zásady první pomoci vèetnì praktickıch ukázek.}
{8100}{}{Leguán na špejli}
{8101}{}{A cooked iguana, roasted in its own skin.}
{8200}{}{Klíè}
{8201}{}{Klíè. Urèitì pasuje do nìjakého zámku.}
{8300}{}{Svazek klíèù}
{8301}{}{Nìkolik klíèù.}
{8400}{}{Sada paklíèù}
{8401}{}{Sada zámeènického náøadí. Obsahuje paklíèe a šperháky potøebné k otevøení všech klasickıch i dozickıch zámkù.}
{8500}{}{Plastická vıbušnina}
{8501}{}{Kostka Cordexu, vojenské znaèky plastickıch trhavin. Velmi nièivá a pøitom vysoce stabilní. Vèetnì èasovaèe.}
{8600}{}{Skautská pøíruèka}
{8601}{}{Kniha o metodách a idejích skautingu. Plná praktickıch informací o ivotì ve volné pøírodì.}
{8700}{}{Buffout}
{8701}{}{Velmi úèinné steroidy. Po dobu pùsobení zvyšují sílu a zrychlují reflexy. Vysoce návykové.}
{8800}{}{Hodinky}
{8801}{}{Drahé hodinky. Sice nefungují, ale stále vypadají velmi dobøe.}
{8900}{}{Motor}
{8901}{}{Elektrickı motor o vıkonu 40 koòskıch sil.}
{9000}{}{Batoh}
{9001}{}{Batoh s nìkolika kapsami.}
{9100}{}{Doktorskı kuføík}
{9101}{}{This brown bag contains instruments and drugs used by doctors in the application of their trade.}
{9200}{}{Radškorpioní ocas}
{9201}{}{Oddìlenı ocas z radškorpiona.}
{9300}{}{Vak}
{9301}{}{Vak prùmìrné velikosti. Vyroben z brahmíní kùe.}
{9400}{}{Brokovnice}
{9401}{}{Dvouhlavòová brokovnice Winchester Ovdovovaè ráe 12. S krátkou hlavní a mahagonovou pabou. Min. SÍ: 4.}
{9500}{}{Brokové náboje ráe 12}
{9501}{}{Munice do brokovnice. Toto støelivo je oznaèeno: "broky ráe 12, nevhodné pro dìti do tøí let."}
{9600}{}{Èervená pøístup. karta}
{9601}{}{Elektronickı bezpeènostní klíè oznaèenı èervenou barvou.}
{9700}{}{Modrá pøístupová karta}
{9701}{}{Elektronickı bezpeènostní klíè oznaèenı modrou barvou.}
{9800}{}{Haraburdí}
{9801}{}{Haraburdí. Ode všeho trochu.}
{9900}{}{Zlatı pøívìsek}
{9901}{}{Velice cennı zlatı pøívìsek.}
{10000}{}{Vysílaèka}
{10001}{}{Radiovı komunikátor model 2043B od firmy Wattz Electronics. Robustní, spolehlivı a maskovanı. S doplòkovım rozhraním RS-121.}
{10100}{}{Zapalovaè}
{10101}{}{Støíbrnı zapalovaè na butan. V dobrém stavu.}
{10200}{}{Zbranì a støelivo}
{10201}{}{Støeleckı bulvár. Èasopis zamìøenı na praktické pouívání støelnıch zbraní a obèasné zaujaté recenze.}
{10300}{}{Leguán na špejli}
{10301}{}{Spálené maso se zeleninou na tyèi.}
{10400}{}{Magnetofon}
{10401}{}{Magnetofon Zahraj-Mi-To od Wattz Electronics. Nahrává a pøehrává standardní 30ti minutové Nahraj-To-Jednou pásky s vysokou hustotou záznamu.}
{10500}{}{Klíè}
{10501}{}{Speciální druh klíèe.}
{10600}{}{Nuka-Cola}
{10601}{}{Láhev Nuka-Coly, oblíbené sodovky post-nukleárního svìta. Nápoj je teplı a zvìtralı.}
{10700}{}{Kosti}
{10701}{}{Hromádka podivnıch kostí.}
{10800}{}{Kosti}
{10801}{}{Hromádka podivnıch kostí.}
{10900}{}{Rad-X}
{10901}{}{Anti-radiation drugs to be taken before exposure. No known side effects.}
{11000}{}{Psycho}
{11001}{}{Prostøedek s unikátním aplikaèním systémem obsahujícím neznámé chemikálie pravdìpodobnì vojenského pùvodu. Všeobecnì se má za to, e jeho pouití zvyšuje bojové schopnosti vojákù.}
{11100}{}{.44 magnum FMJ}
{11101}{}{Zásobník munice ráe .44 magnum, celoplášová expanzní støela.}
{11200}{}{Urna}
{11201}{}{Nádherná zlatá urna s nápisem "Harriet".}
{11300}{}{Róba}
{11301}{}{Obnošené roucho.}
{11400}{}{Tanglerova ruka}
{11401}{}{Robotickı manipulátor ve tvaru a podobì ruky. Byl poškozen pøi neodborném pokusu o rozebrání.}
{11500}{}{Super Kladivo}
{11501}{}{Mohutnı perlík vyrobenı v dílnách Bratrstva Oceli za pouití nejmodernìjší dostupné technologie. Obsahuje zásobník kinetické energie, kterı umocòuje úder. Min. SÍ: 5.}
{11600}{}{Trhaè}
{11601}{}{Vibraèní nù znaèky Trhaè(tm). Napájen malımi energetickımi èlánky. Jeho vibrující øetìzová èepel je schopna roztrhat a rozpárat svùj cíl bìhem nìkolika sekund. Min. SÍ: 4.}
{11700}{}{Kytka}
{11701}{}{Nádherná kvìtina.}
{11800}{}{Laserová puška}
{11801}{}{Laserová puška model Wattz 2000. Mikro-fúzní èlánky poskytují laseru vyšší vıkon a prodlouená hlaveò umoòuje delší dostøel. Min. SÍ: 6.}
{11900}{}{Náhrdelník}
{11901}{}{Luxusnì vypadající náhrdelník vyrobenı ze zlata, støíbra a broušenıch diamantù.}
{12000}{}{Alien Blaster}
{12001}{}{Podivná zbraò zjevnì mimozemského pùvodu. Nicménì se zdá, e mùe vyuívat malé energetické èlánky. Min. SÍ: 2.}
{12100}{}{9mm náboje}
{12101}{}{Sada prastarıch nábojù 9x19mm. Jsou chránìné tlustou vrstvou vazelíny proti pùsobení okolního prostøedí. Standardní náboje.}
{12200}{}{9mm Mauser}
{12201}{}{Pistole Mauser M/96 ráe 9x19mm Parabellum. Ve vıborném stavu. Neobyèejnì pøesná. Min. SÍ: 3.}
{12300}{}{Psychickı anulátor}
{12301}{}{Podivné zaøízení vytvoøené zvláštní technologií.}
{12400}{}{Pivo}
{12401}{}{Nìjakı druh podomácku vaøeného piva.}
{12500}{}{Pálenka}
{12501}{}{Starodávnı likér z pøedváleèné éry.}
{12600}{}{Láhev na vodu}
{12601}{}{Nádoba na pøechovávání vody a jinıch tekutin.}
{12700}{}{Provaz}
{12701}{}{Pevné a silné lano. Dlouhé asi 15 metrù.}
{12800}{}{Botník}
{12801}{}{Malá skøíòka. Pøechovává vìci, leí u postele a dá se zamknout.}
{12900}{}{Botník}
{12901}{}{Malá skøíòka. Pøechovává vìci, leí u postele a dá se zamknout.}
{13000}{}{Botník}
{13001}{}{Malá skøíòka. Pøechovává vìci, leí u postele a dá se zamknout.}
{13100}{}{Botník}
{13101}{}{Malá skøíòka. Pøechovává vìci, leí u postele a dá se zamknout.}
{13200}{}{Skøíòka}
{13201}{}{Skøíòka na vìci.}
{13300}{}{Skøíòka}
{13301}{}{Skøíòka na vìci.}
{13400}{}{Skøíòka}
{13401}{}{Skøíòka na vìci.}
{13500}{}{Skøíòka}
{13501}{}{Skøíòka na vìci.}
{13600}{}{Skøíòka}
{13601}{}{Skøíòka na vìci.}
{13700}{}{Skøíòka}
{13701}{}{Skøíòka na vìci.}
{13800}{}{Skøíòka}
{13801}{}{Skøíòka na vìci.}
{13900}{}{Skøíòka}
{13901}{}{Skøíòka na vìci.}
{14000}{}{Pøístupová karta}
{14001}{}{Bezpeènostní pøístupová karta. Stále v provozuschopném stavu.}
{14100}{}{Odznak Dìtí}
{14101}{}{Odznak ve tvaru symbolu Dìtí Katedrály. Na jedné stranì si všimneš hrbolù a zoubkování, které ti pøipomínají klíè.}
{14200}{}{Odznak Dìtí}
{14201}{}{Odznak ve tvaru symbolu Dìtí Katedrály. Na jedné stranì si všimneš hrbolù a zoubkování, které ti pøipomínají klíè.}
{14300}{}{Odstøelovací puška}
{14301}{}{Odstøelovací puška DKS-501. Projektilová zbraò s vynikajícím dostøelem. Pùvodnì ráe .308, nicménì tato byla pøevrtána na bìnìjší kalibr .223. Min. SÍ: 5.}
{14400}{}{Super-Stimpak}
{14401}{}{Pokroèilı léèící prostøedek. Velmi úèinnı. Vzhledem ke koncentraci pouitıch chemickıch pøípravkù zpùsobuje po nìjaké dobì drobné škody na organismu.}
{14500}{}{Knihovna}
{14501}{}{Døevìná knihovna.}
{14600}{}{Knihovna}
{14601}{}{Døevìná knihovna.}
{14700}{}{Knihovna}
{14701}{}{Døevìná knihovna.}
{14800}{}{Knihovna}
{14801}{}{Døevìná knihovna.}
{14900}{}{Knihovna}
{14901}{}{Døevìná knihovna.}
{15000}{}{Knihovna}
{15001}{}{Døevìná knihovna.}
{15100}{}{Police}
{15101}{}{Øada døevìnıch regálù.}
{15200}{}{Police}
{15201}{}{Øada døevìnıch regálù.}
{15300}{}{Police}
{15301}{}{Øada døevìnıch regálù.}
{15400}{}{Police}
{15401}{}{Øada døevìnıch regálù.}
{15500}{}{Police}
{15501}{}{Øada døevìnıch regálù.}
{15600}{}{Police}
{15601}{}{Øada døevìnıch regálù.}
{15700}{}{Ponk}
{15701}{}{Ponk. Jo, tvùj starı vyslouilı ponk. Vypadá dobøe.}
{15800}{}{Deska s náøadím}
{15801}{}{Tato deska obsahuje rùzné náøadí zavìšené nad ponkem.}
{15900}{}{Molotovùv koktejl}
{15901}{}{Zápalná láhev domácí vıroby. Min. SÍ: 3.}
{16000}{}{Elektrickı obušek}
{16001}{}{Elektrickı obušek model "Farmáøùv nejlepší pøítel" od Wattz Electronics. Napájen malımi energetickımi èlánky. Min. SÍ: 4.}
{16100}{}{Vzduchovka RR}
{16101}{}{Vzduchovka Red Ryder. Klasika. Min. SÍ: 3.}
{16200}{}{Vzduchovka RR LE}
{16201}{}{Limitovaná edice vzduchovky Red Ryder. Opravdová klasika. Min. SÍ: 3.}
{16300}{}{Diabolky}
{16301}{}{Krabice pøedváleènıch diabolek. Ve vıborném stavu. Nerezová ocel.}
{16400}{}{Páska o Bratrstvu}
{16401}{}{Holodisk o Bratrstvu Oceli.}
{16500}{}{Stánek s leguány}
{16501}{}{Domov Bobovıch Leguáních kouskù. Existuje snad nìco lepšího ne èerstvì opeèenı leguán?}
{16600}{}{Stùl}
{16601}{}{Obyèejnı stùl. Drí vìci nad zemí.}
{16700}{}{Stùl}
{16701}{}{Obyèejnı stùl. Drí vìci nad zemí.}
{16800}{}{Vìci}
{16801}{}{Rùzné pøedmìty známé také jako "vìci".}
{16900}{}{Vìci}
{16901}{}{Rùzné pøedmìty známé také jako "vìci".}
{17000}{}{Vìci}
{17001}{}{Rùzné pøedmìty známé také jako "vìci".}
{17100}{}{Vìci}
{17101}{}{Rùzné pøedmìty známé také jako "vìci".}
{17200}{}{Vìci}
{17201}{}{Rùzné pøedmìty známé také jako "vìci".}
{17300}{}{Vìci}
{17301}{}{Rùzné pøedmìty známé také jako "vìci".}
{17400}{}{Vìci}
{17401}{}{Rùzné pøedmìty známé také jako "vìci".}
{17500}{}{Vìci}
{17501}{}{Rùzné pøedmìty známé také jako "vìci".}
{17600}{}{Vìci}
{17601}{}{Rùzné pøedmìty známé také jako "vìci".}
{17700}{}{Vìci}
{17701}{}{Rùzné pøedmìty známé také jako "vìci".}
{17800}{}{Vìci}
{17801}{}{Rùzné pøedmìty známé také jako "vìci".}
{17900}{}{Vìci}
{17901}{}{Rùzné pøedmìty známé také jako "vìci".}
{18000}{}{Bedna}
{18001}{}{Døevìná bedna plná nejrùznìjších vìcí.}
{18100}{}{Stùl}
{18101}{}{Obyèejnı stùl. Vidìl-li jsi jeden, vidìl jsi je všechny.}
{18200}{}{Stùl}
{18201}{}{Obyèejnı stùl.}
{18300}{}{Stùl}
{18301}{}{Obyèejnı stùl.}
{18400}{}{Stùl}
{18401}{}{Obyèejnı stùl.}
{18500}{}{Stùl}
{18501}{}{Obyèejnı stùl.}
{18600}{}{Stùl}
{18601}{}{Obyèejnı stùl.}
{18700}{}{Stùl}
{18701}{}{Obyèejnı stùl.}
{18800}{}{Skøíòka}
{18801}{}{Skøíòka.}
{18900}{}{Skøíòka}
{18901}{}{Skøíòka.}
{19000}{}{FEV disk}
{19001}{}{A holotape containing medical information. Can be used to enter information into your Pip-Boy.}
{19100}{}{Bezpeènostní disk}
{19101}{}{A holotape with the writing "Security Log" on the label. You can use it to transfer the data it contains to your Pip-Boy.}
{19200}{}{Experiment Alpha disk}
{19201}{}{Na holopásce stojí: "Záznam experimentu Alpha"}
{19300}{}{Experiment Delta disk}
{19301}{}{Na holopásce stojí: "Záznam experimentu Delta"}
{19400}{}{Disk s experimenty Vree}
{19401}{}{This holotape has been updated with medical evidence from Vree of the BoS. It can be used to transfer the data to your Pip-Boy.}
{19500}{}{Sbírka zákonù Bratrstva}
{19501}{}{A holotape, with a rough symbol of the Brotherhood of Steel inscribed on it. Use the tape to transfer the data to your Pip-Boy.}
{19600}{}{Vysílání mutantù}
{19601}{}{This holotape looks like it was set to record audio data from a radio. Use the tape to transfer the information to your Pip-Boy.}
{19700}{}{Bedna}
{19800}{}{Bedna}
{19900}{}{Bedna}
{20000}{}{Bedna}
{20100}{}{Bedna}
{20200}{}{Bedna}
{20300}{}{Bedna}
{20400}{}{Bedna}
{20500}{}{Svìtlice}
{20501}{}{Svìtlice. Na krátkou dobu vytvoøí intenzivního svìtlo. Papír je trochu opotøebovanı, ale jinak je v dobrém stavu. Aktivuje se pootoèením horní èásti. Svítí.}
{20600}{}{Dynamit}
{20601}{}{Vysoce vıbušnı mix nitroglycerinu s hlinkou. Vèetnì èasovaèe, kterı tiká.}
{20700}{}{Geigerùv poèítaè}
{20701}{}{Geiger-Müllerùv detektor radioaktivních èástic. Model Wattz Electronics C-Radz. Detekuje pøítomnost a mnoství radioaktivních èástic. Je zapnutı.}
{20800}{}{Detektor pohybu}
{20801}{}{Detektor pohybu model Wattz Electronics C-U. Detekuje jakıkoliv pohyb biologického pùvodu v okruhu nìkolika metrù. Je zapnutı.}
{20900}{}{Plastická vıbušnina}
{20901}{}{Kostka Cordexu, vojenské znaèky plastickıch trhavin. Velmi nièivá a pøitom vysoce stabilní. Vèetnì èasovaèe, kterı tiká.}
{21000}{}{Mizík}
{21001}{}{Osobní zneviditelòovací zaøízení RobCo Mizík 3001. Generuje modulující pole, které pøenáší odraené svìtlo z jedné strany objektu na druhou. Je zapnutı.}
{21100}{}{Kosti}
{21101}{}{Vidíš Eda. Ed je mrtvı.}
{21200}{}{Tandi}
{21201}{}{Smlouváš o propuštìní Tandi.}
{21300}{}{Pozùstatky Gizma}
{21301}{}{Gizmo, bıvalı zloèineckı boss Junktownu, je mrtvı. A také pìknì zapáchá.}
{21400}{}{Stùl}
{21401}{}{Stùl. Po bliším prozkoumání dojdeš k závìru, e je to opravdu jenom stùl.}
{21500}{}{Historie Bratrstva}
{21501}{}{A holotape containing information relating to the Brotherhood of Steel. Can be used to enter information into your Pip-Boy 2000.}
{21600}{}{Maxsonova historie}
{21700}{}{Maxsonùv deník}
{21800}{}{Malé léèení}
{21801}{}{Zvol tuto monost, pokud chceš vyléèit lehké zranìní.}
{21900}{}{Støední léèení}
{21901}{}{Zvol tuto monost, pokud chceš vyléèit støední zranìní.}
{22000}{}{Velké léèení}
{22001}{}{Zvol tuto monost, pokud chceš vyléèit tìké zranìní.}
{22100}{}{Bezpeènostní karta}
{22101}{}{Klíèová karta s bezpeènostním provìøením zakódovanım velice jednoduchou elektronikou.}
{22200}{}{Pøepínaè pole}
{22201}{}{Elektronické vysílací zaøízení s velmi jednoduchım a velkım pøepínacím tlaèítkem. Zdá se, e bylo nedávno pøizpùsobeno pro velmi velké ruce.}
{22300}{}{lutá pøístupová karta}
{22301}{}{Elektronickı bezpeènostní klíè oznaèenı lutou barvou.}
{22400}{}{Malá soška}
{22401}{}{Myslíš si, e by to mohl bıt vyøezávanı "Pip-Boy", ale nevíš to jistì.}
{22500}{}{Èasopis "Koèièí Packa"}
{22501}{}{Vıtisk èasopisu "Koèièí Packa".}
{22600}{}{Krabice nudlí}
{22601}{}{Nemáš tušení, co znamená "Instantní špagety".}
{22700}{}{Malá zaprášená krabice}
{22701}{}{Televizní svaèinka. Nevíš to jistì, ale pravdìpodobnì se to nedá jíst. A kdo ví, jestli to vùbec nìkdy k jídlu bylo.}
{22800}{}{Technickı manuál}
{22801}{}{Návod na údrbu a opravu energo zbroje T-51b.}
{22900}{}{Malá souèástka}
{22901}{}{Mechanická strojní souèástka. Pokud tato souèástka ve stroji chybí, tak je více ne jisté, e stroj nepracuje správnì.}
{23000}{}{Záznamy Vaultu}
{23001}{}{Souhrn událostí a dùleitıch záznamù z poèítaèového systému Vaultu. Pravdìpodobnì poškozeno.}
{23100}{}{Bezpeènostní kód vojenské základny}
{23101}{}{}
{23200}{}{Tvrzená energo zbroj}
{23201}{}{Energo zbroj model T-51b. Speciální chemickı proces vylepšil obranné schopnosti této hi-tech zbroje.}
{23300}{}{Turbo plazmová puška}
{23301}{}{Upravená plazmová puška Winchester P94. Aby se urychlil proces vytváøení plazmové støely, je komora s plazmou pøedehøívána. Min. SÍ: 6.}
{23400}{}{Boxer s ostny}
{23401}{}{Vylepšená verze klasického mosazného boxeru. Zpùsobuje vìtší poranìní, protoe proniká soupeøùm do masa pøi boji na blízko. Min. SÍ: 1.}
{23500}{}{Energo pìst}
{23501}{}{Energo pìst "Ranaø" od firmy BeatCo. Mnohımi povaována za vùbec nejúèinnìjší zbraò pro boj na blízko. Napájena malımi energetickımi èlánky. Min. SÍ: 1.}
{23600}{}{Bojovı nù}
{23601}{}{Vysoce kvalitní nù znaèky Stallona. Vırobek firmy SharpWit, Inc. Ostrost èepele je garantována po více jak deset let! Min. SÍ: 2.}
{23700}{}{Chemické urnály}
{23701}{}{Náhodnı vıbìr literatury zabıvající se chemií. Obzvláštì zajímavé jsou èlánky o molekulární chemii.}
{23800}{}{Vysílání Regulátorù}
{23801}{}{Holopáska s hlasovım záznamem.}
{23900}{}{Zbroj Bratrstva oceli}
{23901}{}{Vylepšenı model kevlarové zbroje. Oproti bìnì dostupné verzi ji Bratrstvo Oceli v mnohém vylepšilo.}
{24000}{}{Tesla zbroj}
{24001}{}{Tato záøící zbroj poskytuje dokonalou ochranu proti energetickım útokùm. Tøí Tesla cívky pohltí vysoké procento energetickıch vıbojù.}
{24100}{}{.223 pistole}
{24101}{}{Upravená puška ráe .223 s upilovanou hlavní. Jedineèná støelná zbraò vyrobená s láskou a zruèností. Min. SÍ: 5.}
{24200}{}{Opakovací brokovnice}
{24201}{}{Opakovací bullpup brokovnice Winchester ráe 12, model "Masovı vrah". Ve vıborném stavu. Je vybavena pøídavnım tìsnìním DesertWarfare pro zvıšení spolehlivosti. Min. SÍ: 5.}
{24300}{}{Nádoba}
{24301}{}{Kvalitnì vyrobená nádoba z hlíny.}
{24400}{}{Nádoba}
{24401}{}{Kvalitnì vyrobená nádoba z hlíny.}
{24500}{}{Truhla}
{24501}{}{Døevìná truhla.}
{24600}{}{Police}
{24601}{}{Døevìná police s rùznımi vìcmi.}
{24700}{}{Police}
{24701}{}{Døevìná police s rùznımi vìcmi.}
{24800}{}{Nádoba}
{24801}{}{Kvalitnì vyrobená nádoba z hlíny.}
{24900}{}{Nádoba}
{24901}{}{Kvalitnì vyrobená nádoba z hlíny.}
{25000}{}{Kosti}
{25001}{}{Hromada lidskıch kostí.}
{25100}{}{Anniny kosti}
{25101}{}{Tyto kosti vypadají, jako by touily spoèinout v klidu a pokoji.}
{25200}{}{Annin pøívìsek}
{25201}{}{Obnošenı pøívìsek ze zlata. Uvnitø je ukrytı nádhernı obrázek.}
{25300}{}{Kontroler pøívodu energie}
{25301}{}{Tento èip reguluje pøívod energie do elektromotoru auta. Mnoho øidièù tento èip rychle spálilo èastım a prudkım zrychlováním. I pøesto je to ale uiteèná souèástka... pokud máš ovšem auto, do kterého ji mùeš namontovat.}
{25400}{}{Regulátor pøívodu energie}
{25401}{}{Nìkteøí majitelé si tento regulátor namontovali, aby se jim zvıšil dojezd na dvojnásobek, ale vìtšinì øidièù bylo jedno, kolik jejich auto ralo. Vdy energie je levná a je ji dost, tak èeho se bát?}
{25500}{}{Denní propustka}
{25501}{}{Tento kousek pomaèkaného papíru ti umoòuje vstup do všech zón Vault City s vıjimkou samotného Vaultu. Platí pouze ve dne.}
{25600}{}{Falešné obèanství}
{25601}{}{Papíry pøedstavující falešné osvìdèení o Obèanství. Vypadají docela autenticky, ale nevìøíš, e by obstály pøi dùkladnìjší kontrole.}
{25700}{}{Corneliovy zlaté hodinky}
{25701}{}{Starobylá vìc známá jako kapesní hodinky. Èas se na tomto suvenıru zastavil ji pøed mnoha lety.}
{25800}{}{Hydroelektrickı regul.}
{25801}{}{Hydroelektrickı regulátor magnetosféry.}
{25900}{}{Jet}
{25901}{}{Velmi úèinnı metamfetamin, kterı stimuluje centrální nervovı systém. Poèáteèní euforie odezní ji po nìkolika minutách, ale bìhem této doby je konzument naplnìn pøívalem síly a energie.}
{26000}{}{Protilátka na Jet}
{26001}{}{This antidote cures the Jet addiction.}
{26100}{}{Jonnyho vzduchovka}
{26101}{}{Vzduchovka znaèky Red Ryder. Na pabì je vyškrábané jméno 'Jonny'. Min. SÍ: 3.}
{26200}{}{Gumové holínky}
{26201}{}{Pár starıch gumovıch bot. Vypadají dost odolnì na to, aby vydrely nìjaké to svinstvo. Alespoò na chvíli.}
{26300}{}{Dopis od Svìtloplachù}
{26301}{}{Zpráva od vùdce Svìtloplachù pro obyvatele Modocu.}
{26400}{}{Smithova bezva vìcièka}
{26401}{}{DLOUHİ POPIS.}
{26500}{}{Bojová koená bunda}
{26501}{}{Tato silnì podšitá koená bunda je neobvyklá tím, e má dvì vrstvy. A u se v ní ale ukáeš kdekoliv, staneš se zaruèenì støedem pozornosti a budeš urèovat módní trendy pro pøíští podzimní sezónu.}
{26600}{}{Vicovo rádio}
{26601}{}{Toto kapesní rádio je nefunkèní, ale jinak vypadá docela zachovale. Moná by se z nìj daly nìkteré souèástky pouít i do jinıch pøijímaèù.}
{26700}{}{Vicova láhev na vodu}
{26701}{}{Tato relikvie Vaultu 13 byla pravdìpodobnì pouívána k uchovávání nìjakého posvátného symbolu. Na boku je vyraené svaté èíslo 13 jako drahocennı odkaz na minulost tvıch pøedkù a jejich nadìjnou budoucnost.}
{26800}{}{H&K CAWS}
{26801}{}{CAWS brokovnice je skvìlı nástroj pro boj na krátkou vzdálenost. Díky bullpup konstrukci je zbraò krátká, lehce ovladatelná a pøitom má stále dostateènì dlouhou hlaveò pro vysokorychlostní munici. Min. SÍ: 6.}
{26900}{}{Èásti robota}
{26901}{}{Hromada poškozenıch èástí robota.}
{27000}{}{Robo raketomet}
{27001}{}{Tuto raketu mùou pouívat pouze roboti vybavení raketometem.}
{27100}{}{Kvìtina Broc}
{27101}{}{Tato hojnì rostoucí kvìtina je základem pro vırobu léèivého prášku.}
{27200}{}{Koøen Xander}
{27201}{}{Vzácnı koøen, kterı dává léèivému prášku jeho léèivé vlastnosti.}
{27300}{}{Lecivy prasek}
{27301}{}{Velice mocná léèivá magie. Zpùsobuje ospalost.}
{27400}{}{Robo raketa}
{27401}{}{Tuto raketu mùou pouívat pouze roboti vybavení raketometem.}
{27500}{}{Trofej uznání}
{27501}{}{Masivní zlatá trofej s vìnováním: "Komu: Davovi, Od: DC, Za: e je neobyèejnı èlovìk."}
{27600}{}{Kùe z geckona}
{27601}{}{Suchá a zakonzervovaná kùe geckona.}
{27700}{}{Kùe ze zlatého geckona}
{27701}{}{Suchá a zakonzervovaná kùe zlatého geckona.}
{27800}{}{Pazourek}
{27801}{}{Kámen pouívanı k nabroušení kopí.}
{27900}{}{Nervové rozhraní}
{27901}{}{Vypadá to jako nìkolik elektrod zabudovanıch do jakési helmy, která je pøipojena ke standardnímu poèítaèovému rozhraní. Bohuel je rozbitá.}
{28000}{}{Naostøené kopí}
{28001}{}{Tyè s hrotem na konci. Násada je døevìná a hrot je z naostøené oceli. Min. SÍ: 4.}
{28100}{}{Dixonovo oko}
{28101}{}{Malá nádobka obsahující lidské oko plovoucí v nìjakém roztoku. Na štítku stojí: plukovník Dixon.}
{28200}{}{Cliftonovo oko}
{28201}{}{Malá nádobka obsahující lidské oko plovoucí v nìjakém roztoku. Na štítku stojí: generál Clifton.}
{28300}{}{Tomík}
{28301}{}{Samopal Thompson M1928 alias "Tomík" je zlovìstnì vyhlíející zbraò. Kdykoliv ho dríš v ruce, máš nutkání si nasadit plstìnı klobouk a køupnout klouby. "Tomík" je dobøe krmen velikım 50ti-rannım zásobníkem. Min. SÍ: 6.}
{28400}{}{Sušené maso}
{28401}{}{Tyto vysušené a vyuzené kusy zvíøecího masa zùstávají poivatelné a vıivné i po nìkolik let a let a let...}
{28500}{}{Klepeta}
{28501}{}{Tyto radškorpioní klepeta jsou vydlabané a mají na konci popruh s rozbitou pøezkou.}
{28600}{}{Døevo na podpal}
{28601}{}{Nìkolik svázanıch polen a tøísek.}
{28700}{}{Lovecká puška s optikou}
{28701}{}{Není nic lepšího, ne sledovat pøekvapenı vıraz svého cíle v okamiku, kdy ho zasáhne kulka. Optickı zamìøovaè s 20ti-násobnım zvìtšením ti to umoní. Pøesná od prvního do posledního vıstøelu, bez ohledu na velikost cíle. Min. SÍ: 5.}
{28800}{}{Energ. èlánky do auta}
{28801}{}{Energetické èlánky do auta.}
{28900}{}{Lopata}
{28901}{}{Lopata urèená ke kopání jam a jinıch vìcí.}
{29000}{}{Robo elektroobušek 1}
{29001}{}{Zbraò robotù typu "Oèko". Zpùsobuje elektrické poškození.}
{29100}{}{Robo elektroobušek 2}
{29101}{}{Zbraò robotù typu "Oèko". Zpùsobuje elektrické poškození.}
{29200}{}{Boxerské rukavice}
{29201}{}{Pár boxerskıch rukavic, které slabì páchnou potem. Urèitì u zaily hodnì zápasù. Zùstala na nich spousta krvavıch skvrn.}
{29300}{}{Plátované rukavice}
{29301}{}{Nìkdo "omylem" vloil nìkolik kovovıch plátù do tìchto boxerskıch rukavic. Technicky vzato by to mohlo bıt povaováno za podvod, ale ty v tom vidíš pøíleitost jak zpøelámat pár kostí.}
{29400}{}{Holodisk Vault 13}
{29401}{}{Holodisk, kterı údajnì obsahuje lokaci Vaultu 13.}
{29500}{}{Sırové køupky}
{29501}{}{Krabice køupek se sırovou pøíchutí. Jsou velmi dobré.}
{29600}{}{HK P90c}
{29601}{}{Samopal HK P90c byl do vızbroje zaøazen a bìhem války. Bullpup konstrukce a kompaktní design jej èiní snadno ovladatelnım. P90c byl vdy cenìn pøedevším pro svoji odolnost, spolehlivost a vysokou palebnou sílu v kompaktním balení. Min. SÍ: 4.}
{29700}{}{Kovová tyè}
{29701}{}{Dlouhá kovová tyè. Èekáš snad nìco jiného?}
{29800}{}{Klíè od Lovecké ètvrti}
{29801}{}{Obyèejnı klíè.}
{29900}{}{Trubková puška}
{29901}{}{Ruènì vyrobená jednoranná puška. Min. SÍ: 5.}
{30000}{}{Zipka}
{30001}{}{Ruènì vyrobená jednoranná pistole. Min. SÍ: 4.}
{30100}{}{Zápisník}
{30101}{}{Zápisník se zprávou o chlazení.}
{30200}{}{Gecko Holodisk}
{30201}{}{Na štítku tohoto holodisku stojí: "Ekonomická data Gecka." Je obtíné vyhodnotit všechny ty technické grafy, tabulky a statistické vzorce, ale vìtšina informací vyzdvihuje vıhody vzájemné spolupráce Vault City a Gecka.}
{30300}{}{Holodisk reaktoru}
{30301}{}{Na štítku tohoto holodisku stojí: "Vıkonnostní data Gecko reaktoru." Tento holodisk obsahuje øadu èísel, která ti nic neøíkají. Urèitì je tu ale spousta informací, které musí bıt pro nìkoho dùleité.}
{30400}{}{Balíèek karet "Tragic"}
{30401}{}{Sada karet z nìjaké sbìratelské hry. Vypadá to jako pìknì drahı koníèek, pokud to èlovìka chytne.}
{30500}{}{lutá pøístupová karta - reaktor}
{30501}{}{Elektronickı bezpeènostní klíè oznaèenı lutou barvou.}
{30600}{}{Èervená pøístupová karta - reaktor}
{30601}{}{Bezpeènostní elektronickı klíè oznaèenı èervenou barvou.}
{30700}{}{Plazma transformer}
{30701}{}{Tøícestnı plazma transformer.}
{30800}{}{Super náøadí}
{30801}{}{Úasná souprava náøadí vyrobená firmou "Ulomit".}
{30900}{}{Talisman}
{30901}{}{Talisman, kterı nosí stoupenci Braina.}
{31000}{}{Gamma Gulp pivo}
{31001}{}{Láhev Gamma Gulp piva. Svítí ve tmì!}
{31100}{}{Roentgen Rum}
{31101}{}{Láhev roentgen rumu. Svítí ve tmì!}
{31200}{}{ádanka}
{31201}{}{ádanka pro souèástku.}
{31300}{}{Revolver Magnum .44}
{31301}{}{Tohle je Magnum 44, nejlepší pistole na svìtì, která ti dokáe urazit hlavu. Tak se radši sám sebe zeptej: Je dneska mùj šastnej den? Tak co, je tvùj šastnej den, hajzle? Min. SÍ: 5.}
{31400}{}{Kondom (Modré balení)}
{31401}{}{Kondom znaèky Jimmy Hats, co je velmi spolehlivá znaèka. Je opatøen vroubkováním pro intenzivnìjší proitek.}
{31500}{}{Kondom (Zelené balení)}
{31501}{}{Kondom znaèky Jimmy Hats, co je velmi spolehlivá znaèka. Obsahuje fosforeskující zelené barvivo èíslo 2 a je pokrytı spermicidním lubrikantem pro zvıšení ochrany.}
{31600}{}{Kondom (Èervené balení)}
{31601}{}{Kondom znaèky Jimmy Hats, co je velmi spolehlivá znaèka. Obsahuje fosforeskující èervené barvivo èíslo 5 a má skoøicovou pøíchu... øíká se.}
{31700}{}{Pudøenka}
{31701}{}{Pravı kosmetickı kuføík znaèky Mary May.}
{31800}{}{Prázdná støíkaèka}
{31801}{}{Prázdná injekèní støíkaèka.}
{31900}{}{Vystøelovací nù}
{31901}{}{Malı nù s ostøím, které drí pruina. Kdy se zmáèkne tlaèítko na boku, èepel vystøelí za zvuku uspokojujícího "svissst". Min. SÍ: 1.}
{32000}{}{Naostøená tyè}
{32001}{}{Døevìná tyè s naostøenım koncem. Min. SÍ: 4.}
{32100}{}{Kybernetickı mozek.}
{32101}{}{Lidskı mozek vylepšenı o elektronické a robotické èásti.}
{32200}{}{Lidskı mozek.}
{32201}{}{Typickı lidskı mozek. Vìtšinou k nalezení v lidské lebce. Blééh.}
{32300}{}{Šimpanzí mozek.}
{32301}{}{Opièí mozek. Je mìkkı a houbovitı.}
{32400}{}{Abnormální mozek.}
{32401}{}{Zcela pravdìpodobnì lidskı mozek. Má však divnou barvu a levá hemisféra je propadlá.}
{32500}{}{Kostky}
{32501}{}{Pár obyèejnıch hracích kostek. Dala by se z nich udìlat hezká ozdoba pøedního skla ve tvém autì.}
{32600}{}{Falešné kostky}
{32601}{}{Pár cinknutıch hracích kostek. Bıt tebou, tak se s nimi v ádném kasínu neukazuju.}
{32700}{}{Velikonoèní vejce}
{32701}{}{Natvrdo uvaøené vejce pomalované pestrımi barvami.}
{32800}{}{Magická koule}
{32801}{}{Tato èerná koule je nìjakı druh vìšteckého pøístroje... zdá se, e to malé okénko na vrchu dokáe pøedvídat budoucnost! Pøedváleèné lidstvo muselo bıt geniální, kdy dokázalo vytvoøit takovı zázrak!}
{32900}{}{Mutagenní sérum}
{32901}{}{Podivná organická smìs, která moná dokáe zvrátit mutagenní procesy lidského organismu.}
{33000}{}{Zøícenı vertibird}
{33001}{}{Vrak vertibirdu. Zdá se, e tu leí u celé mìsíce.}
{33100}{}{"Koèièí Packa" èíslo 5}
{33101}{}{Vzácné èíslo 5 magazínu "Koèièí Packa". Kromì obrázkù také obsahuje úasnı èlánek o energetickıch zbraních.}
{33200}{}{M3A1 "Vymazávaè" SMG}
{33201}{}{Poté, co armáda pøezbrojila na novìjší druhy zbraní, dostal se tento samopal do arzenálu Národní Gardy. Avšak "Vymazávaè" je natolik jednoduchá a levná zbraò, e se stále hojnì pouívá. Min. SÍ: 4.}
{33300}{}{Pilulky na srdce}
{33301}{}{Tyto pilulky uívají lidé se srdeèními problémy.}
{33400}{}{Jed}
{33401}{}{Injekèní støíkaèka naplnìná prudkım jedem.}
{33500}{}{Mooreùv kuføík}
{33501}{}{Thomas Moore tì poádal o doruèení tohoto kuføíku z brahmínní kùe rodinì Bishopovıch do New Rena. Je uzamèen bezpeènostním zámkem, kterı nedokáeš otevøít.}
{33600}{}{Mooreùv kuføík}
{33601}{}{Thomas Moore tì poádal o doruèení tohoto kuføíku z brahmínní kùe rodinì Bishopovıch do New Rena. Je uzamèen bezpeènostním zámkem, kterı nedokáeš otevøít.}
{33700}{}{Holodisk od Lynette}
{33701}{}{Toto je holodisk, kterı ti dala Lynette.}
{33800}{}{Westinùv holodisk}
{33801}{}{Toto je holodisk, kterı ti dal Westin.}
{33900}{}{Špionání holodisk NCR}
{33901}{}{Holodisk obsahující záznamy o èasovıch rozpisech karavan NCR a dalších bezpeènostních informací. Je adresován Darionovi a podepsán jako "F". Díky tìmto informacím je zcela jasné, jak se nájezdníci tak snadno vyhnuli zajmutí.}
{34000}{}{Doktorovy dokumenty}
{34001}{}{Svazek velice detailních plánù kybernetické psí robojednotky. S tìmito plány a se správnım vybavením by si èlovìk mohl sestrojit svého vlastního robopsa.}
{34100}{}{Prezidentská propustka}
{34101}{}{Nositel této propustky má bezpeènostní provìøení tøídy A-1 autorizované prezidentem New California Republic. Je podepsána prezidentkou Tandi.}
{34200}{}{Odznak Rangera}
{34201}{}{Tento odznak potvrzuje, e jsi oficiálním èlenem organizace New California Rangers. Podívej, má to hvìzdu, kruh a vùbec všechno, co má správnı odznak mít!}
{34300}{}{Mapa Rangerù}
{34301}{}{Mapa okolní krajiny. Pro tebe nijak zvláš uiteèná, ale jsou zde zakresleny pozice a kódové oznaèení základen Rangerù na severu zemì.}
{34400}{}{Hrob}
{34500}{}{Hrob}
{34600}{}{Hrob}
{34700}{}{Hrob}
{34701}{}{}
{34800}{}{Zdok. energo zbroj}
{34801}{}{Tato energo zbroj je tvoøena lehkımi kovovımi slitinami a vyztuena keramickımi vlokami na klíèovıch místech. Navíc je vybavena vysoce kvalitním modelem pomocnıch pohybovıch servomotorù.}
{34900}{}{Zdok. energo zbroj MKII}
{34901}{}{Tato energo zbroj je tvoøena pouze lehkımi keramickımi kompozity namísto obvyklé kombinace kovu a keramickıch plátù. Zdá se bıt ještì odolnìjší ne standardní verze zdokonalené energo zbroje.}
{35000}{}{Bozar}
{35001}{}{Vrcholnı produkt odstøelovaèského umìní. Je nutné ho udrovat v dokonalé èistotì, jinak je náchylnı k zasekávání. Nicménì pøesnost této veliké zbranì bohatì vynahradí její zvıšené poadavky na údrbu. Min. SÍ: 6.}
{35100}{}{FN FAL}
{35101}{}{Tato puška byla uívána ozbrojenımi silami více ne kterákoliv jiná puška v historii. Je to spolehlivá útoèná zbraò do jakéhokoliv terénu nebo bojové situace. Min. SÍ: 5.}
{35200}{}{H&K G11}
{35201}{}{Tato zbraò je revolucí v historii útoènıch zbraní. Pouívá beznábojnicové støelivo tvoøené blokem slisované spalitelné smìsi se zabudovanım projektilem. Vısledná váha i úspora místa umonila instalaci velkokapacitního zásobníku munice. Min. SÍ: 5.}
{35300}{}{XL70E3}
{35301}{}{Experimentální zbraò vyvinutá bìhem války. Pøevánì vyrobena z vysoce odolnıch polymerù, díky èemu je témìø neznièitelná. Je lehká, pøesná, má vysokou kadenci støelby a lze ji rozebrat bez pouití jakıchkoliv nástrojù. Min. SÍ: 5.}
{35400}{}{Pancor Jackhammer}
{35401}{}{Jackhammer je navzdory svému jménu snadno ovladatelná brokovnice. Oblíbená bullpup konstrukce, kdy je zásobník umístìnı a za spouští, z ní dìlá skvìle vyváenou a snadno ovladatelnou zbraò. Min. SÍ: 5.}
{35500}{}{Lehkı kulomet}
{35501}{}{Tento pìchotní kulomet je bullpup konstrukce, díky èemu je vlee na zemi obtínì ovladatelnı. Z tohoto dùvodu byl pøeøazen do vızbroje jednotek Národní Gardy. Nicménì si dokázal získat povìst spolehlivé a vzhledem ke své velikosti i velmi úèinné zbranì. Min. SÍ: 6.}
{35600}{}{Hlasovı modul}
{35601}{}{Plošnı spoj s nìkolika neznámımi souèástkami, mikrofonem a nápisem: "Vault-Tec ovládací hlasovı modul."}
{35700}{}{Kalibr .45}
{35701}{}{Munice. Kalibr. 45}
{35800}{}{2mm EC}
{35801}{}{Munice.}
{35900}{}{4.7mm beznáb}
{35901}{}{Munice. Kalibr: 4.7mm, beznábojnicová.}
{36000}{}{9mm}
{36001}{}{Munice. Kalibr: 9mm.}
{36100}{}{HN jehlová munice}
{36101}{}{Munice. Tento zásobník obsahuje jehlové náboje pro HN jehlovou pistoli. Kadı "projektil" tvoøí malá injekèní støíkaèka zkonstruovaná tak, aby pøi nárazu vstøíkla do cíle svùj obsah.}
{36200}{}{HN AP jehlová munice}
{36201}{}{Munice. Tento zásobník obsahuje prùrazné náboje pro HN jehlovou pistoli. Hroty jehel jsou vyrobeny z neznámé kovové slitiny a jsou neuvìøitelnì ostré.}
{36300}{}{7.62mm}
{36301}{}{Munice. Kalibr: 7.62mm.}
{36400}{}{Motivátor robota}
{36401}{}{Hlavní øídící mechanismus robota.}
{36500}{}{Trn}
{36501}{}{Semeno ve tvaru trnu, které masoravé rostliny vystøelují po své potenciální potravì nebo nositelích semen.}
{36600}{}{G.E.C.K.}
{36601}{}{"Souprava k vytvoøení rajské zahrady". Tento pøístroj je souèástí standardního vybavení vaultù firmy Vault-Tec. GECK je prostøedek k vybudování civilizace po jaderné válce. Staèí pøidat vodu a zamíchat.}
{36700}{}{Bedna s municí}
{36800}{}{Bedna s municí}
{36900}{}{Bedna s municí}
{37000}{}{Bedna s municí}
{37100}{}{Paøát}
{37101}{}{Paøát}
{37200}{}{Paøát}
{37201}{}{Paøát}
{37300}{}{Klíè k Vaultu 15}
{37301}{}{Bezpeènostní elektronickı klíè oznaèenı èervenou barvou.}
{37400}{}{Hrob}
{37500}{}{Hrob}
{37600}{}{Hrob}
{37700}{}{Souèástky poèítaèe}
{37701}{}{Nejrùznìjší souèástky poèítaèe s rùznımi funkcemi. Sen kadého poèítaèového nadšence.}
{37800}{}{Sušenka}
{37801}{}{Èokoládová sušenka. Mòam!}
{37900}{}{Koená zbroj Mark II}
{37901}{}{Zdokonalená verze základní koené zbroje s extra vrstvami. Peèlivì vyrobena z vydìlané brahmínní kùe.}
{38000}{}{Kovová zbroj Mark II}
{38001}{}{Vyleštìné kovové pláty peèlivì pospojované do zbroje.}
{38100}{}{Kevlarová zbroj Mark II}
{38101}{}{Hi-tech zbroj vyrobená z pokroèilıch defenzívních polymerù.}
{38200}{}{Náplò do plamen. MKII}
{38201}{}{Náplò do plamenometu obsahující extra hoølavou smìs.}
{38300}{}{Šídlo}
{38301}{}{Tento podomácku vyrobenı nù je nebezpeènı pøedevším tím, e ho lze snadno ukrıt. Jeho pøítomnost nedokáe nikdo odhalit. Min. SÍ: 1.}
{38400}{}{Montání klíè}
{38401}{}{Bìnı montání klíè pouívanı montéry. Min. SÍ: 3.}
{38500}{}{Upilovaná brokovnice}
{38501}{}{Nìkdo si dal tu námahu a uøízl nìkolik centimetrù z hlavnì a paby této brokovnice. Tím se z ní stalo malé pøíruèní dìlo se širokım rozptylem, obzvláštì úèinné v boji na krátkou vzdálenost a proti více protivníkùm. Min. SÍ: 4.}
{38600}{}{Louisvillskı odpalovaè}
{38601}{}{Tato baseballová pálka z tvrdého døeva americké vıroby si hravì poradí s èímkoliv. Min. SÍ: 4.}
{38700}{}{M60}
{38701}{}{Tento relativnì lehkı kulomet byl cenìn armádami po celém svìtì pro svou vysokou kadenci. Tato spolehlivá a bitvami provìøená zbraò se pouívala na korbách vozidel a jako palebná podpora pìchoty. Min. SÍ: 7.}
{38800}{}{Jehlová pistole}
{38801}{}{Máš podezøení, e se tato jehlová pistole znaèky Bringham kdysi pouívala k vìdeckım úèelùm. Jako støelivo slouí malé injekèní støíkaèky z tvrdého plastu. Min. SÍ: 3.}
{38900}{}{Gatling Avenger}
{38901}{}{Firma Rockwell vytvoøila Avenger jako náhradu za zastaralı model osobního gatlingu CZ53. Model "Avenger" zahrnuje konstrukèní vylepšení jako je úèinnìjší chlazení a pochromování hlavní. To vše umoòuje vyšší dostøel a vìtší smrtonosnost. Min. SÍ: 7.}
{39000}{}{Solární spalovaè}
{39001}{}{Bez sluneèních paprskù, kterı dobíjí kondenzátory této zbranì, nedokáe tato zbraò zapálit ani sirku. Ale na pøímém sluneèním svìtle vyvinou experimentální fotoelektrické èlánky tolik energie, e snadno promìní cokoliv ivého v køupavou peèínku. Min. SÍ: 3.}
{39100}{}{H&K G11E}
{39101}{}{Tato zbraò je revolucí v pìchotních zbraních. Pouívá beznábojnicové støelivo tvoøené blokem slisované spalitelné smìsi se zabudovanım projektilem. Vısledná úspora místa umonila instalaci velkokapacitního zásobníku munice. Min. SÍ: 6}
{39200}{}{M72 Gaussova puška}
{39201}{}{Puška M72 byla zkonstruována v Nìmecku. Pouívá elektromagnetické pole, které vystøelí náboj ohromnou rychlostí... a pronikne témìø jakoukoliv pøekákou. Její dostøel, pøesnost a úèinnost nemají srovnání s ádnou jinou zbraní. Min. SÍ: 6.}
{39300}{}{Fázer}
{39301}{}{Tato záhadná hi-tech zbraò má v sobì nìjakı energetickı generátor. Pokud by nebyl poškozenı, byla by to ultimátní zbraò proti jakémukoliv nepøíteli. Záloní energetickı modul se skládá z malıch energetickıch èlánkù. Min. SÍ: 3.}
{39400}{}{PPK12 Gaussova pistole}
{39401}{}{PPK12 Gaussova pistole nìmecké konstrukce je uznávána pro svùj dostøel a úèinnost. Pouívá elektromagnetické pole, které dokáe vystøelit náboj ohromnou rychlostí a prorazit témìø jakoukoliv zbroj. Min. SÍ: 4.}
{39500}{}{Gatling Vindicator}
{39501}{}{Tento rotaèní kulomet je vırobkem nìmecké firmy Rheinmetal AG. Vindicator dokáe ze svıch šesti hlavní vychrlit více ne 90 000 projektilù za minutu. Tento vrchol inenırského umìní Teutonù je povaován za ultimátní osobní zbraò. Min. SÍ: 7.}
{39600}{}{YK32 pulzní pistole}
{39601}{}{YK32 je elektrická pulzní zbraò vyrobená energetickım konsorciem Yuma Flats. Aèkoliv je velmi úèinná, nikdy nebyla povaována za praktickou zbraò kvùli pøíliš rozmìrné konstrukci a vysoké spotøebì energie. Min. SÍ: 3.}
{39700}{}{YK42B pulzní puška}
{39701}{}{YK42B je elektrická pulzní zbraò vyrobená energetickım konsorciem Yuma Flats. Tato zbraò je povaována za mnohem kvalitnìjší model ne YK32 pistole díky vìtšímu dostøelu a vyšší kapacitì zásobníku. Min. SÍ: 3.}
{39800}{}{.44 Magnum (Nabíjeè)}
{39801}{}{Revolver .44 Magnum se zrychlenım nabíjeèem. Min. SÍ: 5.}
{39900}{}{Elektrickı obušek Super}
{39901}{}{Elektrickı obušek model "Farmáøùv nejlepší pøítel" od Wattz Electronics. Tento model má zvıšenou sílu elektrického vıboje. Min. SÍ: 4.}
{40000}{}{Vylepšenı plamenomet}
{40001}{}{Upravená varianta plamenometu Flambe 450. Chrlí krátké dávky extrémnì hoølavé tekutiny. Vyaduje speciální náplò. Tento model byl upraven pro pouití hoølavìjší smìsi, která zpùsobuje vyšší vznìtlivost. Min. SÍ: 6.}
{40100}{}{Las. puška (Roz. zás.)}
{40101}{}{U této laserové pušky Wattz 2000 byl vylepšen dobíjecí systém instalací speciálního èipu, kterı zvyšuje efektivitu vyuití energie z mikrofúzního èlánku o 50%. Min. SÍ: 6.}
{40200}{}{Magneto-las. pistole}
{40201}{}{Tato laserová pistole Wattz 1000 byla vylepšena instalací zamìøovacího systému s elektromagnetickım polem, které zpøesòuje vyzaøování laseru, èím zvyšuje penetraèní sílu. Min. SÍ: 3.}
{40300}{}{FN FAL (Infrahled)}
{40301}{}{Tato puška byla uívána ozbrojenımi silami více ne kterákoliv jiná puška v historii. Je to spolehlivá útoèná zbraò do jakéhokoliv terénu nebo bojové situace. Tento model je vybaven infrahledem pro zvıšení pøesnosti pøi støelbì v noci. Min. SÍ: 5.}
{40400}{}{Desert Eagle (Roz. zás.)}
{40401}{}{Starobylá pistole Desert Eagle pouívající munici .44 magnum. Èasté pouívání ve filmech pozdního 20. století z ní udìlalo jednu z nejpopulárnìjších pistolí všech dob. Tato je vybavena rozšíøenım zásobníkem pro vìtší zábavu! Min. SÍ: 4.}
{40500}{}{Útoèná puška (Roz. zás.)}
{40501}{}{Tato útoèná puška má rozšíøenı zásobník. Kropit nepøátele nikdy nebyla taková zábava jako s touto zbraní. Min. SÍ: 5.}
{40600}{}{Plazm. pistole (Roz. zás.)}
{40601}{}{U této plazmové pistole Glock 86 bylo provedeno pøenastavení magnetické komory s cílem sníit spotøebu energie. Díky tomu se zdvojnásobila efektivita a sníila spotøeba baterií, tudí je moné vypálit více ran. Min. SÍ: 4.}
{40700}{}{Mega energo pìst}
{40701}{}{Energo pìst "Ranaø" od firmy BeatCo. Mnohımi povaována za vùbec nejúèinnìjší zbraò pro boj na blízko. Tento model má vylepšené servomechanismy pro zvıšení síly úderu. Je napájena malımi energetickımi èlánky. Min. SÍ: 1.}
{40800}{}{Souprava první pomoci}
{40801}{}{Malá souprava obsahující základní lékaøské vybavení. Obinadla, náplasti, dezinfekèní prostøedky apod.}
{40900}{}{Záchranáøská brašna}
{40901}{}{This bag contains instruments and drugs used by paramedics in the field. The tools contained are specifically designed for high trauma and emergency cases.}
{41000}{}{Rozšíøená sada paklíèù}
{41001}{}{Sada zámeènickıch nástrojù. Obsahuje paklíèe a šperháky potøebné k otevøení všech klasickıch i dozickıch zámkù. Tato sada navíc obsahuje speciální náøadí pro zdolání sloitìjších mechanickıch zámkù.}
{41100}{}{Elektronickı paklíè MKII}
{41101}{}{Toto je druhá generace mikromanipulaèního elektronického paklíèe od firmy Wattz Electronics. Pro odblokování elektronickıch zámkù a bezpeènostních systémù. Verze Mark II obsahuje updatovanı software a nástroje rozhraní.}
{41200}{}{Plechovka oleje}
{41201}{}{Vidíš plechovku starodávného syntetického lubrikantu Armor-Go. Jedná se o speciální olej pro energo zbroje.}
{41300}{}{ID karta "Stájí"}
{41301}{}{Doèasná ID karta. Má na sobì èervenı prouek, kterı z tebe dìlá "Vızkumníka Stájí."}
{41400}{}{Klíè od chatrèe u Vaultu 15}
{41401}{}{Obyèejnı klíè.}
{41500}{}{Brıle}
{41501}{}{Dioptrické brıle pro krátkozraké.}
{41600}{}{Prázdná nádobka Jetu}
{41601}{}{Tato prázdná nádobka Jetu se nacházela v pokoji Richarda Wrighta. Uvnitø jsou stále stopy po Jetu.}
{41700}{}{Kyslíková bomba}
{41701}{}{Kyslíková bomba pro dıchací pøístroj pana Salvatora.}
{41800}{}{Bomba s jedov. plynem}
{41801}{}{Tato tlaková nádoba vypadá na první pohled jako kyslíková bomba, ale na jejím spodku je vyrytá malá lebka se zkøíenımi hnátami. Kdyby sis to tak pozornì neprohlédl, ani by sis toho symbolu nevšiml.}
{41900}{}{Dùlní souèástky}
{41901}{}{Vidíš hromadu souèástek s nápisem "Èistiè vzduchu GX-9". Pouitím svıch úasnıch deduktivních schopností usuzuješ, e se pravdìpodobnì jedná o souèástky pro porouchanou èistièku vzduchu.}
{42000}{}{Platidlo Morningstaru}
{42001}{}{Toto je malá plastiková mince, kterou se pravdìpodobnì vyplácí mzda horníkùm z dolu Morningstar.}
{42100}{}{Svatı Ruèní Granát}
{42101}{}{Posvátná relikvie boské moci.}
{42200}{}{Èip pro rypadlo}
{42201}{}{Tento øídící èip je pro nìjakı druh velikého prùmyslového stroje. Zdá se, e i pod tím nánosem prachu a špíny je v pøekvapivì dobrém stavu.}
{42300}{}{Zlatı nugget}
{42301}{}{Valoun zlata.}
{42400}{}{Úlomek monumentu}
{42401}{}{Toto je úlomek podivného kamenného monumentu, kterı jsi našel v poušti. Aèkoliv by to vìtšina obyvatel tvé vesnice povaovala za svatou relikvii, ty máš z nìjakého dùvodu podezøení, e tì nìkdo napálil.}
{42500}{}{Kamenná hlava}
{42501}{}{Obrovskı kamennı monument.}
{42600}{}{Uranová ruda}
{42601}{}{Úlomek surové uranové rudy.}
{42700}{}{Ohnivı dech}
{42800}{}{Lékaøské zásoby}
{42801}{}{Krabice nejrùznìjších lékaøskıch pomùcek. Nic z toho nedokáeš pouít.}
{42900}{}{Zlatı zub}
{42901}{}{Tento zlatı zub kdysi nìkomu patøil, ale u ho nebude potøebovat.}
{43000}{}{Náboj do houfnice}
{43001}{}{Dìlostøeleckı náboj ráe 75mm. Nábojnice je znaènì zkorodovaná, ale pøesto na ní lze rozeznat nápis. SPOTØEBOVAT DO: 9-25-98.}
{43100}{}{Balík - zavøenı}
{43101}{}{Tento balík ti dal Velkı Jeíš Mordino. Máš ho doruèit Ramirezovi do Stájí.}
{43200}{}{Balík - otevøenı}
{43201}{}{Tento balík ti dal Velkı Jeíš Mordino. Máš ho doruèit Ramirezovi do Stájí. Je otevøenı a vyndal jsi z nìj všechen Jet, kterı tam byl.}
{43300}{}{Sluneèní brıle}
{43301}{}{Toto jsou drsnì vypadající sluneèní brıle. Staèí jen, e je máš v inventáøi a hned se cítíš drsnì.}
{43400}{}{Vozík}
{43401}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{43500}{}{Vozík}
{43501}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{43600}{}{Sada karet}
{43601}{}{Balíèek hracích karet.}
{43700}{}{Sada cinknutıch karet}
{43701}{}{Všechny karty v tomto balíèku jsou srdcové královny. To musí bıt nuda s nimi hrát.}
{43800}{}{Klíè od Chrámu}
{43801}{}{Klíè od Chrámu v Arroyo.}
{43900}{}{Chuchvalec}
{43901}{}{Nìjaké chmıøí z kapsy.}
{44000}{}{Biomed gel}
{44001}{}{Sklenice Biomed gelu, kterı se pouívá v biologickıch laboratoøích.}
{44100}{}{Blondieho známky}
{44101}{}{Jméno pùvodního vlastníka bylo z plíšku vybroušeno a na jeho místo nìkdo vyškrábal "Blondie". Pod tímto jménem je èíslo "11".}
{44200}{}{Andìlovy známky}
{44201}{}{Tyto vojenské známky patøí nìkomu jménem "Andìlské oèi". Pod tím je èíslo "16".}
{44300}{}{Tucovy známky}
{44301}{}{Tyto odpornì páchnoucí vojenské známky patøí nìkomu jménem "Tuco Benedicto Pacifico Juan Maria Ramirez" a za tím je èíslo "27".}
{44400}{}{Mapa nájezdníkù}
{44401}{}{Pomaèkaná mapa pøedváleèné severní Kalifornie. Je na ní èervenì zakresleno New Reno a trasy okolních karavan. Daleko na vıchod od New Rena je veliké èervené "X" a pod ním naèmáráno "Nájezdníci".}
{44500}{}{Šerifská hvìzda}
{44501}{}{Odznak šerifa mìsta.}
{44600}{}{Plány vertibirdu}
{44601}{}{Konstrukèní plánù vertibirdu.}
{44700}{}{Bishopùv holodisk}
{44701}{}{Tento holodisk obsahuje dùkazní informace o Bishopovì tajné dohodì s NCR. Bishop zøejmì najal oldáky, aby zaútoèili na Vault City. Doufal, e tím donutí Vault City, aby poádalo NCR o vojenskou pomoc. Holodisk neobsahuje ádná textová data, pouze zvuk. Vault City by nìco takového mohlo zajímat.}
{44800}{}{Úèetní kniha}
{44801}{}{V této úèetní knize je zaznamenána øada mìsíèních plateb skupinì oldákù od rodiny Bishopovıch. Vıše plateb závisí pøevánì na tom, jak moc dostanou oldáci Vault City pod "nátlak". Tato kniha by mohla Vault City zajímat.}
{44900}{}{Unused}
{44901}{}{Unused}
{45000}{}{Útrek papíru 1}
{45001}{}{Vidíš kousek popsaného papíru. Vypadá to jako èást nìjakého kódu, kterı je ale bohuel nekompletní. Pokud by se ti ale podaøilo najít všechny tøi kousky papíru... Takhle dokáeš rozluštit jen: 1. Fyzika: heslo KSLJ, 2. Chemie: heslo TIU, 3. Biologie: heslo INTL}
{45100}{}{Útrek papíru 2}
{45101}{}{Vidíš kousek popsaného papíru. Vypadá to jako èást nìjakého kódu, kterı je ale bohuel nekompletní. Pokud by se ti ale podaøilo najít všechny tøi kousky papíru... Takhle dokáeš rozluštit jen: KJ: Ken-Lee-9, ASPO- Lo-S, VR- Dnky-Pnch-}
{45200}{}{Útrek papíru 3}
{45201}{}{Vidíš kousek popsaného papíru. Vypadá to jako èást nìjakého kódu, kterı je ale bohuel nekompletní. Pokud by se ti ale podaøilo najít všechny tøi kousky papíru... Takhle dokáeš rozluštit jen: 7313, hi-S12908, 98790}
{45300}{}{Papír s heslem}
{45301}{}{Lístek sloenı ze tøí útrkù papíru ti odhalil tøi hesla. Na papírku teï stojí: 1. Fyzika: heslo KSLJKJ: Ken-Lee-97313, 2. Chemie: heslo TIUASPO- Lo-Shi-S12908, 3. Biologie: heslo INTLVR- Dnky-Pnch-98790}
{45400}{}{Rozbuška}
{45401}{}{Tento pøepínaè je koneènou èástí vıbušného zaøízení.}
{45500}{}{Kufr auta}
{45501}{}{Tento kufr je skvìlé místo pro uloení vìcí.}
{45600}{}{Klíè od cely}
{45601}{}{Tento klíè pasuje do dveøí cely v Broken Hills.}
{45700}{}{Hubologistova zpráva}
{45701}{}{Polní zpráva pro vedoucí pøedstavitele církve.}
{45800}{}{V.Z. Holodisk 5}
{45801}{}{Na štítku stojí: Zpráva pro hlavní stan - Dùvìrné.}
{45900}{}{V.Z. Holodisk 1}
{45901}{}{Na štítku stojí: Záznam radiokomunikace - kontrolní stanovištì 1.}
{46000}{}{V.Z. Holodisk 2}
{46001}{}{Na štítku stojí: Záznam radiokomunikace - kontrolní stanovištì 2.}
{46100}{}{V.Z. Holodisk 3}
{46101}{}{Na štítku stojí: Záznam radiokomunikace - kontrolní stanovištì 3.}
{46200}{}{V.Z. Holodisk 4}
{46201}{}{Na štítku stojí: Záznam radiokomunikace - vızkumnı tım.}
{46300}{}{Evakuaèní holodisk}
{46301}{}{Na štítku stojí: Pokyny k opuštìní základny.}
{46400}{}{Experimenty - holodisk}
{46401}{}{Na štítku stojí: Zpráva o vızkumu.}
{46500}{}{Medicína - holodisk}
{46501}{}{Na štítku stojí: Lékaøské záznamy.}
{46600}{}{Papír s heslem}
{46601}{}{Pøeloenı kus papíru a na nìm poznamenáno slovo "Èajkovskij".}
{46700}{}{Jesseho kontejner}
{46701}{}{}
{46800}{}{Smittyho jídlo}
{46801}{}{Nìjakı druh salátu a sendvièe vyrobeného z nìèeho, o èem si myslíš, e je brahmínní maso zalité tuènou lutou omáèkou. To vše obloeno podivnou nakládanou zeleninou.}
{46900}{}{Rot Gut}
{46901}{}{Velmi silnı likér nebo èistící prostøedek. Vyber si.}
{47000}{}{Roubík}
{47001}{}{Pochybná sexuální pomùcka. Radìji ani nechtìj vìdìt, k èemu se to pouívá.}
{47100}{}{"The Lavender Flower"}
{47101}{}{Nìjaká romantická novela napsaná Dorothy Rixonovou. Na obalu je ena leící na posteli obsypána stovkami kvìtin.}
{47200}{}{Hubologistickı Holodisk}
{47201}{}{This holodisk is labeled "Hubology: The Truth Behind the Lies". It looks like it works with your Pip-Boy.}
{47300}{}{Zmutovanı prst}
{47301}{}{Vidíš svùj šestı prst. Je to malá zmutovaná èást tvého já. Kdy se tak díváš na ten malı amputovanı prst, máš z nìjakého dùvodu pocit hrozné ztráty.}
{47400}{}{Petùnie}
{47401}{}{Kvìtináè rozkvetlıch petùnií. No øekni, nejsou nádherné?}
{47500}{}{Unused}
{47501}{}{Unused}
{47600}{}{Dopis pro "Osvíceného"}
{47601}{}{Zpráva adresovaná AHS-9 do San Francisca. Je opravdu nudná. Samé tabulky plné despotickıch regulací, vıdajù a dalších vástù, které ani nestojí za to èíst.}
{47700}{}{Holodisk rozhlasu}
{47701}{}{Na štítku stojí: "Zprávy stanice Galaxy News Network."}
{47800}{}{Holodisk mise Sierra}
{47801}{}{Na štítku stojí: "Zpráva o misi."}
{47900}{}{Souèástky NavCom}
{47901}{}{These are computer parts that look like they slot into the interior of a machine. The fact that they say "Poseidon Oil" and "Navigation Computer" on them lead you to believe they fit into a Poseidon Oil Navigation Computer.}
{48000}{}{Bonus +1 Hbitost}
{48100}{}{Bonus +1 Inteligence}
{48200}{}{Bonus +1 Síla}
{48300}{}{Fallout 2 - tipy a triky}
{48301}{}{TOHLE by se hodilo na zaèátku tıhle zatracenı hry.}
{48400}{}{Tvoje ucho}
{48401}{}{Toto je tvé ucho. dímaèka ti ho bìhem boje ukousl a vyplivl ho na tvé bezvládnì leící tìlo. Pokud èteš tyto øádky, znamená to, e si asi brzy naèteš uloenou pozici. Ale je samozøejmì docela moné, e je tato vìc k nìèemu urèená.}
{48500}{}{dímaèkovo ucho}
{48501}{}{Toto je dímaèkovo ucho. Ukousl jsi mu ho hned poté, co jsi do nìj bušil smyslù zbavenı. Srdeènì ti k jeho poráce gratulujeme. Je to jedna z nejtvrdších postav v této høe, obzvláš proto, e pøi boji s ním nemùeš pouít ádné zbranì ani zbroj.}
{48600}{}{Rafinovaná uranová ruda}
{48601}{}{Úlomek uranové rudy. Tato však prošla nìjakım druhem rafinaèního procesu. Zdá se tìší bıt ne pøedtím.}
{48700}{}{Dopis od Francise}
{48701}{}{"Zaiusi, Marcus poøád nic neudìlal s tím rasistou Jacobem a jeho spiklencema. Nejdøív vyøadili èistièku vzduchu... co bude dál? Našel jsem tunely, kde se tajnì schází. Myslím, e jedno nebo dvì tìla by mohlo Marcuse koneènì pøesvìdèit. Jestli do toho jdeš, dej mi vìdìt. A tentokrát u ten blbej dopis zniè!" -Francis.}
{48800}{}{Motivátor K-9}
{48801}{}{Toto je pohybovı mechanismus pro robota série K-9.}
{48900}{}{Speciální boxerská zbraò}
{49000}{}{Holodisk s historií NCR}
{49001}{}{Na štítku stojí: "Dìjiny NCR."}
{49100}{}{Panenka pana Nixona}
{49101}{}{Vidíš malou panenku s velikım èervenım nosem. Z nìjakého zvláštního dùvodu této zdánlivì nevinné dìtské hraèce nevìøíš.}
{49200}{}{Tanker FOB}
{49201}{}{Zakódovaná vstupní karta umoòující vstup do všech zabezpeèenıch zón tankeru.}
{49300}{}{Holodisk s uèením}
{49301}{}{Na štítku stojí: "Uèení Hubologistù."}
{49400}{}{Platidlo Kokoweef}
{49401}{}{Toto je malá plastiková mince, kterou se pravdìpodobnì vyplácí mzda horníkùm z dolu Kokoweef.}
{49500}{}{Prezidentská karta}
{49501}{}{Tato pøístupová karta má na sobì nìco, co vypadá jako prezidentskı symbol. Zdá se, e se dá pouít k získání prezidentského oprávnìní v poèítaèích.}
{49600}{}{Boxerské rukavice}
{49601}{}{Pár boxerskıch rukavic, které slabì páchnou potem. Urèitì u zaily hodnì zápasù. Zùstala na nich spousta krvavıch skvrn.}
{49700}{}{Plátované rukavice}
{49701}{}{Nìkdo "omylem" vloil nìkolik kovovıch plátù do tìchto boxerskıch rukavic. Technicky vzato by to mohlo bıt povaováno za podvod, ale ty v tom vidíš pøíleitost jak zpøelámat pár kostí.}
{49800}{}{Dvojitı plazmovı kanón}
{49801}{}{Zbraò støelecké vìe.}
{49900}{}{Jazykovı Pip-Boy modul}
{49901}{}{Tento jazykovı Pip-Boy modul obsahuje pamìovı holodisk, kabel s mikrovlákny, helmu a optickı senzor, kterı se umisuje pøed pravé oko uivatele. Pøi pouití se optickou cestou pøenese celı slovník do pamìti uivatele a tím tak natrvalo zvıší jeho dovednost "Øeè".}
{50000}{}{FN FAL HPFA}
{50001}{}{Tato puška byla uívána ozbrojenımi silami více ne kterákoliv jiná puška v historii. Je to spolehlivá útoèná zbraò do jakéhokoliv terénu nebo bojové situace. Model HPFA je silnìjší ne standardní FN FAL. Min. SÍ: 5.}
{50100}{}{Nástìnnı sejf}
{50200}{}{Trezor}
{50300}{}{Modrı pamìovı modul}
{50301}{}{Pamìovı "read only" modul obsahující lékaøská data. Obsahuje detaily o monostech zvıšení charisma.}
{50400}{}{Zelenı pamìovı modul}
{50401}{}{Pamìovı "read only" modul obsahující lékaøská data. Obsahuje detaily o monostech zvıšení vnímání.}
{50500}{}{Èervenı pamìovı modul}
{50501}{}{Pamìovı "read only" modul obsahující lékaøská data. Obsahuje detaily o monostech zvıšení síly.}
{50600}{}{lutı pamìovı modul}
{50601}{}{Pamìovı "read only" modul obsahující lékaøská data. Obsahuje detaily o monostech zvıšení inteligence.}
{50700}{}{Hnijící tìlo}
{50701}{}{Èásteènì rozloené tìlo nìjakého humanoidního tvora.}
{50800}{}{Nafukovací panna}
{50801}{}{Nafukovací gumová panna. Tento model se jmenuje "Tandi".}
{50900}{}{Poškozená nafukovací panna}
{50901}{}{Tato nafukovací gumová panna má natrenı šev. Oèividnì byla èasto pouívána.}
{51000}{}{Kuleèníkovı stùl}
{51100}{}{Kuleèníkovı stùl}
{51101}{}{}
{51200}{}{Kuleèníkovı stùl}
{51300}{}{Kuleèníkovı stùl}
{51400}{}{Kuleèníkovı stùl}
{51500}{}{Kuleèníkovı stùl}
{51600}{}{Lékaøskı Pip-Boy modul}
{51601}{}{Tento lékaøskı Pip-Boy modul obsahuje pamìovı holodisk, kabel s mikrovlákny, pøilbu a optickı senzor, kterı se umisuje pøed levé oko uivatele. Pøi pouití se optickou cestou pøenese lékaøskı slovník a lékaøské dovednosti do pamìti uivatele a tím tak natrvalo zvıší jeho dovednost "Léèení".}
{51700}{}{"Malı Jeíš"}
{51701}{}{Tento zlomyslnì vypadající nù patøil døíve Malému Jeíši Mordinovi. Na povrchu je spousta škrábancù a záøezù, ale èepel je ostrá jako bøitva. Na rukojeti je vyøezán nápis "Malı Jeíš."}
{51800}{}{Dvojitı gatling}
{51801}{}{Zbraò automatickıch vìí.}
{51900}{}{Zátky}
{51901}{}{Toto jsou bezcenné zátky od lahví. Povídá se, e je v dávnıch èasech lidé pouívali místo penìz, ale máš takové tušení, e je to jenom povìst.}
{52000}{}{Tìkı dvojitı gatling}
{52001}{}{Zbraò automatickıch vìí.}
{52100}{}{Almunièka}
{52101}{}{Malá kovová pokladnièka pouívaná k vybírání penìz pro chudé.}
{52200}{}{Meè Wakizashi}
{52201}{}{Kvalitnì vyrobenı krátkı meè. Zdá se, e byla špièka navrena na proráení zbrojí.}
{52300}{}{Geologická mapa}
{52301}{}{Vypadá to jako geologická mapa pobøení oblasti.}
{52400}{}{Róba Stráce mostu}
{52401}{}{Tento páchnoucí špinavı odìv musel bıt vyroben z nìjakého zvláštního materiálu, kdy dokázal bez poškození vydret to, co nevydrelo tìlo Stráce. Zvláštní je, e má všude na sobì stopy po plazmovıch zbraních... ale bez úèinku. Nemáš NEJMENŠÍ tušení, proè má fialovou barvu.}
{52500}{}{Hypo}
{52501}{}{Nìjakı druh injekèního prostøedku. Vypadá velice hi-tech. Nevíš, èím je naplnìn, ale zdá se, e u zbyla jen jedna dávka.}
{52600}{}{Mrtvı Èervenokošiláè}
{52601}{}{Tento chlapík má na sobì podivnou èervenou uniformu, kterou jsi nikdy pøedtím nevidìl. Zdá se, e zemøel na dehydrataci.}
{52700}{}{Mrtvı Èervenokošiláè}
{52701}{}{Tento chlapík má na sobì podivnou èervenou uniformu, kterou jsi nikdy pøedtím nevidìl. Zdá se, e zemøel na dehydrataci.}
{52800}{}{Mrtvı Èervenokošiláè}
{52801}{}{Tento chlapík má na sobì podivnou èervenou uniformu, kterou jsi nikdy pøedtím nevidìl. Zdá se, e zemøel na dehydrataci.}
{52900}{}{Dùlní rypadlo}
{53000}{}{Zbraò finálního bosse}
{53100}{}{Plazmová zbraò finálního bosse}
{53200}{}{Mapa Sama Pritcharda}
{53201}{}{Na této nahrubo naèrtnuté mapì je vyobrazena oblast kolem New Rena. Vypadá to, e je na severu nìjaká vojenská základna.}
{53300}{}{Kùe ohnivého geckona}
{53301}{}{Suchá a zakonzervovaná kùe ohnivého geckona.}
{53400}{}{Kbelík}
{53401}{}{Kbelík støední velikosti, kterı se pouívá na tahání vody ze studny.}
{53500}{}{Ohavná ryba}
{53501}{}{Ohavnì vypadající ryba. Pokud se uvaøí, bude z ní moná chutné jídlo.}
{53600}{}{Ryba}
{53601}{}{Syrovì vypadající ryba. Pokud se uvaøí, bude z ní moná chutné jídlo.}
{53700}{}{Óda na Ohnivou Potopu}
{53701}{}{Román odehrávající se po znièující jaderné válce. Vıòatek z knihy popisuje, jak vlna násilí smetla veškeré pokroèilé znalosti a technologie, které vedly k vıvoji jadernıch zbraní krátce po této válce. Kadı uèenı a nakonec i kadı, kdo umìl èíst, mìl bıt zabit.}
{53800}{}{Uèebnice}
{53801}{}{Stará uèebnice z doby pøed Velkou Válkou. Její obsah je pomìrnì odbornı, ale nevypadá to, e by obsahovala nìjaké uiteèné informace.}
{53900}{}{Technická pøíruèka}
{53901}{}{Stará technická pøíruèka urèená pro inenıry armádního sboru americké armády.}
{54000}{}{Uivatelskı manuál}
{54001}{}{Uivatelskı manuál pro pøenosné taktické šifrovací zaøízení KV-75. Také hojnì pouívané civilním personálem pro vysokoúrovòovou komunikaci na místních širokopásmovıch telefonních sítích a širokopásmovıch satelitních terminálech.}
{54100}{}{Manuál speciálních jednotek}
{54101}{}{Vùbec nerozumíš textu, ale obrázky jsou celkem srozumitelné.}
{54200}{}{Láhev vína}
{54201}{}{Láhev toho nejlepšího vína z Opatství.}
{54300}{}{Deník}
{54301}{}{Zdá se, e tento deník patøil mladé dívce. Nápis na vnitøní stranì obálky øíká: "Majetek Anny". Vìtšina stránek je buï roztrhaná nebo vybledlá, ale jedna z nich je pøeci jen èitelná. "Den 271: Dnes jsem od mámy dostala zlatı pøívìsek. Je to ta nejkrásnìjší vìc, kterou jsem kdy mìla. Nechám si ho do a konce ivota."}
{54400}{}{Botanickı holodisk}
{54401}{}{Tento informaèní disk popisuje rozlièné druhy flóry, které rostly pøed Velkou Válkou.}
{54500}{}{Prošlı G.E.C.K}
{54501}{}{"Souprava k vytvoøení rajské zahrady". Tento pøístroj je souèástí standardního vybavení Vaultù firmy Vault-Tec. GECK je prostøedek k vybudování civilizace po jaderné válce. Staèí pøidat vodu a zamíchat. Tomuto u dávno vypršela doba trvanlivosti. Takové plıtvání!}
{54600}{}{Stará mince}
{54601}{}{Velmi stará mince. Nevíš jistì, kdo je na ní vyobrazenı, ale vypadá to, e by mohla bıt vzácná a velmi cenná.}
{54700}{}{Hodinky}
{54701}{}{Staroitné hodinky. Tato znaèka se pøestala vyrábìt dlouho pøed Velkou Válkou.}
{54800}{}{Krabièka "Komoušek"}
{54801}{}{Nápis vzadu øíká: "Vykuø Komouše, udìlej to pro demokracii a pro svùj dobrı pocit." Vespod je zdravotní varování: "Jako váš doktor doporuèuji Komouše pro svìí dech a vítìznı úsmìv." V krabièce je asi 10 cigaret.}
{54900}{}{Plynová maska}
{54901}{}{Ochranná maska: Tvá maska je první línií obrany proti biologickım èinitelùm. Dobøe se o ni starej.}
{55000}{}{Toustovaè}
{55001}{}{Na stole stojící støíbrnı toustovaè.}
{55100}{}{Injekèní støíkaèka}
{55101}{}{Pøedváleènı nástroj pro podávání lékù. Je naplnìna neznámou látkou.}
{55200}{}{Psí rádlo}
{55201}{}{Nìkolik plechovek psího rádla.}
{55300}{}{Sprej proti hmyzu}
{55301}{}{Sprej naplnìnı látkou, která zabíjí všechen známı hmyz.}
{55400}{}{Ochrannı oblek}
{55401}{}{Nejlepší oblek proti biologickım útokùm.}
{55500}{}{EPA leták}
{55501}{}{Tento informaèní leták se rozdává na zaèátku prohlídky.}
{55600}{}{Léky}
{55601}{}{Nìjakı druh lékù zachovalıch z pøedváleèného období.}
{55700}{}{Pøístupová karta}
{55701}{}{Tato pøístupová karta odemyká bezpeènostní místnosti.}
{55800}{}{Stojánek na zkumavky}
{55801}{}{Stojánek na uloení zkumavek.}
{55900}{}{Klíèe}
{55901}{}{Klíèe umoòující vstup do skladištì na povrchu.}
{56000}{}{Rùzné chemikálie}
{56001}{}{NEBEZPEÈÍ! Neznámé chemikálie. Dbejte zvıšené opatrnosti.}
{56100}{}{Semena}
{56101}{}{Balíèky semen. Na štítku stojí, e jde o geneticky upravená kukuøièná semena imunní proti nákazám a napadení hmyzem.}
{56200}{}{Sprej proti rostlinám}
{56201}{}{Sprej naplnìnı látkou, která zabíjí rùzné druhy rostlin.}
{56300}{}{Dálkovì øízenı dynamit}
{56301}{}{Na rozdíl od dynamitù s èasovaèem lze tento odpálit na dálku.}
{56400}{}{Detonátor}
{56401}{}{Odpalovací zaøízení dynamitu.}
{56500}{}{List papíru}
{56501}{}{List papíru s naèmáranım heslem.}
{56600}{}{Experimentální semena}
{56601}{}{Balíèek experimentálních semen. Vısledek klíèení není znám.}
{56700}{}{Vrtaèka}
{56701}{}{Elektrická vrtaèka.}
{56800}{}{Dálkovì øízenı dynamit}
{56801}{}{Na rozdíl od dynamitù s èasovaèem lze tento odpálit na dálku. Dynamit je odjištìn a pøipraven k odpálení.}
{56900}{}{Pop Rocks}
{56901}{}{Neotevøenı balíèek chutnıch bonbónù vyrobenıch z cukru, laktózy (více cukru), kukuøièného syrupu (ještì více cukru) a rùznıch pøíchutí. Øíká se, e kdy se smíchají s nápojem jako je Nuka Cola, mùe dojít k explozi aludku.}
{57000}{}{Láhev šampónu}
{57001}{}{Láhev kvalitního šampónu. Na rozdíl od jinıch pøedních znaèek je zabalen v neobvyklé pruné plastové láhvi. Byla takto speciálnì navrena, aby po jejím zmáèknutí vyteklo jen potøebné mnoství šamponu. Ne více, ne ménì. Staèí odklopit víèko a zmáèknout.}
{57100}{}{K-9 Kevlar}
{57101}{}{Stará zaprášená sada odolnıch kevlarovıch plátù zasazenıch do èernıch nylonovıch pouzder. Pøijde ti to jako velikost pro trpaslíky, dokud si nevšimneš štítku zevnitø, na kterém stojí: Psí kevlar. Velkı. Produkt firmy DoggieBuddy. Made in Taiwan.}
{57200}{}{Lidské ucho}
{57201}{}{enské ucho. Fuj! Jen duševnì nestabilní jedinec by dokázal oddìlit lidské ucho.}
{57300}{}{Kanystr s ERSI}
{57301}{}{Kanistr s "Inhibitory syndromu odmítání prostøedí". Aplikuje se na jedince, kterı prošel dlouhodobou hibernací.}
{57400}{}{Svìtelnı meè}
{57401}{}{Starodávná zbraò z civilizovanìjší doby. Není tak tìkopádná a nepøesná jako blaster. Daroval ti ji mocnı Obi-Wan-Killap. Min. SÍ: 2}
{57500}{}{Blaster}
{57501}{}{Sentimentální náboenství a starobylı zbranì se nedaj srovnávat s poøádnım blasterem u pasu, mladej. Min ST: 3}
{57600}{}{Svìtelnı meè}
{57601}{}{Starodávná zbraò z civilizovanìjší doby. Není tak tìkopádná a nepøesná jako blaster. Darovala ti ho mocná Imperátorka Timeslip. Min. SÍ: 2.}
{57700}{}{Vzduchová ventilace}
{57701}{}{Møíka na tomto vìtracím otvoru vypadá odlišnì.}
{57800}{}{Kovová skøíòka}
{57801}{}{Skøíòka na vìci.}
{57900}{}{Kovová skøíòka}
{57901}{}{Skøíòka na vìci.}
{58000}{}{Èínská tabulka kódù}
{58001}{}{Nevíš to jistì, ale vypadá to jako tabulka obsahující rozlièné èínské instrukèní kódy. Kdyby se ti podaøilo najíst místo, kam tyto kódy vloit, moná se nìco nového nauèíš.}
{58100}{}{Mrtvı divoch}
{58101}{}{Tato osoba zemøela strašlivou smrtí na lékaøském stole.}
{58200}{}{Mrtvı divoch}
{58201}{}{Tato osoba zemøela strašlivou smrtí na lékaøském stole.}
{58300}{}{Trn}
{58301}{}{Semeno ve tvaru trnu, které masoravé rostliny vystøelují po své potenciální potravì nebo nositelích semen. Tento je ostøejší a tvrdší ne obvykle.}
{58400}{}{Mrtvı obyvatel vaultu}
{58401}{}{Tato osoba zemøela strašlivou smrtí na lékaøském stole.}
{58500}{}{Mrtvı obyvatel vaultu}
{58501}{}{Tato osoba zemøela strašlivou smrtí na lékaøském stole.}
{58600}{}{Mrtvı divoch}
{58601}{}{Tato osoba zemøela strašlivou smrtí na lékaøském stole.}
{58700}{}{Mrtvı divoch}
{58701}{}{Tato osoba zemøela strašlivou smrtí na lékaøském stole.}
{58800}{}{K-9 Kevlar}
{58801}{}{Nositelnı K-9 Kevlar (FAKE)}
{58900}{}{Zbroj pro mutanty}
{58901}{}{Zbroj pro mutanty}
{59000}{}{Zbroj pro mutanty}
{59001}{}{Nositelná zbroj pro mutanty (FAKE)}
{59100}{}{Malı ocas radškorpiona}
{59101}{}{Oddìlenı ocas malého radškorpiona.}
{59200}{}{Semeno rostliny}
{59201}{}{Semeno rostliny, které ti dal Dr. Sheng.}
{59300}{}{Nic zvláštního}
{59301}{}{Nic zvláštního.}
{59400}{}{Nic zvláštního}
{59401}{}{Nic zvláštního.}
{59500}{}{Nic zvláštního}
{59501}{}{Nic zvláštního.}
{59600}{}{Falešné pilulky na srdce}
{59601}{}{Tyto pilulky obvykle uívají lidé se srdeèními problémy, avšak v tomto pøípadì by po poití nastala smrt. Byly toti smíchány s dalšími chemikáliemi a vıslednı produkt tak garantuje srdcervoucí záitek.}
