{100}{}{Hoøící eleznı sud}
{101}{}{eleznı sud, ve kterém hoøí kusy starého papíru a jiného spalitelného odpadu.}
{200}{}{Døevìné dveøe}
{201}{}{Dveøe vyrobené ze døeva.}
{300}{}{Døevìnı stùl}
{301}{}{Stùl vyrobenı ze døeva.}
{400}{}{Døevìnı stùl}
{401}{}{Stùl vyrobenı ze døeva.}
{500}{}{eleznı sud}
{501}{}{Starı sud vyrobenı ze eleza.}
{600}{}{eleznı sud}
{601}{}{Starı sud vyrobenı ze eleza.}
{700}{}{Hromada pneumatik}
{701}{}{Hromada starıch gumovıch pneumatik. Jsou vulkanizované a ztvrdlé, pravdìpodobnì pùsobením horka.}
{800}{}{Bezpeènostní dveøe}
{801}{}{Velmi bytelnì vypadající dveøe. Poskytují ochranu pøed venkovním svìtem a nebezpeènımi tvory.}
{900}{}{Poèítaè}
{901}{}{Poèítaèovı terminál napojenı na hlavní poèítaè.}
{1000}{}{Sloup}
{1001}{}{Opìrnı sloup zajišující rovnomìrné rozloení váhy celé stavby.}
{1100}{}{Poèítaè}
{1101}{}{Poèítaèovı terminál napojenı na hlavní poèítaè.}
{1200}{}{Poèítaè}
{1201}{}{Poèítaèovı terminál napojenı na hlavní poèítaè.}
{1300}{}{Monitor}
{1301}{}{Monitor zobrazující zelenou plochu. Na obrazovce obèas probliknou nìjaká data.}
{1400}{}{Monitor}
{1401}{}{Monitor zobrazující zelenou plochu.}
{1500}{}{Holo generátor}
{1501}{}{Velkoplošnı pøehrávaè THT pásek. Za posledních osmdesát let nebyly natoèeny ádné nové filmy.}
{1600}{}{Obrazovky}
{1601}{}{Øada tøí monitorù zobrazujících rùzná data.}
{1700}{}{Obrazovky}
{1701}{}{Øada tøí monitorù zobrazujících rùzná data tıkajících se tohoto vaultu.}
{1800}{}{Dveøe}
{1801}{}{I po bliším prozkoumání jsou to stále jen dveøe.}
{1900}{}{Dveøe}
{1901}{}{I po bliším prozkoumání jsou to stále jen dveøe.}
{2000}{}{Vìtrací otvor}
{2001}{}{Vzduchová ventilace, která zásobuje celı komplex èistım vzduchem.}
{2100}{}{Vìtrací otvor}
{2101}{}{Vzduchová ventilace, která zásobuje celı komplex èistım vzduchem.}
{2200}{}{Dveøe Vaultu 13}
{2201}{}{Mohutné ocelové dveøe zkonstruované tak, aby odolaly i tomu nejtìšímu poškození.}
{2300}{}{Dveøe Vaultu 13}
{2301}{}{Mohutné ocelové dveøe zkonstruované tak, aby odolaly i tomu nejtìšímu poškození.}
{2400}{}{Podstavec}
{2401}{}{Hydraulicky vısuvnı podstavec urèenı k vedení energetickıch a komunikaèních spojù ke Správcovì plošinì.}
{2500}{}{Monitor}
{2501}{}{Vidìl-li jsi jeden, vidìl jsi je všechny.}
{2600}{}{Monitor}
{2601}{}{Poèítaèovı monitor zobrazující rùzná data.}
{2700}{}{Møí}
{2701}{}{Møí v podlaze.}
{2800}{}{Potrubí}
{2801}{}{I po bliším prozkoumání jsou to stále jen trubky.}
{2900}{}{Vìtrací otvor}
{2901}{}{Standardní ventilaèní systém Vault-Tec.}
{3000}{}{Sloup}
{3001}{}{Obyèejnı opìrnı sloup od firmy Vault-Tec.}
{3100}{}{Sloup}
{3101}{}{Obyèejnı opìrnı sloup od firmy Vault-Tec.}
{3200}{}{Vìtrací otvor}
{3201}{}{Standardní ventilaèní systém Vault-Tec.}
{3300}{}{Vìtrací otvor}
{3301}{}{Standardní ventilaèní systém Vault-Tec.}
{3400}{}{Postel}
{3401}{}{Postel. Vypadá docela pohodlnì ve srovnání s tím, na èem obvykle spíš.}
{3500}{}{Postel}
{3501}{}{Obyèejná postel. Vypadá pohodlnì.}
{3600}{}{Postel}
{3601}{}{Obyèejná postel. Vypadá pohodlnì.}
{3700}{}{Postel}
{3701}{}{Obyèejná postel. Vypadá pohodlnì.}
{3800}{}{Vıtah}
{3801}{}{Vıtah údrby.}
{3900}{}{idle}
{3901}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{4000}{}{idle}
{4001}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{4100}{}{idle}
{4101}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{4200}{}{idle}
{4201}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{4300}{}{Monitor}
{4301}{}{Poèítaèovı monitor zobrazující rùzná data.}
{4400}{}{Monitor}
{4401}{}{Poèítaèovı monitor zobrazující rùzná data.}
{4500}{}{Monitor}
{4501}{}{Poèítaèovı monitor zobrazující rùzná data.}
{4600}{}{Monitor}
{4601}{}{Poèítaèovı monitor zobrazující rùzná data.}
{4700}{}{Monitor}
{4701}{}{Poèítaèovı monitor zobrazující rùzná data.}
{4800}{}{Monitor}
{4801}{}{Poèítaèovı monitor zobrazující rùzná data.}
{4900}{}{Vıchod z mapy}
{4901}{}{Vıchod z mapy}
{5000}{}{Èistièka vzduchu}
{5001}{}{Zaøízení, které èistí starı vzduch a pøivádí do komplexu novı vzduch.}
{5100}{}{idle}
{5101}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{5200}{}{idle}
{5201}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{5300}{}{idle}
{5301}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{5400}{}{idle}
{5401}{}{idle. Škoda, e nemáš èas si sednout a trochu relaxovat.}
{5500}{}{JVV}
{5501}{}{Jednotka video vıstupu. Sdruuje nìkolik poèítaèovıch a televizních monitorù. Na všech se nìco dìje.}
{5600}{}{JVV}
{5601}{}{Jednotka video vıstupu. Sdruuje nìkolik poèítaèovıch a televizních monitorù. Na všech se nìco dìje.}
{5700}{}{idle}
{5701}{}{idle. Vypadá fakt pohodlnì.}
{5800}{}{idle}
{5801}{}{idle. Vypadá fakt pohodlnì.}
{5900}{}{idle}
{5901}{}{idle. Vypadá fakt pohodlnì.}
{6000}{}{idle}
{6001}{}{idle. Vypadá fakt pohodlnì.}
{6100}{}{Stùl}
{6101}{}{Stùl. Ne ho lidé vynalezli, museli vìci pokládat na podlahu.}
{6200}{}{Stùl}
{6201}{}{Toto je zcela urèitì stùl.}
{6300}{}{Laskavec}
{6301}{}{Bylina zvaná laskavec. Ještì nikdy pøedtím se ti nepodaøilo ádnou ivou zahlédnout. Prohlédni si ji tedy poøádnì.}
{6400}{}{Kaktus}
{6401}{}{Na tomto kaktusu není nic zvláštního.}
{6500}{}{Kaktus}
{6501}{}{Na tomto kaktusu není nic zajímavého.}
{6600}{}{Strom}
{6601}{}{Mrtvı strom. Tady ostatnì nic neroste dobøe.}
{6700}{}{Tajnı blokaèní hex}
{6701}{}{Pokud tohle vidíš, pošli stínost technickému návrháøi.}
{6800}{}{Schody}
{6801}{}{Spousta schodù.}
{6900}{}{Stalagmit}
{6901}{}{Pøírodní vırùstek z kamenné podlahy.}
{7000}{}{Stalagmit}
{7001}{}{Pøírodní vırùstek z kamenné podlahy.}
{7100}{}{Krvavá skvrna}
{7101}{}{Na této skvrnì není nic neobvyklého. Tedy samozøejmì kromì toho, e tu nìkdo nebo nìco zemøelo.}
{7200}{}{Kamennı sloup}
{7201}{}{Tlustı kamennı sloup vedoucí od podlahy ke stropu.}
{7300}{}{Kamennı sloup}
{7301}{}{Tenkı kamennı sloup vedoucí od podlahy ke stropu.}
{7400}{}{Kameny}
{7401}{}{Chvíli kameny zkoumáš, ale nepohnuly se.}
{7500}{}{Kameny}
{7501}{}{Dej si na tyto kameny bedlivı pozor, tøeba na tebe chtìjí zaútoèit.}
{7600}{}{}
{7601}{}{}
{7700}{}{Brána}
{7701}{}{Døevìná brána.}
{7800}{}{Kameny}
{7801}{}{Velká hromada kamení. Zdá se, e jsou pùvodem z této oblasti.}
{7900}{}{Kameny}
{7901}{}{Malá hromádka kamení.}
{8000}{}{Kameny}
{8001}{}{Malá hromádka kamení.}
{8100}{}{Kameny}
{8101}{}{Velká hromada kamení.}
{8200}{}{Kosti}
{8201}{}{Hromada vybìlenıch zvíøecích kostí. Tedy, myslíš si, e jsou zvíøecí...}
{8300}{}{Kosti}
{8301}{}{Hromada vybìlenıch zvíøecích kostí. Tedy, myslíš si, e jsou zvíøecí...}
{8400}{}{Kosti}
{8401}{}{Velká hromada vybìlenıch kostí. Nedokáeš urèit, co to bylo za tvory.}
{8500}{}{Kosti}
{8501}{}{Myslíš si, e jsou to kosti rohatého klokana, ale nevíš to jistì. Pro pøesné urèení jsou bohuel pøíliš zvìtralé.}
{8600}{}{Kosti}
{8601}{}{Vidíš kosti velké dvouhlavé krávy.}
{8700}{}{Brána}
{8701}{}{Døevìná brána. Dá se otevøít a zavøít, otevøít a zavøít...}
{8800}{}{Brána}
{8801}{}{Døevìná brána.}
{8900}{}{Brána}
{8901}{}{Døevìná brána.}
{9000}{}{Kameny}
{9001}{}{Velká hromada kamení. Vypadají nebezpeènì i kdy jen tak leí.}
{9100}{}{Kameny}
{9101}{}{Velká hromada kamení. Kdy se podíváš zblízka, vidíš po stranách tváøe malıch starıch muù.}
{9200}{}{Kameny}
{9201}{}{Kamení, kamení, kamení! Kamení všude kam se podíváš!}
{9300}{}{Kameny}
{9301}{}{Malá hromádka kamení.}
{9400}{}{Bar}
{9401}{}{V tomto baru je mnoství lahví s nejrùznìjšími destiláty. Jen je naèepovat.}
{9500}{}{idle}
{9501}{}{Napùl shnilá idle vyrobená ze staré autosedaèky.}
{9600}{}{idle}
{9601}{}{Páchnoucí stará idle vyrobená z autosedaèky. Pruiny ji dávno ztratily svou prunost.}
{9700}{}{idle}
{9701}{}{Rozpadající se stará idle postavená na cihlách. Vypadá velice nepohodlnì.}
{9800}{}{idle}
{9801}{}{Rozpadající se stará idle postavená na cihlách. Vypadá velice nepohodlnì.}
{9900}{}{Pohovka}
{9901}{}{Velmi nepohodlnì vypadající zaøízení na sezení známé také jako gauè.}
{10000}{}{Pohovka}
{10001}{}{Velmi nepohodlnì vypadající zaøízení na sezení známé také jako gauè.}
{10100}{}{Pneumatika}
{10101}{}{Stará gumová pneumatika pohozená v køoví.}
{10200}{}{Køoví}
{10201}{}{Nìjakı druh pouštního plevelu.}
{10300}{}{Køoví}
{10301}{}{Nìjakı druh pouštního plevelu.}
{10400}{}{Køoví}
{10401}{}{Nìjakı druh pouštního plevelu.}
{10500}{}{Køoví}
{10501}{}{Nìjakı druh pouštního plevelu.}
{10600}{}{Haraburdí}
{10601}{}{Zrezivìlé dveøe od auta opøené o starı zrezivìlı sud. To je opravdu hodnì rzi.}
{10700}{}{Haraburdí}
{10701}{}{Rozbitı záchod napùl pohøbenı v písku. ivot je na hovno a potom umøeš.}
{10800}{}{Plevel}
{10801}{}{Nìjakı druh pouštního køoví. Pokud se tomu nìkdy daøilo, tak teï u rozhodnì ne.}
{10900}{}{Haraburdí}
{10901}{}{Pneumatika zapadlá v písku. Kolem ní se povalují døevìné tøísky.}
{11000}{}{Kameny}
{11001}{}{Po podrobnìjším prozkoumání konstatuješ, e by to nejspíš mohlo bıt zkamenìlé døevo.}
{11100}{}{Hlína}
{11101}{}{Hromádka hlíny, ze které trèí uschlá rostlina.}
{11200}{}{Hlína}
{11201}{}{Hromádka hlíny.}
{11300}{}{Hlína}
{11301}{}{Hromádka hlíny.}
{11400}{}{Hlína}
{11401}{}{Hromádka hlíny.}
{11500}{}{Rostlina}
{11501}{}{Hromádka hlíny, ze které trèí uschlá rostlina.}
{11600}{}{Haraburdí}
{11601}{}{Zkroucenı kus rezavého plechu.}
{11700}{}{Haraburdí}
{11701}{}{Rozlámané kusy døeva.}
{11800}{}{Haraburdí}
{11801}{}{Malá hromádka nejrùznìjších odpadkù.}
{11900}{}{Hlína}
{11901}{}{Hromádka hlíny.}
{12000}{}{Hlína}
{12001}{}{Hromádka hlíny.}
{12100}{}{Hlína}
{12101}{}{Hromádka hlíny.}
{12200}{}{Hlína}
{12201}{}{Hromádka hlíny.}
{12300}{}{Hlína}
{12301}{}{Hromádka hlíny.}
{12400}{}{Hlína}
{12401}{}{Hromádka hlíny.}
{12500}{}{Rostlina}
{12501}{}{Bìnı druh pouštní rostliny.}
{12600}{}{Rostlina}
{12601}{}{Bìnı druh pouštní rostliny.}
{12700}{}{Rostlina}
{12701}{}{Bìnı druh pouštní rostliny.}
{12800}{}{Blokující Hex (Neosvícenı)}
{12900}{}{Stìna}
{13000}{}{Stìna}
{13100}{}{Stìna}
{13200}{}{Stìna}
{13300}{}{Stìna}
{13400}{}{Stìna}
{13500}{}{Stoka}
{13501}{}{Z kanálu vychází jakısi odpornı zápach. Ale po chvíli u to není tak strašné.}
{13600}{}{Stoka}
{13601}{}{Skrz møí zahlédneš nìjakı pohyb. Ze tmy na tebe zírají malé rudé oèi. Krysí oèi.}
{13700}{}{Stoka}
{13701}{}{Z kanálu se line zvuk bublající vody. A také pøíšernı zápach.}
{13800}{}{Stoka}
{13801}{}{Z kanálu se line zvuk bublající vody. A také pøíšernı smrad.}
{13900}{}{ebøík}
{13901}{}{Starı vratkı ebøík. Vypadá to, e tì stìí unese.}
{14000}{}{Vstup do kanálu}
{14001}{}{Vypadá to jako vstup do stok.}
{14100}{}{Svìtelnı zdroj}
{14200}{}{Dveøe}
{14201}{}{Vypadá to jako standardní dveøe vaultu, které byly pravdìpodobnì poškozeny ohnìm. I pøesto jsou stále funkèní.}
{14300}{}{Dveøe}
{14301}{}{Vypadá to jako standardní dveøe vaultu, které byly pravdìpodobnì poškozeny ohnìm. I pøesto jsou stále funkèní.}
{14400}{}{Poklop}
{14401}{}{Tìkı poklop. Zdá se, e je v dobrém stavu a nedávno se s ním hıbalo.}
{14500}{}{Díra}
{14501}{}{Velká díra vypálená skrz dveøe.}
{14600}{}{Díra}
{14601}{}{Velká díra vypálená skrz dveøe.}
{14700}{}{Neprùstøelné sklo}
{14701}{}{Absolutnì neznièitelné sklo. Ani to nezkoušej.}
{14800}{}{Neprùstøelné sklo}
{14801}{}{Absolutnì neznièitelné sklo. Ani to nezkoušej.}
{14900}{}{Neprùstøelné sklo}
{14901}{}{Absolutnì neznièitelné sklo. Ani to nezkoušej.}
{15000}{}{Neprùstøelné sklo}
{15001}{}{Absolutnì neznièitelné sklo. Ani to nezkoušej.}
{15100}{}{Dveøe}
{15101}{}{Tyto dveøe jsou pøíkladem vyspìlé konstrukèní technologie. Skládají se ze tøí pohybujících se kovovıch segmentù, které tvoøí samotné dveøe.}
{15200}{}{Dveøe}
{15201}{}{Tyto dveøe jsou pøíkladem vyspìlé konstrukèní technologie. Skládají se ze tøí pohybujících se kovovıch segmentù, které tvoøí samotné dveøe.}
{15300}{}{Dveøe}
{15301}{}{Tyto dveøe jsou opatøeny znakem Bratrstva Oceli.}
{15400}{}{Dveøe}
{15401}{}{Tyto dveøe jsou opatøeny znakem Bratrstva Oceli.}
{15500}{}{Vıtah}
{15501}{}{Vnitøek vıtahu Bratrstva. Je neuvìøitelnì èistı!}
{15600}{}{Vıtah}
{15601}{}{Vnitøek vıtahu Bratrstva. Je neuvìøitelnì èistı!}
{15700}{}{Symbol}
{15701}{}{Symbol Bratrstva Oceli. Jeho úkolem je informovat všechny pøíchozí o tom, e toto je území Bratrstva a e mají ihned odejít.}
{15800}{}{Monitor}
{15801}{}{Vidíš poèítaèovı monitor.}
{15900}{}{Monitor}
{15901}{}{Vidíš poèítaèovı monitor.}
{16000}{}{Poèítaè}
{16001}{}{Toto je pamìová databanka.}
{16100}{}{Poèítaè}
{16101}{}{Toto je pamìová databanka.}
{16200}{}{Poèítaè}
{16201}{}{Špièkovı poèítaè vyuívající moderního záznamu na pásky namísto zastaralıch dìrnıch štítkù.}
{16300}{}{Poèítaè}
{16301}{}{Špièkovı poèítaè vyuívající moderního záznamu na pásky namísto zastaralıch dìrnıch štítkù.}
{16400}{}{Monitor}
{16401}{}{Vidíš poèítaèovı monitor.}
{16500}{}{Monitor}
{16501}{}{Vidíš poèítaèovı monitor.}
{16600}{}{Kabel}
{16601}{}{Nìkolik vzájemnì spletenıch poèítaèovıch kabelù.}
{16700}{}{Kabel}
{16701}{}{Nìkolik vzájemnì spletenıch poèítaèovıch kabelù.}
{16800}{}{Kabel}
{16801}{}{Nìkolik vzájemnì spletenıch poèítaèovıch kabelù.}
{16900}{}{Sloup}
{16901}{}{Podpùrnı sloup.}
{17000}{}{Sloup}
{17001}{}{Podpùrnı sloup.}
{17100}{}{Vstupní poèítaè}
{17101}{}{Tento poèítaè ovládá vstupní dveøe do vaultu. Pøed vstupem musíš zadat pøístupovı kód.}
{17200}{}{Cedule "Kasíno"}
{17201}{}{Reklama na Gizmovo kasíno.}
{17300}{}{Vnìjší dveøe Vaultu 13}
{17301}{}{Tyto mohutné dveøe jsou jedinou spojnicí mezi vaultem a vnìjším svìtem.}
{17400}{}{Vnìjší dveøe Vaultu 13}
{17401}{}{Tyto mohutné dveøe jsou jedinou spojnicí mezi vaultem a vnìjším svìtem.}
{17500}{}{Cedule "Kasíno"}
{17501}{}{Neon, kterım pomalu otáèí elektrickı motor.}
{17600}{}{Šipka dolù}
{17700}{}{Šipka nahoru}
{17800}{}{Bedna}
{17900}{}{Bedna}
{18000}{}{Bedna}
{18100}{}{Vršek vıtahu}
{18101}{}{Díváš se na horní èást vıtahu.}
{18200}{}{Poèítaèová konzole}
{18201}{}{Jednoduchı terminál propojenı kabelem s hlavním poèítaèem.}
{18300}{}{Poèítaèová konzole}
{18301}{}{Jednoduchı terminál propojenı kabelem s hlavním poèítaèem.}
{18400}{}{Emblém}
{18401}{}{Erb Bratrstva. Ozubená kola symbolizují technické vìdomosti Bratrstva, meè jejich odhodlání se bránit a køídla znamenají nadìji, která umírá poslední.}
{18500}{}{Emblém}
{18501}{}{Erb Bratrstva. Ozubená kola symbolizují technické vìdomosti Bratrstva, meè jejich odhodlání se bránit a køídla znamenají nadìji, která umírá poslední.}
{18600}{}{Oznaèení 'Jednièka'}
{18601}{}{Myslíš si, e by to mohlo znamenat, e jsi v prvním patøe.}
{18700}{}{Oznaèení 'Dvojka'}
{18701}{}{Jsi ve druhém patøe.}
{18800}{}{Oznaèení 'Trojka'}
{18801}{}{Urèitì to znamená, e jsi ve tøetím patøe.}
{18900}{}{Oznaèení 'Ètyøi'}
{18901}{}{Nejspíš budeš ve ètvrtém patøe.}
{19000}{}{Palanda}
{19001}{}{Vojenská palanda. Vypadá velmi nepohodlnì a prostìradlo je napnuté jako kšandy.}
{19100}{}{Palanda}
{19101}{}{Vojenská palanda. Vypadá velmi nepohodlnì a prostìradlo je napnuté jako kšandy.}
{19200}{}{Palanda}
{19201}{}{Vojenská palanda. Vypadá velmi nepohodlnì a prostìradlo je napnuté jako kšandy.}
{19300}{}{Bedna}
{19400}{}{Automat na Nuka-Colu}
{19401}{}{Reklama na boku automatu vychvaluje tento populární nápoj.}
{19500}{}{Stìna}
{19600}{}{Padací dveøe}
{19601}{}{Dokonale funkèní padací dveøe.}
{19700}{}{Prùlez}
{19701}{}{ebøík vede kamsi dolù do temnoty. Brrr, to je strašidelné.}
{19800}{}{Oltáø}
{19801}{}{Toto je oltáø.}
{19900}{}{Øeènickı stolek}
{19901}{}{Za touto vìcí lidé obvykle stojí a mluví. Má to dokonce i malı pultík, kam si mùeš poloit pøipravenou øeè.}
{20000}{}{Lavice}
{20001}{}{Lavice vypadá pøesnì tak, jak se by dalo oèekávat. Není na ní nic zvláštního.}
{20100}{}{Ukazatel}
{20101}{}{Písmena na tomto ukazateli jsou trochu rezavá.}
{20200}{}{Ukazatel}
{20201}{}{Písmena na tomto ukazateli jsou trochu rezavá.}
{20300}{}{Ukazatel}
{20301}{}{Písmena na tomto ukazateli jsou trochu rezavá.}
{20400}{}{Ukazatel}
{20401}{}{Písmena na tomto ukazateli jsou trochu rezavá.}
{20500}{}{Ukazatel}
{20501}{}{Písmena na tomto ukazateli jsou trochu rezavá.}
{20600}{}{Stará matrace}
{20601}{}{Stará vyslouilá matrace. Máš pocit, e je zamoøená nìjakım druhem malıch broukù.}
{20700}{}{Stará matrace}
{20701}{}{I kdybys spal na této vìci sám, nespal bys sám.}
{20800}{}{Postel}
{20801}{}{A makeshift bed. The material was scavenged from some other source.}
{20900}{}{Postel}
{20901}{}{A makeshift bed. The material was scavenged from some other source.}
{21000}{}{Postel}
{21001}{}{Tato postel u zaila lepší dny (a noci nejspíš taky.)}
{21100}{}{Postel}
{21101}{}{Po bliším prozkoumání docházíš k závìru, e prostìradlo nebylo vymìnìno u velmi, velmi dlouho.}
{21200}{}{Postel}
{21201}{}{Na tomto velmi opotøebovaném spacím zaøízení je nìkolik pochybnıch skvrn neidentifikovatelného pùvodu.}
{21300}{}{Postel}
{21301}{}{Tato postel u toho zaila opravdu hodnì. A taky se zdá, e nìco vlezlo mezi matrace a chcíplo tam.}
{21400}{}{}
{21401}{}{}
{21500}{}{}
{21501}{}{}
{21600}{}{}
{21601}{}{}
{21700}{}{UNUSED.}
{21800}{}{UNUSED.}
{21900}{}{UNUSED.}
{22000}{}{Krabice}
{22001}{}{Døevìné bedny, které se vlivem poèasí takøka rozpadly.}
{22100}{}{Krabice}
{22101}{}{Na tìchto døevìnıch bednách nenacházíš nic, co by stálo za øeè.}
{22200}{}{Krabice}
{22201}{}{Musíš mít opravdu asi hodnì èasu, kdy prohledáváš i tento shnilı odpad.}
{22300}{}{Krabice}
{22301}{}{Døevìné bedny, které se vlivem poèasí takøka rozpadly.}
{22400}{}{Auto}
{22401}{}{Tento automobil je v naprosto pøíšerném stavu. Nemáš nejmenší tušení, jak by se dal opravit.}
{22500}{}{Auto}
{22501}{}{Tento zrezivìlı kus šrotu u asi opravit nepùjde.}
{22600}{}{Auto}
{22601}{}{Docházíš k závìru, e tento vùz u nebude nikdy jezdit. Opravdu.}
{22700}{}{Auto}
{22701}{}{Tento kus šrotu u nebude v ádném pøípadì jezdit.}
{22800}{}{Auto}
{22801}{}{I kdyby se vedle tebe zèistajasna objevil Mechanik Roku, nebylo by ti to nic platné. Stejnì byste nebyli schopni tuhle zrezivìlou hromadu eleza opravit.}
{22900}{}{idle}
{22901}{}{Pohodlná idle.}
{23000}{}{idle}
{23001}{}{Tato idle u zaila lepší dny.}
{23100}{}{idle}
{23101}{}{Tato idle je zplesnivìlá a odporná. A navíc páchne.}
{23200}{}{idle}
{23201}{}{Tato idle se rozpadá. Hodnì rychle.}
{23300}{}{idle}
{23301}{}{Kdyby ti nìkdo zaplatil opravdu hodnì penìz a navíc bys mìl na sobì elezné brnìní, tak by ses na tuto idli moná i posadil.}
{23400}{}{idle}
{23401}{}{Stará kanceláøská idle. Po všech tìch letech je kupodivu v docela dobrém stavu.}
{23500}{}{idle}
{23501}{}{Stará kanceláøská idle. Moná by ještì udrela dospìlého èlovìka.}
{23600}{}{idle}
{23601}{}{Tato kanceláøská idle u zaila lepší dny. Teï u je ale víceménì na vyhození.}
{23700}{}{idle}
{23701}{}{Tohle vypadá pøesnì jako idle, kterou mùeš vidìt v márnici. Mrtvou.}
{23800}{}{}
{23900}{}{}
{24000}{}{}
{24100}{}{UNUSED.}
{24200}{}{UNUSED.}
{24300}{}{Poární hydrant}
{24301}{}{Toto je poární hydrant. A bude nìkdy hoøet, zapomeò na poární systém ve vaultech a pouij tohle.}
{24400}{}{Lampa}
{24401}{}{Tato lampa je kupodivu stále ještì funkèní. A vidìt tady nìco, co funguje, je takøka malı zázrak.}
{24500}{}{Lampa}
{24501}{}{Tato lampa u nikdy nebude fungovat.}
{24600}{}{Lampa}
{24601}{}{Tato lampa v noci vyzaøuje jemné tlumené svìtlo, které ti vùbec nic nepøipomíná.}
{24700}{}{Lampa}
{24701}{}{Toto je rozbitá lampa. Nedá se opravit.}
{24800}{}{Lampa}
{24801}{}{Tato lampa je stále ještì funkèní.}
{24900}{}{Lampa}
{24901}{}{Tato lampa je tak znièená, e u se nedá opravit.}
{25000}{}{Lampa}
{25001}{}{Tato lampa je stále ještì funkèní.}
{25100}{}{Brána}
{25101}{}{Zámek brány je zaseklı a závory vypadají velmi robustnì.}
{25200}{}{Haraburdí}
{25201}{}{Nepochybnì zcela nepouitelné haraburdí.}
{25300}{}{Haraburdí}
{25301}{}{Nepochybnì zcela nepouitelné haraburdí.}
{25400}{}{Haraburdí}
{25401}{}{Nepochybnì zcela nepouitelné haraburdí.}
{25500}{}{Haraburdí}
{25501}{}{Nepochybnì zcela nepouitelné haraburdí.}
{25600}{}{Haraburdí}
{25601}{}{Nepochybnì zcela nepouitelné haraburdí.}
{25700}{}{Poštovní schránka}
{25701}{}{Schránka je prázdná a máš takovı pocit, e u se dlouho nepouívala.}
{25800}{}{Dveøe}
{25801}{}{Kvalitnì vyrobené døevìné dveøe v dobrém stavu.}
{25900}{}{Dveøe}
{25901}{}{Kvalitnì vyrobené døevìné dveøe v dobrém stavu.}
{26000}{}{Dveøe}
{26001}{}{Kvalitnì vyrobené døevìné dveøe v dobrém stavu.}
{26100}{}{Dveøe}
{26101}{}{Kvalitnì vyrobené døevìné dveøe v dobrém stavu.}
{26200}{}{Lavice}
{26201}{}{Tato døevìná lavice se pomalu rozpadá.}
{26300}{}{Lavice}
{26301}{}{Tato lavice byla zanedbána a podepisuje se na ní zub èasu.}
{26400}{}{Lavice}
{26401}{}{Døevìná lavice pomalu podléhající vlivu staøí a špatného zacházení.}
{26500}{}{Novinovı automat}
{26501}{}{Je prázdnı.}
{26600}{}{Novinovı automat}
{26601}{}{Je prázdnı.}
{26700}{}{Novinovı automat}
{26701}{}{Je prázdnı.}
{26800}{}{Novinovı automat}
{26801}{}{Je prázdnı.}
{26900}{}{Novinovı automat}
{26901}{}{Je prázdnı.}
{27000}{}{Novinovı automat}
{27001}{}{Je prázdnı. Zdá se, e v nìm døív byly èasopisy pro pány.}
{27100}{}{Haraburdí}
{27101}{}{Tato matrace je v pøíšerném stavu. Ani krysy by v ní, nebo na ní, nespali.}
{27200}{}{Haraburdí}
{27201}{}{Manelská matrace, která u zaila i lepší dny.}
{27300}{}{Haraburdí}
{27301}{}{Hromada shnilého døeva. Nemá cenu ani své vlastní váhy. Vlastnì nemá vùbec ádnou cenu.}
{27400}{}{Haraburdí}
{27401}{}{Hromada døeva, ze kterého místy vykukují ohnuté zrezivìlé høebíky.}
{27500}{}{Krabice}
{27501}{}{Kupa starıch kartónovıch krabic. Nechce se ti vìøit, e nìco takového pøeilo tak dlouho.}
{27600}{}{Krabice}
{27601}{}{Kupa starıch kartónovıch krabic.}
{27700}{}{Haraburdí}
{27701}{}{Nìjaké haraburdí, které kdysi pravdìpodobnì byla matrace, ne ji znièilo poèasí.}
{27800}{}{Kameny}
{27900}{}{Kameny}
{28000}{}{Kameny}
{28100}{}{Su}
{28101}{}{Spousta úlomkù kamenù a kamínkù. Dávej si pozor, kam šlapeš!}
{28200}{}{Umyvadlo}
{28201}{}{Porcelánové umyvadlo, které u dávno nefunguje.}
{28300}{}{Umyvadlo}
{28301}{}{Rozbité porcelánové umyvadlo. Na dnì se drí trocha nahnìdlé vody, ve které plave mrtvá krysa.}
{28400}{}{Umyvadlo}
{28401}{}{Podle té velké díry ve spodní èásti usuzuješ, e je toto umyvadlo rozbité.}
{28500}{}{Umyvadlo}
{28501}{}{Rozbité porcelánové umyvadlo. Na dnì se drí trocha nahnìdlé vody, ve které plave mrtvá krysa.}
{28600}{}{Dopravní znaèka}
{28601}{}{Èervená dopravní znaèka, na které je velkımi tiskacími písmeny napsáno slovo STOP.}
{28700}{}{Dopravní znaèka}
{28701}{}{Èervená dopravní znaèka, na které je velkımi tiskacími písmeny napsáno slovo STOP. Díry po kulkách nejsou souèástí pùvodního vırobního procesu.}
{28800}{}{Semafor}
{28801}{}{Starodávná pomùcka pro øízení dopravy.}
{28900}{}{Semafor}
{28901}{}{Starodávná pomùcka pro øízení dopravy.}
{29000}{}{Semafor}
{29001}{}{Starodávná pomùcka pro øízení dopravy.}
{29100}{}{Poulièní lampa}
{29101}{}{Tato lampa poskytuje osvìtlení v noci nebo v temnıch prostorách.}
{29200}{}{Poulièní lampa}
{29201}{}{Tato lampa poskytuje osvìtlení v noci nebo v temnıch prostorách.}
{29300}{}{Poulièní lampa}
{29301}{}{Tato lampa poskytuje osvìtlení v noci nebo v temnıch prostorách.}
{29400}{}{Poulièní lampa}
{29401}{}{Tato lampa poskytuje osvìtlení v noci nebo v temnıch prostorách.}
{29500}{}{Poulièní lampa}
{29501}{}{Tato lampa by mohla osvìtlovat tmavou ulici, kdyby ovšem nebyla zcela rozbitá.}
{29600}{}{Poulièní lampa}
{29601}{}{Tato lampa by mohla osvìtlovat tmavou ulici, kdyby ovšem nebyla zcela rozbitá.}
{29700}{}{Poulièní lampa}
{29701}{}{Tato lampa by mohla osvìtlovat tmavou ulici, kdyby ovšem nebyla zcela rozbitá.}
{29800}{}{Ukazatel}
{29801}{}{Tento ukazatel kdysi oznamoval název ulice, ale písmena u dávno vybledla a jsou neèitelná.}
{29900}{}{Ukazatel}
{29901}{}{Tento ukazatel kdysi oznamoval název ulice, ale písmena u dávno vybledla a jsou neèitelná.}
{30000}{}{Stùl}
{30001}{}{Døevenı stùl ve slušném stavu.}
{30100}{}{Stùl}
{30101}{}{Døevenı stùl ve slušném stavu.}
{30200}{}{Stùl}
{30201}{}{Døevenı stùl v podprùmìrném stavu.}
{30300}{}{Stùl}
{30301}{}{Døevìnı stùl potaenı notnì poškrábanou a popraskanou plastikovou deskou.}
{30400}{}{Stùl}
{30401}{}{Døevìnı stùl natøenı odpornım odstínem zelené barvy. Nelze opravit.}
{30500}{}{Stùl}
{30501}{}{Nízkı kavárenskı stolek. Zvláštì vhodnı pro malé mutanty.}
{30600}{}{Stùl}
{30601}{}{Nízkı kavárenskı stolek. Zvláštì vhodnı pro malé mutanty.}
{30700}{}{Záchod}
{30701}{}{Ostré okraje mísy by ti urèitì dokázaly celou proceduru poøádnì znepøíjemnit.}
{30800}{}{Záchod}
{30801}{}{Tento záchod je rozbitı.}
{30900}{}{Záchod}
{30901}{}{Fuj! Ten, kdo tu byl naposled, po sobì nespláchl!}
{31000}{}{Záchod}
{31001}{}{Tento záchod je rozbitı a pro eny naprosto nepouitelnı.}
{31100}{}{Odpadky}
{31101}{}{Trubky napùl zahrabané v zemi. Tady nic zajímavého neuvidíš. Jdi dál.}
{31200}{}{Odpadky}
{31201}{}{Spousta støepù a jiného odpadu.}
{31300}{}{Odpadky}
{31301}{}{Spousta støepù a jiného odpadu.}
{31400}{}{Odpadky}
{31401}{}{Trubka je v pùlce zlomená. Vypadá to, e zrezivìla a pøelomila se vlastní vahou.}
{31500}{}{Odpadkovı koš}
{31501}{}{Koš na odpadky. Ještì stále na nìm lze rozeznat nápis "Udrujte naše ulice èisté!"}
{31600}{}{Strom}
{31601}{}{Uschlı strom.}
{31700}{}{Strom}
{31701}{}{Paøez. Nic vzrušujícího. Ve skuteènosti je to ta nejménì zajímavá vìc, na které kdy spoèinulo tvé oko.}
{31800}{}{Strom}
{31801}{}{Uschlı strom.}
{31900}{}{Strom}
{32000}{}{Strom}
{32100}{}{Strom}
{32200}{}{UNUSED.}
{32300}{}{Náklaïák}
{32301}{}{Trosky nákladního auta pohánìného dieselovım motorem. Tato hora eleza se u nikdy nepohne.}
{32400}{}{Náklaïák}
{32401}{}{Tomuto dieselovému náklaïáku u není pomoci. Ani ve snu.}
{32500}{}{Vana}
{32501}{}{Tato vana je rozbitá a prasklá.}
{32600}{}{Vana}
{32601}{}{Po bliším prozkoumání konstatuješ, e se v této vanì asi nevykoupeš.}
{32700}{}{Pisoár}
{32701}{}{Obyèejnı pisoár.}
{32800}{}{Pisoár}
{32801}{}{Obyèejnı pisoár.}
{32900}{}{Pisoár}
{32901}{}{Obyèejnı pisoár. Nic zvláštního.}
{33000}{}{Pisoár}
{33001}{}{Obyèejnı pisoár. Nic zvláštního.}
{33100}{}{Vodní nádr}
{33101}{}{Velkı zásobník na tekutiny. V tomto pøípadì to bude asi nádr na vodu.}
{33200}{}{Dveøe}
{33201}{}{Døevìné dveøe. Není na nich vùbec nic zajímavého.}
{33300}{}{Dveøe}
{33301}{}{Døevìné dveøe. Umoòují vstup a vıstup z budovy.}
{33400}{}{Nástìnná lampa}
{33401}{}{Tato lampa je v celkem slušném stavu.}
{33500}{}{Nástìnná lampa}
{33501}{}{Rozbitá lampa. Není ádnım pøekvapením, e nefunguje.}
{33600}{}{Nástìnná lampa}
{33601}{}{Tato lampa je v celkem slušném stavu.}
{33700}{}{Nástìnná lampa}
{33701}{}{Rozbitá lampa. Není ádnım pøekvapením, e nefunguje.}
{33800}{}{Nástìnná lampa}
{33801}{}{Tato lampa je v celkem slušném stavu.}
{33900}{}{Nástìnná lampa}
{33901}{}{Rozbitá lampa. Není ádnım pøekvapením, e nefunguje.}
{34000}{}{Nástìnná lampa}
{34001}{}{Tato lampa je v celkem slušném stavu.}
{34100}{}{Nástìnná lampa}
{34101}{}{Rozbitá lampa. Není ádnım pøekvapením, e nefunguje.}
{34200}{}{Dopravní znaèka}
{34201}{}{Toto je znaèka, která se pouívala k øízení dopravy.}
{34300}{}{Dopravní znaèka}
{34301}{}{Vybledlá znaèka na zkorodovaném sloupku.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{Pokud tohle vidíš, pošli stínost technickému návrháøi.}
{34500}{}{Podlaha}
{34600}{}{Dveøe}
{34601}{}{Zdobené døevìné dveøe. Musel je vyrobit opravdu šikovnı øemeslník.}
{34700}{}{Lavice}
{34701}{}{Tato lavice je podepøena velkımi kusy betonu. Sice to není dùleité, ale kdy tì to tak zajímá...}
{34800}{}{Schodištì}
{34801}{}{Schodištì vede smìrem nahoru.}
{34900}{}{Schodištì}
{34901}{}{Schodištì vede smìrem nahoru.}
{35000}{}{Schodištì}
{35001}{}{Schodištì vede smìrem nahoru.}
{35100}{}{Schodištì}
{35101}{}{Schodištì vede smìrem nahoru.}
{35200}{}{Schodištì}
{35201}{}{Schodištì vede smìrem nahoru.}
{35300}{}{Schodištì}
{35301}{}{Schodištì vede smìrem nahoru.}
{35400}{}{Schodištì}
{35401}{}{Schodištì vede smìrem nahoru.}
{35500}{}{Schodištì}
{35501}{}{Schodištì vede smìrem nahoru.}
{35600}{}{Schodištì}
{35601}{}{Schodištì vede smìrem dolù.}
{35700}{}{Stìna}
{35701}{}{Díváš se na vnìjší èást Katedrály.}
{35800}{}{Stìna}
{35801}{}{Díváš se na vnìjší èást Katedrály.}
{35900}{}{Stìna}
{35901}{}{Díváš se na vnìjší èást Katedrály.}
{36000}{}{Stìna}
{36001}{}{Díváš se na vnìjší èást Katedrály.}
{36100}{}{Závìs}
{36101}{}{Technologie vıroby je sice velice primitivní, ale svùj úèel splòuje tento závìs dokonale.}
{36200}{}{Závìs}
{36201}{}{Technologie vıroby je sice velice primitivní, ale svùj úèel splòuje tento závìs dokonale.}
{36300}{}{Mísa}
{36301}{}{Kvalitnì vyrobená døevìná mísa. Zdá se, e byla navrena ke tøídìní zrní.}
{36400}{}{Mísa}
{36401}{}{Kvalitnì vyrobená døevìná mísa.}
{36500}{}{Nádoba}
{36501}{}{Kvalitnì vyrobená nádoba.}
{36600}{}{Rostlina}
{36601}{}{Vypadá to, e jde o zmutovanou kapustu. Zøejmì jí prospívá teplé poèasí.}
{36700}{}{Rostlina}
{36701}{}{Vypadá to, e jde o zmutovanou kapustu. Zøejmì jí prospívá teplé poèasí.}
{36800}{}{Koleèko}
{36801}{}{Primitivní, ale velmi efektivní zemìdìlské koleèko.}
{36900}{}{Rostlina}
{36901}{}{Zmutovanı obilnı klas. Vypadá to, e se mu v tìchto podmínkách daøí.}
{37000}{}{Rostlina}
{37001}{}{Zmutovanı obilnı klas. Vypadá to, e se mu v tìchto podmínkách daøí.}
{37100}{}{Rostlina}
{37101}{}{Zmutovanı obilnı klas. Vypadá to, e se mu v tìchto podmínkách daøí.}
{37200}{}{Nádoba}
{37201}{}{Kvalitnì vyrobená nádoba z hlíny.}
{37300}{}{Hrábì}
{37301}{}{Tyto hrábì ti nepatøí. Stejnì tì nenapadá, k èemu by se daly pouít.}
{37400}{}{Hrábì}
{37401}{}{Tyto hrábì ti nepatøí. Stejnì tì nenapadá, k èemu by se daly pouít.}
{37500}{}{Hrábì}
{37501}{}{Tyto hrábì ti nepatøí. Stejnì tì nenapadá, k èemu by se daly pouít.}
{37600}{}{Koberec}
{37601}{}{Obyèejnı koberec. Tkalec byl oèividnì velmi talentovanı.}
{37700}{}{Koberec}
{37701}{}{Obyèejnı koberec. Tkalec byl oèividnì velmi talentovanı.}
{37800}{}{Koberec}
{37801}{}{Obyèejnı koberec. Tkalec byl oèividnì velmi talentovanı.}
{37900}{}{Lopata}
{37901}{}{Tato lopata ti nepatøí. Stejnì tì nenapadá, k èemu by se dala pouít.}
{38000}{}{Lopata}
{38001}{}{Tato lopata ti nepatøí. Stejnì tì nenapadá, k èemu by se dala pouít.}
{38100}{}{Lopata}
{38101}{}{Tato lopata ti nepatøí. Stejnì tì nenapadá, k èemu by se dala pouít.}
{38200}{}{Váza}
{38201}{}{Velmi hezká hlinìná váza.}
{38300}{}{Studna}
{38301}{}{Typická studna, která je k nalezení v pustinì.}
{38400}{}{Tyè}
{38401}{}{Bìná souèást stanové konstrukce.}
{38500}{}{Tyè}
{38501}{}{Bìná souèást stanové konstrukce.}
{38600}{}{Tyè}
{38601}{}{Bìná souèást stanové konstrukce.}
{38700}{}{Tyè}
{38701}{}{Bìná souèást stanové konstrukce.}
{38800}{}{Tyè}
{38801}{}{Bìná souèást stanové konstrukce.}
{38900}{}{Tyè}
{38901}{}{Bìná souèást stanové konstrukce.}
{39000}{}{Dveøe vaultu}
{39001}{}{Teï u je to jen ohromnı kus ocelového šrotu.}
{39100}{}{Stìna}
{39101}{}{Mechanismus zajišující otevírání a zavírání tìkıch dveøí vaultu byl nenávratnì poškozen.}
{39200}{}{Vıztuha}
{39201}{}{Tato vıztuha zesiluje ochrannou zeï.}
{39300}{}{Vıztuha}
{39301}{}{Tato vıztuha zesiluje ochrannou zeï.}
{39400}{}{Vıztuha}
{39401}{}{Tato vıztuha zesiluje ochrannou zeï.}
{39500}{}{Vıztuha}
{39501}{}{Tato vıztuha zesiluje ochrannou zeï.}
{39600}{}{eleznı sud}
{39601}{}{Rezavı eleznı sud. Je prázdnı.}
{39700}{}{eleznı sud}
{39701}{}{Podle dutého zvuku usuzuješ, e je tento sud nejspíš prázdnı.}
{39800}{}{elezné sudy}
{39801}{}{Podle dutého zvuku usuzuješ, e jsou tyto sudy nejspíš prázdné.}
{39900}{}{elezné sudy}
{39901}{}{Podle dutého zvuku usuzuješ, e jsou tyto sudy nejspíš prázdné.}
{40000}{}{Vzduchová ventilace}
{40001}{}{Vìtrací otvor ventilace podzemních prostor.}
{40100}{}{Bedna}
{40101}{}{Døevìná bedna. Je v celkem dobrém stavu.}
{40200}{}{Bedna}
{40201}{}{Jednoduchá døevìná bedna. Zachovalá.}
{40300}{}{Bedna}
{40301}{}{Tato bedna se zhroutila vlastní vahou.}
{40400}{}{Stùl}
{40401}{}{Obyèejnı pracovní stùl s poèítaèem.}
{40500}{}{Stùl}
{40501}{}{Obyèejnı pracovní stùl s poèítaèem.}
{40600}{}{Dveøe}
{40601}{}{Døevìné dveøe. Ve slušném stavu.}
{40700}{}{Sesuv}
{40701}{}{Spousta kamení. Víc, ne dokáeš unést.}
{40800}{}{Auto}
{40801}{}{Tento napùl potopenı automobil u nikdy nikdo neopraví.}
{40900}{}{Auto}
{40901}{}{Auto je trochu vlhké a nedá se opravit.}
{41000}{}{Auto}
{41001}{}{Toto auto nìkdo špatnì zaparkoval. Bohuel u se nedá opravit.}
{41100}{}{Haraburdí}
{41101}{}{Toto haraburdí u je znaènì poznamenáno pùsobením zamoøené moøské vody.}
{41200}{}{Haraburdí}
{41201}{}{Toto haraburdí se u témìø rozloilo.}
{41300}{}{Haraburdí}
{41301}{}{Pestrı vıbìr bezcenného šrotu.}
{41400}{}{Potrubí}
{41401}{}{Tìmito trubkami se kdysi èerpalo palivo z podzemních nádrí. Nebyly pouity u velmi dlouhou dobu.}
{41500}{}{Potrubí}
{41501}{}{Tìmito trubkami se kdysi èerpalo palivo z podzemních nádrí. Nebyly pouity u velmi dlouhou dobu.}
{41600}{}{Potrubí}
{41601}{}{Tìmito trubkami se kdysi èerpalo palivo z podzemních nádrí. Nebyly pouity u velmi dlouhou dobu.}
{41700}{}{Šachta vıtahu}
{41701}{}{Èást vıtahového systému.}
{41800}{}{Vìtrací šachta}
{41801}{}{Vìtrací šachta vede kamsi hluboko do lodi. Je poškozená.}
{41900}{}{Vıtah}
{41901}{}{Vıtah. Pouívá se k pøesunu nahoru a dolù do jinıch pater.}
{42000}{}{Šachta vıtahu}
{42001}{}{Šachta vede kamsi hluboko pod zem. Je poškozená.}
{42100}{}{Dveøe vıtahu}
{42101}{}{Tyto dveøe vedou do vıtahu. Pokud ho chceš pouít, musíš nejdøív otevøít tyto dveøe.}
{42200}{}{Potrubí}
{42201}{}{elezná trubka. Další detaily nejsou dùleité.}
{42300}{}{Hlína}
{42400}{}{Bedna}
{42500}{}{Bedna}
{42600}{}{Bedna}
{42700}{}{Bedna}
{42800}{}{Kameny}
{42801}{}{Hromada kamení. Nic zajímavého.}
{42900}{}{Kameny}
{42901}{}{Hromada kamení. Nic zajímavého.}
{43000}{}{Kameny}
{43001}{}{Malá hromádka kamení. Není na nich vùbec nic zajímavého.}
{43100}{}{Kameny}
{43101}{}{Hromádka kamení.}
{43200}{}{Kameny}
{43201}{}{Hromádka kamení.}
{43300}{}{Kameny}
{43301}{}{Hromádka kamení.}
{43400}{}{Kameny}
{43401}{}{Hromádka kamení.}
{43500}{}{Kameny}
{43501}{}{Hromádka kamení.}
{43600}{}{Dveøe vaultu}
{43601}{}{Tyto dveøe jsou podobné tìm ve Vaultu 13. Mechanismus dveøí byl vyøazen z provozu.}
{43700}{}{Dveøe}
{43701}{}{Døevìné dveøe vyztuené ornamentálními kovovımi vıztuhami s takøka fascinujícím designem.}
{43800}{}{Dveøe}
{43801}{}{Døevìné dveøe vyztuené ornamentálními kovovımi vıztuhami s takøka fascinujícím designem.}
{43900}{}{Nádre}
{43901}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44000}{}{Nádre}
{44001}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44100}{}{Nádre}
{44101}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44200}{}{Nádre}
{44201}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44300}{}{Nádre}
{44301}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44400}{}{Nádre}
{44401}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44500}{}{Nádre}
{44501}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44600}{}{Nádre}
{44601}{}{Podivné zaøízení. Vidíš obrovské nádre plné jakéhosi zeleného slizu, kterı vypadá dùleitì.}
{44700}{}{Stìna}
{44800}{}{Dveøe}
{44801}{}{Bezpeènostní pancéøované dveøe.}
{44900}{}{Nukleární hlavice}
{45000}{}{Studna}
{45001}{}{Typická studna, která je k nalezení v pustinì.}
{45100}{}{Hrací stùl}
{45101}{}{Hrací stùl.}
{45200}{}{Hrací stùl}
{45201}{}{Hrací stùl.}
{45300}{}{Hrací stùl}
{45301}{}{Hrací stùl.}
{45400}{}{Hrací stùl}
{45401}{}{Hrací stùl.}
{45500}{}{Hrací stùl}
{45501}{}{Hrací stùl.}
{45600}{}{Hrací stùl}
{45601}{}{Hrací stùl.}
{45700}{}{Hrací stùl}
{45701}{}{Hrací stùl.}
{45800}{}{Hrací stùl}
{45801}{}{Hrací stùl.}
{45900}{}{Hrací stùl}
{45901}{}{Hrací stùl.}
{46000}{}{Hrací stùl}
{46001}{}{Hrací stùl.}
{46100}{}{Kámen}
{46101}{}{Malı kámen, kterı je pro tento pøíbìh naprosto nezajímavı.}
{46200}{}{Kámen}
{46300}{}{Kámen}
{46400}{}{Kámen}
{46500}{}{Hrací automat}
{46501}{}{Primitivní zaøízení, do kterého lidé hází peníze.}
{46600}{}{Hrací automat}
{46601}{}{Primitivní zaøízení, do kterého lidé hází peníze.}
{46700}{}{Vstup}
{46800}{}{Šachta}
{46900}{}{Šachta}
{47000}{}{Dveøe vıtahu}
{47100}{}{Okno}
{47101}{}{Toto okno je vyrobené z voskového papíru namísto skla.}
{47200}{}{Okno}
{47201}{}{Toto okno je vyrobené z voskového papíru namísto skla.}
{47300}{}{Okno}
{47301}{}{Toto okno je vyrobené z voskového papíru namísto skla.}
{47400}{}{Okno}
{47401}{}{Toto okno je vyrobené z voskového papíru namísto skla.}
{47500}{}{Dveøe}
{47501}{}{Velká garáová vrata. Jsou zablokována zevnitø.}
{47600}{}{Dveøe}
{47601}{}{Velká garáová vrata. Jsou zablokována zevnitø.}
{47700}{}{Dveøe}
{47701}{}{Velká garáová vrata. Jsou zablokována zevnitø. Je na nich nápis POUZE PRO NAKLÁDÁNÍ.}
{47800}{}{Dveøe}
{47801}{}{Velká garáová vrata. Jsou zablokována zevnitø.}
{47900}{}{Dveøe}
{47901}{}{Velká garáová vrata. Jsou zablokována zevnitø.}
{48000}{}{Dveøe}
{48001}{}{Velká garáová vrata. Jsou zablokována zevnitø. Je na nich nápis POUZE PRO NAKLÁDÁNÍ.}
{48100}{}{Dveøe}
{48101}{}{Tyto dveøe nápadnì pøipomínají dveøe do skladištì.}
{48200}{}{Dveøe}
{48201}{}{Tyto dveøe nápadnì pøipomínají dveøe do skladištì.}
{48300}{}{Korouhvièka}
{48301}{}{Jednoduchá korouhvièka, která umoòuje obyvatelùm pustin v omezené míøe pøedpovídat poèasí.}
{48400}{}{Oltáø}
{48401}{}{Jednoduchı oltáø ze zdobeného døeva.}
{48500}{}{Pódium}
{48501}{}{Obyèejnı øeènickı pult.}
{48600}{}{Oltáø}
{48700}{}{Monitor}
{48701}{}{Velká èernobílá televize. Pøíjem je docela ucházející vzhledem k tomu, e je umístìna uvnitø a nemá anténu.}
{48800}{}{Monitor}
{48801}{}{Velká èernobílá televize. Èlovìk v rouchu na nìm horeènatì pøednáší náboenská dogmata.}
{48900}{}{Silové pole}
{48901}{}{Silné energetické pole.}
{49000}{}{Silové pole}
{49001}{}{Silné energetické pole.}
{49100}{}{Silové pole}
{49101}{}{Silné energetické pole.}
{49200}{}{Silové pole}
{49201}{}{Silné energetické pole.}
{49300}{}{Stùl}
{49301}{}{Docela obyèejnı døevìnı stùl.}
{49400}{}{Stùl}
{49401}{}{Docela obyèejnı døevìnı stùl.}
{49500}{}{Stùl}
{49501}{}{Docela obyèejnı døevìnı stùl.}
{49600}{}{Stùl}
{49601}{}{Docela obyèejnı døevìnı stùl.}
{49700}{}{Stùl}
{49701}{}{Docela obyèejnı døevìnı stùl.}
{49800}{}{Stùl}
{49801}{}{Docela obyèejnı døevìnı stùl.}
{49900}{}{Kameny}
{49901}{}{Hromada kamení. Nic zajímavého.}
{50000}{}{Kameny}
{50001}{}{Hromada kamení. Nic zajímavého.}
{50100}{}{Kameny}
{50101}{}{Malá hromádka kamení. Není na nich vùbec nic zajímavého.}
{50200}{}{Kameny}
{50201}{}{Hromádka kamení.}
{50300}{}{Kameny}
{50301}{}{Hromádka kamení.}
{50400}{}{Kameny}
{50401}{}{Hromádka kamení.}
{50500}{}{Oltáø}
{50501}{}{Jednoduchı oltáø ze zdobeného døeva.}
{50600}{}{Oltáø}
{50601}{}{Jednoduchı oltáø ze zdobeného døeva.}
{50700}{}{Oltáø}
{50701}{}{Jednoduchı oltáø ze zdobeného døeva.}
{50800}{}{Oltáø}
{50801}{}{Jednoduchı oltáø ze zdobeného døeva.}
{50900}{}{Su}
{50901}{}{Sutiny ze zøíceného stropu. Lano vede zpìt na povrch.}
{51000}{}{Kameny}
{51001}{}{fgfgfg}
{51100}{}{UNUSED.}
{51200}{}{UNUSED.}
{51300}{}{UNUSED.}
{51400}{}{UNUSED.}
{51500}{}{UNUSED.}
{51600}{}{Stùl}
{51601}{}{Tento velkı stùl vypadá dùleitì. e by se tu poøádaly schùze?}
{51700}{}{Stùl}
{51701}{}{Tento velkı stùl vypadá dùleitì. e by se tu poøádaly schùze?}
{51800}{}{Stùl}
{51801}{}{Tento velkı stùl vypadá dùleitì. e by se tu poøádaly schùze?}
{51900}{}{Stùl}
{51901}{}{Tento velkı stùl vypadá dùleitì. e by se tu poøádaly schùze?}
{52000}{}{Stùl}
{52001}{}{Tento velkı stùl vypadá dùleitì. e by se tu poøádaly schùze?}
{52100}{}{Stùl}
{52101}{}{Tento velkı stùl vypadá dùleitì. e by se tu poøádaly schùze?}
{52200}{}{Oltáø}
{52201}{}{Tento oltáø pouívá Bratrstvo Oceli. Jasnì poznáváš jejich symbol.}
{52300}{}{Oltáø}
{52301}{}{Tento oltáø pouívá Bratrstvo Oceli. Jasnì poznáváš jejich symbol.}
{52400}{}{Oltáø}
{52401}{}{Tento oltáø pouívá Bratrstvo Oceli. Jasnì poznáváš jejich symbol.}
{52500}{}{Lavice}
{52501}{}{Sice krásnì navrená, ale u na pohled dìsnì nepohodlná lavice.}
{52600}{}{Pódium}
{52601}{}{Døevìné pódium se zabudovanou nápovìdou.}
{52700}{}{Vozík}
{52701}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{52800}{}{Vozík}
{52801}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{52900}{}{Vozík}
{52901}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{53000}{}{Vozík}
{53001}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{53100}{}{Vozík}
{53101}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{53200}{}{Vozík}
{53201}{}{Karavanovı vozík vyrobenı z vrakù starıch automobilù.}
{53300}{}{ínìnka}
{53301}{}{Cvièební ínìnka.}
{53400}{}{ínìnka}
{53401}{}{Cvièební ínìnka.}
{53500}{}{ínìnka}
{53501}{}{Cvièební ínìnka.}
{53600}{}{ínìnka}
{53601}{}{Cvièební ínìnka.}
{53700}{}{Boxovací pytel}
{53701}{}{Boxovací pytel znaèky Silák Béïa(tm).}
{53800}{}{Cvièební stroj}
{53801}{}{Cvièební pomùcka.}
{53900}{}{Cvièební stroj}
{54000}{}{Bìeckı pás}
{54001}{}{Cvièební pomùcka.}
{54100}{}{Bìeckı pás}
{54101}{}{Cvièební pomùcka.}
{54200}{}{Lavice na benchpress}
{54201}{}{Cvièební pomùcka.}
{54300}{}{Lavice na benchpress}
{54301}{}{Cvièební pomùcka.}
{54400}{}{Prkna}
{54401}{}{Silná døevìná prkna pevnì svázaná dohromady.}
{54500}{}{Prkna}
{54501}{}{Silná døevìná prkna pevnì svázaná dohromady.}
{54600}{}{Stùl na ruletu}
{54601}{}{Hrací stùl.}
{54700}{}{Stùl na ruletu}
{54701}{}{Hrací stùl.}
{54800}{}{Stùl na ruletu}
{54801}{}{Hrací stùl.}
{54900}{}{Stùl na ruletu}
{54901}{}{Hrací stùl.}
{55000}{}{Stùl na ruletu}
{55001}{}{Hrací stùl.}
{55100}{}{Sud}
{55101}{}{Prázdnı eleznı sud, kterı má na boku namalován jasnì lutı symbol varování pøed radiací.}
{55200}{}{Sud}
{55201}{}{Tento sud obsahuje podivnou zelenì fosforeskující hmotu. A lutı nukleární symbol na boku ti napovídá, co by to asi tak mohlo bıt.}
{55300}{}{Poèítaè}
{55301}{}{Velice modernì vypadající poèítaè.}
{55400}{}{Poèítaè}
{55401}{}{Velice modernì vypadající poèítaè.}
{55500}{}{Suspenzní nádr}
{55501}{}{Nìjakı lékaøskı nebo vızkumnı pøístroj. Vypadá to, e by se do nìj mohlo vejít lidské nebo i vìtší tìlo.}
{55600}{}{Rozbitá suspenzní nádr}
{55601}{}{Zcela znièené zaøízení. Nelze opravit.}
{55700}{}{Hlavní poèítaè}
{55701}{}{Velikı superpoèítaè. Pravdìpodobnì nejrychlejší poèítaè jakı existuje.}
{55800}{}{Podpùrná plošina}
{55801}{}{Tato plošina udruje superpoèítaè nad nádrí s chladícím médiem.}
{55900}{}{Dont use}
{56000}{}{Dont use}
{56100}{}{Postel}
{56101}{}{Vojenská palanda. Vypadá velmi nepohodlnì a prostìradlo je napnuté jako kšandy.}
{56200}{}{Postel}
{56201}{}{Vojenská palanda. Vypadá velmi nepohodlnì a prostìradlo je napnuté jako kšandy.}
{56300}{}{Postel}
{56301}{}{Vojenská palanda. Vypadá velmi nepohodlnì a prostìradlo je napnuté jako kšandy.}
{56400}{}{Kabel}
{56401}{}{Vypadá to jako nìjakı sériovı kabel.}
{56500}{}{Kabel}
{56501}{}{Vypadá to jako nìjakı sériovı kabel.}
{56600}{}{Cedule}
{56601}{}{Nápis BAR je asi víc ne vımluvnı, ne?}
{56700}{}{Trám}
{56701}{}{Nad kráterem je upevnìn silnı trám.}
{56800}{}{Trám}
{56801}{}{K trámu je pøipevnìné lano. Zdá se, e u teï mùeš sešplhat dovnitø kráteru.}
{56900}{}{Police}
{56901}{}{Vidíš naprosto prázdné elezné police.}
{57000}{}{Police}
{57001}{}{Vidíš naprosto prázdné elezné police.}
{57100}{}{Police}
{57101}{}{Vidíš naprosto prázdné elezné police.}
{57200}{}{Police}
{57201}{}{Vidíš naprosto prázdné elezné police.}
{57300}{}{Køoví}
{57301}{}{Nìjaká pouštní rostlina. V tomto pøíbìhu nehraje ádnou vıznamnou roli.}
{57400}{}{Køoví}
{57401}{}{Nìjaká pouštní rostlina.}
{57500}{}{Køoví}
{57501}{}{Nìjaká pouštní rostlina.}
{57600}{}{Zem}
{57601}{}{Z této vıšky je na Boneyard pøekrásnı vıhled. Z té ohromné vıšky máš opravdu dobrı pocit.}
{57700}{}{Zem}
{57701}{}{Z této vıšky je na Boneyard pøekrásnı vıhled.}
{57800}{}{Stìna}
{57801}{}{Pìknı vıhled z vnìjší strany Katedrály.}
{57900}{}{Stìna}
{57901}{}{Pìknı vıhled z vnìjší strany Katedrály.}
{58000}{}{Stìna}
{58001}{}{Pìknı vıhled z vnìjší strany Katedrály.}
{58100}{}{Dveøe}
{58101}{}{Tyto dveøe se sem náramnì hodí.}
{58200}{}{Cedule}
{58201}{}{Na ceduli stojí "Darkwaterùv obchod."}
{58300}{}{ebøík}
{58301}{}{ebøík vede nìkam dolù do temnoty.}
{58400}{}{ebøík}
{58401}{}{ebøík vede nìkam dolù do temnoty.}
{58500}{}{Stroj}
{58501}{}{Vypadá to jako starı tiskaøskı stroj.}
{58600}{}{Stroj}
{58601}{}{Vypadá to jako starı tiskaøskı stroj.}
{58700}{}{Stroj}
{58701}{}{Vypadá to jako starı tiskaøskı stroj.}
{58800}{}{Stroj}
{58801}{}{Vypadá to jako starı tiskaøskı stroj.}
{58900}{}{Stroj}
{58901}{}{Vypadá to jako starı tiskaøskı stroj.}
{59000}{}{Staré elezo}
{59001}{}{Kovovı šrot.}
{59100}{}{Stùl}
{59101}{}{Kovovı stùl v dobrém stavu s drákou uprostøed.}
{59200}{}{Stùl}
{59201}{}{Kovovı stùl v dobrém stavu s drákou uprostøed.}
{59300}{}{Stùl}
{59301}{}{Kovovı stùl pokrytı jakousi biomasou.}
{59400}{}{Stùl}
{59401}{}{Kovovı stùl pokrytı jakousi biomasou.}
{59500}{}{Stùl}
{59501}{}{Kovovı stùl pokrytı jakousi biomasou.}
{59600}{}{Nástìnka}
{59601}{}{Na nástìnce je pøipíchnuto mnoství zpráv pro zamìstnance. Vypadá pouívanì.}
{59700}{}{Bouda}
{59701}{}{Aèkoliv je tato bouda stará pøes sto let, je stále v perfektním stavu.}
{59800}{}{Cedule}
{59801}{}{Cedule s nápisem: Smíšené zboí.}
{59900}{}{Cedule}
{59901}{}{Cedule s nápisem: Smíšené zboí.}
{60000}{}{Cedule}
{60001}{}{Na ceduli stojí: Trištì.}
{60100}{}{Sliz}
{60101}{}{U od pohledu ivotu nebezpeèné. Jestli se chceš by jen namoèit, vezmi si odolnı neoprén.}
{60200}{}{Sliz}
{60201}{}{U od pohledu ivotu nebezpeèné. Jestli se chceš by jen namoèit, vezmi si odolnı neoprén.}
{60300}{}{Sliz}
{60301}{}{U od pohledu ivotu nebezpeèné. Jestli se chceš by jen namoèit, vezmi si odolnı neoprén.}
{60400}{}{Stùl}
{60401}{}{Pìknı kovovı stùl.}
{60500}{}{Stùl}
{60501}{}{Pìknı kovovı stùl.}
{60600}{}{Stùl}
{60601}{}{Pìknı kovovı stùl.}
{60700}{}{Stùl}
{60701}{}{Pìknı kovovı stùl.}
{60800}{}{Stùl}
{60801}{}{S tímto kovovım stolem se nezacházelo dobøe. Je samá rez.}
{60900}{}{Stùl}
{60901}{}{Dobøe vypadající, ale trochu zrezivìlı kovovı stùl.}
{61000}{}{Stùl}
{61001}{}{Dobøe vypadající, ale trochu zrezivìlı kovovı stùl.}
{61100}{}{Stùl}
{61101}{}{Dobøe vypadající, ale trochu zrezivìlı kovovı stùl.}
{61200}{}{Ohništì}
{61201}{}{Oheò plápolá.}
{61300}{}{Zrcadlo}
{61301}{}{Chvíli se na sebe díváš.}
{61400}{}{Zrcadlo}
{61401}{}{Chvíli se na sebe díváš.}
{61500}{}{Umyvadlo}
{61501}{}{Umyvadlo je plnì funkèní. A kupodivu je i pìkné a èisté.}
{61600}{}{Záchod}
{61601}{}{Záchod je dokonale èistı. A funguje.}
{61700}{}{Pisoár}
{61701}{}{Funkèní mušle.}
{61800}{}{Záchod}
{61801}{}{Mít úchylku na záchody, tak je tento jasná volba.}
{61900}{}{Umyvadlo}
{61901}{}{Umyvadlo je v perfektním stavu.}
{62000}{}{Pisoár}
{62001}{}{Mušle je v perfektním stavu.}
{62100}{}{Sprcha}
{62101}{}{Sprcha ve vojenském stylu. Nic pro ty, co mají rádi soukromí.}
{62200}{}{Sprcha}
{62201}{}{Sprcha ve vojenském stylu. Nic pro ty, co mají rádi soukromí.}
{62300}{}{Sprcha}
{62301}{}{Sprcha ve vojenském stylu. Nic pro ty, co mají rádi soukromí.}
{62400}{}{Sprcha}
{62401}{}{Sprcha ve vojenském stylu. Nic pro ty, co mají rádi soukromí.}
{62500}{}{Sprcha}
{62501}{}{Sprcha ve vojenském stylu. Nic pro ty, co mají rádi soukromí.}
{62600}{}{Sprcha}
{62601}{}{Sprcha ve vojenském stylu. Nic pro ty, co mají rádi soukromí.}
{62700}{}{Postel}
{62701}{}{Vypadá velmi pohodlnì.}
{62800}{}{Postel}
{62801}{}{Vypadá velmi pohodlnì.}
{62900}{}{Postel}
{62901}{}{Palanda se zesílenou konstrukcí.}
{63000}{}{Postel}
{63001}{}{Palanda se zesílenou konstrukcí.}
{63100}{}{Postel}
{63101}{}{Palanda se zesílenou konstrukcí.}
{63200}{}{Terminál}
{63300}{}{Terminál}
{63400}{}{Vlajka}
{63401}{}{Tato vlajka je symbolem Dìtí Katedrály.}
{63500}{}{Vlajka}
{63501}{}{Tato vlajka je symbolem Dìtí Katedrály.}
{63600}{}{Vlajka}
{63601}{}{Tato vlajka je symbolem Dìtí Katedrály.}
{63700}{}{Poèítaè}
{63701}{}{Velkı poèítaè.}
{63800}{}{Poèítaè}
{63801}{}{Velkı poèítaè.}
{63900}{}{Poèítaè}
{63901}{}{Velkı poèítaè.}
{64000}{}{Terminál}
{64001}{}{Terminál k velkému poèítaèi.}
{64100}{}{Mrtvola}
{64101}{}{Zdá se, e tento èlovìk zemøel velmi bolestivou smrtí.}
{64200}{}{Mrtvola}
{64201}{}{Zdá se, e tento èlovìk zemøel velmi bolestivou smrtí.}
{64300}{}{Mrtvola}
{64301}{}{Zdá se, e tento èlovìk zemøel velmi bolestivou smrtí.}
{64400}{}{Mrtvola}
{64401}{}{Zdá se, e tento èlovìk zemøel velmi bolestivou smrtí.}
{64500}{}{Dveøe}
{64501}{}{Dveøe od cely.}
{64600}{}{Terminál}
{64700}{}{Terminál}
{64800}{}{Vysokozdvinı vozík}
{64801}{}{Je nefunkèní.}
{64900}{}{Vysokozdvinı vozík}
{64901}{}{Je nefunkèní.}
{65000}{}{Zaøízení}
{65100}{}{Operaèní stùl}
{65101}{}{Stùl je velmi zrezivìlı a dráka pro odtok krve v prostøedku stolu je úplnì zanesená.}
{65200}{}{Operaèní stùl}
{65201}{}{Stùl je velmi zrezivìlı.}
{65300}{}{Brána}
{65301}{}{V bránì je závora, kterou se dá pohybovat nahoru a dolù.}
{65400}{}{Potrubí}
{65500}{}{Potrubí}
{65600}{}{Generátor}
{65601}{}{Generátor Wattz ElectroBox. Standardnì pouívanı jako záloní generátor v pøedváleèném období.}
{65700}{}{Tank}
{65701}{}{Velká nádr na vodu. Vypadá docela udrovanì, co je dobøe.}
{65800}{}{Policejní budka}
{65801}{}{Policejní budka z Velké Británie z období cca okolo roku 1960.}
{65900}{}{Stùl}
{65901}{}{Kvalitnì vyrobenı stùl. Ruèní práce, ale pøesto vypadá mnohem lépe ne všechny ostatní stoly.}
{66000}{}{Stùl}
{66001}{}{Kvalitnì vyrobenı stùl. Ruèní práce, ale pøesto vypadá mnohem lépe ne všechny ostatní stoly.}
{66100}{}{Stùl}
{66101}{}{Kvalitnì vyrobenı stùl. Ruèní práce, ale pøesto vypadá mnohem lépe ne všechny ostatní stoly.}
{66200}{}{idle}
{66201}{}{Hezká idle.}
{66300}{}{idle}
{66301}{}{Hezká idle.}
{66400}{}{idle}
{66401}{}{Hezká idle.}
{66500}{}{idle}
{66501}{}{Hezká idle.}
{66600}{}{idle}
{66601}{}{Hezká idle.}
{66700}{}{idle}
{66701}{}{Hezká idle.}
{66800}{}{idle}
{66801}{}{Hezká idle.}
{66900}{}{idle}
{66901}{}{Hezká idle.}
{67000}{}{idle}
{67001}{}{Hezká idle.}
{67100}{}{idle}
{67101}{}{Hezká idle.}
{67200}{}{idle}
{67201}{}{Hezká idle.}
{67300}{}{idle}
{67301}{}{Hezká idle.}
{67400}{}{idle}
{67401}{}{Hezká idle.}
{67500}{}{idle}
{67501}{}{Hezká idle.}
{67600}{}{idle}
{67601}{}{Hezká idle.}
{67700}{}{idle}
{67701}{}{Hezká idle.}
{67800}{}{Postel}
{67801}{}{Hezká postel.}
{67900}{}{Postel}
{67901}{}{Hezká postel.}
{68000}{}{Postel}
{68001}{}{Hezká postel.}
{68100}{}{Postel}
{68101}{}{Hezká postel.}
{68200}{}{Kamna}
{68201}{}{Funkèní kamna na døevo.}
{68300}{}{Kamna}
{68301}{}{Funkèní kamna na døevo.}
{68400}{}{Kamna}
{68401}{}{Funkèní kamna na døevo.}
{68500}{}{Kamna}
{68501}{}{Funkèní kamna na døevo.}
{68600}{}{Znièenı stojan}
{68700}{}{Zøícenı vchod}
{68800}{}{Kameny}
{68801}{}{Velká hromada kamení. Tento zával rozhodnì nevznikl pøirozenou cestou.}
{68900}{}{Kameny}
{68901}{}{Velká hromada kamení. Tento zával rozhodnì nevznikl pøirozenou cestou.}
{69000}{}{Záchod}
{69001}{}{Primitivní, ale provozuschopná toaleta. V díøe je poloeno nìkolik listù nìjaké rostliny na potlaèení zápachu.}
{69100}{}{Hory}
{69101}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{69200}{}{Hory}
{69201}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{69300}{}{Hory}
{69301}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{69400}{}{Hory}
{69401}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{69500}{}{Hory}
{69501}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{69600}{}{Hory}
{69601}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{69700}{}{Mazlavá hmota}
{69701}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{69800}{}{Mazlavá hmota}
{69801}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{69900}{}{Mazlavá hmota}
{69901}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70000}{}{Mazlavá hmota}
{70001}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70100}{}{Mazlavá hmota}
{70101}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70200}{}{Mazlavá hmota}
{70201}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70300}{}{Mazlavá hmota}
{70301}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70400}{}{Mazlavá hmota}
{70401}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70500}{}{Mazlavá hmota}
{70501}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70600}{}{Mazlavá hmota}
{70601}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70700}{}{Mazlavá hmota}
{70701}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70800}{}{Mazlavá hmota}
{70801}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{70900}{}{Mazlavá hmota}
{70901}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71000}{}{Mazlavá hmota}
{71001}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71100}{}{Mazlavá hmota}
{71101}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71200}{}{Mazlavá hmota}
{71201}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71300}{}{Mazlavá hmota}
{71301}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71400}{}{Mazlavá hmota}
{71401}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71500}{}{Mazlavá hmota}
{71501}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71600}{}{Mazlavá hmota}
{71601}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71700}{}{Mazlavá hmota}
{71701}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71800}{}{Mazlavá hmota}
{71801}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{71900}{}{Mazlavá hmota}
{71901}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72000}{}{Mazlavá hmota}
{72001}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72100}{}{Mazlavá hmota}
{72101}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72200}{}{Mazlavá hmota}
{72201}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72300}{}{Mazlavá hmota}
{72301}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72400}{}{Mazlavá hmota}
{72401}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72500}{}{Mazlavá hmota}
{72501}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72600}{}{Mazlavá hmota}
{72601}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72700}{}{Mazlavá hmota}
{72701}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72800}{}{Mazlavá hmota}
{72801}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{72900}{}{Mazlavá hmota}
{72901}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73000}{}{Mazlavá hmota}
{73001}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73100}{}{Mazlavá hmota}
{73101}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73200}{}{Mazlavá hmota}
{73201}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73300}{}{Mazlavá hmota}
{73301}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73400}{}{Mazlavá hmota}
{73401}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73500}{}{Mazlavá hmota}
{73501}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73600}{}{Mazlavá hmota}
{73601}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73700}{}{Mazlavá hmota}
{73701}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73800}{}{Mazlavá hmota}
{73801}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{73900}{}{Mazlavá hmota}
{73901}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74000}{}{Mazlavá hmota}
{74001}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74100}{}{Mazlavá hmota}
{74101}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74200}{}{Mazlavá hmota}
{74201}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74300}{}{Mazlavá hmota}
{74301}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74400}{}{Mazlavá hmota}
{74401}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74500}{}{Mazlavá hmota}
{74501}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74600}{}{Mazlavá hmota}
{74601}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74700}{}{Mazlavá hmota}
{74701}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74800}{}{Mazlavá hmota}
{74801}{}{Vidíš nìjakou podivnou a nebezpeènì vypadající biologickou hmotu.}
{74900}{}{Poèítaè}
{74901}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75000}{}{Poèítaè}
{75001}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75100}{}{Poèítaè}
{75101}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75200}{}{Poèítaè}
{75201}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75300}{}{Poèítaè}
{75301}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75400}{}{Poèítaè}
{75401}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75500}{}{Poèítaè}
{75501}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75600}{}{Poèítaè}
{75601}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75700}{}{Poèítaè}
{75701}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75800}{}{Poèítaè}
{75801}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{75900}{}{Poèítaè}
{75901}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{76000}{}{Poèítaè}
{76001}{}{Pøes všechno to svinstvo se k tomu poèítaèi nedá skoro dostat.}
{76100}{}{Monitory}
{76101}{}{Kvùli podivnému slizu rozteklému pøes obrazovky nedokáeš z monitoru nic pøeèíst.}
{76200}{}{Monitory}
{76201}{}{Kvùli podivnému slizu rozteklému pøes obrazovky nedokáeš z monitoru nic pøeèíst.}
{76300}{}{Monitory}
{76301}{}{Kvùli podivnému slizu rozteklému pøes obrazovky nedokáeš z monitoru nic pøeèíst.}
{76400}{}{Monitory}
{76401}{}{Kvùli podivnému slizu rozteklému pøes obrazovky nedokáeš z monitoru nic pøeèíst.}
{76500}{}{UNUSED ART}
{76600}{}{UNUSED ART}
{76700}{}{Podlaha}
{76800}{}{Bomba}
{76801}{}{Toto je atomová bomba. Vypadá nebezpeènì u jenom tím, jak si tu tiše leí.}
{76900}{}{Stojan}
{76901}{}{Stojan na atomovou bombu.}
{77000}{}{Poèítaèová konzole}
{77001}{}{Toto je ovládací poèítaè atomové bomby. Vypadá velmi zabezpeèenì. Je tu také dráka pro klíè podivného tvaru.}
{77100}{}{Kabely}
{77101}{}{Tyto kabely propojují bombu s poèítaèem.}
{77200}{}{idle}
{77201}{}{Na této idli není nic zvláštního.}
{77300}{}{idle}
{77301}{}{Na této idli není nic zvláštního.}
{77400}{}{idle}
{77401}{}{Na této idli není nic zvláštního.}
{77500}{}{idle}
{77501}{}{Na této idli není nic zvláštního.}
{77600}{}{idle}
{77601}{}{Na této idli není nic zvláštního.}
{77700}{}{idle}
{77701}{}{Na této idli není nic zvláštního.}
{77800}{}{idle}
{77801}{}{Na této idli není nic zvláštního.}
{77900}{}{idle}
{77901}{}{Na této idli není nic zvláštního.}
{78000}{}{Sloup}
{78001}{}{Opìrnı pilíø.}
{78100}{}{Sloup}
{78101}{}{Opìrnı pilíø.}
{78200}{}{Sloup}
{78201}{}{Opìrnı pilíø.}
{78300}{}{Sloup}
{78301}{}{Opìrnı pilíø.}
{78400}{}{Postel}
{78401}{}{Tato postel je v ubohém stavu.}
{78500}{}{Postel}
{78501}{}{Tato postel je ve velmi bídném stavu.}
{78600}{}{Postel}
{78601}{}{Tato postel je v bídném stavu.}
{78700}{}{Postel}
{78701}{}{ato postel je v docela špatném stavu.}
{78800}{}{Monitory}
{78801}{}{Tyto monitory jsou rozbité a nefungují.}
{78900}{}{Monitory}
{78901}{}{Tyto monitory jsou rozbité a nefungují.}
{79000}{}{Monitory}
{79001}{}{Tyto monitory jsou rozbité a nefungují.}
{79100}{}{Monitory}
{79101}{}{Tyto monitory jsou rozbité a nefungují.}
{79200}{}{Vìtrací otvor}
{79201}{}{Z ventilace vychází jen slabı závan èerstvého vzduchu.}
{79300}{}{Vìtrací otvor}
{79301}{}{Nevychází z ní témìø ádnı èerstvı vzduch.}
{79400}{}{Vìtrací otvor}
{79401}{}{Z ventilace nevychází ádnı èerstvı vzduch.}
{79500}{}{Vìtrací otvor}
{79501}{}{Z ventilace vychází jen slabouèkı závan èerstvého vzduchu.}
{79600}{}{Stùl}
{79601}{}{Na tomto stolu není nic zvláštního, tedy a na to, e je témìø znièenı.}
{79700}{}{Stùl}
{79701}{}{Tento stùl je znaènì poškozen.}
{79800}{}{Stùl}
{79801}{}{Tento stùl je ve velmi špatném stavu.}
{79900}{}{Stùl}
{79901}{}{Není ádnı dùvod prohledávat tento stùl.}
{80000}{}{Monitory}
{80001}{}{Obrazovky jsou znièené.}
{80100}{}{Monitory}
{80101}{}{Tyto obrazovky u asi nikdo neopraví.}
{80200}{}{Monitor}
{80201}{}{Obrazovka je prasklá a rozbitá.}
{80300}{}{Monitor}
{80301}{}{S roztøíštìnou obrazovkou je tento monitor k nièemu.}
{80400}{}{Poèítaè}
{80401}{}{Tento poèítaè je rozbitı.}
{80500}{}{Poèítaè}
{80501}{}{Tento poèítaè je rozbitı.}
{80600}{}{Poèítaè}
{80601}{}{Tento poèítaè je rozbitı.}
{80700}{}{idle}
{80701}{}{Tato idle je znièená.}
{80800}{}{idle}
{80801}{}{Tato idle je znièená.}
{80900}{}{idle}
{80901}{}{Tato idle je znièená.}
{81000}{}{idle}
{81001}{}{Tato idle je znièená.}
{81100}{}{Vìtrací otvor}
{81101}{}{Tato ventilace je poškozená natolik, e u se nedá opravit.}
{81200}{}{Vìtrací otvor}
{81201}{}{Tato ventilace je poškozená natolik, e u se nedá opravit.}
{81300}{}{Vìtrací otvor}
{81301}{}{Tato ventilace je zcela nefunkèní.}
{81400}{}{Poèítaè}
{81401}{}{Zdá se, e tento poèítaè mele z posledního.}
{81500}{}{Poèítaè}
{81501}{}{Zdá se, e tento poèítaè mele z posledního.}
{81600}{}{Monitor}
{81601}{}{Tento monitor mele z posledního.}
{81700}{}{Monitor}
{81701}{}{Tento monitor mele z posledního.}
{81800}{}{Poèítaè}
{81801}{}{Tento poèítaè je nefunkèní.}
{81900}{}{Poèítaè}
{81901}{}{Tento poèítaè je nefunkèní.}
{82000}{}{Monitor}
{82001}{}{Tento monitor je nefunkèní.}
{82100}{}{Monitor}
{82101}{}{Tento monitor je nefunkèní.}
{82200}{}{Vstup}
{82201}{}{Velmi hezkı vstup. Drí dobøe dveøe.}
{82300}{}{Monitory}
{82301}{}{Monitory jsou v dobrém stavu.}
{82400}{}{Monitory}
{82401}{}{Monitory jsou v dobrém stavu.}
{82500}{}{Stìna}
{82600}{}{Trezorové dveøe}
{82601}{}{Velmi robustní trezorové dveøe. Vypadají nedobytnì.}
{82700}{}{Lehké}
{82701}{}{Bezpeènostní svìtlo.}
{82800}{}{Lehké}
{82801}{}{Bezpeènostní svìtlo.}
{82900}{}{Sloup}
{82901}{}{Sloup.}
{83000}{}{Dobíjecí místnost}
{83001}{}{Toto je napájecí dok pro roboty. Tady se dobíjí, kdy nejsou ve slubì.}
{83100}{}{Dobíjecí místnost}
{83101}{}{Toto je napájecí dok pro roboty. Tady se dobíjí, kdy nejsou ve slubì.}
{83200}{}{Dobíjecí místnost}
{83201}{}{Toto je napájecí dok pro roboty. Tady se dobíjí, kdy nejsou ve slubì.}
{83300}{}{Dobíjecí místnost}
{83301}{}{Toto je napájecí dok pro roboty. Tady se dobíjí, kdy nejsou ve slubì.}
{83400}{}{Dobíjecí místnost}
{83401}{}{Toto je napájecí dok pro roboty. Tady se dobíjí, kdy nejsou ve slubì.}
{83500}{}{Stroj}
{83501}{}{Toto zaøízení má nìco spoleèného se servisní základnou robotù. Nevypadá nijak zvláš zajímavì.}
{83600}{}{Stroj}
{83601}{}{Toto zaøízení má nìco spoleèného se servisní základnou robotù. Nevypadá nijak zvláš zajímavì.}
{83700}{}{Pruh}
{83800}{}{Pruh}
{83900}{}{Pruh}
{84000}{}{Pruh}
{84100}{}{Pruh}
{84200}{}{Pruh}
{84300}{}{Pruh}
{84400}{}{Pruh}
{84500}{}{Pruh}
{84600}{}{Pruh}
{84700}{}{Pruh}
{84800}{}{Dveøe}
{84801}{}{Naprosto normální døevìné dveøe.}
{84900}{}{Dveøe}
{84901}{}{Naprosto normální døevìné dveøe.}
{85000}{}{Dveøe}
{85001}{}{Naprosto normální døevìné dveøe.}
{85100}{}{Cedule}
{85101}{}{Reklamní cedule spoleènosti Friendly Lending Company.}
{85200}{}{Emblém}
{85201}{}{Vypadá to jako nìjakı náboenskı symbol.}
{85300}{}{Operaèní stùl}
{85301}{}{Vypadá to jako stùl k vyšetøování pacientù.}
{85400}{}{Cedule}
{85401}{}{Neonovı poutaè restaurace Maltese Falcon.}
{85500}{}{Graffiti}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Cedule}
{86901}{}{Stojí na ní: ZBRANÌ. Asi se tu prodávají zbranì.}
{87000}{}{Cedule}
{87001}{}{Stojí na ní: POLICIE.}
{87100}{}{Cedule}
{87101}{}{Poutaè firmy Far Go Traders.}
{87200}{}{Cedule}
{87201}{}{Stojí na ní: Gunrunners.}
{87300}{}{Cedule}
{87301}{}{Toto je cedule obchodní spoleènosti Crimson Caravan.}
{87400}{}{Cedule}
{87401}{}{Na ceduli stojí: NEMOCNICE. To se mùe hodit.}
{87500}{}{Cedule}
{87501}{}{Toto je cedule hotelu Crash House.}
{87600}{}{Cedule}
{87601}{}{Na této velmi neobvyklé ceduli je napsáno: Bobùv obchod s ojetinami.}
{87700}{}{Cedule}
{87701}{}{Poutaè Vodních Kupcù, obchodní spoleènosti z Hubu.}
{87800}{}{Skoøápka}
{87801}{}{Kousky rozbité skoøápky.}
{87900}{}{Skoøápka}
{87901}{}{Kousky rozbité skoøápky.}
{88000}{}{Skoøápka}
{88001}{}{Kousky rozbité skoøápky.}
{88100}{}{Skoøápka}
{88101}{}{Kousky rozbité skoøápky.}
{88200}{}{Kamínky}
{88201}{}{Roztroušené kamínky.}
{88300}{}{Kamínky}
{88301}{}{Roztroušené kamínky.}
{88400}{}{Kamínky}
{88401}{}{Roztroušené kamínky.}
{88500}{}{Skoøápka}
{88501}{}{Kousky rozbité skoøápky.}
{88600}{}{Lampa}
{88601}{}{Lampa. A zdá se, e ještì funguje.}
{88700}{}{Cedule}
{88701}{}{Na ceduli stojí: Motel.}
{88800}{}{Houby}
{88801}{}{Bednièky na stole jsou naplnìny hnojem, ve kterém se vıbornì daøí houbám.}
{88900}{}{Houby}
{88901}{}{Bednièky na stole jsou naplnìny hnojem, ve kterém se vıbornì daøí houbám.}
{89000}{}{Kostra}
{89100}{}{Cedule}
{89101}{}{Je na ní napsáno: VÌZNICE.}
{89200}{}{Cedule}
{89201}{}{Toto je cedule baru Skum Pitt.}
{89300}{}{Cedule}
{89301}{}{Reklama na bøitvy znaèky Blade.}
{89400}{}{Sprcha}
{89401}{}{Normální sprchovı kout.}
{89500}{}{Sprcha}
{89501}{}{Normální sprchovı kout.}
{89600}{}{Cedule}
{89601}{}{Poutaè banky Friendly Lending Company.}
{89700}{}{Cedule}
{89701}{}{Poutaè banky Friendly Lending Company.}
{89800}{}{Plakát}
{89801}{}{Plakát nìjakého hororového filmu z doby pøed Válkou.}
{89900}{}{Plakát}
{89901}{}{Plakát nìjakého hororového filmu z doby pøed Válkou.}
{90000}{}{Bar}
{90001}{}{Na baru je poloená urna. Je sice trochu otluèená, ale i pøesto se zdá bıt cenná.}
{90100}{}{Šachta vıtahu}
{90101}{}{Seshora visí lano.}
{90200}{}{Šachta vıtahu}
{90201}{}{Za hranu vıtahove šachty je upevnìné lano.}
{90300}{}{Lékaøské lùko}
{90301}{}{Lùko má zabudované pøístroje pro monitorování stavu pacientù.}
{90400}{}{Vodní pumpa}
{90401}{}{Èást zaøízení èerpající vodu zpod povrchu.}
{90500}{}{Lékaøské lùko}
{90501}{}{Lùko má zabudované pøístroje pro monitorování stavu pacientù.}
{90600}{}{Souèástky do energo zbroje}
{90601}{}{Nìkolik souèástek pro energo zbroj.}
{90700}{}{Lehké}
{90701}{}{Poplašné svìtlo rudì pulzuje.}
{90800}{}{Lehké}
{90801}{}{Poplašné svìtlo rudì pulzuje.}
{90900}{}{Symbol}
{91000}{}{Symbol}
{91100}{}{Symbol}
{91200}{}{Symbol}
{91300}{}{Symbol}
{91400}{}{Symbol}
{91500}{}{Provaz}
{91600}{}{Provaz}
{91700}{}{Provaz}
{91800}{}{Provaz}
{91900}{}{Provaz}
{92000}{}{Provaz}
{92100}{}{Provaz}
{92200}{}{Provaz}
{92300}{}{- Kaòon}
{92400}{}{- Kaòon}
{92500}{}{- Kaòon}
{92600}{}{- Kaòon}
{92700}{}{- Kaòon}
{92800}{}{- Kaòon}
{92900}{}{- Kaòon}
{93000}{}{- Kaòon}
{93100}{}{Podlaha jeskynì}
{93200}{}{Neprostupné dveøe}
{93201}{}{Tyto dveøe nemají ádnı otevírací mechanismus.}
{93300}{}{Znièené dveøe}
{93301}{}{Dveøe otevøené vıbuchem.}
{93400}{}{Dveøe}
{93401}{}{Dveøe se sloitım zámkem.}
{93500}{}{Pochodeò}
{93501}{}{Do elezného kruhu pøipevnìného na zdi je zasazena hoøící pochodeò.}
{93600}{}{Pochodeò}
{93601}{}{Do elezného kruhu pøipevnìného na zdi je zasazena hoøící pochodeò.}
{93700}{}{Kamennı monument}
{93800}{}{Kamennı monument}
{93900}{}{Kamennı monument}
{94000}{}{Totem}
{94001}{}{Døevìnı sloup, ve kterém jsou zasazeny lidské lebky.}
{94100}{}{Totem}
{94101}{}{Døevìnı sloup, ve kterém jsou zasazeny lidské lebky.}
{94200}{}{Totem}
{94201}{}{Døevìnı sloup, ve kterém jsou zasazeny lidské lebky.}
{94300}{}{Rostlina}
{94301}{}{}
{94400}{}{Rostlina}
{94500}{}{Strom}
{94600}{}{Strom}
{94700}{}{Strom}
{94800}{}{Postel}
{94900}{}{Postel}
{95000}{}{Díra}
{95001}{}{Velmi podezøelá díra ve zdi.}
{95100}{}{Nášlapná deska}
{95101}{}{Nášlapná deska.}
{95200}{}{Nefunkèní nášlapná deska}
{95201}{}{Nefunkèní nášlapná deska.}
{95300}{}{Spuštìná nášlapná deska}
{95301}{}{Spuštìná nášlapná deska.}
{95400}{}{Dveøe}
{95500}{}{Dveøe}
{95600}{}{Dveøe}
{95700}{}{Dveøe}
{95800}{}{Dveøe}
{95900}{}{Dveøe}
{96000}{}{Dveøe}
{96100}{}{Dveøe}
{96200}{}{Dveøe}
{96300}{}{Rostlina}
{96301}{}{Zmutovaná kukuøice.}
{96400}{}{Rostlina}
{96401}{}{Zmutovaná kukuøice.}
{96500}{}{Rostlina}
{96501}{}{Zmutovaná kukuøice. Tahle je nìèím napadena.}
{96600}{}{Rostlina}
{96601}{}{Zmutovaná kukuøice.}
{96700}{}{Rostlina}
{96701}{}{Zmutovaná kukuøice.}
{96800}{}{Rostlina}
{96801}{}{Zmutovaná kukuøice.}
{96900}{}{Døevìnı sloup}
{97000}{}{Døevìnı sloup}
{97100}{}{Døevìnı sloup}
{97200}{}{Døevìnı sloup}
{97300}{}{Døevìnı sloup}
{97400}{}{Døevìnı sloup}
{97500}{}{Znièenı døevìnı sloup}
{97501}{}{Tento sloup vypadá, e by se mohl zøítit, pokud by ho nìkdo zatíil.}
{97600}{}{Zøícená podlaha}
{97601}{}{Èást kamenné podlahy se zøítila do nišího patra.}
{97700}{}{ebøík dolù}
{97701}{}{Umìle vytvoøenı otvor s ebøíkem vedoucím dolù.}
{97800}{}{Dveøe}
{97900}{}{Stìna}
{98000}{}{Nápis: Reaktor 5}
{98100}{}{Dveøe}
{98200}{}{Dveøe}
{98300}{}{Dveøe}
{98400}{}{Dveøe}
{98500}{}{Radioaktivní odpad}
{98600}{}{Radioaktivní odpad}
{98700}{}{Radioaktivní odpad}
{98800}{}{Radioaktivní odpad}
{98900}{}{Bezpeènostní dveøe}
{99000}{}{Dveøe vaultu}
{99100}{}{Údrbáøskı jeøáb}
{99200}{}{Údrbáøskı jeøáb}
{99300}{}{Studna}
{99400}{}{Studna}
{99500}{}{Kùlna}
{99600}{}{Díra}
{99601}{}{Nevidíš a na dno.}
{99700}{}{Nášlapná deska}
{99701}{}{Vidíš nášlapnou desku. Je to past.}
{99800}{}{Nefunkèní nášlapná deska}
{99801}{}{Tato nášlapná past byla zneškodnìna.}
{99900}{}{Spuštìná nášlapná deska}
{99901}{}{Tato past byla spuštìna. A sakra!}
{100000}{}{Destilátor}
{100001}{}{Vypadá to jako destilátor na døevo.}
{100100}{}{Èásti radškorpiona}
{100101}{}{Vidíš velikou hromadu èástí radškorpiona. Nìkdo je vydlabal a pøipevnil k nim popruhy.}
{100200}{}{Zaøízení elektrárny}
{100201}{}{Toto je plutoniovı gamma štít. Souèást zaøízení reaktoru.}
{100300}{}{Zaøízení elektrárny}
{100301}{}{Jupiterovı vlnovı kompilátor. Souèást zaøízení reaktoru.}
{100400}{}{Zaøízení elektrárny}
{100401}{}{Ovládací mechanismus uranovıch palivovıch tyèí. Regulaèní a zabezpeèovací zaøízení reaktoru.}
{100500}{}{Zaøízení elektrárny}
{100501}{}{Neptunovı rotor. Souèást zaøízení reaktoru.}
{100600}{}{Zaøízení elektrárny}
{100601}{}{Kapacitor tøídy Saturn. Souèást zaøízení reaktoru.}
{100700}{}{Ovládání èerpadel}
{100701}{}{Ovládací panel èerpadel chladícího média pro reaktor.}
{100800}{}{Brahmíní bok}
{100900}{}{Auto}
{101000}{}{Auto Chrysalis Motors}
{101001}{}{Tento Highwayman od firmy Chrysalis Motors je na svùj vìk v docela dobrém stavu.}
{101100}{}{Auto}
{101200}{}{Hrob}
{101201}{}{Nachází se tu hrob.}
{101300}{}{Náhrobek}
{101301}{}{Náhrobek}
{101400}{}{Náhrobek}
{101401}{}{Náhrobek}
{101500}{}{Náhrobek}
{101501}{}{Náhrobek}
{101600}{}{Náhrobek}
{101601}{}{Náhrobek}
{101700}{}{Pluh}
{101701}{}{Tento pluh je evidentnì uzpùsoben pro zapøaení brahmíny.}
{101800}{}{Pluh}
{101801}{}{Tento pluh je evidentnì uzpùsoben pro zapøaení brahmíny.}
{101900}{}{Voda}
{102000}{}{Cedule}
{102001}{}{Vstupní poutaè mìsta New Reno.}
{102100}{}{Cedule}
{102101}{}{Vstupní poutaè mìsta New Reno.}
{102200}{}{Cedule}
{102201}{}{Vstupní poutaè mìsta New Reno.}
{102300}{}{Cedule}
{102301}{}{Vstupní poutaè mìsta New Reno.}
{102400}{}{Cedule}
{102401}{}{Vstupní poutaè mìsta New Reno.}
{102500}{}{Cedule}
{102501}{}{Vstupní poutaè mìsta New Reno.}
{102600}{}{Stín}
{102700}{}{Stín}
{102800}{}{Stín}
{102900}{}{Graffiti}
{103000}{}{Graffiti}
{103100}{}{Graffiti}
{103200}{}{Graffiti}
{103300}{}{Graffiti}
{103400}{}{Graffiti}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Graffiti}
{104800}{}{Graffiti}
{104900}{}{Graffiti}
{105000}{}{Graffiti}
{105100}{}{Graffiti}
{105200}{}{Graffiti}
{105300}{}{Graffiti}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Graffiti}
{105800}{}{Graffiti}
{105900}{}{Graffiti}
{106000}{}{Cedule}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Graffiti}
{107200}{}{Graffiti}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Graffiti}
{108800}{}{Graffiti}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Graffiti}
{109900}{}{Graffiti}
{110000}{}{Graffiti}
{110100}{}{Graffiti}
{110200}{}{Graffiti}
{110300}{}{Graffiti}
{110400}{}{Graffiti}
{110500}{}{Graffiti}
{110600}{}{Graffiti}
{110700}{}{Graffiti}
{110800}{}{Graffiti}
{110900}{}{Graffiti}
{111000}{}{Cedule}
{111100}{}{Cedule}
{111200}{}{Cedule}
{111300}{}{Cedule}
{111400}{}{Cedule}
{111500}{}{Cedule}
{111600}{}{Cedule}
{111700}{}{Cedule}
{111800}{}{Plakát}
{111900}{}{Plakát}
{112000}{}{Plakát}
{112100}{}{Plakát}
{112200}{}{Plakát}
{112300}{}{Plakát}
{112400}{}{Plakát}
{112500}{}{Plakát}
{112600}{}{Plakát}
{112700}{}{Plakát}
{112800}{}{Plakát}
{112900}{}{Plakát}
{113000}{}{Plakát}
{113100}{}{Plakát}
{113200}{}{Plakát}
{113300}{}{Plakát}
{113400}{}{Plakát}
{113500}{}{Plakát}
{113600}{}{Plakát}
{113700}{}{Plakát}
{113800}{}{Plakát}
{113900}{}{Plakát}
{114000}{}{Plakát}
{114100}{}{Filmová kamera}
{114200}{}{Rakev}
{114300}{}{Rakev}
{114400}{}{Rakev}
{114500}{}{Rakev}
{114600}{}{Ocelové tyèe}
{114700}{}{Ocelové tyèe}
{114800}{}{Ocelové víko}
{114900}{}{Ocelové víko}
{115000}{}{Laserovı paprsek}
{115100}{}{Laserovı paprsek}
{115200}{}{Dùlní vozík}
{115300}{}{Dùlní vozík s pøipevnìnou eleznou tyèí}
{115400}{}{Dùlní vozík s dynamitem}
{115500}{}{Cedule "Zavøeno"}
{115600}{}{Cedule "Zavøeno"}
{115700}{}{Oznaèení domu vdovy Bucknerové}
{115800}{}{Oznaèení Vicova staroitnictví}
{115900}{}{Stìna}
{116000}{}{Stìna}
{116100}{}{Oèní skener}
{116101}{}{Toto je bezpeènostní zaøízení, které snímá lidskou sítnici.}
{116200}{}{Cedule s nápisem "Centrála"}
{116300}{}{Cedule s nápisem "Centrála"}
{116400}{}{Cedule s nápisem "Centrála"}
{116500}{}{Cedule s nápisem "Pracovní pásmo"}
{116600}{}{Cedule s nápisem "Pracovní pásmo"}
{116700}{}{Stroj}
{116701}{}{Nefunkèní stroj.}
{116800}{}{Stroj}
{116801}{}{Nefunkèní stroj.}
{116900}{}{Dveøe}
{117000}{}{Dveøe}
{117100}{}{Rezavé potrubí}
{117101}{}{Sple starıch rezavıch trubek.}
{117200}{}{Tank}
{117300}{}{Dík.}
{117400}{}{Dík.}
{117500}{}{Dík.}
{117600}{}{Vìtrací otvor}
{117700}{}{Vìtrací otvor}
{117800}{}{Cedule "Harpyje"}
{117900}{}{Truhláøská koza}
{118000}{}{Truhláøská koza}
{118100}{}{Truhláøská koza}
{118200}{}{Vìtrací otvor}
{118300}{}{Vìtrací otvor}
{118400}{}{Cedule "Zámeènictví"}
{118500}{}{Cedule "Kanceláø"}
{118600}{}{Cedule "Sklad"}
{118700}{}{Cedule "Radiace"}
{118800}{}{Pára}
{118900}{}{Stroj}
{118901}{}{Nìjaké nezajímavé zaøízení elektrárny.}
{119000}{}{Tank}
{119100}{}{Oheò}
{119200}{}{Voda}
{119300}{}{Cedule "Lovecká ètvr"}
{119400}{}{Cedule "U Zlatého geckona"}
{119500}{}{Cedule "Láznì"}
{119600}{}{Jeskynní malba}
{119700}{}{Jeskynní malba}
{119800}{}{Jeskynní malba}
{119900}{}{Jeskynní malba}
{120000}{}{Ohništì}
{120100}{}{Stìna jeskynì}
{120200}{}{Stìna jeskynì}
{120300}{}{Stìna jeskynì}
{120400}{}{Stìna jeskynì}
{120500}{}{Stìna jeskynì}
{120600}{}{Stìna jeskynì}
{120700}{}{Stìna jeskynì}
{120800}{}{Stìna jeskynì}
{120900}{}{Stìna jeskynì}
{121000}{}{Stìna jeskynì}
{121100}{}{Stìna jeskynì}
{121200}{}{Stìna jeskynì}
{121300}{}{Stìna jeskynì}
{121400}{}{Stìna jeskynì}
{121500}{}{Stìna jeskynì}
{121600}{}{Kùl}
{121601}{}{Na tomto kùlu je nabodnuto lidské tìlo!}
{121700}{}{Kùl}
{121701}{}{Na tomto kùlu je nabodnuto lidské tìlo!}
{121800}{}{Kùl}
{121801}{}{Na tomto kùlu je nabodnuto lidské tìlo!}
{121900}{}{Kùl}
{121901}{}{Na tomto kùlu je nabodnuto lidské tìlo!}
{122000}{}{Kùl}
{122001}{}{Na tomto kùlu je nabodnuto lidské tìlo!}
{122100}{}{Kùl}
{122101}{}{Na tomto kùlu je nabodnuto lidské tìlo!}
{122200}{}{Kùl}
{122201}{}{Na tomto kùlu je nabodnuta lidská lebka.}
{122300}{}{Kùl}
{122301}{}{Na tomto kùlu je nabodnuta lidská lebka.}
{122400}{}{Kùl}
{122401}{}{Tento kùl na svoji obì teprve èeká.}
{122500}{}{Kùl}
{122501}{}{Tento kùl na svoji obì teprve èeká.}
{122600}{}{Kùl}
{122601}{}{Tento kùl na svoji obì teprve èeká.}
{122700}{}{Kùl}
{122701}{}{Tento kùl na svoji obì teprve èeká.}
{122800}{}{Zatykaè}
{122801}{}{Osoba na této vıvìsce je ti neuvìøitelnì podobná!}
{122900}{}{Podlaha}
{123000}{}{Deaktivovanı kyborg}
{123001}{}{Nekompletní tìlo robota, kterému chybí nìkolik souèástek.}
{123100}{}{Houfnice}
{123101}{}{Toto podivnì vypadající dìlo vypadá jako nìjakı pozùstatek z doby pøed Válkou. Zajímalo by tì, jak se sem dostalo.}
{123200}{}{Cedule}
{123300}{}{Cedule}
{123400}{}{Cedule}
{123500}{}{Cedule}
{123600}{}{Vypínaè}
{123700}{}{Køí}
{123800}{}{Køí}
{123900}{}{Køí}
{124000}{}{Køí}
{124100}{}{Køí}
{124200}{}{Køí}
{124300}{}{Èerpací stanice}
{124400}{}{Èerpací stanice}
{124500}{}{Èerpací stanice}
{124600}{}{Oznaèení "Èerpací stanice"}
{124700}{}{Cedule "Stín"}
{124800}{}{Seník}
{124900}{}{Seník}
{125000}{}{Seník}
{125100}{}{Seník}
{125200}{}{Seník}
{125300}{}{Seník}
{125400}{}{Cedule "Dustyho krèma"}
{125500}{}{Obchod "Leguání kousky Bobovy syna".}
{125501}{}{Poulièní stánek.}
{125600}{}{Obchod "Leguání kousky Bobovy syna".}
{125601}{}{Poulièní stánek.}
{125700}{}{Obchod "Leguání kousky Bobovy syna".}
{125701}{}{Poulièní stánek.}
{125800}{}{Obchod "Leguání kousky Bobovy syna".}
{125801}{}{Poulièní stánek.}
{125900}{}{Cedule "NCR"}
{126000}{}{Cedule "Kongres"}
{126100}{}{Cedule "Kongres"}
{126200}{}{Plakát NCR}
{126300}{}{Plakát NCR}
{126400}{}{Plakát NCR}
{126500}{}{Plakát NCR}
{126600}{}{Cedule "Salón U Nevydìlanı kùe"}
{126700}{}{Cedule "Kasíno"}
{126800}{}{Cedule "Kasíno"}
{126900}{}{Cedule "Kasíno"}
{127000}{}{Cedule "Kasíno"}
{127100}{}{Cedule "Kasíno"}
{127200}{}{Cedule "Kasíno"}
{127300}{}{Hromada kamení}
{127301}{}{Vypadá to, jako kdyby tyto kameny nìco skrıvaly.}
{127400}{}{Trám}
{127500}{}{Trám}
{127600}{}{Trám}
{127700}{}{Trám}
{127800}{}{Trám}
{127900}{}{Trám}
{128000}{}{Trám}
{128100}{}{Trám}
{128200}{}{Trám}
{128300}{}{Trám}
{128400}{}{Stín}
{128500}{}{Stín}
{128600}{}{Stín}
{128700}{}{Stín}
{128800}{}{Stín}
{128900}{}{Stín}
{129000}{}{Stín}
{129100}{}{Stín}
{129200}{}{Stín}
{129300}{}{Vıtah}
{129400}{}{Èerpací stanice}
{129500}{}{Èerpací stanice}
{129600}{}{Èerpací stanice}
{129700}{}{Provaz}
{129800}{}{Díra}
{129900}{}{Brahmíní maso}
{130000}{}{Brahmíní maso}
{130100}{}{Brahmíní maso}
{130200}{}{Brahmíní maso}
{130300}{}{Brahmíní maso}
{130400}{}{Brahmíní maso}
{130500}{}{Trám}
{130600}{}{Trám}
{130700}{}{Trám}
{130800}{}{Trám}
{130900}{}{Trám}
{131000}{}{Trám}
{131100}{}{Trám}
{131200}{}{Trám}
{131300}{}{Stín}
{131400}{}{Stín}
{131500}{}{Stín}
{131600}{}{Stín}
{131700}{}{Stín}
{131800}{}{Stín}
{131900}{}{Stín}
{132000}{}{Stín}
{132100}{}{Krev}
{132200}{}{Krev}
{132300}{}{Krev}
{132400}{}{Krev}
{132500}{}{Krev}
{132600}{}{Krev}
{132700}{}{Krev a kosti}
{132800}{}{Krev a kosti}
{132900}{}{Krev a kosti}
{133000}{}{Ústí jeskynì}
{133100}{}{Vybavení}
{133200}{}{Vybavení}
{133300}{}{Vybavení}
{133400}{}{Vybavení}
{133500}{}{Poèítaè}
{133501}{}{Terminál napojenı na hlavní poèítaè Vaultu.}
{133600}{}{Poèítaè}
{133601}{}{Terminál napojenı na hlavní poèítaè Vaultu.}
{133700}{}{Vstup do Vault City}
{133800}{}{Vstup do Vault City}
{133900}{}{Stìna}
{134000}{}{Stìna}
{134100}{}{Stìna}
{134200}{}{Stìna}
{134300}{}{Stìna}
{134400}{}{Stìna}
{134500}{}{Stìna}
{134600}{}{Stìna}
{134700}{}{Dveøe}
{134800}{}{Dveøe otevøené vıbuchem}
{134900}{}{Zbytky dveøí}
{135000}{}{Budova}
{135100}{}{Budova}
{135200}{}{Budova}
{135300}{}{Budova}
{135400}{}{Budova}
{135500}{}{Budova}
{135600}{}{Budova}
{135700}{}{Budova}
{135800}{}{Dveøe}
{135900}{}{Chrám}
{136000}{}{Chrám}
{136100}{}{Chrám}
{136200}{}{Chrám}
{136300}{}{Chrám}
{136400}{}{Chrám}
{136500}{}{Ohništì}
{136600}{}{Ohništì}
{136700}{}{Houfnice}
{136701}{}{Toto podivnì vypadající dìlo vypadá jako nìjakı pozùstatek z doby pøed Válkou. Zajímalo by tì, jak se sem dostalo.}
{136800}{}{Chrám}
{136900}{}{Chrám}
{137000}{}{Hory}
{137100}{}{- Jeskynì}
{137200}{}{Posuvník dveøí}
{137300}{}{Pochodeò}
{137301}{}{Do elezného kruhu pøipevnìného na zdi je zasazena hoøící pochodeò.}
{137400}{}{Pochodeò}
{137401}{}{Do elezného kruhu pøipevnìného na zdi je zasazena hoøící pochodeò.}
{137500}{}{Pochodeò}
{137501}{}{Do elezného kruhu pøipevnìného na zdi je zasazena hoøící pochodeò.}
{137600}{}{Pochodeò}
{137601}{}{Do elezného kruhu pøipevnìného na zdi je zasazena hoøící pochodeò.}
{137700}{}{Vertibird}
{137701}{}{Velikı vojenskı létající prostøedek.}
{137800}{}{Znièené dveøe}
{137801}{}{Su zcela blokuje vstup.}
{137900}{}{Znièené dveøe}
{137901}{}{Su zcela blokuje vstup.}
{138000}{}{Stìna}
{138100}{}{Stìna}
{138200}{}{Stìna}
{138300}{}{Stìna}
{138400}{}{Stìna}
{138500}{}{Stìna}
{138600}{}{Lehké}
{138700}{}{Dveøe}
{138800}{}{Dveøe}
{138900}{}{Dveøe}
{139000}{}{Dveøe}
{139100}{}{Dveøe}
{139200}{}{Dveøe}
{139300}{}{Prapor}
{139400}{}{Ukazatel}
{139500}{}{Ukazatel}
{139600}{}{Prapor}
{139700}{}{Prapor}
{139800}{}{Ukazatel}
{139900}{}{Ukazatel}
{140000}{}{Prapor}
{140100}{}{Stín}
{140200}{}{Stín}
{140300}{}{Prapor}
{140400}{}{Prapor}
{140500}{}{Prapor}
{140600}{}{Prapor}
{140700}{}{Cedule "Koèièí Packa"}
{140800}{}{Cedule "Koèièí Packa"}
{140900}{}{Cedule}
{141000}{}{Cedule "Box"}
{141100}{}{Cedule "Box"}
{141200}{}{Cedule "Box"}
{141300}{}{Cedule "Renescova lékárna"}
{141400}{}{Cedule "Lovecké potøeby"}
{141500}{}{Cedule "Bar Salvatore"}
{141600}{}{Socha}
{141700}{}{Garáová vrata}
{141800}{}{Garáová vrata}
{141900}{}{Cedule "Doktor Johnson"}
{142000}{}{Cedule "Šerif"}
{142100}{}{Cedule "Hospoda U Malamuta"}
{142200}{}{Cedule "Dùl Morningstar"}
{142300}{}{Cedule "Dùl Kokoweef"}
{142400}{}{Cedule "Dùl Kokoweef"}
{142500}{}{Cedule "Dùl Kokoweef"}
{142600}{}{Ukazatel}
{142601}{}{Tento døevìnı ukazatel ukazuje do dvou smìrù. Jeden vede do New Rena a druhı do "Pekla". Máš podezøení, e je to obrácenì.}
{142700}{}{Cedule s èíslem 1}
{142800}{}{Cedule s èíslem 2}
{142900}{}{Cedule s èíslem 3}
{143000}{}{Cedule s èíslem 4}
{143100}{}{Cedule s èíslem 5}
{143200}{}{Cedule s èíslem 6}
{143300}{}{Provaz}
{143301}{}{Pomocí tohoto lana se mùeš dostat pøes zeï.}
{143400}{}{Dveøe}
{143500}{}{Dveøe}
{143600}{}{Okno}
{143700}{}{Okno}
{143800}{}{Okno}
{143900}{}{Okno}
{144000}{}{Okno}
{144100}{}{Okno}
{144200}{}{Okno}
{144300}{}{Okno}
{144400}{}{Okno}
{144500}{}{Okno}
{144600}{}{Okno}
{144700}{}{Okno}
{144800}{}{Bazénovı ebøík}
{144900}{}{Dveøe}
{145000}{}{Klenba}
{145100}{}{Klenba}
{145200}{}{Klenba}
{145300}{}{Klenba}
{145400}{}{Klenba}
{145500}{}{Klenba}
{145600}{}{Klenba}
{145700}{}{Klenba}
{145800}{}{Stín}
{145900}{}{Stín}
{146000}{}{Stín}
{146100}{}{Klenba}
{146200}{}{Klenba}
{146300}{}{Klenba}
{146400}{}{Stín}
{146500}{}{Stín}
{146600}{}{Dveøe v plotì}
{146700}{}{Dveøe v plotì}
{146800}{}{Velitelské køeslo}
{146801}{}{V tomto køesle obvykle sedí Správce vaultu.}
{146900}{}{Propast}
{147000}{}{Propast}
{147100}{}{Propast}
{147200}{}{Propast}
{147300}{}{Vchod do kasína}
{147400}{}{Vchod do kasína}
{147500}{}{Koberec}
{147600}{}{Vchod do kasína}
{147700}{}{Vchod do kasína}
{147800}{}{Vchod do kasína}
{147900}{}{Dveøe kasína}
{148000}{}{Dveøe kasína}
{148100}{}{Vchod do kasína}
{148200}{}{Vchod do kasína}
{148300}{}{Vchod do kasína}
{148400}{}{Vchod do kasína}
{148500}{}{Vchod do kasína}
{148600}{}{Vchod do kasína}
{148700}{}{Vchod do kasína}
{148800}{}{Vchod do kasína}
{148900}{}{Vchod do kasína}
{149000}{}{Vchod do kasína}
{149100}{}{Dveøe kasína}
{149200}{}{Dveøe kasína}
{149300}{}{Nástìnné svìtlo}
{149400}{}{Nástìnné svìtlo}
{149500}{}{Nástìnné svìtlo}
{149600}{}{Nástìnné svìtlo}
{149700}{}{Nástìnné svìtlo}
{149800}{}{Stìna}
{149900}{}{Stìna}
{150000}{}{Ventilátor}
{150100}{}{Ventilátor}
{150200}{}{Hasící pøístroj}
{150300}{}{Hasící pøístroj}
{150400}{}{Potrubí}
{150500}{}{Rozvadìè elektøiny}
{150600}{}{Rozvadìè elektøiny}
{150700}{}{Stìna}
{150800}{}{Stìna}
{150900}{}{Stìna}
{151000}{}{Stìna}
{151100}{}{Stìna}
{151200}{}{Stìna}
{151300}{}{Stìna}
{151400}{}{Stìna}
{151500}{}{Stìna}
{151600}{}{Døevìné obloení}
{151700}{}{Døevìné obloení}
{151800}{}{Potrubí}
{151900}{}{Potrubí}
{152000}{}{Potrubí}
{152100}{}{Potrubí}
{152200}{}{Potrubí}
{152300}{}{Potrubí}
{152400}{}{Potrubí}
{152500}{}{Potrubí}
{152600}{}{Potrubí}
{152700}{}{Potrubí}
{152800}{}{Potrubí}
{152900}{}{Vzduchová ventilace}
{153000}{}{Vzduchová ventilace}
{153100}{}{Dveøe}
{153200}{}{Dveøe}
{153300}{}{Dveøe}
{153400}{}{Dveøe}
{153500}{}{Dveøe}
{153600}{}{Dveøe}
{153700}{}{Sprcha}
{153800}{}{UNUSED.}
{153900}{}{UNUSED.}
{154000}{}{UNUSED.}
{154100}{}{UNUSED.}
{154200}{}{UNUSED.}
{154300}{}{UNUSED.}
{154400}{}{UNUSED.}
{154500}{}{UNUSED.}
{154600}{}{Stìna raketoplánu}
{154700}{}{Stìna raketoplánu}
{154800}{}{Silové pole}
{154900}{}{Silové pole}
{155000}{}{Extraktor orgánù}
{155001}{}{Poslední model z chirurgické série "Udìlej si sám" od firmy Vault-Tec. Pouhım stiskem tlaèítka dokáe automaticky vyjmout libovolnı tìlesnı orgán.}
{155100}{}{Raketoplán}
{155200}{}{Raketoplán}
{155300}{}{Raketoplán}
{155400}{}{Raketoplán}
{155500}{}{Raketoplán}
{155600}{}{Raketoplán}
{155700}{}{Raketoplán}
{155800}{}{Raketoplán}
{155900}{}{Raketoplán}
{156000}{}{Raketoplán}
{156100}{}{Raketoplán}
{156200}{}{Raketoplán}
{156300}{}{Raketoplán}
{156400}{}{Raketoplán}
{156500}{}{Raketoplán}
{156600}{}{Stín}
{156700}{}{Stín}
{156800}{}{Stín}
{156900}{}{Stín}
{157000}{}{Stín}
{157100}{}{Stín}
{157200}{}{Trùn}
{157300}{}{Dveøe}
{157400}{}{Dveøe}
{157500}{}{Dveøe}
{157600}{}{Dveøe}
{157700}{}{Vzduchová ventilace}
{157800}{}{AutoDok}
{157801}{}{Automatickı doktor je zaøízení vyvinuté pro léèení nemocí a aplikaci nejrùznìjších léèiv.}
{157900}{}{Socha}
{157901}{}{Malá soška legendárního Zakladatele.}
{158000}{}{Hromada kamení}
{158100}{}{Silové pole}
{158101}{}{Energetické pole blokující cestu.}
{158200}{}{Silové pole}
{158201}{}{Energetické pole blokující cestu.}
{158300}{}{Silové pole}
{158301}{}{Energetické pole blokující cestu.}
{158400}{}{Silové pole}
{158401}{}{Energetické pole blokující cestu.}
{158500}{}{Cisterna}
{158600}{}{Cisterna}
{158700}{}{Cisterna}
{158800}{}{Cisterna}
{158900}{}{Cisterna}
{159000}{}{Cisterna}
{159100}{}{Cisterna}
{159200}{}{Cisterna}
{159300}{}{Cisterna}
{159400}{}{Cisterna}
{159500}{}{Cisterna}
{159600}{}{Cisterna}
{159700}{}{Cisterna}
{159800}{}{Cisterna}
{159900}{}{Cisterna}
{160000}{}{Stìna}
{160100}{}{Stìna}
{160200}{}{Propadlina}
{160300}{}{Kamenná lavice}
{160400}{}{Kamenná lavice}
{160500}{}{Kadidelnice}
{160600}{}{Satelitní vysílaè}
{160700}{}{Satelitní vysílaè}
{160800}{}{Stín}
{160900}{}{Stín}
{161000}{}{Stín}
{161100}{}{Stín}
{161200}{}{Stín}
{161300}{}{Trám}
{161400}{}{Trám}
{161500}{}{Stín}
{161600}{}{Stín}
{161700}{}{Stín}
{161800}{}{Stín}
{161900}{}{Schody}
{162000}{}{Deaktivovanı kyberpes}
{162001}{}{Vidíš deaktivovaného kyberpsa.}
{162100}{}{Znièenı generátor energie}
{162101}{}{Vidíš znièenı generátor energie.}
{162200}{}{Stopa}
{162300}{}{Stopa}
{162400}{}{Stopa}
{162500}{}{Dùlní vozík}
{162600}{}{Dùlní vozík s pøipevnìnou eleznou tyèí}
{162700}{}{Dùlní vozík s pøipevnìnım dynamitem}
{162800}{}{Znièenı dùlní vozík}
{162900}{}{Dùlní vozík}
{163000}{}{Kuleèníkovı stùl}
{163100}{}{Kuleèníkovı stùl}
{163200}{}{Kuleèníkovı stùl}
{163300}{}{Kuleèníkovı stùl}
{163400}{}{Kuleèníkovı stùl}
{163500}{}{Kuleèníkovı stùl}
{163600}{}{Stùl}
{163700}{}{Vlajka}
{163800}{}{Stìna}
{163900}{}{Stìna}
{164000}{}{Stìna}
{164100}{}{Stìna}
{164200}{}{Vıvod}
{164300}{}{Stùl}
{164400}{}{Stùl}
{164500}{}{Schody dolù}
{164600}{}{Schody nahoru}
{164700}{}{Schody nahoru}
{164800}{}{Schody nahoru}
{164900}{}{Jádro reaktoru}
{165000}{}{Jádro reaktoru}
{165100}{}{Jádro reaktoru}
{165200}{}{Cedule "Karavany"}
{165300}{}{Stùl s rakví}
{165400}{}{Stùl s rakví}
{165500}{}{Dùlní vıtah}
{165600}{}{Dùlní vıtah}
{165700}{}{Stoár na vlajku}
{165800}{}{Vlajka NCR}
{165900}{}{Cedule "Pohonné hmoty Poseidon"}
{166000}{}{Schody dolù}
{166100}{}{Cedule "Klinika"}
{166200}{}{Cedule "Nápravné zaøízení"}
{166300}{}{Cedule "Celnice"}
{166400}{}{Cedule "Celnice"}
{166500}{}{Cedule "Uvítací kanceláø"}
{166600}{}{Cedule "U Šastného Harryho"}
{166700}{}{Cedule "Díra"}
{166800}{}{Cedule "Informace"}
{166900}{}{Cedule "Informace"}
{167000}{}{Logo Vault City}
{167100}{}{Cedule "Radnice"}
{167200}{}{Cedule "Radnice"}
{167300}{}{Nápis "Centrum údrby"}
{167400}{}{Cedule "Jídelna"}
{167500}{}{Cedule "Hospoda"}
{167600}{}{Cedule "Westinùv ranè"}
{167700}{}{Cedule "Koloniál"}
{167800}{}{Nápis "A"}
{167900}{}{Nápis "B"}
{168000}{}{Cedule "Rozdìlování sluebníkù"}
{168100}{}{Cedule "Rozdìlování sluebníkù"}
{168200}{}{Cedule "Obchodní centrum"}
{168300}{}{Cedule "Obchodní centrum"}
{168400}{}{Dùlní vıtah}
{168500}{}{Dùlní vıtah}
{168600}{}{Dùlní vıtah}
{168700}{}{Dùlní vıtah}
{168800}{}{Vertibird}
{168900}{}{Vertibird}
{169000}{}{Vertibird}
{169100}{}{Vertibird}
{169200}{}{Vertibird}
{169300}{}{Stín}
{169400}{}{Stín}
{169500}{}{Stín}
{169600}{}{Stín}
{169700}{}{Strange machine, crashed}
{169800}{}{Strange machine, crashed}
{169900}{}{Strange machine, crashed}
{170000}{}{Strange machine, crashed}
{170100}{}{Strange machine, crashed}
{170200}{}{Strange machine, crashed}
{170300}{}{Stín}
{170400}{}{Stín}
{170500}{}{Stín}
{170600}{}{- Zøícenı most}
{170601}{}{Na dnì propasti vidíš to, co zbylo z mostu do Arroya. Teï u se zpátky do vesnice nedostaneš.}
{170700}{}{- Zøícenı most}
{170701}{}{Na dnì propasti vidíš to, co zbylo z mostu do Arroya. Teï u se zpátky do vesnice nedostaneš.}
{170800}{}{- Kaòon}
{170900}{}{Dveøe}
{171000}{}{Dveøe}
{171100}{}{Stìna}
{171200}{}{Stìna}
{171300}{}{Stìna}
{171400}{}{Stìna}
{171500}{}{Stìna}
{171600}{}{Stìna}
{171700}{}{Stìna}
{171800}{}{Stìna}
{171900}{}{Vzduchová ventilace}
{172000}{}{Vzduchová ventilace}
{172100}{}{Neprùstøelné sklo}
{172200}{}{Neprùstøelné sklo}
{172300}{}{Neprùstøelné sklo}
{172400}{}{Tìká laserová vì}
{172401}{}{Vì se vıhrunì otáèí.}
{172500}{}{Tìká laserová vì}
{172501}{}{Vì se vıhrunì otáèí.}
{172600}{}{Kameny}
{172700}{}{Kameny}
{172800}{}{Kameny}
{172900}{}{Kameny}
{173000}{}{Kameny}
{173100}{}{Kameny}
{173200}{}{Kameny}
{173300}{}{Kameny}
{173400}{}{Kameny}
{173500}{}{Kameny}
{173600}{}{Kameny}
{173700}{}{Cedule "Bar u Becky"}
{173800}{}{Cedule "Bar u Becky"}
{173900}{}{Cedule "Salón posledního vydechnutí"}
{174000}{}{Cedule "U Mámy"}
{174100}{}{Cedule "Cech otrokáøù"}
{174200}{}{Cedule "Potøeby pro pøeití"}
{174300}{}{Cedule "Tubbyho bazar"}
{174400}{}{Cedule "Tubbyho bazar"}
{174500}{}{Brána dùlního vıtahu}
{174600}{}{Ventilátor}
{174700}{}{Ventilátor}
{174800}{}{Dveøe prezidentské kanceláøe}
{174900}{}{Oèní diagram}
{175000}{}{Ruiny}
{175100}{}{Strazce vecnosti}
{175200}{}{Cedule "Mimo provoz"}
{175300}{}{Zøícená podlaha}
{175400}{}{Záchod}
{175500}{}{Køí}
{175600}{}{Stìna}
{175700}{}{Stìna}
{175800}{}{Stìna}
{175900}{}{Stìna}
{176000}{}{Stìna}
{176100}{}{Stìna}
{176200}{}{Stìna}
{176300}{}{Stìna}
{176400}{}{Budova}
{176500}{}{Budova}
{176600}{}{Budova}
{176700}{}{Budova}
{176800}{}{Budova}
{176900}{}{Budova}
{177000}{}{Ocelové podpìry}
{177100}{}{Ocelové podpìry}
{177200}{}{Ocelové podpìry}
{177300}{}{Voda}
{177400}{}{Voda}
{177500}{}{Voda}
{177600}{}{Voda}
{177700}{}{Voda}
{177800}{}{Voda}
{177900}{}{Vodopád}
{178000}{}{Silnice}
{178100}{}{Silnice}
{178200}{}{Silnice}
{178300}{}{Silnice}
{178400}{}{Silnice}
{178500}{}{Silnice}
{178600}{}{Silnice}
{178700}{}{Mostní pilíø}
{178800}{}{Mostní pilíø}
{178900}{}{Mostní pilíø}
{179000}{}{Plot}
{179100}{}{Lampa}
{179200}{}{Lampa}
{179300}{}{Mrtvı vorvaò}
{179301}{}{Vypadá to, e se tento kytovec zøítil z obrovské vıšky.}
{179400}{}{Mrtvı vorvaò}
{179401}{}{Vypadá to, e se tento kytovec zøítil z obrovské vıšky.}
{179500}{}{Vorvaní ploutev}
{179501}{}{Ploutev mrtvého vorvanì.}
{179600}{}{Vorvaní oko}
{179601}{}{Oko mrtvého vorvanì.}
{179700}{}{Kus vorvaního masa}
{179701}{}{Poøádnı kus vorvaního masa!}
{179800}{}{Kus vorvaního masa}
{179801}{}{Poøádnı kus vorvaního masa!}
{179900}{}{Kus vorvaního masa}
{179901}{}{Poøádnı kus vorvaního masa!}
{180000}{}{Kus vorvaního masa}
{180001}{}{Poøádnı kus vorvaního masa!}
{180100}{}{Kus vorvaního masa}
{180101}{}{Poøádnı kus vorvaního masa!}
{180200}{}{Nohy bosse}
{180300}{}{Kameny}
{180400}{}{Kameny}
{180500}{}{Kameny}
{180600}{}{Kameny}
{180700}{}{Cedule "Kùe"}
{180800}{}{Cedule "Hotel u Rose"}
{180900}{}{Cedule "Vortisova úschovna"}
{181000}{}{Cedule "Vortisova úschovna"}
{181100}{}{Cedule "Dùl Velkı Wamamingo"}
{181200}{}{Cedule "Ascortiho Eso a Radnice"}
{181300}{}{Zøícená loï}
{181301}{}{Nìjaké kosmické plavidlo. Zdá se, e tu havarovalo teprve nedávno.}
{181400}{}{Rakev}
{181500}{}{Cedule "Stockmanova Asociace"}
{181600}{}{Cedule "Modocká Jatka"}
{181700}{}{Prkno}
{181800}{}{Døevìné dveøe}
{181900}{}{Døevìné dveøe}
{182000}{}{Automat na Colu}
{182100}{}{Automat na Colu}
{182200}{}{Kamna}
{182300}{}{Kamna}
{182400}{}{Kamna}
{182500}{}{Kamna}
{182600}{}{Vìci}
{182700}{}{Vìci}
{182800}{}{Vìci}
{182900}{}{Vìci}
{183000}{}{Vìci}
{183100}{}{Vìci}
{183200}{}{Vìci}
{183300}{}{Vìci}
{183400}{}{Prezidentské køeslo}
{183500}{}{Schody}
{183600}{}{Mapa svìta}
{183700}{}{Situaèní mapa}
{183800}{}{Strategickı stùl}
{183900}{}{Konferenèní stùl}
{184000}{}{Konferenèní stùl}
{184100}{}{Strategickı stùl}
{184200}{}{Strom}
{184300}{}{Strom}
{184400}{}{Rampa}
{184500}{}{Cedule "Porno studio Zlatı glóbus"}
{184600}{}{Kormidlo}
{184700}{}{Ovladaè rychlosti}
{184800}{}{Komunikaèní stanice}
{184900}{}{Poèítaèová konzole}
{185000}{}{Okenice}
{185100}{}{Pára}
{185200}{}{Stará motorka}
{185201}{}{Pøedváleèná motorka. Je nefunkèní.}
{185300}{}{Zásobník vody}
{185301}{}{elezná vì, ve které se uchovává pitná voda.}
{185400}{}{Cedule "Mámin sirotèinec"}
{185500}{}{Ventilátor}
{185600}{}{Zdravì vypadající strom}
{185700}{}{Zdravì vypadající strom}
{185800}{}{Zdravì vypadající strom}
{185900}{}{Zdravì vypadající strom}
{186000}{}{Zdravì vypadající strom}
{186100}{}{Zdravì vypadající strom}
{186200}{}{Rostlina}
{186201}{}{Zmutovaná kukuøice. Zdá se, e jí místní podmínky velice prospívají. Má jinou barvu ne ostatní.}
{186300}{}{Úrodná pùda}
{186400}{}{Úrodná pùda}
{186500}{}{Úrodná pùda}
{186600}{}{USED ART}
{186601}{}{}
{186700}{}{USED ART}
{186701}{}{Trùn pro vùdce nebo velitele.}
{186800}{}{Ventilace}
{186801}{}{Kruhová ventilace do podzemního zaøízení.}
{186900}{}{Provaz}
{186901}{}{Lano vedoucí do vzduchové ventilace.}
{187000}{}{Vzduchová ventilace}
{187001}{}{Ventilace pouívaná k filtrování vzduchu v podzemí.}
{187100}{}{Vìtrací otvor}
{187101}{}{Ventilace pouívaná k èištìní vzduchu v podzemí.}
{187200}{}{Cedule}
{187201}{}{Cedule s instrukcemi.}
{187300}{}{Cedule}
{187301}{}{Cedule s varováním.}
{187400}{}{Vırobní stroj}
{187401}{}{S pomocí tohoto stroje si mùeš vyrobit svoje vlastní léky.}
{187500}{}{Chemikálie}
{187501}{}{Odpornì páchnoucí rosolovité chemikálie.}
{187600}{}{Chemikálie}
{187601}{}{Odpornì páchnoucí rosolovité chemikálie.}
{187700}{}{Chemikálie	}
{187701}{}{Odpornì páchnoucí rosolovité chemikálie.}
{187800}{}{Chemikálie	}
{187801}{}{Odpornì páchnoucí rosolovité chemikálie.}
{187900}{}{Provaz}
{187901}{}{Provaz oznaèující uzavøenou oblast.}
{188000}{}{Provaz}
{188001}{}{Provaz omezující vstup do urèité oblasti.}
{188100}{}{Umìleckı obraz}
{188101}{}{Obraz zobrazující Monu Lisu.}
{188200}{}{Umìleckı obraz}
{188201}{}{Obraz zobrazující první kroky na Mìsíci.}
{188300}{}{Vırobní stroj}
{188301}{}{S pomocí tohoto stroje si mùeš vyrobit svoje vlastní léky.}
{188400}{}{Úrodná pùda}
{188401}{}{Pùda pøipravená pro setbu.}
{188500}{}{Úrodná pùda}
{188501}{}{Pùda pøipravená pro setbu.}
{188600}{}{Dopravní znaèka}
{188601}{}{Znaèka oznaèující místa pro parkování.}
{188700}{}{Vıtah}
{188701}{}{Pomocí vıtahu se dá pøesouvat do jinıch pater.}
{188800}{}{Hibernaèní poèítaè}
{188801}{}{Poèítaè ovládající hibernaèní komory.}
{188900}{}{Skupina sudù}
{188901}{}{V tìchto sudech jsou uskladnìny rùzné chemikálie.}
{189000}{}{Hoøící sud}
{189001}{}{Nápis øíká, e je obsah hoølavı.}
{189100}{}{Sud}
{189101}{}{Sud naplnìnı nìjakou tekutinou.}
{189200}{}{Sud}
{189201}{}{Sud obsahující silnì škodlivou èervenou tekutinu.}
{189300}{}{Sud}
{189301}{}{Sud má na sobì štítek biologického nebezpeèí.}
{189400}{}{Rostlina}
{189401}{}{Tato rostlina má na sobì nìjakı druh bobulí.}
{189500}{}{Strom}
{189600}{}{Toustovaè}
{189601}{}{Na stole stojící støíbrnı toustovaè.}
{189700}{}{Hologram projektor}
{189701}{}{Hologram projektor HD 2000.}
{189800}{}{Hologram projektor}
{189801}{}{Hologram projektor HD 2000.}
{189900}{}{Hologram projektor}
{189901}{}{Hologram projektor HD 2000.}
{190000}{}{Stín}
{190001}{}{}
{190100}{}{Vertibird}
{190200}{}{Kryogenní mrazák}
{190201}{}{Mrazící zaøízení, které dokáe uchovat ivou lidskou bytost. Je otevøenı.}
{190300}{}{Kryogenní mrazák}
{190301}{}{Mrazící zaøízení, které dokáe uchovat ivou lidskou bytost. Je zavøenı.}
{190400}{}{Stùl}
{190401}{}{Velkı a robustnì vypadající stùl.}
{190500}{}{Hibernaèní komora}
{190501}{}{Hibernaèní komora. Uvnitø leí tìlo bìlošky.}
{190600}{}{Hibernaèní komora}
{190601}{}{Hibernaèní komora. Uvnitø leí tìlo bìlocha.}
{190700}{}{Hibernaèní komora}
{190701}{}{Otevøená hibernaèní komora. Uvnitø leí nahé tìlo bìlošky.}
{190800}{}{Hibernaèní komora}
{190801}{}{Otevøená hibernaèní komora. Uvnitø leí nahé tìlo bìlocha.}
{190900}{}{Hibernaèní komora}
{190901}{}{Otevøená hibernaèní komora. Uvnitø leí nahé tìlo èernocha.}
{191000}{}{Hibernaèní komora}
{191001}{}{Hibernaèní komora. Uvnitø leí tìlo èernocha.}
{191100}{}{Hibernaèní komora}
{191101}{}{Otevøená hibernaèní komora. Je prázdná.}
{191200}{}{Elektrické køeslo WattzMan 2000}
{191300}{}{Imperiální vısadkovı èlun}
{191301}{}{Nìjakı druh vesmírné lodi. Má poznávací znaèku s nápisem IMPVEDE!}
{191400}{}{Imperiální vısadkovı èlun}
{191401}{}{Nìjakı druh vesmírné lodi. Má poznávací znaèku s nápisem IMPVEDE!}
{191500}{}{Millennium Falcon}
{191501}{}{Vypadá to jako pìkná plechovka. Všimneš si dvojice chlupatıch kostek na zpìtném zrcátku.}
{191600}{}{Hoøící koš na uhlí}
{191601}{}{Tento uhlák je plnı hoøícího uhlí.}
{191700}{}{Kost}
{191701}{}{}
{191800}{}{Kost}
{191900}{}{Kost}
{192000}{}{Kosti}
{192001}{}{Roztroušené ostatky.}
{192100}{}{Kosti}
{192101}{}{Jsou lidské!}
{192200}{}{Kosti}
{192201}{}{Roztroušené lidské kosti.}
{192300}{}{Kosti}
{192400}{}{Kosti}
{192500}{}{Kosti}
{192501}{}{Roztroušené lidské kosti.}
{192600}{}{Kosti}
{192601}{}{Roztroušené lidské pozùstatky.}
{192700}{}{Kosti}
{192701}{}{Jsou lidské!}
{192800}{}{Kosti}
{192900}{}{Betonová zábrana}
{193000}{}{Betonová zábrana}
{193100}{}{Bezpeènostní dveøe}
{193101}{}{Tyto dveøe vypadají velmi pevnì.}
{193200}{}{Bezpeènostní dveøe}
{193201}{}{Tyto rezavé dveøe vypadají stále velmi pevnì.}
{193300}{}{Šachta vıtahu}
{193400}{}{Šachta vıtahu}
{193401}{}{Šachta je èásteènì zøícená.}
{193500}{}{Šachta vıtahu}
{193501}{}{Za hranu vıtahove šachty je upevnìné lano.}
{193600}{}{Šachta vıtahu}
{193601}{}{Ve vıtahovì šachtì je porouchanı vıtah a upevnìné lano.}
{193700}{}{Šachta vıtahu}
{193701}{}{Ve vıtahovì šachtì chybí vıtah. Velmi nebezpeèné!}
{193800}{}{Rezavé potrubí}
{193801}{}{Nìkolik starıch rezavıch trubek.}
{193900}{}{Generátor}
{193901}{}{Generátor Wattz ElectroBox. Standardnì pouívanı jako záloní generátor v pøedváleèném období.}
{194000}{}{Generátor}
{194001}{}{Pojistková skøíò Wattz ElectroBox. Standardnì pouívanı jako záloní generátor v pøedváleèném období.}
{194100}{}{Elektrickı stroj}
{194101}{}{Ze stroje vychází zvuk bzuèící elektøiny.}
{194200}{}{Malı monitor}
{194201}{}{Na tomto monitoru nìkdo hovoøí.}
{194300}{}{Monitor}
{194301}{}{Velkı èernobílı monitor. Na tomto monitoru nìjaká ena pøednáší o morálce.}
{194400}{}{Monitor}
{194401}{}{Velkı èernobílı monitor. Tento varuje pøed jadernım spadem.}
{194500}{}{Monitor}
{194501}{}{Velkı èernobílı monitor. Bìí na nìm podivnı film, kterı se zasekl v nekoneèné smyèce.}
{194600}{}{Velkı monitor}
{194601}{}{Velkı èernobílı monitor. Na tomto je postava v energo zbroji.}
{194700}{}{Monitor}
{194701}{}{Velkı èernobílı monitor. Na tomto monitoru je uhlazenı, ale prostì vyhlíející mu, kterı bez pøestání vaní.}
{194800}{}{Monitor}
{194801}{}{A large monitor, black and white only. The picture is of a rotating cross and circle.}
{194900}{}{spare}
{195000}{}{spare}
{195100}{}{Stín}
{195200}{}{Stín}
{195300}{}{Velké ulepené mechanické èerpadlo}
{195301}{}{Vidíš velké mechanické èerpadlo pokryté nìjakou podivnou biologickou hmotou.}
{195400}{}{Podlahovı rošt}
{195401}{}{Rezavı podlahovı rošt.}
{195500}{}{Velké mechanické èerpadlo}
{195501}{}{Velká mechanické èerpadlo vystupující skrz rošt v podlaze.}
{195600}{}{Velké ulepené mechanické èerpadlo}
{195601}{}{Vidíš velké mechanické èerpadlo pokryté nìjakou podivnou biologickou hmotou.}
{195700}{}{Znièené velké ulepené mechanické èerpadlo}
{195701}{}{Vidíš velké mechanické èerpadlo pokryté nìjakou podivnou biologickou hmotou. Jeho pumpovací dny jsou seèteny.}
{195800}{}{Znièené velké ulepené mechanické èerpadlo}
{195801}{}{Vidíš velké mechanické èerpadlo pokryté nìjakou podivnou biologickou hmotou. Jeho pumpovací dny jsou seèteny.}
{195900}{}{Dutina v podlaze}
{196000}{}{Velké mechanické èerpadlo}
{196001}{}{Velká mechanické èerpadlo vystupující skrz rošt v podlaze.}
{196100}{}{Velké mechanické èerpadlo}
{196101}{}{Velká mechanické èerpadlo vystupující skrz rošt v podlaze.}
{196200}{}{Hromada pneumatik}
{196201}{}{Hromada starıch gumovıch pneumatik. Jsou vulkanizované a ztvrdlé, pravdìpodobnì pùsobením horka.}
{196300}{}{Gumové pneumatiky}
{196301}{}{Dvì staré gumové pneumatiky. Jsou vulkanizované a ztvrdlé, pravdìpodobnì pùsobením horka.}
{196400}{}{Gumová pneumatika}
{196401}{}{Stará gumová pneumatika. Je vulkanizovaná a ztvrdlá, pravdìpodobnì pùsobením horka.}
{196500}{}{Velká turbína}
{196501}{}{Velká rotující turbína.}
{196600}{}{Vìtrací otvor}
{196601}{}{Vzduchová ventilace, která zásobuje celı komplex èistım vzduchem.}
{196700}{}{Vìtrací otvor}
{196701}{}{Vzduchová ventilace, která zásobuje celı komplex èistım vzduchem.}
{196800}{}{Vzduchová ventilace}
{196900}{}{Vzduchová ventilace}
{197000}{}{Rezavá vzduchová ventilace}
{197001}{}{Tato ventilace je rezavá a zablokovaná.}
{197100}{}{Rezavá vzduchová ventilace}
{197101}{}{Tato ventilace je rezavá a zablokovaná.}
{197200}{}{Rezavá vzduchová ventilace}
{197201}{}{Tato rezavá ventilace je zablokovaná.}
{197300}{}{Stìna}
{197400}{}{Stìna}
{197500}{}{Døevìné obloení}
{197600}{}{Vìtrací otvor}
{197700}{}{Vìtrací otvor}
{197800}{}{Studna}
{197801}{}{Typická studna, která je k nalezení v pustinì.}
{197900}{}{Schody}
{197901}{}{Široké schodištì.}
{198000}{}{Široké rezavé schody}
{198001}{}{Tyto schody pomalu sírá rez.}
{198100}{}{Široké rezavé schody}
{198101}{}{Tyto schody pomalu sírá rez.}
{198200}{}{Schùdky}
{198201}{}{Typické schùdky.}
{198300}{}{Rezavé schùdky}
{198301}{}{Tyto schùdky sírá rez.}
{198400}{}{Zaseknutı ventilátor}
{198401}{}{Ve vìtráku je zaseknutı kus eleza.}
{198500}{}{Vzduchová ventilace}
{198501}{}{Standardní ventilaèní systém Vault-Tec.}
{198600}{}{Ocelová stìna}
{198700}{}{Ocelová stìna}
{198800}{}{Ocelová stìna}
{198900}{}{Ocelová stìna}
{199000}{}{Ocelová stìna}
{199100}{}{Rezavé potrubí}
{199200}{}{Potrubí}
{199300}{}{Garáová vrata}
{199400}{}{Garáová vrata}
{199500}{}{Obøí mìdìná socha}
{199501}{}{Tato majestátní socha vystupuje pøímo ze zemì. Cítíš slabı zápach opièí moèi.}
{199600}{}{Obøí mìdìná socha}
{199601}{}{Tato majestátní socha vystupuje pøímo ze zemì. Cítíš slabı zápach opièí moèi.}
{199700}{}{Obøí mìdìná socha}
{199701}{}{Tato majestátní socha vystupuje pøímo ze zemì. Cítíš slabı zápach opièí moèi.}
{199800}{}{Obøí mìdìná socha}
{199801}{}{Tato majestátní socha vystupuje pøímo ze zemì. Cítíš slabı zápach opièí moèi.}
{199900}{}{Obøí mìdìná socha}
{199901}{}{Tato majestátní socha vystupuje pøímo ze zemì. Cítíš slabı zápach opièí moèi.}
{200000}{}{Stín}
{200001}{}{Stín}
{200100}{}{Stín}
{200200}{}{Suspenzní nádr}
{200201}{}{Nìjaké lékaøské nebo experimentální zaøízení. Uvnitø je nìjaká podivná zelená tekutina.}
{200300}{}{Vodní nádr}
{200301}{}{Velkı zásobník na tekutiny. V tomto pøípadì to bude asi nádr na vodu.}
{200400}{}{Dveøe}
{200500}{}{Glóbus EPA}
{200501}{}{Rezavìjící logo spoleènosti.}
{200600}{}{Stín}
{200700}{}{Strategickı stùl}
{200800}{}{Strategickı stùl}
{200900}{}{Bezpeènostní dveøe}
{200901}{}{Tyto dveøe vypadají velmi pevnì.}
{201000}{}{Cedule "EPA"}
{201100}{}{Cedule "EPA"}
{201200}{}{Cedule EPA}
{201201}{}{Kovová cedule s nápisem EPA.}
{201300}{}{Cedule EPA}
{201301}{}{Kovová cedule s nápisem EPA.}
{201400}{}{Rezavìjící cedule EPA}
{201401}{}{Tuto kovovou ceduli pomalu sírá rez.}
{201500}{}{Kovová deska}
{201501}{}{Kovová deska s èíslem 1.}
{201600}{}{Kovová deska}
{201601}{}{Kovová deska s èíslem 2.}
{201700}{}{Kovová deska}
{201701}{}{Kovová deska s èíslem 3.}
{201800}{}{Kovová deska}
{201801}{}{Kovová deska s èíslem 4.}
{201900}{}{Kovová deska}
{201901}{}{Kovová deska s èíslem 5.}
{202000}{}{Kovová deska}
{202001}{}{Kovová deska s èíslem 6.}
{202100}{}{Muzejní obraz}
{202200}{}{Muzejní obraz}
{202300}{}{Muzejní obraz}
{202400}{}{Glóbus EPA}
{202401}{}{Logo spoleènosti EPA.}
{202500}{}{Stín}
{202600}{}{Stín}
{202700}{}{Stín}
{202800}{}{Plakát s dívkou}
{202900}{}{Plakát s dívkou}
{203000}{}{Plakát s dívkou}
{203100}{}{Plakát s dívkou}
{203200}{}{Plakát s dívkou}
{203300}{}{Plakát s dívkou}
{203400}{}{Plakát s dívkou}
{203500}{}{Plakát s dívkou}
{203600}{}{Plakát s dívkou}
{203700}{}{Plakát s dívkou}
{203800}{}{Plakát s dívkou}
{203900}{}{Plakát s dívkou}
{204000}{}{Plakát s dívkou}
{204100}{}{Plakát s dívkou}
{204200}{}{Plakát s dívkou}
{204300}{}{Plakát s dívkou}
{204400}{}{Plakát s dívkou}
{204500}{}{Plakát s dívkou}
{204600}{}{}
{204601}{}{}
{204700}{}{Koberec}
{204701}{}{Starı tkanı koberec.}
{204800}{}{Koberec}
{204801}{}{Starı tkanı koberec.}
{204900}{}{Nádoba}
{204901}{}{Kvalitnì vyrobená nádoba.}
{205000}{}{Nádoba}
{205001}{}{Kvalitnì vyrobená nádoba.}
{205100}{}{Nádoba}
{205101}{}{Kvalitnì vyrobená nádoba.}
{205200}{}{Nádoba}
{205201}{}{Kvalitnì vyrobená nádoba.}
{205300}{}{Vzduchová ventilace}
{205400}{}{Vzduchová ventilace}
{205500}{}{Vnìjší dveøe vaultu}
{205501}{}{Tyto mohutné dveøe jsou jedinou spojnicí mezi vaultem a vnìjším svìtem.}
{205600}{}{Rezavìjící vnìjší dveøe vaultu}
{205601}{}{Tyto mohutné dveøe jsou jedinou spojnicí mezi vaultem a vnìjším svìtem.}
{205700}{}{Rezavìjící vnìjší dveøe vaultu}
{205701}{}{Tyto mohutné dveøe jsou jedinou spojnicí mezi vaultem a vnìjším svìtem.}
{205800}{}{Rezavìjící vnìjší dveøe vaultu}
{205801}{}{Mechanismus zajišující otevírání a zavírání tìkıch dveøí vaultu byl nenávratnì poškozen.}
{205900}{}{Rezavìjící vnìjší dveøe vaultu}
{205901}{}{Mechanismus dveøí byl vyøazen.}
{206000}{}{Vnìjší dveøe vaultu}
{206001}{}{Tyto mohutné dveøe jsou jedinou spojnicí mezi vaultem a vnìjším svìtem.}
{206100}{}{Nádoba}
{206101}{}{Kvalitnì vyrobená nádoba.}
{206200}{}{Nádoba}
{206201}{}{Kvalitnì vyrobená nádoba.}
{206300}{}{Nádoba}
{206301}{}{Kvalitnì vyrobená nádoba.}
{206400}{}{Nádoba}
{206401}{}{Kvalitnì vyrobená nádoba.}
{206500}{}{Stìna}
{206600}{}{Silové pole}
{206700}{}{Kovová deska}
{206701}{}{Kovová deska s èíslem 7.}
{206800}{}{Kameny}
{206801}{}{Velká hromada kamení.}
{206900}{}{Kameny}
{206901}{}{Velká hromada kamení.}
{207000}{}{Rezavìjící vıtah}
{207001}{}{Tento rezavìjící vıtah zajišuje pøepravu mezi podlaími.}
{207100}{}{Špinavá odpadní voda}
{207200}{}{elezná káï}
{207201}{}{Velká elezná káï s nìjakou podivnou zelenou tekutinou uvnitø.}
{207300}{}{Bezpeènostní dveøe}
{207301}{}{Tyto dveøe vypadají velmi pevnì.}
{207400}{}{Ošoupanı koberec}
{207401}{}{Starı tkanı koberec.}
{207500}{}{Ošoupanı koberec}
{207501}{}{Starı tkanı koberec.}
{207600}{}{Obraz NCR}
{207601}{}{Obraz s vlajkou NCR.}
{207700}{}{Obraz NCR}
{207701}{}{Obraz s vlajkou NCR.}
{207800}{}{Obraz NCR}
{207801}{}{Obraz s vlajkou NCR.}
{207900}{}{Hory}
{207901}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{208000}{}{Hory}
{208001}{}{Tato skalní stìna vypadá velmi nepøístupnì.}
{208100}{}{Obraz}
{208200}{}{Obraz}
{208300}{}{Obraz}
{208400}{}{Vìtrací otvor}
{208500}{}{Vìtrací otvor}
{208600}{}{Vìtrací otvor}
{208700}{}{Vìtrací otvor}
{208800}{}{Vìtrací otvor}
{208900}{}{Vìtrací otvor}
{209000}{}{Døevìné obloení}
{209100}{}{Døevìné obloení}
{209200}{}{Vìtrací otvor}
{209300}{}{Vìtrací otvor}
{209400}{}{Potrubí}
{209500}{}{Potrubí}
{209600}{}{Potrubí}
{209700}{}{Potrubí}
{209800}{}{Potrubí}
{209900}{}{Potrubí}
{210000}{}{Bezpeènostní dveøe}
{210001}{}{Tyto elezné dveøe jsou zabudovány do skalního masivu.}
{210100}{}{Vnìjší dveøe vaultu}
{210101}{}{Tyto elezné dveøe jsou zabudovány do skalního masivu. Zdá se, e pøestály vıbuch atomové bomby.}
{210200}{}{Vnìjší dveøe vaultu}
{210201}{}{Tyto velké dveøe jsou jedinou spojnicí mezi vaultem a vnìjším svìtem. Byly seehnuty obrovskım vıbuchem.}
{210300}{}{- Vchod do jeskynì}
{210301}{}{Zdá se, e jeskynì ústí do vìtšího komplexu jeskyní.}
{210400}{}{Vstupní poèítaè}
{210401}{}{Tento poèítaè ovládá vstupní dveøe do vaultu. Pøed vstupem musíš zadat pøístupovı kód.}
{210500}{}{Rezivìjící loï}
{210501}{}{Tato loï nevypadá, e by byla schopna plavby.}
{210600}{}{Rezivìjící loï}
{210601}{}{Tato loï nevypadá, e by byla schopna plavby.}
{210700}{}{Vyvazovací pachole}
{210701}{}{Lano vede z vyvazovací pachole k lodi.}
{210800}{}{Vyvazovací pachole}
{210801}{}{Lano vede z vyvazovací pachole k lodi.}
{210900}{}{Rezavìjící poklop ponorky}
{210901}{}{S trochou úsilí by šel poklop otevøít.}
{211000}{}{Rezavìjící vì ponorky}
{211001}{}{Zub èasu a slaná voda pomalu ale jistì sírají tento rezavìjící vrak.}
{211100}{}{Rezavìjící vì ponorky}
{211101}{}{Zub èasu a slaná voda pomalu ale jistì sírají tento rezavìjící vrak.}
{211200}{}{Rezavìjící ebøík}
{211201}{}{Slaná voda postupnì rozpouští tento eleznı ebøík.}
{211300}{}{Rezavìjící vì ponorky}
{211301}{}{Zub èasu a slaná voda pomalu ale jistì sírají tento rezavìjící vrak.}
{211400}{}{Rezivìjící loï}
{211401}{}{Tato loï nevypadá, e by byla schopna plavby.}
{211500}{}{Zakalenı oceán}
{211600}{}{Rezavìjící trup}
{211601}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{211700}{}{Rezavìjící trup}
{211701}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{211800}{}{Rezavìjící trup}
{211801}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{211900}{}{Zakalenı oceán}
{212000}{}{Rezavìjící trup}
{212001}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{212100}{}{Rezavìjící trup}
{212101}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{212200}{}{Zakalenı oceán}
{212300}{}{Zakalenı oceán}
{212400}{}{Zakalenı oceán}
{212500}{}{Zakalenı oceán}
{212600}{}{Zakalenı oceán}
{212700}{}{Rezavìjící trup}
{212701}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{212800}{}{Rezavìjící trup}
{212801}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{212900}{}{Rezivìjící loï}
{212901}{}{Tato loï nevypadá, e by byla schopna plavby.}
{213000}{}{Zakalenı oceán}
{213100}{}{Rezavìjící trup}
{213101}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{213200}{}{Rezavìjící trup}
{213201}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{213300}{}{Zakalenı oceán}
{213400}{}{Zakalenı oceán}
{213500}{}{Zakalenı oceán}
{213600}{}{Rezavìjící trup}
{213601}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{213700}{}{Rezavìjící trup}
{213701}{}{Trup ponorky je ponoøen pod hladinou zakaleného oceánu.}
{213800}{}{Zakalenı oceán}
{213900}{}{Zakalenı oceán}
{214000}{}{Zakalenı oceán}
{214100}{}{Rezavìjící trup}
{214200}{}{Torpédomet}
{214201}{}{Tyto kovové roury na sobì mají spoustu bezpeènostních opatøení. Zdá se, e jsou stále funkèní.}
{214300}{}{Rezavìjící trup}
{214301}{}{Rezavìjící trup}
{214400}{}{Rezavìjící trup}
{214500}{}{Rezavìjící trup}
{214600}{}{Rezavìjící trup}
{214700}{}{Torpéda}
{214701}{}{Torpéda}
{214800}{}{Torpéda}
{214801}{}{Torpéda}
{214900}{}{Torpéda}
{214901}{}{Torpéda}
{215000}{}{Rezavìjící trup}
{215100}{}{Rezavìjící trup}
{215200}{}{Rezavìjící trup}
{215300}{}{Rezavı stroj}
{215400}{}{Rezavı stroj}
{215500}{}{Torpéda}
{215501}{}{Torpéda}
{215600}{}{Torpéda}
{215601}{}{Torpéda}
{215700}{}{Rezavı stroj}
{215800}{}{Rezavìjící trup}
{215900}{}{Rezavı stroj}
{216000}{}{Rezavìjící trup}
{216100}{}{Rezavı stroj}
{216200}{}{Rezavı stroj}
{216300}{}{Rezavı stroj}
{216400}{}{Rezavı stroj}
{216500}{}{Rezavìjící trup}
{216600}{}{Rezavìjící trup}
{216700}{}{Rezavìjící trup}
{216800}{}{Rezavìjící trup}
{216900}{}{Rezavìjící trup}
{217000}{}{Rezavìjící trup}
{217100}{}{Rezavìjící trup}
{217200}{}{Rezavìjící trup}
{217300}{}{Dveøe ponorky}
{217400}{}{idle}
{217500}{}{idle}
{217600}{}{Poutaè Poseidon Oil}
{217601}{}{V tomto starém neonovém poutaèi zbylo ještì trochu ivota.}
{217700}{}{Masivní ocelové dveøe vaultu}
{217701}{}{Tyto ocelové dveøe jsou prakticky neznièitelné.}
{218800}{}{Vì ponorky}
{218900}{}{Vì ponorky}
{219000}{}{Schody}
{219001}{}{Døevìné schody.}
{219100}{}{Schody}
{219101}{}{Døevìné schody.}
{219200}{}{Schody}
{219201}{}{Døevìné schody.}
{219300}{}{ebøík}
{219400}{}{Rezavìjící poklop ponorky}
{219500}{}{Rezavìjící poklop ponorky}
{219501}{}{S trochou úsilí by šel poklop otevøít.}
{219600}{}{AutoDok}
{219700}{}{}
{219800}{}{Zatykaè}
{219801}{}{Náèrtek potrétu èlovìka hledaného místním zákonem.}
{219900}{}{Ventilátor}
{220000}{}{Zaseknutı ventilátor}
{220100}{}{Rezavé ocelové zábradlí}
{220200}{}{Cedule}
{220201}{}{Cedule s nápisem: Smíšené zboí.}
{220300}{}{Ošoupanı koberec}
{220301}{}{Obyèejnı koberec. Tkalec byl oèividnì velmi talentovanı.}
{220400}{}{Záøící kosti}
{220401}{}{Hromada záøících zvíøecích kostí. Tedy, myslíš si, e jsou zvíøecí...}
{220500}{}{Záøící kosti}
{220501}{}{Hromada záøících zvíøecích kostí. Tedy, myslíš si, e jsou zvíøecí...}
{220600}{}{Záøící kosti}
{220601}{}{Velká hromada záøících kostí. Nedokáeš urèit, co to bylo za tvory.}
{220700}{}{Záøící kosti}
{220701}{}{Myslíš si, e jsou to kosti rohatého klokana, ale nevíš to jistì. Pro pøesné urèení jsou bohuel pøíliš zvìtralé a záøící.}
{220800}{}{Záøící kosti}
{220801}{}{Vidíš kosti veliké dvouhlavé krávy.}
{220900}{}{Sesuv}
{220901}{}{Velká spousta záøícího kamení. Víc, ne dokáeš unést.}
{221000}{}{Záøící eleznı poklop}
{221001}{}{Tìkı záøící poklop. Zdá se, e je v dobrém stavu a nedávno se s ním hıbalo.}
{221100}{}{Záøící otvor do kanálu}
{221101}{}{Vypadá to jako pøístupovı otvor do kanalizace. A záøí zelenì!}
{221200}{}{Záøící stalagmit}
{221201}{}{Pøírodní vırùstek z kamenné podlahy. Záøí zelenì!}
{221300}{}{Záøící stalagmit}
{221301}{}{Pøírodní vırùstek z kamenné podlahy. Záøí zelenì!}
{221400}{}{Záøící kamennı sloup}
{221401}{}{Tento tlustı kamennı sloup vede od podlahy a ke stropu. A záøí!}
{221500}{}{Záøící kamennı sloup}
{221501}{}{Tento tlustı kamennı sloup vede od podlahy a ke stropu. A záøí!}
{221600}{}{Záøící stìna jeskynì}
{221700}{}{Záøící stìna jeskynì}
{221800}{}{Záøící stìna jeskynì}
{221900}{}{Záøící stìna jeskynì}
{222000}{}{Záøící stìna jeskynì}
{222100}{}{Záøící stìna jeskynì}
{222200}{}{Záøící stìna jeskynì}
{222300}{}{Záøící stìna jeskynì}
{222400}{}{Záøící stìna jeskynì}
{222500}{}{Záøící stìna jeskynì}
{222600}{}{Záøící stìna jeskynì}
{222700}{}{Záøící stìna jeskynì}
{222800}{}{Záøící stìna jeskynì}
{222900}{}{Záøící stìna jeskynì}
{223000}{}{Záøící stìna jeskynì}
{223100}{}{Záøící kameny}
{223101}{}{Hromada záøících kamenù. Nic zajímavého.}
{223200}{}{Záøící kameny}
{223201}{}{Hromada záøících kamenù. Nic zajímavého.}
{223300}{}{Záøící kameny}
{223301}{}{Hromádka záøících kamenù. Nic, co by tì mìlo zajímat.}
{223400}{}{Záøící kameny}
{223401}{}{Hromádka záøících kamenù.}
{223500}{}{Záøící kameny}
{223501}{}{Hromádka záøících kamenù.}
{223600}{}{Záøící kameny}
{223601}{}{Hromádka záøících kamenù.}
{223700}{}{Záøící kameny}
{223701}{}{Hromádka záøících kamenù.}
{223800}{}{Záøící kameny}
{223801}{}{Hromada záøících kamenù. Nic zajímavého.}
{223900}{}{Záøící skoøápky}
{223901}{}{Kousky rozbité skoøápky. A záøí!}
{224000}{}{Záøící skoøápky}
{224001}{}{Kousky rozbité skoøápky. A záøí!}
{224100}{}{Záøící skoøápky}
{224101}{}{Kousky rozbité skoøápky. A záøí!}
{224200}{}{Záøící skoøápky}
{224201}{}{Kousky rozbité skoøápky. A záøí!}
{224300}{}{Záøící kamínky}
{224301}{}{Roztroušené záøící kamínky.}
{224400}{}{Záøící kamínky}
{224401}{}{Roztroušené záøící kamínky.}
{224500}{}{Záøící kamínky}
{224501}{}{Roztroušené záøící kamínky.}
{224600}{}{Záøící skoøápky}
{224601}{}{Kousky rozbité skoøápky. A záøí!}
{224700}{}{Záøící døevìná prkna}
{224701}{}{Silná døevìná prkna pevnì svázaná dohromady.}
{224800}{}{Záøící døevìná prkna}
{224801}{}{Silná døevìná prkna pevnì svázaná dohromady.}
{224900}{}{ebøík}
{224901}{}{Starı vratkı záøící ebøík. Vypadá to, e tì stìí unese.}
{225000}{}{ebøík dolù}
{225001}{}{Umìle vytvoøenı otvor s ebøíkem vedoucím dolù.}
{225100}{}{Záøící kameny}
{225101}{}{Chvíli záøící kameny zkoumáš, ale nepohnuly se.}
{225200}{}{Záøící kameny}
{225201}{}{Dej si na tyto záøící kameny bedlivı pozor, tøeba na tebe chtìjí zaútoèit.}
{225300}{}{Záøící kameny}
{225301}{}{Velká hromada záøících kamenù. Vypadají radioaktivnì.}
{225400}{}{Záøící kameny}
{225401}{}{Hromádka záøících kamenù.}
{225500}{}{Záøící kameny}
{225501}{}{Hromádka záøících kamenù.}
{225600}{}{Záøící kameny}
{225601}{}{Hromádka záøících kamenù.}
{225700}{}{Záøící kameny}
{225701}{}{Velká hromada záøících kamenù. Vypadají nebezpeènì i kdy jen tak leí.}
{225800}{}{Záøící kameny}
{225801}{}{Velká hromada záøících kamenù. Kdy se podíváš zblízka, vidíš po stranách tváøe malıch starıch muù.}
{225900}{}{Záøící kameny}
{225901}{}{Kameny, kameny, kameny! Záøící kameny všude kam se podíváš!}
{226000}{}{Záøící kameny}
{226001}{}{Hromádka záøících kamenù.}
{226100}{}{Záøící kameny}
{226200}{}{Záøící kameny}
{226300}{}{Záøící kameny}
{226400}{}{Záøící kameny}
{226500}{}{Záøící kameny}
{226600}{}{Záøící kameny}
{226700}{}{Záøící kameny}
{226800}{}{Záøící stìna}
{226900}{}{Záøící stìna}
{227000}{}{Záøící stìna}
{227100}{}{Záøící stìna}
{227200}{}{Záøící stìna}
{227300}{}{Záøící stìna}
{227400}{}{Záøící stoka}
{227401}{}{Z kanálu vychází jakısi odpornı zápach. Ale po chvíli u to není tak strašné.}
{227500}{}{Záøící stoka}
{227501}{}{Skrz møí zahlédneš nìjakı pohyb. Ze tmy na tebe zírají zelené záøící oèi. Krysí oèi.}
{227600}{}{Záøící stoka}
{227601}{}{Z kanálu se line zvuk bublající vody. A také pøíšernı zápach.}
{227700}{}{Záøící stoka}
{227701}{}{Z kanálu se line zvuk bublající vody. A také pøíšernı smrad.}
{227800}{}{Špinavá postel}
{227801}{}{Po bliším prozkoumání docházíš k závìru, e prostìradlo nebylo vymìnìno u velmi, velmi dlouho.}
{227900}{}{Špinavá postel}
{227901}{}{Po bliším prozkoumání docházíš k závìru, e prostìradlo nebylo vymìnìno u velmi, velmi dlouho.}
{228000}{}{Špinavá postel}
{228001}{}{Po bliším prozkoumání docházíš k závìru, e prostìradlo nebylo vymìnìno u velmi, velmi dlouho.}
{228100}{}{Sklo}
{228101}{}{Pøes toto sklo je špatnì vidìt.}
{228200}{}{Sklo}
{228201}{}{Pøes toto sklo je špatnì vidìt.}
{228300}{}{Sklo}
{228301}{}{Pøes toto sklo je špatnì vidìt.}
{228400}{}{Sklo}
{228401}{}{Toto sklo je stìí prùhledné.}
{228500}{}{Sklo}
{228501}{}{Toto sklo je stìí prùhledné.}
{228600}{}{Sklo}
{228601}{}{Toto sklo je stìí prùhledné.}
{228700}{}{elezné dveøe}
{228701}{}{Pevné elezné dveøe.}
{228800}{}{elezné dveøe}
{228801}{}{Pevné elezné dveøe.}
{228900}{}{Stráná bouda}
{228901}{}{Stráná bouda.}
{229000}{}{Stráná bouda}
{229001}{}{Stráná bouda.}
{229100}{}{Zelená bublající tekutina}
{229101}{}{Zelená bublající tekutina. Má zvláštní zápach.}
{229200}{}{Tìká laserová vì}
{229201}{}{Laserová vì postavená na betonové vìi.}
{229300}{}{Tìká laserová vì}
{229301}{}{Vì se vıhrunì otáèí.}
{229400}{}{Tìká laserová vì}
{229401}{}{Laserová vì postavená na betonové vìi.}
{229500}{}{Tìká laserová vì}
{229501}{}{Vì se vıhrunì otáèí.}
{229800}{}{Filmovı plakát}
{229801}{}{Starı otrhanı plakát s filmem "Somrák s brokárnou".}
{229900}{}{Podivnì vypadající tvor}
{229901}{}{Mrtvé tìlo obrostlé rostlinnım porostem.}
{230000}{}{Podivnì vypadající tvor}
{230001}{}{Mrtvé tìlo obrostlé rostlinnım porostem.}
