{100}{}{Potrzebujesz %d pkt. akcji.}
{101}{}{Brak amunicji.}
{102}{}{Cel poza zasiêgiem.}
{103}{}{Nie mo¿esz przerwaæ walki, gdy w pobli¿u znajduj¹ siê wrogowie.}
{104}{}{Linia strza³u zablokowana.}
{105}{}{Nie mo¿esz u¿ywaæ broni maj¹c okaleczone obie rêce.}
{106}{}{Nie mo¿esz u¿ywaæ broni oburêcznej maj¹c okaleczon¹ rêkê.}
{107}{}{Nie masz wystarczaj¹co du¿o si³y, by prawid³owo pos³ugiwaæ siê t¹ broni¹.}
{108}{}{ i }
{200}{}{traci przytomnoœæ}
{201}{}{upada}
{202}{}{ma okaleczon¹ lew¹ nogê}
{203}{}{ma okaleczon¹ praw¹ nogê}
{204}{}{ma okaleczon¹ lew¹ rêkê}
{205}{}{ma okaleczon¹ praw¹ rêkê}
{206}{}{traci wzrok}
{207}{}{ginie}
{208}{}{obrywa}
{209}{}{krytycznie}
{210}{}{p³onie}
{211}{}{dostaje pomimo pancerza}
{212}{}{broñ eksploduje}
{213}{}{broñ ulega zniszczeniu}
{214}{}{upuszcza broñ na ziemiê}
{215}{}{traci kolejn¹ turê}
{216}{}{trafia siebie}
{217}{}{traci resztê amunicji}
{218}{}{odpala niewypa³}
{219}{}{trafia siebie}
{220}{}{przypadkowo obrywa}
{221}{}{ma okaleczon¹ jedn¹ z koñczyn}
{222}{}{obrywa od³amkami}
{250}{}{traci przytomnoœæ}
{251}{}{upada}
{252}{}{ma okaleczon¹ lew¹ nogê}
{253}{}{ma okaleczon¹ praw¹ nogê}
{254}{}{ma okaleczon¹ lew¹ rêkê}
{255}{}{ma okaleczon¹ praw¹ rêkê}
{256}{}{traci wzrok}
{257}{}{ginie}
{258}{}{obrywa}
{259}{}{krytycznie}
{260}{}{p³onie}
{261}{}{dostaje pomimo pancerza}
{262}{}{broñ eksploduje}
{263}{}{broñ ulega zniszczeniu}
{264}{}{upuszcza broñ na ziemiê}
{265}{}{traci kolejn¹ turê}
{266}{}{trafia siebie}
{267}{}{traci resztê amunicji}
{268}{}{odpala niewypa³}
{269}{}{trafia siebie}
{270}{}{przypadkowo obrywa}
{271}{}{ma okaleczon¹ jedn¹ z koñczyn}
{272}{}{obrywa od³amkami}
{300}{}{traci przytomnoœæ}
{301}{}{upada}
{302}{}{ma okaleczon¹ lew¹ nogê}
{303}{}{ma okaleczon¹ praw¹ nogê}
{304}{}{ma okaleczon¹ lew¹ rêkê}
{305}{}{ma okaleczon¹ praw¹ rêkê}
{306}{}{traci wzrok}
{307}{}{ginie}
{308}{}{obrywa}
{309}{}{krytycznie}
{310}{}{p³onie}
{311}{}{dostaje pomimo pancerza}
{312}{}{broñ eksploduje}
{313}{}{broñ ulega zniszczeniu}
{314}{}{upuszcza broñ na ziemiê}
{315}{}{traci kolejn¹ turê}
{316}{}{trafia siebie}
{317}{}{traci resztê amunicji}
{318}{}{odpala niewypa³}
{319}{}{trafia siebie}
{320}{}{przypadkowo obrywa}
{321}{}{ma okaleczon¹ jedn¹ z koñczyn}
{322}{}{obrywa od³amkami}
{400}{}{traci przytomnoœæ}
{401}{}{upada}
{402}{}{ma okaleczon¹ lew¹ nogê}
{403}{}{ma okaleczon¹ praw¹ nogê}
{404}{}{ma okaleczon¹ lew¹ rêkê}
{405}{}{ma okaleczon¹ praw¹ rêkê}
{406}{}{traci wzrok}
{407}{}{ginie}
{408}{}{obrywa}
{409}{}{krytycznie}
{410}{}{p³onie}
{411}{}{dostaje pomimo pancerza}
{412}{}{broñ eksploduje}
{413}{}{broñ ulega zniszczeniu}
{414}{}{upuszcza broñ na ziemiê}
{415}{}{traci kolejn¹ turê}
{416}{}{trafia siebie}
{417}{}{traci resztê amunicji}
{418}{}{odpala niewypa³}
{419}{}{trafia siebie}
{420}{}{przypadkowo obrywa}
{421}{}{ma okaleczon¹ jedn¹ z koñczyn}
{422}{}{obrywa od³amkami}
{506}{}{Twoja postaæ}
{509}{}{O rany! Obrywa %s, a nie %s!}
{511}{}{%s krytycznie obrywa %s, trac¹c %d PW}
{512}{}{%s obrywa %s, trac¹c %d PW}
{513}{}{%s traci %d PW}
{514}{}{%s haniebnie pud³uje}
{515}{}{%s nie trafia}
{520}{}{%s obrywa krytycznie, trac¹c %d PW}
{521}{}{%s krytycznie obrywa %s, trac¹c 1 pkt. wytrzyma³oœci}
{522}{}{%s dostaje %s, trac¹c 1 pkt. wytrzyma³oœci}
{523}{}{%s traci 1 pkt. wytrzyma³oœci}
{524}{}{%s obrywa krytycznie, trac¹c 1 pkt. wytrzyma³oœci}
{525}{}{%s krytycznie obrywa %s, lecz nie odnosi obra¿eñ}
{526}{}{%s dostaje %s, lecz nie odnosi obra¿eñ}
{527}{}{%s obrywa, lecz nie odnosi obra¿eñ}
{528}{}{%s obrywa krytycznie, lecz nie odnosi obra¿eñ}
{533}{}{%s haniebnie pud³uje i traci 1 pkt. wytrzyma³oœci}
{534}{}{%s haniebnie pud³uje i traci %d PW}
{556}{}{Twoja postaæ}
{559}{}{O rany! Obrywa %s, a nie %s!}
{561}{}{%s krytycznie obrywa %s, trac¹c %d PW}
{562}{}{%s obrywa %s, trac¹c %d PW}
{563}{}{%s traci %d PW}
{564}{}{%s haniebnie pud³uje}
{565}{}{%s nie trafia}
{570}{}{%s obrywa krytycznie, trac¹c %d PW}
{571}{}{%s krytycznie obrywa %s, trac¹c 1 pkt. wytrzyma³oœci}
{572}{}{%s dostaje %s, trac¹c 1 pkt. wytrzyma³oœci}
{573}{}{%s traci 1 pkt. wytrzyma³oœci}
{574}{}{%s obrywa krytycznie, trac¹c 1 pkt. wytrzyma³oœci}
{575}{}{%s krytycznie obrywa %s, lecz nie odnosi obra¿eñ}
{576}{}{%s dostaje %s, lecz nie odnosi obra¿eñ}
{577}{}{%s obrywa, lecz nie odnosi obra¿eñ}
{578}{}{%s obrywa krytycznie, lecz nie odnosi obra¿eñ}
{583}{}{%s haniebnie pud³uje i traci 1 pkt. wytrzyma³oœci}
{584}{}{%s haniebnie pud³uje i traci %d PW}
{608}{}{O rany! Obrywa %s, zamiast ciebie!}
{609}{}{O rany! Obrywa %s, a nie %s!}
{611}{}{%s krytycznie obrywa %s, trac¹c %d PW}
{612}{}{%s obrywa %s, trac¹c %d PW}
{613}{}{%s traci %d PW}
{614}{}{%s haniebnie pud³uje}
{615}{}{%s nie trafia}
{620}{}{%s obrywa krytycznie, trac¹c %d PW}
{621}{}{%s krytycznie obrywa %s, trac¹c 1 pkt. wytrzyma³oœci}
{622}{}{%s dostaje %s, trac¹c 1 pkt. wytrzyma³oœci}
{623}{}{%s traci 1 pkt. wytrzyma³oœci}
{624}{}{%s obrywa krytycznie, trac¹c 1 pkt. wytrzyma³oœci}
{625}{}{%s krytycznie obrywa %s, lecz nie odnosi obra¿eñ}
{626}{}{%s dostaje %s, lecz nie odnosi obra¿eñ}
{627}{}{%s obrywa, lecz nie odnosi obra¿eñ}
{628}{}{%s obrywa krytycznie, lecz nie odnosi obra¿eñ}
{633}{}{%s haniebnie pud³uje i traci 1 pkt. wytrzyma³oœci}
{634}{}{%s haniebnie pud³uje i traci %d PW}
{708}{}{O rany! Obrywa %s, zamiast ciebie!}
{709}{}{O rany! Obrywa %s, a nie %s!}
{711}{}{%s krytycznie obrywa %s, trac¹c %d PW}
{712}{}{%s obrywa %s, trac¹c %d PW}
{713}{}{%s traci %d PW}
{714}{}{%s haniebnie pud³uje}
{715}{}{%s nie trafia}
{720}{}{%s obrywa krytycznie, trac¹c %d PW}
{721}{}{%s krytycznie obrywa %s, trac¹c 1 pkt. wytrzyma³oœci}
{722}{}{%s dostaje %s, trac¹c 1 pkt. wytrzyma³oœci}
{723}{}{%s traci 1 pkt. wytrzyma³oœci}
{724}{}{%s obrywa krytycznie, trac¹c 1 pkt. wytrzyma³oœci}
{725}{}{%s krytycznie obrywa %s, lecz nie odnosi obra¿eñ}
{726}{}{%s dostaje %s, lecz nie odnosi obra¿eñ}
{727}{}{%s obrywa, lecz nie odnosi obra¿eñ}
{728}{}{%s obrywa krytycznie, lecz nie odnosi obra¿eñ}
{733}{}{%s haniebnie pud³uje i traci 1 pkt. wytrzyma³oœci}
{734}{}{%s haniebnie pud³uje i traci %d PW}
{1110}{}{w g³owê}
{1111}{}{w lew¹ rêkê}
{1112}{}{w praw¹ rêkê}
{1113}{}{w pierœ}
{1114}{}{w praw¹ nogê}
{1115}{}{w lew¹ nogê}
{1116}{}{w oczy}
{1117}{}{w pachwinê}
{1118}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1150}{}{w g³owê}
{1151}{}{w lew¹ tyln¹ nogê}
{1152}{}{w praw¹ tyln¹ nogê}
{1153}{}{w pierœ}
{1154}{}{w praw¹ przedni¹ nogê}
{1155}{}{w lew¹ przedni¹ nogê}
{1156}{}{w oczy}
{1157}{}{w wymiê}
{1158}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1160}{}{w g³owê}
{1161}{}{w tyln¹ ³apê}
{1162}{}{w tyln¹ ³apê}
{1163}{}{w tu³ów}
{1164}{}{w przedni¹ ³apê}
{1165}{}{w przedni¹ ³apê}
{1166}{}{w oczy}
{1167}{}{w pachwinê}
{1168}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1170}{}{w CPU}
{1171}{}{w manipulator}
{1172}{}{w manipulator}
{1173}{}{w korpus}
{1174}{}{w motywator}
{1175}{}{w motywator}
{1176}{}{w czujniki}
{1177}{}{w regulator}
{1178}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1180}{}{w g³owê}
{1181}{}{w lew¹ rêkê}
{1182}{}{w praw¹ rêkê}
{1183}{}{w pierœ}
{1184}{}{w praw¹ nogê}
{1185}{}{w lew¹ nogê}
{1186}{}{w oczy}
{1187}{}{w pachwinê}
{1188}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1190}{}{w g³owê}
{1191}{}{w lew¹ ³apê}
{1192}{}{w praw¹ ³apê}
{1193}{}{w tu³ów}
{1194}{}{w praw¹ nogê}
{1195}{}{w lew¹ nogê}
{1196}{}{w oczy}
{1197}{}{w pachwinê}
{1198}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1210}{}{w g³owê}
{1211}{}{w lew¹ rêkê}
{1212}{}{w praw¹ rêkê}
{1213}{}{w pierœ}
{1214}{}{w praw¹ nogê}
{1215}{}{w lew¹ nogê}
{1216}{}{w oczy}
{1217}{}{w pachwinê}
{1218}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1220}{}{w g³owê}
{1221}{}{w ogon}
{1222}{}{w kleszcze}
{1223}{}{w korpus}
{1224}{}{w przednie nogi}
{1225}{}{w tylne nogi}
{1226}{}{w oczy}
{1227}{}{w mózg}
{1228}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1230}{}{w g³owê}
{1231}{}{w pysk}
{1232}{}{w przedpyszcze}
{1233}{}{w tu³ów}
{1234}{}{w pêcherz p³awny}
{1235}{}{w ogon}
{1236}{}{w zwój nerwowy}
{1237}{}{w pok³ade³ko}
{1238}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1240}{}{w g³owê}
{1241}{}{w lew¹ ³apê}
{1242}{}{w praw¹ ³apê}
{1243}{}{w tu³ów}
{1244}{}{w praw¹ nogê}
{1245}{}{w lew¹ nogê}
{1246}{}{w oczy}
{1247}{}{w pachwinê}
{1248}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1250}{}{w g³owê}
{1251}{}{w lew¹ rêkê}
{1252}{}{w praw¹ rêkê}
{1253}{}{w tu³ów}
{1254}{}{w praw¹ nogê}
{1255}{}{w lew¹ nogê}
{1256}{}{w oczy}
{1257}{}{w pachwinê}
{1258}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1270}{}{w g³owê}
{1271}{}{w lew¹ rêkê}
{1272}{}{w praw¹ rêkê}
{1273}{}{w pierœ}
{1274}{}{w praw¹ nogê}
{1275}{}{w lew¹ nogê}
{1276}{}{w oczy}
{1277}{}{w pachwinê}
{1278}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1460}{}{w g³owê}
{1461}{}{w lew¹ rêkê}
{1462}{}{w praw¹ rêkê}
{1463}{}{w pierœ}
{1464}{}{w praw¹ nogê}
{1465}{}{w lew¹ nogê}
{1466}{}{w oczy}
{1467}{}{w pachwinê}
{1468}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1490}{}{w g³owê}
{1491}{}{w lew¹ rêkê}
{1492}{}{w praw¹ rêkê}
{1493}{}{w pierœ}
{1494}{}{w praw¹ nogê}
{1495}{}{w lew¹ nogê}
{1496}{}{w oczy}
{1497}{}{w pachwinê}
{1498}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1500}{}{w g³owê}
{1501}{}{???}
{1502}{}{???}
{1503}{}{w korpus}
{1504}{}{???}
{1505}{}{???}
{1506}{}{w oczy}
{1507}{}{w CPU}
{1508}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1510}{}{w g³owê}
{1511}{}{w lew¹ rêkê}
{1512}{}{w praw¹ rêkê}
{1513}{}{w pierœ}
{1514}{}{w praw¹ nogê}
{1515}{}{w lew¹ nogê}
{1516}{}{w oczy}
{1517}{}{w pachwinê}
{1518}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1520}{}{w g³owê}
{1521}{}{w chwytak}
{1522}{}{w chwytak}
{1523}{}{w odw³ok}
{1524}{}{w nogi}
{1525}{}{w skrzyd³a}
{1526}{}{w oczy}
{1527}{}{w tu³ów}
{1528}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1530}{}{w CPU}
{1531}{}{w manipulator}
{1532}{}{w manipulator}
{1533}{}{w korpus}
{1534}{}{w motywator}
{1535}{}{w motywator}
{1536}{}{w czujniki}
{1537}{}{w regulator}
{1538}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1540}{}{w CPU}
{1541}{}{w manipulator}
{1542}{}{w manipulator}
{1543}{}{w korpus}
{1544}{}{w motywator}
{1545}{}{w motywator}
{1546}{}{w czujniki}
{1547}{}{w regulator}
{1548}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1550}{}{w g³owê}
{1551}{}{w lew¹ ³apê}
{1552}{}{w praw¹ ³apê}
{1553}{}{w tu³ów}
{1554}{}{w praw¹ nogê}
{1555}{}{w lew¹ nogê}
{1556}{}{w oczy}
{1557}{}{w pachwinê}
{1558}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1580}{}{w skorupê}
{1581}{}{w skorupê}
{1582}{}{w skorupê}
{1583}{}{w skorupê}
{1584}{}{w skorupê}
{1585}{}{w skorupê}
{1586}{}{w skorupê}
{1587}{}{w skorupê}
{1588}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1590}{}{w g³owê}
{1591}{}{w ogon}
{1592}{}{w kleszcze}
{1593}{}{w korpus}
{1594}{}{w przednie nogi}
{1595}{}{w tylne nogi}
{1596}{}{w oczy}
{1597}{}{w mózg}
{1598}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1600}{}{w g³owê}
{1601}{}{w lew¹ rêkê}
{1602}{}{w praw¹ rêkê}
{1603}{}{w pierœ}
{1604}{}{w praw¹ nogê}
{1605}{}{w lew¹ nogê}
{1606}{}{w oczy}
{1607}{}{w pachwinê}
{1608}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1650}{}{w pysk}
{1651}{}{w ³odygê}
{1652}{}{w ³odygê}
{1653}{}{w ³odygê centraln¹}
{1654}{}{w korzenie}
{1655}{}{w korzenie}
{1656}{}{w pn¹cza czuciowe}
{1657}{}{w nasadê}
{1658}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1660}{}{w g³owê}
{1661}{}{w rêkê - rakietnicê}
{1662}{}{w rêkê - giwerê}
{1663}{}{w tu³ów}
{1664}{}{w praw¹ nogê}
{1665}{}{w lew¹ nogê}
{1666}{}{w czujniki}
{1667}{}{w ni¿szy korpus}
{1668}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1670}{}{w g³owê}
{1671}{}{w lewego szpona}
{1672}{}{w prawego szpona}
{1673}{}{w tu³ów}
{1674}{}{w praw¹ nogê}
{1675}{}{w lew¹ nogê}
{1676}{}{w oczy}
{1677}{}{w pachwinê}
{1678}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1680}{}{w g³owê}
{1681}{}{w lewego szpona}
{1682}{}{w prawego szpona}
{1683}{}{w tu³ów}
{1684}{}{w praw¹ nogê}
{1685}{}{w lew¹ nogê}
{1686}{}{w oczy}
{1687}{}{w pachwinê}
{1688}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1800}{}{w g³owê}
{1801}{}{w lew¹ mackê}
{1802}{}{w praw¹ mackê}
{1803}{}{w tu³ów}
{1804}{}{w praw¹ stopê}
{1805}{}{w lew¹ stopê}
{1806}{}{w oczy}
{1807}{}{w organ rozrodczy}
{1808}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1850}{}{w g³owê}
{1851}{}{w lew¹ rêkê}
{1852}{}{w praw¹ rêkê}
{1853}{}{w pierœ}
{1854}{}{w praw¹ nogê}
{1855}{}{w lew¹ nogê}
{1856}{}{w oczy}
{1857}{}{w pachwinê}
{1858}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1860}{}{w g³owê}
{1861}{}{w lew¹ mackê}
{1862}{}{w praw¹ mackê}
{1863}{}{w tu³ów}
{1864}{}{w praw¹ stopê}
{1865}{}{w lew¹ stopê}
{1866}{}{w oczy}
{1867}{}{w organ rozrodczy}
{1868}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1900}{}{w jednostkê centraln¹}
{1901}{}{w mech. ster. dzia³em}
{1902}{}{w mech. ster. dzia³em}
{1903}{}{w korpus}
{1904}{}{w g³ówny mech. ster.}
{1905}{}{w g³ówny mech. ster.}
{1906}{}{w czujniki}
{1907}{}{w regulator}
{1908}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1970}{}{w g³owê}
{1971}{}{w lew¹ przedni¹ nogê}
{1972}{}{w praw¹ przedni¹ nogê}
{1973}{}{w odw³ok}
{1974}{}{w praw¹ tyln¹ nogê}
{1975}{}{w lew¹ tyln¹ nogê}
{1976}{}{w czu³ki}
{1977}{}{w tu³ów}
{1978}{}{w niezidentyfikowan¹ czêœæ cia³a}
{1990}{}{w g³owê}
{1991}{}{w lew¹ rêkê}
{1992}{}{w praw¹ rêkê}
{1993}{}{w pierœ}
{1994}{}{w praw¹ nogê}
{1995}{}{w lew¹ nogê}
{1996}{}{w oczy}
{1997}{}{w pachwinê}
{1998}{}{w niezidentyfikowan¹ czêœæ cia³a}
{2000}{}{w g³owê}
{2001}{}{w lew¹ rêkê}
{2002}{}{w praw¹ rêkê}
{2003}{}{w pierœ}
{2004}{}{w praw¹ nogê}
{2005}{}{w lew¹ nogê}
{2006}{}{w oczy}
{2007}{}{w pachwinê}
{2008}{}{w niezidentyfikowan¹ czêœæ cia³a}
{2010}{}{w jednostkê centraln¹}
{2011}{}{w mech. ster. dzia³em}
{2012}{}{w mech. ster. dzia³em}
{2013}{}{w korpus}
{2014}{}{w g³ówny mech. ster.}
{2015}{}{w g³ówny mech. ster.}
{2016}{}{w czujniki}
{2017}{}{w regulator}
{2018}{}{w niezidentyfikowan¹ czêœæ cia³a}
{2030}{}{w g³owê}
{2031}{}{w ¿¹d³o}
{2032}{}{w czu³ki}
{2033}{}{w korpus}
{2034}{}{w przednie nogi}
{2035}{}{w tylne nogi}
{2036}{}{w oczy}
{2037}{}{w skrzyd³a}
{2038}{}{w niezidentyfikowan¹ czêœæ cia³a}
{5000}{}{. To go naprawdê boli}
{5001}{}{. Serious pain is inflicted.}
{5002}{}{, jako ¿e nie chroni go pancerz}
{5003}{}{. To straszliwe uderzenie pozbawia go przytomnoœci}
{5004}{}{. Ten cios go powala}
{5005}{}{. Tak silny cios w g³owê od razu go nokautuje}
{5006}{}{. Trafienie zmienia jego skroñ w krwaw¹ miazgê. Dobranoc, Anio³ku}
{5007}{}{ - zgon jest natychmiastowy}
{5008}{}{. Biedak, cierpi teraz na ostry przypadek ³okcia tenisisty}
{5009}{}{. Wyszarpniêcie koñczyny ze stawu barkowego nie wyjdzie mu na zdrowie}
{5010}{}{. Zostaje mu po tym wielki siniak}
{5011}{}{. Jego lewe ramiê zosta³o powa¿nie okaleczone}
{5012}{}{. Jego lewa koñczyna dynda na strzêpie skóry}
{5013}{}{. To ramiê wygl¹da teraz jak zakrwawiony pieniek}
{5014}{}{. Okaleczenie jego prawego ramienia jest bardzo powa¿ne}
{5015}{}{. Jego prawe ramiê uleg³o zmia¿d¿eniu wskutek tego potê¿nego uderzenia}
{5016}{}{ na skutek tego mocarnego trafienia}
{5017}{}{ pomimo pancerza}
{5018}{}{. Dziêki temu otrzymuje on dodatkow¹ dawkê obra¿eñ}
{5019}{}{ oraz grunt pod nogami}
{5020}{}{, i pada po tym, jak si³a uderzenia pozbawi³a jego p³uca zapasu powietrza}
{5021}{}{. Niestety, od przodu mo¿na teraz z ³atwoœci¹ dostrzec jego krêgos³up}
{5022}{}{. W zamian otrzymuje solidn¹ dawkê bólu w dolnej koñczynie}
{5023}{}{. Zaraz po tym przewraca siê on jak k³oda}
{5024}{}{. Œwie¿o okaleczona koñczyna nie jest w stanie utrzymaæ jego ciê¿aru i w rezultacie traci on równowagê}
{5025}{}{, podczas gdy jego kolano zostaje zdruzgotane, a on sam upada}
{5026}{}{. Dotkliwy ból, wywo³any niespodziewan¹ utrat¹ koñczyny, pozbawia go œwiadomoœci}
{5027}{}{, co zwiêksza jego dawkê cierpienia}
{5028}{}{ oraz - niefortunnie dla niego - zdolnoœæ widzenia}
{5029}{}{, a jako ¿e nie posiada on tam os³ony, sprawia mu to prawdziwy ból}
{5030}{}{ i wzrok za spraw¹ osza³amiaj¹cego ciosu}
{5031}{}{. Utrata oka to dla niego zbyt wiele, zatem grunt usuwa mu siê spod nóg}
{5032}{}{; co smutne, jest on nadmiernie zaabsorbowany wtargniêciem powietrza do jego nagle otwartej mózgoczaszki, by zauwa¿yæ nadejœcie œmierci}
{5033}{}{. A³æ! To musia³o zaboleæ}
{5034}{}{. A on nawet nie za³o¿y³ ochraniacza}
{5035}{}{. Nie mia³ on os³ony w punkcie trafienia, wiêc natychmiast pada, jêcz¹c w agonii}
{5036}{}{. Cierpienie jest dla niego nie do zniesienia, tote¿ po chwili osuwa siê on w dó³ jak szmaciana lalka}
{5037}{}{. Mamrocze "Mamo", gdy oczy uciekaj¹ mu w ty³ czaszki}
{5100}{}{. To go naprawdê boli}
{5101}{}{. Serious pain is inflicted}
{5102}{}{, jako ¿e nie chroni jej pancerz}
{5103}{}{. To straszliwe uderzenie pozbawia j¹ przytomnoœci}
{5104}{}{. Ten cios j¹ powala}
{5105}{}{. Tak silny cios w g³owê od razu j¹ nokautuje}
{5106}{}{. Trafienie zmienia jej skroñ w krwaw¹ miazgê. Dobranoc, Anio³ku}
{5107}{}{ - zgon jest natychmiastowy}
{5108}{}{. Biedak, cierpi teraz na ostry przypadek ³okcia tenisisty}
{5109}{}{. Wyszarpniêcie koñczyny ze stawu barkowego nie wyjdzie mu na zdrowie}
{5110}{}{. Zostaje mu po tym wielki siniak}
{5111}{}{. Jego lewe ramiê zosta³o powa¿nie okaleczone}
{5112}{}{. Jej lewa ramiê ledwo trzyma siê barku}
{5113}{}{. To ramiê wygl¹da teraz jak zakrwawiony pieniek}
{5114}{}{. Okaleczenie jego prawego ramienia jest bardzo powa¿ne}
{5115}{}{. Wybuch zmieni³ jej prawe ramiê w hamburgera}
{5116}{}{ na skutek tego mocarnego trafienia}
{5117}{}{ pomimo pancerza}
{5118}{}{. Dziêki temu otrzymuje on dodatkow¹ dawkê obra¿eñ}
{5119}{}{ oraz traci grunt pod nogami}
{5120}{}{, i pozbawia j¹ tchu. Osuwa siê na ziemiê}
{5121}{}{. Niestety, jej organy wewnêtrzne s¹ teraz wystawione na wzrok ciekawskich}
{5122}{}{. W zamian otrzymuje solidn¹ dawkê bólu w dolnej koñczynie}
{5123}{}{. Od razu siê k³adzie, jak kiepska laska podczas randki w ciemno}
{5124}{}{. Œwie¿o okaleczona koñczyna nie jest w stanie utrzymaæ jego ciê¿aru i w rezultacie uczestniczka walki traci równowagê}
{5125}{}{, podczas gdy jej kolano zostaje zdruzgotane, a ona sama pod¹¿a najkrótsz¹ tras¹ w dó³}
{5126}{}{. Wrzeszczy przy tym z bólu emanuj¹cego ze strzaskanej koœci udowej}
{5127}{}{, co zwiêksza jego dawkê cierpienia}
{5128}{}{ oraz zdolnoœæ widzenia. Szok wykrzywia jej twarz w straszliwym grymasie}
{5129}{}{, a jako ¿e nie posiada on tam os³ony, sprawia mu to prawdziwy ból}
{5130}{}{. Zranienie skutkuje ciê¿k¹ œlepot¹ - jak gdyby istnia³a jej l¿ejsza odmiana}
{5131}{}{. Omdlewa po tym oœlepiaj¹cym ataku}
{5132}{}{; co smutne, ju¿ nie uda jej siê pomodliæ do swoich bogów przed spotkaniem z nimi}
{5133}{}{. Przyjmuje to jak prawdziwy mê¿czyzna. Innymi s³owy, boli j¹ jak diabli}
{5134}{}{, i pada jak œciêta k³oda}
{5135}{}{. Jej zdolnoœæ do prokreacji staje pod znakiem zapytania, podczas gdy ona sama wiotczeje i osuwa siê w dó³}
{5200}{}{. Doprowadza je to do p³aczu}
{5201}{}{. Natychmiast pada przez to nieprzytomne}
{5202}{}{. A³ajæ}
{5203}{}{. Ten cios nie jest markowany, nic wiêc dziwnego, ¿e dzieciak mdleje}
{5204}{}{. To uderzenie ciska maluchem jak wiatr kawa³kiem szmaty}
{5205}{}{. Jego lewa r¹czka ma teraz kuku}
{5206}{}{, a na dodatek siê przewraca}
{5207}{}{. Uderzenie ³amie tê ma³¹ koñczynê z g³oœnym trzaskiem. Teraz zaczynaj¹ siê prawdziwe ³zy}
{5208}{}{. Si³a uderzenia ³amie dzieciêc¹ r¹czkê równie ³atwo, jak patyczek od lizaka}
{5209}{}{. Jego drobne, prawe ramiê zaczyna puchn¹æ jak balon}
{5210}{}{, i zaczyna p³akaæ}
{5211}{}{ po trafieniu w czu³e miejsce}
{5212}{}{. Ten skierowany przeciw witalnym organom atak przewraca dzieciaka}
{5213}{}{. To uderzenie wywraca malucha jak zabawkê trafion¹ kamieniem}
{5214}{}{. Ta m³oda istotka ju¿ nigdy w pe³ni nie doœwiadczy ¿ycia}
{5215}{}{. Rezultatem jest g³êboka rana}
{5216}{}{. Brutalny atak wywraca dzieciaka i ³amie mu doln¹ koñczynê}
{5217}{}{. Wyrz¹dza to wielk¹ krzywdê temu maleñstwu}
{5218}{}{. Skrzywdzone dzieci¹tko spogl¹da w górê i wybucha p³aczem}
{5219}{}{, co je oœlepia}
{5220}{}{ po brutalnym ciosie w jego m³odziutki nosek}
{5221}{}{. Na jego czó³ku pojawia siê rana, z której obficie zaczyna wyp³ywaæ krew}
{5222}{}{, co rozsadza mu narz¹d wzroku tak, ¿e teraz przypomina on nadepniête winogrono. Maluch wygl¹da na bardzo tym zadziwionego}
{5223}{}{ i zdolnoœæ widzenia. Wywo³any tym szok sprawia, ¿e upada}
{5224}{}{, gdy cios dosiêga jego ma³ego mózgu}
{5225}{}{. Wygl¹da teraz na zdezorientowane i wstrz¹œniête}
{5226}{}{. Natychmiast powala to ten m³odziutki cel}
{5300}{}{. Sprawia to ból temu potê¿nemu œwiadectwu twórczej mocy promieniowania}
{5301}{}{ po trafieniu w witalny organ}
{5302}{}{. Uderzenie w czu³e miejsce œcina tego olbrzyma z nóg}
{5303}{}{. Ten gigantyczny produkt radiacji przez chwilê rozgl¹da siê wokó³ z niedowierzaniem, a potem traci grunt pod nogami}
{5304}{}{. Jego czaszka eksploduje jak olbrzymi, krwisty arbuz}
{5305}{}{; koñczy siê to dla tego potê¿nego dziecka ery atomu powa¿nym okaleczeniem}
{5306}{}{; sk³ania to tego giganta do spêdzenia chwili na klniêciu na czym œwiat stoi}
{5307}{}{; atak trafia w nerw i zmusza olbrzyma do z³apania siê za przedramiê z grymasem cierpienia na twarzy}
{5308}{}{. Cios gruchocze mu ³okieæ i chyba nie jest szczególnie przyjemnym doznaniem}
{5309}{}{. Na jego umiêœnionym ramieniu widaæ otwarte z³amanie, z rany strumieniem leje siê mutancia krew}
{5310}{}{; w rezultacie ten olbrzym przez chwilê tañczy w miejscu, a potem pada jak powalone drzewo}
{5311}{}{, gdy strug¹ wyp³ywaj¹ z niego litry flaków}
{5312}{}{; po krótkim locie gigant przybli¿a siê do ³ona Matki-Ziemi}
{5313}{}{. Potyka siê on i upada, jako ¿e jego koñczynie trudno jest teraz utrzymaæ jego ciê¿ar}
{5314}{}{ po trafieniu w kluczowy punkt. Z³amana koñczyna natychmiast ugina siê pod nim}
{5315}{}{. Ból promieniuj¹cy ze z³amanej piszczeli przyt³acza tego mocarnego olbrzyma}
{5316}{}{ po niemal oœlepiaj¹cym go uderzeniu}
{5317}{}{. Zranienie pozbawia go wzroku i doprowadza do furii}
{5318}{}{. Trafienie pozbawia go równowagi i prawie oœlepia}
{5319}{}{. Oœlepiony, nie przygotowany na kolejny atak, potyka siê do ty³u}
{5320}{}{. Trafienie pozbawia wzroku ten teraz nieprzytomny skutek uboczny wojny staro¿ytnych}
{5321}{}{. Oczy jarz¹ mu siê przez chwilê, lecz ich œwiat³o zaraz gaœnie - na zawsze}
{5400}{}{. Zosta³ zaskoczony, wiêc nie uda³o mu siê obroniæ przed tym atakiem}
{5401}{}{. Ten cios go pogrzeba³}
{5402}{}{. D³oñ oszo³omionego stwora ulega rozszarpaniu}
{5403}{}{. Atak nie zosta³ powstrzymany przez pancerz, tote¿ dosiêgn¹³ wa¿nego stawu}
{5404}{}{. Atak nie zosta³ powstrzymany przez pancerz i urwa³ mu ramiê}
{5405}{}{. Poruszy³ siê on w niew³aœciw¹ stronê w niew³aœciwym momencie i straci³ oko}
{5406}{}{. Stwór nie za³o¿y³ na to miejsce os³ony}
{5407}{}{, a jako ¿e nie ma he³mu, zostaje oœlepiony}
{5408}{}{, przez co w swych ostatnich chwilach wygl¹da na oszo³omionego}
{5500}{}{, co przewraca to wielkie bydlê na ziemiê}
{5501}{}{. Skuteczny atak pozbawia œwiadomoœci oba mózgi i powala to olbrzymie zwierzê}
{5502}{}{. Ta zmutowana krowa wydaje z siebie donoœny ryk wyra¿aj¹cy zaskoczenie}
{5503}{}{; si³a uderzenia ³amie jej jedn¹ z koñczyn}
{5504}{}{. Powa¿nie okalecza tê zmutowan¹ krowê}
{5505}{}{; skutkuje to pojawieniem siê g³êbokiej rany na grubej skórze tego gigantycznego bydlêcia}
{5506}{}{; penetracja siêga obu serc tej zmutowanej krowy}
{5507}{}{. Ten pojedynczy cios niszczy mu obie pary narz¹dów wzroku}
{5508}{}{; atak oœlepia obie g³owy i obezw³adnia tê zmutowan¹ krowê}
{5509}{}{; bydlê zostaje ca³kowicie oœlepione i zamroczone}
{5510}{}{; to wielkie, zmutowane bydle przez chwilê ma trudnoœci z utrzymaniem równowagi}
{5511}{}{. Zwierzê dr¿y z wœciek³oœci}
{5512}{}{. Muæka parska z bólu oboma pyskami}
{5513}{}{. Zwierzak jest rozjuszony tym wymiê-rnie destruktywnym atakiem}
{5600}{}{, co posy³a tego stawonoga na grzbiet}
{5601}{}{, co od³¹cza mu ³eb od tu³owia}
{5602}{}{; koñczy siê to dla niego powa¿n¹ ran¹ na jadowitym zaodw³oku}
{5603}{}{. Rozleg³e obra¿enia jego potê¿nych szczypiec s¹ bardzo bolesne}
{5604}{}{. Ten cios trafi³ w szczelinê w jego solidnej skorupie}
{5605}{}{. Atak przebi³ siê przez tward¹ skorupê bez spowolnienia}
{5606}{}{. Uderzenie przeniknê³o przez jego naturalny pancerz i wywróci³o tego przeroœniêtego pajêczaka do góry nogami}
{5607}{}{. Ten stawonóg-mutant nie potrafi sobie radziæ z nowymi doznaniami, takimi jak utrata narz¹dów wewnêtrznych}
{5608}{}{, co posy³a go w powietrze i zarazem okalecza niektóre z jego odnó¿y}
{5609}{}{. Ten atak przenika przez nieopancerzony staw i w rezultacie g³adko odcina koñczynê}
{5610}{}{. Trafienie ciê¿ko rani i okalecza to zmutowane stworzenie}
{5611}{}{, penetracja dociera niemal do samego mózgu. To siê nazywa topienie robaka... w jego w³asnej jusze}
{5612}{}{. Impet uderzenia nie siêga mózgu, ale i tak oœlepia stworzenie}
{5613}{}{. Ten atak jest iœcie szatañski, stanowczo zbyt wymyœlny jak na to niewyrafinowane stworzenie}
{5614}{}{. Mo¿esz przysi¹c, ¿e gdyby by³ cz³owiekiem, by³by teraz naprawdê wkurwiony}
{5615}{}{. Zranienie pozbawia to biedne stworzonko zmys³ów}
{5616}{}{; si³a uderzenia wyrzuca jego mózg na ziemiê}
{5700}{}{. Czaszka gryzonia wydaje kilka niezdrowych odg³osów}
{5701}{}{, co mia¿d¿y czaszkê tego gryzonia równie ³atwo, jak papierowy kubek}
{5702}{}{; jego lewa koñczyna jest teraz trochê p³aska}
{5703}{}{. Lewe odnó¿e tego stworzenia zostaje oderwane}
{5704}{}{. Efektem s¹ ciê¿kie obra¿enia prawego odnó¿a}
{5705}{}{; impet uderzenia urywa mu prawe odnó¿e}
{5706}{}{. Gryzoñ zosta³ powa¿nie zraniony w trakcie tego ataku}
{5707}{}{. Trafienie powa¿nie rani gryzonia i odrzuca go do ty³u}
{5708}{}{, co rozbryzguje go po pod³o¿u}
{5709}{}{. Jego prawa ³apa ulega okaleczeniu}
{5710}{}{, co skutkuje pojawieniem siê wielkiej dziury w jego lewym odnó¿u}
{5711}{}{, dziêki naruszeniu czu³ego punktu odnosi on nieco dodatkowych obra¿eñ}
{5712}{}{; stworzenie wezwa³ Wielki Szczuro³ap w Niebiosach}
{5800}{}{, i natychmiast siê przewraca}
{5801}{}{; stworzenie upada, najwyraŸniej bez ¿ycia}
{5802}{}{, co ma powa¿ne konsekwencje dla jego dalszej egzystencji}
{5803}{}{; trafienie obezw³adnia to plugawe stworzenie}
{5804}{}{, atak trafia tam w czu³e miejsce i pozbawia stwora przytomnoœci}
{5805}{}{. Ten cios sprawia, ¿e stwór dziko podryguje spowity szkar³atn¹ mgie³k¹}
{5806}{}{; cios wyzwala jak¹œ gwa³town¹ reakcjê we wnêtrzu tego stworzenia}
{5807}{}{. Stwór nagle wybucha p³omieniem}
{5808}{}{, potem doznaje gwa³townego skurczu i zaczyna dr¿eæ jak galareta}
{5809}{}{, ten cios dosiêgn¹³ jego czu³ego punktu}
{5810}{}{. Stwór jest w sposób oczywisty zdenerwowany}
{5900}{}{; odrzucony jak z³y na³óg, przewraca siê i mdleje}
{5901}{}{, gdy cios trafia w krytyczny punkt}
{5902}{}{, co skutkuje rozleg³¹ niewydolnoœci¹ uk³adu nerwowego}
{5903}{}{. Twój gwa³towny atak pozbawia go œwiadomoœci}
{5904}{}{; koñczy siê to okaleczeniem trafionej koñczyny}
{5905}{}{; trafienie w krytyczne miejsce okalecza mu ramiê}
{5906}{}{; si³a uderzenia okalecza koñczynê stworzenia i je przewraca}
{5907}{}{. Stwór traci przytomnoœæ z bólu, gdy potyka siê na okaleczonej koñczynie}
{5908}{}{; trafienie pozbawia go wzroku}
{5909}{}{, co go zaskakuje. Oœlepiony stwór przez chwilê ma trudnoœci z równowag¹}
{5910}{}{, co go zaskakuje. Natychmiast pada jak k³oda}
{5911}{}{, co go zaskakuje. Upada tworz¹c stertê odra¿aj¹cej mazi}
{5912}{}{. Ten atak nie by³ maksymalnie skuteczny}
{6000}{}{, co powoduje uszkodzenia strukturalne}
{6001}{}{; sypi¹ siê iskry i robot momentalnie wyrywa siê spod kontroli}
{6002}{}{; uszkodzenie wa¿nego komponentu uwalnia robota spod kontroli}
{6003}{}{; trafienie w wa¿ny komponent powoduje rozleg³¹ awariê}
{6004}{}{. Robot stara siê to skompensowaæ}
{6005}{}{. Robot wysila siê, by to skompensowaæ}
{6006}{}{; trafienie którejœ kluczowej czêœci wywo³uje ciê¿kie uszkodzenia}
{6007}{}{, co powoduje ciê¿kie uszkodzenia strukturalne}
{6008}{}{; trafienie w wa¿ny komponent skutkuje powa¿nymi uszkodzeniami}
{6009}{}{. Robot drga od intensywnoœci tego ataku}
{6010}{}{, co skutkuje jego faktycznym demonta¿em}
{6011}{}{. Robot usi³uje to skompensowaæ, lecz nie odnosi powodzenia i upada na pod³o¿e}
{6012}{}{. Robot nadwerê¿a siê w obliczu przemocy i pada na pod³o¿e}
{6013}{}{, soczewki jego czujników optycznych ulegaj¹ st³uczeniu}
{6100}{}{, co powala go na pod³o¿e}
{6101}{}{ po uderzeniu prosto w pysk}
{6102}{}{. Psina siê przewraca, ale wci¹¿ oddycha}
{6103}{}{; zwierzê wykas³uje strugê krwi}
{6104}{}{; trafienie okalecza mu koñczynê}
{6105}{}{, co okalecza mu odnó¿e. Zwierzak stara siê ustaæ, lecz siê mu to nie udaje}
{6106}{}{. Oœlepione zwierzê wyje z bólu}
{6107}{}{; trafienie sterylizuje tego biednego zwierzaka}
{6200}{}{; trafienie powala tego zmutowanego owada}
{6201}{}{; insekt-mutant ciê¿ko upada}
{6202}{}{. Owad rozwa¿a, czy pozostaæ przy ¿yciu}
{6203}{}{, co trwale okalecza koñczynê}
{6204}{}{; sk³ania to robala do polizania swoich ran. Odnó¿e trzyma wykrzywione pod dziwacznym k¹tem}
{6205}{}{; uderzenie omija chitynow¹ zbrojê}
{6206}{}{. Gigantyczny insekt krzyczy i podryguje w skrajnie nieludzki sposób}
{6207}{}{, i natychmiast siê przewraca. Jej koñczyna jest teraz wygiêta pod dziwacznym k¹tem}
{6208}{}{; po tym ataku nie pozostan¹ jej ju¿ nawet tylko marzenia o lataniu}
{6209}{}{; uderzenie omija chitynow¹ zbrojê i ciska tym przeroœniêtym owadem}
{6210}{}{; ten celny cios oœlepia insekta}
{6300}{}{. Nawet taka bestia wydaje siê byæ zaskoczona tym osza³amiaj¹cym atakiem}
{6301}{}{. Uderzenie ominê³o wielkie szpony, by trafiæ w samego potwora, który teraz otrz¹sa siê i warczy}
{6302}{}{. Skutkiem tego s¹ rozleg³e obra¿enia narz¹du wzroku potwora}
{6400}{}{. Zas³ona nic nie pomog³a}
{6401}{}{, i gubi sporo liœci}
{6402}{}{, i traci kilka ga³êzi}
{6403}{}{. Musia³o to nieŸle zaboleæ}
{6404}{}{, i wyrzuca w powietrze chmurê zarodników}
{6405}{}{, i niemal siê przewraca}
{6406}{}{, i ³amie kilka grubych ga³êzi}
{6500}{}{. Czeka ciê jutro ból g³owy, o ile po¿yjesz tak d³ugo}
{6501}{}{. Pancerz nie zapewnia ci ochrony przed tym dobrze wymierzonym ciosem}
{6502}{}{. Przez moment odczuwasz ból, a potem ogarnia ciê ciemnoœæ..}
{6503}{}{. Tego ciosu nie powstrzymuje twój pancerz, wiêc si³a uderzenia zbija ciê z nóg}
{6504}{}{. Szok zaciemnia twoje spojrzenie. Po chwili zdajesz sobie sprawê, ¿e wzrok ci nie powraca}
{6505}{}{. Masz ³adny widok na w³asne cia³o, gdy twoja g³owa ¿egluje w powietrzu}
{6506}{}{. O dziwo, zranienie nie boli ciê bardziej ni¿ zwykle}
{6507}{}{; trafienie pozbawia ciê na moment przytomnoœci}
{6508}{}{. Poczuj ten ból}
{6509}{}{. Ten atak czyni twoje ramiê bezu¿ytecznym}
{6510}{}{. Cios nie zwa¿a, czy nosisz pancerz, i ³amie koœci w twoim ramieniu, jakby by³y z próchna}
{6511}{}{. Ramiê zwisa ci teraz luŸno u boku, gdy¿ nie ochroni³ go pancerz}
{6512}{}{. Siniak bêdzie siê nieŸle prezentowa³, a blizny byæ mo¿e stan¹ siê dobrym tematem pogaduszek na imprezach}
{6513}{}{. To trafienie mia¿d¿y twoje narz¹dy wewnêtrzne. Wszystko, co jesteœ w stanie teraz uczyniæ, to bulgotaæ w³asn¹ krwi¹}
{6514}{}{; wywraca ciê to do góry nogami}
{6515}{}{; trafienie posy³a ciê w powietrze i ³amie ci doln¹ koñczynê}
{6516}{}{. Si³a uderzenia przenika przez twój pancerz, przewraca ciê i powa¿nie rani ci kolano}
{6517}{}{. Ból ze z³amanej koñczyny pozbawia ciê przytomnoœci}
{6518}{}{. Bolesny cios sprawia, ¿e odskakujesz do ty³u, ale nie czyni ci wiele wiêcej}
{6519}{}{. Nieszczêœliwie dla ciebie, wywo³uje to tak¿e natychmiastow¹ utratê wzroku}
{6520}{}{. Chwilê zabiera ci otarcie krwi z twoich powiek}
{6521}{}{ bez wzglêdu na twój pancerz. Stoisz w oszo³omieniu, zaczynaj¹c zdawaæ sobie sprawê, ¿e ju¿ nie widzisz}
{6522}{}{. Pod czaszk¹ narasta ci dziwne uczucie. Zdajesz sobie sprawê, ¿e to nieuchronne obumieranie tkanek mózgu}
{6523}{}{. Zmusza ciê to, by siê skuliæ}
{6524}{}{. Chwytasz siê za podbrzusze i upadasz z bólu na pod³ogê}
{6525}{}{. Spowodowany tym ból wystarcza, by pozbawiæ ciê œwiadomoœci. A³æ}
{6526}{}{. W ca³ym wszechœwiecie nie ma tylu s³ów, aby opisaæ ból, jaki w³aœnie odczuwasz}
{6700}{}{; próba uniku na nic siê zda³a}
{6701}{}{, i gubi spory kawa³ ³uskowatej skóry}
{6702}{}{, i ³amie kilka palców}
{6703}{}{; jaszczur ma powa¿ne k³opoty z oddychaniem}
{6704}{}{; jaszczur krztusi siê w³asn¹ krwi¹}
{6705}{}{, i niemal siê przewraca}
{6706}{}{, i ³amie kilka koñczyn}
{6800}{}{, mimo próby zas³ony}
{6801}{}{, i gubi spory kawa³ œluzowatego cia³a}
{6802}{}{, i traci parê szczêkoczu³ek}
{6803}{}{, i rani sobie tchawki}
{6804}{}{, i wytrz¹sa z siebie jakieœ obrzydliwoœci}
{6805}{}{, i niemal siê przewraca}
{6806}{}{, i uszkadza kilka macek}
{6900}{}{, mimo próby uniku}
{6901}{}{, i gubi kilka czu³ek}
{6902}{}{, i ³amie parê czu³ek}
{6903}{}{, i odnosi powa¿ny uszczerbek na zdrowiu}
{6904}{}{, i dostaje konwulsji}
{6905}{}{, i niemal siê przewraca}
{6906}{}{. Czêœæ egzoszkieletu jest uszkodzona}
{7000}{}{, mimo próby uniku}
{7001}{}{, i gubi kilka czu³ek}
{7002}{}{, i ³amie parê czu³ek}
{7003}{}{, i odnosi powa¿ny uszczerbek na zdrowiu}
{7004}{}{, i dostaje konwulsji}
{7005}{}{, i niemal siê przewraca}
{7006}{}{. Czêœæ egzoszkieletu jest uszkodzona}
{7100}{}{, mimo noszonego pancerza.}
{7101}{}{, sprowadzaj¹c Ochroniarza na kolana}
{7102}{}{; mechanizm ramienia jest chyba uszkodzony}
{7103}{}{; mechanizm rotacyjny nogi jest chyba uszkodzony}
{7104}{}{; bioniczne oko jest chyba doszczêtnie zmia¿d¿one}
{7105}{}{. Przerwa na chwilê, by otrz¹sn¹æ siê po ataku}
{7106}{}{; napierœnik jest doszczêtnie zniszczony}
