{100}{}{WCZYTAJ}
{101}{}{GRA DO SZYBKIEGO ODCZYTU}
{102}{}{ZAPISZ GR }
{103}{}{GRA DO SZYBKIEGO ZAPISU}
{104}{}{GOTOWE}
{105}{}{Anuluj}
{106}{}{B≥πd w trakcie odczytu listy gier!}
{107}{}{Katalog }
{108}{}{nie istnieje lub jest wadliwy.}
{109}{}{ZAPISZ GR }
{110}{}{WCZYTAJ}
{111}{}{- PLIK JEST PUSTY -}
{112}{}{- PLIK JEST WADLIWY -}
{113}{}{- STARA WERSJA -}
{114}{}{Pusty plik.}
{115}{}{B≥πd!}
{116}{}{Stara wersja.}
{117}{}{STY}
{118}{}{LUT}
{119}{}{MAR}
{120}{}{KWI}
{121}{}{MAJ}
{122}{}{CZE}
{123}{}{LIP}
{124}{}{SIE}
{125}{}{WRZ}
{126}{}{PAè}
{127}{}{LIS}
{128}{}{GRU}
{129}{}{Poziom doúwiadczenia}
{130}{}{OPIS}
{131}{}{Plik juø istnieje, czy chcesz go zastπpiÊ?}
{132}{}{B≥πd w trakcie zapisu!}
{133}{}{Nie uda≥o siÍ zapisaÊ gry.}
{134}{}{B≥πd w trakcie odczytu!}
{135}{}{Nie uda≥o siÍ wczytaÊ gry.}
{136}{}{Plik pochodzi z niezaktualizowanej wersji gry.}
{137}{}{Mapa}
{140}{}{Gra zapisana.}
{141}{}{Gra wczytana.}
{200}{}{Opcja niedostÍpna}
{201}{}{w wersji demo.}
