{0}{}{ZAPISZ GR }
{1}{}{WCZYTAJ}
{2}{}{OPCJE GRY}
{3}{}{WYJåCIE}
{4}{}{GOTOWE}
{100}{}{OPCJE GRY}
{101}{}{TRUDNOå∆ GRY}
{102}{}{TRUDNOå∆ WALKI}
{103}{}{BRUTALNOå∆}
{104}{}{OBRYS CEL”W}
{105}{}{OBRAZ WALKI}
{106}{}{KOM. BOJOWE}
{107}{}{OBELGI BOJOWE}
{108}{}{FILTR J ZYKOWY}
{109}{}{BIEG}
{110}{}{NAPISY FILMOWE}
{111}{}{OBRYS PRZEDM.}
{112}{}{SZYBKOå∆ WALKI}
{113}{}{OP”èNIENIE TEKSTU}
{114}{}{G£OåNOå∆ OG”LNA}
{115}{}{MUZYKA/FILMY}
{116}{}{EFEKTY DèWI KOWE}
{117}{}{MOWA}
{118}{}{JASNOå∆ EKRANU}
{119}{}{CZU£Oå∆ MYSZY}
{120}{}{STAND.}
{121}{}{Anuluj}
{122}{}{Dotyczy prÍdkoúci gracza}
{123}{}{Mowa Pip-Boya}
{201}{}{W≥.}
{202}{}{Wy≥.}
{203}{}{Min.}
{204}{}{Norm.}
{205}{}{Maks.}
{206}{}{Min.}
{207}{}{Norm.}
{208}{}{Maks.}
{209}{}{Norm.}
{210}{}{Maks.}
{211}{}{D≥ugie}
{212}{}{ZwiÍz≥e}
{213}{}{Podczas celowania}
{214}{}{brak}
{215}{}{Min.}
{216}{}{Ocean krwi}
{217}{}{Wolno}
{218}{}{Szybko}
{219}{}{Zawsze}
{220}{}{MnÛstwo}
{221}{}{Cicho}
{222}{}{G≥oúno}
{223}{}{Jasno}
{224}{}{Szeroko}
{300}{}{GOTOWE}
{301}{}{PAUZA}
{1000}{}{Opcje gry nie sπ dostÍpne}
{1001}{}{w wersji demo.}
