{100}{}{rakieta}
{200}{}{Kula plazmy}
{300}{}{Eksplozja}
{400}{}{krew}
{500}{}{Pole nieprzechodnie}
{501}{}{}
{600}{}{nó¿}
{700}{}{w³ócznia}
{800}{}{Eksplozja EMP}
{900}{}{Eksplozja laserowa}
{1000}{}{Eksplozja plazmy}
{1100}{}{Eksplozja}
{1200}{}{Bloker przewijania}
{1300}{}{Impuls elektryczny}
{1400}{}{Eksplozja}
{1500}{}{Eksplozja}
{1600}{}{Obszar Wyjœciowy}
{1700}{}{Obszar Wyjœciowy}
{1800}{}{Obszar Wyjœciowy}
{1900}{}{Obszar Wyjœciowy}
{2000}{}{Obszar Wyjœciowy}
{2100}{}{Obszar Wyjœciowy}
{2200}{}{Obszar Wyjœciowy}
{2300}{}{Obszar Wyjœciowy}
{2400}{}{flara}

{2500}{}{granat}
{2600}{}{ska³a}
{2700}{}{Eksplozja}
{2800}{}{Eksplozja}
{2900}{}{Eksplozja}
{3000}{}{koktail Mo³otowa}
{3100}{}{Obszar Wyjœciowy}
{3200}{}{Obszar Wyjœciowy}
{3300}{}{Obszar Wyjœciowy}
{3400}{}{Obszar Wyjœciowy}
{3500}{}{Obszar Wyjœciowy}
{3600}{}{Obszar Wyjœciowy}
{3700}{}{Obszar Wyjœciowy}
{3800}{}{Obszar Wyjœciowy}
{3900}{}{Obszar Wyjœciowy}
{4000}{}{Obszar Wyjœciowy}
{4100}{}{Obszar Wyjœciowy}
{4200}{}{Obszar Wyjœciowy}
{4300}{}{Obszar Wyjœciowy}
{4400}{}{Obszar Wyjœciowy}
{4500}{}{Obszar Wyjœciowy}
{4600}{}{Obszar Wyjœciowy}
{4700}{}{rakieta naprowadzana}
{4701}{}{}
{4800}{}{Bum!}
{4801}{}{}
{4900}{}{Kolec}
{4901}{}{}
{5000}{}{Podwójna kula plazmowa}
