{100}{}{Vidíš silnou jeptišku.}
{101}{}{Vidíš Elaine.}
{102}{}{Poøád ji vidíš.}

{200}{}{Zdravím!}
{201}{}{Ahoj, jak se jmenuješ?}
{202}{}{Co mi mùžeš øíct o Opatství?}
{203}{}{Nashle.}

{300}{}{Jestli se chceš o našem øádu dozvìdìt víc, promluv si s Opatem. Najdeš ho ve tøetím patøe.}
{301}{}{Rozumím. Chci se ještì zeptat...}

{400}{}{Jistì, co chceš vìdìt?}
{401}{}{Jak se jmenuješ?}
{402}{}{Vlastnì nic, nashle.}
{403}{}{Co mi mùžeš øíct o Opatství?}

{500}{}{Jmenuji se Elaine.}
{501}{}{Rozumím. Ještì se chci zeptat...}

{600}{}{Poèkej! Než odejdeš, mùžeš mi prokázat malou laskavost? Potøebuji donést tuto souèástku Maxovi do tiskárny ve sklepì, ale jak vidíš, moje levé koleno není co bývalo a chození po schodech je velmi bolestivé. Nevadilo by ti zanést mu tu souèástku?}
{601}{}{Jasnì.}
{602}{}{Promiò, na tohle nemám èas. Sbohem.}
{603}{}{Vypadám snad jako donášková služba? Udìlej si to sama, ty tlustá líná èubko. Nashle.}  #new in RP 1.3

{604}{}{Díky! Tady to je. Tiskárna je ve sklepì. Použij schodištì, které je v kapli za bratrem Matthewem.}
{605}{}{Žádný problém. (Bereš si souèástku.) Hned to Maxovi donesu.}

#dumb dialgoue
{700}{}{Já }
{701}{}{. Kdo ty?}

{710}{}{Hehe. To hezké jméno.}
{711}{}{Nashle!}

{720}{}{Ty jsi ale milý kluèík, že? Udìlal bys mi VELKOU laskavost a byl dnes mým zvláštním pomocníkem?}
{721}{}{Ty jsi ale milá dìvenka, že? Udìlala bys mi VELKOU laskavost a byla dnes mým zvláštním pomocníkem?}
{722}{}{Já zvláštní. Já pomoct.}
{723}{}{Já nechtít pomoct.}

{730}{}{Vážnì? Skvìle! Prosím, dej tuhle souèástku Maxovi v tiskárnì. Najdeš ho ve SKLEPÌ. Ano?}
{731}{}{Já tì nezklamat!}

{740}{}{Pokraèuj, vedeš si dobøe.}
