{100}{}{Vidíš mnicha ve støedních letech.}
{101}{}{Vidíš bratra Mathewa.} 
{102}{}{Stojí na pódiu a káe obyvatelùm Opatství.}

{200}{}{Dobøí lidé z Opatství. Slyšte na chvíli, nebo mám tolik co øíci.}

#new speech for RP 1.3
{201}{}{Ostatky svaté vìkù dávnıch jsme zde shromádili.}
{202}{}{Seehnuti Ohnivou záplavou, uvrhnuti jsme v temnotu byli.}
{203}{}{Pro zachování moudrosti dob minulıch, Memorabilia budeme tvoøiti.}
{204}{}{By plamen ji dávno vychladl, musíme peèovati o nì a chrániti.} 
{205}{}{Moudra tato zneuita by mohla bıti, plamen zkázy znovu vzplane.}
{206}{}{Nikdo tedy uèiti se nebude, z obavy, e další Ohnivá záplava se stane.}
{207}{}{Pøijde však den, kdy se lidstvo povznese nad svou touhou po zkáze.}
{208}{}{A Memorabilia budou tu èekati na znovuvzkøíšení své zase.}
{209}{}{Dohlííme tedy na náš úkol posvátnı, jinak moudrost všechnu bychom mohli ztratiti.}
{210}{}{Musíme ji zachovati a dobøe chrániti, nikdy však uíti.}
{211}{}{A nyní jdìte, pøátelé, a duch váš je povznesen.}
{212}{}{Neb stráci vìdìní, kadı z nás byl obdaøen.}
{213}{}{Nyní se prosím na chvíli zamyslete nad mımi slovy.}

{224}{}{Nyní se prosím na chvíli zamyslete nad mımi slovy.}

{300}{}{Vítám tì, pøíteli. Ještì nikdy jsem tì tu pøedtím nevidìl. Jsem bratr Mathew a pomáhám šíøit slovo o dùleitosti zachování moudra a vìdìní starších.}
{301}{}{Tìší mì, Matte. Jmenuju se }
{302}{}{ a mım posláním je najít svatı GECK.}
{303}{}{Promiò, u musím jít.}

{400}{}{GECK, jo? Vzpomínám si, e jsem na nìj narazil pøi jednom pøepisování, take o nìm musí bıt zmínka v naší databázi, ale obávám se, e pøístup k našim poèítaèùm je omezen. Nicménì, pokud si promluvíš s Opatem, je moné, e ti udìlí pøístup. Za pokus nic nedáš. Jo a klidnì si projdi sbírku našich pøedváleènıch relikvií. Poádal bych tì, abys nic nepoškodil, ale obávám se, e vše ji bylo nenapravitelnì poškozeno.}
{401}{}{Myslím, e se ho zeptám, ale mám ještì nìjaké otázky.}
{402}{}{Dìkuju. Pùjdu se ho hned zeptat.}

{500}{}{Jsem ti k slubám. Co chceš vìdìt?}
{501}{}{Co mi mùeš øíct o tomto místì?}
{502}{}{Jsi pøi svém kázání velmi poetickı. Máš k tomu nìjakı dùvod?}
{503}{}{Ale nic. Mìj se.}

{600}{}{Opatství je domovem pro kadého, kdo se chová slušnì. Jsme nezávislá komunita a návštìvníky, jako jsi ty, tu míváme jen velmi zøídka. Vìtšina z tìch, které tady vidíš, jsou potomky pùvodních zakladatelù, kteøí se usadili v tomto starém klášteøe krátce po Ohnivé záplavì.}
{601}{}{Pokraèuj.}
{602}{}{Ticho a mírumilovnost tohoto místa ji v prùbìhu let pøilákalo mnohé cestovatele touící uniknout z temného chaosu pustiny. Ale samozøejmì pravá hodnota tohoto místa je ukryta v rozsáhlé knihovnì, která je zaplnìna starımi svazky obsahujícími neobvyklou moudrost ztraceného vìku. Postupem èasu jsme se pasovali do role strácù a ochráncù tohoto vìdìní.}
{603}{}{Velmi zajímavé. Mám další otázku.}
{604}{}{Zajímavé, ale u musím jít.}

{700}{}{(Pousmìje se nad tvojí otázkou.) Ne, nemám k tomu ádnı konkrétní dùvod. Jen jsem za svùj ivot pøeèetl mnoho poezie a baví mì ji vyuívat pøi svıch kázáních. Pomáhá to zanechat v posluchaèích hlubší dojem.}
{701}{}{Dobøe. Mám další otázku.}

{800}{}{Rád tì znovu vidím }
{801}{}{. Co pro tebe mohu udìlat?}
{802}{}{Mám nìjaké otázky.}
{803}{}{Nic. Zatím.}
