{100}{}{Vidíš farmáře.}
{101}{}{Vidíš zdravě vypadajícího rolníka.}
{102}{}{Vidíš osobu.}
{103}{}{Poslední dobou jsi trochu chlastal, co?}
{104}{}{Dej na chvíli ruce pryč od alkoholu.}
{105}{}{Vidím, že jsi měl Hankův "speciální" mix.}
{106}{}{Vítej, hrdino!}
{107}{}{Opravdu jsi to těm enklávským bastardům ukázal!}
{108}{}{Jsi opravdový hrdina!}
{109}{}{Slyšel jsem, že jsi zničil Enklávu. Skvělá práce!}
{110}{}{Ahoj.}
{111}{}{Doufám, že začne brzy pršet, jinak moje úroda nepřežije.}
{112}{}{Nemáme tu moc návštěvníků.}
{113}{}{Vítej!}
{114}{}{Jo, já vím. Je tu pěkná nuda, ale alespoň jsme tu v bezpečí od nájezdníků a tak...}
{115}{}{Ahoj, divochu.}
{116}{}{Dneska je opravdu horko!}
{117}{}{Je tu úrodná půda...}
{118}{}{Hezký den.}
{119}{}{Vítej v Opatství, poutníku!}
{120}{}{Náš klášter je působivý, že ano?}
{200}{}{Dej ze mě ty pracky pryč!}
