{100}{}{Vidíš Lucase.}
{101}{}{Lucas je nejsilnìjší váleèník tvého kmene.}
{102}{}{Tak tady jsi, Vyvolený. Hmmm...jak jsi na tom se svým posláním?}
{103}{}{Jde to skvìle.}
{104}{}{Ne moc dobøe.}
{105}{}{He?!}
{106}{}{Musím se k tomu co nejdøív vrátit.}
{107}{}{Možná, že by se ti hodilo nìkolik rad od zkušeného bojovníka.}
{108}{}{Urèitì. S èím mi mùžeš pomoct?}
{109}{}{Ani ne. Daøí se mi docela dobøe.}
{110}{}{Dobrá odpovìï, blbeèku. A teï sklapni, zrovna trénuju.}
{111}{}{Dobøe.}
{112}{}{Umím dobøe bojovat beze zbranì. Chceš, abych tì nìco nauèil?}
{113}{}{Co mì mùžeš nauèit?}
{114}{}{Pøeju ti vítr v zádech, Vyvolený.}
{115}{}{Sbohem.}
{116}{}{Hmmm... zùstaò tu se mnou jeden den a nauèím tì, jak rozdávat vìtší rány.}
{117}{}{Dobøe. Pojïme na to.}
{118}{}{Promiò, zrovna teï nemám èas.}
{119}{}{Umíš už všechno, co vím, Vyvolený. Hodnì štìstí pøi tvém poslání.}
{120}{}{Aha, dobøe.}
{121}{}{Hm. Vyvolený, nejsi dost obratný. Nemùžu tì nic nauèit.}
{122}{}{Aha, dobøe.}
{123}{}{Vyvolený, chybí ti rychlost pohybu. Mùj trénink ti nepomùže.}
{124}{}{Aha, dobøe.}
{125}{}{Musíš se zlepšit v boji, než tì budu moct zaèít trénovat.}
{126}{}{Aha, dobøe.}
{127}{}{Mùžu tì nauèit jeden velmi mocný kop. Potrvá nám to jeden celý den.}
{128}{}{Dobøe.}
{129}{}{Mùžu tì nauèit dost na to, aby se ti lépe zápasilo. Potrvá nám to jeden celý den.}
{130}{}{Dobøe.}
{131}{}{Šlo ti to dobøe, Vyvolený. Pøeju ti vítr v zádech.}
{132}{}{Díky za pomoc.}
{133}{}{Nauèil jsem tì už všechno, co vím, Vyvolený. Hodnì štìstí pøi svém poslání.}
