{100}{}{Vidíš èlena tvého kmene.}
{101}{}{Vidíš èlenku tvého kmene.}
{150}{}{Pøed tebou stojí jeden z váleèníkù tvé vesnice. Na sobì má kalhoty ušité ze zvíøecích kùí.}
{151}{}{[MLUVIT]}
{152}{}{Zdravím tì, Vyvolenı. Mùu ti nìjak pomoct s tvım úkolem?}
{153}{}{Jen se tak naposled procházím vesnicí, ne odsud budu muset odejít.}
{154}{}{Co mi mùeš øíct o kupcích, se kterımi naše vesnice obchoduje?}
{155}{}{Kde seenu víc léèivého prášku?}
{156}{}{Nech ti bohové dají sílu pøinést nám ráj døív, ne bude pozdì.}
{157}{}{Mám otázku.}
{158}{}{Sbohem, pøíteli.}
{159}{}{Haha, ty mì zkoušíš, viï? Jdi navštívit Hakuninovu chıši na severním konci vesnice. To on vyrábí všechny naše léky.}
{160}{}{Díky. Sbohem.}
{161}{}{No, co já vím, tak naposled mluvili s Mynocem. Promluv si s ním. Je strácem Velkého mostu.}
{162}{}{Díky. Sbohem.}
{163}{}{Mùeš mi øíct, jak se dostanu k Velkému mostu?}
{164}{}{Ještì se chci na nìco zeptat.}
{165}{}{Jsi v poøádku, Vyvolenı? Velkı most je na jiním konci vesnice. Ale to pøece víš. Vdy kadı z nás tamtudy prošel u nejménì tisíckrát.}
{166}{}{Díky. Sbohem.}
{167}{}{Ještì se chci na nìco zeptat.}
{168}{}{Samozøejmì. Co tì zajímá?}
{169}{}{Kde seenu víc léèivého prášku?}
{170}{}{Co mi mùeš øíct o kupcích, se kterımi naše vesnice obchoduje?}
{171}{}{Zapomeò na to.}
{172}{}{A hele, naše trdlo. Øíká se o tobì, e jsi Vyvolenı. Musím øíct, e duch našeho Zakladatele má opravdu divnı vkus.}
{173}{}{Lhúnhetyk.}
{174}{}{Pøeju ti bezpeènou cestu, trdlo... pro naše vlastní dobro.}
{175}{}{Héé????}
{176}{}{Zrádèe! Musíš zemøít.}
{177}{}{Zrádce svıch vlastních lidí!}
{178}{}{Proè tohle dìláš?}
{179}{}{Smrt ïáblovi!}
{180}{}{Radìji se od nich dr dál! Oškubou kohokoliv jen aby pøeili.}
{181}{}{Kde seenu víc léèivého prášku?}
{182}{}{Díky. Sbohem.}
{183}{}{Ještì se chci na nìco zeptat.}
{300}{}{Rád tì znovu vidím, Vyvolenı. Nech tì duchové váleèníkù vedou a chrání.}
{301}{}{Máš nìjaké problémy, Vyvolenı? Nesmíš nás zklamat. Pospìš si, prosím.}
{302}{}{Proè ti to tak dlouho trvá? Musíme získat GECK co nejdøív, Vyvolenı. Naše vesnice umírá.}
{303}{}{Vyvolenı, naše vesnice je u témìø mrtvá. Proè nám ještì neneseš svatı GECK?}
{970}{}{To je moje jméno.}
{971}{}{Mluvíš se mnou.}
{972}{}{To je ale blbá otázka. To jsem pøece já.}
{980}{}{O tom nic nevím.}
{981}{}{Je mi líto. Nemám tušení.}
{982}{}{O tom jsem nikdy neslyšel.}
{1000}{}{Starsi}
{1001}{}{Zakladatel}
{1002}{}{Obyvatel Vaultu}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Vault}
{1006}{}{Vyvoleny}
{1007}{}{Saman}
{1008}{}{Hakunin}
{1009}{}{Lecivy prasek}
{1010}{}{Most}
{1011}{}{Mynoc}
{1100}{}{Starší je tvoje matka a náš vùdce.}
{1101}{}{Náš slavnı pøedek, kterı nám pøedal své znalosti.}
{1102}{}{První èlovìk, kterı bojoval a zvítìzil nad chaosem.}
{1103}{}{To je naše krásná vesnice.}
{1104}{}{That’s trading outpost a few days east of here.}
{1105}{}{Vault je jako nebe.}
{1106}{}{Ty jsi Vyvolenı.}
{1107}{}{Léèí nás pomocí bylin a magie. Jeho chıše leí v severní èásti vesnice.}
{1108}{}{Léèí nás pomocí bylin a magie. Jeho chıše leí v severní èásti vesnice.}
{1109}{}{To je kouzelnı prášek, kterı èlovìka vyléèí. Ale zpùsobuje ospalost.}
{1110}{}{Velikı most je jedinım vıchodem z naší vesnice.}
{1111}{}{Stráí most, kterı vede do naší vesnice.}
