{100}{}{Vidíš bezdomovce.}
{101}{}{Vidíš bezdomovce Johna.}
{102}{}{Vidíš muže středního věku ve starých obnošených šatech.}
{103}{}{Promiň, cizinče, ale nemám na tebe čas.}
{104}{}{Proč nechtít mluvit?}
{105}{}{Dobře, pápá.}
{106}{}{Tak dobře, měj se.}
{107}{}{Počkej minutku. Proč se mnou nechceš mluvit?}
{108}{}{Jsme velmi uzavřené společenství a nechceme tu žádné problémy ani zásahy z okolního světa. Prosím, nech nás být.}
{109}{}{Dobře.}
{110}{}{Ahoj... a sbohem.}
{111}{}{Díky za všechno, co jsi pro nás udělal. Omlouvám se za svoje předešlé chování.}
{112}{}{Jdi do hajzlu, ty parchante!}
{113}{}{Sakra. Nesnáším, když se tohle stane.}
{114}{}{Tu máš! Tohle tě naučí.}
