{100}{}{Vidíš starší ženu.}
{101}{}{Vidíš Rebeccu.}
{102}{}{Vidíš starší ženu. I když vypadá, že mìla tìžký život, neubralo jí to ani trochu na jejím pøirozeném pùvabu.}
{103}{}{Ahoj, já jsem Rebecca. Mùžeme si promluvit nìkde v soukromí, prosím?}
{104}{}{Mluvit o èem?}
{105}{}{Proè ty potøebovat mluvit v soukromí?}
{106}{}{Dobøe.}
{107}{}{Ne. Já jít.}
{108}{}{Promiò, ale nemám zájem.}
{109}{}{O èem chceš se mnou mluvit?}
{110}{}{Jistì. Kde si mùžeme v klidu promluvit?}
{111}{}{Proè je potøeba to soukromí?}
{112}{}{(šeptá) Moje dcera se ztratila a já potøebuju pomoc. Tady o tom nemùžu mluvit. Mùžeme jít nìkam stranou?}
{113}{}{Dobøe.}
{114}{}{Proè ty potøebovat mluvit v soukromí?}
{115}{}{Ne, já jít.}
{116}{}{Dobøe, tak pojïme.}
{117}{}{Proè je potøeba to soukromí?}
{118}{}{Díky, ale ne. Nechci se do nièeho zaplést.}
{119}{}{(šeptá) Možná si o mnì budeš myslet, že jsem blázen, ale mám takový pocit, že mì poøád nìkdo sleduje. Je to znepokojující a jsem z toho nervózní.}
{120}{}{Dobøe, my jít nìkam jinam.}
{121}{}{Nemít èas pro nemocná hlava.}
{122}{}{Dobøe. Kde si mùžeme v klidu promluvit?}
{123}{}{Promiò, ale tohle se mi nìjak nelíbí.}
{124}{}{Díky. Mùžeme jít do mého stanu.}
{125}{}{Dobøe.}
{126}{}{Tady snad mùžeme nerušenì mluvit.}
{127}{}{Dobøe, tak v èem je problém?}
{128}{}{Vyvolený mít nejdøív pár otázek.}
{129}{}{Dobøe, tak co je ta veledùležitá vìc?}
{130}{}{Nejdøív se chci na nìco zeptat.}
{131}{}{Mám dceru, jmenuje se Chrissy. Je to trochu uliènice. Ráda se toulá, objevuje nové vìci a všude strká nos. Ale jinak je to hodné dítì, opravdu. Nejsou s ní problémy, vrací se domù vèas a chová se jako zodpovìdná dívka. Minulý týden se ale Chrissy nevrátila domù. Vyptávala jsem se všude po okolí, ale nikdo ji nevidìl ani o ní neslyšel. Zkoušela jsem ji hledat sama, ale Zeke mì nenechal. On je tu... nìco jako náš vùdce. Øekl, že pro mì není bezpeèné, abych venku pátrala na vlastní pìst a že pošle nìkolik mužù. Ale oni ji nenašli a navíc øíkají, že ji možná chytili otrokáøi.}
{132}{}{Ne, nechtít se zaplést.}
{133}{}{Potøebovat si to rozmyslet.}
{134}{}{Dobøe, vyvolený být tvùj hrdina.}
{135}{}{Promiò, ale nemám zájem.}
{136}{}{Musím si to rozmyslet.}
{137}{}{Dobøe, Rebecco. Pokusím se ti pomoct.}
{138}{}{A co z toho budu mít když ti pomùžu?}
{139}{}{Co chceš vìdìt?}
{140}{}{Co tady dít?}
{141}{}{Kdo šéf?}
{142}{}{Vyvolený hledat Vault 13. Vìdìt ty kde je?}
{143}{}{Mluv o Vault.}
{144}{}{Mluv o Darion.}
{145}{}{Dík. My mluvit, ty mít problém?}
{146}{}{Co se tady dìje?}
{147}{}{Kdo to tady vede?}
{148}{}{Hledám Vault 13. Nevíš o nìm nìco?}
{149}{}{Povìz mi nìco o tom vaultu.}
{150}{}{Povez mi o Darionovi.}
{151}{}{Dìkuju ti, Rebecco. A teï si promluvme o tvém problému.}
{152}{}{Øíkáme tomuhle místu 'Squat', protože bylo osídleno bezdomovci z mnoha mìst. Není to nic moc, ale je to všechno, co máme. Na západ odsud leží mìsto, které se jmenuje NCR. Vìdí o nás už delší dobu, ale nikdy nám nenabídli žádnou pomoc. A teï si najednou nárokují tohle místo. Tvrdí, že je to jejich dávný domov a chtìjí ho zpátky.}
{153}{}{Dobøe.}
{154}{}{Co tady oni chtít?}
{155}{}{Aha.}
{156}{}{Co je tady tak dùležitého, že tohle místo chtìjí?}
{157}{}{No... je tady starý vault. Myslím, že je to èíslo 15. Chtìjí ho vybílit a ukrást odtamtud všechny staré technologie, které tam stále ještì mùžou být.}
{158}{}{Aha. Já rozumìt.}
{159}{}{Bylo mi hned jasné, že je za tím ještì nìco jiného než jen pár hladových otrapù.}
{160}{}{Chápu.}
{161}{}{Tím se toho hodnì vysvìtluje. Moc jsi mi pomohla. Potøebuju se ještì zeptat na pár otázek.}
{162}{}{To bude Zeke. On to tady všechno vede. Najdeš ho v támhleté budovì. ::ukazuje na severovýchod::}
{163}{}{Dík. Mít další otázky.}
{164}{}{Díky. Potøebuju se tì ještì na pár vìcí zeptat.}
{165}{}{Promiò, ale nic mì nenapadá. Mùžeš se na to zeptat v NCR. Poslední dobou projevují o tenhle vault velký zájem.}
{166}{}{Dobøe, já udìlat to.}
{167}{}{Dobøe, jdu na to.}
{168}{}{No... nemáme o tom sice s nikým mluvit, ale protože potøebuju tvou pomoc... Darion opravuje Vault. On je náš dobrodinec. Jakmile bude Vault plnì funkèní, nastìhujeme se dovnitø a budeme koneènì v bezpeèí pøed nájezdníky a otrokáøi. Hned jakmile budou v poøádku systémy na výrobu jídla a vody.}
{169}{}{Rozumìt. Chtít vìdìt víc.}
{170}{}{Potøebuju ještì nìjaké informace.}
{171}{}{Není moc o èem mluvit, opravdu. Darion nikdy neopouští Vault. Když nám chce nìco øíct, vzkáže to po Zekeovi. Potkala jsem ho jen jednou a vypadal jako hodný chlapík.}
{172}{}{Dobøe.}
{173}{}{Hodní chlapi moc dlouho nepøežijí. A jak to, že on to tu vede?}
{174}{}{Aha.}
{175}{}{Dobøe. Moc jsi mi pomohla.}
{176}{}{Nemám nic, co bych ti dala. Jen svùj vdìk.}
{177}{}{To je víc než dost. Pomùžu ti.}
{178}{}{Na to, aby sis koupila moji pomoc, budeš potøebovat trochu víc.}
{179}{}{Ale co, tak já ti pomùžu.}
{180}{}{Mnohokrát ti dìkuju. Nikdy ti za to nepøestanu být vdìèná. Poèkám tady, dokud ji nepøivedeš... hej, nìkdo nás venku odposlouchával! Vidìla jsem jeho stín na stìnì stanu. Teï utíká tamtudy! ::ukazuje na severo-východ:: Musel to všechno slyšet!}
{181}{}{Já zùstat, ty nikam nejít!}
{182}{}{Ty nebát se, Vyvolený tvoji dceru najít.}
{183}{}{Jejda.}
{184}{}{Zkusím ho dohonit.}
{185}{}{To mì neodradí. Já tvoji dceru najdu.}
{186}{}{Co už. Nehody se stávají.}
{187}{}{Prosím, odejdi.}
{188}{}{Už to máš promyšlené?}
{189}{}{Já potøebovat nìco zeptat.}
{190}{}{Ne, stále pøemýšlet.}
{191}{}{Ne, stále to zvažuju.}
{192}{}{Chci se tì na pár vìcí zeptat.}
{193}{}{Rozmyslel sis to? Pomùžeš mi?}
{194}{}{Prominout, ale ne.}
{195}{}{Já pomoct.}
{196}{}{Ano, pomùžu ti.}
{197}{}{Ty musíš být ten èlovìk, který zachránil moji dceru. Nikdy ti za to nepøestanu být vdìèná. Dìkuju ti. Prosím, poèkej chvíli, promluvím si s Chrissy a potom bych ráda mluvila s tebou.}
{198}{}{Zachránil jsi moji dceru. Nikdy ti za to nepøestanu být vdìèná. Dìkuju ti. Prosím, poèkej chvíli, promluvím si s Chrissy a potom bych ráda mluvila s tebou.}
{199}{}{Dobøe.}
{200}{}{Moje dcera mi všechno øekla. Tìžko uvìøit, že je Darion takové monstrum, po tom všem, co pro nás udìlal. A to pomyšlení, že jsme mu pomáhali krýt ty jeho loupeže. Slibuji ti, že to tak nezùstane. Mluvila jsem se Zekem a ten mi øekl, že by tì chtìl vidìt. Zastav se za ním.}
{201}{}{Tìžko uvìøit, že Darion je takové monstrum, po tom všem, co pro nás udìlal. A to pomyšlení, že jsme mu pomáhali krýt ty jeho loupeže. Slibuji ti, že to tak nezùstane. Promluvím si se Zekem a všechno mu vysvìtlím. Urèitì tì taky bude chtít vidìt. Zastav se za ním.}
{202}{}{Díky.}
{203}{}{Doufám, že Chrissy brzy najdeš.}
{204}{}{Já hledat.}
{205}{}{Pokraèuju v pátrání.}
{206}{}{Díky za všechno, co jsi pro mì udìlal.}
{207}{}{Nedokážu øíct proè, ale myslím, že ji otrokáøi neunesli. Mám takový pocit, že je za tím nìco jiného. Ten pocit mám od té doby, co jsem o Chrissy mluvila se Zekem. Potøebuju nìkoho, kdo mi ji pomùže vypátrat. Pomùžeš mi, prosím?}
{208}{}{Poøád sem posílají lidi, kteøí nás pøesvìdèují, abychom odsud odešli. Ale oni nechápou, že my nemáme kam jinam jít. Nejsme natolik schopní, abychom pøežili nìkde jinde.}
{209}{}{Víš, je docela legraèní, že ve Vaultu už prý opravili kdeco, ale ne svìtla. To zatracené místo je poøád ještì osvìtleno pochodnìmi. A Darion nechce, aby nìkdo vìdìl, co se tam dole dìje. Bojí se, že kdyby na to nìkdo pøišel, tak nám všechno seberou. A tak nám øekl, abychom se nebavili s nikým novým, kdo se tu objeví... hlavnì ne s nikým z NCR.}
