{100}{}{Vidíš technika.}
{101}{}{Vidíš technika Enklávy.}
{102}{}{Vidíš osobu v laboratorním plášti. Vypadá sebevědomě a sebejistě.}
{103}{}{Ano, vojáku?}
{104}{}{Já tu nový. Potřebovat něco zeptat.}
{105}{}{Tak nashle. Už muset jít.}
{106}{}{Jsem tu nový a snažím se seznámit se základnou. Můžu ti položit několik otázek?}
{107}{}{Tak se měj. Uvidíme se později.}
{108}{}{Jistě. Pár minut můžu obětovat.}
{109}{}{S čím ti můžu pomoct?}
{110}{}{Co být tohle za místo?}
{111}{}{Co být tvoje práce?}
{112}{}{Kde být hlavní základna Enkláva?}
{113}{}{Hledat plány vertibird. Kde najít?}
{117}{}{Já muset jít.}
{118}{}{Co je tohle za místo?}
{119}{}{Co tu děláš?}
{120}{}{Kde se nachází hlavní základna Enklávy?}
{121}{}{Potřebuju se podívat na plány vertibirdu. Kde jsou?}
{125}{}{No nic. Už musím jít.}
{126}{}{Tohle je řídící a navigační centrum vzdušné dopravy. Odtud můžeme monitorovat a ovládat všechny pohyby vertibirdů.}
{127}{}{Aha. Ještě se zeptat.}
{128}{}{Rozumím. Mám ještě nějaké otázky.}
{129}{}{Jsem počítačový technik první třídy. Dohlížím na centrální počítač tam dole.}
{130}{}{Hmm... jo tak.}
{131}{}{Výborně. Přeju hodně pracovních úspěchů.}
{132}{}{Nepřicházíš náhodou odtamtud?}
{133}{}{Eee... ne, Vyvolený přijít ze sever.}
{134}{}{Ne, to opravdu ne, já jsem ze severu.}
{135}{}{Aha... ani jsem nevěděl, že tam máme základnu. No, naše hlavní základna je poblíž pobřeží kousek od San Francisca.}
{136}{}{Jak se tam dostat?}
{137}{}{Dobře... a jak se tam můžu dostat?}
{138}{}{Vertibirdem, samozřejmě. Jinak to nejde, leda snad lodí. Na to abys tam doplaval, je to přece jen moc daleko.}
{139}{}{Díky.}
{140}{}{Díky.}
{141}{}{Plány vertibirdu... nevidím důvod, proč bys o nich měl něco vědět. Ale zkus se zeptat vedle na údržbě.}
{142}{}{Dobře.}
{143}{}{Chápu.}
{153}{}{Jsi normální courat se tady okolo bez uniformy? Padej se rychle převlíct!}
{154}{}{Jestli tě seržant načapá bez uniformy, nakope ti prdel.}
{155}{}{Proč na sobě nemáš uniformu? }
{156}{}{Zatraceně! Byli jsme napadeni! Poplach!}
{157}{}{Vetřelci! Zavolejte stráže!}
{158}{}{Stráže! Vetřelci v komunikačním centru!}
{159}{}{Co se děje? Jsme napadeni?}
{160}{}{Proč ten poplach? Co se stalo?}
{161}{}{Co se to sakra zase děje?}
{162}{}{Jsem jen technik! Nestřílej!}
{163}{}{Já nejsem voják, vyznám se jen v technice!}
{164}{}{Tohle je laboratorní oblek, ne zbroj! Já tu jen pracuju!}
