{100}{}{Vidíš stráž.}
{101}{}{Vidíš stráž hlídající vchod.}
{102}{}{Vidíš osobu v energo zbroji neobvyklého vzhledu. Na prsou má znak, který nepoznáváš.}
{103}{gate1}{Stát! Tohle je federální území. Sem je vstup bez pøíslušného povolení zakázán.}
{104}{}{Eh... fedr..er..ace? Co to je?}
{105}{}{Já mít propustku... kam ji jen dát?}
{106}{}{Já být nový. Mnì øíct vy èekat mì.}
{107}{}{Aha. Já omlouvat. Hned jít pryè.}
{108}{}{Mám propustku... kde ji jenom mám.}
{109}{}{Jsem nováèek. Øekli mi, že mì budete oèekávat.}
{110}{}{Aha, promiò. Tak já jdu teda pryè.}
{111}{gate2}{Ty jsi trochu pomalejší, viï? Seber si svých pìt švestek a už se sem nevracej. Rozumíš?}
{112}{}{Chtít jít dovnitø.}
{113}{}{Dobøe. Já jít.}
{114}{gate3}{Nikdo sem... sakra. (Pomalu.) Ty potøebovat propustku, aby ty dostat dovnitø. Když ty nemít propustku, ty jít pryè. Když ty nejít pryè, ty dostat pøes držku. Ty rozumìt?}
{115}{}{A co když já místo toho ty nakopat prdel?}
{116}{}{Dobøe. Já jít.}
{117}{gate14}{(Dá ruku na zbraò.) Neomlouvej se mi! Buï mi ukaž propustku, nebo mi øekni heslo!}
{118}{}{Já nemoct najít propustka. Já nepamatovat heslo!}
{119}{}{Kašlat na to. Já zabít.}
{120}{}{Promiò, nemùžu tu propustku najít a nevím nic o žádném heslu.}
{121}{}{K èertu s tebou a takovými jako ty!}
{122}{gate5}{Radím ti dobøe, rychle odsud vypadni a nevracej se bez øádné propustky. Øíkám to dost jasnì?}
{123}{}{Ano.}
{124}{gate6a}{Rozumím. Mùžu laskavì slyšet heslo?}
{125}{gate6b}{Aha. (Dá ruku na zbraò.) Všichni nováèci se musí do služby hlásit sami. Radši odsud odejdi i s tìmi svými kumpány. Øíkám to dost jasnì?}
{126}{}{Ovèí hlava.}
{127}{}{Ano.}
{128}{gate7a}{Momentík prosím. (Po chvíli.) Dobøe, vypadáš v poøádku. Nahlas se výkonnému dùstojníkovi. Projdi vchodem, pak kolem budovy a jsou to ty první dveøe napravo.}
{129}{gate7b}{(Mumlá.) Ty vygumovaný palice jsou èím dál tím pitomìjší.}
{130}{}{Dobøe.}
{131}{gate8a}{Stát! - Hmm. Vidím, že tentokrát jsi sám. Tak rekrute, jaký je to heslo?}
{132}{gate8b}{Stát! - Zase ty. Koukám, že ta banda je poøád s tebou. (dá ruku na zbraò) Mìli byste odtud vypadnout a nevracet se sem. Øíkám to dost jasnì?}
{133}{}{Ovèí hlava.}
{134}{}{Ano.}
{135}{gate9}{Stát! - Zase ty? Doufám, že tentokrát už máš propustku nebo znáš heslo. Tak do toho, já èekám.}
{136}{}{No... já nevìdìt. Vrátit se.}
{137}{}{Kašlat na to. Já projít pøes tvý mrtvá tìlo.}
{138}{}{Podívej, já tu pitomou propustku prostì nemùžu najít...}
{139}{}{K èertu s tím. Nažer se olova, kreténe!}
{140}{gate10}{Tohle je poslední varování. Doporuèuju ti co nejrychleji vypadnout a nevracet se sem. Øíkám to dost jasnì?}
{141}{}{Dobøe, tak já zase jít...}
{142}{}{Starý dobrý slova... ty jít do prdel!}
{143}{}{Dobrá, už jdu.}
{144}{}{Øeknu ti to jako za starejch èasù... jdi do prdele!}
{145}{gate11a}{Stát! - Zase ty? Varoval jsem tì. Poplach! Vetøelec u vchodu! }
{146}{}{Zatracenì!}
{147}{}{Vetøelec u vchodu!}
{148}{}{Hlavní vchod byl napaden!}
{149}{}{Ke vchodu! Vetøelci u vchodu!}
{200}{}{...kretén...}
{201}{}{...jo, RADŠI odsud zmiz...}
{202}{}{...sráè jeden...}
{203}{}{...ano, pane! No jo kurva, pane!...}
{300}{}{Pokraèuj, vojáku.}
