{100}{}{Vidíš døevìnou bednu.}
{101}{}{Vidíš kovovou skøíòku.}
{102}{}{Vidíš masivní kontejner se zámkem odemykatelnım pomocí paklíèù a vysoce vıbušnou pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit odstranit.}
{103}{}{Vidíš masivní kontejner se zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit odstranit.}
{104}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení a vysoce vıbušnou pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit odstranit.}
{105}{}{Vidíš masivní kontejner se starım, rezavım zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit odstranit.}
{106}{}{Vidíš masivní kontejner se zámkem odemykatelnım pomocí paklíèù a pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit zneškodnit.}
{107}{}{Vidíš masivní kontejner se zámkem a pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit zneškodnit.}
{108}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení a pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit zneškodnit.}
{109}{}{Vidíš masivní kontejner se starım, rezavım zámkem a pastí umístìnou na zárubni kontejneru, kterou se mùeš pokusit zneškodnit.}
{110}{}{Vidíš masivní kontejner se zámkem odemykatelnım sadou paklíèù a kousek drátku, kterı èouhá ze zárubnì kontejneru, kterı se mùeš pokusit zneškodnit.}
{111}{}{Vidíš masivní kontejner se zámkem a kousek drátku, kterı èouhá ze zárubnì kontejneru, kterı se mùeš pokusit zneškodnit.}
{112}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení a kousek drátku, kterı èouhá ze zárubnì kontejneru, kterı se mùeš pokusit odstranit.}
{113}{}{Vidíš masivní kontejner se starım, rezavım zámkem a kousek drátku, kterı èouhá ze zárubnì kontejneru, kterı se mùeš pokusit odstranit.}
{114}{}{Vidíš masivní kontejner se zámkem odemykatelnım pomocí paklíèù, kterı se mùeš pokusit vypáèit.}
{115}{}{Vidíš masivní kontejner se zámkem, kterı se mùeš pokusit vypáèit.}
{116}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení, kterı se mùeš pokusit vypáèit.}
{117}{}{Vidíš masivní kontejner se starım, rezavım zámkem, kterı se mùeš pokusit vypáèit.}
{118}{}{Vidíš masivní kontejner se zámkem odemykatelnım pomocí paklíèù a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{119}{}{Vidíš masivní kontejner se zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{120}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{121}{}{Vidíš masivní kontejner se starım, rezavım zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{122}{}{Vidíš masivní kontejner se zámkem odemykatelnım pomocí paklíèù a pastí umístìnou na zárubni kontejneru.}
{123}{}{Vidíš masivní kontejner se zámkem a pastí umístìnou na zárubni kontejneru.}
{124}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení a pastí umístìnou na zárubni kontejneru.}
{125}{}{Vidíš masivní kontejner se starım a rezavım zámkem a pastí umístìnou na zárubni kontejneru.}
{126}{}{Vidíš masivní kontejner se zámkem odemykatelnım pomocí paklíèù a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{127}{}{Vidíš masivní kontejner se zámkem a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{128}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{129}{}{Vidíš masivní kontejner se starım, rezavım zámkem a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{130}{}{Vidíš masivní kontejner se zámkem odemykatelnım pomocí paklíèù.}
{131}{}{Vidíš masivní kontejner se zámkem.}
{132}{}{Vidíš masivní kontejner bez zjevného odemykacího zaøízení.}
{133}{}{Vidíš masivní kontejner se starım, rezavım zámkem.}
{134}{}{Vidíš ponièenı kontejner se zámkem odemykatelnım pomocí paklíèù a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{135}{}{Vidíš ponièenı kontejner se zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{136}{}{Vidíš ponièenı kontejner bez zjevného odemykacího zaøízení a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{137}{}{Vidíš ponièenı kontejner se starım, rezavım zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{138}{}{Vidíš ponièenı kontejner se zámkem odemykatelnım pomocí paklíèù a pastí umístìnou na zárubni kontejneru.}
{139}{}{Vidíš ponièenı kontejner se zámkem a pastí umístìnou na zárubni kontejneru.}
{140}{}{Vidíš ponièenı kontejner bez zjevného odemykacího zaøízení a pastí umístìnou na zárubni kontejneru.}
{141}{}{Vidíš ponièenı kontejner se starım, rezavım zámkem a pastí umístìnou na zárubni kontejneru.}
{142}{}{Vidíš ponièenı kontejner se zámkem demykatelnım pomocí paklíèù a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{143}{}{Vidíš ponièenı kontejner se zámkem a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{144}{}{Vidíš ponièenı kontejner bez zjevného odemykacího zaøízení a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{145}{}{Vidíš ponièenı kontejner se starım, rezavım zámkem a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{146}{}{Vidíš ponièenı kontejner se zámkem odemykatelnım pomocí paklíèù.}
{147}{}{Vidíš ponièenı kontejner se zámkem.}
{148}{}{Vidíš ponièenı kontejner bez zjevného odemykacího zaøízení.}
{149}{}{Vidíš ponièenı kontejner se starım, rezavım zámkem.}
{150}{}{Vidíš starı kontejner se zámkem odemykatelnım pomocí paklíèù a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{151}{}{Vidíš starı kontejner se zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{152}{}{Vidíš starı kontejner bez zjevného odemykacího zaøízení a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{153}{}{Vidíš starı kontejner se starım, rezavım zámkem a vysoce vıbušnou pastí umístìnou na zárubni kontejneru.}
{154}{}{Vidíš starı kontejner se zámkem odemykatelnım pomocí paklíèù a pastí umístìnou na zárubni kontejneru.}
{155}{}{Vidíš starı kontejner se zámkem a pastí umístìnou na zárubni kontejneru.}
{156}{}{Vidíš starı kontejner bez zjevného odemykacího zaøízení a pastí umístìnou na zárubni kontejneru.}
{157}{}{Vidíš starı kontejner se starım, rezavım zámkem a pastí umístìnou na zárubni kontejneru.}
{158}{}{Vidíš starı kontejner se zámkem odemykatelnım pomocí paklíèù a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{159}{}{Vidíš starı kontejner se zámkem a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{160}{}{Vidíš starı kontejner bez zjevného odemykacího zaøízení a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{161}{}{Vidíš starı kontejner se starım, rezavım zámkem a kousek drátku, kterı vyèuhuje ze zárubnì kontejneru.}
{162}{}{Vidíš starı kontejner se zámkem, kterı mùeš odemknout pomocí paklíèù.}
{163}{}{Vidíš starı kontejner se zámkem.}
{164}{}{Vidíš starı kontejner bez zjevného odemykacího zaøízení.}
{165}{}{Vidíš starı kontejner se starım, rezavım zámkem.}
{166}{}{Aktivuješ past a ta tì zasáhla za }
{167}{}{ hit bodù.}
{168}{}{ aktivuje past a byl zasaen za }
{169}{}{ hit bodù.}
{170}{}{Úspìšnì odemykáš zámek kontejneru.}
{171}{}{Díky své nešikovnosti se zámek kontejneru zasekl.}
{172}{}{Nepodaøilo se ti kontejner odemknout.}
{173}{}{ úspìšnì odemyká zámek kontejneru.}
{174}{}{ nezkušeností zpùsobí zaseknutí zámku kontejneru.}
{175}{}{ se nepodaøilo dveøe zamknout.}
{176}{}{Podaøilo se ti vypáèit zámek kontejneru.}
{177}{}{Pøi páèení zámku sis poranil záda a to ti zpùsobilo jeden bod poškození.}
{178}{}{Pøi páèení zámku sis poranil záda a to ti zpùsobilo poškození za }
{179}{}{ hit bodù.}
{180}{}{Na vypáèení tohoto zámku nemáš dostateènou sílu.}
{181}{}{ se podaøilo vypáèit zámek kontejneru.}
{182}{}{ si poranil záda, kdy se pokoušel vypáèit zámek, co mu zpùsobilo jeden bod poškození.}
{183}{}{ si poranil záda, kdy se pokoušel vypáèit zámek, co mu zpùsobilo poškození za }
{184}{}{ hit bodù.}
{185}{}{ nemá na vypáèení zámku dostateènou sílu.}
{186}{}{ si poranila záda, kdy se pokoušela vypáèit zámek, co jí zpùsobilo jeden bod poškození.}
{187}{}{ si poranila záda, kdy se pokoušela vypáèit zámek, co jí zpùsobilo poškození za }
{188}{}{ hit bodù.}
{189}{}{Úspìšnì zamykáš kontejner.}
{190}{}{Nepodaøilo se ti kontejner zamknout.}
{191}{}{ úspìšnì zamyká kontejner.}
{192}{}{ se nepodaøilo kontejner zamknout.}
{193}{}{Vıbuch na tomto kontejneru nezanechal ani škrábnutí.}
{194}{}{Nacházíš na kontejneru past.}
{195}{}{Nepodaøilo se ti na kontejneru najít past.}
{196}{}{Zkušenì odstraòuješ past.}
{198}{}{Nepovedlo se ti odstranit past.}
{199}{}{ nachází na kontejneru past.}
{200}{}{ se nepodaøilo najít na kontejneru past.}
{201}{}{ zkušenì odstraòuje past.}
{202}{}{ se nepodaøilo zneškodnit past na dveøích.}
{203}{}{Zdá se, e ten kontejner je zamèenı.}
{204}{}{Všiml sis pasti v zárubni kontejneru.}
{205}{}{ objevil past v zárubni kontejneru.}
{206}{}{Na tento kontejner nemùeš umístit past, protoe je otevøenı.}
{207}{}{ nemùe na tento kontejner umístit past, protoe je otevøenı.}
{208}{}{Zkušenì umisuješ past na kontejner.}
{209}{}{Nepodaøilo se ti umístit past na kontejner.}
{210}{}{ zkušenì umisuje past na kontejner.}
{211}{}{ se nepodaøilo umístit past na kontejner.}
{212}{}{Vidíš lednièku.}
{400}{}{Odemykáš kontejner.}
{601}{}{It is open, dummy.}
{610}{}{You fail spectacularly, and the exposive goes off prematurely.}
{611}{}{ fails spectacularly, and the exposive goes off prematurely.}
