{100}{}{Vidíš dítì vykøikující reklamní slogany.}
{101}{}{Toto dítì, jak se zdá, je placeno za to, aby propagovalo urèitý druh turistické atrakce.}
{500}{}{Uvidíte tajemnou mumii!}
{501}{}{Uvidíte starobylý skvost!}
{502}{}{Nefalšovaná mumie, právì teï!}
{503}{}{Uvidíte egyptského prince!}
{504}{}{Uvidíte Královnu Nilu!}
{505}{}{Vstupte do skuteèného domu hrùzy!}
{506}{}{Záhada Podsvìtí vynesena na svìtlo svìta!}
{507}{}{Pøijïte, pøijïte všichni!}
{508}{}{Životní pøíležitost!}
