{100}{}{Vidíš člena Cechu otrokářů.}
{150}{}{Vidíš Metzgera, šéfa Cechu otrokářů.}
{151}{}{[MLUVIT]}
{152}{}{Stráže! Do útoku!}
{153}{}{[KONEC]}
{154}{}{Vrať se ráno, sakra! Pracuju jen přes den.}
{155}{}{[KONEC]}
{156}{}{Co je? Začínáš mě pěkně štvát.}
{157}{}{Chci se omluvit.}
{158}{}{Promiň, předtím jsem byl zfetovanej. Nemyslel jsem to tak.}
{159}{}{Hele, co máš za problém?}
{160}{}{Chci se na něco zeptat.}
{161}{}{Už to tak vypadá. Nashle.}
{162}{}{Coo?}
{163}{}{No, tak na to už je moc pozdě. Vypadni.}
{164}{}{Prosím, prosím, prosím, omlouvám se.}
{165}{}{No dobře, za pokus to stálo.}
{166}{}{Tak jdi do hajzlu!}
{167}{}{Dobře, dobře. Přijímám omluvu.}
{168}{}{Skvělé. Můžu se tě na něco zeptat?}
{169}{}{Jsem rád, že jsme si to vyříkali. Uvidíme se později.}
{170}{}{Zdravím. Rád tě vidím.}
{171}{}{Ahoj, Metzgere. Musíme si promluvit.}
{172}{}{Nápodobně. Nashle.}
{173}{}{Škyt.}
{174}{}{Jsem Metzger, šéf Cechu otrokářů. Co potřebuješ?}
{175}{}{Ano, mám nějaké otázky.}
{176}{}{Ne, díky. Už půjdu.}
{177}{}{Swavuh???}
{178}{}{Odejdi prosím. Hned.}
{179}{}{Nebo co?}
{180}{}{Dobře. Ale ještě se vrátím!}
{181}{}{Dobře. Nashle.}
{182}{}{Co potřebujete vědět?}
{183}{}{O obchodníkovi Vicovi...}
{184}{}{Můžu se připojit k Cechu otrokářů?}
{185}{}{Chci prodat svého manžela do otroctví.}
{186}{}{Chci prodat svoji manželku. Za kolik?}
{187}{}{Chci prodat tady jednoho z mých přátel.}
{188}{}{Pověz mi něco o Cechu.}
{189}{}{Jaká města kupují vaše otroky?}
{190}{}{Chci koupit otroka.}
{191}{}{Hledám Vault 13. Neslyšel jsi o něm něco?}
{192}{}{Metzger? To je zvláštní jméno.}
{193}{}{Nic. Už musím jít.}
{195}{}{Pochází ze starýho jazyka, z předválečný doby nebo tak nějak.}
{196}{}{Metzger znamená řezník. Trefný, nemyslíš?}
{197}{}{To bylo jméno mýho pradědy. Pocházel odněkud z východu, za velkou louží.}
{198}{}{Četl jsem nějakou knihu o Metzgerovi. Byl prezident nebo něco takového.}
{199}{}{To je mi ale náhodička, divochu.}
{200}{}{Je to němacky, německy, nimecky nebo tak nějak. Takovej starobylej jazyk z dávný doby.}
{201}{}{I ty, Brute?}
{202}{}{Aha. Mám ještě otázku.}
{203}{}{To je ta nejblbější věc, kterou jsem kdy slyšel.}
{204}{}{Fascinující. Už musím jít.}
{205}{}{Naším posláním je poskytovat spolehlivou a vysoce kvalitní pracovní sílu, která dokáže uspokojit stále rostoucí poptávku ve větších městech. Chceš se k nám přidat?}
{206}{}{Jistě. Zní to skvěle.}
{207}{}{Na to zapomeň.}
{208}{}{Zpátky k mojí otázce. Jaká města kupují vaše otroky?}
{209}{}{Promiň, ale to je interní záležitost.}
{210}{}{Dobře. Hlásím se!}
{211}{}{Ne! Jste zvrácení lidé!}
{212}{}{Popřemýšlím o tom. Mám ještě nějaké otázky.}
{213}{}{Hmm, vrátím se později.}
{214}{}{Musíme ti udělat malou značku na čele, aby byla jasná tvoje příslušnost k cechu. Jsi připraven?}
{215}{}{To zní skvěle! Udělejte to!}
{216}{}{Myslím, že ne. Můžu se ještě na něco zeptat?}
{217}{}{Teď nemám čas. Už musím jít.}
{218}{}{Vítej v Cechu!}
{219}{}{Skvěle, mám otázky!}
{220}{}{Dobře, díky. Ještě se vrátím.}
{221}{}{Vault 13? Ne. Počkej... myslím, že Vic je z Vault City. Možná je to ono.}
{222}{}{Jo a kde to je?}
{223}{}{Ne, ale mám ještě další otázku.}
{224}{}{Ne, zapomeň na to.}
{225}{}{Prodáváme většinu našich otroků do Vault City a do New Rena. New Reno je jihovýchodně odsud a obchoduje s ním většina Denu.}
{226}{}{Kde je Vault City?}
{227}{}{Mám další otázky.}
{228}{}{Díky, už musím jít.}
{229}{}{Vault City je odsud na východ a trochu na jih. Vic odtamtud pochází.}
{230}{}{Mám další otázky.}
{231}{}{Díky, už půjdu.}
{232}{}{Hmm, vypadá jako zdravý otrok. Dám ti za něj }
{233}{}{ dolarů.}
{234}{}{Dobře! Dohodnuto.}
{235}{}{Eh, zapomeň na to.}
{236}{}{V žádném případě! Chci dvojnásobek!}
{237}{}{Jsi pěknej vydřiduch. Tady jsou peníze!}
{238}{}{Díky. Mám další otázky.}
{239}{}{Dík. Naskle.}
{240}{}{Ještě něco?}
{241}{}{Ano, mám otázku.}
{242}{}{Ne. Nashle.}
{243}{}{Kterýho "přítele" chceš prodat?}
{244}{}{Eh, zapomeň na to.}
{245}{}{Zajímavý. Dám ti za něj }
{246}{}{ dolarů.}
{247}{}{Prodáno!}
{248}{}{Ne, díky.}
{249}{}{Chci víc peněz!}
{250}{}{Dobře, dám ti za něj }
{251}{}{ , ale ne víc!}
{252}{}{Prodáno!}
{253}{}{To je málo.}
{254}{}{To je moc málo. Odcházím.}
{255}{}{Co chceš Vicovi? Je teď můj majetek. Neměl se mnou vyjebat.}
{256}{}{Chci ho koupit.}
{257}{}{Proč ho tady držíš?}
{258}{}{O ničem. To je jedno.}
{259}{}{Není na prodej... zatím.}
{260}{}{Proč ne?}
{261}{}{Aha, dobře.}
{262}{}{Bude tě stát $2000.}
{263}{}{Tady jsou peníze.}
{264}{}{To je moc. Možná později.}
{265}{}{Stojí $1000.}
{266}{}{Tady jsou peníze.}
{267}{}{Tolik u sebe nemám. Zatím.}
{268}{}{Naše rádio je rozbitý a on má za úkol ho opravit.}
{269}{}{Aha.}
{270}{}{Nemáš dost peněz!}
{271}{}{A sakra. Můžu se na něco zeptat?}
{272}{}{Promiň, ještě se vrátím.}
{307}{}{Jak se opovažuješ sem znovu přijít potom, co jsi opustil svý bratry během honu na otroky? Stráže! Do útoku!}
{308}{}{[KONEC]}
{309}{}{Výborně! Počítej ale s tím, že ti cesta tam a zpět pár dní zabere. Jsi připraven vyrazit?}
{310}{}{Ne. Ještě se vrátím.}
{311}{}{Ano, jsem připraven. Pojďme.}
{312}{}{Á, jsi zpět z honu na otroky. Tak se podíváme, jak se ti dařilo...}
{313}{}{[Více]}
{314}{}{[Více]}
{315}{}{Zabil jsi potenciální otroky! Mrtvej člověk je nám k ničemu! Zabíjej jenom ty, který představujou hrozbu. Ti ostatní jsou neškodní.}
{316}{}{[Více]}
{317}{}{Nepřivedl jsi žádný otroky! Co to s tebou k čertu je? Tady se snažíme peníze vydělat, ne prodělat.}
{318}{}{[Více]}
{319}{}{Celkem ti to šlo dobře. Pokračuj v dobrý práci a možná si tě tu i chvíli nechám.}
{320}{}{Díky. Budu se snažit.}
{321}{}{Nevím, jestli se mi to až tak líbí.}
{322}{}{Potřebuješ zlepšit svoji techniku získávání otroků.}
{323}{}{Zkusím to.}
{324}{}{Omlouvám se za svůj chabý výkon.}
{325}{}{Myslím, že mi to jde docela dobře.}
{326}{}{Zatraceně! Vedl sis otřesně. Snažíš se mě zruinovat? Příště si dej větší pozor. Nemusíš je všechny zabít! Zabíjej jenom ty vzpurný. Ty bezbranný nech do sbírky.}
{327}{}{Promiň, Metzgere.}
{328}{}{Hele, je to fuška být otrokářem!}
{329}{}{Chtěl bych vidět tebe.}
{330}{}{Chci jít na hon otroků.}
{331}{}{Zatraceně! Nesnáším, když ztratím na honu člena cechu. Zkuste si víc krejt záda!}
{332}{}{Celkem ti to šlo dobře. Tady máš $}
{333}{}{ jako motivační bonus pro další dobře odvedenou práci.}
