{100}{}{Vidíš gangstera.}
{150}{}{Zdá se, e je to èlen Laøina gangu.}
{151}{}{Zdá se, e je to èlenka Laøina gangu.}
{200}{}{Chytráku.}
{201}{}{Tady jseš!}
{202}{}{Odplata.}
{203}{}{Pojï sem.}
{204}{}{Ještì jsem neskonèil.}
{205}{}{Dìvka.}
{225}{}{Zajímalo by mì, co se tu bude dít po Metzgerovì smrti.}
{226}{}{Take Metzger u je koneènì mrtvej?}
{227}{}{To byla tvoje práce?}
{228}{}{Den u nikdy nebude stejnej.}
{240}{}{Nemùu uvìøit, e jsme je fakt porazili!}
{241}{}{Metzger nás teï bude muset respektovat.}
{242}{}{Pìknì jsme jim to nandali.}
{243}{}{Ukázali jsme jim naše vlastní pojetí spravedlnosti.}
{244}{}{Bez tebe bysme to nedokázali!}
{245}{}{Díky za pomoc!}
{246}{}{Dokázali jsme to!}
{247}{}{Kašleš na nás?}
{248}{}{Dávej si teï radši bácha.}
{249}{}{Lara je jedinej dùvod, proè tì teï neobìsíme.}
{250}{}{Co to jako bylo?}
{251}{}{Srabe.}
{252}{}{Je mi z tebe na blití.}
{253}{}{Ztra se.}
{254}{}{Vypadni.}
{255}{}{A budeš chtít, mùeme zaèít.}
{256}{}{Je naèase jim to vrátit.}
{257}{}{Nenávidím èekání.}
{258}{}{Tak u pojïme.}
{259}{}{Mùeme vyrazit?}
{260}{}{Dej vìdìt Laøe, a bude ten správnej èas.}
{270}{}{Chceš se k nám pøidat?}
{271}{}{Jseš tu kvùli Laøe, co?}
{272}{}{Jak to jde?}
{273}{}{Promluv si s Larou.}
{274}{}{Ahoj.}
{275}{}{Jdeš za Larou?}
{300}{}{Ahoj.}
{301}{}{Jak to jde?}
{302}{}{Doufám, e to jde dobøe.}
{303}{}{Take nám pomùeš?}
{304}{}{Rád tì vidím.}
{305}{}{Tylerovi to brzo vrátíme...}
{306}{}{Nìco novıho?}
{310}{}{Díky za pomoc. Ubohá Lara.}
{311}{}{Koneènì jsme je dostali!}
{312}{}{Bez tebe bysme to nedokázali.}
{313}{}{Aspoò padla Lara v boji.}
{314}{}{Nemùu uvìøit, e to Lara nepøeila.}
{315}{}{Ukázali jsme Metzgerovi, kdo je tady nejlepší.}
{316}{}{Metzgerovi je bez nás líp.}
{350}{}{Øekl sis o to!}
{351}{}{Jsou z nich mrtvoly!}
{352}{}{Nakopem jim prdel!}
{400}{}{Nakopali jsme jim prdel! Jestli budeš nìco potøebovat, najdeš nás v kostele.}
{500}{}{Doprdele, nemùu uvìøit, e jsme ztratili Laru. Sice jsme se postarali o tenhle pøedvoj, ale Tyler a jeho lidi jsou poøád naivu. Pokud je napadnem teïka bìhem jejich flámu v Obytnı ètvrti, urèitì je zastihnem nepøipravenı, tak to pojïme skonèit. Jdeš do toho?}
{501}{}{Nejdøív se vyléèím. Øeknu ti, a budu moct.}
{502}{}{Pojïme.}
{510}{}{Mùeme jít vyøídit Tylera a jeho partu?}
{520}{}{Hele, nechoï moc daleko. Potøebujeme to skonèit dneska v noci.}
