{100}{}{Vidíš hrdloøeza.}
{101}{}{Vidíš Joeyho.}

{150}{}{Tenhle chlapík nevypadá pøíliš pøátelsky.}
{151}{}{[MLUVIT]}

# 1.
{152}{}{Udìlám ti facelift ksichtu, sráèi!}
{153}{}{Jo? Tak pojï a zkus to.}
{154}{}{Hej, tak moment!}
{155}{}{Bıt tebou, tak si to poøádnì rozmyslím.}

# 2.
{156}{}{Co chceš? Proè bych tì teï nemìl zabít za to, co jsi udìlal, místo toho, abych poslouchal ty tvoje vásty?}
{157}{}{Chci s tebou mluvit o tom duchovi, kterı sem v noci chodí.}
{158}{}{Vzal jsi z toho strašidelného domu pøívìsek?}
{159}{}{Zapomeò na to. Místo toho ti nakopu prdel.}
{160}{}{Nic. Jen procházím.}

# 3.
{161}{}{O èem to sakra mluvíš?}
{162}{}{Ukradl jsi z toho strašidelného domu pøívìsek?}
{163}{}{O nièem. To je jedno.}
{164}{}{Zapomeò na to. Teï tì zabiju a pak naporcuju.}

# 4.
{165}{}{Já... já nevím, o èem to mluvíš.}
{166}{}{Já myslím, e to moc dobøe víš! Ukradl jsi té mrtvé dívce pøívìsek a její duch teï nemùe odpoèívat v pokoji.}
{167}{}{Dobøe, vezmu si ho tedy násilím.}

# 5.
{168}{}{T-to je k-kurva šílenı! Nn-emáš v sso-bì nìjakou ttu Tubb-yho ssra-èku? Já-já jsem t-tam ádnıho d-ducha nevidìl, k-kdy jsem t-tam byl... byl jsem sjetej, t-to nebylo skuteènı.}
{169}{}{Poslyš, koupím ho od tebe.}
{170}{}{Dej mi ho, nebo se k ní pøipojíš.}
{171}{}{Kdy ho teï nevrátíš, tak tì bude pronásledovat. A ji nikdo nezastaví.}

# 6.
{172}{}{Coe? No jasnì, jasnì. Na t-to vezmi jed. Budeš muset vypláznout pár babek. Zadarmo ti ho nedám! $50, nebo nech bejt!}
{173}{}{Dobøe, tady jsou peníze.}
{174}{}{Tady máš $20 a buï rád, e si ho nevezmu z tvojí mrtvoly.}
{175}{}{No, vlastnì jsem si to rozmyslel. Zatím.}
{176}{}{Dej mi ho, nebo tì zabiju.}

# 7.
{177}{}{Tady je. A teï u mi dej pokoj.}
{178}{}{Nechám.}
{179}{}{A u se to znovu neopakuje!}

# 8.
{180}{}{H-hej! Vdy nemáš peníze! Vypadni odsud!}
{181}{}{Sakra. Ještì se vrátím.}
{182}{}{V tom pøípadì tì budu muset zabít.}

# 9.
{183}{}{Zdar. Jak se máš?}
{184}{}{Dobøe. A ty?}
{185}{}{Moc dobøe ne.}
{186}{}{Vzal jsi z toho domu pøívìsek?}
{187}{}{Co víš o tom duchovi, kterı sem v noci chodí?}

# 10.
{188}{}{Nazdar, chlape. Já jsem Joey. Co dìláš na mım území?}
{189}{}{Tvém území? Nemyslím si, e je tvoje.}
{190}{}{Moná tì hledám.}
{191}{}{U jdu pryè. Nashle.}
{192}{}{Sháním informaci.}

# 11.
{193}{}{Nazdar, buchto. Hledáš Joeyho? Tak tady jsem.}
{194}{}{Ne. Jdi pryè.}
{195}{}{Moná. Co mi nabídneš?}
{196}{}{Chci nìjaké informace.}
{197}{}{Ne, promiò. U musím jít.}

# 12.
{198}{}{Mám nìjakej Jet. Je to vynikající matroš pøímo z New Rena. Chceš?}
{199}{}{V ádném pøípadì!}
{200}{}{Za kolik?}
{201}{}{Ne, chci nìjaké informace.}
{202}{}{U musím jít. Nashle.}

# 13.
{203}{}{Co ty a já spolu? Jdeme na to?}
{204}{}{Dobøe.}
{205}{}{Ani kdybys byl poslední nezmutovanı mu na planetì.}
{206}{}{Eh, no... myslím, e ne. Potøebuju nìco jiného.}

# 14.
{207}{}{Však ty se vrátíš.}
{208}{}{Moná.}
{209}{}{S tím nepoèítej.}
{210}{}{Poèkej! Mùu se na nìco zeptat?}

# 15.
{211}{}{Takhle se mnou nikdo mluvit nebude!}
{212}{}{Já ano. Umíš ještì nìco jiného ne mluvit?}
{213}{}{To je jedno. Prodáváš nìco, nebo jenom mluvíš?}
{214}{}{Omlouvám se. Jen se dívám kolem a neznám to tady.}

# 16.
{215}{}{Co chceš?}
{216}{}{Hledám pøívìsek.}
{217}{}{Potøebuju nìjaké informace o tom strašidelném domì.}
{218}{}{Proè jsou u toho starého kostela ty stráe?}
{219}{}{Nic, co mùeš obstarat.}
{220}{}{Slyšel jsi u nìkdy o Vaultu 13?}
{221}{}{Eh, zapomeò na to. Zatím.}

# 17. The Church
{222}{}{Jo ty myslíš Tylera a jeho gang? Hlídaj nìjakı hovna, co chodìj z Vault City. Nìjakı zkurvenì velkı bedny. Jednou za èas je vyzvednou karavany smìøující do New Rena.}
{223}{}{Mùeš mi o nich øíct ještì nìco?}
{224}{}{Mùu se zeptat na nìco jiného?}
{225}{}{Dobøe, díky. Nashle.}

# 18.
{226}{}{Co chceš ještì vìdìt?}
{227}{}{Kdo je Tyler?}
{228}{}{Kde je New Reno?}
{229}{}{Co je uvnitø?}
{230}{}{Chci se zeptat na nìco jiného.}
{231}{}{To je všechno. Nashle.}

# 19 Who's Tyler?
{232}{}{Tyler je podrazák, kterej s náma vydrbal pøi jednom pìknım kšeftíku s Metzgerem, ale srát na to! U je mi to kurva jedno. Ale klidnì bych mu tu jeho zasranou prdel nakopal. Lara a on se poøád hádají. Má to nìco spoleènıho s Tylerem a jejím bratrem.}
{233}{}{To by mohlo bıt uiteèné. Mùeš mi o nich øíct ještì nìco?}
{234}{}{Mùu se zeptat ještì na nìco jiného?}
{235}{}{Dobøe, díky. Sbohem.}

# 20. New Reno?
{236}{}{New Reno je daleko dole na jihu a potom trochu na vıchod. Je tam hodnì rušno, ale taky zatracenì nebezpeèno. Bejt tebou, tak tam nelezu. Ale mùu ti to ukázat na tı tvı podivnı vìci s obrazovkou.}
{237}{}{Myslím, e teï u to najdu. Mùeš mi o nich øíct ještì nìco?}
{238}{}{Mùu se ještì na nìco zeptat?}
{239}{}{Dobøe, díky. Sbohem.}

# 21. Contents?
{240}{}{Co já vím.}
{241}{}{Zajímavé. Mùeš mi o nich øíct ještì nìco?}
{242}{}{Mùu se ještì na nìco zeptat?}
{243}{}{Dobøe, díky. Sbohem.}

# 22.
{244}{}{e jsi to ty, prodám ti Jet za $500.}
{245}{}{Ne, díky. Nashle.}
{246}{}{Ne, díky, ale chci se ještì na nìco zeptat.}
{247}{}{To je moc!}
{248}{}{Dobøe, koupím ho.}

# 23.
{249}{}{Jestli nemáš peníze, tak pøijï, a si to budeš moct dovolit. Ne abych tì vidìl, e kupuješ od nìkoho jinıho, nebo ti nakopu tu tvoji zasranou prdel. Já jedinej mám èistı neøíznutı svinstvo, dovezenı pøímo z New Rena.}
{250}{}{Poèkej, koupím ho.}
{251}{}{Mùu se ještì na nìco zeptat?}
{252}{}{Nashle.}

# 24.
{253}{}{Dobøe, sníím cenu na $350, ale to je maximum! To je moje koneèná nabídka. Platíš velkı prachy za dobrej fet. Nekupuj od Tubbyho nebo od jinejch jemu podobnejch zoufalcù. Ti maj fet øedìnej. Já jsem jedinej na míle daleko, kterej mùe nabídnout ten nejlepší materiál.}
{254}{}{Zapomeò na to. Mùu se ještì na nìco zeptat?}
{255}{}{Dobøe, koupím ho.}
{256}{}{Zapomeò na to. Nashle.}

# 25
{257}{}{Vault... Vault... Vault 13? O tom jsem urèitì nikdy neslyšel. Neøíkej mi, e pøišli s další novou drogou! Nic nemùe bıt lepší ne Jet!}
{258}{}{Ne, ty debile.}
{259}{}{Ne, to je místo. Mùu se ještì na nìco zeptat?}
{260}{}{Ano, je to skvìlá droga.}
{261}{}{Ne, nashle.}

# ??Don't know what this is for.
{262}{}{Tady Joey toho moc nenakecá.}

# 4. extra
{300}{}{Pravdìpodobnì ne. Nashle.}

# Addition for Node 17
{350}{}{Spíš nebo co? Ukázalo se, e je Lara pìkná dìvka. To ona odpráskla Tylera. Slyšel jsem, e v tom má prsty Metzger. No, radši se vrátím do práce.}
{351}{}{Spíš nebo co? Ukázalo se, e je Lara pìkná dìvka... škoda, e je mrtvá. Zametla s Tylerovou grupou. Co jsem naposled slyšel, tak to teï vede její gang.}