# 0. Look
{100}{}{Vidíš stráž.}
{101}{}{Vidíš Marca, strážce.}
{102}{}{Vidíš Marca, jednoho z Tylerových stráží.}

# 1. Door opened
{150}{}{Nazdar, Tylere!}

# 2. Hostile
{200}{}{Co to...?}

# 3. Gang 1 Won War
{225}{}{Díky za tip. To byla fakt sranda.}
{226}{}{Já vìdìl, že ty sraby dostanem.}
{227}{}{Škoda, že jsme je všechny zabili. Co teï budeme dìlat?}
{228}{}{Jsme skvìlý, že jo?}
{229}{}{Jsme fakt dobrý.}
{230}{}{Dostali pìknì na prdel! Jo kurva!}

# 4. TRAP NO
{250}{}{Promluv si s Tylerem, holka, ne se mnou.}
{251}{}{Jak to jde? Jestli nìco potøebuješ, promluv si tady s Tylerem.}
{252}{}{Na co èumíš?}
{253}{}{Promluv si s Tylerem, chlape, ne se mnou.}

# 5. TRAP SET
{255}{}{Dnes v noci se chystáme nìkomu natrhnout prdel!}
{256}{}{Dnes bude noc s velkým N!}
{257}{}{Tuhle noc si budu urèitì pamatovat.}
{258}{}{Neøíkej mi, že dostali strach.}
{259}{}{Doufám, že se ti sráèi ukážou.}

# 6. TRAP NOSHOW
{260}{}{Já vìdìl, že se ti srabi neukážou.}
{261}{}{Mìli bysme jim natrhnout prdel už jen proto, že s námi chtìli bojovat.}
{262}{}{Kdyby se bývali ukázali, rozprášili bysme je.}
{263}{}{Zvládnul bych je sám.}
{264}{}{Tyler a já bysme jim natrhli prdel.}