{100}{}{Vidíš velkého, primitivně vypadajícího muže.}
{101}{}{Vidíš štíhlou primitivní ženu.}
{200}{}{Vidíš podivně vyhlížejícího muže.}
{201}{}{Vidíš otrhaného muže.}
{202}{}{Vidíš muže v otrhaných šatech.}
{210}{}{Vidíš velmi špinavou ženu.}
{211}{}{Vidíš pěkně špinavou ženu.}
{212}{}{Vidíš vychrtlou ženu.}
{270}{}{Oni nenajít já.}
{271}{}{Muset schovat. Muset schovat.}
{272}{}{Proč oni chtít zranit?}
{273}{}{Já bát.}
{274}{}{Já nebojovat.}
{275}{}{Já chtít žít.}
{276}{}{Nezranit moje rodina.}
{280}{}{A do prdele!}
{281}{}{Proč to dělají?}
{282}{}{Co bude s mojí rodinou?}
{283}{}{Nechci zemřít.}
{284}{}{Nechci být otrok.}
{285}{}{Zasloužím si něco lepšího než je tohle.}
{300}{}{Ahhh!}
{301}{}{Nezabít! Nezabít!}
{302}{}{Přestat!}
{303}{}{Pomóóóóc!}
{304}{}{Běžet!}
{305}{}{Nechat být!}
{306}{}{Nezranit!}
{307}{}{Já nezranit tebe!}
{308}{}{Já nebojovat!}
{350}{}{Zachraň se kdo můžeš!}
{351}{}{Nenechte se od nich chytit!}
{352}{}{Otrokáři! Utíkejte!}
{353}{}{Pomozte nám někdo! Prosím!}
{354}{}{Utíkej, Marty!}
{355}{}{Ahhh!}
{356}{}{Zastavte to šílenství!}
{357}{}{Nic jsme neudělali! Nechte nás na pokoji!}
{358}{}{Tohle tetování znám!}
{359}{}{Ne, prosím!}
{360}{}{Prosím, nezabíjejte mě!}
{361}{}{Vzdávám se, nezabíjejte mě!}
{362}{}{Prosím, já nechci zemřít!}
{363}{}{Vy jste otrokáři, že jo? Ach Bože.}
