{100}{}{Vidíš prostitutku.}
{150}{}{Je to naprosto obyèejná prostitutka.}
{152}{}{[MLUVIT]}
{153}{}{Hej, já nedìlám enskı!}
{154}{}{Nevadí.}
{155}{}{Omlouvám se.}
{156}{}{Mami?}
{157}{}{Hele, chlapeèku, bude to draší, jestli chceš mít i obecenstvo.}
{158}{}{Oni jdou tam, kam jdu já.}
{159}{}{Chci je mít s sebou.}
{160}{}{Ještì se vrátím.}
{161}{}{Mami?}
{162}{}{Ach, zlato, celı ivot na tebe èekám. Kde jsi byl?}
{163}{}{Pøímo tady, zlato.}
{164}{}{Za kolik, sestro?}
{165}{}{Ach jo, musím jít. Nashle.}
{166}{}{Vííí!}
{167}{}{Mám je ráda velkı a tupı.}
{168}{}{To jsem pøesnì já!}
{169}{}{Jó!}
{170}{}{Ach. Ne. Nashle.}
{171}{}{Ty jseš ale velkej chlap!}
{172}{}{To máš pøece ráda.}
{173}{}{Ano, madam.}
{174}{}{Musím jít.}
{176}{}{Dobøe!}
{177}{}{Ne. Nashle.}
{178}{}{Ty se vrátíš.}
{179}{}{Uvidíme.}
{180}{}{Eh, ne.}
{181}{}{[Slintat]}
{182}{}{Nemáš dost penìz. Ztra se, zlato.}
{183}{}{Ještì se vrátím.}
{184}{}{Za to mi nestojíš, brouku.}
{185}{}{Ehh!}
{186}{}{Byl jsi ohromnej!}
{187}{}{Jako vdycky, zlato.}
{188}{}{Nevadí.}
{189}{}{Ty taky.}
{190}{}{Já ochromenej!}
{191}{}{Byl jsi skvìlej!}
{192}{}{Díky. Ty taky.}
{193}{}{Hmm.}
{194}{}{Jooo.}
{195}{}{Skvìlı!}
{196}{}{Fajn, hotovo. Nashle.}
{197}{}{That's it?}
{198}{}{Dobøe. Nashle.}
{199}{}{Bylo to dobrı.}
{200}{}{Pápá.}
{201}{}{Za tohle mi platí málo.}
{202}{}{Tak tohle teda za ty prachy vùbec nestálo.}
{203}{}{Budu ti chybìt.}
{204}{}{Nashle.}
{205}{}{Ztratil ses?}
{206}{}{Zastav se zase nìkdy.}
{207}{}{Dobøe. Nashle.}
{208}{}{Jo, dobøe.}
{209}{}{Jehee!}
{210}{}{Zatím.}
{211}{}{Nashle.}
{212}{}{Pápá.}
{213}{}{Stojí to $}
{214}{}{ za èíslo. Nejdøív zapla.}
{215}{}{Pojï za mnou.}
{216}{}{Já èekám.}
{217}{}{Nehodlám v tıhle studené díøe stát celej den.}
{218}{}{Mohl by sis pospíšit?}
{219}{}{Poslední šance.}
{220}{}{Fajn. U nehodlám èekat ani vteøinu.}
{221}{}{Tak u pojï.}
{222}{}{Jseš vzrušenej?}
{223}{}{Pojï za mnou.}
{224}{}{Hej, kámo, dej ty pracky pryè.}
{225}{}{Ruce pryè! Nejsem ádná hraèka, se kterou si mùeš hrát.}
{230}{}{Ehhh...? To bylo tvoje poprvé?}
