{100}{}{Vidíš velkého, primitivnì vypadajícího mue.}
{125}{}{Má šrámy a modøiny po celém tìle.}
{150}{}{Vidíš slabou, primitivní enu.}
{175}{}{Vypadá, jako by ji nìkdo zmlátil.}
{200}{}{Vidíš otrhaného mue.}
{225}{}{Nevypadá pøíliš zdravì.}
{250}{}{Vidíš zajatou enu.}
{275}{}{Je špinavá a vypadá podvyivenì.}
{300}{}{Neubliovat mi, prosím!}
{301}{}{My budeme jít?}
{302}{}{Ty nemluvit. My muset bìet.}
{303}{}{Díky za pomoc.}
{304}{}{Dìkuji mnohokrát!}
{305}{}{Jsi svatı.}
{306}{}{Co dìláš? Mìli bysme jít.}
{307}{}{Pomoz nám utéct, prosím.}
{320}{}{Ty zlı!}
{321}{}{My nemluvit s ty.}
{322}{}{My utéct.}
{323}{}{Ty nezastavit nás.}
{324}{}{Ty otrokáø!}
{325}{}{Proè to vy otrokáøi dìláte?}
{326}{}{Jak mùete dìlat pro takové lidi?}
{327}{}{Nejsme primitivové!}
{328}{}{Nemáte ádné svìdomí?}
{329}{}{Co s námi bude?}
{330}{}{Co jsme udìlali špatnì?}
{331}{}{Nech nás o samotì, otrokáøi!}
{332}{}{Neubliuj mi!}
{333}{}{Jdìte ode mì!}
{350}{}{Kdo ty?}
{351}{}{Ty ne otrokáø.}
{352}{}{Ty neublíit?}
{353}{}{Pøítel?}
{354}{}{Ty pomáhat?}
{355}{}{Co s námi bude?}
{356}{}{Taky tì chytli?}
{357}{}{Nejsme primitivové!}
{358}{}{Co si o sobì ti lidi myslí?}
{359}{}{Pomoz nám prosím!}
{360}{}{Dostaòte mì odsud.}
{380}{}{Ty nezastavit my tady!}
{381}{}{To nesprávné!}
{382}{}{My ne zlı!}
{383}{}{Ty pomáhat my?}
{384}{}{Ty dát svobodu my!}
{385}{}{My nemít to rád.}
{386}{}{Zlı místo.}
{387}{}{Proè tohle zlí lidi dìlají?}
{388}{}{My nebıt otroci!}
{389}{}{My nedìlat nic zlı.}
{390}{}{My jít!}
{391}{}{Co se dít?}
{392}{}{Velkı rámus?}
{393}{}{Kdo bojovat?}
{394}{}{Co se stát?}
{395}{}{Nìco se stát?}
{396}{}{Pomozte nám nìkdo!}
{397}{}{Hej! Slyší mì nìkdo?}
{398}{}{Tohle je špatné!}
{399}{}{Nic jsme neudìlali!}
{400}{}{Pus nás odsud!}
{401}{}{Dostaòte nás nìkdo odsud!}
{402}{}{Co jsme udìlali?}
{403}{}{Neudìlali jsme nic.}
{404}{}{Tohle si nezaslouíme.}
{405}{}{Ti bastardi!}
{406}{}{Pomozte nám!}
{407}{}{Puste mì!}
{408}{}{Nejsme otroci!}
{409}{}{Nejsme primitivové! Pus nás odsud!}
{410}{}{Co se dìje?}
{411}{}{Je tady nìkdo, kdo nás zachrání?}
{412}{}{Hej, tady!}
{413}{}{Pomoc! Neopouštìj nás!}
{414}{}{Co to bylo za støelbu?}
{415}{}{Co se dìje?}
{420}{}{Ahhh!}
{421}{}{Ug!}
{422}{}{Nezastavuj se!}
{423}{}{Ano!}
{424}{}{Utíkám odsud, jak jen daleko to pùjde.}
{425}{}{Nezastavuj se!}
{426}{}{Svoboda! Koneènì svoboda!}
{440}{}{Co bıt rámus vıstøel? Co ty chtít?}
{441}{}{Hej! Co to bylo za støelbu? Jsou otrokáøi mrtví?}
{442}{}{Hej! Co to bylo za støelbu? Co se dìje?}
{443}{}{To byla Metzgerova poslední píseò.}
{444}{}{Ale nic. Jenom vás kontroluju. Sbohem.}
{445}{}{Jste volní, mùete jít. Metzger je mrtvej.}
{446}{}{Vy svoboda.}
{447}{}{ pøítel. On zabít Mezgur. Teï vy jít.}
{448}{}{ pøítelka. Ona zabít Mezgur. Teï vy jít.}
{460}{}{On mrtvı? Já dìkovat ty! My jít rychle pryè. Ahoj. Ty pøítel.}
{461}{}{Coe? Metzger je mrtvej? Oh, mockrát dìkujeme! Mìli bychom radìji zmizet, ne se objeví ostatní. Ještì jednou dìkujeme.}
{462}{}{Není zaè. Teï odsud radìji zmizte.}
{463}{}{Dejte na sebe pozor.}
{464}{}{Není zaè.}
{470}{}{Poèkat, ještì nìco. Hledám jednu konkrétní enu a nikde ji tu nevidím. Nevíte, kde drí ostatní otroky?}
{471}{}{Velkı tábor blízko tady. (Divoch ukazuje na jihozápad) Dva noc odsud.}
{472}{}{Dva dny cesty na jihozápad odtud leí tábor. Tam jsem byl nejdøív.}
{473}{}{Díky. Teï odsud radìji zmizte.}
{474}{}{Díky ti. Dejte na sebe pozor.}
{475}{}{Poèkat. Já hledat nìkoho. Kde víc otrok?}
{476}{}{Dìkovat. Teï ty jít!}
{480}{}{Co ty chtít?}
{481}{}{Co chceš?}
{482}{}{Ale nic.}
{500}{}{He?}
{501}{}{Zapomeò na to. Jste volní, mùete jít. Metzger je mrtvı.}
{510}{}{Co? Volní? Zlı mu pryè? My teï jít! Dìkovat ti. Ty pøítel! Ahoj!}
{511}{}{Volní? Coe? Všechny si je zabil? Mnohokrát ti dìkujeme! Mìli bysme radìji zmizet, dokud mùeme. Ještì jednou dìkujeme, jsi svatej!}
{520}{}{K èertu s tebou!}
{521}{}{Sma se v pekle!}
{522}{}{Za to zaplatíš.}
{523}{}{Proè na mnì poøád mluvíš?}
{524}{}{Nech mì bıt.}
{525}{}{Nechci s vámi mluvit.}
{526}{}{Jak si mohl?!}
{527}{}{U tì nechci nikdy vidìt.}
{528}{}{Tímhle se nic nezmìní.}
{529}{}{Pokud ti to nebude vadit, pùjdu si svoji cestou.}
{530}{}{Nech mì odejít, prosím.}
{531}{}{Nech mì odejít.}
{532}{}{Poøád s tebou nechci mluvit.}
{533}{}{Nech mì bıt.}
{534}{}{Ani náhodou.}
{535}{}{Myslíš, e je to takhle lepší?}
{600}{}{My jít?}
{601}{}{Ty neublíit?}
{602}{}{Jít!}
{603}{}{Domù!}
{604}{}{Volnı?}
{605}{}{He?}
{606}{}{Coe?}
{607}{}{Øekl jsi "volnı"?}
{608}{}{Mizím odsud!}
{609}{}{Poïme!}
{610}{}{Hej všichni! Jsme volní!}
{611}{}{Jooooooooo!}
{700}{}{Osvobodil jsi otroky ze zajetí.}
