{100}{}{Vidíš informaèní tabuli.}
{150}{}{Vypadá to, že je na této informaèní tabuli nìkolik zpráv.}
{200}{}{Tato informaèní tabule patøí Rebeèinu Kasíno Baru, kde seženete nejlepší drinky v okolí. }
{201}{}{Tato informaèní tabule patøí Rebeèinu Kasíno Baru...}
{202}{}{(Nìkdo tu na okraj téhle zprávy nìco naèmáral.)}
{203}{}{(Všimneš si, že byla èást této zprávy odtržena.)}
{204}{}{Otrokáøský Cech}
{205}{}{Bary & Herny}
{206}{}{Jídlo}
{207}{}{Obchody}
{225}{}{Otrokáøský Cech je nejlepší a jediný dodavatel otrokù v pustinách.}
{250}{}{Pokud chcete práci nebo obchodovat s otroky, navštivte šéfa otrokáøù Metzgera.}
{275}{}{Otrokáøský Cech je na východní stranì mìsta za Rebeèiným kasínem a Frankieho barem.}
{300}{}{Kvùli zvýšené poptávce momentálnì neprodáváme otroky široké veøejnosti.}
{325}{}{(Jsou tady vypsaná dvì místa.)}
{350}{}{Rebeèin Kasíno Bar nabízí hazardní hry a vynikající nápoje.}
{375}{}{Sídlíme východnì odtud. Jsme první budova po levé stranì, když vejdete do mìsta. Urèitì nás pøijïte navštívit!}
{400}{}{Rebeka je kurfa kerá øedí chlast! Je to potvodnice a lháøka! (Písmo je skoro neèitelné.)}
{401}{}{(Zpráva, která byla na tomto místì, byla peèlivì odtržena.)}
{425}{}{Slova slova... eh... slova... Bar... slova... v Denu.}
{426}{}{Je to pro tebe natolik matoucí, až tì z toho zaène bolet hlava.}
{450}{}{Frankie provozuje bar, hospodu a 'zábavní' podnik ve východní èásti mìsta.}
{475}{}{Mámina restaurace je jediná v Denu. Je ve východní èásti mìsta, kousek na jih od Otrokáøského Cechu.}
{500}{}{(Vypadá to, že se to nìkdo snažil zapálit. Nedokážeš rozluštit ani jednu zprávu.)}
{525}{}{(Jsou tu tøi zprávy.)}
{550}{}{Tubby prodává všechno možné, ale hlavnì drogy a støelivo.}
{575}{}{Tubby sídlí na západ od této informaèní tabule. Je to první budova po pravé stranì když vejdeš do mìsta.}
{600}{}{Flick prodává rùzné vìci ve své 'kanceláøi' v obytné budovì na jih odsud a pøímo pod Rebeèiným Kasíno Barem.}
{625}{}{Smitty je místní mechanik. Obèas má pár vìcí na prodej.}
{650}{}{Smitty sídlí na smetišti v jihozápadní èásti mìsta.}
{1000}{}{Pokraèovat.}
{1010}{}{Kde nás najdete:}
{1020}{}{Konec.}
{1030}{}{Flickùv obchod}
{1040}{}{Frankieho Bar}
{1050}{}{Rebeèin Kasíno Bar}
{1060}{}{Zpìt na hlavní stranu}
{1070}{}{Smitty}
{1080}{}{Speciální poznámka:}
{1090}{}{Tubbyho obchod}
