{100}{}{Vidíš MIBoba Fe88.}
{101}{}{Vidíš zdatného a nemilosrdného lovce odměn.}
{110}{}{Vidíš drsného a nemilosrdného lovce odměn. Nevypadá, že by toho moc namluvil. Pomohl s novými skripty a nápady. A se zabíjením lidí.}
{200}{}{Vidíš Hivana Zola.}
{201}{}{Špinavý, ale pohledný zloděj.}
{210}{}{Mladej, přeletěl jsem z jednoho koutu galaxie na druhej a viděl jsem hodně divnejch věcí, ale ještě jsem nikdy neviděl *nic*, co by mě donutilo uvěřit, že všechno ovládá nějaká všemocná Síla. Žádný tajuplný energetický pole neřídí *můj* osud. Je to všechno jen spousta jednoduchejch fíglů a nesmyslů. Sentimentální náboženství a starobylý zbraně se nedaj srovnávat s pořádným blasterem u pasu. Poznám, když to někdo umí s bouchačkou, takže si tohle vem a věř mi: až na tebe bude vypsaná odměna, bude se ti hodit. (Podává ti blaster.)}
{211}{}{Moje skutečný jméno je Ivan Zaharath.}
{212}{}{Přeložil jsem Restoration Project do polštiny ve prospěch velký a mocný Polský republiky... chci říct Rebelský Aliance.}
{213}{}{Jen se směj, chlupáči.}
{214}{}{Sentimentální náboženství a starobylý zbraně se nedaj srovnávat s pořádným blasterem u pasu, mladej.}
{215}{}{Komu říkáš 'špinavej'!?}
{300}{}{Vidíš Contie-bacca.}
{301}{}{Vypadá jako chodící koberec.}
{310}{}{Roow rooo arrrrr rooow.}
{311}{}{Rrrrrrrrrrrrr... písk!}
{312}{}{Nowrrrrragh.}
{313}{}{Yawrrrk!}
{314}{}{Roow rooo Nowrrrrragh!}
{315}{}{Říká, že je Continuum a že udělal novou a unikátní grafiku.}
{316}{}{Říká, že ji udělal pomocí 3D modelování. Víš, on je docela chytrý. Na člověka.}
{317}{}{Říká, že nemluví česky, ačkoliv to zní trochu jako dětské žvatlání.}
{318}{}{Říká, že to není kuše, je to blaster. A ne, nemůžeš ho mít.}
{319}{}{Říká, že mu můžeš poděkovat za to, že dostal ponorku zpět do hry.}
{400}{}{Vidíš Dareka Vadera.}
{401}{}{Tenhle týpek vypadá pěkně drsně a zdá se, že je to spíš stroj než člověk.}
{410}{}{Já jsem Darek. Pomohl jsem Obi-Wan-Killapovi zodpovědět milión začátečnických otázek.}
{411}{}{Připoj se ke mně! Společně můžeme vládnout galaxii!}
{412}{}{Víš, že MĚ velký Obi-Wan-Killap požádal o pomoc?}
{413}{}{Neříkej nic Obi-Wan-Killapovi, ale myslím, že začíná šílet.}
{414}{}{Pomohl jsem zlikvidovat několik ošklivých much. Můžeš mi poděkovat později.}
{500}{}{Vidíš Jotisze Hutta.}
{501}{}{Tenhle chlápek je obrovský, tlustý a zelený.}
{510}{}{Já jsem Jotisz Hutt. Možná vypadám jako velký, tlustý, zelený slimák, ale ve skutečnosti jsem to byl já, kdo pomohl vytvořit tuhle krásnou novou zbroj, kterou tvůj kámoš Sulik právě nosí. Byla vytvořena Yosanem12 a mnou. Já vím! Těmahle zavalitýma rukama!}
{511}{}{Já jsem Jotisz Hutt. Možná vypadám jako velký, tlustý, zelený slimák, ale ve skutečnosti jsem to byl já, kdo pomohl vytvořit tuhle krásnou novou zbroj, kterou tvůj kámoš... hej, kde je Sulik? Měl bys ho najít a podívat se jak v ní vypadá. Jeho zbroj byla vytvořena Yosanem12 a mnou. Já vím! Těmahle zavalitýma rukama!}
{512}{}{*písk* Já jsem velký, tlustý, zelený slimák...}
{513}{}{Pokud sis toho ještě nevšiml, je až podezřele jednoduché mě uškrtit.}
{514}{}{Kde jsem nechal tu Leiu...?}
{600}{}{Vidíš R2Qwerty.}
{601}{}{Horlivý malý robot. Bliká a pípá.}
{610}{}{Píp píp!}
{611}{}{Rrrrrr píp rrrrwow!}
{612}{}{*vzrušené bliká a poskakuje*}
{613}{}{Kuše! Taktika! Kuše!}
{700}{}{Vidíš Chris3ParksO.}
{701}{}{Zlatý zářivý humanoidní robot. Vypadá překvapeně.}
{710}{}{Ahoj, já jsem Chris3ParksO, specialista na lidsko-robotické vztahy. Jsem velice zběhlý ve více než 3 miliónech programovacích jazyků.}
{711}{}{Pomohl jsem položit základní kámen pro Kmen Umbra a EPA.}
{712}{}{Toto je R2QWERTY - můj věrný společník. On vytvořil nové tvory a grafiku.}
{800}{}{Vidíš Yosan12.}
{801}{}{Malý zelený mužíček. Vypadá STAŘE.}
{810}{}{Yosan12 já jsem. NPC mód brnění já vytvořil. Xwing z bažiny já také vyzdvihl. Velmi podivným způsobem já také mluvím. Těžké je rozumět, hmmm? Ha ha ha! Také novou odstřelovací pušku, Wakizashi a animace světelného meče já vytvořil.}
{811}{}{Pamatuj - vztek, strach, nenávist, temná strana jsou.}
{812}{}{Až zemřu já, malý, mlhavý, zářící duch stane se ze mě.}
{813}{}{Kdysi loutka s moudrostí a charakterem byl jsem já. Nyní prázdná CGI postavička pro děti stala se ze mě.}
{814}{}{Hlupák JarJar Binks je.}
{900}{}{Vidíš Obi-Wan-Killapa.}
{901}{}{Vypadá jako starý milý muž. Je na něm něco trochu medvědího.}
{910}{}{Ahoj, }
{911}{}{. Vidím, že ti to docela šlo. Já jsem Obi-Wan-Killap - upravuju Fallout do podoby, ve které měl být už od samého počátku.}
{912}{}{Páni. Díky moc, pane Killap. Jak jsi to dokázal?}
{913}{}{Co to k čertu je ten Fallout?}
{914}{}{Aha a kdo jsou prosím tě ti ostatní lidé?}
{920}{}{Já jsem Mistr Programátor, znalý způsobům Zdrojáku. Je to energetické pole vytvořené všemi digitálními věcmi. Obklopuje nás a proniká skrz nás. Spojuje galaxii dohromady. Ty, já, strom, kámen. Jsme jen obyčejné bytosti... ale ne tato primitivní hmota (*šťouchne do tebe*). Naučil jsem se používat tuto sílu skrze roky zírání do obrazovky počítače.}
{921}{}{Páni. Náš šaman vždycky říkal, že náš svět není jenom o tom, co můžu vidět, slyšet, dotýkat se, ochutnat a cítit. Můžeš mě naučit používat sílu Zdrojáku?}
{922}{}{Myslím, že už jsem slyšel tolik náboženskejch blábolů, že mi to vydrží na další nukleární zimu. Upřímně mám raději plazmovou pistoli po svém boku.}
{923}{}{No super, další praštěnej náboženskej pošuk. Padám odsud.}
{930}{}{Jsi ve světě Falloutu. Já jsem ho stvořil, respektive upravil tak, jak měl původně vypadat. Víš, ještě donedávna byl tento svět v chaosu. Cestovatelé, kteří sem přišli, byli příliš často zabíjeni obrovským množstvím much, které se potulovaly pustinou a náhodně kazily uložené pozice. Bohům tohoto světa to bylo jedno. Ale pak jsme přišli já a moji přátelé a díky moci Zdrojáku jsme pustinu vyčistili. Dalo by se říct, že jsem zachránce. Mnoho lidí mě má za boha - Bear Dude.}
{931}{}{Chápu. No... vlastně, měl jsem dojem, že hlavním hrdinou tohohle příběhu mám být já. Běhám okolo, sbírám hovadiny, zabíjím lidi, vždyť víš, jako hrdina. Jo a občas s nimi i mluvím, ale tahle část je občas otravná. Jen to tak proklikám, abych se dostal k těm zábavnějším věcem.}
{932}{}{Výborná práce, pane Killap. Velmi oceňuju všechen ten čas a dřinu, kterou jsi věnoval čištěním pustiny. Pokud je to pravda, tak bys měl vědět, že já jsem taky hrdina. Popravdě, já sám jsem taky pár much zlikvidoval.}
{935}{}{A my jsme vděční za to, že se ti podařilo zničit Enklávu. Tady jsi skutečný hrdina.}
{936}{}{Někdo to udělat musel.}
{937}{}{Takže, jak přesně jsi vyčistil tenhle svět?}
{938}{}{Kdo jsou prosím tě ti ostatní lidé?}
{940}{}{To jsou moji společníci. Pomohli mi tento svět vylepšit: MIBoba Fe88, Hivan Zolo, Contie-bacca, Darek Vader, Jotisz Hutt, R2Qwerty, Chris3ParksO, Yosan12, Emperor Timeslip, Luke Skynet, Mon-Morticia, Kanhef, HawkEyE, Adam Dravean, Mr. Wolna, encinodude, Minigun Jim, Bofast, Pixote, Mash, Mikael Grizzly, x'il, Per a Masses. Ti všichni byli součástí velikého projektu při obnově tohoto světa, který měl za úkol vymýtit všechny mouchy. Jediná dobrá moucha je mrtvá moucha.}
{941}{}{Hmm. Ty jména mi zní nějak povědomě... myslím, že si s nimi půjdu promluvit.}
{950}{}{To vskutku můžu. Musíš se naučit používat své pocity: opusť svoje vědomí. Vypni monitor. Zavři oči a VNÍMEJ energii Zdrojáku protékající skrz myš... (Následuješ jeho instrukce.)}
{951}{}{Nemáš dostatek zkušeností pro započetí tréninku. Vrať se, až budeš ovládat alespoň nějaké základy programování, mladý padawane.}
{960}{}{Jak si přeješ, mladý }
{961}{}{. Ale než půjdeš svojí cestou, tak si toto zapamatuj: Mnoho pravd, kterých se držíme, hluboce závisí na našem vlastním úhlu pohledu. A teď odejdi a nechť tě provází Zdroják.}
{962}{}{. Skutky na tvé cestě prokázaly tvé dobro, laskavost a upřímnost. Vezmi si toto na pomoc v boji proti Temné Straně - je to světelný meč tvých předků. Toto je zbraň Rytířů Java. Není tak neohrabaný a nepřesný jako blaster. Elegantní zbraň pro civilizovanější dobu. A ačkoliv tě může lákat použít ho k svévolnému půlení lídí jen tak pro zábavu, měl bys ho použít pouze ve jménu dobra. Hodně štěstí a nechť tě provází Zdroják, příteli.}
{963}{}{Cože?! Můj předek, Zakladatel, měl taky takový meč?! Nevzpomínám si, že bych něco takového našel ve Falloutu 1! *jdeš to zkontrolovat*}
{964}{}{Díky, pane Bear Dude. Za všechno. Nechť tě taky provází Zdroják.}
{1000}{}{Vidíš Imperátorku Timeslip.}
{1001}{}{Vidíš zlověstně vypadající shrbenou postavu zahalenou v plášti.}
{1010}{}{Já jsem Imperátorka Timeslip. Jsem Mistryně Programování, znalá způsobům Zdrojáku. Byla jsem to já, kdo dovolil Obi-Wan-Killapovým špehům ukradnout moje opravy v herním enginu, které zvyšují stabilitu tohoto světa a opravují SMĚŠNÉ A HLOUPÉ MOUCHY zanechané původními tvůrci.}
{1011}{}{Vskutku, můj mistře. Pověz mi o sobě, ó veliká.}
{1012}{}{Páni. Naháníš mi hrůzu. A tvoje tvář vypadá ohavně.}
{1013}{}{To je fajn. Musím jít.}
{1020}{}{Pouhou myšlenkou dokážu natvrdo změnit zakódované věci do Zdrojáku a tím určit osud celých vesmírů! Celá legie mých nejlepších oprav všelijakých much na tebe stále ještě čeká. Já jsem paní Temné Strany Zdrojáku.}
{1021}{}{Ticho! Roky práce v temnotě mohly pokřivit můj vzhled, ale v této mysli je ukryta síla boha! S pomocí Zdrojáku vytvářím počasí ovládající celé světy a vylepšuji to, co již nemůže být vylepšeno! Byla jsem to já, kdo umožnil Zlé Beth ovládnout svět RPG díky mým modifikacím. Vše, co se stalo, se stalo podle MÝCH představ.}
{1022}{}{Sauce? What kind of sauce? Are you saying cooking is the key to controlling the universe? Whatever you say, chef.}
{1023}{}{Jo, jo. Jak myslíš. Myslím, že půjdu pryč.}
{1024}{}{Eh, tak jo. To je skvělé. No, už musím jít... ehm... zalít kytky...}
{1030}{}{Nevychovaný hlupáku. Tvá arogance je zároveň i tvoje slabina a moje víra v tvé přátele je... noo... moje. *vypadá zmateně* Kliď se mi z očí!}
{1040}{}{Počkej! Odejdeš POKUD a AŽ tak rozhodnu. Pokud to náhodou nevíš, tvá krutost při plnění poslání byla opravdu mimořádná. Tvá zloba z tebe udělala mocného člověka a tvoje postava se vyvinula přesně podle mých přání. Zloba, strach, nenávist... to jsou známky temné strany. Nyní se staneš mým učedníkem a naplníš své místo PO MÉM BOKU!}
{1041}{}{Jak si přeješ, můj mistře. Čekám na tvé rozkazy.}
{1042}{}{Nemám zájem. Nashle.}
{1045}{}{Odejdi a vykonávej zkázu mé dítě.}
{1046}{}{Zmiz!}
{1050}{}{Výýýýýborně. Vezmi si tedy tuto Java zbraň. Používej ji. Zabíjej bezmyšlenkovitě. POUŽIJ SVOJE AGRESIVNÍ POCITY, DÍTĚ! (Podává ti červený světelný meč.)}
{1051}{}{Takže... v podstatě mám pokračovat v tom, co jsem dělal doteď. Žádný problém. Nashle!}
{1052}{}{Nezklamu tě, můj mistře.}
{1053}{}{Zabít všechny? Myslíš... i děti?}
{1060}{}{PŘEDEVŠÍM děti.}
{1100}{}{Vidíš Luka Skyneta.}
{1101}{}{Zahalená postava, která vypadá sebejistě.}
{1110}{}{Já jsem Luke Skynet. Jsem tu, abych tě zachránil.}
{1111}{}{Zachránil?}
{1112}{}{Vypadám snad jako nějaká princezna? Co myslíš tím 'zachránit'?}
{1113}{}{Hmm, myslím, že jsi to spíš ty, kdo potřebuje zachránit... před svojí vlastní filmovou kariérou. Nashle.}
{1120}{}{Ano, jsem tady, abych tě zachránil. Položil jsem základy toho, co lze spatřit v Opatství. Tam najdeš spásu, tam najdeš světlo!}
{1121}{}{Vlastně už jsem tam byl. Podařilo se mi 'zachránit' spoustu věcí ještě před tím, než by byly nadobro ztracené ve všech těch šuplících a krabicích.}
{1122}{}{Ámen, bratře. Děkuju ti za pomoc při stvoření tohohle místa útěchy a míru. Zrovna když budu potřebovat nechat odpočinout své radioaktivní nohy a hledat spirituální oživení.}
{1123}{}{Pamatuju si to místo. Žádný schopný šaman a žádné pořádné byliny. Nevím, čí představa o spirituálním místě to byla, ale moje teda ne.}
{1124}{}{Opravdu? A kde leží to místo, které mě může zachránit?}
{1125}{}{Blázen! Pápá!}
{1130}{}{Musíš se tam opět vrátit. Je to bezpečný úkryt před nelítostnou pustinou.}
{1131}{}{Už jdu, pane Skynet. Díky za všechno. Sbohem.}
{1132}{}{No, myslím, že bys tam měl jít TY, Skybraine, a rovnou tam i zůstat. Já odsud mizím. Podivíne.}
{1135}{}{Tady. (Ukazuje na tvém Pip-Boyi.) Musíš tam jít hned teď.}
{1138}{}{Opatství je místo osamění.}
{1139}{}{Dávej si venku pozor.}
{1200}{}{Vidíš Mon-Morticii.}
{1201}{}{Velmi diplomaticky vyhlížející dáma.}
{1210}{}{Pomohla jsem s psaním návodu, který usnadní všem nováčkům průchod tímto vylepšeným světem.}
{1211}{}{Do prdele! Jsem na špatné straně! Nikdy jsem si nebyla příliš jistá na čí straně mám být.}
{1212}{}{Nemám v tomhle velký zadek?}
{1213}{}{Imperátorka Timeslip udělala fatální chybu a nastal čas na náš útok. *mrk*}
{1300}{}{Vidíš Kanhefa.}
{1301}{}{TENHLE vypadá jako skvělý chlapík.}
{1310}{}{Já jsem v podstatě centrum podpory No Mutants Allowed.}
{1311}{}{Nemám s těmito podivíny nic společného.}
{1312}{}{Sakra. Proč má číslo 23 vždycky zpoždění?}
{1313}{}{Pokud to náhodou nevíš, tak jsem vcelku všestranně použitelný chlap.}
{1400}{}{Vidíš HawkEyE.}
{1401}{}{Třpytivý drahokam nenávisti.}
{1410}{}{Bonjour. Je suis Hawk-Eye. J'ai translate le version Francais. }
{1411}{}{Já jsem Hawk-EyE. Vedl jsem překlad do francouzštiny. Vive la France!!}
{1412}{}{Rád jím... lahodnéééé malé rybičky!}
{1413}{}{Kromě nás zbabělců tu už nikdo není.}
{1500}{}{Vidíš Adama Draveana.}
{1501}{}{Přikyvuje tvým směrem.}
{1510}{}{Já jsem Mr. Wolna. Vedl jsem překlad do němčiny.}
{1511}{}{(Prozím, dej mi facku!)}
{1512}{}{Dobrá práce, hoši! Jen tak dál!}
{1513}{}{Podívej! Zlatý Orel!}
{1514}{}{Ich komme aus Deutschland!}
{1600}{}{Vidíš Pana Wolnu.}
{1601}{}{Tento muž je opravdu nadšený...}
{1610}{}{(Sundá si helmu a odhrne svůj rudý plášť na stranu. Před tvými zraky se zjeví pohledný muž s vyholenou hlavou a koženou bundou. Vyzařuje ze sebe charisma a velkolepost.) Nazdar cizinče, jmenuju se Adam. Jak to jde?}
{1611}{}{Docela dobře. Sice to bylo dost složité, ale nakonec se mi to podařilo dohrát.}
{1612}{}{Na tohle nemám čas. Nashle.}
{1620}{}{To rád slyším. (Rozhlédne se kolem a poté svraští čelo.) Kdepak je Dex? Strávil jsem spoustu času psaním dialogu toho frajera a ty ho ani nepoužíváš? (Hluboce povzdechne a zakroutí hlavou.)}
{1621}{}{Dex? Ty jsi napsal jeho dialog? O čem to mluvíš?}
{1630}{}{To rád slyším. Omluv mě na moment. (Přijde k Dexovi, plácne si s ním a poté se k tobě vrátí.) Jsem rád, že jste to dali s mým kámošem Dexem dohromady. Víš, že jsem strávil spoustu času psaním jeho dialogu.}
{1631}{}{Odkud znáš Dexe? A ty jsi "napsal jeho dialog?" O čem to mluvíš?}
{1640}{}{Hele, s tím si nelam hlavu. Ale pokud se někdy rozhodneš pustit na další epickou výpravu, tak se určitě zastav v EPA. Dá se tam dělat hafo věcí a když to dobře zahraješ, tak tam možná najdeš i novýho společníka. (Podívá se na tebe a zeširoka se usměje.) Jo, ty jsi přesně Dexův typ, takže si budete určitě rozumět.}
{1641}{}{Díky. Budu na to myslet.}
{1650}{}{Hele, s tím si nelam hlavu. Ale pokud se někdy rozhodneš pustit na další epickou výpravu, tak se určitě zastav v EPA. Dá se tam dělat hafo věcí a když to dobře zahraješ, tak tam možná najdeš i novýho společníka. (Podívá se na tebe a zeširoka se usměje.) Ale jestli chceš být s Dexem kamarád, tak asi budeš muset změnit svůj přístup. Nemá moc v lásce zarputilé dobráky.}
{1651}{}{Díky. Budu na to myslet.}
{1660}{}{(Pokyvuje a dívá se do dálky.) Víš, Dex nebyl mým jediným příspěvkem. Taky jsem pomohl Bear Dudeovi vylepšit tento svět tím, že jsem sloužil jako poradce, tester, a strážce principů a původního obsahu. Ale především jsem měl za úkol vylepšit kvalitativní úroveň nově přidané mluvené řeči. Byl to sakra tvrdý oříšek, ale musím říct, že se to kurva povedlo. (Podívá se zpět na tebe a ušklíbne se.)}
{1661}{}{To je jedno. Už mě unavuje tohle poslouchat. Nashle.}
{1662}{}{To bylo od tebe šlechetné. Odvedl jsi znamenitou práci. Dávej na sebe pozor. Nashle.}
{1670}{}{*Prohlédne si tvé společníky* Vypadáš dobře, Dexi.}
{1671}{}{Dávej pozor na Dexe, jasný? Nerad bych, aby se dostal do maléru. Koneckonců, to já ho stvořil.}
{1672}{}{Není třeba mi děkovat za pročištění dialogů.}
{1673}{}{Hej, kde je Dex? Napsal jsem jeho dialog, víš.}
{1700}{}{Vidíš encinoduda.}
{1701}{}{Vypadá jako dobrák.}
{1710}{}{*Prohlédne si tvé společníky* Vypadáš dobře, Kitsune.}
{1711}{}{Dávej pozor na Kitsune, rozumíš? Nechci, aby se dostala do maléru. To já ji stvořil, víš.}
{1712}{}{Pomohl jsem s ponorkou, víš.}
{1713}{}{Hele, kde je Kitsune? Napsal jsem její dialog, víš.}
{1714}{}{Pomohl jsem s ponorkou, víš.}
{1800}{}{Vidíš Minigun Jima.}
{1801}{}{Pod svou zbrojí nosí tričko Červeného Trpaslíka.}
{1810}{}{*Prohlédne si tvé společníky* Vypadáš dobře, Kocoure.}
{1811}{}{Dávej pozor na Kocoura, rozumíš? Nechci, aby se dostal do maléru. To já ho stvořil, víš.}
{1812}{}{Hele, kde je Kocour? Napsal jsem totiž jeho dialog, víš.}
{1900}{}{Vidíš Bofasta.}
{1901}{}{Postaví se vzpřímeně, když uvidí, že se na něj díváš.}
{1910}{}{To bylo od tebe hezké, že se ti podařilo mírumilovně vyřešit ten problém s nájezdníky útočícími na Vault City. Beze mě by to nebylo možné.}
{1911}{}{Nebylo nutné zabíjet všechny nájezdníky útočící na Vault City. Díky mě teď existuje i mírumilovné řešení.}
{2000}{}{Vidíš Pixota.}
{2001}{}{Vidíš ušlechtilého oprávářského robota.}
{2010}{}{(Robot kývne, když se přiblížíš.) Nazdar. Bavíš se na tomto světě?}
{2011}{}{Ano, bavím. Díky za optání.}
{2012}{}{Ani ne. Mohlo by to být lepší.}
{2013}{}{Nemám náladu si teď povídat. Nashle.}
{2020}{}{To rád slyším! Doufám, že všechna ta dřina, aby každá lokace byla co možná nejdetailnější a nejunikátnější, se nějakým způsobem projevila na tvém štěstí. Dalo hodně práce to všechno upravit, ale celkově je teď atmosféra i vzhled naprosto dokonalá. Nemyslíš?}
{2021}{}{Jo, to rozhodně. Všechno vypadá úžasně. Máš docela talent!}
{2022}{}{No, ujde to.}
{2023}{}{Je to hezké. Nashle.}
{2030}{}{To nerad slyším. Nejspíš se jen nedíváš pořádně kolem sebe. Hodně jsem se snažil, aby každá lokace vypadala co nejlépe a nejdetailněji jak to jen jde. Třeba se ti zvedne nálada, když se podíváš na detaily. Dalo hodně práce to všechno upravit, ale celkově je teď atmosféra i vzhled naprosto dokonalá. Nemyslíš?}
{2031}{}{Když tak o tom mluvíš, tak je pravda, že to tady vypadá mnohem lépe.}
{2032}{}{Opravdu nic zvláštního nevidím.}
{2033}{}{Je to hezké. Nashle.}
{2040}{}{(Robot se radostně houpe vpřed a vzad.) Jsem rád, že se ti to líbí. No, musím teď odejít. Mám ještě na práci pár drobností, které chci vypustit do tohoto světa.}
{2041}{}{Dobrá. Tak zatím.}
{2050}{}{(Robotovi smutně poklesne hlava.) Hmm, moje práce zřejmě není pro každého. Teď mě omluv, musím odejít. Mám ještě na práci pár drobností, které chci vypustit do tohoto světa.}
{2051}{}{Nevadí. Nashle.}
{2060}{}{Já tak strašně rád tvořím nové věci.}
{2061}{}{Teď je tu tolik nových detailů. Překrásné.}
{2100}{}{Vidíš Mashe.}
{2101}{}{Kýve na tebe.}
{2110}{}{Nazdar! Jsem rád, že ses dostal tak daleko. Doufám, že se ti líbí zvětšená viditelnost tohoto světa. Nedalo se najednou zobrazit dostatek věcí na jedné obrazovce, tak jsem to všechno změnil. Imperátorka Timeslip a já jsme mistry Zdrojáku. Přivedli jsme tento starý svět do nové doby.}
{2111}{}{Páni, díky moc. Všechno je teď o hodně lepší. Občas trochu moc malé, ale to si lehce upravím.}
{2112}{}{Na tohle nemám čas. Nashle.}
{2120}{}{Jsem rád, že si užíváš plody mé těžké práce. Také jsem umožnil měnit vzhled postavy. Už nemáš na výběr pouze konkrétní rasu nebo účes. Yosan12, x'il a ostatní vytvořili fyzické vzhledy, ale to já se s pomocí Imperátorky Timeslip zanořil hluboko do Zdrojáku a provedl potřebné úpravy. Vidím, že již této možnosti využíváš. Vynikající!}
{2121}{}{Jo, miluji svůj nový vzhled. Díky moc!}
{2122}{}{Jasně. Sbohem.}
{2130}{}{Jsem rád, že si užíváš plody mé těžké práce. Také jsem umožnil měnit vzhled postavy. Už nemáš na výběr pouze konkrétní rasu nebo účes. Yosan12, x'il a ostatní vytvořili fyzické vzhledy, ale to já se s pomocí Imperátorky Timeslip zanořil hluboko do Zdrojáku a provedl potřebné úpravy. Vidím, že této možnosti zatím nevyužíváš. Teď už víš, že tu něco takového je. Skvělé místo na vyzkoušení je v EPA. Och, taková zábava!}
{2131}{}{Budu si to pamatovat. Díky.}
{2132}{}{Jasně. Sbohem.}
{2140}{}{Výborně. Tak zatím.}
{2141}{}{Sbohem.}
{2142}{}{Zatím.}
{2150}{}{Zdroják je záludný, ale já si s ním poradím.}
{2151}{}{Užij si zvětšenou viditelnost tohoto světa!}
{2152}{}{Užij si tvé nové já!}
{2200}{}{Vidíš Mikaela Grizzlyho.}
{2201}{}{Toto zvíře je extrémně chlupaté.}
{2210}{}{Nazdar. Pomohl jsem dostat ponorku zpět do tohoto světa.}
{2211}{}{Líbí se ti, jak jsem chlupatý? Mně jo.}
{2212}{}{Doufám, že se ti ponorka líbila.}
{2300}{}{Vidíš x'ila.}
{2301}{}{S obdivem tě pozoruje.}
{2310}{}{Hodně jsem pomohl se vzhledem nových tvorů. Doufám, že se ti líbily!}
{2311}{}{Pěkný vlasy, člověče. Beze mě by to nebylo možné.}
{2400}{}{Vidíš hromadu kamení.}
{2401}{}{Na kamenech je plaketa.}
{2410}{}{Na kamenech je plaketa. Je na ní napsáno: "Věnováno Peru Jornerovi - Mistru návodů, Královi ještěrek a Akumulátorovi všech kamenů.}
{2500}{}{Vidíš velikou hromadu slizu.}
{2501}{}{Zdá se, že tato hromada slizu něco vyslovuje: "Věnováno všem, jejichž jména už byla zapomenuta, ale přesto pomohli dotáhnout všechno do zdárného konce."}
{2510}{}{}
{5000}{}{Boj zde není dovolen.}
