{100}{}{Vidíš velkı kamennı monument. Zdá se, e... si pro sebe nìco mumlá?}
{101}{}{Vidíš kamennı monument v podobì hlavy Zakladatele. Podoba je docela vìrná, i kdy pochybuješ, e jeho hlava byla tak veliká.}
{102}{}{Vidíš velkı kamennı monument.}
{103}{}{Vidíš kamennı monument v podobì hlavy Zakladatele. Podoba je docela vìrná, i kdy pochybuješ, e jeho hlava byla tak veliká.}
{104}{}{Zatracení turisti...}
{105}{}{"Jsem Vyvolenı"}
{106}{}{Bıt tebou, Vyvolenı, zmizel bych odsud.}
{107}{}{Chrrrr chrrrr chrrrrrrrr}
{108}{}{Chrrrrrrrrrrrrr}
{109}{}{Chrvrrv... *chrr*... chrrrrrrrr}
{110}{}{Chrrrrrvvvvvrrrrrr}
{111}{}{Chrrrrrrvvvvvvvvrrrrrrr}
{112}{}{Pøál bych si, abych vidìl, co je za mnou.}
{113}{}{Kdyby tak nìkdo pøišel a vykopal mì celého...}
{114}{}{Ti kamenoraví mravenci tady jistì kadou chvíli budou a seerou mì.}
{115}{}{"Staò se velikou kamennou hlavou! Uvidíš svìt!" Takové kecy.}
{116}{}{Nemám nejmenší tušení, jak jsem se ocitl uprostøed téhle pouštì.}
{117}{}{Poøád nechápu, proè musím bıt tady uprostøed pouštì, zatímco ta druhá hlava si spokojenì hoví ve vesnici.}
{118}{}{Tím chci øíct, e ji uctívají, èistí, lidé se k ní modlí... a já se mùu akorát tak celı den dívat na písek.}
{119}{}{Slyšel jsem, e se ti kluci na Velikonoèních ostrovech nemají špatnì.}
{120}{}{Vsadím se, e má Stonehenge vìtší návštìvnost ne já.}
{121}{}{Hrnnfff... ehhh, mami... dneska nejdu do školy... chrrrrrrr}
{122}{}{Chrrrrrrrrrr... ještì nechci vstávat... chrrrrrrr}
{123}{}{Chrrrrrrrr... eh?}
{124}{}{Co...?}
{125}{}{DEJ TY ZATRACENİ PRACKY PRYÈ!}
{126}{}{Hráè by se mìl otoèit, udìlat nìkolik krokù dozadu a znovu se otoèit èelem k monumentu.}
{127}{}{*Ehm*}
{128}{}{KDO SE OPOVAUJE PØISTOUPIT K POSVÁTNÉ HLAVÌ ZAKLADATELE?!}
{129}{}{Já, Vyvolenı.}
{130}{}{HAHAHAHAHAHA!}
{131}{}{*TY*?! A VYVOLENİ?!}
{132}{}{VDY NEJSI VÌTŠÍ NE MÙJ PRST!}
{133}{}{TY *NEJSI* VYVOLENİ.}
{134}{}{Jo, jsem.}
{135}{}{NE, NEJSI.}
{136}{}{Jo, jsem.}
{137}{}{E-e.}
{138}{}{Aha.}
{139}{}{E-e.}
{140}{}{Aha.}
{141}{}{E... e...}
{142}{}{E... he...}
{143}{}{E... DOST! NECH TOHO!}
{144}{}{NO DOBØE! PØESVÌDÈIL JSI MÌ!}
{145}{}{TY *JSI* VYVOLENİ!}
{146}{}{VEM SI TOHLE!}
{147}{}{A TEÏ ODEJDI!}
{148}{}{Hej, díky!}
{149}{}{NO JO. A TEÏ VYPADNI.}
{150}{}{ZATRACENÍ TURISTI.}
{151}{}{U JSEM TI DÁREK DAL.}
{152}{}{ZMIZ!}
{153}{}{Idiote.}
{154}{}{CO?! TY MÌ CHCEŠ OKRÁST?!}
{155}{}{ZEMØI!}
{156}{}{Rozloit hráèe pomocí animace plazmové smrti.}
{200}{}{(O 12 hodin pozdìji.)}
{1129}{}{Já Vyvolenı.}
{1134}{}{Já bıt.}
{1136}{}{Já bıt!}
{1138}{}{Aha.}
{1140}{}{Aha.}
{1142}{}{E... he...}
{1148}{}{Dík!}
