# Message file for Toaster.ssl 
# Number of nodes: 7

{100}{}{Vidíš matnì støíbrnı toustovaè stojící na stole.}
{101}{}{Vidíš Odvánı Malı Toustovaè.}
{102}{}{OMT, váš veselı i kdy trochu otravnı spoleèník u snídanì.}

# Node  0  [Node001]
{200}{}{Tì péro, sombréro! Tak co ivot? Já jsem Odvánı Malı Toustovaè - švitoøící toustovaè, váš veselı spoleèník u snídanì. OMT jsem já a toustuju rád. Dá si nìkdo toust?}
{201}{}{Ne, díky, ale chci se na nìco zeptat.}
{202}{}{Teï ne, u musím jít.}

# Node  1  [Node002]
{210}{}{Jasnì, sem s tím! Jsem jednièka v kvantové mechanice, submolekulární biologii a televizních znìlkách. Zeptej se mì na cokoliv. Ale mùu mít nejdøív otázku já na tebe?}
{211}{}{No, proè ne. Co potøebuješ vìdìt?}

# Node  2  [Node003]
{220}{}{Urèitì nemáš chu na toust?}
{221}{}{NE! Nechci ádnı tousty! ádnı muffiny, ani tousty, koláèky, ádnı emle, briošky, bagety, ani buchty, ádnı veky, ani loupáky a palaèinky, bramborovı placky, ádnı teplı jidáše a u vùbec ne nìjakı pitomı lívance!!!}

# Node  3  [Node004]
{230}{}{Ahá, take ty jsi na vafle!}
{231}{}{Tak a u toho mám dost.}
{232}{}{(Vyèerpanì se chytneš za hlavu.) U musím jít. Já... teï musím nìkde bıt. Kdekoliv jinde.}

# Node  4  [Node005]
{240}{}{Ne, poèkej. Omlouvám se. Nejsem jednostrannì, peèivovì zaloenı pøístroj. Co pro tebe mùu udìlat?}
{241}{}{Potøebuju nìjaké informace o tomhle místì. Co mi o nìm mùeš øíct?}

# Node  5  [Node006]
{250}{}{Øeknu ti jedno: tohle je hrozné místo pro nìkoho mıch toustovacích kvalit. Víš, e u je to víc ne sto let, co jsem mìl to potìšení nìkomu udìlat toust? Jsi první návštìvník, kterı sem od války pøišel a teï se podr: kdybys mì poádal o toast, tak já ani nevím, jestli bych ho ještì zvládl udìlat. Víš, cítím se teï trochu pod psa. Je to docela trapné.}
{251}{}{To je, eh, hrozná tragédie. A proè jsi vlastnì tady?}
{252}{}{Aha. Díky za tvùj èas.}

# Node  6  [Node007]
{260}{}{Myslím, e si sem tìsnì pøed tou nehodou nechal doruèit zásilku plynovıch masek. Nìkdo dokonce tvrdí, e si za ten problém mùe vlastnì sám.}
{261}{}{A proè jsi vlastnì tady?}
{262}{}{Díky za informace.}

# Node  7  [Node008]
{270}{}{Pøece abych ti zpøíjemnil ráno, jak to jen pùjde! Poslyš, nemáš v bøiše po tak vyèerpávající konverzaci trochu místa na toust?}
{271}{}{To u jsme snad probírali!! Nemám hlad a ani mít nikdy nebudu. A teï vánì, proè jsi OPRAVDU tady?}

# Node  7  [Node008]
{280}{}{No dobøe, tak se hned nerozèiluj. Rozèilování není nikdy dobrı start do nového dne. Byl jsem pùvodnì vytvoøen jako spoleèník ke snídani, ale poslouím stejnì tak dobøe i u obìda nebo veèeøe. Toustem nikdy nic nezkazíš. Nebo se snad ptáš, proè teï leím zrovna tady a z boku mi èouhá drát? No, zdá se, e Mr. Handy není pokadé tak šikovnı, jak se na první pohled zdá. Ten vùl se rozbil zrovna pøi mé roèní kontrole. Pak samozøejmì odcupital na údrbu a mì tu nechal osudu.}
{281}{}{Aha. No, díky za tvùj èas.}

{290}{}{Za málo. A zase se nìkdy stav. Tøeba ti èasem vyhládne.}
{291}{}{Pochybuju. Nashle.}

{300}{}{Já vìdìl, e se vrátíš. Kadı se nakonec vrátí. Nedáš si toust?}
{301}{}{Já vìdìl, e se vrátíš. Kadı se nakonec vrátí. A teï kdy jsem opravenı, udìlám ještì lepší toust ne pøedtím. Nedáš si?}
{302}{}{Teï ne, ale mám na tebe otázku.}
{303}{}{Ne. U musím jít.}

{310}{}{Sem s ní. Doufám, e je peèivovitá.}
{311}{}{Co je tohle za místo?}
{312}{}{Vlastnì nic. Nashle.}

{350}{}{Hele, já jsem opravenı! Já vìdìl, e to Mr. Handy pìknì odbyl. Teï se cítím líp ne kdy pøedtím! Díky.}
{351}{}{Jasnì, není zaè. Tak zatím.}
{352}{}{Poèkej ještì. Jestli nechceš udìlat toust, tak ti dám aspoò malou radu. Znáš ty hrací automaty na páku, co bıvají v kasínech? Tak já jsem vypoèítal, jak se dají snadno vydímat a do dna. Mám toti IQ 6000, víš, a kdy zrovna netoustuju, rád pøemıšlím nad takovımi vìcmi. Za tvoji pomoc ti povím tyhle tajné kódy. Staèí jen normálnì zatáhnout za páku a...}
{353}{}{[Více]}
{354}{}{...a to je všechno. Za chvíli budeš mít tolik penìz, e se budeš moct ládovat toustama od rána do veèera.}
{355}{}{Díky, váím si toho. Mìj se.}

{400}{}{Úspìšnì se ti podaøilo opravit toustovaè.}
{401}{}{Nepodaøilo se ti opravit toustovaè.}
{402}{}{Toustovaè je u opravenı.}
{403}{}{ úspìšnì opravuje toustovaè.}
{404}{}{ selhává pøi opravì toustovaèe.}