{100}{}{Vidíš dveøe.}
{101}{}{Vidíš elektronické dveøe.}
{102}{}{Vidíš elektronické dveøe s hlasovì ovládaným zámkem, který je chránìný pøístupovým kódem.}
{200}{}{Vložit kód:}
{201}{}{XY104FD}
{202}{}{BFN12}
{203}{}{Otevøít}
{204}{}{Pšenice}
{205}{}{Abre}
{206}{}{[KONEC]}
{300}{}{Nesprávný kód. Zamykám dveøe. Prosím, kontaktujte vedení Oddìlení pro styk s veøejností pro získání nového kódu.}
{301}{}{[KONEC]}
{400}{}{Vložit nový kód.}
{401}{}{[KONEC]}
{402}{}{Tyto dveøe jsou elektronicky uzamèené.}
{403}{}{Odemykám dveøe. Dìkujeme a pøejeme pøíjemný zbytek dne.}
{404}{}{[KONEC]}
{500}{}{Tyto dveøe nemají zámek, který by se dal vypáèit.}
