{100}{}{Dobrý den, vítejte v Agentuře na ochranu životního prostředí, známé také jako komplex EPA! V tomto Rozcestníku naleznete informace o jednotlivých barevně odlišených zónách, na které jsou rozdělena podlaží našeho komplexu. Vyberte prosím zónu, o které se chcete dozvědět více.}
{101}{}{ORANŽOVÁ ZÓNA}
{102}{}{ČERVENÁ ZÓNA}
{103}{}{ŽLUTÁ ZÓNA}
{104}{}{INDIGO ZÓNA}
{105}{}{FIALOVÁ ZÓNA}
{106}{}{ZELENÁ ZÓNA}
{107}{}{MODRÁ ZÓNA}
{108}{}{V Oranžové zóně naleznete konferenční místnosti, kde padají všechna vzrušující rozhodnutí, dále bistro s chutnými pokrmy a úložiště nebezpečných chemikálií.}
{109}{}{V Červené zóně je umístěno naše oddělení ostrahy (takže se chovejte ukázněně!) a malé, ale velmi informativní muzeum. Dále si nezapomeňte koupit svačinu a zastavte se v našem středisku veřejných poprav! (Upozornění: Středisko poprav není vhodné pro děti do čtyř let.)}
{110}{}{Ve Žluté zóně je umístěna místnost s generátory energie pro naše nové fascinující hologramy. Také zde najdete oblíbený přístroj na výrobu léků a drog, Mr. Chemmieho! (Upozornění: Kvůli nedostatku skladových prostor jsou zde v současné době uskladněny také některé nebezpečné chemikálie, dbejte proto zvýšené opatrnosti!)}
{111}{}{V Indigo zóně provádějí naši geniální vědci přísně tajný výzkum! Vzrušující, že ano? Mějte na paměti, že nepovolaní civilisté v této zóně budou na místě zastřeleni, proto prosíme rodiče, aby nenechávali své děti volně pobíhat bez dozoru.}
{112}{}{Ve Fialové zóně je umístěno paměťové jádro pro uchovávání informací a další věci, které jsou bohužel pro návštěvníky relativně nezajímavé. Omlouváme se! Nicméně je tato zóna přímo propojena s mnohem zajímavější Žlutou zónou, kde najdete například Mr. Chemmieho, farmaceutický automat budoucnosti!}
{113}{}{Ve vzrušující Zelené zóně najdete arboretum, výzkum biologických zbraní, fascinující nová stvoření a EPA interaktivní zoo, tolik oblíbenou u dětí.}
{114}{}{Modrá zóna neexistuje. Pokud vám někdo tvrdí opak, je to hnusný lhář a pravděpodobně přívrženec komunismu. Jako správný americký vlastenec jej prosím nahlaste na oddělení ostrahy v Červené zóně a naše ochranka se s ním už vypořádá. Děkujeme vám!}
{115}{}{Zpět do hlavního menu.}
{116}{}{Děkujeme za použití Rozcestníku.}
{117}{}{[KONEC]}
{118}{}{Vidíš počítač.}
{119}{}{Vidíš EPA Rozcestník.}
{120}{}{Vidíš počítač, který obsahuje detailní informace o barevných zónách komplexu EPA.}
