{100}{}{Řídící počítač hibernační komory. Vyberte akci.}
{101}{}{Historie subjektů.}
{102}{}{Rozmrazit testovací subjekt.}
{103}{}{[KONEC]}
{104}{}{Hibernační komory. Před válkou zde byli uloženi tři jedinci, každý kvůli specifickým, utajovaným důvodům. Subjekty zůstaly zmraženy a izolovány od okolí. Pro každý subjekt jsou dostupné záznamy.}
{105}{}{Zpět do hlavního menu.}
{106}{}{VAROVÁNÍ: Dlouhodobý pobyt ve velmi chladném prostředí změní chemické procesy v těle. Před opuštěním komory je nutno aplikovat chemikálie do lidského těla, jinak může subjekt trpět ERS (Syndromem odmítání prostředí). K zajištění bezpečnosti subjektu je vysoce doporučeno umístit kanystr s ERSI (Inhibitorem syndromu odmítání prostředí) do dávkovače ještě před otevřením.}
{107}{}{No skvělý. Právě se probudila hromada kostí.}
{108}{}{Ne, zpět do hlavního menu.}
{109}{}{Rozmrazuji testovací subjekt.}
{110}{}{Rozmrazuji testovací subjekt.}
{111}{}{Rozmrazuji testovací subjekt.}
{112}{}{Děkujeme, že jste použili řídící počítač hibernační komory.}
{113}{}{Vidíš velký počítač.}
{114}{}{Vidíš řídící počítač hibernační komory.}
{115}{}{Vidíš počítač, který se používá k ovládání všeho kolem hibernačních nádrží.}
{116}{}{Umístit kanystr s ERSI do dávkovače.}
{117}{}{Pokračovat.}
{118}{}{Inhibitory syndromu odmítání prostředí byly úspěšně aplikovány na jedince. Srdeční tep jedince se zdá být normální. Prosím pokračujte do kryogenické komory pro vyzvednutí subjektu.}
{119}{}{VAROVÁNÍ: Na jedince nebyly aplikovány žádné inhibitory syndromu odmítání prostředí. Stav jedince je neznámý. Prosím pokračujte do kryogenické komory pro vyzvednutí subjektu.}
{120}{}{Hmm, možná by nebylo špatné se podívat po nějakém tom kanystru s ERSI. Někde tady ty chemikálie musí být...}
{200}{}{Číst záznamy.}
{210}{}{Vyberte prosím subjekt.}
{211}{}{Subjekt A.}
{212}{}{Subjekt B.}
{213}{}{Subjekt C.}
{214}{}{Zpět.}
{220}{}{Záznam #87983: Tak k tomu nakonec došlo. Vypustili na nás atomovky a my na ně vypustili ty svoje. Brass nechce sdělit podrobnosti, ale touhle dobou už musí být na povrchu Soudný Den. Rádiové spojení bylo přerušeno na neurčitou dobu. Ještě, že jsem si na toto místo zvykl. Ani nedoufám, že ještě někdy spatřím povrch.}
{221}{}{[Více]}
{222}{}{Přivedli ženu ke zmražení. Neřekli proč, jen to, že se jedná o přísně tajnou záležitost. Byla opravdu velmi pohledná. Taková drobná, s čínskými kořeny, a na jejich očích bylo něco zvláštního. Oddělala dva agenty tajné služby, když se dozvěděla, co s ní chceme udělat. Překvapila je a rozpárala je jedním z Delnayových skalpelů. Ježiši Kriste, na něco takového by se dokázal dívat jen zvrácený člověk. Třetí agent ji už přemohl, ale i kdyby zabila úplně všechny, stejně by tu dole prožila zbytek svého života. Teď je v bezvědomí a připravuje se pro ni komora. Je hned vedle toho psychopata Patricka. Taková škoda. Chtěl sem ji poznat blíže. -Dr. David Kimble, 23.10.2077}
{230}{}{Záznam #81977: Dexter "Dex" Patrick je velmi zajímavý jedinec. Je to narcistický, šílený vrah, který nesnáší ženy a je znám občasným vyžíváním se v nekrofilii a kanibalismu. Je až extrémně bezcitný a nemá žádné slitování se svými obětmi, mezi které patří nevinné děti, staří lidé a postižení. Jeho nejčastějšímí obětmi byly přitažlivé, mladé ženy, které nejdříve svedl k souloži a poté je brutálně zavraždil.}
{231}{}{[Více]}
{232}{}{I přes své anti-sociální chování je až pozoruhodně přátelský a dokonce i galantní. Ve skutečnosti přitahoval několik zaměstnankyň, i když věděly o jeho mnoha spáchaných zvěrstvech. Dex má v současnosti na svědomí 68 potvrzených obětí, i když se chvástal, že skutečné číslo je hodně přes sto. I přesto, že se Dex ukázal být notorickým lhářem, nejsem stále schopen zpochybnit pravdivost tohoto tvrzení.}
{233}{}{[Více]}
{234}{}{Jediné Dexovy známé emoce jsou k rock 'n rollovému idolu poloviny dvacátého století, kterého považuje za svůj vzor a možná i za svého otce. Také se až nezdravě váže na oddělené lidské ucho, které dle naší identifikace patří Vicky Safronové, Dexově středoškolské lásky a jedné z jeho prvních obětí. Tvrdí, že si to ucho schovává v kapse, aby Vicky slyšela křik všech jeho obětí.}
{235}{}{[Více]}
{236}{}{Rozhodl jsem se, že prozatím nechám Dexe zmraženého, jelikož vláda převedla peníze z našeho projektu na válečný program a můj tým byl přeřazen na jiné pozice. Nechť je poznamenáno, že toto považuji za krok vedle, jelikož naše studie podstaty lidské zloby pokračují rychlým tempem a já věřím, že jsme blízko velikému průlomu, který by byl pro naši vládu mnohem cennější než výroba "plechových obleků". Ale zpět k tématu.}
{237}{}{[Více]}
{238}{}{Dex tu zůstane zmražený, dokud ti nahoře nepřijdou k rozumu a neobnoví tento nesmírně důležitý projekt. Jen doufám, že budu ještě naživu, až ten den nastane. -Dr. Dustin C. Delnay, 13.04.2075}
{240}{}{Záznam #80052: Seržant Christopher "Kocour" Jules byl převelen na vojenskou ostrahu komplexu EPA dne 17.02.2074. Předtím byl součástí vzdušných sil 205-tého průzkumného oddílu. Seržant má vynikající bojové výsledky a je jedním z nejlepších specialistů v oddílu na energetické zbraně a boj beze zbraně. Nicméně jsou tyto úspěchy zastřeny jeho stejně dlouhým seznamem obvinění z drobných krádeží, opakovaných případů nenošení uniformy a chováním s extrémní arogancí vůči nadřízeným důstojníkům.}
{241}{}{[Více]}
{242}{}{Srž. Jules byl rekrutován jako pokusný subjekt pro projekt zlepšení lidských reflexů dne 5.10.2075, výměnou za vymazání některých záznamů z jeho složky. Už od počátku však nastaly komplikace a Srž. Jules dostal sedativa, aby neohrozil bezpečnost okolí.}
{243}{}{[Více]}
{244}{}{Uběhlo několik dní a Srž. Jules se zdá být zdravý, ale spolu s původními cíli projektu na zlepšení reflexů a zvýšených schopností smyslů, se u něj vyvinuly prodloužené špičáky a jisté výstřední vlastnosti. Zaznamenal jsem několik zpráv od velitele základny požadující další financování, ale bohužel tu existují jedinci, kteří si nepřejí pokračovat v mém projektu. Je to docela škoda, jelikož vzorky tkání a psychologické testy Srž. Julese ukazují pouze lehké zohyzdění a tendence ke sníženému rozsahu pozornosti. Jinak je naprosto schopný výkonu služby a díky výsledkům pokusu je ve skutečnosti ještě způsobilejší než předtím. Srž. Jules zůstane v hibernaci, dokud nedostaneme VÍCE financí na tento projekt. -Dr. R.D. Crichton, 04.11.2075}
{300}{}{Vybrat subjekt:}
{301}{}{Seržant Christopher "Kocour" Jules}
{302}{}{Dexter "Dex" Patrick}
{303}{}{Kitsune}
