{100}{}{Vidíš osobu v legračním pyžamu.}
{101}{}{Vidíš Shi, městského obyvatele.}
{102}{}{Tato osoba vypadá jinak než ostatní. Nevypadá to, že se o tebe zajímá.}
{103}{}{Nejsi špión, že ne?}
{104}{}{Kdo jsi?}
{105}{}{Ryby a mořské řasy. To je to jediné, co tady máme.}
{106}{}{Hehe, koukni na ty legrační kulaté oči!}
{107}{}{Vypadáš jako Hubologista.}
{108}{}{Nech nás na pokoji.}
{109}{}{Ať žije Lo Pan!}
{110}{}{Pryč s Dragonem!}
{111}{}{Lo Pan je hrdina.}
{112}{}{Pozor na Dragona. Jsou s ním problémy.}
{113}{}{Ti pankáči jsou vždycky tak hlasití.}
{114}{}{Práce, práce a zase jenom práce. Rýže, rýže a zase jenom rýže. ::povzdech::}
{115}{}{To je celý život jenom o tomhle?}
{116}{}{Jsme chytřejší, než si myslíš.}
{117}{}{Podívej! Lao wai!}
{118}{}{Vítej v San Franciscu.}
{119}{}{Vypadáš jako někdo, kdo to má v hlavě v pořádku.}
{120}{}{Lo Panovi by se hodila tvoje pomoc.}
{121}{}{Neubližuj lidem v červeném, lao wai.}
{122}{}{Lao wai znamená "cizinec".}
{123}{}{Jsi na naší straně, že ano?}
{124}{}{Zabij pro nás Dragona, ano?}
{125}{}{Tvoje přítomnost je nám ctí.}
{126}{}{Náš vůdce! Ach ne!}
{127}{}{Musíme se pomstít za Lo Pana!}
{128}{}{Kdo nás povede vstříc lepším zítřkům, když je teď Lo Pan mrtev?}
{129}{}{Co budeme teď dělat?}
{130}{}{Jsme zneuctěni. Měli bychom být mrtví jako Lo Pan.}
{131}{}{Život nemá žádný smysl.}
{132}{}{S Lo Panem odešly i naše sny.}
{133}{}{Lo Pan byl náš poslední velký vůdce.}
{134}{}{Dragon je mrtvý! Lo Pan zvítězil!}
{135}{}{Vysmívejte se poraženým!}
{136}{}{Dragon padl!}
{137}{}{Lo Pan! Lo Pan! Lo Pan!}
{138}{}{Jsme vítězi!}
{139}{}{Dragon je mrtev. Jó!}
{140}{}{Práce, práce a zase jenom práce. Rýže, rýže a zase jenom rýže. ::povzdech::}
{141}{}{To je celý život jenom o tomhle?}
{142}{}{Jsme chytřejší, než si myslíš.}
{143}{}{Podívej! Lao wai!}
{144}{}{Císařův mluvčí! A mrtev! Celé město se teď zhroutí!}
{145}{}{Co teď s námi bude?}
{146}{}{Doufám, že nás teď divoši nepředběhnou!}
{147}{}{Dobro vždy umírá mladé.}
{148}{}{Doufám, že bez Kena Lee přežijeme zimu.}
{149}{}{Říká se, že byl Ken Lee jediný člověk, který dokázal Císaře zmanipulovat.}
{150}{}{Říká se, že byl Císař pouhou loutkou Kena Lee. }
{151}{}{Možná by mohl Lo Pan převzít pozici Kena Lee...}
{152}{}{Práce, práce a zase jenom práce. Rýže, rýže a zase jenom rýže. ::povzdech::}
{153}{}{To je celý život jenom o tomhle?}
{154}{}{Jsme chytřejší, než si myslíš.}
{155}{}{Podívej! Lao wai!}
{163}{}{Ty jsi zabil AHS-9? Jó!}
{164}{}{Ti hubologisti mi nahání husí kůži.}
{165}{}{Prokázal jsi nám velkou službu.}
{166}{}{Smrt Hubologistům!}
{167}{}{Snad to odsud vyžene Hubologisty.}
{168}{}{Pitomí Hubologisti, neumí si ani ochránit svého vůdce.}
{169}{}{Snad se nám Hubologisti nebudou chtít pomstít.}
{170}{}{Tak nakonec asi nejsi špión.}
{171}{}{Prase! Chcípni!}
{172}{}{Zneuctil jsi svoji rodinu!}
{173}{}{Nech nás na pokoji, lao wai!}
{174}{}{Copak jsi už nezpůsobil dost problémů?}
{175}{}{Nenávidím tě!}
{176}{}{Opusť toto město!}
{177}{}{Vrať se domů ke svým lidem!}
{178}{}{Nezastiňuj můj život svým obličejem!}
{179}{}{Co mě bude stát, abych se tě zbavil?}
{180}{}{Pomoc! Pomoc!}
