{100}{}{Vidíš docela mladého plešatícího vìdce. Vypadá to, e je soustøedìnı na svou práci.}
{101}{}{You see Crockett, the Hubologist scientist.}
{102}{}{Vidíš pomìrnì mladého plešatícího vìdce. Vypadá jako neupravenı geek.}
{103}{}{Jo? Co chceš?}
{104}{}{Á. Em. Hmm.}
{105}{}{Posílá mì Dr. Jing. Chce nìjaké tvrzené energo zbroje.}
{106}{}{Mùeš mi vylepšit energo zbroj?}
{107}{}{Kdo jsi?}
{108}{}{Co tady dìláš?}
{109}{}{Nic, díky.}
{110}{}{Pøísahám, e je tu kadım dnem èím dál tím víc podlidí. Kšá! Kšá!}
{111}{}{Chmm.}
{112}{}{Jo, to mùu, ale co mi za to nabídneš?}
{113}{}{Dr. Jing je ochoten ti prodat palivo pro vaši vesmírnou loï.}
{114}{}{Mùu ti za to zaplatit.}
{115}{}{Nechám tì ít.}
{116}{}{ádnı. Zapomeò na to.}
{117}{}{I'm Crockett. I'm a scientist and fix-it guy. Can I get back to it?}
{118}{}{Ne. Mám další otázky.}
{119}{}{Jo, jistì.}
{120}{}{Vyvinul jsem novou technologii a na oplátku si mùu uít trochu kultistické lásky, jestli mi rozumíš.}
{121}{}{So you're not a Hubologist?}
{122}{}{Chápu. Mám další otázky.}
{123}{}{Ne. Co tím myslíš?}
{124}{}{Jakou novou technologii jsi vyvinul?}
{125}{}{Naprosto jasnì. Zatím.}
{126}{}{No... to bude *asi* staèit. Dohodnuto. Máš u sebe zbroj, kterou chceš vytvrdit?}
{127}{}{Ano.}
{128}{}{Ne.}
{129}{}{Skvìlé. Bude tì to stát $10 000 a ani o dolar ménì. Potøebuji nìjaké nové vybavení.}
{130}{}{$10 000? To je šílené! Tolik penìz nemám!}
{131}{}{Tak dobøe. Tady jsou.}
{132}{}{Ještì se vrátím.}
{133}{}{::vypadá pobavenì:: Vyhrouješ mi snad?}
{134}{}{Ano. Udìlej to, nebo zemøeš.}
{135}{}{Ne, jenom si dìlám legraci.}
{136}{}{Nech ji tady den a já ji pøipravím. Ne pùjdeš, mìl bys vìdìt, e mám materiál pouze na dvì sady zbrojí.}
{137}{}{Jasnì. Mám další otázky.}
{138}{}{Pak se vrátím pro tu zbroj.}
{139}{}{Kdy ji nemáš, tak na ní nemùu pracovat. Vra se, a ji budeš mít.}
{140}{}{Mám další otázky.}
{141}{}{Nashle.}
{142}{}{::krèí kameny:: Chceš tu zbroj nebo ne? Bude to $10 000 a ani o dolar ménì.}
{143}{}{Ještì se vrátím.}
{144}{}{Fajn. Tady máš.}
{145}{}{Taková zlodìjina. V ádném pøípadì.}
{146}{}{::dívá se ti do oèí a dojde k názoru, e to myslíš vánì:: Máš u sebe jednu takovou zbroj?}
{147}{}{Ano.}
{148}{}{Ne.}
{149}{}{::dívá se ti do oèí a dojde k názoru, e blafuješ:: Zkus to, buzno. Budeš mít strá za prdelí a u se nikdy nenauèíš vytvrdit zbroj.}
{150}{}{Fajn. Chcípni, šprte.}
{151}{}{Doprdele. Odhalil jsi mùj blaf.}
{152}{}{Podvodníku. Uvidíme, co na to øeknou stráe.}
{153}{}{Zatracenì!}
{154}{}{Tihle lidi neznají opravdovou vìdu. Pomáhám jim v jejich vıstøednosti vımìnou za nìjakı èas s jejich dámami a poøádnı plat.}
{155}{}{Hmm. Chci se ještì na nìco zeptat.}
{156}{}{To nezní špatnì. Zatím.}
{157}{}{Take... postavil jsem nukleární reaktor pro vesmírnou loï, vytvoøil jsem vytvrzující proces pro energo zbroje a opravuji vìci, které jsou rozbité.}
{158}{}{Chápu. No, mám další otázky.}
{159}{}{Hmm. Musím jít. Nashle.}
{160}{}{Hej, nic jsem ti neudìlal. Jenom mi neubliuj.}
{161}{}{Chci se tì na nìco zeptat.}
{162}{}{Jsem tu pro tu zbroj.}
{163}{}{Pøíliš pozdì.}
{164}{}{Nashle.}
{165}{}{Ještì to není hotové. Musíš mi dát èas!}
{166}{}{Fajn. Mám nìjaké otázky.}
{167}{}{Fajn. Ještì se vrátím.}
{168}{}{Mám ji pro tebe pøipravenou. Vezmi si ji.}
{169}{}{Díky. Mám další otázky.}
{170}{}{Díky.}
{171}{}{Díky. TEÏ mùeš umøít.}
{172}{}{Nemám u dost chemikálií. Promiò.}
{173}{}{Pak mi tedy mùeš odpovìdìt na pár otázek.}
{174}{}{Pak mùeš umøít.}
{175}{}{Aha. Sakra. Nashle.}
{176}{}{Tak kde je to moje palivo? Slíbil jsi mi palivo, kreténe.}
{177}{}{Dostaneš ho, neboj. A teï mi odpovìz na pár otázek.}
{178}{}{No, víš, kašlu na tebe.}
{179}{}{To byla tvoje poslední slova. STRÁE!}
{180}{}{Chcípni, kreténe.}
{181}{}{Doprdele. Mizím odsud.}
{182}{}{Dobøe, co chceš teï?}
{183}{}{Jsi u pøipraven zaplatit $10 000?}
{184}{}{Nech to tady tak den a já to pøipravím. Pamatuj si, e tohle je poslední zbroj, kterou mùu vylepšit.}
{185}{}{Nazdar, mám pro tebe další zbroj na vylepšení.}
