{100}{}{Vidíš muže v kovové zbroji.}
{101}{}{Vidíš Joshuu.}
{102}{}{Vidíš muže v kovové zbroji s odznakem blesku.}
{103}{}{Ahoj,}
{104}{}{. Jmenuju se Joshua. Co pro tebe můžu udělat?}
{105}{}{Jak ty vědět jméno?}
{106}{}{Jak víš, jak se jmenuju?}
{107}{}{Tvoje nedávné činy k nám přitáhly pozornost. Jedni mluví, druzí poslouchají a pak už se to šíří rychle. Ale pamatuj, že jsi jen malá rybka v oceánu plném žraloků,}
{108}{}{.}
{109}{}{Co to znamenat?}
{110}{}{Co tím myslíš?}
{111}{}{Řekněme, že jsi tu nový a nevíš, co se tu děje. Avšak věz, že tu nejde jen o jeden malý úkol...}
{112}{}{Pokračuj.}
{113}{}{Pokračuj, poslouchám.}
{114}{}{Už jsem prozradil dost. Myslím, že bude lepší, když se vrátíš ke své práci.}
{115}{}{Počkat, já potřebovat zeptat otázka.}
{116}{}{Počkej, potřebuju se tě na něco zeptat.}
{117}{}{Dobře, povolím ti jednu otázku. Co to bude?}
{118}{}{Ty vědět, kde já najít GECK?}
{119}{}{Ty vědět, kde já najít Vault 13?}
{120}{}{Já hledat obchodník Vic. Kde já najít?}
{121}{}{Nevíš, kde najdu GECK?}
{122}{}{Nevíš, kde najdu Vault 13?}
{123}{}{Hledám obchodníka jménem Vic. Nevíš, kde ho najdu?}
{124}{}{GECK bylo standardní vybavení každého vaultu. Jestli si dobře vzpomínám, používaly se k obnovení civilizace po otevření vaultu. Předpokládám tedy, že by se jeden mohl nalézat v nějakém dosud neotevřeném vaultu. Hodně štěstí,}
{125}{}{Díky.}
{126}{}{Slyšel jsem spoustu příběhů o Vaultu 13, ale v žádném z nich nebylo ani slovo o tom, kde se nachází. Hodně štěstí,}
{127}{}{Díky.}
{128}{}{Vic se zapletl s Cechem otrokářů. Tam ho najdeš. Hodně štěstí,}
{129}{}{Počkej! Kde najdu ten Cech?}
{130}{}{Počkej, můžeš mi říct, kde je ten Cech otrokářů?}
{131}{}{Zdravím. Už ti nemám co říct.}
{132}{}{. No... už nejsi ten obyčejný divoch jako na začátku. Doporučuju ti navštívit naši pobočku v New California Republic. Určitě se ti to vyplatí. A teď když mě omluvíš...}
{133}{}{Zdravím. Už ti nemám co říct.}
{134}{}{Čekat...}
{135}{}{To je soukromá kancelář.}
{136}{}{Tam pro tebe nic není.}
{137}{}{To je soukromý pozemek, takže odejdi.}
