{100}{}{Vidíš přístavního dělníka. Když se přiblížíš, podívá se na tebe.}
{101}{}{Vidíš utrápeného, přístavního dělníka. Jeho žalem naplněné oči si tě zběžně prohlédnou, když se přiblížíš.}
{200}{}{(Zamumlá si pro sebe.) Ach jo, co zlého provedl chudák Meng ve svém minulém životě, že se na něho lepí taková smůla? Teď ke mně přišel lao wai. Co dobrého může přinést? Samozřejmě že nic, vůbec nic...}
{201}{}{Proč nenecháš chudáka Menga na pokoji? (Zamumlá si pro sebe.) Ne že bych někdy poznal, co je to klid. A pokud ano, tak už je dávno zapomenut, jako vzdálený sen...}
{202}{}{Eh, zdá se, že jdu ve špatnou chvíli. Nashle.}
{203}{}{Co máš za problém, mumlale?}
{204}{}{Vidím, že jsi kvůli něčemu rozrušený. Třeba ti můžu nějak pomoct.}
{210}{}{Můj problém? (Zhluboka se zasměje.) Loa wai, nepřej si znát můj problém. Zažít takové utrpení, jako jsem zažil já, je jako zapomenout na dětský smích nebo vřelé obětí milovaného. Ne, věř mi, nechceš nahlédnout do mého osobního pekla.}
{211}{}{Už jsem zažil spoustu strašných věcí. Jsem si jist, že ať už máš jakýkoliv problém, dokážu ho vyřešit.}
{212}{}{Ty si myslíš, že jsou *tvoje* problémy veliké? Vsadím se, že se nedají *srovnat* s tím, čím jsem musel projít já.}
{213}{}{Je mi líto, že byl k tobě život krutý, ale možná se ti uleví, když si o tom promluvíš. Pokud chceš, vyslechnu tě.}
{214}{}{Jak myslíš, pane Melodramatiku. Jdu pryč, než z tebe chytnu depresi. Nashle.}
{220}{}{Fajn. Chceš znát můj problém, tak já ti ho povím. Před dvěma roky, můj bratr, který je mi velmi podobný, měl aféru s děvčetem šéfa místního gangu. Ten se o tom dozvěděl a můj bratr utekl z města. Gang místo něj chytil mě a protože si mysleli, že jsem můj bratr, tak mi za trest usekli penis. Teď chčiju skrz hadičku.}
{221}{}{Aha, no...}
{230}{}{Ne, ne! Ještě jsem neskončil. Potom mě má krásná dívka opustila, protože už jsem nebyl "skutečný muž" a nemohl ji uspokojit. Ona si pak vzala mého souseda, který je navíc můj šéf. Takže teď musím celý den pracovat, protože mi neustále rozkazuje a posmívá se mi i s mými spolupracovníky. A navíc teď musím každou noc usínat, zatímco slyším, jak on souloží s dívkou, kterou jsem si měl vzít za ženu.}
{231}{}{Hahaha! No do prdele, ty jsi ale smolař. Proč to raději neskoncuješ?}
{232}{}{Já, eh, páni, nevím co říct. To je strašný příběh.}
{233}{}{Je mi líto, co se ti stalo, Mengu. Život umí být krutý, ale vždycky se to může zlepšit. Být tebou, odstěhuju se někam pryč a najdu si jinou práci. Jinak se z toho nikdy nedostaneš.}
{240}{}{Ano. Ano, to už jsem měl udělat dávno. Je to jediný způsob, jak si zachovat trochu té cti, která mi ještě zbývá. Děkuji ti, lao wai. (Vezme si nůž a podřízne si krk. Vidíš, jak rychle krvácí a umírá.)}
{241}{}{[KONEC]}
{250}{}{Ano. Varoval jsem tě. Teď mě nech být. Nemám ti co říct.}
{251}{}{[KONEC]}
{260}{}{Asi máš pravdu. Celý můj život jsem nepoznal nic jiného než Shi. Tady na mě čeká jen žal. Ano, myslím, že bych se měl odvážit vyjít ven do světa vstříc novému osudu. I kdyby mi pustiny nenabídly nic jiného než rychlou smrt, bude to pořád lepší než zůstat tady. Děkuji ti, lao wai.}
{261}{}{Hodně štěstí, Mengu. Doufám, že už nebudeš mít takovou smůlu.}
{262}{}{Než se začneš balit, bylo by možné se tě na něco zeptat ohledně Shi?}
{270}{}{Proč ne? Ruším všechny vazby k Shi. Jejich tajemství teď pro mě nic neznamenají. Klidně se ptej.}
{271}{}{Co mi můžeš říct o támhleté hlídané lodi? }
{272}{}{Zapomeň na to. Hodně štěstí v novém životě, Mengu.}
{280}{}{Shi tu loď používají, aby se dostali k našemu spícímu strážci, ponorce.}
{281}{}{Co víš o té ponorce?}
{290}{}{Shi-Huang-Ti je ponorka, ve které sem připluli naši předci z daleka. Následkem Velké Války ztratila pohon a uvízla na mělčině v San Franciském zálivu. Kapitán Ye Li a jeho posádka se pak dostali do tohoto města a založili to, z čeho se stala společnost Shi.}
{291}{}{Zmínil ses o ní jako o "spícím strážci". Co jsi tím myslel?}
{300}{}{Podobně jako spící drak, jehož nozdry stále můžou chrlit smrtelný oheň, tak i ponorka není bezbranná i přesto, že se nemůže hýbat. Shi vyráželi potají k ponorce pod rouškou noci a pracovali na ní. Její zbraně byly znovu aktivovány a je téměř jisté, že dokáže zničit jakékoliv nečínské plavidlo, které se opováží proplout zálivem.}
{301}{}{No, řekněme čistě "hypoteticky", že by se ten velký tanker pokusil vyplout...}
{310}{}{Potom... BUM!}
{311}{}{Chápu. Asi netušíš, jak ty zbraně deaktivovat, že?}
{320}{}{Takové věci vědí jen technici Shi. Řekl jsem ti všechno, co vím.}
{321}{}{Díky, Mengu. Hodně štěstí v novém životě.}
{330}{}{Je načase začít nový...}
{350}{}{Nech mě na pokoji, lao wai.}
{400}{}{Podařilo se ti přesvědčit Menga, aby začal nový život.}
