{100}{}{Vidíš stráž ve volnějším oblečení. Vypadá ostražitě, ale zároveň znuděně.}
{101}{}{Vidíš přístavního stráž. Je neobvykle dobře ozbrojen.}
{102}{}{Vidíš stráž motorové lodi.}
{150}{}{Hej! Jdi od toho!}
{151}{}{Ani na to nemysli. Tohle je poslední varování.}
{152}{}{Varoval jsem tě, lao wai, teď chcípneš!}
{200}{}{Co chceš, lao wai?}
{201}{}{Zase ty? Co chceš, lao wai?}
{202}{}{Co tady hlídáš?}
{203}{}{Chci si půjčit tu motorovou loď.}
{204}{}{Nic. Nashle.}
{210}{}{Všechno. Nezkoušej žádné blbosti.}
{211}{}{Nemohl bys to trošku upřesnit?}
{220}{}{Ne. Teď odejdi, cizinče.}
{221}{}{Tak dobře. Nashle.}
{222}{}{Nikdo mi nebude řikat co mám dělat. Jseš kurva mrtvej!}
{230}{}{A já chci, abys šel do prdele. Nemáš povolení tu loď používat. Sakra, vždyť ty ani nejseš Shi, jseš lao wai.}
{231}{}{Poslouchej, jsem v zoufalé situaci. Když mi tu loď nepůjčíš, tak může celý můj kmen zemřít. Zrovna teď jsou všichni v zajetí těch bastardů z Enklávy a počítají s tím, že je zachráním. Ale k tomu nutně potřebuju tady tuhle loď. Když mi ji nepůjčíš, budu muset použít násilí a jeden z nás nakonec zemře. Prosím, nenech to zajít tak daleko.}
{232}{}{Ve skutečnosti jsem čestný člen Shi. Najali mě do týmu údržby ponorky díky mým odborným znalostem v oblasti... ponorkologie. Tady je moje heslo...}
{233}{}{Asi si neuvědomuješ, koho jsi právě urazil. Čas chcípnout, kreténe.}
{234}{}{No jo, už jdu... Ježiš, některý lidi...}
{240}{}{(Dlouze se na tebe dívá a poté si povzdechne.) Podívej, na tuhle loď se nikdo bez správného hesla nedostane. Jako to, co jsi mi právě řekl. (Zamumlá.) Ken Lee mi za tohle utrhne hlavu...}
{241}{}{Díky, kamaráde. A neboj, nikomu nic neřeknu.}
{250}{}{To doufám, v zájmu nás obou... dej mi vědět, až budeš chtít odplout. Ale nemůžeš s sebou nikoho vzít, vzbudilo by to podezření. Budeš muset jít jen ty.}
{251}{}{Chci odplout hned teď.}
{252}{}{Teď ne.}
{260}{}{(Stráž si poslechne heslo a přikývne.) Myslím, že jsi opravdu technik. Hmm, Shi musí být opravdu zoufalí, když najímají i cizince... ale stejně jsi tu brzo. Oni ti neřekli, že tým techniků neodplouvá z přístavu dřív než před půlnocí? Jestli chceš, můžeš tady na ně počkat.}
{261}{}{Nemám teď nic lepšího na práci, takže jo...}
{262}{}{Přijdu později.}
{270}{}{Použij vyvazovací pacholi a slez po provazu do lodi. Ale ať ti to netrvá moc dlouho, nechci se dostat do nějakého průšvihu.}
{271}{}{Rozumím. Nashle.}
{272}{}{Spolehni se. Sbohem.}
{280}{}{Jsi připraven se přidat k týmu techniků?}
{281}{}{Ano, jsem připraven vyrazit.}
{282}{}{Ne, ještě ne.}
{290}{}{Nevidíš, že mám práci?}
{300}{}{Já jet na železná rybo-ryba?}
{310}{}{(Dívá se na tebe jako na to nejpitomější stvoření, které si dokáže představit. Nevěřícně zakroutí hlavou.) Ty nejet na železné rybo-rybě. Ty teď odejít nebo já střílet. Rozumíš?}
{311}{}{Dobže! Pápá!}
{312}{}{Ty hnusná chlap. Já bacit hnusná chlap!}
{500}{}{Díky tvým řečnickým schopnostem se ti podařilo získat přístup na motorovou loď.}
