{100}{}{Vidíš seschlého starého mue v bílém pracovním plášti.}
{101}{}{To je Dr. Fung.}
{102}{}{Vidíš seschlého starého mue v bílém pracovním plášti.}
{103}{}{Mohu vám s nìèím pomoci?}
{104}{}{Auvej! Jau! Auuuu!}
{105}{}{Jo... mám zranìní a vy vypadáte jako doktor.}
{106}{}{Ano. Potøebuju doktora pro mého pøítele.}
{107}{}{Nemáte nìjaké Stimpaky? Chci si nìjaké koupit.}
{108}{}{Kdo jsi?}
{109}{}{Mám pøítele, kterému chybí slezina. Mùete mu pomoct?}
{110}{}{Co mi mùeš øíct o tomto místì?}
{111}{}{Nashle.}
{112}{}{Ukate, podívám se na to. Hmm... ano. Budete mi muset zaplatit, samozøejmì.}
{113}{}{Kolik za to?}
{114}{}{Zapomeò na to.}
{115}{}{Mohu ho vyléèit... samozøejmì za peníze.}
{116}{}{Kolik za to?}
{117}{}{Zapomeò na to.}
{118}{}{Kdo jsem? Jsem Dr. Fung. Uèím a léèím.}
{119}{}{Dr. Fung? Znáte Doc Hollidaye?}
{120}{}{Tìší mì. Potøebuju vyléèit.}
{121}{}{Mùj pøítel potøebuje uzdravit.}
{122}{}{Aha. Díky. Nashle.}
{123}{}{Hollidaye? Ano! To já ho všechno nauèil! Kde je teï?}
{124}{}{ije v Broken Hills.}
{125}{}{Vrátil se domù, e? Doufám, e tam našel klid.}
{126}{}{Myslím, e ano. Mám další otázky.}
{127}{}{Nejspíš. U musím jít. Nashle.}
{128}{}{Bude vás to stát $100.}
{129}{}{Zaplatím.}
{130}{}{Zapomeò na to.}
{131}{}{Tohle vypadá vánì. Bude to stát $200.}
{132}{}{Zaplatím.}
{133}{}{Zapomeò na to.}
{134}{}{To jsou opravdu rozsáhlá zranìní. $300 bude staèit na zaplacení mıch slueb.}
{135}{}{Zaplatím.}
{136}{}{Zapomeò na to.}
{137}{}{Obávám se, e za takové zranìní budu muset poadovat $400.}
{138}{}{Zaplatím.}
{139}{}{Zapomeò na to.}
{140}{}{Radìji se posaïte. Budete to potøebovat, a uslyšíte èástku, kterou poaduji. Zmrzaèené konèetiny stojí $600.}
{141}{}{Zaplatím.}
{142}{}{Zapomeò na to.}
{158}{}{Coe? Vy nemáte peníze? Z èeho myslíte, e budu ít, kdy po mnì poadujete práci zadarmo?}
{159}{}{Máte Stimpaky?}
{160}{}{Ne, díky.}
{161}{}{Bylo mi potìšením s vámi obchodovat.}
{162}{}{Díky.}
{163}{}{Bohuel vaše nabídka není pøijatelná.}
{164}{}{A co tohle?}
{165}{}{Víc nabídnout nemùu. Sbohem.}
{166}{}{Máte zranìní? Ts, ts, ts. Starovìkı léèebnı prostøedek to vyléèí. }
{167}{}{Dobøe!}
{168}{}{}
{169}{}{Hotovo. Teï jdìte a buïte opatrnı!}
{170}{}{Díky!}
{171}{}{Ještì nìco?}
{172}{}{Potøebuju uzdravit.}
{173}{}{Mám pøítele, kterı potøebuje uzdravit.}
{174}{}{Kdo jsi?}
{175}{}{Povìz mi nìco o tomhle místì.}
{176}{}{Mám pøítele, kterému chybí slezina. Mùete mu pomoct?}
{177}{}{Ne, ale kadopádnì díky.}
{178}{}{Tak to jste na správném místì. Chcete radìji slyšet dlouhı pøíbìh nebo ten krátkı?}
{179}{}{Dlouhı.}
{180}{}{Krátkı.}
{181}{}{ádnı. Mám další otázky.}
{182}{}{Naši lidé sem pøipluli na ponorce Shih-huang-ti, kdy rakety vybuchly po celém svìtì. Za pomoci kultu jsme poté my, Shi, opìt postavili San Francisco. Taková je zkrácená verze.}
{183}{}{A jak zní ta dlouhá verze?}
{184}{}{Díky. Mám další otázky.}
{185}{}{Díky.}
{186}{}{Dlouhá verze zní takto: Jsme tady, protoe naši lidé jsou potomci posádky atomové ponorky, jen se nazıvá Shih-huang-ti. Kdy støely dopadly bìhem Velké Potopy, systémy vnì ponorky se porouchaly a my jsme byli unášeni po mnoho dní neznámo kam.}
{187}{}{[Více]}
{188}{}{Nakonec jsme se dostali na bøeh poblí ruin San Francisca. Vìtšina mìsta byla znièena válkou. Museli jsme znovu vybudovat základy spoleènosti zaloené pouze na nìkolika lidech, kteøí pøeili a dobelhali se zpìt do mìsta.}
{189}{}{[Více]}
{190}{}{Stavìli jsme z materiálu, kterı jsme mìli po ruce a díky vìdcùm a technologiím, které by nám mohl závidìt celı svìt, budujeme novou civilizaci, ale ne takovou, jakou pøed námi vytvoøil ten šílenı Vùdce.}
{191}{}{Chápu. Mám další otázky.}
{192}{}{Dík. Naskle.}
{193}{}{Samozøejmì e ano. A ponìvad znáte Doc Hollidaye... udìlám to èistì z pøátelství. Øeknìte svému kamarádovi bez sleziny, a sem pøijde a já mu ji dám zpìt.}
{194}{}{Díky! Mám další otázky.}
{195}{}{Díky!}
{196}{}{Ano, to bych mohl. Bude vás to ale stát $1000 dolarù. Pøedem. Pøijímáte?}
{197}{}{Ano.}
{198}{}{Ne.}
{199}{}{Øeknìte vašemu kamarádovi, a sem pøijde a já mu ji dám zpìt.}
{200}{}{Díky. Mám další otázky.}
{201}{}{Díky.}
{202}{}{Nemohu pro nìj nic udìlat, dokud nedáte dohromady $1000. Mìjte se.}
{203}{}{Hezkı den.}
{204}{}{Neošetøuji nepøátele mıch lidí. Omlouvám se.}
{205}{}{Velectìnı pane, doporuèuji vám najít vašeho kultovního léèitele.}
{206}{}{Co mi mùete øíct o implantátech?}
{207}{}{Publikoval jsem nìkolik èlánkù o implantátech. Jsou zapotøebí jen mé znalosti a vaše materiály. Jakı druh implantátu si pøejete?}
{208}{}{Jaké druhy existují?}
{209}{}{Podkoní implantáty.}
{210}{}{Zesílené podkoní implantáty.}
{211}{}{Phoenix implantáty.}
{212}{}{Zesílené Phoenix implantáty.}
{213}{}{Eh... zapomeòte na to. Mám další otázky.}
{214}{}{Vlastnì ádnı. Nashle.}
{215}{}{Máme podkoní implantáty, které chrání pøed fyzickım poškozením. Pokud se vám to zamlouvá, mùeme vám dát tento implantát v jednoduchém i vylepšeném provedení. Dále máme Phoenix implantáty, které chrání pøed árem. Ty samozøejmì mohou bıt také ještì vylepšeny. Pokud vás zajímají jenom vylepšení, budete si muset poèkat na to, a budete mít nainstalovanı jeden ze základních implantátù. A ještì ne se zeptáte... ano, MUETE mít všechny ètyøi operace.}
{216}{}{Super. Vezmu si podkoní implantáty.}
{217}{}{Chci podkoní implantáty.}
{218}{}{Dejte mi zesílené podkoní implantáty.}
{219}{}{Vezmu si Phoenix implantáty.}
{220}{}{Èas pro zesílené Phoenix implantáty.}
{221}{}{Eh... zapomeòte na to. Mám další otázky.}
{222}{}{Vlastnì ádnı. Nashle.}
{223}{}{Vıbornì. Budu potøebovat jednu kevlarovou zbroj a také $5500. No a vy budete potøebovat dva dny na zotavení a schopnost neškrábat si strupy.}
{224}{}{Pojïme na to.}
{225}{}{Zapomeòte na to. Sbohem.}
{226}{}{Zesílené podkoní implantáty, jo? To vás bude stát nìkolik dní vašeho ivota, $33000, kevlarovou zbroj a nìkolik jizev, které vám u nikdy nezmizí.}
{227}{}{No a? Tohle VŠECHNO si mùu dovolit.}
{228}{}{Hmm. Myslím, e tolik za to zaplatit nechci. Sbohem.}
{229}{}{Jestli vám nevadí, e pøijdete o $8500, nìkolik dní ivota a kevlarovou zbroj, mùeme hned zaèít.}
{230}{}{Do toho, doktore. Jsem pøipravenı.}
{231}{}{To je trochu moc. Ještì se vrátím.}
{232}{}{To je veliká operace. Bude vás to stát váš "hezkı vzhled", kevlarovou zbroj a $49000. Opravdu to chcete podstoupit?}
{233}{}{Jo. Pojïme na to.}
{234}{}{Páni. To je... drahé. Ještì se vrátím.}
{235}{}{::potøásá hlavou:: Nehrajte si se mnou. Schází vám dùleité souèásti. Pøíštì mì poøádnì poslouchejte. Teï jdìte a vrate se, a vám budu moci pomoct.}
{236}{}{Dobøe.}
{237}{}{Tady jste! Jste... vylepšen. Pamatujte... neškrábejte si strupy, pokud nechcete, aby vám na tìle zùstaly ohavné jizvy.}
{238}{}{Díky, doktore. Sbohem.}
{239}{}{Mám ty peníze na slezinu.}
{240}{}{Opìt se zajímáte o implantáty?}
