{100}{}{Vidíš nadšeného Shi.}
{101}{}{Vidíš Mai Da Chianga, majitele Červených 888 Zbraní.}
{102}{}{Vidíš baculatého Shi, který vypadá, že neustále pracuje.}
{103}{}{Ahoj! Vítej u Červených 888 Zbraní! Jsem Mai Da Chiang, majitel tohoto podniku. Jak ti můžu pomoct?}
{104}{}{Grokken di ma!}
{105}{}{Já koupit!}
{106}{}{Hledám nějaké zbraně.}
{107}{}{Pověz mi o tomhle místě.}
{108}{}{Zapomeň na to.}
{109}{}{Lituju! Nemluvím tvojí řečí! Měj se hezky!}
{110}{}{Rrr?}
{111}{}{Á, tak zbraně, jo? No, mám tohle.}
{112}{}{[Více]}
{113}{}{Skvělé, skvělé. Díky za obchod. Přijď zas!}
{114}{}{Další otázky!}
{115}{}{Nashle!}
{116}{}{Ne, to není dost dobré. Lituju. Možná něco jiného?}
{117}{}{Další otázky.}
{118}{}{Ne. Nashle.}
{119}{}{Potřebuješ ještě něco?}
{120}{}{Já koupit!}
{121}{}{Ne. Nashle.}
{122}{}{Hledám nějaké zbraně.}
{123}{}{Pověz mi o tomhle místě.}
{124}{}{Zapomeň na to.}
{125}{}{Žijeme tu už spoustu let, ale ne vždy jsme tady žili. Dr. Fung zná úplnou historii. Vsadím se, že tě zajímá co děláme teď.}
{126}{}{Jo.}
{127}{}{Ne, ve skutečnosti chci znát historii. Půjdu najít Funga. Zatím.}
{128}{}{Teď jsme převážně rybáři a vědci. Naši rybáři chytají ryby a naši vědci pracují na projektu, o němž prohlašují, že změní svět.}
{129}{}{Změní svět? Jak?}
{130}{}{Co se ještě děje ve městě?}
{131}{}{Hmm. Zajímavé. Mám další otázky.}
{132}{}{Dík. Měj se.}
{133}{}{To nevím. Oni svoje tajemství nevyzrazují.}
{134}{}{Aha. Co se ještě děje ve městě?}
{135}{}{Chápu. Mám další otázky.}
{136}{}{Dík. Měj se.}
{137}{}{Máme tu dva rivaly ve válečných uměních. Jsou to Lo Pan, člověk zamilovaný sám do sebe, a Dragon, který miluje ostatní. Říká se, že kdo zvítězí, ten rozhodne o budoucnosti válečných umění.}
{138}{}{Aha. Co se ještě děje ve městě?}
{139}{}{Chápu. Mám další otázky.}
{140}{}{Díky.}
{141}{}{Je tu gang tuláků, kteří se přestěhovali do tankeru Poseidon Oil v přístavu. Uvnitř žily nějaké příšery, ale tuláci je zavřeli do nižšího podpalubí. A ačkoliv jsou to cizinci, jsme jim za to vděční.}
{142}{}{Nějaké jiné novinky?}
{143}{}{Chápu. Mám další otázky.}
{144}{}{Dík. Měj se.}
{145}{}{Vědci tvrdí, že se někdo dostal přes jejich počítačovou ochranu a ukradl jejich tajemství.}
{146}{}{Nějaké jiné novinky?}
{147}{}{Chápu. Mám další otázky.}
{148}{}{Dík. Měj se.}
{149}{}{Na nic dalšího si momentálně nevzpomínám. Měj se.}
{150}{}{Hezký den.}
{151}{}{Jsi zloděj, vrah a ničema. Obávám se, že tě budu muset zabít.}
{152}{}{Čekat...}
