{100}{}{Vidíš inspirující pár vyznávající fyzické a psychické zdraví.}
{101}{}{Vidíš Juana Cruze a Vikki Goldmanovou, dvě velice známé filmové hvězdy z New Rena.}
{102}{}{Vidíš tmavovlasého muže a blonďatou ženu. Oba jsou velmi atraktivní. Vyzařují ze sebe neodolatelné charisma.}
{103}{}{On: Ahoj! Já jsem Juan Cruz! Ona: A já Vikki Goldmanová! Oba: Jsme celebrity! A oba dva schvalujeme Hubologii! Oba: Pamatuj prosím, že jakákoliv podobnost mezi námi, lidmi nebo institucemi, ať už živými nebo mrtvými, je čistě náhodná.}
{104}{}{He? Klus? Vykid?}
{105}{}{Celebrity? Co z vás dělá celebrity?}
{106}{}{Podobnost? Co tím myslíte?}
{107}{}{Chci být Hubologista. Jak se k vám můžu přidat?}
{108}{}{Poslyš, Vikki, Dave H. tě miluje.}
{109}{}{Paráda. Už musím jít.}
{110}{}{On: Ubohé dítě pustiny. Ona: Nepomohlo by třeba srovnání? On: Ano. Ty. Chceš podstoupit srovnání?}
{111}{}{Jo!}
{112}{}{Ne!}
{113}{}{Ona: Doufám, že to pomohlo. Hodně štěstí na cestách!}
{114}{}{Ahoj!}
{115}{}{Opravdu to pomohlo!}
{116}{}{On: Pokud nechceš přijmout naši pomoc... Ona: ...pak ti nemůžeme pomoci. Sbohem.}
{117}{}{Nashle!}
{118}{}{On: Vidíš? Vědomosti Hubu opět předvedly svoji cenu!}
{119}{}{Mám nějaké otázky.}
{120}{}{Diky! Nashle!}
{121}{}{Ona: Byli jsme součástí filmového průmyslu v New Renu. Natočili jsme stovky filmů, z nichž se mnohé staly klasiky, jako třeba "Top Bun," "Pikantní Podnik," a "Bouřlivé Sny". Díky tomu jsme celebrity.}
{122}{}{On: Ale jakožto člen tohoto průmyslu to jistě víš.}
{123}{}{Konečně si můžu spojit jména s tvářemi.}
{124}{}{Koho zajímá, že se k nim HLÁSÍTE? Copak nemůžu učinit vlastní rozhodnutí?}
{125}{}{Aha. Mám na vás další otázky.}
{126}{}{Díky, nashle.}
{127}{}{Ona: Ale ano, samozřejmě že můžeš učinit vlastní rozhodnutí. On: A v Hubově poslední knize se můžeš dočíst, jak učinit to PRAVÉ rozhodnutí!}
{128}{}{V jeho poslední knize? On není mrtvý?}
{129}{}{"Pravé rozhodnutí?" No jasně. A co třeba svobodná vůle?}
{130}{}{To zní skvěle. Jak se k vám můžu přidat?}
{131}{}{Jistě. Mám další otázky.}
{132}{}{Jasně. Nashle.}
{133}{}{On: Další otázky? V tom případě máme odpovědi! Samozřejmě poskytnuté Velkým Kolem.}
{134}{}{Jak se k vám můžu přidat?}
{135}{}{Co z vás dělá celebrity?}
{136}{}{Copak nemůžu učinit vlastní rozhodnutí místo toho, aby za mě rozhodovali celebrity?}
{137}{}{Jak se k vám můžu přidat?}
{138}{}{Poslyš, Vikki, Dave H. tě miluje.}
{139}{}{Ne, žádné další otázky.}
{140}{}{Ona: (Prázdný chladný pohled.) On: Děkujeme ti.}
{141}{}{Eh... mám nějaké otázky.}
{142}{}{To bude ode mě všechno! Zatím!}
{143}{}{On: Mrtvý? Hehe! Možná. My si ale myslíme, že srovnal všechny svoje neurodyny a šel následovat Hvězdného Otce. Ona: Intenzivně využíváme jeho poznámky na papírcích a stěží čitelné rukopisy, abychom šířili Hubova slova. On: Například jsme našli útržek, na kterém se píše: "2 tucty vejcí/mléko/toaleťák". To jsou očividně významná slova. Lid se o tom musí dozvědět.}
{144}{}{Eh... jasně. Mám další otázky.}
{145}{}{Jenom proto, že si nějaký magor něco poznamenal, tak cítíte potřebu VŠECHNO zveřejnit?}
{146}{}{Ano! Ať žije Hub! Vidím světlo! Jak se k vám můžu přidat?}
{147}{}{Jasně. Nashle.}
{148}{}{On: Ano. Někteří si mohou myslet, že se podobáme jistým lidem. Ona: Ale pravdou je, že je to jen čistě náhoda.}
{149}{}{Ach tak. No, tím se všechno vysvětluje. Poslyšte, mám další otázky.}
{150}{}{Chápu. Zatím.}
{151}{}{Ona: Samozřejmě že máš svou svobodnou vůli. Máš možnost nechat své neurodyny naplnit špínou světa. On: Máš volbu žít bezradostně a bezvýznamně jako krysa. Oba: Nebo se můžeš dozvědět o smyslu života díky Velkému Kolu.}
{152}{}{Neurodyny? Co jsou zač?}
{153}{}{To zní skvěle. Jak se k vám můžu přidat?}
{154}{}{Hmm. Myslím, že budu raději žít jako krysa.}
{155}{}{Jasně. No, už musím běžet.}
{156}{}{Ona: Ty se opovažuješ nazývat Huba (Ať žije jeho vize.) magorem? Tady? V pevnosti oddané jeho učení? On: Vypadni odsud. Jestli s někým odsud po cestě promluvíš, nebudeme mít slitování. Nevěřící. Oba: O dalšího nevěřícího méně.}
{157}{}{V tom případě udělám první krok já. Vždycky jsem totiž nenáviděl vaše filmy. Uvidíme, jak umíte zahrát mrtvé scény.}
{158}{}{Vaše filmy jsou pěknej brak. Nashle.}
{159}{}{Nashle.}
{160}{}{Ona: Neurodyny jsou podstatou duší zničených ve Velké Válce, které znečišťují tvou duševní podstatu a snaží se tě svést z cesty. On: Jestli chceš vědět více o naší výuce, budeš muset navštívit náš kostel.}
{161}{}{Ano, to zní úžasně.}
{162}{}{Slyšel jsem, že je tohle jen sci-fi, ale nevěděl jsem jak moc. Hub musel být opravdu magor.}
{163}{}{No, opravdu mě moc zajímá, co se naučím. Počítejte se mnou.}
{164}{}{Hmm. Ne, teď ne. Ale mám další otázky.}
{165}{}{Eh... musím jít. Nashle.}
{166}{}{On: To je od tebe velmi pozitivní myšlení. Ona: Velmi osvícené. On: Nabízíme naše názory lidem... a pokud naše sláva přitáhne více věřících, milerádi toho využijeme.}
{167}{}{Mám další otázky.}
{168}{}{Chci se k vám přidat.}
{169}{}{Chápu. No, zatím.}
{170}{}{On: No, to je velmi prosté. Dáme ti tento informační holodisk. Ona: ...podíváš se na krátký film... On: ...a poté si půjdeš promluvit s AHS-7! Ona: Snadné, že ano?}
{171}{}{Pojďme na to.}
{172}{}{Myslím, že na to nejsem připraven.}
{173}{}{Ona: Na to máš samozřejmě právo. On: A já doufám, že pochopíš, že se nemůžeš potulovat po naší základně. Ona: Takže raději odejdi... stráže tě pravděpodobně zastřelí, pokud se tu budeš poflakovat.}
{174}{}{No páni, díky moc. Nejdřív dostanu nabídku k přijetí a když odmítnu, tak mě zastřelíte? To se vám teda povedlo.}
{175}{}{V tom případě nejdřív zastřelím já vás.}
{176}{}{Padám odsud.}
{177}{}{On: Toto je tvá poslední šance změnit své rozhodnutí. Ona: Nechceme, aby se ti stalo něco zlého.}
{178}{}{Jdi se vycpat.}
{179}{}{Fajn. Jak se k vám můžu přidat?}
{180}{}{Něco zlého se brzy stane VÁM.}
{181}{}{Ne. Myslím, že to risknu. Zatím.}
{182}{}{On: Udělali jsme pro tebe vše, co jsme mohli. Ona: Hodně štěstí na cestách.}
{183}{}{Nashle!}
{184}{}{Ona: Dave? Ten počítačový geek? On: Haha! Taková nicka! Vikki je moje, jen moje... v žádném případě se... promiň, čelím negativní energii. Mám nejspíš znečištěné neurodyny. Ona: (Šeptá ti.) Myslím, že je Dave roztomilý, ale nic s ním nemůžu mít, když je Juan poblíž. On: Uf. Neurodyny už jsou zase čisté.}
{185}{}{Dobře, mám další otázky.}
{186}{}{To už bude všechno. Nashle.}
{187}{}{Ona: Nebylo to až tak zlé, že ne? On: Teď si jdi promluvit s AHS-7 a poté se z nás stanou soudruzi v Hubologii. Ona: Jsem tak vzrušená! On: Získávání nových rekrutů mě vždycky vzruší. Ona: Ach, miláčku... On: Ach, zlato...}
{188}{}{Asi se vrátím později.}
{189}{}{On: Příliš pozdě. Ona: Už jsi zavázaný.}
{190}{}{[KONEC]}
{191}{}{On: Udělal jsi životní rozhodnutí. Ona: A bohužel to bylo špatné rozhodnutí. Oba: Stráže! Stráže!}
{192}{}{Zatraceně.}
{193}{}{On: Zdravím, }
{194}{}{Takže co mám teď jako Hubologista dělat?}
{195}{}{Můžu s vámi někdy něco podniknout?}
{196}{}{To bude nejspíš všechno. Zatím!}
{197}{}{}
{198}{}{}
{199}{}{On: Můžeš si promluvit s Harry Rocketem na povrchu. Třeba potřebuje nějakou pomoc. Ona: Nebo si promluv s AHS-7 nebo AHS-9. Ti většinou o něčem vědí. On: Nebo můžeš sledovat vysílání modliteb. Ona: Nebo můžeš způsobit rozbroje mezi nepřáteli Kola.}
{200}{}{Díky. Můžu s vámi někdy něco podniknout?}
{201}{}{Díky. To bude nejspíš všechno.}
{202}{}{Ona: Je nám líto... protože Hvězdný Otec ví, že jsi roztomilý... ale nejspíš to nepůjde. On: Ale lichotíš nám! Ona: Možná bychom někdy mohli jít do New Rena a natočit spolu film.}
{203}{}{Aha, tak dobře. Co jiného můžu jako Hubologista dělat?}
{204}{}{Aha, tak dobře. Zatím.}
{205}{}{Ona: Lhaní je pro tvé neurodyny špatné. On: To je pravda. Ona: A proto musím být upřímná a říct ti, že nejsi přitažlivý. On: Ale i přesto tě milujeme jako kamaráda a následovníka Hubu!}
{206}{}{Páni, díky. Takže co jiného můžu jako Hubologista dělat?}
{207}{}{Jo, jasně. [Zamumlat] Kreténi.}
{208}{}{Vítejte, noví rekruti!}
{209}{}{Já jsem Vikki Goldmanová!}
{210}{}{A já Juan Cruz!}
{211}{}{Jsme celebrity, jak jistě víte.}
{212}{}{Myslíme si, že je Hubologie cestou budoucnosti.}
{213}{}{My VÍME, že je Hubologie cestou budoucnosti.}
{214}{}{Dokážu usmažit brouky pouhou myšlenkou!}
{215}{}{Vypadám ve staniolové čepici opravdu dobře!}
{216}{}{Možná, když budete tvrdě pracovat na optimalizaci svého ducha, budete se k nám moci přidat.}
{217}{}{To bychom uvítali.}
{218}{}{Ano. Neustále hledáme přátele...}
{219}{}{...pokud jsou ochotni optimalizovat svého ducha.}
{220}{}{A pokud jsou natolik vysoce postavení jako my.}
{221}{}{Jsme AHS-5.}
{222}{}{Jednoho dne z vás může být také AHS-5.}
{223}{}{Když přispějete hodně peněz, můžete být AHS-5 ještě dříve.}
{224}{}{Ale nemyslete si, že vás chceme jen pro peníze.}
{225}{}{Ne, my vám chceme POMOCI.}
{226}{}{A o tom všem je Hubologie.}
{227}{}{[Potlesk]}
{228}{}{. Doufám, že jde tvé osvícení dobře. Ona: Vkládáme do tebe... veliké... naděje.}
{229}{}{Lekce 1: Zde je věčnost, naše Velké Kolo. (Na něco ukáže.) A tady jsme my. (Na něco ukáže.) Nyní jen musíme urazit dlouhou cestu, abychom se mohli setkat s našimi hvězdnými bratry.}
{230}{}{Sakra, tak to budeme potřebovat opravdu hodně bot.}
{231}{}{On: Teď si jdi promluvit s AHS-7 a poté se z nás stanou soudruzi v Hubologii! Ona: Jsem tak vzrušená! On: Získávání nových rekrutů mě vždycky vzruší. Ona: Ach, miláčku... On: Ach, zlato...}
