{100}{}{Vidíš přátelsky vypadajícího pankáče.}
{101}{}{Vidíš Marca.}
{102}{}{Vidíš přátelsky vypadajícího pankáče.}
{103}{}{Ty zkurvysyne... jak jsi nám to mohl udělat?}
{104}{}{Co pro tebe můžu udělat, mama-jamma?}
{105}{}{Co ti můžu udělat, mama-jamma?}
{106}{}{Och! Och! Ach!}
{107}{}{Kdo jsi?}
{108}{}{Co je tohle za místo?}
{109}{}{Kdo to tu řídí?}
{110}{}{Nic. Nashle.}
{111}{}{Hmm. Promiň, ale s tímhle ti nepomůžu. Zkus se zeptat někoho jinýho.}
{112}{}{Dík?}
{113}{}{Jmenuju se Marc. Jsem místní chytrák a vím úplně všecko. ::usmívá se::}
{114}{}{Aha. Mám další otázky.}
{115}{}{Nashle.}
{116}{}{Tohle je Poseidon Marine Vessel Valdez - známej taky jako PMV Valdez. Jestli chceš o něm vědět víc, tak se jdi zeptat kapitána.}
{117}{}{Kapitán? Kdo to je?}
{118}{}{Mám další otázky.}
{119}{}{Nashle.}
{120}{}{Na starosti? Nemáme žádnýho šéfa.}
{121}{}{Odkud jste všichni přišli?}
{122}{}{V tom případě mám na tebe další otázky.}
{123}{}{Nashle.}
{124}{}{Kapitán je starej drsnej voják. Sedí v horním patře a pozoruje okolí. Hodně toho o týhle lodi ví.}
{125}{}{Díky. Mám další otázky.}
{126}{}{Dík. Měj se.}
{127}{}{No, tak různě. Hodně jsme slyšeli o San Franciscu od našich starších. Někteří tu totiž žili před Velkou válkou. Chceš vědět víc?}
{128}{}{Ano.}
{129}{}{Ne, ale chci se zeptat na něco jiného.}
{130}{}{Ne, to bude všechno.}
{131}{}{Jsme skupina muzikantů, ajťáků, geeků a umělců. Chtěli jsme žít na nějakým místě, který je známý svobodou umění a taky svobodou člověka. Já jsem sem přišel, abych se tu usadil. Pořád chceš vědět víc?}
{132}{}{Ano.}
{133}{}{Ne, ale chci se zeptat na něco jiného.}
{134}{}{Ne, to bude všechno.}
{135}{}{No a když jsme se sem dostali, rozhodli jsme se, že tu budeme kempovat, dokud nezjistíme, jak znovu zprovoznit tenhle tanker, nebo dokud nevymyslíme něco jinýho.}
{136}{}{A přišli jste na to?}
{137}{}{Pověz mi něco o Hubologistech.}
{138}{}{Pověz mi něco o Shi.}
{139}{}{Mám další otázky.}
{140}{}{Dík. Měj se.}
{141}{}{Myslím, že náš kapitán na to přišel... ale nejdřív potřebujem pár věcí. Abych řekl pravdu, už jsme to v podstatě vzdali... máme teď jiný plány.}
{142}{}{Jaké?}
{143}{}{Kde najdu toho kapitána?}
{144}{}{Chci se zeptat na něco jiného.}
{145}{}{Nashle.}
{146}{}{Jsou to blázni. Vůbec jim nevěř... teda pokud nejseš mentálně postiženej nebo máš rád, když tě někdo využívá. Je zajímaj jenom tvý peníze a duše. Kvůli tomu jsou schopný zničit jeden druhýho. Už mockrát jsem viděl, jak se to stalo.}
{147}{}{Přišli jste na to jak zprovoznit tanker?}
{148}{}{Pověz mi něco o Shi.}
{149}{}{Mám další otázky.}
{150}{}{Nashle.}
{151}{}{To jsou dobrý lidi. Sice moc nedůvěřujou cizincům, ale to není až tak špatná vlastnost v týhle době. Maj zvláštní zvyky a mluví srandovně, ale jinak jsou v pohodě.}
{152}{}{Přišli jste na to jak zprovoznit tanker?}
{153}{}{Pověz mi něco o Hubologistech.}
{154}{}{Mám další otázky.}
{155}{}{Nashle.}
{156}{}{Chceš vědět jaký máme plány? Chceme najít místo, který by nebylo postižený lidskou chamtivostí a pak se pokusíme vytvořit lepší společnost.}
{157}{}{A už víte, jak to uděláte?}
{158}{}{Mám další otázky.}
{159}{}{Dík. Měj se.}
{160}{}{Doufáme, že se vyhneme chybám společností. Nemůže to bejt už o moc horší než teď.}
{161}{}{Přišli jste na to jak zprovoznit tanker?}
{162}{}{Pověz mi něco o Hubologistech.}
{163}{}{Pověz mi něco o Shi.}
{164}{}{Mám další otázky.}
{165}{}{Dík. Měj se.}
{166}{}{Neviděl jsi tu někde Badgerovu přítelkyni?}
{167}{}{Myslím, že jsem ji viděl jít dolů. Na severní straně týhle paluby je díra.}
