{100}{}{Vidíš humanoida pokrytého rostlinným porostem. Kape z nìj zelené bahno.}
{101}{}{Vidíš jedno ze stvoøení Dr. Shenga.}
{102}{}{Vidíš jedno ze stvoøení Dr. Shenga. Zdá se, že se pøíliš nepovedlo.}
{200}{}{Promluv si s vùdcem, èlovìèe.}
{201}{}{Z tvého tìla by byl dobrý hostitel...}
{202}{}{Vùdce øíká, že se tì nesmím dotknout... prozatím.}
{300}{}{(Pomalu se k tobì belhá pùl tucet podivných humanoidních tvorù. Jejich vyzáblé výhonky a tìla pokryté mechem vydávají odpudivé èvachtavé zvuky s každým neohrabaným krokem. Vùdèí tvor tì osloví skøehotavým hlasem.) Vùdce chce s tebou mluvit. Pojï s námi, èlovìèe, a nebraò se... nebo z tebe udìláme hostitele.}
{301}{}{[Pokrèit rameny] To bude zajímavé. Jdìte první.}
{302}{}{Nikam s váma nepùjdu, vy rostlinní... tvorové.}
{303}{}{Seru na to, na tohle nemám èas.}
{304}{}{Tak moment, kdo je váš vùdce? A co jste vlastnì zaè?}
{310}{}{Nemáš na výbìr, èlovìèe. Buï pùjdeš s námi a promluvíš si s Vùdcem, nebo se uchýlíme k násilí.}
{311}{}{Tak jdem na vìc.}
{312}{}{Tak dobøe. Setkám se s tím vaším vùdcem.}
{320}{}{Vùdce ti zodpoví veškeré otázky. A teï pojï.}
{321}{}{Ne-e!}
{322}{}{Tak dobøe. Setkám se s tím vaším vùdcem.}
{400}{}{Uuuhhhhh...}
{401}{}{Grrraaah!}
{402}{}{Hheesssss...}
{403}{}{Ohhh...}
{410}{}{Vùdce øíká, že nikdo nesmí dovnitø.}
{420}{}{Vùdce øíká, že mùžeš vstoupit, èlovìèe.}
{500}{}{Postøíkáš tvora a ten hlasitì zasténá. Èásti rostlinného porostu z nìj odpadnou na zem.}
{501}{}{Postøíkáš tvora, ten hlasitì zasténá a rozteèe se pøímo pøed tvýma oèima.}
