{100}{}{Vidíš pankáče s napůl vyholenou hlavou.}
{101}{}{Vidíš Ryana, pramen veškeré moudrosti.}
{102}{}{Vidíš nafoukaného a potměšilého pankáče.}
{103}{}{Musíš to vydržet, ty vole.}
{104}{}{Tohle je strašná prdel.}
{105}{}{Udělám tě tak, že budeš krvácet. Pardon, řekl jsem to snad nahlas?}
{106}{}{Aj karamba! Nalgas con queso!}
{107}{}{Héhé héhé héhé!}
{108}{}{Padám odsud.}
{109}{}{Znal jsem Velkýho Ježíše Mordina když byl ještě malej Ježíš.}
{110}{}{Ježíši Kriste Panno Marie!}
{111}{}{Jsem výrobce. Dělám hry. Hry jsou zábava. Zahraj si moje hry.}
{112}{}{Plamenomet na buzny!}
{113}{}{Říkaj mi... LESKLÝ KLADIVO.}
{114}{}{Přišel jsem do San Fran dělat hry a nakopat pár zadků.}
{115}{}{Letní lásky...}
{116}{}{Hola, seňore! Nebo je to seňorita?}
{117}{}{Héhé!}
{118}{}{Ty vole... tohle místo je jak slib ve Stocktonu... samej vítr a žádná akce.}
{119}{}{Můj přítel Scott si myslel, že hlavní město Old California je Stockton. Fakt!}
{120}{}{Chtěl bych se udělat na Chipa.}
{121}{}{Ty vole!}
{122}{}{Ale no ták!}
{123}{}{Nával zlaaaaaaa!}
{124}{}{Fakt mě chceš rozzuřit?}
{125}{}{Jasný, ne?}
{126}{}{Přesně, pane. Hehehe.}
