{100}{}{Vidíš stráž ve volnějším oblečení. Vypadá ostražitě, ale zároveň znuděně.}
{101}{}{Vidíš strážce paláce.}
{102}{}{Vidíš strážce paláce, který drží nebezpečně vypadající zbraň.}
{103}{}{Jdi dál a nic se ti nestane.}
{104}{}{Máš tu něco na práci?}
{105}{}{Dáme si na tebe pozor.}
{106}{}{Nic na nás nezkoušej.}
{107}{}{Chovej se k našim lidem s úctou.}
{108}{}{Nesahej na to. To je poslední varování.}
{109}{}{Ať už tě tady nevidím.}
{110}{}{Ustup, cizinče.}
{111}{}{Pomalu od toho ustup.}
{112}{}{Ať tě to ani nenapadne.}
{113}{}{Přestaň s tím. Hned.}
{114}{}{Chcípni, nepříteli lidu!}
{115}{}{Posílám tě do pekla hořícího kovu!}
{116}{}{Nechť se Buddha slituje nad tvou duší!}
{117}{}{Usmaž se v pekle, nepříteli!}
