{100}{}{Vidíš kupce.}
{101}{}{Vidíš Cala, obchodníka se zbraněmi.}
{102}{}{Vidíš znuděného, ale přátelsky vypadajícího muže.}
{103}{}{Dobrý den, pane. Můžu ti nějak pomoct?}
{104}{}{Dobrý den, paní. Můžu ti nějak pomoct?}
{105}{}{Já chtít informace.}
{106}{}{Co ty mít?}
{107}{}{Ne, já jít.}
{108}{}{Chci nějaké informace.}
{109}{}{Jasně. Ukaž mi co máš.}
{110}{}{Zapomeň na to.}
{111}{}{Neprodávám informace. Jenom zbraně. Chceš vidět moje zboží?}
{112}{}{Ano.}
{113}{}{Ne.}
{114}{}{Myslím, že se ti bude moje zboží líbit. Nemusíš vůbec spěchat.}
{115}{}{Dobře.}
{116}{}{Chceš ještě něco jiného?}
{117}{}{Ano.}
{118}{}{Ne.}
{119}{}{V tom případě ti přeju pěknej den.}
{120}{}{Dobře.}
{121}{}{Vítej zpátky. Chceš ještě něco koupit?}
{122}{}{Ano.}
{123}{}{Ne.}
{124}{}{Je mi líto, ale mám zavřeno. Otvírám okolo osmý hodiny. Jestli budeš něco potřebovat, přijď později.}
{125}{}{Dobře.}
{126}{}{Tobě nic neprodám. Vypadni z mýho obchodu!}
{127}{}{Dobře.}
{128}{}{Doufám, že brzy přijde další zboží.}
