#############################################################
#  Message File: Geckpwpl.msg                               #
#                                                           #
#  Created: September 2, 1998                               #
#                                                           #
#  Updated:                                                 #
#############################################################

{100}{}{Vstupuješ do jaderné elektrárny v Gecku.}
{200}{}{Reaktor byl znièen.}
{300}{}{Robot opravil jadernou elektrárnu.}