{100}{}{Vidíš starce se scvrklou kůží oblečeného v doktorském plášti.}
{101}{}{To je doktor Holliday.}
{102}{}{Vidíš starce se scvrklou kůží oblečeného v lehce zakrváceném doktorském plášti. Vyzařují z něj ohromné vědomosti. Také se zdá, že je trochu nemocný.}
{103}{}{::sípavě:: Vítám tě. Jsem doktor Holliday. Jak ti můžu pomoct?}
{104}{}{Takže co chceš?}
{105}{}{Jauvajs!}
{106}{}{Mám zranění a potřebuju vyléčit.}
{107}{}{Jeden z mých přátel je zraněný a potřebuje vyléčit.}
{108}{}{Co tady děláš?}
{109}{}{Pověz mi něco o tomhle městě.}
{110}{}{Neslyšel jsi nějaké drby?}
{111}{}{Potřebuju nějaké Stimpaky.}
{112}{}{Zapomeň na to. Promiň.}
{113}{}{Ukaž, podívám se na to. Vyléčím tě, ale bude tě to něco stát.}
{114}{}{Kolik za to?}
{115}{}{Zapomeň na to.}
{116}{}{Ano, to se dá vyléčit... ::sípavě:: za malý obnos.}
{117}{}{Kolik za to?}
{118}{}{Zapomeň na to.}
{119}{}{Co tu dělám? Jsi v nemocnici, já mám na sobě doktorský plášť, jsem celý od krve a povalují se tu ostré špičaté věci. Takže buď jsem úspěšný zabiják nebo slušný doktor. Vyber si.}
{120}{}{Asi ti budu říkat doktore.}
{121}{}{Nehraj si na chytrýho, staříku.}
{122}{}{Opravdu dobrý doktor by nebyl celý od krve.}
{123}{}{Tak poslouchej. Před lety jsem se tu narodil. Zrovna se to tu začínalo rozjíždět. Když jsem byl ještě mladý, potloukal jsem se kolem a potkal jsem dívku. Zamiloval jsem se. Po čase onemocněla a zemřela. Po této události jsem se rozhodl být doktorem.}
{124}{}{Opravdu? Pokračuj.}
{125}{}{Měl jsi mluvit o Broken Hills, ne o svém mládí.}
{126}{}{Divil by ses, co dokáží lidé říct, když prožívají bolest.}
{127}{}{Opravdu? Co třeba?}
{128}{}{Už mě to nezajímá. Raději se zeptám na něco jiného.}
{129}{}{Bude to za $50.}
{130}{}{Zaplatím.}
{131}{}{Zapomeň na to.}
{132}{}{Tak tohle zranění tě přijde na $100.}
{133}{}{Zaplatím.}
{134}{}{Zapomeň na to.}
{135}{}{To muselo pěkně bolet. A bude to bolet i tvoji peněženku... $150.}
{136}{}{Zaplatím.}
{137}{}{Zapomeň na to.}
{138}{}{Jau! Tohle nebude tak jednoduché. $200.}
{139}{}{Zaplatím.}
{140}{}{Zapomeň na to.}
{141}{}{Fíha... no, příteli, tohle bude bolet. $300 a bude z tebe nový člověk.}
{142}{}{Zaplatím.}
{143}{}{Zapomeň na to.}
{144}{}{Bude se cítit jako znovuzrozený... ::sípavě:: za směšných $50.}
{145}{}{Zaplatím.}
{146}{}{Zapomeň na to.}
{147}{}{Dostali jste se do pěkné šlamastiky, že? Také jsem byl v mládí horká hlava a pár jich koupil. Tohle neštěstí tě přijde na $100.}
{148}{}{Zaplatím.}
{149}{}{Zapomeň na to.}
{150}{}{Poslyš, dáváš vůbec pozor na svoje přátele? ::zakašlání:: Jestli chceš, abych se o toho kamaráda postaral, tak mi zaplať $150.}
{151}{}{Zaplatím.}
{152}{}{Zapomeň na to.}
{153}{}{Musíš být opravdu dobrý člověk, když jsou tví přátelé tak oddaní. Doufám, že jsi dobrý... protože tě to přijde na ::zakašlání:: $200.}
{154}{}{Zaplatím.}
{155}{}{Zapomeň na to.}
{156}{}{Jau! Na to budu muset dát dlahu nebo něco takového. Mé široké lékařské znalosti tě budou stát $300.}
{157}{}{Zaplatím.}
{158}{}{Zapomeň na to.}
{159}{}{Příteli, nemáš dost peněz. Jestli chceš, prodám ti nějaké Stimpaky, protože s tím, co máš, si toho ode mě víc nekoupíš.}
{160}{}{Dej mi ty Stimpaky.}
{161}{}{Ne, díky.}
{162}{}{Bylo mi potěšením.}
{163}{}{Díky.}
{164}{}{To je nepřijatelné.}
{165}{}{A co tohle?}
{166}{}{Víc nabídnout nemůžu. Sbohem.}
{167}{}{::sípavě:: Máš zranění? Tak ukaž, podívám se na to. Máš nějaké peníze?}
{168}{}{Penis-e?}
{169}{}{Jo!}
{170}{}{Ukaž mi svůj batoh. (Hledá v batohu a něco vytáhne.) Dobře. Bude to teď trochu bolet.}
{171}{}{Bolet?}
{172}{}{Ano. Tak... a je to! Hotovo. Hodně štěstí, ano? Dávej na sebe pozor!}
{173}{}{Díky!}
{174}{}{Přesně tak, jsem doktor. Jsem rád, že jsou v tomhle post-nukleárním světě stále ještě inteligentní bytosti.}
{175}{}{Ha! To říká dědek, kterýmu je 70!}
{176}{}{Hele dědku, stejně si od tebe žádný sračky nevezmu.}
{177}{}{Ehmmm... jasně. Chci se zeptat.}
{178}{}{Nashle.}
{179}{}{Vyhrožovat jedinému doktorovi ve městě není moc dobrý nápad. ::kašle:: Příteli, jestli ode mě něco chceš, tak se mnou mluv slušně. Jinak táhni z týhle nemocnice.}
{180}{}{Polib si, dědku. Připrav se zemřít.}
{181}{}{Jo, jasně.}
{182}{}{Promiň, mám špatný den.}
{183}{}{Byla to jen legrace.}
{184}{}{Ty jeden spratku, máš se ještě hodně co učit ohledně slušného chování.}
{185}{}{Dítě, máš se ještě co učit ohledně humoru.}
{186}{}{Jo, dobře.}
{187}{}{Tak jo, nasral jsi mě. Teď se budeš muset léčit.}
{188}{}{(I přes své brýle jsou v jeho očích vidět záblesky smíchu.) To už dnes moc nikde neuvidíš. Například ta dnešní mládež...}
{189}{}{Hej!}
{190}{}{Dědku, nedráždi mě.}
{191}{}{...má stejné znalosti, jako měli naši staří...}
{192}{}{Jo, jo, jo... už musím jít.}
{193}{}{Klid, dítě, jenom žertuju.}
{194}{}{Jo, já vím. Takže... ehm... }
{195}{}{...mínus to, co vám odmítneme říct, vy malí bastardi! (Dostane záchvat smíchu.) Dítě, až ode mě budeš zase chtít nějaké léčení, máš to zadarmo.}
{196}{}{Chci se ještě na něco zeptat.}
{197}{}{Díky. Uvidíme se později.}
{198}{}{Máš zranění? Tak ukaž, ošetřím tě.}
{199}{}{Umm...}
{200}{}{Díky. Nashle!}
{201}{}{Kdo má zranění? Aha, tak se postavte do řady a já se na vás podívám.}
{202}{}{One more thing...}
{203}{}{Diky! Nashle!}
{204}{}{Překvapivě málo. Promiň, ale když se soustředím na něčí léčbu, nevěnuji obvykle pozornost jeho nejintimnějším tajemstvím.}
{205}{}{Aha. Můžu se ještě na něco zeptat?}
{206}{}{Poté jsem odešel do San Francisca a tam jsem začal studovat medicínu v Čínské čtvrti u pana Funga, který mě naučil všemu, co o medicíně vím. A naučil mě i některá moudra.}
{207}{}{Co se stalo potom?}
{208}{}{A jak to souvisí s Broken Hills?}
{209}{}{Počkej, k tomu se teprve dostaneme! Vy mladí jste tak netrpěliví.}
{210}{}{Promiň, pokračuj.}
{211}{}{Tohle je na prd. Odcházím.}
{212}{}{Potom jsem se sem vrátil a sledoval jsem Marcuse, jak z několika chatrčí, které si pamatuji ještě z mládí, vybudoval "rozlehlou metropoli", kterou teď vidíš před sebou. Viděl jsem, jak sem přicházejí lidé s vidinou bohatství a viděl jsem, jak lidé dospívají a umírají. Znám celou historii města.}
{213}{}{Takže to znamená...}
{214}{}{To znamená, že mnoho nových lidí už ani neznám. Většina z toho už jsou jen... vzpomínky.}
{215}{}{Aha. No, díky za příběh.}
{216}{}{Ty kreténe! Nechal jsi mě čekat tak dlouho jen tak pro nic?}
{217}{}{Ne. Já díky za vyslechnutí mých blábolů. Příště, až budeš chtít vyléčit, budeš to mít zadarmo.}
{218}{}{Díky! Takže...}
{219}{}{Díky. Sbohem!}
{220}{}{Jo. Doufám, že to stálo za to! (Zlomyslně se usměje.)}
{221}{}{Ne, ani ne. Pověz mi ještě o něčem.}
{222}{}{Ne, ty starý seschlý kreténe. Nashle.}
{300}{}{Kdo potřebuje uzdravit?}
{301}{}{Vic.}
{302}{}{Myron.}
{303}{}{Marcus.}
{304}{}{Cassidy.}
{305}{}{Sulik.}
{306}{}{Lenny.}
{307}{}{Kyberpes.}
{308}{}{Doktor.}
{309}{}{Goris.}
{310}{}{Davin.}
{311}{}{Miria.}
{312}{}{Skynet.}
{313}{}{Zapomeň na to.}
{314}{}{Máš zranění? Ukaž, podívám se na to a na tvé přátele taky.}
{315}{}{Tak, hotovo. Už by to mělo být lepší.}
{316}{}{[Pokračovat]}
{400}{}{Dogmeat.}
{401}{}{K-9.}
{402}{}{Kitsune.}
{403}{}{Dex.}
{404}{}{Kocour Jules.}
