{100}{}{Vidíš počítačovou konzoli elektrárny.}
{101}{}{Tato konzole se používá k regulaci a směrování toku energie v Broken Hills.}
{102}{}{Raději na to bezdůvodně nesahej.}
{103}{}{Nevědecký přístup k ovládání Erikovi extra šťávu nepřidá.}
{104}{}{Erikův dům už má dost energie.}
{105}{}{Raději na to bezdůvodně nesahej.}
{106}{}{Pokoušíš se zvýšit příkon energie do Erikova domu, ale nezdařilo se.}
{107}{}{Hrát s proudem se nevyplácí. Dostáváš pořádnou elektrickou ránu.}
{108}{}{Podařilo se ti přijít na to, jak přesměrovat víc energie do Erikova domu.}
{109}{}{Podařilo se ti přesměrovat víc energie do Erikova domu a navíc ještě zoptimalizovat celou elektrickou síť Broken Hills.}
{110}{}{Erikův dům už má dost energie.}
