{100}{}{Vidíš pořádný kus stroje.}
{101}{}{The air purifier is making clunking and creaking noises. It appears to be broken. Maybe it needs a part...}
{102}{}{Čistička vzduchu tiše přede. Vypadá to, že je všechno v pořádku.}
{110}{}{Tato součástka to neopraví.}
{120}{}{Podařilo se ti opravit čističku vzduchu.}
{125}{}{Čistička vzduchu byla zničena.}
{129}{}{Spiklenci už nemůžou vyslat odpalující signál pro rozbušku. Je už k ničemu, takže ji zahodíš.}
{130}{}{Už je to opravené.}
{131}{}{Buch}
{132}{}{Skříp}
{133}{}{Břink}
{134}{}{Vrrrrrrrrr}
