{100}{}{Vidíš dobře vyzbrojeného žoldáka.}
{150}{}{Vidíš drsně vypadajícího muže oblečeného v kožené zbroji. Tělo má pokryté četnými jizvami a střelnými ranami. Ovšem jeho zbroj i zbraně vypadají udržovaně, skoro jako nové.}
{151}{}{Vidíš dobře vyzbrojeného nájezdníka. Pozoruje okolí a má prst na spoušti.}
{200}{}{No, tak ten si teda troufá...}
{201}{}{Kontakt!}
{202}{}{Oblast byla narušena!}
{203}{}{Chlapi, máme nezvaného hosta!}
{204}{}{Do zbraně, chlapi, máme tu vetřelce!}
{205}{}{A hele kdo přišel chcípnout...}
{206}{}{Zatraceně! Někdo nás našel!}
{207}{}{Máš fakt odvahu sem přijít...}
{208}{}{Jseš na *špatným* místě, děvko.}
{209}{}{Hele, podívejte se na tu děvku, jak se tu naparuje...}
{250}{}{Šli jsme chlastat a on to nazval 'hodina zlepšování nálady', tak jsme mu nakopali prdel.}
{251}{}{Musíme zkontrolovat bomby v jeskyni...}
{252}{}{Už je skoro čas zase zkontrolovat rajón...}
{253}{}{Sakra, ten divoch ale *smrdí.* Stejně jako všichni divoši.}
{254}{}{Zatracený laserový věže ve Vault City...}
{255}{}{Už mě nebaví leštit bouchačku... obě dvě.}
{256}{}{Jak dlouho tu ještě budem?}
{257}{}{Za pár dní bysme měli vyrazit...}
{258}{}{Nemůžu se dočkat, až se vrátím do Rena. *Obzvlášť* se těším na Kočičí Packu.}
{259}{}{Radškorpioni už zase mají hlad. Včera v noci bylo slyšet jejich... *cvak* *klap* *cvak*}
{260}{}{Zkontroloval jsi ty miny u vchodu, jak jsem ti *říkal*?}
{261}{}{Kapitán už po mně zase jde, protože mi málem utekl jeden obchodník...}
{262}{}{Zajímalo by mě, jak se dostanu z týhle posraný výpravy.}
{263}{}{Lynette je kočka. No, svým aristokratickým, tyranským, otrokářským způsobem.}
{264}{}{... a pak *řekla*, 'to je můj pupík, blbečku!' Haha! Tenhle vtip mě *vždycky* dostane.}
{265}{}{Můžeme jít.}
{266}{}{Kapitán má moje koule v hrsti...}
{267}{}{Mám pocit, jako kdybych tu stál věčně a jen čekám, až se někdo ukáže.}
{268}{}{Chtěl bych jít někam jinam, kdybych měl kam...}
