{100}{}{Vidíš atraktivní mladou ženu.}
{101}{}{Vidíš lázeňskou obsluhu.}
{102}{}{Vidíš jednu z dívek Nosaté Sally.}
{103}{}{Vidíš znuděně vypadající ženu.}
{104}{}{Vidíš ženu, která si tě prohlíží.}
{105}{}{Tahle žena tě doslova svléká pohledem.}
{106}{}{Vidíš mladou ženu.}
{110}{}{Vidíš atraktivní dívku. Na obličeji má nanesený nějaký druh bílého pudru.}
{111}{}{Vidíš ženu středního věku s opravdu velmi pěkně vyvinutými ňadry.}
{112}{}{Vidíš přitažlivou ženu oděnou do přiléhavých šatů.}
{113}{}{Vidíš ženu, která se na tebe usmívá.}
{120}{}{To bylo rychlý.}
{121}{}{Kdypak to bylo naposledy, zlatíčko?}
{122}{}{Snad to bude příště delší.}
{123}{}{Víš, tohle nejsou dostihy.}
{124}{}{Neříkají ti přátelé 'Rychlíku'?}
{125}{}{Kdyby byli všichni mí zákazníci tak rychlí, mohla bych jít dřív domů.}
{126}{}{Je to větší zábava, když počkáš, až ti s tím pomůžu.}
{127}{}{Kdybys počkal, až se svléknu, určitě by se ti to líbilo víc.}
{130}{}{To bylo opravdu pěkné. Jsi opravdový chlap.}
{131}{}{To bylo skvělé. Jsi úžasný. Další!}
{132}{}{Jo, zlatíčko, ještě nikdy jsem nic lepšího nezažila. (zív)}
{133}{}{Jsi nejlepší. Brzy se vrať.}
{134}{}{Jsem si jistá, že učiníš některé děvče z tvého kmene velmi šťastnou.}
{135}{}{Ne zlato, na velikosti nezáleží. Bylo to hezké.}
{136}{}{Nejsi jenom - hup na to a je to.}
{137}{}{Hezkej malej šikula, co ho tam máš schovanýho...}
{140}{}{Velikost je důležitá! Ach ty záhady života... }
{141}{}{Až přijdeš příště, udělám si přesčas.}
{142}{}{Jistě sis za svý peníze užil.}
{143}{}{Na zbytek dne si budu muset vzít volno.}
{144}{}{Páni! Taky se s tebou otřásla zem?}
{145}{}{Teď už vím, jak se cítila Kateřina Veliká.}
{150}{}{No, prachy jsou prachy.}
{151}{}{Tohle bylo, hmm, jiné, řekla bych.}
{152}{}{Tohle bylo fakt super. Další!}
{153}{}{Ne, nemůžeš používat můj parfém.}
{154}{}{No, aspoň je tvůj knírek menší, než má většina mých zákazníků.}
{155}{}{Jseš si jistá, že jsi holka?}
{160}{}{To bylo velmi něžné.}
{161}{}{To bylo nezvyklé, ale rozhodně ne špatné.}
{162}{}{Myslím, že bych si to ráda někdy opět vyzkoušela.}
{163}{}{Měli bychom se někdy sejít mimo pracovní dobu.}
{164}{}{To bylo parádní, zlato.}
{165}{}{Fíha! Od teď bude můj život úplně jiný.}
{166}{}{Nevěděla jsem, že to může být i příjemné.}
{170}{}{Jdi si promluvit s Nosatou Sally.}
{171}{}{Vypadáš roztomile.}
{172}{}{Hrozně tě miluju!}
{173}{}{Přijď se za mnou někdy podívat.}
{174}{}{Ty víš jak na to, viď?}
{175}{}{Bývala jsem čistá jako lilie, ale pak jsem se nechala svést.}
{176}{}{Sukničkáři.}
{177}{}{Nazdar tygře.}
{178}{}{Nazdar bejby...}
{179}{}{Běž si promluvit se Sally, jestli chceš nějakou akci.}
{180}{}{Nahoru a dolů, nahoru a...}
{181}{}{Vypadá to, že potřebuješ koupel.}
{182}{}{Ó, divoch. Mám ráda exotiku.}
{183}{}{Obvykle to s divochama nedělám.}
{184}{}{Líbí se ti co vidíš, bejby?}
{185}{}{Chceš mě?}
{186}{}{Jestli si chceš užít, budeš muset nejdřív zacálovat, zlato.}
