{100}{}{Vidíš velikého muže pokrytého prachem. Tváří se mírně připitoměle.}
{101}{}{Vidíš Torra Bucknera, městského prosťáčka.}
{102}{}{Vidíš velkého, svalnatého muže ve špinavém oblečení, které je pokryté špínou a prachem. Na tváři má blažený úsměv.}
{110}{}{Ty zlá. Ty bít Torr. Ty jít pryč hned!}
{111}{}{Jít zlá osobá! Nebít Torr.}
{112}{}{Jaůů! Jít pryč!}
{113}{}{Nebít Torr už víc.}
{114}{}{Torr hodná. Nebít Torr.}
{115}{}{Torr zraněná. Zlá chlap! Zlá chlap jít pryč!}
{120}{}{Pomoct Torr! (Pomoz mi prosím. Je tady jisté stvoření, které mi zabraňuje v útěku z tohoto místa.)}
{121}{}{Pomoct Torr!}
{122}{}{ pomoct Torr. (Pomůžu ti, Torre. Vydrž!)}
{123}{}{Pomůžu ti, Torre.}
{130}{}{Písk písk zlá! Pomoct Torr! (Dej si pozor na Ducha, který kráčí! Promluvíme si, až mě odsud dostaneš.)}
{131}{}{Písk Písk! Au! Duch zlá! Zlá! Pomoct Torr! Torr jít hned!}
{132}{}{Dobže, Torr. (To je rozumné, Torre. Vypadneme odsud.)}
{133}{}{Promluvíme si později, teď odsud musíme vypadnout.}
{140}{}{Já Torr (Jsem Torr. Můžu ti nějak pomoct?)}
{141}{}{Já Torr.}
{142}{}{Ty Torr. (Ahoj, Torre. Mám na tebe pár otázek.)}
{143}{}{Těší mě, Torre. Nestalo se tady v poslední době něco zajímavého?}
{144}{}{Jsem tu kvůli brah... eh, chci říct bůbům.}
{150}{}{Já hlídkovat bůbů před broukochlapama. (Hlídám brahmíní stádo naší rodiny před zuřivými nočními útoky dvounohých bytostí pokrytých chitinovým pancířem, kterým říkám lido-brouci.)}
{151}{}{Já hlídkovat bůbů před broukochlapama.}
{152}{}{Broukochlapama? (Lido-brouci? No, to zní jako výstižný název pro to, co jsi mi právě popsal. Pověz mi o nich víc.)}
{153}{}{Broukochlapama?}
{160}{}{Broukochlap krást bůbů když noc. Torr strach! Pomoct Torr? (No, jak jsem řekl, jsou to noční tvorové. Hodila by se mi nějaká pomoc při hlídání. Pomůžeš mi zabít lido-brouky, kteří se dostanou blízko k brahmínám?)}
{161}{}{Broukochlap krást bůbů když noc. Torr strach! Pomoct Torr?}
{162}{}{Pomoct Torr s bůbů. (Jistě, pomůžu ti ochránit tvoje brahmíny před útoky těch proradných lido-brouků.)}
{163}{}{Broukouchlap oni zlá. Nepomoct Torr. (Hmm, myslím, že ti s tím nepomůžu, Torre. Ale přeju ti hodně štěstí. Sbohem.)}
{164}{}{Eh...jistě, Torre. Pomůžu ti ohlídat brahmíny.}
{165}{}{Nemůžu (zavrtíš hlavou) ti s tím pomoct. Sbohem.}
{166}{}{Obchoďák znát? (Než se tam vydáme, Torre, nevíš o nějakém obchodníkovi ve městě?}
{170}{}{Ty pomoct Torr. Pole bůbů (ukáže na východ) ve tma jo? (usměje se) (Díky za pomoc. Dnes v noci ji opravdu budu potřebovat.)}
{171}{}{Ty pomoct Torr. Pole bůbů (ukáže na východ) ve tma jo? (usměje se)}
{172}{}{ pomoct Torr. (Pomůžu ti. Setkáme se na pastvině při západu slunce.)}
{173}{}{Torr? (Pomůžu ti ohlídat brahmíny, ale nejdřív se tě chci na něco zeptat.)}
{174}{}{Pomůžu ti ohlídat brahmíny, Torre. Setkáme se na pastvině při západu slunce. Sbohem.}
{175}{}{Dnes v noci ti nemůžu pomoct hlídat brahmíny, Torre. Nashle.}
{180}{}{Torr říct? (Co chceš vědět, příteli?)}
{181}{}{ tady! (Pověz mi, co se tu děje.)}
{182}{}{ Chrrrrr. Jasný? (Potřebuju místo k přespání.)}
{183}{}{Chtít! (ukážeš na věci)(Kde můžu obchodovat?)}
{184}{}{GGG ek? (Slyšel jsi někdy o věci zvané GECK?)}
{185}{}{Jít Torr. (To mi zatím stačí. Sbohem, Torre.)}
{190}{}{Dobže! Broukochlap, dívok Ulik, Smiley chybět. (No, je tady ten můj problém s lido-brouky a pak je tady Sulik, který si u mojí mámy odpracovává dluh... mám pocit, že je do něj sestra zamilovaná. A mámin přítel, chlápek jménem Smiley, se ztratil někde na západě. V poslední době je tady docela živo.)}
{191}{}{Torr? (Tady to ale žije. Chci se ještě na něco zeptat.)}
{192}{}{Dobže! (To mi zatím stačí. Sbohem.)}
{200}{}{Chrrrr? Torr Chrrrr. (No, můžeš přespat u mě. Zadarmo.)}
{201}{}{Torr Chrrrrrrr? (Necháš mě u sebe přespat? To je od tebe opravdu milé. Hned toho využiju, už skoro spím. Díky.)}
{202}{}{Chrrrrr? (Teď se mi zrovna nechce spát, ale díky za nabídku, možná ji využiju později. Ale mám na tebe ještě pár otázek.)}
{203}{}{Chrrr Ne Torr. (Teď momentálně spánek nepotřebuju, ale díky za nabídku. Sbohem, příteli.)}
{210}{}{Buckner! Zlátág nene (Myslím, že nejlepší ceny dostaneš u nás, Bucknerů. U Zlatého geckona se ti jenom vysmějí.)}
{211}{}{Uckner? (Díky, nakoupím tam. Chci se ještě na něco zeptat.)}
{212}{}{Zlátág nene. (Dobrá rada. Ale teď stejně nic nepotřebuju. Sbohem.)}
{220}{}{GGGék? Vic Gék! (Takže ty hledáš GECK, jo? Ty byly dřív ve vaultech, ne? Nevím, kde by se dalo něco takového sehnat, ale určitě o tom něco ví obchodník Vic. Specializuje se na předválečné zboží. Žije v severovýchodní části Klamathu.)}
{221}{}{Gék Vic? (Díky za informaci. Zkusím se toho Vica zeptat. Chci se ještě na něco zeptat.)}
{222}{}{Gék Vic, dobře! (Díky, zajdu za ním. Sbohem.)}
{229}{}{Torr ráda }
{230}{}{. Torr děkovat. Broukochlap zlá, nenechat brokouchlap papat bůbů! (Děkuju ti za pomoc, z těhlech lido-brouků mi běhá mráz po zádech. Doufám, že už o žádné další brahmíny nepřijdeme.)}
{231}{}{. Torr děkovat. Broukochlap zlá, nenechat brokouchlap papat bůbů!}
{232}{}{Torr. (Když jsme tu dva, tak nám určitě žádnou brahmínu nevezmou.)}
{233}{}{Doufám, že zastavíme ty útoky na tvé bůbů. Eh, chci říct brahmíny. Myslím, že si na nás dva netroufnou.}
{234}{}{Vlastně tě jdu varovat. Támhle na druhé straně skály je několik broukochlapů. Pohlídám bůbů za tebe a ty utíkej pro pomoc.}
{240}{}{Dobže? Pomoct Torr s bůbů? Ne broukochlap! Broukochlap zlá! (Pomůžeš mi ochránit brahmíny před útokem lido-brouků?)}
{241}{}{Dobže? Pomoct Torr s bůbů? Ne broukochlap! Broukochlap zlá!}
{242}{}{ pomoct Torr s bůbů (Ano, jdu ti pomoct ochránit brahmíny proti lido-broukům. Pokud tu budeme oba, nedostanou ani jeden kus!)}
{243}{}{Ne pomoct. (Promiň, ale já tudy jenom procházím. Nemůžu ti pomoct. Sbohem.)}
{244}{}{Eh, ano. Jdu ti pomoct ochránit brahmíny... chci říct bůbů... před broukochlapy.}
{245}{}{Vlastně tě jdu varovat. Támhle na druhé straně skály je několik broukochlapů. Pohlídám bůbů za tebe a ty utíkej pro pomoc.}
{246}{}{Promiň, Torre. Mám moc práce na to, abych tady stál se stádem brahmín, ať už mají dvě nohy nebo čtyři.}
{249}{}{Torr milovat }
{250}{}{. Torr milovat máma. Torr milovat táta. (Jsem opravdu rád, že jsi mě zachránil. Už jsem myslel, že to nepřežiju.)}
{251}{}{. Torr milovat máma. Torr milovat táta.}
{252}{}{Torr dobrá. (To nic nebylo, určitě bys udělal to samé i pro mě. Chci se ještě na něco zeptat.)}
{253}{}{Torr hehehe. (No, vypadal jsi opravdu srandovně, když tě ten robot držel v šachu. Příště si dávej větší pozor. Sbohem.)}
{254}{}{Torre, buď opatrnější, ano? Sbohem, Torre.}
{255}{}{Nemáš ani páru, co ti říkám, co? Kvůli tobě bylo málem bylo po mně, blbečku. Sbohem a doufám, že už tě nikdy neuvidím.}
{260}{}{Broukochlap zlá. Torr bát.}
{261}{}{Torr vidět broukochlap bít bůbů.}
{262}{}{Bůbů bít!}
{263}{}{Brokochlap chodit z kaňon.}
{264}{}{Torr vidět mrtvá broukochlap.}
{265}{}{Hehehe.}
{266}{}{Leonard?}
{267}{}{Duntoni zlá.}
{268}{}{Maso mňam.}
{269}{}{Torr silná.}
{270}{}{Ook?}
{271}{}{Zugzug.}
{272}{}{Blabla?}
{273}{}{Arroyo?}
{274}{}{Muset čůrat.}
{275}{}{Ahoj.}
{276}{}{Ahoj.}
{277}{}{Torr!}
{279}{}{Torr vidět }
{280}{}{! (Vítej, příteli. Můžu ti s něčím pomoct?)}
{281}{}{ vídět Torr! (No, vlastně se tě chci zeptat na pár věcí.)}
{282}{}{Torr, ahoj. (Těší mě, že tě zase vidím, Torre, ale jenom tudy procházím. Měj se.)}
{300}{}{Torr jít pro pomoc! (Torr zmizel v temnotě a nechal tě s bůbů, eh, s brahmínami.)}
{301}{}{Brouka mrtvej. Bůbů v bezpečí. Torr děkovat.}
{400}{}{Ty pomoct Torr. Bůbů na pole (ukáže na východ) támhle teď? (usměje se) (Díky za pomoc, budu ji potřebovat.)}
{401}{}{Ty pomoct Torr. Bůbů na pole (ukáže na východ) támhle teď? (usměje se)}
{402}{}{ pomoct Torr. (Půjdu s tebou na pastvinu na východ od města.)}
{404}{}{Pomůžu ti ohlídat brahmíny, Torre.}
{405}{}{Teď ti s hlídáním nemůžu pomoct, Torre.}
{500}{}{Přestat bít bůbů.}
{501}{}{Torr pomoct bůbů.}
{502}{}{Zlej ženská! Zlej! Nebít bůbů!}
{503}{}{Jít pryč, zlá chlap.}
{504}{}{Zlej ženská! Zlej! Jít pryč!}
{505}{}{Zlá chlap, zlá! Nebít bůbů!}
{506}{}{Nebít Torrova bůbů!}
{507}{}{Torr jít zachránit bůbů!}
{600}{}{Torr děkovat. Torr teď fajn. Ty jít.}
{700}{}{Obchoďák? V Kamat? Ik v Den. (Obchodník v Klamathu? Ale jo, Vic prodává nějaké starožitnosti, ale momentálně není ve městě. Myslím, že obchoduje v Denu, který leží na jih odtud.)}
{701}{}{Groo! (Díky moc, Torre. Co jsi to říkal o těch predátorech?}
{702}{}{Grok! Torr! (Díky moc, Torre. Jsi dobrý muž. Bohužel musím odejít, ale přeju ti hodně štěstí při chování dobytka. Sbohem, příteli Torre.)}
{800}{}{Torr byl zachráněn.}
