{100}{}{Vidíš velikého muže v kožené zástìøe.}
{101}{}{Vidíš koželuha Balthase.}
{102}{}{Vidíš vysokého, svalnatého muže, který páchne kùží.}
{151}{}{Mùj syn byl omylem zabit v boji.}
{152}{}{Nevydržím žít bez Jonnyho.}
{153}{}{[Vzlyk]}
{154}{}{Setkáme se na Farmì Duchù. Zaútoèíme na ty duchy.}
{155}{}{Zdravím, jmenuju se Balthas. Vedu koželužnu tady v Modocu. Mùžu ti nìjak pomoct?}
{156}{}{Vypadáš ponìkud roztržitì. Dìje se nìco?}
{157}{}{Mùžu vidìt tvoje zboží?}
{158}{}{Nevidìl jsi nìkde ležet zlaté hodinky?}
{159}{}{Vrátím se pozdìji.}
{160}{}{Hledám vìc, která se jmenuje GECK. Nevíš o tom náhodou nìco nebo nevíš, jak ho získat?}
{161}{}{GECK?}
{163}{}{S èím ti mùžu pomoct?}
{168}{}{Jen se dívám, díky.}
{171}{}{Máš nìjaké nové zprávy ohlednì Jonnyho?}
{172}{}{Tohle leželo na dnì vyschlé studny. Èást studny se zøítila dovnitø a tohle bylo v sutinách. Je mi líto, ale myslím, že je Jonny mrtvý.}
{173}{}{Ne, zatím nic.}
{175}{}{Dìkuju ti za záchranu mého chlapce. Nevím, jak bych se ti mohl odvdìèit, ale vezmi si prosím tuhle koženou zbroj jako podìkování. Vynalezl jsem nový zpùsob vydìlávání kùží. Zjistíš, že je tahle zbroj velmi odolná a navíc v ní vypadáš opravdu dobøe.}
{176}{}{Dìkuju ti za záchranu mého syna!}
{177}{}{Prosím, nech mì truchlit o samotì.}
{178}{}{Jonny je naživu! Nìjací lidé, kteøí si øíkají Svìtloplachové, ho zachránili. Když ještì chvíli vydržíš, najdu zpùsob, jak dostat Jonnyho domù.}
{179}{}{Jonny byl unesen. Drží ho duchové na farmì a chtìjí ho obìtovat svému temnému bohu.}
{180}{}{Chápu. Promiò, že obtìžuju.}
{181}{}{Cože? Podívej, nebudu se bavit s cizincem o svém soukromém životì. Chceš nìco koupit nebo ne?}
{182}{}{Omlouvám se, jmenuju se }
{183}{}{. Tak a už jsme se koneènì pøedstavili. Zdá se, že tì nìco trápí.}
{184}{}{Ano, zajímám se o nìjaké kožené zboží.}
{186}{}{Myslím, že ne.}
{187}{}{Øíkáš }
{188}{}{? Ano, myslím, že už jsem o tobì slyšel. Jeden ze strážcù projíždìjící karavany o tobì pochvalnì mluvil. Vím, že jsme se teprve seznámili, ale docela bych potøeboval tvoji pomoc.}
{189}{}{A co kdybys mi øekl, co máš za problém? Tøeba ti s ním pomùžu.}
{190}{}{Mám svých problémù dost, promiò.}
{191}{}{(Vezme do ruky ocelovou tyè a zaène ji zuøivì kroutit. K tvému úžasu se ocelová tyè kroutí, jako by byla z gumy. Ten chlap má ale sílu!) Ztratil se mi mùj chlapec Jonny! Pøed nìkolika dny si šel hrát ven a už se nevrátil. Hledali jsme všude, ale zatím jsme ho nenašli.}
{192}{}{Kde si Jonny vìtšinou hrál? A hrál si ještì s nìkým jiným?}
{193}{}{Je mi líto tvého chlapce. Mùžu pro tebe nìco udìlat?}
{194}{}{To je strašné! Ale zajímám se jen o tvé kožené zboží. Asi mi nemùžeš ukázat, co nabízíš, že?}
{195}{}{Fíha! To je ale hodin. Musím bìžet.}
{196}{}{Znamená to, že mi pomùžeš? Dìkuju ti! Naposledy vidìli Jonnyho, jak si hraje pøed domem na kovboje a indiány s jeho psem Laddie. Byli to dva nerozluèní pøátelé. A vlastnì díky ní jsme zjistili, že se nìco stalo. Jednoho dne se Laddie vrátila bez Jonnyho. Od té doby ho stále hledáme. Vezmi si Laddii s sebou, tøeba se vám ho podaøí najít.}
{197}{}{No, vypadáš jako zkušený cestovatel. S tvými zkušenostmi se ti možná podaøí mého syna najít.}
{198}{}{No, ano! Jsem zkušený stopaø, tedy aspoò si to o sobì myslím. Dobrá, pomùžu ti.}
{199}{}{S lichotkami na mì nechoï. Podívej, mám na tebe pár otázek.}
{200}{}{Mé modlitby byly vyslyšeny! Vezmi si Laddie s sebou, tøeba ti pomùže. Prosím, pospìš si!}
{201}{}{No, možná máš pravdu. Díky za vyslechnutí.}
{202}{}{Slyšel jsem o tobì. Podívej, nechci žádné problémy. Jsme mírumilovná spoleènost. Bavme se jen o obchodu, ano?}
{203}{}{Chci se tì na nìco zeptat.}
{204}{}{Momentálnì spolu nemáme žádný obchod. Nashle.}
{205}{}{No...mám strach o svého syna Jonnyho. Hledali jsme všude, ale nemùžeme ho nikde najít. Bojím se, že ho roztrhala divoká zvìø.}
{206}{}{Možná ti mùžu pomoct. Hodnì cestuju, takže se mùžu po tvém chlapci podívat.}
{208}{}{To bych byl moc rád. Každá pomoc je vítaná. Mimochodem, nekoupíš si u mì nìco?}
{210}{}{No, ani ne. Už musím jít. Díky.}
{211}{}{Promiò, ale o tom jsem nikdy neslyšel.}
{214}{}{Hehehe. Tak tebe ten staroch Cornelius taky navezl do hledání jeho hodinek? Ne, tady je nenajdeš. Ten starej trouba je nejspíš nìkde zapomnìl a neví kde.}
{215}{}{I pøesto dìkuju. Budu je hledat dál. Nashle.}
{216}{}{(Zblízka se na tebe podívá a poté se usmìje.) Buï hodný chlapec a bìž si hrát ven.}
{217}{}{(Zblízka se na tebe podívá a poté se usmìje.) Buï hodná holèièka a bìž si hrát ven.}
{218}{}{Prosím, nepøestávej hledat. Vím, že je naživu, cítím to!}
{219}{}{To je Jonnyho vzduchovka. Neeeeeeeeeeeeeeeeeeee! (Balthas se zhroutí a zaène neovladatelnì plakat.)}
{220}{}{Já vìdìl, že Jonny není mrtvý! Øíkáš, že musím èekat... tomu nerozumím! Je zranìný? Mùj instinkt mi øíká, abych šel za svým synem, ale cítím, že ti na mém synovi opravdu záleží. Prosím, pospìš si a pøiveï mi mého syna.}
{221}{}{Ale ne! Duchové ne! Já øíkal, abychom to místo vypálili. Nenechám jim svého syna... dostanu Jonnyho zpìt za každou cenu. Jsem si jistý, že mi ho obyvatelé Modocu pomùžou dostat zpìt! Setkáme se na Farmì Duchù. Všechny je zabijeme!}
{230}{}{Jonny byl v poøádku vrácen zpìt do Modocu.}
{240}{}{Prosím, pøiveï mi mého syna zpìt.}
{2199}{}{To je Jonnyho vzduchovka... nevìøím, že je mrtvý. Prosím, nepøestávej hledat mého syna. Jsem si jistý, že tam nìkde venku poøád je.}
