{100}{}{Podle nápisu na chomoutu se jmenuje Bess.}
{101}{}{Vidíš Bess.}
{110}{}{Zdá se, že tato brahmíní samice byla asi napadena nějakým divokým zvířetem. Je vážně zraněná.}
{111}{}{Na takovou brahmínu by mohl být každý pyšný.}
{120}{}{Bůůůůůůůůů!}
{121}{}{(Ta nebohá brahmína je zraněná.)}
{130}{}{Bůůůůůůůůů.}
{131}{}{(Bess hluboce a smutně zabučí.)}
{132}{}{Chudinko - dávat tě řezníkovi asi nebude nejlepší nápad. Chtěla bys odsud utéct?}
{133}{}{Jupí! Bude z tebe vynikající sušený maso.}
{140}{}{Bůůůůůůů.}
{141}{}{(Teď bučí o hodně veseleji.)}
{142}{}{Dobře, tak pojď odsud pryč.}
{143}{}{Jen si dělám legraci. Víš, potřebuju tvoje maso víc než tebe.}
{150}{}{Bůůůůů.}
{200}{}{Dovednost První pomoc ti nepomůže vyléčit zlomenou nohu této ubohé brahmíny.}
{300}{}{Podařilo se ti uzdravit brahmíninu zlomenou nohu.}
{310}{}{Nepodařilo se ti uzdravit brahmíninu zlomenou nohu.}
