{100}{}{Vidíš stráž Světloplachů.}
{150}{}{Vzdej se, nebo zemřeš!}
{151}{}{Vzdávám se.}
{152}{}{Ty zemřít!}
{153}{}{Ug!}
{154}{}{Jestli chceš vidět Vegeira, můžeme tě k němu doprovodit.}
{155}{}{Teď ne. Sejdu se s Vegeirem později.}
{156}{}{Ano, chci hned vidět Vegeira.}
{160}{}{Ty jsi ale hlupák! Jestli chceš vidět Vegeira, najdi si ho.}
{200}{}{Nevěřím Nadzemníkům.}
{201}{}{Vegeir říkal, ať tě necháme na pokoji... ZATÍM.}
{202}{}{Odpovídáme za ochranu našich lidí.}
{203}{}{Sleduju tě.}
{220}{}{Myslím, že jsi v pohodě... na Nadzemníka.}
{221}{}{Možná bysme mohli spolupracovat s Nadzemníky.}
{222}{}{Jsem rád, že jsem se v tobě mýlil.}
