{100}{}{Malá farmáøská osada obklopená rozlehlými poli zvadlého obilí.}
{500}{}{Zdá se, že už jsou všichni mrtví.}
{501}{}{Zabila všechna škaredá obluda.}
{502}{}{Podaøilo se ti vyèistit Farrelovu zahradu.}
{600}{}{Vidíš mìšec.}
{601}{}{Vidíš mìšec. Nìkdo ho asi hodil do studny, aby se mu splnilo pøání.}
{610}{}{Tohle je MÙJ sen, MOJE pøání a já si ho beru zpìt. Všechny si je beru zpìt.}
{1000}{}{Všechny je zabijte!}
{1001}{}{Smrt Svìtloplachùm!}
{1002}{}{Chci vidìt, jak budou øvát!}
{1003}{}{Jdeme je sejmout!}
{1100}{}{Padáš asi pìt metrù do špatnì osvìtlené jeskynì. O vzdálenìjší zeï je opøené všelijaké farmáøské vybavení.}
{1200}{}{Podaøilo se ti dostat z jámy tìsnì pøed výbuchem, který tì odhodil do vzduchu.}
