{100}{}{Vidíš jednoho z bodygardù Korsických bratrù.}
{150}{}{Vidíš drsnì vypadající ženu se zeleným èírem. Opatruje svùj samopal, jako by to bylo její dítì.}
{151}{}{Vidíš jednoho z bodygardù Korsických bratrù.}
{200}{}{Zachránil jsi celej svìt, co? No to je toho.}
{201}{}{Hmm, jseš mùj hrdina. A teï ODPREJSKNI.}
{300}{}{Haló?}
{301}{}{Hele, támhle je nìjaká pìkná blondýnka...}
{302}{}{Copak, jseš moc nóbl na to, abys se mnou mluvil?}
{303}{}{Øekni nìco. Cokoliv!}
{400}{}{Èurák.}
{401}{}{Kokot.}
{402}{}{Sráè.}
{403}{}{Jo, jdi pryè, idiote.}
{404}{}{Doufám, že už nikdy nebudu mít to "potìšení" setkat se znovu s takovým kreténem.}
{405}{}{Ta holka by si mìla vzít Tic-Tac.}
{406}{}{Dìvka.}
{500}{}{Rozpaèitì se na tebe dívá.}
{501}{}{Oèividnì neví co øíct.}
{600}{}{Ráda bych si ho vzala do postele a zahrála si s ním "kulièky".}
{601}{}{Mùžeš mì s ním nìkdy seznámit?}
{602}{}{Hmmm...}
{603}{}{Mùžeš mì s ní nìkdy seznámit?}
{604}{}{Moc rád bych to s ní dal dohromady.}
{605}{}{Jsem do ní strašnì zamilovanej, ale bojím se jí to øíct.}
