{100}{}{Vidíš zuřivého fanouška boxu. }
{150}{}{Vidíš divokého a odvázaného muže. Kvůli něčemu strašně řve.}
{151}{}{Vidíš zuřivého fanouška boxu. Řve a žádá si krev.}
{152}{}{Vidíš divokou a odvázanou ženu. Kvůli něčemu strašně řve.}
{153}{}{Vidíš zuřivou fanynku boxu. Řve a žádá si krev.}
{200}{}{Joooooooooooooo!}
{201}{}{::řev:: ::bučení:: ::řev::}
{202}{}{Zabij ho, }
{203}{}{Jseš nejlepší, }
{204}{}{Nandej jim to, }
{205}{}{Joooo! Nandej mu to!}
{206}{}{}
{207}{}{}
{208}{}{}
{209}{}{}
{210}{}{}
{211}{}{}
{212}{}{}
{213}{}{}
{214}{}{Miluju }
{215}{}{::vřískot:: ::vřískot::}
{216}{}{}
{250}{}{}
{251}{}{}
{252}{}{}
{253}{}{Slyšela jsem, že byla }
{254}{}{Panebože! }
{255}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dětem, že jsi mi dal ránu!}
{256}{}{Jseš nejlepší, }
{257}{}{Zabij ho, }
{258}{}{Jseš nejlepší, }
{259}{}{Nandej jim to, }
{260}{}{Joooo! Nandej mu to!}
{261}{}{}
{262}{}{}
{263}{}{Joooooooooooooo!}
{264}{}{::řev:: ::bučení:: ::řev::}
{265}{}{}
{266}{}{}
{267}{}{Jseš drsnější než Mike Tyson!}
{268}{}{}
{269}{}{}
{270}{}{}
{271}{}{Slyšela jsem, že byla }
{280}{}{Nechceš polibek pro štěstí?}
{281}{}{}
{282}{}{}
{283}{}{}
{284}{}{}
{285}{}{}
{286}{}{Slyšela jsem, že byla }
{287}{}{Panebože! }
{288}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dětem, že jsi mi dal ránu!}
{289}{}{Jseš nejlepší }
{290}{}{Zabij ho, }
{291}{}{Jseš nejlepší, }
{292}{}{Nandej jim to, }
{293}{}{Joooo! Nandej mu to!}
{294}{}{}
{295}{}{}
{296}{}{Áááááááááááááá!}
{297}{}{::vřískot:: ::vřískot::}
{298}{}{}
{299}{}{}
{300}{}{Jseš drsnější než Mike Tyson!}
{301}{}{}
{302}{}{}
{303}{}{}
{304}{}{Slyšela jsem, že byla }
{320}{}{ zabije každýho, kdo se mu postaví do cesty!}
{321}{}{ je prostě NEJLEPŠÍ. NEJLEPŠÍ.}
{322}{}{!!!}
{323}{}{ je fakt chlapák!}
{324}{}{ je nejlepší šampión v boxu, kterýho jsem kdy viděl.}
{325}{}{ je i pěkně chytrej a opravdu ví, jak někomu ublížit.}
{326}{}{ se zajímá i o svý fanoušky. Nezabíjí je jako ostatní boxeři.}
{327}{}{ je tááááák hezkej.}
{328}{}{ je laskavej a vychovanej. To mi řekl minulou noc.}
{350}{}{}
{351}{}{Doma mám trochu tvýho potu schovanýho v láhvi.}
{352}{}{Panebože! }
{353}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dětem, že jsi mi dal ránu!}
{354}{}{Jseš nejlepší }
{355}{}{Jseš nejlepší, }
{356}{}{Jdi a nandej jim to, }
{357}{}{}
{358}{}{}
{359}{}{Joooooooooooooo!}
{360}{}{}
{361}{}{}
{362}{}{}
{363}{}{Slyšela jsem, že jsi byl neznámej, než jsi začal boxovat v New Renu. Odkud jsi?}
{364}{}{}
{365}{}{Jseš drsnější než Mike Tyson!}
{366}{}{}
{380}{}{Nechceš polibek pro štěstí?}
{381}{}{}
{382}{}{}
{383}{}{::Když s ní začneš mluvit, tak úplně omdlévá::}
{384}{}{Doma mám trochu tvýho potu schovanýho v láhvi.}
{385}{}{Panebože! }
{386}{}{Dej mi ránu! Dej mi ránu! Budu vykládat svým dětem, že jsi mi dal ránu!}
{387}{}{Jseš nejlepší }
{388}{}{Zabij je, !}
{389}{}{Jseš nejlepší, }
{390}{}{Nandej jim to, }
{391}{}{.}
{392}{}{}
{393}{}{Áááááááááááááá!}
{394}{}{}
{395}{}{}
{396}{}{}
{397}{}{Slyšela jsem, že jsi byl neznámej, než jsi začal boxovat v New Renu. Odkud jsi?}
{398}{}{}
{399}{}{Jseš drsnější než Mike Tyson!}
{400}{}{}
{1202}{}{!}
{1203}{}{!}
{1204}{}{!}
{1206}{}{ je prostě NEJLEPŠÍ. NEJLEPŠÍ.}
{1207}{}{!!!}
{1208}{}{, jseš fakt chlapák!}
{1209}{}{ je nejlepší šampión v boxu, kterýho jsem kdy viděl.}
{1210}{}{ je i pěkně chytrej a opravdu ví, jak někomu ublížit.}
{1211}{}{ se zajímá i o svý fanoušky. Nezabíjí je jako ostatní boxeři.}
{1212}{}{ je tááááák hezkej.}
{1213}{}{ je pořádnej chlap.}
{1214}{}{ Áááááááááááááá!}
{1216}{}{ je laskavej a vychovanej. To mi řekl minulou noc.}
{1250}{}{, jseš fakt chlapák!}
{1251}{}{ je i pěkně chytrej a opravdu ví, jak někomu ublížit.}
{1252}{}{ se zajímá i o svý fanoušky. Nezabíjí je jako ostatní boxeři.}
{1253}{}{ skoro neznámej, než začal boxovat v New Renu. Je tak záhadnej! A vražednej!}
{1254}{}{! Dej mi prosím autogram!}
{1256}{}{! Pořádně jim to nandej!}
{1257}{}{!}
{1258}{}{!}
{1259}{}{!}
{1261}{}{, jseš prostě NEJLEPŠÍ. NEJLEPŠÍ.}
{1262}{}{!!!}
{1265}{}{ je nejlepší šampión v boxu, kterýho jsem kdy viděl.}
{1266}{}{, jseš nejdrsnější ženská na světě!}
{1268}{}{, jseš pořádná ženská!}
{1269}{}{ je i pěkně chytrá a opravdu ví, jak někomu ublížit.}
{1270}{}{ se zajímá i o svý fanoušky. Nezabíjí je jako ostatní boxeři.}
{1271}{}{ skoro neznámá, než začala boxovat v New Renu. Je tak záhadná!}
{1281}{}{, jseš fakt chlapák!}
{1282}{}{ je tááááák hezkej.}
{1283}{}{ je chlap jako hora!}
{1284}{}{ je i pěkně chytrej a opravdu ví, jak někomu ublížit.}
{1285}{}{ se zajímá i o svý fanoušky. Nezabíjí je jako ostatní boxeři.}
{1286}{}{ skoro neznámej, než začal boxovat v New Renu. Je tak záhadnej! A vražednej!}
{1287}{}{! Dej mi prosím autogram!}
{1289}{}{! Pořádně jim to nandej!}
{1290}{}{!}
{1291}{}{!}
{1292}{}{!}
{1294}{}{, jseš prostě NEJLEPŠÍ. NEJLEPŠÍ.}
{1295}{}{!!!}
{1298}{}{ je nejlepší šampión v boxu, kterýho jsem kdy viděl.}
{1299}{}{, jseš nejdrsnější ženská na světě!}
{1301}{}{, jseš pořádná ženská!}
{1302}{}{ je i pěkně chytrá a opravdu ví, jak někomu ublížit.}
{1303}{}{ se zajímá i o svý fanoušky. Nezabíjí je jako ostatní boxeři.}
{1304}{}{ skoro neznámá, než začala boxovat v New Renu. Je tak záhadná!}
{1350}{}{, jseš fakt chlapák!}
{1352}{}{! Dej mi prosím autogram!}
{1354}{}{! Pořádně jim to nandej!}
{1355}{}{!}
{1356}{}{!}
{1357}{}{, jseš prostě NEJLEPŠÍ. NEJLEPŠÍ.}
{1358}{}{!!!}
{1360}{}{, jseš nejlepší šampión v boxu, kterýho jsem kdy viděla.}
{1361}{}{, ty opravdu víš, jak někomu ublížit.}
{1362}{}{, ty se fakt zajímáš o svý fanoušky. Nezabíjíš je jako ostatní boxeři.}
{1364}{}{, jseš nejdrsnější ženská na světě!}
{1366}{}{, jseš pořádná ženská!}
{1381}{}{, jseš fakt chlapák!}
{1382}{}{, jseš táááááák krásnej.}
{1385}{}{! Dej mi prosím autogram!}
{1387}{}{! Pořádně jim to nandej!}
{1388}{}{!}
{1389}{}{!}
{1390}{}{!}
{1391}{}{, jseš prostě NEJLEPŠÍ. NEJLEPŠÍ.}
{1392}{}{!!!}
{1394}{}{, jseš nejlepší šampión v boxu, kterýho jsem kdy viděla.}
{1395}{}{, ty opravdu víš, jak někomu ublížit.}
{1396}{}{, ty se fakt zajímáš o svý fanoušky. Nezabíjíš je jako ostatní boxeři.}
{1398}{}{, jseš nejdrsnější ženská na světě!}
{1400}{}{, jseš pořádná ženská!}
