# 0. QUICK LOOK

# 0. LOOK
{150}{}{Vidíš vysokého mladíka s èírem. Je obleèenı v kùi a ovìšenı øetìzy.}
{151}{}{Vidíš Chrise Wrighta.}
{152}{}{Vidíš Chrise Wrighta. K smrti se nudí.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Nazdar! }
{201}{}{Jen tak dál, }
{202}{}{Skvìlı, }
{203}{}{::Jásá::}
{204}{}{::Tleská::}
{205}{}{::Píská::}

# 2. FLOAT DIALOGUE: POWER ARMOR (WTG)
{215}{}{Jak s tou zbrojí chodíš na záchod?}

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Nazdárek, }
{221}{}{Je hroznı vedro co, }
{222}{}{Zdar, }

# 4. FLOAT/CLICK (DAD IS DEAD) (WTG)
{230}{}{Poøád nemùu uvìøit, e je táta mrtvej. Chtìl jsem mu toho ještì tolik øíct...}

# 5. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM] (WTG)
{235}{}{Jdi do hajzlu.}
{236}{}{Jdi do hajzlu. Myslím to vánì.}
{237}{}{Nemám ti co øíct.}

# 6. INTRO (NORMAL) (WTG)
{245}{}{Jo?}
{246}{}{Nazdar! Jak to jde, }
{1246}{}{? Všichni se k tobì chovaj dobøe? Nepotøebuješ nìco?}
{247}{}{Jsem ti vdìènej, e se ti podaøilo zjistit, kdo zabil Richarda, }
{248}{}{. Jsem tvùj velkej dluník a Wrightova rodina vdycky svoje dluhy splatí. Co pro tebe mùu udìlat?}
{249}{}{Mattah. Chlap je Mattah!}
{250}{}{Kdo ty?}
{251}{}{Odbelhat se.}
{252}{}{Kdo jsi?}
{253}{}{Hledám práci. Nabírají Wrightovi?}
{254}{}{Potkal jsem tvoji matku.}
{255}{}{Mùeš mi øíct nìco o Richardovi?}
{256}{}{Nic, díky. Promiò, e obtìuju.}
{257}{}{Mùeš mi øíct nìco o Wrightovì rodinì?}

# 7.  RETARD (6)
{265}{}{Jdi do hajzlu, retarde. Nemám èas si s tebou povídat znakovou øeèí.}

# 8.  WHO ARE YOU? (6)
{275}{}{Jsem Chris. Chris Wright. Z rodiny Wrightù. Máš radost?}
{277}{}{Rodina Wrightù? Co jsou zaè?}
{278}{}{Chris Wright, jo? Potkal jsem tvoji matku.}
{279}{}{Mùeš mi øíct, co se stalo tvému bratrovi Richardovi?}
{280}{}{Ani ne. Promiò, e obtìuju.}

# 9. FAMILY WRIGHT? WHO'S THAT? (8, 10, 12)
{290}{}{Ty neznáš rodinu Wrightù? To jsi musel bıt v poušti asi pìknì dlouho. Wrightova rodina je nejvìtší zloèinecká rodina v Renu. Brzy budem šéfovat celımu mìstu.}
{291}{}{Opravdu? To zní, jako kdyby to tu mìli pod palcem. Nabírají lidi?}
{292}{}{Vlastnì mi pøijde, e jsou nejslabší rodina... chci øíct, kšeftujou jenom s chlastem, nemají ani kasíno nebo fet a dohromady jich je mnohem ménì ne v ostatních rodinách.}
{293}{}{Kdy u mluvíme o rodinì, potkal jsem tvoji matku.}
{295}{}{Opravdu? To je zajímavé... poslyš, u musím jít.}
{296}{}{Wrightova rodina je nejvìtší zloèinecká rodina v Renu. Brzy budem šéfovat celımu mìstu.}

# 10. QUESTIONS (15, 16, 17, 18, 19, 20, 22, 25, 26, 28)
{305}{}{Jakı tøeba?}
{306}{}{Mùeš mi øíct nìco o rodinì Wrightù?}
{307}{}{Nabírají Wrightovi lidi?}
{308}{}{Nedávno jsem potkal tvoji matku. Milá dáma.}
{310}{}{Nemám ádné další otázky. Radìji u pùjdu.}

# 11. INTRO (SLAVER) (WTG)
{315}{}{(Mladík se k tobì otoèí a prohlédne si tì od hlavy k patì. Jeho oèi se zastaví na tetování na tvém èele.) Ale ale. (Odfrkne si a poté ti plivne na nohu.) Slízni to, otrokáøi.}
{316}{}{(Mladík se k tobì otoèí a prohlédne si tì od hlavy k patì.) Ale ale. (Odfrkne si a poté ti plivne na nohu.) Slízni to, ty psí }
{317}{}{ sraèko.}
{318}{}{[Kopnout ho botou, na kterou ti plivl]}
{320}{}{[Nechat to bıt a odejít. Pro tentokrát] }

# 12. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 8, 9, 10)
{325}{}{No... já... teda, Wrightova rodina... moje rodina... by mohla mít volnej flek. Nic ti neslibuju, ale zajdi do toho baráku na jih odsud, najdi mıho bráchu Keitha a øekni mu, e tì posílám. Jmenuju se Chris. Chris Wright.}
{326}{}{Eh, Wrightova rodina? Co jsou zaè?}
{327}{}{Wright, jo? Potkal jsem tvoji matku.}
{329}{}{Díky.}
{330}{}{Díky. Mùu se na nìco zeptat?}

# 13. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 8, 9, 10)
{335}{}{Ne... vìtšinou nenabíráme nikoho, kdo není èlenem rodiny. Zkus se zeptat táty v baráku, ale nejspíš stejnì øekne ne.}
{336}{}{Tak dobøe.}

# 14. I RAN INTO YOUR MOM (NORMAL) (6, 9, 10, 11, 12)
{345}{}{(Otøepe se.) *No skvìlı.* Udìlala ti pøednášku?}
{346}{}{Tak trochu. Ty nemáš rád svoji matku?}
{347}{}{Ne. To vìtšinou dìlá?}
{348}{}{Ani ne. Poslyš, u musím jít. }

# 15. I RAN INTO YOUR MOM (INSULT) (9, 16)
{355}{}{Dìláš si SRANDU? Jestli jo, tak se ti ten fórek ani trochu nepovedl. Chceš si snad zaènout s rodinou Wrightù?}
{356}{}{Zaènout? Ne, jenom DOKONÈIT.}
{357}{}{Ne, promiò. Tak jsem to nemyslel. Poslyš, mám ještì nìjaké otázky...}
{358}{}{Ne, vùbec ne. Myslím, e radìji pùjdu. }

# 16. DO YOU NOT LIKE YOUR MOM? (14)
{365}{}{(Pokrèí rameny.) Ona se zkrátka nezajímá o vìci, co se dìjou kolem ní. Mám ji rád, ale obèas je slepá jako netopır.}
{366}{}{No, nedávno vletìla do naší palírny a celı to tam znièila! Mám ji rád, ale obèas je slepá jako netopır.}
{367}{}{Haha. A taky tak vypadá.}
{368}{}{Slepá? Jak to myslíš?}
{369}{}{Aha. Chci se ještì na nìco zeptat...}
{370}{}{Nejspíš jo. Poslyš, u radìji pùjdu. }

# 17. WHAT DO YOU MEAN? (16)
{380}{}{Chodí kolem a káe o høíchu a tak, ale vùbec neví, co vlastnì táta dìlá. A nebo to ignoruje.}
{381}{}{A co tvùj táta dìlá?}
{382}{}{Hmmmm. Poslyš, chci se ještì na nìco zeptat...}
{383}{}{Zajímavé. No, u musím jít. }

# 18. WHAT DOES YOUR DAD DO? (17)
{390}{}{Pálí chlast, prodává kvéry, mlátí lidi, kteøí s ním chtìj vymrdat... typickı rodinnı záleitosti. Matka by byla nasraná, kdyby se dozvìdìla, co vlastnì dìláme. Obzvláš kdyby našla naši palírnu.}
{391}{}{Jak moc by byla nasraná?}

# 19. HOW PISSED? (18)
{400}{}{Dost na to, aby to tady rozmlátila. A pak by nám nadávala a nìkolik dní bysme museli poslouchat to její kázání. Hehe. }
{401}{}{Zajímavé. Poslyš, chci se ještì na nìco zeptat...}
{402}{}{Hmmmmm. Díky. }

# 20. WHAT ABOUT RICHARD? (6, 8, 9, 10, 12)
{410}{}{Richard? Našli jsme ho mrtvıho ve škarpì jako nìjakıho feáka. Myslíme si, e ho nìkdo napumpoval drogama, dokud neumøel.}
{411}{}{'Nìkdo' mu toho dal moc? Jak víš, e se nepøedávkoval SÁM?}
{412}{}{Kdo si myslíš, e to udìlal?}
{413}{}{To je mi líto. Mám ještì nìjaké otázky...}
{414}{}{To je síla. Poslyš, u musím jít. }

# 21. GAVE HIM TOO MUCH? (20)
{420}{}{Protoe byl èistej... matka ho to nauèila. A jestli na to máš jinej názor, mùeme to spolu vyøešit hned teï.}
{421}{}{Tak jsem to nemyslel. Promiò.}
{422}{}{Nenech se zaslepit pøehnanou vírou ve svého bratra. Klidnì to mohl brát. Jet je vysoce návykovı.}
{423}{}{Poslyš, *chlapèe*, jestli víš, co je pro tebe dobré, pøestaò zavírat oèi nad kadou malou pravdou, která se objeví a dá ti facku.}
{425}{}{Nestojím o problémy. U pùjdu. }

# 22. I'M SORRY. I DIDN'T MEAN IT LIKE THAT (21)
{435}{}{Jo... no, dávej si pozor. To jsou slova, kterı se nelíbí ádnımu Wrightovi, take je z huby radši nepouštìj, jasnı?}
{437}{}{Poslyš, chlapèe, nezaèínej si se mnou. Jestli víš, co je pro tebe dobrı, pøestaò zavírat oèi nad kadou malou pravdou, která se objeví a dá ti facku.}
{438}{}{Promiò, nechtìl jsem tì urazit. Poslyš, chci se ještì zeptat...}
{439}{}{Rozumím. Radìji u pùjdu. }

# 23. APOLOGY FAILED (15, 21, 22)
{445}{}{Jdi do hajzlu. U ti nemám co øíct.}
{446}{}{Poèkej, jenom jednu otázku...}
{447}{}{U jdu, u jdu. }

# 24. IMPLY RICH KEPT TAKING DRUGS (15, 21, 22, 23)
{455}{}{(Chris na tebe chvíli zírá a poté se na tebe vrhne!)}
{456}{}{Tak TAKHLE ty, jo? FAJN, TAK POJÏ, TY ZMR...}

# 25. WHO DO YOU THINK DID IT? (20, 21)
{465}{}{Øekl bych, e Mordinové. Buï nìkterej z jejich dealerù, nebo nìkdo z jejich rodiny. Ti hajzlové vyrábìj tuny Jetu.}
{466}{}{Rozumím. Poslyš, chci se ještì zeptat...}
{467}{}{Kterı z dealerù myslíš, e to prodal Richardovi?}
{468}{}{Aha. Radìji u pùjdu. }

# 26. WHO DO YOU THINK SOLD IT? (25)
{475}{}{Mohl to bejt kdokoliv z tìhlech: zjizvenej zkurvysyn Poøezanej Jimmy J na rohu ulice Panen nebo starej syèák Renesco 'Rakeák', co prodává Jet v tı svı pevnosti v Obchodní ètvrti.}
{476}{}{Nìjací další dealeøi?}

# 27. WHO DO YOU THINK SOLD IT? (28)
{485}{}{Hej, kámo, DÍKY. }
{486}{}{Hej, dámo, DÍKY. }
{487}{}{Díky tobì víme, kdo zabil Richarda a celá rodina Wrightù ti za to dìkuje. A to nejsou ádnı malı díky, jasnı?}
{488}{}{Rozumím. Uvidíme se pozdìji, Chrisi. }

# 28. ANYBODY ELSE? (26)
{495}{}{Ještì Jules na kraji mìsta prodává Jet, ale vìtšinou jen turistùm... a pak je tady Malej Jeíš Mordino. Mohl ho napumpovat drogama, kdy byl Rich sám venku. Poflakuje se kolem Desperada.}
{497}{}{Poøezanej Jimmy J, Renesco Rakeák, Jules a Malej Jeíš... podívám se na nì. Díky za informace, Chrisi. }


# end lines
{1200}{}{! Takhle se Enklávì nakopává prdel!}
{1201}{}{! Jseš nejlepší!}
{1202}{}{!}
{1220}{}{. Tak jak bylo?}
{1221}{}{?}
{1222}{}{. Jak to jde?}