{150}{}{Vidíš chlapíka v pomačkaném oblečení. Mne si nos a nenápadně se rozhlíží kolem.}
{151}{}{Vidíš distributora drog.}
{152}{}{Vidíš drogového dealera. Vypadá to, že čeká na zákazníka.}
{200}{}{Nazdar, hrdino! Nechceš oslavit svoje vítězství nad Enklávou trochou toho nejlepšího Jetu? Jsem tvůj člověk!}
{201}{}{Takhle se Enklávě nakopává prdel, hrdino! Nechceš toho zachraňování světa na chvíli nechat a oslavit to trochou Jetu?}
{202}{}{::Fandí::}
{203}{}{::Píská::}
{204}{}{Není nic lepšího, než si dát trochu Jetu po zaslouženým vítězství nad Enklávou, co říkáš? Nemám pravdu?}
{205}{}{Mám matroš, kterej tě dostane až do nebe, hrdino.}
{206}{}{Nepotřebuješ píchnout?}
{207}{}{Hrdino, kdykoliv budeš chtít trochu dobroty do mozku, přijď za mnou. Dám ti speciální slevu, jenom pro tebe.}
{208}{}{Vím, co hledáš, příteli, a taky že to mám. Mám tolik Jetu, kolik jen budeš CHTÍT.}
{209}{}{Proč chodit po zemi, když můžeš lítat?}
{210}{}{Mám ten nejčistší Jet ve městě. Není zrovna levnej, ale stojí za to.}
{211}{}{Chceš lítat? Máš prachy? Pak jsem tvůj člověk.}
{212}{}{Mám matroš, po kterým se budeš cítit jako v sedmým nebi, příteli.}
{213}{}{Mám Jet. Hodně Jetu. Promluvme si.}
{214}{}{Řekni mi, jak ti můžu pomoct, hrdino. Řekni mi, co chceš a já ti dám takovou cenu, jakou ti nedá nikdo jinej široko daleko.}
{215}{}{Chceš oslavit to vítězství trochou Jetu, hrdino? Tak to jseš na správným místě. PRO TEBE je všechno se slevou.}
{216}{}{To nejmenší, co pro tebe můžu udělat, je dát ti slevu na všechno, hrdino. Je to můj způsob, jak ti poděkovat za záchranu našich zadků.}
{217}{}{Není nic lepšího, než si dát trochu Jetu po zaslouženým vítězství nad Enklávou, co říkáš? Nemám pravdu? Všechen můj matroš je se slevou.}
{218}{}{Mám matroš, po kterým se budeš cítit jako v sedmým nebi, hrdino. A speciálně pro tebe mám parádní slevu. Co tomu říkáš?}
{219}{}{Ty mít dobroty? }
{220}{}{Odbelhat se.}
{221}{}{Co nabízíš?}
{222}{}{Nic nechci, díky.}
{230}{}{Páni... jsem v přítomnosti významný osoby. Pro TEBE, kámo, mám zvláštní slevu. Jo a řekni o mně všem svým kámošům, jo?}
{231}{}{Takže ty si chceš dát trochu do nosu, co? Tak to jseš na správným místě. PRO TEBE je všechno se slevou.}
{232}{}{Mám tolik Jetu, že vyletíš až do kosmu, kámo. A speciálně pro tebe mám parádní slevu. Tak co, dohodnem se?}
{233}{}{Mám matroš, po kterým se budeš cítit jako v sedmým nebi, kámo. A speciálně pro tebe mám parádní slevu. Co tomu říkáš?}
{234}{}{To nejmenší, co pro tebe můžu udělat, je dát ti slevu na veškerý zboží, kámo. Je to můj způsob, jak bejt přátelskej.}
{235}{}{Jseš třída, víš to? Fakt třída. A když je někdo taková třída jako ty, dostane u mě parádní slevu, chápeš?}
{236}{}{Řekni, jak TI můžu pomoct, příteli. Řekni, co potřebuješ, a já ti udělám tu nejlepší cenu.}
{237}{}{Po tak namáhavym dnu je trocha Jetu potřeba, co? No nemám pravdu? Pro TEBE je všechno se slevou.}
{238}{}{Páni... jsem v přítomnosti významný osoby. Pro TEBE mám holka zvláštní slevu. Jo a řekni o mně všem svým kámošům, jo?}
{239}{}{Takže ty si chceš dát trochu do nosu, holka? Tak to jseš na správným místě. PRO TEBE je všechno se slevou.}
{240}{}{Mám tolik Jetu, že vyletíš až do kosmu, holka. A speciálně pro tebe mám parádní slevu. Tak co, dohodnem se?}
{241}{}{Mám matroš, po kterým se budeš cítit jako v sedmým nebi, holka. A speciálně pro tebe mám parádní slevu. Co tomu říkáš?}
{242}{}{To nejmenší, co pro tebe můžu udělat, je dát ti slevu na veškerý zboží, holka. Je to můj způsob, jak bejt přátelskej.}
{247}{}{Vím, co hledáš, otrokáři, a taky že to mám. Mám tolik Jetu, kolik jen budeš CHTÍT.}
{248}{}{Proč chodit po zemi, když můžeš lítat? Ty máš škváru, já mám zboží.}
{249}{}{Mám nejčistší Jet ve městě, otrokáři. Není zrovna levnej, ale stojí za to.}
{250}{}{Chceš si zalítat, otrokáři? Máš prachy? Pak jsem tvůj člověk.}
{251}{}{Mám matroš, po kterým se budeš cítit jako v sedmým nebi, otrokáři.}
{252}{}{Mám Jet. Hodně Jetu. Promluvme si.}
{253}{}{Mám tolik Jetu, že vyletíš až do kosmu, otrokáři. Tak co, dohodnem se?}
{254}{}{Nepotřebuješ píchnout, otrokáři? Mám ten nejlepší Jet široko daleko.}
{255}{}{Sháníš Jet? Tak pojď, otrokáři, promluvme si.}
{256}{}{Sháníš Jet? Tak pojď, otrokáři, ty a já hodíme řeč.}
{261}{}{Vím, co hledáš, příteli, a taky že to mám. Mám tolik Jetu, kolik jen budeš CHTÍT.}
{262}{}{Proč chodit po zemi, když můžeš lítat?}
{263}{}{Mám nejčistší Jet ve městě, otrokáři. Není zrovna levnej, ale stojí za to.}
{264}{}{Chceš si zalítat? Máš prachy? Pak jsem tvůj člověk.}
{265}{}{Mám matroš, po kterým se budeš cítit jako v sedmým nebi, příteli.}
{266}{}{Mám Jet. Hodně Jetu. Promluvme si.}
{267}{}{Mám tolik Jetu, že vyletíš až do kosmu, příteli. Tak co, dohodnem se?}
{268}{}{Nepotřebuješ píchnout, otrokáři? Mám ten nejlepší Jet široko daleko.}
{269}{}{Sháníš Jet? Tak pojďme obchodovat.}
{270}{}{Sháníš Jet? Promluvme si.}
{519}{}{ RÁD dobroty!}
