{100}{}{Vidíš Myrona! Myron, jó, Myron!}
{150}{}{Vidíš bledého puberáka, kterı po tobì pokukuje. Má mastné vlasy a lehce páchne po formaldehydu.}
{151}{}{Vidíš Myrona. Nenápadnì po tobì pokukuje.}
{200}{}{Vidíš bledého puberáka. Má mastné vlasy a lehce páchne po formaldehydu.}
{201}{}{Vidíš Myrona. Rozhlíí se kolem jako nìjakı špeh.}
{202}{}{Vidíš Myrona. Posmrkává, jako kdyby mìl rımu.}
{203}{}{Vidíš Myrona. Vypadá znudìnì.}
{204}{}{Vidíš Myrona. Zívá a mne si oèi.}
{210}{}{Zvednìte ty svı zadky a pojïte sem, chlapi! Máme tu vetøelce!}
{215}{}{Co sakra chceš?}
{216}{}{Jestli jseš tady kvùli Jetu, tak na to zapomeò a vypadni.}
{217}{}{Nìco tady smrdí...}
{225}{}{Nazdárek, krásko.}
{226}{}{Pojï ke mnì na chvilku. Neboj, nekoušu.}
{227}{}{Pøestaò mì škádlit a pojï blí.}
{228}{}{Myslím, e jsem se právì zamiloval.}
{229}{}{Chodíš sem èasto?}
{230}{}{Mmmm-mmmm. Máš krásnı dlouhı nohy.}
{235}{}{Co je to za smrad? Smrdí to jako divoch.}
{236}{}{Fajn kost co má ten tvùj kámoš. Fakt stylovı.}
{237}{}{Ten divoch je tvùj otrok?}
{238}{}{Nekompenzuje si ten tvùj divoch nìco?}
{239}{}{Jak se sem ta vìc sakra dostala?}
{240}{}{No skvìlı. Teï u sem pouštìj i mutanty.}
{241}{}{Víš urèitì, e je dobrı nápad tahat sebou mutanta?}
{242}{}{Ten mutant je tvùj otrok?}
{243}{}{Jak rychle se ten tvùj hnusnej mutantí kámoš naštve?}
{244}{}{Co je to za smrad? Smrdí to jako mutant.}
{255}{}{Co to tady smrdí? Jako by tu nìco chcíplo.}
{256}{}{No skvìlı. Teï u sem pouštìj i ghouly.}
{257}{}{Ten ghoul by potøeboval vyvenèit. Pìknì smrdí.}
{258}{}{Není ten ghoul radioaktivní?}
{259}{}{Nechceš toho ghoula pomazat skunkem? Urèitì by vonìl líp.}
{265}{}{Budeme u taky nìco dìlat?}
{266}{}{Pojïme sbalit nìjakı enskı v tomhle strašnım ohozu.}
{267}{}{Co takhle jít nìkam, kde je víc enskejch?}
{268}{}{Mùeš dìkovat nebesùm, e jsem s tebou a upozoròuju tì na všechny tvoje hloupı chyby.}
{375}{}{Hej, já tady umírám! Dej mi u koneènì Stimpak!}
{376}{}{To je moje krev?}
{377}{}{Medik!}
{378}{}{Auuuuuuu. Kurva! Auuu, to bolí!}
{379}{}{Au! To štípe!}
{380}{}{Auuuuuuuuuuuu auuuuuuu Au. Au. Au?}
{381}{}{Auuuu. Ké by mì tak NÌKDO obvázal.}
{390}{}{Dej mi Stimpak nebo omdlím!}
{391}{}{Dej mi sakra Stimpak! Jsem v šoku!}
{392}{}{Dejte mi nìkdo rychle první pomoc! Umírám tady!}
{400}{}{Jejda... jsem nìjakej slabej...}
{401}{}{Hmm... zvedá se mi aludek... zvıšenej tep... horeèka. To bude nejspíš jed.}
{402}{}{Eh... u... dlouho... nevydrím... jed... se... šíøí...}
{403}{}{Mùe ze mì nìkdo prosím vysát ten jed?}
{410}{}{Is that me glowing? Give me some Rad-X next time we dick around in radiation zones, okay?}
{411}{}{I need some RadAway before the radiation eats my Gnads-away.}
{412}{}{Co kdybysme se pøíštì toho radioaktivního slizu rovnou napili? Aspoò chcípneme rychleji!}
{413}{}{Svım tìlem bych mohl osvìtlovat celı New Reno.}
{414}{}{I'm glowing brighter than New Reno at midnight. Anybody got some RadAway?}
{415}{}{No skvìlı. Trocha radiace a hned je ze mì lidská baterka.}
{416}{}{Somebody let me hold the RadAway. I won't use all of it. I promise.}
{425}{}{Co kdybysme se vrátili do prvního patra dungeonu mezi koboldy?}
{426}{}{Ještì, e jsem hrával Draèí Doupì. Za ty roky jsem se nauèil pár vìci o odvaze.}
{427}{}{Podej mi Buffout. Asi ho budu brzo potøebovat.}
{428}{}{Skvìlı místo. Fakt skvìlı místo. Co kdybysme se tu zdreli jen na chvíli?}
{429}{}{Jó, tohle je fakt MNOHEM lepší, ne bejt v nìjakım útulnım bordelu.}
{430}{}{Rychle dovnitø, rychle ven, jasnı?}
{431}{}{Co kdybysme se sem podívali pozdìji?}
{432}{}{Proè tu sakra jsme?}
{433}{}{Tohle místo mi nièí morálku.}
{434}{}{Navrhuju, abysme poslali Kostìnıho Nosa na prùzkum okolí. Samotnıho.}
{435}{}{Co kdybysme poslali Kostìnıho Nosa na prùzkum okolí?}
{445}{}{Co kdybysme poslali Marcuse na prùzkum okolí?}
{446}{}{Navrhuju, abysme poslali Marcuse na prùzkum okolí. Samotnıho.}
{447}{}{Podej mi Buffout. Asi ho budu brzo potøebovat.}
{448}{}{Co kdybysme se vrátili do prvního patra dungeonu mezi koboldy?}
{449}{}{Ještì, e jsem hrával Draèí Doupì. Za ty roky jsem se nauèil pár vìci o odvaze.}
{450}{}{Skvìlı místo. Fakt skvìlı místo. Co kdybysme se tu zdreli jen na chvíli?}
{451}{}{Jó, tohle je fakt MNOHEM lepší, ne bejt v nìjakım útulnım bordelu.}
{452}{}{Rychle dovnitø, rychle ven, jasnı?}
{453}{}{Co kdybysme se sem podívali pozdìji?}
{454}{}{Proè tu sakra jsme?}
{455}{}{Tohle místo mi nièí morálku.}
{456}{}{Navrhuju, abysme poslali Lennyho na prùzkum okolí. Samotnıho.}
{457}{}{Co kdybysme poslali Lennyho na prùzkum okolí?}
{465}{}{Hej, díky. To mi fakt bodlo.}
{466}{}{Není nad poøádnou dávku pøímo do íly.}
{467}{}{Doufám, e to neznamená, e jsme svoji, e ne?}
{468}{}{Nemáš nìjakou trávu?}
{469}{}{Co kdybych nesl Stimpaky já?}
{470}{}{Ááááááááách.}
{471}{}{Óóóóóóóch. Áááááááách. Mmmmmm.}
{472}{}{Miluju, kdy tohle dìláš.}
{473}{}{Drogy mì vdycky úplnì omámí.}
{485}{}{Hej, nedávej mi tu sraèku! Nech si to pro závisláky!}
{486}{}{Hele, já lítat nechci a ty taky ne. Zahoï tu sraèku nìkam.}
{487}{}{Co kdybys tu sraèku dal Kostìnımu Nosovi?}
{495}{}{Co kdybys tu sraèku dal Marcusovi?}
{496}{}{Hej, nedávej mi tu sraèku! Nech si to pro závisláky!}
{497}{}{Ty vole, já lítat nechci a ty taky ne. Zahoï tu sraèku nìkam.}
{498}{}{Co kdybys tu sraèku dal Lennymu?}
{505}{}{Dobøe, dobøe. U jdu na to.}
{506}{}{Zùstaò vzadu, idiote. Já na to pøijdu.}
{507}{}{To vypadá jednoduše. Zùstaò vzadu, jasnı?}
{508}{}{ádnı problém.}
{509}{}{Èas na mı 'kouzelnı prstíky'...}
{515}{}{Bingo!}
{516}{}{Heuréka!}
{517}{}{Jo kurva!}
{518}{}{Myron to opìt dokázal. Dav šílí!}
{519}{}{Hele, nìco jsem našel.}
{520}{}{Hotovo. Finito.}
{521}{}{Lehèí ne jezdit na kole. Nebo na tvı matce! Hahahahaha!}
{522}{}{Ano. Myron je... bùh vìdy.}
{523}{}{Cink. Myron úspìšnì pouil dovednost VÌDA.}
{530}{}{No nic.}
{531}{}{Nada.}
{532}{}{Smùla.}
{533}{}{Do hajzlu! Zkusil jsem všechno...}
{534}{}{S tím nic nesvedu.}
{535}{}{Na nic jsem nepøišel. Prozatím.}
{536}{}{Moná, e bych to s Mentats zvládl... mmmm. Mentats.}
{537}{}{Nemám na to dostateènì vysokou dovednost. Dej mi pár dovednostních bodù a pak to mùu zkusit znovu. Haha.}
{538}{}{Nic jsem se nenauèil.}
{539}{}{Za tìchto podmínek nedokáu uspìt v hodu na dovednost Vìda.}
{540}{}{Cink. Myron neúspìšnì pouil dovednost VÌDA.}
{550}{}{Dobøe, dobøe! Pøestaò do mì strkat!}
{551}{}{Pøestaò do mì strkat, nebo tì... no, prostì do mì pøestaò strkat.}
{552}{}{Dobøe, TAK PROMIÒ.}
{553}{}{Tak dobøe, ale pøíštì uhneš TY MNÌ.}
{554}{}{Já tu byl první, ale a je po tvım.}
{560}{}{To mi nemusíš øíkat dvakrát.}
{561}{}{Spíš by mì vyléèilo trochu enskı lásky, jestli mi rozumíš.}
{562}{}{Ááááách. Ještì, e nejsou Stimpaky tak návykovı.}
{563}{}{Jo jó. Ještì, e nejsou Stimpaky tak návykovı.}
{570}{}{Nepíchej do mì tu sraèku. Je mi fajn, jasnı?}
{571}{}{Nestarej se furt o mì. Jsem v poøádku.}
{572}{}{Vykašli se na to. Jsem v poøádku. Ale ty Stimpaky klidnì ponesu, jestli chceš.}
{580}{}{Hej, chci se k tobì zase pøidat! No ták!}
{581}{}{Promiò, e jsem byl takovej kretén. Dej mi ještì jednu šanci.}
{582}{}{U je mi z toho èekání blbì.}
{583}{}{Já se tak nudím. No ták, nechceš, abych to s tebou zase chvilku táhnul?}
{584}{}{Mìl jsem si vzít knihu.}
{585}{}{U na tebe NEBUDU dál èekat.}
{590}{}{Hele... Miria je fakt tvoje stará?}
{591}{}{Miria je docela kost. Mohl bych... no, však víš... co ty na to?}
{592}{}{Tvoje ena vypadá faaaakt dobøe.}
{593}{}{Take... ty a Miria. Je to s váma vánı, nebo...?}
{594}{}{Take... ty a Miria. Jste spolu nezávaznì, nebo...?}
{595}{}{Nechceš si vymìnit manelky? Pùjèím ti svoji, a si nìjakou najdu.}
{596}{}{Hele... kdo je ta sexy asiatka?}
{597}{}{Kitsune je docela kost. Mohl bych... no, však víš... co ty na to?}
{598}{}{Ta asiatka vypadá faaaakt dobøe.}
{599}{}{Take... ty a Kitsune. Chodíte spolu nebo tak nìco?}
{600}{}{Mùeme jít?}
{605}{}{Proè TADY sakra jsme?}
{606}{}{Všichni by v tomhle mìstì potøebovali klystır.}
{607}{}{Z Vault City se mi dìlá... špatnì.}
{608}{}{Proè se mi chce z Vaulty City blejt?}
{609}{}{Kdy se vrátíme do Rena?}
{615}{myn102b}{Take jsi koneènì zpátky, co? Vìdìl jsem, e se vrátíš. Potøebuješ mì.}
{616}{myn102a}{Take jsi koneènì zpátky, co krásko? Vìdìl jsem, e se vrátíš. Dobøe, pøidám se zas k tobì.}
{617}{myn103a}{Jo, co je? Nevidíš, e pøemejšlím?}
{618}{myn103b}{Take jsi koneènì dostala rozum, krásko? Pochopila jsi, e já jsem pro tebe ten jedinej?}
{619}{}{Nevypadáš moc dobøe, Myrone. Uzdrav se.}
{620}{}{Poèkej tady, dokud se, eh, nevrátím.}
{621}{}{Schovej tu zbraò, nebo si ublííš.}
{622}{}{Dr se blízko mì.}
{623}{}{Dr se trochu dál, Myrone.}
{624}{}{Odstup trochu, Myrone. Bude to tak pro oba lepší.}
{625}{}{Mám nìjaké otázky...}
{626}{}{Teï ne, Myrone. Mám nìjaké otázky...}
{627}{}{Tak dobøe. Pospìš si a pùjdeme.}
{628}{}{Ne, zùstaneš tady. Vrátím se pro tebe, slibuju.}
{629}{}{V tom pøípadì tì nechám pokraèovat v nic nedìlání.}
{630}{}{Myrone, tvoje ruka je ta "jediná" pro tebe.}
{640}{myn105_b}{Je to nìkde u Golgoty... dám ti vìdìt, a pùjdeme kolem.}
{641}{}{Dobøe, Myrone.}
{645}{myn106}{Jo. Co chceš vìdìt?}
{646}{}{Povìz mi nìco o Jetu.}
{647}{}{Mùeš mi udìlat nìjaké drogy?}
{648}{}{Nevypadáš zrovna nejlépe, Myrone. Zkus se dát do poøádku.}
{650}{}{Kde je ta Mordinova skrıš, o které jsi mluvil?}
{655}{myn107a}{Á, moje malé mistrovské dílko. Co s ním?}
{656}{myn107b}{To u jsme pøece probírali. Nejsem tvoje osobní databanka.}
{657}{myn107c}{To u jsme pøece probírali. Podívej, klidnì budu tvùj otrok lásky, krásko, ale ne tvoje osobní databanka.}
{658}{}{Jak jsi ho vytvoøil?}
{659}{}{Je na nìj nìjakı lék?}
{660}{}{Mùeš mi udìlat nìjakı Jet?}
{661}{}{Udìlám z tebe mrtvolu, jestli mi neodpovíš na moje otázky. Jak jsi vytvoøil Jet?}
{662}{}{Nech tìch kecù, Myrone. Je na Jet nìjakı lék?}
{664}{}{To si radìji propíchnu vøedy jazykem, ne abys byl mım otrokem lásky, Myrone.}
{665}{}{Myrone, 'otrok lásky' je ta poslední vìc, která mì napadne, kdy si na tebe vzpomenu.}
{666}{}{Vlastnì jsem spíš pøemıšlela o tom, e si z tebe místo otroka lásky udìlám cviènı terè.}
{667}{}{To radìji políbím Sulika, ne abys byl mım otrokem lásky. Eh... bez uráky, Suliku.}
{668}{}{To radìji políbím Marcuse, ne abys byl mım otrokem lásky. Eh... bez uráky, Marcusi.}
{669}{}{Zapomeò na to, Myrone.}
{680}{myn108}{Eh, ve svı laboratoøi. Další otázka?}
{681}{}{JAK jsi ho vytvoøil, chytráku?}
{682}{}{Zapomeò na to. Zmìòme téma...}
{683}{}{Tohle nikam nevede. Zapomeò na to, Myrone.}
{690}{myn109}{Jeíš. No... kdy jsem kdysi dávno narazil na Mordiny, pìstovali pejotlovı kaktusy a pokoušeli se to prodat turistùm jako 'záitek z Rena.' Taková hovadina.}
{691}{}{Pokraèuj.}
{692}{}{Forget this. I had some other questions...}
{693}{}{Zapomeò na to.}
{700}{myn110}{Proè zrovna pejotl? Takovej nesmysl. Vdy to nemá ani polovièní úèinek v porovnání tøeba se starım dobrım LSD.}
{701}{}{Eh, no a co ten Jet?}
{710}{myn112}{Navíc, pejotlovej trip je moc dlouhej. Zisky jsou tam, kde je krátkodobej úèinek a vysoká závislost jako tøeba, eh, barbituráty pøed Velkou Válkou, víš?}
{711}{}{Doufám, e tohle nìkam vede.}
{712}{}{Kdy to øíkáš.}
{713}{}{Barbituráty... jako tøeba kokain, krek a tak?}
{714}{}{Myslíš barbituráty jako tøeba kokain, krek a tak?}
{716}{}{Zapomeò na to, Myrone. Nemám èas na ty tvoje zdlouhavı kecy.}
{725}{myn113a}{Pøesnì. Mùu to dokonèit? }
{726}{myn113b}{Problém je v tom, e máme novı klima a v nìm neroste vìtšina zeleninky, ze kterı se dìlají ty nejlepší drogy.}
{727}{}{Ty se rád posloucháš, e jo?}
{728}{}{Poslouchám.}
{729}{}{'Zeleninky'? Myslíš tøeba koku, mák a takovı vìci?}
{740}{myn114a}{Nedokáeme vypìstovat koku ani mák... a e jsme to fakt zkoušeli. Take jsme usoudili, e naší nejvìtší nadìjí jsou houby.}
{741}{myn114b}{Pøesnì tak, Sherloku. Zkoušeli jsme to, ale ani uk. Take jsme usoudili, e naší nejvìtší nadìjí jsou houby.}
{742}{myn114c}{Protoe se dají vypìstovat, kdy pouiješ dost brahmíních hoven jako hnojivo.}
{743}{}{Kdy u mluvíš o hovnech... pokraèuj.}
{744}{}{Aha...}
{755}{myn115}{A navíc, halucinogeny mají nízkej vrchol, take jsem zaèal experimentovat s deriváty diethylamid kyseliny lysergové a psilocybinem. Ale poøád...}
{756}{}{Ale poøád co?}
{765}{myn116}{Ale poøád jsem chtìl namíchat nìjakou poøádnou bombu, která by nebyla zaloená na extraktech ze zeleninek. Byl jsem pìknej idiot, páè se ukázalo, e odpovìdí JSOU právì ty extrakty nebo lépe øeèeno to, v ÈEM rostou.}
{766}{}{Tebe vùbec nezajímá, co øíkám, e? Ty prostì rád vyprávíš svùj pøíbìh.}
{767}{}{Jak to myslíš?}
{775}{myn117}{Víš, starej Jeíš Mordino chtìl nìco, na èem by se horníci z Reddingu stali rychle závislí a co by je donutilo víc pracovat. Tak jsem mu øekl 'no problemo,' jasnı?}
{776}{}{Vysvìtli mi to s tím Reddingem.}
{777}{}{Vysvìtli mi ještì jednou to s tím Reddingem.}
{778}{}{Jasnı. Pokraèuj.}
{779}{}{Jo, no problemo.}
{790}{myn118}{No, nebylo moc tìkı najít ten správnej vylepšovák. Staèilo vzít vzorek pøedváleènıho proteinovıho extraktu, udìlat pár úprav a BUM... máme slušnej amfetamin.}
{791}{}{Vysvìtli mi ještì jednou to s tím Reddingem.}
{792}{}{Eh, "proteinovı extrakt?"}
{800}{myn119}{Redding? To je mìsto plnı zlatokopù. Mordino ho chce mít celı pod palcem, take jednoho dne pøišel za mnou a zaèal sípat tím svım hlasem: 'Myrone, Myrone, vytvoø mi nìco, èím si podmaním Redding.'}
{801}{}{A ty jsi øekl...}
{810}{myn120}{A já øekl, 'Fajn, kdy to má bejt hotovı?' A on samozøejmì øekl: 'Vèera bylo pozdì.' Mafiáni. Chtìj mít všechno rychle hotovı a nedodìlanı. Aspoò, e nemaj marketingovı oddìlení.}
{811}{}{Aha. Vra se k tvorbì Jetu.}
{820}{myn121}{Nìkterı masnı spoleènosti experimentovaly pøed Velkou Válkou s levnım proteinovım extraktem na zvıšení produkce jídla, ale museli se na to vykašlat. Staèila jedna malá koní bakterie a všechno bylo v hajzlu.}
{821}{}{V hajzlu? Jak to?}
{830}{myn122}{Ta kontaminovaná verze se po spolknutí chovala jako amfetamin. Takovı drobnı vedlejší efekt. Neptej se mì, jak je to monı. Je to trochu, eh, odbornı.}
{831}{}{Take... jsi nìjakım zpùsobem získal ten proteinovı extrakt?}
{840}{myn123}{To nebylo tøeba. Kdy to podìlali poprvı, zakontaminovali tuny tìch sraèek. A ne aby to vyhodili, nakrmili s tím svoje brahmíny, aby se jim aspoò trochu vrátily ztráty.}
{841}{}{Eh, dobøe...}
{842}{}{Doufám, e to nìkam vede, Myrone.}
{843}{}{Take jsi pouil brahmíní hovna jako hnojivo pro houby, a na to, e ten pøedváleènı kontaminovanı protein díky nim získal... jisté ingredience navíc?}
{850}{myn124a}{Pøihoøívá...}
{851}{myn124b}{Víš, kdy jsme zaèali experimentovat s brahmíníma hovnama jako hnojivem pro houby, tak jsme si všimli, e otroci pracující u kádí s hnojivem byli zfetovaní z vıparù...}
{853}{}{Take jen samotné vıpary staèily na to, aby byli zfetovaní?}
{860}{myn125a}{Pøeeeesnì...}
{861}{myn125b}{Zjistili jsme, e kdy do kádí nacpeme tuny brahmíních sraèek, tak ty vıpary mají víc ne dostateènej úèinek. Heuréka. Doslova. Samozøejmì jsme ale museli udìlat nìjakı testy, abysme získali ten správnej pomìr...}
{862}{}{Eh, kolik jste toho otestovali?}
{863}{}{Kolik jste toho pøesnì otestovali?}
{865}{}{Zapomeò na to, Myrone.}
{866}{}{To zní jako hromada sraèek... doslova. Zdá se mi, e toho o vırobì drog moc nevíš. "Vıpary z brahmíních hoven?" Prosím tì. U to nebudu poslouchat.}
{870}{myn126}{Hmmm... asi sto otrokù? Vìtšinou dostali infarkty, krvácení do mozku, psychotickı záchvaty... a tak podobnì.}
{871}{}{Zbláznil ses? Ty jsi zabil pøes sto lidí jen kvùli otestování drogy?!}
{872}{}{Tak to jo... pøeci jen Jet dokáe bıt poøádnì silná potvora. Aspoò, e neumøel nikdo dùleitı. Ale i pøesto se mi nechce uvìøit, e jsi jich zabil tolik...}
{873}{}{Aha. Mám ještì nìjaké otázky...}
{880}{myn127}{No, ne bezdùvodnì. Víš, otroci jsou dost drazí. Ale naštìstí jsme ztráty vyrovnali bìhem nìkolika prvních mìsícù, take na mì Mordinové nebyli moc nasraní.}
{881}{}{Myslím, e my dva spolu budeme vycházet, Myrone. Pøeci jen, úèel svìtí prostøedky. Mám ještì nìjaké otázky...}
{882}{}{Myrone, ty jsi neuvìøitelnı mizera. Zabíjet lidi kvùli testování drog... to je ta nejvìtší podlost, jaká existuje.}
{883}{}{Ty jsi zabil pøes sto lidí jen kvùli otestování drogy? Nevyoperovali ti náhodou svìdomí u jako malému dítìti?}
{884}{}{To mi povídej. Ceny otrokù jdou poøád nahoru. Ké by se tak lidé mnoili rychleji. Nicménì, mám ještì nìjaké otázky...}
{885}{}{I... see. Look, I had some other questions...}
{886}{}{To u by staèilo, u to nebudu poslouchat.}
{887}{}{Aha, take je TO vlastnì v poøádku. U to nebudu poslouchat. Odcházím.}
{890}{myn128}{Mám se snad podìlat kvùli pár otrokùm? Hele, museli jsme se pøesvìdèit, e je Jet pro naše zákazníky bezpeènej.}
{891}{}{To je fakt, Myrone. Mám ještì nìjaké otázky...}
{893}{}{Aha, take je TO vlastnì v poøádku. Gratuluju, Myrone, dosáhl jsi toho nejhlubšího morálního dna, jakého kdy mùe lidská bytost dosáhnout. Odcházím.}
{894}{}{To zní rozumnì. Moná si popovídáme pozdìji.}
{900}{myn129a}{To je legraèní. Lék? No to urèitì. Staèí ho úplnì pøestat brát, ale to samozøejmì není tak snadnı, o to jsem se postaral.}
{901}{myn129b}{Hele, krásko, mluvíme tu o závislosti na drogách a ne o nìjakı chøipce nebo angínì. Jedinej lék je pøestat brát Jet, hehe, ale to není zrovna snadnı.}
{902}{}{Jak jsi vytvoøil Jet?}
{903}{}{Myrone, vdy ty jsi pìknì chytrı chlapík. Ber to jako vızvu. Co by bylo zapotøebí k vytvoøení léku na Jet?}
{910}{myn130}{To nejde kurva, chápeš? Je to droga a ne nìjaká bakteriální infekce.}
{911}{}{V podstatì je to vysoce návykovı meta-amfetamin, e? Nemohl bys ke sníení závislosti pouít tøeba tlumièe nervové soustavy?}
{913}{}{Zapomeò na to, Myrone.}
{920}{myn131}{Zajímavej nápad, ale nepouitelnej. Jet se nedá tak snadno utlumit. Jakmile ho máš v sobì, nedostaneš ho pryè.}
{921}{}{A co takhle pouít nìjakı blokátor endorfinù? To by potlaèilo chemickou i psychickou závislost, ne?}
{924}{}{Tak nic.}
{930}{myn132}{Jeíš, to je ten nejblbìjší... hmmmm...}
{931}{}{Ano?}
{940}{myn133}{No... moná by to mohlo fungovat, ale jsem si jistej, e se Jet pøes tu sraèku stejnì prokouše. A p-p-proè se o tom vùbec bavíme?! K-kde chceš vlastnì vzít ty endorfinové blokátory?}
{941}{}{To mi øekni ty, Myrone. Chytrı jsi na to dost.}
{950}{myn134}{Moná ve Vault City. Mají docela dobrej sklad chemikálií. A spousta starejch pøed-holokaustovejch základen je mìla na skladì kvùli prevenci závislosti na bojovejch drogách.}
{951}{}{Take mám zkusit Vault City?}
{952}{}{Pøed-holokaustové základny? Kde?}
{954}{}{Tak dobøe. Snad je nìkde najdu.}
{960}{myn135}{Ha! To se ti spíš podaøí pøesvìdèit radškorpiona, aby si nechal uøíznout ocas, ne pøesvìdèit Vault City, aby ti nìco dali.}
{961}{}{A co ty pøed-holokaustové základny? Kde se nachází?}
{962}{}{Jo, moná. Mám ještì nìjaké otázky...}
{963}{}{Za pokus nic nedám.}
{970}{myn136}{Vypadám snad jako nìjakej kartograf? Ale jestli je chceš hledat v poušti, tak si klidnì poslu.}
{971}{}{A co Vault City?}
{973}{}{Tak díky za nic, Myrone.}
{974}{}{To moná udìlám.}
{980}{myn137}{Hehe... s takovım dùvtipem dostaneš urèitì èasem rozum a budeš mì chtít, krásko. Uvidíš.}
{981}{}{Kdy myslíš... jak jsi vytvoøil Jet?}
{983}{}{Jo, uvidíme. Mùeš mi udìlat nìjakı Jet?}
{985}{}{Zapomeò na to, Myrone.}
{990}{myn139}{C-c-oooo? Dìláš si kurva srandu? Prr, prr, hej, hej... kdy mì necháš jít s tebou, prokáu ti laskavost. Co? C-co øíkáš?}
{991}{}{Jakou laskavost?}
{992}{}{O laskavosti nemám zájem. A teï odpal, ty otravnı hovado.}
{993}{}{O laskavosti nemám zájem. A teï tu poèkej, ty otravnı hovado.}
{994}{}{Zapomeò na to. Mùeš zùstat.}
{1005}{myn140}{Ohó! Aha, t-t-take to byl jenom nìjakej divošskej vtípek, jo? Buehehehe. Fakt kurva sranda.}
{1006}{}{Jo, my divoši jsme tím proslulí. Pojïme.}
{1010}{myn141}{Dobøe! Dobøe! Poèkám tady, ale zaslouím si trochu vìtší respekt, víš. Jsem toti MYRON.}
{1020}{myn142a}{Slyšel jsem o tajnı budovì se spoustou podivnı vegetace. Kdy budu s tebou, mùu ti jí ukázat na mapì.}
{1021}{myn142b}{Moná vím o jednı malı skrıši Mordinù v Golgotì poblí Rena. Spousta zátek. Spousta drog. Jen mì musíš vzít s sebou.}
{1022}{myn142c}{Já... budu nosit víc tvejch vìcí! A nebudu remcat, kdy budeš chtít udìlat drogy! Jen mì musíš vzít s sebou, jasnı?}
{1023}{}{Dobøe. Mùeš zùstat.}
{1026}{}{Zapomeò na to, Myrone. Poèkej tady, ne se vrátím.}
{1035}{myn143a}{"Jestli mùu udìlat nìjaké drogy?" Jsem pøece Myron. Co potøebuješ?}
{1036}{myn143b}{Copak, u ti došly? Co potøebuješ?}
{1037}{}{Protijed na radškorpioní jed.}
{1038}{}{Jet.}
{1039}{}{Stimpaky.}
{1040}{}{Mùeš udìlat nìjaké Super-Stimpaky?}
{1041}{}{Nic. Mám nìjaké otázky...}
{1042}{}{Zapomeò na to.}
{1050}{myn145a}{Eh, nejdøív budu potøebovat pár radškorpioních jedovıch váèkù. Ironie, e?}
{1051}{myn145b}{No, víš, to bych moc rád, krásko, ale potøebuju radškorpioní ocasy.}
{1052}{}{Mùeš udìlat nìjaké jiné drogy?}
{1053}{}{Forget it then. I had some questions...}
{1060}{myn146a}{Hmmm, to by nemìlo bejt moc tìkı. Kolik tìch lahví chceš?}
{1061}{myn146b}{Jeišimarjá. Nenapadlo tì nìkdy, e by bylo lehèí se tìm blbejm radškorpionùm radši vyhnout, Einsteine? Kolik jich chceš tentokrát?!}
{1062}{myn146c}{Pro tebe cokoliv, krásko. Hehe. Kolik jich chceš?}
{1063}{}{Jenom jednu.}
{1065}{}{Tøi budou akorát.}
{1066}{}{Udìlej protijedy ze všech ocasù, které máme. Stejnì jsou jinak k nièemu.}
{1067}{}{Zapomeò na to. Mùeš udìlat nìjaké jiné drogy?}
{1068}{}{Ani jednu. Mám nìjaké otázky...}
{1081}{myn147a}{Hotovo. Tady to máš.}
{1082}{myn147b}{Tady máš. A u dost. U ty sraèky nechci ani vidìt, jasnı? Pøíštì si na to najdi nìjakıho medicinmana.}
{1083}{myn147c}{Hotovo. Tady to máš, krásko.}
{1085}{}{Díky. Mám ještì nìjaké otázky...}
{1086}{}{Díky, Myrone. Jsi opravdovı pøítel.}
{1095}{myn148}{Promiò, nemám na to ty "suroviny", kterı potøebuju... a ani je nechci shánìt.}
{1097}{}{Forget it then. I had some other questions...}
{1098}{}{Dobøe. Fakt díky, Myrone.}
{1105}{myn149a}{To je hraèka. Kolik jich chceš?}
{1106}{myn149b}{Hele, ty Einsteine. Nenapadlo tì nìkdy, e by bylo lehèí si dávat vìtší pozor, co? No dobøe, kolik?}
{1107}{myn149c}{Staèí øíct kolik a kde je chceš mít, krásko.}
{1111}{}{Udìlej jich tolik, kolik jich mùeš udìlat z toho co máme.}
{1113}{}{Mùeš udìlat nìjaké Super-Stimpaky?}
{1114}{}{Zapomeò na to. Mám nìjaké otázky...}
{1125}{myn151}{Promiò, nemáme u sebe nic, z èeho by se dal spíchnout Stim. Potøebuješ koøen Xanderu, kvìtinu Broc... a prázdnou støíkaèku.}
{1126}{}{Mùeš udìlat nìjaké jiné drogy?}
{1127}{}{Kdy dokáeš udìlat Stimpaky, nemohl bys taky udìlat nìjaké Super-Stimpaky?}
{1128}{}{Tak dobøe. Mám nìjaké otázky...}
{1135}{myn152}{Samozøejmì, e bych mohl... akorát, e na to nemáme suroviny. Potøebuju nìjakı zmutovanı ovoce, abych získal kyselinu citrónovou... trochu Nuka Coly... a normální Stimpak.}
{1145}{myn153a}{Opakuj po mnì: Myron je génius. Kolik jich chceš?}
{1146}{myn153b}{Co takhle. Si. Dávat. Pozor? No nic, asi je to pro tebe moc sloitı. Kolik jich chceš tentokrát?}
{1147}{myn153c}{K slubám, krásko. Kolik jich chceš?}
{1149}{}{Udìlej mi dva.}
{1151}{}{Udìlej jich tolik, kolik jich mùeš udìlat z toho co máme.}
{1170}{myn201a}{Kdo jsi a kde se tady sakra bereš? K-kde jsou ti kreténi, co mì mají hlídat?}
{1171}{myn201b}{Panejooooo. Nazdárek, krásko. Co ti, eh, co pro tebe mùe Myron udìlat?}
{1172}{}{Brı. Ne-e.}
{1173}{}{Nazdárek Moron. Já }
{1174}{}{Brı. Mrtvej.}
{1175}{}{Slabı lidi u dveøe nedıchat kdy já zabít je.}
{1176}{}{Pá-pá.}
{1177}{}{Tvoje stráe mají teï dost práce s posmrtnım ivotem.}
{1178}{}{Mám tuhle ID kartu. Posílá mì Marjorie.}
{1179}{}{Kdo jsi?}
{1180}{}{Ty jsi Myron?}
{1181}{}{Klídek, tygøe. Zklidni hormony. Kdo jsi?}
{1182}{}{Klídek, tygøe. Zklidni hormony. Ty jsi Myron?}
{1183}{}{Promiò. Asi jsem ve špatné místnosti.}
{1195}{myn202}{No dobøe, take kdo jsi? Vyklop to, nebo øeknu stráím, a to z tebe VYMLÁTÍ.}
{1196}{}{Tvoje stráe teï mají moc práce s posmrtnım ivotem, take ti jsou k nièemu. Ještì nìjakı otázky, ty malej sráèi?}
{1197}{}{Kdo jsi?}
{1198}{}{Ty jsi Myron?}
{1199}{}{Myslím, e bude nejlepší, kdy odsud odejdu. Bylo mi potìšením.}
{1205}{myn203}{No skvìlı, mentální zakrslík z pustiny. Hele, moc toho tady nemám, ale mùeš si v-v-vzít, co chceš.}
{1206}{}{JÁ CHTÍT TY MRTVEJ.}
{1207}{}{Chtít šecko. Hned.}
{1208}{}{Gdo ty? Ty PÍTEL od }
{1209}{}{Ahooooj.}
{1215}{myn204}{Jasnì! To si piš! Eh, tady máš. To je všechno. A teï, eh, bì zpátky do svı klece, ano?}
{1216}{}{Ne-e. Zabít.}
{1217}{}{Gdó tı? Tı PÍTEL od }
{1225}{myn205}{Pøesnì tak kurva! Hehe, to si piš! My dva budeme nejlepší kamarádi, jasnı?}
{1226}{}{Lhát? }
{1227}{}{Pítel dát šecko }
{1235}{myn207}{Samozøejmì, e jsi. Posaï se na postel. Mùu ti pøinıst nìco k pití nebo tøeba trochu... Jetu?}
{1236}{}{Posadit. Blití.}
{1237}{}{Tı pítel?}
{1245}{myn208}{Vıbornì... tady máš. Tenhle malı drink ti pomùe uvolnit se, jestli mi rozumíš.}
{1246}{}{Pytí.}
{1247}{}{Ty }
{1255}{myn209}{Eh, hej, hej, hej! Poèkej chvilku! Zùstaò... nechceš nìco k pití? Mùeme si popovídat, spøátelit se... CHCEŠ, abysme byli pøátelé, ne?}
{1265}{myn210}{Jsem si jistej, e budeme pøátelé.}
{1266}{}{Chtít pøítel.}
{1267}{}{Pítel. Dát šecko. Hned.}
{1275}{myn211}{Tak a teï pìknì odpoèívej...}
{1276}{}{Dóbroooooo zzzz Zznnzznn Zzznnnzzzz.}
{1285}{myn212}{Hmmmm. Máš vıdr jako brahmína. Vypadni, krásko.}
{1295}{myn213}{Hmm, ty stráe stojej za starou baèkoru... no nic, mùj retardovanej pøíteli, u jsme se pøedstavili, take co kdybys ODSUD SAKRA VYPADNUL?}
{1296}{}{AÙ UŠI. ZABÍT.}
{1297}{}{Ne pítel?}
{1305}{myn214a}{Jo, to si piš, kámo. }
{1306}{myn214b}{Jo, to si piš, zlato. }
{1307}{myn214c}{Ty a já - navdy pøátelé. Nebo do další injekce. A TEÏ SAKRA VYPADNI!}
{1308}{}{NE PÍTEL. ZABÍT.}
{1309}{}{Pítel dát šecko. Hned.}
{1325}{myn215a}{ZATRACENÌ! Øíkal jsem Jeíšovi, e ti dva kreténi neuhlídaj ani kus šutru! Je, eh, po nich, co? A mì zabiješ taky?}
{1326}{myn215b}{Páni! Sexy a ještì nebezpeèná! Take jsi je sejmula, jo? A mì zabiješ taky?}
{1327}{}{Pøemıšlím o tom. Máš nìco, co by mì mohlo pøesvìdèit o tom, e to nemám udìlat... chlapèe?}
{1328}{}{Ne, pokud nebudeš dìlat problémy. Kdo jsi?}
{1329}{}{Ne, pokud nebudeš dìlat problémy. Ty jsi Myron?}
{1330}{}{Jo, proè ne? U dlouho tady nikdo nezemøel. }
{1331}{}{Teï ne. Moná pozdìji. }
{1345}{myn216a}{Jasnì, kámo. }
{1346}{myn216b}{Jasnì, holka. }
{1347}{myn216c}{To si piš, krásko. }
{1348}{myn216d}{J-já... mùu ti dát nìjakı drogy. Chceš se proletìt?}
{1349}{}{No, vlastnì chci všechno, co máš. Dej mi to a nechám tì ít.}
{1350}{}{Jasnì. Dej mi všechny drogy, co máš.}
{1351}{}{Teï nic nechci. Moná pozdìji.}
{1365}{myn217}{Dobøe, dobøe. Tady to máš. Necháš mì u teï na pokoji?}
{1366}{}{Ne. Kdo jsi?}
{1367}{}{Ne. Ty jsi Myron?}
{1368}{}{Jasnì. Prozatím... ale moná se ještì vrátím.}
{1375}{myn218a}{M-moná. K-kdo sakra jsi?}
{1376}{myn218b}{Poslyš, ty jseš nìjaká nová Mordinova kurva, nebo jenom velká fanynka Myrona? Jo a mùu vìdìt, jak se jmenuje majitelka tìch krásnejch noek?}
{1377}{myn218c}{Kdo sakra jsi?}
{1378}{myn218d}{Jsem nìkdo, kdo hledá nìkoho, jako jsi ty, krásko. A ty jsi...?}
{1379}{}{.}
{1380}{}{Jsem jen poutník procházející kolem.}
{1381}{}{Jsem nìkdo, kdo je ve špatné místnosti. Zatím.}
{1395}{myn219a}{Opravdu? A proè jsi tady? No? Myslíš si, e z Myrona dostaneš nìjakı drogy zadarmo, co?}
{1396}{myn219b}{To je jedno, krásko. Nechceš nìjakı drogy, a prolomíme ledy, nebo si rovnou zaskotaèíme v posteli?}
{1397}{}{Moná, ale nemám teï deset sekund nazbyt. O jakıch drogách to mluvíš?}
{1398}{}{Drogy? Jaké tøeba?}
{1399}{}{Jsem urèitì ve špatné místnosti. Promiò.}
{1405}{myn220a}{Jseš snad blbej? Jet, ty mamrde, Jet! Mluvíš s jeho tvùrcem. Jeho stvoøitelem. Jeho... bohem.}
{1406}{myn220b}{Jseš snad blbá? Jet, ty krávo, Jet! Mluvíš s jeho tvùrcem. Jeho stvoøitelem. Jeho... bohem.}
{1407}{myn220c}{Slyšela jsi nìkdy o Jetu, krásko? Mluvíš s jeho tvùrcem. Jeho stvoøitelem. Jeho... bohem.}
{1408}{}{Hovno. Ty jsi nevytvoøil Jet.}
{1409}{}{Ty jsi vytvoøil Jet?}
{1410}{}{Ty jsi vytvoøil Jet? Hustı! Dá se na nìm hroznì moc VYDÌLAT!}
{1411}{}{No a co má bejt? U musím jít.}
{1412}{}{To na tebe musí bıt maminka opravdu pyšná. Zatím, chlapèe.}
{1413}{}{Opravdu? Zajímavé, ale musím teï odejít.}
{1425}{myn221a}{Opravdu jsem vytvoøil Jet! Myslíš, e tahle laboratoø je jen pro srandu králíkùm?}
{1426}{myn221b}{Je mi líto, e tì musím pøesvìdèit o opaku, krásko, ale rozhlídni se kolem sebe. Tahle laboratoø není jen pro srandu králíkùm.}
{1427}{}{No dobøe, MONÁ jsi opravdu vytvoøil Jet.}
{1428}{}{Proè jsi vytvoøil Jet?}
{1430}{}{To na tebe musí bıt maminka opravdu pyšná. Odcházím.}
{1445}{myn222}{To si sakra piš, e jo! Vytváøím fet, po kterım všichni šílí a poøád ho nemají dost.}
{1455}{myn223}{"Proè?" Paè jsem mohl. Rodina Mordinù potøebovala nìjakej produkt a tak Myron vytvoøil produkt a za to ho èiní šastnım... v rámci moností. Hezkej milostnej kruh, co?}
{1456}{}{Jak jsi vytvoøil Jet?}
{1457}{}{'V rámci moností?' Ty jsi tady šastnı?}
{1458}{}{A co kdy ti navrhnu novı kruh? Mordinové nedokáou poznat talent, i kdyby je mlátili do hlavy kladivem, ale já ano.}
{1459}{}{Jo, jasnì. Musím odejít.}
{1465}{myn224a}{Pche, to nemáš šanci pochopit. Je to na tebe MOC sloitı.}
{1466}{myn224b}{Netrap si s tím tu svoji hezkou malou hlavièku, krásko, ale mùu ti dát nìco jinıho, nad èím bys ji mohla trochu potrápit.}
{1467}{}{Ty jsi tady šastnı?}
{1468}{}{Jasnì, hádám, e od takového idiota, jako jsem já, se nedá oèekávat pochopení sloitého procesu vıroby halucinogen-amfetaminového hybridu, jako je Jet, e?}
{1469}{}{Jasnì, hádám, e od takové nány, jako jsem já, se nedá oèekávat pochopení sloitého procesu vıroby halucinogen-amfetaminového hybridu, jako je Jet, e?}
{1472}{}{Myslím, e bys byl docela pøekvapenı, kolik toho vím o tom tvém amatérském halucinogen-amfetaminovém hybridu. Dítì jako ty na nìj klidnì mohlo tøeba jen náhodou NARAZIT.}
{1473}{}{No, díky, e sis udìlal èas, Myrone. U musím jít.}
{1485}{myn225}{Docela jo. Dávají mi kurvy, prachy, drogy. Taky mám vlastní laboratoø a volnost pøi tvorbì, kterou potøebuju, abych vytvoøil kouzla, ale... ne, je to dobrı místo.}
{1486}{}{Ale co? Nechovají se k tobì dobøe?}
{1487}{}{To je dobøe, Myrone. U musím jít.}
{1495}{myn226}{No, víš, Mordinové nechovají k Myronovi R-E-S-P-E-K-T, chápeš? Já jim øeknu, co mají udìlat a oni øeknou 'dr hubu, Myrone' nebo 'jdi zpátky do laboratoøe, Myrone.' Bastardi.}
{1496}{}{Moná mùu nìjak pomoct. Nechceš vypadnout z mìsta? Pøidej se ke mnì a moná si pak Mordinové uvìdomí, jakou máš vlastnì cenu.}
{1497}{}{Jsi pøíliš cennı na to, abys tady sedìl, Myrone. Mìl bys odejít.}
{1498}{}{To je opravdu ošklivé, Myrone. U musím jít.}
{1505}{myn227}{Zapomínají na to, e jen díky MNÌ ovládají Reno a za pár mìsícù budou mít v kapse i Redding. Vìtšina Mordinù má víc chlupù na zadku ne mozkovejch bunìk, jestli mi rozumíš.}
{1506}{}{Eh, moná ti mùu nìjak pomoct...}
{1507}{}{Jsi opravdu pøíliš cennı na to, abys tu byl, Myrone... vánì bys mìl odejít.}
{1509}{}{Zaèínám u chápat, proè tì neposlouchají.}
{1510}{}{To si piš, Myrone. U musím jít.}
{1515}{myn228}{A další vìc: Mordinové nedokáou zaboha pochopit, e mì èištìní Jetu nezajímá. Funguje pøesnì tak, jak má. Já chci vytváøet NOVİ drogy, ne pøedìlávat ty starı, chápeš?}
{1516}{}{Moná ti mùu pomoct. Co kdybys vypadnul z tohohle mìsta a cestoval se mnou? Moná si pak Mordinové uvìdomí, jakou máš vlastnì cenu.}
{1517}{}{Máš naprostou pravdu. Jsi pøíliš cennı na to, abys tu byl, Myrone! Mìl bys odejít!}
{1518}{}{Co jsi to øíkal o Reddingu?}
{1525}{myn229a}{Hmm... jejich boskej chlapec utíká z mìsta. Ha. To je probere. Jo. }
{1526}{myn229e}{To se mi líbí.}
{1527}{myn229d}{Líbí se mi tvùj zpùsob myšlení, krásko.}
{1528}{myn229c}{Take, kam máme namíøeno?}
{1529}{myn229b}{Take, kam máme namíøeno, krásko?}
{1530}{}{Pojï za mnou, Myrone.}
{1531}{}{Tak pojï se mnou.}
{1532}{}{Tak poèkat. Neøíkám, e tì hned beru. Co vlastnì umíš, Myrone? Nemùu s sebou brát kadého. Mám urèitì poadavky.}
{1533}{}{Nejdøív mi øekni, v èem jsi dobrı, Myrone.}
{1534}{}{Zatím nikam. Mám ještì nìjaké otázky...}
{1535}{}{Zatím nikam, Myrone, ale za chvíli se pro tebe vrátím.}
{1545}{myn230a}{Asi né, vypadá to, e je vás moc. Co kdybys vyrazil toho divocha? Zdá se, e ty kosti bere moc vánì.}
{1546}{myn230b}{Asi né, vypadá to, e je vás moc. A Myron se nekamarádí s mutantama. Eh, bez uráky, velkej kámo.}
{1547}{myn230c}{Eh, asi né, vypadá to, e je vás moc. A eh, Myron se nekamarádí s ghoulama. Nikdy nevíš, kdy z nich odpadne kousek tìla pøímo na tvoji botu.}
{1548}{myn230d}{Asi né, nechci se zaplíst s další rodinou. Mordinové mi staèili. Vykopni pár lidí a pak mi øekni.}
{1549}{myn230e}{Jo, jasnì. Ani mouchy by za tebou nelítaly, kdybys byl obalenej hovnama. Pche, zapomeò na to.}
{1550}{}{Tak dobøe. No, mám ještì nìjaké otázky...}
{1551}{}{Máš opravdu vybrané chování. Popøemıšlím o tom, Myrone.}
{1552}{}{Ne, má minimálnì dvakrát takovou cenu jak ty. Zatím, chlapèe.}
{1553}{}{Chlapèe, na to jak vypadáš, ti to fakt kecá. Pøiprav se na smrt.}
{1554}{}{Ale lítaly! To mi vìø.}
{1555}{}{Tvoje chyba, Myrone. Zatím.}
{1565}{myn231}{Jo? Poslouchám...}
{1566}{}{Moná bychom si mohli navzájem pomoct. Hodil by se mi nìkdo s tvımi dovednostmi. Co kdyby ses vykašlal na tohle mìsto a cestoval chvíli se mnou? Moná si pak Mordinové uvìdomí, jakou máš vlastnì cenu.}
{1567}{}{Ále, zapomeò na to. Mám ještì nìjaké otázky...}
{1568}{}{Zapomeò na to. Stejnì by to mezi námi nefungovalo.}
{1575}{myn232a}{Tak dobøe. }
{1576}{myn232b}{Tak dobøe, krásko. }
{1577}{myn232c}{No proè ne? Prásknem do bot.}
{1578}{}{Mizíme odsud.}
{1579}{}{Do Arroya je to 106 mil, máme plnı fùzní èlánek, pùl tuctu RadAway, je pùlnoc a já mám na sobì 50 let starou kombinézu Vaultu 13. Tak pojïme.}
{1585}{myn233}{Á! Co, chceš snad Myronùv ivotopis? Jsem vìdátor. Všechno vím, všechno znám. Nemluvì o tom, e ti dokáu udìlat jakoukoliv drogu, která tì napadne. Pokud mám ty správnı suroviny.}
{1586}{}{Tak dobøe, prošel jsi u pohovoru. Ta èást o drogách ti pomohla. Pojï se mnou.}
{1587}{}{Popøemıšlím o tom. Mám ještì nìjaké otázky...}
{1588}{}{Hmm, popøemıšlím o tom... ale, víš, bez uráky, vìdátoøi jsou nechvalnì proslulí svojí neschopností v boji.}
{1589}{}{Musím si to rozmyslet. Ještì se vrátím.}
{1595}{myn119}{Redding? To je mìsto plnı zlatokopù. Mordino ho chce mít celı pod palcem, take jednoho dne pøišel za mnou a zaèal sípat tím svım hlasem: 'Myrone, Myrone, vytvoø mi nìco, èím si podmaním Redding.'}
{1596}{}{A ty jsi øekl...}
{1597}{}{Hmmm. Chci se ještì zeptat...}
{1605}{myn120}{A já øekl, 'Fajn, kdy to má bejt hotovı?' A on samozøejmì øekl: 'Vèera bylo pozdì.' Mafiáni. Chtìjí mít všechno rychle hotovı a nedodìlanı. Aspoò, e nemají marketingovı oddìlení.}
{1615}{myn236a}{Jo. Proè? Chceš mi snad dokázat, e se pletu, kámo? }
{1616}{myn236b}{Jo. Proè? Chceš mi snad dokázat, e se pletu, dámo? }
{1617}{myn236c}{Jo? Hele, krásko, nemusíš se bránit. Nenarodila ses kvùli svı inteligenci, víš? }
{1618}{myn236d}{Zapomnìl jsem toho o farmaceutickım vızkumu víc, ne budeš kdy vìdìt.}
{1619}{}{Je na Jet nìjakı lék?}
{1620}{}{Fajn, tak jak jsi vytvoøil Jet?}
{1621}{}{Nejdøív mi odpovìz na tuhle otázku: Jak jsi vytvoøil halucinogen-amfetaminovı hybrid? Zdá se, e má Jet nìjaké... unikátní vlastnosti.}
{1623}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{1624}{}{Zapomeò na to. Mizím odsud.}
{1625}{}{Polib mi prdel, ty arogantní sráèi. Mizím odsud.}
{1635}{myn237}{Amatérskı? Ama-amatérskı?! Jet je práce génia, na to nezapomínej! A já na nìj jen tak nenarazil, já ho VYTVOØIL.}
{1636}{}{Nevìøím ti. Øekni mi, jak se vyrábí.}
{1637}{}{To je jedno, chlapèe. Mizím odsud.}
{1645}{myn238}{Dvì slova: brahmíní hovna.}
{1646}{}{To je to, v èem necháváš vyrùstat ten halucinogen?}
{1647}{}{Pouíváš brahmíní hovna jako hnojivo pro rùst Jetu, e jo?}
{1648}{}{Nechceš mi to øíct? Fajn. Tak mi odpovìz na jiné otázky...}
{1649}{}{Tak dobøe. Je mi jasné, kam tohle vede. Kašli na to.}
{1655}{myn239a}{Vıbornì a to je taky to jedinı, co se o tom kdy dozvíš, kámo. A jestli chceš vìdìt víc, tak si na to pøijï sám.}
{1656}{myn239b}{Vıbornì a to je taky to jedinı, co se o tom kdy dozvíš, dámo. A jestli chceš vìdìt víc, tak si na to pøijï sama.}
{1657}{myn239c}{Vıbornì, krásko, a to je taky to jedinı, co se o tom kdy dozvíš, take si s tím u netrap tu svoji roztomilou hlavièku. Ale dost øeèí, co kdybysme si ty a já... eh, hehe...}
{1658}{}{Take brahmíní hovna mají nìjaké zvláštní chemické vlastnosti, které stimulují lidskı nervovı systém?}
{1659}{}{To moná udìlám. Mám ještì nìjaké otázky...}
{1660}{}{...ještì chvíli povídali? Vıbornì! Mám ještì nìjaké otázky...}
{1661}{}{Fajn. Musím jít.}
{1662}{}{Eh, co kdybysme si popovídali pozdìji? Dobrı nápad. Zatím.}
{1675}{myn240}{Máš fakt spoustu blbejch otázek. Odpovìï zní: Jo, moná... hele, o-odkud vlastnì tohle všechno víš? Jseš snad z Vault City nebo co?}
{1676}{}{Odpovìï na tvou otázku zní: Jo... MONÁ. A odkud to víš TY?}
{1677}{}{Ne tak docela. Obèas prostì nìkde nìco pochytím. Je to docela jednoduché.}
{1678}{}{No. Look, I had some other questions...}
{1679}{}{Vault City. Kde to je?}
{1680}{}{Nechám tì hádat. U jsi mi stejnì øekl všechno, co potøebuju vìdìt.}
{1685}{myn241a}{Jo, jen buï drzej, chytráku. Cejtím z tebe ty implantáty a tady. Já jsem pøírodní. Sám jsem se vypracoval. Nemám v sobì ádnı ty 'èistı' sraèky z Vault City, chápeš?}
{1686}{myn241b}{Hehe, cha, ha! Jseš chytrá, krásko... èernı vlasy, zuby, drápy... mmm-mmm. Take ses ty hovadiny nauèila ve Vault City nebo co?}
{1687}{}{Nemám to z Vault City. Obèas prostì nìkde nìco pochytím. Je to docela jednoduché.}
{1689}{}{Chci se ještì zeptat...}
{1695}{myn244}{Co chceš vìdìt?}
{1696}{}{Povìz mi nìco o tomhle místì.}
{1697}{}{Povìz mi o rodinì Mordinù.}
{1699}{}{U pùjdu.}
{1705}{myn245a}{Stáje? Testujeme tady novı druhy Jetu. Co chceš ještì vìdìt?}
{1706}{myn245b}{Stáje? No, testujeme tady novı druhy Jetu. Co chceš ještì vìdìt, krásko?}
{1715}{myn246}{Jsou to moji patronové. Jsou docela v pohodì... aspoò myslím.}
{1716}{}{Aspoò myslíš? Nechovají se k tobì snad dobøe?}
{1725}{myn247}{Zase ty? Take... mùeme jít?}
{1726}{}{Jasnì, Myrone. Vypadneme odsud.}
{1727}{}{Tak poèkat. Neøíkám, e tì hned beru. Co vlastnì umíš, Myrone? Nemùu s sebou brát kadého. Mám urèitì poadavky.}
{1728}{}{Nejdøív mi øekni, v èem jsi dobrı, Myrone.}
{1729}{}{Ne, ne tak docela. Mám nìjaké otázky...}
{1730}{}{Teï ne. Co kdyby sis na chvíli odpoèinul?}
{1735}{}{Jseš trochu podivná... a to se mi líbí.}
{1736}{}{Jseš trochu podivná... a to se mi líbí.}
{1745}{myrn104a}{Nestarej se o mì.}
{1746}{myn104b}{Jauuu! To bolí! To bo- ach, lí. Ne. Ne, jsem celkem v poøádku. Jenom to trochu štípe.}
{1747}{myn104c}{Umírám tady! D-dej mi Stimpak! Nebo dva. Nebo tøi.}
{1748}{myn104d}{To... jseš... ty? Nevidím... ztrácím... vìdomí. *Ugh* *Ech* Pomoz... mi...}
{1749}{}{Hmmmm. Zkus se znovu vyléèit.}
{1753}{}{Dej mi na chvíli pokoj, Myrone.}
{1756}{}{Zapomeò na to. Pojïme.}
{1757}{}{Buï chlap a vydr to, Myrone. Máme to ještì daleko.}
{1765}{myn138}{Eh, promiò, ale mám tady na tebe poèkat? Dìláš si srandu? Øekni mi, e si dìláš srandu.}
{1766}{}{Zùstaò. Tady. Dokud. Se. Nevrátím. Rozumíš?}
{1767}{}{Já se vrátím. Buï v klidu.}
{1775}{myn1003a}{Ale no ták... fajn, jak myslíš. I kdy jsem si chtìl vyzkoušet tu novou techniku støelby dávkou, na kterı pracuju.}
{1776}{myn1003b}{Eh, tuhle zbraò? Aha... promiò, krásko. Ona se mi vdycky tak nìjak... zjeví v rukách, víš?}
{1781}{}{Moná bys mìl trochu odstoupit, Myrone.}
{1784}{}{Ne, dokud jsi se mnou, tak ne. A teï pojï.}
{1785}{}{Prı taky nìkdy pøedèasnì 'vystøelíš'. A teï pojï.}
{1795}{myn1004a}{Eh... tak dobøe. Doufám, e mì netrefíš.}
{1796}{myn1004b}{Cokoliv øekneš, krasotinko. Vrrrr.}
{1802}{}{Radìji se dr opodál, Myrone. Bude to tak pro oba lepší.}
{1804}{}{A tì trefím, tak to poznáš. A teï pojï.}
{1805}{}{Uklidni se, Myrone. Pojïme.}
{1815}{myn1005a}{No... tak dobøe. Ale slyšel jsem, e ten uprostøed to koupí vdycky jako první.}
{1816}{myn1005b}{Tak dobøe, budu ti pozornì hlídat prdelku... er... eh, záda.}
{1820}{}{Vlastnì, zapomeò na to. Dr se u mì.}
{1822}{}{Bì ještì o trochu dál, Myrone. Bude to tak pro oba lepší.}
{1824}{}{S tím poèítám. A teï pojï.}
{1825}{}{Skvìlıııı. Pojïme.}
{1835}{myn1006a}{Dobøe, pohlídám to tam vzadu. Aspoò mám dost prostoru na to, abych si vyzkoušel svoji techniku støelby dávkou.}
{1836}{myn1006b}{Co... smrdím, nebo co?! Ach jo.}
{1841}{}{Pojï blí, Myrone.}
{1844}{}{To je jedno. A teï pojï.}
{1845}{}{Kdyby to byl jen tvùj tìlesnı pach, dalo by se to vydret. Pojïme.}
{1860}{myn232a}{Tak dobøe.}
{1863}{}{Chlapèe, na to jak vypadáš, ti to fakt kecá. Pøiprav se na smrt.}
{1866}{}{Pojïme.}
{1870}{}{Já bıt òák blbì.}
{1875}{}{Podaøilo se ti pøesvìdèit Myrona, e by mohl existovat lék na Jet.}
{1880}{}{To je hrob, ve kterém Velkej Jeíš schoval peníze.}
{1885}{}{Podaøilo se ti pøesvìdèit Myrona, aby odešel ze Stájí.}
{1957}{}{Dobøe, dobøe! Pøestaò do mì strkat!}
{1958}{}{Hej, dej mi pokoj! Já svoji AI neprogramoval.}
{1959}{}{Dobøe, TAK PROMIÒ.}
{1960}{}{Tak dobøe, ale pøíštì uhneš TY MNÌ.}
{1961}{}{Já tu byl první. Ale a je po TVİM.}
{2001}{myn321}{To je na hovno.}
{2004}{myn324}{O èem to sakra mluvíš?}
{2023}{myn343}{To radši vylíu Marcusovi prdel.}
{2024}{myn344}{To radši olíu Lennymu koule.}
{2025}{myn345}{To radši nechám toho kyberpsa, a mi ukousne koule.}
{2033}{myn353}{Co já vím.}
{2091}{}{Nemáš pár drobnejch? Musím zbavit pár holek panenství.}
{2675}{myn242a}{Jednoduchı, jo? Já jsem nejlepší. Dvakrát lepší ne ti ocasové ve Vault City.}
{2676}{myn242b}{No jo, to máš pravdu. Jednodušší ne ty blbosti, co by ti tloukli do hlavy ti ocasové ve Vault City.}
{2678}{}{Nech to bıt, pane Nejistı. Mám ještì nìjaké otázky...}
{2679}{}{Máš opravdu vytøíbenı jazyk. Uvidíme se pozdìji, Myrone.}
{2685}{myn243}{To je mìsto na severovıchodì. Banda "geneticky èistejch" lidí. Kdyby namyšlenost nadnášela, utopí se pøi prvním dešti.}
{2686}{}{Nemám to z Vault City. Obèas prostì nìkde nìco pochytím. Je to docela jednoduché.}
{2687}{}{Zajímavé. Mám ještì nìjaké otázky...}
{2688}{}{Máš opravdu vytøíbenı jazyk. Uvidíme se pozdìji, Myrone.}
{3000}{}{Myrone, myslím, e bychom si mìli promluvit o... vzdálenosti mezi námi.}
{3001}{}{Promluvme si na chvíli o tvém vybavení.}
{3002}{}{Zapomeò na to. Zùstaò kde jsi.}
{3003}{}{Potøebuju, aby sis sundal zbroj.}
{3004}{}{S jakımi zbranìmi umíš zacházet, Myrone?}
{3005}{}{Nech to bıt, potøebuju od tebe nìco jiného.}
{3025}{}{Nevadí.}
{4000}{}{Jo, tady by mìlo bıt to zaøízení, kterı jsem ti vyznaèil do mapy. Nejspíš bude hluboko pod zemí.}
{5000}{}{Kurva! Kurva! Necítím jednu konèetinu!}
{5001}{}{Cítím se, jako bych se kurva rozpouštìl!}
{5002}{}{Bleju tu svı zasranı vnitønosti!}
{5616}{}{Jasnì. Vyzkoušej mì.}
{5617}{}{Myslím, e ti mùu pár vìcí ukázat.}
{5725}{}{Fajn, fajn. A v èem je problém s vırobou barbiturátù?}
{5741}{}{Jak to?}
{5851}{}{Ano...?}
{5861}{}{U chápu.}
{6208}{}{?}
{6218}{}{ jít.}
{6226}{}{ ZABÍT.}
{6247}{}{ pítel?}
{6256}{}{ pít.}
{6257}{}{ pítel?}
{6287}{}{ jít.}
{6298}{}{ jít, }
{6379}{}{Jsem }
{6525}{}{Urèitì. Bıt tebou, tak to udìlám, aby si uvìdomili, o co pøichází.}
