{100}{}{Vidíš hubeného vysokého muže s tlustými brýlemi.}
{101}{}{Vidíš Jimmyho.}
{102}{}{Vidíš hubeného vysokého muže s tlustými brýlemi. Jeho obočí je svraštělé a za neustálého žbrblání chodí po místnosti.}
{103}{}{Nazdárek. Jsem Jim nebo Jimmy, chceš-li. Potřebuješ něco?}
{104}{}{Já dívat kolem.}
{105}{}{Já}
{106}{}{Eh... já dívat kolem. Já teď jít.}
{107}{}{Jenom se rozhlížím.}
{108}{}{Ahoj, Jime. Jsem}
{109}{}{Do toho ti nic není, brejloune. Odpal.}
{110}{}{Jen se tak rozhlížím. Už půjdu.}
{111}{}{Klidně se dívej, ale hlavně se prosím ničeho nedotýkej. Máme tu spoustu citlivých zařízení.}
{112}{}{Já jen dívat kolem. Já nedotýkat.}
{113}{}{Jen se tak dívám. Ničeho se dotýkat nebudu.}
{114}{}{Jsi otravný. Jdi pryč.}
{115}{}{Promiň. Nechtěl jsem tě prudit. Nechám tě zase pracovat.}
{116}{}{Dobře.}
{117}{}{Rád tě potkávám,}
{118}{}{Co potřebujete vědět?}
{119}{}{Co ty tady dělat?}
{120}{}{Co dělat tyhle stroje?}
{121}{}{Vault mít správce. Tohle místnost správce?}
{122}{}{Ty ve vault protože chtít tady?}
{123}{}{Co ty myslet o párači?}
{124}{}{Počítač potřebovat součástku. Ty vědět kde sehnat?}
{125}{}{Já vědět dost. Já teď jít.}
{126}{}{Co tady děláš?}
{127}{}{K čemu jsou všechny tyhle stroje?}
{128}{}{Není tohle náhodou místnost správce vaultu?}
{129}{}{Jsi tu, protože tu chceš být?}
{130}{}{Co si myslíš o páračích?}
{131}{}{Počítač potřebuje nějakou součástku. Nevíš, kde by se dala sehnat?}
{132}{}{Myslím, že už půjdu.}
{133}{}{No... máme nějaký problém s počítačem a já se na to pokouším přijít. Bohužel moje specializace je software, ne hardware.}
{134}{}{Jaký problém?}
{135}{}{Co je to za problém?}
{136}{}{Ano, Gruthar se o tom zmínil a požádal mě, ať se na to podívám. Můžu?}
{137}{}{Přestalo fungovat hlasové rozhraní počítače, takže Gruthar nemůže udílet příkazy k řízení vaultu. Vodní a potravinové procesory se už vypnuly a energetický systém bude pravděpodobně brzy následovat.}
{138}{}{Proč vy nepoužít klávesnice?}
{139}{}{Proč prostě nepoužijete klávesnici?}
{140}{}{No, víš, to je na tom to zvláštní. Systém odmítá příkazy z klávesnice. Nemám nejmenší tušení, jak dál pokračovat.}
{141}{}{Nevadit já podívat?}
{142}{}{Nebude ti vadit, když se na to podívám?}
{143}{}{Ano, Gruthar se o tom zmínil a požádal mě, ať se na to podívám. Můžu?}
{144}{}{No... bez urážky, ale jsi si jistý, že tomu rozumíš? No, to je stejně jedno. Pochybuji, že to ještě víc pokazíš. Tak prosím.}
{145}{}{No, víc už to asi pokazit nemůžeš, takže si klidně posluž.}
{146}{}{Dobře, ale já nejdřív ptát pár otázek.}
{147}{}{Tak dobře, ale nejdřív se chci na něco zeptat.}
{148}{}{Tohle je hlavní počítačový systém a jeho přídavná zařízení. Odtud se vzdáleně ovládají všechny funkce vaultu.}
{149}{}{Eh... co ty říkat?}
{150}{}{Aha, chápu.}
{151}{}{Obvykle by tu měl sídlit správce vaultu, avšak Vault 13 byl plně zautomatizován.}
{152}{}{Jak to?}
{153}{}{Dobře, já ptát víc.}
{154}{}{Proč? Chci říct, není to neobvyklé?}
{155}{}{Aha. Změňme téma.}
{156}{}{Neznám celý příběh, ale kdysi proběhlo ve vaultu povstání. Správce byl buď zabit nebo sesazen, nejsem si jistý. Tak jako tak, vůdcové povstání nechtěli svěřit osud lidí do rukou dalšího správce, proto nainstalovali tento počítač. Záznamy říkají, že byl zakoupený z... sakra, jak to jen bylo... jo, z 'Bratrstva oceli.'}
{157}{}{Ty říct o Bratrstvo?}
{158}{}{Mohl bys mi o tom Bratrstvu něco říct?}
{159}{}{Ne, je mi líto, nevím o nich nic. Tohle všechno se stalo už dávno a nikdy jsem o nich nenašel další záznamy kromě tohohle. Co vím, tak Bratrstvo byla vojenská jednotka. Na západě jsou nějaké ruiny, které vypadají jako bývalá vojenská základna. To je možná to jediné, co po nich zbylo.}
{160}{}{Aha. Já ptát dál.}
{161}{}{Dobře. Chci se ještě na něco zeptat.}
{162}{}{Ale jo. Líbilo se mi tu už od prvního okamžiku, co jsem tady, a asi už nikdy neodejdu. Vždycky jsem byl samotář a o lidi jsem se moc nezajímal, bez urážky.}
{163}{}{Já neurazit.}
{164}{}{Neuráží mě to.}
{165}{}{No... svým způsobem se mi na nich líbí, co jsou a čím se snaží být. A svým způsobem se jich bojím víc než čerta. Myslím, že si asi nikdy nezvyknu na to, že jsou chytří jako já... tedy, někteří z nich.}
{166}{}{Ty myslet oni hrozba pro lidi?}
{167}{}{Myslíš, že jsou pro lidi hrozbou?}
{168}{}{To rozhodně. Fyzicky nás převyšují a mentálně jsou na tom zhruba nastejno. To z nich dělá opravdu velkou hrozbu. Ovšem všechno nakonec stojí a padá na morálce a etiketě. A oni jsou naštěstí morálně i eticky na výši.}
{169}{}{Já chápat.}
{170}{}{Aha. Chápu, co tím myslíš.}
{171}{}{Ahoj. Rád tě zase vidím. S čím ti můžu pomoct?}
{172}{}{Potřebovat zeptat otázka.}
{173}{}{Jen tebe zdravit. Já jít.}
{174}{}{Chci se tě na něco zeptat.}
{175}{}{Jenom jsem tě chtěl pozdravit.}
{176}{}{No, hmm... myslím, že bude nejlepší, když začneš hledat ve Vault City, jelikož je to nejmodernější město, které znám. Zkusil bych to i v New Renu. Jsou blíž a často obchodují s Vault City.}
{177}{}{Díky.}
{178}{}{Děkuji ti, že jsi opravil ten počítač. Zachránil jsi nám zadky.}
{179}{}{Mám jiné věci na práci než zabíjet ubožáky, ale každý občas potřebuje dovolenou!}
{180}{}{. Já mít otázky.}
{181}{}{. Můžu se tě na něco zeptat?}
{182}{}{. Rád ti odpovím na tvoje otázky.}
{183}{}{Řekni Grutharovi, že je ten počítač opravený.}
