{100}{}{Vidíš malou holčičku ve žlutých šatičkách.}
{101}{}{Vidíš Sandy.}
{102}{}{Vidíš malou holčičku ve žlutých šatičkách s kytičkami. Zdá se, že mňouká jako kočka. Má jmenovku se jménem "Sandy".}
{103}{}{Mňau... mňau... já jsem kočka. A mám speciální schopnosti jako kočky. Co jsi ty?}
{104}{}{Já pejsek! Haf! Haf! Kdo ty?}
{105}{}{He? (Zmatený psí pohled)}
{106}{}{Ty divný. Já pryč.}
{107}{}{Já jsem člověk, který ti nakope prdel, jestli nepřestaneš s těma kočičíma blbostma a neřekneš mi svoje jméno.}
{108}{}{Jsem jen obyčejný člověk, kterého zajímá tvoje speciální osobnost. Řekneš mi svoje jméno?}
{109}{}{Zapomeň na to.}
{110}{}{(Směje se) Vypadáš srandovně! Mňau... jsem Sandy. Nejsem opravdová kočka, jen si na ni ráda hraju.}
{111}{}{(Křičí) Mami! Mami! Mami!}
{112}{}{Jsem Sandy. Nejsem opravdová kočka, jenom si ráda hraju.}
{113}{}{Já taky hrát. Já ptát ty otázky?}
{114}{}{Já teď jít.}
{115}{}{Aha. Můžu se na něco zeptat?}
{116}{}{Dobře, mizím.}
{117}{}{Na co se mě chceš zeptat?}
{118}{}{Ty být tady protože muset?}
{119}{}{Ty líbit tady?}
{120}{}{Ty být v bezpečí?}
{121}{}{To nic. Já odejít.}
{122}{}{Ty tady musíš být?}
{123}{}{Líbí se ti tady?}
{124}{}{Jsi tady v bezpečí?}
{125}{}{Ale nic. Nashle.}
{126}{}{Jo. Maminka mi vždycky říká kam můžu a kam ne. Říká mi, kde si můžu hrát, kdy mám jíst, kdy mám jít spát, kdy mám čůrat a kdy mám jít do školy, no prostě všechno. Myslím, že to není fér, když si ona může dělat co chce, ale já ji musím pořád poslouchat.}
{127}{}{Dobře.}
{128}{}{Já muset jít.}
{129}{}{Aha.}
{130}{}{Tak to by mi prozatím stačilo. Ahoj.}
{131}{}{Asi jo. Chybí mi tu další děti, se kterejma bych si mohla hrát, ale maminka říká, že se to jednou změní. Myslí si, že sem přijdou žít další rodiny s dětmi. Zatím si hraju s Valdisem. Je s ním sranda a hraje si se mnou na koníčka. Maminka říká, abych ho nechala být. Má moc práce a nemá čas si hrát, ale když mu řeknu, tak si se mnou stejně hraje. Jenom o tom mamince neříkám.}
{132}{}{Na koníčka... (Zmatený psí pohled)}
{133}{}{Já jít.}
{134}{}{To je milé.}
{135}{}{Dobře, zatím.}
{136}{}{Jo. Maminka se o mě stará a Valdis nedovolí, aby mi někdo ublížil. Jsem v bezpečí.}
{137}{}{Dobře. Já teď jít.}
{138}{}{Dobře. Už musím jít.}
{139}{}{Ahoj.}
{140}{}{Běž pryč! Nemám tě ráda!}
