{100}{}{Vidíš vychrtle vypadajícího mue v modré kombinéze.}
{101}{}{Vidíš Martina Frobishera. Je mluvèí vìzòù ve Vaultu 13.}
{102}{}{Vidíš vychrtle vypadajícího mue v modré kombinéze vaultu. Je stejná jako ta tvoje.}
{103}{}{Dostaò nás odsud!}
{104}{}{Vypni silové pole.}
{105}{}{Vypni silové pole, a mùeme utéct!}
{106}{}{Dostaò nás ODSUD!}
{107}{}{Elektøina je vypnutá! Dveøe jsou otevøené!}
{108}{}{Jsme v hajzlu.}
{109}{}{Dostaò nás odsud, ne zaènou dìlat další testy.}
{110}{}{Kdo jsou ti lidé?}
{111}{}{Proè já? Proè my?}
{112}{}{Musíme se dostat z tohohle místa.}
{113}{}{Hej ty, tady jsme!}
{114}{}{Hledáš mì?}
{115}{}{Chceš vìdìt, co se stalo?}
{116}{}{Pomoc!}
{117}{}{Já jsem Martin, tady jsem.}
{118}{}{Hej, ty, já jsem Frobisher. Tady!}
{119}{}{Tady jsééém!}
{120}{}{Ahóóóój!}
{121}{}{Pojï sem!}
{122}{}{Øeknu ti všechno, co budeš chtít.}
{123}{}{Jmenuju se Martin.}
{124}{}{Mùu ti øíct, co se stalo potom.}
{125}{}{Ahoj, já jsem Martin Frobisher. Jsem mluvèí tìchto lidí. Díky bohu, e jsi tady.}
{126}{}{Co potøebujete vìdìt?}
{127}{}{Máte pìkné obleèení, pøesnì jako je to moje. Kdo jste?}
{128}{}{Co tady dìláte?}
{129}{}{Ty jsi správce vaultu?}
{130}{}{Jak jste se sem dostali?}
{131}{}{Tìší mì, e tì poznávám, Martine, ale musím osvobodit pár lidí. Sbohem.}
{132}{}{Ano, doufal jsem, e kvùli tomu jsi tady. Musíš nás osvobodit.}
{133}{}{Osvobodit vás? Chci osvobodit jen svoje lidi.}
{134}{}{Ale jistì, nenechám nikoho na tomhle místì shnít.}
{135}{}{A co tu vlastnì dìláte?}
{136}{}{Testují na nás protilátky proti nìjakému smrtícímu viru.}
{137}{}{Jakému viru?}
{138}{}{To nezní moc dobøe. Chci se ještì na nìco zeptat.}
{139}{}{To máte tedy štìstí. Moná teï koneènì pochopíte jakou bolest mùj pøedek, Zakladatel, cítil. Doufám, e všichni skonèíte v pekle. Sbohem.}
{140}{}{Øíkají tomu F.E.V. toxin. Dìlá s lidmi strašné vìci ne je zabije. Jedinou *vıhodou* toho toxinu je, e zabíjí okamitì. Ale vypadá to velmi bolestivì.}
{141}{}{To zní strašnì. Ale proè pouívají na testy právì tvoje lidi?}
{142}{}{Unesli nás všechny z našeho vaultu, protoe potøebují pokusné osoby na testování protilátek. Potøebovali lidi, kteøí ijí mimo Enklávu a jsou stále nezasaení radiací. A tak si vybrali nás.}
{143}{}{Vybrali si vás? Jak a odkud?}
{144}{}{Jednou pøišli k hlavnímu vchodu našeho vaultu a nìjakım zpùsobem zjistili vstupní bezpeènostní kód, take jen otevøeli dveøe a jejich tìkoodìnci nás naloili do vertibirdù a dopravili a sem. A pak zaèali s experimenty. (Celı se zatøese.)}
{145}{}{To zní hroznì. Chci se ještì na nìco zeptat.}
{146}{}{Vault? Z kterého vaultu jste?}
{147}{}{Z Vaultu 13, samozøejmì.}
{148}{}{Tam jsem šel, abych našel GECK.}
{149}{}{Tam jsem byl poprosit o váš GECK, abych zachránil svoje lidi, ale vy jste u byli pryè. Jenom ten GECK tam zùstal.}
{150}{}{Ten jsem hledal. Poslyš, nejsi ty náhodou správce vaultu?}
{151}{}{GECK? Mìli jsme dva. Rádi ti jeden pøenecháme. Myslím, e jsem vidìl nìkolik vojákù nakládat jeden z našich GECKù do vertibirdu.}
{152}{}{Ty jsi je vidìl nakládat GECK? Nevíš, kam ho dali?}
{153}{}{To nevadí. Podaøilo se mi získat GECK z vašeho vaultu. Chci se ještì na nìco zeptat.}
{154}{}{Nevím kam ho pøesnì dali, ale slyšel jsem je, jak se baví o tom, e ho odnesou do skladištì. Myslím, e je v patøe pod námi.}
{155}{}{To je skvìlé. Díky. Radìji u pùjdu.}
{156}{}{Aha, rozumím. Chci se ještì na nìco zeptat.}
{157}{}{Poèkej! Musíš nás odsud dostat.}
{158}{}{To mám v plánu. Teï pùjdu dolù k reaktoru a a ho vypnu, budete volní. Jakmile budou vypnuta silová pole, utíkejte co nejrychleji nahoru na moji loï.}
{159}{}{Jak to mám udìlat?}
{160}{}{Na to jste mìli myslet døív, *ne* jste vykopli mého pøedka z vaultu. Doufám, e tu všichni shnijete. Sbohem.}
{161}{}{Díky. Hodnì štìstí a bùh tì provázej, pøíteli.}
{162}{}{Sbohem a hodnì štìstí.}
{163}{}{Díky, ale chci se ještì na nìco zeptat.}
{164}{}{Mám takovı pocit, e ho budu potøebovat. Sbohem.}
{165}{}{Myslím, e k vypnutí silovıch polí je potøeba vypnout hlavní zdroj napájení.}
{166}{}{A jak to mám sakra udìlat?}
{167}{}{Zaslechl jsem, e reaktor øídí velkı poèítaè tøi patra pod námi. Pokud ho vyhodíš do vzduchu, mìla by se pøerušit dodávka energie a my budeme volní.}
{168}{}{Skvìlı nápad. Mùu pouít své vıbušniny a vyhodit tak poèítaè do vzduchu. Vy pak utíkejte co nejrychleji nahoru na moji loï. Budu hned za vámi.}
{169}{}{Skvìlı nápad, ale nemám tušení, jak vyhodit reaktor do vzduchu. Nemám ádné vıbušniny.}
{170}{}{Jsem si jistı, e nìkde poblí kasáren bude i skladištì zbraní. Urèitì tam budou mít i vıbušniny.}
{171}{}{Skvìlı nápad. Najdu ty vıbušniny a vyhodím s nimi poèítaè do vzduchu. Vy pak utíkejte co nejrychleji nahoru na moji loï. Budu hned za vámi.}
{172}{}{Ten název ji dlouho nepouíváme. Mìli jsme pøed mnoha lety správce vaultu, ale udìlal velikou chybu a díky ní mnoho našich lidí opustilo vault... jen aby zcela jistì zemøeli v pustinì. Poté stanul pøed soudem a za svùj zloèin byl odsouzen k smrti. Od té doby ten titul u nepouíváme.}
{173}{}{Nevyèítám ti to. Teï u chápu, e to byl správce, kdo vykopl mého pøedka, Zakladatele, ven do pustiny.}
{174}{}{Zakladatele? Kdy se to stalo? Asi tak pøed osmdesáti lety?}
{175}{}{Ano, bylo to pøed osmdesáti lety. Jak to víš?}
{176}{}{Pøed osmdesáti lety náš vault zachránil jeden hrdina a správce ho poté vyhnal. Další lidé ho následovali a u nikdy jsme o nich neslyšeli. Všichni si tu událost pamatujeme s hanbou.}
{177}{}{Hej! Mluvíš o *mém* pøedkovi a o lidech, kteøí pomáhali zaloit moji vesnici. Všichni pocházeli ze svatého Vaultu 13.}
{178}{}{To byste také mìli. Chci se ještì na nìco zeptat.}
{179}{}{Myslím, e jste za to zatím trpìli málo. Sbohem.}
{180}{}{Neuvìøitelné, to je náš vault! Opìt se musí lidé z vaultu spolehnout na... eh, tentokrát... na pravnuka Zakladatele, aby nás zachránil.}
{181}{}{Neuvìøitelné, to je náš vault! Opìt se musí lidé z vaultu spolehnout na... eh, tentokrát... na pravnuèku Zakladatele, aby nás zachránila.}
{182}{}{Bohuel nevím, jak vás mám zachránit.}
{183}{}{Tak to si ještì rozmyslím.}
{184}{}{To je ale náhodièka! Chci se ještì na nìco zeptat.}
