{100}{}{Vidíš statnou ženu v hornickém oděvu.}
{101}{}{Vidíš "Rouhavou" Betty, horníka z dolu Morningstar.}
{102}{}{Vidíš sebevědomě se tvářící svalnatou ženu.}
{103}{}{Caminetto, tví horníci z Kokoweefu jsou k smíchu.}
{104}{}{Já ti ukážu kam máš jít, Rouhavá Betty.}
{105}{}{Ty bys mi to neukázal, ani kdybys měl mapu.}
{106}{}{Ale jen proto, abych se k tobě nemusel přibližovat.}
{107}{}{Moc si lichotíš, ty zakrslíku.}
{108}{}{Ty bys byla šťastná i za toho zakrslíka namísto tý vrtačky, kterou obvykle používáš.}
{109}{}{No, aspoň ta vrtačka vydrží dýl než třicet sekund.}
{110}{}{Není divu, že jsou vrtáky Morningstaru věčně zlámaný.}
{111}{}{Já ti ukážu zlámaný... pěstma!}
{112}{}{Tvýma pěstma? Stačí mi tvůj dech.}
{113}{}{Nechápu, jak to můžeš cítit přes ten oblak vlastního smradu.}
{114}{}{Smradu? Pouhý pohled na tebe mi působí mnohem větší utrpení.}
{115}{}{Ty nevíš o bolesti vůbec nic, ale dám ti o ní pár lekcí.}
{116}{}{Ty mně?}
{117}{}{Jo, přesně tak. Pač tvoje máma na to asi zapomněla.}
{118}{}{Teď začneš mluvit o mojí mámě? To není moc kreativní.}
{119}{}{Kreativní to bude, až ti udělám novej ksicht. Na ten starej se už nedá koukat.}
{120}{}{Ty? A kde na to vezmeš lidi?}
{121}{}{Vystačím si sama. Vsadím se, že my z Morningstaru vás rozneseme levou zadní.}
{122}{}{Pochybuju. Tady vládne Kokoweef. Měl bych tě o tom poučit.}
{123}{}{To se ti bude těžko dělat, když budeš v bezvědomí.}
{124}{}{Myslíš, že budeš mít takový štěstí, jo?}
{125}{}{Na to, abych tě zadupala do podlahy, nepotřebuju štěstí.}
{126}{}{No, tlustá jsi na to dost, to je fakt. Pomoc, už se bojím.}
{127}{}{Tak se ukaž, nebo sklapni, ty skrčku.}
{128}{}{Tak se ukaž, ty krávo.}
{129}{}{A kdo teď doufá, že bude mít štěstí?}
{130}{}{Už toho mám dost, za tohle tě vynesu v zubech.}
{131}{}{Kdo to na nás sakra čumí?}
{132}{}{To je někdo novej. Hej, tohle je soukromá záležitost! Vypadni!}
{133}{}{Pro jednou s tebou musím souhlasit. Vypadni!}
{134}{}{A kdo teď bude těžit zlato, co, chytrolíne?}
{135}{}{Trochu zasranýho volna by mi fakt bodlo.}
{136}{}{To mám bejt v týhle smradlavý díře s tím kreténem?}
{137}{}{Caminetto, tvoje posraný dny jsou sečteny.}
{138}{}{Za to si polib řiť a rozluč se se životem.}
{139}{}{Dostaňte mě kurva odsud!}
{140}{}{Hej, sráči, pust mě ven!}
{141}{}{Hej, šerife! Když mě pustíš, tak ti ho přeblafnu.}
{142}{}{Příště se na to vykašlu.}
{143}{}{Na co sakra čumíš?}
{144}{}{Co chceš, sráči?}
{145}{}{Nedovolím, abyste se navzájem pomlátili.}
{146}{}{Zajímalo by mě, co se tady děje.}
{147}{}{Tahle hospoda je plná svinstva a já a mí hoši z Morningstaru ho hodláme vymést ven na ulici. To největší hovno má dokonce i jméno - Caminetto.}
{148}{}{Proč? Jak to začalo?}
{149}{}{Aha. Jenže já ti to nedovolím. Musíte toho hned nechat.}
{150}{}{Jen se na ty schlíplý ptáky podívej. Kdo by odolal tomu pokušení vytřít s nima podlahu?}
{151}{}{To mi nepřijde jako dobrý důvod. Nedovolím, abyste se pomlátili.}
{152}{}{No, to opravdu vypadá jako problém. Nebudu vás rušit. Hodně štěstí.}
{153}{}{A co s tím jako hodláš udělat, ty mizernej patolízale?}
{154}{}{Prvního, kdo udeří, zabiju.}
{155}{}{No, nejdřív vás mile požádám. Pak vytáhnu bouchačku a budu čekat, kdo mi dá šanci se trochu procvičit ve střelbě.}
{156}{}{Šerif mě požádal o pomoc do doby, než bude mít zdravou nohu. Dal jsem mu svoje slovo, že tu bude klid.}
{157}{}{Jo? No, ten Marion je docela hezkej. Dobře, kvůli němu dám těmhle babám z Kokoweefu pokoj.}
{158}{}{Díky. Doufal jsem, že se na to budeš dívat stejně. Sbohem.}
{159}{}{Co si vlastně o sobě myslíš, ty namachrovanej kovboji? Vůbec se mi nelíbí ten tvůj drzej tón.}
{160}{}{Ani se ti nemusí líbit. Buď se mnou půjdeš do basy dobrovolně, nebo tu zbyde jen tvoje mrtvola. Je to na tobě.}
{161}{}{Promiň. Opravdu jsem nechtěl být tak nezdvořilý. Raději už půjdu. Sbohem.}
{162}{}{Jo? No dobře, něco ti povím. Půjdu, když zabásneš i toho smrada Caminetta.}
{163}{}{Nejsi zrovna v situaci, kdy si můžeš klást podmínky.}
{164}{}{To není špatný nápad. Když mezi vámi budou mříže, tak snad trochu vychladnete. A teď sebou pohněte.}
{165}{}{Máš ty vůbec něco v hlavě? Jestli si něco zkusíš, tak tě na zahřátí pěkně zmlátíme. A pak tu poteče krev. Myslíš, že se to šerifovi bude líbit?}
{166}{}{No, to asi ne.}
{167}{}{To je mi jedno. Nebude to *moje* krev, která tu poteče.}
{168}{}{No, možná bych si mohla trochu odfrknout. Poslední dobou jsem měla spoustu práce. (Na ostatní.) Dejte si pohov, hoši. Uvidíme se zítra v práci.}
{169}{}{To je rozumná volba.}
{170}{}{Neměj obavy, beru Caminetta s sebou a bude ti tam dělat společnost. Je to tak, Caminetto?}
{171}{}{Ty to fakt kurva nechápeš, co? Zkus se do toho míchat a já i ten schlíplej ocas Caminetto s tebou zatočíme.}
{172}{}{No, tak v tom případě budu muset zavřít oba.}
{173}{}{No, tak v tom případě muset odprásknout oba.}
{174}{}{Hmm, myslím, že mě teď zrovna potřebujou někde jinde ve městě. Budu muset jít. Sbohem.}
{175}{}{Jsi chytřejší, než vypadáš. Ale to asi musíš být, když jsi pořád ještě naživu. Teď utíkej zpátky za maminkou a řekni jí, že jsme na tebe byli hrozně moc oškliví.}
{176}{}{Tak dost. Už mám těch tvých keců až po krk. Poslední výzva. Pojď v klidu se mnou, nebo tě roztrhnu jak hada.}
{177}{}{To možná udělám. Nechci nikomu ublížit. Sbohem.}
{178}{}{Já vím, jak to chodí, ty malej sráči. Dobře, půjdu s tebou a Caminetto taky.
(Na Caminetta) Že jo, ty můj ocásku?}
{179}{}{Tak se mi to líbí.}
{180}{}{Ne, už je pozdě. Udělám z vás obou žrádlo pro psy. }
{181}{}{Myslím, že nakopu Caminettovi prdel někdy jindy.}
