{100}{}{Vidíš občana Reddingu.}
{101}{}{Tento muž vypadá, že je místní.}
{102}{}{Vidíš horníka.}
{103}{}{Vidíš farmáře Reddingu.}
{104}{}{Vidíš místního muže.}
{105}{}{Vidíš místní ženu.}
{106}{}{Tato žena vypadá, že je místní.}
{107}{}{Vidíš místní ženu.}
{108}{}{Vidíš ženu, která nejspíš pracuje v dolech.}
{109}{}{Vidíš farmářku.}
{110}{}{Na co čumíš?}
{111}{}{Vítej ve velkým městě.}
{112}{}{Ahoj.}
{113}{}{Zůstaneš v Reddingu dlouho?}
{114}{}{Poprvý v Reddingu, co?}
{115}{}{Nechceme tu žádný potíže.}
{116}{}{Taky se na tebe dívám.}
{117}{}{Nazdar, cizinče.}
{118}{}{Jak je?}
{119}{}{Jak se vede?}
{120}{}{Přeju hezkej den.}
{121}{}{Jo.}
{122}{}{Ahoj.}
{123}{}{Vidíš muže s chlazeným nápojem v ruce.}
{124}{}{Vidíš muže, který si objednává pivo.}
{125}{}{Tento chlápek toho moc vypil.}
{126}{}{Vidíš násosku.}
{127}{}{Tento chlapík vypadá velice šťastně.}
{128}{}{Vidíš ženu s chlazeným nápojem v ruce.}
{129}{}{Vidíš ženu, která si objednává pivo.}
{130}{}{Tato žena toho moc vypila.}
{131}{}{Vidíš násosku.}
{132}{}{Tato žena je opilá.}
{133}{}{Ahoj, cizinče.}
{134}{}{Nazdárek.}
{135}{}{Hmmm.}
{136}{}{Hyk.}
{137}{}{Glo-glo-glo.}
{138}{}{Díky, cizinče.}
{139}{}{To není špatný na divocha.}
{140}{}{To je ono.}
{141}{}{Mmm-hmmm.}
{142}{}{Díky.}
{143}{}{Jsi můj nejlepší přítel.}
{144}{}{Díky, kámo.}
{145}{}{Jsi nejlepší.}
{146}{}{Divoši jsou taky lidi.}
{147}{}{Nic než přátelé.}
{148}{}{Chce se mi zpívat...}
{149}{}{Odvolávám všechno, co jsem o tobě předtím řekl.}
{150}{}{Jsi opravdový kámoš.}
{151}{}{Divoši jsou hodní.}
{152}{}{Hip hip hurá divochům.}
{153}{}{./~ Mám sucho v krku... ./~}
{154}{}{./~ 99 flašek piva na stěně, 99 flašek piva... ./~}
{155}{}{Vidíš muže, který se dívá na svůj domov.}
{156}{}{Vidíš muže, který jí maso.}
{157}{}{Vidíš muže, který si zašívá oblečení.}
{158}{}{Tento muž odpočívá.}
{159}{}{Tento muž odpočívá u sebe doma.}
{160}{}{Vidíš ženu, která se dívá na svůj domov.}
{161}{}{Vidíš ženu, která jí maso.}
{162}{}{Vidíš ženu, která si zašívá oblečení.}
{163}{}{Tato žena odpočívá.}
{164}{}{Tato žena odpočívá u sebe doma.}
{165}{}{Ahoj.}
{166}{}{Co tu děláš?}
{167}{}{Kdo tě sem pustil?}
{168}{}{Vypadni, tohle není dům pro divochy.}
{169}{}{Vypadni! Zmiz!}
{170}{}{Co děláš u mě doma?}
{171}{}{Vidíš horníka Reddingu.}
{172}{}{Vidíš horníka.}
{173}{}{Vidíš unaveného horníka.}
{174}{}{Vidíš kopáče zlata.}
{175}{}{Vidíš špinavou osobu.}
{176}{}{Tato osoba vypadá jako horník.}
{177}{}{./~ Každým dnem starší a zadluženější./~}
{178}{}{Jsem celý špinavý.}
{179}{}{Tam dole je fakt tma.}
{180}{}{Kopat, my musíme.}
{181}{}{Nejdřív kopeme, potom zhebneme.}
{182}{}{Proč není zlato na povrchu?}
{183}{}{Vidíš vzrušenou osobu.}
{184}{}{Tato osoba je velice nervózní.}
{185}{}{Vidíš osobu, která sleduje zápas v ringu.}
{186}{}{Tato osoba si patrně dala povzbuzováka.}
{187}{}{Vidíš někoho, kdo sází na zápasy.}
{188}{}{Tato osoba vypadá vzrušeně.}
{189}{}{Sejmi ho!}
{190}{}{A týdenní plat je v háji... už zase.}
{191}{}{Jó!}
{192}{}{Zabít, zabít, zabít!}
{193}{}{Jdi mu po krku!}
{194}{}{Zabij toho parchanta!}
{195}{}{Skoč na něj!}
{196}{}{Obejdi ho! Ne, tou druhou stranou!}
{197}{}{Bacha!}
{198}{}{To je ono!}
{199}{}{Budu bohatej!}
{200}{}{Vydělám si na nový boty!}
{201}{}{Nepárej se s ním!}
{202}{}{Nestůj na místě, ty idiote! Nestůj na místě!}
{203}{}{Doraž ho!}
{204}{}{Bojuj!}
{205}{}{Vidíš malého chlapce.}
{206}{}{Tento malý chlapec přišel na tržnici.}
{207}{}{Vidíš mladíka.}
{208}{}{Vidíš zaprášeného mladíka.}
{209}{}{Toto dítě je celé zablácené.}
{210}{}{Vidíš mladíka, který se šťourá v nose.}
{211}{}{Vidíš dítě, které na tebe zírá.}
{212}{}{Vidíš malého chlapce.}
{213}{}{Vidíš malou dívku.}
{214}{}{Vidíš roztomilé, malé děvče.}
{215}{}{Dobrý den, pane.}
{216}{}{Co děláte, pane?}
{217}{}{Ty jseš kanibal?}
{218}{}{Utíkejte, utíkejte!}
{219}{}{Jednou jsem si šáhnul na mrtvýho geckona.}
{220}{}{Jíte lidi?}
{221}{}{Já myslel, že máš na hlavě rohy.}
{222}{}{Odkud jseš?}
{223}{}{Jseš z daleka?}
{224}{}{Že mě nechytíš?}
{225}{}{Héhé, héhé, héhé!}
{226}{}{Vypadáš legračně.}
{227}{}{Pěkně smrdíš.}
{228}{}{Dobrý den, paní.}
{229}{}{Co děláte, paní?}
