{100}{}{Vidíš statného, podsaditého mue s krátkımi, hustımi vlasy.}
{101}{}{Vidíš Jamese Hoffyho, správce karavan.}
{102}{}{Vidíš zjizveného, statného mue s vypoèítavım pohledem.}
{103}{}{No tak, vypadni odsud.}
{104}{}{Tady není charita. Vypadni.}
{105}{}{Kdo tì pustil z domu?}
{106}{}{uk, uk, je tam nìkdo?}
{107}{}{Nedokáeš ani odpovìdìt?}
{108}{}{Tak dìlej, vypadni odsud.}
{109}{}{Nemám èas na debily.}
{110}{}{Slyšel jsem, e jsi mìl problémy s nìjakou karavanou. Nic si z toho nedìlej, to se stává. Nesmí se to ale stát pravidlem.}
{111}{}{Slyšel jsem, e u jsi pracoval u karavany. To je dobøe. Vdycky máme místo pro dobré stráe.}
{112}{}{Kdo jsi?}
{113}{}{Je nìjaká karavana pøipravena vyrazit?}
{114}{}{Kam všechny ty karavany odsud jezdí?}
{115}{}{Dìje se nìco zajímavého ve mìstì?}
{116}{}{Neslyšel jsi nìkdy o vìci zvané GECK?}
{117}{}{Díky, e jsi mi dal vìdìt. Sbohem.}
{118}{}{Nazdar, já jsem James Hoffy. Ale lidi mi vìtšinou øíkají Jimmy. Starám se o všechny místní karavany.}
{119}{}{Co potøebuješ, kámo?}
{120}{}{Je nìjaká karavana pøipravena vyrazit?}
{121}{}{Kam všechny ty karavany odsud jezdí?}
{122}{}{Dìje se nìco zajímavého ve mìstì?}
{123}{}{Neslyšel jsi nìkdy o vìci zvané GECK?}
{124}{}{Jenom se tak dívám, Jimmy. Díky a sbohem.}
{125}{}{To nevím, zeptej se správcù karavan, ale vìtšinou je tu potkáš 1., 11. a 21. kadı mìsíc. Pokud tu v ten den nejsou, tak to znamená, e teprv do Reddingu dorazí. Víš, vdycky kdy pøijede nìjaká nová karavana a hledá posily, její správce vztyèí svùj stan jinì od mého zámku. Máme to tady ale pìknì zavedené, co?}
{126}{}{Tvého zámku? Co tím myslíš?}
{127}{}{Aha. Tak já se jich jdu zeptat. Díky a sbohem.}
{128}{}{Posíláme karavany na tøi vzdálená místa. Vyváíme zlato do Vault City, nìco do New Rena (o-lalá, jestli mi rozumíš) a dokonce obchodujeme i s tìmi zavšivenımi bastardy z NCR.}
{129}{}{Co mi mùeš øíct o Vault City?}
{130}{}{Co mi mùeš øíct o New Renu?}
{131}{}{Co mi mùeš øíct o NCR?}
{132}{}{Chci se ještì na nìco zeptat.}
{133}{}{To bude prozatím všechno. Díky a sbohem.}
{134}{}{Co jiného znamená pro mue jeho dùm? Vyrostl jsi snad ve stanu nebo co?}
{135}{}{Vlastnì... ano.}
{136}{}{U to nebudu poslouchat, ty zatracenej magore. Sbohem.}
{137}{}{No jo, tím se to vysvìtluje. Spousta vìcí. Hehe.}
{138}{}{Teï kdy se to všechno vysvìtlilo, chci se ještì na nìco zeptat.}
{139}{}{Jo, to vìøím. Sbohem.}
{140}{}{Vault City? (Jimmy si pohrdavì odplivne.) Dobøe, povím ti o tìch zkurvysynech. Ti zasraní parchanti si myslí, e jsou nìco víc. Vymìòují s námi léky jen proto, e potøebují naše zlato, jinak by nás nechali shnít. Bıt tebou, nezdrel bych se tam moc dlouho, ale jestli se tam pøece jenom chceš podívat, karavana vyjídí kadı první den v mìsíci.}
{141}{}{Co mi mùeš øíct o New Renu?}
{142}{}{Co mi mùeš øíct o NCR?}
{143}{}{Díky. Chci se ještì na nìco zeptat.}
{144}{}{To bude prozatím všechno. Sbohem.}
{145}{}{To je zajímavé mìsto. A tam budeš, tak si dávej bedlivı pozor a rozhodnì nespouštìj prst ze spouštì. New Reno je toti mìsto plné rvaèek a pøestøelek. Kdyby všechny tamní rodiny alespoò trošku spolupracovali, bylo by New Reno opravdu silné. Ale teï jsou spíš... k smíchu. Jestli se tam chceš podívat, zeptej se Savinelliho. Jeho karavana odsud odjídí 21. kadı mìsíc.}
{146}{}{Co mi mùeš øíct o Vault City?}
{147}{}{Co mi mùeš øíct o NCR?}
{148}{}{Díky. Chci se ještì na nìco zeptat.}
{149}{}{To bude prozatím všechno. Sbohem.}
{150}{}{New California Republic je plné samıch arogantních zkurvysynù. Myslí si o sobì, e jenom jejich zpùsob ivota je ten správnı. Nikde nenajdeš arogantnìjší bandu, ne jsou oni, ale jestli se tam i pøesto chceš podívat, zeptej se Stanwella. Jeho karavana odsud odjídí 11. kadı mìsíc.}
{151}{}{Co mi mùeš øíct o Vault City?}
{152}{}{Co mi mùeš øíct o New Renu?}
{153}{}{Díky. Chci se ještì na nìco zeptat.}
{154}{}{To bude prozatím všechno. Sbohem.}
{155}{}{GECK? Nejsem si sice úplnì jistı, ale myslím, e tu ádnı nemáme. Hmm, zkus to ve vaultu. Tam by snad mìli mít tyhle technologickı vìcièky, ne?}
{156}{}{Zkusím se do nìjakého podívat. Chci se ještì na nìco zeptat.}
{157}{}{Díky za radu. Sbohem.}
{158}{}{Jo, slyšel jsem, e se našel nìjakı nováèek, kterı chce jít do starého Wanamingo dolu pro nìjakou souèástku.}
{159}{}{Slyšel jsem, e šerif našel nìkoho, kdo za nìj udìlá špinavou práci.}
{160}{}{Nic zvláštního se nedìje. Jenom se poøád dokola tìí a jezdí s karavany.}
{161}{}{No, ten nováèek jsem já. Máš s tím snad nìjakı problém?}
{162}{}{Nìkdo v tomhle zavšiveném mìstì musí udrovat poøádek.}
{163}{}{Chci se ještì na nìco zeptat.}
{164}{}{Jen se tak ptám. Díky a sbohem.}
{165}{}{Ne, nemám s tím problém, ale je ti doufám jasné, e si zahráváš s ohnìm?}
{166}{}{Co tím myslíš?}
{167}{}{Jo, jasnì. Sbohem.}
{168}{}{No, ten dùl, kterému dáš tu souèástku, na tom bude potom dobøe. Tak dobøe, e ten druhı dùl zcela jistì zkrachuje.}
{169}{}{A...?}
{170}{}{Tomu se øíká kapitalismus, pøíteli. Sbohem.}
{171}{}{No, kdy dáš tu souèástku dolu Kokoweef, zaène se ve mìstì objevovat spousta vyvrhelù z NCR. Kdy ten šastnı bude Dan McGrew z dolu Morningstar, objeví se tu místo toho hromada Jetu. Ale takovı u je ivot, nìkdo vyhraje a nìkdo zase prohraje.}
{172}{}{Ale kdy nic neudìlám, nevyhraje nikdo. Povìz mi ještì o nìèem jiném.}
{173}{}{Tak u to na svìtì chodí nebo ne? Sbohem.}
{174}{}{No, hlavnì, e to nemusím dìlat já, kámo.}
{175}{}{Chci se ještì na nìco zeptat.}
{176}{}{Jen procházím. Sbohem.}
