{100}{}{Vidíš unavenou enu, která mohla bıt zamlada docela pohledná.}
{101}{}{Vidíš Lou, majitelku hospody U Malamuta.}
{102}{}{Vidíš hodnì nalíèenou starší enu.}
{103}{}{Chci ti jen øíct, e jsem ti moc vdìèná. Mùu ti nìjak pomoct?}
{1103}{}{Zdravím. Jmenuju se Lou a tohle je moje hospoda U Malamuta, nejlepšího podniku na sever od San Francisca. Chci ti jen øíct, e jsem ti moc vdìèná. Mùu ti nìjak pomoct?}
{104}{}{Vìzení není pro toho bastarda dostateènım trestem.}
{1104}{}{Já jsem Lou a tohle je moje hospoda U Malamuta, nejlepšího podniku na sever od San Francisca. Vìzení není pro toho bastarda dostateènım trestem.}
{105}{}{Nemùu uvìøit, e necháš toho bastarda jít. A ještì máš tu odvahu se sem vrátit! Co sakra chceš?}
{1105}{}{Já jsem Lou a tohle je moje hospoda U Malamuta, nejlepšího podniku na sever od San Francisca. Nemùu uvìøit, e necháš toho bastarda jít. A ještì máš tu odvahu se sem vrátit! Co sakra chceš?}
{106}{}{Jsi poøád hroznı idiot. Ale ivot jde dál... pro vìtšinu z nás. Co sakra ještì chceš?}
{1106}{}{Jsi poøád hroznı idiot. Ale ivot jde dál... pro vìtšinu z nás. Já jsem Lou a tohle je moje hospoda U Malamuta, nejlepšího podniku na sever od San Francisca. Co sakra ještì chceš?}
{107}{}{Pamatuj si, co jsem øekla. Pøíliš mnoho penìz nedìlá tomu dìvèeti dobrotu. Co potøebuješ?}
{1107}{}{Já jsem Lou a tohle je moje hospoda U Malamuta, nejlepšího podniku na sever od San Francisca. Pamatuj si, co jsem øekla. Pøíliš mnoho penìz nedìlá tomu dìvèeti dobrotu. Co potøebuješ?}
{108}{}{Zdravím. Já jsem Lou a tohle je moje hospoda U Malamuta, nejlepšího podniku na sever od San Francisca.}
{109}{}{Co to bude?}
{110}{}{Ooo?}
{111}{}{Ahoj, Lou. Potøebuju nìjaké vìci.}
{112}{}{Neslyšela jsi o vìci zvané GECK?}
{113}{}{Ahoj, Lou. Co se tady ve mìstì dìje?}
{114}{}{Co je to malamut?}
{115}{}{Kde je San Francisco?}
{116}{}{Pomáhám šerifovi. Øekl mi, e tu nìkdo poøezal jedno z tvıch dìvèat.}
{117}{}{Je mi líto, ale nemám moc èasu ani trpìlivosti pro hlupáky. Co potøebuješ?}
{118}{}{Blití?}
{119}{}{Pokoj?}
{120}{}{Pá pá.}
{121}{}{Myslíš pití, viï? No, to bude $25 za hezky vychlazenou láhev piva. Dávám ti speciální slevu, páè soucítím s tìmi jednoduššími.}
{122}{}{Blití? [Dret penìenku v ruce]}
{123}{}{Pokoj?}
{124}{}{Ne blití. Pá pá.}
{125}{}{Ty chceš pokoj, viï? No, moná bych pro tebe nìco mìla. Jedno útulné místeèko tì bude stát $50.}
{126}{}{Pokoj. [Dret penìenku v ruce]}
{127}{}{Blití?}
{128}{}{Ne pokoj. Pá pá.}
{129}{}{Mùeš jít dovnitø, ale to tvoje pojízdné "obludárium" zùstane venku.}
{130}{}{Slyšíš? Nechci ádné obludy ve své hospodì.}
{131}{}{Tyhle *vìci* do mé hospody nesmìjí. Nech je venku.}
{132}{}{Nejsem si jistá, jestli jsem u o tom nìkdy slyšela. Co je to?}
{133}{}{No, je to zaøízení, které se pouívá pro... eh, hmm. Je to prostì nìco, co hledám. Povìz mi ještì o nìèem jiném.}
{134}{}{Nic dùleitého. No, radìji pùjdu.}
{135}{}{No, tìíme hlavnì zlatou rudu a prodáváme ji ostatním mìstùm.}
{136}{}{Vy tu tìíte zlatou rudu?}
{137}{}{Komu tu rudu prodáváte?}
{138}{}{To je zajímavé. Povìz mi ještì o nìèem jiném.}
{139}{}{Jo. Jen v severní èásti mìsta jsou dva fungující doly na zlato.}
{140}{}{Øíkala jsi, e tu rudu prodáváte?}
{141}{}{Zajímavé. Chci se ještì na nìco zeptat.}
{142}{}{No, vymìòujeme zlatou rudu za lékaøské potøeby z Vault City. Dále ji vymìòujeme za èerstvé brahmíny z NCR a jiné potraviny a taky za drogy a chlast z New Rena.}
{143}{}{Vy tu tìíte zlato?}
{144}{}{Zajímavé. Chci se ještì na nìco zeptat.}
{145}{}{Takovı velkı pes.}
{146}{}{Aha, chápu. Hmm, chci se ještì na nìco zeptat.}
{147}{}{A jo vlastnì! To bude asi všechno. Díky a sbohem.}
{148}{}{San Francisco je hodnì na jihu. Je to odsud pìknì daleko. Jdi na jih a pak trochu na západ. Je to hned vedle oceánu. Ukáu ti to na mapì. Ale nechápu, proè by tam chtìl nìkdo normální jít.}
{149}{}{Proè? Je to nebezpeèné?}
{150}{}{Zajímavé. Chci se ještì na nìco zeptat.}
{151}{}{Díky za informace. Sbohem.}
{152}{}{No, slyšela jsem, e je celé mìsto plné nìjakıch praštìnıch náboenskıch fanatikù.}
{153}{}{Praštìnıch fanatikù?}
{154}{}{Nìkteré vìci se prostì nezmìní. Díky a sbohem.}
{155}{}{Jo, pøesnì tak. Slyšela jsem, e tam staví nìjaké obrovské zaøízení, které jim umoní spojit se s jejich bohy nebo nìco takového, ale nevím to jistì, je to opravdu daleko.}
{156}{}{Zdá se, e monumenty bohùm s sebou vdy pøinášejí nìjaké problémy. Povìz mi ještì o nìèem jiném.}
{157}{}{To bude asi všechno. Díky. Sbohem.}
{158}{}{Pøesnì tak. Je na tom dost špatnì. Byla velmi hezká. Doufám, e se o to rychle postaráš, protoe se mi u pøestává líbit, jak si ti horníci dìlají, co se jim zachce.}
{159}{}{Mùu tu dívku vidìt?}
{160}{}{Nevíš, kdo to udìlal?}
{161}{}{Mùeš mi øíct, co se pøesnì stalo?}
{162}{}{To vypadá na velikı problém. Chci se ještì na nìco zeptat.}
{163}{}{Poslala jsem ji pryè. V tomhle oboru by u stejnì nemìla moc uplatnìní. Stejnì by s ní u nikdo nechtìl bıt poté, co jí ten bastard tak zøídil. Take jsem jí dala nìjaké peníze a nechala ji jít.}
{164}{}{Nevíš, kdo to udìlal?}
{165}{}{Mùeš mi øíct, co se pøesnì stalo?}
{166}{}{Chci se ještì na nìco zeptat.}
{167}{}{Pokusím se to objasnit. Mùeš se na mì spolehnout. Sbohem.}
{168}{}{Nejsem si jistá, kdo to udìlal, ale kdy jsme ji našli, drela v ruce platidlo dolu Morningstar a navíc s ní byl naposledy nìjakı horník.}
{169}{}{Mùu tu dívku vidìt?}
{170}{}{Mùeš mi øíct, co se pøesnì stalo?}
{171}{}{Platidlo dolu Morningstar? Co je to?}
{172}{}{Chci se ještì na nìco zeptat.}
{173}{}{Pokusím se to objasnit. Mùeš se na mì spolehnout. Sbohem.}
{174}{}{No, slyšela jsem nìjakı dlouhı vıkøik, tak jsem se šla podívat do toho pokoje. Kdy jsem tam pøišla, ten bastard byl u pryè a moje dìvèe leelo v kalui krve. Pak jsem zavolala doktora a nakonec šerifa. Zbytek u znáš.}
{175}{}{Nevíš, kdo to udìlal?}
{176}{}{Mùu tu dívku vidìt?}
{177}{}{Chci se ještì na nìco zeptat.}
{178}{}{Pokusím se to objasnit. Mùeš se na mì spolehnout. Sbohem.}
{179}{}{Dan McGrew provozuje dùl Morningstar v severní èásti mìsta. Horníci vìtšinou dostávají zaplaceno na úèet nebo stvrzenkami... vdy víš, plastikovımi mincemi. No a moje dívka byla nalezena s jednou takovou mincí v ruce. Tady je, podívej. (Pøedá ti minci.)}
{180}{}{Aha, chápu. Mùu tu dívku vidìt?}
{181}{}{Aha, chápu. Mùeš mi øíct, co se pøesnì stalo?}
{182}{}{Chci se ještì na nìco zeptat.}
{183}{}{Pokusím se to objasnit. Mùeš se na mì spolehnout. Sbohem.}
{184}{}{No, jsem ráda, e se aspoò nìkdo najde. Taková vìc se prostì nedìlá. Doufám, e toho bastarda chytíš a dáš mu co proto. Zaøiï, aby to u nikomu neudìlal.}
{185}{}{No, udìlám, co budu moct. Chci se ještì na nìco zeptat.}
{186}{}{Uvidím, co se dá dìlat. Sbohem.}
{187}{}{Co pro tebe mùu udìlat? Chceš prázdnou postel, nebo s nìkım? Moná nìjakı chlast nebo jiné zboí?}
{188}{}{Chci pokoj s prázdnou postelí, Lou.}
{189}{}{Postel s nìkım? To zní dobøe. Povìz mi o tom víc.}
{190}{}{Chlast nebo jiné zboí? Tak to je nìco pro mì. Pojïme obchodovat.}
{191}{}{Hmm, chci se ještì na nìco zeptat.}
{192}{}{Bude to všechno, nebo chceš ještì nìco koupit?}
{193}{}{Vypadá to, e se nemùeš rozhodnout. Bude to všechno, nebo se chceš podívat ještì jednou?}
{194}{}{Ne. To u bude opravdu všechno. Díky. Povìz mi ještì o nìèem jiném.}
{195}{}{Hmm, chci se ještì jednou podívat na tvoje zboí.}
{196}{}{Díky, Lou. To bude prozatím všechno. Sbohem.}
{197}{}{Take ty se chceš vyspat, jo? No, to tì bude stát $40. V cenì je zahrnuto i èerstvì vyprané povleèení. Poøád máš zájem?}
{198}{}{To beru, Lou.}
{199}{}{Hmm, odpoèinu si jindy. Chci se ještì na nìco zeptat.}
{200}{}{Bohuel na to teï nemám peníze. Chci se ještì na nìco zeptat.}
{201}{}{Nejseš náhodou jeden z Faniinıch zákazníkù? Proè si radši nepromluvíš s ní? Je nìkde vzadu.}
{202}{}{Jsi hotové prokletí. Potom, co se stalo s Fannie Mae, s tebou nechtìjí mít mé dívky nic spoleèného... a ani se jim nedivím.}
{203}{}{Hledáš nìkoho, kdo ti pomùe zahøát tu velkou postel, jo? Poèkej, podívám se, kdo má momentálnì volno. Hmm, zkus se zeptat Fannie Mae. Mìla by se tu nìkde poflakovat. S ní u se na nìèem domluvíš.}
{204}{}{To zní jako dobrı nápad, jdu za ní. Sbohem.}
{205}{}{Ale já... dobøe. Sbohem.}
{206}{}{Ty a Fannie jste u spolu nìco mìli. Proè si radši nepromluvíš s ní? Je nìkde vzadu.}
{207}{}{Jsi hotové prokletí. Potom, co se stalo s Fannie Mae, s tebou nechtìjí mít mé dívky nic spoleèného... a ani se jim nedivím.}
{208}{}{U nás pracují jenom dìvèata, zlato, ale pokud ti to nevadí, zkus se domluvit s Fannie Mae. Je nìkde vzadu. S ní u se na nìèem domluvíš.}
{209}{}{To zní jako dobrı nápad, jdu za ní. Sbohem.}
{210}{}{Ale já... dobøe. Sbohem.}
{211}{}{Nemùu uvìøit, e jsi byl tak hloupı a dal Fannie tolik penìz. Díky tomu se pøedávkovala. Jsi idiot nebo co?}
{212}{}{To mi nikdo neøekl. Opravdu. No tak, Lou... chci se ještì na nìco zeptat.}
{213}{}{Bylo jen na ní, co udìlá se svım ivotem. Sbohem.}
{214}{}{Vysvobodil jsem ji z tohohle posranıho svìta. Ty taky nejsi ádnej svatoušek, Lou. Sbohem.}
{215}{}{Take ty jsi ten idiot, co dává mé Fannie všechny ty peníze. To bych nedìlala bıt tebou. Myslíš si, e jí tím pomáháš, ale mılíš se.}
{216}{}{Co tím myslíš?}
{217}{}{Pomáhám jí zaèít novı ivot.}
{218}{}{Jo, jak myslíš. Promluvme si o nìèem jiném.}
{219}{}{Tím myslím, e má Fannie problém a peníze jí nepomùou. Nechci tì urazit, ale Fannie z tebe dìlá blbce. Ty peníze chce jenom proto, aby si mohla koupit víc Jetu. Hodnì Jetu.}
{220}{}{Myslím, e se jen bojíš, e pøijdeš o jednu ze svıch nejlépe vydìlávajících dìvèat. Chceš si svoje dívky udret za kadou cenu.}
{221}{}{Jo, jasnì. U to nebudu dál poslouchat. Sbohem.}
{222}{}{Svımi penìzi jí pomáháš leda tak do hrobu. Nakupuje za nì strašnì moc Jetu. Pokud jí je nepøestaneš dávat, tak se jednoho dne pøedávkuje.}
{223}{}{Hmm, budu o tom pøemıšlet.}
{224}{}{Budu o tom pøemıšlet. Sbohem.}
{225}{}{Mùeš si myslet, co chceš, já jsem ti jenom chtìla øíct, jaká je to svinì. Je na tobì, jestli tomu vìøíš nebo ne.}
{226}{}{To u jsem všechno slyšel. Vrame se k jinım záleitostem.}
{227}{}{Díky, budu o tom pøemıšlet. Chci se ještì na nìco zeptat.}
{228}{}{Popøemıšlím o tom. Sbohem.}
{229}{}{Hmmm... moná tu mám øešení. [Pøedat Lou Jet sérum]}
{230}{}{Co to sakra je?}
{231}{}{Zbaví ji to závislosti. A si pøíštì objedná pití, nalij obsah lahvièky do sklenice.}
{232}{}{No... tak dobøe. Potøebuješ ještì nìco?}
{233}{}{Potøebuju nìjaké vìci.}
{234}{}{Co se tady ve mìstì dìje?}

{300}{}{Podaøilo se ti zbavit Fannie závislosti na Jetu.}
{301}{}{Sbohem.}
{310}{}{Moná mám nìco, co Fannie pomùe. [Pøedat Lou Jet sérum]}