{100}{}{Vidíš muže v kombinéze.}
{101}{}{Vidíš Bena Weda, správce karavany Redding - Vault City.}
{102}{}{Vidíš muže oblečeného v kombinéze vaultu.}
{103}{}{Ty máš drzost se po tom všem ještě vrátit? Tak zase odejdi, pro mě už nikdy pracovat nebudeš.}
{104}{}{Kliď se mi z očí.}
{105}{}{Jdeme do nich!}
{106}{}{Dobře, pojďme.}
{107}{}{Nazdar, jmenuju se Ben. Ben Wade. Jsem správce karavany Redding - Vault City. Hodila by se nám další stráž, jestli ti nevadí, že odjíždíme hned teď.}
{108}{}{Nazdar, jmenuju se Ben. Ben Wade. Jsem správce karavany Redding - Vault City. Před každým výjezdem sháníme stráže. Odjíždíme prvního, takže se stav, jestli budeš mít zájem.}
{109}{}{Co chceš teď?}
{110}{}{Bůů-bůů?}
{111}{}{Potřebuješ stráž, jo?}
{112}{}{Co tahle karavana převáží?}
{113}{}{Proč čekáte s odjezdem až do prvního?}
{114}{}{To není nic pro mě. Sbohem.}
{115}{}{Zdá se mi, že je to čím dál těžší.}
{116}{}{Ha! Měli si to rozmyslet dřív, než zaútočili na moji karavanu.}
{117}{}{Ještě že jsi s námi.}
{118}{}{To je otrava. Už to prostě není jako dřív.}
{119}{}{Pustiny už nejsou tak bezpečné jako dřív.}
{120}{}{Ty nejsi žádná stráž, ty jsi podvodník. Kliď se mi z očí, srabe.}
{121}{}{Opustil jsi karavanu, takže opusť i mě.}
{122}{}{Nejsi nic jiného než zloděj. Svůj podíl sis už nakradl, takže tu nemáš co dělat.}
{123}{}{Já že jsem zloděj? Tak to si budu pamatovat, ty zatracenej nevděčníku. Sbohem.}
{124}{}{To tě bude jednou mrzet. Sbohem.}
{125}{}{Kdyby ses věnoval svojí práci a hlídal moji karavanu, měl bych dost peněz na to, abych ti zaplatil. Jenomže platí pravidlo "jak si usteleš, tak si také lehneš", což znamená, že nedostaneš nic.}
{126}{}{Ty jeden proradnej bastarde! To tě bude jednou mrzet. Sbohem.}
{127}{}{No, někdy holt štěstí nepřeje. Jako třeba v tomhle případě. Sbohem.}
{128}{}{To bylo dost špatné. Můžu ti dát jenom $500 a i tak na tom prodělám. Promiň.}
{129}{}{No, lepší něco než nic. Sbohem.}
{130}{}{Ty jeden proradnej bastarde! Nikdo by neudělal lepší práci než já. To tě bude jednou mrzet. Sbohem.}
{131}{}{Tahle karavana byla úspěšná. Tady máš $1000. Rád jsem s tebou pracoval a doufám, že tě tu ještě někdy uvidím.}
{132}{}{Už nikdy nechci strávit tolik času pozorováním brahmíních zadků. Sbohem.}
{133}{}{To nebylo tak špatné. Uvidíme se později. Sbohem.}
{134}{}{Pane jo! To byla výborná jízda. Tady máš $1000 a dalších $200 za skvěle odvedenou práci. Ty jsi snad dítě štěstěny. Určitě s námi musíš jet i příště.}
{135}{}{Konečně potkávám někoho, kdo je schopen ocenit moji práci. Uvidíme se později... možná. Sbohem.}
{136}{}{Nikdy nepohrdnu penězi navíc. Díky a sbohem.}
{137}{}{To se těžko vysvětluje. Záleží to hlavně na tom, za jak dlouho se podaří vytěžit dostatek zlata. Sice nejsem horník, ale myslím, že by to nemělo trvat déle než pár týdnů.}
{138}{}{No, protože si nejsem jistý, jak dlouho potrvá sehnat všechny ty lékařské potřeby. Pravděpodobně ne déle než pár týdnů. Teprve potom můžeme vyrazit. Stav se, pokud budeš mít zájem o práci.}
{139}{}{Co většinou převážíte?}
{140}{}{Chci se ještě na něco zeptat.}
{141}{}{Díky, stavím se. Sbohem.}
{142}{}{Sice pořád hledáme strážce karavan, ale tahle karavana nebude ještě pár dní připravena vyrazit. Stav se až prvního.}
{143}{}{Proč až prvního?}
{144}{}{Co tahle karavana převáží?}
{145}{}{Aha, díky. Sbohem.}
{146}{}{Je mi líto, kámo, ale už máme strážných dost.}
{147}{}{Aha, dobře.}
{148}{}{No, ve Vault City nabíráme plný náklad lékařských potřeb a potom ho v Reddingu vyměňujeme za zlato.}
{149}{}{Zajímavé. Říkal jsi, že sháníš stráže?}
{150}{}{Chci se ještě na něco zeptat.}
{151}{}{Aha, dobře. Sbohem.}
{152}{}{Jdeš právě včas, zrovna odjíždíme. Nabízím ti $1000, ale jenom tobě, jelikož potřebuju jenom jednu stráž. Bereš to?}
{153}{}{Jdeš právě včas, zrovna odjíždíme. Nabízím ti $1000. Bereš to?}
{154}{}{To zní dobře. Můžeme vyrazit.}
{155}{}{Myslím, že strážce karavany není práce pro mě. Uvidíme se později. Sbohem.}
{156}{}{Dostal jsi bezpečný převoz a tři teplá jídla denně. A teď odsud vypadni, blbečku.}
{157}{}{Oooo? Pápá.}
{158}{}{Ááááá! Já zabít!}
