{100}{}{Vidíš muže v pracovních šatech.}
{101}{}{Je to obchodník s brahmínami. Očekává Halovu karavanul.}
{102}{}{Páchne po brahmínách.}
{113}{}{No, tak to je teda pěkně v hajzlu! Bojím se, že za tenhle okruh nikdo z nás žádný prachy nedostane. Můžem bejt rádi, že jsme zůstali naživu.}
{114}{}{No, rančeři z toho nejsou zrovna na větvi - jenom $1000 za okruh. Holt smůla.}
{115}{}{No, měli jsme trochu smůly, ale jinak to bylo v pohodě. Tady máš těch $2000.}
{116}{}{Zatraceně, to bylo skvělý! Tady máš $1000 navrch k těm $2000, který jsem ti slíbil. A Redding dneska zažije malý zemětřesení!}
{118}{}{Ty jseš ta nejhorší napodobenina strážce, jakou jsem kdy viděl. Vypadni odsud.}
{119}{}{Škoda, Hal to nezvládl.}
{120}{}{Škoda Hala...}
{121}{}{Bylo mi potěšením s tebou obchodovat.}
{213}{}{K čertu, Hal zhebnul! A brahmíny taky! Bojím se, že za tenhle okruh nikdo z nás žádný prachy nedostane. Můžem bejt rádi, že jsme zůstali naživu.}
{214}{}{Dohajzlu Hal chcípnul! Rančeři z toho nejsou zrovna na větvi, jenom $1000 za okruh. Holt smůla.}
{215}{}{Zatraceně, Hal se odebral k pánu! No, měli jsme trochu smůly, ale jinak to ušlo. Tady máš těch $2000.}
{216}{}{Sakra, Hal zahynul! Přesto to docela zvládl. Tady máš $1000 navrch k těm $2000, který jsem ti slíbil. A Redding dneska zažije malý zemětřesení!}
