{100}{}{Vidíš mladého mue s odznakem policie NCR.}
{101}{}{Vidíš Karla, zástupce mìsta.}
{102}{}{Vidíš mladíka sotva odrostlého z puberty. Vypadá vlídnì.}
{103}{}{Vítej, cizinèe. Jsem Karl a zastupuji toto mìsto. Co pro tebe mohu udìlat?}
{104}{}{Jako tøeba?}
{105}{}{Eh... heee..}
{106}{}{Jsem v NCR nováèek. Co mi mùeš øíct o tomhle mìstì?}
{107}{}{No, hledám Vault 13.}
{108}{}{Posílá mì prezidentka Tandi. Mám si promluvit s vaším vìznìm.}
{109}{}{Jmenuju se}
{110}{}{Hledám chlápka jménem Jack. Øíkají mu taky Whack Jack.}
{111}{}{Kde najdu Rogera Westina?}
{112}{}{Hmm, trochu jsme moc bumbali, e? Podívej, tamhle je volná cela. Co takhle si tam lehnout a vyspat se z toho?}
{113}{}{Poslyš, dám ti radu. Øekni tìm svım pøátelùm, a si tì odvedou domù a hezky se z toho vyspi. Pití na veøejnosti je zde trestnım èinem.}
{114}{}{Tohle je NCR, hlavní mìsto New California Republic. 3000 obyvatel a stále se rozrùstá. ádní otroci, ádné hazardní hry a ádné drogy. Prezidentkou je paní Tandi a mım šéfem je šerif Dumont. Staèí ti taková odpovìï?}
{115}{}{Dobøe, mám ještì nìjaké otázky.}
{116}{}{Jo, to bude všechno.}
{117}{}{To já taky, kdy jsem byl malı. Dej mi vìdìt, pokud ho najdeš!}
{118}{}{Dobøe, mám ještì nìjaké otázky.}
{119}{}{No, tak dík.}
{120}{}{Jmenuje se Oswald. Víc jsme z nìj nedostali. Prı je to squatter z Vaultu 15, ale... pochybuji o tom. Na to je pøíliš drsnı. Chápeš, co tím myslím?}
{121}{}{Je to drsnı chlap, jo?}
{122}{}{Co s ním chcete dìlat?}
{123}{}{O tobì u jsem urèitì slyšel. Jo... jen samé dobré vìci. Poslyš, vím o pár lidech, kterım by se tvoje dovednosti hodily. Zajdi do obchodu s auty a ptej se po Elise. Øekni jí, e ji Karl pozdravuje.}
{124}{}{Work? The Stockman's Association is looking for guards. Raiders been hitting the cattle drives hard again. And I heard that President Tandi's been looking for somebody "resourceful," as she puts it. That help?}
{125}{}{Dobøe, mám ještì nìjaké otázky.}
{126}{}{Trochu. Díky.}
{127}{}{To je dùstojník Jack, cizinèe. Jeden z našich lidí. Ještì jsi nemluvil s Mirou, e ne?}
{128}{}{Ano.}
{129}{}{Kdo je Mira?}
{130}{}{That SOB? He's got a spread just outside town. Just take the road past Stockman's.}
{131}{}{Ty ho asi nemáš moc rád, e?}
{132}{}{Dobøe, mám ještì nìjaké otázky.}
{133}{}{Díky.}
{134}{}{Jo. Je opravdu zlı. Zabil dva z našich muù a neøekl ani slovo.}
{135}{}{Nech mì s ním chvíli o samotì. Tøeba ho pøesvìdèím, aby spolupracoval.}
{136}{}{Mùu ho teï vidìt?}
{137}{}{Povìsíme toho bastarda, aspoò doufám. On a jeho banda zabili dva dobré mue. Nebude mì ani trochu mrzet a bude mrtvı.}
{138}{}{Mùu ho teï vidìt?}
{139}{}{Víš, ona a Jack byli kdysi manelé. Prošli si opravdu drsnım rozvodem. Nevìøil bych jí ani slovo, rozhodnì ne cokoliv o Jackovi. Bude lepší, kdy se do toho nebudeš plést. Jack je dobrı chlap, jen je teï trochu napjatı.}
{140}{}{Dobøe, pøejdìme na jiné téma.}
{141}{}{No, díky moc za radu, zástupce.}
{142}{}{Jeho bıvalá. Jestli není tady, mùe bıt v elektrárnì. Pøivydìlává si tam v noci u Dorothy.}
{143}{}{Dobøe, mám ještì nìjaké otázky.}
{144}{}{Díky.}
{145}{}{Koukám, e je to na mnì vidìt. Spousta lidí k nìmu vzhlíí, protoe je radní, ale já ne. Myslí si o sobì, e je nìkdo, jako by pro nìj zákony neplatily. Byl bych rád, kdyby mu jednou spadl høebínek.}
{146}{}{Co není, mùe bıt. Co mi o nìm mùeš øíct?}
{147}{}{Musím jít. Øíkal jsi venku za mìstem?}
{148}{}{ádnı problém. Budu pøedstírat, e tu pìt minut nejsem. Pojï za mnou.}
{149}{}{Jistì, proè ne?}
{150}{}{No, pøed pár lety mìl mrtvici a teï má od doktora Jubilee pøedepsané nìjaké léky. Proè tì to vùbec zajímá?}
{151}{}{To nic, jen tak. U tì nebudu zdrovat.}
{152}{}{. Hledám nìjakou poctivou práci.}
{153}{}{Tandi øíkat ty tady mít špatná chlap.}
{154}{}{Já chtít vidìt špatná chlap.}
