{100}{}{Vidíš muže v kevlarové zbroji.}
{101}{}{Vidíš ženu v kevlarové zbroji.}
{102}{}{Nosí odznak s nápisem NCR Ranger.}
{103}{}{Nosí odznak s nápisem NCR Ranger.}
{200}{}{Zdravím, kolego Rangere. Chystáš se tu strávit noc?}
{201}{}{Zabil jsi dneska nìjaké otrokáøe?}
{202}{}{Dneska jsme osvobodili tucet otrokù.}
{203}{}{Ochrana pustiny je tvrdá práce, ale nìkdo to dìlat musí.}
{204}{}{Ještì že tì máme. Mùžeš tu zùstat jak dlouho chceš.}
{205}{}{Slyšel jsem, co se stalo Metzgerovi. Dobrá práce!}
{300}{}{To je otrokáø, na nìj!}
{301}{}{Do prdele, útoèí na nás!}
{400}{}{Buï zdráv, pøíteli.}
{401}{}{Tohle je soukromý pozemek. Neokounìj tady moc dlouho.}
{402}{}{Máš rád otrokáøe? Doufám, že ne... pro tvoje vlastní dobro.}
{500}{}{Co to!? Otrokáøi? Jak nás sakra našli? Musíme se bránit. Útok!}
{501}{}{Poèkejte! Já jsem na vaší stranì. Jen jsem vám pøivedl nìjaké cvièné cíle. [Otoèit se na otrokáøe] Je mi líto, hoši, ale já už jsem takovej. [Zaútoèit na otrokáøe]}
{502}{}{Tohle bude zábava! [Zaútoèit na Rangery]}
{600}{}{Podaøilo se ti vyhladit úkryt Rangerù.}
