{100}{}{Vidíš muže v umazaném oblečení, nejspíš mechanika.}
{101}{}{Vidíš Ronda, majitele tohoto podniku.}
{102}{}{Myslíš si, že je to mechanik, ale nosí u sebe zbraň, což je trochu zvláštní.}
{103}{}{Vítej, Rangere. Doufám, že se ti daří.}
{104}{}{Jednou ty otrokáře úplně vyhladíme.}
{105}{}{Musím jít zase někdy na lov otrokářů.}
{106}{}{Promiň, ale máme zavřeno.}
{107}{}{Tohle je soukromý majetek. Odejdi prosím.}
{108}{}{Momentálně nepřijímám žádné další zakázky, jasný?}
{109}{}{Nezahrávej si s Rangery, bastarde.}
{110}{}{Ještě jednou se dotkni mých věcí a já ti ukážu, zač je toho loket.}
