{100}{}{Vidíš šedovlasého muže v uniformě NCR policie.}
{101}{}{Vidíš šerifa NCR.}
{102}{}{Tento muž je názorná ukázka toho, jak by měl správný policista vypadat - vlasy na ježka, hranatá čelist a přímočaré vystupování.}
{103}{}{Vítej v NCR, cizinče. Jmenuju se Dumont, šerif Dumont. Doufám, že si to tady užíváš v míru a poklidu.}
{104}{}{Přijmi malou radu od šerifa Dumonta, cizinče - v tomhle městě nemáme rádi lidi, jako jsi ty. Jakékoliv potíže a půjdu tvrdě po tobě. Můžu pro tebe teď něco udělat?}
{105}{}{Zdravím. Můžu pro tebe něco udělat?}
{106}{}{No tak se vymáčkni.}
{107}{}{Heegh.}
{108}{}{Hledám Vault 13. Nevíš, kde se nachází?}
{109}{}{Nemáš GECK?}
{110}{}{Hledám nějakou poctivou práci. Nevíš o něčem?}
{111}{}{Jo, je tu fajn. Všechno je báječné.}
{112}{}{Primitiv, že? Ty. Otázky? Ptát já. Ano?}
{113}{}{Vault 13?}
{114}{}{GECK?}
{115}{}{Dobře.}
{116}{}{Ne, to nevím, ale je to něco, co by ráda věděla i prezidentka Tandi. Vyřešilo by nám to spoustu problémů.}
{117}{}{Problémů? Jakých problémů?}
{118}{}{Prezidentka Tandi?}
{119}{}{Dobře. Jen zkouším štěstí. Díky.}
{120}{}{Poslyš, já vedu prospěšný život a mám čistý rejstřík! Nemám žádný GECK ani cokoliv podobného.}
{121}{}{Tak promiň! Nevíš náhodou, kde se nachází Vault 13?}
{122}{}{Tak na to zapomeň. Už půjdu.}
{123}{}{O něčem bych věděl, jestli máš zájem.}
{124}{}{Děláš si srandu, ne? Po té události s Jackem? Myslím, že by se určitě nějaká slušná práce našla.}
{125}{}{Například?}
{126}{}{Změňme téma.}
{127}{}{Zapomeň na to, odcházím. Sbohem.}
{128}{}{Ne Vault 13. Vault 15 ano.}
{129}{}{Pat-náct?}
{130}{}{Ne. Tři-náct!}
{131}{}{Ano, 15! Ty mluvit s Tandi. Velký náčelník NCR. Tandi znát Vault. Hledat pomoc. Ty jít za Tandi.}
{132}{}{Tandi?}
{133}{}{Já nejít. Já chtít 13!}
{134}{}{Po-slou-chej. Žádný Vault 13. Nenalezen. Nevidět. Ne 13. Vault 15 - lidé najít. Lidé žít ve Vault 15. Ty rozumět?}
{135}{}{Ne tři-náct? Pat-náct?}
{136}{}{NE. JÁ CHTÍT TŘINÁCT!}
{137}{}{Ááááá! NENÍ ŽÁDNÁ 13, TY TUPEJ ZABEDNĚNČE! Žádná 13. Nenalezen. Vůbec! Nikdy!}
{138}{}{Tandi velký náčelník. Tandi chtít pomoct. Ty mluvit s Tandi. Jít do kon-gresu. Rozumět?}
{139}{}{GECK?}
{140}{}{Dobře.}
{141}{}{Nepotřebovat GECK. Já zdravý. Ne nemocný.}
{142}{}{Vault 13?}
{143}{}{Dobře.}
{144}{}{Rozhlédni se kolem sebe. NCR se neustále rozrůstá. Potřebujeme součástky, počítače a tak podobně. Jenomže máme problém se squattery, kteří se zabydleli ve Vaultu 15.}
{145}{}{Vault 15? Squatteři? O co tady jde?}
{146}{}{Kdo je to ta prezidentka Tandi?}
{147}{}{Díky za informace.}
{148}{}{To je přeci prezidentka NCR, kdo jiný? Musí mít opravdu velké starosti, protože mě dokonce požádala o to, abych jí půjčil jednoho ze svých zástupců na jednu speciální misi. Ale bohužel nemůžu momentálně nikoho postrádat, takže jsem to musel velmi nerad odmítnout.}
{149}{}{A co třeba já? Možná bys mě mohl doporučit.}
{150}{}{Hmm. Koukám těžký život.}
{151}{}{Tebe? Hmmm... to by nešlo. Vždyť tě ani neznám... ale je pravda, že někoho shání, takže si s ní můžeš jít promluvit. Její kancelář je v budově Kongresu.}
{152}{}{Díky. Zastavím se tam.}
{153}{}{Nevíš něco o věci zvané GECK?}
{154}{}{Hmm, to je od tebe sice zatraceně hezké, cizinče, ale taky zatraceně drzé. Ani nevím, jestli vůbec pocházíš z Adama a Evy a navíc se mi ani trochu nelíbí tvůj pohled! Nikomu tě doporučovat nebudu. A teď mám nějakou práci.}
{155}{}{Well, there's Duppo at the Stockman's. He does the hiring for the brahmin drives. Then there's Mr. Westin. If you talk to him, tell him I sent you. Even President Tandi's been asking around for some help.}
{156}{}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. Go try him.}
{157}{}{Westin?}
{158}{}{Prezidentka Tandi?}
{159}{}{Musím jít.}
{160}{}{Roger Westin. Jeho pozemky se nacházejí v západní části města. Má potíže s nějakými škůdci. Postaral by se o ně sám, jenže jeho zdraví už není to co dřív. Jak říká doktor Jubilee, má špatné srdce.}
{161}{}{Jo?}
{162}{}{Je v tomhle městě nějaká práce?}
{163}{}{Zapomeň na to. Už půjdu.}
{164}{}{Doufám, že to tak zůstane. Sbohem.}
{165}{}{To byla zatraceně dobrá práce se starým Jackem, cizinče, a protože jsem šerif, tak to odteď přebírám na starost.}
{166}{}{Je tvůj.}
{167}{}{Co takhle nějaká odměna?}
{168}{}{No, bohužel pro tebe žádnou odměnu nemám. Můžu ti jen poděkovat.}
{169}{}{Počkej, mám ještě nějaké otázky.}
{170}{}{Aha, rozumím. Tak dobře.}
{171}{}{Promiň, ale nemůžu si s tebou teď povídat. Už takhle přijdu pozdě k soudnímu ohledání mrtvého, i když mi to přijde celkem jasné.}
{172}{}{Promiň, ale žádný zločin, žádný viník.}
{173}{}{Pouštní krysy jsou to. Pochop, že kořeny tohohle města sahají až k Vaultu 15. Před dávnými časy se v něm nejspíš vyskytl nějaký problém a ti co přežili, založili Shady Sands, takže nám Vault 15 po právu patří. Jenže před několika lety se tam nastěhovali nějací squatteři a začaly zase problémy. Nejlepší bude, když si o tom půjdeš promluvit přímo s Tandi.}
{174}{}{Tandi?}
{175}{}{Beru na vědomí.}
{176}{}{Nevím o žádné další práci.}
{177}{}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. President Tandi's been asking around for some help.}
{178}{}{Kdokoliv jiný s tvou reputací by raději opustil tohle město, natož aby tady ještě hledal práci.}
{179}{}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. Go try him. Then there's Mr. Westin. If you talk to him, tell him I sent you.}
