{100}{}{Velký chlápek, velká zbraň a stále tu postává. Je to stráž.}
{101}{}{Pořád vidíš stráž.}
{102}{}{Má na čele otrokářské tetování, které ho nedělá ani o trochu chytřejším.}
{103}{}{Promluv si s panem Vortisem, ne se mnou.}
{104}{}{Eh...}
{105}{}{Máš otázky? Tak si promluv s Vortisem.}
{106}{}{Jestli budeš dělat potíže, tak uvidíš. Rozumíš?}
{107}{}{Hej, máme tady vetřelce!}
{108}{}{Poplach! Vetřelec nablízku!}
{109}{}{Pane Vortisi - nájezdníci!}
{110}{}{Tak tohle byla velká chyba.}
