{100}{}{Vidíš informační tabuli.}
{101}{}{Vidíš informační tabuli se stanovenými zákony NCR.}
{102}{}{Typická informační tabule s několika přišpendlenými papíry. Mezi nimi vyčnívají zákony NCR.}
{103}{}{Vítejte v New California Republic! Předtím, než vstoupíte do našeho krásného města, si prosím udělejte čas k obeznámení se s následujícími pravidly a nařízeními.}
{104}{}{Uvnitř města se nesmí viditelně nosit žádné zbraně.}
{105}{}{Osoby pod vlivem alkoholu nebo drog budou zatčeny.}
{106}{}{Otrokářství, hazard a prostituce jsou uvnitř města zakázány.}
{107}{}{Neznalost zákona neomlouvá. Hlupáci budou vyhoštěni stejně tak rychle jako chytráci.}
{108}{}{Jestli nehodláte dodržovat naše zákony - tak táhněte k čertu!}
{109}{}{Bude lepší, když schováš zbraně. A myslíme to vážně.}
{110}{}{Dobrý občan vždy dodržuje zákony.}
{111}{}{Zpět.}
{112}{}{Nic dalšího už číst nechci.}
{113}{}{To nevěští nic dobrého pro moje rekreační návyky.}
{114}{}{Prima, aspoň tam nebudou žádní opilci nebo žebráci, kteří jenom tahají z člověka peníze.}
{115}{}{Zpět.}
{116}{}{Nic dalšího už číst nechci.}
{117}{}{A sakra, tak to vypadá, že mám v tomhle městě s přivýdělkem útrum.}
{118}{}{Hmm... zdá se, že se tu někdo snaží vytvořit počestnou a slušnou společnost.}
{119}{}{Zpět.}
{120}{}{Nic dalšího už číst nechci.}
{121}{}{Pěkně drsná slova, ale třeba se mi je podaří obejít.}
{122}{}{Rovnost všech před zákonem nezní jako špatný nápad.}
{123}{}{Zpět.}
{124}{}{Nic dalšího už číst nechci.}
{125}{}{Naučit tyhle chlápky respektu se právě dostalo na vyšší místo na mém seznamu.}
{126}{}{No, to je sice trochu přehnané, ale naprosto srozumitelné.}
{127}{}{Zpět.}
{128}{}{Nic dalšího už číst nechci.}
{130}{}{Au au hlava bolet. Moc písmena.}
