{100}{}{Vidíš váleèníka.}
{101}{}{Vidíš Serina.}
{102}{}{Vypadá to, že je vážnì zranìn a má zlomenou nohu.}
{103}{}{Vidíš Serina. Vypadá to, že je vážnì zranìn a má zlomenou nohu.}
{104}{}{Vidíš Serina. Má zavázanou nohu a kulhá.}
{105}{}{Vidíš Serina. Vypadá už lépe a hluboce spí.}
{106}{}{Vidíš Serina. Vypadá to, že se docela dobøe zotavil.}
{200}{}{*ble* Chcípni, démone!! Už nebudeš...}
{201}{}{Uklidni se. Jsi v bezpeèí. Ten geckon je už mrtvý.}
{202}{}{Co!? Och, chvála duchùm, pøítela. Já báti, že být vyøízená.}
{203}{}{Co se tady stalo?}
{204}{}{Jerem a já jsme choditi lovit každý týden. Jít jeskynním prùchodem na pole, kde se potuluje hodnì geckonù. Lov šel špatnì. Muset utýct. Pøíliš mnoho geckonù s ducha zuøivosti. Vstoupili jsme do jeskynì. Zaèít køièet o pomoc. (Na chvíli pøestane mluvit a škubne sebou bolestí poté, co se poškrábe na noze.)}
{205}{}{Prosím, pokraèuj.}
{206}{}{Prùchod už byl na pokraji zøícení. Voda prosakovat z toku nad námi. Smrtelný prùchod, ale to býti velký zkratka na pole. Nic víc. Víš, my øváti jako idioti a strop na nás padat.}
{207}{}{[Pokraèovat]}
{208}{}{Chudák Jerem. Vidìl jsem, jak ho velká kámen rozdrtit jako mouchu. Velké kameny mì minuly, ale geckonova tlama ne. Zrovna když já mysleti já být v bezpeèí, geckon pøijít odnikud a ukousnout mi velká kus nohy. Upadnul jsem rovnou na zem. Nemít žádné kopí a já mysleti, že geckon mì mít k veèeøi. Ale duchové míti se mnou jiné plány. Poslední velký kámen svalit geckonovi na hlavu. Udìlat z nìj flek. Ale taky rozdrtit moje noha.}
{209}{}{[Pokraèovat]}
{210}{}{Takže já býti uvìznìný na zemi bez kopí. Náhle já slyšeti nìco na mì pøijít ze tmy. Pøiblížilo se to a já uvidìl, že to býti velký naštvaný geckon. Padající kameny ho jen víc nasrat. Potom ty pøijít, pøítela. Já míti u tebe dluh.}
{211}{}{Páni, to byl zajímavý pøíbìh. Zdá se, že jsi mìl velké štìstí. A co noha?}
{212}{}{Ne dobøe, pøítela. Zdá se, že kameny být silnìjší než moje kost. Já pochybovat já brzo choditi.}
{213}{}{Nemìj obavy, jsem zkušený doktor. Podívám se na tvoji nohu a uvidím, co se dá dìlat.}
{214}{}{Nemìj obavy, bez problému tì odsud odnesu. Potom se na tvoji nohu podívá šaman.}
{215}{}{Na tohle se asi bude muset pøijít podívat odborník. Zkusím nìkde rychle najít pomoc. Jeskynì už se zdá být prázdná, takže by ti nemìlo hrozit žádné nebezpeèí.}
{216}{}{Hmm... myslím, že nemám dostateènou sílu na to tì odsud odnést, ale vsadím se, že to Sulik zvládne. (Na Sulika.) Odneseme ho odsud.}
{217}{}{Hmm... myslím, že nemám dostateènou sílu na to tì odsud odnést, ale vsadím se, že to Marcus zvládne. (Na Marcuse.) Odneseme ho odsud.}
{218}{}{(Prohlížíš si váleèníkovou nohu. Je ošklivì potrhaná a na nìkterých místech vyènívá kost. Zkušenì vrátíš kost zpìt na své místo, zastavíš krvácení, dáš nohu do dlahy a stabilizuješ ji.)}
{219}{}{(Po 15-ti minutách usilovné práce už noha vypadá mnohem lépe. Zdá se, že bude tento muž jednou zase chodit.)}
{220}{}{Tak, tohle by mìlo staèit. Budeš potøebovat nìkolik dní odpoèinku na úplné zotavení. Moc ji nenamáhej a budeš zase v poøádku.}
{221}{}{Svatá ducha tì ovládat, pøítela! Já díky! Já teï dokulhati k šamanovi. Získat nìjaké dobré byliny na zmírnìní bolesti. Uvidìti se zpìt v táboøe, pøítela.}
{222}{}{[KONEC]}
{300}{}{Já díky, pøítela. Uvidìti se zpìt v táboøe.}
{400}{}{Díky moc, pøítela. Máš opravdu požehnání duchù.}
{500}{}{chrrrRRrrr...}
{501}{}{...chrrRRRRrr...pšíí...}
{600}{}{Podaøilo se ti vyléèit Serinovu nohu.}
{700}{}{Potøebuje lepší péèi, než jakou mu dokážu nabídnout. Radìji pùjdu.}
{1000}{}{Dobré na tebe koukati, hrdino.}
{1001}{}{Já nikdy nezapomenout, co ty pro mì udìlat, hrdino.}
