{100}{}{Vidíš zaprášeného cestovatele.}
{101}{}{Vidíš barmanku.}
{102}{}{Vidíš zaprášeného cestovatele.}
{103}{}{Hele, podívejte! To je ten, co nakopal Enklávě prdel!}
{104}{}{Gratulujeme, hrdino!}
{105}{}{Nazdar, hrdino! Můžu ti koupit pití?}
{106}{}{Zdá se, že Kapitán přišel navštívit chudinu...}
{107}{}{No jestlipak tohle není oblíbená vlezdoprdelka První Občanky...}
{108}{}{No jestlipak tohle není "Kapitán..."}
{109}{}{Všichni pozor. Právě vstoupil sám zákon.}
{110}{}{Přišel jsi navštívit chudinu, Občane?}
{111}{}{Nepatříš spíš do vnitřního města, "Občane?"}
{112}{}{Zatracení Občani si sem napochodujou, kdykoliv se jim zachce...}
{113}{}{Tý jo... to je mutant?!}
{114}{}{Mizíme, chlapi. Máme tady mutanta.}
{115}{}{Budeš mít problémy, až stráže uviděj toho mutanta...}
{116}{}{Oni už pouštěj dovnitř i *mutanty*?}
{117}{}{Mám dojem, že se ten mutant brzy ocitne ve Vězeňským středisku...}
{118}{}{Řekni, že to není ghoul.}
{119}{}{Co je to za *puch?!* Jdi s tím ghoulem pryč!}
{120}{}{Jdi s tím smradlavým ghoulem pryč z baru!}
{121}{}{Jestli tady po tom ghoulovi zbudou nějaký kusy těla, tak ho vykuchám.}
{122}{}{Jestli toho ghoula uviděj stráže, udělaj z něj cvičnej terč. }
{123}{}{Stěží si můžu v týhle době dovolit Denní propustku...}
{124}{}{Ceny brahmín pořád rostou...}
{125}{}{Nastane těžký období, jestli ty sucha neskončej...}
{126}{}{Přišel jste navštívit chudinu, Kapitáne?}
{127}{}{Poslyšte, já nic neudělal, Kapitáne. Starám se jen o svoje věci.}
{128}{}{Já nic nevím, Kapitáne. Nechte mě na pokoji.}
{129}{}{Jděte někam, "Kapitáne."}
{130}{}{Zdá se, že dneska udělá Lynette Občanem úplně každýho.}
{131}{}{Já už strážím peníze za ochranu dal, tak mě nech bejt.}
{132}{}{Přišel jsi navštívit chudinu, Občane?}
{133}{}{Radši se vrať do města, Občane.}
{134}{}{Vypadni, Občane.}
{135}{}{Jdi někam, Občane.}
{136}{}{Zdá se, že dneska udělá Lynette Občanem úplně každýho.}
{137}{}{Ten Smith je fajn chlap.}
{138}{}{Myslím, že nikdy Denní propustku nezískám.}
{139}{}{Nepij místní vodu. Je radioaktivní.}
{140}{}{Když kolem projde Občan, nikdy se ti nepodívá do očí a ani nepozdraví.}
{141}{}{Vault City nás možná nemá v lásce, ale aspoň nás chrání.}
{142}{}{Dávej pozor na Auto-Doka. Sice tě vyléčí...většinou, ale moc svoje štěstí nepokoušej.}
{143}{}{Ed, obchodník s dobytkem, musel zase zvýšit ceny, aby mohl zaplatit měsíční poplatek strážím.}
{144}{}{Skeeve mě nechává za podíl propašovat do města nějakou tu kořalku. }
{145}{}{Minulej tejden jsem byl na cestách. Přišel jsem z NCR, tam dole na jihu.}
{146}{}{Pár mejch přátel odešlo do Rena... a od tý doby jsem je neviděl.}
{147}{}{Prý je to v Renu zase napjatý. Rodiny se navzájem nenávidí.}
{148}{}{Prý se ghoulové z Gecka chystaj napadnout město.}
{149}{}{Nepleť se do cesty Občanům, nebo tě hned šoupnou do Vězeňského centra.}
{150}{}{Lynette je pěkně bezcitná.}
{151}{}{Vault City není tak úplně "svobodné" město. Ale není to tady nejhorší.}
{152}{}{Vault City je lepší než Den. Ale zase tady není tolik zábavy.}
