{100}{}{Vidíš... dalšího... funkcionáře Vault City.}
{101}{}{Vidíš Barkuse, velitele Centra rozdělování služebníků Vault City.}
{102}{}{Co to sak...?! Mutant! Ve Vault City! Stráže! Stráže!}
{103}{}{Co to sak...?! Ghoul! Ve Vault City! Stráže! Stráže!}
{104}{}{Emm... ehrmmm?}
{105}{}{Jestli chcete boj...}
{106}{}{Středisko rozdělování služebníků je teď zavřeno. Přijďte prosím ráno.}
{107}{}{Ano, Kapitáne?}
{108}{}{Ano, Občane?}
{109}{}{Ano, co se děje? Jsem pozadu v plnění svých úkolů.}
{110}{}{Ehmm... já hledat Valt!}
{111}{}{Odbelhat se.}
{112}{}{Co je tohle za budovu?}
{113}{}{Hledám Vault.}
{114}{}{Hledám konkrétního služebníka... Joshuu. Je tu někde?}
{115}{}{Chcete koupit otroky... eh, služebníky?}
{116}{}{Dnes nic, díky.}
{117}{}{Tahle? To je Centrum rozdělování služebníků. Potřebujete služebníka?}
{118}{}{Tohle je Centrum rozdělování služebníků.}
{119}{}{Centrum rozdělování služebníků? Co to je?}
{120}{}{Hledám konkrétního služebníka... Joshuu. Je tu někde?}
{121}{}{Rozdělování služebníků, jo? Kupujete tu otroky... eh, služebníky?}
{122}{}{Ne, jen se tak ptám. Díky.}
{123}{}{Jen se ptám. Díky.}
{124}{}{Vault? To je ta obří díra ve skále na východ od města. Vyjděte ze vstupních dveří, otočte se doleva a jděte pořád rovně. Nemůžete to minout.}
{125}{}{Co je tohle za budovu?}
{126}{}{Může jít dovnitř kdokoliv?}
{127}{}{Chci se ještě zeptat...}
{128}{}{Díky za informace. Sbohem.}
{129}{}{Což...? Vy jste nový služebník?}
{130}{}{Jo.}
{131}{}{E-he, já teď odejít.}
{132}{}{Nejspíš to tu neznáte. Vysvětlím vám to... pomalu.}
{133}{}{Občané, kteří potřebují pomoc s podřadnými pracemi, si zajdou do Centra a na den dostanou přiřazeného služebníka.}
{134}{}{To zní skoro jako otroctví.}
{135}{}{Aha, tak tady se skladují otroci. Proč jste to neřekl hned?}
{136}{}{Odkud berete všechny služebníky?}
{137}{}{Hledám konkrétního služebníka... Joshuu. Je tu někde?}
{138}{}{Nemáte zájem koupit nějaké otroky... eh, služebníky?}
{139}{}{Aha, jen se tak ptám, díky. Nashle.}
{140}{}{Už mě unavuje posílat služebníky bez řádného povolení... *vzdych* ...tak se na to podíváme. Říkáte, že hledáte Vault? To bude určitě vaše dnešní náplň práce. Tak dobře. Pošlu tam s vámi nějaký doprovod.}
{141}{}{Valt! Valt!}
{142}{}{Být vámi, dám si pozor na to, co říkáte. Tohle NENÍ otroctví. My se o tyto uprchlíky staráme a díky tomu mají slušný život... lepší, než kdyby žili venku v pustině.}
{143}{}{Odkud je berete?}
{144}{}{Hm, chci se ještě zeptat...}
{145}{}{To bude asi všechno, díky. Hezký den.}
{146}{}{Ne, přístup do Vaultu mají pouze Občané. Poslyšte, mám teď dost vlastní práce, takže mě omluvte...}
{147}{}{Ještě jednu otázku...}
{148}{}{Tak dobře. Sbohem.}
{149}{}{Naši služebníci jsou většinou uprchlíci před útoky nájezdníků nebo vězni, kteří se rozhodli odpracovat si svůj trest prospěšnými pracemi.}
{150}{}{Aha, vy myslíte skriptaře? Znám jednoho chlapíka jménem Dan, který...}
{151}{}{Za cenu vlastní svobody, jo?}
{152}{}{Máte ve vazbě vězně jménem Joshua?}
{153}{}{Nemáte zájem koupit nějaké otroky... eh, služebníky?}
{154}{}{Hmmm. Chci se ještě zeptat...}
{155}{}{Aha. Díky za informace.}
{156}{}{Ne, žádní skriptaři, ty magore.}
{157}{}{Magor? Víte jakou práci dá získat 9 Inteligence a Vnímání, aby se člověk dostal k téhle odpovědi? O čem jste to vlastně mluvil?}
{158}{}{Vy jste ten pravý na vynášení morálních soudů, otrokáři. Vypadněte odsud.}
{159}{}{Mluvíte úplně stejně jako ten idiot Moore... přesně to Vault City potřebuje. Poslyšte, ať už jste kdokoliv, mám dost práce, takže budu rád, když se ztratíte...}
{160}{}{Fajn, fajn...}
{161}{}{Donuťte mě odejít.}
{162}{}{Joshua? Ano, máme tu takového služebníka, ale určitě ho nebudete chtít najmout. Zatrénovat ho je... obtížné. Nejsem si jist, že je toho vůbec schopen.}
{163}{}{Joshua? Myslím, že jsme někoho takového kdysi měli, ale už tu dávno není.}
{164}{}{Musím se ho na něco zeptat ohledně jedné záležitosti, která se týká bezpečnosti Vault City. Nechte ho ihned poslat na Předměstí.}
{165}{}{I přesto si ho chci najmout.}
{166}{}{Obtížné?}
{167}{}{Nechci ho najmout pro sebe. To vůbec ne. Jen se obávám, že by mohl být nakažený.}
{168}{}{Hmmm. Ještě jednu otázku...}
{169}{}{Tak dobře. Sbohem.}
{170}{}{Myslím, že to není dobrý nápad. Počkejte, než podstoupí trochu víc tréninku a poté se rozhodnu.}
{171}{}{Říkáte, že se obtížně trénuje?}
{172}{}{Ještě jednu otázku...}
{173}{}{Tak dobře. Sbohem.}
{174}{}{Ano. Je mnohem vzpurnější, než kterýkoliv ze služebníků, které jsme tu doposud měli. Kdybych ho tak dobře neznal, myslel bych si, že jeho otec byla brahmína.}
{175}{}{Víte, takové chování by mohl být problém. Co kdyby se ostatní služebníci začali chovat jako on?}
{176}{}{Co když ho koupím a zbavím vás ho? Přijímá Centrum... "sponzorské dary?"}
{177}{}{Ještě jednu otázku...}
{178}{}{Tak dobře. Sbohem.}
{179}{}{To je pravda. Musel jsem ho oddělit od ostatních... a zrovna včera měl jeden ze služebníků tu drzost zpochybňovat jeden z mých požadavků.}
{180}{}{Měl byste ho raději propustit, než bude pozdě.}
{181}{}{Joshua? Ano, máme tu takového služebníka. Právě byl přesunut do Nápravného zařízení. Proč vás to zajímá?}
{182}{}{Chci vyjednat jeho propuštění.}
{183}{}{Mám podezření, že je nakažen nakažlivou chorobou. Možná byste ho měl propustit dřív, než nakazí další služebníky.}
{184}{}{Jen tak. Chci se ještě zeptat...}
{185}{}{Tak dobře. Sbohem.}
{186}{}{Opravdu? A proč si myslíte, že bych ho měl propustit?}
{187}{}{Co byste řekl na velmi štědrý dar do provozního fondu Služebnického centra?}
{188}{}{Mám podezření, že je nakažen nakažlivou chorobou. Možná byste ho měl propustit dřív, než nakazí další služebníky.}
{189}{}{Jen tak. Chci se ještě zeptat...}
{190}{}{Tak dobře. Sbohem.}
{191}{}{Ne, měl jsem na mysli mnohem větší částku.}
{192}{}{Hmm. Dary jsou vskutku vítány k zajištění plynulého provozu Centra, ale bude třeba darovat něco opravdu hodnotného, abych vám mohl vydat Joshuu.}
{193}{}{Co takhle $1000?}
{194}{}{Co takhle $750?}
{195}{}{Co takhle $500?}
{196}{}{Co takhle $250?}
{197}{}{Popřemýšlím o tom. Chci se ještě zeptat...}
{198}{}{Aha. Možná se vrátím později.}
{199}{}{Aha. Vrátím se, až budu mít dost peněz na darování.}
{200}{}{No... není to zrovna dar, který bych si představoval, ale budiž. Dohlédnu na to, aby Joshuu dopravili k Soudu k dalšímu zpracování. Hned se do toho dám.}
{201}{}{Dobře.}
{202}{}{Hotovo. Joshua už není služebníkem ve Vault City a byl přesunut na Předměstí spolu se zbytkem venkovanů.}
{203}{}{Díky. Chci se ještě zeptat...}
{204}{}{Perfektní. Půjdu si ho tam vyzvednout.}
{205}{}{To zní dobře. Snad se nevrátí zpět do města.}
{206}{}{Vážně? Uvědomujete si, že každý služebník projde velmi důkladnou prohlídkou, než je zařazen do Centra?}
{207}{}{Možná se pletu. Nicméně i přesto chci vyjednat jeho propuštění.}
{208}{}{Říká vám něco syndrom }
{209}{}{? Neukáže se na většině lékařských přístrojů a jeho příznaky můžou být skryté i několik týdnů.}
{210}{}{V pustinách je nemoc zvaná syndrom }
{211}{}{. Možná jste zpozoroval sníženou výkonnost služebníků v poslední době. Tu celkovou nevrlost?}
{212}{}{To je naprostý nesmysl. Přestanete už mrhat mým časem svými lži...}
{213}{}{Tak dobře, zapomeňte na ten syndrom "}
{214}{}{." I přesto chci vyjednat propuštění Joshuy.}
{215}{}{No, nevadí. Chci se ještě zeptat...}
{216}{}{V tom případě odcházím. Sbohem.}
{217}{}{Infikovaný? Infikovaný čím?}
{218}{}{Příznaky? Jaké příznaky?}
{219}{}{Možná jste zpozoroval sníženou výkonnost služebníků v poslední době. Nebo nepozornost. Jejich neschopnost poslouchat rozkazy a správně je plnit. A to je teprve počáteční stádium.}
{220}{}{Eh...}
{221}{}{ syndrom. Má ho spousta lidí z vnějšího světa. Mezi symptomy patří i, ehm, mluvení bez vyzvání a používání sprostých slov.}
{222}{}{Hmmmm. To se nesmí stát, aby Občané hlásili problémy se služebníky... tak dobrá, ihned propustím Joshuu. Počkejte, musím udělat pár nezbytných opatření...}
{223}{}{Ano... v poslední době jsem si něčeho takového u služebníků všiml. Nakažlivé, říkáte? Hmmm. No, pokud je Joshua přenašeč, měl bych ho raději okamžitě propustit. Vydržte chvíli, jen provedu nějaké nezbytnosti...}
{224}{}{Žádný problém. Joshuovi bude stejně lépe s ostatními lidmi z vnějšího světa.}
{225}{}{Jistě, Kapitáne. Hned se o to postarám.}
{226}{}{Výborně, děkuji vám, Občane.}
{227}{}{Možná. Chcete nějaké prodat?}
{228}{}{Ano, mám tu jednoho. Prohlédněte si ho a nabídněte cenu.}
{229}{}{Ano, mám jich tu několik. Prohlédněte si je a nabídněte cenu.}
{230}{}{No, vlastně ne. Chci se ještě zeptat...}
{231}{}{No, dnes vlastně ne. Sbohem.}
{232}{}{Hmmm. Ta žena, Miria, že? Má silné paže... a pěkné boky. Koupím ji od vás za $250.}
{233}{}{Hmmm. Ten hoch, Davin, že? Vypadá celkem nezasažen kontaminací z venku. Koupím ho od vás za $200.}
{234}{}{Hmmm. Ten divoch, kterého máš. Silně... páchne. Ale vypadá zdravě. Vezmu ho za $100.}
{235}{}{Hmmm. Tamten chlapík... Vic, že? I když je dost starý, vypadá jako šikovný chlap. $100.}
{236}{}{Vraťte se, až budete mít služebníka, který za něco stojí. Vaše současná nabídka je... nezajímavá.}
{237}{}{No tak, ten otrok má větší cenu.}
{238}{}{To je dobrá cena. Služebník je váš.}
{239}{}{Toho vlastně ještě nechci prodat. Chci se ale na něco zeptat...}
{240}{}{Tohohle otroka vlastně ještě nechci prodat. Provedeme ten obchod jindy.}
{241}{}{Tak dobře. Chci se ještě na něco zeptat...}
{242}{}{Tak dobře. Zastavím se, až budu mít lepší nabídku.}
{243}{}{Ne, to určitě ne... 250 nebo nic.}
{244}{}{Ne, ten hoch vypadá, že půjde těžko zatrénovat... 200 nebo nic.}
{245}{}{Poslyšte, potrvá týden, než z toho divocha smyjeme ten zápach. 100 nebo nic.}
{246}{}{Vždyť mi ani nemůžete zaručit, že nedostane infarkt, až odejdete. Je starý. 100 nebo nic.}
{247}{}{Tak dobře, to zní fér. Služebník je váš.}
{248}{}{Tak na to zapomeňte. Chci se ale ještě na něco zeptat...}
{249}{}{Tak tedy nic. Nemůžu si dovolit propustit služebníka za takovou cenu. Možná někdy jindy.}
{250}{}{Hmmmm... vypadá jako zdravý kousek... možná bych tu pro ni našel nějakou práci. $500. A to je má konečná nabídka.}
{251}{}{Hmmmm. Je to zdravý jedinec. Dám vám za něj $400.}
{252}{}{Hmmmm. Tak dobře. $200. A už žádné smlouvání.}
{253}{}{Hmmmmmmm. $200. A ani o babku víc.}
{254}{}{To zní fér. Služebník je váš.}
{255}{}{Toho vlastně ještě nechci prodat. Chci se ale na něco zeptat...}
{256}{}{Tohohle otroka vlastně ještě nechci prodat. Provedeme ten obchod jindy.}
{257}{}{Výborně. Tady máte peníze. Nechám ji odeslat na lékařskou prohlídku a k začlenění. }
{258}{}{Výborně. Tady máte peníze. Nechám ho odeslat na lékařskou prohlídku a k začlenění. }
{259}{}{Výborně. Tady máte peníze. Nechám toho divocha odeslat na lékařskou prohlídku a k začlenění. }
{260}{}{Výborně. Tady máte peníze. Nechám toho starocha odeslat na lékařskou prohlídku a k začlenění. }
{261}{}{Vydrž chvíli, jen provedu nějaké nezbytnosti...}
{262}{}{Jistě. Počkám tady.}
{263}{}{Tak dobře. Váš služebník byl přemístěn k lékařské prohlídce a rekvalifikaci. Zvláštní... zdál se být velmi překvapený. Musel dostat pár uklidňujících střel, aby mohlo všechno hladce proběhnout. Všechno, co měl u sebe, jsem dal do krabice ve své kanceláři.}
{264}{}{No, služebníci zůstanou vždy služebníky. Chci se ještě zeptat...}
{265}{}{Opravdu? No, vím určitě, že bude časem mnohem poslušnější. Zajímají vás ještě nějací další společníci?}
{266}{}{Jo, bude to pro ně zpočátku těžké, ale oni si časem zvyknou. Hezký den.}
{267}{}{Co tady děláte? Poslal jsem vás do Vaultu! U všech čer... no dobře, řeknu někomu, ať vás tam dopraví zpátky.}
{268}{}{Dobřéééé.}
{269}{}{Podařilo se ti přesvědčit Barkuse, aby propustil Joshuu.}
{300}{}{Slyšel jsem, že je z vás hrdina. Dobrá práce.}
