{100}{}{Vidíš muže ve špinavém modrém svetru, který má mezeru mezi zuby. Je silně cítit brahmínami.}
{101}{}{Vidíš Eda, obchodníka s dobytkem.}
{102}{}{Zatracený brahmíny. Bučí tady, pak zas támhle...}
{103}{}{Přísahám, že jsem slyšel jednu z těch brahmín mluvit. Říkala "Bůů, povídám," nebo tak něco.}
{104}{}{Letos moc prodej brahmín nejde.}
{105}{}{Netuším, kde se všechny ty hovna z brahmín berou. Vždycky se někde objeví.}
{106}{}{Tož tě tady vítám, venkovane. Jsem Ed, místní obchodník s brahmínami. Potřebuješ s něčím pomoct?}
{107}{}{Rád tě zase vidím. Co pro tebe můžu udělat?}
{108}{}{Neznáš náhodou obchodníka jménem Vic? Říkal mi, že od tebe koupil tuhle láhev na vodu z Vaultu.}
{109}{}{Neznáš náhodou obchodníka jménem Vic?}
{110}{}{Tady můj přítel Vic říká, že od tebe koupil tuhle láhev na vodu.}
{111}{}{Nemáš tušení, kde jsi vzal tuhle láhev na vodu?}
{112}{}{Hledám Vault.}
{113}{}{Můžete mi říct něco o Vault City?}
{114}{}{Co tady děláš?}
{115}{}{Sbohem.}
{116}{}{Vic?}
{117}{}{On ti prodal láhev na vodu? A byla na ní "13"?}
{118}{}{Už nic. Musím už jít.}
{119}{}{Ty ji máš u sebe? Možná by mi mohla trochu osvěžit paměť.}
{120}{}{Zapomeň na to. Mám na tebe jiné otázky...}
{121}{}{Uvidím, jestli ji někde najdu. Ještě se vrátím.}
{122}{}{Ale jó... už si vzpomínám. Je to už hodně dávno co, Vicu. Tak láhev na vodu, jo? A co s ní?}
{123}{}{Ale jó... takovej tlustej chlápek, že jo? V takový kožený vestě? Plešatej? Pamatuju si ho. A co jako s ním?}
{124}{}{Můžeš mi říct, odkud ta láhev je?}
{125}{}{Říkal, že ti prodal láhev na vodu.}
{126}{}{Jenom zkouším, jestli jsi ho znal. Díky.}
{127}{}{Víš, nedokážu si to přesně vybavit... mám toho v tý svý makovici nakupenýho za ty léta hrozně moc. Myslím, že jsem ji našel při jednom ze svých brahmíních okruhů. Když jsem se pak usadil, nepotřeboval jsem ji.}
{128}{}{Brahmíních okruhů?}
{129}{}{Aha. Dobře, stejně děkuju.}
{130}{}{Když jsem byl mladší, míval jsem ve zvyku jezdit s brahmínama 'Velký okruh'... Broken Hills, New Reno, Redding, Den, Modoc, a zase zpátky sem. Po čase se to stávalo čím dál nebezpečnější a tak jsem se usadil tady.}
{131}{}{Kde jsou ty místa?}
{132}{}{Aha. No, díky za informace.}
{133}{}{Ukaž mi svoji mapu a já ti to tam načmárám. Dívej, Broken Hills leží jižně... a když se vydáš odtamtud kousek na západ, nemůžeš minout Reno. Severozápadně od Rena je Redding, na severu je pak Den, na východ od něj Modoc a o trochu dál na východ Vault City.}
{134}{}{Vzpomínáš si, na kterém z těch míst jsi tu láhev našel?}
{135}{}{Díky za informace.}
{136}{}{Promiň, ale na tohle ti nedokážu odpovědět. Je to už dávno. Proč to chceš vědět?}
{137}{}{Hledám Vault, ze kterého pochází tahle láhev.}
{138}{}{Díky za informace.}
{139}{}{No sakra, jestli hledáš Vault, tak za zdmi tohohle města jeden je.}
{140}{}{Vault 13 je uvnitř města?}
{141}{}{Díky za informace.}
{142}{}{Jo tak jestli je to zrovna "13", to fakt nevím, ale nějakej Vault tam je. A jestli to není ten, kterej hledáš, tak centrální počítač uvnitř určitě zná lokace dalších. Jsou v něm seznamy všeho možnýho.}
{143}{}{Chci se ještě zeptat...}
{144}{}{Díky za informace.}
{145}{}{Jasně. Co chceš vědět?}
{146}{}{Neznáš náhodou obchodníka jménem Vic? Říkal mi, že od tebe koupil tuhle láhev na vodu z Vaultu.}
{147}{}{Neznáš náhodou obchodníka jménem Vic?}
{148}{}{Tady můj přítel Vic říká, že od tebe koupil tuhle láhev na vodu.}
{149}{}{Nemáš tušení, kde jsi vzal tuhle láhev na vodu?}
{150}{}{Hledám Vault.}
{151}{}{Můžete mi říct něco o Vault City?}
{152}{}{Co tady děláš?}
{153}{}{Sbohem.}
{154}{}{Poslyš... uvnitř hlavní části města je Vault. Už to tam máš prohlídnutý? To by mohl bejt ten, kterej hledáš.}
{155}{}{Poslyš... uvnitř hlavní části města je Vault. Je to ten, kterej hledáš?}
{156}{}{Možná. Mám ještě nějaké otázky...}
{157}{}{To by mohlo být ono. Díky za informace.}
{158}{}{Fajn město... když umíš jednat s Občany. Sice ty jejich názory tak úplně neschvaluju, ale co... jinak se tu žije docela fajn.}
{159}{}{Chci se ještě zeptat...}
{160}{}{Aha. Díky za informace. Nashle.}
{161}{}{Prodávám brahmíny lidem, který je potřebujou. Pomáhá mi to zaplatit nájem za tenhle flek.}
{162}{}{Chci se ještě zeptat...}
{163}{}{Aha. Díky za informace. Nashle.}
{164}{}{I některý moje brahmíny jsou chytřejší než ty. Jdi si radši po svejch.}
{165}{}{Tohle vypadá jako Edův obchod. Od něj jsem koupil tu láhev na vodu.}
{166}{}{Podařilo se ti zjistit původ láhve na vodu.}
