{100}{}{Vidíš šéfknihovníka Kohla.}
{101}{}{Vidíš uhlazeně vyhlížejícího muže v kombinéze Vault City.}
{102}{}{Vidíš šéfknihovníka Kohla.}
{103}{}{Vidíš uhlazeně vyhlížejícího muže v kombinéze Vault City.}
{104}{}{Zařídím, aby vaše hrdinské činy byly zaznamenány v archívech Vault City, }
{105}{}{U všech knih! Vetřelec! Pomoc! Stráže!}
{106}{}{U všech knih! Mutant ve Vault City! Stráže! Stráže!}
{107}{}{U všech knih! Ghoul ve Vault City! Stráže! Stráže!}
{108}{}{Informační kancelář je večer zavřená. Přijďte ráno.}
{109}{}{Informační kancelář je večer zavřená. A až roztřídím všechny tyto listiny, půjdu domů.}
{110}{}{Psssst.}
{111}{}{Tiše, prosím.}
{112}{}{Psssst.}
{113}{}{V tichosti JE síla.}
{114}{}{Á... zdravím! S čím vám mohu pomoci?}
{115}{}{Frazz-urb-luuw!}
{116}{}{Odbelhat se.}
{117}{}{Co je tohle za místo?}
{118}{}{No nic. Promiň, že ruším.}
{119}{}{Eh... promiňte?}
{120}{}{Skřípy-skřípy vrz,}
{121}{}{Odbelhat se.}
{122}{}{Á, vy budete určitě služebník. Tak to se raději co NEJRYCHLEJI vraťte ke svému pánovi Barkusovi, jinak bude zuřit!}
{123}{}{Dóbže!}
{124}{}{Toto je Informační centrum Vault City. Je tohle to místo, které hledáte?}
{125}{}{Ano, konečně. Mám na vás několik otázek.}
{126}{}{Informační centrum? Máte nějaké knihy nebo manuály?}
{127}{}{Ani ne. Promiňte, že ruším.}
{128}{}{Bohužel jsou teď naše knihy právě převáděny do elektronické podoby. Ty, které byly navíc, se převezly do kanceláří Obchodního centra na druhém konci ulice. Zkuste to tam.}
{129}{}{A kde jsou ty knihy převedené do elektronické podoby?}
{130}{}{Všechny knihy jsou pryč?}
{131}{}{Aha. Chci se zeptat...}
{132}{}{Tak já se tam půjdu zeptat.}
{133}{}{Rád vás zase vidím. Potřebujete pomoct něco najít?}
{134}{}{Zajisté. Co potřebujete vědět?}
{135}{}{Co je tohle za místo?}
{136}{}{Nevíš, kde najdu GECK?}
{137}{}{Nevíte, kde se nachází Vault?}
{138}{}{Dnes nic, díky.}
{139}{}{GECK? To zní povědomě. Co to má být?}
{140}{}{Víte, to ani já přesně nevím. Podle slov naší Starší by to měl být nějaký všelék pro moji vesnici. Ale moc tomu nevěřím.}
{141}{}{To doopravdy nevím.}
{142}{}{Můžu se vás ještě na něco zeptat?}
{143}{}{Zapomeň na to. Možná si promluvíme někdy jindy.}
{144}{}{Vault? Vchod najdete, když půjdete doleva po ulici... je to ta obrovská díra ve skále.}
{145}{}{Znáte ještě nějaké jiné Vaulty?}
{146}{}{Můžu se vás ještě na něco zeptat?}
{147}{}{Díky za radu.}
{148}{}{Jiné Vaulty? Hmmm. Ne, neznám. Vím, že byly postaveny i jiné Vaulty, ale nikdy jsme žádný jiný nenašli. Možná bude nějaká zmínka v centrálním počítači našeho Vaultu.}
{149}{}{Jak se dostanu do Vaultu?}
{150}{}{Můžu se vás ještě na něco zeptat?}
{151}{}{Díky za informace.}
{152}{}{Hmmmm. No, víte, taková informace by se mohla nacházet v centrálním počítači uvnitř našeho Vaultu. Je tam uloženo mnoho starých archívů.}
{153}{}{Jak se dostanu do Vaultu?}
{154}{}{Můžu se vás ještě na něco zeptat?}
{155}{}{Díky za informace.}
{156}{}{No, pokud jste Občanem této komunity, můžete vstoupit do Vaultu.}
{157}{}{Aha, vy jste Občan? Omlouvám se, moc se omlouvám... no, v tom případě můžete vstoupit do Vaultu a použít centrální počítač.}
{158}{}{Nejprve se musíte stát Občanem Vault City. Jestli chcete, můžete podstoupit test Občanství... nebo bude možná lepší, když si promluvíte s První Občankou Lynette. Jsem si jist, že by mohla ve vašem případě udělat výjimku.}
{159}{}{Eh, ale já jsem Občan.}
{160}{}{Můžu se vás ještě na něco zeptat?}
{161}{}{Díky za informace.}
{162}{}{Ano, všechno se překládá, protože... hmmm. Je to trochu delikátní záležitost, ale myslím, že je moje funkce ve Vault City již zastaralá.}
{163}{}{Zastaralá? Co tím myslíte?}
{164}{}{Zastaralá?}
{165}{}{Aha. Chci se ještě na něco zeptat...}
{166}{}{To je mi líto. Musím už jít.}
{167}{}{To znamená, že je moje funkce již zbytečná. Asi to tak bude lepší.}
{168}{}{Plánuje se instalace informačních terminálů do každé domácnosti. Všechny tyto terminály budou napojeny do sítě s vyhledávacím a informačním serverem. Až to bude hotové, tak Informační centrum... a já... budeme zbyteční. Asi to tak bude lepší.}
{169}{}{Jsi si jistá?}
{170}{}{Aha. Chci se ještě na něco zeptat...}
{171}{}{To je mi líto. Musím už jít.}
{172}{}{Ó ano. První Občanka se v takových věcech málokdy mýlí. I přesto mi bude po tomto místě smutno. Slyšel jsem, že pro mě mají místo v Úřadě seznamů.}
{173}{}{Aha. No, je mi líto, že se všechny knihy přepisují. Raději si přečtu poctivou papírovou knihu, než civět do monitoru.}
{174}{}{Aha. No, je mi líto, že se všechny knihy přepisují. Raději si přečtu poctivou papírovou knihu, než civět do monitoru.}
{175}{}{Aha. Chci se ještě na něco zeptat...}
{176}{}{To je mi líto. Musím už jít.}
{177}{}{Mluvíte mi úplně z duše! Nemám nic proti elektronickému formátu, ale není nad to si knihu... osahat... vlastníma rukama a obracet jednu stránku za druhou. Hmmm. Víte...}
{178}{}{Ano?}
{179}{}{Aha. Chci se ještě na něco zeptat...}
{180}{}{To je mi líto. Musím už jít.}
{181}{}{Všechny knihy do Obchodního centra nepřevezli. Vím, že Randalovi nebudou chybět, pokud je dám někomu, kdo je opravdu využije... někomu, jako jste vy.}
{182}{}{S radostí si je vezmu. Díky.}
{183}{}{Dojdu pro ně...}
{184}{}{Tak dobře.}
{185}{}{Tady jsou. Snad se vám budou líbit. Jsou to některé z mých nejoblíbenějších... trochu technické, ale přesto dobré.}
{186}{}{Díky. Nebude vám vadit, když se ještě na něco zeptám?}
{187}{}{Skvělé. Jdu si je přečíst.}
{188}{}{Byly přepsány do jednoho z knihovních počítačů ve třetím podlaží Vaultu. Nemohu si vzpomenout, do kterého... ale určitě to není jeden z těch u centrálního počítače.}
{189}{}{Proč se všechno přepisuje?}
{190}{}{Jak se dostanu do Vaultu?}
{191}{}{Aha. Nebude vám vadit, když se ještě na něco zeptám?}
{192}{}{Asi se po něm půjdu podívat.}
{193}{}{! Výborně! Bravo!}
