{100}{}{Vidíš dobøe vypadající stráž. Na sobì má kovovou zbroj a v rukou útoènou pušku.}
{101}{}{Vidíš stráž Vault City.}
{102}{}{Ano? Co chceš?}
{103}{}{Já jít do velká DÍRA v kopec.}
{104}{}{Chci vstoupit do Vaultu.}
{105}{}{Nic, promiò, že ruším.}
{106}{}{Je po šesté veèer. Musíš odejít.}
{107}{}{Dobrá. Už jdu.}
{108}{}{Dobøe. Dej mi ještì chvíli.}
{109}{}{Musím ještì nìco udìlat. Pùjdu, až to dokonèím.}
{110}{}{Bubu baba!?! BUBU BABA!}
{111}{}{Poèkej, zavolám stráže, aby tì vyprovodili ven.}
{112}{}{Dobrá. Tak jdeme.}
{113}{}{Bongo Dongo.}
{114}{}{Není tøeba. Pùjdu i bez nich.}
{115}{}{Promiò, ale takové jsou moje rozkazy.}
{116}{}{Dobøe... ale radost z toho nemám. Možná si budu stìžovat na vyšších místech...}
{117}{}{No, já ale zùstávám.}
{118}{}{Nechci použít násilí, ale když budu muset, tak ho použiju. Nedìlej to ještì horší, než to je.}
{119}{}{Dobøe, fajn, fajn... pùjdu.}
{120}{}{Dotkni se mì a budeš nosit koule za kloboukem.}
{121}{}{Zdravím, Obèane. Mùžu ti nìjak pomoct?}
{122}{}{Chci vstoupit do Vaultu.}
{123}{}{Já jít do velká DÍRA v kopec.}
{124}{}{Momentálnì ne.}
{125}{}{Je mi líto, ale pouze Obèané mùžou vstoupit do Vaultu. Doufám, že to chápeš.}
{126}{}{Vstoupit mùžou pouze Obèané. Teï odejdi.}
{127}{}{Dobøe.}
{128}{}{Umgh.}
{129}{}{Jistì. Pokraèuj prosím.}
{130}{}{Dìkuju!}
{131}{}{Díky.}
{132}{}{Ano? Mùžu ti nìjak pomoct?}
{133}{}{Chci vstoupit do Vaultu.}
{134}{}{Nic, promiò, že ruším.}
{135}{}{Je mi líto, ale pouze Obèané mùžou vstoupit do Vaultu.}
{136}{}{Já *jsem* Obèan.}
{137}{}{Omlouvám se... nepoznávám tì. Mám rozkaz nechat vstoupit do Vaultu pouze Obèany, které znám. Snad by ti mohla pomoct První Obèanka Lynette. Hezký den.}
{138}{}{Zdravím, Kapitáne. Mùžu vám nìjak pomoct?}
{139}{}{Aha, dobøe.}
{140}{}{Aha, dobøe. Jen se tak dívám.}
{141}{}{Umgh.}
{142}{}{Jo, to je fuk, Mungoth. Øekni to mé ruce.}
{143}{}{Hej ty! Co dìlá ten ghoul ve Vault City?!}
{144}{}{Hej ty! Co dìlá ten mutant ve Vault City?!}
{145}{}{Eeech-èup kiki kiki.}
{146}{}{Ghoul? Kde?}
{147}{}{Mutant? Kde?}
{148}{}{Je tu se mnou.}
{149}{}{Cestuje se mnou. A jestli s tím má nìkdo z vás rasistù problém, tak ho mùžeme vyøešit hned teï.}
{150}{}{Pokud je ta pøíšera s tebou, pak oba patøíte zpátky na Pøedmìstí, ne do ulic Vault City.}
{151}{}{Tak dobøe, pùjdeme bez protestu.}
{152}{}{Mùžeš nás odsud zkusit vyprovodit, ale zaruèuju ti, že to bude zatracenì tvrdá zkušenost.}
{153}{}{Jak se ti venkovani dostali až sem...?}
{154}{}{Támhleta pøíšera.}
{155}{}{Oba patøíte zpátky na Pøedmìstí, ne do ulic Vault City.}
{156}{}{JÁ NECHTÍT BÝT TVÙJ KÁMOŠ! TY NE MÙJ KÁMOŠ!}
{157}{}{My jít my jít potichùùù.}
{158}{}{Tak dobøe, pùjdeme bez protestu.}
{159}{}{Cestuje se mnou. A jestli s tím má nìkdo z vás rasistù problém, tak ho mùžeme vyøešit hned teï.}
{160}{}{Stráže! Vetøelci ve mìstì!}
{161}{}{Hrnghhhhhhhh!}
{162}{}{Zemøeš døív, než se ti tvoji pøátelé vùbec objeví.}
{163}{}{Hej! Ty jsi ten, co porazil Enklávu!}
{164}{}{Podívejte, to je ten, co porazil Enklávu!}
{165}{}{Vítej ve Vault City.}
{166}{}{Vaše bitva proti enklávì zapùsobila i na První Obèanku.}
{167}{}{Slyšel jsem, že tvoje cesty vedly až na jih do San Francisca. Je to pravda?}
{168}{}{Je to pravda? Opravdu vláda starého svìta vedla poøád válku?}
{169}{}{Bylo by dobré zaznamenat své cesty do hlavního poèítaèe Vault City.}
{170}{}{Mùžeš tu zùstat, jak dlouho chceš, hrdino.}
{171}{}{Mìl bys sepsat seznam svých hrdinských èinù proti Enklávì a nahrát je na rozesílací server.}
{172}{}{Kapitáne.}
{173}{}{Vault City vždy zvítìzí, Kapitáne.}
{174}{}{Zdravím, Kapitáne.}
{175}{}{Vault City vždy zvítìzí, Obèane.}
{176}{}{Obèane.}
{177}{}{Zdravím, Obèane.}
