{100}{}{Poèítaèovı terminál zobrazující nejrùznìjší data.}
{101}{}{Vidíš terminál. }
{102}{}{Poèítaèovı terminál zobrazující nejrùznìjší data.}
{103}{}{Vidíš øídící poèítaè Vault City.}
{104}{}{Vidíš terminál.}
{105}{}{Vidíš øídící poèítaè Vault City.}
{106}{}{Poèítaè, kterı si pøímo øíká o pøipojení Pip-Boye.}
{107}{}{Nic se nestalo.}
{108}{}{S pomocí informací ve svém Pip-Boyi zpøístupòuješ poèítaè.}
{109}{}{Páni.}
{110}{}{Získáváš TUNY novıch informací o Falloutu 2.}
