{100}{}{Počítačový terminál.}
{101}{}{Vypadá přesně jako bezpečnostní terminál.}
{102}{}{Obrazovka je pro tebe zcela nečitelná.}
{103}{}{Skynet - Bezpečnostní systémy                                    Přístup odepřen}
{104}{}{}
{105}{}{Konec.}
{106}{}{Chyba!                                                                 Program nenalezen                                              Prosím, restartujte}
{107}{}{}
{108}{}{}
{109}{}{Konec.}
{200}{}{ nedokáže přečíst text na monitoru.}
{300}{}{Vypadá to, že je v počítači nějaký obranný mechanismus.}
