{100}{}{Poèítaèovı terminál.}
{101}{}{Na rùznıch místech poèítaèe jsou nalepeny obrázky spoøe odìnıch dívek.}
{102}{}{Obrazovka je pro tebe zcela neèitelná.}
{103}{}{Zbrojní pøístupovı terminál                                        Silová pole - Vypnuta                                           Elektrická podlaha - Vypnuta}
{104}{}{Zbrojní pøístupovı terminál                                        Silová pole - Vypnuta                                           Elektrická podlaha - Zapnuta}
{105}{}{Zbrojní pøístupovı terminál                                        Silová pole - Zapnuta                                           Elektrická podlaha - Vypnuta}
{106}{}{Zbrojní pøístupovı terminál                                        Silová pole - Zapnuta                                           Elektrická podlaha - Zapnuta}
{107}{}{Vypnout elektrickou podlahu.}
{108}{}{Vypnout silová pole.}
{109}{}{Èíst poštu.}
{110}{}{Konec.}
{111}{}{(A se snaíš sebevíc, tyhle zakroucené èáry ti nedávají praádnı smysl.)}
{112}{}{Vypnout elektrickou podlahu                                        Prosím zadejte heslo:}
{113}{}{Hacknout se do systému.}
{114}{}{Hádat heslo.}
{115}{}{Zpìt do hlavního menu.}
{116}{}{Konec.}
{117}{}{(Tento program je na tebe pøíliš sloitı.)}
{118}{}{Zpìt do hlavního menu.}
{119}{}{Konec.}
{120}{}{(Podaøilo se ti obejít pøístupové heslo a deaktivovat elektrickou podlahu.)}
{121}{}{Zpìt do hlavního menu.}
{122}{}{Konec.}
{123}{}{Vypnout silová pole                                             Prosím zadejte heslo:}
{124}{}{Hacknout se do systému.}
{125}{}{Hádat heslo.}
{126}{}{Zpìt do hlavního menu.}
{127}{}{Konec.}
{128}{}{(Soubory jsou zašifrovány a bez dekodéru je nedokáeš pøeèíst.)}
{129}{}{Zpìt do hlavního menu.}
{130}{}{Konec.}
{131}{}{(Tak tohle byla celkem hraèka... silová pole jsou nyní vypnuta.)}
{132}{}{Zpìt do hlavního menu.}
{133}{}{Konec.}
{134}{}{(Nìkdo zapomnìl zavøít svùj mailbox.)                     Potvrzení objednávky                                              Pokyny k evakuaci                                                   Pøátelskı pozdrav                                                   Obchodní mail}
{135}{}{[Vybrat soubor k pøeètení]}
{136}{}{Èíst Potvrzení objednávky.}
{137}{}{èíst Pokyny k evakuaci.}
{138}{}{Èíst Pøátelskı pozdrav.}
{139}{}{Èíst Obchodní mail.}
{140}{}{Zpìt do hlavního menu.}
{141}{}{Konec.}
{142}{}{Tato zpráva potvrzuje vaši objednávku videa "Debbie pracuje v armádì a polyká - díl 1059". Titul by vám mìl bıt doruèen poštou do dvou tıdnù. Dìkujeme, e jste vyuili našich slueb.}
{143}{}{Èíst další mail.}
{144}{}{Konec.}
{145}{}{Evakuace Armádního skladu Sierra byla posunuta o jeden tıden dopøedu. Všechna bezpeènostní naøízení musí bıt splnìna do tohoto data. To vše na pøíkaz Generála Cliftona.}
{146}{}{Èíst další mail.}
{147}{}{Konec.}
{148}{}{(Uslyšíš zvuk jiskøení nìkde z útrob terminálu. Zaèíná se z nìj kouøit... s mírnım odstupem sleduješ, jak se z klávesnice stává cosi tekutého. Hmm... to musí bıt jeden z tìch virù, o kterém se všichni zmiòují.)}
{149}{}{Konec.}
{150}{}{Tady Klinger z 8063. NUTNÌ potøebujeme souèástku ev. èíslo 102-53B. Mám tady bedınku Chateau Lafayette, roèník 2155, pokud by se ti to podaøilo nìjak popohnat. Díky a ozvi se!}
{151}{}{Èíst další mail.}
{152}{}{Konec.}
{153}{}{(Máš neuvìøitelné štìstí! Podaøilo se ti uhádnout heslo "Dudy".)
                                                               Deaktivuji elektrickou podlahu}
{154}{}{Zpìt do hlavního menu.}
{155}{}{Konec.}
{156}{}{(Je úplnì jedno, jak dlouho se budeš snait... to heslo stejnì neuhádneš.)}
{157}{}{Zpìt do hlavního menu.}
{158}{}{Konec.}
{159}{}{(Ten, kdo tu vymıšlel hesla, musel bıt blázen do poprsí. Správné heslo je "Bradavky".)                                   Deaktivuji silová pole}
{160}{}{Zpìt do hlavního menu.}
{161}{}{Konec.}
{162}{}{(Je úplnì jedno, jak dlouho se budeš snait... to heslo stejnì neuhádneš.)}
{163}{}{Zpìt do hlavního menu.}
{164}{}{Konec.}
{165}{}{(Tvoje neodborné hrátky zpùsobily, e ti terminál explodoval pøímo do tváøe.)}
{166}{}{Konec.}
{200}{}{Tento terminál je nefunkèní.}
{300}{}{Vypínáš energetické pláty.}
{400}{}{Poèítaè je v diagnostickém reimu. Prosím vyèkejte, dokud proces neskonèí.}
