# lockpick
# dude
{100}{}{Úspìšnì odemykáš zámek.}
{101}{}{Nezdaøilo se. Zámek je stále zamèený.}
{102}{}{Úspìšnì zamykáš zámek.}
{103}{}{Nepodaøilo se ti zamknout zámek.}
# other critter
{200}{}{ odemyká zámek.}
{201}{}{ byl úspìšný pøi odemykání zámku.}
{202}{}{ zamyká zámek.}
{203}{}{ byl úspìšný pøi zamykání zámku.}

# explosion
{300}{}{Exploze znièila zámek.}
{301}{}{Ani exploze nepomohla odstranit zámek.}

# pry
# dude
{400}{}{Podaøilo se ti vypáèit zámek.}
{401}{}{Nepodaøilo se ti vypáèit zámek.}
# other critter
{500}{}{ byl úspìšný pøi páèení zámku.}
{501}{}{ nebyl úspìšný pøi páèení zámku.}