{100}{}{Tu vois Frère John.}
{101}{}{Tu vois un vieux moine de l'Abbaye.}
{102}{}{C'est un vieux moine. Il doit avoir dans les soixante-dix ans.}
{300}{}{Salut gamin.}
{301}{}{Qui es-tu ?}
{302}{}{Avez-vous-entendu parler du J.E.K ou de l'abri 13 ?}
{303}{}{Salut.}
{400}{}{Je suis John, l'un des plus vieux moines de l'Abbaye.}
{401}{}{Que faites-vous exactement ?}
{402}{}{Je vois, au revoir.}
{403}{}{Hé bien, autrefois je travaillais à la ferme, mais ce n'était pas très bon pour mon coeur.}
{404}{}{Vous avez des problèmes cardiaques ?}
{405}{}{Pas de chance, au revoir !}
{406}{}{Oui, j'ai un coeur fragile. Si seulement j'avais mes pilules, elles me soulageraient tellement la vie. De nos jours, il est difficile de se procurer des traitements pour ce genre de problèmes.}
{407}{}{J'ai peut-être une solution pour vos problèmes de coeur...}
{408}{}{Navré de l'entendre, au revoir.}
{410}{}{Salut.}
{411}{}{Vraiment ? T'es en train de me dire que tu AS des pilules pour le coeur ?}
{412}{}{Oui, il se trouve que j'en ai. Je vous les donne avec plaisir.}
{413}{}{Ouais j'ai vos pilules magiques. Vous pouvez les avoir pour $400.}
{414}{}{Je plaisantais. Je n'ai aucune pilule sur moi.}
{415}{}{[Il te prend les pilules.] Oh merci l'ami ! Tiens, prends cet objet en guise de ma gratitude.}
{416}{}{Heureux de vous avoir aidé, et merci pour l'objet. Au revoir !}
{417}{}{[Il semble fou de rage, mais se calme rapidement.] Très bien, voilà ton fric. Maintenant, donne-moi les pilules !}
{418}{}{J'ai finalement décidé de garder ces pilules. Merci pour l'argent !}
{419}{}{Heureux de faire affaire avec vous, au revoir.}
{420}{}{Hmmm, désolé j'en sais rien. Parle à notre supérieur, il sait peut-être quelque chose.}
{421}{}{C'est ce que je vais faire merci. Maintenant j'ai quelque chose d'autre à vous demander.}
{422}{}{Si j'étais pas si malade, je t'aurais botté le cul enfoiré ! MAINTENANT SORS D'ICI !}
{423}{}{Très bien, je vais y aller.}
{500}{}{Merci encore pour les pilules l'ami. Bonne chance dans tes voyages.}
{600}{}{Pars, s'il te plaît.}
{700}{}{Tu as montré à John à quel point le monde est cruel.}
