{100}{}{Tu vois Lucas.}
{101}{}{Lucas est le chef guerrier de ta tribu.}
{102}{}{Alors te voilà, Etre Elu ? Hum ! Comment se déroule ta quête ?}
{103}{}{Assez bien.}
{104}{}{Pas très bien.}
{105}{}{Hein ?!!}
{106}{}{Je dois m'y remettre.}
{107}{}{Tu as peut-être besoin de l'aide d'un guerrier.}
{108}{}{Certainement. Comment peux-tu m'aider ?}
{109}{}{Non. Je me débrouille très bien.}
{110}{}{Alors tais-toi pendant que je m'entraîne.}
{111}{}{Euh... Ok.}
{112}{}{Je sais me battre avec mes poings et mes pieds. Tu crois que tu peux apprendre ça ?}
{113}{}{Que peux-tu m'apprendre ?}
{114}{}{Que le vent te pousse, Etre Elu.}
{115}{}{Salut.}
{116}{}{Hum, passe une journée avec moi et je t'apprendrai à frapper plus fort.}
{117}{}{Très bien, allons-y.}
{118}{}{Je regrette mais je n'ai pas le temps pour le moment.}
{119}{}{Tu connais déjà tout ce que je peux t'enseigner. Bonne chance pour ta quête.}
{120}{}{Oh, d'accord.}
{121}{}{Etre Elu, tu manques d'élégance pour que je t'enseigne quoi que ce soit.}
{122}{}{Oh, d'accord.}
{123}{}{Tu n'es pas assez rapide au combat pour que mon entraînement puisse t'aider, Etre Elu.}
{124}{}{Oh, d'accord.}
{125}{}{Tu dois en apprendre plus sur le combat avant que je puisse t'aider.}
{126}{}{Oh, d'accord.}
{127}{}{Je peux t'apprendre un coup de pied plus puissant. Ca va nous prendre toute une journée.}
{128}{}{Ok.}
{129}{}{Je peux t'apprendre à mieux te battre. Ca va nous prendre toute une journée.}
{130}{}{Ok.}
{131}{}{Tu as bien appris, Etre Elu. Que le vent te pousse dans ta quête.}
{132}{}{Merci pour ton aide.}
{133}{}{Je t'ai enseigné tout ce que je pouvais, Etre Elu. Bonne chance pour ta quête.}
