{100}{}{Tu vois un villageois.}
{101}{}{Tu vois une villageoise.}
{150}{}{Un gentil membre de ton village.}
{151}{}{[PARLER]}
{152}{}{Bonjour ! J'ai entendu dire que tu es l'Etre Elu. Maintenant, notre village va peut-être pouvoir être sauvé.}
{153}{}{Peux-tu me dire où trouver plus de poudre de guérison ?}
{154}{}{Que peux-tu me dire des marchands qui traitent avec nous ?}
{155}{}{Ca fait plaisir de te voir, mais je dois partir.}
{156}{}{Que les dieux te protègent au cours de ton voyage !}
{157}{}{J'ai une question à te poser.}
{158}{}{Au revoir.}
{159}{}{Va voir Hakunin au Nord du village. Il peut t'aider.}
{160}{}{Merci. Au revoir.}
{161}{}{Oh, moi je ne traite pas avec les marchands. Parle à Mynoc, le gardien du grand pont. Il les voit tous.}
{162}{}{Merci. Au revoir.}
{163}{}{Peux-tu me dire où se trouve le grand pont ?}
{164}{}{Encore une question, si je puis me permettre.}
{165}{}{La bonne blague, l'Etre Elu ! Tu sais bien où il se trouve. Par là, vers le Sud.}
{166}{}{Merci. Au revoir.}
{167}{}{Encore une question, si je puis me permettre.}
{168}{}{Bien sûr, de quoi s'agit-il ?}
{169}{}{Où puis-je trouver des herbes médicinales ?}
{170}{}{Que peux-tu me dire des marchands qui traitent avec nous ?}
{171}{}{Ca ne fait rien.}
{172}{}{Grands Dieux. Puisse l'esprit du Fondateur te guider. Si tu es l'Etre Elu, nous allons en avoir besoin.}
{173}{}{Ounga.}
{174}{}{Bon voyage.}
{175}{}{????}
{176}{}{Nous sommes condamnés ! Ta quête a échoué.}
{177}{}{Tu ne peux pas continuer comme ça.}
{180}{}{Tu as trahi ton propre peuple.}
{181}{}{Pourquoi fais-tu cela ?}
{182}{}{Tu es démoniaque. L'Etre Elu est démoniaque !}
{183}{}{Ils viennent au village de l'Est... mais leurs marchandises sont de mauvaise qualité.}
{184}{}{Où puis-je trouver des herbes médicinales ?}
{185}{}{Merci. Au revoir.}
{186}{}{Encore une question, si je puis me permettre.}
{300}{}{Bonjour, Etre Elu. Quel plaisir de te revoir ! Je prie pour que ta quête aboutisse. Puis-je faire quelque chose pour toi ?}
{301}{}{Etre Elu, notre peuple se meurt. Tu dois te dépêcher de trouver le saint J.E.K. Que puis-je faire pour t'aider dans cette sainte quête ?}
{302}{}{Le temps nous est compté, Etre Elu. Dépêche-toi de terminer ta quête. Nous ne pouvons pas nous permettre d'attendre plus longtemps. Si je peux faire quelque chose t'aider à nous sauver, dis-le-moi.}
{303}{}{Etre Elu, notre village est presque mort... Tu es notre seul espoir. Y a-t-il quelque chose que je puisse te dire pour t'aider à nous sauver ?}
{400}{}{Y-a-t-il quoi que se soit que tu puisses me dire sur Kaga ?}
{401}{}{[Le villageois te regarde fixement, les yeux grands ouverts, puis il s'éloigne doucement de toi tout en jetant nerveusement des coups d'oeil autour de lui.]}
{402}{}{Ok, je suppose que ça veut dire *non*.}
{1000}{}{La doyenne}
{1001}{}{Fondatrice}
{1002}{}{Habitant de l'Abri }
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Abri}
{1006}{}{Elu}
{1007}{}{Chaman}
{1008}{}{Hakunin}
{1009}{}{Poudre médicinale}
{1010}{}{Pont}
{1011}{}{Mynoc}
{1100}{}{La doyenne est à la fois ta mère et ton chef.}
{1101}{}{Notre illustre ancêtre qui nous a légué le savoir.}
{1102}{}{La première à avoir combattu et vaincu le chaos. }
{1103}{}{Voilà ce que serait notre beau village.}
{1104}{}{Notre poste d'approvisionnement est à quelques jours à l'Est d'ici.}
{1105}{}{L'Abri, c'est le paradis.}
{1106}{}{Tu es l'Elu.}
{1107}{}{Il nous guérit avec ses herbes et sa magie. Il habite dans la partie Nord du village.}
{1108}{}{Il nous guérit avec ses herbes et sa magie. Il habite dans la partie Nord du village.}
{1109}{}{Avec cette poudre magique, tu vas guérir, mais cela te fera somnoler.}
{1110}{}{Le grand pont est à la sortie de notre village au Sud.}
{1111}{}{Il garde le pont par lequel on pénètre dans notre village.}
