{100}{}{Tu vois un moine.}
{101}{}{Ce moine ressemble à un commerçant.}
{200}{}{Bienvenue voyageur.}
{201}{}{Paix à toi.}
{202}{}{Beau temps.}
{203}{}{Va jouer ailleurs.}
{300}{}{Salut, comment puis je t'aider ?}
{301}{}{Que peux-tu me dire au sujet de ton ordre ?}
{302}{}{Faisons affaire.}
{303}{}{Salut.}
{400}{}{Notre sainte mission est de lire, copier et prendre soin de nos bibles de la connaissance. Nous aimons partager nos connaissances avec n'importe qui aussi longtemps qu'ils n'endommagent rien.}
{401}{}{Qui est ton meneur ?}
{402}{}{Quel genre de connaissance ?}
{403}{}{Il peut être trouvé au troisième étage. Si tu souhaites en apprendre plus au sujet de notre ordre, il est celui à qui parler.}
{404}{}{Sous la forme de livres. Tant d'informations peuvent être obtenues de ces textes. C'est notre mission que de les préserver pour les générations futures.}
{405}{}{Ok.}
{406}{}{Ok.}
{500}{}{Arrête ça! }
