{100}{}{Tu vois un squatteur.}
{101}{}{Tu vois Bill, le squatteur.}
{102}{}{Tu vois un homme d'âge moyen portant des vêtements usés.}
{103}{}{Je regrette mais je n'ai pas le temps de discuter avec toi.}
{104}{}{Hé, j'ai dit que j'avais pas le temps de parler. Allez, va-t'en.}
{105}{}{Merci d'avoir aidé Elisabeth. Tu as fait quelque chose de bien.}
{106}{}{Laisse-moi, je ne te veux aucun mal.}
{107}{}{Très bien, très bien, j'me pousse.}
