{100}{}{Tu vois Monsieur Tricheur.}
{101}{}{Il ressemble bel hé bien à un tricheur.}
{200}{}{Bonjour, je suis Monsieur Tricheur. Que puis-je faire pour toi ?}
{201}{}{Tu peux kidnapper ma Tribu ?}
{202}{}{Tu peux me mettre sur l'affaire des Shis ?}
{203}{}{Tu peux me mettre sur l'affaire d'Elron ?}
{204}{}{Tu peux me mettre sur l'affaire de la Confrérie ?}
{205}{}{Fais en sorte que je sois déjà allé à la base militaire.}
{206}{}{J'ai kidnappé ta Tribu.}
{207}{}{Je t'ai mis sur l'affaire des Shis.}
{208}{}{Je t'ai mis sur l'affaire d'Elron.}
{209}{}{Je t'ai mis sur l'affaire de la confrérie.}
{210}{}{C'est fait, maintenant tu es déjà allé dans la base militaire.}
{211}{}{Merci, Monsieur Tricheur.}
