{100}{}{Tu vois une homme qui brille de partout.}
{101}{}{Un soldat en super-armure.}
{102}{}{Un soldat doté d'une sorte de SuperArmure.}
{103}{}{C'est pas vrai ! Je suis encore de corvée de patates !}
{104}{}{On dit que le vieux va aller à SF !}
{105}{}{J'en ai marre d'attendre. Je dis que nous allons exterminer tous ces primitifs, et pas de quartier !}
{106}{}{T'as du feu ? Oh attends, laisse tomber. J'en ai.}
{107}{}{Jeu de dés ce soir derrière le hangar. Ne le dis pas au patron !}
{108}{}{Qui va là ? <Zzzt> Un intrus ici !}
{109}{}{Toi là-bas ! Stop !}
{110}{}{Un intrus dans la base !}
{111}{}{Attends... Euh, laisse tomber.}
{112}{}{Ecoute, tu devrais avoir tes papiers. Ces fausses alertes font sursauter tout le monde.}
{113}{}{Bon Dieu que ces fausses alertes m'énervent !}
{114}{}{Des intrus par ici ! Attrapez-les !}
{115}{}{Voilà l'intrus !}
{116}{}{Par ici ! Ne les laissez pas s'échapper !}
{117}{}{On nous attaque sur le front ! Envoyez-nous des renforts !!}
{118}{}{Ne laissez pas l'intrus s'échapper !}
{119}{}{Meurs, primitif !}
