{100}{}{Tu ouvres l'armoire et découvres des rangées de dossiers et des piles de notes.}
{101}{}{Fouiller l'armoire.}
{102}{}{[Quitter]}
{103}{}{En examinant les enregistrements, tu découvres une fine mallette en cuir, bien dissimulée au fond de l'armoire.}
{104}{}{Sortir la mallette.}
{105}{}{Ignorer la mallette, et continuer à fouiller.}
{106}{}{Tu passes 30 minutes à chercher sans trouver quoi que ce soit d'important. Tu apprends seulement que Chad a enregistré chaque instant de sa vie. C'est un mec plutôt ennuyeux à vrai dire. Tu es sur le point de fermer l'armoire quand tu entends quelqu'un tousser devant la porte d'entrée, la poignée tourne...}
{107}{}{Sortir la mallette.}
