# Player uses a skill on the door
# Unlock Door
{170}{}{Tu crochètes adroitement la serrure du placard.}
{171}{}{A cause de ton manque d'adresse, tu coinces la serrure de ce placard.}
{172}{}{Tu ne réussis pas à crocheter la serrure de ce placard.}

# Unlock Door
{173}{}{ crochète adroitement la serrure du placard.}
{174}{}{ a manqué d'adresse et coince la serrure du placard.}
{175}{}{ n'a pas réussi à crocheter la serrure du placard.}

# Player uses an item on the door
{176}{}{Tu fais sauter la serrure de la porte.}
{177}{}{Tu te fais un tour de reins en essayant de faire sauter la serrure et tu subis un point de dégâts.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Tu te fais un tour de reins en essayer de faire sauter la serrure et tu subis }
{179}{}{ points de dégâts.}
{180}{}{Tu es trop faible pour faire sauter la serrure.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ fait sauter la serrure de la porte.}
{182}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit un point de dégâts.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit }
{184}{}{ points de dégâts.}

{185}{}{ est trop faible pour faire sauter la serrure.}
{186}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit un point de dégâts.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ se fait un tour de reins en essayant de faire sauter la serrure et subit }
{188}{}{ points de dégâts.}

# Lock Door
{189}{}{Tu verrouilles adroitement le placard.}
{190}{}{Tu ne réussis pas à verrouiller le placard.}

# Lock Door
{191}{}{ verrouille adroitement le placard.}
{192}{}{ ne réussit pas à verrouiller le placard.}

{203}{}{Le placard est verrouillé.}

{800}{}{Tu as récupéré le passe.}
{810}{}{Tu as récupéré les plans.}
{820}{}{Tu as récupéré le motivateur du K-9.}
