{100}{}{Tu vois un fantôme !}
{101}{}{Tu vois le fantôme d'Anna.}
{150}{}{C'est un fantôme. On n'en voit pas tous les jours.}
{151}{}{Elle a l'air très tourmentée.}
{152}{}{[PARLER]}
{153}{}{Oh, quelle douleur ! Ca brûle !}
{154}{}{Quel est le problème ?}
{155}{}{Qui es-tu ?}
{156}{}{Va-t'en, esprit maléfique !}
{157}{}{Je m'arrête et je frappe à toutes les portes. Mais personne ne vient. Personne ne m'entend.}
{158}{}{Je t'entends moi. Que se passe-t-il ?}
{159}{}{Madame, j'crois qu'vous devriez éteindre votre Homme Invisible...}
{160}{}{Où est-il ? Je ne le trouve pas ? Je suis perdue ! Oh...}
{161}{}{Que cherches-tu ? Je peux peut-être t'aider.}
{162}{}{Il faudrait vraiment que tu arrêtes de marmonner et que tu articules.}
{163}{}{Mon médaillon ! Je ne l'ai plus. Au voleur ! Au voleur !}
{164}{}{Eh, j'viens d'arriver. J'ai rien fait moi !}
{165}{}{Je peux t'aider à le chercher ?}
{166}{}{Oh, destin cruel !}
{167}{}{Tu m'entends ?}
{168}{}{Allez à plus, Mademoiselle le fantôme.}
{169}{}{Salut. Je vais essayer de me rendre utile.}
{170}{}{Mon médaillon ! Donne-le-moi !!! Oh !!!}
{171}{}{Pas question ! C'est moi qui l'ai trouvé, il est à moi !}
{172}{}{D'accord. Voilà.}
{173}{}{Voilà. Je te souhaite de trouver le repos de l'âme.}
{174}{}{Ok.}
{175}{}{Non.}
{176}{}{Mon médaillon, mon médaillon ! J'arrive, papa ! J'arrive !}
{177}{}{Salut.}
{178}{}{Attends ! Ne pars pas !}
{179}{}{Va dans la lumière !}
{200}{}{Où peut-il bien être ?}
{201}{}{Ohhh.}
{202}{}{Maman ? Papa ? Où êtes-vous ?}
{203}{}{Je ne le trouve pas !}
{500}{}{Maman... Papa... J'arrive...}
{501}{}{Il fait tellement clair...}
{502}{}{Grand-mère, je te vois...}
{503}{}{Oh, c'est le gentil M. Cain. Ca fait plaisir de vous revoir...}
{550}{}{Cette baraque est clean !}
{551}{}{Ooh, joli squelette.}
{560}{}{Exterminateurs !}
{561}{}{Ug.}
