{100}{}{Tu vois un citoyen de La Fosse.}
{101}{}{Tu vois Fred.}
{102}{}{Tu vois Fred. Il porte des vêtements très raffinés.}
{150}{}{On dirait qu'il réfléchit à quelque chose.}
{151}{}{Il a l'air content de ses nouvelles fringues.}
{200}{}{Un jour, je serai riche.}
{201}{}{Oh, laisse-moi tranquille. J'ai des choses à faire.}
{202}{}{Le plan directeur...}
{203}{}{Un jour, je trouverai la solution...}
{204}{}{Pourquoi est-ce que je perds toujours ?}
{205}{}{Les tables doivent être truquées...}
{206}{}{Un jour, je dirigerai ma propre affaire...}
{207}{}{J'aurai des beaux habits...}
{220}{}{Hé ! Il est tard, mon vieux. Laisse-moi tranquille.}
{221}{}{Non, je n'ai pas besoin de compagnie.}
{222}{}{Tu sais quelle heure il est ?}
{223}{}{Je n'ai rien.}
{224}{}{J'ai sommeil. Reviens demain matin.}
{225}{}{Va-t'en !}
{226}{}{Y'a personne à la maison.}
{227}{}{Je peux pas parler. Je vais me coucher.}
{228}{}{Hé, poupée ! Il est tard. Laisse-moi tranquille.}
{240}{}{Plus d'argent ! Laisse-moi tranquille...}
{241}{}{Y'a pas de boulot. Que vais-je devenir ?}
{242}{}{Ne me dis pas que j'ai des dettes ! Ah !}
{243}{}{C'est foutu. Je serai jamais riche.}
{244}{}{J'suis complètement fauché.}
{245}{}{J'ai vraiment besoin de fric...}
{246}{}{Je pourrai jamais acheter des nouveaux habits...}
{247}{}{Je dois trouver un nouveau plan directeur...}
{260}{}{Merci. Heureusement que tu étais là.}
{261}{}{Tu m'as sauvé la vie.}
{262}{}{Je te rendrai ton argent bientôt.}
{263}{}{Je vais bientôt gagner gros.}
{264}{}{C'est toi que je viendrai voir quand j'aurai gagné le gros lot.}
{275}{}{Le plan directeur est en action !}
{276}{}{Merci pour le prêt ! Ton argent est entre de bonnes mains.}
{277}{}{T'en fais pas, les tables sont solides.}
{278}{}{Un jour, je gagnerai gros, grâce à toi.}
{279}{}{C'est pour bientôt ! Je l'sens !}
{280}{}{Je te rembourserai, je l'jure !}
{281}{}{Je vais gagner gros très bientôt. Je l'sens !}
{295}{}{Hein ? On se connaît ? Que veux-tu ?}
{296}{}{Pourquoi tu me lâches pas un peu ? Je te connais même pas. Va emmerder quelqu'un d'autre.}
{297}{}{Je viens chercher l'argent que tu dois à quelqu'un.}
{298}{}{Ca ne fait rien.}
{299}{}{Uk !}
{300}{}{Salut.}
{310}{}{Hé ! Te voilà ! Je te cherchais partout ! Vise un peu ces fringues !}
{311}{}{Encore merci !}
{312}{}{Pas mal.}
{313}{}{T'as l'air d'un sac !}
{314}{}{Berk !}
{315}{}{Ug.}
{320}{}{Merci. Merci infiniment ! Grâce à toi, j'ai 4 jeux identiques !}
{321}{}{Alors, tu es riche, finalement ?}
{322}{}{Alors, où est mon argent ?}
{330}{}{Tu n'aimes pas mes fringues ? Tu as raison. Moi non plus. Je vais renouveler ma garde-robe. Je peux me le permettre !}
{331}{}{Alors, tu es riche, finalement ?}
{332}{}{Où est mon argent ?}
{333}{}{Hum.}
{340}{}{J'allais y venir ! Laisse-moi savourer ma victoire ! J'ai travaillé dur pour y arriver.}
{341}{}{Je sais. Je regrette.}
{342}{}{Va t'faire ! Où est l'argent que je t'ai prêté ?}
{343}{}{J'en ai rien à battre ! Où est mon argent ?}
{350}{}{Bon. Voilà. [Fred te donne $500.] Voici un petit bonus pour m'avoir fait confiance. A plus tard. Merci encore.}
{351}{}{Merci !}
{352}{}{Bref.}
{360}{}{Merci pour ton aide. C'est important pour moi d'avoir obtenu la confiance d'une personne complètement étrangère. Je voudrais te donner ceci...}
{361}{}{Ok.}
{362}{}{Tu n'aurais pas dû.}
{363}{}{Heu.}
{370}{}{Je te dois beaucoup. Tu m'as fait confiance quand la chance m'a abandonné. J'ai un petit quelque chose pour toi en témoignage de ma gratitude.}
{371}{}{Ok.}
{372}{}{Tu n'aurais pas dû.}
{373}{}{Heu.}
{380}{}{Voilà. [Fred te donne $1 000.] J'espère que ça t'aidera. Tu sauras l'utiliser à bon escient je n'en doute pas.}
{381}{}{Je regrette, je ne peux pas accepter.}
{382}{}{Merci.}
{383}{}{C'est pas sûr, mais je l'accepte.}
{384}{}{Miam.}
{390}{}{Voilà. [Fred te donne $2 000, 5 Cellules à Fusion, 5 Cellules Energétiques, et une Grenade à Plasma.] Ca t'aidera peut-être un peu.}
{391}{}{Je regrette, je ne peux pas accepter.}
{392}{}{Merci infiniment.}
{393}{}{C'est pas sûr, mais je l'accepte.}
{394}{}{Miam.}
{400}{}{Quoi ? D'accord, si tu insistes. Merci infiniment. Prends bien soin de toi.}
{401}{}{Salut.}
{410}{}{Quoi ? Tu prends des trucs ? Pourtant, t'as pas l'air de quelqu'un qui plane au Jet. Ne t'approche pas de moi, sale junkie !}
{411}{}{Casse-toi !}
{412}{}{Ug.}
{420}{}{De quoi tu parles ? Je ne dois rien à personne. De qui parles-tu bon sang ?}
{421}{}{Ouais, t'as dit ça la dernière fois. Je ne sais pas de quoi tu parles. Tu te fais des films.}
{422}{}{Babeth dit que tu lui dois $500.}
{423}{}{C'est Babeth qui m'envoie.}
{424}{}{Elisabeth dit qu'elle t'a prêté $200.}
{430}{}{Ah, ouais. Elisabeth m'a prêté $200... Oh, attends. Peut-être... hum...}
{431}{}{Elle m'a dit de te casser la figure si tu ne payais pas.}
{432}{}{Allez, donne-moi l'argent.}
{440}{}{Ouais, c'est ça. J'ai jamais vu autant d'argent de ma vie.}
{441}{}{Hum !}
{442}{}{Oh !}
{450}{}{Et puis quoi encore ! Babeth ne ferait pas de mal à une mouche. Elle est pas mal par contre...}
{451}{}{T'as tort, espèce de trou duc.}
{452}{}{C'était peut-être quelqu'un d'autre.}
{460}{}{Merde. Tu as raison, mais... Je suis presque à sec. Je ne peux pas me permettre de sortir cet argent ! Il faut que je mange moi, tu comprends ?!}
{461}{}{Pardon.}
{462}{}{Pas de chance, c'est pas ton jour hein ?}
{470}{}{Oh merde... J'ai à peine $100. Tu peux m'avancer le reste ? J'te promets que j'te l'rendrai !}
{471}{}{Non, je regrette.}
{472}{}{Allez... Paie le tout !}
{473}{}{D'accord, c'est bon.}
{480}{}{Merde ! Tu vas me ruiner ! Bon, d'accord. Voilà. Je suis complètement à sec maintenant.}
{481}{}{Oh, d'accord. Je t'avance.}
{482}{}{Merci. Gère mieux ton argent la prochaine fois.}
{483}{}{Merci pour tout.}
{490}{}{Je te l'ai dit ! Je peux pas ! Sinon je vais mourir de faim. Oh, allez, tu peux pas m'aider ?}
{491}{}{D'accord. Je t'avance la moitié.}
{492}{}{Non, je regrette. J'ai pas d'argent sur moi non plus.}
{493}{}{Je reviendrai.}
{500}{}{Quoi ? C'est vrai ? Super ! Merci mon pote ! Voilà $100. Je te rendrai les autres $100 dès que possible !}
{501}{}{Quoi ? C'est vrai ? Super ! Merci poupée ! Voilà $100. Je te rendrai les autres $100 dès que possible !}
{502}{}{Pas de problème.}
{503}{}{Tu as intérêt à me rembourser.}
{510}{}{Oh, ne t'en fais pas. Tu as ma parole et cette fois, je n'oublierai pas.}
{511}{}{Ok.}
{520}{}{Au fait, tu sais quoi ? Ces $100 vont vraiment, euh... retarder les choses. Tu crois que je pourrais en réemprunter une partie.}
{521}{}{Combien ?}
{522}{}{Pas question.}
{530}{}{Attends. Ecoute, je te donne $100 et tu paies les $100 restants que je dois à Babeth. Je te les rendrai très bientôt.}
{531}{}{D'accord, c'est bon.}
{532}{}{Pas question.}
{540}{}{$50 seulement. Je t'en prie ! Ca fait partie du plan directeur !}
{541}{}{D'accord.}
{542}{}{Ca me laisse seulement $50 pour payer ton prêt de $200.}
{543}{}{Non.}
{550}{}{Quoi ? Heu... merde ! Tu ne le regretteras pas ! J'assure !}
{551}{}{Pas de problème.}
{560}{}{Heu, ouais. Je vois que tu sais compter. Je t'en prie ! C'est presque rien pour toi, mais c'est énorme pour moi.}
{561}{}{Ok.}
{562}{}{Non.}
{570}{}{Ouais, bien sûr. Tout le monde sait qu'elle déteste ce nom. C'est pas nouveau !}
{571}{}{Je ne lui dois rien.}
{572}{}{Elle a dit que tu avais la mémoire courte.}
{573}{}{Ecoute, je n'ai pas de temps à perdre. Paie, merde !}
{574}{}{Elisabeth a dit qu'elle te l'avait prêté il y a quelque temps.}
{580}{}{Non ! Ecoute... Attends. Ah, cette fois-là... Je ne l'ai pas remboursée ? Je croyais que oui.}
{581}{}{Non. C'est pour ça qu'elle m'envoie.}
{582}{}{Aboule le fric que j'me casse.}
{590}{}{Je ne me souviens pas. Mais Babeth a aidé mes amis et moi-même par le passé, c'est sûr.}
{591}{}{Aboule les $200.}
{592}{}{Donne-moi ce fric.}
{600}{}{Laisse-moi tranquille.}
{601}{}{Peu importe.}
{602}{}{Ok.}
{610}{}{Heu... Salut ! Alors, je suppose que tu veux le fric. Tu crois que tu peux m'avancer la moitié ?}
{611}{}{Non, désolé.}
{612}{}{Si elle te prête $200, faut que tu rembourses.}
{613}{}{D'accord, c'est bon.}
