# 0. Look
{100}{}{Tu vois une femme d'un certain âge. Elle a l'air gentille.}

{150}{}{Tu vois la Mamma, affairée à la cuisine et au ménage.}
{151}{}{Tu vois une femme d'un certain âge, robuste, au sourire jovial.}

# 1. Low Intelligence (WtG)
{200}{}{Bonjour. Je suis la Mamma. Je m'trompe ou t'es pas d'ici ?!}
{201}{}{Re-bonjour. Que peut faire la Mamma pour toi ?}
{202}{}{Moi }
{203}{}{Hum. Ok ? Au revoir Môman.}

# 2. Low IQ more (1)
{220}{}{Tu bouffes tellement que tu nous as presque mis sur la paille ! Trouve-toi donc un autre endroit ! Tu as assez mangé ici pour aujourd'hui.}
{221}{}{Eh bien, }
{222}{}{ , tu as vraiment l'air perdu. Je n'aime pas voir souffrir de pauvres créatures. Tu veux manger quelque chose ?}
{223}{}{Moi ventre plein. Mamma bon manger. Au revoir Mamma.}
{224}{}{Moi payer ?}
{225}{}{Moi partir. Au revoir Mamma.}

# 3. Pay? (2)
{240}{}{Bon, d'accord. Combien tu as ? [Elle prend ton porte-monnaie.]}
{241}{}{Mamma ? [Tu lui tends ton porte-monnaie.]}
{242}{}{Non ! Moi partir. Au revoir, Môman.}

# 4. No, not really (7,9)
{250}{}{Non, je regrette. Il nous reste seulement de la tourte aux rats, un pain de rat, et des spaghettis.}
{251}{}{Qu'est-ce que ça sera, cette fois ?}
{252}{}{Heu, puis-je avoir un truc avec moins de rats ?}
{253}{}{Je prendrai un pain de rat.}
{254}{}{Une tourte aux rats.}

# 5. Not so much rat in it (4)
{270}{}{Tu peux prendre les spaghettis. Il n'y a pas trop de rats dedans. Juste un peu dans la sauce.}
{271}{}{Bon, d'accord. Allons-y pour les spaghettis à la sauce au rat.}

# 6. Here's your food (4,5)
{280}{}{Je t'apporte une belle plâtrée tout de suite. Ca fera $10.}
{281}{}{Je n'ai pas assez d'argent pour le moment. A la place, j'aimerais te poser une question.}
{282}{}{$10 pour du rat ? C'est fou ! Dans le village, un bon gros rat bien juteux coûte bien plus cher. C'est vraiment une affaire !}
{283}{}{Bon, d'accord. Voilà l'argent.}
{284}{}{Je crois que j'ai changé d'avis. J'aimerais te poser une question à la place.}
{285}{}{Je reviendrai plus tard. Au revoir.}

# 7.  Thanks Mom (6,20)
{300}{}{Tu as bon appétit. J'aime les gens qui mangent bien. Est-ce que ça te suffira ?}
{301}{}{Oh que non, Mamma, je vais en reprendre !}
{302}{}{Certainement. Laisse-moi te poser une question.}
{303}{}{Ca suffit pour le moment. Au revoir Mamma.}

# 8. What's there to do here? (13)
{320}{}{Bon, j'ai besoin de quelqu'un pour livrer un repas à Smitty. Il est au Sud-Ouest d'ici, au dépotoir. Tu veux bien me rendre ce service ? En échange, tu auras un repas gratuit.}
{321}{}{Bien sûr. Ca ne me dérange pas.}
{322}{}{Laisse-moi réfléchir. En attendant, j'aimerais te poser une autre question. }
{323}{}{Heu, je regrette, Mamma. Je ne peux pas. Au revoir.}

# 9. Random Food item list (13)
{340}{}{Tu as de la chance. On a du ragoût de radscorpions.}
{341}{}{On a du rat-cochon braisé.}
{342}{}{On a des queues de radscorpions cuites à la vapeur et revenues dans du beurre.}
{343}{}{Je n'ai que de la soupe au chou en ce moment.}
{344}{}{Frites de Brahmine croustillantes !}
{345}{}{Une tourte de gecko bien chaude : ça marche !}
{346}{}{Steak de flanchet.}
{347}{}{Rataupe marbré.}
{348}{}{Fricassée de Flotteur.}
{349}{}{Filet mignon.}
{350}{}{Médaillons de gecko grillé.}
{351}{}{Mante Marsala.}
{352}{}{Rataupe Manicotti.}
{353}{}{Brahmine en brochette.}
{354}{}{Radscorpion en croûte.}
{355}{}{Succulent cochon de lait.}
{356}{}{Heu, je ne sais pas, mais le goût ressemble à celui du poulet.}
{357}{}{Côtelette de Centaure, ma spécialité.}
{358}{}{C'est une surprise.}
{359}{}{C'est de la viande en boîte !}
{360}{}{Ah bon ?}

# 10. Low IQ hand food (3)
{375}{}{Et voilà. Tu as l'air presque famélique. [Mamma te tend une assiette fumante au parfum délicieux.]}
{376}{}{Mèssi Mamma.}

# 11. Low IQ fed (10)
{385}{}{Et voilà. Je savais que ça te plairait.}
{386}{}{Miam-miam... Salut, Mamma.}

# 12. Sure I'll deliver it (8)
{395}{}{Merci infiniment. Je l'aurais bien fait moi-même mais il n'y aurait plus personne pour surveiller ici. Tiens, voilà le repas de Smitty. Si je ne lui faisais pas porter le déjeuner, je suis sûre qu'il oublierait de manger !}
{396}{}{Je le lui apporterai.}

# 13. Hello (WtG, 6,7,8,15,18)
{405}{}{Tu m'as déçue. Le pauvre Smitty a dû venir chercher son repas lui-même. Maintenant, que veux-tu ?}
{406}{}{Bonjour, je m'appelle Mamma et je tiens ce restaurant. La meilleure cuisine au Nord de New Reno.}
{407}{}{De quoi voulais-tu parler avec Mamma ?}
{417}{}{Tiens, ce ne serait pas mon héros par hasard ? Que peut faire Mamma pour toi ?}
{408}{}{T'es pas ma mère.}
{409}{}{Connais-tu un Abri ou quelqu'un nommé Vic ?}
{410}{}{Que peut-on faire ici en ville ?}
{411}{}{Qu'as-tu à manger ?}

# 14. I'm not your mom (13)
{425}{}{J'sais bien, mais tout le monde m'appelle comme ça. Les gens sont un peu de la famille, mais seulement s'ils respectent mes règles.}
{426}{}{Les règles ?}

# 15. Rules? (14)
{435}{}{C'est ça. Pas de vol, pas de gros mots, pas de bagarre. Pas chez moi en tout cas. Sinon, j'te flanque dehors ! J'aime avoir la paix ici.}
{436}{}{Je vois. J'aimerais te poser une autre question.}
{437}{}{C'est sûr. A plus tard, Mamma.}

# 16. Vic or Vault? (13)
{445}{}{Bon, alors il y a une Cité de l'Abri à l'Est d'ici, légèrement vers le Nord. Et Vic, hum... Laisse-moi réfléchir.}
{446}{}{J'espère que tu sais où se trouve Vic. C'est un marchand.}
{447}{}{Merci. C'est tout ce que je voulais savoir.}

# 17. Trader Vic (16)
{455}{}{Vic le Marchand ? Ca me rappelle quelque chose. Oui, je crois que Metzger l'a enfermé.}
{456}{}{Qui est Metzger et où puis-je le trouver ?}
{457}{}{T'es super, Mamma. Merci.}

# 18. Who's Metzger (17)
{465}{}{Metzger c'est le chef de la Guilde des Esclavagistes. Il a enfermé des tas de gens chez lui. Il habite un peu plus haut dans la rue, au Nord d'ici.}
{466}{}{Metzger c'était le chef de la Guilde des Esclavagistes. Il avait enfermé des tas de gens chez lui. Mais je ne sais pas, j'ai entendu dire qu'il avait été tué.}
{467}{}{Merci pour ces renseignements. Mais dis-moi, Mamma...}
{468}{}{Je dois partir m'occuper d'une affaire. Merci, Mamma.}

# 19. Smitty's meal in progress (WtG)
{475}{}{Vas-y et porte ce repas à Smitty maintenant.}
{476}{}{Je ne t'aiderai pas tant que tu n'auras pas tenu parole.}
{477}{}{Dépêche-toi maintenant.}
{478}{}{Va donner le repas à Smitty. Dépêche-toi.}
{479}{}{Ne reste pas là à rien faire ! Porte ce repas à Smitty.}

# 20. Reward (WtG)
{485}{}{C'est du bon travail. Tu dois avoir très faim. Je t'ai préparé une petite gâterie pour te récompenser. Un assortiment de mes meilleurs plats. Uniquement pour toi.}
{486}{}{Ca m'a l'air génial ! Voyons ça.}
{487}{}{Oh, Mamma. Je ne pense pas pouvoir manger maintenant. Merci quand même. Au revoir.}

# 21. What do you know about that haunted house? (13)
{500}{}{Hum. Je sais pas grand-chose là-dessus. C'est peut-être seulement quelqu'un qui s'amuse.}
{501}{}{Elle a toujours été hantée ?}
{502}{}{Cette maison est-elle encore habitée ?}
{503}{}{Je suis d'accord. Au revoir.}

# 22. Started 2 years back... (21)
{520}{}{Ca a commencé il y a 2 ans. J'ai entendu parler de gémissements et d'esprits. Mais j'y crois pas.}
{521}{}{Il y a 2 ans, hein ? La maison était-elle habitée à l'époque ?}
{522}{}{Moi non plus. Merci.}

# 23. Anyone used it then? (21-22)
{540}{}{L'un des garçons dormait là-bas il y a quelques années. Il sait peut-être quelque chose.}
{541}{}{Qui ?}
{542}{}{Peut-être pas. Salut.}

# 24. Who? (23)
{560}{}{Il venait de temps en temps mettre des bijoux en gage. Je me souviens d'un petit médaillon en or qu'il a gardé pour lui.}
{561}{}{Tu te souviens de son nom ?}
{562}{}{Un médaillon ? Etrange. Qui c'était ?}
{563}{}{J'aimerais te poser une autre question.}
{564}{}{Merci. Salut.}

# 25. Name? (24)
{580}{}{Je ne sais plus. Joe ou Joël, un truc dans ce genre là. Il a presque 19 ans maintenant. Il fait partie d'une bande de voyous du coin.}
{581}{}{Merci. J'aimerais te poser une autre question.}
{582}{}{Merci. Salut.}

# 13b. PC Responce line added to node 13
{600}{}{Que sais-tu de cette maison hantée ?}

{800}{}{Les orphelins sont vraiment nombreux dans cette ville.}
{801}{}{Oui, c'est malheureux hein ? Ces enfants n'ont pas de maison et ils volent pour vivre... C'est terrible.}
{802}{}{Quoi, on ne peut rien y faire ? On m'a dit que t'aurais bien une ou deux idées à ce propos.}
{803}{}{Ces enfants ont besoin d'un endroit pour vivre et d'une vraie éducation. Il y a quelques années je voulais ouvrir un orphelinat mais c'était impossible. Personne n'en voulait, et il n'y a jamais eu d'endroit pour ça. C'est vraiment navrant. Les enfants sont notre futur... Ils ont tous oublié ça depuis la guerre.}
{804}{}{Ca m'intéresse. Que puis-je faire pour t'aider ?}
{805}{}{Quel dommage. Bon, c'était sympa de te parler. Allez, salut.}
{806}{}{Tu veux m'aider ? Génial ! Je connais un endroit parfait qui pourrait facilement être reconverti en orphelinat. Il y a un grand bâtiment abandonné dans la zone résidentielle. Il reste des squatteurs là-bas, mais si on trouve un moyen de les faire partir, on pourra restaurer le bâtiment et ce sera parfait. Qu'en penses-tu ?}
{807}{}{Ca pourrait marcher. Je reviendrai te prévenir quand j'aurais fait évacuer le bâtiment.}
{808}{}{J'ai jamais vraiment aimé expulser les gens, tu sais. Peut-être que tu pourrais trouver quelqu'un d'autre ?}
{809}{}{Oh, je vois... C'est vraiment dommage. Merci d'avoir essayé, tu n'as besoin de rien d'autre ?}
{810}{}{Rien. Salut Mamma.}

#added by killap - RP 1.3
{811}{}{Si j'attrape un de ces petits salopards en train de me voler, ce sera la dernière fois. Je me fiche de savoir quelle est leur excuse, un voleur est un voleur. A plus.}
{820}{}{Bonne nouvelle, Mamma. J'ai nettoyé le bâtiment. J'ai eu un petit accrochage, mais ces squatteurs ne seront plus un problème.}
{821}{}{J'ai parlé avec les squatteurs. Ils ont dit qu'ils allaient partir et qu'ils étaient désolés d'avoir causé des ennuis. Ils sont en train de nettoyer l'endroit pour essayer de se racheter. Je me disais que peut-être, s'ils s'en sortent assez bien, vous pourriez leur offrir des emplois.}
{1821}{}{Bonne nouvelle, Mamma. J'ai convaincu les squatteurs de partir. Je ne pense pas qu'ils vous dérangeront à nouveau.}
{822}{}{C'est une excellente nouvelle. J'espère que personne n'a été blessé dans cette histoire. Bien, je vais contacter quelques amis et on pourra commencer. Reviens dans la zone résidentielle d'ici quelques jours pour voir l'orphelinat. Je suis si heureuse ! Encore une fois, merci. Tiens, voilà un repas que j'ai préparé.}
{1822}{}{C'est une excellente nouvelle. Bien, je vais contacter quelques amis et on pourra commencer. Reviens dans la zone résidentielle d'ici quelques jours pour voir l'orphelinat. Je suis si heureuse ! Encore une fois, merci. Tiens, voilà un repas que j'ai préparé.}
{823}{}{Mmh... Je suppose que tout le monde mérite une seconde chance. Bien, je vais contacter quelques amis et on pourra commencer. Reviens dans la zone résidentielle d'ici quelques jours pour voir l'orphelinat. Je suis si heureuse ! Encore une fois, merci. Tiens, voilà un repas que j'ai préparé.}
{824}{}{Merci Mamma. A la prochaine.}
{850}{}{Tu as aidé à l'établissement d'un orphelinat pour les enfants de la Fosse.}
