{100}{}{Tu vois un drogué.}
{101}{}{Tu vois Pierrot.}
{150}{}{Celui-là est un paumé.}
{151}{}{Pierrot a l'air d'avoir besoin d'aide.}
{152}{}{[Parler]}
{155}{}{[Tousse.] Un peu de monnaie pour Pierrot ?}
{156}{}{Bien sûr. Tiens.}
{157}{}{Non, éloigne-toi de moi.}
{158}{}{Pirrrot ?}
{159}{}{Tu es bien pire que moi. [Tousse.] Merci quand même.}
{160}{}{Je regrette. Salut.}
{161}{}{Euh, de rien. Hé hé, ouais.}
{162}{}{Peut-être la prochaine fois. Merci quand même. [Tousse.]}
{163}{}{[Terminé]}
{164}{}{Merci beaucoup. [Tousse.] Vraiment, vraiment beaucoup.}
{165}{}{Pas d'quoi.}
{166}{}{Ouais, ouais.}
{167}{}{Monsieur, [Tousse.] pouvez-vous aider un pauvre homme malchanceux ?}
{168}{}{Voilà 5 dollars.}
{169}{}{Pas aujourd'hui.}
{170}{}{Trouve toi un boulot.}
{171}{}{Bonne dame, aidez s'il vous plaît [Tousse.] un pauvre homme sur sa fin qui est [Tousse.] trop malade pour travailler.}
{172}{}{Ah, mon pauvre... Tenez, voilà 5 dollars.}
{173}{}{Je ne donne jamais d'argent aux mendiants.}
{174}{}{Non.}
{175}{}{Désolé, je n'ai pas d'argent sur moi.}
{200}{}{Hé, tu me donnes de l'argent ?}
{201}{}{T'aurais pas quelques pièces ?}
{202}{}{Hé, tu peux m'aider avec quelques dollars ?}
{203}{}{Peux-tu me soulager avec 2 ou 3 dollars ?}
{204}{}{Tu pourrais me prêter quelques pièces ?}
{205}{}{Tu as de l'argent, gentille Madame ?}
{206}{}{Hé m'dame, vous auriez pas quelques pièces ?}
{220}{}{S'il vous plaît, aidez-moi Monsieur !}
{221}{}{Ahhh, ça fait mal.}
{222}{}{J'ai b'soin d'aide ! J'ai mal !!}
{223}{}{Madame, tu peux m'aider un peu ?}
{225}{}{Merci beaucoup.}
{226}{}{Hé, que crois-tu faire ?}
{230}{}{Ca fait tellement de bien.}
{231}{}{Heu...}
{232}{}{::Rirre bête::}
{233}{}{Hé...}
{234}{}{Cooool...}
{235}{}{Oh ouais...}
{300}{}{Ahh, quelqu'un a buté Tubby ?}
{301}{}{Que s'est-il passé avec Tubby ??}
{302}{}{Oh Merde, Tubby...}
{303}{}{Ahhh...}
{304}{}{J'l'aimais pas ce trouduc, de toute façon.}
{305}{}{Flick est mort ? Merde.}
{306}{}{Qu'est-il arrivé à Flick?}
{307}{}{Flick...}
{310}{}{Hé Tubby, j'ai, euuh, besoin d'aide ici.}
{311}{}{Hé TUBBY !}
{312}{}{Bonjour.}
{313}{}{Hé !}
{314}{}{Hé Flick, J'ai, Euuh, besoin d'aide ici.}
{315}{}{HE FLICK !}
{320}{}{Hé Tubby, tu peux me dépanner ? J'ai du cash.}
{321}{}{Hummm, Tubby, j'ai de l'argent.}
{322}{}{Heu...}
{323}{}{Y m'en faut.}
{324}{}{Hé Flick, tu peux me dépanner ? J'ai du cash.}
{325}{}{Humm, Flick, j'ai de l'argent.}
{330}{}{Uhhh... Encore merci, Tubby.}
{331}{}{T'es un pote, Tubby.}
{332}{}{Je promets, j'arrête demain.}
{333}{}{T'es un pote.}
{334}{}{Uhhh... Encore merci, Flick.}
{335}{}{T'es vraiment un pote, Flick.}
{340}{}{Ici. Maintenant barre-toi, sale drogué.}
{341}{}{Prends-le et va te faire foutre.}
