{100}{}{Tu vois un drogué.}
{110}{}{Tu vois une prostituée fidèle au Jet.}
{111}{}{Tu vois une prostituée fidèle au Jet, c'est une des filles de Dodu.}
{150}{}{On dirait un ami de Dodu.}
{160}{}{Elle a l'air complètement défaite.}
{161}{}{Vu sa tête, ça doit faire trop longtemps qu'elle n'a pas pu planer.}
{200}{}{Putain, où va-t-on trouver du matos maintenant ?!}
{201}{}{Pourquoi t'as tué Dodu ?}
{202}{}{Ca craint à mort maintenant !}
{203}{}{Et maintenant, que fait-on ?}
{204}{}{La galère...}
{205}{}{Hé, c'est pas juste !}
{206}{}{Ne nous fais pas de mal, on le dira à personne.}
{220}{}{Oh là là, t'as vraiment pas l'air cool toi...}
{221}{}{Hé, t'es vraiment cool comme mec ! On t'l'a pas déjà dit ?}
{222}{}{Hé, t'es une chouette fille ! On t'l'a pas déjà dit ?}
{223}{}{Nous sommes les gardes de Dodu.}
{224}{}{Laisse Dodu tranquille. Ici, c'est son territoire.}
{225}{}{Putain, je m'sens bien !}
{226}{}{Nous sommes des gardes. C'est cool, non ?}
{227}{}{Ce matos, c'est du bon !}
{228}{}{Ohhh, je sens plus mes jambes.}
{229}{}{Dodu, c'est not' pote.}
{230}{}{Dodu, on en est complètement mordu.}
{231}{}{Oh là là, là là, là là... Merde, mes yeux...}
{232}{}{Hé... T'es esclavagiste ? Ouah...}
{233}{}{Ce tatouage, ça t'a fait mal ?}
{234}{}{Vous, les esclavagistes, vous êtes des durs.}
{235}{}{C'est pas dangereux d'être esclavagiste ?}
{236}{}{Hé, j'ai entendu dire que ton patron s'était fait descendre. Pas de chance.}
{237}{}{Hé, tu connais la nouvelle ? Y paraît que Metzger est mort.}
{238}{}{Oh, oh... Quelqu'un a buté Metzger le Boucher.}
{239}{}{J'espère que Dodu pourra rester dans les affaires même si Metzger est mort.}
{250}{}{Hé ! Il a tué Dodu !}
{251}{}{J'ai l'impression que mon matos est pourri.}
{252}{}{Oh, qu'est-ce qui s'passe ?}
{253}{}{C'était quoi tout ce bruit ?}
{254}{}{Merde, c'était pas du bon matos.}
{255}{}{Hé ! Elle a tué Dodu !}
{260}{}{Ooooohhouuaaahh... c'est du bon.}
{261}{}{C'est quoi, ça ?}
{262}{}{Ah ouais... Je plane...}
{263}{}{Oh, il fait chaud.}
{264}{}{Elle est tellement belle !}
{265}{}{Oh, c'est le blackout... merde, je vois plus rien.}
{270}{}{Hé, tu vois c'que j' vois ?!}
{271}{}{Ouais, tu sais ce que c'était ?}
{272}{}{Je crois que c'était un oiseau.}
{273}{}{Non, un chien.}
{274}{}{Mais, ça volait !}
{275}{}{La vache... Ca a traversé le sol en trombe.}
{276}{}{T'as des hallus mon vieux !}
{277}{}{Mais non, j'délire pas !}
{278}{}{Peu importe.}
{279}{}{Ohhh, ça recommence à donner des coups de pieds. Ahhh !}
{290}{}{Jolies lumières.}
{291}{}{Beaucoup de lumières.}
{292}{}{Il fait si bon.}
{293}{}{Et les arbres.}
{294}{}{Où sont les femmes ?}
{295}{}{Si vertes et si belles.}
{296}{}{J'aime les pommes de terre.}
{297}{}{Les arbres sont en bois.}
{298}{}{J'aime les femmes et les pommes de terre.}
{299}{}{Ca fait de la fumée quand ça brûle.}
{300}{}{Mais pas ensemble.}
{301}{}{Les animaux habitent dans les arbres.}
{302}{}{Non, pas des femmes et des arbres ! Des femmes et des pommes de terre !}
{303}{}{Je sais grimper aux arbres.}
{304}{}{Une femme qui grimpe aux arbres en mangeant de pommes de terre ? T'es grave, toi.}
{305}{}{D'où ils viennent les arbres ?}
{306}{}{Tu peux pas grimper aux arbres en mangeant des pommes de terre.}
{307}{}{J'aime aussi les arbustes.}
{308}{}{Enfin, c'est difficile.}
{309}{}{Parce qu'ils sont verts.}
{310}{}{Les pommes de terre ne sont pas vertes.}
{311}{}{Oh, les jolies lumières !}
{312}{}{Oh, j'ai mal à la tête...}
{320}{}{Ne me parle plus, j'ai mal à la tête.}
{321}{}{Je ne le dirai à personne.}
{322}{}{Ne me fais pas mal.}
{323}{}{J'ai rien fait.}
{324}{}{J'ai rien vu.}
{325}{}{J'ai rien entendu.}
{326}{}{Va-t'en, s'il te plaît.}
{327}{}{Eh, la miss, j'ai pas trop envie de causer. J'ai un méga mal de crâne.}
{340}{}{Putain, tu crains.}
{341}{}{Pourquoi t'as gâché un trip aussi parfait ?}
{342}{}{Putain c'que ça fait mal !}
{343}{}{Oh, ça va aller oui ?!}
{344}{}{Comment est-ce que ça va arriver ?}
{400}{}{Dodu est fantastique.}
{401}{}{Le Jet, ça m'excite complètement.}
{402}{}{Dodu a le doigté pour s'occuper de ses femmes.}
{403}{}{Tu trouves pas qu'il est fantastique Dodu ?}
{404}{}{Oh, oui mon chou ! Hé, arrête ! T'es pas Dodu !}
{405}{}{Où il est notre homme ?}
{406}{}{Tu sens des picotements dans la peau, hein ?}
{407}{}{Dodu est le meilleur fournisseur de toute la ville !}
{408}{}{Je me sens tellement en vie !}
{420}{}{As-tu entendu un grand "Boum" ?}
{421}{}{Je n'ai pas vu Dodu depuis un bout de temps.}
{422}{}{Où il est Dodu ?}
{423}{}{T'aurais pas vu Dodu ?}
{440}{}{Oh, ma tête !}
{441}{}{Où il est Dodu ?! Je crois que je vais mourir.}
{442}{}{Je peux plus supporter ça.}
{443}{}{Oh, cette douleur devient de plus en plus forte !}
{444}{}{Ca fait un moment que Dodu ne nous a plus approvisionnés. Où est-il ?}
{445}{}{Je sens plus mes lèvres.}
{446}{}{Je sens plus mes doigts.}
{460}{}{Ne me fais pas mal.}
{461}{}{Non, arrête !}
{462}{}{Je ne l'ai pas !}
{463}{}{C'était pas moi !}
{464}{}{Laisse-moi tranquille.}
{465}{}{Je savais pas que c'était à toi !}
