{100}{}{Tu vois un esclave.}
{101}{}{Tu vois Vic.}
{150}{}{On dirait que cet esclave est sous haute surveillance.}
{151}{}{C'est Vic.}
{152}{}{[PARLER]}
{153}{}{Pourrais-tu lui dire que je ne peux pas... attendre ? Qui es-tu ? Tu n'es pas esclavagiste. Que fais-tu ici ?}
{154}{}{Je m'appelle }
{155}{}{. Je suis là pour t'aider à sortir d'ici.}
{156}{}{Je m'appelle }
{157}{}{. Pourquoi t'ont-ils enfermé dans cette cellule ?}
{158}{}{Peux-tu me dire où se trouve l'Abri 13 ?}
{159}{}{Je m'appelle }
{160}{}{. Je reviens tout de suite.}
{161}{}{Moi être }
{162}{}{.}
{163}{}{Metzger m'en veut encore, même après lui avoir réparé sa foutue radio. Il menace de me vendre ! Je ferai tout ce que tu veux pour que tu me sortes de ce pétrin !}
{164}{}{D'accord. Compte sur moi.}
{165}{}{Je regrette, je peux pas. Salut.}
{166}{}{Eh ben !}
{167}{}{Oh, salut ! Encore toi ! Cette foutue radio ne va pas se réparer toute seule. Comment veut-il que j'arrive à la réparer ?}
{168}{}{Où puis-je trouver des pièces de rechange ?}
{169}{}{Je peux peut-être la réparer.}
{170}{}{Peux-tu utiliser cette radio que j'ai trouvée ?}
{171}{}{Je vais voir ce que je peux faire.}
{172}{}{Pèz de change ?}
{173}{}{Je peux le faire ! Mais il me faut des pièces de rechange. Je pourrais les prendre sur une vieille radio que j'ai dans ma cabane à Klamath. Tu vois le magasin des Dunton ? Ben, ma cabane se trouve à l'Est de chez eux.}
{174}{}{Tu veux parler de cette radio ?}
{175}{}{Je vais aller la chercher.}
{176}{}{Hum... Je vais revenir.}
{177}{}{Super ! Je vais réparer cette radio en un rien de temps.}
{178}{}{D'accord. Je vais parler à Metzger.}
{179}{}{Merci.}
{180}{}{Salut.}
{181}{}{Pardon ? Je ne comprends pas.}
{182}{}{Hum...}
{183}{}{Merci ! Je te suis éternellement reconnaissant. Que puis-je faire pour te remercier ?}
{184}{}{Dis-moi où se trouve l'Abri 13.}
{186}{}{Viens avec moi. J'ai besoin d'un coup de main.}
{187}{}{Il n'y a pas de quoi. Au revoir.}
{188}{}{Bonbon ?}
{189}{}{L'Abri 13 ? La Cité de l'Abri se trouve au Sud-Est. Je vais faire des échanges là-bas de temps en temps.}
{190}{}{Tu veux venir avec moi là-bas ?}
{191}{}{Merci. Au revoir.}
{192}{}{Bien sûr ! Je t'accompagne. Ce vieux machin a encore une belle vie devant lui. J'en suis certain. Metzger a beau dire, je me débrouille pas mal en bricolage.}
{193}{}{Génial. Allons-y !}
{194}{}{Bienvenue à bord.}
{195}{}{Peu importe.}
{196}{}{Vic et moi meilleurs copains.}
{197}{}{Tu veux m'accompagner dans ma quête ?}
{198}{}{Génial ! Merci.}
{203}{}{La Cité de l'Abri se trouve à l'Est d'ici. Là, je vais te montrer sur la carte.}
{204}{}{Merci.}
{206}{}{C'est juste là. [Désignant une carte du doigt.]}
{220}{}{Ca va pas marcher. Je sais que la radio que j'ai à Klamath, dans ma cabane, a les pièces qu'il faut.}
{300}{}{Ouais, je peux peut-être t'aider, mais d'abord, tu dois m'aider à sortir d'ici.}
{301}{}{Je te l'ai dit. Si tu peux me faire sortir d'ici, je ferai tout ce que je peux pour t'aider.}
{302}{}{Comment on va faire ?}
{303}{}{Alors, débrouille-toi. }
{304}{}{D'accord, je vais voir ce que je peux faire.}
{350}{}{Tu crois que tu peux m'aider ?}
{351}{}{Metzger ne veut pas me laisser partir.}
{352}{}{J'en ai assez de tout ça.}
{353}{}{Je ferai n'importe quoi pour toi si tu m'aides.}
{354}{}{Je payerai toutes les dépenses que tu auras dû engager.}
{400}{}{J'ai vraiment besoin de cette radio ! Metzger est chaque jour un peu plus en colère contre moi.}
{450}{}{Où as-tu eu cette fiole d'eau ?}
{451}{}{J'avais une fiole d'eau sur laquelle un grand 13 jaune était inscrit. Tu te souviens de l'endroit où tu l'as eue ?}
{500}{}{Ouais. Je me souviens. C'est Ed qui me l'a vendue. C'est un marchand de Brahmines de la Cité de l'Abri.}
{501}{}{Une fiole d'eau ? Oh, attends. Ouais, j'en avais une bonne douzaine. Ca se vendait plutôt bien. Je les ai eues par Ed, un marchand de Brahmines de la Cité de l'Abri.}
{502}{}{La Cité de l'Abri ?}
{550}{}{Tu veux bien arrêter de m'appeler *Patron* ?}
{600}{}{Pas de blème, Chef !}
{601}{}{Ca SUFFIT, maintenant !}
{602}{}{Il faudra bien que ça fasse l'affaire !}
{650}{}{Ok, mon vieux !}
{651}{}{Oouggh !}
{700}{}{Toi et moi faire ami-ami.}
{710}{}{Dis-lui que je ne peux pas réparer sa radio sans pièces de rechange. Je sais pas... Attends. Qui es-tu ? Une nouvelle recrue ? Il a encore chargé quelqu'un de venir me tirer les bretelles, hein ? Ca ne changera rien, je ne peux pas la réparer ici.}
{750}{}{Tu ferais ça pour moi ? Je ferais n'importe quoi pour que tu me sortes d'ici. Le problème, c'est que Metzger ne me laissera pas sortir d'ici tant que j'aurai pas réparé sa radio et je n'ai pas les pièces de rechange.}
{753}{}{Où puis-je trouver les pièces dont tu as besoin ?}
{754}{}{Je vais voir ce que je peux faire.}
{760}{}{C'est une longue histoire. Disons que Metzger me garde ici jusqu'à ce que j'aie réparé cette foutue radio. La galène est foutue et je n'ai pas de pièces de rechange. Comment veut-il que j'arrive à la réparer ?}
{761}{}{Je suis ici pour te sortir de là.}
{764}{}{Aucune idée. Salut.}
{800}{}{Il faut que je répare cette radio. Avec ton aide, on pourra peut-être le raisonner.}
{801}{}{Que puis-je faire ?}
{803}{}{J'en doute. Bonne chance.}
{810}{}{Pourquoi as-tu tué cette pauvre Mamma... J'imagine que tu avais tes raisons. Je regrette, Boss. Je n'ai pas à te poser de questions. C'est une sale ville. Elle avait dû faire quelque chose de mal.}
{811}{}{Hé, Boss, merci de m'avoir tiré de ce bordel avec Metzger. T'as besoin de quelque chose ? Mamma a été assez gentille pour me nourrir en ton absence. Je lui donne un coup de main...}
{812}{}{Salut.}
{813}{}{Oooh.}
{814}{}{Beiye}
{823}{}{Où est ton ami Ed, déjà ?}
{830}{}{Je le ferais si je le pouvais, mais tu n'as pas l'air très bien. Je serai un fardeau. Maintenant que Mamma n'est plus là, je crois que je vais partir. Je ne sais pas où... Nous nous reverrons peut-être. Merci pour tout ce que tu as fait pour moi.}
{831}{}{Je le ferais si je le pouvais, mais tu n'as pas l'air très bien. On dirait que tu as déjà du mal à t'occuper de toi. Je serai un fardeau. Je vais attendre ici, la cuisine de Mamma me rappelle mon ex-femme...}
{832}{}{Je le ferai, honnêtement. Je ferai presque n'importe quoi pour toi. C'est juste que tu n'as pas l'air en forme pour mener quelqu'un. Je vais aller chez la Mamma, tout à l'heure... Jusqu'à ce que tu règles tout. Je n'ai pas goûté à sa cuisine maison depuis un bon moment.}
{833}{}{Pardon, Boss. On dirait qu'il y a du monde. Maintenant que Mamma n'est plus là, je vais partir. Je ne sais pas où... On se reverra peut-être. Merci pour tout ce que tu as fait pour moi.}
{834}{}{Tu as l'air d'avoir beaucoup à faire, Boss. Je vais t'attendre ici, le temps que tu t'occupes de tout. La cuisine de la Mamma me rappelle mon ex-femme... Je ne sais pas si c'est une bonne ou une mauvaise chose.}
{835}{}{Ca me ferait plaisir, Boss. C'est juste que tu ne sembles pas avoir beaucoup de place. Je vais aller chez la Mamma. Je n'y suis pas allé depuis un moment. Viens me chercher si tu trouves de la place pour moi.}
{840}{}{Ed est à la Cité de l'Abri. C'est un trafiquant de Brahmines. Il faisait juste partie de mes nombreux fournisseurs. La Cité de l'Abri n'est pas loin d'ici.}
{845}{}{Je te l'ai dit, c'est là-bas. [Vic désigne une direction sur ton Pip-Boy.]}
{900}{}{Tu savais que Vic était marchand.}
{1000}{}{J'ai besoin de te demander quelque chose.}
{1100}{}{Guérison complète, Patron. Autre chose ?}
{1200}{}{Etat presque parfait, Patron.}
{1300}{}{Je suis presque guéri, Patron. Mais j'ai connu des jours meilleurs...}
{1400}{}{J'ai essayé, Patron, mais je suis pas au top de ma forme. Je ferai de mon mieux.}
{1500}{}{C'est toi le patron, Patron.}
{1501}{}{Ici ? Juste ici ? D'accord, c'est toi le patron.}
{1502}{}{D'accord. Je reste ici et j'attends ton retour, Patron. Tu reviendras, hein ?}
{1503}{}{Aussi longtemps que tu voudras. Je ne bouge pas d'ici.}
{1504}{}{Bien sûr, Patron.}
{1600}{}{Si tu le dis.}
{1601}{}{Bien parlé, Patron.}
{1602}{}{Bien vu, Patron.}
{1603}{}{Bien sûr, Patron. Autre chose ?}
{1604}{}{C'est loin, Patron.}
{1605}{}{Pas de problème, Patron}
{1606}{}{C'est fait, Patron.}
{1700}{}{Certainement, Boss.}
{1701}{}{C'est tout près, Patron.}
{1702}{}{C'est toi qui sais, Patron.}
{1703}{}{Je suis juste derrière toi, Patron.}
{1704}{}{Comme un pot de colle, Patron.}
{1705}{}{Si tu le dis, Patron.}
{1706}{}{Oh, d'accord, Patron.}
{1800}{}{D'accord, je garde mes distances, mais pas trop, Patron.}
{1801}{}{D'accord, je ne le ferai plus, Patron.}
{1802}{}{Je reste juste un peu en retrait, Patron.}
{1803}{}{Certainement, Boss.}
{1900}{}{D'accord, Patron. Je reste loin.}
{1901}{}{C'est toi le patron, Patron.}
{1902}{}{Voilà, Patron.}
{1903}{}{Je m'écarte, Patron.}
{1904}{}{Je prends mes distances, Patron.}
{1905}{}{Je m'éloigne, Patron.}
{1906}{}{D'accord, Patron.}
{2000}{}{Heu... Patron ? Tu as l'air un peu perturbé. Je t'attends ici.}
{2100}{}{Tu me fais peur, Patron. Que t'arrive-t-il ? Tu as l'air... effrayant. Je crois que je vais attendre un petit moment par ici.}
{2200}{}{Certainement, Patron.}
{2201}{}{Tu peux compter sur moi, Patron.}
{2202}{}{Pas de problème, Patron.}
{2203}{}{On peut y aller quand tu veux, Patron.}
{2204}{}{Génial ! Allons-y.}
{2205}{}{Super !}
{2206}{}{Tu es le meilleur, Boss !}
{2207}{}{Tu ne seras plus déçu. Plus d'erreur !}
{2208}{}{Je vais faire attention cette fois, ne t'inquiète pas !}
{2209}{}{Je savais que tu me pardonnerais... Hum. Alors, euh, Boss. Quel est le plan !}
{2210}{}{Je ne te laisserai pas tomber, Boss !}
{2211}{}{Tu es formidable, Boss !}
{2212}{}{Je savais que je n'étais pas trop que je n'avais pas dépassé l'âge pour ça. C'était juste de la malchance. D'accord, Boss ?}
{2300}{}{De la part d'Ed. Il est trafiquant de Brahmines à la Cité de l'Abri. Tu y es déjà allé ? Je vais te montrer sur la carte.}
{2305}{}{La Cité de l'Abri. Ici. Je vais te montrer sur cette drôle de carte.}
{2310}{}{Il devrait être quelque part par ici.}
{2311}{}{La Cité de l'Abri. Regardes sur cette drôle de carte.}
{2403}{}{Où t'es-tu procuré la fiole d'eau de l'Abri 13 ?}
{2404}{}{Ca ne fait rien.}
{2500}{}{Certainement, Boss.}
{2501}{}{Demande-moi ce que tu veux, Boss.}
{2502}{}{Si je le peux, je t'aiderai, Boss.}
{2503}{}{Je n'ai pas d'ennuis, pas vrai, Boss ?}
{2504}{}{Ai-je fait quelque chose de mal, Boss ?}
{2505}{}{Bien sûr.}
{2600}{}{Que va-t-on faire maintenant, Boss ?}
{2601}{}{Quel est le plan, Boss ?}
{2602}{}{Je vais faire de mon mieux, Boss.}
{2603}{}{Que puis-je faire pour toi, Boss ?}
{2604}{}{Les plans ont changé, Boss ?}
{2605}{}{Une nouvelle stratégie, Boss ?}
{2700}{}{Boss, ils m'ont bien eu. Tu dois me conduire chez un docteur. Je ne sais pas si je vais encore pouvoir te couvrir.}
{2701}{}{J'ai besoin d'un docteur, Boss. Ca ne va vraiment pas. Je ne sais pas si je vais encore pouvoir me battre à tes côtés.}
{2702}{}{Boss, ça ne va vraiment pas. Tu dois aller chercher Lenny pour qu'il m'ausculte.}
{2800}{}{Hé, Boss. Tu veux bien que je t'accompagne ?}
{2801}{}{Hé, Boss. Ca ne m'ennuie pas de t'attendre. Je suis quelqu'un de très patient.}
{2802}{}{On se retrouve, Boss ? Je vais essayer de faire encore mieux.}
{2803}{}{J'avais peur que tu ne reviennes pas. Ca fait vraiment plaisir de te revoir, Boss.}
{2804}{}{Tu cherches encore de la compagnie ?}
{2805}{}{Je suis prêt à partir, Boss.}
{2806}{}{Je savais que tu ne m'abandonnerais pas.}
{2807}{}{Tu as besoin de soutien ?}
{2808}{}{Tu as besoin de faire réparer quelque chose ? Je suis l'homme de la situation, Boss !}
{2809}{}{Ne t'inquiète pas Boss. Sulik et moi allons partir, vraiment.}
{2810}{}{C'est parti.}
{2811}{}{Reste ici. Je vais revenir.}
{2812}{}{Moi aller.}
{3100}{}{Quoi ? Euh... Ok, Boss. Si tu le dis.}
{3101}{}{Puis-je ajouter quelque chose, Boss ? Je suis un peu contrarié.}
{3102}{}{Ok... Tu ne vas pas me laisser ici... Pas vrai, Boss ?}
{3103}{}{Mais... Enfin, je veux dire... Certainement, Boss. J'arrive.}
{3200}{}{Eh bien, Boss... Je manie assez bien les petites armes. Je sais me servir de pratiquement toutes les carabines, fusils et de la plupart des pistolets petits et moyens. Je manie également les couteaux. Je suis assez bon au lancement des armes, même si ma visée n'est pas parfaite... En fait, elle est minable. Pardon, Boss. J'essaie vraiment de m'améliorer.}
{3201}{}{Comme je te l'ai dit, Boss, je préfère les petites armes. Je sais me servir de pratiquement tout, carabines, fusils et de la plupart des pistolets de petit et moyen calibres. Et si la situation l'exige, je peux aussi essayer le maniement du couteau et toute autre arme.}
{3300}{}{Je sais me servir des couteaux et je suis assez habile, même si ma visée n'est pas parfaite... En fait, elle est minable. Pardon, Boss. J'essaie vraiment de m'améliorer.}
{3301}{}{Comme je l'ai dit, Boss. Je manie bien les couteaux et je suis assez habile... C'est juste que je manque très souvent ma cible.}
{3400}{}{J'en ai jusque là !}
{3401}{}{Je vais t'arracher ta fichue tête ! On ne fait pas de mal à ma famille !}
{4000}{}{Ici ?}
{4001}{}{C'est mieux, Boss ?}
{4002}{}{Et ici ?}
{4003}{}{Oui, Boss.}
{4004}{}{Quoi ?}
{4005}{}{Où nous aller ?}
{4006}{}{Nous partir, Boss ?}
{4007}{}{Je m'en vais.}
{4008}{}{Pardon, Boss}
{4009}{}{Mieux ?}
{4010}{}{Ouf.}
{4011}{}{Et là, Boss ?}
{4012}{}{Je vais rester ici.}
{4013}{}{Je vais aller ici maintenant.}
{4100}{}{Boss ! Ce n'est pas mieux ici.}
{4101}{}{Je dois voir un médecin.}
{4102}{}{Oh, la vache. Ca fait vraiment mal !}
{4103}{}{Aïe !}
{4104}{}{Oh là là !}
{4105}{}{Eh merde.}
{4106}{}{Docteur ?}
{4107}{}{Je reste ici... A peine.}
{4200}{}{Je n'ai jamais aimé cet endroit.}
{4201}{}{Pourquoi cet endroit est-il si propre ?}
{4202}{}{Tu as senti quelque chose, Boss ?}
{4203}{}{Tu sais, Boss. Je ne crois pas que je reviendrai ici lorsqu'on aura fini. Ce n'est plus chez moi.}
{4204}{}{C'est vraiment plus sale que dans ma mémoire.}
{4205}{}{On ne va pas rester ici longtemps, pas vrai, Boss ?}
{4206}{}{Cet endroit ne changera jamais.}
{4207}{}{Boss, cet endroit va me manquer.}
{4208}{}{Merci encore de m'avoir fait quitter cet endroit, Boss.}
{4209}{}{Je te suis vraiment reconnaissant, Boss.}
{4210}{}{Oh là là, cet endroit a vraiment changé.}
{4211}{}{Cela fait une éternité que je ne suis pas venu ici.}
{4212}{}{Je ne vais pas passer ma retraite ici.}
{4213}{}{Je pourrais ouvrir un atelier de réparations dans le coin.}
{4300}{}{Ah, un endroit pour les yeux enflammés. C'est... C'était chez moi, mais je crois que tu le sais déjà. Pas vrai, Boss ?}
{4400}{}{Sulik, arrête de me regarder comme ça...}
{4401}{}{Boss, Sulik n'arrête pas de me fixer.}
{4402}{}{Joli clebs.}
{4500}{}{La de da...}
{4501}{}{Ho hum.}
{4502}{}{Attendre le Boss....}
{4503}{}{J'attends le Boss.}
{4504}{}{J'attends, c'est tout.}
{4505}{}{Le Boss ne m'abandonnerait certainement pas.}
{4506}{}{Toc, toc... Qui est-là ? Attends. Comment ça se passe...}
{4507}{}{J'attends toujours.}
{4508}{}{Qu'est-ce que ça sent ?}
{4509}{}{Y a-t-il quelque chose à réparer dans le coin ?}
{4510}{}{Je suis ici... J'attends le Boss.}
{4511}{}{Un vieil homme comme moi, en train de gaspiller ses talents à attendre ici.}
{4512}{}{J'aimerais tant manger du chewing-gum. Ca fait des années.}
{4513}{}{Je dois quitter ce fichu boulot... C'est trop d'ennuis.}
{4514}{}{Pourquoi c'est si ennuyeux d'attendre....}
{4600}{}{Euh, merci, Boss.}
{4601}{}{Merci.}
{4602}{}{Tu sais vraiment ce que tu fais ?}
{4603}{}{On ne peut pas plutôt se reposer ?}
{4604}{}{Devons-nous installer un campement ?}
{4605}{}{Suis-je aussi mauvais ?}
{4700}{}{Pas autant, Boss.}
{4701}{}{Si tu insistes, Boss.}
{4702}{}{Boss, ma tête ne va pas exploser, hein ?}
{4703}{}{Boss, je crois que je commence à aimer ce truc.}
{4704}{}{Je me sens un peu bizarre, Boss.}
{4705}{}{Tu es sûr que tu en auras assez pour toi ?}
{4706}{}{Certainement, Boss. Je vais en prendre un peu.}
{4707}{}{Merci, Boss.}
{4708}{}{Pas mal.}
{5000}{}{J'ai un peu faim là. T'veux pas retourner voir Mamma ?}
{5500}{}{Boss, je crois que je me suis cassé un membre. Tu devrais regarder.}
{5501}{}{Boss, j'ai l'impression de brûler. Tu devrais jeter un oeil.}
{5502}{}{Boss, je me sens comme si on m'avait empoisonné. Tu devrais regarder.}
