{100}{}{Tu vois une femme mince au teint hâlé.}
{101}{}{Tu vois une fermière.}
{102}{}{Tu remarques qu'elle a le teint hâlé d'une fermière.}
{200}{}{Voici ma maison.}
{201}{}{Saleté de bandits !}
{202}{}{Laisse-nous tranquilles !}
{203}{}{Je déteste les bandits. }
{204}{}{Nous ne possédons rien que tu puisses voler.}
{205}{}{Epargne-moi !}
{206}{}{J'en ai assez.}
{207}{}{Prends ce que tu veux.}
{208}{}{Pitié, épargne-moi !}
{209}{}{Je déteste la ferme de toute façon.}
{210}{}{Pitié, ne mets pas le feu à la maison !}
{220}{}{Ne me dérange pas.}
{230}{}{Merci de nous avoir aidés.}
{231}{}{J'aimerais qu'il y ait plus de personnes comme toi dans ce monde.}
