{100}{}{Tu vois un homme qui porte une armure de combat.}
{101}{}{Tu vois Kaga vêtu d'une armure de combat.}
{102}{}{Il porte une armure de combat. On dirait qu'il a de bonnes armes.}
{103}{}{Cette fois, il t'attendait.}
{104}{}{L'Etre Elu ne retournera jamais à Arroyo !}
{105}{}{Kaga te réduira en miettes !}
{106}{}{Kaga n'a peur de personne !}
{107}{}{Ne bouge plus, laisse Kaga viser !}
{108}{}{On se reverra !}
{109}{}{Ce n'est pas la dernière fois que tu verras Kaga !}
{110}{}{Kaga a vraiment besoin d'un entraînement plus poussé.}
{120}{}{Casse-toi Kaga !}
{150}{}{[Un grand guerrier puissamment bâti se tient devant toi, ses yeux reflètent la haine alors qu'il te passe en revue] Alors comme ça, ils ont chassé Kaga, et ont fait de TOI l'Etre Elu ? Ha ! Tu penses qu'être le petit fils de l'Habitant de l'Abri te rend exceptionnel ?! Tu crois que tu vaux mieux que moi, Kaga le Grand ?!}
{151}{}{Hé bien, JE SUIS, l'Etre Elu, n'est-ce pas ?}
{152}{}{Hé, attends une seconde. J'ai jamais dit que je valais mieux que toi.}
{160}{}{Ce titre ne voudra plus rien dire lorsque Kaga t'arrachera la tête !}
{161}{}{Aucune parole ne te sauvera la peau. Toi mort, mon honneur sera restauré. Kaga va maintenant prendre sa revanche !}
{200}{}{Ooglie ?}
{201}{}{Quoi !? C'est *toi* qu'ils ont choisi comme Etre Elu ? ho-la-la, ils doivent être désespérés.}
{202}{}{Moi pas aimer toi. Toi l'air méchant.}
{203}{}{Je n'ai pas de temps à perdre à te parler. Prépare-toi à mourir des mains de Kaga !}
