{100}{}{Tu vois un homme qui porte une armure de combat.}
{101}{}{Tu vois Kaga vêtu d'une armure de combat.}
{102}{}{Il porte une armure de combat. On dirait qu'il a de bonnes armes.}
{103}{}{Cette fois, il t'attendait.}
{104}{}{L'Etre Elu ne retournera jamais à Arroyo !}
{105}{}{Kaga te réduira en miettes !}
{106}{}{Kaga n'a peur de personne !}
{107}{}{Ne bouge plus, laisse Kaga viser !}
{108}{}{On se reverra !}
{109}{}{Ce n'est pas la dernière fois que tu verras Kaga !}
{110}{}{Kaga a vraiment besoin d'un entraînement plus poussé.}

{111}{}{Te voilà enfin, "Etre Elu".}
{112}{}{Il faut que cela cesse Kaga.}
{113}{}{Ha ! Ne t'inquiète pas, nos rencontres vont bientôt prendre fin.}
{114}{}{Et j'aurai enfin ma vengeance !}

{115}{}{Une fois encore, je mets fin à ce combat prématurément.}
{116}{}{Mais il doit être le dernier.}
{117}{}{La prochaine fois que nous nous rencontrerons, un seul d'entre nous en sortira vivant.}
{118}{}{Je serai prêt Kaga.}

{120}{}{Casse-toi Kaga !}

#added by RP 1.3
{150}{}{[Un grand guerrier puissamment bâti se tient devant toi, ses yeux reflètent la haine alors qu'il te passe en revue] Alors comme ça, ils ont chassé Kaga, et ont fait de TOI l'Etre Elu ? Ha ! Tu penses qu'être le petit fils de l'Habitant de l'Abri te rend exceptionnel ?! Tu crois que tu vaux mieux que moi, Kaga le Grand ?!}
{151}{}{Hé bien, JE SUIS, l'Etre Elu, n'est-ce pas ?}
{152}{}{Hé, attends une seconde. J'ai jamais dit que je valais mieux que toi.}

{160}{}{Ce titre ne voudra plus rien dire lorsque Kaga t'arrachera la tête !}
{161}{}{Aucune parole ne te sauvera la peau. Toi mort, mon honneur sera restauré. Kaga va maintenant prendre sa revanche !}

#dumb dialogue
{200}{}{Ooglie ?}
{201}{}{Quoi !? C'est *toi* qu'ils ont choisi comme Etre Elu ? Ho-la-la, ils doivent être désespérés.}
{202}{}{Moi pas aimer toi. Toi l'air méchant.}
{203}{}{Je n'ai pas de temps à perdre à te parler. Prépare-toi à mourir des mains de Kaga !}

{300}{}{Abandonne, t'es foutu.}
{301}{}{Blah !}
