{100}{}{J'en tirerai un bon prix au marché.}
{101}{}{Essaie de ne pas abîmer la marchandise.}
{102}{}{Tu feras un esclave plein d'entrain.}
{103}{}{Ce n'est pas bien.}
{104}{}{Fuyons !}
{105}{}{Je devrais peut-être me mettre à vendre des meubles à la place.}
{106}{}{Les esclavagistes ne devraient pas se battre entre eux.}
{107}{}{La guilde sera mise au courant !}
{108}{}{Que fais-tu ?}
{109}{}{De la chance ?}
{110}{}{Tu as trouvé de bons esclaves ?}
{111}{}{On vient renouveler notre stock.}
{112}{}{C'est notre territoire ici.}
