{100}{}{Pour l'Unité !}
{101}{}{Tenez-les à distance, messieurs.}
{102}{}{A mort les intrus !}
{103}{}{Protégez la ville !}
{104}{}{Allez ! Allez ! Allez !}
{105}{}{Attention ! Des pillards !}
{106}{}{Fichons le camp d'ici !}
{107}{}{Oh, non... Juste au moment où je nous croyais en sécurité. Assez ! Assez !}
{108}{}{Vas-y !}
{109}{}{Traite notre peuple avec respect.}
{110}{}{Ne viole pas la loi.}
{111}{}{Si tu cherches les ennuis, souviens-toi de nous. Sois sage et Marcus sera sage !}
{112}{}{Nous sommes des pacifistes à Collines Brisées, mais nous savons nous battre.}
