{100}{}{Tuer est une forme d'art.}
{101}{}{Ton karma dit que tu dois mourir.}
{102}{}{La vie et la mort sont la même chose.}
{103}{}{Meurs avec honneur !}
{104}{}{Mon heure a sonné.}
{105}{}{Mourir au combat est honorable. Ouais, c'est ça !}
{106}{}{Une étude plus complète est nécessaire.}
{107}{}{La fuite est déshonorante. Mais la mort serait pire.}
{108}{}{Il vaut mieux un lâche vivant qu'un héros mort.}
