{200}{}{Si j'y attache une corde, je pourrais probablement descendre là-bas.}
{201}{}{Une corde serait, sans aucun doute, utile ici.}
{300}{}{Ca devrait le faire.}
{301}{}{J'ai déjà placé la corde.}
{302}{}{Tu attaches la corde à un des bords et laisses tomber le reste de la corde en bas. Tu entends un bruit sourd, la corde touche le fond.}
{400}{}{Tu pénètres dans l'un des systèmes de ventilation de l'EPA. Tu peux entendre une multitude d'insectes qui se déplacent.}
