{100}{}{Tu ne devrais pas mettre le minuteur. Cela pourrait être dangereux.}
{101}{}{L'impact de l'explosion ne semble pas assez puissant pour dégager le passage.}
{102}{}{Le chariot a l'air en état de marche. Tu peux essayer de le pousser.}
{103}{}{En attachant de la dynamite sur la barre en métal, tu peux avoir la puissance suffisante pour ouvrir le passage.}
{104}{}{De la dynamite est attachée à une barre en métal sur le chariot.}
{105}{}{Un bon petit coup et ça devrait marcher.}
{106}{}{Tu fournis un gros effort pour pousser le chariot.}
{107}{}{Tu pousses le chariot sur les rails.}
{108}{}{Le chariot à lui tout seul ne suffira pas à ouvrir la mine.}
{109}{}{Tu ne trouves rien auquel tu pourrais l'attacher.}
{110}{}{Si seulement tu avais une barre en métal pour l'attacher à l'avant du chariot.}
{111}{}{Tu attaches la barre en métal au chariot.}
{112}{}{Tu attaches la dynamite à la barre en métal.}
