{100}{}{Tu vois un scientifique plutôt jeune à la chevelure dégarnie. Il a l'air absorbé par son travail.}
{101}{}{Tu vois Crockett, le scientifique Hubologiste.}
{102}{}{Tu vois un scientifique plutôt jeune à la chevelure dégarnie. Il est débraillé et semble négligé.}
{103}{}{Ouais ? Qu'est-ce tu veux ?}
{104}{}{Agh. Hum. Duur.}
{105}{}{Le Docteur Jing m'envoie. Il veut une SuperArmure renforcée.}
{106}{}{Peux-tu améliorer ma SuperArmure ?}
{107}{}{Qui es-tu ?}
{108}{}{Qu'est-ce tu fais ici ?}
{109}{}{Rien. Merci.}
{110}{}{Ma parole, c'est dingue ! Il y a de plus en plus de sous-humains qui se baladent dans le coin ! Allez, ouste ! Ouste !}
{111}{}{Euh.}
{112}{}{Ouais, je peux le faire. Mais qu'est-ce tu m'donnes en échange ?}
{113}{}{Le Docteur Jing voudra certainement te vendre du carburant pour le vaisseau spatial.}
{114}{}{Je peux payer.}
{115}{}{Je te laisserai en vie.}
{116}{}{Rien. Laisse tomber.}
{117}{}{Je m'appelle Crockett. Je suis scientifique et bricoleur. J'peux me remettre au travail là ?}
{118}{}{Non. J'ai d'autres questions.}
{119}{}{Ouais, bien sûr.}
{120}{}{Je mets au point une nouvelle technologie et je prends ma part du gâteau sur les membres de la secte, si tu vois ce que je veux dire.}
{121}{}{Alors comme ça, tu n'es pas Hubologiste ?}
{122}{}{Je comprends. Mais dis-moi...}
{123}{}{Non. Que veux-tu dire ?}
{124}{}{Quel type de nouvelle technologie as-tu mis au point ?}
{125}{}{Parfaitement clair. Au revoir.}
{126}{}{Eh bien... Je *pense* que ça fera l'affaire. Marché conclu. As-tu l'armure à renforcer avec toi ?}
{127}{}{Oui.}
{128}{}{Non.}
{129}{}{Parfait. Ca te coûtera $10 000 et pas de marchandage. C'est à prendre ou à laisser. J'ai besoin de nouveau matos.}
{130}{}{$10 000 ? C'est scandaleux ! Je n'ai pas autant d'argent !}
{131}{}{Très bien. Voilà.}
{132}{}{Je reviendrai plus tard.}
{133}{}{[Il semble amusé.] Es-tu en train de me menacer ?}
{134}{}{Oui. Tu acceptes ou tu crèves.}
{135}{}{Non, je plaisantais.}
{136}{}{Laisse-la moi une journée et je m'en occuperai. Avant de partir, sache qu'avec ce que j'ai comme matériel, je ne peux m'occuper que de deux armures.}
{137}{}{Certainement. Mais dis-moi...}
{138}{}{Je reviendrai pour l'armure.}
{139}{}{Je ne peux pas exercer mes talents si tu ne l'as pas. Reviens quand tu l'auras.}
{140}{}{J'ai d'autres questions.}
{141}{}{Salut.}
{142}{}{[Il hausse les épaules] Tu veux cette armure ou quoi ? C'est $10 000 à prendre ou à laisser.}
{143}{}{Je reviendrai plus tard.}
{144}{}{Très bien. Voilà.}
{145}{}{Du vrai banditisme ! C'est hors de question.}
{146}{}{[Il te regarde dans les yeux et te prend au sérieux.] As-tu l'armure avec toi ?}
{147}{}{Oui.}
{148}{}{Non.}
{149}{}{[Il te regarde dans les yeux et pense que tu bluffes.] Essaie un peu, minable. Tu auras les gardes au cul et tu ne sauras pas comment renforcer ton armure !}
{150}{}{Très bien. Crève donc binoclard.}
{151}{}{Merde. Tu m'as pris au mot.}
{152}{}{Tu bluffes. Je crois qu'on va voir ce que les gardes pensent de ça.}
{153}{}{Bon sang !}
{154}{}{Ces types ne connaissent rien à la science. Je les aide à justifier leur extravagance en échange d'un peu de bon temps avec les filles et d'un gros salaire.}
{155}{}{Hum. J'ai d'autres questions à te poser.}
{156}{}{Pas mal du tout. A plus.}
{157}{}{Voyons... J'ai construit un réacteur nucléaire pour le vaisseau spatial. J'ai mis au point le processus de renforcement de la SuperArmure. Et je répare les choses cassées.}
{158}{}{Je vois. Eh bien, j'ai d'autres questions.}
{159}{}{Hum. Je dois partir. Au revoir.}
{160}{}{Hé, je n'ai rien contre toi. Ne me fais pas de mal.}
{161}{}{J'ai quelques questions à te poser.}
{162}{}{Je suis ici pour mon armure.}
{163}{}{Trop tard.}
{164}{}{Salut.}
{165}{}{C'est pas encore prêt. Tu dois me laisser du temps !}
{166}{}{Très bien. J'ai quelques questions.}
{167}{}{Très bien, je reviendrai.}
{168}{}{Je l'ai ici pour toi. Prends-la, prends-la.}
{169}{}{Merci. J'ai d'autres questions.}
{170}{}{Merci.}
{171}{}{Merci. MAINTENANT, tu peux crever !}
{172}{}{Je n'ai plus assez de produits chimiques. Désolé.}
{173}{}{Alors, tu vas pouvoir répondre à quelques questions.}
{174}{}{Alors tu peux crever.}
{175}{}{Oh. Mince. Au revoir.}
{176}{}{Alors, où il est mon carburant ? Tu m'avais promis du carburant, trou duc' !}
{177}{}{Tu l'auras, tu l'auras. Mais d'abord réponds à quelques questions.}
{178}{}{Ouais, eh bien, je t'ai baisé en beauté.}
{179}{}{Et aussi pour la dernière fois. GARDES !}
{180}{}{Crève, ordure !}
{181}{}{Merde. Je m'en vais.}
{182}{}{Ok, tu veux quoi maintenant ?}
{183}{}{Tu acceptes de payer $10 000 cette fois ?}
{184}{}{Laisse-la ici une journée et je m'en occuperai. Mais n'oublie pas que c'est la dernière dont je peux m'occuper.}
{185}{}{Hé, je t'ai amené une autre armure à améliorer.}
