{100}{}{Tu vois un garde bien armé.}
{101}{}{Tu vois un garde Hubologiste.}
{102}{}{Tu vois une personne bien armée au regard cruel.}
{103}{}{Envahisseur !}
{104}{}{Emparez-vous de l'intrus !}
{105}{}{Par ici ! Par ici !}
{106}{}{Ton heure est venue, infidèle ! La Grande Roue va rouler sur toi !}
{107}{}{Nous sommes les Gardiens. Tu dois mourir à présent.}
{108}{}{Père Etoile, guidez-moi.}
{109}{}{Tu as enfreint nos règles !}
{110}{}{Si les lois ne peuvent rien contre toi, nos armes, elles, ne vont pas te rater.}
{111}{}{Nous sommes les représentants de la loi d'Hubol.}
{112}{}{Sacrilège !}
{113}{}{Fais attention où tu mets les pieds.}
{114}{}{Regarde où tu mets les pieds, étranger.}
{115}{}{Ne touche pas à ce que tu n'as pas le droit de toucher.}
{116}{}{Un seul faux pas, et nous te réduisons en chair à pâté.}
{117}{}{Fais très, très attention.}
{118}{}{Nous représentons la loi d'Hubol. Ne l'enfreins pas.}
{119}{}{Je suis AHS-4.}
{120}{}{Je *t'alignerais* si tu te conduis mal.}
{121}{}{J'ai le consentement de la Grande Roue.}
{122}{}{Bonjour camarade voyageur.}
{123}{}{Bonjour,}
{124}{}{C'est un plaisir de t'avoir parmi nous.}
{125}{}{Continue comme ça.}
{126}{}{Ne dérange pas ceux qui essaient de se concentrer.}
{127}{}{Ta présence est la bienvenue... là-bas.}
{128}{}{Hubol nous a chargés de surveiller son troupeau.}
{129}{}{Le Père Etoile t'aime beaucoup. C'est pour ça que tu es ici.}
{130}{}{Nous sommes loyaux envers AHS-9.}
{131}{}{Obéis.}
{132}{}{Dors.}
{133}{}{Consomme.}
{134}{}{Nous prenons tes meilleurs intérêts à coeur.}
{135}{}{.}
