{100}{}{Tu vois quelqu'un portant une casquette de capitaine.}
{101}{}{Tu vois le Capitaine A. Ron Meyers}
{102}{}{Tu vois une crapule portant des vêtements en lambeaux et une casquette de capitaine.}
{103}{}{Qu'est-ce tu veux ? Je n'adresse la parole qu'à mes amis et aux gens bien. Commence par faire quelque chose pour un des mes potes si tu veux me parler.}
{104}{}{[Terminé]}
{105}{}{J'ai entendu parler de ce que tu as fait pour mes hommes. Merci. Que puis-je faire pour toi ?}
{106}{}{Qui toi ?}
{107}{}{J'ai entendu dire que tu en savais beaucoup sur ce navire.}
{108}{}{Pourquoi t'appellent-ils Capitaine ?}
{109}{}{Comment tu fais marcher ce truc ?}
{110}{}{Rien.}
{111}{}{Je suis le Capitaine. Je commande ce navire. Si tu as d'autres questions, adresse-toi à un des Shi, à Badger, ou à quelqu'un d'autre. Je n'ai pas de temps à t'accorder.}
{112}{}{[Terminé]}
{113}{}{Ce navire c'est le pétrolier Poséidon. Il est équipé de techniques d'avant-guerre. Il dispose d'un passe électronique permettant d'accéder à la Salle de navigation informatique et d'un transpondeur IFF qui le protège des armes Poséidon.}
{114}{}{Comment sais-tu tout ça ?}
{115}{}{C'est quoi un transpondeur IFF ?}
{116}{}{Comment ça marche ?}
{117}{}{Merci. Au revoir.}
{118}{}{J'ai travaillé pour l'Enclave. Et puis, je me suis rendu compte que je ne me battais pas pour les Etats-Unis, mais pour les vieux salauds fortunés qui ne voulaient rien céder de leur pouvoir. J'ai déserté et maintenant, je vis ici avec des gens plus honnêtes.}
{119}{}{Des gens plus honnêtes ? Ces types ?}
{120}{}{C'est quoi au juste l'Enclave ?}
{121}{}{Comment fais-tu marcher ce truc ?}
{122}{}{Au revoir.}
{123}{}{Comment on pilote ce rafiot ? Tu le remplis avec du carburant, t'as qu'à essayer chez les Hubologistes ou les Shis après que tu te sois occupé de tout le reste, et tu appuies sur le bouton. L'ordinateur s'occupera du reste, enfin, s'il marche toujours. Il naviguera jusqu'à la plate-forme pétrolière, à moins que ce vieux sous-marin ne le fasse exploser. Mais au moins tu n'auras pas à t'inquiéter que l'Enclave te tire dessus, parce que tu as le transpondeur IFF. Arrange-toi juste pour avoir tout le nécessaire pour obtenir un accès total : le passe FOB, un ordinateur qui marche et du carburant. Trop facile, hein ?}
{124}{}{Certainement. Comment sais-tu tout ça ?}
{125}{}{C'est quoi au juste ce transpondeur IFF et ce fameux passe ?}
{126}{}{Quelle plate-forme pétrolière ?}
{127}{}{Oui. Au revoir.}
{128}{}{La technologie IFF signifie que le navire est identifié comme un navire ami et que les autres installations Poséidon, comme disons, une plate-forme pétrolière, ne te tireront pas dessus lorsque tu t'en approcheras. Oh, et le passe électronique c'est un passe issu d'une technologie de l'Enclave te permettant de franchir électroniquement une porte. Tu devrais en trouver un dans une de leurs bases ou un endroit de ce genre.}
{129}{}{Comment sais-tu tout ça ?}
{130}{}{Quelle plate-forme pétrolière ?}
{131}{}{Merci. Au revoir.}
{132}{}{Oui. Avec ces gens-là, on sait vraiment à quoi s'en tenir. Ils ne plaisantent pas. L'Enclave était comme une meute de hyènes, elle pouvait te tomber dessus en une seconde.}
{133}{}{C'est quoi au juste l'Enclave ?}
{134}{}{Comment as-tu fait pour t'en débarrasser ?}
{135}{}{L'Enclave c'est le vestige d'une époque révolue. En pilotant cet engin jusqu'à la plate-forme, tu t'en rendras compte par toi-même.}
{136}{}{Comment fait-on pour piloter ça ?}
{137}{}{Quelle plate-forme ?}
{138}{}{C'était assez facile. Un jour, j'ai simplement quitté la base de Navarro et je suis arrivé ici. J'ai pensé que ce serait le dernier endroit où on viendrait me chercher. Et puis, je ne suis pas assez important pour que l'Enclave me cherche.}
{139}{}{C'est quoi au juste l'Enclave ?}
{140}{}{Merci. Au revoir.}
{141}{}{Il y a une grande plate-forme Poséidon sur l'eau. C'est la dernière base de l'Enclave.}
{142}{}{Comment sais-tu tout ça ?}
{143}{}{Que se passe-t-il d'autre sur la plate-forme ?}
{144}{}{Merci. Au revoir.}
{145}{}{Des rumeurs se propagent.}
{146}{}{Je vois. Que se passe-t-il d'autre sur la plate-forme ?}
{147}{}{Je vois. Au revoir.}
{148}{}{J'en ai aucune idée. J'étais technicien à Navarro, pas opérateur de plate-forme. On leur a juste parlé via les lignes de communication et c'est à peu près tout.}
{149}{}{Je vois. Comment on pilote ça déjà ?}
{150}{}{Merci. Au revoir.}
{151}{}{Tu as commis une grave erreur en venant te frotter au Capitaine et à ses amis...}
{152}{}{Comment faire pour piloter ce bateau ? Eh bien, je vois que tu as déjà fait le plein de carburant. Quand tu te seras occupé de tout le reste, contente-toi d'appuyer sur le bouton. L'ordinateur s'occupera du reste, enfin, s'il marche toujours. Il naviguera jusqu'à la plate-forme pétrolière, à moins que ce vieux sous-marin ne le fasse exploser. Mais au moins tu n'auras pas à t'inquiéter que l'Enclave te tire dessus, parce que tu as le transpondeur IFF. Arrange-toi juste pour avoir tout le nécessaire pour obtenir un accès total : le passe FOB, un ordinateur qui marche et du carburant. Trop facile, hein ?}
{153}{}{Oh ouais. Tu dois également faire marcher l'ordinateur de navigation.}
{154}{}{Je suis content de te revoir ! De quoi t'as besoin ?}
# Begin Seraph's Code
{155}{}{, et sauf si je me trompe, c'est la que sont tes amis aussi.}
{156}{}{.}
# End Seraph's Code

#added by killap
{200}{}{Quel vieux sous-marin ?}
{210}{}{Il y a un vieux sous-marin chinois abandonné là-bas dans la baie. Cette satanée chose me donne la chair de poule, tapie sous l'eau comme un fantôme rouillé. Je doute qu'il marche encore, mais si c'était le cas, son système d'armes automatisées pourrait envoyer ce tanker en enfer avant même que tu ne t'approches de la plate-forme pétrolière.}
{211}{}{Qu'est-ce qui te fait croire que le sous-marin n'est plus actif ?}
{220}{}{Eh bien, d'une part, il est resté là à pourrir dans l'océan depuis la Grande Guerre. De plus, s'il était toujours actif, il aurait tiré sur cette plate-forme lorsque l'Enclave s'y est installée. Bien sûr, les Shis pourraient bien l'avoir bricolé, on ne sait jamais. Il vaudrait mieux que tu y jettes un oeil avant d'appareiller.}
{221}{}{Et comment je fais pour y aller ?}
{230}{}{Si quelqu'un sait quelque chose concernant ce sous-marin, ce sont bien les Shis. C'est le sous-marin qui les amenés ici en premier lieu, ça ne m'étonnerait pas d'apprendre qu'ils vénèrent cette chose. L'empereur Shi sait tout ce qu'il y a à en savoir, bien sûr, mais bonne chance avec ça. Tu ferais aussi bien de demander à Lao Chou, là-bas au Dragon Volant 8, il est connu pour distribuer des informations de temps en temps. Et va savoir, tu pourrais peut-être même faire parler un des dockers.}
