{100}{}{Tu vois une personne en pyjama amusant. Elle semble préoccupée.}
{101}{}{Tu vois un ingénieur du sous-marin Shi.}
{150}{}{Euh, que fais-tu, à rôder comme ça ?}
{151}{}{Tu es un genre d'espion ?}
{200}{}{Je déteste travailler sur cette épave.}
{201}{}{Essayons de recalibrer ceci... là, voilà...}
{202}{}{Tous ces câbles étendus partout et aucune isolation de prévue...}
{203}{}{J'espère que je ne serai pas électrocuté en rechargeant le générateur.}
{300}{}{Hé, je suis occupé là.}
{301}{}{Désolé, je travaille.}
{302}{}{Ces câbles ne vont pas se réparer tous seuls, Ok ? Va trouver quelqu'un d'autre à emmerder.}
