{100}{}{Tu vois une petite Goule.}
{101}{}{Tu vois Percy Crump la Goule, un grand marchand.}
{102}{}{Tu vois une Goule petite et assez grosse. Elle est sur son trente-et-un.}
{103}{}{Par toutes les Goules ! J'm'en va t'remercier pour m'avoir ramené mon ami ! Pour sûr que j'va t'donner quèkchose pour tout l'mal qu'tu t'es donné.}
{104}{}{Tout le plaisir est pour moi.}
{105}{}{Qu'est-ce que j'y gagne ?}
{106}{}{Bon, j'espère que ça en vaut la peine. Ca a été beaucoup de travail, et beaucoup de voyages aussi. Et puis c'était dangereux aussi. J'aurais pu y laisser ma peau moi dans tout ça.}
{107}{}{Sûr qu'tu veux pas résoudre les problèmes du vio Percy ? J'pourrais sûr'ment utliser d'l'aide.}
{108}{}{Euh, laisse-moi y penser plus longtemps. En attendant, t'as rien à échanger ?}
{109}{}{Bon, tu peux me redire de quoi il s'agit.}
{110}{}{Je ne savais pas que tu m'embêterais avec ça chaque fois que j'entre. Au revoir.}
{111}{}{Tu l'as trouvé Woody ? J'suis vraiment inquiet. Il n'est jamais sorti si longtemps.}
{112}{}{Euh, pas encore, mais je continue à le chercher. Hé, t'aurais pas quelque chose à troquer ?}
{113}{}{Non. Je ferais mieux de continuer à le chercher.}
{114}{}{Salut toi, moi c'est Percy Crump, l'plus grand commerçant d'cette bonne ville. Mais tu peux m'appeler l'vieux Percy. Ouais. Tout l'monde le fait. Bon, qu'est-ce que j'peux faire pour toi ?}
{115}{}{Qu'est-ce que l'vieux Percy peut faire pour toi ?}
{116}{}{Je voulais juste savoir c'qui s'passe en ville.}
{117}{}{Je me demandais si t'avais un truc à vendre ou à troquer.}
{118}{}{Euh, rien de spécial, je passais juste. Au revoir.}
{119}{}{Troquer ?}
{120}{}{Moi aller, salut.}
{121}{}{J'veux juste te féli-chi-ter pour avoir réparé not' réacteur nucléaire. Y ronronne comme une chatte main'ant. A part ça, j'me demande c'que fait mon ami Woody pour pas êt' encore là.}
{122}{}{J'dois être r'connaissant pour la réparation du réacteur nucléaire. C't idiot de Festus il aurait pas fait si bien. Sinon, à part ça, j'me demande où qu'c'est qu'il a disparu mon ami Woody.}
{123}{}{oh, y'a pas grand-chose de nouveau en ville. Y paraît qu'Wooz a fait du bizness l'aut'jour. Mais mis à part ça j'me demande où qu'c'est qu'il a disparu mon ami Woody.}
{124}{}{Bon, dis m'en plus là-dessus.}
{125}{}{Ho, c'est dommage. Ben, je hais les contes tristes. Je te laisse à ta douleur. Au revoir.}
{126}{}{Pour sûr, hé, j'ai plein d'bons trucs qu'j'fais à bon prix.}
{127}{}{T'as tout c'que tu veux ou tu veux aut'chose ?}
{128}{}{Moi vouloir truc ?}
{129}{}{Hmm, fais voir ce que tu as.}
{130}{}{Montre-moi encore une fois ta marchandise.}
{131}{}{Ce sera tout. Merci Percy. Au revoir.}
{132}{}{Moi aller. Salut.}
{133}{}{Cette vieille trousse de médicaments antii-radii-ation ne m'f'rait point d'mal. C'est j'ste un peu tard d'un an pour moi pour l'utiliser. Hé, hé, hé. J'crois année après année, qu'les amis sont très importants. Merci...}
{134}{}{C'est tant mieux si j'ai pu vous aider toi et Woody. Merci pour les médocs.}
{135}{}{Cool, boulot facile bien payé. J'aime ça.}
{136}{}{Ben tu vois, j'avais un ami nommé Woody. Ce Woody, il peut dormir comme personne d'autre. Le pire, c'est qu'il aime les voyages. Il aime vraiment remuer la poussière comme personne.}
{137}{}{Ok.}
{138}{}{Bon, c'est pas vraiment ça l'problème. Le problème il est autour de ça. Tu vois, la dernière fois qu'j'ai vu Woody, l'allait faire un tour à la Fosse. Tu sais où c'est la Fosse ?}
{139}{}{Oui je sais où c'est. Continue.}
{140}{}{En fait, je ne sais pas où c'est la fosse.}
{141}{}{Oh, c'est vraiment facile d'y aller, tiens, j'va t'la marquer d'une croix dans votre petit bloc-notes là.}
{142}{}{Hé, fais-y attention ! Bon, continue maintenant.}
{143}{}{Bon, n'empêche qu'y a pas vraiment de problèmes autour de Gecko. Mais, tu vois, les gens dans les autres endroits, y ne nous ressemblent pas.}
{144}{}{Et alors ?}
{145}{}{Tu vois donc pas où j'veux en venir ? C'est pourtant logique : c'que j'crains c'est que Woody il s'est arrêté faire un p'tit somme quèkpart dans la Fosse, c'est un long chemin après tout. Et si c'est l'cas, ils seraient bien capables de l'enterrer vivant ! J'ai donc besoin de quelqu'un qui veut bien aller le chercher là-bas.}
{146}{}{Et... ?}
{147}{}{Ben, il me manque. Voilà la raison. (Percy cligne de ses yeux humides en te regardant). Oh, j'y suis, tu veux savoir c'que toi t'auras en échange ?}
{148}{}{C'est d'habitude la chose qui m'intéresse le plus. Alors ?}
{149}{}{Ben, j'sais où j'peux m'procurer un tas de Rad-X et d'AntiRad. Me demande ni pourquoi ni comment, mais je crois que ça pourrait servir à une Peaudouce comme toi. Alors, tu vas le faire oui ou non ? J'te paierai que si j'sais que Woody est vivant.}
{150}{}{Et un tas, ça représente quoi au juste ?}
{151}{}{Oui, je le ferai. Je te tiendrai au courant.}
{152}{}{Non, je ne crois pas vouloir t'aider maintenant.}
{153}{}{Laisse-moi y réfléchir. Au revoir.}
{154}{}{C'est bien plus que tu n'auras jamais besoin, voilà ce que c'est. Alors, tu vas le faire ?}
{155}{}{Oui, je le ferai. Je te tiendrai au courant.}
{156}{}{Non, je ne crois pas vouloir t'aider maintenant.}
{157}{}{Laisse-moi y réfléchir. Au revoir.}
{158}{}{Merci de trouver mon ami Woody. Et qu'est c'que l'Vieux Percy peut faire pour toi ?}
