#############################################################
#  Message File: GeckSetl.msg                               #
#                                                           #
#  Created: August 14, 1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

{100}{}{Tu es entré dans une petite installation de Gecko.}
