{100}{}{Tu vois un homme sale. On dirait qu'il dort.}
{101}{}{XXX}
{102}{}{Tu vois un homme sale qui a l'air de dormir. Ses vêtements sont très, TRES, démodés.}
{103}{}{[Il frotte ses paupières.] Que... euh ? Où suis-je ? Depuis quand je dors ?}
{104}{}{Hein ?}
{105}{}{Qui es-tu ?}
{106}{}{Je ne sais pas depuis quand tu dors, mais tu es aux Collines Brisées, près de la République de Nouvelle Californie.}
{107}{}{Oh non ! J'ai tellement dormi que le monde est devenu fou ! [Il s'enfuit de panique.]}
{108}{}{[Terminé]}
{109}{}{Je suis Chuck Stodgers, le meilleur pilote d'avion au monde ! Malheureusement... je me suis écrasé. J'ai atterri dans cette cave pour me protéger de l'explosion, et les fumées m'ont surpris.}
{110}{}{Ca ressemble étrangement au début d'un vieux dessin animé.}
{111}{}{Nouvelle QUOI ? CALIFORNIE ? LE MONDE A TELLEMENT CHANGE ? AIEEEEEEEEEEEEEEEEE ! [Il s'enfuit de panique.]}
{112}{}{Hé, attends un peu...}
{113}{}{Oui, c'est vrai, n'est-ce pas ? Je dois aller voir ce qui est arrivé au monde. Bonne chance, camarade !}
{114}{}{A toi aussi, Stodgers !}
{115}{}{Malgré tout, tu viens de découvrir un grand nom de la culture populaire.}
{116}{}{Zzzzzzzzzzz...}
