{100}{}{Tu vois une femme ayant en permanence une mine renfrognée.}
{101}{}{Tu vois Lise, la gestionnaire du magasin.}
{102}{}{Tu vois une femme d'âge moyen au visage érodé par la mauvaise humeur. On dirait qu'elle fait partie de ces gens qui prennent un plaisir pervers à une vie difficile.}
{103}{}{Salut. Moi c'est Lise. Que veux-tu ?}
{104}{}{Quoi encore ?}
{105}{}{Nggg ! Nnnnnng !}
{106}{}{Moi achder truuUUCS !}
{107}{}{Je voudrais acheter quelque chose.}
{108}{}{Que pouvez-vous me dire à propos de cette ville ?}
{109}{}{J'ai soif de tuer. Y'a quoi dans l'coin ?}
{110}{}{T'en es où pour les armes qui sont dans ta cave ?}
{111}{}{J'ai cru comprendre que tu as un surplus d'armes. J'en veux.}
{112}{}{Rien.}
{113}{}{Oh, mon dieu... Encore un bébé mutant écervelé. Quand va-t-on enfin exterminer ces choses-là ?}
{114}{}{Glouglou.}
{115}{}{Parle doucement et clairement et je verrai ce que je peux pour toi.}
{116}{}{Nn ! Trucs ! Moi !}
{117}{}{Talut !}
{118}{}{Tu veux acheter quelque chose ?}
{119}{}{Oui !}
{120}{}{Non non.}
{121}{}{Ok. Que veux-tu ?}
{122}{}{Troc.}
{123}{}{N'oublie pas le service.}
{124}{}{Marssii !}
{125}{}{Tu veux acheter quelque chose ? Bien. Voilà ce que j'ai.}
{126}{}{Autre chose...}
{127}{}{Merci. A plus.}
{128}{}{C'est une petite ville minière ennuyeuse pleine de toutes sortes d'indésirables. Si tu veux une visite guidée, vois avec Steve par exemple.}
{129}{}{Dis donc, plutôt revêche. J'ai d'autres questions.}
{130}{}{Ok. Au revoir.}
{131}{}{Que voudrais-tu tuer ?}
{132}{}{Des radscorpions, des rats... ce genre de truc, quoi.}
{133}{}{Oh, un humanoïde de temps en temps.}
{134}{}{Toi. Crève, sale gribiche !}
{135}{}{Des sales types.}
{136}{}{Personne. Laisse tomber.}
{137}{}{Qui t'a parlé de ça ?!? Bien sûr que non ! Ne sois pas ridicule !}
{138}{}{Relax. C'est Jacob qui m'a dit.}
{139}{}{Ouais, toute la ville est au courant, c'est un secret de Polichinelle.}
{140}{}{Ton secret ne craint rien. Je l'ai su d'une source digne de confiance.}
{141}{}{Tu pourrais essayer les grottes ou la zone située près des maisons. D'après ce que je sais, il y a plein de monstres par là-bas.}
{142}{}{Merci. Au revoir.}
{143}{}{Des humanoïdes, hein ? Un genre en particulier ?}
{144}{}{Les humains.}
{145}{}{Les Goules.}
{146}{}{Les mutants.}
{147}{}{Je plaisantais.}
{148}{}{Quelle est ta définition d'un sale type ?}
{149}{}{Tous ceux qui me reviennent pas. Surtout les humanoïdes.}
{150}{}{Tous ceux qui se mettent en travers de mon chemin.}
{151}{}{C'est une définition assez fluide.}
{152}{}{Ah bon, si c'est une source de confiance, alors oui. Vas-tu mettre un terme à la domination des mutants ?}
{153}{}{Ouais.}
{154}{}{Non.}
{155}{}{Bon alors je vais commencer par nettoyer dans les coins.}
{156}{}{[Terminé]}
{157}{}{Je ne suis pas pour les tueries dans ce magasin. Sors d'ici.}
{158}{}{Ouais, comme tu veux la gribiche.}
{159}{}{Les Goules sont des esclaves utiles. Ils ont pas beaucoup d'esprit, mais ça vaut pas non plus la peine de les tuer. Je suis contre leur exécution.}
{160}{}{Ok. Je veux autre chose.}
{161}{}{Allez va, salut.}
{162}{}{Si tu veux vraiment massacrer des mutants, tu pourrais peut-être parler à Jacob le chimiste.}
{163}{}{Jacob, hein ? D'accord.}
{164}{}{J'y avais pensé. Maintenant file.}
{165}{}{Certainement.}
{166}{}{Dans ce cas, prends le passage caché dans le plancher de ma chambre et qui mène à la forteresse. J'ai un véritable arsenal là-bas. Vas-y !}
{167}{}{Merci.}
{168}{}{Malheureusement, je me suis débarrassée de toutes mes armes à part ce que tu vois ici. Je peux t'aider pour autre chose ?}
{169}{}{Oui.}
{170}{}{Non.}
{171}{}{Pas question de te vendre quoi que ce soit ! Sors de mon magasin !}
{172}{}{[Terminé]}
{173}{}{Le magasin est fermé. On ouvre à huit heures.}
{174}{}{Hé ! Fiche le camp d'ici !}
{175}{}{Bon, tu l'auras cherché !}
{178}{}{Je m'en tape même si tu tiens l'info de Dieu en personne ! Je vais juste faire en sorte que personne d'autre l'apprenne.}
{179}{}{Hé ! Ne descends pas par là !}
{180}{}{Je ne vais pas le redire. Ne t'approche pas !}
{181}{}{Ca suffit ! Viens ici !}
{182}{}{Que viens-tu m'enquiquiner encore ?}
{183}{}{Merci.}
{184}{}{[Continue]}
{185}{}{Hé ! Qui va là ?}
{186}{}{J'sais pas qui tu es mais j'viens t'chercher !}
{200}{}{Avez-vous quelque chose de spécial que vous souhaiteriez vendre et qui ne serait pas déjà sur les tablettes ?}
{201}{}{En fait... Oui. En voyant ton vieux chien, je me rappelle de quelque chose que j'ai trouvé qui pourrait lui être d'une certaine utilité. Es-tu intéressé par cette armure ? Elle t'en coûtera $2 000.}
{202}{}{Cela sonne bien !}
{203}{}{Non merci, ce chien a déjà ce qu'il lui faut. Merci quand  même. Voyons ce que vous avez d'autre.}
{204}{}{[Elle se penche sur toi et tes amis.] Non, désolée. Je ne pense pas avoir rien de spécial qui pourrait t'être utile. Ce que tu vois ici est tout ce qu'il y a à vendre.}
{205}{}{D'accord. Voyons ce que tu as comme marchandises.}
{206}{}{Je t'ai dit que je te la vendais pour $2 000. Reviens quand tu auras assez d'argent !}
{207}{}{D'accord. Montre-moi ce que tu as.}
{208}{}{Bon. Je serai de retour dans un moment.}
