{100}{}{Tu vois un mutant aux habits poussiéreux avec une pioche.}
{101}{}{Tu vois un mineur mutant.}
{102}{}{Tu vois un mutant aux habits poussiéreux avec une pioche. D'après l'aspect de ses mains et son expression fatiguée, tu penses que ce doit être un mineur. Il a l'air fatigué et un peu troublé.}
{103}{}{Qu'est-ce tu veux ?}
{104}{}{Ag ag ! Ooo !}
{105}{}{Ork ! Oooki !}
{106}{}{Dallo ?}
{107}{}{Dallo !}
{108}{}{Y'a des choses à faire par ici ?}
{109}{}{Qui es-tu ?}
{110}{}{Ah, je vois. T'es débile. Les radiations, hein ? Je ne comprends pas c'que tu dis. J'peux pas t'aider.}
{111}{}{J'ai dit que j'peux pas t'aider ! Tire-toi et va harceler quelqu'un d'autre !}
{112}{}{Qu'est-ce qu'il y a à faire ? Eh bien, la mine est fermée parce qu'on a pas de purificateur d'air qui marche. Il y a le saloon. Il y a les caravaniers, et aussi le magasin. C'est à peu près tout. Attends voir... On en était où ?}
{113}{}{A qui puis-je parler à propos de la mine ?}
{114}{}{Où est le saloon ?}
{115}{}{Où sont les caravaniers ?}
{116}{}{Où est le magasin ?}
{117}{}{Merci. Au revoir.}
{118}{}{A un des mineurs. Tu veux quelqu'un d'important ?}
{119}{}{Oui.}
{120}{}{Non.}
{121}{}{Salut.}
{122}{}{Les personnages influents de la ville sont Marcus, qui est à la fois maire et shérif on va dire, Zaius, le chef de la mine et Chad, qui s'occupe des caravanes. Le tenancier Phil est le chef des Goules, enfin... si on peut dire qu'ils ont un chef. Qui tu es toi déjà ?}
{123}{}{Où puis-je trouver Marcus ?}
{124}{}{Où puis-je trouver Zaius ?}
{125}{}{Où puis-je trouver Cameron ?}
{126}{}{Où puis-je trouver Chad ?}
{127}{}{Où puis-je trouver Phil ?}
{128}{}{Merci. Au revoir.}
{129}{}{Si tu penses que tu peux aider à la mine, va voir Zaius. D'habitude il est dans la cabane du chef de la mine devant la mine. Il est de mauvaise humeur à cause de la panne du purificateur d'air. Autre chose ?}
{130}{}{Phil tient le saloon. C'est un peu le porte-parole des Goules en ville. Tu peux le trouver à l'Est de la banque. Autre chose ?}
{131}{}{Chad s'occupe des caravanes de chez lui dans la partie Sud-Ouest de la ville. Autre chose ?}
{132}{}{Lise, une humaine relativement acceptable. Elle tient le magasin qui s'trouve juste à l'Ouest de la banque. Autre chose ?}
{133}{}{Ok, d'accord. A plus tard.}
{134}{}{Cameron c'est le chef des humains normaux. Il aime pas trop les mutants et les Goules, mais il nous traite pas trop mal. C'est un politicien, tu le trouveras soit à la banque soit au saloon. Parfois tu peux même le trouver au travail chez le maréchal-ferrant. Autre chose ? Et où suis-je, au fait ? Ah ouais... Alors... Autre chose ?}
{135}{}{Marcus c'est notre chef. Il a participé à la fondation des Collines Brisées. Il est en général à la banque ou à la prison. Autre chose ?}
{136}{}{Sale rapace. Tu sais comme on travaille dur ? Va pourrir !}
{137}{}{Merci pour le minerai !}
{138}{}{Je peux pas croire que la mine ait explosé. On va tous mourir de faim. Cette mine était la seule chose qui faisait tourner la ville. Bon, au moins je peux devenir sénile sans travailler...}
{139}{}{Saloperie ! Crève !}
{140}{}{Merci d'avoir réparé la mine. On te doit beaucoup. Que puis-je faire pour toi ?}
{141}{}{Qui es-tu ?}
{142}{}{Qu'y a-t-il à faire dans cette ville ?}
{143}{}{Rien.}
{144}{}{Tu nous as sauvés de ces salauds de la RNC. Merci. On te doit beaucoup. Que puis-je faire pour toi ?}
{145}{}{Qui es-tu ?}
{146}{}{Qu'y a-t-il à faire dans cette ville ?}
{147}{}{Rien.}
