{100}{}{Tu vois un capitaine mercenaire.}
{150}{}{Tu vois un homme à l'apparence bourrue vêtu d'une armure de combat. Son armure et ses armes semblent bien entretenues, presque neuves.}
{151}{}{Tu vois un capitaine mercenaire. Il scrute les environs en tripotant son arme.}
{200}{}{Hé, regarde les balles en cuivre de cette crapule...}
{201}{}{Contact !}
{202}{}{On a un intrus, les gars !}
{203}{}{Remuez-vous, les gars, on a un intrus !}
{204}{}{Hé, on dirait que t'as envie de mourir...}
{205}{}{Merde ! Quelqu'un nous a trouvés !}
{206}{}{T'as du cran de venir ici...}
{207}{}{Garce ! T'as frappé à la *mauvaise* porte !}
{208}{}{Eh bien, regarde le culot de cette salope...}
{215}{}{On ferait mieux d'appeler tout de suite les équipes de tueurs...}
{216}{}{Je crois que l'équipe Bravo est à quelques km au Sud de la Cité de l'Abri... Ils continuent à poursuivre cette caravane.}
{217}{}{Cette brebis galeuse a intérêt à la mettre en veilleuse... Ce genre de merde ne prend pas par ici.}
{218}{}{Il sera bientôt temps d'envoyer des hommes surveiller le périmètre...}
{219}{}{Si seulement on pouvait saboter les canons laser de la Cité de l'Abri...}
{220}{}{On attend toujours des nouvelles de Bishop...}
{221}{}{Ca fait une semaine que Bishop n'a pas envoyé de messager.}
{222}{}{Je pense que la prochaine caravane partira de la RNC pour la Cité de l'Abri...}
{223}{}{Il faudra qu'on soit prêts à partir sur-le-champ.}
{224}{}{J'espère que ces gars ont vérifié qu'il n'y avait pas de pièges.}
{225}{}{Les équipes Alpha et Bravo sont rentrées ?}
