{100}{}{Tu vois un vieillard avec une barbe broussailleuse et un gros nez rouge.}
{101}{}{Tu vois Whiskey Bob.}
{110}{}{Salut, je m'appelle Whiskey Bob. Et toi, quel est ton nom ?}
{111}{}{Quel bout d'chou tu fais ! Je m'appelle Bob, Whiskey Bob. C'est quoi ton p'tit nom ?}
{112}{}{Whicky Gob ? Zou ?}
{113}{}{Nez luisant. [Hé ! Hé !]}
{114}{}{Moi }
{115}{}{[Partir]}
{120}{}{T'as pas inventé le fil à couper le beurre toi, hein ? Bah, on a quand même fait un brin de causette. Allez, salut !}
{121}{}{Mon lapin, tu me fends le coeur chaque fois que tu ouvres la bouche. Peut-être que la prochaine fois je t'emmènerai à Trapper Town et je te montrerai mes estampes japonaises [Hé, hé]. Salut ma poule.}
{130}{}{Eh bien, j'espère te revoir prochainement par ici. Au revoir.}
{131}{}{J'espère revoir bientôt ta petite frimousse dans le coin. Au revoir.}
{140}{}{Hum ! Si tu ne veux pas être mon compagnon de beuverie, alors va voir ailleurs si j'y suis.}
{141}{}{Hum ! Je ferais mieux d'aller aux Bains chez Sally plutôt que de perdre mon temps avec toi. Allez, ouste !}
{150}{}{Salut ! Je m'appelle Whiskey Bob. Et toi ?}
{151}{}{Je m'appelle }
{152}{}{.}
{153}{}{Je m'appelle }
{154}{}{. Que peux-tu me dire sur cette ville ?}
{155}{}{Tu n'as pas besoin de connaître mon nom.}
{160}{}{C'est toujours agréable de rencontrer un compagnon de bar. Tu me paies un verre ? Parler me donne toujours soif.}
{161}{}{Bien sûr, Bob. Pas de problème.}
{162}{}{J'ai pas les moyens en ce moment.}
{163}{}{J'ai pas envie de te payer un verre, Whiskey Bob.}
{164}{}{Avec un nom comme le tien, c'est plutôt toi qui devrais payer ta tournée.}
{170}{}{Merci pour le verre. Maintenant que j'ai plus le gosier sec, j'ai envie de partager un de mes soucis. Tu pourras peut-être m'aider ?}
{171}{}{Ben, tu sais, j'ai pas mal de trucs à faire en ce moment. Je ne crois pas pouvoir t'aider.}
{172}{}{Que puis-je faire pour toi ?}
{173}{}{Si ça ne prend pas trop de temps, je peux peut-être t'aider. Contre une petite rémunération, bien sûr.}
{174}{}{Je peux sans doute t'aider, si c'est pas trop dangereux.}
{175}{}{Se passe-t-il des choses bizarres en ville ?}
{180}{}{On dirait que ton porte-monnaie est à sec. Tu n'as pas assez d'argent pour offrir un verre à ce bon vieux Bob.}
{181}{}{[Plus]}
{190}{}{Alors voilà : je tiens un petit commerce et j'ai besoin que quelqu'un me donne un petit coup de main. J'ai une distillerie clandestine à l'extérieur de la ville qui a besoin d'être alimentée de temps à autre. Un gecko m'a mordu la jambe, et je ne peux pas y aller. Si je t'indiquais l'endroit où elle se trouve, irais-tu la ravitailler ? Selon moi, c'est un service qui vaut $50.}
{191}{}{Ca m'a l'air honnête... Je t'écoute.}
{192}{}{Je regrette Whiskey mais je ne peux pas te rendre ce service.}
{200}{}{Ecoute, ça ne te prendra pas longtemps et ce n'est absolument pas dangereux. Enfin, je crois pas. Tu veux en savoir plus ?}
{201}{}{Ouais, vas-y je t'écoute.}
{202}{}{Je pense en avoir assez entendu. Au revoir.}
{210}{}{Très bien ! T'as l'esprit vif toi, pas de doute. Tiens, bois donc un p'tit coup. En échange, j'vais te parler d'un p'tit problème que j'ai.}
{220}{}{Tout ce que tu dois faire, c'est trouver une cabane au Sud de la ville. Tu rentres, et tu mets des bûches dans la chaudière de l'alambic. Ensuite, reviens ici et je te donnerai ton argent. Mais il faut que ce soit fait avant demain, sinon ma cuvée sera foutue.}
{221}{}{Ca m'a pas l'air bien compliqué. Bon ben c'est d'accord.}
{222}{}{Je regrette Bob mais je n'ai pas envie de t'aider.}
{223}{}{$50, c'est pas cher payé pour ce genre de boulot.}
{230}{}{Tu es d'accord ? Super. Mais souviens-toi : il faut faire vite, sinon je perds ma cuvée. Merci encore et à bientôt !}
{231}{}{Pas de problème, Bob. Allez, à demain.}
{232}{}{Ca me fait plaisir de t'aider. Mais avant, dis-moi un peu ce qu'il se passe en ville.}
{240}{}{Eh bien ! T'es du genre pas facile en affaires toi, pas de doute. Bon eh bien, disons $65. C'est d'accord ?}
{241}{}{Ce boulot ne vaut pas plus de $50. Je ne peux pas me permettre de te payer plus.}
{242}{}{C'est d'accord.}
{243}{}{Ce n'est pas assez cher payé pour moi. Mon temps vaut plus que ça.}
{250}{}{Salut, mon pote ! Tu reviens voir ton vieux copain Whiskey Bob, hein ? Tu es prêt à discuter alcool, affaires et autre ?}
{251}{}{Salut, poulette. Tu veux taper une causette avec Whiskey Bob sur l'alcool, les affaires eh bien d'autres choses encore ? Viens t'asseoir sur mes genoux ! Hé, hé, c'était pour rire.}
{252}{}{Bien sûr, Bob. Parle-moi de l'alcool et des affaires.}
{253}{}{J'ai assez donné la dernière fois.}
{260}{}{Tu as rempli ma chaudière ? Non, je ne crois pas que ce soit déjà fait. Reviens quand tu auras fait ce que je t'ai demandé.}
{270}{}{Quelqu'un a bousillé mon alambic ! Y'a qu'à toi à qui j'en avais parlé ! Si j'étais plus jeune, et complètement bourré, je te filerais une sacrée raclée !! Hors de ma vue, sale traître !}
{280}{}{Merci d'avoir rempli ma chaudière. Maintenant, je n'ai plus à m'inquiéter. Tiens, voilà tes $50. Tu as des questions à me poser ?}
{281}{}{Merci. Ca m'aura coûté 65 $ mais au moins ça m'évite d'y aller avec ma patte folle... Tiens, voilà ton argent. Tu as des questions à me poser ?}
{282}{}{Oui, dis-moi un peu ce qui se passe en ville en ce moment.}
{283}{}{Non, merci Bob. Je sais tout ce que je dois savoir pour le moment.}
{290}{}{Il se passe des tas de choses dernièrement. Il y a des }
{291}{}{Parle-moi des mutilations de Brahmines.}
{292}{}{Parle-moi des Esprits ambulants.}
{293}{}{Des rats géants ? J'aimerais en savoir plus.}
{294}{}{Une fosse ? Quelle genre de fosse ?}
{295}{}{Des disparus ?}
{296}{}{Je veux te demander autre chose. As-tu déjà entendu parler d'un Jardin d'Eden en Kit ?}
{297}{}{Je n'ai pas besoin d'entendre tout ça pour le moment.}
{298}{}{Ouais bien sûr, Bob, et moi je vais te raconter l'histoire du poisson aussi grand que moi que j'ai pêché dans un tonneau d'eau de pluie.}
{310}{}{Merci de m'avoir aidé. Je m'occuperai de ma distillerie quand ma jambe sera guérie. Tu as des questions à poser à un vieux pilier de bar comme moi ?}
{311}{}{J'ai entendu des rumeurs en ville et je me pose des questions.}
{312}{}{Je n'ai pas besoin d'autres renseignements pour l'instant.}
{320}{}{Il paraît que des bêtes qui ressemblent à des insectes humanoïdes géants et recouverts d'une carapace, mutilent les Brahmines pendant la nuit. On retrouve leurs cadavres le ventre ouvert, affreusement mutilés.}
{321}{}{C'est horrible !}
{330}{}{Plusieurs personnes ont vu les Hommeinsectes, mais c'est Torr, le fils de Buckner, qui en a vu le plus et de plus près. Ce qu'il a vu lui a presque fait perdre la tête, déjà qu'il est un peu limite de ce côté là !}
{331}{}{C'est dingue ça ! Je voudrais te poser une autre question...}
{332}{}{J'ai pas envie d'en entendre plus pour l'instant. Au revoir.}
{340}{}{Y'a un canyon à l'Ouest de la ville. Y'a quelques mois, une lumière vive s'est mise à briller dans le canyon et depuis, de temps à autre, on entend des couinements horribles qui viennent du canyon. Les Brahmines qui s'égarent ne reviennent jamais. Tout le monde a la frousse de s'en approcher.}
{341}{}{Oui, c'est sûrement infesté d'esprits. Dommage que vous ayez pas un shaman compétent. Mais dis-moi...}
{342}{}{Ca suffit pour le moment. Je vais cogiter là-dessus pendant quelque temps. Au revoir.}
{350}{}{A l'extérieur de Trapper Town, à l'Ouest du centre-ville, y'a un un coin reculé qui est infesté par des rats. Plus tu t'enfonces, plus ils deviennent gros. On dit même qu'ils obéissent à l'esprit du Grand Rat. Certains trappeurs ne veulent même plus rester là-bas. Ils disent que c'est trop dangereux.}
{351}{}{Des trappeurs chassés par des rats ? Parle-moi d'autre chose.}
{352}{}{Hum ! C'est sûrement pas les mêmes rats que ceux qu'il y a chez moi. J'en ai assez entendu. Au revoir.}
{360}{}{Pas *une fosse*, mais *La Fosse*. C'est un bas-fond, un vrai repaire d'ordures. J'ai déjà entendu ça quelque part... C'est un endroit reculé à quelques jours au Sud de Klamath. Là-bas, tout s'achète... même des esclaves. Et puis, il faut faire gaffe, il y en a qui ont la gâchette facile. Je ne crois pas qu'ils nous cherchent, nous sommes trop pauvres.}
{361}{}{Ici, je serai en sécurité. Je sais me débrouiller. Laisse-moi te poser une autre question.}
{362}{}{J'en ai assez entendu comme ça. Au revoir.}
{370}{}{Dernièrement, certaines personnes ont disparu. Comme Vic, un marchand spécialisé dans les objets d'avant-guerre. Et puis aussi un de nos meilleurs trappeurs.}
{371}{}{Parle-moi encore de ce marchand qu'on appelle... Vic.}
{372}{}{J'aimerais en savoir plus sur le trappeur.}
{373}{}{J'ai encore une question.}
{374}{}{C'est tout ce que je voulais savoir. Au revoir.}
{380}{}{Vic c'est un sacré lascar. Il aimait pas trop travailler, alors il s'est spécialisé dans les objets d'avant-guerre qui coûtent cher évidemment. Il allait les vendre à la Fosse ou les refilait à ces idiots de tribals euh... [Il glousse] Oh, pardon, ne le prends pas mal... Je disais donc qu'il les refilait aux tribals persuadés d'acheter des artefacts sacrés. Ca fait un moment que j'l'ai pas vu. Tout ce que je sais, c'est qu'il est parti vers le Sud vendre ses trucs. Peut-être bien à la Fosse.}
{381}{}{Que sais-tu du trappeur disparu ?}
{382}{}{J'aimerais te poser une autre question, Bob.}
{383}{}{Merci, je vais réfléchir à ce que tu m'as raconté. Au revoir, Whiskey Bob.}
{390}{}{Tu devrais aller parler à Mme Buckner. Elle était très proche de Souriant. Il est parti vers le Nord chercher la grotte des geckos dorés et il n'est pas revenu depuis. Ca fait déjà un moment.}
{391}{}{Parle-moi encore de ce marchand qu'on appelle... Vic.}
{392}{}{Hum ! Intéressant. Dis-moi encore quelque chose.}
{393}{}{Ca suffit pour le moment. Au revoir, Whiskey Bob.}
{400}{}{J'aurais préféré que tu tiennes ta promesse. T'as pas été à la distillerie à temps et par ta faute ma dernière cuvée est complètement foutue ! Je ne veux plus jamais te revoir et j'espère ne plus jamais entendre parler de toi. }
{401}{}{Mais, je croyais avoir plus de temps...}
{402}{}{Qu'on ravitaille la chaudière ou non, ça ne doit pas faire une grande différence de goût.}
{403}{}{Ta gnôle, c'est du pipi de chat.}
{404}{}{Il semblerait que le combustible n'ait pas fourni une flamme suffisante pour augmenter la température et permettre la fermentation.}
{410}{}{J'ai pas envie d'entendre tes excuses bidon ! Hors de ma vue ! Et laisse-moi te dire une bonne chose : tant que je vivrai, je dirai à tout le monde que tu n'as pas de parole.}
{420}{}{Un J.E.K ? J'ai déjà vu ce nom écrit dans les pages d'un vieux catalogue que je feuilletais assis là-bas... Mais j'en sais pas plus que ça.}
{421}{}{C'est vrai ? J'aimerais voir ce catalogue.}
{430}{}{Heu... [Gêné.] J'ai utilisé cette page pour autre chose, si tu vois ce que je veux dire.}
{431}{}{Autre chose ? Ah, oui... Personnellement, je préfère le papier journal. Bon eh bien, parle-moi d'autre chose.}
{432}{}{Dommage, j'étais si près du but. J'ai eu assez de déceptions pour le moment. Au revoir, Bob.}
{500}{}{Salut. Que puis-je faire pour toi ?}
{501}{}{Que s'passe-t-il ici ?}
{502}{}{Rien. Merci.}
{550}{}{On dirait que Bob n'a pas envie de te parler.}
{2900}{}{Les choses se sont ralenties récemment. Pas grand-chose à te dire.}
{2901}{}{mutilateurs de Brahmines}
{2902}{}{Esprits ambulants}
{2903}{}{rats géants}
{2904}{}{villageois portés disparus}
{2905}{}{. Certains disent que la Fosse y est pour quelque chose.}
