{100}{}{Tu vois de la substance collante toxique.}
{101}{}{Tu vois de la substance collante toxique.}
{110}{}{Aïe, ça brûle.}
{120}{}{Ces vieilles bottes en caoutchouc évitent d'avoir un dépôt gluant.}
{130}{}{Tes bottes viennent de fondre.}
{140}{}{Tes pieds commencent à brûler et à te démanger.}
{150}{}{Tes pieds commencent vraiment à brûler et ils te démangent pendant un moment. Ensuite, ça va mieux.}
