{100}{}{Tu vois un vieil homme.}
{101}{}{Tu vois Cornélius.}
{102}{}{Mis à part l'expression quelque peu perturbée de son visage, il a l'air tout à fait normal.}
{150}{}{Bienvenue à l'Auberge de Rose. Je m'appelle Rose, euh... j'veux dire... Cornélius... c'est moi qui m'occupe de l'Auberge. Que puis-je faire pour toi ?}
{151}{}{Si c'est toi qui diriges cette maison, pourquoi l'appelle-t-on l'Auberge de Rose ?}
{152}{}{Je cherche une montre en or.}
{153}{}{Qu'est-ce tu fais ici ?}
{154}{}{Qui est Rose ?}
{155}{}{Je voudrais une chambre.}
{156}{}{Des questions ? T'ai-je demandé quelque chose moi ? Je m'appelle Cornélius.}
{162}{}{Mon vieux, tu as besoin qu'on s'occupe de toi.}
{163}{}{Farrel a mis ta montre dans son coffre mural. Allons le pendre.}
{164}{}{J'ai trouvé ta montre chez Farrel. Tu avais raison, c'est bien lui le voleur.}
{165}{}{Je crois qu'un rat très industrieux s'est emparé de ta montre. Je lui ai repris.}
{166}{}{Bonjour ! On s'est déjà rencontré, non ?}
{176}{}{Quelqu'un a tué Farrel ! C'était mon meilleur ami !! Toute la ville recherche le meurtrier. Quand on l'aura attrapé, on le lynchera !}
{177}{}{C'est moi qui l'ai tué. Alors, que vas-tu faire maintenant, espèce de vieux fou ?}
{178}{}{Oh là là ! J'avais pas vu l'heure. Il faut que j'y aille.}
{179}{}{Rose c'est ma femme. J'ai donné son nom à l'auberge. Tu savais que j'étais marié ?}
{180}{}{Puis-je te poser encore quelques questions ?}
{181}{}{Alors, pourquoi ne demandes-tu pas à ce porc de Farrel ? Peut-être qu'il te vendra la montre qu'il m'a volée ! Et maintenant, si ce n'est pas trop te demander, j'ai beaucoup à faire. Je dois raser la Brahmine.}
{182}{}{Je suis le patron de l'auberge. C'est sûr que sans moi y aurait jamais rien de fait ici. As-tu jeté un oeil aux toilettes ? Les plus propres que tu aies jamais vues. C'est mon travail.}
{183}{}{Qu'est-ce que la propreté des toilettes a à voir avec la direction de cette auberge ?}
{184}{}{Rose c'est ma femme. Elle s'occupe de la cuisine. Tu trouveras des plats aussi bons nulle part ailleurs. Elle est si belle Rose. Un jour je l'épouserai.}
{185}{}{Mais, tu viens de me dire que c'est ta femme !!}
{186}{}{J'ai une chambre. J'y dors. Et toi, tu dors où ?}
{187}{}{Je crois que tu n'as pas compris. Je voudrais une chambre pour la nuit.}
{188}{}{Il y a pas mal de temps, j'ai oublié quand, mon meilleur ami depuis 30... ou peut-être 40 ans... Oh, ça n'a plus d'importance. Ce qui est important, c'est qu'il a volé ma montre de gousset en or, un vrai bijou. Elle a été transmise de père en fils dans ma famille pendant 5, euh, non, 6, euh, je veux dire 4 générations. Je me rappelle bien l'avoir mise sur mon bureau. Et quand j'ai regardé sur la table de la cuisine, elle avait disparu.}
{189}{}{D'accord, je vais te ramener ta montre.}
{190}{}{L'as-tu cherchée sur ton bureau ?}
{191}{}{Tu vas m'aider ? C'est fantastique ! Va mettre une bonne raclée à Farrel et ramène-moi ma montre. Il l'a probablement bien cachée. N'hésite pas, retourne toute sa baraque s'il le faut mais trouve-la.}
{192}{}{De quoi parles-tu ?}
{193}{}{Ecoute, je ne veux pas me mêler de ça.}
{194}{}{Tuer Farrel, reprendre la montre... C'est compris ! Je reviens tout de suite.}
{195}{}{Tuer Farrel ! Qui va tuer Farrel ? C'est mon meilleur ami. Je pendrai moi-même haut et court le vaurien qui essaie de le tuer !}
{196}{}{J'accepte le boulot et j'entends bien à ce qu'on me paie quand il sera terminé.}
{197}{}{Je ne peux plus supporter ça. Je m'en vais.}
{198}{}{Bien sûr que je vais te payer. Dès que tu auras fini de nettoyer la grange, viens me voir.}
{199}{}{J'ai une montre. C'est une montre en or. Je me demande où je l'ai mise...}
{200}{}{Oui, oui, oui. J'ai regardé dans mon tiroir à chaussettes. Elle n'y est pas non plus.}
{201}{}{Je continuerai à chercher ta montre pendant que je serai en ville.}
{202}{}{Il n'est pas question que j'aide un vieux fou de ton genre. Je m'en vais.}
{203}{}{Je savais que je ne pouvais pas lui faire confiance. Je m'en vais le pendre par les oreilles jusqu'à ce qu'il me rende ma montre !}
{204}{}{Il n'y a rien ici. Le Shérif Jo et moi avons déjà regardé.}
{206}{}{C'est bien lui ? Je le savais ! Je vais lui donner une leçon qu'il n'oubliera jamais. Tu ferais mieux de rester ici ou tu risquerais de prendre des coups.}
{207}{}{Ma montre ! Que fais-tu avec ma montre ? Rends-la moi ! [Il t'arrache la montre des mains.] Tu ferais mieux de partir, nous n'aimons pas les voleurs ici.}
{208}{}{Ca alors, tu parles d'une gratitude !}
{209}{}{As-tu goûté aux omelettes de Rose ? Elles sont succulentes.}
{210}{}{J'ai vu Jonny jouer près du puits avec son chien Laddie. Quel gentil garçon !}
{211}{}{Ne va pas à la ferme perdue si tu as encore envie de vivre.}
{212}{}{Miria est une fille bien. Nous avions l'habitude de jouer au docteur quand elle était petite.}
{213}{}{David est un gentil garçon. Je me demande pourquoi il ne ressemble pas à son père.}
{214}{}{Un jour, j'étais aux toilettes quand un gros chien a surgi des égouts. J'ai cru mourir de peur.}
{215}{}{Grisham est un bon gars. Il nous vend des restes pour nourrir la poule géante.}
{216}{}{N'approche pas de la basse-cour ! J'ai failli perdre un bras en donnant à manger à cette créature !}
{217}{}{Les chiens de Rose sont vicieux. Ce que j'fais, je leur jette des bouts de viande et ils font plus attention à moi.}
{218}{}{Pour moi, Farrel c'est le meilleur ami du monde.}
{219}{}{Laddie est un chien intelligent. Je lui parle sans arrêt.}
{220}{}{J'ai entendu dire que Grisham essaie de marier ses enfants. Je me demande si Rose accepterait que j'aie une autre femme.}
{222}{}{La belote ? Qu'est-il advenu ce jeu ? Bon, je dois partir. On pourra peut-être jouer plus tard.}
{223}{}{J'AI TROUVE LE MEURTRIER ! IL A AVOUE LE MEURTRE DE FARREL ! ALLONS L'ARRETER !}
{224}{}{J'AI TROUVE LA MEURTRIERE ! ELLE A AVOUE LE MEURTRE DE FARREL ! ALLONS L'ARRETER !}
{225}{}{Moi tuer Farrel.}
{300}{}{[Hmmm... Certains mots semblent le mettre en colère.] Rose... chambre... courir...}
{301}{}{Ooga.}
{501}{}{J'ai toujours su que tu étais un voleur.}
{502}{}{Comment as-tu pu faire une chose pareille à ton meilleur ami ?}
{503}{}{Je vais te tuer !}
{504}{}{Je vais faire empailler ta tête et l'accrocher dans mon salon !}
{550}{}{Il a l'air inquiet.}
{600}{}{Tu as rapporté la montre à Cornélius.}
{650}{}{Tu as réglé le problème de Cornélius et Farrel.}
