{100}{}{Elle ressemble à un colley.}
{101}{}{Tu vois Laddie.}
{102}{}{Ce chien a l'air très vif et intelligent.}
{103}{}{Il n'y pas de doute, ce chien est sûrement plus malin que toi.}
{150}{}{Wouaf !}
{151}{}{Wouaf ! Wouaf !}
{152}{}{Ouaf ! Ouaf ! Ouaf !}
{153}{}{[Ce chien a l'air particulièrement agité.]}
{154}{}{T'es un bon toutou toi.}
{155}{}{Tu sais où est Jonny ?}
{156}{}{Stay here, Laddie.}
{157}{}{Allons chercher Jonny.}
{158}{}{Laddie, Jonny est-il tombé dans le puits ?}
{159}{}{Que se passe-t-il ? Tu essaies de me dire quelque chose ?}
{160}{}{Grrrr ! [Laddie te mord de toutes ses forces.]}
{161}{}{[Hmm... Le chien n'a pas l'air de t'aimer... Va savoir pourquoi.]}
{162}{}{Ouaf ! Ouaf ! Ouaf ! [Laddie te saute dessus et te lèche le visage.]}
{163}{}{[Quel bon toutou.]}
{164}{}{Ouaf ? [Tu peux presque entendre le rire du chien qui se moque de toi.]}
{165}{}{[Personne n'aime les grandes gueules.]}
{167}{}{Jonny est-il quelque part à proximité de Modoc ?}
{168}{}{Jonny a-t-il quitté Modoc ?}
{169}{}{Jonny a-t-il été enlevé par des extraterrestres ?}
{170}{}{J'ai pas le temps de jouer, Laddie. Nous devons trouver Jonny. Allons-y !}
{171}{}{Près de l'abattoir ?}
{172}{}{Près de la tannerie ?}
{173}{}{Près du poste d'approvisionnement ?}
{174}{}{Près du puits ?}
{175}{}{Peut-être à un autre endroit alors ?}
{177}{}{Près de l'Auberge de Rose ?}
{180}{}{Il est parti vers le Nord ?}
{181}{}{Il est parti vers le Sud ?}
{182}{}{Il est parti vers l'Est ?}
{183}{}{Il est parti vers l'Ouest ?}
{186}{}{Ouaf ?}
{187}{}{Ok, Ok... Peut-être ailleurs alors ?}
{190}{}{Il jouait aux cow-boys et aux indiens quand il est tombé accidentellement dans le puits et tu veux que j'aille chercher une corde pour descendre le chercher. Ok, on y va Laddie. [Incroyable !]}
{191}{}{Il jouait aux cow-boys et aux indiens quand il est tombé accidentellement dans le puits et tu veux que j'utilise ma corde pour descendre le chercher. Ok, on y va Laddie. [Incroyable !]}
{195}{}{Ok, je vais aller chercher une corde pour descendre dans le puits et secourir Jonny.}
{196}{}{Ok, je vais utiliser ma corde pour descendre dans le puits et secourir Jonny.}
