{100}{}{Tu vois l'un des Frères Corses.}
{150}{}{Tu vois un homme bien habillé qui sent la Vaseline. Bizarrement, il te fait penser à un reptile.}
{151}{}{Tu vois Marty, l'un des Frères Corses. Ses cheveux sont noirs et gominés. Son visage est recouvert d'un léger voile de sueur.}
{152}{}{Tu vois Sid, l'un des Frères Corses. Il porte une perruque et des lunettes de soleil.}
{200}{}{Hé, }
{201}{}{}
{202}{}{Yo, }
{210}{}{Comment fais-tu pour aller aux toilettes avec ce truc ?}
{211}{}{C'est une sorte de vibromasseur, ou quoi ?}
{212}{}{C'est quoi ça, un nouveau préservatif corporel ?}
{220}{}{Ton tempérament est plus éruptif qu'un volcan en activité.}
{221}{}{Tu es une star. Une étoile FILANTE.}
{222}{}{Tu es une star. Une étoile JAILLISSANTE.}
{223}{}{Tu es une star. Une étoile PALPITANTE.}
{224}{}{Tes exploits valent une centaine de triques.}
{225}{}{}
{226}{}{Tu es une star. Une étoile étincelante !}
{227}{}{Hé, ça fait plaisir de te revoir.}
{228}{}{Viens faire un brin de causette avec moi.}
{229}{}{Parle-moi du boulot.}
{230}{}{Reviens me voir !}
{231}{}{Tu vois ce que je vois ? La plus sexy de tous les canons de ce monde !}
{232}{}{}
{233}{}{Hé, ça fait plaisir de te revoir, ô ma belle aux tétons d'or !}
{245}{}{Oh-oh. Une huile. Tout le monde se dresse.}
{246}{}{Bonjour, }
{250}{}{Hé, Hercule, la bombe sexuelle !}
{251}{}{Vise un peu ces pectoraux !}
{252}{}{Tu as déjà pensé à faire carrière, }
{253}{}{Tu pourrais faire quelques scènes, si tu voulais. Penses-y, d'accord ?}
{254}{}{Tu as un joli style de combat. Et au lit, t'es comment ?}
{255}{}{Reviens quand tu veux. Ecoute, si tu veux parler affaire...}
{256}{}{Ecoute, }
{257}{}{Reviens me voir !}
{258}{}{Vas-y, Xena !}
{259}{}{Quels jolis abdos ! On dirait un trampoline.}
{270}{}{On en a trop, esclavagiste.}
{271}{}{Ces esclaves sont à moi. Attention les yeux !}
{275}{}{Heu, joli robot-chien, mais on ne fait pas ce genre de photo. Pas encore.}
{276}{}{Ce robot-chien est-il propre ?}
{280}{}{Ha ! Regarde les fils sur ce robot !}
{281}{}{C'est un de ces vibromasseurs robotisés dont on parle ?}
{282}{}{Ton robot est-il intéressé par le cinéma ?}
{290}{}{Ecoute, fais-moi sortir d'ici ton ami mutant. On ne fait pas ce genre de film ici.}
{291}{}{Franchement, je ne pense pas qu'une seule de nos actrices puisse s'occuper de ton mutant.}
{292}{}{On a déjà fait un film avec un mutant. Il a bouffé toutes nos actrices.}
{300}{}{Nom de nom ! Fais-moi sortir d'ici cette Goule infecte avant que ça ne commence à puer.}
{301}{}{On ne tourne pas avec les Goules. Sors-la d'ici.}
{302}{}{<Pouah> Cette Goule pue comme c'est pas croyable ! Vite, un désodorisant, je m'évanouis.}
{310}{}{Il n'y a plus de lumière...}
{311}{}{Qu'est-ce que ça peut foutre que la perche soit dans la prise de vue ?}
{312}{}{On peut se concentrer sur notre trésor, s'il vous plaît ?}
{313}{}{Le tournage dure trop longtemps. Je me ruine à payer des nanas moi !}
{314}{}{Il veut QUOI ?! Dis-lui d'aller se faire voir chez les Brahmines !}
{315}{}{Le temps des implants, c'était le bon temps...}
{316}{}{On va tuer le budget.}
{317}{}{J'ai adoré Diggler.}
{318}{}{Ce type, c'est de la dynamite en bâton !}
{319}{}{Je ne vais PAS te filmer comme ça !}
{320}{}{C'est un missile ! Une fusée ! Il décolle, Sid, j'te jure !}
{321}{}{Tu l'as dit bouffi !}
{322}{}{Dis à ce salaud d'aller se faire foutre !}
{323}{}{Ecoute, si cette tapette se montre encore une fois...}
{324}{}{Merci-oui-ouiiii m'dame.}
{325}{}{Ca c'est le bouquet...}
{326}{}{Rien à péter.}
{327}{}{Va le dire à cette tapette de fils de pute ! Dis-lui...}
{328}{}{Et ensuite, il a pris des chattes.}
{329}{}{C'est pas mon problème. C'est le *tien*.}
{330}{}{20 minutes, mon chou.}
{331}{}{Alors... ::Il vérifie le script:: Randy entre... Il ramone Sylvia... Christy va dans la salle de bain, Peter la rejoint... Ils baisent. Ron entre...}
{345}{}{Les Frères Corses, pour vous servir... [Il te regarde d'abord énervé, puis surpris.] Hé, c'était toi tout à l'heure... Tu voulais un petit rôle de nana, c'est ça ?}
{346}{}{Les Frères Corses, pour vous servir... [Il te regarde, l'air énervé.] Encore toi ! Ecoute, tu veux faire la nana oui ou non ?}
{347}{}{Les Frères Corses, pour vous servir... [Il te regarde, l'air énervé puis te regarde une deuxième fois.] C'est TOI la nouvelle nana ?}
{348}{}{Les Frères Corses, pour vous servir... [Il te regarde, l'air énervé.] C'est toi le nouvel acteur ?}
{349}{}{Moi ananas.}
{350}{}{Moi pas ananas ! Moi en a là-d'dans.}
{351}{}{[Partir]}
{353}{}{C'est moi.}
{354}{}{En fait, c'est ma femme.}
{356}{}{Non. Je viens chercher le fric de Big Jésus Mordino.}
{357}{}{Non. Je m'excuse pour le dérangement.}
{358}{}{Nooooon. Excuse le dérangement.}
{370}{}{D'accord, petite cervelle. C'est payé 5... heu, 3 jetons par prise. Va huiler le bâton du gars dans la salle du fond.}
{371}{}{Le bâton... quelle andouille !}
{372}{}{Fais ce qu'on te dit.}
{380}{}{Attention quand tu l'ouvres !}
{381}{}{Je parle de Bâton !}
{390}{}{::Il lève les mains en l'air:: C'est possible.}
{391}{}{Va huiler son bâton.}
{400}{}{Hum. Tu t'allonges pour combien ?}
{401}{}{Hum. T'es aussi forte que t'en as l'air, tétons d'or ?}
{402}{}{Moi allonger.}
{403}{}{Moi pas allonger, moi faire la femme.}
{404}{}{Moi tétons d'argent.}
{405}{}{Moi forte.}
{415}{}{Très bien, mon pote. Je sais d'où tu viens, et je sais aussi EXACTEMENT où tu vas. Tu aimes le cinéma ?}
{416}{}{Très bien, tétons d'or. Je sais d'où tu viens, et je sais aussi EXACTEMENT où tu vas aller. Tu aimes le cinéma ?}
{417}{}{Moi aimer faire trucs.}
{418}{}{Quel genre de cinéma ?}
{425}{}{C'est vrai ? Moi aussi ! Nous avons déjà tellement de choses en commun ! Regarde, ici, c'est un studio, on fait de la MAGIE. Tu...}
{426}{}{Toi, mon pote, tu peux faire PARTIE de cette magie !}
{427}{}{Toi, tétons d'or, tu peux faire PARTIE de cette magie !}
{428}{}{D'accord, je marche.}
{429}{}{Magie ! Magie ! Moi aimer magie !}
{435}{}{Sois comme une BETE, un rhinocéros, un animal primitif, dont les pulsions sexuelles sont exploitées pour le plaisir des masses ! C'est ça la MAGIE dont je te parle !}
{436}{}{Sois comme une BETE, un lynx, un animal primaire, dont le DESIR profond est d'exciter les pulsions sexuelles des masses ! C'est ça la MAGIE dont je te parle !}
{445}{}{SEXcellent ! C'est le moment de faire un essai. Je veux voir comment tu chevauches.}
{446}{}{Tu es prêt mon pote ?}
{447}{}{Tu es prête tétons d'or ?}
{448}{}{C'est bon.}
{455}{}{Alors, c'est parti ! Pas de temps à perdre ! Hé ! Faites venir un figurant ! }
{456}{}{Mon pote, c'est le moment de te surpasser... }
{457}{}{Tétons d'or, c'est le moment de te surpasser... }
{458}{}{[Fais ce que le drôle de bonhomme te dit...] }
{459}{}{Attends ! T'as encore RIEN vu ! }
{465}{}{Je regrette, mon pote, t'es pas assez SOUPLE pour satisfaire nos besoins. Entraîne-toi et on en reparlera, d'accord.}
{466}{}{Je regrette, tétons d'or, t'es pas assez SOUPLE pour satisfaire nos besoins. Entraîne-toi et on en reparlera, d'accord.}
{467}{}{Moi AIMER travailler ici. Moi revenir.}
{468}{}{<Sniff> D'accord. <Sniff> Moi me sentir objet.}
{469}{}{Je vais travailler ma souplesse. A une prochaine fois, peut-être.}
{470}{}{Je reviendrai peut-être. Après une douche. Une longue douche.}
{475}{}{Désolé, mon vieux. Tu es superbe, tu es souple comme il faut, mais t'as pas, heu, l'endurance nécessaire. Entraîne-toi un peu, et on en reparlera, d'accord ?}
{476}{}{Désolé, ma jolie. Tu es superbe, tu es souple comme il faut, mais t'as pas, heu, l'endurance nécessaire. Entraîne-toi un peu, et on en reparlera, d'accord ?}
{479}{}{Je vais travailler mon endurance. A une prochaine fois, peut-être.}
{485}{}{Désolé, mon vieux. Tu es superbe, tu es souple, t'as l'endurance d'une Brahmine, mais tu manques encore un peu d'expérience. On a pas le temps de te former.}
{486}{}{Désolé, ma jolie. Tu es superbe, tu es souple, t'as l'endurance d'une Brahmine, mais tu manques encore un peu d'expérience. On a pas le temps de te former.}
{489}{}{Je vais travailler mon, heu, *expérience*. A une prochaine fois peut-être.}
{495}{}{Mon vieux, c'était fan-tas-tique !}
{496}{}{Tétons d'or, c'était fan-tas-tique !}
{497}{}{Tu étais magnifique, absolument magnifique ! Ce que tu as fait, ça valait MILLE triques ! Tu veux tourner un film avec nous ? Allez, viens discuter, mon chou, viens DISCUTER !}
{498}{}{D'accord... Moi parler avec toi. Moi vouloir faire trucs encore et encore.}
{499}{}{Non-on. Moi vouloir partir. Moi sentir sale dedans.}
{500}{}{Ca m'intéresse. Mon prix : 200 jetons... la prise.}
{501}{}{Ca m'intéresse. Mais selon certaines conditions. Premièrement, je ne travaille qu'avec des acteurs CLEAN. Je veux au moins 500 jetons par prise, des royalties de 20% et pas d'EMBROUILLES. Je suis une star et tu le sais.}
{503}{}{Pas question. Je veux prendre une douche. Une longue douche.}
{515}{}{[Il tire un bout de papier de son blouson, et te fait griffonner un « X » dessus.] C'est fait ! On tourne ! D'abord, il te faut un nom de scène, un truc qui en jette. Tu as une idée ?}
{516}{}{[Il tire un bout de papier de son blouson, et t'invite à griffonner ta signature.] C'est fait ! On tourne ! D'abord, il te faut un nom de scène, un truc qui en jette. Tu as une idée ?}
{517}{}{Bon, et si on te trouvait un autre nom ?}
{525}{}{Je... Hum... Je... Hum... Ecoute, c'est d'accord pour les 500 jetons, mais PAS DE ROYALTIES. Ok ?}
{526}{}{D'accord.}
{527}{}{Pas question. Salut.}
{528}{}{Pas de royalties.}
{535}{}{D'accord ! }
{536}{}{Achtung ! Achtung !}
{537}{}{Au boulot.}
{545}{}{Hé... pas ce nom, d'accord ? Con-notations. On peut pas avoir un nom pareil dans un porno digne de ce nom. Trouves-en un autre, d'accord ?}
{546}{}{D'accord...}
{547}{}{Mais moi vraiment AIMER nom}
{548}{}{Mais j'aime beaucoup ce nom.}
{555}{}{Voilà un nom si éclatant et si mordant, SI EXPLOSIF... c'est puissant ! Bien choisi, mon pote, bien choisi. Maintenant, on TOURNE ! Lumières ! Caméra ! Moteur !}
{556}{}{Ah, voilà un nom qui sent le vécu, et la magie. Bien choisi, mon pote, bien choisi. Maintenant, on TOURNE ! Lumières ! Caméra ! Moteur !}
{557}{}{Ah, voilà un nom derrière lequel on sent la magie. Bien choisi, tétons d'or, bien choisi. Maintenant, on TOURNE ! Lumières ! Caméra ! Moteur !}
{558}{}{Voilà un nom si éclatant et si mordant, SI EXPLOSIF... c'est puissant ! Bien choisi, tétons d'or, bien choisi. Maintenant, on TOURNE ! Lumières ! Caméra ! Moteur !}
{565}{}{D'accord ! D'accord ! On y va ! Allez ! Un peu d'entrain ! Tout le monde est prêt ?}
{566}{}{Moi prêt pour l'aventure.}
{567}{}{J'attends que ça !}
{575}{}{Très bien, mon volcan. C'est tout pour aujourd'hui. Eblouissante performance ! EBLOUISSANTE ! Quelle prise ! Parfait ! Si tu veux en tourner d'autres, reviens nous voir dans un mois. D'accord ?}
{576}{}{Très bien, tétons d'or. C'est tout pour aujourd'hui. Eblouissante performance ! EBLOUISSANTE ! Si tu veux en tourner d'autres, reviens nous voir dans un mois. D'accord ?}
{577}{}{D'accord... Salut.}
{585}{}{Coupez ! Très bien, mon vieux.}
{586}{}{Coupez ! Très bien, ma chérie.}
{587}{}{C'est dans la boîte. C'était EBLOUISSANT !}
{588}{}{Quelle prise !}
{589}{}{Quel charme !}
{590}{}{Parfait ! Voilà ta paie : }
{591}{}{200 jetons.}
{592}{}{500 jetons.}
{593}{}{Si tu veux en tourner d'autres, reviens nous voir dans un mois. D'accord ?}
{594}{}{D'accord.}
{610}{}{Tu te fous de ma gueule ? Si tu veux savoir, t'es PAS le genre de personne qu'il nous faut. Que veux-tu ?}
{612}{}{Un boulot, hein ? Eh ben, je suis LA nana de l'emploi. La meilleure nana dans le métier.}
{613}{}{Hum, rien. J'ai dû me tromper d'endroit.}
{620}{}{Où avais-je la tête ? La crème de la crème se présente ici et moi je bafouille comme un idiot ! Excuse-moi, mon pote. Ecoute, hum, tu cherches du boulot ? C'est pas de la camelote, c'est un vrai travail d'ACTEUR, tu vois ?}
{621}{}{Où avais-je la tête ? La crème de la crème se présente ici et moi je bafouille comme un idiot ! Excuse-moi, tétons d'or. Ecoute, hum, tu cherches du boulot ? C'est pas de la camelote, c'est un vrai travail d'ACTRICE, tu vois ?}
{622}{}{D'abord, c'est quoi ici ?}
{623}{}{Ca m'intéresse si la paie est réglo.}
{630}{}{Bon. Va dans la pièce du fond. Commence à huiler les bâtons. Tiens, voilà ta paie : 5 jetons.}
{631}{}{[Fais ce qu'il te dit]}
{632}{}{Hum, non, merci, j'ai changé d'avis. Je ferais mieux de partir.}
{640}{}{Ta femme, hein ? Hum... D'accord. Envoie l'élue de ton coeur au fond et dis-lui d'astiquer les bâtons. Voici la paie : 3 jetons.}
{641}{}{Davin mon chou, fais ce qu'il te dit, allez vas-y.}
{642}{}{Miria, ma douce, fais ce qu'il te dit, IMMEDIATEMENT.}
{650}{}{Ici ? Tu plaisantes ? Voici les studios de TOURNAGE des Golden Globes, les seuls de New Reno, et probablement les SEULS qui ont encore la frite. Tu ne reconnais pas ton propre foyer ? C'est vexant !}
{651}{}{Ce sont les studios de tournage des Golden Globes, mon pote, les seuls de New Reno, et probablement les SEULS qui ont encore la frite ! Bon, tu vas me chauffer les oreilles encore longtemps ? Tu cherches du boulot ?}
{652}{}{Ce sont les studios de tournage des Golden Globes, tétons d'or, les seuls qui existent à New Reno, et probablement les SEULS qui ont encore la frite ! Bon, tu vas me chauffer les oreilles encore longtemps ? Tu cherches du boulot ?}
{653}{}{Ces vieux trucs ? Ce sont les studios de tournage des Golden Globes, les SEULS qui ont encore la frite dans ce monde. Mais parlons d'autre chose. Tu cherches du boulot, mon pote ? On a BESOIN de nouveaux talents comme toi.}
{654}{}{Ces vieux trucs ? Ce sont les studios de tournage des Golden Globes, les SEULS qui ont encore la frite dans ce monde. Mais parlons d'autre chose. Tu cherches du boulot, chérie ? }
{655}{}{Comment fais-tu un film ? Je sais bien qu'il faut des caméras, des pellicules, des projecteurs... où trouves-tu tout ça ?}
{657}{}{Non, merci. Je dois partir.}
{658}{}{Juste pour savoir. Je sens comme une espèce de vide en moi dernièrement.}
{670}{}{On a eu de la veine ! Pas besoin de ce matos préhistorique. On est tombé sur un projecteur porno... heu, holo...graphique qui FONCTIONNE ! Pas d'équipement encombrant, pas d'histoires... et pas de désordre disgracieux.}
{671}{}{Ah bon ? Quelles sont les caractéristiques techniques ?}
{672}{}{Je vois... Bon, écoute, je cherche du boulot, si tu as toujours quelque chose à proposer...}
{673}{}{Ca m'a fait plaisir de te parler, mais il faut que je parte.}
{680}{}{Bon, on n'a pas encore atteint la capacité maximale du lecteur QUB, mais je peux te dire que ça fait un cube d'environ 300 Go de mémoire haute densité. Même si le système d'exploitation Winblows 57 consomme entre 70 et 75%, on pourrait filmer encore pendant 100 ans.}
{681}{}{Où il est le cube ? Je peux le voir ?}
{683}{}{Eh, ça fait PAS MAL de pornos. Je crois que je vais y réfléchir.}
{690}{}{Non, on évite de faire venir les gens sur le tournage... Sinon chacun veut mettre son grain de sel pendant le montage et le rangement. En plus, le cube, c'est de l'or pour nous. Je ne voudrais pas que quelque chose lui arrive.}
{692}{}{C'est logique. Dieu seul sait ce qu'un voleur pourrait faire avec ce cube s'il s'en emparait ! Enfin... Salut !}
{700}{}{SEXcellent ! Bien sûr, il faut que je vois ce que tu vaux, et comment tu *chevauches*. T'es d'accord, mon pote ?}
{701}{}{SEXcellent ! Bien sûr, il faut que je vois ce que tu vaux, et comment tu *chevauches*. T'es d'accord, chérie ?}
{702}{}{Certainement.}
{703}{}{Heu, non, merci. J'ai changé d'avis. Une autre fois peut-être.}
{710}{}{Alors, casse-toi, petite merde ! On n'a pas besoin de toi ! Barre-toi ! Tu ne travailleras plus jamais dans le porno !}
{711}{}{Moi pas vouloir toute façon ! VOILA ! Na !}
{712}{}{Va te faire voir ! T'es pas mon patron. C'est moi le patron de }
{720}{}{Casse-toi. J'ai rien à te dire.}
{721}{}{On n'a plus rien à se dire. Va-t'en.}
{730}{}{Hé, ça fait plaisir de te revoir, }
{732}{}{Mais avant, tu peux me parler un peu du studio ?}
{733}{}{Ca fait plaisir de te l'entendre dire. Je viens chercher le fric de Big Jésus Mordino.}
{734}{}{D'accord. A bientôt.}
{735}{}{::Clin d'oeil:: Toi, mon chou, tu vaux de l'or !}
{740}{}{Les Frères Corses pour vous servir... [Le type lève les yeux et sourit.] Hé, quel plaisir de te revoir, }
{743}{}{Exact. Allons casser quelques lattes.}
{745}{}{Pas exactement. Je viens chercher le fric de Big Jésus Mordino.}
{746}{}{Pas de problème.}
{755}{}{Quoi ? Tu veux PLUS le faire ?! T'es TROP BIEN pour nous, c'est ça ? Maintenant que tu as ce que tu voulais, }
{756}{}{Moi pas oublier, toi pas en colère sinon moi triste, moi revenir mais partir maintenant.}
{758}{}{[Ignore-le et barre-toi]}
{759}{}{T'excite pas ! J'ai pas envie de tourner aujourd'hui, c'est tout ! Je reviendrai plus tard quand tu auras retrouvé ton calme.}
{760}{}{Allez-vous faire foutre. J'ai pas besoin de cette merde de Brahmine. Je suis une star ! Une superstar !}
{765}{}{Hé... ça va ? T'as pas l'air dans ton assiette. T'as pas pris des trucs au moins ? Je te FAIS PAS tourner dans cet état.}
{766}{}{Moi vouloir filmer MAINTENANT petite personne.}
{768}{}{T'es pas mon patron ! J'ai envie de sexe, c'est ma queue, alors tout le monde en place ! On filme MAINTENANT !}
{769}{}{T'es pas mon patron ! J'ai envie de sexe, c'est ma chatte, alors tout le monde en place ! On filme MAINTENANT !}
{770}{}{D'accord. Je reviendrai plus tard quand je serai moins speed.}
{780}{}{Les Frères Corses pour vous servir... [Le type te regarde d'abord énervé, puis surpris.] Sacré nom... }
{781}{}{Pour moi ! Pour moi !}
{782}{}{Rien.}
{783}{}{Où suis-je ici ?}
{784}{}{Tu peux me parler un peu du studio ?}
{785}{}{Il n'y aurait pas quelques... ouvertures à... combler ?}
{786}{}{Tu as du boulot pour quelqu'un comme moi ?}
{787}{}{Je viens chercher le fric de Big Jésus Mordino.}
{788}{}{Rien. Je m'excuse de t'avoir dérangé.}
{795}{}{Les studios Golden Globes accueillent les seuls talents qui restent en ce monde. Et toi, tu pourrais devenir une STAR, tu vois ce que je veux dire ? Tu veux faire du cinéma ?}
{797}{}{Bien sûr. C'est sérieux ?}
{799}{}{Pas pour le moment. Je regrette de t'avoir dérangé.}
{805}{}{Oh que oui ! Tu vas faire un bout d'essai. Hé ! Faites venir des figurants ! On a une star ici !}
{806}{}{Fais ce que ce type te dit.}
{810}{}{Les Frères Corses pour vous servir... [Le type te regarde d'abord énervé, puis surpris.] Sacré nom... heu, comment vas-tu, }
{812}{}{Que dalle.}
{813}{}{Où suis-je ici ?}
{814}{}{Fais-moi plaisir. Parle-moi de ce studio.}
{815}{}{Bonne question. Il n'y aurait pas quelques... ouvertures à... combler ?}
{816}{}{Bonne question. T'as du boulot pour quelqu'un comme moi ?}
{825}{}{Les studios Golden Globes accueillent les seuls talents qui restent en ce monde. Alors... heu, que puis-je faire pour toi ?}
{827}{}{Tu vas me faire passer une audition ? Je crois que je peux devenir une star, tu me suis ?}
{829}{}{Rien pour aujourd'hui. Je regrette de t'avoir dérangé.}
{835}{}{Heu, bien sûr. Tu vas faire, heu, un essai. Qu'on voit un peu ce que tu vaux. Tu sais, on est débordés, mais tu feras un bout d'essai, d'accord ? Heu... Faites venir des figurants ! Allez, on se dépêche !}
{836}{}{Fais ce que ce type te dit.}
{845}{}{Heu, bien sûr ! Et voilà. 250 jetons. Et, heu, passe le bonjour à Big Jésus de ma part, hein ?}
{846}{}{Heu, bien sûr ! Je regrette, c'était un malentendu. Et voilà. 250 jetons. Et, heu, passe le bonjour à Big Jésus de ma part, hein ?}
{847}{}{Avant qu'on me foute à la porte, tu veux pas me parler de ton opération, petit cachottier !}
{848}{}{Ouais, peut-être. A plus tard, mon pote.}
{855}{}{Les Frères Corses pour vous servir... [Il lève les yeux.] Encore toi. Tu cherches encore du travail, Monsieur-la-Turbine ?}
{856}{}{Les Frères Corses pour vous servir... [Il lève les yeux.] Encore toi. Tu cherches encore du travail, Mademoiselle-la-Turbine ?}
{857}{}{Les Frères Corses pour vous servir... [Il lève les yeux.] Que t'est-il arrivé ? Je veux dire, c'est bon, c'est bon... J'ai dû louper quelque chose. Tu voulais jouer un petit rôle de nana, c'est ça ?}
{861}{}{Heu, de quoi tu parles ?}
{862}{}{Ouais. Il y a encore du boulot pour moi ?}
{875}{}{Les Frères Corses pour vous servir... [Il lève les yeux.] Tu as réfléchi à ma proposition ? Hein ?}
{876}{}{Les Frères Corses pour vous servir... [Il lève les yeux.] Hé ! Tu veux faire un autre bout d'essai ? C'est ça ?}
{877}{}{Les Frères Corses pour vous servir... [Il lève les yeux.] Tu as réfléchi à ma proposition ? Tu veux le refaire, pour voir si t'as encore le feeling ? Hein ?}
{879}{}{Dac-cord.}
{881}{}{Oui. J'ai changé d'avis. Qu'est-ce que je fais, je dégaine ou... ?}
{882}{}{Oui. J'ai changé d'avis. Qu'est-ce que je fais, je tombe la culotte ou... ?}
{895}{}{...j'ai entendu parler de tes X-ploits... quand tu as explosé tous les membres de l'Enclave. Tu as des tripes toi.}
{896}{}{Ouais.}
{897}{}{Non.}
{899}{}{Heu, pas tous les membres de l'Enclave. En fait, ce qui s'est passé...}
{900}{}{Je ferais mieux de partir.}
{910}{}{Ne sois pas modeste. Ca a dû chier. La plupart des gens n'en auraient pas eu les tripes. Mais tu as ravalé ton orgueil et tu as fait ce qu'il fallait. C'est ça être une star.}
{911}{}{Ouais.}
{914}{}{Heu, écoute, je n'ai pas explosé tous les membres de l'Enclave...}
{915}{}{Je ferais mieux de partir.}
{920}{}{Tu sais à quoi je pense, }
{921}{}{Un héros, }
{922}{}{Ouais.}
{924}{}{Youpi-youpi. Tchaaao.}
{926}{}{Bien sûr. Pourquoi pas. J'ai fini ce jeu. Allons-y.}
{927}{}{Su-per ! Merci...}
{928}{}{Laisse-moi d'abord enregistrer la partie. Ensuite, je reviendrai peut-être.}
{935}{}{Ruinés. Nous sommes ruinés.}
{936}{}{Sans ce cube, nous sommes ruinés.}
{937}{}{Oh, Dieux du sexe, pourquoi tant de cruauté ! Quelle offense avons-nous commise pour que vous nous enleviez le cube ?}
{938}{}{::Soupir:: Sans le cube, il ne nous reste plus qu'à ouvrir un club de macramé.}
{1000}{}{Moi sentir mal-mal dans ventre.}
{1001}{}{Tu sens un goût infect et malsain dans la bouche, et tu as mal à l'estomac. Mais, 3 jetons, c'est 3 jetons !}
{1100}{}{Argh ! ::Crachat:: C'est DEGUEULASSE !}
{1101}{}{Tu sens un goût infect et malsain dans la bouche, et tu as mal à l'estomac. Mais, 5 jetons, c'est 5 jetons !}
{1200}{}{Je... ne me sens pas bien.}
{1201}{}{L'amour triomphe toujours. Ta femme a l'air d'une morte, mais au moins, tu t'es enrichi de 3 jetons !}
{1250}{}{Tu es une star. Une grande star !}
{5200}{}{ ! C'est la star qu'on voulait voir !}
{5201}{}{, notre star, nous voulons te proposer un marché !}
{5202}{}{ ! On a entendu parler de ce que tu as fait à l'Enclave ! Maintenant, que peut-on faire pour TOI ?}
{5225}{}{ vaut de l'or !}
{5232}{}{ ! Mon chou ! Tétons d'or !}
{5246}{}{. Belle journée, n'est-ce pas ?}
{5252}{}{ ?}
{5256}{}{, si tu voulais tourner avec nous...}
{5528}{}{ se casse de ce studio de merde !}
{5535}{}{ J'AIME CA ! J'AIME CA ! Allez, on tourne }
{5641}{}{ avec fierté.}
{5712}{}{ !}
{5730}{}{ ! On ne tourne pas aujourd'hui, mais reviens bientôt.}
{5740}{}{ ! Tu vas à un nouveau tournage ?}
{5755}{}{ ! Et ne l'oublie pas !}
{5780}{}{ ?! Pourquoi tu te pointes que maintenant ? Belle bagarre au fait ! Super ! Que puis-je faire pour toi ? }
{5810}{}{ ?! Comment va le Patron }
{5920}{}{ ? Je pense à un film inspiré de tes X-ploits. Ca pourrait s'appeler « Folles out : Débandade post-nucléaire ». Tu es d'accord ? Hein ?}
{5921}{}{. Un vrai héros. Je vais pas oublier toute la merde que tu as dû avaler pour nous. Et une fois qu'on touchera le jackpot, le monde entier aussi saura.}
{6535}{}{ ! Lumière ! Caméra ! Moteur !}
{6810}{}{ ? Fais comme chez toi ! Alors, que puis-je faire pour toi ?}
