{100}{}{Tu vois une nana.}
{150}{}{Tu vois une femme assez attirante. Elle semble te dévisager.}
{151}{}{Tu vois une nana. Elle semble hésiter à s'occuper de toi.}
{160}{}{Tu vois une femme assez attirante. Elle te dévisage comme si tu étais son adversaire.}
{161}{}{Tu vois une nana. Elle te dévisage comme si tu étais son adversaire.}
{200}{}{Oh mon dieu... C'est lui.}
{201}{}{Tu es le plus grand tombeur au monde.}
{202}{}{Vas-y, ma fille !}
{203}{}{J'ai entendu que les frères te cherchaient. Ils veulent tourner un film basé sur ton aventure.}
{204}{}{Ouais, }
{205}{}{::Applaudissements::}
{206}{}{::Acclamations::}
{207}{}{Oh mon dieu... C'est elle. }
{208}{}{Bravo, ma belle !}
{209}{}{::Lève le pouce et te fait signe::}
{225}{}{Il n'est pas QUESTION que je rate ça !}
{226}{}{Comment fais-tu pour aller aux toilettes avec ce truc ?}
{227}{}{C'est une sorte de vibromasseur, ou quoi ?}
{228}{}{C'est quoi ça, un nouveau préservatif corporel ?}
{235}{}{Besoin de quelque chose, }
{236}{}{Par ici, }
{237}{}{Regardez ! C'est lui !}
{238}{}{C'est }
{239}{}{J'aimerais tellement tourner une scène avec }
{240}{}{Ce mec est vraiment la crème de la crème.}
{241}{}{Il peut me fouetter avec son sexe quand il veut.}
{242}{}{Un vilain petit crochet de cobra que tu as là.}
{245}{}{Besoin de quelque chose, }
{246}{}{Si je dois encore m'occuper d'un acteur aujourd'hui, je vais vomir.}
{247}{}{Ce n'est pas facile d'être une nana.}
{248}{}{J'ai entendu dire que la situation redevenait tendue entre les Familles.}
{249}{}{J'ai frappé Jules dans les bijoux de famille la semaine dernière.}
{250}{}{J'espère que les frères me laisseront jouer.}
{251}{}{Je ne vois vraiment pas ce que les frères Corses ont VU en elle...}
{255}{}{Oh mon dieu... C'est lui.}
{256}{}{Regarde-moi ces muscles ! Je suis toute faible à côté...}
{257}{}{Il est monté comme un taureau. Regarde un peu cette masse.}
{258}{}{Regardez-moi ce tas de muscles...}
{259}{}{Il est à moi...}
{260}{}{::Soupire::}
{261}{}{Ce mec est vraiment la crème de la crème.}
{262}{}{Un vilain petit crochet de cobra que tu as là.}
{270}{}{Oh mon dieu... C'est elle. }
{271}{}{Bienvenue au studio, Madame.}
{272}{}{Elle est trop... ::Frissonne:: ... dangereuse.}
{273}{}{Elle est bien gaulée.}
{274}{}{Bonjour, m'dame. Dis-moi si je peux t'aider en quoi que ce soit.}
{280}{}{Oh mon dieu... C'est lui.}
{281}{}{Bienvenue au studio, Monsieur.}
{282}{}{Il est trop... ::Frissonne:: ... dangereux.}
{283}{}{Ca c'est un dur à cuire ou je ne m'y connais pas.}
{284}{}{Ce mec est vraiment la crème de la crème.}
{285}{}{Un vilain petit crochet de cobra que tu as là.}
{290}{}{Oh mon dieu... C'est elle. }
{291}{}{Bienvenue au studio, Madame.}
{292}{}{Elle est trop... ::Frissonne:: ... dangereuse.}
{293}{}{Elle est bien gaulée.}
{294}{}{Bonjour, m'dame. Dis-moi si je peux t'aider en quoi que ce soit.}
{300}{}{Oh, merde. C'est Myron ! Cours !}
{301}{}{Merde ! C'est Myron. Reste cool... Il peut sentir la peur.}
{302}{}{Tu as intérêt que Myron ne s'approche pas de moi.}
{303}{}{Tu as intérêt que Myron ne s'approche pas de moi.}
{304}{}{Si Myron travaille ici, je me casse.}
{305}{}{Myron, tu as déjà dépassé la barre des cinq secondes ?}
{306}{}{Myron, tu as intérêt à te barrer avant que les frères te voient.}
{315}{}{Ces timbrés en cuir ne savent pas qu'ils sont supposés être là les mercredis ?}
{316}{}{Super. Encore un rôle SM.}
{317}{}{Oooooh. Cuir noir. CA c'est nouveau.}
{318}{}{On ne fait ni cuir ni chaînes avant la semaine prochaine.}
{319}{}{Super, encore un lapin en cuir.}
{320}{}{Regarde, un lapin en cuir, le casting est le mercredi, pas vrai ?}
{325}{}{Si je dois encore m'occuper d'un acteur aujourd'hui, je vais vomir.}
{326}{}{Ce n'est pas facile d'être une nana.}
{327}{}{J'ai entendu dire que la situation redevenait tendue entre les Familles.}
{328}{}{J'ai frappé Jules dans les bijoux de famille la semaine dernière.}
{329}{}{Le type qui a un os entre les narines est plutôt mignon. D'un point de vue sadomasochiste en tout cas.}
{330}{}{Qui c'est le type avec un os dans le nez ?}
{331}{}{Vise un peu le tribal qui a un os entre les narines. Ah, il ira loin !}
{332}{}{Woa, J'en ai vu des accidents sur le plateau, mais jamais un mec qui s'était coincé un os dans le nez.}
{333}{}{J'espère que les frères me laisseront jouer.}
{334}{}{::Foudroie du regard::}
{335}{}{Super. Une AUTRE poupée. Rien qu'à la regarder on voit qu'elle travaillera sûrement à moitié prix.}
{336}{}{Qui c'est ?}
{337}{}{Qui es-tu ?}
{345}{}{Si je dois encore m'occuper d'un acteur aujourd'hui, je vais vomir.}
{346}{}{Ce n'est pas facile d'être une nana.}
{347}{}{J'ai entendu dire que la situation redevenait tendue entre les Familles.}
{348}{}{J'ai frappé Jules dans les bijoux de famille la semaine dernière.}
{349}{}{J'espère que les frères me laisseront jouer.}
{350}{}{Super. Une AUTRE poupée. Rien qu'à la regarder on voit qu'elle travaillera sûrement à moitié prix.}
{351}{}{::Foudroie du regard::}
{352}{}{Qui c'est ?}
{353}{}{Qui es-tu ?}
{360}{}{L'Enclave ? Le président ? Raconte-moi toute l'histoire.}
{361}{}{Tom French m'a scénarisée. Avec ces mains douces et agréables.}
{362}{}{Ils étaient toujours en GUERRE ?! Vraiment ! T'as eu raison de défoncer ces enfoirés.}
{363}{}{T'es un sacré dur à cuire. Dire que de simple tribal fabricant de lance, sans offense, tu en viens à sauver le monde. Tu défonces tout. Point final.}
{364}{}{Tu devrais recommencer le jeu avec un autre type de personnage.}
{365}{}{Raconte-moi tout sur cette bataille contre l'Enclave. Je vais te chercher une bière fraîche.}
{366}{}{J'ai entendu que les frères te cherchaient. Ils veulent tourner un film basé sur ton aventure.}
{370}{}{Ouuups. J'ai laissé tomber quelque chose dans ton futal. Laisse-moi aller le récupérer.}
{371}{}{Hum, tu ne voudrais pas sortir prendre un verre ? Sinon, ça te dirait un petit coup rapide ?}
{372}{}{Comment fais-tu pour rester si mince ?}
{373}{}{Je peux avoir un autographe ? Sur la poitrine ?}
{374}{}{Tu as été aidé, }
{375}{}{J'aurais besoin de l'aide d'une baraque dans ton genre.}
{376}{}{J'ai entendu que tu étais... très dur... dans ton travail.}
{377}{}{J'ai entendu que quand tu te mettais en rogne, après tu te *rapprochais* des autres. Ca me va.}
{378}{}{Je suis vraiment heureuse de te connaître ! Je veux dire, wao, tu es... }
{379}{}{Hum, je sais qu'aucun film n'est en tournage, mais si tu as quand même envie d'une pipe...}
{380}{}{Besoin que quelqu'un prenne soin de ça pour toi ?}
{381}{}{Besoin, d'un minou... humide, }
{382}{}{Je t'ai adoré dans "Tant qu'il y aura des couilles".}
{383}{}{Je t'ai adoré dans "Blanche-Fesse et les 7 mains".}
{384}{}{Je t'ai adoré dans "Les Sex Mercenaires".}
{385}{}{Tu étais génial dans "L'abri Sex-ième". Trèèèès *inspiré*.}
{386}{}{Je n'ai pas vu les frères dans le coin... essaie le bureau peut-être ?}
{387}{}{Y'aurais moyen que tu parles aux frères Corsican pour qu'ils me fassent tourner ?}
{388}{}{Les suceuses ont la tâche ardue de *maintenir* le moral des acteurs *en forme*.}
{389}{}{Je pourrais jouer dans ton prochain film ?}
{390}{}{Je ne veux pas rester suceuse toute ma vie. Non, vraiment.}
{391}{}{Je fais juste ça pour payer mes études.}
{392}{}{Mon mec ne sait pas que je bosse ici.}
{393}{}{Mon turbin ? Je t'en parlerai une autre fois.}
{394}{}{Mon mec ne sait pas que je bosse ici.}
{395}{}{J'aimerais que certains acteurs prennent une douche. Je veux dire, régulièrement...}
{396}{}{Je veux vraiment jouer.}
{397}{}{Ma copine ne sait pas que je bosse ici.}
{398}{}{Je peux avoir un autographe ?}
{399}{}{Hum, ça te dirait d'aller boire un coup ? Si tu aimes les femmes, bien sûr...}
{400}{}{::T'ignore::}
{420}{}{Tu veux sauter le pas avec moi, champion ?}
{421}{}{Belle unité que tu as là.}
{422}{}{Besoin que quelqu'un prenne soin de ça pour toi champion ?}
{423}{}{Passer de la boxe au porno ? En fait, il s'agit toujours de mettre des coups.}
{424}{}{Tu te lances dans les affaires aussi ? Bienvenue à bord champion.}
{425}{}{Tu te lances dans les affaires ? Ok, au moins tu n'auras pas besoin de commencer au même point que moi.}
{426}{}{Moi ? Je suis une suceuse. Parfois.}
{427}{}{Les suceuses ont la tâche ardue de *maintenir* le moral des acteurs *en forme*.}
{428}{}{Les frères disent que je ne suis pas vendable. Ca doit être pour ça qu'ils couchent autant avec moi.}
{429}{}{Tu devrais faire du porno. Tu as le corps qu'il faut pour ça.}
{430}{}{Tu veux fourrer ?}
{431}{}{Mon turbin ? Je t'en parlerai une autre fois.}
{432}{}{Fais gaffe au Mastiquateur. C'est un vrai crétin. Il a essayé de me bouffer l'oreille une fois.}
{433}{}{Salut, m'dame. Je peux fait quelque chose pour toi...*n'importe quoi* ?}
{434}{}{Um, Si tu cherches de la compagnie à plus, ma'am...}
{435}{}{La même chose que d'habitude m'dame ?}
{450}{}{Bonjour, beau gosse. Je peux faire quelque chose pour toi... *n'importe quoi* ?}
{451}{}{Si tu cherches de la compagnie plus tard...}
{452}{}{La même chose que d'habitude m'sieur ?}
{453}{}{Besoin que quelqu'un prenne soin de ça pour toi ?}
{454}{}{Tu peux glisser un mot sympa sur moi au patron ?}
{455}{}{Tu penses à te lancer dans le business aussi ?}
{456}{}{Tu devrais faire du porno. Tu as le corps qu'il faut pour ça.}
{457}{}{Mon turbin ? Je t'en parlerai une autre fois.}
{458}{}{Salut, m'dame. Je peux fait quelque chose pour toi...*n'importe quoi* ?}
{459}{}{Um, Si tu cherches de la compagnie à plus, ma'am...}
{460}{}{La même chose que d'habitude m'dame ?}
{465}{}{Non merci, je regrette. J'aurais plus de plaisir avec mon rouge à lèvres.}
{466}{}{Toi ? Désolé, je ne serais JAMAIS aussi en désespérée.}
{467}{}{Heu, ton ami qui a un os entre les narines essaie-t-il de compenser un manque ?}
{468}{}{Ton ami, celui qui a un os entre les narines, il est pris ?}
{469}{}{Ton ami, celui qui a un os entre les narines, il est plutôt mignon. Dans le genre sadomasochiste.}
{470}{}{C'est qui ton ami si mignon, celui avec un os entre les narines ?}
{471}{}{Dis au tribal avec l'os dans le nez qu'il pourrait aller loin dans cette industrie.}
{472}{}{Woa, J'en ai vu des accidents sur le plateau, mais jamais un mec qui s'était coincé un os dans le nez.}
{473}{}{Je n'ai pas vu les frères dans le coin... essaie le bureau peut-être ?}
{474}{}{Les suceuses ont la tâche ardue de *maintenir* le moral des acteurs *en forme*.}
{475}{}{Je veux vraiment jouer.}
{476}{}{Je ne veux pas rester suceuse toute ma vie. Non, vraiment.}
{477}{}{Mon mec ne sait pas que je bosse ici.}
{478}{}{Besoin d'un *coup de main* ?}
{479}{}{Si tu cherches du boulot, parles-en aux frères.}
{480}{}{Je fais juste ça pour payer mes études.}
{481}{}{J'ai baisé gratos avec Avellone.}
{482}{}{Ce n'est pas que je ne veuille pas te parler, mais... attends qu'est-ce que c'est que CA ?!}
{483}{}{J'ai besoin de m'allonger.}
{484}{}{Mon turbin ? Je t'en parlerai une autre fois.}
{485}{}{Tu n'as rien contre les vidéos pornos, n'est-ce pas ?}
{486}{}{Tu es la nouvelle suceuse ?}
{487}{}{Quelqu'un a-t-il une serviette ? Un des acteurs a eu un... accident.}
{488}{}{Ne mords pas les acteurs, et tout se passera bien.}
{489}{}{J'aimerais que certains acteurs prennent une douche. Je veux dire, régulièrement...}
{490}{}{Hum, c'est la première fois que tu viens ici, hein ?}
{491}{}{C'est vraiment pas bon mais on s'y fait.}
{500}{}{Non merci, je regrette. J'aurais plus de plaisir avec mon rouge à lèvres.}
{501}{}{Toi ? Désolé, je ne serais JAMAIS aussi en désespérée.}
{502}{}{Je n'ai pas vu les frères dans le coin... essaie le bureau peut-être ?}
{503}{}{Les suceuses ont la tâche ardue de *maintenir* le moral des acteurs *en forme*.}
{504}{}{Je veux vraiment jouer.}
{505}{}{Je ne veux pas rester suceuse toute ma vie. Non, vraiment.}
{506}{}{Mon mec ne sait pas que je bosse ici.}
{507}{}{Besoin d'un *coup de main* ?}
{508}{}{Si tu cherches du boulot, parles-en aux frères.}
{509}{}{Je fais juste ça pour payer mes études.}
{510}{}{J'ai baisé gratos avec Avellone.}
{511}{}{Ce n'est pas que je ne veuille pas te parler, mais... attends qu'est-ce que c'est que CA ?!}
{512}{}{J'ai besoin de m'allonger.}
{513}{}{Mon turbin ? Je t'en parlerai une autre fois.}
{514}{}{Tu n'as rien contre les vidéos pornos, n'est-ce pas ?}
{515}{}{Tu es la nouvelle suceuse ?}
{516}{}{Quelqu'un a-t-il une serviette ? Un des acteurs a eu un... accident.}
{517}{}{Ne mords pas les acteurs, et tout se passera bien.}
{518}{}{J'aimerais que certains acteurs prennent une douche. Je veux dire, régulièrement...}
{519}{}{Hum, c'est la première fois que tu viens ici, hein ?}
{520}{}{C'est vraiment pas bon mais on s'y fait.}
{1200}{}{. La personne qui a donné une leçon à l'Enclave.}
{1204}{}{ ! C'est comme ça qu'on donne une leçon à l'Enclave !}
{1207}{}{. La personne qui a donné une leçon à l'Enclave.}
{1235}{}{ ?}
{1236}{}{ !}
{1238}{}{ !}
{1239}{}{.}
{1245}{}{ ?}
{1255}{}{.}
{1270}{}{.}
{1280}{}{.}
{1290}{}{.}
{1374}{}{ ?}
{1378}{}{ !}
{1381}{}{ ?}
