{150}{}{Tu vois un homme maigre à l'air affamé. Son regard est hagard, et il a une barbe de plusieurs jours.}
{151}{}{Tu vois Lloyd Beau Gosse.}
{152}{}{Tu vois Lloyd Beau Gosse. Il te regarde avec méfiance.}
{200}{}{Faut que j'quitte la ville...}
{210}{}{Qui es-tu ? Que fais-tu là ?!!}
{211}{}{Encore toi ?!! Que fais-tu là ?!!}
{212}{}{Oh rien mon chou.}
{213}{}{Moi }
{214}{}{[Partir]}
{215}{}{Mais que fais-tu là TOI ?}
{216}{}{Calme-toi, camarade, APRES on pourra parler. Tout va bien ?}
{217}{}{C'est toi Lloyd ? Lloyd Beau Gosse ?}
{218}{}{Rien. Je visite. Salut.}
{225}{}{Ouais, ben tire-toi. Et dis à personne que tu m'as vu, c'est compris ?}
{226}{}{Moi ici. Maintenant moi partir !}
{230}{}{Ca ne te regarde pas... camarade. Je te suggère de remonter ces escaliers tout de suite et d'oublier notre rencontre.}
{231}{}{Moi Oublier. Ou-bliette, ou... heu... oublier quoi ?}
{232}{}{Ok, d'accord.}
{233}{}{Ta suggestion ne me dit rien... Quel est le problème ici ?}
{234}{}{Tu as des problèmes. Je peux peut-être t'aider.}
{235}{}{Tu as l'air d'un homme qui chérit sa vie privée. Pour quelqu'un de bavard comme moi, ça va être très cher d'oublier.}
{236}{}{All right then... sorry to bother you.}
{245}{}{Des problèmes ? Le problème est devant moi et me parle.}
{246}{}{Bien, je vais pas le dire deux fois, mec : casse-toi.}
{247}{}{Bien, je vais pas le dire deux fois, chérie : va-t'en.}
{248}{}{Tu me *menaces* ? Fais vraiment TRES attention avant de répondre !}
{255}{}{Un problème ? Pas du tout, mon vieux. Je cherche juste un peu d'intimité ; c'est tout.}
{256}{}{Un problème ? Pas du tout, ma chérie. Je cherche juste un peu d'intimité ; c'est tout.}
{257}{}{Un problème ? Pas du tout. Je cherche juste un peu d'intimité. Mais... C'ETAIT malpoli de ma part de rejeter une si jolie dame.}
{258}{}{Je pense que tu AS un problème. Tu vois, c'est si intime et privé ici que personne peut entendre ce qui se passe. Peut-être bien que je vais te tuer, hein ?}
{260}{}{Pour quelqu'un d'aussi bavard que moi, le droit à la vie privée peut coûter assez cher.}
{261}{}{Bon d'accord. Je m'excuse de t'avoir dérangé.}
{262}{}{Tu as raison. C'ETAIT malpoli. Je m'en vais maintenant.}
{270}{}{[Il plisse les yeux.]}
{271}{}{Si t'es descendu chercher des ennuis, t'as tout gagné, mon vieux.}
{272}{}{Si t'es descendue chercher des ennuis, t'as tout gagné, ma chérie.}
{273}{}{J'espère que t'as rendu tes hommages...}
{274}{}{Tu cherches l'embrouille ? Tu TROUVES l'embroui --}
{283}{}{Heu... Attends, écoute... Je ne menace personne, et je ne cherche certainement pas à avoir des ennuis.}
{284}{}{Je pense que tu AS un problème. Tu vois, c'est si intime et privé ici que personne peut entendre ce qui se passe. Peut-être bien que je vais te tuer, hein ?}
{285}{}{Tu as l'air d'avoir des problèmes, je peux peut-être t'aider. Qu'en dis-tu ?}
{286}{}{Tu me fais l'effet d'un homme qui chérit sa vie privée. Pour quelqu'un de bavard comme moi, ça va être très cher d'oublier.}
{287}{}{All right then... sorry to bother you.}
{295}{}{Heu... Hé, attends... Heu, c'est pas la peine de parler comme ça. On peut peut-être parler d'AUTRE chose : ton ami Lloyd peut t'aider.}
{296}{}{Ca m'intéresse. Continue.}
{297}{}{Ca m'intéresse pas. Salut.}
{298}{}{Laisse tomber, Lloyd. C'est ton tour. Prépare-toi à crever !}
{305}{}{[Le visage de l'homme pâlit. Il déglutit un instant... puis t'assène un coup !]}
{306}{}{Ordu -}
{315}{}{J'ai des jetons... Peut-être qu'un peu d'argent pourrait clarifier la situation, nous rendre civilisés ?}
{316}{}{Bien. Donne-moi tout ce que tu as.}
{318}{}{Tu peux garder ton argent. Je me barre.}
{325}{}{D'accord, d'accord... [Il met la main dans sa poche, en retire quelques jetons et te les donne] Bon, fais-moi plaisir, prends cet argent, remonte et amuse-toi aux frais de Lloyd, d'accord ?}
{326}{}{Tu souffres peut-être de surdité. J'ai DIT, donne-moi tout ce que t'as !}
{327}{}{Ok. Mais je vais d'abord te tuer.}
{328}{}{Bon d'accord. Je m'en vais.}
{335}{}{Heu, voilà... C'est tout ce que j'ai. J'ai rien d'autre, je t'ai tout donné.}
{336}{}{M'arnaque pas, Lloyd. J'suis la personne la plus teigneuse du désert. J'SAIS que t'en as encore, t'es pas con. Bon, pour la dernière fois, Lloyd : où est le reste ?}
{337}{}{On verra bien, Lloyd. Je verrai bien quand je fouillerai ton cadavre.}
{345}{}{Je... J'ai dit... Heu... D'accord... Je sais où tu peux trouver plus de fric... Il est pas à moi, et ça va t'attirer des ennuis, mais si tu le veux, il est à toi.}
{346}{}{Peut-être bien que je sais où tu pourrais trouver du fric... Il est pas à moi, tu comprends, et ça va t'attirer des ennuis, mais si tu le veux, il est à toi.}
{347}{}{Continue à parler de trucs intéressants comme ça.}
{348}{}{En fait, je plaisantais en parlant de te donner une chance, Lloyd. Je vais juste te tuer et laisser les esprits mettre de l'ordre.}
{349}{}{Ton double langage de merde de Brahmine ne m'intéresse pas. Salut.}
{355}{}{Bon d'accord... Dans la plaine du Golgotha, au Sud de Reno, enterré dans une des tombes. Mais je suis le seul à savoir où.}
{357}{}{Dis-moi.}
{358}{}{C'est le plus gros amas de... Oh merde, Lloyd, je vais juste te tuer et laisser les esprits mettre de l'ordre.}
{359}{}{Oh, laisse tomber. Salut.}
{365}{}{Quand tu es devant le panneau du croisement du Golgotha, marche vers le Nord-Ouest jusqu'à la troisième tombe. Après, prends vers le Nord-Est jusqu'au premier poteau. C'est une tombe marquée « Arch Stanton ». Creuse environ deux mètres et tu trouveras.}
{366}{}{Devant le panneau, compte trois tombes vers le Nord-Ouest, et après vers le Nord-Est jusqu'au premier poteau, et cherche « Arch Stanton »... Bon, on y va, Lloyd. J'ai besoin de quelqu'un pour creuser, après tout.}
{367}{}{Bon d'accord. Je me tire. Tiens-toi à carreau. [Tu laisses Lloyd partir.]}
{368}{}{C'est tout ce que je dois savoir... Ils t'enterreront dans cette tombe au matin.}
{375}{}{[Lloyd s'apprête à parler, y repense, puis hoche la tête.] Bon d'accord. On dirait que j'ai pas le choix. On y va.}
{376}{}{Je dois d'abord m'occuper d'un truc. Tu attends là, je reviens dans une heure. [Tu sors, tu te caches dehors, puis tu vérifies si Lloyd sort et tu le suis.]}
{377}{}{Je dois d'abord m'occuper d'un truc. Tu attends là, je reviens.}
{378}{}{Je suis derrière toi.}
{385}{}{Hum. Je te connais pas... mais je pense que j'aimerais bien. Moi c'est Lloyd. Certains m'appellent Lloyd Beau Gosse, mais bon...}
{386}{}{Hum. Je te connais pas, chérie... mais je pense que j'aimerais bien. Moi c'est Lloyd. Certains m'appellent Lloyd Beau Gosse, mais bon...}
{387}{}{Hum. J'suis pas assez fou pour refuser l'aide d'une femme aussi belle. Moi c'est Lloyd. Certains m'appellent Lloyd Beau Gosse, mais bon...}
{388}{}{Sympa de te rencontrer. Alors... mon offre... ?}
{395}{}{La famille Salvatore et moi on a eu un... désaccord au sujet de mon succès à l'une de leurs tables de jeu. Je pense que le seul moyen d'y remédier est de me retirer aussi loin que possible de New Reno.}
{396}{}{Du succès à leurs tables de jeu, hein ? Combien t'as gagné, Lloyd ?}
{397}{}{Que puis-je faire ?}
{398}{}{Qu'est-ce que j'y gagne ?}
{399}{}{Je pense pas que je puisse t'aider, Lloyd. Je crois qu'on ferait mieux d'oublier cette rencontre. Au revoir.}
{405}{}{Hum... J'ai l'impression que tu ferais un bon garde du corps. Aide-moi à quitter la ville. Escorte-moi vers le Sud jusqu'à la plaine du Golgotha, je te donnerai quelques jetons pour ta peine.}
{407}{}{C'est bon. On y va. [Tu le suis.]}
{415}{}{[Il pâlit, puis se reprend.] Assez pour les rendre fous. J'ai presque tout dépensé en pots-de-vin pour que les brutes de Salvatore me laissent me planquer. J'ai peur de me montrer en ville...}
{416}{}{[Il a l'air surpris, puis se reprend.] Assez pour les rendre fous. J'ai presque tout dépensé en pots-de-vin pour que les brutes de Salvatore me laissent me planquer. J'ai peur de me montrer en ville...}
{417}{}{Je peux t'aider, mais je veux la moitié de cet argent que tu as gagné, Lloyd. Et m'embrouille pas si tu veux pas y rester.}
{418}{}{Donne-moi la moitié de ce que tu as gagné, et je t'aiderai, Lloyd. C'est un échange de bons procédés, tu quitteras la ville sain et sauf.}
{419}{}{D'accord, je vais t'aider. Sortons d'ici. [Tu le suis.]}
{420}{}{Je ne pense pas pouvoir t'aider, Lloyd. Au revoir.}
{425}{}{[Lloyd s'apprête à dire quelque chose, y repense, puis hoche la tête.] Bon d'accord. On dirait que j'ai pas le choix. On y va.}
{427}{}{Non, tu attends là et tu restes tranquille jusqu'à ce que je revienne. Je dois m'occuper d'un truc, après je reviens et on ira sur le terrain.}
{435}{}{[Il se raidit.] Peut-être. Qui es-tu ? Je crois pas avoir déjà eu le plaisir...}
{436}{}{[Il se raidit, puis te regarde perplexe.] Peut-être. Je suis sûr que je ne t'aurais pas oubliée. Je ne crois pas avoir déjà eu le plaisir... ?}
{437}{}{Laisse tomber ton baratin, Lloyd. Je suis là au sujet de l'argent que tu as volé à M. Salvatore.}
{438}{}{Ecoute, Lloyd, donne-moi le fric et j'oublierai PEUT-ETRE que je t'ai rencontré le temps que tu te tires d'ici.}
{439}{}{Lloyd, M. Salvatore m'a demandé de venir chercher son argent et de faire de toi un... exemple. Il n'est pas nécessaire d'en arriver là... SI on peut arriver à un accord, tous les deux.}
{445}{}{D'accord... D'accord... [Il déglutit.] Il est dans les plaines de Golgotha, au Sud de Reno, enterré dans l'une des tombes. Mais je suis le seul à savoir où.}
{446}{}{Montre-moi.}
{448}{}{C'est le plus gros amas de... Oh merde, je vais juste te tuer et trouver le fric sans toi.}
{455}{}{Hum hum. Je pense pas qu'on croie à ça ni l'un ni l'autre... [Il déglutit.] Mais je peux peut-être te faire confiance. L'argent est enterré sur les plaines du Golgotha, au Sud de Reno, dans l'une des tombes. Mais je suis le seul à savoir où.}
{459}{}{Oh, oublie ces conneries. Je m'en vais. Garde ton fric et ton secret et que je te revoie plus.}
{465}{}{Hum. Un *accord* tu dis... D'accord, d'accord... Que veux-tu ?}
{466}{}{Je peux te faire quitter la ville pour la moitié de cet argent que tu as gagné chez Salvatore, Lloyd.}
{467}{}{Je peux te faire quitter la ville si tu me donnes cet argent que tu as gagné chez Salvatore, Lloyd.}
{468}{}{Oh, peu importe. Je ne veux rien, sors de là avant que je change d'avis. [Tu fais semblant de partir, tu te caches et tu le suis.]}
{469}{}{Oh, peu importe. Je ne veux rien, sors de là avant que je change d'avis.}
{475}{}{Bon, alors... Hum... J'ai l'impression que j'ai pas le choix. Mais je vais devoir t'emmener où se trouve l'argent, sinon tu ne le trouveras pas. Allons-y.}
{476}{}{Je dois d'abord m'occuper d'un truc. Attends, je reviens dans une heure. [Tu fais semblant de partir, tu te caches et tu le suis.]}
{477}{}{Non, tu attends là que je revienne. Je dois m'occuper d'un truc, et après je reviendrai te chercher et on ira sur le terrain.}
{478}{}{Je suis derrière toi. [Tu le suis.]}
{555}{}{[Il bondit.] Heu... On y va ?}
{556}{}{Oui. Allons-y. [Tu le suis.]}
{557}{}{Non, tu attends là que je revienne. Je dois d'abord m'occuper d'un truc.}
{565}{}{En ce qui concerne ton offre, une aide me SERAIT bien utile. Je dois quitter la ville, mais les choses sont compliquées à cause d'un certain... malentendu.}
{566}{}{Quel malentendu ?}
{585}{}{Il est temps de foutre le camp de Reno...}
{586}{}{Putain de boîte...}
{587}{}{Plus lourde que je ne croyais...}
{595}{}{Nous y voilà...}
{596}{}{C'est celle-là.}
{605}{}{Nous y voilà... <Ouf> ... l'argent est dans... cette tombe.}
{606}{}{Allez creuse, Lloyd.}
{607}{}{Laisse-moi d'abord examiner cette tombe...}
{609}{}{Bon, recule et laisse-moi creuser...}
{610}{}{Sors de là, Lloyd. Cet argent m'appartient maintenant.}
{615}{}{[Il a l'air épuisé.] Dans le... cadre de... ta mission de garde, je... je voudrais que... tu creuses.}
{616}{}{Euh...}
{617}{}{Y'a deux types de personnes dans ce monde, Lloyd. Ceux qui ont des fusils chargés et ceux qui creusent.}
{620}{}{All right then, I'll do it...}
{625}{}{[Lloyd marmonne dans sa barbe, puis commence à creuser.]}
{626}{}{[Lloyd marmonne dans sa barbe, puis commence à creuser... prudemment. Moins d'une minute plus tard, il extrait une mine de la terre et la met de côté. Il hausse les épaules d'un air penaud.]}
{627}{}{C'est ça. Tu te débrouilles bien. Continue. Creuse un peu plus vite.}
{628}{}{C'est bien, Lloyd. CONTINUE de creuser. Voyons voir ce qu'il y a d'autre là-dessous.}
{635}{}{[Une demi-heure plus tard, Lloyd a déblayé assez de terre pour révéler une petite plaque d'égout encastrée dans le sol... Tu sais que tu ne l'aurais pas trouvée s'il ne t'en avait pas parlé. Lloyd respire profondément et s'essuie le front.] Vieil... abri... antiatomique.}
{636}{}{[Une demie heure plus tard, tu as déblayé assez de terre pour révéler une petite plaque d'égout encastrée dans le sol. Tu ne l'aurais pas trouvée s'il ne t'avait pas dit où creuser. Lloyd parle :] C'est un vieil abri antiatomique. Je l'ai trouvé il y a une semaine alors que je vérifiais la zone.}
{637}{}{Bon, laisse-moi ouvrir ça, et on s'occupera de notre affaire.}
{638}{}{Ouvre l'abri, Lloyd.}
{645}{}{[On dirait qu'on a récemment marché autour de la tombe. A cause de la distance à laquelle Lloyd se tient par rapport à la tombe, tu te demandes soudain si elle n'a pas été piégée.]}
{646}{}{Je crois que tu devrais creuser, Lloyd.}
{647}{}{Hum. Laisse-moi examiner la tombe de plus près...}
{648}{}{Recule, Lloyd. Je vais commencer à creuser.}
{655}{}{[On dirait qu'on a récemment marché autour de la tombe. Ca colle avec le fait que Lloyd ait caché les jetons ici.]}
{665}{}{[Tu examines le site avec attention et retires la terre. Ce faisant, tu remarques une mine qui a été enterrée. Tu la désarmes prudemment et la ranges dans ton sac.]}
{666}{}{Oublier ça, Lloyd ? Voyons voir si tu peux oublier CA !}
{667}{}{Je crois que TU devrais creuser, Lloyd. Grouille-toi.}
{668}{}{Je vais laisser passer ça, Lloyd... cette fois. Maintenant recule pendant que je continue à creuser.}
{675}{}{[L'abri antiatomique s'ouvre avec un grincement rouillé, révélant un trou obscur.]}
{676}{}{Rentre là-dedans, Lloyd.}
{677}{}{Reste là, Lloyd. J'y vais.}
{685}{}{[Lloyd fronce les sourcils, pense à faire un commentaire, puis hausse les épaules et s'introduit dans l'abri antiatomique.]}
{686}{}{Dépêche-toi, Lloyd.}
{687}{}{HE LLOYD, ATTRAPE ! [Tu lances la mine dans le trou.]}
{688}{}{Je descends tout de suite derrière toi, Lloyd.}
{695}{}{[Tu entends grogner Lloyd plus bas.] Attends... Je l'ai presque... [Il y a un bruit de métal, puis le silence.]}
{696}{}{Bouge-toi, Lloyd. On a pas toute la journée.}
{698}{}{J'arrive, Lloyd.}
{706}{}{Rien d'extraordinaire...}
{715}{}{D'accord, d'accord... c'est à toi. Pas de problème. Je m'en vais. [Il se retourne et s'en va.]}
{716}{}{[Tu le laisses partir]}
{717}{}{[Tu lui tires dans le dos]}
{1000}{}{Après une longue marche, vous arrivez aux contreforts du Golgotha. Lloyd te mène jusqu'à l'une des tombes.}
{1001}{}{Tu suis Lloyd jusqu'au Golgotha. Une fois sur place, il creuse sur l'une des tombes.}
{1002}{}{Tu perds Lloyd à la sortie de New Reno.}
{1050}{}{Tu laisses partir Lloyd.}
{1051}{}{::Marmonne:: Ca aurait pu être mon argent.}
{1052}{}{Euh... Merci de m'avoir laissé en vie.}
{1053}{}{Quand tu ressors de la tombe, Lloyd a disparu.}
{1054}{}{Oublie ça. C'est mon argent et tu n'auras rien du tout !}
{5213}{}{ Moi }
{7213}{}{Qui tu}
