{100}{}{Tu vois Marjorie Reed, la chef des chercheurs.}
{150}{}{Tu vois une femme à l'air fatiguée. Elle a le crâne rasé et porte une blouse blanche.}
{151}{}{Tu vois Marjorie Reed. Elle remplit une seringue. Elle grommelle toute seule.}
{200}{}{Salut, Myron.}
{201}{}{Myron, as-tu une minute... ?}
{202}{}{As-tu entendu parler d'un nouvel arrivage d'esclaves, Myron ?}
{203}{}{Myron, les derniers résultats sont très prometteurs...}
{204}{}{Myron, as-tu une minute ?}
{215}{}{Merde, où est Myron ?}
{216}{}{Fais venir Myron. Il faut qu'il voie ça.}
{217}{}{J'aimerais que ces esclaves la ferment...}
{218}{}{Où ai-je laissé cette seringue...}
{219}{}{Quelqu'un a-t-il vu le n°31 ? Il était là il y a une seconde.}
{220}{}{Débrouille-toi pour que les esclaves apportent plus de Jet Béta.}
{221}{}{Les résultats des tests de Jet Béta sont très prometteurs, mais...}
{222}{}{Ca *plane* de 15 minutes à une heure... Calculer la période d'une dose par heure... Hum.}
{223}{}{N°12 souffre toujours de saignements de nez.}
{224}{}{C'est la cinquième fois que n°12 fait des crises... On augmente la dose et on voit...}
{225}{}{Bon, quelles SORTES d'hallucinations avait-il ?}
{226}{}{Vérifie son pouls. S'il est encore dans des limites tolérables, augmente la dose.}
{227}{}{Pourquoi l'esclave du groupe témoin s'est-elle suicidée ? On ne s'est même pas servi d'elle pour faire des expériences !}
{228}{}{Ces foutus gardes sont une vraie bande d'incapables.}
{235}{}{Bonjour chef. Les tests se passent comme prévu.}
{236}{}{Chef, Myron, ce nouveau lot de Jet crée une forte dépendance. Les esclaves sont presque prêts à s'entre-tuer pour en avoir.}
{237}{}{Chef, Myron, tu seras content de savoir que les esclaves préfèrent prendre du Jet plutôt que se nourrir.}
{238}{}{Qui sont ces gens Myron ? De nouveaux sujets ?}
{239}{}{Chef, Myron, il semble que le troisième groupe soit le meilleur de tous.}
{240}{}{Chef, Myron, si tu as un moment... Je crois que le prochain groupe devrait comporter au moins 3 enfants.}
{241}{}{Chef, Myron, le n°46 a eu une attaque cardiaque, nous avons réduit les doses à 6 par jour.}
{242}{}{Chef, Myron... Nous aurions besoin d'une nouvelle livraison de seringues de la Cité de l'Abri. On ne peut pas réutiliser celles-ci à l'infini.}
{243}{}{On a des nouvelles du prochain arrivage d'esclaves, chef ?}
{244}{}{Chef, Myron, nous avons déplacé 3 esclaves du groupe témoin vers le groupe d'essai à cause des problèmes respiratoires de la semaine dernière.}
{245}{}{Chef, Myron, mauvaise nouvelle : nous avons dû abattre un esclave qui tentait de s'échapper. Quel gâchis.}
{246}{}{Myron, l'hallucinogène que nous développons en ce moment est prometteur, mais il ne rend pas aussi dépendant que le Jet.}
{250}{}{[La femme chauve ne lève même pas les yeux de son écritoire.] Oui ?}
{251}{}{Non !}
{252}{}{Oui !}
{253}{}{Hé-hé ! Toi chauve. Toi ressembler homme.}
{254}{}{Delenn ?}
{255}{}{[Partir]}
{256}{}{Qui es-tu ?}
{257}{}{Pardon, j'ai cru que tu étais une autre femme chauve avec un écritoire. Je dois partir.}
{265}{}{[La femme lève les yeux et te fusille du regard.] Fais-tu partie des cobayes ? Peu importe de toute façon... Gardes ! Attrapez cet esclave !}
{266}{}{Où ça esclave ? Moi pas voir.}
{275}{}{J'ai des tas de choses à faire, si tu permets... [Elle jette un oeil par-dessus l'écritoire, puis fait la grimace.] Qui es-tu ? Comment as-tu fait pour entrer ?}
{276}{}{J'ai ENORMEMENT de choses à faire, si tu permets... [Elle jette un oeil par-dessus l'écritoire, puis fait la grimace.] Encore toi ? Que veux-tu ?}
{277}{}{On rentre ici comme dans un moulin... étable, moulin... elle est bonne hein ?}
{278}{}{Je fais partie du personnel récemment affecté ici.}
{279}{}{Je cherche Myron. Il est par ici ?}
{280}{}{Ce sont des résultats sur l'écritoire ? Je peux les voir ?}
{282}{}{Ça ne fait rien. Je m'excuse de t'avoir dérangé.}
{295}{}{Ce service n'est pas ouvert aux... visiteurs. Pars ou j'appelle les gardes.}
{296}{}{Mais, je voulais te poser des questions...}
{298}{}{Ce sont des résultats de test sur l'écritoire ? Je peux les voir ? Moi aussi je fais de la recherche, enfin, pas la même.}
{300}{}{Très bien. Je m'excuse de t'avoir dérangée.}
{310}{}{Gardes ! Gardes, attrapez cette personne !}
{315}{}{ENCORE des gardes. Ha ! Comme si ça changeait quelque chose... Ecoute, tu aurais dû recevoir des instructions de la personne qui t'a envoyé ici. Va parler à l'autre garde pour savoir où tu dois aller. Vas-y !}
{316}{}{Je ne vais pas être garde, je fais de la recherche. Tu as du travail pour moi ?}
{317}{}{Excuse-moi, j'espérais que tu pourrais me faire visiter. Je t'ai vue et j'ai ressenti le BESOIN de te parler. Peut-être qu'après la visite, on pourrait aller manger...}
{318}{}{Merci. Ton aide m'a été très utile.}
{325}{}{Tu fais de la RECHERCHE ? Hum. C'est la première fois que je te vois. Tu t'y connais en recherche pharmaceutique ?}
{326}{}{Heu, assez. Reste là, ne te dérange pas.}
{327}{}{J'en connais un morceau sur la composition et la fabrication à base de composés neurochimiques. Je pourrais utilement contribuer à tes études.}
{328}{}{Je dois partir.}
{335}{}{Ha ! Je crois que je vais te laisser filer. Pars avant que j'appelle les gardes.}
{336}{}{D'accord.}
{337}{}{Je m'en vais... [Marmonne.] ... tête d'oeuf.}
{345}{}{Hum. D'accord. Laisse-moi te briefer sur notre activité ici : nous testons les effets et la force d'une méta amphétamine qui s'appelle le Jet.}
{346}{}{Je vois. Et où en sont les recherches ?}
{347}{}{Je crois que j'ai une idée. Je vais faire le reste des tests moi-même.}
{355}{}{Pas très bien. Notre programme est très juste et nous devrons bientôt purifier le procédé de fabrication du Jet.}
{356}{}{Pourquoi ? Il semblerait que le Jet rende déjà assez dépendant.}
{357}{}{Pourquoi un programme juste ?}
{358}{}{Ca a l'air dur comme boulot. Ecoute, je dois m'occuper de quelque chose, mais je reviens.}
{365}{}{Personne ne l'a jamais dit, mais c'est probablement dû à la distribution de Jet à Redding. Le Jet est *assez* fort, mais on peut encore faire de gros progrès. Et l'armée veut augmenter la dépendance de Jet à Redding.}
{366}{}{Que se passe-t-il avec Redding ?}
{367}{}{Eh bien, bonne chance pour terminer dans les délais.}
{375}{}{Le Jet est *assez* fort, mais on peut encore faire de gros progrès. Et l'armée veut augmenter la distribution de Jet à Redding. Le but est d'atteindre un taux de dépendance le plus proche de 100%. Ca va nous demander encore pas mal de boulot.}
{377}{}{Merci pour ces renseignements. Je reviendrai plus tard.}
{385}{}{Il suffit de rendre dépendants au Jet les mineurs de Redding. Celui qui contrôle le Jet contrôle Redding. C'est le jeu du pouvoir habituel.}
{386}{}{Alors, qui contrôle la came ?}
{395}{}{Qui contrôle la came ? Les Mordino. Bien sûr, Myron a fait le plus gros avec la composition de Jet. Nous faisons surtout de la purification.}
{396}{}{Myron, c'est ton patron ?}
{405}{}{En QUELQUE sorte. Il faut bien avouer que c'est un malin. Mais il se fout pas mal de ce qui se passe ici. En général, il reste au sous-sol... Les visiteurs sont interdits, sauf les putes. C'est un chef de projet typique.}
{406}{}{Puis-je le voir ?}
{407}{}{Ouais, il y a pire, il y a le marketing. Merci quand même pour les renseignements. Je reviendrai.}
{415}{}{Je suppose... Prends ce badge provisoire, et montre-le aux gardes. Fais vite, Myron n'aime pas les gens qui restent trop longtemps.}
{416}{}{Je suppose... Prends ce badge provisoire, et montre-le aux gardes. Fais vite, Myron n'aime pas les gens qui restent trop longtemps... mais il fera peut-être une exception pour toi.}
{417}{}{Merci pour le badge. Je reviendrai te voir plus tard.}
{425}{}{Ecoute, j'ai des tas de choses à faire, si tu permets...}
{426}{}{Ecoute, heu... J'ai heu... Des tas de choses à faire, si tu permets...}
{427}{}{Alors tant pis...}
{428}{}{Merci quand même.}
{429}{}{Merci quand même... [Marmonne.] crâne d'oeuf.}
{435}{}{Ce... Hum... Je suis très flattée mais j'ai des tas de choses à faire en ce moment... Alors, heu...}
{436}{}{Alors si tu veux, je passe te chercher après le boulot. Je te force pas... On ira dîner, c'est tout, et on fera un brin de causette. On dirait que tu as besoin de penser à autre chose que le boulot. Il a l'air d'y avoir beaucoup de travail pour toi.}
{437}{}{Bon, j'ai essayé. Merci quand même.}
{445}{}{Oh, je suis pas terriblement occupée, mais assez. Les expériences, c'est la routine, et de temps en temps, un esclave pète les plombs.}
{446}{}{Ca ne te pose pas de problème éthique d'injecter sciemment des méta amphétamines expérimentales sur des humains réduits à l'esclavage ?}
{447}{}{Ca a l'air dangereux. Ca t'arrive de te faire mal ? Le taux de mortalité est-il important ?}
{448}{}{Des expériences de stupéfiants ? Comment ça se passe ?}
{449}{}{Ca m'a l'air intéressant, mais je dois partir... Heu, je reviendrai.}
{455}{}{C'était une mauvaise blague, hein ?}
{456}{}{Simple question. Et si c'était toi qui avais été vendue comme esclave, amenée ici, et bourrée de stupéfiants ?}
{457}{}{Heu, oui. Il faut que je parte.}
{465}{}{Moi, je suis de CE côté, les esclaves sont de l'AUTRE côté. Puisque nous parlons d'hypothèse, tu veux faire l'expérience, il nous reste certainement une place.}
{466}{}{Attends une minute...}
{467}{}{Heu, non merci. Je m'excuse de t'avoir dérangée.}
{475}{}{Les accidents mortels surviennent par overdose, résultats d'erreurs professionnelles en général, ou de blessures volontaires. Certains avalent trop de Jet et ils veulent VRAIMENT planer. }
{476}{}{A part ça, comment se passent les tests de stupéfiants ?}
{477}{}{C'est clair. Merci pour ces renseignements. Ton aide a été très précieuse.}
{485}{}{Va voir au labo, au sous-sol. Il y a une porte gardée. Si tu le vois, dis-lui de monter quand il aura un moment. Seulement s'il n'est pas trop occupé.}
{1000}{}{Marjorie te donne un passe provisoire.}
