{100}{}{You see... Sheb.}
{150}{}{Tu vois un homme décharné portant des vêtements bleu vif. Comme si ça ne suffisait pas pour se faire remarquer, il hurle à pleins poumons.}
{200}{}{Butin, butin, bu-tiiin !}
{201}{}{Entrez, amateurs de butin !}
{202}{}{Ici, au Cat's Paw, on coupe les prix en deux !}
{203}{}{Faites-nous une offre sur notre sélection des meilleurs butins ! On fait sauter les prix !}
{204}{}{On a des butins blancs, des butins noirs, des butins du Sud, des butins du Nord...}
{205}{}{On a des butins chauds, des butins froids, des butins frais, des... butins... <Snifff> *puants*...}
{206}{}{On a des butins tribals, des butins mutants, des butins radscorpions, des butins robots.}
{207}{}{On a même des butins Brahmines, des butins Goules, des butins Griffemorts.}
{208}{}{Allez, vous voulez des butins ? Entrez, amateurs de butins !}
{209}{}{Ce qu'on n'a pas, c'est que vous n'en voulez pas ! Entrez, amateurs de butins !}
{210}{}{Attention, acheteurs de butins ! Ne ratez pas cette vente spéciale !}
{211}{}{Achetez un butin au prix normal et vous aurez le deuxième de même valeur ou moins pour un jeton seulement !}
{212}{}{Essayez de trouver un butin à moins d'un jeton !}
{213}{}{Si vous trouvez des butins moins chers... ACHETEZ-LES !}
