{100}{}{Tu vois un soldat portant la SuperArmure de l'Enclave.}
{101}{}{Tu vois le sergent Granite.}
{102}{}{Tu vois un soldat avec des épaulettes de sergent.}
{103}{}{Attrapons ce psychopathe !}
{104}{}{Ouais, j'm'en charge personnellement !}
{105}{}{A vos armes et prêt, partez !}
{106}{}{Ca va cartonner !}
{107}{}{Descendons cette espèce de monstre !}
{108}{}{Faites-lui sa fête !}
{109}{}{Faut y aller là.}
{110}{}{Yeah !}
{111}{}{J'vais l'allumer cet iroquois !}
{112}{}{J'aime pas trop descendre des débiles.}
{113}{}{Tu peux y aller.}
{114}{}{J'ai rien vu}
{115}{}{C'est pas les robots qu'on cherchait.}
{116}{}{Avance.}
{117}{}{J'en ai assez de tuer.}
{118}{}{Vas-y !}
{119}{}{Du calme les gars.}
{120}{}{Fais gaffe mutant.}
{121}{}{Bonne chance, mutant. T'en auras besoin.}
{122}{}{Halte ! Que fais-tu là ?}
{123}{}{J'essaie de rejoindre mon peuple.}
{124}{}{Ca te regarde pas.}
{125}{}{Je n'ai pas de temps à perdre avec vos questions.}
{126}{}{Mais qui es-tu ?}
{127}{}{Tu sais l'autre monstre, l'agent Horrigan, il vient de passer en trombe. Il attend que quelqu'un se jette à l'eau.}
{128}{}{Qui c'est ?}
{129}{}{Je crois que tu te trompes. Disons que j'en fais mon affaire. Et maintenant tu vas me dire ce que tu fous ici ?}
{130}{}{J'essaie de rejoindre le navire pour m'échapper avec ma tribu.}
{131}{}{Bien, tu ferais mieux d'expédier ça.}
{132}{}{Pourquoi ? Qu'est-ce que ça veut dire ?}
{133}{}{Tout ce que je vais expédier, c'est toi dans l'au-delà.}
{134}{}{Fais ce que tu veux. Ne dis pas qu'on n'a pas essayé de te prévenir.}
{135}{}{Prévenir ? A propos de quoi ?}
{136}{}{Ouais, mieux vaut prévenir. Prépare-toi à mourir !}
{137}{}{C'est un monstre produit par le génie génétique. Il a été garde du corps du président. Agent des services secrets Frank Horrigan. Maintenant, c'est une machine à plus de 50%.}
{138}{}{Ca présage rien de bon.}
{139}{}{J'ai tué pire que ça. Ce ne sera plus qu'une autre tache dans quelques minutes.}
{140}{}{Brrrr, j'en tremble déjà. Ferme-la.}
{141}{}{Oh, et bien pire encore. Il va te transformer en serpillière. C'est un dur, un rapide et du genre vicelard. J'ai vu ce qu'il a fait à des mutants et c'est pas joli !}
{142}{}{D'abord, je ne suis pas un mutant et... Que leur a-t-il fait au juste ?}
{143}{}{Je n'aime pas trop en parler. Ca me donne des cauchemars. Disons que ces murs ne sont pas recouverts de *rouille* uniquement.}
{144}{}{Je crois que je vais avoir du mal à m'en débarrasser.}
{145}{}{C'est le moins qu'on puisse dire. Je te plains, sincèrement.}
{146}{}{Me plaindre ? C'est moi qui te plains ! L'ordinateur de contrôle de ta centrale a grillé et le réacteur ne va pas tarder à entrer en fusion. Vous êtes tous morts, à moins que...}
{147}{}{Je n'ai pas besoin de ta pitié. Juste de te voir crever.}
{148}{}{J'ai autre chose à faire. Vous êtes tous morts. Profitez de vos dernières minutes sur cette planète. Fumez-vous-en une si vous en avez. Adieu.}
{149}{}{A moins que quoi ?!?}
{150}{}{A moins que tu m'aides à me débarrasser d'Horrigan et à rejoindre mon navire.}
{151}{}{C'est pas grave. J'ai pas le temps d'en discuter. Adieu.}
{152}{}{Ah, ouais. Elle est bien bonne. Si le réacteur est foutu comment se fait-il que les lumières soient allumées ? Hein ? C'est une bonne blague.}
{153}{}{C'est l'éclairage de *secours*. Hé, j'ai vu *l'emplacement* de l'ordinateur. Il est pas grillé, il a *disparu*. Je te le dis, vos minutes sont comptées à moins que....}
{154}{}{J'ai plus le temps de discuter de ça. J'espère que vous êtes bons nageurs. Adieu.}
{155}{}{J'aime tes petites histoires. Tu me fais rire. Tu vois, j'crois même que tu pourrais tenir plus d'une minute contre Horrigan. Ca serait un record absolu. Bonne chance mutant.}
{156}{}{Ouah, c'est généreux de ta part. Je ferais mieux de m'échauffer. Sur toi et ton escouade.}
{157}{}{Croise les doigts pour que cette armure flotte. Adieu.}
{158}{}{D'accord. Je ne représente pas tout le monde mais moi et mes hommes on va t'aider à régler son compte à ce monstre de Horrigan. J'ai pas envie de crever noyé comme un foutu rat !}
{159}{}{Bonne idée. Allons lui régler son compte. Il faut se tirer d'ici.}
{160}{}{Sergent Granite de la compagnie CE.}
{161}{}{Compagnie CE ?}
{162}{}{Compagnie de Contrôle de l'Enclave. Nous avons la responsabilité du périmètre de défense, enfin *normalement*.}
{163}{}{Oh, je vois. Qu'est-ce tu entends par *normalement* ?}
