{100}{}{Tu vois un terminal.}
{101}{}{Tu vois un terminal. Il a l'air de fonctionner.}
{102}{}{Tu vois un Dataplex 2000 IntelliTerminal, avec 64 ko de mémoire, le dernier-né de la technologie informatique. Dommage qu'il ne fonctionne pas.}
{103}{}{Tu vois un Dataplex 2000 IntelliTerminal, avec 64 ko de mémoire, le dernier-né de la technologie informatique.}
{104}{}{Bienvenue sur PoséidoNet. Faites une sélection dans le menu :}
{105}{}{[Connexion]}
{106}{}{[Aide]}
{107}{}{[Fermer la session]}
{108}{}{Ce terminal passe un film indien, mais il est vraiment ennuyeux.}
{109}{}{Ce terminal passe une émission de tir sur cible. Tout ce qu'on voit c'est le mille de la cible.}
{110}{}{Ce terminal expose une sorte d'art moderne, un boulot à base de plein de différentes bandes de couleurs.}
{111}{}{Tu vois un terminal. Il montre de petites bombes bougeant en diagonale sur l'écran.}
{112}{}{Ce terminal a un message affiché sur son écran : « Vous pouvez maintenant éteindre votre ordinateur en toute sécurité ». Tu te demandes ce que ça veut dire.}
{113}{}{Tu vois une image, des pointes rouges, vertes et bleues de lumière combinées pour faire une image d'un truc...}
{114}{}{Il y a un visage hideux qui te regarde dans les yeux. Oh, attends, ce terminal est éteint.}
{115}{}{Cette fenêtre scrute dans une dimension sombre au-delà de l'espace et du temps.}
{116}{}{This terminal has a message on it; "Loading Fenestra '98." The terminal is covered with a thick layer of dust.}
{117}{}{Ce terminal semble être de la marque Apricot. Un truc appelé Fallout 2 tourne dessus. Wouh, on dirait qu'il est en multijoueurs et en 3D.}
{118}{}{Entrez Identification Utilisateur :}
{119}{}{[J'vais essayer ça.] Liste utilisateurs.}
{120}{}{[Est-ce que ça va marcher ?] Smith, J.}
{121}{}{[Retour]}
{123}{}{Je pense que je devrais faire ça ailleurs.}
{124}{}{Listing (the terminal displays a list of about 500 names).}
{125}{}{Listing (the computer displays a list of names).}
{126}{}{Sélectionnez Identification Utilisateur ou déconnectez-vous :}
{127}{}{[Celui-ci possède les autorisations d'accès.] Smith, J.}
{128}{}{(This one looks kind of special.) Presidential Passkey-Security Override.}
{129}{}{[Celui-ci accède à des données plus intéressantes que d'habitude.] Murray, T.}
{130}{}{[Celui-ci a un accès de bonne qualité.] Curling, Dr. C.}
{131}{}{[On dirait qu'il a vraiment beaucoup de droits.] Bird, D.}
{132}{}{[J'essaierai ça plus tard.] [Déconnexion]}
{133}{}{Sélection :}
{134}{}{                A. E. C. : Contrôle Centrale Nucléaire,}
{135}{}{                Statut Sécurité ?}
{136}{}{Download A. E. C.: Atomic Power plant Operations.}
{137}{}{Statut Sécurité}
{138}{}{Retour Identification Utilisateur :}
{139}{}{Sélection :}
{140}{}{                Niveau Sécurité : Statut Courant,}
{141}{}{                Corporation Chimique : Rapport d'Avancement de Projet,}
{142}{}{                A. E. C. : Contrôle Centrale Nucléaire,}
{143}{}{                Statut Sécurité ?}
{144}{}{Sécurité/Niveau : Statut Courant}
{145}{}{Download Chemical Corps: Project Status Report.}
{146}{}{Download A. E. C.: Atomic Power plant Operations.}
{147}{}{Statut Sécurité}
{148}{}{Retour Identification Utilisateur :}
{149}{}{Sélection :}
{150}{}{                Etat de la Nation: Statut Courant,}
{151}{}{                (LISTE MOTS), }
{152}{}{                Niveau Sécurité : Statut Courant,}
{153}{}{                Corporation Chimique : Rapport d'Avancement de Projet,}
{154}{}{                A. E. C. : Contrôle Centrale Nucléaire,}
{155}{}{                Statut Sécurité ?}
{156}{}{Etat de la Nation : Statut Courant}
{157}{}{Téléchargement Liste Mots}
{158}{}{Sécurité/Niveau : Statut Courant}
{159}{}{Download Chemical Corps: Project Status Report.}
{160}{}{Download A. E. C.: Atomic Power plant Operations.}
{161}{}{Statut Sécurité}
{162}{}{Retour Identification Utilisateur :}
{163}{}{Sélection : Statut Sécurité ?}
{164}{}{Statut Sécurité}
{165}{}{End Access.}
{166}{}{Téléchargement Achevé.}
{167}{}{Etat de la Nation : Statut Courant}
{168}{}{Téléchargement Liste Mots}
{169}{}{Sécurité/Niveau : Statut Courant}
{170}{}{Download Chemical Corps: Project Status Report.}
{171}{}{Download A. E. C.: Atomic Power plant Operations.}
{172}{}{Retour Identification Utilisateur :}
{173}{}{Téléchargement Achevé.}
{174}{}{Téléchargement Liste Mots}
{175}{}{Sécurité/Niveau : Statut Courant}
{176}{}{Téléchargement Corporation Chimique : Rapport d'Avancement de Projet}
{177}{}{Téléchargement C. C. N. : Contrôle Centrale Nucléaire}
{178}{}{Statut Sécurité}
{179}{}{Retour Identification Utilisateur :}
{180}{}{Téléchargement Achevé.}
{181}{}{Etat de la Nation : Statut Courant}
{182}{}{Sécurité/Niveau : Statut Courant}
{183}{}{Téléchargement Corporation Chimique : Rapport d'Avancement de Projet}
{184}{}{Téléchargement C. C. N. : Contrôle Centrale Nucléaire}
{185}{}{Statut Sécurité}
{186}{}{Retour Identification Utilisateur :}
{187}{}{Niveau Baraquements Gardes : Tourelles de sécurité actuellement en statut Alerte Armée.}
{188}{}{Niveau Baraquements Gardes : Tourelles de sécurité actuellement en statut Normal.}
{189}{}{Niveau Baraquements Gardes : Tourelles de sécurité actuellement en statut Désactivation Maintenance.}
{190}{}{Niveau Quartiers du Sujet Test : Tourelles de sécurité actuellement en statut Alerte Armée.}
{191}{}{Niveau Quartiers du Sujet Test : Tourelles de sécurité actuellement en statut Normal.}
{192}{}{Niveau Quartiers du Sujet Test : Tourelles de sécurité actuellement en statut Désactivation Maintenance.}
{193}{}{Zone de Projet de Recherche et Développement : Tourelles de sécurité actuellement en statut Alerte Armée.}
{194}{}{Zone de Projet de Recherche et Développement : Tourelles de sécurité actuellement en statut Normal.}
{195}{}{Zone de Projet de Recherche et Développement : Tourelles de sécurité actuellement en statut Désactivation Maintenance.}
{196}{}{Zone des Bureaux de Cadres : Tourelles de sécurité actuellement en statut Alerte Armée.}
{197}{}{Zone des Bureaux de Cadres : Tourelles de sécurité actuellement en statut Normal.}
{198}{}{Zone des Bureaux de Cadres : Tourelles de sécurité actuellement en statut Désactivation Maintenance.}
{199}{}{Niveau d'Information et de la Centrale : Tourelles de sécurité actuellement en statut Alerte Armée.}
{200}{}{Niveau d'Information et de la Centrale : Tourelles de sécurité actuellement en statut Normal.}
{201}{}{Niveau d'Information et de la Centrale : Tourelles de sécurité actuellement en statut Désactivation Maintenance.}
{202}{}{Adjust security level.}
{203}{}{Etat de la Nation : Statut Courant}
{204}{}{Téléchargement Liste Mots}
{205}{}{Download Chemical Corps: Project Status Report.}
{206}{}{Download A. E. C.: Atomic Power plant Operations.}
{207}{}{Statut Sécurité}
{208}{}{Retour Identification Utilisateur :}
{209}{}{Téléchargement Achevé.}
{210}{}{Download State of the Nation: Current status.}
{211}{}{Téléchargement Liste Mots}
{212}{}{Sécurité/Niveau : Statut Courant}
{213}{}{Download A. E. C.: Atomic Power plant Operations.}
{215}{}{Statut Sécurité}
{216}{}{Retour Identification Utilisateur :}
{217}{}{Téléchargement Achevé.}
{218}{}{Download State of the Nation: Current status.}
{219}{}{Téléchargement Liste Mots}
{220}{}{Sécurité/Niveau : Statut Courant}
{221}{}{Download Chemical Corps: Project Status Report.}
{222}{}{Statut Sécurité}
{223}{}{Retour Identification Utilisateur :}
{224}{}{Ce terminal est en cours d'auto-diagnostic approfondi. Veuillez utiliser un autre terminal. Merci.}
{225}{}{Bienvenue au système d'Aide PoséidoNet. Nous regrettons de vous informer que vos fichiers d'Aide sont périmés, et non disponibles. Désirez-vous rechercher les mises à jour ? (O/N)}
{226}{}{Oui.}
{227}{}{Non, Retour.}
{228}{}{Mise à jour des fichier d'Aide non disponible avec la version limitée de PoséidoNet. Veuillez acquérir la version complète pour toutes les mises à jour futures. Votre période d'essai pour l'accès à PoséidoNet est dépassée de 59 439 jours.}
{229}{}{[Retour à l'écran de connexion]}
{230}{}{[Fin de session]}
{231}{}{Contournement de sécurité, nécessite le passe-partout Présidentiel. Options autorisées: Contre-Insurrection, Arrêt d'Urgence des Systèmes de Défense.}
{232}{}{[Je vais jeter un oeil à celui-ci.] Contre-Insurrection.}
{233}{}{[Je vais jeter un oeil à celui-là.] Arrêt d'Urgence des Systèmes de Défense.}
{234}{}{[Je devrais essayer quelque chose de moins frappant.] [Retour Identification Utilisateur]}
{235}{}{[Je ne pense pas avoir envie de tout dérégler maintenant.] [Déconnexion]}
{236}{}{Contre-Insurrection. Dans le cas d'une rébellion armée, la Carte Présidentielle de Sécurité autorise les systèmes de défense à attaquer toute unité menaçante, même si elle étaient antérieurement loyale dans une zone. Les systèmes de défenses sont programmés pour attaquer en premier les ennemis les plus dangereux. Attention ! Niveau opérationnel courant - Niveaux d'entrée uniquement !}
{237}{}{[Ca a l'air utile.] [Activer le Protocole Contre-Insurrection]}
{238}{}{[Bon j'essaierai ça la prochaine fois.] [Retour]}
{239}{}{[Je ne veux plus jouer avec l'ordinateur pour l'instant.] [Déconnexion]}
{240}{}{Clé Présidentielle de Sécurité reconnue, Bonjour, M. le Président... Protocole Contre-Insurrection Activé. Cible acquise}
{241}{}{[Je pense que je vais reculer et voir ce qui se passe.]}
{242}{}{Clé Présidentielle de Sécurité reconnue, Bonjour, M. le Président... Protocole Contre-Insurrection Activé... **Dysfonctionnement**... Sécurité déconnectée à ce niveau. Envoyez formulaire FG-I-106-32-0635 aux services de réparation agréés. Merci d'utiliser un produit Vault-Tek. Bonne journée.}
{243}{}{[Peut-être que ça marchera sur les niveaux d'entrée. Humm, ça veut dire la zone juste avant les docks. Il va falloir que j'essaie ça.] [Retour à Identification Utilisateur]}
{244}{}{[Je me demande ce que je peux essayer d'autre.] [Retour]}
{245}{}{Carte Présidentielle de Sécurité nécessaire pour accéder à cette fonction. Carte non trouvée.}
{246}{}{[Je me demande ce que je peux essayer d'autre.] [Retour]}
{247}{}{Arrêt d'Urgence des Systèmes de Défense coupe momentanément les sécurités actives niveau par niveau. L'arrêt d'Urgence lance un diagnostic approfondi avant d'initialiser le redémarrage des systèmes de sécurité.}
{248}{}{[On dirait quelque chose qui vaut la peine d'être essayé.] Activation Arrêt d'Urgence des Systèmes de Défense.}
{249}{}{[Humm, j'essaierai ça une autre fois.] [Retour]}
{250}{}{[Je ne veux plus jouer avec l'ordinateur pour l'instant.] [Déconnexion]}
{251}{}{Clé Présidentielle de Sécurité reconnue. Bonjour, M. le Président... Arrêt d'Urgence des Systèmes de Défense activé... Lancement diagnostic approfondi. Alpha... Bravo... Charlie...}
{252}{}{[Pour une raison étrange, je n'ai pas envie de faire ça maintenant.] [Retour]}
{253}{}{[Je ferais bien de m'en aller, tant que cette chose fait toujours tourner son diagnostic.] [Déconnexion]}
{254}{}{Clé Présidentielle de Sécurité non reconnue. Accès refusé.}
{255}{}{[Humm, je me demande si je peux berner le scanner en lui faisant croire que j'ai la clé en forçant l'accès au fichier d'autorisation. Je pense que je vais essayer.]}
{256}{}{[Bon, ça valait le coup d'essayer.] [Retour]}
{257}{}{Security Passkey Scanner malfunction noted... Reinitializing scanner...}
{258}{}{(That's my chance, now if I can only get it to think it's recognized the Presidential Passkey...)}
{259}{}{(Damn, well nothing ventured...) Back.}
{260}{}{Scanner reinitialized. Rescanning...}
{261}{}{[C'est maintenant le grand moment.] [Tu tapes fiévreusement]}
{262}{}{Procédure illégale détectée. Tout accès futur sera refusé... Alerte de maintenance émise.}
{263}{}{Merde. C'est pas du tout ce que je voulais.}
{264}{}{Clé Présidentielle de Sécurité reconnue. Bonjour, M. le Président. [Ouais ! Voyons ce qu'on peut faire avec ça...]}
{265}{}{[Que puis-je faire d'autre ?]}
{266}{}{Presidential Security Passkey recognized. Good day, Mr. President... Emergency Counter Insurgency Protocol initiated... **Error** Target not found. Please ensure that the sensors are working correctly. If not, please submit form FG-I-106-32-0635 to authorize repair services. Thanks for using another fine Vault-Tec product. Good day.}
{267}{}{[Hmm... peut-être que ça marcherait s'il y avait quelqu'un ici. Je vais devoir essayer ça plus tard.] [Retourner à l'ID Utilisateur]}
{268}{}{[Je me demande ce que je peux essayer d'autre.] [Retour]}
