{100}{}{Tu vois une femme mineuse solidement bâtie.}
{101}{}{Tu vois Betty Blasphème, une femme qui travaille à la mine Morningstar.}
{102}{}{Tu vois une femme bien musclée avec une assurance du tonnerre.}
{103}{}{Caminetto, tes mineurs de Kokoweef ne sont que des vantards.}
{104}{}{Tu vas voir ce que tu vas voir, Betty Blasphème.}
{105}{}{Tu pourrais pas me faire voir sur une carte.}
{106}{}{Juste parce que j'ai pas envie de trop m'approcher de toi.}
{107}{}{Ne te vante pas trop, espèce d'avorton.}
{108}{}{Tu serais bien contente d'avoir une tête d'avorton pour remplacer la machine à perforer que tu utilises.}
{109}{}{Ouais, mon forêt au moins, il dure plus de trente secondes.}
{110}{}{Pas étonnant que les machines de la Morningstar soient toujours en panne.}
{111}{}{Je vais te montrer moi comment tu vas tomber en panne, et avec mes poings !}
{112}{}{Tes poings ? Avec ton haleine, ça suffira.}
{113}{}{Je ne sais pas comment tu peux encore sentir quelque chose avec ta puanteur accumulée depuis trois semaines.}
{114}{}{Puanteur ? Te regarder, c'est déjà assez douloureux comme ça.}
{115}{}{Tu connais rien à la douleur, mais t'inquiète pas, je vais t'apprendre !}
{116}{}{Tu vas m'apprendre ?}
{117}{}{Ouais, c'est ça. Parce que ta mère, elle a pas dû le faire.}
{118}{}{Tu parles de ma môman maintenant ? C'est pas très original ça.}
{119}{}{Je ferais mieux de te refaire la face, ça ce serait original. Celle-là n'est pas très belle à voir.}
{120}{}{Toi et qui encore ?}
{121}{}{Moi c'est tout, ça suffira. Mais je te parie que nous autres de la Morningstar on peut vous avoir quand on veut vous les chiffes molles de Kokoweef.}
{122}{}{Pas si sûr que ça. C'est Kokoweef qui fait la loi ici. Tu vas apprendre ça.}
{123}{}{Ca sera dur pour toi de le faire lorsque je t'aurai mis KO.}
{124}{}{Alors, comme ça, tu crois que tu vas avoir de la chance ?}
{125}{}{J'ai pas besoin de chance pour t'aplatir comme une crêpe.}
{126}{}{Tu vas m'aplatir avec ta graisse ? Ah, ah ben ça alors, j'ai *peur*.}
{127}{}{Vas-y ou ferme-la, espèce de mauviette !}
{128}{}{Viens m'chercher, vieille peau !}
{129}{}{Qui est-ce qui espère avoir de la chance maintenant ?}
{130}{}{Ca suffit ! Je vais t'écrabouiller !}
{131}{}{Mais bon sang, il y a quelqu'un qui nous regarde ?}
{132}{}{Quelqu'un de nouveau. Hep, c'est une affaire privée ! Attrapons-les !}
{133}{}{Pour une fois, je suis d'accord avec toi. Allons-y !}
{134}{}{Hein, et qui va exploiter l'or maintenant, pauv'cloche ?}
{135}{}{Des vacances, ça me ferait vachement de bien.}
{136}{}{Je dois partager cette prison dégueulasse avec ce débile ?}
{137}{}{Caminetto, tes jours sont comptés.}
{138}{}{Tu peux dire adieu à ta tronche de cake.}
{139}{}{Faites-moi sortir d'ici, bordel !}
{140}{}{Eh merde, fais-moi sortir d'ici !}
{141}{}{Eh, Shérif, t'auras l'droit à une turlute si tu me laisses sortir.}
{142}{}{La prochaine fois, je te réglerai ton compte définitivement.}
{143}{}{Que regardes-tu bordel ?}
{144}{}{Que veux-tu, ducon-la-joie ?}
{145}{}{Je ne vais pas vous laisser vous entretuer.}
{146}{}{Je me demandais seulement ce qui se passait ici.}
{147}{}{Il y a un tas de merdes dans ce bar, moi et mes mineurs de la Morningstar, on va les foutre à la rue. Le plus gros étron a même un nom : Caminetto.}
{148}{}{Pourquoi ? Qu'est-ce qui a mis le feu aux poudres ?}
{149}{}{Je vois. Bon, je peux pas vous laisser faire ça. Arrêtez tout de suite.}
{150}{}{Regarde-les, ces têtes de noeud. Qui n'aurait pas envie de les aplatir comme des crêpes ?}
{151}{}{C'est pas une raison. Je vous interdis de vous battre.}
{152}{}{Bon, il y a effectivement un problème. Je comprends. Bonne chance.}
{153}{}{Et que comptes-tu faire, imbécile ?}
{154}{}{Je tue le premier qui cogne.}
{155}{}{Je vais d'abord vous le demander gentiment. Ensuite, je remplirai mon chargeur et je m'exercerai un peu.}
{156}{}{Le Shérif m'a demandé de l'aider car il a une jambe mal en point. Je dois tenir mes engagements.}
{157}{}{Ouais ? Ce Marion est pas mal. Pour lui, je veux bien reporter à plus tard cette baston avec ces tapettes de Kokoweef.}
{158}{}{Merci. Je pensais que vous verriez les choses ainsi. Au revoir.}
{159}{}{Tu te prends pour une espèce de cowboy d'opérette ?! J'aime pas du tout ton attitude de minable.}
{160}{}{Que ça te plaise ou non, c'est pareil. Tu vas venir avec moi jusqu'à la prison ou je vais y traîner ton cadavre, à toi de voir.}
{161}{}{Oh, je regrette. Je ne voulais pas faire preuve d'impolitesse. Je m'en vais maintenant. Au revoir.}
{162}{}{Ah bon ? Je vais te dire une chose. J'irai si tu embarques aussi cette vermine de Caminetto.}
{163}{}{Tu n'es pas en position de proposer un marché.}
{164}{}{Pas mauvaise ton idée. Des barreaux entre vous deux, ça calmera un peu les esprits. Allez, je vous embarque tous les deux !}
{165}{}{Tu souffrirais pas d'une inversion crâne-rectum ? Si tu essaies quoi que ce soit, on te sautera tous dessus juste pour s'échauffer. Ensuite, ça va saigner. Tu crois que le Shérif aimera ça ?}
{166}{}{Non, j'imagine que non.}
{167}{}{Je m'en balance. C'est pas *mon* sang qui va couler.}
{168}{}{Bon, du repos, ça me ferait pas de mal. J'ai trop travaillé ces temps-ci. [Aux autres :] Ca suffit, les gars. Je reviendrai demain au boulot.}
{169}{}{Sage décision.}
{170}{}{T'inquiète pas, j'emmène aussi Caminetto pour te tenir compagnie. Pas vrai, Caminetto ?}
{171}{}{Non, mais tu piges rien ? T'essaies de te mêler de nos affaires mais moi et cette fouine de Caminetto, on va t'agrafer.}
{172}{}{Faut donc que je t'emprisonne toi et Caminetto.}
{173}{}{Faut donc que je vous tue toi et Caminetto.}
{174}{}{Hum, je crois qu'on m'attend ailleurs en ville. C'est une urgence. Au revoir.}
{175}{}{On dirait qu't'es moins bête que t'en as l'air. Mais tu dois l'être quand même, t'es raide comme un piquet. Cours à la maison voir môman et dis-lui que tu n'as pas eu assez de cran pour faire quoi que ce soit.}
{176}{}{Ca suffit ! J'en ai assez de ta grande gueule ! Une dernière chance, tu pars sans faire d'histoires ou je te mets en pièces.}
{177}{}{Ouais, c'est mieux pour tout le monde. Je n'veux surtout pas blesser quelqu'un. Au revoir.}
{178}{}{I see how this is going, you little piece of shit. OK, you can take me in, and Caminetto too.
 (to Caminetto) Right, my little fuckface?}
{179}{}{Je préfère ça.}
{180}{}{Non, c'est trop tard maintenant. Je vais devoir vous régler votre compte à tous les deux.}
{181}{}{Je crois que je botterai les fesses de Caminetto un autre jour.}
