{100}{}{Tu vois une femme fatiguée qui devait être fort jolie plus jeune.}
{101}{}{Tu vois, Lou, la patronne du Malamute Saloon.}
{102}{}{Tu vois une femme d'un âge avancé assez fardée.}
{103}{}{Je veux que tu saches que j'apprécie ce que tu as fait. Comment puis-je t'aider ?}
{104}{}{La prison est bien trop douce après ce qu'a fait ce salaud.}
{105}{}{Je peux pas croire que tu aies laissé partir le salaud qui a amoché une de mes filles. Tu manques pas d'air de revenir ici. Que veux-tu bon sang ?}
{106}{}{T'es toujours aussi con. Pour nous autres, la vie continue. Alors, tu veux quoi au juste ?}
{107}{}{Rappelle-toi bien ceci. Trop d'argent, c'est pas bon pour cette fille. Bon, que veux-tu ?}
{108}{}{Bonjour, je suis Lou. Patronne du Malamute Saloon, la meilleure maison au Nord de 'Frisco.}
{109}{}{Quoi encore ?}
{110}{}{Quoi ?}
{111}{}{Il y a quelque chose qui m'intéresse ici.}
{112}{}{Tu as entendu parler de quelque chose qu'on appelle le Jardin d'Eden en Kit ?}
{113}{}{Bonjour, Lou. Que se passe-t-il dans cette ville ?}
{114}{}{C'est quoi un Malamute ?}
{115}{}{Où est Frisco par rapport à ici ?}
{116}{}{Je donne un coup de main au Shérif. Il m'a dit qu'une de tes filles avait été sacrément amochée ?}
{117}{}{Je regrette, j'ai pas de temps à perdre avec des idiots et qui plus est, j'ai pas de patience. Que veux-tu ?}
{118}{}{Boirrrre ?}
{119}{}{Chambre ?}
{120}{}{Salut.}
{121}{}{Ah, à boire ? C'est $25 pour une bonne bouteille de bière bien fraîche. Je te fais un prix spécial, parce que j'ai un faible pour les simples d'esprit.}
{122}{}{Boirrrre ? [Tu tiens ton porte-monnaie à la main.]}
{123}{}{Chambre ?}
{124}{}{Pas boirrrre. Salut.}
{125}{}{Tu veux une chambre, hein ? Il devrait m'en rester une pour toi. Ca sera $50 pour un coin bien douillet.}
{126}{}{Chambre. [Tu tiens ton porte-monnaie à la main.]}
{127}{}{Boirrrre ?}
{128}{}{Pas chambre. Salut.}
{129}{}{Tu peux rentrer, mais le monstre que t'as comme compagnon de voyage, il reste dehors.}
{130}{}{T'es sourdingue ? Pas de monstres dans mon saloon !}
{131}{}{Ces *trucs* n'entrent pas dans mon saloon. Laisse-les à l'extérieur.}
{132}{}{J'ai pas souvenir d'en avoir entendu parler. Qu'est-ce que c'est ?}
{133}{}{Bien, c'est un appareil utilisé pour... euh, hum. Bon, c'est juste quelque chose que je cherche. Parle-moi d'autre chose.}
{134}{}{Rien d'important. Mieux vaut que j'y aille.}
{135}{}{En fait, on exploite surtout du minerai d'or et on le vend à l'extérieur.}
{136}{}{Vous exploitez du minerai d'or ici ?}
{137}{}{Où l'or est-il commercialisé ?}
{138}{}{C'est intéressant. Parle-moi d'autre chose.}
{139}{}{Oui. Juste dans la partie Nord de la ville, il y a deux mines d'or en exploitation.}
{140}{}{Tu disais que tu vendais du minerai ?}
{141}{}{C'est intéressant. Puis-je te demander autre chose ?}
{142}{}{En fait on échange avec la Cité de l'Abri du minerai d'or contre du matériel médical. Avec la RNC, on échange du minerai contre des Brahmines fraîches et autres victuailles et avec New Reno contre des stimulants et de la bibine.}
{143}{}{Vous exploitez de l'or ici ?}
{144}{}{C'est intéressant. Puis-je te demander autre chose ?}
{145}{}{Juste un gros chien.}
{146}{}{Ah, je vois. Hum, puis-je te demander autre chose.}
{147}{}{Bien sûr. C'est ce que je voulais savoir en fait. Merci. Au revoir.}
{148}{}{San Fransisco est assez loin vers le Sud. Il te reste du chemin à faire. Plein Sud et juste un poil à l'Ouest. Tout près de l'océan. Je sais pas pourquoi quelqu'un de sensé voudrait y aller.}
{149}{}{Pourquoi ? C'est dangereux ?}
{150}{}{C'est intéressant. Puis-je te demander autre chose ?}
{151}{}{Merci pour l'information. Au revoir.}
{152}{}{J'ai entendu tout un tas de choses sur cette ville qui serait pleine d'adeptes fous d'une sorte de religion clandestine.}
{153}{}{Des adeptes toqués ?}
{154}{}{Certaines choses évoluent plus que d'autres. Merci. Au revoir.}
{155}{}{Ouais. C'est vrai. J'ai entendu dire qu'ils construisaient un énorme dispositif qui leur permettra d'établir le contact avec leurs dieux. Ou quelque chose de ce genre. C'est pas sûr. Ca fait loin.}
{156}{}{Il semble que les monuments érigés à la gloire des dieux sont toujours synonymes de problème en fin de compte. Parle-moi d'autre chose.}
{157}{}{C'est tout ce que j'ai besoin de savoir pour l'instant. Merci. Au revoir.}
{158}{}{C'est vrai. Elle est bien amochée. Une si jolie créature. J'espère que tu vas t'en occuper rapidement. Il faudrait pas que ces mineurs pensent qu'ils peuvent s'en tirer aussi facilement. C'est mauvais pour les affaires.}
{159}{}{Puis-je voir la fille ?}
{160}{}{Sais-tu qui a fait ça ?}
{161}{}{Sais-tu ce qui est arrivé ?}
{162}{}{Il y a effectivement un problème. Puis-je te demander autre chose.}
{163}{}{Je l'ai renvoyée. Elle n'était plus bonne à rien pour ce genre de boulot. Personne n'aurait voulu d'elle après ce que ce salaud lui a fait. Je lui ai donné de l'argent et je l'ai laissée partir.}
{164}{}{Sais-tu qui a fait ça ?}
{165}{}{Sais-tu ce qui est arrivé ?}
{166}{}{Je voudrais te demander autre chose.}
{167}{}{T'inquiète pas, je m'en charge. Au revoir.}
{168}{}{Je ne sais pas qui a fait ça mais elle tenait à la main un bon de paie de la mine Morningstar lorsqu'on l'a trouvée et c'est un mineur qui a été vu avec elle pour la dernière fois.}
{169}{}{Puis-je voir la fille ?}
{170}{}{Sais-tu ce qui est arrivé ?}
{171}{}{Un bon de paie de la mine Morningstar ? C'est quoi ça ?}
{172}{}{Je voudrais te demander autre chose.}
{173}{}{T'inquiète pas, je m'en charge. Au revoir.}
{174}{}{Bon, comme il y avait des cris et du barouf, je suis allée voir. Le salaud s'était déjà barré quand je suis arrivée et ma fille était en mauvais état. J'ai appelé le doc et le Shérif. Tu connais la suite.}
{175}{}{Sais-tu qui a fait ça ?}
{176}{}{Puis-je voir la fille ?}
{177}{}{Je voudrais te demander autre chose.}
{178}{}{T'inquiète pas, je m'en charge. Au revoir.}
{179}{}{Au Nord de la ville, Dan McGrew dirige la mine Morningstar. Les mineurs sont souvent payés par acompte ou avec des avoirs venant de chaque mine... enfin, tu sais, des bons. On a retrouvé ma fille avec un de ces bons à la main. Regarde, le voilà. [Elle te tend le bon.]}
{180}{}{Ah, je vois. Puis-je voir la fille ?}
{181}{}{Ah, je vois. Sais-tu ce qui est arrivé ?}
{182}{}{Je voudrais te demander autre chose.}
{183}{}{T'inquiète pas, je m'en charge. Au revoir.}
{184}{}{Bon, c'est pas une mauvaise chose que quelqu'un s'y soit mis. C'est mauvais sur toute la ligne, ce genre de choses. J'espère que tu feras payer à ce salaud ce qu'il a fait à ma fille. Arrange-toi pour qu'il n'ait plus l'occasion de le refaire.}
{185}{}{Bon, je ferai de mon mieux. Autre chose, voyons.}
{186}{}{Je verrai ce que je peux faire. Au revoir.}
{187}{}{Que puis-je faire pour toi ? Tu veux un lit vide ou un lit plein ? De la bibine ou autre chose peut-être ?}
{188}{}{J'aimerais une chambre avec un lit vide, Lou.}
{189}{}{Un lit plein. Ca a l'air intéressant. Donne-moi plus de détails.}
{190}{}{De la bibine et d'autres trucs. Ouais, ce serait le pied. Tope-là.}
{191}{}{Hum, je peux te demander autre chose ?}
{192}{}{Ca ira pour toi, où y a-t-il autre chose que tu veux acheter ?}
{193}{}{On dirait que tu as du mal à te décider. C'est bon, ou tu veux encore jeter un coup d'oeil ?}
{194}{}{Non, j'ai tout ce qu'il me faut pour l'instant. Merci. Encore une question.}
{195}{}{Hum, laisse-moi encore regarder ton stock.}
{196}{}{Merci Lou, ce sera tout pour l'instant. Au revoir.}
{197}{}{Tu veux roupiller, c'est ça ? Ca te coûtera $40 avec des draps frais, pratiquement propres. Ca t'intéresse toujours ?}
{198}{}{Ca marche, Lou.}
{199}{}{Hum, finalement je n'ai pas tant besoin de dormir que ça. Puis-je te poser une autre question ?}
{200}{}{Je n'ai pas l'argent qu'il faut maintenant. Puis-je te poser une autre question.}
{201}{}{Tu la connais plutôt bien Fannie, non ? Tu n'as qu'à aller lui parler. Elle est dans le fond quelque part.}
{202}{}{Ecoute. Tu es un porte-poisse. Après ce qui est arrivé à Fannie Mae, aucune autre de mes filles n'a envie d'aller avec toi... et je les comprends.}
{203}{}{Tu cherches quelqu'un pour t'aider à réchauffer ce grand lit ? Voyons voir qui j'ai de disponible. Hum, pourquoi t'essaies pas Fannie Mae ? Elle se trouve dans le fond, quelque part. Tu n'as qu'à t'arranger directement avec elle.}
{204}{}{Bonne idée. J'y vais. Au revoir.}
{205}{}{Mais, j'ai pas... D'accord. Au revoir.}
{206}{}{Toi et Fannie vous avez déjà fait affaire. Pourquoi tu n'irais pas la voir ? Elle est dans le fond quelque part.}
{207}{}{Ecoute. Tu es un porte-poisse. Après ce qui est arrivé à Fannie Mae, aucune autre de mes filles n'a envie d'aller avec toi... et je les comprends.}
{208}{}{On n'a que des filles qui travaillent ici. Si ça te convient, un sou est un sou. Essaie de parler à Fannie Mae. Elle se trouve dans le fond quelque part. Débrouille-toi avec elle.}
{209}{}{Bonne idée. J'y vais. Au revoir.}
{210}{}{Mais, j'ai pas... D'accord. Au revoir.}
{211}{}{J'arrive pas à croire que t'as été assez débile pour donner à Fannie autant d'argent en même temps, à tel point qu'elle a fait une overdose. C'est pas croyable ! T'es vraiment trop stupide !}
{212}{}{Je savais pas. Juré. Allez, Lou... J'ai autre chose à te demander.}
{213}{}{Ce qu'elle a fait de sa vie, ça ne regarde qu'elle. Au revoir.}
{214}{}{Je lui ai permis de s'évader un peu de cette existence de merde. T'es pas une sainte non plus, Lou. Au revoir.}
{215}{}{Alors, c'est toi la poire qui a donné à Fannie tout cet argent. Je ne l'aurais pas fait à ta place. Tu ne l'aides pas en faisant ça.}
{216}{}{Que veux-tu dire ?}
{217}{}{Je l'aide à se refaire une nouvelle vie.}
{218}{}{Ouais, peu importe. Parlons d'autre chose.}
{219}{}{Fannie a un problème et l'argent n'est pas la solution. J'ai pas envie de te briser le coeur, mais Fannie t'entube parce que t'es une bonne poire. L'argent qu'elle veut, c'est juste pour acheter du Jet. Beaucoup trop de ce foutu Jet.}
{220}{}{Ce qui t'inquiète en fait, c'est de perdre une de tes meilleures filles. Tu veux simplement les maintenir dans leur misère.}
{221}{}{Ouais, pour sûr. J'en ai entendu assez. Au revoir.}
{222}{}{Tu l'aides à se foutre en l'air, c'est tout ce que tu fais avec ton argent. Elle achète bien trop de Jet. Si tu continues à lui filer du fric comme ça, un de ces jours elle fera une overdose...}
{223}{}{Hum, je crois que je vais y réfléchir.}
{224}{}{J'y réfléchirai. Au revoir.}
{225}{}{Tu peux penser ce que tu veux. Je voulais simplement te dresser un portrait réaliste de la situation. Tu en feras ce que tu voudras.}
{226}{}{Tout ça n'est pas nouveau. Passons à autre chose.}
{227}{}{Merci, je vais réfléchir à ce que tu m'as dit. Puis-je te poser une autre question ?}
{228}{}{Il faudra que j'y réfléchisse. Au revoir.}
{229}{}{Hum, j'ai peut-être une solution à ça. [Tu tends à Lou l'antidote contre le Jet.]}
{230}{}{C'est quoi, ça ?}
{231}{}{Ca supprimera sa dépendance au Jet. La prochaine fois qu'elle commande un verre, arrange-toi pour en mélanger avec.}
{232}{}{Bien... D'accord. Puis-je faire quelque chose d'autre pour toi ?}
{233}{}{Oui, il me faudrait autre chose.}
{234}{}{S'passe quoi en ville, en ce moment ?}
{300}{}{Tu as aidé Fannie à vaincre sa dépendance au Jet.}
{301}{}{Salut.}
{310}{}{J'ai peut-être quelque chose qui puisse aider Fannie. [Donner à Lou l'antidote au Jet]}
{1103}{}{Salut, je suis Lou. Patronne du Malamute Saloon, la meilleure maison au Nord de 'Frisco. Je tenais à ce que tu saches que je suis reconnaissante pour ce que t'as fait. Que puis-je faire pour toi ?}
{1104}{}{Salut, je suis Lou. Patronne du Malamute Saloon, la meilleure maison au Nord de 'Frisco. La prison est bien trop douce après ce qu'a fait ce salaud.}
{1105}{}{Salut, je suis Lou. Patronne du Malamute Saloon, la meilleure maison au Nord de 'Frisco. Je peux pas croire que tu aies laissé partir le salaud qui a amoché une de mes filles. Tu manques pas d'air de revenir ici. Que veux-tu bon sang ?}
{1106}{}{T'es toujours aussi con. Pour nous autres, la vie continue. Je suis Lou. Patronne du Malamute Saloon, la meilleure maison au Nord de 'Frisco. Alors, que veux-tu au juste ?}
{1107}{}{Je suis Lou. Patronne du Malamute Saloon, la meilleure maison au Nord de 'Frisco. Rappelle-toi bien ceci. Trop d'argent, c'est pas bon pour cette fille. Bon, que veux-tu ?}
