{100}{}{Tu vois un homme grassouillet, qui a l'air d'un employé de bureau.}
{101}{}{Tu vois Nording le responsable de la paie.}
{102}{}{Tu vois un petit pigeon d'homme, nerveux, grassouillet.}
{103}{}{Comme tu as abandonné la caravane, on ne te paiera pas.}
{104}{}{Euh, des choses manquaient dans la caravane. Les arrêtés de la RNC ne m'autorisent pas à payer quelqu'un qui vole. Je regrette.}
{105}{}{On m'accuse de vol ? Pas sympa comme remarque ! T'es vraiment ingrat ! C'est bon, je me tire.}
{106}{}{Un de ces jours, tu regretteras qu'on se soit rencontrés. Salut.}
{107}{}{Je ne peux pas récompenser une caravane qui a eu tant de déboires. Tu n'auras rien de moi.}
{108}{}{Espèce de pourriture ! Tu paieras pour m'avoir volé ma part ! Salut.}
{109}{}{Bon, la chance, ça tourne. Ce coup-ci, c'était pas ton tour. Salut.}
{110}{}{Cette caravane a été un fiasco complet. Je ne peux pas te donner plus de $500.}
{111}{}{C'est toujours mieux que rien. Salut.}
{112}{}{Ordure ! Personne n'aurait fait mieux. Tu regretteras d'avoir osé m'arnaquer. Salut.}
{113}{}{Ce n'était pas si mal. Voilà tes $1500. Je ne sais pas quand on trouvera quelqu'un d'autre pour la reprendre en main, mais il y aura du travail pour toi si ça se fait.}
{114}{}{Passer encore autant de temps à regarder le cul d'une Brahmine, très peu pour moi ! Au revoir.}
{115}{}{C'était pas si mal. A un de ces jours. Au revoir.}
{116}{}{Cette caravane a bien marché même si tu as perdu Stanwell. Dans la vie, y'a toujours des hauts et des bas. Voilà tes $100 plus les $50 de Stanwell.}
{117}{}{C'est sympa de rencontrer quelqu'un qui sait reconnaître et apprécier la qualité. A plus tard, peut-être. Au revoir.}
{118}{}{Je ne crache jamais sur un petit extra. Merci et au revoir.}
{119}{}{Si tu étais en RNC, on te garderait dans une jolie chambre d'hôpital et tu n'aurais pas besoin d'affronter le monde extérieur. On t'a au moins permis de voyager en sécurité. Au revoir.}
{120}{}{Okéé ?}
{121}{}{C'est une honte que Stanwell ait été tué. Je m'appelle Nording. Je réglerai la dette.}
{122}{}{Euh, merci.}
{123}{}{C'est une honte que Stanwell ait été tué.}
