{100}{}{Tu vois un type petit et tâché de graisse.}
{101}{}{C'est Buster l'armurier que tu vois là.}
{102}{}{Les habits de ce gars sont en lambeaux et il a des marques de poudre explosive sur les mains, les bras et le visage. Pourtant, il a l'air plutôt gai.}
{103}{}{Hé ! Bienvenue chez Buster, le grand et luxueux Bazar de l'Armement ! Je m'appelle Buster, l'unique, le vrai. J'ai de la bonne marchandise ici.}
{104}{}{Hé ! Tu es de retour ? Je peux t'aider ?}
{105}{}{Rien d'autre ?}
{106}{}{Vouloir pistolet.}
{107}{}{Qu'est-ce que t'as ?}
{108}{}{Tu peux peut-être me proposer quelque chose de spécial ?}
{109}{}{J'ai quelques questions à te poser.}
{110}{}{Salut.}
{111}{}{Du premier choix !}
{112}{}{C'est une très bonne affaire !}
{113}{}{Je veux pas te presser, mais j'ai du travail.}
{114}{}{Bien sûr, que veux-tu savoir ?}
{115}{}{Parle-moi de la RNC.}
{116}{}{Que se passe-t-il avec Merk ?}
{117}{}{Que peux-tu me dire à propos de Roger Westin ?}
{118}{}{Je voudrais rencontrer le Vieux Carlson. Tu connais quelqu'un qui pourrait m'aider ?}
{119}{}{As-tu un J.E.K ?}
{120}{}{C'est bien beau tout ça, mais ici, c'est pas la charité.}
{121}{}{J'ai peut-être un viseur Triveld x20 qui irait très bien sur un fusil de chasse, si quelqu'un était intéressé. Je le laisse pour pas cher : $500.}
{122}{}{Hé ! Tu m'as déjà vidé les poches !}
{123}{}{Ok, ça marche.}
{124}{}{Non, merci.}
{125}{}{C'est la République de Nouvelle Californie. La présidente Tandi et les autres clament leur désir de rebâtir le bon vieux temps. Si tu veux mon avis, ils essaient juste de s'en mettre plein les poches. Oh, j'ai pas à me plaindre, j'étais même pas né en ce temps-là. Mais ils sont un peu coincés, ils aiment pas les esclaves, les jeux, tout ça. C'est pour ça que je me suis installé ici. J'aime pas les contraintes, j'en ai jamais eu.}
{126}{}{Je vois.}
{127}{}{Salut.}
{128}{}{Je ne me frotte pas à M. Merk et ça ne te rapportera rien de colporter des ragots sur lui. Si t'as des questions, va les poser au Rawhide.}
{129}{}{Je vois.}
{130}{}{Salut.}
{131}{}{Roger Westin, le gars du Congrès ? Il a des terres à l'Ouest de la ville. Il est dans l'élevage de Brahmines. C'est une huile dans l'Association des Eleveurs. Il a toujours besoin de bras, si tu cherches du boulot.}
{132}{}{Je vois.}
{133}{}{Salut.}
{134}{}{C'est drôle que tu demandes ça après ce qui est arrivé à Roger Westin. Moi je sais rien, mais tu peux toujours aller demander à Merk, au Rawhide. Il pourra peut-être t'aider.}
{135}{}{Je vois.}
{136}{}{Salut.}
{137}{}{Une de ces importations d'avant-guerre ? Laisse-moi deviner... des munitions 14 mm ? Non, j'en ai pas.}
{138}{}{Je vois.}
{139}{}{Salut.}
{140}{}{Ecoute, je peux le faire que sur un fusil de chasse. A cause de la monture, tu comprends ?}
{141}{}{Je vois.}
{142}{}{Salut.}
{143}{}{C'est fermé. Casse-toi.}
{144}{}{Reviens à une heure plus raisonnable, d'accord ?}
{145}{}{Reviens à l'ouverture et referme le rabat de la tente en sortant.}
{146}{}{C'est fermé.}
{147}{}{Ecoute, sors d'ici sinon M. .45 va se fâcher !}
{148}{}{Bas les pattes...}
{149}{}{Voilà ce que j'ai sur cette étagère. Si t'as besoin de quelque chose d'autre, regarde sur les autres étagères, tu y trouveras peut-être ton bonheur...}
