{100}{}{Un mutant apprivoisé.}
{101}{}{C'est Lenny, tu te souviens ? L'odieux personnage.}
{102}{}{Hou la... Ce gars est un sacré numéro. Il est vert, moche et il a plus de cicatrices qu'une vieille traînée. C'est un dur à cuire, c'est sûr.}
{103}{}{Moi, c'est Lenny. Et toi, t'es que de la merde. Barre-toi de là.}
{104}{}{Pourquoi embêtes-tu Lenny, petite larve ?}
{105}{}{Que veux-tu de Lenny, vaurien d'humain ?}
{106}{}{Continue à m'emmerder et je te renvoie chez ton créateur.}
{107}{}{Enchanté ! Moi, c'est Lenny et toi, tu dois être "larve". Ha ! Ha !}
{108}{}{Dis à ton maître mutant que mon nom est Lenny, esclave.}
{109}{}{Hé, frère mutant, Lenny se demande pourquoi tu traînes avec ces limaces d'humains !}
{110}{}{Lenny parle pas à ceux qui se servent des mutants comme esclaves !}
{111}{}{Lenny dit que toi et ton lèche-bottes de mutant, Tom, pouvez aller au diable !}
{112}{}{Fais gaffe. Lenny n'est pas apprivoisé comme le mutant que tu as là.}
{113}{}{Hé, le petit humain visage pâle est revenu !}
{114}{}{Lâche-moi, sale humain !}
{115}{}{Va te faire voir, imbécile !}
{116}{}{Qu'est-ce que t'as ? Il te faut quelqu'un pour changer tes couches ?}
{117}{}{T'es aussi lourd qu'un tas de briques !}
