{100}{}{Un de ces types qui pensent plus avec leurs poings qu'avec leur cerveau.}
{101}{}{Hmmm. Un des gardes de Merk.}
{102}{}{Grand. Balèze. Simplet. Un garde.}
{103}{}{Recule ! Laisse la place à Merk.}
{104}{}{Euh...}
{105}{}{Je n'ai pas le droit de parler pendant mon service.}
{106}{}{Tu nous causes des problèmes. Je fais mon boulot. Compris ?}
{107}{}{Circule, il y a rien à voir.}
{108}{}{Ne me dérange pas.}
{109}{}{M.Merk ne veut pas être dérangé.}
