{100}{}{Tu vois un homme en armure de combat.}
{101}{}{Tu vois une femme en armure de combat.}
{102}{}{Il porte un badge avec l'inscription RNC.}
{103}{}{Elle porte un badge indiquant RNC.}
{200}{}{Salut camarade Ranger. T'es ici pour passer la nuit ?}
{201}{}{T'as tué des esclavagistes aujourd'hui ?}
{202}{}{Nous avons libéré une douzaine d'esclaves aujourd'hui.}
{203}{}{Protéger le désert est un travail pénible, mais quelqu'un doit aller le faire.}
{204}{}{C'est bien de t'avoir à bord. Reste aussi longtemps que tu veux.}
{205}{}{J'ai entendu ce qui est arrivé à Metzger. Bon travail !}
{300}{}{C'est un esclavagiste, à l'attaque !}
{301}{}{Merde, on nous attaque !}
{400}{}{Salut l'ami.}
{401}{}{C'est une propriété privée. Ne traîne pas trop longtemps.}
{402}{}{Tu aimes les esclavagistes ? J'espère que non... pour ta sécurité.}
{500}{}{Quoi ?! Les Esclavagistes ? Par quelle malédiction nous ont-ils trouvés ? Nous devons nous défendre. A l'attaque !}
{501}{}{Attendez ! Je suis de votre côté. Je vous apportais juste quelques cibles d'exercices. [Se tournant vers les esclavagistes.] Désolé les mecs, je suis ce genre de personne. [Tu attaques les esclavagistes.]}
{502}{}{Ca peut être marrant ! [Tu attaques les Rangers.]}
{600}{}{Tu détruis l'abri des Rangers.}
