{100}{}{Tu vois une personne vêtue d'habits de travail poussiéreux.}
{101}{}{C'est un des ouvriers du ranch de Westin.}
{102}{}{Ca pourrait être un ouvrier de ranch comme un tueur à gages. En tout cas, on dirait qu'il cherche la bagarre.}
{103}{}{T'as le droit de te balader par ici ?}
{104}{}{Va parler à Félix si tu cherches du boulot.}
{105}{}{J'en ai marre des Brahmines.}
{106}{}{J'ai entendu dire que les Bishop se sont fait le patron.}
{107}{}{Tu veux parler à quelqu'un ? Va voir le contremaître, Félix.}
{108}{}{You ain't with the Bishops, are you?}
{109}{}{On sait que c'était un meurtre. On attrape la vipère et on la fait mourir à petit feu.}
{110}{}{Félix jure que les Bishop sont derrière tout ça. Il dit que c'est une histoire d'argent.}
{111}{}{Bon, c'est l'heure de partir, on dirait. Ca sent le roussi par ici.}
