{100}{}{Tu vois une plaque relevée qui semble faire partie d'un piège.}

# NPC name prepends this line
{101}{}{ voit une plaque relevée qui semble faire partie d'un piège.}

{102}{}{Tu vois une plaque relevée.}

# NPC name prepends this line
{103}{}{ voit une plaque relevée.}

{104}{}{Tu déclenches le piège et évites de justesse le projectile provenant du mur.}

# NPC name prepends this line
{105}{}{ déclenche le piège et évite de justesse le projectile provenant du mur.}

{106}{}{Tu vois une plaque relevée qui semble inoffensive.}
