{100}{}{Tu vois un tableau d'affichage.}
{101}{}{Tu vois sur un tableau d'affichage des textes de loi de la RNC.}
{102}{}{Voici un tableau d'affichage sur lequel plusieurs feuilles sont punaisées. Bien en évidence, on peut voir les textes de loi de la RNC.}
{103}{}{Bienvenue en République de Nouvelle Californie ! Avant de pénétrer dans notre belle cité, prenez un moment pour lire le règlement ci-dessous.}
{104}{}{Le port d'une arme visible n'est pas autorisé en ville.}
{105}{}{Toute personne sous l'emprise de l'alcool ou d'autres substances sera arrêtée.}
{106}{}{L'esclavage, le jeu et la prostitution ne sont pas autorisés en ville.}
{107}{}{Nul n'est censé ignorer la loi. Les petits cons recevront une raclée identique aux petits malins.}
{108}{}{Si tu ne peux pas respecter ces règles, alors casse-toi !}
{109}{}{Tu devrais ranger tes armes. On ne plaisante pas.}
{110}{}{Tout bon citoyen obéit à la loi.}
{111}{}{[Terminé]}
{112}{}{[J'en ai assez lu]}
{113}{}{Ca s'annonce mal pour tes activités de détente.}
{114}{}{Bien. Tu ne te feras pas harceler par des poivrots ou des junkies en manque.}
{115}{}{[Terminé]}
{116}{}{[J'en ai assez lu]}
{117}{}{Et voilà un bon plan qui tombe à l'eau !}
{118}{}{On dirait qu'ils essaient de créer une gentille communauté honorable et respectable.}
{119}{}{[Terminé]}
{120}{}{[J'en ai assez lu]}
{121}{}{C'est dur à avaler. On verra si ce n'est pas trop gros pour leur petit gosier.}
{122}{}{L'égalité devant la loi est une bonne chose.}
{123}{}{[Terminé]}
{124}{}{[J'en ai assez lu]}
{125}{}{"Apprendre le respect à ces mecs" gagne des places dans ta liste de choses à faire.}
{126}{}{C'est un peu abrupt, mais ça a le mérite d'être clair.}
{127}{}{[Terminé]}
{128}{}{[J'en ai assez lu]}
{130}{}{Moi mal à la tête. Trop à lire.}
