{100}{}{Tu vois un guerrier}
{101}{}{Tu vois Serin.}
{102}{}{Il semble salement amoché et a une jambe cassée.}
{103}{}{Tu vois Serin. Il semble salement amoché et a une jambe cassée.}
{104}{}{Tu vois Serin. Sa jambe est bandée et il boitille.}
{105}{}{Tu vois Serin. Il semble aller mieux et dort profondément.}
{106}{}{Tu vois Serin. Il semble s'être bien remis de ses blessures.}
{200}{}{[Gémissement.] Meurs monstre !! Tu ne vas p...}
{201}{}{Calme toi. Tout va bien maintenant. Le gecko est mort.}
{202}{}{Quoi !? Oh, merci aux esprits ! J'ai cru que j'allais pas m'en sortir.}
{203}{}{Que s'est-il passé ?}
{204}{}{Jerem et moi on est parti chasser pour la tribu. Nous y allons toutes les semaines. Il y a un passage dans la grotte qui mène à un petit champ où vivent beaucoup de geckos. Mais la chasse s'est pas passée comme prévu et nous avons dû fuir. Plusieurs geckos énervés étaient sur nos traces et nous avons couru sur le chemin en criant à l'aide. [Il marque une pause un instant et semble souffrir alors qu'il se masse la jambe.]}
{205}{}{Je t'en prie, parle.}
{206}{}{On savait que ce passage ne tiendrait plus longtemps mais c'est un gros raccourci. Il y a un petit siphon juste au-dessus du passage et des gouttes d'eau gouttaient vers l'entrée. Mais des rochers et de la boue sont tombés du plafond. Bref, nos cris ont dû précipiter l'effondrement car au moment où on courait, des rochers ont commencé à tomber de partout.}
{207}{}{[Continue]}
{208}{}{Pauvre Jerem. J'ai vu un énorme rocher l'écraser comme un insecte. J'ai pu l'éviter mais un gecko m'a mordu et je suis tombé en laissant échapper ma lance. Sans mon arme, j'ai cru que j'allais lui servir de repas. Mais les esprits avaient d'autres plans. Une dernière pierre lui est tombée sur la tête en le tuant. Mais le caillou est aussi tombé sur ma jambe.}
{209}{}{[Continue]}
{210}{}{J'étais au sol et désarmé quand j'ai entendu quelques chose s'approcher de moi dans le noir. C'était un gros gecko en colère. Il était un peu sonné par l'éboulement mais cela l'avait rendu encore plus furieux. C'est là que tu es arrivé et il a fui. J'ai une dette envers toi.}
{211}{}{Quelle histoire. Heureusement tu es toujours en vie. Comment va ta jambe ?}
{212}{}{Pas très bien. On dirait que cette pierre est plus dur que l'os de ma jambe. Je sais pas si je vais pouvoir me lever et marcher.}
{213}{}{Je suis un assez bon docteur, tu sais. Laisse moi examiner ta jambe.}
{214}{}{Je suis plutôt costaud. Je vais te porter hors d'ici et t'amener au shaman afin qu'il examine ta jambe.}
{215}{}{Peut-être qu'il vaudrait mieux laisser un professionnel s'occuper de ça. Laisse moi aller chercher de l'aide pour te faire sortir d'ici.}
{216}{}{Hum... Je ne suis pas assez fort pour te transporter à travers la grotte, mais ce n'est pas le cas de Sulik. [A Sulik] Porte ce gars hors d'ici.}
{217}{}{Hum... Je ne suis pas assez fort pour te transporter à travers la grotte, mais ce n'est pas le cas de Marcus. [A Marcus] Porte ce gars hors d'ici.}
{218}{}{[Tu examines la jambe du guerrier. Elle est terriblement écorchée et l'os est visible par endroits. Tes compétences te permettent d'arrêter les saignements et tu commences à soigner sa jambe.]}
{219}{}{[Après environ 15 minutes d'opérations douloureuses la jambe est en meilleur état. On dirait que cet homme sera capable de remarcher.]}
{220}{}{Bien, ça devrait le faire. Tu devras rester au repos complet durant deux jours pour guérir totalement. Ne t'appuie pas trop sur cette jambe pendant ce temps et tu devrais ensuite aller mieux.}
{221}{}{Les esprits te protègent l'ami ! Je vais pouvoir me rendre auprès du shaman. On se revoit au camp.}
{222}{}{[Terminé]}
{300}{}{Merci pour ton aide. Je te retrouverai au camp.}
{400}{}{Merci de m'avoir sauvé. Tu es quelqu'un de bien.}
{500}{}{zzzZZzzz...}
{501}{}{...zzZZZZzz...zzz...}
{600}{}{Tu as soigné la jambe de Serin.}
{700}{}{Il a besoin de plus d'aide que je ne peux lui offrir. Je ferai mieux de partir.}
{1000}{}{Ca fait plaisir de te voir dans le coin, le héros.}
{1001}{}{Je n'oublierais jamais ce que tu as fait pour moi, héros.}
