{100}{}{Tu vois Amanda.}
{101}{}{Tu vois une femme à l'air fatiguée. On dirait qu'elle a pleuré.}
{102}{}{Tu vois Amanda.}
{103}{}{Tu vois une femme à l'air fatiguée. On dirait qu'elle a pleuré.}
{104}{}{Tu vois Amanda. Elle a l'air beaucoup plus heureuse, maintenant que Joshua est libre.}
{105}{}{Tu vois Amanda.}
{106}{}{Tu vois Amanda. Elle a l'air beaucoup plus heureuse, maintenant que Joshua est libre.}
{107}{}{Oh, Joshua...}
{108}{}{Que vais-je faire ?}
{109}{}{On a plus du tout d'argent...}
{110}{}{Si seulement les citoyens voulaient bien le laisser partir...}
{111}{}{Joshua, je suis tellement contente que tu sois libre. J'étais si inquiète...}
{112}{}{Je regrette, je n'ai rien à te donner.}
{113}{}{Laisse-moi tranquille, s'il te plaît, ou j'appelle les gardes.}
{114}{}{Que veux-tu ?}
{115}{}{Ca va bien ? Tu n'as pas l'air dans ton assiette.}
{116}{}{Rien. Excuse-moi de te déranger.}
{117}{}{Je... Eh bien, je... C'est mon mari, Joshua. Il... s'est mis dans de sales draps... au bar. Il a accidentellement frappé un citoyen et il a été arrêté. Il voulait pas faire de mal, mais il avait bu, et...}
{118}{}{Arrêté ? Où est-il maintenant ?}
{119}{}{S'il était saoul et qu'il a agressé quelqu'un, c'est normal qu'il se soit fait arrêter.}
{120}{}{Je regrette. J'espère qu'ils le laisseront partir.}
{121}{}{Dans la Cité, au Centre de répartition des domestiques... Ils ont dit qu'il pourrait purger sa peine en travaillant comme domestique, mais que ça prendrait des années !}
{122}{}{Que peut-on faire ?}
{123}{}{S'il était saoul et qu'il a agressé quelqu'un, c'est normal qu'il se soit fait arrêter.}
{124}{}{Je regrette. J'espère qu'ils le laisseront partir.}
{125}{}{Mais c'était un accident ! Je... Il ne voulait pas faire ça !}
{126}{}{Où est-il maintenant ?}
{127}{}{Il ne voulait agresser personne ? Bien sûr. Peut-être que ça te servira de leçon, à toi.}
{128}{}{Je regrette. J'espère qu'ils le laisseront partir.}
{129}{}{Il ne me reste plus beaucoup d'argent, et il va falloir qu'on parte bientôt si on n'a pas les moyens de se payer la protection des gardes. Ils ont dit que si on voulait rester avec Joshua, ils pourraient faire de nous des domestiques aussi...}
{130}{}{Ce serait peut-être une solution. On traite plutôt bien les domestiques à la Cité de l'Abri, non ?}
{131}{}{Attends, je vais voir ce que je peux faire, d'accord ? Je peux peut-être parler à quelqu'un au Centre de répartition.}
{132}{}{Je pourrais t'aider. Mais ça va te coûter cher.}
{133}{}{Je regrette. J'espère qu'ils le laisseront partir.}
{134}{}{Je veux pas que mon fils soit élevé comme un esclave ! On est venus à la Cité de l'Abri parce qu'on avait entendu dire que c'était une ville libre... Mais on arrive ici... et il y a toutes ces lois, et ces redevances aux gardes, et... c'est pas du tout comme on nous avait dit.}
{135}{}{Attends, je vais voir ce que je peux faire, d'accord ? Je peux peut-être parler à quelqu'un au Centre de répartition.}
{136}{}{Je regrette. J'espère qu'ils le laisseront partir.}
{137}{}{Le responsable, c'est Barkus, l'officier Barkus. J'ai même pas pu entrer dans la Cité pour le voir. Je ne sais même pas si Joshua va bien ! Je...}
{138}{}{Ne t'inquiète pas. Je vais voir ce que je peux faire.}
{139}{}{Mais, je n'ai pas beaucoup d'argent et...}
{140}{}{Je ne pensais pas à de l'argent.}
{141}{}{Tant pis. Je vais peut-être pouvoir parler à quelqu'un du Centre de répartition.}
{142}{}{Je regrette. Peut-être qu'ils le libéreront tout simplement. Au revoir. }
{143}{}{Que veux-tu... ? Oh, non. Je... ne pourrais pas. Je veux dire, je...}
{144}{}{Tu veux faire libérer ton mari, oui ou non ? Ton mari n'en saura jamais rien.}
{145}{}{Tant pis. Je vais peut-être pouvoir parler à quelqu'un du Centre de répartition.}
{146}{}{Je regrette. J'ai l'impression que ton mari ne sera jamais libéré. Au revoir.}
{147}{}{Si tu promets de faire libérer mon mari, je... je... Très bien. Je... ferme le rabat de la tente. Je... crois que mon fils est encore en train de jouer dehors, on ne sera pas dérangés.}
{148}{}{Ne t'inquiète pas. Je ferai libérer ton mari. Une fois que j'aurai reçu mon dû.}
{149}{}{Laisse tomber. Peut-être que je pourrai parler à quelqu'un du Centre de répartition.}
{150}{}{Tant pis. Oublie qu'on s'est rencontrés.}
{151}{}{Hé, et moi alors ?!}
{152}{}{Je t'en prie, sauve Joshua. Il est dans la Cité, au Centre de répartition des domestiques.}
{153}{}{Merci d'avoir sauvé mon mari ! Je t'en prie... accepte ceci comme récompense. Ce n'est pas beaucoup, mais...}
{154}{}{Merci encore d'avoir sauvé mon mari. On va partir d'ici peu.}
{155}{}{Heu... Merci d'avoir sauvé mon mari... Je t'en prie, ne lui dis rien de ce qui s'est passé entre nous.}
