{100}{}{Tu vois un homme très âgé avec une lueur de folie dans l'oeil.}
{101}{}{Tu vois le Vieux Joe, l'idiot savant local.}
{102}{}{Salut ! Ca fait longtemps que je t'avais pas vu !}
{103}{}{Je te connais ??}
{104}{}{Ah, c'est sûr, ça fait un bail ! Alors, qu'est-ce que tu deviens ?}
{105}{}{Hé bien, ça faisait longtemps ! Qu'est-ce tu faisais ?}
{106}{}{Des choses et d'autres... Tu me connais d'où ?}
{107}{}{Ecoute, vieil homme, je ne sais absolument pas qui tu es.}
{108}{}{C'est ça... J'ai atterri ici, dans cette ville-abandonnée-de-dieu, comme ils disent... C'est plus comme dans le bon vieux temps. Non monsieur !}
{109}{}{Ouaip, le bon vieux temps... Tu te souviens de cette fois où...}
{110}{}{C'est plus pareil, c'est sûr. Qu'avait-on fait, déjà ?}
{111}{}{Tu te souviens pas de moi, c'est ça ? Ouais... T'as l'air plus jeune...}
{112}{}{Qu'essaies-tu de me dire ?}
{113}{}{Tu m'as l'air si familier... Ca doit être mes vieux yeux fatigués. Bonne journée à toi...}
{114}{}{Euh, ouais... Salut...}
{115}{}{Ouais, pour sûr on lui a fait sa fête, au Maître ! Mais après, j'étais recherché, et j'ai dû bouger, changer de nom...}
{116}{}{J'ai vécu dans un petit village...}
{117}{}{Bon, surveille tes arrières par ici... Les choses sont devenues bizarres ces derniers temps...}
{118}{}{Ok, merci !}
{119}{}{Ouais, j'ai recherché ton Abri un certain temps, mais en vain... Alors, tu dois avoir des tas d'histoires à raconter à ton vieil ami Ian, non ?}
{120}{}{Ian ?}
{121}{}{Ouais, Ian. Tu te souviens pas de moi ? Ca remonte à loin, maintenant... Tu te souviendrais pas de ton meilleur pote ? Bon, à part pour les tirs dans le dos, je m'en excuse aujourd'hui encore.}
{122}{}{Désolé, mais tu dois penser que je suis l'habitant de l'Abri. C'est lui qui a fondé mon village.}
{123}{}{Je commence à comprendre... C'est bien de savoir que mon vieil ami a fait de bonnes choses. Oh, le vieux Ian a un conseil pour toi... Fais gaffe dans les parages. Les choses dégénèrent en ce moment...}
{124}{}{Que se passe-t-il ?}
{125}{}{Eh bien, les citoyens de l'Abri tiennent à leurs communautés *d'origine*, et ils ne s'intéressent pas du tout à des gens comme toi et moi... Tiens, prends ça, on sait jamais. Pour te protéger si les choses tournent mal... Il ne faudrait pas qu'on te voie avec ce vieux fou de Ian... Tu devrais partir.}
{126}{}{Merci pour ton aide. Salut.}
{127}{}{J'ai besoin de repos...}
{128}{}{Si familier...}
{129}{}{Laisse-moi, maintenant...}
{130}{}{Tu ferais mieux d'y aller maintenant...}
{131}{}{Ils vont se poser des questions s'ils nous voient encore parler...}
{132}{}{Allez, vas-y. Rends mon vieux pote fier.}

{133}{}{Merci. Encore une chose cependant. J'essaie d'aider le petit village au Nord-Est d'ici. Connar m'a dit d'en parler avec toi.}
{134}{}{Connar, hein ? Un gars bien. Oui, il m'a envoyé ici il y a un moment pour garder un oeil sur ce qui se passe. Et que veut-il exactement ?}
{135}{}{Il essaie de trouver des armes. Il a dit que si lui et ses gars pouvaient obtenir quelques armes, ils pourraient garder les patrouilles de la Cité à distance.}
{136}{}{Ah, alors c'est son nouveau plan, hein ? Bon, va à l'épicerie générale et parle avec Harry. Il a une magnifique cargaison toute indiquée pour une telle occasion. Dis-lui que Connar t'a envoyé. Il saura quoi faire. Cependant, je ne pense pas que ce soit la meilleure solution.}
{137}{}{Je vais parler à Harry dans ce cas. Prends soin de toi l'ami.}
{138}{}{Quoi, que veux-tu dire ?}
{139}{}{Eh bien, Connar et ses gars devraient pouvoir tenir les patrouilles à distance pendant un moment, mais ça ne sera pas suffisant. La Ville a des ressources presque illimitées. Parfois, il vaut mieux parler franchement et essayer de raisonner avec les gens. C'est une leçon que j'ai apprise de mon vieil ami, l'Habitant de l'Abri. McClure, membre principal du Conseil, s'est révélé être un homme raisonnable. Peut-être qu'on peut s'entendre avec lui ?}
{140}{}{Hmm... Il va falloir que je prenne ça en compte. Merci pour tout, salut.}
{141}{}{Je vais peut-être aller lui parler dans ce cas. Je suis quand même curieux à propos des rataupes qui gardent le village.}
{142}{}{Ouais, et alors ?}
{143}{}{Une idée d'où elles viennent et de qui les contrôle ?}
{144}{}{Je n'en suis pas vraiment sûr. Elles sont venues avec un groupe de Goules qui portaient des amulettes étranges et parlaient d'un *Renouveau*. C'est à peu près tout ce que je sais. Tu devrais aller vérifier à Gecko, cet endroit grouille de Goules. En parlant de gros rats, est-ce que je t'ai déjà parlé de la fois où l'Habitant de l'Abri et moi sommes allés à l'Abri 15 ?}
{145}{}{Non, mais je connais bien l'histoire, car c'est devenu une légende sacrée dans ma tribu. Je vais peut-être aller voir ce que je peux trouver à Gecko. Prends soin de toi, Ian.}
{146}{}{Euh, merci pour l'info. Au fait, je pense que tu es le gars que je cherche. Connar m'envoie te demander des infos.}
{147}{}{Attends une minute ! Connar m'a dit que t'avais des infos.}
{148}{}{Non, mais je connais bien l'histoire, car c'est devenu une légende sacrée dans ma tribu. Je vais peut-être aller voir ce que je peux trouver à Gecko. Prends soin de toi.}

{150}{}{Il voulait obtenir des armes pour repousser les patrouilles de la Cité. J'ai réussi à le convaincre qu'il y avait une meilleure solution.}
{151}{}{Ah, c'est donc ça son nouveau plan, hein ? Ouais, Connar est un homme bien, mais il ne pense pas vraiment à tout. Parfois, il vaut mieux parler franchement et essayer de raisonner avec les gens. C'est une leçon que j'ai apprise de mon vieil ami, l'Habitant de l'Abri.}

{152}{}{Bon, sais-tu à quel conseiller je pourrais aller parler ?}
{153}{}{Je pense que le conseiller McClure est l'homme à qui parler. Qu'en penses-tu ?}
{154}{}{Le conseiller McClure est un homme sage ici à la Cité de l'Abri. Peut-être qu'un accord peut être conclu avec lui ?}

{155}{}{Très bien. Je vais essayer d'aller lui parler. Salut.}
{156}{}{Je vais aller lui parler dans ce cas. Je suis quand même curieux à propos des rataupes qui gardent le village.}

{157}{}{C'est ta meilleure chance. C'est le dernier dans le conseil à qui il reste une âme.}
{158}{}{Très bien. Je vais essayer d'aller lui parler. Salut.}
{159}{}{Je vais aller lui parler dans ce cas. Je suis quand même curieux à propos des rataupes qui gardent le village.}

#added by killap - new in RP 1.3
{200}{}{Hé, si tu es vraiment le Ian qui a voyagé avec mon ancêtre, alors j'ai une question pour toi.}
{201}{}{Très bien, j'écoute.}
{202}{}{Comment peux-tu être encore vivant ? Tu devrais avoir plus de cent ans ! Et en plus, les mémoires de l'Habitant de l'Abri racontent que tu es mort carbonisé au lance-flammes, à Nécropolis par un Super Mutant.}
{203}{}{[Il se met à éclater de rire pendant un long moment. Finalement, Il se calme et essuie quelques larmes de ses yeux.] Oh, rien que ça ? Cramé par un lance-flamme ?! Ha ha ha ! Tu vois, j'ai demandé à l'Habitant de l'Abri de bien vouloir romancer ma mort, j'voulais pas qu'une de nos vieilles connaissances essaie de me refroidir... C'est pour ça que j'ai changé de nom. Je lui avais demandé une disparition étincelante, et on dirait qu'il l'a pris au pied de la lettre. Ha ha ha, excellente celle-là !}
{204}{}{Ha, j'crois que je comprends mieux... Je me pose quand même des questions sur les rataupes qui gardent le village.}
{205}{}{Ca n'explique toujours pas comment tu es encore vivant après toutes ces années.}
{206}{}{Hé, j'en sais pas plus que toi. Qui sait ? Peut-être que ça a quelque chose à voir avec toutes les radiations que j'ai pu me prendre à l'époque. La vache, quand on est allé au Rayon, je me souviens que l'Habitant de l'Abri avalait les Rad-X comme des bonbons, mais est-ce qu'il en a donné assez au vieux Ian ? Bien sûr que non ! Je pense qu'il l'avait mauvaise à cause des balles que je lui tirais dans le dos sans vouloir. Ha ha ! [Soupir...] C'était le bon vieux temps.}
{207}{}{Je n'en doute pas. Merci pour la petite histoire Joe, euh, Ian. Prends soin de toi.}
{208}{}{Je n'en doute pas. Merci pour la petite histoire Joe, euh, Ian. Je me pose quand même des questions sur les rataupes qui gardent le village.}

{300}{}{Attends une minute ! T'es le contact de la Cité de l'Abri dont Connar parlait ?}
