{100}{}{Tu vois un homme de forte stature, en vêtements de travail. Il a les yeux rivés au sol.}
{101}{}{Tu vois un esclave de la Cité de l'Abri.}
{102}{}{Tu vois un homme de forte stature, en vêtements de travail. Il a les yeux rivés au sol.}
{103}{}{Tu vois une femme en vêtements de travail, qui paraît en pleine santé. Elle a les yeux rivés au sol.}
{104}{}{Tu vois un esclave de la Cité de l'Abri.}
{105}{}{Tu vois une femme en vêtements de travail et en bonne santé. Elle a les yeux rivés au sol.}
{106}{}{On m'a parlé de tes actes de bravoure. Tu as rendu un grand service à la Cité de l'Abri... et au monde.}
{107}{}{Même la Première citoyenne a été impressionnée par ce que tu as fait.}
{108}{}{Je voudrais bien pouvoir quand même te donner quelque chose pour tout ce que tu as fait pour nous. Mais j'ai rien à offrir... A part... mes remerciements.}
{109}{}{Les autres domestiques vont être jaloux de savoir que je t'ai parlé.}
{110}{}{Oui, Capitaine ?}
{111}{}{Capitaine ?}
{112}{}{Vous vouliez me faire faire quelque chose, Capitaine ?}
{113}{}{Vous aviez une tâche à me confier, Capitaine ?}
{114}{}{Je m'excuse, Capitaine. Je vais essayer de travailler plus dur.}
{115}{}{Je m'excuse, Capitaine. Je vais essayer de faire plus attention.}
{116}{}{Oui, citoyen ?}
{117}{}{Citoyen ?}
{118}{}{Vous vouliez me faire faire quelque chose, citoyen ?}
{119}{}{Vous aviez une tâche à me confier, citoyen ?}
{120}{}{Je m'excuse, citoyen. Je vais essayer de travailler plus dur.}
{121}{}{Je m'excuse, citoyen. Je vais essayer de faire plus attention.}
{122}{}{Les mutants ne sont pas admis dans la Cité !}
{123}{}{Si les gardes voient ton mutant, ils t'obligeront à partir.}
{124}{}{Les mutants sont interdits dans la Cité ! Vous devez partir !}
{125}{}{Les Goules ne sont pas admises dans la Cité !}
{126}{}{Si les gardes voient ta Goule, ils t'obligeront à partir.}
{127}{}{Les Goules sont interdites dans la Cité ! Vous devez partir !}
{128}{}{Oui, j'appartiens déjà à quelqu'un. Le Centre de Répartition des Domestiques a mes papiers.}
{129}{}{Je vous en prie, laissez-moi tranquille. Je suis un domestique de la Cité de l'Abri.}
{130}{}{Je vous en supplie, vous n'auriez pas vu deux enfants, aux cheveux bruns... ? Ils ont été emmenés par d'autres esclavagistes, il y a deux ans, et vendus dans le Nord.}
{131}{}{S'il vous plaît... Je n'ai pas le droit de parler à qui que ce soit.}
{132}{}{Si un citoyen m'attrape en train de parler à un esclavagiste, on me punira.}
{133}{}{Les gardes vont me signaler si vous continuez à me parler.}
{134}{}{Je ne peux pas vous parler. J'ai des tâches à accomplir.}
{135}{}{Allez vous-en s'il vous plaît, esclavagiste. Je ne veux pas avoir de problèmes.}
{136}{}{M'échapper ? Je... je n'ai jamais essayé de m'échapper. La vie est agréable, ici.}
{137}{}{Les citoyens m'ont dit que si je travaillais assez dur, un jour, *moi* aussi, je pourrais devenir un des leurs.}
{138}{}{Les citoyens nous enseignent que le travail est sa propre récompense.}
{139}{}{Les citoyens nous disent que nos services leur laissent du temps pour des affaires plus importantes.}
{140}{}{J'ai eu de la chance que la Cité de l'Abri ait eu besoin de domestiques. J'aurais pu atterrir à New Reno.}
{141}{}{La Cité de l'Abri récompense les domestiques qui travaillent consciencieusement en leur donnant des rations supplémentaires.}
{142}{}{J'ai entendu dire qu'on faisait des choses atroces aux esclaves, à New Reno.}
{143}{}{Les citoyens ont amené tous les membres de ma tribu dans la Cité pour en faire des domestiques.}
{144}{}{Les citoyens m'ont fait venir ici du désert et ils m'ont appris à lire.}
{145}{}{Les citoyens me traitent très bien. La nourriture est excellente, ici.}
{146}{}{Je n'ai pas le droit de parler aux étrangers.}
{147}{}{Au début, ma famille me manquait, mais ça fait des années que je ne les ai pas vus.}
{148}{}{Je me suis fait capturer dans un village tribal, au Nord d'ici. La vie est bien plus agréable, ici.}
{149}{}{Je me suis d'abord fait capturer à la Fosse. Heureusement, j'ai fini par me retrouver ici.}
{150}{}{J'ai entendu dire que des fois la Première citoyenne s'emporte contre ses domestiques.}
{151}{}{Je ne peux pas vous parler. J'ai du travail.}
{152}{}{Je dois finir mes corvées dans l'heure.}
{153}{}{Parler aux étrangers est contraire au règlement.}
{154}{}{S'échapper ? Pourquoi ?}
{155}{}{Oui ? Je peux faire quelque chose pour toi ?}
{156}{}{Je me suis fait capturer par des esclavagistes il y a longtemps. Je m'en souviens à peine.}
{157}{}{J'avais deux enfants, mais ils ont été envoyés vers le Nord. J'espère que, un jour, ils arriveront jusqu'ici.}
{158}{}{Je regrette, mais je n'ai pas le temps de discuter.}
