{100}{}{Ves a Morlis, una de tus tías... a la que nunca le has gustado.}
{101}{}{¿Por qué me molestas, sobrino? ¿No ves que estoy ocupada?}
{102}{}{Emm... vale. Lo siento.}
{103}{}{¿Qué pasa? ¡Sabes que tengo mucho que hacer!}
{104}{}{Emmm, Mynoc dijo...}
{105}{}{¿Qué dijo Mynoc? ¡Suéltalo, chiquilla!}
{106}{}{Que, emm... podrías tener un pedernal.}
{107}{}{Lo tengo. Lo quieres, ¿no es eso?}
{108}{}{Bueno, sí.}
{109}{}{Bien... quiero tres dosis de polvos curativos. Se acercan malos tiempos y debo estar preparada. Traémelos y te daré el pedernal. ¡Ahora ve a conseguirlos!}
{110}{}{¡Si, señora!}
{111}{}{No me hagas perder el tiempo. ¿Tienes los polvos?}
{112}{}{Si, aquí están.}
{113}{}{Emm... me temo que no.}
{114}{}{Aquí está el pedernal. ¡Ahora lárgate! No tengo tiempo para estar de cháchara.}
{115}{}{Gracias, Tía Morlis.}
{116}{}{Otra vez me haces perder el tiempo, ¡sobrino inútil! ¿Cómo es posible que te escogieran a ti como el Elegido?}
{117}{}{Si, tía Morlis.}
{118}{}{Eh, tía Morlis, aquí tengo los tres.}
{150}{}{Tía Morlis, estoy en una peligrosa misión para salvar al poblado. Mis posibilidades de supervivencia aumentarían mucho si me quedara con los polvos curativos y me dieras el pedernal. ¿No crees?}
{151}{}{¿Qué crees que estás haciendo, chiquilla? Esa no es manera de actuar para una Elegida. ¡Ahora desaparece de mi vista!}
{152}{}{Si este pedernal es tan importante que estás dispuesto a deshonrar el nombre del Elegido, tenlo. Toma el pedernal y desaparece de mi vista.}
{153}{}{Si, tía Morlis.}
{154}{}{Bien... Oh, bien. Aquí está el pedernal. Te deseo un buen viaje, hija.}
{155}{}{No, no lo creo. Ahora deja de hacerme perder el tiempo y ¡lárgate de aquí!}
{156}{}{Si, tía Morlis.}
{200}{}{Así que has vuelto. ¿Has encontrado el sagrado Trece?}
{201}{}{No, tía Morlis. Yo...}
{202}{}{¡Entonces vete de aquí y encuéntralo! ¡Nuestra gente depende de ti!}
{203}{}{Si, tía Morlis.}
{204}{}{Bien, aquí estás de nuevo. ¿Otra vez has fracasado en tu búsqueda?}
{205}{}{Si, tía Morlis, pero...}
{206}{}{Entonces vete de aquí y no vuelvas hasta que no la hayas completado. ¿Por qué pierdes el tiempo volviendo aquí, cuando podrías estar usándolo para continuar buscando?}
{207}{}{Si, tía Morlis.}
{208}{}{El hecho de que estés aquí debe significar que has completado tu misión. No perderías un precioso tiempo volviendo aquí con las manos vacías, ¿verdad?}
{209}{}{Si, tía Morlis. Quiero decir... no, tía Morlis. Eh... tengo que irme, tía Morlis.}
{210}{}{Bien, chiquilla. De nuevo estás ante mí. ¿Otra vez con las manos vacías?}
{211}{}{Si, tía Morlis.}
{212}{}{Escucha, }
{213}{}{. La gente está muriendo, el ganado está muriendo, las cosechas están muriendo. Todo el mundo está hambriento, enfermo, o ambas cosas. Nuestro tiempo se acaba. Si no encuentras pronto el GECK, estamos condenados. ¿Me entiendes?}
{214}{}{Si, tía Morlis.}
{215}{}{¡Entonces vete de aquí y encuéntralo! ¡Nuestra gente depende de ti!}
{216}{}{Si, tía Morlis.}
{300}{}{Bien, parece que he extraviado el pedernal. Oh bien, al menos tengo mis polvos. ¡Ahora lárgate! No tengo tiempo para estar de cháchara.}
{301}{}{¿Por qué me molestas, sobrina? ¿No ves que estoy ocupada?}
{302}{}{Bien, no puedo encontrar la pedernal. Pero estoy seguro de que me la quitaste cuando no estaba mirando. Te cogí antes. ¡Ahora fuera con usted! No tengo tiempo para chismear.}
{303}{}{Bien... Oh, lo siento, pero parece que he extraviado el pedernal. Sin embargo te deseo un buen viaje, hija.}
{304}{}{Ya te di el pedernal, estúpida. Ahora deja de hacerme perder el tiempo y ¡lárgate de aquí!}
{305}{}{Ya te di el pedernal, estúpida. Oh bien, al menos tengo mis polvos. ¡Ahora lárgate! No tengo tiempo para estar de cháchara.}
