{100}{}{Ves a alguien que lleva una armadura de combate.}
{101}{}{Ves al guardia de la puerta del comandante.}
{102}{}{Ves a alguien que lleva una armadura de combate. Tiene una insignia en el peto con la que no estás familiarizado.}
{103}{}{¡Señora! ¿Qué hace aquí?}
{104}{}{¿Qué es este lugar?}
{105}{}{Uh... yo nuevo aquí.}
{106}{}{Yo limpio cosas.}
{107}{}{No recuerdo. Marcho yo.}
{108}{}{¿Qué lugar es éste?}
{109}{}{Hola, soy nueva.}
{110}{}{He venido a limpiar la oficina del comandante.}
{111}{}{No importa.}
{112}{}{Esta es la oficina del comandante de la base. Está área está restringida a todo el personal. Voy a tener que pedirle que se marche, señora.}
{113}{}{Yo hago asunto con comandante.}
{114}{}{Bien.}
{115}{}{Tengo asuntos que tratar con el comandante.}
{116}{}{De acuerdo.}
{117}{}{¿Cuál es la naturaleza de dichos asuntos, señora?}
{118}{}{Eh...}
{119}{}{Mierda. He jodido...}
{120}{}{Da igual. Marcho yo.}
{121}{}{Bueno...}
{122}{}{Eh... recibimos una llamada de seguridad. Parece que están preocupados por la posibilidad de que la clave de acceso al petrolero caiga en malas manos. Tenemos que asegurarla.}
{123}{}{Me marcho.}
{124}{}{Señora, este es el último aviso. Tengo que pedir que abandone esta zona.}
{125}{}{Vale.}
{126}{}{Oh... tú jodes. Yo disparo.}
{127}{}{Que te jodan. Me abriré paso a tiros.}
{128}{}{¿Qué? Oh, lo pillo. Realmente la has jodido y Dornan te ha puesto a limpiar.}
{129}{}{Sí... yo jodido... y... gneee.}
{130}{}{(hablando para sí mismo) Comandante. La de la limpieza está aquí, señor. (pausa) Sí, señor. (mirándote) Entra.}
{131}{}{Gracias.}
{132}{}{(hablando para sí mismo) Comandante. Seguridad está aquí. La base principal quiere que la clave de acceso del petrolero sea asegurada. (pausa) Sí, señor. (mirándote) Entra.}
{133}{}{Déjame ver tus ordenes.}
{134}{}{Gracias.}
{135}{}{Oh, no las he traído conmigo.}
{136}{}{(tranquilamente) Debes haberte perdida. Esta es la oficina del comandante de la base. No se permite estar aquí a nadie a menos que el viejo te llame.}
{137}{}{¿Nadie viene aquí? ¿Nunca?}
{138}{}{¿Nadie viene a verle?}
{139}{}{(tranquilamente) Nadie. Bueno, sólo los de la limpieza. Suelen venir por aquí en una hora o así. Aparte de ellos, este lugar está restringido. Ahora, será mejor que te largues.}
{140}{}{Vale.}
{141}{}{(hablando para sí mismo) Comandante. La de la limpieza está aquí, señor. (pausa) Sí, señor. (mirándote) Entra.}
{142}{}{Llegas pronto. Vuelve más tarde.}
{143}{}{Vale.}
{144}{}{Entonces vuelve al centro de comunicaciones y que te impriman la orden.}
{145}{}{Vale.}
{146}{}{Debes estar buscando la armería. Vuelve por el pasillo, gira a la derecha, y es la primera puerta a la izquierda. Te darán tu equipo allí.}
{147}{}{Gracias.}
{148}{}{¿Quién demonios sois vosotros... ¡Alerta! ¡Intrusos!}
{149}{}{¡Hemos sufrido una infiltración! ¡Alerta!}
{150}{}{¡Múltiples intrusos! ¡Dad la alarma!}
{151}{}{¡Alerta de seguridad! ¡Sellad la base!}
{152}{}{¡Asegurad todas las estaciones! ¡Estamos en alerta!}
{153}{}{¡Alerta de intrusos! ¡Pasad a Código Rojo!}
{154}{}{¡Te aplastaremos!}
{155}{}{¡El Enclave dominará el mundo!}
{156}{}{¡Tú morirás y el Enclave sobrevivirá!}
{160}{}{Has vuelto. ¿Traes contigo la orden del FOB?}
{161}{}{No, todavía no. La conseguiré.}
{162}{}{Sí, claro. Te digo que los de limpieza están a punto de llegar y mágicamente te conviertes en uno de ellos. Ni siquiera te he perdido de vista. ¿Crees que soy un jodido imbécil? ¡Fuera de aquí!}
{200}{}{(hablando a sí mismo) Comandante. (pausa) ¿Está allí, Comandante? (pausa) Hmm... Ninguna respuesta. Eso no es como él an absoluto. Será mejor que vaya a verlo.}
{201}{}{¡Santa mierda el Comandante está muerto! ¡Sonar las alarmas, tenemos un intruso!}
