{100}{}{Ves a un chico pequeño.}
{101}{}{Jonny}
{102}{}{Pelo rubio, ojos azules: el típico chico americano.}
{150}{}{¡Buaaaaa!}
{151}{}{¡Quiero mi perro!}
{152}{}{Gimoteo...}
{153}{}{¡Una extraña!}
{154}{}{¡Laddie! Te he echado de menos, chico. Gracias por traerme de vuelta a mi perro.}
{155}{}{Hola, no te he visto por aquí antes.}
{156}{}{¿Te llamas Jonny?}
{157}{}{¿Cómo te llamas, pequeño?}
{158}{}{Dime tu nombre, pequeño monstruo.}
{159}{}{¿Quieres un caramelo, pequeño?}
{160}{}{Hola de nuevo.}
{161}{}{¿Te llamas Jonny?}
{162}{}{¿Cómo te llamas, pequeño?}
{163}{}{Dime tu nombre, pequeño monstruo.}
{164}{}{¿Quieres un caramelo, pequeño?}
{165}{}{Hola de nuevo.}
{166}{}{Tu madre y tu padre me han enviado a buscarte.}
{167}{}{¿Quieres un caramelo, pequeño?}
{168}{}{¿Has hablado con Vegeir para que pueda volver a casa?}
{169}{}{Sí. Ha dicho que quiere que tus padres vengan a buscarte.}
{170}{}{No, aún no.}
{171}{}{Mi papá dijo que Laddie fue contigo para buscarme. ¿Dónde está? Le echo de menos.}
{172}{}{Lo siento, Jonny. Laddie murió mientras te buscábamos.}
{173}{}{Rose dijo que cuidaría de tu perro.}
{174}{}{Me llamo Jonny. ¿Cómo te llamas tú?}
{175}{}{Me llamo }
{176}{}{.}
{177}{}{Mi nombre no es lo importante.}
{178}{}{Me llamo Jonny, y no me gustas.}
{179}{}{[Te señala y comienza a gritar]. ¡Extraña! ¡Extraña! ¡Extraña!}
{180}{}{Encantado de conocerte, }
{181}{}{Tu madre y tu padre me han enviado a buscarte.}
{182}{}{Ya nos veremos, chico.}
{183}{}{¡Que bien! Quería ir a casa, pero Vegeir dice que su gente no puede viajar tan lejos por la superficie y no podían llevarme... No es que dude de ti, pero ¿cómo se llama mi padre?}
{184}{}{Farrel}
{185}{}{Cornelius}
{186}{}{Balthas}
{187}{}{Davin}
{188}{}{Joshua}
{189}{}{No puedes confiar en mí Jonny?}
{190}{}{Hmm… no. Gracias por traer de vuelta a mi perro, pero ahora tengo que irme. Adiós.}
{191}{}{Me alegro de haberte conocido, pero ahora tengo que irme. Adiós.}
{192}{}{Eso es correcto! Yipee! Me voy a casa. Pedir Vegeir si es del todo correcto para que me lleve a casa. Él ha sido
 tan bueno conmigo, no quiero salir hasta que él dice que todo está correcto. Por favor, date prisa, estoy nostálgico.}
{193}{}{Vale señor, le creo. Pregúntele a Vegeir si puede llevarme a casa. Se ha portado muy bien conmigo, y no quiero irme hasta que diga que puedo hacerlo.}
{194}{}{Vale señora, la creo. Pregúntele a Vegeir si puede llevarme a casa. Se ha portado muy bien conmigo, y no quiero irme hasta que diga que puedo hacerlo.}
{195}{}{No. Ahora voy a ir a jugar con mis amigos. Adiós.}
{196}{}{Se supone que no debo hablar con extraños. Adiós.}
{197}{}{¡Eso es! ¿Cómo lo has sabido? Laddie ha debido decírtelo. Es un perro tan listo.}
{198}{}{Tu madre y tu padre me han enviado a buscarte.}
{199}{}{Vas a venir conmigo de niño. Hay una recompensa por traer de vuelta.}
{200}{}{Sí, creo que es lo mejor. Aunque confío en ti, estoy seguro de que Vegeir tan sólo quiere asegurarse de que vuelvo a casa sano y salvo. Gracias por tu ayuda.}
{201}{}{Por favor, date prisa. Quiero volver a casa.}
{202}{}{¡No! ¡No te creo! ¡Devuélveme a mi perro! [¡Buaaaaaa!]}
{203}{}{Oh no! No sabes Rose utiliza perro en sus platos! Laddie es, probablemente, una hamburguesa por ahora.}
