{100}{}{Ves a Monada Nikki.}
{125}{}{Ves a una de las croupiers del casino.}
{150}{}{Ves a Monada Nikki.}
{151}{}{Vea usted Darlin' Nikki. Ella guiños a usted.}
{152}{}{Ves a Monada Nikki. Te hace señas para que te acerques a jugar.}
{153}{}{Vea usted Darlin' Nikki. Mason fue derecho sobre su culo.}
{154}{}{Vea usted Darlin' Nikki. Su vestido apenas cubre su cuerpo.}
{155}{}{Vea usted Darlin' Nikki. Mason fue derecho sobre su culo.}
{156}{}{Vea usted Darlin' Nikki. Su vestido apenas cubre su cuerpo.}
{160}{}{Ves a Monada Nikki. Te hace señas para que te acerques a jugar.}
{161}{}{Vea usted Darlin' Nikki. Su vestido apenas cubre su cuerpo.}
{162}{}{Vea usted Darlin' Nikki. Su vestido apenas cubre su cuerpo.}
{170}{}{Ves a una de las croupiers del casino.}
{171}{}{Ves a una de las croupiers del casino. Te guiña un ojo.}
{172}{}{Ves a una de las croupiers del casino. Te hace señas para que te acerques a jugar.}
{173}{}{Ves a una de las croupiers del casino. Tiene unas bonitas piernas.}
{174}{}{Ves a una de las croupiers del casino. Su vestido apenas cubre su cuerpo.}
{175}{}{Ves a una de las croupiers del casino. Huele muy pero que muy bien.}
{180}{}{Ves a una de las croupiers del casino. Te hace señas para que te acerques a jugar.}
{181}{}{Ves a una de las croupiers del casino. Su vestido apenas cubre su cuerpo.}
{182}{}{Ves a una de las croupiers del casino. Su vestido apenas cubre su cuerpo.}
{183}{}{Ves a una de las croupiers del casino. Te hace señas para que te acerques a jugar.}
{200}{}{::Brindis::}
{201}{}{::Aplausos::}
{202}{}{::Silbidos::}
{203}{}{!Bienvenido al casino, héroe!}
{204}{}{Pensé que se había olvidado de nosotros, mientras que fueron a salvar el mundo.}
{210}{}{Hola, }
{211}{}{Si estás buscando un poco de compañía para más tarde…}
{212}{}{Oye, tú… [guiño]… ¿te gustaría jugar?}
{213}{}{Parece tan… (tiene un escalofrío)… peligroso.}
{214}{}{Bienvenido al casino, }
{215}{}{¿Le hablará bien al jefe de mí?}
{216}{}{Hola, señorita. Hágame saber si puedo ayudarla con algo.}
{217}{}{¿Quiere jugar, señorita?}
{218}{}{Parece tan… (tiene un escalofrío)… peligrosa.}
{220}{}{Parece que éste ya está apostando con su vida.}
{221}{}{Eh, creo que acaba de entrar en el casino equivocado…}
{222}{}{Si no sale antes de que los muchachos le vean…}
{223}{}{Oh-oh. Problemas…}
{224}{}{Parece que ésta ya está apostando con su vida.}
{225}{}{Eh, creo que acaba de entrar en el casino equivocado…}
{226}{}{Si no sale antes de que los muchachos la vean…}
{230}{}{Oye, fortachona. ¿Quieres gastar algunas fichas?}
{231}{}{Oye, campeón… [guiño]… ¿te gustaría jugar?}
{232}{}{Oye, campeón… [sonríe]… ¿te apetece probar?}
{233}{}{Si estás buscando un poco de compañía para más tarde…}
{234}{}{Me pregunto si debería hablar con él…}
{235}{}{Oye, }
{236}{}{Si buscas ganar algo de pasta, has venido al lugar adecuado.}
{237}{}{El mejor casino New Reno. En el MUNDO, incluso.}
{238}{}{La Dama Fortuna está en la casa esta noche… ¡sólo hay ganadores!}
{239}{}{Adelante, }
{240}{}{¿Quieres otra copa?}
{241}{}{Bienvenido al casino, }
{242}{}{Hola, }
{243}{}{Seguro que quieres jugar, }
{244}{}{Bienvenido al casino, }
{250}{}{Hola, estrella. ¿Quieres gastar algunas fichas?}
{251}{}{Oye, }
{252}{}{Oye, }
{253}{}{Si buscas ganar algo de pasta, }
{254}{}{El mejor casino New Reno. En el MUNDO, incluso.}
{255}{}{La Dama Fortuna está en la casa esta noche… ¡sólo hay ganadores!}
{266}{}{Adelante, }
{267}{}{¿Quieres otra copa?}
{268}{}{Bienvenido al casino, }
{269}{}{Hola, la Señora de la Estrella de Cine. Busca pasar de un cheque de pago?}
{270}{}{Oye, cariño. ¿Quieres gastar algunas de tus fichas?}
{271}{}{Oye, cariño… [guiño]… ¿quieres jugar?}
{272}{}{Oye, cariño… [sonríe]… ¿te apetece probar?}
{273}{}{Si buscas ganar algo de pasta, has venido al lugar adecuado.}
{274}{}{El mejor casino New Reno. En el MUNDO, incluso.}
{275}{}{La Dama Fortuna está en la casa esta noche… ¡sólo hay ganadores!}
{276}{}{Adelante, gana algunas fichas.}
{277}{}{¿Quieres otra copa, cariño?}
{278}{}{Bienvenido al casino, cariño.}
{279}{}{Esta mesa está libre, si quieres jugar…}
{280}{}{Oye, cariño. ¿Quieres gastar algunas de tus fichas?}
{281}{}{¿Quieres jugar, cariño?}
{282}{}{Bienvenido al casino, cariño.}
{290}{}{Bueno, estás loco por entrar aquí, pero… hagan sus apuestas. La apuesta mínima es de 5 fichas. Hagan sus apuestas…}
{291}{}{Um... el lugar sus apuestas... apuesta de mínimo de 5 fichas. Coloque sus apuestas...}
{292}{}{Coloque su apuesta, señor. Apuesta de mínimo de 5 fichas. Coloque sus apuestas...}
{293}{}{Coloque su apuesta, señor. Apuesta de mínimo de 5 fichas. Coloque sus apuestas...}
{294}{}{Coloque sus apuestas, apuesta mínima de 5 fichas. Coloque sus apuestas...}
{295}{}{Yo más ap-apuesto que tú}
{296}{}{Me juego los pantalones.}
{297}{}{Lo de este juego? Puede usted apuesta Gecko de la piel? Me dieron geck... ooooh... bastante luces por allí!}
{298}{}{Apuesta 5 fichas?}
{299}{}{Apuesta 5 fichas?}
{300}{}{Apuesta 5 fichas?}
{301}{}{Apuesta 5 fichas?}
{302}{}{Usted Nikki?}
{303}{}{¿Cómo te va, Nikki?}
{304}{}{Whoa, demasiado rico para mi sangre. Me voy de aquí.}
{305}{}{Nada de apuestas hoy, gracias.}
{310}{}{Uh, muy bien, señor. Vuelva pronto.}
{311}{}{Uh, muy bien, señora. Vuelva pronto.}
{312}{}{Um… he oído que están regalando cerebros ahí atrás. Quizá deberías echar un vistazo.}
{313}{}{Adiooos}
{314}{}{Bueeeno. }
{315}{}{Uh... cerebro... ¿cuál de ellos?}
{320}{}{Muy bien, señor. Vuelva pronto.}
{321}{}{Muy bien, señora. Vuelva pronto.}
{322}{}{5 fichas? "Demasiado rico para su sangre?' Pal, usted está en la ciudad equivocada.}
{323}{}{5 fichas? "Demasiado rico para su sangre?' Pal, usted está en la ciudad equivocada.}
{324}{}{5 fichas? "Demasiado rico para su sangre?' Chica, estás en la ciudad equivocada.}
{325}{}{5 fichas? "Demasiado rico para su sangre?' Chica, estás en la ciudad equivocada.}
{326}{}{Eso haré, gracias.}
{327}{}{Tal vez sea así, pero al menos que *yo* no vive aquí.}
{330}{}{Lo siento, señor. Más suerte la próxima vez.}
{331}{}{Lo siento, señora. Más suerte la próxima vez.}
{332}{}{Lo siento, más suerte la próxima vez.}
{333}{}{Usted tiene [C] fichas. Seguir jugando?}
{334}{}{Lo dejas para otro día.}
{335}{}{Lo dejas para otra noche.}
{340}{}{¡Ganador! ¡Bien hecho, señor!}
{341}{}{El ganador! Bien hecho, señora!}
{342}{}{¡Ganador!}
{343}{}{Usted tiene [C] fichas. Seguir jugando?}
{344}{}{Lo dejas para otro día.}
{345}{}{Lo dejas para otra noche.}
{350}{}{¡Ganador! ¡Ha duplicado su dinero! ¡Bien hecho, señor!}
{351}{}{¡Ganador! ¡Ha duplicado su dinero! ¡Bien hecho, señora!}
{352}{}{¡Ganador! ¡Ha duplicado su dinero!}
{353}{}{Usted tiene [C] fichas. Seguir jugando?}
{354}{}{Lo dejas para otro día.}
{355}{}{Lo dejas para otra noche.}
{360}{}{¡Ganador! ¡Ha triplicado su dinero! ¡La suerte está en la casa esta noche! ¡Bien hecho, señora!}
{361}{}{¡Ganador! ¡Ha triplicado su dinero! ¡La suerte está en la casa esta noche! ¡Bien hecho, señora!}
{362}{}{¡Ganador! ¡Ha triplicado su dinero!}
{363}{}{Usted tiene [C] fichas. Seguir jugando?}
{364}{}{Lo dejas para otro día.}
{365}{}{Lo dejas para otra noche.}
{370}{}{¿Qué quieres ahora? ¿Estás aquí para hacerme perder el tiempo, o vas a apostar?}
{371}{}{Yo soy quien tu QUIERES que yo sea, cariño. Ahora, usted va a hacer una apuesta?}
{372}{}{Yo soy quien tu QUIERES que yo sea, novia. Ahora, usted va a hacer una apuesta?}
{373}{}{Colocar una apuesta.}
{374}{}{Sí. Estoy segura de que usted sabe dónde Pretty Boy Lloyd es.}
{375}{}{Sí, estoy segura de que usted y el Niño Bonito de la Lloyd ambos estaban robando el dinero del Señor Salvatore. Es difícil de creer que
 no se le nota truco de todos los tiempos.}
{376}{}{¿Conoces a alguien llamado Lloyd el Guapo?}
{377}{}{Vamos a hablar más tarde, Nikki.}
{380}{}{Sí, he oído que está MUERTO. ¡¿Eso es lo que querías oír, asesina?! ¡¿Eh?! Y ahora, ¿vas a apostar o vas a seguir con tus chorradas?}
{381}{}{Nope. Usted va a hacer una apuesta?}
{382}{}{Colocar una apuesta.}
{383}{}{Sí. Estoy segura de que usted sabe dónde Pretty Boy Lloyd es.}
{384}{}{Sí, estoy segura de que usted y el Niño Bonito de la Lloyd ambos estaban robando el dinero del Señor Salvatore. Es difícil de creer que
 no se le nota truco de todos los tiempos.}
{385}{}{Vamos a hablar más tarde, Nikki.}
{390}{}{Entonces esa apuesta la PERDERÍAS, encanto, pero si eres tan estúpido como feo, probablemente apostarías de todas formas. No
 he visto a esa escoria desde que estafó al señor Salvatore.}
{391}{}{A continuación, es una apuesta pierde, cariño. No me está visto que bum ya que él tiró de que la estafa en el Señor Salvatore.}
{392}{}{A continuación, es una apuesta pierde, novia. No me está visto que bum ya que él tiró de que la estafa en el Señor Salvatore.}
{393}{}{Tal vez usted no me oye el primer tiempo, para el beneficio de las personas con discapacidad auditiva: Donde se Lloyd?}
{394}{}{Bastante sospechoso que no se le nota truco de todos los tiempos. Habría que ser ciego... o sobornados.}
{395}{}{Bien. Vamos a hablar más tarde, Nikki.}
{400}{}{Encanto, te he DICHO que no sé dónde está. Ahora, mira, estoy TRABAJANDO, así que vuelve a la roca de la que hayas salido...}
{401}{}{Novia, yo le DIJE que yo no sé dónde está. Ahora, miren, estoy TRABAJANDO aquí, así que ir de vuelta a lo rock you --}
{402}{}{Nikki, Nikki... estoy perdiendo la PACIENCIA aquí. Si no me dices donde Lloyd es, voy a perder mi temperamento, demasiado.}
{403}{}{Nikki, no sé lo que pasó entre tú y Lloyd. Pero, ¿adivinen qué? No NECESITO saber. Sólo voy a decir
 El señor Salvatore lo que sospecho.}
{404}{}{Nikki, yo sé que usted ayudó a Lloyd trampa. Dime donde Lloyd es, y yo voy a dar la mitad de su toma: 500 fichas.}
{405}{}{Bastante sospechoso que no se le nota truco de todos los tiempos. Habría que ser ciego... o sobornados.}
{406}{}{Hablaremos más tarde, Nikki.}
{410}{}{Tócame, y el señor Salvatore te desollará vivo.}
{411}{}{Salvatore no lo protegerá; distribuidores como usted es un chip de una docena. Cortar la mierda y me dicen donde Lloyd es o MÁS.}
{412}{}{Salvatore no van a proteger a usted; él está muerto. Cortar la mierda y me dicen donde Lloyd es o MÁS.}
{413}{}{Nikki, yo sé que usted ayudó a Lloyd trampa. Dime donde Lloyd es, y yo voy a dar la mitad de su toma: 500 fichas.}
{414}{}{Bastante sospechoso que no se le nota truco de todos los tiempos. Habría que ser ciego... o sobornados.}
{415}{}{Hablaremos más tarde, Nikki.}
{420}{}{¿De qué estás hablando?}
{421}{}{Nikki, si no me dices todo ahora mismo, te voy a decir el Señor Salvatore fuiste, si lo eran o no.
 Él va a tener Mason de corte de hasta siete formas del domingo, y tienes tu trabajo lleno en una hora.}
{422}{}{Nikki, yo sé que usted ayudó a Lloyd trampa. Dime donde Lloyd es, y yo voy a dar la mitad de su toma: 500 fichas.}
{423}{}{Bastante sospechoso que no se le nota truco de todos los tiempos. Habría que ser ciego... o sobornados.}
{424}{}{Hablaremos más tarde, Nikki.}
{430}{}{Mira, COMO HE DICHO, no sé dónde está. Pero *quizá* haya oído que solía tener una habitación en el Desperado. Quizá encuentres
 algo allí. Y ahora, si no te importa, tengo que volver al trabajo.}
{431}{}{Nikki, yo sé que usted ayudó a Lloyd trampa. Dime donde Lloyd es, y yo voy a dar la mitad de su toma: 500 fichas.}
{432}{}{Bastante sospechoso que no se le nota truco de todos los tiempos. Habría que ser ciego... o sobornados.}
{433}{}{Hablaremos más tarde, Nikki.}
{440}{}{Mira, acabo de EMPEZAR a trabajar aquí, y no puedo reconocer a cada contador de cartas y tramposo del tres al cuarto que anda por aquí.
 Aunque tengo bastante buena vista con los imbéciles como tú.}
{441}{}{Ah, esa es la forma en que usted y Lloyd enganchado hasta entonces?}
{442}{}{Así que usted acaba de comenzar el trabajo, ¿eh? Muy conveniente. Bueno, eso es todo lo que necesito saber. Dígale a Lloyd es hombre muerto.}
{443}{}{Nikki, yo sé que usted ayudó a Lloyd trampa. Dime donde Lloyd es, y yo voy a dar la mitad de su toma: 500 fichas.}
{444}{}{Hablaremos más tarde, Nikki.}
{450}{}{Cierto, si tomas bastante Jet, todo parece sospechoso, ¿verdad?}
{451}{}{ES sospechoso. Usted debe haber tenido Lloyd vinculado por qué se fue tan pronto como él anduvo en este casino.}
{452}{}{Nikki, yo sé que usted ayudó a Lloyd trampa. Dime donde Lloyd es, y yo voy a dar la mitad de su toma: 500 fichas.}
{453}{}{Hablaremos más tarde, Nikki.}
{460}{}{Lárgate de aquí de una puñetera vez. No tengo nada que decirte.}
{461}{}{No tengo nada que decir a usted. Salir de aquí.}
{462}{}{No ahora, tal vez. Vamos a hablar más adelante, aunque, Nikki. Contar con ella.}
{470}{}{Eres sinuoso... como las serpientes. QUIZÁ sepa dónde está Lloyd, o QUIZÁ no. ¿Tienes 500 fichas?}
{471}{}{Tal vez. Depende de lo que tienes para mí.}
{480}{}{PUDIERA ser que Lloyd aún tenga mi parte, y que no estuviera segura de que me la fuera a dar. Así que QUIZÁS -a cambio de 500 fichas-
 podría contarte dónde PUEDE que esté su mentiroso trasero.}
{481}{}{Hecho. Aquí está el 500 fichas. Dime dónde está.}
{482}{}{Es un precio excesivo para un montón de "posibles" y "coulds." Lo encontraré por mi cuenta.}
{483}{}{No tengo suficientes fichas, pero voy a estar de vuelta. Mejor todavía estar aquí cuando regrese.}
{490}{}{(Se guarda el dinero). Comprueba la zona de la parrilla en el sótano del Desperado. Era allí donde el hijo de perra se
 iba a meter si las cosas se calentaban.}
{491}{}{Bien entonces. Más Tarde, Nikki.}
{500}{}{¡¿Quieres largarte de aquí?! Si la gente nos ve hablando de esto, entonces son ELLOS los que hablarán. ¿Lo entiendes?}
{501}{}{Bien entonces. Más Tarde, Nikki.}
{510}{}{¡Pues vete al infierno! No tengo nada más que decirte, NUNCA.}
{511}{}{Rompe mi corazón. Más Tarde, Nikki.}
{600}{}{Usted sobornar a Nikki en la que le dice donde Lloyd podría estar escondido.}
{1210}{}{. ¿Puedo ayudarte con… *lo que sea*?}
{1214}{}{.}
{1235}{}{. ¿Quieres gastar algunas fichas?}
{1239}{}{, ganas algunas fichas.}
{1241}{}{.}
{1242}{}{. Házme saber si puedo ayudarte con lo que sea.}
{1243}{}{?}
{1244}{}{.}
{1251}{}{...(guiño)...usted está buscando para jugar?}
{1252}{}{...(sonríe)...quiero tener una oportunidad?}
{1253}{}{, usted vino al lugar correcto.}
{1266}{}{, ganas algunas fichas.}
{1268}{}{.}
{1314}{}{ siempre se puede utilizar elemento nuevo inventario}
{2699}{}{¿Bailas esta noche?}
