{100}{}{Ves a un hombre de aspecto amigable, con el rostro enrojecido.}
{101}{}{Es Duppo. Corre el Vaquero de la Asociación.}
{102}{}{Es un tipo fornido con la cara constantemente enrojecida y una mata de fino pelo rubio. Camina con una leve cojera.}
{103}{}{Saludos, forastera. No te tengo vista por aquí, de modo que no eres una ganadera. ¿Vienes buscando trabajo o estas aquí por negocios?}
{104}{}{¿Qué va a ser, forastera?}
{105}{}{Trabajo.}
{106}{}{Negocios.}
{107}{}{Bueno, mi nombre es Duppo. Suministros del rancho y sala de contratación, justo aquí lo hacemos todo. Te diré que no tienes pinta de matarife de brahmines. ¿Qué tal manejas las armas?}
{108}{}{Todavía buscamos algunos guardias, si estas interesado.}
{109}{}{Je. Matar.}
{110}{}{Bastante bien.}
{111}{}{Yo no soy violenta.}
{112}{}{Bien, aquí están mis existencias. Asegúrate de comprobar todas las mesas para el resto del inventario. Si no te gusta lo que tengo, mueve tu culo con ese buscapleitos de Buster. Por supuesto, intentará timarte.}
{113}{}{Bien, tienes pinta de eso. Estamos buscando a guardias para conducir una manada de brahmines hasta Redding. La paga es de 2.000 dólares menos lo que se pierda antes de llegar allí. Si te interesa, ve a la puerta del rancho de Westin mañana. Si no te presentas, no vas. ¿Aceptas?}
{114}{}{Marcho yo.}
{115}{}{No gusta. No hago yo.}
{116}{}{Suena bien.}
{117}{}{Paso, no quiero ir a Redding.}
{118}{}{Bien, entonces aquí no hay trabajo para ti. El campo es un lugar duro. No hay sitio para los débiles, forastera. }
{119}{}{¿Algo más?}
{120}{}{Bastante bien, sí. ¿Algo más, forastera?}
{121}{}{Negocios.}
{122}{}{Trabajo.}
{123}{}{¿Wes-tin?}
{124}{}{Estoy buscando a Roger Westin. ¿Has oído hablar de él?}
{125}{}{¿Dónde puedo encontrar a Frank Carlson?}
{126}{}{¿Carl-son?}
{127}{}{Adiós.}
{128}{}{¿Te refieres a Roger Westin? Al oeste del pueblo.}
{129}{}{Uno de los mandamases de este lugar. Al oeste de la ciudad. No creo que esté buscando trabajadores para el rancho, si es lo que estás pensando.}
{130}{}{Es el vicepresidente; es todo lo que sé. Por otra parte, no puede decirte nada más. Pasa la mayoría del tiempo en la Residencia Presidencial. Casi nunca sale, especialmente ahora con todos los problemas que hemos tenido.}
{131}{}{Carlson. Gran Jefe. Vive en la casa grande. Eso es todo.}
{132}{}{Lo siento: la temporada de caravanas de ganado terminó. Vuelve dentro de algunos meses.}
{133}{}{Sí, sí... ¿hay alguna otra manera de ganarse unos pavos rápidamente en el pueblo?}
{134}{}{Es posible que haya algo así. Digamos que los funcionarios no quieren saber nada de una oportunidad como ésta.}
{135}{}{Bueno, estaría dispuesta a pagar una cantidad por algo de información.}
{136}{}{Hmm, ¿de cuánto estás dispuesto a deshacerte?}
{137}{}{¿Qué tal 500?}
{138}{}{¿Qué tal 300?}
{139}{}{¿Qué tal 200?}
{140}{}{¿Qué tal 100?}
{141}{}{Bueno, esto no lo has escuchado aquí, pero la contraseña de la puerta trasera es PEDAZO DE PANDILLA PROBLEMA.}
{142}{}{Hmm... no creo que eso me llegue a interesar.}
{143}{}{Hmmm.. no te olvides de mis 10 hijos.}
{144}{}{Hmmm.. bueno, mi esposa querrá un nuevo abrigo de piel.}
{145}{}{Hmmm.. vas a tener que contribuir con algo más.}
{146}{}{Ah, ¿un poco corta de fondos en estos tiempos?}
{147}{}{Supongo que sí.}
{148}{}{Vemos, no seas tacaña.}
{149}{}{Te estás acercando.}
{150}{}{Mira, voy a necesitar un incentivo mayor.}
{151}{}{Aprisa, antes de que alguien nos vea.}
{152}{}{¿Estás seguro de no estar mezclado con la ley?}
{153}{}{Mira, casi lo tienes, sigue así.}
{154}{}{Muy bien, sólo un poco más, te lo prometo.}
{155}{}{Estate en la entrada del rancho de Westin mañana. Si no apareces, saldremos sin ti. ¿Entendido?}
{156}{}{Estamos a punto de hacer otro ganado a Redding. ¿Cómo está tu manejo de las armas?}
