{100}{}{Ves a un joven delgado con gafas.}
{101}{}{Es Gunther, el ayudante de la presidente Tandi. Al menos eso es lo que dice el cartel de la puerta.}
{102}{}{Parece oficioso y ocupado, del tipo nacido para ser el burócrata que el resto odia.}
{103}{}{¿Puedo ayudarte?}
{104}{}{¿Otra vez tú?}
{105}{}{Uhhhh - trabajar. Trabajar con Tandi yo.}
{106}{}{¿Quién eres?}
{107}{}{Estoy aquí para ver a la presidente Tandi por un trabajo.}
{108}{}{Lo siento, oficina equivocada.}
{109}{}{¿Quieres trabajo?}
{110}{}{Vamos a intentarlo de nuevo. ¿Ayudar a Tandi? ¿Hacer trabajo para Tandi?}
{111}{}{¡Sísisisi!}
{112}{}{Tandi trabajo. Quiero yo.}
{113}{}{¿Qué haces?}
{114}{}{Uhhhh... ¡mato, mato mucho grande!}
{115}{}{Uhhhh... yo listo. Anciana dice que tengo cerebro-de-niño. Tengo 2 cerebros. Yo listo.}
{116}{}{¡No puedes tomar el trabajo de presidente!}
{117}{}{¿No?}
{118}{}{Oh. De acuerdo.}
{119}{}{Vale. No estoy seguro de que sea eso lo que está buscando. En fin, dijo que los enviase a todos. Puedes ir. Habla con Tandi ahora.}
{120}{}{¡NO! Tú eres tonta. ¡El presidente debe ser listo, hablar con palabras de dos sílabas! Tú no eres presidente.}
{121}{}{Oh. ¿Que yo hago?}
{122}{}{Yo no como tú. Tú gritas. Hombre malo.}
{123}{}{Mi nombre es Gunther, soy el asistente personal de la presidente Tandi. Y ahora, ¿qué puedo hacer por ti?}
{124}{}{Estoy buscando el Refugio 13.}
{125}{}{Estoy buscando un GECK.}
{126}{}{Creo que la presidente tiene un trabajo que hay que hacer.}
{127}{}{La Señora Presidente no concede entrevistas referidas al Refugio 13. Lo siento. Está demasiado ocupada como para ver a cada prospector que se deja caer por aquí.}
{128}{}{¿Eh? No lo entiendo.}
{129}{}{¿Qué acerca de un GECK? Ella puede saber algo acerca de eso?}
{130}{}{Se habló sobre un trabajo.}
{131}{}{Me resultas inútil. Me marcho.}
{132}{}{Entonces te sugiero que leas la placa de la estatua del exterior. Y ahora, buenos días.}
{133}{}{No tengo ni idea de lo que estás hablando. ¿Tienes alguna pregunta de verdad?}
{134}{}{Estoy buscando el Refugio 13.}
{135}{}{Creo que la presidente tiene un trabajo que hay que hacer.}
{136}{}{No importa.}
{137}{}{Ah, sí. Bien, ella me dio instrucciones para dejar pasar a cualquiera que preguntara sobre ello. Puedes pasar. Es la puerta de mi derecha.}
{138}{}{¿La Señora Presidente ha terminado contigo? ¿Cómo han ido las cosas?}
{139}{}{Bien. Yo adiós.}
{140}{}{Muy bien. Ahora, me largo de aquí.}
{141}{}{¿Estás aquí para informar de los resultados del Refugio 15?}
{142}{}{Sí.}
{143}{}{No.}
{144}{}{Bien, lo siento, pero la Señora Presidente está muy ocupada. ¿Por qué no vuelves cuando el trabajo esté hecho?}
{145}{}{Vale.}
{146}{}{¡Excelente! Avisaré de que vas.}
{147}{}{¡Zorra! ¡Guardias! ¡Asesina! ¡Asesina!}
{148}{}{¡Ya de vuelta! ¿Y ahora qué?}
{149}{}{Rec-compensa.}
{150}{}{La presidente dijo que te preguntara por una recompensa.}
{151}{}{D-dinero.}
{152}{}{Estoy aquí para recoger mi paga.}
{153}{}{Tu presidente dijo que deberías saber que hay un espía en vuestra casa: alguien llamado Feargus.}
{154}{}{Nada.}
{155}{}{Desde luego, acaba de avisarme sobre ello. Una recompensa de 6.000 dólares y el agradecimiento de la RNC, dijo. Ahora, tengo trabajo que hacer. Adiós.}
{156}{}{Veamos. En el contrato pone 500 dólares. Aquí están.}
{157}{}{De hecho, acaba de avisarme para cambiar la cantidad: parece que has merecido un extra. Aquí están, 900 dólares y las gracias de la RNC. Y ahora, he de continuar trabajando, así que adiós.}
{158}{}{Tu presidente dijo que deberías saber que hay un espía en vuestra casa: alguien llamado Feargus.}
{159}{}{Adiós.}
{160}{}{¿Feargus? ¡No lo creo!}
{161}{}{Echa una mirada a este disco.}
{162}{}{Lo que sea. Me largo de aquí.}
{163}{}{Maldición. Parece una prueba sólida. Mira, nos encargaremos de esto. Aquí tienes 4.000 dólares por la información.}
{164}{}{No acepto dinero manchado de sangre. Me largo de aquí.}
{165}{}{Gracias. Que tengas un buen día.}
{166}{}{Oh, eres tú. Mira, este no es un buen momento. De hecho, creo que la Señora Presidente preferiría que no te involucraras en nada más. Gracias y buenos días.}
{167}{}{Te voy a hablar claro. La presidente no va a verte... ni ahora ni nunca. Se te ha pagado. Ahora simplemente vete.}
{171}{}{Yo ir.}
{172}{}{Absolutamente nada.}
{173}{}{¡Zorra! ¡Guardias! ¡Asesina! ¡Asesina!}
{174}{}{He estado en el Refugio 15 y necesito hablarle a tu jefa sobre ello.}
{175}{}{Tengo que hablar del Refugio 15.}
{176}{}{Deberías saber que hay un espía en vuestra casa: alguien cuyo nombre empieza por F.}
{177}{}{También encuentro espía. Ferrrgus.}
{178}{}{Yo no mentir. Miira. (Le das el disco).}
{179}{}{¡Agradezco yo!}
{500}{}{Tenemos las puertas cerradas por una razón.}
{501}{}{Debo pedirte que te vayas.}
{502}{}{Este es tu último aviso. Vete antes de que tenga que sacarte yo.}
{503}{}{Seguridad: por favor, encargaos de este problema.}
{510}{}{Bueno, espera un minuto. Tengo más que discutir con tu jefe sobre el Refugio 15.}
