{100}{}{Ves a un viejo huesudo con un lápiz enganchado tras la oreja y unos anteojos en la punta de la nariz.}
{101}{}{Es Vortis, el propietario de este centro de esclavos.}
{102}{}{Tiene como unos tres dientes. Sus dedos y su camisa están manchados de tinta azul. Tiene un tatuaje de esclavista realmente desteñido en la frente.}
{103}{}{Y.. ¿qué es lo que quiere?}
{104}{}{Amiga, bienvenida a El Portal de Vortis. ¿En qué puedo ayudarte?}
{105}{}{Estás empezando a cansarme.}
{106}{}{Este lugar es MI lugar y yo, Vortis, dirijo un negocio honesto y legítimo y no importa lo que nadie de la RNC te diga. Ya que la RNC no permite esclavos entre sus muros, yo cuido de ellos para los tipos que tienen negocios en el interior.}
{107}{}{¿Qué pasa contigo, eres tonta? Este es un centro de esclavos. Tengo licencia para ello.}
{108}{}{}
{109}{}{Sólo necesito hacer unas preguntas.}
{110}{}{Estoy buscando trabajo.}
{111}{}{¿Eh?}
{112}{}{¿No es letrina? Marcho ya.}
{113}{}{¿Qué se hace en este lugar?}
{114}{}{Nada. Lugar equivocado.}
{115}{}{Oh, mira: una buenaza que ayuda a cruzar la calle a las ancianitas. ¡Muchachos, escoltad a este hipócrita modelo de virtud santificada fuera de mi vista!}
{116}{}{Hay que joderse.}
{117}{}{¿Bien?}
{118}{}{Estoy buscando el Refugio 13.}
{119}{}{¿Tienes un GECK?}
{120}{}{¿Qué me puedes contar de esta ciudad?}
{121}{}{¡Eres escoria esclavista! ¿Por qué no debería matarte?}
{122}{}{He oído hablar de esos tipos... los Rangers de Nueva California. ¿Te han dado algún problema?}
{123}{}{¿Te importa si echo una vistazo por aquí?}
{124}{}{¿Trabajo? Bien... podría haber algo. ¿Has oído hablar los Rangers de Nueva California?}
{125}{}{Sí.}
{126}{}{No.}
{127}{}{Que te jodan. Muchachos, escoltad a esta molesta escoria fuera de mi vista.}
{128}{}{¡Chúpamela!}
{129}{}{¡Refugio! Lárgate de aquí. Ese maldito lugar es un mito. Refugio 13, mis cojones.}
{130}{}{Otra pregunta...}
{131}{}{Bien, gracias por nada.}
{132}{}{¿Un qué? Bueno, lo que quiera que sea, no lo tengo.}
{133}{}{Otra pregunta...}
{134}{}{Bien, gracias por nada.}
{135}{}{República de Nueva California: nada más que tipejos moderados y comerciantes. No les gusta un pelo ni los esclavistas ni la esclavitud, pero qué puñetas, ese es mi negocio.}
{136}{}{Otra pregunta...}
{137}{}{Gracias, tengo que irme.}
{138}{}{Alguien te ha tomado el pelo. No tengo problemas con nadie: especialmente ninguno con los Rangers. Tengo todos los requisitos legales, así que no tienen nada contra mí.}
{139}{}{Otra pregunta...}
{140}{}{Lo que tú digas. Me marcho.}
{141}{}{Sí, tengo mis opiniones acerca de los Rangers. ¿Estás buscando trabajo?}
{142}{}{Sí.}
{143}{}{No.}
{144}{}{¡No, no puedes ir a husmear, tonto del culo! ¡Esto no es un museo!}
{145}{}{Otra pregunta...}
{146}{}{Eres demasiado susceptible para mi gusto. Me marcho.}
{147}{}{Pues bien, deberías saber que ciertos tipos los ven como un problema potencial. Sería extremadamente útil que tuviéramos un mapa de sus pisos francos por todo el norte: Nuevo Reno, Klamath, donde sea. Estaría dispuesto a pagar, digamos, 500 dólares por algo así. ¿Crees que me lo podrías conseguir?}
{148}{}{Claro.}
{149}{}{Creo que no.}
{150}{}{Entonces déjame que te cuente. Estos Rangers tienen metido en la cabeza el eliminar la esclavitud y a los esclavistas... por la fuerza. Han estado provocando una gran cantidad de problemas a los que nos dedicamos a ello.}
{151}{}{Trabajan en secreto, especialmente por el norte.}
{152}{}{Joder, ¿te lo tengo que explicar todo? Atacan a los esclavistas, liberan a las existencias, y los dirigen al sur, a las tierras de la RNC en las que la esclavitud es ilegal. ¿Te interesa entonces?}
{153}{}{¡Nada de "y"! ¿Quieres el trabajo o no?}
{154}{}{¿Y?}
{155}{}{Entonces, ¿qué quieres que haga?}
{156}{}{Correcto. Cuando consiga un mapa, vendré por aquí.}
{157}{}{¿Dónde voy a encontrar un mapa?}
{158}{}{De acuerdo, aunque tengo algunas preguntas más.}
{159}{}{Estoy en ello. Te veré entonces.}
{160}{}{¿¡Cómo diablos voy a saberlo!? Si lo supiera, lo tendría, ¿no te parece? Mira, se supone que hay una célula en la ciudad. Encuéntrala y mira a ver lo que puedes hacer.}
{161}{}{Sólo unas pocas preguntas más.}
{162}{}{De acuerdo. Volveré.}
{163}{}{Ya has vuelto. ¿Conseguiste ese mapa?}
{164}{}{Sí.}
{165}{}{No.}
{166}{}{¡Todavía estoy esperando que termines el primer trabajo!}
{167}{}{Oh, sí, lo olvidé.}
{168}{}{No desde que hiciste tu trabajo. Gracias.}
{169}{}{Sólo un par de preguntas.}
{170}{}{No hay problema. Adiós.}
{171}{}{Buen trabajo. Ahora lo mejor que puedes hacer es esfumarte, por si esos Rangers se enteran.}
{172}{}{Un placer hacer negocios contigo.}
{173}{}{¡Pero no andes por aquí, imbécil! Alguien podría sospechar.}
{174}{}{Vale, ya lo pillo.}
{175}{}{¡Qué cojones? ¡Guardias! ¡Tenemos una intrusa!}
{176}{}{Entra ahí y te vuelo la puta cabeza. ¿Lo pillas?}
{177}{}{Es tarde y hemos cerrado. Vuelve por la mañana.}
{200}{}{Buen trabajo. Una cosa más, aunque. Eres un esclavista, ¿verdad? ¿Cómo 'bout you echar una mano y limpie esas casas de seguridad para mí. Yo podría
 usted paga por el trabajo - por ejemplo, de $1000.}
{201}{}{Buen trabajo. Una cosa más, aunque. Te ves como un medio sonuvabith. ¿Cómo 'bout you de borrar esas casas de seguridad para mí. Hay una recompensa por ello - por ejemplo, de $1000.}
{202}{}{Claro.}
{203}{}{No estoy interesado.}
{204}{}{Excelente. Aquí, permítanme marca de estas coordenadas en el mapa cosita. Informe cuando haya terminado.}
{205}{}{Su pérdida. Ahora usted mejor hacerte escasos, en el caso de los Rangers siempre sabios.}
{206}{}{De acuerdo. Adiós.}
{207}{}{En realidad, ¿crees que podrías enviar a algunos de sus hombres conmigo? Esto podría hacer que las cosas vayan un infierno de mucho más rápido, y más garantía de éxito.}
{210}{}{Ya estás de vuelta. ¿Limpie los Rangers' casas de seguridad?}
{211}{}{El infierno sí lo hice. Pedazo de la torta.}
{212}{}{No todavía. Todavía estoy trabajando en ello.}
{215}{}{De verdad? Caliente maldito. Esta es la mejor noticia que he escuchado hasta ahora. Este va a ser un golpe bastante duro para los Rangers. Buen trabajo. Aquí está tu paga. Ahora usted mejor hacerte escasos, los Rangers en la ciudad que de seguro te busca.}
{216}{}{Deje que em miren ... yo no tengo miedo. Gracias por el dinero.}
{217}{}{Mejor me fuera de la ciudad, a continuación,. Nos vemos más tarde.}
{218}{}{Parece que todo lo que hago se las arregla para mear a alguien. Estoy acostumbrado a que ahora. Bye.}
{220}{}{El infierno no. Yo no soy redondeo alguno de los chicos para este. Si usted siente que no puede manejar, y luego dejar.}
{221}{}{Yo nunca dije que no podía manejarlo. Yo sólo pensaba que sus hombres le gustaría unirse a la diversión. Pero lo que sea, me va a manejar en el mío propio, no hay problema. Voy a informar de cuando yo estoy hecho.}
{222}{}{Bien, usted puede contar de mí, idiota. Yo no voy a ser tu perro. Bye.}
{223}{}{Usted me llama pollo? Nadie me llama así y la vida!}
{225}{}{Bien, bien. Creo que puede reunir a algunos niños para que te ayuden en esto. Ellos se encontrarán en el camino. Estás listo para empezar
 ahora?}
{226}{}{Dame un poco de tiempo. Voy a estar de vuelta cuando estoy listo.}
{227}{}{Nací listo. Vamos a arrasar.}
{228}{}{Yo estoy listo. Vamos a ir.}
{229}{}{Creo que voy a pasar todo esto. He perdido el interés. Bye.}
{230}{}{Estás listo para la raid, o está usted aquí para perder más de mi tiempo?}
{231}{}{Necesito más tiempo.}
{232}{}{Yo estoy listo. Vamos a ir.}
{240}{}{Limpie el Rangers " casas de seguridad. Se trata de un golpe bastante duro para los Rangers en su lucha contra la esclavitud.}
{241}{}{Estoy buscando para comprar algunos esclavos.}
{250}{}{Así que puto agradable. Nosotros no vendemos aquí. Metzger en el norte, en el estudio puede ayudar con eso.}
{251}{}{Yo he estado allí y su acción no fue hasta mis estándares.}
{252}{}{A ver cómo me mató Metzger, no sé cómo va a ser útil para mí. Creo que me voy a matar en su lugar.}
{260}{}{Bueno, ¿no eres exigente con la mierda. Te das cuenta de que su acción no se limita a la Madriguera, ¿verdad? Él tiene su propio corral donde los esclavos se cayó.}
{261}{}{Interesante. ¿Cómo puedo llegar a este otro lugar?}
{270}{}{Qué, ¿crees que puedes conseguir lo que coño quieres gratis? $1000. Lo tomas o lo dejas.}
{271}{}{Qué, ¿crees que puedes conseguir lo que coño quieres gratis? Además, el cieno virtuosidad. No me gusta eso. $2000. Lo tomas o lo dejas.}
{272}{}{Muy bien, aquí.}
{273}{}{No importa.}
{274}{}{Voy a hacer lo que yo quiera. Y creo que me voy a matar ahora.}
{275}{}{Volveré cuando tenga más dinero.}
{280}{}{[Señala en el mapa la ubicación de la esclavista campamento.] Es por ahí. Ahora, ¿qué otra cosa vas a perder mi tiempo con?}
{281}{}{Tengo lo que necesito. Bye.}
