{100}{}{B?n th?y Klint, m?t ngư?i đ?ng t?c.}
{101}{}{B?n th?y Klint.}
{102}{}{B?n th?y m?t c?u trai tr? có cơ b?p cu?n cu?n v?i dáng v? r?t t? tin.}
{103}{}{Xin chào, }
{104}{}{. Anh chưa hoàn thành th? thách c?a Trư?ng l?o nên không qua đây đư?c.}
{105}{}{?...}
{106}{}{Tôi c?n quay l?i làng.}
{107}{}{Tôi có vài câu h?i.}
{108}{}{Đư?c r?i, tôi đi làm th? thách đây.}
{109}{}{(th? dài)}
{110}{}{. Vào đ?n. Làm th? thách. Không quay l?i cho đ?n khi xong. Tuân l?i Trư?ng l?o. Đi đi!}
{111}{}{Ng? đi.}
{112}{}{Th? l?i cho tôi, }
{113}{}{, nhưng tôi không đ? anh qua đư?c. N?u anh mu?n tr? l?i làng, h?y đi theo đư?ng hoàn thành th? thách trư?c m?t.}
{114}{}{Hi?u r?i. Ch?c là tôi đi đây.}
{115}{}{Tôi h?i vài câu đư?c không?}
{116}{}{Tôi có th? đá đít c?u và đi kh?i đây.}
{117}{}{Th? l?i cho tôi, nhưng tôi không tr? l?i đư?c. H?y th?c hi?n th? thách do Trư?ng l?o đ?t ra và ch?ng t? anh x?ng đáng d?n đ?u b? t?c.}
{118}{}{Đư?c r?i.}
{119}{}{C?n có hai ngư?i m?i có th? bê đư?c cây c?t này. M?t m?nh anh ch?c ch?n không đư?c đâu. Tôi s? không giúp anh cho đ?n khi anh vư?t qua th? thách c?a Trư?ng l?o.}
{120}{}{? h?. Tôi hi?u r?i.}
{121}{}{Xin chào, C?u tinh! R?t vui đư?c g?p anh. Tôi giúp g? đư?c đây?}
{122}{}{Ng? chào. Th? thôi.}
{123}{}{Chào h?i thôi. Tôi s?p lên đư?ng làm nhi?m v? r?i.}
{124}{}{C?u cho linh h?n tiên t? phù h? anh, C?u tinh. Tôi chúc anh hành tr?nh t?t đ?p.}
