{100}{}{You see a particularly leathery-looking Ghoul.}
{101}{}{You see Harold.}
{102}{}{You see a very old but still spry-looking ghoul.}
{103}{hld1a}{I gotta tell ya, ol' Harold's a bit slow on the draw hisself. The two of us talkin' wouldn't get a whole lot done.}
{104}{hld1b}{Ahh, ain't you cute. I just don't have time to try understanding ya right now.}
{105}{hld1c}{Heh heh, ain't you a kick. }
{106}{hld2a}{Hello there, smoothskin. The name's Harold. I help keep this town running.}
{107}{hld2a1}{Whatcha need, youngster?}
{108}{hld2b}{Well, golly-be-damned, smoothskin. You did us a great favor helping out our power plant. The name's Harold. I keep this town running.}
{109}{hld2c}{Mighty kind o' ya helping us out with the atomic power plant. We're in your debt. Now, what can this cranky-old carcass do for ya?}
{110}{hld2d}{You are somethin'. Just like the original. What can old Harold do for ya, Vault Dweller? }
{111}{hld2e}{Haven't you done enough harm, smoothskin? What do you want now?}
{112}{}{Smoothskin? Why did you call me that?}
{113}{}{Vault Dweller? I'm not a Vault Dweller.}
{114}{}{Hello, Harold. What do you do here?}
{115}{}{Is there someplace I can barter or re-supply here?}
{116}{}{Is that a tree growing out of your head?}
{117}{}{You must know if there's something called a Garden of Eden Creation kit here.}
{118}{}{Harold, I'd like to know where I can get some healing.}
{119}{}{I know you're probably still mad, but you mentioned the Master. My ancestor killed him.}
{120}{}{Hello, Harold. Just passing through. Goodbye.}
{121}{hld3}{Wha-whatever it takes to keep this place together. Better job on it than me.}
{122}{}{This place is coming apart?}
{123}{}{You don't sound so good.}
{124}{hld3a}{Yep, but I'm doing great for being dead! I never get tired of the looks when I tell that one.}
{125}{}{Ahh, right....So you say the place is falling apart?}
{126}{}{Dead, you say? Well, in that case you're doing great. So good you can answer my next question.}
{127}{hld4a}{Well, sorta. Our atomic reactor's a mite... sensitive. The people I got running it mean well, but... well, they are not the sharpest tools in the shed. If you know what I mean.}
{128}{hld4b}{Well, we're doing better now you've fixed our reactor. I'd never thought anybody'd get those idjits in Vault City to help us out.}
{129}{hld4c}{You know, it's not so bad now. You fix the power plant, then you get the info we need to make it good-as-new. Golly-be-damned, ain't you somethin'?!}
{130}{}{What do you mean?}
{131}{}{I didn't want to see Vault City destroy your town.}
{132}{}{Well, I didn't want to see Vault City destroy your town. Besides it was in their best interest to fix your power plant as well.}
{133}{}{Well, since it's in Vault City's best interest to fix up your reactor, it wasn't too hard to get the Optimization info from them.}
{134}{}{I don't like to complete any job only half-way.}
{135}{}{Well, I'd love to stay and chat with you but I've got things to do and places to go. Good luck.}
{136}{hld5}{Well, technically... it's a thingie.}
{137}{}{Okay, what does it do?}
{138}{hld6}{Need a little time on the whetstone yourself, huh? I mean they are not too bright. Here's an example. The other day I get a report. On it, it says the main coolant valve should be shut down. That woulda caused a meltdown that would make the Grand Canyon look like a pig wallow.}
{139}{}{That sounds bad.}
{140}{hld7}{Uh, yeah, that would be bad. Now, I got things fixed up in time, but we came close to the end there. They need someone to watch out for 'em.}
{141}{}{Good thing you're here to help them.}
{142}{hld8}{Who'd a thought I'd be making things right? Although if we don't get a Hydroelectric Magnetosphere Regulator pretty damn quick, there is gonna be trouble.}
{143}{}{What the hell is Hydra-magna-whateveraltor?}
{144}{}{Hmm, sounds like a real problem all right. Let me ask you something else.}
{145}{}{Trouble? What kind of trouble?}
{146}{}{Well, I've taken enough of your valuable time. Goodbye.}
{147}{hld9}{Heck, if it weren't for you, them damn idjits in Vault City woulda laid us out for the big dirt nap.}
{148}{}{I couldn't let Vault City kill all of you.}
{149}{}{Happy to help out, Harold. Let me ask you about something else, though.}
{150}{hld11a}{Mighty kind a'ya. Not many smoothskins would do that for a town full of ghouls. Kinda reminds me of a smoothie I knew, way back when.}
{151}{hld11b}{You know, you're a lot like the Vault Dweller.}
{152}{}{Another smoothie? What do you mean?}
{153}{}{Thanks. I'm hoping to live up to my ancestor. Let me ask you something else while I'm here that might help.}
{154}{}{Happy to help. Let me ask you about something else though.}
{155}{}{Well, all in a day's work really. I need to be going now, though. People to save, monsters to slay, disasters to avert, you know, all that sort of thing. Goodbye.}
{156}{hld14}{You cut with the dull edge of the knife, don't ya? You don't look like an orange peel left in the sun all day. Your skin's still soft and purty. }
{157}{}{Got me there. I'll try to make my next question a little more worthwhile.}
{158}{}{Oh. Yeah. Hey, let me ask you something else.}
{159}{}{You just better not be getting any funny ideas about my soft skin.}
{160}{}{Uh, well, I better be going. Goodbye.}
{161}{hld15}{Funny ideas? Well, you mean like skinning you alive with a rusty, dull, old knife and then grafting your still-warm, wet, glistening, oh-so-soft, skin over my crusty-rotten gook?}
{162}{}{Hey! You just keep the hell away from me. I'm getting out of here while I still have my skin!}
{163}{}{Yeah, that's exactly what I meant. Good call.}
{164}{hld16}{Well, you don't have anything to worry about....can't find my knife.}
{165}{}{How 'bout I change the subject with another question?}
{166}{}{Well, you just better keep your grubby mitts off my skin. Goodbye.}
{167}{hld17}{More skin! ... Need more skin! (chuckles) What happ'n? Drop your sense of humor in the dust on the way into town?}
{168}{}{I've got a lot on my mind, all right? I need some more information.}
{169}{}{I think I'll go look for it. Goodbye.}
{170}{hld18}{I just let a big fart and it still doesn't cover your stink. Why don't you just drift outta here?}
{171}{}{Okay, but first I wanted to apologize for the way I acted earlier.}
{172}{}{Put a sock in it ya smelly old ghoul. Goodbye.}
{173}{hld19}{That's a start, but you're gonna have to do better.}
{174}{}{I don't know what else to say. I guess I just don't deal well with things that are new to me. I am sorry, though.}
{175}{}{Okay, how 'bout this? If I had jerky that looked half as bad as you do I'd burn it just to keep from poisoning any scavengers that might happen upon it. Bye.}
{176}{hld20a}{Well, alright. But you'd better stop being a bonehead. }
{177}{hld20b}{Well, I tell ya youngster. Nice try but yer still an idjit. Maybe this'll be the lesson you need. You are outta here.}
{178}{}{I'm sorry. Now that we've got that settled. Let me ask you something.}
{179}{}{Okay, goodbye.}
{180}{hld21a}{I'd rather look like this than look like you and have to be you. You are a bonehead. Get the hell outta here. }
{181}{hld21b}{You're like that bad booger ya can't shake off your finger. But I'm still shaking.... Oh look, there ya go!}
{182}{hld21c}{Well, look what the wind pooped in. My favorite turd. Why don'tcha just squish on outta here?}
{183}{hld21d}{Wanna know how to keep an idjit in suspense?}
{184}{hld21e}{Hey, I was hoping you'd show up. You won a prize for bein' the biggest jerk. There's a party in your honor ten miles north of town. Better hurry.}
{185}{hld26}{Their best interest? What do you mean?}
{186}{}{Well, according to some economic data I got hold of Vault City is much better off if they help you to repair your power plant.}
{187}{}{I mean, it's always better to try to get along with others.}
{188}{}{Uh, nothing.}
{189}{}{Wow, it's much later than I thought it was. I better be going. Goodbye.}
{190}{hld27}{Economic data? You didn't give them that information th-that Gordon keeps flapping his yap about, did you?}
{191}{}{Uh, yes I did. Why?}
{192}{}{Uh, no, of course not.}
{193}{hld28}{Yeah, well, I'm sure some bonehead, very much like yourself, said the same thing about the Master.}
{194}{}{Sounds like a great story. Wish I had time to hear it but I gotta go.}
{195}{}{The Master? My ancestor killed him!}
{196}{hld29}{Nothing, huh? I'm not buyin' it. You just put us in a bind. Why don't you skedaddle while I thinka what to do.}
{197}{}{Uh, sorry.}
{198}{}{Yeah, sure. Why don't you just do that. Geez, try to help some people....}
{199}{hld30}{Why?! Now Vault City knows just how much we need uranium ore from Broken Hills. They could cut off them shipments and we'd be finished.}
{200}{}{Oh, it can't be as bad as all that. They seemed like reasonable people to me.}
{201}{}{I didn't know that was what they'd use the information for. I'm sorry. Goodbye.}
{202}{hld31}{Well, I sure hope not. Those idjits in Vault City hate ghouls. They'd cut off our ore shipments from Broken Hills in a white-hot minute. Then they'd set the terms. Wouldn't be long until Gecko'd be a slave camp.}
{203}{}{Oh, I'm sure they wouldn't do that. They seem pretty reasonable.}
{204}{}{Well, it's a good thing I didn't tell them anything like that then. Heh, heh. Hey, let me ask you something else.}
{205}{}{Well, shit happens. Sometimes it happens to you. Goodbye.}
{206}{hld32}{Reasonable? Reasonable! Well, I'm sure people said the Master was reasonable, too. What a bonehead. Get the hell out. Now!}
{207}{}{Maybe they have the right idea. Maybe it's time to put an end to freaks like you. Goodbye.}
{208}{}{Uh, well, I uh, that is. Goodbye.}
{209}{hld33}{Well, you might try talking to Wooz over in the Harp. You can't miss it - it's just across the way. }
{210}{}{Thanks. Let me ask you something else.}
{211}{}{Thanks, that's all I need to know for now. Goodbye.}
{212}{hld34}{Jealous? His name's Herbert. I talk to him when I get lonely... Heh heh. Just kiddin'... His name's Bob.}
{213}{}{Right... Well, maybe you or Bob will know the answer to this.}
{214}{}{Thanks, that's way more than I need to know for now. Goodbye.}
{215}{hld35}{A Garden of Eden Creation Kit? A GECK, right? I seem to remember Vaults had those. Don't know where you'd find one today. }
{216}{}{Thanks. Let me ask you something else.}
{217}{}{Thanks, that's all I need to know for now. Goodbye.}
{218}{hld36}{Just talk to my assistant, Lenny. He'll be able to fix ya right up.}
{219}{}{Thanks. Let me ask you something else.}
{220}{}{Thanks, that's all I need to know for now. Goodbye.}
{221}{hld37}{Another smoothskin. Had a lot of respect for that one.}
{222}{}{Who was that?}
{223}{hld38}{Well, I could probably remember if I wasn't dead. I never get tired of that joke. }
{224}{}{Maybe you don't...}
{225}{hld38a}{Well, to be honest, can't remember the name. But they wore a funny suit. Kinda like the one you're wearing.}
{226}{}{I'm wearing the Vault Suit that my ancestor wore. It's a totem of my holy quest.}
{227}{}{Oh, this old thing?}
{228}{hld38b}{No lie?}
{229}{}{I'm wearing the Vault Suit that my ancestor wore. It's a totem of my holy quest.}
{230}{}{No lie, Harold.}
{231}{hld39}{That so? Well, well, well. That explains a thing or two. I wondered why you looked familiar. I'm not losing the last coupla marbles I got left.}
{232}{}{We really look alike?}
{233}{}{Tell me what the Vault Dweller was like.}
{234}{hld40}{Yea, it looked just like that. Come to think of it, it had a 13 on it too. }
{235}{}{Actually, this is the suit of my ancestor, the Vault Dweller.}
{236}{hld41}{There is a resemblance. Near as I can remember, anyways. You know, your ancestor saved the whole darn lot of us.}
{237}{}{The Vault Dweller saved all of the ghouls?}
{238}{}{Thanks. It's nice to know. Look, I have to run off for a bit. I'll see you later.}
{239}{hld42}{Jumpin' to conclusions, youngster. That's gonna get your ass shot off someday. All of us. Saved every two-legged-shuffler on the dang planet. }
{240}{}{I didn't realize that.}
{241}{}{I think I've heard enough for now. Goodbye.}
{242}{hld43}{Well. Now ya do. And what happened next? For a thank you, the damn high-and-mighty Vaulties booted the Vault Dweller out. I always wondered what happened after that.}
{243}{}{I can tell you what happened.}
{244}{}{Enough reminiscing let me ask you something else.}
{245}{hld44}{Well, I'd sure like to hear that.}
{246}{}{The legend of the Vault Dweller starts with the Vault casting him out into the dry Wastes.... [You tell Harold the story of your ancestor]...and so that's why I'm looking for Vault 13 now.}
{247}{hld45}{Thanks for telling. I sure was curious all these years. You sure got your work cut out for ya. Huh, ya know....}
{248}{}{Know what?}
{249}{}{I've taken enough of your time already. I better be going. Goodbye.}
{250}{hld46a}{Well, I been saving these for a rainy day, but it sounds like you're gonna need'em more than I ever will. Here, take these.}
{251}{hld46b}{I was gonna give you some healing supplies but damn me if I didn't do that already. I tell you, gettin' old's hell on the memory.}
{252}{}{Thanks. Let me ask you about something though.}
{253}{}{Thanks for everything. I better be going though. Goodbye.}
{254}{hld48a}{Without a functional Hydroelectric Magnetosphere Regulator we're leaking radioactive coolant into the groundwater. Now that means, anyone using that water is not gunna need a night-light to take a midnight piss. Also, we need more fuel because our power plant is not burnin' it very efficiently.}
{255}{hld48b}{We need a Hydroelectric Magnetosphere Regulator and it needs to be installed soon or we have got some real problems. }
{256}{}{Sounds bad. Where would you get a Hydro magnetosomething-or-other?}
{257}{}{What happens if you don't get the part?}
{258}{}{Who do you buy your fuel from?}
{259}{}{Sorry to hear it. Let me ask you about something else.}
{260}{}{I think I'm going to have to leave you to your troubles for right now. Goodbye.}
{261}{hld49}{Well, I'm certain those ornery bastards in Vault City have one. Not that they'd share. Hell, even if we had one of those thingies, I'm not so certain Festus could install the dang thing.}
{262}{}{Vault City wouldn't give you the part? Even if it means that the groundwater won't be polluted anymore?}
{263}{}{Sounds like you've got a lot on your mind. Goodbye.}
{264}{hld50}{If we don't get it, you can bet those boneheads from Vault City will shut down our power plant, permanently.}
{265}{}{What will you do then?}
{266}{hld51}{We get our fuel from the Broken Hills. That's a mining community some ways south.}
{267}{}{Interesting. Where would you get one of those Hydro magnetosomething-or-others?}
{268}{}{What happens if you don't get that Hydro-part?}
{269}{}{Hmm, I think I should let you figure this out on your own. Goodbye.}
{270}{hld52}{Take dirt naps. Vault City doesn't play nice. They'll just come up here and kill all of us if we don't get that part. Well, at least I'll have a tree for a monument.}
{271}{}{What was the name of that part again?}
{272}{}{Sounds like you need that Hydro-thingy pretty badly. Let me ask you something else right now, though.}
{273}{}{Sounds like trouble. I need to run off and see what I can do. Bye.}
{274}{hld53}{Well, they'd only help us if they thought it was in their own best interest to do so. Huh. Not much chance of that happening.}
{275}{}{Hmm, you may be right. Still if someone could convince them that they should help you...}
{276}{hld54}{They shoot ghouls on sight. Makes conversation a bit tricky.}
{277}{}{I wonder if someone else could tell them.}
{278}{}{Yes, it would. Right now I've got another question.}
{279}{}{Hey, you never know. I'll see you later.}
{280}{}{To the north}
{281}{}{To the northwest}
{282}{}{To the west}
{283}{}{To the southwest}
{284}{}{To the south}
{285}{}{To the southeast}
{286}{}{To the east of here}
{287}{}{To the northeast}
{288}{}{I don't understand.}
{289}{}{I don't know.}
{290}{}{That hurts.}
{291}{}{That really hurts.}
{292}{}{That's got to hurt.}
{293}{}{I don't know anything about that.}
{294}{}{Yes}
{295}{}{No}
{296}{}{Why do you talk to me this way?}
{297}{}{You're not nice.}
{298}{}{Thank you. }
{299}{}{This is good.}
{300}{}{This isn't good.}
{301}{}{I have a good feeling about this.}
{302}{}{I have a bad feeling about this.}
{303}{}{These people are crazy.}
{304}{}{I didn't learn anything.}
{305}{}{I learned something}
{306}{}{Is everyone else crazy here?}
{307}{}{There must be another way.}
{308}{}{Follow me.}
{309}{}{Try this.}
{310}{}{Come here.}
{311}{}{I'm scared.}
{312}{}{I'm worried.}
{313}{}{I found something.}
{314}{}{I got lucky.}
{315}{}{You need to fix this.}
{316}{}{You need to turn this on.}
{317}{}{You need to unlock this.}
{318}{}{You need to open this.}
{319}{}{Maybe we should come back here.}
{320}{}{No, lie. I'll make sure the reactor gets fixed. One way or another. Hmm,
 I wonder if I can get Festus to do it. Oh well, goodbye for now.}
{321}{}{Hey Harold, I got that part you need to fix your reactor. I am going to go and try to get it installed in the reactor. I'll report back when I am done. Bye.}
