{100}{}{You see a bedraggled man wearing a lab coat.}
{101}{}{You see Jacob the Chemist.}
{102}{}{You see a bedraggled man in a stained lab coat. His hands are discolored from chemicals.}
{103}{}{Hi there. I'm Jacob, the chemist of the Chemist's Drugstore. What can I do for you?}
{104}{}{Mu?n g??}
{105}{}{Hello again! What can I for you today?}
{106}{}{Welcome back. What can I do for you?}
{107}{}{Da yagga! Eep oop op!}
{108}{}{Dugstore? Rugstore?}
{109}{}{I have some ore I want refined, and I don't want to pay the refinery's prices.}
{110}{}{What can you tell me about Broken Hills?}
{111}{}{I want some chemicals mixed.}
{112}{}{I was told to speak to you about a certain matter regarding mutants.}
{113}{}{Chào.}
{114}{}{::A look of disgust crosses his face:: Get out of here. I don't have time for you.}
{115}{}{[XONG]}
{116}{}{Drugstore. It's a drugstore. Look, do you want anything?}
{117}{}{You again? Do you want something?}
{118}{}{'Es!}
{119}{}{Unh uh.}
{120}{}{Fine. Let's see what you want.}
{121}{}{[THÊM]}
{122}{}{Then leave.}
{123}{}{[XONG]}
{124}{}{There. We're done. Thank you for the tip. Now please leave.}
{125}{}{D'okay!}
{148}{}{Why don't you tell me how you feel about mutants first?}
{149}{}{I hate them.}
{150}{}{I'm ambivalent about them.}
{151}{}{I like them!}
{152}{}{In that case, I'll give you the real history.}
{153}{}{A human named Jacob -- I was named after him -- founded this place. Then mutant Marcus came along
 and forced everyone under his rule. }
{154}{}{That's enough. You're crazy. Goodbye.}
{155}{}{Tell me more.}
{156}{}{Maybe if I tell you the real history, you'll change your mind.}
{157}{}{Okay. Tell me.}
{158}{}{No, I'm not really interested.}
{159}{}{In that case, it's just great being here. This town has everything you could want... mutant
 sheriff, uranium mine, hospital, store... you can get just about anything here. You want anything else?}
{160}{}{Đúng v?y.}
{161}{}{Không.}
{162}{}{Great. Bye.}
{163}{}{Chào.}
{164}{}{He's been ruling here ever since the Master was destroyed. He puts down anyone who disagrees
 with him... or they just "disappear." The place looks civilized on the top of things, but the truth is
 that it's a killing ground for bloodthirsty mutants. There's a friend of a friend who had friends who
 disappeared after speaking up.}
{165}{}{Ti?p t?c đi.}
{166}{}{That's enough. You're crazy. Goodbye.}
{167}{}{We all pretend that this is a civilized town, that we're all on the up and up... but we all live
 in fear of the mutant rage. Each day, there are fewer and fewer humans.}
{168}{}{All the mutants I've seen look old and decrepit.}
{169}{}{Why not fight back?}
{170}{}{That's because they're trying to fool you, friend. They're trying to fool you.}
{171}{}{Why not fight back against them, then?}
{172}{}{Fool me? I see. Well, I have to go. Nice talking to you.}
{173}{}{Actually, we are. Some friends of mine and I are planning to strike a blow that will rid this
 town of mutants, but we need to get some friends out of jail. Are you with us?}
{174}{}{Không.}
{175}{}{No. And I'm turning you in. You're crazy.}
{176}{}{Sure! }
{177}{}{Are you sure? This is a chance to keep humanity free, you know, from those vicious mutant
 bastards.}
{178}{}{Still not in.}
{179}{}{Oh, all right. You've convinced me. }
{180}{}{Then that's your choice. I'll let you go on with your life. Pity, though. You look tough.}
{181}{}{Yeah. Bye.}
{182}{}{You are, eh? I don't think so, traitor.}
{183}{}{What?}
{184}{}{I have a little job for you. Our friends, Manson and Franc, are being held in jail. I want you
 to get them out. Do it quietly, if possible. Don't want the whole town on your head.}
{185}{}{What if I kill someone?}
{186}{}{Got it. I have more questions.}
{187}{}{Forget it. I'm out.}
{188}{}{Got it. See ya.}
{189}{}{No problem. They're all mutants anyway. But do it quietly, for god's sake.}
{190}{}{Got it. I have more questions.}
{191}{}{Got it. See ya.}
{192}{}{More questions?}
{193}{}{I have some ore I want refined, and I don't want to pay the refinery's prices.}
{194}{}{What can you tell me about Broken Hills?}
{195}{}{I want some chemicals mixed.}
{196}{}{Nothing. Bye.}
{222}{}{Way to turn on your own kind, mutie-lover. How could you do that to Chad? I don't care what you've done for us. You're a
 disgrace to humanity.}
{223}{}{Chào.}
{224}{}{Well done on the jail work! }
{225}{}{Cám ơn.}
{226}{}{Did you really have to kill everyone? Now they're all going to be worried. Well, no matter.}
{227}{}{Sorry.}
{228}{}{You got them out. I guess that's the important part. Of course, now everyone in town knows
 you're linked to Manson and Franc somehow. Oh, well.}
{229}{}{Sorry.}
{230}{}{I think I can trust you with something important. How'd you like to do a little more work?}
{231}{}{What else can I do for you, friend?}
{232}{}{More work? Like what?}
{233}{}{I need some ore refined.}
{234}{}{Not just yet. I need some chemicals.}
{235}{}{Not just yet, thanks. Bye.}
{258}{}{It's like this. We hate the mutants. We want to kill them. The best way to get rid of 'em is to
 blow the mine up while they're inside. We want you to plant the charge.}
{259}{}{I'll do it!}
{260}{}{I can't do that.}
{261}{}{Excellent, my friend! Here. Take this explosive switch. Hook it up to the air purifier and get the hell out of there.
 We've arranged it so that the town's mutants will be in the mine.}
{262}{}{Just let me know when you're ready to go.}
{263}{}{Will do.}
{264}{}{I can't do it.}
{265}{}{Why not? Are you scared or something? Are you positive you won't do it?}
{266}{}{Đúng v?y.}
{267}{}{No, I guess I'll do it.}
{268}{}{I suppose I can understand. You'll be equally understanding, I hope, when I tell you to get the
 hell out of my sight. Traitor.}
{269}{}{[XONG]}
{270}{}{Are you ready to go on with the plan?}
{272}{}{Yes. Let's do it.}
{273}{}{I've changed my mind. I don't want to do this.}
{274}{}{Good. I've been waiting for this day. Just attach the explosive switch to the purifier in the mine
 and get the hell out. There'll be a huge explosion. See you afterwards!}
{275}{}{So long! Death to the mutants!}
{276}{}{I changed my mind. I don't want to do this.}
{277}{}{You utter traitor.}
{278}{}{You did good work. Once. Too bad you turned against us.}
{279}{}{We are finally free of the impure mutant scourge. Thank you so much for your help. There is a small cache of
 weapons in the basement under Liz's General Store. For your loyalty, please help yourself to what you find there.}
{280}{}{We're leaving town. You should too.}
{281}{}{Come find me when I'm in the store and we'll talk.}
{282}{}{Your ore is done. Here you go.}
{283}{}{Thanks!}
{284}{}{I'm not done with the ore yet. Give me some time.}
{285}{}{I had other questions.}
{286}{}{Okay. Bye.}
{287}{}{Ready for the distraction?}
{288}{}{Ready to try that distraction again?}
{289}{}{You got it. Want to help me make a distraction?}
{290}{}{I'd like to buy some... uh... medicine.}
{291}{}{Anything else?}
{292}{}{Đúng v?y.}
{293}{}{No, thanks. Bye.}
{294}{}{Now you can see how treacherous the mutants are. If only you had seen earlier.}
{295}{}{If you're not gonna help us, we ain't gonna help you.}
{296}{}{Well, what are ya doin' just standin' there? You've got patriots to rescue from incarceration!}
{297}{}{Oh.. That's right.}
{298}{}{I told you to break them out of prison, not get them killed! What the hell's the matter with you?}
{299}{}{I'm sorry... I just...}
{300}{}{Just nothin'. Whether you meant to or not, you've royally screwed up our plans for this town. Now yer gonna pay.}
{301}{}{Sorry, friend, but... I just lost my two best friends. Those bastard muties killed them in prison.}
{302}{}{Urrggg. Toooo badddd. Bye.}
{303}{}{Uh... Gee. I'm really sorry. You have my condolences. Bye.}
{304}{}{Oops.}
{305}{}{Oops? Did you say 'Oops?' You didn't have nothin' to do with this, did you?}
{306}{}{It was an accident, I swear!}
{307}{}{Hell no. Of course not! Damn muties!}
{308}{}{Accident, my ass! Eat this, you mutie-lovin' rat-bastard!}
{309}{}{Yeah, well... their day is comin'.}
{310}{}{I already told you everything you need to know about this place. So, what do you want?}
{311}{}{I have some other questions.}
{312}{}{Nothing. Forget it.}
{313}{}{Cám ơn.}
{314}{}{[TI?P T?C]}
{315}{}{Hey, friend. I appreciate your help gettin' our friends out of their spot of trouble. You're all right in my book.}
{316}{}{Cám ơn.}
