{100}{}{You see one of the Reno townsfolk.}
{150}{}{You see a ragged-looking man. He looks bored.}
{151}{}{You see a ragged-looking man. He has a dull look in his eye.}
{152}{}{You see a ragged-looking man. He looks like he is nursing a hangover.}
{153}{}{You see a ragged-looking man. He looks a little tipsy.}
{154}{}{You see a ragged-looking man. He gives you an irritated glance, then ignores you.}
{155}{}{You see a ragged-looking man. He looks pissed off.}
{160}{}{You see a ragged-looking woman. She looks bored.}
{161}{}{You see a ragged-looking woman. She has a dull look in her eye.}
{162}{}{You see a ragged-looking woman. She is staring a thousand miles away.}
{163}{}{You see a ragged-looking woman. She looks a little drunk.}
{164}{}{You see a ragged-looking woman. She gives you an irritated glance, then ignores you.}
{165}{}{You see a ragged-looking woman. When she catches your eye, she sneers.}
{200}{}{::Claps::}
{201}{}{::Cheers::}
{202}{}{Way to burn those Enclave bastards! Way to go!}
{203}{}{Way to crush the Enclave, }
{204}{}{Congrats on stomping the Enclave, }
{205}{}{Congrats on stomping the Enclave, }
{215}{}{Uh-oh. Get out of the way.}
{216}{}{Just looking at him... her... it... WHATEVER it is gives me the shivers.}
{217}{}{Think that thing's looking to cap anyone?}
{218}{}{It's hell's fury given flesh. Uh, underneath the armor, that is.}
{219}{}{Stay outta that thing's path.}
{220}{}{Talk about dangerous-looking...}
{221}{}{*Gulp*}
{222}{}{I think that Mr. Roboto dude was scanning me.}
{223}{}{I think that walking tank just gave me the stare of death. I'm outta here.}
{224}{}{I heard that thing fragged three hitmen just yesterday.}
{240}{}{Well, hellloooo stud.}
{241}{}{A stallion like you in need of a saddle? I'm free tomorrow night.}
{242}{}{What you doing later, sailor?}
{243}{}{Can I feel your muscles?}
{244}{}{How come you don't pass out when you get erect?}
{245}{}{Wanna come over to my place for a drink?}
{246}{}{I want to eat my dinner off your chest.}
{247}{}{Need a partner for your next film?}
{248}{}{::Stares at your biceps.::}
{249}{}{::Claps, whistles::}
{255}{}{Whoa. Check that out.}
{256}{}{Would you look at THAT?}
{257}{}{::Mouths the word 'damn.'::}
{258}{}{I KNEW I should have shaved today.}
{259}{}{Come chat with me for a sec, honey-tits.}
{260}{}{Tribals got them tits! Damn!}
{261}{}{Check out the rack on that tribal.}
{262}{}{That there's the main filly of my herd.}
{263}{}{I'd bathe for that woman.}
{264}{}{I got your mother lode right here.}
{265}{}{Shake it!}
{266}{}{Work it!}
{267}{}{::Whistles::}
{268}{}{Them legs go all the way up?}
{269}{}{Hey, beautiful, you got a tongue to go with that ass?}
{270}{}{You got fries to go with that shake, beautiful?}
{271}{}{Maybe she'll dance tonight.}
{272}{}{Did you see her latest film? Red hot, man, red HOT.}
{273}{}{Excuse me. I have to go to the bathroom and er, comb my hair for a sec.}
{274}{}{I'd like to be her underpants.}
{275}{}{I'd like to be her underwear.}
{276}{}{I'd like to smell her shorts.}
{277}{}{That is one foxy lady.}
{278}{}{Damn. All them curves and me with no brakes.}
{279}{}{Check out those bazoongas!}
{280}{}{Check out those begonias!}
{281}{}{I want to get a better look at those big brown eyes.}
{282}{}{Daaaaamn.}
{283}{}{Check out those headlights.}
{284}{}{I bet she has back problems.}
{285}{}{You don't look so tough, Mr. Prizefighter.}
{286}{}{I got 20 chips riding on you!}
{287}{}{Hey, champ! That last fight was great!}
{288}{}{Saw you fight in the ring. Damn good right hook you throw.}
{289}{}{You gonna take the fall? I got 30 chips riding on you.}
{290}{}{How much you bench?}
{291}{}{Where do you work out?}
{292}{}{Watch out for the Masticator. He has a taste for ears.}
{293}{}{I'd get you a drink if I hadn't blown all my money betting on your opponent.}
{294}{}{You don't look so tough, Ms. Left Hook.}
{295}{}{Can I see your abdominal muscles flex?}
{300}{}{Stay outta that man's path.}
{301}{}{I think he was looking at me.}
{302}{}{I think he just gave me the stare of death. I'm outta here.}
{303}{}{I heard he shot down three hitmen just yesterday.}
{304}{}{Just looking at him gives me the shivers.}
{305}{}{Think he's looking to cap anyone?}
{306}{}{Uh-oh. Get out of the way.}
{307}{}{It's hell's fury given flesh.}
{308}{}{Talk about dangerous-looking...}
{309}{}{*Gulp*}
{310}{}{La Femme Nikita, then some.}
{311}{}{Just looking at her gives me the shivers.}
{312}{}{Think she's looking to cap anyone?}
{313}{}{I think she was looking at me.}
{314}{}{I think she just gave me the stare of death. I'm outta here.}
{315}{}{I heard she shot down three hitmen just yesterday.}
{316}{}{What an ass! Uh, bad ass, that is.}
{320}{}{What's with all the slavers around here recently?}
{321}{}{I ain't seen that slaver around here before...}
{322}{}{I wonder if the slaver's headed to the Stables...}
{323}{}{Wonder if that slaver's got any stock...}
{324}{}{You headed to the stables, slaver?}
{325}{}{ANOTHER slaver. Mordino must have discovered a gold mine somewhere...}
{326}{}{Slaver's bound for Golgotha.}
{327}{}{That stink from Golgotha was damn awful last night...}
{328}{}{Friggin' slavers...}
{329}{}{Of all the rotten luck...}
{330}{}{Heard they got a new crop o' slaves.}
{331}{}{New crop of slaves in the whorehouse.}
{332}{}{Conjunction, Junction.}
{333}{}{I'm making bank.}
{334}{}{Sometimes too much to drink is not enough.}
{335}{}{Damned crossroaders in the casinos...}
{336}{}{Great, another low roller.}
{337}{}{House was against me.}
{338}{}{Fortune's against me.}
{339}{}{Glad they put that guy on the rack...}
{340}{}{Filthy stinkard...}
{341}{}{Slavers walking round like they own the place...}
{342}{}{The House ha'mercy on me.}
{343}{}{Bad luck, ill wind, not good times, not good times...}
{344}{}{Reno's a-heating up, time ta move on.}
{345}{}{That Bishop daughter is out of control.}
{346}{}{If the Temperance Union lectures me one more time...}
{347}{}{Saw Tully passed out in the gutter again.}
{348}{}{Damn Den gutter trash.}
{349}{}{I got to get out of this town.}
{350}{}{Saw another O.D. this morning. Flies all over his mouth. And he was SMILING.}
{351}{}{TRIED to quit, but...}
{352}{}{Slaver better watch it in this town...}
{353}{}{I hate this goddamn town.}
{354}{}{I've been in this town too long.}
{355}{}{This town's great... except for the tourists.}
{356}{}{This town's great... except for the slavers.}
{357}{}{This town's great... except for the pimps and whores.}
{365}{}{Is that some kind of slot machine that's following you around?}
{366}{}{Is that a robo-slot machine?}
{367}{}{Does your robot do tricks? Uh... magic tricks, I mean.}
{375}{}{Tell me that ain't a mutant.}
{376}{}{That a mutant?}
{377}{}{Holy shit. Mutants in New Reno. Must mean trouble.}
{378}{}{That mutant is one big mutha.}
{379}{}{Filthy mutant-lover...}
{385}{}{Yer friend has a bone through his nose.}
{386}{}{Everybody in yer little band stick a bone through their nose to prove themselves?}
{387}{}{That fella with you from the 'stick-a-bone-up-my-honker' tribe?}
{388}{}{That fella with the bone in his nose is proof that tribals ain't never gonna be civilized.}
{389}{}{That fella got a bone in his nose?}
{390}{}{That fella's got a bone in his nose the size of my arm. Keeee-rist.}
{391}{}{I don't even want to know how that friend o' yours got that bone in his nose.}
{392}{}{Great. It's one of those tribal shit-kickers.}
{393}{}{How many tribals are gonna be coming to this town?}
{394}{}{Another primate.}
{395}{}{Boy's bound for Golgotha.}
{396}{}{That stink from Golgotha was damn awful last night...}
{397}{}{Friggin' tourists.}
{398}{}{Of all the rotten luck...}
{399}{}{Heard they got a new crop o' slaves.}
{400}{}{Conjunction, Junction.}
{401}{}{I'm making bank.}
{402}{}{Sometimes too much to drink is not enough.}
{403}{}{Damned crossroaders in the casinos...}
{404}{}{House was against me.}
{405}{}{Fortune's against me.}
{406}{}{Glad they put that guy on the rack...}
{407}{}{Filthy stinkard...}
{408}{}{The House ha'mercy on me.}
{409}{}{Bad luck, ill wind, not good times, not good times...}
{410}{}{Reno's a-heating up, time ta move on.}
{411}{}{That Bishop daughter is out of control.}
{412}{}{If the Temperance Union lectures me one more time...}
{413}{}{Saw Tully passed out in the gutter again.}
{414}{}{Damn ferner.}
{415}{}{That one's not from around here.}
{416}{}{I got to get out of this town.}
{417}{}{Saw another O.D. this morning. Flies all over his mouth. And he was SMILING.}
{418}{}{TRIED to quit, but...}
{419}{}{Why risk jumping a claim like that?}
{420}{}{I hate this goddamn town.}
{421}{}{I've been in this town too long.}
{422}{}{This town's great... except for the tourists.}
{423}{}{This town's great... except for the slavers.}
{424}{}{This town's great... except for the pimps and whores.}
{425}{}{You selling that woman o' yours?}
{426}{}{How much for that woman you got with you?}
{427}{}{That woman you got with you shore is pretty.}
{428}{}{Can that woman o' yours cook? If so, I'll take her.}
{429}{}{How much for that skirt you got with you?}
{430}{}{Check out the new boss o' the walk.}
{431}{}{Gonna get some action to-night!}
{432}{}{Mrs. Bishop shore got a sweet ass.}
{450}{}{Mrs. Bishop's shore got a sweet ass.}
{451}{}{If the Temperance Union lectures me one more time...}
{452}{}{Great. It's one of those tribal shit-kickers.}
{453}{}{How many tribals are gonna be coming to this town?}
{454}{}{Another primate.}
{455}{}{Tribal's bound for Golgotha.}
{456}{}{That stink from Golgotha was damn awful last night...}
{457}{}{Can't find his ass in a sandstorm...}
{458}{}{Friggin' tourists.}
{459}{}{Of all the rotten luck...}
{460}{}{Heard they got a new crop o' slaves.}
{461}{}{Conjunction, Junction.}
{462}{}{I'm making bank.}
{463}{}{Sometimes too much to drink is not enough.}
{464}{}{Damned crossroaders in the casinos...}
{465}{}{Great, another low roller.}
{466}{}{House was against me.}
{467}{}{Fortune's against me.}
{468}{}{Glad they put that guy on the rack...}
{469}{}{Filthy stinkard...}
{470}{}{The House ha'mercy on me.}
{471}{}{Bad luck, ill wind, not good times, not good times...}
{472}{}{Reno's a-heating up, time ta move on.}
{473}{}{That Bishop daughter is out of control.}
{474}{}{Saw Tully passed out in the gutter again.}
{475}{}{Damn ferner.}
{476}{}{That one's not from around here.}
{477}{}{I got to get out of this town.}
{478}{}{Saw another O.D. this morning. Flies all over his mouth. And he was SMILING.}
{479}{}{TRIED to quit, but...}
{480}{}{Why risk jumping a claim like that?}
{481}{}{I hate this goddamn town.}
{482}{}{I've been in this town too long.}
{483}{}{This town's great... except for the tourists.}
{484}{}{This town's great... except for the slavers.}
{485}{}{This town's great... except for the pimps and whores.}
{486}{}{Might head downtown, see if any new men are in town...}
{487}{}{If the Temperance Union lectures me one more time...}
{490}{}{Way to burn those Enclave bastards! Way to go!}
{491}{}{I always knew the President wanted to kill us all.}
{492}{}{The President was alive? When was the last election?}
{493}{}{Way to crush the Enclave, }
{494}{}{The Enclave never messed with me, but I'm glad they're gone.}
{495}{}{I can't believe the Enclave were still fighting the war after all this time. Idiots.}
{496}{}{I felt a great disturbance... as if a hundred evil bastards on an oil derrick suddenly cried out in terror and were suddenly silenced. Strange.}
{497}{}{Congrats on stomping the Enclave, }
{498}{}{This game was brought to you by the letter Z.}
{499}{}{We miss Tim Cain. He used to cook wonderful bread. Then he would spank us like small children.}
{500}{}{Yeah, yeah, I'm the Avatar, too.}
{501}{}{New Reno was designed by Chris Avellone and Tom French. Rumor is that they will marry soon.}
{502}{}{Feargus got that frowny-look on his face when he saw how many float text messages I have.}
{503}{}{You score is 192 out of 208. You really should have used the mutated toe on Horrigan.}
{510}{}{You looking for your brother Robby? You know, the Robot? Aw, nevermind.}
{511}{}{Sorry, was I in your way? I'll leave town.}
{512}{}{Sorry, was I breathing your air? I'll stop.}
{513}{}{::Knocks on armor:: Anybody in there?}
{514}{}{'Danger, Will Robinson! Danger, Will Robinson!' Heh-heh. Uh... just a joke.}
{515}{}{Niiiiice armor. Does it have air conditioning?}
{516}{}{Don't you get hot in there?}
{517}{}{Lose your heart, tin man?}
{518}{}{Uh, hello, sir... ma'am... whatever you are.}
{519}{}{Anything wrong, sir... ma'am... uh, whatever you are?}
{520}{}{Are you some kind of new walking arcade game?}
{521}{}{Are you one of those new console systems that are coming out?}
{522}{}{No, I'm NOT going to oil your joints.}
{523}{}{You look like you were on your way to one of those battle-mech PC games and got lost.}
{524}{}{Yeah, yeah, 'clank-whirrr-clank' to you, too.}
{525}{}{If you think that armor intimidates me, you're right.}
{540}{}{You selling?}
{541}{}{Can I buy your clothes? I mean, right now?}
{542}{}{I KNEW I should have shaved today.}
{543}{}{Come chat with me for a sec, honey.}
{544}{}{C'mon, honey-lips... walk with me.}
{545}{}{Nimble little minx, aincha?}
{546}{}{I'd bathe for you.}
{547}{}{I got your mother lode right here.}
{548}{}{Them legs go all the way up?}
{549}{}{You gonna dance tonight?}
{550}{}{Excuse me. I have to go to the bathroom and er, comb my hair for a sec.}
{551}{}{I'd like to be your underwear.}
{552}{}{I'd like to smell your shorts.}
{553}{}{You are one foxy lady.}
{554}{}{Screw me if I'm wrong, darling, but don't you want to kiss me?}
{555}{}{Damn. All them curves and me with no brakes.}
{556}{}{Know what would look good on you? Me.}
{557}{}{Your panties may not be the best thing on earth, but they're damn close to it.}
{558}{}{Nice bazoongas!}
{559}{}{Nice begonias!}
{560}{}{Those headlights of yours are gonna blind me.}
{561}{}{Got back problems?}
{580}{}{Hello, sir. How are you?}
{581}{}{Anything wrong, sir?}
{582}{}{Sorry, was I in your way? I'll leave town.}
{583}{}{Sorry, was I breathing your air? I'll stop.}
{584}{}{Give my regards to your boss.}
{585}{}{Look, please... I don't want any trouble.}
{586}{}{Hello, ma'am. How are you?}
{587}{}{Anything wrong, ma'am?}
{600}{}{What's with all the slavers around here recently?}
{601}{}{I ain't seen you around here before...}
{602}{}{If yer lookin' to sell slaves, try the Mordinos.}
{603}{}{You headed to the stables? They keep most of the slaves there.}
{604}{}{Show me your stock.}
{605}{}{If you're looking to sell slaves, check with the Mordinos.}
{606}{}{I hate this goddamn town.}
{607}{}{I've been in this town too long.}
{608}{}{This town's great... except for the tourists.}
{609}{}{This town's great... except for the slavers.}
{610}{}{This town's great... except for the pimps and whores.}
{611}{}{There's drug-testing bein' done on slaves north of New Reno, I hear.}
{612}{}{Golgotha's south of Reno, in the desert.}
{613}{}{I may be poor, but not in spirit.}
{614}{}{I'm not poor, I just have rotten luck.}
{615}{}{That stink from Golgotha was damn awful last night...}
{616}{}{Dammit! See, I was up 53 chips, then...}
{617}{}{You better be careful around these parts, or you'll be bound for Golgotha.}
{618}{}{New Reno wouldn't be a bad place 'cept for all the friggin' tourists.}
{619}{}{Conjunction, Junction.}
{620}{}{I'm making bank.}
{621}{}{Sometimes too much to drink is not enough.}
{622}{}{Damned crossroaders in the casinos...}
{623}{}{A low roller is someone who comes into town and bets only a chip or two at the tables.}
{624}{}{House was against me.}
{625}{}{Fortune's against me.}
{626}{}{Glad they put that guy on the rack...}
{627}{}{Filthy stinkard...}
{628}{}{What do you want?}
{629}{}{Bad luck, ill wind, not good times, not good times...}
{630}{}{Reno's a-heating up, time ta move on.}
{631}{}{That Bishop daughter is out of control.}
{632}{}{If the Temperance Union lectures me one more time...}
{633}{}{Saw Tully passed out in the gutter again.}
{634}{}{I got to get out of this town.}
{635}{}{Saw another O.D. this morning. Flies all over his mouth. And he was SMILING.}
{636}{}{TRIED to quit, but...}
{637}{}{Stop bothering me.}
{638}{}{Look, I ain't got the time to talk to you right now.}
{650}{}{Yer friend has a bone through his nose.}
{651}{}{Everybody in yer little band stick a bone through their nose to prove themselves?}
{652}{}{That fella with you from the 'stick-a-bone-up-my-honker' tribe?}
{653}{}{That fella with the bone in his nose is proof that tribals ain't never gonna be civilized.}
{654}{}{That fella got a bone in his nose?}
{655}{}{That fella's got a bone in his nose the size of my arm. Keeee-rist.}
{656}{}{I don't even want to know how that friend o' yours got that bone in his nose.}
{657}{}{I hate this goddamn town.}
{658}{}{I've been in this town too long.}
{659}{}{This town's great... except for the tourists.}
{660}{}{This town's great... except for the slavers.}
{661}{}{This town's great... except for the pimps and whores.}
{662}{}{There's drug-testing bein' done on slaves north of New Reno, I hear.}
{663}{}{Golgotha's south of Reno, in the desert.}
{664}{}{I may be poor, but not in spirit.}
{665}{}{I'm not poor, I just have rotten luck.}
{666}{}{That stink from Golgotha was damn awful last night...}
{667}{}{Dammit! See, I was up 53 chips, then...}
{668}{}{You better be careful around these parts, or you'll be bound for Golgotha.}
{669}{}{New Reno wouldn't be a bad place 'cept for all the friggin' tourists.}
{670}{}{Conjunction, Junction.}
{671}{}{I'm making bank.}
{672}{}{Sometimes too much to drink is not enough.}
{673}{}{Damned crossroaders in the casinos...}
{674}{}{A low roller is someone who comes into town and bets only a chip or two at the tables.}
{675}{}{House was against me.}
{676}{}{Fortune's against me.}
{677}{}{Glad they put that guy on the rack...}
{678}{}{Filthy stinkard...}
{679}{}{What do you want?}
{680}{}{Bad luck, ill wind, not good times, not good times...}
{681}{}{Reno's a-heating up, time ta move on.}
{682}{}{That Bishop daughter is out of control.}
{683}{}{If the Temperance Union lectures me one more time...}
{684}{}{Saw Tully passed out in the gutter again.}
{685}{}{I got to get out of this town.}
{686}{}{Saw another O.D. this morning. Flies all over his mouth. And he was SMILING.}
{687}{}{TRIED to quit, but...}
{688}{}{Stop bothering me.}
{689}{}{Look, I ain't got the time to talk to you right now.}
{690}{}{She's yer "wife," huh? Can I borrow her fer an hour or two?}
{691}{}{Wanna swap wives for a while?}
{692}{}{You selling that woman o' yours?}
{693}{}{How much for that woman you got with you?}
{694}{}{That woman you got with you shore is pretty.}
{695}{}{Can that woman o' yours cook? If so, I'll take her.}
{696}{}{How much for that skirt you got with you?}
{697}{}{Mrs. Bishop shore got a sweet ass.}
{700}{}{Gonna get some action to-night!}
{701}{}{Find a whore, get some play.}
{702}{}{Mrs. Bishop shore got a sweet ass.}
{703}{}{There's drug-testing bein' done on slaves north of New Reno, I hear.}
{704}{}{Golgotha's south of Reno, in the desert.}
{705}{}{I may be poor, but not in spirit.}
{706}{}{I'm not poor, I just have rotten luck.}
{707}{}{How many tribals are gonna be coming to this town?}
{708}{}{Tell the rest of your tribe to stay at home.}
{709}{}{Another primate? You tribals breed like mantises.}
{710}{}{That stink from Golgotha was damn awful last night...}
{711}{}{Dammit! See, I was up 53 chips, then...}
{712}{}{You better be careful around these parts, or you'll be bound for Golgotha.}
{713}{}{New Reno wouldn't be a bad place 'cept for all the friggin' tourists.}
{714}{}{Heard they got a new crop o' slaves.}
{715}{}{New crop of slaves in the whorehouse.}
{716}{}{Conjunction, Junction.}
{717}{}{I'm making bank.}
{718}{}{Sometimes too much to drink is not enough.}
{719}{}{Damned crossroaders in the casinos...}
{720}{}{A low roller is someone who comes into town and bets only a chip or two at the tables.}
{721}{}{House was against me.}
{722}{}{Fortune's against me.}
{723}{}{Glad they put that guy on the rack...}
{724}{}{Filthy stinkard...}
{725}{}{What do you want?}
{726}{}{Bad luck, ill wind, not good times, not good times...}
{727}{}{Reno's a-heating up, time ta move on.}
{728}{}{That Bishop daughter is out of control.}
{729}{}{If the Temperance Union lectures me one more time...}
{730}{}{Saw Tully passed out in the gutter again.}
{731}{}{I got to get out of this town.}
{732}{}{Saw another O.D. this morning. Flies all over his mouth. And he was SMILING.}
{733}{}{TRIED to quit, but...}
{734}{}{Stop bothering me.}
{735}{}{Look, I ain't got the time to talk to you right now.}
{736}{}{Might head downtown, see if any new men are in town...}
{737}{}{Glad they put that asshole on the rack...}
{1203}{}{!}
{1204}{}{! You kick ass! You kick ASS!}
{1205}{}{! You are so MONEY!}
{1493}{}{!}
{1497}{}{! You kick ass! You kick ASS!}
