{100}{}{You see a hunched over old man.}
{101}{}{The decrepit old man reeks of sweat and possibly urine. He's garbed in tattered, muddy rags, and is carrying a shovel.}
{102}{}{You see Tom.}
{200}{}{[The old man jolts with surprise when he sees you approach.] Uh, look, I really must be going...}
{201}{}{Now you hold on a minute. [You grab the man by the arm as he begins to walk away.] Who are you, and what are you
 doing here at this hour?}
{202}{}{What? Why, uh... the name's Tom and can't an old man enjoy a nightly stroll anymore without getting asked a bunch of
 questions?}
{203}{}{Not when he's slinking around like a thief and carrying a shovel.}
{204}{}{Alright fine, but why are you carrying a shovel?}
{205}{}{Whatever, I'm out of here.}
{206}{}{Vegye úgy, hogy nem is szóltam! Bocsánat, hogy zavartam.}
{207}{}{You mean this ol' thing? [He glances down at the rusty shovel in his hands.] Well, uh, you never know when you
 might find something that needs digging up. Always be prepared I say.}
{208}{}{Find something, eh? You mean like something in a grave?}
{209}{}{That's a good motto indeed. Well, take care.}
{210}{}{(Tom's eyes widen) I'm not quite sure what you, uh, mean.}
{211}{}{Tom, you're in a graveyard, you've got mud all over you, and it's past midnight. Why, even Torr could draw a
 conclusion from this. It's time to start giving me some answers, Tom. Why are you digging up these graves?}
{212}{}{[He puts down the shovel and sighs.] Alright, I'll tell you. My body ain't what it used to be. I've got no job,
 and no real means to get food. I know grave diggin ain't something that folks smile upon, but it's been a way for me to
 bring in some money. I'm just trying to survive... I don't mean no harm.}
{213}{}{I don't think that digging graves is a good thing for a man in your condition. Tell you what. You just mosey on
 out of here and we'll forget that this conversation ever happened. I never want to see your face again though, Okay?}
{214}{}{[The old man looks like he's about to protest, then stops.] Alright, you win. You've seen the last of poor old Tom.
 [He picks up his shovel and shuffles away.]}
{215}{}{On second thought, maybe it would be better for the world if I kill you.}
{216}{}{Goodbye Tom.}
{217}{}{I heard you've also been stealing crops from the farmer here.}
{218}{}{[The old man fidgets uncomfortably.] I couldn't help it! I was just so hungry and the food looked so good. Please,
 I don't mean any trouble. Look, I'll just go away and you won't see me here again. I promise!}
{219}{}{Alright, get going then. Before I change my mind.}
{220}{}{Wait, no need for any of that. The Petersons own the farm here and they're extremely nice people. Mr. Peterson
 even offered to talk with whoever was taking his crops and come to a reasonable agreement. Go talk with him.
 I'm sure he can help you out somehow.}
{221}{}{(The old man's eyes light up.) That doesn't sound like a bad idea at all. Hey, thanks. Maybe this world aint as
 cruel as I thought it was.}
{222}{}{You take care then, Tom. I'll check with you later and see how things are going.}
{223}{}{I sure hope that Peterson fella is as friendly as you say he is.}
{300}{}{You see Tom. He's wearing new worker's clothing and whistling cheerfully.}
{301}{}{Hey there! Wow, you were right. That Mr. Peterson is one kindly fella. He forgave me for what I did and even
 offered me a job helping out in the field. He says once I pay off the food I've taken, then I'll start making a
 weekly salary. Thanks again for your trouble.}
{302}{}{You're welcome, Tom. You take care of yourself now.}
{303}{}{Alright I wi- Oh, wait a second. I want to give you something for helping an old fella like me out. I found this
 lighter on some lad I dug up a couple weeks ago. I have no use for it and hopefully you might.}
{304}{}{Thanks, Tom. I'm sure this'll come in handy. See you around.}
{305}{}{(The old man nods and goes back to what he was doing.)}
{306}{}{[vége]}
{307}{}{Hello again. Thanks for everything!}
{308}{}{*Whistle*}
{400}{}{You youngins never learn. You aint the boss of me. I think I'll just kill you instead.}
{450}{}{Listen, I've dug up my share of graves too. I'm a bit of a kleptomaniac. What's your reason?}
{451}{}{I'm not unfamiliar to grave digging, Tom. Every man has his own enjoyment. Now you be on your way.}
{1000}{}{You figure out who is digging up the graves and set Tom towards a new life.}
{1001}{}{You figure out who is digging up the graves.}
{1002}{}{I'm going. No need to rush an old man.}
{1003}{}{You see Tom. He's got a smile on his face and he's wearing new worker's clothing.}
{1004}{}{He seems to be in much better condition and he smiles when you approach.}
