{100}{}{Egy számítógép-terminált látsz.}
{101}{}{Darion számítógép-terminálját látod.}
{102}{}{Egy szabványos számítógép-terminált látsz. Úgy t?nik, m?köd?képes, és adatokat vár.}
{103}{}{Belépsz a számítógépbe, és gyorsan átnézed a fájlokat. Néhány személyes naplóbejegyzés mellett több részletes jelentést is találsz az ÚKK-ról. Úgy t?nik, egy kém van a tanácsukban. Kimásolod a jelentéseket egy hololemezre.}
{104}{}{Nehézségeid vannak a fájlok elérésével.}
{105}{}{Megbeszéltük.}
{106}{}{A számítógép nem tartalmaz más hasznos információt az ÚKK-ban lapuló kémen kívül.}
{107}{}{Megbeszéltük.}
