{100}{}{A generátor normálisan m?ködik. A leadott teljesítmény optimális.}
{101}{}{Úgy t?nik, a generátor vészhelyzeti készenléti állapotban van. A teljesítmény-leadás minimális.}
{102}{}{A hiba megkeresése.}
{103}{}{Ó... asszem, indulni kéne.}
{104}{}{Valószín?leg rövidzárlat történt a rendszerben. A biztosítékok kioldottak, de nyitott állásban maradtak. Talán vissza tudod zárni ?ket, és helyre tudod állítani az energiaellátást.}
{105}{}{Nem találsz semmi rosszat a rendszerben. Egyszer?en csak nem m?ködik.}
{106}{}{A javítás megkísérlése.}
{107}{}{Ideje menni.}
{108}{}{Valahogy sikerült a csatlakozókat meglazítanod, és visszállítani az energiát!}
{109}{}{A fenébe. Ez keményebb dió, mint amilyennek látszott.}
{110}{}{Megbeszéltük.}
