{100}{}{Egy katonai gyakorlót viselõ fickó.}
{101}{}{You see Quincy, the mechanic.}
{102}{}{Egy fickót látsz katonai gyakorlóban. Az olajfoltokból ítélve inkább szerelõ lehet, mint katona.}
{103}{}{Quincy a nevem. Mit keresel itt?}
{104}{}{Kell kérdezni tõled valami.}
{105}{}{Semmi.}
{106}{}{Üdv! Kérdezni szeretnék néhány dolgot.}
{107}{}{Értem.}
{108}{}{Rendben, de siess vele. Rengeteg dolgom van.}
{109}{}{Mit akarsz tudni?}
{110}{}{Mi lenni ez hely?}
{111}{}{Én keresse gépmadárnak terve. Merre lenni?}
{112}{}{Egy szerelõ mondani nekem, hogy lenni itt gépmadár tervek.}
{113}{}{Én menni mostan.}
{114}{}{Mi ez a hely tulajdonképpen?}
{115}{}{A gépmadár-terveket keresem. Tudod, hol találom meg õket?}
{116}{}{Egy másik szerelõ mondta, hogy itt keressem a gépmadár terveit.}
{117}{}{Az a helyzet, hogy most mennem kell.}
{118}{}{Ez a szerviz. Egy csomó mindent javítunk itt, csak épp a gépmadarakat nem.}
{119}{}{Hol javítják meg gépmadárok?}
{120}{}{Hol javítják a gépmadarakat?}
{121}{}{Az egyetlen hely, ami alkalmas rá az a hangár belseje, vagy a szabad ég alatt. Innen fogva kitalálod magad is?}
{122}{}{Öhm... Oké.}
{123}{}{Oké. Vettem a lapot.}
{124}{}{Nos... Van másolatom a tervekrõl, de nem adhatom oda csak úgy akárkinek. Mit akarsz velük?}
{125}{}{Lenni barátok délen, kiknek kelleni.}
{126}{}{Nos... öhm...}
{127}{}{I've got some friends down south who want to get their hands on them.}
{128}{}{Az õrmi mondta, hogy hozzam el õket.}
{129}{}{Délen... Szent szar! Egy kém! Õrség! Riadó!}
{130}{}{Upsz.}
{131}{}{Hoppá. Lépjünk olajra!}
{132}{}{Te is csak az üres tárig vagy képes gondolkodni, mi? Na, figyelj, te IQ-bajnok, nem adhatom oda a terveket engedély nélkül. Szóval menj vissza, akárki küldött is, és intézd el a papírmunkát, oké?}
{133}{}{Na, figyelj, te IQ bajnok, nem adhatom oda a terveket engedély nélkül. Szóval menj vissza, akárki küldött is, és intézd el a papírmunkát, oké?}
{134}{}{Oké. Menni.}
{135}{}{Nem, mi lõni szarrá tégedet, aztán keresni megfele tervek... mit mondol?}
{136}{}{Jól van na!}
{137}{}{Nekem van egy másik ötletem. Szerintem elõbb cafatokra szedlek, aztán majd magam megkeresem a terveket.}
{138}{}{Egy szerelõ mondta... Raulra gondolsz? Õ küldött?}
{139}{}{Öhm, ja, persze.}
{140}{}{Ömm, nem tudom...}
{141}{}{Igen, õ volt az.}
{142}{}{Nem, nem Raul volt az.}
{143}{}{A szentségit! Tudod, Raul a fejét is elvesztené, ha nem volna olyan szépen a seggébe ágyazva... Ez már a harmadik alkalom, hogy elveszti a terveket, és most már ide sem mer jönni, hogy személyesen kérje el tõlem? Jól van, a szekrényben vannak mögöttem. Ha átadtad neki, mondd meg annak a seggfejnek, hogy látni akarom!}
{144}{}{Köszi.}
{145}{}{Áh, szóval visszajöttél! Elhoztad az engedélyed?}
{146}{}{Már megint te? Most mit akarsz?}
{147}{}{Igen, lenni nekünk plazmapuska. Ez lenni elég jó engedély...}
{148}{}{Nem, még nem.}
{149}{}{Igen, van egy kibaszott nagy puskám. Ez elég jó engedély, nem?}
{150}{}{Nem, még nem.}
{151}{}{Mi kérdezni tõled valami.}
{152}{}{Mi csak beugrani.}
{153}{}{Kérdezni akarok tõled valamit.}
{154}{}{Csak beugrottam.}
{155}{}{Te valami nudista vagy? Miért nincs rajtad egyenruha? Öltözz fel!}
{156}{}{Ha az õrmester észrevesz, nagy bajba kerülsz.}
{157}{}{Miért nincs magán egyenruha?}
{158}{}{Szent szar! Megtámadtak bennünket! Riadó!}
{159}{}{Behatolók! Hívjátok az õrséget!}
{160}{}{Õrség! Behatolók a szervizben!}
{161}{}{Mi van? Megtámadtak, vagy mi?}
{162}{}{Miért van riadó? Mi történik?}
{163}{}{Mi a szar folyik itt?}
{164}{}{Hé! Ne turkálj azokon a polcokon!}
{165}{}{Mondtam, hogy ne buzeráld a cuccom! Õrség!}
{200}{}{Oké. Ne higyj el semmit, amit hallasz!}
{201}{}{Ki mondta ezt neked? Mert az lesz a következõ, miután téged móresre tanítottalak!}
{300}{}{Nem látod, hogy nem érek rá?!}
{301}{}{Hé! Ne turkálj azokon a polcokon!}
{302}{}{Mondtam, hogy ne buzeráld a cuccom! Õrség!}
