{100}{}{Egy őrt látsz.}
{150}{}{Tyler egyik őre.}
{151}{}{A lány Tyler egyik őre.}
{200}{}{Még élsz?}
{210}{}{Megmutattuk nekik, mi?}
{211}{}{Senki sem baszakodhat velünk!}
{212}{}{Szétrúgtuk a seggüket!}
{213}{}{Épp ideje volt, hogy végezzünk velük.}
{214}{}{Nem fogom elfelejteni, ahogyan nézett. Remek volt.}
{215}{}{Meglepett, hogy Metzger le se szarta.}
{216}{}{Kíváncsi vagyok, Metzger miért nem lépett közbe.}
{225}{}{Nem tudom, mért velünk őrizteti ezt a szart.}
{226}{}{Ki akarná ellopni ezt a szart?}
{227}{}{Ez a munka gyerekjáték.}
{228}{}{Senki nem köthet belénk.}
{229}{}{Szerintem ez a cucc valami menedékből, vagy miből származhat.}
{230}{}{Egyébként mit keresel te itt?}
{231}{}{Nincs itt semmi különös.}
{232}{}{Ne fecséreld az időd, már vagy ezerszer átnéztük a cuccot.}
{233}{}{A mai este különleges.}
{234}{}{Utálok várni.}
{235}{}{Ezért bármikor kihagynám az italt.}
{236}{}{Idő van már? Alig várom.}
{237}{}{Remélem, én ölöm meg az elsőt.}
{238}{}{Miért vártak ennyit arra, hogy belénk kössenek?}
{239}{}{Ez érdekes lesz.}
{240}{}{Kár, hogy mégsem volt semmilyen akció.}
{241}{}{Kiváncsi vagyok, miért gondolták meg magukat.}
{242}{}{Az a sok várakozás, erre semmi...}
{243}{}{Szóval mi a helyzet azzal a csapdával, amit közösen akartunk állítani nekik?}
{244}{}{Mi történt a múlt éjszaka?}
{245}{}{Kár, hogy azok a beszariak betojtak. Szép lett volna kicsinálni őket.}
{246}{}{El sem hiszem, hogy azok a szemetek lesből akartak lecsapni ránk.}
