{100}{}{Egy gengszter.}
{150}{}{Lara bandájához tartozik.}
{151}{}{Úgy tűnik, Lara bandájához tartozik.}
{200}{}{Bölcs fickó vagy mondhatom...}
{201}{}{Most megvagy!}
{202}{}{Eljött a fizetség ideje!}
{203}{}{Gyere ide!}
{204}{}{Még nem végeztem veled.}
{205}{}{Ringyó!}
{225}{}{Kíváncsi vagyok, Metzger halála után mire számíthatunk...}
{226}{}{Szóval Metzgernek végre annyi?}
{227}{}{A te műved volt?}
{228}{}{Rejtek már sosem lesz a régi.}
{240}{}{El sem hiszem, végre legyőztük őket.}
{241}{}{Metzgernek most már tisztelnie kell minket.}
{242}{}{Megmutattuk nekik!}
{243}{}{Megismerték a mi igazságunkat.}
{244}{}{Nélküled nem tudtuk volna véghez vinni.}
{245}{}{Kösz a segítséget!}
{246}{}{Megcsináltuk!}
{247}{}{Bennünket akarsz csesztetni?}
{248}{}{Better watch your step.}
{249}{}{Lara az egyetlen indok, hogy miért nem akasztunk fel.}
{250}{}{Mit akartál elérni?}
{251}{}{Gyáva féreg!}
{252}{}{Undorodom tőled!}
{253}{}{Tűnj el!}
{254}{}{Tűnés!}
{255}{}{Készen állunk, csak add meg a jelet!}
{256}{}{Ideje már, hogy szétrúgjuk a seggüket.}
{257}{}{Utálok várni.}
{258}{}{Let's go already.}
{259}{}{Kész vagy már?}
{260}{}{Szólj Larának, ha készen állsz!}
{270}{}{Csatlakozni akarsz?}
{271}{}{Biztos Larához jöttél.}
{272}{}{Mi újság?}
{273}{}{Larával beszélj, ha akarsz valamit!}
{274}{}{Helló!}
{275}{}{Larához jöttél?}
{300}{}{Helló!}
{301}{}{Mi újság?}
{302}{}{Remélem, jól mennek a dolgok.}
{303}{}{Szóval tudsz nekünk segíteni?}
{304}{}{Örülök, hogy látlak.}
{305}{}{Hamarosan megmutatjuk Tylernek...}
{306}{}{Vannak új fejlemények?}
{310}{}{Thanks for the help. Too bad about Lara.}
{311}{}{Végre elkaptuk őket!}
{312}{}{Nélküled nem sikerült volna.}
{313}{}{Lara legalább harc közben halt meg.}
{314}{}{Nem hiszem el, hogy Lara is otthagyta a fogát...}
{315}{}{Megmutattuk Metzgernek, hogy ki a jobb.}
{316}{}{Metzgernek jobb velünk.}
{350}{}{Te akartad!}
{351}{}{Most mind kinyiffan!}
{352}{}{Ideje szétrúgni néhány lepcses picsát!}
{400}{}{We kicked serious ass! We'll be over at the church if you need us.}
{500}{}{Shit, I can't believe we lost Lara. We took care of the skeleton crew here, but Tyler and his crew are still alive.
 If we attack them now during their party over in the Residential area, we're sure to catch them off guard. Let's finish this job. You still in?}
{501}{}{Let me heal first. I'll tell you when I am ready.}
{502}{}{Gyerünk!}
{510}{}{You ready to take Tyler and his crew out?}
{520}{}{Hey, don't stray too far. We need to finish this tonight.}
