{100}{}{Egy félelmet kelt? útonállót látsz.}
{101}{}{Egy Rejtekbéli ?rszem.}
{102}{}{Ne most! Szolgálatban vagyok.}
{103}{}{Nem beszélgethetek veled.}
{104}{}{Kérlek, távozz!}
{105}{}{Ne tarts fel!}
{106}{}{Légyszíves, fordulj a f?nökömhöz!}
{107}{}{Nem válaszolhatok a kérdéseidre.}
{108}{}{Ne zaklass!}
{109}{}{Itt dolgozom...}
{110}{}{Nem tudok semmit.}
{111}{}{Csak a f?nökkel szoktam beszélni.}
