{100}{}{Egy félelmet keltõ útonállót látsz.}
{101}{}{Egy Rejtekbéli õrszem.}
{102}{}{Ne most! Szolgálatban vagyok.}
{103}{}{Nem beszélgethetek veled.}
{104}{}{Kérlek, távozz!}
{105}{}{Ne tarts fel!}
{106}{}{Légyszíves, fordulj a fõnökömhöz!}
{107}{}{Nem válaszolhatok a kérdéseidre.}
{108}{}{Ne zaklass!}
{109}{}{Itt dolgozom...}
{110}{}{Nem tudok semmit.}
{111}{}{Csak a fõnökkel szoktam beszélni.}
