{100}{}{Egy őrt látsz.}
{101}{}{Becky Kaszinó Bárjának egyik őre.}
{150}{}{Nagyon figyeli ezt az ajtót.}
{200}{}{Nem szöksz meg olyan könnyen.}
{210}{}{Az Rebecca szobája. Senki nem mehet be oda!}
{211}{}{Remélem, jól érzed magad!}
{212}{}{Beckyt keresed? Ott áll.}
{213}{}{Helló!}
{214}{}{Jó játékot az asztaloknál!}
{215}{}{Becky-nél kapod a legolcsóbb italokat a városban.}
{230}{}{Takarodj onnan most azonnal!}
{231}{}{Ne merj még egyszer hozzáérni!}
{232}{}{Állj hátrébb!}
{233}{}{Hagyd békén!}
{234}{}{Mi a szart csinál?}
{240}{}{Tolvaj!}
{250}{}{Ezt itt nem tűrjük meg!}
{300}{}{Bébi, van már dolgod munka után?}
{301}{}{Jól nézel ki, mint mindig.}
{302}{}{Te aztán tudod, hogy kell játszani, bébi.}
{303}{}{Édesem, felvennéd megint azokat a kockákat? Imádom a mozdulataidat.}
{304}{}{Mi a helyzet, édesem?}
{305}{}{Esetleg... te és én... munka után?}
{306}{}{Becky talán szabit ad holnapra, ha te... esetleg... elérhető lennél...}
{307}{}{Mondtam már neked, hogy milyen szép a szemed?}
{350}{}{Már megint rám se hederítesz. Ezt a játékot két emberre találták ki.}
{351}{}{Mi? Még mindig fújsz rám?}
{352}{}{Te aztán... öö... jól csinálod... abba ne hagyd...}
{353}{}{Na, mi van? Megint máshol jár az eszed?}
{354}{}{Elfoglalt vagy... értem. Később dumcsizunk.}
{355}{}{Ember, te aztán tudod, hogy kell megdolgozni a vágyaidért.}
{356}{}{Én... öö, akkor majd később beszélgetünk...}
{357}{}{Veled is jó beszélgetni... vissza is megyek oda.}
{375}{}{Bakker...}
