{100}{}{Ez a fickó elképeszt?en hatalmas.}
{101}{}{Ez a fickó elképeszt?en hatalmas.}
{102}{}{Ez az óriás valószín?leg hozzád hasonlókat eszik reggelire.}
{103}{}{Vénember! Most velünk jössz!}
{104}{}{Hagyjon minket békén! Nem csináltunk semmit!}
{105}{}{Nem mondom mégegyszer! Indulás, különben nem éled meg a következ? másodpercet!}
{106}{}{Nem! A titkomat inkább magammal viszem a sírba!}
{107}{}{Ahogy gondolod. MEGÖLNI ?KET!}
{108}{}{Ez nem rád tartozik. Hátra arc és tünés!}
{109}{}{Azt hiszem, rossz id?be voltál rossz helyen.}
