{100}{}{Remete.}
{101}{}{Remete.}
{102}{}{Úgy néz ki, mint aki már évek óta nem fürdött.}
{103}{}{Meg tod mondolni mér' én lenni remete? [Úgy tűnik, évek óta nem beszélt senkivel.]}
{104}{}{Miért?}
{105}{}{Átutazóban vagyok.}
{106}{}{Aghhh!}
{107}{}{Én akarja te hagyni engemet békibe!}
{108}{}{Ha már itt vagyok, akár csereberélhetünk is. Biztos vagyok benne, hogy van nálam olyasmi, amire szükséged van.}
{109}{}{Akkor magadra hagylak.}
{110}{}{Cserél. Aztán menni te el!}
{111}{}{Oké, itt van a cuccom...}
{112}{}{Legjobb, ha megyek.}
{113}{}{Mostan akkó' menny!}
{114}{}{Indulok.}
{115}{}{Hmm... tetszel nekem. Semmi mellédumálás. Maradj, csereberéljünk!}
{116}{}{K'}
{117}{}{Megyek.}
{118}{}{Beszélsz te jól. Most menny! Én lenni fáradt.}
{119}{}{[Befejezés]}
{120}{}{Beszédtől megfájdul fej. Menny!}
{121}{}{A beszédet befejeztem veled.}
{122}{}{Nem beszél. Megy.}
{123}{}{Menjen innen!}
{124}{}{Hagyj magamra!}
{125}{}{Hogyan te merel engemet támadni meg?}
{126}{}{Hagy békén engemet!}
{127}{}{Menek.}
