{100}{}{Mintha kissé inogna ez az ember.}
{101}{}{A buli csaposát látod.}
{102}{}{Úgy tűnik, hogy ő is végigkóstolta a saját áruját.}
{103}{}{Mih... mija... mit adhatok? [Hukk.]}
{104}{}{Nuka-Colát [$6]}
{105}{}{Sört [$15]}
{106}{}{Piát [$30]}
{107}{}{Semmit, kösz.}
{108}{}{Aghhh!}
{109}{}{Óhhhh... de hát pia nélkül mit ér a buli... [Átnyújt egy italt.]}
{110}{}{[Vége]}
{111}{}{Tessék. Kicsit meleg, me' nem volt ideje lehűlni. Gyo'sabban adom el a cuccot, mint ahogy csinálni tudom. [Az ital meleg, sárga és...]}
{112}{}{[Vége]}
{113}{}{[Úgy érzed, mintha elolvadna a gyomrod, és nyelsz egy nagyot.]}
{114}{}{[Vége]}
{115}{}{Azta... [hukk] Úgy nézem, te má' eleget ittá'.}
{116}{}{[Vége]}
{117}{}{Óhhh, haver! Nincsen 'lég pénzed! Gyere vissza ha lesz lóvéd!}
{118}{}{[Vége]}
{119}{}{Elég vad kinézete van.}
{120}{}{You see an addict.}
{121}{}{Kicsit idegesnek tűnik.}
{122}{}{Mitakarsz? Vanmindenem!}
{123}{}{Mentátot [$560]}
{124}{}{Buffoutot [$400]}
{125}{}{Pszichót [$800]}
{126}{}{Semmit, kösz.}
{127}{}{Aghhh!}
{128}{}{Nagyszerű! Virítsdalóvétaztánhúzzinnen! Vezetnemkelazüzletet.}
{129}{}{[Vége]}
{130}{}{Ahogyamondástartja. Nincspénznincsméz. Oh. Aztaszexremondják. Akkorlegyennincskassaznincsmassza. Gyerevisszahavanpénzed!}
{131}{}{[Vége]}
{132}{}{Hehhehe! Asszemmentátravanszükséged. Aggyegyezrest!}
{133}{}{[Adok neki 1000 dollárt]}
{134}{}{Megyek.}
{135}{}{ÓIGEN! Ezmajdjólhelyretesz!}
{136}{}{[Befejezés]}
{150}{}{Hé, milyen cuki vagy. Mi a neved?}
{151}{}{Még egy kis löketet! Óh, igen!}
{152}{}{Készen állsz... akarsz elsülni?}
{153}{}{Ne... ne... neh... neh-nah-ne.}
{154}{}{Ezt nézd! Igen!}
{155}{}{Menj innen!}
{156}{}{Most tök részeg leszek.}
{157}{}{Menj elsülni ...máshova!}
{158}{}{Mi lenne, ha te meg én sétálnánk egyet messze a többiektől?}
{159}{}{Uhh, let's do it!}
{160}{}{Nee, részeg vagyok!}
{161}{}{[Büff!] ::mosolyog::}
{170}{}{Hé, nem akarsz velem bejönni a bokor mögé?}
{171}{}{Csináltad már ennyire felpörögve?}
{172}{}{Megmutassam neked a csillagokat, bébi?}
{173}{}{Egy kis szexre éhezem.}
{174}{}{Reméltem, hogy belebotlok valakibe, aki készen áll bármire.}
{175}{}{Ennyi elég volt.}
{176}{}{Hé, van egy cigid?}
{177}{}{Hé, ez csak egy kaland volt... szeretem a szabadságot.}
{178}{}{Simulékony vagy, mint egy macska. Akarlak téged!}
{179}{}{Készen állsz?}
{180}{}{Ne most! Be kell lőnöm magam...}
{181}{}{Légy résen! Bemegyünk.}
{200}{}{Ne legyél má' hülye!}
{201}{}{Menj, bulizz máshol!}
{202}{}{Ki engedett be téged?}
{203}{}{Ez nem frankó!}
{204}{}{Nyugi, haver!}
{205}{}{Pihenj, ember!}
{210}{}{It seems she's been sampling some of her own merchandise.}
