{100}{}{Egy koszos, borostás férfit látsz.}
{101}{}{Prémvadász.}
{102}{}{Jobb, ha nem mész túl közel! Lehet, hogy a ruhájában rejtőző egynémely élőlény éppen tisztább otthont keres.}
{103}{}{Helló! Nem találkozunk túl gyakran emberekkel errefelé. Mit akarsz?}
{104}{}{Van eladó gekkóbőrötök?}
{105}{}{Átutazóban vagyok.}
{106}{}{Aghhh!}
{107}{}{Hát, éppenséggel van pár eladásra szánt bőrőm. Megkímélnél a város meglátogatásától, ha megvennéd őket.}
{108}{}{Mutasd, mid van!}
{109}{}{Rá se ránts!}
{110}{}{Aghhh!}
{111}{}{Here's what I got: }
{112}{}{ regular gecko pelts.}
{113}{}{ golden gecko pelts.}
{114}{}{Mindet megveszem.}
{115}{}{Talán legközelebb. Viszlát!}
{116}{}{Köszönöm a vásárlást. Viszlát legközelebb!}
{117}{}{Viszlát!}
{118}{}{Úgy néz ki, nincs elég pénz nálad. Mi lenne, ha adnál nekem öt percet, amit a nőddel tölthetnék? Hidd el, megérné!}
{119}{}{Úgy néz ki, nincs elég pénz nálad. Mi lenne, ha adnál nekem öt percet, amit a pasiddal tölthetnék? Érted, mire gondolok. Rendes csereüzletről van szó.}
{120}{}{Úgy néz ki, nincs elég pénzed. Figyelj csak! TÚL régóta vagyok már egyedül ebben az erdőben, ha érted, mire akarok kilyukadni. Megérné neked, hidd el!}
{121}{}{Persze.}
{122}{}{Kizárt dolog! Viszlát!}
{123}{}{[Miria meg fog bocsátani... alkalmasint. De nézd a jó oldalát! Kaptál pár gekkóbőrt a prémvadásztól.]}
{124}{}{[Davin nem tűnik túl megviseltnek az eset után.]}
{125}{}{[Mocskosnak érzed magad a szó számos értelmében... de lagalább van pár gekkóbőröd.]}
{126}{}{Viszlát!}
{127}{}{[Felemeli a jobb karját, és úgy beszél hozzád] Uff! Én lenni hatalmas prémvadász. Vadászni nagy gekkókra. Nem akarni háborgatni te földed. Békésen távozni. [Átad egy ajándék gekkóbőrt.]}
{128}{}{[Befejezés]}
{129}{}{Nincs több dolgom veled.}
{130}{}{Gyáva kutya!}
{131}{}{Ez az én vadászterületem. Távozz!}
{132}{}{Elevenen megnyúzlak!}
{133}{}{Trófeát csinálok a fejedből.}
{134}{}{Egy sima gekkóbőr: $}
{135}{}{Egy aranygekkó bőre: $}
{136}{}{Oké, haver. Nyertél.}
{137}{}{Mázlista, utána kell néznem a csapdáimnak.}
{138}{}{Mintha anyu szólítana, mennem kell.}
{140}{}{Looks like I don't have any regular gecko pelts, but I do have }
{141}{}{Looks like I don't have any golden gecko pelts, but I do have }
{142}{}{Sorry, looks like I'm all out of stock.}
{200}{}{Egy piszkos, szedett-vedett nőt látsz.}
