{100}{}{Az Összefogásért!}
{101}{}{Uraim, verjük vissza őket!}
{102}{}{Megölni a behatolókat!}
{103}{}{Megvédeni a várost!}
{104}{}{Gyerünk, gyerünk, gyerünk!}
{105}{}{Vigyázz! Útonállók!}
{106}{}{Most szépen szedem a sátorfámat!}
{107}{}{Óh, vazzeg... amikor már azt hittem, hogy biztonságban vagyunk! Elég! Elég volt!}
{108}{}{Futáááás!}
{109}{}{Tisztelettel bánj a mieinkkel!}
{110}{}{Ne szegd meg a törvényt!}
{111}{}{Ha azon töprengsz, miként okozhatnál balhét, csak jussunk az eszedbe! Viselkedj rendesen, és Marcus is rendesen fog viselkedni.}
{112}{}{Békeszerető Broken Hills-i lakosok vagyunk, de azért tudjuk, hogyan kell harcolni.}
