{100}{}{Egy fehér hõs-karaktert látsz.}
{101}{}{Egy nagyon izmos fehér férfit látsz, aki a 13-as Menedék kezeslábasát viseli. Miközben a történetét meséli, mosolyog és nevet.}
{102}{}{Egy fehér hõs-karaktert látsz. Mosolyog és nevetgél.}
{103}{}{Egy fehér hõs-karaktert látsz. Mosolyog és nevetgél.}
{104}{}{Naszóval a játékosom ANNYIRA, DE ANNYIRA hülye volt, hogy...}
{105}{}{Ezt kapd ki... azt hitte, hogy a sörétes puska lõszere a víztisztító chip, és visszavitte a Felvigyázónak...}
{106}{}{Micsoda egy idióta!}
{107}{}{Engem egy 'erõszakos, segghülye' játékos irányított, és meg kell, mondjam...}
{108}{}{Egy ideig szórakoztató volt, de gyorsan rá lehetett unni. Olyan sokat kell gyilkolászni, hogy a végére hulla fáradt leszel.}
{109}{}{Három egész órát kellett eltöltenünk a karaktergeneráló képernyõn, mire a játékosom VÉGRE eldöntötte, hogy játszani is fogunk a játékkal.}
{110}{}{Ian sokkal veszélyesebb volt rám nézve, mint az ellenségeink. Akárhol is kötött ki, remélem, meghalt azóta.}
{111}{}{Nézd csak a karaktermodellem izmait! Túlzásba vitték! Egyszerûen nevetséges!}
