{100}{}{Egy fehér hős-karaktert látsz.}
{101}{}{Egy nagyon izmos fehér férfit látsz, aki a 13-as Menedék kezeslábasát viseli. Miközben a történetét meséli, mosolyog és nevet.}
{102}{}{Egy fehér hős-karaktert látsz. Mosolyog és nevetgél.}
{103}{}{Egy fehér hős-karaktert látsz. Mosolyog és nevetgél.}
{104}{}{Egyszerűen lehetetlen feladat volt Dogmeatet életben tartani a Fallout 1-ben, főképp a végén.}
{105}{}{Egyszerűen nem volt elég szívós a végjátékhoz.}
{106}{}{Imádtam azt a kutyát. Azt kívántam, bárcsak feltűnne a stáblistában.}
{107}{}{Meséltek egy Vince DeNardo nevű játékosról, akinek volt egy taktikája arra, hogyan tartsa életben Dogmeatet a végén.}
{108}{}{Minden egyes szinten bezárta egy erőtér szobába, hogy távoltartsa a harcoktól.}
{109}{}{Az volt az idegesítő, hogy minden egyes szinten meg kellett csinálni ezt, különben a mutánsok kicsinálták volna a kutyát.}
{110}{}{Azt hiszem, végülis sikerült neki.}
