{100}{}{Talán mégsem kéne beállítani az időzítőt. Veszélyes lehet.}
{101}{}{Ez a robbanószer nem tűnik elég erősnek, hogy utat nyisson.}
{102}{}{A kocsi működőképes. Egy lökéssel talán még el is indulna.}
{103}{}{Esetleg egy rúdra erősített dinamit elég erős lenne ahhoz, hogy kirobbantsa a beomlott törmeléket.}
{104}{}{A dinamit rá van erősítve a rúdra, az meg a kocsira.}
{105}{}{Egy nagy lökés elindítaná ezt a kocsit.}
{106}{}{Megerőltetted magad a taszítással.}
{107}{}{Meglökted a kocsit.}
{108}{}{A kocsi egymagában nem elég ahhoz, hogy eltűnjön a törmelék.}
{109}{}{Nincs semmid, amihez hozzáerősíthetnéd.}
{110}{}{Bárcsak lenne egy rudad, amit a kocsi elejéhez erősíthetnél.}
{111}{}{Ráerősítetted a rudat a kocsira.}
{112}{}{Ráerősítetted a dinamitot a rúdra.}
