{100}{}{You see a bare-chested Shi man.}
{101}{}{? Sárkány. Számos Shi közember példaképe.}
{102}{}{You see a bare-chested, well-muscled man whose hands look like dangerous weapons.}
{103}{}{Miben segíthetek?}
{104}{}{Dinkle humper doo!}
{105}{}{Te ki lenni?}
{106}{}{Kivel verekedtél?}
{107}{}{Ki vagy te?}
{108}{}{Taníts meg bunyózni!}
{109}{}{Szeretnélek kihívni.}
{110}{}{Felejtsük el!}
{111}{}{Attól tartok, nem értem a nyelved. ::meghajol:: Legyen jó napod!}
{112}{}{Üüüüüdv!}
{113}{}{A Sárkány vagyok, barátom. Az elnyomás és az ellenségem, Lo Pan ellen harcolok. Az az ember akarja uralni ezt a várost.}
{114}{}{Taníts!}
{115}{}{Köfönöm.}
{116}{}{Akkor elkezdjük.}
{117}{}{[DONE]}
{118}{}{::Jól megnéz magának:: Nem hiszem, hogy jóra használnád a tudásod. Legyen jó napod!}
{119}{}{Grrr!}
{120}{}{Kérlek, bocsásd meg nekem a nyers modoromat. Jelen pillanatban nem beszélhetünk.}
{121}{}{Bah... oké!}
{122}{}{Lo Pan volt. Esküdt ellenségem és riválisom. Ha gy?zdelmeskedik felettem, félek, hogy a népem sorsa rosszra fordul.}
{123}{}{A nép olyan, mint egy birkanyáj. Légy a magad ura!}
{124}{}{Akkor gy?zedelmeskedned kell!}
{125}{}{Értem. Volna még néhány kérdésem.}
{126}{}{Te tényleg hiszel ebben? Akkor talán el kéne bánnod Lo Pannal. Viszlát!}
{127}{}{[DONE]}
{128}{}{Úgy bizony. Viszont attól tartok, egyenl?ek az esélyeink. Még a követ?ink számában is kiegyenlítettek az er?viszonyok. Egy ember elég, hogy felboruljon az egyensúly.}
{129}{}{Én jó leszek?}
{130}{}{Értem. Nos, még kérdeznék, ha nem gond.}
{131}{}{Értem. Hát akkor isten veled.}
{132}{}{Tényleg? Próbát kéne tennünk veled. Csak tisztességes párbaj dönthet majd.}
{133}{}{Egyszer úgy is meg fog halni, így vagy úgy! Mi a különbség?}
{134}{}{Elég méltányos. Hogy m?ködik a teszt?}
{135}{}{Ó, hát ebben az esetben mennem kell.}
{136}{}{Azok, akik nem tisztességesen küzdenek, nem jobbak az állatoknál!}
{137}{}{Oké, Pollyanna. Nyugalom.}
{138}{}{Én ravasz bunyónak nevezem. A "tisztesség" szót a gyilkosok dics?ítésére találták ki.}
{139}{}{Fogom. Hadd kérdezzek még valamit!}
{140}{}{Hát persze. Viszlát!}
{141}{}{El?ször is meg kell határoznunk, hogy a végs?kig küzdünk, vagy csak e képességeid ellen?rzéseképp.}
{142}{}{A végs?kig. Én képes vagyok legy?zni téged.}
{143}{}{Csak teszteljük a képességeinket. Nem akarlak megölni.}
{144}{}{Én sem. Felejtsd el!}
{145}{}{Erre a feladatra nem te vagy a megfelel? személy. Legyen jó napod!}
{146}{}{[DONE]}
{147}{}{Gondolod? A háború és a harc eléggé rokon fogalmak. Jobb, ha szabályok szerint harcolunk, mintha belefeledkeznénk az értelmetlen pusztításba.}
{148}{}{Bármi áron gy?zni fogok.}
{149}{}{Ha az embernek harcolnia kell, a túlélésre játszik. Ha valaki megpróbál megölni, minden létez? eszközt bevetek ellene.}
{150}{}{Hm. Mondasz valamit. Hát, kérdeznék még valamit.}
{151}{}{Igen, oké. Üdv!}
{152}{}{Nagyszer?! Lépjünk a szorítóba és addig verekedjünk, amíg valamelyikünk ott nem marad.}
{153}{}{[Attack now, with armor and weapons.]}
{154}{}{[Enter the ring, remove armor and weapons, and fight hand to hand.]}
{155}{}{Ah, egy harcos. Nekieresztelek az embereimnek és megnézzük, hogy boldogulsz. Kezdjük!}
{156}{}{[BEGIN]}
{157}{}{Egy szabályokkal regulázott küzdelemben nem kérdés, hogy a saját jószántadból fogtál bele. Ha egyszer belementél, eldobnád a szabályokat?}
{158}{}{Valószín?leg nem. De élet-halál kérdésben az ember bármit megtesz a túlélésért.}
{159}{}{Nem, nem hinném}
{160}{}{Értem az okfejtésed. Egy szó, mint száz... ha harcolni akarsz Lo Pannal, fegyvertelenül és véd?öltözék nélkül tennéd? Ha úgy adódik, hogy igénybe vesszük a segítséged, betartanád a szabályainkat?}
{161}{}{Igen, betartanám.}
{162}{}{Dehogy tartanám! Nyugodtan felejtsd el!}
{163}{}{Kiváló. Akkor nézzük, hogy a képességeid megfelel?ek-e Lo Pan ellen!}
{164}{}{Gyerünk!}
{165}{}{Most ne! Kés?bb visszajövök, és lejátszhatjuk.}
{166}{}{Én a Sárkány vagyok, a népem védelmez?je és Lo Pan esküdt ellensége. Mindketten a saját harci rendszerünk mesterei vagyunk.}
{167}{}{Elég jó vagyok a pusztakezes harcban. Akarsz egy próbát?}
{168}{}{Ez érdekes. Bizonyára gyümölcsöz?. Hadd kérdezzek még valamit!}
{169}{}{Kösz. Viszlát!}
{170}{}{Mivel megpróbáltad megszégyeníteni a népemet, most meg kell öljelek. El?re elnézésed kérem, ha fájni fog, mikor meghalsz.}
{171}{}{[DONE]}
{172}{}{Ne szólj hozzám, Hubologista birka! Semmi szükségünk nincs rád!}
{173}{}{[DONE]}
{174}{}{Tisztelettudásod egy disznóéval, erkölcsöd egy tüd?shaléval vetekszik. Nem óhajtok veled egy leveg?t szívni.}
{175}{}{[DONE]}
{176}{}{Te aztán elképeszt?en verekszel! Megküzdesz Lo Pannal?}
{177}{}{De. Akár most azonnal.}
{178}{}{Ez nem igazán az én harcom.}
{179}{}{Hogyne. De el?bb kérdeznék valamit.}
{180}{}{Megértem. Ha meggondolnád magad, tudod, hol találod ?t. Csak mondd meg neki, hogy a Sárkány nevében érkeztél!}
{181}{}{Jól van. Volna néhány kérdésem.}
{182}{}{Ööö... oké. Viszlát!}
{183}{}{Nemrég tértem vissza egy tiszteletbeli küldetésr?l.}
{184}{}{Nagyszer?! Kérdeznék.}
{185}{}{Nagyszer?! Viszlát!}
{186}{}{Lo Pan meghalt! Köszönettel tartozom neked, annyi szent. Most már meg vagyok gy?z?dve, hogy az iskolánk képes lesz továbbörökíteni a harci stílusunkat.}
{187}{}{Nagyszer?! Kérdeznék.}
{188}{}{Nagyszer?! Viszlát!}
{189}{}{A kung fud nem ér itt semmit.}
{190}{}{Egy nap legy?zlek, Sárkány!}
{191}{}{Várni fogok rád, Lo Pan!}
{200}{}{A Sárkány nem észleli az akciódat, és elosonsz mellette.}
{201}{}{A Shik nem tisztelik a tolvajokat! Távozz innen!}
{202}{}{Figyelmeztettelek, hogy távozz! Most megfizetsz!}
{203}{}{Nagyon úgy t?nik, hogy t?lem te már nem tudsz semmit tanulni.}
{204}{}{Lessons are more than just physical, grasshopper. Ponder this and return tomorrow.}
{205}{}{Ziggy Mester vagyok, az utolsó kihívód.}
{206}{}{Zurak vagyok. Készülj!}
{207}{}{A nevem Jimmy. Szedd össze magad!}
{208}{}{Herb vagyok. Innen nem jutsz tovább!}
{209}{}{Jobe-nak hívnak. Itt az id?, hogy vereséget szenvedj!}
{210}{}{Rube Mester vagyok. Most véged!}
{211}{}{HARC!}
{212}{}{Sokat kell még gyakorolnod!}
{213}{}{Na, hadd szóljon!}
{214}{}{Igazi halálig tartó küzdelemben gy?zted le a Sárkányt. Habár igazságos küzdelem volt, elvesztését sokan fogják fájlalni.}
{215}{}{Már legy?zted az embereimet, és átmentél az általam támasztott vizsgán. Immár megküzdhetsz Lo Pannal.}
{216}{}{A képességeidet csak a használatuk során fejlesztheted. Tovább már nem tudlak segíteni a tanulmányaidban.}
{217}{}{Kezdjük! Jer utánam!}
{218}{}{Mára elég volt a tréningb?l.}
{219}{}{A Sárkány tényleg nagyon jó, de jól felkészültél.}
{220}{}{Már legy?zted az embereimet. Senki nem akar kiállni veled.}
{221}{}{Annak ellenére, hogy nem tudsz róla, jelent?sen megsegítetted az ügyünket azzal, hogy eltávolítottad Lo Pant. Fogadd köszönetemet!}
{222}{}{Örömömre szolgált. Üdv!}
{223}{}{Nem kell megköszönni. Ég veled!}
{224}{}{Nem tesz semmit. Kérdezhetek valamit?}
{225}{}{Üdv! Én kérdezhetni?}
{226}{}{NYERTÉL!}
{227}{}{VESZTETTÉL!}
{228}{}{Következ? ellenfél!}
{230}{}{El?ször is be kell bizonyítanod, hogy képes vagy megcsinálni. Ki kell állnod öt emberemmel, persze egyszerre csak egyikükkel. Ha mindegyiket legy?zöd, jöhet a végs? próbatétel.}
{231}{}{Az meg mi?}
{232}{}{T?l nagy gondnak hangzik. Kés?bb találkozunk!}
{233}{}{You will be tested against my chosen apprentice. However, none of these battles will be to the death.}
{234}{}{Oké, csapjunk bele!}
{235}{}{Egyedül is elbánsz te Lo Pannal...}
{236}{}{[The Dragon studies you] I regretfully cannot let one of your skill level hurt himself.}
{237}{}{Oké, de kérdezhetek valami mást?}
{238}{}{Remek. Üdv!}
