{100}{}{Ez egy zömök Shi férfi, aki szemlátomást elég okos ember.}
{101}{}{Ő Ken Lee, az Uralkodó tanácsadója.}
{102}{}{Egy zömök Shi férfihez van szerencséd. Szemüvege mellé némi mosolyt is magára erőltetett.}
{103}{}{Mit szeretne, barátom?}
{104}{}{Mit akar?}
{105}{}{Segíthetek valamiben?}
{106}{}{Te ki?}
{107}{}{Ki vagy?}
{108}{}{Én is örülök, hogy látlak. Mi ez a hely?}
{109}{}{Eltűnt falusiak után kutatok.}
{110}{}{Üzemanyagra van szükségem.}
{111}{}{Beszélni szeretnék az Uralkodóval.}
{112}{}{A Hubologisták azzal bíztak meg, hogy öljem meg az Uralkodót.}
{113}{}{Semmi-semmi... kösz, viszlát!}
{114}{}{Ken Lee, az Uralkodó tanácsadója vagyok. Te pedig, barátom, elég egyszerű embernek látszol, szóval vésd az eszedbe: ha az Enklávét kutatod, a Poseidon Tankerrel kell odamenni hozzájuk. A hajóba üzemanyag kell. Fogadd áldásomat a feladathoz!}
{115}{}{Köfönet!}
{116}{}{Ken Lee, az Uralkodó tanácsadója vagyok. Uralkodóm azt tanácsolja nekem, hogy ne beszélgessünk, ezért nem is fogok. Minden jót, bolond!}
{117}{}{Grrr!}
{118}{}{Ahh, utazó, nem segíthetek magán. Esetleg valami más módon választ nyer majd a küldetése által felvetett kérdésekre. Minden jót!}
{119}{}{Ló napot!}
{120}{}{Ken Lee, a Shi Uralkodó tanácsadója, és bölcsességének letéteményese vagyok. És maga?}
{121}{}{Szeretnék találkozni az Uralkodóval.}
{122}{}{A nevem}
{123}{}{Maga olyan, mint az egyszeri csicskás, aki sokat képzel magáról!}
{124}{}{Én nem vagyok fontos ember. Viszlát!}
{125}{}{Ez az Uralkodó Acél Palotája. Maga most épp a Shi város szívében áll.}
{126}{}{És hol találom az Uralkodót?}
{127}{}{Milyen kísérleteket folytat itt?}
{128}{}{Mesélne a palota történetéről?}
{129}{}{Értem. Nos, viszlát!}
{130}{}{Ha látni akarja az Uralkodót, adja meg a saját nevét!}
{131}{}{Ó, rendben van. A nevem}
{132}{}{Hogyne! A nevem}
{133}{}{Igen.}
{134}{}{Rövid úton felejtsd el!}
{135}{}{Nem mindenki olyan szerencsés, hogy láthatja az Uralkodót. Először be kell bizonyítania, hogy érdemes rá. Hajlandó ilyesmire?}
{136}{}{Igen.}
{137}{}{Nem. Az elmúlt hónapokban egy életre való teszten mentem keresztül.}
{138}{}{Nem hinném, hogy az Uralkodó látni szeretné magát. Azt az utasítást kaptam, hogy tagadjam meg a belépést az illetlen és a gonosz lelkületű emberektől. Magára mindkettő ráillik, utazó. Minden jót!}
{139}{}{[RENDBEN]}
{140}{}{Az inzultusok sehova sem vezetnek, utazó, legfeljebb rövid úton eltávolítjuk az Acél Palotából. Kérem, vigyázzon tehát a nyelvére!}
{141}{}{Rajta csak!}
{142}{}{Rendben.}
{143}{}{Az Uralkodó láthatatlan a kiváncsi szemek számára. Mivel a feladatom szerint én oltalmazom az Uralkodót, se most, se később nem mondhatom el, hol található.}
{144}{}{Mást szeretnék kérdezni.}
{145}{}{Viszlát!}
{146}{}{Olyan kutatásokat végzünk, amelyek megváltoztatják a világot. Ha további válaszokat szeretne, keresse fel Dr. Wong Yi Tze-t!}
{147}{}{Felkeresem, viszont addig is hadd kérdezzek még egy s mást.}
{148}{}{Szólok. Viszlát!}
{149}{}{Egy tengeralattjáró roncsaiból kimenekült túlélők vagyunk. Amikor partra vetett bennünket a víz, megfosztottuk a járművet a borításától, és abból hoztuk létre az Acél Palotát. Vannak, akik nemigen hiszik ezt el.}
{150}{}{Hm. Úgy hangzik, mintha orrolna valakire.}
{151}{}{Értem. Köszönöm. Viszlát!}
{152}{}{Ah, igen! Láttam néhány filmjét! Feltételezem viszont, hogy nem ez a rendes neve...}
{153}{}{Pedig az.}
{154}{}{Valóban nem. A rendes nevem }
{155}{}{Ennél több névre nincs szüksége, vénember!}
{156}{}{Ez lehetetlen. Minden jót!}
{157}{}{[RENDBEN]}
{158}{}{Ennél azért többet is mondhatna. Tudom, hogy működik az "üzlet". Voltam már New Renóban korábban.}
{159}{}{Oké, a nevem }
{160}{}{Ez az igazi nevem! Most pedig hadd beszéljek az Uralkodóval!}
{161}{}{Kiváló! A következőt kérném magától: északi irányban létezik egy apró katonai bázis, Navarro néven. Rengeteg gépmadár állomásozik ott. Ahhoz, hogy legyárthassuk a sajátunkat, szükségünk van a terveire. Ha megszerzi nekünk, az Uralkodó elé járulhat.}
{162}{}{Legyen.}
{163}{}{Rövid úton felejtsd el!}
{164}{}{Nem gondolta meg magát a tesztünket illetően?}
{165}{}{Nem.}
{166}{}{Ó, rendben. Úgy lesz.}
{167}{}{Én nem hallottam semmiféle eltűnt falusiakról. Lehet, hogy az Uralkodó többet tudna róluk.}
{168}{}{Mást szeretnék kérdezni.}
{169}{}{Köszönöm. Viszlát!}
{170}{}{Volna itt egy második teszt: a Hubologisták az ellenségeink. A vezetőjük, BHK-9 rendszeresen elrabolja a gyermekeinket és agymosást végez rajtuk. Ölje meg nekünk a Shik nevében és lehetővé teszem, hogy beszélhessen az Uralkodóval!}
{171}{}{Vegye máris halottnak!}
{172}{}{Nagy eséllyel.}
{173}{}{Nem? Szomorú vagyok, de egyúttal meg is értem. Legyen szerencséje az útja során! Ha meggondolná magát, bármikor elérhet itt.}
{174}{}{Hogyne! Viszont volna még néhány kérdésem.}
{175}{}{Igen. Viszlát!}
{176}{}{Aggódva várom a próbálkozása eredményét. Minden jót!}
{177}{}{Jó napot.}
{178}{}{Berating someone? Any fool who had done their research can see that the very basis of Shi-town is the wreckage of this submarine. It seems fruitless to argue with those who would say otherwise.}
{179}{}{Ez nagyon józan gondolkodás magától.}
{180}{}{Az. Pedig sajnos naponta kell ilyen emberekkel találkoznom!}
{181}{}{Hát... akkor kérdeznék még valamit.}
{182}{}{Ó, szegény ember... Na, üdv!}
{183}{}{Kétségtelen, hogy maga megérdemli az üzemanyagunkat. Hiszem, hogy magára bízhatom a titkainkat is. A hátsó fertályban észreveheti, hogy a nagy számítógépet védő erőtér ki lett kapcsolva. Üsse be a "CSPDMSHR-Shih-huang-ti-X9372" jelszót és máris rácsatlakozott az Uralkodó-Számítógépre. Az Uralkodó oda fogja irányítani az üzemanyagot, ahova csak szeretné.}
{184}{}{Kösz.}
{185}{}{Őrség! Ide jött az ellenség egyik embere! Őrség!}
{186}{}{Valóban? Talán meg szeretné leckéztetni őket? Megígérhetem, hogy teljes támogatásunkról biztosítjuk magát, ha megöli BHK-9-et.}
{187}{}{Vegye máris halottnak!}
{188}{}{Nem.}
{189}{}{Kiváló. Remélem, hamarosan beszámolhat a sikeréről.}
{190}{}{Úgy lesz. Hadd kérdezzek még addig is!}
{191}{}{Úgy lesz. Üdv!}
{192}{}{Ebben az esetben maga csak ellenség lehet. Minden jót!}
{193}{}{Jó napot.}
{194}{}{A Nagy és Rettegett BHK-9 halálával a Hubologisták nem jelentenek többé igazi veszélyt se nekünk se a kutatóink számára. Gratulálok! Kivívta az elismerésünket. Szeretne beszélni az Uralkodónkkal?}
{195}{}{Igen.}
{196}{}{Most nem. Ellenben volna néhány kérdésem.}
{197}{}{Bebizonyította, hogy maga a Shik barátja. Mostantól magára bízhatom a titkainkat is. A hátsó fertályban észreveheti, hogy a nagy számítógépet védő erőtér ki lett kapcsolva. Üsse be a "CSPDMSHR-Shih-huang-ti-X9372" jelszót és máris rácsatlakozott az Uralkodó-Számítógépre. Remélem, ez hasznosnak bizonyul majd.}
{198}{}{Az Uralkodó egy SZÁMÍTÓGÉP?}
{199}{}{Vettem. Kösz.}
{200}{}{Igen. Ő tárolja a történelmünket, a kutatási anyagainkat, és a jövőbeli projektjeink terveit. Sokkal jobb, mint egy gyarló ember! Mellesleg a javaslatait a saját emberi természetünknek megfelelő tudással elegyítjük.}
{201}{}{Értem... Kösz, hogy feltarthattalak.}
{202}{}{Kémeink azt jelezték, hogy maga átadta a gépmadár terveit a Hubologistáknak. Lopja el tőlük, és busásan megjutalmazzuk érte!}
{203}{}{Mérget vehet rá. Ellenben még kérdeznék.}
{204}{}{Semmiképp.}
{205}{}{Köszönjük a gépmadár terveit, utazó. Mit tehetek immáron magáért?}
{206}{}{Volna néhány kiváncsi kérdésem.}
{207}{}{Öö... attól tartok, semmit.}
{208}{}{Miután megszerezte a gépmadár terveit, adja oda őket Dr. Wong Yi Tze-nek! Ő majd jó hasznát fogja venni.}
{209}{}{Oké. Addig is feltennék néhány kérdést.}
{210}{}{Oké. Viszlát!}
{211}{}{. Szeretnék találkozni az Uralkodóval.}
{212}{}{ dollár.}
{213}{}{Emlékezzen rá, hogy Dr. Wong Yi Tze-nek kell odaadnia a terveket!}
{214}{}{Remélem, nem azért jött, hogy inzultáljon...}
{215}{}{Ahogy azt már mondtam, tudnunk kell, hogy hívják magát.}
{216}{}{Nos, a nevem}
{217}{}{Kopjon már le a nevemről, maga idióta!}
{218}{}{Emlékezzen, az Uralkodó várja, hogy BHK-9 meghaljon...}
{219}{}{Sajnálom, de az üzemanyagunkat nem tudom felajánlani. Talán azért jött, hogy beszéljen az Uralkodóval?}
{220}{}{Ez miképp lehetséges?}
{221}{}{Kérdezhetek valami mást?}
{222}{}{Bárcsak felajánlhatnám az üzemanyagunkat, de sajnos a készleteink leapadtak. Valami módon átkerültek a Hubologistákhoz. Talán kéne találnia valakit, aki visszaszerzi nekünk.}
{223}{}{Most akkor találkozhatok az Uralkodóval?}
{224}{}{Tiszteletteljesen emlékeztetném magát arra, hogy a Dr. Wong Yi Tze számára eljuttatott gépmadár tervek ellenére sem adhatom meg az engedélyt egy Uralkodóval való találkozásra. Remélem, megérti.}
{500}{}{Azon nyomban távozzon, kérem, különben hívom az őrséget!}
{501}{}{Távozzon! Ez a második figyelmeztetés!}
{502}{}{Ez az utolsó figyelmeztetés!}
{503}{}{Őrség!}
{1430}{}{A Császár rejtve marad a vizslató tekintetek elől. A munkám az, hogy a Császár védelmeként és szürőjeként tevékenykdjek. Ugyanakkor, bebizonyította, hogy maga a Shik barátja. Mostantól magára bízhatom a titkainkat is. A hátsó fertályban észreveheti, hogy a nagy számítógépet védő erőtér ki lett kapcsolva. Üsse be a "CSPDMSHR-Shih-huang-ti-X9372" jelszót és máris rácsatlakozott az Uralkodó-Számítógépre. Remélem, ez hasznosnak bizonyul majd.}
{2001}{}{Öö... értem. Hát köszönöm, hogy rám pazarolta az idejét. Volna még egy falu, amit meg kell mentenem.}
