{100}{}{Egy lazaöltözékű őr. Unatkozik ugyan, de a figyelme nem lanyhul.}
{101}{}{Palotaőr.}
{102}{}{Palotaőr.}
{103}{}{Menjen tovább! Úgy nem lesz semmi gond.}
{104}{}{Van itt valami dolga?}
{105}{}{Szemmel tartjuk magát!}
{106}{}{Ne próbálkozzon semmi vicces dologgal!}
{107}{}{Tisztelettel bánj a mieinkkel!}
{108}{}{Ne érjen hozzá még egyszer! Nem figyelmeztetem többet!}
{109}{}{Menjen onnan!}
{110}{}{Lépjen hátra, lao wai, különben annyi ólmot eresztek magába, hogy zörögni fog járás közben!}
{111}{}{Lassan lépjen el onnan! Ha a fegyveréért nyúl, meghal!}
{112}{}{Meg ne forduljon a fejében!}
{113}{}{Abbahagyni! Most azonnal!}
{114}{}{Meghalsz, népünk ellensége!}
{115}{}{Most szépen elküldelek az izzó fémpokolba!}
{116}{}{Buddha könyörüljön a lelkednek!}
{117}{}{Szenvedj, népünk ellensége!}
