{100}{}{Egy fémpáncélt visel? férfit látsz.}
{101}{}{? Luke.}
{102}{}{Egy fémpáncélt visel? férfit látsz, a mellén villám-mintájú jelzés díszlik.}
{103}{}{Helló,}
{104}{}{. Luke vagyok. Mit tehetek érted?}
{105}{}{Honnan tud nekem név?}
{106}{}{Honnan tudod a nevem?}
{107}{}{Joshua említette, hogy látogatást tettél a Rejtekbeli irodánkban. Azt mondta rólad, hogy kicsi a bors, de er?s...}
{108}{}{Gyorsan terjednek a hírek. Kicsi, de er?s bors vagy te...}
{109}{}{Hogy érteni ezt?}
{110}{}{Merthogy?}
{111}{}{Nagyon sok ember figyelmét felkelted. Jobb, ha odafigyelsz a dolgokra!}
{112}{}{Folytasd!}
{113}{}{Folytasd, hallgatlak!}
{114}{}{Épp eleget mondtam. Jobb, ha mostantól a magad dolgával foglalkozol!}
{115}{}{Én kapja hasonló elzavarást Joshuától. Énnekem kell kérdezni kérdéset.}
{116}{}{Várja, én akar kérdezni!}
{117}{}{Joshua ugyanígy elhajtott. Kérdezhetek dolgokat?}
{118}{}{Várj, szeretnék még kérdezni egy-két dolgot!}
{119}{}{Joshua egyetlen egy kérdést engedélyezett. Én ugyanezt fogom tenni. Mi tehát a kérdésed?}
{120}{}{Rendben, de csak egy kérdésed lehet. Jól gondold meg!}
{121}{}{Hol találni ÉLET?}
{122}{}{Hol lenni Tizenháromos Menedék?}
{123}{}{Ki a fenék vagytok ti, srácok?}
{124}{}{Tudja, merre találhatnék egy ÉLET-et?}
{125}{}{Tudod, hol van a 13-as Menedék?}
{126}{}{Ki a fenék vagytok ti, srácok?}
{127}{}{Nos, úgy vélem a 13-as Menedékbeliek sosem használták fel a magukét. Ott biztosan találsz egyet. Sok szerencsét hozzá!}
{128}{}{Várni! Merre lenni Menelék?}
{129}{}{Na, várjunk egy picit! Hol található a Menedék?}
{130}{}{A koordinátái a t?lünk keletre található 15-ös Menedék számítógépes rendszerében vannak. Sok szerencsét hozzá!}
{131}{}{ vagyok.}
{132}{}{Köszi.}
{133}{}{Mi vagyunk az Acél Testvérisége. Jelen pillanatban nem fogok magunkról többet elárulni. Légy szerencsés!}
{134}{}{Várni! Nekem kell tunni többet!}
{135}{}{Várj, ennyi infó nem elég nekem!}
{136}{}{Sajnálom, de nincs több mondanivalóm a számodra.}
{137}{}{. Nos... Szemlátomást elég sokat fejl?dtél egy törzsbélihez képest. Ha id?d engedi, meg kéne látogatnod a San Francisco-i irodánkat. Nem fogsz benne csalódni. Most viszont, ha megbocsátasz, dolgom van.}
{138}{}{Sajnálom, de nincs több mondanivalóm a számodra.}
{139}{}{Várakozol...}
{140}{}{Ez egy privát iroda.}
{141}{}{Semmi keresnivalód odabent!}
{142}{}{Ez itt magántulajdon, szóval lehet továbbállni!}
