{100}{}{You see a humanoid covered in plant-growth. It drips green sludge.}
{101}{}{You see one of Dr. Sheng's foul creations.}
{102}{}{You see one of Dr. Sheng's foul creations. It looks like this one didn't turn out so well.}
{200}{}{Speak to the master, human.}
{201}{}{Your body would make a fine host...}
{202}{}{The master said you are off limits... for now.}
{300}{}{[A half-dozen strange humanoid creatures slowly shamble toward you. Their cadaverous vine and moss-covered bodies make repulsive squelching sounds with each awkward step. The lead creature addresses you in a harsh rasp.] Master wants to speak with you. Come with us, human, and do not resist ... or we'll make a host of you.}
{301}{}{[Shrug] This should be interesting. Lead the way.}
{302}{}{I'm not going anywhere with you, plant ... creature ... things.}
{303}{}{Nincs nekem id?m erre a szarra!}
{304}{}{Hold on. Who's your master? And what, exactly, are you?}
{310}{}{You have no choice, human. Either come and speak to Master, or we shall resort to violence.}
{311}{}{Then let's dance.}
{312}{}{All right. I'll meet this master of yours.}
{320}{}{Master will answer all questions. Now, come.}
{321}{}{Nem hinném.}
{322}{}{All right. I'll meet this master of yours.}
{400}{}{Uuuhhhhh...}
{401}{}{Grrraaah!}
{402}{}{Hheesssss...}
{403}{}{Ohhh...}
{410}{}{The master says no one may enter.}
{420}{}{The master says you may enter, human.}
{500}{}{You spray the creature and it gives off a heavy groan. Segments of the plant-growth covering it fall limp to the floor.}
{501}{}{You spray the creature; it gives off a heavy groan and oozes into a puddle before your eyes.}
