{100}{}{Egy számítógép-terminált látsz.}
{101}{}{Ez egy Hubologista számítógép.}
{102}{}{Ez egy számítógép. Habár működőképes állapotban van, elég primitív szegény.}
{103}{}{Ez az egység nem fogad el parancsokat. Viszlát!}
{104}{}{[Akárhogy is próbálkozol, nem tudod megtörni a számítógép védelmét.]}
{105}{}{Kilépés.}
{106}{}{Üdvözöli önt a HubLink.}
{107}{}{Várom a parancsait:}
{108}{}{Adatbázis elérése.}
{109}{}{Vezérlőszervek elérése.}
{110}{}{Kilépés.}
{111}{}{Adatbázis kiválasztása.}
{112}{}{Kutatás.}
{113}{}{Jövőbeli tervek.}
{114}{}{Pénzügyek.}
{115}{}{Vissza.}
{116}{}{[Miután átnyálazod a sok vallásos halandzsát, rátalálsz egy olyan fejezetre, amely a Hubologisták által kifejlesztett megerősített erőpáncélt taglalja. Ezenkívül arra is rájöttek, hogyan számoljanak ki bizonyos kilövési röppályákat, orbitális pályákat és térbeli koordinátákat. Mindezenfelül még az időjárás megzabolázásán is munkálkodnak.]}
{117}{}{Vissza.}
{118}{}{Kilépés.}
{119}{}{[Körülbelül fél órát töltesz BHK-9 céljainak olvasgatásával. A megvilágosodás és a Csillagbéli Atyával való egyesülés mellett az is nyilvánvaló, hogy nem igazán érez szívfájdalmat, ha régi, még a kezdeteknél vele tartó elvtársait is meg kell öletni. Egy kicsit meg van zakkanva az öreg.]}
{120}{}{Vissza.}
{121}{}{Kilépés.}
{122}{}{[Amint az nyilvánvaló a szöveg alapján, a Hubologista Egyház igen-igen gazdag. Az alapvető eljárás a következő: minden újonc azzal kezdi pályafutását, hogy valamennyi földi tulajdonát és pénzét átruházza az egyházra, s ezzel hitet tesz az eltökéltsége mellett. Ha valakitől nem kérik ezt, a Hubologisták nem fogják méltányos elbánásban részesíteni. Valahol a sivatagban van egy rejtekhelyük, ahol az így felhalmozott javakat raktározzák. A koordinátákat nem sikerül kobogarásznod.]}
{123}{}{Vissza.}
{124}{}{Kilépés.}
{125}{}{Kontrollmenü. Műveletkiválasztás:}
{126}{}{Merevlemez formázása.}
{127}{}{Rendszer állapotellenőrzés.}
{128}{}{Vissza.}
{129}{}{Kilépés.}
{130}{}{Tiltott művelet. Lépjen kapcsolatba a rendszergazdával! Kilépés. Viszlát!}
{131}{}{[RENDBEN]}
{132}{}{Úgy tűnik, ehhez nincs interfész.}
{133}{}{Az ESS Quetzel fel van töltve és készen áll a kilövésre.}
{134}{}{Az ESS Quetzel üzemanyagtartályai üresek.}
{135}{}{Mainframe operational. Pipeline operational. Research stations operational. Repair center operational. Cameras operational.}
{136}{}{Vissza.}
{137}{}{Kilépés.}
{200}{}{[The Hubologist Church appears to be hugely wealthy. The standard approach is to ask a new recruit to donate all
 his or her worldly possessions to the Church as a sign of good faith. When someone isn't asked to do this, apparently
 it means the Hubologists aren't intending to deal fairly. They have a huge cache of loot stashed somewhere in the desert.
 After a bit hacking and mathematical calculations, you determine the coordinates of the stash. You mark them down in your Pip-Boy.]}
{201}{}{[The Hubologist Church appears to be hugely wealthy. The standard approach is to ask a new recruit to donate all
 his or her worldly possessions to the Church as a sign of good faith. When someone isn't asked to do this, apparently
 it means the Hubologists aren't intending to deal fairly. They have a huge cache of loot stashed somewhere in the desert.
 You already determined the coordinates of it.]}
{210}{}{Hack the system.}
{211}{}{[After some time you gain full administrative access to the mainframe. You can now do whatever you want to the system.]}
{212}{}{Format the system.}
{213}{}{Initializing format procedure... Initialized... Formatting... Formatting Complete... System is shutting down. Goodbye.}
{220}{}{You format the Hubologist mainframe.}
{250}{}{Üzemanyag átirányítása a Poseidon tankerbe.}
{251}{}{Az üzemanyag átirányítva a kért helyre. Tároló = Üres. Program bezárása.}
{252}{}{[RENDBEN]}
