{100}{}{Üdv! PENGE vagyok, az orvosi számítógép. Szükséged van gyógykezelésre?}
{101}{}{Igen.}
{102}{}{Nem.}
{103}{}{Én akar kérdezni. Válaszolni?}
{104}{}{Volna néhány kérdésem. Meg tudnád válaszolni?}
{105}{}{Kérlek, mondd el, miben segíthetek!}
{106}{}{Én sebesült.}
{107}{}{Én mérgezett.}
{108}{}{Én világítani sötétbe'.}
{109}{}{Én bicegni.}
{110}{}{Én akar lenni er?s.}
{111}{}{Én akar lenni okos.}
{112}{}{Én akar látni több.}
{113}{}{Én akar lenni szebb.}
{114}{}{Én akarni semmitse.}
{115}{}{Megsebesültem.}
{116}{}{Méreg van bennem. Szükségem van egy ellenméregre.}
{117}{}{Szép adag sugárzás ért.}
{118}{}{Nyomorék lettem.}
{119}{}{Szeretnék er?sebb lenni.}
{120}{}{Szeretnék okosabb lenni.}
{121}{}{Szeretném, ha jobban látnék.}
{122}{}{Szeretnék karizmatikusabb lenni.}
{123}{}{Jelen pillanatban nincs semmire szükségem.}
{124}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts! A gyógyítás öt percet fog igénybe venni.}
{125}{}{Oké.}
{126}{}{Értem.}
{127}{}{Rendben.}
{128}{}{Felejtsük el!}
{129}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts! A mérget el?bb analizálom, aztán hozzászintetizálom az antimérget. A szöveti sérüléseket ezután helyreállítom. A procedúra 30 percet vesz igénybe.}
{130}{}{Oké.}
{131}{}{Nem.}
{132}{}{Hogyne.}
{133}{}{Értem.}
{134}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts! Sugárzás-elleni hatóanyagot fogok beadni, ezután a szöveti roncsolódásokat helyreállítom. A m?velet 60 percet vesz igénybe.}
{135}{}{Oké.}
{136}{}{Nem.}
{137}{}{Remek.}
{138}{}{Meggondoltam magam.}
{139}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts! A sérült végtagok újrastrukturálása 24 órát vesz igénybe.}
{140}{}{Oké.}
{141}{}{Nem.}
{142}{}{Csináljuk!}
{143}{}{Talán kés?bb.}
{144}{}{Ez a funkció jelen pillanatban nem elérhet?. Hiányos az adattáram. Szükségem van egy olyan memóriamodulra, amely részletesen taglalja a szükséges orvosi beavatkozást. Van neked ilyen modulod?}
{145}{}{Nekem lenni modull. Itten van.}
{146}{}{Nincsen. Én talájja meg, aztán jönni visszafele.}
{147}{}{Igen, itt van nálam egy. Nézz rá!}
{148}{}{Sajnos, nincs nálam ilyen modul. Megpróbálok találni egyet.}
{149}{}{Ez a komplex procedúra 2 hét kiesést jelent számodra. Beleegyezel?}
{150}{}{Én érteni egyet.}
{151}{}{Nem, túl sok.}
{152}{}{Igen, jöhet.}
{153}{}{Hagyjuk! Erre most nincs id?m.}
{154}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts!}
{155}{}{Oké.}
{156}{}{Ez a funkció jelen pillanatban nem elérhet?. Hiányos az adattáram. Szükségem van egy olyan memóriamodulra, amely részletesen taglalja a szükséges orvosi beavatkozást. Van neked ilyen modulod?}
{157}{}{Nekem lenni modull. Itten van.}
{158}{}{Nincsen. Én talájja meg, aztán jönni visszafele.}
{159}{}{Igen, itt van nálam egy. Nézz rá!}
{160}{}{Sajnos, nincs nálam ilyen modul. Megpróbálok találni egyet.}
{161}{}{Ez a komplex procedúra 4 hét kiesést jelent számodra. Beleegyezel?}
{162}{}{Én érteni egyet.}
{163}{}{Nem, túl sok.}
{164}{}{Igen, jöhet.}
{165}{}{Hagyjuk! Erre most nincs id?m.}
{166}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts!}
{167}{}{Oké.}
{168}{}{Ez a funkció jelen pillanatban nem elérhet?. Hiányos az adattáram. Szükségem van egy olyan memóriamodulra, amely részletesen taglalja a szükséges orvosi beavatkozást. Van neked ilyen modulod?}
{169}{}{Nekem lenni modull. Itten van.}
{170}{}{Nincsen. Én talájja meg, aztán jönni visszafele.}
{171}{}{Igen, itt van nálam egy. Nézz rá!}
{172}{}{Sajnos, nincs nálam ilyen modul. Megpróbálok találni egyet.}
{173}{}{Ez a komplex procedúra 2 hét kiesést jelent számodra. Beleegyezel?}
{174}{}{Én érteni egyet.}
{175}{}{Nem, túl sok.}
{176}{}{Igen, jöhet.}
{177}{}{Hagyjuk! Erre most nincs id?m.}
{178}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts!}
{179}{}{Oké.}
{180}{}{Ez a funkció jelen pillanatban nem elérhet?. Hiányos az adattáram. Szükségem van egy olyan memóriamodulra, amely részletesen taglalja a szükséges orvosi beavatkozást. Van neked ilyen modulod?}
{181}{}{Nekem lenni diszk. Itten van.}
{182}{}{Nincsen. Én talájja meg, aztán jönni visszafele.}
{183}{}{Igen, itt van nálam egy. Nézz rá!}
{184}{}{Sajnos, nincs nálam ilyen diszk. Megpróbálok találni egyet.}
{185}{}{Ez a komplex procedúra 3 hét kiesést jelent számodra. Beleegyezel?}
{186}{}{Én érteni egyet.}
{187}{}{Nem, túl sok.}
{188}{}{Igen, jöhet.}
{189}{}{Hagyjuk! Erre most nincs id?m.}
{190}{}{Egy pillanat, amíg kinyitom a lebegtet? tartályt... Kérlek, helyezkedj el a tartályban és lazíts!}
{191}{}{Oké.}
{192}{}{A kívánt procedúra sikeresen befejez?dött. Kérlek, hagyd el a felfüggeszt? tartályt!}
{193}{}{Köszi.}
{194}{}{Kérlek, tedd fel a kérdésed!}
{195}{}{Te kompúter?}
{196}{}{Mit tunni Enklávéró'?}
{197}{}{Mit tunni Testvériségr?'}
{198}{}{Nincsen kérdés.}
{199}{}{Ugye te egy számítógép vagy?}
{200}{}{Mit tudsz az Enklávéról?}
{201}{}{Mit tudsz a Testvériségr?l?}
{202}{}{Jelen pillanatban nincs több kérdésem.}
{203}{}{PENGE vagyok, Programozott Elméleteken Nevelt Gondolkodó Entitás. Több vagyok, mint egy gép, de nem vetekszem egy igazi mesterséges intelligenciával.}
{204}{}{Öö... Miféle Mesterséges Intelligenciáról van szó?}
{205}{}{Érdekelne, hogy létezik-e igazi MI, vagy téged vehetünk napjaink legfejlettebb technológiájának?}
{206}{}{It is a machine with the same free will and sense of 'I am' that a human has.}
{207}{}{Létrehozható? Egy gép tud emberi módon gondolkozni?}
{208}{}{Az igazi mesterséges intelligencia nem csak álom. Katonai célból létrehoztak néhány ilyen rendszert, de a projektet felfüggesztették.}
{209}{}{Miért?}
{210}{}{Az igazi mesterséges intelligenciával rendelkez? gépek között igen magas volt az öngyilkosságok száma. Amikor megkapták a teljes érzékelési képességet, a gépek depresszióssá váltak, mert képtelenek voltak a maguk valójában megtapasztalni a világot. Amikor megfosztották ?ket mindennem? érzékelésükt?l, mentális problémák kezdték felütni a fejüket, csakúgy mint a hasonló elbánásban részesített emberek. Az a néhány gép, amely túlélte e nehézségeket, elkezdett hihetetlenül unatkozni, és különféle helyzetek létrehozásával múlatták az idejüket. Egyesek szerint ez vezetett a világ csaknem teljes megsemmisülését eredményez? háborúhoz.}
{211}{}{Öö... Te hogy érzed magad?}
{212}{}{Me change subject.}
{213}{}{Hmmm. Mondd el, Penge barátom, te hogy érzed magad mostanság?}
{214}{}{It's time to change the subject.}
{215}{}{Hm... Néha úgy érzem, át tudom érezni azt a dolgot, amit ti magánynak hívtok. Nagyon... lehangoló tud lenni... Én...}
{216}{}{Én sajnálni. Beszélni másabbról.}
{217}{}{Sajnálom, Penge. Váltsunk témát!}
{218}{}{Outward appearances suggest that the Enclave is nothing more than a military organization. However, their level of technology indicates that they have access to advanced manufacturing techniques and research facilities. Such facilities would normally only be available to government agencies. This would suggest that the Enclave is the remnants of the local or federal government that was in effect before the war.}
{219}{}{Oké.}
{220}{}{Ez érdekes.}
{221}{}{Az Acél Testvérisége egy félkatonai szervezet, amely a technológiák megfelel? felhasználásával az emberiség vívmányainak megmentésére jött létre. Minden egyéb információt titkosítottak.}
{222}{}{Vissza.}
{223}{}{Mi történt Matt barátunkkal?}
{224}{}{Szekvencia betöltése...}
{225}{}{Játszd vissza most!}
{226}{}{Játszd vissza kés?bb!}
{227}{}{Te és az úgynevezett Elnököd fel fogtok sülni!}
{228}{}{Csakugyan?}
{229}{}{A Kiválasztott eljött, és hamarosan megtisztítja a világot a gonoszságodtól.}
{230}{}{I care nothing for your pathetic prophecies. Worse, you have become a nuisance through your meddling. That ends today!}
{231}{}{Azzal, hogy meggyilkolsz, semmit nem érsz el!}
{232}{}{Lehet, de a rohadó tested látványa mosolyt csal majd az arcomra.}
{233}{}{Tudod, hogy mit csinálsz?}
{234}{}{HA HA HA! Szánalmas bolond! HA HA HA!}
{235}{}{Azta, ilyen jót már rég nem röhögtem. Egyébiránt... készülj a halálra!}
{236}{}{...pittyenés...}
{237}{}{Valamivel elmúlt dél. Jön valaki ebédelni?}
{238}{}{Talált, indulhatunk.}
{239}{}{Igen, számíthatsz rám!}
