{100}{}{Egy világító ghoult látsz, arcán az aggodalom jeleivel.}
{101}{}{You see Hank the glowing ghoul, a worker here in the power plant.}
{102}{}{? egy világító ghoul. Folyamatosan ellen?riz néhány mér?m?szert.}
{110}{}{Üdv, Hank vagyok. Én felügyelem a reaktormag környékét. Nem mintha túl sok mindenre kéne itt felügyelni.}
{111}{}{Üdv, örülök, hogy megint erre jársz. Az ember olyan ellazultnak érzi magát itt a reaktormag közelében. A legtöbb simab?r? nem tudja, mit hagy ki.}
{112}{}{Helló, Hank. Be kéne jutnom a reaktormaghoz.}
{113}{}{Hank barátom, hoztam Haroldtól egy h?t?közeg jelentést, amit meg kéne nézned. Tessék...}
{114}{}{Üdvözlet, Hank. Csak körbenézek. Viszlát!}
{120}{}{Hehe... Nem javaslom, simab?r? barátom. Ropogósra sülnél az biztos. Én ugyan szeretem a meleget, de mégsem ajánlanám kipróbálásra. Egy egész pici h?ség és sugárzás van odabenn. Az er?m?vet épít? simab?r?ek ezért raktak be oda egy karbantartó robotot.}
{121}{}{Miféle karbantartó robotot?}
{122}{}{Köszönöm szépen. Viszlát!}
{130}{}{Na, hadd nézzem csak... E szerint a h?t?közeg szintje túl magas. Azt gondolná az ember, hogy a h?tés kikapcsolása azonnali leolvadáshoz vezet, de lehet, hogy mégse. Azt hiszem, jobb lesz, ha lekapcsolom a h?tést.}
{131}{}{A jelentés szerint a h?t?közeg szintje túl magas. Mit gondolsz, nem kéne kikapcsolni?}
{132}{}{Remek okfejtés, Hank. Na, akkor én megyek is. Viszlát!}
{133}{}{Most, hogy jobban végiggondolom, talán várhatnál vele egy kicsit. Hadd egyeztessek Harolddal, miel?tt lekapcsolnád a h?tést. Hamarosan jövök.}
{140}{}{Yeah, the smoothies that built this place didn't want to fry either, so they included a robot.
 It was designed to perform maintenance tasks by remote control from that terminal over there.}
{141}{}{Remek, ezt kipróbálom!}
{142}{}{Ezt ki kell próbálnom. Majd még jövök.}
{150}{}{Szép kis alkatrészed van. Épp erre volt szükségünk.}
{151}{}{Örülök, hogy tetszik. Van kedved üzembe helyezni?}
{152}{}{Kösz, nekem is igazán tetszik. Viszlát!}
{160}{}{Szeretnék segíteni, de nem tudom, hogy kell az ilyesmit beszerelni. Én többnyire csak figyelem itt a m?szereket. Próbáld meg Festust. ? itt a két lábon járó zseni... csak kérdezz rá nála.}
{161}{}{Hol találom Festust?}
{162}{}{Van esetleg másik mód?}
{163}{}{Már itt sem vagyok.}
{170}{}{Beszéltél már Festussal az alkatrész beszerelésér?l?}
{171}{}{Hol találom meg?}
{172}{}{Van esetleg másik mód?}
{173}{}{Még nem. Talán most sort kerítek rá. Üdv!}
{180}{}{Festust arra találod, amerr?l jöttél. Az irányítóteremben tölti az idejét. Nem igazán lehet összetéveszteni senkivel. Egy nagy rakás egoizmusba csomagolt b?zl?, nyavalygó fazon. Ellenben van esély, hogy segíthet rajtad.}
{181}{}{Kösz. Viszlát!}
{190}{}{Hát ha képes lennél irányítani a karbantartó robotot, az megcsinálná helyetted a beszerelést. Vagy, ha nincs jobb dolgod, menj be magad, és csináld meg egyedül.}
{191}{}{Karbantartó robotot mondtál?}
{192}{}{Én csináljam meg egyedül?}
{200}{}{Hát mostanában nem m?ködött valami fényesen. Folyton túlhevült. Nincs szükség rá, hogy használjuk, ezért nem törtük magunkat, hogy megjavítsuk a rajta lév? h?pajzsot. Ha kibogarászod a vezérl?kódokat, és nem használod túl sokáig, lehetséges, hogy megteszi, amit akarsz t?le.}
{201}{}{Kösz. Viszlát!}
{210}{}{Köszönjük, hogy megjavítottad a reaktort.}
{211}{}{Nincs itt h?vösebb mostanában?}
{212}{}{Köszönjük, hogy segítettél rajtunk.}
{220}{}{Még sosem hallottam így zümmögni.}
{221}{}{Úgy dorombol, mint egy kiscica.}
{222}{}{Jobban m?xik, mint valaha.}
{230}{}{Csak ne lábatlankodj és ne nyúlj semmihez!}
{231}{}{Hogy jöttél be ide?}
{232}{}{Miért nem sétálsz át azon az ajtón? Takaros kis hely az, kellemesen világít. Hehehe...}
{300}{}{Telebeszélted Hank fejét, hogy elindítson egy reaktorolvadást.}
{900}{}{Nem látod, hogy nem érek rá?!}
