{100}{}{}
{101}{}{}
{102}{}{}
{103}{powr1}{Itt az ENKLÁVÉ. Miért nem m?ködik a videóátvitele?}
{104}{}{Itt jól m?ködik. Én látom magát.}
{105}{}{Elromlott.}
{106}{}{Folyamatosan dolgozunk a vizuális kapcsolaton. Tesztelni akartam.}
{107}{}{(Kilépés.)}
{108}{powr2}{Ki a franc maga?}
{109}{}{Ööö... mi mind jól megvagyunk. És maguk?}
{110}{}{Mi a ...ét sssssssss ..zel a ..ca..al, ..ll engem? Vége.}
{111}{}{A Kiválsztott vagyok, szóval vigyázzon a nyelvére.}
{112}{}{Hármas egység jelentkezik.}
{113}{powr3_c}{A maga egysége még mindig nem m?ködik, jóember. Kivel beszélek?}
{114}{powr3a}{Francot se változott ett?l. Még mindig semmit sem látunk! Kivel beszélek?}
{115}{}{Ismételje meg! Vége.}
{116}{}{Elmondhatnám, de utána meg kéne, hogy öljem magát...}
{117}{}{I'm the Chosen One.}
{118}{}{Hát ez nem szokatlan errefelé, ugye? Itt semmi nem m?ködik többé jól.}
{119}{}{Maradjunk annyiban, hogy én tudom, maga meg rájön, ha akar. Viszlát!}
{120}{powr3b_b}{Mir?l beszél? Ki-ki a csoda maga?}
{121}{}{Elmondhatnám, de utána meg kéne, hogy öljem magát...}
{122}{}{I'm the Chosen One.}
{123}{}{Hát ez nem szokatlan errefelé, ugye? Itt semmi nem m?ködik többé jól.}
{124}{}{Maradjunk annyiban, hogy én tudom, maga meg rájön, ha akar. Viszlát!}
{125}{powr4a_a}{Itt az Elnök beszél! Bizonyám...}
{126}{powr4b_b}{Oh? Egy okos fiú, mi? Figyelj, futtatom a helyzetmeghatározót, cimbi. Majd meglátjuk, mit szólsz hozzá, ha az egész biztonsági csapat a nyakadon liheg. Faszfej!}
{127}{powr4c_a}{Na, elég a gyökérségeidb?l! Nem akarsz véletlenül ugorj-el-a-plazma-el?lt játszani a rohamosztaggal? He?}
{128}{}{Hé, ugye megbocsátasz nekem. Nem akartalak felb?szíteni.}
{129}{}{Sikerült bemérni téged, így most meg tudom mutatni, hova húzzál el.}
{130}{}{Szóval bemértél, mi? Igenám, de én is bemértelek közben, haver!}
{131}{}{Szívesen meglátogatnálak benneteket, és az összes haveroddal megbeszélném az általatok kitervelt eljegyzési ceremóniát, de momentán van nekem jobb dolgom is. Na, légy jó.}
{132}{}{Ajjaj, inkább a távozás mezejére lépnék... Viszlát!}
{133}{powr5_a}{Próbáljon er?síteni!}
{134}{}{Az ott... az megteszi... Mi más?}
{135}{}{Gain? What am I'm supposed to gain? I keep pretty active; I don't think I can gain anything.}
{136}{}{Megpróbálok kés?bb visszajönni. Viszlát!}
{137}{powr6_a}{Chosen One, huh? Well, uh, pardon me for not blowing sunshine up your ass, but I'm a little too busy for this, your highness.}
{138}{}{Térdepelj le el?ttem, és akkor meghagyom az életed. (Hmm, ennél szebben nem is mondhattam volna).}
{139}{}{Jól van, a térdeplést elhagyhatjuk. Egy enyhe meghajlás és csók a gy?r?mre ugyanúgy megteszi.}
{140}{}{Öö... úgy értettem, ogy engem választottak ki, hogy megjavítsam a kommunikációs egységet. Úgy t?nik itt minden bekrepált.}
{141}{}{Megelégeltem a tiszteletlenséget, melyet irányomba tanúsítasz. Pusztulj a szemem el?l, alattvaló!}
{142}{powr7_a}{Hármas egység? Azt hittem, még mindig a navarrói bázison vannak?}
{143}{}{A navarrói bázison? Ja igen, hát persze, hogy a navarrói bázison. Ott vagyunk. Hol is lennénk máshol?}
{144}{}{Nem, el kellett onnan jönnünk.}
{145}{}{A jelét egyre rosszabbul veszem. Viszlát!}
{146}{powr8_a}{Hah, mindjárt el is hiszem. Csak nehogy valakinek az elnök emberei közül a fülébe jusson, mert az id?k végezetéig krampácsolhat New Reno-ig bezárólag!}
{147}{}{Az Elnök?}
{148}{}{Hát mivel csak két lábam van, alaposan belefáradnék ebbe.}
{149}{}{Na, mehetünk megszakadni. Jobban teszem, ha nyomban rendbe hozom itt a dolgokat. Viszlát!}
{150}{powr9_a}{Yeah, that's a new one. Since my video's working you can see I'm rolling on the floor here. It does seem like everything's a damn secret though, huh? All the special ops on the mainland. I don't see how anything gets done.}
{151}{}{A szárazföldön? Miért, maga hol van?}
{152}{}{Hát, nekem úgy t?nik, hogy ez van mindenhol.}
{153}{powr10_a}{Igen-igen, tudja, milyen boldogtalan lesz, ha az emberek nekiállnak panaszkodni. Személyes sértésnek veszi, mintha ennek valami köze is lenne a h?séghez. Talán ez a velejárója, ha valaki az Egyesült Államok Elnöke lesz. Illetve, ami az országból maradt.}
{154}{}{Az Egyesült Államok Elnöke?}
{155}{}{Én ugyan nem szavaztam rá. Meg voltam gy?z?dve, hogy a hálószoba túlságosan leköti. Jobban szeretem az id?sebbeket, mert azoknak már f?leg a munkán jár az esze.}
{156}{}{Meghelet. Viszont most indulnom kell dolgzoni. Viszlát!}
{157}{powr11}{Hát ez nagyon mókás. De tudok egy kiváló helyet, ahol kipihenhetné a fáradalmait... legalábbis ezt hallottam arról a helyr?l.}
{158}{}{Akkor tehát nem New Renóban van?}
{159}{}{Hát asszem, most dolgoznom kell. Meg kell még reparálnom ezt a kommunikációs csatornát. Viszlát!}
{160}{powr12}{Az Egyesült Kibaszott Államok Elnöke. Maga szerint kir?l beszélek? Egyáltalán ki a fa - Kicsoda - Mi - Úgy picsán rúglak, hogy nem állsz meg a kibaszott lábadon! Ki beszél ott?}
{161}{}{A Kiválasztott vagyok. Csókold meg a... lábamat.}
{162}{}{I'm the Chosen One.}
{163}{}{Én pedig az Elnök, és jó nagy bajba keverte magát.}
{164}{}{Maga nem elég fontos személy, hogy ezt az információt átadjam.}
{165}{}{H?, asszem, mennem kell. Egy csomó munka vár itt rám. Viszlát!}
{166}{powr13}{Ez az ENKLÁVÉ f? kommu... de hát ezt magának tudnia kell. Ki maga?}
{167}{}{Hát, én csak... észrevette már, hogy a f?tt gekkónak olyasmi íze van, mint a brahmin farhátnak?}
{168}{}{Én a Kiválasztott vagyok, és garantálom, hogy ne felejtse el.}
{169}{}{Nem vagyok jelent?s személyiség. Viszlát!}
{170}{powr14}{Aha, pillanatokon belül megbánod te, hogy idetoltad a segged. Na, várjunk csak. Ez nem lehet... te a szárazföldön vagy.}
{171}{}{Hát persze, te hülyegyerek. Pont ott, ahol nem tudsz megfogni.}
{172}{}{Ez nem lehet. A kommunikációs pultnál állok alig pár lépésre t?led... Jól látszol innen. Ezt a bugrist...}
{173}{}{Igen, a Poseidon Olaj 12-es atomer?m?vénél vagyok. Gyere azt kapj el!}
{174}{powr15}{A Poseidon Olaj 5-ös reaktoránál vagy, most ellen?riztem. Ülj csak nyugodtan, és mindjárt megrendelek neked egy kis látványosságot. Lesz közte t?zijáték is.}
{175}{}{Ó, kedvesem, immmádom a t?zijátékot! Ne spórolj vele!}
{176}{}{A Kiválasztott vagyok! Jobb lenne, ha egy mosoly kíséretében ismételné meg, amit mondott.}
{177}{}{Személyem aligha meríti ki a fontos jelz?t, így hát most mennék... Viszlát!}
{178}{powr16_a}{Hát persze, bárki is legyél, elindítottam egy gépmadár-osztagot hozzád. Kívánom, hogy legyen egy jó napod...}
{179}{}{Azta, ha m?ködne a videó, látnád, hogy remegek.}
{180}{}{És mit fognak csinálni?}
{181}{}{Akkor jobb, ha mozdulok. Nem szeretném, ha a piros sz?nyeg kigurítása el?tt ideérnének. Na, csá...}
{182}{powr17}{Többnyire l?ni szoktak. Aztán kiküldenek valakit, hogy a megmaradt hamut átkutassa.}
{183}{}{Hát engem meg nem fognak, az biztos.}
{184}{}{Hát nagyon berezeltem. Asszem, alsónem?t kell cserélnem.}
{185}{}{Hát bizony zokon venném, ha a tegnapi napot hiába töltöttem volna fegyverpucolással.}
{186}{}{Hogyne-hogyne. Már jobbak ráfáztak, hogy velem találkoztak. Viszlát!}
{187}{powr18}{Akkor légy jó. A következ? hír, amit veled kapcsolatban olvasok, a halotti bizonyítvány lesz.}
{188}{}{Mit? Veszi az adást!}
{189}{}{Mi sem természetesebb ennél...}
{190}{}{Hé, felkerültél a listámra, azt tudod...}
{191}{powr19_a}{El kellett jönnie? Mire fel? A partvidéken vannak. Remek védelemmel a hátuk mögött. Én semmit nem hallottam err?l... Hé, tulajdonképpen ki a franccal beszélek?}
{192}{}{A hatalmas, isteni Willie vagyok. Térdepelj le el?ttem és áhítsd a megbocsátásom. Úgy talán megkegyelmezek.}
{193}{}{Nem vagyok fontos személyiség. Hol is van ez a Navarro?}
{194}{}{Nos, elfoglaltuk Navarrót és megtaláltuk a pucér fotókat a mamádról. Persze lehet, hogy az apád volt, csak rossz ruhát vett fel. Nem csoda, ha ilyen kibaszottul rusnya vagy. Viszlát, seggfej!}
{195}{powr20}{Mondd csak, mondd csak. Szorul a hurok itt az ENKLÁVÉNÁL és a kibaszott Elnök is úgy figyel ránk, mint a sas.}
{196}{}{Az Elnök?}
{197}{}{Úgymint itt? Hol vannak most pontosan?}
{198}{}{Hát ez már a dolgok természete. Most mennem kell dolgozni. Viszlát!}
