{100}{}{Egy teljes kémikus felszerelést látsz.}
{101}{}{Egy "Kis Kémikus" felszerelés.}
{102}{}{Egy "Kis Kémikus" készletet látsz, amivel érdekes kotyvalékokat lehet kikeverni.}
{103}{}{Mivel szeretnéd kezdeni? Négyféle folyadékod van kis fiolákban: piros, kék, sárga és áttetsz?.}
{104}{}{A pirossal.}
{105}{}{A kékkel.}
{106}{}{A sárgával.}
{107}{}{Az áttetsz?vel.}
{108}{}{Nem csinálok semmit.}
{109}{}{A pirosat választottad. Mit szeretnél hozzákeverni?}
{110}{}{Kéket. Így lila lesz.}
{111}{}{Sárgát. Így narancssárga lesz.}
{112}{}{Áttetsz?t. Így piros marad.}
{113}{}{Megiszom.}
{114}{}{Blue. This, you know, will make Jet, an addictive amphetamine-like drug... if you get the correct
 dosages.}
{115}{}{Sárgát. Tudós elméd felismeri, hogy ha jól kevered hozzá, sósav lesz bel?le.}
{116}{}{Áttetsz?t. Gyakorlott agyad tudja, hogy így er?s vitamin lesz bel?le... feltéve, ha ki tudod mérni a megfelel? arányt.}
{117}{}{Abbahagyom.}
{118}{}{A kéket választottad. Mit szeretnél hozzákeverni?}
{119}{}{Pirosat. Így lila lesz.}
{120}{}{Sárgát. Így zöld lesz..}
{121}{}{Áttetsz?t. Így kék marad.}
{122}{}{Red. This, you know, will make Jet, an addictive amphetamine-like drug... if you get the correct
 dosages.}
{123}{}{Sárgát. Miel?tt hozzákevernéd, fejben elvégzed a szükséges számításokat. Tudod jól, hogy nitroglicerin lesz bel?le, egy er?s robbanóanyag.}
{124}{}{Áttetsz?t. Így egy toxikus vegyületet kapsz, ami semmire nem jó a sugárzás hatásának tanulmányozásán kívül.}
{125}{}{Megiszom.}
{126}{}{Abbahagyom.}
{127}{}{A sárgát választottad. Mit szeretnél hozzákeverni?}
{128}{}{Kéket. Így zöld lesz.}
{129}{}{Pirosat. Így narancssárga lesz.}
{130}{}{Áttetsz?t. Így sárga marad.}
{131}{}{Megiszom.}
{132}{}{Kéket. Miel?tt hozzákevernéd, fejben elvégzed a szükséges számításokat. Tudod jól, hogy nitroglicerin lesz bel?le, egy er?s robbanóanyag.}
{133}{}{Pirosat. Tudós elméd felismeri, hogy ha jól kevered hozzá, sósav lesz bel?le.}
{134}{}{Áttetsz?t. Tudod, hogy ha így folytatod, egy gyenge méreg lesz az eredmény.}
{135}{}{Abbahagyom.}
{136}{}{Az áttetsz? folyadékot választottad. Mit szeretnél hozzákeverni?}
{137}{}{Kéket, hogy kék maradjon.}
{138}{}{Pirosat, hogy piros maradjon.}
{139}{}{Sárgát, hogy sárga maradjon.}
{140}{}{Megiszom.}
{141}{}{Sárgát. Tudod, hogy ha így folytatod, egy gyenge méreg lesz az eredmény.}
{142}{}{Kéket. Így egy toxikus vegyületet kapsz, ami semmire sem jó a sugárzás hatásának tanulmányozásán kívül.}
{143}{}{Pirosat. Gyakorlott agyad tudja, hogy így er?s vitamin lesz bel?le... feltéve, ha ki tudod mérni a megfelel? arányt.}
{144}{}{Abbahagyom.}
{145}{}{Sikerült létrehoznod egy érdekes, lila szín? kotyvalékot. Mit teszel vele?}
{146}{}{Megiszom.}
{147}{}{Elteszem a hátizsákomba.}
{148}{}{Hmmm. Különleges narancssárga színe lett. Mit teszel vele?}
{149}{}{Megiszom.}
{150}{}{Elteszem a hátizsákomba.}
{151}{}{Skarlátvörös szín. Mi legyen vele?}
{152}{}{Megiszom.}
{153}{}{Elteszem a hátizsákomba.}
{154}{}{Méregzöld szín az eredmény. Mi legyen vele?}
{155}{}{Megiszom.}
{156}{}{Elteszem.}
{157}{}{Furcsa kék árnyalat. Mit teszel vele?}
{158}{}{Megiszom.}
{159}{}{Elteszem kés?bbre.}
{160}{}{Ez a sárga úgy néz ki, mint a vizelet és borzasztó szaga van. Mit teszel vele?}
{161}{}{Megiszom.}
{162}{}{Elteszem. Még hasznos lehet.}
{163}{}{Ááh, édes siker! Létrehoztad a Jetet. New Renóban nagy népszer?ségre tehetnél szert ezzel. Mit teszel vele?}
{164}{}{Megiszom.}
{165}{}{Elteszem. Majd kés?bb hasznát vehetem...}
{166}{}{Hoppá! Valamiféle toxikus g?z fejl?dik! Egy szippantástól kifekszel. Nagyon szarul érzed magad.}
{167}{}{[DONE]}
{168}{}{Ez a szer hatásosnak t?nik. Mit teszel vele?}
{169}{}{Megiszom.}
{170}{}{Elteszem kés?bbre.}
{171}{}{Ó nem! Túl er?teljesen keverted! Átmarta az üveget és a kezedet is majdnem! Jaj!}
{172}{}{Sikeresen létrehoztál egy adag folyékony robbanóanyagot!}
{173}{}{Megiszom.}
{174}{}{Elteszem a hátizsákomba.}
{175}{}{Egy csepp ebb?l, egy csepp abból, és... ajjaj... BUMM!}
{176}{}{Ó, ne! Te marha! Lenyelted a robbanóanyagot!}
{177}{}{Kissé viccesen érzed magad. Nem, nagyon viccesen érzed magad. Tulajdonképpen úgy érzed, hogy felgyorsul a szíved, a külvilág pedig lelassul. Nem tudod, mi történik, és nem tudsz segítséget kérni, mert nem tudod, mi történik veled... jaj, ne, vigyázz! ÁÁÁÁÁÁH! TELJESEN KIPURCANSZ!!!}
{178}{}{Elfintorodsz az íze miatt, majd, ahogy halad lefelé, észreveszed, hogy éget a folyadék. Au! AU! AUUU!! Szétroncsolja a beleidet! }
{179}{}{Kicsit kesernyés, de leer?szakolod. Különös, de jobban érzed magad t?le.}
{180}{}{Ahh, what the hell. Despite the looks of it, you down the nasty brew. You immediately begin
 spitting and gagging. You've been irradiated!}
{181}{}{[DONE]}
{182}{}{Na, jó... rendben. Emlékezve arra, mi mindent ittál még kisgyermek korodban, lehúzod az üveg tartalmát. Amint leér a folyadék, a gyomrod összerándul. Úgy érzed magad, mintha épp most csípett volna meg egy radskorpió.}
{183}{}{Hé, ez pont olyan, mintha víz lenne, szóval legalább olyan jó is, nem? Amint lenyeled, érzed, hogy nagyot hibáztál. Ez ÉGET! Nagyon nagyon sokáig fáj.}
{184}{}{Egy kicsit ebb?l, egy kicsit abból... egy pillanat... miért füstöl az üveg... mit csináltam rosszul? Ó, NE! Az üveg az arcodba robban!}
{185}{}{Vidáman összekevered a löttyöket, remélve, hogy a megfelel? vegyi anyagokat választottad. Aztán leülsz és várod az eredményt. És vársz. És vársz. A folyadék átszínez?dik valami trutymós barnává. Mehet a szemétbe.}
{186}{}{Sikerült egy adag er?s vitamint létrehoznod. Mit teszel vele?}
{187}{}{Megiszom.}
{188}{}{Elteszem kés?bbre.}
{189}{}{Sikerült egy adag mérget létrehoznod! Rendben, és most?}
{190}{}{Megiszom.}
{191}{}{Elteszem kés?bbre.}
{192}{}{Sikeresen létrehoztál egy adag folyadékot, mely szimulálja a radioaktív mérgezés tüneteit. Mit teszel vele?}
{193}{}{Megiszom.}
{194}{}{Elteszem kés?bbre.}
