{100}{}{Egy aggódó embert látsz.}
{101}{}{Dan, az aggódó férj.}
{102}{}{Egy jólöltözött férfit látsz, akinek az arcvonásai küszöbön álló hisztériáról árulkodnak.}
{103}{}{Ki vagy te? Mit csinálsz a házamban?}
{104}{}{Akk? Úúp?}
{105}{}{A nevem }
{106}{}{Én? Senki.}
{107}{}{Azért jöttem, hogy kiraboljalak.}
{108}{}{Semmit. Senki. Viszlát!}
{109}{}{Ne az én házamban, kérlek! Ott az utca. Ott aludhatsz, vagy csinálhatsz bármit, amit a magadfajta különös emberek csinálnak.}
{110}{}{Thppt!}
{111}{}{Nagyszerű! Örülök, hogy találkoztunk. [Zavartan bámul] Hé, te... te amolyan kalandozó fajta vagy, nem?}
{112}{}{Igen.}
{113}{}{Nem ismered fel a Kiválasztottat?}
{114}{}{Nem.}
{115}{}{Mi közöd hozzá?}
{116}{}{Azért kérdeztem, mert amint láthatod, a feleségem eltűnt. Nem tudom, hol lehet. Több napja elveszett már. Körbekérdeztem a városban, de senki sem látta. Nem keresnéd meg?}
{117}{}{Mit ajánlasz cserébe?}
{118}{}{Körülnézek. Hogy néz ki a feleséged?}
{119}{}{Nem. Sok a dolgom.}
{120}{}{Van 500 dollárom. A spórolt pénzem.}
{121}{}{Annyi elég lesz. Megkeresem a feleséged.}
{122}{}{Sajnálom. Nem vállalom.}
{123}{}{Kérlek, kérlek! A feleségem... ő jelent mindent számomra. Kérlek!}
{124}{}{Azt mondtam, nem!}
{125}{}{Jól van! Jól van! Csak hagyj végre békén a sirámaiddal!}
{126}{}{Itt a pénz. Kérlek, kérlek, KÉRLEK... találd meg a feleségem! Talán összeállt valaki mással, talán elhagyott... de tudnom kell.}
{127}{}{Rendben, haver. Hogy néz ki?}
{128}{}{Rendicsek. Megteszem, amit tudok.}
{129}{}{::önkéntelenül szipog pár másodpercig:: Rendben. Menj csak! És vedd észre, hogy elvetted az utolsó reményemet is!}
{130}{}{Viszlát, vesztes!}
{131}{}{Szőke, szexi és csodálatos énekhangja van... utoljára errefelé látam őt. Nem szereti a mutánsokat és a ghoulokat, szóval nem hiszem, hogy közel lenne hozzájuk. Senki nem tudja, hova mehetett. Mintha egyszerűen eltűnt volna.}
{132}{}{Ennyi elég lesz..}
{133}{}{Nos? Megtaláltad? A szívem minden pillanatban sajog.}
{134}{}{Sajnálom, haver, még keresem.}
{135}{}{Igen, megtaláltam.}
{136}{}{Nem, még nem. Folytatom a keresést.}
{137}{}{Ó, a fájó szívem. Kérlek, azonnal szólj, ha megtaláltad!}
{138}{}{Persze, magától értetődik.}
{139}{}{Az igazat megvallva, nem akarom tovább keresni.}
{140}{}{Megtaláltad? ::egészen felvillanyozódik:: Hol?}
{141}{}{Ugye nem voltak lábai?}
{142}{}{Egy rakás holttestet találtam a város alatti alagutakban. Ott volt közöttük. Nagyon sajnálom.}
{143}{}{Mi? Nem! Szép hosszú lábai voltak!}
{144}{}{Óh. Értem. Hát, most már nincsenek szép hosszú lábai. Brutálisan megölték, a lábait pedig LEVÁGTÁK. Tökéletesen halott és sokat szenvedett a halála előtt.}
{145}{}{Értem. Azt hiszem, megtaláltam őt a város alatti alagútrendszerben. Meghalt. Nagyon sajnálom.}
{146}{}{Köszönöm, hogy elmondtad. Azt hiszem, megyek és sírok egyet...}
{147}{}{Ez az, menj csak bőgni, te szánalmas vesztes!}
{148}{}{Sajnálom, haver.}
{149}{}{Utállak! Mindenki utál! Dögölj meg! ::szipp::}
{150}{}{Találtam egy levelet a feleséged mellett. Kiderül belőle, hogy valószínűleg részese volt egy a Broken Hills mutánsai ellen irányuló összesküvésnek.}
{151}{}{Istenem! Nem... nem tudom elhinni... Ez nem... [Mélyet sóhajt]. Azt hiszem igaz, amit mondasz. Úgy tűnt, nem kedveli a mutánsokat és a ghoulokat. Sohasem tudtam, miért.}
{152}{}{Talán igaz, de akkor vigyáznod kell, hátha a gyilkosok nem állnak meg a feleségednél! Ha ő bűnrészes volt, te is lehetsz célpont.}
{153}{}{Csak nem gondolod, hogy én is veszélyben vagyok? Ó, jaj! Talán igazad van. Éjszakánként zajokat hallok odakintről. Suttogást és csoszogást.}
{154}{}{Azt hiszem, jobban tennéd, ha elmennél Broken Hillsből. Vigyázz magadra! Sok szerencsét!}
{155}{}{Köszönöm a segítséget. Nem maradok itt tovább!}
{156}{}{Értesítetted Dant a felesége haláláról.}
{157}{}{ dollár.}
