{100}{}{You see a greasy, sweating ghoul.}
{101}{}{Eric.}
{102}{}{You see a greasy, sweating ghoul. He looks quite miserable.}
{103}{}{Ennek a városnak nem kell több pech. Nekem sem kell több.}
{104}{}{Gyere már, gyere már! Csukd be gyorsan az ajtót! Bejönnek a legyek!}
{105}{}{Legyek mi?}
{106}{}{Oké, jól van. Nem kell kiabálni!}
{107}{}{Te kiabálsz velem?}
{108}{}{Annyi legyet engedek be, amennyit csak akarok. Seggfej!}
{109}{}{Aha. Na, légy jó!}
{110}{}{Csukd be az ajtót! Kérlek! Menj és vidd magaddal a legyeket is!}
{111}{}{Okké!}
{112}{}{Bocs. Kicsit ideges vagyok. Itt ez a sok légy, és nem m?ködik a légkondicionáló. Ha több áramot kapnék, nem lenne gond velük... de nem kapok.}
{113}{}{Ki vagy te?}
{114}{}{Honnan kapsz áramot?}
{115}{}{Miért jönnek a legyek ide?}
{116}{}{Fürdened kéne inkább, nem gondolod?}
{117}{}{Peched van, haver. Na, viszlát!}
{118}{}{Hmmm. Szar ügy. Viszlát!}
{119}{}{A belvárosban van egy generátorállomás, ami ellátja a várost árammal. Ha elmennél oda, és kérnél nekem még egy kis áramot a légkondicionálómhoz, hálás lennék.}
{120}{}{Mennyire hálás? Pénz vagy felszerelés?}
{121}{}{Oké, megpróbálom.}
{122}{}{Nincs rá id?m. Talán kés?bb.}
{123}{}{Te hülye vagy? Nem. Olyan szánalmas vagy, hogy szívességet tennél a világnak, ha meghalnál!}
{124}{}{Azért, mert valami furcsa oknál fogva légytápanyagot izzadok. A testem kaját jelent nekik, és ez az izzadás csak ront a helyzetemen.}
{125}{}{Ez elég szar lehet. Miért nem fürdesz, vagy valami?}
{126}{}{Akkor szívességet teszek, ha megöllek.}
{127}{}{Értem. Ez több, mint amit tudni akartam. Viszlát!}
{128}{}{Próbáltam. Mindent próbáltam már. Az egyetlen dolog, ami távoltartaná a legyeket, ha nem izzadnék... de ha nincs elég áram, soha nem lesz itt h?vös.}
{129}{}{Értem. Volna még néhány kérdésem.}
{130}{}{Értem. Viszlát!}
{131}{}{Igen?}
{132}{}{Beszéltem Briannel, és azt mondta, hogy a sz?kös készletekre való tekintettel nem adhat több áramot.}
{133}{}{Miért jönnek ide a legyek?}
{134}{}{Próbáltál már fürdeni?}
{135}{}{Hol van a generátorállomás?}
{136}{}{Ki vagy te?}
{137}{}{Most már sokkal jobb. Megfelel?}
{138}{}{Semmi. Hagyjuk!}
{139}{}{Össze tudok neked kaparni egy-két dolgot, ha megcsinálod. Nem ígérhetek sokat, de hát ez nem is olyan nagy kérés.}
{140}{}{Megegyeztünk. Csak legyen valami, amit elvihetek, ha visszajövök a jó hírrel!}
{141}{}{Megcsinálom ingyen. Nem kell semmi.}
{142}{}{Hagyjuk! Nem akarom megcsinálni.}
{143}{}{Gondolkozom rajta.}
{144}{}{El sem tudom mondani, milyen hálás vagyok! Kérlek, azonnal szólj, ha sikerült, hogy rögtön bekapcsolhassam a légkondicionálót és fürödhessek egyet!}
{145}{}{Persze, de lenne még pár kérdésem.}
{146}{}{Tiszta sor. Viszlát!}
{147}{}{Kérlek, ne halaszd sokára... kezdek meg?rülni ezekt?l a pimasz legyekt?l!}
{148}{}{Oké, csak lenne még pár kérdésem.}
{149}{}{Rendben.}
{150}{}{Kösz az együttérzést! Ez szarkazmus volt, ha nem vetted volna észre. T?nj a pokolba a házamból!}
{151}{}{Miért nem döglesz meg és mész te a pokolba?}
{152}{}{Viszlát, légyetet?!}
{153}{}{Az er?m? rögtön a bal kezed felé van, amikor belépsz Broken Hillsbe. Egy Brian nev? fickó üzemelteti. Amolyan naplopó, aki igyekszik minél kevesebbet dolgozni.}
{154}{}{Frankó munka lehet. Kösz. Lenne még pár kérdésem.}
{155}{}{Értem. Akkor megyek is.}
{156}{}{Eric vagyok. Én vezettem a város hoteljét, de el kellett adnom a légy-problémám miatt. A kocsmát is én vezettem, de azt is el kellett adnom, ugyanazért. A generátort is én felügyeltem, de a legyek folyton belerepültek.}
{157}{}{Ez szörnyen sok munka. Lenne még pár kérdésem.}
{158}{}{Értem. Viszlát!}
{159}{}{Azt mondta? Akkor mondd meg neki, hogy a generátor uránnal üzemel, és az a minimális energiatöbblet, amit kérek meg sem kottyanna a generátornak. És mondd meg neki azt is, hogy az áramomat akarom!}
{160}{}{Úgy lesz! Ez a beszéd!}
{161}{}{Megmondom neki, de el?bb kérdeznék valamit.}
{162}{}{Oké. Viszlát!}
{163}{}{Sikerült? Nagyon köszönöm. El sem tudom mondani, milyen hálás vagyok.}
{164}{}{A hála kifejezésének elterjedt módja a pénz, vagy más használható tárgy ajándékozása.}
{165}{}{Ne legyél. Beérem a köszöneteddel.}
{166}{}{Francisnak, a mutánsnak er?keszty?je van. Mindenkit kihív szkanderezni, és mindenkit le is gy?z. A gond az, hogy er?sebb mindenkinél. Ha érdekel, tudok adni pár pirulát, amivel legy?zheted.}
{167}{}{Hogyne.}
{168}{}{Inkább pénzt kérnék, ha van.}
{169}{}{Nem kell jutalom.}
{170}{}{Ezt a drogot Buffoutnak hívják. Megnöveli az er?t, de elködösíti az agyat. Ne vegyél be túl sokat egyszerre, mert függ?vé válhatsz! Sok sikert!}
{171}{}{Kösz! Viszlát!}
{172}{}{Tudnál segíteni a légy-problémámon? Nagyon hálás lennék.}
{173}{}{Mennyire hálás?}
{174}{}{Hogyne.}
{175}{}{Gondolkozom rajta.}
{176}{}{Nem érdekel.}
{177}{}{Itt az összes pénzem... 150 dollár. Köszönöm!}
{178}{}{Nem, én köszönöm. Viszlát!}
{179}{}{Akkor kétszeresen is hálás vagyok. Ó... úgy hallottam, egy ÉLET-et keresel. Nézz körül az ÚKK-ban, innen délre!}
{180}{}{Kösz! Viszlát!}
{181}{}{Nagyon is. A legyek megfogyatkoztak, a leveg? h?vös, és nem izzadok annyit. Mindenkinek jobb így a környéken!}
{182}{}{Rendben. Hát ez minden. Viszlát!}
{183}{}{Egy kövér, kevésbé izzadó embert látsz. Láthatóan jól érzi magát.}
