{100}{}{Egy embert látsz, aki egy szép, nagy fegyvert szorongat a kezében.}
{101}{}{A Broken Hillsi keresked? és ?rz? testület egyik tagját látod.}
{102}{}{Egy embert látsz, akit az út pora borít. Szép nagy fegyvert tart a kezében.}
{103}{}{Én mondom, még egy csapat útonálló, és legközelebb dinamitot is viszek magammal!}
{104}{}{Hasznát látnánk egy kis segítségnek a karavánoknál.}
{105}{}{Haver... az "Összefogás" ?rjárat kezd nagyon, nagyon kiöregedni.}
{106}{}{Szóval akkor jött az a törzsbéli, mire én... ööö, hagyjuk.}
{107}{}{Még egy "Szivárvány ?rjárat" seggség, és valakit biztosan kinyírok!}
{108}{}{Ha az útonálók bekeményítenek, jöv?re mind meghalunk, az tuti.}
{109}{}{Milyen faluból jössz?}
{110}{}{Nem vennél egy kis piát egy dolgozó embernek?}
{111}{}{Túlságosan kifáraszt a karavánmunka, hogy még beszélgessek is.}
{112}{}{Ha kell valami, beszélj Billel, a karavánok szervez?jével!}
{113}{}{Talán ennyi id? után, amit a puszta civilizálásával töltöttünk, közelebb kerültünk a célunkhoz.}
{114}{}{Elegem van ebb?l az ember-mutáns veszekedésb?l. Nem éppen nekünk kellene példát mutatnunk?}
{115}{}{Mit akarsz? Nem látod, hogy pihenek?}
{116}{}{Mikor indul a következ? karaván?}
{117}{}{Jár?rözni, jár?rözni, jár?rözni... mindig ugyanaz a meló.}
{118}{}{Kezdek álmos lenni.}
{119}{}{Fizetésemelést követelek! Ez veszélyes munkakör.}
{200}{}{Segíthetek?}
{201}{}{Igen, a karavánmestert keresem.}
{202}{}{Chadról szeretnék kérdezni pár dolgot.}
{203}{}{Ki vagy te?}
{204}{}{Nem, kösz.}
{205}{}{In that case, you wanna talk to Bill, the Outfitter of Broken Hills. He is inside that building over there.}
{206}{}{Lenne még kérdésem.}
{207}{}{Kösz. Viszlát!}
{208}{}{Talán tudok válaszolni. Mit akarsz tudni?}
{209}{}{Milyen ember?}
{210}{}{Megbízható?}
{211}{}{Honnan szerzi a pénzt?}
{212}{}{Milyen a múltja?}
{213}{}{Hagyjuk. Viszlát kés?bb!}
{214}{}{Hogy én? }
{215}{}{. Bill karavánjait kísérem. Más kérdés?}
{216}{}{Hogy milyen ember? Hát, barátságos, de kemény. Jó vezet?, és általában rendesen bánik velünk Nem durvul velünk, meg ilyesmi, ha arra vagy kiváncsi. Van még kérdés?}
{217}{}{Hát, egy kicsit gyanús, szerintem... de mindenki az manapság. Van még kérdésed?}
{218}{}{Nekem mindig úgy t?nt, hogy egyszer?en van nála - és nem kevés. Ez nem az a fajta kérdés, amit csak úgy feltesz az ember valakinek, tudod. Egyéb kérdés?}
{219}{}{Semmit nem tudok a múltjáról. Mi mind más városból jöttünk, hogy munkát szerezzünk itt, mint karavánkísér?. Gondolom, neki is siet?sen el kellett hagynia egy másik helyet, és így került ide. Egyéb kérdés?}
{220}{}{Igen.}
{221}{}{Nem.}
{222}{}{Rendben. Lássuk csak!}
{223}{}{Viszlát!}
{300}{}{Hatch}
{301}{}{Stark}
{302}{}{Darin}
{303}{}{Michael}
{304}{}{Harry}
{305}{}{Jake}
{306}{}{Matt}
{307}{}{Ted}
{308}{}{Clay}
{309}{}{Scott}
{310}{}{Prentiss}
{311}{}{Eddie}
{312}{}{John}
{313}{}{Max}
{400}{}{Tawni}
{401}{}{Kim}
{402}{}{Urs}
{403}{}{Susan}
{404}{}{Cindy}
{405}{}{Jen}
{406}{}{Lisa}
{407}{}{Buffy}
{408}{}{Heather}
{409}{}{Cathy}
{410}{}{Lori}
{411}{}{Mary}
{412}{}{Julie}
{413}{}{Sarah}
{450}{}{? }
{451}{}{, a karavánkísér?.}
{2050}{}{In that case, you wanna talk to Bill, the Outfitter of Broken Hills. He's the one wearing a hat, right over there.}
