{100}{}{Egy ghoult látsz. Épp az els? lökhárítód alatt fekszik.}
{101}{}{Lumpyt látod. Reméled, hogy nincs semmi baja.}
{102}{}{Egy ghoult látsz, akinek, úgy t?nik, er?s fájdalmai vannak. Talán ha jobban tudnál vezetni, elkerülhetted volna ezt.}
{103}{}{Oooooh! De fáj!}
{104}{}{Jaj! A gyomrom!}
{105}{}{Nem látta valaki az epehólyagomat?}
{106}{}{A gerincem! A gerincem!}
{107}{}{Hamarosan találkozunk, Elizabeth!}
{108}{}{Orvost...}
{109}{}{Nem akar valaki segíteni? Nem tudom elolvasni a rendszámot.}
{110}{}{Hé, haver!}
{111}{}{Hé, kölyök!}
{112}{}{A nevem Lumpy. Nem segítenél ki innen?}
{113}{}{Ajjaj! Te jól lenni, Lumpy?}
{114}{}{Istenem! Jól vagy, Lumpy?}
{115}{}{Hopplá...}
{116}{}{Óh, semmi gond. Eltekintve a többszöri csonttörést?l és az orrdíszt?l, ami jó magasra felcsúszott a seggembe, jól vagyok.}
{117}{}{Ohhh. Kell segítsegg?}
{118}{}{Tuti. Pá-pá.}
{119}{}{Jól van, nyugodj meg! Kell segítség?}
{120}{}{Hála istennek! Azt hittem, valami komoly bajod esett. Hát akkor, viszlát kés?bb!}
{121}{}{[Lumpy csendesen a szemedbe néz. Pislant egyet. Majd még egyet.]}
{122}{}{Uhhh... hüjje kéédés. Ugyi?}
{123}{}{Ezt igennek veszem.}
{124}{}{Rohadtul úgy van! Mozdulni sem tudok! Ne félj, nem panaszkodok! Voltak már durvább sérüléseim is. Ez össze sem hasonlítható azzal, amikor pár évvel ezel?tt a kólás kamion ment át rajtam. Látnod kellett volna, kölyök! Kupakok mindenütt!}
{125}{}{Áááááh. Vicces!}
{126}{}{Nahát! Képzeld el, ha valaki rátalál a sivatagban! Hogy meggazdagodott volna!}
{127}{}{Ahogy mondod. Arrh! Aúú! Kár, hogy véget kell vetnem ennek a sziporkázó beszélgetésnek, de ha segítenél kimászni a lökhárító alól, leköteleznél vele.}
{128}{}{Szabad lenni?}
{129}{}{Biztos vagy benne? Talán jobb lenne, ha nem mozdulnál!}
{130}{}{Á, ne aggódj! El?bb-utóbb mindenem vissza fog ugrani a helyére.}
{131}{}{Okké. Kész?}
{132}{}{Rendben. Kész vagy?}
{133}{}{Igen... hopplá! Hol a pokolban tanultál meg így vezetni?}
{134}{}{Énmagamtó'.}
{135}{}{Hát, ami azt illeti, önképz? vagyok.}
{136}{}{Látszik, ha engem kérdezel.}
{137}{}{Oh. Te Oké?}
{138}{}{Óh... nos... hmmmm. Minden... rendben?}
{139}{}{Én mondtam nekik, hogy közlekedési táblák kellenének, de figyeltek rám? Neeem... Ne is figyeljetek a vén Lumpyra!}
{200}{}{Ó, basszus!}
{201}{}{Uh, oh. Me hit smelly man.}
