{100}{}{Egy mutánst látsz koszos ruhában. Kezében csákányt tart.}
{101}{}{Egy mutáns bányász.}
{102}{}{Egy mutánst látsz koszos ruhában. Kezében jókora csákány. A tenyerén lév? b?rkeményedésekb?l és a fáradt ábrázatából arra következtetsz, hogy egy bányászhoz van szerencséd. Fáradtnak és zavarodottnak t?nik.}
{103}{}{Mit akarsz?}
{104}{}{Ag-ag! Úúú!}
{105}{}{Ork! Úkí!}
{106}{}{Dallo?}
{107}{}{Dallo!}
{108}{}{Mit lehet itt csinálni?}
{109}{}{Ki vagy te?}
{110}{}{Óh, szuper. Egy hülyegyerek. Kaptál egy kis sugárzást mi, haver? Nem értelek, szóval nem tudok segíteni se.}
{111}{}{Mondtam, hogy nem tudok segíteni. Menj, idétlenkedj valaki másnak!}
{112}{}{What's there to do? Well, the mine's shut down because we haven't got an air purifier that
 works. There's the saloon. There's the caravaneers, and there's the general store. That's about it.
 Wait... what were we talking about?}
{113}{}{Kivel beszélhetek a bányáról?}
{114}{}{Merre van az a kocsma?}
{115}{}{Hol vannak a karavánosok?}
{116}{}{Hol találom a boltot?}
{117}{}{Kösz. Viszlát!}
{118}{}{Just one of the miners. Do you want someone important?}
{119}{}{Igen.}
{120}{}{Nem.}
{121}{}{Viszlát!}
{122}{}{Hát, a város irányítói Marcus, aki afféle seriff és polgármester egy személyben, Zaius, aki a bánya munkavezet?je és Chad, aki a karavánokat felügyeli. Phil, a kocsmáros, pedig a ghoulok vezet?je, asszem... ha egyáltalán van vezet?jük. Ki is vagy te?}
{123}{}{Hol találom Marcust?}
{124}{}{Hol találom Zaiust?}
{125}{}{Hol találom Cameront?}
{126}{}{Merre van Chad?}
{127}{}{Merre van Phil?}
{128}{}{Kösz. Viszlát!}
{129}{}{Ha úgy gondolod, hogy tudnál segíteni a bányánál, akkor beszélj Zaiusszal! Többnyire a munkavezet? házában van a bánya mellett. Elég rosszkedv?, mert elromlott a bánya légtisztítója. Van más kérdésed?}
{130}{}{Phil, a ghoul, vezeti a kocsmát. ? amolyan szószólója a városi ghouloknak. Megtalálhatod a banktól keletre. Kiváncsi vagy még valamire?}
{131}{}{Chad irányítja a karavánokat a város dél-nyugati részén. Más kérdés?}
{132}{}{Liz elég rendes, ember létére, ? vezeti a vegyesboltot a banktól nyugatra. Egyéb kérdés?}
{133}{}{Rendben. Viszlát!}
{134}{}{Cameron a normális emberek vezet?je. Nem szereti túlzottan a mutánsokat és a ghoulokat, de rendesen bánik velünk. ? amolyan politikus, szóval vagy a bankban van, vagy a kocsmában. Néha a kovácsm?helyben dolgozik. Más kérdés? Amúgy hol tartottam? Ja igen... szóval... van még kérdésed?}
{135}{}{Marcus is our leader. He helped found Broken Hills. You can usually find him at the bank or
 the jail. Anything else?}
{136}{}{Kapzsi gané! Tudod, milyen keményen dolgozunk? Rohadj meg!}
{137}{}{Kösz az ércet!}
{138}{}{Nem hiszem el, hogy felrobbant a bánya. Mind éhen fogunk dögleni! A bánya tartotta fent a várost. Hmm, legalább nem kell többet dolgoznom...}
{139}{}{Megdöglesz, te gané!}
{140}{}{Kösz, hogy helyrehoztad a bányát. Soha nem felejtjük el. Mit tehetek érted?}
{141}{}{Ki vagy te?}
{142}{}{Mit lehet ebben a városban csinálni?}
{143}{}{Semmi.}
{144}{}{Jövünk neked eggyel, amiért megmentettél minket azoktól az ÚKK-s mocskoktól. Kösz, haver! Tehetek érted valamit?}
{145}{}{Ki vagy te?}
{146}{}{Mit lehet ebben a városban csinálni?}
{147}{}{Semmi.}
