{100}{}{Egy összeaszott ghoult látsz.}
{101}{}{Egy öreg ghoult látsz azon néhány közül, akik otthonuknak nevezik ezt a házat.}
{102}{}{Olyan fáradt vagyok...}
{103}{}{Belefáradtam. Belefáradtam a várakozásba, belefáradtam, hogy várjak r-áá-d.}
{104}{}{Mikor kell lefeküdnöm?}
{105}{}{Mi ez a borzalmas b?z? Ja, csak én.}
{106}{}{Nincs még 4 óra? Vacsorát akarok!}
{107}{}{Ez igen, már majdnem egy órája nem ficamítottam ki a csíp?met!}
{108}{}{Nem látta valaki a fogamat?}
{109}{}{Hol a kajám?}
{110}{}{Halál! Engem akarsz? Itt vagyok!}
{111}{}{Helló, Billy! Úgy örülök, hogy visszajöttél meglátogatni.}
{112}{}{A megöregedés nem puhányoknak való.}
{113}{}{Hoppáré! A beleim!}
{114}{}{Van valakinél egy pelenka?}
{115}{}{Olyan sok bölcsességet szedtem össze, mégsem örülök neki.}
{116}{}{Ghoulok manapság... ugyan!}
{117}{}{Semmi tisztelet... Senkit nem tisztelnek ma már.}
{118}{}{Emlékszem még a jó öreg Setre...}
{119}{}{Hogy juthatott el az öreg Jed Gekkóba?}
{120}{}{Szereted a mutikat? Én szeretem ?ket.}
{121}{}{Imádom a krumplit! Szeretem törve! Szeretem sütve!}
{122}{}{Éhes vagyok!}
{123}{}{Bárcsak lenne pár növény idebenn.}
{124}{}{Nem szeretek kint lenni.}
{125}{}{Ez az öreg uránbánya is hamarosan kimerül.}
{126}{}{Te nem Menedékvárosból vagy, ugye?}
{127}{}{Emlékszem még, amikor a "Fényl?k" ellen küzdöttünk Necropolis alatt... azok voltak a szép napok...}
{128}{}{Hadd meséljek neked arról, amikor kinyitottuk a Menedéket...}
{129}{}{...mit is kezdtem el mondani?}
{130}{}{::ásít::}
{131}{}{::pffffft::}
{132}{}{Nincs semmi mondandóm senkinek!}
{133}{}{Szundikálni szeretnék.}
{134}{}{Hideg van és farkasok vannak a nyomomban.}
{135}{}{A kutyák még órákig tudják csóválni a farkukat a haláluk után!}
