{101}{}{You see an average person, of average height, of average complexion. Nothing out of the ordinary.}
{102}{}{You see Jo.}
{103}{}{You see Trader Jo.}
{104}{}{You see Sheriff Jo.}
{105}{}{You see Mayor Jo.}
{106}{}{You see Justice of the Peace Jo.}
{150}{}{Mindenkit megöltünk. Még a gyerekeket is... [zokog]}
{151}{}{Találkozzunk a Kísértetfarmon! Azonnal támadunk.}
{152}{}{Köszönöm, hogy megmentette Modoc lakosságát.}
{153}{}{Mit csinálsz te ott?}
{154}{}{Hé! Hagyja azt békén!}
{155}{}{Tolvaj!}
{156}{}{Sajnálom, az aszály miatt zárva tartjuk a kereskedést.}
{157}{}{Ki mondta, hogy vásárolni akarok?}
{158}{}{Új vagyok errefelé. Mit érdemes tudni erről a helyről?}
{159}{}{Ugye nem is remélhetem, hogy van egy eladó aranyórája?}
{160}{}{ÉLET!}
{161}{}{Segíthetek valamiben?}
{162}{}{Egy bizonyos dolgot keresek. Azon törtem a fejem, vajon tudna-e nekem segíteni a felkutatásában.}
{164}{}{Szeretnék venni egy aranyórát. Nem tudja, honnan szerezhetnék egyet?}
{165}{}{Mit tudsz felajánlani?}
{166}{}{Mit tudsz mesélni nekem erről a városról?}
{167}{}{Mit csinálsz itt?}
{168}{}{ÉLET!}
{169}{}{Visszajött hát! Mit talált a farmon?}
{170}{}{Megoldottam a Kísértetfarm problémáját. Bármikor odamehet és beköltözhet.}
{171}{}{Üzenetet hoztam magának az Aljanéptől.}
{172}{}{Üzze-neth.}
{173}{}{Farm?}
{174}{}{Rossz dolgok mind eltűntenek!}
{175}{}{Menek.}
{176}{}{Ha többről tudok beszámolni, megint beszélünk.}
{179}{}{Van egy részeges fazon Rejtekben, akire ráillik a leírás. Aszongya, ő is termelő volt.}
{180}{}{Azok a testek nem igaziak. Leraktak valami bábukat és Brahminbeleket szórtak szét rajtuk. Csak azért vannak, hogy elriassza magukat a földekről.}
{181}{}{Mit is kéne tehát csinálnom?}
{182}{}{Hogy mondja? Ja, nyilván újnak tetszik itt lenni. Üdv Modocban. A nevem Jo, és enyém a modoc-i kereskedés.}
{183}{}{Küldetésben járok a szent ÉLET nyomában. Van ötlete, hol találhatnám meg?}
{186}{}{Maga aztán szerencsés. Mit tesz isten, tudom, hol van és közben egy kis üzletet is nyélbe üthetnénk.}
{187}{}{Üzletet? Csak mondja meg, hol van a szent ÉLET és már itt sem vagyok.}
{188}{}{Nekünk csak egyetlen üzletet kell összehoznunk. Mielőtt morcos leszek, maga szépen elmondja, hol van a szent ÉLET.}
{189}{}{Mit akar ezért az információért?}
{190}{}{Na, igen, nézzük, mit is akarok... Ha még nem vette volna észre, a mi kis termelő közösségünk a lehető legrosszabb aszályt fogta ki idén. Az esős évszak szokatlanul rövid volt és a vízhiány következtében a termés egyszerűen elhal. Röviden, kis településünk lassan feléli a tartalékait.}
{191}{}{Hmm... Gondolom tisztában van azzal, hogy nem tudok esőt csinálni...}
{192}{}{[Halkan kuncog...] Persze, persze... hogy is tudna. Lehetetlent sosem kérnék. Esőt csinálni nyilván nem tud, így van? Hát persze, hogy nem... Viszont ahogy azt mán említettem, bajban vagyunk, és elkelne a maga segítsége.}
{193}{}{Rendben, hallgatom.}
{194}{}{A város határában van egy farm, ahol nem kéne lennie neki. Néhány évvel ezelőtt a semmiből "tűnt" elő.}
{195}{}{Azt állítja, hogy az egyik éjszaka a semmiből előugrott? Hát persze, így megy ez!}
{196}{}{Néhányan éppen vadászni voltunk, amikor észrevettük az új farmot. De nem ez az érdekes, hanem, hogy röviddel ezután együtt ellátogattunk az új szomszédhoz, és azt kellett látnunk, hogy nem él ott senki.}
{197}{}{Folytassa, kérem!}
{198}{}{Miután hónapokig próbálkoztunk, hogy a pórul járt tulajdonosokkal felvegyük a kapcsolatot, arra jutottunk, hogy a farmot közvetlenül a megépítése után elhagyták. Ezért aztán ahelyett, hogy hagytuk volna a termést megrohadni a mezőn, Karl fiú beköltözött.}
{199}{}{Hmm... }
{200}{}{Na, ekkor fordultak rosszra a dolgok. Karl pletykákat kezdett terjeszteni, hogy éjszakánként fura, izzó alakok dolgoznak a földeken és etetik az állatokat. Mindannyian nevettünk rajta, azt hittük csak a fejéből pattant ki a sok sületlenség. Aztán egy nap Karl nem jött többé a városba.}
{201}{}{Mi történt vele? Nekiálltak keresni őt?}
{202}{}{Persze, hogy nekiálltunk. Amint neszét vettük, hogy valami nem stimmel, rögtön odamentünk. [Erősen remegni kezd.] Szörnyűség! Testek hevertek mindenütt. Némelyeket keresztrefeszítettek, másokat kinnhagytak rohadni a napon. Az akkor látott szörnyűségek hatására még ma is felriadok álmomból.}
{203}{}{Na, hadd találjam ki. Azt akarja, hogy menjek el arra a farmra, és nézzek utána, mi történt.}
{204}{}{Más esetben otthagytam volna azt az átkozott helyet, de valami oknál fogva a termény az aszály ellenére is rendben megterem ott. Ha nem jutunk élelemhez, éhen fogunk halni. Segít nekünk kitakarítani a szellemeket a farmról?}
{205}{}{Mire számíthatok, ha igen?}
{206}{}{A segítségért cserébe elmondom, merre találhatja, amit keres.}
{207}{}{Akkor pecsételjük meg gyorsan az üzletet. Vágja le a jobb kisujját!}
{208}{}{Akkor üssük nyélbe azonnal! Mutassa meg, hol van ez a Kísértetfarm.}
{209}{}{Micsoda?! Maguknál így szokás egy üzletet megpecsételni? Hát... az a helyzet, hogy a helyzet komoly, és maga az egyetlen, aki a végére tud járni ennek. Végül is ez nem nagy áldozat, ha megmentheti vele a városunkat. [Jo előhúz egy kést, és nekiáll lemetszeni a jobb kisujját!]}
{210}{}{[Időben megállítod.] Álljon már meg! Látom, hogy tényleg az igazat beszéli, és tényleg segítségre van szüksége. Segítek.}
{211}{}{Most pedig dinsztelje meg az ujját enyhén fokhagymás lében. Nagyon ízletes!}
{212}{}{Ez a farm kábé egy napi járóföldre van innen. [Előhúz egy térképet, és egy Modoctól észak-kelet felé eső pontra mutat]. Jöjjön vissza, ha talál valamit.}
{213}{}{[Jo teljes nyugalommal bekötözi a kezét, aztán előhúz egy vadászpuskát!] Na, nézzük, ehhez mit szólsz, kisköcsög!}
{214}{}{[BUMM!]}
{215}{}{Maga viccel! Eszemben nincs levágni az ujjamat. Elszánt ugyan vagyok, de hülye nem. Most akkor akarja a munkát, vagy sem?}
{216}{}{Rendben, megcsinálom. Hol van az a farm?}
{217}{}{Szemmel láthatóan nem elég elszánt. Passzolom a témát.}
{218}{}{Micsoda? Aszontad ÉLET?}
{219}{}{Ööö... ÉLET.}
{220}{}{Megyek.}
{222}{}{A nevem Jo. Ki tudod mondani? Na, nem számít. Látod azt a négyzet alakú valamit? Az ott az ajtó. Vigyázz meg ne üsd magad, mikor kimész.}
{223}{}{[Nem értesz mindent, amit mond, de elvigyorodsz és sarkon fordulva otthagyod.]}
{224}{}{[Egy röpke pillanatig eltűnődik valamin, aztán elmosolyodik és rádnéz.] Talán kinéz valami üzlet is. A nevem Jo. Enyém ez a kereskedés. Tudok ezt-azt az ÉLET-ről. Érdekli?}
{225}{}{[Bólogatsz.]}
{226}{}{[Ingatod a fejed.]}
{227}{}{Fantasztikus! Nos tehát, van egy Kísértet... ööö... egy farm a város peremén. Nagyjából egy nap járás észak-kelet felé. Csúnya dolgok történnek arrafelé. Szüntesd meg a rossz dolgokat, aztán gyere vissza, és mesélek az ÉLET-ről.}
{228}{}{Menek.}
{229}{}{Rendben, akkor nincs miről beszélnünk. Az ajtót ott találja.}
{230}{}{Látta már azt a nagy hólyagot a nyakán. Miért nem jön vissza, ha már összébbment? Na, szép napot, és vigyázzon az ajtóra kifelé menet.}
{231}{}{Akkor hát... üdvözöljük Modocban. Jo-nak hívnak és enyém az itteni kereskedés. Nincs itt sok látnivaló. csak néhány tanya, egy mészárszék, Rose panziója, és a cserzőműhely. Épp elég, hogy csereárut állítsunk elő. Sajna az aszály keresztbetehet.}
{232}{}{Mit tudsz mondani a mészárszékről?}
{233}{}{Rose panziója?}
{234}{}{Mondjon valamit a kereskedésről!}
{235}{}{Hol van a cserzőműhely?}
{236}{}{Feltehetek néhány további kérdést?}
{237}{}{A mészárszéket Grisham és a fia vezeti. Kelet felé megtalálja. Az egész Sziklás hegységben ő csinálja a legremekebb szárított húst.}
{242}{}{Rose panziója a város északi felében van. Messze földről érkeznek utazók, hogy kipróbálják a világhírű omlettjét. Egyesek szerint az az omlett még a betegeket is meggyógyítja. Őszintén szólva ez elég nagy marhaság.}
{247}{}{Just follow your nose and you'll find it. Can you smell that foul stench in the air? That's the
 tanning vats just north of here. If you overlook the smell, you'll not find a better place to get
 leather goods. Balthas can work miracles with leather.}
{252}{}{Ahogy azt már korábban említettem, Jo-nak hívnak, és enyém a modoci kereskedés. Én szervezem az árucserét Modoc és az élelmiszert meg bőrárut igénylő városok között. Nagy baj viszont, hogy az aszály hamarosan mindent gallyra tesz. Már a legrosszabbra is felkészültünk.}
{257}{}{Miről beszéljek? A mészárszékről, Rose panziójáról, a cserzőműhelyről vagy a kereskedésről?}
{262}{}{Na, köpje már ki! Nem tudok segíteni, ha nem mondja el, mit keres, és az hótt biztos, hogy nem fogok itt órákat állni, hogy kivárjam, amíg eldönti.}
{263}{}{A szent ÉLET után kutatok.}
{264}{}{Rá se ránts!}
{265}{}{Mivel meglehetősen függünk a Modocban gyártott termékektől, nem sok csereárum van. Tudja, az aszály, meg minden. Azért érdekli valami?}
{266}{}{Nézzük, miből élünk.}
{267}{}{Kösz nem, viszont kérdeznék egy s mást.}
{268}{}{Nem, talán később. Most mennem kell.}
{269}{}{Ez jó kérdés. Az időmet leginkább a kereskedés tölti ki. Esetenként azonban én vagyok a seriff, a polgármester, a bíró, és bármilyen létező hivatali személy.}
{270}{}{Ez igen! Nagyon népszerű lehet, ha ilyen sok tisztséggel megbízzák.}
{271}{}{Kösz az információért. Most mennem kéne.}
{272}{}{Fenéket, jól megszívattak. Éppen beszerzőúton voltam, amikor visszajövet láttam, hogy a népek időközben engem választottak meg. Senki más nem akarta elvállalni a munkát. Az időnkénti vitákat leszámítva nem sok dolgom akad, és ez eléggé fekszik nekem.}
{273}{}{Feltehetek még néhány kérdést?}
{274}{}{Micsoda? Ne okoskodjon itt! Mindenki tudja, hogy az öreg Corni elvesztette az aranyóráját. Még a legjobb barátom házát is átkutattatta velem. Ha jót akar, ne üsse ebbe bele az orrát. Jónapot!}
{275}{}{[Átveszi az Aljanép üzenetét.] Ez mi a rosseb? A Kísértetfarm lakóitól jött. Hát ezt nem hiszem el! Olvastad ezt a... ööö, hát hogy is olvastad volna, nem igaz? Szóval van még ez az, amit el kéne simítani az Aljanép és Modoc között, de az apró agyadnak ez túl bonyolult, szóval nem kell aggódnod emiatt.}
{276}{}{ÉLET most!}
{277}{}{Hát ez egy kis nehézségbe ütközik. Nem igazán tudom, mi az az ÉLET, viszont van egy GEKKÓ nevű település, ahol ugyan még sosem voltam, de úgy tudom, kelet felé van. Ott lehet, hogy segítenek. Nem akarlak átverni. Bárcsak többet ajánlhatnék cserébe, de az egyetlen dolog, amit adhatok, az árengedmény. Nem sok árum van, de biztos vagyok, hogy a dolgok hamar rendbe jönnek, és megtisztelve fogom magam érezni, ha felszerelhetlek.}
{278}{}{Marharépa!}
{280}{}{Nem rovom fel magának, hogy ki van bukva rám, de nem sajnálom, amit tettem. Szükségünk volt valakire a munkához, és maga vállalkozott. Nem tudok mást mondani, mint köszönet érte, de most útjára engedem.}
{282}{}{Igen... faaaaarm. Farm északra. Menni farm. Rossz dolgoknak mondani: Pápá.}
{283}{}{Ez nagyszerű! Elküldök néhány embert, hogy azonnal álljanak neki a betakarításnak. Megmentettél bennünket.}
{284}{}{Mutatni ÉLET!}
{285}{}{Azt mondják, hajlandóak élelmet adni gyógyszerekért és más dolgokért. Nem tudom, bízhatunk-e bennük. Végül is megölték Karlt meg a többieket. Mi erről a véleménye?}
{286}{}{Az összes kirakott test kamu. Semmi más csak néhány brahminbéllel befedett bábu. Azt akarták csak, hogy maguk ne lopkodják a terményüket.}
{287}{}{Nagyon érzékenyek a fényre. Szerintem néhány fáklyával felszerelt ember szempillantás alatt ki tudná füstölni onnan őket.}
{288}{}{Megtaláltam Karlt Rejtekben. Azért ment el, mert senki nem akarta neki elhinni a szellemeket és nagyon berezelt.}
{289}{}{Szegény Jonnyt túszul tartják ott! Támadnunk kell!}
{290}{}{Kamu? A saját szememmel láttam a testeket. Akárhogy is legyen, Karl nincs itt. Hogy magyarázzák ezt? Nem bízom bennük, amíg mindent le nem rendeztünk velük.}
{292}{}{Azt állítják, hogy aki néhány éve beköltözött, hirtelen lelépett.}
{293}{}{Karl nem tenne ilyet. Valószínűleg megölték! Nem, amíg nem tudjuk biztosan, mi történt Karllal, nem bízhatunk bennük. Reméltem, hogy ez nem következik be, de most az következik, hogy megyünk és erővel elvesszük a farmot. Vagy ők, vagy mi.}
{294}{}{Várjon csak! Hadd próbáljak magam rájönni, mi történhetett Karl barátunkkal. Kell, hogy legyen valami magyarázat az eltűnésére.}
{295}{}{Egyetértek, hogy támadni kéne! Az ő gyengeségük a szemük.}
{296}{}{Nem értek egyet ezzel. Rájöttem, mi folyik a Kísértetfarmon. Most pedig mondja meg, hol a szent ÉLET!}
{297}{}{Adok egy hónapot, hogy minél több dolgot megtudjon Karlról. Ha nem jön vissza időben, mozgósítani fogom Modoc lakosságát, és erővel vesszük el a farmot.}
{298}{}{Oké, egy hónap! Ne csináljanak semmi elhamarkodott dolgot. Hamarosan visszajövök.}
{299}{}{Több idő kell. Ilyen rövid idő alatt lehetetlen megtalálni őt.}
{300}{}{Egy hónap, nem több! Mondtam, hogy mindenre elszántuk magunkat. Az élelmiszerkészletünk veszélyesen megfogyatkozott. Egy hónapra való maradt belőle, aztán jön az éhezés. Indulok, és azonnal beszervezem a város lakosságát. Siessen!}
{301}{}{Kérem ne hamarkodjon el semmit, amíg vissza nem érek!}
{302}{}{[Homlokára csap] Rejtek! Asszem, egy kicsit kemények voltunk vele. El tudom képzelni, min ment keresztül a Kísértetfarmon, hiszen senki nem hitt neki. Szóval részegeskedik? Rejtekben? Ha Karl megkapná az üzenetet, hogy visszavárjuk, nagyon hálás lennék. Amúgy szerintem itt az idő, hogy az Aljanép és Modoc lakossága barátkozni kezdjen.}
{303}{}{Szerintem a megállapodásunk rám eső felét megtettem. Mit szólna, ha most rátérnénk a magáéra és elmondaná, hol találom a szent ÉLET-et!}
{304}{}{[Acting a little embarrassed.] Um... well, you see, I don't really know anything about this holy
 GECK thing you're looking for. You have to understand; we were desperate! However, I do know of a place
 called Gecko. It's a ways east of here somewhere. If I were a betting man, I would wager your GECK gizmo
 is located there. I wish I had more I could give you, but we're still a poor community with not
 much in the way of offerings. The best I can do is offer you goods at basically my cost. But
 I'd be honored to help keep you stocked for your journeys when I have the goods and I'm sure any
 of the other residents would be equally grateful if you asked them. Thank you! You've saved us all.}
{305}{}{Szóval Karlt megölték a farm közelében felnyársalt összes emberrel együtt. Na, jó, induljunk! Maga rátalált a rejtekhelyükre és elég alkalmas embernek is látszik. Vezessen győzelemre bennünket a mocskos Aljanép ellen!}
{306}{}{Hogyne! Ilyen igaz ügy érdekében boldogan segítek legyőzni az Aljanépet.}
{307}{}{Lehet, hogy nem a legjobb ötlet. Találjunk ki valami mást.}
{308}{}{Nagyszerű! Összekürtölöm a városiakat, és ott találkozunk.}
{309}{}{Látta ott Jonnyt?! Már tűvé tettük érte a környéket. Azok a szörnyetegek elrabolják a gyerekeinket. Nem vagyunk biztonságban, amíg mindannyian meg nem haltak. Összeszedem a városiakat, és lerohanjuk a rejtekhelyüket. Találkozzunk a Kísértetfarmon amilyen gyorsan csak lehet.}
{310}{}{Hogy képes a saját bőrében megmaradni? Itt krízishelyzet van, maga meg csak a saját érdekével törődik? Na, jó, miért nem megy akkor Gekkóba? Valahol kelet felé található. Ha van valaki, aki tud arról az ÉLET bigyóról, akkor ők azok. Most pedig, ha megbocsát, össze kell jönnöm a városiakkal, hogy kitaláljuk, mitévők legyünk.}
{311}{}{Ez nagyszerű. Mik voltak azok a valamik egyébként?}
{312}{}{Valami mutáns banda. Ha eddig nem voltak szellemek, akkor most már azok.}
{313}{}{Szellemek voltak. Eltűntek. Elég ennyit tudnia. Most pedig mondja meg, hol van a szent ÉLET.}
{314}{}{Nem azzal küldtük el, hogy ezt tegye. Az volt a feladata, hogy nyomozza ki, mi történik a farmon, és hozzon információkat. Azt hiszem, most távoznia kéne.}
{315}{}{Támadni fogunk, de csak akkor, ha nincs más lehetőség. Sajnos csak egy hónapra való élelmiszerünk maradt, aztán jön az éhezés. Ennyi ideje van, hogy rájöjjön, mi folyik itt. Nem tárgyalok velük, amíg nem vagyok biztos benne, hogy nem csináltak semmit Karllal.}
{316}{}{Támadni fogunk, de csak akkor, ha nincs más lehetőség. Sajnos csak egy hónapra való élelmiszerünk maradt, aztán jön az éhezés. Ennyi ideje van, hogy rájöjjön, mi folyik itt. Nem tárgyalok velük, amíg nem tudom biztosan, hogy nem tettek semmit Karllal. Azt is tudnom kell, miért húzták karóba azt a sok szerencsétlent ott a farm közelében. Nem akarok vademberekkel közösködni.}
{317}{}{Azt hiszem, jobban szeret gyilkolászni, mint azt az én izlésem el tudná viselni. Jobb lenne, ha távozna.}
{318}{}{Rejtekben? Szerfelett hálásak lennénk, ha át tudná adni neki, hogy hiszünk benne és hazavárjuk.}
{319}{}{Arra is rájöttem, hogy az összes Kísértetfarmot körülvevő test kamu. Sima bábuk brahminbelsőséggel betakarva.}
{320}{}{Akkor beszél az Aljanép vezetőjével?}
{321}{}{Egyelőre ennyit tudok.}
{322}{}{Fake! That's impossible; I saw them with my own eyes. Blood and gore everywhere. But... I guess
 it's possible, we didn't... I mean... well [Jo's face turns beat red.] We all kind of turned tail and ran
 when we saw the bodies. No one actually had the guts to examine them closely.}
{326}{}{Igen, hiszem, hogy az Aljanép és Modoc népe képes lesz valami kölcsönösen előnyös megegyezésre. Köszönjük, hogy megmentette Modoc városát.}
{327}{}{Van még valami apróság... Azt mondta, elmondja, hol a szent ÉLET.}
{328}{}{Meg kell tudnia, kik a Kísértetfarm közelében karóba húzott emberek. }
{329}{}{Karl már jóideje eltűnt a farmról. Rá kéne jönnie, mi történt vele.}
{330}{}{Értem, megnézzük, mit tehetünk.}
{331}{}{Nem szeretjük a te fajtádat errefelé!}
{400}{}{[Engeded, hogy levágja az ujját.] Oké, most már segítek.}
{410}{}{Mi az a nagy fehér épület a város közepén?}
{500}{}{Ó, az a templom. Modoc népe építette, hogy kimutassák hitük erejét. Mostanában nem sokmindent köszönhetünk meg odabenn, ezért a prédikációk megszüntek.}
{600}{}{Kedves ifjú pár! Azért gyűltünk itt most egybe...}
{602}{}{[Jo lapoz néhányat.]}
{603}{}{OK, um... Before we begin, is there anyone in this room who knows any reason why these two
 here before us should not be joined together in holy matrimony?}
{604}{}{Elfogadod-e }
{605}{}{ testvérünket kedves, }
{606}{}{, törvényes}
{607}{}{Akkor a törvény értelmében házastársaknak nyilvánítalak benneteket. Most pedig megcsókolhatod a menyasszonyt.}
{608}{}{Akkor a törvény értelmében házastársaknak nyilvánítalak benneteket. Most pedig megcsókolhatják egymást a menyasszonyok.}
{609}{}{Akkor a törvény értelmében házastársaknak nyilvánítalak benneteket. Most pedig megcsókolhatod a másikat.}
{612}{}{[Bo turns some pages in his book.]}
{625}{}{ feleségedül?}
{626}{}{ férjedül?}
{627}{}{ Micsoda?... egyébül? Szóval törvényes egyébül?}
{628}{}{ egyébül?}
{629}{}{Miria}
{630}{}{Davin}
{800}{}{Megtámadjuk az Aljanépet, mégpedig }
{801}{}{ napon belül, hacsak meg nem tud győzni minket az ellenkezőjéről.}
{802}{}{Holnap megtámadjuk az Aljanépet, hacsak meg nem győz bennünket az ellenkezőjéről.}
{803}{}{Most azonnal megtámadjuk az Aljanépet! Jön vagy marad?}
{804}{}{Jövök!}
{805}{}{Elegem van ebből, kiszállok!}
{806}{}{Akkor támadjunk! Az Aljanép bebizonyította, hogy megbízhatatlanok.}
{820}{}{Miben segíthetek?}
{821}{}{Nem akarok részt venni ebben. Én teljesítettem a magam részét. Mondja meg, hol van az ÉLET!}
{850}{}{Visszajövök, ha rájöttem, mi történt Karllal.}
{900}{}{Köszönjük, hogy megmentette kicsiny városunkat, barátom.}
{925}{}{Nem tesz semmit. Viszlát!}
{1000}{}{Megmentetted Modoc városát.}
{1500}{}{You see Substitute Justice of the Peace Bo.}
