{100}{}{Ez egy szurtos kölök, aki a brahminokra felügyel.}
{101}{}{Marhapásztor.}
{150}{}{A munkáján kívül nemigen figyel másra.}
{200}{}{Bocsi, az istálló tele van. Máshova kell mennie.}
{201}{}{Most nem érek rá.}
{250}{}{Szag? Gondolom hozzászoktál.}
{251}{}{Nem is olyan vészes.}
{252}{}{Szerintem idén nem kell trágyáznom. Köszi.}
{300}{}{Ennek friss széna kell.}
{301}{}{Vizet kell még hoznom.}
{302}{}{Hű! Lapát kell ide.}
{303}{}{Ez itt rendben van.}
{304}{}{Jobb lenne ezt szemmel tartani. Elég betegnek látszik.}
{350}{}{Zzz... Alszom... Zzz...}
{351}{}{*ÁSÍT* Korán kell kelnem.}
{352}{}{Hé, én még növésben vagyok. Aludnom kell.}
{353}{}{Miért nem megy és beszél mással?}
{354}{}{Azta, álmos vagyok, mint a fene. Bárcsak hagynának aludni.}
