{100}{}{A hölgy pornószínészn?.}
{150}{}{Ez a n? igen csinos. Mintha magában beszélne.}
{151}{}{Mintha szöveget memorizálna. Kis id? után "O" bet?t formál a szájából és el?re-hátra kezdi mozgatni a fejét.}
{152}{}{A hölgy pornószínészn?. Rád sem hederít.}
{200}{}{Gondolom, meg kéne köszönnöm, hogy megmentetted a világot, de én inkább egy hosszú, szenvedélyes szeretkezésre gondoltam veled kapcsolatban. Nem gond?}
{201}{}{Úgy hallottam, te vagy az a tökös gyerek, aki picsán rúgta az Enklávét.}
{202}{}{Az olyan fickóktól, akik picsán rúgják a gonosz enklávésokat, nedves lesz a bugyim.}
{203}{}{Azt mondják, a Testvérek várnak téged. Filmet akarnak forgatni a kalandjaidból.}
{210}{}{Gondolom, meg kéne köszönnöm, hogy megmentetted a világot. Hát... kösz.}
{211}{}{Úgy hallottam, te vagy az, aki seggbe rúgta az Enklávésokat. Le vagyok ny?gözve.}
{212}{}{Azt hallottam, a Testvérek keresnek téged. Filmet szeretnének készíteni a kalandjaid alapján. Öö, esetleg játszhatnék benne egy kis szerepet...?}
{220}{}{SZÍVESKEDNÉL nem trappolni itt abban a pléhvacakban? Szeretném még ma megtanulni a szövegemet.}
{221}{}{Akármilyen harcirobotos játékból is jöttél, húzzál vissza! Ez egy SZEREPJÁTÉK!}
{222}{}{Valamit takargatsz?}
{230}{}{Mi újság, }
{231}{}{Jól nézel ki, }
{232}{}{Hé, kicsim? Egyedül élsz?}
{233}{}{Hát nem er?ltetik meg magukat fizetéskor...}
{234}{}{Na, nézzük... "Oh, istenem"... "Mutasd gyorsan..." Francba! Mi is a következ? sor?}
{235}{}{Na, jó, de mi motivál ENGEM ebben a jelenetben?}
{236}{}{Nézzük csak... (belenéz a forgatókönyvbe)... a fickó bejön, mi szexelünk. Nem t?nik nehéznek.}
{237}{}{Én igazából rendezni szeretnék.}
{238}{}{Istennek hála végre felszerelték azt a párnázott fejtámlát.}
{239}{}{Nem tudom, mit esznek benne a Korzikai Testvérek...}
{240}{}{Bárcsak lelépne és sosem látnám újra ezt a n?t.}
{241}{}{Az a csaj egyszer?en koppintja a stílusomat.}
{242}{}{Nagykanállal eszi a pasikat az ribanc.}
{243}{}{Hmmm... Ezt a gyökeret!}
{244}{}{Olyan tehetséges, mint egy k?darab, viszont kétszer olyan randa.}
{250}{}{Mi újság, }
{251}{}{Na, végre egy kis balhé, de a fene bánja.}
{252}{}{Nem engem keresel?}
{253}{}{Miért nem jössz gyakrabban?}
{254}{}{Van egy tágra nyitott lehet?ségem számodra.}
{255}{}{Végre egy igazi pasi is felt?nt errefelé...}
{256}{}{Na, nézzük... "Oh, istenem"... "Mutasd gyorsan..." Francba! Mi is a következ? sor?}
{257}{}{Na, jó, de mi motivál ENGEM ebben a jelenetben?}
{258}{}{Nézzük csak... (belenéz a forgatókönyvbe)... a fickó bejön, mi szexelünk. Nem t?nik nehéznek.}
{259}{}{Én igazából rendezni szeretnék.}
{260}{}{Istennek hála végre felszerelték azt a párnázott fejtámlát.}
{265}{}{Mi újság, }
{266}{}{Na, végre egy kis balhé, de a fene bánja.}
{267}{}{Nem engem keresel?}
{268}{}{Miért nem jössz gyakrabban?}
{269}{}{Van egy tágra nyitott lehet?ségem számodra.}
{270}{}{Végre egy igazi pasi is felt?nt errefelé...}
{271}{}{Na, nézzük... "Oh, istenem"... "Mutasd gyorsan..." Francba! Mi is a következ? sor?}
{272}{}{Na, jó, de mi motivál ENGEM ebben a jelenetben?}
{273}{}{Nézzük csak... (belenéz a forgatókönyvbe)... a fickó bejön, mi szexelünk. Nem t?nik nehéznek.}
{274}{}{Én igazából rendezni szeretnék.}
{275}{}{Istennek hála végre felszerelték azt a párnázott fejtámlát.}
{280}{}{Mi ez a szag?}
{281}{}{Nagyszer?! Egy újabb ungabunga szartaposó.}
{282}{}{Ne beszélj hozzám!}
{283}{}{Na, nézzük... "Oh, istenem"... "Mutasd gyorsan..." Francba! Mi is a következ? sor?}
{284}{}{Na, jó, de mi motivál ENGEM ebben a jelenetben?}
{285}{}{Nézzük csak... (belenéz a forgatókönyvbe)... a fickó bejön, mi szexelünk. Nem t?nik nehéznek.}
{286}{}{Én igazából rendezni szeretnék.}
{287}{}{Istennek hála végre felszerelték azt a párnázott fejtámlát.}
{288}{}{Nem volna rossz, ha nem szólalnál meg, amíg velem beszélsz. Gondolj szép csendben magadra, és tégy úgy, mintha válaszolnék.}
{289}{}{Ki vagy te?}
{290}{}{Te vagy az új csicskás?}
{295}{}{Nem vagy te túl alacsony egy rohamosztagoshoz képest?}
{296}{}{Aiiijjjj! A szívbajt hozod rám!!! T?nés kifelé!}
{297}{}{Milyen filmet akarsz te itt forgatni? Pirx pilóta kalandjait? Na, t?nés innen, bádogember!}
{298}{}{SZÍVESKEDNÉL nem trappolni itt abban a pléhvacakban? Szeretném még ma megtanulni a szövegemet.}
{299}{}{Valamit takargatsz?}
{305}{}{Mi újság, }
{306}{}{Nem akarsz segíteni a szövegem gyakorlásában?}
{307}{}{Nincs kedved egyet zuhanyozni velem a következ? jelenet el?tt?}
{308}{}{Tetszik, amit a nyelveddel csinálsz.}
{309}{}{They've got me set up as the French exchange student from next door.}
{310}{}{A komornyik vagy a sof?r vagy a harmadik jelenetb?l?}
{311}{}{Feldobhatnál egy kis Jettel...}
{312}{}{A forgatás csak nyúlik, mint a tészta... fenébe, teljesen kikészít.}
{313}{}{Asszem, végre közös jelenetet fogunk forgatni!}
{314}{}{A fiúim nem tudják, hogy itt dolgozom. Na, nem mintha érdekelne, mit gondolnak.}
{315}{}{Nem láttam itt a Testvéreket... próbáld meg az irodát!}
{316}{}{Nem igazán érdekel, mi lesz kés?bb, csak térítsd meg a beléd ölt pénzt.}
{317}{}{Szenvedélyes, misztikus pasi vagy. A kéj embere.}
{318}{}{Csinálhatjuk a neked legkényelmesebb módon.}
{319}{}{Amint veszek egy forró zuhanyt, jöhet a következ? jelenet.}
{320}{}{Bárki mamája leszek, aki szeretetre vágyik.}
{321}{}{Sztár lesz bel?led. Nagy, fényes, ragyogó sztár.}
{322}{}{Kirobbanóbb vagy, mint egy vulkán, ha rossz napja van.}
{323}{}{Tetszik, amikor Spanyol akcentussal csinálod.}
{324}{}{Csodálatosan nézel ki, kedvesem.}
{330}{}{::Rád sem hederít::}
{331}{}{Te a francia vagy az orosz lány vagy a következ? jelenetb?l?}
{332}{}{Bárcsak megbízhatóbb lenne a fogamzásgátlás.}
{333}{}{Te raktad el a magassarkúmat?}
{334}{}{Kissé fáradt kezdek lenni... nincs nálad egy kis Jet?}
{335}{}{Hmphhh!}
{336}{}{Sajnálom, kedvesem. Nem tudom, a Testvérek épp hol vannak.}
{337}{}{Megmutassam a kijáratot?}
{338}{}{Meghíztál?}
{339}{}{Szíveskednél kissé hátrébb állni! A bel?led áradó... illatfelh?... émelyít.}
{340}{}{Úgy hallottam, a Testvérek meg akarnak válni t?led. Sajnálom, ez annyira gáz.}
{341}{}{Szerintem, ha egy hozzád hasonló antitalentumnak sikerül, akkor én is vihetem valamire.}
{342}{}{Milyen telt kis segged van! Csinosnak is mondható!}
{343}{}{Ebben az iparban szerintem nem nehéz érvényesülni.}
{344}{}{Én ugyan nem mondtam rólad, hogy kövér vagy csúnya vagy. Valaki más mondhatta.}
{345}{}{Úgy hallottam, egyik színész sem akar veled dolgozni.}
{346}{}{Korábban sosem fürödtél?}
{350}{}{Mi újság, }
{351}{}{Abbahagyod a bokszot a pornó kedvéért? Végül is ugyanaz, csak máshol megy a küzdelem.}
{352}{}{Nem akarsz ringbe szállni velem, bajnokom?}
{353}{}{Nem akarsz bokszcsatát vívni, bajnokom?}
{354}{}{Vigyázz a Húsdarálóval! Az a fickó meg van zakkanva. Egyszer már le akarta harapni a fülemet.}
{355}{}{Nem akarsz segíteni a szövegem gyakorlásában?}
{356}{}{Feldobhatnál egy kis Jettel...}
{357}{}{A forgatás csak nyúlik, mint a tészta... fenébe, teljesen kikészít.}
{358}{}{Azért jöttél, hogy egy-két csajszit kipróbálj?}
{359}{}{Szép darab vasrúd van a zsebedben.}
{360}{}{A fiúim nem tudják, hogy itt dolgozom. Na, nem mintha érdekelne, mit gondolnak.}
{361}{}{Ha társaságra vágysz, most van egy kis szabadid?m.}
{362}{}{Beszállsz az iparba? Üdv a fedélzeten.}
{363}{}{Szép a micsodád.}
{364}{}{Be kéne szállnia a pornóba. A teste megvan hozzá.}
{365}{}{Szép darab vasrúd van a zsebedben.}
{366}{}{Ha társaságra vágysz, most van egy kis szabadid?m.}
{367}{}{Hallottam rólad. A neved }
{368}{}{A f?nök küldött hozzám?}
{369}{}{Csak nem egy kis szexet akarsz kicsiholni bel?lem? Rajta, ne fogd vissza magad!}
{370}{}{A f?nök említette a nevemet neked?}
{380}{}{Milyen az ökölvívás?}
{381}{}{Vigyázz a Húsdarálóval! Az a fickó meg van zakkanva. Egyszer már le akarta harapni a fülemet.}
{382}{}{Tetszik a ruhád. Dögös maca.}
{383}{}{Ez a ruha remekül áll rajtad.}
{384}{}{Mit akar itt a... oh! Hölgyem! Üdvözöljük a stúdióban.}
{385}{}{A fiúim nem tudják, hogy itt dolgozom. Na, nem mintha érdekelne, mit gondolnak.}
{386}{}{Öö... nem tudna egy kis Jettel feldobni engem, hölgyem? Nagyon rámférne.}
{387}{}{A forgatás csak nyúlik, mint a tészta... fenébe, teljesen kikészít.}
{388}{}{Hm... van valami dolgom kés?bb? Ööö... nincs, hölgyem. Semmi az égadta világon.}
{389}{}{Milyen a f?nöknek dolgozni?}
{390}{}{A f?nök beszélt valaha rólam?}
{395}{}{Kötözés meg a szado-mazo csak szerdán van. Most pedig illegesd ki szépen a kis b?rnacis seggedet a helyiségb?l.}
{396}{}{Er?sen kétlem, hogy a Testvérek újabb b?rcuccos filmet forgatnának a "B?rökben éltek míg meg nem haltak" fiaskója után.}
{397}{}{Kérlek, szállj le rólam. Próbálom megtanulni a szerepemet.}
{398}{}{MINTHA b?rszagot éreznék! Azt hittem a fotelból jön, de nem...}
{399}{}{Figyu, b?rnyuszi, ha nincs saját korbácsod, a Testvérek úgy penderítenek ki, mint a huzat.}
{410}{}{Te lennél a partnerem? Na, neee. A rúzsommal frankóbb szexre lennék képes.}
{411}{}{Miért nem szórakoztatod magad inkább egy ceruzahegyez?vel?}
{412}{}{Most nincs id?m, hogy unalmas, értelmetlen beszélgetésbe fogjak veled.}
{413}{}{Az sem hat meg, ha képes vagy egy százas szöget beverni a deszkába a farkaddal! T?nj a szemem el?l! }
{414}{}{Szexelni akarsz? Sajnos férjezett vagyok, meg különben sincs kedvem.}
{415}{}{Nem randizok fiúkkal.}
{416}{}{Nem hiszem, hogy jobb lennél a zuhanyzórózsámnál.}
{417}{}{Nem úgy nézel ki, mint aki eleget tudna tenni az én vásárlási igényeimnek.}
{418}{}{Kedvesem, nem valószín?, hogy megengedhetsz magadnak.}
{419}{}{Az Igazit keresem. Kösz, hogy nem hagysz unatkozni, amíg fel nem t?nik.}
{420}{}{Nehogy azt hidd ám, hogy a bugyim közelébe juthatsz. Tudod, csak egy seggnek van benne hely.}
{421}{}{Bocs, azt hittem, jól nézel ki, de tévedtem.}
{422}{}{Veled? Ekkora hiányom azért nincs.}
{423}{}{Nem láttam a Testvéreket errefelé... most pedig hagyj békén. Színészn? vagyok.}
{424}{}{Légyszi... nem adok autogramot.}
{425}{}{Tudom, mi hiányzik nekem. A rendezés...}
{426}{}{Csütörtökönként a kaszinókban táncolok. Gyere nézz meg, és hozz magaddal egy kis lovettát is.}
{427}{}{Nem hiszem, hogy valaha is felfognád, mennyire stresszes az életem.}
{428}{}{A fiúim nem tudják, hogy itt dolgozom. Na, nem mintha érdekelne, mit gondolnak.}
{429}{}{Kérlek, hagyj lógva! Próbálom megjegyezni a szövegemet.}
{430}{}{Ha munkát akarsz, beszélj a Testvérekkel!}
{431}{}{Te vagy az új tutajos?}
{432}{}{Te vagy az új csicskás? Nem tudom elképzelni, mi más lehetnél.}
{433}{}{Ha te vagy az új csicskás, kezdésnek akár ki is törölhetnéd a seggem.}
{434}{}{Nem láttam a Testvéreket errefelé, kislány... most pedig hagyj békén. Én itt színészn? vagyok.}
{435}{}{Kislány... nem adok autogramot.}
{436}{}{Ha egy kicsit megmosdanál, talán még "Tutajos" is lehetnél.}
{437}{}{Sajnálom, de 200 dolcsinál kevesebbért nem leszek leszbikus. Neked inkább 300.}
{438}{}{Csütörtökönként a kaszinókban táncolok. Gyere nézz meg, és hozz magaddal egy kis lovettát is.}
{439}{}{Nem hiszem, hogy valaha is felfognád, kislány, mennyire stresszes az életem.}
{1230}{}{?}
{1231}{}{ vagyok.}
{1250}{}{?}
{1265}{}{?}
{1305}{}{?}
{1350}{}{?}
{1367}{}{, ugye?}
