{100}{}{Õ a Korzikai Testvérek egyike.}
{150}{}{Ez a jólöltözött fickó bûzlik a vazelintõl. Valami oknál fogva, eléggé gyíkszerû benyomást tesz rád.}
{151}{}{Õ Marty, a Korzikai Testvérek egyike. A haját lesímította, az arcát pedig csillogó izzadtság borítja.}
{152}{}{Õ Marty, a Korzikai Testvérek egyike. Kis parókát visel, hozzá pedig sötét napszemüveget.}
{200}{}{Hé, }
{201}{}{}
{202}{}{Hela, }
{210}{}{Hogy a fészkes fenébe mész fürdeni, ha rajtad van ez a vacak?}
{211}{}{Ez valami új vibrátor?}
{212}{}{Ez valamiféle új test-óvszer?}
{220}{}{Kirobbanóbb vagy, mint egy vulkán, ha rossz napja van.}
{221}{}{Tudtad, hogy csillag vagy? Hullócsillag...}
{222}{}{Tudtad, hogy csillag vagy? Egy fényességes, nagy csillag...}
{223}{}{Tudtad, hogy csillag vagy? Egy JÓKORA LÜKTETÕ csillag...}
{224}{}{A teljesítményed még úgy is megéri nekünk, hogy ezerszer kell felállítani.}
{225}{}{}
{226}{}{Tudtad, hogy csillag vagy? Egy fényességes, nagy csillag...}
{227}{}{Hé, üdv minálunk!}
{228}{}{Gyere, beszélgessünk egy kicsit!}
{229}{}{Beszéljünk az üzletrõl!}
{230}{}{Gyere máskor is!}
{231}{}{Tudod, mit bámulok? A világ legdögösebb szajháját.}
{232}{}{}
{233}{}{Szia, édeske, üdv újra a köreinkben!}
{245}{}{Ööö... egy öltönyös. Mindenki vegyen vissza magából...}
{246}{}{Helló, }
{250}{}{A szerelem Herkulese jött el hozzánk!}
{251}{}{Még az a mellizom! Befeszítenéd néhányszor?}
{252}{}{Gondolkoztál már azon, hogy karriert csinálj a szexiparban, }
{253}{}{Ha akarod, betehetlek egy-két jelenetbe. Gondolkozz rajta, oké?}
{254}{}{Jó a bunyós stílusod. Az ágybeli stílusoddal mi a helyzet?}
{255}{}{Bármikor szívesen látunk. Fõleg, ha az üzleti része is érdekel...}
{256}{}{Itt jön a nagy }
{257}{}{Gyere máskor is!}
{258}{}{Ne add fel, Xena!}
{259}{}{Jó kis feszes hasad van. Olyan, mint egy deszka.}
{270}{}{Teli vagyunk, hajcsár!}
{271}{}{Ezek az én rabszolgáim, hajcsár. Nézd csak azokat a szemeket!}
{275}{}{Szép ez a robotkutya, de ilyesmit nem filmezünk. Egyelõre...}
{276}{}{Az a robotkutya kóbor?}
{280}{}{Azta, micsoda lánctalp van azon a roboton!}
{281}{}{Ez az az új robotvibrátor, amirõl annyit beszélnek?}
{282}{}{A robotodat nem érdekli a filmezés?}
{290}{}{Vidd innen a mutáns barátodat! Mi nem csinálunk ilyen témájú filmeket.}
{291}{}{Megmondom az õszintét... szerintem itt nincs egyetlen színésznõ sem, aki bevállalná a mutáns barátodat.}
{292}{}{Egyszer már forgattunk egy mutánssal. Felfalta az összes színésznõt, de sajnos nem a szemével.}
{300}{}{Jesszus! Azonnal vidd ki innen azt a ghoult, mielõtt a szaga beeszi ide magát.}
{301}{}{Ghoulos filmet nem csinálunk! Vidd ki innen azonnal!}
{302}{}{Atyám, ez a ghoul úgy bûzlik, mint a pöcegödör! Hozzatok egy légfrissítõt, mert rögtön beájulok!}
{310}{}{A fények kihúnytak...}
{311}{}{Érdekel itt valakit egyáltalán, hogy az elsülés rajta lesz-e a felvett anyagon?}
{312}{}{Koncentrálhatnánk esetleg a csajszira?}
{313}{}{A jelenetek túl hosszúak lettek. Meg fogom húzni a tutajosok fizetését...}
{314}{}{MIT AKAR? Mondd meg a srácnak, hogy inkább tossza meg magát, meg azt a brahmin-t is, amin idejött!}
{315}{}{Az implantok korában sokkal jobban mentek a dolgok...}
{316}{}{A rezsi ki fog minket készíteni.}
{317}{}{Az a Diggler gyerek tetszett nekem.}
{318}{}{Ez a srác egy szexdinamit!}
{319}{}{Így nem fogunk lefilmezni, az tuti.}
{320}{}{Ez a srác egy rakéta! Egy ballisztikus rakéta, Sid! Úgy fog felszállni, mint a pinty, nekem elhiheted!}
{321}{}{Elbaszottuti-biztos!}
{322}{}{Mondd meg annak a fasznak, hogy menjen a picsába!}
{323}{}{Figyi, ha az a cukifalat újra idetolja a képét...}
{324}{}{Kiszi-köszi-kicsi-szöszi...}
{325}{}{Hát ha ez nem üt mindent, akkor semmi...}
{326}{}{Engem aztán kurvára nem érdekel!}
{327}{}{Mész és elmondod annak a szarevõ fasznak, szépen elmondod neki...}
{328}{}{Azt a srácot aztán szépen elkapta a csipkeimádat.}
{329}{}{Ez nem az Én Problémám, hanem a Te Problémád...}
{330}{}{20 perc, bébi...}
{331}{}{Nézzük csak: (beleolvas a forgatókönyvbe.) Randy belép, aztán Sylviával nekifognak... Christy elmegy a fürdõszobába, Peter utánamegy és nyomulnak egyet. Ron belép...}
{345}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant, bosszankodó arcot vág, aztán kiakad kissé.) Hé... te már jártál nálunk a tutajos állás ügyében, nem igaz?}
{346}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant és bosszankodó arcot vág.) Megint te vagy? Most érdekel a tutajos állás vagy sem?}
{347}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant, bosszankodó arcot vág, aztán kissé megütközve kérdezi.) Te vagy az új tutajos?}
{348}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant és bosszankodó arcot vág.) Te vagy az új tutajos?}
{349}{}{Én tutalos}
{350}{}{Én nem szívó! Én szívós!}
{351}{}{Elpályázol}
{353}{}{Én vónék.}
{354}{}{Tulképp a házastársam az.}
{356}{}{Nem, azért jöttem, hogy behajtsam Nagy Jesus Mordino pénzét.}
{357}{}{Nem. Bocs, hogy zavartam.}
{358}{}{Dehogyiiiiis. Bocs, hogy zavartam.}
{370}{}{Rendben, te kis agytröszt. 5 pé'zt ööö... 3 pé'zt fizetünk egy jelenetért. Menj az akció-szobába és állítsd fel az ottani fickó furkóját.}
{371}{}{Furkó... fickó lenni jó nagy...}
{372}{}{[Do as man say.]}
{380}{}{Vigyázz a szádra!}
{381}{}{Én beszélni Kálmánró'!}
{390}{}{(Feltartja a kezét.) Fogom én...}
{391}{}{Menek állítani furkó!}
{400}{}{Hmmmm. Mennyit nyomsz fekve, haver?}
{401}{}{Hmmmm. Édeske, kiváncsi vagyok, olyan szívós vagy-e, mint amilyennek látszol.}
{402}{}{Én nyom}
{403}{}{Én nem nyom pad én nyom nõ}
{404}{}{Nem édeske... pénzecske!}
{405}{}{Én bír}
{415}{}{Nagyszerûûûû. Haver, tudom én, honnan jössz, és PONTOSAN tudom, hova tartasz. Szeretnél színészkedni?}
{416}{}{Nagyszerûûûû. Édeske, tudom én, honnan jössz, és PONTOSAN tudom, hova tartasz. Szeretnél színészkedni?}
{417}{}{Én csíp ilyenek}
{418}{}{Mit kell színészkenni}
{425}{}{Télleg? Én ugyanígy vagyok vele! Máris egy csomó dologban hasonlítunk. Tudod, ez itt egy stúdió, itt születik a varázslat. Te pedig...}
{426}{}{ barátom, része lehetsz ennek a varázslatnak!}
{427}{}{ édeske, része lehetsz ennek a varázslatnak!}
{428}{}{Oki-doki}
{429}{}{Varázs! Varázs! Én szeret varázs!}
{435}{}{Mint egy ÁLLAT. Mint egy vaddisznó. Egy fõemlõs, aki azért zabolázza meg a vágyait, hogy a tömegek igényét kielégítse. VARÁZSLAT, BÉBI, VARÁZSLAT! Na, errõl beszélek én!}
{436}{}{Mint egy ÁLLAT. Mint egy megvadult kutya. Egy fõemlõs, kinek lelke arra hivatott, hogy a tömegek kéjvágyát lángralobbantsa. VARÁZSLAT, BÉBI, VARÁZSLAT! Na, errõl beszélek én!}
{445}{}{Kevválló! Most jöhet a próba. Látnom kell, mit nyújtasz az ágyban. }
{446}{}{Jöhet a játék, haver?}
{447}{}{Jöhet a játék, édeske?}
{448}{}{Gyühet}
{455}{}{Akkor fogjunk bele! Nincs vesztegetni való idõnk! Hé, valaki hozzon ide egy lézengõt! }
{456}{}{Rendben, haver, most megmutathatod...}
{457}{}{Rendben, édeske, most megmutathatod...}
{458}{}{[Do as the odd man directs.]}
{459}{}{Ahogy gondolod, de a java csak most jön.}
{465}{}{Sajnálom, haver, de a mi igényeinkhez nem vagy elég RUGANYOS. Dolgozz rajta, és késõbb talán beszélhetünk az üzletrõl, oké?}
{466}{}{Sajnálom, édeske, de a mi igényeinkhez nem vagy elég RUGANYOS. Dolgozz rajta, és késõbb talán beszélhetünk az üzletrõl, oké?}
{467}{}{Én AKARNI üzletet itten. Én jön VISSZA}
{468}{}{*Sznffff* Oki. *Sznfff* Én érez kihasználva}
{469}{}{Próbálok ráedzeni a ruganyosságomra. Talán legközelebb...}
{470}{}{Késõbb visszajövök. Miután vettem egy zuhanyt. Egy jó kiadós zuhanyt.}
{475}{}{Bocs, haver, jóképû vagy, és ruganyos is, de nem bírod eléggé a gyûrõdést... Edzz egy kicsit, és akkor talán beszélhetünk az üzletrõl, oké?}
{476}{}{Bocs, édeske, csinos vagy, és ruganyos is, de nem bírod eléggé a gyûrõdést... Edzz egy kicsit, és akkor talán beszélhetünk az üzletrõl, oké?}
{479}{}{Megpróbálok javítani az állóképességemen. Késõbb talán találkozunk.}
{485}{}{Bocs, haver, jóképû vagy, és ruganyos is, az állóképességed akár egy brahminé, de a hálószoba titkaiban tapasztalatlan vagy. Nekünk nincs idõnk arra, hogy behozzuk a lemaradást.}
{486}{}{Bocs, édeske, csinos vagy, és ruganyos is, az állóképességed remek, de a hálószoba titkaiban tapasztalatlan vagy. Nekünk nincs idõnk arra, hogy behozzuk a lemaradást, kiscsibém.}
{489}{}{Hát akkor megpróbálom behozni ööö... a lemaradást. Talán legközelebb.}
{495}{}{Hát barátom, ez hihhhhetetlen volt! }
{496}{}{Hát kedvesem, ez hihhhhetetlen volt! }
{497}{}{Aranyba kéne téged foglalni! Ez a teljesítmény MINDEN fáradságot megér! Akarsz velünk filmezni? Gyerünk, tárgyaljuk meg, bébi, beszélgessünk!}
{498}{}{Oki-Doki... én beszél veled. Én akar csinálni ezt újra meg újra}
{499}{}{Öh-öh. Én akar menni. Mocsoknak érez odabenn}
{500}{}{Érdekel a dolog, 200 dolcsit kérek egy jelenetért.}
{501}{}{Érdekel a dolog, de elõször tisztázzuk a feltételeket. Elõször is, csak TISZTA színészekkel dolgozom. Minden egyes jelenetért legalább 500 dolcsit kérek, valamint 20 százalék részesedést, és semmi SZARAKODÁS! Sztár vagyok, és ezzel te is tisztában vagy!}
{503}{}{Szó sem lehet róla! Zuhanyoznom kell. Egy jó kiadósat...}
{515}{}{(He yanks out a piece of paper from his jacket, and has you scrawl an "X" on it.) Done! Let's film! First, you'll
 need a stage name, something that screams STAR. Any ideas?}
{516}{}{(Elõkapar egy darab papírt a zakójából és aláíratja veled.) Kész! Jöhet a filmezés! Elõször is, kell neked egy jó kis név, amirõl üvölt, hogy SZTÁR vagy. Valami ötlet?}
{517}{}{Hát mit szólnál egy másik névhez?}
{525}{}{Hát hogy mondjam... az 500 dolcsi rendben volna, de a RÉSZESEDÉS nem kóser. Veszed az adást?}
{526}{}{Rendben.}
{527}{}{Akkor nincs üzlet. Majd látjuk még egymást.}
{528}{}{Ha nincs részesedés, }
{535}{}{Rendben! "}
{536}{}{Achtung! Achtung!}
{537}{}{[Get down to business.]}
{545}{}{Eh... ez a név nem jó! Rossz asszociációkat szül. Úgy értem, egy kellemes kis pornóban senki nem akar ilyen nevet látni. Válassz légyszi egy másik nevet!}
{546}{}{Okay...}
{547}{}{De én teccik a név}
{548}{}{De nekem tényleg tetszik ez a név.}
{555}{}{Hát ez aztán név a javából, nagyon-nagyon ütõs! Jó választás volt, haver, nagyon jó. Most pedig fogjunk munkához! Fények be! Kamera indul! Csapó!}
{556}{}{Ennek a névnek aztán van történelme és varázsa! Jó választás volt, haver, nagyon jó. Most pedig fogjunk munkához! Fények be! Kamera indul! Csapó!}
{557}{}{Hát ennek a névnek aztán van varázsa! Jó választás volt, édeske, nagyon jó. Most pedig fogjunk munkához! Fények be! Kamera indul! Csapó!}
{558}{}{Now, THAT'S a name so bright and so sharp, that it'll just EXPLODE because it's just so powerful! Good choice, honey-tits, good choice. Now, let's FILM! Lights! Camera! Action!}
{565}{}{Rendben! Rendben! Fogjunk munkához, emberek! Gyerünk! Mintha élnétek! Készen álltok?}
{566}{}{Készen állok mint péló}
{567}{}{Arra születtem, hogy KÉSZEN álljak.}
{575}{}{Na, kéremszépen... Mára ennyi lenne, haver. EGETVERÕ teljesítmény volt! EGETVERÕ! Megérte a beleölt pénzt... Tökéletes! Ha újra akarsz forgatni, egy hónapon belül gyere vissza, rendben?}
{576}{}{Na, kéremszépen... Mára ennyi lenne, édeske. EGETVERÕ teljesítmény volt! EGETVERÕ! Ha akarsz újra forgatni, egy hónapon belül gyere vissza, rendben?}
{577}{}{Oké... hali}
{585}{}{Snitt! Rendben is vagyunk, haver. }
{586}{}{Snitt! Rendben is vagyunk, édeske. }
{587}{}{Ez igen! EGETVERÕ teljesítmény volt! }
{588}{}{Megérted a pénzed! }
{589}{}{Megérte a sok nyavalygás! }
{590}{}{Tökéletes! Itt a fizetséged: }
{591}{}{200 dolcsi. }
{592}{}{500 dolcsi. }
{593}{}{Ha újra akarsz forgatni, gyere vissza egy hónapon belül, rendben?}
{594}{}{Akkor rendben vagyunk.}
{610}{}{Ugye nem szívatni akarsz?! Ha már mindenképpen tudni akarod, nem TE vagy a kiszemelt ember erre a munkára. Most, hogy ezt megtudtad, akarsz még valamit?}
{612}{}{Miféle munka? Ami azt illeti, tutajos vagyok. A legjobb a szakmában.}
{613}{}{Ööö, semmi-semmi. Rossz helyre jöttem.}
{620}{}{Jaj, mit is beszélek! Klasszis létedre bejössz ide, én meg úgy hablatyolok, mint egy idióta. Elnézést kérek, barátom. Munkát keresel? Nem a tutajos melóra gondolok. Igazi színészi játékra!}
{621}{}{Jaj, mit is beszélek! Klasszis létedre bejössz ide, én meg úgy hablatyolok, mint egy idióta. Elnézést kérek, édeske. Munkát keresel? Nem a tutajos melóra gondolok. Igazi színészi játékra!}
{622}{}{Elõször is mi ez a hely?}
{623}{}{Ha a fizetség nem marad el, akkor érdekel a dolog.}
{630}{}{Hm... faszállító... Menj szépen az akció-szobába, és fogj hozzá a merevítéshez! Itt a fizetséged: 5 dolcsi.}
{631}{}{[Do as he says.]}
{632}{}{Ööö, az a helyzet, hogy meggondoltam magam. Kösz, de inkább nem vállalom. Legjobb, ha most megyek is.}
{640}{}{A házastársad... Hmmmm. Rendben. Vezesd életed párját az akciószobába, és fogjon hozzá a farkak keményítéséhez. Itt a fizetség: 3 dolcsi.}
{641}{}{Tedd, amit a fickó mond, Davin kedvesem. Menj }
{642}{}{Tedd, amit a fickó mond, Miria kedvesem. MOST!}
{650}{}{Hogy mi ez a hely? Ugye csak viccelsz? Ez itt a Golden Globes filmstúdió, az egyetlen Renóban, és még mindig ÁLL. Hát nem ismered a saját otthonodat? Ez fáj...}
{651}{}{Hogy mi ez a hely? Ez itten a Golden Globes filmstúdió, haver, az egyetlen Renóban, és még mindig ÁLL. Szét akarod dumálni a fejem, vagy valami munkát akarsz?}
{652}{}{Hogy mi ez a hely? Ez itten a Golden Globes filmstúdió, drágám, az egyetlen Renóban, és még mindig ÁLL. Szét akarod dumálni a fejem, vagy valami munkát akarsz?}
{653}{}{Hogy mi ez a jó öreg hely? Ez itten a Golden Globes filmstúdió, haver, az egyetlen Renóban, és még mindig ÁLL. De ne beszéljünk errõl... munkát keresel, haver? Szükségünk van egy hozzád hasonló tehetségre.}
{654}{}{Hogy mi ez a jó öreg hely? Ez itten a Golden Globes filmstúdió, drágám, az egyetlen Renóban, és még mindig ÁLL. De ne errõl beszéljünk... munkát keresel, édeske?}
{655}{}{How do you "film?" I mean, c'mon... you'd need cameras, film, projectors... where would you get all that stuff?}
{657}{}{Kösz nem. Mennem kell.}
{658}{}{Csak benéztem. Mostanában egy kicsit kimerültnek érzem magam.}
{670}{}{Szerencsénk van... nincs szükségünk azokra a kõkori vackokra. Találtunk egy MÛKÖDÕ porno... ööö holo... grafikus vetítõt. Nincsenek bazi nagy berendezések, nincs fáradozás... és nincs az a sok dzsuva.}
{671}{}{Ez igen... milyen paraméterekkel rendelkezik az a vetítõ?}
{672}{}{Értem... hát meg kell mondjam, érdekelne valami meló, ha van még lehetõség.}
{673}{}{Örülök, hogy beszélhettünk, de most mennem kell.}
{680}{}{Még nem értük el a QEWB meghajtó kapacitásának felsõ határát. Közel sem. Egy nagy adatsûrûségû, 300 TByte-os memóriakocka van benne. A Ringyóz 57 oprendszer ugyan megeszi a hetven-hetvenöt százalékát, de így is több száz évig elleszünk vele.}
{681}{}{Hol van ez a memóriakocka? Láthatnám?}
{683}{}{Azta. Jó sok pornó belefér. Megyek, ez szöget ütött a fejembe.}
{690}{}{Nem, senki nem mehet be a filmes szobába... unom, hogy amikor vágásra, meg utómunkára kerül a sor, mindenki csak kibickedik. Ezenkívül az a cucc a mi kincsesbányánk, nem akarom, hogy valami baja essen.}
{692}{}{Hát meg lehet érteni. Isten tudja, mire nem használnák azt az izét, ha valaki ellopná. Na, akkor most megyek!}
{700}{}{Kevvválló! Persze, látnom kell, milyen fából faragtak, egy kis próbát kell tenned hálószoba-akrobatikából. Jöhet a játék, haver?}
{701}{}{Kevvválló! Persze, látnom kell, milyen fából faragtak, egy kis próbát kell tenned hálószoba-akrobatikából. Jöhet a játék, édeske?}
{702}{}{Hogyne.}
{703}{}{Öö... kösz nem. Meggondoltam magam. Talán máskor.}
{710}{}{Akkor húzz innen a fenébe, te kis szaros! Nincs rád szükségünk! Tûnés innen! Nem fogsz TE többet pornózni!}
{711}{}{Én se nem akarni! ÉRTENI?}
{712}{}{Franc essen beléd! Nem parancsolgatsz te nekem! Nem te vagy a fõnököm, az én saját beosztottam }
{720}{}{Tûnés innen! Nincs mit mondanom neked!}
{721}{}{Nekünk nincs semmi közünk egymáshoz. Kopj le!}
{730}{}{Üdvözlünk a stúdióban, }
{732}{}{Ha már itt tartunk, mondanál egy-két szót a stúdióról?}
{733}{}{Örülök, hogy ez szóba került. Én viszont Nagy Jesus Mordino pénzéért jöttem.}
{734}{}{Rendben. Késõbb visszanézek.}
{735}{}{(Kacsint.) Bébi, te pénzt jelentesz, ez a te sorsod!}
{740}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant, és mosolyog.) Üdv újra a stúdióban, }
{743}{}{Jöhet. Rogyasszuk meg az ágyakat!}
{745}{}{Nem igazán. Nagy Jesus Mordino pénzéért jöttem.}
{746}{}{Kösz nem.}
{755}{}{Nocsak... nem AKAROD csinálni? Te TÚL sokat érsz nekünk! Mi tettünk azzá, ami vagy, '}
{756}{}{Én nem felejt ne hari én szomorú jövök én visszafele de mostan menni kén'}
{758}{}{Rá se hederítesz, és elmész}
{759}{}{Nyugalom! Ma egyszerûen nincs kedvem, oké? Fenébe, majd visszajövök, ha lenyugodtál!}
{760}{}{Csesszétek meg! Ez a brahminszar nekem nem kell! Én sztár vagyok! Egy igazi Sztár!}
{765}{}{Hey... you all right? You seem a little out of it. You ain't on chems, are you? Cause I AIN'T gonna shoot you like this.}
{766}{}{Én akar filmez MOST kicsike ember}
{768}{}{Te nem vagy a fõnököm! Baszni akarok, és az én nagy farkam a lényeg, szóval most mindenki szépen nekiáll kibaszottul filmezni!!!}
{769}{}{Te nem vagy a fõnököm! Baszni akarok, és az én nagy lukam a lényeg, szóval most mindenki szépen nekiáll kibaszottul filmezni!!!}
{770}{}{Rendben, megpróbálok késõbb visszajönni, ha már lenyugodtál.}
{780}{}{A Korzikai Testvérek mindenki rendelkezésére állnak... (A férfi bosszankodva felnéz, aztán kiakad.) Szentséges... }
{781}{}{Engemet! Engemet!}
{782}{}{Semmit}
{783}{}{Mi ez a hely tulajdonképpen?}
{784}{}{Mondanál valamit a stúdióról?}
{785}{}{Van üresedés... amit... betölthetnék?}
{786}{}{Van valami munkátok a magamfajtának?}
{787}{}{Nagy Jesus Mordino pénzéért jöttem.}
{788}{}{Semmit. Már itt sem vagyok.}
{795}{}{Ez itt a Golden Globes stúdió, a világban még megmaradt tehetségek felkarolását tûztük ki célul. Úgy látom, barátom, te SZTÁR lehetnél nálunk. Gondolom tudod, mire célzok. Érdekel a színészet?}
{797}{}{Hogyne. Komolyan gondolod a dolgot?}
{799}{}{Jelen pillanatban nem. Bocs, hogy zavartalak.}
{805}{}{Hogy a fenébe ne! Tegyünk próbát! Hé! Hozzatok gyorsan egy-két lébecolót! Egy valóságos sztárral fogunk együtt dolgozni!}
{806}{}{[Do as the man directs.]}
{810}{}{A Korzikai Testvérek mindenki rendelkezésére állnak... (A férfi bosszankodva felnéz, aztán kiakad.) Szentséges... öö... hogy vagy, }
{812}{}{Semmitse}
{813}{}{Mi ez a hely tulajdonképpen?}
{814}{}{Keltsd fel az érdeklõdésemet! Mondj egy kicsit többet errõl a stúdióról!}
{815}{}{Jó kérdés. Volna némi... üresedés... amit betölthetnék?}
{816}{}{Jó kérdés. Van valami munkád a magamfajtának?}
{825}{}{Ez itt a Golden Globes stúdió, az egyetlen, amely a világban még megmaradt tehetségek felkarolását tûzte ki célul. Szóval... ööö... tehetek valamit érted?}
{827}{}{Van idõd arra, hogy megnézz engem? Tulajdonképpen gondoltam már rá, hogy sztár legyek...}
{829}{}{Ma már semmit. Bocs, hogy zavartalak.}
{835}{}{Ööö, hogyne. Hogyne. Hát próbáljuk meg... Lássuk, megy-e. Úgy értem, egy kicsit elfoglaltak vagyunk, de azért megpróbálhatjuk, oké? Ööö... hozzatok egy-két lébecolót, gyorsan!}
{836}{}{[Do as the man directs.]}
{845}{}{Ööö, hogyne, hogyne! Hogyne... itt van, tessék a 250 dolcsid. És ööö add át üdvözletem Nagy Jesusnak, oké?}
{846}{}{Ööö, hogyne, hogyne! Hogyne... sajnálom, hogy félreértés történt. Itt van, tessék. 250 dolcsi. Ja és add át üdvözletem Nagy Jesusnak, oké?}
{847}{}{Mielõtt sebtiben kizavarnál innen, miért nem mesélsz gyorsan valamit az itt folyó kis üzelmekrõl?}
{848}{}{Hát talán átadom. Na, csá, haver.}
{855}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant.) Már megint te vagy? Újabb munka kell, Tutajmûvész Úr?}
{856}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant.) Már megint te vagy? Újabb munka kell, Tutajmûvésznõ?}
{857}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant.) Hát te? Mi történt veled? Úgy értem, semmi gond... valamitõl biztos kiesett a fejembõl. Mintha a tutajoskodás iránt érdeklõdtél volna, ugyebár?}
{861}{}{Mi az a tutajos?}
{862}{}{Igen. Van még valami munka számomra?}
{875}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant.) Hé! Gondolkoztál az ajánlatomon?}
{876}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant.) Hé, akarsz egy újabb próbát?}
{877}{}{A Korzikai Testvérek mindenki szolgálatára állnak... (Felpillant.) Hé! Gondolkoztál az ajánlatomon? Újra megpróbálnád, hogy lásd, megvan-e benned a varázs?}
{879}{}{Ohkéj}
{881}{}{Igen. Meggondoltam magam. Kitegyem most, vagy...?}
{882}{}{Igen. Meggondoltam magam. Levegyem a bugyimat, vagy...?}
{895}{}{ ...hallottam a dolgaidról... hallottam, hogy szétcseszted az Enklávésok alól azt az olajfúró-tornyot. Gondolom, kellett hozzá gyomor.}
{896}{}{Ja}
{897}{}{Nema}
{899}{}{Hát én nem az összes Enklávést nyomtam azért le. Tudod, a történtek csak...}
{900}{}{Jobb, ha megyek.}
{910}{}{Ne szerénykedj! Tudom, hogy szivatós dolog lehetett. A legtöbb embernek nem lett volna gyomra hozzá. Viszont lenyelted a büszkeségedet és megtetted, amit kell. Ez sztártulajdonság.}
{911}{}{Ja}
{914}{}{Figyelj, ööö én nem az összes Enklávést nyomtam le. Ami történt csupán...}
{915}{}{Jobb, ha megyek.}
{920}{}{Tudod, mire gondoltam, }
{921}{}{Hõs vagy, }
{922}{}{Ja}
{924}{}{Úgy biza. Na, csá.}
{926}{}{Hogy a francba ne. Végül is végigcsináltam ezt a játékot. Na, húzzunk bele!}
{927}{}{Nagyszerû! Köszi...}
{928}{}{Elõbb hadd mentsek egy állást, aztán visszajövök és nekivághatunk.}
{935}{}{Ez az egész egy nagy romhalmaz.}
{936}{}{A memóriakocka nélkül... nekünk lõttek.}
{937}{}{Ó, kegyetlen szexistenek! Mit követtünk el, hogy elvettétek tõlünk a memóriakockát?!}
{938}{}{::Sóhajt:: Most, hogy a memóriakockának annyi, talán kötögethetnék...}
{1000}{}{Fáj hasika.}
{1001}{}{You have a foul, unhealthy taste in your mouth, and you feel sick to your stomach. But hey, 3 chips is 3 chips!}
{1100}{}{Akhh! ::köpködsz néhányat:: EZ TÖK SZÍVÁS!}
{1101}{}{You have a foul, unhealthy taste in your mouth, and you feel sick to your stomach. But hey, 5 chips is 5 chips!}
{1200}{}{Nem... érzem túl jól magam.}
{1201}{}{Az igazi szerelem újra gyõzedelmeskedett. A házastársad halálosan betegnek néz ki, de legalább 3 dolcsival gazdagabb vagy!}
{1250}{}{Sztár lettél, egy mindenkit felülmúló sztár.}
{5200}{}{! A hõs, akit már épp látni akartunk!}
{5201}{}{, a mi hõs barátunk. Van valamink a számodra!}
{5202}{}{! Hallottuk, mit tettél az Enklávéval! Akkor most beszéljünk arról, hogy mit tehetünk MI érted...}
{5225}{}{ aranyat ér. Igazi aranyat.}
{5232}{}{! Kedvesem! Édeském!}
{5246}{}{. Szép idõnk van ma, nem igaz?}
{5252}{}{?}
{5256}{}{, ha esetleg akarnál velünk forgatni...}
{5528}{}{ egyszerûen nemet mond erre és húz kifelé ebbõl a fosrakás stúdióból!}
{5535}{}{!" TETSZIK! TETSZIK! Na, akkor jöhet a filmezés... }
{5641}{}{ büszkén!}
{5712}{}{!}
{5730}{}{! Ma nincs felvétel, de hamarosan visszanézhetsz. }
{5740}{}{! Jöhet egy újabb film?}
{5755}{}{!' Errõl ne feledkezz meg!}
{5780}{}{?! Hogyhogy korábban nem jöttél hozzánk? Amúgy nagy csatát vívtál! Nagy csatát! Mit tehetek érted?}
{5810}{}{?! A nagyfõnök, }
{5920}{}{? Az eszem egyfolytában egy kalandfilmen jár, ami bemutatná a történetedet. A címe lehetne például: "Pullout: Post-Nuclear Boogalo." Benne lennél?}
{5921}{}{. Egy igazi hõs. Soha nem felejtem el, mennyi szart kellett lenyelned értünk. Ha a jegyeladásokról megküldik a visszajelzést, az egész világ tudni fog errõl!}
{6535}{}{! Fény be! Kamera indul! Csapó!}
{6810}{}{ jól van? Foglalj helyet! Szóval, ööö, mit tehetek érted?}
