{100}{}{Ő egy "tutajos".}
{150}{}{Ez a nő nem a világ szépe, de azért elmegy. Úgy tűnik, jól megnéz magának.}
{151}{}{Ő egy "Tutajos". Azt a benyomást kelti, mintha a veled való szexelés esélyét latolgatná.}
{160}{}{Ez a nő nem a világ szépe, de azért elmegy. Úgy néz rád, mint a riválisára.}
{161}{}{A nő egy "Tutajos". Úgy néz rád, mint a riválisára.}
{200}{}{Óh egek... ez Ő.}
{201}{}{Te vagy a legnagyobb tenyészcsődör a világon!}
{202}{}{::Majd elájul, hogy lát...::}
{203}{}{Úgy hallottam, a Testvérek utánad kajtatnak. Filmet akarnak csinálni a kalandjaidból.}
{204}{}{Igen, }
{205}{}{::Tapsol::}
{206}{}{::Éljenez::}
{207}{}{Óh, egek... ez Ő.}
{208}{}{Nagy vagy, bébi!}
{209}{}{::Hüvelykujjával mutatja, hogy minden rendben::}
{225}{}{Én ugyan rá nem bukom arra az izére.}
{226}{}{Hogy a fészkes fenébe mész fürdeni, ha rajtad van ez a vacak?}
{227}{}{Ez valami új vibrátor?}
{228}{}{Ez valamiféle új test-óvszer?}
{235}{}{Nincs szükséged valamire}
{236}{}{Erre-erre}
{237}{}{Nézzétek! Ez Ő!}
{238}{}{Nahát, }
{239}{}{Tudjátok kit szeretnék, ha a partnerem lenne? A nagy }
{240}{}{Az a srác aztán rajta van a témázgatáson.}
{241}{}{Erre a srácra bármikor rábukom.}
{242}{}{Hű, milyen mérges kis gyíkod van!}
{245}{}{Nincs szükséged valamire}
{246}{}{Ha ma még le kell ápolnom valakit, én totál kész leszek!}
{247}{}{Nem könnyű a "tutajosok" élete.}
{248}{}{Úgy hallottam, a családok közt megint viszály kezd kialakulni.}
{249}{}{Múlt héten jól tökön rúgtam Jules-t.}
{250}{}{Bárcsak a Testvérek odaengednének a kamera elé...}
{251}{}{Nem tudom, mit esznek benne a Korzikai Testvérek...}
{255}{}{Óh egek... ez Ő.}
{256}{}{Nézzétek ezeket az izmokat! Mindjárt elalélok!}
{257}{}{Úgy néz ki, mint egy harckocsi. Nézzétek azt a ágyúcsövet!}
{258}{}{Nézzétek azt az ágyúcsövet azon a harckocsin...}
{259}{}{Mindene az enyém...}
{260}{}{::Sóhajt::}
{261}{}{Az a srác aztán rajta van a témázgatáson.}
{262}{}{Hű, milyen mérges kis gyíkod van!}
{270}{}{Óh, egek... ez Ő.}
{271}{}{Üdvözöljük a stúdióban, hölgyem.}
{272}{}{(Megborzong) ...ez a nő aztán nem ijed meg az árnyékától.}
{273}{}{Ez a nő aztán nagyon csinos...}
{274}{}{Üdvözlöm hölgyem! Segíthetnék Önnek valamiben?}
{280}{}{Óh egek... ez Ő.}
{281}{}{Üdvözöljük a stúdióban, uram.}
{282}{}{(Megborzong) ...ez a fickó aztán nem ijed meg a saját árnyékától.}
{283}{}{Ez a legtökösebb ember, akivel valaha találkoztam.}
{284}{}{Az a srác aztán rajta van a témázgatáson.}
{285}{}{Hű, milyen mérges kis gyíkot rejtegetsz te ott!}
{290}{}{Óh, egek... ez Ő.}
{291}{}{Üdvözöljük a stúdióban, hölgyem.}
{292}{}{(Megborzong) ...ez a nő aztán nem ijed meg az árnyékától.}
{293}{}{Ez a nő aztán nagyon csinos...}
{294}{}{Üdvözlöm hölgyem! Segíthetnék Önnek valamiben?}
{300}{}{A francba! Ez Myron! Fussunk!}
{301}{}{Beszarok! Megjött Myron. Nyugalom... megérzi a félelmet.}
{302}{}{Jobb lenne, ha távoltartanád tőlem Myront.}
{303}{}{Myron, jobb lenne, ha ROHADTUL távol tartanád magad tőlem!}
{304}{}{Ha Mryon itt fog dolgozni, én veszem a kalapom.}
{305}{}{Myron, megdöntötted már az 5 másodperces rekordodat?}
{306}{}{Myron, mielőtt a Testvérek meglátnának téged, én lelépnék a helyedben.}
{315}{}{Ezek a bőrcuccosok nem tudják, hogy a szerda az ő napjuk?}
{316}{}{Nagyszerű! Már megint egy szado-mazo jelenet.}
{317}{}{Óhhhh. A fekete bőr egész új dolog...}
{318}{}{Bőrös és kötözős jelenetet jövő hétig nem forgatunk.}
{319}{}{Nagyszerű! Még egy bőrimádó!}
{320}{}{Figyusz, bőrharisnya, a szereplőválogatás szerdán van. Rendben?}
{325}{}{Ha ma még le kell ápolnom valakit, én totál kész leszek!}
{326}{}{Nem könnyű a "tutajosok" élete.}
{327}{}{Úgy hallottam, a családok közt megint viszály kezd kialakulni.}
{328}{}{Múlt héten jól tökön rúgtam Jules-t.}
{329}{}{A farokorrú haverod nagyon csini. Legalábbis a szadomazo fogalmak szerint.}
{330}{}{Ki ez az farokorrú fickó?}
{331}{}{Nézd már a farokorrú kannibált! Még viszi valamire!}
{332}{}{Hát láttam már néhány balesetet, de hogy egy srác orrába farok kerüljön... ez még nekem is meredek.}
{333}{}{Bárcsak a Testvérek odaengednének a kamera elé...}
{334}{}{::Rádbámul::}
{335}{}{Nagyszerű! Még egy tutajos. Ahogy kinéz, gondolom, feleáron dolgozik.}
{336}{}{Ez ki?}
{337}{}{Ki vagy?}
{345}{}{Ha ma még le kell ápolnom valakit, én totál kész leszek!}
{346}{}{Nem könnyű a "tutajosok" élete.}
{347}{}{Úgy hallottam, a családok közt megint viszály kezd kialakulni.}
{348}{}{Múlt héten jól tökön rúgtam Jules-t.}
{349}{}{Bárcsak a Testvérek odaengednének a kamera elé...}
{350}{}{Nagyszerű! Még egy tutajos. Ahogy kinéz, gondolom, feleáron dolgozik.}
{351}{}{::Rádbámul::}
{352}{}{Ez ki?}
{353}{}{Ki vagy?}
{360}{}{Enklávé? Elnök? Meséld már el elölről!}
{361}{}{Engem Tom French szkriptelt. Puha, gyengéd keze van a srácnak.}
{362}{}{Azok ott még mindig HÁBORÚSKODTAK? Tényleg? Hát jó, hogy kinyírtad azt a gyökér társaságot!}
{363}{}{Te aztán nem vagy semmi! Na, csak azért mondom, mert egy volt lándzsarázó törzsbéli - már elnézést a kifejezésért - megmentette a világot. Hihetetlen, elképesztő!}
{364}{}{Egy másik karakterrel újra végig kéne játszanod a játékot!}
{365}{}{Mondj el mindent az Enklávéval vívott harcodról... hozok egy hideg sört.}
{366}{}{Úgy hallottam, a Testvérek utánad kajtatnak. Filmet akarnak csinálni a kalandjaidból.}
{370}{}{Jaj, valamit beleejtettem a gatyádba. Hadd vegyem ki!}
{371}{}{Ööö... gondolom nincs kedved kimenni italért? Mit szólnál egy kis semmitmondó szexhez?}
{372}{}{Hogy tudsz ilyen fitt maradni?}
{373}{}{Kérhetek egy autogramot a mellemre?}
{374}{}{Körbevezettek már, }
{375}{}{Az ágyúcsövedhez elkel majd egy kis segítség.}
{376}{}{Azt mondják, veled... elég nehéz dolgozni.}
{377}{}{Úgy hallottam, akkor megy neked igazán, ha megjön a kedved. Nekem bejön.}
{378}{}{Igazán örülök, hogy ismerlek téged. Hiszen - az eszem megáll - a neved mégiscsak }
{379}{}{Hát tudom, hogy most épp nincs filmezés, de azért nincs szükséged egy tutajosra?}
{380}{}{Nincs szükséged valakire, aki babusgatja?}
{381}{}{Nem kell egy törülköző, }
{382}{}{Jó voltál a Nagy Szűzgolyókban.}
{383}{}{Remek voltál a Szexivánéji álomban!}
{384}{}{Tetszettél a Farkalókkal táncolók folytatásában.}
{385}{}{Tetszettél a "23 Centis Menedékben". Ihletet adott.}
{386}{}{Nem láttam a Testvéreket errefelé... próbálkozz az irodában!}
{387}{}{Van rá esély, hogy beszélj a Korzikai Testvérekkel a színészi lehetőségeimről?}
{388}{}{A tutajosoknak az a feladata, hogy a színészek merevek maradjanak.}
{389}{}{Szerepelhetnék a következő filmedben?}
{390}{}{Egész életemben azért nem akarok tutajos maradni. Akar a fene.}
{391}{}{Csak azért csinálom, hogy a tandíjat fizetni tudjam.}
{392}{}{A barátom nem tudja, hogy itt dolgozom.}
{393}{}{Obi? Máskor majd kivesézhetjük.}
{394}{}{A barátom nem tudja, hogy itt dolgozom.}
{395}{}{Néhány színész igazán zuhanyozhatna. Úgy értem, rendszeresen.}
{396}{}{Minden vágyam, hogy színésznő legyek.}
{397}{}{A barátnőm nem tudja, hogy itt dolgozom.}
{398}{}{Kérhetek autogramot tőled?}
{399}{}{Ööö... ugye nem szívesen mennél ki italért? Úgy értem, ha esetleg nőkre fájna a fogad...}
{400}{}{::Rád sem hederít::}
{420}{}{Nem akarsz ringbe szállni velem, bajnokom?}
{421}{}{Szép a micsodád.}
{422}{}{Nem kell valaki, aki babusgatja, bajnokom?}
{423}{}{Abbahagyod a bokszot a pornó kedvéért? Végül is ugyanaz, csak máshol megy a küzdelem.}
{424}{}{Beszállsz az iparba? Üdv a fedélzeten.}
{425}{}{Beszállsz az iparba? Legalább nem ott kell indulnod, ahol én tartok.}
{426}{}{Hogy én? Tutajos vagyok. Faszállító. Néha.}
{427}{}{A tutajosoknak az a feladata, hogy a színészek merevek maradjanak.}
{428}{}{A Testvérek szerint felbecsülhetetlen szolgálatot teszek. Talán ezért kell olyan sokszor lefeküdnöm velük.}
{429}{}{Be kéne szállnod a pornóba. A tested megvan hozzá.}
{430}{}{Akarsz bokszolni?}
{431}{}{Obi? Máskor majd kivesézhetjük.}
{432}{}{Vigyázz a Húsdarálóval! Az a fickó meg van zakkanva. Egyszer már le akarta harapni a fülemet.}
{433}{}{Üdv, hölgyem. Segíthetek... *bármiben?*}
{434}{}{Ha később egy kis társaságra vágyna, hölgyem...}
{435}{}{A szokásost, hölgyem?}
{450}{}{Üdvözöljük, uram. Segíthetnék... *bármiben?*}
{451}{}{Ha később vágynál egy kis társaságra...}
{452}{}{A szokásost, uram?}
{453}{}{Nincs szükséged valakire, aki babusgatja?}
{454}{}{Mondjon már egy-két jó szót értem a főnöknél...}
{455}{}{Ön is be akar szállni az iparba?}
{456}{}{Be kéne szállnod a pornóba. A tested megvan hozzá.}
{457}{}{Obi? Máskor majd kivesézhetjük.}
{458}{}{Üdv, hölgyem. Segíthetek... *bármiben?*}
{459}{}{Ha később egy kis társaságra vágyna, hölgyem...}
{460}{}{A szokásost, hölgyem?}
{465}{}{Bocs, de inkább nem. A rúzsommal jobbat tudnék szexelni.}
{466}{}{Veled? Bocs, de ekkora hiányom azért nincs.}
{467}{}{A farokorrú barátod ezzel próbál valamit elrejteni mások elől?}
{468}{}{A farokorrú barátod fogad kuncsaftokat?}
{469}{}{A farokorrú barátod elég jóképű. Legalábbis szado-mazo szemszögből.}
{470}{}{Ki ez a jóképű farokorrú barátod?}
{471}{}{Mondd meg annak a farokorrú előembernek, hogy még sokra viszi ebben az iparágban!}
{472}{}{Hát láttam már néhány balesetet, de hogy egy srác orrába farok kerüljön... ez még nekem is meredek.}
{473}{}{Nem láttam a Testvéreket errefelé... próbálkozz az irodában!}
{474}{}{A tutajosoknak az a feladata, hogy a színészek merevek maradjanak.}
{475}{}{Minden vágyam, hogy színésznő legyek.}
{476}{}{Egész életemben azért nem akarok tutajos maradni. Akar a fene.}
{477}{}{A barátom nem tudja, hogy itt dolgozom.}
{478}{}{Körbevezettek már?}
{479}{}{Ha munka kell, beszélj a Testvérekkel!}
{480}{}{Azért csinálom ezt, hogy ki tudjam fizetni a tandíjat.}
{481}{}{Avellone-t ingyen is lecummantanám.}
{482}{}{Nem mintha nem akarnék veled beszélgetni, de... tulképpen, tényleg nem akarok.}
{483}{}{Valaki megdönthetne.}
{484}{}{Obi? Máskor majd kivesézhetjük.}
{485}{}{Ugye nem viszolyogsz a disznó filmektől?}
{486}{}{Te vagy az új tutajos?}
{487}{}{Van nálad törülköző? Az egyik színész egy kis... balesetet szenvedett.}
{488}{}{Ha nem harapod meg a színészt, nem lesz semmi gond.}
{489}{}{Néhány színész igazán zuhanyozhatna. Úgy értem, rendszeresen.}
{490}{}{Ööö... új vagy itt?}
{491}{}{Trutyi? Hát szokj hozzá?}
{500}{}{Bocs, de inkább nem. A rúzsommal jobbat tudnék szexelni.}
{501}{}{Veled? Bocs, de ekkora hiányom azért nincs.}
{502}{}{Nem láttam a Testvéreket errefelé... próbálkozz az irodában!}
{503}{}{A tutajosoknak az a feladata, hogy a színészek merevek maradjanak.}
{504}{}{Minden vágyam, hogy színésznő legyek.}
{505}{}{Egész életemben azért nem akarok tutajos maradni. Akar a fene.}
{506}{}{A barátom nem tudja, hogy itt dolgozom.}
{507}{}{Körbevezettek már?}
{508}{}{Ha munka kell, beszélj a Testvérekkel!}
{509}{}{Azért csinálom ezt, hogy ki tudjam fizetni a tandíjat.}
{510}{}{Avellone-t ingyen is lecummantanám.}
{511}{}{Nem mintha nem akarnék veled beszélgetni, de... tulképpen, tényleg nem akarok.}
{512}{}{Valaki megdönthetne.}
{513}{}{Obi? Máskor majd kivesézhetjük.}
{514}{}{Ugye nem viszolyogsz a disznó filmektől?}
{515}{}{Te vagy az új tutajos?}
{516}{}{Van nálad törülköző? Az egyik színész egy kis... balesetet szenvedett.}
{517}{}{Ha nem harapod meg a színészt, nem lesz semmi gond.}
{518}{}{Néhány színész igazán zuhanyozhatna. Úgy értem, rendszeresen.}
{519}{}{Ööö... új vagy itt?}
{520}{}{Trutyi? Hát szokj hozzá?}
{1200}{}{. Ő az, aki picsán rúgta az Enklávésokat!}
{1204}{}{! Jó munka volt seggbe rúgni az Enklávét!}
{1207}{}{. Ő az, aki picsán rúgta az Enklávésokat!}
{1235}{}{ barátoddal?}
{1236}{}{. menet!}
{1238}{}{. menet!}
{1239}{}{ dollár.}
{1245}{}{ barátoddal?}
{1255}{}{ dollár.}
{1270}{}{ dollár.}
{1280}{}{ dollár.}
{1290}{}{ dollár.}
{1374}{}{ barátoddal?}
{1378}{}{. menet!}
{1381}{}{ barátoddal?}
