{100}{}{Ez itt Mordino egyik embere.}
{101}{}{? Ramirez.}
{150}{}{Egy napbarnított férfit látsz. Állát borosta borítja, a b?re pedig hámlik. Idegesen nézeget körbe-körbe.}
{151}{}{Ez itt Mordino egyik embere.}
{152}{}{Ez itt Mordino egyik embere. Egy kicsit izgatottnak t?nik.}
{153}{}{Ez itt Mordino egyik embere. Meglehet?sen ideges.}
{154}{}{Ez itt Mordino egyik embere. Szemlátomást nem aludt már egy ideje.}
{160}{}{Egy tüskés hajú, sunyi kinézet? embert látsz. Idegesen néz körbe-körbe.}
{200}{}{Hela! }
{201}{}{Azt a kibebaszott mindenedet, }
{202}{}{::Hüvelykjével mutatja, hogy minden rendben::}
{203}{}{::Fütyül::}
{205}{}{Hogy tudsz pisálni, ha rajtad van az a pléhvacak?}
{210}{}{Jól el vagy látva, }
{215}{}{Mi ez a nagy lopódzkodás, }
{220}{}{Van nálad egy kis Jet, homes?}
{221}{}{Hé, }
{222}{}{Hát elfogadnék egy italt, basszus...}
{223}{}{Öcsééém, nagyon meleg van!}
{224}{}{Valami hír a nagykutyáktól, }
{230}{}{Mi van, Cabron? A halál angyalát keresed? Kopj le!}
{231}{}{Mi a fa... Mit csinálsz te itt?}
{232}{}{Na, mi van puta? A halál angyalát keresed? T?nés innen!}
{235}{}{Hela, hombre! Sajnálom, de azt a fegyvert nem hordhatod idebenn!}
{236}{}{Hela, homes! Rakd el azt a fegyvert, miel?tt felmegy itt az emberek agyvize!}
{240}{}{Hela, Chica! Azzal a fegyverrel nem mászkálhatsz nálunk.}
{241}{}{Hela, Chica! Rakd el azt a fegyvert, miel?tt felmegy itt az emberek agyvize!}
{245}{}{Mi a francnak lopakodsz, }
{250}{}{Minek lopakodsz, chica? Azzal a jobb horoggal, amit te tudsz ütni, emelt f?vel járhatsz köztünk.}
{255}{}{Hol tanultál bunyózni, }
{256}{}{Ez a cojones bármikor egy Mordino becsületére válna!}
{257}{}{Mesébe ill? volt az utolsó bunyód, hombre.}
{258}{}{Vigyázz a Húsdarálóval! Legszívesebben füleket eszik.}
{259}{}{Pillekönny? mozgás, szúrós fullánk. Na, ez vagy te, }
{260}{}{Régen én is bokszoltam, de lesérült a karom, és abba kellett hagynom.}
{261}{}{Hát bizony elkelne egy hozzád hasonló ember a Mordino családnál, }
{262}{}{Honnan jössz, hogy így tudsz bunyózni? Nagyon jól csinálod, NAGYON JÓL!}
{263}{}{Ha munkát akarsz, keresd meg Kis Jesust!}
{264}{}{Rád fogadtam, és bizony a legjobb helyre tettem a pénzem. Úgy nyomod le az embereket, ahogy senki más.}
{265}{}{Láttalak a ringben bunyózni, }
{266}{}{Mennyit nyomsz fekve, }
{267}{}{Hol edzel, mi?}
{268}{}{Meghívnálak egy italra, de az ellenfeledre fogadtam, és elbuktam az összes pénzem.}
{269}{}{Hol tanultál bunyózni, chica? Durva, amit csinálsz. Nagyon jó mozgásod van.}
{270}{}{Beillenél közénk.}
{271}{}{Az utolsó bunyód mesébe ill? volt, chica.}
{272}{}{Hol edzel, mi? Nem kell egy segéd?}
{273}{}{Vigyázz a Húsdarálóval! Legszívesebben füleket eszik... beteg az az ember.}
{280}{}{Hey, hey, hey! Chica, you need me to put that weapon away for you?}
{281}{}{Azt akarod, hogy megmotozzalak, vagy mi? Gyerünk, tedd el azt a fegyvert, miel?tt felmegy bennem a pumpa!}
{285}{}{Mi a francnak lopakodsz, }
{290}{}{Chica, ezzel a karosszériával nem fogsz észrevétlenül elosonni egy Mordino el?tt.}
{295}{}{A filmed nem volt rossz, de azért egy-két jelenetet fel tudnék dobni.}
{296}{}{Mondj már rólam egy-két jó szót a Testvéreknek!}
{297}{}{Hé, }
{298}{}{Én készen állok, ráérek, filmezzünk, oké? Mozira gondoltam, }
{299}{}{Én vagyok a mindenkit felülmúló latin szeret?. Hozzám hasonlót sehol nem találsz.}
{300}{}{Beszélnél a Testvérekkel az érdekemben?}
{301}{}{Úgy hallottam, Tökös Tomi magánvetítésre vár téged.}
{302}{}{Mi lenne, ha mi ketten csinálnánk egy filmet? Jól fogok bánni veled, chica, megmutatom, mit tud egy latin szeret?.}
{303}{}{Miért nem ugrasz be munka után?}
{304}{}{Van barátod?}
{305}{}{Okos dolog, hogy egy követ fújsz a Mordinókkal. Nekünk van jöv?nk.}
{306}{}{Nem kell egy kis Jet? Én el tudlak látni, chica.}
{307}{}{Chica, nincs olyan dolog, amit ne tennék meg érted... gyere már ide! Aggggy egy csókot!}
{308}{}{Need some drugs? Hootch? Some chips? I can set you up. I'm co-nnected, see?}
{315}{}{Ne hadonássz itt a fegyvereddel, barátom! Rakd el gyorsan!}
{320}{}{Ne osongass itt, hajcsár, oké? Itt barátok közt vagy!}
{325}{}{Te ott! Megsüketültél vagy mi a szar? Rakd el azt a vackot, mert bántani foglak!}
{326}{}{Megszabadítsalak attól a kevés agyadtól? Tedd el azt a fegyvert!}
{327}{}{Te ott, chica! Megsüketültél, vagy mi a szar? Rakd el azt a vackot, mert bántani foglak!}
{330}{}{Mi a francnak lopódzol itt? Golyót akarsz a hátadba?}
{335}{}{Mi a francnak lopódzol itt, chica? Golyót akarsz a hátadba?}
{340}{}{Vidd innen azt a guruló hulladékot!}
{341}{}{Robotok nem jöhetnek ide! Vidd innen a francba!}
{342}{}{Ha az a robot ittmarad, ócskavasat csinálunk bel?le!}
{345}{}{Csak jól éreztem, hogy egy MUTÁNS jött ide. Vidd innen, miel?tt mérges leszek!}
{346}{}{Ki vagy te? Mutánsbérenc? Annak a valaminek a helye odakinn van! Nem mondom kétszer...}
{347}{}{Az a mutáns ott céltábla akar lenni? Csak lófráljatok még itt egy kicsit, és valóra váltjuk az álmát.}
{350}{}{Csak jól éreztem, hogy valami rohad! Vidd ki innen a ghoul barátodat, de rögtön!}
{351}{}{Most azonnal vidd innen azt a büdös ghoult!}
{352}{}{Ha az a ghoul még egy percig itt marad, halottabb lesz, mint amennyire máris az.}
{355}{}{Én f?szerepere mentem meghallgatásra, de csak ezt a jelentéktelen mellékszerepet kaptam. Remélem, nem fognak beskatulyázni.}
{356}{}{New Renót Chris Avellone tervezte és Tom French szkriptelte. Mindkett? tisztára beteg ember.}
{357}{}{Hela! }
{358}{}{Azt a kibebaszott mindenedet, }
{359}{}{Úgy hallottam, a Korzikai Testvérek beszélni akarnak veled.}
{360}{}{Azt hittem, az Elnök csak legenda.}
{361}{}{Úgy nézel ki, mint aki megjárta a poklot. Lazíts, megérdemled!}
{362}{}{Ember, azok az Enklávés barmok szerencsésnek tarthatják magukat, hogy nem kötözködtek a Mordinókkal.}
{370}{}{Van nálad egy kis Jet, homes?}
{371}{}{Na, mi az ábra? Nálunk olyan, mint mindig.}
{372}{}{Heh... ::Köp egyet:: Na, mi van, }
{373}{}{Jó, hogy újra látunk!}
{374}{}{Hát elfogadnék egy italt, basszus...}
{375}{}{Öregesen vagyunk, öregesen. Veled mi a helyzet, }
{376}{}{Öcsééém, nagyon meleg van!}
{377}{}{A Nagy Mordino jól elvan? Mondd meg neki, hogy benézek hozzá, }
{378}{}{Kinyírtam egy skorpit tegnap éjjel. Majdnem megmart, basszus!}
{379}{}{A Bishopok folyton csak kekeckednek velünk, de a csontkukacok fogják ?ket felzabálni, nem igaz?}
{380}{}{Valami hír a nagykutyáktól, }
{381}{}{Mikor nyomjuk le a Bishopokat, mi? Még a végén berozsdásodik a fegyverem.}
{382}{}{A Salvatorék úgy flangálnak fel-alá, mintha övék lenne Reno. Vissza kéne menniük az iskolapadba!}
{383}{}{Azt hallottam, hogy Tökös Tomi megint a városban van. Jobb, ha meghúzod magad!}
{384}{}{Van nálad egy kis Jet, chica? Majd meghalok nélküle.}
{400}{}{Néhány cojone idetolta a képét. Ajánlom, hogy küldd el ?ket!}
{401}{}{A kinézeted alapján az anyádat kutyaólban kellett, hogy tartsák.}
{402}{}{Úgy nézel ki, mint aki nem tudja, mikor fog meghalni.}
{403}{}{Hijo de puta...}
{404}{}{Hozzám beszélsz? Hozzám beszélsz?}
{405}{}{Ha még egyszer idejössz, annyi ólmot eresztek beléd, hogy még a Superman se lesz képes átlátni rajtad.}
{406}{}{::Leköpi a lábad::}
{407}{}{Mit gondolsz, csak úgy odasétálhatsz egy Mordinóhoz és beszélgetni kezdhetsz vele? Húzz a retekbe!}
{408}{}{Ha még egyszer hozzám szólsz, kiirtom a családodat, leölöm a kutyádat, aztán elvágom a nyakad.}
{409}{}{::Leköpi a lábad::}
{410}{}{Mit gondolsz, csak úgy odasétálhatsz egy Mordinóhoz és beszélgetni kezdhetsz vele? Húzz a retekbe!}
{411}{}{Ha még egyszer idejössz, annyi ólmot eresztek beléd, hogy még a Superman se lesz képes átlátni rajtad.}
{412}{}{Nem volna jobb ha visszamennél a kutyaóladba, puta?}
{413}{}{Ha szóba mersz állni velem. te vagy a leghülyébb puta az egész világon!}
{414}{}{Hija de puta...}
{420}{}{Nem velem kell beszélni rabszolgák ügyében... Kis Jesus majd eligazít.}
{421}{}{Mikor hozol már jóféle rabszolgákat? Az utolsó eresztés elég siralmas volt, hajcsár. Gagyi.}
{422}{}{A Mordinóknak nem kell rabszolga a boldoguláshoz. Persze, ha van felesleges árud...}
{423}{}{Rabszolga-vásárlás ügyben nem velem kell tárgyalni.}
{424}{}{Okos dolog, hogy egy követ fújsz a Mordinókkal. Nekünk van jöv?nk.}
{425}{}{Hogy mennek a dolgok Rejtekben, mi?}
{430}{}{Munkát akarsz? Keresd Kis Jesust!}
{435}{}{Figyelj, nem vagyok én a compadréd, szóval meg ne szólíts többet!}
{436}{}{A Mordinók csak Mordinókkal barátkoznak. Szóval lehet lekopni, ?stulok!}
{437}{}{Lehet lekopni, vadember!}
{438}{}{Most NINCS id?m rád!}
{439}{}{T?nj innen!}
{440}{}{Mocskos vadember...}
{441}{}{Mi a szart akarsz, vadember?}
{442}{}{Most NINCS id?m rád!}
{443}{}{Kopás van!}
{444}{}{Mocskos vadember...}
{445}{}{Akármennyit is könyörögsz, nem adok egy deka Jetet sem. Húzz innen!}
{446}{}{Figyelj ide, nem vagyok én a testvéred, szóval ne szólíts meg többet!}
{447}{}{Nézd, ha kurva kell, megyek és megveszem magamnak. Tehát lehet lelépni, chica!}
{448}{}{A Mordinók csak Mordinókkal barátkoznak. Húzd el a beled, puta!}
{449}{}{Húzd el a beled, puta!}
{460}{}{(Ahogy közeledsz felé, végigmér és kaján arcot vág.) Keresed a bajt, homes?}
{461}{}{(Ahogy közeledsz felé, végigmér és kaján arcot vág.) Keresed a bajt, chica?}
{462}{}{Te vagy Ramirez? Nagy Jesus ezt a csomagot küldte neked.}
{463}{}{Nincs gond. Megyek is.}
{470}{}{(Átveszi a dobozt.) Na, végre. Már majdnem kifogytunk a Jetb?l. (Szipog, és kissé köhög hozzá.) Van fogalmad, hova vezet ez... mi?}
{471}{}{Hát bizony én résen lennék a helyedben...}
{472}{}{A Jetes köhögésedet meg az orrdörzsölésedet figyelembe véve van róla elképzelésem, mi lesz a Jet-szállítmány sorsa.}
{473}{}{Nagy J volna az aki tör?dik velünk, mi? Csak a múlt héten három rabszolgát kaptam el, akik voltak olyan ostobák, hogy elszökjenek. Vajon kaptam-e jutalmat? Heh. Kaptam a szart. Itt nyugodtan megszakadhatsz. Pedig én ?R vagyok.}
{474}{}{Igen, nagyszer?. Mostantól jobb, ha vigyázol magadra!}
{475}{}{I wonder if Big Jesus realizes how those three slaves might have escaped under the NOSES of such perceptive, Jet-addicted
 guards such as yourself.}
{476}{}{Ramirez... vigyázz, hogy mit mondasz nekem, oké? Nehogy eljárjon a szád, és bajba keveredj!}
{480}{}{(Pislog.) Öö...? Mi van?}
{481}{}{Semmi olyat nem mondtam, amit értenél vagy megérné megismételni. Légy résen, oké?}
{482}{}{I said, "I wonder if Big Jesus realizes how those slaves might have escaped under the NOSES of such
 perceptive, Jet-addicted guards such as yourself."}
{490}{}{(Pislog és zavartan mosolyog.) Öö... Igen, igen. Agyas vagyok, persze... élesszem?... ?R vagyok, nemde?}
{491}{}{Igen, ezt már mondtad korábban. A helyedben, Ramirez, tennék az emberiségnek egy szívességet, és egyszerre bevenném azt az egész doboz Jetet. Na, ég áldjon!}
{492}{}{Hát barátom, jó, hogy valaki volt olyan bölcs és nem adott neked teljesen automata fegyvereket. Sokkal biztonságosabban érzem magam. Na, viszlát, Ramirez.}
{493}{}{(Pislog.) Öö...? Mi van?}
{494}{}{Felejtsd el! Eridj, ölelgess egy l?fegyvert és húzd meg a ravaszt, oké?}
{495}{}{Semmit. A helyedben, Ramirez, tennék az emberiségnek egy szívességet, és egyszerre bevenném azt az egész doboz Jetet. Na, ég áldjon!}
{496}{}{(Te is indulsz a dolgodra.)}
{500}{}{(Ahogy megfordulsz, Ramirez felhördül.) Hé! Ezt a dobozt kinyitották!}
{501}{}{Lenyúlsz, homes?}
{502}{}{Lenyúlsz, chica?}
{503}{}{Senki nem kekeckedhet Ramirez-zel, hallod?!}
{504}{}{Persze, hogy hallom, de már nem sokáig.}
{505}{}{Elég gyengére sikerült utolsó szavak ezek, Ramirez.}
{600}{}{Elvitted Nagy Jesus csomagját Ramirez-nek.}
{1200}{}{. Szép munka volt valagba rúgni az Enklávés fiúkat!}
{1201}{}{, királyul megtanítottad azokat az Enklávés gyíkokat, hogy mennek a dolgok a KÜLVÁROSBAN.}
{1210}{}{ vagyok.}
{1215}{}{? A Mordinók emelt f?vel járnak.}
{1221}{}{! Que pasa?}
{1224}{}{?}
{1245}{}{? Amilyen jobbhorgokat te tudsz ütni, nyugodtan járhatsz itt emelt f?vel.}
{1255}{}{? Durva, amit csinálsz. Nagyon jó mozgásod van, homes.}
{1259}{}{ vagyok.}
{1261}{}{. Ha meglát a többi család, egy szempillantás alatt be fognak rosálni.}
{1263}{}{ vagyok.}
{1265}{}{. Azt a fickót LEMOSTAD a pályáról!}
{1266}{}{?}
{1285}{}{? Ugyan már, járj emelt f?vel!}
{1297}{}{! Que pasa? Összehozol a Testvérekkel engem, vagy mi lesz?}
{1298}{}{, jöhet a mozi!}
{1300}{}{... ugyan már! Én KÉPES vagyok rá!}
{1357}{}{. Szép munka volt valagba rúgni az Enklávés fiúkat!}
{1358}{}{, királyul megtanítottad azokat az Enklávés gyíkokat, hogy mennek a dolgok a KÜLVÁROSBAN.}
{1372}{}{?}
{1373}{}{. Hol voltál?}
{1375}{}{?}
{1377}{}{?}
{1380}{}{?}
