{100}{}{Ez itt egy jópofa "kis ember."}
{101}{}{Ez itt Stuart Little.}
{150}{}{Ez egy gyerekruhába öltözött törpe. Egy fogpiszkálót rágcsálva néz vissza rád.}
{151}{}{? Stuart Little, a törpe bokszmenedzser. Egy fogpiszkálót rágcsálva néz vissza rád.}
{152}{}{? Stuart Little, a törpe bokszmenedzser. Nagyon aranyos. Olyan, mint egy vörös sz?r? plüssmaci.}
{200}{}{Kölyök, tudom, hogy jól nyomod, de azt azért nem gondoltam volna, hogy még a világot is megmented. Jó munka volt!}
{201}{}{Büszke vagyok rád, kölyök.}
{202}{}{Megjártad a hadak útját, kölyök. Stuart nagyon büszke rád.}
{210}{}{Bárcsak láttam volna, ahogy szétütöd az Enklávét.}
{211}{}{A jó életbe! Az Enklávé elleni csata nem lehetett semmi!}
{212}{}{Hah! Nem akarod esetleg a ringben is kamatoztatni az agilitásodat, és nem csak a világ megmentésére pazarolni a tehetséged javát?}
{220}{}{Mi a nagy helyzet, bajnok?}
{221}{}{Jól nézel ki, hallod-e!}
{222}{}{Az ökleid aranyból vannak!}
{223}{}{Villámot eszel és mennydörgést szarsz, kölyök!}
{224}{}{You dropped that sonuvabitch like a bad habit. Good job.}
{225}{}{Örülök, hogy kipróbáltalak, drágám!}
{226}{}{Jól nézel ki, kedvesem!}
{230}{}{Kéne valami új tehetség...}
{231}{}{Ólomsegg?ek gyülekezete...}
{232}{}{Bárcsak egy kicsit magasabb lennék...}
{233}{}{Ezek a srácok, egyt?l-egyig úgy verekszenek, mint a csövesek...}
{240}{}{(Ahogy odamész hozzá, a törpe végigmér és kiveszi a fogpiszkálót a szájából.) }
{241}{}{Igen, mit akarsz, nagyfiú?}
{242}{}{Mit tehetek érted, kedvesem?}
{243}{}{Üdv, h?söm! Mit tehetek érted?}
{244}{}{Hönh?}
{245}{}{Miért lenni kicsike?}
{246}{}{[Wander off.]}
{247}{}{Ki vagy te?}
{248}{}{Semmi-semmi... csak körbenéztem errefelé.}
{250}{}{(Beint egyet.) Na, akkor kopj le, seggfej! Csak az id?met pazarlod!}
{251}{}{Bzzzzzzz-bzzzzzz}
{260}{}{(Sóhajt egyet, úgy néz ki, mondana valamit, aztán végigmér.) Te verekszel? Elég fittnek nézel ki.}
{261}{}{Én harcol SOKSZOR. Én harcol veled?}
{262}{}{Én nem lenni csinos. Fiúkat szeret? Vagyok benne}
{270}{}{Nem, nem... a RINGBEN bunyózz! Tudod... RING! (Rámutat a szorítóra, és ütöget néhányat a leveg?be.) Érdekel a dolog?}
{271}{}{(Arcul ütöd az apró embert és elveszed az ebédpénzét)}
{272}{}{[Bólogatsz]}
{273}{}{Kapok jégkrém ha verekszek?}
{274}{}{[Ingatod a fejed]}
{275}{}{Enyim házastársa a kaland én menni}
{280}{}{(Hátraugrik.) Vigyázz, seggfej! Ez ráér majd a ringben. Szóval beszállsz, vagy sem?}
{281}{}{Beszáll}
{283}{}{Nem száll befele}
{290}{}{(Mosolyog.) Rendben van, akkor megegyeztünk. A nevem Stuart, a legtöbben Stuart Little-nek hívnak, de ez csak azért van, mert... mindegy, ez nem fontos, a lényeg, hogy én vagyok itt a f?mandró. Van neved, seggfej?}
{291}{}{Én }
{292}{}{Me... uh... me...}
{293}{}{Én Nagy Stu}
{296}{}{[Wander away in search of adventure.]}
{300}{}{Én-öö-Én, mi? "Él? Fény..." TETSZIK! TETSZIK! Rendben van, akkor csapjunk a lovak közé!}
{301}{}{(Homlokát ráncolja.) Túlteng a bölcsesség benned, mi? Hmmm... nem adnak kell? tiszteletet a városban. (Vállat von.) Rendben van, akkor csapjunk a lovak közé!}
{302}{}{Na}
{305}{}{[Run away and hide.]}
{310}{}{(Sért?dötten felfújja magát.) Idefigyelj! Csak azért, mert nem tartozom az úgynevezett "átlagos magasságúak" közé, nem jelenti azt, hogy t?rnöm kéne a toszogatást.}
{311}{}{Csakugyan?}
{320}{}{Na, t?nj innen, seggfej! Ne is reménykedj, hogy viszed valamire a városban! T?nés!}
{321}{}{NEM SZABAD LETT VOLNA kockáztatnom veled! Micsoda elcseszett balfék vagy te! Na, most aztán t?nés a szemem el?l! Ne is lássalak!}
{322}{}{ÉN }
{323}{}{Hol van jégkrém?}
{324}{}{[Run off crying.]}
{326}{}{[Smile calmly, nod, then attack him.]}
{327}{}{Adj még egy esélyt, Stuart! Légyszíves, csak egy picike esélyt! Nem hagylak cserben!}
{328}{}{[Leave.]}
{329}{}{(Miközben kipenderítenek a ringb?l, Stuart undorodva néz feléd.) }
{330}{}{Micsoda? A Húsdaráló leharapta a füled, fiam? }
{331}{}{Micsoda? A Húsdaráló leharapta a füled, lányom? }
{332}{}{Azt mondtam, T?NÉS A SZEMEM EL?L! Ki innen!}
{333}{}{[Kick the loud red little man.]}
{334}{}{[Tromp out angrily.]}
{336}{}{[Hit the road.]}
{337}{}{(Céklavörös lesz.) }
{340}{}{One more chance. I get 75%, no arguments. }
{341}{}{One more chance. I still get 75%, no arguments. }
{342}{}{Legyen. Készen állok a meccsre most azonnal. Menjünk, Stuart!}
{343}{}{Legyen. Hadd pihenjek egy kicsit, hamarosan újra készen állok majd.}
{344}{}{Semmi nem éri meg ezt a rengeteg szívást.}
{345}{}{(Stuart céklavörös lesz, úgy néz ki, mint aki rögtön üvöltözni kezd, aztán lenyugszik.) Rendbe'. }
{346}{}{Csak még egyszer sülj fel, úgy kipenderítelek innen...}
{350}{}{(Stuart sakál módjára mosolyog.) Hát ez eszméletlen jó teljesítmény volt, }
{351}{}{Most én készen KÉSZEN SZÉTÜTÖK MINDEN MOST MOST}
{352}{}{Én alszik kicsit aztán harc újra}
{353}{}{Én akar kis jégkrém}
{355}{}{Készen állok. Jöjjön az üzlet.}
{356}{}{Hadd pihenjek egy kicsit, aztán jöhet a mehet.}
{357}{}{Asszem, én kész vagyok, Stuart... meghaltam a ringben, és ez kiakaszt engem. Szögre akasztom a keszty?t.}
{360}{}{(A törpe pislog, aztán összevonja a szemöldökét.) Jég... micsodát?}
{361}{}{Jégrém, jégrém, mindenki kéri a jégkrém}
{362}{}{Öö... öö... Jég KRÉM}
{363}{}{[Wander off in search of adventure.]}
{370}{}{(A törpe kényszeredetten mosolyog.) }
{371}{}{Well, I can get you some cream, pal... mostly of the whore or drug variety... but that's about it. }
{372}{}{Well, I can get you some cream, honey... mostly of the male prostitute or drug variety... but that's about it. }
{373}{}{Most akkor bunyózol vagy mi lesz?}
{374}{}{Oké}
{375}{}{Én akar pihenni kicsit el?bb}
{376}{}{Neem}
{380}{}{Hát er?ltetni nem fogom, de pazar kis üzlet lett volna, száguldás a hírnév felé, igazi égi f?nyeremény... majd gyere vissza, ha meggondoltad magad. Te ugyanis aranyat érsz, kölyök.}
{390}{}{Akkor rendben! Kezd?djék a cirkusz!}
{391}{}{[Follow him.]}
{400}{}{Mi a... nem hallottad, amit mondtam? Stuart, Stuart Little. A legnagyobb menedzser egész Renóban! }
{401}{}{Valaki jól kicseszett veled, haver, hogy nem mesélt el?re rólam. }
{402}{}{Valaki jól kicseszett veled, drágám, hogy nem mesélt el?re rólam. }
{404}{}{Hmmm. Szóval... Mi is a neved?}
{405}{}{Én }
{407}{}{Dolgoztál már cirkuszban, Stuart?}
{408}{}{"Stuart Little?"}
{409}{}{A lábamon kívül azért egy kicsit több dolog is van rajtam, Stuart. Szóval légy udvariasabb, különben még a szokásosnál is nehezebben fogsz randizni ebben a városban! Megegyeztünk?}
{410}{}{Tulképpen csak épp körbenéztem. Kés?bb még beugrom, Stuart.}
{411}{}{(Visszateszi a fogpiszkálót a szájába, és tovább rágódik rajta.) Neved van?}
{412}{}{(Tet?t?l talpig végigmér.) Ezekhez a lábakhoz valami név is jár?}
{420}{}{(Stuart bólogat.) }
{421}{}{Rendbe' van, }
{422}{}{... }
{423}{}{Mit tehetek magáért?}
{424}{}{Bokszolni akarok. Tudsz segíteni rajtam?}
{430}{}{(Ahogy közeledsz, Stuart bólogat és mosolyog.) Hé, h?söm! Hallottam, mit csináltál. Fogadd gratulációimat! Amúgy mi a helyzet?}
{431}{}{(Ahogy közeledsz, Stuart bólogat és mosolyog.) Héééé, }
{432}{}{(Ahogy közeledsz, Stuart csak bámul.) Megáll az ész, ez itt "}
{433}{}{Én akarja harc megin}
{434}{}{Azég. 'szlááát.}
{435}{}{Készen állok az ütésváltásra!}
{436}{}{Adj még egy esélyt, Stuart! Nem hagylak cserben! Kérlek...}
{437}{}{Semmit nem akarok. Csak úgy körülnéztem.}
{440}{}{Bokszolni akarsz? Ööö... rendbe', hadd legyek ?szinte, kölyök. Egyszer?en nincs meg hozzá az alkatod.}
{441}{}{Bokszolni akarsz? Rendbe', mindent tudok. A n?knek szánt renói állások többsége, hogyismondjam csak... hmmm. Szóval ahogy így megnézlek, lehet, hogy nem neked találták ki azokat.}
{442}{}{Bokszolni akarsz? Rendbe', mindent tudok. Nem akarok itt szemétkedni vagy valami, de a boksz CSÚNYA sport... és hát a bokszolók is egyre csúnyábbak lesznek. A te esetedben ez nagy szó lenne.}
{444}{}{Adj egy esélyt, és elfelejtem ezt a KIS beszólásodat!}
{445}{}{Adj egy esélyt, Stuart!}
{446}{}{Na, jó, hagyjuk ezt a brahminfost! T?nök a francba innen.}
{450}{}{Nem, sajnálom, kedvesem, túl nagy a kockázat... ami azt illeti, be sem engednének a ringbe. Inkább menj haza, oké?}
{451}{}{Nem, sajnálom, barátom, túl nagy kockázat lenne... mészárlássá fajulna. Na, menj haza, oké?}
{452}{}{Nincsenek n?i ökölvívók, Stuart, és én erre apellálok. Te leszel az els? menedzser, aki egy n?i bokszolót futtat. Az emberek ÖZÖNLENI fognak, hogy lássák.}
{453}{}{Valszeg így van ez, Stu... ugye hívhatlak Stu-nak? ...mészárlás lenne, valóban. És tudod, mennyire vonzza az embereket a mészárlás? Olyan lenne, mintha kivégzést néznének az emberek!}
{454}{}{Ez egy rakás brahminfos. Húzok a francba.}
{460}{}{Nem, sajnálom, kedvesem, túl nagy a kockázat... ami azt illeti, be sem engednének a ringbe. Inkább menj haza, oké?}
{461}{}{Nem, sajnálom, barátom, az a mészárlás nem lenne szórakoztató. Inkább menj haza, oké?}
{462}{}{Kockázatos, tudom... de hát tudod, Stuart, egy kicsit akár "alulöltözött" is lehetnék a ringben. Alkalomadtán ez nagyobb tömeget vonzana, mint amihez hozzá vagy szokva...}
{463}{}{Ez egy rakás brahminfos. Húzok a francba.}
{470}{}{Hmmmm... rendbe', adok egy esélyt... de nem ígérek semmit. Ha ez megárt a üzletnek, akármilyen kicsit is, repülsz. (Csíp?re teszi a kezét.) A nyeremény fele az enyém, és nincs vita!}
{471}{}{Hmmmm... rendbe', adok egy esélyt... de nem ígérek semmit. Azzal, hogy egy zöldfül?t bevállalok, szívességet teszek. A nyeremény fele az enyém, vita pedig nincs!}
{472}{}{Megbeszéltük.}
{473}{}{Legyen 25 százalék és megegyeztünk.}
{474}{}{Ez egy rakás brahminfos. Húzok a francba.}
{480}{}{(Stuart még a szokásosnál is jobban összehúzza a szemöldökét. Úgy néz ki, mint aki épp tiltakozni készül, aztán önelégülten megrázza a fejét.) Minek is vitatkoznánk... Ha végeztél a megkopasztásommal, akár az üzletr?l is beszélhetnénk.}
{481}{}{Okay...}
{490}{}{Rendbe'... (Stuart végigmér.) Szükséged lesz egy névre, tudod, egy becenévre. Valami dögös, jól hangzó név kell neked, mint például }
{500}{}{(A törpe komor arcot vág.) ? nem halt meg, amikor azzal az Orosz fickóval bunyózott? Nem mintha számítana. Mehetünk a ringbe?}
{501}{}{(The midget smirks.) Looks like you and the "Masticator" will be getting along just fine. Just don't bite off too many
 ears. Well... shall we hit the ring?}
{502}{}{(A törpe önelégült arcot vág.) Nem nézel ki Orosznak. Mondjuk tökmindegy, mi hajt... mehetünk a ringbe?}
{503}{}{(A törpe önelégült arcot vág.) Megesett a szíved a szegény bolondon, mi? Na, jó... reméljük, a karriered nem fut zátonyra. Indulhatunk a ringbe?}
{504}{}{(A törpe önelégült arcot vág.) Eye of the Tiger, mi? "Adrian," "Aaaadrian..." Hehe. Tetszik... jó nagy izomkötegek vannak benne. Na, mindegy... mehetünk a ringbe?}
{505}{}{(A törpe bólint.) }
{506}{}{Csináljuk!}
{510}{}{Ne már! Fifti-fifti, vagy SEMMI! Ha nem tetszik, megyek a dolgomra.}
{511}{}{Legyen! Azt azért nem gondoltam volna, hogy ilyen nagyra n?tt vámpírok léteznek.}
{512}{}{Oké. 50/50. És most?}
{513}{}{25/75-öt mondtam volna? Valójában ötven-ötven-re gondoltam. A profitot szépen megosztjuk, nincs itt semmi probléma.}
{514}{}{[Walk.]}
{520}{}{Igen, igen, tudom, mi a gondod a "Stuart Little" névvel. Az anyám csak úgy falta E. B. White m?veit. Egyébként téged hogy hívnak?}
{521}{}{Hmmmm. Van valami neved?}
{526}{}{Örülök, hogy összehozott bennünket a sors, Stu. Sajnos most nem tudunk beszélgetni, de kés?bb még találkozunk.}
{530}{}{Aztán mib?l gondolod, hogy láttam valaha is cirkuszt, ráadásul még a tagja is voltam egynek?}
{531}{}{Ööö... hát azt tudom, hogy New Reno polgárainak zöme úgy viselkedik, mintha épp most szalajtották volna a cirkuszból, ezért gondoltam, hogy...}
{540}{}{Azt hiszed, attól, hogy kisnövés? vagyok, egyedül csak az úgynevezett csúcsszakmákat m?velhetem?}
{541}{}{Uh... well, now...}
{550}{}{Azt hiszed, egy gyors pillantásból az egész életemet megítélheted? A világért sem jutna az eszedbe, hogy egy ilyen magasságú ember esetleg a Boksz Menedzsmentben is érvényesülhessen?}
{551}{}{Elnézést, nem akartalak megbántani.}
{560}{}{Miért kéne megsért?dnöm? Azért talán, mert szemlátomást mindenki azt a jó szokást vette itt fel magára, hogy az NJK-król csak úgy futó véleményt lehet alkotni a külseje alapján?}
{561}{}{Hát én nem tudok semmiféle futó véleményr?l...}
{570}{}{Én például ugyanezt csináltam veled.}
{571}{}{Tényleg?}
{580}{}{(Könyörg?en néz rád.) Érzed a TRAGÉDIA mibenlétét? Véletlenül egy sztereotíp, karikatúra-jelleg?, közhelyes Fallout típusnak néztelek ahelyett, hogy egy egyedülálló, jellegzetes karaktert láttam volna benned.}
{581}{}{Ö..., de hát, Stuart, én egy tipikus h?stípus vagyok. Az a helyzet, hogy én vagyok ennek a játéknak a f?szerepl?je.}
{590}{}{Nem minden n?t vonzanak a kidolgozott fels?test?, hatalmas izomzatú férfi modellek. Egész meglep?dnél, milyen sok n? bukik az ilyen apró termetre.}
{591}{}{Azon is meglep?dnél, milyen sok férfi bukna rá.}
{600}{}{Bed?ltem a nevetségesen túlizmosított alkatodnak, a k?kemény Mad Max koppintó stílusodnak, a minden leleményt nélkülöz? karakterpont felhasználásodnak és arra a végeredményre jutottam, hogy egy közönséges tápos disznó vagy.}
{601}{}{I've taken in your over-pixilated breasts, your ridiculous sashay when you walk, your unimaginative character point
 allocation and concluded you are a mini-maxing Laura Kroft wannabe... a "munchkin."}
{602}{}{I...}
{610}{}{Nem vagy egyéb, mint egy tipikus RPG férfi h?s, vagy ha jobban tetszik, egy olyasféle modell, amelyb?l Dunát lehet rekeszteni ebben a világban.}
{611}{}{Nem vagy egyéb, mint egy tipikus RPG h?sn?, vagy ha jobban tetszik, egy olyasféle modell, amelyb?l Dunát lehet rekeszteni ebben a világban.}
{612}{}{Nos...}
{1302}{}{ barátom, csapjunk a lovak közé!}
{1322}{}{ NEM SEGGFEJ ÉN ÖL MEG ÉN ÖL MEG ÉN ÖL MEG ÉN...}
{1350}{}{! Minden rendben amúgy? Jól érzed magad? Majd szólj, mikor állsz készen a következ? mérk?zésre!}
{1405}{}{ vagyok.}
{1406}{}{, és bokszolni szeretnék. Tudsz segíteni?}
{1421}{}{. Örülök, hogy talá'koztunk. }
{1422}{}{... tetszik. Jó kis név. Hát légy üdvözölve minálunk. }
{1431}{}{! What's up? Ready to get back in the ring?}
{1432}{}{." Mi hozott téged errefelé?}
{1490}{}{ a Hurrikán, }
{2490}{}{ a Pofozógép, vagy ilyesmi.}
{2505}{}{... nem rossz, nem rossz. Illik hozzád. (A ring felé biccent.) Mehetünk akkor? Készen állsz?}
{3422}{}{. }
