{100}{}{Ez itt Koporsós Willie.}
{150}{}{Ez itt egy öreg, büdös, ráncos ghoul. Barátom, ez úgy bűzlik, hogy arra nincs szó!}
{200}{}{Atyám! Ez a sír bűzlik, mint állat!}
{201}{}{Aha... ássunk csak tovább...}
{202}{}{Mi a...?}
{203}{}{Na, hogy oda ne csesszek! Az ásás aztán nem az erősséged, marharépa!}
{204}{}{Menj előlem, simabőrű!}
{205}{}{A'apu?}
{206}{}{Most ne, Lenny, nincs kedvem beszélgetni!}
{300}{}{Az ember beugrik Renóba' egy kis itókára meg kurvázásra, erre a francos simabőrűek bevágnak egy sírgödörbe...}
{301}{}{Jó, hogy nincs egy fia orrom se, különben felfordulnék a saját szagomtól.}
{302}{}{A ghoulokat francba se veszik!}
{303}{}{Beugrok a városba egy italra, erre a renói seggfejek élve eltemetnek.}
{304}{}{Nincs unalmasabb, mint hónapokig egy koporsóban lakni.}
{305}{}{El a kezekkel, simabőrű! Dolgom van.}
{306}{}{Vedd le a simabőrű mancsodat rólam, te!}
{500}{}{A fejfán ez áll: "Itt nyugszik a legostobább fasz, aki valaha betette a lábát New Renóba."}
{550}{}{A sírgödörből szörnyű szag árad.}
{600}{}{Hé!}
{601}{}{Hallok valamit odakinntről!}
{602}{}{Ne lépjé' a sírra! Hullik a főd a fejemre!}
{603}{}{Gyorsan, SZEREZZ EGY ÁSÓT!}
{604}{}{Kiásna már végre valaki? Inni akarok!}
{605}{}{Ez itt egy féreg? Végül is... mindegy.}
{700}{}{Ug, smellie in hole.}
{701}{}{Me dig more for smellie shinies.}
{702}{}{Huh, You not shini-!?}
