{100}{}{Az elõtted látható széfet masszívan beleerõsítették a falba. Az ajtaja csukva van.}
{150}{}{Az elõtted látható széfet masszívan beleerõsítették a falba. Az ajtaja nyitva van.}
{200}{}{(There is a little door in the wall. A very, very small person must live inside! There is a doorknob with numbers on it in the middle of the door.)}
{220}{}{(Kattanásokat hallasz, és a széf már nyitva is van.)}
{240}{}{(Jónéhány percig tekergeted a tárcsát, de nem jutsz vele semmire.)}
{260}{}{(Nem találtál semmiféle csapdát a széfen.)}
{270}{}{(Elfordítod a gombot... mire hirtelen kattanásokat hallasz, és az ajtó kinyílik!)}
{280}{}{(Elfordítod a gombot, de az apró ajtó nem nyílik!)}
{300}{}{(Nem hallasz senkit, és csengõt sem látsz. Talán nincs is otthon senki.)}
