{100}{}{Az előtted látható széfet masszívan beleerősítették a falba. Az ajtaja csukva van.}
{150}{}{Az előtted látható széfet masszívan beleerősítették a falba. Az ajtaja nyitva van.}
{200}{}{(There is a little door in the wall. A very, very small person must live inside! There is a doorknob with numbers on it in the middle of the door.)}
{220}{}{(Néhány kattanást követően a széf kinyílik.)}
{230}{}{(You pry up a small panel on the bottom of the safe. You don't think you would have found it if Mrs. Bishop hadn't told you about it. Inside is an odd-looking Pip-Boy attachment.)}
{240}{}{(Jónéhány percig tekergeted a tárcsát, de nem jutsz vele semmire.)}
{250}{}{(Nem találtál csapdát a széfen.)}
{260}{}{(Elfordítod a gombot... mire hirtelen kattanásokat hallasz, és az ajtó kinyílik!)}
{270}{}{(Elfordítod a gombot, de az apró ajtó nem nyílik!)}
{290}{}{(Nem hallasz senkit, és csengőt sem látsz. Talán nincs is otthon senki.)}
