{100}{}{A sírkövön ez áll: "Itt nyugszik szeretett gyermekünk, Richard Wright. Emléke örökké szívünkben él."}
{200}{}{A koporsóban egy tinédzser testét találod.}
{201}{}{Átvizsgálod Richard Wright sírját. A testb?l émelyít? szag árad.}
{202}{}{A testb?l áradó szag radskorpió méregre utal... a gyerek nem Jet túladagolásban halt meg, hanem megmérgezték.}
{203}{}{A gyerek testéb?l áradó szag nagyon ismer?s, de nem akar beugrani...}
{300}{}{Rájöttél, hogy Richard Wrightot megmérgezték.}
