{100}{}{Egy szomorú, idősebb ember.}
{101}{}{Dave, alias "Mr. Depresszió".}
{102}{}{Egy mogorva, idősebb embert látsz, aki a korai hatvanas éveit tapossa. Olyan képet vág, mint aki lócitromba harapott.}
{103}{}{Bocs. Nem láttam, hogy itt áll.}
{104}{}{Hogyhogy? Én nagy.}
{105}{}{Te szomorú. Miért?}
{106}{}{Én menni, üdv.}
{107}{}{Semmi gond, bárkivel előfordulhat. Hm, elég gondterheltnek tűnik. Megmondaná, miért?}
{108}{}{Oké, mindegy. Miért ilyen szomorú?}
{109}{}{Legközelebb talán üssem fejbe, hogy észrevegyen?!}
{110}{}{Mindegy. Most jut eszembe, nekem valahol máshol kéne lennem.}
{111}{}{Az élet szemét... főleg velem.}
{112}{}{Öö... én most menni el.}
{113}{}{Úgymint?}
{114}{}{Jó hozzáállás. Mire fel?}
{115}{}{Valahol máshol akarok lenni.}
{116}{}{Két hónappal korábban születtem, mint kellett volna. Egy évesen leejtettek a tornácra. Két évesen tüdőgyulladásom volt. Három évesen bárányhimlőt kaptam. Négy évesen leestem a lépcsőről, és hat bordám eltört. Öt éves koromban a nagybátyámat lefejezte egy dinnye. Hat évesen a szüleim fejbe vágtak egy ásóval. Hét évesen a jobb mutatóujjamat leharapta a patkányom.}
{117}{}{Öö, valaki hívni engem. Szia!}
{118}{}{Sajnálni rossz dolgok.}
{119}{}{Múlt rossz, nem semmi. Dolgok most jók?}
{120}{}{Húúú! Örülük, hogy nem vagyok a maga helyében!}
{121}{}{Oké, képben vagyok. Most éppen mi zavarja?}
{122}{}{Igazán sajnálom, hogy ennyi fájdalom érte az életben. Remélem, most már jobb sora van?}
{123}{}{Egy pillanat. Elfelejtettem, hogy most valami egészen más dolgom akadt.}
{124}{}{Hát, ja, az élet szemét... főleg velem.}
{125}{}{Mi történik most?}
{126}{}{Én már hallottam. Üdv!}
{127}{}{Most épp mi történt, amin így kiakadt?}
{128}{}{Igazán nincs szükségem erre a dumára. Azt hiszem, megyek.}
{129}{}{Naszóval, épp a sivatagban utaztam, mikor a brahminjaim hirtelen holtan estek össze. Akkor vettem észre, hogy alig van nálam víz és már jó ideje nem ittam. A csontjaim csakhamar sajogni kezdtek, a fejem elkezdett fájni, hasmenésem lett, és olyan kiütést kaptam, hogy azóta sem múlt el. Ideje volt leülni, és meghalni.}
{130}{}{Én... ööö.. maga... maga nincs feleség vagy gyerek?}
{131}{}{Nem beszélje tovább! Én menni.}
{132}{}{Nem szeretnék több hasonló dolgot hallani. Jobb lesz, ha eltűnök a közeléből. Viszlát!}
{133}{}{Könyörgöm, nyugtasson meg, hogy nincs gyereke!}
{134}{}{Nincs. Huszonkét éves koromban kijött rajtam egy fura gomba a...}
{135}{}{Ááá! Elég! Én menni el!}
{136}{}{ELÉG! Ne tovább! Nem akarom tudni!}
{137}{}{Ó, üdv! Mit tehetek magáért?}
{138}{}{Öö, mi történt magával?}
{139}{}{Bocs, én megy.}
{140}{}{Azon gondolkoztam, elmondaná-e még egyszer a történetét?}
{141}{}{Egy pillanat, összekevertem valakivel.}
{142}{}{Végre, eljött az én időm. Most meg fog ölni?}
{143}{}{Igen.}
{144}{}{Nem.}
{145}{}{Nyolc éves koromban a kutyámat, Tüsit elütötte egy traktor. Kilenc éves koromban az anyám karját leharapta egy veszett brahmin. Tíz éves koromban a nővéremet széttépte egy falka kutya. Tizenegy éves koromban a nagyapám öngyilkos lett, mert ronda voltam. Tizenhárom éves koromban az apám részegségében kiszúrta a saját szemét egy villával.}
{146}{}{Tizenhét éves koromban levágtam egy kapával a nagylábujjamat. Tizennyolc éves koromban az apám lábát levágta ugyanaz a traktor, amelyik a kutyámat ütötte el. Tizenkilenc éves koromban...}
{147}{}{Tehát ott ültem a sivatagban, várva, hogy végleg megszűnjek létezni, mikor egy falka halálkarom tűnt fel. Na, gondoltam, eljött az idő. Egy rakás halálkarom-szarként fogom végezni a sivatagban. De nem... a sors folytatta kegyetlen játékát ellenem.}
{148}{}{Amint látja, a halálkarmok nem öltek meg. Helyette vizet adtak, ide hoztak, megkaptam ezt a szobát, adtak ennem, megmosdattak, és most nem engednek távozni. Szerintem azért hízlalnak, hogy bevégezzem ismeretlen, szörnyű sorsomat. Hiába mondom nekik, hogy soványabban finomabb lennék. Csak mosolyognak, már ha annak lehet nevezni, és megpaskolva a fejemet azt mondják: "Ne aggódj, ember, jobbra fordul a sorsod". Hah! Mindketten tudjuk, mit jelent ez.}
{149}{}{Mindenesetre, hogy még rosszabb legyen, valamiféle gyógykezelés alá vettek. Eléggé felfújt, úgyhogy abbahagytam... Milyen igazam volt! Azt hiszem, valami "tudat-befolyásoló" pirula volt, mert valahogy szebbnek láttam tőle a világot! Hát, ennyit erről. Csak arra várok, hogy a halálkarmok felszabdalt, megpörkölt testemből lakomázzanak.}
