{100}{}{Ez a Halálkarom szokatlanul intelligens tekintettel néz rád.}
{101}{}{Jul, a Halálkarmok egyike.}
{102}{}{Egy átlagos Halálkarom. Óriási teremtmény, er?s testtel, éles fogakkal és karmokkal felvértezve..}
{103}{}{Állsz! Nem mégy ide! Ez hely itten határ!}
{104}{}{Okés. Elmegyek.}
{105}{}{Mi lenni ez hely?}
{106}{}{Te ki?}
{107}{}{Rendben, elmegyek.}
{108}{}{Oda megyek, ahová akarok, gyík-ivadék!}
{109}{}{Mi ez a hely tulajdonképpen?}
{110}{}{Ki vagy te?}
{111}{}{Ez fészek. Falka anya bent. Tojások bent. ?rzök. Mindenkit.}
{112}{}{Beszélni akarok az anyával.}
{113}{}{Te ki?}
{114}{}{Én menni mostan.}
{115}{}{Akkor elmegyek.}
{116}{}{Ki vagy te?}
{117}{}{Szeretnék beszélni az anyával.}
{118}{}{Én Jul. Falka harcos. ?rzök fészek. ?rzök anya.}
{119}{}{Én}
{120}{}{Én menni mostan.}
{121}{}{?rizni anya, fontos. Te fontos.}
{122}{}{Én}
{123}{}{Az anya ?rzése nagy felel?sség. Te bizonyára fontos vagy a falkában.}
{124}{}{Azt hiszem, most elmegyek.}
{125}{}{Várj! Megkérdezni anya.}
{126}{}{Oké.}
{127}{}{Anya beszél veled. Menny be! Nem csiná'sz bajt. Nem akarni bántást neked, de ha okozod bajt, nagy bántást kapol.}
{128}{}{Anya beszél veled. Te bemész, egyedül. Társak marannak. Nem csiná'sz bajt! Nem akarni bántást neked, de ha okozod bajt, nagy bántást kapol.}
{129}{}{Oké.}
{130}{}{Úgy gondolod? Szerintem nem. Jójjaz nekem. Teccik. Kösz.}
{131}{}{Köszönöm. Most menni elfele.}
{132}{}{Beszélni akarok az anyával.}
{133}{}{Köszönöm. Most már mennem kell.}
{134}{}{Beszélhetnék az anyával?}
{135}{}{Gyík ivadék... Ó, venni. Haha! Akkor kapjad ki eztet! Azér' ?rköd itt, mert én lenni legokosabb, leger?sebb, legkegyetlenebb vadállat itten a francos menedékben. Szívassál csak, a legjobbat szívatod. Takaroggyá, mer eltöröm kezed-lábad, aztán beleszúrom hátadba!}
{136}{}{Elmegyek akkor...}
{137}{}{Valóban? Lássuk, milyen kemény vagy!}
{138}{}{Te vagyol? Mit akarni?}
{139}{}{Mondok helló. Elmegyek.}
{140}{}{Mit mondol, ki lenni?}
{141}{}{Mi lenni ez hely?}
{142}{}{Csak köszönni ugrottam be.}
{143}{}{Mi ez a hely tulajdonképpen?}
{144}{}{Ki is vagy te?}
{145}{}{Már hulla vagy. Csak túl hülye vagy hozzá, hogy felfogd.}
{146}{}{. Én akar beszélés anyával.}
{147}{}{, Jul, és szeretnék beszélni az anyával, kérlek.}
