{100}{}{Kislány, sárga ruhában.}
{101}{}{Egy kisgyerek, akit Sandynek hívnak.}
{102}{}{Egy sárga, virágos ruhát viselő kislány. Úgy nyávog mint egy macska. A ruháján egy felirat azt mondja: "Sandy".}
{103}{}{Miau... miau... Cica vagyok. Olyan különleges erőm van, ami csak a cicáknak. Te mi vagy?}
{104}{}{Én kutya! Vau! Vau! Te ki?}
{105}{}{Hmmm? (zavarodott kutyus tekintet)}
{106}{}{Te fura. Én menni.}
{107}{}{Én az az ember vagyok, aki szétrúgja a seggedet, ha nem hagyod abba ezt a cica baromságot, és nem mondod meg a neved!}
{108}{}{Én csak egy sima ember vagyok, akit egészen meghatott a te különös természeted. Megmondod a neved?}
{109}{}{Rá se ránts!}
{110}{}{(Kuncogás) Viccesen nézel ki! Miau... Sandy vagyok. Nem vagyok igaziból cica. Csak szeretem eljátszani, hogy az vagyok.}
{111}{}{(Sikítás) Anyuu! Anyuu!! Anyuu!!}
{112}{}{Sandy vagyok. Nem vagyok cica, csak szeretem eljátszani.}
{113}{}{Én is játszani. Lehet kérdés tőled?}
{114}{}{Elmegyek.}
{115}{}{Értem. Kérdezhetek pár dolgot?}
{116}{}{Okés, én most felszívódok.}
{117}{}{Mit szeretnél kérdezni?}
{118}{}{Kötelező itt lenned?}
{119}{}{Jó itt neked?}
{120}{}{Biztonságos itt?}
{121}{}{Semmi, elmegyek.}
{122}{}{Kényszerítenek, hogy itt maradj?}
{123}{}{Szeretsz itt lenni?}
{124}{}{Biztonságban vagy itt?}
{125}{}{Semmi, szia.}
{126}{}{Aha. Anya mindig megmondja, hova mehetek, és hova nem. Megmondja, hol játsszak, mikor egyek, mikor menjek lefeküdni, mikor bilizzek, és mikor menjek suliba, meg minden. Szerintem nem szép dolog, hogy ő azt csinál amit akar, nekem meg mindig azt kell csinálnom, amit ő mond.}
{127}{}{Oké.}
{128}{}{Most kell menni.}
{129}{}{Értem.}
{130}{}{Azt hiszem, már eleget hallottam. Szia.}
{131}{}{Tulképpen... Viszont hiányzik, hogy nem játszhatok más gyerekekkel, de anya azt mondta, minden máshogy lesz. Azt hiszi, más gyerekek is idejönnek majd lakni. Amíg nincsenek, addig Valdisszal szeretnék játszani. Ő vicces, és lovagolhatok is rajta. Anyu azt mondja, hogy békén kellene hagynom. Sok dolga van, és nincs ideje játszani, de ha megkérem, mindig játszik velem. Nem mesélem el anyunak, és kész.}
{132}{}{Lovacska... (zavarodott kutyus tekintet)}
{133}{}{Megyek.}
{134}{}{Ez kedves.}
{135}{}{Ok, szija.}
{136}{}{Aha. Anya vigyáz rám, és Valdis sem hagyná, hogy bárki bántson. Itt biztonságban vagyok.}
{137}{}{Oké. Most már menni.}
{138}{}{Jó, akkor én megyek is.}
{139}{}{Helló!}
{140}{}{Menj innen! Nem kedvellek!}
