{151}{}{}
{200}{}{Jók a kilátások.}
{201}{}{A kilátások nem túl jók.}
{202}{}{A válaszom: nem.}
{203}{}{Ne számíts rá!}
{204}{}{Megbízhatsz benne.}
{205}{}{Késõbb kérdezd.}
{206}{}{Valószínûleg.}
{207}{}{Most nem tudom megjósolni.}
{208}{}{Igen.}
{209}{}{Igen. Kétségtelenül.}
{210}{}{Jobb, ha most nem mondom el neked.}
{211}{}{Ez biztos.}
{212}{}{Elég bizonytalan.}
{213}{}{Határozottan olyan.}
{214}{}{Koncentrálj és kérdezz rá újra.}
{215}{}{A jelek arra engednek következtetni, hogy igen.}
{216}{}{Forrásaim szerint nem.}
{217}{}{Kételyek nélkül.}
{218}{}{A válasz ködös, próbáld újra.}
{219}{}{Szerintem igen.}
{220}{}{Ne rázz ennyire! Ez fáj!}
{221}{}{Erõs jobb karod van.}
{222}{}{Kérlek, töröld meg a kezed, mielõtt még egyszer megrázol!}
{223}{}{Átmenetileg nem mûködik.}
{224}{}{Az RPG Tanács által bezáratva.}
{225}{}{Ha tovább rázol, baj lesz!}
{226}{}{Egyre betegebb vagyok.}
{227}{}{Egyre jobban émelygek.}
{228}{}{Meleg a kezed.}
{229}{}{Feargus nem akart beletenni a játékba. Jó nagy állat.}
{230}{}{Az eredményed 23 pont a lehetséges 100-ból. Még van tennivaló bõven.}
{231}{}{Scott Everts nagyokat sóhajtozik, mikor átnézi, hogy mennyi tárgy van a játékban.}
{232}{}{Nézz be a New Reno-i Mordino kaszinó elsõ emeletén lévõ WC-be!}
{233}{}{Ha aktiválod a "Szemét" feliratú keresztet a Golgotán, találhatsz valamit.}
{234}{}{Miután befejezted a játékot, menj vissza New Renóba és beszélj Tully atyával!}
{235}{}{Tudod, hogy használhatsz fegyverként.}
{236}{}{Ne rázz ilyen erõsen!}
{237}{}{A szerencséd szerfelett magas. Rázz tovább nyomravezetõ tanácsokért!}
{238}{}{Igen, mi tudjuk, hogy a "Descent to Undermountain" egy kalap szar.}
