{100}{}{Egy hatalmas, ember-szerű, páncélos figurát látsz.}
{101}{}{Frank Horrigan-t, a Titkosszolgálat ügynökét látod.}
{102}{}{Egy hatalmas, ember-szerű figurát látsz, aki a legtisztább gyűlölettel néz rád.}
{103}{}{Nem mész innen sehova, mármint élve, apró mutánsom!}
{104}{}{Te nyavalyás mutáns.}
{105}{}{Vörös mutáns!}
{106}{}{Elpusztítottál valamennyiünket.}
{107}{}{Fizetni fogsz azért, amit tettél!}
{108}{ssa2}{Ne örülj (köhög) a győzelemnek! Te, meg a kis mutáns féreg barátaid összeölelkezünk egy jó kis gombafelhő közepén. Épp most indítottam el az önmegsemmisítést. Hehe... (köhécsel) A munka majd megy tovább. Nem értél el itt semmit, kivéve, hogy aláírtad a halálos ítéletedet. Kötelesség, (köhög) becsület... bátorság... Semper Fiiiii...}
{109}{ssa2}{Ne örülj (köhög) a győzelemnek! Te, meg a kis mutáns féreg barátaid összeölelkezünk egy jó kis gombafelhő közepén. Épp most indítottam el az önmegsemmisítést. Hehe... (köhécsel) A munka majd megy tovább. Nem értél el itt semmit, kivéve, hogy aláírtad a halálos ítéletedet. Kötelesség, (köhög) becsület... bátorság... Semper Fiiiii...}
{110}{}{Ajjaj! Rossz történni itt. Futni vissza hajóra.}
{111}{}{Jobb, ha felmegyek a hajóra, és eltűnök innen a búsba.}
{112}{ssa3alt}{Messzire jutottál, messzebb, mint szabad lett volna, de még nem találkoztál Frank Horrigan-nel. A történet most befejeződik, apró mutánsom. Itt az idő, hogy meghalj!}
{113}{}{Átgázolok rajtad, akár tetszik, akár nem!}
{114}{}{Nem beszélhetnénk ezt át egy kicsit?}
{115}{ssa4a}{Az FEV toxin légszűrőnkbe való pumpálása nem tesz téged hőssé. Csak egy újabb mutáns vagy, akinek egyetlen lehetséges sorsa van: a pusztulás}
{116}{ssa4b}{A reaktorunk leolvasztása azt jelenti, hogy a dolgok mindjárt bemelegednek itt. Kár, hogy nem fogod megérni. Nem vagy hős, csak egy két lábon járó hulla.}
{117}{}{Vajon van akkora lángod, mint amekkora füstöd? Aligha.}
{118}{}{Várj egy kicsit! Várj! Nem beszélhetnénk ezt meg?}
{119}{ssa5}{Már megtettük. A beszéd ideje lejárt.}
{120}{}{Legyen hát...}
{121}{}{Várj!}
{130}{ssa7}{Én Frank Horrigan vagyok. Az Egyesült Államok Titkosszolgálatától. Nem mész te innen sehova!}
{131}{}{Átgázolok rajtad, akár tetszik, akár nem!}
{132}{}{Várj, beszéljük ezt meg!}
{133}{}{Nem megyek sehova, amíg ki nem tapostam belőled az utolsó szuszt is.}
{134}{}{Eh? Frank "Ki a rák?"}
{135}{}{Itt csak egyetlen aprócska mutánst látok, az pedig te vagy. Pusztulj, szörnyszülött!}
{140}{ssa6}{Te mutáns söpredék! Próbálkozz csak a trükkjeiddel! Nem segít rajtad, semmi sem segít már!}
{141}{}{Átgázolok rajtad, akár tetszik, akár nem!}
{142}{}{Várj, beszéljük ezt meg!}
