{100}{}{Egy alacsony, hollófekete hajú, mosolygós emberhez van szerencséd.}
{101}{}{Ascortit látod, aki éppenséggel Redding polgármestere.}
{102}{}{Egy elegánsan öltözött, nyájas férfire fókuszál most a pupillád.}
{103}{}{Mozgás, haver!}
{104}{}{Ha azért jöttél, hogy próbára tedd a szerencséd, légy üdvözölve!}
{105}{}{Játssz vagy tűnj innen a búsba!}
{106}{}{Jobb lesz, ha visszafogod magad amíg itt tartózkodsz!}
{107}{}{Tégy próbát az asztaloknál, bennszülött!}
{108}{}{Ki kéne próbálnod a pénznyerőket, bennszülött! Esetleg a ráolvasás is segítene!}
{109}{}{Csak módjával idd tüzes vizet, bennszülött!}
{110}{}{Üdvözöljük Redding előkelő városában... és köszöntjük a kaszinómban! Ascortinál mindenki nagyágyú! Én vagyok Ascorti, a tulajdonos és e remek város első embere.}
{111}{}{Mit tehet önért Ascorti polgármester?}
{112}{}{Van valami munkalehetőség itt, Reddingben?}
{113}{}{Mi a helyzet a városban mostanában?}
{114}{}{Hallott valami olyasmiről, amit Édenkert Létrehozást Elősegítő Táskának neveznek?}
{115}{}{Mit csinálsz itt?}
{116}{}{Csak bámészkodtam, polgármester úr. Majd később találkozunk! Viszlát!}
{117}{}{Ezt a kaszinót üzemeltetem, és besegítenek még néhány dologba a városka életében. Ezenkívül én foglalkozom például a birtoklevelekkel meg ilyesmikkel.}
{118}{}{Milyen birtoklevelekről van szó?}
{119}{}{Értem. Akkor hadd kérdezzek valami mást, polgármester úr.}
{120}{}{Olyasféle birtoklevelekkel foglalkozom, mint pl. a Nagy-Wanamingo bányáé, amit meg akarok venni magától. Nem akarja eladni?}
{121}{}{Talán... Mennyit lenne hajlandó felajánlani érte?}
{122}{}{Esetleg... De előtte hadd kérdezzek más egyébről is!}
{123}{}{Még gondolkodom rajta. Viszlát, polgármester!}
{124}{}{Nos, csak egyetlen birtoklevelet érint a dolog. Amit eladtam önnek. Tudja, ami a Nagy-Wanamingo bányáé volt...}
{125}{}{Ja, hogy az a birtoklevél! Most már emlékszem. Akkor inkább kérdeznék valami mást, polgármester úr.}
{126}{}{Természetesen - csak kíváncsi voltam, hogy volt-e más ilyen üzlete is. Na, ideje, hogy nekilássak kipucolni azt a bányát... Viszlát!}
{127}{}{A Nagy-Wanamingo bánya birtoklevele, amit visszavásároltam öntől. Emlékszik?}
{128}{}{Persze, hogy emlékszem! Öö, izé... feltehetnék egy másik témával kapcsolatos kérdést is, polgármester úr?}
{129}{}{Igen, persze, hogy emlékszem. Csak érdeklődtem. Viszlát, Ascorti polgármester úr!}
{130}{}{Mindenféle magántulajdon. Most, mit tesz isten, éppen van egy hihetetlenül értékes eladó birtoklevelem...}
{131}{}{Mi az?}
{132}{}{Elhiszem, hogy van... de előtte még meg szeretnék kérdezni valamit, polgármester úr.}
{133}{}{Hmm... először egy kicsit körbenézek a városban, polgármester úr. Viszlát!}
{134}{}{A Nagy-Wanamingo bányáé. Az a bánya, amelyik a városka határában fekszik. Ha érdekli, én hajlandó vagyok eladni önnek potom 1000 dollárért. Ez egy nem mindennapi ajánlat! Mindössze csak a szerencsének köszönheti, hogy ilyen nagyvonalú napot fogott ki.}
{135}{}{Ez érdekesen hangzik... Mondjon róla még valamit!}
{136}{}{Nincs itt valami simlisség, polgármester úr?}
{137}{}{Nem, nem hinném, hogy most meg akarnám venni, polgármester úr. Inkább engedje meg, hogy kérdezzek valami mást.}
{138}{}{Nos, a bányában lakozik néhány átkozott dög, amiket érdemes lenne elintézni, mielőtt bárki is lemerészkedne oda dolgozni. Ha megvenné tőlem a birtoklevelet, szépen legyilkolgathatná a bányát ellepő szörnyetegeket, én pedig örömmel vásárolnám vissza öntől sokkal magasabb áron.}
{139}{}{Mégis mennyivel magasabb áron?}
{140}{}{Miért nem Ön tisztítja meg a bányát, ha annyira jövedelmező?}
{141}{}{Miféle szörnyetegekről beszél?!}
{142}{}{Semmiféle simlisség nincsen! Egyáltalán nincs! Egyszerűen csak ki kell füstölni onnan a nem oda illő elemeket. De ez nem okozhat gondot egy ilyen belevaló embernek, mint ön. Ha érdekli, még mondhatok róla többet is.}
{143}{}{Rendben, essünk neki... Halljuk a részleteket!}
{144}{}{Valahogy most nincs kedvem ilyen ügyekbe keveredni, polgármester úr. Inkább kérdeznék helyette valami mást.}
{145}{}{Értem. Ezt a nemes feladatot inkább valaki másra hagynám. Minden jót, polgármester úr!}
{146}{}{Heh! Jóval a duplája felett! Úgy vélem, legalább ennyit megér önnek a rászánt idő. Ennél többet viszont már tényleg nem tudok érte fizetni. Ráadásul még rengeteg munka vár rám, hogy a bányát termelőképes állapotba hozzam.}
{147}{}{Ez jól hangzik! Szóval mennyit is kéne fizetnem érte?}
{148}{}{Annyira nem érdekel. Helyette viszont kérdeznék valami mást, kedves polgármester úr.}
{149}{}{A Nagy-Wanamingo bánya birtoklevele csak 1000 dollárba kerül. Akkor megveszi?}
{150}{}{Persze, megveszem azt a birtoklevelet!}
{151}{}{Szívesen megvenném a birtoklevelet, de sajnos nincs elég pénzem jelen pillanatban... Kérdeznék valami mást!}
{152}{}{Most nem szeretném megvásárolni. Viszont kérdezni azt szeretnék...}
{153}{}{Talán majd később, polgármester úr!}
{154}{}{Akkor nekiállok kiállítani a Nagy-Wanamingo bánya birtoklevelét az ön nevére. Kérem, azonnal értesítsen, amint megtisztította a bányát, hogy mihamarabb vissza tudjam öntől vásárolni!}
{155}{}{Meglesz! Most viszont még kérdeznék valami mást is, polgármester úr...}
{156}{}{Oké! Hamarosan visszajövök, polgármester!}
{157}{}{Nem érzem magam képesnek erre. Igazából nem vagyok én olyan ember, aki csak úgy keresi magának a veszélyt... Tisztában vagyok vele, hogy sem az erőm, sem a harci képességeim nem ütik meg a szükséges mércét. De ön! Ön aztán rátermettnek tűnik, hombre! Ez egyenesen önnek való...}
{158}{}{Lehet, hogy így van. Mennyit is szándékozik szánni a birtoklevél visszavásárlására, ha esetleg sikerülne lerendezni ezt a bánya-ügyet?}
{159}{}{Lehet, hogy igen, lehet, hogy nem. Még gondolkodnom kell rajta. Addig is hadd kérdezzek valami másról, polgármester.}
{160}{}{Nekem erre most nincs felesleges időm. Nagyon sajnálom, polgármester úr. Viszlát!}
{161}{}{Nah, kisepregette már a bányát?}
{162}{}{De ki ám!}
{163}{}{Még nem, de nemsokára meglesz. Addig is szeretnék kérdezni egy s mást.}
{164}{}{Dolgozom rajta. Viszlát, Ascorti polgármester úr!}
{165}{}{Hát... szerintem még nem sikerült elintéznie az összes rohadt wanamingót... Jobb lesz, ha visszamegy és még körülnéz egy kicsit. Addig nem fogom visszavásárolni a bányát, amíg az összes meg nem döglik!}
{166}{}{Értem. Kezdéskeppen hadd kérdezzek még valamit, polgármester úr.}
{167}{}{Akkor jobb lesz, ha tényleg visszamegyek és újra szétnézek.}
{168}{}{Gratulálok, nagyszerű munkát végzett! Sikerült elpusztítania az összes nyamvadt wanamingót a bányában! De lenne még egy kis gond...}
{169}{}{Egy kis gond?! Úgymint?}
{170}{}{Megtisztította az egész bányát. Nagyon-nagyon szépen köszönöm! Hajlandó eladni a birtoklevelet? Adok érte 2500 dollárt.}
{171}{}{Kötve hiszem. Úgy érzem, egyelőre jobb lesz, ha nálam marad. Viszlát, polgármester úr!}
{172}{}{Naná! Örülök, hogy megszabadulhatok ettől az átkozott birtoklevéltől, tisztelt polgármester úr!}
{173}{}{Wanamingóknak hívjuk őket. Borzalmas természetfeletti teremtmények, pengeéles fogakkal és szívókával vagy mi a túróval... Nem túlságosan okosak, de ha közel engedi őket magához, nagyon megjárhatja...}
{174}{}{Értem. És azt szeretné, hogy szabadítsam meg a bányát ezektől a kedves lényektől?}
{175}{}{Eltalálta! Tudtam én, hogy ön nem olyan lassú felfogású, mint amilyennek látszik! Okos is tud lenni, ha szükség van rá...}
{176}{}{Jaja. Nos, akkor mennyit is kell majd kibírnom ezért a busás üzletért?}
{177}{}{Nagyon is otthonos volt, amíg valaki be nem költözött... Egy tipikus rosszfiú, Morton, a Hűtős... és... öö... a bandája. Legalábbis ezt hallottam.}
{178}{}{Miért hívják őt Hűtősnek?}
{179}{}{És ehhez nekem mi közöm van?}
{180}{}{Nagyszerű, mit kezdjek ezzel?}
{181}{}{Szerintem azért ragasztották ezt a nevet rá, mert folyton hidegre teszi az embereket. Velejéig romlott ember, akit nem szabad elszalasztani... és ha sikerül, ön hős lesz! Szeretne hős lenni, nem?}
{182}{}{Meglehet, de még mindig nem látom át, mi közöm nekem ehhez.}
{183}{}{Hogyne, persze! Miképp segíthetek?}
{184}{}{Most jutott eszembe, hogy elfelejtettem kitakarítani! Majd visszanézek, amint megbillentettem pár hátsót, Polgármester úr...!}
{185}{}{Háááát... amíg a bánya nincs kitisztítva, nem tudok munkásokat küldeni oda. Szóval, ha el akarja adni nekem a bányát, ez a gond az ön vállát nyomja...}
{186}{}{Miért hívják őt Hűtősnek?}
{187}{}{Nagyszerű! Mit tudok én tenni az ügyben?}
{188}{}{Akkor jobb is lesz, ha belevágok. Viszlát, polgármester úr!}
{189}{}{Van egy olyan érzésem, hogy vissza kellene mennie a Wanamingo bányába, és leszámolni a Hűtőssel meg a bandájával... Ha sikerült, jöjjön vissza és én abban a szent pillanatban, szélesvásznú szinkronizált mosoly kíséretében visszavásárolom öntől a bányát.}
{190}{}{Hát már sosem mehetnek simán a dolgok? Rendben, polgármester úr. Később találkozunk. Van még egy-két függőben levő ügyem, amit le kell zárnom.}
{191}{}{Hajlandó végre eladni nekem a Wanamingo bányát?}
{192}{}{Hát persze, polgármester úr! Mit is mondott, mekkora lenne az összeg?}
{193}{}{Most még nem, polgármester úr! Viszlát!}
{194}{}{Hallottam, hogy úgy döntött, segít a seriffnek. Helyes! Nem engedhetjük meg, hogy annak a csóró Rooneynak ilyen szép háza legyen.}
{195}{}{Arra az aprócska, széllelbélelt viskóra gondol, amiért szó szerint kiszipolyozza őt?}
{196}{}{Lett volna rá egy fogadásom. Mennyivel tartozik Önnek?}
{197}{}{Majd meglátom, mit tehetek az ügyben. Viszont még kérdeznék valami mást is.}
{198}{}{Ja. Mégis kicsoda ön?}
{199}{}{Jobb szeretem, ha inkább kényelmes, évszakhoz igazított szellőzőrendszerrel felszerelt lakásnak nevezzük. És az ára is igazán elfogadható.}
{200}{}{Bizonyára így is van. Mennyi lakbérrel tartozik még Önnek?}
{201}{}{Hmmm... most már jobb lesz, ha megyek, polgármester úr. Viszlát!}
{202}{}{Nézzük csak! Mrs. Rooney... igen, már meg is van... 120 dollárral tartozik nekem. Pontosan 120 dollárral!}
{203}{}{Csak ennyi? Itt van a zsebemben az összeg.}
{204}{}{Hát ez nem valami sok. Hadd kérdezzek még valami mást!}
{205}{}{Majd meglátom, hogyan tudnám behajtani rajta az adósságot. Viszlát!}
{206}{}{Ez így rendben is van. Az ügy elsimítva. Köszönöm, hogy lerendeztük a tartozását.}
{207}{}{Nem gond! De azért kérdeznék még valami mást is.}
{208}{}{Szerintem csak vannak emberek, akik gavallérabbak másoknál. Viszlát, polgármester úr!}
{209}{}{Köszönöm, hogy megtisztította a tulajdonomat, seriff! Most már végre kiadhatom valakinek, aki fizet is azért, hogy benne lakik!}
{210}{}{Hát nem érzem magam valami jól azután, amit tettem.}
{211}{}{Ebben van ráció.}
{212}{}{Miért nem? Pedig érezze csak jól magát! Azzal, hogy kitette az özvegy Rooney szűrét, újra tudok fizetni az alkalmazottaimnak. Ha nem adok nekik fizetést, a családjaik éhezni fognak! Ez nem volna helyes, ugye?}
{213}{}{Nem volna. Ebben a tekintetben még nem is gondoltam át a dolgot. A baj az, hogy továbbra sem érzem magam valami jól miatta.}
{214}{}{Nem úgy tűnik, mintha túl rosszul menne itt a dolga. Biztosra veszem, hogy a kaszinóból elég bevétele származik!}
{215}{}{Jó adag elszántságra van ahhoz szükség, hogy az ember mindig helyesen cselekedjen, még akkor is, ha éppen rossz érzések maradnak benne. Komoly dolgot vitt véghez, és jól helyt állt. Meghívom egy sörre!}
{216}{}{Köszönöm, polgármester! Ez igazán rendes volt magától.}
{217}{}{Nem akarok én magával inni semmit se! Se most, se máskor! Viszlát!}
{218}{}{Nincs itt semmi gond... Boldog vagyok, hogy meghívhatom egy korsóra a helyi rendfenntartó erőt...}
{219}{}{Még egyszer köszönöm, polgármester úr! És még hadd kérdezzek valami másról is.}
{220}{}{Köszönöm, polgármester! Később találkozunk! Viszlát!}
{221}{}{Ma talán igen... de ki tudja, mit hoz a holnap? Valahogy fenn kell tartanom a kényes egyensúlyt, és jó bevételt kell produkálnom. Tartozom ezzel az alkalmazottaimnak, meg persze magamnak is.}
{222}{}{Úgy vélem, ez éppen elég méltányos.}
{223}{}{Maga még annyit sem ér, mint egy döglött gekkó bele... Eleget hallgattam magát! Viszlát!}
{224}{}{Csak szerettem volna újból megköszönni, hogy a lehető leghelyesebben járt el Mrs. Rooneyval. Én igazán nem akartam kirúgni azt az öreglányt a házából...}
{225}{}{Mégis így történt. Inkább beszélgessünk valami szívderítőbb témáról!}
{226}{}{Valahogy éreztem, hogy valami ilyesmit fog mondani. Viszlát, polgármester úr!}
{227}{}{Túl messzire ment azzal az özvegyasszony Rooneyval! Nem ártott ő a légynek sem! Miért kellett mindenáron megölni?}
{228}{}{Megérdemelte!}
{229}{}{Baleset volt...}
{230}{}{Megérdemelteee?! Ő csak egy ártatlan idős hölgy volt! Maga tisztára be van golyózva! Tűnjön el innen!}
{231}{}{Maga beszól nekem, mi?}
{232}{}{Már amúgy is éppen indulófélben voltam... Viszlát!}
{233}{}{Baleset?! Egyes testrészeit még mindig keresik!!! Ajánlom, hogy a jövőben lehetőleg ne szokjon rá az ilyen balesetekre! Árt az üzletnek!}
{234}{}{Megértettem. Hadd kérdezzek valami mást, polgármester úr!}
{235}{}{Legközelebb sokkal óvatosabb leszek.}
{236}{}{Igen, magához szóltam! Lát itt valaki mást is, akinek beszólhattam volna?! Húzzon el a kocsmámból a búsba!}
{237}{}{Maga *HOZZÁM* beszél?}
{238}{}{Megyek már, megyek...}
{239}{}{Micsoda?! Maga süket vagy teljesen segg idióta?! *ÉN* *MAGÁHOZ* beszéltem!!! Takarodjon innen!}
{240}{}{Hát, bizonyára hozzám beszélt, mert nem látok senki mást a környéken...}
{241}{}{Rendben van! Elmegyek! Ne izgassa halálra magát! Ég áldja!}
{242}{}{A törzsükben mindenki ilyen barom? Remek. Akar táncolni? Akkor táncoljunk! Őrség!}
{243}{}{Bizonyára hozzám beszél, de nekem egyáltalán nem tetszik, amit hallok...}
{244}{}{Hohóóó... hé! Nyugi, emberke! Éppen menni akartam.}
{245}{}{Hallottam, hogy Earl Marionnak dolgozol, helyettes seriffként, amíg ő jobban nem lesz. Ez bizonyára alaposan lefoglal majd egy ideig. Akárhogy is legyen, más neked való munka ebben a városban nem nagyon jut eszembe.}
{246}{}{Értem. Akkor hadd kérdezzek még, Ascorti polgármester úr!}
{247}{}{Hé, áruljon még el nekem pár dolgot a bánya tulajdonosairól!}
{248}{}{Mindenesetre köszönöm, polgármester. Viszlát!}
{249}{}{Hallottam, hogy nagyon ügyesen kisegítette Marion seriffet. A város egészen elcsöndesedett, mióta segített neki. Momentán semmi olyan nem jut eszembe, ami megfelelne a képességeinek.}
{250}{}{Köszönet, polgármester! Ez nagyon sokat jelent nekem. Szeretnék más egyébről is feltenni pár kérdést.}
{251}{}{Hé, áruljon még el nekem pár dolgot a bánya tulajdonosairól!}
{252}{}{Azért kösz. Na, akkor beletaposok a lábbuszba... Viszlát!}
{253}{}{Ha jók az értesüléseim, akkor Earl Marion seriff éppen keres valakit, aki kisegítené őt egy kis időre, amíg a tropára ment lába meggyógyul. Talán vele kellene beszélned. Az irodája innen délre van, az utca túloldalán.}
{254}{}{Kösz a tippet! De még mielőtt elrohannék, feltennék néhány kérdést.}
{255}{}{Hé, áruljon még el nekem pár dolgot a bánya tulajdonosairól!}
{256}{}{Talán akkor át kellene néznem oda... Kösz!}
{257}{}{Nos, van a seriff meg a bánya tulajdonosai. Olyasvalakit keresnek, aki szerezne nekik egy alkatrészt a gépeik egyikébe.}
{258}{}{Mi ez a dolog a seriffel?}
{259}{}{Mi a helyzet a bányatulajdonosokkal?}
{260}{}{Érdekes. Még lenne néhány kérdésem, polgármester úr.}
{261}{}{Lehet, hogy körbenézek egy kicsit... Köszi és viszlát!}
{262}{}{A mindenit, úgy van! Hallottam, hogy már elindult és megszerezte egyikőjüknek a chipet.}
{263}{}{Nos, akkor mondjon nekem valamit a seriffről!}
{264}{}{Ja, az én voltam. Akkor most beszéljünk valami másról, polgármester!}
{265}{}{Ó, azt hittem, lesz majd valami új. Akkor viszlát!}
{266}{}{Nem tudok túl sokat róluk. Talán beszélnie kéne Dinamit Den McGrewval a Morningstar bányában, vagy Marge LeBarge-dzsal a Kokoweefben. Mindketten innen északra találhatóak a belvárostól, a temetőn keresztül.}
{267}{}{Kösz! Szóval akkor mi van a seriffel?}
{268}{}{Köszönöm! De még hadd tudakoljak meg pár információt.}
{269}{}{Esetleg el kellene sétálnom hozzájuk, és beszélni velük. Kösz, polgármester úr! Viszlát!}
{270}{}{Az utóbbi időben kezdtek belassulni az aranyszállítmányok, mert a bányászaink túl sok időt töltenek a "repkedéssel"... csak úgy nyomják magukba a Jetet.}
{271}{}{Almost all of the miners are spending more time flying Jet than mining for gold... so our prices
 are up, and our exports are down. Bad for business all the way around.}
{272}{}{Mindenki túlságosan el van szállva a Jettől... ahelyett, hogy megfelelően dolgoznának! Így még a normális aranykitermelés tizedét sem érjük el, és ezért alaposan meg kellett emelni az árakat. Tarthatatlan!}
{273}{}{Úgy tűnik, mindenki beszívott egy jó adag Jetet... Az összes Jet-Pilóta durva detoxikációnak van alávetve. Úgy vélem, valami nem stimmel velük. Nem tudom, mi történt velük, de szerintem hamarosan minden jóra fordul.}
{274}{}{A dolgok már majdnem rendbe jöttek. Mindenki, aki a Jet hatása alatt volt, elkezdett leszokni róla. A bánya termelése és szállítási ütemezésünk hamarosan visszatér a megszokott szintre. Úgy látom, a nehezén már túl vagyunk.}
{275}{}{Hmmm... Ez érdekes! Hadd kérdezősködjek még valami másról is, Ascorti polgármester!}
{276}{}{Értem. Köszönöm az információt, polgármester. Viszlát!}
{277}{}{Édenkert Létrehozást Elősegítő Táska? Ha jól emlékszem, Menedékvárosban gyártottak ilyet. Mindegyik menedékben lennie kell egy ilyennek, de az biztos, hogy a környéken nincs ilyesmi.}
{278}{}{Óh, értem. Még kérdeznék valami mást is, polgármester úr.}
{279}{}{Akkor jobb lesz, ha tovább keresem. Köszönöm, Ascorti úr!}
