{100}{}{Egy reddingi lakost látsz.}
{101}{}{Ez a férfi helyi lakosnak t?nik.}
{102}{}{Egy bányászt látsz.}
{103}{}{Egy reddingi földm?vest látsz.}
{104}{}{Egy helyi embert látsz.}
{105}{}{Egy reddingi n?t látsz.}
{106}{}{Ez a n? idevalósinak t?nik.}
{107}{}{Egy helyi n?t látsz.}
{108}{}{Ez a n? valószín?leg a bányában dolgozik.}
{109}{}{Egy földm?ves n?t látsz.}
{110}{}{Mit néze'?}
{111}{}{Üdvözlünk a Nagyvárosban!}
{112}{}{Helló!}
{113}{}{Régóta itt élsz Reddingben?}
{114}{}{El?ször jársz Reddingben, mi?}
{115}{}{Nem akarunk itt semmilyen z?rt.}
{116}{}{Én is téged néztelek.}
{117}{}{Hogy s mint, idegen?}
{118}{}{Mi a helyzet?}
{119}{}{Hogy vagy?}
{120}{}{Jó napot.}
{121}{}{Ige'.}
{122}{}{Üdv!}
{123}{}{Itt egy férfi, kezében h?s itallal.}
{124}{}{Ez a férfi éppen sört rendel.}
{125}{}{Ez a fickó már túl sokat ivott.}
{126}{}{Egy részeges n?t látsz.}
{127}{}{Ez az úriember nagyon boldognak t?nik.}
{128}{}{Itt egy n?, kezében h?s itallal.}
{129}{}{Ez a n? éppen sört rendel.}
{130}{}{Ez a csaj már túl sokat ivott.}
{131}{}{Egy részeges n?t látsz.}
{132}{}{Ez a n? eléggé kapatosnak t?nik.}
{133}{}{Helló, idegen!}
{134}{}{Helló!}
{135}{}{Hmmm.}
{136}{}{*Büff*}
{137}{}{Glug-glug-glug.}
{138}{}{Kösz, idegen.}
{139}{}{Nem rossz egy törzsbélit?l, én mondom.}
{140}{}{Erre már szükségem volt.}
{141}{}{Mmm-hmmm.}
{142}{}{Köszi.}
{143}{}{Te vagy a legjobb barátom.}
{144}{}{Micsoda egy pajti!}
{145}{}{Te vagy a legjobb!}
{146}{}{A törzsbéliek is emberek.}
{147}{}{Semmi sem ér fel a barátokkal, nem igaz?}
{148}{}{Azt hiszem, énekelni szeretnék...}
{149}{}{A nagy részét visszavonom annak, amit korábban mondtam rólad.}
{150}{}{Micsoda egy barát!}
{151}{}{A törzsbéliek közel állnak hozzánk.}
{152}{}{Hip, hip, hurrrá a törzsbélinek!}
{153}{}{./~ Amíg a munka becsület dolga... én tisztességgel megszomjazom.../~}
{154}{}{./~De amíg élek, bár rövid az élet... vizet már nem iszom./~}
{155}{}{Ez a férfi nagyon otthon érzi magát.}
{156}{}{Ez a férfi éppen eszik.}
{157}{}{A férfi ruhát foltoz.}
{158}{}{A férfi épp pihen.}
{159}{}{Ez a férfi éppen otthona nyugalmát élvezi.}
{160}{}{Ez a n? nagyon otthon érzi magát.}
{161}{}{Ez a n? éppen eszik.}
{162}{}{A n? épp ruhát foltoz.}
{163}{}{A n? épp pihen.}
{164}{}{Ez a n? éppen otthona nyugalmát élvezi.}
{165}{}{Helló!}
{166}{}{Mit csinálsz itt?}
{167}{}{Nem hívtalak meg.}
{168}{}{Menj el! Nincs itt semmilyen alamizsna törzsbélieknek!}
{169}{}{Húzz el! T?nj el!}
{170}{}{Mit keresel a házamban?}
{171}{}{Egy reddingi bányászt látsz.}
{172}{}{Egy bányászt látsz.}
{173}{}{Egy fáradt bányászt látsz.}
{174}{}{Egy arany-bányászt látsz.}
{175}{}{Egy tet?t?l talpig mocskos illet?t látsz.}
{176}{}{Ez az ember biztosan bányász.}
{177}{}{./~ Nincs pénzem, nincs nevem... Mit?l legyen jó kedvem? Üres zseb, üres gyomor... Szembe jön velem a nyomor. /~}
{178}{}{Mer? egy mocsok vagyok.}
{179}{}{Odalenn aztán sötét van ám!}
{180}{}{Ásni muszáj!}
{181}{}{El?bb ásunk, aztán meghalunk odalenn.}
{182}{}{Miért van az, hogy aranyat sosem találnak a felszínen?}
{183}{}{Ez az ember elég izgatott.}
{184}{}{Ez az ember szerfelett ideges.}
{185}{}{Ez az illet? a egyfolytában csak a küzd?teret figyeli.}
{186}{}{Ez az ember eléggé be van sózva!}
{187}{}{Ez az ember valószín?leg pénzt tett fel a küzdelemre.}
{188}{}{Ez az ember izgatottnak t?nik.}
{189}{}{Kapd el!}
{190}{}{Egy heti bérem úszott el... már megint.}
{191}{}{Igen!}
{192}{}{Nyírd ki, nyírd ki, nyírd ki!}
{193}{}{A torkára menj!}
{194}{}{Csonkítsd meg a szemétládát!}
{195}{}{Mássz rá!}
{196}{}{Menj körbe! Ne arra, a másik irányba!}
{197}{}{Vigyázz!}
{198}{}{Ez az!}
{199}{}{Tégy gazdaggá!}
{200}{}{Add nekem azt az új cip?t, bébi!}
{201}{}{Adj egy kicsit abból a cukorból!}
{202}{}{Lábmunka kell, te hülye! Lábmunka!}
{203}{}{Végezz vele!}
{204}{}{Harc!}
{205}{}{Egy fiatal fiút látsz.}
{206}{}{Ez a kisfiú a piacra jött.}
{207}{}{Egy gyerk?cöt látsz.}
{208}{}{Egy tet?t?l-talpig poros kamaszt látsz.}
{209}{}{Ez a gyerek tet?t?l-talpig sáros.}
{210}{}{Egy kölyköt látsz, éppen az orrát piszkálja.}
{211}{}{Egy gyereket látsz, téged bámul.}
{212}{}{Egy pöttöm fiúcskát látsz.}
{213}{}{Egy fiatal lányt látsz.}
{214}{}{Egy csinos kislányt látsz.}
{215}{}{Hé maga, uram!}
{216}{}{Micsinál, uram?}
{217}{}{Te kannibál vagy?}
{218}{}{Fussunk, fussunk!}
{219}{}{Egyszer megérintettem egy halott gekkót.}
{220}{}{Te embereket eszel?}
{221}{}{Én azt hittem, hogy a fejeden szarvaknak kéne lenniük.}
{222}{}{Hová való vagy?}
{223}{}{Messzir?l jöttél?}
{224}{}{Úgysem tudsz elkapni!}
{225}{}{Nyah, nyah, nyah, nyah, nyah!}
{226}{}{Viccesen nézel ki.}
{227}{}{Rossz szagod van!}
{228}{}{Hé maga, hölgyem!}
{229}{}{Micsinál, hölgyem?}
