{100}{}{You see an elderly, frail man.}
{101}{}{Ez Carlson alelnök.}
{102}{}{Habár fizikailag gyenge, a pillantása elárulja, hogy rendkívül er?s jellem. Elszánt ember a javából.}
{103}{}{Mit csinál itt? ?rség!}
{104}{}{Maga nem az én emberem! ?rség!}
{105}{}{T?njön innen!}
{106}{}{Hihetetlenül elfoglalt vagyok. Kérem, jöjjön vissza máskor!}
{107}{}{Nézze, nem akarok durva lenni, de több id?re van szükségem, hogy dolgozni tudjak.}
{108}{}{Sajnálom, de most nincs id?m magával találkozni.}
