{100}{}{Hivatalos személynek néz ki, mert az ÚKK jelvényével díszített egyenruhát viseli.}
{101}{}{Ez csak egy városi őr.}
{102}{}{Lássuk csak: nehéz fiú, van fegyvere, jelvénye, páncélja... hmm, minden bizonnyal egy őr.}
{103}{}{Üdvözlöm az ÚKK-ban. A miheztartás végett: ha van fegyvere, jobb, ha a tokjában tartja. Itt nem tűrjük a fegyverek használatát, idegen.}
{104}{}{Üdvözlöm az ÚKK-ban, az Új Kaliforniai Köztársaság fővárosában, Tandi Elnöknő irányítása alatt.}
{105}{}{Üdvözlet, idegen. Üzleti ügyek miatt jött az ÚKK-ba?}
{106}{}{Az ÚKK üdvözli önt... feltéve, ha nem okoz bajt.}
{107}{}{Hé, maga, tegye el azt a fegyvert. Az ÚKK-ban nem nézik jó szemmel az ilyesmit.}
{108}{}{Idegen, az ÚKK-nak törvényei vannak, és az egyik úgy szól, hogy "Nem tűrjük a fegyvereket". Tegye el, akkor nem lesz semmi zűr!}
{109}{}{Elolvasta a feliratot befelé jövet? "Nem tűrjük a fegyvereket", és ezt mi komolyan is gondoljuk. Megértette?}
{110}{}{Az összes csavargó ugyanolyan. Ez egy békés város, ami azt jelenti, hogy nincs szükségünk a fegyverüket hadonászókra. Tegye el a fegyvert, és nem lesz semmi zűr!}
{111}{}{A kapu zárva van éjszakára. Ha sürgős ügye van, menjen az Őrsre!}
{112}{}{Ha be akar jutni a kapun, az őrség kapitányával kell beszélnie!}
{113}{}{Elég késő van a látogatáshoz. Menjen, keresse meg a kapitányt, talán ő beengedi.}
{114}{}{A maga helyében én most megfordulnék szépen, és nagyon gyorsan elpályáznék innen.}
{115}{}{A magafajtákat nem látjuk szívesen az ÚKK-ban.}
{116}{}{Jöjjön csak közelebb, és nagyon megbánja!}
{117}{}{Figyelmeztettük, úgyhogy távozzon békével! Megértette?}
