{100}{}{Ez egy kövérkés fickó, fényes, kopasz fejjel, és vastag üveg? szemüveggel.}
{101}{}{It's Dr. Henry.}
{102}{}{Ez a fickó annyira nincs képben, hogy az már fáj. Igazi tojásfej, nem a való világban él, annyi szent.}
{103}{}{Bocsásson meg, Dr. Henry vagyok és nagyon elfoglalt. Mit akar?}
{104}{}{Már megint itt van? Mi a fenét akar?}
{105}{}{Hörgh.}
{106}{}{Én}
{107}{}{Enough chit-chat. You've got some papers Mr. Merk wants. Hand 'em over and nobody gets hurt.}
{108}{}{Hallott valaha egy Enklávénak nevezett helyr?l?}
{109}{}{Semmi közöd hozzá.}
{110}{}{Hmm, visszamaradott cranium-fejl?dés... eltompult intellektuális fejlettség. Nem jelent?s testi mutáció... Nem, egyszer?en maga nem alkalmas, attól tartok. Minden jót!}
{111}{}{The Chosen One? Of course, that makes sense. Interesting... I'm afraid I can't help you. I was assigned to cyber-genetics research, not the Vault Behavioral Project.}
{112}{}{Mir?l beszélsz?}
{113}{}{Menedék-viselkedéstan Projekt?}
{114}{}{Kibergenetika? Nem emlékszem, hogy valaha is tanultam ilyesmit.}
{115}{}{Áh, értem. Magának nincs ki az összes kereke. Ég magával!}
{116}{}{Nagy ég, máris többet mondtam, mint kéne. Nem számít... ha bárki is rákérdezne, én nem mondtam semmit.}
{117}{}{Something about extreme sociological conditioning. Mind you, I thought it was all so much mumbo-jumbo, no real science in it at all. But I did hear something about 13 having to be improvised during the course of the experiment. Sloppy work, I'd say.}
{118}{}{Milyen kísérletr?l beszél?}
{119}{}{Mi ez a kibergenetika dolog?}
{120}{}{Azt várja, hogy elhiggyem ezt? Maga most szökött a zártosztályról!}
{121}{}{Oh, it's a whole new field - very exciting. Why I'm working on some projects right now - a radical new concept for the mutant problem. You see, it's really quite simple - mutantcy isn't absolute. It can be cured.}
{122}{}{Természetesen az egyszer? gondolkodású kollégáim a lehet? legdurvább módon próbálják megoldani a problémát. Megtisztulás a javából! Elismerem, hogy voltak korai nehézségek, de mostanra már elimináltuk ?ket... szerintem.}
{123}{}{}
{124}{}{[folytatás]}
{125}{}{Az a helyzet, hogy maga akár segíthetne is nekem a tesztelésben. Érdekelné a dolog?}
{126}{}{Milyen tesztelésre gondolt?}
{127}{}{Még csak az kéne...}
{128}{}{El?készítettem egy apró szérum-mintát, de bele kéne injektálni egy hordozóba.}
{129}{}{Nem hagyom, hogy bármilyen t?t is belémnyomjon!}
{130}{}{Itt hagyjuk abba, már le is léptem!}
{131}{}{Magába? Jaj, dehogyis... a szérum nem tud mit kezdeni egy ilyen alacsony mutagén hányadossal. Ezt egy szupermutánson kell használni. Injektálja bele a szérumot egy szupermutáns testébe, és jelentse nekem az eredményt! Tisztában vagyok vele, hogy Broken Hills tele van velük.}
{132}{}{Mit csinál ez?}
{133}{}{Mi esik le nekem ebb?l?}
{134}{}{Well, it should cause a regression in the genetic matrix that results in the destabilization and assimilation of aberrant DNA, leaving the host free of mutagenic potential. If I knew for sure, I wouldn't need you to test it.}
{135}{}{Mi esik le nekem ebb?l?}
{136}{}{You'll be participating in an important experiment, in fact, the most important, scientific-oh, you mean money. Well, I do have a Cyber-Hound Mk. II, Personal Security Model that I brought with me. I suppose I could have it activated and on-line by the time you got back. Would that do?}
{137}{}{Kiberkutya? Hogyne, jól hangzik.}
{138}{}{Maga teljesen megzavarodott. Gumiszobába kéne zárni!}
{139}{}{Excellent. Here's the serum, fitted up in a stim hypo. All you have to do is use it on a super-mutant and then report back to me. Like I said, Broken Hills - that's the place to look. Good luck.}
{140}{}{Mondja meg a maga Mr. Merkjének, hogy a válaszom egy fikarcnyit sem változott. Nem érdekel semmiféle "közös üzlet". Köszönöm, és minden jót!}
{141}{}{Semmi értelme. Nem megyek vissza. Egyik?jük sem ismerte el az általam végzett munkát, ezért ne próbálja itt kiadni magát a barátomnak! Nagyon szépen köszönöm!}
{142}{}{Hát, akkor nincs mir?l beszélnünk. Minden jót!}
{143}{}{Nos, hogy ment? Sikerült a teszt?}
{144}{}{Igen.}
{145}{}{Nem.}
{146}{}{Ha nem bánja, ne fecséreljük egymás idejét! Már nem vagyok fiatal.}
{147}{}{És... Hogy m?ködött?}
{148}{}{A szérum megölte a szupermutánst! Maga azt mondta, hogy a szérum gyógyít!}
{149}{}{Meghalt, Jim!}
{150}{}{You misunderstood. I said it would remove their mutagenic potential. The process does seem violent on the system, though. Oh well, more refining to do.}
{151}{}{Mi a helyzet a fizetségemmel?}
{152}{}{Maga egy szörnyeteg! Semmi közöm magához!}
{153}{}{Kicsit bugos még. Újra és újra kell próbálkozni!}
{154}{}{Mi a helyzet a fizetségemmel?}
{155}{}{Maga egy szörnyeteg! Semmi közöm magához!}
{156}{}{Természetesen a kiberkutya a magáé. Most azonban dolgom van.}
{157}{}{...so the mutation rate stabilizes over-don't bother me now.}
{158}{}{A környezeti behatások primitív adaptációja. Káprázatos...}
{159}{}{Nincs magánál egy oszcillációs kalibrátor? Persze, miért is lenne...}
{160}{}{ vagyok, a Kiválasztott. A 13-as Menedéket keresem.}
{161}{}{Minden jót ám, a valagam! Itt csak én udvariaskodhatok. Adja át a papírokat, különben egyenként szaggatom le az ujjait! Majd akkor megnézzük, milyen jó orvos is maga...}
{162}{}{Rendben, hagyom inkább.}
{163}{}{Öö... rendben, a papírok abban a asztalban vannak. Vigye csak! Egy kérésem van, a kezemet ne bántsa, kérem!}
{164}{}{Egyen szart, maga kretén! ?rség! ?rség!}
{165}{}{Látom, veszi a dolgokat. El is mondom Mr. Merknek.}
{166}{}{Ezt még megbánja, doki!}
{167}{}{Hé! Tíz másodpercet kap, hogy lerakja azt a köteg papírt, különben hívom az ?rséget!}
{168}{}{Már megint kutakodik? Rendben! Majd a törvény odahat a magafajtára. ?rség! ?rség!}
