{100}{}{Ezen az emberen az ÚKK rendőrség jelvényét látod.}
{101}{}{Ő Jack, az ÚKK rendfenntartó erőinek helyettes megbízottja.}
{102}{}{Ez az ember úgy fel van húzva, mint az óra rugója. Állandóan összeszorítja az állkapcsát, a homlokán kidagadnak az erek, és a vidámság szikrája sem fedezhető fel rajta.}
{103}{}{Nem akarom hallani a bajodat! Zavarj vele valaki mást!}
{104}{}{Ezt nekem nem kell elszenvednem... sem tőled, sem mástól.}
{105}{}{Az átkozott ex-feleségem mindenemet elvette.}
{106}{}{Hülyét csinált belőlem. Senki nem csinálhat hülyét Jackből.}
{107}{}{Napokon belül megmutatom neki. Mindenkinek megmutatom...}
{108}{}{Mit nézel??? Takarodj!}
{109}{}{A franc vinne el! Én Jack vagyok! Az emberek jobb, ha rám figyelnek!}
{110}{}{Van egy bombám idebent, úgyhogy ne próbálkozz semmivel!}
{111}{}{Az emberek mindig kinevetik Jacket, Gyakós Jacknek nevezik... majd az nevet, aki utoljára nevet!}
{112}{}{Háromig számolok és ha Mira nem lesz itt akkora, felrobbantom ezt a kócerájt. Egy...}
{113}{}{Kettő..}
{114}{}{Három...}
{115}{}{Mit akarsz? Mit bámulsz?}
{116}{}{Hagyj békén, megértetted?}
{117}{}{Átkozott exem! Minden az ő hibája!}
{118}{}{Állj hátrébb! Bomba van nálam!}
{119}{}{Ne csináld ezt, Jack! Mindig van jobb megoldás!}
{120}{}{Öhh - állj!}
{121}{}{Ja, persze. Mit tudsz te erről?}
{122}{}{Tudom, hogy néha rosszul néznek ki a dolgok, de a robbantgatás nem old meg semmit.}
{123}{}{Semmit! Szart se tudok a problémáidról. Talán jobb lesz, ha elmondod!}
{124}{}{Mi ez?... Valami trükk? El akarod vonni Jack figyelmét, amíg a haverok ide nem jönnek megölni?}
{125}{}{Ki akar megölni?}
{126}{}{Ne aggódj, senki sem akar bántani!}
{127}{}{A volt nejem, az az átkozott kurva, Mira. Holtan akar látni.}
{128}{}{Hát akkor hagyd a törvényre! Ne így próbáld orvosolni a problémát, Jack!}
{129}{}{Igazad van. Felbérelt, hogy öljelek meg. Tehát mit mondasz? Van hozzáfűznivalód, Jack?}
{130}{}{Ki a franc az a Mira?}
{131}{}{Rendben, te rohadék! Essünk túl rajta!}
{132}{}{Ez vicc! Én vagyok a törvény. Nézd milyen jót tett.}
{133}{}{Gondolkodj el ezen Jack!}
{134}{}{Tehát ha felrobbantod az erőművet, azzal elintézed Mirát?}
{135}{}{Mint ahogy már mondtam, az exem. Rajtakaptam fűvel-fával és most azt mondja, én vagyok a rossz fiú. Megfűzte a bíróságot, hogy minden az övé legyen, és még mindig ki akar velem cseszni.}
{136}{}{Hú... ez kemény. Nagyon igazságtalan. }
{137}{}{Visszaszerezheted. Az idő mindent megold. Teljesen el fog felejteni.}
{138}{}{Hát persze... nem! Francba, nem tudom. Csinálni fogok valamit. Megmutatom az embereknek, hogy nem léphetnek csak úgy át Jacken. }
{139}{}{Ismernek, Jack. Nézz rájuk. Felrobbantod magad és soha többé nem fognak tisztelni.}
{140}{}{Át kéne gondolnod ezt a dolgot! Ha felrobbantod ezt a helyet, alapot adsz a szavainak.}
{141}{}{Nem viccelek, Sherlock! A népek most szépen rám fognak figyelni.}
{142}{}{Senki sem fog rád hallgatni egy bombával a kezedben. Tedd le, gyere ki, és mindent rendbe teszünk!}
{143}{}{Look, think this through. Blow this place up and folks will say, "Jack took the weak way. Let himself get pushed around by his ex-wife." She wins, you lose.}
{144}{}{Tényleg így gondolod?}
{145}{}{Igen, Jack. Ez így igaz, ahogy mondom.}
{146}{}{Persze. Hazudok én szerinted?}
{147}{}{Nem tudom.}
{148}{}{Ne hagyd nyernyi, Jack!}
{149}{}{Itt a lehetőség. Állj a sarkadra! Lökd ki a nyeregből!}
{150}{}{Cseszd meg! Torkig vagy ezzel! Nem is aggódsz értem!}
{151}{}{A fenébe, lehet, hogy igazad van. Amúgy se volt valami jó ötlet.}
{152}{}{Biztos lehetsz, hogy megtettem volna.}
{153}{}{Átkozott Mira, most majd meg kapja.}
{154}{}{Az emberek mostantól tudják, hogy ki is az a Jack.}
{155}{}{Csak maradj nyugton! Nem akarlak bántani!}
{156}{}{Ez téged nem érint!}
{157}{}{Gyerünk, ölj csak meg! Érdekel is engem...}
{158}{}{Ez nem a te dolgod. Hagyj békén!}
{159}{}{Felrobbanok vagy megölsz. Mi a különbség?}
{160}{}{Nem próbállak bántalmazni! Csak azt akarom, hogy emlékezzenek...}
{161}{}{ }
{162}{}{ experience points for taking care of Jack for Mira.}
