{100}{}{Egy furcsa, félig kutya, félig fém dolgot látsz. Úgy látszik, be van kapcsolva.}
{101}{}{Ez itt egy Roboeb! Mindenki kedvence!}
{102}{}{Ez a valami vagy egy szörnyűséges módon összetákolt kutya-gép kombináció vagy teljes mértékben gép és csak külsőre néz ki kutyának. Nehéz megmondani.}
{103}{}{Arf! <katt> Vaúú!}
{104}{}{...bzzzzzz...}
{105}{}{...whirrrrr... Nem vagyok kutyuli.}
{106}{}{Grrrrrrrrrrrrrrrr--}
{107}{}{Vau! Va-va-va-<katt>vaúú.}
{108}{}{<sprzzzt> Miáú... hiba.}
{109}{}{UgatUgatUgatUgatUgatUgatUgat!}
{110}{}{Grrr...}
{111}{}{Háuúúúúú! <kitt-katt> Háúúúú!}
{112}{}{Yipe! Yipe! Yipe!}
{113}{}{Veszély! Veszély!}
{114}{}{Rowf! <tick-tick-tick> Rowf!}
{115}{}{<whirrr> Nem madár, nem repülő, nem is béka, csak én magam - Roboeb!<katt>}
{116}{}{Rooby-Doo!}
{117}{}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{118}{}{Vaú!}
{119}{}{GRRR-ROWF!}
{120}{}{Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{OKÉ}
{122}{}{Nincs kedvem újra csatlakozni hozzád. Viszlát!}
{123}{}{Rowf? <bang> Raggy?}
{124}{}{Hogy vagy?}
{125}{}{Várj itt, amíg vissza nem jövök!}
{126}{}{Egyelőre ennyi.}
{127}{}{<katt> nyaff}
{128}{}{Rá se ránts!}
{129}{}{OKÉ}
{130}{}{HP:}
{131}{}{A kiberebet most nem lehet tovább javítani.}
{132}{}{A kibereb egy kicsit jobban van.}
{133}{}{A kibereb most már teljesen ép.}
{1000}{}{Vau! Va-va-va-<katt>Vaúú?}
{1100}{}{Arf! <katt> Vaúú!}
{1200}{}{Rowf? <bang> Raggy?}
{1300}{}{<katt> nyaff.}
{1400}{}{Háuúúúúú! <kitt-katt> Háúúúú!}
{1500}{}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{1600}{}{Hát hogyne, elteszem...}
{1700}{}{Arf-arf távolág: közel.}
{1800}{}{Arf-arf távolág: közepes.}
{1900}{}{Arf-arf távolág: messze.}
{2000}{}{...whirrrrr... Nem vagyok kutyuli.}
{2100}{}{GRRR-ROWF!}
{2200}{}{Vau! Va-va-va-<katt>Vaúú?}
{2204}{}{Ok, you're at a good distance for now.}
