{100}{}{Ez a köpcös ember egy géppisztolyt hintáztat a kezében.}
{101}{}{Ez a rabszolga-felügyel?.}
{102}{}{A tetoválásáról rögtön tudod, hogy ? egy rabszolga-hajcsár. Úgy néz ki, hogy ? az itteni ?rök f?nöke.}
{103}{}{Mi a fene vagy te? Valami betör??}
{104}{}{Az ÚKK jótev?je! Van neked egy kis gyógyszerem.}
{105}{}{Vortis, van egy behatolónk!}
{106}{}{?rség! Riadó!}
{107}{}{Mit akarsz?}
{108}{}{Kurg?}
{109}{}{Mi ez a hely tulajdonképpen?}
{110}{}{A Felderít?k küldtek.}
{111}{}{A tulajt keresem.}
{112}{}{Hajcsár-testvérem, volna néhány kérdésem.}
{113}{}{Bocs, nem téged kereslek.}
{114}{}{El innen, eridj! Van már itt épp elég hülye ?r.}
{115}{}{Mi van, tökfej, vak vagy? Ez egy rabszolga-karám. Ha többet akarsz tudni, beszélj Vortisszal!}
{116}{}{Is that so? Well, I'm sending you back in a body bag.}
{117}{}{Nyilván Vortisra gondolsz, az öreg fickóra.}
{118}{}{Thanks. Say, you seem like a bright guy. I'll bet you can help me out with a few questions.}
{119}{}{Az öreg fickó? Okés.}
{120}{}{Ha már így állunk, nem igazán tudok nemet mondani. Mi jár a fejedben?}
{121}{}{Kösz, idegen.}
{122}{}{Többet tudok, mint amennyit az öreg Vortis feltételez rólam.}
{123}{}{Több mindent csináltam már, mint amire az emberek többsége számítana. Itt van például ez a meló. Igazán megfelel az igényeimnek.}
{124}{}{Ahogy gondolja.}
{125}{}{Mi a helyzet a mindenfelé elhíresült Felderít?kkel?}
{126}{}{A 13-as Menedéket keresem. Hallottál már róla?}
{127}{}{Hallottál valaha az ÉLET-r?l?}
{128}{}{Hallottál már egy Enklávé nev? csoportosulásról?}
{129}{}{Munkát keresek. Tudsz valakit, aki szerz?dtetne?}
{130}{}{Na, magadra hagylak... Nem akarlak feltartani.}
{131}{}{Those bastards killed my brother and then said it was for the good of the people! I want them dead. If you can help, talk to Vortis.}
{132}{}{Nekem jó ötletnek t?nik.}
{133}{}{Vortisszal? Te vagy itt a bölcsesség forrása. Mit egyebet tudsz még mondani?}
{134}{}{Kösz. Azt hiszem, azt fogom most csinálni. }
{135}{}{Mindenki hallott a 13-as Menedékr?l. Mikor kölyök voltam, én és a haverok egyre csak kerestük. Innen keletre kellene lennie, mindent átkutattuk utána, de soha nem találtuk meg.}
{136}{}{Biztos vagyok benne, hogy mindent beleadtatok. Kérdeznék még valamit, ha már ilyen sokat tudsz.}
{137}{}{Rendben, viszont mennem kell.}
{138}{}{ÉLET, na hiszen... Régen, amikor a Menedék-technikát tanulmányoztam, olvastam róluk. Feltehet?en minden menedéknek volt egy és amikor kinyitották az ajtókat, ezeket kellett el?ször használniuk. Azt mondják, Shady Sands is így kezdte... egy ÉLET-tel. Segít ez valamit?}
{139}{}{Tanulmányoztad a Menedék-technikát? Leny?göz?. Van még néhány kérdésem a számodra.}
{140}{}{Rendben, viszont mennem kell.}
{141}{}{Az Enklávé... Tudod, van egy doki a városban, egy Henry nev?. Valamelyik éjjel, amikor be volt rúgva, beszélt valami Enklávésoknak titulált fickókról.}
{142}{}{Pontoson ezt akartam tudni. Te aztán jól informált ember vagy.}
{143}{}{Csak ennyit akartam t?led, testvérem. Kösz.}
{144}{}{Me, I'm always on the lookout - problem is, nobody ever wants to hire a slaver anymore. Vortis, my boss, has got something hush-hush. And in town the ranchers at the Stockman's Association are always hiring plus Dorothy can always use a hand at the power plant if you got skills. Word is even President Tandi's looking for a specialist.}
{145}{}{Ember, te aztán jó sokmindent tudsz! Az egész napot el tudnám tölteni azzal, hogy téged kérdezgetlek.}
{146}{}{Rendben, megyek és utána nézek a dolgoknak.}
{147}{}{Levágod nekem a... tudod, mir?l van szó... rendben?}
{148}{}{Semmi gond. Mindamellett van itt még valami, amit tudni szeretnék.}
{149}{}{Elintézem ?ket, ne aggódj!}
