{100}{}{Ez itt egy ösztövér, vén fickó, a füle mögött golyóstollal, az orrán pedig szemüveg billeg.}
{101}{}{Vortis, e rabszolga-karám felügyelője.}
{102}{}{A fickónak kábé három foga van. Az ujját és az ingét tintapacák csúfítják. A homlokán egy meglehetősen halvány rabszolga-hajcsár tetoválás díszlik.}
{103}{}{Szóval mit is akarsz?}
{104}{}{Testvérem, üdvözlünk Vortis papánál. Miben segíthetek?}
{105}{}{Kezdesz bosszantani...}
{106}{}{This place is my place and I, Vortis, run an honest and legitimate business no matter what anybody in NCR tells you. Since NCR doesn't allow slaves inside the gates, I mind them for folks who've got business inside.}
{107}{}{Mi van, meggárgyultál? Ez egy rabszolga-karám. Engedélyem van rá.}
{108}{}{}
{109}{}{Csak néhány kérdést tennék fel...}
{110}{}{Munkát keresek.}
{111}{}{He?}
{112}{}{Nem budi? Menek innét elfele.}
{113}{}{Mire való ez a hely?}
{114}{}{Semmi. Rossz hely.}
{115}{}{Nézzétek már... egy kis jótét lélek, egy nyalókáért ácsingózó kölyök jött hozzánk... Fiúk, vezessétek el a szemem elől ezt a kétszínű, álszenteskedő díszpéldányt!}
{116}{}{Baszódj meg!}
{117}{}{Nos?}
{118}{}{A 13-as Menedéket keresem.}
{119}{}{Nincs egy ÉLETED?}
{120}{}{Mit tudsz mesélni nekem erről a városról?}
{121}{}{Te egy mocsokláda hajcsár vagy! Egy okot mondj, hogy ne öljelek meg!}
{122}{}{Úgy hallottam, van itt egy kompánia, akiket az Új Kaliforniai Felderítőknek neveznek. Nem törnek borsot az orrod alá?}
{123}{}{Nem bánod, ha körbenézek?}
{124}{}{Munkát keresel? Hát... lehet, hogy volna valami. Hallottál valaha az Új Kaliforniai Felderítőkről?}
{125}{}{Igen.}
{126}{}{Nem.}
{127}{}{Baszódj meg, ott ahol vagy! Fiúk, vigyétek ki innen ezt a bosszantó kis mocskot!}
{128}{}{Cseszd meg!}
{129}{}{13-as Menedék?! Tűnj innen a francba! Az egy kamu hely! Méghogy 13-as Menedék... meg a valagam.}
{130}{}{Kérdeznék még...}
{131}{}{Hát, köszi, bár sokra nem mentem vele.}
{132}{}{Egy micsodám? Hát, nem tudom, mi az, de nincs nekem olyanom.}
{133}{}{Kérdeznék még...}
{134}{}{Hát, köszi, bár sokra nem mentem vele.}
{135}{}{Új Kaliforniai Köztársaság - csupa önmegtartóztató meg kereskedő lakik itt. Nem csípik a hajcsárokat meg a rabszolgaságot, de hát az istenit, ez a munkám!}
{136}{}{Kérdeznék még...}
{137}{}{Kösz, most mennem kell.}
{138}{}{Valaki rossz irányba terelt téged. Nincs nekem bajom senkivel, különösen nem a Felderítőkkel. Teljesen legálisan működöm itt, szóval nem érheti szó a ház elejét.}
{139}{}{Kérdeznék még...}
{140}{}{Mondhatsz, amit akarsz, nekem most mennem kell.}
{141}{}{Igen, a felderítők bandája a szívem csücske. Munkát keresel?}
{142}{}{Igen.}
{143}{}{Nem.}
{144}{}{Nem, te csak ne nézelődj itt, szararcú! Ez nem múzeum!}
{145}{}{Kérdeznék még...}
{146}{}{Túl ingerlékeny vagy. Engedelmeddel távozom.}
{147}{}{Ami azt illeti... egyesek potenciális problémát látnak bennük. Szerfelett örülnénk neki, ha az északi területeken, New Reno, Klamath meg ilyenek környékén lévő rejtekhelyeikről térképet szerezhetnénk. Fizetnék érte vagy 500 dollárt. Szerinted tudnál ilyesmit szerezni?}
{148}{}{Persze.}
{149}{}{Nem hinném.}
{150}{}{Elmondok valamit akkor. Ezek a Felderítők azt vették a fejükbe, hogy a hajcsárokat és magát a rabszolgaságot is eltörlik a föld színéről. Erővel. Sok problémát okoznak egy rakás keményen dolgozó embernek.}
{151}{}{Titokban működnek, különösen északon.}
{152}{}{A jóéletbe! Külön magyarázatot kell benyújtanom? Megtámadják a rabszolga-kereskedőket, elhajtják az állományt, és lehozzák délre, az ÚKK-ba, ahol a rabszolga-tartás illegális. Na, érdekel?}
{153}{}{Nincs semmiféle "és"! Akarod a munkát vagy sem?}
{154}{}{És?}
{155}{}{Szóval mit akarsz, hogy tegyek?}
{156}{}{Remek. Amint megszerzed a térképet, itt leszek.}
{157}{}{Hol találjak térképet?}
{158}{}{Oké, volna néhány kérdésem azért...}
{159}{}{Benne vagyok. Találkozunk később.}
{160}{}{Honnan a francból tudjam!? Ha tudnám, nálam lenne, nem igaz? Figyelj rám, van egy sejt a városban. Találd meg őket, és gondold át, mire mehetsz velük!}
{161}{}{Csak még néhány kérdést, ha lehet...}
{162}{}{Rendben. Később jövök...}
{163}{}{Szóval megint itt vagy... Megszerezted azt a térképet?}
{164}{}{Igen.}
{165}{}{Nem.}
{166}{}{Még mindig várom, hogy teljesítsd az első feladatot!}
{167}{}{Oh yeah, I forgot.}
{168}{}{Nem, mivel megcsináltad a munkát. Köszönöm.}
{169}{}{Csak egy vagy két kérdést még...}
{170}{}{Nem probléma. Üdv!}
{171}{}{Jó munka volt! Most viszont jobb, ha felszívódsz! Ha esetleg azok a Felderítők rájönnének erre-arra...}
{172}{}{Öröm, ha együtt üzletelünk.}
{173}{}{Ne lófrálj már itt, te ütődött! Valaki még gyanút foghat!}
{174}{}{Rendben, veszem én az adást...}
{175}{}{Mi a faszom...? Őrség! Fogtam egy behatolót!}
{176}{}{Csak menj be oda, és lerobbantom a fejedet! Megértetted?}
{177}{}{It's late and we're closed. Come back in the morning.}
{200}{}{Good work. One more thing though. You're a slaver, right? How 'bout you lend a hand and wipe out those safe houses for me. I could
 pay you for the job - say $1000.}
{201}{}{Good work. One more thing though. You look like a mean sonuvabith. How 'bout you wipe out those safe houses for me. There's a reward for it - say $1000.}
{202}{}{Persze.}
{203}{}{Nem érdekel a dolog.}
{204}{}{Excellent. Here, let me mark these coordinates on your map thingy. Report back when you're done.}
{205}{}{Your loss. Now you best make yourself scarce, in case those Rangers ever wise up.}
{206}{}{Aha. Na, viszlát!}
{207}{}{Actually, do you think you could send some of your men along with me? It'd make things go a hell of a lot faster, and further guarantee success.}
{210}{}{You're back. Did you wipe out the Rangers' safe houses?}
{211}{}{Hell yeah I did. Piece of cake.}
{212}{}{Not yet. I'm still working on it.}
{215}{}{Really? Hot damn. This is the best news I've heard yet. This will be quite a blow to the Rangers. Good work. Here's your pay. Now you best make yourself scarce, the Rangers in town are sure to be looking for you.}
{216}{}{Let em look -- I'm not afraid. Thanks for the money.}
{217}{}{I better get out of town then. See you later.}
{218}{}{It seems everything I do manages to piss someone off. I'm used to it now. Bye.}
{220}{}{Hell no. I'm not rounding up any guys for this. If you feel you can't handle it, then leave.}
{221}{}{I never said I couldn't handle it. I just thought your men would like to join in on the fun. But whatever, I'll handle it on my own, no problem. I'll report back when I'm done.}
{222}{}{Fine, you can count me out, asshole. I'm not gonna be your dog. Bye.}
{223}{}{You calling me chicken? No one calls me that and lives!}
{225}{}{Well, alright. I think I can round up some boys to aid you in this. They'll meet you on the way. You ready to start
 now?}
{226}{}{Give me some time. I'll be back when I am ready.}
{227}{}{I was born ready. Let's rumble.}
{228}{}{I'm ready. Let's go.}
{229}{}{I think I'll pass on all this. I've lost interest. Bye.}
{230}{}{You ready for the raid, or are you here to waste more of my time?}
{231}{}{I need more time.}
{232}{}{I'm ready. Let's go.}
{240}{}{You wipe out the Rangers' safe houses. This deals quite a blow to the Rangers in their fight against slavery.}
{241}{}{I'm looking to buy some slaves.}
{250}{}{Well that's fuckin nice. We don't sell here. Metzger up north in the Den can help you with that.}
{251}{}{I've been there and his stock wasn't up to my standards.}
{252}{}{Seeing how I killed Metzger, I don't know how that's going to be useful to me. I think I'll kill you instead.}
{260}{}{Well aren't you a picky fuck. You do realize that his stock isn't limited to just the Den, right? He's got his own holding pen where slaves are dropped off.}
{261}{}{Interesting. How would I get to this other location?}
{270}{}{What, do you think you can get whatever the fuck you want for free? $1000. Take it or leave it.}
{271}{}{What, do you think you can get whatever the fuck you want for free? Plus, you ooze virtuousness. I don't like that. $2000. Take it or leave it.}
{272}{}{Alright, here.}
{273}{}{Hagyjuk!}
{274}{}{I'll do whatever I want. And I think I'll kill you now.}
{275}{}{Sajnos most nincs pénzem, de majd benézek még ide. Tetszik ez a hely.}
{280}{}{[He points on your map the location of the slaver camp.] It's around there. Now what else are you going to waste my time with?}
{281}{}{I've got what I need. Bye.}
