{100}{}{Egy könyvespolcot látsz, melyet különböz? tárgyak tárolásra használnak.}
{101}{}{Egy régi könyvespolc áll itt, mely elég masszívnak t?nik különféle tárgyak tárolására.}
{195}{}{Úgy t?nik, nincs csapda a könyvespolcon.}
{200}{}{ szerint nincs csapda a könyvespolcon.}
{206}{}{Hé, azt ne rakd ide!}
{207}{}{Hagyd békén azt a rohadt könyvespolcot, különben súlyos szankciókat vezetek be ellened!}
{208}{}{Ne csináld ez!}
