{100}{}{Charlie.}
{101}{}{Egy sovány embert látsz. Hajának egy része nagy csomókban hiányzik a fejér?l, a b?re cafatokban lóg.}
{102}{}{Charlie.}
{103}{}{Egy sovány embert látsz. Hajának egy része nagy csomókban hiányzik a fejér?l, a b?re cafatokban lóg.}
{104}{}{Egy sovány embert látsz, úgy t?nik, komoly bajban van.}
{105}{}{Charlie.}
{106}{}{Egy sovány embert látsz, úgy t?nik, komoly bajban van.}
{107}{}{? Charlie. Már sokkal jobb b?rben van és nem kapkod leveg? után.}
{108}{}{Charlie.}
{109}{}{? Charlie. Már sokkal jobb b?rben van és nem kapkod leveg? után.}
{110}{}{Ez a férfi sugárfert?zött, orvosi kezelésre van szüksége.}
{111}{}{Ez a férfi rémesen néz ki. Nem tudod, mi lehet a baja.}
{112}{}{Kösz, de tényleg jól vagyok, komolyan! Az a Rad-Away cucc bejött.}
{113}{}{You find a vein and inject the Rad-Away into Charlie's system.}
{114}{}{*Öhrkkkk*...}
{115}{}{5 Seconds}
{116}{}{Uhhhhh...*köhh* *köhh*...}
{117}{}{5 Seconds}
{118}{}{Hrnnhhhh...*rotty*...ahhhhh}
{119}{}{5 Seconds}
{120}{}{Mi történt? Sokkal jobban érzem magam.}
{121}{}{Meggyógyítottad Charlie-t.}
{122}{}{*Nyöszörgés*}
{123}{}{*Zihálás*}
{124}{}{*Köhh-köhh*}
{125}{}{*Rotty*}
{126}{}{Most ittam utoljára ebb?l a mocskos vízb?l, az tuti.}
{127}{}{Jól érzem magam. Köszönöm.}
{128}{}{Ez a szar Rad-Away jól meghajt. WC-re kell mennem.}
{129}{}{Kösz idegen, hálás vagyok. Sajnos nem volt pénzem az Auto-dokira.}
{130}{}{Szeretnék adni valamit, de egy árva buznyákom sincs.}
{131}{}{Most ittam utoljára ebb?l a mocskos vízb?l, az tuti.}
{132}{}{Jól érzem magam. Köszönöm.}
{133}{}{Ez a szar Rad-Away jól meghajt. WC-re kell mennem.}
