{100}{}{Egy menedékvárosi Polgárt látsz.}
{101}{}{Üdvözöllek, Polgártárs.}
{102}{}{Csodaszép ez a mai nap, nemdebár?}
{103}{}{A tegnapi tanácsülés nagyon eredményes volt. Rengeteg listát készítettünk. Rengeteget.}
{104}{}{Nem várhatok tovább, vissza kell mennem a városba. }
{105}{}{Jó napot, Polgártárs!}
{106}{}{Bocsánat.}
{107}{}{Utamban vagy.}
{108}{}{Miért nem mész ki a többiekkel?}
{109}{}{Tartana egy kis távolságot, kérem?}
{110}{}{Maradj csak ott!}
{111}{}{Kérem, menjen odébb!}
{112}{}{Takarodj ki innen!}
{113}{}{Vigyázz magadra, vagy hívom az ?röket.}
{114}{}{Figyellek...}
{115}{}{Kívülállók, mint te...}
