{100}{}{A hölgy igen szigorú tekintet?, er?s szemüveget visel, és Menedékváros kezeslábasát hordja. A viselkedése alapján fontos személyiségnek t?nik.}
{101}{}{? Lynette, az Els? Polgár. Elfoglalt n? a javából.}
{102}{}{? Lynette, az Els? Polgár. Elfoglalt n? a javából.}
{103}{}{Ma már kés? van. Holnap reggelre beszéljen le egy id?pontot, és akkor fogadom magát.}
{104}{}{Amint azt már MONDTAM, ilyen kés?n már nem fogadok látogatókat. A LEGTÖBB Polgár már rég ágyban van ilyenkor.}
{105}{}{Egyeztessen le egy holnapi id?pontot, akkor majd fogadom.}
{106}{}{HOLNAP beszélhetünk.}
{107}{}{Nem tudom, hogy jutott át az ?rségen, egyenesen az irodámba, de legjobb lenne, ha most szépen távozna.}
{108}{}{Nem tudom, mi a célja azzal, hogy piszkál, de nem t?röm tovább!}
{109}{}{Lehet, hogy szórakoztatónak találja, ha... piszkál. Remélem, a Nevel?központot is ugyanilyen humorosnak fogja találni.}
{110}{}{Kitüntet a figyelmével, de ha felbosszantanak, fenemód harapós vagyok.}
{111}{}{Én vagyok az Els? Polgár! Nyugovóra kell térnem!}
{112}{}{Távozzon!}
{113}{}{T?nés kifelé!}
{114}{}{Kifelé! Kifelé! Kifelé!}
{115}{}{Csodálatra méltó a kitartása, de ha lehet, inkább távolról csodálnám.}
{116}{}{Ez valami ügyefogyott próbálkozás arra, hogy tudassa velem, tetszem??}
{117}{}{Tetszenek a kis rasztafürtjeim? Szerintem Scott Rodenhizer furcsa humorérzékkel van megáldva.}
{118}{lyn002}{A bátor tetteir?l szóló mendemondák gyorsan terjednek. Tényleg igaz lenne? A kormány még mindig háborúskodni akar?}
{119}{}{Gyak? Gyak, gyak?}
{120}{}{Igen. Akartak használni egy vírust, amely minden életet kiirtana. Elölr?l akarták kezdeni... még az itt felépített várost sem kímélték volna.}
{121}{}{Rosszul hallotta. Utazó vagyok, semmi egyéb... h?s kiváltképp nem. Csak békességet szeretnék, remélve, hogy nem háborgatnak, miközben a pusztaságot járom és a helyem keresem ebben az új világban. Ég magával, Els? Polgár... mindörökre.}
{122}{lyn003}{Még a legegyszer?bb lényekb?l is - mint tenmagad - emberi nagyságok bontakozhatnak ki. Légy jó, kis ügyefogyottam... egész Menedékváros háláját kivívtad.}
{123}{}{(Hug her.)}
{124}{}{Óó... Szia-Szia.}
{125}{lyn004}{Auuu... ugyan, ugyan. Ha bármikor egy kis ölelésre vágysz, látogasd meg Lynett nénit, rendben?}
{126}{}{Oki-doki.}
{127}{}{Viszlát!}
{128}{lyn005}{Micsoda arcátlanság! Micsoda érzéketlenség! Nincsenek tisztában, miféle társadalmat építettünk ki itt az évek során?}
{129}{}{Lehet, hogy fontos tanulságot lehetne levonni ebb?l, Lynette. A világtól elzárt kormány eltökélte magát, hogy megsemmisítik ezt a helyet anélkül, hogy tisztában lennének közösségük értékével. Lehet, hogy Menedékvárosnak felül kéne vizsgálnia, mi történik a világban... és talán a saját, benne elfoglalt helyét is.}
{130}{}{Arcátlanság, érzéketlenség... meglehet. Azt tudom, hogy az általam képviselt t?zer? jelent?s. Minden jót, Els? Polgár.}
{131}{lyn006}{Ebben van ráció. A következ? alkalommal hathatósabban kéne a kormány maradványait felkutatnunk, és szövetkezni velük. Úgy hallottam, nagyszer? er?páncéljaik vannak.}
{132}{}{De hát... na mindegy, felejtse el. Legyen szerencséje, Els? Polgár.}
{133}{}{A felével sincs tisztában, Els? Polgár! Er?visszacsatolás, testnedvek elvezetése, fenyeget? küls?... iszonyat jó cucc.}
{134}{}{Viszlát, minden Polgárok Els?je! Vár a külvilág... meg kell találnom benne a helyem.}
{135}{lyn007}{Kérem, szólítson Lynette-nek... és vigyázzon ha úton van... barátom. Sosem feledjük el. Menedékváros falai közt mindig otthonra lel majd.}
{136}{}{Köszönöm... Lynette.}
{137}{}{Hát igen, JÓ KIS otthon lenne ez a hely. Az új skulóimmal meg a brutál t?zer?mmel öt perc alatt szarrá l?hetnék mindenkit ebben a posványos falanszterben. Szép álmokat, Lynette. Ha ha ha ha ha.}
{138}{lyn008}{Maga menedékruhát visel! Sosem gondoltam volna, hogy valaha találkozom egy másik menedék lakójával. Ez a 13-as menedéké... érdekelne, merre található.}
{139}{}{Hönh?}
{140}{}{Menelék! Menelék!}
{141}{}{Evótam jóól!}
{142}{}{Hela-hela.}
{143}{}{Nem az itteni Menedék az, ahonnan az ?söm származik?}
{144}{}{Fogalmam sincs. Egy nyugati faluból jöttem.}
{145}{}{Nem tudom. Próbálom felkutatni azt a Menedéket, amelyb?l az ?söm származik... tud nekem segíteni?}
{146}{}{Most nincs id?m ecsetelni az egész történetet. Legyen jó napja.}
{147}{lyn009}{A szám a kezeslábasodon nem a Menedék száma, hanem az IQ-d nagysága lesz.}
{148}{}{Mi?}
{149}{}{Van Szááám}
{150}{}{Evótamám!}
{151}{}{[Elcsoszogsz]}
{152}{lyn010}{Nem tudom, honnan tettél szert akkora agykapacitásra, hogy bejuss a városba, de most garantálom, hogy többet nem tévedsz erre... ?rség! Vigyék ki ezt a tökkelütöttet a falon kívülre!}
{153}{}{NE!}
{154}{}{ megy fémes népekkel...}
{155}{lyn011}{Jó napot, idegen. Én Lynett vagyok, az Els? Polgár. Megérdekl?dhetem, mi járatban van errefelé?}
{156}{}{Gyárat? Lyárrat?}
{157}{}{Ööö!}
{158}{}{Viszlát!}
{159}{}{Az Édenkert Létrehozást El?segít? Táska nyomában járok. Nincs maguknak egy fölösleges darab?}
{160}{}{Els? Polgár asszony, az Édenkert Létrehozást El?segít? Táskát keresem. Van az önök városának ilyenje? Megvásárolnám.}
{161}{}{Maga a... maga ennek a Menedéknek a Felvigyázója?}
{162}{}{Bocsásson meg tudatlanságomért, Els? Polgár. Ez a cím azt jelenti, hogy ön az itteni Menedék Felvigyázója?}
{163}{}{Ez Menedékváros? Miért nem élnek Menedékben?}
{164}{}{Most nincs különösebb dolgom itt. Talán máskor.}
{165}{}{Ma semmi különös dolgom nincs itt. Bocsásson meg, hogy zavartam, Els? Polgár. Minden jót!}
{166}{lyn012a}{Egy ilyen MAGAFAJTA honnan hallott egyáltalán az Édenkert Létrehozást El?segít? Táskáról?}
{167}{lyn012b}{Azt a technológiát nem kívülállók számára találták ki.}
{168}{}{Van valami problémája a Kívülállókkal, jóasszony?}
{169}{}{Van valami problémája a Kívülállókkal?}
{170}{}{Elnézését kérem... de van valami baja a Kívülállókkal, Els? Polgár?}
{171}{}{A Menedéklakó leszármazottja vagyok. Az ÉLET azért kell, hogy segítsek a szül?falumon.}
{172}{}{A Menedéklakó leszármazottja vagyok, Els? Polgár. Az ÉLET azért kell, hogy segítsek a szül?falumon.}
{173}{}{Ide az ÉLET-tel, asszony, különben er?vel veszem el!}
{174}{}{Ide az ÉLET-tel, különben er?vel veszem el.}
{175}{}{Akkor nincs mir?l társalognunk. Ég magával.}
{176}{lyn013}{Az a probléma, hogy a Kívülállók részt akarnak a társadalmunkból, s ez egyszer?en megengedhetetlen. Minden kétséget kizáróan magunk is a külvilágot mételyez? anarchiába süllyednénk.}
{177}{}{Értem. A Menedék Felvigyázójával óhajtok beszélni. El tud hozzá vinni?}
{178}{}{Mi vezet rá egy magadfajtát, hogy Menedéklakóvá váljék?}
{179}{}{Ha annyira gy?löli a külvilágot, miért él idekinn, miért nem a Menedékben?}
{180}{}{Nekem erre nincs id?m.}
{181}{}{Hát... értem... Kösz, hogy rám pazarolta az idejét, Els? Polgár.}
{182}{lyn014}{Az ÖSSZES létez? Kívülálló er?szakos. Kulturálatlanok és primitívek, nagyjából az állatok szintjén! Most pedig kifelé. Vagy er?nek erejével vezettetem ki innen.}
{183}{}{Nem én! Addig nem mozdulok, amíg nem kapom meg a válaszaimat!}
{184}{}{"Er?nek erejével kivezettet?" Próba cseresznye! Állok elébe.}
{185}{}{Akkor csendben távozom... most még.}
{186}{}{Megyek én, megyek!}
{187}{lyn015a}{Száz éve nincs itt semmiféle Felvigyázó. Honnan tud a Menedékek Felvigyázóiról?}
{188}{lyn015b}{Már elmondtam. A Felvigyázók a távoli múlt emlékei.}
{189}{}{Az els? Menedéklakó leszármazottja vagyok. Nagyon sok... történetet hallottam a Felvigyázóról.}
{190}{}{Mi történt a Felvigyázóval? Beszélnem kell vele.}
{191}{}{Maga NYILVÁNVALÓAN nem az a személy, aki illetékes itt. Jóasszony, rögvest hozza ide a Felvigyázót!}
{192}{}{Maga NYILVÁNVALÓAN nem az a személy, aki illetékes itt. Rögvest hozza ide a Felvigyázót!}
{193}{}{Vegye úgy, mintha nem is mondtam volna. Most mennem kell. Viszlát!}
{194}{lyn016}{Mit ért az alatt, hogy a Menedéklakó leszármazottja?}
{195}{}{Az els? Menedéklakó ükunokája vagyok.}
{196}{}{Asszony, csak az id?t vesztegetem azzal, hogy szóba elegyedtünk. Ide a Felvigyázót, de rögvest!}
{197}{}{Csak az id?t vesztegetem azzal, hogy szóba elegyedtünk. Hozza ide a Felvigyázót, de rögvest!}
{198}{}{Semmi-semmi, felejtse el. Kés?bb majd folytatjuk a beszélgetést.}
{199}{lyn017a}{Beront a szobámba és még van b?r a képén inzultálni engem, Lynette-et, Menedékváros Els? Polgárát!}
{200}{lyn017b}{Beront a szobámba és még van b?r a képén követel?zni Lynette-nél, Menedékváros Els? Polgáránál!}
{201}{lyn017c}{Távozzék! Ön mostantól fogva "Persona non grata" a városban.}
{202}{}{Addig nem megyek sehova, amíg nem kapok választ a kérdéseimre.}
{203}{}{Megyek... ez alkalommal.}
{204}{lyn018}{Nem, nem, mi nem élünk a Menedék mélyén. Átmeneti megoldásnak szánták, hogy a kiválasztott keveseket megóvja a háborútól, és segítse ?ket egy új világ megteremtésében.}
{205}{}{Honnan tudták, mikor kell elhagyni a Menedéket? Úgy hallottam, a Menedékeket izolálták a külvilágtól.}
{206}{}{Nagyon fontos, hogy beszélhessek a Felvigyázóval. Hozzá tudna vezetni?}
{207}{}{Csak az id?t vesztegetem azzal, hogy szóba elegyedtünk, asszony. Hozza ide a Felvigyázót, de rögvest!}
{208}{}{Csak az id?t vesztegetem azzal, hogy szóba elegyedtünk. Hozza ide a Felvigyázót, de rögvest!}
{209}{}{Nekem erre nincs id?m.}
{210}{}{Köszönöm, hogy id?t szakított rám, Els? Polgár. Viszontlátásra.}
{211}{lyn019}{Nálunk nincs "Felvigyázó". Amikor kijöttünk a felszínre, új kormányt alakítottunk. A Felvigyázói pozíció idejét múlttá vált.}
{212}{}{Meséljen err?l az új kormányról.}
{213}{}{Ezek szerint maga az egykori menedéklakók vezet?je?}
{214}{}{Nem rossz. Megszabadultak a korrupt Felvigyázótól.}
{215}{}{Értem. Köszönet az információért. Viszlát!}
{216}{lyn020}{Amit hallott, nem állja meg a helyét. Adattárunk elég kiterjedt: Menedékünk két évvel a lepecsételés után vette a "minden tiszta" jelet.}
{217}{}{Honnan vették azt a "minden tiszta" jelet?}
{218}{}{Hol van az az adattár?}
{219}{}{Hol találom a Felvigyázót? Beszélnem kell vele!}
{220}{}{Nos, a törzsi legendáink szerint a Menedéket évekre lezárták... és soha semmilyen "minden tiszta" jel nem érkezett.}
{221}{}{Maga hazudik! Az a "minden tiszta" jelzés soha a büdös életben nem érkezett meg!}
{222}{}{Értem. Köszönet az információért. Viszlát!}
{223}{lyn021}{Hát... gondolom a felszínt figyel? monitorok által. Biztos vagyok benne, hogy mindenféle érzékel?k figyelték a környezetet. Különben honnan tudta volna a Felvigyázó, mikor biztonságos a napvilágra menni?}
{224}{}{Ezek a monitorok még léteznek? Láthatnám ?ket?}
{225}{}{Tehát... a Menedékek elhagyása a Felvigyázó parancsa volt?}
{226}{}{Jó is hogy eszembe jut. Hol van a Felvigyázó? Beszélhetnék vele?}
{227}{}{Hazudik! A "minden tiszta" jel soha nem ért el hozzánk!}
{228}{}{Egyel?re... bizonytalan vagyok. Viszlát!}
{229}{lyn022}{A közelmúltban szétszedték, és más rendszerek felújítására használták fel ?ket.}
{230}{}{Hmmm. Tehát a Menedék elhagyására a Felvigyázó adta a parancsot?}
{231}{}{Hol van a Felvigyázó? Most azonnal beszélnem kell vele!}
{232}{}{Nem hiszek magának. Elmondanám, hogy a "minden tiszta" jel soha az életben nem érkezett meg hozzánk!}
{233}{}{Értem. Köszönet az információért. Viszlát!}
{234}{lyn023}{Igen... legalábbis az adattárból erre emlékszem. Mindazonáltal, biztos vagyok benne, hogy számos Polgárunk volt beosztva a felszíni érzékel?k figyelésére.}
{235}{}{Van valami ötlete, hol lehetnek most ezek a felszíni érzékel?k?}
{236}{}{Hol van az az adattár?}
{237}{}{Hol találom a Felvigyázót? Beszélnem kell vele!}
{238}{}{Hazudik! A "minden tiszta" jel soha nem ért el hozzánk!}
{239}{}{Értem. Köszönet az információért. Viszlát!}
{240}{lyn024}{Ha képes lenne felfogni a saját szavai értelmét, mindjárt nyilvánvalóvá válna egy-két dolog. Az adattár biztosítja, hogy az adataink ne jussanak a szájról szájra járó "törzsi legendák" sorsára.}
{241}{}{Hol van az az adattár?}
{242}{}{Hol találom a Felvigyázót? Beszélnem kell vele!}
{243}{}{Nézze, egyet el kell mondanom... a "minden tiszta" jel soha nem érkezett meg hozzánk!}
{244}{}{Eleget hallottam. Minden jót!}
{245}{lyn025}{Van b?r a képén HAZUGSÁGGAL vádolni engem, Lynette-et, Menedékváros els? polgárát? Távozzék! Többé nem szívesen látott vendég nálunk!}
{246}{}{Addig nem megyek sehova, amíg nem kapok választ a kérdéseimre!}
{247}{}{Most az egyszer távozom...}
{248}{lyn026}{The archives are stored within our vault. Only Citizens have access to them... they are
 NOT for Outsiders.}
{249}{}{Remek. Hol találom a Felvigyázót? Rákérdeznék nála erre az adattárra.}
{250}{}{De hát én jogosult Polgár vagyok.}
{251}{}{Hogy lesz a magukfajtából Menedéklakó?}
{252}{}{Hogy válhatok teljes jogú Polgárrá?}
{253}{}{Eleget hallottam. Minden jót!}
{254}{lyn027}{Mi már nem tekintjük magunkat "Menedéklakóknak"... mi már régóta Polgárok vagyunk. Ha a közösségünk részévé akar válni, el?ször is bizonyítania kell a rátermettségét.}
{255}{}{Hogy bizonyítsam be a rátermettségemet?}
{256}{}{Az els? Menedéklakó leszármazottja vagyok - ha ez nem elég, akkor semmi.}
{257}{}{Még gondolkodom efel?l. Viszlát!}
{258}{lyn028}{Félreért engem... nem a világra, hanem a benne él? emberekre gondoltam. Nézzen körül - e falakon belül található minden, ami megmarad a háború el?ttr?l.}
{259}{}{Hol találom a Felvigyázót? Beszélnem kell vele.}
{260}{}{Nem helyes, hogy így gondolkodik. A maga felel?ssége, hogy mindenkin segítsen... nem csak azokon, akik e falakon belül élnek.}
{261}{}{Ah... értem. Köszönöm, hogy id?t szakított rám. Viszontlátásra.}
{262}{lyn029}{Maguk Kívülállók aztán leckét vehetnének "felel?sségtudatból". Folyton segítségért ácsingóznak, de hogy maguk tennének saját magukért valamit, az már smafu. A beszélgetésünk ezennel véget ért... most pedig távozzék, miel?tt szólítom az ?rséget.}
{263}{}{Akkor szólítsa csak az ?rséget, mert több lehet?sége úgysem lesz rá.}
{264}{}{Addig nem megyek sehova, amíg elém nem hozza a Felvigyázót!}
{265}{}{Most az egyszer... elmegyek.}
{266}{}{Nagyon jó. Köszönöm, hogy beszélhettünk. Viszlát!}
{267}{lyn030}{Nem tudom mire vélni ezt az "els? Menedéklakó" dolgot. Létezik egy másik Menedék is? Soha nem voltunk kapcsolatban másik Menedékekkel! Hol található?}
{268}{}{Úgy tudom, hogy EZ volt az a Menedék, ahonnan az ?söm is származik.}
{269}{}{Nem élek Menedékben. Egy nyugati törzs gyermeke vagyok.}
{270}{}{Hát nem is tudom... próbálom megtalálni azt a Menedéket, amelyb?l az ?söm is származik.}
{271}{}{Ha rátaláltam, értesíteni fogom. Addig is viszlát!}
{272}{lyn031}{120 évvel ezel?tt elhagytuk a Menedéket, és a saját Éden Táskánkkal belefogtunk Menedékváros felépítésébe. Tíz évvel kés?bb a Felvigyázó visszavonult és rövidesen megalakult a Polgári Tanács, amely kis id? múlva bevezette az Els? Polgár intézményét.}
{273}{}{Említette az ÉLET-et. Nem volna véletlenül még egy a számomra?}
{274}{}{Akkor tehát maga a város vezet?je?}
{275}{}{120 éve? Az hetven évvel korábban volt, mint ahogy a Menedéklakó móresre tanította a Mestert. Ez a Menedék úgy látszik nem az a Menedék, amit én keresek.}
{276}{}{Értem. Viszlátásra.}
{277}{lyn032}{Pontosan így van... én vagyok Menedékváros Els? Polgára.}
{278}{}{Els? Polgár, sürg?s kérésem lenne. A falumnak éget?en szüksége lenne egy Édenkert Létesítést El?segít? Táskára. Nincs maguknak egy tartalék, amit felhasználhatnék?}
{279}{}{Akkor maga az, akit keresek. Arroyói testvéreim nevében érkeztem, hogy benyújtsam igényünket a minket jogosan megillet? szent ÉLET-re.}
{280}{}{Értem. Köszönöm, hogy beszélt velem. Viszlátásra.}
{281}{lyn033}{Mir?l beszél? A Felvigyázó nagyszer?, feddhetetlen ember volt. Tanításai, és bölcsessége a mai napig meghatározzák a tananyagunkat.}
{282}{}{Hát ezek után van rá esély, hogy ? nem a Menedéklakó által ismert Felvigyázó.}
{283}{}{Miután a Menedéket megmentette, a Felvigyázó elzavarta a Menedéklakót. Miféle dolog ez?}
{284}{}{Akkor tudatlanságban n?ttek fel. Ne pazarolja az id?met, asszony! Hozzon ide valakit, aki segíteni tud nekem!}
{285}{}{Akkor tudatlanságban n?ttek fel. Ne pazarolja az id?met! Hozzon ide valakit, aki segíteni tud nekem!}
{286}{}{Hát ez bizony nem túl szerencsés eset. Na, viszlát!}
{287}{lyn034a}{Beszéljen Gregory F?biztos úrral. ? jogosult az állampolgársági tesztet levezetni. Lejjebb a folyosón megtalálja ?t a tárgyalóteremben.}
{288}{lyn034b}{Illetve... van még egy MÁSIK mód, hogy jogosult Polgárrá váljon.}
{289}{}{Mégpedig?}
{290}{}{Azt hiszem, beszélek a F?biztossal. Kés?bb találkozunk.}
{291}{}{Akkor beszélek a F?biztos úrral.}
{292}{}{Megyek és beszélek Gregory-val. Köszönöm, hogy id?t szakított rám, Els? Polgár.}
{293}{lyn035}{Aligha hinném. Ebben a században végig a Menedéken kívül éltünk, és soha senki nem akart innen elmenni. Mellesleg régen volt két Polgárunk, akiket szám?znünk kellett innen... ezzel b?nh?dtek a tetteikért.}
{294}{}{Tehát maguk HAJÍTOTTÁK KI a Menedéklakót! Azért jöttem, ami jogosan megillet bennünket!}
{295}{}{Mit követett el az a két Polgár?}
{296}{}{Ha nem ez a keresett Menedék, akkor meg kell találnom azt, ahonnan az ?söm származik.}
{297}{}{Mennem kell. Viszlát!}
{298}{lyn036a}{Falut mondott? De hát Menedékruhát visel... mi-miféle faluról beszél? Ne kerteljen! A türelmemnek is van határa.}
{299}{lyn036b}{Falut mondott? El?ször még azt állította, hogy egy Menedékb?l jön, most meg egy faluból? Most akkor melyikb?l? Ne handabandázzon itt nekem, mert kijövök a sodromból!}
{300}{}{Várjon, félreért engem. A Menedéklakó a falum alapítója volt.}
{301}{}{Az én türelmemnek talán nincs határa, asszony??? Na, hozzon ide gyorsan valaki mást... valakit, aki segíthet nekem.}
{302}{}{Az én türelmemnek talán nincs határa, asszony??? Na, hozzon ide gyorsan valaki mást... valakit, aki segíthet nekem.}
{303}{}{Azt hiszem, majd kés?bb visszajövök. Minden jót!}
{304}{lyn037}{Aha... most már értem. Ellenben miféle bizonyítéka van, hogy az ?se egy Menedékb?l származik?}
{305}{}{A legendák, melyeket a falunk törzsf?je hagyott rám, azok bizonyítják.}
{306}{}{A Menedéklakó szent ereklyéit birtoklom... ezt a Menedékruhát és ezt a szent flaskát.}
{307}{}{Nálam van ez a Menedék-kezeslábas és ez a kulacs. Mindkett? az ?sömé volt.}
{308}{}{Fárasztanak a kérdései. Megyek, és keresek valaki mást, aki segíteni tud nekem.}
{309}{}{Mennem kell. Viszlát!}
{310}{lyn038}{Hmm... talán az adattárunk tartalmaz némi információt a maga Menedékér?l.}
{311}{}{Hát... esetleg megnézhetnénk?}
{312}{}{Els? Polgár, nagyon fontos lenne számomra, hogy megtaláljam az ?söm Menedékét. Nagyon hálás lennék, ha vethetnék egy pillantást az adattárra.}
{313}{}{Hmmmm. Köszönöm a tájékoztatást. Viszontlátásra.}
{314}{lyn039}{Sajnálom, de a miénket felhasználtuk Menedékváros építésekor. Nem hinném, hogy volna tartalék, de azért nyugodtan keresse csak fel a Beszerzési Irodánkat, melyet a menedékünk bejáratánál talál meg.}
{315}{}{Nagyszer?! Kérdezhetek még valamit?}
{316}{}{Nem tudja esetleg, hol találhatnám meg a 13-as Menedéket?}
{317}{}{Nagyszer?! Már megyek is oda. Minden jót!}
{318}{lyn040}{Egy koszos menedékruha és egy ütött-kopott kulacs? Ez volna a bizonyíték? Ki tudja, hol guberálta ezeket a "relikviákat"... vagy éppen kit ölt meg érte.}
{319}{}{Kérem... nézze meg ?ket újra. Ezek egyediek!}
{320}{}{Ronggyá jártam a lábam, mire elértem idáig! Legalább nézze meg ?ket, jóasszony!}
{321}{}{Ronggyá jártam a lábam, mire elértem idáig! Legalább nézze meg ?ket!}
{322}{}{Ha ez nem elég, hogy meggy?zze magát, akkor nincs mir?l beszélnünk. Viszlát!}
{323}{lyn041a}{Van valami halvány fogalma arról, milyen elfoglalt ember vagyok? Én vezetem ezt a várost, és nem sok id?m van a maga légb?lkapott igényeivel foglalkozni!}
{324}{lyn041b}{Van valami halvány fogalma arról, milyen elfoglalt ember vagyok? Én vezetem ezt a várost, és nem sok id?m van magával foglalkozni!}
{325}{lyn041c}{Most pedig azonnal távozzék, vagy hívom az ?rséget!}
{326}{}{Hajrá, hívja csak ?ket! Nem fognak ideérni, hogy megmentsék az életét!}
{327}{}{Rendben. Már megyek is.}
{328}{}{Rendben van, Els? Polgár. Viszontlátásra.}
{329}{lyn042}{Törzsi legendáknak higgyek? A törzsi mítosznál valami hihet?bbet is el?áshatna, ha azt akarja, hogy higgyenek magának.}
{330}{}{De hát nálam vannak a Menedéklakó szent ereklyéi... a Menedékruha, és ez a szent flaska.}
{331}{}{Nálam van ez a Menedék-kezeslábas és ez a kulacs. Mindkett? az ?sömé volt.}
{332}{}{Ha nem hisz a szavamnak, mit csináljak, hogy bebizonyítsam a származásomat?}
{333}{}{Rendben. Már megyek is.}
{334}{}{Nagyon jó, akkor nincs mir?l beszélnünk. Minden jót, Els? Polgár!}
{335}{lyn043}{Ránézhetnénk a Menedékbeli számítógépekre. Van rá esély, hogy megtalálja bennük a keresett információt, viszont a számítógépeket csak Polgárok használhatják.}
{336}{}{De hát én jogosult Polgár vagyok.}
{337}{}{Van rá mód, hogy jogosult Polgár legyek?}
{338}{}{Akkor megint elhagyott a szerencsém... Viszlát!}
{339}{lyn044}{A teszt kitöltése helyett egy sokkal, hogyismondjam csak... kifinomultabb módon is bebizonyíthatja a Menedékekhez való elkötelezettségét. Kívülállóként abban a kivételes helyzetben van, hogy pontot tehet egy... számunkra igen kellemetlen szituáció végére.}
{340}{}{Miféle szituációról van szó?}
{341}{}{Mi sem természetesebb ennél. Bármi is kell a Menedéknek, kötelességemnek érzem, hogy segítsek.}
{342}{}{Hát nem tudom... ez az Állampolgársági teszt nem szabványeljárás?}
{343}{}{Nem hinném, hogy én vagyok a legmegfelel?bb a feladatra... viszlát!}
{344}{}{Nem, köszönöm, most már tényleg indulnom kéne. Legyen jó napja, Els? Polgár.}
{345}{lyn045}{Mindkett? gyilkos volt. Boyarsky-t tíz évvel ezel?tt szám?ztük, Richard Moreau-t pedig röviddel azután, hogy elhagytuk a Menedéket. Polgárnak lenni bizalmi kérdés - a b?ncselekményeket pedig nem t?rjük e falakon belül.}
{346}{}{Ha nem ez a keresett Menedék, akkor meg kell találnom azt, ahonnan az ?söm származik.}
{347}{}{Hogyan lesz valakib?l Polgár?}
{348}{}{Eleget hallottam, most már mennem kell.}
{349}{}{Értem. Azért köszönöm, hogy id?t szakított rám, Els? Polgár. Minden jót magának.}
{350}{lyn046}{Mir?l beszél? Valami félreértés lesz. Akármilyen "Menedéklakót" is emleget itt nekem, egy másik Menedékb?l származik, nem innen.}
{351}{}{Ha ez igaz, akkor meg kell találnom azt a másik Menedéket.}
{352}{}{Hazudik! EZ az a menedék, ahonnan az ?söm származik!}
{353}{}{Meglehet. Kösz, hogy beszélt velem. Viszlátásra.}
{354}{lyn047}{Van egy város... már ha városnak lehetne nevezni... t?lünk észak-kelet felé. Tele van afféle... teremtményekkel, amik veszélyes sugárzással szennyezik a talajvizet.}
{355}{}{Hogy képesek mérgezni a talajvizet?}
{356}{}{Mit csináljak velük?}
{357}{}{Most, hogy jobban meggondolom, ez nem olyan dolog, ami felkeltené az érdekl?désemet. Viszlát!}
{358}{lyn048}{Iktassa ki az er?m?vüket, egyszer s mindenkorra! Akkor nem tudnak többet ártani.}
{359}{}{Elég könny?nek t?nik. Visszajövök, ha a szituációt... "megoldottam".}
{360}{}{Egész pontosan hogy szivárog a sugárzás abból az er?m?b?l?}
{361}{}{Hadd gondolkozzam rajta. Kés?bb visszajövök.}
{362}{lyn049}{Azok a... lények... egy sérült atomer?m?vet m?ködtetnek. Immunisak a sugárzásra... nem érdekli ?ket, hogy szép lassan kiirtanak minket a mérgükkel.}
{363}{}{Elsimítjuk a problémát. Visszajövök, ha a szituációt... "megoldottam".}
{364}{}{Úgy t?nik, a világ nevében cselekszenek. Találjon magának másik "Kívülállót", hogy a piszkos munkát elvégezze.}
{365}{}{Ezt még jól át kell gondolnom. Kés?bb visszajövök.}
{366}{lyn050}{Hát nézzük csak... Nahát... ezek eredetiek! Hihetetlen... egy másik Menedék túlél?jéhez van szerencsém! Üdvözlet a Városunkban... rengeteget szenvedhetett a külvilágban.}
{367}{}{Meg kell találnom a Menedéket, ahonnan a népem származik.}
{368}{}{Szükségem van egy Édenkert Táskára. Van maguknak?}
{369}{}{Ó, tehát most már szívesen látott vendég vagyok? Felejtse el... már t?nök is innen.}
{370}{}{You have no idea... but I'll tell you about the Temple of Trials some other time. Goodbye.}
{371}{lyn051}{Felajánlom a lehet?séget, ami kevés Kívülállónak adatik meg. Megpróbálhatja a tesztet, ha óhajtja, de a szituáció megoldása sokkal kifizet?döbb lehet. Megért engem?}
{372}{}{Értem-értem. Miféle szituációról is van szó?}
{373}{}{Értem én. Bármi is kell a Menedéknek, kötelességemnek érzem, hogy segítsek.}
{374}{}{Nem hinném, hogy én vagyok a legmegfelel?bb a feladatra... viszlát!}
{375}{}{Szerintem mennem kéne, de sürg?sen. Viszlátásra, Els? Polgár!}
{376}{lyn052}{Ó... igen-igen. A F?biztos említette, hogy egy új Polgárral b?vültünk. Üdvözöljük, Polgártárs. Ami az adattárat illeti, igen... nos, a Menedékben található. Használja csak, ahogy jól esik.}
{377}{}{Miel?tt átvizsgálnám az adattárat, szeretnék feltenni néhány újabb kérdést...}
{378}{}{Esetleg volna egy ÉLET is raktáron?}
{379}{}{Nagyszer?! Köszönöm.}
{380}{}{Köszönöm, Els? Polgár.}
{381}{lyn053a}{Igen? Miben segíthetek önnek?}
{382}{lyn053b}{Igen? Mit akar?}
{383}{}{Hönh?}
{384}{}{Menelék! Menelék!}
{385}{}{Furiszem???!}
{386}{}{Hela-hela.}
{387}{}{Lenne néhány kérdésem, amit megválaszolhatna.}
{388}{}{Lenne néhány kérdésem, amit megválaszolhatna.}
{389}{}{Hogy lesz valakib?l Menedékváros jogosult Polgára?}
{390}{}{Újragondoltam a Polgárságra tett ajánlatát.}
{391}{}{Térjünk vissza a gekkói er?m?re...}
{392}{}{Van egy-két információm a várost zaklató rablókról.}
{393}{}{Újabb információkat találtam azokról a rablókról, akik a várost zaklatták.}
{394}{}{Találtam valamit Bishop széfjében, ami talán érdekelhetné magát.}
{395}{}{Úgy hiszem, hogy Dr. Troy valami illegális dologba keveredett.}
{396}{}{I must speak with you on the delivery of that holodisk.}
{397}{}{I've changed my mind. I will deliver that holodisk to the Counselor in the NCR.}
{398}{}{Bocs, hogy zavartalak.}
{399}{lyn054a}{Természetesen. Miben segíthetek, Polgártárs?}
{400}{lyn054b}{Természetesen. Miben segíthetek, Kapitány?}
{401}{}{Mit tudna elmondani nekem a városunkat id?r?l-id?re ér? rablótámadásokról?}
{402}{}{A külvárosban belebotlottam Thomas Moore polgártársunkba. ? kicsoda?}
{403}{}{Nincs egy ÉLETED?}
{404}{}{A 13-as Menedéket keresem.}
{405}{}{Ez Menedékváros? Miért nem élnek Menedékben?}
{406}{}{Miért támogatják a rabszolga-tartást?}
{407}{}{Kösz, egyel?re elleszek magam is.}
{408}{lyn055}{Egy nem jogosult Polgárhoz képest maga aztán elég sok id?met elfoglalja.}
{409}{}{De hát én jogosult Polgár vagyok!!!}
{410}{}{Nincs egy ÉLETED?}
{411}{}{A 13-as Menedéket keresem.}
{412}{}{Mire van szükségem, ha netán helyi Polgár akarok lenni?}
{413}{}{Ez Menedékváros? Miért nem élnek Menedékben?}
{414}{}{Miért támogatják a rabszolga-tartást?}
{415}{}{Vegye úgy, hogy nem szóltam. Viszlát!}
{416}{lyn056}{Mi van már megint? Nincs id?m a marhaságaira!}
{417}{}{Reménykedtem, hogy feltehetek egy újabb kérdést.}
{418}{}{Bocsánatot kérek a korábbi kijelentéseimért, Els? Polgár. Reméltem, hogy feltehetek néhány kérdést Menedékvárossal kapcsolatban.}
{419}{}{Tudja, vannak koffeinmentes termékek, amelyek ugyanolyan íz?ek, mint az eredeti.}
{420}{}{Senkit.}
{421}{}{Elnézést, Els? Polgár. Bocsánat, hogy zavartam.}
{422}{lyn057}{Micsoda? Hát nem intézte el ?ket?}
{423}{}{Egy kicsit komplikáltabb az ügy, mint gondoltam. Azok a fickók nem egyszer? rablóbanda... hanem k?kemény zsoldosok.}
{424}{}{Felejtse el. Viszlátásra.}
{425}{lyn058}{Nem emlékszem, hogy elnyerte volna ezt a címet. Mutassa a papírjait!}
{426}{}{Tessék. Minden rendben van vele.}
{427}{}{Ööö... most nincsenek nálam a papírok.}
{428}{}{A papírjaimat? Hát még ki sem állították. Nagyjából egy nap kell még, mire a maga íróasztalára kerül.}
{429}{}{A papírjaimat? Hát még ki sem állították. Nagyjából egy nap kell még, mire a maga íróasztalára kerül.}
{430}{lyn059}{Ne szórakozzon velem, "Polgártárs", különben teszek róla, hogy többet ne tehesse a lábát Menedékváros utcáira. Most pedig távozzék!}
{431}{}{Semmi probléma... Mintha itt sem lettem volna. Viszlát!}
{432}{}{Legyen jó napja, Els? Polgár.}
{433}{lyn060}{BOLONDNAK néz engem? Err?l még én is megmondom, hogy hamisítvány! Ki adta magának ezeket a papírokat? Ha megmondja, magánál hagyom a Napi Belép?jét.}
{434}{}{Egy Skeev nev? Polgár adta a f?kapunál.}
{435}{}{Ööö... nem emlékszem.}
{436}{}{El?bb engem kell elkapnia!}
{437}{lyn061}{Hmmmm... remek-remek. De nehogy idejöjjön nekem, amíg nincsenek meg a Polgárságra jogosító iratai! Minden jót magának!}
{438}{}{Viszlát!}
{439}{}{Legyen jó napja, Els? Polgár.}
{440}{lyn062}{Ó, csakugyan? Ez akkor igazolja a gyanúmat. Menedékvárosi hozzáférését ezennel bevonom. Nyújtsa át a Napi Belép?t és az ?rökkel irány a f?kapu!}
{441}{}{Micsoda? Azt mondta, megtarthatom a Napi Belép?met!}
{442}{}{Nem megyek én sehova! Ha kell magának a Napi Belép?, vegye el!}
{443}{}{Rendben, már itt sem vagyok. Nem akarok itt bajt keverni.}
{444}{lyn063}{Valóban? Ezek szerint véget vet a gekkói vízszennyezésnek? Minden szükséges eszköz bevetésével?}
{445}{}{Igen, véget vetek... a Polgárságot bizonyító papírokért és a Menedékbeli számítógépek használatáért cserébe.}
{446}{}{Nem, nem igazán. Csak meg akartam gy?z?dni, él-e még az ajánlat.}
{447}{lyn064}{Nagyon jó. Jelentse, ha a munkát elvégezte, és megadom magának a Polgárságot bizonyító okmányokat.}
{448}{}{Miel?tt mennék, kérdezhetek valamit?}
{449}{}{Rendben. Ha a szituációt elboronáltam, visszajövök.}
{450}{lyn065}{Megoldotta a szituációt?}
{451}{}{Rájöttem, hogy nekik semmi másra nincs szükségük az er?m? hibátlan m?ködéséhez, mint egy hidroelektromos magnetoszféra szabályzóra.}
{452}{}{Az er?m?vet megsemmisítettem. A maguk helyében mostantól egy kicsit dél-nyugatabbra legeltetném a brahminjaikat.}
{453}{}{Elboronáltam a gekkói er?m? kérdését. A szivárgással többet nem lesz gond, az biztos.}
{454}{}{Nem, még nem. Még dolgozom rajta.}
{455}{lyn066}{Akkor ne fecsérelje a drága id?met! Akkor jöjjön vissza, ha van valami jelentenivalója!}
{456}{}{Rendben. Kés?bb visszajövök.}
{457}{}{Nos rendben. Legyen jó napja, Els? Polgár.}
{458}{lyn067a}{Ezek szerint NEM intézte el a problémát?}
{459}{lyn067b}{Ha még igényt tart a Polgárságunkra, jobban teszi, ha mihamarabb utánanéz a dolgoknak.}
{460}{}{Tehát maguknak Menedékvárosban megvan az alkatrész, amellyel meg lehet javítani a gekkói er?m?vet.}
{461}{}{Rendben. Kés?bb visszajövök.}
{462}{}{Nos rendben. Legyen jó napja, Els? Polgár.}
{463}{lyn068}{És mi van, ha igen? Ez csak egy átmeneti megoldás. Kérem, a problémát HOZZA RENDBE és ne az er?m?vüket. Érthet?en fejeztem ki magam?}
{464}{}{Els? Polgár, nem akarok tiszteletlen lenni, de volna egy megoldás, amelynek segítségével a ghoul-ok megölése vagy az atomer?m?vük lekapcsolása nélkül is megoldhatnánk a problémájukat. Szóval, megkaphatnám az alkatrészt...?}
{465}{}{Azt mondta, hogy javítsam meg az er?m?vet, nem volt szó Gekkó lemészárlásáról.}
{466}{}{Kristálytiszta. Kés?bb visszajövök.}
{467}{}{Igen. Legyen jó napja, Els? Polgár.}
{468}{lyn069a}{Mi ez a... teremtmény... itt magával? Ezek a... lények nem léphetik át a kapuinkat! ?rség! Vezessék ki a behatolókat a f?kapuhoz!}
{469}{lyn069b}{Ó, csakugyan? Én úgy emlékszem, mintha azt állította volna, hogy ön Állampolgár nálunk. Magát többé nem engedjük be Menedékváros kapuin. Az ?rök kikísérik a f?kapuhoz.}
{470}{lyn069c}{Elegem van az oktalanságaiból! Többé nem akarom látni Menedékvároson belül. Az ?rség kivezeti a kapuhoz.}
{471}{}{Meghósz fényll?szem????!}
{472}{}{[Bólogatsz]}
{473}{}{Nem szereti a barátomat, mi? Ez rossz hír, ugyanis ? szereti magát... finom mártásban.}
{474}{}{Az ?rség nem fog id?ben ideérni, hogy megmentsék az életét... "Els? Polgárka."}
{475}{}{Nem kell ide semmiféle ?rség - megyek én magamtól is.}
{476}{lyn070}{Micsoda? Megsemmisítette az er?m?vet? De hát a szennyez?dés! Maga IDIÓTA! Mondjuk az jó, hogy a ghoul-ok mind elt?ntek... na kotródjon a szemem el?l.}
{477}{}{Ejha! És mi a helyzet a Polgárságot bizonyító papírokkal, amit megígért?}
{478}{}{Nézze, azt a pusztítást nem volt könny? véghezvinni. Valami kompenzációra igényt tartok...}
{479}{}{Rendben, rendben, már megyek is.}
{480}{}{Jó napokat, Els? Polgár.}
{481}{lyn071}{Ne szórakozzon velem, különben elintézem, hogy többé az életben ne tegye ide a lábát!}
{482}{}{Nézzen magába, "Els? Polgár". Minden jót!}
{483}{}{Legyen jó napja, Els? Polgár.}
{484}{lyn072a}{Hát megcsinálta?!! Nagyszer?! Felbecsülhetetlen szolgálatot tett Menedékváros számára. Kérem, fogadja el ezt megbecsülésünk jeleként. Ha arra gondolok, hogy egy rakás fosztogató okozta azt a temérdek problémát...}
{485}{lyn072b}{Kiváló. Pont azt kapták, amit megérdemeltek. Ha arra gondolok, hogy egy rakás fosztogató okozta azt a temérdek problémát...}
{486}{}{Hát nem igazán fosztogatók voltak... hanem inkább zsoldosok.}
{487}{lyn073}{Ezek szerint kiiktatta az er?m?vüket?}
{488}{}{Nem, megjavítottam. McClure Tanácsos adta a szükséges alkatrészt, ami lehet?vé tette, hogy az er?m? most tökéletesen m?ködjön.}
{489}{}{Mindent elindéztem.}
{490}{lyn074}{Micsoda? McClure ilyet tett? Gondolom, Polgári papírokat is kiállított magának! Gekkó er?m?vének megjavítása semmit nem old meg. Azok a... teremtmények! Nem lehet bennük bízni! Mi lesz, ha újra szivárogni kezd az er?m??!}
{491}{}{Nem tudom... talán SEGÍTENI kéne nekik megjavítani?}
{492}{}{Nézze, a talajvíz többé nem szennyez?dik, és senki nem sérült meg. A probléma el van boronálva.}
{493}{}{Majd visszajövök, ha lecsillapodott.}
{494}{}{Mennem kell, El?s Polgár. Viszlát!}
{495}{lyn075}{Jobb, ha minden mozdulatára gondosan ügyel, "Polgártárs"! Figyelni fogom magát. Egy rossz lépés, és szám?zzük innen.}
{496}{}{Na, idefigyeljen! Senki nem fog engem fenyegetni, különösen nem egy ilyen bigott, karót nyelt lotyó. Azt tudja, hogy most annyi magának...}
{497}{}{Csak nyugodtan kekeckedjen velem, Lynette, és Menedékvárosnak hamarosan új Els? Polgárt kell választania. Értve vagyok?}
{498}{}{És? Majd szólok McClure-nak, hogy visszakapjam a papírjaimat. ? aztán kiérdemelné, hogy Els? Polgár legyen.}
{499}{}{Majd visszajövök, ha lecsillapodott.}
{500}{}{Legyen jó napja, Els? Polgár.}
{501}{lyn076a}{Kiváló. Derék menekültvárosi Polgárhoz méltó módon járt el.}
{502}{lyn076b}{Örömmel állítom ki a Polgárságot bizonyító dokumentumot, amellyel a jelent?s privilégiumok mellett a szolgáltatásaink igénybevételének széleskör? joga is együtt jár.}
{503}{}{Hát gondoltam, valami anyagi vonzata is lesz a segítségemnek.}
{504}{}{Oda se neki. Csak a munkámat végzem. Viszlát!}
{505}{}{Örömmel tettem, Els? Polgár asszony. Minden jót!}
{506}{}{Nagyszer?, köszönöm. Megyek és ki is próbálom.}
{507}{}{Igazán nagyra értékelem, amit értem tett, Els? Polgár. Viszlát!}
{508}{lyn077ab}{Már eddig is túl sokat kapott, Kívülálló. Az Állampolgárság már önmagában is jutalom.}
{509}{lyn077b}{Az Állampolgárság már önmagában is jutalom.}
{510}{}{Francokat! Nyúljon bele gyorsan a zsebébe, különben a Menedékvárosiak új Els? Polgár után nézhetnek!}
{511}{}{Semmi gond... csak kiváncsi voltam. Viszlát!}
{512}{}{Rendben van, Els? Polgár. Viszontlátásra.}
{513}{lyn077_a}{Egyáltalán nem.}
{514}{}{Kiváncsi leszek, ki veszi át a helyét, ha meghalt... ez ugyanis pillanatokon belül megtörténik.}
{515}{}{Semmi gond... gondoltam próbálkozom. Viszlát!}
{516}{lyn078}{Dr. Troy? ? hogy jön ide?}
{517}{}{He asked me to smuggle in some illegal drugs into the city.}
{518}{}{Az ? dolga a Polgáraink gyógyítása.}
{519}{}{Semmi-semmi... csak félrebeszéltem. Viszlát!}
{520}{lyn079}{Kinek képzeli magát, hogy egy Polgárt ilyen b?nökkel mer vádolni? ?rség! Kísérjék ki ezt a Kívülállót a kapuhoz!}
{521}{}{Az ?rség nem fog id?ben ideérni, hogy megmentsék az életét... "Els? Polgárka."}
{522}{}{Nem kell ide semmiféle ?rség - megyek én magamtól is.}
{523}{}{Ez az igazság! Hinnie kell nekem. Be fogom bi -!}
{524}{lyn080}{Ez nagyon komoly vád. Mivel maga most már Polgártársunknak számít, hitelt kell adnom a szavának... de hát... teljesen biztos benne? Ha így van, a doktor Állampolgárságát visszavonjuk, és szám?zzük ?t.}
{525}{}{Nézze, tudom, hogy nehéz elhinnie, de ? maga kért meg engem, hogy csempésszek be neki Jet-et a városba.}
{526}{}{Nem er?s ez egy kicsit? Egy sima rehabilitáció elég lenne, és folytathatná a praxisát... nincs igazam?}
{527}{}{Oh. Izé... félrebeszéltem. Az találtam mondani, hogy Dr. Troy töménytelen dolgot hozzon be nem törvénytelen drogot.}
{528}{}{Hmmmm. Megyek, és megnézem, találok-e még valamit.}
{529}{lyn081}{Nem létezik, hogy egy ilyen komoly ember drogfügg? lenne. Köszönjük az ?szinteségét, Polgártárs. Most azonnal utánanézek a dolognak.}
{530}{}{Lenne pár kérdésem.}
{531}{}{Nagyszer?. Végül is nem tudtam kívülr?l szemlélni ezt az egész ügyet. Minden jót!}
{532}{}{Köszönöm, Els? Polgár. Csak azt akartam, hogy érvényesüljön az igazság.}
{533}{lyn082a}{Azonnal értesítsen, ha további dolgokra fény derül.}
{534}{lyn082b}{Polgártárs, Menedékváros mindenek felett!}
{535}{}{Lenne pár kérdésem.}
{536}{}{Hogyne. Viszlát!}
{537}{}{Úgy lesz. Köszönöm, Els? Polgár.}
{538}{lyn083}{A törvény az törvény. Ha kivételt teszünk, nem vagyunk jobbak, mint a kívülállók. Még egyszer megkérdezem: teljes mértékben biztos, hogy a vádjai megalapozottak?}
{539}{}{Akkor visszakérdezek. Azzal, hogy Állampolgárságot ígér a gekkói szituáció megoldásáért cserébe, vajon törvényes módon jár el?}
{540}{}{Igen. Megkért, hogy csempésszek Menedékvárosba Jet-et, és vigyem el hozzá.}
{541}{}{Oh. Izé... félrebeszéltem. Az találtam mondani, hogy Dr. Troy töménytelen dolgot hozzon be nem törvénytelen drogot.}
{542}{}{Hmmmm. Megyek, és megnézem, találok-e még valamit.}
{543}{lyn084a}{Jobb lenne, ha átgondolná, mit beszél.}
{544}{lyn084b}{Jobb lenne, ha átgondolná, mit beszél, Kívülálló.}
{545}{lyn084c}{Ha meghallom, hogy Dr. Troy-jal vagy bármelyik más polgártásunkkal balhét csinál, többet be nem teszi ide a lábát. Értve vagyok?}
{546}{}{Uh... sure. Sorry. I had some other questions...}
{547}{}{Kristálytisztán érthet?. Akkor most nem is zavarok tovább.}
{548}{}{Elnézést kérek, Els? Polgár. Viszontlátásra.}
{549}{lyn085}{TERMÉSZETES, hogy csak Polgárokat gyógyít. Arra nincs energiája, hogy Kívülállókkal is foglalkozzon. Arra ott van az Auto-doki.}
{550}{}{Well, you might want to know that the Doctor asked me to smuggle some illegal drugs into the city.}
{551}{}{Oh... Hát akkor volna néhány kérdésem...}
{552}{}{Igen, azoknak, akik megengedhetik maguknak... és ez azt feltételezi, hogy egy darabban voltak képesek eljutni az Auto-dokihoz.}
{553}{}{Hát akkor vegye úgy, hogy nem is mondtam semmit. Viszlát!}
{554}{}{Elnézést kérek, Els? Polgár. Viszontlátásra.}
{555}{lyn086}{Úgy vélem, eljött az id?, hogy távozzék. Ajánlom, hogy fogja rövidre a Menedékvárosban való tartózkodását.}
{556}{}{Miel?tt elmennék, feltennék néhány kérdést...}
{557}{}{Rendben. Már itt sem vagyok.}
{558}{lyn087}{Moore? Az egy bajkever?, semmi más.}
{559}{}{Igaza van. Kívülállókhoz méltó... dolgokban utazik.}
{560}{}{Maga szerint miért bajkever??}
{561}{}{Feltehetnék egy másik kérdést?}
{562}{}{Beszéltem vele... a mondandójának nagy részében van igazság.}
{563}{}{Egyetértek. Ha gondolja... ránézhetek a körmére....}
{564}{}{Akkor vonja vissza az Állampolgári jogait.}
{565}{}{Értem. Távol tartom magam t?le. Viszlát!}
{566}{lyn088}{Állandóan arról akarja meggy?zni Menedékváros Polgárait, hogy "demokráciára" van szükségük, ahogy ? nevezi. Azt papolja, hogy mindenkinek joga lenne beleszólni a törvényekbe, a döntéshozásba. Én ezt anarchiának nevezném.}
{567}{}{"Demokrácia?"}
{568}{}{Hogyan próbálja meggy?zni a Polgárságot?}
{569}{}{Hát elég problémás alaknak t?nik. Mi lenne, ha... a körmére néznék?}
{570}{}{Nem tudja egyszer?en kipenderíteni innen?}
{571}{}{Lenne pár kérdésem.}
{572}{}{Ó, értem, köszönöm az információt. Viszlát!}
{573}{lyn089}{Az adatbázis szerint rengeteg régi állam ilyen berendezkedés szerint m?ködött. Mindannyian tudjuk, HOVA juttatta ez ?ket. El tudja képzelni, mennyi fejtörést okozna egy ilyen társadalom? Ez egyszer?en kivihetetlen.}
{574}{}{Miért lenne kivihetetlen?}
{575}{}{Moore hogyan próbálja meggy?zni a többi Állampolgárt?}
{576}{}{Lenne pár kérdésem.}
{577}{}{Meglehet. Most mennem kéne.}
{578}{}{Köszönöm, hogy id?t szakított rám, Els? Polgár. Viszlát!}
{579}{lyn090}{Egy kormánynak er?s, rátermett vezet?re van szüksége, aki gyorsan képes döntéseket hozni, és megvan a hatalma, hogy érvényt is szerezzen nekik. A parlamentáris kormányzás az nem kormányzás.}
{580}{}{Moore hogyan próbálja meggy?zni a Polgárokat, hogy Menedékvárosnak demokráciában kellene élnie?}
{581}{}{Lenne pár kérdésem.}
{582}{}{Meglehet. Most mennem kéne.}
{583}{}{Köszönöm, hogy id?t szakított rám, Els? Polgár. Viszlát!}
{584}{lyn091}{Kiáll a térre, és végetnemér? beszédeket tart. Ezzel saját magát is nevetségessé teszi. A ÚKK-ban történt betegség ecsetelésével próbál a szívünkhöz szólni, mintha nekünk kéne az egész világot gatyába ráznunk.}
{585}{}{Elég problémásnak t?nik. Ha gondolja... a körmére nézhetek...}
{586}{}{Pedig igaza van. Ez maguknak semmiség lenne. A gyógyászati technológiájuk, hogy úgy mondjam, eléggé impresszív.}
{587}{}{Nem tudja egyszer?en kipenderíteni innen?}
{588}{}{Hát csak kiváncsiskodtam. Viszlát!}
{589}{lyn092}{Már maga is kezdi? Polgártársaink szabadon gondolkodhatnak, de ez... EZ A...! Lehet, hogy maga nem képes eleget tenni az Állampolgárság által megkövetelt felel?sségtudatnak.}
{590}{}{Ez igen... bocsánat! Hát vegye úgy, hogy nem mondtam semmit. Akartam még kérdezni ezt-azt.}
{591}{}{Ha ez azt jelenti, hogy mindenben vakon kell követni magát, akkor lehet, hogy éppen MAGA nem képes eleget tenni az Állampolgárság által megkövetelt felel?sségtudatnak.}
{592}{}{Thomas Moore egy Polgártársunk, és e mozgalom vezet?je.}
{593}{}{Új id?ket élünk, eljött a változás szele.}
{594}{}{Sajnálom, hogy így érez. Viszlát!}
{595}{lyn093}{? nem IGAZI Polgár... már nem. Amikor két évvel ezel?tt idejött, mindent úgy tett, ahogy az egy Polgártól elvárható. Azonban már egy évvel kés?bb... megváltozott. Ellenünk fordult.}
{596}{}{Hát ez megmagyarázna egy-két dolgot. Moore valószín?leg színészkedett egy darabig.}
{597}{}{Talán épp most jött el a megújulás ideje.}
{598}{}{Sajnálom, hogy maga szerint Moore nem "igazi" Polgár. Talán felül kéne vizsgálnia magában, hogy mit jelent Polgárnak lenni.}
{599}{}{Meglehet, hogy ? látta a fától az erd?t. Na, viszlát!}
{600}{lyn094}{Mi fennmaradtunk egy olyan világban, ahol a nagy többség elbukott, és maga beszél nekem változásról? Nézzen ki a külvilágba! Anarchia, pusztulás, betegségek... Menedékváros egy paradicsom ahhoz képest!}
{601}{}{Pontosan ez az, AMIÉRT a változásra szükség van. Másokkal is meg kellene osztaniuk az eredményeiket.}
{602}{}{Néhány embernek paradicsom... Meglehet... bár szerintem a rabszolgáik máshogy vélekednének.}
{603}{}{Nem kívánok vitát nyitni err?l. Viszlát!}
{604}{lyn095}{Menedékvárost kemény munkával, rengeteg Polgár szenvedése árán építettük. A külvilág példát vehetne rólunk és követniük kéne minket, nem csak odakinn kuporogni és alamizsnáért könyörögni.}
{605}{}{Polgárok kemény munkájáról beszél? Akármerre megyek a városban, mindenütt rabszolgákat látok dolgozni.}
{606}{}{Nem kívánok vitát nyitni err?l. Viszlát!}
{607}{lyn096}{Hogy miért támogatjuk a rabszolga-tartást? A rendszerünk évek óta fennáll és igen jól m?ködik. Mindkét félnek csak hasznára van.}
{608}{}{Értem. Kérdezhetek még?}
{609}{}{Biztos vagyok benne, hogy a rabszolgáik másképp vélekednének.}
{610}{}{De hát... úgy adják-veszik az emberi lényeket, mint a brahminokat. Nem éreznek lelkiismeretfurdalást emiatt?}
{611}{}{Nekem erre nincs id?m.}
{612}{}{Köszönöm, hogy id?t szakított rám, Els? Polgár. Viszlát!}
{613}{lyn097}{?k nem rabszolgák, hanem a "szolgáink". Otthont, ételt, ruhát és célokat adtunk nekik. Életet, ha úgy tetszik.}
{614}{}{Hát persze. Miért is akarnának szabadok lenni, amikor maguknak is dolgozhatnak?}
{615}{}{Nézze, nem számít, milyen mézesmázos szavakkal próbálja itt nekem elmismásolni a b?zt, attól ez még k?kemény rabszolgaság.}
{616}{}{Ööö... hogyne. Hát, volna még egy-két kérdésem, ha nem gond.}
{617}{}{Nem kívánok vitát nyitni err?l. Viszlát!}
{618}{}{Hmmmm. Ezt még sosem néztem ebb?l a szemszögb?l. Megyek, végiggondolom.}
{619}{lyn098}{A kétszín?sége elég jól fejlett, meg kell hagyni. A Rabszolga-tartók jelét viseli, de azért a rabszolgaságot kikéri magának.}
{620}{}{Nem kérem ki magamnak. Egyszer?en csak arra próbálok utalni, hogy az igazi munkát ?k végzik itt.}
{621}{}{Nézze, a jelet azért viselem magamon, hogy információkhoz jussak... nem vagyok rabszolga-tartó.}
{622}{}{Fiatal voltam... kellett a pénz...}
{623}{}{Nem kívánok vitát nyitni err?l. Viszlát!}
{624}{lyn099}{Ez hogy kell érteni?}
{625}{}{Moore igazából az Új Kalifornia Köztársaságnak dolgozik.}
{626}{}{Hagyjuk! Kérdeznék valami mást.}
{627}{}{Semmi-semmi. Mennem kell. Viszlát!}
{628}{}{Semmi-semmi. Félrebeszélek. Viszlátásra, Els? Polgár.}
{629}{lyn100}{Gyilkosságról szó se essék. Az ilyesmi semmiféle módon, köntösben, formában nem engedélyezett Menedékváros területén. Akkor sem, ha okunk volna rá. Ne is említse többet.}
{630}{}{Értem. Feltehetek még egy kérdést?}
{631}{}{Look, 'murder' is such an ugly word. I could arrange some sort of accident. . . a drug overdose,
 mauled by a brahmin... any of a number of things can happen in this dangerous world.}
{632}{}{Rendben. Már itt sem vagyok.}
{633}{}{Rendben van, Els? Polgár. Viszontlátásra.}
{634}{lyn101}{Egy Polgár fejében nem járhatnak ilyen gondolatok! Ezennel bevonom a papírjait. Az ?rség megmutatja, merre van a kijárat.}
{635}{}{Az ?rség nem fog id?ben ideérni, hogy megmentsék az életét... "Els? Polgárka."}
{636}{}{Nem kellenek az ?rök. Megyek én magamtól is.}
{637}{lyn102}{Habár ez egybeesne Menedékváros érdekeivel, nem támogatom... addig, amíg nem szegi meg a törvényt, Moore azt mond, amit akar.}
{638}{}{Mit szólna, ha... a körmére néznék?}
{639}{}{Hát ez nem így van. Moore nem egyszer?en a Polgárok egyike... Mások dolgába is beleüti az orrát.}
{640}{}{Feltehetnék egy másik kérdést?}
{641}{}{Nos, ha így halad az illet?, maga alatt vágja a fát. Kés?bb beszélünk.}
{642}{}{Értem. Nos, kösz, hogy meghallgatott, Els? Polgár.}
{643}{lyn103}{ÚKK kém lenne? Ez... ez... ez iszonyúan sok dolgot megmagyarázna. Köszönöm, Polgártárs. Most azonnal kezembe veszem a problémát.}
{644}{}{Lenne pár kérdésem.}
{645}{}{Nagyszer?, köszönöm. Viszlát!}
{646}{}{Köszönöm, Els? Polgár.}
{647}{lyn104}{Jónéhány hónappal ezel?tt kezdték. A lézerlövegek eddig távol tartották ?ket, de nem tudom, meddig leszünk képesek megálljt parancsolni nekik.}
{648}{}{Banditák?}
{649}{}{Lenne pár kérdésem.}
{650}{}{Most mennem kell. Viszlát!}
{651}{}{Sajnálattal hallom ezt. Talán elmennek majd máshova, hogy könnyebb célpontot találjanak. Legyen jó napja, Els? Polgár.}
{652}{lyn105}{Kívülálló söpredék. A városunkat már jó egy évszázada próbálják kifosztani... mindhiába. Alkalomadtán ezeket is hidegre tesszük.}
{653}{}{Hogyhogy alkalomadtán? Eddig miért nem intézték el ?ket?}
{654}{}{Feltehetnék egy másik kérdést?}
{655}{}{Most mennem kell. Viszlát!}
{656}{}{Most mennem kell. Viszontlátásra, Els? Polgár.}
{657}{lyn106}{A bázisuk megtalálása nehézségekbe ütközött. Ráadásul jelent?s t?zer?vel rendelkeznek. Ett?l eltekintve persze minden támadásukat visszavertük... és alig voltak veszteségeink.}
{658}{}{Feltehetnék egy másik kérdést?}
{659}{}{Most mennem kell. Viszlát!}
{660}{}{Köszönöm, hogy id?t szakított rám. Viszlát, Els? Polgár.}
{661}{lyn107}{Nos?}
{662}{}{Megtaláltam a bázisukat. Egy dél felé húzódó dombvidéknél találtam egy barlangrendszert, oda ásták be magukat.}
{663}{}{Kifüstöltem ?ket. Egy dél felé húzódó dombvidék barlangrendszerébe ásták be magukat.}
{664}{}{Az információnak ára van.}
{665}{}{Semmi gond. Viszont mennem kell.}
{666}{lyn108}{Nahát! Kiváló! A városi ?rök eléggé kivannak... magával mi a helyzet? Véget tudna vetni a támadásoknak? Nem lennék sz?kmarkú.}
{667}{}{Nem, jelen pillanatban túlságosan elfoglalt vagyok.}
{668}{}{Megnézem, mit tehetek.}
{669}{lyn109}{Na, jó... Ha megbocsát, én is nagyon elfoglalt ember vagyok. Remélem, kitalál innen.}
{670}{}{El?ször fel szerettem volna tenni néhány kérdést...}
{671}{}{Elnézést, csak megszaladt a pofám. Már itt sem vagyok.}
{672}{}{Nos rendben. Legyen jó napja, Els? Polgár.}
{673}{lyn110a}{Miféle zsoldosokról van szó? Ki bérelte fel ?ket?}
{674}{lyn110b}{Igen, úgy vélem, már említette ezt korábban. Tudja, ki bérelte fel ?ket?}
{675}{}{Le merném fogadni, hogy a New Reno-i Bishop család keze van a dologban.}
{676}{}{A New Reno-i illet?ség? Bishop család.}
{677}{}{Még nem vagyok benne biztos. Dolgozom az ügyön.}
{678}{lyn111a}{Micsoda? Honnan tudja ezt? Miféle bizonyítéka van erre?}
{679}{lyn111b}{Van valami bizonyítéka erre?}
{680}{}{Kézzelfogható bizonyítékom nincs, de New Reno-ban azt rebesgetik, hogy a Bishop-ok állnak a dolog mögött.}
{681}{}{A fosztogatók széfjében találtam ezt a számlakönyvet, melyben Bishop által kitöltött számlák vannak a maguk városa ellen indított három hónapos terrorhadjárat pénzügyeinek bizonyítékaképp... egy hónap ráhagyással, ha maguk esetleg túl sokat akadékoskodnának.}
{682}{}{Egyel?re nincs közvetlen bizonyítékom, de rajta vagyok a problémán.}
{683}{lyn112}{Nem lennék meglep?dve ezen. Bishop nem is olyan régen látogatást tett nálunk, és azt ajánlotta, hogy kössünk szövetséget. Természetesen visszautasítottam. Mi nem paktálunk le b?nöz?kkel.}
{684}{}{Lehet, hogy ezáltal akarta magukat szövetségbe kényszeríteni.}
{685}{lyn113}{Hamarosan segítséget kell kérnünk az ÚKK-tól. Ha netán valami kézzelfogható bizonyítékot találna Bishop tevékenységét illet?en, kérem, hozza el nekünk azonnal!}
{686}{}{Méltányos. Viszont kérdeznék egy s mást...}
{687}{}{Ha találok valamit, tudatni fogom magával.}
{688}{}{Úgy lesz, Els? Polgár. Viszlát!}
{689}{lyn114}{Nem vagyok meglep?dve ezen. Bishop nem is olyan régen látogatást tett nálunk, és szövetséget ajánlott. Természetesen visszautasítottam. Mi nem paktálunk le b?nöz?kkel.}
{690}{}{I think he expected that. I found this holodisc in Bishop's safe. He was hired by NCR to get
 Vault City to join the Republic. When you refused his offer, he hired the mercenaries to attack you
 so you would ask NCR for help.}
{691}{}{Lehet, hogy ezáltal akarta magukat szövetségbe kényszeríteni.}
{692}{lyn115}{Lehetséges... de ez sosem m?ködne. Hamarosan az ÚKK segítségéhez kell folyamodnom. Ön nagy szolgálatot tett Menedékvárosnak. Kérem, fogadja el ezt az elismerésünk jeléül.}
{693}{}{Nagyszer?! Kérdezhetek még valamit?}
{694}{}{Ha hallok még valamit, tudatni fogom magukkal.}
{695}{}{Örömömre szolgált, Els? Polgár. Minden jót magának.}
{696}{lyn116}{Természetesen. Zsoldosokat küldtek a népem kiirtására csak azért mert nem akartam csatlakozni a kormányukhoz? Ezt... ezt nem akarom elhinni.}
{697}{}{A dolog ennél sokkal komplikáltabb, ugyanis Thomas Moore is nyakig benne van.}
{698}{}{Segíthetek bármiben?}
{699}{}{Ez bizony durva egy világ. Viszont most beszélhetnénk a kompenz - }
{700}{lyn117}{Amit maga tesz, nem Polgárhoz méltó, viszont szükségem van az információra. Mennyit akar?}
{701}{}{100 dollárt}
{702}{}{200 dollárt}
{703}{}{400 dollárt}
{704}{}{500 dollárt}
{705}{}{Emiatt ne aggódjon. Ingyen is elmondom az információt.}
{706}{lyn118}{Jól van, fogja a pénzét. Most pedig ki vele, mit tud?}
{707}{}{Megtaláltam a bázisukat. Egy dél felé húzódó dombvidéknél találtam egy barlangrendszert, oda ásták be magukat.}
{708}{}{Kifüstöltem ?ket. Egy dél felé húzódó dombvidék barlangrendszerébe ásták be magukat.}
{709}{}{Az igazat megvallva, semmi újdonságot nem tudok mondani.}
{710}{}{Kösz a pénzért. Most mennem kell.}
{711}{lyn119}{I need you to go immediately to New California Republic and find Counselor Westin,
 Roger Westin. Give him the holodisk. That should insure that no more "raiders" get hired.}
{712}{}{Öö... nem hallotta jól? Westin halott. Úgy értem, baleset érte. Halálos baleset. Hosszú történet.}
{713}{}{Várjunk egy pillanatra. Most menjek az ÚKK-ba? Nem ?k felel?sek ezért az egészért?}
{714}{}{Rendben. Elvállalom.}
{715}{}{Nem, köszönöm, olyan elfoglalt vagyok, mint még soha.}
{716}{lyn120}{Roger Westin valószín?leg az egyetlen Új Kaliforniai ember, akit ?szintének lehetett nevezni, és szimpatizált az ügyünkkel... halála szörny? veszteség.}
{717}{}{Igen, elég kemény fickó volt. Jó gyerek. Csomó életponttal. Szóval... ett?l eltekintve megkapom a jutalmamat a megszerzend? információért, vagy...?}
{718}{}{Igen, én is szomorúan hallottam. Mintha épp csak az imént láttam volna ?t.}
{719}{lyn121a}{Úgy emlékszem, hogy a "fosztogatókért" járó fizetségét már megkapta. A kompenzáció megvolt, most pedig távozzék.}
{720}{lyn121b}{Igen, igen... nagyon jó szolgálatot tett. Kérem... fogadja el a jutalmat t?lünk.}
{721}{}{Nincs jutalom? Erre a politikai szarságra nem volt könny? rájönni. Szerintem valami pluszt érdemlek, nem gondolja?}
{722}{}{Várjon, még nem végeztem. Volna még egynéhány kérdésem.}
{723}{}{Elnézést, csak megszaladt a pofám. Már itt sem vagyok.}
{724}{}{Nagyszer?! Kérdezhetek még valamit?}
{725}{}{Nagyszer?! Köszönöm... most azonban mennem kell.}
{726}{}{Köszönöm, Els? Polgár.}
{727}{lyn122}{Roger Westin valószín?leg az egyetlen Új Kaliforniai ember, akit ?szintének lehet nevezni, és szimpatizál az ügyünkkel...}
{728}{}{Rendben, elviszem neki a lemezt.}
{729}{}{Nem köszönöm. Mostanság túl elfoglalt vagyok.}
{730}{lyn123}{Your patriotism will not go unrewarded. Go now. Time is of the essence.}
{731}{}{Miel?tt útnak erednék, volna néhány kérdésem.}
{732}{}{Elvállalom.}
{733}{}{Számíthat rám, Els? Polgár. Amint visszavittem a lemezt Westinnek, benézek.}
{734}{lyn124}{Akárhogy is legyen, Menedékváros a jöv?ben is mindenek felett fog állni. Ön értékes szolgálatot tett nekünk... kérem, fogadja el ezt elismerésünk jeleként.}
{735}{}{Nagyszer?! Kérdezhetek még valamit?}
{736}{}{Nagyszer?! Köszönöm... most azonban mennem kell.}
{737}{}{Köszönöm, Els? Polgár.}
{738}{lyn125}{Elvitte a lemezt a rendeltetési helyére?}
{739}{}{Nem. Azon gondolkodtam volt, miféle jutalomról beszélt nekem.}
{740}{}{Nem, most túl elfoglalt vagyok ehhez.}
{741}{}{Nem, még nem. Viszont kérdésem az volna néhány...}
{742}{}{Elvittem a lemezt Westin képvisel?nek.}
{743}{}{Még nem. Amint megvagyok, visszajövök.}
{744}{}{Még nem, Els? Polgár. Amint elvittem Westin-nek, visszajövök.}
{745}{lyn126}{Megteszi nekünk?! Remek! Vigye el a Bishop-tól szerzett lemezt, és ne késlekedjen. Sürget az id?.}
{746}{}{Miel?tt útnak erednék, volna néhány kérdésem.}
{747}{}{Elvállalom.}
{748}{}{Számíthat rám, Els? Polgár. Amint visszavittem a lemezt Westinnek, benézek.}
{749}{lyn127}{Believe me, you will not be disappointed. Now please deliver that holodisk.}
{750}{}{Miel?tt útnak erednék, volna néhány kérdésem.}
{751}{}{Rendben, hallgatom.}
{752}{}{Számíthat rám, Els? Polgár. Amint visszavittem a lemezt Westinnek, benézek.}
{753}{lyn128}{Látom, hogy a megállapodásunk nem jelentett semmit magának. Így is jó. A maga menedékvárosi privilégiumait ezennel megvonom. Az ?rség kivezeti magát a kapuhoz.}
{754}{}{Az ?rökkel végzek... miután végeztem magával.}
{755}{}{Oké! Itt a lemez, most megyek.}
{756}{lyn129}{Köszönöm! Nagyon nagy szolgálatot tett nekünk! Westin küldött választ?}
{757}{}{Igen, kezdem a Jöv? Hírnökének érezni magamat. Tessék, azt akarta, hogy adjam át magának ezt a lemezt.}
{758}{}{Nem, elveszítettem.}
{759}{}{Nem, nem adott nekem semmit.}
{760}{lyn130a}{Kiváló. Hadd szkenneljem le.}
{761}{}{Fade out 3 seconds}
{762}{lyn130b}{Az ÚKK-val most jó sokáig nem lesz gondunk.}
{763}{}{Ez bizony jó hír.}
{764}{lyn131}{Most... térjünk rá a fizetségre. Keresse fel Randal-t, a Komforthivatal vezet?jét. Mondja meg neki, hogy én küldtem és majd ? átadja a jutalmát. Még egyszer köszönjük.}
{765}{}{Miel?tt útnak erednék, volna néhány kérdésem.}
{766}{}{Rendben. Hé, jutalom, már itt is vagyok.}
{767}{}{Köszönöm, Els? Polgár. Viszontlátásra.}
{768}{lyn132}{Egyedülálló szolgálatot tett. Oly nagy szolgálatot, hogy tisztségemnél fogva ezennel az ?rség századosának nevezem ki. Fogadja gratulációmat, Kapitány. Megérdemli.}
{769}{}{Ööö... köszönöm.}
{770}{}{Köszönöm, Els? Polgár.}
{771}{lyn133}{Ezenfelül jelentkezzen be Randal-nál, a Komforthivatal vezet?jénél! Mondja meg neki, hogy én küldtem, és megkapja a jutalmát. Lekötelezett bennünket... Kapitány.}
{772}{}{Miel?tt útnak erednék, volna néhány kérdésem.}
{773}{}{Rendben. Hé, jutalom, már itt is vagyok!}
{774}{}{Köszönöm, Els? Polgár. Viszontlátásra.}
{775}{lyn134}{Elvesztette? Az a válasz hihetetlenül fontos volt! Na, mindegy... itt a fizetsége a lemez elszállításáért. Most pedig, ha megbocsát...}
{776}{}{Várjon egy pillanatra! Miel?tt elmennék, volna még néhány kérdésem.}
{777}{}{Kés?bb találkozunk.}
{778}{}{Legyen jó napja, Els? Polgár.}
{779}{lyn135}{Nem adott magának semmit? Különös... akárhogy is legyen, itt a fizetsége a lemez elviteléért. Most pedig, ha megbocsát...}
{780}{}{Várjon egy pillanatra! Miel?tt elmennék, volna még néhány kérdésem.}
{781}{}{Kés?bb találkozunk.}
{782}{}{Legyen jó napja, Els? Polgár.}
{783}{lyn136}{Nos?}
{784}{}{Ezt a hololemezt Bishop széfjében találtam. Az ÚKK bérelte fel, hogy rávegye Menedékvárost a Köztársasághoz való csatlakozásra. Amikor maga visszautasította Bishop ajánlatát, a férfi zsoldosokat bérelt fel, hogy támadják meg Menedékvárost, és emiatt mindenképpen az ÚKK segítségéhez kelljen folyamodniuk.}
{785}{lyn099}{Ez hogy kell érteni?}
{786}{}{Moore igazából az Új Kalifornia Köztársaságnak dolgozik.}
{787}{lyn138}{Az ÚKK-nak kémkedne? Ez... ez... nagyon sok mindent megmagyarázna. Köszönjük, hogy fényt derített erre, Polgártárs. Ezt a problémát azon nyomban a kezembe veszem.}
{788}{}{Az ÚKK problémáról volna szó... van valami, amiben segíthetnék?}
{789}{}{Ezt jó hallani. Egyébként a Reno és az ÚKK ügyében tett dolgokért esetleg számítanék valami jutal - }
{790}{}{?rség!}
{791}{}{Kérem, keresse fel a F?biztost! Nála lesz, amire szüksége van.}
{792}{}{Kérem, keresse meg McClure F?tanácsost! Nála lesz, amire szüksége van.}
{793}{}{Kérem, keresse fel az asszisztensemet! Nála lesz, amire szüksége van.}
{794}{}{Észak}
{795}{}{Dél}
{796}{}{Kelet}
{797}{}{Nyugat}
{798}{}{Észak-nyugat}
{799}{}{Észak-kelet}
{800}{}{Dél-nyugat}
{801}{}{Dél-kelet}
{802}{}{Északra}
{803}{}{Délre}
{804}{}{Kelet felé}
{805}{}{Nyugatra}
{806}{}{Észak-nyugatra}
{807}{}{Észak-keletre.}
{808}{}{Dél-nyugatra}
{809}{}{Dél-keletre}
{810}{}{Nem akarom.}
{811}{}{Köszönöm!}
{812}{}{Köszönöm, hogy id?t szakított rám.}
{813}{}{?rség!}
{814}{}{Én bizony szeretem Scott Rodenhizer-t, aki a karakterek fejeit tervezte.}
{815}{}{Csinosak a kis rasztafürtjeim.}
{816}{}{T-Ray thinks a little too highly of himself.}
{817}{}{Ez jó hír.}
{818}{}{Rendben.}
{819}{}{Minden jót!}
{820}{}{Jó napot, Polgártárs!}
{821}{}{Én viszem el.}
{822}{}{Adja ezt oda nekem!}
{823}{}{Arról semmit se tudok.}
{824}{}{Nem tudom.}
{825}{}{Igen.}
{826}{}{Nem.}
{827}{}{Minden bizonnyal.}
{828}{}{Persze.}
{829}{}{Így van.}
{830}{}{Pontosan.}
{831}{}{Úgy van.}
{832}{}{Hmmmmm.}
{833}{}{Elmagyarázná nekem, hogy a Fallout 2-ben, miért nincsenek fekete f?szerepl?k?}
{834}{}{Menedékváros mindenek felett!}
{835}{}{Menedékváros mindenek felett, Polgártárs.}
{836}{}{A Ratracer információs szolgálata az Ön rendelkezésére áll, Asszonyom!}
{837}{}{Degenerált!}
{838}{}{Kívülálló}
{839}{}{Mocskos Kívülálló...}
{840}{}{*Hortyogás*}
{841}{}{*Zzzzzzzzzzz*}
{842}{}{A lemez tartalma elég kell, hogy legyen a megállításukra. A fosztogatók leleplez?dtek, és ha a lemez tartalma valaha is kikerül az ÚKK küls? kerületeibe, többet nem bízik bennük senki.}
{843}{}{A gekkót érint? adataim szerint még mindig élnek ghoul-ok a városban. A maga Polgári státusza a szituáció megoldásától függ... csakis attól. Érthet? voltam?}
{844}{}{Sajnálom, azt hittem, mindet megöltem.}
{845}{}{Jó kezdés, de a talajvíz továbbra is szennyez?dik. Ki kell iktatnia az er?m?vüket!}
{846}{}{Az valóban segít, de nem oldja meg az els?dleges problémánkat, mégpedig a talajvíz szennyez?dést. Meg kell akadályoznia, hogy az er?m?b?l kiszivároghasson a sugárzás.}
{847}{}{A falunk vezet?je adott nekem egy vizesflaskát, de most épp nincs nálam. A törzsf? által mesélt történetek szerint az ?söm egy Menedékb?l származik.}
{848}{}{A ghoul-okra gondol? Igen, rájöttem, mi a baj az er?m?vükkel.}
{849}{}{Az er?m?be kell egy hidromágnes, öö, egy olyan izé, hogy m?ködhessen. A ghoul-ok szerint maguknak van itt olyanjuk, ezért szeretném elkérni, hogy rendbehozhassuk az er?m?vet.}
{850}{}{Egy hidroelektromos magnetoszféra szabályzóra van szükségük, hogy megjavítsák az er?m?vet és megakadályozzák a talajvíz szennyez?dését. Azt állítják, hogy Menedékvárosban van ilyesmi. Szóval, ha megkaphatnám azt az alkatrészt...}
{851}{}{Na, sebaj. Kés?bb is beszélhetünk err?l.}
{852}{lyn047b}{És ha igen? Ez csak átmeneti megoldás.}
{853}{}{Öö... hát, nem tudom a specifikációkat, de nagyon úgy hangzik, hogy a magneto-izé mind Gekkón, mind Menedékvároson egyaránt segítene. Megkaphatnám azt az alkatrészt?}
{854}{}{Az a helyzet, hogy a szabályzó segítségével az er?m?vet évekig lehetne szennyezésmentesen üzemeltetni. Szóval, ha megkaphatnám azt az alkatrészt...}
{855}{}{Na, sebaj. Talán valaki más majd segít nekem.}
{856}{}{Jól mondja, Els? Polgár. Megnézzük, én magam mit tehetek az ügy érdekében.}
{857}{}{Nem hinném, hogy értem. Van valami probléma Gekkóval... vagy a ghoul-okkal?}
{858}{}{Els? Polgár, kérem, figyelmezzen reám... van valami akadálya, hogy megkapjam az alkatrészt? Megoldaná a maguk Gekkóval fennáló problémáját és a ghoul-okon is segítene...}
{859}{}{Na, sebaj. Talán valaki más majd segít nekem.}
{860}{}{Bocsánat, hogy zavartam, Els? Polgár.}
{861}{}{?k nem akarnak bántani senkit. Csak egyszer?en hiányzik nekik az alkatrész, amivel az er?m?vüket szennyezés nélkül tudnák üzemeltetni. Így hát, ha meg tudnának válni az alkatrészt?l...}
{862}{}{Na, sebaj. Talán valaki más majd segít nekem.}
{863}{}{Jól van akkor. Elnézést, hogy zavartam, Els? Polgár.}
{864}{lyn017b}{Beront a szobámba és még van b?r a képén követel?zni Lynette-nél, Menedékváros Els? Polgáránál!}
{865}{lyn041c}{Most pedig azonnal távozzék, vagy hívom az ?rséget!}
{866}{}{Na, ebb?l elég. Most fájdalmas leckét veszünk...}
{867}{}{Na, sebaj. Talán valaki más majd segít nekem.}
{868}{}{Bocsánat, hogy zavartam, Els? Polgár.}
{869}{}{Szükségem van egy alkatrészre, hogy megjavítsam vele Gekkó er?m?vét.}
{870}{}{Eljuttattad Westin hololemezét Lynette számára.}
{871}{}{Eljuttattad Westin hololemezét Lynette számára, ezért az ?rség Kapitánya lettél.}
{872}{}{Likvidáltad a fosztogatókat, ezzel nagy segítséget nyújtottál Menedékváros számára.}
{873}{}{Leleplezted Moore-t, aki az ÚKK-nak kémkedett.}
{874}{}{Bebizonyítottad, hogy Bishop bérelte fel a fosztogatókat.}
{875}{}{Bebizonyítottad, hogy Bishop-ot az ÚKK bérelte fel.}
{876}{}{Kell nekem egy olyan, hogy megmentsem vele a -}
{877}{}{Várjunk egy pillanatra -}
{878}{}{Felejtse el. Már megyek is.}
{879}{}{Látszik, hogy magával is csak az id?met fecsérlem. Jobb lenne, ha menne, és hozna valakit, aki TUD segíteni nekem.}
{880}{}{Akkor bocsánat, hogy zavartam. Viszlát!}
{881}{}{Ezt jó hallani. Tehát...?}
{882}{}{Köszönöm, Els? Polgár.}
{883}{}{Jaj, elnézést, nem úgy gondoltam -}
{884}{}{Elnézését kérem, Els? Polgár, én csak -}
{885}{}{?rség!}
{1663}{}{They were holed up in a series of caves in the foothills to the South. I convinced their guide to not help them anymore. Without him, they will be unable to find their way through the mountains.}
{1708}{}{They were holed up in a series of caves in the foothills to the South. I convinced their guide to not help them anymore. Without him, they will be unable to find their way through the mountains.}
