{100}{}{Egy ráncos bőrü, hajlott korú férfit látsz.}
{101}{}{John MacRae-t látod.}
{102}{}{Hé te, még soha nem láttalak itt! MacRae vagyok, a tulaj. Miben segíthetek?}
{103}{}{Menedéket keresem.}
{104}{}{Szeretnél eltünni innen?}
{105}{}{Mit csinálsz itt?}
{106}{}{Van valami érdekes a környéken?}
{107}{}{Nyim nyamm}
{108}{}{Tőled? Semmit.}
{109}{}{Menedék? Az egyetlen amit ismerek az a városban van. Egy bazi nagy lyuk ... el se tudod téveszteni!}
{110}{}{Mit lehet itt inni?}
{111}{}{Van valami érdekes a környéken?}
{112}{}{Kösz az útbaigazítást! Viszlát.}
{113}{}{Csak a szokásosat. Sör 20 dolcsi, whisky 30, extra nincs. Kérsz valamit?}
{114}{}{Tudsz valamit a Menedékről?}
{115}{}{Egy sört kérek.}
{116}{}{Egy whiskyt kérek.}
{117}{}{Történt valami érdekes mostanában?}
{118}{}{Ma semmit, kösz. Viszlát.}
{119}{}{A környéken? Mindig a régi nóta ... általában halálra unom magam. Miért, keresel valamit?}
{120}{}{Mit lehet itt inni?}
{121}{}{Tudsz valamit a Menedékről?}
{122}{}{Nem lehet ennyire rossz!}
{123}{}{Semmit. Viszlát!}
{124}{}{Aha ... azt hiszem, túl sokat kapott a fejed! Bocs, de nem dumálok hülyékkel.}
{125}{}{Itt van, húzd fel! Ez az egyetlen buli, amit ezen a csóró helyen találhatsz.}
{126}{}{Nem lehet ennyire rossz!}
{127}{}{Kösz az italt! Azt hiszem, megyek is.}
{128}{}{Nézd! Megkérdeztem, akarsz-e egy italt, utána megmondtam, mennyibe kerül. A legtöbb ember felfogja ezt agyilag. Ha nincs pénzed, minek kérdezősködsz?}
{129}{}{Bocs. Azt hittem, van pénzem. Nem látok bele a zsebembe, vili?}
{130}{}{Ja...bármit. Na mentem.}
{131}{}{Rosszabb. A Polgárok nem isznak túl sokat, így csak a kereskedők csinálnak némi forgalmat. Egyébként mellékesen megemlíteném, hogy a  következő topisnak aki alkudozni merészel, szétrúgom a seggét.}
{132}{}{Úgy hangzik, mintha kicsit eleged lenne ebből a helyből.}
{133}{}{Sajnálom. Mit tudsz a Menedékről?}
{134}{}{Mindenki követ el hibákat ... van aki többet, van aki kevesebbet. Szóval, mit szeretnél?}
{135}{}{Történt valami érdekes mostanában?}
{136}{}{Ma semmit, kösz. Viszlát.}
{137}{}{Ja, remélem, elhúzhatok innen a francba.}
{138}{}{Miért nem mész el?}
{139}{}{Kimenni a pusztába ... egyedül? Unatkozom, de hülye azért nem vagyok.}
{140}{}{Miért nem tartassz velem?}
{141}{}{Hát akkor, sok szerencsét!}
{142}{}{Hát ... úgy tűnik, épp elegen vagytok így is.}
{143}{}{Rendben. Sok szerencsét!}
{144}{}{Tudod mit? Nem is hangzik olyan rosszul. Számíthatsz rám.}
{145}{}{Aha, mit?}
{146}{}{Légyszíves, menj az utamból!}
{147}{}{Hogy vagy?}
{148}{}{Gyógyítsd meg magad!}
{149}{}{Várj itt, amíg vissza nem jövök!}
{150}{}{Te! Ehhem!}
{151}{}{Egyelőre ennyi.}
{152}{}{OK, everything's stitched up. Let's get going.}
{153}{}{OK, nagyjából mindent megcsináltam.}
{154}{}{Ez bőven megteszi, de jó lenne még pár stimpakk.}
{155}{}{Már mindent elhasználtam, de így is elég gyűrött vagyok. Van még pár stimpakkod?}
{156}{}{Részesítsd elsősegélybe magad.}
{157}{}{Hagyjuk!}
{158}{}{Oké.}
{159}{}{OK, itt várok.}
{160}{}{Hagyjuk!}
{161}{}{Oké.}
{162}{}{Induljunk!}
{163}{}{Oké.}
{164}{}{Nézd, épp elég ember van már a sarkadban.}
{165}{}{Ja, vele mész.}
{166}{}{Nem ... asszem ezt most kihagyom.}
{167}{}{Azt hiszem, inkább maradok még egy kicsit.}
