{100}{}{McClure F?tanácsost látod.}
{101}{}{Egy id?sebb menedékvárosi hivatalnokot látsz. A haja már foltokban ?szül.}
{102}{}{McClure F?tanácsost látod.}
{103}{}{Egy id?sebb menedékvárosi hivatalnokot látsz. A haja már foltokban ?szül.}
{104}{}{Már hallottam a h?stetteir?l, Kiválasztott. Mindannyian az adósai vagyunk.}
{105}{}{Még táblázatba kell foglalnom ezeket a listákat. Jöjjön vissza reggel, akkor majd fogadom!}
{106}{}{Egy ghoul?! ?rség ! ?rség !!!}
{107}{}{Egy mutáns?! ?rség ! ?rség !!!}
{108}{}{Nincs semmi mondanivalóm az ön számára. Távozzon, vagy hívom az ?röket!}
{109}{}{Jó napot ... Kapitány, ugye? Sokat hallottam már önr?l. Segíthetek valamiben?}
{110}{}{Jó napot ... Polgártárs, ugye? Hallottam, hogy közösségünk új taggal b?vült. Tudok valamiben segíteni?}
{111}{}{Üdvözlöm ... segíthetek valamiben?}
{112}{}{Jó napot, Kapitány. Remélem, minden rendben van?}
{113}{}{Jó napot, Polgártárs. Segíthetek valamiben?}
{114}{}{Igen? Szüksége van még valamire?}
{115}{}{Mik..ull..ásh?}
{116}{}{[Elcsoszogsz]}
{117}{}{Feltehetek néhány kérdést?}
{118}{}{Ki vagy te?}
{119}{}{Csak nézel?döm, köszönöm. Viszlát!}
{120}{}{Hogy jutott be a városba? ?rség! Itt egy Kívülálló, kérem kísérjék a kapuhoz!}
{121}{}{Én nem menni, én nem menni!}
{122}{}{Ááá... Kérni nem menni. Én leszek jó!}
{123}{}{Természetesen, Kapitány.}
{124}{}{Természetesen, Polgártárs.}
{125}{}{Mit szeretne tudni?}
{126}{}{Mivel foglalkozik?}
{127}{}{Egy Édenkert Létrehozást El?segít? Táska nyomában járok.}
{128}{}{Mit tud mondani az Els? Polgárról?}
{129}{}{Szeretnék néhány dolgot megtudni Gekkóról.}
{130}{}{Mit tudsz mondani Reddingr?l?}
{131}{}{Szeretnék önnel Reddingr?l beszélgetni.}
{132}{}{Hogy lehet valakib?l Polgár?}
{133}{}{Szerintem önnek van olyan alkatrésze, amivel megjavíthatom a gekkói er?m?vet.}
{134}{}{Megjavítottam Gekkó er?m?vét.}
{135}{}{Van egy gazdálkodási adatlemezem az ön számára. Tessék. Valószín?leg érdekesnek fogja találni.}
{136}{}{Tudom, hogyan lehet optimalizálni a gekkói reaktor teljesítményét.}
{137}{}{Itt van a gekkói reaktor adat-lemeze. Tudná optimalizálni?}
{138}{}{Kösz, egyel?re elleszek magam is.}
{139}{}{Én McClure F?tanácsos vagyok. És ön ...?}
{140}{}{Semmi közöd hozzá.}
{141}{}{. Örülök, hogy találkoztunk.}
{142}{}{Sajnos rohannom kell. Talán majd máskor bemutatkozhatunk egymásnak.}
{143}{}{Ilyen durva udvariatlanság a Kívülállókra jellemz? és nem a Polgárainkra. Én Menedékváros Tanácsának vezet?je vagyok. Tanúsítson tiszteletet irántam, különben visszavonom a Polgárságát!. Megértett?}
{144}{}{Bassza meg, vénember!}
{145}{}{Rendben. Már úgyis menni akartam.}
{146}{}{Sajnálom, nem akartam megsérteni önt.}
{147}{}{Felháborító! Ekkora pimaszságot nem t?rök egy Kívülállótól! Adja ide a Napi Belép?jét és távozzon! A magafajtának nincs helye a városunkban.}
{148}{}{Nem adok magának semmit. Akarja? Gyerünk, vegye el!}
{149}{}{Én nem vagyok Kívülálló, hanem Polgár!}
{150}{}{Oké... oké, megyek.}
{151}{}{Kötve hiszem. Hadd lássam a papírjait!}
{152}{}{Tessék. Itt van!}
{153}{}{Szeretné látni a papírjaimat? Gyerünk, vegye el!}
{154}{}{Nem tudom, hogy lehet egy ilyen tiszteletlen emberb?l Polgár, de ezek a papírok rendben vannak. Különös... nem emlékszem, hogy valaha is láttam volna önt. Mindenesetre ... megbecsülöm a polgárságát.}
{155}{}{Átkozottul igaza van! Meg kell becsülnie a polgárságomat!}
{156}{}{Ja, oké. Már itt sem vagyok.}
{157}{}{Soha többé ne szóljon hozzám! Ha megteszi, esküszöm, hogy visszavonom a Polgárságát. Végeztem!}
{158}{}{Minden jót!}
{159}{}{Azt próbálja meg...  nagyon megkeserüli}
{160}{}{Gyenge öregember. Nekem maga a fél fogamra sem elég.}
{161}{}{Rendben! Polgár vagy sem, takarodjon innen! ?rség!  Mutassák meg ennek a degeneráltnak a kijáratot!}
{162}{}{Megyek. Ez a hely egyébként is szívás.}
{163}{}{Nem megyek én sehova innen!}
{164}{}{Mit tehetek magáért?}
{165}{}{Fogalmam sincs, öreg. TUD nekem segíteni?}
{166}{}{Egy Édenkert Létrehozást El?segít? Táska nyomában járok.}
{167}{}{Feltehetek néhány kérdést?}
{168}{}{Nem, köszönöm. Csak körülnéztem az épületében.}
{169}{}{Egy ÉLET-et? Ha jól tudom, nekünk csak egy volt bel?le, amit fel is használtunk. Valahol azonban azt olvastam, hogy volt egy tartalékunk is.  Ez már a születésem el?tt tönkrement, de lehet, hogy van egy másik ...}
{170}{}{Volna egy másik ...???}
{171}{}{Igen. A régi kormány egyszer elfuserált egy szállítmányt és mi kaptuk azt, amit a tizenhármas Menedékbe küldtek. Valószín?leg oda vitték azt az ÉLET-et, amit a meghibásodott helyett nekünk küldtek.}
{172}{}{És mi volt a tizenhármas Menedéknek szánt szállítmányban?}
{173}{}{Mit történt azzal az ÉLET-tel, ami tönkrement?}
{174}{}{Feltehetnék egy másik kérdést?}
{175}{}{Értem. Köszönöm az információt.}
{176}{}{Mintegy száz darab víztisztító-csip. Nem tudom, miért küldtek ennyit... nekünk még sosem volt problémánk vele. Mióta itt élünk, az eredeti chipet használjuk.}
{177}{}{Mit történt azzal az ÉLET-tel, ami tönkrement?}
{178}{}{Feltehetnék egy másik kérdést?}
{179}{}{Köszönöm, hogy rabolhattam az idejét. Viszlát!}
{180}{}{A nyelve borotvaéles. Kés?bb majd még beszélünk, miután elállítottam a vérzést.}
{181}{}{Darabokra szedtük, az alkatrészeit pedig más berendezésekhez használtuk fel.}
{182}{}{Mi volt abban a szállítmányban, ami a 13-as Menedék felé tartott?}
{183}{}{Feltehetnék egy másik kérdést?}
{184}{}{Értem. Kösz, hogy id?t szakítottál rám.}
{185}{}{? a nép vezet?je, a mostani nehéz id?kben ? a közösségünk támasza. Menedékváros Polgárai hozzá fordulnak, ha segítségre van szükségük, de a  Tanácson keresztül a döntésekbe is  beleszólhatnak.}
{186}{}{"Nehéz id?kben?" Mit ért ez alatt?}
{187}{}{És ön mivel foglalkozik?}
{188}{}{Feltehetnék egy másik kérdést?}
{189}{}{Köszönöm a segítséget. Viszlát!}
{190}{}{Gekkóról? Mit szeretne tudni?}
{191}{}{Merre találom Gekkót?}
{192}{}{Mi az a Gekkó?}
{193}{}{Feltehetnék egy másik kérdést?}
{194}{}{Köszönöm a segítséget. Viszlát!}
{195}{}{Nem sok mindent tudok mondani, kivéve azt a tényt, hogy egyre kevesebb ércszállítmányt kapunk t?lük.}
{196}{}{Van valami ötlete, hogy miért?}
{197}{}{Merre van Redding?}
{198}{}{Feltehetnék egy másik kérdést?}
{199}{}{Köszönöm a segítséget. Viszlát!}
{200}{}{Én vagyok a F?tanácsos, a  Tanács üléseit vezetem.}
{201}{}{Akkor mit csinál az Els? Polgár?}
{202}{}{Feltehetnék egy másik kérdést?}
{203}{}{Thank you for your time. Goodbye.}
{204}{}{A polgárság nem való mindenkinek. Ön inkább kalandornak néz ki... így fogalmam sincs, miért lenne szüksége rá.}
{205}{}{Gyerünk... mondja csak el, mire van szükségem ahhoz, hogy polgár lehessek!}
{206}{}{Én mindenképpen Polgár szeretnék lenni.}
{207}{}{Feltehetnék egy másik kérdést?}
{208}{}{Csak egy futó ötlet volt...}
{209}{}{Ön Polgár szeretne lenni? Nos, mi ennek csak örülni tudunk. Mindössze annyit kell tennie, hogy beszél Gregory F?biztossal, aki  ad önnek egy polgársági  tesztlapot.}
{210}{}{Merre találom Gregory F?biztost?}
{211}{}{Feltehetnék egy másik kérdést?}
{212}{}{Köszönöm. Azonnal megkeresem. Viszlát!}
{213}{}{Rendben van. Csak beszélnie kell Gregory F?biztossal, aki  ad önnek egy polgársági tesztlapot.}
{214}{}{Merre találom Gregory F?biztost?}
{215}{}{Feltehetnék egy másik kérdést?}
{216}{}{Rendben van. Most azonnal felkeresem ?t.}
{217}{}{A keleti épületszárnyban van az irodája, az Els? Polgáréval szemben.}
{218}{}{Feltehetnék egy másik kérdést?}
{219}{}{Köszönöm a segítséget. Viszlát!}
{220}{}{Az utóbbi két évben eldurvult a helyzet. Az ÚKK egyre agresszívabban követeli, hogy Menedékváros csatlakozzon a Köztársasághoz.}
{221}{}{Azt ígérték, ha belépünk, megvédenek bennünket a várost zaklató banditáktól. Ezek a támadások egyre hevesebbek és sok gondot okoznak nekünk.}
{222}{}{Ráadásul a gekkói ghoul-ok is szennyezik a talajvizet.}
{223}{}{Merre találom Gekkót?}
{224}{}{Mi az a Gekkó?}
{225}{}{Nehéz id?k járnak, valóban. Feltehetek önnek egy újabb kérdést?}
{226}{}{Sajnálattal hallom. Köszönöm, hogy szakított rám id?t. Viszlát!}
{227}{}{It is just northeast of here, but if you are planning on going there, I would advise you to purchase some anti-radiation drugs. If they are contaminating our water, it is likely their town itself is irradiated.}
{228}{}{Mi az a Gekkó?}
{229}{}{Feltehetnék egy másik kérdést?}
{230}{}{Köszönöm a figyelmeztetést. Viszlát!}
{231}{}{Az egy elhagyatott hely, valóságos nyomornegyed, melyet egy régi atomer?m? maradványai köré építettek.}
{232}{}{Hol találom Gekkót?}
{233}{}{Feltehetnék egy másik kérdést?}
{234}{}{Köszönöm a segítséget. Viszlát!}
{235}{}{Nem értem az egészet. Hajlandóak lennénk a legmagasabb árat fizetni az ércükért, de ahányszor csak beszélni próbálunk velük, kitérnek el?lünk. Bárcsak tudnám, miért ...}
{236}{}{Utánanézhetek, ha gondolja.}
{237}{}{Merre van Redding?}
{238}{}{Köszönöm a segítséget. Viszlát!}
{239}{}{Megtenné? Nincs felhatalmazásom, hogy fizessek a szolgálataiért, de megtaláljuk kompenzáció módját.}
{240}{}{Merre van Redding?}
{241}{}{Nem probléma. Szétnézek ott egy kicsit és amint találok valami érdekeset, jelentkezem.}
{242}{}{Redding nyugatra van, kb.. egyheti gyaloglásra innen. Én még sosem jártam ott.  Ami azt illeti... Menedékváros falain túl se voltam soha. Egyébként úgy értesültem, Redding az egyik legkellemesebb település a pusztában.}
{243}{}{Van valami ötlete, hogy miért csökkent az ércszállítmány?}
{244}{}{Értem. Köszönöm az információt.}
{245}{}{És mi az? Bármit is mond, nagy segítség lehet.}
{246}{}{Mit tudsz mondani Reddingr?l?}
{247}{}{I found that a large part of Redding is addicted to a drug called Jet. The miners are trading most of their ore to New Reno just to keep supplied.}
{248}{}{Dr. Troy el?állította a Jet ellenszerét.}
{249}{}{Eljuttattam az ellenszert Reddingbe.}
{250}{}{What is this "Jet" that they are all addicted to?}
{251}{}{Amint újabb részleteket is megtudok, ismertetni fogom magával.}
{252}{}{It's a drug with a 100% addiction rate, and severe withdrawals.}
{253}{}{Kérem, tegyen meg mindent!}
{254}{}{Kérdezhetek valami mást?}
{255}{}{Hogyne.}
{256}{}{Ez borzalmas. Tennünk kell valamit! Ha ez így megy tovább, az érckészleteink kiapadnak. Kérem, segítsen!}
{257}{}{Megnézem, mit tehetek.}
{258}{}{El?állította?! Akkor meg mit ácsorog még mindig itt? Azonnal juttassa el a szert Dr. Johnson-hoz! ? tudni fogja, mit kezdjen vele.}
{259}{}{Tudom, már említette. Kérem vigye Reddingbe, hátha segít rajtuk!}
{260}{}{Miel?tt indulnék, feltehetek önnek egy kérdést?}
{261}{}{Rendben, viszlátásra.}
{262}{}{Köszönöm! Most már csak reménykedhetünk, hogy id?ben érkezett a segítség.}
{263}{}{Szívesen! Örülök, hogy segíthettem.}
{264}{}{Nem probléma. Feltehetek önnek egy újabb kérdést?}
{265}{}{Héééé... hát nem kapok semmit a fáradozásaimért?}
{266}{}{Ha pénz a szíve vágya, akkor... tessék, 500 dollár. Most, ha megbocsát, dolgom van. Viszlát!}
{267}{}{KÖSZÖNÖM szépen.}
{268}{}{Öt kiló??!!!! Jobban teszi, ha felköhög még egy keveset, különben egy fabatkát sem fog érni az élete!}
{269}{}{Ezt most hogy kell értenem?}
{270}{}{Ha lenne egy hidroelektromos magnetoszféra szabályzóm, kicserélném a hibás alkatrészt és az er?m? szivárgásmentesen m?ködne tovább.}
{271}{}{Óh, semmiség. Sajnálom, hogy zavartam.}
{272}{}{Ez  jó megoldásnak t?nik. Nem akarok mást, mint megállítani a radioaktív szennyezést.}
{273}{}{Attól tartok,  ha megjavítom az er?m?vet, Lynette megakadályozza a Polgárrá válásomat,}
{274}{}{Kiváló! Hol vehetem át az alkatrészt?}
{275}{}{Észben tartom.}
{276}{}{Ha megjavítja az er?m?vet, megadom önnek a Polgárságot és ebben senki nem akadályozhat meg.}
{277}{}{Nagyszer?! Hol vehetem át az alkatrészt?}
{278}{}{Menjen Randalhoz, a Komfort Hivatal vezet?jéhez! T?le megkapja.}
{279}{}{Köszönöm. Már indulok is.}
{280}{}{Még egy dolog. Lehet, hogy ezt az adatlemezt  érdekesnek fogja találni.}
{281}{}{Kiváló! Már kezdtem aggódni, hogy a fokozódó sugárzás miatt el kell költöznünk. Kiemelked? munkát végzett.}
{282}{}{Menedékváros mindenek felett, Polgártárs.}
{283}{}{Menedékváros mindenek felett, Kapitány!}
{284}{}{Tessék, itt vannak a Polgárságát bizonyító papírok. Ha bármikor segítségre van szüksége, forduljon csak hozzám!}
{285}{}{Menedékváros mindenek felett, F?tanácsos!}
{286}{}{Köszi.}
{287}{}{Igen, már említette.}
{288}{}{Bravó, Kapitány!}
{289}{}{Nagyszer?, Polgártárs!}
{290}{}{Remek!}
{291}{}{Lenne pár kérdésem.}
{292}{}{Köszi.}
{293}{}{Tessék? Egy adatlemez? Miféle adatlemez?}
{294}{}{Itt van, nézze meg!}
{295}{}{Ez egy gazdálkodási adatlemez, ami azt mutatja, mennyi energiát termelt a gekkói atomer?m? a háború el?tt. Lehet, hogy ennyit manapság is képes lenne el?állítani.}
{296}{}{Felejtsd el! Kérdeznék valami mást.}
{297}{}{Bocs, hogy zavartalak.}
{298}{}{Rendben. Adjon egy percet...}
{299}{}{Rendben.}
{300}{}{Hmmm. Hogy jutott hozzá a lemezhez?}
{301}{}{Hmm... találtam.}
{302}{}{Akkor találtam, amikor Menedékváros adattárában keresgéltem.}
{303}{}{Gekkóban kaptam valakit?l.}
{304}{}{Gekkóban kaptam egy ghoultól. Az illet?t Gekkó Gordonnak hívják és érdekelt az atomer?m? teljesítményének növelésében, valamint a Menedékvárossal kialakítandó energiamegosztásban... cserébe Menedékváros orvosi technológiájáért.}
{305}{}{Értem... tehát...}
{306}{}{Ahogyan én látom, Menedékváros generátora csak meghatározott számú embert képes ellátni. ?szintén szólva szerintem ez a szám már most sem növelhet?.}
{307}{}{Nem érdekel, honnan szerezte az információit, de ha mindez igaz, mit javasol, mit tegyek?}
{308}{}{Az adatok nyilvánvalóvá tették, hogy a gekkói er?m? képes annyi energiát termelni, hogy Menedékvárosnak is jusson bel?le. Ehhez csupán arra van szükség, hogy optimalizáljuk a m?ködését.}
{309}{}{A lemezen lév? adatok nyilvánvalóvá tették, hogy a gekkói er?m? - ha optimalizáljuk - nagyon sok energiát termelhet. Többet, mint amennyire Gekkónak szüksége van. Menedékváros felhasználhatná ezt a feles energiát.}
{310}{}{Azt javasolja tehát, hogy FOGLALJUK EL Gekkót és szerezzük meg az er?m?vüket ??!!! Hát ebbe én nem egyezem...}
{311}{}{...nem, nem... ha Gekkó megkapja a szükséges adatokat az optimális m?ködtetéshez, fogadok, hogy orvosi felszerelésre cserélik majd a felesleges energiát.}
{312}{}{Hmmm. Az egészségügyi támogatás megkezdéséig csak együttérzésemr?l biztosíthatom Gekkó lakosait. Biztos sokat szenvednek... Ellenben hogy tudnánk optimalizálni az er?m? m?ködését?}
{313}{}{Fogalmam sincs, de csak találok valakit, aki elmondja.}
{314}{}{Nem tudom. Remélem, az er?m? környékén akad majd valaki, akivel beszélni tudok ezügyben.}
{315}{}{Csak be kell lépnem Menedékváros számítógépébe. Azzal  optimalizálni tudnám az er?m? reaktor-lemezét és ez jelent?sen felfuttatná a teljesítményét.}
{316}{}{Rendben van. Ha történik valami ezügyben, kérem, értesítsen!}
{317}{}{Rendben van. El?ször is elmegyek Randalhoz az alkatrészért.}
{318}{}{Rendben, Kapitány.}
{319}{}{Rendben, Polgártárs.}
{320}{}{Rendben, megkapja az engedélyt. Használhatja a számítógépet a reaktor-lemez optimalizálásához. A Menedék harmadik szintjén találja, a M?veleti terem közelében.}
{321}{}{Nagyszer?. Köszönöm, F?tanácsos. Megyek is.}
{322}{}{Kész van. Tessék.}
{323}{}{Megtartom az  adatlemezt további tanulmányozás céljából. Remélem, meg tudom gy?zni a Tanácsot, hogy kezdjünk el tárgyalni Gekkóval a felesleges energiájuk megvételével kapcsolatosan. Az adatlemez meggy?z? érv lesz.}
{324}{}{Rendben. Köszönöm.}
{325}{}{Hmmm... nos, nem engedélyezhetem önnek a belépést a Menedékbe, de lehet, hogy én magam optimalizálni tudom a reaktor-lemezt.}
{326}{}{Rendben, de nincs nálam a kérdéses lemez. Hamarosan jelentkezem.}
{327}{}{Az nagyszer? lenne.}
{328}{}{Kit?n?!}
{329}{}{Rendben.}
{330}{}{Adja ide a reaktor-lemezt és én majd személyesen optimalizálom a számítógéppel.}
{331}{}{Nagyszer?! Köszönöm.}
{332}{}{Mi a fene ez?}
{333}{}{Van itt egy reaktor-lemez. Egy gekkói ... hmmm ... technikus szerint Menedékváros számítógépe optimalizálni tudná a m?ködését, tovább növelve a teljesítményét és stabilitását.}
{334}{}{?rség! ?rség !!!}
{335}{}{}
{336}{}{You told McClure about the Redding Jet addiction problem.}
{337}{}{Átadtad a gazdálkodási adatlemezt McClure számára.}
{338}{}{Még mindig keresem a módját, hogy lehetne optimalizálni az er?m? m?ködését.}
{339}{}{Még mindig keresem a módját, hogy lehetne optimalizálni az er?m? m?ködését.}
{340}{}{Azt kívánom, bárcsak segíteni tudnék, de félek, hogy a  reaktorokat érint? tudásom ... hmmm ... igencsak felszínes. Talán egy technikust kellene megkérdezni a gekkói er?m?nél.}
{341}{}{Lehet. Volna még pár kérdésem...}
{342}{}{Lehetséges. Majd meglátom.}
{343}{}{Tudattad McClure-ral, hogy kézbesítetted a Jet-ellenszert.}
{344}{}{The disk shows that since the plant is now fully functional and optimized, it can now produce a great deal of energy. Far more than Gecko needs. Vault City could use that energy. I feel that the council should consider what this disk has to offer.}
{345}{}{Do you know anything about the nearby village that's swarming with mole rats?}
{346}{}{Actually, yes. Sergeant Stark reported something on this to me recently. What interest do you have in this matter?}
{347}{}{Is it true that you intend to make servants of those people?}
{348}{}{Nothing really. May I ask you about something else?}
{349}{}{Doesn't matter. Bye.}
{350}{}{Recruiting servants is not the issue here. The issue is the threat that these monsters pose to Vault City. According to Sergeant Stark's report, the people of that village seem to coexist with those huge rat creatures. If that's true, they may have found a way to control them, and perhaps that's why these creatures have begun to attack our patrols. Sergeant Stark plans to eliminate these pests, and he has my full support.}
{351}{}{I assure you the people of that village aren't controlling the mole rats. In fact, I've got a proposition for you: I'll take care of this mole rat problem, and in return, I want your assurance that Vault City will leave the people of that village alone.}
{352}{}{An interesting proposition, but how exactly do you plan to deal with all those rat creatures?}
{353}{}{I think I might know who *is* controlling them.}
{354}{}{Don't really know, but I'll think of something. I always do.}
{355}{}{Really? Very well then, I'll take your word for it. The raid will be postponed for a month.}
{356}{}{You're a good man, McClure, and you won't regret this. I'll be back once the problem's taken care of.}
{357}{}{It's amazing, the mole rat attacks on our patrols suddenly stopped without warning. I don't know how you did it, but I thank you. Also, I shall uphold my end of the bargain -- I'll order Stark to cancel the raid at once. As long as the people of that village pose no threat to Vault City, they'll have nothing to fear from us -- I'll see to that.}
{358}{}{Thank you!}
{359}{}{You solved the village problem.}
{360}{}{This is quite interesting.}
{370}{}{Alright. Well, I won't get in your way then.}
