{100}{}{Egy fáradt tekintetű nőt látsz. Úgy tűnik, már napok óta nem aludt.}
{101}{}{Melindát, az Üdvözlő Hivatal vezetőjét látod.}
{102}{}{Nem emlékszem, hogy láttalak már itt korábban, utazó. Üdvözöllek Menedékvárosban. Miben segíthetek?}
{103}{}{Miben segíthetek?}
{104}{}{Ez a bekerített rész a város?}
{105}{}{Menedéket keresem.}
{106}{}{Ki vagy?}
{107}{}{Ezt inkább kihagynám. Viszlát!}
{108}{}{Ezit Menedíkváááros?}
{109}{}{Nem. Ne tévesszen meg a látvány, ez a hely még csak az Előváros. Az igazi ettől északra található.}
{110}{}{Mi a különbség a két terület között?}
{111}{}{Kérdezhetek még valamit?}
{112}{}{Kösz a segítséget. Viszlát!}
{113}{}{Köfii}
{114}{}{A mi Menedékünket? Az a belvárosban van. Tudnod kell azonban, hogy oda csak Polgárok tehetik be a lábukat.}
{115}{}{Mindenképpen be kell jutnom. Segítenél?}
{116}{}{Kérdezhetek még valamit?}
{117}{}{Kösz a segítséget. Viszlát!}
{118}{}{Melindának hívnak, én vezetem Menedékváros Üdvözlő Hivatalát.}
{119}{}{Hmm ... kemény munka lehet.}
{120}{}{Kérdezhetek még valamit?}
{121}{}{Köszönöm a segítséget.}
{122}{}{Előváros az, ahol a kevésbé szerencsések élnek. Bár ők is élvezik Menedékvéros védelmét, a belváros ettől északra található. Az a terület kizárólag a Polgárok számára van fenntartva.}
{123}{}{Miért csak Polgárok élhetnek a belvárosban?}
{124}{}{Kérdezhetek még valamit?}
{125}{}{Köszönöm a segítséget.}
{126}{}{Sajnálom, nem tudok, az tiltott terület a Kívülállók számára. De... talán beszélj Wallace-szal, a vámhivatalnokkal! Az irodáját Előváros északi végében találod.}
{127}{}{Kérdezhetek még valamit?}
{128}{}{Kösz a segítséget. Viszlát!}
{129}{}{My work benefits Vault City, and I have the privilege of being able to talk
 to travelers about the grandeur of the city.}
{130}{}{Azért néha baromira unod, igaz? Valld csak be!}
{131}{}{Kérdezhetek még valamit?}
{132}{}{Köszönöm a segítséget.}
{133}{}{Hogy mindenkinek jobb életet biztosíthassunk, védenünk kell magunkat a külső hatásoktól.}
{134}{}{Ez azt jelenti, hogy elkülönítitek magatokat?}
{135}{}{Gúnyolódj csak, akkor is büszke vagyok arra, amit Menedékvárosért teszek. Most dolgom van. Fontosabb, mint a pimasz megjegyzéseidet hallgatni.}
{136}{}{Nem önös érdekből tesszük. A közösségért.}
{137}{}{Na, persze. Mindjárt gondoltam.}
{138}{}{Kérdezhetek még valamit?}
{139}{}{Köszönöm a segítséget.}
{140}{}{Felesleges gúnyolódnod. Kétlem, hogy képes vagy megérteni, mit-miért teszünk.}
{141}{}{Igazán? Ilyen nehéz felfogásúnak látszom? Kitöltünk egy IQ tesztet és összehasonlítjuk az eredményt, asszony?}
{142}{}{Elnézést, nem akartalak megbántani. Köszönöm a segítséget.}
{143}{}{Most sok a dolgom. Ha kérdésed van, tedd fel Steve-nek, az Üdvözlő Hivatal Segéd Üdvözlőjének!}
