{100}{}{A terminál véletlenszer?en fel-le mozgó, világító, zöld oszlopokat mutat.}
{101}{}{Ez Menedékváros orvosi terminálja.}
{102}{}{A terminál véletlenszer?en fel-le mozgó, világító, zöld oszlopokat mutat.}
{103}{}{Kicsit tudományosabb megközelítéssel sokkal több információhoz juthatnál.}
{104}{}{Nem jöttél rá, hogy m?ködik a terminál.}
{105}{}{Rohadt számítógépek!!!}
{106}{}{Nem jöttél rá, hogy m?ködik a terminál.}
{107}{}{Rohad' számtó... ghépk}
{108}{}{Bejelentkeztél Menedékváros Orvosi Adatbázisába. Bár a kezel?felületet nem teljesen érted, látod, hogy maga az adatbázis több adattárra van bontva.}
{109}{}{Megkeresed a 13-as Menedék koordinátáit.}
{110}{}{Adatok keresése: Édenkert Létrehozást El?segít? Táska.}
{111}{}{Átkutatod az orvosi adatbázist bármi érdekes után.}
{112}{}{Kilépés.}
{113}{}{You don't find any mention of Vaults in the database. It's mostly medical information relating
 to anatomy, known diseases, treatments, drugs, and implants.}
{114}{}{Átkutatod az adattárat, hátha megemlíti az Édenkert Létrehozást El?segít? Táskát.}
{115}{}{Átkutatod az orvosi adatbázist bármi érdekes után.}
{116}{}{Kilépés.}
{117}{}{You don't find any mention of the GECK in the database. It's mostly medical archives relating to
 anatomy, known diseases, treatments, drugs, and implants.}
{118}{}{Megkeresed a 13-as Menedék koordinátáit.}
{119}{}{Átkutatod az orvosi adatbázist bármi érdekes után.}
{120}{}{Kilépés.}
{121}{}{Átkutattad az adatbázist, de az orvosi terminológiát nem igazán érted. Ha többet tudnál a szakmáról, nem jelentene problémát.}
{122}{}{Keresés folytatása.}
{123}{}{Kilépés.}
{124}{}{Átkutattad az adatbázist és elképedsz az adattár információb?ségén. Menedékváros aktuális kutatási programjainak színvonala, az orvosi technológiájuk messze túlmutat mindenen, amit valaha is láttál.}
{125}{}{Ismét átnézed az adatbázist, de semmi újat nem találtál. Az implantátumok m?szaki rajza a leghasznosabb információ az adattárban. Talán kihagytál valamit, de úgy gondolod, ez nem valószín?.}
{126}{}{Ismét átnézted az adatbázist, de semmi újat nem találtál. Ha még vagy hússzor megismétled, talán rábukkannál valami érdekesre.}
{127}{}{Csak vicceltünk! Tényleg nincs itt semmi. Persze ha alaposan átnézed az adattárat még vagy harmincszor, esetleg találsz valamit... hehe :)}
{128}{}{Hát nem vagy semmi, apafej! Figyu! Menj és folytasd a játékot, oké? Nem üldögélhetsz itt örökké.}
{129}{}{Hát jó! Keress csak tovább!}
{130}{}{Csak az id?det vesztegeted.}
{131}{}{Négyes az Intelligenciád, igaz?}
{132}{}{Húzz el, öcsi!}
{133}{}{Miért nem mész inkább a n?vérkével papás-mamást játszani?}
{134}{}{Nincs itt semmi!}
{135}{}{Átkutattad az adattárat, de nem találtál semmit.}
{136}{}{Ötvenharmadszor is átnézted az adatbázist. Még most sem találtál újat.}
{137}{}{Csak megcsináltad még egyszer, igaz? Makkonya! :)}
{138}{}{Oké, figyelj! Elárulok egy nagy titkot. Miután meguntad a kutakodást, mindenképpen nézd meg a Központi Számítógépet a harmadik szinten! Most pedig lépj ki, és folytasd a játékot!}
{139}{}{Átkutattad az adattárat, de nem találtál semmit.}
{140}{}{További keresés az adattárban.}
{141}{}{Keresés folytatása, csak hogy biztos legyél benne, nem hagytál ki semmit.}
{142}{}{További keresés az adattárban.}
{143}{}{Kilépés.}
{144}{}{Majdnem egy órát töltöttél az adatbázis tanulmányozásával. Ahogy egyre mélyebbre ásol, rábukkansz valami régi adatra, amely valamiféle "harci implantátum" m?szaki leírását tartalmazza.}
{145}{}{Az implantátumokról szóló információk tanulmányozása.}
{146}{}{A m?szaki leírások részletesen bemutatják a lövedékálló lemezek és h?elosztó membránok emberi testbe való beültetését. Így növelhet? a fizikai és h?ellenálló képesség. Nagyon bonyolult m?veletnek t?nik.}
{147}{}{Feljegyzést készíteni, majd tovább kutatni.}
{148}{}{Feljegyzést készíteni, majd kilépni.}
{149}{}{Visszatértél a f?menübe. A képerny?n néhány adattár és keres?program látható.}
{150}{}{Keresés: 13-as Menedék.}
{151}{}{Keresés: Édenkert Létrehozást El?segít? Táska.}
{152}{}{Átkutatod az orvosi adatbázist bármi érdekes után.}
{153}{}{Kilépés.}
{200}{}{Befejezted Menedékváros Orvosi Adatbázisának tanulmányozását.}
{201}{}{A barátod megpróbálja felhívni a figyelmedet a színes képerny?s dobozra, ami azt mondja, hogy  BIPP-BIPP, de nem tudsz rájönni a nyitjára. Végül megunod és otthagyod.}
{202}{}{Otthagyod.}
{203}{}{*Bíííp*}
{204}{}{*Bipp... Bipp*}
{205}{}{*Zzzzz... klity... klaty... bipp*}
{206}{}{*Bííí-úúúp*}
{207}{}{*Bíííp*}
{208}{}{PING!}
{209}{}{Sajnálom, Dave. Nem tehetem.}
{210}{}{Veszély! Will Robinson!}
{211}{}{Harminc másodperce van, hogy elérje a minimális biztonsági távolságot.}
{212}{}{PING! Én mondtam!}
{213}{}{Kérem, vegye el a kártyáját, csak ezután kapja meg a pénzét és a bizonylatot.}
{214}{}{Érdekes játék. Az egyetlen nyer? lépés az, ha nem játszol.}
