{100}{}{Ez itt nem más, mint egy aktív számítógép-terminál.}
{101}{}{Közelebbr?l megvizsgálva egy fényl? feliratra leszel figyelmes: "I*tel Inside".}
{102}{}{Képtelen vagy elolvasni, mi van a képerny?n.}
{103}{}{F? Energia - Kikapcsolva                      
                        Tartalék Energia - Bekapcsolva
                                    Biztonsági Rendszer Újraindítása    
                             Figyelem! Alacsony energiaszint - Az Er?terek  50%-osan m?ködnek
                                                          Betöltés Befejezve...
                                                Skynet Biztonsági Ellen?rzés 1
                                   Kérem, adja meg a jelszót:}
{104}{}{1-es Skynet Biztonsági Ellen?rz? Pont
                                       Kérem, adja meg a jelszót:}
{105}{}{Csajkovszkij}
{106}{}{Szezám tárulj!}
{107}{}{Sierra}
{108}{}{Armageddon}
{109}{}{Feltöröd a védelmi rendszert}
{110}{}{G?zöd nincs. Kilépés.}
{113}{}{Er?terek az 1. Szinten: Kikapcsolva}
{115}{}{Kilépés}
{117}{}{Ehhez a terminálhoz le van tiltva a hozzáférés.}
{119}{}{Kilépés}
{121}{}{29-es Hibakód
                                                            Nem sikerült csatlakozni a szerverhez
                                     Kérem, indítsa újra a gépet!}
{123}{}{Kilépés}
{124}{}{Belépés: Engedélyezve
                                                 Er?terek az 1. szinten: Kikapcsolva}
{125}{}{Kilépés}
{126}{}{Érvénytelen Jelszó
                                                     Belepés: Elutasítva
                                                   Kérem, adja meg a jelszót:}
{127}{}{Csajkovszkij}
{128}{}{Szezám tárulj!}
{129}{}{Sierra}
{130}{}{Armageddon}
{131}{}{Feltöröd a Biztonsági Rendszert}
{132}{}{G?zöd nincs. Kilépés.}
{133}{}{[A <Ctrl><Alt><C> összeomlást okozott a programnak. Abban reménykedsz, hogy a maradék biztonsági berendezéseken is hasonlóan egyszer? lesz átrágnod magad.]}
{134}{}{Kilépés.}
{135}{}{Biztonsági Rés az 1. Szinten
                                          Biztonsági Protokoll Aktiválása
                                    A Felhasználók terminál-hozzáférése visszavonva  
     Átvitel Vége}
{136}{}{Kilépés}
{137}{}{It's no use. The program is just too complicated for you to understand.}
{138}{}{A hozzá-nemértésed bekapcsolta a riasztó rendszert.}
{139}{}{Kilépés}
{200}{}{ képtelen elolvasni, mi van a képerny?n.}
{300}{}{Úgy látszik, a számítógép védelmi berendezéssel van ellátva.}
{301}{}{Áramütés ért, ezért -}
{302}{}{, a társad, áramütést szenvedett, ezért -}
{303}{}{ ÉP a büntetés!}
