{100}{}{Egy éles szem? ember, akir?l lerí az üzleti szemlélet.}
{101}{}{Kockavet? krupié. A játék neve CRAPS.}
{102}{}{Egy halom zseton és pénz van nála. Kipróbálhatod nála a szerencsédet.}
{103}{}{Tegyék meg a tétjeiket! Új dobás következik.}
{104}{}{Mennyit tesz az FELTÉTEL NÉLKÜL NYER? SÁVRA?}
{105}{}{Mennyit tesz a NEM FELTÉTEL NÉLKÜL NYER? SÁVRA?}
{106}{}{Mennyit tesz a NYÍLT SÁVRA?}
{107}{}{Mennyit tesz a NEM NYÍLT SÁVRA?}
{108}{}{Mennyit tesz a MEZ?RE?}
{109}{}{Célszám:}
{110}{}{Feltétel nélkül nyer? sáv.}
{111}{}{Nem feltétel nélkül nyer? sáv.}
{112}{}{Nyílt sáv.}
{113}{}{Nem nyílt sáv.}
{114}{}{Egydobásos tétek...}
{115}{}{Szám tétek...}
{116}{}{Mez?-tét.}
{118}{}{Jöhet a dobás...}
{119}{}{A FELTÉTEL NÉLKÜL NYER? SÁVRA ÖN AZ ALÁBBI TÉTET TETTE: }
{120}{}{A NEM FELTÉTEL NÉLKÜL NYER? SÁVRA ÖN AZ ALÁBBI TÉTET TETTE: }
{121}{}{A NYÍLT SÁVRA ÖN AZ ALÁBBI TÉTET TETTE: }
{122}{}{A NEM NYÍLT SÁVRA ÖN AZ ALÁBBI TÉTET TETTE: }
{123}{}{7-es:}
{124}{}{dupla 3-as:}
{125}{}{dupla 4-es:}
{126}{}{dupla 5-ös:}
{127}{}{dupla 2-es:}
{128}{}{1-es és 2-es:}
{129}{}{5-ös és 6-os:}
{130}{}{1-es és 1-es:}
{131}{}{6-os és 6-os:}
{132}{}{CRAPS:}
{133}{}{4-es szám:}
{134}{}{5-ös szám:}
{135}{}{6-os szám:}
{136}{}{8-as szám:}
{137}{}{9-es szám:}
{138}{}{10-es szám:}
{139}{}{- a 4:}
{140}{}{- az 5:}
{141}{}{- a 6:}
{142}{}{- a 8:}
{143}{}{- a 9:}
{144}{}{- a 10:}
{145}{}{nyereményaránya: 4:}
{146}{}{nyereményaránya: 5:}
{147}{}{nyereményaránya: 6:}
{148}{}{nyereményaránya: 8:}
{149}{}{nyereményaránya: 9:}
{150}{}{nyereményaránya: 10:}
{151}{}{A MEZ?-TÉT ÉRTÉKE: }
{152}{}{Melyik EGYDOBÁSOS TÉT legyen?}
{153}{}{Mennyi?}
{154}{}{Egyszer? tétek...}
{155}{}{Nehezített tétek...}
{156}{}{Melyik fajta tét legyen?}
{157}{}{Mennyit tesz SZÁMRA?}
{200}{}{7-es (Nyereményarány: 5:1)}
{201}{}{dupla 3-as (Nyereményarány: 10:1)}
{202}{}{dupla 4-es (Nyereményarány: 10:1)}
{203}{}{dupla 5-ös (Nyereményarány: 8:1)}
{204}{}{dupla 2-es (Nyereményarány: 8:1)}
{205}{}{"1 és 2" (Nyereményarány: 15:1)}
{206}{}{"5 és 6" (Nyereményarány: 15:1)}
{207}{}{"1 és 1" (Nyereményarány: 30:1)}
{208}{}{"6 és 6" (Nyereményarány: 30:1)}
{209}{}{Bármilyen "craps" érték? dobás (Nyereményarány: 8:1)}
{299}{}{Melyik SZÁM TÉTET szeretné megtenni?}
{300}{}{Legyen a 4-es (1.8-szoros nyeremény)}
{301}{}{Legyen az 5-ös (1.4-szeres nyeremény)}
{302}{}{Legyen a 6-os (1.16-szoros nyeremény)}
{303}{}{Legyen a 8-as (1.16-szoros nyeremény)}
{304}{}{Legyen a 9-es (1.4-szeres nyeremény)}
{305}{}{Legyen a 10-es (1.8-szoros nyeremény)}
{400}{}{Vissza...}
{500}{}{$}
{501}{}{ vagyok.}
{600}{}{Hetes fizet az automatikusan nyer? sávon, célszám törl?dik.}
{601}{}{Tizenegyes fizet az automatikusan nyer? sávon.}
{602}{}{Kettes, nincs nyeremény.}
{603}{}{Hármas, nincs nyeremény.}
{604}{}{Tizenkettes, nincs nyeremény.}
{610}{}{Hetes, nincs nyeremény, célszám törl?dik.}
{611}{}{Tizenegyes, nincs nyeremény.}
{612}{}{Kettes fizet a nem automatikusan nyer? sávon.}
{613}{}{Hármas fizet a nem automatikusan nyer? sávon}
{614}{}{Tizenkettes, fizet a nem automatikusan nyer? sávon}
{620}{}{Az egydobásos 7-es}
{621}{}{Prop bet double 3s}
{622}{}{Az egydobásos dupla 4-es}
{623}{}{Az egydobásos dupla 5-ös}
{624}{}{Az egydobásos dupla 2-es}
{625}{}{Az egydobásos "1 és 2"}
{626}{}{Az egydobásos "5 és 6"}
{627}{}{Az egydobásos "1 és 1"}
{628}{}{Az egydobásos "6 és 6"}
{629}{}{Az egydobásos "CRAPS" 2,3,12}
{630}{}{veszített!}
{631}{}{nyert!}
{650}{}{4-es szám-tét}
{651}{}{5-ös szám-tét}
{652}{}{6-os szám-tét}
{653}{}{8-as szám-tét}
{654}{}{9-es szám-tét}
{655}{}{10-es szám-tét}
{660}{}{2-es mez?-tét duplán nyert.}
{661}{}{3-as mez?-tét nyert.}
{662}{}{4-es mez?-tét nyert.}
{663}{}{9-es mez?-tét nyert.}
{664}{}{10-es mez?-tét nyert.}
{665}{}{11-es mez?-tét nyert.}
{666}{}{12-es mez?-tét triplán nyert.}
{667}{}{A lehelyezett mez?-tét veszített. }
{670}{}{4-es sima tét}
{671}{}{5-ös sima tét}
{672}{}{6-os sima tét}
{673}{}{8-as sima tét}
{674}{}{9-es sima tét}
{675}{}{10-es sima tét}
{680}{}{4-es nyeremény-tét}
{681}{}{5-ös nyeremény-tét}
{682}{}{6-os nyeremény-tét}
{683}{}{8-as nyeremény-tét}
{684}{}{9-es nyeremény-tét}
{685}{}{10-es nyeremény-tét}
{700}{}{Nincs érvényes célszámmal rendelkez? nyeremény.}
{701}{}{Eredmény}
{702}{}{Nem}
{710}{}{Az egyik kockán:}
{711}{}{A másik kockán:}
{712}{}{Bocs, mennem kell.}
{713}{}{Elnézést, de ezt a tétet nem óhajtom megtenni.}
{714}{}{Célszámok törl?dnek.}
{800}{}{Kockáztathat a számokkal!}
{801}{}{Válasszon nyeremény-szorzót! A lehetséges nyeremény:}
{802}{}{*x nyeremény.}
{803}{}{- A jelenlegi beállítás:}
{804}{}{Nyeremény-tét a 4-esre.}
{805}{}{Nyeremény-tét az 5-ösre.}
{806}{}{Nyeremény-tét a 6-osra.}
{807}{}{Nyeremény-tét a 8-asra.}
{808}{}{Nyeremény-tét a 9-esre.}
{809}{}{Nyeremény-tét a 10-esre.}
{810}{}{Melyik számra tesz?}
{1100}{}{Egy éles szem? n?, akir?l lerí az üzleti szemlélet.}
{1102}{}{Egy halom zseton és pénz van nála. Kipróbálhatod nála a szerencsédet.}
