{100}{}{Przed tobą stoi Hakunin, wioskowy szaman. Spogląda na ciebie szaleńczym wzrokiem ze świata, który zamieszkuje tylko on...}
{101}{}{Widzisz Hakunina. Leży na ziemi. Jest ciężko ranny.}
{102}{}{Widzisz Hakunina. Jest bardzo bliski śmierci.}
{103}{}{Hakunin jest strasznie poparzony. Pachnie jak przypieczony kurczak, wygląda jak spalony kotlet i nie masz pojęcia jak udało mu się przeżyć tak długo w tym stanie.}
{104}{hak001}{Witaj, Dziecko Przeznaczenia. Czemuż to ziemia przede mną ogrzewa się od twego dotyku?}
{105}{}{Hę? }
{106}{}{Przychodzę, żeby się pożegnać. Wyruszam ze świętą misją. }
{107}{}{Odchodzę stąd. Przyszło mi na myśl, że może chociaż ten jeden raz będziesz gadać jak człowiek. }
{108}{}{Za dużo grzebiesz się w prochach. Wynoszę się stąd. }
{109}{}{Zraniono mnie. Możesz mnie uzdrowić?}
{110}{}{W twoim ogrodzie wyrosło kilka wrednych roślin - trzeba było je wyplewić.}
{111}{hak001a}{Proszę, wyjaw zamglonym oczom cel swego przybycia.}
{112}{}{Hę? }
{113}{}{Przychodzę, żeby się pożegnać. Wyruszam ze świętą misją. }
{114}{}{Odchodzę stąd. Przyszło mi na myśl, że może chociaż ten jeden raz będziesz gadać jak człowiek. }
{115}{}{Za dużo grzebiesz się w prochach. Wynoszę się stąd. }
{116}{}{W twoim ogrodzie wyrosło kilka wrednych roślin - trzeba było je wyplewić.}
{117}{hak002}{Ziemia śpiewa o nadejściu nowej duszy bohatera... może przed odejściem wyświadczysz mi grzeczność?}
{118}{}{Jasne. Czego potrzebujesz?}
{119}{}{To zależy... co mi dasz?}
{120}{hak002a}{Na świat można patrzeć z wielu różnych stron - to lekcja, której już niedługo doświadczysz... może przed odejściem wyświadczysz mi grzeczność?}
{121}{}{Czy właśnie poprosiłeś mnie o przysługę? Jeśli tak, to czemu nie?}
{122}{}{Zrobię coś dla ciebie, ale ponieważ muszę się ciężko napracować, żeby cię w ogóle zrozumieć, to zlecenie będzie cię kosztować.}
{123}{hak003}{Cóż za błogosławieństwo, zaprawdę jesteś dzieckiem natury. Czy możesz użyć swoich niezwykłych talentów, by pozbyć się z mego ogrodu roślin o mrocznych duszach?}
{124}{}{Uch-huh. }
{125}{}{Neech-ech. Tyyyy. Daj. To boli.}
{126}{hak004}{Niech twa aura rozświetli me życie, gdy... och, stań u mych drzwi, gdy już skończysz, a dam ci coś dobrego.}
{127}{}{Argggg.}
{128}{hak005}{Rośliny o mrocznych duszach znów rozpleniły się w moim ogrodzie. Wiele wiosen dotykało mych kości i jestem zbyt kruchy, by stanąć do tej walki, która w naturze nigdy się nie kończy. Proszę cię o pomoc.}
{129}{}{Nie mogę. Muszę natychmiast rozpocząć swą misję.}
{130}{}{Wiem, że nie jesteś złym facetem, ale mnie i tak już boli głowa, więc chyba raczej dam sobie z tym spokój.}
{131}{}{Mowy nie ma. W przyszłości będę przewodzić tej wiosce. Opiekowanie się twoim ogródkiem jest niegodne mojej osoby.}
{132}{}{Byłoby to dla mnie zaszczytem, święty ojcze.}
{133}{}{Czy poprosiłeś mnie właśnie o wytępienie chwastów z twojego ogrodu? Jeśli tak, to nie ma sprawy.}
{134}{}{Za opłatą.}
{135}{hak006}{Żądać zapłaty za prezent przynosi mniej niż sam podarunek. Dam ci to i dodam nauczkę w postaci rozczarowania cię przy odbiorze przez twoją własną osobę.}
{136}{}{Może być. Gdzie jest ogród?}
{137}{}{Wiesz, miłym prezentem byłoby, gdybyś zaczął MÓWIĆ PO LUDZKU!}
{138}{}{A co jeśli dam ci nauczkę w postaci rozczarowania wychodząc stąd natychmiast? Żegnam.}
{139}{}{Skoro masz taki tupet, to mnie cała ta sprawa nie interesuje. Do widzenia.}
{140}{hak006a}{Czy mówiąc tymi samymi słowami mamy na myśli to samo? Czy słowa zawsze niosą ten sam powiew duszy?}
{141}{}{O tak. Dużo lepiej. A moja najnowsza lekcja brzmi: zamknij się i po prostu gadaj gdzie leży ogród.}
{142}{}{Wypróbujmy takie słowo, "do widzenia". Oznacza, że odchodzę. }
{143}{hak007}{Z pewnością pamiętasz, że leży na północnym wschodzie, Dziecko Głupoty.}
{144}{}{Dzięki za pomoc.}
{145}{}{Dzięki. Nawet to rozumiem.}
{146}{}{Wątpisz w moją inteligencję? W takim razie chyba już nie chcę ci pomagać. }
{147}{}{Wrócę niedługo po moją zapłatę.}
{148}{hak008}{Brzemię, które dźwigasz, będzie cię męczyło coraz bardziej.}
{149}{hak009}{Niech bogowie wspomogą twoje wysiłki, Dziecko Przeznaczenia. Niech twa aura rozświetli mój byt, gdy ziemia znów odetchnie pełną piersią.}
{150}{}{Rozumiem, że chcesz mnie znowu zobaczyć, gdy już skończę... wiesz, mogłeś to po prostu powiedzieć.}
{151}{}{Żegnaj.}
{152}{hak010}{Ha! Żyje w tobie duch Założyciela. Skup się na umacnianiu siebie, by rozszerzać wielkość i umożliwić jej dotknięcie świata. Oczywiście, nagroda będzie więcej niźli tylko duchowa. }
{153}{}{Brzmi interesująco. Wrócę, gdy skończę.}
{154}{}{A więc dostanę jakąś zapłatę. Może być. Na razie.}
{155}{}{Chyba stanowczo za dużo bawiłeś się z tymi roślinami. By uniknąć twego losu, będę się trzymać z dala od twojego ogrodu.}
{156}{hak011}{Czas nie może zostać stracony ani zaoszczędzony - zawsze musi liczyć się teraz. To czyny tworzą sploty twego życia.}
{157}{}{Eee, oczywiście. No więc, jak to już zostało powiedziane, muszę lecieć. Do widzenia. }
{158}{}{Wiesz, rozmawianie z tobą sprawia, że zaczynam się zastanawiać nad tym pomysłem, że czasu nie można tracić. Zmiatam stąd. }
{159}{}{Gdyby tylko dana mi była twoja mądrość, o światły ojcze. Wybacz mi - oczywiście zajmę się tym dla ciebie.}
{160}{hak012}{Choć przywdziewasz szaty Dziecka Przeznaczenia, mroczna dusza krzyczy z twego wnętrza.}
{161}{}{Błagam cię o przebaczenie, o święty ojcze. Jak mogę oczyścić swoją duszę? }
{162}{}{Dokładnie, Hakuninie. Byłoby naprawdę mądrze z twojej strony, gdybyś o tym nie zapominał.}
{163}{}{Ból rozdziera wnętrze mojej głowy, gdy cię słucham. Lepiej stąd pójdę.}
{164}{}{Buka!}
{165}{hak013}{Oczyść swą duszę tak, jak wypędza się demony z mego ogrodu.}
{166}{}{Tak zrobię, o światły ojcze. Przyjdę by prosić cię o przebaczenie, gdy już oczyszczę twój ogród.}
{167}{}{Chcesz przez to powiedzieć, że wyplewienie twojego ogrodu dobrze mi zrobi, czy tak? No dobrze, niech będzie.}
{168}{}{W sumie lubię swoją duszę taką, jaka jest. Żegnam.}
{169}{}{To byłby dla mnie zbyt wielki zaszczyt. Odejdę natychmiast.}
{170}{hak014}{Dziecko, oto znowu istota twego jestestwa jest całością, jak błogosławiona kraina.}
{171}{}{Dziękuję.}
{172}{}{Masz na myśli, że już mi lepiej, tak?}
{173}{hak015}{Czynienie czegoś całością daje poczucie spełnienia, którego zrozumienie da ci mądrość, moje dziecko.}
{174}{}{Czekaj, nie podpowiadaj. Czuję się lepiej i fakt, że mi pomogłeś, sprawia ci przyjemność, tak? Dzięki.}
{175}{}{Jesteś mądry i uczynny, święty ojcze.}
{176}{hak017}{W jaki sposób mogę dotknąć duszy przeznaczenia, potomku Przybysza?}
{177}{}{Uch, gdzie dokładnie jest twój ogród?}
{178}{}{Zraniono mnie. Możesz mnie uzdrowić?}
{179}{}{Och, to nic takiego. Do widzenia.}
{180}{hak018}{Ach. Przywracasz światu ducha Przybysza i przynosisz uśmiech duszy starego, przemijającego człowieka. W nagrodę dam ci lecznicze proszki. Pamiętaj, że one mącą umysł tak samo, jak oczyszczają ciało.}
{181}{}{Dziękuję.}
{182}{hak018a}{Ponadto zmieszam ze sobą kwiat Broca i korzeń xandrowy zawsze wtedy, gdy je do mnie przyniesiesz. Niech twoje ścieżki wiodą cię prosto, a twoje serce wiernie ci służy.}
{183}{}{Gdzie mogę znaleźć te rzeczy?}
{184}{}{Dziękuję.}
{185}{}{Prawie mi przykro, że muszę już iść. Już niemal potrafię cię zrozumieć. Do widzenia.}
{186}{hak019}{Ach, Dziecko, mój ogród ma się dobrze, a twój?}
{187}{}{Chyba tak.}
{188}{}{Potrzebuję uzdrowienia.}
{189}{}{Mówiłeś, że gdzie są te rośliny?}
{190}{}{Nie mam żadnego ogrodu - o czym u licha gadasz tym razem?}
{191}{}{Chciałbym, żebyś zrobił dla mnie trochę leczniczego proszku.}
{192}{}{Och, nieważne. Muszę już iść.}
{193}{}{Ouu?}
{194}{}{Uuug! Bak!}
{195}{hak020}{Wypełnia mnie radość z tych słów. Zaprawdę, bogowie szepczą do mnie. Do widzenia.}
{196}{}{Bywaj.}
{197}{}{Wciąż mieszasz jakieś dziwne zioła, co? Na razie.}
{198}{hak021}{Wszyscy mamy swoje ogrody. Niech twoje czyny służą doglądaniu twego. Nich ci się dobrze wiedzie. Tymczasem będę zabiegał o łaskę bogów.}
{199}{}{Cześć.}
{200}{}{Założę się, że ciągasz ze sobą to swoje towarzystwo, gdziekolwiek pójdziesz. Trzymaj się.}
{201}{hak022}{Spójrz na północ, Dziecko, a droga stanie otworem.}
{202}{}{Dobra, dzięki.}
{203}{hak023}{Czuję się zaszczycony, że mogę służyć Dziecku Przeznaczenia.}
{204}{hak024}{Takie jest życie. Dwoje tworzy trzecie. Do stworzenia leczniczego proszku będą ci potrzebne korzeń xandrowy i kwiat Broca.}
{205}{}{Och. Dzięki.}
{206}{}{Puu.}
{207}{hak025}{Oby nigdy nie zaszła potrzeba jego użycia.}
{208}{}{Dobra, dzięki.}
{209}{}{Uch!}
{210}{hak026}{Zdrowie do ciebie powróciło.}
{211}{}{Dziękuję.}
{212}{}{Żadnych lekcji? Żadnych niezrozumiałych przemówień? Na pewno wszystko z tobą w porządku?}
{213}{hak027}{Witaj, Dziecko. Pobłogosław nas nowiną, że GECK zostanie niedługo znaleziony. Nasza wioska cierpi, nasza potrzeba jest wielka, a nasz czas - krótki.}
{214}{}{Nuch.}
{215}{}{A twoja zdolność do mówienia po ludzku, nieistniejąca. Wciąż szukam.}
{216}{}{Pracuję nad tym. }
{217}{}{Odczep się ode mnie, staruchu. Robię co mogę.}
{218}{}{Wciąż szukam, o święty ojcze. Mam nadzieję, że znajdę GECK już wkrótce.}
{219}{hak028a}{Niech Ziemia łagodzi każdy twój krok.}
{220}{hak028b}{Niech Wody umilają twą podróż.}
{221}{hak028c}{Niech Wiatr prowadzi cię do twego celu.}
{222}{hak028d}{Niech Ogień smaży twoje siedzenie, aż ukończysz to zadanie.}
{223}{}{Dziękuję.}
{224}{}{Że co?!}
{225}{}{Uch.}
{226}{}{Huh?!}
{227}{hak029}{Witaj z powrotem, Dziecko. Z wyrazu twej twarzy czytam, że ocalenie przez GECK nie jest jeszcze naszym udziałem. Nie ustawaj w dążeniach jak pracowita mrówka, dopóki nasze rezerwy się nie wyczerpią. Jesteś naszą ostatnią nadzieją.}
{228}{}{Yhy.}
{229}{}{Staram się. Ciekawe, czy jest jakaś mrówka, która przeszła tyle mil co ja.}
{230}{}{Robię co mogę.}
{231}{}{Podwoję swoje wysiłki, święty ojcze. Nie zawiodę cię.}
{232}{}{Jasne, jasne. Już to mówiłeś.}
{233}{hak030}{Dziecko - wioska płacze z rozpaczy. Ludzie słabną z głodu. Proszę, nie wytrzymamy już zbyt długo.}
{234}{}{Yhy.}
{235}{}{Staram się. Staram się! Dajcie mi wszyscy spokój!}
{236}{}{Znajdę GECK, o święty. Masz moje słowo.}
{237}{}{Zrobię co tylko będę w stanie, by odnaleźć GECK.}
{238}{hak031}{Dziecko, zostało nam już tylko kilka ziaren z całego piasku czasu. Proszę, przynieś szybko GECK i spraw, by przyszłość naszej wioski przypominała plażę nad oceanem. Szybko, zanim ostatnie ziarno się przesypie.}
{239}{}{Yhy.}
{240}{}{W porządku. Wyruszam na poszukiwania.}
{241}{}{Życie jest plażą, co?}
{242}{}{Znajdę GECK, o święty. Nie zawiodę naszego ludu.}
{243}{hak032}{Dziecko, duchy naszych przodków prowadzą mnie przez świat snów, abym mógł dotknąć twych myśli. Bez świętego GECKa nasza wioska cierpi. Twoje dłonie trzymają pasma naszego życia tak, jak ojciec trzyma swoje dzieci.}
{244}{hak033}{Kolejny raz mój duch dotyka cię poprzez pustkę, Dziecko Przeznaczenia. Nasze uprawy usychają, a nasze zapasy są bardzo skromne. Wróć do nas z GECKiem. Twoja porażka zgasi ostatni promień nadziei.}
{245}{hak034}{Dziecko. Wioska słabnie. Dotykanie twych snów staje się coraz trudniejsze. Musisz się pośpieszyć, albo wszyscy...}
{246}{hak035}{Dziecko? Dziecko? Czy mnie słyszysz? Wioska umiera. Cała nasza przyszłość umiera razem z nią. Niewiele nam już zostało czasu i ducha... Pośpiesz się. Pośpiesz się...}
{247}{hak101}{Dziecko - cień mroku nadciągnął przed tobą.}
{248}{}{Auuuu!}
{249}{}{Co się stało?}
{250}{}{Wyglądasz fatalnie. Pozwól mi pomóc.}
{251}{hak102}{Dziecko Natury, jakże mogliśmy położyć takie brzemię na twych ramionach? (westchnienie) Twój lud został porwany.}
{252}{}{Uuch?}
{253}{hak103}{Tak. Porwany. Wiele mrocznych dusz ujeżdżających metalowe ptaki nadciągnęło tu jak rój głodnych karaluchów, kryjąc swe zło pod lśniącymi skórami. }
{254}{}{Ooo! Błyszczy udne!}
{255}{hak104}{Nie! Nie błyszczy ładnie! Porwali nasz lud i zabrali go na południowy zachód.}
{256}{}{Auu.}
{257}{hak105}{Tak. Wielki smutek i ból. Stoję między światami, by ci to powiedzieć, Dziecko Przeznaczenia. Uratuj swój lud.}
{258}{}{Hm?}
{259}{hak106}{Dziecko, pozwól moim słowom dotknąć twojej duszy. Idź na południowy zachód. Południe i zachód. Uratuj nasz lud. Uratuj nasz lud.}
{260}{}{Uch-huh..}
{261}{hak107}{Dziękujmy przodkom. Teraz moja dusza może dołączyć do wiecznej pieśni. Bezpiecznej podróży, Dziecko.}
{262}{}{Iść?}
{263}{hak108}{Idź!...}
{264}{}{PA PA.}
{265}{hak109}{Nadeszły mroczne dusze. Zabrali wszystkich.}
{266}{}{Mroczne dusze? Co masz na myśli?}
{267}{hak110}{Zerwał się nagły wiatr. Nadleciały wielkie ważki plujące ogniem. Źli ludzie wypełzli z brzuchów potworów i przynieśli śmierć naszym wojownikom.}
{268}{}{Nasi wojownicy nie umieli ich powstrzymać?}
{269}{hak112}{Duch nie zawiódł, lecz włócznie były zbyt słabe. Niegodziwcy spalili naszych wojowników piekielnymi światłami.}
{270}{}{Zabili wszystkich?}
{271}{hak113}{Wszyscy zostali zabici lub pojmani. Mój duch powrócił do ciała tylko po to, by przekazać prawdę Dziecku Przeznaczenia.}
{272}{}{Co się stało z tymi, których pojmano?}
{273}{hak114}{Bestie połknęły wszystkich i odeszły z wiatrami.}
{274}{}{Uch, w którą stronę wiały wiatry, za którymi podążały?}
{275}{hak115}{Czy nie pamiętasz, czego uczyłem cię o dorocznym tańcu duchów wiatru? Oczywiście na południe.}
{276}{}{Twoje opowieści były tak żywe i sugestywne, o wielki Hakuninie, że często w czasie twoich lekcji opuszczały mnie zmysły.}
{277}{}{Ach, TE wiatry. Oczywiście. }
{278}{hak116}{Tak, odeszli z wiatrem na południe. Podsłuchałem rozmowę dwóch mrocznych dusz. Zamierzali pozwolić swoim bestiom odpocząć w miejscu zwanym Navarro, a potem przekroczyć wielką misę łez naszej matki-Ziemi.}
{279}{}{Co mam zrobić?}
{280}{}{Misa łez?}
{281}{hak117}{Dla mnie - już nic. Dziecko, musisz odszukać zagrodę mrocznych i ocalić nasz lud.}
{282}{}{Spróbuję.}
{283}{hak118}{Jesteś Dzieckiem Przeznaczenia. Musisz spróbować.}
{284}{}{Hakuninie?}
{285}{}{Po raz pierwszy rozumiem, o co ci chodzi.}
{286}{hak120}{Ocean łez wypłakanych przez matkę za swoje dzieci.}
{287}{}{Och, ocean. Ale co mam zrobić?}
{288}{hak121}{Dziwna mgła ukradła ich myśli i wysłała ich do krainy Snu. Źli ludzie wędrowali między śniącymi, ale sami nie śnili.}
{289}{}{I co?}
{290}{hak122}{Zbyt wiele lat i zbyt wiele ran, Dziecko. Zamiast tego musisz posłuchać.}
{291}{}{Dobrze.}
{300}{}{Ci którzy kradną dźwigają ciężkie brzemię. Pamiętaj o tym, Dziecko Przeznaczenia.}
{301}{}{Teraz musisz zapłacić za swoje grzechy, Dziecko Przeznaczenia.}
