{100}{}{Necesitas %d puntos de acción.}
{101}{}{Sin munición.}
{102}{}{Objetivo fuera de alcance.}
{103}{}{El combate no puede terminar si hay criaturas hostiles cerca.}
{104}{}{Línea de fuego bloqueada.}
{105}{}{No puedes usar armas con los dos brazos rotos.}
{106}{}{No puedes usar armas de dos manos con un brazo roto.}
{107}{}{No tienes suficiente fuerza para manejar ese arma.}
{108}{}{ y }
{200}{}{queda fuera de combate}
{201}{}{derribada}
{202}{}{te deja lisiada la pierna izquierda}
{203}{}{te deja lisiada la pierna derecha}
{204}{}{te deja lisiado el brazo izquierdo}
{205}{}{te deja lisiado el brazo derecho}
{206}{}{cegada}
{207}{}{te mueres}
{208}{}{es herida}
{209}{}{críticamente}
{210}{}{ardiendo}
{211}{}{traspasa tu armadura}
{212}{}{tu arma explota}
{213}{}{destruye tu arma}
{214}{}{tu arma se cae}
{215}{}{pierdes el siguiente turno}
{216}{}{te hieres a ti misma}
{217}{}{pierdes el resto de tu munición}
{218}{}{dispara un proyectil defectuoso}
{219}{}{hiriéndote}
{220}{}{es golpeado al azar}
{221}{}{se rompe un miembro al azar}
{222}{}{le alcanzan los fragmentos}
{250}{}{queda fuera de combate}
{251}{}{derribada}
{252}{}{te deja lisiada la pierna izquierda}
{253}{}{te deja lisiada la pierna derecha}
{254}{}{te deja lisiado el brazo izquierdo}
{255}{}{te deja lisiado el brazo derecho}
{256}{}{cegada}
{257}{}{te mueres}
{258}{}{es herida}
{259}{}{críticamente}
{260}{}{ardiendo}
{261}{}{traspasa tu armadura}
{262}{}{tu arma explota}
{263}{}{destruye tu arma}
{264}{}{tu arma se cae}
{265}{}{pierdes el siguiente turno}
{266}{}{te hieres a ti misma}
{267}{}{pierdes el resto de tu munición}
{268}{}{dispara un proyectil defectuoso}
{269}{}{hiriéndote}
{270}{}{es golpeado al azar}
{271}{}{se rompe un miembro al azar}
{272}{}{le alcanzan los fragmentos}
{300}{}{queda fuera de combate}
{301}{}{derribada}
{302}{}{rompe su pierna izquierda}
{303}{}{rompe su pierna derecha}
{304}{}{rompe su brazo izquierda}
{305}{}{rompe su brazo derecho}
{306}{}{cegada}
{307}{}{muere}
{308}{}{es herida}
{309}{}{críticamente}
{310}{}{ardiendo}
{311}{}{traspasando su armadura}
{312}{}{su arma estalla}
{313}{}{su arma se destruye}
{314}{}{su arma se cae}
{315}{}{pierde su siguiente turno}
{316}{}{se hiere a sí mismo}
{317}{}{pierde el resto de su munición}
{318}{}{dispara un proyectil defectuoso}
{319}{}{hiriéndose}
{320}{}{es golpeado al azar}
{321}{}{se rompe un miembro al azar}
{322}{}{le alcanzan los fragmentos}
{400}{}{queda fuera de combate}
{401}{}{derribada}
{402}{}{rompe su pierna izquierda}
{403}{}{rompe su pierna derecha}
{404}{}{rompe su brazo izquierda}
{405}{}{rompe su brazo derecho}
{406}{}{cegada}
{407}{}{muere}
{408}{}{es herida}
{409}{}{críticamente}
{410}{}{ardiendo}
{411}{}{traspasa su armadura}
{412}{}{su arma estalla}
{413}{}{su arma se destruye}
{414}{}{su arma se cae}
{415}{}{pierde el siguiente turno}
{416}{}{se hiere a si misma}
{417}{}{pierde el resto de su munición}
{418}{}{dispara un proyectil defectuoso}
{419}{}{hiriéndose}
{420}{}{es golpeado al azar}
{421}{}{se rompe un miembro al azar}
{422}{}{le alcanzan los fragmentos}
{506}{}{Tú}
{509}{}{%s eres herida en vez de %s!}
{511}{}{%s eres herida críticamente en %s, pierdes %d puntos de salud}
{512}{}{%s eres herida en %s perdiendo %d puntos de salud}
{513}{}{%s eres herida perdiendo %d puntos de salud}
{514}{}{%s falla críticamente}
{515}{}{%s falla}
{520}{}{%s eres herida críticamente, pierdes %d puntos de salud}
{521}{}{%s eres herida críticamente en %s perdiendo 1 punto de salud}
{522}{}{%s eres herida en %s y pierdes 1 punto de salud}
{523}{}{%s eres herida y pierdes 1 punto de salud}
{524}{}{%s eres críticamente herido y pierdes 1 punto de salud}
{525}{}{%s eres críticamente herido en %s, sin sufrir daño alguno}
{526}{}{%s eres herida en %s sin sufrir daño}
{527}{}{%s recibes un golpe pero no te hace daño}
{528}{}{%s eres críticamente herida sin sufrir daño}
{533}{}{%s falla críticamente y pierde 1 punto de salud}
{534}{}{%s falla críticamente y pierde %d puntos de salud}
{556}{}{Tú}
{559}{}{%s eres herida en vez de %s!}
{561}{}{%s eres herida críticamente en %s, pierdes %d puntos de salud}
{562}{}{%s eres herida en %s perdiendo %d puntos de salud}
{563}{}{%s eres herida perdiendo %d puntos de salud}
{564}{}{%s falla críticamente}
{565}{}{%s falla}
{570}{}{%s eres herida críticamente, pierdes %d puntos de salud}
{571}{}{%s eres herida críticamente en %s perdiendo 1 punto de salud}
{572}{}{%s eres herida en %s y pierdes 1 punto de salud}
{573}{}{%s eres herida y pierdes 1 punto de salud}
{574}{}{%s eres críticamente herido y pierdes 1 punto de salud}
{575}{}{%s eres críticamente herido en %s, sin sufrir daño alguno}
{576}{}{%s eres herida en %s sin sufrir daño}
{577}{}{%s recibes un golpe pero no te hace daño}
{578}{}{%s eres críticamente herida sin sufrir daño}
{583}{}{%s falla críticamente y pierde 1 punto de salud}
{584}{}{%s falla críticamente y pierde %d puntos de salud}
{608}{}{¡Ups! ¡%s es herida en vez de tú!}
{609}{}{¡Ups! ¡%s es herida en vez de %s!}
{611}{}{%s es herida críticamente en %s, perdiendo %d puntos de salud}
{612}{}{%s es herida en %s, pierde %d puntos de salud}
{613}{}{%s es herida, pierde %d puntos de salud}
{614}{}{%s falla críticamente}
{615}{}{%s falla}
{620}{}{%s es críticamente herida, pierde %d puntos de salud}
{621}{}{%s es críticamente herida en %s y pierde 1 punto de salud}
{622}{}{%s es herida en %s y pierde 1 punto de salud}
{623}{}{%s es herida y pierde 1 punto de salud}
{624}{}{%s es críticamente herida y pierde 1 punto de salud}
{625}{}{%s es críticamente herida en %s sin que sufra daño}
{626}{}{%s es herida en %s sin que sufra daño}
{627}{}{%s es herida sin que sufra daño}
{628}{}{%s es críticamente herida sin que sufra daño}
{633}{}{%s falla críticamente y pierde 1 punto de salud}
{634}{}{%s falla críticamente y pierde %d puntos de salud}
{708}{}{¡Ups! ¡%s es herida en vez de tú!}
{709}{}{¡Ups! ¡%s es herida en vez de %s!}
{711}{}{%s es herida críticamente en %s, perdiendo %d puntos de salud}
{712}{}{%s es herida en %s, pierde %d puntos de salud}
{713}{}{%s es herida, pierde %d puntos de salud}
{714}{}{%s falla críticamente}
{715}{}{%s falla}
{720}{}{%s es críticamente herida, pierde %d puntos de salud}
{721}{}{%s es críticamente herida en %s y pierde 1 punto de salud}
{722}{}{%s es herida en %s y pierde 1 punto de salud}
{723}{}{%s es herida y pierde 1 punto de salud}
{724}{}{%s es críticamente herida y pierde 1 punto de salud}
{725}{}{%s es críticamente herida en %s sin que sufra daño}
{726}{}{%s es herida en %s sin que sufra daño}
{727}{}{%s es herida sin que sufra daño}
{728}{}{%s es críticamente herida sin que sufra daño}
{733}{}{%s falla críticamente y pierde 1 punto de salud}
{734}{}{%s falla críticamente y pierde %d puntos de salud}
{1110}{}{la cabeza}
{1111}{}{el brazo izquierdo}
{1112}{}{el brazo derecho}
{1113}{}{el torso}
{1114}{}{la pata derecha}
{1115}{}{la pata izquierda}
{1116}{}{los ojos}
{1117}{}{la ingle}
{1118}{}{un lugar indefinido}
{1150}{}{la cabeza}
{1151}{}{la pata izquierda delantera}
{1152}{}{la pata delantera derecha}
{1153}{}{el torso}
{1154}{}{la pata derecha trasera}
{1155}{}{la izquierda trasera}
{1156}{}{los ojos}
{1157}{}{las ubres}
{1158}{}{un lugar indefinido}
{1160}{}{la cabeza}
{1161}{}{la pata trasera}
{1162}{}{la pata trasera}
{1163}{}{el cuerpo}
{1164}{}{la pata delantera}
{1165}{}{la pata delantera}
{1166}{}{los ojos}
{1167}{}{la ingle}
{1168}{}{un lugar indefinido}
{1170}{}{la CPU}
{1171}{}{el manipulador}
{1172}{}{el manipulador}
{1173}{}{la base}
{1174}{}{la unidad motriz}
{1175}{}{la unidad motriz}
{1176}{}{los sensores}
{1177}{}{el regulador}
{1178}{}{un lugar indefinido}
{1180}{}{la cabeza}
{1181}{}{el brazo izquierdo}
{1182}{}{el brazo derecho}
{1183}{}{el torso}
{1184}{}{la pata derecha}
{1185}{}{la pata izquierda}
{1186}{}{los ojos}
{1187}{}{la ingle}
{1188}{}{un lugar indefinido}
{1190}{}{la cabeza}
{1191}{}{la pata izquierda}
{1192}{}{la pata derecha}
{1193}{}{el cuerpo}
{1194}{}{la pata derecha}
{1195}{}{la pata izquierda}
{1196}{}{los ojos}
{1197}{}{la ingle}
{1198}{}{un lugar indefinido}
{1210}{}{la cabeza}
{1211}{}{el brazo izquierdo}
{1212}{}{el brazo derecho}
{1213}{}{el torso}
{1214}{}{la pata derecha}
{1215}{}{la pata izquierda}
{1216}{}{los ojos}
{1217}{}{la ingle}
{1218}{}{un lugar indefinido}
{1220}{}{la cabeza}
{1221}{}{la cola}
{1222}{}{la garra}
{1223}{}{el caparazón}
{1224}{}{las patas traseras}
{1225}{}{las patas delanteras}
{1226}{}{los ojos}
{1227}{}{el cerebro}
{1228}{}{un lugar indefinido}
{1230}{}{la cabeza}
{1231}{}{la boca}
{1232}{}{la boca delantera}
{1233}{}{el cuerpo}
{1234}{}{el saco flotante}
{1235}{}{la cola}
{1236}{}{los ganglios}
{1237}{}{el ovipositor}
{1238}{}{un lugar indefinido}
{1240}{}{la cabeza}
{1241}{}{la pata izquierda}
{1242}{}{la pata derecha}
{1243}{}{el cuerpo}
{1244}{}{la pata derecha}
{1245}{}{la pata izquierda}
{1246}{}{los ojos}
{1247}{}{la ingle}
{1248}{}{un lugar indefinido}
{1250}{}{la cabeza}
{1251}{}{el brazo izquierdo}
{1252}{}{el brazo derecho}
{1253}{}{el cuerpo}
{1254}{}{la pata derecha}
{1255}{}{la pata izquierda}
{1256}{}{los ojos}
{1257}{}{la ingle}
{1258}{}{un lugar indefinido}
{1270}{}{la cabeza}
{1271}{}{el brazo izquierdo}
{1272}{}{el brazo derecho}
{1273}{}{el torso}
{1274}{}{la pata derecha}
{1275}{}{la pata izquierda}
{1276}{}{los ojos}
{1277}{}{la ingle}
{1278}{}{un lugar indefinido}
{1460}{}{la cabeza}
{1461}{}{el brazo izquierdo}
{1462}{}{el brazo derecho}
{1463}{}{el torso}
{1464}{}{la pata derecha}
{1465}{}{la pata izquierda}
{1466}{}{los ojos}
{1467}{}{la ingle}
{1468}{}{un lugar indefinido}
{1490}{}{la cabeza}
{1491}{}{el brazo izquierdo}
{1492}{}{el brazo derecho}
{1493}{}{el torso}
{1494}{}{la pata derecha}
{1495}{}{la pata izquierda}
{1496}{}{los ojos}
{1497}{}{la ingle}
{1498}{}{un lugar indefinido}
{1500}{}{la cabeza}
{1501}{}{???}
{1502}{}{???}
{1503}{}{la base}
{1504}{}{???}
{1505}{}{???}
{1506}{}{los ojos}
{1507}{}{la CPU}
{1508}{}{un lugar indefinido}
{1510}{}{la cabeza}
{1511}{}{el brazo izquierdo}
{1512}{}{el brazo derecho}
{1513}{}{el torso}
{1514}{}{la pata derecha}
{1515}{}{la pata izquierda}
{1516}{}{los ojos}
{1517}{}{la ingle}
{1518}{}{un lugar indefinido}
{1520}{}{la cabeza}
{1521}{}{la pata raptorial}
{1522}{}{la pata raptorial}
{1523}{}{el abdomen}
{1524}{}{las patas}
{1525}{}{las alas}
{1526}{}{los ojos}
{1527}{}{el metatórax}
{1528}{}{un lugar indefinido}
{1530}{}{la CPU}
{1531}{}{el manipulador}
{1532}{}{el manipulador}
{1533}{}{la base}
{1534}{}{la unidad motriz}
{1535}{}{la unidad motriz}
{1536}{}{los sensores}
{1537}{}{el regulador}
{1538}{}{un lugar indefinido}
{1540}{}{la CPU}
{1541}{}{el manipulador}
{1542}{}{el manipulador}
{1543}{}{la base}
{1544}{}{la unidad motriz}
{1545}{}{la unidad motriz}
{1546}{}{los sensores}
{1547}{}{el regulador}
{1548}{}{un lugar indefinido}
{1550}{}{la cabeza}
{1551}{}{la pata izquierda}
{1552}{}{la pata derecha}
{1553}{}{el cuerpo}
{1554}{}{la pata derecha}
{1555}{}{la pata izquierda}
{1556}{}{los ojos}
{1557}{}{la ingle}
{1558}{}{un lugar indefinido}
{1580}{}{la cáscara}
{1581}{}{la cáscara}
{1582}{}{la cáscara}
{1583}{}{la cáscara}
{1584}{}{la cáscara}
{1585}{}{la cáscara}
{1586}{}{la cáscara}
{1587}{}{la cáscara}
{1588}{}{un lugar indefinido}
{1590}{}{la cabeza}
{1591}{}{la cola}
{1592}{}{la garra}
{1593}{}{el caparazón}
{1594}{}{las patas traseras}
{1595}{}{las patas delanteras}
{1596}{}{los ojos}
{1597}{}{el cerebro}
{1598}{}{un lugar indefinido}
{1600}{}{la cabeza}
{1601}{}{el brazo izquierdo}
{1602}{}{el brazo derecho}
{1603}{}{el torso}
{1604}{}{la pata derecha}
{1605}{}{la pata izquierda}
{1606}{}{los ojos}
{1607}{}{la ingle}
{1608}{}{un lugar indefinido}
{1650}{}{la boca}
{1651}{}{el tallo}
{1652}{}{el tallo}
{1653}{}{el tallo central}
{1654}{}{las raíces}
{1655}{}{las raíces}
{1656}{}{las antenas}
{1657}{}{la base}
{1658}{}{un lugar indefinido}
{1660}{}{la cabeza}
{1661}{}{el misil de mano}
{1662}{}{la pistola de mano}
{1663}{}{el cuerpo}
{1664}{}{la pata derecha}
{1665}{}{la pata izquierda}
{1666}{}{los sensores}
{1667}{}{el torso inferior}
{1668}{}{un lugar indefinido}
{1670}{}{la cabeza}
{1671}{}{la garra izquierda}
{1672}{}{la garra derecha}
{1673}{}{el cuerpo}
{1674}{}{la pata derecha}
{1675}{}{la pata izquierda}
{1676}{}{los ojos}
{1677}{}{la ingle}
{1678}{}{un lugar indefinido}
{1680}{}{la cabeza}
{1681}{}{la garra izquierda}
{1682}{}{la garra derecha}
{1683}{}{el cuerpo}
{1684}{}{la pata derecha}
{1685}{}{la pata izquierda}
{1686}{}{los ojos}
{1687}{}{la ingle}
{1688}{}{un lugar indefinido}
{1800}{}{la cabeza}
{1801}{}{el tentáculo izquierdo}
{1802}{}{el tentáculo derecho}
{1803}{}{el cuerpo}
{1804}{}{el pie derecho}
{1805}{}{el pie izquierdo}
{1806}{}{¿los ojos?}
{1807}{}{el enchufe de la ingle}
{1808}{}{un lugar indefinido}
{1850}{}{la cabeza}
{1851}{}{el brazo izquierdo}
{1852}{}{el brazo derecho}
{1853}{}{el torso}
{1854}{}{la pata derecha}
{1855}{}{la pata izquierda}
{1856}{}{los ojos}
{1857}{}{la ingle}
{1858}{}{un lugar indefinido}
{1860}{}{la cabeza}
{1861}{}{el tentáculo izquierdo}
{1862}{}{el tentáculo derecho}
{1863}{}{el cuerpo}
{1864}{}{el pie derecho}
{1865}{}{el pie izquierdo}
{1866}{}{¿los ojos?}
{1867}{}{el enchufe de la ingle}
{1868}{}{un lugar indefinido}
{1900}{}{la cpu}
{1901}{}{la servoarma}
{1902}{}{la servoarma}
{1903}{}{la base}
{1904}{}{la servobase}
{1905}{}{la servobase}
{1906}{}{los sensores}
{1907}{}{el regulador}
{1908}{}{un lugar indefinido}
{1970}{}{la cabeza}
{1971}{}{la izquierda trasera}
{1972}{}{la pata derecha trasera}
{1973}{}{el abdomen}
{1974}{}{la pata delantera derecha}
{1975}{}{la pata izquierda delantera}
{1976}{}{las antenas}
{1977}{}{el metatórax}
{1978}{}{un lugar indefinido}
{1990}{}{la cabeza}
{1991}{}{el brazo izquierdo}
{1992}{}{el brazo derecho}
{1993}{}{el torso}
{1994}{}{la pata derecha}
{1995}{}{la pata izquierda}
{1996}{}{los ojos}
{1997}{}{la ingle}
{1998}{}{un lugar indefinido}
{2000}{}{la cabeza}
{2001}{}{el brazo izquierdo}
{2002}{}{el brazo derecho}
{2003}{}{el torso}
{2004}{}{la pata derecha}
{2005}{}{la pata izquierda}
{2006}{}{los ojos}
{2007}{}{la ingle}
{2008}{}{un lugar indefinido}
{2010}{}{la cpu}
{2011}{}{la servoarma}
{2012}{}{la servoarma}
{2013}{}{la base}
{2014}{}{la servobase}
{2015}{}{la servobase}
{2016}{}{los sensores}
{2017}{}{el regulador}
{2018}{}{un lugar indefinido}
{2030}{}{la cabeza}
{2031}{}{el aguijón}
{2032}{}{las antenas}
{2033}{}{el tórax}
{2034}{}{las patas traseras}
{2035}{}{las patas delanteras}
{2036}{}{los ojos}
{2037}{}{las alas}
{2038}{}{un lugar indefinido}
{5000}{}{. Eso realmente duele}
{5001}{}{. provocándole una fea herida}
{5002}{}{ traspasando su armadura}
{5003}{}{. El ataque lo deja inconsciente}
{5004}{}{. El golpe lo tira al suelo}
{5005}{}{. El fuerte golpe en la cabeza lo deja fuera de combate}
{5006}{}{. El ataque aplasta su sien. Buenas noches, Gracie}
{5007}{}{. La muerte es instantánea}
{5008}{}{, causando una grave luxación en el codo}
{5009}{}{, arrancándole el brazo}
{5010}{}{, dejando un gran hematoma}
{5011}{}{, rompiéndole el brazo izquierdo}
{5012}{}{, dejando el brazo izquierdo colgando de la piel}
{5013}{}{. Ahora ese brazo parece un muñón sangriento}
{5014}{}{, dejándole el brazo derecho roto}
{5015}{}{. Su brazo derecho queda pulverizado por este potente golpe}
{5016}{}{ en un potente golpe}
{5017}{}{, al perforar sus defensas}
{5018}{}{, provocando aún mas daño}
{5019}{}{ traspasando su armadura y tumbándole en el suelo}
{5020}{}{, dejándole sin aire. Se derrumba en el suelo, quedando fuera de combate}
{5021}{}{. Desafortunadamente, varios órganos vitales son ahora claramente visibles}
{5022}{}{, dejando una gran herida en su pierna}
{5023}{}{, tirándole al suelo como un bolo en medio de una bolera}
{5024}{}{, tumbándole y rompiéndole esa pierna}
{5025}{}{, enviándole la rotula a la ciudad mas cercana. Se cae}
{5026}{}{. el terrible dolor de perder una pierna hace que huya}
{5027}{}{, provocándole más dolor}
{5028}{}{. Desafortunadamente para el, causa ceguera}
{5029}{}{. Sin protección ahí, le causa un grave dolor}
{5030}{}{, y se queda K.O. por un potente golpe}
{5031}{}{. La perdida de un ojo es demasiado para él, y se cae al suelo}
{5032}{}{. Con tristeza, está demasiado ocupado notando como el aire entra en su cerebro para darse cuenta de que se muere}
{5033}{}{. ¡Ouch! Eso tuvo que doler}
{5034}{}{, y tampoco lleva coquilla}
{5035}{}{. Sin protección, se cae, gimiendo de agonía}
{5036}{}{. El dolor es demasiado para él y se desploma como un castillo de naipes}
{5037}{}{. Susurra "Mamá", mientras sus ojos se quedan en blanco}
{5100}{}{. Eso realmente duele}
{5101}{}{. provocándole una fea herida}
{5102}{}{ traspasando su armadura}
{5103}{}{. El ataque la deja inconsciente}
{5104}{}{. El golpe la tira al suelo}
{5105}{}{. El fuerte golpe en la cabeza la deja fuera de combate}
{5106}{}{. El ataque aplasta su sien. Buenas noches, Gracie}
{5107}{}{. La muerte es instantánea}
{5108}{}{, causando una grave luxación en el codo}
{5109}{}{, arrancándole el brazo}
{5110}{}{, dejando un gran hematoma}
{5111}{}{, rompiéndole el brazo izquierdo}
{5112}{}{. El brazo izquierdo y su hombro apenas siguen unidos}
{5113}{}{. Ahora ese brazo parece un muñón sangriento}
{5114}{}{, dejándole el brazo derecho roto}
{5115}{}{. El golpe convierte su brazo derecho en carne picada}
{5116}{}{ en un potente golpe}
{5117}{}{, al perforar sus defensas}
{5118}{}{, provocando aún mas daño}
{5119}{}{ traspasando su armadura y tumbándola en el suelo}
{5120}{}{, dejándola sin aire. Se desploma en el suelo}
{5121}{}{. Desafortunadamente, varios órganos vitales son ahora claramente visibles}
{5122}{}{, dejando una gran herida en su pierna}
{5123}{}{, dejándola tirada como a una mala cita a ciegas}
{5124}{}{, tumbándola y rompiéndole esa pierna}
{5125}{}{, enviándole la rotula a la ciudad mas cercana. Se cae}
{5126}{}{. Grita por el dolor de su pierna rota}
{5127}{}{, provocándole más dolor}
{5128}{}{, causando ceguera. Gime de dolor}
{5129}{}{. Sin protección ahí, le causa un grave dolor}
{5130}{}{. La herida le causa una severa ceguera, como si hubiese mas de un tipo de ceguera}
{5131}{}{. Se desmaya por el potente golpe}
{5132}{}{. Por desgracia, no tiene tiempo de rezar sus ultimas oraciones}
{5133}{}{. Se lo toma como un hombre. Es decir, le duele}
{5134}{}{, tirándola al suelo}
{5135}{}{. Sus días de maternidad están en entredicho mientras siga cojeando tanto}
{5200}{}{. El pequeño empieza a llorar}
{5201}{}{. inconsciente, el niño se cae}
{5202}{}{. ¡Ouch!}
{5203}{}{. El golpe es fuerte, y el niño cae inconsciente}
{5204}{}{, quebrando al niño como a un muñeco de trapo}
{5205}{}{. El brazo de este niño ahora parece un muñón}
{5206}{}{, desequilibrando al niño, que cae al suelo}
{5207}{}{, rompiéndole ese brazo con un ruidoso crujido. El niño empieza a llorar}
{5208}{}{, quebrando fácilmente ese brazo como un papel de caramelo}
{5209}{}{. El brazo derecho comienza a hincharse, como un globo}
{5210}{}{, y empieza a llorar}
{5211}{}{ en un punto sensible}
{5212}{}{. El ataque a un órgano vital deja al niño en el suelo}
{5213}{}{, tirando al niño como un juguete}
{5214}{}{. Ahora este niño nunca vivirá la verdadera experiencia de la salud}
{5215}{}{, provocándole un corte profundo}
{5216}{}{. El ataque hace rodar al niño, y se rompe la pierna}
{5217}{}{, produciéndole mucho daño al niño}
{5218}{}{. El niño alza la vista y empieza a llorar}
{5219}{}{, que ciega al niño}
{5220}{}{, golpeándole en su joven nariz}
{5221}{}{. Un corte aparece sobre los ojos y la sangre empieza a manar sin control}
{5222}{}{, que le abre un ojo como una uva cuando estalla. El niño parece desconcertado}
{5223}{}{, causando ceguera. El joven cae al suelo}
{5224}{}{, el golpe se prolonga por el pequeño cerebro}
{5225}{}{. El niño parece confuso y trastornado}
{5226}{}{, golpeando a este joven hacia el suelo}
{5300}{}{, hiriendo al poderoso mutante}
{5301}{}{, dándole en un punto vital}
{5302}{}{, dándole en un punto vital y derribando al gigante al suelo}
{5303}{}{. El gran mutante mira alrededor un momento, y se desploma en el suelo}
{5304}{}{. La cabeza estalla como una gigante y sangrienta sandía}
{5305}{}{, hiriendo severamente al poderoso mutante}
{5306}{}{, causando que el gigante dedique un momento a maldecir al universo}
{5307}{}{, golpeándole un nervio y forzando al mutante a sujetarse su brazo por el dolor}
{5308}{}{. El golpe le rompe el codo y probablemente no se sienta demasiado bien}
{5309}{}{, rompiéndole el brazo y derramando la sangre del mutante por el suelo}
{5310}{}{, causándole un traspiés al gigante y éste se derrumba como un árbol talado}
{5311}{}{, y trozos de vísceras caen al suelo}
{5312}{}{, tirando rápidamente al gigante al suelo}
{5313}{}{. El mutante da un traspié y se cae, su pierna apenas es capaz de sostenerle}
{5314}{}{, golpeándole en una parte vital. El mutante se estruja su pierna rota}
{5315}{}{. El dolor de una pierna rota abruma al poderoso gigante}
{5316}{}{, a punto de cegar al mutante}
{5317}{}{, cegando al furioso mutante}
{5318}{}{, a punto de cegar al mutante pero derribándolo}
{5319}{}{. El mutante cegado tropieza, desprotegido para el siguiente ataque}
{5320}{}{, cegando al ahora inconsciente mutante}
{5321}{}{. Los ojos del mutante brillan un momento, y entonces se desvanecen... permanentemente}
{5400}{}{. El necrófago es sorprendido, y falla al intentar defenderse contra este ataque}
{5401}{}{. El golpe entierra a este necrófago}
{5402}{}{. La mano de este necrófago atontado voló de golpe}
{5403}{}{, sigilosamente a través de su armadura y golpeándole críticamente}
{5404}{}{, sigilosamente a través de su armadura y cortándole el brazo}
{5405}{}{. El necrófago se mueve de la manera equivocada en el momento equivocado, y pierde un ojo}
{5406}{}{. El necrófago no lleva armadura ahí}
{5407}{}{, y traspasando su armadura, el necrófago es cegado}
{5408}{}{, haciendo que el necrófago contemple desconcertado su momento final}
{5500}{}{, tumbando a la gran bestia en el suelo}
{5501}{}{, atontando a ambos cerebros y haciendo caer al gran animal}
{5502}{}{. La vaca mutante hace un ruido: ha empezado a llorar}
{5503}{}{, rompiendo una de las patas del brahmin}
{5504}{}{, hiriendo seriamente a la vaca mutante}
{5505}{}{, penetrando con facilidad la gruesa piel de la bestia gigante}
{5506}{}{, penetrando directamente a través de ambos corazones de la vaca mutante}
{5507}{}{, cegando ambos conjuntos de ojos con un solo golpe}
{5508}{}{, cegando ambas cabezas y atontando a la vaca mutante}
{5509}{}{, cegando completamente al brahmin y tumbándolo}
{5510}{}{. El gran bovino mutante tropieza}
{5511}{}{. El brahmin se sacude con rabia}
{5512}{}{. El brahmin resopla de dolor}
{5513}{}{. El brahmin está totalmente furioso por ese ataque devastador}
{5600}{}{, haciendo que el escorpión aterrice sobre su espalda}
{5601}{}{, separando la cabeza del caparazón}
{5602}{}{, dañándole gravemente la cola}
{5603}{}{, dejando una importante herida en sus garras}
{5604}{}{. El golpe se desliza entre las grietas de su resistente caparazón}
{5605}{}{, dándole en el resistente caparazón sin detenerse}
{5606}{}{, pasando a través de caparazón y golpeando sobre el escorpión}
{5607}{}{. El escorpión no se acostumbra a la nueva sensación de falta de órganos internos}
{5608}{}{, haciendo volar al escorpión y rompiéndole una de sus patas}
{5609}{}{. El ataque corta la desprotegida articulación de la pierna, amputándola}
{5610}{}{, hiriéndole gravemente y cegando a la criatura mutante}
{5611}{}{, penetrándole casi hasta el cerebro. Esto sí que es aplastar bichos}
{5612}{}{, penetrando casi hasta el cerebro y cegando a la criatura}
{5613}{}{. El ataque es diabólico y demasiado sofisticado para esta criatura tan simple}
{5614}{}{. Si fuera humano, jurarías que está muy cabreado}
{5615}{}{, golpeando a la insensible y pobre criatura}
{5616}{}{, arrojando su cerebro al suelo}
{5700}{}{. El cráneo del roedor hace varios sonidos enfermizos}
{5701}{}{, aplastando el cráneo del roedor como una bolsa de papel mojado}
{5702}{}{, y la pata izquierda ahora parece un poco más suelta}
{5703}{}{. La pata izquierda de la rata quedó inútil}
{5704}{}{. La pata derecha está muy dañada}
{5705}{}{, golpeando la pata derecha}
{5706}{}{. La rata está seriamente herida por este ataque}
{5707}{}{, hiriendo profundamente a la rata}
{5708}{}{, aplastando la rata contra el suelo}
{5709}{}{, rompiéndole la pata derecha}
{5710}{}{, haciéndole un gran agujero en su pata izquierda}
{5711}{}{, haciendo más daño por darle en un punto sensible}
{5712}{}{, enviando a esta criatura al gran paraíso de las ratas}
{5800}{}{. El nómada cae al suelo}
{5801}{}{. El nómada cae al suelo, aparentemente con menos salud}
{5802}{}{, con serias consecuencias para su existencia}
{5803}{}{, atontando a la horrible criatura}
{5804}{}{, golpeándolo en un punto sensible y atontando al nómada}
{5805}{}{. El golpe hace que el nómada se estremezca violentamente en un chorro carmesí}
{5806}{}{. El golpe causa algún tipo de reacción violenta en la criatura}
{5807}{}{. El nómada de pronto estalla en llamas}
{5808}{}{. Sufre una sacudida frenética y se estremece como gelatina}
{5809}{}{, golpeándole en un punto sensible}
{5810}{}{. La criatura está obviamente agitada}
{5900}{}{. El centauro se tropieza y queda atontado}
{5901}{}{ el golpe alcanzó un punto crítico}
{5902}{}{, causando un fallo neurológico masivo}
{5903}{}{, atontándolo por tu ataque violento}
{5904}{}{, rompiéndole el brazo}
{5905}{}{, dándole en un punto crítico. El brazo está roto}
{5906}{}{, tirando a la criatura y rompiéndole la pata}
{5907}{}{, atontando al centauro al tiempo que cae debido a una pata rota}
{5908}{}{, cegándole}
{5909}{}{, sorprendiendo al centauro. Cegado, se tropieza}
{5910}{}{, sorprendiendo al centauro. Se desploma}
{5911}{}{, sorprendiendo al centauro. Se desploma como un montón de materia pegajosa}
{5912}{}{. El ataque no fue tan eficaz como podría haber sido}
{6000}{}{, produciéndole cierto daño estructural}
{6001}{}{. Vuelan las chispas y el robot pierde momentáneamente el control}
{6002}{}{, golpeando un componente crítico y forzando al robot a perder el control}
{6003}{}{, golpeando un componente crítico y causándole un fallo de funcionamiento masivo}
{6004}{}{. El robot intenta compensarse}
{6005}{}{. El robot se esfuerza en compensarse}
{6006}{}{, golpeándole en una parte clave y causando mucho daño}
{6007}{}{, provocándole muchos daños estructurales}
{6008}{}{, golpeando un componente crítico y causándole daños graves}
{6009}{}{. El robot se estremece bajo este intenso ataque}
{6010}{}{, desmontando al robot}
{6011}{}{. El robot intenta compensar el golpe, pero falla, cayendo al suelo}
{6012}{}{. El robot se agota bajo la presión, cayéndose al suelo}
{6013}{}{, rompiéndole las lentes de los sensores}
{6100}{}{, tirando al perro al suelo}
{6101}{}{, justo a través del hocico}
{6102}{}{. El perro se cae, pero todavía sigue respirando}
{6103}{}{. El animal tose sangre}
{6104}{}{, rompiéndole la pata}
{6105}{}{, rompiéndole la pata. El animal intenta seguir en pie, pero no puede}
{6106}{}{. El animal cegado aúlla de dolor}
{6107}{}{, neutralizando al pobre animal}
{6200}{}{, tumbando a este insecto mutante}
{6201}{}{. Se desploma}
{6202}{}{. La mantis no sabe si seguirá o no viviendo}
{6203}{}{, rompiéndole un miembro}
{6204}{}{, haciendo que la mantis lama sus heridas. Sujeta su miembro extrañamente}
{6205}{}{, traspasando su caparazón}
{6206}{}{. Los chillidos y temblores de la mantis no parecen los de un ser humano}
{6207}{}{, lo que causa que la mantis caiga. Un miembro de su cuerpo está extrañamente doblado}
{6208}{}{, triturando sus alas}
{6209}{}{, traspasando su caparazón y tirando a la mantis}
{6210}{}{, cegando a la mantis con un golpe preciso}
{6300}{}{. Incluso esta bestia parece asombrada por ese increíble ataque}
{6301}{}{, yendo más allá de las enormes garras para golpear al monstruo. Éste se sacude y gruñe}
{6302}{}{. El resultado es un masivo daño en los ojos de la Garra mortal}
{6400}{}{, rompiendo las defensas de la planta}
{6401}{}{, arrancando algunas de sus hojas}
{6402}{}{, rompiendo algunas de sus hojas}
{6403}{}{, dañándole su tallo}
{6404}{}{, extrayéndole todo su polen}
{6405}{}{, casi tumbándola}
{6406}{}{, dañando algunas de sus ramas}
{6500}{}{. Mañana tendrás dolor de cabeza, si es que aún vives para ver otro amanecer}
{6501}{}{. Tu armadura no te proporciona ninguna protección contra este golpe bien dirigido}
{6502}{}{. Sientes dolor durante un momento, y entonces se te oscurece la vista...}
{6503}{}{, traspasando tu armadura. El golpe te hace caer}
{6504}{}{. El choque hace que te quedes a ciegas. Después de un momento, te das cuenta de que sigues sin ver}
{6505}{}{. Consigues una bonita vista de tu cuerpo cuando tu cabeza salta por los aires}
{6506}{}{. Asombrosamente, el daño parece menor de lo normal}
{6507}{}{, aturdiéndote por un momento}
{6508}{}{. Sientes un terrible dolor}
{6509}{}{. El ataque te deja el brazo inútil}
{6510}{}{, traspasando tu armadura. El golpe hace crujir los huesos de tu brazo igual que un tallo seco}
{6511}{}{, traspasando tu armadura. Tu brazo ahora cuelga inerte}
{6512}{}{. La herida quedará bien, y tus cicatrices servirán de tema de conversación}
{6513}{}{, haciéndote puré los órganos internos. Todo lo que puedes hacer es escupir sangre}
{6514}{}{, haciéndote caer redondo al suelo}
{6515}{}{, derribándote y rompiéndote la pierna}
{6516}{}{, disolviendo tu armadura. El golpe te tira al suelo y daña gravemente tu rodilla}
{6517}{}{. El dolor de tu pierna rota hace que caigas inconsciente}
{6518}{}{. El doloroso golpe hace que te encojas, pero poco más}
{6519}{}{. Desafortunadamente para ti, tiene como efectos secundarios la inmediata perdida de visión}
{6520}{}{. Te tomas un momento para limpiar la sangre de tus ojos}
{6521}{}{, traspasando tu armadura. Te quedas aturdido hasta que te das cuenta de que no puedes ver nada}
{6522}{}{. Sientes una extraña sensación en tu cabeza. Te das cuenta de que tu cerebro está a punto de morir}
{6523}{}{, haciéndote temblar}
{6524}{}{. Te echas las manos a la ingle y caes al suelo retorciéndote de dolor}
{6525}{}{. El dolor es suficiente para hacer que te derrumbes en el suelo. ¡Ouch!}
{6526}{}{. No hay suficientes palabras en el universo para describir el dolor que estás sintiendo en este momento}
{6700}{}{, traspasando las defensas del lagarto}
{6701}{}{, arrancando algo de su babosa piel}
{6702}{}{, rompiendo algunos de sus dedos}
{6703}{}{, dejándole sin respiración}
{6704}{}{, arrancándole las vísceras}
{6705}{}{, casi tumbándola}
{6706}{}{, dañando algunos de sus miembros}
{6800}{}{, traspasando las defensas de la criatura}
{6801}{}{, haciendo que se manche con sus propias babas}
{6802}{}{, triturando algunos de sus succionadores}
{6803}{}{, dañando su aparato ¿respiratorio?}
{6804}{}{, sacándole las entrañas}
{6805}{}{, casi tumbándola}
{6806}{}{, dañándole sus tentáculos}
{6900}{}{, rompiendo las defensas de la hormiga}
{6901}{}{, arrancando varias de sus antenas}
{6902}{}{, dañando algunos de sus sensores}
{6903}{}{, dañando su salud}
{6904}{}{, haciéndola tambalear}
{6905}{}{, casi tumbándola}
{6906}{}{, dañando parte de su exoesqueleto}
{7000}{}{, rompiendo las defensas de la hormiga}
{7001}{}{, arrancando varias de sus antenas}
{7002}{}{, dañando algunos de sus sensores}
{7003}{}{, dañando su salud}
{7004}{}{, haciéndola tambalear}
{7005}{}{, casi tumbándola}
{7006}{}{, dañando parte de su exoesqueleto}
{7100}{}{, traspasando su armadura}
{7101}{}{, haciéndolo caer de rodillas}
{7102}{}{, destruyendo su mecanismo de control de los brazos}
{7103}{}{, destruyendo su mecanismo de rotación de las piernas}
{7104}{}{, cargándose su ojo biónico}
{7105}{}{, haciendo que se detenga y tiemble por tu brutal ataque}
{7106}{}{, compactando su esternón}
