{200}{}{Caverna Entrada}
{201}{}{Entrada}
{202}{}{Habitaciones}
{203}{}{Centro de Mando}
{210}{}{Entrada Desierto}
{211}{}{Caverna/Entrada}
{212}{}{Habitaciones}
{213}{}{Centro de Mando}
{220}{}{Entrada}
{221}{}{Jardin}
{222}{}{Corral Brahmines}
{230}{}{Entrada}
{231}{}{Vertedero}
{232}{}{Casino}
{240}{}{Base}
{250}{}{Hotel}
{251}{}{Sala}
{252}{}{Almacén de Agua}
{260}{}{Entrada}
{261}{}{Centro Ciudad}
{262}{}{Alturas}
{263}{}{Ciudad Vieja}
{264}{}{Mercaderes}
{265}{}{Cueva}
{270}{}{Entrada}
{271}{}{Nivel 1}
{272}{}{Nivel 2}
{273}{}{Nivel 3}
{274}{}{Nivel 4}
{280}{}{Entrada}
{281}{}{Fortaleza Nivel 1}
{282}{}{Fortaleza Nivel 2}
{283}{}{Cubas Nivel 1}
{284}{}{Cubas Nivel 2}
{290}{}{Crater}
{291}{}{Nivel 1}
{300}{}{Adytum}
{301}{}{Centro Ciudad}
{302}{}{Libreria}
{303}{}{Fortaleza}
{304}{}{Almacen}
{310}{}{Entrada}
{311}{}{Interior}
{500}{}{¡Has ganado 10.000 puntos de experiencia!}
{501}{}{Ruinas}
{1000}{}{Desierto}
{1001}{}{Montañas}
{1002}{}{Ciudad}
{1003}{}{Costa}
{1004}{}{Desconocido}
