{100}{}{Armadura de cuero}
{101}{}{Tu atuendo básico de cuero. Hecho artesanalmente con piel curtida de brahmin.}
{200}{}{Armadura de metal}
{201}{}{Placas de metal pulidas formando toscamente una armadura.}
{300}{}{Servoarmadura}
{301}{}{Una armadura autónoma con tecnología avanzada. Alimentada con un reactor de micro-fusión, con suficiente combustible para cientos de años.}
{400}{}{Cuchillo}
{401}{}{Una hoja afilada, cortante y punzante. Min FU: 2.}
{500}{}{Porra}
{501}{}{Una porra militar o de la policía. De madera maciza. Min FU: 3.}
{600}{}{Almádena}
{601}{}{Un gran martillo con un mango también grande. Muy popular entre la gente musculosa. Min FU: 6.}
{700}{}{Lanza}
{701}{}{Un palo con una hoja afilada. El mango es de madera, y la punta es de acero. Min FU: 4.}
{800}{}{Pistola de 10mm}
{801}{}{Una pistola Colt 6520 con cargador automático de 10mm. Cada disparo recargará automáticamente el arma hasta que se vacíe el cilindro. De un solo disparo, usa las potentes balas de 10mm. Min FU: 3.}
{900}{}{SMG de 10mm}
{901}{}{Sub-ametralladora H&K MP9 (variante de 10mm). Una SMG de tamaño medio, de disparo único o modo ráfaga. Min FU: 4.}
{1000}{}{Rifle de caza}
{1001}{}{Un rifle semiautomático Colt Rangemaster, de calibre .223. De un solo disparo. Min FU: 5.}
{1100}{}{Lanzallamas}
{1101}{}{Un lanzallamas modelo Flambe 450, variante 'varmiter'. Dispara un chorro corto de líquido inflamable extremadamente caliente. Requiere un combustible especial para que funcione correctamente. Min ST: 6.}
{1200}{}{Minicañón}
{1201}{}{Un minicañón personal Rockwell CZ53. Una ametralladora de cañón múltiple que dispara municiones de 5mm a 60.000 RPM. Min FU: 7.}
{1300}{}{Lanzacohetes}
{1301}{}{Un lanzacohetes Rockwell BigBazooka. Con gatillo deluxe de 3 lb. Dispara cohetes explosivos o AP. Min FU: 6.}
{1400}{}{Cohete explosivo}
{1401}{}{Un cohete con una gran cabeza explosiva.}
{1500}{}{Rifle de plasma}
{1501}{}{Un rifle de plasma Winchester P94. Un arma energética de grado industrial, que dispara rayos de plasma supercalientes  por un cañón superconductor. Alimentado por células MF de microfusión. Min FU: 6.}
{1600}{}{Pistola láser}
{1601}{}{Una pistola láser Wattz 1000. Modelo civil, así que tiene menor potencia que las versiones militares y de la policía. Usa células PE de energía. Min FU: 3.}
{1700}{}{Armadura de combate}
{1701}{}{Armadura de alta tecnología, elaborada con polímeros defensivos avanzados.}
{1800}{}{Desert Eagle .44}
{1801}{}{Una antigua pistola Desert Eagle, mágnum .44. Su participación en películas de finales del siglo XX la convirtió en una de las pistolas más populares de todos los tiempos. Min FU: 4.}
{1900}{}{Roca}
{1901}{}{Es una roca. Modelo Granite-Inc., en una versión actualizada. Min FU: 1.}
{2000}{}{Palanca}
{2001}{}{Una pieza de metal muy sólida y pesada, especialmente diseñada para apalancar. O para golpear cabezas. Min FU: 5.}
{2100}{}{Nudilleras}
{2101}{}{Duras nudilleras hechas de auténtico acero. Protegen tu mano, y hacen más daño en un combate desarmado. Min FU: 1.}
{2200}{}{Pistola de 14mm}
{2201}{}{Una pistola automática Sig-Sauer de 14mm. Una gran arma de disparo único. Excelente artesanía. Min FU: 4.}
{2300}{}{Rifle de asalto}
{2301}{}{Un rifle de asalto AK-112 de 5mm. Un antiguo modelo militar, en desuso en la época de la guerra. Puede disparar un único tiro o una ráfaga, usando balas de 5mm de alta velocidad. Min FU: 5.}
{2400}{}{Pistola de plasma}
{2401}{}{Pistola de plasma Glock 86. Diseñada por la Gaston Glock AI. Dispara un pequeño rayo de plasma supercaliente. Alimentada por células PE energía. Min FU: 4.}
{2500}{}{Granada de fragmentación}
{2501}{}{Una granada de fragmentación genérica. Contiene una pequeña cantidad de alto explosivo, y la propia carcasa forma parte de los fragmentos dañinos. Explota al contacto. Min FU: 3.}
{2600}{}{Granada de plasma}
{2601}{}{Una unidad de plasma sellada magnéticamente, con explosivos detonantes. Crea una ráfaga de plasma supercaliente al contacto. Min FU: 4.}
{2700}{}{Granada IEM}
{2701}{}{Una granada de impulso electromagnético, genera un intenso campo magnético al detonar. No afecta a las criaturas biológicas. Se funde al contacto. Min FU: 4.}
{2800}{}{Gatling láser}
{2801}{}{Una Gatling H&K L30 láser. Diseñada para uso militar, estaba en fase de prototipo al principio de la gran guerra. Sus múltiples cañones le permiten disparar varias veces antes de sobrecalentarse. Alimentada por células MF de microfusión. Min FU: 6.}
{2900}{}{10mm BHC}
{2901}{}{Munición calibre: 10mm, de punta hueca y chaqueta metálica.}
{3000}{}{10mm PB}
{3001}{}{Munición calibre: 10mm, perforante.}
{3100}{}{.44 mágnum BHC}
{3101}{}{Munición calibre .44 mágnum, de punta hueca.}
{3200}{}{Comb. Lanzallamas}
{3201}{}{Un cilindro que contiene un líquido combustible extremadamente inflamable para lanzallamas.}
{3300}{}{14mm PB}
{3301}{}{Munición de gran calibre. 14mm perforante.}
{3400}{}{.223 CM}
{3401}{}{Una caja de munición calibre .223, con chaqueta metálica.}
{3500}{}{5mm BHC}
{3501}{}{Una munición pequeña y ligera. Calibre: 5mm, de punta hueca y chaqueta metálica.}
{3600}{}{5mm PB}
{3601}{}{Munición de pequeño calibre, 5mm perforante.}
{3700}{}{Cohete PB}
{3701}{}{Un cohete con explosivo de pequeña potencia pero diseñado para perforar blindajes.}
{3800}{}{Células PE}
{3801}{}{Una pequeña unidad autónoma de almacenamiento de energía.}
{3900}{}{Células MF}
{3901}{}{Una unidad de producción de energía de tamaño medio. Con reactor de fusión autónomo.}
{4000}{}{Estimulante}
{4001}{}{Un producto químico curativo. Cuando se inyecta, la sustancia química cura inmediatamente heridas menores.}
{4100}{}{Dinero}
{4101}{}{Moneda de curso legal en el Yermo.}
{4200}{}{Refrigerador}
{4201}{}{Un refrigerador. Sin líquido refrigerante.}
{4300}{}{Congelador}
{4301}{}{Un tipo antiguo de congelador. Las bisagras están en buenas condiciones.}
{4400}{}{Congelador}
{4401}{}{Un tipo antiguo de congelador. Las bisagras están en buenas condiciones.}
{4500}{}{Cuchillo arrojadizo}
{4501}{}{Un cuchillo específicamente equilibrado para ser lanzado. Hecho de titanio, y afilado con láser. Min FU: 3.}
{4600}{}{Maleta}
{4601}{}{Una bolsa de tamaño medio. Hecha con tejido de pelo de brahmin.}
{4700}{}{Kit de primeros auxilios}
{4701}{}{Un pequeño kit que contiene equipamiento médico básico. Vendas, gasas, spray antiséptico, y más.}
{4800}{}{RadAway}
{4801}{}{Una solución química que enlaza con las partículas radiactivas y las elimina de tu sistema. Necesita tiempo para que funcione.}
{4900}{}{Antídoto}
{4901}{}{Una botella que contiene un antídoto casero para el veneno. Un líquido espeso con trozos de carne de escorpiones rad.}
{5000}{}{Objeto reservado}
{5001}{}{Esto es un objeto reservado. NO USAR.}
{5100}{}{Dinamita}
{5101}{}{Un explosivo de alta potencia, elaborado al mezclar la nitroglicerina con una sustancia absorbente llamada kiselguhr. Incluye un temporizador.}
{5200}{}{Contador Geiger}
{5201}{}{Un modelo C-Radz de contador Geiger, de Wattz Electronics. Detecta la presencia y la intensidad de los campos radiactivos.}
{5300}{}{Mentats}
{5301}{}{Una caja de píldoras que alteran la mente. Incrementa las funciones relacionadas con la memoria, y la velocidad de otros procesos mentales. Altamente adictiva.}
{5400}{}{Sigilante}
{5401}{}{Un dispositivo personal de sigilo Stealth Boy 3001, de RobCo. Genera un campo modulado que transmite la luz reflejada de la cara de un objeto sobre otra.}
{5500}{}{Chip de agua}
{5501}{}{Un chip de agua de Vault-Tec. Normalmente se empaquetan en grupos de cinco por caja.}
{5600}{}{Chapas de identificación}
{5601}{}{Un juego de chapas de identificación. El nombre Dickinson y la palabra Enclave son apenas legibles.}
{5700}{}{Micrófono}
{5701}{}{Un pequeño micrófono y dispositivo de trasmisión.}
{5800}{}{Holodisco}
{5801}{}{Una holodisco de Wattz Electronics. Este disco en particular parece estar en muy malas condiciones.}
{5900}{}{Sensor de movimiento}
{5901}{}{Un sensor de movimiento modelo C-U de Wattz Electronics. Detecta el movimiento de la materia biológica a varios metros de distancia usando un radar sintonizado. Tener uno en tu inventario también te ayudará a evitar encuentros al aire libre (+20% a la habilidad Supervivencia).}
{6000}{}{Estantería}
{6001}{}{Una estantería de madera.}
{6100}{}{Estantería}
{6101}{}{Una estantería de madera.}
{6200}{}{Estantería}
{6201}{}{Una estantería de madera.}
{6300}{}{Estantería}
{6301}{}{Una estantería de madera.}
{6400}{}{Estantería}
{6401}{}{Una estantería de madera.}
{6500}{}{Estantería}
{6501}{}{Una estantería de madera.}
{6600}{}{Escritorio}
{6601}{}{Un escritorio de madera.}
{6700}{}{Escritorio}
{6701}{}{Un escritorio de madera.}
{6800}{}{Vestidor}
{6801}{}{Un tocador de madera.}
{6900}{}{Vestidor}
{6901}{}{Un tocador de madera.}
{7000}{}{Vestidor}
{7001}{}{Un tocador de madera.}
{7100}{}{Fruta}
{7101}{}{Una extraña pieza de fruta. Sin conservantes ni colorantes.}
{7200}{}{Maletín}
{7201}{}{Un maletín, con una etiqueta de 'Fabricado en USA'. De cuero. En buenas condiciones, pero con la cerradura de combinación rota.}
{7300}{}{El gran libro de la ciencia}
{7301}{}{Una colección de libros que contiene información sobre diferentes campos de la ciencia.}
{7400}{}{Chaqueta de cuero}
{7401}{}{Una chaqueta de cuero negra y pesada.}
{7500}{}{Set de herramientas}
{7501}{}{Un set de herramientas, con varios útiles, incluyendo alicates.}
{7600}{}{El decano de la electrónica}
{7601}{}{Un libro de estudio del campo de la electrónica. Una nota en la cubierta dice que es para los "¡jóvenes electricistas en ciernes por todo el mundo!"}
{7700}{}{Ganzúa electrónica}
{7701}{}{Una ganzúa electrónica Micromanipulator FingerStuff de Wattz Electronics. Para librarse de cerraduras electrónicas y aparatos de seguridad.}
{7800}{}{Cuadro borroso}
{7801}{}{Una imagen de un cantante. Obviamente, muy antigua. La imagen tiene un tacto áspero y se mantiene en buenas condiciones.}
{7900}{}{Bengala}
{7901}{}{Una bengala. Crea luz durante un corto periodo de tiempo. El papel está un poco usado, pero por lo demás está en buenas condiciones. Gira la parte superior para activarla.}
{8000}{}{Libro de primeros auxilios}
{8001}{}{Un libro de estudio sobre los conceptos y la práctica de los primeros auxilios.}
{8100}{}{Pincho de iguana}
{8101}{}{Una iguana cocinada, asada en su propia piel.}
{8200}{}{Llave}
{8201}{}{Una llave. Una llave que abrirá una cerradura en particular.}
{8300}{}{Llavero}
{8301}{}{Múltiples llaves.}
{8400}{}{Ganzúas}
{8401}{}{Un juego de herramientas de cerrajero. Incluye todo lo necesario para abrir cerraduras.}
{8500}{}{Explosivo plástico}
{8501}{}{Un trozo de Cordex, una marca militar de explosivo plástico. Altamente inestable, y muy destructivo. Incluye un temporizador.}
{8600}{}{Manual del explorador}
{8601}{}{Un libro de ideales y consejos para exploradores. Contiene mucha información práctica respecto a la vida en el exterior.}
{8700}{}{Esteroides}
{8701}{}{Esteroides altamente avanzados. Mientras hacen efecto, incrementan la fuerza y los reflejos. Muy adictivos.}
{8800}{}{Reloj}
{8801}{}{Un reloj caro. En realidad no funciona, pero sigue pareciendo bonito.}
{8900}{}{Motor}
{8901}{}{Un motor eléctrico de 40CV.}
{9000}{}{Mochila}
{9001}{}{Una mochila sencilla, con correas opcionales.}
{9100}{}{Bolsa de doctor}
{9101}{}{Esta bolsa marrón contiene instrumentos y productos químicos que usan los médicos en el ejercicio de su profesión.}
{9200}{}{Cola de escorpión}
{9201}{}{La cola cortada de un escorpión rad.}
{9300}{}{Maleta}
{9301}{}{Una maleta de tamaño medio. Tejida con pelo de brahmin.}
{9400}{}{Escopeta}
{9401}{}{Una escopeta Winchester Widowmaker con dos cañones y calibre 12. De cañón corto, con asa en caoba. Min FU: 4.}
{9500}{}{Cartuchos de escopeta calibre 12}
{9501}{}{Munición de escopeta. Esta munición en particular indica que es: "munición calibre 12, prohibido su uso a menores de 3 años".}
{9600}{}{Pase rojo}
{9601}{}{Una llave electrónica de seguridad, codificada en color rojo.}
{9700}{}{Pase azul}
{9701}{}{Una llave electrónica de seguridad, codificada en color azul.}
{9800}{}{Basura}
{9801}{}{Un montón de basura. Hay un poco de todo.}
{9900}{}{Medallón dorado}
{9901}{}{Un valioso medallón de oro.}
{10000}{}{Radio}
{10001}{}{Modelo 2043B Radio Communicator, de la excelente marca Wattz Electronics. Fiable, resistente y de camuflaje. Con interfaz opcional RS-121.}
{10100}{}{Encendedor}
{10101}{}{Un encendedor plateado, en buenas condiciones.}
{10200}{}{Armas y Balas}
{10201}{}{Una revistucha de armas. Es una revista dedicada al uso de las armas de fuego, y con análisis poco imparciales.}
{10300}{}{Pincho de iguana}
{10301}{}{Algo de carne chamuscada y verduras cocinadas en un palo.}
{10400}{}{Cinta grabadora}
{10401}{}{Una cinta grabadora 'Reprodúcelo-Para-Mí' de Wattz Electronics. Reproduce y graba cintas estándar de alta densidad de una única grabación de 30 minutos.}
{10500}{}{Llave}
{10501}{}{Algún tipo de llave especial.}
{10600}{}{Nuka-Cola}
{10601}{}{Una botella de Nuka-Cola, la bebida más sabrosa del mundo post-nuclear. Está caliente e insípida.}
{10700}{}{Huesos}
{10701}{}{Una colección de extraños huesos.}
{10800}{}{Huesos}
{10801}{}{Una colección de extraños huesos.}
{10900}{}{Rad-X}
{10901}{}{Producto químico anti-radiación que debe tomarse antes de la exposición. No tiene efectos secundarios conocidos.}
{11000}{}{Psico}
{11001}{}{Un elemento especial lleno de extraños y desconocidos componentes químicos de probable origen militar. Se supone que incrementa el potencial de combate de un soldado.}
{11100}{}{.44 mágnum CM}
{11101}{}{Munición de calibre .44 para mágnum, con chaqueta metálica.}
{11200}{}{Urna}
{11201}{}{Un bonita urna dorada con el nombre "Harriet" inscrito en la parte frontal, que contiene cenizas.}
{11300}{}{Túnica}
{11301}{}{Túnica de los Niños de la Catedral.}
{11400}{}{Mano de Tangler}
{11401}{}{Un manipulador cibernético, con forma de mano. Dañada por la naturaleza descuidada del proceso de retirada.}
{11500}{}{Super almádena}
{11501}{}{Una super almádena, elaborada por la Hermandad del Acero, que usa la mejor tecnología armamentística disponible. Incluye un dispositivo que almacena energía cinética, para aumentar la pegada. Min FU: 5.}
{11600}{}{Destripador}
{11601}{}{Una hoja vibratoria Destripador(tm). Alimentada con células PE de energía, la hoja destripa y desgarra a su objetivo. Min FU: 4.}
{11700}{}{Flor}
{11701}{}{Una bonita flor.}
{11800}{}{Rifle láser}
{11801}{}{Un rifle láser Wattz 2000. Usa células MF de microfusión para un láser más potente, y un cañón extendido para mayor alcance. Min FU: 6.}
{11900}{}{Collar}
{11901}{}{Un collar de apariencia costosa, hecho de plata, oro y diamantes.}
{12000}{}{Pistola alienígena}
{12001}{}{Una extraña arma de origen obviamente alienígena. Sin embargo, parece que puede utilizar células PE de energía. Min FU: 2.}
{12100}{}{Balas de 9mm}
{12101}{}{Una colección de antiguas balas 9x19mm. Llevan un montón de grasa para protegerlas del entorno. Balas estándar.}
{12200}{}{Mauser de 9mm}
{12201}{}{Una Mauser M/96, 9x19mm Parabellum. En excelentes condiciones. Extremadamente precisa. Min ST: 3.}
{12300}{}{Anulador psíquico}
{12301}{}{Un extraño dispositivo, construido a partir de una extraña tecnología.}
{12400}{}{Cerveza}
{12401}{}{Algún tipo de cerveza casera.}
{12500}{}{Licor}
{12501}{}{Un licor de antes de la gran guerra.}
{12600}{}{Cantimplora}
{12601}{}{Un envase que mantiene y preserva el agua u otros líquidos.}
{12700}{}{Cuerda}
{12701}{}{Una cuerda fuerte y fina. De unos 45 pies de longitud.}
{12800}{}{Baúl}
{12801}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{12900}{}{Baúl}
{12901}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{13000}{}{Baúl}
{13001}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{13100}{}{Baúl}
{13101}{}{Baúl básico. Guarda las cosas, se coloca a los pies de la cama, puede cerrarse con llave.}
{13200}{}{Taquilla}
{13201}{}{Un recipiente de almacenamiento.}
{13300}{}{Taquilla}
{13301}{}{Un recipiente de almacenamiento.}
{13400}{}{Taquilla}
{13401}{}{Un recipiente de almacenamiento.}
{13500}{}{Taquilla}
{13501}{}{Un recipiente de almacenamiento.}
{13600}{}{Taquilla}
{13601}{}{Un recipiente de almacenamiento.}
{13700}{}{Taquilla}
{13701}{}{Un recipiente de almacenamiento.}
{13800}{}{Taquilla}
{13801}{}{Un recipiente de almacenamiento.}
{13900}{}{Taquilla}
{13901}{}{Un recipiente de almacenamiento.}
{14000}{}{Tarjeta de acceso}
{14001}{}{Una tarjeta de acceso de seguridad. Aún funcional.}
{14100}{}{Insignia}
{14101}{}{Una insignia con la forma del símbolo de los Niños de la Catedral. En un lado notas unas protuberancias y hendiduras que casi te recuerdan a una llave.}
{14200}{}{Insignia}
{14201}{}{Una insignia con la forma del símbolo de los Niños de la Catedral. En un lado notas unas protuberancias y hendiduras que casi te recuerdan a una llave.}
{14300}{}{Rifle francotirador}
{14301}{}{Un rifle francotirador DKS-501. Un excelente arma de largo alcance. Originalmente de calibre .308, pero se ha modificado a un calibre más común, el .223. Min FU: 5.}
{14400}{}{Superestimulante}
{14401}{}{Un avanzado producto químico curativo. Muy potente. Los superestimulantes producirán una pequeña cantidad de daño después de un periodo de tiempo, debido a la potencia de los productos químicos utilizados.}
{14500}{}{Estantería}
{14501}{}{Una estantería de madera.}
{14600}{}{Estantería}
{14601}{}{Una estantería de madera.}
{14700}{}{Estantería}
{14701}{}{Una estantería de madera.}
{14800}{}{Estantería}
{14801}{}{Una estantería de madera.}
{14900}{}{Estantería}
{14901}{}{Una estantería de madera.}
{15000}{}{Estantería}
{15001}{}{Una estantería de madera.}
{15100}{}{Estantes}
{15101}{}{Un grupo de estantes de madera.}
{15200}{}{Estantes}
{15201}{}{Un grupo de estantes de madera.}
{15300}{}{Estantes}
{15301}{}{Un grupo de estantes de madera.}
{15400}{}{Estantes}
{15401}{}{Un grupo de estantes de madera.}
{15500}{}{Estantes}
{15501}{}{Un grupo de estantes de madera.}
{15600}{}{Estantes}
{15601}{}{Un grupo de estantes de madera.}
{15700}{}{Mesa de trabajo}
{15701}{}{Una mesa de trabajo. Sí, la vieja y popular mesa de trabajo de toda la vida. Ahí puesta también tiene buena pinta.}
{15800}{}{Tablero de herramientas}
{15801}{}{Este tablero sobre la popular mesa de trabajo contiene una variedad de herramientas.}
{15900}{}{Cóctel Molotov}
{15901}{}{Una granada inflamable casera. Min FU: 3.}
{16000}{}{Picana}
{16001}{}{Una picana modelo 'La Mejor Amiga Del Granjero', de Wattz Electronics. Utiliza células PE de energía. Min FU: 4.}
{16100}{}{Escopeta Red Ryder BB}
{16101}{}{Una escopeta Red Ryder BB. La de toda la vida. Min FU: 3.}
{16200}{}{Escopeta Red Ryder LE BB}
{16201}{}{Una edición limitada de la escopeta Red Ryder BB. Un verdadero clásico. Min FU: 3.}
{16300}{}{Balines BB}
{16301}{}{Un paquete de balines BB de antes de la guerra. En excelentes condiciones. De acero inoxidable.}
{16400}{}{Holodisco de la Hermandad}
{16401}{}{Un holodisco de la Hermandad del Acero.}
{16500}{}{Puesto de Iguana}
{16501}{}{El hogar de los Bocaditos de Iguana de Bob. ¿Quién no adora las iguanas frescas asadas?}
{16600}{}{Mesa}
{16601}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{16700}{}{Mesa}
{16701}{}{Una mesa genérica. Mantiene a las cosas lejos del suelo.}
{16800}{}{Objetos}
{16801}{}{Diversos objetos, también conocidos como "cosas".}
{16900}{}{Objetos}
{16901}{}{Diversos objetos, también conocidos como "cosas".}
{17000}{}{Objetos}
{17001}{}{Diversos objetos, también conocidos como "cosas".}
{17100}{}{Objetos}
{17101}{}{Diversos objetos, también conocidos como "cosas".}
{17200}{}{Objetos}
{17201}{}{Diversos objetos, también conocidos como "cosas".}
{17300}{}{Objetos}
{17301}{}{Diversos objetos, también conocidos como "cosas".}
{17400}{}{Objetos}
{17401}{}{Diversos objetos, también conocidos como "cosas".}
{17500}{}{Objetos}
{17501}{}{Diversos objetos, también conocidos como "cosas".}
{17600}{}{Objetos}
{17601}{}{Diversos objetos, también conocidos como "cosas".}
{17700}{}{Objetos}
{17701}{}{Diversos objetos, también conocidos como "cosas".}
{17800}{}{Objetos}
{17801}{}{Diversos objetos, también conocidos como "cosas".}
{17900}{}{Objetos}
{17901}{}{Diversos objetos, también conocidos como "cosas".}
{18000}{}{Embalaje}
{18001}{}{Una caja de embalaje de madera con objetos genéricos.}
{18100}{}{Escritorio}
{18101}{}{Un escritorio genérico. Cuando has visto un escritorio, los has visto todos.}
{18200}{}{Escritorio}
{18201}{}{Un escritorio genérico.}
{18300}{}{Escritorio}
{18301}{}{Un escritorio genérico.}
{18400}{}{Escritorio}
{18401}{}{Un escritorio genérico.}
{18500}{}{Escritorio}
{18501}{}{Un escritorio genérico.}
{18600}{}{Escritorio}
{18601}{}{Un escritorio genérico.}
{18700}{}{Escritorio}
{18701}{}{Un escritorio genérico.}
{18800}{}{Taquilla}
{18801}{}{Una taquilla.}
{18900}{}{Taquilla}
{18901}{}{Una taquilla.}
{19000}{}{Disco sobre VEF}
{19001}{}{Un holodisco con información médica. Se puede usar para introducir información en tu PipBoy.}
{19100}{}{Disco de seguridad}
{19101}{}{Un holodisco etiquetado como "Registro de seguridad". Puedes usarlo para transferir los datos que contiene a tu PipBoy.}
{19200}{}{Disco del experimento Alfa}
{19201}{}{En la etiqueta de este holodisco pone: "Registro del experimento Alfa".}
{19300}{}{Disco del experimento Delta}
{19301}{}{En la etiqueta de este holodisco pone: "Registro del experimento Delta".}
{19400}{}{Disco del experimento de Vree}
{19401}{}{Este holodisco ha sido actualizado con datos médicos de Vree, de la Hermandad del Acero. Puedes usarlo para transferir los datos a tu PipBoy.}
{19500}{}{Código de Honor de la Hermandad}
{19501}{}{Un holodisco, con un basto símbolo de la Hermandad del Acero inscrito en él. Usa el disco para transferir los datos a tu PipBoy.}
{19600}{}{Transmisiones mutantes}
{19601}{}{Parece que este disco se configuró para grabar el sonido de una radio. Úsala para transferir los datos a tu PipBoy.}
{19700}{}{Caja}
{19800}{}{Caja}
{19900}{}{Caja}
{20000}{}{Caja}
{20100}{}{Caja}
{20200}{}{Caja}
{20300}{}{Caja}
{20400}{}{Caja}
{20500}{}{Bengala}
{20501}{}{Una bengala. Ofrece luz durante un corto periodo de tiempo. El papel está un poco usado, pero por lo demás está en buenas condiciones. Está encendida.}
{20600}{}{Dinamita}
{20601}{}{Un explosivo de alta potencia, elaborado al mezclar la nitroglicerina con una sustancia absorbente llamada kieselguhr. Incluye un temporizador, porque está haciendo tic-tac.}
{20700}{}{Contador Geiger}
{20701}{}{Un modelo C-Radz de contador Geiger de Wattz Electronics. Detecta la presencia y la intensidad de los campos radiactivos. Está encendido.}
{20800}{}{Sensor de movimiento}
{20801}{}{Un sensor de movimiento modelo C-U de Wattz Electronics. Detecta el movimiento de la materia biológica a varios metros de distancia usando un radar sintonizado. Está encendido.}
{20900}{}{Explosivo plástico}
{20901}{}{Un trozo de Cordex, una marca militar de explosivo plástico. Altamente inestable, y muy destructivo. Incluye un temporizador, porque está haciendo tic-tac.}
{21000}{}{Sigilante}
{21001}{}{Un dispositivo personal de sigilo Stealth Boy 3001, de RobCo. Genera un campo modulado que transmite la luz reflejada de la cara de un objeto sobre otra.}
{21100}{}{Huesos}
{21101}{}{Ves a Ed. Y Ed está muerto.}
{21200}{}{Tandi}
{21201}{}{Estás negociando la liberación de Tandi.}
{21300}{}{Restos de Gizmo}
{21301}{}{Gizmo, antiguo jefe criminal de Ciudad Vertedero, está muerto. Y además apesta lo suyo.}
{21400}{}{Escritorio}
{21401}{}{Un escritorio. Tras observarlo detenidamente, decides que sigue siendo un escritorio.}
{21500}{}{Historia de la Hermandad}
{21501}{}{Un holodisco que contiene información relativa a la Hermandad del Acero. Puede usarse para introducir información en tu PipBoy 2000.}
{21600}{}{Historia de Maxson}
{21700}{}{Diario de Maxson}
{21800}{}{Curación ligera}
{21801}{}{Comercia con esta opción si quieres una curación ligera.}
{21900}{}{Curación media}
{21901}{}{Comercia con esta opción si quieres una curación media.}
{22000}{}{Curación intensa}
{22001}{}{Comercia con esta opción si quieres muchos cuidados y una curación intensa.}
{22100}{}{Tarjeta de seguridad}
{22101}{}{Una tarjeta con un nivel de seguridad codificado con electrónica muy básica.}
{22200}{}{Interruptor}
{22201}{}{Un dispositivo electrónico de transmisión, con un simple y gran interruptor. Parece que se creó recientemente y se diseñó para manos muy grandes.}
{22300}{}{Pase amarillo}
{22301}{}{Una tarjeta electrónica de seguridad, codificada en color amarillo.}
{22400}{}{Figurilla}
{22401}{}{Crees que pueda ser una escultura de "Pip Boy", pero no puedes asegurarlo.}
{22500}{}{Revista 'La Garra de la Gata'}
{22501}{}{Un número de la revista 'La Garra de la Gata'.}
{22600}{}{Caja de fideos}
{22601}{}{No tienes ni idea de lo que significa "Espaguettis instantáneos".}
{22700}{}{Pequeña caja polvorienta de algo}
{22701}{}{No estás seguro, pero seguramente no es comestible. No estás totalmente seguro de si alguna vez lo fue.}
{22800}{}{Manual técnico}
{22801}{}{Un manual de reparaciones técnicas de la servoarmadura T-51b.}
{22900}{}{Pequeña pieza de maquinaria}
{22901}{}{Una pieza dañada de servoarmadura. Es muy limpia y podría ser un trofeo de algún tipo.}
{23000}{}{Registros del Refugio}
{23001}{}{Un compendio de eventos e importantes grabaciones de una computadora de Refugio. Posiblemente dañado.}
{23100}{}{Código de seguridad de la base militar}
{23101}{}{}
{23200}{}{Servoarmadura mejorada}
{23201}{}{Una servoarmadura T-51b. El proceso de mejora ha aumentado la capacidad defensiva de esta armadura de alta tecnología.}
{23300}{}{Turbo rifle de plasma}
{23301}{}{Un rifle de plasma modificado Winchester P94. La cámara de plasma ha sido puenteada para acelerar el proceso de formación del rayo. Min FU: 6.}
{23400}{}{Nudillera con pinchos}
{23401}{}{Una versión mejorada de las clásicas nudilleras. Los nudillos con pinchos hacen más daño, rasgando la carne de tu oponente en un combate desarmado. Min FU: 1.}
{23500}{}{Servopuño}
{23501}{}{Un servopuño "Acojonador" de BeatCo. Considerado por muchos la arma definitiva en combate desarmado. Otros se limitan a asustarse. Alimentado por células PE de energía. Min FU: 1.}
{23600}{}{Cuchillo de combate}
{23601}{}{Un cuchillo de combate de alta calidad de SharpWit Inc. ¡Se garantiza el afilado de la hoja a lo largo de diez años de uso! Min FU: 2.}
{23700}{}{Revistas de química}
{23701}{}{Un montón de literatura relativa al campo de la química. Las revistas de química molecular son particularmente interesantes.}
{23800}{}{Transmisión de Regulador}
{23801}{}{Un holodisco con la grabación de una transmisión sonora.}
{23900}{}{Armadura de la Hermandad}
{23901}{}{Una versión mejorada de la armadura de combate. La Hermandad del Acero ha hecho muchas mejoras sobre la versión estándar.}
{24000}{}{Armadura Tesla}
{24001}{}{Esta brillante armadura proporciona una protección superior contra los ataques de energía. Las tres bobinas Tesla de atracción dispersan un gran porcentaje de la energía recibida en un ataque.}
{24100}{}{Pistola .223}
{24101}{}{Un rifle calibre .223 modificado y acortado como pistola. Se trata de un arma única, obviamente realizada con cariño y habilidad. Min FU: 5.}
{24200}{}{Escopeta de combate}
{24201}{}{Una escopeta de combate Winchester City-Killer de calibre 12. En excelentes condiciones, tiene un sellador ambiental opcional DesertWarfare para una mayor fiabilidad. Min FU: 5.}
{24300}{}{Olla}
{24301}{}{Una olla artesanal.}
{24400}{}{Olla}
{24401}{}{Una olla artesanal.}
{24500}{}{Cofre}
{24501}{}{Un cofre de madera.}
{24600}{}{Estante}
{24601}{}{Un estante de madera con varios objetos.}
{24700}{}{Estante}
{24701}{}{Un estante de madera con varios objetos.}
{24800}{}{Olla}
{24801}{}{Una olla artesanal.}
{24900}{}{Olla}
{24901}{}{Una olla artesanal.}
{25000}{}{Huesos}
{25001}{}{Un montón de huesos humanos.}
{25100}{}{Huesos de Anna}
{25101}{}{Estos huesos parecen inestables.}
{25200}{}{Medallón de oro de Anna}
{25201}{}{Este medallón de oro se abre para revelar un encantador retrato.}
{25300}{}{Inyector de combustible}
{25301}{}{Este chip controla el flujo de energía que entra en el motor eléctrico del vehículo. Muchos conductores queman este chip debido a acelerones frecuentes. Sigue siendo una pieza valiosa... sólo si tienes un vehículo en el que instalarla.}
{25400}{}{Regulador de combustible}
{25401}{}{Algunos propietarios de vehículos instalan este regulador, que dobla el kilometraje entre cargas, pero muchos conductores no se preocupan del combustible que consumen: después de todo, la energía es barata y abundante, así que ¿por que preocuparte?}
{25500}{}{Pase de día}
{25501}{}{Este papel ligeramente arrugado garantiza tu acceso a todos los lugares de Ciudad Refugio, excepto al propio Refugio, sólo durante las horas del día.}
{25600}{}{Documentos de Ciudadanía falsos}
{25601}{}{Unos documentos de Ciudadanía falsos. Parecen lo bastante auténticos, pero dudas que pudieran pasar una inspección seria.}
{25700}{}{Reloj de oro de Cornelius}
{25701}{}{Un antiguo elemento de medida del tiempo llamada reloj de bolsillo. Y hace tiempo que el ídem se acabó para este objeto de recuerdo.}
{25800}{}{Objeto hidroeléctrico}
{25801}{}{Un regulador hidroeléctrico magnetosférico.}
{25900}{}{Jet}
{25901}{}{El Jet es una poderosa metanfetamina que estimula el sistema nervioso central. El subidón inicial de euforia rara vez dura más que unos pocos minutos, pero durante ese tiempo, el usuario nota gran energía y fuerza.}
{26000}{}{Antídoto para el Jet}
{26001}{}{Este antídoto cura los efectos de la adicción al Jet.}
{26100}{}{Escopeta BB de Jonny}
{26101}{}{Una escopeta Red Ryder BB con el nombre 'Jonny' grabado en la culata. Min FU: 3.}
{26200}{}{Botas de caucho}
{26201}{}{Un viejo par de botas de caucho. Parecen lo bastante duraderas como para librarte de los residuos, al menos durante un tiempo.}
{26300}{}{Mensaje de los Escorias}
{26301}{}{Esto es un mensaje del líder de los Escorias para los ciudadanos de Modoc.}
{26400}{}{Objeto guay de Smith}
{26401}{}{LARGA DESCRIPCION AQUI.}
{26500}{}{Chaqueta de cuero de combate}
{26501}{}{Esta chaqueta de cuero reforzada es inusual, ya que tiene dos mangas. Sin duda harás un pase de moda cuando y donde quieras, y arrasarás.}
{26600}{}{Radio de Vic}
{26601}{}{Esta radio de mano parece que no funciona, pero aún está en buenas condiciones. Algunas de sus piezas probablemente podrían servir para otras radios.}
{26700}{}{Cantimplora de Vic}
{26701}{}{Esta reliquia del Refugio probablemente se usó para contener algún sacramento sagrado. El Sagrado 13 adorna una cara de este precioso frasco, un vínculo entre tus antepasados y el esperanzador futuro.}
{26800}{}{H&K SAAC}
{26801}{}{La SAAC, abreviatura de Sistema de Arma de Asalto Cercano, es una escopeta útil para combates de corto alcance. El diseño del arma le aporta un manejo sencillo a poca distancia, aunque tiene unos cañones lo bastante largos como para disparar a alta velocidad. Min FU: 6.}
{26900}{}{Piezas de un robot}
{26901}{}{Un montón de piezas de robot dañadas.}
{27000}{}{Lanzacohetes de robot}
{27001}{}{Sólo lo usan los robots equipados con cohetes.}
{27100}{}{Flor de broquia}
{27101}{}{La abundante flor que es la base de los polvos curativos.}
{27200}{}{Raíz de xandria}
{27201}{}{La rara raíz que le da las propiedades de curación a los polvos curativos.}
{27300}{}{Polvos curativos}
{27301}{}{Una potente curación mágica... aunque te provocará sensación de sueño.}
{27400}{}{Cohetes para robots}
{27401}{}{Sólo lo usan los robots equipados con cohetes.}
{27500}{}{Trofeo de reconocimiento}
{27501}{}{Un sólido trofeo de oro con la inscripción "A: Dave, De: DC, Por: Ser una persona especial."}
{27600}{}{Piel de gecko}
{27601}{}{La seca y curada piel de un gecko.}
{27700}{}{Piel de gecko dorado}
{27701}{}{La seca y curada piel de un gecko dorado.}
{27800}{}{Pedernal}
{27801}{}{Una piedra que se usa para afilar armas.}
{27900}{}{Interfaz neural}
{27901}{}{Parece ser un juego de electrodos integrados en un casco con un enchufe de interfaz estándar para computadoras. Está roto, sin embargo.}
{28000}{}{Lanza afilada}
{28001}{}{Un palo con una cuchilla en la punta. El palo es de madera, y la punta es de acero afilado. Min FU: 4.}
{28100}{}{Ojo de Dixon}
{28101}{}{Un pequeño frasco que contiene un ojo humano suspendido en algún tipo de líquido. En la etiqueta pone: cabo Dixon.}
{28200}{}{Ojo de Clifton}
{28201}{}{Un pequeño frasco que contiene un ojo humano suspendido en algún tipo de líquido. En la etiqueta pone: general Clifton.}
{28300}{}{Ametralladora}
{28301}{}{Esta ametralladora Thompson M1928 es un arma de apariencia siniestra; cada vez que la amartillas, sientes ganas de ponerte un sombrero fedora y hacer crujir tus nudillos. La Thompson tiene un gran cargador para 50 balas. Min FU: 6.}
{28400}{}{Cecina}
{28401}{}{Esta carne de bestia ahumada y seca se mantiene masticable y parcialmente nutritiva durante años, y años, y años....}
{28500}{}{Extremidad de escorpión rad}
{28501}{}{Estas pinzas de escorpión rad están vaciadas y tienen una correa con una hebilla rota al final.}
{28600}{}{Leña}
{28601}{}{Un montón de leña.}
{28700}{}{Rifle de caza con mira}
{28701}{}{Nada mejor que ver una mirada de sorpresa en el rostro de tu objetivo: la mira x20 de este rifle de caza lo hace más fácil que nunca. Precisa desde el primer al último tiro, sin que importe a lo que le estés disparando. Min FU: 5.}
{28800}{}{Combustible de coche}
{28801}{}{Combustible para un vehículo.}
{28900}{}{Pala}
{28901}{}{Es una pala es para excavar zanjas y otras cosas.}
{29000}{}{Arma de robot 1}
{29001}{}{Para robots. Produce daño eléctrico.}
{29100}{}{Arma de robot 2}
{29101}{}{Para robots. Produce daño eléctrico.}
{29200}{}{Guantes de boxeo}
{29201}{}{Un par de guantes de boxeo que apenas huelen a sudor. Parece que se han usado mucho: aún tienen muchas viejas manchas de sangre.}
{29300}{}{Guantes de boxeo trucados}
{29301}{}{Alguien ha dejado caer "accidentalmente" placas de metal en estos guantes de boxeo. Técnicamente se podría considerar hacer trampas, pero tú prefieres pensar que es una mejor oportunidad para romper huesos.}
{29400}{}{Holodisco del Refugio 13}
{29401}{}{Un holodisco que supuestamente contiene la localización del Refugio 13.}
{29500}{}{Bolitas de queso}
{29501}{}{Un paquete de bolitas con sabor a queso. Están extremadamente buenas.}
{29600}{}{H&K P90c}
{29601}{}{La Heckler & Koch P90c empezó a usarse al comenzar la guerra. El diseño tipo novillo del arma, y su diseño compacto, la hacen fácil de controlar. La duradera P90c es apreciada por su confiabilidad y su alta potencia de fuego, con una dura carcasa compacta. Min FU: 4.}
{29700}{}{Barra de metal}
{29701}{}{Es una larga barra de metal. ¿Qué esperabas?}
{29800}{}{Llave del barrio de los tramperos}
{29801}{}{Una llave estándar.}
{29900}{}{Rifle de tubo}
{29901}{}{Se trata de un rifle hecho a mano, de un solo disparo. Min FU: 5.}
{30000}{}{Pistola desmontable}
{30001}{}{Una pistola hecha a mano, de un solo disparo. Min FU: 4.}
{30100}{}{Portapapeles}
{30101}{}{Un portapapeles con el informe del sistema de refrigeración.}
{30200}{}{Holodisco de Gecko}
{30201}{}{En la etiqueta de este holodisco pone: "Datos económicos de Gecko". Es difícil interpretar la mayoría de las gráficas técnicas, las tablas, y las fórmulas que contiene, pero la mayor parte de la información parece destacar las ventajas de una alianza Ciudad Refugio-Gecko.}
{30300}{}{Holodisco del reactor}
{30301}{}{En la etiqueta de este holodisco pone: "Datos de rendimiento del reactor de Gecko". Este disco contiene una serie de números que no significan nada para ti. De todas formas, estás seguro de que mucha de la información que contiene es importante para alguien.}
{30400}{}{Baraja de cartas "Tragic"}
{30401}{}{Una baraja de un juego de cartas coleccionables. Parece que podría ser un pasatiempo caro si te enganchases a él.}
{30500}{}{Pase amarillo del reactor}
{30501}{}{Una tarjeta electrónica de seguridad, codificada en color amarillo.}
{30600}{}{Pase rojo del reactor}
{30601}{}{Una tarjeta de seguridad, codificada en color rojo.}
{30700}{}{Transformador de plasma}
{30701}{}{Esto es un transformador trifásico de plasma.}
{30800}{}{Super-set de herramientas}
{30801}{}{Una impresionante colección de herramientas fabricadas por la marca 'Snap-Off'.}
{30900}{}{Talismán}
{30901}{}{Un talismán usado por los seguidores de El Cerebro.}
{31000}{}{Cerveza radiactiva}
{31001}{}{Una botella de cerveza radiactiva. ¡Brilla en la oscuridad!}
{31100}{}{Ron Roetgen}
{31101}{}{Una botella de ron Roetgen. ¡Brilla en la oscuridad!}
{31200}{}{Formulario de solicitud de piezas}
{31201}{}{Esto es un formulario de solicitud de piezas.}
{31300}{}{Revólver mágnum .44}
{31301}{}{Siendo éste el mejor revólver del mundo, capaz de volarte los sesos de un tiro, ¿no crees que debieras pensar que eres afortunado? ¿Verdad que sí, vago? Min FU: 5.}
{31400}{}{Preservativo (paquete azul)}
{31401}{}{Un preservativo de Sombreros Jimmy, una marca de mucha confianza. Éste está estriado para el placer de ella.}
{31500}{}{Preservativo (paquete verde)}
{31501}{}{Un preservativo de Sombreros Jimmy, una marca de mucha confianza. Éste contiene tinte de fósforo verde #2 y está recubierto de lubricante espermicida para una protección añadida.}
{31600}{}{Preservativo (paquete rojo)}
{31601}{}{Un preservativo de Sombreros Jimmy, una marca de mucha confianza. Éste contiene tinte de fósforo rojo #5 y tiene un sabor a magdalena de canela para chuparse los dedos... o eso has oído.}
{31700}{}{Estuche cosmético}
{31701}{}{Un genuino estuche de cosmética de la marca Mary May.}
{31800}{}{Jeringuilla vacía}
{31801}{}{Una jeringuilla vacía.}
{31900}{}{Navaja de muelle}
{31901}{}{La hoja de este pequeña navaja funciona a resorte. Cuando se presiona un botón del mango, la hoja salta con un satisfactorio "Sssssshk". Min FU: 1.}
{32000}{}{Barrote afilado}
{32001}{}{Un barrote de madera con la punta afilada. Min FU: 4.}
{32100}{}{Cerebro cibernético}
{32101}{}{Un cerebro humano que ha sido mejorado con accesorios electrónicos y robóticos.}
{32200}{}{Cerebro humano}
{32201}{}{Un cerebro humano normal. Normalmente se encuentran en calaveras humanas. ¡Puaj!}
{32300}{}{Cerebro de chimpancé}
{32301}{}{Un cerebro de chimpancé. Es blando y escurridizo.}
{32400}{}{Cerebro anormal}
{32401}{}{Muy posiblemente un cerebro humano. El color no parece estar del todo bien, y el hemisferio izquierdo tiene un agujero.}
{32500}{}{Dados}
{32501}{}{Un par de dados de juego normales. Sería genial llevar un par de ellos en tu coche.}
{32600}{}{Dados cargados}
{32601}{}{Un par de dados cargados. No los vayas enseñando por el casino.}
{32700}{}{Huevo de Pascua}
{32701}{}{Esto es un duro huevo de gallina pintado con tinta de colores.}
{32800}{}{Bola-8 mágica}
{32801}{}{Esta esfera negra es un extraño artilugio de predicción... ¡una pequeña ventana en la parte superior parece capaz de predecir el futuro! ¡La humanidad de antes de la guerra debe haber estado poblada de genios para inventar semejante maravilla!}
{32900}{}{Suero mutagénico}
{32901}{}{Un extraño brebaje orgánico que posiblemente podría revertir el factor de mutación en seres humanos.}
{33000}{}{Vertibird estrellado}
{33001}{}{La cabina de un vertibird. Parece que se estrelló aquí hace meses.}
{33100}{}{La Garra de la Gata número #5}
{33101}{}{Este es el sumamente difícil de encontrar número 5 de la revista 'La Garra de la Gata'. Dejando a un lado las fotografías, este número contiene un maravilloso artículo sobre armas de energía.}
{33200}{}{SMG M3A1 "Ametralladora Grasienta"}
{33201}{}{Esta ametralladora llenó los arsenales de la Guardia Nacional después de que el Ejército la reemplazara por armas más modernas. Sin embargo, la "Ametralladora Grasienta" era sencilla y barata de fabricar, por lo que aún hay bastantes en uso. Min FU: 4.}
{33300}{}{Píldoras para el corazón}
{33301}{}{Estas píldoras las usan las personas con problemas de corazón.}
{33400}{}{Veneno}
{33401}{}{Una jeringuilla llena de un potente veneno.}
{33500}{}{Maletín de Moore}
{33501}{}{Thomas Moore te pidió que llevases este maletín de piel de brahmin a la Familia Bishop en Nuevo Reno. Tiene una cerradura de seguridad, y parece que no puedes abrirlo.}
{33600}{}{Maletín de Moore}
{33601}{}{Thomas Moore te pidió que llevases este maletín de piel de brahmin a la Familia Bishop en Nuevo Reno. Tiene una cerradura de seguridad, y parece que no puedes abrirlo.}
{33700}{}{Holodisco de Lynette}
{33701}{}{Este es el holodisco que te dio Lynette.}
{33800}{}{Holodisco de Westin}
{33801}{}{Este es el holodisco que te dio Westin.}
{33900}{}{Holodisco del espía en la RNC}
{33901}{}{Este holodisco contiene informes de programas de las caravanas de RNC e información de seguridad. Está dirigido a Darion y firmado como "F". Con esta información, es sencillo entender cómo han evitado los Saqueadores ser capturados.}
{34000}{}{Documentos del doctor}
{34001}{}{Un juego de planos muy detallados de una Unidad Canina Cibernética de Guardia. Con ellos y la habilidad adecuada, una persona puede ser capaz de construir un perro-robot.}
{34100}{}{Pase Presidencial}
{34101}{}{El portador de este documento dispone de un pase de seguridad clase-A conforme a lo autorizado por la Presidencia de la República de Nueva California. Está firmado por la Presidente Tandi.}
{34200}{}{Insignia de Ranger}
{34201}{}{Esta insignia indica que eres un Ranger de de Nueva California. Fíjate: ¡tiene una rueda de códigos y todo!}
{34300}{}{Mapa de los Rangers}
{34301}{}{Un mapa de los alrededores (no te servirá de mucho): tiene nombres en código para los pisos francos de los Rangers en el norte.}
{34400}{}{Cementerio}
{34500}{}{Cementerio}
{34600}{}{Cementerio}
{34700}{}{Cementerio}
{34800}{}{Servoarmadura avanzada}
{34801}{}{Esta servoarmadura está compuesta por una aleación de metales ligeros, reforzada con piezas de fundición de cerámica en los puntos clave. Los servomotores de ayuda al movimiento también parecen ser modelos de alta calidad.}
{34900}{}{Servoarmadura avanzada MKII}
{34901}{}{Esta servoarmadura parece estar completamente realizada con compuestos ligeros de cerámica, en lugar de por la combinación habitual de placas metálicas y cerámicas. Parece que aporta más protección que la servoarmadura avanzada estándar.}
{35000}{}{Bozar}
{35001}{}{El perfeccionamiento definitivo del arte del francotirador. Aunque un poco quisquilloso y propenso a atascarse si no se mantiene escrupulosamente limpio, la gran precisión de este rifle compensa más que de sobra sus requerimientos adicionales de mantenimiento. Min FU: 6.}
{35100}{}{FN FAL}
{35101}{}{Este rifle ha sido más ampliamente utilizado por las fuerzas armadas que cualquier otro fusil en la historia. Es un arma de asalto fiable para cualquier terreno o situación táctica. Min FU: 5.}
{35200}{}{H&K G11}
{35201}{}{Este arma revolucionó el diseño de las armas de asalto. Dispara cartuchos sin carcasa formados por un bloque de propelente con una bala en su interior. El ahorro de peso y espacio resultantes le permite una muy alta capacidad de cargador. Min FU: 5.}
{35300}{}{XL70E3}
{35301}{}{Fue un arma experimental durante la gran guerra. Fabricada principalmente con resistentes polímeros, el arma es casi indestructible. Es ligera, dispara rápidamente, es precisa, y se puede desarmar sin usar herramientas. Min FU: 5.}
{35400}{}{Taladradora Pancor}
{35401}{}{La Taladradora, a pesar de su nombre, es una escopeta fácil de controlar, incluso en modo de disparo automático. El diseño tipo novillo, que sitúa el cargador tras el gatillo, hace que el arma esté equilibrada y sea fácil controlarla. Min FU: 5.}
{35500}{}{Arma ligera de apoyo}
{35501}{}{Este arma de apoyo para escuadras tiene un diseño tipo novillo que dificulta su uso estando acostado. Por ello, se retiraron de las unidades de la Guardia Nacional. Sin embargo, se ganó una reputación como arma confiable con buena potencia para su tamaño. Min FU: 6.}
{35600}{}{Módulo de voz para computadora}
{35601}{}{Una placa de circuitos con varias partes no identificables, un micrófono, y una inscripción en la que pone "módulo de reconocimiento de voz Vault-Tec".}
{35700}{}{Calibre .45}
{35701}{}{Munición calibre .45.}
{35800}{}{2mm EC}
{35801}{}{Munición.}
{35900}{}{4.7mm sin carcasa}
{35901}{}{Munición calibre: 4.7mm, SC.}
{36000}{}{9mm}
{36001}{}{Munición calibre: 9mm.}
{36100}{}{Cartucho de agujas HN}
{36101}{}{Munición. Este cartucho parece ser munición para la pistola de agujas HN. Cada 'bala' es una pequeña jeringuilla diseñada para inyectar su contenido en un objetivo cuando impacta.}
{36200}{}{Cartucho de agujas HN AP}
{36201}{}{Munición. Este cartucho parece ser munición atravesadora de blindaje para la pistola de agujas HN. Las puntas de las jeringuillas están hecha de una extraña aleación y son increíblemente afiladas.}
{36300}{}{7.62mm}
{36301}{}{Munición calibre: 7.62mm.}
{36400}{}{Unidad motriz de robot}
{36401}{}{Es el mecanismo de movimiento de un robot.}
{36500}{}{Pincho de planta}
{36501}{}{Una semilla-pincho orgánica que las plantas carnívoras escupen sobre portadores potenciales de alimentos o semillas.}
{36600}{}{G.E.C.K.}
{36601}{}{El Kit de Creación del Jardín del Edén. Esta unidad es un equipamiento estándar para todos los Refugios de Vault-Tec. Un GECK es una fuente de reconstrucción de la civilización tras las bombas. Tan solo añadir agua y agitar.}
{36700}{}{Caja de munición}
{36800}{}{Caja de munición}
{36900}{}{Caja de munición}
{37000}{}{Caja de munición}
{37100}{}{Garra}
{37101}{}{Garra}
{37200}{}{Garra}
{37201}{}{Garra}
{37300}{}{Tarjeta del Refugio 15}
{37301}{}{Una tarjeta de seguridad, codificada en color rojo.}
{37400}{}{Cementerio}
{37500}{}{Cementerio}
{37600}{}{Cementerio}
{37700}{}{Piezas de computadora del Refugio 15}
{37701}{}{Diversas piezas de computadora con varias funciones. El sueño de un fanático de las computadoras.}
{37800}{}{Galleta}
{37801}{}{Una galleta con trocitos de chocolate. ¡Mmm!}
{37900}{}{Armadura de cuero Mark II}
{37901}{}{Una versión mejorada de la armadura básica de cuero, con capas extra de protección. Elaborada artesanalmente con piel curtida de brahmin.}
{38000}{}{Armadura de metal Mark II}
{38001}{}{Placas de metal pulidas, pegadas artesanalmente en una armadura.}
{38100}{}{Armadura de combate Mark II}
{38101}{}{Armadura de alta tecnología, elaborada con polímeros defensivos avanzados.}
{38200}{}{Combustible de lanzallamas MKII}
{38201}{}{Este combustible para lanzallamas usa una mezcla avanzada de super-quemado.}
{38300}{}{Pincho}
{38301}{}{Este cuchillo casero es tan peligroso como fácil de ocultar. Los demás no pueden detectar su presencia. Min FU: 1.}
{38400}{}{Llave inglesa}
{38401}{}{Una típica llave inglesa usada por mecánicos. Min FU: 3.}
{38500}{}{Escopeta recortada}
{38501}{}{Alguien se tomó su tiempo para cortar las últimas pulgadas del cañón de esta escopeta. Ahora, la alta propagación del disparo la hacen perfecta para el control de multitudes a corta distancia. Min FU: 4.}
{38600}{}{Bate de Louisville}
{38601}{}{Un bate de béisbol de madera maciza, americano de pura cepa, que tumbará a cualquiera que se interponga en tu camino. Min FU: 4.}
{38700}{}{M60}
{38701}{}{Esta ametralladora relativamente ligera era muy apreciada por los militares de todo el mundo por su alto ratio de disparo. Este arma confiable y de diseño probado en el campo de batalla, se usó en vehículos para apoyo de fuego a escuadrillas. Min FU: 7.}
{38800}{}{Pistola de agujas}
{38801}{}{Sospechas que esta pistola de agujas Bringham fue utilizada en su momento en estudios científicos de campo. Usa pequeñas jeringuillas de plástico endurecido como munición. Min FU: 3.}
{38900}{}{Minicañón Vengador}
{38901}{}{Rockwell diseñó el Vengador para reemplazar su viejo minicañón personal CZ53. Las mejoras de diseño del Vengador incluyen aletas refrigeradas por gel y orificios de cañón metalizados en cromo. Esto aumenta su alcance y letalidad. Min FU: 7.}
{39000}{}{Abrasador solar}
{39001}{}{Sin los rayos del sol cargando los condensadores de este arma, resulta inútil. Sin embargo, a plena luz del día, las células fotoeléctricas experimentales que alimentan el Abrasador permite convertir casi todo en un bicho achicharrado. Min FU: 3.}
{39100}{}{H&K G11E}
{39101}{}{Este arma revolucionó el diseño del armamento de apoyo a escuadrillas. Dispara cartuchos sin carcasa formados por un bloque de propelente con una bala en su interior. El ahorro de peso y espacio resultantes le permite una muy alta capacidad de cargador. Min FU: 6.}
{39200}{}{Rifle M72 Gauss}
{39201}{}{El M72 tiene diseño alemán. Usa un campo electromagnético para propulsar balas a una tremenda velocidad... y penetran en casi cualquier obstáculo. Su largo alcance, precisión y potencia de disparo resulta casi imparable. Min FU: 6.}
{39300}{}{Fáser}
{39301}{}{Este misterioso arma de alta tecnología parece tener algún tipo de generador de energía dentro. Si no había dañado, este arma podría ser el arma definitivo contra cualquier enemigo. El módulo de energía reservo consta de células PE de energía sustituibles. Min FU: 3.}
{39400}{}{Pistola Gauss PPK12}
{39401}{}{Alabada por su alcance y su poder imparable, la pistola Gauss PPK12 tiene diseño alemán. Utiliza un campo electromagnético para propulsar balas a una tremenda velocidad y perfora casi cualquier tipo de armadura. Min FU: 4.}
{39500}{}{Minicañón Reivindicador}
{39501}{}{La compañía alemana Rheinmetal AG creó el minicañón definitivo. El Reivindicador dispara unas 90.000 balas sin carcasa por minuto, a través de sus seis cañones de carbono polimérico. Cima de la ingeniería alemana, es el arma grande definitiva. Min FU: 7.}
{39600}{}{Pistola de pulsos YK32}
{39601}{}{La YK32 es un arma de pulsos eléctricos desarrollada por el consorcio Yuma Flats Energy. Aunque potente, la YK32 nunca fue considerada un arma práctica debido la poca eficiencia de su uso energético y su abultado diseño. Min FU: 3.}
{39700}{}{Rifle de pulsos YK42B}
{39701}{}{La YK42B es un arma de pulsos eléctricos desarrollada por el consorcio Yuma Flats Energy. Se considera un arma superior a la pistola YK32, ya que tiene una mayor capacidad de carga y alcance. Min FU: 3.}
{39800}{}{Mágnum .44 (cargador rápido)}
{39801}{}{Un revólver mágnum .44 con un cargador rápido. Min FU: 5.}
{39900}{}{Super picana}
{39901}{}{Una picana modelo 'La Mejor Amiga Del Granjero', de Wattz Electronics. Este modelo se ha actualizado para incrementar su descarga eléctrica. Min FU: 4.}
{40000}{}{Lanzallamas mejorado}
{40001}{}{Un lanzallamas modelo Flambe 450, variante 'varmiter'. Dispara un chorro corto de líquido inflamable extremadamente caliente. Requiere un combustible especial para que funcione correctamente. Este modelo ha sido modificado para disparar una mezcla más caliente que provoca una mayor combustión. Min FU: 6.}
{40100}{}{Rifle láser (capacidad extra)}
{40101}{}{A este rifle láser Wattz 2000 se le mejoró el sistema de recarga y se le instaló un chip de reciclaje especial que reduce el gasto de las células MF de microfusión en un 50%. Min FU: 6.}
{40200}{}{Pistola magnetoláser}
{40201}{}{Esta pistola láser Wattz 1000 ha sido mejorada con un sistema de objetivado de campo magnético que afina la emisión láser, proporcionando al arma una mayor potencia de penetración. Min FU: 3.}
{40300}{}{FN FAL (visión nocturna)}
{40301}{}{Este rifle ha sido más ampliamente utilizado por las fuerzas armadas que cualquier fusil en la historia. Es un arma de asalto fiable para cualquier terreno o situación táctica. Esta variante ha sido equipada con un mira nocturna para una mayor precisión por la noche. Min FU: 5.}
{40400}{}{Desert Eagle (capacidad extra)}
{40401}{}{Una antigua pistola Desert Eagle, mágnum .44. Su participación en películas de finales del siglo XX la convirtió en una de las pistolas más populares de todos los tiempos. ¡Esta variante está equipada con un cargador expandido para una diversión mayor! Min FU: 4.}
{40500}{}{Rifle de asalto (capacidad extra)}
{40501}{}{Este rifle de asalto tiene un cargador de munición expandido, a tamaño militar, haciendo más divertido que nunca el pegar tiros sin pensar. Min FU: 5.}
{40600}{}{Pistola de plasma (capacidad extra)}
{40601}{}{Esta pistola de plasma Glock 86 tiene una cámara magnética reajustada para reducir el consumo de sus células de energía. Su eficiencia se ha duplicado, lo que le permite disparar más veces antes de que se gaste la batería. Min ST: 4.}
{40700}{}{Servopuño Megapotente}
{40701}{}{Un servopuño "Acojonador" de BeatCo. Considerado por muchos la arma definitiva en combate desarmado. Esta versión ha mejorado su potencia para incrementar la fuerza. Alimentado por células PE de energía. Min FU: 1.}
{40800}{}{Kit de primeros auxilios de campo}
{40801}{}{Un pequeño kit que contiene equipamiento médico básico. Vendas, gasas, spray antiséptico, y más.}
{40900}{}{Mochila de paramédico}
{40901}{}{Esta mochila contiene instrumentos y sustancias químicas usadas por paramédicos en el campo de batalla. Las herramientas que contiene están específicamente diseñadas para traumas grandes y casos de emergencia.}
{41000}{}{Set de ganzúas expandido}
{41001}{}{Un juego de herramientas de cerrajero. Incluye todo lo necesario para abrir cerraduras. Este juego también incluye herramientas especiales para desbloquear los mecanismos más difíciles.}
{41100}{}{Ganzúa electrónica MKII}
{41101}{}{Segunda generación de la ganzúa electrónica Micromanipulator FingerStuff de Wattz Electronics. Para librarse de cerraduras electrónicas y aparatos de seguridad. Esta versión Mark II incluye software actualizado y herramientas de interfaz.}
{41200}{}{Bidón de aceite}
{41201}{}{Ves una bidón de Armor-Go. Contiene lubricante polimérico de la era espacial para servoarmaduras.}
{41300}{}{Pase del Establo}
{41301}{}{Un pase de identificación temporal. Tiene una franja roja que lo cruza, en la que indica que eres un "Investigador del Establo".}
{41400}{}{Llave de la choza del Refugio 15}
{41401}{}{Una llave estándar.}
{41500}{}{Gafas}
{41501}{}{Unas gafas para la corrección visual.}
{41600}{}{Botella vacía de Jet}
{41601}{}{Esta botella vacía de Jet se encontró en la habitación de Richard Wright. Aún guarda trazas de Jet.}
{41700}{}{Depósito de oxígeno}
{41701}{}{Este es el depósito de oxígeno para el respirador de Salvatore.}
{41800}{}{Deposito de veneno}
{41801}{}{Este depósito es similar al tanque de oxígeno, pero tiene el símbolo de una pequeña calavera y huesos grabado en la parte inferior. Si no lo hubieras examinado muy de cerca, no hubieras visto el símbolo.}
{41900}{}{Piezas de la mina}
{41901}{}{Ves un montón de piezas claramente etiquetadas como "Purificador de aire GX-9". Usando tus increíbles habilidades deductivas, decides que probablemente sean piezas de un purificador de aire roto.}
{42000}{}{Vale de la mina Morningstar}
{42001}{}{Este pequeño vale probablemente sirve para pagar a los trabajadores de la mina Morningstar.}
{42100}{}{Santa Granada}
{42101}{}{Una reliquia sagrada de poder divino.}
{42200}{}{Chip de excavación}
{42201}{}{Este chip parece proceder de algún tipo de gran máquina industrial. Bajo la suciedad y el polvo, parece estar en un sorprendente buen estado.}
{42300}{}{Pepita de oro}
{42301}{}{Una pepita de oro.}
{42400}{}{Pedazo de monumento}
{42401}{}{Esto es una pieza del descontento monumento de piedra que encontraste en el desierto. Aunque muchos en tu poblado no dudarían en considerarlo como una reliquia sagrada, de algún modo sospechas que has sido engañado.}
{42500}{}{Cabeza de piedra}
{42501}{}{Un enorme monumento de piedra.}
{42600}{}{Mineral de uranio}
{42601}{}{Un trozo de mineral de uranio, sin refinar.}
{42700}{}{Aliento de fuego}
{42800}{}{Suministros médicos}
{42801}{}{Una caja de suministros médicos. Aunque no hay nada que pueda utilizar.}
{42900}{}{Diente de oro}
{42901}{}{Este diente de oro pertenecía a otra persona, pero ya no lo necesitará.}
{43000}{}{Proyectil de Howitzer}
{43001}{}{Un proyectil de 75mm. de un cañón Howitzer. La mayoría del revestimiento esta corroído, pero puedes ver estas letras: EXP. 25-09-98.}
{43100}{}{Maleta de Ramirez, cerrada}
{43101}{}{Esta es la maleta que recibiste de Gran Jesús Mordino para dársela a Ramirez en el Establo.}
{43200}{}{Maleta de Ramirez, abierta}
{43201}{}{Esta es la maleta que recibiste de Gran Jesús Mordino para dársela a Ramirez en el Establo. Está abierta, y has sacado el Jet que había dentro.}
{43300}{}{Gafas de espejo}
{43301}{}{Un par de gafas de sol a la última moda. Sólo con tenerlas en tu inventario hace que te sientas más guay.}
{43400}{}{Carro}
{43401}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{43500}{}{Carro}
{43501}{}{Un carro de mercancías convertido a partir de restos destrozados de un antiguo automóvil.}
{43600}{}{Baraja de cartas}
{43601}{}{Una baraja de cartas estándar.}
{43700}{}{Baraja de cartas marcadas}
{43701}{}{Todas las cartas de esta baraja son reinas rojas. Debe ser para juegos aburridos.}
{43800}{}{Llave del templo}
{43801}{}{Una llave para la puerta del templo de Arroyo.}
{43900}{}{Hilo de bolsillo}
{43901}{}{Pelusa que encontraste en un bolsillo.}
{44000}{}{Gel biomédico}
{44001}{}{Un bote de gel biomédico que se usa en biomedicina.}
{44100}{}{Chapa de identificación de Blondie}
{44101}{}{Esta chapa de identificación tiene el nombre de "Blondie" grabado en la parte trasera. Bajo el nombre está el número "11".}
{44200}{}{Chapa de identificación de Angel-Eyes}
{44201}{}{Esta chapa de identificación indica que su propietario es "Angel-Eyes". Bajo el nombre está el número "16".}
{44300}{}{Chapa de identificación de Tuco}
{44301}{}{Esta apestosa chapa identificación indica que su propietario es "Tuco Benedicto Pacifico Juan Maria Ramirez", seguido por el número "27".}
{44400}{}{Mapa de los saqueadores}
{44401}{}{Un mapa arrugado de California del Norte de antes de la guerra. Reno y las rutas de las caravanas circundantes están subrayados en rojo, y hay un "X" roja al este de Reno bajo la que hay escrito "Saqueadores".}
{44500}{}{Insignia del sheriff}
{44501}{}{Un insignia usada por el sheriff de una ciudad.}
{44600}{}{Planos del vertibird}
{44601}{}{Un juego de planos para la construcción de vertibirds.}
{44700}{}{Holodisco de Bishop}
{44701}{}{Este holodisco contiene información que incrimina a Bishop en un trato secreto con la RNC. Aparentemente, Bishop contrató mercenarios para atacar Ciudad Refugio con la esperanza de que ésta pidiera ayuda militar a la RNC. Este holodisco sólo tiene datos de audio, no de texto. Ciudad Refugio podría estar interesada en esto.}
{44800}{}{Libro de cuentas}
{44801}{}{Este libro de cuentas incluye una lista de pagos mensuales a una banda de mercenarios, realizados por la Familia Bishop de Nuevo Reno. Los pagos dependen mucho de cuánta "presión" hagan los mercenarios sobre Ciudad Refugio. En Ciudad Refugio podrían estar interesados en esto.}
{44900}{}{Sin uso}
{44901}{}{Sin uso}
{45000}{}{Papel desgarrado 1}
{45001}{}{Ves un trozo de papel escrito. Parece un trozo de código de algún tipo. Desafortunadamente, el código está incompleto. Si pudieras encontrar los tres trozos... Puedes ver lo siguiente: 1. Contraseña de Física KSLJ, 2. Contraseña de Química TIU, 3. Contraseña de biología INTL}
{45100}{}{Papel desgarrado 2}
{45101}{}{Ves un trozo de papel escrito. Parece un trozo de código de algún tipo. Desafortunadamente, el código está incompleto. Si pudieras encontrar los tres trozos... Puedes ver lo siguiente: KJ: Ken-Lee-9, ASPO- Lo-S, VR- Dnky-Pnch-}
{45200}{}{Papel desgarrado 3}
{45201}{}{Ves un trozo de papel escrito. Parece un trozo de código de algún tipo. Desafortunadamente, el código está incompleto. Si pudieras encontrar los tres trozos... Puedes ver lo siguiente: 7313, hi-S12908, 98790}
{45300}{}{Papel con contraseña}
{45301}{}{Esta es la hoja de papel que forman los tres trozos al reunirlos, revelando tres contraseñas. El texto dice: 1. Contraseña de Física KSLJKJ: Ken-Lee-97313, 2. Contraseña de Química TIUASPO- Lo-Shi-S12908, 3. Contraseña de Biología INTLVR- Dnky-Pnch-98790}
{45400}{}{Interruptor de explosivo}
{45401}{}{Este interruptor es el componente final de un explosivo.}
{45500}{}{Maletero de coche}
{45501}{}{El maletero es un gran lugar para guardar tus cosas.}
{45600}{}{Llave de la celda}
{45601}{}{Esta llave es la adecuada para las puertas de las celdas de Broken Hills.}
{45700}{}{Informe de campo del Hubologista}
{45701}{}{Un informe oficial para la membresía en la Fe Verdadera.}
{45800}{}{Holodisco B.M. 5}
{45801}{}{En la etiqueta pone: Mensaje a CHQ- Confidencial.}
{45900}{}{Holodisco B.M. 1}
{45901}{}{En la etiqueta pone: Registro de las transmisiones por radio en el punto de control 1.}
{46000}{}{Holodisco B.M. 2}
{46001}{}{En la etiqueta pone: Registro de las transmisiones por radio en el punto de control 2.}
{46100}{}{Holodisco B.M. 3}
{46101}{}{En la etiqueta pone: Registro de las transmisiones por radio en el punto de control 3.}
{46200}{}{Holodisco B.M. 4}
{46201}{}{En la etiqueta pone: Registro de las transmisiones por radio del equipo de investigación.}
{46300}{}{Holodisco de evacuación}
{46301}{}{En la etiqueta pone: Aviso de la evacuación de la Base.}
{46400}{}{Holodisco del experimento}
{46401}{}{En la etiqueta pone: Registro de investigación.}
{46500}{}{Holodisco médico}
{46501}{}{En la etiqueta pone: Registro médico.}
{46600}{}{Papel con contraseña}
{46601}{}{Un papel con la palabra "TCHAIKOVSKY" escrita en él.}
{46700}{}{Recipiente de Jesse}
{46800}{}{Comida de Smitty}
{46801}{}{Algún tipo de ensalada y un sandwich de lo que crees que es carne de brahmin, cubierto con una espesa salsa de color amarillo oscuro. También tiene en un lado un extraño vegetal encurtido verde.}
{46900}{}{Aguardiente}
{46901}{}{Un aguardiente muy fuerte o un producto de limpieza, tú decides.}
{47000}{}{Mordaza}
{47001}{}{Un discutible juguete sexual. Si necesitas preguntar, es que no quieres saberlo.}
{47100}{}{"La Flor de Lavanda"}
{47101}{}{Parece ser algún tipo de novela romántica escrita por Dorothy Rixon. La portada muestra a una mujer en el borde de una cama, cubierta por cientos de flores.}
{47200}{}{Holodisco Hubologista}
{47201}{}{Este holodisco esta etiquetado como "Hubología: la verdad tras las mentiras". Parece que funciona en tu PipBoy.}
{47300}{}{Dedo mutado del pie}
{47301}{}{Ves tu sexto dedo. Es una pequeña parte mutada de ti mismo. Por alguna razón, notas una terrible sensación de pérdida cuando miras al pequeño dedo amputado.}
{47400}{}{Margaritas}
{47401}{}{Una maceta con margaritas. ¿No son bonitas?}
{47500}{}{Sin uso}
{47501}{}{Sin uso}
{47600}{}{Carta de la Primera Iluminada}
{47601}{}{Un informe dirigido a ASH-9 en San Francisco. Desde luego es una lectura áspera: tablas de ajustes a opresivos, informes de gastos, y otras chorradas con las que no deberías perder el tiempo.}
{47700}{}{Holodisco de emisión}
{47701}{}{En la etiqueta pone: "Galaxy News Network".}
{47800}{}{Holodisco de misión Sierra}
{47801}{}{En la etiqueta pone: "Estado de Misión".}
{47900}{}{Circuito CompNav}
{47901}{}{Placa de circuito que parece se puede insertar en una computadora. El hecho de que ponga "Petrolero Poseidon" y "computadora de navegación" en ellas te hace pensar que encajaría en la computadora de navegación de un petrolero Poseidon.}
{48000}{}{Bono +1 Agilidad}
{48100}{}{Bono +1 Inteligencia}
{48200}{}{Bono +1 Fuerza}
{48300}{}{Libro de Pistas para Fallout 2}
{48301}{}{Bien, ESTO hubiese sido mejor tenerlo al principio del maldito juego.}
{48400}{}{Oreja del jugador}
{48401}{}{Esta es tu oreja. El Masticador la mordió durante la pelea y la escupió sobre tu cuerpo inconsciente. Si estás leyendo esto, probablemente significa que cargarás la partida pronto. Por supuesto, es posible que este objeto tenga algún valor especial.}
{48500}{}{Oreja del Masticador}
{48501}{}{Esta es la oreja de El Masticador. Se la mordiste cuando le estabas aporreando hasta dejarlo sin sentido. Felicidades por derrotarlo. Es uno de los enemigos mas duros del juego, especialmente si no llevas ningún arma o armadura.}
{48600}{}{Mineral de uranio refinado}
{48601}{}{Un trozo de mineral de uranio. Parece que ha sufrido algún tipo de proceso. Parece pesado.}
{48700}{}{Nota de Francis}
{48701}{}{"Zaius: Marcus no está haciendo nada con ese Jacob y sus malditos conspiradores. Primero desactivan el purificador... ¿y luego qué? Encontré los túneles en los que se reúnen. Imagino que un par de cuerpos podrían implicar a Jacob. Si quieres entrar, dímelo. ¡Y quema la maldita nota esta vez!" -Firmado, Francis.}
{48800}{}{Unidad motriz de K-9}
{48801}{}{Esto es un mecanismo de movimiento para el robot K-9.}
{48900}{}{Arma especial de boxeador}
{49000}{}{Holodisco de la RNC}
{49001}{}{En la etiqueta pone: "Historia de la RNC".}
{49100}{}{Muñeco del señor Nixon}
{49101}{}{Ves un pequeño muñeco con una gran nariz roja. Por alguna razón, no te tragas la aparente cara de inocencia que tiene este juguete infantil.}
{49200}{}{FOB del petrolero}
{49201}{}{Un pase codificado que permite el acceso a las zonas de alta seguridad.}
{49300}{}{Holodisco de Enseñanzas}
{49301}{}{En la etiqueta pone: "Enseñanzas Hubologistas".}
{49400}{}{Vale de la mina Kokoweef}
{49401}{}{Este pequeño vale probablemente sirve para pagar a los trabajadores de la mina Kokoweef.}
{49500}{}{Llave presidencial de acceso}
{49501}{}{Esta llave de acceso tiene grabado lo que parece el sello presidencial. Parece que sirve para entrar a los niveles de acceso presidencial de las computadoras.}
{49600}{}{Guantes de boxeo}
{49601}{}{Un par de guantes de boxeo que apenas huelen a sudor. Parece que se han usado mucho: aún tienen muchas viejas manchas de sangre.}
{49700}{}{Guantes de boxeo trucados}
{49701}{}{Alguien ha dejado caer "accidentalmente" placas de metal en estos guantes de boxeo. Técnicamente se podría considerar hacer trampas, pero tú prefieres pensar que es una mejor oportunidad para romper huesos.}
{49800}{}{Cañón dual de plasma}
{49801}{}{Utilizado únicamente por torretas.}
{49900}{}{Realzador de lenguaje PipBoy}
{49901}{}{Este realzador consiste en un holodisco de almacenamiento, un cable de microfilamentos, un casco, y un sensor óptico que se sitúa sobre el ojo derecho. Al usarlo, un destello óptico transmite un diccionario completo en la memoria del usuario, mejorando de forma permanente su habilidad conversadora.}
{50000}{}{FN FAL HPFA}
{50001}{}{Este rifle ha sido más ampliamente utilizado por las fuerzas armadas que cualquier otro fusil en la historia. Es un arma de asalto fiable para cualquier terreno o situación táctica. El HPFA es más potente que el estándar FN FAL. Min FU: 5.}
{50100}{}{Caja fuerte}
{50200}{}{Caja fuerte de suelo}
{50300}{}{Módulo azul de memoria}
{50301}{}{Un módulo de memoria de sólo lectura para una computadora, que contiene información médica. Este módulo detalla mejoras de carisma.}
{50400}{}{Módulo verde de memoria}
{50401}{}{Un módulo de memoria de sólo lectura para una computadora, que contiene información médica. Este módulo detalla mejoras de percepción.}
{50500}{}{Módulo rojo de memoria}
{50501}{}{Un módulo de memoria de sólo lectura para una computadora, que contiene información médica. Este módulo detalla mejoras de fuerza.}
{50600}{}{Modulo amarillo de memoria}
{50601}{}{Un módulo de memoria de sólo lectura para una computadora, que contiene información médica. Este módulo detalla mejoras de inteligencia.}
{50700}{}{Cuerpo en descomposición}
{50701}{}{Este cuerpo parcialmente descompuesto corresponde a una criatura humanoide.}
{50800}{}{Muñeca hinchable}
{50801}{}{Una muñeca hinchable de plástico. Este modelo se denomina "Tandi".}
{50900}{}{Muñeca hinchable dañada}
{50901}{}{Esta muñeca hinchable tiene las costuras rotas. Obviamente se ha usado mucho.}
{51000}{}{Mesa de billar}
{51100}{}{Mesa de billar}
{51200}{}{Mesa de billar}
{51300}{}{Mesa de billar}
{51400}{}{Mesa de billar}
{51500}{}{Mesa de billar}
{51600}{}{Realzador médico PipBoy}
{51601}{}{Este realzador consiste en un holodisco de almacenamiento, un cable de microfilamentos, un casco, y un sensor óptico que se sitúa sobre el ojo derecho. Al usarlo, un destello óptico transmite un diccionario de habilidades y conocimientos médicos en la memoria del usuario, mejorando de forma permanente su habilidad médica.}
{51700}{}{"Jesusito"}
{51701}{}{Esta hoja de apariencia maléfica perteneció a Pequeño Jesús Mordino. Tiene numerosos rasguños y cortes por toda su superficie, pero su hoja está bien afilada. En su mango está grabado "Jesusito".}
{51800}{}{Minicañón doble}
{51801}{}{Lo usan sólo los personajes con auto-cañón.}
{51900}{}{Chapas de botella}
{51901}{}{Son chapas de botella sin valor. Has oído que hace tiempo se usaban como moneda, pero sospechas que no es más que un cuento.}
{52000}{}{Minicañón pesado doble}
{52001}{}{Lo usan sólo los personajes con auto-cañón.}
{52100}{}{Cepillo}
{52101}{}{Una pequeña caja usada para recoger las monedas para los pobres.}
{52200}{}{Cuchillo Wakizashi}
{52201}{}{Un corto cuchillo artesanal. La punta parece diseñada para agujerear armaduras.}
{52300}{}{Mapa de reconocimiento}
{52301}{}{Parece un mapa de reconocimiento de la zona de la Bahía.}
{52400}{}{Túnica del guardián del puente}
{52401}{}{Esta maloliente y sucia prenda debe estar hecha con alguna tela especial para haber resistido en el asqueroso cuerpo del guardián. Por extraño que parezca, tiene marcas de quemaduras, como si se hubieran usado armas de plasma contra ella... sin efecto. No tienes NI idea del por qué es morada.}
{52500}{}{Jeringuilla}
{52501}{}{Un tipo de instrumento médico de inyección. Parece alta tecnología. No sabes de qué está lleno pero parece que sólo queda una dosis.}
{52600}{}{Muerto con camisa roja}
{52601}{}{Este tipo lleva un extraño uniforme rojo que nunca antes habías visto. Parece que murió de deshidratación.}
{52700}{}{Muerto con camisa roja}
{52701}{}{Este tipo lleva un extraño uniforme rojo que nunca antes habías visto. Parece que murió de deshidratación.}
{52800}{}{Muerto con camisa roja}
{52801}{}{Este tipo lleva un extraño uniforme rojo que nunca antes habías visto. Parece que murió de deshidratación.}
{52900}{}{Máquina de minería}
{53000}{}{Cuchillo de jefe final}
{53100}{}{Pistola de plasma de jefe final}
{53200}{}{Mapa de Sam Pritchard}
{53201}{}{Este mapa crudo muestra los alrededores de Nuevo Reno. Parece que hay algún tipo de base militar en el norte.}
{53300}{}{Piel de gecko de fuego}
{53301}{}{La seca y curada piel de un gecko de fuego. Está muy quemado y, como resultado, tiene poco valor.}
