{100}{}{Ves a una comerciante.}
{102}{}{Ves a un comerciante que está tratando de arreglar la bomba de agua.}
{103}{}{¡Simplemente no puedo conseguir que esta cosa funcione!}
{104}{}{Esto parece ser muy difícil de arreglar.}
{105}{}{¡Qué mierda es esto!}
{106}{}{Stubborn little sonnuva bitch are we?}
{107}{}{¿Puedes ayudar?}
{108}{}{Quizás tengas más suerte con esto.}
{109}{}{¡Oye, gracias por arreglar la bomba de agua!}
{110}{}{You should notify the headmonk that the waterpump is now fixed.}
{200}{}{Gracias por ayudarnos con esta cosa.}
{300}{}{Ah, what a piece of shi- umm, I'm a little busy right now. Do you need something or are
 you just wasting my time?}
{301}{}{Actually yes, the Abbot sent me. He said the water pump is having some trouble.}
{302}{}{Heh, "having trouble" is an understatement. This ol' thing is totally busted. There's no way
 it's going to run again.}
{303}{}{Ya, uno no lo pensaría al mirarlo.}
{304}{}{Sure, be my guest. Not like you could break it any more.}
{305}{}{Mira, no quiero parecer maleducado, pero necesito más tiempo para trabajar.}
{306}{}{The main water pump for the Abbey is busted. The damn thing was breathing its last the past few days
 and now it's finally gone out.}
{307}{}{I'm a bit of a techie, mind if I take a look?}
{308}{}{Well, I'm not that great with machines, but perhaps I can see if something can be done.}
{309}{}{Seguro, nadie te detiene.}
{310}{}{Eh, lo siento. Adiós.}
{311}{}{Entonces veré lo que puedo hacer.}
{312}{}{I thought I might be able to help, but if you want to be an asshole about it, then you're welcome to figure it out on your own.}
{313}{}{I told the Abbot I'd be willing to help, but if you want to be an asshole about it, then you're welcome to figure it out on your own.}
{320}{}{[He squints at you for a moment, then slowly lets out his breath in a sigh.] Sorry friend, this thing's being a
 real bitch, and it's gotten me all worked up. I didn't mean to snap at ya. }
{321}{}{Bien, ¿cuál es el problema entonces?}
{322}{}{Da igual, adiós.}
{330}{}{Vuelve y habla conmigo por la mañana.}
{400}{}{Oh, eres tú otra vez. ¿Alguna suerte?}
{401}{}{No, aún no. Me pondré en contacto cuando lo haya hecho.}
{402}{}{Actually, yes. I looked inside and it seems the motor is completely busted. The connections are shot, so we're
 going to have to get our hands on a new motor, as well as some wires to reconnect everything since the old wires are fried.}
{500}{}{Hmm...the connectors are shot on the main motor, eh? Well, I got some wires here with me that will work, but not
 that specific motor. I am sure Vault City has the part though. Go there and speak with Harry in the main courtyard. Tell him
 Dave sent you. Damn motor is expensive, but he should give you a good deal.}
{501}{}{Voy a ir allí ahora. Volveré pronto.}
{502}{}{Whoa, hold on a second. I was happy to help you figure out the problem, but who said I'm willing to trek across
 the wastes to go buy you an expensive motor? If you want my help, it's going to cost you.}
{503}{}{How 'bout *you* tell Harry that when you go fetch it your damn self? I'm not your fucking errand boy. Bye.}
{510}{}{Alright, I wouldn't expect someone to do work for free. The part will cost you bout 500 and I think 100 more for
 your trouble is reasonable. Here's 600.}
{511}{}{Eso es mejor. Volveré con la pieza.}
{600}{}{Any luck on that part? This machine won't fix itself.}
{601}{}{No, aún no. Volveré cuando lo consiga.}
{602}{}{Sí, tengo la pieza aquí.}
{700}{}{Excellent. Want me to install the damn thing, or do you want the pleasure?}
{701}{}{Creo que puedo escuchar el océano.}
{702}{}{Actually, I think I've done enough on this job. Go ahead and install it yourself.}
{800}{}{Muy bien, déjalo.}
{801}{}{Aquí están.}
{900}{}{Eso no suena bien.}
{901}{}{La bomba de agua ha sido reparado.}
{910}{}{(Wipes the sweat from his forehead.) Yeah, need something?}
{911}{}{Por supuesto, capitán. ¿Cuál es el problema?}
{912}{}{No importa. Adiós.}
{913}{}{I took a look at the water pump and it seems the motor is completely busted. The connections are shot, so we're
 going to have to get our hands on a new motor, as well as some wires to reconnect everything since the old wires are fried.}
