{100}{}{Ves al señor Tramposo.}
{101}{}{Ves a una mujer de apariencia cansada. Parece como si hubiera estado llorando.}
{200}{}{Bienvenido a la gran ciudad.}
{201}{}{Habla con Jacob si quieres algo.}
{202}{}{Buen juego, ¿verdad?}
{300}{}{Bienvenido a la gran ciudad.}
{301}{}{Habla con Jacob si quieres algo.}
{302}{}{Hoy tenemos un día precioso, ¿verdad?}
{400}{}{Oh, Dios. Lo siento, pero no tengo nada que decirte. Por favor, vete.}
