{100}{}{Ves una bomba de agua.}
{101}{}{Ves una bomba de agua muy vieja que parece estar roto.}
{102}{}{Ahora la bomba de agua funciona correctamente.}
{103}{}{Necesitará algo más que tus manos para arreglar esta máquina. Tal vez algunas herramientas ayudarían con la instalación de esta pieza.}
{104}{}{Has reparado la bomba de agua.}
{105}{}{No has conseguido reparar la bomba.}
{106}{}{Has descubierto de lo que va mal en la bomba de agua.}
{200}{}{Abres la máquina y miras adentro. Ves muchos engranajes y motores oxidados. Uno de los motores tiene una grieta en el.}
{201}{}{Lo dejas para otro día.}
{202}{}{Investigar más.}
{203}{}{Tras una inspección más cercana, ves que la grieta no es la causa del problema, sino más bien la conexión para donde van los cables. Los conectores parecen haberse quemado a lo largo de los años de uso. Se necesitara un motor completamente nuevo, así como un nuevo conjunto de cables para que esta máquina vuelva a funcionar.}
{204}{}{Salir.}
