#############################################################
#  Abrir armarios (Navarro)     		            #
#  Traducido por Wenck                                      #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Consigues forzar hábilmente la cerradura.}
{171}{}{Debido a tu falta de habilidad, la cerradura se ha atascado.}
{172}{}{No consigues forzar la cerradura.}

# Unlock Door
{173}{}{ fuerza hábilmente la cerradura.}
{174}{}{ no es lo suficientemente hábil, y consigue que la cerradura se atasque.}
{175}{}{ no consigue forzar la cerradura.}

# Player uses an item on the door
{176}{}{Arrancas la cerradura de la puerta.}
{177}{}{Te dañas la espalda mientras intentas arrancar la cerradura, provocándote un punto de daño.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Te dañas la espalda mientras tratas de arrancar la cerradura y te haces }
{179}{}{ puntos de daño.}
{180}{}{Eres demasiado débil para arrancar la cerradura.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ arranca la cerradura de la puerta.}
{182}{}{ se daña la espalda mientras intenta arrancar la cerradura y se provoca un punto de daño.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ se daña la espalda mientras trata de arrancar la cerradura y se provoca }
{184}{}{ puntos de daño.}

{185}{}{ es demasiado débil para arrancar la cerradura.}
{186}{}{ se daña la espalda mientras trata de arrancar la cerradura y se provoca un punto de daño.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ se daña la espalda mientras intenta arrancar la cerradura y se provoca }
{188}{}{ puntos de daño.}

# Lock Door
{189}{}{Abres hábilmente el armario.}
{190}{}{No consigues abrir el armario.}

# Lock Door
{191}{}{ abre hábilmente el armario.}
{192}{}{ no consigue abrir el armario.}

{203}{}{The locker appears to be locked.}

{800}{}{Has recuperado el FOB.}
{810}{}{Te has hecho con los planos.}
{820}{}{Has recuperado la unidad motriz de K-9.}
