{100}{}{Ves a una mujer mayor de aspecto bondadoso.}
{150}{}{Ves a Mamá, cocinando y limpiando con afán.}
{151}{}{Ves a una vieja y robusta mujer con una sonrisa jovial en su rostro.}
{200}{}{Hola, soy Mamá. No te he visto antes por aquí.}
{201}{}{Hola de nuevo. ¿Qué puede hacer Mamá por ti?}
{202}{}{Yo }
{203}{}{Mmmm. ¿Vale? Adiós, Mami.}
{220}{}{Ya casi te has comido todo lo que tengo. ¿Por qué no te vas un rato a otro sitio? Por hoy ya has comido suficiente.}
{221}{}{Bueno }
{222}{}{, parece que estás un poco confuso. Odio ver sufrir a una criaturita como tú. ¿Quieres comer algo?}
{223}{}{Yo lleno. Comida de Mamá bueeena. Adiós Mamá.}
{224}{}{¿Yo paga?}
{225}{}{Yo marcho. Adiós, Mamá.}
{240}{}{Bueno, de acuerdo. ¿Qué es lo que quieres? (Mamá se hace con el monedero).}
{241}{}{¿Mamá? (ofreces el monedero)}
{242}{}{¡No! Marcho yo. Adiós, Mami.}
{250}{}{No, la verdad que no. Lo siento. Sólo tenemos pastel de rata, pan de rata, y spaghetti.}
{251}{}{¿Qué va a ser esta vez?}
{252}{}{Uh, ¿podría ser algo que no tuviera mucha rata?}
{253}{}{Creo que pediré el pan de rata.}
{254}{}{Creo que pediré el pastel de rata.}
{270}{}{Podrías pedir los spaghetti. No llevan mucha rata... sólo la salsa, eso es todo.}
{271}{}{Bien, de acuerdo, creo que pediré los spaghetti con salsa de rata.}
{280}{}{Te daré una buena ración ahora mismo. Serán 10 dólares.}
{281}{}{Ahora mismo no tengo suficiente dinero. En vez de eso, déjame hacerte una pregunta.}
{282}{}{¿10 dólares por una rata? Debes de estar loca. Demonios, en mi aldea una buena rata jugosa cuesta bastante más. Trato hecho.}
{283}{}{Bien, vale. Aquí está el dinero.}
{284}{}{He cambiado de idea. En vez de eso, déjame hacerte una pregunta.}
{285}{}{Creo que volveré más tarde. Adiós.}
{300}{}{Veo que tienes buen apetito. Me gusta ver a alguien que come bien. ¿Te ha parecido suficiente?}
{301}{}{Ni de broma, Mamá. Quiero el segundo plato.}
{302}{}{Claro. Déjame hacerte una pregunta, Mamá.}
{303}{}{Es suficiente por hoy. Adiós, Mamá.}
{320}{}{Bueno, necesito que alguien le entregue un almuerzo a Smitty. Está justo al oeste, en el desguace. ¿Lo harías por mí? Te daré un almuerzo gratis si lo haces.}
{321}{}{Claro, no me importaría.}
{322}{}{Déjame pensármelo. Mientras tanto, déjame hacerte una pregunta.}
{323}{}{Uh, lo siento, Mamá. No puedo. Adiós.}
{340}{}{Estás de suerte. Tenemos filete de escorpión rad.}
{341}{}{Tenemos rata-cerdo estofada.}
{342}{}{Servimos colas de escorpiones rad hervidas en mantequilla clarificada.}
{343}{}{La sopa de col es todo lo que me tengo ahora.}
{344}{}{¡Frituras de brahmin recién hechas!}
{345}{}{Marchando un pastel caliente de gecko.}
{346}{}{Filete de lomo.}
{347}{}{Rata topo con grasa y magra.}
{348}{}{Trocitos de nómada bañados en salsa.}
{349}{}{Filet mignon.}
{350}{}{Medallones de gecko a la parrilla.}
{351}{}{Mantis a la marsala.}
{352}{}{Manicotti de rata topo.}
{353}{}{Brahmin en brochetas.}
{354}{}{Escorpión rad empanado.}
{355}{}{¡Jamón enlatado!}
{356}{}{Uh, no estoy segura, pero sabe como el pollo.}
{357}{}{Trocitos de centauro, mi especialidad.}
{358}{}{Es una sorpresa.}
{359}{}{¡No puedo darte mis recetas secretas!}
{360}{}{¿De verdad?}
{375}{}{Aquí tienes. Parece estar medio muerto de hambre. (Mamá te entrega una gran fuente humeante con comida que huele deliciosamente).}
{376}{}{Gra-cias, Mamá.}
{385}{}{Ah, ya te vas. Sabía que te gustaría.}
{386}{}{Mmm, ñam ñam. Adiós, Mamá.}
{395}{}{Muchísimas gracias. Lo haría yo misma, pero no hay nadie que vigile el local mientras estoy fuera. Aquí está el almuerzo de Smitty. Si no se lo llevara estoy segura de que se olvidaría de comer.}
{396}{}{Se lo llevaré ahora mismo.}
{405}{}{Estoy muy decepcionada contigo. El pobre Smitty tuvo que venir él mismo a por su comida. Y ahora, ¿qué es lo que quieres?}
{406}{}{Hola, mi nombre es Mamá y regento este local. También tengo la mejor comida al norte de Nuevo Reno.}
{407}{}{¿Sobre qué querías hablar con Mamá?}
{408}{}{Tú no eres mi mamá.}
{409}{}{¿Has oído hablar de un Refugio o de alguien llamado Vic?}
{410}{}{¿Qué se puede hacer en este pueblo?}
{411}{}{¿Qué tienes para comer?}
{425}{}{Ya lo sé. Pero todo el mundo me llama así. Demonios, incluso trato a la gente como si fueran mis hijos: siempre que obedezcas mis normas, claro.}
{426}{}{¿Normas?}
{435}{}{Así es. No robar, no maldecir, y no pelear, en mi tienda no lo harás. Porque si lo haces, fuera te irás. Me gusta que este sitio sea pacífico.}
{436}{}{Ya veo. Deja que te pregunte algo más.}
{437}{}{Tiene sentido. Ya nos veremos, Mamá.}
{445}{}{Bueno, hay una Ciudad Refugio bastante al este de aquí y un poco al norte. Y Vic, hmmm, déjame pensar...}
{446}{}{Espero que sepas donde está Vic. Es un mercader.}
{447}{}{Gracias, pero eso es todo lo que quería saber. Adiós, Mamá.}
{455}{}{¿Vic el Mercader? Ya sé quién es. Sí, creo que Metzger lo mantiene retenido por alguna razón.}
{456}{}{¿Quién es Metzger y dónde puedo encontrarle?}
{457}{}{Eso es genial, Mamá. Gracias.}
{465}{}{Metzger es el jefe local del Gremio de Esclavistas. Tiene a toda clase de gente encerrada en ese sitio. Está calle arriba, justo al norte de aquí.}
{466}{}{Metzger solía ser el jefe local del Gremio de Esclavistas. Tenía a toda clase de gente encerrada en ese sitio. Pero ahora no lo sé... he oído que lo han matado.}
{467}{}{Gracias por la información. Déjame hacerte otra pregunta, Mamá.}
{468}{}{Tengo que ocuparme de algunos asuntos. Gracias, Mamá.}
{475}{}{Ve y dale ya ese almuerzo a Smitty.}
{476}{}{No te ayudaré hasta que cumplas tu palabra.}
{477}{}{Date prisa.}
{478}{}{Ve a darle a Smitty su almuerzo. Deprisa.}
{479}{}{Deja de perder el tiempo y entrégale ese almuerzo a Smitty.}
{485}{}{Ha sido un buen trabajo. Te debe de haber abierto el apetito. Tengo una auténtica delicia para ti como recompensa. Un plato combinado con la condenada mejor comida que tengo aquí, sólo para ti.}
{486}{}{¡Eso suena genial! ¡Voy a comérmela!}
{487}{}{Vaya, Mamá. No creo que ahora pueda comerme eso, pero gracias de todos modos. Adiós.}
{500}{}{Hmm, no sé mucho sobre ella. Seguramente sea alguien que se está divirtiendo un poco, eso es todo.}
{501}{}{¿Siempre ha estado encantada?}
{502}{}{¿Alguien usa esa casa?}
{503}{}{Estoy de acuerdo. Adiós.}
{520}{}{Empezó hace 2 años. He oído todo eso de los espíritus y los quejidos. Pero no me lo creo.}
{521}{}{¿Hace dos años, eh? ¿Alguien vivía en aquel lugar entonces?}
{522}{}{Ni yo. Gracias.}
{540}{}{Uno de los chicos solía dormir allí hace unos años. Quizá él sepa algo.}
{541}{}{¿Quién?}
{542}{}{No lo creo. Adiós.}
{560}{}{Solía venir aquí a empeñar cosas. Recuerdo un pequeño medallón de oro que se guardó para sí mismo.}
{561}{}{¿Recuerdas su nombre?}
{562}{}{¿Medallón? Que extraño. ¿Quién era?}
{563}{}{Déjame hacerte otra pregunta.}
{564}{}{Gracias, adiós.}
{580}{}{No estoy seguro. Creo que era Joseph, Joel o algo así... Ahora debe tener 19 años... Una pena, la verdad. Creo que se ha juntado con algunos matones de por aquí.}
{581}{}{Gracias. Tengo otra pregunta.}
{582}{}{Gracias, adiós.}
{600}{}{¿Qué sabes sobre esa casa encantada?}
