{100}{}{Ves a un vagabundo con una media sonrisa.}
{101}{}{Ves a Badger.}
{102}{}{Ves a un vagabundo con una media sonrisa burlona en su rostro.}
{103}{}{::Eructa con fuerza:: ¿Qué quieres?}
{104}{}{::eructas::}
{105}{}{¿Quién?}
{106}{}{¿Quién eres?}
{107}{}{¿Qué puedes decirme de este petrolero?}
{108}{}{¿Qué haces aquí?}
{109}{}{Me gustaría que piratearas una computadora para mí.}
{110}{}{¿Cómo va lo del pirateo?}
{111}{}{Nada. Buen eructo.}
{112}{}{::Prepara otro eructo::}
{113}{}{::Eructas con fuerza::}
{114}{}{Asqueroso.}
{115}{}{::Lanza un horripilante eructo que desafía los mismos cielos con su volumen y alcance::}
{116}{}{::Aplaudes::}
{117}{}{Soy Badger. Tenía una banda. ::suspira:: Nos llamábamos Miradas Ardientes. Ahora soy el técnico de computadoras residente de San Fran.}
{118}{}{¡Oh! ¡Petroleros!}
{119}{}{¿Qué clase de cosas de computadoras haces?}
{120}{}{Apostaría a que tu banda apestaba.}
{121}{}{¿Qué fue de la banda?}
{122}{}{Gracias. Adiós.}
{123}{}{Ehh... de acuerdo.}
{124}{}{¡Adiós!}
{125}{}{Deberías hablar con Marc o el capitán sobre eso.}
{126}{}{¿Dónde puedo encontrar a Marc?}
{127}{}{¿Dónde puedo encontrar al capitán?}
{128}{}{Soy el genio de las computadoras local.}
{129}{}{¿Qué clase de cosas de computadoras haces?}
{130}{}{Gracias. Adiós.}
{131}{}{No me molestes. ::se pedorrea:: Estoy trabajando en ello, ¿de acuerdo?}
{132}{}{Está bien, está bien. Tan sólo avísame cuando termines.}
{133}{}{Bien, digamos simplemente que soy un especialista en recuperar información.}
{134}{}{¿Puedes recuperar algo para mí?}
{135}{}{¿Y eso qué significa?}
{136}{}{Sí, bueno, que te jodan.}
{137}{}{¡Oye!}
{138}{}{Que te jodan a ti también.}
{139}{}{¡Que te voy a decir! ¡Rompíamos la pana! Nuestro cantante era... umm... un poco locaza, y Aaron siempre estaba sudando, y de todo lo demás tenía la culpa Todd. Pero éramos buenos.}
{140}{}{Lástima que no estéis juntos de nuevo. Me hubiera gustado haberos escuchado.}
{141}{}{Umm. Desde luego. Tengo más preguntas.}
{142}{}{Seguro que apestábais.}
{143}{}{Normalmente puedes encontrar a Marc en el bar.}
{144}{}{Gracias. Tengo más preguntas.}
{145}{}{Gracias. Eso es todo.}
{146}{}{Normalmente el capitán está en el puente. Simplemente sube las escaleras desde el bar.}
{147}{}{Gracias. Tengo más preguntas.}
{148}{}{Gracias. Eso es todo.}
{149}{}{Sí, pero te va a costar.}
{150}{}{¿Cuál es tu precio?}
{151}{}{Sí, lo que sea. Tengo que irme.}
{152}{}{Significa que puedo encontrar cualquier dato que necesites.}
{153}{}{¿Puedes hacer algo por mí?}
{154}{}{Ya veo. Qué guay. Tengo más preguntas.}
{155}{}{Ya veo. Gracias.}
{156}{}{Sí, lo habrías hecho. De todos modos, tengo que volver a esto.}
{157}{}{Espera. Tengo más preguntas.}
{158}{}{Gracias. Nos vemos.}
{159}{}{Creo que ahora me gustas lo suficiente como para que pueda hacerlo para ti. ¿A quién quieres que visite?}
{160}{}{A los Hubologistas.}
{161}{}{A los Shi.}
{162}{}{A ninguno. Sólo quería asegurarme.}
{163}{}{Supongo que puedo hacerlo gratis, ya que comprobaste lo de mi novia. Pero me llevará un tiempo. ¿A quién prefieres que lo haga?}
{164}{}{A los Hubologistas.}
{165}{}{A los Shi.}
{166}{}{A ninguno. Sólo quería asegurarme.}
{167}{}{Primero me tienes que hacer un favor. Mi novia se perdió en el petrolero. Encuéntrala por mí y lo haré.}
{168}{}{Me parece bien. Nos vemos.}
{169}{}{Olvídalo. Nos vemos.}
{170}{}{Como robarle el caramelo a un niño. Nunca me encontrarán. ¿Qué es lo que quieres de ellos?}
{171}{}{Genial. Tengo más preguntas.}
{172}{}{Genial. Volveré.}
{173}{}{Puedo conseguirlos. Son muy protectores con su información, y tienen algunos cortafuegos problemáticos protegiendo sus máquinas. ¿Estás seguro de que quieres que vaya tras ellos?}
{174}{}{En fin, buena suerte. Tengo más preguntas.}
{175}{}{Buena suerte. Volveré más tarde.}
{176}{}{Oye, encuentra a mi novia y entonces hablaremos.}
{177}{}{De acuerdo, de acuerdo.}
{178}{}{¿Está muerta? ¿MUERTA? ¿Cómo murió? No, espera... no me lo digas. Dame un par de horas para reponerme.}
{179}{}{Claro, claro.}
{180}{}{Ponte las pilas, juerguista. Tenemos puñeteras cosas que hacer.}
{181}{}{De acuerdo. Ya estoy mejor.}
{182}{}{Bien. Necesito preguntarte algo.}
{183}{}{Bien hecho. No quería hablar contigo.}
{184}{}{Gracias, gracias, gracias. No puedo agradecerte lo suficiente el que la salvaras. ¿Qué quieres?}
{185}{}{Tengo algunas preguntas.}
{186}{}{Tu gratitud es suficiente para mí. Hasta luego.}
{187}{}{Muy bien, entré en las computadoras Shi. No sé si lo que hice fue detectado. Supongo que ahora lo mejor es ocultarse. ¿Quieres algo más?}
{188}{}{Sí.}
{189}{}{No. Nos vemos.}
{190}{}{Conseguí lo de los Hubologistas. Sin problemas. ¿Necesitas algo más?}
{191}{}{Sí.}
{192}{}{No. Nos vemos.}
{193}{}{Acabas de cometer un gran error, amigo. Acabo de poner en tu contra a los Shi a través de sus computadoras. Estás acabado en San Francisco. }
{194}{}{Entonces supongo que lo mejor será que te mate.}
{195}{}{Dame un par de horas para reponerme.}
{196}{}{¿Quieres que piratee una computadora formateada? La información está perdida. No hay nada que hacer.}
{197}{}{Voy a tener que abandonar este lugar.}
{198}{}{Me alegro de verte.}
{199}{}{Estoy buscando algo de combustible.}
{200}{}{He oído que los Hubologistas tienen algo de combustible, y pude echar un vistazo en su computadora para ti.}
{201}{}{Los Shi tienen todo su combustible por aquí. Podría echar un vistazo a su computadora principal por ti.}
{202}{}{¿Podrías?}
{203}{}{¿Qué coño quieres?}
{204}{}{¿Badger, supongo?}
{205}{}{¡Has deshonrado a nuestro Emperador por última vez!}
{206}{}{Creo que voy a ir a comprarle algunos caramelos a Lao Chou en la ciudad.}
{207}{}{Demasiado para un juicio justo. Hmmm...}
{208}{}{Colega, relájate. Yo sólo quería algunos caramelos.}
{209}{}{¿Puedes transferir el combustible de su nave espacial al petrolero?}
{210}{}{¿Puedes conseguirme una copia de sus planos del vertibird?}
{211}{}{¿Puedes transferir el combustible y conseguirme los planos?}
{212}{}{Sí, necesito lo que tienen.}
{213}{}{Da igual, encontraré otra forma.}
{214}{}{Está bien, pero la mierda podría esparcirse.}
{215}{}{¿Puedes transferir el combustible de sus reservas al petrolero?}
{216}{}{No importa, lo haré de otra forma.}
{217}{}{No importa.}
{218}{}{Muy bien. Pasa por aquí dentro de un día y te informaré.}
{219}{}{¿Conseguiste lo que necesitaba?}
{220}{}{Sí, tengo el combustible.}
{221}{}{Sí, tengo los planos del verti.}
{222}{}{Sí, tengo el combustible y los planos.}
{223}{}{Muchas gracias. Nos vemos.}
