{100}{}{Ves a un Shi descamisado.}
{101}{}{Ves al Dragón, héroe de muchos campesinos Shi.}
{102}{}{Ves a un musculoso hombre descamisado con manos que parecen armas peligrosas.}
{103}{}{¿Cómo puedo ayudarte?}
{104}{}{¡Dinkle humper doo!}
{105}{}{¿Quién?}
{106}{}{¿Con quién estabas luchando?}
{107}{}{¿Quién eres?}
{108}{}{Enséñame a luchar.}
{109}{}{Quiero desafiarte.}
{110}{}{Olvídalo.}
{111}{}{Me temo que no comprendo tu idioma. ::se inclina:: Buenos días.}
{112}{}{¡Adiooos!}
{113}{}{Soy el Dragón, amigo. Lucho contra la opresión y mi enemigo, Lo Pan, quien desea controlar esta ciudad. Lucho, y enseño a otros a luchar.}
{114}{}{¡Enséñame!}
{115}{}{G-gracias.}
{116}{}{Empecemos entonces.}
{117}{}{[HECHO]}
{118}{}{::Te mira atentamente:: Creo que no usarías ese conocimiento para el bien. Buenos días.}
{119}{}{¡Grrr!}
{120}{}{Por favor, excusa mi rudeza. No puedo hablar contigo ahora mismo.}
{121}{}{¡Duhhh... vale!}
{122}{}{Era Lo Pan. Es mi peor enemigo y mi rival. Si él triunfa y me vence, temo por el bien del pueblo.}
{123}{}{Las personas son ovejas. Deberías servirte a ti mismo.}
{124}{}{Entonces tú debes triunfar.}
{125}{}{Ya veo. Tengo más preguntas.}
{126}{}{¿Realmente crees eso? Entonces tal vez deberías tratar con Lo Pan. Buenos días.}
{127}{}{[HECHO]}
{128}{}{Debo, sí. Pero me temo que estamos demasiado igualados. Incluso estamos igualados en nuestros seguidores. Hará falta una persona que desequilibre la balanza.}
{129}{}{Yo soy esa persona.}
{130}{}{Ya veo. Bueno, tengo más preguntas.}
{131}{}{Ya veo. Bueno, hasta luego.}
{132}{}{¿Lo eres? Tal vez deberíamos probarte. Sólo aceptaré a quien venza en un combate honesto.}
{133}{}{Oye, él va a morir de una forma u otra. ¿Qué diferencia hay?}
{134}{}{Me parece justo. ¿Cómo funciona esta prueba?}
{135}{}{Oh. Bien, en tal caso, he de irme.}
{136}{}{¡Aquellos que luchan sin honor no son mejores que los animales!}
{137}{}{De acuerdo, Pollyanna. Relájate.}
{138}{}{Yo lo llamo lucha inteligente. "Honor" es una palabra inventada para glorificar a los asesinos.}
{139}{}{Comprendo. Tengo más preguntas.}
{140}{}{Vaaaale. Nos vemos.}
{141}{}{Primero determinamos si quieres que esta lucha sea hasta el final, o una prueba de tus habilidades contra las mías.}
{142}{}{Hasta el final. Puedo contigo.}
{143}{}{Una prueba de habilidad. No quiero matarte.}
{144}{}{Ni una cosa ni la otra. Olvídalo.}
{145}{}{No eres el adecuado para esta tarea. Adiós.}
{146}{}{[HECHO]}
{147}{}{¿Eso crees? La guerra y la lucha parecen inevitables. Quizá sería mejor que luchásemos con reglas y códigos que ceder a la destrucción misma. }
{148}{}{Yo venzo de cualquier forma que pueda.}
{149}{}{Si tenemos que luchar, deberíamos luchar por la supervivencia. Si alguien trata de matarme, me defenderé por todos los medios posibles.}
{150}{}{Hm. Tienes razón. Bueno, tengo más preguntas.}
{151}{}{Sí, de acuerdo. Adiós.}
{152}{}{Muy bien. Entremos en el cuadrilátero y luchemos hasta que uno de los dos no pueda seguir moviéndose.}
{153}{}{[Atacas ya, con armadura y armas]}
{154}{}{[Entras en el cuadrilátero, dejas a un lado armadura y armas, y luchas mano a mano]}
{155}{}{Ah, un guerrero. Te enfrentaré a mis hombres para ver cómo te portas. Empecemos.}
{156}{}{[COMENZAR]}
{157}{}{Sin embargo, en un entorno de combate formalizado, no puedes negar que has entrado en esta arena por tu propia elección. Una vez has entrado así, ¿no deberías acatar sus reglas?}
{158}{}{Sí, probablemente. Pero en una situación de vida o muerte, debes hacer cualquier cosa por sobrevivir.}
{159}{}{No, creo que no.}
{160}{}{Tienes razón. De acuerdo entonces. Si deseas combatir a Lo Pan, ¿lo harás sin armas o armaduras? Si te vamos a pedir ayuda en esto, queremos que cumplas nuestras reglas.}
{161}{}{Sí, lo haré a tu manera.}
{162}{}{No. Olvídalo.}
{163}{}{Excelente. Entonces, veamos si tus habilidades son lo suficientemente buenas como para combatir a Lo Pan.}
{164}{}{Vamos.}
{165}{}{Ahora mismo no. Volveré más tarde.}
{166}{}{Soy el Dragón, protector del pueblo y enemigo jurado de Lo Pan. Él y yo somos los últimos maestros de nuestro estilo de lucha.}
{167}{}{A mí no se me da mal el combate mano a mano. ¿Quieres darme una oportunidad?}
{168}{}{Eso es interesante. Debe de ser gratificante. Tengo más preguntas.}
{169}{}{Gracias. Adiós.}
{170}{}{Has intentado deshonrar a mi pueblo, así que ahora debo matarte. Lamento hacerte daño mientras mueres.}
{171}{}{[HECHO]}
{172}{}{No hables conmigo, oveja de la Hubología. No trato con los de tu clase.}
{173}{}{[HECHO]}
{174}{}{Tienes el honor de un cerdo y la moral de un pez pulmonado. No deseo asociarme contigo.}
{175}{}{[HECHO]}
{176}{}{Tienes unas habilidades de combate realmente asombrosas. ¿Combatirás a Lo Pan?}
{177}{}{Sí. Iré ahora mismo.}
{178}{}{En realidad no es mi lucha.}
{179}{}{Desde luego. Pero tengo algunas preguntas.}
{180}{}{Entiendo. Si cambias de opinión, sabes dónde encontrarlo. Dile simplemente que vas en el nombre del Dragón.}
{181}{}{Correcto. Tengo unas preguntas.}
{182}{}{Err... de acuerdo. Adiós.}
{183}{}{He vuelto recientemente de una misión honorable. Nos sentimos fortalecidos esta noche.}
{184}{}{Genial. Tengo unas preguntas.}
{185}{}{Genial. Adiós.}
{186}{}{¡Lo Pan está muerto! He de agradecértelo a ti, estoy seguro. Ahora, sin duda mi escuela conducirá nuestro estilo de lucha hacia el futuro.}
{187}{}{Genial. Tengo unas preguntas.}
{188}{}{Genial. Adiós.}
{189}{}{Tu kung-fu no es bueno aquí.}
{190}{}{Te venceré algún día, Dragón.}
{191}{}{Estaré esperando por ti.}
{200}{}{El Dragón detecta tu avance y te escurres de él.}
{201}{}{Un ladrón no tiene honor entre los Shi. Vete ahora.}
{202}{}{Te advertí que te fueras. Ahora lo pagarás.}
{203}{}{Parece que necesitas más de mi entrenamiento.}
{204}{}{Las lecciones son algo más que algo físico, saltamontes. Considera esto y vuelve mañana.}
{205}{}{Soy el maestro Ziggy, tu prueba final.}
{206}{}{Soy Zurak. Prepárate.}
{207}{}{Soy Jimmy. Prepárate.}
{208}{}{Soy Herb. No llegarás más lejos.}
{209}{}{Soy Jobe. Es hora de que seas vencido.}
{210}{}{Soy el maestro Rube. Estás acabado.}
{211}{}{¡LUCHA!}
{212}{}{El entrenamiento sigue en tu futuro.}
{213}{}{¡Y allá vamos!}
{214}{}{Has vencido al Dragón en combate mortal. A pesar de ser una lucha justa, su pérdida será sentida por muchos.}
{215}{}{Ya ha derrotado a mis hombres, y pasado mi prueba. Estás listo para luchar contra Lo Pan.}
{216}{}{Tus habilidades sólo avanzarán con su uso. Ya no puedo ayudarte en tu aprendizaje.}
{217}{}{Empecemos. Sigue mis indicaciones.}
{218}{}{El entrenamiento se realiza durante el día.}
{219}{}{El Dragón es muy bueno, pero has aprendido bien.}
{220}{}{Ya has derrotado a mis hombres. Nadie más desea desafiarte.}
{221}{}{Incluso aunque no lo sabías, has ayudado a nuestra causa al eliminar a Lo Pan. Tienes nuestro agradecimiento.}
{222}{}{Fue un placer. Adiós.}
{223}{}{No hay de qué. Adiós.}
{224}{}{No hay de qué. ¿Puedo hacerte una pregunta?}
{225}{}{No hay qué. ¿Hago pregunta?}
{226}{}{¡GANAS!}
{227}{}{¡PIERDES!}
{228}{}{¡Siguiente oponente!}
{230}{}{En primer lugar, tendrás que demostrar que puedes hacerlo. Te enfrentaré a cinco de mis luchadores: uno cada vez. Si los derrotas, entonces encararás la prueba final.}
{231}{}{¿Qué es eso?}
{232}{}{Suena a demasiados problemas. Adiós.}
{233}{}{Serás probado en contra de mi aprendiz elegido. Sin embargo, ninguna de estas peleas será a la muerte.}
{234}{}{De acuerdo, hagámoslo.}
{235}{}{Puedes encárgate de Lo Pan tú mismo.}
{236}{}{[El Dragón te estudia] Lamentablemente no puedo permitir que alguien con tu nivel de habilidad se hiera a sí mismo.}
{237}{}{Vale, pero ¿puedo preguntarte algo más?}
{238}{}{Bien. Adiós.}
