{100}{}{Ves a un fornido Shi que parece lleno de conocimiento.}
{101}{}{Ves a Ken Lee, consejero del Emperador.}
{102}{}{Ves a un fornido Shi con gafas y una media sonrisa.}
{103}{}{¿Qué se te ofrece, amigo?}
{104}{}{¿Qué quieres?}
{105}{}{¿Qué puedo hacer por ti?}
{106}{}{¿Tú?}
{107}{}{¿Quién eres?}
{108}{}{¿Qué es este lugar?}
{109}{}{Estoy buscando a unos tribales perdidos.}
{110}{}{Necesito combustible.}
{111}{}{Me gustaría hablar con el Emperador.}
{112}{}{Los Hubologistas me han asignado para matar al Emperador.}
{113}{}{Nada. Gracias. Adiós.}
{114}{}{Soy Ken Lee, consejero del Emperador. Y tú, amigo mío, parecer ser un ingenuo, así que recuerda esto: si buscas al Enclave, entonces debes usar el petrolero Poseidon para ello. Necesitarás combustible para él. Tienes mi bendición.}
{115}{}{¡G-gracias!}
{116}{}{Soy Ken Lee. Soy el consejero del Emperador. El Emperador me aconseja no hablar contigo, así que no lo haré. Buenos días, bobo.}
{117}{}{¡Grrr!}
{118}{}{Ahh, viajero, no puedo ayudarte. Tal vez puedes encontrar la respuesta a tu búsqueda de otra forma. Buenos días.}
{119}{}{¡Nuevos días!}
{120}{}{Soy Ken Lee. Consejero del Emperador de los Shi. Doy luz a la sabiduría del Emperador. ¿Y quién eres tú?}
{121}{}{Me gustaría ver al Emperador.}
{122}{}{Soy}
{123}{}{A mí me pareces un lacayo sobredimensionado.}
{124}{}{Nadie importante. Adiós.}
{125}{}{Este es el Palacio de Acero del Emperador. El corazón de Ciudad-Shi.}
{126}{}{¿Y dónde está el Emperador?}
{127}{}{¿Qué clase de investigación llevas a cabo aquí?}
{128}{}{¿Cuál es la historia de este lugar?}
{129}{}{Ya veo. Hasta luego.}
{130}{}{Si deseas ver al Emperador entonces tendrás que darme tu propio nombre.}
{131}{}{Oh. De acuerdo. Soy}
{132}{}{Desde luego. Mi nombre es}
{133}{}{Sí.}
{134}{}{Olvídalo.}
{135}{}{No a todo el mundo se le concede la oportunidad de ver al Emperador. Primero hay que demostrar valía. ¿Estás dispuesto a probar la tuya?}
{136}{}{Sí.}
{137}{}{No. Ya he hecho suficientes pruebas en los últimos meses como para el resto de mi vida.}
{138}{}{No creo que el Emperador quiera verte. Se me ha dicho que prohiba la entrada a todos aquellos que me ofenden o apestan a maldad. Para ti son ambas cosas, viajero. Buenos días.}
{139}{}{[HECHO]}
{140}{}{Los insultos no te llevarán a ningún lado, salvo al exterior del Palacio de Acero. Controla tu lengua.}
{141}{}{Hazlo tú.}
{142}{}{Bien.}
{143}{}{El Emperador se mantiene alejado de las miradas indiscretas. Como es mi trabajo actuar como pantalla del Emperador, ni puedo ni te diré dónde está.}
{144}{}{Tengo más preguntas.}
{145}{}{Adiós.}
{146}{}{Investigamos lo que cambiará el mundo. Para más respuestas a tus preguntas, deberías buscar al doctor Wong Yi Tze. }
{147}{}{Lo haré. Y tengo más preguntas.}
{148}{}{Lo haré. Adiós.}
{149}{}{Fuimos los supervivientes del naufragio de un submarino. Cuando encallamos, extrajimos el metal del submarino para crear el Palacio. Algunos no creen esto.}
{150}{}{Hm. Casi parece como si estuvieras reprendiendo a alguien.}
{151}{}{Ya veo. Gracias. Adiós.}
{152}{}{¡Ah, sí! He visto algunas de tus películas. Sin embargo, seguramente ese no es tu auténtico nombre...}
{153}{}{Desde luego que lo es.}
{154}{}{No. Mi verdadero nombre es }
{155}{}{Ese es el único nombre que necesitas, anciano.}
{156}{}{Eso va a ser imposible. Buenos días.}
{157}{}{[HECHO]}
{158}{}{Sin duda, me tienes que valorar mejor. Sé cómo funciona el "negocio". He viajado a Nuevo Reno antes.}
{159}{}{Está bien, mi nombre es }
{160}{}{¡Ese es mi nombre verdadero! ¡Y ahora déjame hablar con el Emperador!}
{161}{}{Excelente. Esto es lo que necesito de ti: hay una pequeña base militar al norte de aquí, llamada Navarro. Allí hay numerosos vertibirds. Necesitamos esquemas y planos para fabricar algunos de ellos nosotros mismos. Consigue esto y podrás ver al Emperador.}
{162}{}{Me parece bien.}
{163}{}{Olvídalo.}
{164}{}{¿Reconsiderarás pasar nuestra prueba?}
{165}{}{No.}
{166}{}{Oh, está bien. Lo haré.}
{167}{}{¿Tribales perdidos? No he escuchado nada sobre eso. Tal vez el Emperador podría saber algo sobre ellos.}
{168}{}{Tengo más preguntas.}
{169}{}{Gracias. Adiós.}
{170}{}{Debes completar una segunda prueba: los Hubologistas son nuestros enemigos. Su líder, AHS-9, ha estado secuestrando y lavando el cerebro a nuestros hijos. Mátalo por el bien de los Shi y te diré cómo hablar con el Emperador.}
{171}{}{Dalo por muerto.}
{172}{}{No, creo que no.}
{173}{}{¿No? Eso me entristece, pero lo comprendo. Mucha suerte en tu búsqueda. Si cambias de opinión, ya sabes dónde encontrarme.}
{174}{}{Desde luego. Tengo más preguntas.}
{175}{}{Sí. Adiós.}
{176}{}{Estoy ansioso por ver el resultado de tu intento. Buenos días.}
{177}{}{Buenos días.}
{178}{}{¿Reprendiendo a alguien? Cualquier tonto que hubiera investigado un poco podría ver que la base misma de Ciudad-Shi son los restos de este submarino. Parece inútil discutir con quienes afirman que no hay un submarino.}
{179}{}{Eso es muy ecuánime por tu parte.}
{180}{}{Ciertamente lo es. Y trato con esa gente a diario. ¡Ay!}
{181}{}{En fin, tengo más preguntas.}
{182}{}{Sí, pobre de ti. Adiós.}
{183}{}{Ciertamente eres digno merecedor de nuestro combustible. Creo que te puedo confiar nuestros secretos. En la estancia de atrás comprobarás que el campo de fuerza que bloquea el acceso a la computadora principal está desconectado. Introduce la contraseña "CSPDMSHR-Shih-huang-ti-X9372" y estarás conectado a la Computadora Emperador. El Emperador podrá dirigir nuestro combustible a donde lo necesites.}
{184}{}{Gracias.}
{185}{}{¡Guardias! ¡El enemigo está entre nosotros! ¡Guardias!}
{186}{}{¿Realmente lo tienen? Quizá te gustaría cambiar las tornas con ellos? Puedo prometerte nuestra ayuda si aceptas matar a AHS-9. }
{187}{}{Dalo por muerto.}
{188}{}{No.}
{189}{}{Excelente. Espero oír noticias de tu éxito pronto.}
{190}{}{Lo harás. Tengo más preguntas.}
{191}{}{Lo harás. Adiós.}
{192}{}{En ese caso entonces, sólo puedes ser un enemigo. Buenos días.}
{193}{}{Buenos días.}
{194}{}{Con la muerte de AHS-9, el Grande y Terrible, los Hubologistas no suponen una amenaza para nosotros y nuestras investigaciones. Bien hecho. Tienes nuestra gratitud. ¿Te gustaría hablar con el Emperador?}
{195}{}{Sí.}
{196}{}{Ahora mismo no. Aunque tengo otras preguntas para ti.}
{197}{}{Has demostrado ser un amigo de los Shi. Creo que te puedo confiar nuestros secretos. En la estancia de atrás comprobarás que el campo de fuerza que bloquea el acceso a la computadora principal está desconectado. Introduce la contraseña "CSPDMSHR-Shih-huang-ti-X9372" y estarás conectado a la Computadora Emperador. Espero que te resulte útil.}
{198}{}{¿El Emperador es una COMPUTADORA?}
{199}{}{Lo tengo. Gracias.}
{200}{}{Sí. Almacena nuestra historia, nuestras investigaciones, y las posibilidades de proyectos futuros. Es mucho mejor que cualquier humano falible... aunque moderamos sus sugerencias con nuestro conocimiento de la naturaleza humana.}
{201}{}{Ya... veo. Bien, gracias por tu tiempo.}
{202}{}{Nuestros espías informan que le has entregado los planos del vertibird a los Hubologistas. Róbaselos para nosotros y serás recompensado.}
{203}{}{Como quieras. Tengo algunas preguntas.}
{204}{}{Ni hablar.}
{205}{}{Gracias por los planos del vertibird, viajero. ¿Qué puedo hacer por ti?}
{206}{}{Tengo preguntas.}
{207}{}{Um... nada.}
{208}{}{Una vez hayas conseguido los planos del vertibird, entrégaselos al doctor Wong Yi Tze. Él les dará buen uso.}
{209}{}{De acuerdo. Tengo otras preguntas.}
{210}{}{Vale. Adiós.}
{211}{}{. Me gustaría ver al Emperador.}
{212}{}{.}
{213}{}{Recuerda, debes llevarle los planos al doctor Wong Yi Tze.}
{214}{}{Has vuelto a insultarme de nuevo. Se acabó.}
{215}{}{Como ya te he dicho, necesito saber tu nombre.}
{216}{}{Está bien, es }
{217}{}{¡Olvídalo, idiota!}
{218}{}{Recuerda, el Emperador espera la muerte de AHS-9.}
{219}{}{Lo siento. Pero no puedo ofrecerte el combustible que tenemos. ¿Tal vez si hablases con el Emperador?}
{220}{}{¿Cómo lo consigo?}
{221}{}{¿Puedo al menos hacerte una pregunta?}
{222}{}{Me gustaría poder ofrecerte nuestro combustible, pero desafortunadamente nuestros almacenes están vacíos. De alguna manera, su contenido se desvió a los Hubologistas. Es posible que seas capaz de encontrar a alguien que lo recupere para nosotros.}
{223}{}{¿Ahora ya puedo ver al Emperador?}
{224}{}{Te recuerdo respetuosamente que a menos que le entregues los planos del vertibird al doctor Wong Yi Tze, no te puedo permitir el acceso al Emperador. Espero que lo entiendas.}
{500}{}{Vete de inmediato o llamaré a los guardias.}
{501}{}{Vete ahora. Este es tu segundo aviso.}
{502}{}{Este es tu último aviso.}
{1430}{}{El Emperador permanece oculto a los ojos indiscretos. Es mi trabajo actuar como la pantalla del Emperador. Sin embargo, has demostrado ser un amigo de los Shi. Creo que te puedo confiar nuestros secretos. En la estancia de atrás comprobarás que el campo de fuerza que bloquea el acceso a la computadora principal está desconectado. Introduce la contraseña "CSPDMSHR-Shih-huang-ti-X9372" y estarás conectado a la Computadora Emperador. Espero que te resulte útil.}
{2001}{}{Ya... veo. Bien, gracias por tu tiempo. Tengo un poblado que rescatar.}
