{100}{}{Ves a un necrófago particularmente descuidado.}
{101}{}{Ves a Festus, el supervisor de la central nuclear.}
{102}{}{Ves a un necrófago que parece abatido, con aspecto particularmente rancio. Huele como una
 herida infectada.}
{110}{}{¿Eres lo más estúpido que pudieron conseguir? Ja, ja, ja.}
{111}{}{¿Eres tonto o qué? Ja, ja, ja. Te pareces a uno de esos de Ciudad Refugio.}
{112}{}{Bien, eres bastante estúpido, ¿no? Deberías dirigirte a Ciudad Refugio.}
{113}{}{Tengo muchas cosas importantes que hacer. ¿Por qué no vuelves a Ciudad Refugio, que es a donde perteneces?}
{114}{}{Ja, ja, ja. Menuda mirada de estúpido la tuya.}
{120}{}{Muy buenas. Soy Festus. Dirijo todo el reactor. Sin mí, la ciudad al completo estaría
 perdida. Soy un tipo muy ocupado. Me hacen trabajar demasiado por aquí.}
{121}{}{Tengo mucho que hacer aquí. Desde luego, podría tomar un descanso. Pero, como ya sabrás, nadie más puede manejar
 la central nuclear. Controlo el poder del átomo, ¿sabes? Es algo que agotaría a cualquiera.}
{122}{}{¿Qué haces aquí?}
{123}{}{Por lo que sé, el reactor no funciona demasiado bien. ¿Es cierto?}
{124}{}{¿Por qué pareces -y hueles- como si te estuvieras cayendo a pedazos?}
{125}{}{Bien, no quiero abusar de tu precioso tiempo. Seguiré mi camino. Adiós.}
{130}{}{Estoy seguro de que tengo al reactor funcionando de maravilla ahora. Mira que soy bueno.}
{131}{}{El reactor está funcionando bastante bien ahora, cierto. Aún se podría afinar un poquito, pero diría que de todas formas es un buen trabajo.}
{132}{}{¿Más trabajo? ¿Qué quieres decir?}
{133}{}{Bueno, nada es perfecto. Adiós, Festus.}
{141}{}{Bien, superviso la central nuclear. En realidad, diría que lo dirijo todo yo solo.}
{142}{}{Pues sí, yo lo dirijo todo... en calidad de supervisor. Todo lo hago yo. Sería imposible si
 no fuera tan condenadamente bueno en ello. Es una bendición, desde luego...}
{143}{}{¿Todo lo haces tú? ¿Entonces qué está haciendo toda esa gente en las otras estancias?}
{144}{}{Entonces debes saber bastante sobre la energía nuclear.}
{145}{}{Bien, no quiero distraerte de tu trabajo. Adiós.}
{150}{}{Derrochadores. Todos ellos. No entienden realmente lo que hay que hacer. Sólo hacen bulto. Me fastidia que crean saber algo sobre centrales nucleares. Coño, si no fuera
 por mí...}
{151}{}{Hmm. ¿Qué dijiste que hacías aquí?}
{152}{}{Ah, sí. Bueno, será mejor que me vaya. Adiós.}
{160}{}{¿Que si sé bastante sobre energía nuclear? Bueno, casi la inventé. Sé más sobre energía nuclear que cualquier persona
 viva. si se trata de energía nuclear, yo soy tu hombre.}
{161}{}{Hmm. ¿Qué dijiste que hacías aquí?}
{162}{}{Ah, sí. Bueno, será mejor que me vaya. Adiós.}
{170}{}{Verás, desde luego yo dirijo todo este lugar. Es bastante difícil. Pero tengo muchos años de
 experiencia. Soy todo un profesional cuando se trata de dirigir centrales nucleares.}
{171}{}{Debes de ser muy bueno en tu trabajo.}
{172}{}{Estoy seguro de que lo eres. Eh, será mejor que me marche ya. Adiós.}
{180}{}{Casi todo el mundo cree que es sencillo. Se piensan que cualquiera puede manejar un reactor atómico. Pero no es algo
 para gente inexperta o débiles de corazón. ¡Yo controlo el poder el átomo aquí!}
{181}{}{Estoy impresionado.}
{182}{}{Vale, dejémoslo aquí. Adiós.}
{190}{}{Estaría bien tener algo de ayuda. Pero, verás, nadie más está cualificado para hacer lo que yo.
 Ni siquiera entienden los conceptos básicos de lo que hago.}
{191}{}{¿Cómo podría nadie pretender seguirte el ritmo? Estás por encima de todo el mundo.}
{192}{}{Eres realmente especial, no hay duda de ello. Adiós.}
{200}{}{Sabes que lo soy. Creo que tú entiendes realmente este tipo de cuestiones. Si no estuviera tan ocupado por aquí
 dirigiría todo Gecko. Y déjame decirte que lo haría muy bien.}
{201}{}{¿También dirigirías la ciudad?}
{202}{}{¡Arrrrrgh! Me marcho. Eso hago. No intentes detenerme. ¡Adiós!}
{210}{}{Bueno, no habría que comerciar con el uranio de Broken Hills. Lo intercambiaríamos
 por energía, en vez de ello. Ellos podrían dirigir su ciudad usando el poder del átomo.}
{211}{}{¿No tendrías que supervisar líneas de alimentación a través de millas y millas de peligroso desierto?}
{212}{}{¿Hueles eso? ¿Eso que apesta? Será mejor que me vaya. Adiós.}
{220}{}{Bueno, supongo que sí. Entonces les haríamos comprarnos baterías gigantes. Sí, eso es lo bonito de todo
 esto. Entonces ellos también tendrían que comprarnos las baterías. Y eso sólo sería el comienzo: tengo otros grandes
 planes, como...}
{221}{}{¿También eres un político? Es increíble que tu talento abarque tantos campos.}
{222}{}{¿Algo se está pudriendo por aquí? Creo que necesito algo de aire fresco. Adiós.}
{230}{}{Sólo soy polifacético. En serio, soy muy bueno en todo lo que intento. Rara vez hay alguien mejor.
 Por supuesto, prefiero dirigir la central nuclar. Pero, si quisiera, podría hacer
 cualquier cosa.}
{231}{}{No me puedo creer que haya alguien en Gecko que no aprecie tu auténtico valor. Voy a contárselo
 ahora mismo. Adiós.}
{232}{}{He de escapar. Desvanecerme. Marcharme.}
{240}{}{¿Que te trae a esta parte de mi reactor nuclear?}
{241}{}{Bien, tengo una pieza que puedes usar para reparar el reactor.}
{242}{}{Eh, sólo estaba mirando. Adiós.}
{250}{}{Verás, en realidad no estoy seguro de que esa sea la pieza correcta. Quizá deberías llevarla de vuelta
 a Ciudad Refugio para comprobarlo. No creo que pueda ayudarte con esto, después de todo.}
{251}{}{Estoy seguro de que es la pieza adecuada. Tengo mucha confianza en tu capacidad.}
{252}{}{Supongo que tienes razón. Será mejor que encuentre otra forma de instalar la pieza.}
{260}{}{No creo que a esa gente de Ciudad Refugio les gustemos demasiado. No instalaría esto
 pensando que pudiera ser una trampa. ¡Quizás parece la pieza adecuada, y realmente es una bomba!
 No puedes engañarme tan fácilmente. No voy a instalar esa cosa.}
{261}{}{Con tu pericia técnica, si fuera una bomba, ya lo habrías notado. Por favor, limítate
 a instalarla.}
{262}{}{Supongo que tienes razón. Será mejor que encuentre otra forma de instalar la pieza.}
{270}{}{De acuerdo, aquí estoy. Pero sigo sin estar seguro de que esa sea la pieza adecuada, o de que no se trate de algún tipo
 de trampa. Verás, soy demasiado valioso como para correr riesgos. Tal vez debería dejar que algún otro hiciera esto...
 más tarde... mucho más tarde.}
{271}{}{Se tiene que hacer ahora. Y tú eres el único que puede hacerlo bien. ¡Venga, todo Gecko
 depende de ti!}
{272}{}{Supongo que tienes razón. Será mejor que encuentre otra forma de instalar la pieza.}
{300}{}{Bien, desde luego utiliza un montón de uranio. Y pierde otro montón. Verás, pedí a alguien para arreglarlo,
 pero nadie me escucha.}
{301}{}{He oído que está filtrando radiación al agua subterránea. ¿Eso es cierto?}
{302}{}{Creía que tú eras el experto. ¿Por qué no lo arreglas? ¿No es precisamente lo que haces aquí, de todas formas?}
{310}{}{Bien, es posible, pero no creo que vaya a hacer daño de ningún tipo. Sucede bajo tierra,
 después de todo.}
{311}{}{Creo que te equivocas. Ciudad Refugio se ha estado quejando de que vuestra central nuclear está
 contaminando su agua con radiación.}
{312}{}{Bueno, si tú lo dices. Adiós.}
{320}{}{Imposible. Nadie sabría más sobre ello que yo. Sólo están buscando a alguien para culparle
 de sus problemas. Ni siquiera utilizamos el mismo acuífero.}
{321}{}{Pareces estar seguro. Pero ellos también lo estaban.}
{330}{}{Bueno, son un montón de novatos cuando hablamos de energía nuclear. Aquí el verdadero experto soy yo.
 Puedo asegurarte que lo que yo digo va a misa. Aunque ya no haya misas.}
{331}{}{En fin, supongo que sabes de lo que estás hablando. Adiós.}
{332}{}{No estoy tan seguro como tú. Adiós.}
{340}{}{¿Te sobra un regulador hidroeléctrico magnetosférico?}
{341}{}{¿Y ya sabes lo que es?}
{342}{}{Desde luego. ¿Listo para instalarlo?}
{350}{}{¿Sorprendido? Ya te dije que lo sé todo sobre centrales nucleares. Deberías haberme escuchado.}
{351}{}{Bueno, pues ya que sabes lo que es, sabrás cómo instalarlo.}
{352}{}{Creo que ya te he escuchado demasiado. Adiós.}
{360}{}{Por supuesto que sí. Es algo sencillísimo para alguien de mi experiencia y talento. Me
 destetaron con reguladores magnetosféricos, ¿sabes?}
{361}{}{Pues qué bien. ¿Lo puedes instalar por mí?}
{370}{}{Bien, supongo que podría instalarlo. Ciertamente soy el único que puede hacerlo bien.
 Instalar un regulador hidroeléctrico magnetosférico es bastante complicado.}
{371}{}{Aquí está el regulador. Sabía que podía contar contigo.}
{372}{}{Pensándolo bien, creo que será mejor que encuentre otra forma de hacerlo. Adiós.}
{380}{}{Supongo que podría instalarlo. Pero, verás, instalar un regulador hidroeléctrico magnetosférico
 es bastante complicado. Y peligroso. No es que tema por mí, pero, ¿quién podría dirigir la central
 nuclear si algo me sucediera? Lo siento, pero no puedo ayudarte.}
{381}{}{Debería haber sabido que te acobardarías. Adiós.}
{390}{}{Ahora mismo no puedo ayudarte. Estoy demasiado ocupado.}
{391}{}{Vuelve la próxima semana. Tal vez tenga tiempo para entonces.}
{392}{}{Eh, de todos modos tienes la pieza equivocada. Sí, eso es.}
{393}{}{Lo siento, estoy demasiado ocupado para ayudarte.}
{394}{}{No puedo defraudar a Gecko poniéndome a mí mismo en peligro.}
{400}{}{Oh, sí. Je, je. Claro, es la pieza adecuada. Es sólo, eh, un modelo más primitivo del que
 suelo usar. Eso es todo.}
{401}{}{Bien. Entonces adelante e instálalo.}
{410}{}{Supongo que harían algo mejor que intentar engañarme a mí con una bomba. Estoy seguro de que saben exactamente
 con quién están tratando.}
{411}{}{A menudo hablaron de ti en Ciudad Refugio. Por lo general, en un tono reverencial. Y ahora, limítate a instalar
 la puta pieza.}
{420}{}{De acuerdo, ya está. ¡Oye! Lo hice. Realmente soy bueno.}
{421}{}{Maldita sea, soy bueno.}
{422}{}{Fue difícil, pero lo hice. Soy un héroe.}
{423}{}{Merezco un aumento de sueldo por el trabajo que he hecho.}
{424}{}{Gecko me debe mucho ahora.}
{425}{}{¿Me viste ahí fuera? Ni siquiera vacilé un segundo.}
{430}{}{¿Qué quieres?}
{431}{}{He oído que tú te encargas de los pedidos de piezas y necesito una.}
{432}{}{Sólo me preguntaba qué haces aquí. }
{440}{}{¿Tú? ¿Qué es lo que tú necesitas?}
{441}{}{Bien, los chicos de esa otra habitación la necesitan. Pero les dije que quería conseguirla yo sólo
 para poder verte en acción.}
{442}{}{Sólo necesito una. Venga, pórtate como un colega. Dame sólo una. ¿De acuerdo?}
{443}{}{Creo que será mejor que me des una. Trabajando en una central nuclear, a veces las personas tienen accidentes.
 ¿Me comprendes?}
{444}{}{Necesito un for... oye, ¿eso que parpadea en rojo es un activador Fershlubiner como-se-llame?}
{450}{}{Bien, de acuerdo. Aquí está tu formulario de solicitud de piezas. Supongo que tienes tus razones para necesitarlo.}
{451}{}{Bien, de acuerdo. Aquí está tu… ¿eh? ¿Dónde he puesto ese maldito papel? Tiene que estar por alguna parte… Hmm, supongo
 que no puedo encontrarlo ahora. Pero aparecerá.}
{452}{}{Gracias. Adiós.}
{453}{}{Oh, en fin. Entonces quizá vuelva más tarde. Adiós.}
{460}{}{No me importa lo que quieras. Esos formularios de solicitud de piezas sólo son para usos oficiales. Se confían
 sólo al personal clave. Pero eso yo los tengo. ¿Me captas? Sólo personal clave. }
{461}{}{Que sí, que te capto. Adiós.}
{462}{}{Bien, ya recibirás lo tuyo. Tal vez hoy no, pero pronto. Adiós.}
{470}{}{Eh, bueno, se supone que debe ser así. Tengo mucho e importante trabajo que hacer. Si eso es todo
 lo que querías...}
{471}{}{Bueno, en realidad necesito un formulario de solicitud de piezas.}
{472}{}{Después de todo, no necesito nada más. Adiós.}
{480}{}{¿Qué quieres decir? Oh, en fin, supongo que he estado trabajando demasiado últimamente. En realidad
 no he tenido tiempo de cuidar de mí mismo como debería. Tal vez la radiación sólo me afecta de forma un
 poco diferente.}
{481}{}{Eh, bueno... tal vez deberías considerar el ducharte o algo, por el bien de tu apariencia.}
{490}{}{Sí, creo que debo hacerlo. Pero cada vez que me ducho, se me cae un montón de piel y todas las costras se
 abren. Y otra cosa, mis uñas se desgarran y...}
{491}{}{¡Espera! ¡Alto! Creo que ye he oído más que suficiente. Eh, retrocedamos un poco.}
{500}{}{Festus se marcha y después vuelve. Aún lleva la pieza.}
{510}{}{[HECHO]}
{520}{}{Festus te devuelve la pieza.}
{530}{}{Festus se marcha y después vuelve. Parece muy contento por algo.}
{600}{}{Tengo un disco de datos del reactor que puede ayudarte a optimizar el reactor.}
{610}{}{De acuerdo, dámelo y veré qué puedo hacer.}
{620}{}{Aquí están.}
{630}{}{No, creo que de momento me lo voy a quedar.}
{640}{}{De acuerdo. Tiene buena pinta. Gracias por toda tu ayuda.}
{650}{}{Desde luego. No hay problema.}
{700}{}{Has convencido a Festus para que te ayude con la central nuclear.}
{800}{}{Quiero decir que ahora el reactor está funcionando, pero seguro que podría hacerlo mejor. Y me refiero a mejor pero de largo, si tuviéramos una pizca más de datos. Así que si pudieras
 conseguir los datos de optimización, cocinaríamos con gas, eh, bueno, ya sabes a qué me refiero.}
{801}{}{¿Datos de optimización? ¿De dónde podría obtenerlos?}
{802}{}{Bueno, probablemente podrías conseguir la información de la computadora central de
 Ciudad Refugio.}
{803}{}{Está bien, déjame ver lo que puedo hacer.}
{804}{}{Hmm, es una idea.}
{805}{}{Eso sólo sucederá cuando un perro de papel persiga con éxito a un gato
 de amianto por todo el infierno. Adiós, Festus.}
{806}{}{Apuesto a que un tipo listo como tú podría colarse allí y usar un
 holodisco con la información del rendimiento del reactor en la computadora central. Y después
 traer el disco de vuelta aquí. Eso sería todo. Lo haría yo mismo, pero soy demasiado
 valioso como para marcharme, incluso aunque sea sólo un rato.}
{807}{}{Odio dejar un trabajo a medio hacer.}
{808}{}{Hmm, no creo que pueda salir de aquí con eso. Lo siento, Festus. Adiós.}
{809}{}{Eso podría funcionar. Supongo que algo de mi inteligencia se te está
 contagiando. Bien, bien. Oye, deberías ir a llevárselo a un tipo llamado McClure. Por
 lo que he oído, es el único por allí que prestaría oídos algo más que los preciosos 
 ciudadanos de Ciudad Refugio.}
{810}{}{El concejal McClure es el hombre con el que tratar. De acuerdo, gracias por el consejo. Supongo entonces que
 lo haré.}
{811}{}{Dios santo, me encantaría que me encerraran en Ciudad Refugio por ser un simpatizante de mutantes. No
 gracias, Festus. Estás solo en esto. Adiós.}
{812}{}{Ese es el espíritu. Esperaba que dijeras eso. Fantástico. Tan solo usa este disco
 en la computadora central de Ciudad Refugio y después regresa aquí. Usaremos menos uranio, el
 núcleo no tendrá tantas pérdidas, y la dichosa Ciudad Refugio no tendrá ninguna razón para exterminarnos.}
{813}{}{Desde luego no quiero ver cómo destruyen Gecko. Lo haré.}
{814}{}{No creo que pueda hacerlo. Lo siento, Festus. Adiós.}
{815}{}{Por supuesto, desearía perder mi tiempo e ir a hacerlo yo mismo, pero no puedo. Todo lo que puedo decir es
 gracias, muchacho. Nos harás un gran favor. (sniff, sniff) Hazme sentir
 orgulloso.}
{816}{}{Bueno, será mejor marcharse. Adiós, Festus. Volveré con los datos que necesitas lo
 antes posible.}
{817}{}{No haraganees por aquí. Consigue esos datos.}
{818}{}{No te quedes ahí parado. El reactor no va a funcionar para siempre.}
{819}{}{Muévete y consigue esos datos de optimización, como dijiste que harías.}
{820}{}{Tendremos tiempo de sobra para charlar *después* de optimizar el reactor.}
{821}{}{Ve a Ciudad Refugio y negocia con McClure lo del disco para los datos del reactor que necesitamos.
 ¿De acuerdo?}
{822}{}{Venga. Consigue ese disco de McClure.}
{823}{}{¿Ciudad Refugio? ¿Un trabajo a medio hacer? ¿Hay un hueco en eso que tienes entre ambas orejas?}
{824}{}{¡Aprisa!}
{825}{}{Gracias por conseguir los datos que necesitábamos de Ciudad Refugio para optimizar esta vieja bestia goteante.
 Eres un tipo astuto, no lo niegues, campeón. Ha sido un trabajo casi tan bueno como si lo hubiera hecho yo mismo.
 Por supuesto... si es que llegas a *terminarlo*, cojones, así que usa ese disco en el terminal de control del robot.
 ¿Me has entendido? Bien, pues a ello entonces.}
{826}{}{Bien, no quería dejar el trabajo a medio hacer. Adiós, Festus.}
{827}{}{Sí, apuesto a que lo hubieras hecho. Ulceroso charlatán. Adiós.}
{828}{}{Eres una maravilla. No hay duda de ello. Sabía que lo harías.}
{829}{}{Me has hecho sentir orgulloso.}
{830}{}{Gracias. Ahora déjame volver a mi importante trabajo.}
{831}{}{Sigue así y puede que algún día llegues a ser alguien como yo.}
{900}{}{¿Acaso no ves que estoy ocupado?}
