{100}{}{Ves a alguien que podría ser un trampero.}
{101}{}{Ves a alguien relajándose.}
{102}{}{Ves a un vecino del pueblo.}
{103}{}{Ves a un trabajador relajándose.}
{104}{}{Ves a una persona disfrutando de una bebida.}
{106}{}{Ves a los parroquianos de un bar. Parecen contentos y felices.}
{107}{}{Ves a un parroquiano. Parece sano y bien alimentado.}
{108}{}{Ves a un parroquiano hablando tranquilamente con alguien cercano.}
{109}{}{Ves a un parroquiano bebiendo tranquilamente una jarra de cerveza.}
{110}{}{Ves a unos parroquianos haciendo bromas y riéndose.}
{120}{}{Estás en la taberna equivocada, ¿no?}
{121}{}{No queremos alborotadores por aquí.}
{122}{}{Los tribales siempre traéis problemas.}
{123}{}{Siempre que no tomes demasiada agua de fuego...}
{124}{}{(murmurando) ...tengo que largarme de este pueblucho...}
{125}{}{Otro de la banda de los Dunton.}
{126}{}{¿Qué estás mirando?}
{127}{}{Muévete.}
{128}{}{Invítanos a una ronda, recién llegado.}
{129}{}{Espero que puedas aguantar el licor.}
{130}{}{No tienes pinta de caníbal.}
{131}{}{No hay habitaciones para los tuyos.}
{132}{}{Últimamente hay demasiados extranjeros.}
{133}{}{Bueno, al menos tus dientes no están afilados en punta.}
{134}{}{El barrio se está echando a perder.}
{135}{}{¿No se supone que deberías tener un hueso en la nariz?}
{136}{}{(Te mira y sacude la cabeza)}
{137}{}{(Hace un gesto grosero de forma sutil)}
{138}{}{Estoy seguro de que eres el responsable de la mutilación de ganado.}
{139}{}{Algunos de los cazadores han desaparecido y probablemente tú seas la causa.}
{140}{}{Hay hombres bicho asustando al pueblo.}
{141}{}{Hay un espíritu en un cañón al este del pueblo.}
{142}{}{¡No dejes que los espíritus te pillen!}
{143}{}{Será mejor que no se te ocurra robar nuestro ganado.}
{144}{}{No te voy a quitar el ojo de encima.}
{150}{}{Me alegra ver a alguien nuevo en el pueblo.}
{151}{}{Parece que los tribales no son tan malos después de todo.}
{152}{}{¡Invítanos a una ronda!}
{153}{}{Hola a todos.}
{154}{}{Podrías ser el hermano gemelo de Sulik.}
{155}{}{¿Has saludado a Sulik?}
{156}{}{Últimamente el negocio del trampeo marcha bien.}
{157}{}{Tiene pinta de que el tiempo va a cambiar, eso parece.}
{158}{}{Tengo un buen sitio de caza al sur de aquí.}
{159}{}{Si eres listo te alejarás de los Dunton.}
{160}{}{Si estás ansioso, ve a la Casa de Baños.}
{161}{}{Al oeste está el barrio de los tramperos, si buscas un lugar donde dormir.}
{162}{}{Bienvenido, amigo.}
{163}{}{Espero que te guste nuestra ciudad.}
{164}{}{Klamath es el mejor lugar del mundo.}
{165}{}{Me alegro de verte.}
{166}{}{(Alza su gorra hacia ti)}
{167}{}{(Te guiña el ojo)}
{168}{}{No vayas por ahí fuera de noche.}
{169}{}{Hay hombres bicho en las colinas.}
{170}{}{Uno de nuestros mejores tramperos ha desaparecido.}
{201}{}{Oh, esto seguro que me refresca el gaznate.}
{202}{}{Gracias.}
{203}{}{Mmm-mm, bien.}
{204}{}{No hay nada como la Buckner’s Best.}
{205}{}{Gracias por la cerveza.}
{206}{}{¡Hurra!}
{207}{}{Los tribales saben qué es lo mejor de la vida.}
{208}{}{Gracias.}
{209}{}{Gracias, amigo.}
{210}{}{Me hacia falta una. Gracias.}
{211}{}{¡Un millón de gracias!}
{212}{}{Prefiero tener una botella delante mío...}
{213}{}{Te lo agradezco, amigo.}
{214}{}{¡Bien!}
{215}{}{¡Sí! Lo estaba esperando.}
{216}{}{Pensaba que nunca la pedirías.}
{217}{}{Gracias, amigo.}
{218}{}{Igual que Sulik.}
{219}{}{Gracias.}
{220}{}{¡Siiii!}
