{100}{}{Ves a Monte Tres-Cartas.}
{150}{}{Ves a un anciano alto y flaco con la cara quemada por el sol. Está tan delgado que parece hecho de astillas.}
{200}{}{No sé cómo he perdido…}
{205}{}{¡Heeeey! ¡Héroe! Lo hiciste bien, muy bien.}
{215}{}{¿Dónde diablos están mis cartas? ESTABAN aquí.}
{220}{}{Tú, camarada, no pierdas el tiempo en los casinos. Ven a jugar con Monte.}
{230}{}{Monte no está disponible hoy, amigo; he perdido mis malditas cartas.}
{231}{}{(El viejo sonríe, y la piel que rodea sus ojos se arruga.) ¿Quieres jugar, amigo?}
{250}{}{¿Ponernos a qué? ¡Al juego, por supuesto!}
{260}{}{(Entregas el dinero. Monte hace un gesto afirmativo, te muestra las cartas, y las pone boca abajo, barajándolas unos segundos.)}
{280}{}{(Monte da la vuelta a la carta. Es el dos de espadas).}
{300}{}{(Entregas el dinero. Monte hace un gesto afirmativo, te muestra las cartas, luego las pone en el suelo. Al hacerlo, se guarda una bajo la palma, tan rápido que casi te lo pierdes. Entonces empieza a barajarlas unos segundos).}
{320}{}{¿QUÉ has dicho, camarada?}
{330}{}{Mira, no tengo tiempo para perdedores. Pagas con tu dinero, y tienes tu oportunidad. ¡Si
 quieres JUGAR, bien, pero si
 te vas a subir por las paredes cuando pierdas, entonces piérdete!}
{340}{}{(Entregas el dinero. Monte hace un gesto afirmativo, y pone las cartas boca abajo, barajándolas unos segundos).}
{360}{}{(Entregas el dinero. Monte hace un gesto afirmativo, te muestra las cartas, y las pone boca abajo, barajándolas unos segundos.)}
{375}{}{(Monte pone la carta boca arriba. Es la reina de corazones. Parece paralizado por la sorpresa). ¿Eh…? Je. Eh...}
{385}{}{(Monte pone la carta boca arriba. Es la reina de corazones. Parece muy sorprendido). ¿Eh…? Je...eh...}
{400}{}{(Parece dolorido) Eh… bueno, tengo algo... pero es MÁS valioso que lo que has ganado... aún así...}
{405}{}{Eh… hmnnn… depende de lo que quieras saber.}
{415}{}{Eh … bueno... mira, esto no me lo has escuchado a mí, pero apuesto por Renesco, ese gilipollas que dirige la farmacia de la parte oeste.
 No sé con seguridad si se lo vendió al chico, pero sabe algo. Esto es todo lo que diré.}
{420}{}{Eh… bueno... (parece que libra una lucha interior) ... mira, no me lo has escuchado a mí, pero si fuera tú,
 comprobaría el sótano del Desperado.}
{425}{}{(Entorna los ojos y se inclina) Yo le preguntaría al viejo Jules, en la parte delantera de la ciudad. Nada se le escapa… y
 si lo HICIERA, entonces es que tendría una mano metida en ello, ¿entiendes lo que digo?}
{430}{}{Bueno... ¿conoces a ese tal Eldridge que dirige Armas Nuevo Reno? Dice que mejora armas, pero nunca le he visto
 hacerlo. Quizá merecería la pena echar un ojo a su local... pero yo no te he he dicho nada.}
{435}{}{(Monte frunce el ceño al verte) Mira, hoy no voy a jugar más, ¿vale? Desaparece.}
{440}{}{Que no. No me desharé de ella. Punto. Es una AUTÉNTICA pieza de colección de antes de la guerra... un trocito de historia. NI HABLAR.}
{450}{}{¿Estás sordo? Ni siquiera esa cantidad me interesa.}
{460}{}{Vaya, ya no la aprecio TANTO. Es tuya, camarada. (Mira a derecha e izquierda, se agacha y se quita la
 bota. Desenrosca el talón y saca la carta de su interior). Aquí tienes. Cuídala.}
{465}{}{(Frunce el ceño) Lo que yo diga depende de lo que quieras saber. Y no va a resultarte barato.}
{475}{}{De ninguna manera voy siquiera a TOCAR el tema en Gólgota. Vete a tomar viento.}
{490}{}{(Niega con la cabeza) Ni hablar. Hablar sobre ello haría que alguien muriese, empezando conmigo. Olvídalo.}
{495}{}{Eh… bueno... eso es un montón de fichas. (Se moja los labios. Parece mantener una lucha interior.... pero la batalla es breve). Mira, esto no me lo has oído a mí...}
{500}{}{(Se burla) Quizá he oído algo, o quizá no. Di una cantidad.}
{510}{}{¡Ja! No podrías comprar ni un balde de mierda con eso. Olvídalo.}
{515}{}{Eeeeso es hablar. (sonríe maliciosamente). Mira, esto no me lo has oído a mí, pero si yo fuera tú echaría un vistazo en el sótano del Desperado, en la calle Virgin. Hay un montón de "ratas" por allí, no sé si me, ejem, explico.}
{520}{}{(Se encoge de hombros) Quizá he oído algo, o quizá no. Dime una cantidad y quizá tenga algo que decir.}
{530}{}{(Enarca las cejas) Por esa cantidad, no sé nada.}
{535}{}{Eso me parece bien… (enarca las cejas) ... Yo le preguntaría al viejo Jules, en la parte delantera de la ciudad. Nada se le escapa… y si lo HICIERA, entonces es que tendría una mano metida en ello, ¿entiendes lo que digo?}
{540}{}{(Se encoge de hombros) Escucho cosas, veo cosas. Por 200 fichas, quizá puedas obtener el beneficio de mi experiencia, ¿sabes lo que quiero decir?}
{550}{}{¿Estás sordo? HE DICHO 200 fichas, y lo decía en serio.}
{555}{}{Hecho. (Monte se inclina) Bien, ¿sabes que ese tal Eldridge dirige Armas Nuevo Reno? DICE que hace
 mejoras de armas, pero nunca le he visto hacerlo. Podrías echar un vistazo en su local... pero
  esto no me lo has oído a mí.}
{560}{}{El cementerio al sur de la ciudad. Apesta hasta hacerte perder el sentido, eso seguro.}
{565}{}{Apuesto por Renesco, ese viejo gilipollas que dirige la farmacia de la parte oeste. No sé con seguridad
 si se lo vendió al muchacho, pero sabe ALGO. (Mira a su alrededor) Y eso es todo lo que voy a decir.}
{570}{}{(Mira a su alrededor, luego se agacha y se quita la bota. Retira el talón y saca una carta... en la carta
 hay un hombre con un extraño sombrero, y lleva un garrote). ¿Te interesa? Es una genuina pieza de colección de antes de la guerra.}
