# 0. QUICK LOOK
{100}{}{Ves a Keith Wright.}

# 0. LOOK [MALE]
{150}{}{Ves a un joven delgado, pálido y con pelo rubio y fibroso. Te está mirando recelosamente.}
{151}{}{Ves a Keith Wright. Te está mirando recelosamente.}

# 1. FLOAT DIALOGUE: WARNING (WTG)
{200}{}{¿Quién eres?}
{201}{}{¿Qué quieres?}

# 2. FLOAT DIALOGUE: WARNING - KNOWS PLAYER BUT NOT MADE MAN (WTG)

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Oye, }

# 4. INTRO (WARNING) (WTG)
{230}{}{Da otro paso en dirección a esa puerta, y lo lamentarás.}

# 5. FLOAT (DAD IS DEAD) (WTG)
{240}{}{Aún no me puedo creer que papá esté muerto. Había tantas cosas que quería decirle…}

# 6. INTRO (NORMAL) (WTG)
{250}{}{Esclavista, has venido a la parte equivocada de la ciudad. Si no empiezas a dar explicaciones, vas a tener
 un montón de problemas.}
{251}{}{No te conozco, mi padre no te conoce, y si no empiezas a explicarte, ya no va a importar.}
{252}{}{¿Cómo te va, }
{253}{}{Gracias por descubrir quién mató a Richard, }
{254}{}{¿Qué quieres ahora?}
{255}{}{Mateo. ¡El Hombre es Mateo!}
{256}{}{Jabawokee Ding Dong}
{257}{}{Te alejas}
{258}{}{Estoy buscando trabajo. ¿La familia Wright ofrece algo?}
{259}{}{Estoy buscando trabajo. Chris me envió. ¿La familia Wright ofrece algo?}
{262}{}{Oye, Keith. Me encontré con tu madre.}
{263}{}{¿Puedes hablarme sobre tu hermano Richard?}
{264}{}{No importa. Lamento haberte molestado.}

# 7. RETARD (6)
{280}{}{Largo de aquí, cabeza hueca. La próxima vez que me hables, te llenaré de agujeros.}
{281}{}{Agujeros, agujeros, agujeros en mis calderos}
{282}{}{Shamma Lamma DING DONG}

# 8. HOLES HOLES HOLES IN MY SOLES (7)
{290}{}{¡Sal de aquí! ¡No te lo vuelvo a advertir!}
{291}{}{A-quí, mi pirulí, y montones de din-din}
{292}{}{¡DING DONG! ¡DING DONG!}

# 9. A-GIN, MY SHIN, LOTS OF DIN-DIN (8)
{300}{}{Te lo advertí, imbécil…}
{301}{}{¿Eh?}

# 10. WHO ARE YOU? (6, 11)
{310}{}{Soy Keith Wright, de la familia Wright. Y ahora, ¿vas a decirme qué haces aquí?}
{312}{}{Chris me dijo que echara un vistazo. Busco trabajo. ¿Puedes ayudarme?}
{313}{}{Keith Wright, ¿eh? Me encontré con tu madre.}
{315}{}{¿Qué es este lugar?}

# 11. WHAT IS THIS PLACE (6, 10)
{325}{}{Esta es la CASA de la familia Wright. Y ahora, ¿vas a decirme qué haces aquí?}

# 12. CHRIS TOLD ME TO STOP BY . . . (6, 10, 11)
{335}{}{Chris te envió, ¿eh?}
{336}{}{Efectivamente. Dijo que quizá tuvierais algo de trabajo para mí.}

# 13. I'M LOOKING FOR A JOB . . . [GOOD RESPONSE] (6, 10, 11)
{345}{}{No sé si servirá de algo, pero supongo que podría preguntarle a papá…}
{346}{}{Si pudieras, te lo agradecería.}

# 14. I'M LOOKING FOR A JOB . . . [BAD RESPONSE] (6, 10, 11)
{355}{}{Nah... no contratamos a matones, como sí hacen las otras Familias, al menos por ahora. }
{356}{}{Nah... no tratamos con basura esclavista, como sí hacen las otras Familias. }
{357}{}{Mejor será que te largues.}
{358}{}{No me iré hasta que haya visto al señor Wright.}
{359}{}{Está bien.}

# 15. I'M NOT LEAVING UNTIL I SEE MR. WRIGHT. (14)
{365}{}{Nah, apuesto a que SÍ te irás, porque pareces la clase de persona a la que le gusta vivir. Y ahora, largo.}
{366}{}{NO me voy.}
{367}{}{Está bien.}

# 16. I'M NOT LEAVING. (15)
{375}{}{Te lo he ADVERTIDO…}
{376}{}{¡¿Quieres un poco de ESTO, MUCHACHO?! ¡¿Quieres un poco de ESTO?! Ten un POC--}

# 17. TELL ME ABOUT MOM (6, 10)
{380}{}{Eh… ¿qué pasa con ella? ¿Se ha vuelto a meter en problemas?}
{381}{}{No. ¿Es algo habitual?}
{383}{}{No, sólo era curiosidad. Nos vemos, Keith.}

# 18. NO. IS THAT A COMMON OCCURRENCE? (17)
{390}{}{A veces. Siempre está predicando a voces acerca de los males de la bebida, del juego, y de casi cualquier
 maldita otra cosa. Provoca un gran revuelo a veces, y hace que papá se altere.}
{391}{}{¿Tu madre tiene alguna idea de lo que hace tu familia?}
{392}{}{No me extraña. Bien, gracias por hablar conmigo, Keith.}

# 19. DOES YOUR MOM HAVE ANY IDEA WHAT YOUR FAMILY DOES? (17, 18)
{400}{}{Nah, ella no sabe ni la mitad. Cree que papá está completamente limpio, pero no es lo bastante
 espabilada como para darse cuenta de lo que él está haciendo. Si encontrase ese alambique que hay bajo la estación del tren, montaría un auténtico escándalo, sin duda.}
{401}{}{Ya veo. Gracias, Keith.}

# 20. MOM = AFTER WRECKED STILLS (17)
{410}{}{(Mueve la cabeza). La ha hecho buena esta vez, destrozando los alambiques de papá y todo eso. Los trabajadores estaban demasiado asustados
 para detenerla, y papá se cabreó, y ella hizo volar la mano (se encoge de hombros). A papá le va a llevar
 un tiempo el levantarse.}

# 21. CAN YOU TELL ME ABOUT RICHARD? (6, 10)
{420}{}{Un buen chico. Maldita sea, si alguna vez encontremos al que le hizo eso…}
{421}{}{¿Alguna idea de quién podría haberlo hecho?}
{422}{}{Bien, con un poco de suerte encontraréis al asesino. Adiós, Keith.}

# 22. ANY IDEAS WHO MIGHT'VE DONE IT? (21)
{430}{}{Casi todas las demás Familias venden Jet, podría haber sido cualquiera. Aunque Mordino tiene a la mayor parte de traficantes,
 porque son los que fabrican más Jet. Apostaría a que fue uno de ellos.}
{431}{}{¿De qué traficantes sospechas?}
{432}{}{¿Puedes contarme algo más sobre Richard?}

# 23. WHAT DEALERS ARE SUSPECT? (22, 24)
{440}{}{Un puñado: Jeta Jimmy J en la calle Segunda, el viejo hijoputa de Renesco en la zona Oeste… y Jules
 también trapichea en la entrada a la ciudad, pero casi siempre a turistas imbéciles. Y luego está Pequeño Jesús Mordino.}
{441}{}{¿Pequeño Jesús Mordino?}
{442}{}{¿Puedes contarme algo más sobre Richard?}
{443}{}{Gracias por la información, Keith.}

# 24. CAN YOU TELL ME A LITTLE MORE ABOUT RICHARD? (22, 23, 27)
{450}{}{Un chico callado, limpio. Se mantenía lejos de los problemas, y para un Wright eso no está mal. Lo enterramos
 en las llanuras del Gólgota hace tiempo, pero aún así, mamá sigue sin querer que nadie toque nada de su habitación.
 Le resulta duro pasar página, ¿entiendes?}
{451}{}{¿Cuál era su habitación? ¿Crees que tu madre se enfadaría si echase un vistazo?}
{452}{}{¿Sospechas de algún traficante que le hubiera pasado el Jet?}
{454}{}{Enterrado en el Gólgota, ¿eh? Hmmm. Gracias por la información, Keith.}

# 25. CAN I LOOK AROUND HIS ROOM? (24)
{460}{}{¿Su habitación? Es la que está vacía al lado de la de mamá, la segunda bajando desde la cocina. Y sobre echar un vistazo… bueno… mira, no te quedes
 mucho… y no desordenes nada, o mamá se cabreará si se entera.}
{461}{}{Gracias, Keith. No tardaré mucho.}

# 26. JOB, SUCCESS . . . (12, 13)
{470}{}{Espera. (llama a la puerta que tiene detrás) ¿Papá? (Mete la cabeza, se escuchan unos susurros, y luego se da la vuelta y señala la puerta).
 Puedes entrar, pero cuidado. Papá está de un humor de perros.}
{471}{}{Gracias.}

# 27. LIL' JESUS (23)
{480}{}{Es el hijo de Gran Jesús. Un bastardo, más bien. Puede que hubiera pillado sólo a Richard, y le llenase de Jet hasta arriba. Si le buscas, mira en el Desperado. Pequeño Jesús pasa el rato por allí con su viejo.}



# END LINES
{1220}{}{. ¿Qué pasa?}
{1252}{}{ ¿Todo el mundo te trata bien? ¿Puedo hacer algo por ti?}
{1253}{}{. Te debemos una buena, y los Wright siempre pagan sus deudas. ¿Puedo hacer algo por ti?}