{100}{}{Ves a Renesco 'el Astronauta'.}
{150}{}{Ves a un anciano con un par de grandes y llamativos anteojos. Parece irritado al verte.}
{200}{}{Ves a Renesco el Astronauta. Mientras lo miras, se quita sus anteojos rotos y lustra la única lente sana.}
{201}{}{Ves a Renesco el Astronauta. Mientras lo miras, se quita sus anteojos rotos y lustra la única lente sana.}
{210}{}{Una lente más, es todo lo que pido.}
{211}{}{¡Malditos anteojos!}
{212}{}{¡Maldigo mis ojos!}
{213}{}{¿Vas a COMPRAR algo?}
{214}{}{Esto no es un comedor de beneficencia. ¿Vas a COMPRAR algo?}
{215}{}{Voy a quedarme ciego si mantengo esta clase de trabajo.}
{216}{}{Voy a necesitar más chemtex nueve básico…}
{217}{}{La demanda está creciendo…}
{225}{}{Vete al infierno.}
{226}{}{Sal de aquí, o te dispararé hasta matarte. Dos veces.}
{227}{}{LÁRGATE de aquí.}
{228}{}{¡Fuera! ¡Fuera! ¡Fuera! ¡Fuera! ¡Fuera!}
{235}{}{(El anciano empuja sus rotos anteojos contra su nariz y suspira exasperado). ¿SÍ? ¿Qué es lo que quieres? }
{236}{}{¡Venga, hombre, suéltalo!}
{237}{}{¡Venga, mujer, suéltalo!}
{238}{}{Vaaale lo suelto… mejor tú das un paso atrás (te bajas la cremallera).}
{239}{}{Vaaale. Abro sujetador primero. Espera (te bajas la cremallera).}
{240}{}{¿Qué QUIERO yo? ¿Qué TIENES tú?}
{241}{}{[Le miras un segundo, sólo para asegurarte de que es real, y luego te alejas]}
{242}{}{¿Quién eres?}
{243}{}{Oye, yo tengo unos anteojos, si los quieres.}
{244}{}{¿Cómo están los anteojos?}
{245}{}{Ya sabes, hay marcas descafeinadas que tienen tan buen sabor como las auténticas.}
{246}{}{Amigo, estoy en el lugar equivocado. Adiós.}
{255}{}{(Te mira casi en estado de shock).}
{256}{}{…otra ruina abortada tras nacer en un post-holocausto repleto de niñatos idiotas. (Levanta sus puños).
 ¡Sal de mi tienda! ¡Ahora mismo! Y no vuelvas, ¡¿me oyes?!}
{257}{}{Siento un poco yo }
{258}{}{No sé poner sujetador ahora.}
{259}{}{No gritas a }
{260}{}{ te odia! }
{261}{}{Me voy, me voy. Por ahora.}
{270}{}{¿Yo? Oh, sólo soy el alegre Santa Claus, maldito imbécil a tiempo completo.}
{271}{}{¿Yo? Sólo soy el alegre Santa Claus. Y TÚ debes de ser ese estúpido matón a sueldo que ha estado rondando por la ciudad como un
 perro famélico, hambriento de sus propios excrementos.}
{272}{}{¿Yo? Sólo soy el alegre viejo Santa Claus. Y TÚ debes de ser el estúpido montón de basura del porno que calza como
 un caballo y es igual de estúpido.}
{273}{}{Yo? Sólo soy el alegre viejo Santa Claus. Y TÚ debes de ser la estúpida basura del porno cuya trinchera usan los viejos
 verdes para satisfacer sus fantasías masturbatorias.}
{274}{}{Bien, me alegra no tener que presentarme a mí mismo. ¿Qué estás haciendo aquí, "Santa"?}
{275}{}{¿Santa Claus? ¿Quién diablos es ese?}
{276}{}{Oye, abuelete, otro comentario más como ese, y llevaré tus dientes de collar.}
{277}{}{Oye, voy a dejar pasar tu comentario… por esta vez. Y ahora, ¿quién eres?}
{278}{}{Impresionante vocabulario… "Santa". ¿Eres de por aquí?}
{279}{}{Olvídalo. Me largo de aquí.}
{290}{}{(Te mira fijamente y resopla). Me llamo Renesco. Simplemente dime lo que quieres, eh… bien, lo que quiera que seas.
 (Te mira de reojo). Te pareces a uno de esos primates adoradores del sol con esa pinta que tienes.}
{291}{}{Soy de un poblado del noroeste. Arroyo.}
{292}{}{¿Qué vendes aquí?}
{293}{}{¿Lo que QUIERO? Realmente no lo sé. La mayor parte del tiempo ignoro mi misión y entro en las casas de los demás,
 ojeando en sus estanterías... ¡oooh, como esas de allí!}
{294}{}{Tienes un vocabulario interesante… Renesco. ¿Eres de por aquí?}
{295}{}{Me largo de aquí.}
{305}{}{En su mayor parte vendo drogas recreativas. Por eso me pusieron ese apodo idiota, 'el Astronauta'. Hmmmph.
 También vendo suministros de caravana. ¿NECESITAS algo o puedo volver a dedicarme a cosas importantes?}
{306}{}{Astronauta, ¿eh? ¿Te suena el verso de la canción de Elton John, "Astronauta, quemando los mmmncfnfm yendo a casa'? ¿A qué
 se refiere realmente?}
{307}{}{¿Puedo ver lo que tienes a la venta?}
{308}{}{¿Vendes drogas, aquí en la TIENDA?}
{309}{}{¿Te refieres a cosas como venderle drogas al hijo de Wright?}
{310}{}{Puedes volver a hacer cosas importantes.}
{320}{}{(Renesco te mira fijamente. Parece como si te desnudara mentalmente, y te arrancase los miembros uno a uno).}
{321}{}{Entonces no importa. Tenía algunas otras preguntas…}
{322}{}{No importa, entonces.}
{330}{}{(Renesco te mira disgustado). Sí. En la TIENDA. Esto no es el siglo XX, en el que las drogas las vendían
 cucarachas de esquina que vivían con un temor constante a las autoridades.}
{331}{}{Bien, entonces -}
{332}{}{Pero -}
{333}{}{Eh, creo que será mejor que -}
{350}{}{Esto es NUEVO RENO. Aquí no hay policía, no hay leyes, y hay un montón de clientes a los que no les importa comprar veneno en la
 farmacia del final de la calle. ¿Contesta ESO a tu pregunta, primate?}
{351}{}{A todas excepto a una: ¿fue Richard Wright uno de tus clientes?}
{352}{}{Vale, vale... ¿qué tienes a la venta?}
{353}{}{En realidad, tenía algunas preguntas más...}
{354}{}{Pero, como has dicho, las drogas son… venenosas. Matan el espíritu. ¿No te molesta el venderlas?}
{355}{}{Seguro que sí. Me iré ahora.}
{365}{}{¿Me MOLESTA vendérselas a idiotas, esclavistas, señores del crimen y tribales sin los que el mundo estaría
 mejor? Primate, dos palabras: sal más.}
{366}{}{Vale... ¿puedo ver lo que tienes a la venta?}
{367}{}{Está bien, está bien. Oye, tenía algunas otras preguntas...}
{368}{}{Las drogas de Nuevo Reno están encontrando su camino hacia otros lugares, y haciendo daño a la gente. ¿No te importa eso?}
{369}{}{Empezaré por marcharme ahora mismo.}
{375}{}{¿Y? ¿A mí qué me importan ellos?}
{377}{}{La raza humana sufrió una horrible tragedia. Ahora está intentando renacer. Vender Jet parece… contraproducente
 para esa reconstrucción.}
{378}{}{Vale, lo que sea. Debo irme ahora.}
{385}{}{Y qué. Nadie OBLIGA a esos idiotas a inhalar Jet. ¡Nadie les ronda y se lo mete a la fuerza por sus
 gargantas!}
{386}{}{Me parece -}
{387}{}{Pero no -}
{388}{}{Esa es tu -}
{395}{}{¡Esos acarrea-rocas con lámparas en la cabeza de Redding SABEN lo que están tomando, así que no siento ni una pizca de piedad por ellos!
 ¡Por lo que a mí concierne, el Jet extirpa a la basura que debería haber muerto cuando lanzaron las bombas!}
{396}{}{Eh, está bien. ¿Puedo ver tu mercancía?}
{397}{}{¿Dónde está esa Redding de la que hablas? ¿Por qué la mencionas?}
{398}{}{Has mencionado Redding específicamente. ¿Por qué el Jet es tan relevante en Redding?}
{400}{}{Estás en tu derecho de sentirte así. Ahora he de irme.}
{410}{}{Bueno, Redding es un… caso especial. Verás, hay gente en Reno que se asegura de que Redding esté bien abastecido. Después de todo, una
 vez pruebas el Jet, te enganchas. Así es como YO me gano la vida.}
{411}{}{Hablando de eso, ¿puedo ver tu mercancía?}
{412}{}{¿Quién se asegura de que Redding esté bien abastecido? ¿Y por qué?}
{413}{}{Ya me he dado cuenta. Oye, tenía algunas preguntas más...}
{414}{}{Ya veo… ahora debo irme.}
{420}{}{Bien, tribal, dudo que seas tan espabilado como para notar esto, pero Nuevo Reno no produce nada útil.
 Es como una gran y brillante garrapata agarrada al desierto.  Ahora bien, Redding, por el contrario…}
{421}{}{Sigue.}
{422}{}{… PRODUCE algo útil.}
{423}{}{Ya he oído bastante.}
{430}{}{Primera y última vez que te aviso, tribal: no termines mis malditas frases. No me gustan los primates listillos
 que hablan cuando deberían escuchar. No me extraña que todos sigáis usando lanzas…}
{431}{}{No todos. Por ejemplo, yo utilizo una variedad de armas para matar gente... déjame que te las enseñe.}
{432}{}{Perdóname. Por favor, continúa.}
{433}{}{Que te jodan. Me largo de aquí. }
{440}{}{Redding tiene una fuerza de trabajo estable que se dedica a minar materias primas, oro en su mayor parte. A Nuevo Reno le vendría muy bien ese oro. Alguien
 se imagina que todo lo que tenemos que hacer es conseguir que esos mineros se vuelvan adictos, y los tendremos atrapados de por vida. ¿Lo entiendes ahora?}
{441}{}{Sí… excepto por una cosa: ¿de dónde vino el Jet?}
{442}{}{¿Quién está intentando que todos los mineros se vuelvan adictos?}
{443}{}{Sí, lo entiendo. Verás, tenía algunas otras preguntas...}
{444}{}{No quiero oír nada más. Debo irme ahora.}
{450}{}{(Señala a Myron). ¿Por que no le preguntas a tu amiguito cachondo? Estoy seguro de que le encantará contártelo. (Mira
 a Myron). ¿Verdad, muchacho?}
{451}{}{Hay una persona a la que le podemos agradecer el Jet. ¿Has oído hablar del pequeño chico de oro de la Familia Mordino, Myron? Pues bien, el pequeño
 bastardo CREÓ el Jet. Gran Jesús Mordino se limita a permitir que todo el mundo sepa dónde podría conseguirlo.}
{452}{}{Háblame más de Myron.}
{453}{}{¿Hay alguna cura para el Jet?}
{454}{}{Tenía algunas preguntas más...}
{460}{}{Gran Jesús Mordino está canalizando el Jet hacia Redding. El típico juego de poder. En cuanto esa línea de suministro funciona al 100%, esos
 mineros están perdidos.}
{461}{}{¿De dónde procede el Jet?}
{463}{}{Ya veo. Oye, tenía algunas preguntas más...}
{470}{}{Cachondo como un sapo y con sus mismas costumbres. Pero es un chico inteligente. Tiene un alto cociente intelectual. Desperdicia su cabeza fabricando drogas, eso es
 cierto, joder.}
{471}{}{¿Dónde puedo encontrarlo?}
{472}{}{Ya veo. Tenía algunas preguntas más…}
{480}{}{Los Mordino lo tienen encerrado en alguna parte. Probablemente bien protegido. No sé exactamente dónde.}
{481}{}{Gracias por la información. ¿Puedo ver lo que tienes a la venta?}
{490}{}{¡¿Una CURA para la adicción a la metanfetamina?! ¡Ja! Sólo conozco dos: una es la muerte. La otra es encerrarse
 en una jaula un año sin Jet y echarla de tu cuerpo sudándola. Hmmmph. ¡"Cura", mis cojones! ¡Qué tontería!}
{492}{}{Debe haber una cura. ¿Cuál es la composición química del Jet?}
{505}{}{¿Por qué no le preguntas a tu amigo? Él diseñó la droga.}
{506}{}{Yo solo vendo el material. Yo de ti le preguntaría a un científico. O a Myron. Él diseñó la droga.}
{515}{}{(Renesco te mira en silencio).}
{516}{}{(Renesco vuelve a mirarte, esta vez en silencio).}
{517}{}{Creo que te gustaría Arroyo. Es un poblado tranquilo. Excepto por las plantas poseídas por espíritus malignos… y, por supuesto, el templo
 de las pruebas, lleno de trampas de pinchos mortales y hormigas gigantes devoradoras de hombres.}
{518}{}{Oye, ¿alguna vez has oído hablar de un Kit de Creación del Jardín del Edén? ¿O del Refugio 13?}
{519}{}{De acuerdo, entonces… me voy de aquí.}
{525}{}{(Renesco continúa mirándote en silencio).}
{526}{}{Y a veces la Anciana se molesta con pequeñeces, como… je, je… esa noche en la que ignoré mi voto de
 celibato y me colé con Reyna - Cuyas - Piernas - Aplastan - con - la - Fuerza - de - Mil - Serpientes en el cañón de Arroyo…}
{535}{}{(Renesco te lanza una mirada fulminante).}
{536}{}{Es como si hubiera pasado ayer. El cuerpo de Reyna brillaba como la plata con la luz de la luna cuando se arrodilló y… oye, ¿sabes qué?
 Tú podrías ser como la Anciana. Tiene más o menos tu edad.}
{545}{}{(Renesco continúa mirándote fijamente como si de algún modo pudiera hacerte desaparecer con sólo imaginarlo lo suficiente).}
{546}{}{¿He mencionado que Arroyo fue fundado por mi antepasado, el santo Morador del Refugio? Hizo un viaje legendario desde el
 sur después de derrotar a un gran mal. (Hinchas el pecho y miras con orgullo a lo lejos). ¡Ahora, *yo* soy el salvador de mi
 tribu, elegido para buscar el sagrado GECK!}
{547}{}{De acuerdo, basta de historias… será mejor que siga mi camino. ¡Alabado sea el Refugio!}
{555}{}{(La mirada hostil de Renesco se desmorona). }
{556}{}{¿GECK? ¿Un 'Kit de Creación del Jardín del Edén'? ¿Tiene una unidad básica de replicación, un lector de holodiscos con selecciones
 de la biblioteca del Congreso, y una pequeña pluma-linterna?}
{557}{}{Sí, pero eso no es importante ahora mismo. Aún no he terminado de hablarte de Arroyo.}
{558}{}{¡Sí! Mi poblado tiene problemas con los cultivos, y se necesita el GECK para restaurarlos. ¿Sabes dónde puedo encontrar uno?}
{559}{}{Se dice que está sellado dentro del Refugio 13, o al menos eso dice la leyenda. ¿Conoces tal lugar?}
{560}{}{Si no vas a ESCUCHAR cuando recito las sagradas escrituras, me voy de aquí.}
{561}{}{Pudiera ser. Oye, tengo que irme.}
{570}{}{Tu poblado, un remanso de fumadores de hierba, está condenado, y tú junto a él. ¿Por qué
 un primate como tú está buscando un GECK?}
{571}{}{Arroyo… mi remanso de fumadores de hierba, como tú dices… está teniendo problemas con sus cosechas. Se necesita el GECK
 para restaurarlas.}
{572}{}{Se dice que está sellado dentro del Refugio 13. ¿Conoces tal lugar?}
{573}{}{Creo que no me apetece compartir eso en este momento. Adiós.}
{580}{}{Hmmmmm. Seguro que podría hacerlo… fácilmente. SI es que encuentras uno. Ni siquiera sé dónde podrías empezar a buscar. RNC
 o Ciudad Refugio, quizá, pero dudo que tengan uno… aunque…}
{581}{}{¿Aunque…?}
{590}{}{Aunque esos bastardos santurrones podrían ser capaz de indicarte una dirección. Si hablas despacio y usas palabras sencillas…}
{591}{}{¿RNC o Ciudad Refugio, dices? Iré a buscar en esos lugares y preguntar a sus habitantes sobre el GECK. Gracias.}
{592}{}{¿Por qué el GECK no estaría en el sagrado Refugio 13? Las escrituras DICEN que el GECK está sellado en el interior del sagrado 13.}
{593}{}{Muy gracioso. Tenía algunas otras preguntas…}
{594}{}{De acuerdo entonces… iré a comprobarlo. Gracias.}
{600}{}{Demonios, no, primate. Claro que he oído hablar de los refugios, pero no del Refugio 13. Lo que más se acerca es Ciudad Refugio, al nordeste… y
 si esos aristócratas mequetrefes habitaron en un Refugio alguna vez, seguro de cojones que ya no lo hacen.}
{601}{}{¿Ciudad Refugio, dices? Iré a buscar esa ciudad del Refugio y preguntaré a sus habitantes acerca del GECK.
 Gracias, Renesco. ¡Alabado sea el Refugio! }
{602}{}{¿"Refugios"? ¿Hay más de un Refugio?}
{603}{}{Hmmm. Tenía algunas preguntas más…}
{610}{}{Si vas a ir a Ciudad Refugio, no me des las gracias, primate. Estarías mejor en Nuevo Reno. Al menos la gente que
 te toma medidas para tu ataúd es honesta al respecto.}
{611}{}{De acuerdo… voy de camino a Ciudad Refugio. ¡Alabado sea el Refugio! }
{612}{}{Ya veo. Gracias por la advertencia. }
{620}{}{¿Por qué crees que se llama Refugio TRECE, tiraflechas? ¿Qué pasa, que en tu tribu andáis cortos de seso o simplemente es que
 efectuáis lobotomías rituales para eliminar la minúscula voz de la razón que habla en vuestras cabezas?}
{623}{}{Ya, vuelves a meterte conmigo. Gracias… por la información, al menos. }
{630}{}{El pasado de una persona no es un inteligente tema de conversación aquí en Nuevo Reno. Y ahora, ¿qué es lo que quieres?}
{632}{}{Pareces un hombre bien educado. ¿Alguna vez has oído hablar de un GECK o un lugar llamado Refugio 13?}
{634}{}{Nada, no importa. }
{640}{}{(Renesco te arranca los anteojos de las manos y se los pone. Abre mucho los ojos). ¡Dulce Reno! ASÍ es como está esta maldita
 tienda. (Frunce el ceño). Qué desorden… ¿y qué es eso que hay en las estanterías? Parece mierda de brahmin.}
{641}{}{No hay de qué…}
{642}{}{Disfruta. }
{650}{}{¡Hmpphh! Yo… hmmm… eh… ¿de dónde has sacado esto?}
{651}{}{Bien, había un diminuto escorpión rad, ¿sabes?, y un científico que lo estaba entrenando, y... ¿sabes qué? Ni yo
 me lo creo. Sólo guárdalas bien, ¿vale?}
{652}{}{Digamos solamente que las he encontrado. En alguna parte.}
{660}{}{¡Oye! ¡Espera un momento! ¿De dónde has sacado esto?}
{661}{}{Bien, había un diminuto escorpión rad, ¿sabes?, y un científico que lo estaba entrenando, y... ¿sabes qué? Ni yo
 me lo creo. Sólo guárdalas bien, ¿vale?}
{670}{}{Bueno, yo… hmnnn… estoy… eh, agradecido. Pensé que tendría que sufrir con ese armazón roto el
 resto de mi vida. Si puedo hacer algo por ti, házmelo saber… y, eh, me lo PENSARÉ.}
{671}{}{¿Que tal un descuento?}
{672}{}{No importa… mira, tan sólo ten cuidado con ellas, ¿vale? Tenía algunas preguntas más…}
{673}{}{Algún día… y puede que ese día nunca llegue, tendrás que hacerme un servicio. Pero hasta entonces
 acepta estos anteojos como un regalo en el día de la boda de mi hija. }
{680}{}{Ehhh…}
{681}{}{Errr…}
{682}{}{Bueno…}
{683}{}{¡Está bien! ¡Está bien! ¡Te haré un descuento! Hmphhh.}
{684}{}{Venga. Sólo un pequeño descuento. Venga…}
{687}{}{¡Genial! Vamos a ver lo que tienes, "colega".}
{688}{}{¡Excelente! Oye, tenía algunas preguntas más…}
{689}{}{Volveré para comprar más tarde. }
{700}{}{Que sea rápido.}
{701}{}{Oye, soy un hombre ocupado…}
{702}{}{¿Y bien? ¡Suéltalo ya!}
{703}{}{¿Sí?}
{704}{}{¿Alguna vez te he hablado acerca de mi poblado, Arroyo?}
{706}{}{¿Le vendiste Jet a Richard Wright?}
{707}{}{Estoy aquí para recoger el tributo del señor Salvatore.}
{710}{}{Estoy buscando ciertas piezas para la mina de Broken Hills…}
{711}{}{Tienes un interesante vocabulario… ¿Eres de por aquí?}
{712}{}{No importa. }
{725}{}{(Entorna los ojos). ¿Y bien?}
{726}{}{Bueno, necesito las piezas para reparar el purificador de aire de su mina. Pensé que podrías ayudarme.}
{727}{}{Bueno, necesito las piezas para reparar el purificador de aire de su mina. Zaius me envía. Dijo, eh… dijo... eh... mierda.}
{728}{}{Bueno, necesito las piezas para reparar el purificador de aire de su mina. Zaius me envía. Dijo, 'El canario estiró la pata'.}
{735}{}{Pues sí, resulta que tengo unas piezas con las que se podría reparar el purificador de aire. 100 pavos.}
{736}{}{Me las llevaré. Aquí tienes.}
{737}{}{¿Qué tal cincuenta pavos?}
{738}{}{Eh, no llevo encima un centenar… volveré más tarde con el dinero. }
{745}{}{Inflación debida a la irritación de la directiva con los regateadores. 200 o nada.}
{746}{}{(Frunce el ceño). 200 o nada.}
{747}{}{¡¿Doscientos?! ¡Dijiste CIEN hace un segundo!}
{748}{}{Eh, me las llevaré. Aquí tienes.}
{749}{}{Eh, no llevo encima dos centenares… volveré más tarde con el dinero. }
{755}{}{DUDO horrores que fuera eso lo que dijo.  No sería 'El canario estiró la pata', ¿verdad?}
{756}{}{Bueno, sí.}
{760}{}{¿Y…?}
{761}{}{¿"Y"?}
{765}{}{¿Y la SEGUNDA parte fue…?}
{766}{}{"¿Segunda parte?" Él no dijo nada acerca de una SEGUNDA parte. ¡El infame bast-!}
{769}{}{Sólo te ponía a prueba. No hay segunda parte. Bien, si Zaius te envía, SUPONGO que tengo algunas piezas de sobra. }
{770}{}{Aquí tienes. No las dejes caer.}
{771}{}{Gracias. Tenía algunas preguntas más…}
{772}{}{Eh, gracias. }
{780}{}{Ni se te OCURRA lanzar esa acusación sobre mí. Si quieres saber quién lo hizo, pregunta a Tweedledum y Tweedledumber
 si todavía siguen vendiendo Jet cortado con arsénico.}
{781}{}{¿'Tweedledum' y 'Tweedledumber'? ¿Quienes son?}
{782}{}{Jules dijo que te preguntase. Dice que tú vendes mierda de la mala.}
{783}{}{Jeta Jimmy dijo que te preguntase. Dice que tú vendes mierda de la mala.}
{784}{}{Los dos dicen lo mismo sobre TI. Dicen que tú vendes mierda de la mala.}
{785}{}{No creo que fuera arsénico... pero CREO que fue envenenado.}
{786}{}{¿Qué puedes contarme sobre este frasco vacío de Jet?}
{788}{}{Entonces iré a preguntarles. }
{795}{}{Ese buitre de Jules y ese mentiroso réprobo de 'Jeta Jimmy'. Jules siempre está posado cerca de la entrada
 a la ciudad, buscando visitantes ignorantes a los que timar, y Jeta Jimmy trapichea en la calle Segunda con el resto de la chusma de Reno.}
{798}{}{Dijeron que te preguntara. Dijeron que tú vendes mierda de la mala. Mierda de la que mata gente.}
{800}{}{Entonces iré a preguntarles. }
{805}{}{Oye, primate… ni siquiera SABES de lo que estás balbuceando.}
{806}{}{Oh, yo creo qu-}
{807}{}{¿Sí? De acuerdo entonces, por qué no -}
{808}{}{No importa. Tenía algunas otras preg-}
{809}{}{Mira, será mejor que me vay-}
{815}{}{ABRE tu boca de nuevo y que le llegue al señor Wright aunque sólo sea un SUSURRO, incluso apenas un INDICIO, de que yo… o tú… podríamos haber tenido algo
 que ver con la sobredosis de ese chico, y nuestras vidas no valdrán un excremento de brahmin. Y si ESO ocurre --}
{816}{}{¿Oh? Así que tú -}
{817}{}{¡¿Yo?! Oye, espera un mom-}
{825}{}{Si ESO ocurre, BASURA tribal, te JURO que morirás antes que yo. Y ahora… por ÚLTIMA vez, ese chico nunca me compró MIERDA
 a mí, ¿entendido? NUNCA vuelvas a pronunciar su nombre aquí, o de lo contrario…}
{826}{}{JULES dice que él no le vendió al chico. JIMMY dice que él no le vendió al chico. TÚ dices que no le vendiste. Uno
 de vosotros está mintiendo.}
{827}{}{JULES dice que él no le vendió al chico. JIMMY dice que él no le vendió al chico. TÚ dices que no le vendiste. O uno
 de vosotros es responsable, o... algún otro lo es.}
{828}{}{¿Puedes contarme algo más acerca de Richard Wright? ¿Quién trapichea por ahí que podría haber tenido drogas?}
{829}{}{Está bien... verás, tengo algunas otras preguntas...}
{830}{}{Vale, vale... ya me marcho. }
{835}{}{A eso puedo contestar fácilmente. Uno de esos dos chuchos callejeros está mintiendo para salvar sus posaderas. Entre tú y yo, ellos
 venden el 90% del Jet de Reno, y ese es el único lugar en el que el 'chico' del que estamos hablando podría haberlo conseguido.}
{836}{}{O alguien se lo compró a uno de vosotros tres. ¿Quién de tus clientes del mes pasado podría haber tenido contacto
 con… la víctima?}
{837}{}{¿Puedes contarme algo más acerca de Richard Wright? ¿Quién trapichea por ahí que podría haber tenido drogas?}
{838}{}{Ya veo... tenía algunas otras preguntas...}
{839}{}{Ya me marcho. }
{845}{}{ESTÚPIDO bastardo. }
{846}{}{ESTÚPIDA zorra. }
{847}{}{Te DIJE que no dijeses su nombre aquí. ¡Lárgate! Si vuelvo a verte, DISPARARÉ HASTA MATARTE. Si el señor Wright viene a
 buscarme, y cree que yo maté a su chico, TÚ morirás primero.}
{848}{}{No me amenaces, viejo…}
{849}{}{Eh, eh. Ya me voy. }
{855}{}{No tengo NI idea. No conocía al chico, así que no conozco a sus amigos O sus hábitos. El único que podría hablarte
 sobre él está demasiado ocupado estando muerto en el Gólgota para contártelo.}
{856}{}{¿Gólgota?}
{858}{}{Quizá lo haga. Adiós. }
{865}{}{Entonces has hecho un viaje en balde. PAGUÉ al señor Salvatore su 'tributo' *hace dos semanas*, según su agenda. No sé
 quién eres, o qué crees que estás haciendo, pero no vas a obtener de mí una mísera ficha. Largo.}
{866}{}{Oye, abuelete. Deja de tocarme las pelotas. Suelta las fichas, o vas a toser sangre.}
{867}{}{Soy el representante del señor Salvatore. Me entregarás el tributo que he pedido, y lo harás ahora.}
{868}{}{Lo comprobaré en la agenda del señor Salvatore, y volveré. }
{875}{}{¿Te has quedado sordo, muchacho? }
{876}{}{¿Te has quedado sorda, muchacha? }
{877}{}{HE DICHO. QUE. YA. PAGUÉ. EL. TRIBUTO. *Hace dos semanas*. Si de verdad estuvieras con Salvatore, sabrías eso. ¡Ahora piérdete!}
{878}{}{Oye. Por última vez: Entrega las fichas.}
{879}{}{Tú eres el que se ha quedado sordo. Soy el representante del señor Salvatore, y tú vas a pagar el tributo.}
{880}{}{Te he avisado, abuelete. Parece que tendremos que hacerlo por las malas. Hora de morir.}
{881}{}{Comprobaré en la agenda del señor Salvatore lo del tributo, y volveré. }
{890}{}{Demuestra que estás con Salvatore, y CONSIDERARÉ entregarte las fichas. De lo contrario, no vas a conseguir una mierda.}
{891}{}{No necesito demostrar nada. Soy su representante, y eso es todo lo que necesitas saber.}
{892}{}{¿Qué te crees, que esta pistola láser sólo es para ir enseñándola?}
{893}{}{Si no me entregas el tributo en cinco segundos, TE MATARÉ.}
{900}{}{¡Lárgate de una puta vez, matón del tres al cuarto! ¡Vuelve a mostrar tu cara por aquí, y te pegaré un tiro!}
{901}{}{Te lo advertí. Hora de morir.}
{910}{}{Hmmmph. No importa, no puedo pagar. el último cobro casi me liquidó.}
{911}{}{Eso no me concierne. Me entregarás el dinero ahora. El señor Salvatore no quiere oír tus excusas.}
{920}{}{Amenazarme no te ayudará. El señor Salvatore quiere su dinero. Yo no lo tengo. Él se cabreará conmigo, pero también
 se cabreará contigo. A Salvatore NO le gusta la gente que le defrauda… será mejor que piensas algo rápido.}
{921}{}{Ya lo tengo. Yo pagaré tu parte de este plazo. A cambio, tú me harás un 'descuento' en tu tienda.}
{924}{}{Intentaré encontrar algo mejor… volveré.}
{930}{}{Espera un momento, neanderthal…}
{931}{}{No voy a discutir contigo. Mi paciencia tiene un límite. Esas son mis condiciones.}
{940}{}{Yo... bueno, verás, yo... hmmmm... está bien. Tienes un… "descuento".}
{941}{}{Veamos tu mercancía. Haré mis 'compras' ahora.}
{943}{}{Ahora no quiero nada, pero no te preocupes, que volveré. }
{950}{}{(Cruza los brazos). Adecuados. Si estás esperando un folleto por ser un buen samaritano, estás MUY
 equivocado. Y ahora… ¿qué es lo que quieres?}
{951}{}{¡La madre que parió a la Garra mortal o al director de marketing que te hizo! ¡¿QUIERES algo?! ¡Aquí! ¡AQUÍ! ¡Toma ESTO!
 Toma todo lo que tengo! Lo que sea con tal de que me DEJES EN PAZ!}
{952}{}{Déjame ver tu mercancía.}
{953}{}{Tengo algunas preguntas…}
{955}{}{¿Qué demonios ES esto…? }
{960}{}{¿Envenenado? ¿Qué estás balbuceando?}
{961}{}{La condición del cuerpo concordaba con el veneno del escorpión rad. Creo que murió porque su Jet estaba envenenado,
 NO debido a una sobredosis.}
{962}{}{Encontré un frasco vacío de Jet en su habitación. Había restos de veneno de escorpión rad en ella.}
{963}{}{No importa. Tenía algunas otras preguntas...}
{964}{}{Olvídalo. Tengo que irme ahora. }
{970}{}{¿Escorpión rad...? (Renesco se queda helado, como si recordase algo).}
{971}{}{Hijo de puta. Tú *envenenaste* al chico, ¿verdad?}
{972}{}{Sabes algo al respecto, ¿verdad?}
{980}{}{¡Eh! ¡Espera un momento...!}
{981}{}{¡No me tomes el pelo, Renesco! Trata de escabullirte de ésta, y te unirás a Richard. ¿Entendido?}
{982}{}{Eso es todo. El señor Wright y yo vamos a tener una pequeña charla. Buenos días, Renesco... o debería decir, "adiós".}
{990}{}{¡Espera un momento! Oye... ¡no se lo vendí al chico! ¡Él nunca me compró NADA! Me... me PIDIERON
 que cortase un poco de Jet con veneno de escorpión rad, pero... ¡pero NO se lo vendí al chico!}
{991}{}{¿Te PIDIERON que prepararas Jet envenenado? ¿Para quién?}
{992}{}{¿A QUIÉN se lo vendiste?}
{995}{}{Los Salvatore lo pidieron: dijeron que era un... "pedido especial". No sabía que se lo iban a dar
 al chico de Wright. TIENES que creerme... ¡Yo no enveneno a niños!}
{996}{}{Sólo a adultos, ¿eh, Renesco? Patético hijo de puta...}
{997}{}{¿POR QUÉ envenenaste el Jet?  Tenías que saber que iban a matar a alguien con él.}
{998}{}{Está bien, está bien, te creo. Tenía algunas otras preguntas...}
{999}{}{Cierra el pico, anda. Bien, tengo algunas preguntas más...}
{1000}{}{Los Salvatore, ¿eh? Creo que el señor Wright querrá enterarse de esto. }
{1005}{}{Los Salvatore son MIS dueños, este lugar les PERTENECE, y cuando quieren algo se lo doy, o me matarían
 y me reemplazarían. Nunca tuve la intención de hacer daño a ese chico.}
{1007}{}{Cierra el pico. Bien, tengo algunas otras preguntas para ti...}
{1008}{}{Sí, estoy seguro de que tenías la mejor de las intenciones mientras estabas mezclando ese Jet con veneno. Adiós, Renesco.}
{1009}{}{Nos vemos, Renesco. }
{1020}{}{Está vacío. Es un frasco de Jet como cientos de otros por todo Nuevo Reno. ¿Puedo ayudarte en algo más?}
{1021}{}{¿Esto es tuyo?}
{1022}{}{¿Sabes algo de los rastros de veneno de escorpión rad que hay en este frasco?}
{1023}{}{Sí, tenía algunas preguntas más...}
{1030}{}{No. ¿Puedo ayudarte en alguna OTRA cosa?}
{1033}{}{No. Adiós. }
{1040}{}{¿El Gólgota? Es un enorme cementerio a las afueras de la ciudad, hacia el sur. Sigue el olor... el olor que no es el TUYO.}
{1041}{}{Oh. Tenía algunas preguntas más...}
{1042}{}{Sigue haciendo bromitas como esa conmigo, Renesco, y vas a estar agonizando un buen rato. }
{1043}{}{GRACIAS, Renesco. }
{1526}{}{Y a veces la Anciana se molesta con pequeñeces, como… je, je… esa noche en la que ignoré mi voto de
 castidad y me colé con Kor - Quien - Ruge - como - Mil - Sementales en el cañón de Arroyo…}
{1536}{}{Es como si hubiera pasado ayer. El cuerpo de Kor se tensaba como el bronce bajo la luz de la luna cuando se arrodilló y… oye, ¿sabes qué?
 Tú podrías ser como la Anciana. Tiene más o menos tu edad.}
{2000}{}{Has destapado la participación de Renesco en la muerte de Richard Wright.}
{5257}{}{ es muy grande. Marcho ahora yo }
{5259}{}{ no grites tú POR QUE GRITAS DEJA LOS GRITOS }
{5260}{}{…*sniff*… ¡voy a buscar a mi hermano mayor y te pegará, viejo! Luego comeremos helado y…*sniff*… TARTA
 y habrá una fiesta grande con payasos y…}
{6259}{}{ TE MATA.}
