{100}{}{Ves a un científico.}
{150}{}{Ves a un hombre de mirada seria con un portapapeles y una aguja hipodérmica. Te ignora.}
{151}{}{Parece extremadamente cansado e irritable.}
{152}{}{Ves a una mujer de mirada cansada. Comprueba un portapapeles y mira a su alrededor
 como si hubiera olvidado algo.}
{153}{}{Está llenando una aguja hipodérmica, gruñendo ligeramente para sí misma.}
{154}{}{Hola Myron, señor.}
{155}{}{Myron... señor, ¿tiene un minuto…?}
{156}{}{¿Alguna noticia sobre cuándo llegarán más esclavos, Myron, señor?}
{157}{}{Myron... señor, estos nuevos resultados son muy prometedores…}
{158}{}{¿Myron? ¿Un minuto de su tiempo, señor?}
{159}{}{Dónde demonios está Myron…}
{160}{}{Traed a Myron aquí. Debe ver esto.}
{161}{}{Ojalá esos esclavos cerrasen la boca…}
{162}{}{Dónde habré puesto esa jeringuilla…}
{163}{}{¿Alguien a visto al Sujeto 31? Estaba aquí hace un segundo.}
{164}{}{Que los esclavos traigan más Jet Beta.}
{165}{}{Los resultados de las pruebas del Jet Beta son muy prometedores, pero…}
{166}{}{El "subidón" dura de 15 minutos a una hora… calcula un período de una dosis/hora… hmmmmnnn.}
{167}{}{El Sujeto 12 todavía tiene hemorragia pulmonar…}
{168}{}{Es la quinta vez que el Sujeto 12 ha tenido ataques… aumenta la dosis, a ver qué pasa…}
{169}{}{Bien, ¿qué TIPO de alucinaciones estaba teniendo?}
{170}{}{Comprueba el pulso de aquel. Si aún está dentro de los límites tolerables, aumenta la dosis.}
{171}{}{¿Por qué se suicidó la esclava del grupo de control? ¡Ni siquiera estábamos haciendo pruebas con ella!}
{200}{}{Las pruebas se están desarrollando según lo planeado, Myron.}
{201}{}{Esta nueva variedad de Jet es extremadamente adictiva, señor. Los esclavos casi están
 dispuestos a matarse entre ellos por ella.}
{202}{}{Los esclavos preferirían el Jet antes que la comida, tan potente es.}
{203}{}{¿Quienes son esas personas que van con usted, Myron? ¿Nuevos sujetos?}
{204}{}{El tercer grupo de pruebas parece ser el mejor de todos, Myron, señor.}
{205}{}{Myron, opino que el siguiente grupo de pruebas debería incluir al menos tres niños, señor.}
{206}{}{Myron, señor, el Sujeto 46 tuvo un ataque al corazón; ahora estamos restringiendo las dosis a
 seis veces al día.}
{207}{}{¿Myron? Pronto necesitaremos un nuevo envío de agujas hipodérmicas de Ciudad Refugio. No podemos
 seguir reutilizando estas.}
{208}{}{¡Myron, por fin! ¿Alguna noticia sobre cuándo llegarán más esclavos, señor?}
{209}{}{Myron, señor, hemos trasladado tres esclavos del grupo de control al grupo de pruebas debido
 a los fallos respiratorios que ocurrieron la semana pasada.}
{210}{}{Myron, señor... tuvimos que disparar a un esclavo que intentaba escapar. Fue un desperdicio.}
{211}{}{Myron... este nuevo alucinógeno que desarrolló es prometedor, pero no es tan adictivo como el Jet…}
{212}{}{Si tienes alguna sugerencia, por favor escríbela en un trozo de papel y ponla justo
 en esa papelera de ahí.}
{213}{}{¿Sí, sí, qué?}
{214}{}{No seremos capaces de obtener resultados si continúas interrumpiéndonos.}
{215}{}{Parece que hoy en día se permite pasear a cualquier hijo de vecino por aquí…}
{216}{}{¿Qué quieres?}
{217}{}{Por favor perdóname, *tengo* trabajo que hacer.}
{218}{}{Si tienes preguntas, habla con los guardias, no conmigo.}
{219}{}{Sí, tengo la seguridad de que lo que quiera que necesites tiene una *enorme* importancia, pero tengo mis propias
 tareas.}
{220}{}{¿Estás autorizado para estar aquí?}
{221}{}{¿Quién te permitió entrar aquí?}
{222}{}{Cuando Myron se entere de que en el laboratorio han entrado extraños…}
{223}{}{¿Tienes esos resultados de las pruebas que te pedí… oh, lo siento. Creí que eras un técnico de laboratorio.}
{224}{}{Demasiado ocupado para hablar ahora mismo, lo siento.}
{225}{}{Necesitaremos una nueva inyección de esclavos pronto… estos se están quedando sin gas.}
