{100}{}{Ves a un joven de aspecto corriente vestido con ropa respetable.}
{101}{}{Es el recepcionista del edificio.}
{102}{}{No hay nada en particular en el tipo. Parece el epítome del burócrata en ciernes.}
{103}{}{Bienvenido al Congreso. ¿Cómo puedo ayudarte?}
{104}{}{Has vuelto, por lo que que veo. ¿Cómo puedo ayudarte esta vez?}
{105}{}{Y ahora, ¿qué puedo hacer por ti?}
{106}{}{Uhhh...}
{107}{}{¿Ver a Tandi yo?}
{108}{}{¿Ver a Tandi yo?}
{109}{}{Estoy aquí para ver a la presidente Tandi.}
{110}{}{¿Puedes ayudarme a encontrar el Refugio 13?}
{111}{}{No puedes, a menos que tengas un GECK.}
{112}{}{Tengo noticias importantes para tu jefa.}
{113}{}{Estoy aquí para ver a la presidente Tandi.}
{114}{}{Estoy aquí para ver a la presidente Tandi.}
{115}{}{Estoy buscando trabajo.}
{116}{}{¿Qué es este lugar?}
{117}{}{No puedes.}
{118}{}{Yo me voy.}
{119}{}{Lo siento, aquí no hay aseos públicos. ¿Por qué no sigues tu camino?}
{120}{}{¿Referente a?}
{121}{}{Hmmm... ¿Por qué quieres ver a la Señora Presidente?}
{122}{}{Hombre dice que Tandi me contrata.}
{123}{}{Pequeño pueblo en el desierto quiere hacer amigos con Tandi.}
{124}{}{He oído que tu presidente tiene un trabajo que hacer.}
{125}{}{La gente del Refugio 15 quiere hacer un trato.}
{126}{}{}
{127}{}{¿Como cuales?}
{128}{}{Alguien la ha traicionado.}
{129}{}{Nada que te concierna.}
{130}{}{Qué bien. Esto no es un centro de contratación. ¿Por qué no lo intentas en el centro de la ciudad?}
{131}{}{Este es el Congreso, el órgano legislativo de la RNC.}
{132}{}{(Continuar)}
{133}{}{¿13? ¿O querías decir 15?}
{134}{}{He dicho 13.}
{135}{}{¿15?}
{136}{}{No.}
{137}{}{(Continuar)}
{138}{}{Oh, eso. Habla con el señor Gunther, ahí atrás.}
{139}{}{¿El Refugio 15? ¿Quieren hacer un trato? Interesante. Habla con Gunther, ahí atrás.}
{140}{}{Puedes decírselo tú mismo. Sólo tienes que ir a hablar con Gunther.}
{141}{}{Eso no suena bien. Ahora, si me perdonas, tengo trabajo que hacer.}
{142}{}{Tengo que contarle algo.}
{143}{}{Bien. Dile que hay un espía en su oficina.}
{144}{}{Tan sólo dile que quiero verla. ¿Entendido?}
{145}{}{Pues bien, no puedo ayudarte con eso.}
{146}{}{(Continuar)}
{147}{}{Oh, nada. Error mío. Dijiste 13, ¿verdad? Bueno, no sé nada sobre eso.}
{148}{}{(Continuar)}
{149}{}{Soluciono problemas. Me cargo a los malos. Quiero dinero.}
{150}{}{Dile que he resuelto su problema con los okupas.}
{151}{}{¿Darion está muerto? Oh, perdóname. Entra directamente.}
{152}{}{¿En serio? Bueno... estoy seguro de que es una maravillosa noticia. ¿Te enteraste de algo más?}
{153}{}{No.}
{154}{}{Sí, hay algo más... algo acerca de un espía.}
{155}{}{Quizá deb... quiero decir, me alegro de que todo haya terminado. Entra directamente.}
{500}{}{Perdóname, pero no puedes entrar aquí sin permiso.}
{501}{}{Tengo que pedirte que dejes de manipular eso.}
{502}{}{Este es el último aviso: vete o afronta las consecuencias.}
{503}{}{Seguridad: por favor, ocupaos de nuestro "invitado".}
