{100}{}{Ves a un esclavista.}
{101}{}{Esta parece ser la dueña.}
{102}{}{Esta parece ser la dueña.}
{200}{}{Ahí estás.}
{201}{}{Ahora, morirás.}
{202}{}{Gracias, Albóndiga. Eres fantástico.}
{300}{}{¿Estas drogado con Jet, o algo así?}
{301}{}{¿Jerga? Es quien está a cargo de las computadoras?}
{302}{}{Esto es propiedad privada, así que muévete.}
{303}{}{Necesitas aprender modales.}
{304}{}{Es bueno tenerte con nosotros.}
{305}{}{Hola. ¿Cómo te va?}
{306}{}{¿Aún no le has dado de palos a ningún esclavo?}
{307}{}{Hola de nuevo.}
{308}{}{¿Te marchas a otra cacería de esclavos?}
{309}{}{Las cosas están muy calmadas por aquí.}
{310}{}{¿Cuando voy a ver algo de acción?}
{311}{}{Bagging slaves always brings a smile to my face.}
{312}{}{Las cacerías de esclavos son un desmadre.}
{313}{}{Eh, amigo, me alegro de tenerte con nosotros.}
{400}{}{Eh. ¿Qué crees que estas haciendo?}
{401}{}{Metzger sent me. I need to speak with whoever is in charge here.}
{402}{}{Tengo información que podría interesarte.}
{403}{}{I was called because of a rodent problem. Namely all of you here.}
{404}{}{[The man's eyes flare up.] You've picked the wrong group to fuck with. HEY GUYS, WE GOT AN INTRUDER!}
{405}{}{[He looks up and down your party members.] I think we might be interested. Go inside and speak with Don.}
{406}{}{Isn't it a little early for another shipment? What does Metzger need?}
{407}{}{He needs a few healthy slaves. Specifically female slaves, if you know what I mean.}
{408}{}{Hehe. I sure do. Well, go inside and speak to Don. I'm sure he's got what the boss needs.}
{409}{}{Umm...well, he uhh, said he needs more slaves.}
{410}{}{More slaves? He got a huge shipment last week. You're full of shit and I don't have time for this. Leave now
 or you'll find a bullet in your head.}
{411}{}{Me marcho.}
{412}{}{Creo que te mataré lentamente.}
{500}{}{Umm..uhh...the boss sent me.}
{501}{}{The "boss" huh? Sounds like your full of shit me. Looks like we got a trespasser.}
{502}{}{Listen, I'm on orders from the boss. You know how he gets when we keep him waiting.}
{503}{}{Metzger sent you, huh? Man, he can be a real pain sometimes. But, uh, (The man fidgets) don't tell anyone I said that.}
{504}{}{Yep, Metzger sent me alright. Now, I need to speak with whose in charge here.}
{599}{}{Vuelve a tocarme y morirás.}
{600}{}{¡Jódete, capullo!}
{800}{}{[HECHO]}
{900}{}{What the!? Rangers! Shit, how did they find us. Alright, time to kick some ass!}
