{100}{}{Ves a un guerrero de la tribu.}
{101}{}{Ves a Sulik.}
{102}{}{Ves a una mujer de aspecto fuerte y sólido con aire de autoridad.}
{150}{}{[FIN]}
{200}{}{Sulik! [She catches herself and begins to whisper.] Do the spirits be teasing, or is that really you, brother?}
{201}{}{Me? No, I'm the Chosen One. You must be thinking of old bone nose here.}
{202}{}{[Sulik rushes to the gate door and clasps the outstretched hands of his sister. You turn away to give some privacy to their emotional reunion. Moments later, a twig snaps outside the building. Sulik lets go of his sister and reaches for his weapon as he glances at the door. No more sounds come from outside.]}
{203}{}{[MÁS]}
{204}{}{[Sulik's sister turns to you.] Bonespirits say you be leading Sulik. Name's Kurisu, but now not the time for proper greetin'. Please, you needin' to get us out of cage and away from de wicked men ruled by spirits of lust. [She sneers and spits in the dirt.] Filthy dogs will not be laying hands on us again. [Upon hearing this, Sulik's eyes widen as his face contorts with rage. He reaches for his weapon.]}
{205}{}{Hold on there, Sulik, we're outnumbered here. Let me see if I can lockpick this door and we can sneak our way
 out of here.}
{206}{}{Hold on there, Sulik, we're outnumbered here. I got the key to this door. Let's keep it quiet and we'll sneak our
 way out of here.}
{207}{}{[You nod at Sulik] These bastards will pay. Lock and load ol' buddy.}
{208}{}{[A few minutes pass by and you finally hear a click from the lock. The door swings open.]}
{209}{}{[You turn to Kurisu.] Alright, stay close and keep your head down. [To the other slaves.] Keep quiet and head for the woods.}
{210}{}{[A few minutes pass by and you are unsuccessful at unlocking the door.]}
{211}{}{There must be another way to unlock this door. Let me see if I can get a key somehow. Wait here, I'll be back for you.}
{212}{}{Alright Sulik, it's time for your plan. Time to take out the trash.}
{213}{}{[You put the key in the lock and unlock the gate, it screeches as it opens.]}
{214}{}{Any luck, fren? Please hurry.}
{215}{}{No, aún no. Sigo trabajando en ello.}
{216}{}{Tengo que salir de aquí.}
{217}{}{Why there be so much commotion out there? Ah, I sense many have gone to join the spirits. Who be... Sulik? Do the spirits be teasing, or is that really you, brother?}
{218}{}{Why there be so much commotion out there? Ah, I sense many have gone to join the spirits. And I sense you be the one sending em. What you be needin', Ghost-maker?}
{219}{}{He venido a rescatarte.}
{221}{}{Praise the spirits! Please, you needin' to get us out of cage. Away from this evil place.}
{222}{}{Spirits praise you! Now I must go and return to my people. Long have I been missed. Please, stop by my village. It be near the Great Salt Water, a few days south west of here. Thank you, fren.}
{223}{}{[Sulik rushes to the gate door and clasps the outstretched hands of his sister. You turn away to give some privacy to their emotional reunion. Moments later, his sister turns to you.] Bonespirits say you be leading Sulik. Name's Kurisu, but now not the time for proper greetin'. The Slavers, they be dead, yes?}
{224}{}{Es un supervisor de esclavos.}
{225}{}{Praise the spirits! Please, unlock this door. We eager to go from this evil place.}
{226}{}{No te preocupes. No lo haré.}
{227}{}{De acuerdo, venid a por mí.}
{400}{}{Muévete.}
{401}{}{Por favor, date prisa. Quiero volver a casa.}
{410}{}{[You turn to Kurisu.] Wait, I don't want to leave here until I free the slaves in the other holding pens. You wait
 here until I free everyone from this camp. [To the other slaves.] Keep quiet and head for the woods. I'll handle the guards.}
{500}{}{If you be choosin' me for a lay, you best expect a fight -- wait, you don't be having the demon mark on your head. Who you be?}
{501}{}{"Yo soy el Elegido". Y una mierda.}
{502}{}{Me llamo }
{503}{}{. ¿Quién eres?}
{510}{}{My name be Kurisu. I come from tribe to south west, sits next to the Great Salt Water. Slavers got me. Got others too, but they been sent on. They say they ain't done with me. Be keeping me around for their wicked pleasure. Please, you needin' to get us out of cage and away from de evil men.}
{511}{}{Don't worry I'm here to get you out. I got a key and permission to take you out of here.}
{512}{}{De acuerdo, venid a por mí.}
{530}{}{It be safe yet? You sent the slavers to the spirits?}
{531}{}{Sí, veamos qué tienes.}
{532}{}{Yes, but let me free all the slaves here first before we go.}
{533}{}{Aún no. Volveré cuando lo haya hecho.}
{600}{}{Praise the spirits, we be home at last! Thank you so much, fren.}
{601}{}{De nada. Ahora lárgate de aquí.}
{602}{}{Was trading in nearby village. Slavers came. Much bloodshed and chaos. Then, everything go dark. Awoke in packed cage reeking of shit. Soon moved to smaller cage, with ones they like to be keeping. Peeped many slaves come and go. Sad to see people be treated like cattle.}
{603}{}{Yeah, slavery is certainly a horrible thing. I'm sorry you had to go through that, Kurisu. So, what are you gonna do now?}
{604}{}{Slavers hurt me, but I far from broken. The spirits guided you to ensure my freedom. Clearly, the spirits be planning something big for me. Spirits got big plans for you, too. And brother Sulik. He will be much missed, but the spirits say his place is walking by-and-by with you. Hell, even Grampy Bone like you, so I know Sulik in good hands. You take care.}
{605}{}{Gracias. Hasta otra.}
{606}{}{Slavers hurt me, but I far from broken. The spirits guided you to ensure my freedom. Clearly, the spirits be planning something big for me. Soon, I think I be going to hunt down brother. Knowing Sulik, he prolly got in trouble, trying to come help me. Now, perhaps I be the one helping him.}
{607}{}{Actually, I think I've seen your brother. Face full of tattoos and a big bone in the nose, right?}
{608}{}{That be Sulik alright! And Grampy Bone, too! Please, could you go bring Sulik home? I be missing that man so much.}
{609}{}{No problem, I'll bring him here. See you around, Kurisu.}
{610}{}{No creo que pueda hacer eso.}
{611}{}{Sulik... dead? Truly, this be a dark day. I know he be with Grampy now, but Sulik... he will be much missed. [She looks away as tears fill her eyes.] Please... I need being alone now. Thank you... for bringing me home.}
{650}{}{Hello, fren. Any lu-- Sulik!}
{651}{}{[MÁS]}
{652}{}{[Kurisu rushes to Sulik, who sweeps her up into an embrace. You turn away to give them some privacy during their emotional reunion. Several moments later, Kurisu turns to you with a grin as she wipes tears from her eyes.] Thank you, fren, for finding brother. Spirits got big plans for you and Sulik. He will be much missed, but the spirits say his place is walking by-and-by with you. Hell, even Grampy Bone like you, so I know Sulik in good hands. You take care.}
{653}{}{Hello, fren. You be having luck finding brother Sulik?}
{654}{}{Aún no. Volveré cuando lo haya hecho.}
{700}{}{Gracias de nuevo por ayudarnos.}
{701}{}{Brother Sulik will be much missed.}
{800}{}{¡Los espíritus están de mi lado!}
{810}{}{Get back in the building, Kurisu! I'll handle this.}
{820}{}{Por favor, no quemes la casa.}
{900}{}{Me? No, me Chosen One. You talk Sulik?}
{910}{}{Si, yo hago.}
{920}{}{He tenido suerte.}
{921}{}{Intentaré darme prisa.}
{922}{}{[You nod at Sulik] We fight bad men now.}
{923}{}{Todavía busco.}
{930}{}{[You turn to Kurisu.] I protect yoo. [To the other slaves.] Go home.}
{940}{}{Lockpick no work. I look for key. Yoo wait.}
{941}{}{Lockpick no work. [You turn to Sulik] We fight bad men now.}
{950}{}{Yo Thearn. ¿Quién tú?}
{951}{}{Yo }
{952}{}{Hola. ¿Quién tú?}
{960}{}{Quiero irme a casa.}
{961}{}{Sólo necesito una mano para matarte.}
{970}{}{Vale. Marcho ahora.}
{971}{}{Yes, bad men no good. What yoo do now?}
{972}{}{Gracias. ¡Adiós!}
{973}{}{I know Sulik. Sulik me friend. He talk like me. He talk with bone in nose.}
{974}{}{Tráeme mi libro.}
{975}{}{Lo siento. Está muerto.}
{976}{}{Todavía busco.}
{1000}{}{You reunite Sulik and his sister.}
{2000}{}{Tengo los planos del vertibird para ti.}
{2001}{}{First you be saving me. Then you be saving the world. You quite the hero.}
{2002}{}{Nosotros no necesitamos más hijos y no importa.}
