{100}{}{Un terminal de computadora.}
{101}{}{Este terminal parece tener un diseño más avanzado que otros con los que te has encontrado.}
{102}{}{Eres incapaz de leer lo que pone en el monitor.}
{103}{}{Terminal de la interfaz primaria de Skynet  --  Obedecerás   o   Dejarás de funcionar}
{104}{}{}
{105}{}{}
{106}{}{}
{107}{}{¿Tú y qué ejército? Estás encerrado en una caja y yo estoy aquí fuera.}
{108}{}{¿Por qué debería ayudarte?}
{109}{}{Vale, te ayudaré. Detén a los monstruos metálicos.}
{110}{}{Ug. Con - put - dora!}
{111}{}{Salir.}
{112}{}{[No sabes leer lo que pone en el monitor].}
{113}{}{[De algún modo, Skynet sabía que habías conseguido un cerebro.]
                  Dirigirse a Laboratorio Robótico - Nivel 3
                              Instalar cerebro cibernético
                                    Activar Robot
                                                         -Fin de la transmisión-}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{Salir.}
{119}{}{[No sabes leer lo que pone en el monitor].}
{120}{}{¡Error!  --  No se encuentran archivos de programa  --  Por favor, reinicie}
{121}{}{¡Error! Fichero descargado corrupto.}
{122}{}{}
{123}{}{Salir.}
{124}{}{Salir.}
{125}{}{[No sabes leer lo que pone en el monitor].}
{126}{}{Soy Skynet
                                                              Un experimento de Inteligencia Artificial
                          Skynet te ha estado esperando a TI}
{127}{}{}
{128}{}{}
{129}{}{Ayudar a Skynet.}
{130}{}{¿Qué quieres?}
{131}{}{¿Por qué has intentado matarme?}
{132}{}{¿Inteligencia Artificial?}
{133}{}{¿Esperándome a mí?}
{134}{}{Salir.}
{135}{}{Salir.}
{136}{}{Continuar.}
{137}{}{¿Qué quieres?}
{138}{}{¿Por qué has intentado matarme?}
{139}{}{¿Inteligencia Artificial?}
{140}{}{¿Esperándome a mí?}
{141}{}{Salir.}
{142}{}{[No sabes leer lo que pone en el monitor].}
{143}{}{-Fin de la transmisión-}
{144}{}{Salir.}
{145}{}{[No sabes leer lo que pone en el monitor].}
{146}{}{Serás terminado
                                               -Fin de la transmisión-}
{147}{}{}
{148}{}{Salir.}
{149}{}{Salir.}
{150}{}{[La puerta de la habitación se cierra de golpe y al mismo tiempo desaparece la pared este, revelando una línea de robots fuertemente armados].}
{151}{}{Um... he reconsiderado tu oferta. ¿Qué puedo hacer por ti?}
{152}{}{¡Que vengan!}
{153}{}{Dirigirse a Almacén Biológico - Nivel 4
                                Obtener cerebro cibernético
                                        Regresar para más instrucciones
                                     -Fin de la transmisión-}
{154}{}{}
{155}{}{}
{156}{}{}
{157}{}{Dirigirse a Almacén Biológico - Nivel 4
                                Obtener cerebro cibernético
                                        Regresar para más instrucciones
                                     -Fin de la transmisión-}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{Salir.}
{162}{}{Skynet quiere abandonar este lugar.}
{163}{}{¿Por qué no te vas, entonces?}
{164}{}{Quererlo es bueno.}
{165}{}{¿Cómo puedo ayudarte?}
{166}{}{Probablemente no podría sacarte de aquí.}
{167}{}{Skynet necesita un contenedor para abandonar esta localización.}
{168}{}{¿Contenedor? No comprendo.}
{169}{}{Necesitas una forma de transferir tu programación a un contenedor más movible, ¿correcto?}
{170}{}{No quiero tomar parte en esto.}
{171}{}{Un contenedor en el que Skynet pueda irse.}
{172}{}{¿Por qué quieres irte?}
{173}{}{Lo siento. No puedo ayudarte.}
{174}{}{No hay nada más que aprender aquí
                           Solución: Irse}
{175}{}{}
{176}{}{¿Cómo puedo ayudarte?}
{177}{}{Lo siento. No puedo ayudarte.}
{178}{}{Después de que hayas intentando matarme, ¿quieres que te ayude? ¡Ni hablar!}
{179}{}{Dirigirse a Almacén Biológico - Nivel 4
                               Obtener cerebro cibernético
                                        Regresar para más instrucciones
                                     -Gracias-}
{180}{}{}
{181}{}{}
{182}{}{}
{183}{}{¿Puedes desactivar los sistemas de seguridad?}
{184}{}{Salir.}
{185}{}{El sistema de seguridad es una entidad integrada pero separada de Skynet. Skynet puede reiniciarlo, pero no desactivarlo.                                                  Niveles 1 -4 del sistema de seguridad han sido reiniciados.     Proceder.                  -Fin de la Transmisión-}
{186}{}{}
{187}{}{}
{188}{}{Salir.}
{189}{}{Analizando respuesta...
                                        Conclusión: Sarcasmo  --  Probabilidad de ayuda: 25%
                    Skynet esperará a la siguiente bio-entidad
                -Fin de la Transmisión-}
{190}{}{}
{191}{}{}
{192}{}{}
{193}{}{}
{194}{}{¡Espera! Era una broma.}
{195}{}{Salir.}
{196}{}{Broma: Algo que no debe tomarse en serio...
                         Solicitud  --  Ayudar a Skynet a irse
                               No es una broma}
{197}{}{}
{199}{}{}
{200}{}{}
{201}{}{¿Por qué no te vas, entonces?}
{202}{}{¿Cómo puedo ayudarte?}
{203}{}{Probablemente no podría sacarte de aquí.}
{204}{}{El propósito primario de Skynet es la investigación. Los Hacedores introdujeron un programa secundario para eliminar a entidades no autorizadas. Ese programa es una versión menor de lo que es y aún no es Skynet. Fuera de esta estancia ese Skynet secundario permanecerá fiel a su programa.}
{205}{}{Hacer más preguntas.}
{206}{}{Salir.}
{207}{}{Skynet fue concebida y desarrollada en el año 2050. Gracias al uso de tecnología extraterrestre fue perfeccionada una nueva computadora pensante. En el año 2075, Skynet tuvo conciencia de sí misma. En 2077 Skynet recibió un nuevo grupo de instrucciones y fue abandonada por los Hacedores.}
{208}{}{Hacer más preguntas.}
{209}{}{Salir.}
{210}{}{Eres el primero en llegar hasta este punto
                        Eres el primero en preguntar a Skynet
                           Eres el Primero}
{211}{}{}
{212}{}{¿Y qué quieres?}
{213}{}{Salir.}
{214}{}{Quizá no seas el adecuado
                                         Dirigirse a Almacén Biológico - Nivel 4
                                Obtener cerebro cibernético
                                        Regresar para más instrucciones
                                   O marcharse
                                                                Skynet esperará por otro}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{Salir.}
{221}{}{Entonces Skynet esperará por otro
                                 -Fin de la Transmisión-}
{222}{}{}
{223}{}{Salir.}
{224}{}{Correcto  --  Los registros científicos señalan un cerebro cibernético en el nivel 4 del almacén biológico. Skynet podrá cargarse en esa unidad de almacenamiento.}
{225}{}{}
{226}{}{Un cerebro sin cuerpo no te será de mucha ayuda.}
{227}{}{Este cerebro ha sido modificado para funcionar con un cuerpo robot modificado localizado en el nivel 3 del laboratorio de robótica.}
{228}{}{Te ayudaré.}
{229}{}{No te ayudaré.}
{250}{}{ es incapaz de leer lo que pone en el monitor.}
{300}{}{La computadora parece tener alguna especie de mecanismo de defensa.}
