# quick looks
# unknown
{100}{}{Ves una máquina extraña. }
# normal
{101}{}{Ves una máquina tragaperras. }
# high roller
{102}{}{Ves una reluciente máquina tragaperras. }
# jackpot
{103}{}{Ves una brillante máquina tragaperras. }

# examines
# unknown
{130}{}{Tiene tres ojos y un brazo.}
# bet amount
{140}{}{La apuesta mínima es de }
{141}{}{ dólares.}
# normal
{150}{}{Jurarías que puedes verla por el rabillo del ojo, mirándote. }
{151}{}{Su estructura brillante y su palanca dorada brillan seductoramente bajo las luces. }
# high roller
{165}{}{Está pensada para los grandes apostadores. }
# jackpot
{180}{}{Su alto premio te resulta muy atractivo. }

# slot machine first play message
{200}{}{(Te tiembla la mano mientras buscas tus monedas. La máquina sigue susurrándote). *Vamos, cariño… eso
 es… acércate… no me hagas esperar…*}
{201}{}{Ves una máquina tragaperras. Su estructura brillante y su palanca dorada brillan seductoramente bajo las luces. Su ranura para las monedas
 te atrae, y sientes cómo te ruborizas por la expectación.}
{202}{}{(Te tiembla la mano mientras buscas tus monedas. La máquina sigue susurrándote). *Venga, cielo… eso
 es… agarra la palanca… sujétala con firmeza… vamos…*}

# insert coin messages
{250}{}{Introduces }
{251}{}{ dólares. }
{252}{}{Juegas tus últimos }
{253}{}{ dólares.}
{254}{}{Lo dejas para otro día.}
{255}{}{Te has arruinado. Tienes que dejarlo para otro día.}
{256}{}{Lo dejas para otra noche.}
{257}{}{Te has arruinado. Tienes que dejarlo para otra noche.}
{258}{}{¡Ya está bien! ¡Me marcho!}
{259}{}{¡Ya está bien! ¡Me marcho!}

# this is the message for when the machine is played
{500}{}{El rodillo de la máquina gira... }
# this goes between every symbol, example:   "cherry... orange... melon... "
{599}{}{... }

# pay off types
{600}{}{Nada. }
{601}{}{Una cereza. }
{602}{}{Dos cerezas. }
# Three [symbol].
{603}{}{Tres }
{613}{}{. }
{604}{}{¡PREMIO! }
{605}{}{¡¡¡PREMIO DOBLE!!! }

# payoff amount message
{700}{}{El premio es de }
{701}{}{  dólares.}
# symbol types
# singular
{1001}{}{cereza}
{1002}{}{naranja}
{1003}{}{ciruela}
{1004}{}{campana}
{1005}{}{lingote}
{1006}{}{melón}
{1007}{}{siete}
# plural
{1101}{}{cerezas}
{1102}{}{naranjas}
{1103}{}{ciruelas}
{1104}{}{campanas}
{1105}{}{lingotes}
{1106}{}{melones}
{1107}{}{sietes}

# float messages
{2000}{}{*Ven a jugar un rato conmigo, vaquero*.}
{2001}{}{*Hola, guapo*.}
{2002}{}{*Pon una moneda y tira de la palanca. Seré buena contigo*.}
{2003}{}{*Tick… Tick… Tiiiiick…*}
{2004}{}{*Ding*}
{2005}{}{*Bing*}
{2006}{}{*Kaaa-ching*}
{2007}{}{*Zzzzzzz*}
{2008}{}{*Ring-a-ling*}
{2009}{}{*Dingity-ding*}
{2010}{}{*Hola, hermosura. Ven a jugar un rato conmigo*.}
{2011}{}{*Hola, hermosura*.}
{2012}{}{*Mira qué cosita tan guapa. ¿Por qué no vienes a jugar conmigo?*}

# 3.  NO MONEY (WTG, 9)
# no money to play
{2175}{}{(Miras a la máquina mientras te das cuenta de que no tienes suficiente dinero para jugar, y maldices tu pobreza. Quizá en otra ocasión…)}
{2176}{}{Te marchas.}
# won jackpot block
{2185}{}{(La señal luminosa de "FUERA DE SERVICIO" en la máquina está parpadeando).}
{2186}{}{Te marchas.}

# 4. RETARD (WTG)
{2100}{}{Ves una caja rara de metal dorado con tres ojos y un brazo. Es una de las
 cosas más bonitas que has visto.}
{2101}{}{Yo }
{2102}{}{ ¿Quién tú?}
{2103}{}{Quiero a MAMÁ. }
{2104}{}{ extraño ARR-YO. Quiero ir a casa.}
{2105}{}{(Le das la mano)}
{2106}{}{eres mutante raro.}
{2107}{}{¡Alabemos el Refugio! ¡Alabemos el Refugio!}
{2108}{}{¿Eres un chip de agua?}
{2109}{}{Te alejas, buscando otras cosas brillantes.}
{2110}{}{Te marchas.}

# 5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{2130}{}{La rara caja de metal dorado con tres ojos y un brazo no contesta.}
{2131}{}{YO }
{2132}{}{¡TU ME CONTESTAS!}
{2133}{}{(Le das la mano)}
{2134}{}{Yo soy hijo de Morador de Refugio. Tú me hablas AHORA.}
{2135}{}{eres mutante raro.}
{2136}{}{¿Eres un chip de agua?}
{2137}{}{Te alejas, buscando otras cosas brillantes.}
{2138}{}{(Te marchas).}

# 6.  RETARD PULLS HANDLE (4, 5)
{2151}{}{Le agarras el brazo y lo sacudes con fuerza. ¡Al hacerlo, escuchas un *bzzzzzzz,* y la caja
 habla! "Por favor… introduce… moneda".}
{2152}{}{Aighhhhh! Robot! Robot! Funcionaaaaar}
{2153}{}{(Te marchas).}

# slot machine taunts loss
# male
{2200}{}{(La oyes reírse de ti).}
{2201}{}{*Ja ja ja, ¿por qué no lo dejas, cariño?*}
{2202}{}{*Quizá deberías dejar que otro tire de mi palanca*.}
# any
{2203}{}{(Una débil risa maníaca sale de la máquina).}
{2204}{}{(Escuchas a la máquina reírse de ti).}
{2205}{}{(La máquina se mofa de ti).}
{2206}{}{*Venga, perdedor, no me dejes ahora*.}
# female
{2207}{}{*Tengo lo que quería de ti, querida. ¿Por qué no lo dejas?*}
{2208}{}{*¡Escoria!*}
{2209}{}{*Ten cuidado de que la puerta del casino no te golpee en el culo cuando salgas*.}

# slot machine taunts win
# male [3X - 1X]
{2247}{}{*¡Aaaaaah! ¡Eso es, cariño! ¡Oh Dios, sí! ¡Sí! ¡Sí, otra vez! ¡Más rápido! ¡Más fuerte! ¡A qué estás esperando?! ¡Más!*}
{2248}{}{*Eso es, cariño… sigue meneando la palanca… más rápido, más fuerte, más rápido… hazlo ahora…*}
{2249}{}{*Vamos, cielo… eso le ocurre a todos al menos una vez… inténtalo otra vez… por favor…*}
# any
{2250}{}{*¡Por favor, no me dejes así ahora! ¡Ahora te necesito más que nunca!*}
# female [1X - 3X]
{2251}{}{*Vamos, cariñito… inténtalo otra vez… agarra la palanca… agárrala con fuerza… hazlo ahora…*}
{2252}{}{*Eso es, cariño… sigue meneando la palanca… más rápido, más fuerte, más rápido… hazlo ahora…*}
{2253}{}{*Ennnnghhhh! ¡Eso es, cariño! ¡¿Quién es tu macho?! ¡¿Quién es tu macho?!! Hazlo de nuevo! ¡Menéala más fuerte esta vez! ¡Más fuerte!*}

# 13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{2280}{}{(Ves una máquina tragaperras. Su estructura brillante y su palanca dorada resplandecen seductoramente bajo las luces de Nuevo Reno. Su ranura para las monedas te atrae, y sientes cómo te ruborizas por la expectación. Mientras la miras, te guiña uno de sus tres ojos. Escuchas una voz grave susurrando desde la ranura para monedas). *¡Vaya, vaya! Hoooola, cielo. ¿Le harás pasar a esta nena un buen rato?*}
{2281}{}{(Ves una máquina tragaperras. Su fuerte y tosca estructura y su palanca dorada brillan como el sol bajo las luces de Nuevo Reno. Su ranura para las monedas te atrae seductoramente, y sientes que los muslos te arden por la excitación. Mientras la miras, de repente una fuerte voz masculina susurra desde la ranura para monedas). *Jamás he visto a una mujer tan hermosa como tú antes, señorita. ¿Quieres una oportunidad conmigo?*}
{2282}{}{::Te pellizcas::}
{2283}{}{Uh… ¿hola?}
{2284}{}{::Respiras profundamente, y te vas.::}

# 14. DRUNK CONVERSATION 1 (13)
{2300}{}{*Sigo aquí, preciosa.* (La máquina baja el tono de voz). *Venga, vamos… ¿quieres hacer una apuesta?*}
{2301}{}{*Todavía estoy aquí, cielo.* (La máquina baja el tono de voz). *Eres todo un hombre, ¿sabes? Venga… ¿no quieres meter unas monedas en mi pequeña ranura?*}
{2302}{}{¿Quieeen *eres* túuu?}
{2303}{}{Cl-laro que har-ré una apuesssta}
{2304}{}{Mejor que me marche antes de que te meta algo de lo que me arrepienta. (Te vas).}
{2305}{}{::Respiras profundamente, y te vas.:: (Te vas).}

# 15. DRUNK 2 (14)
{2320}{}{*Soy tu hombre ideal*. (La máquina te guiña un ojo). *Dame algunas monedas, y te daré placer de formas en que ningún hombre te ha dado placer NUNCA*.}
{2321}{}{*Soy tu hombre ideal, preciosa. Todo lo que quiero es un poco de atención. ¿Puedes prestarme un poco de atención? Venga, ¿sólo una o dos monedas?*}
{2322}{}{¿No podemos s-solo hablar?}

# 16. DRUNK 3 (15)
{2340}{}{*Por supuesto que puedo, cielo, por supuesto que puedo*. (La máquina parece comprensiva). *¿Que le preocupa a tu cabecita?*}
{2341}{}{*Por supuesto que puedo, cielo, por supuesto que puedo*. (La máquina parece comprensiva). *¿Qué te preocupa, guapetón?*}
{2342}{}{Hecho de menos a MAMÁ y a ARROYO y… no puedo encontrar el GECK y… *sniff*}
{2343}{}{Hecho de menos a MAMÁ y Arroyo fue ATACADO y… no sé dónde están… y… *sniff*}
{2344}{}{Tengo que arreglar el gran barco… y no sé CÓMO… y m-m-mi MAMÁ se ha IDO y… *sniff*}
{2345}{}{He terminado de jugar… y ahora no hago más que dar vueltas y… me preocupa que todo haya ACABADO y… *sniff*}
{2346}{}{Es s-sólo que Fhallout no s-soporta mi maldita tarjeta gráf-fica y gasté tanto *dinero* y *sniff*}
{2347}{}{He intentado ha-hacerlo bien pero c-creo que he gastado *mal* todos mis puntos… y ahora s-soy una m-mierda de personaje… y… *sniff*}
{2348}{}{Estoy teniendo una co-cor-conversación con una máquina tragaperras, estoy bien jodido.}

# 17. DRUNK 4 (16)
{2370}{}{*Vamos, vamos... que tu preciosa cabecita no se preocupe más por eso… tan solo deja que yo me ocupe de todo. Venga, descansa tu cabeza sobre mí. Vamos. Deja que salga todo*.}
{2371}{}{*Vamos, vamos... no te preocupes más, cielo… tan solo deja que yo me ocupe de todo. Venga, descansa tu hermosa cabeza sobre mí. Vamos. Deja que salga todo*.}
{2372}{}{Gracias, máquina tragap-perras *sniff* eres-eres la mejor}
{2373}{}{T-tú eres la *única* persona b-buena que he encontrado y todo el m-mundo hasta ahora ha intentado hacerme *daño* y quitar-me el dinero y… *sniff*}

# 18. DRUNK 5 (17)
{2380}{}{*¿Seguro que estarás bien, cariño? No me siento cómoda dejando que te vayas solo cuando estás así*.}
{2381}{}{(Reposas tu cansada cabeza sobre la máquina).}
{2382}{}{*¿Estarás bien, cielo? No me siento cómoda dejando que te vayas solo cuando estás así*.}
{2383}{}{Esssstaré bdien… grac-cias por hablar con-nmigo, m-m-máquina te quieeeeeero}

# 19. DRUNK 6 (18)
{2400}{}{*¡Eres la única heroína que tenemos en este mundo binario de bastardos y ladrones! Cuídate mucho, ¿de acuerdo, cariño?* (Te das la vuelta). *Vete antes de que me ponga demasiado tierna*.}
{2401}{}{(Una lágrima parece formarse en una de las ventanas). }
{2402}{}{*¡Eres el único héroe que tenemos en este mundo binario de bastardos y ladrones! Tú… tú… cuídate mucho, ¿de acuerdo, cielo?* (Te das la vuelta). *Vete antes de que empiece a llorar*.}
{2403}{}{Adioooos}

# rollin' messages
{3000}{}{¡Vamos, }
{3001}{}{! ¡Esta nena necesita un nuevo par de zapatos!}
{3002}{}{! ¡Papá necesita un rifle de plasma nuevo!}

# can't play
{4000}{}{Parece que alguien está bloqueando la máquina.}

{5000}{}{Jinx la máquina te entrega todo su dinero.}
{5001}{}{La máquina parece quedarse congelada, y entonces escuchas un rumor leve y una avalancha de monedas comienza a caer desde el
 dispensador.}
{5002}{}{[Recoges el dinero y te marchas].}
