{100}{}{Você vê um traficante de drogas.}
{101}{}{Você vê um traficante de drogas.}
{102}{}{Se você estiver olhando para lidar, eu tenho o material.}
{103}{}{Com certeza, me mostre.}
{104}{}{Talvez alguma outra hora.}
{105}{}{Encontrou o que precisa?}
{106}{}{Obrigado. Adeus.}
{200}{}{Você vê um bandido.}
{201}{}{Você vê um bandido.}
{202}{}{Estou aqui para proteção. Fale com o revendedor se quiser comprar.}
