{100}{}{Você abre o armário e encontra linhas de arquivos e anotações.}
{101}{}{Pesquisa da cômoda.}
{102}{}{Deixar.}
{103}{}{As you search through the records in the dresser, you notice a thin leather briefcase stuffed carefully deep in the back.}
{104}{}{Puxe o porta-documentos.}
{105}{}{Ignore a mensagem e continue lendo.}
{106}{}{30 minutos passam e você não encontra nada de importância. Tudo o que descobriu é que o Chade possui registros
  documentando cada momento de sua vida. Ele é um cara muito chato na verdade. Assim como você está prestes a fechar as gavetas, você
  ouve uma tosse da porta da frente e uma alça girando ...}
{107}{}{Puxe o porta-documentos.}
{108}{}{Inside the briefcase you find papers documenting a whole year's worth of skimming money from
 caravans by Chad.}
{109}{}{Wow, it really looks like Chad was skimming money. Apparently he is preparing to skip town as well,
 better tell Marcus all this.}
{110}{}{30 minutes pass and you find nothing of importance. All that you have found out is that Chad has records
 documenting every moment of his life. He's a pretty boring guy actually.}
