{100}{}{Corre!}
{101}{}{Ajuda!}
{102}{}{We're being attack by the surfacers.}
{103}{}{Nos deixe em paz.}
{104}{}{Can't we all just get along?}
{150}{}{Go back where you came from.}
{151}{}{Você não é procurado aqui.}
{152}{}{All you surfacers are alike.}
{153}{}{You will not escape.}
{200}{}{Groan!}
{201}{}{Boo!}
{202}{}{Moaaaaaaan.}
{203}{}{*Clank*}
{204}{}{*Clink*}
{250}{}{We used to live above ground.}
{251}{}{What's it like above ground?}
{252}{}{It's so BIG up there.}
{253}{}{What's the sun look like?}
{254}{}{Hello, surfacer.}
{300}{}{I knew we could trust you.}
{301}{}{Obrigado por nos ajudar.}
{302}{}{Bom ver você de novo.}
