{100}{}{Você precisa de %d pontos de ação.}
{101}{}{Sem munição.}
{102}{}{Alvo fora do alcance.}
{103}{}{Não é possível finalizar o combate com criaturas hostis nas proximidades.}
{104}{}{Linha de fogo bloqueada.}
{105}{}{Você não pode usar armas com os dois braços quebrados.}
{106}{}{Você não pode usar armas de duas mãos com um braço quebrado.}
{107}{}{Você não é forte o suficiente para usar esta arma corretamente.}
{108}{}{ e }
{200}{}{te deixou fora de combate}
{201}{}{derrubado}
{202}{}{perna esquerda quebrada}
{203}{}{perna direita quebrada}
{204}{}{braço esquerdo quebrado}
{205}{}{braço direito quebrado}
{206}{}{cego}
{207}{}{você morreu}
{208}{}{te deixa ferido}
{209}{}{criticamente}
{210}{}{em chamas}
{211}{}{perfura sua armadura}
{212}{}{sua arma explodiu}
{213}{}{sua arma foi destruída}
{214}{}{sua arma caiu}
{215}{}{perdeu seu próximo turno}
{216}{}{acertou em você mesmo}
{217}{}{perdeu o resto de sua munição}
{218}{}{tiro fracassado}
{219}{}{você se feriu}
{220}{}{bater aleatoriamente}
{221}{}{quebrar um membro aleatório}
{222}{}{você alcança os fragmentos}
{250}{}{te deixou fora de combate}
{251}{}{derrubado}
{252}{}{perna esquerda quebrada}
{253}{}{perna direita quebrada}
{254}{}{braço esquerdo quebrado}
{255}{}{braço direito quebrado}
{256}{}{cego}
{257}{}{você morreu}
{258}{}{te deixa ferido}
{259}{}{criticamente}
{260}{}{em chamas}
{261}{}{perfura sua armadura}
{262}{}{sua arma explodiu}
{263}{}{sua arma foi destruída}
{264}{}{sua arma caiu}
{265}{}{perdeu seu próximo turno}
{266}{}{acertou em você mesmo}
{267}{}{perdeu o resto de sua munição}
{268}{}{tiro fracassado}
{269}{}{você se feriu}
{270}{}{bater aleatoriamente}
{271}{}{quebrar um membro aleatório}
{272}{}{você alcança os fragmentos}
{300}{}{te deixou fora de combate}
{301}{}{derrubado}
{302}{}{quebrou sua perna esquerda}
{303}{}{quebrou sua perna direita}
{304}{}{quebrou seu braço esquerdo}
{305}{}{quebrou seu braço direito}
{306}{}{cego}
{307}{}{morreu}
{308}{}{te deixa ferido}
{309}{}{criticamente}
{310}{}{em chamas}
{311}{}{perfura sua armadura}
{312}{}{sua arma explodiu}
{313}{}{sua arma foi destruída}
{314}{}{deixou cair a arma}
{315}{}{perdeu seu próximo turno}
{316}{}{acertou em você mesmo}
{317}{}{perdeu o resto de sua munição}
{318}{}{tiro fracassado}
{319}{}{você se feriu}
{320}{}{bater aleatoriamente}
{321}{}{quebrar um membro aleatório}
{322}{}{você alcança os fragmentos}
{400}{}{te deixou fora de combate}
{401}{}{derrubado}
{402}{}{quebrou sua perna esquerda}
{403}{}{quebrou sua perna direita}
{404}{}{quebrou seu braço esquerdo}
{405}{}{quebrou seu braço direito}
{406}{}{cego}
{407}{}{morreu}
{408}{}{te deixa ferido}
{409}{}{criticamente}
{410}{}{em chamas}
{411}{}{perfura sua armadura}
{412}{}{sua arma explodiu}
{413}{}{sua arma foi destruída}
{414}{}{deixou cair a arma}
{415}{}{perdeu seu próximo turno}
{416}{}{acertou em você mesma}
{417}{}{perdeu o resto de sua munição}
{418}{}{tiro fracassado}
{419}{}{você se feriu}
{420}{}{bater aleatoriamente}
{421}{}{quebrar um membro aleatório}
{422}{}{você alcança os fragmentos}
{506}{}{Você}
{509}{}{Oops! %s foi atingido, em vez de %s!}
{511}{}{%s foi gravemente atingido %s, perdendo %d pontos de vida}
{512}{}{%s foi atingido %s perdendo %d pontos de vida}
{513}{}{%s foi atingido perdendo %d pontos de vida}
{514}{}{%s errou criticamente}
{515}{}{%s errou}
{520}{}{%s foi gravemente atingido, perdeu %d pontos de vida}
{521}{}{%s foi gravemente atingido %s perdendo 1 ponto de vida}
{522}{}{%s foi atingido %s e perdeu 1 ponto de vida}
{523}{}{%s foi atingido e perde 1 ponto de vida}
{524}{}{%s foi gravemente atingido e perde 1 ponto de vida}
{525}{}{%s foi gravemente atingido %s, sem sofrer nenhum dano}
{526}{}{%s foi atingido %s sem danos}
{527}{}{%s foi atingido sem sofrer nenhum dano}
{528}{}{%s foi gravemente atingido sem sofrer nenhum dano}
{533}{}{%s erro critico, perdeu 1 ponto de vida}
{534}{}{%s erro critico, perdeu %d pontos de vida}
{556}{}{Você}
{559}{}{Oops! %s foi atingido, em vez de %s!}
{561}{}{%s foi gravemente atingido %s, perdendo %d pontos de vida}
{562}{}{%s foi atingido %s perdendo %d pontos de vida}
{563}{}{%s foi atingido perdendo %d pontos de vida}
{564}{}{%s errou criticamente}
{565}{}{%s errou}
{570}{}{%s foi gravemente atingido, perdeu %d pontos de vida}
{571}{}{%s foi gravemente atingido %s perdendo 1 ponto de vida}
{572}{}{%s foi atingido %s e perdeu 1 ponto de vida}
{573}{}{%s foi atingido e perde 1 ponto de vida}
{574}{}{%s foi gravemente atingido e perde 1 ponto de vida}
{575}{}{%s foi gravemente atingido %s, sem sofrer nenhum dano}
{576}{}{%s foi atingido %s sem danos}
{577}{}{%s foi atingido sem sofrer nenhum dano}
{578}{}{%s foi gravemente atingido sem sofrer nenhum dano}
{583}{}{%s erro critico, perdeu 1 ponto de vida}
{584}{}{%s erro critico, perdeu %d pontos de vida}
{608}{}{Oops! %s foi atingido em vez de você!}
{609}{}{Oops! %s foi atingido, em vez de %s!}
{611}{}{%s é gravemente atingido %s, perdendo %d pontos de vida}
{612}{}{%s é atingido %s, perdendo %d pontos de vida}
{613}{}{%s é atingido, perdendo %d pontos de vida}
{614}{}{%s errou criticamente}
{615}{}{%s errou}
{620}{}{%s é gravemente atingido, perdendo %d pontos de vida}
{621}{}{%s é gravemente atingido %s, perdendo 1 ponto de vida}
{622}{}{%s é atingido %s, perdendo 1 ponto de vida}
{623}{}{%s é atingido, perdendo 1 ponto de vida}
{624}{}{%s é gravemente atingido, perdendo 1 ponto de vida}
{625}{}{%s é gravemente atingido %s, sem sofrer nenhum dano}
{626}{}{%s é atingido %s, sem sofrer nenhum dano}
{627}{}{%s é atingido, sem sofrer nenhum dano}
{628}{}{%s é gravemente atingido, sem sofrer nenhum dano}
{633}{}{%s erro critico, perdeu 1 ponto de vida}
{634}{}{%s erro critico, perdeu %d pontos de vida}
{708}{}{Oops! %s foi atingido em vez de você!}
{709}{}{Oops! %s foi atingido, em vez de %s!}
{711}{}{%s é gravemente atingido %s, perdendo %d pontos de vida}
{712}{}{%s é atingido %s, perdendo %d pontos de vida}
{713}{}{%s é atingido, perdendo %d pontos de vida}
{714}{}{%s errou criticamente}
{715}{}{%s errou}
{720}{}{%s é gravemente atingido, perdendo %d pontos de vida}
{721}{}{%s é gravemente atingido %s, perdendo 1 ponto de vida}
{722}{}{%s é atingido %s, perdendo 1 ponto de vida}
{723}{}{%s é atingido, perdendo 1 ponto de vida}
{724}{}{%s é gravemente atingido, perdendo 1 ponto de vida}
{725}{}{%s é gravemente atingido %s, sem sofrer nenhum dano}
{726}{}{%s é atingido %s, sem sofrer nenhum dano}
{727}{}{%s é atingido, sem sofrer nenhum dano}
{728}{}{%s é gravemente atingido, sem sofrer nenhum dano}
{733}{}{%s erro critico, perdeu 1 ponto de vida}
{734}{}{%s erro critico, perdeu %d pontos de vida}
{1110}{}{na cabeça}
{1111}{}{no braço esquerdo}
{1112}{}{no braço direito}
{1113}{}{no tronco}
{1114}{}{na perna direita}
{1115}{}{na perna esquerda}
{1116}{}{nos olhos}
{1117}{}{na virilha}
{1118}{}{lugar indefinido}
{1150}{}{na cabeça}
{1151}{}{na pata traseira esquerda}
{1152}{}{na pata traseira direita}
{1153}{}{no tronco}
{1154}{}{na pata dianteira direita}
{1155}{}{na pata dianteira esquerda}
{1156}{}{nos olhos}
{1157}{}{nas glândulas mamárias}
{1158}{}{lugar indefinido}
{1160}{}{na cabeça}
{1161}{}{na pata traseira}
{1162}{}{na pata traseira}
{1163}{}{no corpo}
{1164}{}{na pata dianteira}
{1165}{}{na pata dianteira}
{1166}{}{nos olhos}
{1167}{}{na virilha}
{1168}{}{lugar indefinido}
{1170}{}{no CPU}
{1171}{}{no manipulador}
{1172}{}{no manipulador}
{1173}{}{na estrutura}
{1174}{}{na unidade matriz}
{1175}{}{na unidade matriz}
{1176}{}{nos sensores}
{1177}{}{no regulador}
{1178}{}{lugar indefinido}
{1180}{}{na cabeça}
{1181}{}{no braço esquerdo}
{1182}{}{no braço direito}
{1183}{}{no tronco}
{1184}{}{na perna direita}
{1185}{}{na perna esquerda}
{1186}{}{nos olhos}
{1187}{}{na virilha}
{1188}{}{lugar indefinido}
{1190}{}{na cabeça}
{1191}{}{na pata esquerda}
{1192}{}{na pata direita}
{1193}{}{no corpo}
{1194}{}{na perna direita}
{1195}{}{na perna esquerda}
{1196}{}{nos olhos}
{1197}{}{na virilha}
{1198}{}{lugar indefinido}
{1210}{}{na cabeça}
{1211}{}{no braço esquerdo}
{1212}{}{no braço direito}
{1213}{}{no tronco}
{1214}{}{na perna direita}
{1215}{}{na perna esquerda}
{1216}{}{nos olhos}
{1217}{}{na virilha}
{1218}{}{lugar indefinido}
{1220}{}{na cabeça}
{1221}{}{na cauda}
{1222}{}{na garra}
{1223}{}{na carapaça}
{1224}{}{nas patas dianteiras}
{1225}{}{nas patas traseiras}
{1226}{}{nos olhos}
{1227}{}{no cérebro}
{1228}{}{lugar indefinido}
{1230}{}{na cabeça}
{1231}{}{na boca}
{1232}{}{na boca dianteira}
{1233}{}{no corpo}
{1234}{}{no saco flutuante}
{1235}{}{na cauda}
{1236}{}{no gânglio}
{1237}{}{no ovipositor}
{1238}{}{lugar indefinido}
{1240}{}{na cabeça}
{1241}{}{na pata esquerda}
{1242}{}{na pata direita}
{1243}{}{no corpo}
{1244}{}{na perna direita}
{1245}{}{na perna esquerda}
{1246}{}{nos olhos}
{1247}{}{na virilha}
{1248}{}{lugar indefinido}
{1250}{}{na cabeça}
{1251}{}{no braço esquerdo}
{1252}{}{no braço direito}
{1253}{}{no corpo}
{1254}{}{na perna direita}
{1255}{}{na perna esquerda}
{1256}{}{nos olhos}
{1257}{}{na virilha}
{1258}{}{lugar indefinido}
{1270}{}{na cabeça}
{1271}{}{no braço esquerdo}
{1272}{}{no braço direito}
{1273}{}{no tronco}
{1274}{}{na perna direita}
{1275}{}{na perna esquerda}
{1276}{}{nos olhos}
{1277}{}{na virilha}
{1278}{}{lugar indefinido}
{1460}{}{na cabeça}
{1461}{}{no braço esquerdo}
{1462}{}{no braço direito}
{1463}{}{no tronco}
{1464}{}{na perna direita}
{1465}{}{na perna esquerda}
{1466}{}{nos olhos}
{1467}{}{na virilha}
{1468}{}{lugar indefinido}
{1490}{}{na cabeça}
{1491}{}{no braço esquerdo}
{1492}{}{no braço direito}
{1493}{}{no tronco}
{1494}{}{na perna direita}
{1495}{}{na perna esquerda}
{1496}{}{nos olhos}
{1497}{}{na virilha}
{1498}{}{lugar indefinido}
{1500}{}{na cabeça}
{1501}{}{???}
{1502}{}{???}
{1503}{}{na estrutura}
{1504}{}{???}
{1505}{}{???}
{1506}{}{nos olhos}
{1507}{}{no CPU}
{1508}{}{lugar indefinido}
{1510}{}{na cabeça}
{1511}{}{no braço esquerdo}
{1512}{}{no braço direito}
{1513}{}{no tronco}
{1514}{}{na perna direita}
{1515}{}{na perna esquerda}
{1516}{}{nos olhos}
{1517}{}{na virilha}
{1518}{}{lugar indefinido}
{1520}{}{na cabeça}
{1521}{}{na pata raptorial}
{1522}{}{na pata raptorial}
{1523}{}{no abdômen}
{1524}{}{nas pernas}
{1525}{}{nas asas}
{1526}{}{nos olhos}
{1527}{}{no metatórax}
{1528}{}{lugar indefinido}
{1530}{}{no CPU}
{1531}{}{no manipulador}
{1532}{}{no manipulador}
{1533}{}{na estrutura}
{1534}{}{na unidade matriz}
{1535}{}{na unidade matriz}
{1536}{}{nos sensores}
{1537}{}{no regulador}
{1538}{}{lugar indefinido}
{1540}{}{no CPU}
{1541}{}{no manipulador}
{1542}{}{no manipulador}
{1543}{}{na estrutura}
{1544}{}{na unidade matriz}
{1545}{}{na unidade matriz}
{1546}{}{nos sensores}
{1547}{}{no regulador}
{1548}{}{lugar indefinido}
{1550}{}{na cabeça}
{1551}{}{na pata esquerda}
{1552}{}{na pata direita}
{1553}{}{no corpo}
{1554}{}{na perna direita}
{1555}{}{na perna esquerda}
{1556}{}{nos olhos}
{1557}{}{na virilha}
{1558}{}{lugar indefinido}
{1580}{}{na carapaça}
{1581}{}{na carapaça}
{1582}{}{na carapaça}
{1583}{}{na carapaça}
{1584}{}{na carapaça}
{1585}{}{na carapaça}
{1586}{}{na carapaça}
{1587}{}{na carapaça}
{1588}{}{lugar indefinido}
{1590}{}{na cabeça}
{1591}{}{na cauda}
{1592}{}{na garra}
{1593}{}{na carapaça}
{1594}{}{nas patas dianteiras}
{1595}{}{nas patas traseiras}
{1596}{}{nos olhos}
{1597}{}{no cérebro}
{1598}{}{lugar indefinido}
{1600}{}{na cabeça}
{1601}{}{no braço esquerdo}
{1602}{}{no braço direito}
{1603}{}{no tronco}
{1604}{}{na perna direita}
{1605}{}{na perna esquerda}
{1606}{}{nos olhos}
{1607}{}{na virilha}
{1608}{}{lugar indefinido}
{1650}{}{na boca}
{1651}{}{no talo}
{1652}{}{no talo}
{1653}{}{no talo central}
{1654}{}{nas raízes}
{1655}{}{nas raízes}
{1656}{}{nas antenas}
{1657}{}{na base}
{1658}{}{lugar indefinido}
{1660}{}{na cabeça}
{1661}{}{mísseis de mão}
{1662}{}{pistola de mão}
{1663}{}{no corpo}
{1664}{}{na perna direita}
{1665}{}{na perna esquerda}
{1666}{}{nos sensores}
{1667}{}{na parte inferior do tronco}
{1668}{}{lugar indefinido}
{1670}{}{na cabeça}
{1671}{}{na garra esquerda}
{1672}{}{na garra direita}
{1673}{}{no corpo}
{1674}{}{na perna direita}
{1675}{}{na perna esquerda}
{1676}{}{nos olhos}
{1677}{}{na virilha}
{1678}{}{lugar indefinido}
{1680}{}{na cabeça}
{1681}{}{na garra esquerda}
{1682}{}{na garra direita}
{1683}{}{no corpo}
{1684}{}{na perna direita}
{1685}{}{na perna esquerda}
{1686}{}{nos olhos}
{1687}{}{na virilha}
{1688}{}{lugar indefinido}
{1800}{}{na cabeça}
{1801}{}{no tentáculo esquerdo}
{1802}{}{no tentáculo direito}
{1803}{}{no corpo}
{1804}{}{no pé direito}
{1805}{}{no pé esquerdo}
{1806}{}{nos olhos?}
{1807}{}{na virilha}
{1808}{}{lugar indefinido}
{1850}{}{na cabeça}
{1851}{}{no braço esquerdo}
{1852}{}{no braço direito}
{1853}{}{no tronco}
{1854}{}{na perna direita}
{1855}{}{na perna esquerda}
{1856}{}{nos olhos}
{1857}{}{na virilha}
{1858}{}{lugar indefinido}
{1860}{}{na cabeça}
{1861}{}{no tentáculo esquerdo}
{1862}{}{no tentáculo direito}
{1863}{}{no corpo}
{1864}{}{no pé direito}
{1865}{}{no pé esquerdo}
{1866}{}{nos olhos?}
{1867}{}{na virilha}
{1868}{}{lugar indefinido}
{1900}{}{no CPU}
{1901}{}{no servidor de arma}
{1902}{}{no servidor de arma}
{1903}{}{na estrutura}
{1904}{}{na base do servidor}
{1905}{}{na base do servidor}
{1906}{}{nos sensores}
{1907}{}{no regulador}
{1908}{}{lugar indefinido}
{1970}{}{na cabeça}
{1971}{}{na pata dianteira esquerda}
{1972}{}{na pata dianteira direita}
{1973}{}{no abdômen}
{1974}{}{na pata traseira direita}
{1975}{}{na pata traseira esquerda}
{1976}{}{nas antenas}
{1977}{}{no metatórax}
{1978}{}{lugar indefinido}
{1990}{}{na cabeça}
{1991}{}{no braço esquerdo}
{1992}{}{no braço direito}
{1993}{}{no tronco}
{1994}{}{na perna direita}
{1995}{}{na perna esquerda}
{1996}{}{nos olhos}
{1997}{}{na virilha}
{1998}{}{lugar indefinido}
{2000}{}{na cabeça}
{2001}{}{no braço esquerdo}
{2002}{}{no braço direito}
{2003}{}{no tronco}
{2004}{}{na perna direita}
{2005}{}{na perna esquerda}
{2006}{}{nos olhos}
{2007}{}{na virilha}
{2008}{}{lugar indefinido}
{2010}{}{no CPU}
{2011}{}{no servidor de arma}
{2012}{}{no servidor de arma}
{2013}{}{na estrutura}
{2014}{}{na base do servidor}
{2015}{}{na base do servidor}
{2016}{}{nos sensores}
{2017}{}{no regulador}
{2018}{}{lugar indefinido}
{2030}{}{na cabeça}
{2031}{}{no ferrão}
{2032}{}{nas antenas}
{2033}{}{no tórax}
{2034}{}{nas patas dianteiras}
{2035}{}{nas patas traseiras}
{2036}{}{nos olhos}
{2037}{}{nas asas}
{2038}{}{lugar indefinido}
{5000}{}{. Essa doeu}
{5001}{}{. Um ferimento grave é inflingido}
{5002}{}{ sem a proteção da armadura}
{5003}{}{. Ele foi nocauteado pelo violento ataque}
{5004}{}{. Ele cai no chão, nocauteado pelo golpe}
{5005}{}{. O forte ataque na cabeça faz com que ele seja nocauteado}
{5006}{}{. O ataque destrói a têmpora. Boa noite, Bela Adormecida}
{5007}{}{. A morte é instantânea}
{5008}{}{, causando uma severa lesão no cotovelo}
{5009}{}{, tirando o braço da frente}
{5010}{}{, deixando um grande roxo}
{5011}{}{, danificando o braço esquerdo}
{5012}{}{, deixando o braço esquerdo pendurado pela pele}
{5013}{}{. Esse braço agora é só um cotoco sangrento}
{5014}{}{, danificando o braço direito}
{5015}{}{. Seu braço direito é pulverizado pelo poderoso ataque}
{5016}{}{ em um potente ataque}
{5017}{}{, atravessando a armadura}
{5018}{}{, infligindo um dano extra}
{5019}{}{ sem armadura, nocauteando o combatente}
{5020}{}{, expulsando o ar de seus pulmões. Ele cai no chão, fora da luta}
{5021}{}{. Infelizmente, agora é possível ver claramente sua coluna através do buraco em seu tronco}
{5022}{}{, ferindo gravemente sua perna}
{5023}{}{, nocauteando-o como pinos num jogo de boliche depois de um belo strike}
{5024}{}{, atropelando-o, danificando a perna}
{5025}{}{, quebrando feio seu joelho. Ele cai}
{5026}{}{. A intensa dor de perder a perna faz ele desistir}
{5027}{}{, inflingindo dor extra}
{5028}{}{. Infelizmente, ele perde a visão}
{5029}{}{. Sem nenhuma proteção, o golpe causa uma dor severa}
{5030}{}{, cegando-o com um golpe atordoador.}
{5031}{}{. a perda de um olho é muito pra ele, e ele desmaia, caindo no chão}
{5032}{}{. Infelizmente, ele está preocupado de mais sentindo a falta de ar no cérebro pra perceber a morte chegando}
{5033}{}{Ai! Essa doeu}
{5034}{}{, e ele não está usando um protetor de saco.}
{5035}{}{. Sem proteção, ele cai no chão gemendo em agonia}
{5036}{}{. A dor é tanta que ele desmaia, caindo no chão feito um saco de merda}
{5037}{}{. Ele susurra "Mamãe", enquanto seus olhos giram para trás de sua cabeça}
{5100}{}{. Essa doeu}
{5101}{}{. Um ferimento sério é inflingido}
{5102}{}{ sem a proteção da armadura}
{5103}{}{. Ela foi nocauteada pelo violento ataque}
{5104}{}{. Ela cai no chão, nocauteada pelo golpe}
{5105}{}{. O forte golpe na cabeça faz com que ela seja nocauteada.}
{5106}{}{. O ataque destrói sua têmpora. Boa noite, Bela Adormecida.}
{5107}{}{. A morte é instantânea}
{5108}{}{, causando uma severa lesão no cotovelo}
{5109}{}{, tirando o braço da frente}
{5110}{}{, deixando um grande roxo}
{5111}{}{, danificando o braço esquerdo}
{5112}{}{. O braço esquerdo agora está pendurado apenas por um fio de carne}
{5113}{}{. Esse braço agora é só um cotoco sangrento}
{5114}{}{, danificando o braço direito}
{5115}{}{. O braço direito dela virou carne moida com o golpe}
{5116}{}{ em um potente ataque}
{5117}{}{, atravessando suas defesas}
{5118}{}{, infligindo um dano extra}
{5119}{}{ sem armadura, derrubando a combatente nocauteada no chão}
{5120}{}{, expulsando o ar de seus pulmões. Ela cai no chão, inconsciente}
{5121}{}{. Infelizmente, a maioria dos órgãos vitais dela estão agora de fora}
{5122}{}{, ferindo gravemente sua perna}
{5123}{}{, fazendo ela desmaiar como se tivesse visto a maior barata do mundo}
{5124}{}{, derrubando-a e danificando sériamente esta perna}
{5125}{}{, quebrando feio seu joelho. Ela vai direto pro chão}
{5126}{}{. Ela grita de dor por causa da perna quebrada}
{5127}{}{, inflingindo dor extra}
{5128}{}{, causando cegueira. Ela contorce o rosto}
{5129}{}{. Sem nenhuma proteção, o golpe causa uma dor severa}
{5130}{}{. O ferimento causa uma cegueira severa (como se existisse algum outro tipo)}
{5131}{}{. Ela desmaia após perder a visão com o ataque}
{5132}{}{. Ela não tem tempo nem de pedir perdão à Deus antes de ir conhecê-lo pessoalmente}
{5133}{}{. Ela aguenta que nem macho. Ou seja, doeu muito}
{5134}{}{, derrubando-a no chão, nocauteada}
{5135}{}{. As chances dela ter filhos diminuem sériamente enquanto ela cai no chão feito uma boneca de pano}
{5200}{}{. A criancinha começa a chorar}
{5201}{}{. Inconsciente, a criança cai no chão}
{5202}{}{. Ai!}
{5203}{}{. O ataque é forte, e a criança é nocauteada}
{5204}{}{, esmagando a criança, que parece um boneco de pano quando é atingida}
{5205}{}{. O braço esquerdo da criança agora está com um dodói}
{5206}{}{, fazendo a criança perder o equilíbrio}
{5207}{}{, quebrando o braço com um alto estalo. A criança começa a chorar muito}
{5208}{}{, quebrando o braço facilmente, como se fosse um palitinho}
{5209}{}{. O braço direito começa a inchar, como um balão}
{5210}{}{, e ela começa a chorar}
{5211}{}{ num lugar sensível}
{5212}{}{. O ataque atinge um órgão vital, derrubando a criança no chão}
{5213}{}{, derrubando a criança como se fosse um brinquedo}
{5214}{}{. Agora essa criancinha não vai mais poder desfrutar a vida}
{5215}{}{, inflingindo um corte profundo}
{5216}{}{. O ataque faz com que a criança caia no chão, quebrando a perna}
{5217}{}{, ferindo sériamente a criancinha}
{5218}{}{. A criancinha olha pra cima e começa a chorar}
{5219}{}{, cegando a criança}
{5220}{}{, esmagando o jovem nariz da criança}
{5221}{}{. Um corte aparece em cima dos olhos e o sangue começa a fluir livremente}
{5222}{}{, o que faz com que seu olho fique parecendo uma uva explodida. A criança está desnorteada}
{5223}{}{, causando cegueira. A criança cai no chão}
{5224}{}{, o golpe continua até atingir o pequeno cérebro}
{5225}{}{. A criança parece confusa e assustada}
{5226}{}{, nocauteando a criancinha, que cai no chão}
{5300}{}{, ferindo o incrível mutante}
{5301}{}{, acertando um órgão vital}
{5302}{}{, acertando um órgão vital e nocauteando o gigante}
{5303}{}{. O gigantesco mutante olha pros lados por um segundo, e depois cai no chão}
{5304}{}{. A cabeça explode feito uma melancia gigante e sangrenta}
{5305}{}{, ferindo gravemente o terrível mutante}
{5306}{}{. O gigante para por um segundo, amaldiçoando o universo}
{5307}{}{, atingindo um nervo. O gigante é obrigado a segurar seu braço por causa da dor}
{5308}{}{. O ataque quebra o cutuvelo e provavelmente não foi uma sensação agradável}
{5309}{}{, quebrando o gigantesco braço, o que faz com que o sangue mutante comece a jorrar no chão}
{5310}{}{, fazendo o gigante perder o equilíbrio por um momento, e então cair no chão feito uma árvore recém cortada}
{5311}{}{, e galões de tripas começam a cair no chão}
{5312}{}{, fazendo o gigante cair voando no chão}
{5313}{}{. O mutante treme e cai, sem conseguir suportar seu peso com a perna}
{5314}{}{, acertando um lugar vital. O mutante cai com a perna quebrada}
{5315}{}{. A dor de uma perna quebrada domina o terrível gigante}
{5316}{}{, quase cegando o mutante}
{5317}{}{, cegando o agora furioso mutante}
{5318}{}{, quase cegando o mutante, que perde o equilíbrio}
{5319}{}{. O mutante cego tropeça para trás, despreparado para o próximo ataque}
{5320}{}{, cegando o agora inconsciente mutante}
{5321}{}{. Os olhos do mutante brilham por um momento, e depois as luzes se apagam - pra sempre}
{5400}{}{. O ghoul é surpreendido, e não consegue defender o ataque}
{5401}{}{. O ataque enterra este ghoul}
{5402}{}{. A mão do ghoul desnorteado se escancaram}
{5403}{}{, atravessando sua armadura e atingindo um ponto crítico}
{5404}{}{, atravessando a armadura e destruindo seu braço}
{5405}{}{. O ghoul vai pro lugar errado, na hora errada, e perde um olho}
{5406}{}{. O ghoul não está usando nenhuma armadura ai}
{5407}{}{, e sem proteção, o ghoul fica cego}
{5408}{}{, causando um olhar desnorteado no ghoul em seus últimos momentos}
{5500}{}{, derrubando a grande besta no chão}
{5501}{}{, atordoando os dois cérebros e derrubando o gigante animal}
{5502}{}{. A vaca mutante faz um alto som, claramente assustada}
{5503}{}{, quebrando uma das patas do Brahmin}
{5504}{}{, ferindo gravemente a vaca mutante}
{5505}{}{, penetrando facilmente na grossa carne do animal}
{5506}{}{, atravessando diretamente os dois corações da vaca mutante}
{5507}{}{, cegando todos os olhos com um único ataque}
{5508}{}{, cegando as duas cabeças e atordoando a vaca mutante}
{5509}{}{, cegando completamente o Brahmin, que cai nocauteado em seguida}
{5510}{}{. O gigantesco mutante bovino perde o equilíbrio por um momento}
{5511}{}{. O Brahmin balança com ódio}
{5512}{}{. O Brahmin perde o ar com a dor}
{5513}{}{. O Brahmin fica bem chateado com esse ataque super devastador}
{5600}{}{, fazendo o Radscorpion voar longe}
{5601}{}{, separando o cabeça da carapaça}
{5602}{}{, danificando sériamente a cauda}
{5603}{}{, ferindo sériamente suas garras}
{5604}{}{. O ataque passa entre a grossa carapaça do Radscorpion}
{5605}{}{, atravessando a carapaça sem perder velocidade}
{5606}{}{, perfurando a armadura natural e nocauteando o Radscorpion}
{5607}{}{. O Radscorpion não consegue lidar com uma sensação nova, tipo a de perder órgãos internos}
{5608}{}{, fazendo o escorpião voar longe e quebrando algumas de suas pernas}
{5609}{}{. O ataque abre um rasgo em uma parte desprotegida da perna, mutilando-a}
{5610}{}{, ferindo gravemente e cegando a criatura mutante}
{5611}{}{, penetrando quase até o cérebro. Isso que eu chamo de esmagar insetos}
{5612}{}{, quase chegando até o cérebro, cegando a criatura ao invés disso}
{5613}{}{. O ataque é forte, e sofisticado de mais para que }
{5614}{}{. Se fosse um humano, você poderia ter certeza de que ele estaria muito puto}
{5615}{}{, fazendo a pobre criatura cair no chão, sem os sentidos}
{5616}{}{, deixando pedaços de seu cérebro no chão}
{5700}{}{. A cabeça do roedor faz sons nada saudáveis}
{5701}{}{, esmagando a cabeça do roedor como se fosse uma bola de papel molhada}
{5702}{}{, e a pata da esquerda agora está meio achatada}
{5703}{}{. A pata da esquerda do rato está completamente destruida}
{5704}{}{. A pata direita está gravemente ferida}
{5705}{}{, explodindo a pata direita}
{5706}{}{. O rato é severamente ferido com este ataque}
{5707}{}{, ferindo gravemente o rato, que é nocauteado}
{5708}{}{, espalhando o rato pelo chão}
{5709}{}{, quebrando a perna direita}
{5710}{}{, fazendo um enorme buraco na perna esquerda}
{5711}{}{, fazendo um dano extra devido a sensibilidade da área atingida}
{5712}{}{. Sua alma foi arrebatada para conhecer o maravilhoso (porém pequeno) deus rato}
{5800}{}{. O floater cai no chão}
{5801}{}{. O floater cai no chão, aparentemente morto}
{5802}{}{, deixando sérias sequelas que vão prejudicar bastante a vida da criatura}
{5803}{}{, atordoando a terrível criatura}
{5804}{}{, atigindo uma área sensível e atordoando o floater}
{5805}{}{. O golpe faz com que a criatura trema violentamente, numa névoa de sangue}
{5806}{}{. O ataque causa algum tipo de reação violenta na criatura}
{5807}{}{. O floater de repente explode em chamas}
{5808}{}{. A criatura sacode selvagemente e treme como um pudim surpreso}
{5809}{}{, atingindo uma área sensível}
{5810}{}{. A criatura está obviamente agitada}
{5900}{}{. O centauro cai e fica atordoado}
{5901}{}{ e o golpe atinge um ponto crítico}
{5902}{}{, causando uma grande falha neurológica}
{5903}{}{, atordoando-o com seu ataque violento}
{5904}{}{, ferindo gravemente o braço}
{5905}{}{, atingindo um ponto crítico. O braço está incapacitado}
{5906}{}{, derrubando a criatura e ferindo gravemente a perna}
{5907}{}{, deixando o centauro atordoado enquanto cai com uma perna incapacitada}
{5908}{}{, cegando a cabeça}
{5909}{}{, surpreendendo o centauro. Ele tropeça cegamente por um momento}
{5910}{}{, surpreendendo o centauro. Ele cai como um monte de merda}
{5911}{}{, surpreendendo o centauro. Ele cai em uma pilha de gosma}
{5912}{}{. O ataque não foi tão eficaz como poderia ter sido}
{6000}{}{, causando alguns danos estruturais}
{6001}{}{. Faíscas voam e o robô fica momentaneamente fora de controle}
{6002}{}{, atingindo um componente crítico que deixa o robô fora de controle}
{6003}{}{, atingindo um componente crítico que causa um gigantesco mau funcionamento}
{6004}{}{. O robô tenta se manter em pé}
{6005}{}{. As robô luta para não cair}
{6006}{}{, atingindo uma parte crítica que causa danos pesados}
{6007}{}{, causando um gigantesco dano estrutural}
{6008}{}{, atingindo um componente crítico e causando graves danos}
{6009}{}{. O robo treme diante desde intenso ataque}
{6010}{}{, desmontando o robô}
{6011}{}{. O robô tenta compensar, mas não consegue, caindo no chão}
{6012}{}{. O robô cede sobre a pressão, caindo no chão}
{6013}{}{, Quebrando as lentes do sensor}
{6100}{}{, derrubando o cão no chão}
{6101}{}{, bem no meio do focinho}
{6102}{}{. O cão cai no chão, mas ainda está respirando}
{6103}{}{. O animal tosse uma nuvem de sangue}
{6104}{}{, quebrando a perna}
{6105}{}{, quebrando a perna. O animal tenta se manter em pé, mas não consegue}
{6106}{}{. O animal cego uiva com a dor}
{6107}{}{, neutralizando o pobre animal}
{6200}{}{, Derrubando esse inseto mutante}
{6201}{}{. ele cai no chão}
{6202}{}{. O manti se pergunta se deve ou não continuar vivendo}
{6203}{}{, quebrando o membro}
{6204}{}{, fazendo o Manti lamber suas feridas. Ele segura seu membro de forma... curiosa}
{6205}{}{, ignorando a armadura de sua resistente carapaça}
{6206}{}{. O Manti grita e se contorce de uma maneira nada humana}
{6207}{}{, o que faz com que o Manti caia. Um membro fica curvado em um ângulo estranho. Isso deve doer}
{6208}{}{, rasgando as asas}
{6209}{}{, ignorando a armadura de carapaça e jogando o Manti pra longe}
{6210}{}{, cegando o inseto com um golpe preciso}
{6300}{}{. Até mesmo essa besta parece desorientada com este ataque brutal}
{6301}{}{, escorregando pelas enormes garras para atingir o monstro. O Deathclaw se chacoalha e grunhe}
{6302}{}{. O resultado é um enome estrago nos olhos do Deathclaw}
{6400}{}{, ignorando as defesas da planta}
{6401}{}{, arrancando algumas de suas folhas}
{6402}{}{, quebrando alguns de seus galhos}
{6403}{}{. Esse ataque violento tiraria todo o fôlego da planta, se ela tivesse pulmões}
{6404}{}{, espirrando pólem pra todos os lados}
{6405}{}{, quase a derrubando}
{6406}{}{, danificando alguns de seus galhos}
{6500}{}{. Você vai ter uma dor de cabeça forte amanhã, se sobreviver até lá}
{6501}{}{. Sua armadura não te protege desse ataque certeiro}
{6502}{}{. Você sente uma dor forte por um momento, e depois tudo fica preto..}
{6503}{}{, ignorando sua armadura. O golpe te derruba no chão}
{6504}{}{. O choque faz você enchergar tudo preto. Depois de uns segundos, você percebe que sua visão não voltou}
{6505}{}{. Você dá uma bela olhada no seu coorpo enquanto sua cabeça viaja pelo ar}
{6506}{}{. De forma surpreendete, o golpe não é tão pior que o normal}
{6507}{}{, te desorientando por um momento}
{6508}{}{. Sinta a dor}
{6509}{}{. O ataque deixa seu braço inutilizado}
{6510}{}{, atravessando sua armadura. O golpe quebra os ossos de seu braço como se fossem gravetos}
{6511}{}{, atravessando sua armadura. Seu braço agora está pendurado por um fio no seu ombro}
{6512}{}{. Vai ficar um roxo enorme, e talvez as cicatrizes sirvam de assunto nas próximas festas}
{6513}{}{, destruindo seus órgãos internos. Tudo que você pode fazer é gargarejar sangue}
{6514}{}{, te jogando de cabeça pra baixo. Você dá quase um mortal}
{6515}{}{, você sai voando com a perna quebrada}
{6516}{}{, passando por sua armadura como se fosse manteiga. O pancada te derruba no chão, e fere seriamente seu joelho}
{6517}{}{. A dor da sua perna quebrada faz você desmaiar}
{6518}{}{. A pancada faz você se contorcer um pouco, mas nada além disso}
{6519}{}{. Pro seu azar, você fica cego imediatamente}
{6520}{}{. Ai. Você perde um tempinho tentando limpar o sangue dos seus olhos}
{6521}{}{, atravessando sua armadura. Você fica sem direção até perceber que você perdeu a visão}
{6522}{}{. Você sente uma coisa estranha na cabeça. Você percebe que é morte cerebral iminente}
{6523}{}{, fazendo você gritar}
{6524}{}{. Você segura sua virilha e cai no chão, sentindo uma terrível dor}
{6525}{}{. A dor é tão grande que você desmaia. Eu não queria ser você agora}
{6526}{}{. Não existem palavras no universo pra descrever a dor que você está sentindo neste momento}
{6700}{}{, ultrapassando as defesas do lagarto}
{6701}{}{, arrancando um pedaço de sua pele gosmenta}
{6702}{}{, quebrando alguns de seus dedos}
{6703}{}{, prejudicando seriamente a habilidade do Gecko respirar}
{6704}{}{. Que pancada}
{6705}{}{, quase a derrubando}
{6706}{}{, danificando sériamente alguns de seus membros}
{6800}{}{, atravessando as defesas da criatura}
{6801}{}{, fazendo voar gosma pra todos os lados}
{6802}{}{, destruindo seus... o que é isto mesmo? Eca }
{6803}{}{, danificando sua habilidade de... respirar (?)}
{6804}{}{, fazendo voar uma coisa nojenta}
{6805}{}{, quase a derrubando}
{6806}{}{, danificando alguns de seus tentáculos}
{6900}{}{, ultrapassando as defesas da formiga}
{6901}{}{, arrancando uma de suas antenas fora}
{6902}{}{, quebrando algumas de suas pernas}
{6903}{}{, ferindo a formiga gravemente}
{6904}{}{, fazendo com que ela tropece um pouco}
{6905}{}{, quase a derrubando}
{6906}{}{, danificando uma parte de seu exoesqueleto}
{7000}{}{, ultrapassando as defesas da formiga}
{7001}{}{, arrancando uma de suas antenas fora}
{7002}{}{, quebrando algumas de suas pernas}
{7003}{}{, ferindo a formiga gravemente}
{7004}{}{, fazendo com que ela tropece um pouco}
{7005}{}{, quase a derrubando}
{7006}{}{, danificando uma parte de seu exoesqueleto}
{7100}{}{, ultrapassando a armadura}
{7101}{}{, fazendo ele cair de joelhos}
{7102}{}{, destruindo o mecanismo que controla seu braço}
{7103}{}{, destruindo o mecanismo que faz sua perna se movimentar}
{7104}{}{, estourando seu olho biônico}
{7105}{}{, fazendo ele parar por alguns segundos se recompondo de seu ataque destruidor}
{7106}{}{, compactando seu peitoral mecânico}
