{1000}{}{A minha cara! A minha cara!}
{1001}{}{Ai! Isso dói!}
{1002}{}{Ouch! Preciso de um pouco de gelo para a minha cabeça.}
{1003}{}{Você arrancou minha cabeça!Oh Deus, minha cabeça se foi!}
{1004}{}{Meu nariz! Arrancou meu nariz!}
{1005}{}{Ai, Meu couro cabeludo!}
{1006}{}{Eu não tenho rosto, oh Deus, não!}
{1007}{}{Onde esta minha orelha?}
{1008}{}{Por que está tudo girando?}
{1009}{}{Ninguém nunca vai ser capaz de olhar para mim de novo!}
{1010}{}{Ow, o meu braço!}
{1011}{}{Ow!}
{1012}{}{Você quebrou o meu braço!}
{1013}{}{Cristo, arrancou meu braço!}
{1014}{}{Oh Deus, meu braço não.}
{1015}{}{Para, por favor, para.}
{1016}{}{(soluços, soluços)}
{1017}{}{Meu braço esta totalmente quebrado.}
{1018}{}{Como vou ganhar a vida agora?}
{1019}{}{Você quebrou.}
{1020}{}{Ow, o meu braço!}
{1021}{}{Wahhhh!}
{1022}{}{Meu Deus! Meu braço!}
{1023}{}{Como posso sustentar a minha família agora?}
{1024}{}{Osso, assim tão branco.}
{1025}{}{Quanto sangue.}
{1026}{}{Cristo, faça com que a dor pare!}
{1027}{}{Não meus dedos, tudo menos isso. Nããão!}
{1028}{}{Arrancou meu braço. Oh Deus, não.}
{1029}{}{Não me mate.}
{1030}{}{Ai! Isso realmente dói!}
{1031}{}{Eu acho que vou desmaiar}
{1032}{}{Ouch!}
{1033}{}{Uuuuf!}
{1034}{}{Isso dói!}
{1035}{}{Me deixe em paz!}
{1036}{}{Ohhh, dor!}
{1037}{}{Eu estou morrendo!}
{1038}{}{Oh Cristo, isso dói muito...}
{1039}{}{Eu estou sangrando.}
{1040}{}{Tenho um pé na cova.}
{1041}{}{Oh Deus, porque tem que fazer isso?}
{1042}{}{Quem vai cuidar da minha familia?}
{1043}{}{Por que? Por que?}
{1044}{}{O que foi que eu fiz para você?}
{1045}{}{Eu nunca quis morrer assim.}
{1046}{}{Eu não queria fazer nada. Nao me mate.}
{1047}{}{Arrrgh, minha coluna!}
{1048}{}{Espera, onde está o meu baço?}
{1049}{}{Quanto sangue.}
{1050}{}{Eu estou começando a sentir frio e sono.}
{1051}{}{Por Cristo, não me mate por favor!}
{1052}{}{Não vou ficar no seu caminho, mas me deixe viver.}
{1053}{}{Quem vai cuidar da minha familia.}
{1054}{}{Não me machuque mais.}
{1055}{}{Você está me matando!}
{1056}{}{(Soluço, Soluço) Não posso respirar.}
{1057}{}{Acho que vou desmaiar, não posso continuar.}
{1058}{}{Me ajude, me ajuuuudem!}
{1059}{}{Oh Deus, Oh Deus, Oh Deus...}
{1060}{}{Ow, minha perna!}
{1061}{}{Meu joelho!}
{1062}{}{Ow!}
{1063}{}{Você arrancou minha perna.}
{1064}{}{Acabou com meu joelho!}
{1065}{}{Não posso andar.}
{1066}{}{Por que tem que doer tanto?}
{1067}{}{Meus dedos do pé.}
{1068}{}{Meu pé, onde esta meu pé?}
{1069}{}{Não posso sentir meu pé!}
{1070}{}{Ow, minha perna!}
{1071}{}{Meu joelho!}
{1072}{}{Aaaarrrrggghhh!}
{1073}{}{Nunca vou dançar novamente.}
{1074}{}{Nunca vou andar novamente.}
{1075}{}{Eu não posso sentir meus dedos.}
{1076}{}{É osso, é muito branco... a dor é tão grande...}
{1077}{}{Quanto sangue...por toda parte.}
{1078}{}{Fui partido.}
{1079}{}{Isso é péssimo, oh Deus, por que.}
{1080}{}{Ai! Meus olhos!}
{1081}{}{Minha cara! Meus olhos! Arrrrgh!}
{1082}{}{Meus olhos!}
{1083}{}{Oh Deus, estou cego!}
{1084}{}{Me arrancou um olho! Oh Deus, nãããooo.}
{1085}{}{Nos olhos não, tudo menos isso.}
{1086}{}{Me deixou cego, nãããããão.}
{1087}{}{Nos olhos não, por favor isso não.}
{1088}{}{Estou cego, me mate. (soluço, soluço)}
{1089}{}{Onde está o meu olho, se eu pudesse coloca-lo de volta no lugar...}
{1090}{}{Ooooooooo, minha virilha! Ooooooo ...}
{1091}{}{Oww ... Queima!}
{1092}{}{Urp!}
{1093}{}{Ooorp! aoooww...}
{1094}{}{Eu... não posso ... respirar ...}
{1095}{}{A dor, a dor ...}
{1096}{}{Queria ter uma familia.}
{1097}{}{Agora eu nunca vou ter mais filhos.}
{1098}{}{Por que aqui? Por quê?}
{1099}{}{Me queima, me queima.}
{1100}{}{Tenho que me sentar.}
{1101}{}{Não é justo.}
{1102}{}{Covarde, unh...}
{1103}{}{Porra!}
{1104}{}{Meu crânio dói!}
{1105}{}{A minha cara! A minha cara!}
{1106}{}{Vejo estrelas!}
{1107}{}{Quem apagou as luzes?}
{1108}{}{Quebrou meus dentes!}
{1109}{}{Ei, cortou meu cabelo.}
{1110}{}{Hah, pelo menos você não bateu em nada importante.}
{1111}{}{Poxa, a minha cabeça.}
{1112}{}{Eu me sinto um pouco tonto.}
{1113}{}{Aggghhh! Meu braço!}
{1114}{}{Meu braço!}
{1115}{}{Oh cara, isso dói!}
{1116}{}{Meu braço dói.}
{1117}{}{Meu braço quebrou.}
{1118}{}{Meu braço quebrou, aqui... e aqui...}
{1119}{}{O osso saiu pra fora do braço, arrrrgghhh.}
{1120}{}{Eu não posso sentir nada, meu braço esta totalmente dormente.}
{1121}{}{Alguém coloca meu braço no lugar, por favooooooor?!?}
{1122}{}{Arrancou meu polegar!}
{1123}{}{Aggghhh! Meu braço!}
{1124}{}{Meu braço!}
{1125}{}{Quase arrancou minhas mãos!}
{1126}{}{Arrrrgh! Me ajude encontrar meus dedos!}
{1127}{}{Agora nunca vou poder escrever novamente.}
{1128}{}{Quebrou meu braço!}
{1129}{}{Unh, você acabou com meu braço.}
{1130}{}{Meu cotovelo Não pensei que poderia sentir tanta dor.}
{1131}{}{No braço não, por quê meu braço?}
{1132}{}{Esta doendo muito.}
{1133}{}{Minhas pernas, eu não consigo sentir minhas pernas.}
{1134}{}{Oof!}
{1135}{}{Ouch!}
{1136}{}{Ufa! Minha costela dói}
{1137}{}{Ugh! Isso dói!}
{1138}{}{Maldição! Eu cuspo em você!}
{1139}{}{Argh!}
{1140}{}{Oh, minhas costelas!}
{1141}{}{Ai!!!}
{1142}{}{Oof!}
{1143}{}{Se não doer muito é um ruim?}
{1144}{}{Sindo seu peso pesado no peito, suspiro, suspiro, tenho sede.}
{1145}{}{*Cusp* Por quê não posso respirar direito?}
{1146}{}{Dói muito.}
{1147}{}{Acho que quebrou alguma coisa por dentro, dói muito.}
{1148}{}{Ack! Quebrou alguma coisa dentro do meu peito.}
{1149}{}{Por quê tem que doer tanto?}
{1150}{}{Oh Cristo, um golpe critico na barriga!}
{1151}{}{Eu continuo sangrando, e não vai (Soluço, Soluço) parar.}
{1152}{}{I Não posso respirar and I keep coughin' up blood, that's bad ain't it?}
{1153}{}{Tenho um buraco no meio do corpo.}
{1154}{}{Posso ver minhas tripas, uh oh.}
{1155}{}{Minhas tripas estão saindo pra fora, isso não é bom.}
{1156}{}{Meus pulmões estão assobiando (Soluço, Soluço, suspiro).}
{1157}{}{Estou me sentindo meio quente e sonolento agora.}
{1158}{}{Eu acho que eu só quero deitar um pouco.}
{1159}{}{Tudo esta ficando tão escuro agora.}
{1160}{}{Aggghhh! Minha perna!}
{1161}{}{Minha perna!}
{1162}{}{Lá se vai o meu joelho!}
{1163}{}{Minha carrera no mundo do balé acabou.}
{1164}{}{Meu joelho ja era.}
{1165}{}{Onde está a parte de baixo da minha perna? Onde ele está?!?}
{1166}{}{Dói para se mover.}
{1167}{}{Fui atingido. Não posso sentir minha perna.}
{1168}{}{Que dor, alguém faça parar!}
{1169}{}{Que dor, Que dor, Que dor!}
{1170}{}{Aggghhh! Minha perna!}
{1171}{}{Minha perna!}
{1172}{}{Lá se vai o meu joelho!}
{1173}{}{Não sindo minhas pernas.}
{1174}{}{Acho melhor encontrar com um papagaio e um tapa-olho.}
{1175}{}{Agora você pode me chamar compacto.}
{1176}{}{Agora nunca vou ser capaz de sustentar a minha família.}
{1177}{}{Quem me vai contratar agora?}
{1178}{}{Eu não sou bom a ninguém como um aleijado. (soluço, soluço).}
{1179}{}{A minha perna, eu não posso senti-la.}
{1180}{}{Aggghhh! Estou cego!}
{1181}{}{Meus olhos! Meus olhos!}
{1182}{}{O meu olho! Você vai pagar por isso!}
{1183}{}{Você arrancouu meu olho fora.}
{1184}{}{Quem apagou as luzes?}
{1185}{}{Meus olho! Aiiieeeee!}
{1186}{}{Eu com certeza gostaria de poder ver apenas mais um pôr do sol.}
{1187}{}{Meu olho, eu não consigo ver nada!}
{1188}{}{De repente tudo ficou tão escuro e solitário.}
{1189}{}{Daria tudo para ver novamente.}
{1190}{}{Oooooo, minha virilha!}
{1191}{}{Oooooooooo!}
{1192}{}{Eu... não posso ... respirar ...}
{1193}{}{Erg! Direto nas jóias!}
{1194}{}{A dor, a dor ...}
{1195}{}{Maldição, isso dói!}
{1196}{}{Eu não vou ter mais filhos.}
{1197}{}{*unh* Um golpe baixo.}
{1198}{}{Eeeeeep!}
{1199}{}{Oh sim, isso dói.}
{1200}{}{Ai! Seu filho da ...}
{1201}{}{Você quebrou meu nariz!}
{1202}{}{Eu vou arrancar sua cabeça!}
{1203}{}{Você atingiu minha a porra da minha cabeça!}
{1204}{}{Terá que acertar mais forte que isso, mas não muito.}
{1205}{}{Ouch, vai pagar por isso.}
{1206}{}{Oh, olhe para todos os passarinhos.}
{1207}{}{Isso dói.}
{1208}{}{Você fudeu com a minha linda cara.}
{1209}{}{Isso vai deixar uma cicatriz.}
{1210}{}{Ow, meu braço.}
{1211}{}{Você acabou de fazer o maior erro de sua vida.}
{1212}{}{Meu braço!}
{1213}{}{Hah, eu sou destro.}
{1214}{}{Só preciso de um braço para te matar.}
{1215}{}{Eu não preciso dos dedos.}
{1216}{}{Eu só preciso de um dedo para acabar com você .}
{1217}{}{Maldição, isso vai acabar com meu swing.}
{1218}{}{Eu ainda posso acabar com sua existencia.}
{1219}{}{Maldição, partiu meu braço em dois.}
{1220}{}{Ow, meu braço.}
{1221}{}{Você acabou de fazer o maior erro de sua vida.}
{1222}{}{Meu braço!}
{1223}{}{Posso cuidar de você somente com a esquerda.}
{1224}{}{Hah, eu sou um canhoto de qualquer maneira.}
{1225}{}{Tentando me desarmar né?}
{1226}{}{Isso não vai me impedir.}
{1227}{}{Eu ainda tenho outra mão para usar contra você.}
{1228}{}{Maldição, Isso dói.}
{1229}{}{Mmm, isso vai deixar uma marca.}
{1230}{}{Urp!}
{1231}{}{Oof!}
{1232}{}{Ouch!}
{1233}{}{Yup, isso me arrancou algumas costelas.}
{1234}{}{Ugh! Isso dói!}
{1235}{}{Ouch!}
{1236}{}{Argh!}
{1237}{}{Oh, eu acho que você me quebrou uma costela!}
{1238}{}{Ai! Meu estômago!}
{1239}{}{Sim, nós apenas começamos.}
{1240}{}{Agora você me deixou nervoso.}
{1241}{}{Eu não gostei disso.}
{1242}{}{Porra, você acabou com a porra dos meus pulmões.}
{1243}{}{Apenas um verme como você tenta me golpear no estômago}
{1244}{}{Vou substituir esses orgãos que me arrancou pelos seus.}
{1245}{}{Caramba, você é melhor do que parece.}
{1246}{}{Isso não é bom. Vou ter que te ensinar boas maneiras.}
{1247}{}{Um tiro de sorte.}
{1248}{}{Espero que você ache engraçado quando eu fizer isso com você.}
{1249}{}{Eu devo estar ficando velho. Isso me machucou realmente.}
{1250}{}{Você vai ter que fazer melhor.}
{1251}{}{Tudo está funcionando bem o suficiente para dar um jeito em você}
{1252}{}{Eu sinto falta de um pulmão, eu acho.}
{1253}{}{Tenho certeza de que tem um monte de sangue aqui dentro, bem, pelo menos eu costumava ter.}
{1254}{}{Droga, isso dói!}
{1255}{}{Filho da puta! Bastardo!}
{1256}{}{Ninguém faz isso e vive para contar a história.}
{1257}{}{Assim que eu recuperar o fôlego (tosse, tosse), eu vou te pegar.}
{1258}{}{Você quebrou alguma coisa aqui dentro.}
{1259}{}{Você não sabe o que acabou de fazer.}
{1260}{}{Ow, minha perna.}
{1261}{}{Eu não preciso ficar de pé para te matar!}
{1262}{}{Meu joelho!}
{1263}{}{Meu tendão de Aquiles!}
{1264}{}{Aaiiiieeee!!}
{1265}{}{Lá se vai minha foxtrot.}
{1266}{}{Eu sim vou te ensinar a arrancar os dedos.}
{1267}{}{Quebre a perna? E vou acabar com você!}
{1268}{}{Onde está um torniquete quando você precisa de um.}
{1269}{}{Merda, minha perna dói.}
{1270}{}{Ow, minha perna.}
{1271}{}{Eu não preciso ficar de pé para te matar!}
{1272}{}{Meu joelho!}
{1273}{}{Isso vai me deixar uma marca por um bom tempo.}
{1274}{}{Vem cá, não me faça correr atrás de você.}
{1275}{}{Maldição quase arrancou minhas pernas.}
{1276}{}{Isso vai me atrasar.}
{1277}{}{Oh, isso sim que vou enviar para o banco.}
{1278}{}{Eu tenho outra perna.}
{1279}{}{Hah-hah, essa era a minha perna de prótese.}
{1280}{}{Eu não posso ver!}
{1281}{}{Esta luta está ficando pior a cada segundo.}
{1282}{}{Isso foi um verdadeiro golpe baixo!}
{1283}{}{Me deixou cego, porra!}
{1284}{}{Seu idiota, você me cegou!}
{1285}{}{Só por isso, eu vou estourar seus olhos como uvas maduras.}
{1286}{}{Você arrancou a porra do meu olho!}
{1287}{}{Merda, meu olho esta pendurado pelo nervo óptico.}
{1288}{}{Eu ainda posso ouvir onde você está.}
{1289}{}{Você nunca vai tocar meus malditos olhos de novo!}
{1290}{}{Oooooo, minha virilha!}
{1291}{}{Eu vou sentir isso pela manhã.}
{1292}{}{Covarde do caralho!}
{1293}{}{Urp!}
{1294}{}{Isso não vai te ajudar em nada.}
{1295}{}{Eu achei que você ia tentar fazer isso.}
{1296}{}{Esta divertido?}
{1297}{}{Eu vou arrancar o seu e saco e fazer você comer.}
{1298}{}{Eu acho que eu preciso sentar por um tempo.}
{1299}{}{Tem que se esforçar mais do que isso.}
{1300}{}{Isso vai ser uma cicatriz legal!}
{1301}{}{Estou começando a ficar irritado.}
{1302}{}{Faça isso de novo, porco.}
{1303}{}{Isso só me deixa louco.}
{1304}{}{Aquele som de toque que eu ouço é o som da sua sentença de morte.}
{1305}{}{Mais uma cicatriz não vai me fazer mais feio.}
{1306}{}{Eu nem sentir isso.}
{1307}{}{Pelo menos você só bateu minha cabeça.}
{1308}{}{Ouch, isso dói.}
{1309}{}{Eu ainda tenho *alguns dentes*.}
{1310}{}{Eu voltei!}
{1311}{}{Posso acabar com você com apenas uma mão.}
{1312}{}{Você quebrou meu braço, mas eu vou quebrar seu pescoço!}
{1313}{}{Você não pode me parar assim tão fácil.}
{1314}{}{Esse foi apenas o meu braço esquerdo.}
{1315}{}{Eu ainda posso cuidar de pequenos problemas como você.}
{1316}{}{Maldição, meu braço esquerdo.}
{1317}{}{Meu cotovelo!}
{1318}{}{Merda, la se vai mais um par de dedos.}
{1319}{}{Me arrancou um dedo, vou te arrancar uma maldita mão.}
{1320}{}{Posso acabar contigo somente com a mão esquerda.}
{1321}{}{Foi apenas um arranhão ...}
{1322}{}{Você quebrou meu braço, então eu vou quebrar seu pescoço,}
{1323}{}{So preciso de um braço para acabar contigo.}
{1324}{}{Perdi outro dedo. Isso dói.}
{1325}{}{De qualquer forma, esse braço nao usava pra nada.}
{1326}{}{Isso é mais do que um arranhão.}
{1327}{}{Meu Deus isso dói.}
{1328}{}{Isso vai precisar de pontos.}
{1329}{}{Eu vou arrancar o seu fígado por isso.}
{1330}{}{Um pouco de sangue não machuca ninguém.}
{1331}{}{Uff! Vou torcer seu pescoço por isso ...}
{1332}{}{Ow!}
{1333}{}{Eu gosto da dor!}
{1334}{}{Eu gosto do som de costelas quebrando!}
{1335}{}{Isso não é nada!}
{1336}{}{Arg!}
{1337}{}{Sim, dá-me mais.}
{1338}{}{Isso é o melhor que você pode fazer?}
{1339}{}{Você bate como uma franguinha.}
{1340}{}{E eu que pensava que isso seria uma luta séria.}
{1341}{}{Isso vai atrasar por horas.}
{1342}{}{Ouch, ja estou com poucas costelas.}
{1343}{}{Uma ferida na barriga não vai me atrasar.}
{1344}{}{Isso chamou meu interesse.}
{1345}{}{Pode ter certeza que vai doer mais em você do que em mim.}
{1346}{}{Seu estúpido filho da puta. Agora eu vou te matar lentamente.}
{1347}{}{Isso doeu um pouco.}
{1348}{}{O sangue só me deixa com raiva.}
{1349}{}{Apenas um arranhão, eu já estive pior.}
{1350}{}{Isso não me fez nada.}
{1351}{}{Obrigado, minhas costas se sente muito melhor agora.}
{1352}{}{Espero que tenha sido o seu melhor tiro, você não vai ter outra chance.}
{1353}{}{Ok, agora é minha vez.}
{1354}{}{Maldição, isso queima um pouco.}
{1355}{}{Ei, isso arde um pouco.}
{1356}{}{Maldição, isso queima um pouco.}
{1357}{}{Vou ter tempo para curar isso quando estiver morto.}
{1358}{}{Já tive piores.}
{1359}{}{Vamos ver como você gosta disso.}
{1360}{}{Eu adoro o som de ossos se quebrando.}
{1361}{}{Vou te pegar nem que eu tenha que rastejar atrás de você.}
{1362}{}{Você quebrou a minha perna, mas eu vou quebrar seu pescoço!}
{1363}{}{Merda! Não sindo minhas pernas.}
{1364}{}{Um zé ruéla não vai me parar.}
{1365}{}{Você acabou com minha perna, desgraçado!}
{1366}{}{Poderia ter sido pior.}
{1367}{}{Vamos falar de vingança agora.}
{1368}{}{De qualquer forma essa perna não funcionava muito bem.}
{1369}{}{Eu é que vou queimar seus pés.}
{1370}{}{Eu adoro o som de ossos se quebrando.}
{1371}{}{Eu ainda tenho uma perna esquerda.}
{1372}{}{Você quebrou a minha perna, mas eu vou quebrar seu pescoço!}
{1373}{}{De qualquer maneira eu nunca fui bom de dança.}
{1374}{}{Bem, acho que eu nunca vou ser um Rockette.}
{1375}{}{Isso vai te custar * ambas * as pernas.}
{1376}{}{Posso aguentar coisas piores.}
{1377}{}{Eu vou arrancar sua perna fora com meus dentes.}
{1378}{}{Maldição, arrancou meus dedos do pé.}
{1379}{}{Agora você pode me chamar compacto.}
{1380}{}{Ei, estou cego.}
{1381}{}{Eu não posso ver. Agora a luta vai ficar de igual pra igual.}
{1382}{}{Meus olhos, cadela!}
{1383}{}{Eu ainda posso ouvi-lo.}
{1384}{}{Vai se fuder seu viado.}
{1385}{}{Eu não posso vê-lo, mas eu ainda pode matá-lo.}
{1386}{}{Você vai pagar por isso.}
{1387}{}{Você fudeu com meus olhos!}
{1388}{}{Pora! Quem apagou as luzes?}
{1389}{}{Meus malditos olhos estão pegando fogo!}
{1390}{}{Uff, minha virilha!}
{1391}{}{Esse foi um movimento corajoso.}
{1392}{}{Heh, heh, não pode me ferir com isso, sou banhado em ouro.}
{1393}{}{Você é um pedaço de merda.}
{1394}{}{Então é assim que você quer jogar?}
{1395}{}{Ack!}
{1396}{}{Seu cretino, vou te castrar.}
{1397}{}{Porra, isso dói.}
{1398}{}{Essa coisa queima.}
{1399}{}{É melhor você correr.}
{1400}{}{Atenção, registrado mal funcionamento CPU!}
{1401}{}{Aviso! Danos na CPU! Processamento prejudicado!}
{1402}{}{Aviso! CPU danificada! Desviando sistema crítico!}
{1410}{}{Danos registrados no manipulador.}
{1411}{}{Unidade atingida no manipulador esquerdo. Avaliando danos.}
{1412}{}{Impacto registrado no manipulador. Tentando compensação.}
{1420}{}{Danos registrados no manipulador.}
{1421}{}{Unidade atingida no manipulador direito. Avaliando danos.}
{1422}{}{Impacto registrado no manipulador. Tentando compensação.}
{1430}{}{Impacto na carcaça. Correção de danos.}
{1431}{}{Impacto na carcaça. Correções internas inicializadas.}
{1432}{}{Estrutura principal sob ataque.}
{1433}{}{Armadura penetrada.}
{1434}{}{Estrutura principal sob ataque. Corrigindo.}
{1435}{}{Unidade sob ataque.}
{1436}{}{Tentando manobras de ataque.}
{1437}{}{Brzzt!}
{1438}{}{Danos menores.}
{1439}{}{Brzzt!}
{1460}{}{Danos registrados em unidade matriz.}
{1461}{}{Unidade atingida na matriz direita. Avaliando danos.}
{1462}{}{Impacto registrado na unidade matriz. Tentando compensação.}
{1470}{}{Danos registrados em unidade matriz.}
{1471}{}{Unidade atingida na matriz esquerda. Avaliando danos.}
{1472}{}{Impacto registrado na unidade matriz. Tentando compensação.}
{1480}{}{Sensor atingido! Sensor atingido!}
{1481}{}{Sensores prejudicados! Sensores prejudicados!}
{1482}{}{Mau funcionamento do sistema de sensor, tentando desviar.}
{1490}{}{Mau funcionamento registrado no regulador!}
{1491}{}{Regulador danificado! Regulador danificado!}
{1492}{}{Regulador danificado! Desviando para o sistema crítico!}
{1500}{}{Minha cabeça está cheia de maus espíritos.}
{1501}{}{Posso escutar meus antepassados me chamando.}
{1502}{}{Isso vai me deixar uma bela cicatriz.}
{1503}{}{Ouuuuch!}
{1504}{}{Minha cabeça esta em chamas!}
{1505}{}{Queima, queima!}
{1506}{}{Que dor.}
{1507}{}{Sua magia é poderosa.}
{1508}{}{Você não pode roubar minha alma dessa maneira.}
{1509}{}{Sua magia não pode me matar.}
{1510}{}{Vou usar o meu braço direito para matá-lo.}
{1511}{}{Eu só preciso de uma mão para te matar.}
{1512}{}{Sua dor vai ser ainda maior!}
{1513}{}{Eu não preciso que muitos dedos.}
{1514}{}{De qualquer maneira esse braço era um pouco grande demais.}
{1515}{}{Vou arrancar seus dois braços por isso.}
{1516}{}{Por isso, vou te matar lentamente.}
{1517}{}{Ouch!}
{1518}{}{Quanto sangue.}
{1519}{}{Algo para mostrar para as crianças.}
{1520}{}{Eu vou matá-lo com minha mão esquerda.}
{1521}{}{Sua mira é tão ruim assim?}
{1522}{}{Eu só preciso de uma mão para te matar.}
{1523}{}{Eu não preciso que muitos dedos.}
{1524}{}{Por isso, vou te matar lentamente.}
{1525}{}{Vou arrancar seus dois braços por isso.}
{1526}{}{Você arrancou meu braço, eu vou levar a sua cabeça!}
{1527}{}{Esta tentando me matar?}
{1528}{}{Vou cortar suas entranhas por isso.}
{1529}{}{Vou fazer com que morra lentamente.}
{1530}{}{Awwwwwg!}
{1531}{}{Minhas entranhas queimar!}
{1532}{}{Minhas entranhas estão pegando fogo!}
{1533}{}{Meus espíritos de vida se separam de mim.}
{1534}{}{Fui rasgado!}
{1535}{}{Posso viver o suficiente para acabar com você}
{1536}{}{Antepassados??, estou chegando.}
{1537}{}{Eu nunca vou ver a aldeia novamente.}
{1538}{}{Pelo menos eu vou morrer com honra.}
{1539}{}{Meus irmãos vão me vingar.}
{1540}{}{Eu não tenho mais fôlego.}
{1541}{}{Você tomou minha alma.}
{1542}{}{Você me mataria?}
{1543}{}{Estou eviscerado como um brahmin.}
{1544}{}{Eu não me sinto bem.}
{1545}{}{Eu não posso sentir minhas pernas.}
{1546}{}{De repente, eu me sinto quente e sonolento.}
{1547}{}{Errrggggg!}
{1548}{}{Gack! cough, cough.}
{1549}{}{Devo continuar, devo matar o inimigo...}
{1550}{}{A escuridão acena para mim.}
{1551}{}{A hora da minha morte se aproxima.}
{1552}{}{O Shaman estava certo, eu não voltar.}
{1553}{}{O forasteiro me matou.}
{1554}{}{Eu estou morto.}
{1555}{}{Minhas entranhas estão soltas da minha espinha!}
{1556}{}{Não deixe com vergonha da minha morte.}
{1557}{}{Maldição esses intestinos fracos.}
{1558}{}{Hei, olhe aqui, eu posso ver o meu almoço.}
{1559}{}{Para onde foi todo o ar?}
{1560}{}{Vou rastejar para matá-lo.}
{1561}{}{Devo me manter em pé, devo ....}
{1562}{}{Não me faça correr para pegar você!}
{1563}{}{Você me aleijou, covarde!}
{1564}{}{Awwwwgg!}
{1565}{}{Osso? Tão branco ....}
{1566}{}{Por que eu não posso andar?}
{1567}{}{Arrrrrrgh.}
{1568}{}{Unnhhh.}
{1569}{}{Sinto fogo em minhas pernas.}
{1570}{}{Vou rastejar para matá-lo.}
{1571}{}{Devo me manter em pé, devo ....}
{1572}{}{Não me faça correr para pegar você!}
{1573}{}{Você me aleijou, covarde!}
{1574}{}{Awwwwgg!}
{1575}{}{Osso? Tão branco ....}
{1576}{}{Não posso andar. Oh que dor...}
{1577}{}{Vou queimar seu pé por isso.}
{1578}{}{Ooooo-ouuuuch!}
{1579}{}{Sinto fogo em minha perna.}
{1580}{}{A escuridão está aqui.}
{1581}{}{Onde você está?}
{1582}{}{Ajuda, me ajuda.}
{1583}{}{Eu ainda posso ouvi-lo.}
{1584}{}{Querendo me cegar? Covarde!}
{1585}{}{Minha visão foi roubada.}
{1586}{}{Você pode tirar meus olhos, mas não a minha coragem!}
{1587}{}{Venha aqui para que eu possa matá-lo!}
{1588}{}{A escuridão, a escuridão, Aaaiiiieee!}
{1589}{}{Onde está o meu olho, onde está?!}
{1590}{}{Agora eu tenho muitos filhos.}
{1591}{}{Você luta sem honra.}
{1592}{}{Estou casado, não uso de qualquer maneira.}
{1593}{}{Espíritos santos, o mundo explodiu.}
{1594}{}{suspiro ... não consigo respirar...}
{1595}{}{Em voz alta e estridente--Ouch!}
{1596}{}{Unnhhh. Eu preciso sentar um pouco.}
{1597}{}{Seu filho da puta - eu mato você lentamente por isso.}
{1598}{}{Você não sabe nada de honra.}
{1599}{}{Eu farei você em pedaços como se fosse um animal pronto para o abáte.}
{1600}{}{Oh, meu rosto bonito}
{1601}{}{O meu cérebro dói.}
{1602}{}{Agora eu Pareço o Van Gogh.}
{1603}{}{Maldição, lá se vai o meu nariz.}
{1604}{}{Ei, esse é o meu último dente.}
{1605}{}{Ai, Meu couro cabeludo!}
{1606}{}{Gostaria de ficar na frente de uma garrafa ...}
{1607}{}{Me deixe compartilhar minhas idéias.}
{1608}{}{Ahhh, esse era meu olho bom.}
{1609}{}{Meu olho bom sai lágrimas.}
{1610}{}{Você me desarmou!}
{1611}{}{Ooohh, que dor, que dor.}
{1612}{}{Eu ainda tenho alguns dedos da mão esquerda.}
{1613}{}{Eu só precisa de um dedo para * você *, covarde.}
{1614}{}{Então acho que vou te dar uma mão.}
{1615}{}{Isso é pior do que uma unha encravada.}
{1616}{}{Isso acabou com meu swing.}
{1617}{}{Vou esfaqueá-lo com meu coto!}
{1618}{}{Ei, para onde foram meus?}
{1619}{}{Isso vai ser ótimo. Pareço-me com Capitão Gancho.}
{1620}{}{Deveria ter usado a direita.}
{1621}{}{Você quebrou o meu braço!}
{1622}{}{Você vai se arrepender disso!}
{1623}{}{Sobrou alguns dedos.}
{1624}{}{Acabou o Wimbledon.}
{1625}{}{Sieg... ah, esquece.}
{1626}{}{Você me desarmou!}
{1627}{}{Eu só precisa de um dedo para * você *, covarde.}
{1628}{}{Te chutarei até a morte.}
{1629}{}{Lá se vai minha grande luva de Michael Jackson!}
{1630}{}{Isso é * meu * fígado, me devolva!}
{1631}{}{Só mais um pouquinho para a direita, ahhh, muito melhor.}
{1632}{}{Gerrk!}
{1633}{}{O que é esse cheiro de mofo? Oh, minha entranhas.}
{1634}{}{Agora que você já me espedaçou, eu estou tão esbelto! Obrigado!}
{1635}{}{./~ [Canta] Eu te dei meu coração....../~}
{1636}{}{Isso fez cócegas nas minhas costelas.}
{1637}{}{De qualquer maneira quem precisa de um apêndice.}
{1638}{}{Acho que você passou um pouco do ponto, doc.}
{1639}{}{Arrggghh, minha coluna!}
{1640}{}{Minhas pernas, eu não consigo sentir minhas pernas.}
{1641}{}{Só uma ferida nas tripas, Sarge.}
{1642}{}{Os pulmões são para maricas.}
{1643}{}{Ei, eu tenho costelas!}
{1660}{}{Ai, minha perna.}
{1661}{}{Você vai pagar por isso!}
{1662}{}{Argh! Você quebra minha perna, eu vou quebrar seu pescoço!}
{1663}{}{Maldição, lá se vai o meu Tango.}
{1664}{}{Maldição, lá se vão meus pés.}
{1665}{}{Eu acho que agora preciso de outra perna.}
{1666}{}{Você acabou com meus sapatos de camurça azul!}
{1667}{}{Você acabou com meus dedos!}
{1668}{}{E eu foi só um de raspão.}
{1669}{}{Eu vou arrancar seus joelhos fora com meus dentes!}
{1670}{}{Minha perna!}
{1671}{}{Você acabou com minhas coisas!}
{1672}{}{Ouch! Hey! Isso é abaixo da cintura!}
{1673}{}{Sabe levantar vergões como ninguém.}
{1674}{}{Me castigue mamãe, eu fui mau.}
{1675}{}{Isso deixará uma boa cicatriz.}
{1676}{}{Todo esse sangue é meu?}
{1677}{}{Xerife Dillon, Xerifel Dillon!}
{1678}{}{Isso vai me dar bolhas.}
{1679}{}{Kai, yai, yippee, ai, ay!}
{1680}{}{Maldição sangue em meus olhos!}
{1681}{}{O meu olho! Você vai pagar por isso!}
{1682}{}{Safado!}
{1683}{}{Quem apagou as luzes?}
{1684}{}{Hah, la se foi meu olho de vidro!}
{1685}{}{Faz um barulho como se estoura uma uva madura, não é assim?}
{1686}{}{Ei você esta com meu olho, uh, você pode me devolver, por favor?}
{1687}{}{Eu ainda posso rastreá-lo apenas pelo som!}
{1688}{}{Aiyeee! Aiyeee! meus olhos!}
{1689}{}{Me cegou porque você está com medo, não é.}
{1690}{}{Você não é um cavalheiro.}
{1691}{}{Yooooouuuuch!}
{1692}{}{Unnhhhhh!}
{1693}{}{Talvez se eu simplesmente não se mover por um tempo ....}
{1694}{}{Essa é a minha carne mortadela!}
{1695}{}{Lá se vai minha vida social.}
{1696}{}{Eu acho que preciso me sentar um pouco.}
{1697}{}{Pô, Olha! um coquetel de Ostras Prairie.}
{1698}{}{Oohh, isso dói.}
{1699}{}{Será que isso ...? Oh, sim, isso dói.}
{1700}{}{Ei, olha! Ostras Prairie.}
{1701}{}{Alguem quer nozes picadas?}
{1702}{}{Não poderei mais escrever meu nome na neve.}
{1703}{}{Na cara! Na cara não...}
{1704}{}{Minha cabeça ... ... ficando tonto ...}
{1705}{}{Ugnnn!}
{1706}{}{Na cara! Na cara não!}
{1710}{}{Eu posso bater em você com um braço!}
{1711}{}{Médico! Fudeu com meu braço!}
{1712}{}{Ack! Ainda bem que eu sou ambidestro...}
{1720}{}{Você quebrou o meu braço! Agora a luta é justa!}
{1721}{}{Médico! Fudeu com meu braço!}
{1722}{}{Você precisará remover mais do que o meu braço para se salvar seu burro!}
{1730}{}{Ahhg! Grande tiro!}
{1731}{}{Hnrgggg! Não posso ... respirar ...}
{1732}{}{Minhas costelas estão feridas. Agora vou retirar as suas! É justo!}
{1733}{}{Você... vai ... pagar ... por... isso!}
{1734}{}{* Ooooof * Deus, como odeio isso ...}
{1735}{}{Nggg! No complexo solar!}
{1760}{}{Maldição! Minha perna!}
{1761}{}{Eu não preciso de duas pernas para chutar sua bunda.}
{1762}{}{Vou precisar de um stimpack para a minha perna ...}
{1763}{}{Urggg ... perna se ... ferrou ...}
{1770}{}{Maldição! Minha perna!}
{1771}{}{* Ergg * Vai ter troco ...}
{1772}{}{Vou precisar de um stimpack para a minha perna ...}
{1773}{}{Urggg ... perna se ... ferrou ...}
{1780}{}{Merda! Nos olhos não!}
{1781}{}{Tentando inviabilizar minha percepção de profundidade, não é?}
{1782}{}{Não posso ... ver ... sangue ... dentro ... dos olhos ...}
{1783}{}{Não preciso te ver, posso sentir seu cheiro!}
{1790}{}{O que você acha que é isso? Algum filme barato de ação?}
{1791}{}{Minhas bolas! Venha aqui e deixe-me fazer isso com você!}
{1792}{}{Bem, lá se vão as minhas bolas de bronze.}
{1793}{}{Me desculpe por vomitar tudo sobre mim mesmo.}
{1794}{}{Grande. Eu começo a lutar com alguém que tem fixação por bolas.}
{1795}{}{Deixe-me descansa um pouco, então depois vou te matar.}
{1796}{}{Minhas bolas! Oh bem, sem filhos para mim.}
{1800}{}{Whoa. Algo me atingiu no rosto.}
{1801}{}{O que acabou de me bater na cabeça?}
{1802}{}{Ngggg}
{1803}{}{Ainda bem que estou chapado de Jet, ou teria sido muito doloroso.}
{1804}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
{1810}{}{Hey! Alguém acabou de bater no meu braço!}
{1811}{}{Olha, meu braço é apenas para desenhar. Pare de atacá-lo.}
{1812}{}{Nggggg}
{1813}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
{1820}{}{Hey! Alguém acabou de bater no meu braço!}
{1821}{}{Olha, meu braço é apenas para desenhar. Pare de atacá-lo.}
{1822}{}{Nggggg}
{1823}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
{1830}{}{Meu estômago!}
{1831}{}{Ai! Owwww, meu maldito peito! Ai!}
{1832}{}{Hey! Porque você me bateu no peito?, idiota!}
{1833}{}{Pare de me bater no peito!}
{1834}{}{Whoa. Meu peito. Isso machucou legal.}
{1835}{}{Nrgggg}
{1836}{}{*hfff*}
{1837}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
{1860}{}{Hey! Alguém acabou de bater na minha perna!}
{1861}{}{Hey! Eu ando com a perna!}
{1862}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
{1870}{}{Hey! Alguém acabou de bater na minha perna!}
{1871}{}{Hey! Eu ando com a perna!}
{1872}{}{Owwwww! Alguém me dê um Stimpack! Ou algum Jet!}
{1880}{}{Isso é como sentir uma agulha no olho ...}
{1881}{}{Hey! Eu vejo com aquele olho!}
{1882}{}{MEUS Olhos! MEUS Olhos! Meus olhos doem!}
{1890}{}{Estou tão chapado de Jet, que mal senti isso. Ah ... não, espere.}
{1891}{}{*Hurhkkkk*}
{1892}{}{Chuta minhas partes, anda!}
{1893}{}{Nghhhhh!}
{1894}{}{Na virilha não! Na virilha não!}
{1895}{}{Os meus órgãos genitais! Meus pobres órgãos genitais!}
{1896}{}{Me desculpe por vomitar em todo o lugar.}
{1897}{}{Isso... dói... muito.}
{1898}{}{Espero que a minhas partes vá para o céu genital.}
{2000}{}{Misericórdia!}
{2001}{}{Alguém me ajude!}
{2002}{}{Por favor, pare!}
{2003}{}{Ajuda!}
{2004}{}{Aaaaahhhh!}
{2005}{}{Misericórdia!}
{2006}{}{Alguém me ajuuuuuude!}
{2007}{}{Oh Deus, Oh Deus, Oh Deus....}
{2008}{}{Só não me mate, porfavoooooor!}
{2009}{}{Não me mate!}
{2010}{}{Por favor não me mate.}
{2011}{}{Me ajude! Por favor! Ajudeeeeee!}
{2012}{}{Só não me machuque mais.}
{2013}{}{Por favor, pare de me bater!}
{2014}{}{Não, pare, por favor, nãããão!}
{2015}{}{Não, por favor, não me machuque mais!}
{2016}{}{Eu não aguento mais!}
{2017}{}{Pelo amor de Deus, me deixe em paz.}
{2018}{}{De novo não, eu tenho que sair daqui.}
{2019}{}{Ajuda! Estou sendo morto! Ajuda!}
{2020}{}{Hmm, uh, pare!}
{2021}{}{Eu não gosto de seu tipo ...}
{2022}{}{Eu realmente esperava que não chegasse a isso...}
{2023}{}{Eu acho que eu tenho que me defender}
{2024}{}{Eu acho que eu tenho que me defender}
{2025}{}{Eu realmente esperava que não chegasse a isso...}
{2026}{}{Por favor, não me obrigue a fazer isso.}
{2027}{}{Oh querido, oh meu.}
{2028}{}{De verdade, não quero ter que fazer isso.}
{2029}{}{Shoo! Vá-se embora! Shoo!}
{2030}{}{Cai fora e não vou te machucar.}
{2031}{}{Não me faça fazer isso.}
{2032}{}{Cuidado, eu esou muito perigoso. De verdade. Eu sou.}
{2033}{}{É melhor você tomar cuidado, eu tenho muitos amigos.}
{2034}{}{Sou muito perigoso, é melhor você correr.}
{2035}{}{Uh, eu não * quero * te atacar.}
{2036}{}{Apenas vá embora, e ninguém vai se machucar.}
{2037}{}{Eu não faça mal a ninguém.}
{2038}{}{Eu não quero ter que matar de novo, por favor, não me faça.}
{2039}{}{Por que sempre temos que chegar a isso?}
{2040}{}{Tome isso!}
{2041}{}{Você não deveria ter começado isso!}
{2042}{}{Você pediu por isso!}
{2043}{}{Você gosta disso?}
{2044}{}{Tome isso!}
{2045}{}{Otário!}
{2046}{}{Eu não quero fazer isso!}
{2047}{}{Sim, quem tem medo agora!}
{2048}{}{Eu não queria lutar, mas ...}
{2049}{}{Canalha!}
{2050}{}{É melhor tomar cuidado comigo!}
{2051}{}{Estou armado e sou muito perigoso, certo.}
{2052}{}{É, depois de tudo isso não é tão dificil.}
{2053}{}{Uau, posso fazer isso!}
{2054}{}{Me sinto tão fortalecido.}
{2055}{}{Sim! Sinta a dor, idióta!}
{2056}{}{Vai morrer.}
{2057}{}{Oh, sim, sou mau, sou muito mau.}
{2058}{}{Vou acabar com você!}
{2059}{}{Sou fodão. É melhor tomar cuidado.}
{2060}{}{Sou melhor do que pensava}
{2061}{}{Não vou desistir!}
{2062}{}{Uau, poderia ter me ferido!}
{2063}{}{Ufa! Eu ainda estou vivo!}
{2064}{}{Hey! Poderia ter me ferido!}
{2065}{}{Ufa! Eu ainda estou vivo!}
{2066}{}{Estou morto ... ei, espera, não estou.}
{2067}{}{Ouch! Isso ..., você errou.}
{2068}{}{Estou sangrando em algum lugar?}
{2069}{}{Você errou? Eu não acredito.}
{2070}{}{Sabia que não estava apontando para mim de verdade!}
{2071}{}{Hah, hah. Você não presta!}
{2072}{}{(Você faz bugigangas) Nyah, nyah, nyah, nyah, nyah.}
{2073}{}{(Eleva um dedo para você)}
{2074}{}{Você não é tão quente.}
{2075}{}{Da pena, eu não posso acreditar que eu estava com medo de você.}
{2076}{}{Sabia que não queria me matar.}
{2077}{}{Isso estava perto de mais.}
{2078}{}{Ainda bem que eu sou tão astuto.}
{2079}{}{Pare de atirar em mim!}
{2100}{}{Ataque mais alguém, por favor!}
{2101}{}{Tenha misericórdia!}
{2102}{}{Alguém me ajude!}
{2103}{}{Por favor, pare!}
{2104}{}{Me deixe em paz.}
{2105}{}{Eu não vou morrer por isso!}
{2106}{}{Pare de pegar em mim!}
{2107}{}{Socorro! Socoorrroo!}
{2108}{}{Esta me matando! Socorro!}
{2109}{}{Corra por sua vida!}
{2110}{}{Eu não fiz nada! Me deixa viver!}
{2111}{}{Eh, o que queria que eu fizesse? sindo muito!}
{2112}{}{Foda-se, merda, merda!}
{2113}{}{Eu não quero morrer assim!}
{2114}{}{Nos deixe em paz!}
{2115}{}{Oh Deus, oh Deus, oh Deus, noooooo!}
{2116}{}{Não me mate, por favor!}
{2117}{}{Eu não fiz nada pra você!}
{2118}{}{Qual o seu problema?}
{2119}{}{Socorro! Há um psicopata à solta!}
{2120}{}{Espere até que eu te ...}
{2121}{}{É isso aí, eu já estou cansado de tipos como você.}
{2122}{}{Ei, você!}
{2123}{}{Você não é bem vindo aqui}
{2124}{}{Ninguém vai destruir este lugar ...}
{2125}{}{Quem você pensa que é?}
{2126}{}{Você não pode simplesmente fazer o que quiser aqui.}
{2127}{}{Você precisa aprender boas maneiras.}
{2128}{}{Eu ja me cansei de você.}
{2129}{}{Você e os outros de sua classe são todos iguais.}
{2130}{}{Eu não queria ter que fazer isso.}
{2131}{}{Eu odeio você e tudo o que você representa.}
{2132}{}{É patifes como você que tornam a vida difícil para as pessoas decentes.}
{2133}{}{Alguém precisa acabar com você por tudo que tem feito.}
{2134}{}{Você precisa levar uma surra!}
{2135}{}{Você não pode simplesmente fazer algumas coisas e não esperar que se tenha consequencias.}
{2136}{}{Seus dias aqui estão contados.}
{2137}{}{Porra, eu não vou aceitar isso.}
{2138}{}{Estou totalmente louco e eu não vou agüentar mais isso!}
{2139}{}{Caia fora daqui.}
{2140}{}{Você não deveria ter feito isso.}
{2141}{}{Preocupamos uns com os outros.}
{2142}{}{Isto é o que fazemos com vermes!}
{2143}{}{Você é uma aberração mutante!}
{2144}{}{Idiota!}
{2145}{}{Vou te enfiar de volta na buceta da tua mãe.}
{2146}{}{Aprenda com isso!}
{2147}{}{Bem. Você pediu por isso.}
{2148}{}{Animal!}
{2149}{}{Você merece o que está passando!}
{2150}{}{Espero que isso dói.}
{2151}{}{Isso vai te ensinar boas maneiras.}
{2152}{}{Você tem que aprender.}
{2153}{}{Tome isso!}
{2154}{}{Aprenda como devolver os golpes!}
{2155}{}{Eu ja me cansei de gente como você!}
{2156}{}{Sinta a dor!}
{2157}{}{Não voltara a fazer isso!}
{2158}{}{Este é um golpe fodão!}
{2159}{}{Yeah, Tome isso!}
{2160}{}{Não sou tão ruim, sou?}
{2161}{}{Eu vi mais Brahmin mais esperto que você}
{2162}{}{Ufa!}
{2163}{}{Eu nao sou uma presa facil.}
{2164}{}{Graças a Deus!}
{2165}{}{Errou!}
{2166}{}{Você não é tão bom assim.}
{2167}{}{Hah hah, você não é de nada!}
{2168}{}{Eu pensei que você ....}
{2169}{}{Sou melhor nisso do que eu pensava.}
{2170}{}{Você não pode me bater!}
{2171}{}{Você me bateu! Oh? Talvez não!!}
{2172}{}{Yeah! Você errou!}
{2200}{}{Não vale a pena!}
{2201}{}{Tenho coisas melhores para fazer.}
{2202}{}{Alguém me ajude!}
{2203}{}{Você me venceu... desta vez}
{2204}{}{Vai ter o que merece!}
{2205}{}{Eu não vou morrer por isso!}
{2206}{}{Você tem que dormir em algum momento, e eu vou estar lá quando você o fizer.}
{2207}{}{Teve sorte.}
{2208}{}{Você venceu a batalha, mas a guerra quem vai ganhhar será eu.}
{2209}{}{Desta vez você ganhou.}
{2210}{}{Da próxima vez a sorte vai estar do meu lado.}
{2211}{}{Melhor viver hoje para lutar outro dia.}
{2212}{}{Estou fora daqui.}
{2213}{}{Você não vale a pena.}
{2214}{}{Merda, eu não acho que você daria muito trabalho.}
{2215}{}{Merda, é hora de sumir.}
{2216}{}{Você é um filho da puta desagradável!}
{2217}{}{Eu sou mau, mas você é muito mais.}
{2218}{}{Asta la vista!}
{2219}{}{Saborei as bananas!}
{2220}{}{É tarde demais para correr!}
{2221}{}{Quem te deixou entrar aqui?}
{2222}{}{Ei, você!}
{2223}{}{Nós não gostamos de seu tipo por aqui!}
{2224}{}{Ninguém vai destruir este lugar ...}
{2225}{}{Quem você pensa que é?}
{2226}{}{Isso vai ser bom.}
{2227}{}{Eu acho que você não vai gostar disso.}
{2228}{}{Eu vou gostar disso.}
{2229}{}{Vamos começar machucando.}
{2230}{}{Vamos dançar.}
{2231}{}{Hora de bailar!}
{2232}{}{Achou que vou te matar lentamente.}
{2233}{}{Eu vou gostar de ver suas entranhas espalhadas no chão.}
{2234}{}{Gostaria de saber o que vai fazer quando eu sangrar você.}
{2235}{}{Bem-vindo às grandes ligas, novato.}
{2236}{}{Eu adoro ver como se contorce.}
{2237}{}{Espero que este seja um desafio.}
{2238}{}{Oh sim! Estava a muito tempo esperando por isso.}
{2239}{}{Vamos ver do que realmente voce e feito.}
{2240}{}{Tome isso!}
{2241}{}{Você gosta disso?}
{2242}{}{Isto é o que fazemos com vermes!}
{2243}{}{Isto é para você!}
{2244}{}{Good-bye!}
{2245}{}{Vamos em frente!}
{2246}{}{Escória problemática!}
{2247}{}{Eu vou bater em você como um filho da puta.}
{2248}{}{Animal!}
{2249}{}{Você vai se arrepender de colocar o pé aqui!}
{2250}{}{Sinta essa dor.}
{2251}{}{Sinta essa dor, filho da puta!}
{2252}{}{Você gosta não é?}
{2253}{}{Isso é vai te sangrar!}
{2254}{}{Esta começando a se cansar?}
{2255}{}{Ah, sim, este é o lugar onde ele está.}
{2256}{}{Sentiu isso?}
{2257}{}{Sim amigo, segura esses golpes.}
{2258}{}{Toma, toma mais!}
{2259}{}{Adoro ver o sangue jorar.}
{2260}{}{Você não é tão bom quanto pensa.}
{2261}{}{Patético.}
{2262}{}{Você é apenas um bandido comum.}
{2263}{}{Não é nada especial.}
{2264}{}{Eu não vou ser sua vítima.}
{2265}{}{Esse foi seu último erro.}
{2266}{}{Era o seu melhor tiro?}
{2267}{}{E eu que pensei que isto ia ser uma luta.}
{2268}{}{Da proxima vez tente apontar para mim.}
{2269}{}{Você é apenas um maldito palhaço.}
{2270}{}{Malditos aficionados!}
{2271}{}{É a sua primeira vez, criançã?}
{2272}{}{Eu nem sequer tento esquivar disso.}
{2300}{}{Estou fugindo.}
{2301}{}{Eu voltarei!}
{2302}{}{Mais tarde, seu puto!}
{2303}{}{Isso foi divertido, mas eu vou embora!}
{2304}{}{Pagará por isso... depois!}
{2305}{}{Vamos fazer isso novamente em breve!}
{2306}{}{Eu vou estar de volta.}
{2307}{}{Te vejo por aí.}
{2308}{}{Eu voltarei, até lá você pode sonhar comigo.}
{2309}{}{Você me deixa entediado.}
{2310}{}{Eu vou encher a cara de pinga, depois eu volto.}
{2311}{}{Vou procurar um desafio em outro lugar.}
{2312}{}{Temos que fazer isso de novo algum dia.}
{2313}{}{Foi divertido, tchau.}
{2314}{}{Whoa, esta na hora do almoço.}
{2315}{}{Isso foi ótimo, me fez suar!}
{2316}{}{Hora de conseguir munições e alguns stimpacks!}
{2317}{}{Espere aqui, voltarei daqui a pouco.}
{2318}{}{Eu tenho alguns amigos que vão querer se juntar nisso.}
{2319}{}{Vamos fazer isso de novo, algum dia.}
{2320}{}{Vou pregar suas orelhas para trás!}
{2321}{}{Carne fresca!}
{2322}{}{Você só fez alegrar meu dia!}
{2323}{}{Você vai ser minha puta!}
{2324}{}{Vou pregar suas orelhas para trás!}
{2325}{}{Eu vou-me por em seu lugar!}
{2326}{}{Mmm, vou gostar disso.}
{2327}{}{Eu quero ficar um tempo com você.}
{2328}{}{Você não vai gostar disso, mas tenho certeza que eu vou.}
{2329}{}{Nunca enfrentou um autentico profissional, não é mesmo?}
{2330}{}{Isso vai ser muito bom.}
{2331}{}{Adoro o som de ossos quebrando.}
{2332}{}{Isso vai me fazer sentir melhor.}
{2333}{}{Suas tripas vão ficar jogadas no chão.}
{2334}{}{Me pergunto quanto de sangue você tem?}
{2335}{}{Espero que você tenha alguma resistência.}
{2336}{}{Isto com certeza não se parece com um grande desafio.}
{2337}{}{Isso não vai durar muito tempo.}
{2338}{}{Fique quieto e isso acabará logo.}
{2339}{}{Pelo menos você vai morrer pelo melhor de todos.}
{2340}{}{Eu vou pegar você!}
{2341}{}{Hora de jogar!}
{2342}{}{Por favor, não se humilhe. A morte deve ser digna.}
{2343}{}{Eu espero que você não morra muito rapidamente.}
{2344}{}{Tem algumas últimas palavras?}
{2345}{}{Tome isso!}
{2346}{}{Morra! Morra! Morra! Morra! Morra!}
{2347}{}{Morra!}
{2348}{}{Vamos abri-lo um pouco ...}
{2349}{}{Vai virar ração de cachorro, amigo.}
{2350}{}{Você lutou contra o resto, agora é hora de enfrentar o melhor!}
{2351}{}{Oh yeah! Isso é ótimo!}
{2352}{}{Adoro ver o quanto você sangra!}
{2353}{}{Amigo, alguma vez viu um cranio aberto dessa maneira?}
{2354}{}{Olhe para o respingo de sangue! Sim, foi muito longe!}
{2355}{}{Você é um filho da puta!}
{2356}{}{Porra, adoro isso!}
{2357}{}{Vai se fuder, pau no cu!}
{2358}{}{Sim nenem, sim!}
{2359}{}{Asta la Vista, Baby.}
{2360}{}{Não me toque.}
{2361}{}{Você me fez chorar}
{2362}{}{Vamos lá seu merda, lute comigo!}
{2363}{}{Isso é o melhor que pode fazer?}
{2364}{}{Você não presta!}
{2365}{}{Isso vai ser mais fácil do que eu pensava}
{2366}{}{Da próxima vez tente me acertar.}
{2367}{}{Você esta brincando comigo?}
{2368}{}{Me bate! Vamos maldito covarde! Me bate!}
{2369}{}{Um tiro bem no meio da cabeça!}
{2370}{}{Você não tem coragem não é?}
{2371}{}{Bem no meio das pernas.}
{2372}{}{Merda, eu pensei que isso ia ser uma espécie de desafio!}
{2400}{}{Vou sair daqui!}
{2401}{}{Péssima ideia, parceirinho!}
{2402}{}{Ataque outro, vai!}
{2403}{}{Caramba!}
{2404}{}{Eu não vou morrer por isso!}
{2405}{}{Isso é demais para mim!}
{2420}{}{Ei, você!}
{2421}{}{Eu vou te ensinar boas maneiras!}
{2422}{}{Nós não gostamos de seu tipo por aqui!}
{2423}{}{Você precisa aprender um pouco de respeito!}
{2424}{}{Hora de ganhar meu salário ...}
{2425}{}{Espere até que eu te ...}
{2426}{}{Por que você vai fazer isso?}
{2427}{}{Há sempre idiotas como você por perto para atrapalhar um pouco.}
{2440}{}{Tome isso!}
{2441}{}{É bom não é?}
{2442}{}{Deveria ter me deixado sozinho.}
{2443}{}{Você gosta disso?}
{2444}{}{Onde está sua mãe agora?}
{2445}{}{Toma isso!}
{2446}{}{Vamos ver o quão duro você é ...}
{2447}{}{Bastardo!}
{2448}{}{Folgado!}
{2449}{}{Vou te matar para o bem de todos.}
{2460}{}{Sua mãe te ensinou isso?}
{2461}{}{Simplesmente chupa!}
{2462}{}{Não é suficientemente bom.}
{2463}{}{Esse foi seu último erro.}
{2464}{}{Amador.}
{2465}{}{Você aprende a lutar em bares?}
{2500}{}{Tenho que sair daqui!}
{2501}{}{Eu voltarei...}
{2502}{}{Não vai me matar hoje!}
{2503}{}{Mais tarde, seu puto!}
{2504}{}{Não será a última vez que nos vemos!}
{2505}{}{Vai pagar por isso... mas tarde!}
{2520}{}{Você é história!}
{2521}{}{Carne fresca...}
{2522}{}{Eu vou mijar no seu túmulo.}
{2523}{}{Todo mundo! É um alvo em potencial!}
{2524}{}{Se prepara, vagaba?}
{2525}{}{Vou desfrutar disto ...}
{2540}{}{Toma isso!!!}
{2541}{}{Não adianta ficar gritando por Misericórdia ...}
{2542}{}{Esta é a melhor parte ...}
{2543}{}{Você quer mais disso! Huh!}
{2544}{}{Vou te usar como alimentar para os cães!}
{2545}{}{Não deve começar o que você não pode terminar.}
{2546}{}{Espero que você não morra rápido demais}
{2547}{}{Apenas um de nós vai sair vivo dessa.}
{2548}{}{Morra!}
{2549}{}{Eu como viados como você no café da manhã.}
{2550}{}{Vou usar você como alimento para o meu iguana}
{2551}{}{A última coisa que você verá é o rosto sorridente.}
{2552}{}{Este é meu trabalho favorito.}
{2560}{}{Você é uma piada.}
{2561}{}{Isso é o melhor que pode fazer?}
{2562}{}{Você está fazendo isso fácil.}
{2563}{}{Simplesmente patético...}
{2564}{}{Muito lento!}
{2565}{}{Perdedor!}
{2600}{}{Executado Maligno!}
{2601}{}{Os espíritos me dizem para me salvar.}
{2602}{}{Nosso inimigo tem usado magia poderosa - Corra! Alguém pode chamar um Shaman !}
{2603}{}{O espírito maligno é mais poderoso agora. A morte caminha sobre a terra!}
{2604}{}{O espírito maligno está aqui!}
{2605}{}{O espírito maligno quer nos castigar. Corre!}
{2606}{}{Aiiieeeee!!}
{2620}{}{Meus antepassados guiam meu braço!}
{2621}{}{Sua força será minha.}
{2622}{}{Grande será a minha glória.}
{2623}{}{Vou desonrar sua tribo.}
{2624}{}{Ayah! Nabataluk!}
{2625}{}{Que os espíritos me acompanhem!}
{2626}{}{Venha faça nossas espadas dançarem.}
{2627}{}{Pode começar!}
{2628}{}{U-Suthoooo!}
{2629}{}{Os espíritos me acompanham!}
{2640}{}{Seus antepassados abandonaram você.}
{2641}{}{Sua derrota vai me trazer grande honra. Minha magia não conhece derrota!}
{2642}{}{Renda-se agora e não vamos comer seu coração.}
{2643}{}{Você luta bem. Vou acabar com sua coragem. Os espíritos vão gostar da minha vitória.}
{2644}{}{Vou tomar banho em seu sangue!}
{2645}{}{Eu não tenho medo de você!}
{2646}{}{Trago à paz perdida.}
{2647}{}{Glória na batalha compra a vida eterna! Obrigado estrangeiro.}
{2648}{}{A escuridão te rodeia.}
{2649}{}{Nossos ancestrais estão sedentos por sua alma.}
{2650}{}{Minha espada está sedenta!}
{2651}{}{Vamos beber do cálice da batalha!}
{2660}{}{Seus olhos estão pretos de ódio.}
{2661}{}{Os espíritos abandonaram você.}
{2662}{}{Nossa magia está funcionando!}
{2663}{}{Minha magia me faz invencível!}
{2664}{}{Sua força de vida está enfraquecendo!}
{2665}{}{O medo é um assassino para a mente}
{2666}{}{Meu canto de batalha está funcionando!}
{2667}{}{Nossos filhos sabem mais que você sobre uma batalha!}
{2668}{}{Você conheceu a paz por muito tempo.}
{2669}{}{Todos de sua tribo são fracos?}
{2700}{}{Reforços!!}
{2701}{}{Podem fazer uma lei marcial...}
{2702}{}{Médico!}
{2703}{}{Retirada! Retirada!}
{2704}{}{Voltando! Voltando!}
{2705}{}{Você pode ter vencido a batalha ...}
{2720}{}{Vamos em frente!}
{2721}{}{Oh, sim!!}
{2722}{}{Eu vou te ensinar boas maneiras!}
{2723}{}{Você é história!}
{2724}{}{Ataque!}
{2725}{}{Vamos enterrar esse Perdedor!}
{2726}{}{Preparados!}
{2727}{}{Vamos deixar Deus separar o que sobrou de você.}
{2740}{}{Tome isso!}
{2741}{}{Agora tenho você!}
{2742}{}{Agora é a hora que você vai morrer!}
{2743}{}{Você gosta disso?}
{2744}{}{Este não é apenas um trabalho para nos}
{2745}{}{Não deve começar o que você não pode terminar.}
{2746}{}{É melhor você rezar para os deuses!}
{2747}{}{Você nem vai ver outro amanhecer. }
{2748}{}{Tudo bem?}
{2749}{}{Te vejo no inferno.}
{2760}{}{Posso treinar um pouco.}
{2761}{}{Isso é o melhor que pode fazer?}
{2762}{}{Vamos Perdedor. Lute comigo!}
{2763}{}{Tente apontar melhor da próxima vez.}
{2764}{}{Civil...}
{2765}{}{Deixe isso para os profissionais da próxima vez.}
{2800}{}{}
{2801}{}{}
{2802}{}{}
{2803}{}{}
{2804}{}{}
{2805}{}{}
{2820}{}{}
{2821}{}{}
{2822}{}{}
{2823}{}{}
{2824}{}{}
{2825}{}{}
{2826}{}{}
{2828}{}{}
{2840}{}{}
{2841}{}{}
{2842}{}{}
{2843}{}{}
{2844}{}{}
{2845}{}{}
{2846}{}{}
{2847}{}{}
{2848}{}{}
{2849}{}{}
{2860}{}{}
{2861}{}{}
{2862}{}{}
{2863}{}{}
{2864}{}{}
{2865}{}{}
{2900}{}{fugir! Fugir!}
{2901}{}{Retiro!}
{2902}{}{Reagrupar!}
{2903}{}{Voltando!}
{2904}{}{Retirada!}
{2905}{}{Aaaaghhh!}
{2920}{}{Mate este idiota!}
{2921}{}{Carne fresca...}
{2922}{}{Exterminado!}
{2923}{}{Esse é meu!}
{2924}{}{Ahhhhhhh!}
{2925}{}{Ataque!}
{2940}{}{Aproveite os últimos segundos da sua vida.}
{2941}{}{Sangue! Sangue! Sangue!}
{2942}{}{Seu coração é o meu!}
{2943}{}{RAAAAAAARRRR!!}
{2944}{}{Suas armas serão meus troféus!}
{2945}{}{Morte!}
{2946}{}{Eu mesmo vou te matar!}
{2947}{}{Seus ossos vou sair pra fora!}
{2948}{}{Sangue e escuridão!}
{2949}{}{YAAAAAAAAAAAAH!}
{2950}{}{Idiota Mascarado!}
{2960}{}{Esforço desperdiçado!}
{2961}{}{Errou, idiota!}
{2962}{}{Meu sangue é mais forte que o seu!}
{2963}{}{Estou vivo!}
{2964}{}{Seu corpo é fraco e lento!}
{3000}{}{Inicio da operação de retirada.}
{3001}{}{Plano Tático: Retirada.}
{3002}{}{Efetividade de combate mínima. Se recomenda retirada.}
{3003}{}{Análise tática completada. Recomenda-se retirada.}
{3004}{}{Baixando de programa fuga.}
{3005}{}{Seqüência de retirada iniciada.}
{3020}{}{Alvo adquirido!}
{3021}{}{Exterminar! Exterminar!}
{3022}{}{O humanóide não deve escapar!}
{3023}{}{Eliminar intruso!}
{3024}{}{Seqüência de combate iniciada.}
{3025}{}{Atualizando programa de combate.}
{3040}{}{Seqüência de combate iniciada.}
{3041}{}{Atacando o alvo.}
{3042}{}{Iniciando seqüência de ataque.}
{3043}{}{O intruso deve ser destruído!}
{3044}{}{Seleção de opções táticas concluída.}
{3045}{}{Iniciando ataque.}
{3046}{}{O alvo será destruído.}
{3047}{}{Seqüência de exterminação do inimigo iniciada.}
{3048}{}{Alvo deve ser eliminado.}
{3049}{}{Seleção ofensiva concluída.}
{3060}{}{Análise. Sucesso no programa defensivo.}
{3061}{}{Análise. Ataque ao inimigo ineficiente.}
{3062}{}{Falha no ataque ao alvo. Calculando resposta.}
{3063}{}{Unidade não foi danificada no ataque.}
{3064}{}{Recalculando habilidades ofensivas do alvo.}
{3065}{}{Análise. Alvo errou na seleção tática. Unidade sem danos.}
{3100}{}{Tenho que sair daqui!}
{3101}{}{Eu voltarei...}
{3102}{}{Não vai me matar hoje!}
{3103}{}{Mais tarde, normal!}
{3104}{}{Não vai ser o último a ouvir falar de mim!}
{3105}{}{Vai pagar por isso... mas tarde!}
{3106}{}{Eu não vou morrer de novo.}
{3107}{}{Pés, não vão falhar agora né!}
{3108}{}{Estou apenas caindo fora.}
{3109}{}{Uh, hora da retirada tática.}
{3110}{}{Saída no fundo esquerdo.}
{3111}{}{É mais tarde do que eu pensava.}
{3112}{}{Tenho que correr. Até mais.}
{3113}{}{Correeeeeeeeeer!}
{3114}{}{Eu tenho que ir recolocar algumas partes.}
{3115}{}{Estes velhos ossos não agüentam mais.}
{3116}{}{Não são os anos, são os milênios.}
{3117}{}{Que mundo é este, Que mundo é este...}
{3118}{}{Acredito aprenda a lição. Agora vou cair fora daqui!}
{3119}{}{Ei, pare de se afastar de mim.}
{3120}{}{Você é história!}
{3121}{}{Carne fresca...}
{3122}{}{Carne, Carne, Carne, Carne a milanesa!}
{3123}{}{Cérebros...}
{3124}{}{Eu vou cavar sua cova...}
{3125}{}{Espero que eu possa manter sua cabeça intacta ...}
{3126}{}{Mais Cérebros...}
{3127}{}{Envie mais policiais!}
{3128}{}{Envie mais Paramédicos!}
{3129}{}{Eu poderia usar algumas peças novas.}
{3130}{}{Um sanduíche de miúdos saindo.}
{3131}{}{Lá vem de novo!}
{3132}{}{É sopa?}
{3133}{}{Onde está a carne?}
{3134}{}{Muito mais cérebros...}
{3135}{}{Você cruzou minha linha... mais ou menos}
{3136}{}{Eu sabia que eu tinha ouvido alguém chamando pra comer.}
{3137}{}{Advinha quem veio comer.}
{3138}{}{Gostaria de tudo um pouco.}
{3139}{}{Você que é meu novo doador de órgãos?}
{3140}{}{Saiu seu número!}
{3141}{}{Não adianta ficar gritando por Misericórdia ...}
{3142}{}{Vou aproveitar isto.}
{3143}{}{Oooo, isso vai doer!}
{3144}{}{Hora de despedaçar e mutilar.}
{3145}{}{Vou comer seu fígado!}
{3146}{}{Espero que você não morra rápido demais!}
{3147}{}{Hora da janta!}
{3148}{}{Morra!}
{3149}{}{Eu como bastardos como você no café da manhã e almoço..}
{3150}{}{Como pode alguém ser tão confuso e mau?}
{3151}{}{Anda, me deixe provar só um pedaço!}
{3152}{}{Dê ao papai algum açúcar, baby!}
{3153}{}{Tenho algo para você!}
{3154}{}{Fique quieto! Vai doer menos.}
{3155}{}{Pare de se mover, o chefe está na cozinha!}
{3156}{}{Adoro os ver sofrerem.}
{3157}{}{Delicioso e nutritivo também!}
{3158}{}{Tenho certeza de que sangrar muito. Deve ser macia e suculenta.}
{3159}{}{Suponho que isso seja mais medo do que emoção.}
{3160}{}{Não pode me bater!}
{3161}{}{Você acha * Ghouls * são lentos?}
{3162}{}{Você perdeu, normal!}
{3163}{}{Você perdeu, normal!}
{3164}{}{Não pode matar aquilo que não se pode ferir!}
{3165}{}{Muito lento!}
{3166}{}{OK, vamos tentar a toda velocidade agora.}
{3167}{}{Você estava realmente apontando para mim?}
{3168}{}{O que foi isso?}
{3169}{}{Isto não é uma charada.}
{3170}{}{Combate exige concentração total.}
{3171}{}{É uma pena que a sua primeira seja a última também.}
{3172}{}{Você está olhando para mim?}
{3173}{}{Quer tentar isso mais tarde quando souber?}
{3174}{}{Não, não, não. É muito ruim de mira, tem que apontar para mim. Entendeu?}
{3175}{}{Em que esta apontando? Parece que esta apontando para TUDO?}
{3176}{}{Isso é o melhor que você faz?}
{3177}{}{Você nunca fez isso antes, certo?}
{3178}{}{Minha vez!}
{3179}{}{Esse foi seu melhor tiro? Caramba, você tem problemas.}
{3200}{}{Whoa. Acho melhor cair fora.}
{3201}{}{Estarei de volta... depois de conseguir outra dose.}
{3202}{}{Sabia que deveria ter tomado mais esteróides...}
{3203}{}{Não posso me drogar se estiver morto...}
{3204}{}{Aieeeeeee! Não me machuque! Não me machuque!}
{3205}{}{Esta alucinação esta cada vez mais real para mim ...}
{3220}{}{Toma isso!}
{3221}{}{Melhor você ter alguns stimpacks ... ou algum Jet.}
{3222}{}{Talvez eu possa vender seu corpo por algum Jet ...}
{3223}{}{Vou te bater ...quando ... te... pega.}
{3224}{}{Talvez matando você eu fique melhor..}
{3225}{}{Eu vou matar você! Eu vou matar você! Eu vou matar você!}
{3226}{}{Matar você vai me fazer bem ...}
{3240}{}{Toma isso!}
{3241}{}{Eu vou matar você! Eu vou matar você! Eu vou matar você!}
{3242}{}{Você quer um pouco disso!}
{3243}{}{Nrrrg!}
{3244}{}{Hiyaaaaaa!}
{3245}{}{Vou te matar lentamente...}
{3246}{}{Você está se comportando tão baixo quanto uma prostituta...}
{3260}{}{Perto, mas nenhum Jet.}
{3261}{}{Sou muito alto, não pode me tocar!}
{3262}{}{Para quem você está apontando?}
{3263}{}{Whoa. Quase me pegou.}
{3264}{}{Eu sabia que um Jet me faria mais rápido ...}
{3265}{}{É um péssimo lutador para ser uma alucinação induzida por drogas.}
{10020}{}{Eu sou Rato Keeng}
{10021}{}{Squeeee! Matei os filhos de Keeng!}
{10022}{}{Keeng vai quebrar seus ossos!}
{10023}{}{Keeng vai comer as suas partes mais moles!}
{10024}{}{Keeng luta, Rato Keeng!}
{10025}{}{Grande luta! Esfola Keeng na caverna!}
{10026}{}{Keeng mata!}
{10027}{}{Fome, fome, Keeng mata, mata!}
{10028}{}{Keeng cheira o medo em você.}
{10029}{}{Rato perdeu as patas traseiras, Keeng matar!}
{10030}{}{Matar, matar!}
{10031}{}{Banquete de carne! Banquete de carne!}
{10032}{}{Keeng destripar! Destripar!}
{10033}{}{Venha aqui para Rato Keeng!}
{10034}{}{Keeng vai destripar suas partes da perna.}
{10035}{}{Keeng matar o nariz grande!}
{10036}{}{Keeng matar rato sem pelo.}
{10037}{}{Keeng desgarrar.}
{10038}{}{Rato te mete uma patada!}
{10040}{}{Eu sou Rato Keeng}
{10041}{}{Squeeee! Matei os filhos de Keeng!}
{10042}{}{Keeng vai quebrar seus ossos!}
{10043}{}{Keeng vai comer as suas partes mais moles!}
{10044}{}{Keeng luta, Rato Keeng!}
{10045}{}{Grande luta! Esfola o Keeng na caverna!}
{10046}{}{Keeng mata!}
{10047}{}{Fome, fome, Keeng mata, mata!}
{10048}{}{Keeng cheira o medo em você.}
{10049}{}{Rato perdeu as patas traseiras, Keeng matar!}
{10050}{}{Matar, matar!}
{10051}{}{Banquete de carne! Banquete de carne!}
{10052}{}{Keeng destripar! Destripar!}
{10053}{}{Venha aqui para Rato Keeng!}
{10054}{}{Keeng vai destripar suas partes da perna.}
{10055}{}{Keeng matar o nariz grande!}
{10056}{}{Keeng matar rato sem pelo.}
{10057}{}{Keeng desgarrar.}
{10058}{}{Rato te mete uma patada!}
{10120}{}{O número cinco está vivo!}
{10121}{}{Vejam, Vejam.}
{10122}{}{Error! Error Errrrrrrooooorrrr....}
{10123}{}{Quem é o criador?}
{10124}{}{Impossivel computar! Impossivel computar!}
{10125}{}{Sinto muito Dave.}
{10126}{}{[Canta] Daisy, Daisy, give me your answer, do}
{10127}{}{Perigo, Bill Williamson, Perigo!}
{10128}{}{Gort! Klaatu Berada Nictu!}
{10129}{}{Sssszzzzztt *POP*}
{10130}{}{Gostaria de creme com isso, minha senhora?}
{10131}{}{Sim senhor, uma unidade Sr. Handy.}
{10132}{}{Sou muito competente.}
{10133}{}{Eu sou um tradutor.}
{10134}{}{Nanoo-nanoo.}
{10135}{}{Eu não posso deixar você fazer isso Dave.}
{10136}{}{Não pode passar.}
{10137}{}{Perigo! Perigo!}
{10138}{}{ZZzzzzzzzttt! Sprack!}
{10139}{}{Mas a M-5 é invencível.}
{10140}{}{O número cinco está vivo!}
{10141}{}{Vejam, Vejam.}
{10142}{}{Error! Error Errrrrrrooooorrrr....}
{10143}{}{Quem é o criador?}
{10144}{}{Impossivel computar! Impossivel computar!}
{10145}{}{Sinto muito Dave.}
{10146}{}{[Canta] Daisy, Daisy, give me your answer, do}
{10147}{}{Perigo, Bill Williamson, Perigo!}
{10148}{}{Gort! Klaatu Berada Nictu!}
{10149}{}{Sssszzzzztt *POP*}
{10150}{}{Gostaria de creme com isso, minha senhora?}
{10151}{}{Sim senhor, uma unidade Sr. Handy.}
{10152}{}{Sou muito competente.}
{10153}{}{Eu sou um tradutor.}
{10154}{}{Nanoo-nanoo.}
{10155}{}{Eu não posso deixar você fazer isso Dave.}
{10156}{}{Não pode passar.}
{10157}{}{Perigo! Perigo!}
{10158}{}{ZZzzzzzzzttt! Sprack!}
{10159}{}{Mas a M-5 é invencível.}
{12000}{}{De jeito nenhum que vou ficar nesta espelunca...}
{12001}{}{Retiro!}
{12002}{}{Hora de cair fora daqui..}
{12003}{}{Dispersar!}
{12004}{}{Voltando!}
{12005}{}{Vou esperar para pegar esses filhos da puta quando Fallout 3 sai ...}
{12006}{}{Bishop fica sossegado aew com seu maldito dinheiro...}
{12020}{}{Alvo adquirido!}
{12021}{}{Alguém me cubra!}
{12022}{}{Vamos vamos vamos vamos vamos}
{12023}{}{Vamos vamos vamos vamos vamos}
{12024}{}{Vamos vamos vamos vamos vamos}
{12025}{}{Beijo na bunda... Beijo na sua bunda tchau ...}
{12026}{}{Hora de fuder com este filho da puta ...}
{12027}{}{Preparados!}
{12028}{}{Rock and roll!}
{12029}{}{Olha quem acabou de entrar para a zona de fogo ...}
{12030}{}{Melhor que você tenha alguns stimpacks, Zé ruéla ...}
{12031}{}{Contato!}
{12032}{}{Perímetro invadido!}
{12033}{}{Temos um intruso, rapazes!}
{12034}{}{Vários, temos vários intrusos, rapazes!}
{12035}{}{Que venham todos para a festa...}
{12036}{}{Pelos números, pessoas, pelos números.}
{12037}{}{Prestem atenção aos detalhes, pessoal!}
{12038}{}{Fogo cruzado, mantenham a cabeça baixa!}
{12040}{}{Destruído!}
{12041}{}{Você está sem sorte, tribal ...}
{12042}{}{Vou meter meu pé na sua bunda, você ficará cheirando sapato polonês durante uma semana.}
{12043}{}{::Quero ser tele transportado...::}
{12044}{}{Buscando golpes críticos!}
{12045}{}{Você quer um pouco disso! Você quer um pouco disso!}
{12046}{}{Hiyaaaaaa!!!}
{12047}{}{Obter algum!}
{12048}{}{Melhor que você tenha alguns stimpacks, Zé ruéla ...}
{12049}{}{Beijo na bunda... Beijo na sua bunda tchau ...}
{12060}{}{Você luta como um velho idiota!}
{12061}{}{Ha! Errou!}
{12062}{}{Rápido de mais pra você...}
{12063}{}{Vai agonizar por muito tempo...}
{12064}{}{Trapalhão...}
{12065}{}{Pelo que vejo, fraco e lento.}
{12100}{}{Tenho que sair daqui!}
{12101}{}{Eu voltarei...}
{12102}{}{Não vai me matar hoje!}
{12103}{}{Mais tarde, normal!}
{12104}{}{Não vai ser o último a ouvir falar de mim!}
{12105}{}{Vai pagar por isso... mas tarde!}
{12120}{}{Você é história!}
{12121}{}{Carne fresca...}
{12122}{}{Ah, o jantar chegou.}
{12123}{}{Cérebros...}
{12124}{}{Eu vou cavar sua cova...}
{12125}{}{Espero que eu possa manter sua cabeça intacta ...}
{12140}{}{Saiu seu número!}
{12141}{}{Não adianta ficar gritando por Misericórdia ...}
{12142}{}{Vou aproveitar isto.}
{12143}{}{Oooo, isso vai doer!}
{12144}{}{Hora de morrer!}
{12145}{}{Vou comer seu fígado!}
{12146}{}{Espero que você não morra rápido demais!}
{12147}{}{Hora da janta!}
{12148}{}{Morra!}
{12149}{}{Eu como bastardos como você no café da manhã e almoço..}
{12160}{}{Não pode me bater!}
{12161}{}{errou!}
{12162}{}{Você perdeu, normal!}
{12163}{}{Você perdeu, normal!}
{12164}{}{Não pode matar aquilo que não se pode ferir!}
{12165}{}{Muito lento!}
{12200}{}{Caralho, esta merda está ficando seria.}
{12201}{}{Hora de ir para os outros caras ...}
{12202}{}{Te mato da próxima vez!}
{12203}{}{Tem sorte de eu não ter uns stimpacks...}
{12204}{}{Hora de cair fora daqui.}
{12205}{}{Preciso encontrar alguns stimpacks e rápido...}
{12220}{}{Vou te fazer de gato e sapato.}
{12221}{}{E lá estava eu, pensando que eu não ia conseguir matar ninguém hoje ...}
{12222}{}{Parece que Gólgota vai ter um novo ocupante...}
{12223}{}{Parece que vamos ter que fazer isso da maneira mais difícil ...}
{12224}{}{Vou arrancar seus dentes e fazer jogo de dados com eles.}
{12225}{}{Parece que alguém quer apostar sua vida...}
{12226}{}{Eu vou matar você, sua família e seu cachorro.}
{12227}{}{Hora de sacar a arma...}
{12228}{}{Vai me servir como chaveiro de sorte...}
{12240}{}{Eu vou chutar o seu traseiro com tanta força que você vai estar usando seu rabo como um chapéu.}
{12241}{}{A dama da sorte não esta com você hoje ...}
{12242}{}{Eu vou te bater até você ficar feio.}
{12243}{}{Hora de por sua bunda no caixão.}
{12244}{}{Vou arrancar seu coração e cagar em cima.}
{12245}{}{Queria ter tempo para colocar a cabeça em um frasco ...}
{12246}{}{Deixe-me mostrar-lhe o que fazer com o lixo por aqui ...}
{12247}{}{Vou te bater tão forte que vai pensar que é um terremoto...}
{12248}{}{Eu já tive o suficiente deste tarado...}
{12249}{}{Diga oi para os anjos por mim...}
{12260}{}{Movimentos como este podem te levar para o hospital...}
{12261}{}{Você bateu como uma puta ...}
{12262}{}{Boa. Em um segundo vou te mostrar como se faz.}
{12263}{}{Você é cego estúpido?}
{12264}{}{Você esta drogado com Jet ou algo assim?}
{12265}{}{Não poderia bater nem na parede de um casino.}
{12266}{}{Se você tentar acertar o ar, você vai errar.}
{12300}{}{Ngggg}
{12301}{}{Minha cabeça ... ficando tonto ...}
{12302}{}{Ugnnn!}
{12303}{}{Na cara! Na cara não!}
{12310}{}{Meu ... braço ... meu ... lindo ... braço.}
{12311}{}{Médico! Fudeu com meu braço!}
{12312}{}{*hffff*}
{12320}{}{Minha mão! Você não tem vergonha?!}
{12321}{}{Médico! Fudeu com meu braço!}
{12322}{}{Parece que não vou poder limpar minha arma com essa mão...}
{12330}{}{Meu estômago!}
{12331}{}{Hnrgggg}
{12332}{}{*hff*}
{12333}{}{Você... vai ... pagar ... por... isso!}
{12334}{}{*Ooooof*}
{12335}{}{Nggg! No complexo solar!}
{12360}{}{Maldição! Minha perna!}
{12361}{}{*Ergg*}
{12362}{}{Vou precisar de um stimpack para a minha perna ...}
{12363}{}{Urggg ... perna se ... ferrou ...}
{12370}{}{Maldição! Minha perna!}
{12371}{}{*Ergg*}
{12372}{}{Vou precisar de um stimpack para a minha perna ...}
{12373}{}{Urggg ... perna se ... ferrou ...}
{12380}{}{Meus olhos! Meus lindos olhos!}
{12381}{}{Tentando inviabilizar minha percepção de profundidade, não é?}
{12382}{}{Não posso ... ver ... sangue ... dentro ... dos olhos ...}
{12390}{}{O que você acha que é isso? Algum filme barato de ação?}
{12391}{}{Agora eu não posso dizer que sou um homem completo.}
{12392}{}{Bem, lá se vão as minhas bolas de bronze.}
{12393}{}{Me desculpe por vomitar tudo sobre mim mesmo.}
{12394}{}{Grande. Um tipo com fixação por bolas.}
{12395}{}{Deixe-me descansa um pouco, então depois vou te matar.}
{12396}{}{Minhas bolas!}
{12400}{}{A cabeça...esta zumbindo..}
{12401}{}{*Urrr*... Filho da puta arrancou meu couro cabeludo...}
{12402}{}{Não estou enxergando... meus olhos estão sangrando... alguém ...}
{12403}{}{A minha cara! A minha cara!}
{12404}{}{Aahhhk...me acertou na porra da minha cabeça!}
{12405}{}{Não apanho assim desde Tommy Bengala...}
{12406}{}{Outro tiro na cabeça com esse e estou acabado...}
{12407}{}{Minha orelha! Arrancou minha maldita orelha!}
{12408}{}{Sinto como se minha cabeça estivesse dentro de um torno...}
{12409}{}{Nrgggg! Na metada da minha cabeça...}
{12410}{}{Meu braço! Você quebrou a porra do meu braço!}
{12411}{}{Merda! Tiro no meu braço esquerdo!}
{12412}{}{Pegou no braço ... porra!}
{12413}{}{Esse hit deslocou meu braço!}
{12414}{}{Owww! Foda-se!}
{12415}{}{Tem sangue por todo o meu braço ...!}
{12416}{}{Minha mão de pistoleiro!}
{12417}{}{* Nfff * ... quase arrancou meu braço...!}
{12418}{}{* Urkkk * ...ainda posso .... bater em você ... com a outra mão ...}
{12419}{}{Vou precisar de alguns stimpacks para o meu braço. Depois de matá-lo.}
{12420}{}{Meu braço! Você quebrou a porra do meu braço!}
{12421}{}{Merda! Tiro no meu braço direito!}
{12422}{}{Pegou no braço ... porra!}
{12423}{}{Esse hit deslocou meu braço!}
{12424}{}{Owww! Foda-se!}
{12425}{}{Tem sangue por todo o meu braço ...!}
{12426}{}{Minha mão de pistoleiro!}
{12427}{}{* Nfff * ... quase arrancou meu braço...!}
{12428}{}{Vou precisar de alguns stimpacks para o meu braço. Depois de matá-lo.}
{12429}{}{* Urkkk * ...ainda posso .... bater em você ... com a outra mão ...}
{12430}{}{Não posso... respirar...}
{12431}{}{*Oooooffff*}
{12432}{}{Maldição...me...deixou...sem...ar...}
{12433}{}{*Unfffff*}
{12434}{}{Acho que acabou de quebrar uma costela...}
{12435}{}{Vou precisar de alguns stimpacks para o meu peito. Depois de matá-lo.}
{12436}{}{Boa pontaria... Agora eu vou quebrar todas as costelas do seu corpo.}
{12437}{}{Dê-me um segundo ... ... para recuperar o fôlego ... então eu vou te matar ...}
{12438}{}{*Hrkkk*}
{12439}{}{Isso foi uma ...estúpidez... vou te mostrar porquê.}
{12440}{}{Vou te destripar como um canibal.}
{12441}{}{Me acertou no peito ...}
{12442}{}{Argghhh! Filho da puta...}
{12443}{}{Isso foi... Sorte...}
{12444}{}{*Unnffff*... tenho que usar uma armadura melhor.}
{12445}{}{Deslocou meu ombro...foi só isso....continuamos a luta.}
{12446}{}{Vou quebrar todos os ossos do seu corpo.}
{12447}{}{Vou arrancar seus dentes por isso...}
{12448}{}{Meu peito está pegando fogo ...}
{12449}{}{Alguém tem alguns stimpacks? Meu peito esta sangrando muito!}
{12450}{}{Merda ... este tribal bate como um...}
{12451}{}{Você quebrou minhas costelas, agora eu vou quebrar seu pescoço.}
{12452}{}{É tudo que você sabe fazer? Cai fora pobre tribal.}
{12453}{}{Ferimento no peito... isso não é nada.}
{12454}{}{Maldição! Quebrou algumas costelas ...}
{12455}{}{Acho que quebrou minha coluna...}
{12456}{}{Deixe eu te mostrar como nós matamos as pessoas aqui.}
{12457}{}{Caralho! No meu estômago! Qualquer coisa, mas não no meu estômago!}
{12458}{}{* Urgggg * ... isso foi um nocaute... alguns órgãos estão soltos ...}
{12459}{}{Vou sujar de sangue todo esse maldito lugar ...}
{12460}{}{Você quebrou Minha perna! Agora eu vou quebrar a sua cara.}
{12461}{}{Eu vou fazer um pano de prato da sua cara.}
{12462}{}{Ahhh! Me acertou na porra do joelho!}
{12463}{}{Eu vou quebrar ambos os seus joelhos para que ...}
{12464}{}{Justo na perna ...}
{12465}{}{Você teve sorte, idiota ...}
{12466}{}{Vou ficar aleijado sem esta perna...}
{12467}{}{Tiro da perna... hora da vingança.}
{12468}{}{Eu não preciso dessa perna para chutar sua bunda.}
{12469}{}{Eu vou arrancar sua perna e bater em você com ele.}
{12470}{}{Você quebrou Minha perna! Agora eu vou quebrar a sua cara.}
{12471}{}{Eu vou fazer um pano de prato da sua cara.}
{12472}{}{Ahhh! Me acertou na porra do joelho!}
{12473}{}{Eu vou quebrar ambos os seus joelhos para que ...}
{12474}{}{Justo na perna ...}
{12475}{}{Você teve sorte, idiota ...}
{12476}{}{Vou ficar aleijado sem esta perna...}
{12477}{}{Tiro da perna... hora da vingança.}
{12478}{}{Eu não preciso dessa perna para chutar sua bunda.}
{12479}{}{Eu vou arrancar sua perna e bater em você com ele.}
{12480}{}{Ahhhh, merda! A porra do meu olho!}
{12481}{}{Erggg...Isso foi... Sorte...}
{12482}{}{Porra..tudo esta escuro..}
{12483}{}{Nada que... um tapa-olho ... nao vai curar ...}
{12484}{}{Vou arrancar seus dois olhos por isso... devagar.}
{12485}{}{Estou cego! Socorro! Estou cego!}
{12486}{}{Não posso ver... cabeça girando...}
{12487}{}{Vai agonizar por muito tempo...}
{12488}{}{Não consigo ver nada merda! Onde esta? Vou te matar!}
{12489}{}{*Hrrkkkk*}
{12490}{}{*Uhhhnnnnnn*...tenho...que...descançar...}
{12491}{}{Eu ... vou acabar com você... por ter batido em minhas bolas ...}
{12492}{}{*Hrkkkk*...}
{12493}{}{Minhas bolas! Minhas maldidas bolas do saco!}
{12494}{}{Golpe baixo...}
{12495}{}{Golpe baixo! Filho da puta!}
{12496}{}{Não vou mirar ai embaixo. Não vou mirar ai embaixo.}
{12497}{}{Você vai ver. Vou dizer a Tommy Bengala para te buscar!}
{12498}{}{Não sentia tanta dor assim desde que aquela prostituta me deixou uma marca...}
{12499}{}{* Unnfffff * ... Eu acho que minhas bolas ... estão ... dentro .. do meu estômago ... ...}
{14000}{}{Buscar para Zomak!}
{14001}{}{Deixe-me em paz!}
{14002}{}{Pare de me incomodar.}
{14003}{}{Vocês humanos sempre agindo dessa maneira.}
{14004}{}{É esta a única maneira que você pode lidar com o desconhecido?}
{14005}{}{Respostas simples para mentes simples.}
{14006}{}{Eu não posso acreditar que você está agindo dessa maneira.}
{14007}{}{Shoo! Cai fora daqui!}
{14008}{}{Eu deveria ter pensado melhor antes de falar com um ser humano.}
{14009}{}{Você deve destruir tudo o que você não entende?}
{14020}{}{Isso vai doer mais em mim do que em você.}
{14021}{}{Eu não gosto de ter que fazer isso.}
{14022}{}{Normalmente, eu evitar a violência, mas no seu caso, vou abrir uma exceção.}
{14023}{}{Eu realmente vou ter que usar o fio dental depois disso.}
{14024}{}{Você não precisa nem ter um bom cheiro.}
{14025}{}{Isso vai fazer um desastre.}
{14026}{}{Você me pressionou demais desta vez.}
{14027}{}{Que pena, eu quase gostei de você.}
{14028}{}{Agora vai ter que morrer.}
{14029}{}{Esperava que não teria que fazer isso.}
{14040}{}{Então eu irei por você.}
{14041}{}{Touche!}
{14042}{}{En Garde!}
{14043}{}{Hai-Kee-Baaa!}
{14044}{}{Vou te pegar!}
{14045}{}{Prepare suas mãos.}
{14046}{}{Uh, é como desenhar um passaro, não é?}
{14047}{}{Hai-Yah!}
{14048}{}{Isso pode ser considerado apenas como um esporte.}
{14049}{}{Deixe o terráqueo para mim! Sempre quis dizer isso.}
{14060}{}{Hah, você é um bípede desajeitado!}
{14061}{}{De novo desequilibrado!}
{14062}{}{O que foi isso?}
{14063}{}{Isto não é uma farsa!}
{14064}{}{O que? você de novo?}
{14065}{}{Você estava realmente tentando? Como é triste.}
{14066}{}{Me alcançar é importante para você?}
{14067}{}{Mais rápido do que você pensou, não é?}
{14068}{}{Nada mal para um velho roedor hein?}
{14069}{}{Tente usar o * outro lado *.}
{18000}{}{Na cara não...}
{18001}{}{Nffff}
{18002}{}{Ainda bem que meu cérebro já são filmados ...}
{18010}{}{Nffff}
{18011}{}{Ernhhh}
{18020}{}{Nffff }
{18021}{}{Ernhhh }
{18030}{}{Oooof}
{18031}{}{Nfff}
{18032}{}{Ernhhh}
{18033}{}{Hrggg}
{18034}{}{Deveria levantar suas mãos...}
{18035}{}{Não tenho dor, Não tenho dor..}
{18060}{}{Nada de golpe abaixo da cintura!}
{18061}{}{Atacando as pernas seu pedaço de bosta.}
{18070}{}{Nada de golpe abaixo da cintura!}
{18071}{}{Atacando as pernas seu pedaço de bosta.}
{18080}{}{Apontando para os olhos, não é?}
{18081}{}{Nfff}
{18082}{}{Lá vai o olho do tigre ...}
{18090}{}{Nada de golpe abaixo da cintura!}
{18091}{}{Eu sabia que deveria ter usado o meu copo.}
{18092}{}{Você vai pagar por isso, vou encher você de chutes puta!}
{18100}{}{Adrian! Adrian!}
{18101}{}{Podia ter sido um concorrente!}
{18102}{}{Não vai haver revanche!}
{18103}{}{Devo praticar um pouco mais...}
{18104}{}{Eu sabia que deveria ter tomado mais esteroides ...}
{18105}{}{Deixa eu tomar um pouco de Psycho e voltarei.}
{18106}{}{Hora de sair daqui.}
{18107}{}{Talvez eu possa encontrar alguma luta mais fácil em outro lugar.}
{18120}{}{Você quer um pouco disso!}
{18121}{}{Você vai beijar a lona!}
{18122}{}{Hora de fazer de você minha puta ...}
{18123}{}{Vou te bater até você ficar feio...}
{18124}{}{Vou te deixar feio ...}
{18125}{}{Agora chega de brincadeira...}
{18126}{}{Vou perder meu tempo te machucando ...}
{18127}{}{Vou acabar com você...}
{18140}{}{Quem é que manda aqui?}
{18141}{}{Você quer um pouco disso?}
{18142}{}{Ernhhh}
{18143}{}{Hrghhh}
{18144}{}{Hrggg}
{18145}{}{Toma isso!}
{18146}{}{Você vai beijar a lona!}
{18147}{}{Cadela!}
{18148}{}{Vou fazer de você uma puta ...}
{18149}{}{Não vai haver revanche!}
{18150}{}{Buscando golpes críticos!}
{18151}{}{Lute contra essa merda!}
{18152}{}{SUPER... NUCLEAR... TORNADO... NUCLEAR... }
{18153}{}{Vou te quebrar. }
{18154}{}{Vou acabar com você...}
{18160}{}{Muito lento!}
{18161}{}{Nada além de internet.}
{18162}{}{Eu bati como uma borboleta... você bate como o meu avó.}
{18163}{}{Lixo como você não da conta de bater em ninguem.}
{18164}{}{Ha! Se você tentou acertar o ar, você vai errar.}
{18165}{}{Parece que temos um cego aqui ..}
{18166}{}{Você não vale nada!}
{18167}{}{Deve estar vendo dobrado...}
{18168}{}{Você não vai ter outra chance igual a essa...}
{18169}{}{Você luta como um coitado! }
{18170}{}{Você não tem coragem!}
{18171}{}{Você é um vagabundo! Um vagabundo!}
{18172}{}{Vou acabar com você...}
{18173}{}{O que, você esta vendo três de mim?}
{18174}{}{Isso é tudo que sabe?}
{18175}{}{Se isso é tudo que você sabe, então vai ser uma luta facil.}
{18176}{}{Fraco...}
{18177}{}{Lento...}
{26000}{}{fugir! Fugir!}
{26001}{}{Retiro!}
{26002}{}{Reagrupar!}
{26003}{}{Voltando!}
{26004}{}{Retirada!}
{26005}{}{Vou sair daqui!}
{26020}{}{Mate este idiota!}
{26021}{}{É um homem morto...}
{26022}{}{Eu vou comer teu cu!}
{26023}{}{Esse é meu!}
{26024}{}{Voltei por você!}
{26025}{}{Suas orelhas serão um grande troféu!}
{26040}{}{Aproveite os últimos segundos de sua vida!}
{26041}{}{Sangue! Sangue! Sangue!}
{26042}{}{Seu coração é o meu!}
{26043}{}{Eu adoro fazer isso!}
{26044}{}{Suas armas serão meus troféus!}
{26045}{}{Morte e desmembramento. Minhas duas coisas favoritas!}
{26046}{}{Eu mesmo vou te matar!}
{26047}{}{Seus ossos vou sair pra fora!}
{26048}{}{Sangue e escuridão!}
{26049}{}{Vou roubar o seu cadáver!}
{26050}{}{Idiota Mascarado!}
{26100}{}{Khans! Cubram-me!}
{26101}{}{Retiro!}
{26102}{}{Reagrupar!}
{26103}{}{Voltando!}
{26104}{}{Retirada!}
{26105}{}{Recuar e reagrupar!}
{26120}{}{Que comece o desafio!}
{26121}{}{Vou te usar como treino!}
{26122}{}{Não haverá Misericórdia pra você!}
{26123}{}{Esse é meu!}
{26124}{}{Ataque os Khans!}
{26125}{}{Que comece a festa!}
{26126}{}{Que alguém mate este desperdício de ser humano!}
{26140}{}{Mate os Khans!}
{26141}{}{Os Khans são a elite dos que sobraram!}
{26142}{}{Sou supremo!}
{26143}{}{Os Khans governarão!}
{26144}{}{Os Khans são invencíveis!}
{26145}{}{Não Recuar! Recuar-se jamais!}
{26146}{}{Eu mesmo vou te matar!}
{26147}{}{Eu vou fazer um colar dos seus dentes!}
{26148}{}{Sangue e escuridão!}
{26149}{}{Os Khans são os mais fortes!}
{26160}{}{Boa tentativa, mas eu ainda estou aqui!}
{26161}{}{Nada pode me tocar!}
{26162}{}{Sou indestrutível!}
{26163}{}{Meu sangue é mais forte que o seu!}
{26164}{}{Talvez devêssemos parar por tempo para que você possa treinar tiros!}
{26165}{}{Você não é digno de lutar comigo!}
{26166}{}{Por que eu estou perdendo meu tempo com idiotas como você?}
{32000}{}{A minha cara! A minha cara!}
{32001}{}{Meu couro cabeludo!}
{32002}{}{oooh... meus ouvidos...}
{32010}{}{Ow, o meu braço!}
{32011}{}{Ow!}
{32012}{}{Você quebrou o meu braço!}
{32020}{}{Ow, o meu braço!}
{32021}{}{Wahhhh!}
{32022}{}{Meu Deus! Meu braço!}
{32030}{}{OUCH!}
{32031}{}{Eu acho que vou desmaiar...}
{32032}{}{Hey! Meu estômago!}
{32033}{}{Uuuuf!}
{32034}{}{Isso dói!}
{32035}{}{Eu acho que você bateu no meu fígado!}
{32036}{}{Ohhh, dor!}
{32060}{}{Ow, minha perna!}
{32061}{}{Meu joelho!}
{32062}{}{Direto na artéria!}
{32070}{}{Ai, minha perna.}
{32071}{}{::hop... hop::}
{32072}{}{Aaaarrrrggghhh!}
{32080}{}{Eu não posso ver! Idiota!}
{32081}{}{Minha cara! Meus olhos! Arrrrgh!}
{32082}{}{Onde você está? Ajuda!}
{32090}{}{Ooooooooo, minha virilha! Ooooooo ...}
{32091}{}{Eu. Eu. Ai ...}
{32092}{}{::choradeira::}
{32093}{}{::vômita::}
{32094}{}{Eu... não posso ... respirar ...}
{32095}{}{A dor, a dor ...}
{32100}{}{Seu kung fu é melhor do que o meu!}
{32101}{}{Você é realmente poderoso. Tchau.}
{32102}{}{Aieee! Espíritos malvados!}
{32103}{}{Oh Não...}
{32104}{}{Falhei.}
{32105}{}{Tem sido mau.}
{32120}{}{Me obriga a te atacar.}
{32121}{}{Acho melhor você correr.}
{32122}{}{Só os covardes usam armas.}
{32123}{}{Fuja enquanto pode.}
{32124}{}{Prepare-se, malfeitor.}
{32125}{}{Corra e não vou te machucar.}
{32126}{}{Se você insistir em lutar ...}
{32128}{}{Você acha que pode me derrotar?}
{32140}{}{Haiiiiiiii-YA!}
{32141}{}{Chop-socky!}
{32142}{}{rooOOOooo!}
{32143}{}{Hai!}
{32144}{}{Huh!}
{32145}{}{Hai oooOOo!}
{32146}{}{Hai - ah!}
{32147}{}{Mostre-me do que é capaz!}
{32148}{}{Carne da Mongólia!}
{32149}{}{Um chute em seus olhos!}
{32160}{}{Só os covardes usam armas.}
{32161}{}{Tem medo de enfrentar um lutador de verdade?}
{32162}{}{Seu kung fu não é bom aqui.}
{32163}{}{Render!}
{32164}{}{Você chama isso de luta?}
{32165}{}{Você se move como uma lesma.}
{32200}{}{Estou procurando uma mulher de olhos verdes...tchau!}
{32201}{}{Sim senhor ... o cheque está no correio.}
{32202}{}{Eu acho que eu tenho um compromisso ...}
{32203}{}{Okay, você ganhou!}
{32204}{}{Eu desisto!}
{32205}{}{O seu kung-fu é mais forte do que o meu!}
{32220}{}{Porra! Mate-os para mim!}
{32221}{}{Seus poderes são fracos!}
{32222}{}{Seu kung fu não pode me machucar!}
{32223}{}{Sou invencível!}
{32224}{}{Corra, de pressa!}
{32225}{}{O trovão rola na sua direção!}
{32226}{}{Flutua como uma borboleta!}
{32228}{}{Pica como uma abelha!}
{32240}{}{Quem é Jack Burton?}
{32241}{}{É demais se eu pedir para que você morra!}
{32242}{}{Você já pagou suas dívidas, Jack?}
{32243}{}{Há um problema com o seu rosto.}
{32244}{}{O cheque está no CORREIO!}
{32245}{}{O inferno te espera!}
{32246}{}{Cumprimente seus antepassados por mim!}
{32247}{}{Sou imortal!}
{32248}{}{Chop-suey!}
{32249}{}{Hai-YA!}
{32260}{}{Feelin tipo “invencível”!}
{32261}{}{Mostre-me seu melhor tiro.}
{32262}{}{Posso agüentar.}
{32263}{}{Você realmente não sabe lutar, não é?}
{32264}{}{Você chama isso de luta?}
{32265}{}{::bocejo::}
{32300}{}{Eu tenho uma esposa e filhos!}
{32301}{}{Não... é meu aniversário!}
{32302}{}{Ai... meu estômago ...}
{32303}{}{De volta ao hospital!}
{32304}{}{Devo... proteger...meu braço...}
{32305}{}{Oh, meu fígado dolorido.}
{32320}{}{Não me obrigue a usar a faca.}
{32321}{}{Vou te bater de uma forma que não imagina...}
{32322}{}{Você come pequenos pedaços de merda no café da manhã?}
{32323}{}{Eu vou chutar o seu cu.}
{32324}{}{Vou te fazer em pedaços!}
{32325}{}{Isso é tudo o que tenho a dizer.}
{32340}{}{Boom!}
{32341}{}{Vai tomar no cu!}
{32342}{}{YEAH!}
{32343}{}{Yeah, baby, yeah!}
{32344}{}{Você quer um pouco disso?}
{32345}{}{Não se mova!}
{32346}{}{Impressionante, bay-by!}
{32347}{}{Oh, é seu rosto?}
{32348}{}{Sua cara é assim tão feia?}
{32360}{}{Errou meu estômago! Ha ha!}
{32361}{}{Você não presta!}
{32362}{}{Ha ha! Aqui quem manda sou eu!}
{32363}{}{Me dê um beijo, doçura.}
{32364}{}{Hora de dormir, baby.}
{32365}{}{Vou te fazer em pedaços!}
{32400}{}{Na cara! Não bata na cara!}
{32401}{}{Acabou com meu penteado, Otário!}
{32402}{}{Idiota! Vou acabar com você por isso!}
{32403}{}{Preciso de uma arma maior!}
{32404}{}{Waaaaaaaaaaa!!!}
{32405}{}{AAGGH! Você me deu um tiro na bunda!!}
{32420}{}{Eu vou fazer você deseja nunca ter saído de casa!}
{32421}{}{Diga... você tem uma cara de cu!}
{32422}{}{Vamos ver o que você tem, panáca.}
{32423}{}{Incline-se e agarrar seus tornozelos, pimpolho!}
{32424}{}{Por Shane!}
{32425}{}{Vou tentar fazer isso o mais doloroso possível.}
{32426}{}{Se importa se eu quebrar seus joelhos em primeiro?}
{32428}{}{Vamos lá, menina. Mostre-me do que você é capaz.}
{32440}{}{Espero que não precise teste braço...}
{32441}{}{Maldição, Isso vai doer, hein?}
{32442}{}{Uf-da!}
{32443}{}{Eu amo o cheiro de sangue da manhã ...}
{32444}{}{Rapaz, você sangra muito hein?}
{32445}{}{::::Puts!:::::}
{32446}{}{Você quebrou a cara, homem!!}
{32447}{}{Um enema quente a ponto de chegar!!}
{32448}{}{Toma isso!!}
{32460}{}{Você atira pior do que a minha mãe!}
{32461}{}{Maldição, Você não presta!}
{32462}{}{De volta a Los Angeles, merda!}
{32463}{}{Quer que eu fique parado para você?}
{32464}{}{:::puts:::}
{32465}{}{Oh, isso foi bom...}
{32500}{}{Santo deus, com eu queria lambê-los!}
{32501}{}{La la la ... Ajuda!}
{32502}{}{Ha ha Ai!}
{32503}{}{AT! AT! At at at at at!}
{32504}{}{Ay Caramba!}
{32505}{}{Socorro!}
{32520}{}{Você não queria nada disso!}
{32521}{}{Come Toma isto!}
{32522}{}{Você quer um pouco disto? Huh? Huh?}
{32523}{}{Vamos lá! Eu vou te estuprar!}
{32524}{}{Você está tão morto.}
{32525}{}{Vai conhecer um mundo novo de dor.}
{32526}{}{Tenho algo pra você... Oh, sim.}
{32540}{}{Você quer lutar por essa merda.}
{32541}{}{::canta::}
{32542}{}{Iii... vou sempre amar VOCEEEEÊ}
{32543}{}{Nos não podemos ficar juntos?}
{32544}{}{Você está tão morto.}
{32545}{}{Se curve por um segundo ...}
{32546}{}{Tenho um presente para você.}
{32547}{}{Você quer um pedaço de mim?}
{32548}{}{Ele atira ... pra matar!}
{32549}{}{Que tal um pouco de amor?}
{32560}{}{É isso mesmo!}
{32561}{}{É isso mesmo!}
{32562}{}{Ha ha ha!}
{32563}{}{Alguma vez fez algo bom?}
{32564}{}{Não pode tocar nisto!}
{32565}{}{Ai! Ha ha ... apenas brincando.}
{32600}{}{Aiee!}
{32601}{}{Próxima classificação!}
{32602}{}{Voltando!}
{32603}{}{fugir! Fugir!}
{32604}{}{Fuja!}
{32620}{}{Prepare-se para ser desonrado.}
{32621}{}{As colunas do céu tremem ...}
{32622}{}{... flechas envenenadas caem do céu...}
{32623}{}{Aí vem o expresso Porkchop.}
{32624}{}{Nós te avisamos...}
{32625}{}{Um ex-gaijin, chegando!}
{32626}{}{Goodbye, mais um morto.}
{32640}{}{Tenho algo para você...}
{32641}{}{... Tenho algo para sua mãe...}
{32642}{}{...Tenho algo para seu Pai...}
{32643}{}{...Tenho algo para sua irmã....}
{32644}{}{... e algo para seus ancestrais!}
{32645}{}{Cai fora!}
{32646}{}{Morra!}
{32647}{}{Goodbye!}
{32648}{}{Deixe-me desonrar você!}
{32649}{}{Sua presença me ofende.}
{32660}{}{É tudo nos reflexos.}
{32661}{}{Gaijin tolo!}
{32662}{}{:: suspira :: Quando é que vamos lutar com alguém BOM?}
{32663}{}{É isso nunca vai acabar?}
{32664}{}{Quando é que você vai começar a me bater?}
{32665}{}{Isso está ficando manjado...}
{32700}{}{A minha cara! A minha cara!}
{32701}{}{Pai do céu! Ajude-me!}
{32702}{}{Ouch! Preciso de um pouco de gelo para a minha cabeça.}
{32710}{}{Ow, o meu braço!}
{32711}{}{Ow!}
{32712}{}{Você quebrou o meu braço!}
{32720}{}{Ow, o meu braço!}
{32721}{}{Wahhhh!}
{32722}{}{Por Elron! Meu braço!}
{32730}{}{Ai! Isso realmente dói!}
{32731}{}{Eu acho que vou desmaiar}
{32732}{}{Ouch!}
{32733}{}{Oh Deus! Ajude-me!}
{32734}{}{Isso dói!}
{32735}{}{Me deixe em paz!}
{32736}{}{Ohhh, dor!}
{32760}{}{Ow, minha perna!}
{32761}{}{Meu joelho!}
{32762}{}{Ow!}
{32770}{}{Ai, meu braço!}
{32771}{}{Meu joelho!}
{32772}{}{Aaaarrrrggghhh!}
{32780}{}{Ai! Meus olhos!}
{32781}{}{Minha cara! Meus olhos! Arrrrgh!}
{32782}{}{Meus olhos!}
{32790}{}{Ooooooooo, minha virilha! Ooooooo ...}
{32791}{}{Oww ... Queima!}
{32792}{}{Urp!}
{32793}{}{::suspiro::}
{32794}{}{Eu... não posso ... respirar ...}
{32795}{}{Menos mal...que ja... sou estéril ...}
{32800}{}{Deus! Ajude-nos!}
{32801}{}{Meus analgésicos!}
{32802}{}{Eu quero viver para ver Quetzel!}
{32803}{}{Eeek!}
{32804}{}{Salve nossas celebridades!}
{32805}{}{OZ-9! Ajude-nos!}
{32820}{}{Eu estou indo para "ajustar" mas não esta fácil ...}
{32821}{}{Fico feliz quando fico atrás de um dos seus tipos...}
{32822}{}{Pena que você não vai ver o futuro.}
{32823}{}{Nunca desafie o Pai das estrelas.}
{32824}{}{Elron te executarei!}
{32825}{}{Somos a vingança de o Pai estrelar!}
{32826}{}{Morte para os não iniciados!}
{32828}{}{Pensa que isso é um zeta-scan diferente.}
{32840}{}{Você tem energia suja!}
{32841}{}{Pelo Padre estrelar!}
{32842}{}{Por Elron!}
{32843}{}{Por Quetzel!}
{32844}{}{Por OZ-9!}
{32845}{}{Morra, impuro!}
{32846}{}{Não profane nosso santuário!}
{32847}{}{Isto é por OZ-9!}
{32860}{}{Sua energia está desalinhado.}
{32861}{}{Se você fosse um de nós, você teria me atingido.}
{32862}{}{Você tem energia impura.}
{32863}{}{Não bata em um verdadeiro crente!}
{32864}{}{Isso irá acabar com suas dores!}
{32865}{}{Impuro!}
{32900}{}{Eu sou uma estrela de cinema!}
{32901}{}{Abram caminho celebridade passando!}
{32902}{}{Isso não está no script!}
{32903}{}{Padre estrelar! Ajuda!}
{32904}{}{Espera... Sou famoso!}
{33000}{}{Oh Deus! Ajude-me!}
{33001}{}{Não! Eu não!}
{33002}{}{Por favor, mate outro!}
{33003}{}{Não me mate! Sou OZ-9!}
{33004}{}{Guardas! Me ajudem!}
{33005}{}{Não pode me matar! Sou muito importante!}
{33020}{}{Você poderia ter sido um de nós.}
{33021}{}{O estúpido sempre se voltam contra seus superiores.}
{33022}{}{Sua impureza brilha!}
{33023}{}{Se você tivesse feito o juramento ...}
{33024}{}{O Pai estrelar vai te derrubar.}
{33025}{}{Nunca vai ver o planeta Quetzel.}
{33026}{}{Traidor da evolução da humana.}
{33028}{}{Indigno e impuro.}
{33040}{}{Meu toque vai purificá-lo!}
{33041}{}{Vou te bater até que morra!}
{33042}{}{Em nome de Elron!}
{33043}{}{Pela glória do Pai Estrelar!}
{33044}{}{Sinta a ira de Elron!}
{33045}{}{Isto irá melhorar você!}
{33060}{}{O Pai estrelar me salva!}
{33061}{}{Elron me proteja!}
{33062}{}{Seus remédios estão contaminados!}
{33063}{}{Sua energia não é boa.}
{33064}{}{Você não sabe como se concentrar?}
{33100}{}{Oh Deus! Ajude-me!}
{33101}{}{Eu prefiro estar em Quetzel!}
{33102}{}{Eu não! Não me mate!}
{33103}{}{Eu sou apenas um protestante!}
{33104}{}{Não sou eu quem tomo as decisões!}
{33105}{}{Não sou a pessoa que procura!}
{33120}{}{Eu prefiro não ter que fazer isso ...}
{33121}{}{Tem certeza de que não prefere desistir?}
{33122}{}{Podemos resolver isso, não podemos?}
{33123}{}{Se OZ-9 diz que você é ruim, você deve ser ruim.}
{33124}{}{Pela ... glória de Elron!}
{33125}{}{Lutar é ruim para os anódinos ...}
{33126}{}{Eu não sou bom nessa coisa de ameaçador.}
{33128}{}{Minhas desculpas se eu estou a ponto de te machucar.}
{33140}{}{Look out!}
{33141}{}{::O que tiver na vista ataque::}
{33142}{}{Ai vem outro ataque...}
{33143}{}{Se você fugir, eu não teria que fazer isso.}
{33144}{}{Vá em frente! Caiam fora daqui!}
{33145}{}{Shoo! Shoo!}
{33146}{}{Parem de brigar!}
{33147}{}{Hoooooooowdy ho!}
{33148}{}{Você cheira a flores.}
{33149}{}{Nós podemos resolver isso!}
{33160}{}{Por que você está tentando me machucar?}
{33161}{}{O que foi que eu fiz para você?}
{33162}{}{Você sabe que não temos que lutar!}
{33163}{}{Eu não quero te machucar!}
{33164}{}{Eu não quero que você me machuque!}
{33165}{}{Podemos resolver isso como adultos?}
{33200}{}{Acho que você quebrou meu maxilar!}
{33201}{}{Minha bochecha!}
{33202}{}{Isso vai deixar uma puta de uma cicatriz.}
{33210}{}{Minha mão de escrever!}
{33211}{}{Meu cotovelo!}
{33212}{}{Hey! Cuidado com o que faz!!}
{33220}{}{Ahhh! Aiee! Ahh!}
{33221}{}{Wahhhh!}
{33222}{}{Ai! Minha unha!!}
{33230}{}{Eu acho que você acertou meu rim!}
{33231}{}{Meu plexo solar!}
{33232}{}{::arquejo::}
{33233}{}{Uuuuf!}
{33234}{}{Você não tem que fazer isso...}
{33235}{}{Okay, isso dói.}
{33236}{}{Ohhh... owwww}
{33260}{}{Minha tibia!}
{33261}{}{Meu joelho!}
{33262}{}{Ow!}
{33270}{}{Oooh, meu fêmur!}
{33271}{}{Meu joelho!}
{33272}{}{Isso vai me deixar feridas.}
{33280}{}{Eu acho que você arrancou minha retina!}
{33281}{}{Meu humor aquoso! Meu vítreo!}
{33282}{}{Estou cego! Estou cego!}
{33290}{}{Isso é ... isso é ... doloroso ...}
{33291}{}{mãe...}
{33292}{}{::choradeira::}
{33293}{}{Santa mãe de DEUS!}
{33294}{}{Hmmm. Ow. Hmmm.}
{33295}{}{Acho que vou entrar em choque agora.}
{36000}{}{Auch! Isso me bateu na cabeça!}
{36001}{}{Ai! Minha cabeça!!}
{36002}{}{Ufa! A cabeça de Kaga está pegando fogo!}
{36010}{}{Minha mão!}
{36011}{}{Ai! Ainda bem que eu sou destro}
{36012}{}{Ai!!}
{36020}{}{Ow, o meu braço!}
{36021}{}{Você quebrou o meu braço!}
{36022}{}{Você vai se arrepender disso!}
{36030}{}{(Grunhido!)}
{36031}{}{É apenas uma ferida superficial!}
{36032}{}{Grrr!}
{36033}{}{Você vai se arrepender disso!}
{36034}{}{Você deve parar enquanto esta ganhando!}
{36035}{}{Bom tiro. Minha vez.}
{36060}{}{Ow, minha perna!}
{36061}{}{Você vai pagar por isso!}
{36062}{}{Ah! Minha perna!}
{36070}{}{Minha perna!}
{36071}{}{Uhh! Esta mirando baixo, não é?}
{36072}{}{Não estava tentando acertar minha perna, está?!}
{36080}{}{Maldição sangue em meus olhos!}
{36081}{}{O meu olho! Você vai pagar por isso!}
{36082}{}{Safado!}
{36090}{}{Oooooo, acabou o tempo, tenho que pegar alguma coisa}
{36091}{}{Ooo! Kaga tem que aprender esse movimento...}
{36092}{}{Urg! Petey! Está bem ai em baixo?}
{36093}{}{Isso ... wheeeeze ... dói!}
{36094}{}{Urp!}
{36095}{}{suspiro!}
{36100}{}{Nós vamos nos encontrar novamente!}
{36101}{}{Eu voltarei...}
{36102}{}{Nunca fui espancado antes!}
{36103}{}{Vou me dedicar a caçá-lo!}
{36104}{}{Não vai ser o último a ouvir falar de mim!}
{36105}{}{Vai pagar por isso... mas tarde!}
{36120}{}{Eu deveria ter sido o Escolhido!}
{36121}{}{Arroyo vai se arrepender de ter me jogado aqui!}
{36122}{}{Eu terei minha vingança em VOCÊ!}
{36123}{}{Kaga irá mandá-lo para o outro lado da vida!}
{36124}{}{Outro Escolhido para matar!}
{36140}{}{Sua mãe não está aqui para ajudá-lo!}
{36141}{}{Vou aproveitar isto.!}
{36142}{}{Oooo, isso vai doer!}
{36143}{}{Vou levar sua cabeça de volta para Anciã!}
{36144}{}{Vou comer seu fígado!}
{36145}{}{Espero que você não morra tão rapidamente quanto os outros!}
{36146}{}{Outro Escolhido para matar!}
{36147}{}{Morra!}
{36148}{}{Grite para mim.}
{36160}{}{Não pode me bater!}
{36161}{}{Os espíritos estão me protegendo.}
{36162}{}{Espero que esse não seja o seu melhor tiro.}
{36163}{}{Bwahaha. Kaga nem sequer têm de pato!}
{36164}{}{Não pode matar aquilo que não se pode ferir!}
{36165}{}{Muito lento!}
{36200}{}{Nós vamos nos encontrar novamente!}
{36201}{}{Eu voltarei...}
{36202}{}{Você não pode matar o Grande Kaga!}
{36203}{}{Você está com sorte! Kaga tem negócios em outros lugares.}
{36204}{}{Você e Kaga se encontraram novamente.}
{36205}{}{Vai pagar por isso... mas tarde!}
{36220}{}{Depois que eu matar você, eu vou queimar Arroyo!}
{36221}{}{Vou ser temido por todos!}
{36222}{}{Kaga terá sua cabeça como troféu!}
{36223}{}{Renda-se e eu vou fazer que sua morte seja rápida!}
{36240}{}{Sinta a ira de Kaga!}
{36241}{}{Não adianta ficar gritando por Misericórdia ...}
{36242}{}{Vou aproveitar isto.!}
{36243}{}{Oooo, Kaga sentiu isso daqui.}
{36244}{}{Vou levar sua cabeça de volta para Anciã!}
{36245}{}{Vou tirar seu coração para fora com uma colher!}
{36246}{}{Espero que você não morra tão rapidamente quanto os outros!}
{36247}{}{Outro Escolhido para matar!}
{36248}{}{Morra!}
{36249}{}{Grite para mim.}
{36260}{}{Não pode me bater!}
{36261}{}{Os espíritos estão me protegendo.}
{36262}{}{Espero que esse não seja o seu melhor tiro.}
{36263}{}{Bwahaha. Kaga nem sequer têm de pato!}
{36264}{}{Não pode matar aquilo que não se pode ferir!}
{36265}{}{Muito lento!}
{36300}{}{Isso está virando um mau hábito.}
{36301}{}{Kaga precisa de mais treinamento.}
{36302}{}{Eu vou estar de volta. Yada yada yada eu vou te matar.}
{36303}{}{Você está com sorte! Kaga tem negócios em outros lugares.}
{36304}{}{Você e Kaga se encontraram novamente.}
{36305}{}{Vai pagar por isso... mas tarde!}
{36320}{}{Kaga e o Escolhido vão se encontrar novamente.}
{36321}{}{Vamos acabar com isso.}
{36322}{}{Você vai se arrepender de ter ouvido o nome de Kaga!}
{36323}{}{Minhas habilidades aumentaram desde o nosso último encontro.}
{36340}{}{Sinta a ira de Kaga!}
{36341}{}{Vou aproveitar isto.!}
{36342}{}{Oooo, Kaga sentiu isso daqui.}
{36343}{}{Vou levar a sua cabeça como troféu.}
{36344}{}{Vou tirar seu coração para fora com uma colher!}
{36345}{}{Espero que você não morra tão rápido quanto os outros.}
{36346}{}{Outro Escolhido para matar!}
{36347}{}{Morra!}
{36348}{}{Grite para mim.}
{36360}{}{Não pode me bater!}
{36361}{}{Os espíritos estão me protegendo.}
{36362}{}{Espero que esse não seja o seu melhor tiro.}
{36363}{}{Bwahaha. Kaga nem sequer têm de pato!}
{36364}{}{Não pode matar aquilo que não se pode ferir!}
{36365}{}{Muito lento!}
{36400}{}{Isso está virando um mau hábito.}
{36401}{}{Kaga precisa de mais treinamento.}
{36402}{}{Este não é o último que você vai ver de Kaga.}
{36403}{}{Você está com sorte! Kaga tem negócios em outros lugares.}
{36404}{}{Você e Kaga se encontraram novamente.}
{36405}{}{Vai pagar por isso... mas tarde!}
{36420}{}{O Escolhido nunca irá retornar para Arroyo!}
{36421}{}{Kaga vai esmagar você!}
{36422}{}{Kaga não teme ninguém!}
{36423}{}{Deixe que Kaga te ensine as novas habilidades que aprendeu!}
{36440}{}{Sinta a ira de Kaga!}
{36441}{}{Fique quiéto para que Kaga possa atirar melhor.}
{36442}{}{Vou aproveitar isto.!}
{36443}{}{Oooo, Kaga sentiu isso daqui.}
{36444}{}{Vou levar sua cabeça de volta para Anciã!}
{36445}{}{Vou tirar seu coração para fora com uma colher!}
{36446}{}{Espero que você não morra tão rapidamente quanto os outros!}
{36447}{}{Outro Escolhido para matar!}
{36448}{}{Morra!}
{36449}{}{Grite para mim.}
{36460}{}{Não pode me bater!}
{36461}{}{Os espíritos estão me protegendo.}
{36462}{}{Espero que esse não seja o seu melhor tiro.}
{36463}{}{Bwahaha. Kaga nem sequer têm de pato!}
{36464}{}{Não pode matar aquilo que não se pode ferir!}
{36465}{}{Muito lento!}
{36500}{}{}
{36501}{}{}
{36502}{}{}
{36503}{}{}
{36504}{}{}
{36505}{}{}
{36520}{}{Kaga está pronto para você agora.}
{36521}{}{Vocês não são páreo para Kaga.}
{36522}{}{Kaga vai te mandar para a próxima vida!}
{36523}{}{Kaga vai sentir sua falta.}
{36540}{}{Sinta a ira de Kaga!}
{36541}{}{Kaga será famoso por matar você!}
{36542}{}{Vou aproveitar isto.}
{36543}{}{Oooo, Kaga sentiu isso daqui.}
{36544}{}{Vou levar sua cabeça de volta para Anciã!}
{36545}{}{O Escolhido morrerá aqui!}
{36546}{}{Kaga tem que matá-lo agora!}
{36547}{}{Morra!}
{36548}{}{Grite para mim.}
{36560}{}{Não pode me bater!}
{36561}{}{Os espíritos estão me protegendo.}
{36562}{}{Espero que esse não seja o seu melhor tiro.}
{36563}{}{Bwahaha. Kaga nem sequer têm de pato!}
{36564}{}{Não pode matar aquilo que não se pode ferir!}
{36565}{}{Muito lento!}
{36600}{}{Ahhhgh! Minha cara!}
{36601}{}{Minha cara! Vai sofrer por isso!}
{36602}{}{Ahhhgh! Eu fazer você em pedaços!}
{36610}{}{Ahhhgh!}
{36611}{}{Ai! Quase machuquei o Escolhido!}
{36612}{}{Ahhhgh! Vou quebrar seu pescoço por isso!}
{36620}{}{Ahhhgh!}
{36621}{}{Ai! Quase machuquei o Escolhido!}
{36622}{}{Ahhhgh! Vou quebrar seu pescoço por isso!}
{36630}{}{Oof!}
{36631}{}{Grrr!}
{36632}{}{Vou matá-lo por isso!}
{36633}{}{Não vai me machucar quando estiver morto!}
{36634}{}{Eu rio de seu fraco Ataque!}
{36635}{}{Oh!}
{36636}{}{Vou acabar com você!}
{36637}{}{Grrr! Estou me irritando!}
{36638}{}{Agh!}
{36639}{}{Te devolverei a mesma dor!}
{36640}{}{Oof!}
{36641}{}{Ouch!}
{36642}{}{Hmm, você pode ser um problema.}
{36643}{}{Grrr! Estou ansioso por sua Morte!}
{36644}{}{Pode me machucar, mas jamais vai vencer!}
{36645}{}{Ai! Isso não foi uma boa idéia.}
{36660}{}{Ahhhgh! Minha perna!}
{36661}{}{Você chama isso de dor? Eu brinco!}
{36662}{}{Ahhhgh! Vou quebrar seu pescoço por isso!}
{36670}{}{Ahhhgh! Minha perna!}
{36671}{}{Você chama isso de dor? Eu brinco!}
{36672}{}{Ahhhgh! Vou quebrar seu pescoço por isso!}
{36680}{}{Ahhhgh! Humano miserável! Estou cego!}
{36681}{}{Ahhhgh! Dor! O que você fez!}
{36682}{}{Ahhhgh! Eu vou te torturar por muitos dias!}
{36690}{}{Essa é a fraqueza humana!}
{36691}{}{Você chama isso de dor? Eu brinco!}
{36692}{}{Você é estúpido, humano!}
{36693}{}{Por que esta me atacando?}
{36694}{}{Você vai sofrer por muitas horas!}
{36695}{}{Por que esta me atacando?}
{36700}{}{Corre!}
{36701}{}{Você não vai me matar!}
{36702}{}{Eu voltarei!}
{36703}{}{Meus amigos vão te pegar por mim!}
{36704}{}{Você vai pagar por isso - depois!}
{36705}{}{Somos os Escolhidos! Vai morrer daqui a pouco!}
{36720}{}{Sua morte esta próxima!}
{36721}{}{Aqueles que atrapalham os Escolhidos, não voltaram a atrapalhar mais ninguém de novo!}
{36722}{}{Armas humanas não podem me prejudicar!}
{36723}{}{Você vai sofrer, vai sofrer muito!}
{36724}{}{Quando eu luto, eu mato!}
{36725}{}{Quem é suficientemente burro para nos irritar?}
{36726}{}{Eu vejo inimigos para destruir!}
{36727}{}{Você vai sofrer, vai sofrer muito!}
{36740}{}{Agora é a hora que você vai morrer!}
{36741}{}{Ninguém vai te salvar agora!}
{36742}{}{Deixe-me ver a sua dor!}
{36743}{}{Agora você vai morrer com muito sofrimento!}
{36744}{}{Morra seu tolo humano!}
{36745}{}{Agora você vai morrer gritando!}
{36746}{}{Sofra!}
{36747}{}{Vou te trucidar!}
{36748}{}{Não pode lutar contra os Escolhidos!}
{36749}{}{Sofra, humano!}
{36760}{}{Por que você luta assim?}
{36761}{}{Isso é o melhor que os humanos podem fazer!}
{36762}{}{Você não tem o poder!}
{36763}{}{Você me faz rir muito!}
{36764}{}{Isso foi um ataque?}
{36765}{}{Nos somos os Escolhidos!}
{36800}{}{Agora sei porquê te procuram!}
{36801}{}{Eu vou estar de volta.}
{36802}{}{Esta não vai ser a última vez que você vai me ver.}
{36803}{}{Supostamente são os mocinhos que ganham?}
{36804}{}{Por que não vamos falar sobre isso?}
{36805}{}{Mamãe estava certa. Uma pessoa pode morrer se fizer isso.}
{36806}{}{Acho que vou me concentrar em criar porcos.}
{36807}{}{Não vale a pena morrer por esta recompensa!}
{36808}{}{Por favor me deixe ir!}
{36809}{}{Nos não podemos ficar juntos?}
{36810}{}{Não me mate, eu tenho familia!}
{36811}{}{Não posso gastar a recompensa se estiver morto!}
{36812}{}{Você é um assassino cruel!}
{36813}{}{Maldição! Eu já passei a minha parte do dinheiro da recompensa.}
{36814}{}{Não pode acabar assim.}
{36815}{}{Alguém me ajude!}
{36816}{}{Eu deveria estar caçando você!}
{36817}{}{Eu tenho dinheiro. Deixe-me ir e ele é seu.}
{36818}{}{O inferno acaba de ficar congelado.}
{36819}{}{Maldição você é bom!}
{36820}{}{Você sabe quanto tempo eu estive procurando por você?}
{36821}{}{É um homem morto.}
{36822}{}{Renda-se e vou te matar rapidamente.}
{36823}{}{Te procurei por dias.}
{36824}{}{A recompensa me cairá muito bem.}
{36825}{}{Eu vou arancar o seu coração!}
{36826}{}{O preço por sua cabeça não esta mal.}
{36827}{}{Vou adorar matar um bastardo como você!}
{36828}{}{Você achou que ia fugir depois da matança dos inocentes?}
{36829}{}{Escória como você merece morrer.}
{36830}{}{Prepare para morrer!}
{36831}{}{Vou te mandar diretamente para o inferno!}
{36832}{}{Tem uma boa recompensa por sua cabeça.}
{36833}{}{Não torne isso pessoal, mas vou te matar agora.}
{36834}{}{Outro dia, outro assassino.}
{36835}{}{Vai ter que pagar por seus crimes.}
{36836}{}{Ouvi dizer que você gosta de matar pessoas inocentes.}
{36837}{}{Vejamos o quanto você é bom.}
{36838}{}{Uma vida por outra. É assim que funciona as coisas aqui.}
{36839}{}{Sabia que vale mais morto que vivo?}
{36840}{}{Matar não é tão fácil quando o seu adversário atira de volta.}
{36841}{}{Tente isso com outros dos seu tamanho.}
{36842}{}{Eu só preciso de sua cabeça, pode ficar com o resto.}
{36843}{}{Não é tão divertido quando é você que vai morrer né?}
{36844}{}{A recompensa é tão boa quanto eu.}
{36845}{}{Você não é tão duro.}
{36846}{}{Isso vai doer mais em você do que em mim.}
{36847}{}{Eu amo meu trabalho.}
{36848}{}{Eu acho que isso foi coisa do destino.}
{36849}{}{Eu quero ver o que a dentro de você.}
{36850}{}{Sua mamãezinha não esta aqui para te salvar.}
{36851}{}{Aqui esta um presente das pessoas que você assassinou.}
{36852}{}{Você se sente com sorte?}
{36853}{}{Vou te capturar!}
{36854}{}{Morra!}
{36855}{}{Sem misericórdia!}
{36856}{}{É melhor começar a rezar.}
{36857}{}{Me desculpe, mas eu tenho que fazer isso.}
{36858}{}{Prepare para morrer!}
{36859}{}{Espero que tenha feito seu testamento.}
{36860}{}{Whoa! Tenha cuidado ou vai acabar machucando alguém.}
{36861}{}{Hey hey! Quase me bateu!}
{36862}{}{Ajudaria se eu pintar um alvo em mim mesmo?}
{36863}{}{Não passou nem perto.}
{36864}{}{Me desculpe, mas você estava apontando para mim?}
{36865}{}{Voce me acertou com essa pedra nem estava armado.}
{36866}{}{Espero que isso não seja o seu melhor tiro.}
{36867}{}{Isso vai ser mais facil do que eu pensava.}
{36868}{}{Melhor você largar essa coisa antes que se machuque.}
{36869}{}{Ha! Você errou!}
{36870}{}{Perto, mas não perto o suficiente.}
{36871}{}{Da próxima vez tente apontar melhor.}
{36872}{}{Minha mãe faz melhor que você.}
{36873}{}{Suas mãos devem estar tremendo muito para você errar assim.}
{36874}{}{Isso sim é uma merda de tiro.}
{36875}{}{Eu nem sequer tento esquivar disso.}
{36876}{}{Parece que precisa praticar mais.}
{36877}{}{Isso foi um erro fatal.}
{36878}{}{Ou eu tenho sorte ou você é um desastre.}
{36879}{}{O lugar mais seguro pra ficar é bem na sua frente.}
{40000}{}{Espíritos querer sair do crânio, ah cara, crânio dói!}
{40001}{}{Escuridão chegar cedo agora.}
{40002}{}{Grande cicatriz na minha cara agora.}
{40003}{}{Essa quase quebrar Vovô-osso}
{40004}{}{Rá, Vovô-osso bloquear o impacto!}
{40005}{}{Sulik não precisar de dentes mesmo.}
{40006}{}{Sulik ainda ter uma orelha pra ouvir sofrimento!}
{40007}{}{Vovô-osso cair, mim precisa achar vovô!}
{40008}{}{Você poder ouvir o som dos sinos do espírito tocando?}
{40009}{}{Você ver brilho das estrelas também?}
{40010}{}{Meu osso ser tão branco.}
{40011}{}{Ainda poder usar a arma.}
{40012}{}{Um braço ser extra pro homem.}
{40013}{}{Arrrg.}
{40014}{}{Isso não doeu... muito.}
{40015}{}{Sulik achar que você não quer machucar ele.}
{40016}{}{Sulik ataca agora.}
{40017}{}{Agora nós ver como você e nós gosta disso.}
{40018}{}{Sulik nem precisar de todos os dedos mesmo.}
{40019}{}{Grande ser a cicratriz no meu braço.}
{40020}{}{Agora nós tomar seu braço também.}
{40021}{}{Pequenino irmão-rato estar me machucando forte.}
{40022}{}{Sulik pensar, ser época de mosquito agora?}
{40023}{}{Não sentimos dor... ainda.}
{40024}{}{Oh, oh. Sulik não sentir os dedos.}
{40025}{}{Vovô-osso dizer que nós precisa ser forte.}
{40026}{}{Vá pra casa e não acertar nós no braço de novo!}
{40027}{}{Seu coração não estar na luta!}
{40028}{}{You hurt de arm dat we roll with.}
{40029}{}{Nós só precisar de um braço pra acabar com você.}
{40030}{}{Oof!}
{40031}{}{Respirar estar mais difícil agora.}
{40032}{}{Nós sentir calor e estar com sono agora.}
{40033}{}{Nós dividir muito sangue agora.}
{40034}{}{Vovô-osso mostra o caminho pra nós!}
{40035}{}{Nós e eu não morrer tão fácil.}
{40036}{}{Nós não sentir muita dor nessa.}
{40037}{}{Espíritos fazer nós forte.}
{40038}{}{Nós não machucar o coração desse jeito.}
{40039}{}{Sulik ter muito sangue mesmo...}
{40040}{}{Nós achar que você não estar em paz com nós.}
{40041}{}{O dia parece estar acabado.}
{40042}{}{Difícil de respirar se tomarmos o golpe do dragão.}
{40043}{}{Nós achar que isso não ser tão bom.}
{40044}{}{Vovô-osso diz que isso ser o que parece.}
{40045}{}{O irmão-lagarto que nós comer antes quer sair agora.}
{40046}{}{Nós gostar do lado de dentro do jeito que ele ser, cara!}
{40047}{}{Nós nunca acostuma com isso.}
{40048}{}{Vovô-osso diz que os espíritos não querer nós ainda.}
{40049}{}{Você fazer coisas má com nós.}
{40050}{}{Nós e eu estar sofrendo coisas más.}
{40051}{}{Nós não querer que o vermelho, vermelho, vinho sai pra fora.}
{40052}{}{Se você nos machucar, nós machucaremos de volta.}
{40053}{}{Aaaaaiiiiii!}
{40054}{}{Shing-ding-ding!}
{40055}{}{O espírito-da-sombra estar no nosso ombro.}
{40056}{}{O céu estar tão claro agora.}
{40057}{}{Vovô-osso não deixar nós morrer.}
{40058}{}{Nós não sentir muito bem.}
{40059}{}{Nós e eu estar com buraco bem no meio do corpo.}
{40060}{}{Nós não vai fazer a dança do espírito agora.}
{40061}{}{Ah, cara! Você tirar o dedão fora.}
{40062}{}{Nossos pés estão queimando agora.}
{40063}{}{Nós chuta pedras, machucar mais que você.}
{40064}{}{Nós só precisa de uma perna pra matar você, cara.}
{40065}{}{Nós não precisa trabalhar agora.}
{40066}{}{Nós percebe como você gostar de ver nós mancar.}
{40067}{}{Ai, essa doer muito.}
{40068}{}{Aaaaaaaaaaiiiii!}
{40069}{}{Nós precisa de um pouco de erva agora.}
{40070}{}{Nós não vai conseguir mais dançar, cara.}
{40071}{}{Onde estar erva quando nós precisa dela?}
{40072}{}{Você me machucar bem nessa.}
{40073}{}{Osso da perna ser branco como vovô-osso.}
{40074}{}{A perna machucar nós agora.}
{40075}{}{Isso não ser legal com minha perna.}
{40076}{}{Vovô-osso mandar sofrimento pra sua perna agora.}
{40077}{}{Nós não estar com pressa mesmo.}
{40078}{}{Nós quer pular, cara.}
{40079}{}{Você quer deixar nossa perna legal?}
{40080}{}{Estar escuro agora.}
{40081}{}{Nós ainda pode ouvir você.}
{40082}{}{Vovô-osso ainda ver você.}
{40083}{}{Você tirar osso, Sulik tirar vida.}
{40084}{}{Você furar nosso olho. Isso machucar nós.}
{40085}{}{Rá, você ainda deixar um olho.}
{40086}{}{Nós ainda pode ver você, na nossa mente.}
{40087}{}{Nós estar mais forte que você pode imaginar agora, cara.}
{40088}{}{Nós enxergar claro pela primeira vez agora.}
{40089}{}{Vovô-osso faz o olhar pra nós.}
{40090}{}{Unnh!.}
{40091}{}{Nós viver na cabana das mulher agora.}
{40092}{}{Aaaaaaaiiiiiiiii!}
{40093}{}{Nós não precisar de mais criança mesmo.}
{40094}{}{Você não deixar nossas mulher feliz com isso.}
{40095}{}{Nós acha que você acertou nós porque o seu ser pequeno.}
{40096}{}{Você mirar no nosso alvo grande, cara.}
{40097}{}{Vovô-osso diz pra nós cortar você e fazer sanduíche.}
{40098}{}{Nós precisava de uma circuncisão mesmo.}
{40099}{}{Nós e mim precisa de um poco mais de erva, cara.}
{40100}{}{Sulik volta com arma maior.}
{40101}{}{Mágica do Sulik ser fraca.}
{40102}{}{Mágica má muito forte.}
{40103}{}{Antigos diz pro Sulik ir embora.}
{40104}{}{Sulik tem assunto pra resolver em outro lugar.}
{40105}{}{Sulik tem que ir agora.}
{40106}{}{Sulik precisa sangrar lagarto agora.}
{40107}{}{Sulik confunde inimigo correndo agora.}
{40108}{}{Sulik vai buscar ajuda.}
{40109}{}{Fuja!}
{40110}{}{Sulik acha que a luta não vale a pena.}
{40111}{}{Sulik tem mau pressentimento.}
{40112}{}{Sulik volta mais tarde.}
{40113}{}{Sulik precisa de desncanso.}
{40114}{}{Sulik vigia retaguarda.}
{40115}{}{Sulik ataca por trás.}
{40116}{}{Sulik não ter medo de homens, mas esses são demônios malignos!}
{40117}{}{Sulik não vai lutar contra demônios-que-anda-igual-homem.}
{40118}{}{Sulik não estar com garra-de-gecko da sorte, precisar achar.}
{40119}{}{Sulik esqueceu um coisa, volta daqui a poco.}
{40120}{}{Rá, cara, poder sentir o ritmo?}
{40121}{}{Nós ter o poder agora!}
{40122}{}{Nós e mim ter mágica forte agora.}
{40123}{}{Vovô-osso sentir seu medo.}
{40124}{}{Nós pronto pra comer seu coração.}
{40125}{}{Nós sentir seu medo, cara.}
{40126}{}{Sulik cantar música de guerra.}
{40127}{}{Espíritos olhar por nós agora.}
{40128}{}{Nós ver você caindo.}
{40129}{}{Você ir pro outro mundo, cara.}
{40130}{}{Ossos-antigo comer sua alma em breve.}
{40131}{}{We be havin' de seven-demon bags!}
{40132}{}{Cai dentro, cara.}
{40133}{}{Nós massacrar você como gelatina agora.}
{40134}{}{Nós quebrar você.}
{40135}{}{Nós trazer a dor pra você.}
{40136}{}{A dor ir até você agora, cara.}
{40137}{}{Nós espantar você agora, cara.}
{40138}{}{Melhor você correr.}
{40139}{}{Nós prontos pra tirar algumas cabeçar agora, cara.}
{40140}{}{Nós vai massacrar você.}
{40141}{}{Vovô diz que nós deve matar agora!}
{40142}{}{Vovô amar som de crânio quebrando, cara.}
{40143}{}{Vovô-osso me ajudar agora!}
{40144}{}{Espíritos me ajudar agora!}
{40145}{}{Você e mim ver sangue voar agora.}
{40146}{}{Nós fazer amigo pra vovô-osso dos seus ossos!}
{40147}{}{Vovô-osso diz que nós deve começar a matança.}
{40148}{}{Nós começar a fazer a dança-da-dor.}
{40149}{}{Nós começar a dança má na cabeça do inimigo agora, cara.}
{40150}{}{Nós deixar o ódio se divertir agora.}
{40151}{}{Vovô tentar imaginar que cor ter sangue-mau.}
{40152}{}{Iiiiiiáaaaa!}
{40153}{}{Nós lavar lança no seu sangue.}
{40154}{}{Nós querer carne fresca, que bom você estar aqui.}
{40155}{}{Você quer entrar na próxima dança com vovô e nós?}
{40156}{}{Nós aqui pra dançar.}
{40157}{}{Nós pronto pra ferir.}
{40158}{}{Nós provar seu sangue agora.}
{40159}{}{Vovô osso diz matar você e depois matar de novo.}
{40160}{}{Nós ter mágia mais forte agora.}
{40161}{}{Nós salvo de homem mau aqui.}
{40162}{}{Sulik ter magia forte.}
{40163}{}{Nós ter magia mais forte.}
{40164}{}{Você não machucar nós.}
{40165}{}{Vovô-osso fazer você errar.}
{40166}{}{Você bater como garotinha.}
{40167}{}{Você atacar nós ou espíritos perto de nós?}
{40168}{}{Você mirar em nós? Sério?}
{40169}{}{Você precisar de mais erva sagrada, cara.}
{40170}{}{Nós feliz por você errar.}
{40171}{}{Você confuso do que estar fazendo?}
{40172}{}{Você precisar praticar.}
{40173}{}{Estamos nos perguntando, o que foi isso?}
{40174}{}{Você fazer nós rir.}
{40175}{}{Nós achar que você deve voltar a caçar rato até aprender mais.}
{40176}{}{Vovô-osso não saber por que maus ser tão esúpidos.}
{40178}{}{Estamos nos perguntando se você quer começar de novo.}
{40179}{}{Nós achar que você mais estúpido que parece, mas vovô-osso achar que isso não ser possível.}
{40800}{}{*Nffff*}
{40801}{}{*Hrkkk*...Tenho...uma ferida...na cabeça...}
{40802}{}{*Nfff* Quase...arrancou...*nfff*...minha cabeça...}
{40803}{}{Minha cabeça...dói... seu imbécil...}
{40804}{}{Quase acertou minha cabeça... tudo esta rodando...}
{40805}{}{Não é possível ... tudo esta ficando escuro ... tenho que ficar consciente ...}
{40806}{}{Outro tiro como esse na cabeça e eu estou perdido.}
{40807}{}{Graças a Deus por essa placa de metal na Minha Cabeça, ou eu estaria morto ...}
{40810}{}{Maldição! Fui esfaqueado no braço em 2203!}
{40811}{}{* Hrkkkk * braço esquerdo ... dói pra caralho...}
{40812}{}{Braço esquerdo ... inútil ...}
{40813}{}{Acho que meu braço quebrou...}
{40814}{}{Não consigo... sentir meu braço esquerdo...}
{40815}{}{* Nfff * ... boa tentativa ... meu braço ... ja recebeu coisas piores ...}
{40816}{}{* Nfff * ... só meu braço ... é só o meu braço ...}
{40817}{}{* Nfff * ... outra ... Maldição de braço machucado...}
{40818}{}{Desloquei o meu maldito braço...}
{40820}{}{Maldito seja! Não levo um tiro nesse braço desde 2201!}
{40821}{}{*Hrkkkk*... o braço direito é... inútil...}
{40822}{}{* Nfff * ... boa tentativa ... meu braço ... ja recebeu coisas piores ...}
{40823}{}{Acho que quebrei meu braço ...}
{40824}{}{Não consigo... sentir meu braço direito...}
{40825}{}{* Nfff * ... só meu braço ... é só o meu braço ...}
{40826}{}{Vou ... precisar... de mais ... proteção nos braços ...}
{40827}{}{* Nfff * ... outra ... Maldição de braço machucado...}
{40828}{}{Desloquei o meu maldito braço...}
{40830}{}{*Hrrrk*}
{40831}{}{*Hrkkk*...quase arrancou meu braço...}
{40832}{}{Parece que isso quebrou varias costelas...}
{40833}{}{*Nffff*...Tenho que ficar consciente ... coração batendo...}
{40834}{}{Não é possível ... tudo esta ficando escuro ... tenho que ficar consciente ...}
{40835}{}{Inferno, uma ferida no peito ...}
{40836}{}{O impacto abriu um buraco bem no meu peito...}
{40837}{}{Vou precisar de alguns curativos extras no meu peito ...}
{40838}{}{*Unffff*...esse golpe... me deixou sem air...}
{40839}{}{* Hrkkk * ... caramba ... machucado...peito ... Maldição ... O coração esta ficando sem força...}
{40840}{}{Mantenha a respiração, Cassidy ... é apenas um ferimento no peito ...}
{40841}{}{* Nfffff *... sacudiu alguns órgãos soltos ...}
{40842}{}{estilhaços no meu peito...deve me proteger melhor}
{40843}{}{Vou ... * hrkkk * ... precisar ...de mais alguma... . armadura no peito ...}
{40844}{}{*Unfffff*}
{40845}{}{*Unffff* Outra...maldita ferida no peito...}
{40846}{}{* Nfff * Preciso de ajuda ... fui atingido no peito ... que dor...}
{40847}{}{Alguém tem alguns stimpacks! Eu tomei um golpe no peito!}
{40848}{}{*Unnffff* Isso quebrou uma.... ou duas costelas...}
{40849}{}{*Nfff*}
{40850}{}{*Hrkkkk*}
{40851}{}{Ferida no peito ... meu coração esta ficando lento...}
{40852}{}{*Hrnnn*...bem no peito.... vou precisar de um monte de curativos...}
{40853}{}{Acho... meu pulmão foi perfurado...}
{40854}{}{Ignorar a dor, Cassidy ... é apenas uma ferida no peito ... aguenta...}
{40855}{}{* Urkkkk * que golpe... meu coração... bate lento ...}
{40856}{}{Arrancou uma lasca da minha coluna...}
{40857}{}{* Unnnffff * ... estômago ...}
{40858}{}{Acho que quebrou minha coluna...}
{40859}{}{Senti um estalo na costela ..}
{40860}{}{Damn! Eu não levo um tiro na perna desde 1900 e bolinha.}
{40861}{}{* NFFF * ... boa tentativa ... minha perna ja recebeu golpes piores.}
{40862}{}{Isso abriu uma ferida na perna.}
{40863}{}{Vou ter que proteger melhor a minha perna direita...}
{40864}{}{*Nffff*...right leg's...useless...}
{40865}{}{Não consigo... sentir... minha perna direita...}
{40866}{}{* Nfff * ... outra ... ferida na porra da perna. }
{40867}{}{Isso fudeu com meu joelho bom ...}
{40870}{}{Damn! Eu não levo um tiro na perna desde 1900 e bolinha.}
{40871}{}{* NFFF * ... boa tentativa ... minha perna ja recebeu golpes piores.}
{40872}{}{Isso abriu uma ferida na perna.}
{40873}{}{Vou ter que proteger melhor a minha perna esquerda ...}
{40874}{}{*Nffff*...a perna esquerda ficou inútil...}
{40875}{}{Não sinto minha perna esquerda...}
{40876}{}{*Nff*...outra maldita ferida na perna...}
{40877}{}{Isso fudeu com meu joelho bom ...}
{40880}{}{*Hrrrkkk*}
{40881}{}{*Hrnnn*...meu...olho...}
{40882}{}{Voce deixou apenas... * NFFF * ... um dos meus olhos. * Hrkkk * agora eu vou arrancar... os todos os seus.}
{40883}{}{Meu olho... não posso ver...}
{40884}{}{Não consigo ver... apenas vermelho...}
{40885}{}{Não preciso ver para te matar...}
{40886}{}{Graças a Deus esse olho era falso...}
{40890}{}{Me bater nas bolas ... ISSO É novo.}
{40891}{}{Inferno, você acertou meu saco!}
{40892}{}{Nada de golpe abaixo da cintura!}
{40893}{}{Minha terceira perna ja recebeu golpes piores.}
{40894}{}{Acerte novamente meu pinto e eu vou te matar duas vezes.}
{40895}{}{*Hrrrkkk*}
{40896}{}{*Nffff*}
{40897}{}{Eu vou ter que pegar um copo, se continuar assim.}
{40898}{}{Fique longe da minha virilha, seu bastardo!}
{40899}{}{Estamos jogando...pedra...papel e tesoura?!}
{40900}{}{Tenho que cair fora...}
{40901}{}{É a última vez que entro em uma briga sem uma boa armadura.}
{40902}{}{Da próxima vez será você seu filho da puta...}
{40903}{}{Da próxima vez vou arrumar um lançador de foguetes... e mais stimpacks.}
{40904}{}{Se tivesse uns vinte anos a menos, teria ganhado essa luta.}
{40905}{}{Os bastardos me deram uma surra de verdade...}
{40906}{}{Pensei que essa maldita mala amarela havia sumido...}
{40907}{}{A grandesa esta em saber quando puxar saco.}
{40908}{}{Eu tenho que diferenciar quando ficar, quando sair, e quando fugir.}
{40909}{}{Eu tenho que ter cobertura ...}
{40910}{}{Espere até eu respire fundo ...}
{40911}{}{Maldição, minhas velhas feridas estão abertas novamente...}
{40912}{}{Sinto muito amigo, não posso resitir mais...}
{40920}{}{Tem 10 segundos para cair fora...}
{40921}{}{Parece que saimos de um monte de merda para entrar em outro...}
{40922}{}{Hora de corrigir outro erro da mãe natureza.}
{40923}{}{As bombas deveriam ter exterminado todo esse lixo...}
{40924}{}{Vou fazer com que seu trazeiro chegue no seu ouvio.}
{40925}{}{Filho da puta...}
{40926}{}{*Huf*...I...*Huf*...precisso de mais...*Huf*....pontos de ação.}
{40927}{}{Vai agonizar por muito tempo...}
{40928}{}{Você é vai ser um filho da puta morto se comprar briga com a gente ...}
{40929}{}{É hora de Cassidy te ensinar como fazemos as coisa na cidade grande.}
{40940}{}{Eu gostaria de uma pausa pra descansar...}
{40941}{}{Vou arrancar seus dentes e usa-los como dados.}
{40942}{}{Nada melhor que um bom tiro critico nos olhos.}
{40943}{}{Vou te matar... te matar..te matar...}
{40944}{}{Eu tenho seu número, seu pequeno filho da puta ...}
{40945}{}{Você é um teimoso ...}
{40946}{}{Filho da puta...}
{40947}{}{Não tem o que precisa para acabar comigo...}
{40948}{}{Vou arrancar sua alma...}
{40949}{}{Não costumo correr de uma luta, topas?}
{40950}{}{Nada melhor que quebrar alguns ossos para fazer se sentir vivo.}
{40951}{}{Não se preocupe, eu vou cuidar de sua viúva quando você se for ...}
{40952}{}{Parece que você vai sair na vantagem com um ou dois golpes...}
{40953}{}{Hora de se livrar da miseria.}
{40954}{}{Hora de uma pequena limpeza genética...}
{40955}{}{Espero que ja tenha escolhido seu caixão..}
{40956}{}{Se procura a morte, esta no lugar certo.}
{40957}{}{Vou fazer de você um merengue de sangue...}
{40958}{}{Vou reduzir-lhe para o pesadelo de um agente funerário.}
{40959}{}{Vou explodir você...}
{40960}{}{Cão que late não morde...}
{40961}{}{Hoje não, amigo.}
{40962}{}{É mais lento do que uma tartaruga.}
{40963}{}{Areia em seus olhos?}
{40964}{}{Você aponta por apontar. Eu atiro para matar.}
{40965}{}{Você não tem o necessário para acabar comigo.}
{40966}{}{Além de burro é cego.}
{40967}{}{Você falhou por uma boa porcentagem.}
{40968}{}{Seu cego filho da puta.}
{40969}{}{Errou. Na próxima rodada vai perder a cabeça.}
{40970}{}{Inferno, eu sou um bosta, mas posso fazer melhor que você.}
{40971}{}{Pena que você não pode recarregar o jogo e tentar novamente ...}
{40972}{}{Teria acertado se tivesse um pouco mais habilidade.}
{40973}{}{Um conselho: Da próxima vez tente acertar onde mirou.}
{40974}{}{Próximo...}
{40975}{}{Próximo, mas não tem prêmio.}
{40976}{}{Não vai ter uma segunda chance.}
{40977}{}{Lento filho da puta...}
{40978}{}{Parece que Cassidy vai ter que te ensinar como fazemos as coisa na cidade grande.}
{40979}{}{Acredito que vai ter que deixar o álcool antes de entrar em combate.}
{41200}{}{O meu cérebro dói.}
{41201}{}{Agora sim vou te dar umas palmadas!}
{41202}{}{Você machucou a minha bunda.}
{41203}{}{Vejo estrelas.}
{41204}{}{Oh querida, eu acho que perdi mais cabelo.}
{41205}{}{Essa crise não pode ser boa.}
{41206}{}{Só mais um pouco pra cima.}
{41207}{}{Você acabou com meu rosto!}
{41208}{}{Tenha um pouco da minha mente.}
{41209}{}{Oh, oh. Não lembro de nada.}
{41210}{}{Meu peito nunca vai ser o mesmo.}
{41211}{}{Hah, hah. Braço errado, ya 'putz!}
{41212}{}{Ack! Isso dói.}
{41213}{}{Médico! Oh, sou eu. Heh, heh.}
{41214}{}{Essa mão não era boa mesmo.}
{41215}{}{Ouch!}
{41216}{}{Me desarmou!}
{41217}{}{Eu só preciso de um dedo para acabar com você.}
{41218}{}{Lá se vai o meu polegar!}
{41219}{}{Essa pele estava começando a apodrecer de qualquer maneira.}
{41220}{}{Isso realmente vai afetar o meu swing.}
{41221}{}{Puxa...isso dói!}
{41222}{}{Me desarmou!}
{41223}{}{Lá se vai o meu jogo de oito bola.}
{41224}{}{Isso vai me matar na quadra.}
{41225}{}{Não a mais bola rápida para mim.}
{41226}{}{Você quebrou meus ossos frágeis!}
{41227}{}{Aquele som de trituração não é bom.}
{41228}{}{Gostava do meu ombro como era.}
{41229}{}{Maldição, la se vai varios dedos.}
{41230}{}{Preciso de um médico...}
{41231}{}{Perdi varias costelas.}
{41232}{}{Arrrg! Meu estômago!}
{41233}{}{Lá se vai minha vesícula!}
{41234}{}{Heh heh...passou raspando pela minha direita... não senti nada.}
{41235}{}{Médico cura a si mesmo.}
{41236}{}{Uh oh, isso foi muito mau.}
{41237}{}{Hey, Temos alguem sangrando, e sou eu!}
{41238}{}{Alguem quer aprender alguma coisa de anatomia?}
{41239}{}{Nada te agrada mais do que cortar alguns pedaços.}
{41240}{}{Para entender melhor a vida, nada como retirar a vesícula... sinto que estou morto, caramba.}
{41241}{}{Arrrrrrgh! Minha coluna.}
{41242}{}{Uma boa forma de perder peso e altura.}
{41243}{}{Minhas pernas, não sinto minhas pernas!}
{41244}{}{De repente esta fazendo muito frio.}
{41245}{}{Outra maldita cicatriz no.}
{41246}{}{Eu estava muito perto.}
{41247}{}{Agora vou ter que por um pedaço de pele no braço.}
{41248}{}{Sim meus órgãos vitais não foram preservados em um frasco, isso vai doer.}
{41249}{}{Temos que tampar isso com um pano antes que entre moscas.}
{41250}{}{Merda! Tenho cupins!}
{41251}{}{Não tinha idéia de que estava tão seco e quebradiço.}
{41252}{}{Maldição, Alguém tem alguma fita adesiva?}
{41253}{}{(Tosse... ofegante)}
{41254}{}{Buraco de entrada, buraco de saida, a coleção esta completa!}
{41255}{}{Maldição, estão me fatiando.}
{41256}{}{Ta de boa, esse não era meu lado bom.}
{41257}{}{Você arrancou um mamilo!}
{41258}{}{Não obrigado, ja me barbiei aí.}
{41259}{}{Melhor até mesmo do que uma lipoaspiração!}
{41260}{}{De qualquer forma esta perna não estava boa.}
{41261}{}{Agora você pode me chamar compacto.}
{41262}{}{Agora eu só preciso de um papagaio e um tapa-olho.}
{41263}{}{Caramba, é como se ainda estivesse funcionando.}
{41264}{}{Você pode me chamar de manco.}
{41265}{}{Não preciso desses dedos do pé.}
{41266}{}{Acabou a dança para este velho.}
{41267}{}{Quebra como um galho seco.}
{41268}{}{Me pergunto se não há alguma maneira de voltar a usá-la.}
{41269}{}{Oh Não... meus sapatos de camurça azul!}
{41270}{}{Não mais Mr. Rápido.}
{41271}{}{Essa canela estava começando a apodrecer}
{41272}{}{Obrigado por cuidar disso pra mim, estava gangrenando.}
{41273}{}{Ei, isso vai me deixar aleijado.}
{41274}{}{Lá se vai minha confusão elétrica.}
{41275}{}{Alguém tem uma tábua e alguns pregos para volta a pregar isso?}
{41276}{}{Afinal, quem é que precisa de rótulas?}
{41277}{}{Lá se vão os meus dedos!}
{41278}{}{Ouch, shin-splint!}
{41279}{}{Não sinto os dedos dos pés!}
{41280}{}{Acho que vou precisar de um tapa-olho só para me chamarem de Jack Sparrow.}
{41281}{}{Arrrr, que legal, lagrimas saem do meu olho bom.}
{41282}{}{Olho, ai meu olho!}
{41283}{}{Quem apagou as luzes?}
{41284}{}{Meu olho esta em você, uh, pode me devolver agora?}
{41285}{}{Eu ainda posso encontrá-lo com a minha super-audição.}
{41286}{}{Hah, esse era o meu olho de vidro!}
{41287}{}{Isto vai ser olho por olho.}
{41288}{}{Mãe? Está ficando escuro.}
{41289}{}{Olhe o que você fez!}
{41290}{}{Se houvesse qualquer galão de ghoul, ficaria chateado com você.}
{41291}{}{Não poderei mais escrever meu nome na neve.}
{41292}{}{Alguem quer nozes picadas?}
{41293}{}{Eu não ia ser cantor mesmo.}
{41294}{}{Oy-vey!}
{41295}{}{Mazel tov!}
{41296}{}{Eu gostava de ser uma espécie gentil.}
{41297}{}{Como * que isso * vai atrapalhar o meu estilo.}
{41298}{}{De touro a vaca em um único golpe.}
{41299}{}{Eu sinto que eu deveria estar guardando um harém agora.}
{41300}{}{Uh oh, meu senso spider está formigando.}
{41301}{}{Maldição, aqui tem kriptonita. Vou cair fora daqui.}
{41302}{}{Nenhum aviso dizendo que isso seria perigoso!}
{41303}{}{Então querr dizer que eles estão armados?}
{41304}{}{Cooorraaaaaaaa!}
{41305}{}{Corra por isso!}
{41306}{}{Entrada!!!!!!}
{41307}{}{Meus super poderes são inúteis contra esse inimigo!}
{41308}{}{Uh, eu tenho que falar com um homem perto de um cavalo.}
{41309}{}{Eu voltarei. Não me espere.}
{41310}{}{Não, não, não. Você vai na frente. Eu te seguirei mais tarde.}
{41311}{}{Estou atrasado para o meu tratamento de canal. Até mais.}
{41312}{}{E então vamos entrar no coelho gigante e ....}
{41313}{}{Jesus Cristo! Corra!!!!!}
{41314}{}{Pelo amor de Deus, vamos sair daqui!}
{41315}{}{Não quero morrer hoje.}
{41316}{}{Oh, por favor, por favor, por favor, por favor.}
{41317}{}{Pés, não vão travar agora!}
{41318}{}{Vou cair fora daqui!}
{41319}{}{Vou sair correndo daqui!}
{41320}{}{Tenho um mal presentimento sobre isto.}
{41321}{}{Meu sentido aranha esta acionado.}
{41322}{}{É só um coelho.}
{41323}{}{Ele tem dentes de quantos centímetros de comprimento?}
{41324}{}{Sim, agora eles vão assustar.}
{41325}{}{Cuidado, aqui vou eu.}
{41326}{}{Pronto ou não, aqui vou eu!}
{41327}{}{Lenny para o resgate!}
{41328}{}{Não se mexa. Estamos caçando coelhos.}
{41329}{}{Não acho que isso seja uma boa idéia.}
{41330}{}{Vai você primeiro, eu vou te dar retaguarda.}
{41331}{}{Não senhor, parece muito perigoso.}
{41332}{}{Tem certeza de que isso é necessario?}
{41333}{}{Bem, se é a unica maneira.}
{41334}{}{Não nasci para isso.}
{41335}{}{Hey, alguém pode se machucar fazendo isso.}
{41336}{}{Não tem outro jeito de resolver isso?}
{41337}{}{Nos não podemos ficar juntos?}
{41338}{}{Alguém vai se machucar, provavelmente vai ser eu.}
{41339}{}{Me avise quando puder abrir meus olhos.}
{41340}{}{Hai-Keeba!}
{41341}{}{Ele atira, ele marca!}
{41342}{}{...e a multidão vai à loucura!}
{41343}{}{Tremam de medo, o poderoso Lenny agora esta aqui!}
{41344}{}{Yah, é isso mesmo, quem é o fodão agora!}
{41345}{}{Vou te colocar em uma sinuca de bico!}
{41346}{}{Eu vou te desmascarar!}
{41347}{}{Eu Voltarei imbecil, idiota!}
{41348}{}{Ninguém se mete com o 'DOIDÃO' Lenny}
{41349}{}{É melhor você parar, ou senão...}
{41350}{}{Eu fiz isso, eu realmente fiz isso!}
{41351}{}{Você me odeia, você realmente odeia-me!}
{41352}{}{Haii-yah!}
{41353}{}{Agora você é o aluno.}
{41354}{}{Oh, querido, oh me, oh meu.}
{41355}{}{Tome isso!}
{41356}{}{E isso!}
{41357}{}{Bifff!!}
{41358}{}{Pow!!}
{41359}{}{Kablam!!}
{41360}{}{Heh, heh, te enganei.}
{41361}{}{Ufa, essa foi por pouco.}
{41362}{}{Ei, cuidado, você quase me bateu.}
{41363}{}{Oy vey!}
{41364}{}{Nyah, nyah-nyah, nyah-nyah}
{41365}{}{errou!}
{41366}{}{Sim!}
{41367}{}{Você não presta!}
{41368}{}{Não esperava esse movimento, não é verdade?}
{41369}{}{Swing, batta, batta. Swing!}
{41370}{}{Este velho ghouls é mais forte do que pensava hein?}
{41371}{}{Fala.. fala de mais..}
{41372}{}{O que foi isso?}
{41373}{}{Esto não é uma charada.}
{41374}{}{Isso requer muita concentração.}
{41375}{}{Pode fazer melhor que isso.}
{41376}{}{Oh, vem aqui.}
{41377}{}{Isso é o melhor que pode fazer? É serio?}
{41378}{}{Eu só não acho que você está tentando.}
{41379}{}{Esta pondo seu coração nisso?}
{41600}{}{Oooh, meu cérebro.}
{41601}{}{Oh meu Deus!}
{41602}{}{Minha cabeça!}
{41603}{}{Ja tive piores.}
{41604}{}{Você chama isso de ataque?}
{41605}{}{Humano, você tem muita coragem.}
{41606}{}{Chega de jogo limpo.}
{41607}{}{Ok. Agora você está morto.}
{41608}{}{Ay-yi-yi!}
{41609}{}{Arrancou uma orelha!}
{41610}{}{Ouch!}
{41611}{}{Meu ombro!}
{41612}{}{Uma perfuração!}
{41613}{}{Eu acho que você bateu na minha mão.}
{41614}{}{Okay, isto não é divertido.}
{41615}{}{Meu bíceps!}
{41616}{}{Meu tríceps!!}
{41617}{}{Aí minha munheca.}
{41618}{}{Não vou conseguir digitar no meu pc mais... vou te matar.}
{41619}{}{Essa é minha mão de escrever!}
{41620}{}{Aí, minha mão de dar tiro.}
{41621}{}{Meu cotovelo!}
{41622}{}{Santo Deus!}
{41623}{}{Ja recebi coisas piores no treinamento.}
{41624}{}{Suponho que isso teria que doer?}
{41625}{}{Será que uma abelha me picou?}
{41626}{}{Eu acho que você me arranhou.}
{41627}{}{Ouch! Maldição!}
{41628}{}{Meu bíceps!}
{41629}{}{Meu tríceps!!}
{41630}{}{Santo Deus!}
{41631}{}{Ja recebi coisas piores no treinamento.}
{41632}{}{Eu acho que você me arranhou.}
{41633}{}{Ouch! Maldição!}
{41634}{}{Oof!}
{41635}{}{Meu fígado!}
{41636}{}{Minhas entranhas estão como geléia.}
{41637}{}{Deixe eu te devolver o favor.}
{41638}{}{Eu ja tive o SUFICIENTE!}
{41639}{}{Você está se divertindo ainda?}
{41640}{}{Pare com isso.}
{41641}{}{Você realmente acha que é durão?}
{41642}{}{A violencia nunca resolve nada.}
{41643}{}{Ow!}
{41644}{}{Pare com isso.}
{41645}{}{Ja recebi tudo de você.}
{41646}{}{Não sou um mutante feliz.}
{41647}{}{Ai! Pare com isso.}
{41648}{}{Deus! Meu estômago!}
{41649}{}{Meu plexo solar!}
{41650}{}{Meu apêndice!}
{41651}{}{Um pouco mais abaixo e eu seria estéril.}
{41652}{}{Você está me irritando.}
{41653}{}{Maldição, no meu estômago não!}
{41654}{}{Porque, você é danadinho...}
{41655}{}{Pare de me bater!}
{41656}{}{Você está cometendo um grande erro.}
{41657}{}{::respiração difícil::}
{41658}{}{Me deixou sem ar!}
{41659}{}{Você vai pagar por isto.}
{41660}{}{Eu acho que vou ficar manco.}
{41661}{}{Ooh, minha coxa.}
{41662}{}{Meu joelho!}
{41663}{}{Eu disse Pare com ISSO.}
{41664}{}{Vou pular em você.}
{41665}{}{Oh, minha perna!}
{41666}{}{Isso vai dificultar para eu chutar sua bunda.}
{41667}{}{Ow!}
{41668}{}{Hey!}
{41669}{}{Estúpido!}
{41670}{}{mãe...!}
{41671}{}{Meu joelho!}
{41672}{}{Meu tornozelo!}
{41673}{}{Minha panturrilha!}
{41674}{}{Merda!}
{41675}{}{Porra!}
{41676}{}{Isso vai deixar uma cicatriz.}
{41677}{}{Ow!}
{41678}{}{Estúpido!}
{41679}{}{Hey!}
{41680}{}{Aaah!}
{41681}{}{Estou cego! Estou cego!}
{41682}{}{Acabou a graça!}
{41683}{}{My retina!}
{41684}{}{Arrr!}
{41685}{}{Médico!}
{41686}{}{Preciso de um tapa-olho!}
{41687}{}{Minha córnea!}
{41688}{}{Minha íris!}
{41689}{}{Acabou a graça!}
{41690}{}{merda! Agora estou estéril, com certeza!}
{41691}{}{Aieeeeeeeee!}
{41692}{}{Os meus testículos!}
{41693}{}{Oh... deus...}
{41694}{}{Ow. Ow. Ai!}
{41695}{}{A dor, a dor ...}
{41696}{}{Que horror ... Que horror ...}
{41697}{}{::ofegando::}
{41698}{}{Isso ... dói ...}
{41699}{}{Oh, totalmente sem preparo físico!}
{41700}{}{Foda-se vocês, eu estou indo para casa.}
{41701}{}{Nunca pensei que veria o dia ...}
{41702}{}{Estúpido :: hum, hum::}
{41703}{}{retirada estratégica! Vamos lá!}
{41704}{}{Eu não sou um mutante alegre!}
{41705}{}{Não há honra em fugir.}
{41706}{}{filho da puta... fugindo.}
{41707}{}{merda. Tenho que cair fora.}
{41708}{}{Isso não é certo.}
{41709}{}{Vou ficar atras de você.}
{41710}{}{Vamos cair fora daqui!}
{41711}{}{Vamos, caipiras!}
{41712}{}{Vamos sair daqui!}
{41713}{}{Pés, não me falhem agora.}
{41714}{}{Deuses ... se outros mutantes me verem agora estou lascado.}
{41715}{}{:: balança a cabeça e corre ::}
{41716}{}{Nunca achei que teria que correr.}
{41717}{}{Deve estar escorregando na minha velhice.}
{41718}{}{O que diabos eu estou fazendo?}
{41719}{}{Aqui vou eu ...}
{41720}{}{Eu tenho uma lata de Skol! com o seu nome.}
{41721}{}{Você quer um pouco disso?}
{41722}{}{Você ferrou com o cara errado.}
{41723}{}{Vou gostar disto...}
{41724}{}{Pés, mãos, cabeça ... tudo vai atrás de seu traseiro.}
{41725}{}{Incline-se, amigo ...}
{41726}{}{Isto pode ser divertido.}
{41727}{}{Estou aproximando do seu cu.}
{41728}{}{Idiotas ... fugir!}
{41729}{}{Vá em frente! Caiam fora daqui!}
{41730}{}{Não me faça te matar.}
{41731}{}{Vou ter que sacar as armas grandes, né?}
{41732}{}{merda, parece que você está em desvantagem.}
{41733}{}{La vem problema.}
{41734}{}{hora de adicionar mais um alvo para minha arma.}
{41735}{}{É melhor você correr, monstro.}
{41736}{}{Arma, te apresento meu inimigo. Inimigo, conheça a minha arma.}
{41737}{}{Imagine esso atravessando sua garganta.}
{41738}{}{Isso vai te machucar.}
{41739}{}{Isso vai doer mais em você do que em mim.}
{41740}{}{Aqui... FUI!}
{41741}{}{Como nos velhos tempos.}
{41742}{}{Sua cabeça vai conhecer seu cu.}
{41743}{}{Morre, seu comedor de merda.}
{41744}{}{Por que você simplismente não morre?}
{41745}{}{Vai desistir?}
{41746}{}{Deite-se, idiota!}
{41747}{}{Tomá-lo como uma garotinha!}
{41748}{}{Gosta disso?}
{41749}{}{Vai querer mais?}
{41750}{}{La vem.}
{41751}{}{As pessoas nunca aprendem.}
{41752}{}{Às vezes tanta violência me cansa.}
{41753}{}{Você tem parentes?}
{41754}{}{Quando foi a última vez que você foi espancado?}
{41755}{}{Chris Avellone te ama!}
{41756}{}{Aqui tem um pouquinho de amor mutante.}
{41757}{}{Saudações, amigo.}
{41758}{}{Graças ao São Pedro.}
{41759}{}{Um punho, dois punho, punho vermelho, punho azul...}
{41760}{}{Isso é o melhor que você pode fazer?}
{41761}{}{Me avise quando quiser me assustar.}
{41762}{}{Próximo..}
{41763}{}{Pegue um número.}
{41764}{}{Bzz! Isso se chama ERRO!}
{41765}{}{Vocês nunca desisti?}
{41766}{}{bocejo.}
{41767}{}{Amadores.}
{41768}{}{Pratique um pouco, jovem.}
{41769}{}{Talvez você consiga me bater um dia.}
{41770}{}{Quando é que vai começar a ação?}
{41771}{}{Preciso de uma bebida fresca. Aqui não acontece nada.}
{41772}{}{Onde está a emoção?}
{41773}{}{Oh! Você estava apontando pra MIM!}
{41774}{}{Você precisa praticar mais ok?}
{41775}{}{Obrigado, tente novamente.}
{41776}{}{Não é isso.}
{41777}{}{:: olha para o relógio ::}
{41778}{}{Pra que esta violência sem sentido?}
{41779}{}{Será que não podemos conviver juntos?}
{42000}{}{ignore a dor de cabeça... ignore a dor de cabeça}
{42001}{}{Aighh! Há sangue por toda a minha cara! Ajuda! Stimpack! Ajuda!}
{42002}{}{minha cabeça! minha cabeça! ME ACERTOU NA CABEÇA! SOCORRO! SOCORRO!}
{42003}{}{Oooooooh. Lá se vai a alguns pontos de Inteligência.}
{42004}{}{São pedaços do meu cérebro em minhas mãos?}
{42005}{}{Onde foi parar minha orelha?}
{42006}{}{Ooooh! Meu primeiro ferimento na cabeça...ow. Owwwww. OWWWWW.}
{42007}{}{Hey! O que minha orelha faz no chão?!}
{42008}{}{Ou eu fui atingido na cabeça, ou esta é a pior enxaqueca que eu já tive.}
{42009}{}{A minha cara! Meu belo rosto cheio de espinhas de olhos esbugalhados!}
{42010}{}{ignorar a dor em meu braço... ignorar a dor em meu braço}
{42011}{}{Aighh! Há sangue por todo meu braço! Ajuda! Stimpack! Ajuda!}
{42012}{}{Meu braço! Meu braço! ME ACERTOU NO BRAÇO! SOCORRO! SOCORRO!}
{42013}{}{Não é o meu braço esquerdo! Esse é o meu braço forte!}
{42014}{}{Não é a minha mão! Rosie! Rosie Palmer! Fale comigo, garota!}
{42015}{}{Aighhh! Meu osso engraçado! Eu. .. Eu. .. Eu. .. deve manter ... de ... de rir ...}
{42016}{}{Aieeee! Eu não posso sentir meu braço esquerdo!}
{42017}{}{* Urkkk * ... braço esquerdo ... parece que está pegando fogo ...}
{42020}{}{ignorar a dor em meu braço... ignorar a dor em meu braço}
{42021}{}{Aighh! Há sangue por todo meu braço! Ajuda! Stimpack! Ajuda!}
{42022}{}{Meu braço! Meu braço! ME ACERTOU NO BRAÇO! SOCORRO! SOCORRO!}
{42023}{}{Não é a minha mão! Rosie! Rosie Palmer! Fale comigo, garota!}
{42024}{}{Aighhh! Meu osso engraçado! Eu. .. Eu. .. Eu. .. deve manter ... de ... de rir ...}
{42025}{}{Aieeee! Eu não posso sentir meu braço direito!}
{42026}{}{* Urkkk * ... braço direito... parece que está pegando fogo ...}
{42027}{}{Não meu braço direito! Eu uso ele nos fins de semana para traduzir alguns jogos!}
{42030}{}{ignorar a dor em meu peito... ignorar a dor em meu peito}
{42031}{}{Meu protetor de bolso!}
{42032}{}{* Unfff * ... hey ... era minha... última camisa limpa.}
{42033}{}{Aighh! Há sangue por todo meu peito! Ajuda! Stimpack! Ajuda!}
{42034}{}{MEU PEITO! MEU PEITO! EU FUI ATINGIDO NO PEITO! AJUDA! AJUDA!}
{42035}{}{* Urkkk * ... peito ... parece que está pegando fogo ...}
{42036}{}{Que diabos é esse sangue ... TA fazendo ... o que... no meu... peito ... * urkkk *}
{42037}{}{Unfff... fui abatido...}
{42038}{}{Se você quebrar minha calculadora de bolso, eu vou te matar.}
{42039}{}{Eu acho que eu acabei de ouvir minha coluna de crack.}
{42040}{}{Acho melhor não ser o meu baço no chão.}
{42041}{}{Então é com isso que meus intestinos se parecem.}
{42042}{}{Aaa ... Eu vou precisar de... outro ... pulmão ...}
{42043}{}{Que diabos é esse buraco no meu peito?}
{42044}{}{Meu peito! A porra do meu peito!}
{42045}{}{Eu acho que meu peito esta torto.}
{42046}{}{Aieeeee! Meu estômago! Meu baço!}
{42047}{}{Outra baço! Quantos malditos baços que eu tenho?!}
{42048}{}{Eu acabei de acordar de um sonho em que alguém me bateu no peito ... uh-oh.}
{42049}{}{Há bolhas que saem do meu peito. Isso não pode ser bom.}
{42050}{}{Espero acho que perdi meu coração. Espere ... não, isso não aconteceu.}
{42051}{}{Grande. Mais sangue. Brotaaaando do meu peito. Caralho.}
{42052}{}{Me perdoem por deixar o chão todo cheio de sangue.}
{42053}{}{Nada como um peito jorando sanque pra alegrar o dia.}
{42054}{}{Isso são minhas costelas estralando?}
{42055}{}{Ughhh ... Me sinto como se alguém rasgou meu peito ... uh-oh.}
{42056}{}{De onde veio esse maldito buraco no meu peito?}
{42057}{}{* Hrrkkkk * ... alguém ... consegue ... pra mim...um... kit de primeiros socorros (first aid) ...}
{42058}{}{Bem ... que gêiser de sangue que emana do meu peito é a prova de que tem pressão arterial elevada.}
{42059}{}{}
{42060}{}{ignorar a dor na minha perna... ignorar a dor na minha perna}
{42061}{}{Aighh! Há sangue por toda parte da minha perna! Ajuda! Stimpack! Ajuda!}
{42062}{}{Minha perna! Minha perna! EU FUI ATINGIDO NA PERNA! AJUDA! AJUDA!}
{42063}{}{Aieeeee! Eu não posso sentir minha perna direita!}
{42064}{}{Owwww! Minha perna!}
{42065}{}{* Urkkk * ... perna direita ... parece que está pegando fogo ...}
{42066}{}{Oh não! Essa era minha perna! Nããão!}
{42067}{}{Você vai estar recebendo um telefonema do meu podólogo!}
{42068}{}{Aighh! Lá se vai minha perna. Eu vou ter que rastejar para fora da aqui, usando meus quadris.}
{42070}{}{ignorar a dor na minha perna... ignorar a dor na minha perna}
{42071}{}{Aighh! Há sangue por toda parte da minha perna! Ajuda! Stimpack! Ajuda!}
{42072}{}{Minha perna! Minha perna! EU FUI ATINGIDO NA PERNA! AJUDA! AJUDA!}
{42073}{}{Aieeeee! Eu não posso sentir minha perna esquerda!}
{42074}{}{Owwww! Minha perna!}
{42075}{}{* Urkkk * ... perna esquerda... parece que está pegando fogo ...}
{42076}{}{Oh não! Essa era minha perna! Nããão!}
{42077}{}{Você vai estar recebendo um telefonema do meu podólogo!}
{42078}{}{Aighh! Lá se vai minha perna. Eu vou ter que rastejar para fora da aqui, usando meus quadris.}
{42080}{}{Yuh-yuh-lo ... me acertou no olho ...}
{42081}{}{Meus olho! Meus olho! Ajuda! Alguém me ajude!}
{42082}{}{Aighh! Eu não posso ver! Ajuda! Stimpack! Ajuda!}
{42083}{}{Meus olho! Meus olho!}
{42084}{}{Estou cego! Não vou poder me masturbar!}
{42085}{}{Owwwww! Meus olho! Meus olho!}
{42086}{}{Aieeeee! Eu fui atingido no olho! Todo mundo, olhe para mim!}
{42087}{}{Meu olho esta sangrando! Merda!}
{42088}{}{Grande. Lá se vai alguns pontos de Percepção.}
{42089}{}{Alguém pode me dizer se esse foi o meu globo ocular ou apenas um tiro de na minha cabeça?}
{42090}{}{ignorar a dor em minhas bolas... ignorar a dor em minhas bolas}
{42091}{}{Nas bolas não!}
{42092}{}{Aiiieeee! Levei um tiro no saco!}
{42093}{}{Acho que cortou!}
{42094}{}{Por favor não acerte nas partes abaixo okay.}
{42095}{}{Ajuda! Fui atingido na virilha! Ajuda!}
{42096}{}{Eu vou precisar de quinze stimpacks uma vez que a dor atingiu o cérebro.}
{42097}{}{Minha virilha! Myron ... fale comigo, amigo! Fale comigo!}
{42098}{}{Acho que vou precisar uma prótese antes voltar a frequentar a putaria.}
{42099}{}{Vou dar suas bolas para outras pessoas.}
{42100}{}{Estamos ferrados.}
{42101}{}{Estamos fudidos.}
{42102}{}{Game over, cara! Game Over!}
{42103}{}{merda! Eu sou daqui!}
{42104}{}{Não me machuque! Não me machuque!}
{42105}{}{Aieeeee! Meu cabelo parece pegar fogo!}
{42106}{}{Essas lutas são muito mais divertidas à distância.}
{42107}{}{Todo mundo me passe a grana que e eu vou garantir a nossa rota de fuga!}
{42108}{}{Entra ai! Eu te cubro! É serio!}
{42109}{}{Por aqui! Eu vejo uma briga do outro lado! Vou cuidar disso!}
{42110}{}{Eu tenho que dar o fora daqui.}
{42111}{}{Não me bata! Eu tenho problema de rins!}
{42112}{}{Não me bata! Não me bata!}
{42113}{}{Hora de observador de longe...}
{42114}{}{Eu deveria ter trazido meu spray de asma. Sinto que esta vindo uma crise de asma.}
{42115}{}{Aieeeeee!}
{42116}{}{Tem que sair daqui tem que sair daqui tem que sair daqui}
{42117}{}{Pés, não vão falhar agora né!}
{42120}{}{Eu não brigo desde a quinta série.}
{42121}{}{Estou bem atrás de você!}
{42122}{}{Estou vigiando ao redor!}
{42123}{}{Essas lutas com certeza são muito mais divertidas a distância ...}
{42124}{}{Prefiro observar de longe.}
{42125}{}{Estou pronto para o rock and roll. O que quer que isso signifique.}
{42126}{}{Vou arrancar sua cabeça e ... uh ... um porcaria, esqueci o resto.}
{42127}{}{Vamos ver: Vou começar pelo pescoço, cagar na sua cabeça...}
{42128}{}{Vou te tratar como uma prostituta.}
{42129}{}{Alguém me de cobertura? Alguém?!}
{42130}{}{Hiiiiiyaaaaaa!!!}
{42131}{}{Deixe isso para mim! Deixe isso para mim!}
{42132}{}{Myron! He's one bad mutha...}
{42133}{}{Ainda bem que todos esses anos jogando Fallout me ensinou-algumas coisas sobre coragem.}
{42140}{}{Você é uma overdose esperando para acontecer.}
{42141}{}{Você tem experiência?}
{42142}{}{Toma isso!}
{42143}{}{Você esta com sorte, escoria?}
{42144}{}{Vi Robert DeNiro fazer isso em um filme antigo, uma vez ...}
{42145}{}{Vou te tratar como uma prostituta.}
{42146}{}{Er... segura o grosso!}
{42147}{}{Er...Tome isso!}
{42148}{}{Quer um pouco de Myron, hein? Então ... uh ... você vai ter! Yeah!}
{42149}{}{Alguém me de cubertura!}
{42150}{}{Você tem sorte de eu ser uns 20kg. mais leve, ou você estaria morto agora.}
{42151}{}{Por favor morra, por favor morra..}
{42152}{}{Eu trabalho duro, e eu luto ... bem, na verdade, eu não trabalho tanto assim.}
{42153}{}{Essas lutas com certeza são muito mais divertido à distância.}
{42154}{}{Prefiro observar de longe.}
{42155}{}{Você pode ficar duas semanas livre se beijar minha bunda.}
{42156}{}{Eu não posso acreditar que estou realmente em uma luta.}
{42157}{}{Eu não brigo desde a quinta série.}
{42158}{}{Você mordeu mais do que pode mastigar, cara de cu.}
{42159}{}{Morre! Eh, por favor?}
{42160}{}{Caramba!}
{42161}{}{Aieeeee ... oh, espere que você errou. Esqueça aquela parte do grito.}
{42162}{}{Você não vale nada!}
{42163}{}{Isso foi muito perto ...}
{42164}{}{Será que alguém pode me ajude, por favor!}
{42165}{}{Acho que fiz xixi nas calças.}
{42166}{}{Ajuda! Isso quase me pegou!}
{42167}{}{Não me machuque! Não me machuque!}
{42168}{}{Não me ataque! Não me ataque!}
{42169}{}{Eu sou muito jovem para morrer... Eu sou muito jovem para morrer... Sou muito jovem para morrer}
{42170}{}{por favor ataque outro... por favor ataque outro...}
{42171}{}{Caramba. Foi por pouco.}
{42172}{}{Hey! Você está tentando me matar! Pare com isso!}
{42173}{}{Não, não! Não ... oh, ufa. Você errou.}
{42174}{}{Eu vou precisar de uma nova cueca quando isso terminar.}
{42175}{}{Não podemos falar sobre isso?}
{42176}{}{Ha! Você perdeu, idiota!}
{42177}{}{Zoiks!}
{44000}{}{Bzzzt!}
{44010}{}{Zzzzzzt!}
{44020}{}{Fizzzzzzzzt!}
{44030}{}{Buzzzzz!}
{44060}{}{Pfffft!}
{44070}{}{Mfffffft!}
{44080}{}{Zot!}
{44090}{}{Zaaap!}
{44100}{}{BA - NAN - NAS}
{44101}{}{Voltando à selva}
{44400}{}{Invólucro do cérebro rompida.}
{44401}{}{Detectado vazamento no revestimento do cérebro.}
{44402}{}{Níveis de fluido diminuindo.}
{44403}{}{Conexão do cérebro falhando.}
{44404}{}{Atividade das ondas cerebrais temporariamente interrompida.}
{44405}{}{Níveis de EEG caindo.}
{44406}{}{Sensores internos indicam danos ao cérebro.}
{44407}{}{Fissura detectado no revestimento do cérebro.}
{44408}{}{Pressão Biogel caindo. Desconexão iminente.}
{44410}{}{Extensor Esquerda danificado.}
{44411}{}{Extensor direito danificado.}
{44412}{}{Computando danos no manipulador esquerda.}
{44413}{}{Manipulador prejudicado.}
{44420}{}{Os Sensores registam danos ao manipulador direita.}
{44421}{}{Mal funcionamento dos servidores do manipulador.}
{44422}{}{Mecanismo de Rotação severamente danificado.}
{44423}{}{Os sistems informam danos no circuito retrator direito.}
{44430}{}{Iniciando seqüência de reparo.}
{44431}{}{Impacto no sequenciador de auto giro. Compensação.}
{44432}{}{Pressão hidráulica caindo. Vazamento detectado em reservatórios.}
{44433}{}{Relés secundários danificado. Ajustar para compensar.}
{44434}{}{Ligação da interface primária cortada. Ativando sistemas de backup.}
{44435}{}{Bobinas de Restrição cortada. Restauração de fábrica necessário.}
{44436}{}{Mau funcionamento dos sistemas.}
{44437}{}{Sistemas energéticos flutuando. Ativando energia de reserva.}
{44438}{}{Integridade do casco principal comprometida. Principais circuitos expostos.}
{44439}{}{Danos na unidade de condicionamento de energia. Operando com 75% da capacidade.}
{44460}{}{Motivador direito atingido. Danos mínimos.}
{44461}{}{Bogie direito fora do alinhamento.}
{44462}{}{Roda direita danificada.}
{44463}{}{Piso direito atingido.}
{44470}{}{Motivador esquerdo atingido. Danos mínimos.}
{44471}{}{Bogie esquerdo fora do alinhamento.}
{44472}{}{Roda esquerda danificada.}
{44473}{}{Piso esquerdo atingido.}
{44480}{}{Optical relays hit. Attempting to compensate.}
{44481}{}{Lens damaged on main sensors. Switching to infrared.}
{44482}{}{Imaging scanners hit. Picture resolution deteriorated.}
{44483}{}{Targeting systems impaired. Auto tracking disabled.}
{44490}{}{Regulator hit. Fluid levels dropping.}
{44491}{}{Damage to regulator registered.}
{44492}{}{Regulator fused. Rerouting functions.}
{44500}{}{Executando Programa de auto-preservação.}
{44501}{}{Análise do inimigo completa. Plano de ataque sugerido: Retirada.}
{44502}{}{Retornando à base para reparos.}
{44503}{}{Iniciando protocolo de evacuação.}
{44504}{}{Batalha análise completa: Retirada recomendado.}
{44505}{}{Recuando.}
{44506}{}{Ativando Manobras evasivas.}
{44507}{}{Abandonando território hostil.}
{44520}{}{Analisando inimigo.}
{44521}{}{Movendo-se para posições de ataque.}
{44522}{}{Alvo adquirido.}
{44523}{}{Computando nível de ameaça do alvo.}
{44524}{}{Alternar para o modo de combate.}
{44525}{}{Alvo selecionado para a eliminação.}
{44526}{}{Digitalização de capacidades inimigas. Ajuste padrão de ataque para compensar.}
{44527}{}{Fechando a distância de tiro ideal.}
{44528}{}{Movendo-se para alcance de ataque.}
{44540}{}{Alternar para o modo de combate.}
{44541}{}{Padrão de ataque Omega iniciada.}
{44542}{}{Acabando com entidade hostil.}
{44543}{}{Iniciando seqüência de ataque.}
{44544}{}{Bloqueio do alvo confirmada.}
{44545}{}{Atacar alvo agora.}
{44546}{}{Alcance de ataque ideal.}
{44547}{}{Iniciando ataque sobre o alvo.}
{44548}{}{Iniciando ataque.}
{44549}{}{Eliminando ameaça.}
{44560}{}{Ativando manobras evasivas.}
{44561}{}{Protocolo defensivo Beta iniciado.}
{44562}{}{Capacidade de segmentação do Inimigo: baixo. Reajustar nível de ameaça.}
{44563}{}{Erro do Inimigo. Recálculo capacidade ofensiva do inimigo.}
{44564}{}{Análise: eficácia inimigo mínima.}
{44565}{}{Análise: exito na manobras evasiva.}
{44566}{}{Unidade não danificada.}
{44800}{}{Tenho a cabeça dura, mas isso dói.}
{44801}{}{Agora tenho uma maldita dor de cabeça.}
{44802}{}{Umph. Na cabeça não!}
{44803}{}{Eu também posso machucar sua cabeça!}
{44804}{}{Arrrgh! Tonnnto...}
{44810}{}{Vou te matar com meu outro braço.}
{44811}{}{Não preciso dos meus dois braços para acabar com seu dia!}
{44812}{}{De qualquer maneira eu não usava este braço.}
{44813}{}{Ouch! Vai ter que usar um cabresto.}
{44814}{}{Um braço a menos, ainda tenho outro!}
{44820}{}{Ei, esse é meu braço de luta!}
{44821}{}{Maldição, nesse braço dói!}
{44822}{}{Posso acabar com você sem a necessidade dos meus braços.}
{44823}{}{Meu braço direito...arrgh!}
{44824}{}{Você machucou meu braço. Agora vou arrancar o seu!}
{44830}{}{Umph...Não posso...respirar.}
{44831}{}{Um par de costelas a menos.}
{44832}{}{Ouch! Odeio tiros no estômago.}
{44833}{}{Arrgghh! Dores no peito!}
{44834}{}{Meus estômago...isso sim é que é dor!}
{44835}{}{Isso é uma luta ou você está apenas tentando chamar minha atenção?}
{44836}{}{Suponho que isso deveria doer. Vou chorar por você mais tarde.}
{44837}{}{Sua mãe que te ensinou a lutar?}
{44838}{}{Oh a dor (bocejo). Por favor, não me machuque mais.}
{44839}{}{Você chama isso de golpe. Vou te mostrar como se faz!}
{44840}{}{Eu vou chutar o seu traseiro por isso.}
{44841}{}{Whoa! Isso dói um pouquinho.}
{44842}{}{Deixou o refúgio por isso?}
{44843}{}{Eu vou precisar de um período de férias.}
{44844}{}{Yeeeouch! Isso dói!}
{44845}{}{Isso não doeu nada}
{44846}{}{Onde estão os stimpacks quando preciso deles?}
{44847}{}{Você vai ver quando eu puder me mover novamente!}
{44848}{}{Eu sou imune à dor!}
{44849}{}{Vou desfigurar sua cara por isso!}
{44860}{}{Genial.}
{44861}{}{Ouch! Minha perna...}
{44862}{}{Vai pagar por isso.}
{44863}{}{Vou sentir falta dessa perna ...}
{44864}{}{Não preciso de duas pernas para matar você.}
{44870}{}{Grande. Uma perna machucada.}
{44871}{}{Maldição! Minha perna...}
{44872}{}{Na perna não...como vou andar assim.}
{44873}{}{Quebrou minha perna, agora vou quebrar a sua.}
{44874}{}{Arrggh! Isso dói o joelho!}
{44880}{}{Não posso ver!}
{44881}{}{Não nos olhos!}
{44882}{}{Sangue...nos olhos... não posso ver.}
{44883}{}{Eu não posso vê-lo, mas posso sentir seu cheiro.}
{44884}{}{Vou precisar de óculos depois disso!}
{44890}{}{Na virilha é golpe baixo!}
{44891}{}{Não atire... a baixo...cintura!}
{44892}{}{Isso é golpe baixo...que tal se eu der um chute no seu saco?}
{44893}{}{Odeio tiros abaixo da cintura..}
{44894}{}{Um tiro bem no meio das pernas...ainda bem que não sou humano!}
{44900}{}{Hora de correr!}
{44901}{}{Hora de cair fora!}
{44902}{}{Retiro!}
{44903}{}{Voltando!}
{44904}{}{Eu estou fora daqui!}
{44905}{}{Pés, não vão falhar agora né!}
{44906}{}{Fora do caminho, quero passar!}
{44907}{}{Não estou fugindo, estou me posicionando estrategicamente.}
{44908}{}{Eu já tive o suficiente desta merda!}
{44909}{}{Tenho que sair daqui!}
{44920}{}{Vem aqui para que eu possa te acertar!}
{44921}{}{Você é meu!}
{44922}{}{Sou eu ou você... e eu voto em você!}
{44923}{}{É seu funeral!}
{44924}{}{Vem pegar!}
{44925}{}{Prepare para enfrentar pesadelo!}
{44926}{}{Melhor beijar seu rabo enquanto ainda pode.}
{44927}{}{Vou te fazer sangrar por tudo quanto é buraco!}
{44928}{}{Que comece a festa!}
{44929}{}{Estou indo em!}
{44930}{}{Nos vemos na linha da frente!}
{44931}{}{Hora de sair e matar alguém!}
{44932}{}{Avançar e aniquilar!}
{44933}{}{Vou pra cima de você com tudo!}
{44934}{}{Hora de pegar pesado!}
{44935}{}{Agora ficou pessoal.}
{44936}{}{Idiota ao ponto de morrer!}
{44937}{}{Atacando!}
{44938}{}{Alvo atingido!}
{44939}{}{Há uma tempestade chegando!}
{44940}{}{Vou te machucar...e MUITO!}
{44941}{}{Vai doer mais em você do que em mim!}
{44942}{}{Faça aos outros antes que eles façam a você!}
{44943}{}{Se há uma parte de você que não dói, essa vai ser a próxima!}
{44944}{}{Esportes de contato. Adoro!}
{44945}{}{Me diga seu nome para eu possa procurar seu parente mais próximo.}
{44946}{}{Eu sou a razão pelo qual todos conhecem como Deathclaw!}
{44947}{}{É melhor dar que receber!}
{44948}{}{Espero que esteja gostando tanto quanto eu!}
{44949}{}{Esta doendo? Senão posso te golpear mais duramente.}
{44950}{}{Temos um sangrando por aqui!}
{44951}{}{Você vai precisar de muito mais que um stimpack pra te consertar.}
{44952}{}{Espero que tenha seguro de vida. Vai precisar.}
{44953}{}{Um rasgo aqui...um rasgo ali...rasgado em tudo quanto é parte.}
{44954}{}{Não interessa quem começou, EU vou de terminar!}
{44955}{}{Adoro o som dos ossos quebrando, você não?}
{44956}{}{Só estou brincando, o melhor vem agora.}
{44957}{}{Estou afiando minhas garras.}
{44958}{}{Oooops! Espero que não precise disto!}
{44959}{}{Vou embora somente quanto cair e não se levantar!}
{44960}{}{Poderia parar de se mover para que eu possa acerta?}
{44961}{}{Garrafas. Deveria trazer algumas garrafas.}
{44962}{}{Precisa que eu pinte um alvo em você?}
{44963}{}{Por que você está mirando lá quando estou aqui?}
{44964}{}{Acho que não devia se dedicar profissionalmente à luta.}
{44965}{}{Como você consegue errar algo tão gordo quanto eu?}
{44966}{}{Ai sim...na distancia adequada, vai ter problemas.}
{44967}{}{Eu sou um merdinha ligeiro, certo?}
{44968}{}{Fico feliz por minha mão não ver isso.}
{44969}{}{Você realmente deveria considerar praticar mais.}
{44970}{}{Que vergonha. Por favor, não conte a ninguém que eu fiz isso.}
{44971}{}{Então, você está se esforçando para errar o alvo?}
{44972}{}{Isso não te deixa puto?}
{44973}{}{Eu vou acertar você da próxima vez.}
{44974}{}{Ae, Grace. E se você tentar de novo?}
{44975}{}{Isso foi um exemplo brilhante de como não acertar o alvo.}
{44976}{}{Estou começando a pensar que não sou muito bom com isso.}
{44977}{}{Você está tentando me fazer morrer de rir?}
{44978}{}{Acertei o vendo! Pufs, nunca errei tanto!}
{44979}{}{Errei de novo!}
{50000}{}{}
{50010}{}{}
{50020}{}{}
{50030}{}{}
{50060}{}{}
{50070}{}{}
{50080}{}{}
{50090}{}{}
{50100}{}{}
{50120}{}{}
{50140}{}{}
{50160}{}{}
{60000}{}{Sistema ofensiivo excedido}
{60020}{}{Sistema ofensiivo inicializado.}
{60040}{}{Whrrr. Clic. Clic. Woof!}
{60041}{}{Arg! Clic. Woof!}
{60060}{}{Ação ofensiva evadida.}
{70000}{}{É melhor torcer para que não deixa uma cicatriz.}
{70001}{}{Woah! Na cara não!}
{70002}{}{Minha cara! Minha linda cara!}
{70003}{}{Hey! Não mexa comigo.}
{70004}{}{Tente de novo filho da puta pra ver o que acontece.}
{70010}{}{Isso dói, imbecil.}
{70011}{}{Merda! Meu braço!}
{70012}{}{Ei, dispensar as armas.}
{70013}{}{Filho da puta, isso dói!}
{70020}{}{Isso dói, imbecil.}
{70021}{}{Merda! Meu braço!}
{70022}{}{Ei, dispensar as armas.}
{70023}{}{Filho da puta, isso dói!}
{70030}{}{Estou tecnicamente com mais de cento e oitenta anos de idade, você deve se sentir envergonhado.}
{70031}{}{Estou sangrando ... não é assim que isso deve funcionar.}
{70032}{}{Você não pode me matar, eu tenho o coração de um demônio.}
{70033}{}{Me bata de novo e eu vou te meter a faca na virilha.}
{70040}{}{Você está tentando me encorajar?}
{70041}{}{Ah! Meu joelho!}
{70042}{}{Merda! Minha perna!}
{70043}{}{Você me deu um cavalo Charley porra!}
{70050}{}{Você está tentando me encorajar?}
{70051}{}{Ah! Meu joelho!}
{70052}{}{Merda! Minha perna!}
{70053}{}{Você me deu um cavalo Charley porra!}
{70060}{}{Meus olhos!}
{70061}{}{Oh merda, meus olhos NÃO!}
{70062}{}{MAh! Eu não consigo ver nada!}
{70063}{}{MEUS Olhos! Meus olhos! Ja não sou mais uma pessoa atraente!}
{70070}{}{FODA!}
{70071}{}{Você acabou de tornar isso pessoal.}
{70072}{}{Oh, você vai se arrepender disso.}
{70073}{}{Você está se metendo no topo da linha de tecnologia de antes da guerra.}
{70074}{}{Ciumento?}
{70075}{}{Whoa! Whoa! Whoa! Isso foi desnecessário!}
{70100}{}{Olha, tudo isso foi apenas um grande mal-entendido.}
{70101}{}{Eu estou bem arrependido, agora me deixe em paz.}
{70102}{}{Foda-se, eu vou embora daqui.}
{70103}{}{Vou voltar mais tarde e te esfaquear enquanto você dorme.}
{70104}{}{Foi só uma piada.}
{70105}{}{Sinto muito, eu não sei o que deu em mim.}
{70106}{}{Eles me obrigaram a fazer isso, eu juro!}
{70107}{}{Deixe-me viver e eu nunca vou matar de novo, eu prometo!}
{70108}{}{Não podemos apenas falar sobre isso como pessoas civilizadas?}
{70120}{}{Oh, eu vou gostar disso.}
{70121}{}{Eu não posso esperar para ouvir alguns gritos.}
{70122}{}{Eu apenas fui ansiosos para matar ...}
{70123}{}{Hora de entrar nas alegrias de uma sociedade sem lei.}
{70124}{}{Tudo bem! Hora de balear nas partes de baixo!}
{70140}{}{Grite para mim.}
{70141}{}{Deixe-me dar uma olhada melhor no seu sangue.}
{70142}{}{Vou tentar fazer isso o mais doloroso possível.}
{70143}{}{Toda essa violência está me deixando de pau duro.}
{70160}{}{O que... não esta brincando.}
{70161}{}{Puta merda você chupa.}
{70162}{}{Você tem sorte que você perdeu. Na verdade, você não tem sorte, porque eu ainda vou te matar.}
{70163}{}{A caminho para o erro, campeão.}
{70200}{}{A esperança que não deixar uma cicatriz ...}
{70201}{}{Maldição! Você arrebentou meu dente seu macaco!}
{70202}{}{Hey! Mire na cara!}
{70210}{}{Merda! Acertou meu braço!}
{70211}{}{Ohh, esse picadas!}
{70212}{}{Isso vai deixar uma contusão feia no pinto.}
{70220}{}{Merda! Acertou meu braço!}
{70221}{}{Ohh, esse picadas!}
{70222}{}{Isso vai deixar uma contusão feia no pinto.}
{70230}{}{Ah! Mesmo no meu peito!}
{70231}{}{Lá se vai uma das minhas vidas ...}
{70232}{}{Você acertou meu coração, macaco!}
{70240}{}{Você não pode suportar este gato.}
{70241}{}{Merda, bem no meu joelho!}
{70242}{}{Você não pode me atrasar!}
{70250}{}{Você não pode suportar este gato.}
{70251}{}{Merda, bem no meu joelho!}
{70252}{}{Você não pode me atrasar!}
{70260}{}{Filho da puta me bateu nos olhos!}
{70261}{}{Oh! Eu acho que meu olho esta com um sangramento!}
{70262}{}{Meus olhos!}
{70270}{}{Whoa, não bater abaixo da cintura.}
{70271}{}{Golpe abaixo da virilha não é legal.}
{70272}{}{Hey agora! Fora dos limites da virilha.}
{70273}{}{Este gato não quer ser castrado!}
{70300}{}{Um gato tem que cuidar de si mesmo!}
{70301}{}{Dane-se, dá pena de você.}
{70302}{}{Foda-se, eu vou embora daqui.}
{70303}{}{Preciso de um Jet enquanto eu ainda estou vivo.}
{70304}{}{Você ganhou desta vez, macaco!}
{70320}{}{Não se preocupe, isso vai acabar em breve.}
{70321}{}{Este gato está prestes a atacar!}
{70322}{}{Vamos perder esses ataques.}
{70340}{}{Apresse-se e morra para que eu possa ir tirar um cochilo.}
{70341}{}{Pelo menos eu estou te matando com estilo.}
{70342}{}{Tomara você não sujar minha roupa de sangue.}
{70343}{}{Tomara que eu não quebre a unha.}
{70360}{}{Parece que este gato é muito rápido para você.}
{70361}{}{Agora que é triste.}
{70362}{}{Aqui, Me deixe te mostrar como realmente * bater * em alguma coisa.}
{70363}{}{Inferno, eu quase sinto pena de você. Quase.}
{70400}{}{Ah! Minha cabeça!}
{70401}{}{Eu acho que meu ouvido esta com um sangramento.}
{70402}{}{Cào! Espero não ter quebrado meu nariz.}
{70410}{}{Cào! Meu braço!}
{70411}{}{Maldição, isso dói!}
{70412}{}{Pelo menos ele não está quebrado... Eu não acho.}
{70420}{}{Cào! Meu braço!}
{70421}{}{Maldição, isso dói!}
{70422}{}{Pelo menos ele não está quebrado... Eu não acho.}
{70430}{}{Acho que quebrei uma costela.}
{70431}{}{Eu não vou morrer tão facilmente.}
{70432}{}{Cào! Isso dói!}
{70440}{}{Nem as pernas!}
{70441}{}{Ah! Na canela direita.}
{70442}{}{Isso dói, mas pelo menos eu ainda posso andar.}
{70450}{}{Nem as pernas!}
{70451}{}{Ah! Na canela direita.}
{70452}{}{Isso dói, mas pelo menos eu ainda posso andar.}
{70460}{}{Cào! Meus olhos!}
{70461}{}{Tiro barato!}
{70462}{}{Hey! Eu não posso pagar outra cirurgia do olho!}
{70470}{}{Eu não posso acreditar que você acabou de me bater lá.}
{70471}{}{Eu não sou esse tipo de garota!}
{70472}{}{Você acabou de tornar isso pessoal.}
{70500}{}{Parece que eu não tenho escolha a não ser correr...}
{70501}{}{Eu prefiro fugir do que morrer.}
{70502}{}{Tudo bem. Isso é o suficiente...}
{70520}{}{Vamos acabar com isso.}
{70521}{}{Sua morte virá rapidamente.}
{70522}{}{Parece que chegou sua hora...}
{70540}{}{Você pediu por isso.}
{70541}{}{Não tenho prazer com isso.}
{70542}{}{Agora você vê a conseqüência de suas ações.}
{70560}{}{Uau, isso é patético.}
{70561}{}{Rápido demais para você, não é?}
{70562}{}{Não passou nem perto.}
