{100}{}{You see the Resident Medical Assistant, Phyllis.}
{101}{}{You see a thin young woman. She smells faintly of antiseptic.}
{102}{}{You see RMA Phyllis.}
{103}{}{You see a thin young woman. She smells faintly of antiseptic.}
{104}{}{You risked your own life to save us ALL. You're the bravest person I've ever known.}
{105}{}{An intruder! Aieeeeee! Guards!}
{106}{}{A mutant! Aieeeeee! Guards!}
{107}{}{A ghoul! Aieeeeee! Guards!}
{108}{}{Need to print out Gregory's charts...}
{109}{}{Let's see. We have three Servant inoculations scheduled for 1400...}
{110}{}{All that beeping is driving me crazy...}
{111}{}{I swear those medical databases are talking amongst themselves...}
{112}{}{Let's see... three hypodermics, antiseptic, three ampoules of Rad-X...}
{113}{}{Better prep Dr. Troy on that seminar for tomorrow...}
{114}{}{Yeah, they have me working late AGAIN. Mostly making lists.}
{115}{}{You might want to come back in the morning.}
{116}{}{I think I put you on the list for tomorrow morning, if it's an emergency.}
{117}{}{Can't wait to go home. Making all these lists wears me out.}
{118}{}{It'd be best if you came back in the morning. I have to compile these lists.}
{119}{}{Poor Dr. Troy. He didn't DO anything!}
{120}{}{Why did they exile Dr. Troy?}
{121}{}{I hope Dr. Troy will be all right in the Outworld...}
{122}{}{Hmmph. I'm too busy to speak to you right now. If you need anything, see Dr. Troy.}
{123}{}{Oh! Hello, there. I haven't seen you around before... are you a new Citizen?}
{124}{}{Oh! Hello, again.}
{125}{}{Sit-Zen?}
{126}{}{A-gin?}
{127}{}{Got ouchie... *snfff*... ouchie HURT}
{128}{}{Actually, I'm the new Captain of the Guard.}
{129}{}{Yeah, I just recently got my Citizenship.}
{130}{}{Uh, yeah, I just recently got my Citizenship.}
{131}{}{Sorry, I thought you were someone else. Good day.}
{132}{}{Oh my, you are hurt, aren't you? I'm sorry, I should have been paying more attention. Go see Dr. Troy. He'll take care of you.}
{133}{}{Uh... kay? Yup-yup.}
{134}{}{Could I ask you some questions first?}
{135}{}{Thanks. I'll go see him now.}
{136}{}{Oh! You must be one of the Servants assigned here for the day. You should... uh, hmmm. YOU - GO - MARTIN.}
{137}{}{Uh... hmmm. Listen to me again, closely this time: YOU - GO - MARTIN.}
{138}{}{HUGO MARTIN.}
{139}{}{Got ouchie... *snfff*... ouchie HURT}
{140}{}{Shamble off}
{141}{}{YES, MARTIN. GO - BOTTOM - LEVEL.}
{142}{}{YES, MAR-TIN. GO BOTTOM LEVEL.}
{143}{}{Got ouchie... *snfff*... ouchie HURT}
{144}{}{Shamble off}
{145}{}{GO - BOTTOM - LEVEL. LEVEL - THREE. NOW.}
{146}{}{ME GO BOTTOM LEVEL TREE NOW}
{147}{}{Got ouchie... *snfff*... ouchie HURT}
{148}{}{Shamble off}
{149}{}{Maybe our Servants have some sort of Intelligence Deficiency Syndrome...}
{150}{}{Oh! Well, welcome to Vault City, Captain.}
{151}{}{Well, welcome to Vault City, fellow Citizen.}
{152}{}{We don't see many new faces around here. I'm Phyllis. What's your name?}
{153}{}{My name's }
{154}{}{I'm }
{155}{}{If I wanted to give you my name, I would have told it to you, "Sy-phyllis"... or whatever the hell your name is.}
{156}{}{Sorry, I don't have time to talk right now.}
{157}{}{Why, of all the...! I have NEVER met someone as low-class as yourself. I suggest you leave. Now.}
{158}{}{I suggest you watch that tone of yours, or there's going to be trouble.}
{159}{}{Whatever. I'm done talking to you anyway.}
{160}{}{Guards! Dr. Troy! Help!}
{161}{}{So that's how it's going to be, huh? All right then...}
{162}{}{I'm the Resident Medical Assistant. I work for Dr. Troy.}
{163}{}{What do you think of Dr. Troy?}
{164}{}{Can I ask you some questions?}
{165}{}{Great. I could use some medical assistance.}
{166}{}{Sorry, I don't have time to talk right now.}
{167}{}{Welcome back. Anything I can help you with?}
{168}{}{Of course. What is it you would like to know?}
{169}{}{What do you think of Dr. Troy?}
{170}{}{Can you tell me where the Central Computer is?}
{171}{}{I need some healing.}
{172}{}{What do you do here?}
{173}{}{Can you tell me about Vault City?}
{174}{}{Actually, never mind. Thanks anyway.}
{175}{}{Oh, Dr. Troy can be pretty strict sometimes, but all in all, he's a good man. Vault City's fortunate to have him.}
{176}{}{Well, he asked me to smuggle some drugs into the city for him.}
{177}{}{Can I ask you another question?}
{178}{}{Thanks for your time. Goodbye.}
{179}{}{}
{180}{}{}
{181}{}{Are you certain? That doesn't sound like Dr. Troy at all. Still... he HAS been working hard lately... no, no, that's impossible. You must be mistaken.}
{182}{}{I don't think so. He was very clear about what he wanted.}
{183}{}{Hmmmm. Can I ask you another question?}
{184}{}{Never mind then.}
{185}{}{I would be VERY careful about what you say about Dr. Troy in Vault City. He is a respected member of our community.}
{186}{}{All right, then. Can I ask you another question?}
{187}{}{Thanks for the warning. Maybe I should go talk to someone else.}
{188}{}{It's down on the 3rd level, if I remember correctly. Haven't been down there in ages.}
{189}{}{Why not?}
{190}{}{Can I ask you another question?}
{191}{}{Thanks for the directions. Goodbye.}
{192}{}{Oh, I don't know. Not much reason to go down into the Vault. It's mostly used for storage space nowadays. The only one down there is Martin, and... well, just between you and me, he's not a great conversationalist.}
{193}{}{Uhh.... Why did they make him conversationalist if he's no good at his job?}
{194}{}{Can I ask you another question?}
{195}{}{I see. Thanks for the information.}
{196}{}{Uh... maybe you SHOULD go speak to him. You two may have more in common than I first thought.}
{197}{}{Can I ask you another question first?}
{198}{}{All right then. I'll go speak to him.}
{199}{}{Vault City? Well, actually, there's not much to say. I mean, I've been a Citizen all my life... but there's not much to do in Vault City. At all.}
{200}{}{It seems a shame that a beautiful young woman such as yourself can't find SOMETHING to do in Vault City.}
{201}{}{Nothing at all? Come on.}
{202}{}{Can I ask you another question...}
{203}{}{Oh, well. Just thought I'd ask.}
{204}{}{Look, I know you're a new Citizen and all, and I don't mean to throw a damper on your Citizenship, but this City can be VERY dull at times.}
{205}{}{Dull? How so?}
{206}{}{That's too bad. I had some other questions...}
{207}{}{Oh, well. Sorry to hear it.}
{208}{}{I mean, have you noticed how similar everyone is? And OLD? Most of the seminars and extracurricular activities are geared towards octogenarians. I'm barely twenty-five, and this city makes me feel like I'm fifty.}
{209}{}{Uh... octo-genarians? You mean the guards?}
{210}{}{Speaking of old, I noticed there aren't any children in the city.}
{211}{}{I DID notice the similarity of Citizens.}
{212}{}{Oh, well. Just thought I'd ask.}
{213}{}{Uh no... "octogenarian" is an adjective that refers to a person who is eighty years old. }
{214}{}{Uh, okay. Can I ask you another question?}
{215}{}{All right then. Maybe we'll speak later.}
{216}{}{Well... yes. Actually, there aren't. Yet. I don't know if anyone told you yet, Vault City is a planned community. We're not due for another pregnancy cycle until a few years from now.}
{217}{}{Uh... a pregnancy cycle?}
{218}{}{Can I ask you another question?}
{219}{}{I see. Well, thanks for the information.}
{220}{}{Yes. Pregnancies are permitted only during certain years established by the Council.}
{221}{}{What if you get pregnant anyway?}
{222}{}{Oh. I had some other questions...}
{223}{}{I see. Well, thanks for the information.}
{224}{}{How would that happen?}
{225}{}{Uh, last I heard, SEX can make someone pregnant.}
{226}{}{Forget I asked. Look, I had some other questions...}
{227}{}{Never mind. I better be going.}
{228}{}{Oh, you mean intercourse? Intercourse is still allowed outside of pregnancy cycles.}
{229}{}{Doesn't that make people pregnant?}
{230}{}{Oh. I had some other questions...}
{231}{}{Oh, well. Just thought I'd ask.}
{232}{}{Oh, no, no... you see, our pregnancies don't result from intercourse.}
{233}{}{I'm afraid to ask. But I will anyway.}
{234}{}{I don't want to know any more. I had some other questions, though...}
{235}{}{I think I've heard enough.}
{236}{}{Male Citizens "donate" to the Auto-Doc here in the Vault and the most favorable matches are chosen by the computer. Then the appropriate female Citizen is seeded by the Auto-Doc.}
{237}{}{Can I donate?}
{238}{}{Don't people still get pregnant from intercourse? What about accidental pregnancies?}
{239}{}{You know, I would very much like to ask you any other question right now.}
{240}{}{Would you excuse me? I'm going to go see if I can get my Citizenship revoked.}
{241}{}{I think I'm going to go somewhere and be violently ill. Goodbye.}
{242}{}{Certainly. We'd welcome your contribution. Vault City could use some fresh genetic material.}
{243}{}{All right then...}
{244}{}{Say, could I get a magazine or something?}
{245}{}{Your contribution is impressive... you yourself seem to be quite gifted. How do you feel?}
{246}{}{Excellent! Thank you.}
{247}{}{Hmmm. Maybe your contribution wasn't as valuable as I thought. Thanks anyway, though.}
{248}{}{I can honestly say I have never missed the primitive charm of Arroyo more until this moment.}
{249}{}{I have never felt the need to be held more than at this moment.}
{250}{}{No, thank YOU.}
{251}{}{Well, actually... you see, this is something I've been thinking about recently, but Citizens don't seem to have accidental pregnancies. The only successful pregnancies have been facilitated by the Auto-Doc.}
{252}{}{You know, background radiation might be resulting in sterility or even worse, chromosomal damage. Might be worth checking out.}
{253}{}{Maybe it's just because they don't have much real sex around here.}
{254}{}{Oh, well. Just thought I'd ask.}
{255}{}{You know, I was thinking the same thing. Maybe I should mention it to Dr. Troy. He's been too busy to look into it recently, but the next pregnancy cycle IS coming up, so...}
{256}{}{Can I ask you some other questions?}
{257}{}{Mentioning it to Dr. Troy would be a good idea. Good luck.}
{258}{}{It's like they're all... clones. They all dress alike, act alike, and the worst part is that everybody seems happy with it. I... well, sometimes I worry that I'll end up being just like them. That probably sounds silly, huh?}
{259}{}{Not at all. Pressure to conform must be pretty rough around here, especially considering how insular a community Vault City is.}
{260}{}{Oh, well. Just thought I'd ask.}
{261}{}{Yeah, it can get kind of overwhelming at times. But here I am, bringing down your opinion of Vault City. Don't misunderstand me. It's a great place to live.}
{262}{}{Just a suggestion, but you might want to travel a little outside of Vault City. Even speak to some of the merchants in the Courtyard. They might be able to broaden your horizons a little.}
{263}{}{It's got its advantages, no doubt. Can I ask you some other questions?}
{264}{}{Glad you're happy here. Maybe we'll speak again.}
{265}{}{Well, I've been tempted to go outside the gate, but the other Citizens have warned me against it...}
{266}{}{That's just another reason to do it. You don't want to do what the OTHER Citizens do, do you? They're all set in their ways.}
{267}{}{Well, it can be dangerous out there. Say, can I ask you another question?}
{268}{}{They're right. It's probably not a good idea. I better be going.}
{269}{}{You know, you're right. Maybe I will step outside the gate when I get the chance. I'd like to know more about the outside world.}
{270}{}{Great. Say, can I ask you another question?}
{271}{}{It'll be good for you. Take care.}
{272}{}{Pardon me?}
{273}{}{I couldn't help but notice you're an attractive young woman who could stand to get out once in a while. How about you and I have dinner?}
{274}{}{Never mind. Can I ask you another question?}
{275}{}{Oh, well. Just thought I'd ask.}
{276}{}{Oh. I... you know, I'd love to, but I can't.}
{277}{}{Oh. Well, I... I'd love to.}
{278}{}{Aw, c'mon. I'm new. I'll get into trouble if I go around by myself.}
{279}{}{All right. Can I ask you some questions then?}
{280}{}{Oh, well. Just thought I'd ask.}
{281}{}{Great! Let's go.}
{282}{}{Thanks for the wonderful evening.}
{283}{}{Uh... sure. Maybe we'll go out some other time. I'll... uh, call you. Bye.}
{284}{}{I'm sorry, but no.}
{285}{}{All right. Can I ask you some questions instead?}
{286}{}{Oh, well. Just thought I'd ask.}
{287}{}{Well, it's good to see same-sex prejudice is alive and well in Vault City. Bye.}
{288}{}{. What do you do around here?}
{289}{}{. Mind if I ask you some questions?}
{290}{}{Oh well, I thought there weren't any children because this might be the European version of Fallout 2. Goodbye.}
{291}{}{You have given Vault City a donation and introduced favorable genetic material into their community.}
{292}{}{You have given Vault City a donation and introduced fresh genetic material into their community.}
{293}{}{You have given Vault City a donation... for whatever it's worth.}
{294}{}{You have convinced Phyllis to speak to Dr. Troy about the potential sterility in Vault City.}
{295}{}{You have convinced Phyllis to see the outside world.}
{296}{}{You quickly discover Phyllis is rather dull and self-centered. You resolve never to date anyone like her again.}
{297}{}{Speaking of octo-generic- uh, octo-ians, uh, old people, I noticed there aren't any children in Vault city.}
