{100}{}{Widzisz nagrobek.}
{101}{}{Na nagrobku jest napisane: }
{102}{}{"Tu le¿y Brat Grzegorz. Cz³owiek, który nie zna³ granic."}
{103}{}{"Ciotka Patty. W istocie, dziêki Bogu."}
{104}{}{"Tu le¿y Piotr J¹dro. Zgin¹³ z powodu rozszczepienia jednego."}
{105}{}{"Tu le¿y ojciec Micha³. Za³o¿yciel, Ojciec, Wojownik."}
{106}{}{"Ateista. Wystrojony, ale nie ma dok¹d pójœæ."}
{107}{}{"Tu le¿y Jaœ Dro¿d¿e. Wybaczcie mi, ¿e nie rosnê."}
{108}{}{"Mary Jane. Kochaj¹ca ¿ona i matka."}
{109}{}{"'Szach mat!' by³o zawo³aniem starego dobrego Jana. Na szachownicy ¿ycia by³ tylko pionkiem.}
{110}{}{"Sir Jan Dziwny, tu le¿y uczciwy prawnik i to jest dziwne."}
{111}{}{"£zy jej nie wskrzesz¹ - dlatego p³aczê."}
{112}{}{"Ka¿dego dnia i w ka¿dy sposób, staje siê coraz lepszy."}
{250}{}{Nie ma ¿adnego napisu na tym nagrobku.}
{251}{}{Nagrobek jest zbyt zniszczony ¿eby odczytaæ inskrypcje.}
{252}{}{Nazwisko na nagrobku Zbyszek Nowak.}
{253}{}{Napis na tym nagrobku zosta³ zatarty przez pogodê.}
