{100}{}{Widzisz pompê wodn¹.}
{101}{}{Widzisz naprawdê star¹ pompê wodn¹. Wygl¹da na zepsut¹.}
{102}{}{Pompa wodna jest ju¿ sprawna.}
{103}{}{Go³ymi rêkoma nie naprawisz tej maszyny. Mo¿e jakieœ narzêdzia pomog¹ w zainstalowaniu tej czêœci.}
{104}{}{Naprawiasz pompê wodn¹.}
{105}{}{Nie uda³o ci siê naprawiæ pompy.}
{106}{}{Ju¿ wiesz co jest nie tak z t¹ pomp¹ wodn¹.}
{200}{}{Podnosisz klapê i zagl¹dasz do maszyny. Widzisz du¿o pordzewia³ych zêbatek i przek³adni. Jeden z silników jest pêkniêty.}
{201}{}{Mam doœæ.}
{202}{}{Musisz siê jeszcze nad tym zastanowiæ.}
{203}{}{Po dok³adniejszych oglêdzinach zauwa¿asz, ¿e pêkniêcie silnika nie jest jedyn¹ przyczyn¹ problemów z pomp¹, jest te¿ problem ze z³¹czami na przewodach. Styki popali³y siê w ci¹gu tych wszystkich lat pracy. Do naprawy tej maszyny bêd¹ potrzebne nowy silnik i zestaw kabli.}
{204}{}{WyjdŸ.}
