{100}{}{Widzisz mieszkańca wioski.}
{101}{}{Widzisz mieszkankę wioski.}
{150}{}{Jedna z osób zamieszkujących Arroyo.}
{151}{}{[ROZMAWIAJ]}
{152}{}{Witaj! Podobno jesteś Dzieckiem Przeznaczenia. Może teraz nasza wioska ma szanse na ocalenie.}
{153}{}{Czy możesz mi powiedzieć, gdzie znajdę proszek leczniczy?}
{154}{}{Co możesz powiedzieć o handlarzach, którzy nas odwiedzają?}
{155}{}{Miło było cię widzieć, ale muszę iść.}
{156}{}{Niech bogowie chronią cię w twej podróży.}
{157}{}{Mam do ciebie kilka pytań.}
{158}{}{Żegnaj.}
{159}{}{Porozmawiaj z Hakuninem w północnej części wioski. On może ci pomóc.}
{160}{}{Dziękuję. Do widzenia.}
{161}{}{Och, ja nie zajmuję się handlem z kupcami. Porozmawiaj z Mynokiem, strażnikiem Wielkiego Mostu. On z nimi rozmawia.}
{162}{}{Dziękuję. Do widzenia.}
{163}{}{Czy możesz mi powiedzieć, gdzie znajduje się Wielki Most?}
{164}{}{Mam kilka pytań, jeżeli pozwolisz.}
{165}{}{Dobry dowcip, Dziecko! Przecież wiesz, że jest on na południe stąd.}
{166}{}{Dziękuję. Do widzenia.}
{167}{}{Mam kilka pytań, jeżeli pozwolisz.}
{168}{}{Oczywiście, co chcesz wiedzieć?}
{169}{}{Czy możesz mi powiedzieć, gdzie znajdę trochę leczniczych ziół?}
{170}{}{Co możesz powiedzieć o handlarzach, którzy nas odwiedzają?}
{171}{}{Nieważne.}
{172}{}{Och, bogowie - niech duch Założyciela cię prowadzi. Jeśli to ty jesteś Dzieckiem Przeznaczenia, będziemy potrzebować dużo szczęścia.}
{173}{}{Uun Ga.}
{174}{}{Bezpiecznej podróży.}
{175}{}{????}
{176}{}{Jesteśmy zgubieni! Przez twoją nieudolność wioska jest zgubiona.}
{177}{}{Nie możesz pozostać wśród nas.}
{180}{}{Twoja zdrada zgubi nasz lud.}
{181}{}{Dlaczego to robisz?}
{182}{}{Widzę zło w twych oczach. Dziecko Przeznaczenia jest złe!}
{183}{}{Przychodzą do naszej wioski ze wschodu, ale ich towary są nędzne.}
{184}{}{Czy możesz mi powiedzieć, gdzie znajdę trochę leczniczych ziół?}
{185}{}{Dziękuję. Do widzenia.}
{186}{}{Mam kilka pytań, jeżeli pozwolisz.}
{300}{}{Witaj, Dziecko Przeznaczenia. Miło cię znów widzieć. Mam nadzieję, że twa święta misja przebiega pomyślnie. Czy mogę ci w czymś pomóc?}
{301}{}{Dziecko, nasz lud umiera. Musisz się pośpieszyć i odnaleźć święty GECK. Jak mogę ci pomóc w tej najważniejszej z misji?}
{302}{}{Nie mamy wiele czasu, Dziecko. Proszę, skończ swą misję jak najszybciej. Nie możemy długo czekać. Jeśli mogę ci jakoś pomóc w ocaleniu wioski, daj mi znać.}
{303}{}{Dziecko, nasza wioska jest już niemal wymarła... jesteś naszą jedyną nadzieją. Czy mogę ci jakoś dopomóc w twojej misji?}
{400}{}{Czy możesz mi cokolwiek powiedzieć o Kadze?}
{401}{}{[Gapi się na ciebie, szeroko otwartymi oczyma, poczym powoli odchodzi  nerwowo się rozglądając.]}
{402}{}{Czyli, nie. Rozumiem.}
{1000}{}{Starsza}
{1001}{}{Założyciel}
{1002}{}{Przybysz z Krypty}
{1003}{}{Arroyo}
{1004}{}{Klamath}
{1005}{}{Krypta}
{1006}{}{Dziecko Przeznaczenia}
{1007}{}{Szaman}
{1008}{}{Hakunin}
{1009}{}{Proszek Leczniczy}
{1010}{}{Most}
{1011}{}{Mynoc}
{1100}{}{Starsza jest naszą matką i przywódczynią.}
{1101}{}{To nasz wielki przodek, który dał nam wiedzę.}
{1102}{}{Pierwszy, który walczył i zwyciężył chaos.}
{1103}{}{To jest nasza piękna wioska.}
{1104}{}{To miasto handlowe leżące kilka dni na wschód stąd.}
{1105}{}{Krypta jest rajem.}
{1106}{}{Ty jesteś Dzieckiem Przeznaczenia.}
{1107}{}{Leczy nas magią i ziołami. Mieszka w północnej części naszej wioski.}
{1108}{}{Leczy nas magią i ziołami. Mieszka w północnej części naszej wioski.}
{1109}{}{To magiczny proszek, który cię wyleczy, lecz uspi twe zmysly.}
{1110}{}{Wielki Most stanowi wyjście z naszej wioski od południa.}
{1111}{}{Mynoc strzeże mostu prowadzącego do naszej wioski.}
