{100}{}{Widzisz terminal komputerowy.}
{101}{}{Widzisz terminal centrum kontroli.}
{102}{}{Widzisz standardowy terminal komputerowy. Wygl¹da na to, ¿e jest w pe³ni sprawny i oczekuje na komendy.}
{103}{}{Ze wskazañ terminalu wynika, ¿e pole si³owe zabezpieczaj¹ce wejœcie do krypty zosta³o uaktywnione wraz z przywróceniem zasilania.}
{104}{}{Ze wskazañ terminalu wynika, ¿e wszystkie systemy bezpieczeñstwa s¹ wy³¹czone z powodu awarii zasilania.}
{105}{}{Wy³¹cz pole si³owe.}
{106}{}{W³¹cz pole si³owe.}
{107}{}{Koniec.}
{108}{}{Wydajesz komendê wy³¹czenia pola si³owego.}
{109}{}{Koniec.}
{110}{}{Wydajesz komendê w³¹czenia pola si³owego.}
{111}{}{Koniec.}
{112}{}{Ze wskazañ terminala wynika, ¿e pole zosta³o rêcznie wy³¹czone.}
{113}{}{Ze wskazañ terminala wynika, ¿e system wytwarzaj¹cy pole zosta³ naruszony przez si³y obce.}
{114}{}{Ze wskazañ terminala wynika, ¿e system wytwarzaj¹cy pole jest wy³¹czony.}
