{100}{}{Widzisz drewniane drzwi.}
{101}{}{Widzisz metalowe drzwi.}
{102}{}{Widzisz solidne drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e silny ³adunek wybuchowy we framudze. Mo¿esz spróbowaæ je wywa¿yæ.}
{103}{}{Widzisz solidne drzwi zamkniête na zamek i chronione ³adunkiem wybuchowym ukrytym we framudze. Mo¿e uda ci siê je sforsowaæ.}
{104}{}{Widzisz solidne drzwi bez widocznego zamka. S¹ chronione ³adunkiem wybuchowym ukrytym we framudze. Mo¿e uda ci siê je sforsowaæ.}
{105}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek i chronione ³adunkiem wybuchowym ukrytym we framudze. Mo¿e uda ci siê je sforsowaæ.}
{106}{}{Widzisz solidne drzwi zamkniête na zamek (który mo¿esz otworzyæ wytrychem) i chronione pu³apk¹ ukryt¹ we framudze. Mo¿e uda ci siê je sforsowaæ.}
{107}{}{Widzisz solidne drzwi zamkniête na zamek i chronione pu³apk¹ ukryt¹ we framudze. Mo¿e uda ci siê je sforsowaæ.}
{108}{}{Widzisz solidne drzwi bez widocznego zamka. S¹ chronione pu³apk¹ ukryt¹ we framudze. Mo¿e uda ci siê je sforsowaæ.}
{109}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek i chronione pu³apk¹ ukryt¹ we framudze. Mo¿e uda ci siê je sforsowaæ.}
{110}{}{Widzisz solidne drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e przeciêty kabel we framudze. Mo¿esz spróbowaæ je wywa¿yæ.}
{111}{}{Widzisz solidne drzwi zamkniête na zamek. Dostrzegasz przerwany drut we framudze drzwi. Mo¿e uda ci siê je sforsowaæ.}
{112}{}{Widzisz solidne drzwi bez widocznego zamka. Dostrzegasz przerwany drut we framudze drzwi. Mo¿e uda ci siê je sforsowaæ.}
{113}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek. Dostrzegasz przeciêty drut we framudze drzwi. Mo¿e uda ci siê je sforsowaæ.}
{114}{}{Widzisz solidne drzwi zamkniête na zamek (który mo¿esz otworzyæ wytrychem). Mo¿e uda ci siê je sforsowaæ.}
{115}{}{Widzisz solidne drzwi zamkniête na zamek. Mo¿e uda ci siê je sforsowaæ.}
{116}{}{Widzisz solidne drzwi bez widocznego zamka. Mo¿e uda ci siê je sforsowaæ.}
{117}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek. Mo¿e uda ci siê je sforsowaæ.}
{118}{}{Widzisz solidne drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e silny ³adunek wybuchowy we framudze.}
{119}{}{Widzisz solidne drzwi zamkniête na zamek i chronione ³adunkiem wybuchowym ukrytym we framudze.}
{120}{}{Widzisz solidne drzwi bez widocznego zamka. S¹ chronione ³adunkiem wybuchowym ukrytym we framudze.}
{121}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek i chronione ³adunkiem wybuchowym ukrytym we framudze.}
{122}{}{Widzisz solidne drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e jak¹œ pu³apkê we framudze.}
{123}{}{Widzisz solidne drzwi zamkniête na zamek i chronione pu³apk¹ ukryt¹ we framudze.}
{124}{}{Widzisz solidne drzwi bez widocznego zamka. S¹ chronione pu³apk¹ ukryt¹ we framudze.}
{125}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek i chronione pu³apk¹ ukryt¹ we framudze.}
{126}{}{Widzisz solidne drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e przeciêty kabel we framudze.}
{127}{}{Widzisz solidne drzwi zamkniête na zamek. Dostrzegasz przerwany drut we framudze drzwi.}
{128}{}{Widzisz solidne drzwi bez widocznego zamka. Dostrzegasz przerwany drut we framudze drzwi.}
{129}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek. Dostrzegasz przeciêty drut we framudze drzwi.}
{130}{}{Widzisz solidne drzwi z zamkiem, który mo¿na by otworzyæ wytrychami.}
{131}{}{Widzisz solidne drzwi zamkniête na zamek.}
{132}{}{Widzisz solidne drzwi bez widocznego zamka.}
{133}{}{Widzisz solidne drzwi zamkniête na stary, pordzewia³y zamek.}
{134}{}{Widzisz uszkodzone drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e silny ³adunek wybuchowy we framudze.}
{135}{}{Widzisz uszkodzone drzwi zamkniête na zamek i chronione ³adunkiem wybuchowym ukrytym we framudze.}
{136}{}{Widzisz uszkodzone drzwi bez widocznego zamka. S¹ chronione ³adunkiem wybuchowym ukrytym we framudze.}
{137}{}{Widzisz uszkodzone drzwi zamkniête na stary, pordzewia³y zamek i chronione ³adunkiem wybuchowym ukrytym we framudze.}
{138}{}{Widzisz uszkodzone drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e jak¹œ pu³apkê we framudze.}
{139}{}{Widzisz uszkodzone drzwi zamkniête na zamek i chronione pu³apk¹ ukryt¹ we framudze.}
{140}{}{Widzisz uszkodzone drzwi bez widocznego zamka. S¹ chronione pu³apk¹ ukryt¹ we framudze.}
{141}{}{Widzisz uszkodzone drzwi zamkniête na stary, pordzewia³y zamek i chronione pu³apk¹ ukryt¹ we framudze.}
{142}{}{Widzisz uszkodzone drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e przeciêty kabel we framudze.}
{143}{}{Widzisz uszkodzone drzwi zamkniête na zamek. Dostrzegasz przerwany drut we framudze drzwi.}
{144}{}{Widzisz uszkodzone drzwi bez widocznego zamka. Dostrzegasz przerwany drut we framudze drzwi.}
{145}{}{Widzisz uszkodzone drzwi zamkniête na stary, pordzewia³y zamek. Dostrzegasz przeciêty drut we framudze drzwi.}
{146}{}{Widzisz uszkodzone drzwi z zamkiem, który mo¿na by otworzyæ wytrychami.}
{147}{}{Widzisz uszkodzone drzwi zamkniête na zamek.}
{148}{}{Widzisz uszkodzone drzwi bez widocznego zamka.}
{149}{}{Widzisz uszkodzone drzwi zamkniête na stary, pordzewia³y zamek.}
{150}{}{Widzisz stare drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e silny ³adunek wybuchowy we framudze.}
{151}{}{Widzisz stare drzwi zamkniête na zamek i chronione ³adunkiem wybuchowym ukrytym we framudze.}
{152}{}{Widzisz stare drzwi bez widocznego zamka. S¹ chronione ³adunkiem wybuchowym ukrytym we framudze.}
{153}{}{Widzisz stare drzwi zamkniête na pordzewia³y zamek i chronione ³adunkiem wybuchowym ukrytym we framudze.}
{154}{}{Widzisz stare drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e jak¹œ pu³apkê we framudze.}
{155}{}{Widzisz stare drzwi zamkniête na zamek i chronione pu³apk¹ ukryt¹ we framudze.}
{156}{}{Widzisz stare drzwi bez widocznego zamka. S¹ chronione pu³apk¹ ukryt¹ we framudze.}
{157}{}{Widzisz stare drzwi zamkniête na pordzewia³y zamek i chronione pu³apk¹ ukryt¹ we framudze.}
{158}{}{Widzisz stare drzwi z zamkiem, który mo¿na by otworzyæ wytrychami, a tak¿e przeciêty kabel we framudze.}
{159}{}{Widzisz stare drzwi zamkniête na zamek. Dostrzegasz przerwany drut we framudze drzwi.}
{160}{}{Widzisz stare drzwi bez widocznego zamka. Dostrzegasz przerwany drut we framudze drzwi.}
{161}{}{Widzisz stare drzwi zamkniête na pordzewia³y zamek. Dostrzegasz przerwany drut we framudze drzwi.}
{162}{}{Widzisz stare drzwi z zamkiem, który mo¿na by otworzyæ wytrychami.}
{163}{}{Widzisz stare drzwi zamkniête na zamek.}
{164}{}{Widzisz stare drzwi bez widocznego zamka.}
{165}{}{Widzisz stare drzwi zamkniête na pordzewia³y zamek.}
{166}{}{Uaktywniasz pu³apkê i odnosisz }
{167}{}{ punktów obra¿eñ.}
{168}{}{ uaktywnia pu³apkê i odnosi }
{169}{}{ punktów obra¿eñ.}
{170}{}{Zrêcznie otwierasz zamek na drzwiach.}
{171}{}{Przez twój brak umiejêtnoœci zamek zosta³ powa¿nie uszkodzony.}
{172}{}{Nie uda³o ci siê otworzyæ drzwi.}
{173}{}{ zrêcznie otwiera drzwi.}
{174}{}{ nieporadnie poczyna sobie z zamkiem i wreszcie go psuje.}
{175}{}{ nie mo¿e otworzyæ drzwi.}
{176}{}{Wy³amujesz zamek z drzwi.}
{177}{}{W trakcie wy³amywania zamka nadwyrê¿asz sobie krêgos³up i otrzymujesz punkt obra¿eñ.}
{178}{}{W trakcie wy³amywania zamka nadwyrê¿asz sobie krêgos³up i otrzymujesz }
{179}{}{ punktów obra¿eñ.}
{180}{}{Brakuje ci si³, ¿eby wy³amaæ ten zamek.}
{181}{}{ wy³amuje zamek z drzwi.}
{182}{}{ nadwerê¿a siê próbuj¹c wy³amaæ zamek z drzwi i odnosi jeden punkt obra¿eñ.}
{183}{}{ nadwerê¿a siê próbuj¹c wy³amaæ zamek i odnosi }
{184}{}{ punktów obra¿eñ.}
{185}{}{ nie ma doœæ si³ by wy³amaæ zamek.}
{186}{}{ nadwerê¿a siê próbuj¹c wy³amaæ zamek i odnosi jeden punkt obra¿eñ.}
{187}{}{ nadwerê¿a siê próbuj¹c wy³amaæ zamek i odnosi }
{188}{}{ punktów obra¿eñ.}
{189}{}{Zrêcznie zamykasz drzwi.}
{190}{}{Nie uda³o ci siê zamkn¹æ drzwi.}
{191}{}{ zrêcznie zamyka drzwi.}
{192}{}{ nie mo¿e zamkn¹æ drzwi.}
{193}{}{£adunki wybuchowe nawet nie zarysowa³y powierzchni tych drzwi.}
{194}{}{Odkrywasz pu³apkê na drzwiach.}
{195}{}{Nie widzisz ¿adnej pu³apki.}
{196}{}{Sprawnie rozbrajasz pu³apkê.}
{198}{}{Nie uda³o ci siê rozbroiæ pu³apki.}
{199}{}{ znajduje pu³apkê na drzwiach.}
{200}{}{ nie widzi ¿adnej pu³apki.}
{201}{}{ sprawnie rozbraja pu³apkê.}
{202}{}{ nie mo¿e rozbroiæ pu³apki.}
{203}{}{Drzwi wygl¹daj¹ na zamkniête. Wydaje siê, ¿e u¿ywaj¹ jakichœ cienkich kart jako kluczy.}
{204}{}{S³yszysz trzaski elektrycznoœci p³yn¹cej przez drzwi.}
{205}{}{ zauwa¿a trzaski elektrycznoœci p³yn¹cej przez drzwi.}
{206}{}{Nie udaje ci siê za³o¿yæ pu³apki w tych drzwiach, gdy¿ s¹ one otwarte.}
{207}{}{ zawodzi przy zak³adaniu pu³apki w tych drzwiach, gdy¿ s¹ one otwarte.}
{208}{}{Sprawnie umieszczasz pu³apkê na drzwiach.}
{209}{}{Nie udaje ci siê za³o¿yæ prawid³owo pu³apki we framudze drzwi.}
{210}{}{ sprawnie umieszcza pu³apkê na drzwiach.}
{211}{}{ zawodzi przy zak³adaniu poprawnie pu³apki we framudze drzwi.}
{300}{}{Otwierasz drzwi.}
{301}{}{Zamykasz drzwi.}
{302}{}{Nie mo¿esz zamkn¹æ na klucz otwartych drzwi!}
{303}{}{Ten klucz nie pasuje do zamka.}
{320}{}{Nie mo¿na zamkn¹æ tych drzwi na klucz.}
{400}{}{Otwierasz drzwi.}
{500}{}{Nie ma sposobu, aby zdj¹æ pu³apkê z tych drzwi.}
