{100}{}{Widzisz technika.}
{101}{}{Widzisz technika komputerowego.}
{102}{}{Widzisz osobê ubran¹ w fartuch laboratoryjny, uzupe³niony zestawem zapasowych d³ugopisów.}

{103}{}{Dzieñ dobry, ¿o³nierzu.}
{104}{}{Proszê niczego nie dotykaæ.}
{105}{}{Wy, ¿o³daki, nie powinniœcie siê tu krêciæ.}

{106}{}{Nie masz na sobie munduru. }
{107}{}{Lepiej siê przebierz. Zbrojownia mieœci siê na koñcu korytarza, po lewej.}
{108}{}{Du¿o ryzykujesz w³a¿¹c tu bez munduru. Lepiej zg³oœ siê do zaopatrzenia.}

{109}{}{Coœcie u licha za jedni... Alarm! Intruzi!}
{110}{}{Zostaliœmy zinfiltrowani! Alarm!}
{111}{}{Liczni intruzi! Oglosiæ alarm!}

{112}{}{Cholera. Za³adujcie kopiê rezerwow¹.}
{113}{}{Pozamykaæ wszystkie zastrze¿one procesy.}
{114}{}{Zabezpieczyæ system i w³¹czyæ wszystkie has³a.}

{115}{}{Jestem naukowcem, a nie ¿o³nierzem!}
{116}{}{Ostry koniec z dioda laserow¹ skierowaæ na przeciwnika. Poci¹gn¹æ za spust.}
{117}{}{Pomocy! Pomocy! Niebezpieczeñstwo w pracowni komputerowej!}
