#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: September 26, 1997                              #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc
{100}{}{Widzisz drewnian¹ skrzynkê.}
{101}{}{Widzisz metalowy schowek.}
{212}{}{Widzisz lodówkê.}

# description_proc

# Perception Check Critical Success
{102}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy pomocy wytrychów) i ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}
{103}{}{Widzisz solidny pojemnik z zamkiem i ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}
{104}{}{Widzisz solidny pojemnik bez widocznego zamka i z ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}
{105}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek i z ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}

{106}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}
{107}{}{Widzisz solidny pojemnik z zamkiem i ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}
{108}{}{Widzisz solidny pojemnik bez widocznego zamka i z ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}
{109}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek i z ukryt¹ pu³apk¹, który mo¿esz byæ w stanie otworzyæ.}

{110}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i z przeciêtym kablem na obudowie, który móg³byœ otworzyæ.}
{111}{}{Widzisz solidny pojemnik z zamkiem i z przeciêtym kablem na obudowie, który móg³byœ otworzyæ.}
{112}{}{Widzisz solidny pojemnik bez widocznego zamka i z przeciêtym kablem na obudowie, który móg³byœ otworzyæ.}
{113}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek i z przeciêtym kablem na obudowie, który móg³byœ otworzyæ.}

{114}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów), który móg³byœ otworzyæ.}
{115}{}{Widzisz solidny pojemnik z zamkiem, który móg³byœ otworzyæ.}
{116}{}{Widzisz solidny pojemnik, bez widocznego zamka, który móg³byœ otworzyæ.}
{117}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek, który móg³byœ otworzyæ.}

# Perception Check Success

{118}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{119}{}{Widzisz solidny pojemnik z zamkiem i z bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{120}{}{Widzisz solidny pojemnik bez widocznego zamka z bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{121}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek z bardzo niebezpieczn¹ pu³apk¹ na obudowie.}

{122}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i z pu³apk¹ na obudowie.}
{123}{}{Widzisz solidny pojemnik z zamkiem i pu³apk¹ na obudowie.}
{124}{}{Widzisz solidny pojemnik bez widocznego zamka i z pu³apk¹ na obudowie.}
{125}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek z pu³apk¹ na obudowie.}

{126}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i przeciêtym kablem na obudowie.}
{127}{}{Widzisz solidny pojemnik z zamkiem i przeciêtym kablem na obudowie.}
{128}{}{Widzisz solidny pojemnik bez widocznego zamka i przeciêtym kablem na obudowie.}
{129}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek i przeciêtym kablem na obudowie.}

{130}{}{Widzisz solidny pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów).}
{131}{}{Widzisz solidny pojemnik z zamkiem.}
{132}{}{Widzisz solidny pojemnik bez widocznego zamka.}
{133}{}{Widzisz solidny pojemnik zamkniêty na stary, zardzewia³y zamek.}

# Perception Check Critical Failure

{134}{}{Widzisz zniszczony pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{135}{}{Widzisz zniszczony pojemnik z zamkiem i bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{136}{}{Widzisz zniszczony pojemnik bez widocznego zamka, z bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{137}{}{Widzisz zniszczony pojemnik zamkniêty na stary, zardzewia³y zamek, z bardzo niebezpieczn¹ pu³apk¹ na obudowie.}

{138}{}{Widzisz zniszczony pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i z pu³apk¹ na obudowie.}
{139}{}{Widzisz zniszczony pojemnik z zamkiem i pu³apk¹ na obudowie.}
{140}{}{Widzisz zniszczony pojemnik bez widocznego zamka, z pu³apk¹ na obudowie.}
{141}{}{Widzisz zniszczony pojemnik zamkniêty na stary, zardzewia³y zamek, z pu³apk¹ na obudowie.}

{142}{}{Widzisz zniszczony pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów) i przeciêtym kablem na obudowie.}
{143}{}{Widzisz zniszczony pojemnik z zamkiem i przeciêtym kablem na obudowie.}
{144}{}{Widzisz zniszczony pojemnik bez widocznego zamka i przeciêtym kablem na obudowie.}
{145}{}{Widzisz zniszczony pojemnik zamkniêty na stary, zardzewia³y zamek i przeciêtym kablem na obudowie.}

{146}{}{Widzisz zniszczony pojemnik z zamkiem (który mo¿na otworzyæ przy u¿yciu wytrychów).}
{147}{}{Widzisz zniszczony pojemnik z zamkiem.}
{148}{}{Widzisz zniszczony pojemnik bez widocznego zamka.}
{149}{}{Widzisz zniszczony pojemnik zamkniêty na stary, zardzewia³y zamek.}

# Perception Check Failure

{150}{}{Widzisz stary pojemnik z zamkiem [który mo¿na otworzyæ przy u¿yciu wytrychów] i bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{151}{}{Widzisz stary pojemnik z zamkiem i bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{152}{}{Widzisz stary pojemnik bez widocznego zamka i z bardzo niebezpieczn¹ pu³apk¹ na obudowie.}
{153}{}{Widzisz stary pojemnik zamkniêty na stary, zardzewia³y zamek z bardzo niebezpieczn¹ pu³apk¹ na obudowie.}

{154}{}{Widzisz stary pojemnik z zamkiem [który mo¿na otworzyæ przy u¿yciu wytrychów] i z pu³apk¹ na obudowie.}
{155}{}{Widzisz stary pojemnik z zamkiem i z pu³apk¹ na obudowie.}
{156}{}{Widzisz stary pojemnik bez widocznego zamka i z pu³apk¹ na obudowie.}
{157}{}{Widzisz stary pojemnik zamkniêty na stary, zardzewia³y zamek i z pu³apk¹ na obudowie.}

{158}{}{Widzisz stary pojemnik z zamkiem [który mo¿na otworzyæ przy u¿yciu wytrychów] i przeciêtym kablem na obudowie.}
{159}{}{Widzisz stary pojemnik z zamkiem i przeciêtym kablem na obudowie.}
{160}{}{Widzisz stary pojemnik bez widocznego zamka i przeciêtym kablem na obudowie.}
{161}{}{Widzisz stary pojemnik zamkniêty na stary, zardzewia³y zamek i przeciêtym kablem na obudowie.}

{162}{}{Widzisz stary pojemnik z zamkiem [który mo¿na otworzyæ przy u¿yciu wytrychów].}
{163}{}{Widzisz stary pojemnik z zamkiem.}
{164}{}{Widzisz stary pojemnik bez widocznego zamka.}
{165}{}{Widzisz stary pojemnik zamkniêty na stary, zardzewia³y zamek.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Rozbrajasz pu³apkê i otrzymujesz }
{167}{}{ punktów obra¿eñ.}

# NPC sets off the trap
{168}{}{ rozbraja pu³apkê i otrzymuje }
{169}{}{ punktów obra¿eñ.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Zrêcznie rozbrajasz zamek na tym pojemniku.}
{171}{}{Zbyt niskie zdolnoœci sprawiaj¹, ¿e blokujesz zamek przy próbie jego otwarcia.}
{172}{}{Nie udaje ci siê rozbroiæ zamka na tym pojemniku.}

# Lock Door
{189}{}{Zrêcznie zamykasz pojemnik.}
{190}{}{Nie udaje ci siê zamkn¹æ pojemnika.}

# Find Trap on the Door
{194}{}{Widzisz pu³apkê na tym pojemniku.}
{195}{}{Nie widzisz tu ¿adnej pu³apki.}

# Disarm the Trap on the Door
{196}{}{Umiejêtnie rozbrajasz pu³apkê.}
{198}{}{Nie udaje ci siê rozbroiæ pu³apki.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{ zrêcznie otwiera zamek na pojemniku.}
{174}{}{ blokuje zamek na pojemniku podczas próby jego otwarcia.}
{175}{}{ nie potrafi otworzyæ zamka na tym pojemniku.}

# Lock Door
{191}{}{ zrêcznie zamyka pojemnik.}
{192}{}{ nie potrafi zamkn¹æ pojemnika.}

# Find Trap on the Door
{199}{}{ znajduje pu³apkê na pojemniku.}
{200}{}{ nie znajduje ¿adnej pu³apki na pojemniku.}

# Disarm the Trap on the Door
{201}{}{ umiejêtnie rozbraja pu³apkê.}
{202}{}{ nie potrafi rozbroiæ pu³apki.}

# Using a key on the door.
{400}{}{Otwierasz pojemnik.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Niszczysz zamek na pojemniku.}
{177}{}{Nadwyrê¿asz krêgos³up podczas próby zniszczenia zamka i otrzymujesz jeden punkt obra¿eñ.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Nadwyrê¿asz krêgos³up podczas próby zniszczenia zamka i otrzymujesz }
{179}{}{ punktów obra¿eñ.}
{180}{}{Nie masz si³y, aby zniszczyæ zamek.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ niszczy zamek na pojemniku.}
{182}{}{ nadwyrê¿a krêgos³up podczas próby zniszczenia zamka i otrzymuje jeden punkt obra¿eñ.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ nadwyrê¿a krêgos³up podczas próby zniszczenia zamka i otrzymuje }
{184}{}{ punkty obra¿eñ.}

{185}{}{ jest za s³aby by zniszczyæ zamek.}
{186}{}{ nadwyrê¿a krêgos³up podczas próby zniszczenia zamka i otrzymuje jeden punkt obra¿eñ.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ nadwyrê¿a krêgos³up podczas próby zniszczenia zamka i otrzymuje }
{188}{}{ punkty obra¿eñ.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Wybuch nie uszkadza pojemnika.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{Pojemnik okazuje siê zamkniêty.}
{204}{}{Zauwa¿asz pu³apkê na pojemniku.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jamb.

{205}{}{ zauwa¿a pu³apkê na pojemniku.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Nie mo¿esz za³o¿yæ pu³apki na pojemniku, poniewa¿ jest on otwarty.}

# NPC tries to set a trap on an open door
{207}{}{ nie mo¿e za³o¿yæ pu³apki na pojemniku, poniewa¿ jest on otwarty.}

# Player tries to set a trap on a closed door
{208}{}{Umiejêtnie zak³adasz pu³apkê na pojemniku.}
{209}{}{Nie udaje ci siê za³o¿yæ pu³apki na pojemniku.}

# NPC tries to set a trap on a closed door
{210}{}{ umiejêtnie zak³ada pu³apkê na pojemniku.}
{211}{}{ zawodzi przy zak³adaniu pu³apki na pojemniku.}