{100}{}{Widzisz drewnianą skrzynkę.}
{101}{}{Widzisz metalowy schowek.}
{102}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy pomocy wytrychów) i ukrytą pułapką, który możesz być w stanie otworzyć.}
{103}{}{Widzisz solidny pojemnik z zamkiem i ukrytą pułapką, który możesz być w stanie otworzyć.}
{104}{}{Widzisz solidny pojemnik bez widocznego zamka i z ukrytą pułapką, który możesz być w stanie otworzyć.}
{105}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek i z ukrytą pułapką, który możesz być w stanie otworzyć.}
{106}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i ukrytą pułapką, który możesz być w stanie otworzyć.}
{107}{}{Widzisz solidny pojemnik z zamkiem i ukrytą pułapką, który możesz być w stanie otworzyć.}
{108}{}{Widzisz solidny pojemnik bez widocznego zamka i z ukrytą pułapką, który możesz być w stanie otworzyć.}
{109}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek i z ukrytą pułapką, który możesz być w stanie otworzyć.}
{110}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i z przeciętym kablem na obudowie, który mógłbyś otworzyć.}
{111}{}{Widzisz solidny pojemnik z zamkiem i z przeciętym kablem na obudowie, który mógłbyś otworzyć.}
{112}{}{Widzisz solidny pojemnik bez widocznego zamka i z przeciętym kablem na obudowie, który mógłbyś otworzyć.}
{113}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek i z przeciętym kablem na obudowie, który mógłbyś otworzyć.}
{114}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów), który mógłbyś otworzyć.}
{115}{}{Widzisz solidny pojemnik z zamkiem, który mógłbyś otworzyć.}
{116}{}{Widzisz solidny pojemnik, bez widocznego zamka, który mógłbyś otworzyć.}
{117}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek, który mógłbyś otworzyć.}
{118}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i bardzo niebezpieczną pułapką na obudowie.}
{119}{}{Widzisz solidny pojemnik z zamkiem i z bardzo niebezpieczną pułapką na obudowie.}
{120}{}{Widzisz solidny pojemnik bez widocznego zamka z bardzo niebezpieczną pułapką na obudowie.}
{121}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek z bardzo niebezpieczną pułapką na obudowie.}
{122}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i z pułapką na obudowie.}
{123}{}{Widzisz solidny pojemnik z zamkiem i pułapką na obudowie.}
{124}{}{Widzisz solidny pojemnik bez widocznego zamka i z pułapką na obudowie.}
{125}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek z pułapką na obudowie.}
{126}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i przeciętym kablem na obudowie.}
{127}{}{Widzisz solidny pojemnik z zamkiem i przeciętym kablem na obudowie.}
{128}{}{Widzisz solidny pojemnik bez widocznego zamka i przeciętym kablem na obudowie.}
{129}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek i przeciętym kablem na obudowie.}
{130}{}{Widzisz solidny pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów).}
{131}{}{Widzisz solidny pojemnik z zamkiem.}
{132}{}{Widzisz solidny pojemnik bez widocznego zamka.}
{133}{}{Widzisz solidny pojemnik zamknięty na stary, zardzewiały zamek.}
{134}{}{Widzisz zniszczony pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i bardzo niebezpieczną pułapką na obudowie.}
{135}{}{Widzisz zniszczony pojemnik z zamkiem i bardzo niebezpieczną pułapką na obudowie.}
{136}{}{Widzisz zniszczony pojemnik bez widocznego zamka, z bardzo niebezpieczną pułapką na obudowie.}
{137}{}{Widzisz zniszczony pojemnik zamknięty na stary, zardzewiały zamek, z bardzo niebezpieczną pułapką na obudowie.}
{138}{}{Widzisz zniszczony pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i z pułapką na obudowie.}
{139}{}{Widzisz zniszczony pojemnik z zamkiem i pułapką na obudowie.}
{140}{}{Widzisz zniszczony pojemnik bez widocznego zamka, z pułapką na obudowie.}
{141}{}{Widzisz zniszczony pojemnik zamknięty na stary, zardzewiały zamek, z pułapką na obudowie.}
{142}{}{Widzisz zniszczony pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów) i przeciętym kablem na obudowie.}
{143}{}{Widzisz zniszczony pojemnik z zamkiem i przeciętym kablem na obudowie.}
{144}{}{Widzisz zniszczony pojemnik bez widocznego zamka i przeciętym kablem na obudowie.}
{145}{}{Widzisz zniszczony pojemnik zamknięty na stary, zardzewiały zamek i przeciętym kablem na obudowie.}
{146}{}{Widzisz zniszczony pojemnik z zamkiem (który można otworzyć przy użyciu wytrychów).}
{147}{}{Widzisz zniszczony pojemnik z zamkiem.}
{148}{}{Widzisz zniszczony pojemnik bez widocznego zamka.}
{149}{}{Widzisz zniszczony pojemnik zamknięty na stary, zardzewiały zamek.}
{150}{}{Widzisz stary pojemnik z zamkiem [który można otworzyć przy użyciu wytrychów] i bardzo niebezpieczną pułapką na obudowie.}
{151}{}{Widzisz stary pojemnik z zamkiem i bardzo niebezpieczną pułapką na obudowie.}
{152}{}{Widzisz stary pojemnik bez widocznego zamka i z bardzo niebezpieczną pułapką na obudowie.}
{153}{}{Widzisz stary pojemnik zamknięty na stary, zardzewiały zamek z bardzo niebezpieczną pułapką na obudowie.}
{154}{}{Widzisz stary pojemnik z zamkiem [który można otworzyć przy użyciu wytrychów] i z pułapką na obudowie.}
{155}{}{Widzisz stary pojemnik z zamkiem i z pułapką na obudowie.}
{156}{}{Widzisz stary pojemnik bez widocznego zamka i z pułapką na obudowie.}
{157}{}{Widzisz stary pojemnik zamknięty na stary, zardzewiały zamek i z pułapką na obudowie.}
{158}{}{Widzisz stary pojemnik z zamkiem [który można otworzyć przy użyciu wytrychów] i przeciętym kablem na obudowie.}
{159}{}{Widzisz stary pojemnik z zamkiem i przeciętym kablem na obudowie.}
{160}{}{Widzisz stary pojemnik bez widocznego zamka i przeciętym kablem na obudowie.}
{161}{}{Widzisz stary pojemnik zamknięty na stary, zardzewiały zamek i przeciętym kablem na obudowie.}
{162}{}{Widzisz stary pojemnik z zamkiem [który można otworzyć przy użyciu wytrychów].}
{163}{}{Widzisz stary pojemnik z zamkiem.}
{164}{}{Widzisz stary pojemnik bez widocznego zamka.}
{165}{}{Widzisz stary pojemnik zamknięty na stary, zardzewiały zamek.}
{166}{}{Uaktywniasz pułapkę i odnosisz }
{167}{}{ punktów obrażeń.}
{168}{}{ uaktywnia pułapkę i odnosi }
{169}{}{ punktów obrażeń.}
{170}{}{Zręcznie rozbrajasz zamek na tym pojemniku.}
{171}{}{Zbyt niskie zdolności sprawiają, że blokujesz zamek przy próbie jego otwarcia.}
{172}{}{Nie udaje ci się rozbroić zamka na tym pojemniku.}
{173}{}{ zręcznie otwiera zamek na pojemniku.}
{174}{}{ blokuje zamek na pojemniku podczas próby jego otwarcia.}
{175}{}{ nie potrafi otworzyć zamka na tym pojemniku.}
{176}{}{Niszczysz zamek na pojemniku.}
{177}{}{Nadwerężasz się próbując wyłamać zamek i odnosisz jeden punkt obrażeń.}
{178}{}{Nadwerężasz się próbując wyłamać zamek i odnosisz }
{179}{}{ punktów obrażeń.}
{180}{}{Brakuje ci sił, żeby wyłamać ten zamek.}
{181}{}{ niszczy zamek na pojemniku.}
{182}{}{ nadweręża się próbując wyłamać zamek z drzwi i odnosi jeden punkt obrażeń.}
{183}{}{ nadweręża się próbując wyłamać zamek i odnosi }
{184}{}{ punktów obrażeń.}
{185}{}{ nie ma dość sił by wyłamać zamek.}
{186}{}{ nadweręża się próbując wyłamać zamek i odnosi jeden punkt obrażeń.}
{187}{}{ nadweręża się próbując wyłamać zamek i odnosi }
{188}{}{ punktów obrażeń.}
{189}{}{Zręcznie zamykasz pojemnik.}
{190}{}{Nie udaje ci się zamknąć pojemnika.}
{191}{}{ zręcznie zamyka pojemnik.}
{192}{}{ nie potrafi zamknąć pojemnika.}
{193}{}{Wybuch nie uszkadza pojemnika.}
{194}{}{Widzisz pułapkę na tym pojemniku.}
{195}{}{Nie widzisz tu żadnej pułapki.}
{196}{}{Sprawnie rozbrajasz pułapkę.}
{198}{}{Nie udało ci się rozbroić pułapki.}
{199}{}{ znajduje pułapkę na pojemniku.}
{200}{}{ nie znajduje żadnej pułapki na pojemniku.}
{201}{}{ sprawnie rozbraja pułapkę.}
{202}{}{ nie może rozbroić pułapki.}
{203}{}{Pojemnik okazuje się zamknięty.}
{204}{}{Zauważasz pułapkę na pojemniku.}
{205}{}{ zauważa pułapkę na pojemniku.}
{206}{}{Nie możesz założyć pułapki na pojemniku, ponieważ jest on otwarty.}
{207}{}{ nie może założyć pułapki na pojemniku, ponieważ jest on otwarty.}
{208}{}{Umiejętnie zakładasz pułapkę na pojemniku.}
{209}{}{Nie udaje ci się założyć pułapki na pojemniku.}
{210}{}{ umiejętnie zakłada pułapkę na pojemniku.}
{211}{}{ zawodzi przy zakładaniu pułapki na pojemniku.}
{212}{}{Widzisz lodówkę.}
{400}{}{Otwierasz pojemnik.}
{601}{}{To jest otwarte, głupku.}
{610}{}{Ponosisz spektakularną porażkę, ładunek wybuchowy wybucha przedwcześnie.}
{611}{}{ zawodzi spektakularnie, ładunek wybuchowy wybucha przedwcześnie.}
{620}{}{Wyginasz łom nie do poznania. Jest teraz bezużyteczny.}
{621}{}{ wygina łom nie do poznania. Jest teraz bezużyteczny.}
{800}{}{Znajdujesz klucz.}
{810}{}{Znajdujesz plany.}
{820}{}{Udało ci się zdobyć motywator K-9.}
