{100}{}{Widzisz Larê.}
{150}{}{Przewodzi temu gangowi.}
{200}{}{Jestem Lara. Dowodzê t¹ band¹. Mam nadziejê, ¿e nie szukasz k³opotów, bo mo¿e ciê to drogo kosztowaæ.}
{201}{}{Znowu ty? Czego potrzebujesz?}
{202}{}{Szukam pracy.}
{203}{}{Tak siê tylko rozgl¹dam.}
{204}{}{Szukam kupca, niejakiego Vica.}
{205}{}{Arf.}
{206}{}{Rara.}
{220}{}{Przykro mi. W tym mieœcie nie ma ¿adnego lekarza.}
{221}{}{Obawiam siê, ¿e nie rozumiem.}
{222}{}{Ak.}
{230}{}{Jakoœ nie obi³o mi siê o uszy, ale trudno sprawdziæ kto przewija siê przez to miasto. Pogadaj z Becky. Ka¿dy zagl¹da do niej przynajmniej raz. Mo¿e ona ci pomo¿e.}
{231}{}{Szukam pracy.}
{232}{}{Dziêki. Na razie.}
{240}{}{Jeœli nie masz w Norze konkretnego interesu do za³atwienia, to wynoœ siê st¹d jak najprêdzej. Tu nie jest zbyt bezpiecznie.}
{241}{}{Och, w porz¹dku.}
{242}{}{Szukam pracy.}
{243}{}{Dam sobie radê.}
{244}{}{Dobra, dziêki.}
{250}{}{Nie w¹tpiê. W przeciwnym razie ju¿ by by³o po tobie.}
{251}{}{No pewnie. Niejeden tak mówi³ zanim...}
{252}{}{Szukam pracy.}
{253}{}{Dobra, dziêki.}
{260}{}{To zale¿y jak¹ pracê masz na myœli. Jest w tym mieœcie coœ, co mnie interesuje. Jeœli wywêszysz co i jak, mo¿esz zarobiæ trochê kasy.}
{261}{}{Jak ju¿ mówi³am, potrzebujê informacji na pewien temat. Oczywiœcie zap³acê.}
{262}{}{Nie ma sprawy. O co chodzi?}
{263}{}{Mo¿e póŸniej.}
{270}{}{Wróæ, jak zmienisz zdanie.}
{271}{}{Dobrze.}
{280}{}{Na wschód st¹d jest taki koœció³. Metzger kaza³ pewnym ludziom pilnowaæ czegoœ, co znajduje siê w œrodku. Dowiedz siê co to jest, a zarobisz $200.}
{281}{}{To ³atwizna. Ja ju¿ wiem.}
{282}{}{Jasne.}
{283}{}{Zobaczê, co da siê zrobiæ.}
{290}{}{Dziêki. Tylko nie wdawaj siê w bójki... jeszcze nie. Mam pewien plan.}
{291}{}{Nie ma sprawy.}
{292}{}{Zaraz wracam.}
{300}{}{Co to takiego?}
{301}{}{Wielkie skrzynie wype³nione po brzegi chemicznymi pó³produktami.}
{302}{}{Wielkie pojemniki pe³ne jakichœ chemikaliów.}
{303}{}{Mo¿e sprawdzê jeszcze raz.}
{310}{}{To by siê zgadza³o. Dziêki. Tu s¹ twoje pieni¹dze.}
{311}{}{Dlaczego?}
{312}{}{Nie ma sprawy. Czeœæ.}
{320}{}{Widzia³am karawany przybywaj¹ce tu z Kryptopolis. Czêœæ towaru trafia potem do Nowego Reno.}
{321}{}{No i? Co w tym takiego?}
{322}{}{Och.}
{340}{}{Nowe Reno to lokalna fabryka prochów. Przecie¿ musz¹ sk¹dœ braæ pó³produkty, prawda? Wygl¹da na to, ¿e czêœæ lub ca³oœæ dostaj¹ z Kryptopolis.}
{341}{}{Gdzie le¿y to Nowe Reno?}
{342}{}{Dobra, dziêki.}
{350}{}{Nie jestem pewna. Chyba gdzieœ na po³udnie. Nigdy tam nie by³am. Ich karawany zagl¹daj¹ do Nory tylko sporadycznie.}
{351}{}{W porz¹dku. Dziêki.}
{360}{}{Chcesz siê ³atwo wzbogaciæ? $50. Nic szczególnie trudnego.}
{361}{}{Jasne.}
{362}{}{Sprê¿aj siê.}
{370}{}{Chcê wyrównaæ z Tylerem pewne stare porachunki. Potrzebujê kogoœ, kto poprosi Metzgera o pozwolenie. On bêdzie wiedzia³ o co chodzi.}
{371}{}{Dlaczego sama tego nie zrobisz?}
{372}{}{Spróbujê}
{373}{}{W porz¹dku.}
{380}{}{Bo nie chcê, ¿eby Tyler albo ktoœ z jego ludzi zobaczy³ mnie jak wchodzê lub wychodzê z domu Metzgera. Wtedy wszystkiego siê domyœl¹.}
{381}{}{Nie kapujesz? Jeœli Tyler dowie siê, ¿e rozmawia³am z Metzgerem, mo¿e nabraæ podejrzeñ.}
{382}{}{Zobaczê, co siê da zrobiæ.}
{383}{}{W porz¹dku.}
{390}{}{No i? Wiesz ju¿ co jest w œrodku?}
{391}{}{Wielkie skrzynie wype³nione po brzegi chemicznymi pó³produktami.}
{392}{}{Wielkie pojemniki pe³ne jakichœ chemikaliów.}
{393}{}{Jeszcze nie.}
{400}{}{No i jak posz³o? Co powiedzia³?}
{401}{}{Zgodzi³ siê. Jeœli wygrasz, dostaniesz znowu tê robotê.}
{402}{}{Na.}
{410}{}{Œwietnie. Mia³am przeczucie, ¿e siê zgodzi. Od jakiegoœ czasu strasznie na nich narzeka³. Oto twoje pieni¹dze.}
{411}{}{Pewnie jest jeszcze coœ do zrobienia?}
{412}{}{Dziêki. Na razie.}
{420}{}{Mam dla ciebie jeszcze jedno zadanie. Nie wiem, jak masz to zrobiæ, ale skoro uda³o ci siê dostaæ do œrodka, poradzisz sobie i teraz.}
{421}{}{Raczej wœlizn¹æ ni¿ dostaæ.}
{422}{}{Co to jest?}
{430}{}{Na pewno jakoœ sobie poradzisz.}
{431}{}{Dobra, o co chodzi?}
{440}{}{Oko w oko nie mamy z nimi szans. S¹ lepiej wyposa¿eni i przewa¿aj¹ nas liczebnie. Mo¿e uda ci siê znaleŸæ jakiœ s³aby punkt albo coœ, co moglibyœmy wykorzystaæ w walce...}
{441}{}{Co? ZnaleŸæ s³aby punkt? Niby jak mam to zrobiæ?}
{442}{}{Ile?}
{443}{}{Nie ma sprawy.}
{450}{}{Dostaniesz od nas $150. Bez ciebie sobie nie poradzimy.}
{451}{}{Ze mn¹ te¿ niekoniecznie.}
{452}{}{W porz¹dku.}
{460}{}{Nie wiem. Dlatego proszê ciê o pomoc.}
{461}{}{Spróbujê.}
{462}{}{To bezcelowe.}
{470}{}{Wiesz ju¿ coœ?}
{471}{}{Tak. Urz¹dzaj¹ dziœ w nocy imprezê.}
{472}{}{Jeszcze nie. Odezwê siê.}
{473}{}{Gra.}
{474}{}{Na.}
{480}{}{Œwietnie! Zostawi¹ tylko nieliczn¹ stra¿. To powinno wyrównaæ szanse. Tymi na imprezie zajmiemy siê po zdobyciu koœcio³a.}
{481}{}{A moje pieni¹dze?}
{490}{}{Jeszcze nie teraz. Musisz pójœæ z nami, inaczej nie dostaniesz pieniêdzy. Nie musisz braæ udzia³u w walce, chcê mieæ tylko pewnoœæ, ¿e nie prowadzisz nas w pu³apkê. W sumie dostaniesz od nas $300.}
{491}{}{Zaczynamy?}
{492}{}{Bierzmy siê do roboty.}
{493}{}{Daj mi trochê czasu na przygotowanie.}
{494}{}{W ¿yciu. Zatrzymaj sobie swoje pieni¹dze!}
{500}{}{Dobra, ale musimy dzia³aæ szybko, albo stracimy nasz¹ szansê, wiêc œpiesz siê.}
{501}{}{W porz¹dku.}
{510}{}{Nie musisz nawet walczyæ. To ³atwizna.}
{511}{}{No i jak? Mo¿e zmienisz zdanie?}
{512}{}{Bierzmy siê do roboty.}
{513}{}{W porz¹dku, zaraz wracam.}
{514}{}{Nie.}
{515}{}{Uk.}
{520}{}{Przez ciebie straciliœmy niepowtarzaln¹ okazjê.}
{521}{}{Tchórz ciê oblecia³!}
{522}{}{Nic od nas nie dostaniesz.}
{523}{}{Za³o¿ê siê, ¿e to by³a pu³apka.}
{524}{}{Przykro mi, nie mo¿na na tobie polegaæ.}
{525}{}{Nie mo¿na ci ufaæ.}
{530}{}{Uda³o siê!}
{531}{}{Dziêki za pomoc.}
{532}{}{Jesteœmy ci wdziêczni!}
{533}{}{Wreszcie Tyler zap³aci³ mi za to co sta³o siê z moim bratem.}
{534}{}{Jeszcze raz - wielkie dziêki.}
{540}{}{Nie wiem co siê stanie po œmierci Metzgera.}
{541}{}{Chyba powinniœmy siê st¹d wynieœæ.}
{542}{}{Wiesz ju¿ o œmierci Metzgera? Nie wiem co teraz z nami bêdzie.}
{543}{}{Co siê teraz stanie z Nor¹? Mo¿e zmieni siê na lepsze.}
{544}{}{To chyba zmiana na lepsze.}
{550}{}{Skurwiel!}
{551}{}{Suka!}
{560}{}{Dziêki. Oto twoje pieni¹dze, plus $100 ekstra.}
{570}{}{Tyler i jego stra¿nicy nie ¿yj¹? I jak mamy teraz pokazaæ Metzgerowi co potrafimy? To by³a nasza jedyna szansa, ¿eby dostaæ tê robotê.}
{571}{}{Jesteœmy bez pracy. Ktoœ za³atwi³ stra¿ników Metzgera, i teraz stary nie chce z nami rozmawiaæ. Pewnie myœli, ¿e to nasza robota.}
{572}{}{Przykro mi.}
{573}{}{Wielka szkoda.}
{574}{}{To MOJA robota. Teraz kolej na WAS.}
{575}{}{No tak. Do zobaczenia.}
{576}{}{Uhr?}
{577}{}{Ug.}
{590}{}{Przecie¿ mówi³am, ¿e mieliœmy iœæ razem. Po œmierci stra¿ników ktoœ wyczyœci³ koœció³ z towaru. Metzger wœciek³ siê jak jasna cholera.}
{591}{}{Prosi³am tylko o znalezienie ich s³abego punktu. Nie trzeba by³o ich od razu zabijaæ! Po œmierci stra¿ników ktoœ wyczyœci³ koœció³ z towaru. Metzger wœciek³ siê jak jasna cholera.}
{592}{}{Cholera! Prosi³am ciê tylko o porozmawianie z Metzgerem! Po œmierci stra¿ników ktoœ wyczyœci³ koœció³ z towaru. Metzger wœciek³ siê jak jasna cholera.}
{593}{}{Cholera! Przecie¿ zabroni³am ci ich atakowaæ! Po œmierci stra¿ników ktoœ wyczyœci³ koœció³ z towaru. Metzger wœciek³ siê jak jasna cholera.}
{594}{}{Trudno. Muszê ju¿ iœæ.}
{595}{}{Wielka szkoda.}
{596}{}{Bêdziesz nastêpna, suko.}
{597}{}{Hmph!}
{598}{}{Tera ty.}
{610}{}{Ty to naprawdê potrafisz coœ spieprzyæ, wiesz?}
{611}{}{Nie potrzebujemy ju¿ twojej pomocy.}
{612}{}{IdŸ przeszkadzaæ komuœ innemu.}
{613}{}{Lepiej, ¿eby Metzger siê nas nie czepia³.}
{614}{}{Przykro mi. Nie mogê ci pomóc.}
{615}{}{Nie mam czasu na rozmowê. Zastanawiam siê co robiæ dalej.}
{616}{}{Mam nadziejê, ¿e Metzger nie bêdzie nas wini³.}
{617}{}{Co my teraz zrobimy?}
{618}{}{Lepiej siê st¹d wynoœmy. Metzger mo¿e pomyœleæ, ¿e to my wykoñczyliœmy jego stra¿ników.}
{619}{}{Wiesz gdzie jest Nowe Reno? Mo¿e uciekniemy tam - albo na pó³noc.}
{650}{}{Dobra! Do roboty! Wszyscy za mn¹!}
{700}{}{Dobra, zajêliœmy siê szcz¹tkowa ekip¹ tutaj w koœciele, ale ci¹gle Tyler i jego kolesie s¹ w dzielnicy Mieszkalnej.
 Do tej pory pewnie s¹ ju¿ pijani, mo¿emy ich ³atwo zaskoczyæ. Czas to skoñczyæ, idziesz?}
{701}{}{Pozwól mi siê najpierw podleczyæ.Powiem ci jak skoñczê siê przygotowywaæ.}
{702}{}{Ruszajmy.}
{710}{}{Czas ¿eby zdj¹æ Tylera i jego kumpli.}
{720}{}{Hej, nie odchodŸ za daleko. Musimy to skoñczyæ tej nocy lub zrobimy to bez ciebie.}
{721}{}{Nied³ugo wrócê.}
{722}{}{Ruszajmy.}
{730}{}{Zrobiliœmy to. Nie mogê w to uwierzyæ! Wracamy do koœcio³a ¿eby go zaj¹æ. Spotkajmy siê tam to dostaniesz swoj¹ kasê.}
