{100}{}{Widzisz faceta w œrednim wieku.}
{101}{}{Jest nieogolony i œmierdzi alkoholem.}
{102}{}{*hik* Czy my siê znamy?}
{103}{}{Jest jedenasta. Wiesz gdzie jest twoje dziecko?}
{104}{}{[Patrzy na ciebie zaspany.] Co? *hik* Ju¿ jedenasta?}
{105}{}{W³aœciwie nie, ale nieŸle brzmi. A tak na serio, wiesz gdzie jest twoje dziecko?}
{106}{}{W³aœciwie to tak, ale to nie jest teraz najwa¿niejsze. A tak na serio, wiesz gdzie jest twoje dziecko?}
{107}{}{*hik* To ja mam dzieci? *hik* A tak, mam. On... czy ona?... *hik* Powinno gdzieœ tu byæ.}
{108}{}{£a³, naprawdê jesteœ a¿ takim pijakiem. Có¿, dobrze, ¿e pracujê nad zabraniem go st¹d.}
{109}{}{[Zignorowa³ to co mówisz.] Tak to œwietnie. *hik* A teraz pozwól mi wróciæ do mojego drinka.}
{110}{}{Jesteœ bohaterem dla wszystkich ojców. Tak trzymaj!}
{111}{}{zzzZZZZzzz...}
{112}{}{zZZZZzzZZzzz...}
{113}{}{*mamrocze*}
{114}{}{Nie widzisz, ¿e ja tu staram siê napiæ? *hik*}
{115}{}{Nie przeszkadzaj mi. *hik*}

{116}{}{W³aœciwie dopiero dochodzi jedenasta, ale to nie jest teraz najwa¿niejsze. A tak na serio, wiesz gdzie jest twoje dziecko?}
{117}{}{W³aœciwie jest trochê po jedenastej, ale to nie jest teraz najwa¿niejsze. A tak na serio, wiesz gdzie jest twoje dziecko?}

