{100}{}{Widzisz dziecko.}
{101}{}{Widzisz ma³ego ch³opca. Sprawia wra¿enie szczêœliwego.}
{102}{}{Widzisz ma³¹ dziewczynkê. Sprawia wra¿enie szczêœliwej.}
{200}{}{Dzieñ dobry Panu!}
{201}{}{Przepraszamy, ¿e próbowaliœmy ciê okraœæ.}
{202}{}{Bardzo mi siê tu podoba.}
{203}{}{Dziêkuje, ¿e pomog³eœ Mamie przygotowaæ to miejsce!}
{300}{}{Dzieñ dobry Pani!}
{301}{}{Przepraszamy, ¿e próbowaliœmy ciê okraœæ.}
{302}{}{Bardzo mi siê tu podoba.}
{303}{}{Dziêkuje, ¿e pomog³eœ Mamie przygotowaæ to miejsce!}
