{100}{}{Widzisz łowcę niewolników.}
{150}{}{Wydaje się być czymś przejęty.}
{200}{}{Dotknij tego jeszcze raz, a stracisz kończynę.}
{201}{}{Dość tego!}
{210}{}{Nie ma tam nic oprócz niewolników.}
{211}{}{Niewolnicy nie przyjmują gości.}
{212}{}{Te drzwi są tylko dla czlonków gildii.}
{213}{}{Szukasz niewolnika? Gadaj z Metzgerem.}
{214}{}{Gadaj z Metzgerem. Wstęp do kwater niewolników jest wzbroniony.}
{215}{}{Czego tu szukasz? Spierdalaj.}
{216}{}{Spierdalaj, dziwko. Niewolnicy nie przyjmują gości.}
{230}{}{Jak leci?}
{231}{}{Trochę dziś nudno.}
{232}{}{Mam nadzieję, że podoba ci się w gildii.}
{233}{}{Twój tatuaż nieźle wyszedł.}
{234}{}{Czy ja cię nie widziałem na ostatnim polowaniu?}
{235}{}{Cześć.}
{236}{}{Jesteś w moim typie, kobieto.}
{237}{}{Kobieta-Łowca - to mi się podoba.}
{238}{}{Sie masz.}
{239}{}{Nieźle wyglądasz.}
