{100}{}{Widzisz umorusanego mechanika.}
{150}{}{Widzisz Smitty'ego - mechanika i właściciela złomowiska w jednej osobie.}
{151}{}{Widzisz umorusanego mechanika w brudnym ubraniu roboczym.}
{200}{}{Ty szkodniku! Wynoś się stąd zanim dam ci nauczkę!}
{201}{}{Wynoś się stąd!}
{202}{}{Wynoś się z mojej ziemi!}
{203}{}{Cholerny szkodniku, uciekaj stąd.}
{204}{}{Idź do diabła.}
{220}{}{Hej, wynoś się z mojej ziemi.}
{221}{}{Hej, głupolu, uciekaj stąd.}
{222}{}{No już, sio!}
{223}{}{Nie mam czasu dla takich jak ty.}
{224}{}{Nie potrafię mówić po głupkowemu.}
{240}{}{Witaj, młodzieńcze. Co stary Smitty może dla ciebie zrobić?}
{241}{}{Witaj, ślicznotko. Co stary Smitty może ci... dla ciebie zrobić?}
{242}{}{A niech mnie! Co mogę dla ciebie zrobić tym razem?}
{243}{}{Jak leci! Wielkie dzięki za tę wyżerkę od Mamuśki. Co stary Smitty może dla ciebie zrobić?}
{244}{}{Zastanawiam się właśnie czym się tu zajmujesz?}
{245}{}{Słuchaj, staruszku, mam tu taką rzecz z Gecko...}
{246}{}{Hej Smitty, interesuje mnie samochód, który masz na sprzedaż.}
{247}{}{Przynoszę ci jedzenie od Mamuśki.}
{248}{}{Słuchaj, staruszku, mam tu taką rzecz z Klamath...}
{249}{}{Chcę się tylko trochę rozejrzeć. Do zobaczenia, Smitty.}
{260}{}{Niech no stary Smitty rzuci na to okiem.}
{261}{}{Jasne, proszę bardzo.}
{262}{}{Może później. Na razie chcę cię o coś zapytać.}
{263}{}{Może innym razem. Do zobaczenia, Smitty.}
{280}{}{Niech no stary Smitty rzuci na to okiem.}
{281}{}{Jasne, proszę bardzo.}
{282}{}{Może później. Na razie chcę cię o coś zapytać.}
{283}{}{Może innym razem. Do zobaczenia, Smitty.}
{300}{}{No no... to mi wygląda na stary kontroler ogniw zasilających. Hmm, jakby to wsadzić do starego Krążownika Szos, chodziłby jak prawdziwy skarb.}
{301}{}{Hę?}
{310}{}{Hmm, to wygląda jak regulator ogniw zasilających. Gdybym miał tu jakiś sprawny samochód, mógłbym zmniejszyć jego zużycie paliwa.}
{311}{}{Hę?}
{320}{}{To bardzo miło z twojej strony. Wielkie dzięki! Oto mały prezent w nagrodę. Może ci się kiedyś przydać, zwłaszcza w tych stronach. (Daje ci Stimpak)}
{321}{}{Dzięki, Smitty. Do zobaczenia.}
{322}{}{Eee... Dzięki, ale zajrzałem niedawno do Mamuśki i zdążyłem już co nieco przekąsić. Nie jestem głodny.}
{323}{}{Uuups, osoba, która zwykle dostarcza te przesyłki zachorowała, więc ją zastępuję. Mogę mimo to dostać trochę punktów doświadczenia?}
{324}{}{Och, serdecznie przepraszam. Mam nadzieję, że Mamuśka mnie nie wyleje. Bardzo potrzebuję tej pracy.}
{325}{}{Wiesz, że nie dajemy już darmowych posiłków po przekroczeniu 24 godzin, prawda?}
{326}{}{Cóż, w takim razie JA zjem ten posiłek.}
{327}{}{Mamuśka nie będzie zachwycona jak się o tym dowie.}
{330}{}{Widzisz, mam tu ten samochód - Krążownik Szos firmy Chrysalis Motors. Prawdziwe cacko. Reklamowali go hasłem: "Nic nie zatrzyma Krążownika Szos". Zbudowany jak czołg - ot co.}
{331}{}{A co to ma wspólnego ze mną?}
{340}{}{Widzisz, myślałem, że potrzebuję do niego akumulatora, ale okazuje się, że wystarczy założyć nowy kontroler ogniw zasilających. One zawsze łatwo się psuły.}
{341}{}{Mam takie coś!}
{350}{}{Naprawdę? No to zawrzyjmy układ. Daj mi $2000, a ja sprzedam ci ten samochód. Cholercia, nawet zainstaluję w nim twój kontroler ogniw zasilających. Będzie chodził jak nowy. Do tego dorzucę jeszcze parę nowych ogniw.}
{351}{}{To wspaniale! Oto pieniądze i część.}
{352}{}{Może później. Chcę cię najpierw o coś zapytać, Smitty.}
{353}{}{Zastanowię się. Do zobaczenia, Smitty.}
{370}{}{Tylko nie szalej od razu. Daj mu się najpierw rozgrzać.}
{371}{}{Jasne. Dzięki, Smitty.}
{380}{}{Cóż, to bardzo dużo i bardzo mało zarazem.}
{381}{}{Hę?}
{390}{}{Chodzi mi o to, że taki regulator to dobra rzecz, ale bez kontrolera ogniw zasilających się i tak nie obejdzie.}
{391}{}{Dlaczego?}
{400}{}{Bo jakbym miał kontroler, to za $2000 odpicowałbym dla ciebie ten Krążownik Szos Chrysalis Motors.}
{401}{}{Naprawdę? A gdzie mogę znaleźć taki kontroler ogniw zasilających?}
{410}{}{Co za niemądre pytanie! Gdybym wiedział gdzie można znaleźć takie cacko, sam bym już dawno jeździł tym cudeńkiem, nie sądzisz?}
{411}{}{Cóż, spróbuję się rozejrzeć za takim urządzeniem.}
{420}{}{Dobry pomysł. Jeśli go znajdziesz, przynieś go do mnie. No i nie zapomnij o $2000.}
{421}{}{Umowa stoi, Smitty. Chcę cię jeszcze o coś zapytać.}
{422}{}{Najlepiej od razu zacznę szukać. Do widzenia.}
{430}{}{Witaj, jak się sprawuje twój samochód?}
{431}{}{Całkiem nieźle, Smitty. Słuchaj, nie wiesz, do czego może służyć ta część samochodowa?}
{432}{}{Wspaniale, Smitty, po prostu wspaniale. Hej, mam dla ciebie posiłek. Pozdrowienia do Mamuśki.}
{433}{}{W porządku, Smitty. Trzymaj się. Do zobaczenia.}
{450}{}{No proszę, to jest regulator ogniw zasilających. Powinien zmniejszyć zużycie paliwa. Mogę go dla ciebie zamontować, za jakieś... $750.}
{451}{}{Umowa stoi, Smitty. Oto część i pieniądze.}
{452}{}{Przemyślę to sobie. Do zobaczenia.}
{460}{}{Głównie pilnuję całego tego złomu. I tak mam tu tylko jedną rzecz wartą parę groszy.}
{461}{}{Co to takiego?}
{462}{}{No tak. Mogę cię zapytać o coś jeszcze?}
{470}{}{No... mam tu autentyczny Krążownik Szos firmy Chrysalis Motors. Reklamowali je hasłem: "Nic nie zatrzyma Krążownika Szos". Trzeba przyznać - ten wóz jest zbudowany jak czołg.}
{471}{}{Niesamowite! Jest sprawny?}
{480}{}{Myślisz, że siedziałbym w tej śmierdzącej dziurze, gdyby był sprawny?}
{481}{}{Tak.}
{482}{}{Pewnie nie.}
{490}{}{Cóż, pewnie masz rację. Przyzwyczaiłem się już do tej dziury.}
{491}{}{Rozumiem.}
{500}{}{Cóż, chyba jednak tak. Polubiłem trochę tę dziurę.}
{501}{}{Rozumiem.}
{510}{}{Ale chętnie sprzedam ten wóz. Gdyby ktoś przyniósł mi akumulator - nie, czekaj, chyba potrzebuję raczej kontrolera ogniw zasilających. Tak, gdybym miał coś takiego, sprzedałbym wóz za $2000. Instalacja kontrolera wliczona w cenę.}
{511}{}{Brzmi interesująco. Jeśli uda mi się kiedyś znaleźć taki kontroler, zgłoszę się do ciebie. Mogę cię jeszcze o coś zapytać?}
{512}{}{Odezwę się jak już go znajdę. Do widzenia, Smitty.}
{520}{}{Proszę bardzo. Jak nowy. Tylko ostrożnie się z nim obchodź.}
{521}{}{Jasne. Dzięki, Smitty. Do zobaczenia.}
{600}{}{TRZYMAJ SIĘ Z DALA OD MOJEGO SAMOCHODU!}
{650}{}{I żebym cię już nigdy nie złapał na włóczeniu się przy moim samochodzie.}
{651}{}{Nie złapiesz, obiecuję.}
{652}{}{Uggg-K.}
