{100}{}{Widzisz właściciela sklepu.}
{101}{}{Widzisz Tubby'ego.}
{150}{}{To jest właściciel sklepu.}
{151}{}{To jest Tubby, właściciel sklepu.}
{152}{}{[ROZMAWIAJ]}
{153}{}{Lepiej załatwiaj swoje interesy gdzie indziej.}
{154}{}{Jesteś człowiekiem biznesu. Porozmawiajmy o interesach.}
{155}{}{Mogę cię o coś zapytać?}
{156}{}{Bywaj.}
{157}{}{Tak się cieszę, że cię znów widzę. Co mogę dla ciebie zrobić tym razem?}
{158}{}{Pohandlujmy.}
{159}{}{Mogę cię o coś zapytać?}
{160}{}{Na razie nic. Dziękuję.}
{161}{}{Witam, drogi panie, witam u Tubby'ego. Jestem Tubby, we własnej osobie. Czym mogę służyć?}
{162}{}{Interesuje mnie wymiana towarów.}
{163}{}{Potrzebuję informacji.}
{164}{}{Żegnaj.}
{165}{}{Witam, droga pani. Przyjaciele mówią na mnie Tubby. Witam w moim skromnym sklepie. W czym mogę pani pomóc?}
{166}{}{Chcę coś kupić.}
{167}{}{Potrzebuję informacji.}
{168}{}{Żegnaj.}
{169}{}{Lepiej będzie jak sobie pójdziesz.}
{170}{}{Bywaj.}
{171}{}{Co chcesz wiedzieć?}
{172}{}{Kto rządzi w tym mieście?}
{173}{}{Dlaczego wszyscy tutaj handlują prochami?}
{174}{}{Wiesz gdzie znajduje się jakaś Krypta?}
{175}{}{Może jednak kupię coś od ciebie.}
{176}{}{Nieważne. Żegnaj.}
{177}{}{Ojej. Widzę, że porozumienie się z tobą może być nieco problematyczne. Kiwnij głową, jeśli chcesz coś kupić.}
{178}{}{[Kiwnij głową.]}
{179}{}{Pa-pa.}
{180}{}{Obawiam się, że nikt. Nora to dość anarchistyczne osiedle. Obowiązuje jedynie darwinowska reguła: przeżyją najsilniejsi, najszybsi i najsprytniejsi. Zastanów się, czy należysz do którejś z tych grup.}
{181}{}{Dzięki.}
{182}{}{Prochy to podstawa kruchej ekonomii tego osiedla. Inne miasta mają zboża albo złoto, my mamy prochy.}
{183}{}{Dziękuję.}
{184}{}{Słyszałem o miejscu zwanym Kryptopolis, ale niestety nie mam pojęcia gdzie to jest. Widzisz, bardzo niewiele okolicznych miast może sobie pozwolić na świadczone w Kryptopolis usługi medyczne, więc mało kto tam zagląda.}
{185}{}{Dobra. Dzięki.}
{186}{}{To nie jest informacja, którą można się dzielić z byle kim.}
{187}{}{Może stówka pomoże ci zmienić zdanie?}
{188}{}{Może dam ci za nią $50. Co ty na to?}
{189}{}{To może zawrzyjmy układ: albo ty powiesz mi co wiesz, albo ja przewietrzę ci mózg.}
{190}{}{Nieważne.}
{191}{}{A mogę cię zapytać o coś innego?}
{192}{}{No cóż, takie pieniądze z pewnością uspokoiły by moje sumienie. Tyle tylko, że nie masz dość gotówki!}
{193}{}{Pewnie została w innych spodniach. Pójdę jej poszukać.}
{194}{}{To raczej nie wystarczy.}
{500}{}{Jasne Petey. Zaraz przyjdę.}
{501}{}{Zaczekaj, Petey!}
{502}{}{Już lecę, już lecę.}
{510}{}{Proszę bardzo, Petey.}
{511}{}{Wiesz co, Petey, powinieneś odstawić to gówno.}
{512}{}{Masz, Petey, i zjeżdżaj stąd w cholerę.}
{520}{}{Interesy z tobą to przyjemność.}
