{100}{}{Widzisz niewolnika.}
{101}{}{Widzisz Vica.}
{150}{}{Ten niewolnik jest pilnie strzeżony.}
{151}{}{To Vic!}
{152}{}{[ROZMAWIAJ]}
{153}{}{Powiedz mu, że nie mogę... czekaj. Kim jesteś? Nie jesteś Łowcą. Co tu robisz?}
{154}{}{Nazywam się }
{155}{}{. Chcę cię stąd wydostać.}
{156}{}{Jestem }
{157}{}{, ale czemu siedzisz tu zamknięty?}
{158}{}{Możesz mi powiedzieć, gdzie jest Krypta 13?}
{159}{}{Jestem }
{160}{}{. Zaraz wracam.}
{161}{}{Dubba iba }
{162}{}{.}
{163}{}{Metzger ciągle jest na mnie zły, chociaż naprawiłem to jego cholerne radio. Grozi, że gdzieś mnie sprzeda! Zrobię co tylko zechcesz, ale pomóż mi się stąd wydostać.}
{164}{}{OK, spróbuję.}
{165}{}{Przykro mi, nie mam czasu. Pa.}
{166}{}{Ktoo.}
{167}{}{Och, witaj ponownie. To cholerne radio samo się nie naprawi. Jak ja niby mam to zrobić?}
{168}{}{Gdzie mogę znaleźć części?}
{169}{}{Może mi uda się je naprawić.}
{170}{}{Może przyda ci się moje radio?}
{171}{}{Zobaczę, co da się zrobić.}
{172}{}{Spa pa?}
{173}{}{Wiem co trzeba zrobić, potrzebuję tylko odpowiednich części. W mojej szopie w Klamath mam stare radio, które mogłoby mi się przydać. Wiesz gdzie urzędują Duntonowie? Moja szopa jest... no, na wschód od nich.}
{174}{}{Masz na myśli to radio?}
{175}{}{Poszukam go.}
{176}{}{Hmmm... Jeszcze tu wrócę.}
{177}{}{Świetnie! Teraz naprawię radio bez żadnych kłopotów.}
{178}{}{Dobra, pogadam z Metzgerem.}
{179}{}{Dziękuję.}
{180}{}{Bywaj.}
{181}{}{Słucham? Przykro mi, ale nie rozumiem.}
{182}{}{[Mruknięcie]}
{183}{}{Dziękuję! Jestem twoim dłużnikiem. Jak ja ci się odwdzięczę?}
{184}{}{Powiedz mi gdzie jest Krypta 13.}
{186}{}{Chodź ze mną, przyda mi się pomoc.}
{187}{}{Nie ma o czym mówić. Do widzenia.}
{188}{}{Cu-ke-rek?}
{189}{}{Krypta 13? Niedaleko stąd jest Kryptopolis. Tam wiedzą o takich rzeczach.}
{190}{}{Chcesz się tam ze mną wybrać?}
{191}{}{Dzięki. Na razie.}
{192}{}{Pewnie! Chętnie do ciebie dołączę! Tego starego psa jeszcze stać na to i owo. Możesz na mnie liczyć! Mimo tego co mówi Metzger, nieźle sobie radzę z naprawianiem starego złomu.}
{193}{}{Świetnie, zatem w drogę.}
{194}{}{Witaj na pokładzie.}
{195}{}{Jak chcesz.}
{196}{}{Vic moja najlepsza przyjaciół.}
{197}{}{Chcesz mi pomóc w poszukiwaniach?}
{198}{}{Świetnie! Dzięki.}
{203}{}{Kryptopolis jest na wschód stąd. Pokażę ci na tej twojej mapie.}
{204}{}{Dziękuję.}
{206}{}{Jest tutaj. [Pokazuje na mapie.]}
{220}{}{Cholera. Nieźle, ale potrzebuję starego radia z mojej szopy w Klamath. Mógłbym z niego wyciągnąć potrzebne części.}
{300}{}{Cóż, pewnie mógłbym ci pomóc, ale najpierw muszę się stąd jakoś wydostać.}
{301}{}{Mówiłem ci już. Jeśli pomożesz mi się stąd wydostać, zrobię co tylko zechcesz.}
{302}{}{Tylko jak to zrobić?}
{303}{}{No to radź sobie sam.}
{304}{}{Dobrze, zobaczę co się da zrobić.}
{350}{}{Myślisz, że jesteś w stanie mi pomóc?}
{351}{}{Metzger wciąż nie chce mnie puścić.}
{352}{}{Dłużej tego nie wytrzymam.}
{353}{}{Zrobię co zechcesz, tylko mnie stąd wydostań.}
{354}{}{Odpłacę ci za wszystko z nawiązką!}
{400}{}{Kiedy wreszcie zajrzysz do mojej szopy w Klamath? Naprawdę potrzebuję tego radia. Metzger z dnia na dzień bardziej się na mnie złości.}
{450}{}{Skąd masz tę manierkę?}
{451}{}{Miałem kiedyś taką manierkę z dużą żółtą trzynastką. Skąd masz swoją?}
{500}{}{A, tak. Przypominam sobie. Kupiłem ją od Eda. Handluje braminami w Kryptopolis.}
{501}{}{Manierka? A, czekaj! Tak, miałem ich kilka. Nieźle się sprzedawały. Kupowałem je od Eda. Facet handluje braminami w Kryptopolis.}
{502}{}{Kryptopolis?}
{550}{}{Przestań wreszcie mówić do mnie "szefie"!}
{600}{}{Nie ma sprawy, szefie!}
{601}{}{Miałeś przestać!!!}
{602}{}{Dobrze już, dobrze.}
{650}{}{Nie ma sprawy, Wodzu!}
{651}{}{Uggg!}
{700}{}{Tyy przyjaciół!}
{710}{}{Powiedz mu, że bez odpowiednich części nic tu nie zdziałam... czekaj. Kim jesteś? Jakiś nowy rekrut? Masz mi znowu dać wycisk, co? To i tak bez znaczenia. Nie naprawię tego złomu.}
{750}{}{Tak! Zrobisz to dla mnie? Zrobię wszystko, tylko mnie stąd uwolnij. Cały problem w tym, że Metzger nie chce mnie puścić zanim nie naprawię dla niego tego radia, a ja nie mam odpowiednich części.}
{753}{}{Gdzie mogę znaleźć części, których potrzebujesz?}
{754}{}{Zobaczę, co da się zrobić.}
{760}{}{To długa historia. W wielkim skrócie: Metzger przetrzymuje mnie tu, żebym naprawił to przeklęte radio. Niestety, bez części zamiennych nie dam rady! Czy ten człowiek nie może tego pojąć?}
{761}{}{Jestem tu, żeby cię uwolnić.}
{764}{}{Nie wiem. Cześć.}
{800}{}{Muszę jakoś naprawić ten odbiornik. Jeśli mi w tym pomożesz, może Metzger da się jakoś ubłagać.}
{801}{}{Jak mogę pomóc?}
{803}{}{Wątpię. Miłej zabawy.}
{810}{}{Dlaczego Mamuśka musiała zginąć... Zapewne były jakieś powody... Przepraszam, szefie. Nie powinienem tak cię męczyć. To bardzo złe miasto. Pewnie zrobiła coś bardzo złego.}
{811}{}{Hej, szefie. Dzięki za wyplątanie mnie z tego bagna. Potrzebujesz czegoś? Wiesz, Mamuśka była tak miła i dawała mi jeść podczas twojej nieobecności. Pomagam jej trochę...}
{812}{}{Bywaj.}
{813}{}{Oooh.}
{814}{}{Papa.}
{823}{}{Gdzie znajdę tego twojego kumpla... Eda?}
{830}{}{To chyba nie jest najlepszy pomysł. Tylko bym ci zawadzał. Po śmierci Mamuśki nic mnie już nie trzyma w tym mieście. Muszę wyjechać... sam... Może się jeszcze spotkamy. Dziękuję za wyplątanie mnie z kłopotów. Żegnaj.}
{831}{}{To chyba nie jest najlepszy pomysł. Z trudem dajesz sobie radę, ja bym ci dodatkowo zawadzał. Zostanę tutaj. Obiady Mamuśki przypominają mi moją byłą żonę...}
{832}{}{Zrobiłbym to, słowo. Zrobiłbym dla ciebie prawie wszystko. Ale... nie wyglądasz na kogoś, kto potrafi dowodzić ludźmi. Tylko bym ci zawadzał. Posiedzę trochę u Mamuśki. Brakowało mi domowego jedzenia...}
{833}{}{Przykro mi, szefie. Chyba masz już niezły tłok. Po śmierci Mamuśki nic mnie już nie trzyma w tym mieście. Muszę wyjechać... sam... Może się jeszcze spotkamy. Dziękuję za wyplątanie mnie z kłopotów. Żegnaj.}
{834}{}{Chyba masz już dość towarzyszy, szefie. Zaczekam tu, aż zwolni się jakieś miejsce. Obiady Mamuśki przypominają mi moją byłą żonę... Jeszcze nie wiem czy to dobrze, czy źle...}
{835}{}{Bardzo chętnie, szefie, ale chwilowo nie masz już chyba dla mnie dość miejsca. Lepiej zajrzę do Mamuśki. Wpadnij tam, jak znajdziesz dla mnie jakąś robotę.}
{840}{}{Ed mieszka w Kryptopolis. Handluje braminami. To jeden z moich stałych dostawców. Kryptopolis leży całkiem niedaleko stąd.}
{845}{}{Mówiłem ci już, jest tutaj. [Vic wskazuje miejsce na twoim Pip-Boyu 2000]}
{900}{}{Dowiadujesz się, że Vic jest kupcem.}
{1000}{}{Muszę cię o coś zapytać.}
{1100}{}{Zdrów jak ryba, szefie. Co teraz?}
{1200}{}{Do wesela się zagoi, szefie.}
{1300}{}{Trochę się podkurowałem, szefie, ale bywało lepiej.}
{1400}{}{Staram się, szefie, ale ledwie zipię. Nie wiem, jak długo pociągnę.}
{1500}{}{Jak sobie życzysz, szefie.}
{1501}{}{Tutaj? Właśnie tutaj? Dobra, ty tu rządzisz.}
{1502}{}{Dobra, szefie. Będę tu czekał, aż do twojego powrotu. Ale wrócisz tu, prawda?}
{1503}{}{Jak sobie życzysz. Nie ruszam się z miejsca.}
{1504}{}{Naturalnie, szefie.}
{1600}{}{Jak sobie życzysz.}
{1601}{}{Dobry pomysł, szefie.}
{1602}{}{Główka pracuje, co, szefie?}
{1603}{}{Dobra, szefie. Coś jeszcze?}
{1604}{}{Już odkładam, szefie.}
{1605}{}{Żaden problem, szefie.}
{1606}{}{Zrobione, szefie.}
{1700}{}{Dobra, szefie.}
{1701}{}{Ma być blisko - będzie blisko.}
{1702}{}{Ty tu rządzisz, szefie.}
{1703}{}{Będę cię osłaniał, szefie.}
{1704}{}{Jak papużki nierozłączki, szefie.}
{1705}{}{Jak sobie życzysz, szefie.}
{1706}{}{Tak jest, szefie.}
{1800}{}{Dobra, będę się kręcił gdzieś w pobliżu ciebie, szefie.}
{1801}{}{Dobrze, będę uważał, szefie.}
{1802}{}{No to trochę sobie pospaceruję, szefie.}
{1803}{}{Dobra, szefie.}
{1900}{}{Dobra, szefie. Będę się trzymał na dystans.}
{1901}{}{Jak sobie życzysz, szefie.}
{1902}{}{Już się robi, szefie.}
{1903}{}{Trzymam się z dala, szefie.}
{1904}{}{Już się oddalam, szefie.}
{1905}{}{Większy dystans... Przyjąłem, szefie.}
{1906}{}{Dobra, szefie.}
{2000}{}{Eee, szefie? Prowadzisz ze sobą niezłe stadko. Może lepiej będzie jak tu sobie poczekam.}
{2100}{}{Przerażasz mnie, szefie. Co ci się stało? Wyglądasz... no... strasznie. Może lepiej będzie jak sobie jeszcze trochę poczekam...}
{2200}{}{Jasna sprawa, szefie!}
{2201}{}{Jestem na rozkazy, szefie.}
{2202}{}{Już się robi, szefie.}
{2203}{}{Powiedz tylko słowo, szefie.}
{2204}{}{Świetnie! Ruszajmy.}
{2205}{}{Wspaniale!}
{2206}{}{Ty tu rządzisz, szefie!}
{2207}{}{Nie zawiodę cię. Zrobię co w mojej mocy!}
{2208}{}{Tym razem będę ostrożniejszy, spokojna głowa!}
{2209}{}{Wiedziałem, że kiedyś mi wybaczysz... hmmm. No więc, eee, szefie, co dalej?}
{2210}{}{Nie zawiodę cię, szefie!}
{2211}{}{Jesteś super, szefie!}
{2212}{}{Wiedziałem, że jeszcze nie jestem za stary na przygodę. Po prostu miałem trochę pecha, co, szefie?}
{2300}{}{Od Eda. Gość handluje braminami w Kryptopolis. Zdarzyło ci się tam zawędrować? Pokażę ci gdzie to jest na tej twojej śmiesznej mapie.}
{2305}{}{Kryptopolis. Tutaj. Pokażę ci na tej twojej fikuśnej mapie.}
{2310}{}{Powinien gdzieś się tu kręcić.}
{2311}{}{Kryptopolis. Rzuć okiem na tę swoją fikuśną mapę.}
{2403}{}{Skąd wziąłeś manierkę Krypty 13?}
{2404}{}{Nieważne.}
{2500}{}{Dobra, szefie.}
{2501}{}{Pytaj o co chcesz, szefie.}
{2502}{}{Pomogę ci w miarę możliwości, szefie.}
{2503}{}{Chyba nie wpadłem w kłopoty, co szefie?}
{2504}{}{Zrobiłem coś nie tak, szefie?}
{2505}{}{Spoko.}
{2600}{}{Co teraz, szefie?}
{2601}{}{Jaki masz plan, szefie?}
{2602}{}{Robię co mogę, szefie.}
{2603}{}{Co mogę dla ciebie zrobić, szefie?}
{2604}{}{Zmiana planów, szefie?}
{2605}{}{Zmiana strategii, szefie?}
{2700}{}{Szefie, nieźle oberwałem. Musimy znaleźć jakiegoś lekarza. Nie wiem, czy jeszcze na coś ci się przydam.}
{2701}{}{Potrzebuję lekarza, szefie. Naprawdę źle ze mną. Nie wiem, czy dam radę jeszcze walczyć.}
{2702}{}{Szefie, poważnie oberwałem. Każ Lenny'emu rzucić na to okiem.}
{2800}{}{Hej, szefie. Mam już do ciebie dołączyć?}
{2801}{}{Hej, szefie. Chciałem ci tylko powiedzieć, że nie mam nic przeciwko czekaniu tu na ciebie.}
{2802}{}{Potrzebujesz mnie już, szefie? Tym razem lepiej się postaram.}
{2803}{}{Bałem się, że już nie wrócisz, szefie. Miło cię znów widzieć.}
{2804}{}{Znowu szukasz towarzystwa?}
{2805}{}{Jestem gotowy, szefie.}
{2806}{}{Wiedziałem, że mnie tu nie zostawisz.}
{2807}{}{Potrzebujesz wsparcia?}
{2808}{}{Masz coś do naprawienia, prawda? Ja to naprawię, szefie!}
{2809}{}{Spokojna głowa, szefie. Sulik i ja jakoś się dogadamy.}
{2810}{}{Ruszajmy.}
{2811}{}{Zostań tutaj. Niedługo wrócę.}
{2812}{}{Ja iść.}
{3100}{}{Co? Ummm... dobra, szefie. Skoro tak uważasz.}
{3101}{}{Mogę założyć coś innego, szefie. Trochę się obawiam.}
{3102}{}{Niech będzie... ale nie zostawisz mnie tutaj, co szefie?}
{3103}{}{Ale... znaczy... dobra, szefie. Już zdejmuję.}
{3200}{}{No cóż.... Nieźle sobie radzę z bronią palną. Potrafię strzelać z prawie wszystkich strzelb i karabinów, no i z pistoletów. 'Mogę' walczyć nożem. Potrafię również całkiem mocno rzucać, chociaż nie celuję najlepiej... w zasadzie, to celuję fatalnie... Przepraszam, szefie. Ja się naprawdę bardzo staram.}
{3201}{}{Jak już mówiłem, szefie, nie przepadam za ciężką bronią. Poradzę sobie ze strzelbami, karabinami i pistoletami. Jak będzie BARDZO źle, to może być zwykły nóż albo coś do rzucania.}
{3300}{}{'Mogę' walczyć nożem. Potrafię również całkiem mocno rzucać, chociaż nie celuję najlepiej... w zasadzie, to celuję fatalnie... Przepraszam, szefie. Ja się naprawdę bardzo staram.}
{3301}{}{Jak już wspominałem, szefie. Noże i jakaś broń do rzucania. Tylko nie oczekuj, że trafię w dziesiątkę.}
{3400}{}{Mam tego po dziurki w nosie!}
{3401}{}{Urwę ci łeb! Nie pozwolę ci krzywdzić mojej rodziny!}
{4000}{}{Tam?}
{4001}{}{Tak lepiej, szefie?}
{4002}{}{Tutaj może być?}
{4003}{}{Tak, szefie.}
{4004}{}{Co?}
{4005}{}{Gdzie idziemy?}
{4006}{}{Idziemy, szefie?}
{4007}{}{Już idę.}
{4008}{}{Przepraszam, szefie.}
{4009}{}{Lepiej?}
{4010}{}{Uff.}
{4011}{}{Może być, szefie?}
{4012}{}{Stanę sobie tutaj.}
{4013}{}{Może się trochę przesunę.}
{4100}{}{Szefie! Nie czuję się najlepiej.}
{4101}{}{Potrzebuję lekarza.}
{4102}{}{O raju. To dopiero boli.}
{4103}{}{Au!}
{4104}{}{Auć.}
{4105}{}{Niech to szlag.}
{4106}{}{Lekarza!}
{4107}{}{Ledwie zipię.}
{4200}{}{Nigdy mi się tu nie podobało.}
{4201}{}{Czemu tu tak czysto?}
{4202}{}{Czujesz coś, szefie?}
{4203}{}{Wiesz co, szefie? Jak już skończymy, moja noga nigdy tu nie postanie. Jak ja mogłem nazywać to domem?}
{4204}{}{Jest tu jeszcze bardziej brudno niż kiedyś.}
{4205}{}{Nie zostaniemy tu chyba zbyt długo, co szefie?}
{4206}{}{To miejsce nigdy się nie zmieni.}
{4207}{}{Wiesz co, szefie, nie będę tęsknił za tym miejscem.}
{4208}{}{Całe szczęście, że nie muszę już tu gnić. Dzięki, szefie.}
{4209}{}{Jestem twoim dłużnikiem, szefie.}
{4210}{}{Jej, ale się tu pozmieniało.}
{4211}{}{Nie było mnie tu od wieków.}
{4212}{}{Osiądę tu na starość.}
{4213}{}{Mógłbym tu otworzyć mały warsztat.}
{4300}{}{Ach, co za widok! To jest... był mój lokal. Ale przecież ty już o tym wiesz, prawda, szefie?}
{4400}{}{Sulik, przestań się tak na mnie gapić.}
{4401}{}{Szefie, Sulik znów się na mnie gapi!}
{4402}{}{Ładny kundel.}
{4500}{}{La la la...}
{4501}{}{Tururu rum.}
{4502}{}{Czekam na szefa....}
{4503}{}{Czekam tu na szefa.}
{4504}{}{Tak sobie czekam.}
{4505}{}{Szef na pewno o mnie nie zapomni...}
{4506}{}{Puk puk... kto tam... cholera. Jak to szło....}
{4507}{}{Ciągle czekam.}
{4508}{}{Co to za zapach?}
{4509}{}{Jest tu coś do naprawy?}
{4510}{}{Tak sobie... czekam na szefa.}
{4511}{}{Starszy, doświadczony mężczyzna marnuje najlepsze lata swojego życia stojąc jak słup soli.}
{4512}{}{Oddam królestwo za gumę do żucia... ile to już lat minęło.}
{4513}{}{Muszę skończyć z handlem starociami. Same z tym kłopoty.}
{4514}{}{To czekanie jest takie męczące...}
{4600}{}{Dzięki, szefie.}
{4601}{}{Dziękuję.}
{4602}{}{Na pewno wiesz co robisz?}
{4603}{}{Może po prostu trochę odpoczniemy?}
{4604}{}{Rozbijamy obóz?}
{4605}{}{Aż tak ze mną źle?}
{4700}{}{Tylko nie za dużo, szefie.}
{4701}{}{Skoro nalegasz, szefie.}
{4702}{}{Szefie, moja głowa tak naprawdę nie wybuchnie, prawda?}
{4703}{}{Wiesz co, szefuniu, zaczyna mi się tu podobać.}
{4704}{}{Dziwnie się czuję, szefie.}
{4705}{}{Na pewno chcesz to na mnie zmarnować?}
{4706}{}{Dobra, szefie. Skoro tak trzeba.}
{4707}{}{Dzięki, szefie.}
{4708}{}{Nieźle!}
{5000}{}{Teraz jestem trochę głodny. Pogadamy znowu u Mamuśki.}
{5500}{}{Chyba jest złamana, szefie. Lepiej ją obejrzyj.}
{5501}{}{Chyba mam gorączkę, szefie. Lepiej to sprawdź.}
{5502}{}{Czuje się jakbym został otruty, szefie. Lepiej to sprawdź.}
