{100}{}{Widzisz łowcę niewolników.}
{150}{}{Skupia całą swoją uwagę na drzwiach.}
{200}{}{Hej! Łapy przy sobie.}
{201}{}{Dość tego!}
{210}{}{Kłopotów?}
{211}{}{Lata praktyki?}
{212}{}{Hmmm.}
{220}{}{Proszę bardzo.}
{230}{}{Hej, jak leci?}
{231}{}{Hej, jesteś z nami, co? Super. Mam nadzieję, że mamy jakieś wspólne cechy.}
{232}{}{O czym chcesz porozmawiać?}
{233}{}{Kto tam jest?}
{234}{}{Porozmawiajmy o Vicu...}
{235}{}{Dobra, dzięki.}
{236}{}{Muszę już iść.}
{237}{}{Robota?}
{238}{}{Meko veek?}
{239}{}{Ugruk.}
{240}{}{Ruru!}
{250}{}{Nazywa się Vic - to kupiec, który zepsuł coś mojemu szefowi, czy coś w tym stylu. Nie jestem pewien.}
{251}{}{Nazywa się Vic - to kupiec, który naraził się czymś szefowi, czy coś w tym stylu. Nie na sto procent.}
{252}{}{Aaa, on? Taaa, to jakiś kupiec. Myślę, że coś zepsuł, ale nie jestem pewien. Czemu pytasz? Znasz go?}
{253}{}{Aaa, on? Taaa, to jakiś kupiec. Myślę, że coś zepsuł, ale nie jestem pewien. Czemu pytasz? Znasz go?}
{254}{}{Taak?}
{255}{}{Dlaczego go pilnujecie?}
{256}{}{Kto jest twoim szefem?}
{257}{}{Czy mogę się z nim zobaczyć?}
{258}{}{Potrafię naprawić wiele rzeczy. Może mogę jakoś pomóc?}
{259}{}{Mam doświadczenie naukowe, może mogę jakoś pomóc?}
{260}{}{Drzwi są zamknięte. Mógłbyś je otworzyć?}
{261}{}{Dziękuję.}
{275}{}{Dzięki za kasę. Możesz się z nim zobaczyć. Koleś nie jest zbyt zabawny. Nie może opuszczać pokoju bez zgody Metzgera. Zrozumiano?}
{276}{}{Dobra, możesz z nim pogadać. Koleś nie jest zbyt zabawny. Nie może opuszczać pokoju bez zgody Metzgera. Kapujesz?}
{277}{}{W porządku.}
{285}{}{Żeby mieć pewność, że żadna plugawa gnida nie będzie mu przeszkadzać, gdy pracuje dla szefa, ale też po to, żeby nie uciekł.}
{286}{}{To proste, żeby nie uciekł - przynajmniej tak mi się wydaje. Naprawia jakieś radio czy coś takiego.}
{287}{}{Kto jest twoim szefem?}
{288}{}{Czy mogę się z nim zobaczyć?}
{289}{}{Czy mogę się z nim zobaczyć?}
{290}{}{Dzięki.}
{295}{}{Jasne. Myślę, że możesz się z nim zobaczyć, zwłaszcza że jesteś z nami.}
{296}{}{Jasne. Tak sądzę. Nie jest niczym zajęty, nigdzie nie może pójść, więc czemu nie.}
{297}{}{Czy w takim razie mógłbyś otworzyć drzwi?}
{298}{}{Dobra, dzięki.}
{305}{}{Jasne. Nie sądziłem, że chcesz się z nim zobaczyć właśnie teraz. Myślałem, że pytasz tylko z ciekawości.}
{306}{}{Dziękuję.}
{310}{}{Eee? Jesteś w tym gównianym mieście i nie wiesz? To jest siedziba łowców niewolników.}
{311}{}{Uff, a może dorobił się jakiegoś imienia...}
{312}{}{Naprawdę? Myślałem, że jestem w Kansas.}
{313}{}{Dobra, dzięki.}
{320}{}{Gdzie? Nigdy nie słyszałem o tym miejscu. To jest Nora, o której zresztą też wiem niewiele.}
{321}{}{Debil.}
{322}{}{Uff, dobra. Dzięki.}
{330}{}{Sukinsyn. Metzger to szef łowców niewolników. Trzyma w swojej śmierdzącej łapie całą okolicę.}
{331}{}{Kurwa. To jest ostatnie miejsce, w którym taka panienka jak ty chciałaby się znaleźć. Metzger to szef łowców niewolników.}
{332}{}{Uff, w takim razie gdzie jest jego melina?}
{333}{}{W porządku. Na razie.}
{340}{}{W prawo, przez tamte drzwi.}
{341}{}{Dziękuję.}
{350}{}{Nie rozumiem.}
{351}{}{Hmph.}
{360}{}{Vic nie przyjmuje gości.}
{361}{}{Taaa, to jest Vic.}
{362}{}{Seve?}
{363}{}{Surek?}
{364}{}{Gaw.}
{370}{}{Jasne, możesz się z nim widzieć.}
{371}{}{Jasne, możesz się z nim widzieć. Tylko otworzę drzwi.}
{372}{}{Dzięki.}
{380}{}{Naprawdę? Jestem pewien, że szef to doceni. Nie chcielibyśmy kolejnej ucieczki.}
{381}{}{Dziękuję.}
{390}{}{Nie. Teraz jest zajęty - pracuje nad jakimś projektem dla szefa.}
{391}{}{Nie ma mowy. Rozkaz bezpośrednio od szefa.}
{392}{}{Może tak, a może nie, masz MOJE pieniądze?}
{393}{}{Muszę zadać mu kilka pytań.}
{394}{}{No stary, daj spokój. Pozwól mi zamienić z nim kilka słów.}
{395}{}{Tak. Tutaj.}
{396}{}{Nie. A jak wrócę, to ma cię tu już nie być!}
{397}{}{Kto jest twoim szefem?}
{398}{}{Nieważne. Cześć.}
{410}{}{Przestań mi zawracać dupę. Pogadaj z Metzgerem. On tu rządzi.}
{411}{}{Zostaw mnie w spokoju! Masz jakiś problem?}
{412}{}{Mówiłem, porozmawiaj z Metzgerem!}
{413}{}{Dobra, poddaję się! Możesz z nim porozmawiać, ale toto zostawiasz tutaj! Nie może wyjść z tego pokoju. Kapujesz? A teraz spierdalaj!}
{414}{}{W porządku.}
{415}{}{Dzięki!}
{430}{}{Taaa, pogadaj z Metzgerem. Na pewno ma jakąś robotę. Mówił ostatnio, że potrzeba mu nowych ludzi.}
{431}{}{Taaa, pogadaj z Metzgerem. Na pewno ma jakąś robotę. Mówił ostatnio, że potrzebuje nowego człowieka... ale jestem pewien, że się nadasz.}
{432}{}{Pogadaj z Metzgerem.}
{433}{}{Ruru?}
{434}{}{Hm?}
{435}{}{Och.}
{450}{}{Brać go chłopcy.}
{451}{}{Brać ją chłopcy.}
{460}{}{Jest zajęty.}
{461}{}{Proszę, nie będziemy opuszczać pokoju. Obiecuję.}
{462}{}{A może zajmiemy się czymś innym - finansami?}
{463}{}{W porządku. Na razie.}
{470}{}{Więc, uch... No nie wiem. Myślę, że zależy ci na tej rozmowie. $300 i wpuszczam cię do środka.}
{471}{}{Pojebało cię. To za dużo!}
{472}{}{Ale z ciebie kutwa, koleś!}
{473}{}{Jasne.}
{474}{}{Nie mam tyle.}
{480}{}{Świetnie, widzisz jak się o ciebie troszczę.}
{481}{}{W porządku.}
{482}{}{Dobra.}
{490}{}{Nie.}
{491}{}{Powiedziałem nie. Teraz spierdalaj. Musisz pogadać z Metzgerem.}
{492}{}{W porządku.}
{500}{}{Szkoda że się do nas nie przyłączyłeś.}
{501}{}{Musisz przyłączyć się do gidili.}
{502}{}{Po prostu rób to co kryjomu.}
{503}{}{Mam nadzieję, że Vic nie pracuje tylko dla was.}
{504}{}{Lepiej rób swoje.}
{505}{}{Może złapię cię, gdy będziesz uciekać.}
{506}{}{Jak leci?}
{507}{}{Znowu się widzimy.}
