{100}{}{Widzisz niewolnika.}
{101}{}{Widzisz Vica.}

{150}{}{Ten niewolnik jest pilnie strze¿ony.}
{151}{}{To Vic!}
{152}{}{[Rozmawiaj.]}

# Node 1
{153}{}{Powiedz mu, ¿e nie mogê... czekaj. Kim jesteœ? Nie jesteœ £owc¹. Co tu robisz?}
{154}{}{Nazywam siê }
{155}{}{. Chcê ciê st¹d wydostaæ.}
{156}{}{Jestem }
{157}{}{, ale czemu siedzisz tu zamkniêty?}
{158}{}{Mo¿esz mi powiedzieæ, gdzie jest Krypta 13?}
{159}{}{Jestem }
{160}{}{. Zaraz wracam.}
{161}{}{Dubba iba }
{162}{}{.}

# Node 2
{163}{}{Metzger ci¹gle jest na mnie z³y, chocia¿ naprawi³em to jego cholerne radio. Grozi, ¿e gdzieœ mnie sprzeda! Zrobiê co tylko zechcesz, ale pomó¿ mi siê st¹d wydostaæ.}
{164}{}{OK, spróbujê.}
{165}{}{Przykro mi, nie mam czasu. Pa.}
{166}{}{Ktoo.}

# Node 3
{167}{}{Och, witaj ponownie. To cholerne radio samo siê nie naprawi. Jak ja niby mam to zrobiæ?}
{168}{}{Gdzie mogê znaleŸæ czêœci?}
{169}{}{Mo¿e mi uda siê je naprawiæ.}
{170}{}{Mo¿e przyda ci siê moje radio?}
{171}{}{Zobaczê co siê da zrobiæ.}
{172}{}{Spa pa?}

# Node 4
{173}{}{Wiem co trzeba zrobiæ, potrzebujê tylko odpowiednich czêœci. W mojej szopie w Klamath mam stare radio, które mog³oby mi siê przydaæ. Wiesz gdzie urzêduj¹ Duntonowie? Moja szopa jest... no, na wschód od nich.}
{174}{}{Masz na myœli to radio?}
{175}{}{Poszukam go.}
{176}{}{Hmmm... Jeszcze tu wrócê.}

# Node 4b
{206}{}{Jest tutaj. [Pokazuje na mapie.]}

# Node 5
{177}{}{Œwietnie! Teraz naprawiê radio bez ¿adnych k³opotów.}
{178}{}{Dobra, pogadam z Metzgerem.}

# Node 6
{179}{}{Dziêki.}
{180}{}{Pa.}

# Node 7
{181}{}{S³ucham? Przykro mi, ale nie rozumiem.}
{182}{}{[Mrukniêcie]}

# Node 8
{183}{}{Dziêkujê! Jestem twoim d³u¿nikiem. Jak ja ci siê odwdziêczê?}
{184}{}{Powiedz mi gdzie jest Krypta 13.}
{186}{}{ChodŸ ze mn¹, przyda mi siê pomoc.}
{187}{}{Nie ma o czym mówiæ. Do widzenia.}
{188}{}{Cu-ke-rek?}

# Node 9
{189}{}{Krypta 13? Niedaleko st¹d jest Kryptopolis. Tam wiedz¹ o takich rzeczach.}
{190}{}{Chcesz siê tam ze mn¹ wybraæ?}
{191}{}{Dziêki. ¯egnaj.}

# Node 10
{192}{}{Pewnie! Chêtnie do ciebie do³¹czê! Tego starego psa jeszcze staæ na to i owo. Mo¿esz na mnie liczyæ! Mimo tego co mówi Metzger, nieŸle sobie radzê z naprawianiem starego z³omu.}
{193}{}{Œwietnie, zatem w drogê.}
{194}{}{Witaj na pok³adzie.}
{195}{}{Dobra.}
{196}{}{Vic moja najlepsza przyjació³.}

# Node 11
{197}{}{Chcesz mi pomóc w poszukiwaniach?}
{198}{}{Œwietnie! Dziêki.}

# Node 12 OLD IF IN PARTY. REMOVED NODE. Lines 199, 200, 202 (Don't know where 201 is)

# Node 13
{203}{}{Kryptopolis jest na wschód st¹d. Poka¿ê ci na tej twojej mapie.}
{204}{}{Dziêki.}

# Node 14
{220}{}{Cholera. NieŸle, ale potrzebujê starego radia z mojej szopy w Klamath. Móg³bym z niego wyci¹gn¹æ potrzebne czêœci.}

# used in node 12 REMOVED 230 that was here. Node 12, removed. was What else do you need to know?

# Node 15
{300}{}{Có¿, pewnie móg³bym ci pomóc, ale najpierw muszê siê st¹d jakoœ wydostaæ.}
{301}{}{Mówi³em ci ju¿. Jeœli pomo¿esz mi siê st¹d wydostaæ, zrobiê co tylko zechcesz.}
{302}{}{Tylko jak to zrobiæ?}
{303}{}{No to radŸ sobie sam.}
{304}{}{Dobrze, zobaczê co siê da zrobiæ.}

# Node 2b
{350}{}{Myœlisz, ¿e jesteœ w stanie mi pomóc?}
{351}{}{Metzger wci¹¿ nie chce mnie puœciæ.}
{352}{}{D³u¿ej tego nie wytrzymam.}
{353}{}{Zrobiê co zechcesz, tylko mnie st¹d wydostañ.}
{354}{}{Odp³acê ci za wszystko z nawi¹zk¹!}

# 3b
{400}{}{Kiedy wreszcie zajrzysz do mojej szopy w Klamath? Naprawdê potrzebujê tego radia. Metzger z dnia na dzieñ bardziej siê na mnie z³oœci.}

# water flask question, Question used in Node 9 and Node 1010
{450}{}{Sk¹d masz tê manierkê?}
{451}{}{Mia³em kiedyœ tak¹ manierkê z du¿¹ ¿ó³t¹ trzynastk¹. Sk¹d masz swoj¹?}

# Additions to Node 11
{500}{}{A, tak. Przypominam sobie. Kupi³em j¹ od Eda. Handluje braminami w Kryptopolis.}
{501}{}{Manierka? A, czekaj! Tak, mia³em ich kilka. NieŸle siê sprzedawa³y. Kupowa³em je od Eda. Facet handluje braminami w Kryptopolis.}
{502}{}{Kryptopolis?}

# Node 1000, if said Boss many times.
{550}{}{Przestañ wreszcie mówiæ do mnie "szefie"!}

# Node 16
{600}{}{Nie ma sprawy, szefie!}
{601}{}{Mia³eœ przestaæ!!!}
{602}{}{Dobrze ju¿, dobrze.}

# Node 17
{650}{}{Nie ma sprawy, Wodzu!}
{651}{}{Uggg!}

{700}{}{Tyy przyjació³!}

# Node 1b - Added a line to node 1 for Vic
{710}{}{Powiedz mu, ¿e bez odpowiednich czêœci nic tu nie zdzia³am... czekaj. Kim jesteœ? Jakiœ nowy rekrut? Masz mi znowu daæ wycisk, co? To i tak bez znaczenia. Nie naprawiê tego z³omu.}

# 20. Here to get you out. (From 1)
{750}{}{Tak! Zrobisz to dla mnie? Zrobiê wszystko, tylko mnie st¹d uwolnij. Ca³y problem w tym, ¿e Metzger nie chce mnie puœciæ zanim nie naprawiê dla niego tego radia, a ja nie mam odpowiednich czêœci.}
{753}{}{Gdzie mogê znaleŸæ czêœci, których potrzebujesz?}
{754}{}{Zobaczê, co siê da zrobiæ.}

# 21. Why in this room? (From 1)
{760}{}{To d³uga historia. W wielkim skrócie: Metzger przetrzymuje mnie tu, ¿ebym naprawi³ to przeklête radio. Niestety, bez czêœci zamiennych nie dam rady! Czy ten cz³owiek nie mo¿e tego poj¹æ?}
{761}{}{Jestem tu, ¿eby ciê uwolniæ.}
{764}{}{Nie wiem. Czeœæ.}

# 22. How do we do that?
{800}{}{Muszê jakoœ naprawiæ ten odbiornik. Jeœli mi w tym pomo¿esz, mo¿e Metzger da siê jakoœ ub³agaæ.}
{801}{}{Gdzie znajdê potrzebne czêœci?}
{803}{}{W¹tpiê. Mi³ej zabawy.}

# 23. In Mom's, never joined party. (From WTG)
{810}{}{Dlaczego Mamuœka musia³a zgin¹æ... Zapewne by³y jakieœ powody... Przepraszam, szefie. Nie powinienem tak ciê mêczyæ. To bardzo z³e miasto. Pewnie zrobi³a coœ bardzo z³ego.}
{811}{}{Hej, szefie. Dziêki za wypl¹tanie mnie z tego bagna. Potrzebujesz czegoœ? Wiesz, Mamuœka by³a tak mi³a i dawa³a mi jeœæ podczas twojej nieobecnoœci. Pomagam jej trochê...}
{812}{}{Czeœæ.}
{813}{}{Oooh.}
{814}{}{Papa.}

# Additions to Node 9
{823}{}{Gdzie znajdê tego twojego kumpla... Eda?}

# Additions to Node 10
{830}{}{To chyba nie jest najlepszy pomys³. Tylko bym ci zawadza³. Po œmierci Mamuœki nic mnie ju¿ nie trzyma w tym mieœcie. Muszê wyjechaæ... sam... Mo¿e siê jeszcze spotkamy. Dziêkujê za wypl¹tanie mnie z k³opotów. ¯egnaj.}
{831}{}{To chyba nie jest najlepszy pomys³. Z trudem dajesz sobie radê, ja bym ci dodatkowo zawadza³. Zostanê tutaj. Obiady Mamuœki przypominaj¹ mi moj¹ by³¹ ¿onê...}
{832}{}{Zrobi³bym to, s³owo. Zrobi³bym dla ciebie prawie wszystko. Ale... nie wygl¹dasz na kogoœ, kto potrafi dowodziæ ludŸmi. Tylko bym ci zawadza³. Posiedzê trochê u Mamuœki. Brakowa³o mi domowego jedzenia...}
{833}{}{Przykro mi, szefie. Chyba masz ju¿ niez³y t³ok. Po œmierci Mamuœki nic mnie ju¿ nie trzyma w tym mieœcie. Muszê wyjechaæ... sam... Mo¿e siê jeszcze spotkamy. Dziêkujê za wypl¹tanie mnie z k³opotów. ¯egnaj.}
{834}{}{Chyba masz ju¿ doœæ towarzyszy, szefie. Zaczekam tu, a¿ zwolni siê jakieœ miejsce. Obiady Mamuœki przypominaj¹ mi moj¹ by³¹ ¿onê... Jeszcze nie wiem czy to dobrze, czy Ÿle...}
{835}{}{Bardzo chêtnie, szefie, ale chwilowo nie masz ju¿ chyba dla mnie doœæ miejsca. Lepiej zajrzê do Mamuœki. Wpadnij tam, jak znajdziesz dla mnie jak¹œ robotê.}

# Additions to Node 11
{840}{}{Ed mieszka w Kryptopolis. Handluje braminami. To jeden z moich sta³ych dostawców. Kryptopolis le¿y ca³kiem niedaleko st¹d.}

# Additions to Node 13
{845}{}{Mówi³em ci ju¿, jest tutaj. (Wskazuje miejsce na twoim Pip-Boy'u)}

{900}{}{Dowiadujesz siê, ¿e Vic jest kupcem.}

# 1000 in party dialog
{1000}{}{Muszê ciê o coœ zapytaæ.}

# 1001 After healing
{1100}{}{Zdrów jak ryba, szefie. Co teraz?}
{1200}{}{Do wesela siê zagoi, szefie.}
{1300}{}{Trochê siê podkurowa³em, szefie, ale bywa³o lepiej.}
{1400}{}{Staram siê, szefie, ale ledwie zipiê. Nie wiem, jak d³ugo poci¹gnê.}

# 1002 I need you to wait here until I come back
{1500}{}{Jak sobie ¿yczysz, szefie.}
{1501}{}{Tutaj? W³aœnie tutaj? Dobra, ty tu rz¹dzisz.}
{1502}{}{Dobra, szefie. Bêdê tu czeka³, a¿ do twojego powrotu. Ale wrócisz tu, prawda?}
{1503}{}{Jak sobie ¿yczysz. Nie ruszam siê z miejsca.}
{1504}{}{Naturalnie, szefie.}

# 1003 Put your weapon away.
{1600}{}{Jak sobie ¿yczysz.}
{1601}{}{Dobry pomys³, szefie.}
{1602}{}{G³ówka pracuje, co, szefie?}
{1603}{}{Dobra, szefie. Coœ jeszcze?}
{1604}{}{Ju¿ odk³adam, szefie.}
{1605}{}{¯aden problem, szefie.}
{1606}{}{Zrobione, szefie.}

# 1004 Stay close to me
{1700}{}{Dobra, szefie.}
{1701}{}{Ma byæ blisko - bêdzie blisko.}
{1702}{}{Ty tu rz¹dzisz, szefie.}
{1703}{}{Bêdê ciê os³ania³, szefie.}
{1704}{}{Jak papu¿ki nieroz³¹czki, szefie.}
{1705}{}{Jak sobie ¿yczysz, szefie.}
{1706}{}{Tak jest, szefie.}

# 1005 Don't get too far away.
{1800}{}{Dobra, bêdê siê krêci³ gdzieœ w pobli¿u ciebie, szefie.}
{1801}{}{Dobrze, bêdê uwa¿a³, szefie.}
{1802}{}{No to trochê sobie pospacerujê, szefie.}
{1803}{}{Dobra, szefie.}

# 1006 We should spread out a bit
{1900}{}{Dobra, szefie. Bêdê siê trzyma³ na dystans.}
{1901}{}{Jak sobie ¿yczysz, szefie.}
{1902}{}{Ju¿ siê robi, szefie.}
{1903}{}{Trzymam siê z dala, szefie.}
{1904}{}{Ju¿ siê oddalam, szefie.}
{1905}{}{Wiêkszy dystans... Przyj¹³em, szefie.}
{1906}{}{Dobra, szefie.}

# 1100a Rejoin: Crowded
{2000}{}{Eee, szefie? Prowadzisz ze sob¹ niez³e stadko. Mo¿e lepiej bêdzie jak tu sobie poczekam.}

# 1100b Rejoin: Additional NPC response, PC Charisma 1
{2100}{}{Przera¿asz mnie, szefie. Co ci siê sta³o? Wygl¹dasz... no... strasznie. Mo¿e lepiej bêdzie jak sobie jeszcze trochê poczekam...}

# 1100c Rejoin:
{2200}{}{Jasna sprawa, szefie!}
{2201}{}{Jestem na rozkazy, szefie.}
{2202}{}{Ju¿ siê robi, szefie.}
{2203}{}{Powiedz tylko s³owo, szefie.}
{2204}{}{Œwietnie! Ruszajmy.}
{2205}{}{Wspaniale!}
{2206}{}{Ty tu rz¹dzisz, szefie!}
{2207}{}{Nie zawiodê ciê. Zrobiê co w mojej mocy!}
{2208}{}{Tym razem bêdê ostro¿niejszy, spokojna g³owa!}
{2209}{}{Wiedzia³em, ¿e kiedyœ mi wybaczysz... hmmm. No wiêc, eee, szefie, co dalej?}
{2210}{}{Nie zawiodê ciê, szefie!}
{2211}{}{Jesteœ super, szefie!}
{2212}{}{Wiedzia³em, ¿e jeszcze nie jestem za stary na przygodê. Po prostu mia³em trochê pecha, co, szefie?}

# 1007 Vault 13 Flask?
{2300}{}{Od Eda. Goœæ handluje braminami w Kryptopolis. Zdarzy³o ci siê tam zawêdrowaæ? Poka¿ê ci gdzie to jest na tej twojej œmiesznej mapie.}

# 1008 Where's Ed again? Not Marked
{2305}{}{Kryptopolis. Tutaj. Poka¿ê ci na tej twojej fikuœnej mapie.}

# 1009 Where's Ed again?
{2310}{}{Powinien gdzieœ siê tu krêciæ.}
{2311}{}{Kryptopolis. Rzuæ okiem na tê swoj¹ fikuœn¹ mapê.}

# 1010 Other Questions
{2403}{}{Sk¹d wzi¹³eœ manierkê Krypty 13?}
{2404}{}{Niewa¿ne.}

# 1011 Other questions greeting (From 1000)
{2500}{}{Pewnie, szefie.}
{2501}{}{Pytaj o co chcesz, szefie.}
{2502}{}{Pomogê ci w miarê mo¿liwoœci, szefie.}
{2503}{}{Chyba nie wpad³em w k³opoty, co szefie?}
{2504}{}{Zrobi³em coœ nie tak, szefie?}
{2505}{}{Oczywiœcie.}

# 1012 Standard Greeting, (WTG) Moved From Node 1000
{2600}{}{Co teraz, szefie?}
{2601}{}{Jaki masz plan, szefie?}
{2602}{}{Robiê co mogê, szefie.}
{2603}{}{Co mogê dla ciebie zrobiæ, szefie?}
{2604}{}{Zmiana planów, szefie?}
{2605}{}{Zmiana strategii, szefie?}

# 1013 Crippled
{2700}{}{Szefie, nieŸle oberwa³em. Musimy znaleŸæ jakiegoœ lekarza. Nie wiem, czy jeszcze na coœ ci siê przydam.}
{2701}{}{Potrzebujê lekarza, szefie. Naprawdê Ÿle ze mn¹. Nie wiem, czy dam radê jeszcze walczyæ.}
{2702}{}{Szefie, powa¿nie oberwa³em. Ka¿ Lenny'emu rzuciæ na to okiem.}

# 1014 Waiting
{2800}{}{Hej, szefie. Mam ju¿ do ciebie do³¹czyæ?}
{2801}{}{Hej, szefie. Chcia³em ci tylko powiedzieæ, ¿e nie mam nic przeciwko czekaniu tu na ciebie.}
{2802}{}{Potrzebujesz mnie ju¿, szefie? Tym razem lepiej siê postaram.}
{2803}{}{Ba³em siê, ¿e ju¿ nie wrócisz, szefie. Mi³o ciê znów widzieæ.}
{2804}{}{Znowu szukasz towarzystwa?}
{2805}{}{Jestem gotowy, szefie.}
{2806}{}{Wiedzia³em, ¿e mnie tu nie zostawisz.}
{2807}{}{Potrzebujesz wsparcia?}
{2808}{}{Masz coœ do naprawienia, prawda? Ja to naprawiê, szefie!}
{2809}{}{Spokojna g³owa, szefie. Sulik i ja jakoœ siê dogadamy.}
{2810}{}{Ruszajmy.}
{2811}{}{Zostañ tutaj. Nied³ugo wrócê.}
{2812}{}{Moja iœæ.}

# 1017 Remove armor: Yes
{3100}{}{Co? Ummm... dobra, szefie. Skoro tak uwa¿asz.}
{3101}{}{Mogê za³o¿yæ coœ innego, szefie. Trochê siê obawiam.}
{3102}{}{Niech bêdzie... ale nie zostawisz mnie tutaj, co szefie?}
{3103}{}{Ale... znaczy... dobra, szefie. Ju¿ zdejmujê.}

# 1018 Best Weapon
{3200}{}{No có¿.... NieŸle sobie radzê z broni¹ paln¹. Potrafiê strzelaæ z prawie wszystkich strzelb i karabinów, no i z pistoletów. 'Mogê' walczyæ no¿em. Potrafiê równie¿ ca³kiem mocno rzucaæ, chocia¿ nie celujê najlepiej... w zasadzie, to celujê fatalnie... Przepraszam, szefie. Ja siê naprawdê bardzo staram.}
{3201}{}{Jak ju¿ mówi³em, szefie, nie przepadam za ciê¿k¹ broni¹. Poradzê sobie ze strzelbami, karabinami i pistoletami. Jak bêdzie BARDZO Ÿle, to mo¿e byæ zwyk³y nó¿ albo coœ do rzucania.}

# 1019 Other weapons he can use.
{3300}{}{'Mogê' walczyæ no¿em. Potrafiê równie¿ ca³kiem mocno rzucaæ, chocia¿ nie celujê najlepiej... w zasadzie, to celujê fatalnie... Przepraszam, szefie. Ja siê naprawdê bardzo staram.}
{3301}{}{Jak ju¿ wspomina³em, szefie. No¿e i jakaœ broñ do rzucania. Tylko nie oczekuj, ¿e trafiê w dziesi¹tkê.}

# 1020 Hostile
{3400}{}{Mam tego po dziurki w nosie!}
{3401}{}{Urwê ci ³eb! Nie pozwolê ci krzywdziæ mojej rodziny!}

# 1101 Vic's being Pushed
{4000}{}{Tam?}
{4001}{}{Tak lepiej, szefie?}
{4002}{}{Tutaj mo¿e byæ?}
{4003}{}{Tak, szefie.}
{4004}{}{Co?}
{4005}{}{Gdzie idziemy?}
{4006}{}{Idziemy, szefie?}
{4007}{}{Ju¿ idê.}
{4008}{}{Przepraszam, szefie.}
{4009}{}{Lepiej?}
{4010}{}{Uff.}
{4011}{}{Mo¿e byæ, szefie?}
{4012}{}{Stanê sobie tutaj.}
{4013}{}{Mo¿e siê trochê przesunê.}

# 1102 BGF: Crippled
{4100}{}{Szefie! Nie czujê siê najlepiej.}
{4101}{}{Potrzebujê lekarza.}
{4102}{}{O raju. To dopiero boli.}
{4103}{}{Au!}
{4104}{}{Auæ.}
{4105}{}{Niech to szlag.}
{4106}{}{Lekarza!}
{4107}{}{Ledwie zipiê.}

# 1103 Removed

# 1104 BGF: Random on Specific Map
{4200}{}{Nigdy mi siê tu nie podoba³o.}
{4201}{}{Czemu tu tak czysto?}
{4202}{}{Czujesz coœ, szefie?}
{4203}{}{Wiesz co, szefie? Jak ju¿ skoñczymy, moja noga nigdy tu nie postanie. Jak ja mog³em nazywaæ to domem?}
{4204}{}{Jest tu jeszcze bardziej brudno ni¿ kiedyœ.}
{4205}{}{Nie zostaniemy tu chyba zbyt d³ugo, co szefie?}
{4206}{}{To miejsce nigdy siê nie zmieni.}
{4207}{}{Wiesz co, szefie, nie bêdê têskni³ za tym miejscem.}
{4208}{}{Ca³e szczêœcie, ¿e nie muszê ju¿ tu gniæ. Dziêki, szefie.}
{4209}{}{Jestem twoim d³u¿nikiem, szefie.}
{4210}{}{Jej, ale siê tu pozmienia³o.}
{4211}{}{Nie by³o mnie tu od wieków.}
{4212}{}{Osi¹dê tu na staroœæ.}
{4213}{}{Móg³bym tu otworzyæ ma³y warsztat.}

# 1105 BGF: for specific area on a map
{4300}{}{Ach, co za widok! To jest... by³ mój lokal. Ale przecie¿ ty ju¿ o tym wiesz, prawda, szefie?}

# 1106 Removed

# 1107 BGF: with Specific NPC
{4400}{}{Sulik, przestañ siê tak na mnie gapiæ.}
{4401}{}{Szefie, Sulik znów siê na mnie gapi!}
{4402}{}{£adny kundel.}

# 1108. BGF: Level Up, Not to be Placed in MSG file

# 1109. BGF: Waiting
{4500}{}{La la la...}
{4501}{}{Tururu rum.}
{4502}{}{Czekam na szefa....}
{4503}{}{Czekam tu na szefa.}
{4504}{}{Tak sobie czekam.}
{4505}{}{Szef na pewno o mnie nie zapomni...}
{4506}{}{Puk puk... kto tam... cholera. Jak to sz³o....}
{4507}{}{Ci¹gle czekam.}
{4508}{}{Co to za zapach?}
{4509}{}{Jest tu coœ do naprawy?}
{4510}{}{Tak sobie... czekam na szefa.}
{4511}{}{Starszy, doœwiadczony mê¿czyzna marnuje najlepsze lata swojego ¿ycia stoj¹c jak s³up soli.}
{4512}{}{Oddam królestwo za gumê do ¿ucia... ile to ju¿ lat minê³o.}
{4513}{}{Muszê skoñczyæ z handlem starociami. Same z tym k³opoty.}
{4514}{}{To czekanie jest takie mêcz¹ce...}

# 1110. PC used Healing on PC
{4600}{}{Dziêki, szefie.}
{4601}{}{Dziêki.}
{4602}{}{Na pewno wiesz co robisz?}
{4603}{}{Mo¿e po prostu trochê odpoczniemy?}
{4604}{}{Rozbijamy obóz?}
{4605}{}{A¿ tak ze mn¹ Ÿle?}

# 1111. PC used Drugs on NPC
{4700}{}{Tylko nie za du¿o, szefie.}
{4701}{}{Skoro nalegasz, szefie.}
{4702}{}{Szefie, moja g³owa tak naprawdê nie wybuchnie, prawda?}
{4703}{}{Wiesz co, szefuniu, zaczyna mi siê tu podobaæ.}
{4704}{}{Dziwnie siê czujê, szefie.}
{4705}{}{Na pewno chcesz to na mnie zmarnowaæ?}
{4706}{}{Dobra, szefie. Skoro tak trzeba.}
{4707}{}{Dziêki, szefie.}
{4708}{}{NieŸle!}

{5000}{}{Teraz jestem trochê g³odny. Pogadamy znowu u Mamuœki.}

#added by killap - NPC info
{5500}{}{Chyba jest z³amana, szefie. Lepiej j¹ obejrzyj.}
{5501}{}{Chyba mam gor¹czkê, szefie. Lepiej to sprawdŸ.}
{5502}{}{Czuje siê jakbym zosta³ otruty, szefie. Lepiej to sprawdŸ.}
