{100}{}{Mê¿czyzna w pancerzu wspomaganym.}
{101}{}{Artur, syn Uthera Pendragona.}
{102}{}{Ma rozpiêty rozporek.}
{103}{}{Witajcie podró¿nicy. Jestem Artur, syn Uthera Pendragona, z Bractwa Stali. Poszukujemy Œwiêtego Granatu Rêcznego z Antiochii. Mo¿e go widzia³eœ?}
{104}{}{Œwiête co sk¹d?}
{105}{}{OdpowiedŸ Gracza}
{106}{}{Unga.}
{107}{}{Nie mamy czasu. Jesteœmy zajêci.}
{108}{}{Szukamy Œwiêtego Granatu Rêcznego z Antiochii.}
{109}{}{Dla Bractwa Stali!}
{110}{}{Hmm... Afrykañska czy europejska jaskó³ka?}
{111}{}{Hej! To nie twoje, prawda?}
{112}{}{Uprzedzam ciê. Trzymaj rêce przy sobie.}
{113}{}{Basta. Moja cierpliwoœæ siê skoñczy³a.}
{114}{}{Œwiêty Granat Rêczny z Antiochii? To¿ to najwspanialsza broñ w swojej klasie.}
{115}{}{Dlaczego wiêc szukacie tak straszliwego orê¿a?}
{116}{}{My, Bractwo Stali, poszukujemy tej niszczycielskiej broni by nie wpad³a one w rêce niepowo³anych osób, które wykorzysta³y by Œwiêty Granat Rêczny z Antiochii do mrocznych i niecnych celów.}
{117}{}{Czemu?}
{118}{}{No... bo Bractwo Stali postawi³o sobie za szczytny cel obronê s³abych i bezsilnych, a t¹ zabawk¹ mo¿na komuœ zrobiæ niez³¹ krzywdê.}
{119}{}{Czemu?}
{120}{}{Umm... bo tak nakazuje moralnoœæ!}
{121}{}{Czemu?}
{122}{}{Ja... um... S³uchaj, jesteœmy bardzo zajêci. To jak - pomo¿esz nam czy nie? Wiesz gdzie jest Œwiêty Granat Rêczny z Antiochii?}
{123}{}{Tak.}
{124}{}{Nie.}
{125}{}{No to czemu nic nie mówisz?! Jeœli nam powiesz, wyruszymy bezzw³ocznie i nie bêdziemy ciê wiêcej k³opotaæ.}
{126}{}{[Wskazujesz losowo wybrany kierunek.]}
{127}{}{Dobra. Dziêkujê za pomoc. Oto nagroda za trudy.}
{128}{}{Czekajcie! Ja te¿ czegoœ szukam. Wiecie mo¿e gdzie mogê znaleŸæ œwiêtego GECKa?}
{129}{}{No to chyba nie mamy o czym rozmawiaæ. Ruszamy w drogê.}
{130}{}{[KONIEC]}
{131}{}{Cholerny wieœniak!}
{132}{}{[KONIEC]}
{133}{}{GECK, powiadasz? A tak, mamy nawet dwa. Nastêpny nam nie potrzebny. Mimo to, dziêki.}
{134}{}{Skoro macie dwa, mo¿e dalibyœcie mi jednego.}
{135}{}{Nie. Nie. Tego nie zrobimy. Nie mo¿esz tak szybko skoñczyæ swojego zadania. Poza tym - jest ich wiêcej. ZnajdŸ sobie w³asnego. [Wskazuje kierunek wskazany przez ciebie, gdy zapyta³ ciê o Œwiêty Granat Rêczny z Antiochii.]}
{136}{}{[KONIEC]}
{200}{}{Czy mówisz z dworsk¹ manier¹?}
{201}{}{Haaalo.}
{202}{}{Hej, jestem tutaj.}
{203}{}{Zechcesz mi poœwiêciæ minutkê?}
{204}{}{Ahem.}
{205}{}{No, daj spokój. Przestañ mnie ignorowaæ.}
{206}{}{B³agam! Mam bardzo wa¿ne pytanie.}
{207}{}{Có¿, pora wyruszyæ na poszukiwanie Œwiêtego Granatu Rêcznego z Antiochii. ChodŸ, Patsy.}
{300}{}{Nasza misja zosta³a wype³niona!}
{301}{}{Artur, do us³ug.}
