{100}{}{Widzisz... model czarnoskórego bohatera gry komputerowej.}
{101}{}{Widzisz muskularnego Murzyna w kombinezonie Krypty 13. Przygl¹da ci siê ze z³oœci¹.}
{102}{}{Widzisz czarnoskórego bohatera gry. Przygl¹da ci siê ze z³oœci¹.}
{103}{}{Widzisz czarnoskórego bohatera gry. Przygl¹da ci siê ze z³oœci¹.}
{104}{}{Pierwotnie to ja mia³em wyst¹piæ w grze "Fallout 1".}
{105}{}{Rzecz jasna, nie mia³em nic do gadania.}
{106}{}{Po prostu powiedzieli, ¿e maj¹ "za du¿o animacji". "Za du¿o klatek" - to powiedzieli.}
{107}{}{Ale ja jestem czarny! £apiesz ju¿, o co biega?}
{108}{}{Za ka¿dym razem, kiedy ju¿ myœlisz, ¿e do czegoœ doszed³eœ, jakiœ bia³as zmienia regu³y gry.}
{109}{}{Jak ja bym chcia³ dorwaæ tego...}
