{100}{}{Widzisz szczup³ego, spalonego s³oñcem mê¿czyznê.}
{200}{}{Widzisz szczup³¹, spalon¹ s³oñcem kobietê.}
# male
{101}{}{Widzisz farmera.}
# female
{201}{}{Widzisz ¿onê farmera.}
{102}{}{Widzisz spalonego s³oñcem farmera.}
{202}{}{Widzisz spalon¹ s³oñcem ¿onê farmera.}
{103}{}{Przybywasz w sam¹ porê. Gdyby ciê tu nie by³o... Có¿, ca³e szczêœcie, ¿e jednak tu jesteœ. Nie mamy wiele, ale chcê ci to daæ, jako nagrodê za twoj¹ pomoc. (Podaje ci coœ.)}
{104}{}{Dziêkujê.}
{105}{}{Ug}
{106}{}{Jeszcze raz - dziêki za pomoc.}
{107}{}{}
{108}{}{}
{109}{}{Trzymaj rêce tak, ¿ebym je widzia³. Prze¿ywamy tu ostatnio najazd bandytów ró¿nej maœci. Sk¹d mogê wiedzieæ, ¿e nie jesteœ jednym z nich. Czego chcesz?}
{110}{}{Chcê tylko kupiæ od was trochê zapasów.}
{111}{}{Niczego od was nie chcê. Lepiej bêdzie, jeœli ruszê ju¿ w drogê.}
{112}{}{Ug.}
{113}{}{Có¿, nie widzê w tym nic z³ego. Oto co mam na wymianê.}
{114}{}{[Handluj]}
{115}{}{Dobra, a teraz uciekaj!}
{116}{}{[Handluj]}
{117}{}{Kaza³em ci uciekaæ!}
{118}{}{}
{119}{}{(Trochê siê odprê¿a) Jak na bandytê, to masz za ma³o oleju w g³owie. Szukasz zapasów?}
{120}{}{Uhum.}
{121}{}{E-e.}
{122}{}{No to nie mamy o czym mówiæ. Lepiej idŸ ju¿ sobie.}
{123}{}{[KONIEC]}
{124}{}{Wynoœ siê z mojej farmy!}
{125}{}{Nie pozwolê siê wypêdziæ z w³asnego domu.}
{126}{}{Przeklêci bandyci.}
{127}{}{Wynoœ siê z mojej ziemi.}
{128}{}{Nikomu ju¿ nie mo¿na ufaæ.}
{129}{}{Cholerni bandyci.}
{130}{}{Zbyt ciê¿ko na to pracowa³em, ¿eby teraz siê poddaæ.}
{131}{}{Mo¿e zacznê wszystko od nowa.}
{132}{}{Jestem tylko biednym farmerem.}
{133}{}{B³agam, oszczêdŸ moj¹ farmê.}
{134}{}{I tak nie lubiê ¿ycia na farmie.}
{135}{}{Jeszcze tu wrócê.}
{136}{}{B³agam - weŸ moj¹ ¿onê...}
