{100}{}{Widzisz podró¿nika. Jego twarz znacz¹ liczne blizny.}
{101}{}{Widzisz ochroniarza kupca.}
{200}{}{¯adnej broni w pobli¿u szefa.}
{201}{}{Nikt uzbrojony nie mo¿e podejœæ do szefa.}
{202}{}{Od³ó¿ tê broñ zanim ciê rozwalê.}
{203}{}{Od³ó¿ broñ albo zje¿d¿aj st¹d.}
{250}{}{Nie bêdê siê powtarzaæ. Ju¿ nie ¿yjesz.}
{300}{}{Lepiej pogadaj z szefem.}
{301}{}{Traktujê swoj¹ robotê bardzo powa¿nie. Podskocz szefowi i ju¿ nie ¿yjesz.}
{302}{}{Szef to w gruncie rzeczy w porz¹dku.}
{303}{}{Nawet nie myœl o kradzie¿y czegokolwiek.}
