{100}{}{Widzisz pustelnika.}
{101}{}{Widzisz pustelnika.}
{102}{}{Chyba nie mył się od wielu lat.}
{103}{}{Czy wiesz ty dlaczego ja pustelnik? [Pewnie nie odzywał się do nikogo od wielu lat.]}
{104}{}{Dlaczego?}
{105}{}{Niczego.}
{106}{}{Ug.}
{107}{}{Ja chcieć być sam.}
{108}{}{Skoro już tu jestem, to może pohandlujemy, co? Na pewno chciałbyś coś z moich rzeczy.}
{109}{}{No to zostawię cię w spokoju.}
{110}{}{Handel. Potem pójść ty będziesz.}
{111}{}{Świetnie, oto co mam do zaoferowania.}
{112}{}{Lepiej już pójdę.}
{113}{}{Idź już.}
{114}{}{Chyba już pójdę.}
{115}{}{Hmm... Lubię cię. Nie dużo mowa. Zostań, handel ty i ja.}
{116}{}{K'}
{117}{}{Ja iść.}
{118}{}{Miło mówi. Idź już. Zmęczony jestem ja.}
{119}{}{[KONIEC]}
{120}{}{Mówić robi boligłowa. Idź.}
{121}{}{Koniec ja mówić z tobą.}
{122}{}{Ni mówić. Iść.}
{123}{}{Odejdź!}
{124}{}{Idź dom!}
{125}{}{Jak mnie atakować śmiesz!}
{126}{}{Mnie w spokoju zostaw.}
{127}{}{Moja iść.}
