{100}{}{Widzisz mê¿czyznê w stalowej zbroi.}
{101}{}{Widzisz Kagê.}
{102}{}{Ta, to Kaga Nie-Taki-Wielki. Ma stalow¹ zbrojê i oczywiœcie chce ciê zabiæ.}
{103}{}{Znowu ty!}
{104}{}{Te ci¹g³e spotkania ju¿ mnie nudz¹.}
{105}{}{Dziecko Przeznaczenia - Phi!}
{106}{}{Skoñczmy z tym.}
{107}{}{Po¿a³ujesz, ¿e kiedykolwiek o mnie us³ysza³eœ, Kaga!}
{108}{}{Moje umiejêtnoœci wzros³y od naszego ostatniego spotkania.}
{109}{}{To ju¿ chyba jakaœ ponura tradycja.}
{110}{}{Kaga musi jeszcze trochê potrenowaæ.}
{111}{}{Kaga jeszcze wróci.}

{120}{}{Znowu siê spotykamy, Kaga.}

#added 1.3
{150}{}{[Staje przed tob¹ wysoki, potê¿nie zbudowany wojownik. Patrzy na ciebie, a w jego oczach p³onie nienawiœæ.] Wiêc to tak, wyrzucaj¹ Kagê, a potem okrzykuj¹ CIEBIE Dzieckiem Przeznaczenia? Tak?! Myœlisz, ¿e to ¿e twój dziadek by³ Przybyszem z Krypty cokolwiek tutaj znaczy?! Myœlisz, ¿e Kaga Wielki jest od ciebie gorszy?!}
{151}{}{Có¿, to JA JESTEM, Dzieckiem Przeznaczenia, prawda?}
{152}{}{Hej stój, czekaj chwileczkê. Kto mówi, ¿e jesteœ ode mnie gorszy.}

{160}{}{Ten tytu³ bêdzie gówno wart kiedy Kaga wyrwie ci g³owê z ramion!}
{161}{}{¯adne s³owa nie uratuj¹ twojego ty³ka. Wraz z twoj¹ œmierci¹, Kaga odzyska honor. Kaga teraz siê zemœci!}

#dumb dialogue
{200}{}{Brzyyydal?}
{201}{}{Co!? Wybrali *ciebie* na dziecko przeznaczenia? Cholera, musz¹ byæ naprawdê zdesperowani.}
{202}{}{Ja nie lubieæ. Ty byæ z³y.}
{203}{}{Kaga nawet nie bêdzie z tob¹ gadaæ. Przygotuj siê na œmieræ z r¹k Kagi!}
