{100}{}{Widzisz gangstera.}
{101}{}{No proszę - co my tu mamy?}
{102}{}{Zwykli podróżnicy, tak? Takich ludzi nie ma! Może pomóc wam dźwigać wasz dobytek, co? }
{103}{}{Tylko uważaj co robisz w Reno, albo stanie ci się krzywda. I nigdy, przenigdy NIE WŁAŹ MI W DROGĘ.}
{104}{}{Witaj, }
{105}{}{.}
{106}{}{Co ty tu robisz, }
{107}{}{?}
{108}{}{Właśnie ciebie szukamy, }
{109}{}{. Wszystko w porządku, }
{110}{}{?}
{111}{}{Potrzebujesz trochę odpoczynku, }
{112}{}{? }
{113}{}{ zastanawiał się co u ciebie słychać, }
{114}{}{.}
