{100}{}{Widzisz groźnie wyglądającą osobę.}
{101}{}{Widzisz najeźdźcę.}
{200}{}{Jesteś na naszym terytorium. Teraz zginiesz!}
{201}{}{Jak śmiesz zjawiać się tu bez zaproszenia!}
{202}{}{Giń, mieszczuchu!}
{203}{}{Pewnie nieźle zarobię na twojej śmierci.}
{204}{}{Uciekaj, póki jeszcze możesz!}
{205}{}{Wiecie co robić, panowie.}
{206}{}{Żadnych świadków.}
{207}{}{Osłaniajcie mnie.}
{208}{}{Bez litości!}
{209}{}{Nikt nie może przeżyć.}
{210}{}{Bishop kazał wytłuc włóczęgów.}
{211}{}{Za to nam płacą!}
{300}{}{Widzisz Żabę Mortona.}
{301}{}{Widzisz Ropuchę Mortona.}
{302}{}{Widzisz Traszkę Mortona.}
{303}{}{Widzisz Węża Mortona.}
{305}{}{Przez ciebie zginął mój brat! Już nie żyjesz!}
