{100}{}{Widzisz brudnego, nieogolonego mężczyznę.}
{101}{}{Traper.}
{102}{}{Lepiej się do niego nie zbliżać. Insekty buszujące w jego ubraniu mogą zechcieć przenieść się do czystszego mieszkania.}
{103}{}{Witaj. Nieczęsto spotykam ludzi na tym pustkowiu. Czego chcesz?}
{104}{}{Masz jakieś skórki na sprzedaż?}
{105}{}{Niczego.}
{106}{}{Ug.}
{107}{}{Cóż, chyba mogę odsprzedać ci kilka skórek. I tak nie mam ochoty wybierać się chwilowo do miasta.}
{108}{}{Co tam masz?}
{109}{}{Nieważne.}
{110}{}{Ug.}
{111}{}{Oto co mam: }
{112}{}{x skóra zwykłego gekona.}
{113}{}{x skóra złocistego gekona.}
{114}{}{Wezmę wszystko.}
{115}{}{Może innym razem. Pa.}
{116}{}{Miło robić z tobą interesów. Trzymaj się.}
{117}{}{Bywaj.}
{118}{}{Chyba brakuje ci pieniędzy. Może w zamian pozwolisz mi spędzić pięć minut z twoją kobitą. Opłaci ci się.}
{119}{}{Chyba brakuje ci pieniędzy. Może w zamian pozwolisz mi spędzić pięć minut z twoim chłopem. Dam ci w zamian skórki.}
{120}{}{Chyba brakuje ci pieniędzy. Wiesz co, wyglądasz całkiem apetycznie, he, he. To jak? Opłaci ci się!}
{121}{}{Jasne.}
{122}{}{Nie ma szans. Bywaj.}
{123}{}{[Miria na pewno kiedyś ci wybaczy. Z weselszych informacji: zyskujesz kilka pięknych skórek.]}
{124}{}{[Davin chyba nie miał nic przeciwko.]}
{125}{}{[Potrzebujesz kąpieli, dłuuuugiej kąpieli z dużą ilością mydła - ale zyskujesz kilka pięknych skórek.]}
{126}{}{Bywaj.}
{127}{}{[Podnosi prawą dłoń i mówi] Howgh. Ja świetna traper. Poluje duże gekon. Moja nie chcieć wejść na twoje ziemie. Odejść w pokoju. [Daje ci w prezencie skórkę gekona.]}
{128}{}{[KONIEC]}
{129}{}{Nie mamy już o czym rozmawiać.}
{130}{}{Tchórz!}
{131}{}{To moje tereny łowieckie. Odejdź!}
{132}{}{Obedrę cię ze skóry!}
{133}{}{Zrobię sobie naszyjnik z twoich zębów.}
{134}{}{Jedna zwykła skórka gekona: $}
{135}{}{Jedna skórka gekona złocistego: $}
{136}{}{Dobra. Twoje górą.}
{137}{}{Masz szczęście, muszę się zająć moimi sidłami.}
{138}{}{Chyba mama mnie woła.}
{140}{}{Wygląda na to, że nie mam żadnych skór zwykłych gekonów, ale mam }
{141}{}{Wygląda na to, że nie mam żadnych skór złotych gekonów, ale mam }
{142}{}{Wybacz, wygląda na to, że nie mam już niczego na stanie.}
{200}{}{Widzisz brudną, zaniedbaną kobietę.}
