{100}{}{Widzisz Dexa.}
{101}{}{Widzisz przystojnego, zadbanego mê¿czyznê. Poni¿ej robi¹cych wra¿enie u³o¿onych na ¿elu w³osów, widzisz jego oczy b³yszcz¹ce urokiem... a mo¿e szaleñstwem.}
{200}{}{[Kiedy podchodzisz do komory kriogenicznej, zauwa¿asz narcystycznie wygl¹daj¹cego faceta skulonego na pod³odze. Podci¹ga kolana i przyciska je do klatki. Siedzi tam przez kilka chwil, patrz¹c pusto przed siebie dr¿¹c z zimna i szczekaj¹c zêbami. Wygl¹da, ¿e stopniowo siê uspokaja.]}
{201}{}{O, witam?}
{210}{}{[Odwraca g³owê w twoim kierunku i podnosi siê na nogi. Obserwuje ciê dok³adnie, potem rzuca spojrzenie na otoczenie niczym przera¿one zwierze. Kiedy jego spojrzenie wraca na ciebie, uspokaja siê, jego wspomnienia powoli do niego wracaj¹. Szybko zmienia siê jego postawa, jest teraz spokojny i pewny siebie, mimo swojej nagoœci.] Nie poznaje ciê, koleœ. Nie masz nic przeciwko ¿ebym siê ubra³?}
{211}{}{Myœlê, ¿e nie zaszkodzi...}
{212}{}{Nie s¹dzê ¿eby to by³...}
{220}{}{Oczywiœcie, ¿e nie masz nic przeciwko. Dziêki, koleœ. [Przechodzi obok ciebie i otwiera szafkê. Swobodnie ubiera siê w dobrze skrojony garnitur, potem chowa do kieszeni resztê zawartoœci szafki. Wyci¹ga grzebieñ kieszonkowy i zaczyna czesaæ i uk³adaæ swoje w³osy z precyzj¹ profesjonalisty.] Wiêc, gdzie jest doktorek?}
{221}{}{Doktorek? A, pewnie gdzieœ tu jest. W³aœciwie to myœlê, ¿e ju¿ tu idzie, wiêc ja ju¿ sobie pójdê, ¿eby wam nie przeszkadzaæ jak bêdziecie nadrabiali zaleg³oœci. Czeœæ!}
{222}{}{Có¿, to mo¿e byæ dla ciebie wstrz¹saj¹ce, ale by³eœ zamro¿ony bardzo d³ugo. Kimkolwiek by³ "doktorek", na pewno ju¿ nie ¿yje. Jeœli by³ twoim przyjacielem, to przykro mi.}
{223}{}{Nie chcê ciê dobijaæ, ale by³eœ zamro¿ony *naprawdê* d³ugo. Jestem pewien, ¿e twój przyjaciel, "doktorek", ju¿ od dawna nie ¿yje.}
{224}{}{S³uchaj, ch³opczyku. Nie uwolni³em twojego psychotycznego ty³ka ¿eby móc odpowiadaæ na twoje g³upie pytania i patrzeæ jak siê pogr¹¿asz. Pozwalam ci ¿yæ tylko tak d³ugo ¿ebyœ móg³ przekazaæ mi wszelkie przydatne informacje jakie mo¿esz mieæ. Wiêc zacznij mówiæ. Im wiêcej mi mo¿esz powiedzieæ, tym d³u¿ej po¿yjesz.}
{230}{}{[Jego opanowanie znika, a oczy rozpala furia.] Wydaje ci siê, ¿e mo¿esz straszyæ MNIE? Czy ty masz w ogóle pojêcie z kim rozmawiasz? Tylko tu podejdŸ a poka¿ê ci do czego jestem zdolny!}
{231}{}{[Gotowe.]}
{240}{}{[Dex szczerzy siê do ciebie, ods³aniaj¹c zestaw idealnych zêbów produktu przedwojennej stomatologii dla ciebie wygl¹daj¹ dziwnie w ca³ej swojej per³owej symetrii.]  Doktorek, moim przyjacielem? [Uniós³ brew.] Ty naprawdê nie wiesz kim jestem, co?}
{241}{}{Uch, nie zupe³nie. Odbywa³em pewien rodzaj wêdrówki po tym dziwnym obiekcie, pomajstrowa³em trochê przy tej rzeczy i tak siê sta³o, ¿e trafi³em na ciebie. W ka¿dym razie dlaczego by³eœ zamro¿ony?}
{242}{}{Có¿, wed³ug komputera, jesteœ Dex, narcystycznym, socjopatycznym, seryjnym morderc¹ z przed wielkiej ciszy. Odmrozi³em ciê tylko po to ¿eby ciê ubiæ jak chorego psa , którym jesteœ.}
{243}{}{Uch, nie zupe³nie. Na pewno jesteœ ca³kowicie normalnym goœciem, który zosta³ zamro¿ony z ca³kowicie naturalnych i s³usznych powodów. Do cholery, w koñcu co ja tam wiem? Ja siê tylko w³óczê po tym dziwnym miejscu, bawiê siê sprzêtami i przy okazji ciê rozmrozi³em.}
{250}{}{[Dex jeszcze raz rozejrza³ siê po pokoju i zagwizda³.] To miejsce naprawdê zesz³o na psy. Mówisz, ¿e jak d³ugo mnie nie by³o?}
{251}{}{Minê³o ponad sto piêædziesi¹t lat odk¹d Wielka Cisza przynios³a zag³adê Staro¿ytnym... *twojemu* ludowi.}
{260}{}{Wielka Cisza? Staro¿ytni? Mo¿e oszczêdzisz mi gównianych przenoœni i po prostu powiesz co siê sta³o?}
{261}{}{Wielk¹ Cisz¹ mój lud nazywa koniec twojego œwiata. Kiedy wielki ogieñ spa³ z nieba i spali³ ziemiê. Wkrótce przekonasz siê, ¿e œwiat w niczym nie przypomina ju¿ tego który zna³eœ.}
{270}{}{Bez jaj, wiêc naprawdê zrzucili bomby, co? Czyli projekt Krypt nie by³ jednak marnotrawstwem pieniêdzy podatników.}
{271}{}{Czekaj, wiesz o Œwiêtych Kryptach?}
{280}{}{Czy o nich wiem? Cholera, mieszka³em ko³o krypty w Chicago. Widzia³em nawet jak koñcz¹ budowê. A potem oczywiœcie zaczêli robiæ te przeklête próbne alarmy... [Przerywa i patrzy na ciebie z rozbawieniem.] Ty to naprawdê ³ykn¹³eœ, co?}
{281}{}{MÓW DALEJ O KRYPTACH!}
{282}{}{Có¿, widzisz, zosta³em wybrany przez mój lud abym odnalaz³ Kryptê. Tam, mam nadziejê uda mi siê znaleŸæ G.E.C.K. i u¿yæ jego mocy, aby ocaliæ moj¹ wioskê. Cokolwiek co mo¿esz mi powiedzieæ o Kryptach mo¿e pomóc mi w moim zadaniu.}
{283}{}{Có¿, widzisz, zosta³em wybrany przez mój lud abym odnalaz³ Kryptê. Wielokrotnie ryzykowa³em ¿ycie ¿eby odnaleŸæ Œwiêt¹ Kryptê i w koñcu mi siê to uda³o. Jestem ciekaw co ty mo¿esz o nich wiedzieæ.}
{290}{}{Wiesz co ci powiem, koleœ. Potrzebujesz pomocy przy szukaniu Kryty, a ja potrzebuje kogoœ kto poka¿e mi co i jak w tym szalonym œwiecie. Co ty na to... wspólniku?}
{291}{}{Hmm, twoja wiedza o staro¿ytnych mo¿e mi siê przydaæ... Ale, có¿, szczerze to czyta³em o tobie w tamtym komputerze i nie jestem pewien czy chcê podró¿owaæ z kimœ takim.}
{292}{}{Nie mam czasu ¿eby ci "pokazaæ co i jak". Jestem pewien, ¿e sam sobie œwietnie poradzisz, "koleœ".}
{293}{}{A ja na to, umowa stoi... wspólniku.}
{294}{}{Nie za bardzo pasuje mi przemierzaæ pustkowia w towarzystwie maniakalnego mordercy. Wiêc radŸ sobie sam - koleœ. I nie martw siê, jestem pewien, ¿e ktoœ taki jak ty sobie poradzi. [Szyderczy œmiech.]}
{300}{}{Co, czekaj. Niech zgadnê, czyta³eœ, ¿e jestem jakimœ stukniêtym morderc¹, tak? Có¿ koleœ, mam dal ciebie dwa s³owa: Gówno. Prawda. Nie wierz w ani jedno s³owo.}
{301}{}{Ale to nie ma sensu, po co mieliby k³amaæ?}
{302}{}{Jasne gówno prawda, ale to co ty mówisz i myœlê, ¿e najwy¿szy czas ¿ebym ciê uciszy³, na dobre.}
{310}{}{Hej, wiem, ¿e nie brzmi to zbyt sensownie, ale czy rozejrza³eœ siê po tym miejscu? Niewielu tu sensownych rzeczy. Nikt nie wie co siê roi³o w popieprzonych mózgach tych naukowców. }
{311}{}{Hmm... tu masz racje. Nie mówiê, ¿e ci wierze... ale s¹dzê, ¿e przynajmniej mogê ciê wys³uchaæ.}
{312}{}{Ta, tu siê zgodzê. Mów dalej...}
{320}{}{W porz¹dku, widzisz, to wszystko to czêœæ ich "eksperymentu". Ci szaleni popieprzeni naukowcy robili badania "natury ludzkiego z³a" czy coœ takiego. Wszczepiali mi wspomnienia maniakalnego mordercy ¿eby zobaczyæ jaki bêd¹ mia³y wp³yw na normalnego cz³owieka. A przynajmniej tyle uda³o mi siê ustaliæ.}
{321}{}{Có¿... je¿eli to prawda, to okropne co z tob¹ robili. Ale dlaczego wybrali w³aœnie ciebie do tego eksperymentu?}
{322}{}{Cz³owieku to chore co z tob¹ zrobili. W ka¿dym razie, masz ju¿ to za sob¹, to ju¿ przesz³oœæ. Ci szaleni naukowcy ju¿ dawno nie ¿yj¹ i nie bêd¹ mogli kontynuowaæ swoich eksperymentów. ChodŸ ze mn¹ wynosimy siê st¹d.}
{330}{}{Eh, widzisz i tu robi siê zabawnie. *Ja* sam do *nich* przyszed³em. Odpowiedzia³em na ich og³oszenie, obiecali wysokie wynagrodzenie dla zdrowych ochotników. Potrzebowa³em kasy i có¿, okaza³o siê to moim najwiêkszym ¿yciowym b³êdem. Nie mogê ci nawet opowiedzieæ jaki horror mi wszczepili. [Jego oczy siê zeszkli³y od ³ez na samo wspomnienie. Wzi¹³ g³êboki oddech i otar³ ³zy z oczu.] W ka¿dym razie dziêki, kolego, uwolni³eœ mnie od tego koszmaru.}
{331}{}{Co. Có¿, Cieszê siê, ¿e mog³em pomóc... Tak myœlê.}
{332}{}{W³aœciwie, dupku, twój koszmar w³aœnie siê zacz¹³, bo nie wie¿e w ani jedno twoje s³owo.}
{340}{}{Wiêc jak bêdzie, koleœ? Spó³a? Nie tylko poczujesz siê bardziej odjazdowy bêd¹c w moim towarzystwie, ale te¿ radzê sobie w walce. Cholera, poradzê sobie nawet solo, ale nie mam pojêcia co siê tam na mnie teraz czai. Wszystko co wiem to, ¿e pierwsze drzewo pod jakim bêdê siê chcia³ odszczaæ mo¿e siê otworzyæ i odgryŸæ mi fujarê.}
{341}{}{Dobra, mo¿esz ze mn¹ podró¿owaæ, ale bêdê ciê mia³ na oku. Tylko pomyœlisz o przekroczeniu granicy to ciê zdejmê.}
{342}{}{Pewnie, myœlê, ¿e mo¿emy. Witaj w dru¿ynie, Dex.}
{343}{}{To by³a zabawna historyjka i ca³kiem niez³y z ciebie aktor, co czyni ciê jeszcze bardziej niebezpiecznym. Myœlê, ¿e zrobiê przys³ugê pustkowiu i ciê usunê zanim zrobisz wiêcej szkód.}
{350}{}{[Uœmiech Dexa blednie, a oczy staj¹ siê zamglone. Po chwili, zaczyna mówiæ unikaj¹c twojego spojrzenia.]
 By³em jednym z ich chorych eksperymentów. Oni zrobili mi... coœ strasznego. [Potrz¹sa g³ow¹, a potem patrzy na ciebie z poprzednim uœmieszkiem.]
 Wola³bym o tym nie mówiæ, chyba rozumiesz? A tak przy okazji, nazywam siê Dex.}
{351}{}{Przykro mi to s³yszeæ, Dex. Ale, teraz to ju¿ przesz³oœæ. Naprawdê, *naprawdê* odleg³a przesz³oœæ.}
{352}{}{S³uchaj, Dex, mo¿liwe, ¿e móg³bym ci pomóc, ale muszê wiedzieæ z kim mam do czynienia. Co dok³adnie ci zrobili?}
{360}{}{[Dex jeszcze raz rozejrza³ siê po pomieszczeni i zagwizda³.] Bez ¿artów. To miejsce naprawdê zesz³o na psy. Mówisz, ¿e ile czasu minê³o?}
{370}{}{W porz¹dku, ale naprawdê musisz to wiedzieæ? Dobra. W³aœciwie to ci popieprzeni, szaleni naukowcy prowadzili badania nad "natur¹ ludzkiego z³a", albo tego typu gównem.
 Wszczepili mi wspomnienia jakiegoœ maniaka bo chcieli sprawdziæ jaki to bêdzie mia³o wp³yw na osobowoœæ przyzwoitego, praworz¹dnego goœcia, takiego jak ja. A w ka¿dym razie, tyle uda³o mi siê ustaliæ.}
{371}{}{No dobra rozumiem. Wiêc *jaki* to mia³o wp³yw na ciebie? }
{372}{}{Nie wiem, mam jakieœ koszmary, dobra? S³uchaj, by³em zamro¿ony kto wie jak d³ugo i nie mam ochoty na jakieœ pieprzone przes³uchanie.
 Doktorek te¿ by³ taki wredny... Dobrze s³ysza³em, nie ¿yje? W³aœciwie to jak d³ugo mnie nie by³o? To miejsce wygl¹da jak gówno.}
{400}{}{[Kiedy podchodzisz do komory kriogenicznej, zauwa¿asz przystojnego mê¿czyznê skulonego na pod³odze. Podci¹ga kolana i przyciska je do klatki. Siedzi tam przez kilka chwil, patrz¹c pusto przed siebie dr¿¹c z zimna i szczekaj¹c zêbami. Wygl¹da, ¿e stopniowo siê uspokaja.]}
{401}{}{O, witam?}
{410}{}{[Odwraca g³owê w twoim kierunku i podnosi siê na nogi. Obserwuje ciê dok³adnie, potem rzuca spojrzenie na otoczenie niczym przera¿one zwierze. Kiedy jego spojrzenie wraca na ciebie, uspokaja siê, jego wspomnienia powoli do niego wracaj¹. Szybko zmienia siê jego postawa, jest teraz spokojny i pewny siebie, mimo swojej nagoœci.] Czeœæ lala, wiem ¿e niez³y ze mnie widok, ale jest tu Ÿdziebko zimno. Nie masz nic przeciwko ¿ebym siê ubra³?}
{411}{}{Myœlê, ¿e nie zaszkodzi...}
{412}{}{Nie s¹dzê ¿eby to by³...}
{420}{}{Oczywiœcie, ¿e nie masz nic przeciwko. Dziêki, ma³a. [Przechodzi obok ciebie delikatnie klepi¹c ciê w pupê i otwiera szafkê. Swobodnie ubiera siê w dobrze skrojony garnitur, potem chowa do kieszeni resztê zawartoœci szafki. Wyci¹ga grzebieñ kieszonkowy i zaczyna czesaæ i uk³adaæ swoje w³osy z precyzj¹ profesjonalisty.] Chyba ciê tu wczeœniej nie widzia³em, lala, a nie s¹dzê ¿ebym zapomnia³ taka buŸkê. Nazywam siê Dex, ale to ju¿ pewnie wiesz. Mogê poznaæ twoje imiê?}
{421}{}{Jestem }
{422}{}{. Ale zanim siê jeszcze bardziej spoufalisz, powinieneœ wiedzieæ, ¿e mam tak¹ zasadê, ¿e nie spotykam siê z mê¿czyznami o reputacji mordercy, którzy byli zamro¿eni przez ponad sto piêædziesi¹t lat. A jak dotkniesz mojego ty³ka jeszcze raz to wyrwê ci fiuta, zrozumia³eœ?}
{423}{}{Jestem }
{424}{}{, mi³o ciê poznaæ, Dex. Nawet nie mogê sobie wyobraziæ jak siê czujesz budz¹c siê po ponad stu piêædziesiêciu latach kriogenicznego snu.}
{425}{}{Ta, oczywiœcie, ¿e... nie, ty popieprzony zboku. Odmrozi³am ciê tylko po to ¿eby ciê uœpiæ jak chorego psa, którym jesteœ.}
{426}{}{Zapomnij o imionach. Co powiesz na zdjêcie z powrotem tych ubrañ i pokazanie mi z czego s¹ zrobieni przed wojenni mê¿czyŸni.}
{430}{}{[Uœmiechn¹³ siê do ciebie i zacz¹³ rozbieraæ.] Dziewczyno, jesteœ w moim typie. Przygotuj siê na doœwiadczenie Dexa, Ksiêcia sexu.}
{431}{}{[Dalej.]}
{440}{}{[Po kilku godzinach intensywnego uprawiania mi³oœci na pod³odze laboratorium, oboje padacie zmêczeni. [Dex trzyma niewielki przedmiot przy twoich ustach.] A teraz krzycz, ma³a. [W chwili kiedy orientujesz siê, ¿e jest to ludzkie ucho, czujesz ostrze przeszywaj¹ce twoj¹ pierœ. Krzyczysz kiedy ostrze cofa siê tylko po to aby zostaæ z powrotem wbite...]}
{441}{}{[Koniec.]}
{450}{}{Jak, ¿e niby co? Wróæ trochê, cukiereczku. Powiedzia³aœ w³aœnie sto piêædziesi¹t lat? [Potrz¹sa g³ow¹ z niedowierzaniem.]
 Nie-kurde-wiarygodne. [Sprawdza swoje odbicie w lustrze.] Ale musisz przyznaæ, wygl¹dam zabójczo jak na mój wiek.
 [Dex szczerzy siê do ciebie, ods³aniaj¹c zestaw idealnych zêbów produktu przedwojennej stomatologii dla ciebie wygl¹daj¹ dziwnie w ca³ej swojej per³owej symetrii.]}
{451}{}{Pewnie niektóre dziewczyny mog¹ uwa¿aæ ciê za atrakcyjnego, ale wygl¹da , ¿e jesteœ zimnokrwistym, psychopatycznym morderc¹, co, jak wiesz, tak jakby przyæmiewa ca³y twój urok.}
{452}{}{Tak, jesteœ bardzo atrakcyjny, ale szczerze to jestem trochê nerwowa rozmawiaj¹c z tob¹ po tym co przeczyta³am w twoich aktach.}
{453}{}{Dobra, to przyprawia mnie o md³oœci. Zobaczmy czy bêdzie z ciebie taki przystojniak jak w³aduje ci kilka kul w twarz.}
{454}{}{NieŸle jak na cz³owieka lodu. A w³aœciwie, czemu by³eœ tam zamro¿ony?}
{455}{}{Eh, nie jesteœ w moim typie. A w³aœciwie, czemu by³eœ tam zamro¿ony?}
{456}{}{Dobra, to przyprawia mnie o md³oœci. Zobaczmy czy bêdzie z ciebie taki przystojniak jak w³aduje ci kilka kul w twarz.}
{460}{}{Okej, sk¹d wziê³aœ te bzdury o "psychopatycznym mordercy"?}
{461}{}{Nie próbuj na mnie swoich sztuczek. Czyta³am o tobie w tamtym komputerze.}
{462}{}{Ten komputer ma coœ w rodzaju twojej biografii, a jest ona doœæ przera¿aj¹ca.}
{463}{}{Mogê to wyczuæ. Pewien rodzaj wibracji od ciebie.}
{464}{}{Nawet nie próbuj tych swoich sztuczek na mnie. Znam ludzi takich jak ty.}
{470}{}{Ach tak, teraz to ma sens. S³uchaj, nie przejmuj siê tym, to nie to co myœlisz. Zaraz ci wszystko wyjaœniê. Ale najpierw, czy mog³abyœ mi powiedzieæ co siê wydarzy³o odk¹d mnie zamro¿ono? Mam na myœli, ¿e to miejsce zesz³o na psy, a ty wygl¹dasz dla mnie jak byœ wysz³a z jakiegoœ opowiadania SF.}
{471}{}{Minê³o ponad sto piêædziesi¹t lat odk¹d Wielka Cisza przynios³a zag³adê Staro¿ytnym... *twojemu* ludowi.}
{475}{}{Wielka Cisza? Staro¿ytni? Mo¿e oszczêdzisz mi gównianych przenoœni i po prostu powiesz co siê sta³o?}
{476}{}{Wielk¹ Cisz¹ mój lud nazywa koniec twojego œwiata. Kiedy wielki ogieñ spa³ z nieba i spali³ ziemiê. Wkrótce przekonasz siê, ¿e œwiat w niczym nie przypomina ju¿ tego który zna³eœ. }
{480}{}{Bez jaj, wiêc naprawdê zrzucili bomby, co? Czyli projekt Krypt nie by³ jednak marnotrawstwem pieniêdzy podatników.}
{481}{}{Czekaj, wiesz o Œwiêtych Kryptach?}
{490}{}{Czy o nich wiem? Cholera, mieszka³em ko³o krypty w Chicago. Widzia³em nawet jak koñcz¹ budowê. A potem oczywiœcie zaczêli robiæ te przeklête próbne alarmy... [Przerywa i patrzy na ciebie z rozbawieniem.] Ma³a, ty to naprawdê ³yknê³aœ, co?}
{491}{}{MÓW DALEJ O KRYPTACH!}
{492}{}{Có¿, widzisz, zosta³em wybrany przez mój lud abym odnalaz³ Kryptê. Tam, mam nadziejê uda mi siê znaleŸæ G.E.C.K. i u¿yæ jego mocy, aby ocaliæ moj¹ wioskê. Cokolwiek co mo¿esz mi powiedzieæ o Kryptach mo¿e pomóc mi w moim zadaniu.}
{493}{}{Có¿, widzisz, zosta³am wybrana przez mój lud abym odnalaz³a Kryptê. Wielokrotnie ryzykowa³am ¿ycie ¿eby odnaleŸæ Œwiêt¹ Kryptê i w koñcu mi siê to uda³o. Jestem ciekawa co ty o nich mo¿esz wiedzieæ.}
{500}{}{Wiesz co ci powiem, ma³a. Potrzebujesz pomocy przy szukaniu Kryty, a ja potrzebuje kogoœ kto poka¿e mi co i jak w tym szalonym œwiecie. Co ty na to... wspólniczko?}
{501}{}{A ja na to, umowa stoi... wspólniku.}
{502}{}{Hmm, twoja wiedza o staro¿ytnych mo¿e mi siê przydaæ... Ale, có¿, szczerze to czyta³am o tobie w tamtym komputerze i nie jestem pewna czy chcê podró¿owaæ z kimœ takim...}
{503}{}{Nie za bardzo pasuje mi przemierzaæ pustkowia w towarzystwie maniakalnego mordercy. Wiêc radŸ sobie sam - ma³y. I nie martw siê, jestem pewna, ¿e ktoœ taki jak ty sobie poradzi. [Szyderczy œmiech.]}
{510}{}{Hej, jak ju¿ mówi³em, mogê to wyjaœniæ. Wszystko co o mnie czyta³aœ jes gówno warte. Nie wierz w ani jedno s³owo.}
{511}{}{Hej, jak ju¿ mówi³em, mogê to wyjaœniæ. Te z³e wibracje jakie odemnie czujesz to efekt eksperymentów jakie tu na mnie prowadzili.}
{512}{}{Ale to nie ma sensu, co niby ci takiego zrobili?}
{513}{}{Gówno prawda. Myœlê, ¿e najwy¿szy czas ciê uciszyæ, na dobre.}
{514}{}{Ale to nie ma sensu, po co mieliby k³amaæ?}
{515}{}{Gówno warte to s¹ TWOJE s³owa, nie wierze ci ani trochê, czas ciê uciszyæ na dobre.}
{520}{}{Hej, wiem, ¿e nie brzmi to zbyt sensownie, ale czy rozejrza³aœ siê po tym miejscu? Niewielu tu sensownych rzeczy. Nikt nie wie co siê roi³o w popieprzonych mózgach tych naukowców.}
{521}{}{Hmm... tu masz racje. Nie mówiê, ¿e ci wierze... ale s¹dzê, ¿e przynajmniej mogê ciê wys³uchaæ.}
{522}{}{Ta, tu siê zgodzê. Mów dalej...}
{530}{}{W porz¹dku, widzisz, to wszystko to czêœæ ich "eksperymentu". Ci szaleni popieprzeni naukowcy robili badania "natury ludzkiego z³a" czy coœ takiego. Wszczepiali mi wspomnienia maniakalnego mordercy ¿eby zobaczyæ jaki bêd¹ mia³y wp³yw na normalnego cz³owieka. A przynajmniej tyle uda³o mi siê ustaliæ.}
{531}{}{Có¿... je¿eli to prawda, to okropne co z tob¹ robili. Ale dlaczego wybrali w³aœnie ciebie do tego eksperymentu?}
{532}{}{O³, biedne maleñstwo. W ka¿dym razie, masz ju¿ to za sob¹, to ju¿ przesz³oœæ. Ci szaleni naukowcy ju¿ dawno nie ¿yj¹ i nie bêd¹ mogli ciê wiêcej krzywdziæ. ChodŸ ze mn¹, wynosimy siê st¹d.}
{540}{}{Eh, widzisz i tu robi siê zabawnie. *Ja* sam do *nich* przyszed³em. Odpowiedzia³em na ich og³oszenie, obiecali wysokie wynagrodzenie dla zdrowych ochotników. Potrzebowa³em kasy i có¿, okaza³o siê to moim najwiêkszym ¿yciowym b³êdem. Nie mogê ci nawet opowiedzieæ jaki horror mi wszczepili. [Jego oczy siê zeszkli³y od ³ez na samo wspomnienie. Wzi¹³ g³êboki oddech i otar³ ³zy z oczu.] W ka¿dym razie dziêki tobie, }
{541}{}{, jestem wreszcie wolny od tego koszmaru.}
{542}{}{Co. Có¿, Cieszê siê, ¿e mog³em pomóc... Tak myœlê.}
{543}{}{W³aœciwie, dupku, twój koszmar w³aœnie siê zacz¹³, bo nie wie¿e w ani jedno twoje s³owo.}
{550}{}{Wiêc, jak bêdzie, ma³a? Spó³a? Nie tylko dobrze wygl¹dam, ale te¿ radzê sobie w walce. Cholera, poradzê sobie nawet solo, ale nie mam pojêcia co siê tam na mnie teraz czai. Wszystko co wiem to, ¿e pierwsze drzewo pod jakim bêdê siê chcia³ odszczaæ mo¿e siê otworzyæ i odgryŸæ mi fujarê.}
{551}{}{Dobra, mo¿esz ze mn¹ podró¿owaæ, ale bêdê ciê mia³a na oku. Tylko pomyœlisz o przekroczeniu granicy to ciê zdejmê. }
{552}{}{Pewnie, myœlê, ¿e mo¿emy. Witaj w dru¿ynie, Dex.}
{553}{}{To by³a zabawna historyjka i ca³kiem niez³y z ciebie aktor, co czyni ciê jeszcze bardziej niebezpiecznym. Myœlê, ¿e zrobiê przys³ugê pustkowiu i ciê usunê zanim zrobisz wiêcej szkód.}
{554}{}{A ja na to umowa stoi... wspólniku. }
{555}{}{Có¿, s¹dzê, ¿e twoja wiedza o staro¿ytnych mo¿e mi siê przydaæ... myœlê, ¿e umowa stoi.}
{556}{}{Naprawdê nie mam czasu ¿eby ci "pokazaæ co i jak". Jestem pewna, ¿e sam sobie œwietnie poradzisz, "ma³y".}
{560}{}{[Uœmiech Dexa blednie, a oczy staj¹ siê zamglone. Po chwili, zaczyna mówiæ, ale unika twojego spojrzenia.]
 By³em jednym z ich chorych eksperymentów. Oni zrobili mi... coœ strasznego. [Potrz¹sa g³ow¹, a potem patrzy na ciebie z poprzednim uœmieszkiem.]
 Ale o wiele bardzie wola³bym porozmawiaæ o tobie, ma³a.}
{561}{}{No dobra, pomyœlmy... urodzi³am siê i wychowa³am w wiosce, która nazywa siê Arroyo. Moja matka jest starsz¹ wioski i jesteœmy w prostej linii potomkami Przybysza z Kry—}
{562}{}{S³uchaj, Dex, mo¿liwe, ¿e móg³bym ci pomóc, ale muszê wiedzieæ z kim mam do czynienia. Co dok³adnie ci zrobili?}
{570}{}{£o³, to naprawdê interesuj¹ce, ma³a i nie mogê siê doczekaæ, kiedy us³yszê coœ wiêcej o tobie. Szczerze. Ale mo¿e najpierw, opowiesz mi co siê tu do cholery sta³o, odk¹d wsadzili mnie do lodu.
 Mam na myœli, no wiesz, to miejsce zesz³o na psy, a ty wygl¹dasz jakbyœ wysz³a z jakiejœ przygodowej opowieœci SF.}
{580}{}{W porz¹dku, ale naprawdê musisz to wiedzieæ? Dobra. W³aœciwie to ci popieprzeni, szaleni naukowcy prowadzili badania nad "natur¹ ludzkiego z³a", albo tego typu gównem.
 Wszczepili mi wspomnienia jakiegoœ maniaka bo chcieli sprawdziæ jaki to bêdzie mia³o wp³yw na osobowoœæ przyzwoitego, praworz¹dnego goœcia, takiego jak ja. A w ka¿dym razie, tyle uda³o mi siê ustaliæ.}
{581}{}{No dobra rozumiem. Wiêc, *jaki* to mia³o wp³yw na ciebie?}
{582}{}{Nie wiem, mam jakieœ koszmary, dobra? S³uchaj s³odziutka, wiele przeszed³em i nie jestem teraz w nastroju na... pieprzone przes³uchanie, dobra?
 Odpowiedzia³em na twoje pytania, a teraz mo¿e mi wreszcie powiesz co siê tu do cholery sta³o, odk¹d wsadzili mnie do lodu. Mam na myœli, no wiesz, to miejsce zesz³o na psy, a ty wygl¹dasz jakbyœ wysz³a z jakiejœ przygodowej opowieœci SF.}
{600}{}{[Kiedy podchodzisz do komory kriogenicznej, zauwa¿asz ciotowato wygl¹daj¹cego faceta skulonego na pod³odze. Podci¹ga kolana i przyciska je do klatki. Siedzi tam przez kilka chwil, patrz¹c pusto przed siebie dr¿¹c z zimna i szczekaj¹c zêbami. Wygl¹da, ¿e stopniowo siê uspokaja.]}
{601}{}{Yyy, czeœæ...}
{610}{}{[Odwraca g³owê w twoim kierunku i podnosi siê na nogi. Obserwuje ciê dok³adnie, potem rzuca spojrzenie na otoczenie niczym przera¿one zwierze. Kiedy jego spojrzenie wraca na ciebie, uspokaja siê, jego wspomnienia powoli do niego wracaj¹. Szybko zmienia siê jego postawa, jest teraz spokojny i pewny siebie, mimo swojej nagoœci.] Nie poznaje ciê, koleœ. Nie masz nic przeciwko ¿ebym siê ubra³?}
{611}{}{Myœlê, ¿e nie zaszkodzi...}
{612}{}{Nie s¹dzê ¿eby to by³...}
{620}{}{Oczywiœcie, ¿e nie masz nic przeciwko. Dziêki, koleœ. [Przechodzi obok ciebie i otwiera szafkê. Swobodnie ubiera siê w dobrze skrojony garnitur, potem chowa do kieszeni resztê zawartoœci szafki. Wyci¹ga grzebieñ kieszonkowy i zaczyna czesaæ i uk³adaæ swoje w³osy z precyzj¹ profesjonalisty.] Wiêc, gdzie jest doktorek?}
{621}{}{A sk¹d mam to wiedzieæ. Kimkolwiek by³ "doktorek", na pewno ju¿ nie ¿yje. Widzisz zgrywa³eœ sopel lodu przez BARDZO d³ugi czas.}
{622}{}{S³uchaj, ch³opczyku. Nie uwolni³em twojego psychotycznego ty³ka ¿eby móc odpowiadaæ na twoje g³upie pytania i patrzeæ jak siê pogr¹¿asz. Pozwalam ci ¿yæ tylko tak d³ugo ¿ebyœ móg³ przekazaæ mi wszelkie przydatne informacje jakie mo¿esz mieæ. Wiêc zacznij mówiæ. Im wiêcej mi mo¿esz powiedzieæ, tym d³u¿ej po¿yjesz.}
{630}{}{Naprawdê? [Przygl¹da ci siê zaciekawiony.] Nie wygl¹dasz na kogoœ st¹d, koleœ, jednak zdecydowa³eœ siê mnie uwolniæ, chcia³bym wiedzieæ dlaczego. Zak³adam, ¿e wiesz kim jestem?}
{631}{}{Ta, jesteœ Dex, prawda? Jeœli to co o tobie czyta³em jest prawd¹, to niez³y z ciebie skurwysyn. A mi siê to podoba.}
{632}{}{Có¿, wed³ug komputera, jesteœ Dex, narcystycznym, socjopatycznym, seryjnym morderc¹ z przed wielkiej ciszy. Odmrozi³em ciê tylko po to ¿eby ciê ubiæ jak chorego psa , którym jesteœ.}
{633}{}{Nie mam pojêcia, ale czuje od ciebie ten rodzaj z³ych wibracji, który lubiê.}
{640}{}{[Jego opanowanie znika, a oczy rozpala furia.] Wydaje ci siê, ¿e mo¿esz straszyæ MNIE? Czy ty masz w ogóle pojêcie z kim rozmawiasz? Tylko tu podejdŸ a poka¿ê ci do czego jestem zdolny!}
{641}{}{[Gotowe.]}
{650}{}{[Dex szczerzy siê do ciebie, ods³aniaj¹c zestaw idealnych zêbów produktu przedwojennej stomatologii dla ciebie wygl¹daj¹ dziwnie w ca³ej swojej per³owej symetrii.] Wiedzia³em, ¿e jest coœ co mi siê w tobie podoba. Masz dobry gust. Ale nie przypuszczam ¿ebyœ by³ te¿ fanem Króla?}
{651}{}{Yyy.... [Puste spojrzenie.]}
{652}{}{Pewnie, ¿e tak, uwielbiam to... jak to nazywasz... Król? Ta, jestem wielkim fanem.}
{660}{}{Niewa¿ne, koleœ. [Dex jeszcze raz rozejrza³ siê po pokoju i zagwizda³.] To miejsce zesz³o na psy. Mówisz, ¿e ile czasu minê³o?}
{661}{}{Minê³o ponad sto piêædziesi¹t lat odk¹d Wielka Cisza przynios³a zag³adê Staro¿ytnym... *twojemu* ludowi.}
{665}{}{Wielka Cisza? Staro¿ytni? Mo¿e oszczêdzisz mi gównianych przenoœni i po prostu powiesz co siê sta³o?}
{666}{}{Wielk¹ Cisz¹ mój lud nazywa koniec twojego œwiata. Kiedy wielki ogieñ spa³ z nieba i spali³ ziemiê. Wkrótce przekonasz siê, ¿e œwiat w niczym nie przypomina ju¿ tego który zna³eœ.}
{670}{}{Bez jaj, wiêc naprawdê zrzucili bomby, co? Czyli projekt Krypt nie by³ jednak marnotrawstwem pieniêdzy podatników.}
{671}{}{Czekaj, wiesz o Kryptach?}
{680}{}{Czy o nich wiem? Cholera, zabi³em moj¹ pierwsz¹ dziwkê niedaleko Krypty w Chicago. Co to by³y za dni... [Przerywa i patrzy na ciebie z rozbawieniem.] Ty to naprawdê ³ykn¹³eœ, co?}
{681}{}{MÓW DALEJ O KRYPTACH!}
{682}{}{Có¿, powinienem szukaæ Krypty dla mojego plemienia. Kiedy ju¿ j¹ znajdê mam stamt¹d wzi¹æ G.E.C.K., który ma uratowaæ moj¹ wioskê. Cokolwiek co mo¿esz mi powiedzieæ o Kryptach mo¿e mi cholernie u³atwiæ zadanie.}
{683}{}{Có¿, widzisz, zosta³em wybrany przez mój lud abym odnalaz³ Kryptê. Wielokrotnie ryzykowa³em ¿ycie ¿eby odnaleŸæ przeklêt¹ Œwiêt¹ Kryptê i w koñcu mi siê to uda³o. Jestem ciekaw co ty mo¿esz o nich wiedzieæ.}
{690}{}{Wiesz co ci powiem, koleœ. Potrzebujesz pomocy przy szukaniu Kryty, a ja potrzebuje kogoœ kto poka¿e mi co i jak w tym szalonym œwiecie. Co ty na to... wspólniku?}
{691}{}{Cholera, nie musisz mnie przekonywaæ. Z chêci¹ ciê z sob¹ zabiorê, tylko po to ¿eby zobaczyæ twoje rêkodzie³o osobiœcie.}
{692}{}{No nie wiem, Dex. Powiedzmy, ¿e ciê z sob¹ zabiorê i dotrzemy do wzglêdnego bezpieczeñstwa osiedla. Na miejscu, jak¹ mam pewnoœæ, ¿e nie spróbujesz mi poder¿n¹æ gard³a przy pierwszej nadarzaj¹cej siê sposobnoœci?}
{700}{}{Na pierwszy rzut oka widaæ, ¿e sam nie jesteœ œwiêty, wiec mogê zapytaæ o to samo. Ale ¿eby odpowiedzieæ na twoje pytanie, nie zabijecie ciê bo to mnie kurwa nie urz¹dza. Bêdê z tob¹ szczery, }
{701}{}{, gówno mnie obchodz¹ inni, dla mnie wa¿ny jestem tylko JA. Je¿eli œwiat jest tak popieprzony jak mówisz, to trzymaj¹c siê ciebie mam najwiêksz¹ szansê prze¿ycia. Nic prostszego ni¿ to, prawda?}
{702}{}{S³usznie. Ruszajmy.}
{703}{}{Ale z ciebie pojeb. W kulki sobie z tob¹ lecê, Dex. Nigdy nie zamierza³em ciê z sob¹ zabieraæ. Po prostu chcia³em siê trochê poœmiaæ zanim rozwalê ci ³eb.}
{800}{}{[Kiedy podchodzisz do komory kriogenicznej, zauwa¿asz ciotowato wygl¹daj¹cego faceta skulonego na pod³odze. Podci¹ga kolana i przyciska je do klatki. Siedzi tam przez kilka chwil, patrz¹c pusto przed siebie dr¿¹c z zimna i szczekaj¹c zêbami. Wygl¹da, ¿e stopniowo siê uspokaja.]}
{801}{}{Yyy, czeœæ...}
{810}{}{[Odwraca g³owê w twoim kierunku i podnosi siê na nogi. Obserwuje ciê dok³adnie, potem rzuca spojrzenie na otoczenie niczym przera¿one zwierze. Kiedy jego spojrzenie wraca na ciebie, uspokaja siê, jego wspomnienia powoli do niego wracaj¹. Szybko zmienia siê jego postawa, jest teraz spokojny i pewny siebie, mimo swojej nagoœci.] Czeœæ lala, wiem ¿e niez³y ze mnie widok, ale jest tu Ÿdziebko zimno. Nie masz nic przeciwko ¿ebym siê ubra³?}
{811}{}{Myœlê, ¿e nie zaszkodzi...}
{812}{}{Nie s¹dzê ¿eby to by³...}
{820}{}{Oczywiœcie, ¿e nie masz nic przeciwko. Dziêki, ma³a. [Przechodzi obok ciebie delikatnie klepi¹c ciê w ty³ek i otwiera szafkê. Swobodnie ubiera siê w dobrze skrojony garnitur, potem chowa do kieszeni resztê zawartoœci szafki. Wyci¹ga grzebieñ kieszonkowy i zaczyna czesaæ i uk³adaæ swoje w³osy z precyzj¹ profesjonalisty.] Chyba ciê tu wczeœniej nie widzia³em, lala, a nie s¹dzê ¿ebym zapomnia³ taka buŸkê. Nazywam siê Dex, ale to ju¿ pewnie wiesz. Mogê poznaæ twoje imiê?}
{821}{}{Jestem }
{822}{}{. Ale zanim siê jeszcze bardziej spoufalisz, powinieneœ wiedzieæ, ¿e mam tak¹ zasadê, ¿e nie spotykam siê z mê¿czyznami o reputacji mordercy, którzy byli zamro¿eni przez ponad sto piêædziesi¹t lat. A jak dotkniesz mojego ty³ka jeszcze raz to wyrwê ci fiuta, zrozumia³eœ?}
{823}{}{Jestem }
{824}{}{, mi³o ciê poznaæ, Dex. Nawet nie mogê sobie wyobraziæ jak siê czujesz budz¹c siê po ponad stu piêædziesiêciu latach kriogenicznego snu..}
{825}{}{Ta, oczywiœcie, ¿e... nie, ty popieprzony zboku. Odmrozi³am ciê tylko po to ¿eby ciê uœpiæ jak chorego psa, którym jesteœ.}
{826}{}{Zapomnij o imionach. Co powiesz na zdjêcie z powrotem tych ubrañ i pokazanie mi z czego s¹ zrobieni przed wojenni mê¿czyŸni.}
{830}{}{[Uœmiechn¹³ siê do ciebie i zacz¹³ rozbieraæ.] Dziewczyno, jesteœ w moim typie. Przygotuj siê na doœwiadczenie Dexa, Ksiêcia sexu.}
{831}{}{[Po kilku godzinach intensywnego uprawiania seksu na pod³odze laboratorium, oboje padacie zmêczeni. Zauwa¿asz, ¿e Dex ostro¿nie siêga do ukrytego no¿a. Szybko ³apiesz go za jaja.]}
{832}{}{Dotknij tego no¿a, a zamieniê ciê w Ksiê¿niczkê. A poza tym po co to psuæ? Razem mo¿emy mieæ jeszcze niez³y ubaw.}
{833}{}{Ja... myœlê, ¿e siê zakocha³em. [Dex do³¹cza do twojej dru¿yny.]}
{840}{}{Jak, ¿e niby co? Wróæ trochê, cukiereczku. Powiedzia³aœ w³aœnie sto piêædziesi¹t lat? [Potrz¹sa g³ow¹ z niedowierzaniem.]
 Nie-kurde-wiarygodne. [Sprawdza swoje odbicie w lustrze.] Ale musisz przyznaæ, wygl¹dam zabójczo jak na mój wiek.
 [Dex szczerzy siê do ciebie, ods³aniaj¹c zestaw idealnych zêbów produktu przedwojennej stomatologii dla ciebie wygl¹daj¹ dziwnie w ca³ej swojej per³owej symetrii.]}
{841}{}{Pewnie, niektóre dziewczyny mog¹ uwa¿aæ ciê za atrakcyjnego, ale na pewno ich zapa³ szybko studzi ta twoja mania zabijania.}
{842}{}{Dobra, to przyprawia mnie o md³oœci. Zobaczmy czy bêdzie z ciebie taki przystojniak jak w³aduje ci kilka kul w twarz.}
{843}{}{Pewnie, niektóre dziewczyny mog¹ uwa¿aæ ciê za atrakcyjnego, ale na pewno ich zapa³ szybko studz¹ z³e wibracje psychotycznego mordercy, które czuæ od ciebie.}
{844}{}{NieŸle jak na cz³owieka lodu. A w³aœciwie, czemu by³eœ tam zamro¿ony?}
{845}{}{Eh, nie jesteœ w moim typie. A w³aœciwie, czemu by³eœ tam zamro¿ony?}
{846}{}{Dobra, to przyprawia mnie o md³oœci. Zobaczmy czy bêdzie z ciebie taki przystojniak jak w³aduje ci kilka kul w twarz.}
{850}{}{Có¿, zwykle zauwa¿aj¹ to dopiero kiedy jest ju¿ za póŸno. Ale poza tym... [Dex jeszcze raz rozejrza³ siê po pomieszczeniu i zagwizda³.]
 To miejsce naprawdê zesz³o na psy. Wiêc, co mnie ominê³o?}
{851}{}{Minê³o ponad sto piêædziesi¹t lat odk¹d Wielka Cisza przynios³a zag³adê Staro¿ytnym... *twojemu* ludowi.}
{855}{}{Wielka Cisza? Staro¿ytni? Mo¿e oszczêdzisz mi gównianych przenoœni i po prostu powiesz co siê sta³o?}
{856}{}{Wielk¹ Cisz¹ mój lud nazywa koniec twojego œwiata. Kiedy wielki ogieñ spa³ z nieba i spali³ ziemiê. Wkrótce przekonasz siê, ¿e œwiat w niczym nie przypomina ju¿ tego który zna³eœ.}
{860}{}{Bez jaj, wiêc naprawdê zrzucili bomby, co? Czyli projekt Krypt nie by³ jednak marnotrawstwem pieniêdzy podatników.}
{861}{}{Czekaj, wiesz o Kryptach?}
{870}{}{Czy o nich wiem? Cholera, zabi³em moj¹ pierwsz¹ dziwkê niedaleko Krypty w Chicago. Co to by³y za dni... [Przerywa i patrzy na ciebie z rozbawieniem.] Ma³a, ty to naprawdê ³yknê³aœ, co?}
{871}{}{MÓW DALEJ O KRYPTACH!}
{872}{}{Có¿, powinnam szukaæ Krypty dla mojego plemienia. Kiedy ju¿ j¹ znajdê mam stamt¹d wzi¹æ G.E.C.K., który ma uratowaæ moj¹ wioskê. Cokolwiek co mo¿esz mi powiedzieæ o Kryptach mo¿e mi cholernie u³atwiæ zadanie.}
{873}{}{Có¿, widzisz, zosta³am wybrana przez mój lud abym odnalaz³a Kryptê. Wielokrotnie ryzykowa³am ¿ycie ¿eby odnaleŸæ te przeklêt¹ Œwiêt¹ Kryptê i w koñcu mi siê to uda³o. Jestem ciekawa co ty o nich mo¿esz wiedzieæ.}
{880}{}{Wiesz co ci powiem, ma³a. Potrzebujesz pomocy przy szukaniu Kryty, a ja potrzebuje kogoœ kto poka¿e mi co i jak w tym szalonym œwiecie. Co ty na to... wspólniczko?}
{881}{}{Cholera, nie musisz mnie przekonywaæ. Z chêci¹ ciê z sob¹ zabiorê, tylko po to ¿eby zobaczyæ twoje rêkodzie³o osobiœcie.}
{882}{}{No nie wiem, Dex. Powiedzmy, ¿e ciê z sob¹ zabiorê i dotrzemy do wzglêdnego bezpieczeñstwa osiedla. Na miejscu, jak¹ mam pewnoœæ, ¿e nie spróbujesz mi poder¿n¹æ gard³a przy pierwszej nadarzaj¹cej siê sposobnoœci?}
{883}{}{A ja na to, umowa stoi... wspólniku.}
{884}{}{Có¿, s¹dzê, ¿e twoja wiedza o staro¿ytnych mo¿e mi siê przydaæ... myœlê, ¿e umowa stoi.}
{885}{}{Naprawdê nie mam czasu ¿eby ci "pokazaæ co i jak". Jestem pewna, ¿e sam sobie œwietnie poradzisz, "ma³y".}
{890}{}{Na pierwszy rzut oka widaæ, ¿e sama nie jesteœ œwiêta, wiec mogê zapytaæ o to samo. Ale ¿eby odpowiedzieæ na twoje pytanie, nie zabijecie ciê bo to mnie kurwa nie urz¹dza. Bêdê z tob¹ szczery, }
{891}{}{, gówno mnie obchodz¹ inni, dla mnie wa¿ny jestem tylko JA. Je¿eli œwiat jest tak popieprzony jak mówisz, to trzymaj¹c siê ciebie mam najwiêksz¹ szansê prze¿ycia. Nic prostszego ni¿ to, prawda?}
{892}{}{S³usznie. Ruszajmy.}
{893}{}{Ale z ciebie przyg³up. W kulki sobie z tob¹ lecê Dex. Nigdy nie zamierza³am ciê z sob¹ zabieraæ. Po prostu chcia³am siê trochê zabawiæ zanim rozwalê ci ³eb.}
{900}{}{Zaraz do tego przejdziemy. Ale mo¿e najpierw, opowiesz mi co siê tu do cholery sta³o, odk¹d wsadzili mnie do lodu. Mam na myœli, no wiesz, to miejsce zesz³o na psy, a ty wygl¹dasz jakbyœ wysz³a z jakiejœ przygodowej opowieœci SF.}
{1000}{}{Co s³ychaæ?}
{1001}{}{[Dex podnosi na ciebie brew.] Zar¿niemy coœ?}
{1002}{}{Mów do mnie.}
{1003}{}{[Dex uœmiecha siê.] Jak leci, koleœ?}
{1004}{}{Potrzebujesz czegoœ?}
{1005}{}{Co Dex mo¿e dla ciebie zabiæ yyy... tzn. zrobiæ?}
{1010}{}{Co s³ychaæ?}
{1011}{}{[Dex podnosi na ciebie brew.] Zar¿niemy coœ, ma³a?}
{1012}{}{Powiedz coœ, ma³a.}
{1013}{}{[Dex uœmiecha siê.] Lala, jak leci?}
{1014}{}{Potrzebujesz czegoœ? Czegokolwiek? [Dex siê szczerzy.]}
{1015}{}{Co Dex mo¿e dla ciebie zrobiæ, ma³a?}
{1100}{}{Mo¿emy siê toczyæ dalej?}
{1101}{}{Ruszamy st¹d, czy co?}
{1102}{}{Gotowi? A¿ mnie nosi ¿eby st¹d iœæ. Zw³aszcza, ¿e ju¿ kogoœ szukaj¹.}
{1103}{}{Jednak nie mo¿esz siê beze mnie obyæ co?}
{1104}{}{Idziemy? Nie mam w zwyczaju czekaæ na innych.}
{1105}{}{Daj spokój. By³em zamro¿ony przez ponad sto piêædziesi¹t lat. Chcê siê rozruszaæ.}
{1106}{}{Zaczynam siê niecierpliwiæ.}
{1110}{}{Mo¿esz mnie ju¿ ze sob¹ zabraæ?}
{1111}{}{Ruszajmy.}
{1112}{}{Nie, jeszcze nie.}
{1200}{}{Wiêc, co mo¿esz mi powiedzieæ o Kryptach?}
{1201}{}{A teraz, pamiêtasz coœ o Kryptach?}
{1202}{}{Czy jest coœ u¿ytecznego co mo¿esz mi powiedzieæ o czasach przed Wielk¹ Cisz¹?}
{1210}{}{Dobra, pomyœlmy... Uch. Wiesz co? Mój umys³ jest ci¹gle zamglony co do szczegó³ów. Musisz mnie zapytaæ póŸniej.}
{1211}{}{Hmm. No dobra.}
{1220}{}{Krypty... Krypty... Nie, jeszcze nie.}
{1221}{}{Hmm. No dobra.}
{1230}{}{Tak, w³aœciwie, pamiêtam, ¿e... Czekaj, niewa¿ne, wylecia³o mi z g³owy.}
{1231}{}{Hmm. No dobra.}
{1240}{}{Dobra, mieszka³em ko³o Krypty w Chicago. Czy to mo¿e Ci w czymœ pomóc?}
{1241}{}{Wiesz czy by³ tam G.E.C.K.?}
{1242}{}{Jestem pewny, ¿e tak. W³aœciwie to chyba wszystkie go mia³y.}
{1243}{}{W porz¹dku, wreszcie cos mamy. Mo¿esz mi powiedzieæ gdzie jest ta Krypta?}
{1244}{}{¯aden problem. Jakieœ 3219 kilometrów w tamt¹ stronê. [Dex pokazuje na wschód.]}
{1245}{}{Aha, no dobra. Niewa¿ne.}
{1250}{}{By³ sobie taki facet, wspanialszy od innych, nazywaliœmy go, "Król". By³ przystojny o niepowtarzalnym stylu, wspania³ej fryzurze i g³osie ze z³ota. Zwyk³ym ruchem miednicy móg³ zap³odniæ ka¿d¹ kobietê w zasiêgu wzroku. By³ czczony jak bóg przez ludzi na ca³ym œwiecie. On by³ moim ojcem.}
{1251}{}{Interesuj¹ce...}
{1260}{}{Byli te¿ nieœmiertelni, którzy ¿yli pomiêdzy zwyk³ymi ludŸmi. Musi walczyæ ze sob¹ na miecze, mo¿e zostaæ tylko jeden ¿eby siêgn¹æ po "Nagrodê".}
{1261}{}{Czekaj. Skoro byli nieœmiertelni, to jak moli siê nawzajem zabijaæ?}
{1262}{}{Mo¿na ich by³o zabiæ odcinaj¹c im g³owê. Kiedy jeden nieœmiertelny pozbawi³ g³owy drugiego, zaczyna³o siê lokalne trzêsienie ziemi i wygrany przejmowa³ moce zabitego przeciwnika.}
{1263}{}{Co dok³adnie rozumiesz przez "moce"?}
{1264}{}{Yyy, moce do walki? Fizyczn¹ si³ê? Tego nie wiem, to by³o niejasne.}
{1265}{}{Interesuj¹ce...}
{1270}{}{By³y te¿ ogromne jaszczurki, niektóre wiêksze od budynków, na których jeŸdzili ludzie. Nazywaliœmy je dinozaurami i uwa¿a³o siê je za najlepszych przyjació³ cz³owieka.}
{1271}{}{£a³, a ty mia³eœ takiego?}
{1272}{}{Oczywiœcie. JeŸdzi³em na Tyranozaurze, najwredniejszym z najwiêkszych jaszczurów. Tylko, ¿e mój by³ bardziej zajebisty od innych bo mia³ skrzyd³a. W³aœciwie to by³ smokiem.}
{1273}{}{Interesuj¹ce...}
{1280}{}{W roku 2011, nast¹pi³o Przebudzenie i d³ugo nieobecne magiczne istoty, jak Orki, Elfy, Trole i Krasnoludy powróci³y, razem z magi¹ na ziemiê. Magia i technologia zderzy³y siê w mrocznym œwiecie wojen korporacyjnych prowadzonych w cieniu przeludnionych metropolii.}
{1281}{}{£a³, co siê sta³o z tymi magicznymi istotami?}
{1282}{}{Myœlê, ¿e zginê³y kiedy spad³y bomby. Chocia¿ wygl¹da na to, ¿e w okolicy zosta³o trochê Krasnoludów, Troli i Zombich.}
{1283}{}{Interesuj¹ce...}
{1290}{}{By³a te¿ jedna gigantyczna jaszczurka nazywana God¿ill¹. God¿illa na zmianê terroryzowa³a Japoniê i ratowa³a j¹ przed kosmicznymi najeŸdŸcami. By³a jeszcze jedna gigantyczna jaszczurka nazywana Tarrasque. Myœlê, ¿e by³y kuzynkami.}
{1291}{}{£a³, i co siê z nimi sta³o?}
{1292}{}{God¿illa zosta³a zabita przez Ferris Bueller. A do walki z Tarrasque, wys³aliœmy olbrzymiego robota. Robot uderzy³ Tarrasque tak mocno, ¿e rozpad³ siê na tysi¹ce ma³ych Tarrasque, które rozproszy³y siê po ca³ej Kaliforni.}
{1293}{}{Interesuj¹ce...}
{1300}{}{W tamtych czasach ziemia by³a pe³na gor¹cych laseczek, a ja pobi³em œwiatowy rekord partnerek seksualnych.}
{1301}{}{Rozumiem. Wiesz co, Dex, niektóre z tych rzeczy o których mówisz s¹ trochê... naci¹gane. Mam takie dziwne wra¿enie, ¿e k³amiesz.}
{1302}{}{Hej, a co mo¿e to ty jesteœ z tamtych czasów, co? Nie, to ja wtedy ¿y³em. Wiêc ja tu jestem ekspertem w tych sprawach? Zaufaj mi to wszystko prawda. Ale wiesz co, skoro nie zamierzasz mi wierzyæ to nic ci ju¿ wiêcej nie opowiem.}
{1303}{}{Co? Szkoda, do tej pory twoje opowieœci by³y taaakie pomocne.}
{1400}{}{Po prostu mi powiedz gdzie mnie chcesz.}
{1401}{}{Po prostu mi powiedz gdzie mnie chcesz, ma³a.}
{1402}{}{¯aden problem. Nie chcia³bym nikogo stresowaæ. [Dex szczerzy siê.]}
{1403}{}{Pewnie. Skoro uwa¿asz, ¿e musisz mnie mieæ na oku, mi to nie przeszkadza.}
{1404}{}{Pewnie. To zrozumia³e, ¿e ciê¿ko siê przy mnie skoncentrowaæ. [Dex szczerzy siê.]}
{1405}{}{[Dex podnosi na ciebie brew i mruga do ciebie.]}
{1406}{}{Nie ma sprawy.}
{1500}{}{[Dex uœmiecha siê z³owieszczo.] Co? Nie ufasz mi, kiedy jestem uzbrojony? [Dex œmieje siê.] Jasna sprawa, skoro ma ciê to uspokoiæ.}
{1600}{}{Yyy, pewnie. Ale ¿eby by³o jasne, pamiêtasz, ¿e wolê laseczki... prawda?}
{1601}{}{W porz¹siu. [Dex zdejmuje zbroje i zaczyna siê rozbieraæ z ubrania. Zatrzymuje siê kiedy zauwa¿a twoje spojrzenie.] Hej, lala wysy³asz mi mieszane sygna³y. Dex nie lubi kiedy siê z nim pogrywa. Tylko zbroja, dobra.}
{1700}{}{Có¿, potrafiê czyniæ cuda z no¿em. To jak sztuka. Jest coœ wyj¹tkowego w sposobie w jaki ostrze tnie cia³o, wiesz co mam na myœli?}
{1701}{}{Ta... jasne. Jest jeszcze coœ czym potrafisz siê pos³ugiwaæ? I tym razem odpowiadaj¹c nie hamuj siê przed byciem mniej upiornym.}
{1702}{}{Dobra, mój Wuj by³ jednym z tych twardog³owych wojskowych. Nauczy³ mnie pos³ugiwaæ siê pistoletami i pistoletami maszynowymi, a nawet mia³em okazje pobawiæ siê dzia³aj¹cymi prototypami broni energetycznej. Myœla³, ¿e pójdê w jego œlady i zostanê marionetk¹ Wujka Sama, ale ja, hmm... no có¿ powiedzmy, ¿e poszed³em inn¹ drog¹.}
{1703}{}{Tak ju¿ lepiej. Coœ jeszcze?}
{1704}{}{By³em znany z tego, ¿e st³uk³em parê ty³ków starymi dobrymi kastetami. Kiedy by³em nastolatkiem, próbowa³em swoich si³ w Karate przez jakiœ czas, ale nie mog³em znieœæ tych g³odnych kawa³ków o byciu bardziej zdyscyplinowanym, wiêc powiedzia³em im ¿eby siê odpieprzyli. Chcesz wiedzieæ coœ jeszcze?}
{1705}{}{Powinno wystarczyæ. Dziêki.}
{1800}{}{Dobra, jestem gotowy do drogi.}
{1801}{}{Bywa³o lepiej, ale sobie poradzê.}
{1802}{}{Nie czujê siê za dobrze.}
{1803}{}{Chyba Król mnie wzywa. Widzê œwiat³o...}
{1900}{}{¯aden problem. Ale pamiêtaj beze mnie nie jesteœ ju¿ taki fajny. Tak tylko mówiê...}
{1901}{}{Jasne, do zobaczenia póŸniej.}
{1902}{}{Jasne, poczekam. Ale jeœli nie wrócisz, to zacznê ciê szukaæ, a kiedy ciê znajdê to nie bêdzie przyjemne.}
{1903}{}{W porz¹dku, przynajmniej dopóki nie sp³awiasz mnie ¿eby zrobiæ miejsce dla jakiegoœ dupka. Bo obiecuje ci jestem najlepszy w ka¿dy wyobra¿alny sposób.}
{1904}{}{Nie ma sprawy.}
{1905}{}{¯aden problem, ma³a.}
{1906}{}{W porz¹dku, przynajmniej dopóki nie sp³awiasz mnie ¿eby zrobiæ miejsce dla jakiegoœ dupka. Bo obiecuje ci jestem najlepszy w ka¿dy wyobra¿alny sposób.}
{1907}{}{Robi ci siê przy mnie gor¹co i to ci przeszkadza, tak? Rozumiem.}
{2000}{}{Mój sprzêt, co z nim?}
{2001}{}{Patrz, wiem, ¿e by³em w lodzie bardzo d³ugo, ale wierz mi, WSZYSTKO dzia³a jak nale¿y. Jak chcesz, mogê ci to udowodniæ tu i teraz. [Dex urywa kiedy zauwa¿a twój wzrok.] A, rozumiem chodzi ci o *inny* sprzêt. Co z nim?}
{2010}{}{Trochê przy tobie t³oczno. Daj mi znaæ jak siê to zmieni.}
{2020}{}{Za cholerê nie bêdê z tob¹ podró¿owa³. Jaka morda, brzydka, ¿e ja pierdolê.}
{2030}{}{Toczmy siê dalej.}
{2031}{}{Najwy¿szy czas, ruszajmy.}
{3000}{}{Dobra, opowiedz mi swoj¹ historie?}
{3001}{}{Co, chcesz us³yszeæ o mim ¿yciu? S³uchaj, wiem, ¿e jestem fascynuj¹cy, ale nie mam ochoty staæ tu ca³y dzieñ i mówiæ o sobie. Zaschnie mi w ustach, a tu nie ma za du¿o wody, no wiesz sytuacja raczej nie do pozazdroszczenia. Ale chyba mogê ci to streœciæ jeœli ciê to tak bardzo interesuje... W³aœciwie, to lubiê mówiæ o sobie. Chcesz streszczenie czy pe³n¹ wersjê ze szczegó³ami?}
{3002}{}{Streszczenie.}
{3003}{}{Dawaj ca³¹, ze szczegó³ami.}
{3004}{}{Nie wa¿ne, przesta³o mnie to interesowaæ.}
{3010}{}{Dobra, w³aœciwie to od ma³ego lubi³em zabijaæ ró¿ne rzeczy. Móg³bym mówiæ o moim dzieciñstwie i moich gównianych rodzicach, analizowaæ dlaczego tak to lubiê, ale nie potrzebuje wymówek. Po prostu robiê to bo potrafiê i jest to dla mnie œwietna zabawa. Jeszcze zanim skoñczy³em szesnaœcie lat dni spêdza³em jako znany ³amacz serc, a noce jako rozpruwacz m³odych pracuj¹cych dziewcz¹t z Chicago.}
{3011}{}{Aha. Mów dalej.}
{3012}{}{Pewnego dnia przy³apa³em moj¹ dziewczynê robi¹c¹ ty³kiem co umia³a najlepiej z innym goœciem. Zat³uk³em oboje, podpali³em mieszkanie i uciek³em z Chicago. Nastêpne dziesiêæ lat spêdzi³em podró¿uj¹c po kraju, uwodz¹c i morduj¹c dziewczyny. W koñcu mnie z³apali, a mój proces zrobi³ ze mnie bardzo znan¹ osobê.}
{3013}{}{A potem?}
{3014}{}{Potem jedna z moich nowych fanek, Alicja, pomog³a mi uciec. We dwójkê pojechaliœmy na trzy tygodniow¹ wycieczkê po kraju, morduj¹c dowoli, a¿ w koñcu zdjêto nas w strzelaninie. PóŸniej z jakiœ powodów, Ktoœ kaza³ mnie pozszywaæ i przeprowadziæ na mnie te wszystkie testy. I tak skoñczy³em w AOŒ, gdzie le¿a³em zamro¿ony.}
{3015}{}{Dziêki za opowieœæ.}
{3020}{}{Hmm zobaczmy... Moja mama by³a narkomank¹ i dziwk¹, a ojciec na³ogowym alkoholikiem. Na szczêœcie chocia¿ dziadka mia³em w porz¹dku jak na staruszka. Wprowadzi³ mnie w muzykê Króla. Niestety zabra³a go Nowa Plaga, kiedy mia³em siedem lat. Kiedy mia³em lat dziesiêæ, widzia³em z szafy jak mój ojciec katuje na œmieræ moj¹ matkê za to, ¿e zapomnia³a nakarmiæ naszego psa, Kapitana Robeenie.}
{3021}{}{Nie zbyt mi³y pocz¹tek. Mów dalej.}
{3022}{}{Suka powinna pamiêtaæ, ¿e psa trzeba nakarmiæ. Mów dalej.}
{3023}{}{Ojca zabrali, a mnie wys³ali pod opiekê mojego wuja i ciotki. Wiesz, ju¿ by³em wtedy ma³ym czarcim pomiotem, a mój wujek, bêd¹cy wojskowym, myœla³, ¿e naprostuje mnie na têpi¹cego Czerwonych ¿o³nierza, jak swojego syna, którego straci³. Stara³ siê jak móg³, ale zemnie by³ uparty skurwysyn.}
{3024}{}{Aha. Mów dalej.}
{3025}{}{W ka¿dym razie, wiele razy siê przeprowadzaliœmy, dopiero kiedy poszed³em do szko³y œredniej osiedliœmy na sta³e w Chicago. To wtedy zacz¹³em wymykaæ siê noc¹ mordowaæ dziwki. Zabija³em ró¿ne rzeczy odk¹d pamiêtam, ale zabijanie zwierz¹t s¹siadów nie by³o nawet w po³owie tak zabawne, wiesz?}
{3026}{}{Jasne.}
{3027}{}{Wiêc by³o ca³kiem s³odko, przez wiêkszoœæ czasu. To znaczy nienawidzi³em wuja i ciotki, ale za to w szkole by³em Panem Popularnym. Ka¿dy facet chcia³ byæ moim kumplem, a ka¿da panna by³a gotowa dla mnie roz³o¿yæ nogi. Za wyj¹tkiem jednej, Vicky. Musia³em siê naprawdê postaraæ. Zadziwiaj¹ce, wiem, ale w koñcu mi siê uda³o i zosta³a moj¹ dziewczyn¹.}
{3028}{}{A jednoczeœnie przez ca³y ten czas noc¹ bawi³eœ siê w seryjnego mordercê?}
{3029}{}{Naprawdê nie obchodz¹ mnie twoje szkolne mi³oœci. Zapomnij, mam doœæ twojej historyjki.}
{3030}{}{Ta. [Uœmiecha siê.] Co to by³y za dni. Naprawdê by³em wtedy szczêœliwy, wiesz? Kiedy skoñczyliœmy szko³ê, Vicky i ja znaleŸliœmy sobie przytulne gniazdko i przez jakiœ czas by³o naprawdê super. Ale ta dziwka musia³a wszystko zepsuæ puszczaj¹c siê za moimi plecami.}
{3031}{}{Jak œmia³a.}
{3032}{}{Przy³apa³em j¹ w trakcie i coœ we mnie pêk³o. Zrobi³em siê naprawdê brutalny. Ponios³o mnie i by³em nieostro¿ny, nie by³o ju¿ jak tego zakamuflowaæ. Wiêc po tym jak z nimi skoñczy³em podpali³em mieszkanie i uciek³em z miasta. Du¿o podró¿owa³em, przelecia³em sporo panienek wiêkszoœæ z nich zostawiaj¹c martwych. Nie by³o tak Ÿle, wiesz? Zajê³o im to dziesiêæ lat, ale w koñcu d³ugie ramiê sprawiedliwoœci mnie dosiêg³o.}
{3033}{}{Oho. I co dalej?}
{3034}{}{Trafi³em pod s¹d, proces zamieni³ siê w medialn¹ farsê. Panienkom siê podoba³o bo niez³y ze mnie przystojniak, a wszystkim innym dlatego, ¿e by³a to niez³a odmiana od wiadomoœci o Nowej Pladze i polityce. Wiêc pomyœla³em, ¿e dam im niez³y pokaz.}
{3035}{}{I co zrobi³eœ?}
{3036}{}{Có¿ zdoby³em wówczas mnóstwo fanów, ale jedna by³a szczególna, prawdziwa laska, Alicja. Mówi³a, ¿e mnie kocha, i ¿e zrobi dla mnie wszystko. Wiêc w czasie procesu, pomog³a mi uciec. Plan mo¿e nie by³ idealny, ale miêliœmy wystarczaj¹co szczêœcia ¿eby siê uda³o. A potem wszystko oszala³o... Na pewno nic ci siê o nas nie obi³o o uszy?}
{3037}{}{Na pewno, nie. Mów dalej.}
{3038}{}{Nie nigdy i mam nadziejê, ¿e ju¿ o tym nie us³yszê. Zapomnij, nudzi mnie to.}
{3039}{}{Teraz kiedy by³em z Alicj¹, ciê¿ko by³o porzuciæ stare nawyki uwodzenia i zarzynania kobiet. Zamiast tego zaczêliœmy razem zabijaæ ka¿dego kto siê nawin¹³. Nie wa¿ne jak m³oda czy stara by³a ofiara zabijaliœmy bez faworyzowania. Ale zabijaj¹c w ten sposób, bez umiaru byliœmy ³atwi do namierzenia. W trzy tygodnie zapêdzili nas w kozi róg. Zastrzelili mnie i Alicje, rozchlapali jej mózg po ulicy.}
{3040}{}{Rozumiem. I co dalej?}
{3041}{}{By³em pewny, ¿e umrê, ale wtedy wkroczy³ ten Goœciu i mnie zabra³. Wyleczyli mnie w stu procentach, a potem zaczêli testy, próbuj¹c siê dowiedzieæ co sprawi³o, ¿e taki by³em... W ka¿dym razie resztê znasz. No i zasch³o mi w gardle. Cholera, mia³em nadzieje, ¿e tego uniknê.}
{3042}{}{Dziêki za opowieœæ.}
{3100}{}{Jakieœ rady, jakie mo¿esz mi daæ?}
{3101}{}{Rady? Jakiego typu?}
{3102}{}{Có¿. Myœlê, ¿e masz pewne umiejêtnoœci.}
{3103}{}{Och, mam *wiele* ró¿nych umiejêtnoœci. Ale jeœli szukasz rady... [Patrzy na ciebie, a potem przytakuje.] A co mi tam, do cholery. Pozwól, ¿e podpowiem ci co robiæ ¿eby panienki s³a³y ci siê do stóp. Musisz zacz¹æ od...}
{3104}{}{Chcesz zobaczyæ co potrafiê? Mogê ci pokazaæ kiedy tylko zechcesz, cukiereczku. Ale jeœli szukasz rady... [Patrzy na ciebie, a potem przytakuje.] A co mi tam, do cholery. Pozwól, ¿e podpowiem ci co robiæ ¿eby faceci jedli Ci z rêki. Pierwsza rzecz jak¹ musisz zrobiæ...}
{3105}{}{Proszê bardzo. Ale nie zdradŸ nikomu tych paru sekretów postêpowania z ludŸmi, o których ci powiedzia³em.}
{3106}{}{Dziêkujê.}
{4000}{}{Cz³owieku uwielbiam tê post-nuklearn¹ przysz³oœæ.}
{4001}{}{No chodŸ. Czas na trochê... przemocy.}
{4002}{}{ZnajdŸmy wiêcej ³adnych dziewczyn ¿eby... yyy, popodziwiaæ.}
{4003}{}{Poszukamy wiêcej cielesnej wiedzy.}
{4004}{}{Czy kiedykolwiek roz³o¿y³eœ dziewczynê na ³ó¿ku ¿eby j¹ rozp³ataæ? Mówiê ci, piêkno absolutne.}
{4005}{}{Naprawdê muszê coœ rozp³ataæ, szybko...}
{4006}{}{Mog³oby siê wydawaæ, ¿e zw³oki w ³ó¿ku s¹ okropne, ale zdziwi³byœ siê.}
{4007}{}{[Œpiewa.] Wbi³em topór w ³eb mojej dziewczyny, skoñczy siê to odsiadk¹... tak dobrze wygl¹da³a w czerwieni...[Œpiewa]}
{4008}{}{[Œpiewa.] bo jestem z³yyyyy, na drugie imiê mam, nieszczêœcie...[Œpiewa]}
{4009}{}{Uda³o ci siê odkopaæ mój garnitur? To s³odkie maleñstwo zosta³o uszyte w Grand Rapids, w Michigan.}
{4010}{}{Wiêc... jak myœlisz gdzie na pustkowiach maj¹ ¿el do w³osów?}
{4011}{}{Wiem, ¿e to brzmi obrzydliwie, ale nie krytykuj jajników sma¿onych w g³êbokim oleju dopóki ich nie spróbujesz.}
{4012}{}{[Wyci¹ga kieszonkowy grzebieñ i uk³ada w³osy.]}
{4020}{}{Hej. Ja tu kurde krwawiê.}
{4021}{}{Cz³owieku, nie jest ze mn¹ dobrze.}
{4022}{}{ZaprowadŸ mnie do cholernego lekarza.}
{4023}{}{Bêdziesz tak staæ i patrzeæ jak siê wykrwawiam na œmieræ czy jednak coœ z tym zrobisz?}
{4030}{}{Trochê siê tutaj dziwnie czuje...}
{4031}{}{Hej, czuje siê trochê napromieniowany. Jeœli nie jest to promieniowanie tego typu co daje super moce, to siê zdenerwujê.}
{4040}{}{Wiesz co, Ÿle na mnie wp³ywasz.}
{4041}{}{Staram siê trzymaæ z daleka od tego syfu. Ale skoro nalegasz...}
{4042}{}{Moje cia³o jest œwi¹tyni¹, ale ten jeden raz nie zaszkodzi.}
{4043}{}{Jeœli to spowoduje jakieœ trwa³e uszkodzenia, to ciê potnê.}
{4045}{}{Czujê siê ju¿ du¿o lepiej.}
{4046}{}{Du¿o lepiej.}
{4050}{}{Hej! Uwa¿aj na w³osy.}
{4051}{}{Hej, nie popêdzaj perfekcji.}
{4060}{}{Wiesz, ¿e to nie to samo kiedy ich krew jest ci¹gle ciep³a?}
{4061}{}{Mam nadziejê, ¿e robiliœcie notatki.}
{4062}{}{Dziewczyny sta³y siê doœæ przera¿aj¹ce, po koñcu œwiata... Jak dla mnie bomba.}
{4063}{}{...i dlatego laseczki zwyk³y nazywaæ mnie "Dex, Ksi¹¿ê Seksu".}
{4070}{}{Czujê md³oœci. Chyba, ktoœ mnie otru³.}
{4071}{}{Czujê siê jak bym mia³ wyrzygaæ wnêtrznoœci.}
{4080}{}{Nie mogê ruszaæ t¹ koñczyn¹. Potrzebuje pomocy medycznej.}
{4081}{}{Chyba w³aœnie straci³em czucie w tej koñczynie. Czy to Ÿle?}
{4090}{}{W³aœnie zrobi³o siê trochê, niewyraŸnie. Gdzie wszyscy poszli?}
{4091}{}{Chyba krew zaczê³a mi wyp³ywaæ oczami.}
{4100}{}{Wiêc, tatua¿e na twarzy, co? Chyba jak bym by³ tak paskudny jak ten koœciano-nosy, tutaj, te¿ wola³bym to zamalowaæ.}
{4101}{}{Hej, wytatuowana twarzy. Jesteœ kanibalem, czy coœ? Mo¿e moglibyœmy wymieniæ siê przepisami.}
{4102}{}{Odnoszê wra¿enie, ¿e ten twój kumpel Sulik nie mo¿e mnie znieœæ. Mo¿e czas go sprzedaæ?}
{4110}{}{A teraz serio, o co chodzi z tym przysadzistym, ³ysym kolesiem? Trzymasz go z litoœci czy co?}
{4111}{}{Wiêc Vic, s³ysza³em, ¿e masz odlotow¹ córkê. Powinieneœ mnie jej przedstawiæ.}
{4120}{}{Miria, s³odziutka, naprawdê powinniœmy spêdziæ trochê czasu sam na sam.}
{4121}{}{Zgadujê, ¿e Miri¹ bêdziemy siê zajmowaæ na zmianê, co?}
{4122}{}{[Puszcza oczko do Mirii.]}
{4123}{}{[Uœmiecha siê do Mirii.]}
{4124}{}{Mirio, potrzebujesz mê¿czyzny twojej klasy. No wiesz, takiego jak ja.}
{4125}{}{[Wywija no¿em w stronê Mirii. Uœmiecha siê.]}
{4130}{}{Mam pomys³ zastrzelmy Davina i wrzuæmy go do rowu.}
{4131}{}{Za³ó¿my, czysto hipotetycznie, ¿e Davin dziwnym trafem bêdzie mia³ rano poderzniête gard³o. Nikomu go nie bêdzie szkoda, prawda?}
{4140}{}{Hej Cassidy, powinieneœ spróbowaæ Psycho. S³ysza³em, ¿e nawet w³osy od tego odrastaj¹.}
{4141}{}{Hej, Cassidy czemu nie chlejesz wiêcej tej swojej wódy? Wygl¹da, ¿e ³adnie ciê postarzy³a.}
{4142}{}{To ¿a³osne kiedy ktoœ tak stary jak Cassidy, tak kurczowo trzyma siê ¿ycia. Gdybym to ja by³ na jego miejscu, ju¿ dawno poca³owa³bym lufê strzelby i skoñczy³ z sob¹.}
{4150}{}{Porzuæmy te chodz¹ce zw³oki.}
{4151}{}{Dobra, chyba ten kawa³ z zabraniem Lennego trwa ju¿ za d³ugo, nie s¹dzisz?}
{4152}{}{Jak do cholery mam podrywaæ panienki kiedy Lenny wszêdzie za nami ³azi?}
{4160}{}{A wiêc, Marcus kiedy zmieni³eœ siê w przyjaŸnie nastawionego fizycznego?}
{4161}{}{Hej Marcus, nie masz czasem jakiegoœ miasta, którym masz zarz¹dzaæ, czy coœ?}
{4170}{}{Myron trzymaj siê, jestem pewny, ¿e któregoœ dnia twoje j¹dra siê st¹pi¹.}
{4171}{}{G³¹b chyba karykaturuje mój styl.}
{4172}{}{Myron jest jak jeden wielki pryszcz, tylko czeka ¿eby daæ mu wycisk.}
{4180}{}{Przynajmniej Goris jest na tyle przyzwoity ¿eby siê zakryæ.}
{4181}{}{Œwietne przebranie, Goris, brawo. Wygl¹dasz jak typowy garbaty dziwol¹g.}
{4200}{}{A¿ jestem ciekaw, jakie s¹ te wioskowe dziewczyny.}
{4210}{}{Dziwki... wszêdzie dziwki. Ju¿ mi siê tu podoba.}
{4220}{}{To miejsce siê po prostu domaga odrobiny chaosu.}
{4230}{}{Za du¿o tu policji. Wed³ug mnie czas siê st¹d ulotniæ.}
{4240}{}{Œwietnie, wiêcej dziwade³. Lepiej tu nie zostawaæ d³u¿ej ni¿ trzeba.}
{4250}{}{Marnujemy tu czas. Kobiety Zombi mnie nie krêc¹. Generalnie to nie lubiê dziewczyn, które wygl¹daj¹ na martwe ZANIM z nimi zacznê.}
{4260}{}{Serio. Po co do jasnej cholery w ogóle marnujemy tu czas?}
{4270}{}{Nie s¹dzê ¿ebym z w³asnej woli chcia³ marnowaæ wiêcej mojego czasu w tej placówce.}
{5000}{}{[He snaps his head towards you and leaps to his feet. As he looks at you, his eyes suddenly get really wide and he starts gasping for air.]}
{5001}{}{[KONIEC]}
{5002}{}{O cholera!}
