{100}{}{Widzisz Hologram.}
{101}{}{Widzisz Dyrektora do spraw Ochrony.}
{102}{}{Hologram 10001. Nadzoruje ochronę AOŚ.}
{200}{}{Stać! Nie próbuj się zbliżyć. Zidentyfikuj się intruzie.}
{201}{}{Jestem Dzieckiem Przeznaczenia z Arroyo. Zwiedzam AOŚ.}
{202}{}{Nie jestem intruzem i teraz muszę już iść.}
{203}{}{Jestem }
{204}{}{, nie chcę przeszkadzać, tylko zwiedzam.}
{210}{}{Zwiedzasz!? Zwiedzasz...MOJĄ...AOŚ!? Jak śmiesz mieć czelność włamywać się tu i łazić ot tak sobie! Vollidiot! Mam ochotę cię aresztować i wrzucić twoje dupsko do naszego zoo, byłaby z ciebie prawdziwa uczta dla naszych dziwadeł!}
{211}{}{Nie, czekaj! Nic złego nie robię! Pozwól mi wyjaśnić...}
{220}{}{Nigdzie się nie wybierasz, Pisskopf. Nikt nie będzie właził do mojej AOŚ bez uzasadnienia. Skąd mam wiedzieć, że nie jesteś chińskim szpiegiem?}
{221}{}{Zgaduje, że nie wiesz. Ale jeśli dasz mi szansę się wytłumaczyć, może uda nam się rozwiązać ten mały problem?}
{222}{}{A co jeżeli nawet jestem? Czy to ma jakieś znaczenie? Twoja cena AOŚ już się nie liczy. Jest tylko kolejnym rozsypującym się reliktem utraconej epoki.}
{230}{}{No dobra, Schwachkopf, wytłumacz się. Ale dobrze ci radzę, postaraj się, bo inaczej dostaniesz bęcki od moich robotów, a potem zaciągną cię na dół wprost na krzesło elektryczne!}
{231}{}{Dobra. Po pierwsze, nie jestem chińskim szpiegiem, jestem, jak mógłbyś to określić, dzikusem. wybrano mnie do niezwykle trudnego zadania, uratowania mojej wioski od zagłady. Szukam tu tylko czegoś co mogłoby mi pomóc w mojej misji.}
{232}{}{Odpieprz się! Jesteś HOLOGRAMEM. Najgorsze co możesz mi zrobić to zakrzyczeć mnie na śmierć, czego już próbowałeś. A co do tych kawałków złomu które nazywasz robotami, byłoby to może bardziej zastraszające gdyby jakieś działały.}
{240}{}{Odzyskać! Ty Pissnelke! Jak śmiesz ubliżać tak tej instytucji! Nikt nie zabierze stąd nawet kawałka papieru bez mojego pozwolenia! Ale, dostanie się tak daleko w głąb AOŚ wymaga niemałych umiejętności... może znalazłbym dla ciebie... zastosowanie.}
{241}{}{Hę?}
{242}{}{Nie, dzięki, poszperam jeszcze trochę i sobie pójdę. Cześć!}
{250}{}{Jak śmiesz! Taka obraza ze strony Blödes Arschloch. Kiedy zaczynałem mój trening, brak kultury był karany. I byliśmy karani! Zapamiętaj moje słowa scheisskopf, ten twój cięty język któregoś dnia sprowadzi na ciebie śmierć.}
{251}{}{Być może, być może. Ale jeśli ten dzień w ogóle przyjdzie, zajmę się tym wtedy i tam. Pewne jest to, że nie ty mi ją zadasz. Jesteś nikim. Nie masz już czym rządzić, dlatego zasłaniasz swój smutek gniewem. Od jak dawna roboty nie odpowiadają?}
{260}{}{Cóż, jak się już pewnie domyśliłeś, roboty w AOŚ już nie działają. Komputery już nie rejestrują moich słownych rozkazów, a że nie mam ciała, nie mogę posłużyć się konsolą. Ja... Już nie jestem w stanie niczego bronić. Proszę, napraw dla mnie komputer? Muszę kierować robotami bo... bo tak.}
{261}{}{Cóż, czemu nie? Zobaczę co da się zrobić.}
{262}{}{Nie, nie mam na to czasu. Cześć.}
{270}{}{Fick dich du verdammter Arschficker! Zostaje mi tylko... tylko... [Wzdycha.] Masz rację. Roboty już nie rozumieją, co do nich mówię. Tylko siedzą tak bez ruchu. Komputery przestały działać, a jako Hologram, nie mogę dotknąć klawiatury. Jak już mówiłem od wielu lat, to miejsce wymaga remontu i przebudowy. Może kiedyś będę miał moc, aby to zrobić.}
{271}{}{Może dam radę ci pomóc? Nieźle sobie radzę z komputerami.}
{280}{}{Dziękuję. Jeśli uda ci się naprawić komputer sterowania robotami, dam ci dostęp do dobrze zabezpieczonego skrzydła na poziomie czerwonym. Możesz wziąć co chcesz z magazynów. Obawiam się, że nie będę miał już z tego pożytku.}
{281}{}{Dzięki. Wrócę jak skończę.}
{290}{}{Lech mich! Nie mam ci nic do powiedzenia.}
{291}{}{Dobra.}
{300}{}{Udało ci się ukończyć zadanie? [W oczach błysk nadziei.]}
{301}{}{Nie, jeszcze nie. Jeszcze nad tym pracuję.}
{310}{}{Czy komputery znowu działają?}
{311}{}{Tak. Udało mi się je dla ciebie naprawić. Znów możesz wydawać polecenia robotom.}
{320}{}{Doskonale! Wspaniale! Teraz mogę zmiażdżyć tych głupców! AOŚ znów będzie oczyszczone! Dobrze, a teraz mam tu coś dla ciebie. [Mówi do robotów.] Dawaj tu swoje opancerzone metalowe dupsko i daj temu cywilowi nagrodę za zasługi dla tego wspaniałego narodu! [Robot podjeżdża do ciebie i wyciąga kartę klucz. Kiedy ją odbierasz, wyjeżdża z pokoju. Z jakiegoś powodu, odnosisz wrażenie, że byłoby lepiej dla robotów gdyby ich nie aktywować.] A teraz ruszaj w swoją stronę. Odmaszerować!}
{321}{}{Dziękuję.}
{322}{}{Odmaszerować? A co ja, strażnik? Na razie, staruszku.}
{330}{}{Zostaw mnie w spokoju!}
{331}{}{Nic więcej od ciebie nie chcę.}
{332}{}{MACH ES DIR SELBER!!}
{333}{}{Jestem teraz zajęty.}
{334}{}{Przyjdź później.}
{335}{}{Nie widzisz, że jestem na konferencji?}
{336}{}{Musimy zniszczyć to miejsce, natychmiast!}
{337}{}{To absurd!}
{338}{}{Nigdy!}
{339}{}{Tylko po zniszczeniu starego, nowe może się odrodzić.}
{340}{}{Kto jest za?}
{341}{}{Roboty muszą zostać reaktywowane!}
{342}{}{Warmduschery! Wszyscy!}
{343}{}{Nasze systemy obronne wymagają uzupełnienia amunicji!}
{344}{}{Gdybym to ja tu rządził, wszystko wyglądałoby inaczej!}
{345}{}{Halt die Schnauze!}
{400}{}{Aresztować mnie? Jesteś hologramem. Nie możesz mnie nawet dotknąć.}
{401}{}{Widzę, ze mam tu Klugscheißerga! Myślisz, że nie mogę nakopać do dupy takiemu Warmduscherowi ja ty? No, może ja nie mogę, ale po to są tu te roboty! Na prawdę szybko kończy mi się cierpliwość. Więc lepiej zacznij się tłumaczyć. Skąd mam wiedzieć, że nie jesteś chińskim szpiegiem?}
{410}{}{To tobie zawdzięczam działanie komputera kontroli robotów?}
{411}{}{Dokładnie.}
{412}{}{Uch... może.}
{413}{}{Nie. To nie ja.}
{420}{}{Quatsch! Jesteś tutaj jedyną istotą rozumną z krwi i kości, więc jestem pewien, że to ty.}
{421}{}{Dobra, w porządku, to ja.}
