{100}{}{Widzisz Hologram.}
{101}{}{Widzisz Dyrektora Operacyjnego.}
{102}{}{Hologram 12001. Zarządza operacjami wewnętrznymi AOŚ.}
{200}{}{[Ten cwaniacko wyglądający hologram obdarza cię nerwowym uśmiechem.] Dzień dobry, witamy w AOŚ. Z pewnością zwróciło twoją uwagę iż przechodzimy właśnie pewne trudności, ale przekroczymy ten most kiedy już do niego dotrzemy.}
{201}{}{Uch, dobra. Kim jesteś?}
{210}{}{Jestem Dyrektorem Operacyjnym AOŚ.}
{211}{}{A, tak. [Drapiesz się w głowę] A co to właściwie oznacza?}
{220}{}{[Z trudem powstrzymuje śmiech.] Ależ, zajmuję się koordynacją działań. Sprawiam, że piłka się toczy. Teraz jest po twojej stronie boiska. Lubię wyciągać z ludzi najlepsze. W końcu, tu w AOŚ o to chodzi. Uczciwość. Prawość. Dziękuję, cenimy twoją opinię.}
{221}{}{O czym u diabła mówisz?}
{230}{}{Zapewniam cię, pracujemy bez wytchnienia, by rozwiązać wszystkie problemy. Zdarzały nam się potknięcia, ale wszystko idzie w dobrym kierunku. Jestem pewien, że wszystkie normy zostaną osiągnięte w danym czasie.}
{231}{}{Jakie normy? Gadasz bez sensu. Czy ty w ogóle coś tu robisz? Możesz mi pomóc, czy nie?}
{240}{}{Wszystko zależy od twoich oczekiwań. Mam związane ręce w tej kwestii, ale z przyjemnością ci pomogę, jeśli możesz.}
{241}{}{Zapomnij, na razie.}
{242}{}{Przykro mi, że nie mogłem być bardziej pomocny.}
{243}{}{Dziękuję za twój czas.}
{244}{}{Lepiej tego nie komentować.}
{245}{}{Bez komentarza.}
{246}{}{A ja tak, ale nie mam do tego władzy.}
{247}{}{Zajmiemy się tym zagadnieniem kiedy do tego przyjdzie.}
{248}{}{Spotkaliśmy się, by dyskutować, a nie działać.}
{249}{}{Jestem przekonany, że AOŚ jest na drodze do sukcesu.}
{250}{}{Istotność tego zagadnienia jest sporna.}
{251}{}{Nie śpieszmy się tak, działamy za szybko.}
{252}{}{To brzmi adekwatnie.}
{253}{}{Rozumiem twoje obawy.}
