{100}{}{To miało być tak... Tak myślę.}
{101}{}{Nie, nie może... Ja, cóż...hmmm...}
{102}{}{Niebieski przewód do czerwonego gniazdka...}
{103}{}{Te mutacje ładnie postępują.}
{104}{}{To już długo nie potrwa.}
{105}{}{Jeszcze tylko kilka kropli HCl...}
{106}{}{Widzisz mężczyznę w białym, laboratoryjnym kitlu.}
{107}{}{Widzisz Doktora.}
{108}{}{Głównego i jedynego Doktora pozostałego w AOŚ.}
{109}{}{Niemądrze byłoby mnie atakować.}
{120}{}{Tak?}
{121}{}{Cześć, mam na imię }
{122}{}{. Kim ty jesteś?}
{123}{}{Przepraszam, że przeszkadzam. Do widzenia.}
{130}{}{Jestem znany jako Doktor.}
{131}{}{Dobra, ale co tu robisz? Czemu jesteś tu sam? Reszta tego miejsca wygląda na opuszczoną.}
{132}{}{Dobra, dzięki.}
{140}{}{Wyglądasz na kogoś, kto wie coś o nauce. Może będziesz w stanie zrozumieć co Ja tu robię. Co chcesz wiedzieć?}
{141}{}{Dlaczego tu jesteś?}
{142}{}{Czym się tutaj zajmujesz?}
{150}{}{Przykro mi, ale nie masz potrzebnej wiedzy, aby zrozumieć moją rolę tutaj. Wróć jak się doszkolisz.}
{151}{}{Hej, czekaj. O czym ty mówisz, zrozumiem wszystko co mi powiesz!}
{152}{}{Cóż, w porządku. Do widzenia.}
{160}{}{Jestem członkiem grupy naukowców, którzy pracowali tu przed wojną. Niestety, żaden z nich nie był dostatecznie wykształcony, ani uzdolniony i musieli wszyscy odejść. Zostałem tylko ja.}
{161}{}{I co, jesteś zadowolony z tego? To znaczy z tego, że zostałeś tu sam?}
{170}{}{Nie przeszkadza mi to. Obecnie zajmuję się wieloma badaniami genetycznymi na okazach, które stworzyłem w celu obserwowania działania wirusa FEV na ich system odpornościowy. Lata temu stworzyłem wiele narkotyków i udoskonaliłem kilka już znanych, ale teraz już się tym nie zajmuję.}
{171}{}{A co z potworami, które stworzyłeś?}
{172}{}{Jakie narkotyki stworzyłeś?}
{180}{}{Nie, nie zrozumiesz. Po prostu nie masz wystarczającej wiedzy naukowej na temat biologicznych udoskonaleń. A teraz przepraszam, ale marnujesz mój czas.}
{181}{}{Poradzę sobie. Sprawdź mnie.}
{190}{}{[Uśmiecha się.] Cóż, kto wie. Dobrze, skoro nalegasz, dam ci szansę. Co chcesz wiedzieć?}
{191}{}{Dlaczego tu jesteś?}
{192}{}{Czym się tutaj zajmujesz?}
{200}{}{Oczywiście! Nikt nade mną nie stoi. Żadnych zasad. Robię co chce i kiedy chcę. Poza tym będąc tu sam, mam dostęp do całego sprzęty jakiego potrzebuję bez żadnych ograniczeń. Coś jeszcze?}
{201}{}{Kim są ci ludzie w klatkach?}
{202}{}{Co to za śmieszny kolorowy płyn, który można znaleźć wszędzie w AOŚ?}
{203}{}{Skąd masz cały ten sprzęt?}
{210}{}{W tych pierwszy klatkach pod tamtą ścianą są wieśniacy, którzy trafili tu przypadkiem, złapałem ich do późniejszych eksperymentów. Ci silniejsi to moi wojownicy na wypadek gdybym potrzebował... ochrony.}
{211}{}{...późniejszych eksperymentów?  Co masz na myśli?}
{212}{}{Dzięki. Mogę ci zadać następne pytanie?}
{213}{}{Jasne. Dzięki. Muszę już iść.}
{220}{}{Różne chemikalia i zbiorniki z FEV. Wszystko to zostało zamknięte w wielkich beczkach i magazynowane tu w AOŚ. Niestety, zdarzył się mały wypadek, wyciek chemikaliów zmusił wszystkich do opuszczenia tego miejsca, wszystkich oprócz Hologramów. Część tych środków chemicznych przedostała się do niższych poziomów. Używam ich jako materiału do eksperymentów. Jak do tej pory, udało mi się uzyskać pewne obiecujące rezultaty!}
{221}{}{Jakie rezultaty?  Masz na myśli te stwory?}
{222}{}{A skąd bierzesz potrzebny sprzęt?}
{230}{}{Głównie stąd. AOŚ zostało wyposażone w pełny zakres potrzebnych urządzeń, a skoro większość naukowców opuściła to miejsce, spora część tego sprzętu nie została nigdy użyta. Jednak po tych wszystkich latach niektóre rzeczy zaczynają się kończyć...}
{231}{}{Nieważne. Muszę już iść.}
{240}{}{Narkotyki? Całe tuziny! Przez te lata stworzyłem mentaty, wygrzew, stimpaki, zestawy medyczne o różnej zawartości, psycho i wiele innych, których nie jesteś sobie w stanie nawet wyobrazić. Ale już tego nie robię, stworzyłem Pana Małego Chemika! teraz on się tym zajmuje. Jest w głównym budynku. Jeżeli masz tyle inteligencji i wiedzy naukowej ile mówisz, że masz to możesz z niego skorzystać do zrobienia dowolnej ilości narkotyków i lekarstw.}
{241}{}{Jakie narkotyki specjalne zrobiłeś?}
{242}{}{Gdzie mogę znaleźć tego robota, Pana Małego Chemika!?}
{243}{}{Dzięki. A słyszałeś już o Jetcie?}
{250}{}{Tak, stworzyłem wiele potworów odkąd jestem w AOŚ. Jeżeli jesteś typem odkrywcy to na pewno zdarzyło ci się już na nie trafić. Centaury?  Wisielce? "Obcy"? Włóczą się po pustkowiach. Tutaj zatrzymałem tylko kilka okazów na później.}
{251}{}{Chwileczkę. Mówisz że te wszystkie potwory, które buszują na pustkowiach, które mordują niewinnych ludzi są twoim dziełem?!}
{252}{}{O cholera, zapamiętać: nie denerwować Doktora. Do widzenia.}
{260}{}{'Co masz na myśli?'  Oczywiście FEV - wirusa wymuszonej ewolucji! Dopiero zaczynam eksperymenty z ludźmi. Wszyscy słyszeliśmy historie o Mistrzu. I pomyślałem, żeby zrobić coś podobnego. Własna armia na pewno, by mi się przydała!}
{261}{}{Nie sądzisz, że to ździebko niemoralne? Jak w ogóle mogło ci to przyjść do głowy?}
{262}{}{Dopiero zaczynasz z ludźmi? To co robiłeś do tej pory?}
{263}{}{Cóż, powodzenia. Muszę już iść.}
{270}{}{Tak, chyba mogę cię puścić. To było nawet zabawne. Co jeszcze mogę powiedzieć? }
{271}{}{Opowiedz mi jeszcze raz o tych ludziach.}
{272}{}{Co to za dziwne fosforyzujące substancje?}
{273}{}{Skąd masz potrzebny do eksperymentów sprzęt i środki do badań?}
{280}{}{Nie, nie, nie. Zanim odejdziesz, muszę cię o coś zapytać. Wyświadczysz mi pewną przysługę? Nie opuszczam magazynu z obawy o kradzież. Potrzebuje trochę świeżego materiału. Możesz mi pomóc?}
{281}{}{Ta. Myślę, że tak.  Czego potrzebujesz?}
{282}{}{Nie, mam za dużo do zrobienia. Może innym razem.}
{290}{}{Tak, byłem ciekaw co wirus zrobi ze zwykłymi zwierzętami domowymi sprzed wojny, które zachowaliśmy w naszych magazynach. Nie przewidziałem, że wirus tak przyśpieszy ich rozmnażanie. Więc wkrótce po tym jak to zaważyłem, wypuściłem je na pustkowia.}
{291}{}{Jesteś potworem! Nic dziwnego, że nikt w okolicy nic o tobie nie wie! Najwyższy czas się ciebie pozbyć.}
{292}{}{Cóż, nie zgadzam się z tym co tutaj robisz, ale nic na to nie poradzę. Do widzenia.}
{300}{}{Specjalne, mówisz?  Cóż, staram się wyhodować nową odmianę marihuany. To przedwojenny narkotyk, który przeleżał zamrożony w magazynie. Ale mam tu tylko nawóz od zmutowanych stworów, które tu widzisz, więc okazało się to bardziej niebezpieczne niż myślałem na początku. Zresztą i tak pierwsze próby nie były zbyt udane...}
{301}{}{Mogę je dostać?}
{302}{}{Czemu nie były udane? Co się stało?}
{310}{}{Pan Mały Chemik! znajduje się w północno-wschodniej części najniższego piętra ośrodka. A może w północno-zachodniej... Właściwie to jest na najwyższym piętrze. Już nie pamiętam. To kawał maszyny, na pewno go nie przeoczysz.}
{311}{}{Jasne. Dzięki. Wspominałeś coś o specjalnych narkotykach. Jakie na przykład?}
{320}{}{Spokojnie. Jestem naukowcem. To moja praca. Eksperymenty to moje życie. Może trochę inny, ale to po prostu kolejny eksperyment.}
{321}{}{Zabawiasz się rzeczami, których nie powinieneś ruszać! Co, jak coś pójdzie nie tak? Co, jeśli któraś z osób, na których prowadzisz swoje eksperymenty umrze!?}
{330}{}{Pozbyć się mnie! O, nie. Nie sądzę. Wykonuję swoją pracę - to wszystko. Badania i eksperymenty. Z czasem po prostu kończą się rzeczy do zbadania, więc musisz wymyślić coś nowego. Myślę, że to nazywają 'nieszablonowym myśleniem'.}
{331}{}{Mam tego dość! Jeżeli nikt inny cię nie powstrzyma, ja to zrobię.}
{332}{}{Jesteś stuknięty, idę stąd. Do widzenia.}
{340}{}{Ta, czemu nie? Nie krępuj się i bierz. W magazynach na powierzchni jest tego pełno. Myślę nawet, że zaprogramowałem do wytwarzania tego Pana Małego Chemika! Tu już ich nie trzymam, zajmowały za dużo miejsca.}
{341}{}{Dzięki! Mówiłeś coś wcześniej, że pierwsze próby były nieudane? Co się stało?}
{350}{}{Cóż, kilka najbardziej obiecujących obiektów miało pewne objawy działania wirusa, ale nie warto nawet o nich wspominać. W tym fachu błędy czasem się zdarzają. A teraz wybacz, ale mam dużo do zrobienia.}
{351}{}{Dobra, ja chyba też. Do widzenia.}
{360}{}{To umierają, trudno. Co ja mam na to poradzić? Niezbędne ofiary postępu.}
{361}{}{Potworne! Niewiarygodne! Zginiesz - teraz!}
{362}{}{Nie zniosę tego dłużej. Żegnaj. Nieprędko tu wrócę.}
{370}{}{Jet? Ta, o ile się nie mylę to narkotyk, na którym jedzie całe Ridding. To wyjątkowo złożona mieszanka, moja maszyna nawet na maksymalnej mocy nie mogła jej odtworzyć. Co wiesz o tym narkotyku?}
{371}{}{Cóż, jest ze mną jego twórca.}
{380}{}{[*Błysk w oczach*] Naprawdę!? Kto? Mogę się z nim zobaczyć? Porozmawiać z nim?}
{381}{}{Oczywiście. Nazywa się Myron. Jest tutaj.}
{390}{}{Dzięki ci za przyprowadzenie tu tego dzieciaka Myrona. Ma naprawdę ogromną wiedzę! Co prawda, nie jest tak inteligentny jak ja, ale i tak jest niezły. Gdyby chciał gdzieś zostać na dłużej, chętnie wezmę go na swojego ucznia.}
{391}{}{Wątpię, żeby chciał być czyimkolwiek uczniem. Lepiej już pójdziemy.}
{400}{}{Chwileczkę, zanim odejdziesz. Proszę przyjmij to jako wyraz mojej wdzięczności za przyprowadzenie do mnie Myrona. Mi to tutaj i tak się nie przyda.}
{401}{}{Hej, dzięki. Co to jest?}
{410}{}{To słoneczny spopielacz. Jeden z moich eksperymentów. Zasilany jest energią słoneczną, czyli nie wymaga żadnej amunicji. Myślę, że na pustkowiach będzie bardzo przydatny, ale w związku z tym mam do ciebie jeszcze jedną prośbę...}
{411}{}{Co to takiego?}
{420}{}{Wygląda, że dużo podróżujesz. Ja jestem ograniczony do terenu AOŚ, muszę mieć oko na moje eksperymenty, a potrzebuję pewnych rzeczy, które mi się skończyły. Może udałoby ci się je dla mnie zebrać?}
{421}{}{Ta. Myślę, że tak.  Czego potrzebujesz?}
{422}{}{Nie, muszę uratować moją wioskę. Może innym razem.}
{430}{}{Nie miałem jeszcze okazji zbadać złotego gekona. Potrzebuję trochę materiału do badań. Zbierz 10 skór złotego gekona i przynieś je tutaj? Na pewno znajdę tu coś godnego twojego trudu.}
{431}{}{Nie ma problemu. Wrócę jak tylko je zbiorę.}
{432}{}{Mam je ze sobą.}
{440}{}{[Patrzy na ciebie.] Co?}
{441}{}{Yyy witaj ponownie, możesz mi jeszcze raz powiedzieć kim jesteś.}
{450}{}{To znowu ty? Czego chcesz tym razem?}
{451}{}{Co tutaj robisz? To miejsce przypomina miasto duchów.}
{460}{}{Jeżeli nie chcesz mi pomóc, to przynajmniej zostaw mnie w pokoju. A może jednak jesteś tu, aby mi pomóc?}
{461}{}{Tak. Co trzeba zrobić?}
{462}{}{Nie, ale jak tylko załatwię swoje sprawy, wrócę żeby ci pomóc.}
{470}{}{Witaj. Przeszło ci?}
{471}{}{Nie, jestem tu żeby cię zabić. Świat nie potrzebuje takich jak ty.}
{472}{}{Ta, chyba tak. Muszę cię o coś zapytać.}
{480}{}{Czego chcesz? Wiesz, że muszę pilnować moich eksperymentów!}
{481}{}{Opowiedz mi o narkotykach jakie tu robiłeś.}
{482}{}{Opowiedz mi jeszcze raz o tych ludziach.}
{483}{}{Szukam pracy. Masz coś?}
{484}{}{Skąd masz sprzęt?}
{490}{}{Masz te skóry, o które cię prosiłem?}
{491}{}{Tak, oto on.}
{492}{}{Nie, jeszcze nie.}
{500}{}{Cudownie! Wyśmienicie! Niech no zobaczę...aaa tak, nadają się! A teraz, zrobisz jeszcze coś dla mnie?}
{501}{}{Tak, jeśli masz jeszcze coś.}
{502}{}{Nie teraz. Cześć.}
{510}{}{Dobrze, więc słuchaj. Mimo, że większość badań prowadzę w magazynach, to od czasu do czasu muszę wejść do głównego budynku. Ale jest tam problem z oświetleniem. Napraw je dla mnie, abym mógł wejść do budynku AOŚ.}
{511}{}{Nie ma sprawy.}
{512}{}{Nie mam teraz na to czasu.}
{513}{}{Już zrobione! Na tablicy z bezpiecznikami było trochę luźnych kabli więc...}
{520}{}{Pokonując moich wojowników, udało ci się dowieść swojej wartości. Proponuję ci pracę dla mnie.}
{521}{}{Co!? Praca dla ciebie!? I co ja niby mam robić?}
{522}{}{Dzięki, ale nie. Do widzenia.}
{530}{}{Oświetlenie naprawione?}
{531}{}{Tak, tak, tak, nie muszę znać szczegółów. Dziękuję. Ale mam jeszcze jedno zadanie dla ciebie.}
{532}{}{Co to takiego?}
{533}{}{Nie, wciąż nad tym pracuję.}
{540}{}{Eksperymentuję z serum mającym zwiększać zręczność i spostrzegawczość ludzi, aby pomóc im przeżyć w dzisiejszym brutalnym świecie. Pozwolisz, że przetestuję je na tobie?}
{541}{}{Cóż...chyba tak, w końcu co złego może się stać?}
{550}{}{Nawet sobie nie wyobrażasz...yyy to znaczy jakby poszło coś nie tak... A teraz nie ruszaj się przez chwilę, to nie będzie bolało! Chyba.}
{551}{}{Coo! Czekaj...}
{560}{}{No, i po wszystkim! Witaj ponownie w świecie żywych! Jak się czujesz?}
{561}{}{Uhh, dobrze, czemu pytasz?}
{570}{}{Zgasło ci światło na kilka godzin, ale już wszystko w porządku. Czujniki wykazują, zwiększenie czujności i zmniejszenie twojego czasu reakcji.}
{571}{}{Super! Dziękuję, Doktorze.}
{580}{}{Żaden problem. Daj znać gdyby było ci coś potrzebne.}
{581}{}{Tak zrobię. Do widzenia.}
{590}{}{Pomożesz mi wreszcie czy nie?}
{591}{}{Tak pomogę ci. Wrócę jak przywrócę zasilanie.}
{592}{}{Nie.}
{600}{}{Przepraszam, ale w tej chwili nie mogę dla ciebie nic więcej zrobić. Nie mam też już żadnych zadań. Dzięki za twoją pomoc.}
{601}{}{W takim razie żegnaj.}
{602}{}{Tak, było trochę luźnych przewodów, no i trzeba też było...}
{603}{}{NIE! Co robisz?}
{700}{}{Czekaj, czekaj! Jesteś częścią oryginalnego personelu?! Ale, musiałbyś mieć co najmniej 200 lat!}
{701}{}{W pewnym sensie, to prawda. Urodziłem się dokładnie 202 lata temu. Oczywiście, nie mógłbym tak długo żyć w "normalny" sposób.}
{702}{}{Mów dalej. Słucham.}
{703}{}{Kiedy wybuchła wojna, ja, tak samo jak i pozostali naukowcy zostaliśmy zamrożeni w komorach kriogenicznych. Przekazaliśmy kontrolę nad ośrodkiem w ręce Hologramów i robotów, a później weszliśmy do hibernatorów, żeby przetrwać w ten sposób najgorsze.}
{704}{}{Ale, wojna zakończyła się wiele lat temu.}
{705}{}{To prawda. Zostaliśmy odmrożeni 90 lat temu, tylko po to żeby zobaczyć jak to miejsce zostało zdewastowane. Większość naukowców wróciła do swoich przerwanych badań, po prostu nie wiedząc co robić.}
{706}{}{[KONTYNUUJ]}
{707}{}{Nie mogłem uwierzyć w ich naukową krótkowzroczność... w ich rażący brak wyobraźni! A przecież nadarzyła się okazja do zrobienia rzeczy niezwykłych. Mieliśmy szansę uczynić świat według naszego pomysłu. To smutne, ale moi koledzy zapłacili za swój brak wizji...}
{708}{}{Zabiłeś ich!?}
{709}{}{To zrozumiałe.}
{710}{}{Proszę kontynuuj.}
{711}{}{Nie, ja ich nie zabiłem. Ale nie mogłem też pozwolić, aby przeszkadzali w moich badania. Ja tylko tak ustawiłem pewne wydarzenia, że zdecydowali się odejść.}
{712}{}{Dobra, to wyjaśnia część tej historii. Ale ciągle coś mi tu brakuje...}
{713}{}{A, tak. Przepraszam za to. Czasami mój umysł zmienia kierunek myślenia, albo po prostu błądzi. Naprawdę wspaniałe umysły, wiesz? W każdym razie, nadal korzystałem ze zbiornika, ale nieco go zmodyfikowałem.}
{714}{}{Jakie to były modyfikacje?}
{715}{}{To mi wystarczy. Do widzenia.}
{716}{}{Cóż, za pierwszym razem kiedy weszliśmy do komór kriogenicznych, to było tak jakbym poszedł spać i się obudził. Ale później, zdałem sobie sprawę, że to była strata czasu. Więc ustawiłem komorę tak, aby móc z niej korzystać latami, ale zachowując przytomność! Wykorzystuję ten czas na przemyślenie prowadzonych eksperymentów i obmyślanie nowych tematów. W ten sposób mam możliwość oglądać wyniki moich długoterminowych badań.}
{717}{}{A czy nie przyszło ci do głowy, że korzystanie w ten sposób z komór może być szkodliwe?}
{718}{}{Bzdura! Jeżeli już coś, to nawet czuję się lepiej. Dzięki okresom mojej pozornej hibernacji widzę rzeczy jaśniej, rozumiem je lepiej.}
{719}{}{Jesteś obłąkany! Żegnaj.}
{720}{}{To faktycznie wspaniały pomysł. Jesteś geniuszem! Hej, mogę zerknąć na tę komorę kriogeniczną?}
{721}{}{Rozumiem. Powiedz mi jeszcze o czymś innym.}
{722}{}{Oczywiście, jest tam. Kazałem ją przenieść tutaj już jakiś czas temu. Trzymanie jej na podziemnych poziomach nie byłoby rozsądne.}
{723}{}{Interesujące. Jak to działa?}
{724}{}{Oczywiście naukowe podstawy hibernacji są bardzo skomplikowane. Ale komorą można sterować za pomocą komputera przy użyciu dość prostego interfejsu. [Poświęca kilka minut, żeby pokazać ci jak to działa.]}
{725}{}{Dziękuję za informację, Doktorze. Ale ciągle mam parę pytań.}
{726}{}{Dziękuję za informację, Doktorze. Kto wie, kiedy taka wiedza może się przydać? Do widzenia.}
{727}{}{Dobra, koniec czczego gadania. Muszę już iść. Do widzenia, Doktorze.}
{728}{}{Nie, tak być nie mogło, nie mogli tu zostać i wtrącać się do moich eksperymentów...nie mogli... [Spojrzenie doktora utkwiło gdzieś poza tobą, pogrążył się w swoich myślach.]}
{729}{}{Wiesz co, jesteś pokręcony. Czas pokazać ci jak JA eksperymentuję na ludziach. Czas umierać.}
{730}{}{I co, taka sytuacja ci odpowiada? Mam na myśli to, że zostałeś tu sam?}
{731}{}{Co jeszcze chcesz usłyszeć?}
{800}{}{Właściwie, poczekaj chwilę. Wyglądasz na poszukiwacza przygód. Twoje umiejętności mogą mi się przydać.}
{801}{}{Jasne. Czego potrzebujesz?}
{802}{}{Dzięki, ale nie. Do widzenia.}
{803}{}{Dobrze, zbierałem próbki na jednym z moich miejsc i wygląda na to, że zapomniałem jednego z moich narzędzi. Normalnie sam bym to załatwił, ale jestem w tej chwili bardzo zajęty, a w dodatku nie pamiętam gdzie je zostawiłem. W każdym razie, idąc na północny-zachód od tego budynku trafisz do miejsca, w którym zostało. Dla ciebie to powinno być łatwe zadanie.}
{804}{}{Przyniosę je.}
{805}{}{Nie interesuje mnie to. Cześć.}
{806}{}{Czekaj. Na pewno nie chcesz mi wyświadczyć drobnej przysłógi?}
{810}{}{Wyśmienicie! A teraz muszę wracać do pracy. [Do siebie.] Wszystko idzie zgodnie z planem.}
{811}{}{[dalej]}
{820}{}{Trudno. Cóż, muszę wracać do pracy. [Do siebie.] Prawie cię miałem. Gdzie ja teraz znajdę następny obiekt do badań.}
{821}{}{[dalej]}
{830}{}{[Wygląda na zaskoczonego.] Co do ...?!}
{831}{}{Ciągle szukam.}
{832}{}{Proszę, zgubione narzędzie. Faktycznie łatwizna.}
{833}{}{Co to miało być, chciałeś mnie zabić? To był labirynt pełen zmutowanych potworów. To nie była zwykła prośba odzyskania zguby, prawda?}
{840}{}{Co?! Oddaj mi to! [Wyrywa ci z ręki znalezione przez ciebie narzędzie.] Jak ci się udało..., a z resztą nieistotne. Trzeba będzie nad tym popracować...}
{841}{}{[Ignorujesz zachowanie mężczyzny.] Proszę bardzo, gdybyś jeszcze czegoś potrzebował daj mi znać. Cześć.}
{850}{}{To nie twój interes. [Wyrywa ci z ręki znalezione przez ciebie narzędzie.] A teraz wynoś się stąd. Mam coś do zrobienia. [Odwraca się od ciebie, mamrocząc coś pod nosem.]}
{851}{}{Dobra, dobra. Cześć.}
{852}{}{A więc jednak. Próbowałeś mnie zabić, więc zamierzam ci się odwdzięczyć. Przygotuj się na śmierć!}
{860}{}{Yyy, tak, oczywiście. Więc zabieraj się za to.}
{861}{}{[dalej]}
{900}{}{[Mamrocze w niezadowoleniu.]}
{901}{}{[Do siebie.] Byłem pewny, że nie wróci.}
{1000}{}{Zwracasz Doktorowi jego zapomniane narzędzie.}
