{100}{}{Przechowywanie i zarz¹dzanie danymi. Wybierz opcjê.}
{101}{}{Uruchom diagnostykê.}
{102}{}{[Zrobione]}
{103}{}{Sprawdzam... Inicjujê...Kompilujê...Dziêkujê za cierpliwoœæ podczas trwania procedury...Zakoñczone. Baza danych, sprawnoœæ 84%. Problem z po³¹czeniami p³yty g³ównej powoduje, ¿e cewki magnetyczne s¹ zasilane zbyt wysokim napiêciem. Nienaprawienie tej usterki bêdzie przyczyn¹ dalszych problemów z dzia³aniem terminalu. Sprawdzanie zakoñczone.}
{104}{}{[Zrobione]}
{105}{}{Widzisz komputer.}
{106}{}{Widzisz komputer magazynuj¹cy dane AOŒ.}
{107}{}{Widzisz komputer zapewniaj¹cy w³aœciwe i bezpieczne przechowywanie danych AOŒ.}
{108}{}{Mam ciê!}
{109}{}{Udaje ci siê rozwi¹zaæ problem cewek magnetycznych.}
{1030}{}{Sprawdzam... Inicjujê...Kompilujê...Dziêkujê za cierpliwoœæ podczas trwania procedury...Zakoñczone. Baza danych, sprawnoœæ 100%. Dziêkuje i ¿yczê mi³ego dnia. Koniec sprawdzania.}
