{100}{}{Widzisz broszurę.}
{101}{}{}
{102}{}{To jest przewodnik rozdawany na początku zwiedzania.}
{200}{}{Witam w AOŚ! Zwiedzając naszą placówkę, proszę nie przestraszyć się widoku półprzezroczystych ludzi przemierzających korytarze. To nie duchy, tylko nasz przyjazny nowy zespół hologramów! Myślcie o nich jak o programach komputerowych, obdarzonych ludzką formą dzięki magii i cudom nauki! Chętnie odpowiedzą na każde państwa pytanie, więc proszę nie wahajcie się do nich zwrócić. Uwaga! Hologramy istnieją dzięki zawieszonym kryształom z anty-grawimetrycznymi właściwościami. Przy próbach manipulacji, mogą być bardzo niestabilne, więc proszę, dla własnego bezpieczeństwa, nie dotykać hologramów. Dziękuję i życzę miłego zwiedzania!}
{201}{}{Koniec.}
{202}{}{Najpierw musisz to wyjąć z ekwipunku.}
