{200}{}{Jeśli przywiążę tu linę, będzie można tam zejść.}
{201}{}{Zdecydowanie przydałaby się lina.}
{300}{}{To powinno wystarczyć.}
{301}{}{Lina jest już tu przywiązana.}
{302}{}{Przywiązujesz linę do jednej z krat szybu wentylacyjnego i opuszczasz resztę w dół szybu. Słyszysz głuchy dźwięk, kiedy lina uderza o dno.}
{400}{}{Jesteś w jednym z szybów systemu wentylacji ośrodka AOŚ. Słyszysz przeróżne owady przemykające obok ciebie.}
