{100}{}{Widzisz mê¿czyznê o jasnych w³osach.}
{101}{}{Widzisz Davea H.}
{102}{}{Widzisz jasnow³osego mê¿czyznê z b³yskiem nadziei w oku.}
{103}{}{Dlaczego chcesz nas skrzywdziæ?}
{104}{}{Witaj, uszeregowany.}
{105}{}{Poczyniê kroki w kierunku Vikki... ee... ju¿ nied³ugo.}
{106}{}{Jak mogê ci pomóc?}
{107}{}{Czego chcesz?}
{108}{}{Da... oooch...}
{109}{}{Kim jesteœ?}
{110}{}{Czym siê tutaj zajmujesz?}
{111}{}{Vikki rozmawia³a ze mn¹. Ona i Juan naœmiewali siê z ciebie i mówili, ¿e nie jesteœ prawdziwym mê¿czyzn¹.}
{112}{}{Vikki rozmawia³a ze mn¹. Powiedzia³a, ¿e jesteœ sexy i ¿e czasami ciê pragnie.}
{113}{}{Czy mam porozmawiaæ dla ciebie z Vikki?}
{114}{}{Niewa¿ne. Czeœæ.}
{115}{}{Ummm... oookej. Niewa¿ne. S³uchaj, co tam jest?
[Gdy odwracasz wzrok, zabiera siê do swojej pracy i ignoruje ciê.]}
{116}{}{[dalej]}
{117}{}{Jestem Dave Handy. Pochodzê z Kanady.}
{118}{}{Ach tak. W takim razie czym siê tutaj zajmujesz?}
{119}{}{Co ciê tu przywiod³o?}
{120}{}{Dziêki. Na razie.}
{121}{}{Pokazujê tym ludziom jak przenosiæ ich dane, a tak¿e ca³y dzieñ odpowiadam na g³upie pytania.}
{122}{}{Czy da³byœ radê w³amaæ siê do bazy danych Shi?}
{123}{}{Jakie g³upie pytania?}
{124}{}{Có¿, mam do ciebie inne pytania.}
{125}{}{Brzmi wspaniale. Na razie.}
{126}{}{Obiecaj siê nie œmiaæ.}
{127}{}{W porz¹dku.}
{128}{}{Nie, zapomnij o tym.}
{129}{}{Rekrutuj¹ca Centrologów, Vikki Goldman. Widzia³em jeden z jej film tam, w Kanadzie i po prostu wiedzia³em, ¿e siê we mnie zakocha. Có¿, jeszcze siê to nie sta³o, ale pracujê nad tym.}
{130}{}{Zachowam to dla siebie. Mam inne pytania.}
{131}{}{Cha cha! Jaki z ciebie osio³! Ona jest gwiazd¹ porno, koleœ. Nie chce ciê.}
{132}{}{Zdajesz sobie sprawê, ¿e bêdzie udawaæ zainteresowanie tob¹, ¿eby mieæ pewnoœæ, ¿e zostaniesz dobrym Centrologiem, prawda?}
{133}{}{Có¿, tak... ale warto, w razie gdyby coœ siê sta³o!}
{134}{}{Je¿eli tak mówisz... je¿eli tak mówisz. Mam inne pytania.}
{135}{}{Jak chcesz. Na razie.}
{136}{}{[Siada i przez chwilê nie mo¿e wydobyæ z siebie dŸwiêku. Ból pojawia siê na jego twarzy.] No có¿. [Odwraca g³owê] }
{137}{}{Za³o¿ê siê, ¿e chcesz siê jej odwdziêczyæ piêknym za nadobne.}
{138}{}{Przykro mi. Mam kilka innych pytañ.}
{139}{}{No to wiadomoœæ zosta³a dostarczona... na razie!}
{140}{}{I to jak. Czego potrzebujesz?}
{141}{}{Potrzebujê planów lataczy z twojego komputera.}
{142}{}{Chcê, abyœ sformatowa³ twardy dysk Centrologów.}
{143}{}{Chcê, abyœ w³ama³ siê do baz danych Shi i skierowa³ paliwo do tankowca Posejdon.}
{144}{}{Chcê, abyœ przekierowa³ paliwo ze statku kosmicznego do tankowca Posejdon.}
{145}{}{Niczego. Na razie.}
{146}{}{Proszê. A teraz idŸ st¹d. Zamierzam sformatowaæ komputer i odejœæ.}
{147}{}{Potrzebujê planów lataczy z twojego komputera.}
{148}{}{Chcê, abyœ w³ama³ siê do baz danych Shi i skierowa³ paliwo do tankowca Posejdon.}
{149}{}{Chcê, abyœ przekierowa³ paliwo ze statku kosmicznego do tankowca Posejdon.}
{150}{}{Có¿, tak naprawdê to by³ tylko ¿art. Ona tak naprawdê tego nie powiedzia³a.}
{151}{}{Powodzenia. Do zobaczenia!}
{152}{}{Proszê. To nauczy tych drani, ¿e nie mo¿na mnie wykorzystaæ i odtr¹ciæ. ¯egnam.}
{153}{}{Có¿, tak naprawdê to by³ tylko ¿art. Ona tak naprawdê tego nie powiedzia³a.}
{154}{}{¯egnaj.}
{155}{}{Nie powiedzia³a. To po prostu wspaniale.}
{156}{}{A wiêc uczyni³em te wszystkie szkody za nic. Teraz ciê za to zabijê.}
{157}{}{Spróbuj.}
{158}{}{Tak powiedzia³a? Naprawdê? Rany. [Wspania³y uœmiech pojawia siê powoli na jego twarzy] Co mogê dla ciebie zrobiæ?}
{159}{}{Potrzebujê planów lataczy z twojego komputera.}
{160}{}{Chcê, abyœ sformatowa³ twardy dysk Centrologów.}
{161}{}{Chcê, abyœ w³ama³ siê do baz danych Shi i skierowa³ paliwo do tankowca Posejdon.}
{162}{}{Chcê, abyœ przekierowa³ paliwo ze statku kosmicznego do tankowca Posejdon.}
{163}{}{A, niczego. IdŸ i baw siê dobrze.}
{164}{}{Proszê bardzo. Coœ jeszcze?}
{165}{}{Potrzebujê planów lataczy z twojego komputera.}
{166}{}{Chcê, abyœ sformatowa³ twardy dysk Centrologów.}
{167}{}{Chcê, abyœ przekierowa³ paliwo ze statku kosmicznego do tankowca Posejdon.}
{168}{}{Chcê, abyœ w³ama³ siê do baz danych Shi i skierowa³ paliwo do tankowca Posejdon.}
{169}{}{Nie. Na razie!}
{170}{}{Sformatowaæ twardy dysk? ¯artujesz sobie? Nie ma mowy! Nie mogê tego zrobiæ!}
{171}{}{To tylko rutynowe czyszczenie. Wszystko ju¿ ma kopie bezpieczeñstwa.}
{172}{}{Och, W porz¹dku. Mam wiêcej pytañ.}
{173}{}{Och, w porz¹dku. Do widzenia.}
{174}{}{A. Có¿, jeœli wszystko jest ju¿ zabezpieczone, to zrobiê to [naciska kilka klawiszy na klawiaturze] Gotowe.}
{175}{}{Dziêki! Na razie!}
{176}{}{W³aœnie zosta³eœ dok³adnie wydymany. ¯egnaj, frajerze!}
{177}{}{Sam to sprawdzê. Nie s¹dzê, aby w tej chwili by³o bezpiecznie formatowaæ g³ówn¹ jednostkê.}
{178}{}{Mam wiêcej pytañ.}
{179}{}{Dobra. ¯egnam.}
{180}{}{Nie, nie... By³bym zbyt za¿enowany.}
{181}{}{W porz¹dku, nie ma sprawy. Mam wiêcej pytañ.}
{182}{}{Ok, ok.}
{183}{}{Powinno mi siê udaæ. Ale tylko je¿eli masz na myœli jakieœ konkretne zadanie.}
{184}{}{Przeœlij paliwo do tankowca Posejdon.}
{185}{}{Nic mi w tej chwili nie przychodzi do g³owy. Jakby co, to dam ci znaæ.}
{186}{}{No, na przyk³ad:}
{187}{}{"Czy mój terminal ma obs³ugê 3D?"}
{188}{}{"Dlaczego w polskiej wersji jest Generator Ekosystemu Cudownej Krainy, zamiast swojskiego Garden of Eden Creation Kit? Przecie¿ przez to traci siê inglisz klajmyt?"}
{189}{}{"S¹dzê, ¿e powinniœmy zmieniæ interfejs, pomimo tego, ¿e dzia³a on doskonale!"}
{190}{}{"Co to jest Kryptopolis? Czemu nie Vault City?! Jak mo¿na wymyœliæ tak¹ bzdurê?"}
{191}{}{"Powinienem mieæ dwie spluwy. Czemu nie mogê u¿ywaæ dwóch splów?"}
{192}{}{"Na moim terminalu interfejs chodzi wolno i tnie siê. To na pewno wasza wina."}
{193}{}{Coœ w tym stylu.}
{194}{}{Rozumiem. Ci ludzie musz¹ dawaæ ci kupê radochy. Mam inne pytania.}
{195}{}{Rozumiem. Có¿, do zobaczenia.}
{196}{}{Móg³bym to zrobiæ. Ale potrzebowa³bym dobrego powodu, a takiego nie mam. Przykro mi. Coœ jeszcze?}
{197}{}{Tak, mam te¿ inne pytania.}
{198}{}{Nie, chyba nie.}
{199}{}{Przykro mi, ale ich system od pewnego czasu nie odpowiada. Nie ma sposobu, aby siê tam dostaæ.}
{200}{}{Ju¿ nied³ugo zajmê siê Vikki... ee... tzn. jak mogê ci pomóc?}
{201}{}{Ich system nie odpowiada ju¿ od jakiegoœ czasu. Wygl¹da, ¿e ktoœ sformatowa³ ich bazê danych. Co ja teraz bêdê tu robi³, kiedy ju¿ z tob¹ skoñczê? Coœ jeszcze?}
