#looks/descriptions
{100}{}{Widzisz stra¿nika w luŸnych ciuchach, wygl¹da na znu¿onego czuwaniem .}
{101}{}{Widzisz stra¿nika portowego. Niezwykle dobrze uzbrojonego stra¿nika.}
{102}{}{Widzisz stra¿nika motorówki.}

#touched motor boat without permission
{150}{}{Hej! Odsuñ siê od niej!}
{151}{}{Nawet o tym nie myœl. To ostatnie ostrze¿enie.}
{152}{}{Ostrzega³em, lao wai, giñ!}

#Main dialogue

#Greeting
{200}{}{Czego chcesz, lao wai?}
{201}{}{To znowu ty. Czego chcesz, lao wai?}
{202}{}{Czego pilnujesz?}
{203}{}{Potrzebujê tej motorówki.}
{204}{}{Niczego. Czeœæ.}

#what are you guarding?
{210}{}{Wszystkiego. Nie próbuj niczego zabawnego.}
{211}{}{Mo¿esz wyra¿aæ siê jaœniej?}

#be more specific
{220}{}{Nie. A teraz cofnij siê, przyb³êdo.}
{221}{}{Dobra. Czeœæ.}
{222}{}{Nikt nie bêdzie mi mówi³ co mam robiæ. Jesteœ cholernym trupem!}

#I need to use the motor boat
{230}{}{A ja potrzebuje ciê sp³awiæ. Nie masz pozwolenia na u¿ycie motorówki, cholera, jesteœ lao wai, a nie Shi.}
{231}{}{S³uchaj, jestem w naprawdê trudnej sytuacji. Jeœli nie pozwolisz mi wzi¹æ motorówki, ca³e moje plemiê zginie.
 W tej chwili, s¹ w szponach tych drani z Enclavy i licz¹ na to, ¿e ich uwolniê. Ale ¿eby to zrobiæ,
 potrzebujê tej motorówki. Jeœli nie pozwolisz mi jej wzi¹æ, to dojdzie do walki i ktoœ z nas zginie. Proszê, nie doprowadŸ do tego.}
{232}{}{W³aœciwie, to Shi przyznali mi honorowe cz³onkostwo. Zatrudnili mnie i do³¹czyli do zespo³u obs³ugi okrêtu podwodnego, ze wzglêdu na moje doœwiadczenie w... okrêtologii. To moje has³o...}
{233}{}{Chyba nie wiesz kogo obra¿asz. Czas umieraæ, dupku.}
{234}{}{Dobra, idê... jeju, co za ludzie...}

#Listen, I might not be Shi...
{240}{}{[Patrzy na ciebie przez d³u¿sz¹ chwilê, potem wzdycha.] Pos³uchaj, nikt nie wejdzie na t¹ ³ódŸ bez podania w³aœciwego has³a. No wiesz, takiego jakiego jakie w³aœnie od ciebie us³ysza³em. [Mamrocze.] Oberwie mi siê za to od Kena Lee...}
{241}{}{Dziêkujê, przyjacielu. I nie martw siê, nikomu o tym nie powiem.}

#I won’t speak a word of this anyone
{250}{}{Mam tak¹ nadziejê, te¿ dla twojego dobra... Daj znaæ kiedy bêdzie ci potrzebna ³ódka. Ale nie przyprowadzaj tu nikogo wiêcej, bo to przyci¹gnie za du¿o uwagi. Musisz siê tam udaæ w pojedynkê.}
{251}{}{Teraz jej potrzebujê.}
{252}{}{Jeszcze nie teraz.}

#I'm a member of the Shi...
{260}{}{[Stra¿nik s³ucha has³a i przytakuje.] Chyba naprawdê jesteœ technikiem. Hmm, Shi musz¹ byæ naprawdê zdesperowani skoro przyjmuj¹ obcych... W ka¿dym razie, jesteœ za wczeœnie. Nie powiedzieli ci, ¿e ekipa techników nie opuszcza portu przed pó³noc¹? Jak chcesz mo¿esz poczekaæ na resztê techników tutaj.}
{261}{}{Chêtnie i tak nie mam nic lepszego do roboty...}
{262}{}{Wrócê póŸniej.}

#Use motor boat now
{270}{}{U¿yj polera i zejdŸ po linie cumowniczej do ³ódki. Ale nie grzeb siê tam, nie chcê ¿adnych k³opotów.}
{271}{}{£apiê. Czeœæ.}
{272}{}{Rozumiem. Do zobaczenia.}

#Player wasn't initially ready to go with the tech team
{280}{}{Chcesz wreszcie do³¹czyæ techników?}
{281}{}{Tak, czas ruszaæ.}
{282}{}{Nie, jeszcze nie.}

{290}{}{Nie widzisz, ¿e jestem zajêty?}

#dumb dialogue
{300}{}{Ja jechaæ metalowa rybia-ryba?}
{310}{}{[Patrz¹c na ciebie jak na najg³upsze stworzenie jakie móg³by sobie wyobraziæ, powoli, krêci g³ow¹.] Ty nie jedziesz metalow¹ rybi¹-ryb¹. Ty idziesz. Ty idziesz, albo ja strzelam. Rozumiesz?}
{311}{}{Wporzo, pa pa!}
{312}{}{Ty wredny pan. Ja rozgnieœæ wredny pan!}

{500}{}{Udaje ci siê uzyskaæ dostêp do ³odzi bez rozlewu krwi.}
