{100}{}{Widzisz dobrze uzbrojonego strażnika.}
{101}{}{Widzisz strażnika Centrologów.}
{102}{}{Widzisz dobrze uzbrojoną osobę z okrutnym wyrazem oczu.}
{103}{}{Intruz!}
{104}{}{Łapać intruza!}
{105}{}{Tutaj! Tutaj!}
{106}{}{Czas umierać, niewierni! Przez łamanie Wielkim Kołem!}
{107}{}{Jesteśmy Strażnikami. A ty masz teraz umrzeć.}
{108}{}{Gwiezdny Ojcze, nieś moje kule.}
{109}{}{Plugawisz nasze zasady!}
{110}{}{Jeżeli nasi prawnicy nie mogą sobie poradzić, to zrobią to nasze kule.}
{111}{}{Jesteśmy długim ramieniem sprawiedliwości Centrum.}
{112}{}{Transgresor!}
{113}{}{Uważaj jak chodzisz.}
{114}{}{Stąpaj lekko, ty, z zewnątrz.}
{115}{}{Nie dotykaj niczego, czego nie masz prawa.}
{116}{}{Jeżeli spróbujesz się wyłamać, zrobimy z ciebie siekane kotlety.}
{117}{}{Postępuj bardzo, bardzo ostrożnie.}
{118}{}{Jesteśmy prawem Centrum. Nie łam go.}
{119}{}{Jestem UKC-4.}
{120}{}{Uszereguję cię, jeżeli będziesz się źle zachowywać.}
{121}{}{Mam władzę od Wielkiego Koła.}
{122}{}{Witaj, przyjazna duszo.}
{123}{}{Witaj,}
{124}{}{Dobrze mieć cię z nami.}
{125}{}{Idź zająć się swoimi sprawami.}
{126}{}{Nie zawracaj głowy tym, którzy chcą się skupić.}
{127}{}{Twoja obecność jest mile widziana... ale tam.}
{128}{}{Centrum zostawił nas, abyśmy dbali o jego stado.}
{129}{}{Gwiezdny Ojciec dba o ciebie. Dlatego dał ci nas.}
{130}{}{Jesteśmy lojalni wobec AHS-9.}
{131}{}{Bądź posłuszny.}
{132}{}{Śpij.}
{133}{}{Jedź.}
{134}{}{Mamy na sercu tylko twoje dobro.}
{135}{}{.}
