{100}{}{Widzisz mê¿czyznê w stalowej zbroi.}
{101}{}{You see Luke.}
{102}{}{Widzisz mê¿czyznê w stalowej zbroi z symbolem b³yskawicy.}
{103}{}{Witaj,}
{104}{}{. I'm Luke, what can I do for you?}
{105}{}{Sk¹d zna imiê?}
{106}{}{Sk¹d znasz moje imiê?}
{107}{}{Joshua mentioned that you stopped by our Den office. He said you were a small fish making big waves.}
{108}{}{Word gets around. You're a small fish making big waves.}
{109}{}{Co znaczyæ?}
{110}{}{Co masz na myœli?}
{111}{}{You're attracting the attention of a lot of people. You need to be careful.}
{112}{}{Mów dalej.}
{113}{}{Mówi dalej, s³ucham.}
{114}{}{Doœæ ju¿ powiedzia³em. Musisz wracaæ do swoich poszukiwañ.}
{115}{}{This same blow off me get from Joshua. Me need ask question.}
{116}{}{Czekaj, u mnie pytanie.}
{117}{}{This is the same blow off I got from Joshua. Can I ask you some questions?}
{118}{}{Czekaj, chcê ciê o coœ zapytaæ.}
{119}{}{Joshua allowed you one question; I'll do the same. What will it be?}
{120}{}{Dobrze, odpowiem na jedno pytanie. Co chcesz wiedzieæ?}
{121}{}{Wiedzieæ gdzie GECK?}
{122}{}{Wiedzieæ gdzie Kruchta 13?}
{123}{}{Kim wy do cholery jesteœcie?}
{124}{}{Wiesz mo¿e, gdzie móg³bym odnaleŸæ GECK?}
{125}{}{Nie wiesz gdzie znajduje siê Krypta 13?}
{126}{}{Kim wy do cholery jesteœcie?}
{127}{}{Yes, I believe that Vault 13 never used theirs. You should be able to find one there. Good luck,}
{128}{}{Wait! Where vault?}
{129}{}{Now wait a minute! Where's the vault?}
{130}{}{Yes, its location is stored in the vault 15 computer systems, east of here. Good luck,}
{131}{}{.}
{132}{}{Dziêki.}
{133}{}{We are the Brotherhood of Steel. There is nothing more that I will tell you at this time. Good luck,}
{134}{}{Wait! Me need know even more now!}
{135}{}{Wait, you can't just leave it at that!}
{136}{}{Witaj ponownie. Nie mam ci nic nowego do powiedzenia.}
{137}{}{. Well... You've certainly come a long way from the simple tribesman. You should visit our San Francisco office some time. You might find it rewarding. Now, if you'll excuse me, I must be going.}
{138}{}{Witaj ponownie. Nie mam ci nic nowego do powiedzenia.}
{139}{}{Czekaj...}
{140}{}{Do pomieszczenie zamkniête.}
{141}{}{Nic tam po tobie.}
{142}{}{To teren prywatny. Lepiej st¹d idŸ.}
