{100}{}{Widzisz szykownie ubranego mê¿czyznê.}
{101}{}{Widzisz Wielkiego i Potê¿nego UKC-9.}
{102}{}{Widzisz szykownie ubranego mê¿czyznê.}
{103}{}{Bezczeœcisz imiê Centrum! Musisz umrzeæ!}
{104}{}{Twoja bezczelnoœæ nie zna granic!}
{105}{}{Bêdziemy ciê ³amaæ Wielkim Ko³em!}
{106}{}{Jesteœ w obecnoœci Wielkiego i Potê¿nego UKC-9. Czego sobie od niego ¿yczysz?}
{107}{}{Ych a nu, UKC!}
{108}{}{Szukam mojego ludu. Podobno przeszli nad tym terenem w lataj¹cych statkach.}
{109}{}{Mam do ciebie wiele pytañ, UKC-9.}
{110}{}{Oœwiecona w RNK prosi³a mnie, aby ci dostarczyæ ten list. Wspomina³a tak¿e coœ o nagrodzie.}
{111}{}{Oœwiecona w RNK prosi³a mnie, aby ci dostarczyæ ten list. Oto on.}
{112}{}{Ach, UKC-9, przynoszê ci ten oto list od wys³anniczki w RNK. Padam do stóp twojej chwale.}
{113}{}{Twojej œmierci. ¯egnaj starcze.}
{114}{}{Nic, przepraszam.}
{115}{}{Tak, moje dziecko?}
{116}{}{Hinczolf? [Ty mnie rozumiesz?]}
{117}{}{Agga gaga gigi gugagu! [Och, dziêki bogu. Szukam mojego ludu. Muszê dostaæ siê za wielka wodê.]}
{118}{}{Pe³ne pory! [Có¿, dziêkujê za twój czas. Muszê ju¿ wyruszaæ. Mi³o mi by³o z tob¹ rozmawiaæ.]}
{119}{}{Nie rozumiem s³owa z tego, co mówisz. Zapytaj mo¿e Juana lub Vikki o oœwiecenie.}
{120}{}{Kuje!}
{121}{}{Oczywiœcie, moje dziecko. Szeregowanie oczyœci³o twoje podstawowe neurodyny i ukierunkowa³o je z moimi oraz ze Szprychami Wielkiego Ko³a. Czego sobie ¿yczysz?}
{122}{}{Agga gaga gigi gugagu! [Och, dziêki bogu. Szukam mojego ludu. Muszê dostaæ siê za wielka wodê.]}
{123}{}{J-j-j-ózio. [Nic, dziêkujê. Po prostu to mi³e potrafiæ siê z tob¹ porozumieæ. Do zobaczenia!]}
{124}{}{Je¿eli zgodzisz siê wyœwiadczyæ mi przys³ugê, bêdê móg³ ci pomóc, moje dziecko.}
{125}{}{Ojk? [Có¿ to takiego? Chêtnie us³u¿ê ci pomoc¹.]}
{126}{}{Ne!}
{127}{}{Mój przeciwnik, Cesarz miasta Shi, powoduje, ¿e moje ¿ycie staje siê ¿a³osne. Chcê, ¿eby jego ¿ycie ju¿ siê zakoñczy³o. W podziêce dopilnujê, aby twoja osoba znalaz³a siê tam, gdzie musi.}
{128}{}{Ajs! [Zrobiê to.]}
{129}{}{Ne!}
{130}{}{Daj mi znaæ, je¿eli zmienisz zdanie. Pamiêtaj jednak, ¿e mogê byæ jedyn¹ osob¹, przez któr¹ mo¿esz dotrzeæ do rodziny.}
{131}{}{OK. [Jaka jest ta przys³uga?]}
{132}{}{Didzeruu! [Dziêkujê, ale wolê nie byæ niczyim d³u¿nikiem. ¯egnaj!]}
{133}{}{Dobrze. Powiadom mnie, gdy wykonasz misjê, a ja w tym samym czasie bêdê siê dowiadywaæ o sposoby na osi¹gniecie twojego celu. ¯egnaj, moje dziecko.}
{134}{}{Do'dzenia! [¯egnaj UKC-9. Jesteœ wspania³ym cz³owiekiem.]}
{135}{}{Czy twoja misja jest ju¿ ukoñczona? Od tego zale¿y twoja przysz³oœæ, a tak¿e przysz³oœæ Wielkiego Ko³a na tej planecie.}
{136}{}{Y-y. [Jeszcze nie. Chcê siê tylko przywitaæ.]}
{137}{}{Pracujê nad tym. Mam jednak kilka pytañ.}
{138}{}{Jeszcze nie. Wrócê do ciebie póŸniej.}
{139}{}{I ja ciebie pozdrawiam. A teraz idŸ ukoñczyæ zadanie tak, abym móg³ ci pomóc.}
{140}{}{Ny! Ny! [Tak jest!]}
{141}{}{Z twojej aury wnioskujê, ¿e uda³o ci siê oczyœciæ œwiat z zanieczyszczaj¹cych neurodyn Cesarza.}
{142}{}{Dziksa! [Tak, uda³o mi siê. A jak tam twoja czêœæ umowy?]}
{143}{}{Owszem. A teraz poproszê o pomoc w uratowaniu mojego ludu.}
{144}{}{Je¿eli pójdziesz do doków miasta Shi, znajdziesz tam PMV Valdez. WejdŸ na statek. Udaj siê w prawo i do góry na mostek kapitañski. Tam naciœnij przycisk start, a tankowiec pop³ynie prosto do twojego celu.}
{145}{}{Kuje! [Przyjemnie by³o z tob¹ pracowaæ, UKC-9. ¯yczê ci wszystkiego dobrego. Do widzenia.]}
{146}{}{Statki lataj¹ce? Musisz mieæ na myœli Enklawê i jej latacze.}
{147}{}{Tak, chyba tak.}
{148}{}{Enklawê? Jak¹ Enklawê?}
{149}{}{Zaufaj mi, moje dziecko, mówisz o Enklawie.}
{150}{}{No dobra. Jak mogê ich odnaleŸæ?}
{151}{}{Enklawa to pozosta³oœæ dawnego œwiata - neurodyna, która nie zosta³a jeszcze uszeregowana. Maj¹ ukryte bazy porozrzucane po ca³ej Kalifornii, a ich najsilniejsza forteca znajduje siê daleko na zachód, ponad wod¹.}
{152}{}{Jak tam siê dostaæ?}
{153}{}{Sk¹d ty to wszystko wiesz?}
{154}{}{To, moje dziecko, musisz odkryæ samodzielnie. Popytaj dooko³a, a odnajdziesz prawdê.}
{155}{}{Bardzo mi to pomog³o. Mam inne pytania.}
{156}{}{Sk¹d ty to wszystko wiesz?}
{157}{}{Jak chcesz. Na razie.}
{158}{}{Dziecko, jestem UKC-9. Widzê rzeczy, które przenikaj¹ do rzeczywistego œwiata. Czy masz jeszcze inne pytania, czy mogê powróciæ do moich medytacji?}
{159}{}{Jeszcze tylko kilka.}
{160}{}{Wróæ do swoich medytacji. Nie mam wiêcej pytañ.}
{161}{}{Cesarz i jego s³udzy zostali zabici?}
{162}{}{Tak.}
{163}{}{Wiêc nie ma ju¿ nikogo, kto móg³by stan¹æ mi na drodze! Ale nie widzê sensu, aby ujawniaæ cokolwiek zwyk³emu narzêdziu. ¯egnaj - dziêki bogu!}
{164}{}{Ty œmieciu! Teraz za to zginiesz.}
{165}{}{Och. No có¿, je¿eli tak musi ju¿ byæ. ¯egnaj.}
{166}{}{List od Oœwieconej? Czy¿by tak siê teraz nazywa³a? Ha! [odbiera od ciebie list] Obieca³a ci nagrodê. Oto nagroda - moja wdziêcznoœæ. Dobrego dnia.}
{167}{}{To wszystko? Starcze, jesteœ ju¿ martwy.}
{168}{}{Ee, mam kilka pytañ.}
{169}{}{Jejku, wspaniale. ¯egnam.}
{170}{}{Skieruj swoje pytania do UKC-7. Jam jest Wielki i Potê¿ny UKC-9, mam wiele wa¿nych spraw na g³owie. Nie przeszkadzaj mi, miêcho.}
{171}{}{Je¿eli nie odpowiesz na moje pytania, odpowiesz na moj¹ broñ.}
{172}{}{Jak chcesz.}
{173}{}{Ach, list od mojego agenta operacyjnego. Szkoda, ¿e nazywa siebie "Oœwiecon¹" - to tylko wskazuje na to, jak bardzo ni¹ nie jest. Masz moj¹ wdziêcznoœæ.}
{174}{}{Nie ma sprawy. Mam jednak jedno, dwa pytania.}
{175}{}{Wspaniale. Do zobaczenia.}
{176}{}{Tak, moje dziecko?}
{177}{}{Kiedy odlatuje statek kosmiczny?}
{178}{}{Czy masz dla mnie jakieœ zadania?}
{179}{}{Na co id¹ wszystkie pieni¹dze, które ofiarowujemy?}
{180}{}{Ach, nic takiego. Niewa¿ne.}
{181}{}{Mój przeciwnik, Cesarz miasta Shi, powoduje, ¿e moje ¿ycie staje siê ¿a³osne. Chcê, ¿eby jego ¿ycie ju¿ siê zakoñczy³o. W podziêce dopilnujê, aby twoja osoba znalaz³a siê tam, gdzie musi.}
{182}{}{Jasne, szefie. Na ra.}
{183}{}{Raczej nie.}
{184}{}{Poszukaj Badgera, którego obrzydliwa obecnoœæ trzyma w kupie tych ¿a³osnych w³óczêgów z tankowca. Usuñ tê skazê z naszego miasta. Gdy ju¿ to zrobisz, porozmawiaj z UKC-9.}
{185}{}{Jasne szefie. Na razie.}
{186}{}{Raczej nie.}
{187}{}{Chyba nie da³em do zrozumienia, ¿e jest to moja PROŒBA, dziecko. Zabij go!}
{188}{}{Nie.}
{189}{}{Och, no dobra. Zrobiê to.}
{190}{}{Oœmielasz siê sprzeciwiaæ Wielkiemu i Potê¿nemu UKC-9. A wiêc zginiesz.}
{191}{}{No spróbuj.}
{192}{}{Chwileczkê, jednak chyba to zrobiê.}
{193}{}{Za póŸno, miêcho. Okaza³o siê, ¿e nie mo¿na ci ufaæ. Giñ!}
{194}{}{[Dalej]}
{195}{}{Moje dziecko, s¹ rzeczy na niebie i ziemi, których nie mo¿esz na razie znaæ. [Uœmiecha siê mi³o.]}
{196}{}{W porz¹dku. Mam kilka innych pytañ.}
{197}{}{Hmmm. Do zobaczenia.}
{198}{}{ESS Quetzel wystartuje, gdy uk³ad gwiazd bêdzie odpowiedni.}
{199}{}{O-oczywiœcie. Mam inne pytania.}
{200}{}{Dziêki. Na razie.}
{201}{}{Twoja odpychaj¹ca aura mówi mi, ¿e twoja obecnoœæ tutaj nie znaczy dla mnie nic dobrego. Powiedz mi moje dziecko, czy chcesz mieæ korzyœci ze swojego szczêœcia?}
{202}{}{Tak.}
{203}{}{Nie.}
{204}{}{Nie, po prostu chcê, abyœ zgin¹³.}
{205}{}{A wiêc oto moja propozycja: wróæ do Shi i wyeliminuj Kena Lee i Cesarza. Zap³acê ci wiêcej pieniêdzy, ni¿ kiedykolwiek ci siê œni³o.}
{206}{}{Nie, nie s¹dze.}
{207}{}{Umowa stoi, grubasie.}
{208}{}{A wiêc idŸ i odci¹¿ ich cia³a od zagubionych dusz. Czekam na wiadomoœæ o sukcesie [Uœmiecha siê anielsko.]}
{209}{}{Do zobaczenia.}
{210}{}{Nie, zaczekaj. Chyba jednak wolê uwolniæ CIEBIE od problemów doczesnych.}
{211}{}{Ach, moje dziecko, jak mo¿esz tak zejœæ ze œcie¿ki prawdy? Z twojej aury widzê, ¿e zamierzasz mnie zabiæ. Jestem gorzko zawiedziony. No có¿. Zaczynajmy.}
{212}{}{Tak, zacznijmy. Giñ.}
{213}{}{Pamiêtaj, ¿e po zakoñczonej misji musisz zobaczyæ siê z UKC-7.}
{214}{}{Wszystkie twoje potrzeby zosta³y zaspokojone. Teraz jest czas na moje medytacje.}
