{100}{}{Widzisz zakapturzonego Centrologa. W jakiœ sposób wyró¿nia siê z t³umu.}
{101}{}{Widzisz UKC-7, drugiego we w³adzy.}
{102}{}{Widzisz zakapturzonego Centrologa.}
{103}{}{Stra¿! Niewierny! Usuñcie go!}
{104}{}{Ty. Czego tu chcesz.}
{105}{}{Aaagh! Nu! Nee!}
{106}{}{Mam list dla UKC-9 od Oœwieconej z RNK.}
{107}{}{I'm here to speak to Crockett about some armor.}
{108}{}{Chcê siê tu rozejrzeæ.}
{109}{}{Byæ mo¿e interesowa³oby mnie wst¹pienie w wasze szeregi.}
{110}{}{Kim jesteœ?}
{111}{}{Przybywam, aby zabiæ was wszystkich.}
{112}{}{Ach, moje biedne dziecko. Czy chcesz doznaæ oœwiecenia?}
{113}{}{'ak!}
{114}{}{Nie!}
{115}{}{Biedne dziecko. Ju¿ oœwiecone, jednak niezdolne do wyra¿ania siê. Proszê, wejdŸ.}
{116}{}{'kuje!}
{117}{}{WejdŸ i poszukaj Juana i Vikki. Mog¹ ci pomóc. Powodzenia, moje dziecko.}
{118}{}{'kuje!}
{119}{}{::jego g³os twardnieje:: Wiêc nie widzê powodu, aby pozwolono ci tu zostaæ. ¯egnam.}
{120}{}{'ej!}
{121}{}{Dobrze. Œpiesz siê jednak - to bardzo zajêty cz³owiek.}
{122}{}{W porz¹dku.}
{123}{}{To nie jest miejsce przeznaczone dla wycieczek. Do widzenia.}
{124}{}{[dalej]}
{125}{}{Doskonale! WchodŸ, wchodŸ. Porozmawiaj z Juanem Kruzem i Vikki Goldman - wiesz, oni s¹ gwiazdami, ale porozmawiaj¹ z TOB¥.}
{126}{}{Kim oni s¹?}
{127}{}{Ooch! Gwiazdy!}
{128}{}{Jestem UKC-7, drugi w linii dowodzenia w tym obiekcie. Zanim spytasz: UKC to skrót od Uszeregowanego Kandydata Centrum, co oznacza, ¿e oczyœci³e³em ju¿ siedem poziomów neurodyn mojego ducha. Oznacza to, ¿e jestem bardziej oœwiecony i bli¿ej centrum Wielkiego Ko³a ni¿ ty. A to oznacza, ¿e powiesz mi teraz, czego tutaj chcesz. Teraz.}
{129}{}{Mam list dla UKC-9 od Oœwieconej z RNK.}
{130}{}{I'm here to speak to Crockett about some armor.}
{131}{}{Chcê siê tu rozejrzeæ.}
{132}{}{Byæ mo¿e interesowa³oby mnie wst¹pienie w wasze szeregi.}
{133}{}{Przybywam, aby zabiæ was wszystkich.}
{134}{}{Sa gwiazdami z Nowego Reno. Us³yszeli w naszych pieœniach prawdê i przybyli uszeregowaæ swoje neurodyny.}
{135}{}{Gdzie mogê ich znaleŸæ?}
{136}{}{Có¿, niewa¿ne. Muszê ju¿ iœæ.}
{137}{}{Mo¿esz ich znaleŸæ w pokoju modlitw, pokazuj¹cych naszym nowym rekrutom i miêchu jak op³acalne jest bycie Centrologiem.}
{138}{}{To puœæ mnie do nich!}
{139}{}{Oceniê to samodzielnie. Zaczynajmy spektakl.}
{140}{}{Daruj sobie. Spadam st¹d.}
{141}{}{A wiêc znacie siê ju¿ z Juanem i Vikki. Czy interesuje ciê przy³¹czenie siê do naszych przyjació³ w poszukiwaniu oœwiecenia w Wielkim Kole?}
{142}{}{O tak. Tak, tak, tak!}
{143}{}{Jasne.}
{144}{}{Nie teraz. Czy mogê wróciæ do ciebie póŸniej?}
{145}{}{To chyba nie jest w moim stylu. Przykro mi.}
{146}{}{Do cholery, nigdy! Wasz ob³¹kañczy kult zas³uguje na wypalenie do cna.}
{147}{}{::uœmiecha siê:: Nie po¿a³ujesz tego. Mo¿esz poruszaæ siê po obiekcie. Ach... jesteœ osob¹, która wie jak u¿ywaæ broni. Czy chcesz u¿yæ jej w s³u¿bie Wielkiego Ko³a?}
{148}{}{Tak.}
{149}{}{Mo¿e póŸniej.}
{150}{}{Nie czekaj zbyt d³ugo przed udzieleniem odpowiedzi. Twoje neurodyny bêd¹ coraz bardziej i bardziej wype³niane zatruciem, zanim bêdziemy mogli rozpocz¹æ proces szeregowania.}
{151}{}{Zmieniam zdanie. Do³¹czê do was.}
{152}{}{Za³atwione. Porozmawiamy póŸniej.}
{153}{}{Mo¿esz opuœciæ ten kompleks bez obaw, wêdrowcze, jednak nie odradzam powrót. Je¿eli nie dzia³asz z nami, dzia³asz przeciwko nam - nie chcia³bym, aby sta³a ci siê jakaœ krzywda.}
{154}{}{Dziêki za zainteresowanie. Na razie.}
{155}{}{Nie s¹dzê, aby to mi sta³a siê krzywda. ¯egnaj.}
{156}{}{Spaliæ nas? SPALIÆ NAS? STRA¯E! ZABIÆ TO MIÊCHO!}
{157}{}{[dalej]}
{158}{}{A wiêc by³o du¿o czasu na przemyœlenie twojej decyzji. Czy do³¹czysz do nas?}
{159}{}{Tak.}
{160}{}{Nie.}
{161}{}{Wci¹¿ potrzebujê wiêcej czasu.}
{162}{}{Nie masz wiêcej czasu. Podejmuj decyzjê, miêcho.}
{163}{}{Dobrze, jestem z wami.}
{164}{}{Zapomnij o tym. Nie lubiê polityki silnej rêki.}
{165}{}{Gnêbiciele Shi podwa¿aj¹ potêgê Centrologów i wprowadzaj¹ chaos miêdzy naszych braci, stosuj¹c metody wp³ywania na neurodyny. S¹dzimy, ¿e je¿eli ich Cesarz zginie, zrozumiej¹ b³êdy swojego postêpowania. Czy wyeliminujesz Cesarza?}
{166}{}{Pewnie, zrobiê to.}
{167}{}{Nie, Shi nigdy nie zrobili mi nic z³ego.}
{168}{}{Byæ mo¿e przemyœlisz to jeszcze. Powiadom mnie, gdy to zrobisz. A teraz, czy jest coœ, czym mogê ci s³u¿yæ, rekrucie?}
{169}{}{Tak, mam kilka pytañ.}
{170}{}{Nie, nie teraz, dziêkujê.}
{171}{}{Czy chcesz nam pomóc w naszym wysi³ku przeciwko gnêbicielom Shi? Gwiezdny Ojciec pob³ogos³awi ci, je¿eli weŸmiesz udzia³ w naszej krucjacie.}
{172}{}{Wci¹¿ nie mam pewnoœci, czy chcê to zrobiæ.}
{173}{}{Zrobiê to.}
{174}{}{Byæ mo¿e zdo³am ul¿yæ twojej strapionej duszy. Czego potrzebujesz?}
{175}{}{Gdzie mogê zdobyæ paliwo do tankowca Posejdon?}
{176}{}{Gdzie mogê znaleŸæ znaczenie tych wszystkich wyrazów, których u¿ywacie?}
{177}{}{Kiedy odlatuje statek?}
{178}{}{Where is Crockett?}
{179}{}{Nic, dziêki. Do zobaczenia.}
{180}{}{Powiadom nas, gdy wykonasz misje.}
{181}{}{Zrobi siê. Mam inne pytania.}
{182}{}{W porz¹dku. Do widzenia.}
{183}{}{Czy gnêbicielska cesarska plama zosta³a usuniêta z materii egzystencji?}
{184}{}{Jeszcze nie.}
{185}{}{Tak, UKC-7. Jest martwy.}
{186}{}{Prawdziwy przywódca w³óczêgów z tankowca jest nieuszeregowanym miêchem o imieniu Badger. Wraz z jego œmierci¹ zrozumiej¹ nasz¹ pozycje. Usuniesz go?}
{187}{}{Zrobiê to.}
{188}{}{Nic z³ego mi nie zrobi³. Wolê nie.}
{189}{}{A wiec... Czy chcesz nam pomóc usun¹æ tego "Badgera"?}
{190}{}{Zrobiê to.}
{191}{}{Raczej nie.}
{192}{}{Czy "Badger" jest ju¿ wyeliminowany?}
{193}{}{Jeszcze nie.}
{194}{}{Tak. Po prostu znikn¹³.}
{195}{}{Jego ludzie zaczn¹ popieraæ centrum! Wszystko bêdzie dobrze! Twoja s³u¿ba przynios³a nam wielkie korzyœci!}
{196}{}{Dziêki! Mam jeszcze kilka pytañ.}
{197}{}{Robiê to wszystko dla Ko³a. ¯egnaj.}
{198}{}{Hmm, tak na serio to zamierzam wykoñczyæ tak¿e was. }
{199}{}{Teraz, gdy statek jest nape³niony paliwem, oczekujemy tylko s³owa od Wielkiego i Potê¿nego UKC-9 na osi¹gniecie odlotu.}
{200}{}{... Oczywiœcie. Mam pytania.}
{201}{}{Dziêki. Na razie.}
{202}{}{Poza naszym cennym paliwem, którego potrzebujemy do wystrzelenia nas prosto pod skrzyd³a naszych gwiezdnych braci na planecie Centrum, nie potrafiê pod¹æ innego miejsca. Mo¿e Shi?}
{203}{}{Uch. Mam inne pytania.}
{204}{}{Tak, byæ mo¿e.}
{205}{}{S³ysza³em, ¿e Shi posiadaj¹ ogromny zbiornik paliwa. Mo¿e ma³a kradzie¿ rozwi¹za³aby twój problem.}
{206}{}{Dobry pomyœl. Mam wiêcej pytañ.}
{207}{}{Mo¿e. Dziêki.}
{208}{}{Po prostu wykorzystaj holodysk otrzymany od Juana i Vikki i sprawdŸ znajduj¹cym siê tam s³owniczku pojêæ.}
{209}{}{Dziêki. Wiêcej pytañ?}
{210}{}{Dziêkujê.}
{211}{}{Gdy UKC-9 otrzyma swoj¹ wizjê od Centrum, opuœcimy te ziemie i przy³¹czymy siê do niego w gwiezdnej chwale!}
{212}{}{Ta, chwalmy Ko³o, czy jakoœ tak. Mam wiêcej pytañ.}
{213}{}{Dziêki za dok³adne informacje.}
{214}{}{Zazwyczaj jest w swoim laboratorium, pracuj¹c nad sposobami ulepszania naszych cia³ i umys³ów.}
{215}{}{Dziêki. Chcê spytaæ o coœ innego.}
{216}{}{Dziêkujê.}
{217}{}{Zanim naprawdê zostaniesz naszym cz³onkiem, musimy przeprowadziæ pocz¹tkowy reform-skan - uszeregowanie. Czy mo¿emy zacz¹æ skan?}
{218}{}{Nie! ¯adnego skanowania!}
{219}{}{Jasne. Zróbmy to.}
{220}{}{Bez skanu nie mo¿esz do nas do³¹czyæ. Czy na pewno chcesz odmówiæ?}
{221}{}{Na pewno. Nie chcê, ¿eby wasze maszyny robi³y ze mnie ma³pê.}
{222}{}{Och, w porz¹dku. Skanujcie.}
{223}{}{Uszeregowaliœmy niektóre z twoich najbrudniejszych neurodyn. Obecnie masz rangê UKC-1. Czy ju¿ mo¿esz przy³¹czyæ siê do naszej szlachetnej sprawy?}
{224}{}{O tak.}
{225}{}{Nie. Jeszcze nie chcê.}
{226}{}{Lekcja 1: Tutaj mamy wiecznoœæ. Tutaj jest miejsce, gdzie jest planeta Quetzel [Wskazuje na coœ.] A tu jesteœmy my. [Wskazuje na jakiœ punkt.] Teraz wszystko, co musimy zrobiæ, to przejœæ bardzo d³ug¹ drogê, aby tam dotrzeæ.}
{227}{}{O rany, bêdziemy potrzebowali du¿o butów.}
{228}{}{Czy mogê to jeszcze przemyœleæ?}
{229}{}{Znowu ty? Co?}
{230}{}{Czy jest jeszcze coœ do zrobienia?}
{231}{}{Nie chcemy ciê tu. Proszê, wyjdŸ.}
