{100}{}{Stój, mutancie pustkowia! Szukamy wrogów Enclawy. Zidentyfikuj się.}
{101}{}{Kogo nazywasz mutantem, dupku? Chcesz wroga? To go masz, tu stoję!}
{102}{}{Słuchaj, jestem tylko prostym człowiekiem. Nie znam żadnej Enclawy. Ta osoba której szukacie musi być naprawdę niebezpieczna, sądząc po waszym wyglądzie.}
{103}{}{To mi wystarczy. Zabić to.}
{104}{}{Och, to będzie ciekawe!}
{105}{}{O tak, są niebezpieczni i podejrzewamy, że uciekają z Gecko. Według mnie, to ciebie szukamy.}
{106}{}{Cóż, naprawdę cieszę się, że to nie mnie szukacie, bo nie wyglądacie na kogoś z kim chcę zadzierać. Ale słuchajcie, skoro jest tu w pobliżu ktoś niebezpieczny, muszę jak najszybciej wracać do mojej rodziny żeby ich ostrzec.}
{107}{}{Dobra, poddaje się. Zatańczmy!}
{108}{}{Nigdzie jeszcze nie pójdziesz. Czy zdarzyło ci się kiedykolwiek być w Gecko?}
{109}{}{Tak, oczywiście. Cudowne miejsce. To znaczy, tubylcy są szpetni i trochę śmierdzi i ta cała radiacja i inne takie tam, ale jest kupę zabawy z ich komputerami. Ha! Powinniście tam być jak zadarł ze mną taki dupek—no wiecie, taki podobny do was.}
{110}{}{Gecko? Nigdy w życiu, nie zamierzam się tam zbliżać bardziej niż teraz. Wiecie, że to miejsce jest pełne tych obrzydliwych ghuli? Czemu pytasz?}
{111}{}{Dobra, wierze ci. Chłopaki, rozproszyć się. Przeszukać teren. Musimy znaleźć nasz cel.}
{112}{}{Nie. Nie wieżę ci. Chłopaki, to jego szukamy!}
{113}{}{Nie. Nie wieżę ci. Chłopaki, to jej szukamy!}
{114}{}{Hej! Hej! Czekajcie. Dlaczego mi nie wierzycie? Co mam jeszcze zrobić?}
{115}{}{Ktoś włamał się do sieci komputerowej Enklawy z Reaktora Platformy Posejdon. Próbujemy go wytropić.}
{116}{}{Włamał się!? Cóż, to nie mogę być ja. Pochodzę z plemienia. Nawet nie wiem jak się używa tego - jak to nazywacie? - Kum-pu-tora.}
{200}{}{Geko? O nie, w życiu się tam nie zbliżę bardziej niż teraz. Nie wiesz, że to miejsce jest pełne obrzydliwych ghuli? Wystarczy, że muszę zajmować się moim wujkiem Lennym, tym tutaj. Czemu pytasz?}
{201}{}{Uga?}
{202}{}{Ja zabijać niedobruchów!}
