{100}{}{Widzisz jarzącego się Ghula z zatroskanym wyrazem twarzy.}
{101}{}{Widzisz Hanka, jarzącego się Ghula, pracownika elektrowni.}
{102}{}{Widzisz jarzącego się Ghula doglądającego różnych wskazników.}
{110}{}{Cześć, jestem Hank. Opiekuję się wnętrzem rdzenia reaktora. Jednak rzadko kiedy trzeba tam cokolwiek zrobić.}
{111}{}{Cześć. Miło, że mnie odwiedzasz. Jak miło i cieplutko jest tak blisko rdzenia. Ale większości gładkoskórków to nie interesuje.}
{112}{}{Cześć Hank. Muszę dostać się do rdzenia.}
{113}{}{Hank, mam tu od Harolda raport dotyczacy chłodziwa, który musisz zobaczyć. Oto on.}
{114}{}{Cześć, Hank. Robie sobie tylko małą wycieczkę. Na razie.}
{120}{}{He, he. Nie radziłbym tego żadnemu z gładkoskórków. Usmażyłoby cię tam. Ja lubię ciepło, ale nie polecałbym tego tobie. Trochę tam za dużo gorąca i promieniowania. Dlatego też gładkoskórki, które zbudowały to miejsce, umieściły tu robota naprawczego.}
{121}{}{Robota naprawczego?}
{122}{}{Och, dzięki. Na razie.}
{130}{}{Zobaczmy. Według tego raportu, nasz poziom chłodzenia jest zdecydowanie za wysoki. Myślałem, że wyłączenie chłodzenia doprowadzi do natychmiastowego stopienia rdzenia, ale chyba się myliłem. Lepiej pójdę je wyłączyć.}
{131}{}{Ten raport mówi o zbyt wysokim poziomie chłodzenia. Nie sądzisz, że chyba muszę je wyłączyć?}
{132}{}{Dobrze pomyślane, Hank. Lepiej już pójdę. Do zobaczenia.}
{133}{}{Z drugiej strony może jednak powinieneś chwilę z tym zaczekać. Zanim wyłączysz chłodzenie, pójdę jeszcze skonsultować się z Haroldem. Na razie.}
{140}{}{Ta, gładkoskórki, które zbudowały to miejsce, same też nie chciały się usmażyć, więc umieściły tu robota. Został zaprojektowany do wykonywania robót naprawczych, a sterować można nim zdalnie z terminalu za moimi plecami.}
{141}{}{Doskonale. Wykorzystam to. }
{142}{}{Muszę to sprawdzić. Do zobaczenia.}
{150}{}{Masz tu niezłą część. Dokladnie to, czego potrzebujemy.}
{151}{}{Dobrze, że ci odpowiada. Chcesz ją zainstalować?}
{152}{}{Dzięki, mi też się podoba. Na razie.}
{160}{}{Chciałbym ci pomóc, ale nie wiedziałbym, jak coś takiego zainstalować. Większość czasu poświęcam tylko na obserwowanie tych wskazników. Spytaj Festusa. Jest tutejszym geniuszem od części - po prostu go zapytaj.}
{161}{}{Gdzie on jest?}
{162}{}{Czy nie ma innego sposobu?}
{163}{}{Dobra. Do widzenia.}
{170}{}{Czy Festus już rozmawiał z tobą o instalacji tej części?}
{171}{}{Gdzie on jest?}
{172}{}{Czy nie ma innego sposobu?}
{173}{}{Jeszcze nie. Właśnie do niego idę. Cześć.}
{180}{}{Festus był po drodze do tego miejsca. Jest w pokoju kontrolnym. Nie możesz go przegapić. To ten śmierdzący laluś chwiejący się pod ciężarem własnego ego. Powinien ci pomóc.}
{181}{}{Dzięki. Do zobaczenia.}
{190}{}{Cóż, gdyby wykorzystać robota naprawczego odpowiednio nim kierując, to może byłby w stanie zainstalować tę część. Albo możesz tam po prostu wejść i zainstalować ją samodzielnie.}
{191}{}{Robot naprawczy?}
{192}{}{Zainstalować samodzielnie?}
{200}{}{Cóż, ostatnio nie sprawiał się zbyt dobrze. Ciągle się przegrzewa. I tak nie musimy z niego korzystać, więc nie przejmowaliśmy się naprawieniem jego osłony cieplnej. Jeżeli uda ci się odcyfrować kody sterujące i nie będziesz go zbyt długo używać, być może będziesz w stanie wykorzystać go do swoich planów.}
{201}{}{Dzięki. Do zobaczenia.}
{210}{}{Dzięki za naprawienie reaktora.}
{211}{}{Czy ostatnio nie jest tutaj chłodniej?}
{212}{}{Dzięki za pomoc.}
{220}{}{Nigdy nie słyszałem, żeby w ten sposob buczał.}
{221}{}{Mruczy jak kociak.}
{222}{}{Działa lepiej niż kiedykolwiek.}
{230}{}{Po prostu nie zawadzaj i nic nie dotykaj.}
{231}{}{Kto cię tu wpuścił?}
{232}{}{Dlaczego nie zrobisz sobie wycieczki za te drzwi? Piekło wygląda naprawdę przepięknie. He, he, he.}
{300}{}{Udało ci się oszukać Hanka tak, że zainicjował stopienie rdzenia.}
{900}{}{Nie widzisz, że jestem zajęty?}
