{100}{}{Widzisz brudnego, zaspanego mê¿czyznê.}
{101}{}{XXX}
{102}{}{Widzisz brudnego, zaspanego mê¿czyznê. Jego ubranie wysz³o z mody baaardzo dawno temu.}
{103}{}{[przeciera oczy] Co... hê? Gdzie ja jestem? Jak d³ugo spa³em?}
{104}{}{Urr?}
{105}{}{Kim jesteœ?}
{106}{}{Nie mam pojêcia, ile spa³eœ, ale jesteœ teraz w Broken Hills, niedaleko Republiki Nowej Kalifornii.}
{107}{}{O nie! Spa³em tak d³ugo, ¿e wszyscy cofnêli siê w rozwoju! Aaaaaaaaaaa! [pogr¹¿a siê w panice]}
{108}{}{[Zrobione]}
{109}{}{Jestem Chuck Stodgers, najlepszy pilot samolotowy na œwiecie! Na moje nieszczêœcie... Rozbi³em siê. Doczo³ga³em siê do tej jaskini, by schroniæ siê przed eksplozj¹, ale dorwa³ mnie czad.}
{110}{}{To brzmi bardzo podejrzanie. Jak za³o¿enia dla nowej kretyñskiej kreskówki.}
{111}{}{CO? NOWEJ KALIFORNII? ŒWIAT ZMIENI£ SIÊ A¯ TAK BARDZO? Aaaaaaaaaaa! [pogr¹¿a siê w panice]}
{112}{}{Hej, chwileczkê...}
{113}{}{Œwiat siê bardzo zmieni³, prawda? Muszê iœæ i sprawdziæ co siê zmieni³o. Powodzenia, przyjacielu!}
{114}{}{Nawzajem, panie Stodgers!}
{115}{}{Odkrywasz kolejne ukryte powi¹zanie z kultur¹ masow¹.}
{116}{}{Zzzzzzzzzzz.}
