{100}{}{Widzisz lepiącego i pocącego się faceta.}
{101}{}{Widzisz Erica.}
{102}{}{Widzisz lepiącego i pocącego się faceta. Wygląda trochę żałośnie.}
{103}{}{Tak jakby miastu były potrzebne jeszcze inne kłopoty. Tak jakbym *ja* ich jeszcze potrzebował.}
{104}{}{No właź już! Zamknij za sobą drzwi! Nie wpuszczaj much!}
{105}{}{Duch? F-f-f!}
{106}{}{Dobra, dobra. Nie trzeba tak krzyczeć.}
{107}{}{Ty na mnie krzyczysz?}
{108}{}{Wpuszczę do środka tyle cholernych much, ile tylko mi się spodoba. Palant.}
{109}{}{Dobra. Na razie.}
{110}{}{Zamknij drzwi! Proszę! Odejdź i zabierz ze sobą te wszystkie cholerne muchy!}
{111}{}{Oki!}
{112}{}{Przepraszam. Jestem troszkę zdenerwowany. Te wszystkie cholerne muchy i brak klimatyzacji. Gdybym tylko miał trochę więcej mocy, to mógłbym je wykurzyć... ale nie mam..}
{113}{}{Kim jesteś?}
{114}{}{Skąd bierzesz zasilanie?}
{115}{}{Dlaczego te muchy przylatują?}
{116}{}{Wiesz co, mógłbyś po prostu spróbować się wykąpać.}
{117}{}{Twój pech, stary. Żegnaj.}
{118}{}{Hmm. Szkoda. Na razie.}
{119}{}{W centrum jest elektrownia, która kontroluje energię dla miasta. Będę wdzięczny, jeśli pójdziesz tam i zdobędziesz dla mnie zezwolenie na puszczenie mi trochę więcej energii dla mojego systemu wentylacji.}
{120}{}{Jak wdzięczny? Kasa czy sprzęt?}
{121}{}{Dobra, zrobię to dla ciebie.}
{122}{}{Nie mam czasu. Może później.}
{123}{}{Zwariowałeś? Nie ma mowy. Może w końcu od tej żałosności zdechniesz. Zrobisz światu przysługę.}
{124}{}{Wlatują tu, bo z jakiegoś powodu wydzielam muszą pożywkę. Moje ciało jest dla nich bogate w pożywienie, a pocenie tylko pogarsza sprawę.}
{125}{}{To po prostu wredne. Czemu nie weźmiesz kąpieli, albo czegoś takiego?}
{126}{}{A więc zrobię ci przysługę i cię zabiję.}
{127}{}{Rozumiem. To wszystko, co muszę wiedzieć. Do zobaczenia.}
{128}{}{Próbowałem. Próbowałem wszystkiego. Jedyny sposób, który utrzymuje muchy z dala, to nie pocić się... A ponieważ nie mam wystarczająco energii do ochłodzenia się, po prostu nie mogę tego opanować.}
{129}{}{Rozumiem. Mam inne pytania.}
{130}{}{Rozumiem. Do widzenia.}
{131}{}{Tak?}
{132}{}{Brian rozmawiał ze mną i powiedział, że przydziały energetyczne są tak napięte, że zapewne nie byłby w stanie zwiększyć twojej części.}
{133}{}{Dlaczego przylatują te muchy?}
{134}{}{Próbowałeś się wykąpać?}
{135}{}{Gdzie jest generator prądu?}
{136}{}{Kim jesteś?}
{137}{}{Jest tu o wiele przyjemniej. Wygodnie?}
{138}{}{Nic takiego. Nie zawracaj sobie głowy.}
{139}{}{Mógłbym coś dla ciebie za to uzbierać. Nie mogę obiecać wiele, ale przecież to nie jest też duża przysługa.}
{140}{}{Umowa stoi. Tylko upewnij się, że będziesz coś dla mnie miał, gdy już zdobędę dla ciebie ten prąd.}
{141}{}{Zrobię to za darmo. Bez zapłaty.}
{142}{}{Zapomnij. Nie chcę tego robić.}
{143}{}{Pozwól, że się nad tym zastanowię.}
{144}{}{Nie potrafię wyrazić, jak wdzięczny jestem ci za to. Proszę, daj mi znać, gdy tylko skończysz, abym mógł podkręcić klimatyzację i wziąć kąpiel.}
{145}{}{Zrobi się. Mam jeszcze inne pytania.}
{146}{}{Zrobi się. Na razie.}
{147}{}{Proszę, nie czekaj z tym zbyt długo... Naprawdę robi mi się już niedobrze od tych wszystkich much.}
{148}{}{Jasne. Mam jeszcze inne pytania.}
{149}{}{Jasne. Dam ci znać.}
{150}{}{Wielkie dzięki za twoje ogromne poświęcenie. To sarkazm, jeśli jeszcze tego nie widzisz. Wynocha z mojego domu.}
{151}{}{A dlaczego to ty nie pójdziesz do diabła i wykitujesz?}
{152}{}{Na razie, muchołapie!}
{153}{}{Generator prądotwórczy jest po twojej lewej zaraz jak wejdziesz do Broken Hills z zewnątrz. Szefuje tam gość o imieniu Brian, leniwy sukinsyn, który pracuje możliwie jak najmniej.}
{154}{}{Wygląda na to, że musi dużo pracować. Dzięki. Mam inne pytania.}
{155}{}{Dzięki. Cóż, to na razie wszystko.}
{156}{}{Jestem Eric. Kiedyś prowadziłem hotel w tym miasteczku, ale musiałem go sprzedać ze względu na mój problem z muchami. Oprócz tego prowadziłem pub, ale z tego też musiałem zrezygnować, z tego samego powodu. Na końcu sterowałem generatorem, ale muchy wciąż do niego właziły.}
{157}{}{To cholernie dużo zajęć. Mam też inne pytania.}
{158}{}{Rozumiem. Na razie!}
{159}{}{Powiedział tak, co? Cóż, powiedz mu, że ten generator jest na uran, i że potrzebna mi energia praktycznie nawet nie ruszy strzałki na amperomierzu. I powiedz mu, że chcę mojego prądu!}
{160}{}{Zrobi się! Niezła mowa!}
{161}{}{Powiem mu. Mam też inne pytania.}
{162}{}{Jasne. Na razie.}
{163}{}{Udało ci się z generatorem? Dziękuję ci, bardzo dziękuję. Nawet nie mogę opisać, jaki jestem ci wdzięczny.}
{164}{}{Najczęstsze sposoby wyrażania wdzięczności to prezenty z pieniędzy i sprzętu.}
{165}{}{Nie ma sprawy. To mi wystarczy.}
{166}{}{Mutant Francis ma mocarną pięść. Wciąż obstawia ją w pojedynkach na bary. Problem polega na byciu silniejszym od niego. Jeśli cię to interesuje, to mogę ci dać pewne pigułki, które powinny dać ci nad nim przewagę.}
{167}{}{Jasne.}
{168}{}{Wolę szmal, jeśli go masz.}
{169}{}{Nie chcę nagrody.}
{170}{}{Te pigułki nazywają się buffout. Podniosą twoją siłę, ale i twój umysł trochę na tym ucierpi. Nie bierz za dużo, albo zetnie cię z nóg. Powodzenia z pięścią!}
{171}{}{Dzięki! Na razie!}
{172}{}{Sądzisz, że możesz pomóc mi z moim muszym problemem. Byłbym bardzo wdzięczny.}
{173}{}{Jak wdzięczny?}
{174}{}{Jasne.}
{175}{}{Pozwól, że się nad tym zastanowię.}
{176}{}{Nigdy w życiu!}
{177}{}{Oto wszystkie pieniądze, które mam... 150$. Dziękuję.}
{178}{}{Nie, to ja dziękuję. Na razie.}
{179}{}{Więc jestem podwójnie wdzięczny. Ach... Słyszałem, że poszukujesz GECKa. Spróbuj popytać w RNK. To na południe.}
{180}{}{Dzięki! Na razie!}
{181}{}{A tak. Napór much nieco zelżał, powietrze jest chłodne, a ja mniej spocony. Lepszy układ dla wszystkich dookoła!}
{182}{}{Rzekłeś. Cóż, to wszystko. Na razie!}
{183}{}{Widzisz lepiącego i pocącego się faceta. Wygląda na to, że jest mu całkiem wygodnie.}
