{100}{}{Widzisz niskiego, ¿wawego d¿entelmena.}
{101}{}{Widzisz Mickyego, poszukiwacza skarbów.}
{102}{}{Ten bardzo niski cz³owiek wygl¹da przyjacielsko i odwa¿nie. Jego spojrzenie przeszukuje otoczenie, jakby szukaj¹c œwiec¹cych przedmiotów.}
{103}{}{Witaj, przyjazna duszo! Nie wpad³y ci gdzieœ tu w oko jakieœ klejnoty, albo wartoœciowe metale?}
{104}{}{Kolejny ju¿ raz zaszczycasz mnie swoj¹ obecnoœci¹. Czy le¿¹ tu gdzieœ jakieœ ukryte skarby, o których dobrze by³oby wiedzieæ?}
{105}{}{A wiêc szukasz jakichœ kosztownoœci? Jestem w tym najlepszy z najlepszych!}
{106}{}{Nie skaaaarby dziiisiaj.}
{107}{}{Ta. Moja chcieæ pomóc.}
{108}{}{Kto twoja?}
{109}{}{Pa pa.}
{110}{}{Nie, nie dzisiaj. Je¿eli jednak natrafiê na jakieœ, natychmiast ciê o nich powiadomiê.}
{111}{}{No có¿, owszem. S¹dzê, ¿e jesteœ doskona³ym partnerem do, nazwijmy to, "joint venture".}
{112}{}{Jak siê nazywasz?}
{113}{}{Niewa¿ne.}
{114}{}{Ja? Jestem Micky, szarmancki i uroczy poszukiwacz skarbów z Broken Hills.}
{115}{}{Possssszukiwacz?}
{116}{}{Pa pa.}
{117}{}{Poszukiwacz skarbów?}
{118}{}{Jak mi³o. Uszanowanie.}
{119}{}{Nie mów, ¿e nie znasz mojego imienia! Nigdy nie opowiadano ci historii o Szybkim Mickym? O potyczkach strzeleckich, pojedynkach bokserskich i z³owrogich grabie¿ach?}
{120}{}{Nie.}
{121}{}{Obawiam siê, ¿e nie dane mi by³o o tym us³yszeæ.}
{122}{}{Có¿, du¿o tracisz, przyjazna duszo. Któregoœ dnia bêdê ci musia³ to wszystko opowiedzieæ w najkrwawszych szczegó³ach.}
{123}{}{Doobreee.}
{124}{}{Bêdê czekaæ z zapartym tchem.}
{125}{}{No có¿. Chyba nie powinienem siê temu dziwiæ. Rynek pracy dla poszukiwaczy skarbów w ostatnich latach bardzo siê skurczy³. Ta ca³a œmieræ, g³ód i walka o przetrwanie przyt³umi³y w ludziach chêæ przygody. Je¿eli jednak coœ wyp³ynie, pamiêtaj o mnie.}
{126}{}{Oki-doki.}
{127}{}{Bêdziesz pierwszy na mojej liœcie.}
{128}{}{Naprawdê?! To wspaniale! Co to bêdzie? Z³oto? Klejnoty? Œwiête artefakty?}
{129}{}{Du¿a szmal.}
{130}{}{Newa¿na.}
{131}{}{Wygl¹da na to, ¿e du¿o pieniêdzy. Wystarczaj¹co, aby ¿yæ wygodnie przez d³ugi czas.}
{132}{}{Có¿, chyba jeszcze trochê popracujê nad tym samodzielnie.}
{133}{}{Super! To jest w³aœnie prze³om, na który czeka³em. Co powiesz na 50/50, partnerze?}
{134}{}{Ta!}
{135}{}{Ni. Pa.}
{136}{}{Ach, jasne.}
{137}{}{Z drugiej strony sprawdzê, czy nie zdobêdê tego samodzielnie. Na razie.}
{138}{}{Wspaniale! Jak to by³o? Gdzie s¹ ci Ÿli? Co mam robiæ?}
{139}{}{Twoja ze mn¹! Iœæ ciemna miejsce.}
{140}{}{Powiedzmy, ¿e spêdzisz trochê czasu w miejscowych "jaskiniach".}
{141}{}{Fajowo! Po prostu poka¿ mi odpowiedni kierunek!}
{142}{}{Gdzie skarba? Œrodka miasto?}
{143}{}{Có¿, nie mam pewnoœci. Powiedziano mi, ¿e mogê znaleŸæ skarb gdzieœ tutaj.}
{144}{}{Co? W centrum? Ha! Ktokolwiek ci to powiedzia³ albo k³amie, albo jest szalony. Poza kilkoma zapad³ymi melinami w Broken Hills by³em ju¿ wszêdzie i nic nie znalaz³em. Tak naprawdê to myœlê o ruszeniu dalej.}
{145}{}{Szkooooda. Pa pa.}
{146}{}{Wielka szkoda. Jakieœ wskazówki bardzo by mi siê przyda³y. Có¿, do zobaczenia.}
