{100}{}{Widzisz starego mutanta wyglądającego na twardziela.}
{101}{}{Widzisz Zaiusa, sztygara kopalni.}
{102}{}{Widzisz twardego, starego mutanta z kilofem i kaskiem górniczym.}
{103}{}{To ty jesteś tą nową osobą w mieście w mieście?}
{104}{}{Ik, ug og!}
{105}{}{Nowa! Ja! Osoba!}
{106}{}{Dokładnie.}
{107}{}{Tak, wpadłem tu na jakiś czas.}
{108}{}{Nie, geniuszu. Żyję tu od lat, a ty mnie po prostu nie zauważyłeś.}
{109}{}{Wiem o waszym problemie z kopalnią.}
{110}{}{Co możesz mi powiedzieć o tym miejscu?}
{111}{}{Ummm... dobra. Coś ci powiem. Masz tu parę dolców. Idź do saloonu i kup sobie coś do picia.}
{112}{}{Yagga? Ogg? Gronk!}
{113}{}{Nie rozumiem cię. Czemu nie pójdziesz do saloonu? Do diabła, może Francis się z tobą posiłuje.}
{114}{}{Łuje? O-KEJ!}
{115}{}{Dobrze. Cóż, jestem Zaius. Skoro się już przedstawiliśmy... Znasz się na naprawianiu? Mamy problem z naszym systemem oczyszczania powietrza na dolnym poziomie kopalni, ale nie mamy części, by go naprawić ani sprzętu, który ochroniłby nas przed gazem radonowym.}
{116}{}{Nie znam się na tym. Przykro mi.}
{117}{}{Nie wygląda na trudne. Co muszę zrobić?}
{118}{}{Cóż, mam nadzieję, że podoba ci się w Broken Hills.}
{119}{}{[dalej]}
{120}{}{Cha. Cha. Bardzo śmieszne. Potrzebujemy jakiegoś spryciarza do rozwiązania problemu.}
{121}{}{Mam więcej sprytu niż ktokolwiek inny na tym zadupiu.}
{122}{}{Och? Macie problem? Jaki?}
{123}{}{Głównym problemem jest twoja głupota.}
{124}{}{Można powiedzieć, że mam trochę sprytu. Jaki macie problem?}
{125}{}{Zepsuł się nasz filtr powietrza. Jest na dolnym poziomie. Nie mamy części ani sprzętu ochronnego. Bez części nie możemy go naprawić. Bez ochrony, dopadnie nas gaz radonowy. Znasz się na naprawianiu?}
{126}{}{Chyba tak.}
{127}{}{Niespecjalnie.}
{128}{}{Znowu ty, co?}
{129}{}{Ork! Uuu! Ug ug!}
{130}{}{Cześć! CZEEEŚĆ! Ja }
{131}{}{Dałem ci już pieniądze. Idź poprzeszkadzać komuś innemu, co?}
{132}{}{Witaj ponownie. Czemu nie pójdziesz... umm... do banku w mieście? Jestem pewien, że wielu ludzi z radością z tobą pogada.}
{133}{}{Jeśli wymyślisz jakiś sposób, daj mi znać.}
{134}{}{Naprawdę? Zrobisz to dla mnie... i, co ważniejsze, dla Broken Hills?}
{135}{}{Co będę z tego mieć?}
{136}{}{Pewnie, zrobię tak.}
{137}{}{Nie teraz.}
{138}{}{Doprawdy? Cóż, mądralo, czemu nie naprawisz filtru powietrza? Potrzebujesz tylko części i sposobu, jak poradzić sobie z gazem. Dopóki nie pokażesz mi, że potrafisz to zrobić, uznam chyba, że potrafisz tylko gadać.}
{139}{}{Co będę z tego mieć?}
{140}{}{Pewnie, zrobię tak.}
{141}{}{Chyba żartujesz?}
{142}{}{Głównym problemem jest moja głupota. Powtarzam to, bo nie wierzę, że twoja dupa wypierdziała coś, co brzmiało jak słowa. Zejdź mi z oczu, palancie.}
{143}{}{Oprócz zanudzających mnie palantów, głównym problemem jest system oczyszczania powietrza w kopalni. Zepsuł się, a my nie mamy sprzętu, który ochroniłby nas przed gazem radonowym, ani części, by go naprawić. Ale ty możesz go naprawić, z twoją wielką inteligencją?}
{144}{}{Co będę z tego mieć?}
{145}{}{Pewnie, zrobię tak.}
{146}{}{Chyba żartujesz? W życiu.}
{147}{}{. Co ty na to?}
{148}{}{Za mało, chcę więcej.}
{149}{}{Jak dla mnie może być.}
{150}{}{Zapomnij o tym. Idę stąd.}
{151}{}{Świetnie! Oczywiście musisz zdobyć części. Idź do Nowego Reno i poszukaj Renesco. Ma w sklepie kupę narzędzi. Powiedz mu, że przysłał cię Zaius. Przekaż mu, że powiedziałem "Kanarek kopnął w kalendarz". Nie wiem, gdzie znajdziesz coś, co ochroni cię przed gazem. Możesz iść bez tego, ale odniesiesz wtedy obrażenia. Jeszcze raz ci dziękuję.}
{152}{}{Nie ma sprawy. Cześć.}
{153}{}{Nie? Cóż, jeśli zmienisz zdanie, wiesz, gdzie mnie znaleźć.}
{154}{}{W porządku. Do widzenia.}
{155}{}{ - niech będzie więc tyle. Weź na razie połowę. Drugą połowę dam ci, gdy skończysz. Idź do Nowego Reno i znajdź Renesco. Ma tam kupę narzędzi. Powinien pomóc ci w zdobyciu części.}
{156}{}{Cześć.}
{157}{}{Przykro mi. Więcej nie dam. Bierzesz tyle albo nic.}
{158}{}{W porządku.}
{159}{}{Nie ma mowy.}
{160}{}{Nie bierzesz? Jak chcesz.}
{161}{}{Jak chcesz.}
{162}{}{Cześć, przyjacielu! }
{163}{}{Och, to znowu ty. }
{164}{}{Jak się masz.}
{165}{}{Wiesz, wiedziałem, że te skurwysyny Franc, Manson, Jacob i Aileen coś szykowali. Dobra robota! A więc... }
{166}{}{Mam nadzieję, że myślisz już nad sposobem odzyskaniu rudy... A więc...}
{167}{}{Dzięki za sprzedanie rudy. Nie znaczy to, że nie moglibyśmy jej użyć. A więc...}
{168}{}{Dzięki za odzyskanie tej rudy. Nawet nie wiesz, jak ciężko na nią pracujemy.}
{169}{}{Czego potrzebujesz?}
{170}{}{Możesz opowiedzieć mi o mieście?}
{171}{}{Wiem o waszym problemie z kopalnią.}
{172}{}{Jak leci?}
{173}{}{Jak wam idzie z ludźmi?}
{174}{}{Może jednak zmieniłeś zdanie i chcesz naprawić kopalnię?}
{175}{}{Co będę z tego mieć?}
{176}{}{Pewnie, zrobię tak.}
{177}{}{Nie teraz.}
{178}{}{Nie.}
{179}{}{Jak ci idzie? Mam nadzieję, że wkrótce sobie z tym poradzisz...}
{180}{}{Idzie mi dość dobrze.}
{181}{}{Mam kupę zajęć. Jeszcze się za to nie zabrałem.}
{182}{}{Niedługo dam ci znać.}
{183}{}{Masz te części? Świetnie... Mam nadzieję, że masz jakiś sprzęt ochronny. Nie wiem, czy poradzisz sobie z gazem.}
{184}{}{Mogę ruszać.}
{185}{}{Niedługo się tym zajmę.}
{186}{}{Masz te części? Świetnie... Mam nadzieję, że masz jakiś sprzęt ochronny. Nie wiem, czy poradzisz sobie z gazem.}
{187}{}{Mogę ruszać.}
{188}{}{Niedługo się tym zajmę.}
{189}{}{Udało ci się? Świetnie! Wiem, że to miała być robota za darmo, ale nie pozwolę na to. Pogadałem z chłopakami i zrzuciliśmy się na tę strzelbę bojową. Powodzenia - i dziękujemy.}
{190}{}{Żaden problem. Dzięki!}
{191}{}{Naprawiłeś? Świetnie! Jak się umówiliśmy, to pozostała część zapłaty. Jeszcze raz dziękuję.}
{192}{}{Ty skurwielu. Teraz umrzesz.}
{193}{}{Dobra, dobra. Lepiej się jednak pośpiesz... Nasze miasto tego potrzebuje.}
{194}{}{Jasne. Na razie.}
{195}{}{Nie popędzaj mnie. Mam dużo zajęć, palancie.}
{196}{}{Cóż, przykro mi, Wasza Wysokość, ale chyba przetrwanie miasta jest trochę ważniejsze. Pośpiesz się wreszcie.}
{197}{}{Dobra. Zajmę się tym.}
{198}{}{Przegiąłeś. Żegnaj, trupie.}
{199}{}{Proszę, pośpiesz się. Od kopalni zależy nasze życie.}
{200}{}{Dobra już, dobra.}
{201}{}{Cóż, najlepiej pogadaj o tym z Marcusem, znajdziesz go koło banku, albo ze Stevem przy wejściu do miasta - robi tam za "Szwajcara".}
{202}{}{Hmm. Dobrze, dziękuję.}
{203}{}{W takim razie zapytam ich.}
{204}{}{Jest porządku. Ale... mogłoby być lepiej.}
{205}{}{Heh. Dzięki za informacje.}
{206}{}{Cóż, skoro mutanci nie starzeją się i nie starzeją się -- gaz sprawia że nadal są młodzi, czy jakoś tak.
 Muszę powiedzieć, że jest całkiem nieźle. To znaczy, nie chcemy zabijać wszystkich, a z tego co wiem, ludzie nie mają o nas zbyt złego zdania. Oczywiście, to nie dotyczy ludzi
 z innych miejsc w okolicy... To dopiero są dranie.}
{207}{}{Dobra, dzięki. Na razie.}
{300}{}{. Co ty na to?}
{301}{}{. Co ty na to?}
{302}{}{$}
{381}{}{Jestem kobietą pracującą. Jeszcze się za to nie zabrałam.}
{382}{}{Nie popędzaj mnie. Jestem bardzo zajęta, palancie.}
{383}{}{Cóż, przykro mi, Wasza Wysokość, ale przetrwanie miasta jest chyba trochę ważniejsze. Lepiej się więc pośpiesz.}
{400}{}{Mam kartkę, na której jest twoje imię. Znalazłem ją przy martwej kobiecie w tunelach. Co na to powiesz?}
{401}{}{Hej, właśnie ją otrzymałem. Pogadaj o niej z Francisem, dobra? To on ją napisał.}
{402}{}{Jeśli maczałeś palce w zabiciu tych ludzi, chcę o tym wiedzieć.}
{403}{}{Dobra. Na razie.}
{404}{}{Nie! Chronimy się jedynie przed spiskiem. Marcus wierzy w prawo i dowody, i choć wie, że ci ludzie są niebezpieczni, nie wie, kim są - a jest zbyt honorowy, aby podłożyć dowody. Ja jedynie powstrzymuję Francisa przed totalną zemstą.}
{405}{}{Nie brzmi to zbyt przekonywująco. Jeszcze pogadam z Francisem.}
{406}{}{Wiedziałem, że Francis nie wytrzyma. Znał ryzyko swego czynu, ale chyba nigdy nie przypuszczał, że zostanie schwytany. Ale chyba będzie z nim dobrze. Mam nadzieję, że tak samo będzie z Broken Hills.}
{407}{}{Ja też. Mam parę pytań.}
{408}{}{Ja też. Do widzenia.}
{1130}{}{!}
