{100}{}{Widzisz niechlujnego mê¿czyznê w bardzo brudnym ubraniu.}
{101}{}{Widzisz Aldo, lokalny komitet powitalny. Czujesz jego oddech nawet z tej odleg³oœci.}
{200}{}{Witam serdecznie, pierwszy raz w Klamath, prawda? Jestem Aldo. (czka) Moim zadaniem jest witanie podró¿nych i udzielanie informacji na temat lokalnych atrakcji. Witamy w Klamath. (czka) Czym siê zajmujesz?}
{201}{}{Umm, dziêki za powitanie. Podró¿ujê tu i ówdzie.}
{202}{}{Jestem }
{203}{}{. Dziêki za powitanie.}
{204}{}{ z Arroyo. Jestem Dzieckiem Przeznaczenia.}
{205}{}{Mojej imiê nie powinno ciê interesowaæ. Spadaj st¹d, brudny moczymordo.}
{206}{}{Nie wierzê, ¿e takie miasto jak Klamath zatrudni³oby kogoœ takiego jak ty, ¿eby wita³ podró¿ników.}
{300}{}{Dziecko Przeznaczenia! Och, }
{301}{}{, musisz cieszyæ siê przeogromnym szacunkiem wœród swojego ludu. Jestem pewien, ¿e ktoœ o twojej pozycji (czka) chêtnie wspomo¿e biednego cz³owieka choæby grosikiem. (czka)}
{302}{}{Dam ci dobr¹ radê - trzymaj siê z dala od wódy.}
{303}{}{Grosik, tak? Chyba warto, jeœli siê wreszcie ode mnie odczepisz. Masz tu $5}
{304}{}{Có¿, jeœli rzeczywiœcie jesteœ taki biedny. Czy $5 wystarczy? }
{305}{}{To ty powinieneœ mi zap³aciæ za to, ¿e nie rozsmarujê twoich wnêtrznoœci po tej ulicy.}
{306}{}{Przykro mi, Dziecko Przeznaczenia nie zawraca sobie g³owy tak przyziemnymi sprawami jak pieni¹dze.}
{350}{}{Có¿ }
{351}{}{, poniewa¿ goœcisz tu pierwszy raz (czka) i najwyraŸniej nie wiesz jak zachowaæ siê w wielkim mieœcie, podpowiem ci, ¿e w dobrym tonie jest daæ napiwek komitetowi powitalnemu zanim zaczniesz zadawaæ pytania.}
{355}{}{Szkoda na ciebie moich pieniêdzy.}
{400}{}{Poniewa¿ goœcisz tu pierwszy raz (czka) i najwyraŸniej nie wiesz jak zachowaæ siê w wielkim mieœcie, podpowiem ci, ¿e w dobrym tonie jest daæ napiwek komitetowi powitalnemu zanim zaczniesz zadawaæ pytania.}
{450}{}{Dziêki za pieni¹dze, przyjacielu. (czka) Kupiê za nie jakieœ lekarstwo na moje biedne, wysuszone gard³o. To chyba tyle, jeœli chodzi o czêœæ oficjaln¹. Witaj w Klamath. Masz mo¿e jakieœ pytania co do lokalnych atrakcji?}
{451}{}{Nie, dziêkujê. Chyba dam sobie jakoœ radê bez twojej pomocy.}
{452}{}{Prawdê mówi¹c, mam kilka pytañ.}
{453}{}{Aldo, szukam kupca, który sprzedaje rzeczy sprzed wojny. No wiesz, zabytki...}
{500}{}{Pytaj, dobroczyñco.}
{501}{}{Czym zajmuj¹ siê ludzie w Klamath?}
{502}{}{Gdzie mogê coœ kupiæ i znaleŸæ medyka?}
{503}{}{Opowiedz mi o gekonach.}
{504}{}{Gdzie tu mo¿na kupiæ alkohol?}
{505}{}{Dziêki. Nie potrzebujê wiêcej informacji.}
{506}{}{Wiesz mo¿e, gdzie mogê znaleŸæ GECKa?}
{550}{}{Niech ciê diabli. Mam nadziejê, ¿e d³ugo tu nie zabawisz. Nie potrzebujemy tu takich jak ty. Cholerne dzikusy - wszyscy s¹ tacy sami.}
{600}{}{W Klamath? Niektórzy uprawiaj¹ ziemiê, niektórzy hoduj¹ byd³o, ale najczêœciej poluj¹ na gekony.}
{601}{}{Gekony? Co to takiego?}
{602}{}{Dziêki. To ju¿ chyba wszystko.}
{603}{}{Interesuj¹ce. Mam jeszcze jedno pytanie.}
{650}{}{Gekon to taka du¿a jaszczurka. Tutejsi myœliwi poluj¹ na nie dla miêsa i skór. Ale te cholery wcale nie daj¹ siê ³atwo z³apaæ, jeœli wiesz co mam na myœli. Pos³uchaj mojej rady i omijaj je z daleka. To zbyt niebezpieczne.}
{651}{}{Dziêki. To ju¿ chyba wszystko.}
{652}{}{Hmm. Jeszcze jedno, Aldo.}
{700}{}{Handlowaæ mo¿esz u Bucknerów i w Z³otym Gekonie. Czasem maj¹ tam nawet zio³a lecznicze - chocia¿ na moj¹ chorobê nie znaleŸli jeszcze lekarstwa. Obydwa lokale prowadz¹ straszne sknery. Spróbuj wzi¹æ coœ na kreskê, a wykopi¹ ciê za drzwi.}
{701}{}{Dziêki za informacje. To ju¿ chyba wszystko.}
{702}{}{Osobiœcie nie mam nic przeciwko spaniu pod go³ym niebem. Hmm, mam jeszcze jedno pytanie.}
{750}{}{Wiem, ¿e niechêtnie myœlisz o wynagrodzeniu komitetu powitalnego, ale (czka)mo¿e teraz zmienisz zdanie i zgodzisz siê na oficjalne powitanie w Klamath.}
{751}{}{Dam ci $5 jeœli tylko siê ode mnie odczepisz.}
{752}{}{Ten moment musia³ nast¹piæ prêdzej czy póŸniej. Masz tu $5. Mo¿esz zacz¹æ mnie witaæ.}
{753}{}{Nie skorzystam. Nie potrzebujê oficjalnego powitania.}
{754}{}{A mo¿e twoje flaki chcia³yby powitaæ mój nó¿?}
{800}{}{Witaj ponownie! Mo¿e zechcesz wspomóc mnie finansowo. Zbieram pieni¹dze na zakup lekarstwa. Moje gard³o wysycha w b³yskawicznym (czka) tempie. Jeœli chcesz, zorganizujê dla ciebie nastêpne oficjalne powitanie.}
{801}{}{Czemu nie. Masz tu $5 na lekarstwo.}
{802}{}{Przykro mi, Aldo. Mo¿e innym razem.}
{803}{}{Chyba masz ju¿ doœ tego 'lekarstwa'. WeŸ siê lepiej do uczciwej pracy - bêdziesz zdrowszy.}
{810}{}{Niech ciê szlag. Jak mo¿na tak okrutnie traktowaæ chorego cz³owieka? Dzikus bez serca! (Aldo spluwa na ziemiê przed tob¹. Niestety nie udaje mu siê unikn¹æ oplucia w³asnej brody)}
{820}{}{Zapewniam ciê, ¿e pomoc udzielona komuœ tak potrzebuj¹cemu jak ja przyniesie ci (czka) du¿o szczêœcia. Mam nadziejê, ¿e jeszcze siê spotkamy.}
{830}{}{Ach, jak bardzo przyda³y by mi siê pieni¹dze na lekarstwo. No ale skoro (kaszle) mówisz, ¿e nie mo¿esz sobie (kaszle) na to pozwoliæ, to oczywiœcie rozumiem. Mo¿e innym razem (kaszle) jeœli do¿yjê.}
{850}{}{Masz na myœli moje kochane lekarstwo? (czka) Kiedyœ kupowa³em je albo pod Z³otym Gekonem, albo u Bucknerów, ale teraz nie chc¹ mi ju¿ sprzedawaæ na kredyt. Na szczêœcie Bob Flacha sporz¹dza odrobinê lekarstwa na potrzeby swoje i znajomych.}
{851}{}{Cieszê siê, ¿e znalaz³eœ Ÿród³o... lekarstwa. To ju¿ chyba wszystko co chcê wiedzieæ.}
{852}{}{Ciekawe. A gdzie mogê znaleŸæ tego Boba Flachê?}
{853}{}{Dziêki, Aldo. Mam jeszcze jedno pytanie.}
{860}{}{Bob przesiaduje zwykle u Bucknerów, tu niedaleko. Ale chyba od jakiegoœ czasu nie zagl¹da³ do swojej aparatury. To niezbyt sta³e Ÿród³o, jak dla kogoœ o moim s³abym zdrowiu.}
{861}{}{Dziêki za informacje, Aldo. To chyba wszystko co chcê wiedzieæ.}
{862}{}{Dobrze, ¿e znalaz³eœ innego dostawcê. Czy móg³byœ... tak mocno nie chuchaæ? Dziêki. Mam jeszcze jedno pytanie.}
{870}{}{Witaj, przyjacielu - wygl¹dasz na kogoœ, komu przyda³ by siê przyjaciel. Jestem Aldo, lokalny komitet powitalny.}
{871}{}{Przyjaciel? He, he, }
{872}{}{ lubi przyjaciel.}
{873}{}{Urk, (niuch, niuch) z³y zapach. IdŸ sobie.}
{880}{}{Jak mi dasz $20 zostanê twoim przyjacielem. I wszyscy inni te¿ bêd¹ twoimi przyjació³mi. Tak to ju¿ jest w du¿ym mieœcie.}
{881}{}{Dwa-cie-œcia? Uuk? Duuu¿a Cia-sto? Uuk?}
{882}{}{Daæ listek, taa?}
{890}{}{GECK? Mo¿e gekon? O GECKu nic mi nie wiadomo, ale mogê ci opowiedzieæ o gekonach.}
{900}{}{Zabytki, hê? (czka) No... Jedyny kupiec w tej bran¿y, jakiego znam, to stary Vic.}
{901}{}{Vic? Gdzie go mogê znaleŸæ?}
{910}{}{A to ju¿ inna kwestia (czka), jakoœ go ostatnio nie widujê. Nie bardzo wiem, gdzie go teraz (czka) szszsz... (czka) szukaæ. Pogadaj z Jenny z £aŸni. Ona i Vic byli ca³kiem blisko, dos³ownie i w przenoœni. He, he, he. Chwytasz? I w przenoœni! Jeszcze nie straci³em poczucia humoru.}
{911}{}{Musia³byœ je najpierw mieæ... Pozwól, ¿e zaryzykujê jeszcze jedno pytanie.}
{912}{}{Wielkie dziêki, jesteœ jedyny w swoim rodzaju Aldo. To ju¿ chyba wszystko. Trzymaj siê.}
{920}{}{Witam ponownie mojego przyjaciela. Masz kolejne 20 dolarów do stracenia, aby nasza przyjaŸñ nadal kwit³a?}
{921}{}{Ook.}
{922}{}{Nie moja sprawa. Pa.}
