{100}{}{Widzisz jednego z dwóch bardzo podobnych do siebie mężczyzn - mogliby być bliźniakami. Obaj są dobrze umięśnieni i mają nastroszone brwi.}
{101}{}{Widzisz Chucka, a może Bucka Duntona - obaj są do siebie tak podobni, że nie umiesz powiedzieć, na którego z nich w tej chwili patrzysz.}
{102}{}{Widzisz wysokiego, dobrze umięśnionego mężczyznę. Poniżej krzaczastych brwi dostrzegasz twarz powykręcaną w typowy dla awanturnika pogardliwy, acz nieco przygłupi uśmieszek. Mężczyzna wygląda dokładnie tak samo jak jego brat.}
{110}{}{Lepiej stąd zmiataj, albo razem z bratem zrobimy sobie z twojej małej główki grzechotkę.}
{111}{}{Hej, po co się denerwować, tak tylko się rozglądam. Naprawdę przepraszam. Proszę, nie bijcie mnie. Poza tym, mam do was jedno pytanie.}
{112}{}{Uch, przepraszam pana, panie Dunton. Lepiej już pójdę.}
{113}{}{Potrzebuję informacji i lepiej będzie, jeśli mi powiecie wszystko, co chcę wiedzieć.}
{114}{}{Razem z bratem? Zbyt się boisz, żeby wziąć się za mnie w pojedynkę?}
{120}{}{Zmiataj stąd, zanim zrobimy z ciebie siekane kotlety.}
{121}{}{Hej, naprawdę przepraszam, nie było moją chęcią was złościć. Taka już moja głupota. Wrócę później, kiedy nie będzie już wam się chciało rzygać na mój widok.}
{122}{}{Och, dobrze, przepraszam. Proszę, nie bijcie mnie.}
{123}{}{Przynajmniej uniknę patrzenia na te wasze obrzydliwe mordy.}
{130}{}{Co chcesz od nas wiedzieć?}
{131}{}{Myślę, że nic ci nie musimy mówić. A tak w ogóle, to czego u licha chcesz?}
{132}{}{A tak w ogóle, to czego chce od nas to małe nie wiadomo co?}
{133}{}{Czy któryś z was słyszał cokolwiek o czymś, co nazywa się Generator Ekosystemu Cudownej Krainy?}
{134}{}{Chcę dokonać wymiany.}
{135}{}{Jest tu coś do roboty?}
{136}{}{Ech, właściwie to który z was jest który?}
{137}{}{Słyszeliście może coś w kwestii okaleczania bramin w tej okolicy?}
{138}{}{W sumie to niczego nie potrzebuję. Żegnam.}
{140}{}{Miarka się przebrała. Myślę, że lepiej będzie, jeśli się stąd wyniesiesz, zanim sami nauczymy cię dobrych manier.}
{141}{}{Przepraszam, ale współpraca z wami jest taka ekscytująca. Już sobie idę. Do widzenia.}
{142}{}{Miarka? Jaka miarka? Przede wszystkim to był wasz pomysł.}
{143}{}{Nie, to wy dwaj jesteście po prostu zbyt zieloni, żeby zrobić to, co należało.}
{150}{}{Ha, mamy pod ręką spory zapas naszego światowej sławy Suszonego Mięsa Duntonów. Smaczne i pożywne - tobie też dobrze zrobi.}
{151}{}{Uch, to świetnie. }
{152}{}{Suszone mięso? To nie wygląda mi na rzecz, której potrzebuję. Pomówmy o czymś innym.}
{153}{}{W sumie chyba nie muszę się wymieniać. Żegnam.}
{160}{}{Daliśmy ci już szansę, .}
{161}{}{Chyba nie ma tu dla ciebie żadnej roboty.}
{162}{}{No więc, jest jedna rzecz, w której przydałaby się pomoc. [he, he, he]}
{163}{}{Co takiego Chuck?}
{164}{}{Co takiego Buck?}
{165}{}{Eee, cóż takiego?}
{166}{}{Jasne. Pomówmy więc o czymś innym.}
{167}{}{Hej, zaczekajcie - naprawdę chcę wam pomóc chłopaki. Opowiedzcie mi jeszcze raz o tej robocie.}
{168}{}{Cóż, gapa ze mnie. Lepiej już pójdę. Żegnam.}
{169}{}{Dobra. Na razie.}
{170}{}{Ty bezwartościowa kupo gekońskiego gówna! Co jeszcze u diabła tutaj robisz?}
{171}{}{Pragnę przeprosić. To nie miało tak wyjść. Po prostu kradzież bydła nie wychodzi mi tak dobrze, jak wam. Poza tym, potrzebuję czegoś od was.}
{172}{}{Macie rację - można było to zrobić dużo lepiej. W przeciwieństwie do was nie mam chyba talentu do kradzieży bydła. Tym niemniej, potrzeba mi czegoś.}
{173}{}{Gekońskiego gówna? Mówicie o tym, co jecie, czy o tym, co macie w głowie?}
{180}{}{Znowu tutaj, co? W czym możemy ci pomóc, partnerze?}
{181}{}{Hej, zdróweńko. Załatwienie tego przygłupa Torra to była naprawdę bułka z masłem, no nie? Pozwól, że wypłacę ci twoją dolę.}
{182}{}{To był niezły interes. Dajcie znać, jak będziecie mieli jeszcze jedną taką robotę. Teraz jednak potrzebuję czegoś innego.}
{183}{}{Jestem tu po moją dolę, partnerzy.}
{184}{}{To, co zrobiliśmy, napawa mnie wstydem. Oszukiwać idiotę? Czemu tak dla odmiany nie dobralibyście się do kogoś, kto się może bronić, tchórze? Żegnam.}
{185}{}{Chyba niczego mi teraz nie potrzeba. Do widzenia.}
{190}{}{Dobra. Oto $50, a także coś ekstra. Kilka porcji Suszonego Mięsa Duntonów. Jeszcze raz dzięki, partnerze.}
{191}{}{Dzięki. Słuchajcie, mam do was jeszcze jedną sprawę.}
{192}{}{Forsa na pewno się przyda. I to, mmm [gryz] też całkiem smaczne mięso. Dzięki. Na razie.}
{198}{}{Dobra, oto układ. Potrzebujemy pomocy w, uch, wyzwalaniu kilku bramin spod władzy tego idioty, Torra. Możesz go tak zakręcić, żeby zostawił braminy, albo go ogłuszyć - tylko nie rób mu za dużej krzywdy, bo będzie chryja.}
{199}{}{Teraz już pamiętam. Dzięki.}
{200}{}{Spotkajmy się na pastwisku bramin, zaraz na wschód od miasta, dziś o 6:00 wieczorem.}
{201}{}{Spotkajmy się na pastwisku bramin, zaraz na wschód od miasta, jutro o 6:00 wieczorem.}
{202}{}{Dobra, zajmę się Torrem.}
{203}{}{Dobra, znajdę Torra na pastwisku i zajmę się nim dla was.}
{204}{}{Chyba jednak nie chcę tego robić.}
{205}{}{Dobra, będę tam. Na razie.}
{206}{}{W międzyczasie mam do was jeszcze kilka pytań.}
{207}{}{Żegnaj.}
{208}{}{Jestem Chuck Dunton. Przymuł jakiś, czy co?}
{209}{}{Jestem Buck Dunton. Przymuł jakiś, czy co?}
{210}{}{Czy wyglądam aż tak źle? Jestem Chuck Dunton.}
{211}{}{Czy wyglądam aż tak źle? Jestem Buck Dunton.}
{212}{}{Co, masz coś z główką? Jestem Chuck Dunton.}
{213}{}{Co, masz coś z główką? Jestem Buck Dunton.}
{214}{}{To cię chyba przerasta. Cholerne dzikusy. Jestem Chuck, jełopo.}
{215}{}{To cię chyba przerasta. Cholerne dzikusy. Jestem Buck, jełopo.}
{216}{}{Jestem Wielkonosa Sally Dunton. Podoba ci się moja sukienka? Jestem Chuck Dunton, wioskowy przymule.}
{217}{}{Jestem Wielkonosa Sally Dunton. Podoba ci się moja sukienka? Jestem Buck Dunton, wioskowy przymule.}
{218}{}{Uch, no dobra. Tak mi się właśnie zdawało. Przepraszam.}
{219}{}{Proszę się nie przejmować. Teraz już wiem. Uch, panie Dunton, potrzebuję czegoś od pana.}
{220}{}{Dobra, wszystko jedno. Słuchaj, powiedz mi po prostu to, co chcę wiedzieć.}
{221}{}{Jejku, ależ wy obaj jesteście głupi i brzydcy. A zresztą, co się będę przejmować, na którego Duntona wydzieram japę. Na razie, dupku.}
{222}{}{Ach, tak. Powiedz mi coś o robocie.}
{230}{}{Dobra rada - ani mru mru komukolwiek. Jak komuś piśniesz choćby słówko, to się pogniewamy. A nie chcesz widzieć, jak się gniewamy.}
{231}{}{Przepraszam, nikomu nie powiem. Obiecuję, panie Dunton. Do widzenia.}
{232}{}{Nie martwcie się, nikomu nie powiem. A teraz pomówmy o czymś innym.}
{233}{}{Nie chcę widzieć, jak się gniewacie? W ogóle nie chcę widzieć waszych wstrętnych mord. Żegnam.}
{240}{}{No, no, interesy z tobą, to czysta przyjemność. He, he, he. Coś jeszcze?}
{241}{}{Hmm... myślę, że mam jeszcze coś na wymianę.}
{242}{}{Tak.}
{243}{}{Nie, to już chyba wszystko, Chuck.}
{244}{}{Nie, to już chyba wszystko, Buck.}
{250}{}{Hej tam, partnerze. Dziś w nocy trzymamy za ciebie kciuki. Co mogę dla ciebie zrobić?}
{251}{}{Uch, po powtórnym przemyśleniu dochodzę do wniosku, że nie chcę pomagać wam dziś w nocy.}
{252}{}{Pewnie, będę tam. Tymczasem jednak pozwólcie, że o coś zapytam.}
{253}{}{Pewnie, że tam będę. Na razie.}
{259}{}{Proszę, proszę, czyż to nie nasz wspaniały mięśniaczek?}
{260}{}{Hej tam. Jak się ma twoje ramię? Masz ochotę na jeszcze jeden razik?}
{261}{}{Hej tam, pętaku. Co robisz w barze? Zanim pozwolimy ci tu zostać, musisz pokazać Duntonom, na co cię stać, siłując się ze mną. [ha, ha, ha]}
{262}{}{Nie wyglądasz na zbyt twardego. Czemu się ze mną nie posiłujesz, Chucku Dunton, o prawo do picia w naszym barze?}
{263}{}{Nie wyglądasz na zbyt twardego. Czemu się ze mną nie posiłujesz, Bucku Dunton, o prawo do picia w naszym barze?}
{264}{}{Hej tam, cukiereczki. Żeby tu siedzieć, musicie sobie zasłużyć. Musisz się zmierzyć z Chuckiem Duntonem, jeśli chcesz pić w tym barze.}
{265}{}{Hej tam, cukiereczki. Żeby tu siedzieć, musicie sobie zasłużyć. Musisz się zmierzyć z Buckiem Duntonem, jeśli chcesz pić w tym barze.}
{266}{}{Zdaje się mamy tutaj rywala. Musisz się zmierzyć z Chuckiem Duntonem, jeśli chcesz pić w tym barze.}
{267}{}{Zdaje się mamy tutaj rywala. Musisz się zmierzyć z Buckiem Duntonem, jeśli chcesz pić w tym barze.}
{268}{}{No dobrze, posiłujmy się. Inaczej się pewnie ode mnie nie odczepisz.}
{269}{}{Chyba nie chcę się z tobą teraz siłować.}
{270}{}{Nie chcę się teraz siłować. Chcę tylko o coś zapytać.}
{271}{}{Uch, chyba jestem nie w tym barze, co trzeba. Żegnam.}
{280}{}{Tym razem jesteś górą. Sprytna z ciebie bestia, no nie? Ruszasz się tak szybko, jak gekon, któremu ktoś podpalił ogon. Niech tam, stawiam pierwszego drinka.}
{281}{}{Dzięki. Może umiesz odpowiedzieć mi na parę pytań.}
{282}{}{To tylko szczęśliwy traf. Dzięki.}
{283}{}{Nie chcę twojego piwa, ale chcę cię o coś zapytać.}
{284}{}{Nie chcę twojego piwa. Żegnam.}
{290}{}{Masz szczęście, mogłem złamać twoje cherlawe ramię jak mały patyczek. [Chłe, chłe, chłe] Więc wciąż nie ma w tym mieście prawdziwego wyzwania.}
{291}{}{Nie dość ci upokarzania, jak na jeden wieczór?}
{292}{}{Zróbmy to jeszcze raz. Tym razem ci pokażę.}
{293}{}{Auć. Dobrze już, dobrze. Mam dosyć. Hej, pozwól, że o coś zapytam.}
{294}{}{Mam już dość. Żegnam.}
{300}{}{Nie chcesz się z nami siłować? Co, bracia Dunton nie są dla ciebie dość dobrzy, żeby się z nimi posiłować?}
{301}{}{Siłując się ze mną, mógłbyś zrobić mi krzywdę.}
{302}{}{Może później. Na razie potrzebuję informacji.}
{303}{}{To nie byłoby uczciwe starcie. Żegnam.}
{304}{}{Jesteś zbyt cherlawy. Siłuję się tylko z prawdziwymi mężczyznami. Odczep się cieniasie.}
{310}{}{Że niby czego szukasz? Jedyna Cudowna Kraina jaką znam, to ramiona ślicznej Jenny z łaźni Mamuśki. [chłe, chłe, chłe]}
{311}{}{Eee, dzięki. Pozwól więc, że zapytam o coś innego.}
{312}{}{To już chyba wszystko co chcę wiedzieć. Żegnaj.}
{320}{}{He, słyszałem, że podobno jakieś [chłe, chłe] skorpioludy podrzynają gardła braminom na wschód stąd. Ale ja bym w to nie wierzył. [chłe, chłe, chłe]}
{321}{}{Och, rozumiem, dzięki. Jest jeszcze coś, o co chcę zapytać.}
{322}{}{To już chyba wszystko co chcę wiedzieć. Żegnaj.}
{330}{}{Hej, człowieku. Przychodzisz, żeby wymienić się na Światowej Sławy Suszone Mięso Duntonów?}
{331}{}{Noo? Kupujesz suszone mięso czy nie?}
{332}{}{Brzmi świetnie. Chcę dokonać wymiany.}
{333}{}{Suszone mięso? Brzmi ciekawie. Opowiedz mi coś na ten temat.}
{334}{}{Właściwie to mam do was kilka pytań.}
{335}{}{Na razie chyba niczego nie potrzebuję. Do widzenia.}
{336}{}{Ciekawią mnie te wszystkie braminy, które macie w zagrodzie. Ich piętna różnią się między sobą.}
{340}{}{Hę? O co ci do diabła chodzi? Wszystkie są nasze.}
{341}{}{Chodzi mi o to, że część z nich wygląda tak, jakby miały wcześniej inne piętna, które ktoś nieudolnie zmienił na nowe.}
{342}{}{Ach, rozumiem. He-he, to pewnie pomyłka. Lepiej już pójdę. Żegnam.}
{343}{}{Cóż, chyba po prostu mało wiem o braminach. To pewnie kwestia umaszczenia, czy coś w tym guście. Macie tutaj przepiękne braminy.}
{350}{}{No więc, nasze suszone mięso to niesamowita mieszanka jedenastu ziół i przypraw. Wierz mi, jest tak dobre, że palce lizać. Zwierzęta też je uwielbiają. Będą ścigać cię do końca świata, żeby trochę dostać. To pewnie przez ten zapach padliny.}
{351}{}{Jest jedyne w swoim rodzaju. Jedyne. Wyj-ądkowe. I większość ludzi docenia fakt, że takie jest.}
{352}{}{To LUDZKIE mięso. Chłe, chłe, chłe, chciałem tylko zobaczyć twoją minę, gdy to powiem. Kurczę, to tylko częściowo ludzkie mięso. Chłe, chłe.}
{353}{}{Ono nie jest takie, jak cokolwiek innego, co ludzie zwykle jedzą. Jest inne. Nie lepsze, tylko po prostu inne.}
{354}{}{Nie ma tu mowy o jakimkolwiek okrucieństwie wobec zwierząt. To wszystko jest znaleźne mięso. Czasem zabiera nam to sporo czasu, żeby je znaleźć, ale zwykle udaje nam się zebrać porządne żniwo.}
{355}{}{Po długim dniu spędzonym w zagrodzie bramin, zeskrobujemy resztki z naszych butów i dodajemy je dla smaku.}
{356}{}{Wiesz, okazało się, że ten nasz własnoręcznej roboty sos, jeśli wiesz co mam na myśli, no więc on właśnie nadaje mięsu posmak domowej kuchni.}
{357}{}{Do jego produkcji używamy wołowiny, która ma co najmniej pół roku i została specjalnie skruszona przez larwy gzów.}
{358}{}{Niesamowite. Zupełnie jakbyście sami jedli swoje własne suszone mięso. Uch, chcę przez to powiedzieć, że kto by go nie jadł? Mniam, mniam.}
{359}{}{Serio? Fascynujące. Opowiedz mi więcej.}
{360}{}{To już chyba wszystko, co chcę wiedzieć. Żegnaj.}
{361}{}{Nawet umierając z głodu prędzej oderwę sobie własne ramię i zjem je, niż ruszę to wasze okropne mięso.}
{370}{}{Przyłazisz, by powiedzieć, że zmieniasz zdanie? Chcesz nam pomóc wyzwolić te biedne braminki od Torra?}
{371}{}{Co ty tu robisz do ciężkiego licha? Chcesz pomóc, czy nie? Moglibyśmy mieć dla ciebie robotę, jeśli cię to interesuje.}
{372}{}{Interesuje mnie. Opowiedz mi o tym.}
{373}{}{Nie chcę mieć z wami dwoma nic wspólnego. Żegnam.}
{374}{}{Te części radskorpionów były w tamtej chatce. Wiesz do czego służą?}
{380}{}{Czego u licha chcesz od nas? Zapomniało ci się, po co tu jesteś?}
{381}{}{Nie. Pamiętam. Zaraz się tym zajmę.}
{382}{}{Zwariowaliście? Oni są na naszym tropie. Przychodzę, żeby was ostrzec, żebyście dali sobie z tym spokój. Założę się, że jesteśmy obserwowani.}
{383}{}{Zapomniało się. Moglibyście mi jeszcze raz o tym opowiedzieć? Proszę.}
{384}{}{Te części radskorpionów były w tamtej chatce. Wiesz do czego służą?}
{390}{}{Części radskorpionów? Umm, eee, ach, nie wiemy nic o żadnych częściach radskorpionów. O czym ty mówisz?}
{391}{}{No więc, tu niedaleko leży cały stos chitynowych kończyn, które mają sprzączki i rzemyki, tak że można by się w nie przebrać. Leżały na podłodze.}
{392}{}{Uch, nieważne. Do widzenia.}
{400}{}{Oto jak rzecz wygląda. Musisz pozbyć się Torra.}
{401}{}{Brzmi nieźle, zrobię to.}
{402}{}{Mowy nie ma. Spadam stąd, Dunton. Do widzenia.}
{403}{}{Zwariowaliście? Oni są na naszym tropie. Przychodzę, żeby was ostrzec, żebyście dali sobie z tym spokój. Założę się, że jesteśmy obserwowani.}
{404}{}{Kiedy Torr się tu pokaże, musisz wywabić go}
{405}{}{ stąd na moment. Możesz go przegadać lub ogłuszyć. Ale nie zabijaj go, bo będziesz mieć na karku całe miasto. Kiedy już zrobisz co trzeba, my zajmiemy się braminami. Jutro przyjdziesz do naszego sklepu po swoją dolę..}
{410}{}{Może masz rację. [rozgląda się nerwowo dookoła] Nie podoba mi się, że ktoś mógłby mnie śledzić.}
{411}{}{Powinniście być milsi dla tych, których sami tak przypominacie. A teraz idźcie do domu.}
{420}{}{Nikt nas nie śledzi. Jesteśmy naprawdę ostrożni. Jesteś żółtodziób i tyle, co nie? Śmierdzący tchórz.}
{421}{}{Przepraszam, chyba nerwy trochę mnie zawiodły. Nie wytrzymuję napięcia tak dobrze, jak wy dwaj.}
{422}{}{Przepraszam, trochę panikuję. Lepiej wezmę się do roboty.}
{423}{}{To nie dla mnie. Spadam stąd. Do widzenia.}
{424}{}{A teraz weź się do roboty i pozbądź się stąd tego idioty Torra!}
{430}{}{Świrujesz. To pozostałości radskorpionów, które zabiliśmy. No właśnie. Ot, cała tajemnica. My, ekhm, no, używamy ich jadu jako jednego z tajnych składników naszego suszonego mięsa.}
{431}{}{Jasne, pewnie. Prędzej słońce wzejdzie na zachodzie, niż w to uwierzę.}
{432}{}{Skoro tak mówicie. To mi wystarczy. Żegnam.}
{440}{}{Lepiej wiedz co dla ciebie dobre i trzymaj buzię na kłódkę.}
{441}{}{Jejku, ludzie, spokojnie. Chodziło mi tylko o to, jakim wspaniałym pomysłem mi się to wydało. Kurcze, uspokójcie się.}
{442}{}{Przepraszam. Nic nie powiem. Do widzenia.}
{443}{}{Jasne, no dobra, zmywam się stąd. Żegnam.}
{444}{}{Wiecie co, może lepiej tym razem to wy się zamknijcie. Mam już powyżej uszu słuchania, jak kłapiecie tymi swoimi jadaczkami.}
{449}{}{Ach, to nasz dzikus. Cześć. }
{450}{}{Jestem Chuck Dunton.}
{451}{}{Jestem Buck Dunton.}
{452}{}{Brzyyydal.}
{453}{}{ Dziecko Przeznaczenia!}
{460}{}{Brzyyydal? Hę? Nie masz więcej rozumu niż ten idiota Torr. To dobrze, przyda nam się jeszcze jeden wioskowy dzikus. Z tym Torrem zrobiliśmy już prawie wszystko, co się dało.}
{461}{}{Tym Torrem?}
{470}{}{Dziecko Przeznaczenia, co? Rozmażemy cię na ścianie. Mamusia upuściła cię na ziemię, czy po prostu już taki z ciebie przymuł? Do wszystkich diabłów, wynoś się stąd.}
{471}{}{Dobla! }
{472}{}{ Dziecko Przeznaczenia!}
{480}{}{Idziemy, tak? No dobra, chodźmy. Noc nie trwa wiecznie. Mamy robotę do zrobienia.}
{481}{}{Uch, pewnie, mogę iść. Chodźmy.}
{482}{}{Z przyjemnością dam temu przygłupiemu pastuszkowi nauczkę.}
{483}{}{Chyba w sumie nie chcę tego robić. Na razie.}
{490}{}{Hej, poczekaj aż wejdziemy do środka, wtedy pogadamy.}
{500}{}{Walczysz z wszystkich sił, ale w końcu Dunton wygrywa.}
{510}{}{Po długiej i ciężkiej walce udaje ci się pokonać Duntona.}
{520}{}{W porządku.}
{530}{}{Do diabła, wynoś się stąd. Niektórzy mają robotę na głowie.}
{531}{}{Och, dobrze. Chyba lepiej już pójdę. Kurcze, niektórzy ludzie są tacy przewrażliwieni. Żegnam.}
{532}{}{Torr pasie swoje braminy trochę na północ od centrum miasta.}
{533}{}{Kiedy ten palant Torr się tu zjawi, lepiej się go jakoś pozbądź.}
{600}{}{Nawet ten idiota Torr ma większy móżdżek od ciebie, złodzieju ty!}
{601}{}{ Możemy iść?}
{700}{}{Kradzież bramin zakończyła się powodzeniem.}
{702}{}{Nie! Powiem ci do czego to jest potrzebne. Przebierasz się za "Skorpionoluda" i straszysz biednego starego Torra, prawda?! To ma sens. Po prostu jesteście oprychami.}
{703}{}{[Oczy Dantonów robią się okrągłe i obaj zaczynają się nerwowo kręcić.]  Yy..yyy...tak i co...co ci do tego dzikusie? Wszyscy od czasu do czasu potrzebują trochę dodatkowej gotówki. Jaki masz w tym interes? I co zamierzasz z tym teraz zrobić, co?}
{704}{}{Nie wydam was jeżeli przestaniecie kraść braminy i nie będziecie dręczyć Torra. Wystarczy mi wasze słowo bo jeżeli to się powtórzy nie zostanie żaden z was, żeby ukraść kolejną braminę. Zrozumiano?!}
{705}{}{[Chłe, chłe, chłe] Ta, jasne dzikusie. Najwyższy czas, żebym nauczył cię co się robi z hałaśliwymi dzikusami.}
{706}{}{Dobra Plemienny, tym razem przegraliśmy. Odpuścimy, a teraz zostaw nas w spokoju.}
{707}{}{Udało ci się nastraszyć Duntonów wystarczająco, aby nie dręczyli więcej Torra.}
{708}{}{[dalej]}
{709}{}{Daj nam spokój.}
{710}{}{Ta, jasne dzikusie. Pilnuj swojego interesu.}
{800}{}{Te części radskorpionów były w chatce przy pastwisku. Wiesz do czego służą?}
