{100}{}{Widzisz jednego z dwóch bardzo podobnych do siebie mê¿czyzn - mogliby byæ bliŸniakami. Obaj s¹ dobrze umiêœnieni i maj¹ nastroszone brwi.}
{101}{}{Widzisz Chucka, a mo¿e Bucka Duntona - obaj s¹ do siebie tak podobni, ¿e nie umiesz powiedzieæ, na którego z nich w tej chwili patrzysz.}
{102}{}{Widzisz wysokiego, dobrze umiêœnionego mê¿czyznê. Poni¿ej krzaczastych brwi dostrzegasz twarz powykrêcan¹ w typowy dla awanturnika pogardliwy, acz nieco przyg³upi uœmieszek. Mê¿czyzna wygl¹da dok³adnie tak samo jak jego brat.}

{110}{}{Lepiej st¹d zmiataj, albo razem z bratem zrobimy sobie z twojej ma³ej g³ówki grzechotkê.}
{111}{}{Hej, po co siê denerwowaæ, tak tylko siê rozgl¹dam. Naprawdê przepraszam. Proszê, nie bijcie mnie. Poza tym, mam do was jedno pytanie.}
{112}{}{Uch, przepraszam pana, panie Dunton. Lepiej ju¿ pójdê.}
{113}{}{Potrzebujê informacji i lepiej bêdzie, jeœli mi powiecie wszystko, co chcê wiedzieæ.}
{114}{}{Razem z bratem? Zbyt siê boisz, ¿eby wzi¹æ siê za mnie w pojedynkê?}

{120}{}{Zmiataj st¹d, zanim zrobimy z ciebie siekane kotlety.}
{121}{}{Hej, naprawdê przepraszam, nie by³o moj¹ chêci¹ was z³oœciæ. Taka ju¿ moja g³upota. Wrócê póŸniej, kiedy nie bêdzie ju¿ wam siê chcia³o rzygaæ na mój widok.}
{122}{}{Och, dobrze, przepraszam. Proszê, nie bijcie mnie.}
{123}{}{Przynajmniej uniknê patrzenia na te wasze obrzydliwe mordy.}

{130}{}{Co chcesz od nas wiedzieæ?}
{131}{}{Myœlê, ¿e nic ci nie musimy mówiæ. A tak w ogóle, to czego u licha chcesz?}
{132}{}{A tak w ogóle, to czego chce od nas to ma³e nie wiadomo co?}
{133}{}{Czy któryœ z was s³ysza³ cokolwiek o czymœ, co nazywa siê Generator Ekosystemu Cudownej Krainy?}
{134}{}{Chcê dokonaæ wymiany.}
{135}{}{Jest tu coœ do roboty?}
{136}{}{Ech, w³aœciwie to który z was jest który?}
{137}{}{S³yszeliœcie mo¿e coœ w kwestii okaleczania bramin w tej okolicy?}
{138}{}{W sumie to niczego nie potrzebujê. ¯egnam.}

{140}{}{Miarka siê przebra³a. Myœlê, ¿e lepiej bêdzie, jeœli siê st¹d wyniesiesz, zanim sami nauczymy ciê dobrych manier.}
{141}{}{Przepraszam, ale wspó³praca z wami jest taka ekscytuj¹ca. Ju¿ sobie idê. Do widzenia.}
{142}{}{Miarka? Jaka miarka? Przede wszystkim to by³ wasz pomys³.}
{143}{}{Nie, to wy dwaj jesteœcie po prostu zbyt zieloni, ¿eby zrobiæ to, co nale¿a³o.}

{150}{}{Ha, mamy pod rêk¹ spory zapas naszego œwiatowej s³awy Suszonego Miêsa Duntonów. Smaczne i po¿ywne - tobie te¿ dobrze zrobi.}
{151}{}{Uch, to œwietnie. }
{152}{}{Suszone miêso? To nie wygl¹da mi na rzecz, której potrzebujê. Pomówmy o czymœ innym.}
{153}{}{W sumie chyba nie muszê siê wymieniaæ. ¯egnam.}

{160}{}{Daliœmy ci ju¿ szansê, .}
{161}{}{Chyba nie ma tu dla ciebie ¿adnej roboty.}
{162}{}{No wiêc, jest jedna rzecz, w której przyda³aby siê pomoc. [he, he, he]}
{163}{}{Co takiego Chuck?}
{164}{}{Co takiego Buck?}
{165}{}{Eee, có¿ takiego?}
{166}{}{Jasne. Pomówmy wiêc o czymœ innym.}
{167}{}{Hej, zaczekajcie - naprawdê chcê wam pomóc ch³opaki. Opowiedzcie mi jeszcze raz o tej robocie.}
{168}{}{Có¿, gapa ze mnie. Lepiej ju¿ pójdê. ¯egnam.}
{169}{}{Dobra. Na razie.}

{170}{}{Ty bezwartoœciowa kupo gekoñskiego gówna! Co jeszcze u diab³a tutaj robisz?}
{171}{}{Pragnê przeprosiæ. To nie mia³o tak wyjœæ. Po prostu kradzie¿ byd³a nie wychodzi mi tak dobrze, jak wam. Poza tym, potrzebujê czegoœ od was.}
{172}{}{Macie racjê - mo¿na by³o to zrobiæ du¿o lepiej. W przeciwieñstwie do was nie mam chyba talentu do kradzie¿y byd³a. Tym niemniej, potrzeba mi czegoœ.}
{173}{}{Gekoñskiego gówna? Mówicie o tym, co jecie, czy o tym, co macie w g³owie?}

{180}{}{Znowu tutaj, co? W czym mo¿emy ci pomóc, partnerze?}
{181}{}{Hej, zdróweñko. Za³atwienie tego przyg³upa Torra to by³a naprawdê bu³ka z mas³em, no nie? Pozwól, ¿e wyp³acê ci twoj¹ dolê.}
{182}{}{To by³ niez³y interes. Dajcie znaæ, jak bêdziecie mieli jeszcze jedn¹ tak¹ robotê. Teraz jednak potrzebujê czegoœ innego.}
{183}{}{Jestem tu po moj¹ dolê, partnerzy.}
{184}{}{To, co zrobiliœmy, napawa mnie wstydem. Oszukiwaæ idiotê? Czemu tak dla odmiany nie dobralibyœcie siê do kogoœ, kto siê mo¿e broniæ, tchórze? ¯egnam.}
{185}{}{Chyba niczego mi teraz nie potrzeba. Do widzenia.}

{190}{}{Dobra. Oto $50, a tak¿e coœ ekstra. Kilka porcji Suszonego Miêsa Duntonów. Jeszcze raz dziêki, partnerze.}
{191}{}{Dziêki. S³uchajcie, mam do was jeszcze jedn¹ sprawê.}
{192}{}{Forsa na pewno siê przyda. I to, mmm [gryz] te¿ ca³kiem smaczne miêso. Dziêki. Na razie.}

{198}{}{Dobra, oto uk³ad. Potrzebujemy pomocy w, uch, wyzwalaniu kilku bramin spod w³adzy tego idioty, Torra. Mo¿esz go tak zakrêciæ, ¿eby zostawi³ braminy, albo go og³uszyæ - tylko nie rób mu za du¿ej krzywdy, bo bêdzie chryja.}
{199}{}{Teraz ju¿ pamiêtam. Dziêki.}
{200}{}{Spotkajmy siê na pastwisku bramin, zaraz na wschód od miasta, dziœ o 6:00 wieczorem.}
{201}{}{Spotkajmy siê na pastwisku bramin, zaraz na wschód od miasta, jutro o 6:00 wieczorem.}
{202}{}{Dobra, zajmê siê Torrem.}
{203}{}{Dobra, znajdê Torra na pastwisku i zajmê siê nim dla was.}
{204}{}{Chyba jednak nie chcê tego robiæ.}
{205}{}{Dobra, bêdê tam. Na razie.}
{206}{}{W miêdzyczasie mam do was jeszcze kilka pytañ.}
{207}{}{Do widzenia.}

{208}{}{Jestem Chuck Dunton. Przymu³ jakiœ, czy co?}
{209}{}{Jestem Buck Dunton. Przymu³ jakiœ, czy co?}
{210}{}{Czy wygl¹dam a¿ tak Ÿle? Jestem Chuck Dunton.}
{211}{}{Czy wygl¹dam a¿ tak Ÿle? Jestem Buck Dunton.}
{212}{}{Co, masz coœ z g³ówk¹? Jestem Chuck Dunton.}
{213}{}{Co, masz coœ z g³ówk¹? Jestem Buck Dunton.}
{214}{}{To ciê chyba przerasta. Cholerne dzikusy. Jestem Chuck, je³opo.}
{215}{}{To ciê chyba przerasta. Cholerne dzikusy. Jestem Buck, je³opo.}
{216}{}{Jestem Wielkonosa Sally Dunton. Podoba ci siê moja sukienka? Jestem Chuck Dunton, wioskowy przymule.}
{217}{}{Jestem Wielkonosa Sally Dunton. Podoba ci siê moja sukienka? Jestem Buck Dunton, wioskowy przymule.}
{218}{}{Uch, no dobra. Tak mi siê w³aœnie zdawa³o. Przepraszam.}
{219}{}{Proszê siê nie przejmowaæ. Teraz ju¿ wiem. Uch, panie Dunton, potrzebujê czegoœ od pana.}
{220}{}{Dobra, wszystko jedno. S³uchaj, powiedz mi po prostu to, co chcê wiedzieæ.}
{221}{}{Jejku, ale¿ wy obaj jesteœcie g³upi i brzydcy. A zreszt¹, co siê bêdê przejmowaæ, na którego Duntona wydzieram japê. Na razie, dupku.}
{222}{}{Ach, tak. Powiedz mi coœ o robocie.}

{230}{}{Dobra rada - ani mru mru komukolwiek. Jak komuœ piœniesz choæby s³ówko, to siê pogniewamy. A nie chcesz widzieæ, jak siê gniewamy.}
{231}{}{Przepraszam, nikomu nie powiem. Obiecujê, panie Dunton. Do widzenia.}
{232}{}{Nie martwcie siê, nikomu nie powiem. A teraz pomówmy o czymœ innym.}
{233}{}{Nie chcê widzieæ, jak siê gniewacie? W ogóle nie chcê widzieæ waszych wstrêtnych mord. ¯egnam.}

{240}{}{No, no, interesy z tob¹, to czysta przyjemnoœæ. He, he, he. Coœ jeszcze?}
{241}{}{Hmm... myœlê, ¿e mam jeszcze coœ na wymianê.}
{242}{}{Tak.}
{243}{}{Nie, to ju¿ chyba wszystko, Chuck.}
{244}{}{Nie, to ju¿ chyba wszystko, Buck.}

{250}{}{Hej tam, partnerze. Dziœ w nocy trzymamy za ciebie kciuki. Co mogê dla ciebie zrobiæ?}
{251}{}{Uch, po powtórnym przemyœleniu dochodzê do wniosku, ¿e nie chcê pomagaæ wam dziœ w nocy.}
{252}{}{Pewnie, bêdê tam. Tymczasem jednak pozwólcie, ¿e o coœ zapytam.}
{253}{}{Pewnie, ¿e tam bêdê. Na razie.}

{259}{}{Proszê, proszê, czy¿ to nie nasz wspania³y miêœniaczek?}
{260}{}{Hej tam. Jak siê ma twoje ramiê? Masz ochotê na jeszcze jeden razik?}
{261}{}{Hej tam, pêtaku. Co robisz w barze? Zanim pozwolimy ci tu zostaæ, musisz pokazaæ Duntonom, na co ciê staæ, si³uj¹c siê ze mn¹. [ha, ha, ha]}
{262}{}{Nie wygl¹dasz na zbyt twardego. Czemu siê ze mn¹ nie posi³ujesz, Chucku Dunton, o prawo do picia w naszym barze?}
{263}{}{Nie wygl¹dasz na zbyt twardego. Czemu siê ze mn¹ nie posi³ujesz, Bucku Dunton, o prawo do picia w naszym barze?}
{264}{}{Hej tam, cukiereczki. ¯eby tu siedzieæ, musicie sobie zas³u¿yæ. Musisz siê zmierzyæ z Chuckiem Duntonem, jeœli chcesz piæ w tym barze.}
{265}{}{Hej tam, cukiereczki. ¯eby tu siedzieæ, musicie sobie zas³u¿yæ. Musisz siê zmierzyæ z Buckiem Duntonem, jeœli chcesz piæ w tym barze.}

{266}{}{Zdaje siê mamy tutaj rywala. Musisz siê zmierzyæ z Chuckiem Duntonem, jeœli chcesz piæ w tym barze.}
{267}{}{Zdaje siê mamy tutaj rywala. Musisz siê zmierzyæ z Buckiem Duntonem, jeœli chcesz piæ w tym barze.}

{268}{}{No dobrze, posi³ujmy siê. Inaczej siê pewnie ode mnie nie odczepisz.}
{269}{}{Chyba nie chcê siê z tob¹ teraz si³owaæ.}
{270}{}{Nie chcê siê teraz si³owaæ. Chcê tylko o coœ zapytaæ.}
{271}{}{Uch, chyba jestem nie w tym barze, co trzeba. ¯egnam.}

{280}{}{Tym razem jesteœ gór¹. Sprytna z ciebie bestia, no nie? Ruszasz siê tak szybko, jak gekon, któremu ktoœ podpali³ ogon. Niech tam, stawiam pierwszego drinka.}
{281}{}{Dziêki. Mo¿e umiesz odpowiedzieæ mi na parê pytañ.}
{282}{}{To tylko szczêœliwy traf. Dziêki.}
{283}{}{Nie chcê twojego piwa, ale chcê ciê o coœ zapytaæ.}
{284}{}{Nie chcê twojego piwa. ¯egnam.}

{290}{}{Masz szczêœcie, mog³em z³amaæ twoje cherlawe ramiê jak ma³y patyczek. [Ch³e, ch³e, ch³e] Wiêc wci¹¿ nie ma w tym mieœcie prawdziwego wyzwania.}
{291}{}{Nie doœæ ci upokarzania, jak na jeden wieczór?}
{292}{}{Zróbmy to jeszcze raz. Tym razem ci poka¿ê.}
{293}{}{Auæ. Dobrze ju¿, dobrze. Mam dosyæ. Hej, pozwól, ¿e o coœ zapytam.}
{294}{}{Mam ju¿ doœæ. ¯egnam.}

{300}{}{Nie chcesz siê z nami si³owaæ? Co, bracia Dunton nie s¹ dla ciebie doœæ dobrzy, ¿eby siê z nimi posi³owaæ?}
{301}{}{Si³uj¹c siê ze mn¹, móg³byœ zrobiæ mi krzywdê.}
{302}{}{Mo¿e póŸniej. Na razie potrzebujê informacji.}
{303}{}{To nie by³oby uczciwe starcie. ¯egnam.}
{304}{}{Jesteœ zbyt cherlawy. Si³ujê siê tylko z prawdziwymi mê¿czyznami. Odczep siê cieniasie.}

{310}{}{¯e niby czego szukasz? Jedyna Cudowna Kraina jak¹ znam, to ramiona œlicznej Jenny z ³aŸni Mamuœki. [ch³e, ch³e, ch³e]}
{311}{}{Eee, dziêki. Pozwól wiêc, ¿e zapytam o coœ innego.}
{312}{}{To chyba na razie wszystko, co chcê wiedzieæ. Do widzenia.}

{320}{}{He, s³ysza³em, ¿e podobno jakieœ [ch³e, ch³e] skorpioludy podrzynaj¹ gard³a braminom na wschód st¹d. Ale ja bym w to nie wierzy³. [ch³e, ch³e, ch³e]}
{321}{}{Och, rozumiem, dziêki. Jest jeszcze coœ, o co chcê zapytaæ.}
{322}{}{To chyba na razie wszystko, co chcê wiedzieæ. Do widzenia.}

{330}{}{Hej, cz³owieku. Przychodzisz, ¿eby wymieniæ siê na Œwiatowej S³awy Suszone Miêso Duntonów?}
{331}{}{Noo? Kupujesz suszone miêso czy nie?}
{332}{}{Brzmi œwietnie. Chcê dokonaæ wymiany.}
{333}{}{Suszone miêso? Brzmi ciekawie. Opowiedz mi coœ na ten temat.}
{334}{}{W³aœciwie to mam do was kilka pytañ.}
{335}{}{Na razie chyba niczego nie potrzebujê. Do widzenia.}
{336}{}{Ciekawi¹ mnie te wszystkie braminy, które macie w zagrodzie. Ich piêtna ró¿ni¹ siê miêdzy sob¹.}

{340}{}{Hê? O co ci do diab³a chodzi? Wszystkie s¹ nasze.}
{341}{}{Chodzi mi o to, ¿e czêœæ z nich wygl¹da tak, jakby mia³y wczeœniej inne piêtna, które ktoœ nieudolnie zmieni³ na nowe.}
{342}{}{Ach, rozumiem. He-he, to pewnie pomy³ka. Lepiej ju¿ pójdê. ¯egnam.}
{343}{}{Có¿, chyba po prostu ma³o wiem o braminach. To pewnie kwestia umaszczenia, czy coœ w tym guœcie. Macie tutaj przepiêkne braminy.}

{350}{}{No wiêc, nasze suszone miêso to niesamowita mieszanka jedenastu zió³ i przypraw. Wierz mi, jest tak dobre, ¿e palce lizaæ. Zwierzêta te¿ je uwielbiaj¹. Bêd¹ œcigaæ ciê do koñca œwiata, ¿eby trochê dostaæ. To pewnie przez ten zapach padliny.}
{351}{}{Jest jedyne w swoim rodzaju. Jedyne. Wyj-¹dkowe. I wiêkszoœæ ludzi docenia fakt, ¿e takie jest.}
{352}{}{To LUDZKIE miêso. Ch³e, ch³e, ch³e, chcia³em tylko zobaczyæ twoj¹ minê, gdy to powiem. Kurczê, to tylko czêœciowo ludzkie miêso. Ch³e, ch³e.}
{353}{}{Ono nie jest takie, jak cokolwiek innego, co ludzie zwykle jedz¹. Jest inne. Nie lepsze, tylko po prostu inne.}
{354}{}{Nie ma tu mowy o jakimkolwiek okrucieñstwie wobec zwierz¹t. To wszystko jest znaleŸne miêso. Czasem zabiera nam to sporo czasu, ¿eby je znaleŸæ, ale zwykle udaje nam siê zebraæ porz¹dne ¿niwo.}
{355}{}{Po d³ugim dniu spêdzonym w zagrodzie bramin, zeskrobujemy resztki z naszych butów i dodajemy je dla smaku.}
{356}{}{Wiesz, okaza³o siê, ¿e ten nasz w³asnorêcznej roboty sos, jeœli wiesz co mam na myœli, no wiêc on w³aœnie nadaje miêsu posmak domowej kuchni.}
{357}{}{Do jego produkcji u¿ywamy wo³owiny, która ma co najmniej pó³ roku i zosta³a specjalnie skruszona przez larwy gzów.}
{358}{}{Niesamowite. Zupe³nie jakbyœcie sami jedli swoje w³asne suszone miêso. Uch, chcê przez to powiedzieæ, ¿e kto by go nie jad³? Mniam, mniam.}
{359}{}{Serio? Fascynuj¹ce. Opowiedz mi wiêcej.}
{360}{}{To chyba wszystko, co chcê wiedzieæ. ¯egnam.}
{361}{}{Nawet umieraj¹c z g³odu prêdzej oderwê sobie w³asne ramiê i zjem je, ni¿ ruszê to wasze okropne miêso.}

{370}{}{Przy³azisz, by powiedzieæ, ¿e zmieniasz zdanie? Chcesz nam pomóc wyzwoliæ te biedne braminki od Torra?}
{371}{}{Co ty tu robisz do ciê¿kiego licha? Chcesz pomóc, czy nie? Moglibyœmy mieæ dla ciebie robotê, jeœli ciê to interesuje.}
{372}{}{Interesuje mnie. Opowiedz mi o tym.}
{373}{}{Nie chcê mieæ z wami dwoma nic wspólnego. ¯egnam.}
{374}{}{Te czêœci radskorpionów by³y w tamtej chatce. Wiesz do czego s³u¿¹?}

{380}{}{Czego u licha chcesz od nas? Zapomnia³o ci siê, po co tu jesteœ?}
{381}{}{Nie. Pamiêtam. Zaraz siê tym zajmê.}
{382}{}{Zwariowaliœcie? Oni s¹ na naszym tropie. Przychodzê, ¿eby was ostrzec, ¿ebyœcie dali sobie z tym spokój. Za³o¿ê siê, ¿e jesteœmy obserwowani.}
{383}{}{Zapomnia³o siê. Moglibyœcie mi jeszcze raz o tym opowiedzieæ? Proszê.}
{384}{}{Te czêœci radskorpionów by³y w tamtej chatce. Wiesz do czego s³u¿¹?}

{390}{}{Czêœci radskorpionów? Umm, eee, ach, nie wiemy nic o ¿adnych czêœciach radskorpionów. O czym ty mówisz?}
{391}{}{No wiêc, tu niedaleko le¿y ca³y stos chitynowych koñczyn, które maj¹ sprz¹czki i rzemyki, tak ¿e mo¿na by siê w nie przebraæ. Le¿a³y na pod³odze.}
{392}{}{Uch, niewa¿ne. Do widzenia.}

{400}{}{Oto jak rzecz wygl¹da. Musisz pozbyæ siê Torra.}
{401}{}{Brzmi nieŸle, zrobiê to.}
{402}{}{Mowy nie ma. Spadam st¹d, Dunton. Do widzenia.}
{403}{}{Zwariowaliœcie? Oni s¹ na naszym tropie. Przychodzê, ¿eby was ostrzec, ¿ebyœcie dali sobie z tym spokój. Za³o¿ê siê, ¿e jesteœmy obserwowani.}
{404}{}{Kiedy Torr siê tu poka¿e, musisz wywabiæ go}
{405}{}{ st¹d na moment. Mo¿esz go przegadaæ lub og³uszyæ. Ale nie zabijaj go, bo bêdziesz mieæ na karku ca³e miasto. Kiedy ju¿ zrobisz co trzeba, my zajmiemy siê braminami. Jutro przyjdziesz do naszego sklepu po swoj¹ dolê..}

{410}{}{Mo¿e masz racjê. [rozgl¹da siê nerwowo dooko³a] Nie podoba mi siê, ¿e ktoœ móg³by mnie œledziæ.}
{411}{}{Powinniœcie byæ milsi dla tych, których sami tak przypominacie. A teraz idŸcie do domu.}

{420}{}{Nikt nas nie œledzi. Jesteœmy naprawdê ostro¿ni. Jesteœ ¿ó³todziób i tyle, co nie? Œmierdz¹cy tchórz.}
{421}{}{Przepraszam, chyba nerwy trochê mnie zawiod³y. Nie wytrzymujê napiêcia tak dobrze, jak wy dwaj.}
{422}{}{Przepraszam, trochê panikujê. Lepiej wezmê siê do roboty.}
{423}{}{To nie dla mnie. Spadam st¹d. Do widzenia.}
{424}{}{A teraz weŸ siê do roboty i pozb¹dŸ siê st¹d tego idioty Torra!}

{430}{}{Œwirujesz. To pozosta³oœci radskorpionów, które zabiliœmy. No w³aœnie. Ot, ca³a tajemnica. My, ekhm, no, u¿ywamy ich jadu jako jednego z tajnych sk³adników naszego suszonego miêsa.}
{431}{}{Jasne, pewnie. Prêdzej s³oñce wzejdzie na zachodzie, ni¿ w to uwierzê.}
{432}{}{Skoro tak mówicie. To mi wystarczy. ¯egnam.}

{440}{}{Lepiej wiedz co dla ciebie dobre i trzymaj buziê na k³ódkê.}
{441}{}{Jejku, ludzie, spokojnie. Chodzi³o mi tylko o to, jakim wspania³ym pomys³em mi siê to wyda³o. Kurcze, uspokójcie siê.}
{442}{}{Przepraszam. Nic nie powiem. Do widzenia.}
{443}{}{Jasne, no dobra, zmywam siê st¹d. ¯egnam.}
{444}{}{Wiecie co, mo¿e lepiej tym razem to wy siê zamknijcie. Mam ju¿ powy¿ej uszu s³uchania, jak k³apiecie tymi swoimi jadaczkami.}

{449}{}{Ach, to nasz dzikus. Czeœæ. }
{450}{}{Jestem Chuck Dunton.}
{451}{}{Jestem Buck Dunton.}
{452}{}{Brzyyydal.}
{453}{}{ Dziecko Przeznaczenia!}

{460}{}{Brzyyydal? Hê? Nie masz wiêcej rozumu ni¿ ten idiota Torr. To dobrze, przyda nam siê jeszcze jeden wioskowy dzikus. Z tym Torrem zrobiliœmy ju¿ prawie wszystko, co siê da³o.}
{461}{}{Tym Torrem?}

{470}{}{Dziecko Przeznaczenia, co? Rozma¿emy ciê na œcianie. Mamusia upuœci³a ciê na ziemiê, czy po prostu ju¿ taki z ciebie przymu³? Do wszystkich diab³ów, wynoœ siê st¹d.}
{471}{}{Dobla! }
{472}{}{ Dziecko Przeznaczenia!}

{480}{}{Idziemy, tak? No dobra, chodŸmy. Noc nie trwa wiecznie. Mamy robotê do zrobienia.}
{481}{}{Uch, pewnie, mogê iœæ. ChodŸmy.}
{482}{}{Z przyjemnoœci¹ dam temu przyg³upiemu pastuszkowi nauczkê.}
{483}{}{Chyba w sumie nie chcê tego robiæ. Na razie.}

{490}{}{Hej, poczekaj a¿ wejdziemy do œrodka, wtedy pogadamy.}
{500}{}{Walczysz z wszystkich si³, ale w koñcu Dunton wygrywa.}
{510}{}{Po d³ugiej i ciê¿kiej walce udaje ci siê pokonaæ Duntona.}
{520}{}{Ok.}

{530}{}{Do diab³a, wynoœ siê st¹d. Niektórzy maj¹ robotê na g³owie.}
{531}{}{Och, dobrze. Chyba lepiej ju¿ pójdê. Kurcze, niektórzy ludzie s¹ tacy przewra¿liwieni. ¯egnam.}
{532}{}{Torr pasie swoje braminy trochê na pó³noc od centrum miasta.}
{533}{}{Kiedy ten palant Torr siê tu zjawi, lepiej siê go jakoœ pozb¹dŸ.}

{600}{}{Nawet ten idiota Torr ma wiêkszy mó¿d¿ek od ciebie, z³odzieju ty!}
{601}{}{ Mo¿emy iœæ?}

{700}{}{Kradzie¿ bramin zakoñczy³a siê powodzeniem.}

{702}{}{Nie! Powiem ci do czego to jest potrzebne. Przebierasz siê za "Skorpionoluda" i straszysz biednego starego Torra, prawda?! To ma sens. Po prostu jesteœcie oprychami.}
{703}{}{[Oczy Dantonów robi¹ siê okr¹g³e i obaj zaczynaj¹ siê nerwowo krêciæ.]  Yy..yyy...tak i co...co ci do tego dzikusie? Wszyscy od czasu do czasu potrzebuj¹ trochê dodatkowej gotówki. Jaki masz w tym interes? I co zamierzasz z tym teraz zrobiæ, co?}
{704}{}{Nie wydam was je¿eli przestaniecie kraœæ braminy i nie bêdziecie drêczyæ Torra. Wystarczy mi wasze s³owo bo je¿eli to siê powtórzy nie zostanie ¿aden z was, ¿eby ukraœæ kolejn¹ braminê. Zrozumiano?!}
{705}{}{[Ch³e, ch³e, ch³e] Ta, jasne dzikusie. Najwy¿szy czas, ¿ebym nauczy³ ciê co siê robi z ha³aœliwymi dzikusami.}
{706}{}{Dobra Plemienny, tym razem przegraliœmy. Odpuœcimy, a teraz zostaw nas w spokoju.}
{707}{}{Uda³o ci siê nastraszyæ Duntonów wystarczaj¹co, aby nie drêczyli wiêcej Torra.}
{708}{}{[GOTOWE]}
{709}{}{Daj nam spokój.}
{710}{}{Ta, jasne dzikusie. Pilnuj swojego interesu.}

{800}{}{Te czêœci radskorpionów by³y w chatce przy pastwisku. Wiesz do czego s³u¿¹?}
