{100}{}{Widzisz bardzo wysokiego i chudego trapera.}
{101}{}{Widzisz Cienkiego Bolka, przywódcê Osady Traperów.}
{110}{}{No, no, ch³opcze, widzê, ¿e nasze szczury jeszcze ciê nie zagryz³y - ale zrobi¹ to, jeœli dalej bêdziesz je gnêbi³. Pamiêtaj tylko, ¿eby ¿aden z nich nie przypa³êta³ siê tu za tob¹.}
{111}{}{No, no, panienko, widzê, ¿e nasze szczury jeszcze ciê nie zagryz³y - ale zrobi¹ to, jeœli dalej bêdziesz je gnêbi³a. Pamiêtaj tylko, ¿eby ¿aden z nich nie przypa³êta³ siê tu za tob¹.}
{112}{}{Nie martw siê. Nie przyjd¹ tu.}
{113}{}{Nie, dziêki tobie.}
{114}{}{Ee, ok.}
{120}{}{Po prostu nie chcê mieæ nic wspólnego z tymi gryzoniami. Nie ruszam ich i mam nadziejê, ¿e one odp³ac¹ mi tym samym. Trzymaj siê.}
{130}{}{Uwa¿aj na siebie. Wygl¹da na to, ¿e im g³êbiej siê schodzi, tym wiêksze siê robi¹.}
{140}{}{Hej, dzikusie. Mówi¹ na mnie Cienki Bolek i jestem tym, z którym rozmawia siê o Osadzie Traperów. Nie chcemy tu ¿adnych k³opotów.}
{141}{}{Witaj. To mi³e z twojej strony, ¿e nas odwiedzasz. Mówi¹ na mnie Cienki Bolek i przemawiam w imieniu Osady Traperów.}
{142}{}{Witaj Cienki. Nazywam siê }
{143}{}{. Czemu nazywacie to miejsce Osad¹ Traperów?}
{144}{}{Czy wiesz mo¿e, gdzie mo¿na znaleŸæ coœ, co nazywa siê Generator Ekosystemu Cudownej Krainy?}
{145}{}{Mi³o mi pana poznaæ, panie Bolek. Na razie tylko siê tak tutaj rozgl¹dam. Do widzenia.}
{150}{}{Witaj, nazywaj¹ mnie Cienki Bolek. Przemawiam w imieniu tej czêœci miasta.}
{151}{}{Gruk.}
{152}{}{Uuk, upl.}
{153}{}{[wskazuj¹c na siebie] Moja }
{154}{}{, chcieæ jeœæ.}
{160}{}{Przyznaj siê, twoja antena nie odbiera wszystkich kana³ów, co? No dobra, s³uchaj. Ten klucz otwiera drzwi za moimi plecami. Tam jest mnóstwo ró¿nych szczurów, podobno nawet jeden bardzo du¿y. Mo¿esz tam pójœæ i zabiæ tyle tych przebrzyd³ych szczurów, ile tylko bêdziesz w stanie zjeœæ. Co ty na to?}
{161}{}{Ten stary, wielki szczur, co nas tak tutaj wszystkich w okolicy zamêcza³, chyba znikn¹³. Ale nie wydaje mi siê, ¿eby taki przymu³, jak ty, móg³ mieæ z tym coœ wspólnego.}
{162}{}{Oki. Moja, zabiæ szcur. He, he, he.}
{163}{}{Nie! Szczura straaaaszne! Ne. Moja iœæ.}
{170}{}{Czego u licha chcesz tym razem?}
{171}{}{Hej. W czym mogê pomóc?}
{172}{}{Myœlê, ¿e aby dostaæ siê do pó³nocnej czêœci Osady Traperów potrzebny jest mi klucz.}
{173}{}{Mam do ciebie kilka pytañ.}
{174}{}{W sumie chyba niczego nie potrzebujê. Do widzenia.}
{180}{}{No wiêc, ta czêœæ miasta, w której teraz jesteœmy, to miejsce, gdzie mieszkaj¹ wszyscy traperzy, gdy nie poluj¹ na gekony. Jedyny problem, jaki tu mamy, to szczury mieszkaj¹ce po pó³nocnej stronie. Na szczêœcie uda³o nam siê doœæ szczelnie zabarykadowaæ wiêkszoœæ przejœæ do tamtej czêœci.}
{181}{}{Co chcesz wiedzieæ?}
{182}{}{Czy kiedykolwiek przechodzicie na pó³nocn¹ stronê?}
{183}{}{Opowiedz mi o polowaniu na gekony.}
{184}{}{Czy wiesz coœ o Generatorze Ekosystemu Cudownej Krainy?}
{185}{}{Macie tutaj ca³e mnóstwo samochodów.}
{186}{}{Szczury? Opowiedz mi o szczurach.}
{187}{}{Dziêki za informacjê. Chyba na razie nie potrzebujê nic wiêcej. Do widzenia.}
{190}{}{Och, masz na myœli GECK, co? Widzia³em reklamê jednego z nich w jakimœ starym czasopiœmie. Ale nie s¹dzê, ¿eby jeszcze jakieœ istnia³y. Na pewno nie w tej okolicy.}
{191}{}{Serio? No dobrze, w takim razie opowiedz mi o czymœ innym.}
{192}{}{Och, szkoda. To ju¿ wszystkie pytania. Dziêki.}
{200}{}{Chcesz klucz do pó³nocnej czêœci Osady Traperów? Po co ci on?}
{201}{}{Wci¹¿ chcesz ten klucz? Po co?}
{202}{}{Jestem badaczem, chcê zajrzeæ wszêdzie, gdzie tylko siê da. Poza tym, mo¿e gdzieœ tam, na jakiejœ górnej pó³ce, le¿y sobie jakiœ zapomniany GECK.}
{203}{}{Zamierzam pomóc ci rozwi¹zaæ problem ze szczurami.}
{204}{}{Chcê siê dostaæ do tego samochodu za siatk¹.}
{205}{}{Mogê daæ wszystko za ten klucz. Naprawdê bardzo chcê dostaæ siê na drug¹ stronê Osady Traperów.}
{206}{}{Chyba jednak nie chcê tego klucza. Wygl¹da na to, ¿e tam jest doœæ niebezpiecznie.}
{210}{}{No dobra, oto klucz. Tylko nie prowokuj tam za du¿o k³opotów i nie zapomnij zamkn¹æ drzwi za sob¹.}
{211}{}{Ale odjazd! Tego w³aœnie potrzebowa³em, kochanie. Uwa¿aj, ¿eby nic nie dziabnê³o ciê w ten twój œliczny, ma³y ty³eczek. [he, he, hi, hi, hi]}
{212}{}{Dziêki za klucz, Cienki. Zanim pójdê, mam do ciebie kilka pytañ.}
{213}{}{Dziêki, Cienki. Na pewno zamknê drzwi za sob¹. Do widzenia.}
{220}{}{Jeœli chcesz ten klucz, musisz go ode mnie kupiæ.}
{221}{}{Nie ma sprawy - mo¿emy pohandlowaæ.}
{222}{}{Nie chcê siê o niego targowaæ. Nic ciê nie kosztuje po¿yczenie mi go. Na pewno zamknê drzwi za sob¹.}
{223}{}{Jeœli dasz mi klucz, postaram siê, ¿eby w okolicy by³o trochê mniej szczurów.}
{224}{}{Chyba jednak nie chcê klucza. ¯egnam.}
{230}{}{Teraz chyba masz to, czego chcesz. Uwa¿aj na siebie.}
{231}{}{Dziêki.}
{232}{}{Ostro siê targujesz. Mam nadziejê, ¿e to by³o tego warte.}
{240}{}{No proszê, chyba jednak ten klucz nie jest ci a¿ tak potrzebny, co? Na pewno masz to, czego chcesz?}
{241}{}{Ups. Tak mi siê zdawa³o, ¿e potrzebujê czegoœ innego.}
{242}{}{Hej, Cienki, jest parê rzeczy, o które chcê ciê zapytaæ.}
{243}{}{Nic wiêcej od ciebie nie potrzebujê, ale i tak dziêki.}
{250}{}{Zablokowaliœmy wszystkie przejœcia na pó³nocn¹ stronê oprócz jednego. Mam klucz do tego przejœcia - tak na wypadek gdyby ktoœ z jakiegoœ powodu chcia³ tam pójœæ. Choæ nie mam pojêcia, dlaczego ktoœ mia³by chcieæ tam iœæ. Ja bym nie chcia³.}
{251}{}{Ciekawe. Opowiedz mi o czymœ innym.}
{252}{}{Chêtnie wezmê od ciebie ten klucz.}
{253}{}{To wszystko, co chcê na razie wiedzieæ. Dziêkujê, do widzenia.}
{260}{}{Ciekawi ciê polowanie, co? [Ogl¹da ciê od góry do do³u]}
{261}{}{[Dalej]}
{270}{}{Myœlê, ¿e na twoim miejscu nie próbowa³bym tego. Jeszcze by ci siê pobrudzi³y r¹czki. [he, he, hi, hi, hi] Coœ jeszcze?}
{271}{}{No tak, na pewno nie chce mi siê brudziæ r¹k. Opowiedz mi o czymœ innym.}
{272}{}{To by³oby wspania³e byæ tak uzdolnionym traperem jak ty. Móg³byœ mnie wiele nauczyæ.}
{273}{}{To wszystko, co chcê na razie wiedzieæ. Dziêkujê, do widzenia.}
{280}{}{No no, wygl¹dasz na kogoœ, kto umia³by sobie poradziæ. Gekony wystêpuj¹ w dwóch odmianach - zwyk³ej i z³ocistej. Zwyk³e gekony s¹ ³atwe do upolowania, ale za z³ociste mo¿na dostaæ wiêcej pieniêdzy.}
{281}{}{Powiedz mi coœ wiêcej o gekonach z³ocistych.}
{282}{}{Ciekawe. Opowiedz mi o czymœ innym.}
{283}{}{To wszystko, co chcê na razie wiedzieæ. Dziêkujê, do widzenia.}
{290}{}{Z³ociste gekony s¹ zwinne i dwa razy tak wredne co zwyk³e. Plus, jak ciê ju¿ ugryz¹, to bêd¹ trzymaæ ciê i wgryzaæ siê do samej koœci. A jeszcze nie wziêliœmy pod uwagê ich jadu. Za to ich skóry wygl¹daj¹ naprawdê ³adnie, wiêc s¹ warte du¿o wiêcej.}
{291}{}{Powiedz mi o nich coœ jeszcze.}
{300}{}{Pewien naprawdê dobry traper o imieniu Smiley wyruszy³ na pó³noc w poszukiwaniu terenu, sk¹d wy³azi³yby te wszystkie gekony. By³ przekonany, ¿e one wszystkie pochodz¹ z jednego miejsca. Problem w tym, ¿e od kilku miesiêcy s³uch o nim zagin¹³.}
{301}{}{Jak s¹dzisz, co mu siê mog³o przydarzyæ?}
{310}{}{Maybe he found where they come from and got all ate up. (heh, hee, hee) But I tell you one
 thing: Mrs. Buckner's heart just about broke when he didn't come back. You see, he was her beau. Mrs.
 Buckner runs Buckner house, y'know.}
{311}{}{Ciekawe. Opowiedz mi o czymœ innym.}
{312}{}{To wszystko, co chcê na razie wiedzieæ. Dziêkujê, do widzenia.}
{320}{}{Mamy ca³kiem sporo, mnóstwo i od zatrzêsienia samochodów. Wszystkie tylko czekaj¹, a¿ ich w³aœciciele wróc¹ z zakupów. Rzecz w tym, ¿e nikt ju¿ nie wróci. Zreszt¹, i tak ¿aden z nich nie dzia³a. Jest jeden taki œliczniutki Kr¹¿ownik szos Chrysalis Motors zaraz na wschód st¹d, ale jeszcze nie wykombinowa³em, jak siê do niego dostaæ.}
{321}{}{Kr¹¿ownik szos? Ciekawe. Opowiedz mi o czymœ innym.}
{322}{}{To wszystko, co chcê na razie wiedzieæ. Dziêkujê, do widzenia.}
{330}{}{Wiesz, smakuj¹ ca³kiem nieŸle, kiedy siê je upiecze na ro¿nie z niewielkim dodatkiem zió³. Ale przede wszystkim s¹ prawdziwym utrapieniem, a robi siê coraz gorzej. Zabarykadowaliœmy pó³nocn¹ czêœæ centrum handlowego - ee, znaczy siê Osady Traperów - ale one i tak siê jakoœ przemykaj¹. S¹ pewne drzwi prowadz¹ce tam, w pomieszczeniu tu¿ za mn¹, ale zamkn¹³em je na klucz.}
{331}{}{W domu mama zwykle sma¿y³a je na patelni z odrobin¹ mas³a. Powiedz mi wiêcej o tych szczurzych atakach.}
{332}{}{Ciekawe. Opowiedz mi o czymœ innym.}
{333}{}{To wszystko, co chcê na razie wiedzieæ. Dziêkujê, do widzenia.}
{335}{}{Wiesz, smakuj¹ ca³kiem nieŸle, kiedy siê je upiecze na ro¿nie z niewielkim dodatkiem zió³. Ale przede wszystkim s¹ prawdziwym utrapieniem, a robi siê coraz gorzej. Zabarykadowaliœmy pó³nocn¹ czêœæ Osady, ale one i tak siê jakoœ przemykaj¹. S¹ pewne drzwi prowadz¹ce tam, w pomieszczeniu tu¿ za mn¹, ale zamkn¹³em je na klucz.}
{336}{}{No wiesz, mieliœmy tu kiedyœ du¿y problem ze szczurami, ale ostatnio jakoœ ich uby³o. Zupe³nie jakby je ktoœ wyt³uk³ i wygoni³ st¹d na dobre.}
{337}{}{W domu mama zwykle sma¿y³a je na patelni z odrobin¹ mas³a. Powiedz mi wiêcej o tych szczurzych atakach.}
{340}{}{Ludzie znikaj¹. Na razie tylko ci chorzy i s³abi. Oczywiœcie, szczury nie trac¹ czasu na gotowanie. Po prostu rozdzieraj¹ ich na strzêpy, zostawiaj¹c ma³e k³aczki w³osów i strzêpy ubrañ. W ka¿dym razie tyle znajdujemy rano. S³ysza³em nawet gadkê, ¿e gdzieœ tam jest coœ w rodzaju olbrzymiego szczurzego bóstwa, które wydaje innym szczurom rozkazy.}
{341}{}{Ciekawe. Mo¿e ktoœ powinien coœ z tym zrobiæ. S³uchaj, mogê dostaæ klucz do przejœcia na pó³nocn¹ stronê Osady Traperów?}
{342}{}{Ciekawe. Opowiedz mi o czymœ innym.}
{343}{}{To wszystko, co chcê na razie wiedzieæ. Dziêkujê, do widzenia.}
{350}{}{Wiesz, nie jesteœ znowu taka ³adna, ale od ostatniego razu minê³o du¿o czasu. Myœlê, ¿e móg³bym daæ ci klucz, jeœli tylko ty dasz mi to, czego mi potrzeba. [he, he, hi, hi, hi]}
{351}{}{Kurcze, wiesz, jesteœ œliczn¹ ma³¹ panienk¹, no nie? Na pewno mo¿emy jakoœ to za³atwiæ z tym kluczem, musisz tylko daæ mi to, czego chcê. [he, he, hi, hi, hi]}
{352}{}{No dobra, ale mam nadziejê, ¿e nazywaj¹ ciê Cienkim tylko z powodu twojego wzrostu.}
{353}{}{Uch, nie to dok³adnie mia³am na myœli.}
{354}{}{Lepiej nie patrz na mnie w ten sposób. Chyba sobie pójdê, zanim stanie ci siê krzywda. ¯egnam.}
{360}{}{Móg³bym nauczyæ ciê czegoœ o dziczy. To ciê wyniesie $100.}
{361}{}{Zawsze chêtnie dzielê siê swoimi umiejêtnoœciami z innymi. Mogê nauczyæ ciê paru sztuczek za $50.}
{362}{}{W takim razie, za takie pieni¹dze, lepiej ¿ebyœ mia³ du¿o do nauczenia.}
{363}{}{To mnóstwo pieniêdzy. Po prostu opowiedz mi o czymœ innym.}
{364}{}{Chyba na razie nie potrzebujê uczyæ siê czegokolwiek. Do widzenia.}
{370}{}{Twoje plemiê to g³ównie rolnicy, czy¿ nie? Chyba nie mogê ciê niczego nauczyæ.}
{371}{}{Bo i tak ju¿ jestem fachowiec, co? Dobrze wiêc, opowiedz mi o czymœ innym.}
{372}{}{A wiêc lepiej ju¿ pójdê. ¯egnam.}
{380}{}{No, to powinno nauczyæ ciê jednej albo i trzech rzeczy o naszej wspania³ej dziczy. Mam nadziejê, ¿e zrobisz z tego dobry u¿ytek. Zawsze pamiêtaj o odchodach.}
{381}{}{Masz racjê. Stare odchody smakuj¹ zupe³nie inaczej ni¿ œwie¿e. Dziêki, Cienki. A teraz opowiedz mi coœ wiêcej o tych gekonach.}
{382}{}{Dziêkujê za wszystkie wskazówki, Cienki, ale wci¹¿ uwa¿am, ¿e w¹chanie odchodów jest wystarczaj¹co dobr¹ metod¹. Zastanawia³o mnie jednak coœ jeszcze.}
{383}{}{Dziêki za informacje, Cienki. Pójdê teraz nabraæ trochê wprawy. Do widzenia.}
{390}{}{Opowiedz mi o tych szczurach.}
{400}{}{No, nieŸle ci siê wziê³o i rozwali³o tych wrednych szczurów.}
{401}{}{Hej tam. Mi³o siê ¿yje w bez-szczurzym œrodo-owisku.}
{402}{}{Tia. Mniej szczurów ni¿ kiedykolwiek.}
{403}{}{Ciekawe, co siê sta³o ze szczurami?}
{404}{}{Fachowe rozgonienie szczurzego pomiotu.}
{405}{}{Jesteœ prawdziwy Czarodziejski Flet, co nie? Dzienks.}
{406}{}{Nie ma mowy. Ten klucz mogê oddaæ za coœ z twojego ekwipunku. Nie za szybk¹ gadkê.}
