{100}{}{To chyba jakaœ tablica og³oszeniowa.}
{101}{}{Widzisz tablicê og³oszeniow¹ Klamath.}
{102}{}{Na tej tablicy znajduj¹ siê og³oszenia i oferty pracy. Niektóre z nich wisz¹ tu ju¿ chyba bardzo d³ugo.}
{110}{}{Jest tu ca³e mnóstwo papierów. Trochê og³oszeñ, oferty pracy, nawet jakiœ rysunek! Niektóre z nich wisz¹ tu ju¿ chyba bardzo d³ugo.}
{120}{}{Mo¿e rzucê okiem na ten rysunek.}
{130}{}{To brzmi nieŸle - coœ o gorzale.}
{140}{}{Jest tu coœ o k¹pieli.}
{150}{}{Ktoœ chce kupiæ skórki jaszczurek.}
{160}{}{Jakaœ notka o szczurach.}
{170}{}{Coœ o starych rupieciach.}
{180}{}{NajwyraŸniej ktoœ zagin¹³.}
{190}{}{(OdejdŸ)}
{210}{}{Nieudolny rysunek czegoœ, co przypomina braminê przekreœlon¹ znakiem 'X' i s³owem 'Torr' poni¿ej.}
{220}{}{Lepiej przyjrzê siê innym og³oszeniom.}
{230}{}{To wszystko, co chcê na razie wiedzieæ.}
{240}{}{Gorza³a - przyku³o twoj¹ uwagê, co nie? Problemy z prowadzeniem interesu. Potrzebna pomoc przy uzupe³nianiu zapasów. Tylko powa¿ne oferty. Szczegó³y poda Bob Flacha w lokalu Bucknerów.}
{250}{}{Lepiej przyjrzê siê innym og³oszeniom.}
{260}{}{To wszystko, co chcê na razie wiedzieæ.}
{270}{}{Zaginiony. Czy ktoœ widzia³ ostatnio trapera Smileya? Ma 180cm wzrostu, jest zadbany i sp³ukany (z regu³y). Zagin¹³ gdzieœ na pó³nocy i jakby mi go brakuje. -Ardin Buckner}
{280}{}{Lepiej przyjrzê siê innym og³oszeniom.}
{290}{}{To wszystko, co chcê na razie wiedzieæ.}
{310}{}{Gruba kasa za ³adne skórki. Masz skóry gekonów? Ja mam szmal. Z³ote skórki zdecydowanie kupiê. Zajrzyj do mnie - pogadamy! -Sajag, w³aœciciel knajpy Pod Z³otym Gekonem.}
{320}{}{Lepiej przyjrzê siê innym og³oszeniom.}
{330}{}{To wszystko, co chcê na razie wiedzieæ.}
{340}{}{Za du¿o szczurów w Osadzie Traperów. Za³atw ile wlezie i urz¹dŸ przyjêcie dla znajomych. Chudy.}
{350}{}{Lepiej przyjrzê siê innym og³oszeniom.}
{360}{}{To wszystko, co chcê na razie wiedzieæ.}
{370}{}{Czujesz siê zakurzony? Nie ma to jak k¹piel. Trzy weso³e œwiergotki do wyboru! W³¹cznie z piêkn¹ i utalentowan¹ Jenny (prosto z Nory) - wiêcej szczegó³ów w £aŸni.}
{380}{}{Lepiej przyjrzê siê innym og³oszeniom.}
{390}{}{To wszystko, co chcê na razie wiedzieæ.}
{400}{}{Oryginalne Antyki. Nie to, co ten z³om, co teraz robi¹. Bo teraz ju¿ takich nie robi¹. Szukasz zabytkowego towaru, to zajrzyj do Vica, wschodnia czêœæ centrum.}
{410}{}{Lepiej przyjrzê siê innym og³oszeniom.}
{420}{}{To wszystko, co chcê na razie wiedzieæ.}
{430}{}{Widzisz kawa³ek drewna obwieszony œwistkami papieru. Z wyj¹tkiem jednego wszystkie pe³ne s¹ tych dziwnych czarnych znaczków. Strasznie to wszystko skomplikowane. Lepiej poszukaj czegoœ mniej wymagaj¹cego.}
{440}{}{Gorr. (Przyjrzyj siê jedynemu sensownemu og³oszeniu.)}
{450}{}{Uuk}
{460}{}{Nieudolny rysunek czegoœ, co przypomina braminê przekreœlon¹ znakiem 'X' i s³owem 'Torr' poni¿ej. (Nie jest to mo¿e Rembrandt, ale znaczenie jest wystarczaj¹co jasne.)}
{470}{}{Eruu. (Wygl¹da na to, ¿e jakieœ biedaczysko imieniem Torr potrzebuje pomocy przy swoich braminach.)}
