{100}{}{Widzisz ma³ego ch³opca.}
{101}{}{Widzisz Jonnyego}
{102}{}{Blond w³osy, niebieskie oczy... Klasyczny przyk³ad amerykañskiego dzieciaka.}
{150}{}{£aaaaa!}
{151}{}{Chcê z powrotem mojego psa!}
{152}{}{Whimper... }
{153}{}{Obcy!}
{154}{}{Nareszcie jesteœ, Laddie! Têskni³em za tob¹, ma³y. Dziêki za przyprowadzenie mi mojego psiaka.}
{155}{}{Hej, nie widzia³em ciê tu wczeœniej.}
{156}{}{Masz na imiê Jonny?}
{157}{}{Jak siê nazywasz, ma³y?}
{158}{}{Mów, jak siê nazywasz, ty ma³y potworze.}
{159}{}{Chcia³byœ cukierka, dziecko?}
{160}{}{Witaj ponownie.}
{166}{}{Twoi rodzice wys³ali mnie za tob¹ na poszukiwania.}
{168}{}{Czy Vegeir ju¿ wie o tym, ¿e mam wróciæ?}
{169}{}{Tak. Powiedzia³, ¿e chce, aby twoi rodzice przyszli tu po ciebie.}
{170}{}{Nie, jeszcze nie.}
{171}{}{Tatuœ mówi³, ¿e Laddie poszed³ z tob¹, aby mnie szukaæ. Gdzie teraz jest? Têskniê za nim.}
{172}{}{Przykro mi, Jonny. Laddie zgin¹³, kiedy szukaliœmy ciebie.}
{173}{}{Rose obieca³a poszukaæ twojego psa.}
{174}{}{Mam na imiê Jonny. A ty?}
{175}{}{Nazywam siê }
{176}{}{.}
{177}{}{To nie jest wa¿ne.}
{178}{}{Mam na imiê Jonny, a ty mi siê nie podobasz.}
{179}{}{[Wskazuje na ciebie palcem i zaczyna krzyczeæ.] Obcy! Obcy! Obcy!}
{180}{}{Mi³o mi ciê poznaæ, }
{181}{}{.}
{182}{}{To na razie, dzieciaku.}
{183}{}{To super! Chcia³em iœæ do domu, ale Vegeir mówi, ¿e jego ludzie nie mog¹ zapuszczaæ siê tak daleko i nie bêd¹ mogli mnie wzi¹æ... Wiesz, nie ¿ebym ci nie wierzy³, ale powiedz mi: jak ma na imiê mój ojciec?}
{184}{}{Farrel}
{185}{}{Cornelius}
{186}{}{Balthas}
{187}{}{Davina.}
{188}{}{Joshua}
{189}{}{No co ty, nie wierzysz mi, Jonny?}
{190}{}{Hmm... nie. Dziêki za odnalezienie psa, ale na mnie ju¿ czas. Czeœæ.}
{191}{}{Naprawdê fajnie by³o ciê poznaæ, ale muszê ju¿ iœæ. Czeœæ.}
{192}{}{Zgadza siê! Hurrra! Wracam do domu! Zapytaj Vegeira, czy mogê z tob¹ iœæ. Po tym wszystkim, co dla mnie zrobi³, nie chcê odchodziæ bez jego zgody.}
{193}{}{Dobrze, wierzê panu. Proszê zapytaæ Vegeira czy mogê iœæ. Po tym wszystkim, co dla mnie zrobi³, nie chcê odchodziæ bez jego zgody.}
{194}{}{Dobrze, wierzê pani. Proszê zapytaæ Vegeira czy mogê iœæ. Po tym wszystkim, co dla mnie zrobi³, nie chcê odchodziæ bez jego zgody.}
{195}{}{Nie. Idê teraz pobawiæ siê z moimi kolegami. Czeœæ.}
{196}{}{Nie powinienem rozmawiaæ z nieznajomymi. Do widzenia.}
{197}{}{Tak! Sk¹d wiesz? Pewnie Laddie ci powiedzia³. To taki m¹dry piesek.}
{199}{}{Pójdziesz ze mn¹, ma³y. Chcê zebraæ nagrodê za przyprowadzenie ciê do domu.}
{200}{}{Tak, myœlê, ¿e tak bêdzie najlepiej. Wierzê ci, ale s¹dzê, ¿e Vegeir po prostu chce siê upewniæ, ¿e trafiê bezpiecznie do domu. Dziêki za pomoc.}
{201}{}{Poœpiesz siê, proszê. Chcê do domu.}
{202}{}{Nie! K³amiesz! Chcê mojego psa! [£aaaaa!]}
{203}{}{Och nie! Nie wiesz, ¿e Rose robi z psów jedzenie! Laddie jest ju¿ pewnie potrawk¹!}
{300}{}{Laddie!!!}
{400}{}{Dziêkujê, ¿e mnie pan uratowa³.}
{401}{}{Jak to dobrze byæ znowu w domu!!}
{402}{}{Juhuu...}
{403}{}{Wiesz, ju¿ nie bojê siê ciemnoœci!}
{404}{}{Dziêkujê, ¿e mnie pani uratowa³a.}
