{100}{}{Widzisz jednego z ludzi Bishopa.}
{150}{}{Widzisz zaroœniêtego mê¿czyznê ubranego w zbrojê skórzan¹. Jego cia³o pokrywaj¹ liczne blizny i rany postrza³owe.}
{151}{}{Widzisz jednego z ludzi Bishopa, trzymaj¹cego w rêkach broñ i obserwuj¹cego okolicê.}
{200}{}{Hej! }
{201}{}{::wiwatuje::}
{202}{}{::klaszcze::}
{203}{}{::gwi¿d¿e::}
{205}{}{Jak mo¿esz korzystaæ z ³azienki z czymœ takim na grzbiecie?}
{210}{}{Niez³a spluwa, }
{215}{}{Uch, po co siê tak skradasz, }
{216}{}{Uch, hej, }
{220}{}{Jo, }
{221}{}{Hej, }
{222}{}{Hej, }
{225}{}{W³azisz nie do tego lokalu, je³opie.}
{226}{}{Proszê, proszê, popatrzcie tylko na tego nadêtego sukinsyna... Zmiataj ch³optasiu, zanim ciê zestrzelimy.}
{227}{}{Ten goœæ a¿ prosi siê o k³opoty...}
{228}{}{S³ysza³em, ¿e }
{229}{}{Lepiej odejdŸ, }
{230}{}{Hej, przecie¿ to }
{231}{}{Wydawa³o mi siê, ¿e daliœmy wystarczaj¹co du¿o czasu cz³onkom rodziny }
{232}{}{W³azisz nie do tego lokalu, dziwko.}
{233}{}{Proszê, proszê, popatrzcie tylko na ta nadêta sukê...}
{234}{}{Zmiataj st¹d dziewczynko, zanim ciê zestrzelimy.}
{235}{}{Ta suka siê prosi o k³opoty...}
{236}{}{S³ysza³em, ¿e }
{250}{}{Jo, mistrzu. ¯adnych broni, dobra?}
{251}{}{Jo, mistrzu! Od³ó¿ tê broñ.}
{252}{}{Hej, }
{255}{}{Po co siê tak skradasz? }
{256}{}{Próbujesz uciec przed fanami? }
{257}{}{Uch, po co ta ca³a dyskrecja? }
{260}{}{Jo, }
{261}{}{Jo, }
{265}{}{Jo, kochasiu. ¯adnych broni, dobra?}
{266}{}{Hej, }
{267}{}{Jo, }
{268}{}{S³odziutka, nie mo¿esz wnosiæ tu broni. He he... i bez tego jesteœ doœæ zabójcza.}
{269}{}{Hej, }
{275}{}{Kociaku, z takim cia³em nie masz szans ukryæ siê w t³umie.}
{280}{}{Uwielbiam twoje filmy, }
{281}{}{Uwielbiam ciê za "Majtkix".}
{282}{}{Uwielbiam ciê za film "Ten wibrator 2".}
{283}{}{Jestem wielkim fanem twojej roli z "Archiwum XXX".}
{284}{}{Uwielbiam ciê za "Kryptê 69". To by³ inspiruj¹cy film. Kinematograficzne tour-de-force.}
{285}{}{::Gwi¿d¿e::}
{295}{}{Chcesz poszukaæ swojego ¿ywego towaru na Golgocie? Od³ó¿ tê broñ.}
{296}{}{Od³ó¿ tê broñ, albo zrobiê sobie z ciebie tarczê strzelnicz¹.}
{297}{}{Lepiej NATYCHMIAST zabezpiecz tê broñ.}
{300}{}{Chcesz poszukaæ swojego ¿ywego towaru na Golgocie? Przestañ siê skradaæ.}
{301}{}{Przestañ siê skradaæ, albo zrobiê sobie z ciebie tarcze strzelnicza.}
{302}{}{Mo¿e lepiej wróæ do szko³y ninja - a teraz przestañ siê skradaæ.}
{303}{}{Lepiej przestañ œciemniaæ z tym cichym chodzeniem. OD ZARAZ.}
{305}{}{Szukasz dla siebie grobu na Golgocie, dzikusie? Od³ó¿ to.}
{306}{}{Od³ó¿ tê broñ, dzikusie, albo zrobiê sobie z ciebie tarczê strzelnicz¹.}
{307}{}{Dzikusie, lepiej od³ó¿ tê broñ, ale JU¯.}
{310}{}{Dzikusie, szukasz dla siebie grobu na Golgocie? Przestañ siê skradaæ.}
{311}{}{Przestañ siê skradaæ, dzikusie, albo zrobiê sobie z ciebie tarczê strzelnicz¹.}
{312}{}{Mo¿e lepiej wróæ do szko³y ninja, dzikusie - a teraz przestañ siê skradaæ.}
{313}{}{Dzikusie, lepiej przestañ siê tak skradaæ, ale JU¯.}
{315}{}{Zabieraj st¹d tego robota. Ale ju¿.}
{316}{}{Zabierz st¹d tego robota zanim zrobimy sobie z niego kosz na œmieci i podpalimy.}
{317}{}{Jeœli ten robot tu zostanie, to bêd¹ z niego czêœci zamienne.}
{320}{}{*Wydawa³o* mi siê, ¿e poczu³em zapach mutanta. Lepiej zabierz st¹d tego ¿ó³tego dupka.}
{321}{}{Ty i twój zmutowany kumpel szukacie guza? Spadaj.}
{322}{}{Ten mutant lepiej niech siê st¹d wynosi, albo powiesimy sobie jego g³owê na œcianie.}
{325}{}{Widzieliœcie mo¿e wczorajsz¹ walkê?}
{326}{}{Po pracy lecê do Kociego Pazura.}
{330}{}{Myœla³em, ¿e Prezydent by³ mitem, potworem s³u¿¹cym do straszenia dzieci.}
{331}{}{To musia³o byæ prawdziwe piek³o. Odpocznij trochê. Zas³ugujesz na to.}
{332}{}{Chcieli wystrzeliæ w powietrze jakiœ nowy wirus? Dranie. Mam nadziejê, ¿e paru dosta³o od ciebie w moim imieniu.}
{333}{}{Mo¿e warto by zagraæ w tê grê jeszcze raz inn¹ postaci¹.}
{334}{}{Trzeba mieæ nie lada odwagê, ¿eby tak stawiæ czo³a Enklawie.}
{335}{}{Tak tylko chodzisz po okolicy, zbieraj¹c dodatkowe PD, co? To tylko proszê, nie zabij MNIE, dobra?}
{336}{}{Nowe Reno zosta³o zaprojektowane przez Chrisa Avellone i zaprogramowane przez Toma Frencha. Plotka g³osi, ¿e siê siê nied³ugo pobior¹.}
{337}{}{Mam nadziejê, ¿e w Falloucie 3 zostanê jedn¹ z g³ównych postaci, takich jak Tandi czy Ian. Bycie zbójem jest do bani.}
{338}{}{Tia, zaliczylem numerek z Tandi. To znaczy, jak by³a m³oda.}
{339}{}{Wiesz, ta laska Lynette desperacko potrzebuje kochania, no nie?}
{340}{}{Podobno tam, na po³udniu uda³o ci wysadziæ jak¹œ Enklawê. Bradzo odwa¿ne.}
{350}{}{Hej, }
{351}{}{Jo, }
{352}{}{Hej, }
{353}{}{Podobno Tommy Trzy Jajca wróci³ do miasta i sprawdza jak stoj¹ sprawy. Uwa¿aj na niego.}
{354}{}{Jak zobaczysz Tommy'ego Trzy Jajca, zejdŸ mu z drogi.}
{355}{}{Wstawisz siê za mn¹ u Bishopa?}
{356}{}{Niez³e ciuchy. Te¿ bym chcia³ ¿eby szef mi na takie pozwoli³.}
{357}{}{Jakieœ rady dla goœcia takiego jak ja?}
{358}{}{Rodzina Bishopów zawsze by³a dla mnie dobra.}
{359}{}{John Bishop bêdzie rz¹dzi³ tym miastem.}
{360}{}{Strasznie dziœ cicho.}
{361}{}{Idzie burza.}
{362}{}{Zesz³ej nocy smród od Golgoty by³ nie do wytrzymania.}
{363}{}{Kiedy wreszcie skopiemy jak¹œ rodzinê?}
{364}{}{Gdy jesteœ z nami, inne rodziny nie maj¹ szans, szefie.}
{365}{}{Chcesz czegoœ szefie?}
{366}{}{Jakieœ wieœci o innych rodzinach?}
{367}{}{Um, masz mo¿e Jet?}
{368}{}{Kurczê, napi³bym siê czegoœ...}
{369}{}{Pani Bishop znowu mi siê przygl¹da³a. To jest krêpuj¹ce.}
{370}{}{Pani Bishop ci¹gle patrzy na mnie jak na po³eæ miêsa. Oby w koñcu zauwa¿y³a, ¿e chcê tylko, ¿eby mnie ktoœ przytuli³.}
{371}{}{Ta córunia Bishopa to niez³a dupcia.}
{372}{}{Ta córunia Bishopa to same k³opoty.}
{373}{}{Podobno jeden z ch³opców upi³ córkê Bishopa, pan Bishop go za to obdar³ ze skóry.}
{374}{}{Jeœli idziesz do Bishopa, trzymaj siê z dala od jego ¿ony i córki... mo¿esz sobie przez nie narobiæ k³opotów.}
{380}{}{Podobno pani Bishop ciê szuka. Uwa¿aj, ch³opie.}
{381}{}{Podobno córka Bishopa ciê szuka. To ci mo¿e narobiæ k³opotów.}
{382}{}{Nie patrz tak spode ³ba, panie Mistrzowski Pas.}
{383}{}{Wiesz, rodziana Bishopów mog³aby mieæ wielki po¿ytek z kogoœ takiego jak ty. Kogoœ twardego. Bezkompromisowego.}
{384}{}{Musisz pogadaæ z Bishopem o pracy.}
{385}{}{Rozwa¿, czy by siê do nas nie przy³¹czyæ. To my bêdziemy rz¹dziæ Nowym Reno.}
{386}{}{Postawi³em na ciebie $20!}
{387}{}{Hej, mistrzu! Ta ostatnia walka by³a œwietna!}
{388}{}{Widzieliœmy twoj¹ ostatni¹ walkê. Masz cholernie mocny prawy sierpowy.}
{389}{}{Bêdziesz jeszcze walczyæ? Postawi³em na ciebie $30.}
{390}{}{Ile wyciskasz?}
{391}{}{Gdzie pakujesz?}
{392}{}{Uwa¿aj na Masticatora. On ma s³aboœæ do uszu.}
{393}{}{Postawi³bym ci drinka, ale przepuœci³em ca³¹ forsê stawiaj¹c na twojego przeciwnika.}
{394}{}{Pobaraszkujemy trochê?}
{395}{}{Nie wygl¹dasz na zbyt tward¹, panno Lewy Sierpowy.}
{396}{}{Mogê zobaczyæ jak ruszasz swoimi miêœniami brzusznymi?}
{400}{}{Podobno pani Bishop ciê szuka. Uwa¿aj, ch³opie.}
{401}{}{Ch³opie, znalaz³byœ mi robote? No weŸ. Jestem królem ogierów.}
{402}{}{Uwielbiam twoje filmy, }
{403}{}{Uwielbiam ciê za "Majtkix".}
{404}{}{Uwielbiam ciê za film "Ten wibrator 2".}
{405}{}{Jestem wielkim fanem twojej roli z "Archiwum XXX".}
{406}{}{Uwielbiam ciê za "Kryptê 69". To by³ natchniony film.}
{407}{}{Podobno córka Bishopa ciê szuka. To ci mo¿e narobiæ k³opotów.}
{408}{}{Macie jakieœ wakaty w studio?}
{409}{}{Uwielbiam ciê za "Kryptê 69". To by³ natchniony film.}
{410}{}{Podobno Tommy Trzy Jajca chce ciê zaprosiæ na prywatny pokaz.}
{411}{}{Uwielbiam twój ostatni film. Czy mogê pomóc ci w próbach do nastêpnego?}
{412}{}{Za³atw mi pracê, a poka¿ê ci kilka moich tajnych ciosów.}
{413}{}{Kiedy wpadniesz zobaczyæ siê ze mn¹?}
{414}{}{Hej, bêdziesz tu tañczyæ wieczorem?}
{415}{}{Kochanie, wygl¹dasz zabójczo.}
{416}{}{Pani Fortuna zrobi siê zazdrosna, jeœli bêdziesz tu tak czêsto przychodziæ.}
{420}{}{Jak siê maj¹ sprawy w Norze?}
{421}{}{Czy to bola³o jak ci robili ten tatua¿?}
{422}{}{Zastanawia³em siê, czy nie zostaæ ³owc¹ niewolników, ale nie znoszê tego ci¹g³ego podró¿owania.}
{423}{}{Szukasz stajni? To tam trzyma siê wiêkszoœæ niewolników.}
{424}{}{Byæ w rodzinie Bishopów to niez³a fucha.}
{425}{}{Przywozisz now¹ dostawê niewolników, czy wywozisz?}
{426}{}{Potrzeba wam nowego zaopatrzenia... ta ostatnia dostawa niewolników by³a do dupy.}
{427}{}{£apiecie jeszcze niewolników z dzikich plemion?}
{428}{}{Jaki jest bie¿¹cy kurs niewolnika?}
{429}{}{Niewolnicy, braminy, jeden pies.}
{440}{}{Jeœli szukasz pracy, to przyda³by nam siê taki ktoœ jak ty. Pogadaj z panem Bishopem.}
{441}{}{Szukasz pracy? Mo¿esz o tym porozmawiaæ z panem Bishpem.}
{445}{}{Odwal siê, dzikusie.}
{446}{}{Nie mam dla ciebie ¿adnych prochów, dzikusie.}
{447}{}{IdŸ paliæ sobie swoje fajki pokoju, dzikusie.}
{448}{}{NIE mam ochoty na pogaduszki. Spadaj.}
{449}{}{Spieprzaj dzikusie.}
{450}{}{Wiesz kim jestem? Jestem cz³owiekiem Bishopa. Odpieprz siê ode mnie.}
{451}{}{Chcesz mnie wkurzyæ? To nie bêdzie mi³e jak siê wkurzê.}
{452}{}{Odchrzañ siê zanim zrobiê sobie z ciebie tarczê strzelnicz¹.}
{453}{}{Szukasz k³opotów? Gadaj do mnie tak dalej, to zobaczysz, co siê stanie.}
{460}{}{Nie szukam teraz ¿adnej wioskowej dupy. PrzyjdŸ kiedy indziej.}
{461}{}{Nie mam czasu, ¿eby siê teraz tob¹ zajmowaæ. Mo¿e przyjdŸ póŸniej?}
{462}{}{Nie, nie wiem gdzie to jest, a teraz odwal siê! ::G³upie dzikusy.::}
{463}{}{Odwal siê, dzikusie.}
{464}{}{Bishopowie nie gadaj¹ z wioskowymi œmieciami, maj¹ lepsze rzeczy do roboty.}
{465}{}{Nie mam dla ciebie ¿adnych prochów, dzikusie.}
{466}{}{IdŸ paliæ sobie swoje fajki pokoju, dzikusie.}
{467}{}{NIE mam ochoty na pogaduszki. Spadaj.}
{468}{}{Spieprzaj dzikusie.}
{469}{}{Wiesz kim jestem? Jestem cz³owiekiem Bishopa. Odpieprz siê ode mnie.}
{470}{}{Chcesz mnie wkurzyæ? To nie bêdzie mi³e jak siê wkurzê.}
{471}{}{Odchrzañ siê zanim zrobiê sobie z ciebie tarczê strzelnicz¹.}
{472}{}{Szukasz k³opotów? Gadaj do mnie tak dalej, to zobaczysz, co siê stanie.}
{473}{}{Nie jestem a¿ tak zapity. Spadaj.}
{474}{}{Jesteœ chyba najbrzydsz¹ dzikusk¹, jak¹ kiedykolwiek widzia³em.}
{475}{}{Zmiataj st¹d, zanim ciê tak pobijê, ¿e zrobisz siê jeszcze brzydsza.}
{476}{}{IdŸ suko szczekaæ na kogoœ bardziej pijanego ode mnie.}
{490}{}{*Wydawa³o* mi siê, ¿e poczu³em zapach zgnilizny. Zabierz st¹d tego swojego ghulika.}
{491}{}{Zabieraj st¹d tego œmierdz¹cego ghula. Ale ju¿!}
{492}{}{Jeœli ten ghul zaraz st¹d nie zniknie, bêdzie jeszcze bardziej martwy.}
{1200}{}{! Enklawa nie mia³a szans!}
{1210}{}{.}
{1215}{}{?}
{1216}{}{... po co robiæ takie tajemnice?}
{1220}{}{, cojezd?}
{1221}{}{, co kombinujesz?}
{1222}{}{! Trzymasz siê zdala od k³opotów?}
{1228}{}{ to banda wymoczków. Co ty na to?}
{1229}{}{. Natychmiast.}
{1230}{}{. Czy twojej rodzinie nie bêdzie ciê brakowa³o?}
{1231}{}{, aby zrobili coœ wiêcej, ni¿ tylko ca³owanie ty³ka swojemu szefowi.}
{1236}{}{ to banda wymoczków. Teraz wiem ju¿, ¿e to prawda.}
{1252}{}{! Nie mo¿esz wnosiæ tu broni, no nie?}
{1260}{}{. Dbasz o siebie?}
{1261}{}{. Co jest?}
{1266}{}{! Nie mo¿esz wnosiæ tu broni, no nie?}
{1267}{}{! Od³ó¿ tê broñ.}
{1269}{}{! Mo¿esz trzymaæ na wierzchu cycki, ale nie mo¿esz trzymaæ na wierzchu broni, dobra?}
{1280}{}{!}
{1350}{}{. Co siê dzieje?}
{1351}{}{. Cojezd?}
{1352}{}{. rzymasz siê zdala od k³opotów?}
{1402}{}{!}
