# quick look
{100}{}{Widzisz sta³ego goœcia kasyna.}

# examines
{150}{}{Widzisz jednego z bywalców kasyna. Wygl¹da na zmêczonego.}
{151}{}{Widzisz jednego z bywalców kasyna. W jego oczach widaæ z³ote odblaski.}
{152}{}{Widzisz jednego z bywalców kasyna. Skrywa twarz w d³oniach.}
{153}{}{Widzisz jednego z bywalców kasyna. Jest chyba trochê podchmielony.}
{154}{}{Widzisz jednego z bywalców kasyna. Rzuca ci mrugniêcie okiem i odtacza siê na bok.}
{155}{}{Widzisz jednego z bywalców kasyna. Stara siê zwróciæ na siebie uwagê kelnerki.}
{156}{}{Widzisz jedn¹ z bywalczyñ kasyna. Wygl¹da na zmêczon¹.}
{157}{}{Widzisz jedn¹ z bywalczyñ kasyna. W jej oczach widaæ z³ote odblaski.}
{158}{}{Widzisz jedn¹ z bywalczyñ kasyna. Skrywa twarz w d³oniach.}
{159}{}{Widzisz jedn¹ z bywalczyñ kasyna. Jest chyba trochê podchmielona.}
{160}{}{Widzisz jedn¹ z bywalczyñ kasyna. Rzuca ci mrugniêcie okiem i odtacza siê na bok.}
{161}{}{Widzisz jedn¹ z bywalczyñ kasyna. Stara siê zwróciæ na siebie uwagê kelnera.}

# float
{200}{}{::Klaszcze::}
{201}{}{::Wiwatuje::}
{202}{}{Ale¿ ta Enklawa dosta³a po dupie! Dobra robota!}
{203}{}{Ale ci siê uda³o z t¹ Enklaw¹, }
{204}{}{Gratulacje z okazji zgnicenia Enklawy, }
{205}{}{Gratulacje z okazji zgnicenia Enklawy, }
{206}{}{Uch-och. ZejdŸcie z drogi.}
{207}{}{Mam dreszcze od samego patrzenia na niego... na ni¹... na to... *cokolwiek* to jest.}
{208}{}{Myœlicie, ¿e to coœ da komuœ po ³bie?}
{209}{}{Oto piekielna furia z krwi i koœci. Uch, to znaczy, pod tym pancerzem.}
{210}{}{Lepiej nie w³aŸcie temu czemuœ w drogê.}
{211}{}{Skoro ju¿ o mowa o groŸnym wygl¹dzie...}
{212}{}{*Gulp*}
{213}{}{Myœlê, ¿e ten Pan Roboto mnie namierza.}
{214}{}{Ten chodz¹cy czo³g w³aœnie chyba ¿yczy³ mi œmierci. Zmiatam st¹d.}
{215}{}{Podobno to coœ sfragowa³o wczoraj trzech p³atnych zabójców.}
{216}{}{Dostajê dreszczy od samego patrzenia na niego.}
{217}{}{Myœlicie, ¿e on chce daæ komuœ po ³bie?}
{218}{}{ZejdŸcie z drogi temu facetowi.}
{219}{}{On mi siê chyba przygl¹da.}
{220}{}{On mi chyba w³aœnie ¿yczy³ œmierci. Zmiatam st¹d.}
{221}{}{Podobno on wczoraj zastrzeli³ trzech p³atnych zabójców.}
{222}{}{Uch-och. ZejdŸcie z drogi.}
{223}{}{Oto piekelna furia z krwi i koœci.}
{224}{}{Skoro ju¿ mowa o groŸnym wygl¹dzie...}
{225}{}{*Gulp*}
{226}{}{La Femme Nikita, coœtam coœtam.}
{227}{}{Dostajê dreszczy od samego patrzenia na ni¹.}
{228}{}{Myœlicie, ¿e ona chce daæ komuœ po ³bie?}
{229}{}{Ona mi siê chyba przygl¹da.}
{230}{}{Ona mi chyba w³aœnie ¿yczy³a œmierci. Zmiatam st¹d.}
{231}{}{Podobno ona wczoraj zastrzeli³a trzech p³atnych zabójców.}
{232}{}{Ale babka! To znaczy, twarda babka.}
{233}{}{Nie wygl¹dasz wcale na takiego twardego, panie Mistrz Wagi ciê¿kiej.}
{234}{}{Stawiam na ciebie 20 dolców!}
{235}{}{Hej, miszczuniu! Ta ostatnia walka by³a œwietna!}
{236}{}{Widzieliœmy ciê w ringu. Naprawdê niez³y masz ten prawy sierpowy.}
{237}{}{Bêdziesz jeszcze walczyæ? Stawiam na ciebie 30 dolców.}
{238}{}{Ile wyciskasz?}
{239}{}{Gdzie pakujesz?}
{240}{}{Uwa¿aj na Prze¿uwacza. On ma s³aboœæ do uszu.}
{241}{}{Postawilibyœmy ci drinka, gdybyœmy ni stracili wszystkich pieniêdzy stawiaj¹c na twojego przeciwnika.}
{242}{}{Nie wygl¹dasz wcale tak twardo, panno Lewy Sierpowy.}
{243}{}{Czy mogê zobaczyæ jak napinasz swoje miêœnie brzuszne?}
{244}{}{Hejhejhej. Zobaczcie.}
{245}{}{No tylko popatrzcie na *to*!}
{246}{}{::Rusza ustami, jakby chcia³ powiedzieæ "kurde".::}
{247}{}{WIEDZIA£EM, ¿e powinienem siê dziœ ogoliæ.}
{248}{}{ChodŸ tu na chwilê, s³odziutka, i pogadajmy.}
{249}{}{Te dzikuski to dopiero maj¹ cyce! Kurde!}
{250}{}{Popatrzcie tylko na zderzaki tej dzikuski.}
{251}{}{Oto najlepsza koza z mojego stada.}
{252}{}{Dla tej kobiety móg³bym siê nawet wyk¹paæ.}
{253}{}{Mam tu zaraz przy sobie twoj¹ ¿y³ê z³ota.}
{254}{}{Potrz¹œnij nimi!}
{255}{}{Wypnij siê!}
{256}{}{::Gwi¿d¿e::}
{257}{}{Te twoje nogi naprawdê s¹ takie d³ugie?}
{258}{}{Kuuuuurde.}
{259}{}{}
{260}{}{Mo¿e dziœ zatañczy.}
{261}{}{Widzieliœcie jej ostatni film? Rozgrzewa do czerwonoœci, mówie wam, do CZERWONOŒCI.}
{262}{}{Przepraszam. Muszê iœæ na chwilê do ³azienki, ¿eby siê, eeee, uczesaæ.}
{263}{}{Chcia³bym byæ jej majtkami.}
{264}{}{Chcia³bym byæ jej bielizn¹.}
{265}{}{Chcia³bym pow¹chaæ jej szorty.}
{266}{}{Niez³a z niej sztuka.}
{267}{}{Kurde. Same zakrêty, a ja nie mam hamulców.}
{268}{}{Proszê proszê, wiiiitaj ogierze.}
{269}{}{Potrzebne ci mo¿e siod³o ogierze? Jutro wieczorem jestem do wziêcia.}
{270}{}{Co porabiasz wieczorem marynarzu?}
{271}{}{Czy mogê dotkn¹æ twoich miêœni?}
{272}{}{Jak to mo¿liwe, ¿e nie mdlejesz, gdy ci staje?}
{273}{}{Chcesz zajrzeæ do mnie na drinka?}
{274}{}{Chcê zjeœæ kolacjê z twojej klaty.}
{275}{}{Potrzebujesz towarzystwa do nastêpnego filmu?}
{276}{}{::Gapi siê na twoje bicepsy.::}
{277}{}{Czy to coœ, co za tob¹ ³azi, to jakaœ nowa odmiana automatu do gry?}
{278}{}{Czy to jakiœ robo-automat do gry?}
{279}{}{Czy twój robot potrafi robiæ szkuczki? Uch... to znaczy, magiczne sztuczki.}
{280}{}{To brzmi gorzej ni¿ opowieœci o ¿elaznym wilku.}
{281}{}{}
{282}{}{Dzidzi potrzebuje nowej pary butów...}
{283}{}{Cholerni turyœci za trzy centy...}
{284}{}{Cholera! A by³o ju¿ *53* dolary na plus...}
{285}{}{Takie ju¿ moje psie szczêœcie...}
{286}{}{Tak ma³o brakowa³o!}
{287}{}{Rozbijê bank.}
{288}{}{Ja? Rozbijam bank. Tylko popatrz.}
{289}{}{Los jest przeciwko mnie.}
{290}{}{Szczêœcie mi nie sprzyja.}
{291}{}{Nie zawiedŸ mnie teraz Fortuno.}
{292}{}{Los zlitowa³ siê nade mn¹.}
{293}{}{Miêdzy ustami a brzegiem morza wódzi...}
{294}{}{Obstawiaj tak dalej, a Golgota stanie siê twoim domem...}
{295}{}{Kelnerka, jeszcze jednego!}
{296}{}{Kelner, jeszcze jednego!}
{297}{}{Te drinki smakuj¹... dziwnie.}
{298}{}{Mam goro¹czkê!}
{299}{}{Czy¿by skoñczy³y mi siê ju¿ pieni¹dze?}
{300}{}{Fortuna to niesta³a dziwka, zupe³nie jak moja macocha.}
{301}{}{Ostatnio du¿o w mieœcie ³owców niewolników.}
{302}{}{Ciekawe, co siê dzieje w tych stajniach za miastem.}
{303}{}{Nied³ugo mo¿e siê zacz¹æ nowa wendetta.}
{304}{}{Cholerni podró¿ni, wszêdzie siê tu krêc¹...}
{305}{}{Œwietnie, nastêpny tani gracz.}
{306}{}{ALE mam szczêœcie.}
{307}{}{Wyœpiê siê jak umrê.}
{308}{}{O ludzie, muszê siê wysikaæ. Zaczyna siê ze mnie wylewaæ.}
{309}{}{O ludzie, muszê iœc wyprowadziæ ptaszta na spacer.}
{310}{}{Kurde, wpuszczaj¹ tu teraz byle kogo.}
{311}{}{Dawaj 7!}
{312}{}{Al emasz krzepê, kochanie.}
{313}{}{I kto jest dzisiaj wielkim zwyciêzc¹? Mikey!}
{314}{}{Nie schrzañ tego... no dawaj...}
{315}{}{Mam odrzutowy 'cug'... jeœli wiesz, co mam na myœli.}
{316}{}{STRASZNE bzdury.}
{317}{}{Jestem tylko 60 dolców do ty³u. To znaczy, przez pierwsze piêæ minut.}
{318}{}{Czerwone 23! Czerwone 23! No dawaj, czerwone 23...}
{319}{}{50 dolców na Czarne 15...}
{320}{}{Krêci siê i krêci... gdzie siê zatrzyma, nie wie nikt...}
{321}{}{Œwietnie ci siê uda³o wysadziæ tych drani z Enklawy! Dobra robota!}
{322}{}{Zawsze wiedzieliœmy, ¿e Prezydent chcia³ nas wszystkich zabiæ.}
{323}{}{To Prezydent by³ wci¹¿ ¿ywy? Kiedy by³y ostatnie wybory?}
{324}{}{Zniszczy³o siê Enklawê, co? No, niech¿e wiêc postawiê ci drinka.}
{325}{}{Dziêki tobie Enklawa dosta³a za swoje. Brawo }
{326}{}{Wraz ze zniszczeniem Enklawy to kasyno sta³o siê lepszym miejscem dla moich dzieci. Jak ja ci siê odwdziêczê?}
{327}{}{Enklawa nigdy ze mn¹ nie zadziera³a, ale cieszê siê, ¿e ju¿ jej nie ma.}
{328}{}{Nie mogê uwierzyæ, ¿e ludzie z Enklawy wci¹¿ byli na wojnie, choæ minê³o ju¿ tyle czasu. Idioci.}
{329}{}{Odczuliœmy tu dziwny niepokój... jakby setka wrednych drani na platformie wiertniczej nagle zakrzyknê³a z przera¿enia i zosta³a równie nagle uciszona. Dziwne.}
{330}{}{Brawka z okazli zgniecenia Enklawy, }
{331}{}{Brawka z okazli zgniecenia Enklawy, }
{332}{}{Szukasz swojego brata Robby'ego? No wiesz, Robota? Ech, niewa¿ne.}
{333}{}{Przepraszem, stojê ci na drodze? Odejdê z miasta.}
{334}{}{Przepraszam, czy oddycham twoim powietrzem? Przestanê.}
{335}{}{Nie przysz³o mi do g³owy, ¿e ktoœ robi drzwi w twoim rozmiarze.}
{336}{}{::Stuka w zbrojê:: Jest tam kto?}
{337}{}{"Uwaga, nadchodzi Will Robinson! Uwaga, nadchodzi Will Robinson!" he he. Uch... to tylko taki ¿art.}
{338}{}{£aaaaadna zbroja. Masz tam klimatyzacjê?}
{339}{}{Nie jest ci w tym za gor¹co?}
{340}{}{Czy mogê dotkn¹æ koœæmi twojej zbroi na szczêœcie?}
{341}{}{Straci³eœ swoje serce, ¿elazny drwalu?}
{342}{}{Uch, dzieñ dobry panu... lub pani... lub kimkolwiek jesteœ.}
{343}{}{Przeka¿ wyrazy szacunku temu, kto da³ ci tê zbrojê.}
{344}{}{Czy wszystko u pana... pani... uch, czymkolwiek jesteœ, wszystko w porz¹ku?}
{345}{}{Jesteœ nowym bramkarzem? Czy mo¿e jak¹œ chodz¹c¹ gr¹ zrêcznoœciow¹?}
{346}{}{Nie, NIE mam ochoty oliwiæ twoje zawiasy.}
{347}{}{Czy twoja zbroja mo¿e zmieniæ siê w odrzutowiec i odlecieæ? Tak tylko pytam.}
{348}{}{Jasne, jasne, ty te¿ "dzyñ, trrrr, dzyñ".}
{349}{}{Jeœli myœlisz, ¿e ta zbroja mnie onieœmiela, to masz racjê.}
{350}{}{Musisz byæ jedn¹ z tych przedwojennych konsol do gry.}
{351}{}{S³uchaj, proszê ciê... nie szukam k³opotów. Jestem tu tylko przejazdem.}
{352}{}{S³uchaj, proszê ciê... nie szukam k³opotów.}
{353}{}{Przepraszem, stojê ci na drodze? Odejdê z miasta.}
{354}{}{Przepraszam, czy oddycham twoim powietrzem? Przestanê.}
{355}{}{Przeka¿ pozdrowienia swojemu szefowi.}
{356}{}{Uch... *glup*... wszystko w porz¹dku?}
{357}{}{S³uchaj, proszê ciê... nie szukam k³opotów. Jestem tu tylko przejazdem.}
{358}{}{S³uchaj, proszê ciê... nie szukam k³opotów.}
{359}{}{Sprzedajesz?}
{360}{}{Czy mogê kupiæ twoje ciuchy? To znaczy - tu, na miejscu?}
{361}{}{WIEDZIA£EM, ¿e trzeba by³o siê dziœ ogoliæ.}
{362}{}{Choæ tu, s³odziutka, i pogadaj ze mn¹.}
{363}{}{No, œlicznoœci, pospacerujmy.}
{364}{}{Jesteœ ma³a zwinna pinda, co nie?}
{365}{}{Dla ciebie móg³bym siê nawet wyk¹paæ.}
{366}{}{Mam tu pod rêk¹ twoj¹ ¿y³ê z³ota.}
{367}{}{Te twoje nogi naprawdê s¹ takie d³ugie?}
{368}{}{Bêdziesz tañczyæ dziœ wieczorem?}
{369}{}{Przepraszam. Muszê iœæ na chwilê do ³azienki, ¿eby siê, eeee, uczesaæ.}
{370}{}{Chcia³bym byæ twoj¹ bielizn¹.}
{371}{}{Chcia³bym pow¹chaæ twoje szorty.}
{372}{}{Ale z ciebie niez³a sztuka.}
{373}{}{Popraw mnie, jeœli siê mylê, ale czy nie chcesz przypadkiem daæ mi buziaka?}
{374}{}{Kurde. Same zakrêty, a ja nie mam hamulców.}
{375}{}{Wiesz, co by dobrze na tobie le¿a³o? Ja.}
{376}{}{Twoje spodnie nie s¹ mo¿e najwspanialsz¹ rzecz¹ na ziemi, ale maj¹ do niej bardzo blisko.}

{503}{}{!}
{504}{}{! Rz¹dzisz! RZ¥DZISZ!}
{505}{}{! Jesteœ jak ¿y³a Z£OTA!}
{625}{}{!}
{630}{}{! Rz¹dzisz! RZ¥DZISZ!}
{631}{}{! Jesteœ jak ¿y³a ¯£OTA!}
