# 0. QUICK LOOK
{100}{}{Widzisz Chrisa Wrighta.}

# 0. LOOK
{150}{}{Widzisz wysokiego, m³odego cz³owieka. Jego strój stanowi gustowne po³¹czenie skóry i ³añcuchów.}
{151}{}{Widzisz Chrisa Wrighta.}
{152}{}{Widzisz Chrisa Wrighta. Wygl¹da na œmiertelnie znudzonego.}

# 1. FLOAT DIALOGUE: ENCLAVE DESTROYED IS TRUE (WTG)
{200}{}{Hej! }
{201}{}{Niez³a jazda, }
{202}{}{Dobra robota, }
{203}{}{::Wiwatuje::}
{204}{}{::Klaszcze::}
{205}{}{::Gwi¿d¿e::}

# 2. FLOAT DIALOGUE: POWER ARMOR (WTG)
{215}{}{Jak sobie radzisz w toalecie z ca³ym tym ¿elastwem na sobie?}

# 3. FLOAT DIALOGUE: WARNING - PLAYER IS MADE MAN (WTG)
{220}{}{Sie ma, }
{221}{}{Straszny upa³, co nie, }
{222}{}{Sie ma, }

# 4. FLOAT/CLICK (DAD IS DEAD) (WTG)
{230}{}{Wci¹¿ nie mogê uwierzyæ, ¿e Tato nie ¿yje. Tak wielu rzeczy nie zd¹¿y³em mu powiedzieæ...}

# 5. FLOAT/CLICK [MALE, MADE MAN, FA = WRIGHT, NORM] (WTG)
{235}{}{Spieprzaj.}
{236}{}{Spieprzaj st¹d. Mówiê serio.}
{237}{}{Nie mamy o czym gadaæ.}

# 6. INTRO (NORMAL) (WTG)
{245}{}{Taa?}
{246}{}{Hej! Co s³ychaæ, }
{1246}{}{? Wszystko w porz¹dku? Potrzebujesz czegoœ?}
{247}{}{Hej, dziêki za odkrycie kto zabi³ Richarda, }
{248}{}{. Jestem twoim d³u¿nikiem, a Wrightowie zawsze sp³acaj¹ d³ugi. Mogê coœ dla ciebie zrobiæ?}
{249}{}{Matria. Myœ to matria!}
{250}{}{Ha³abuba.}
{251}{}{OdejdŸ}
{252}{}{Kim jesteœ?}
{253}{}{Prawdê mówi¹c, tak. Szukam pracy. Mo¿e Wrightowie potrzebuj¹ kogoœ do pomocy?}
{254}{}{S³uchaj, rozmawialiœmy ostatnio z twoj¹ mam¹.}
{255}{}{Opowiesz mi o Richardzie?}
{256}{}{Nic, dziêkujê. Mi³o siê rozmawia³o.}

# 7. RETARD (6)
{265}{}{Spieprzaj st¹d, przyg³upie. Nie bêdê z tob¹ rozmawia³ w jêzyku migowym.}
{266}{}{OdejdŸ}

# 8. WHO ARE YOU? (6)
{275}{}{Jestem Chris. Chris Wright. Z rodziny Wrightów. Podoba ci siê ta odpowiedŸ?}
{276}{}{Czemu nie. Szukam pracy. Mo¿e twojej rodzinie przyda siê ktoœ taki jak ja?}
{277}{}{Rodzina Wrightów? Kto to?}
{278}{}{Chris Wright, tak? Znam twoj¹ mamê.}
{279}{}{Mo¿esz mi powiedzieæ, co siê sta³o z twoim bratem, Richardem?}
{280}{}{Wcale. Do widzenia.}

# 9. FAMILY WRIGHT? WHO'S THAT? (8, 10, 12)
{290}{}{Nie wiesz kim jest rodzina Wrightów? Pierwszy raz w mieœcie, czy zbyt d³ugo na pustyni? Wrightowie to najwiêksza rodzina przestêpcza w Reno. Nied³ugo bêdziemy rz¹dziæ tym miastem.}
{291}{}{Serio? Wygl¹da na to, ¿e macie wszystkie asy w rêkawie. Mo¿e przyda wam siê ktoœ taki jak ja?}
{292}{}{Prawdê mówi¹c, odnoszê wra¿enie, ¿e to jedna z najs³abszych rodzin... No wiesz, zajmujecie siê wy³¹cznie alkoholem, nie macie kasyna, nie handlujecie prochami. No i nie jesteœcie zbyt liczni, w porównaniu z innymi rodzinami.}
{293}{}{Skoro o rodzinie mowa, znam twoj¹ mamê.}
{294}{}{Mo¿esz mi opowiedzieæ, co przydarzy³o siê twojemu bratu, Richardowi?}
{295}{}{Naprawdê? To bardzo ciekawe... s³uchaj, muszê ju¿ iœæ.}

# 10. QUESTIONS (15, 16, 17, 18, 19, 20, 22, 25, 26, 28)
{305}{}{Na przyk³ad?}
{306}{}{Mo¿esz mi opowiedzieæ o rodzinie Wrightów?}
{307}{}{Mo¿e Wrightom przyda siê ktoœ taki jak ja?}
{308}{}{Rozmawialiœmy ostatnio z twoj¹ mam¹. Bardzo mi³a pani.}
{309}{}{Mo¿esz mi opowiedzieæ, co przydarzy³o siê twojemu bratu, Richardowi?}
{310}{}{Nie, nie mam wiêcej pytañ. Lepiej ju¿ pójdê.}

# 11. INTRO (SLAVER) (WTG)

{315}{}{(M³ody mê¿czyzna odwraca siê w twoj¹ stronê, ogl¹da ciê uwa¿nie. Jego oczy zatrzymuj¹ siê na tatua¿u na twoim czole) No proszê. (Parska, spluwa ci pod nogi) Masz brudne buty, £owco. Wygl¹dasz jak niechluj. Mo¿e pora coœ z tym zrobiæ?}
{316}{}{(M³ody mê¿czyzna odwraca siê w twoj¹ stronê, ogl¹da ciê uwa¿nie) No proszê. (Parska, spluwa ci pod nogi) Masz brudne buty. Wygl¹dasz jak niechluj, przydupasie [FA]. Mo¿e pora coœ z tym zrobiæ?}
{317}{}{Kopnij go butem, który oplu³.}
{318}{}{OdejdŸ}
{319}{}{Daj mu spokój i odejdŸ. Wyrównasz rachunki nastêpnym razem.}

# 12. I'M LOOKING FOR A JOB... [GOOD RESPONSE] (6, 8, 9, 10)
{325}{}{Có¿... ja... to znaczy rodzina Wrightów... moja rodzina... mo¿e mieæ dla ciebie jak¹œ robotê. Nic nie obiecujê, ale zajrzyj do posiad³oœci, na po³udnie st¹d, znajdŸ mojego brata, Keitha, i powiedz mu, ¿e ja ciê przysy³am. Jestem Chris. Chris Wright.}
{326}{}{Rodzina Wrightów? Kto to taki?}
{327}{}{Wright, tak? Znam twoj¹ mamê.}
{328}{}{Opowiesz mi co przydarzy³o siê twojemu bratu, Richardowi?}
{329}{}{Dziêki. Porozmawiam z nim.}


# 13. I'M LOOKING FOR A JOB... [BAD RESPONSE] (6, 8, 9, 10)
{335}{}{Raczej nie, nie potrzebujemy wiêcej ludzi. W Nowym Reno nie ³atwo teraz o pracê u którejœ z rodzin.}
{336}{}{No to trudno.}

# 14. I RAN INTO YOUR MOM (NORMAL) (6, 9, 10, 11, 12)
{345}{}{Œwieeetnie. D³ugo glêdzi³a?}
{346}{}{Trochê. Nie lubisz swojej matki?}
{347}{}{Ani trochê. A zwykle glêdzi?}
{348}{}{Raczej nie. S³uchaj, muszê ju¿ iœæ.}

# 15. I RAN INTO YOUR MOM (INSULT) (9, 16)
{355}{}{Co to ma byæ - DOWCIP? Jeœli tak, to za cholerê nie by³ œmieszny. Chcesz zacz¹æ z rodzin¹ Wrightów, m¹dralo?}
{356}{}{Zacz¹æ? Nie, ja chcê z ni¹ SKOÑCZYÆ.}
{357}{}{Przepraszam, to nie mia³o tak zabrzmieæ. Mam jeszcze kilka pytañ...}
{358}{}{Ale¿ sk¹d! Lepiej bêdzie, jak sobie st¹d pójdê.}

# 16. DO YOU NOT LIKE YOUR MOM? (14)
{365}{}{Ona po prostu nie zwraca uwagi na to, co siê dzieje wokó³ niej. Kocham j¹, itd., ale czasem potrafi byæ œlepa jak nietoperz.}
{366}{}{Có¿, ca³kiem niedawno wpad³a do piwnicy, w której trzymamy aparaturê destylacyjn¹ i rozwali³a wszystko w drobny mak. Ca³y zacier diabli wziêli! Kocham j¹, itd., ale czasem potrafi byæ œlepa jak nietoperz.}
{367}{}{He he. Wygl¹da te¿ podobnie.}
{368}{}{Œlepa? Co masz na myœli?}
{369}{}{Rozumiem. Mam jeszcze kilka pytañ...}
{370}{}{Pewnie masz racjê. Niestety, muszê ju¿ iœæ.}

# 17. WHAT DO YOU MEAN? (16)
{380}{}{Prawi wszystkim kazania o trzeŸwoœci, ¿yciu bez grzechu i takich tam, a nie ma nawet pojêcia czym zajmuje siê Tato. Albo nie wie, albo nie chce wiedzieæ.}

{381}{}{A czym zajmuje siê twój Tato?}
{382}{}{Hmmmm. Mam jeszcze kilka pytañ...}
{383}{}{To ciekawe. Có¿, muszê ju¿ iœæ.}

# 18. WHAT DOES YOUR DAD DO? (17)
{390}{}{Pêdzi bimber, handluje broni¹, zabija ludzi, którzy próbuj¹ go or¿n¹æ... to co ka¿da g³owa rodziny. Mama bardzo by siê wkurzy³a, gdyby wreszcie przejrza³a na oczy. A zw³aszcza, jakby znalaz³a tê aparaturê destylacyjn¹.}
{391}{}{Jak bardzo by siê wkurzy³a?}
{392}{}{Hmmmm. Mam jeszcze kilka pytañ...}
{393}{}{To ciekawe. Có¿, muszê iœæ.}

# 19. HOW PISSED? (18)
{400}{}{Na tyle, ¿eby rozwaliæ to wszystko w drobny mak... co najmniej. Potem zabra³aby siê za nas - kazaniom nie by³o by koñca. He he he.}
{401}{}{To ciekawe. Mam jeszcze kilka pytañ...}
{402}{}{Hmmmmm. Dziêki.}

# 20. WHAT ABOUT RICHARD? (6, 8, 9, 10, 12)
{410}{}{Richard? No wiesz, znaleŸli go martwego w rynsztoku, jak jednego z tych pieprzonych æpunów. Wszystko wskazuje na to, ¿e ktoœ szprycowa³ go prochami, dopóki biedak nie przesta³ oddychaæ.}
{411}{}{'Ktoœ' szprycowa³ go prochami? Sk¹d pewnoœæ, ¿e to on sam nie przedawkowa³ przypadkiem?}
{412}{}{Jak myœlisz, kto to móg³ zrobiæ?}
{413}{}{Przykro mi to s³yszeæ. Mam jeszcze kilka pytañ...}
{414}{}{To fatalnie. Muszê ju¿ iœæ.}

# 21. GAVE HIM TOO MUCH? (20)
{420}{}{Bo ten dzieciak nie bra³... Chocia¿ tego Mama go nauczy³a. A jeœli zamierzasz twierdziæ inaczej, to mo¿emy sobie wszystko wyjaœniæ tu i teraz.}
{421}{}{To nie mia³o tak zabrzmieæ. Nie wracajmy ju¿ do tego.}
{422}{}{Nie mo¿esz ca³kowicie odrzucaæ mo¿liwoœci, ¿e by³ narkomanem. Jet uzale¿nia bardzo szybko i skutecznie.}
{423}{}{S³uchaj, DZIECIAKU, jeœli ¿ycie ci nie zbrzyd³o, przestañ siê stawiaæ za ka¿dym razem, jak ktoœ powie ci odrobinê przykrej prawdy.}
{424}{}{Jak myœlisz, kto to móg³ zrobiæ?}
{425}{}{Nie szukam k³opotów. Lepiej ju¿ sobie pójdê.}

# 22. I'M SORRY. I DIDN'T MEAN IT LIKE THAT (21)
{435}{}{Dobra, ale uwa¿aj co pleciesz. Za takie gadanie ka¿dy Wright zastrzeli ciê na miejscu, wiêc lepiej trzymaj jêzyk za zêbami, jasne?}
{436}{}{Nie mo¿esz ca³kowicie odrzucaæ mo¿liwoœci, ¿e by³ narkomanem. Jet uzale¿nia bardzo szybko i skutecznie.}
{437}{}{S³uchaj, DZIECIAKU, jeœli ci ¿ycie nie zbrzyd³o, przestañ siê stawiaæ za ka¿dym razem, jak ktoœ powie ci odrobinê przykrej prawdy.}
{438}{}{Wybacz. Mam jeszcze kilka pytañ...}
{439}{}{Jak s³oñce. Lepiej ju¿ sobie pójdê.}

# 23. APOLOGY FAILED (15, 21, 22)
{445}{}{Spieprzaj st¹d. Nie mamy o czym gadaæ.}
{446}{}{Czekaj, mam jeszcze jedno pytanie...}
{447}{}{Spokojnie, ju¿ sobie idê.}

# 24. IMPLY RICH KEPT TAKING DRUGS (15, 21, 22, 23)
{455}{}{(Chris gapi siê na ciebie przez chwilê, potem atakuje!)}
{456}{}{A wiêc TEGO chcesz, tak? DOBRA, ¯ARTY SKOÑCZONE...}

# 25. WHO DO YOU THINK DID IT? (20, 21)
{465}{}{Stawiam na rodzinê Mordino - albo jeden z ich dealerów, albo ktoœ z samej rodziny. Te sukinsyny wytwarzaj¹ ca³e tony Jetu.}
{466}{}{Rozumiem. Mam jeszcze kilka pytañ...}
{467}{}{A twoim zdaniem, który z tych dealerów podsun¹³ Jet Richardowi?}
{468}{}{Rozumiem. Lepiej ju¿ sobie pójdê.}

# 26. WHO DO YOU THINK SOLD IT? (25)
{475}{}{To móg³ byæ ka¿dy z nich: Szramiasty Jimmy J, ten pochlastany sukinsyn z Alei Dziewic, albo Renesco Rakieciarz, gnida handluj¹ca Jetem w zachodniej czêœci miasta.}
{476}{}{Ktoœ jeszcze?}
{477}{}{Rozumiem. Mam jeszcze kilka pytañ...}

# 27. WHO DO YOU THINK SOLD IT? (28)
{485}{}{Hej, stary, dziêkujê.}
{486}{}{Hej, psze pani, dziêkujê.}
{487}{}{Jeœli dowiesz siê kto za³atwi³ mojego brata, ca³a rodzina Wrightów bêdzie ci wdziêczna. A to nie jest ma³o, kapujesz?}
{488}{}{Rozumiem. Pogadamy póŸniej, Chris. }

# 28. ANYBODY ELSE? (26)
{495}{}{Jules przy wejœciu do miasta te¿ sprzedaje Jet, ale g³ównie turystom... No i Ma³y Jesus Mordino móg³ spróbowaæ takiego numeru. Przesiaduje zwykle w Desperado.}
{496}{}{Rozumiem. Mam jeszcze kilka pytañ...}
{497}{}{Szramiasty Jimmy J, Renesco Rakieciarz, Jules i Ma³y Jesus... Pogadam z nimi. Dziêki za informacje, Chris. }


# end lines
{1200}{}{! Ktoœ musia³ wreszcie dopieprzyæ Enklawie!}
{1201}{}{! Rz¹dzisz!}
{1202}{}{!}
{1220}{}{. Co siê z tob¹ dzia³o?}
{1221}{}{?}
{1222}{}{. Jak leci?}
