{150}{}{Widzisz mężczyznę w pomiętym ubraniu. Drapie się w nos i ukradkiem rozgląda się dookoła.}
{151}{}{Widzisz handlarza narkotyków.}
{152}{}{Widzisz dealera narkotyków. Wygląda jakby rozglądał się za klientami.}
{200}{}{Hej, bohaterze! Chcesz poświętować przy Jecie? Chodź pogadać!}
{201}{}{Aleśmy skopali tyłek tej Enklawie! Chcesz teraz posadzić gdzieś tyłek i uczcić zwycięstwo Jetem?}
{202}{}{::Wiwatuje::}
{203}{}{::Gwiżdże::}
{204}{}{Nie ma to skopać tyłek Enklawie i strzelić sobie Jetu, no nie? Dobrze mówię?}
{205}{}{Mam coś, co pomoże ci pocałować niebo, bohaterze.}
{206}{}{Masz doświadczenie?}
{207}{}{Bohaterze pogadaj ze mną, jak będziesz chcieć cukierków dla mózgu. Dam ci zniżkę na WSZYSTKO co mam.}
{208}{}{Wiem czego szukasz i mam to. Tyle Jetu, ile tylko ci POTRZEBA.}
{209}{}{Po co chodzić, skoro możesz LATAĆ?}
{210}{}{Mam najczystszy Jet w mieście. Nie jest tani, ale jest tego wart.}
{211}{}{Chcesz polatać? Masz pieniądze? POGADAJMY.}
{212}{}{Mam coś, co pomoże ci pocałować niebo.}
{213}{}{Mam Jet, Jet i Jet. Pogadajmy.}
{214}{}{Daj znać, jeśli mogę TOBIE w czymś pomóc. Powiedz mi, czego potrzebujesz, a dam ci to po najlepszych stawkach w mieście.}
{215}{}{Chcesz uczcić zwycięstwo odrobiną Jetu? Przychodzisz we właściwe miejsce. Dla ciebie WSZYSTKO mam po specjalnej cenie.}
{216}{}{Mogę zrobić przynajmniej tyle, że spuszczę dla ciebie ceny. To taki mały wyraz wdzięczności za ocalenie skóry.}
{217}{}{Nie ma to skopać tyłek Enklawie i strzelić sobie Jetu, no nie? Dobrze mówię? Dla ciebie wszystkie moje towary po specjalnych cenach.}
{218}{}{Mam coś, co pomoże ci pocałować niebo. I specjalnie dla ciebie: ze zniżką. Co ty na to?}
{219}{}{Masz cukierki? }
{220}{}{Odejdź}
{221}{}{Co masz?}
{222}{}{Dzięki, ale niczego nie chcę.}
{230}{}{Hej, hej... toż to klient wielkiego formatu. Dla CIEBIE stary mam specjalne ceny. Opowiedz o mnie swoim kumplom, dobra?}
{231}{}{Chcesz się zabawić przy odrobinie Jetu, przyjacielu? Przychodzisz do właściwego człowieka. Dla ciebie WSZYSTKO mam po specjalnych cenach.}
{232}{}{Mój drogi przyjacielu, mam tyle Jetu, że mógłbym wysłać cię na orbitę. I mam dla ciebie zniżkę. Pogadamy o cenie?}
{233}{}{Mam coś, co pomoże ci pocałować niebo. I mam dla ciebie zniżkę. Brzmi nieźle, co?}
{234}{}{Mogę zrobić przynajmniej tyle, że spuszczę dla ciebie ceny. W ten sposób okazuję swą przyjaźń.}
{235}{}{Wiesz, że masz klasę? Klasę. A kiedy ktoś z taką klasą jak ty zadaje się ze mną, dostaje zniżkę na moje towary, kumasz?}
{236}{}{Daj mi znać, w jaki sposób mogę pomóc właśnie TOBIE, przyjacielu. Powiedz, czego chcesz, a dam ci to po najlepszych stawkach w mieście.}
{237}{}{Po całym dniu biegania nie ma nic lepszego niż mały łyczek Jetu, co? Mam rację? Dla CIEBIE mam zniżkę.}
{238}{}{Hej, hej... toż to klientka wielkiego formatu. Dla CIEBIE moja panno mam zniżkę. Opowiedz o mnie swoim kumpelom, dobra?}
{239}{}{Chcesz się zabawić przy o drobinie Jetu, prawda? Przychodzisz do właściwego człowieka. Dla ciebie WSZYSTKO mam po specjalnych cenach.}
{240}{}{Moja droga, mam tyle Jetu, że mógłbym wysłać cię na orbitę. I mam dla ciebie zniżkę. Pogadamy o cenie?}
{241}{}{Dziewczyno, mam coś, co pomoże ci pocałować niebo. I mam dla ciebie zniżkę. Brzmi nieźle, co?}
{242}{}{Mogę zrobić przynajmniej tyle, że spuszczę dla ciebie ceny. W ten sposób okazuję swą przyjaźń.}
{247}{}{Wiem czego szukasz i mam to. Tyle Jetu, ile tylko CHCESZ.}
{248}{}{Po co chodzić, skoro możesz LATAĆ? Jak chcesz Jet, to ja go mam.}
{249}{}{Mam najczystszy towar w całym mieście. Nie jest tani, ale jest wart każdego centa.}
{250}{}{Chcesz latać? Masz kasę? Pogadaj ze MNĄ.}
{251}{}{Mam coś, co pomoże ci pocałować niebo, łowco niewolników.}
{252}{}{Mam Jet, Jet i JESZCZE raz Jet. Omówmy to.}
{253}{}{Mam tyle Jetu, że mógłbym wysłać cię na orbitę, łowco niewolników. Pogadamy o cenie?}
{254}{}{Znasz te wrażenia? Pozwól, że zaoparzę cię w najlepszy Jet w mieście.}
{255}{}{Szukasz Jetu? No chodź, łowco niewolników pogadajmy.}
{256}{}{Szukasz Jetu? No chodź, łowco niewolników pogadajmy o tym, ty i ja.}
{261}{}{Wiem czego szukasz i mam to. Tyle Jetu, ile tylko ci POTRZEBA.}
{262}{}{Po co chodzić, skoro możesz LATAĆ?}
{263}{}{Mam najczystszy Jet w całym mieście. Nie jest tani, ale jest wart każdego centa.}
{264}{}{Chcesz polatać? Masz kasę? Pogadaj ze MNĄ.}
{265}{}{Mam coś, co pomoże ci pocałować niebo.}
{266}{}{Mam Jet, Jet i JESZCZE raz Jet. Omówmy to.}
{267}{}{Mam tyle Jetu, że mógłbym wysłać cię na orbitę. Pogadamy o cenie?}
{268}{}{Znasz te wrażenia? Pozwól, że zaoparzę cię w najlepszy Jet w mieście.}
{269}{}{Szukasz Jetu? Zróbmy interes.}
{270}{}{Szukasz Jetu? Pogadajmy.}
{519}{}{ LUBI cukierki!}
