{100}{}{Widzisz Eldridge'a.}
{150}{}{Widzisz pobrudzonego smarem, uzbrojonego po zêby mê¿czyznê. Rozmarzonym wzrokiem wodzi po wisz¹cej na œcianach broni.}
{151}{}{Widzisz Eldridge'a. Rozmarzonym wzrokiem wodzi po wisz¹cej na œcianach broni.}
{200}{}{Gratulujê! Kawa³ dobrej roboty!}
{201}{}{::Strzela w powietrze, zaczyna wiwatowaæ:: Ju¿ po Enklawie, ju¿ po Enklawie! Hurrra!}
{202}{}{::Hura, hura! Enklawa zniszczona! Hura!::}
{203}{}{Enklawa to najlepszy dowód na to, ¿e ka¿dy obywatel powinien nosiæ przy sobie broñ.}
{204}{}{Nastêpnym razem zanim wyruszysz do Enklawy - zajrzyj do mnie. Wyposa¿ê ciê w tak¹ si³ê ognia, ¿e ho ho!}
{210}{}{Maaatko Œwiêta. Pancerz wspomagany!}
{211}{}{Jeeejku. ::Przeciera oczy:: To¿ to pancerz wspomagany?!}
{212}{}{Niech mnie ktoœ uszczypnie. Czy to jest pancerz wspomagany?!}
{213}{}{A niech mnie jasny szlag! Pancerz wspomagany! W Nowym Reno!}
{214}{}{Mo¿e chcesz siê pozbyæ tego pancerza wspomaganego?!! Hej! Jest tam kto?!!}
{220}{}{9mm to sporo, ale .233 osadza goœcia w miejscu. Na sta³e...}
{221}{}{Tak naprawdê to marzê o Red Ryder BB.}
{222}{}{Mam nadziejê, ¿e nikt nie dostanie zmodyfikowanego karabinu plazmowego przede mn¹.}
{223}{}{Ciekawe sk¹d rodzina Salvatore wytrzasnê³a broñ laserow¹...}
{224}{}{Wczoraj w nocy znów œni³a mi siê broñ plazmowa...}
{225}{}{Muszê za³atwiæ Wrightom nowy zapas amunicji do dwururek...}
{226}{}{Mam tylko nadziejê, ¿e Mordino maj¹ doœæ z³ota, ¿eby zap³aciæ za zamówiony towar...}
{227}{}{Ta broñ? Spokojnie wywala dziurê w grubej, metalowej œcianie.}
{228}{}{Ten ch³opak to geniusz... a nie wygl¹da...}
{229}{}{Trzeba zabraæ pieski na spacer, zanim mi tu wszystko obsikaj¹.}
{230}{}{Cholerni niemyci wieœniacy gromadz¹ co raz wiêcej broni... Niez³e z nich kozaki.}
{231}{}{Mo¿e w tym tygodniu ktoœ wreszcie spróbuje mnie okraœæ. Mam ochotê sobie postrzelaæ.}
{232}{}{Trzeba wreszcie uprz¹tn¹æ te pó³ki...}
{233}{}{Na szczêœcie w przysz³ym tygodniu znów bêdzie wojna gangów...}
{234}{}{Mam tu karabiny maszynowe, pistolety, dynamit, granaty... a ludzie i tak przychodz¹ i prosz¹ o miecze i kusze.}
{240}{}{Witaj, bohaterze! Œwietna robota w Enklawie... nie ma co - ¿yjemy wy³¹cznie dziêki tobie. Piêknie dziêkujê. Nazywam siê Eldridge. Chcesz trochê uzupe³niæ ubytki w amunicji?}
{241}{}{Dzieñ dobry panu... Nazywam siê Eldridge. Szuka pan nowej spluwy, czy trochê amunicji?}
{242}{}{Witaj... Nazywam siê Eldridge. Szukasz nowej spluwy, czy trochê amunicji?}
{243}{}{Eeeech? Ma-mu-ni-cji?}
{244}{}{To zale¿y, co tu masz?}
{250}{}{Witaj ponownie, bohaterze! Œwietna robota w Enklawie... nie ma co - ¿yjemy wy³¹cznie dziêki tobie. Piêknie dziêkujê.}
{251}{}{Jak coœ ci wpadnie w oko, daj znaæ. Porozmawiamy o *specjalnej* zni¿ce, jasne?}
{252}{}{Jasna.}
{253}{}{OdejdŸ}
{254}{}{Wspaniale! Mogê siê trochê rozejrzeæ?}
{255}{}{Nie wiem, czy mo¿esz mi pomóc... Szukam czegoœ szczególnego.}
{256}{}{Mój szef... }
{257}{}{Jules powiedzia³, ¿e dostanê u ciebie dobr¹ broñ.}
{258}{}{Czy Salvatore kupuj¹ u ciebie swoje pistolety œwietlne?}
{259}{}{Mam dla ciebie ten obiecany pistolet laserowy.}
{260}{}{Potrafisz ulepszyæ broñ?}
{261}{}{W takim razie wrócê póŸniej.}
{262}{}{Wspaniale... Mogê zobaczyæ twoj¹ ofertê specjaln¹?}
{270}{}{"Bronie z Nowego Reno" oferuj¹ wyspecjalizowane urz¹dzenia obronne, które s¹ w stanie zatrzymaæ w miejscu ka¿dego wrogo nastawionego sukinkota, i dopilnowaæ, ¿eby ju¿ nigdy tego miejsca nie opuœci³. (Uœmiecha siê z³owrogo)}
{272}{}{Witaj znowu. Co mogê dla ciebie zrobiæ?}
{273}{}{Tak, na przyk³ad?}
{274}{}{Moja takie lubi, twoja te¿ takie lubi?}
{276}{}{W³aœnie kogoœ takiego szukam. Mogê siê tu trochê rozejrzeæ?}
{277}{}{Mogê zobaczyæ, co masz na sk³adzie?}
{283}{}{Potrafisz modyfikowaæ lub usprawniaæ broñ?}
{284}{}{Chwilowo podziêkujê. Do widzenia}
{285}{}{Dziêki, ale dziœ nie skorzystam.}
{286}{}{Mogê obejrzeæ twoj¹ ofertê specjaln¹?}
{300}{}{Wpad³o ci coœ w oko? Na pewno coœ ciê zainteresuje.}
{301}{}{Uch... jasne, jasne. (Obrzuca ciê krytycznym wzrokiem) Przypominasz mi mojego niewolnika, Ala. Chcesz obejrzeæ towar?}
{302}{}{Aha}
{303}{}{Moja kce coœ, NIE towar.}
{304}{}{Nee}
{310}{}{Jules ciê przys³a³, tak? }
{311}{}{Najwy¿szy czas, ¿eby ten sukinsyn wzi¹³ siê do roboty... I co mogê dla pana zrobiæ?}
{312}{}{Najwy¿szy czas, ¿eby ten skurwiel wzi¹³ siê do roboty... przepraszam za ³acinê. Co mogê dla pani zrobiæ?}
{330}{}{Nie, nie... kiedyœ siê tym zajmowaliœmy, ale... (krzywi siê) ...có¿, mieliœmy ma³y wypadek... i ju¿ siê tym nie zajmujemy. Mogê s³u¿yæ czymœ innym?}
{331}{}{Trudno. Interesuje mnie coœ jeszcze...}
{340}{}{Jasna sprawa. Co chcesz przerobiæ?}
{341}{}{Dasz radê ulepszyæ któryœ z moich pistoletów?}
{342}{}{Jednemu z moich karabinów przyda³oby siê trochê przeróbek.}
{343}{}{Mo¿esz coœ zrobiæ z tym elektrycznym pastuchem?}
{344}{}{Niewa¿ne. Interesuje mnie coœ innego...}
{345}{}{Chwilowo chyba podziêkujê.}
{350}{}{(Dostrzega twoje magnum) Mogê usprawniæ szybkoœæ prze³adowania tego twojego magnum, za jakieœ $}
{351}{}{Ten twój Desert Eagle... jeœli chcesz, mogê mu wstawiæ powiêkszony magazynek za jakieœ $}
{352}{}{Doczep ten przyspieszacz.}
{353}{}{Powiêksz magazynek w Desert Eagle.}
{354}{}{Prawdê mówi¹c, chodzi mi raczej o inn¹ broñ...}
{355}{}{Niewa¿ne. Mam pytanie...}
{356}{}{W³aœciwie to nie chcê nic ulepszaæ. Muszê iœæ.}
{357}{}{Jak dla mnie za drogo. Wrócê jak bêdê mieæ wiêcej kasy.}
{365}{}{(Przygl¹da siê twoim karabinom, kiwa g³ow¹) }
{366}{}{Mogê zamontowaæ celownik na ten karabin myœliwski za $}
{367}{}{Ten twój ciê¿ki karabin... Mogê mu zamontowaæ powiêkszony magazynek, za jakieœ $}
{368}{}{Mam tu lunetê noktowizyjn¹. W sam raz do tego twojego FN FAL. Mo¿e byæ twoja za $}
{369}{}{Dobra, doczep lunetkê do karabinu myœliwskiego.}
{370}{}{Poszerz magazynek przy karabinie szturmowym AK-112.}
{371}{}{Doczep noktowizor do FN FAL.}
{385}{}{Mam podkrêciæ tego elektrycznego pastucha? Mogê mu dodaæ trochê kopa za $}
{386}{}{Jasne.}
{395}{}{(Eldridge bierze broñ, obrzuca j¹ krytycznym spojrzeniem) Dooobra... poczekaj chwilê, zobaczê, co siê da zrobiæ. (Znika na zapleczu)}
{396}{}{W porz¹dku.}
{400}{}{(Czekasz...)}
{401}{}{Czekaj...}
{405}{}{(Ci¹gle czekasz...)}
{406}{}{Tum tum turu...}
{410}{}{(Masz w³aœnie zapaœæ w drzemkê, kiedy nagle wraca Eldridge) Przepraszam, ¿e tak d³ugo... proszê bardzo. To powinno ci pomóc w walce z ka¿dym skurczybykiem, który zechce ci wejœæ w drogê.}
{411}{}{Dziêki. Czy mo¿esz poprawiæ jak¹œ inn¹ broñ?}
{412}{}{Dziêki. Interesuje mnie coœ jeszcze...}
{413}{}{Dziêki. Pójdê to wypróbowaæ.}
{420}{}{Och... widzê, ¿e mamy tu wybrednego klienta, co? Có¿, od czasu do czasu trafiaj¹ siê ma³e rarytasy... o, na przyk³ad to cacko. (Pokazuje ci coœ... dziwnego) Przedwojenny autentyk. Niez³y sprzêt, nie?}
{423}{}{Eee... JAKIŒ sprzêt, na pewno. Mogê siê mu bli¿ej przyjrzeæ?}
{424}{}{Jasne, ale interesuje mnie coœ innego...}
{425}{}{To nie dla mnie. Do widzenia.}
{430}{}{(Jest to ³adny, plastykowy kwadracik z dziurkami i metalowymi liniami na powierzchni. Widniej¹ na nich te œmieszne literko-znaczki. Przypomina trochê ciasto z kruszonk¹. Zaczynasz siê œliniæ.)}
{431}{}{(Wygl¹da to na jakiœ uk³ad elektroniczny. Trochê zakurzony, ale chyba w dobrym stanie. To chyba czêœæ wiêkszego... czegoœ. Na p³ytce widnieje napis: 'Modu³ Rozpoznawania Mowy firmy KrypTech.')}
{432}{}{(To skomplikowany uk³ad elektroniczny. Sk³ada siê z uk³adu scalonego i zestawu z³¹cz, w tym wejœcia i wyjœcia. Na p³ytce widnieje napis: 'Modu³ Rozpoznawania firmy KrypTech')}
{433}{}{Moja kce mniam p³ytka.}
{434}{}{Moja kce co inne.}
{435}{}{Moja kce iœæ.}
{436}{}{"KrypTech? To musi byæ coœ wa¿nego. Ile za to chcesz?}
{437}{}{Najwy¿szy czas... ile chcesz za tê p³ytkê?}
{438}{}{Nie, dziêki. Szukam czegoœ innego...}
{439}{}{Nie dzisiaj, dziêki.}
{450}{}{Trzy tysi¹ce dolarów. Ani grosza mniej.}
{451}{}{Po raz ostatni: trzy tysi¹ce. Ani grosza mniej.}
{452}{}{Dooobra.}
{454}{}{Rzuæ siê na niego i zabierz mu ciastko.}
{455}{}{Zostaf.}
{457}{}{Cholera, trochê drogo. A mo¿e... 1500?}
{458}{}{Nie, dziêki. Szukam czegoœ innego...}
{459}{}{Nie ma mowy.}
{470}{}{2500$. To moje ostatnie s³owo.}
{471}{}{W porz¹dku, niech bêdzie. Proszê.}
{472}{}{Nie, dziêki. Interesuje mnie coœ jeszcze...}
{473}{}{W takim razie podziêkujê. Do zobaczenia.}
{474}{}{Trochê za du¿o jak na mój gust. Wrócê do ciebie jak zbiorê wystarczaj¹c¹ iloœæ gotówki.}
{480}{}{(Widz¹c, ¿e wyci¹gasz pieni¹dze uœmiecha siê i zaciera rêce) Œwietnie, proszê bardzo. Podaæ coœ jeszcze? }
{481}{}{(Zastanawia siê przez chwilê, obserwuje ciê, kiwa g³ow¹) No dobra... Znaj moje dobre serce. (Daje ci modu³, bierze pieni¹dze.) }
{482}{}{Coœ jeszcze?}
{485}{}{Tak interesuje mnie jeszcze coœ...}
{486}{}{Nie dzisiaj, dziêki.}
{495}{}{(Mruga zaskoczony, œmieje siê.) Ha ha! Nie, nie... To inny rodzaj broni! Oczywiœcie chêtnie rzuci³bym na nie okiem. Sprawdzi³ si³ê ognia, zasiêg, szybkostrzelnoœæ... (Patrzy przed siebie, wzdycha.)}
{496}{}{A jeœli zdobêdê dla ciebie takie cacko?}
{497}{}{Zgadza siê, taka broñ to prawdziwy skarb. Interesuje mnie coœ jeszcze...}
{498}{}{No trudno. Dziêki, Eldridge.}
{505}{}{(Przygl¹da ci siê, jakby zastanawia³ siê, czy mo¿na ci ufaæ) Có¿, nie odmówi³bym... gdyby ci siê uda³o zrobiæ to po cichu. Zap³aci³bym ci uczciw¹ sumkê... (marszczy brew) ...jeœli uda³oby ci siê za³atwiæ to dyskretnie.}
{506}{}{Nie ma sprawy... Mam jeden przy sobie. Proszê bardzo.}
{507}{}{Mo¿esz na mnie liczyæ, ale najpierw chcê jeszcze coœ za³atwiæ...}
{508}{}{Zapomnijmy o tym. Mo¿e móg³byœ mi pomóc w czymœ jeszcze...}
{509}{}{Umowa stoi. Zwinê jeden i przyniosê ci go.}
{510}{}{Tego nie mogê obiecaæ... dyskrecja nie jest moj¹ siln¹ stron¹. Do zobaczenia, Eldridge.}
{520}{}{A niech mnie mole ze¿r¹! }
{521}{}{Jasny szlag! Zgodnie z umow¹, oto nagroda za twoje trudy... }
{522}{}{(Daje ci garœæ ¿etonów, bierze pistolet) Cholera... dziwny sprzêt, nie? (Ogl¹da lufê) Hmmm...}
{523}{}{Interesuje mnie coœ jeszcze...}
{524}{}{Mi³o robiæ z tob¹ interesy, Eldridge. Trzymaj siê.}
{530}{}{(Eldridge ogl¹da ciê od stóp do g³ów, zaczyna mówiæ z szacunkiem) Oczywiœcie. Poka¿ê ci moj¹ ofertê specjaln¹... oczywiœcie za ni¿sz¹ cenê.}
{532}{}{Prawdê mówi¹c, interesuje mnie coœ jeszcze...}
{533}{}{Niewa¿ne. Wrócê innym razem.}
{545}{}{Zamknijcie siê, cholerne kundle!!!}
{546}{}{Zamknij pysk, kundlu!}
{547}{}{Dzieci nocy... zamkn¹æ siê!}
{548}{}{Packard! Buck! Missy! Zamknijcie siê, albo do was pójdê!}
{549}{}{Jeszcze jedno warkniêcie i ka¿ê was wypchaæ!}
{550}{}{Cholerne psy!}
{560}{}{Co jest, czy ja ci wygl¹dam na œlepego?}
{561}{}{Trzymaj siê z dala od tych drzwi!}
{562}{}{Nie zbli¿aj siê do tych drzwi.}
{563}{}{Dotknij znowu tych drzwi, a bêd¹ k³opoty.}
{564}{}{Wiesz co? Ostatni¹ osobê, która dotknê³a tych drzwi, pochowano w Golgocie. Trzymaj siê od nich z daleka.}
{575}{}{Nie masz prawa tu przebywaæ! Wynoœ siê! Wynoœ siê st¹d!}
{576}{}{Nie wolno ci tu wchodziæ! Wynoœ siê!}
{577}{}{Uciekaj st¹d, zanim ciê podziurawiê!}
{578}{}{Jeœli zaraz st¹d nie pójdziesz, zrobiê z ciebie sito!}
{600}{}{Ch³opcze, zamkniête... }
{601}{}{Panienko, zamkniête... }
{610}{}{Wiêc sugerujê wyniesienie siê st¹d, zanim ciê rozwalê.}
{700}{}{Cholerne psy! Wracam do ³ó¿ka.}
{701}{}{Durne psy! Jutro rano ka¿ê was uœpiæ.}
{702}{}{Zamknijcie siê wreszcie, cholerne kundle! Nikt nie jest a¿ tak g³upi, ¿eby w³amywaæ siê do sklepu z broni¹!}
{800}{}{Dostarczasz pistolet Eldridgeowi.}
{801}{}{Hej, czy ja ci wygl¹dam na magika? Musisz mieæ broñ, ¿eby j¹ modyfikowaæ. A teraz idŸ ju¿ st¹d i znajdŸ coœ co mogê ulepszyæ...Phi!}
{802}{}{Wróæ z pieniêdzmi.}
{1340}{}{Jasna sprawa. (Obrzuca spojrzeniem twoje wyposa¿enie) Ale chyba nie masz przy sobie nic, co móg³bym przerobiæ. Przynieœ jakieœ dziewicze... eee, "normalne" pistolety i karabiny, to zobaczê co siê da zrobiæ.}
{1345}{}{W porz¹dku. Interesuje mnie coœ jeszcze...}
{1346}{}{Tak zrobiê. Do widzenia.}
{5256}{}{... kaza³ mi do ciebie zajrzeæ. Powiedzia³, ¿e mo¿esz mnie "zaopatrzyæ".}
{5500}{}{.}
