{100}{}{Widzisz pannę Kitty.}
{150}{}{Widzisz oszałamiająco piękną kobietę. Pomimo bardzo... odkrywczej sukienki, wygląda na profesjonalistkę i prawdziwego człowieka interesu.}
{200}{}{Dochody z pierwszego kwartału nieco wzrosły... a teraz, jeśli weźmiemy pod uwagę podwyższony haracz...}
{201}{}{Jeśli przyłapię ją na braniu Jetu, nawet na malutkim *ffiuuu*, to ją stąd wyrzucę...}
{202}{}{Zbliża się czas comiesięcznych badań... akurat w samą porę przed nowym sezonem karawanowym.}
{203}{}{Potrzebuję więcej dziewczyn na to przyjęcie basenowe u Bishopa...}
{204}{}{Te cholerne terminarze Macrosoftu...}
{205}{}{Spędzam za dużo czasu przy tych terminarzach, w końcu nie zrobię żadnej PRAWDZIWEJ roboty.}
{206}{}{Lepiej, żeby Jules przysłał mi tu kogoś napalonego... i bogatego.}
{215}{}{(Stojąca przed tobą kobieta jest oszałamiająco piękna. Kiedy do niej podchodzisz, odrywa wzrok od swojej pracy i uśmiecha się) Ach, nowa twarz! Jestem panna Kitty... witamy w Kociej Łapce.}
{216}{}{Witam ponownie!}
{217}{}{Proszę, proszę, czyż to nie sława reńskiego ringu?!}
{218}{}{Byłam ciekawa, kiedy pan }
{219}{}{O jejku jejku, czyż to nie gwiazda złotego ekranu?}
{220}{}{ Na co ma pan dziś ochotę?}
{221}{}{ Na co ma pani dziś ochotę?}
{222}{}{Oggottę?}
{223}{}{Tyy maa łaaadneee włoooosy}
{224}{}{Tyy mówi "ochodę" Hłe-hłe-hłe-hłe-hłe}
{225}{}{George mófi, sze mamy swoje fłazne ochody i mam siem tszymać ot ciebie stala albo nie posfoli mi siem pawić z króliżkami więc ja jusz pójdem}
{226}{}{Jules powiedział mi, żeby tu zajrzeć, jeśli mam ochotę na trochę... rozrywki.}
{227}{}{Szukam... rozrywki.}
{228}{}{Prawdę mówiąc, chcę zadać kilka pytań.}
{229}{}{Widzisz, wszędzie na pustyni walały się te magazyny, "Kocia Łapka" i nie mam pojęcia, co to właściwie jest. Mam tu jeden egzemplarz.}
{230}{}{Mam tu tę kolekcję numerów Kociej Łapki, o którą prosiłaś.}
{231}{}{Dzięki, ale dziś nie skorzystam.}
{240}{}{(Piękna pani dotyka palcem dłoni twojego czółka) Och, biedactwo... możesz tu chwilkę zostać, żeby się otrząsnąć z tego całego bałaganu, ale nie możesz zostać tu zbyt długo, dobrze? Obiecaj mi to.}
{241}{}{Dooobrzee, śliczna paaniii, dzieenkujee.}
{245}{}{(Uśmiecha się i mruga do ciebie) Ach tak? A więc jesteś we właściwym miejscu. Bez względu na to, jakie są twoje chęci i marzenia, możemy ci to dostarczyć... i nie wstydź się, już to wszystko słyszeliśmy. A więc, na co masz ochotę?}
{246}{}{Przepraszam za taką śmiałość, ale pragnę lepiej poznać CIEBIE. O której kończysz? Uch, pracę, oczywiście.}
{247}{}{To zależy... co jest w menu?}
{248}{}{Chcę czegoś specjalnego dla jednego z moich znajomych.}
{249}{}{Proszę o coś dla jednego z moich przyjaciół. To z okazji... eee, urodzin.}
{250}{}{Chcę zadać ci kilka pytań...}
{251}{}{Właściwie to nie mam już na nic ochoty. Trema i tak dalej. Do widzenia.}
{255}{}{To bardzo miłe, ale... nie. Nie mogę.}
{256}{}{Oj, daj spokój. Tylko jeden drink. Bez zobowiązań. Będziemy się dobrze bawić.}
{257}{}{Jeśli nie lubisz kobiet, to nie ma sprawy. Do licha, ja też nie lubię większości kobiet, które spotykam. Mamy ze sobą coś wspólnego.}
{258}{}{Hej, nie martw się... nie mam na sobie zbroi wspomaganej, no nie?}
{259}{}{W porządku. Mam kilka pytań...}
{260}{}{Wybacz, nie chcę cię do niczego zmuszać. Do widzenia.}
{265}{}{(Rozgląda się wokół, a potem pochyla się i szepcze) Wiesz co... wróć tu, jak już zrobisz wszystko, co jest do zrobienia, żeby uratować twoją wioskę, a wtedy pogadamy, dobra?}
{266}{}{W porządku. Mam parę innych pytań...}
{267}{}{A więc umowa stoi. Na razie.}
{275}{}{Popatrzmy (odlicza na palcach) ...mamy romantyczne zaloty, dalekomorskie odwierty, wycie do księżyca i wiele innych egzotycznych możliwości. (uśmiecha się) Pytanie tylko, na co TY masz dziś humor?}
{276}{}{Poproszę trochę... ćwiczeń ustnych.}
{277}{}{Myślę, że prosty, zwierzęcy, podły, wulgarny seks w zupełności mi wystarczy.}
{278}{}{Poproszę pełną obróbkę dolnych i górnych części ciała.}
{279}{}{Czy można by z nimi po prostu, no wiesz, porozmawiać?}
{280}{}{Mam specjalne życzenie... dramatyczne.}
{290}{}{W porządku. }
{291}{}{(Mrugnięcie okiem) To będzie nieodpłatnie.}
{292}{}{To będzie }
{293}{}{Dobrze. Oto pieniądze.}
{294}{}{Nie mogę sprzeczać się o cenę. Zróbmy to.}
{295}{}{Nieważne. Mam kilka pytań...}
{296}{}{Nie mam tyle pieniędzy... może innym razem.}
{320}{}{Ależ oczywiście, że można. Nazywamy to "specjał Kestinga". }
{322}{}{Kosztuje tylko }
{323}{}{Czemu to tak nazywacie?}
{325}{}{Dla mnie bomba. A więc zgoda.}
{326}{}{Może innym razem. Mam kilka pytań...}
{335}{}{No cóż... plotka głosi, że był kiedyś taki pracownik słynnej firmy komputerowej, który lubił rozmawiać z innymi (wzruszenie ramion).}
{336}{}{Przypadkiem zarabiał tylko }
{337}{}{Przypadkiem zupełnie nic nie zarabiał, więc stać go było tylko na rozmowę.}
{338}{}{Och. W porządku, zapisz mnie więc na sesję konwersacji. Oto }
{340}{}{Chyba spasuję. Mam kilka pytań...}
{350}{}{Tak?}
{351}{}{Zapytać nie zaszkodzi...}
{352}{}{W porządku. (Uśmiecha się) Jednak odpowiedzi mogą cię kosztować...}
{353}{}{Pewnie. Jakie masz pytania?}
{354}{}{Podobno niektóre z waszych dziewcząt wybiera się, by... odwiedziły Myrona.}
{355}{}{Jules powiedział mi, że można tu znaleźć... rozrywkę.}
{361}{}{Właściwie to lepiej już pójdę.}
{375}{}{Jest szansa, że zdołamy ci dogodzić. A twoje życzenie to...?}
{376}{}{Chcę, żeby druga osoba założyła kombinezon mieszkańca Krypty, nazywała mnie "Przybyszem z Krypty" i żebyśmy wyruszyli na poszukiwanie "Krypty 69".}
{377}{}{Chcę zostać "uwięziony" przez jakąś porywającą mutantkę, a potem zostać zmuszony, by zanurkować w jej mutującej "kadzi".}
{378}{}{Chciałbym zagrać rolę "Herka", młodego, wyrośniętego niewolnika porwanego z rodzinnej wioski przez bandę pożądliwych łowczyń. Ale jest jeden haczyk... on może się komunikować tylko za pomocą swojego CIAŁA.}
{379}{}{Chciałabym zagrać rolę "Zeny", młodej, wyrośniętej niewolnicy porwanej z rodzinnej wioski przez bandę łowców. Ale jest jeden haczyk... ona może się komunikować tylko za pomocą swojego CIAŁA.}
{380}{}{Chcę zostać "uwięziona" przez złośliwego porucznika mutantów, brutalnie przesłuchana, a potem zanurzona w jego mutujących kadziach.}
{381}{}{Macie może jakieś dziewczyny, które wyglądają jak Angela Bishop? Muszę wyładować swoje fascynacje.}
{382}{}{Macie może jakieś dziewczyny, które wyglądają jak pani Bishop? Muszę wyładować swoje fascynacje.}
{383}{}{Chcę zamiast tego zadać ci kilka pytań...}
{384}{}{Właściwie to nieważne. Muszę już iść.}
{395}{}{Oczywiście. (Rzuca okiem na twoje towarzystwo) Kto z nich?}
{396}{}{Czy możecie zająć się Lennym? Myślę, że on nigdy nie całował dziewczyny.}
{397}{}{Czy masz tu kogoś, kto mógłby, eee, "poradzić" sobie z Marcusem?}
{398}{}{Ten tutaj mały oblech - Myron.}
{399}{}{"Kość w Nosie", jeśli wiesz o co mi chodzi. He he.}
{400}{}{Cassidy. Ostatni raz był chyba dawno temu.}
{401}{}{Vic. "Kupiec" Vic.}
{402}{}{Czy któraś z twoich dziewczyn mogłaby przeczytać słownik Robo Mózgowi? To pobudza jego ośrodek mózgowy.}
{403}{}{Doktor chciałby chyba mieć "gorączkę", albo i dwie.}
{404}{}{Davinowi przydałoby się... dużo... dodatkowych doświadczeń.}
{405}{}{Miria chciałaby odbyć wycieczkę na dziką stronę.}
{406}{}{Właściwie to nikt. Dzięki.}
{407}{}{Dex, ten tutaj. Lepiej miej na niego oko, on czasami traci nad sobą kontrolę.}
{408}{}{Kot Jules, ten tutaj. Ale uważaj, może gryźć dziewczyny.}
{409}{}{Kitsune, tutaj. Mam nadzieję, że możesz zaspokoić jej azjatyckie potrzeby, jeśli wiesz co mam na myśli.}
{420}{}{To ten przyjaciel tutaj? (Ogląda wskazaną osobę ze wszystkich stron i kiwa głową) Myślę, że potrafimy ci dogodzić... }
{421}{}{(Ogląda wskazaną osobę ze wszystkich stron i kiwa głową) Myślę, że potrafimy ci dogodzić... }
{422}{}{ dolarów.}
{423}{}{Nie martw się o pieniądze. To będzie za darmo.}
{424}{}{Dobrze. Oto one.}
{425}{}{Nie mogę spierać się z taką ceną. W porządku.}
{426}{}{Może później... wiesz co, mam kilka pytań.}
{427}{}{Hmmm. Może jak będę miał wystarczająco dużo pieniędzy.}
{428}{}{Właściwie to już tego nie chcę. Do widzenia.}
{440}{}{(Wygląda na zaskoczoną) Zobaczmy. (Przegląda magazyny) No, no... wiesz, słyszałam takie pogłoski, że jeszcze przed wojną Kocia Łapka była wydawnictwem... pornograficznym.}
{441}{}{Pornogru - porn-o-gra - pornu - uch, wydawnictwem, tak?}
{442}{}{To miejsce było wydawnictwem?}
{450}{}{Tak... tych pokoi używano do kręcenia filmów z modelami z całego świata. (Wydaje się zafascynowana magazynami) Masz tutaj spory kawałek hisorii.}
{451}{}{Wiesz, no, ja tylko czytam artykuły.}
{452}{}{Strasznie się cieszę, że w końcu wiem, co to jest. To wkurzające, jak się ciągle to ogląda i ciągle dostaje ten sam komunikat. Pewnie DALEJ będzie się pojawiał ten sam, mimo że teraz już wiem, co to jest.}
{460}{}{Wiesz co... jeśli dasz radę przynieść mi pełny zestaw... powiedzmy, dziesięć wydań, odkupię je od ciebie. Będą w sam raz na wystawę, żeby przyciągać klientów. Co ty na to?}
{461}{}{Jeśli dam radę ZNALEŹĆ ich aż tyle... wiesz co, mam jeszcze parę pytań...}
{462}{}{Właściwie to zupełnie przypadkiem mam dziesięć sztuk przy sobie.}
{463}{}{Pewnie. Jeśli znajdę ich tyle, to na pewno tu wpadnę.}
{470}{}{Cudownie! Dam ci $500 za cały komplet.}
{471}{}{$500? Po uzbieraniu ich WSZYSTKICH? Nie ma mowy, chcę tysiąc.}
{472}{}{Brzmi nieźle. Oto one. Ale uważaj na numer piąty... wygląda na to, że kartki się posklejały.}
{473}{}{Nie, chyba jednak je zatrzymam... wiesz co, mam kilka innych pytań...}
{474}{}{Nie, dzięki, czuję do nich przywiązanie. Może innym razem.}
{480}{}{Hmmmmm. Siedemset pięćdziesiąt i umowa stoi.}
{481}{}{$750? W porządku. Są twoje.}
{482}{}{W takim razie jednak je zatrzymam... słuchaj, mam kilka innych pytań...}
{483}{}{Zapomnij. Może innym razem.}
{490}{}{Proszę. (Przelicza pieniądze i wręcza ci je) Jeszcze raz dzięki.}
{491}{}{Wiesz co, mam kilka innych pytań...}
{492}{}{Nie ma sprawy. Do widzenia.}
{500}{}{Naprawdę? (Ogląda nr 5, po czym przegląda resztę) Hmmmm. Wygląda na to, że masz tu dwa jednakowe egzemplarze, więc ten jeden możesz wziąć z powrotem... ale pozwól, że najpierw zetrę tę plamę.}
{501}{}{Dobrze. Uch... a tak w ogóle, to ta plama nie jest moja. Nie mam pojęcia, skąd się tam wzięła.}
{502}{}{Dobrze. Na pewno dasz radę zetrzeć tę plamę? Wygląda na to, że się tam porządnie przylepiła.}
{510}{}{To się ciągle zdarza... (panna Kitty zaczyna czyścić pismo) ...głównie z rozkładówkami. To powinno wystarczyć... (unosi je) ...dobre wydanie - zdaje się zawiera artykuł o broniach energetycznych. Proszę.}
{511}{}{Mam kilka innych pytań...}
{512}{}{Artykuł o broniach energetycznych? Dzięki. Może go później przeczytam.}
{520}{}{(Kiedy mówisz, wstrząśnięta podnosi wzrok) Ty! Jesteś z powrotem! Ja... myślałam, że już nie żyjesz. (Chyba jej ulżyło) Tak się *martwiłam*. Ryzykować życiem, walczyć z Enklawą... to najodważniejsza rzecz, o jakiej kiedykolwiek słyszałam.}
{521}{}{(Kiedy mówisz, wstrząśnięta podnosi wzrok) Ty! Słyszałam o tobie. (Jej twarz rozjaśnia się w zachwycie) Ryzykować życiem, walczyć z Enklawą... to najodważniejsza rzecz, o jakiej kiedykolwiek słyszałam.}
{522}{}{! Cieszę się, że jesteś z powrotem. Już samo przebywanie kogoś takiego jak ty w pobliżu nakręca interes: ryzykować życiem, walczyć z Enklawą... to najodważniejsza rzecz, o jakiej kiedykolwiek słyszałam.}
{523}{}{Kurcze, panno Kitty. To jezd nic czego nikt inny by nie zrobiłby by, gdyby byłby na moim miejscu by.}
{524}{}{Doooookładnie, złotko. I to jest najodważniejsza rzecz o jakiej kiedykolwiek usłyszysz, bo jestem NAJGORSZY z najgorszych.}
{525}{}{To nie było nic, czego nie zrobiłaby na moim miejscu każda wkurwiona kobieta, której ktoś porwał całą wioskę.}
{526}{}{I to jest najodważniejsza rzecz o jakiej KIEDYKOLWIEK usłyszysz, bo jestem NAJGORSZĄ suką na całych pustkowiach.}
{527}{}{Dzięki. Jako bohaterka po prostu wykonuję swoją pracę.}
{528}{}{Dzięki. Jako bohater po prostu wykonuję swoją pracę.}
{529}{}{Kopać tyłki i zbierać tytuły, oto moja praca.}
{545}{}{Jaka skromność. }
{546}{}{Jaka siła. Jaka... pewność siebie. }
{547}{}{KOCHAM to u ciebie. (Ogarnia ręką całą Kocią Łapkę) Zawsze będziemy cię tu miło witać, bez opłaty.}
{548}{}{A więc... co powiesz na tę randkę, o której kiedyś rozmawialiśmy?}
{549}{}{A więc... co ty na to... no wiesz, ty i ja... jakby... no wiesz.}
{550}{}{Złotko, czujem siem jak maszyna, a to nie jest tak, jak siem powinienem czuć. Chodź tutaj.}
{551}{}{Świetnie! Wiesz, co, mam jeszcze kilka pytań, zanim sobie dogodzę...}
{552}{}{Dzięki. Doceniam to panno Kitty.}
{553}{}{Nie oczekuję niczego mniej. Skorzystam później.}
{565}{}{W porządku, }
{566}{}{...pozwól mi tylko wziąć swój płaszcz.}
{567}{}{Nie ma pośpiechu.}
{568}{}{Dobrze, że mam swój "płaszcz" w kieszeni. He, he.}
{569}{}{Pewnie. Ale pośpiesz się... mamy rezerwację na ósmą. W moich SPODNIACH.}
{570}{}{Pewnie. Ale pośpiesz się... ty i mój język są umówieni na ósmą.}
{575}{}{Och, }
{576}{}{, ty miażdżące Enklawę zwierzę...}
{577}{}{::Buanbuan-buan-ba-buan oookuaka oookuaka::}
{585}{}{(Kiwa głową) Tak, to prawda. Zwykle musimy je wszechstronnie trenować, by stłumić ich naturalną odrazę. To w tej chwili niemalże rytuał inicjacyjny. Poza tym, jeśli dziewczyna potrafi przetrzymać Myrona, to znaczy, że jest twarda...}
{586}{}{Chcę się z nim spotkać. Czy mogę zgłosić się na ochotniczkę jako jego następny "wybór"?}
{587}{}{Rozumiem. Mam kilka innych pytań...}
{588}{}{Hmmmm. Dzięki za informację.}
{595}{}{(Przygląda ci się, potem robi okrężny ruch palcem) Obróć się. Hmmmm... }
{596}{}{Nie, nie sądzę, żebyś się nadała. Może gdybyś się trochę umyła, zadbała o... prezencję. Przykro mi.}
{597}{}{Tak... tak, myślę, że się doskonale nadasz. Interesuje cię ta praca? Wszystkie moje dziewczęta już nią... rzygają.}
{598}{}{Jasne.}
{599}{}{Hmmm. Mam kilka innych pytań...}
{600}{}{Nie, ale może poproszę cię o to później. Mam kilka innych pytań...}
{610}{}{(Kiwa głową) Doskonale. Niedługo powinien się pojawić jeden z poruczników Mordina. Jeśli usiądziesz i poczekasz, przedstawię cię jako jedną z... kandydatek.}
{611}{}{Dobrze... zaczekam na niego.}
{612}{}{Właściwie to nieważne. Mam kilka innych pytań...}
{613}{}{Nieważne... zmieniłam zdanie. Może kiedy indziej.}
{620}{}{(Ogląda cię od góry do dołu, po czym kiwa głową) Myślę, że potrafimy ci dogodzić...}
{621}{}{(Ogląda twoje towarzystwo od góry do dołu, po czym kiwa głową) Myślę, że potrafimy dogodzić tej osobie...}
{623}{}{(Mruga okiem) To jest nieodpłatna usługa, więc nie martw się o pieniądze.}
{700}{}{Ooooo-taaak.}
{701}{}{Wstrząsające.}
{702}{}{Łojej. To było takie mocne.}
{703}{}{Ojoj.}
{704}{}{*Fiuu*}
{705}{}{Heh... Mam nadzieję, że nie zaszła ze mną w ciążę.}
{706}{}{Wiesz, że to nie to samo kiedy ich krew jest ciągle ciepła?}
{707}{}{Mam nadzieję, że robiliście notatki.}
{708}{}{Dziewczyny stały się dość przerażające, po końcu świata... Jak dla mnie bomba.}
{709}{}{...i dlatego laseczki zwykły nazywać mnie "Dex, Książę Seksu".}
{710}{}{Rozmawiacie przez wiele godzin. Dziewczyny z Kociej Łapce mają niesamowite pojęcie o ludzkiej naturze.}
{711}{}{Porucznik Mordina przybywa i najwyraźniej jest pod wrażeniem. Prowadzi się na północ od miasta do miejsca, które nazywa się "Stajnie".}
{720}{}{*gwizd*}
{721}{}{*klap klap klap*}
{722}{}{Ale jazda!}
{723}{}{Juhuu.}
{730}{}{*chlip chlip chlip*}
{731}{}{Czuję się jakby... mnie tak strasznie... oszukano...}
{740}{}{*Rrrarrr*}
{750}{}{*Aauuuu*}
{760}{}{*Bzzzt*}
{770}{}{Ale jazda, szefie! Nie uprawiałem seksu już od baaaaaaardzo dawna.}
{800}{}{Magazyny "Kocia Łapka" zostały dostarczone do panny Kitty.}
{900}{}{Czujesz, że twoje ciało jest teraz bardziej dostrojone i skoordynowane z tobą.}
{1218}{}{ cię tu przyśle (mrugnięcie okiem)...}
{1336}{}{ dolarów tygodniowo.}
