{150}{}{Widzisz chudego, wyg³odnia³ego mê¿czyznê. Ma ob³êdne spojrzenie, a jego brodê pokrywa rzadki zarost.}
{151}{}{Widzisz Œlicznego Ch³opca Lloyda.}
{152}{}{Widzisz Œlicznego Ch³opca Lloyda, który uwa¿nie ci siê przygl¹da.}
{200}{}{Muszê wynieœæ siê z miasta...}
{210}{}{Kim jesteœ? Co tutaj robisz?!}
{211}{}{To znowu ty! Co tutaj robisz?!}
{212}{}{Nic, kochanie}
{213}{}{Ja }
{214}{}{OdejdŸ}
{215}{}{A co TY tutaj robisz?}
{216}{}{Najpierw siê uspokój, kolego, a POTEM porozmawiamy. Wszystko w porz¹dku?}
{217}{}{Ty jesteœ Lloyd? Œliczny Ch³opiec Lloyd?}
{218}{}{Nic. Tylko siê rozgl¹dam. Na razie.}
{225}{}{No to zmiataj st¹d. I nie wa¿ siê nikomu powiedzieæ, ¿e tu jestem, s³yszysz?}
{226}{}{Ja tu. A teraz ja iœæ!}
{230}{}{To nie twój interes. Najlepiej bêdzie, jeœli od razu wrócisz po tych schodach na górê i zapomnisz, ¿e siê w ogóle spotkaliœmy.}
{231}{}{Ja Zapomnieæ. Zap-omnie. Zapo-mnie... uch... zapomnieæ co?}
{232}{}{Obraa Dobraa}
{233}{}{Twoje sugestie niewiele mnie obchodz¹. O co tu chodzi?}
{234}{}{Wygl¹dasz na kogoœ w k³opotach. Mo¿e bêdê w stanie ci pomóc.}
{235}{}{Wygl¹dasz na kogoœ, kto ceni swoj¹ prywatnoœæ. W przypadku kogoœ tak gadatliwego jak ja zapominanie mo¿e byæ bardzo kosztowne.}
{236}{}{W takim razie w porz¹dku... Przepraszam za k³opot.}
{245}{}{K³opot? K³opot polega na tym, ¿e stoisz tu przede mn¹. }
{246}{}{A teraz, ch³opie powiem to jeszcze raz: odejdŸ.}
{247}{}{A teraz, kochana, powiem to jeszcze raz: odejdŸ.}
{248}{}{*Grozisz* mi? DOBRZE siê zastanów, zanim odpowiesz.}
{255}{}{K³opoty? Nie mam ¿adnych k³opotów, przyjacielu, zupe³nie ¿adnych. Po prostu potrzebujê odrobiny prywatnoœci, to wszystko.}
{256}{}{K³opoty? Nie mam ¿adnych k³opotów, s³odziutka, zupe³nie ¿adnych. Po prostu potrzebujê odrobiny prywatnoœci, to wszystko.}
{257}{}{K³opoty? Niezupe³nie ¿adnych k³opotów. Po prostu potrzebujê odrobiny prywatnoœci, to wszystko. Mimo to... to BY£O niegrzeczne z mojej strony, wyrzucaæ tak¹ piêkn¹ damê.}
{258}{}{A ja myœlê, ¿e MASZ k³opoty. Widzisz, ca³a ta prywatnoœæ sprawia, ¿e trudno bêdzie komukolwiek u³yszeæ, co siê tu na dole dzieje. Mo¿e wiêc ciê po prostu zabijê, co?}
{260}{}{W przypadku kogoœ tak gadatliwego jak ja prywatnoœæ mo¿e byæ bardzo kosztowna.}
{261}{}{W porz¹dku. Przepraszam za k³opot.}
{262}{}{Masz racjê. To BY£O niegrzeczne. Pójdê ju¿.}
{270}{}{(Jego oczy siê zwê¿aj¹) }
{271}{}{Ch³opie, jeœli przyszed³eœ tu w poszukiwaniu k³opotów, to trafi³eœ w dziesi¹tkê. }
{272}{}{Kochana, jeœli przysz³aœ tu w poszukiwaniu k³opotów, to trafi³aœ w dziesi¹tkê. }
{273}{}{Mam nadziejê, ¿e wszystkie d³ugi masz posp³acane...}
{274}{}{Chcesz k³opotów? Ju¿ MASZ k³op...}
{283}{}{Uch... nie no, pos³uchaj... nikomu nie gro¿ê i z ca³¹ pewnoœci¹ nie szukam k³opotów.}
{284}{}{Myœlê, ¿e MASZ k³opoty. Widzisz, ca³a ta prywatnoœæ sprawia, ¿e trudno bêdzie komukolwiek us³yszeæ, co siê tu na dole dzieje. Mo¿e wiêc ciê po prostu zabijê, co?}
{285}{}{Wygl¹dasz na cz³owieka w k³opotach i mo¿e jestem w stanie ci pomóc. Co ty na to?}
{286}{}{Wygl¹dasz na kogoœ, kto ceni swoj¹ prywatnoœæ. W przypadku kogoœ tak gadatliwego jak ja, zapominanie mo¿e byæ bardzo kosztowne.}
{287}{}{W takim razie w porz¹dku... Przepraszam za k³opot.}
{295}{}{Uch... nie no... nie ma, uch, potrzeby, ¿eby tak mówiæ. Mo¿e porozmawiajmy o czymœ INNYM: ile pomocy mo¿e ci udzieliæ twój przyjaciel Lloyd.}
{296}{}{Interesuj¹ce. Mów dalej.}
{297}{}{Nie interesuje mnie to. Spadam st¹d.}
{298}{}{Zapomnij, Lloyd. Twój numer siê ju¿ skoñczy³. Przygotuj siê na œmieræ.}
{305}{}{(Twarz mê¿czyzny robi siê blada. Przez chwilê prze³yka œlinê... i rzuca siê na ciebie!)}
{306}{}{Skurwys...}
{315}{}{Mam parê dolców... mo¿e nieco pieniêdzy pomog³oby oczyœciæ atmosferê, utrzymaæ nasz stosunki na poziomie?}
{316}{}{Dobrze. Daj mi wszystko, co masz.}
{318}{}{Zatrzymaj pieni¹dze. Spadam st¹d.}
{325}{}{W porz¹dku, w porz¹dku... (Siêga do kieszeni, wyjmuje kilka dolców i daje ci je) ...weŸ proszê te pieni¹dze, wróæ siê po tych schodach na górê i zabaw siê na koszt Lloyda, dobra?}
{326}{}{Chyba og³uch³eœ. MÓWIÊ DO CIEBIE, daj mi wszystko co masz.}
{327}{}{Dobra. Ale najpierw ciê zabijê.}
{328}{}{W porz¹dku. Spadam st¹d.}
{335}{}{Uch, no wiesz... to zupe³nie wszystko co mam. Nie mam nic wiêcej. Ju¿ ci wszysko da³em.}
{336}{}{Nie igraj ze mn¹, Lloyd. WIEM, ¿e masz wiêcej. Jesteœ sprytnym goœciem. Ostatnia szansa: gdzie jest reszta?}
{337}{}{Przekonamy siê, Lloyd. Zaraz sprawdzê, co znajdê przy twoich zw³okach.}
{345}{}{Ale... ale przecie¿ mówiê... ee... no dobrze... wiem, gdzie mo¿na znaleŸæ wiêcej kasy... widzisz, ona nie jest moja i to w sumie strasznie du¿o zachodu, ale skoro tego chcesz, jest twoja.}
{346}{}{Byæ mo¿e wiem, gdzie mo¿na znaleŸæ wiêcej kasy... widzisz, ona nie jest moja i to w sumie strasznie du¿o zachodu, ale skoro tego chcesz, jest twoja.}
{347}{}{Mów dalej i niech to bêdzie równie interesuj¹ce.}
{348}{}{Tak naprawdê to z tym dawaniem ci szans to by³ tylko taki ¿art. Po prostu ciê zabijê i niech ci ziemia lekk¹ bêdzie.}
{349}{}{Nie interesuj¹ mnie te twoje frajerskie bzdury. Spadam st¹d.}
{355}{}{W porz¹dku... ona le¿y na równienie Golgoty na po³udnie od Reno, zakopana w jednym z grobów. Ale tylko ja wiem, gdzie to jest.}
{357}{}{Powiedz mi.}
{358}{}{To najwiêksza kupa... a do licha, Lloyd, po prostu ciê zabijê i niech ci ziemia lekk¹ bêdzie.}
{359}{}{Ech, daj se siana. Spadam st¹d.}
{365}{}{PodejdŸ do znaku drogowego na skrzy¿owaniu na Golgocie, idŸ na pó³nocny zachód a¿ do trzeciego grobu, potem obróæ siê na pó³nocny wschód i idŸ a¿ dojdziesz do pierwszego pala. Jest tam grób oznaczony napisem "Arch Stanton". ¯eby znaleŸæ pieni¹dze, musisz kopaæ jakieœ szeœæ stóp wg³¹b.}
{366}{}{Podejœæ do znaku, iœæ na pó³nocny zachód do trzeciego grobu, potem na pó³nocny wschód do pierwszego pala, potem popatrzeæ na "Arch Stanton"... w porz¹dku, Lloyd, chodŸmy. W koñcu potrzebujê kogoœ do kopania.}
{367}{}{No dobra. Spadam st¹d. Te¿ siê st¹d wydeleguj. (Pozwól Lloydowi st¹d wyjœæ.)}
{368}{}{To wszystko, co chcê wiedzieæ... rankiem zakopi¹ w grobie tak¿e ciebie.}
{375}{}{(Lloyd wygl¹da jakby chcia³ coœ powiedzieæ, ale jeszcze raz siê nad tym zastanowi³ i kiwa g³ow¹) No dobrze. Zdaje siê nie mam wyboru. ChodŸmy.}
{376}{}{Najpierw muszê jeszcze za³atwiæ kilka spraw. Poczekaj tu na mnie, wrócê za godzinê. (WyjdŸ z pokoju i schowaj siê na zewn¹trz, ¿eby sprawdziæ, czy Lloyd wyjdzie i idŸ za nim.)}
{377}{}{Najpierw muszê jeszcze za³atwiæ kilka spraw. Poczekaj tu na mnie, jeszcze wrócê.}
{378}{}{Jestem tu¿ za tob¹.}
{385}{}{Hmmmmm. Nie znam ciê, kolego... ale myœlê, ¿e chcia³bym poznaæ. Lloyd jestem. Niektórzy nazywaj¹ mnie Œliczny Ch³opiec, ale to inni tak mówi¹, nie ja.}
{386}{}{Hmmmmm. Nie znam ciê, kochana... ale myœlê, ¿e chcia³bym poznaæ. Lloyd jestem. Niektórzy nazywaj¹ mnie Œliczny Ch³opiec, ale to inni tak mówi¹, nie ja.}
{387}{}{Hmmmmm. Nie jestem a¿ taki g³upi, ¿eby odrzucaæ pomoc ze strony tak piêknej kobiety. Lloyd jestem. Niektórzy nazywaj¹ mnie Œliczny Ch³opiec, ale to inni tak mówi¹, nie ja.}
{388}{}{Mi³o mi ciê poznaæ. A wiêc... co powiesz na moj¹ propozycjê...?}
{395}{}{Mieliœmy z rodzin¹ Salvatore... nieporozumienie w kwestii mojego sukcesu przy jednym z ich sto³ów do gry. Wydaje mi siê, ¿e ta sprawa mo¿e zostaæ za³agodzona tylko jeœli oddalê siê od Nowego Reno tak bardzo, jak to mo¿liwe.}
{396}{}{Sukces przy jednym z ich sto³ów, tak? Ile wygra³eœ?}
{397}{}{Jak mogê pomóc?}
{398}{}{Co bêdê z tego mieæ?}
{399}{}{Chyba nie mogê ci pomóc, Lloyd. Myœlê, ¿e lepiej bêdzie, jeœli zapomnimy o tym spotkaniu. ¯egnam.}
{405}{}{Hmmmm... wygl¹da na to, ¿e masz doœæ sprzêtu, ¿eby s³u¿yæ za ochroniarza. Pomó¿ mi wydostaæ siê z miasta. OdprowadŸ mnie na równinê Golgoty na po³udnie st¹d, a zap³acê ci parê dolców za fatygê.}
{407}{}{Stoi. ChodŸmy. (IdŸ za nim.)}
{415}{}{(Blednie, lecz po chwili odzyskuje spokój) Wystarczaj¹co du¿o, ¿eby ich rozwœcieczyæ. Wiêkszoœæ wyda³em na ³apówki, ¿eby utrzymaæ oprychów Salvatore'a z dala od siebie na tyle, ¿eby zdo³aæ gdzieœ przycupn¹æ i siê schowaæ. Ostatnio ba³em siê pokazaæ na mieœcie...}
{416}{}{(Wygl¹da na zaskoczonego, lecz po chwili odzyskuje spokój) Wystarczaj¹co du¿o, ¿eby ich rozwœcieczyæ. Wiêkszoœæ wyda³em na ³apówki, ¿eby utrzymaæ oprychów Salvatore'a z dala od siebie na tyle, ¿eby zdo³aæ gdzieœ przycupn¹æ i siê schowaæ. Ostatnio ba³em siê pokazaæ na mieœcie...}
{417}{}{Pomogê ci, Lloyd, ale chcê po³owê pieniêdzy, które wygra³eœ. I jeœli wiesz, co dla ciebie dobre, to nie próbuj mnie oszukaæ.}
{418}{}{Pomogê ci, Lloyd, jeœli dasz mi po³owê swojej wygranej. To uczciwa wymiana jeœli mam ocaliæ twoj¹ skórê.}
{419}{}{W porz¹dku, pomogê ci. Zmiatajmy st¹d. (IdŸ za nim.)}
{420}{}{Chyba nie mogê ci pomóc. Do widzenia.}
{425}{}{(Lloyd wygl¹da jakby chcia³ coœ powiedzieæ, ale jeszcze raz siê nad tym zastanowi³ i kiwa g³ow¹) Zdaje siê nie mam wyboru. ChodŸmy.}
{427}{}{Nie, siedŸ tu cicho i czekaj na mnie, a¿ wrócê. Muszê najpierw za³atwiæ kilka spraw. Wrócê po ciebie póŸniej i wtedy pójdziemy na ten twój spacer.}
{435}{}{(Sztywnieje) Mo¿e. Kim jesteœ? Nie s¹dzê, ¿ebyœmy mieli ju¿ przyjemnoœæ...}
{436}{}{(Sztywnieje, po czym unosi brew) Mo¿e. Z pewnoœci¹ zapamiêta³bym tak¹ piêkn¹ pannê, nie s¹dzê wiêc, ¿ebyœmy mieli ju¿ przyjemnoœæ...?}
{437}{}{Daruj sobie te gadki, Lloyd. Jestem tu po pieni¹dze, które ukrad³eœ panu Salvatore.}
{438}{}{S³uchaj, Lloyd, oddaj mi kasê, a MO¯E zapomnê, ¿e siê spotkaliœmy na wystarczaj¹co d³ugo, ¿ebyœ zd¹¿y³ siê st¹d oddaliæ.}
{439}{}{Pan Salvatore przys³a³ mnie tu, by odzyskaæ swoje pieni¹dze i ¿ebyœ pos³u¿y³ za... przyk³ad. Ale to nie musi tak siê skoñczyæ... O ILE zdo³amy zawrzeæ jakieœ porozumienie.}
{445}{}{No dobrze ju¿, dobrze... (Prze³yka œlinê) Pieni¹dze s¹ zakopane w jednym z grobów na równinie Golgoty. Ale tylko ja wiem, gdzie to jest.}
{446}{}{Poka¿ mi.}
{448}{}{To najwiêksza kupa... a do licha, po prostu ciê zabijê i poszukam kasy na w³asn¹ rêkê.}
{455}{}{Hmmmmmm. Nie s¹dzê, ¿e ktoœ z nas w to wierzy... (prze³yka œlinê) ale mo¿e mogê ci zaufaæ. Pieni¹dze s¹ zakopane w jednym z grobów na równinie Golgoty na po³udnie od Nowego Reno. Ale tylko ja wiem, gdzie to jest.}
{459}{}{Och, daj se siana. Wychodzê. Zatrzymaj sobie swoje pieni¹dze i swoj¹ tajemnicê i zejdŸ mi z oczu.}
{465}{}{Hmmmm. "Porozumienie", powiadasz... no dobrze, dobrze... czego takiego chcesz?}
{466}{}{Wyprowadzê ciê z miasta za po³owê pieniêdzy, które wygra³eœ od pana Salvatore.}
{467}{}{Wyprowadzê ciê z miasta w zamian za wszystkie pieni¹dze, które wygra³eœ od pana Salvatore.}
{468}{}{Aj, niewa¿ne. Nic nie chcê - spadaj st¹d, zanim zmieniê zdanie. (Udaj, ¿e wychodzisz, schowaj siê, a potem idŸ za nim.)}
{469}{}{Aj, niewa¿ne. Nic nie chcê - spadaj st¹d, zanim zmieniê zdanie.}
{475}{}{No tak... hmmmm... wygl¹da na to, ¿e nie mam wyboru. Ale muszê zaprowadziæ ciê tam, gdzie ukry³em pieni¹dze, bo tak to ich nigdy nie znajdziesz. ChodŸmy.}
{476}{}{Najpierw muszê jeszcze za³atwiæ kilka spraw. Poczekaj tu na mnie, wrócê za godzinê. (Udaj, ¿e odchodzisz i ukryj siê, a potem idŸ za nim.)}
{477}{}{Nie, siedŸ tu cicho i czekaj na mnie, a¿ wrócê. Muszê najpierw za³atwiæ kilka spraw. Wrócê po ciebie póŸniej i wtedy pójdziemy na ten twój spacer.}
{478}{}{Jestem tu¿ za tob¹. (IdŸ za nim.)}
{555}{}{(Zrywa siê) Uch... ju¿ idziemy?}
{556}{}{Tak. ChodŸmy. (IdŸ za nim.)}
{557}{}{Nie, poczekaj tu, a¿ wrócê. Muszê najpierw za³atwiæ kilka spraw.}
{565}{}{A co do twojej propozycji, PRZYDA£ABY mi siê czyjaœ pomoc. Widzisz, muszê wiaæ z miasta, ale sprawy trochê siê pokomplikowa³y z powodu pewnego... nieporozumienia...}
{566}{}{Jakiego nieporozumienia?}
{585}{}{Czas wynieœæ siê z Reno...}
{586}{}{Cholerne pud³o...}
{587}{}{Nie pamiêtam, ¿eby by³o tak ciê¿kie...}
{595}{}{No to jesteœmy...}
{596}{}{To ten tutaj.}
{605}{}{No to jesteœmy... *fiuu*... pieni¹dze s¹... w tym grobie.}
{606}{}{£ap za ³opatê, Lloyd.}
{607}{}{Chcê najpierw przyjrzeæ siê temu grobowi...}
{609}{}{No dobrze, cofnij siê, a ja zacznê kopaæ...}
{610}{}{Sp³ywaj st¹d, Lloyd. Pieni¹dze s¹ teraz moje.}
{615}{}{(Sprawia wra¿enie zdyszanego) Bêdê wdziêczny... jeœli w ramach swoich... ochroniarskich obowi¹zków... osobiœcie go rozkopiesz.}
{616}{}{Uch...}
{617}{}{S¹ na tym œwiecie, Lloyd, dwa typy ludzi - ci, którzy maj¹ za³adowan¹ broñ oraz ci, którzy kopi¹.}
{620}{}{W porz¹dku, zrobiê to...}
{625}{}{(Lloyd mamrocze coœ pod nosem i zaczyna kopaæ.)}
{626}{}{(Lloyd mamrocze coœ pod nosem i zaczyna kopaæ... ostro¿nie. Po mniej ni¿ minucie wyci¹ga z piachu minê przeciwpiechotn¹ i odk³ada j¹ na bok. Trzêsie siê jak owca.)}
{627}{}{Baaardzo ³adnie. Œwietnie ci idzie. Tak trzymaæ. Kop trochê szybciej.}
{628}{}{£adny okaz, Lloyd. Kop DALEJ. Zobaczmy, co jest pod spodem.}
{635}{}{(Pó³ godziny póŸniej Lloydowi udaje siê odkopaæ wystarczaj¹co du¿o piachu, by mo¿na by³o dostrzec w ziemi niewielk¹ pokrywê... na pewno nie uda³oby ci siê jej znaleŸæ, gdyby Lloyd ci o niej nie powiedzia³. Lloyd bierze g³êboki oddech i ociera pot z czo³a) Stary... schron... przeciwatomowy.}
{636}{}{(Pó³ godziny póŸniej udaje ci siê odkopaæ wystarczaj¹co du¿o piachu, by mo¿na by³o dostrzec w ziemi niewielk¹ pokrywê. Nie uda³oby ci siê jej znaleŸæ, gdyby Lloyd nie pokaza³ ci, gdzie kopaæ. Kiedy odkopujesz pokrywê, Lloyd mówi) To stary schron przeciwatomowy. Znalaz³em go tydzieñ temu, gdy szwêda³em siê po okolicy.}
{637}{}{No dobra, zaraz j¹ otworzê i podzielimy siê.}
{638}{}{Otwórz pokrywê, Lloyd.}
{645}{}{(Piach wokó³ grobu wygl¹da jakby ktoœ w nim niedawno grzeba³. Z jakiegoœ powodu odleg³oœæ dziel¹ca Lloyda od grobu nasuwa ci podejrzenie, ¿e za³o¿ono tu pu³apkê.}
{646}{}{Myœlê, Lloyd, ¿e to jednak ty powinieneœ kopaæ.}
{647}{}{Hmmmm. Przyjrzyjmy siê temu grobowi z bliska...}
{648}{}{Odsuñ siê, Lloyd. Zaraz zacznê kopaæ.}
{655}{}{(Piach wokó³ grobu wygl¹da jakby ktoœ w nim niedawno grzeba³. To by siê trzyma³o kupy, gdyby Lloyd rzeczywiœcie zakopa³ tu pieni¹dze.)}
{665}{}{(Dok³adnie ogl¹dasz otoczenie i odgarniasz piach, odkrywaj¹c ukryt¹ pod spodem minê przeciwpiechotn¹. Ostro¿nie j¹ rozbrajasz i wk³adasz do plecaka.)}
{666}{}{I co, Lloyd, zapomnia³eœ o tym? Zobaczmy, czy zapomnisz o TYM, trupie.}
{667}{}{Myœlê, Lloyd, ¿e to TY powinieneœ kopaæ. Bierz siê do roboty.}
{668}{}{Ujdzie ci to na sucho... tym razem. A teraz odsuñ siê. Bêdê kopaæ dalej.}
{675}{}{(Pokrywa otwiera siê z g³oœnym zgrzytem, ukazuj¹c prowadz¹c¹ na dó³ czarn¹ otch³añ.)}
{676}{}{W³aŸ do œrodka, Lloyd.}
{677}{}{Odsuñ siê, Lloyd. Wchodzê tam.}
{685}{}{(Lloyd marszczy brwi, zastanawia siê chwilê nad komentarzem, ale tylko wzrusza ramionami i schodzi do œrodka.)}
{686}{}{Poœpiesz siê, Lloyd.}
{687}{}{HEJ, LLOYD, £AP! (Wrzuæ minê do dziury.)}
{688}{}{Jestem tu¿ za tob¹, Lloyd.}
{695}{}{(Dochodzi ciê z do³u przyt³umiony g³os Lloyda) Zaczekaj... ju¿ prawie mam... (S³ychaæ pocieranie metalu o metal, po czym wszystko cichnie.)}
{696}{}{Ruszaj siê, Lloyd. Nie mamy ca³ego dnia.}
{698}{}{Schodzê tam, Lloyd.}
{706}{}{Wszystko w ci¹gu jednego dnia...}
{715}{}{Jasne, jasne... wszystko jest twoje. Nie ma problemu. Pójdê ju¿. (Odwraca siê i odchodzi)}
{716}{}{(Pozwól mu odejœæ.)}
{717}{}{(Strzel mu w plecy.)}
{1000}{}{Kiedy po d³ugim marszu docieracie do podnó¿y wzgórz Golgoty, Lloyd prowadzi ciê do jednego z grobów.}
{1001}{}{Idziesz za Lloydem na Golgotê. Kiedy tam docieracie, Lloyd odkopuje jeden z grobów.}
{1002}{}{Gubisz Lloyda, gdy tylko opuszczacie Nowe Reno.}
{1050}{}{Pozwalasz Lloydowi odejœæ.}
{1051}{}{*utyskuje* Pieni¹¿ki, mog³yœcie byæ moje.}
{1052}{}{Uh...Dziêki za oszczêdzenie mojego ¿ycia.}
{1053}{}{Kiedy wychodzisz z grobu Lloyda ju¿ nie ma.}
{1054}{}{Zapomnij. To s¹ moje pieni¹dze i TY ich nie dostaniesz!}
{5213}{}{ Ja }
{7213}{}{Kto Ty}
