{100}{}{Widzisz szefow¹ dzia³u badañ, Marjorie Reed.}
{150}{}{Widzisz zmêczon¹ kobietê. Jej g³owê ogolono na ³yso. Ma na sobie bia³y kitel.}
{151}{}{Widzisz Marjorie Reed. Przegl¹da w³aœnie wyniki badañ mrucz¹c coœ do siebie pod nosem.}
{200}{}{Witaj, Myron.}
{201}{}{Myron, mogê ciê na chwilê prosiæ?}
{202}{}{Myron, wiesz mo¿e, kiedy dostaniemy nowy transport niewolników?}
{203}{}{Myron, wyniki ostatnich badañ s¹ bardzo obiecuj¹ce.}
{204}{}{Myron, masz woln¹ chwilê?}
{215}{}{Gdzie u diab³a jest Myron...}
{216}{}{Dajcie tu na górê Myrona. Musi to zobaczyæ.}
{217}{}{Szkoda, ¿e ci niewolnicy nie chc¹ siê zamkn¹æ...}
{218}{}{Gdzie jest ta strzykawka...}
{219}{}{Czy ktoœ widzia³ Numer 31? By³ tutaj dos³ownie przed chwil¹.}
{220}{}{Ka¿cie niewolnikom przynieœæ wiêcej Jetu Beta.}
{221}{}{Wyniki testów Jetu Beta s¹ bardzo obiecuj¹ce, ale...}
{222}{}{"Haj" trwa od 15 minut do godziny... przyjmijmy odstêp jednej dawki na godzinê... hmmmmnnn.}
{223}{}{Nie. Numer 12 wci¹¿ ma krwawienia z nosa...}
{224}{}{To ju¿ pi¹ty atak u Numeru 12... zwiêkszcie dawkê, zobaczymy co siê stanie...}
{225}{}{A wiêc jakiego RODZAJU to by³y halucynacje?}
{226}{}{SprawdŸ têtno tego tutaj. Jeœli siê jeszcze mieœci w granicach tolerancji, zwiêksz dawkê.}
{227}{}{Dlaczego niewolnica z grupy kontrolnej zabi³a sama siebie? Nawet nie robiliœmy na niej testów!}
{228}{}{Cholerni stra¿nicy s¹ zupe³nie do niczego...}
{235}{}{Dzieñ dobry, panie Myron. Testy przebiegaj¹ zgodnie z planem.}
{236}{}{Panie Myron, ten nowy rodzaj Jetu jest niesamowicie uzale¿niaj¹cy. Nasi niewolnicy gotowi s¹ dla niego zabiæ.}
{237}{}{Ucieszy siê pan zapewne s³ysz¹c, ¿e nasi niewolnicy gotowi s¹ zrezygnowaæ z jedzenia, ¿eby tylko dostawaæ kolejne dzia³ki Jetu Beta.}
{238}{}{Myronie, kim s¹ ci ludzie? To nowe obiekty?}
{239}{}{Trzecia grupa ma zdecydowanie najlepsze wyniki ze wszystkich.}
{240}{}{Myron, jeœli znalaz³by pan chwilê czasu... Moim zdaniem w sk³ad kolejnej grupy powinno wejœæ co najmniej troje dzieci.}
{241}{}{Numer 46 mia³ atak serca. Postanowiliœmy zmniejszyæ dozowanie do szeœciu dzia³ek dziennie.}
{242}{}{Panie Myron... pilnie potrzebujemy kolejnej dostawy strzykawek z Kryptopolis. Nie mo¿emy u¿ywaæ tych w nieskoñczonoœæ.}
{243}{}{Czy s¹ jakieœ wieœci o tym, kiedy dostarcz¹ nam nowych niewolników?}
{244}{}{Musieliœmy przenieœæ trzy jednostki z grupy nadzorczej do laboratoryjnej z powodu tych ataków.}
{245}{}{Mam z³e wiadomoœci. Musieliœmy zastrzeliæ jednego niewolnika podczas próby ucieczki. Co za marnotrawstwo!}
{246}{}{Ten pana nowy halucynogen jest obiecuj¹cy, choæ nie uzale¿nia tak silnie jak Jet...}
{250}{}{(£ysa kobieta nawet nie podnosi wzroku, ¿eby na ciebie spojrzeæ) Tak?}
{251}{}{Nie!}
{252}{}{Tak!}
{253}{}{He he. Ty ³ysa. Wygl¹da jak ch³op.}
{254}{}{Delen?}
{255}{}{OdejdŸ}
{256}{}{Kim jesteœ?}
{257}{}{Przepraszam, szukam innej ³ysej kobiety studiuj¹cej wynik badañ. Lepiej ju¿ sobie pójdê.}
{265}{}{(Kobieta przygl¹da ci siê ze zdziwieniem) Jesteœ obiektem z grupy nadzorczej? A zreszt¹, czy to wa¿ne... Stra¿! Zamkn¹æ ten obiekt!}
{266}{}{Gdzie obiekt? Moja nie widzi.}
{275}{}{S³uchaj, jestem bardzo zajêta... [Podnosi wzrok, obrzuca ciê zdziwionym spojrzeniem i zaczyna krzyczeæ.] KIM jesteœ? Kto ciê tu wpuœci³?}
{276}{}{S³uchaj, jestem bardzo zajêta... [Podnosi wzrok, obrzuca ciê zdziwionym spojrzeniem i zaczyna krzyczeæ.] Znowu ty? Czego chcesz tym razem?}
{277}{}{Drzwi by³y otwarte jak wrota stodo³y. He he... ³apiesz? Wrota stodo³y!}
{278}{}{Przydzielono mnie do pracy tutaj.}
{279}{}{Szukam Myrona. Jest gdzieœ tutaj?}
{280}{}{Widzê, ¿e przegl¹dasz wyniki badañ? Mogê rzuciæ okiem?}
{282}{}{Niewa¿ne. Przepraszam za zawracanie g³owy.}
{295}{}{Ten obszar jest zamkniêty dla... goœci. WyjdŸ st¹d, zanim wezwê stra¿.}
{296}{}{Sekundê, chcê ciê najpierw o coœ zapytaæ...}
{298}{}{Widzê, ¿e przegl¹dasz wyniki badañ? Mogê rzuciæ okiem? Chemia to takie moje ma³e hobby.}
{300}{}{W porz¹dku. Nie bêdê ci dalej przeszkadzaæ.}
{310}{}{Stra¿! Stra¿, wyprowadŸcie intruza!}
{315}{}{NASTÊPNY stra¿nik. Ha! Jakby by³ z was jakiœ po¿ytek... S³uchaj, ktokolwiek ciê tu przys³a³ powinien udzieliæ ci odpowiednich instrukcji. W razie w¹tpliwoœci porozmawiaj z innymi stra¿nikami. A teraz przestañ zawracaæ mi g³owê.}
{316}{}{Nie jestem stra¿nikiem, tylko naukowcem. Czym mam siê zaj¹æ?}
{317}{}{Przepraszam, ale odk¹d mój wzrok pad³ na ciebie marzê wprost o tym, ¿ebyœ to TY mnie oprowadzi³a. Mo¿e póŸniej umówimy siê na kolacjê...?}
{318}{}{Dziêki. Jesteœ bardzo mi³a.}
{325}{}{Jesteœ NAUKOWCEM...? Hmmmm. Nigdy ciê tu nie widzia³am. Co wiesz o badaniach farmaceutycznych?}
{326}{}{Wystarczaj¹co du¿o. Chcesz zobaczyæ, co potrafiê?}
{327}{}{Wiem ca³kiem sporo o sposobach uzyskiwania podstawowych zwi¹zków neurochemicznych. Myœlê, ¿e przyda ci siê ktoœ taki jak ja.}
{328}{}{Muszê ju¿ iœæ.}
{335}{}{Nie! Chcê zobaczyæ jak st¹d wychodzisz! Zmykaj, zanim wezwê stra¿e.}
{336}{}{Dobrze.}
{337}{}{Ju¿ idê... ::pod nosem::... ty ³ysa zdziro.}
{345}{}{Hmmmm. W porz¹dku. Pozwól, ¿e przedstawiê ci pokrótce obszar naszych badañ: testujemy tu efekty dzia³ania metaamfetaminy zwanej Jet i pracujemy nad jej udoskonaleniem.}
{346}{}{Rozumiem. I jak postêpuj¹ badania?}
{347}{}{Rozumiem. Jeœli pozwolisz, chêtnie siê tutaj rozejrzê.}
{355}{}{Nie najlepiej. Goni nas termin i musimy jak najszybciej udoskonaliæ proces produkcji Jetu.}
{356}{}{Dlaczego? Jet i tak jest niezwykle silnie uzale¿niaj¹cym œrodkiem.}
{357}{}{Sk¹d ten poœpiech?}
{358}{}{Niewdziêczna robota. S³uchaj, muszê siê zaj¹æ pewn¹ piln¹ spraw¹, ale nied³ugo wrócê.}
{365}{}{Nikt nam tego nie powiedzia³ wprost, ale zapewne chodzi o dystrybucjê Jetu w Redding. Jet jest *doœæ* skuteczny, ale mo¿na przy nim jeszcze wiele ulepszyæ. Zw³aszcza, ¿e 'góra' chce zwiêkszyæ liczbê uzale¿nionych w Redding.}
{366}{}{O co chodzi z tym ca³ym Redding?}
{367}{}{Có¿, w takim razie pozostaje mi ¿yczyæ ci powodzenia.}
{375}{}{Jet jest *doœæ* skuteczny, ale mo¿na przy nim jeszcze wiele ulepszyæ. 'Góra' chce zwiêkszyæ iloœæ towaru trafiaj¹cego do Redding. Odsetek uzale¿nionych ma siê zbli¿yæ do 100%. Dlatego musimy pracowaæ dniem i noc¹.}
{377}{}{Dziêki za informacje. Wrócê innym razem.}
{385}{}{Uzale¿nij górników z Redding od Jetu, a ktokolwiek bêdzie kontrolowa³ dostawy narkotyku, bêdzie kontrolowa³ ca³e miasto. Tak zyskuje siê w³adzê.}
{386}{}{A kto kontroluje prochy?}
{395}{}{Kto kontroluje prochy? Rodzina Mordino. Przecie¿ to na ich ¿yczenie Myron wykona³ wszystkie badania przygotowawcze, w wyniku których powsta³ Jet. My zajmujemy siê tylko szczegó³ami.}
{396}{}{To znaczy, ¿e Myron jest twoim szefem?}
{405}{}{Mo¿na tak powiedzieæ. Ch³opak jest bystry, trudno mu tego odmówiæ, ale nie interesuje go, co siê tutaj dzieje. Zwykle siedzi w tej swojej podziemnej norze... nie przyjmuje ¿adnych goœci, tylko od czasu do czasu jakieœ prostytutki. Typowy manager projektu.}
{406}{}{Mogê siê z nim zobaczyæ?}
{407}{}{Tak, ale ci z marketingu s¹ jeszcze gorsi. Dziêki za informacje. Zajrzê do ciebie póŸniej.}
{415}{}{Czemu nie... wystawiê ci tymczasow¹ przepustkê, poka¿ j¹ stra¿nikom. Tylko nie siedŸ tam zbyt d³ugo, Myron nie jest zbyt towarzyski.}
{416}{}{Czemu nie... wystawiê ci tymczasow¹ przepustkê, poka¿ j¹ stra¿nikom. Tylko nie siedŸ tam zbyt d³ugo, Myron nie jest zbyt towarzyski... chodŸ w twoim przypadku mo¿e zrobiæ wyj¹tek.}
{417}{}{Dziêki za przepustkê. Zobaczymy siê póŸniej.}
{425}{}{S³uchaj, jestem bardzo zajêta, wiêc jeœli pozwolisz...}
{426}{}{S³uchaj, ja... jestem... bardzo zajêta. Przykro mi...}
{427}{}{Trudno...}
{428}{}{Có¿, trudno.}
{429}{}{Mimo to, dziêki... ::pod nosem:: ...ty sztywna, jajog³owa zdziro.}
{435}{}{To... hmm... Jestem zaszczycona, ale i bardzo zajêta... wiêc... hmm...}
{436}{}{Có¿, mo¿e w takim razie odbiorê ciê z pracy i pójdziemy na kolacjê? ¯adnych zobowi¹zañ. Wygl¹dasz na kogoœ, komu przyda siê przerwa w pracy... odrobina relaksu.}
{437}{}{Có¿, warto by³o spróbowaæ. Do zobaczenia.}
{445}{}{Có¿, nie jestem a¿ tak zajêta... ha... prawdê mówi¹c, to jestem bardzo zajêta. To znaczy: zwykle wykonujê tylko rutynowe testy chemiczne. Tylko od czasu do czasu jakiœ niewolnik zeœwiruje...}
{446}{}{Czy celowe podawanie eksperymentalnej metaamfetaminy nie k³óci siê z twoim sumieniem?}
{447}{}{Ojej. To brzmi niebezpiecznie. Nie boisz siê, ¿e coœ ci siê stanie? Czy œmiertelnoœæ wœród pacjentów jest wysoka?}
{448}{}{Testy chemiczne? Naprawdê? I jak posuwaj¹ siê badania?}
{449}{}{Brzmi fascynuj¹co, ale muszê ju¿ iœæ.... wrócê... innym razem.}
{455}{}{To mia³ byæ jakiœ dowcip?}
{456}{}{Tylko pytam. A co by by³o, gdyby schwytali ciê ³owcy niewolników i sprzedali tutaj, gdzie napompowano by ciê jakimiœ prochami?}
{457}{}{Tak, oczywiœcie. Muszê ju¿ iœæ.}
{465}{}{Ja jestem po TEJ stronie krat, oni po TAMTEJ. Skoro ju¿ rozwa¿amy sytuacjê hipotetyczne, chcesz siê dowiedzieæ, jak to jest byæ jednym z nich? Znajdzie siê jeszcze miejsce dla dodatkowego niewolnika.}
{466}{}{Zaraz, zaraz...}
{467}{}{Nie, dziêki. Do zobaczenia.}
{475}{}{Œmiertelnoœæ? Ca³kiem spora. G³ównie przypadkowe przedawkowania - b³¹d laborantów - lub samookaleczenia. Niektórzy niewolnicy sami b³agaj¹ nas o wiêksz¹ dawkê, w rezultacie której gin¹.}
{476}{}{A poza tym, jak przebiegaj¹ badania?}
{477}{}{Rozumiem. Wielkie dziêki za informacje.}
{485}{}{Spróbuj na dole, w laboratorium. To te pilnie strze¿one drzwi. Jak go spotkasz, powiedz mu, ¿eby tu do nas zajrza³... jeœli nie jest ZBYT zajêty.}
{1000}{}{Marjorie da³a ci tymczasow¹ przepustkê.}
