{100}{}{Widzisz automat do gry.}
{101}{}{Widzisz błyszczący automat do gry.}
{150}{}{Widzisz automat do gry. Możesz przysiąc, że kątem oka dostrzegasz, jak na ciebie patrzy.}
{151}{}{Widzisz automat do gry. Jego połyskująca rama i złoty uchwyt migoczą kusząco wsród świateł Nowego Reno.}
{152}{}{Widzisz błyszczący automat do gry. Jest przeznaczony dla graczy o wysoką stawkę... minimalny zakład to }
{153}{}{ dolarów.}
{154}{}{Widzisz błyszczący automat do gry.}
{160}{}{*Chodź tu na chwilę i zagraj, kowboju.*}
{161}{}{*Witaj marynarzu.*}
{162}{}{*Wrzuć monetę, pociągnij rączkę. Będę dla ciebie miły.*}
{163}{}{*Tik... Tik... Tiiiiik...*}
{164}{}{*Hej, ślicznotko. Chodź tu na chwilę i zagraj.*}
{165}{}{*Witaj, ślicznotko.*}
{166}{}{*Proszę proszę, jaka miła mała ślicznotka. Może chodź tu i zagraj na mnie?*}
{175}{}{*Dzyń*}
{176}{}{*Bing*}
{177}{}{*Kaaa-czing*}
{178}{}{*Zzzzzzz*}
{179}{}{*Dry-i-dzyń*}
{180}{}{*Dumne-dzyń*}
{185}{}{Widzisz dziwne, złote, metalowe pudło z trojgiem oczu i jedną ręką. To jedna z najpiękniejszych rzeczy, jakie kiedykolwiek zdarzyło ci się widzieć.}
{186}{}{Ja }
{187}{}{ ty kto?}
{188}{}{Ja tęsknić MAMA. }
{189}{}{ tęsknić ARR-YO. Ja chcieć wracać dodom}
{190}{}{(Uściśnij mu rękę)}
{191}{}{Ty jakiś dziwny mutant}
{192}{}{Chwalcie Kryptę! Chwalcie Kryptę!}
{193}{}{Ty być hydroprocesor?}
{194}{}{Odejdź w poszukiwaniu innych błyszczących rzeczy}
{195}{}{Odejdź.}
{205}{}{Dziwne, śliczne, metalowe pudło z trojgiem oczu i jedną ręką nie odpowiada.}
{206}{}{JA }
{207}{}{! TY MI ODPOWIE!}
{208}{}{(Uściśnij mu rękę)}
{209}{}{Ja dziecko Przybysz z Krypty. Ty ze mną rozmawiać JUŻ.}
{210}{}{Ty jakiś dziwny mutant}
{211}{}{Ty być hydroprocesor?}
{212}{}{Odejdź w poszukiwaniu innych błyszczących rzeczy}
{213}{}{Odejdź.}
{220}{}{Chwytasz ramię pudła i potrząsasz nim serdecznie. Kiedy to robisz, rozlega się *bzzzzzzzz* i pudło przemawia! "Wrzuć... monetę."}
{221}{}{Aaaaaach! Robot! Robot! Uciekaaaaać}
{222}{}{Odejdź.}
{225}{}{Gapisz się na automat myśląc o tym, że nie masz dość pieniędzy, żeby zagrać i przeklinasz własną nędzę. Może kiedy indziej...}
{226}{}{Odejdź.}
{230}{}{Widzisz automat do gry. Jego połyskująca rama i złoty uchwyt migoczą kusząco od świateł Nowego Reno. Jego wrzutnik dziwnie cię przyciąga. Czujesz jak z przejęcia na twarzy robią ci się wypieki.}
{231}{}{(Twoja ręka drży z przejęcia, gdy sięgasz po monety. Maszyna wciąż szepcze do ciebie.) *No dalej, kochanie... tak jest... no już... nie drażnij się...*}
{232}{}{(Twoja ręka drży z przejęcia, gdy sięgasz po monety. Automat wciąż szepcze do ciebie.) *No dalej, kochanie... tak jest... złap rączkę... chwyć ją mocno... no dalej...*}
{233}{}{Masz }
{234}{}{ własnego dolara. Zaryzykujesz do końca?}
{235}{}{Masz }
{236}{}{ dolarów. Postawić }
{237}{}{ dolar?}
{238}{}{Postawić }
{239}{}{ dolarów?}
{240}{}{Jak na jedną noc wystarczy.}
{241}{}{Na dzisiaj wystarczy.}
{245}{}{Obrazki kręcą się i... nic z tego.}
{246}{}{NIC. NIC! Słyszysz jak się śmieje i wpadasz w gniew... ochroniarze muszą odciągać od maszyny twoje wrzeszczące ciało.}
{247}{}{(Maszyna rechocze) *Dostałem już, czego chciałeł od tego związku. Wybacz, malutka. Uważaj, żeby cię drzwi od kasyna nie trzasnęły w tyłek, jak będziesz wychodzić. Ha ha ha ha ha ha.}
{248}{}{Zostało ci teraz }
{249}{}{ dolarów. Chcesz grać dalej?}
{250}{}{Masz }
{251}{}{ dolarów. Postawisz je wszystkie?}
{252}{}{Nie masz już pieniędzy. Jak na jedną noc musi ci już wystarczyć.}
{253}{}{Nie masz już pieniędzy. Na dziś musi ci już wystarczyć.}
{254}{}{Jak na jedną noc wystarczy.}
{255}{}{Na dzisiaj wystarczy.}
{260}{}{Trzy sztylety. Wygrywasz równowartość stawki.}
{261}{}{(Maszyna wciąż szepcze do ciebie) *No dalej, skarbie... to się każdemu choć raz przytrafia... spróbuj znowu... proszę...*}
{262}{}{(Automat wciąż szepcze do ciebie) *No dalej, kochanie... spróbuj jeszcze raz... złap za rączkę... trzymaj ja mocno... no dalej...*}
{263}{}{Wciąż jeszcze masz }
{264}{}{ dolara. Grasz dalej?}
{265}{}{Wciąż jeszcze masz }
{266}{}{ dolarów. Grasz dalej?}
{267}{}{Jak na jedną noc wystarczy.}
{268}{}{Na dzisiaj wystarczy.}
{275}{}{Trzy pociski! Podwajasz wygraną!}
{276}{}{(Maszyna wzdycha z zachwytu) *Tak jest, kochanie... ciągnij za rączkę... szybciej, mocniej, szybciej... no dalej...*}
{277}{}{(Automat mruczy z zachwytu) *Tak jest, malutka... ciągnij za rączkę... szybciej, mocniej, szybciej... no dalej...*}
{278}{}{Zostało ci teraz }
{279}{}{ dolarów! Grasz dalej?}
{280}{}{Jak na jedną noc wystarczy.}
{281}{}{Na dzisiaj wystarczy.}
{290}{}{Trzy granaty! Ale jazda! Potrajasz wygraną!}
{291}{}{(Maszyna piszczy z zachwytu, gdy monety bębnią o podajnik) *Aaaaajajaj! O to chodzi, skahbie! O Boże, tak! Tak! Tak, jeszcze raz! Szybciej! Mocniej! Na co czekasz?! Jeszcze raz!*}
{292}{}{(Automat mruczy z zachwytu, gdy monety bębnią o podajnik) *Eeeeejejej! O to chodzi, malutka! Kim jest twój tatuś?! Kim jest twój tatuś?! Jeszcze raz! Tym razem szarpnij mocniej! Mocniej!*}
{293}{}{Kręcąc biodrami i machając w górze rękami wykonaj taniec zwycięstwa, potem weź głęboki oddech i graj dalej.}
{294}{}{No dalej, granaty! Maleństwo potrzebuje nowej pary butów! (Graj dalej.)}
{295}{}{Zostało ci teraz }
{296}{}{ dolarów. Grasz dalej?}
{297}{}{Jak na jedną noc wystarczy.}
{298}{}{Na dzisiaj wystarczy.}
{305}{}{(Widzisz automat do gry. Jej połyskująca rama i złoty uchwyt migoczą kusząco wśród świateł Nowego Reno. Jej wrzutnik dziwnie cię przyciąga - czujesz jak z przejęcia na twarzy robią ci się wypieki. Kiedy się tak na nią gapisz, jedno z jej okienek mruga do ciebie. Z wrzutnika dobiega cię gardłowy głos) *Witaj, powiadam! Wiiitaaaj, skarbie. Chcesz spędzić ze mną kilka upojnych chwil?*}
{306}{}{(Widzisz automat do gry. Jego mocna, chropowata rama i złoty uchwyt lśnią jak słońce wśród świateł Nowego Reno. Jego wrzutnik kusi cię i czujesz jak z przejęcia na twarzy robią ci się wypieki. Kiedy się tak na niego gapisz, potężny, męski, szepczący głos zaczyna dobiegać do ciebie z wrzutnika) *Nigdy wcześniej nie widziałem tu tak pięknej kobiety jak ty panienko. Chcesz spróbować szczęścia ze mną?}
{307}{}{::Uszczypnij się::}
{308}{}{O... cześć?}
{309}{}{::Weź głęboki oddech i odejdź.::}
{315}{}{*Wciąż tu jestem, ślicznotko.* (Automat do gry zniża głos) *No nie bądź taka... chcesz postawić zakład?*}
{316}{}{*Wciąż tu jestem, skahbie.* (Maszyna zniża głos) *Mój ty silny mężczyzno... no nie bądź taki... chcesz wsadzić kilka monet starej maszynie?}
{317}{}{*Ktooo* tyyyy?}
{318}{}{Oszyfiście zssałoszę śśsię spszyjemnościom}
{319}{}{Chyba lepiej pójdę sobie, zanim wsadzę ci coś, czego byłoby mi potem żal. (Odejdź.)}
{320}{}{::Weź głęboki oddech i odejdź.::}
{325}{}{*Jestem twoim idealnym mężczyzną.* (Automat rzuca ci porozumiewawcze mrugnięcie) *Daj mi parę monet, a zadowolę cię tak, jak jeszcze ŻADEN mężczyzna cię nie zadowolił.*}
{326}{}{*Jestem twoją idealną kobietą, skahbie. Chcę tylko, żeby ktoś zwrócił na mnie uwagę. Pomożesz swojej starej przyjaciółce? No chodź, tylko jedną albo dwie monety.*}
{327}{}{Nie moszszemy po prosstu porozmawiać}
{328}{}{Oszyfiście zssałoszę śśsię spszyjemnościom}
{329}{}{Chyba lepiej pójdę sobie, zanim wsadzę ci coś, czego byłoby mi potem żal. (Odejdź.)}
{330}{}{::Weź głęboki oddech i odejdź.::}
{335}{}{*Pewnie, że możemy, kochanie.* (Automat sprawia wrażenie, jakby ci współczuł) *Co kłopocze twoją małą śliczną główkę?*}
{336}{}{*Pewnie, że możemy, skarbie.* (Maszyna sprawia wrażenie, jakby ci współczuła) *Co cię gryzie, przystojniaku?*}
{337}{}{Tęsknię za MAMĄ i ARROYO, i... nie mogę znaleźć GECKa, i... *sniff*}
{338}{}{Tęsknię za MAMĄ i ktos NAPADŁ Arroyo, i... nie wiem gdzie oni są... i... *sniff*}
{339}{}{Muszę naprawić wielki statek... i nie wiem JAK... i mo-mo-moja Mama ZNIKŁA, i... *sniff*}
{340}{}{Gra się ssskońszyła... ajasię tylk-ko krencę fkółko i... boję się sze to jusz KONIEC i... *sniff*}
{341}{}{Poprosstu Fhallowt tfaa nie opssługuje mojej karty 3D Fxxxx, a ona kosztowała tyle *pieniency* i *sniff*}
{342}{}{To miała pyćśś dobra posstaćśś, ale chyba wszszystkie punkty poszszły w *złe* cechy... terass mam gófnianą posstaćśś... no i... *sniff*}
{343}{}{Rossmafiam sobie z automatem do gry, musi pyć semną kiepssko}
{344}{}{::Weź głęboki oddech i odejdź.::}
{350}{}{*No już dobrze, spokojnie... nie zawracaj już sobie tym swojej, ślicznej małej główki... pozwól mi się tym zająć. Połóż na mnie swoją głowę. Wszystko będzie dobrze, wyrzuć to z siebie.*}
{351}{}{*No już dobrze, spokojnie... nie przejmuj się już tym tak, skarbie... pozwól mi się tym zająć. Połóż na mnie swoją przystojną główkę. Wszystko będzie dobrze, wyrzuć to z siebie.*}
{352}{}{Dzięki, *sniff* zaffsze można na ciebie liszyć}
{353}{}{Jesteś jetyną *miłą* ossobą wszy-wszyscy inni somtacy podli ichcą mnie *skszywdzić* i zabrać moje pienionce i... *sniff*}
{354}{}{::Weź głęboki oddech i odejdź.::}
{360}{}{(Kładziesz swoją zmęczoną głowę na automacie)}
{361}{}{*Dasz sobie radę, ślicznotko? Miałbym wyrzuty sumienia, gdybym puścił cię stąd w tym stanie.*}
{362}{}{*Dasz sobie radę, skarbie? Miałabym wyrzuty sumienia, gdybym puściła cię stąd w tym stanie.*}
{363}{}{Nic mi nie bęcie... dzienki zza rosmofe, kooochaaam cię}
{370}{}{(Wydaje ci się, że w jednym z okienek pokazuje się łza) }
{371}{}{*Jesteś ostatnią bohaterką, jaka nam została w tym podłym świecie kanalii i rabusiów, }
{372}{}{. Ty... ty... trzymaj się mocno, słyszysz?* (Odwraca się) Lepiej odejdź, zanim zacznę się źle zachowywać.*}
{373}{}{*Jesteś ostatnim bohaterem, jaki nam został w tym podłym świecie kanalii i rabusiów, }
{374}{}{. Ty... ty... trzymaj się mocno, słyszysz?* (Odwraca się) Lepiej odejdź, zanim się zrobię okrutna.*}
{375}{}{Paaaaa}
{380}{}{Widzisz automat przeznaczony do gry o wysokie stawki - najniższa stawka wynosi }
{381}{}{ dolców. Jego połyskująca rama i złoty uchwyt migoczą kusząco wsród świateł Nowego Reno. Jego wrzutnik dziwnie cię przyciąga. Czujesz jak z przejęcia na twarzy robią ci się wypieki.}
{382}{}{(Twoja ręka drży z przejęcia, gdy sięgasz po monety. Maszyna wciąż szepcze do ciebie.) *No dalej, kochanie... tak jest... no już... nie drażnij się...*}
{383}{}{(Twoja ręka drży z przejęcia, gdy sięgasz po monety. Automat wciąż szepcze do ciebie.) *No dalej, kochanie... tak jest... złap rączkę... chwyć ją mocno... no dalej...*}
{384}{}{Masz }
{385}{}{ dolarów. Chcesz postawić wszystko?}
{386}{}{Masz }
{387}{}{ dolarów. Postawić }
{388}{}{ dolarów?}
{389}{}{Postawić }
{390}{}{ dolarów?}
{391}{}{Jak na jedną noc wystarczy.}
{392}{}{Na dzisiaj wystarczy.}
{400}{}{Obrazki kręcą się i... nic z tego.}
{401}{}{NIC. NIC! Słyszysz jak się śmieje i wpadasz w gniew... ochroniarze muszą odciągać od maszyny twoje wrzeszczące ciało.}
{402}{}{(Maszyna rechocze) *Dostałem już, czego chciałeł od tego związku. Wybacz, malutka. Uważaj, żeby cię drzwi od kasyna nie trzasnęły w tyłek, jak będziesz wychodzić. Ha ha ha ha ha ha.}
{403}{}{Zostało ci teraz }
{404}{}{ dolarów. Chcesz grać dalej?}
{405}{}{Masz }
{406}{}{ dolarów. Chcesz postawić wszystko?}
{407}{}{Nie masz na dalszą grę. Tej nocy musi ci już wystarczyć.}
{408}{}{Nie masz na dalszą grę. Na dziś musi ci już wystarczyć.}
{409}{}{Jak na jedną noc wystarczy.}
{410}{}{Na dzisiaj wystarczy.}
{415}{}{Trzy bomby... wygrywasz równowartość stawki.}
{416}{}{(Maszyna wciąż szepcze do ciebie) *No dalej, skarbie... to się każdemu choć raz przytrafia... spróbuj znowu... proszę...*}
{417}{}{(Automat wciąż szepcze do ciebie) *No dalej, kochanie... spróbuj jeszcze raz... złap za rączkę... trzymaj ja mocno... no dalej...*}
{418}{}{Wciąż jeszcze masz }
{419}{}{ dolarów. Grasz dalej?}
{420}{}{Jak na jedną noc wystarczy.}
{421}{}{Na dzisiaj wystarczy.}
{425}{}{Trzy atomówki! Podwajasz wygraną!}
{426}{}{(Maszyna wzdycha z zachwytu) *Tak jest, kochanie... ciągnij za rączkę... szybciej, mocniej, szybciej... no dalej...*}
{427}{}{(Automat mruczy z zachwytu) *Tak jest, malutka... ciągnij za rączkę... szybciej, mocniej, szybciej... no dalej...*}
{428}{}{Zostało ci teraz }
{429}{}{ dolarów! Grasz dalej?}
{430}{}{Jak na jedną noc wystarczy.}
{431}{}{Na dzisiaj wystarczy.}
{435}{}{Trzy grybki atomowe! Potrajasz wygraną!}
{436}{}{(Maszyna piszczy z zachwytu, gdy monety bębnią o podajnik) *Aaaaajajaj! O to chodzi, skahbie! O Boże, tak! Tak! Tak, jeszcze raz! Szybciej! Mocniej! Na co czekasz?! Jeszcze raz!*}
{437}{}{(Automat mruczy z zachwytu, gdy monety bębnią o podajnik) *Eeeeejejej! O to chodzi, malutka! Kim jest twój tatuś?! Kim jest twój tatuś?! Jeszcze raz! Tym razem szarpnij mocniej! Mocniej!*}
{438}{}{Kręcąc biodrami i machając w górze rękami wykonaj taniec zwycięstwa, potem weź głęboki oddech i graj dalej.}
{439}{}{No dalej, grzybki atomowe! Maleństwo potrzebuje nowej pary butów! (Graj dalej.)}
{440}{}{Zostało ci teraz }
{441}{}{ dolarów. Grasz dalej?}
{442}{}{Jak na jedną noc wystarczy.}
{443}{}{Na dzisiaj wystarczy.}
{1000}{}{Szanse nie wydają się całkiem równe.}
{1001}{}{Szanse wydają się równe.}
{1005}{}{Nie jesteś w stanie określić swoich szans.}
{1006}{}{Szanse wydają się mniej więcej równe.}
{1010}{}{Szanse wydają się równe.}
{1011}{}{Szanse nie wydają się równe.}
{1015}{}{Szanse wydają się równe.}
{1016}{}{Szanse nie wydają się równe.}
