# 0.  LOOK, CLOSED (WTG)
{100}{}{Widzisz sejf na kombinacjê wmurowany w œcianê. Jest zamkniêty.}

# 1.  LOOK, OPEN (WTG)
{101}{}{Widzisz sejf na kombinacjê wmurowany w œcianê. Jest otwarty.}

# LOCKPICKING
# trapped
{120}{}{Ju¿ chcesz otwieraæ sejf, gdy nagle zauwa¿asz lont biegn¹cy w œcianê tu¿ pod drzwiami. Wygl¹da na to, ¿e ten sejf ma za³o¿on¹ pu³apkê.}
{121}{}{Wci¹¿ widzisz za³o¿on¹ w sejfie pu³apkê.}

# successfull unlock
{150}{}{S³ychaæ KER-KLANK, gdy sejf siê otwiera.}

# lucky unlock
{160}{}{Obracasz pokrêt³em w przypadkowy sposób, gdy nagle trafia ono na kombinacjê... s³ychaæ KER-KLANK, i mechanizm sejfu jest otwarty.}

# failed unlocks
{170}{}{Obracasz powoli pokrêt³o przez kilka minut, ale nic z tego nie wychodzi.}
{171}{}{Obracasz pokrêt³o przez kilka minut, ale nic siê nie dzieje.}

# TRAPS
# disarm
{180}{}{Znajdujesz pu³apkê za³o¿on¹ w sejfie i skutecznie j¹ rozbrajasz.}
{181}{}{Udaje ci siê skutecznie rozbroiæ pu³apkê przy sejfie.}

# find trap
{190}{}{Znajdujesz pu³apkê przy sejfie, ale nie udaje ci siê jej rozbroiæ.}

# fail
{200}{}{Nie wygl¹da na to, aby by³a tam jakaœ pu³apka.}
{201}{}{Nie udaje ci siê rozbroiæ pu³apki.}

# fail critical

# CHANGING COMBO ON SAFE
# trap needs re-arming
{220}{}{Chyba najlepiej by³oby najpierw z powrotem uzbroiæ sejf plastikiem lub dynamitem.}

# changed combination
{230}{}{Uda³o ci siê zmieniæ kombinacjê sejfu... che che che...}
{231}{}{Uda³o ci siê zmieniæ kombinacjê sejfu... po raz kolejny.}

# no skills
{240}{}{Nie masz wystarczaj¹co umiejêtnoœci, aby zmieniæ kombinacjê.}
{241}{}{ nie ma wystarczaj¹co umiejêtnoœci, aby zmieniæ kombinacjê.}

# it's open
{250}{}{Sejf musi byæ zamkniêty.}

# REARMING TRAP
{260}{}{Wygl¹da na to, ¿e w sejfie ju¿ jest pu³apka.}

{270}{}{Nie udaje ci siê za³o¿yæ pu³apki w sejfie.}
{271}{}{ zawodzi przy zak³adaniu pu³apki w sejfie.}

{280}{}{Pu³apka w sejfie znowu jest aktywna.}

# trap_boom
{300}{}{S³yszysz z góry st³umiony wybuch.}

{400}{}{Otwierasz ma³y panel u do³u sejfu. Gdyby pani Bishop nie powiedzia³a ci o tym, chyba nie uda³oby ci siê go znaleŸæ. W œrodku znajdujesz dziwnie wygl¹daj¹c¹ nak³adkê do pip boya.}

# critical fail
{290}{}{Podczas poszukiwañ w sejfie pu³apki wywo³ujesz eksplozjê.}
{291}{}{Podczas rozbrajania pu³apki poci¹gasz za nieodpowiedni kabel.}