{100}{}{Widzisz du¿¹ kadŸ do pêdzenia bimbru. Ze œrodka dochodzi niski, bucz¹cy dŸwiêk.}
{110}{}{Widzisz du¿¹ kadŸ do pêdzenia bimbru. W œrodku p³ywa ogon radskorpiona.}
{120}{}{Widzisz du¿¹ kadŸ do pêdzenia bimbru. Jest zepsuta, a zniszczeñ chyba nie da siê naprawiæ.}
{130}{}{KadŸ zatrzymuje siê. Chyba nie da siê ju¿ jej naprawiæ.}
{140}{}{Wrzucasz to do kadzi i obserwujesz, jak zanurza siê, wypuszczaj¹c truciznê.}
{150}{}{Chyba jest nie do naprawy.}
{200}{}{::Krrr-czzzz::}
{201}{}{::Brzdêk::}
{202}{}{::Brrrr-brzdêk::}
{203}{}{::Bum-bam::}
{204}{}{::Zzzzzzttt::}
{250}{}{Hmmmmmmmm}
{251}{}{Thmmmmmmm}
{300}{}{Uda³o ci siê zniszczyæ destylarniê rodziny Wrightów.}
