{100}{}{Widzisz nisk¹, szczup³¹ kobietê ubran¹ w niebiesk¹, aksamitn¹ sukienkê.}
{101}{}{Widzisz wdowê Ariel.}
{102}{}{Widzisz nisk¹, szczup³¹ kobietê ubran¹ w niebiesk¹, aksamitn¹ sukienkê letni¹. Wygl¹da na zasmucon¹.}
{103}{}{Witaj, jestem Ariel. Chyba ciê tu wczeœniej nie widzia³am. Kim jesteœ?}
{104}{}{Ja}
{105}{}{Uch... ty smutna. Czemu?}
{106}{}{Moja ju¿ iœæ.}
{107}{}{Witaj Ariel, nazywam siê}
{108}{}{Czeœæ. Wygl¹dasz na przybit¹. Co siê sta³o?}
{109}{}{Moje imiê nie jest ci do niczego potrzebne, ale mi przyda siê kilka informacji od ciebie.}
{110}{}{Wybacz. Nie mam na to czasu.}
{111}{}{Mi³o mi ciê poznaæ. Jak mogê ci pomóc?}
{112}{}{Odpowie pytania?}
{113}{}{Niczego. Czeœæ.}
{114}{}{Raczej nie jesteœ w stanie mi pomóc. Na razie.}
{115}{}{Najpierw chcê zadaæ wam kilka pytañ!}
{116}{}{Przepraszam za zak³ócanie ci spokoju, ale czy mog³abyœ odpowiedzieæ mi na kilka pytañ?}
{117}{}{Mam tylko trochê problemów osobistych. Naprawdê nic wielkiego.}
{118}{}{Ty mówi, moja s³ucha. To pomaga.}
{119}{}{Dobra. Nie mówi problem. Odpowie pytania?}
{120}{}{Umiem s³uchaæ Ariel, a jeœli opowiesz mi o tym, co ciê gryzie, to mo¿e po prostu ci ul¿y.}
{121}{}{Dobra. Na razie zapomnijmy o problemach. Czy odpowiesz mi na kilka pytañ?}
{122}{}{Kobieto, ka¿dy ma problemy. Naucz siê radziæ sobie z nimi.}
{123}{}{Wybacz, ale nie mam czasu dla kogoœ z twoim tupetem. Do widzenia.}
{124}{}{}
{125}{}{}
{126}{}{No dobra.}
{127}{}{Co chcesz wiedzieæ?}
{128}{}{Ty uwiêzieniec?}
{129}{}{Sz'mierci dobre dla ty?}
{130}{}{Chce wyjœæ?}
{131}{}{Czemu ty smutna?}
{132}{}{Jak ty tu przyjœæ?}
{133}{}{Musi ju¿ iœæ.}
{134}{}{Jesteœ tu wiêŸniem?}
{135}{}{Czy szpony œmierci dobrze ciê traktuj¹?}
{136}{}{Czy chcesz opuœciæ to miejsce?}
{137}{}{Powiedz mi Ariel - czemu jesteœ smutna?}
{138}{}{Jak to siê sta³o, ¿e znalaz³aœ siê w tej Krypcie?}
{139}{}{Muszê ju¿ iœæ.}
{140}{}{Nie, mogê odejœæ, kiedy tylko zechcê. Szpony œmierci wyrazi³y siê w tej kwestii bardzo jasno. Z tego, co wiem, nie przebywam tu wbrew ich woli.}
{141}{}{Uch, no dobrze.}
{142}{}{Kuma, Ja iœæ.}
{143}{}{Rozumiem.}
{144}{}{Myœlê suko, ¿e k³amiesz.}
{145}{}{Rozumiem. Jeœli nie masz nic przeciwko, pragnê zadaæ ci jeszcze kilka pytañ.}
{146}{}{Tak. Dostarczaj¹ mi ¿ywnoœæ, wodê, schronienie i ochronê. Czujê siê tu bardzo bezpieczna, a to wiêcej, ni¿ mog³abym oczekiwaæ.}
{147}{}{Dobra. Teraz musi iœæ.}
{148}{}{Dobra. Pytaæ dalej.}
{149}{}{Rozumiem. Chcê zapytaæ ciê o coœ jeszcze.}
{150}{}{Rozumiem. ZejdŸmy wiêc na inny temat.}
{151}{}{Bomba. Mi³oœniczka jaszczurek.}
{152}{}{Myœla³am nad tym, ale muszê powiedzieæ, ¿e nie. Czujê siê tu bezpieczniej ni¿ w jakimkolwiek innym miejscu, w którym ¿y³am do tej pory. Brakuje mi towarzystwa innych ludzi podobnych do mnie, ale byæ mo¿e oni kiedyœ te¿ tu trafi¹ i w ten sposób zaspokoj¹ tê potrzebê.}
{153}{}{Ja iœæ. Macha pa pa.}
{154}{}{Powie wiêcej.}
{155}{}{Œwietnie, mnie nie zale¿y, mo¿esz tu zgniæ.}
{156}{}{Dobrze. Chyba ju¿ pójdê.}
{157}{}{Bardzo mi pomog³aœ, ale muszê ciê jeszcze chwilê pomêczyæ.}
{158}{}{Mój m¹¿ niedawno umar³. Brakuje mi go i nie umiem siê do tego przyzwyczaiæ. To wszystko.}
{159}{}{Pszpszam, jak siê sta³o?}
{160}{}{Uuuups. Musi iœæ, starsza wo³a.}
{161}{}{Przykro mi to s³yszeæ. Jak do tego dosz³o?}
{162}{}{Ciê¿ka sprawa. Do zobaczenia.}
{163}{}{Nieszczêœcia chodz¹ po ludziach, ludzie umieraj¹. Zwykle wtedy, gdy jestem w pobli¿u.}
{164}{}{Ju¿ ci opowiada³am o napadzie. To siê sta³o wtedy.}
{165}{}{Podró¿owaliœmy z mê¿em w towarzystwie karawany w drodze do Republiki Nowej Kalifornii. Chcieliœmy razem z córk¹ Sandy rozpocz¹æ nowe ¿ycie. Niestety pewnej nocy karawana zosta³a zaatakowana przez bandytów. Byli strasznie brutalni. Zabili wszystkich: mê¿czyzn, kobiety i dzieci. Rand, mój m¹¿, zgin¹³, gdy próbowa³ broniæ mnie i Sandy. By³yœmy nastêpne w kolejce, gdy zdarzy³ siê cud.}
{166}{}{Uch... ³a³.}
{167}{}{Fajnie ty, ma³a, obie ma siê dobrze.}
{168}{}{Ja zmykaæ. Pa.}
{169}{}{Och. Co za historia.}
{170}{}{Co za kupa gów... spadam st¹d.}
{171}{}{Dziêki Bogu obie z córk¹ jesteœcie zdrowe.}
{172}{}{Witaj znowu. Jak siê masz?}
{173}{}{}
{174}{}{}
{175}{}{OdejdŸ st¹d, draniu! Nie mam ci nic do powiedzenia.}
{176}{}{OdejdŸ st¹d, dziwko! Nie mam ci nic do powiedzenia.}
{177}{}{Pa.}
{178}{}{.}
{179}{}{. Tak, jestem tu od niedawna.}
{180}{}{Trzyma³am Sandy za sob¹, usi³uj¹c chroniæ j¹ przed potworem, który zastrzeli³ Randa, a on sta³ tak nad cia³em mojego mê¿a i œmia³ siê, celuj¹c w moj¹ g³owê. Nagle wielka ³apa z pazurami wychynê³a z ciemnoœci, z³apa³a go od ty³u i... no, ca³e szczêœcie, ¿e Sandy nie widzia³a, co siê sta³o potem. W ka¿dym razie bandyci zostali wykoszeni przez tê grupê szponów œmierci. Ten, który uratowa³ Sandy i mnie, sta³ niedaleko i mówi³ do mnie. Ci¹gle zapewnia³ mnie, ¿e jestem bezpieczna, i ¿e przykro mu, i¿ nie mogli przybyæ wczeœniej, by nam pomóc. Potem szpony œmierci przyprowadzi³y nas tutaj.}
