{100}{}{Widzisz szpona œmierci, który obserwuje ciê dziwnie inteligentnym wzrokiem.}
{101}{}{Widzisz Valdisa, szpona œmierci.}
{102}{}{Widzisz typowego szpona œmierci. To ogromne stworzenie ma potê¿n¹ budowê cia³a, ostre zêby i d³ugie pazury.}
{103}{}{Pozdrowienia, cz³owieku.}
{104}{}{Jak mogê ci s³u¿yæ?}
{105}{}{Kto ty?}
{106}{}{Co ty robiæ?}
{107}{}{Mózg boli. Wróci póŸniej.}
{108}{}{Witaj, kim jesteœ?}
{109}{}{Na czym polega twoje zajêcie?}
{110}{}{Nie chcê obra¿aæ tutejszych szponów œmierci, ale sprawiasz wra¿enie bardziej... wykszta³conego, ¿e siê tak wyra¿ê.}
{111}{}{Och, tylko têdy przechodzê.}
{112}{}{Mówi¹ na mnie Valdis. A ty jesteœ?}
{113}{}{Ja cz³owiek.}
{114}{}{Oooo! Coœ b³yszczy. Ja iœæ.}
{115}{}{Hej, to ja jestem tutaj od zadawania pytañ.}
{116}{}{Muszê ju¿ iœæ.}
{117}{}{Mi³o mi ciê poznaæ. Jestem}
{118}{}{Kapujê.}
{119}{}{W tej chwili pilnujê tej czêœci Krypty przed wtargniêciem niepowo³anych osób.}
{120}{}{Niep owo ³any chos ub?}
{121}{}{Uch... jasne.}
{122}{}{Ty mówi œmieszny. Ja iœæ.}
{123}{}{Pójdê ju¿ sobie Valdisie.}
{124}{}{Rozumiem.}
{125}{}{Có¿, z pewnoœci¹ znasz siê na swojej robocie.}
{126}{}{Czy masz wystarczaj¹co du¿o rozumu, by decydowaæ, kto jest albo nie jest "niepowo³any"?}
{127}{}{Ale¿ oczywiœcie. Mam te¿ wystarczaj¹co du¿o rozumu, by decydowaæ, kto jest, a kto nie jest dupkiem - i dochodzê do wniosku, ¿e w tej kategorii przebijasz wszystkich! A teraz czemu sobie nie pójdziesz, zanim urz¹dzê sobie pó³godzinn¹ przeja¿d¿kê po twojej twarzy?}
{128}{}{Dobrze.}
{129}{}{Niedobry jaszczur. Teraz muszê ciê zastrzeliæ.}
{130}{}{Hej, przepraszam. Od tej pory bêdê pilnowaæ swojego jêzyka.}
{131}{}{Tak. Doœæ znacznie ró¿nimy siê pod wzglêdem poziomu wykszta³cenia. Staram siê w miarê mo¿liwoœci w wolnym czasie poszerzaæ swoj¹ wiedzê.}
{132}{}{Iguana z ambicjami. Jakie to kurwa s³odkie.}
{133}{}{Dobrze ci idzie.}
{134}{}{To wspania³y cel. Trzymaj tak dalej.}
{135}{}{Hê? Doœæ dobrze zdajê sobie sprawê z tego, ¿e jesteœ cz³owiekiem. Interesuje mnie twoje imiê.}
{136}{}{Ty nie pytaæ imiê, pytaæ "ty jesteœ". Ja jesteœ cz³owiek.}
{137}{}{Ja wie, ja tylko ty testowaæ. Uch... ty zdaæ.}
{138}{}{S³yszy ktoœ wo³a. Ja iœæ.}
{139}{}{Rozumiem. Spróbujmy jeszcze raz. Witaj. Jestem Valdis. Jak masz na imiê?}
{140}{}{Ja}
{141}{}{Bywaj.}
{142}{}{Niepowo³ane osoby. Oznacza "osoby, które nie maj¹ pozwolenia, ¿eby tu byæ".}
{143}{}{Dobra. Ja rozumie.}
{144}{}{Ja znowu mieæ ten bolig³owa. Ja ju¿ iœæ.}
{145}{}{Moj¹ ambicj¹ jest wykazaæ tyle cierpliwoœci, ile zdo³am w œwietle twojego niegrzecznego zachowania. Jeœli nie potrafisz zachowywaæ siê w stosunku do mnie w sposób cywilizowany, proszê - odejdŸ.}
{146}{}{Przepraszam, postaram siê zachowywaæ w bardziej cywilizowany sposób.}
{147}{}{Wal siê.}
{148}{}{Tak.}
{149}{}{Dzieñ dobry.}
{150}{}{¯a³ujê, ¿e muszê ciê zabiæ.}
{151}{}{.}
