{100}{}{Widzisz niskiego, znerwicowanego człowieka.}
{101}{}{Widzisz wiceprezydenta Birda.}
{102}{}{Widzisz niskiego, znerwicowanego człowieka, ubranego w poplamiony jedzeniem garnitur.}
{103}{}{Oto jeden z naszych wspaniałych żołnierzy. Co robisz w gabinecie wiceprezydenta?}
{104}{}{Witaj, żołnierzu. Co robisz w gabinecie wiceprezydenta?}
{105}{}{Wyglądasz znajomo. Czy ja cię już wcześniej spotkałem? Cóż, nieważne. Powiedz mi tylko, co właściwie robisz w gabinecie wiceprezydenta?}
{106}{}{Gdzie?}
{107}{}{Ee, jestem na rutynowym patrolu, ee, Sir.}
{108}{}{Szukam intruzów.}
{109}{}{Jestem tu, żeby jeszcze raz sprawdzić nasze tajne plany.}
{110}{}{Jestem tu by cię zabić.}
{111}{}{Kontynuujcie, żołnierzu. Wy chłopaki wykonujecie fantastyczna robotę. Dzięki wam jesteśmy gotowi na każda ewentualność.}
{112}{}{Hę?}
{113}{}{Ee, tak. Cóż, chyba lepiej dokończę mój patrol. Do widzenia.}
{114}{}{Hmm, powiedz mi, jak się pisze skuwka? Przez 'U', czy nie?}
{115}{}{Hmm, powiedz mi, jak się pisze rzeżączka? Przez 'Ż', czy nie?}
{116}{}{Hmm, powiedz mi, jak się pisze chrząszcz? Przez 'rz', czy nie?}
{117}{}{Hmm, powiedz mi, jak się pisze tchórz? Przez 'Ó', czy nie?}
{118}{}{Hmm, powiedz mi, jak się pisze psychol? Przez 'ch', czy nie?}
{119}{}{Ee, przez.}
{120}{}{Oczywiście, że nie.}
{121}{}{Oczywiście, że tak, oczywiście. Każdy lojalny obywatel Stanów Zjednoczonych tak by zrobił.}
{122}{}{Dlaczego?}
{123}{}{Mam robotę do wykonania. Do widzenia.}
{124}{}{Kontynuujcie, żołnierzu. Nasza przyszłość to lepsze jutro.}
{125}{}{Co chcesz przez to powiedzieć?}
{126}{}{Nie dla ciebie. Właśnie eksterminuję wszystkie gnidy z Enklawy - ty jesteś następny na liście.}
{127}{}{Uch, pewnie. Jak chcesz. Na razie.}
{128}{}{Musimy współpracować, ponieważ jeśli nam się nie powiedzie, narażamy się na niepowodzenie.}
{129}{}{Może wasza porażka nie byłaby tak straszna.}
{130}{}{Cóż, lepiej pójdę.}
{131}{}{Nie ujdzie ci to na sucho.}
{132}{}{Zobaczymy.}
{133}{}{Dlaczego nie?}
{134}{}{Jedno słowo podsumowuje odpowiedzialność spoczywającą na każdym wiceprezydencie - to słowo to 'być zawsze przygotowanym'.}
{135}{}{Na co musi pan być przygotowany?}
{136}{}{Czy to aby nie trzy słowa? 'Przygotowanie' to jedno słowo. O to chodziło, tak?}
{137}{}{Może to jest najlepsze. Starać się być zwięzłym. Bo przecież rozwlekłość prowadzi do niejasnych, niewymawialnych rzeczy.}
{138}{}{Wyobrażam sobie.}
{139}{}{Muszę już iść. Do widzenia.}
{140}{}{Chodziło mi o to, że nie chcemy się cofać. My chcemy iść naprzód.}
{141}{}{A czy to nie jest przypadkiem jedyna droga?}
{142}{}{No cóż, nigdy nie można być nazbyt ostrożnym, w końcu nigdy nie wiadomo jak bardzo nieodpowiedzialny człowiek na wysokim stanowisku może zmienić bieg historii.}
{143}{}{Tak, właśnie widzę.}
{144}{}{A jaki wpływ na historię chce mieć pan?}
{145}{}{Tak, lubię ten kierunek. W przeszłości dokonywałem dobrych wyborów. W przyszłości również. A więc, jak wszystko na to wskazuje, idźmy w tym kierunku.}
{146}{}{Tak.}
{147}{}{Wierzę, że jesteśmy na bezpowrotnej drodze do wolności i demokracji - ale to może się zmienić.}
{148}{}{Zanieczyszczonemu środowisku Pustkowi przydałaby się dla odmiany odrobina wolności.}
{149}{}{Nie wytrzymam tego dłużej - pan po prostu musi zostać zlikwidowany.}
{150}{}{Niech pan nie będzie głupi. To nie zanieczyszczenia krzywdzą środowisko naturalne. To nieczystości w powietrzu i w wodzie, które to powodują.}
{151}{}{Naprawdę muszę już iść.}
{152}{}{Nie ferowałbyś tak wyrokami, gdybyś sam był na kontynencie.}
{153}{}{Właśnie o to chodzi. Enklawa to sztuczna wyspa, otoczona wodą.}
{154}{}{Myśli pan, że to, co się stanie, pana nie dotyczy? Żyje pan na tej samej planecie, co my wszyscy.}
{155}{}{Czy czegoś nie brakuje w twojej wypowiedzi? Jak na przykład wniosku.}
{156}{}{Jestem wiceprezydent Daniel Bird. Cholernie miło mi cię poznać.}
{157}{}{Jesteś tylko kolejną częścią wielkiego problemu, jaki stanowi ta wyspa.}
{158}{}{Jesteś szurnięty.}
{159}{}{Nie jestem częścią problemu, jestem republikaninem.}
{160}{}{Czyli jak już mówiłem - problem.}
{161}{}{Ach, rozumiem. No cóż, jak prawdopodobnie wiesz, już od dłuższego czasu myślimy, że czas najwyższy, aby rodzaj ludzki wkroczył w układ słoneczny.}
{162}{}{A czy my przypadkiem już nie... Ee, *gdzie* wkroczyć?}
{163}{}{A jak niby mielibyśmy tego dokonać?}
{164}{}{Myślę, że Mars byłby całkiem niezły, ponieważ ma zbliżona orbitę... Mars znajduje się w mniej więcej tej samej odległości od Słońca, co jest dla nas bardzo ważne. Widzieliśmy zdjęcia, na których uwieczniono kanały i, jak sądzimy, wodę. Jeśli jest tam woda - to jest też tlen. Jeśli zaś jest tlen - to możemy tam oddychać.}
{165}{}{No to mnie zaskoczyłeś aż tak *pełną* odpowiedzią.}
{166}{}{Postradał pan zmysły.}
{167}{}{Utrata zmysłów to marnotrastwo. Ale niektórzy nie mają ich od urodzenia.}
{168}{}{*Zazwyczaj* to marnotrastwo. Ale twój przypadek to wyjątek.}
{169}{}{Co przed chwilą powiedziałeś?}
{170}{}{Dość - marnuję na ciebie już wystarczająco dużo czasu. Żegnam.}
{171}{}{Dla NASA podbój kosmosu ciągle pozostaje priorytetem.}
{172}{}{Rozumiem. A w którą stronę poszlibyśmy dalej?}
{173}{}{To nieprawda, republikanie rozumieją wagę przywiązania pomiędzy matką i dzieckiem. To jest klucz do rozwiązania wszystkich naszych problemów - musimy powrócić do wartości rodzinnych.}
{174}{}{To co zamierzasz - ty i Enklawa - nie ma nic wspólnego z wartościami rodzinnymi.}
{175}{}{Obstaję przy wszystkich złych wypowiedziach, które poczyniłem.}
{176}{}{Nie rozumiesz, że chcecie doprowadzić do kolejnej Zagłady?}
{177}{}{Jesteś szalony. Zdajesz sobie z tego sprawę, nieprawdaż?}
{178}{}{Zagłada jest wstrętnym odcinkiem historii naszego narodu. To znaczy w historii tego wieku. Ale my wszyscy żyliśmy w tym wieku. Ja nie żyłem w tym wieku.}
{179}{}{Jesteś szurniętym popaprańcem.}
{180}{}{Ktoś musi cię usunąć sprzed moich oczu. Zaczynaj się modlić, Bird.}
{181}{}{Muszę się stąd wyrwać.}
{182}{}{Z-I-E-M-I-A-K}
{183}{}{Z-I-E-M-N-I-A-K}
{184}{}{P-O-M-I-D-U-R}
{185}{}{P-O-M-I-D-O-R}
{186}{}{Gdzie się podziały moje dwa galony lodów truskawkowych?}
{187}{}{Caine, to mój statek. Mój, słyszysz?}
{188}{}{Wszyscy jesteście przeciwko mnie, prawda? Prawda?}
{189}{}{Tak szybki, jak tylko można, nie złapią mnie.}
{190}{}{Śliczne, śliczne.}
{191}{}{Uuu!!! Sreberko!}
{192}{}{Nie mamusiu, ja tego nie zrobiłem. Nie bij mnie!}
{193}{}{Mamusiu! Gdzie jesteś?}
{194}{}{Nie chcę być pacjentem.}
{195}{}{Nie, tylko nie igły, wszystko tylko nie igły.}
{196}{}{Nie, nie, ych-ych, nie. Nieeeeeee!}
