{100}{}{Widzisz niskiego mê¿czyznê z kruczoczarnymi w³osami i mi³ym uœmiechem.}
{101}{}{Widzisz Ascortiego, burmistrza Redding.}
{102}{}{Widzisz dobrze ubranego mê¿czyznê wygl¹daj¹cego doœæ zgrabnie.}
{103}{}{Rusz siê, koleœ.}
{104}{}{Jeœli chcesz wypróbowaæ swoje szczêœcie, to proszê bardzo.}
{105}{}{Graj albo wynocha!}
{106}{}{Lepiej nie narób tu ba³aganu...}
{107}{}{Spróbuj zabawy przy sto³ach do gry. Mówiê ci to, bo wygl¹dasz jak ktoœ, kto mieszka w dziczy.}
{108}{}{Spróbuj zabawy przy maszynach do gry, jesteœ z dziczy, wiêc ci to mówiê. Jest w nich mnóstwo dobrej magii.}
{109}{}{Tylko nie przesadzaj z ognist¹ wod¹...}
{110}{}{Witaj w œlicznym miasteczku - Redding... no i w moim kasynie. Ka¿dy jest asem u Ascortiego. To w³aœnie ja, Ascorti, w³aœciciel i burmistrz tego œlicznego miasta.}
{111}{}{Co burmistrz Ascorti mo¿e dla ciebie zrobiæ?}
{112}{}{Czy w Redding mo¿na dostaæ jak¹œ robotê?}
{113}{}{Co tam ostatnio s³ychaæ w mieœcie?}
{114}{}{Czy s³ysza³eœ o czymœ, co nazywa siê Generator Ekosystemu Cudownej Krainy?}
{115}{}{Co tu robisz?}
{116}{}{Tak tylko siê rozgl¹dam, burmistrzu. Do zobaczenia.}
{117}{}{Prowadzê to kasyno oraz ogólnie zarz¹dzam ca³ym miastem. Monitorujê te¿ na przyk³ad takie sprawy jak akty w³asnoœci.}
{118}{}{Akty w³asnoœci? Czego na przyk³ad?}
{119}{}{Aha. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{120}{}{Przyk³adowo ten od wielkiej kopalni Wanamingo, który chcê od ciebie odkupiæ. Czy mo¿esz ju¿ mi go odsprzedaæ?}
{121}{}{Chyba tak. Ile mia³eœ mi daæ za niego?}
{122}{}{Mo¿e... Ale pozwól, ¿e najpierw spytam ciê o coœ.}
{123}{}{Jeszcze muszê to przemyœleæ. Do widzenia, burmistrzu.}
{124}{}{W zasadzie to tylko jeden akt. Ten, który ci sprzeda³em. No wiesz, od kopalni Wanamingo?}
{125}{}{A, ten... Teraz sobie przypominam. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{126}{}{Jasne, tak tylko siê zastanawiam, czy masz mo¿e coœ jeszcze do sprzedania. Muszê wracaæ do pracy przy jej czyszczeniu. Do widzenia.}
{127}{}{Tylko kopalni Wanamingo, który odkupi³em od ciebie. Pamiêtasz?}
{128}{}{Jasne, ¿e tak. Ale pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{129}{}{Ale¿ tak. Tak tylko sprawdzam. Do widzenia, burmistrzu Ascorti.}
{130}{}{Ró¿nych posiad³oœci. Np. teraz mam do sprzedania naprawdê super sprawê!}
{131}{}{To znaczy co?}
{132}{}{Za³o¿ê siê, ¿e tak, ale pozwól, ¿e spytam ciê najpierw o coœ innego, burmistrzu.}
{133}{}{Hmm, myœlê, ¿e najpierw siê trochê rozejrzê po mieœcie. Do widzenia.}
{134}{}{Akt w³asnoœci wielkiej kopalni Wanamingo znajduj¹cej siê tu¿ za miastem. Mogê ci j¹ sprzedaæ za œmieszn¹ sumkê $1000. Oferta specjalna! Po prostu masz fart, uda³o ci siê trafiæ na dobry dzieñ.}
{135}{}{Brzmi interesuj¹co. Powiedz mi wiêcej na ten temat.}
{136}{}{Gdzie jest haczyk, burmistrzu?}
{137}{}{Chyba nie chcê jej teraz kupowaæ, burmistrzu. Pozwól, ¿e spytam ciê o coœ innego.}
{138}{}{No, s¹ w niej takie cholerne zwierz¹tka i trzeba je pozabijaæ zanim bêdzie mo¿na w niej pracowaæ. Jeœli kupisz akt, pozabijasz wszystkie - to chêtnie j¹ od ciebie odkupiê ze sporym zyskiem.}
{139}{}{Z zyskiem? Jak du¿ym?}
{140}{}{Skoro jest tak wartoœciowa, to czemu sam jej nie oczyœcisz?}
{141}{}{Zwierz¹tka? Jakie?}
{142}{}{Nie ma haczyka. Tylko najpierw musisz wyeksmitowaæ paru niechcianych lokatorów mieszkaj¹cych w niej. Dla ciebie to raczej nic trudnego. Mogê powiedzieæ ci wiêcej, jeœli chcesz...}
{143}{}{Okej, biorê tê sprawê. Mów...}
{144}{}{Chyba nie chcê siê mieszaæ w takie interesy, burmistrzu. Ale pozwól, ¿e spytam ciê o coœ innego.}
{145}{}{Aha. Tak wiêc chyba zostawiê to komuœ innemu. Do widzenia, burmistrzu.}
{146}{}{Nawet podwójnym! To zapewne rozs¹dna zap³ata za twój trud. Niestety, na wiêcej mnie nie staæ. Bêdê musia³ sporo zainwestowaæ w tê kopalniê, zanim zacznie ona przynosiæ zyski.}
{147}{}{Brzmi nieŸle. To ile p³acê?}
{148}{}{Chyba jednak dam sobie spokój. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{149}{}{$1000 za akt w³asnoœci wielkiej kopalni Wanamingo. Bierzesz?}
{150}{}{Tak, biorê go.}
{151}{}{Chêtnie, ale nie mam przy sobie tyle pieniêdzy. Pozwól, ¿e spytam ciê o coœ innego.}
{152}{}{Nie bardzo. Pozwól, ¿e spytam ciê o coœ innego.}
{153}{}{Mo¿e innym razem, burmistrzu. Do widzenia.}
{154}{}{Tylko zapiszê sobie, ¿e kopalnia Wanamingo jest twoj¹ w³asnoœci¹. Daj mi znaæ, jak ju¿ j¹ oczyœcisz, to j¹ od ciebie odkupiê.}
{155}{}{Tak zrobiê. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{156}{}{Dobra. Nied³ugo wrócê, burmistrzu.}
{157}{}{Nie mogê. Nie jestem goœciem szukaj¹cym niebezpieczeñstwa na ka¿dym kroku. Znam swoje mocne strony i walka nie jest jedn¹ z nich. Ale ty, to co innego, wygl¹dasz na tward¹ osobê. Tak w ogóle, to chyba w³aœnie takimi rzeczami siê przecie¿ zajmujesz.}
{158}{}{Byæ mo¿e. Z jakim zyskiem odkupisz ode mnie akt w³asnoœci, gdy oczyszczê kopalniê?}
{159}{}{Mo¿e tak, a mo¿e nie. Pomyœlê nad tym. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{160}{}{Nie bardzo mam teraz czas na takie rzeczy. Przepraszam, panie burmistrzu. Do widzenia.}
{161}{}{To jak? Uda³o ci siê ju¿ oczyœciæ kopalniê?}
{162}{}{Jasne!}
{163}{}{Jeszcze nie, ale zrobiê to. Ale w miedzyczasie pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{164}{}{Pracujê nad tym. Do widzenia, burmistrzu Ascorti.}
{165}{}{Wiesz co, chyba jeszcze nie uda³o ci siê za³atwiæ wszystkich Wanamingos. Lepiej to sprawdŸ. Nie odkupiê kopalni, dopóki nie pozabijasz wszystkich.}
{166}{}{Aha. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{167}{}{W takim razie muszê tam wróciæ i to sprawdziæ.}
{168}{}{Oczyszczenie kopalni to œwietna robota! Ale jest problem.}
{169}{}{Problem? Jaki?}
{170}{}{Uda³o ci siê oczyœciæ ca³¹ kopalniê! Dziêki. Czy odsprzedasz mi teraz akt? Dam ci za niego $2500.}
{171}{}{Nie s¹dzê, chyba go jeszcze potrzymam. Do widzenia, burmistrzu.}
{172}{}{Jasne. Cieszê siê, ¿e siê go pozbêdê, burmistrzu Ascorti.}
{173}{}{Nazywamy je Wanamingos. To jakieœ dziwne stworzenia z wielkimi zêbami i z przyssawkami jak u oœmiornic. Nie s¹ zbyt inteligentne, ale s¹ wredne z bliska.}
{174}{}{Aha. I ja mam siê ich pozbyæ?}
{175}{}{No pewnie. Wiedzia³em, ¿e nie myœlisz tak a¿ tak wolno.}
{176}{}{Taa. To ile zarobiê na tym $1000?}
{177}{}{Wiedzia³em, ¿e ktoœ inny siê tam wprowadzi zamiast Wanamingos. Zrobi³ to wredny koleœ zwany ¯aba Morton. Z tego, co wiem, razem ze swoim gangiem.}
{178}{}{Dlaczego mówi¹ na niego ¯aba?}
{179}{}{I gdzie tu mój problem?}
{180}{}{I co mam z tym zrobiæ?}
{181}{}{To chyba dlatego, ¿e ¿abija ludzi. Wredny z niego koleœ, za którym nikt nie zatêskni... a ty bêdziesz bohaterem! Chcesz byæ bohaterem, nie?}
{182}{}{Mo¿e, ale nadal nie widzê tu mojego problemu.}
{183}{}{Tak, jasne. Co mogê z tym zrobiæ?}
{184}{}{Chyba mam jeszcze trochê do poczyszczenia. Wrócê, gdy nakopiê jeszcze parê ty³ków, burmistrzu.}
{185}{}{No, dopóki kopalnia nie bêdzie czysta, nie mogê wys³aæ górników do pracy w niej. Wiêc jeœli chcesz mi j¹ sprzedaæ, to masz problem.}
{186}{}{A dlaczego nazywaj¹ go ¯aba Morton?}
{187}{}{Œwietnie. To co mam z tym zrobiæ?}
{188}{}{W takim razie idê siê nim zaj¹æ. Do widzenia, burmistrzu.}
{189}{}{Myœlê, ¿e nale¿a³oby pójœæ z powrotem do kopalni Wanamingo i za³atwiæ ¯abê i jego gang. Gdy to zrobisz, mo¿esz do mnie wróciæ, a ja z chêci¹ odkupiê od ciebie kopalniê.}
{190}{}{Nic nie jest ³atwe... Do zobaczenia, muszê siê czymœ zaj¹æ...}
{191}{}{Czy chcesz mi ju¿ odsprzedaæ akt w³asnoœci kopalni Wanamingo?}
{192}{}{Jasne, burmistrzu. Ile on mia³ kosztowaæ?}
{193}{}{Jeszcze nie, burmistrzu. Do widzenia.}
{194}{}{S³ysza³em, ¿e pomagasz szeryfowi. To dobrze. Nie staæ mnie ju¿ na to, by ta sp³ukana Rooney mieszka³a sobie nadal w tym luksusowym domu.}
{195}{}{Masz na myœli ten malutki, przewiewny barak, za który liczysz sobie "nieco" za du¿o?}
{196}{}{No pewnie. Ile jest ci ona dlu¿na?}
{197}{}{Aha, mogê siê tym zainteresowaæ. Ale pozwól, ¿e spytam ciê o coœ innego.}
{198}{}{Tia. A kto ty niby jesteœ?}
{199}{}{Wolê nazywaæ go przytulnym z przyjemn¹ letni¹ wentylacj¹. Równie¿ i cena za niego jest ca³kiem rozs¹dna.}
{200}{}{Tak, na pewno. Ile jest ci winna za czynsz?}
{201}{}{Hmm, lepiej ju¿ sobie pójdê, burmistrzu. Do widzenia.}
{202}{}{Zobaczmy... Pani Rooney jest mi winna... tak, no jest, $120. Tak. $120.}
{203}{}{To wszystko? Mam tyle przy sobie. Masz...}
{204}{}{To nie tak du¿o. Pozwól, ¿e spytam ciê o coœ innego.}
{205}{}{Zobaczê, co mogê zrobiæ, by zmusiæ j¹ do zap³acenia. Do widzenia.}
{206}{}{Dobrze... Teraz jest na bie¿¹co. Dziêki za uregulowanie tego d³ugu.}
{207}{}{Nie ma sprawy. Pozwól, ¿e spytam ciê o coœ innego.}
{208}{}{Po prostu jedni ludzie s¹ bardziej hojni ni¿ inni. Do widzenia, burmistrzu.}
{209}{}{Dziêki, ¿e uda³o ci siê opró¿niæ moj¹ posiad³oœæ, szeryfie. Teraz bêdê móg³ j¹ wynaj¹æ komuœ, kto bêdzie móg³ za ni¹ zap³aciæ.}
{210}{}{Nie czujê siê zbyt dobrze po tym...}
{211}{}{Brzmi sensownie. }
{212}{}{Czemu nie? Mo¿esz siê spokojnie czuæ dobrze. Wywalaj¹c wdowê Rooney, pozwalasz mi na dalsze p³acenie pracownikom. Jeœli nie zap³aci³bym im, to ich rodziny musia³yby g³odowaæ. To dopiero nie jest w porz¹dku, nie?}
{213}{}{No tak. Moja wizja tego by³a nieco inna. Ale nadal nie czujê siê zbyt dobrze.}
{214}{}{Nie wygl¹dasz na takiego biedaka. W koñcu zarabiasz kupê kasy na swoim kasynie.}
{215}{}{Potrzeba silnej osobowoœci, by zrobiæ co trzeba, nawet jeœli po tym ktoœ nie bêdzie siê czu³ zbyt dobrze. Uda³o ci siê zrobiæ coœ bardzo trudnego, i to do tego dobrze. Masz piwo na koszt firmy!}
{216}{}{Dziêki, burmistrzu. To mi³o z twojej strony.}
{217}{}{Nie chcê z tob¹ piæ, ani teraz, ani kiedykolwiek. Do widzenia.}
{218}{}{Nie ma problemu. Dobrze jest czasami zmoczyæ gwizdek lokalnej policji.}
{219}{}{Jeszcze raz dziêki, burmistrzu. Pozwól, ¿e spytam ciê o coœ innego.}
{220}{}{Dziêki, burmistrzu. Do zobaczenia.}
{221}{}{Dzisiaj mo¿e i tak, ale nie zawsze ma takie szczêœcie. Muszê utrzymywaæ wysokie zyski. Jestem to winny moim pracownikom - no i trochê te¿ sobie, oczywiœcie.}
{222}{}{Brzmi sprawiedliwie.}
{223}{}{Upad³eœ tak nisko, jak brzuch gekona! Mam tego doœæ. Do widzenia.}
{224}{}{Chcê ci tylko jeszcze raz podziêkowaæ, ¿e zrobi³eœ to dla pani Rooney. W koñcu nie chcia³bym jej wyrzucaæ z domu.}
{225}{}{Ale zrobi³byœ to. Pozwól, ¿e spytam ciê o coœ innego.}
{226}{}{Mo¿na by³o przewidzieæ, ¿e tak powiesz. Do widzenia, burmistrzu.}
{227}{}{Nie no, tym razem przesadzasz. Pani Rooney nie zagra¿a³a nikomu! Po co by³o j¹ zabijaæ?!?}
{228}{}{Sama siê o to prosi³a.}
{229}{}{To by³ wypadek.}
{230}{}{Pros³a siê? Przecie¿ ona by³a tylko ma³¹, bezbronn¹ staruszk¹. Coœ ci odbi³o? Wynoœ siê!}
{231}{}{Mówisz do mnie?}
{232}{}{I tak ju¿ wychodzê z tego sza³asu. Do widzenia.}
{233}{}{Wypadek? Nadal nie mog¹ znaleŸæ wszystkich czêœci jej cia³a. Lepiej, ¿eby takie wypadki wiêcej siê nie zdarza³y... Dzia³aj¹ Ÿle na biznes.}
{234}{}{Rozumiem. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{235}{}{Nastêpnym razem bêdê uwa¿aæ.}
{236}{}{Tak, mówiê do ciebie. Widzisz tu jeszcze kogoœ, do kogo móg³bym mówiæ? Spierdalaj z mojego baru.}
{237}{}{Czy *ty* mówisz do *mnie*?}
{238}{}{Ju¿ idê. Ju¿ idê...}
{239}{}{Co? Niedos³yszysz, czy masz coœ z g³ow¹? Mówiê do ciebie! Wy-noœ-siê!}
{240}{}{Musisz wiêc mówiæ do mnie, bo nie widzê w okolicy nikogo innego.}
{241}{}{W porz¹dku. Ju¿ wychodzê. Nie denerwuj siê, bo dostaniesz wylewu! Do widzenia.}
{242}{}{Czy wszyscy w twoim plemieniu s¹ tak g³upi? O tak. Chcesz tañczyæ? Dobra, zatañczymy. Stra¿nicy!}
{243}{}{Mówisz do mnie... i nie podobaj¹ mi siê twoje slowa.}
{244}{}{Hej, spokojnie... Ju¿ sobie idê.}
{245}{}{S³ysza³em, ¿e pracujesz dla Earla Mariona jako zastêpca szeryfa, dopóki nie wyzdrowieje. Musisz wiêc mieæ rêce pe³ne roboty. Innej roboty dla ciebie raczej na razie nie znajdzie siê w mieœcie.}
{246}{}{Aha. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu Ascorti.}
{247}{}{Opowiedz mi o w³aœcicielach kopalni.}
{248}{}{I tak dziêkujê, burmistrzu. Do widzenia.}
{249}{}{S³ysza³em, ¿e robisz kawa³ dobrej roboty, pomagaj¹c szeryfowi Marionowi. W mieœcie jest doœæ cicho dziêki tobie. Nie wiem, co jeszcze móg³bym zleciæ tak utalentowanej osobie.}
{250}{}{Dziêki, burmistrzu. Wiele dla mnie znacz¹ takie s³owa, gdy wychodz¹ od takiej osoby. Pozwól, ¿e spytam ciê o coœ innego.}
{251}{}{Opowiedz mi o w³aœcicielach kopalni.}
{252}{}{I tak dziêkujê, burmistrzu. Do widzenia.}
{253}{}{O ile siê nie mylê, szeryf Earl Marion szuka zastêpcy, dopóki nie zagoi siê jego chora noga. Mo¿esz spróbowaæ z nim pogadaæ. Jego biuro jest parê metrów na po³udnie st¹d, po drugiej stronie ulicy.}
{254}{}{Dziêki za poradê. Ale zanim tam pójdê, pozwól, ¿e spytam ciê o coœ innego.}
{255}{}{Opowiedz mi o w³aœcicielach kopalni.}
{256}{}{Mo¿e siê tym zainteresujê. Dziêki.}
{257}{}{No, jest szeryf, no i s¹ te¿ w³aœciciele kopalni, którzy szukaj¹ jakiejœ czêœci do jednej z ich maszyn.}
{258}{}{Co z tym szeryfem?}
{259}{}{Co z tymi w³aœcicielami kopalni?}
{260}{}{Interesuj¹ce. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{261}{}{Mo¿e siê trochê porozgl¹dam. Dziêkujê i do widzenia.}
{262}{}{No tak. S³ysza³em, ¿e ju¿ uda³o ci siê zdobyæ ten chip dla jednego z nich.}
{263}{}{A co w takim razie z szeryfem?}
{264}{}{No tak, to moja robota. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{265}{}{Aha, zdawa³o mi siê, ¿e mo¿e chodzi o coœ nowego. Do widzenia.}
{266}{}{Nie bardzo wiem, o co chodzi. Musisz pogadaæ albo z Niebezpiecznym Danem McGrew w kopalni Morningstar, albo z Marge LeBarge w kopalni Kokoweef. Obie kopalnie s¹ na pó³noc od œrodmieœcia, Po drugiej stronie cmentarza.}
{267}{}{Dziêki. A co z szeryfem?}
{268}{}{Dziêki. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{269}{}{W takim razie pójdê tam i pogadam z nimi. Dziêki, burmistrzu. Do widzenia.}
{270}{}{Ostatnio nasze transporty z³ota zaczê³y trochê siê zmniejszaæ, poniewa¿ górnicy spêdzaj¹ zbyt du¿o czasu lataj¹c na Jecie.}
{271}{}{Prawie wszyscy górnicy lataj¹ na Jecie zamiast wydobywaæ z³oto... tak wiêc nasze ceny id¹ w górê, a import spada. To bardzo niedobrze dla biznesu.}
{272}{}{Ka¿dy zbyt wysoko lata na Jecie, by móc dobrze pracowaæ. Nie wyrabiamy nawet jednej dziesi¹tej normy i musieliœmy przez to bardzo podnieœæ cenê z³ota. Tak nie mo¿e byæ!}
{273}{}{Wygl¹da na to, ¿e ka¿dy trafi³ na jak¹œ trefn¹ dzia³kê jetu. Wszyscy Jetowi d¿okeje przechodz¹ jakiœ masowy detoks. Zapewne coœ by³o z nimi nie tak. Nie bardzo wiem, co siê sta³o, ale jestem pewien, ¿e wyjdzie im to na dobre.}
{274}{}{Wszystko ju¿ prawie wróci³o do normy. Ka¿dy, kto rozchorowa³ siê po Jecie, przeszed³ ju¿ najgorsze i raczej wiêcej ju¿ go nie weŸmie. Nasza produkcja i transport wróci³y te¿ do normy. Wygl¹da na to, ¿e najgorsze mamy za sob¹.}
{275}{}{Hmm. Interesuj¹ce. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu Ascorti.}
{276}{}{Aha. Dziêki za informacje, burmistrzu. Do widzenia.}
{277}{}{Generator Ekosystemu Cudownej Krainy? Chyba w³aœnie z tego zrobili Kryptopolis. Wszystkie krypty mia³y mieæ coœ takiego, ale teraz nie ma ich ju¿ nigdzie w okolicy.}
{278}{}{Szkoda. Pozwól, ¿e spytam ciê o coœ innego, burmistrzu.}
{279}{}{W takim razie muszê nadal szukaæ. Dziêki, burmistrzu Ascorti.}
