{100}{}{Widzisz wysokiego, chudego mężczyznę patrzącego na ciebie taksującym wzrokiem.}
{101}{}{Widzisz Josha Laurance'a, właściciela Saloonu Ostatnie Tchnienie.}
{102}{}{Widzisz mężczyznę mierzącego cię wzrokiem tak, jakby zdejmował twoje wymiary.}
{103}{}{Wykolegowuj się stąd.}
{104}{}{Co ty tu u licha robisz, idioto?}
{105}{}{To nie jest miejsce dla ciebie.}
{106}{}{No już. Zmiataj, idioto!}
{107}{}{Wynoś się, zanim zabrudzisz mi podłogę.}
{108}{}{Dzień dobry. Josh Laurance. Jestem właścicielem tego miejsca.}
{109}{}{Co mogę dla ciebie zrobić?}
{110}{}{Co to dokładnie za miejsce?}
{111}{}{Poproszę drinka.}
{112}{}{Poproszę kolejkę dla wszystkich.}
{113}{}{Poproszę kolejkę dla moich przyjaciół.}
{114}{}{Co się ostatnio dzieje w mieście?}
{115}{}{Na razie nic. Tylko tędy przechodzę. Do widzenia.}
{116}{}{Nie będę nic podawać temu czemuś.}
{117}{}{Zabieraj stąd swojego *przyjaciela*.}
{118}{}{To nie jest żaden cholerny gabinet dziwolągów. Wynoś się stąd.}
{119}{}{To nie wejdzie do mojego lokalu.}
{120}{}{Nie podajemy nic osobom tego rodzaju. Wynocha.}
{121}{}{To jest Saloon i Zakład Pogrzebowy "Ostatnie Tchnienie". Pełna obsługa. Z Butelką do Grobu, oto nasze motto.}
{122}{}{To nieco dziwaczne połączenie, Josh.}
{123}{}{Lukrecja Borgia byłaby z ciebie dumna Josh.}
{124}{}{Co muszę zrobić, aby nabyć trumnę?}
{125}{}{Jak mogę zamówić usługi pogrzebowe?}
{126}{}{Z pewnością będę się trzymać z dala od twojego ginu.}
{127}{}{Oczywiście. Należy się $5.}
{128}{}{Oto pieniądze.}
{129}{}{Chyba jednak na razie nie chcę piwa. Pozwól jednak, że zadam ci kilka pytań.}
{130}{}{Jakie to hojne z twojej strony. $50 do kasy przybywa, by każdy mógł napić się piwa. Hej, nie wiedziałem, że jestem poetą.}
{131}{}{Auć. Uważaj Josh, kalambury zabijają. To przyjacielska rada, a tu są pieniądze.}
{132}{}{Hmmm, twój kalambur odebrał temu pomysłowi cały smak. Pozwół, że zamiast tego o coś cię zapytam.}
{133}{}{Czyż nie jesteś tym typem przyjaciela, którego każdy potrzebuje? To będzie }
{134}{}{Uczciwa cena. Proszę.}
{135}{}{Może jednak lepiej będę ich trzymać w trzeźwości. Pozwól, że zamiast tego o coś cię zapytam.}
{136}{}{Wszystko wygląda dobrze, gdy trzymasz interes w garści. Tak trzymać. W każdym razie pozwól mi zająć się czymś innym.}
{137}{}{Wiesz, to nie jest żadne duże halo. Zwykle mój interes kręci się dosyć wolno. Można by rzec, że jest cichy jak grób. Chociaż ostatnio to nie znaczy już tyle, co kiedyś.}
{138}{}{Hę? Co masz na myśli?}
{139}{}{Dokładnie. Ale nie mógłbym związać końca z końcem, gdybym ograniczał się do grzebania ludzi - można by rzec, że interes zdechł. Można mu było postawić nagrobek.}
{140}{}{Ach tak. Prawie boję się zadać następne pytanie. Ale jednak spróbuję.}
{141}{}{Uch, czy widok tych wszystkich sztywniaków nie obrzydza ludziom jedzenia?}
{142}{}{Chyba nie wytrzymam następnej gry słów. Żegnam.}
{143}{}{Obrzydzałby, gdyby to były prawdziwe trupy. Ale nie są. W każdym razie żaden z tych. Poza tym górnicy chyba to lubią. Dzięki temu dostrzegają, jak wiele mają szczęścia, że żyją.}
{144}{}{Myślę, że to jest przerażające. Jesteś bardzo pokręconym indywiduum.}
{145}{}{Rozumiem. No więc, tego, mam inne pytanie.}
{146}{}{Domyślam się, że niektórzy mogą tak to odbierać. Ale nie ja. Po prostu mam od tego mdłości. Do widzenia.}
{147}{}{Mówisz, że *ja* jestem przerażający? Przecież podobno wasze plemiona jedzą swoich własnych zmarłych.}
{148}{}{Jakże inaczej moglibyśmy wchłonąć ich dusze?}
{149}{}{Odczep się. Zawsze ich przedtem gotujemy. Przecież nie jesteśmy dzikusami.}
{150}{}{To śmieszne. Kto ci to powiedział?}
{151}{}{Nie wiem dokładnie. Ale to przecież oczywiste. Po cóż innego mielibyście opiłowywać swoje zęby, by je naostrzyć, hę? No powiedz!}
{152}{}{Nie piłuję moich zębów, żeby je... och, nieważne. Pozwól, że zapytam o coś innego.}
{153}{}{Dziękuję uprzejmie. Coś jeszcze?}
{154}{}{Właściwie to tak.}
{155}{}{Nie, na razie wystarczy. Dzięki Josh.}
{156}{}{Co przez to rozumiesz?}
{157}{}{Chcę tylko powiedzieć, że to raczej, no, *niezwykła* kombinacja.}
{158}{}{Nic, nic, zupełnie nic. Pozwól Josh, że zapytam o coś jeszcze.}
{159}{}{Chcę tylko powiedzieć, że wolę pić w miejscach, które są nieco mniej sztywne. To znaczy, bardziej na luzie, oczywiście. Do widzenia.}
{160}{}{Spędziłem sporo czasu na ponownym zakopywaniu ludzi leżących na cmentarzu obok. Ktoś - albo coś - ciągle ich wykopuje. Nie wiem czemu. To znaczy, oni nie mają na sobie nic cennego.}
{161}{}{Ktoś otwiera groby?}
{162}{}{Skąd wiesz, że nie mają na sobie nic cennego?}
{163}{}{To pewnie tylko szczury. Pozwól, że zapytam o coś innego.}
{164}{}{No, nie wiem na pewno, ale... ekhm, khm. Tylko zgaduję. Tak, właśnie. Wiesz co, napij się piwa na koszt firmy.}
{165}{}{Nie wiem, co mi imputujesz, ale nie podoba mi się to.}
{166}{}{Dzięki za piwo. Co masz na myśli mówiąc, że coś ich wykopuje?}
{167}{}{A więc powiedz mi, co masz na myśli mówiąc, że coś ich wykopuje.}
{168}{}{No, nigdy nic nie widziałem, ale tak mniej więcej raz na tydzień jeden z grobów zostaje rozgrzebany i na wpół rozkopany. Nie wiem, co też może to robić.}
{169}{}{Dziwne.}
{170}{}{Irytujące raczej. Teraz górnicy mówią mi, że raczej już woleliby spędzić swe ostatnie chwile tutaj, niż zostać zakopanym tylko po to, żeby ich ktoś potem wyciągał jak przejrzałą cebulę. Kurcze, tych milszych mógłbym trzymać tutaj, ale nie całą resztę. Zupełnie nie wiem, co z tym zrobić.}
{171}{}{Jaka miła historia. Na pewno obudzę się z krzykiem, gdy mi się kiedyś przyśni. Pozwól, że zapytam o coś innego.}
{172}{}{W rzeczy samej, to tajemnicza sprawa. No, jeszcze się zobaczymy. Na razie.}
{173}{}{No, skoro ich najpierw gotuje... zaczekaj chwilę. Przecież to wciąż kanibalizm! Jesteś małym, wrednym popaprańcem, nawet jak na dzikusa.}
{174}{}{Spokojnie Josh. Tylko żartuję. He he. Wiesz, gotujemy tylko niektóre części.}
{175}{}{Części, co? A które konkretnie?}
{176}{}{Kogo to obchodzi? (Wzruszenie ramion) Części to części.}
{177}{}{Żartuję przecież. Gdzie się podziały twoje jaja Josh? Pozwól, że zapytam o coś innego.}
{178}{}{Taa, to wszystko trzyma się kupy.}
{179}{}{Pewnie. Pozwól, że zaptam o coś innego.}
{180}{}{Skoro już o tym mowa, zaczynam odczuwać głód. Na razie Josh. Do widzenia.}
{181}{}{Przeklęci Marsjanie. A ja myślałem, że pochodzisz z dzikich plemion. Kurczę, głupio się czuję. Wiesz, w mojej książce kanibale to kanibale i już.}
{182}{}{Hej, zawsze najpierw gotujemy przed zjedzeniem. W końcu przecież nie jesteśmy dzikusami.}
{183}{}{Odczep się od moich jaj, kanibalu! Będą mi jeszcze przez jakiś czas potrzebne. Znajdź sobie inną przekąskę.}
{184}{}{Spokojnie, i tak wyglądasz na twardego i żylastego. He he. Tylko żartuję... w zasadzie. Pozwól Josh, że zapytam o coś innego.}
{185}{}{Rozejrzę się po okolicy. Ale jeśli nie znajdę nic lepszego, wrócę. Żegnaj... na razie.}
{186}{}{Najpierw trzeba kupić farmę. Planujesz w najbliższym czasie kupno jakiegoś porządnego domu?}
{187}{}{Uch, w każdym razie nie kupuję farmy. Pozwól, że zapytam o coś innego.}
{188}{}{To mogłoby pomóc temu lub tamtemu, gdyby kupić farmę w tej okolicy. Na razie Josh.}
{189}{}{Domyślam się, że w tym celu najpierw kogoś ukatrupisz. Ale odradzam. Szeryf Marion raczej nie lubi tego rodzaju zachowania.}
{190}{}{Postaram się zachowywać odpowiednio. Pozwól Josh, że zapytam cię o coś innego.}
{191}{}{Rozumiem... no, przynajmniej wiem już, z kim rozmawiać, gdy zdarzy się jakiś nieszczęśliwy *wypadek*. Do widzenia Josh.}
