{100}{}{Widzisz wysokiego, chudego mê¿czyznê patrz¹cego na ciebie taksuj¹cym wzrokiem.}
{101}{}{Widzisz Josha Laurance'a, w³aœciciela Saloonu Ostatnie Tchnienie.}
{102}{}{Widzisz mê¿czyznê mierz¹cego ciê wzrokiem tak, jakby zdejmowa³ twoje wymiary.}
{103}{}{Wykolegowuj siê st¹d.}
{104}{}{Co ty tu u licha robisz, idioto?}
{105}{}{To nie jest miejsce dla ciebie.}
{106}{}{No ju¿. Zmiataj, idioto!}
{107}{}{Wynoœ siê, zanim zabrudzisz mi pod³ogê.}
{108}{}{Dzieñ dobry. Josh Laurance. Jestem w³aœcicielem tego miejsca.}
{109}{}{Co mogê dla ciebie zrobiæ?}
{110}{}{Co to dok³adnie za miejsce?}
{111}{}{Poproszê drinka.}
{112}{}{Poproszê kolejkê dla wszystkich.}
{113}{}{Poproszê kolejkê dla moich przyjació³.}
{114}{}{Co siê ostatnio dzieje w mieœcie?}
{115}{}{Na razie nic. Tylko têdy przechodzê. Do widzenia.}
{116}{}{Nie bêdê nic podawaæ temu czemuœ.}
{117}{}{Zabieraj st¹d swojego *przyjaciela*.}
{118}{}{To nie jest ¿aden cholerny gabinet dziwol¹gów. Wynoœ siê st¹d.}
{119}{}{To nie wejdzie do mojego lokalu.}
{120}{}{Nie podajemy nic osobom tego rodzaju. Wynocha.}
{121}{}{To jest Saloon i Zak³ad Pogrzebowy "Ostatnie Tchnienie". Pe³na obs³uga. Z Butelk¹ do Grobu, oto nasze motto.}
{122}{}{To nieco dziwaczne po³¹czenie, Josh.}
{123}{}{Lukrecja Borgia by³aby z ciebie dumna Josh.}
{124}{}{Co muszê zrobiæ, aby nabyæ trumnê?}
{125}{}{Jak mogê zamówiæ us³ugi pogrzebowe?}
{126}{}{Z pewnoœci¹ bêdê siê trzymaæ z dala od twojego ginu.}
{127}{}{Oczywiœcie. Nale¿y siê $5.}
{128}{}{Oto pieni¹dze.}
{129}{}{Chyba jednak na razie nie chcê piwa. Pozwól jednak, ¿e zadam ci kilka pytañ.}
{130}{}{Jakie to hojne z twojej strony. $50 do kasy przybywa, by ka¿dy móg³ napiæ siê piwa. Hej, nie wiedzia³em, ¿e jestem poet¹.}
{131}{}{Auæ. Uwa¿aj Josh, kalambury zabijaj¹. To przyjacielska rada, a tu s¹ pieni¹dze.}
{132}{}{Hmmm, twój kalambur odebra³ temu pomys³owi ca³y smak. Pozwó³, ¿e zamiast tego o coœ ciê zapytam.}
{133}{}{Czy¿ nie jesteœ tym typem przyjaciela, którego ka¿dy potrzebuje? To bêdzie }
{134}{}{Uczciwa cena. Proszê.}
{135}{}{Mo¿e jednak lepiej bêdê ich trzymaæ w trzeŸwoœci. Pozwól, ¿e zamiast tego o coœ ciê zapytam.}
{136}{}{Wszystko wygl¹da dobrze, gdy trzymasz interes w garœci. Tak trzymaæ. W ka¿dym razie pozwól mi zaj¹æ siê czymœ innym.}
{137}{}{Wiesz, to nie jest ¿adne du¿e halo. Zwykle mój interes krêci siê dosyæ wolno. Mo¿na by rzec, ¿e jest cichy jak grób. Chocia¿ ostatnio to nie znaczy ju¿ tyle, co kiedyœ.}
{138}{}{Hê? Co masz na myœli?}
{139}{}{Dok³adnie. Ale nie móg³bym zwi¹zaæ koñca z koñcem, gdybym ogranicza³ siê do grzebania ludzi - mo¿na by rzec, ¿e interes zdech³. Mo¿na mu by³o postawiæ nagrobek.}
{140}{}{Ach tak. Prawie bojê siê zadaæ nastêpne pytanie. Ale jednak spróbujê.}
{141}{}{Uch, czy widok tych wszystkich sztywniaków nie obrzydza ludziom jedzenia?}
{142}{}{Chyba nie wytrzymam nastêpnej gry s³ów. ¯egnam.}
{143}{}{Obrzydza³by, gdyby to by³y prawdziwe trupy. Ale nie s¹. W ka¿dym razie ¿aden z tych. Poza tym górnicy chyba to lubi¹. Dziêki temu dostrzegaj¹, jak wiele maj¹ szczêœcia, ¿e ¿yj¹.}
{144}{}{Myœlê, ¿e to jest przera¿aj¹ce. Jesteœ bardzo pokrêconym indywiduum.}
{145}{}{Rozumiem. No wiêc, tego, mam inne pytanie.}
{146}{}{Domyœlam siê, ¿e niektórzy mog¹ tak to odbieraæ. Ale nie ja. Po prostu mam od tego md³oœci. Do widzenia.}
{147}{}{Mówisz, ¿e *ja* jestem przera¿aj¹cy? Przecie¿ podobno wasze plemiona jedz¹ swoich w³asnych zmar³ych.}
{148}{}{Jak¿e inaczej moglibyœmy wch³on¹æ ich dusze?}
{149}{}{Odczep siê. Zawsze ich przedtem gotujemy. Przecie¿ nie jesteœmy dzikusami.}
{150}{}{To œmieszne. Kto ci to powiedzia³?}
{151}{}{Nie wiem dok³adnie. Ale to przecie¿ oczywiste. Po có¿ innego mielibyœcie opi³owywaæ swoje zêby, by je naostrzyæ, hê? No powiedz!}
{152}{}{Nie pi³ujê moich zêbów, ¿eby je... och, niewa¿ne. Pozwól, ¿e zapytam o coœ innego.}
{153}{}{Dziêkujê uprzejmie. Coœ jeszcze?}
{154}{}{W³aœciwie to tak.}
{155}{}{Nie, na razie wystarczy. Dziêki Josh.}
{156}{}{Co przez to rozumiesz?}
{157}{}{Chcê tylko powiedzieæ, ¿e to raczej, no, *niezwyk³a* kombinacja.}
{158}{}{Nic, nic, zupe³nie nic. Pozwól Josh, ¿e zapytam o coœ jeszcze.}
{159}{}{Chcê tylko powiedzieæ, ¿e wolê piæ w miejscach, które s¹ nieco mniej sztywne. To znaczy, bardziej na luzie, oczywiœcie. Do widzenia.}
{160}{}{Spêdzi³em sporo czasu na ponownym zakopywaniu ludzi le¿¹cych na cmentarzu obok. Ktoœ - albo coœ - ci¹gle ich wykopuje. Nie wiem czemu. To znaczy, oni nie maj¹ na sobie nic cennego.}
{161}{}{Ktoœ otwiera groby?}
{162}{}{Sk¹d wiesz, ¿e nie maj¹ na sobie nic cennego?}
{163}{}{To pewnie tylko szczury. Pozwól, ¿e zapytam o coœ innego.}
{164}{}{No, nie wiem na pewno, ale... ekhm, khm. Tylko zgadujê. Tak, w³aœnie. Wiesz co, napij siê piwa na koszt firmy.}
{165}{}{Nie wiem, co mi imputujesz, ale nie podoba mi siê to.}
{166}{}{Dziêki za piwo. Co masz na myœli mówi¹c, ¿e coœ ich wykopuje?}
{167}{}{A wiêc powiedz mi, co masz na myœli mówi¹c, ¿e coœ ich wykopuje.}
{168}{}{No, nigdy nic nie widzia³em, ale tak mniej wiêcej raz na tydzieñ jeden z grobów zostaje rozgrzebany i na wpó³ rozkopany. Nie wiem, co te¿ mo¿e to robiæ.}
{169}{}{Dziwne.}
{170}{}{Irytuj¹ce raczej. Teraz górnicy mówi¹ mi, ¿e raczej ju¿ woleliby spêdziæ swe ostatnie chwile tutaj, ni¿ zostaæ zakopanym tylko po to, ¿eby ich ktoœ potem wyci¹ga³ jak przejrza³¹ cebulê. Kurcze, tych milszych móg³bym trzymaæ tutaj, ale nie ca³¹ resztê. Zupe³nie nie wiem, co z tym zrobiæ.}
{171}{}{Jaka mi³a historia. Na pewno obudzê siê z krzykiem, gdy mi siê kiedyœ przyœni. Pozwól, ¿e zapytam o coœ innego.}
{172}{}{W rzeczy samej, to tajemnicza sprawa. No, jeszcze siê zobaczymy. Na razie.}
{173}{}{No, skoro ich najpierw gotuje... zaczekaj chwilê. Przecie¿ to wci¹¿ kanibalizm! Jesteœ ma³ym, wrednym popaprañcem, nawet jak na dzikusa.}
{174}{}{Spokojnie Josh. Tylko ¿artujê. He he. Wiesz, gotujemy tylko niektóre czêœci.}
{175}{}{Czêœci, co? A które konkretnie?}
{176}{}{Kogo to obchodzi? (Wzruszenie ramion) Czêœci to czêœci.}
{177}{}{¯artujê przecie¿. Gdzie siê podzia³y twoje jaja Josh? Pozwól, ¿e zapytam o coœ innego.}
{178}{}{Taa, to wszystko trzyma siê kupy.}
{179}{}{Pewnie. Pozwól, ¿e zaptam o coœ innego.}
{180}{}{Skoro ju¿ o tym mowa, zaczynam odczuwaæ g³ód. Na razie Josh. Do widzenia.}
{181}{}{Przeklêci Marsjanie. A ja myœla³em, ¿e pochodzisz z dzikich plemion. Kurczê, g³upio siê czujê. Wiesz, w mojej ksi¹¿ce kanibale to kanibale i ju¿.}
{182}{}{Hej, zawsze najpierw gotujemy przed zjedzeniem. W koñcu przecie¿ nie jesteœmy dzikusami.}
{183}{}{Odczep siê od moich jaj, kanibalu! Bêd¹ mi jeszcze przez jakiœ czas potrzebne. ZnajdŸ sobie inn¹ przek¹skê.}
{184}{}{Spokojnie, i tak wygl¹dasz na twardego i ¿ylastego. He he. Tylko ¿artujê... w zasadzie. Pozwól Josh, ¿e zapytam o coœ innego.}
{185}{}{Rozejrzê siê po okolicy. Ale jeœli nie znajdê nic lepszego, wrócê. ¯egnaj... na razie.}
{186}{}{Najpierw trzeba kupiæ farmê. Planujesz w najbli¿szym czasie kupno jakiegoœ porz¹dnego domu?}
{187}{}{Uch, w ka¿dym razie nie kupujê farmy. Pozwól, ¿e zapytam o coœ innego.}
{188}{}{To mog³oby pomóc temu lub tamtemu, gdyby kupiæ farmê w tej okolicy. Na razie Josh.}
{189}{}{Domyœlam siê, ¿e w tym celu najpierw kogoœ ukatrupisz. Ale odradzam. Szeryf Marion raczej nie lubi tego rodzaju zachowania.}
{190}{}{Postaram siê zachowywaæ odpowiednio. Pozwól Josh, ¿e zapytam ciê o coœ innego.}
{191}{}{Rozumiem... no, przynajmniej wiem ju¿, z kim rozmawiaæ, gdy zdarzy siê jakiœ nieszczêœliwy *wypadek*. Do widzenia Josh.}
