{100}{}{Widzisz Madame Modrzejewsk¹.}
{101}{}{Widzisz Madame Modrzejewsk¹.}
{102}{}{Chcê zostaæ sama.}
{103}{}{Proszê, po prostu odejdŸ.}
{104}{}{Nie zawracaj mi g³owy.}
{105}{}{Zostaw mnie w spokoju.}
{106}{}{Nie tolerujê prostaków.}
{107}{}{Wiêkszoœæ plebsu pracuje, ¿eby zdobyæ wystarczaj¹co Jetu. Potrzebuj¹ czegoœ, aby oderwaæ siê myœlami od tego miejsca.}
{108}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{109}{}{Jet? Co to jest Jet?}
{110}{}{Rozumiem. Do zobaczenia.}
{111}{}{Jet ma swoje zastosowania. Oddala on nieco cz³owieka od otaczaj¹cego go brudu.}
{112}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{113}{}{Jet? Co to jest Jet?}
{114}{}{Rozumiem. Do zobaczenia.}
{115}{}{Ostatnio Jet sta³ siê bardzo drogi. To po prostu zbrodnia. A propos... S³ysza³am, ¿e nasz wspania³y burmistrz Ascorti pracuje nad tym, aby zdobyæ dla nas wiêcej Jetu. Ten cz³owiek zawsze jest bohaterem dla mas..}
{116}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{117}{}{Burmistrz Ascorti? Kto to dok³adnie jest?}
{118}{}{Jet? Co to jest Jet?}
{119}{}{Rozumiem. Do zobaczenia.}
{120}{}{Wygl¹da na to, ¿e wszyscy s¹ chorzy. Ostatnia partia Jetu spowodowa³a, ¿e wszyscy patrz¹ na ten towar z obrzydzeniem. Wed³ug mnie wróc¹ do niego jednak wystarczaj¹co szybko.}
{121}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{122}{}{Jet? Co to jest Jet?}
{123}{}{Rozumiem. Do zobaczenia.}
{124}{}{Wygl¹da na to, ¿e jednak omyli³am siê. Wiêkszoœæ ludzi, którzy kiedyœ naprawdê lecieli na Jecie, teraz przeklina jego istnienie. Po tej ostatniej trefnej partii wiêkszoœæ z nas dostaje torsji nawet po samym pow¹chaniu tego towaru.}
{125}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{126}{}{Jet? Co to jest Jet?}
{127}{}{Rozumiem. Do zobaczenia.}
{128}{}{Jestem... Madame Modrzejewska. Czego sobie ode mnie ¿yczysz?}
{129}{}{W czym mogê ci pomóc?}
{130}{}{Nie mogê trwoniæ czasu. Czego chcesz od Madame Modrzejewskiej?}
{131}{}{Lepiej mi nie zawracaæ teraz g³owy. Czego chcesz?}
{132}{}{Madame Modjeska ma dziœ lekk¹ niedyspozycjê. Czego sobie od niej ¿yczysz?}
{133}{}{Chyba mi zaraz pêknie g³owa. Czego sobie ode mnie ¿yczysz?}
{134}{}{Jestem Madame Modrzejewska. Kiedyœ, miêdzy innymi, za¿ywa³am Jetu. Teraz zajmujê siê innymi sprawami. Zda³am sobie sprawê, ¿e Ja i Jet nie pasujemy do siebie..}
{135}{}{Co Madame mo¿e zrobiæ dla ciebie?}
{136}{}{Czym siê tu zajmujesz, Madame Modrzejewska?}
{137}{}{Wygl¹da na to, ¿e du¿o ludzi tutaj jest amatorami chemikaliów. Co ostatnio dzieje siê w mieœcie?}
{138}{}{Czy s³ysza³aœ jakieœ ciekawe plotki?}
{139}{}{Dlaczego mówi¹ na ciebie Madame Modrzejewska?}
{140}{}{Co z tob¹?}
{141}{}{Co ci siê sta³o?}
{142}{}{Ostatnio w ogóle nie robiê du¿o. Kiedyœ prowadzi³am czêœæ interesu Lou w Saloonie Malamute - ale dosz³o miêdzy nami do niesnasek, wiêc odesz³am.}
{143}{}{A wiêc pozwól, ¿e zapytam ciê o coœ innego.}
{144}{}{Rozumiem. Có¿, to wszystko, co muszê wiedzieæ. Do zobaczenia.}
{145}{}{Wszystko, o czym s³yszê, dotyczy polityki. To zawsze jakoœ wychodzi w rozmowie.}
{146}{}{Polityka? Co masz na myœli?}
{147}{}{Oczywiœcie. A wiêc pozwól, ¿e zapytam ciê o coœ innego.}
{148}{}{Có¿, to wszystko, co muszê wiedzieæ. Do widzenia.}
{149}{}{Kiedyœ pracowa³am w Saloonie Malamute. Jako czêœæ tej roboty ludzie nazywali mnie Madame. Imiê pozosta³o, pomimo ¿e ju¿ tam nie pracujê.}
{150}{}{A gdzie teraz pracujesz?}
{151}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{152}{}{Nic wiêcej nie potrzebujê. Do widzenia.}
{153}{}{Troszkê odlecia³am na Jecie kilka dni temu i to spowodowa³o, ¿e nie czujê siê zbyt dobrze. Musia³a byæ jakaœ felerna partia. Niezbyt mnie nêci, aby spróbowaæ tego jeszcze raz. Có¿, chyba czeka mnie powrót do butelki.}
{154}{}{le to brzmi. Zapytam ciê wiêc o coœ innego.}
{155}{}{Rozumiem. Có¿, to wszystko, co muszê wiedzieæ. Do zobaczenia.}
{156}{}{Czujê siê lepiej, ni¿ wygl¹dam. Niedu¿o, ale wystarczaj¹co.}
{157}{}{Co masz na myœli? Co siê sta³o?}
{158}{}{Czy dane ci by³o ju¿ zobaczyæ zawody w ³apaniu œliskiej braminy?}
{159}{}{Jasne. Ee, wiele razy. Zapytam ciê jednak o coœ innego.}
{160}{}{Nie, nie znam niczego takiego. Opowiedz mi o tym.}
{161}{}{Nie wiem, co to mo¿e mieæ wspólnego z polityk¹ lokaln¹, i chyba nie chcê wiedzieæ. Do widzenia.}
{162}{}{Po tej ostatniej felernej partii Jetu, rzuci³am branie. Mo¿e gdy poczujê siê lepiej, zamiast tego po prostu siê upijê (œmieje siê)}
{163}{}{Có¿, to chyba dobrze dla ciebie. Spytam ciê o coœ innego.}
{164}{}{Interesuj¹ce. Có¿, pozostawiam ciê twojemu powrotowi do zdrowia. Do widzenia.}
{165}{}{To co robi¹, to smaruj¹ cielaka braminy, a potem wszyscy w t³umie próbuj¹ go z³apaæ. Je¿eli samemu nie mo¿esz go z³apaæ, to przynajmniej upewniasz siê, ¿e nikt inny nie bêdzie móg³ tego zrobiæ.}
{166}{}{Nie rozumiem, co to wspólnego z polityk¹.}
{167}{}{Tak, oczywiœcie. Wiem ju¿ wszystko, Madame Modrzejewska. Do widzenia.}
{168}{}{W tej grze Redding jest t¹ nasmarowan¹ bramin¹ - na dodatek z³ot¹. Nowe Reno, Republika Nowej Kalifornii i Kryptopolis staraj¹ siê j¹ z³apaæ... a przynajmniej utrzymaæ innych od dostania jej.}
{169}{}{Jak to?}
{170}{}{To mi³o. Có¿, lepiej ju¿ sobiê pójdê, Madame. Dziêki za rozjaœnienie sytuacji. Do widzenia.}
{171}{}{Tutaj, w Redding, wydobywamy z³oto. Potem transportujemy je do Nowego Reno, RNK i Kryptopolis w zamian za inne towary. Ka¿de z tych miejsc chcia³oby mieæ z³oto - i handel - tylko dla siebie.}
{172}{}{Dlaczego po prostu was nie zaatakuj¹ i nie wezm¹ tego, czego chc¹?}
{173}{}{Kto by nie chcia³? Chyba spróbujê samodzielnie znaleŸæ trochê tego z³ota. Dziêkujê i do widzenia.}
{174}{}{Jesteœmy wystarczaj¹co silni i zbyt oddaleni, aby takie przejêcie by³o bezpieczne i op³acalne. O wiele wydajniej by³oby, gdybyœmy przy³¹czyli siê z w³asnej woli.}
{175}{}{Jak to?}
{176}{}{To ma sens. Dziêki za wyjaœnienie mi tego. Do widzenia.}
{177}{}{Trzy si³y próbuj¹ nak³oniæ Redding, aby wybra³o, z kim chce siê zjednoczyæ. Wszystkie one maj¹ potê¿nych sojuszników w mieœcie i wygl¹da na to, ¿e ca³a sprawa nied³ugo bêdzie siê mia³a ku koñcowi. Redding bêdzie wkrótce musia³o podj¹æ decyzjê.}
{178}{}{Decyzjê?}
{179}{}{Kto pracuje dla kogo?}
{180}{}{Pieni¹dze. Hmm. Có¿, muszê ju¿ iœæ. Do widzenia.}
{181}{}{Warstwa t³uszczu na braminie staje siê coraz chudsza. Nied³ugo jedna z tych si³ bêdzie musia³a wykonaæ powa¿ny ruch, aby przej¹æ Redding zanim reszta to zrobi. Gdy to siê stanie, ludziom stanie siê krzywda. Wielu ludziom.}
{182}{}{Kto pracuje dla kogo?}
{183}{}{Dlaczego ludziom ma siê staæ krzywda?}
{184}{}{Dziêkujê za informacje. Do widzenia.}
{185}{}{Nie jestem wszystkiego pewna, ale myœlê, ¿e role wygl¹daj¹ tak: Dan McGrew jest za Nowym Reno, Marge LeBarge za RNK, doktor Johnson za Kryptopolis, jednak nie wiem jeszcze, za kim jest burmistrz Ascorti.}
{186}{}{Jak ci ludzie mog¹ pomóc w przejêciu w³adzy?}
{187}{}{Kim jest Marge LeBarge?}
{188}{}{Kim jest Dan McGrew?}
{189}{}{Kim jest doktorek Johnson?}
{190}{}{Kim jest burmistrz Ascorti?}
{191}{}{Dziêkujê za informacje. Do widzenia.}
{192}{}{Ludziom stanie siê krzywda, poniewa¿ taka zmiana nie przychodzi z ³atwoœci¹. Ci, którzy uwa¿aj¹, ¿e nie uda im siê zdobyæ nagrody maj¹ w g³owie tylko jedn¹ myœl - aby nikt inny jej równie¿ nie dosta³. Jedyn¹ szans¹, aby temu zapobiec, jest zdecydowaæ siê, czy zawieramy z kimœ sojusz i zawrzeæ szybki sojusz, zanim pozostali siê po³api¹.}
{193}{}{S¹dzisz, ¿e co siê stanie?}
{194}{}{Rozumiem. Dziêki, do widzenia.}
{195}{}{Myœlê, ¿e ludzie pójd¹ za przywództwem burmistrza Ascortiego. To drañ, ale ludzie mu ufaj¹. Pójdzie za tym, kto bêdzie najsilnieszy. Widzisz, cokolwiek jest dobre dla Ascortiego, bêdzie tak¿e dobre dla Redding. S¹dzê, ¿e on jeszcze nie zdecydowa³, kto jest najbli¿szy szczytu. Ale bêdzie musia³ szybko zdecydowaæ.}
{196}{}{Pomówmy o czymœ innym.}
{197}{}{Dziêki za wyjaœnienie mi, co tutaj siê dzieje. Do widzenia.}
{198}{}{Marge LeBarge jest w³aœcicielk¹ kopalni Kokoweef. Ona i kopalnia Morningstar s¹ jedynymi dwoma pozosta³ymi kopalniami w Redding. Myœlê, ¿e Marge najbardziej pasuje do RNK. Nie s¹dzê, aby podoba³a jej siê ich pruderyjnoœæ, ale potrafi oceniæ si³ê, któr¹ widzi przed sob¹.}
{199}{}{Kim jest Dan McGrew?}
{200}{}{Kim jest doktorek Johnson?}
{201}{}{Kim jest burmistrz Ascorti?}
{202}{}{Jak ci ludzie mog¹ pomóc w przejêciu w³adzy?}
{203}{}{Dziêkujê za informacje. Do widzenia.}
{204}{}{"Niebezpieczny" Dan McGrew, a, tak. Jest w³aœcicielem kopalni Morningstar. Ona i kopalnia Kokoweef s¹ jedynymi dwoma pozosta³ymi pracuj¹cymi kopalniami w Redding. S¹dzê, ¿e Dan przechyla siê na stronê Nowego Reno, gdybym mia³a zgadywaæ. Lubi, gdy jego górnicy s¹ szczêœliwi i na haju.}
{205}{}{Kim jest Marge LeBarge?}
{206}{}{Kim jest doktorek Johnson?}
{207}{}{Kim jest burmistrz Ascorti?}
{208}{}{Jak ci ludzie mog¹ pomóc w przejêciu w³adzy?}
{209}{}{Dziêkujê za informacje. Do widzenia.}
{210}{}{Ascorti jest merem. Prowadzi Asa Ascortiego w centrum. Zajmuje siê kupnem i sprzeda¿¹ mnóstwa rzeczy. Jest zawsze w centrum wszystkich spraw.}
{211}{}{Ascorti jest merem Redding. Ale nie wiem dok³adnie, gdzie jest teraz. Nie widzia³am go ju¿ od pewnego czasu.}
{212}{}{Pomówmy o czymœ innym.}
{213}{}{Chyba ju¿ wystarczaj¹co d³ugo ciê s³ucham. Do widzenia.}
{214}{}{Kochanie, Jet jest wspania³ym narkotykiem, który pomaga mi odejœæ nieco od tej marnej egzystencji.}
{215}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{216}{}{Interesuj¹ce. Dziêki i do widzenia.}
{217}{}{Jet jest narkotykiem, który pozwala mi poczuæ, ¿e naprawdê ¿yjê. Z Jetem jestem prawdziwym ptakiem przestworzy.}
{218}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{219}{}{Interesuj¹ce. Dziêki i do widzenia.}
{220}{}{Mmmm, powiem ci, co to jest Jet. To jest pyszne, o to co to jest. Jet ma coœ dla ka¿dego.}
{221}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{222}{}{Interesuj¹ce. Dziêki i do widzenia.}
{223}{}{Jet to by³o coœ. Teraz wywraca mi flaki jak zu¿yta pralka. Nie polecam ¿adnej dawki z obecnej partii. Kochanie, lot na tym Jecie mo¿e siê skoñczyæ tylko katastrof¹.}
{224}{}{Jasne, przepraszam. Pozwól, ¿e zapytam ciê o coœ innego.}
{225}{}{Interesuj¹ce. Dziêki i do widzenia.}
{226}{}{Coœ by³o strasznie nie w porz¹dku z ostatni¹ parti¹ Jetu, która przysz³a do miasta. Lot po nim koñczy³ siê tragicznie. Chyba skoñczy³am z lotami. Teraz pijê - zawsze jest coœ, na czym mo¿esz polegaæ.}
{227}{}{Pozwól, ¿e spytam ciê o coœ innego.}
{228}{}{Interesuj¹ce. Dziêki i do widzenia.}
{229}{}{"Bezbolesny" doktor Johnson jest trochê zagadkowym cz³owiekiem. Nie wiem, sk¹d przyby³, ale jest prawdziwym doktorem. Jedyne miejsce, gdzie móg³ zdobyæ takie przeszkolenie, to Kryptopolis. Za³o¿ê siê, ¿e zainstalowali go tutaj, aby rozwija³ ich interesy. Chyba jednak musia³ kogoœ tam wkurzyæ, ¿e dosta³ takie zadanie. Ci Krypciarze nie lubi¹ zbytnio zewnêtrza.}
{230}{}{Kim jest Marge LeBarge?}
{231}{}{Kim jest Dan McGrew?}
{232}{}{Kim jest burmistrz Ascorti?}
{233}{}{Jak ci ludzie mog¹ pomóc w przejêciu w³adzy?}
{234}{}{Dziêkujê za informacje. Do widzenia.}
{235}{}{Mer to cz³owiek, który wie, jak graæ po obu stronach i jeszcze capn¹æ œrodek. Ma bardzo ma³o skrupu³ów, ale najczêœciej bêdzie robi³ to, co dobre dla Redding, aby i jego interesy pozosta³y bezpieczne.}
{236}{}{Kim jest Marge LeBarge?}
{237}{}{Kim jest Dan McGrew?}
{238}{}{Kim jest doktorek Johnson?}
{239}{}{Jak ci ludzie mog¹ pomóc w przejêciu w³adzy?}
{240}{}{Dziêkujê za informacje. Do widzenia.}
