{100}{}{Widzisz człowieka w pancerzu. Patrzy na ciebie w zamyśleniu.}
{101}{}{Widzisz Stanwella, mistrza karawany Redding - RNK.}
{102}{}{Widzisz wysokiego, muskularnego mężczyznę w pancerzu. Jego sprzęt wygląda na używany, ale dobrze utrzymany.}
{103}{}{RNK niezbyt przychylnie patrzy na tchórzy. Wynocha stąd.}
{104}{}{Wiesz, co myślę o takich, jak ty. Wynocha sprzed moich oczu.}
{105}{}{I-haa! Jedziemy.}
{106}{}{Dobra, ruszamy.}
{107}{}{Jestem Stanwell. Prowadzę karawanę pomiędzy Redding i Republiką Nowej Kalifornii. Braminy za złoto. Przydałby nam się dodatkowy strażnik, i jesteśmy właśnie gotowi do drogi. }
{108}{}{Ludzie mówią na mnie Stanwell. Prowadzę karawanę pomiędzy Redding i Republiką Nowej Kalifornii. Braminy za złoto. Zazwyczaj przyda się kilka dodatkowych rąk do pracy. Opuszczamy miasto jedenastego każdego miesiąca. Jeżeli piszesz się na to, to nie zapomnij wtedy się pokazać.}
{109}{}{Czy jeszcze coś?}
{110}{}{Mu-mu?}
{111}{}{Potrzebujesz strażnika, co?}
{112}{}{Co transportuje ta karawana?}
{113}{}{Dlaczego czekacie do jedenastego?}
{114}{}{To chyba nie dla mnie. Na razie.}
{115}{}{Cholera. Nie cierpię, kiedy to się dzieje.}
{116}{}{Ta sama robota. Inny dzień.}
{117}{}{Nic nigdy nie jest proste.}
{118}{}{Gdzie jest Strażnik, kiedy go potrzebujesz?}
{119}{}{W tych czasach to już za każdym razem.}
{120}{}{Jeszcze tak złej i żałosnej podróby strażnika nie widziałem. Nawet gdyby zależało od tego twoje życie, to i tak nie potrafisz dotrzymać słowa.}
{121}{}{Zejdź mi z oczu, do diaska. I dobrze wiesz dlaczego.}
{122}{}{Naprawdę myślisz, że wynagrodzę złodzieja? Masz szczęście, że nie zlinczowałem cię na szlaku. Oczywiście, że nic ci nie płacę. A teraz won.}
{123}{}{Złodziejem? Zapamiętam to sobie, ty podły niewdzięczniku. Odchodzę, żegnam.}
{124}{}{Któregoś dnia, niedługo, pożałujesz tego. Żegnam.}
{125}{}{Zostaliśmy tak oskubani, że nie mam wystarczająco pieniędzy, aby ci zapłacić. Oczywiście, gdyby twoja robota była lepsza, to sprawy stałyby inaczej.}
{126}{}{Ty draniu! Zapłacisz mi za to oszustwo. Żegnam.}
{127}{}{Cóż, czasami ma się większe szczęście od innych. Tym razem było odwrotnie. Żegnaj.}
{128}{}{Na szczęście nie straciliśmy wszystkiego... ale straciliśmy więcej, niż możemy sobie pozwolić. Gdyby twoja praca była lepsza, to i płaca przekraczałaby te $500.}
{129}{}{Cóż, coś to chyba i tak lepiej niż nic. Na razie.}
{130}{}{Ty draniu! Nikt nie mógłby zrobić lepszej roboty. Pożałujesz tego oszustwa. Żegnam.}
{131}{}{Wcale nie było tak źle. Tu są twoje $2000. Wróć, jeżeli kiedyś znowu będziesz potrzebować roboty.}
{132}{}{Nie chcę już chyba nigdy więcej spędzić tyle czasu gapiąc się w dupę braminy. Do widzenia.}
{133}{}{Nie było tak źle. Dzięki. Na razie.}
{134}{}{To był dobry kurs. Nie udałoby się aż tak dobrze, gdyby cię tam z nami nie było. Tu są twoje $2000, a dodatkowo $500 premii za wspaniałą robotę. Jeszcze raz dzięki.}
{135}{}{Miło znaleźć kogoś, kto docenia widoczną jakość. Może jeszcze się zobaczymy. Na razie.}
{136}{}{Zawsze miło jest zarobić dodatkowe pieniądze. Dzięki, i na razie.}
{137}{}{Nie mogę odejść, dopóki nie będę miał pełnego transportu rudy. To wszystko będzie gotowe jedenastego. Najlepiej wcześnie rano. Przyjdź wtedy, jeśli będzie cię to interesować.}
{138}{}{Musimy zebrać braminy z porozrzucanych farm zanim możemy wyruszyć. Będziemy gotowi do wczesnego wyjścia jedenastego. Zajrzyj do mnie wtedy, jeśli będziesz szukać pracy.}
{139}{}{Co zazwyczaj transportujecie?}
{140}{}{Pozwól, że zapytam o coś innego.}
{141}{}{Dzięki, tak zrobię. Na razie.}
{142}{}{Zazwyczaj szukamy kogoś do ochrony karawan, ale, tak jak już mówiłem, nie będziemy gotowi do drogi aż do jedenastego każdego miesiąca. Jeżeli nadal będzie cię to interesować, to zajrzyj do mnie wtedy.}
{143}{}{Kiedy jedenastego?}
{144}{}{Co transportuje ta karawana?}
{145}{}{Okej, dzięki. Na razie.}
{146}{}{Przykro mi, ale mamy już wystarczająco ludzi do pracy przy tej karawanie.}
{147}{}{Och, w porządku.}
{148}{}{Handlujemy najlepszymi braminami z RNK za rudę złota z Redding. Jasno i prosto - tak jak lubię.}
{149}{}{Rozumiem. Mówiłeś, że potrzebujesz strażników?}
{150}{}{Pozwól, że zapytam o coś innego.}
{151}{}{A, w porządku. Na razie.}
{152}{}{Dobrze, że jesteś. Jesteśmy gotowi do wyruszenia. Płacę $2000, ale tylko dlatego, że potrzebuję jeszcze jednego strażnika. Przyłączasz się?}
{153}{}{Dobrze, że jesteś. Jesteśmy gotowi do wyruszenia. Płacę $2000. Przyłączasz się?}
{154}{}{Brzmi wspaniale. Możemy wyruszać.}
{155}{}{Mogę wymyśleć lepsze sposoby na spędzenie czasu, niż żarcie non-stop braminiego pyłu. Na razie.}
{156}{}{Cóż, było darmowe jedzenie i bezpieczna podróż tutaj. A teraz zjeżdżaj, przygłupie.}
{157}{}{Upie? Pa pa.}
{158}{}{Grrrr! Moja chcieć krwi!}
