{100}{}{Widzisz małego gościa umazanego smarem.}
{101}{}{Patrzysz właśnie na Bustera, speca od gnatów.}
{102}{}{Ubrania tego gościa są podarte, a wszędzie na jego dłoniach, ramionach i twarzy widać ślady ciągłego kontaktu z bronią. Mimo to facet sprawia pogodne wrażenie.}
{103}{}{Hej, witaj w Imperium Najwyższej Jakości Uzbrojenia Bustera! To ja jestem Buster i nikt inny. Mam tu na półkach wyśmienite dobra, przyjrzyj się im. Chętnie ci je sprzedam.}
{104}{}{Hej! Z powrotem? Co mogę dla ciebie zrobić?}
{105}{}{Coś jeszcze?}
{106}{}{Chce spluwa.}
{107}{}{Co masz?}
{108}{}{Może mógłbyś skombinować mi coś wyjątkowego?}
{109}{}{Mam kilka pytań.}
{110}{}{Żegnaj.}
{111}{}{Doskonały wybór!}
{112}{}{No, partnerze, kradniemy tu sobie, co?}
{113}{}{Nie chcę cię poganiać, ale mam swoją robotę.}
{114}{}{Pewnie, czego chcesz się dowiedzieć?}
{115}{}{Opowiedz mi o RNK.}
{116}{}{O co chodzi z Merkiem?}
{117}{}{Co możesz mi powiedzieć o Franku Westinie?}
{118}{}{Pragnę spotkać się ze Starym Carlsonem. Znasz kogoś, kto mógłby mi pomóc?}
{119}{}{Masz może GECK?}
{120}{}{To miłe, nieznajomy, ale nie jestem instytucją charytatywną.}
{121}{}{Może. Mógłbym mieć celownik Triveld x10 - akurat pasowałby do karabinu myśliwskiego, gdyby znalazł się ktoś zainteresowany. Puszczę go tanio - 500$.}
{122}{}{Hej, nic mi już nie zostało.}
{123}{}{Dobra, umowa stoi.}
{124}{}{Nie, dzięki.}
{125}{}{Republika Nowej Kalifornii - oto czym jest. Prezydent Tandi i jej zgraja mówią, że próbują przywrócić dawne dni. Ja myślę, że oni tylko próbują zgarnąć, co się da. Cholera, nie mam na co narzekać - dawne dni były długo przed moimi czasami. Ale i tak strasznie z nich pruderyjna banda - nie lubią niewolnictwa, hazardu, niczego. To dlatego siedzę tu, na zewnątrz. Nie lubię zasad - nigdy nie lubiłem.}
{126}{}{Rozumiem.}
{127}{}{Żegnaj.}
{128}{}{Nie zadzieram z panem Merkiem i nie zawracam sobie głowy plotkami o nim. Jeśli masz jakieś pytania, zapytaj o niego w Rawhide.}
{129}{}{Rozumiem.}
{130}{}{Żegnaj.}
{131}{}{Frank Westin? Masz na myśli tego gościa z Kongresu? Usadził się na zachód od miasta. To człowiek od bramin - duża szycha w Stowarzyszeniu Chodowców Bydła. Jeśli szukasz pracy, to on zawsze kogoś szuka.}
{132}{}{Rozumiem.}
{133}{}{Żegnaj.}
{134}{}{Ciekawe, że pytasz o to po tym, co się przytrafiło Frankowi Westinowi. Nie żebym coś wiedział, ale jest taki facet w Rawhide - Merk - może on byłby w stanie ci pomóc.}
{135}{}{Rozumiem.}
{136}{}{Żegnaj.}
{137}{}{To jedno z tych importowanych zabawek sprzed wojny? Niech zgadnę, amunicja 14mm? Nie, nie mam go.}
{138}{}{Rozumiem.}
{139}{}{Żegnaj.}
{140}{}{Wiesz, nie mogę tego zamontować na niczym oprócz karabinu myśliwskiego. To przez budowę oprawy, rozumiesz?}
{141}{}{Rozumiem.}
{142}{}{Żegnaj.}
{143}{}{Zakład nieczynny. Idź sobie.}
{144}{}{O matko! Wróć o jakiejś normalnej godzinie, dobra?}
{145}{}{Przyjdź jak będę miał otwarte. I zasuń za sobą zasłonę, jak będziesz wychodzić z namiotu.}
{146}{}{Zamknięte.}
{147}{}{Słuchaj, zmiataj stąd, albo pan .45 się wścieknie!}
{148}{}{Zły ruch.}
{149}{}{Oto, co mam na tej półce. Jeśli będziesz potrzebować czegoś jeszcze, nie zapomnij przejrzeć również innych szafek.}
