{100}{}{Widzisz postać służącą do oszustw.}
{101}{}{Tego gościa nie powinno tu być.}
{102}{}{Hej, to postać służąca do oszustw.}
{103}{}{Hej, to boli.}
{104}{}{Witaj. Co chciałbyś, aby się zdarzyło?}
{105}{}{Ustawianie znaczników Westina.}
{106}{}{Zaznacz: akceptacja uciszenia Westina?}
{107}{}{Odznacz: akceptacja uciszenia Westina.}
{108}{}{Zaznacz: Westin nie żyje.}
{109}{}{Odznacz: Westin nie żyje.}
{110}{}{Zaznacz: uciszanie Westina odwołane.}
{111}{}{Odznacz: uciszanie Westina odwołane.}
{112}{}{Zaznacz: poznano fakty dotyczące leków Westina.}
{113}{}{Odznacz: poznano fakty dotyczące leków Westina.}
{114}{}{Zaznacz: misja z Westinem nieudana.}
{115}{}{Odznacz: misja z Westinem nieudana.}
{116}{}{Zaznacz: misja z Westinem udana.}
{117}{}{Odznacz: misja z Westinem udana.}
{118}{}{Zaznacz: uciszanie Westina zauważone.}
{119}{}{Odznacz: uciszanie Westina zauważone.}
{120}{}{Ustawianie znaczników Carlsona.}
{121}{}{Zaznacz: uciszanie Carlsona zaakceptowane.}
{122}{}{Odznacz: uciszanie Carlsona zaakceptowane.}
{123}{}{Zaznacz: Carlson martwy.}
{124}{}{Odznacz: Carlson martwy.}
{125}{}{Zaznacz: zadanie ochrony Carlsona.}
{126}{}{Odznacz: zadanie ochrony Carlsona.}
{127}{}{Zaznacz: uciszanie Carlsona odwołane.}
{128}{}{Odznacz: uciszanie Carlsona odwołane.}
{129}{}{Zaznacz: misja z Carlsonem udana.}
{130}{}{Odznacz: misja z Carlsonem udana.}
{131}{}{Zaznacz: misja z Carlsonem nieudana.}
{132}{}{Odznacz: misja z Carlsonem nieudana.}
