{100}{}{Widzisz osobę noszącą mundur policji RNK.}
{101}{}{Glina RNK.}
{102}{}{Sądząc po twarzy, na której nigdy nie pojawia się uśmiech, nie należy oczekiwać tu zbyt wiele litości.}
{103}{}{Odłożyć tę broń - JUŻ!}
{104}{}{Proszę zauważyć, że mamy w tym mieście zakaz noszenia broni. Proszę odłożyć swoją broń.}
{105}{}{Odłóż broń, a nikomu nic się nie stanie.}
{106}{}{Minęła godzina policyjna. Czemu nie pójdziesz do domu?}
{107}{}{Proszę iść dalej. Nie ma tu nic ciekawego.}
{108}{}{Noc nie jest dobrą porą na spacery po ulicach.}
{109}{}{Dzień dobry. Od niedawna w mieście?}
{110}{}{Proszę iść dalej. Nie ma tu nic ciekawego.}
{111}{}{Jestem na służbie. Jeśli będziesz mieć jakieś kłopoty, spróbuj zgłosić to u szeryfa.}
{112}{}{Hej, nie baw się tym.}
{113}{}{Zostaw to w spokoju.}
{114}{}{To nie jest do zabawy.}
{115}{}{Jeśli nie przestaniesz przy tym majsrować, to wiedz, że mam pozwolenie, żeby cię zastrzelić.}
