{100}{}{Widzisz mê¿czyznê w ubraniu roboczym.}
{101}{}{To kupiec braminów. Spodziewa siê karawany Hala.}
{102}{}{Œmierdzi od niego braminami.}
{113}{}{Có¿, to dopiero by³a rzeŸnia! Bojê siê, ¿e w tym spêdzie nie ma kasy dla ¿adnego z nas. Ciesz siê, ¿e ¿yjesz.}
{114}{}{Có¿, ranczerzy nie s¹ zbyt zadowoleni - za ten spêd tylko 1000$. Cholerne szczêœcie.}
{115}{}{Có¿, mia³eœ troszkê pecha, ale uda³o ci siê. Oto 2000$, na które siê umówiliœmy.}
{116}{}{Cholera, doskonale ci posz³o! Oto 1000$ premii dla ciebie. To i 2000$ razem daje twoj¹ zap³atê. Niech Redding lepiej dzisiaj w nocy uwa¿a!}
{118}{}{Nigdy nie widzia³em gorszego konwojenta. Spadaj st¹d!}
{119}{}{Co za szkoda ¿e Hal nie prze¿y³.}
{120}{}{Szkoda Hala...}
{121}{}{Mi³o robiæ z tob¹ interesy.}
{213}{}{Szlag, Hal nie ¿yje! Bramin te¿! Bojê siê, ¿e w tym spêdzie nie ma kasy dla ¿adnego z nas. Ciesz siê, ¿e ¿yjesz.}
{214}{}{Szlag, Hal nie ¿yje! Có¿, ranczerzy nie s¹ zbyt zadowoleni - za ten spêd tylko 1000$. Trudno.}
{215}{}{Szlag, Hal nie ¿yje! Przynajmniej braminom nic siê nie sta³o. Oto 2000$, na które siê umówiliœmy.}
{216}{}{Cholera, Hal nie ¿yje! Mimo to, uda³o ci siê. Oto 1000$ premii dla ciebie. To i 2000$ razem daje twoj¹ zap³atê. Niech Redding lepiej dzisiaj w nocy uwa¿a!}
