{100}{}{Widzisz dobrze ubranego, umięśnionego faceta, umyślnie poruszającego się powoli.}
{101}{}{To Merk - ludzie z okolicy mówią mu "szefie".}
{102}{}{Tego gościa otacza aura chłodu i obojętności. Wydaje się poświęcać ci tyle samo uwagi co muszę, którą zgniata się miedzy palcami.}
{103}{}{Hej, widziałem cię w filmach! Jesteś tu by pokazać się w akcji, co?}
{104}{}{Co ty sobie wyobrażasz? Wchodzisz tu bez pytania i przeszkadzasz mi. Zmiataj stąd.}
{105}{}{Przepraszam, ale mam tu interes do przeprowadzenia.}
{106}{}{Jeśli chcesz ze mną porozmawiać o interesach, spotkaj się ze mną w Rawhide. Jeśli nie - spadaj stąd.}
{107}{}{Widziałem cię na srebrnym ekranie, nie mylę się? Masz duże, ee, predyspozycje i te... no... niebieskie oczy.}
{108}{}{Masz to coś w oczach. Zatrzymaj się przy Rawhide - zawsze przyda się ktoś taki, jak ty.}
{109}{}{Kurwa, co to za odór. Coś właśnie weszło do pokoju.}
{110}{}{Idź przynieś mi następną whisky - biegiem!}
{111}{}{Nie mam teraz czasu.}
{112}{}{Jestem tutaj gościem. Przestań mnie zaczepiać.}
{113}{}{Hej słoneczko, masz ładne nóżki. Carlson ma coraz lepszy gust.}
{114}{}{Tutaj nie prowadzę interesów.}
{115}{}{Nie znam cię. Jestem szanowanym biznesmenem.}
{116}{}{A, co za lebioda. Spadaj i zostaw mnie w spokoju.}
{117}{}{A więc jednak postanowiłaś do mnie przyjść, kociaczku?}
{118}{}{Nie wiem nic o niczym. Zrozumiano?}
{119}{}{Wiceprezydentowi nie spodoba się to, że zaczepiasz jego gości.}
{120}{}{Facet serwuje tu cholernie dobry browar.}
{121}{}{Zejdź mi z drogi!}
{122}{}{Jeśli chcesz koniecznie z kimś pogadać - kup sobie przyjaciela.}
{123}{}{Nie pokazuje drogi i nie daje żebrakom kasy. Odwal się.}
{124}{}{Co to kurde - godzina socjalna?}
{125}{}{Jestem Merk. Czego chcesz?}
{126}{}{Znowu ty?}
{127}{}{Bądź grzeczny gnoju, bo może być niemiło.}
{128}{}{Oort.}
{129}{}{Szukam pracy.}
{130}{}{Z pewnego źródła wiem, że jesteś właściwa osobą do robienia interesów, jeśli wiesz o czym mówię.}
{131}{}{Powiadają, że to ty zapierdzieliłeś mi wóz.}
{132}{}{Szukam informacji.}
{133}{}{Podobno możesz mi udzielić informacji, na przykład o rzeczach, które zniknęły z samochodu.}
{134}{}{Znowu ty? Wykonałeś robotę?}
{135}{}{Hę?}
{136}{}{Nie.}
{137}{}{Mam kilka pytań.}
{138}{}{Hmm... Silny. Głupi... Jeśli chcesz robotę gadaj z Mirą. Zrozumiano? Mi-ra. Tam.}
{139}{}{Lubisz narobić trochę szumu? Czy ktoś zabierze stąd to gówno?}
{140}{}{Jesteś aż takim głupcem? Myślisz, że zatrudnię byle kogo? Jeśli chcesz dla mnie pracować, musisz udowodnić, że do czegoś nadajesz.}
{141}{}{Może po prostu zastrzelę Lennego. Pokaże ci co potrafię, on na to zasługuje.}
{142}{}{Jak udowodnić?}
{143}{}{Znasz może kogoś, kto potrzebuje Jetu?}
{144}{}{Słuchaj, jestem}
{145}{}{Jasne. Bo muszę komuś coś udowadniać. Zapomnij o tym, palancie.}
{146}{}{To był ten pieprzony Doofus, prawda? Ten mały ćpun za dużo gada. Coś ci powiem - skoś go dla mnie, nazwijmy to przysługą, wtedy pogadamy.}
{147}{}{Zgoda.}
{148}{}{Hej - nie jestem mordercą!}
{149}{}{Zaraz będziesz trupem. Chłopcy-}
{150}{}{Interesujące. Któż to taki rozpowiada takie rzeczy?}
{151}{}{Nie chrzan, grubasie. Jeśli nie odzyskam tego, co do mnie należy, skończysz sobie w przytulnej trumience.}
{152}{}{Słodkie. Odpowiesz na moje pytanie, czy nie?}
{153}{}{Och, to tylko coś co można usłyszeć na ulicy. Interesowało mnie, co masz na ten temat do powiedzenia.}
{154}{}{Nawet jeśli coś wiem - co z tego?}
{155}{}{Jeśli ktoś nie może znaleźć kilku własnych rzeczy, to chyba może je u ciebie kupić, co?}
{156}{}{Chcę swój towar, ty pierdolony grubasie!}
{157}{}{A jeśli pogadam o tobie z przedstawicielami prawa?}
{158}{}{Meczysz mnie już. Chłopcy - zajmijcie się naszym gościem.}
{159}{}{Lenny'emu by to się chyba nie podobało.}
{160}{}{Być może, nie pytałem go.}
{161}{}{Rób jak uważasz.}
{162}{}{To prawda. Ostatnio bardzo tu nudno. Czas na jakieś urozmaicenie. Chodź Lenny, chce zobaczyć jak 'to' miażdżysz.}
{163}{}{Jak gdybym miał jakieś problemy.}
{164}{}{Tak, na przykład?}
{165}{}{Jet? Proponujesz mi coś...?}
{166}{}{Mój przyjaciel wie, jak to robić. Zainteresowany?}
{167}{}{Coś nielegalnego? Nie, nie chce się w to pakować.}
{168}{}{Interesujące. Dam ci 1000$ w zamian za jego usługi.}
{169}{}{Zgoda.}
{170}{}{Nie, nie mogę tego zrobić przyjacielowi.}
{171}{}{Wygląda na to, że możemy ubić interes. W mieście mieszka szurnięty naukowiec - doktor Henry. Ma w posiadaniu papiery, których potrzebuję. Zapłacę ci za nie 1000$, ale nie możesz skrzywdzić doktorka. Żywy ma dla mnie większą wartość. Wchodzisz w to? }
{172}{}{Jasne.}
{173}{}{Niee, to nie w moim stylu.}
{174}{}{Wiedza będzie cię kosztować. Wyrażam się jasno?}
{175}{}{"Cena mądrości przekracza wszystkie inne."}
{176}{}{Masz tu 50$.}
{177}{}{Zapomnij o tym.}
{178}{}{O, to ty jesteś tą osobą.}
{179}{}{Kontynuuj.}
{180}{}{No cóż, z tego, co zauważyłem, jesteś tyle warty, co kupa gnoju.}
{181}{}{Domyśliłem się, żeś głupia cipa.}
{182}{}{W porządku. Nie ma sprawy. Nie szukam kłopotów. Powiem ci coś - namówię mojego szefa, żeby oddał ci twoje rzeczy.}
{183}{}{Lepiej, żeby tak było. Inaczej tu wrócę.}
{184}{}{Nie pierdol mi tu bzdur!}
{185}{}{Taka osoba mogłaby być do tego zdolna.}
{186}{}{A teraz, sugeruje, abyś wyszedł.}
{187}{}{Ależ oczywiście, zawołaj oficerów. Oczywiście masz wszystkie niezbędne dowody. Prawda?}
{188}{}{Jasne.}
{189}{}{Nieważne.}
{190}{}{W mieście jest ten przeklęty Centrolog. Strasznie mnie irytuje. Gdy już wyrwiesz tego chwasta, wróć, to pogadamy.}
{191}{}{Masz to jak w banku. Tylko się odpowiednio przygotuje i... Chwileczkę, kto to jest ten Centrolog i gdzie go znajdę?}
{192}{}{Jak śmiesz sprzeciwiać się prawdziwej wierze!}
{193}{}{Przykro mi, nie wdaje się w żadne wojny religijne, ani inne takie...}
{194}{}{Jestem wykształconym człowiekiem. Co chcesz wiedzieć?}
{195}{}{Pytaj.}
{196}{}{Szukam Krypty 13.}
{197}{}{Słyszałeś kiedyś o GECKu?}
{198}{}{Co wiesz na temat o Strażników?}
{199}{}{Co możesz mi powiedzieć o Westinie?}
{200}{}{Potrzebuję informacji o wiceprezydencie Carlsonie.}
{201}{}{To wszystko.}
{202}{}{Twoja zapłata obejmuje jeszcze jedno pytanie. Za następne zapłacisz kolejne 50 dolców.}
{203}{}{Dobra, masz.}
{204}{}{Wiem już wszystko, co było mi potrzebne.}
{205}{}{Tak się składa, że mam mapę do Krypty 13. Chcesz kupić? Tylko 1000 dolców.}
{206}{}{Jasne. Zajmę się tym.}
{207}{}{Pewnie masz jeszcze jakiś most na sprzedaż, co?}
{208}{}{Może później.}
{209}{}{To jakiś narkotyk z Nowego Reno? Nigdy o nim nie słyszałem.}
{210}{}{Nie, ale mam inne pytania.}
{211}{}{To wszystko, czego potrzebuję.}
{212}{}{Te dranie? Najlepiej niech się trzymają z daleka ode mnie, albo ich podziurawię.}
{213}{}{Cóż, to wiele wyjaśniło. Mam inne pytanie.}
{214}{}{To wszystko, czego potrzebuję.}
{215}{}{Ten ranczer, co? Raz tu przyszedł - na wpół martwy. Doktorek musiał nafaszerować go jakimiś pigułami - okazało się, że Westin ma poważne problemy z sercem.}
{216}{}{Dzięki za informacje. Mam jeszcze kilka pytań.}
{217}{}{To wszystko, czego potrzebuję.}
{218}{}{Jako dobry obywatel, popieram Carlsona w każdym działaniu przeciwko poszerzaniu tutaj wpływów Nowego Reno. Teraz, kiedy Westin nie żyje, pomagam w zorganizowaniu ochrony dla wiceprezydenta.}
{219}{}{Cóż, myślę, że nigdy nie będę miał szansy się z nim zobaczyć. Ja też wiele o nim wiem.}
{220}{}{To wszystko, czego potrzebuję.}
{221}{}{To wszystko?}
{222}{}{Nie, mam jeszcze kilka pytań.}
{223}{}{Tak, to już wszystko na dzisiaj.}
{224}{}{Hej, człowiek musi się starać. Krypta 13 to praktycznie miejsce kultu w tej okolicy. Zbudowali nawet pomnik jakiemuś gościowi, który stamtąd pochodził. To wszystko, co wiem.}
{225}{}{Dałem ci za to mapę, spróbuj z niej skorzystać.}
{226}{}{Mapa się nie sprawdziła? Przykro mi, tamten gość przysięgał, że to oryginał. Skąd miałem wiedzieć? Nie mam pojęcia o lokalizacji Krypty 13.}
{227}{}{Mam jeszcze kilka pytań.}
{228}{}{To wszystko, co potrzebuję wiedzieć.}
{229}{}{Powiem ci coś. Jestem zadowolony z twojej pracy, a Carlsonowi przydałby się kolejny strażnik. Daj mi trochę czasu, a będę miał dla ciebie świetną posadkę.}
{230}{}{Wchodzę w to, Merk.}
{231}{}{Nie potrzebuję roboty. Mimo wszystko dzięki.}
{232}{}{Wspaniale. Wróć, kiedy skończysz.}
{233}{}{To bardzo kłopotliwe. Chłopcy, zabijcie go i odzyskajcie dowód.}
{234}{}{Twoje żałosne próby zastraszenia niemal mnie bawią. Ale teraz sugeruje, wyjść, zanim te twoje gierki mnie znudzą.}
{235}{}{Słyszałem już, co się stało. Ciągle interesuje cię praca?}
{236}{}{Tak, zmęczyła mnie darmocha. Przydałaby mi się robota.}
{237}{}{Nie.}
{238}{}{Co ty do cholery tutaj robisz?}
{239}{}{Trochę mi się pomieszało. Już więcej tego nie zrobię. Chcę tylko trochę twojego czasu.}
{240}{}{Zrobię, co będę chciał, palancie.}
{241}{}{Spadaj stąd, warchole!}
{242}{}{No to co ty tu, kurwa, jeszcze robisz, pacanie? Chcesz mi zaimponować, to załatw robotę!}
{243}{}{Nie będę z tobą rozmawiał, dopóki nie skończysz roboty!}
{244}{}{Zawiodłem się na tobie. W normalnych okolicznościach usuwam rzeczy, które mnie zawodzą. Jednakże w twoim przypadku zrobię wyjątek. Po prostu wyjdź i nigdy tu nie wracaj, a zapomnę o wszystkim.}
{245}{}{No, nasz drobny interesik z doktorem Henrym jest już skończony?}
{246}{}{Taa, mam papiery, których potrzebowałeś.}
{247}{}{Nie.}
{248}{}{Dni takie jak ten bardzo mnie cieszą. Cóż, podsumujemy nasz interesik.}
{249}{}{Doszły do mnie słuchy, że nasz genialny doktor opuścił ten padół podczas twojej wizyty. To było wbrew rozkazom. Oczekuję, że wręczysz mi odszkodowanie, które pozwoli zniwelować przyszłe straty.}
{250}{}{Słuchaj, dam ci 500 dolców i po prostu zapomnimy o całej sprawie.}
{251}{}{Chrzań się.}
{252}{}{Cóż, życzę powodzenia. I pamiętaj - nie widzę żadnego powodu, dla którego mielibyśmy znów się spotykać.}
{253}{}{Dla mnie bomba.}
{254}{}{Umowa stoi - ale tylko dlatego, że cię lubię. Proponuje, żeby cię tu w najbliższym czasie nie było.}
{255}{}{Myślę, że po prostu cię zabiję, odbiorę swoją forsę, i zaliczę nagrodę za twoją głowę. W końcu tak powinien się zachowywać przykładny mieszkaniec.}
{256}{}{To znowu ty? GIŃ!}
{257}{}{Wydawało mi się, że kazałem ci nigdy więcej mi nie przeszkadzać.}
{258}{}{, a moje umięjętności są doskonałe. Zapytaj kogokolwiek.}
{259}{}{ facet.}
{260}{}{ laska.}
{261}{}{Ten Centrolog to szurnięty fanatyk religijny. Możesz go znaleźć w kościele.}
{262}{}{Już idę.}
{263}{}{Nie gadam z tobą, dopóki nie wykonasz zadania! Potrzebuję tych papierów na wczoraj.}
{264}{}{Nie, ale potrzebuję informacji.}
{265}{}{Wiem, że śmierć Lennego to nie wypadek, ty draniu.}
{266}{}{Hej, ta mapa była fałszywa.}
{267}{}{A co z pieniędzmi, które dostałeś ode mnie?}
{268}{}{Jak powiedziałem, przykro mi, że nie poszło po twojej myśli.}
{269}{}{Dopiero zrobi ci się przykro, jak wpakuję w ciebie kulkę.}
{270}{}{Hmmpf.}
{271}{}{Udało ci się "rozwiązać problem" z Centrologami dla Merka.}
{272}{}{Udało ci się zdobyć papiery dr Henry'ego.}
{300}{}{Gdzie do cholery wydaje ci się, że idziesz?! Zrób to jeszcze raz, a skopie ci dupę.}
{301}{}{Ostrzegałem cię!}
