{100}{}{Widzisz jaskrawo ubranego gościa zachwalającego jaszczurze kebaby.}
{101}{}{To sprzedawca jaszczurek na patyku.}
{102}{}{Jak na sprzedawcę jaszczurek na patyku, ten facet ma styl. Jest czysty, dobrze ubrany i prowadzi całkiem legalny mały interes.}
{103}{}{Chce ci się jeść, przybyszu? Mam najlepsze jaszczurki w okolicy. Spytaj kogokolwiek!}
{104}{}{Czy mogę służyć?}
{105}{}{Daj mięso.}
{106}{}{Wezmę jedną porcję.}
{107}{}{Co możesz mi powiedzieć o tym mieście?}
{108}{}{Żegnaj.}
{109}{}{Smacznego, przybyszu!}
{110}{}{Musztarda i cebula są tam.}
{111}{}{Cześć, kolego.}
{112}{}{Tak, na razie.}
{113}{}{Następny!}
{114}{}{Słuchaj, mam jedną zasadę. Nie mówię niczego o nikim. To dobra zasada, bo jeżeli trzymam gębę na kłódkę, to trzymam się też z dala od kłopotów. Kapujesz?}
{115}{}{Nic nie widziałem, nic nie słyszałem, a już szczególnie nic nie mówiłem. A teraz przestań mi tym zawracać gitarę.}
{116}{}{Dobrze. Słuchaj, chce mi się jeść.}
{117}{}{Masz może GECK?}
{118}{}{Jezu, przepraszam, że żyje!}
{119}{}{GECKa? Cóż, to stara historia, więc co tam. Masz na myśli stary Generator Ekosystemu Cudownej Krainy? Mieliśmy taki jeden - to znaczy nasi dziadkowie mieli. Użyli go, gdy wyszli z Krypty 15. Mówią, że tak zapoczątkowali to miejsce. Teraz jest już całkowicie zużyty.}
{120}{}{Wciąż chce mi się jeść.}
{121}{}{Cóż, dzięki.}
