{100}{}{Widzisz mieszkańca miasta.}
{101}{}{Widzisz jednego z członków lokalnej społeczności.}
{102}{}{Nie ma nic godnego wzmianki o wyglądzie tej osoby.}
{103}{}{Ach, idź sobie.}
{104}{}{Przykro mi. Już więcej tego nie zrobię.}
{105}{}{Właśnie stąd szedłem.}
{106}{}{Straże, znowu tu jest!}
{107}{}{Daj mi, proszę, spokój.}
{108}{}{Słuchaj, ja też nie chcę być w pobliżu ciebie.}
{109}{}{Zło jest w tobie. Proszę, nie odzywaj się do mnie.}
{110}{}{Zostaw nasze dzieci w spokoju.}
{111}{}{Zaliczasz się do jakichś cholernych kryminalistów. Mam nadzieję, że straże dopadną cię.}
{112}{}{Po prostu odejdź, ok?}
{113}{}{Ej, nie możesz zabijać ludzi - a zwłaszcza dzieci.}
{114}{}{Chyba cię nie lubię.}
{115}{}{Słuchaj, powiadom mnie, gdy znowu zaczniesz wszystko rozwalać, dobra?}
{116}{}{Muszę już iść.}
{117}{}{Za kogo ty się do cholery uważasz - żeby przychodzić do tego miasta?}
{118}{}{Po prostu odejdź, zanim komuś stanie się krzywda.}
{119}{}{Nie podobasz mi się.}
{120}{}{Prawo zniszczy wszystkich takich, jak ty.}
{121}{}{Coś ci się nie podoba?}
{122}{}{Czy nie możemy żyć w zgodzie?}
{123}{}{Nie mów do mnie.}
{124}{}{Cokolwiek by to nie było, powiedz to komuś innemu.}
{125}{}{Nie wyglądasz na kogoś strasznie twardego.}
{126}{}{Dlaczego po prostu nie odejdziesz?}
{127}{}{Cóż, muszę dostać kilka jajek.}
{128}{}{Wiesz może, jak postawić ściany z blachy falistej?}
{129}{}{Witam.}
{130}{}{Nie przeszkadzaj mi, proszę, mam dużo pracy.}
{131}{}{Ciekawe, czy są jeszcze jakieś burgery z braminy u Dustego.}
{132}{}{Czasami zastanawiam się, jak Sienkiewicz, dokąd zmierzam.}
{133}{}{Hmm, dzięki, naprawdę muszę już iść.}
{134}{}{Może później umówimy się na lunch.}
{135}{}{Aaa, ta, jesteś nowa twarzą w mieście.}
{136}{}{Pogadaj lepiej z szeryfem.}
{137}{}{Podobno będą niedługo budować nowe domy.}
{138}{}{W mieście jest dość spokojnie od czasu, gdy Dumont został wybrany.}
{139}{}{Dobrego dnia, przybyszu.}
{140}{}{Mamy tu całkiem spokojne miejsce. Fajnie, nie?}
{141}{}{Od niedawna w mieście? Idź do przybytku mojego kuzyna Duppo.}
{142}{}{Podobno na południu nastały ciężkie czasy. Kiedy rząd zamierza coś z tym zrobić?}
{143}{}{Jesteś z północy? Nie mamy tu wielu takich.}
{144}{}{Podobno wszyscy z pustyni są albo mutantami, albo bandytami!}
{145}{}{Nie mam czasu na pogaduszki. Czas wracać do pracy.}
{146}{}{Czyżby mieli wyprzedaż u Duppo'ego? A, nieważne.}
