{100}{}{Widzisz mężczyznę w pancerzu bojowym.}
{101}{}{Widzisz kobietę w pancerzu bojowym.}
{102}{}{Ten mężczyzna nosi odznakę Strażnika RNK.}
{103}{}{Ta kobieta nosi odznakę Strażnika RNK.}
{200}{}{Witaj Strażniku. Chcesz tu spędzić noc?}
{201}{}{Udało ci się dzisiaj zabić jakichś łowców niewolników?}
{202}{}{Uwolniliśmy dzisiaj tuzin niewolników.}
{203}{}{Ochrona pustkowi to ciężka praca, ale ktoś to musi robić.}
{204}{}{Dobrze cię mieć po naszej stronie. Zostań tu jak długo zechcesz.}
{205}{}{Słyszeliśmy co się stało z Metzgerem. Świetna robota!}
{300}{}{Łowcy niewolników atakują!}
{301}{}{Cholera, zostaliśmy zaatakowani!}
{400}{}{Pozdrawiamy.}
{401}{}{To prywatna posiadłość, nie włócz się tu.}
{402}{}{Lubisz łowców niewolników? Mam nadzieję, że nie... dla twojego dobra.}
{500}{}{Co do...!? Łowcy niewolników? Jak nas znaleźli? Musimy się bronić. Do ataku!}
{501}{}{Czekaj! Jestem po waszej stronie. Udało mi się ich tu zwabić, będziecie mogli na nich poćwiczyć strzelanie. (Zwracasz się w stronę Łowców Niewolników.) Przykro mi chłopaki, macie pecha. (Zaatakuj łowców niewolników.)}
{502}{}{No, to dopiero będzie zabawa! (Zaatakuj Strażników RNK.)}
{600}{}{Udało ci się oczyścić to miejsce ze Strażników RNK.}
