{100}{}{Widzisz mê¿czyznê w pancerzu bojowym.}
{101}{}{Widzisz kobietê w pancerzu bojowym.}
{102}{}{Ten mê¿czyzna nosi odznakê Stra¿nika RNK.}
{103}{}{Ta kobieta nosi odznakê Stra¿nika RNK.}

{200}{}{Witaj Stra¿niku. Chcesz tu spêdziæ noc?}
{201}{}{Uda³o ci siê dzisiaj zabiæ jakichœ ³owców niewolników?}
{202}{}{Uwolniliœmy dzisiaj tuzin niewolników.}
{203}{}{Ochrona pustkowi to ciê¿ka praca, ale ktoœ to musi robiæ.}
{204}{}{Dobrze ciê mieæ po naszej stronie. Zostañ tu jak d³ugo zechcesz.}
{205}{}{S³yszeliœmy co siê sta³o z Metzgerem. Œwietna robota!}

{300}{}{£owcy niewolników atakuj¹!}
{301}{}{Cholera, zostaliœmy zaatakowani!}

{400}{}{Witaj przyjacielu.}
{401}{}{To prywatna posiad³oœæ, nie w³ócz siê tu.}
{402}{}{Lubisz ³owców niewolników? Mam nadziejê, ¿e nie... dla twojego dobra.}

{500}{}{Co do...!? £owcy niewolników? Jak nas znaleŸli? Musimy siê broniæ. Do ataku!}
{501}{}{Czekaj! Jestem po waszej stronie. Uda³o mi siê ich tu zwabiæ, bêdziecie mogli na nich poæwiczyæ strzelanie. (Zwracasz siê w stronê £owców Niewolników.) Przykro mi ch³opaki, macie pecha. (Zaatakuj ³owców niewolników.)}
{502}{}{No, to dopiero bêdzie zabawa! (Zaatakuj Stra¿ników RNK.)}

{600}{}{Uda³o ci siê oczyœciæ to miejsce ze Stra¿ników RNK.}
