{100}{}{To kupa szmat, pod którymi być może znajduje się człowiek.}
{101}{}{Widzisz Ratcha, zapewne właśnie się iskającego.}
{102}{}{To może być człowiek. To może być mutant. Wszystko, co możesz z pewnością powiedzieć, to to, że naprawdę, ale to naprawdę okropnie śmierdzi.}
{103}{}{Złom sprzedaję, złom sprzedaję! Przejrzyj to, zaoferuj coś.}
{104}{}{Jasne, jak chcesz.}
{105}{}{Yy...yyy.}
{106}{}{A wiec, co jest na sprzedaż?}
{107}{}{Wyglądasz na kogoś, kto potrafi dobrze użyć swoich rąk. Masz ręce, prawda?}
{108}{}{Mam 5$. Słyszałeś jakieś ciekawe plotki?}
{109}{}{Żegnaj.}
{110}{}{Widzisz to tam? To jest moja ulubienica - nazywa się Edna. Widzisz, nazywam wszystkie moje rzeczy - są dla mnie jak dzieci. Nie znoszę ich sprzedawać, ale muszę jeść.}
{111}{}{Zadzierasz ze wszystkimi moimi dziećmi!}
{112}{}{Ta, jasne. Masz piątaka. Słyszałeś jakieś ciekawe plotki?}
{113}{}{O-kej czy nie, jesteś po prostu szczególny! Może będę kupować gdzie indziej.}
{114}{}{Pozwól, że przejrzę twój towar jeszcze raz.}
{115}{}{Chyba ja i Edna już sobie pójdziemy.}
{116}{}{Cóż, dzięki Bogu, że ten nieznajomy nie zabrał ciebie dziecko... Moje rzeczy, rozumiesz, są dla mnie jak dzieci.}
{117}{}{Yy - jasne.}
{118}{}{Cóż, chyba już sobie pójdę.}
{119}{}{Potrafię naprawić różne rodzaje sprzętu. Mam dopalacz, nazwałem go Klaudia, pasuje do większości wozów - daje im o wiele więcej mocy. Tylko 1000$. Interesuje cię to?}
{120}{}{Głupi, już o tym rozmawialiśmy.}
{121}{}{Jasne, Klaudia jest w moim typie - czy jak to tam.}
{122}{}{Może coś innego.}
{123}{}{Słyszałem, że tu, w mieście, jest doktorek, który mówi, że ma magiczny lek. Ja go jednak nie biorę...}
{124}{}{Poza tym jest Peklowany Bob. Stary piernik mówi, że odkrył kopalnie złota...}
{125}{}{Panna Dorotka i Toto była tu w ostatnim tygodniu, szukała jakichś części do naprawienia reaktora. Nie mogłem jej jednak pomóc...}
{126}{}{W mieście mówi się, że to, co przytrafiło się Westinowi, wcale nie było wypadkiem. Niektórzy myślą, że jest zbyt dużo podejrzanych obcych dookoła...}
{127}{}{Dzięki za kasę, ale nie wiem już nic więcej.}
{128}{}{Oto następny piątak.}
{129}{}{Mogę zobaczyć twój towar?}
{130}{}{Cóż, dzięki za informacje.}
{131}{}{Cóż, daj mi sześć godzin. Do tego czasu powinienem już to zrobić.}
{132}{}{Zanim to zrobisz, zabiorę ci jeszcze trochę twojego czasu.}
{133}{}{W porządku. Zobaczymy się później.}
{134}{}{Słuchaj, jak będziesz mieć kasę, to wróć. Zapewne wciąż będę ją miał.}
{135}{}{W porządku.}
{136}{}{Żegnaj.}
{137}{}{Gotowe! Klaudia jest już zainstalowana.}
{138}{}{Daj mi jeszcze trochę czasu. Wciąż pracuję nad tą oporną dziewczynką.}
{139}{}{Hej! Nie sądzę, żebym miał dla ciebie jakiś wolny mózg.}
