############################################################
# The following lines are for the description of the NPC
# based on what information the player has about the NPC:
# Name, Appearance, Occupation.
############################################################

# look_at_proc

# description_proc


############################################################
# The following lines are for the responses. Responses are
# in the following format:
# Node Number
# NPC Responses
# Place Responses
############################################################

# Node 000

############################################################
# The following lines are for Tell Me Abouts
#
# The Tell Me Abouts break down into the following:
# Tell Me About Me 970-979
# Tell Me About I Don't Know 980-989
# Tell Me About Subject 1000-1099
# Tell Me About Response 1100-1199
############################################################

############################################################
# Tell Me About Me
############################################################

{970}{}{Tak siê nazywam.}
{971}{}{To w³aœnie ja.}
{972}{}{Nie zadawaj g³upich pytañ. To przecie¿ ja.}

############################################################
# Tell Me About I Don't Know
############################################################

{980}{}{Nic mi o tym nie wiadomo.}
{981}{}{Przykro mi, ale nie wiem.}
{982}{}{Pierwsze s³yszê.}

############################################################
# Tell Me About Subject
############################################################


############################################################
# Tell Me About Response
############################################################
