{100}{}{Cóż, przynajmniej jest już lina.}
{101}{}{To powinno wystarczyć.}
{102}{}{Tej studni brakuje liny i wiadra.}
{103}{}{To już zostało naprawione. Pamiętasz?}
{104}{}{Ta studnia ma już linę, brakuje jej tylko wiadra.}
{200}{}{Widzisz studnię.}
{201}{}{To tylko studnia.}
{202}{}{Po bliższych oględzinach stwierdzasz, że studnia nie działa. Może zdołasz ją naprawić.}
{203}{}{Studnia znowu działa dobrze.}
