{100}{}{Widzisz podejrzliwie zerkaj¹cego stra¿nika.}
{101}{}{Widzisz groŸnie spogl¹daj¹cego stra¿nika.}
{102}{}{Zajmij siê swoimi sprawami.}
{103}{}{Myœlê, ¿e to najwy¿sza pora dla ciebie, aby sobie st¹d pójœæ.}
{104}{}{Nie lubiê twojego widoku.}
{105}{}{Pilnuj siê.}
{106}{}{Witaj, Obywatelu.}
{107}{}{Mi³o mi ciê widzieæ, Obywatelu.}
{108}{}{Pracowity dzieñ, Obywatelu?}
{109}{}{Za tob¹, Obywatelu.}
{110}{}{Witaj wêdrowcze.}
{111}{}{Zajmij siê swoimi sprawami, cudzoziemcze.}
{112}{}{Nie zatrzymywaæ siê.}
{113}{}{Je¿eli chcesz dostaæ siê do Kryptopolis, porozmawiaj z Wallacem.}
{114}{}{Nic siê nie dzieje, Kapitanie.}
{115}{}{Mam tutaj na wszystko oko, Kapitanie.}
{116}{}{Kryptopolis ponad wszystkim, Kapitanie.}
{117}{}{Mi³ego dnia, Kapitanie.}
