{100}{}{Widzisz podejrzliwie zerkającego strażnika.}
{101}{}{Widzisz groźnie spoglądającego strażnika.}
{102}{}{Zajmij się swoimi sprawami.}
{103}{}{Sądzę, że najwyższy czas byś sobie poszedł.}
{104}{}{Nie lubię twojego widoku.}
{105}{}{Tylko uważaj.}
{106}{}{Witam, Obywatelu.}
{107}{}{Miło cię widzieć, obywatelu.}
{108}{}{Pracowity dzień, obywatelu?}
{109}{}{Ty przodem, obywatelu.}
{110}{}{Witaj, wędrowcze.}
{111}{}{Zajmij się swoimi sprawami, przybyszu.}
{112}{}{Przestań się włóczyć bez celu.}
{113}{}{Jeżeli chcesz dostać się do Kryptopolis, porozmawiaj z Wallacem.}
{114}{}{Nic szczególnego, Kapitanie.}
{115}{}{Po prostu miej oczy szeroko otwarte, Kapitanie.}
{116}{}{Kryptopolis na wieki, Kapitanie.}
{117}{}{Dzień dobry, Kapitanie.}
