{100}{}{Widzisz Obywatela w jasno niebieskim ubraniu. Wygl¹da na skafander Przybysza z Krypty, ale nie ma ¿adnego numeru na plecach.}
{101}{}{Widzisz oficer Darrow z Sekcji Udogodnieñ}
{102}{}{Widzisz Obywatela w jasno niebieskim ubraniu. Wygl¹da na skafander Przybysza z Krypty, ale nie ma ¿adnego numeru na plecach.}
{103}{}{::trzask::}
{104}{}{To bohater! Patrzcie!}
{105}{}{A niech mnie! To bohater, tutaj, w Kryptopolis!}
{106}{}{Mi³ego dnia, Kapitanie.}
{107}{}{Kryptopolis ponad wszystkim, Kapitanie.}
{108}{}{Mi³ego dnia, Obywatelu.}
{109}{}{Kryptopolis ponad wszystkim, Obywatelu.}
{110}{}{Mutant! Stra¿! Stra¿!}
{111}{}{Ghul! Stra¿! Stra¿!}
{112}{}{Muszê siê zaj¹æ zamówieniem wiêkszej liczby narzêdzi z Redding.}
{113}{}{Ma³y dzisiaj ruch.}
{114}{}{Ciekawe, czy Randal skoñczy³ ju¿ tê listê zakupów.}
{115}{}{Wydaje siê, ¿e dopiero co da³am Randalowi tê listê towarów.}
{116}{}{Przynajmniej ta robota przebija pracê w Biurze List.}
{117}{}{S³u¿¹cy wci¹¿ zu¿ywaj¹ wiêkszoœæ narzêdzi. Jak bym chcia³a, ¿eby bardziej o nie dbali...}
{118}{}{Przyda³yby mi siê wakacje.}
{119}{}{Biuro Sekcji Udogodnieñ jest w nocy zamkniête... wróæ tu rano. }
{120}{}{W tej chwili przyjmuje towar. Wróæ, gdy otworzymy rankiem.}
{121}{}{Zamkniête. Mo¿esz spróbowaæ w sklepie wielobran¿owym na zewn¹trz, je¿eli ju¿ czegoœ naprawdê potrzebujesz.}
{122}{}{Mogê ci w czymœ pomóc, Kapitanie?}
{123}{}{Mogê ci w czymœ pomóc, Obywatelu?}
{124}{}{Przepraszam, mogê w czymœ pomóc?}
{125}{}{Czym? Dudle-dudle duuuuuuuu}
{126}{}{OdejdŸ, jak gdyby nigdy nic.}
{127}{}{Co to za miejsce?}
{128}{}{Mogê zobaczyæ, co masz na sk³adzie?}
{129}{}{Niczego dziœ nie potrzebujê, dziêki.}
{130}{}{Poczekaj tu chwilê, dobra? Przyprowadzê tu kogoœ, ¿eby ci pokazaæ.}
{131}{}{NIE JA NIE IŒÆ}
{132}{}{Okiiii-dokiiii }
{133}{}{S³uchaj, mo¿e ci siê to przydaæ, na Podmurzu jest taki sklep wielobran¿owy, mo¿esz tam spróbowaæ coœ kupiæ... s³ysza³am, ¿e facet ma wybór prawie tak dobry, jak nasz.}
{134}{}{Ee, dziêki.}
{135}{}{Bêdê robiæ zakupy gdzie mi siê podoba, Zrozumiano?}
{136}{}{Dziêki za odwiedziny. Kryptopolis ponad wszystkim, Obywatelu.}
{137}{}{Dziêki za odwiedziny. Kryptopolis ponad wszystkim, Kapitanie}
{138}{}{Kryptopolis ponad wszystkim, Obywatelu.}
{139}{}{Mi³ego dnia, Obywatelu.}
{140}{}{Biuro A Sekcji Udogodnieñ. Jestem odpowiedzialna za zapotrzebowania na sprzêt ogólny, jak narzêdzia i sprzêt do napraw. Nazywam siê Darrow... Oficer Sekcji Udogodnieñ Darrow. Widzisz coœ, co by ci by³o potrzebne?}
{141}{}{To Biuro A Sekcji Udogodnieñ... Zajmujemy siê dostarczaniem narzêdzi i sprzêtu naprawczego dla miasta. Na pewno to jest miejsce, którego szukasz?}
{142}{}{Mogê zobaczyæ, co masz na sk³adzie?}
{143}{}{Tak, to to miejsce. Czy mogê zobaczyæ, co masz na stanie?}
{144}{}{Niczego dziœ nie potrzebujê, dziêki.}
{145}{}{Nie s¹dzê. Do widzenia.}
{146}{}{Hej! Trzymaj siê od tego z daleka!}
{147}{}{Wystarczy! Zmiataj st¹d!}
{148}{}{Dziêki.}
{149}{}{[dalej]}
