{100}{}{Widzisz cz³owieka w jasnoniebieskim kombinezonie. Strój jest bardzo podobny do tego, który nosi³ Przybysz z Krypty, ale nie ma numeru wypisanego na plecach.}
{101}{}{Widzisz Oficera Udogodnieniowego Holdena.}
{102}{}{Widzisz cz³owieka w jasno niebieskim kombinezonie. Strój jest bardzo podobny do tego, który nosi³ Przybysz z Krypty, ale nie ma numeru wypisanego na plecach.}
{103}{}{::oklaski::}
{104}{}{To TEN cz³owiek! Patrzcie!}
{105}{}{Mój Bo¿e! To TEN cz³owiek, tutaj, w Kryptopolis!}
{106}{}{Dzieñ dobry, Kapitanie.}
{107}{}{Kryptopolis ponad wszystkim, Kapitanie.}
{108}{}{Witaj, Obywatelu.}
{109}{}{Kryptopolis ponad wszystkim, Obywatelu.}
{110}{}{To mutant! Stra¿! Stra¿!}
{111}{}{To ghul! Stra¿! Stra¿!}
{112}{}{Spój¿my... trzy stymulanty i jedno pude³ko Rad-X...}
{113}{}{Nadal muszê zrobiæ ten spis dla Oficera Randalla.}
{114}{}{Hmm... zobaczmy: muszê zobaczyæ, co jest na sk³adzie, zrobiæ spis, sprawdziæ go, i wprowadziæ do systemu...}
{115}{}{Muszê rozejrzeæ siê za paroma zestawami pierwszej pomocy...}
{119}{}{Przykro mi, ale Biuro Udogodnieñ jest zamykane na wieczór.}
{120}{}{Zapraszam ponownie rano!}
{121}{}{Teraz mamy inwentaryzacjê. Otworzymy dopiero jutro rano.}
{122}{}{Czym mogê s³u¿yæ Kapitanie?}
{123}{}{Co mogê dla ciebie zrobiæ, Obywatelu?}
{124}{}{Tak, co to jest?}
{125}{}{Ffy moffe ci pfomuc}
{126}{}{OdejdŸ}
{127}{}{Co to za miejsce?}
{128}{}{Mogê zobaczyæ, co macie na sk³adzie?}
{129}{}{Nic dzisiaj nie wezmê, dziêki.}
{130}{}{Wspaniale, kolejny Cudzoziemiec... Stra¿e! Mamy tutaj Cudzoziemca, którego trzeba eskortowaæ do bramy! Stra¿e!}
{131}{}{NIE LUBIÆ STRA¯E. TY MARTWY}
{132}{}{*He he* Ja pójœæ ze STRA¯E}
{133}{}{Nastêpnym razem zajrzyj do sklepu na zewn¹trz miasta. Powinni mieæ wszystko, czego wy... obcy potrzebujecie.}
{134}{}{Uch, dziêki.}
{135}{}{Bêdê robiæ zakupy gdzie mi siê podoba, Zrozumiano?}
{136}{}{Dziêkujê. Kryptopolis ponad wszystkim, Obywatelu.}
{137}{}{Dziêkujê. Kryptopolis ponad wszystkim, Kapitanie.}
{138}{}{Kryptopolis ponad wszystkim, Obywatelu.}
{139}{}{Mi³ego dnia, Obywatelu.}
{140}{}{To? Ale¿ to jest Biuro Udogodnieñ B, które nadzoruje dystrybucjê leków w tym mieœcie. Jestem Oficer Udogodnieniowy Holden. W czym mogê pomóc, Obywatelu?}
{141}{}{To jest Biuro Udogodnieñ B... zajmujemy siê tutaj dystybucj¹ leków dla Kryptopolis. Chyba nie tego miejsca szukasz?}
{142}{}{Mogê zobaczyæ, co macie na zbyciu?}
{143}{}{Nie, w³asnie tego miejsca szukam. Mo¿esz mi pokazaæ, co macie na sk³adzie?}
{144}{}{Nic nie chcê, dziêki.}
{145}{}{Mo¿e. Do widzenia.}
{150}{}{TO? Alez¿ to jest Biuro Udogodnieñ B, które zarz¹dza przechowywaniem i dystrybucja leków w Kryptopolis. Jestem Oficer Udogodnieniowy Holden. W czym mogê ci dzisiaj pomóc, Kapitanie?}
{151}{}{Hej! Trzymaj siê od tego z daleka!}
{152}{}{Wystarczy! Zmiataj st¹d!}

{153}{}{Dziêki.}
{154}{}{[Dalej.]}
