{100}{}{Widzisz mężczyznę o dzikim spojrzeniu. Ma włosy w nieładzie i potarganą brodę, ale jego ubranie wydaje się być czyste i zadbane.}
{101}{}{Widzisz Thomasa Moore'a.}
{102}{}{Widzisz Thomasa Moore'a. Ma włosy w nieładzie i potarganą brodę, ale jego ubranie wydaje się czyste i zadbane.}
{103}{}{Witaj, przyjazna istoto! Czy znasz już słowo?}
{104}{}{Uurmph}
{105}{}{Ech}
{106}{}{Potrzebie}
{107}{}{Odejdź bez słowa.}
{108}{}{Nie, raczej nie.}
{109}{}{A ty jesteś...?}
{110}{}{Nie. I nie muszę. Żegnam. }
{111}{}{Słowo... To słowo to EGOIZM. Co otrzymamy po dodaniu arogancji? Kryptopolis! Przy całej swojej praworządności, gloryfikuje handel niewolnikami.}
{112}{}{Czemu tu mieszkasz, skoro ci się tu nie podoba?}
{113}{}{Amen, bracie!}
{114}{}{Przykro mi, nie tym razem. Do zobaczenia.}
{115}{}{Sprzedawaj szajbę komuś innemu, kolego... Ja mam jej dosyć.}
{116}{}{Tak! }
{117}{}{Nadszedł CZAS usłyszeć naszych braci, czekających za murami i wpuścić ich! Jesteśmy w stanie ich wyżywić i utrzymać... Nie wolno nam się bogacić, gdy jest tylu BIEDNYCH.}
{118}{}{Słyszę cię!}
{119}{}{Nareszcie ktoś tu mówi do rzeczy! Czemu inni muszą cierpieć, skoro tu można im pomóc?}
{120}{}{To mi wystarczy. Żegnaj.}
{121}{}{Gdy patrzę na ciebie, widzę SIŁĘ. Widzę WIARĘ. Czy oczy mnie zwodzą? Czy też widzą pokrewną duszę, która jest po mojej stronie?}
{122}{}{A pewnie!}
{123}{}{Tak! Wiem, że już CZAS... Czas, by to miasto, zbudowane na grzechu i niewolnictwie, otworzyło bramy dla wszystkich! }
{124}{}{Muszę lecieć. Miło było z tobą rozmawiać... Eee, Miło było cię słuchać.}
{125}{}{Więc pozwól, że zapytam - jak daleko posuniesz się, by rozpowszechniać słowo?}
{126}{}{To zależy od tego, ile masz kasy... "Przyjacielu."}
{127}{}{Tak daleko, jak trzeba... Żadna odległość nie jest zbyt wielka, gdy sprawa jest słuszna, a słowo prawdziwe. Zrobię to, co trzeba!}
{128}{}{Nie podoba mi się kierunek, w którym zmierza ta rozmowa. Miłego dnia.}
{129}{}{Nawet, jeśli oznacza to wygnanie z tej oazy?}
{130}{}{To żadna oaza, bracie. To miasto, zbudowane na egoizmie i chciwości. Trzeba ratować je przed nim samym... Czy w świetle tego wygnanie to faktycznie kara? Nie wydaje mi się.}
{131}{}{Wszystko, co potrzeba, by uwolnić braci z okowów!}
{132}{}{Nie wiem... A co mam według ciebie zrobić?}
{133}{}{Hmmm. Cóż, skoro tak stawiasz sprawę, to chyba nie. Miłego dnia.}
{134}{}{(Nachylając się.) Mam tu teczkę... Z informacjami ważnymi dla naszej sprawy. Czy dostarczysz ją dla mnie do Nowego Reno? Sam bym to zrobił, ale tutejsi Obywatele mnie obserwują...}
{135}{}{Więc, przyznajesz się do związków z Nowym Reno, tak? To będzie cię słono kosztowało... "Przyjacielu."}
{136}{}{Jasne. Daj mi ją.}
{137}{}{Nie, dziękuję... To trochę zbyt ryzykowne. Nie wchodzę w to.}
{138}{}{Proszę... Dostarcz ją do Johna Bishopa z Nowego Reno. Uważaj na siebie, moje dziecko, i głoś słowo.}
{139}{}{Dostarczyć ją do Johna Bishopa? Nie ma sprawy.}
{140}{}{Moje nazwisko? Jestem Thomas Moore, kaznodzieja słowa i prawdy. A co ciebie do mnie sprowadza? Czy i TY poszukujesz słowa?}
{141}{}{Słowa?}
{142}{}{Ee, nie, nie dzisiaj, dzięki. Żegnam.}
{143}{}{Nawet ci, którzy zdają się być niewinni, mogą zwieść głoszącego słowo... Skąd mam wiedzieć, że NAPRAWDĘ w nie wierzysz?}
{144}{}{Uwierzysz, jak wsadzę ci nogę w tyłek!}
{145}{}{NAPRAWDĘ wierzę, bracie. Jak mogę udowodnić moje oddanie?}
{146}{}{Wiem, że to miasto powstało na fundamencie grzechu i niewolnictwa. Tylko praworządni mogą je naprawić!}
{147}{}{Wiesz, może po prostu pogadamy później.}
{148}{}{Pogańskie ignoranctwo! Masz uszy, ale nie słuchasz! Masz oczy, ale są one ślepe! Zejdź mi z oczu, brudna świnio!}
{149}{}{Brudna... Ee... Świ... Co? Nikt nie będzie tak do mnie mówić! Mam nadzieję, że nie masz rodziny, która by za tobą tęskniła, trupie...}
{150}{}{Nikt nie będzie tak do mnie mówić! A już na pewno nie jakiś domorosły kaznodzieja. Chyba czas, byś dostał nauczkę, trupie.}
{151}{}{Spokojnie. Już sobie idę.}
{152}{}{Hmmmmmm. Strzec się trzeba węży, które słowa prawdy powtarzają, lecz fałsz i obłudę w swych sercach kryją.}
{153}{}{Amen, bracie! }
{154}{}{Skoro nie chcesz mi zaufać, odejdę. Żegnam.}
{155}{}{Eee... Jasne. Może pogadamy później.}
{156}{}{Co?! Jak ŚMIESZ mnie szantażować, ty... Ty... (krzywi się) ...Zamieniam się w słuch.}
{157}{}{Porozmawiajmy o zapłacie, dobrze?}
{158}{}{Cóż... Komu należy głosić kazania, jeśli nie tym, którzy ich najbardziej potrzebują?}
{159}{}{Chyba masz rację. Kim jesteś?}
{160}{}{Udowodnij je, bracie! Głoś słowo!}
{161}{}{Dokładnie! To miasto powstało na fundamencie grzechu i niewolnictwa. Tylko praworządni mogą je naprawić!}
{162}{}{Ee... Racja. Cóż, miło było pogadać. Żegnam.}
{163}{}{Masz... W walizce jest numer mojego konta. Zanieś ją do Johna Bishopa z Nowego Reno, a on pozwoli ci skorzystać z konta.}
{164}{}{Zapomnij. I tak cię wsypie.}
{165}{}{No to olej wypłatę. Nie wybiorę się do Reno.}
{166}{}{Świetnie! Ale lepiej, by mi się to opłaciło.}
{167}{}{Widzę, że natura już cię ukarała, łowco niewolników. Może któregoś dnia się nawrócisz.}
{168}{}{Ech... Nie nadajesz się. Uważaj na siebie na Pustkowiu.}
{169}{}{Urf}
{170}{}{I co? Udało ci się przemyśleć sprawę??}
{171}{}{Owszem i wyszło mi, że utrzymanie twojej tajemnicy będzie cię dużo kosztowało. Rozumiesz?}
{172}{}{Widzę światło, bracie... Co mam zrobić?}
{173}{}{Przykro mi, ale nie. Miłego dnia.}
{174}{}{Ech? Co ty tu robisz? Nie udało ci się dostarczyć...}
{175}{}{... teczki Bishopowi? Cóż, udało się. Tyle, że gdy przeczytał liścik, który mu w niej zostawiłeś, to próbował mnie ZABIĆ. Zabawne, nie? Mam nadzieję, że pogodziłeś się ze swoim stwórcą.}
{176}{}{Udało się, ale oto jestem z powrotem, by cię podziurawić i przysypać ziemią.}
{177}{}{Chcę cię tylko podrażnić. Cześć.}
{178}{}{Ach! Witaj ponownie! Jak mogę ci dzisiaj pomóc?}
{179}{}{Co wiesz o RNK?}
{180}{}{Mam pytanie: skąd w Kryptopolis niewolnicy? To podobno wolne miasto.}
{181}{}{Chcę usłyszeć słowo, bracie!}
{182}{}{To miasto zbudowano na grzechu i niewolnictwie, a ja chcę to naprawić!}
{183}{}{Dzięki, ale dziś nie skorzystam.}
{184}{}{Wiem, że starają się o prawdę i sprawiedliwość, a my nawet nie kiwamy palcem, by im pomóc.}
{185}{}{Cóż możemy zrobić?}
{186}{}{To brzmi jak zdrada.}
{187}{}{Szkoda. Żegnam.}
{188}{}{Możemy otworzyć bramy i wpuścić ich! Potrzebują naszej pomocy, a my nie wyciągamy do nich ręki!}
{189}{}{Amen! Zaawansowana technologia Kryptopolis powinna być rozpowszechniana, nie ukrywana.}
{190}{}{Hmm... No nie wiem. Jest tu całkiem dobrze. Czy naprawdę są nam tu potrzebni? W końcu obniżą nam standard życia... Może nawet nas zatrują.}
{191}{}{Hmmm. Cóż, warto to przemyśleć. Żegnam.}
{192}{}{Nie odpowiem na to, gdyż miasto wyrosłe dzięki niewolnictwu, nigdy nie będzie naprawdę wolne.}
{193}{}{Owszem, ale nieźle się wzbogacą, nie?}
{194}{}{Twoje słowa... Coś we mnie poruszyły. Może uwolnienie niewolników i przyjęcie ich do społeczności będzie dla Kryptopolis najlepsze.}
{195}{}{Powinniśmy wyzwolić niewolników i traktować ich jak naszych braci!}
{196}{}{Ej, nie wciskaj mi tego braminiego gówna. Niewolnictwo... i Kryptopolis... Oba będą jeszcze długo istnieć.}
{197}{}{Interesujące. Może jeszcze porozmawiamy.}
{198}{}{Widzę, że trudnisz się handlem ludźmi. Komuś takiemu jak ty, nie ma NIC do powiedzenia.}
{199}{}{Uurmph}
{200}{}{Ech}
{201}{}{Potrzebie}
{202}{}{Odejdź bez słowa.}
{203}{}{Tylko udaję łowcę, żeby zdobyć informacje.}
{204}{}{Cóż, chcę o coś zapytać: skąd w Kryptopolis niewolnicy? To podobno wolne miasto.}
{205}{}{Szlachetny cel uświęca nawet najgorsze środki.}
{206}{}{No to w porządku. Cześć.}
{207}{}{Miło wiedzieć, że nietolerancja nadal ma się dobrze. Żegnam.}
{208}{}{Udając łowcę, nie jest się lepszym niż będąc nim. Odejdź.}
{209}{}{Ale teraz rozumiem swoją pomyłkę!}
{210}{}{Dość tego. Czas cię rozkroić i zobaczyć, co masz w środku...}
{211}{}{No to trudno.}
{212}{}{Nie mam o czym rozmawiać z kimś w tak marnym stanie. Odejdź.}
{213}{}{Chcesz marnego stanu? POKAŻE ci marny stan...}
{214}{}{Rozumiem już moje błędy. Chcę za nie odpokutować i usłyszeć słowo!}
{215}{}{Moje serce zostało rozdarte, gdy ujrzało krzywdy, wyrządzane ludziom przez ludzi!}
{216}{}{W porządku. }
{217}{}{Witaj ponownie! Czy informacje zostały dostarczone zgodnie z moja prośbą?}
{218}{}{Witaj ponownie! Jak mogę ci dzisiaj pomóc?}
{219}{}{Nie chrzan, "Kocurze." Wiem wszystko o tobie i twoich "przyjaciołach" z RNK.}
{220}{}{Czemu pracujesz dla RNK? Wydawałeś się być człowiekiem honoru.}
{221}{}{Tak... Słuchaj, Bishop powiedział, że pracujesz dla RNK. Czy to prawda?}
{222}{}{Tak, chcę tylko dać ci znać, że sprawa załatwiona.}
{223}{}{Cieszy mnie, że moje słowa znalazły miejsce w twym sercu. Może nasze ścieżki jeszcze się skrzyżują.}
{224}{}{Być może. Nie trać wiary, bracie.}
{225}{}{Żegnaj.}
{226}{}{RNK przyniesie honor i porządek całej Kalifornii, a Kryptopolis pomoże to umożliwić! Pomyśl, ile dobra można zdziałać, mając dostęp do technologii Kryptopolis!}
{227}{}{Nie wierzę. Myślę, że muszę cię wsypać, chyba że chcesz kupić moje milczenie.}
{228}{}{Ale ta technologia należy do Kryptopolis. Inni nie mają do niej prawa.}
{229}{}{Zdrada i kłamstwa nie przyniosą nic dobrego. Kryptopolis okłamuje samo siebie od lat... Nie idź za jego przykładem, dobrze?}
{230}{}{Hmm. Muszę o tym pomyśleć.}
{231}{}{Masz rację. Przepraszam za chwilę zwątpienia.}
{232}{}{WSZYSCY ludzie mają prawo do osiągnięć starego świata. Technologia trzeba się dzielić, nie ja ukrywać.}
{233}{}{Po prostu tego nie chwytasz, prawda? Może porządny, staromodny kopniak w tyłek przemówi ci do rozsądku.}
{234}{}{Tak, tak, daruj sobie ten kit pod tytułem "jestem-bardziej-święty-niż-ty". Dawaj kasę, albo cię wydam.}
{235}{}{Muszę o tym pomyśleć. Cześć.}
{236}{}{Proszę, dostarcz tę teczkę do Nowego Reno. Liczy się czas!}
{237}{}{Co zrobić? Głoś słowo, to wystarczy. Krocz ostrożnie i z rozmysłem po Pustkowiu. Gdy słowo będzie ci światłem, nie zbłądzisz.}
{238}{}{Dziękuję, bracie. Uczynię jak mówisz.}
{239}{}{Czy znasz już słowo?}
{240}{}{Poznaj słowo! Słowo cię uwolni!}
{241}{}{Niewolnictwo pogrąży to miasto!}
{242}{}{Trzeba otworzyć bramy Kryptopolis i przyjąć tych z zewnątrz!}
{243}{}{Czemuż nie podzielimy się naszym bogactwem?! }
{244}{}{Czyż nie słyszysz płaczu tych, którzy cierpią za murami?!}
