{100}{}{Widzisz małego chłopca.}
{101}{}{Widzisz małą dziewczynkę.}
{102}{}{Uśmiecha się na twój widok.}
{103}{}{Uśmiecha się na twój widok.}
{104}{}{Spogląda na ciebie niepewnie.}
{105}{}{Spogląda na ciebie niepewnie.}
{106}{}{Krzywo na ciebie patrzy.}
{107}{}{Krzywo na ciebie patrzy.}
{200}{}{Dziękuję, że Pan nam pomógł!}
{201}{}{Hura, jesteśmy bezpieczni!}
{202}{}{Dziękuję, że Pani nam pomogła!}
{203}{}{Hura, jesteśmy bezpieczni!}
{204}{}{Boje się ciebie!}
{205}{}{Jesteś tu żeby nam pomóc?}
