{100}{}{Widzisz terminal edukacyjny Kryptopolis.}
{101}{}{Ten komputer wydaje siê byæ systemem ucz¹cym. Z boku jest Pip-Boy.}
{102}{}{Widzisz komputerowy system ucz¹cy Kryptopolis.}
{103}{}{Mieszasz trochê przy komputerze, ale musisz u¿yæ jakichœ umiejêtnoœci naukowych, by znaleŸæ tam coœ po¿ytecznego.}
{104}{}{Spêdzasz trochê czasu przeszukuj¹c archiwa.}
{105}{}{Spêdzasz trochê czasu przegl¹daj¹c archiwa, lecz nie znajdujesz nic wa¿nego.}
