{100}{}{Nie widzisz ¿adnej mo¿liwoœci u¿ycia emitera.}
{101}{}{Nie widzisz ¿adnej mo¿liwoœci u¿ycia pola si³owego.}
{102}{}{Pora¿a ciê os³abione pole si³owe.}
{103}{}{ ulega pora¿eniu przez os³abione pole si³owe.}
{107}{}{Pora¿a ciê pole si³owe.}
{108}{}{ ulega pora¿eniu przez pole si³owe.}
{109}{}{Nie udaje ci siê wy³¹czyæ pola si³owego.}
{110}{}{ nie daje rady wy³¹czyæ pola si³owego.}
{111}{}{S³yszysz ha³aœliwe dŸwiêki dochodz¹ce z g³oœnika: Uwaga! Wykryto Intruza! Uruchomiæ Systemy Bezpieczeñstwa.}
{112}{}{Wy³¹czasz pole si³owe.}
{113}{}{ wy³¹cza pole si³owe.}
{114}{}{W³¹czasz pole si³owe.}
{115}{}{ w³¹cza pole si³owe.}
{116}{}{Emiter pola si³owego zosta³ zniszczony.}
