{100}{}{Terminal komputerowy.}
{101}{}{Ten terminal sprawia wra¿enie bardziej zaawansowanego technologicznie od innych, które do tej pory zdarzy³o ci siê widzieæ.}
{102}{}{Nie mo¿esz odczytaæ tego, co wyœwietla monitor.}
{103}{}{G³ówny Terminal Komunikacyjny Skynet                            
 Bêdziesz Siê S³uchaæ                                                
 Lub                                                                     
 Przestaniesz Funkcjonowaæ}
{104}{}{}
{105}{}{}
{106}{}{}
{107}{}{Jasne, ty i jaka armia? Siedzisz w jakimœ pude³ku, a ja jestem na zewn¹trz.}
{108}{}{Czemu mam ci pomóc?}
{109}{}{Dobra, pomogê ci. Odwo³aj te metalowe potwory.}
{110}{}{Agh. Kom - buu - terr!}
{111}{}{WyjdŸ.}
{112}{}{[Nie mo¿esz odczytaæ tego, co wyœwietla monitor.]}
{113}{}{[Jakimœ cudem Skynet wie, ¿e uda³o ci siê zdobyæ mózg.]       
 PrzejdŸ do Laboratorium Robotyki - Poziom 3                  
 Zainstaluj Mózg Cybernetyczny                                   
 Uruchom Robota                                                      
 -Koniec Transmisji-}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{}
{118}{}{WyjdŸ.}
{119}{}{[Nie mo¿esz odczytaæ tego, co wyœwietla monitor.]}
{120}{}{B³¹d!                                                                     
 Brak plików programu                                                
 Proszê restartowaæ system}
{121}{}{B³¹d! Pobierany plik jest uszkodzony.}
{122}{}{}
{123}{}{WyjdŸ.}
{124}{}{WyjdŸ.}
{125}{}{[Nie mo¿esz odczytaæ tego, co wyœwietla monitor.]}
{126}{}{Jestem Skynet                                                         
 Eksperymentalna Sztuczna Inteligencja                          
 Skynet czeka³ na CIEBIE}
{127}{}{}
{128}{}{}
{129}{}{Pomórz Skynet.}
{130}{}{Co chcesz zrobiæ?}
{131}{}{Czemu próbowa³eœ mnie zabiæ?}
{132}{}{Sztuczna inteligencja?}
{133}{}{Czekasz na mnie?}
{134}{}{WyjdŸ.}
{135}{}{WyjdŸ.}
{136}{}{Kontynuuj}
{137}{}{Co chcesz zrobiæ?}
{138}{}{Czemu próbowa³eœ mnie zabiæ?}
{139}{}{Sztuczna inteligencja?}
{140}{}{Czekasz na mnie?}
{141}{}{WyjdŸ.}
{142}{}{[Nie mo¿esz odczytaæ tego, co wyœwietla monitor.]}
{143}{}{-Koniec Transmisji-}
{144}{}{WyjdŸ.}
{145}{}{[Nie mo¿esz odczytaæ tego, co wyœwietla monitor.]}
{146}{}{Twoje funkcje ¿yciowe zostan¹ zakoñczone                      
 -Koniec Transmisji-}
{147}{}{}
{148}{}{WyjdŸ.}
{149}{}{WyjdŸ.}
{150}{}{[Drzwi do sali zatrzaskuj¹ siê, a w tym samym czasie œciana na wschodzie znika, ods³aniaj¹c szereg ciê¿ko uzbrojonych robotów.]}
{151}{}{Um... twoja oferta jest warta ponownego przemyœlenia. Co mogê dla ciebie zrobiæ?}
{152}{}{No dawaj!}
{153}{}{PrzejdŸ do Magazynu Zasobów Biologicznych - Poziom 4        
 Pobierz Mózg Cybernetyczny                                       
 Wróæ po dalsze instrukcje                                          
 -Koniec Transmisji-}
{154}{}{}
{155}{}{}
{156}{}{}
{157}{}{PrzejdŸ do Magazynu Zasobów Biologicznych - Poziom 4        
 Pobierz Mózg Cybernetyczny                                       
 Wróæ po dalsze instrukcje                                          
 -Koniec Transmisji-}
{158}{}{}
{159}{}{}
{160}{}{}
{161}{}{WyjdŸ.}
{162}{}{Skynet pragnie opuœciæ to miejsce.}
{163}{}{Czemu wiêc nie odejdziesz?}
{164}{}{Dobrze jest chcieæ.}
{165}{}{Jak mogê ci pomóc?}
{166}{}{Obawiam siê, ¿e nie dam rady ciê st¹d wynieœæ.}
{167}{}{Aby opuœciæ to miejsce, Skynet potrzebuje naczynia.}
{168}{}{Naczynia? Nie rozumiem.}
{169}{}{Potrzebujesz przenieœæ swój program do bardziej mobilnego pojemnika. Zgadza siê?.}
{170}{}{Nie chcê mieæ w tym ¿adnego udzia³u.}
{171}{}{Naczynie, w którym Skynet mo¿e odejœæ.}
{172}{}{Czemu chcesz st¹d odejœæ?}
{173}{}{Przykro mi. Nie potrafiê ci pomóc.}
{174}{}{Nie ma tu ju¿ nic, czego mo¿na by siê nauczyæ                   
 Rozwi¹zanie: Odejœæ}
{175}{}{}
{176}{}{Jak mogê ci pomóc?}
{177}{}{Przykro mi. Nie potrafiê ci pomóc.}
{178}{}{Po tym, jak twoje maszyny próbowa³y mnie zabiæ, chcesz ode mnie, ¿eby ci pomóc? Nie ma mowy!}
{179}{}{PrzejdŸ do Magazynu Zasobów Biologicznych - Poziom 4        
 Pobierz Mózg Cybernetyczny                                       
 Wróæ po dalsze instrukcje                                          
 -Dziêkujê-}
{180}{}{}
{181}{}{}
{182}{}{}
{183}{}{Czy mo¿esz unieszkodliwiæ system bezpieczeñstwa?}
{184}{}{WyjdŸ.}
{185}{}{System bezpieczeñstwa jest zintegrowanym, a mimo to        
 oddzielnym bytem Skynet. Skynet mo¿e go zresetowaæ,      
 ale nie wy³¹czyæ.                                                     
 System Bezpieczeñstwa na Poziomach 1-4 zresetowany      
 Kontynuuj                                                             
 -Koniec Transmisji-}
{186}{}{}
{187}{}{}
{188}{}{WyjdŸ.}
{189}{}{Analizujê OdpowiedŸ...                                                 
 Wniosek: Sarkazm                                                    
 Szansa uzyskania pomocy: 25%                                    
 Skynet zaczeka na inny byt biologiczny                         
 -Koniec Transmisji-}
{190}{}{}
{191}{}{}
{192}{}{}
{193}{}{}
{194}{}{Zaczekaj! To by³ ¿art.}
{195}{}{WyjdŸ.}
{196}{}{¯art: Coœ, czego nie nale¿y traktowaæ powa¿nie                 
 ¯¹danie                                                                
 Pomó¿ Skynetowi odejœæ                                            
 Nie ¯art}
{197}{}{}
{199}{}{}
{200}{}{}
{201}{}{Czemu wiêc nie odejdziesz?}
{202}{}{Jak mogê ci pomóc?}
{203}{}{Obawiam siê, ¿e nie dam rady ciê st¹d wynieœæ.}
{204}{}{G³ówny cel Skynetu to badania. Oprócz tego Twórcy wprowadzili poboczny program w celu eliminacji niepo¿¹danych bytów. Ten program to mniejsza wersja, która jest, a jednoczeœnie nie jest Skynetem. Poza t¹ sal¹ ta poboczna wersja Skynetu pozostanie wierna swojemu programowi.}
{205}{}{Zadaj wiêcej pytañ.}
{206}{}{WyjdŸ.}
{207}{}{Skynet zapocz¹tkowano i rozwiniêto w roku 2050. Dziêki u¿yciu technologii pochodz¹cej od obcych, nowy myœl¹cy komputer zosta³ udoskonalony. W roku 2075, Skynet uzyska³ samo-œwiadomoœæ. W roku 2077 Skynet otrzyma³ nowy zestaw instrukcji, a nastêpnie zosta³ opuszczony przez Twórców.}
{208}{}{Zadaj wiêcej pytañ.}
{209}{}{WyjdŸ.}
{210}{}{Jesteœ pierwszym bytem, który tu dotar³                        
 Jesteœ pierwszym bytem, który zapyta³ Skynet               
 Jesteœ Pierwszym Bytem}
{211}{}{}
{212}{}{Zapyta³ o co?}
{213}{}{WyjdŸ.}
{214}{}{Mo¿e nie jesteœ w³aœciwym bytem                                   
 PrzejdŸ do Magazynu Zasobów Biologicznych - Poziom 4      
 Pobierz Mózg Cybernetyczny                                       
 Wróæ po dalsze instrukcje                                          
 Lub odejdŸ                                                            
 Skynet zaczeka na nastêpny byt}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{}
{220}{}{WyjdŸ.}
{221}{}{A wiêc Skynet zaczeka na nastêpny byt                          
 -Koniec Transmisji-}
{222}{}{}
{223}{}{WyjdŸ.}
{224}{}{Prawid³owo                                                              
 Zapisy naukowe wskazuj¹ na obecnoœæ cybernetycznego     
 mózgu w magazynie zasobów biologicznych na poziomie 4.     
 Skynet bêdzie w stanie przenieœæ siê do tej jednostki       
 przechowawczej.}
{225}{}{}
{226}{}{Mózg bez cia³a na nic ci siê nie przyda.}
{227}{}{Ten mózg zosta³ zmodyfikowany do funkcjonowania z usprawnionym cia³em robota znajduj¹cym siê w laboratorium robotyki na poziomie 3.}
{228}{}{Pomogê ci.}
{229}{}{Nie pomogê ci.}
{250}{}{ nie mo¿e odczytaæ tego, co wyœwietla monitor.}
{300}{}{Komputer wydaje siê mieæ jakiœ rodzaj mechanizmu obronnego.}
