{100}{}{Widzisz stół do gry w oczko.}
{101}{}{Widzisz krupiera rozdającego karty do gry w oczko.}
{102}{}{Chcesz zagrać w oczko? Minimalna stawka wynosi $}
{103}{}{.}
{104}{}{Jasne.}
{105}{}{Nie, dziękuję.}
{106}{}{Cso czko?}
{107}{}{Przykro mi, ale chyba nie masz sumy wystarczającej do obstawienia minimalnej stawki. Wróć, kiedy zdobędziesz trochę pieniędzy.}
{108}{}{Dobrze, wszystkie minimalne stawki zostały wyłożone.}
{109}{}{[zakład]}
{110}{}{To jest stół do gry w oczko. Minimalna stawka to $}
{111}{}{.}
{112}{}{Wyciągasz }
{113}{}{ z }
{114}{}{, }
{115}{}{ i }
{116}{}{. Pkt.: }
{117}{}{. Oczko}
{118}{}{. Bankrut}
{119}{}{.}
{120}{}{Krupier ma }
{121}{}{[dalej]}
{122}{}{[tasując w międzyczasie] Może jeszcze raz?}
{123}{}{Przykro mi, ale twój limit został już osiągnięty. Muszę prosić cię o opuszczenie tego miejsca.}
{124}{}{Wygrywasz rozdanie.}
{125}{}{Krupier wygrywa rozdanie.}
{126}{}{Gra jest nierozstrzygnięta.}
{127}{}{Pewnie, nie ma sprawy.}
{128}{}{Zaraz pokażę ci mój limit.}
{129}{}{Nie możesz już tu grać. Proszę odejść.}
{130}{}{Oooch, przepraszam.}
{131}{}{Wygrywasz $}
{132}{}{.}
{201}{}{asa}
{202}{}{dwa}
{203}{}{trzy}
{204}{}{cztery}
{205}{}{pięć}
{206}{}{sześć}
{207}{}{siódemka}
{208}{}{osiem}
{209}{}{dziewięć}
{210}{}{dziesięć}
{211}{}{waleta}
{212}{}{królową}
{213}{}{króla}
{251}{}{kier}
{252}{}{karo}
{253}{}{pik}
{254}{}{trefl}
