{100}{}{Férfi hős}
{101}{}{}
{200}{}{Hősnő}
{201}{}{}
{300}{}{Falusi ember}
{400}{}{Falusi ember}
{500}{}{Radskorpió}
{501}{}{Egy kis, mutáns skorpió.}
{600}{}{Radskorpió}
{601}{}{Egy mutáns skorpió.}
{700}{}{Halálkarom}
{701}{}{Egy halálkarom kölyök.}
{800}{}{Halálkarom}
{801}{}{Egy halálkarom kölyök.}
{900}{}{Kutya}
{901}{}{Egy kutya, valószínűleg keverék.}
{1000}{}{Brahminok}
{1001}{}{Egy kétfejű, mutáns tehén.}
{1100}{}{Patkány}
{1101}{}{Egy tipikus, nagy patkány.}
{1200}{}{Imádkozó-sáska}
{1201}{}{Egy mutáns imádkozó-sáska.}
{1300}{}{Törzsfőnök}
{1400}{}{Hakunin}
{1500}{}{Mynoc}
{1600}{}{Húsevő növény}
{1601}{}{Egy húsevő növény.}
{1700}{}{Csinos rabszolga}
{1800}{}{Jóképű rabszolga}
{1900}{}{Egészséges rabszolga}
{2000}{}{Egészséges rabszolga}
{2100}{}{Erős rabszolga}
{2200}{}{Erős rabszolga}
{2300}{}{Harci rabszolga}
{2400}{}{Harci rabszolga}
{2500}{}{Ügyes rabszolga}
{2600}{}{Ügyes rabszolga}
{2700}{}{Sima rabszolga}
{2800}{}{Sima rabszolga}
{2900}{}{Anna}
{3000}{}{Vállas bandatag}
{3100}{}{Vállas bandatag}
{3200}{}{Közelharci bandatag}
{3300}{}{Közelharci bandatag}
{3400}{}{Fürge bandatag}
{3500}{}{Fürge bandatag}
{3600}{}{Fegyveres bandatag}
{3700}{}{Fegyveres bandatag}
{3800}{}{Nehézfegyveres bandatag}
{3900}{}{Nehézfegyveres bandatag}
{4000}{}{Kemény őr}
{4100}{}{Kemény őr}
{4200}{}{Közelharci őr}
{4300}{}{Közelharci őr}
{4400}{}{Fürge őr}
{4500}{}{Fürge őr}
{4600}{}{Fegyveres őr}
{4700}{}{Fegyveres őr}
{4800}{}{Nehézfegyveres őr}
{4900}{}{Nehézfegyveres őr}
{5000}{}{Árva (fiú)}
{5100}{}{Árva (lány)}
{5200}{}{Gyerek (fiú)}
{5300}{}{Gyerek (lány)}
{5400}{}{Lúzer!}
{5500}{}{Lúzer!}
{5600}{}{Rossz kereskedő}
{5700}{}{Rossz kereskedő}
{5800}{}{Átlagos kereskedő}
{5900}{}{Átlagos kereskedő}
{6000}{}{Ügyes kereskedő}
{6100}{}{Ügyes kereskedő}
{6200}{}{Vic}
{6300}{}{Gyenge paraszt}
{6400}{}{Gyenge paraszt}
{6500}{}{Átlagos paraszt}
{6600}{}{Átlagos paraszt}
{6700}{}{Erős paraszt}
{6800}{}{Erős paraszt}
{6900}{}{Gyenge közelharci őr}
{7000}{}{Gyenge közelharci őr}
{7100}{}{Gyenge fegyveres őr}
{7200}{}{Gyenge fegyveres őr}
{7300}{}{Javítórobot}
{7400}{}{Javítórobot v2.}
{7500}{}{Robotagy}
{7600}{}{Lebegő szem robot}
{7700}{}{Őrrobot}
{7800}{}{Őrrobot v2.}
{7900}{}{Robotagy}
{8000}{}{Kicsi gekkó}
{8100}{}{Kis, erős gekkó}
{8200}{}{Vadkutya}
{8201}{}{Egy veszett korcs.}
{8300}{}{Aranygekkó}
{8400}{}{Halálkarom}
{8500}{}{Halálkarom kölyök}
{8600}{}{Erős aranygekkó}
{8700}{}{Lynette}
{8800}{}{Dr. Troy}
{8900}{}{John Cassidy}
{9000}{}{Gregory}
{9100}{}{Polgár (nő)}
{9200}{}{Polgár (férfi)}
{9300}{}{Felsőbb rangú Polgár (n)}
{9400}{}{Felsőbb rangú Polgár (f)}
{9500}{}{Prémvadász}
{9600}{}{Prémvadász}
{9700}{}{Sulik}
{9800}{}{Maida Buckner}
{9900}{}{Torr}
{10000}{}{Púpos}
{10100}{}{Világító reaktormunkás}
{10200}{}{Reaktormunkás ghoul}
{10300}{}{Reaktor-őr}
{10400}{}{Zomak}
{10500}{}{Skeeter}
{10600}{}{Vész}
{10700}{}{Lenny}
{10800}{}{Wooz}
{10900}{}{Harold}
{11000}{}{Vakondpatkány}
{11100}{}{Szívós vakondpatkány}
{11200}{}{Disznópatkány}
{11300}{}{Szívós disznópatkány}
{11400}{}{Gyenge Brahmin}
{11401}{}{Egy kétfejű, mutáns tehén.}
{11500}{}{Egy Erőpáncél (ne használd)}
{11600}{}{Mutáns patkány}
{11601}{}{Egy szívós, mutáns patkány.}
{11700}{}{Mutáns vakondpatkány}
{11701}{}{Egy szívós, mutáns patkány.}
{11800}{}{Mutáns disznópatkány}
{11801}{}{Egy szívós, mutáns disznópatkány.}
{11900}{}{Szupermutáns}
{12000}{}{Izmos mutáns}
{12100}{}{Melchior}
{12200}{}{Hero Andro (don't use)}
{12300}{}{Hero Andro (don't use)}
{12400}{}{Hero Male (don't use)}
{12500}{}{Hero Female (don't use)}
{12600}{}{Hero Male (don't use)}
{12700}{}{Hero Female (don't use)}
{12800}{}{Hero Male (don't use)}
{12900}{}{Hero Female (don't use)}
{13000}{}{Hero Male (don't use)}
{13100}{}{Hero Female (don't use)}
{13200}{}{Hero Male (don't use)}
{13300}{}{Hero Female (don't use)}
{13400}{}{Menedékvárosi őr}
{13500}{}{Menedékvárosi őr}
{13600}{}{Kiberkutya}
{13700}{}{ÚKK-s őr}
{13800}{}{ÚKK-s őr}
{13900}{}{ÚKK-s közelharci őr}
{14000}{}{Hajcsár őr}
{14100}{}{Hajcsár felügyelő}
{14200}{}{Mester kereskedő}
{14300}{}{Mester kereskedő}
{14400}{}{Tandi}
{14500}{}{Zsoldos}
{14600}{}{Ratch}
{14700}{}{Doofus}
{14800}{}{Mikey}
{14900}{}{ÚKK-s csapos}
{15000}{}{Boltos}
{15100}{}{Gruthar}
{15200}{}{Goris}
{15300}{}{Vakondpatkány harcos}
{15400}{}{Vakondpatkány harcos}
{15500}{}{Vakondpatkány harcos}
{15600}{}{Vakondpatkány harcos}
{15700}{}{Vakondpatkány harcos}
{15800}{}{Vakondpatkány harcos}
{15900}{}{Szokványos ghoul}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Jones doki}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Öcsi}
{16600}{}{Rondo}
{16700}{}{Ranchsegéd}
{16800}{}{Ranchsegéd}
{16900}{}{Ranchsegéd}
{17000}{}{Kidobóember}
{17100}{}{Kidobóember}
{17200}{}{Gyenge Mr.Handy}
{17300}{}{Szokványos világító ghoul}
{17400}{}{Dar}
{17500}{}{Dalia}
{17600}{}{Gordon}
{17700}{}{test (don't use)}
{17800}{}{Reaktormunkás ghoul}
{17900}{}{Szokványos ghoul}
{18000}{}{Matt}
{18100}{}{Fejvadász Vezető (1-6)}
{18200}{}{Fejvadász (1-6)}
{18300}{}{fejvadász vezető(7-12)}
{18400}{}{Fejvadász (7-12)}
{18500}{}{Fejvadász (7-12)}
{18600}{}{Fejvadász Vezető (13-18)}
{18700}{}{Fejvadász (13-18)}
{18800}{}{Fejvadász (13-18)}
{18900}{}{Fejvadász Vezető (19-?)}
{19000}{}{Fejvadász (19-?)}
{19100}{}{Bess}
{19101}{}{Egy kétfejű, mutáns tehén.}
{19200}{}{Balthas}
{19300}{}{Grisham}
{19400}{}{Phil}
{19500}{}{Csirke}
{19600}{}{Karl}
{19700}{}{Jonny}
{19800}{}{Jo}
{19900}{}{Zeke}
{20000}{}{Mészáros}
{20100}{}{Petey}
{20200}{}{Törzsbéli vadász}
{20300}{}{Törzsbéli vadász}
{20400}{}{Kannibál}
{20500}{}{Kannibál}
{20600}{}{Szent Férfi}
{20700}{}{Szent Nő}
{20800}{}{Nomád- kis}
{20900}{}{Nomád- köz}
{21000}{}{Nomád- kis}
{21100}{}{Nomád- köz}
{21200}{}{Bandita}
{21300}{}{Bandita}
{21400}{}{Farmer}
{21500}{}{Farmer}
{21600}{}{Imádkozó-sáska}
{21700}{}{Rabszolga-kereskedő}
{21800}{}{Rabszolga-kereskedő}
{21900}{}{Vad brahmin}
{22000}{}{Telepes}
{22100}{}{Telepes}
{22200}{}{Menedékvárosi őrjárat}
{22300}{}{Menedékvárosi őrjárat}
{22400}{}{Erős hajcsár}
{22500}{}{Erős hajcsár}
{22600}{}{Őrültek}
{22700}{}{Guberálók}
{22800}{}{Őrült "Fénylők"}
{22900}{}{Világító guberálók}
{23000}{}{Halász}
{23100}{}{Halászasszony}
{23200}{}{Vadonlakó}
{23300}{}{Vadonlakó}
{23400}{}{Szeszcsempész}
{23500}{}{Szeszcsempész}
{23600}{}{Földmérő}
{23700}{}{Földmérő}
{23800}{}{Fosztogató}
{23900}{}{Fosztogató}
{24000}{}{Tűzgekkó}
{24100}{}{Erős Tűzgekkó}
{24200}{}{Idegen}
{24300}{}{Erős idegen}
{24400}{}{Kicsi, erős halálkarom}
{24500}{}{Erős halálkarom}
{24600}{}{Lebegő}
{24700}{}{Ocsmány lebegő}
{24800}{}{Kentaur}
{24900}{}{Aljas kentaur}
{25000}{}{Enklávé őrjárat}
{25100}{}{Enklávé őrjárat}
{25200}{}{Toborzók}
{25300}{}{Toborzók}
{25400}{}{Zsoldos}
{25500}{}{Zsoldos}
{25600}{}{Éjfajzat}
{25700}{}{Izmos éjfajzat}
{25800}{}{Erős ghoul}
{25900}{}{Gengszter}
{26000}{}{Jakuza}
{26100}{}{ÚKK-s Felderítő}
{26200}{}{ÚKK-s Felderítő}
{26300}{}{Martalóc}
{26400}{}{Martalóc}
{26500}{}{Szépfiú Lloyd}
{26600}{}{Vorpal patkány}
{26700}{}{13-as Menedék lakója}
{26800}{}{13-as Menedék lakója}
{26900}{}{A Híd őrzője}
{27000}{}{Titokzatos idegen}
{27100}{}{Titokzatos idegen}
{27200}{}{Hakeswill}
{27300}{}{Nagy Jesus Mordino}
{27400}{}{Dumar}
{27500}{}{Halálkarom anya}
{27600}{}{A Sárkány}
{27700}{}{Lo Pan}
{27800}{}{Hubologista}
{27900}{}{Hubologista}
{28000}{}{Titokzatos idegen}
{28100}{}{Titokzatos idegen}
{28200}{}{Titokzatos idegen}
{28300}{}{Titokzatos idegen}
{28400}{}{Titokzatos idegen}
{28500}{}{Titokzatos idegen}
{28600}{}{Titokzatos idegen}
{28700}{}{Titokzatos idegen}
{28800}{}{Elnöki testőr}
{28900}{}{Halálkarom tojás}
{29000}{}{Metzger}
{29100}{}{Person}
{29200}{}{Person in strange type of armor}
{29300}{}{Elnök}
{29400}{}{Alelnök}
{29500}{}{Technikus}
{29600}{}{A Borz}
{29700}{}{Dr. Fung}
{29800}{}{Kölyök}
{29900}{}{Kölyök}
{30000}{}{Fegyverkereskedő}
{30100}{}{Shi labortechnikus}
{30200}{}{Shi őr}
{30300}{}{Shi közember}
{30400}{}{Shi közember}
{30500}{}{Lo Pan követője}
{30600}{}{Lo Pan követője}
{30700}{}{Dokkmunkás}
{30800}{}{Shi kereskedő}
{30900}{}{Pat'káány Khiráály}
{31000}{}{Sulik - 1. Szint}
{31100}{}{Sulik - 2. Szint}
{31200}{}{Sulik - 3. Szint}
{31300}{}{Sulik - 3. Szint}
{31400}{}{Sulik - 4. Szint}
{31500}{}{Sulik - 5. Szint}
{31600}{}{Lenny - 1. Szint}
{31700}{}{Lenny - 2. Szint}
{31800}{}{Lenny - 3. Szint}
{31900}{}{Goris - 1. Szint}
{32000}{}{Goris - 2. Szint}
{32100}{}{Goris - 3. Szint}
{32200}{}{Goris - 4. Szint}
{32300}{}{Goris - 5. Szint}
{32400}{}{Goris - 6. Szint}
{32500}{}{Myron - 1. Szint}
{32600}{}{Myron - 2. Szint}
{32700}{}{Myron - 3. Szint}
{32800}{}{Myron - 4. Szint}
{32900}{}{Marcus - 1. Szint}
{33000}{}{Marcus - 2. Szint}
{33100}{}{Marcus - 3. Szint}
{33200}{}{Marcus - 4. Szint}
{33300}{}{Marcus - 5. Szint}
{33400}{}{Kiberkutya - 1. Szint}
{33500}{}{Kiberkutya - 2. Szint}
{33600}{}{Kiberkutya - 3. Szint}
{33700}{}{Kiberkutya - 4. Szint}
{33800}{}{Cassidy - 1. Szint}
{33900}{}{Cassidy - 2. Szint}
{34000}{}{Cassidy - 3. Szint}
{34100}{}{Cassidy - 4. Szint}
{34200}{}{Dogmeat}
{34300}{}{Dogmeat - 1. Szint}
{34400}{}{Dogmeat - 2. Szint}
{34500}{}{Dogmeat - 3. Szint}
{34600}{}{Dogmeat - 4. Szint}
{34700}{}{Dogmeat - 5. Szint}
{34800}{}{Dogmeat - 6. Szint}
{34900}{}{Robotagy - 1. Szint}
{35000}{}{Robotagy - 1. Szint}
{35100}{}{Robotagy - 1. Szint}
{35200}{}{Robotagy - 1. Szint}
{35300}{}{Robotagy - 1. Szint}
{35400}{}{Idegen királynő}
{35500}{}{Fekete radskorpió}
{35600}{}{Fekete radskorpió}
{35700}{}{Krumpli}
{35800}{}{Zsoldoskapitány}
{35900}{}{Zsoldos}
{36000}{}{Zsoldos}
{36100}{}{Árnyék-Aki-Jár}
{36200}{}{Punk!}
{36300}{}{Punk!}
{36400}{}{Marc}
{36500}{}{Dave H.}
{36600}{}{A. Ron Meyers kapitány}
{36700}{}{Chip}
{36800}{}{BHK-9}
{36900}{}{Hubologista őr}
{37000}{}{Hubologista őr}
{37100}{}{Juan}
{37200}{}{Vikki}
{37300}{}{Vic - 1. Szint}
{37400}{}{Vic - 2. Szint}
{37500}{}{Vic - 3. Szint}
{37600}{}{Vic - 4. Szint}
{37700}{}{Vic - 5. Szint}
{37800}{}{Vic - 6. Szint}
{37900}{}{Robotagy - csimpánz}
{38000}{}{Robotagy - abnormális}
{38100}{}{Robotagy - emberi}
{38200}{}{Óriáshangya}
{38300}{}{Erős óriáshangya}
{38400}{}{Pária kutya}
{38500}{}{Zurak}
{38600}{}{Imbot}
{38700}{}{Jimmy}
{38800}{}{Wejungh}
{38900}{}{Herb}
{39000}{}{Loopal}
{39100}{}{Jobe}
{39200}{}{Smitty}
{39300}{}{Rube}
{39400}{}{Krall mester}
{39500}{}{Ziggy}
{39600}{}{Khung mester}
{39700}{}{John Bishop}
{39800}{}{Angela Bishop}
{39900}{}{Mrs. Bishop}
{40000}{}{Bishop testőre 1}
{40100}{}{Bishop testőre 2}
{40200}{}{Bishop embere 1}
{40300}{}{Bishop embere 2}
{40400}{}{Veszett brahmin}
{40500}{}{Kis Jesus}
{40600}{}{Nagy Jesus}
{40700}{}{Mordino embere 1}
{40800}{}{Mordino embere 2}
{40900}{}{Mordino embere 3}
{41000}{}{Myron őre 1}
{41100}{}{Myron őre 2}
{41200}{}{Mr. Wright}
{41300}{}{Mrs. Wright}
{41400}{}{Chris Wright}
{41500}{}{Keith Wright}
{41600}{}{Wright fiú 1}
{41700}{}{Wright fiú 2}
{41800}{}{Wright lány 1}
{41900}{}{Wright lány 2}
{42000}{}{Mr. Salvatore}
{42100}{}{Mason}
{42200}{}{Salvatore embere 1}
{42300}{}{Salvatore embere 2}
{42400}{}{Szokványos csapos 1}
{42500}{}{Szokványos csapos 2}
{42600}{}{Szokványos csapos 3}
{42700}{}{Bokszoló 1}
{42800}{}{Bokszoló 2}
{42900}{}{Bokszoló 3}
{43000}{}{Bokszoló 4}
{43100}{}{Mike, a Húsdaráló}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Stuart Little}
{43500}{}{Korzikai Testvérek}
{43600}{}{Korzikai Kurvák}
{43700}{}{Tully atya}
{43800}{}{Kidobóember 1}
{43900}{}{Kidobóember 2}
{44000}{}{Kaszinólány}
{44100}{}{Drogdíler/Strici1}
{44200}{}{Drogdíler/Strici2}
{44300}{}{Drogdíler/Strici3}
{44400}{}{Drogdíler/Strici4}
{44500}{}{McGee}
{44600}{}{Kitty kisasszony}
{44700}{}{Szokványos lotyó 1}
{44800}{}{Szokványos lotyó 2}
{44900}{}{Csipkés Jimmy J.}
{45000}{}{Renesco}
{45100}{}{Tudós}
{45200}{}{Eldridge}
{45300}{}{Algernon}
{45400}{}{Jules}
{45500}{}{Bürokrata 1}
{45600}{}{Bürokrata 2}
{45700}{}{Kereskedő 1}
{45800}{}{Kereskedő 2}
{45900}{}{Őr 1}
{46000}{}{Őr 2}
{46100}{}{Őr 3}
{46200}{}{Őr 4}
{46300}{}{Katona 1}
{46400}{}{Katona 2}
{46500}{}{Katona 3}
{46600}{}{Katona 4}
{46700}{}{Stark őrmester}
{46800}{}{Andrew "doki"}
{46900}{}{Csapos}
{47000}{}{Lövegtorony}
{47001}{}{Ez egy automata lövegtorony iker plazmaágyúval felszerelve.}
{47100}{}{K-9 (alap)}
{47200}{}{K-9 (1.szint)}
{47300}{}{K-9 (2.szint)}
{47400}{}{K-9 (3.szint)}
{47500}{}{K-9 (4.szint)}
{47600}{}{Szokványos kiberkutya}
{47700}{}{Wanamingo tojás}
{47800}{}{Lo Pan őre}
{47900}{}{Marjorie}
{48000}{}{Automata ágyú}
{48100}{}{Speciális gekkó lény}
{48200}{}{A Nagy Kaszás}
{48300}{}{Frank Horrigan}
{48301}{}{The President's Bodyguard.}
{48400}{}{Nessa}
{48401}{}{The ghost of dead Nessa.}
{48500}{}{Sámán}
{48501}{}{Tribal shaman.}
{48600}{}{Warrior 	}
{48601}{}{Tribe warrior.}
{48700}{}{Őr}
{48800}{}{Sulik's sister}
{48900}{}{Kaga}
{49000}{}{Kaga}
{49100}{}{Kaga}
{49200}{}{Kaga}
{49300}{}{Kaga}
{49400}{}{Hologram 00000}
{49401}{}{The hologram for the director of science.}
{49500}{}{Hologram 10001}
{49501}{}{The hologram for the director of security.}
{49600}{}{Hologram 12001}
{49601}{}{The hologram for the director of operations.}
{49700}{}{Hologram 10031}
{49701}{}{Hologram for the director of Ground Maintenance.}
{49800}{}{Hologram 40011}
{49801}{}{Hologram for the Director of Public Relations.}
{49900}{}{Mr. Handy Robot}
{49901}{}{A seriously depressed version of the Mr. Handy Robot.}
{50000}{}{The Doctor}
{50001}{}{The leading, and only, Doctor left in the EPA.}
{50100}{}{EPA Spore Plant}
{50101}{}{A hideously mutated spore plant.}
{50200}{}{Kitsune}
{50300}{}{Dex}
{50400}{}{Cat Jules}
{50500}{}{Doctor's Warrior}
{50501}{}{A warrior for the doctor.}
{50600}{}{Fruit fly}
{50601}{}{A mutated fruit fly.}
{50700}{}{A hologram}
{50701}{}{A hologram.}
{50800}{}{Kitsune - level 1}
{50900}{}{Kitsune - level 2}
{51000}{}{Kitsune - level 3}
{51100}{}{Kitsune - level 4}
{51200}{}{Kitsune - level 5}
{51300}{}{Dex - level 1}
{51400}{}{Dex - level 2}
{51500}{}{Dex - level 3}
{51600}{}{Dex - level 4}
{51700}{}{Dex - level 5}
{51800}{}{Cat Jules - level 1}
{51900}{}{Cat Jules - level 2}
{52000}{}{Cat Jules - level 3}
{52100}{}{Cat Jules - level 4}
{52200}{}{Cat Jules - level 5}
{52300}{}{MIBoba Fe88}
{52400}{}{Hivan Zolo}
{52500}{}{Contie-bacca}
{52600}{}{Darek Vader}
{52700}{}{Jotisz the Hutt}
{52800}{}{R2Qwerty}
{52900}{}{Chris3ParksO}
{53000}{}{Yosan12}
{53100}{}{Obi-Wan-Killap}
{53200}{}{Empress Timeslip}
{53300}{}{Luke Skynet}
{53400}{}{Mon-Morticia}
{53500}{}{Kanhef}
{53600}{}{HawkEyE}
{53700}{}{Dravean}
{53800}{}{Mr. Wolna}
{53900}{}{encinodude}
{54000}{}{Minigun Jim}
{54100}{}{Bofast}
{54200}{}{Krom}
{54300}{}{Mother Spore Plant}
{54400}{}{Mother Alien}
{54500}{}{EPA Spore Plant}
{54501}{}{A hideously mutated spore plant.}
{54600}{}{Vadkutya}
{54601}{}{Egy veszett korcs.}
{54700}{}{Őrrobot v2.}
{54800}{}{Vén Joe}
{54900}{}{A plant creature}
