{100}{}{Égő olajoshordó}
{101}{}{A hordóban papír és más éghető anyag parázslik.}
{200}{}{Fa ajtó}
{201}{}{Egy fából készült ajtó.}
{300}{}{Fa asztal}
{301}{}{Egy fából készült asztal.}
{400}{}{Fa asztal}
{401}{}{Egy fából készült asztal.}
{500}{}{Fém hordó}
{501}{}{Egy régi, acélból készült hordó.}
{600}{}{Fém hordó}
{601}{}{Egy régi, acélból készült hordó.}
{700}{}{Abroncsok}
{701}{}{Egy rakás poros gumiabroncs. Vulkanizált és keményített fajta. Valószínűleg a hő által.}
{800}{}{Biztonsági ajtó}
{801}{}{Ez az ajtó nagyon biztonságosnak látszik. A külső világ elemeitől és a veszélyes teremtményektől véd.}
{900}{}{Számítógép}
{901}{}{Egy számítógépes terminál, amely fel van csatlakoztatva egy szerverre.}
{1000}{}{Oszlop}
{1001}{}{Támasztóoszlop, ami az egész komplexumra eső nyomást hívatott csökkenteni.}
{1100}{}{Számítógép}
{1101}{}{Egy számítógépes terminál, amely fel van csatlakoztatva egy szerverre.}
{1200}{}{Számítógép}
{1201}{}{Egy számítógépes terminál, amely fel van csatlakoztatva egy szerverre.}
{1300}{}{Monitor}
{1301}{}{Monokróm monitor, melyen különböző információjú bitek jelennek meg. Néha egy-egy bájt is feltűnik.}
{1400}{}{Monitor}
{1401}{}{Zöld színű képernyő, amin mindenféle bitek rohangásznak.}
{1500}{}{Holovetítő}
{1501}{}{Szélessávú THT-magnó. Már vagy 80 éve nem gyártottak új filmet hozzá.}
{1600}{}{Képernyők}
{1601}{}{Egy háromtagú monitorsor, melyeken más-más adatok futnak végig.}
{1700}{}{Képernyők}
{1701}{}{Egy három képernyőből álló monitorcsokor, különböző adatokat mutatnak a Menedék minden részéről.}
{1800}{}{Ajtó}
{1801}{}{Közelebbi vizsgálódás után is ajtónak tűnik.}
{1900}{}{Ajtó}
{1901}{}{Közelebbi vizsgálódás után is ajtónak tűnik.}
{2000}{}{Szellőző}
{2001}{}{Egy ventillátor, ami tisztítja és frissíti a bázis levegőjét.}
{2100}{}{Szellőző}
{2101}{}{Egy ventillátor, ami tisztítja és frissíti a bázis levegőjét.}
{2200}{}{A 13-as Menedék ajtaja}
{2201}{}{Egy óriási ajtó, ami bármilyen sérülésnek vagy nyomásnak képes ellenállni.}
{2300}{}{A 13-as Menedék ajtaja}
{2301}{}{Egy óriási ajtó, ami bármilyen sérülésnek vagy nyomásnak képes ellenállni.}
{2400}{}{Talapzat}
{2401}{}{Hidraulikus emelő, mely az egész emelvény energiaellátásáért és a kommunikációért felel.}
{2500}{}{Monitor}
{2501}{}{Ha egy monitort láttál, mindet láttad.}
{2600}{}{Monitor}
{2601}{}{Egy monitor, amin különböző adatok láthatók.}
{2700}{}{Rács}
{2701}{}{Rács a padlón.}
{2800}{}{Csövek}
{2801}{}{Néhány cső. Egész közelről is csőnek tűnnek.}
{2900}{}{Szellőző}
{2901}{}{Szabványos Menedék-Tek szellőzőrendszer.}
{3000}{}{Oszlop}
{3001}{}{Szabványos Menedék-Tek támoszlop-rendszer.}
{3100}{}{Oszlop}
{3101}{}{Szabványos Menedék-Tek támoszlop-rendszer.}
{3200}{}{Szellőző}
{3201}{}{Szabványos Menedék-Tek szellőzőrendszer.}
{3300}{}{Szellőző}
{3301}{}{Szabványos Menedék-Tek szellőzőrendszer.}
{3400}{}{Ágy}
{3401}{}{Egy ágy, ami sokkal kényelmesebbnek látszik, mint amiben eddig aludtál.}
{3500}{}{Ágy}
{3501}{}{Egy átlagos ágy. Puhának tűnik.}
{3600}{}{Ágy}
{3601}{}{Egy átlagos ágy. Puhának tűnik.}
{3700}{}{Ágy}
{3701}{}{Egy átlagos ágy. Puhának tűnik.}
{3800}{}{Lift}
{3801}{}{This is a maintenance elevator.}
{3900}{}{Szék}
{3901}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{4000}{}{Szék}
{4001}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{4100}{}{Szék}
{4101}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{4200}{}{Szék}
{4201}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{4300}{}{Monitor}
{4301}{}{Egy monitor, amin különböző adatok láthatók.}
{4400}{}{Monitor}
{4401}{}{Egy monitor, amin különböző adatok láthatók.}
{4500}{}{Monitor}
{4501}{}{Egy monitor, amin különböző adatok láthatók.}
{4600}{}{Monitor}
{4601}{}{Egy monitor, amin különböző adatok láthatók.}
{4700}{}{Monitor}
{4701}{}{Egy monitor, amin különböző adatok láthatók.}
{4800}{}{Monitor}
{4801}{}{Egy monitor, amin különböző adatok láthatók.}
{4900}{}{A szektor kijárata}
{4901}{}{A szektor kijárata}
{5000}{}{Levegő Tisztító Egység}
{5001}{}{An APU cleans the old air to provide new air for the complex.}
{5100}{}{Szék}
{5101}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{5200}{}{Szék}
{5201}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{5300}{}{Szék}
{5301}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{5400}{}{Szék}
{5401}{}{Ez egy szék. Kár, hogy nincs időd leülni és pihennni egy kicsit.}
{5500}{}{VME}
{5501}{}{A Videó Megjelenítő Egység különféle monitorokból és képernyőkből áll. Nagyon dolgozik a kicsike.}
{5600}{}{VME}
{5601}{}{A Videó Megjelenítő Egység különféle monitorokból és képernyőkből áll. Nagyon dolgozik a kicsike.}
{5700}{}{Szék}
{5701}{}{Egy átlagos szék. Nagyon puhának tűnik.}
{5800}{}{Szék}
{5801}{}{Egy átlagos szék. Nagyon puhának tűnik.}
{5900}{}{Szék}
{5901}{}{Egy átlagos szék. Nagyon puhának tűnik.}
{6000}{}{Szék}
{6001}{}{Egy átlagos szék. Nagyon puhának tűnik.}
{6100}{}{Asztal}
{6101}{}{Tudtad, hogy amíg nem voltak asztalok, az emberek kénytelenek voltak a földre tenni a dolgaikat?}
{6200}{}{Asztal}
{6201}{}{Minden kétséget kizáróan ez egy asztal.}
{6300}{}{Kúszónövény}
{6301}{}{Ez egy kúszónövény. Természetesen, még soha nem láttál élő kúszónövényt ezelőtt. Jobb lesz, ha megnézed közelebbről.}
{6400}{}{Kaktusz}
{6401}{}{Hát, nem látsz túl sok érdekes dolgot ezen a kaktuszon.}
{6500}{}{Kaktusz}
{6501}{}{Nem látsz semmi feltűnőt ezen a kaktuszon. Biztos jó kis pálinkát lehetne belőle készíteni.}
{6600}{}{Fa}
{6601}{}{Egy kiszáradt fa. Itt semmi sem nő rendesen.}
{6700}{}{Szuper-Titkos Hexagon}
{6701}{}{Ha ezt olvasod, akkor lehet panaszkodni a dizájnereknek!}
{6800}{}{Lépcső}
{6801}{}{Egy lépcső. Furcsa, nem?}
{6900}{}{Cseppkő}
{6901}{}{Sztalagmit.}
{7000}{}{Cseppkő}
{7001}{}{Sztalagmit.}
{7100}{}{Vértócsa}
{7101}{}{Ebben a tócsában nincsen semmi rendkívüli. Eltekintve persze attól, hogy itt valaki vagy valami bizony meghalt.}
{7200}{}{Kőoszlop}
{7201}{}{Ez a vastag kőből készült oszlop a padlótól egészen a plafonig ér.}
{7300}{}{Kőoszlop}
{7301}{}{Tömör kőoszlop, mely a padlóból indul és a mennyezetnél ér véget.}
{7400}{}{Kövek}
{7401}{}{Kigúvadt szemekkel figyeled a köveket egy darabig, de nem mozdulnak.}
{7500}{}{Kövek}
{7501}{}{Közelebbről is szemügyre veszed ezeket a kavicsokat, hátha meg akarnának támadni.}
{7600}{}{}
{7601}{}{}
{7700}{}{Kapu}
{7701}{}{Fából készült kapu.}
{7800}{}{Kövek}
{7801}{}{Nagy rakás kő. A környékről származnak.}
{7900}{}{Kövek}
{7901}{}{Egy kupacnyi kő.}
{8000}{}{Kövek}
{8001}{}{Egy kupacnyi kő.}
{8100}{}{Kövek}
{8101}{}{Baromi sok kő.}
{8200}{}{Csontok}
{8201}{}{Egy nagy halom kifehéredett állati csont. Legalábbis állati csontoknak véled...}
{8300}{}{Csontok}
{8301}{}{Egy nagy halom kifehéredett állati csont. Legalábbis állati csontoknak véled...}
{8400}{}{Csontok}
{8401}{}{Rengeteg megsárgult csont. Nem tudod megállapítani, milyen fajtájú állathoz tartoznak.}
{8500}{}{Csontok}
{8501}{}{Valamikor egy szarvaskenguru vázát alkothatták, de nem vagy benne biztos. Ehhez már túlságosan elporladtak.}
{8600}{}{Csontok}
{8601}{}{Ezek a csontok egy böhöm nagy kétfejű tehéné voltak valamikor.}
{8700}{}{Kapu}
{8701}{}{Fából ácsolt kapu. Ki lehet nyitni és be lehet zárni, ki lehet nyitni és be lehet zárni...}
{8800}{}{Kapu}
{8801}{}{Fából készült kapu.}
{8900}{}{Kapu}
{8901}{}{Fából készült kapu.}
{9000}{}{Kövek}
{9001}{}{Nagyon sok kő. Hátborzongató, ahogy itt hevernek.}
{9100}{}{Kövek}
{9101}{}{Egy nagy rakás kő. Ha egy picit közelebbről megnézed, apró öregemberek arcait láthatod a kövek oldalán.}
{9200}{}{Kövek}
{9201}{}{Kövek, kövek, kövek! Bárhova nézel, mindenhol csak köveket látsz!}
{9300}{}{Kövek}
{9301}{}{Egy kupacnyi kő.}
{9400}{}{Pult}
{9401}{}{Itt aztán mindenféle főzött ital megtalálható a porzó májak szolgálatában.}
{9500}{}{Szék}
{9501}{}{Ez egy öreg, szétrohadt szék, amit egy ősrégi autó üléséből készítettek.}
{9600}{}{Szék}
{9601}{}{A sokat látott széknek már szaga van, lábait pedig téglákkal pótolták. Nem túl kényelmes.}
{9700}{}{Szék}
{9701}{}{Egy büdös, penészes ülés, ami valaha egy autó része volt. Mocskosul kényelmetlennek tűnik.}
{9800}{}{Szék}
{9801}{}{Egy büdös, penészes ülés, ami valaha egy autó része volt. Mocskosul kényelmetlennek tűnik.}
{9900}{}{Dívány}
{9901}{}{Egy elképesztően kényelmetlennek tűnő ülőalkalmatosság, melyet dívány néven emlegetnek.}
{10000}{}{Dívány}
{10001}{}{Egy elképesztően kényelmetlennek tűnő ülőalkalmatosság, melyet dívány néven emlegetnek.}
{10100}{}{Abroncs}
{10101}{}{Egy régi gumiabroncs, mely némi gaz közepén csücsül.}
{10200}{}{Bozót}
{10201}{}{Némi sivatagi gaz.}
{10300}{}{Bozót}
{10301}{}{Némi sivatagi gaz.}
{10400}{}{Bozót}
{10401}{}{Némi sivatagi gaz.}
{10500}{}{Bozót}
{10501}{}{Némi sivatagi gaz.}
{10600}{}{Kacatok}
{10601}{}{Egy rozsdás kocsiajtó támaszkodik egy rozsdás fém hordónak. Merő egy rozsda az egész.}
{10700}{}{Kacatok}
{10701}{}{Egy törött vécécsésze, félig betemette már a homok. Olyan akár az élet.}
{10800}{}{Gaz}
{10801}{}{Egy amolyan sivatagi bozót. Ha nőtt is valamit az utóbbi időben, biztosan nem mostanában tette.}
{10900}{}{Kacatok}
{10901}{}{Egy autókerék, amit jócskán belepett a homok. Kis fadarabok hevernek körülötte.}
{11000}{}{Kövek}
{11001}{}{Kicsit közelebbről megnézve, úgy látod, hogy ezek valójában megkövesedett fadarabok.}
{11100}{}{Talaj}
{11101}{}{Kis kupac por, melyből elhalt gaz kandikál elő.}
{11200}{}{Talaj}
{11201}{}{Egy kis kupac kosz.}
{11300}{}{Talaj}
{11301}{}{Egy kis kupac kosz.}
{11400}{}{Talaj}
{11401}{}{Egy kis kupac kosz.}
{11500}{}{Gaz}
{11501}{}{Egy koszbucka, amin keresztülfut egy megszáradt gazcsomó.}
{11600}{}{Kacatok}
{11601}{}{Egy meghajlott rozsdás fémdarab.}
{11700}{}{Kacatok}
{11701}{}{Törött fadarabok.}
{11800}{}{Kacatok}
{11801}{}{Mindenféle haszontalan dolog.}
{11900}{}{Talaj}
{11901}{}{Egy kis kupac kosz.}
{12000}{}{Talaj}
{12001}{}{Egy kis kupac kosz.}
{12100}{}{Talaj}
{12101}{}{Egy kis kupac kosz.}
{12200}{}{Talaj}
{12201}{}{Egy kis kupac kosz.}
{12300}{}{Talaj}
{12301}{}{Egy kis kupac kosz.}
{12400}{}{Talaj}
{12401}{}{Egy kis kupac kosz.}
{12500}{}{Gaz}
{12501}{}{Nahát, megint egy igen érdekes növényre bukkantál!}
{12600}{}{Gaz}
{12601}{}{Nahát, megint egy igen érdekes növényre bukkantál!}
{12700}{}{Gaz}
{12701}{}{Nahát, megint egy igen érdekes növényre bukkantál!}
{12800}{}{Titkos-Hexagon (NoLight)}
{12900}{}{Fal}
{13000}{}{Fal}
{13100}{}{Fal}
{13200}{}{Fal}
{13300}{}{Fal}
{13400}{}{Fal}
{13500}{}{Lefolyó}
{13501}{}{Undorító bűz áramlik a csatornalefolyóból. Pár pillanat múlva már nem is tűnik annyira rossznak a szag.}
{13600}{}{Lefolyó}
{13601}{}{Tisztán ki tudsz venni valami mozgást a rács mögött. Parányi rád meredő vörös szempárt látsz. Egy patkány szemei.}
{13700}{}{Lefolyó}
{13701}{}{A lefolyóból csobogó víz hangja hallatszik, a szag pedig undorító.}
{13800}{}{Lefolyó}
{13801}{}{Hallod a víz bugyogását a lefolyóban. Jó kis bukéja van!}
{13900}{}{Létra}
{13901}{}{Régi, roskatag létra. Úgy tűnik, nem nagyon bírná el a súlyod.}
{14000}{}{Csatornalejáró}
{14001}{}{Mintha egy csatornarendszer bejárata lenne.}
{14100}{}{Fényforrás}
{14200}{}{Ajtó}
{14201}{}{Úgy látszik, ez a menedék-ajtó megsérült, talán megégett. Ezzel szemben még mindig működik.}
{14300}{}{Ajtó}
{14301}{}{Úgy látszik, ez a menedék-ajtó megsérült, talán megégett. Ezzel szemben még mindig működik.}
{14400}{}{Fedél}
{14401}{}{Egy jó nehéz fedőlemez. Elég jó állapotban van és nemrég rakták arrébb.}
{14500}{}{Lyuk}
{14501}{}{Az ajtón egy óriási lyuk tátong.}
{14600}{}{Lyuk}
{14601}{}{Az ajtón egy óriási lyuk tátong.}
{14700}{}{Állítólag golyóálló üveg}
{14701}{}{Állítólag törhetetlen üveg. Meg se próbáld!}
{14800}{}{Állítólag golyóálló üveg}
{14801}{}{Állítólag törhetetlen üveg. Meg se próbáld!}
{14900}{}{Állítólag golyóálló üveg}
{14901}{}{Állítólag törhetetlen üveg. Meg se próbáld!}
{15000}{}{Állítólag golyóálló üveg}
{15001}{}{Állítólag törhetetlen üveg. Meg se próbáld!}
{15100}{}{Ajtó}
{15101}{}{Ez az ajtó nagyon modern. Tágulva nyílik ki, ahogy a három alkotórésze elfordul.}
{15200}{}{Ajtó}
{15201}{}{Ez az ajtó nagyon modern. Tágulva nyílik ki, ahogy a három alkotórésze elfordul.}
{15300}{}{Ajtó}
{15301}{}{Az ajtóra az Acél Testvériségének címerét pingálták.}
{15400}{}{Ajtó}
{15401}{}{Az ajtóra az Acél Testvériségének címerét pingálták.}
{15500}{}{Lift}
{15501}{}{Ez egy Testvériségi lift belseje. Makulátlan!}
{15600}{}{Lift}
{15601}{}{Ez egy Testvériségi lift belseje. Makulátlan!}
{15700}{}{Jel}
{15701}{}{Ez az Acél Testvériségének jelképe. Jelzi, hogy ez a terület az övék, és jobb lesz, ha azonnal eltűnsz innen.}
{15800}{}{Monitor}
{15801}{}{You see a computer monitor.}
{15900}{}{Monitor}
{15901}{}{You see a computer monitor.}
{16000}{}{Számítógép}
{16001}{}{This is a computer memory databank.}
{16100}{}{Számítógép}
{16101}{}{This is a computer memory databank.}
{16200}{}{Számítógép}
{16201}{}{Egy nagyon modern számítógép, ami a szintén modern szalagos tárolási megoldást alkalmazza a már rég elavult lyukkártyák helyett.}
{16300}{}{Számítógép}
{16301}{}{Egy nagyon modern számítógép, ami a szintén modern szalagos tárolási megoldást alkalmazza a már rég elavult lyukkártyák helyett.}
{16400}{}{Monitor}
{16401}{}{You see a computer monitor.}
{16500}{}{Monitor}
{16501}{}{You see a computer monitor.}
{16600}{}{Vezeték}
{16601}{}{Valamelyik monitor vezetéke.}
{16700}{}{Vezeték}
{16701}{}{Valamelyik monitor vezetéke.}
{16800}{}{Vezeték}
{16801}{}{Valamelyik monitor vezetéke.}
{16900}{}{Oszlop}
{16901}{}{Ez egy támpillér.}
{17000}{}{Oszlop}
{17001}{}{Ez egy támpillér.}
{17100}{}{Bejárati terminál}
{17101}{}{Ez a gép irányítja a menedék böszme nagy ajtaját. Ha működésre akarod bírni, meg kell adnod a helyes kódot.}
{17200}{}{Tábla}
{17201}{}{Ez Gizmó Kaszinójának hirdetőtáblája.}
{17300}{}{A 13-as Menedék külső ajtaja}
{17301}{}{Ezen az ajtón keresztül lehet kijutni a menedékből a külvilágba.}
{17400}{}{A 13-as Menedék külső ajtaja}
{17401}{}{Ezen az ajtón keresztül lehet kijutni a menedékből a külvilágba.}
{17500}{}{Tábla}
{17501}{}{A tábla ezen részen látható egy elektromos motor, ami lassan pörgeti körbe-körbe a hozzákapcsolt neon feliratot.}
{17600}{}{Lefele nyíl}
{17700}{}{Felfele nyíl}
{17800}{}{Doboz}
{17900}{}{Doboz}
{18000}{}{Doboz}
{18100}{}{Lift tető}
{18101}{}{A lift egyik részét látod.}
{18200}{}{Számítógépes konzol}
{18201}{}{This is a dumb terminal, hooked up by cable to a large computer.}
{18300}{}{Számítógépes konzol}
{18301}{}{This is a dumb terminal, hooked up by cable to a large computer.}
{18400}{}{Embléma}
{18401}{}{Ez a Testvériség emblémája. A fogaskerekek jelentik a műszaki tudásukat, a kard a védelmi képességeiket, a szárnyak a felemelkedő reményeket.}
{18500}{}{Embléma}
{18501}{}{Ez a Testvériség emblémája. A fogaskerekek jelentik a műszaki tudásukat, a kard a védelmi képességeiket, a szárnyak a felemelkedő reményeket.}
{18600}{}{'Első szint' tábla}
{18601}{}{You think this could mean that you are on level one.}
{18700}{}{'Második szint' tábla}
{18701}{}{You are on level two.}
{18800}{}{'Harmadik szint' tábla}
{18801}{}{This must mean that you are on level three.}
{18900}{}{'Negyedik szint' tábla}
{18901}{}{You must be on level four.}
{19000}{}{Emeletes ágy}
{19001}{}{Egy katonai emeletes ágy. Nagyon durvának látszik. Sőt, úgy tűnik, hogy még egy pénzérme is visszapattanna a takarókról.}
{19100}{}{Emeletes ágy}
{19101}{}{Egy katonai emeletes ágy. Nagyon durvának látszik. Sőt, úgy tűnik, hogy még egy pénzérme is visszapattanna a takarókról.}
{19200}{}{Emeletes ágy}
{19201}{}{Egy katonai emeletes ágy. Nagyon durvának látszik. Sőt, úgy tűnik, hogy még egy pénzérme is visszapattanna a takarókról.}
{19300}{}{Doboz}
{19400}{}{Nuka-Cola automata}
{19401}{}{A gép oldalán lévő hirdetés a híres üdítőt reklámozza.}
{19500}{}{Fal}
{19600}{}{Csapóajtó}
{19601}{}{Egy nagyon rafinált csapóajtó.}
{19700}{}{Nyílás}
{19701}{}{A nyílásban levő létra az ismeretlen sötétségbe vezet. Jujj, mindjárt beviz, Elek.}
{19800}{}{Oltár}
{19801}{}{Ez egy oltár.}
{19900}{}{Szószék}
{19901}{}{Az emberek e mögül szoktak beszédet tartani. Van egy kis hely rajta az előre megírt beszédeknek.}
{20000}{}{Pad}
{20001}{}{Pontosan úgy néz ki, mint amire számítottál. Nincs rajta az égvilágon semmi különös.}
{20100}{}{Útjelző}
{20101}{}{A tábla már egy kissé berozsdált.}
{20200}{}{Útjelző}
{20201}{}{A tábla már egy kissé berozsdált.}
{20300}{}{Útjelző}
{20301}{}{A tábla már egy kissé berozsdált.}
{20400}{}{Útjelző}
{20401}{}{A tábla már egy kissé berozsdált.}
{20500}{}{Útjelző}
{20501}{}{A tábla már egy kissé berozsdált.}
{20600}{}{Régi matrac}
{20601}{}{Ez egy öreg, viharvert matrac. Úgy véled, valami rovarféle szörnyeteg él benne.}
{20700}{}{Régi matrac}
{20701}{}{Még ha meg is próbálnál aludni ezen a valamin, lehet, hogy nem lennél egyedül.}
{20800}{}{Ágy}
{20801}{}{A makeshift bed. The material was scavenged from some other source.}
{20900}{}{Ágy}
{20901}{}{A makeshift bed. The material was scavenged from some other source.}
{21000}{}{Ágy}
{21001}{}{Az ez ágy már látott jobb napokat (és valószínűleg éjjeleket is.)}
{21100}{}{Ágy}
{21101}{}{Közelebbről megvizsgálva, úgy veszed észre, hogy az ágyneműt már nagyon-nagyon régen nem húzták újra.}
{21200}{}{Ágy}
{21201}{}{There are a couple of stains of dubious origin on this well-worn sleeping device.}
{21300}{}{Ágy}
{21301}{}{Ez az ágy már látott egy s mást. Valami bizonyára végigkúszott a matracok között és ágyban, párnák közt halt meg...}
{21400}{}{}
{21401}{}{}
{21500}{}{}
{21501}{}{}
{21600}{}{}
{21601}{}{}
{21700}{}{UNUSED.}
{21800}{}{UNUSED.}
{21900}{}{UNUSED.}
{22000}{}{Ládák}
{22001}{}{Ezeket a ládákat már kikezdte az időjárás.}
{22100}{}{Ládák}
{22101}{}{Úgy tűnik, semmi említésre méltó nincs ezekben a ládákban.}
{22200}{}{Ládák}
{22201}{}{Úgy látszik, rengeteg felesleges időd van, hogy még e szétmálló roncs vizsgálatára is ráérsz.}
{22300}{}{Ládák}
{22301}{}{Ezeket a ládákat már kikezdte az időjárás.}
{22400}{}{Autó}
{22401}{}{Ez az automobil rettentően néz ki. Gondolni se merj arra, hogy egyszer majd üzemképes lesz!}
{22500}{}{Autó}
{22501}{}{Ezt a rozsdás fémdarabot már nem lehet helyrerakni.}
{22600}{}{Autó}
{22601}{}{Minden jel arra utal, hogy ez a jármű már többet nem fog közlekedni. De tényleg.}
{22700}{}{Autó}
{22701}{}{Semmi esély arra, hogy ezt a szemétnek is alig nevezhető valamit valaki, valaha is vezetni fogja.}
{22800}{}{Autó}
{22801}{}{Még ha az Év autószerelője hirtelen melletted is teremne, akkor se tudnátok megjavítani ezt a rozsdahegyet.}
{22900}{}{Szék}
{22901}{}{Egy kényelmes szék.}
{23000}{}{Szék}
{23001}{}{Ennek a széknek már leülték a fedele javát.}
{23100}{}{Szék}
{23101}{}{Ez a szék már penészes és mocskos. Ráadásul szaglik is rendesen, mint ahogy azt sejthetted.}
{23200}{}{Szék}
{23201}{}{Ez a szék szétesőben van. Nem kell már neki sok.}
{23300}{}{Szék}
{23301}{}{Ha valaki fizetne érte, talán akkor megfontolnád, hogy leülj erre a székre.}
{23400}{}{Szék}
{23401}{}{Olyan, mint egy régi irodai szék, és még több év elteltével is mindig nagyon jól néz ki.}
{23500}{}{Szék}
{23501}{}{Ez egy régi irodai szék. Lehet, hogy elbírna még egy embert is.}
{23600}{}{Szék}
{23601}{}{Ez az irodai szék már láthatott jobb napokat is. De most nem több egy rakás szemétnél.}
{23700}{}{Szék}
{23701}{}{Ez a szék úgy néz ki, mintha egy temetkezési vállalkozónál láttad volna. Halott.}
{23800}{}{}
{23900}{}{}
{24000}{}{}
{24100}{}{UNUSED.}
{24200}{}{UNUSED.}
{24300}{}{Tűzcsap}
{24301}{}{Ez egy tűzcsap. A Menedékben már megszokott tűzoltókészülékek hiányában lehet, hogy ezekre még szükséged lehet a tüzek oltásában.}
{24400}{}{Lámpaoszlop}
{24401}{}{Ez a lámpaoszlop még mindig működőképesnek látszik. Hihetetlen, de van ami még működik errefelé.}
{24500}{}{Lámpaoszlop}
{24501}{}{Ez a lámpaoszlop már soha többé nem fog világítani.}
{24600}{}{Lámpaoszlop}
{24601}{}{Ez egy üzemelő lámpaoszlop. Éjjelente sápadt, bársonyos fényt áraszt, amiről neked az égvilágon semmi nem jut eszedbe.}
{24700}{}{Lámpaoszlop}
{24701}{}{Egy törött lámpaoszlop. Nem lehet megjavítani.}
{24800}{}{Lámpaoszlop}
{24801}{}{Ez a lámpa világít.}
{24900}{}{Lámpaoszlop}
{24901}{}{Az oszlopon lévő lámpa összetört a javítás során.}
{25000}{}{Lámpaoszlop}
{25001}{}{Ez egy működő lámpaoszlop.}
{25100}{}{Kapu}
{25101}{}{A kapu le van zárva és a retesz igen robusztusnak tűnik.}
{25200}{}{Kacatok}
{25201}{}{Szemét, mi más?}
{25300}{}{Kacatok}
{25301}{}{Szemét, mi más?}
{25400}{}{Kacatok}
{25401}{}{Szemét, mi más?}
{25500}{}{Kacatok}
{25501}{}{Szemét, mi más?}
{25600}{}{Kacatok}
{25601}{}{Szemét, mi más?}
{25700}{}{Postaláda}
{25701}{}{A postaláda üres. Van egy olyan érzésed, hogy már jó ideje.}
{25800}{}{Ajtó}
{25801}{}{Egy nagyon finoman megmunkált fa ajtó, tűrhető állapotban.}
{25900}{}{Ajtó}
{25901}{}{Egy nagyon finoman megmunkált fa ajtó, tűrhető állapotban.}
{26000}{}{Ajtó}
{26001}{}{Egy nagyon finoman megmunkált fa ajtó, tűrhető állapotban.}
{26100}{}{Ajtó}
{26101}{}{Egy nagyon finoman megmunkált fa ajtó, tűrhető állapotban.}
{26200}{}{Pad}
{26201}{}{Ez a fapad menten az atomjaira hullik szét.}
{26300}{}{Pad}
{26301}{}{A pad nagyon gondozatlan, elég viseltesnek és átázottnak látszik.}
{26400}{}{Pad}
{26401}{}{Egy fából ácsolt pad, ami engedett a kornak és a kínzásnak.}
{26500}{}{Újságautomata}
{26501}{}{A gépben egy fia újság sincs.}
{26600}{}{Újságautomata}
{26601}{}{A gépben egy fia újság sincs.}
{26700}{}{Újságautomata}
{26701}{}{A gépben egy fia újság sincs.}
{26800}{}{Újságautomata}
{26801}{}{A gépben egy fia újság sincs.}
{26900}{}{Újságautomata}
{26901}{}{A gépben egy fia újság sincs.}
{27000}{}{Újságautomata}
{27001}{}{Kong az ürességtől. Pedig úgy tűnik, hogy régebben olcsó szexlapok voltak benne.}
{27100}{}{Kacatok}
{27101}{}{Egy matrac, ami szinte alig felismerhető. Még a patkányok se aludnának rajta vagy épp' benne.}
{27200}{}{Kacatok}
{27201}{}{Egy franciaágy matraca, ami már biztos megélt a mainál szebb napokat is.}
{27300}{}{Kacatok}
{27301}{}{Egy halom koszos és korhadt fa. Még kilóra se tudnád eladni.}
{27400}{}{Kacatok}
{27401}{}{Egy rakat fa, benne néhány rozsdás, hajlott szöggel.}
{27500}{}{Ládák}
{27501}{}{Rengeteg kartondoboz egymáson. El se tudod képzelni, hogyan bírták ki ilyen sokáig.}
{27600}{}{Ládák}
{27601}{}{Kartondobozok, jó nagy halomban.}
{27700}{}{Kacatok}
{27701}{}{Elsőre szemétnek látszik, de neked úgy rémlik, mintha valaha, mielőtt a természet ki nem kezdte volna, matrac volt.}
{27800}{}{Kövek}
{27900}{}{Kövek}
{28000}{}{Kövek}
{28100}{}{Kavicsok}
{28101}{}{Sok kavics és néhány nagyobb kődarab. Vigyázz!}
{28200}{}{Lefolyó}
{28201}{}{Egy porcelánból készült lefolyó, ami már rég nem működik.}
{28300}{}{Lefolyó}
{28301}{}{Törött porcelán lefolyó. Az alján egy poshadt vízű tócsa, amiben egy döglött patkány úszkál.}
{28400}{}{Lefolyó}
{28401}{}{Ez a lefolyó már nem használható. Ezt a közepén éktelenkedő óriási repedésből tudtad megállapítani.}
{28500}{}{Lefolyó}
{28501}{}{Törött porcelán lefolyó. Az alján egy poshadt vízű tócsa, amiben egy döglött patkány úszkál.}
{28600}{}{Stoptábla}
{28601}{}{Egy vörös tábla, amin marha nagy betűkkel a "STOP" felirat van felírva.}
{28700}{}{Stoptábla}
{28701}{}{A tábla alapszíne vörös, de egy jól látható "STOP" felirat is díszíti. Ezenkívül még egy extra golyónyom is látható rajta.}
{28800}{}{Stoplámpa}
{28801}{}{Egy ősrégi jelzőlámpa.}
{28900}{}{Stoplámpa}
{28901}{}{Egy ősrégi jelzőlámpa.}
{29000}{}{Stoplámpa}
{29001}{}{Egy ősrégi jelzőlámpa.}
{29100}{}{Utcai lámpa}
{29101}{}{Ez a lámpa ad némi világosságot az éj leszálltával, vagy a sötétebb területeken.}
{29200}{}{Utcai lámpa}
{29201}{}{Ez a lámpa ad némi világosságot az éj leszálltával, vagy a sötétebb területeken.}
{29300}{}{Utcai lámpa}
{29301}{}{Ez a lámpa ad némi világosságot az éj leszálltával, vagy a sötétebb területeken.}
{29400}{}{Utcai lámpa}
{29401}{}{Ez a lámpa ad némi világosságot az éj leszálltával, vagy a sötétebb területeken.}
{29500}{}{Utcai lámpa}
{29501}{}{A lámpa elméletileg az utcát világítja meg éjszaka vagy ha egyszerűen túl sötét lenne. Sajnos elromlott.}
{29600}{}{Utcai lámpa}
{29601}{}{A lámpa elméletileg az utcát világítja meg éjszaka vagy ha egyszerűen túl sötét lenne. Sajnos elromlott.}
{29700}{}{Utcai lámpa}
{29701}{}{A lámpa elméletileg az utcát világítja meg éjszaka vagy ha egyszerűen túl sötét lenne. Sajnos elromlott.}
{29800}{}{Útjelző}
{29801}{}{Ezen a táblán elméletileg az utca nevének kellene lennie, de a betűk már a feledésbe vesztek.}
{29900}{}{Útjelző}
{29901}{}{Ezen a táblán elméletileg az utca nevének kellene lennie, de a betűk már a feledésbe vesztek.}
{30000}{}{Asztal}
{30001}{}{Fából tákolt asztal, még mindig tűrhető állapotban.}
{30100}{}{Asztal}
{30101}{}{Fából tákolt asztal, még mindig tűrhető állapotban.}
{30200}{}{Asztal}
{30201}{}{Egy fa asztal, eléggé ramaty a kinézete.}
{30300}{}{Asztal}
{30301}{}{Ez is egy faasztal lenne, bár a teteje műanyagból van, ami már egy ideje meg van repedve.}
{30400}{}{Asztal}
{30401}{}{Fából készült és hányászöldre van festve. Nincs mit javítani rajta.}
{30500}{}{Asztal}
{30501}{}{Úgy néz ki, mint egy régi dohányzóasztal, közel a földhöz. Nyilván az apró termetű mutánsok számára készült.}
{30600}{}{Asztal}
{30601}{}{Úgy néz ki, mint egy régi dohányzóasztal, közel a földhöz. Nyilván az apró termetű mutánsok számára készült.}
{30700}{}{WC}
{30701}{}{Mivel a csészének le vannak törve a szélei, igen kényelmetlen lenne a trónolás.}
{30800}{}{WC}
{30801}{}{A csésze eltört.}
{30900}{}{WC}
{30901}{}{Pfúj! Aki legutoljára használta, elfelejtette lehúzni!}
{31000}{}{WC}
{31001}{}{A WC ülőkéje eltört, így ha nő vagy, tutira használhatatlan a számodra.}
{31100}{}{Szemét}
{31101}{}{Néhány szétrohadt cső bukkan elő a mocsokból. Semmi látnivaló nincs itt. Eredj tovább!}
{31200}{}{Szemét}
{31201}{}{Egy-két törött üveg és más tropára ment szemétdarabok.}
{31300}{}{Szemét}
{31301}{}{Egy-két törött üveg és más tropára ment szemétdarabok.}
{31400}{}{Szemét}
{31401}{}{Egy cső, ami ketté van törve. Úgy látszik, csak addig rozsdásodott, míg össze nem szakadt a saját súlya alatt.}
{31500}{}{Szemetes}
{31501}{}{Egy szeméttároló. Ezt lehet olvasni a rajta lévő címkén: "Tartsuk tisztán az utcáinkat!"}
{31600}{}{Fa}
{31601}{}{Egy kiszáradt fa.}
{31700}{}{Fa}
{31701}{}{Egy tuskó. Nincs rajta semmi spéci. Bár, ami azt illeti, ez az egyik legérdekesebb dolog, amin valaha is rajtafelejtetted a szemed.}
{31800}{}{Fa}
{31801}{}{Egy kiszáradt fa.}
{31900}{}{Fa}
{32000}{}{Fa}
{32100}{}{Fa}
{32200}{}{UNUSED.}
{32300}{}{Kocsi}
{32301}{}{A dízeles teherautó utolsó maradványai. Ez a nagy rakás fém már soha nem fog tudni mozogni.}
{32400}{}{Kocsi}
{32401}{}{Ennek a teherautónak már rég lőttek. Jó régen.}
{32500}{}{Fürdőkád}
{32501}{}{A fürdőkád meg van repedve és alig nem több, mint egy rakás ócskavas.}
{32600}{}{Fürdőkád}
{32601}{}{Ahogy alaposabban végigméred, arra a következtetésre jutsz, hogy ebben te bizony nem fürödnél.}
{32700}{}{Vizelde}
{32701}{}{Na, ide lehet pisilni.}
{32800}{}{Vizelde}
{32801}{}{Na, ide lehet pisilni.}
{32900}{}{Vizelde}
{32901}{}{Mindenki ide vizel, de amúgy semmi érdekes.}
{33000}{}{Vizelde}
{33001}{}{Mindenki ide vizel, de amúgy semmi érdekes.}
{33100}{}{Víztartály}
{33101}{}{Ebben az óriási tartályban folyadékot tárolnak. Esetünkben, (feltételezéseid szerint) ez eredetileg víztartály lenne.}
{33200}{}{Ajtó}
{33201}{}{Alapanyaga: fa. Különleges ismertetőjele: nincs.}
{33300}{}{Ajtó}
{33301}{}{100% fa felhasználásával létrehozott ajtó. Ezen keresztül ki és be lehet menni az épületbe.}
{33400}{}{Fali lámpa}
{33401}{}{Úgy látszik, ez a lámpa még működőképes.}
{33500}{}{Fali lámpa}
{33501}{}{A lámpa törött. Nagyon nem lep meg.}
{33600}{}{Fali lámpa}
{33601}{}{Úgy látszik, ez a lámpa még működőképes.}
{33700}{}{Fali lámpa}
{33701}{}{A lámpa törött. Nagyon nem lep meg.}
{33800}{}{Fali lámpa}
{33801}{}{Úgy látszik, ez a lámpa még működőképes.}
{33900}{}{Fali lámpa}
{33901}{}{A lámpa törött. Nagyon nem lep meg.}
{34000}{}{Fali lámpa}
{34001}{}{Úgy látszik, ez a lámpa még működőképes.}
{34100}{}{Fali lámpa}
{34101}{}{A lámpa törött. Nagyon nem lep meg.}
{34200}{}{Tábla}
{34201}{}{Valaha ez egy "Elsőbbségadás kötelező" tábla volt.}
{34300}{}{Tábla}
{34301}{}{A szövege már kifakult, de te még mindig elsőbbségadásra kötelezed a világot.}
{34400}{}{Titkos-Hexagon (Auto Inviso)}
{34401}{}{Ha ezt olvasod, akkor lehet panaszkodni a dizájnereknek!}
{34500}{}{Padló}
{34600}{}{Ajtó}
{34601}{}{Egy gazdagon díszített fa ajtó. Biztos társadalmi munka keretében készült.}
{34700}{}{Pad}
{34701}{}{Ezt az ülést nagy betontömbök tartják. Igaz, ez nem annyira fontos. Te vagy az egyetlen, aki ezt észrevette.}
{34800}{}{Lépcső}
{34801}{}{Felfelé vezet.}
{34900}{}{Lépcső}
{34901}{}{Felfelé vezet.}
{35000}{}{Lépcső}
{35001}{}{Felfelé vezet.}
{35100}{}{Lépcső}
{35101}{}{Felfelé vezet.}
{35200}{}{Lépcső}
{35201}{}{Felfelé vezet.}
{35300}{}{Lépcső}
{35301}{}{Felfelé vezet.}
{35400}{}{Lépcső}
{35401}{}{Felfelé vezet.}
{35500}{}{Lépcső}
{35501}{}{Felfelé vezet.}
{35600}{}{Lépcső}
{35601}{}{Lefele vezet.}
{35700}{}{Fal}
{35701}{}{Most a katedrális oldalát látod.}
{35800}{}{Fal}
{35801}{}{Most a katedrális oldalát látod.}
{35900}{}{Fal}
{35901}{}{Most a katedrális oldalát látod.}
{36000}{}{Fal}
{36001}{}{Most a katedrális oldalát látod.}
{36100}{}{Függöny}
{36101}{}{Úgy látszik, ezt a függönyt igen egyszerű okból készítették, de minden nagyon jól leplezhető vele.}
{36200}{}{Függöny}
{36201}{}{Úgy látszik, ezt a függönyt igen egyszerű okból készítették, de minden nagyon jól leplezhető vele.}
{36300}{}{Tál}
{36301}{}{Egy precíz és kitartó munkával készített fatál. Valószínűleg a gabona őrlésére és leválogatására szolgál.}
{36400}{}{Tál}
{36401}{}{Hát ez bizony fatál is.}
{36500}{}{Cserépedény}
{36501}{}{Nagyon ügyes volt, aki csinálta.}
{36600}{}{Növény}
{36601}{}{Mintha egy mutáns káposzta lenne. Láthatólag kedvez neki a meleg időjárás.}
{36700}{}{Növény}
{36701}{}{Mintha egy mutáns káposzta lenne. Láthatólag kedvez neki a meleg időjárás.}
{36800}{}{Talicska}
{36801}{}{Egyszerű, de hasznos mezőgazdasági eszköz.}
{36900}{}{Növény}
{36901}{}{Egy mutáns kukoricacsutka. Ezek a feltételek kedvezőleg hatnak rá.}
{37000}{}{Növény}
{37001}{}{Egy mutáns kukoricacsutka. Ezek a feltételek kedvezőleg hatnak rá.}
{37100}{}{Növény}
{37101}{}{Egy mutáns kukoricacsutka. Ezek a feltételek kedvezőleg hatnak rá.}
{37200}{}{Cserépedény}
{37201}{}{Gondosan megmunkált cserépedény.}
{37300}{}{Gereblye}
{37301}{}{Ez a gereblye azé, akié. Nem is gondolsz arra, hogy használd.}
{37400}{}{Gereblye}
{37401}{}{Ez a gereblye azé, akié. Nem is gondolsz arra, hogy használd.}
{37500}{}{Gereblye}
{37501}{}{Ez a gereblye azé, akié. Nem is gondolsz arra, hogy használd.}
{37600}{}{Szőnyeg}
{37601}{}{Egy normál szőnyeg. Valószínűleg tehetséges kezek terméke.}
{37700}{}{Szőnyeg}
{37701}{}{Egy normál szőnyeg. Valószínűleg tehetséges kezek terméke.}
{37800}{}{Szőnyeg}
{37801}{}{Egy normál szőnyeg. Valószínűleg tehetséges kezek terméke.}
{37900}{}{Ásó}
{37901}{}{Ehhez az ásóhoz nyilván tartozik valaki. De nem is annyira fontos.}
{38000}{}{Ásó}
{38001}{}{Ehhez az ásóhoz nyilván tartozik valaki. De nem is annyira fontos.}
{38100}{}{Ásó}
{38101}{}{Ehhez az ásóhoz nyilván tartozik valaki. De nem is annyira fontos.}
{38200}{}{Váza}
{38201}{}{Nagyon aranyos agyagváza.}
{38300}{}{Kut}
{38301}{}{Egy tipikus kút, amit az ember a semmi közepén találhat.}
{38400}{}{Rúd}
{38401}{}{Nincs jurta rúd nélkül.}
{38500}{}{Rúd}
{38501}{}{Nincs jurta rúd nélkül.}
{38600}{}{Rúd}
{38601}{}{Nincs jurta rúd nélkül.}
{38700}{}{Rúd}
{38701}{}{Nincs jurta rúd nélkül.}
{38800}{}{Rúd}
{38801}{}{Nincs jurta rúd nélkül.}
{38900}{}{Rúd}
{38901}{}{Nincs jurta rúd nélkül.}
{39000}{}{Menedék-ajtó}
{39001}{}{Ez a Menedék-ajtó mostantól már nem több, mint egy rakás fémdarab.}
{39100}{}{Fal}
{39101}{}{A nagy Menedék-ajtó irányító mechanizmusa megsérült a javítás során.}
{39200}{}{Dúc}
{39201}{}{Ez a dúc támasztja alá a védőfalat.}
{39300}{}{Dúc}
{39301}{}{Ez a dúc támasztja alá a védőfalat.}
{39400}{}{Dúc}
{39401}{}{Ez a dúc támasztja alá a védőfalat.}
{39500}{}{Dúc}
{39501}{}{Ez a dúc támasztja alá a védőfalat.}
{39600}{}{Fém hordó}
{39601}{}{Egy rozsdaette, fémes kongású hordó. Persze hogy üres.}
{39700}{}{Fém hordó}
{39701}{}{Ebből a döngő hangzásból ítélve a hordó tökre üres.}
{39800}{}{Fém hordók}
{39801}{}{Ezek a hordók túlságosan öblös hangot adnak ahhoz, hogy legyen bennük valami.}
{39900}{}{Fém hordók}
{39901}{}{Ezek a hordók túlságosan öblös hangot adnak ahhoz, hogy legyen bennük valami.}
{40000}{}{Szellőztető}
{40001}{}{Ez a szellőztető látszólag egy földalatti építményt lát el levegővel.}
{40100}{}{Doboz}
{40101}{}{Egy faláda. Bár nehéz lenne annak nézni ebben az állagában.}
{40200}{}{Doboz}
{40201}{}{Egy egyszerű láda, ami fából van. Elég jól tartja magát.}
{40300}{}{Doboz}
{40301}{}{Ez a láda összerogyott a saját súlya alatt.}
{40400}{}{Asztal}
{40401}{}{Egy sima asztal, számítógéppel.}
{40500}{}{Asztal}
{40501}{}{Egy sima asztal, számítógéppel.}
{40600}{}{Ajtó}
{40601}{}{Egy fából készített ajtó, még felismerhető állapotban.}
{40700}{}{Barlangnyílás}
{40701}{}{Irdatlan sok kő, sokkal több, mint amennyit könnyedén arrébb lehetne rakni.}
{40800}{}{Autó}
{40801}{}{Ezt az elsüllyedt autót már nem lehet megszerelni.}
{40900}{}{Autó}
{40901}{}{Az autó egy kicsit már vizes, és nagyon már szerelni se lehet.}
{41000}{}{Autó}
{41001}{}{A járművet elég bénán parkolták le. Sajnos, éppen javítják.}
{41100}{}{Kacatok}
{41101}{}{Teljesen szétáztatta a szennyezett tengervíz.}
{41200}{}{Kacatok}
{41201}{}{Majdnem elmosta a víz.}
{41300}{}{Kacatok}
{41301}{}{Valaki ügyesen összeválogatott egy rakat haszontalan szemetet.}
{41400}{}{Csövek}
{41401}{}{Ezek a csövek szállítják az üzemanyagot a földalatti tartályból a garázsba. Már régóta nem használták őket.}
{41500}{}{Cső}
{41501}{}{Ezek a csövek szállítják az üzemanyagot a földalatti tartályból a garázsba. Már régóta nem használták őket.}
{41600}{}{Csövek}
{41601}{}{Ezek a csövek szállítják az üzemanyagot a földalatti tartályból a garázsba. Már régóta nem használták őket.}
{41700}{}{Liftakna}
{41701}{}{A liftrendszer része.}
{41800}{}{Air Shaft}
{41801}{}{An air shaft that stretches deep into the ship. It has been damaged.}
{41900}{}{Lift}
{41901}{}{Egy lift. Ezzel lehet közlekedni lefelé és felfelé a szintek között.}
{42000}{}{Liftakna}
{42001}{}{Egy liftakna, ami mélyen a földben gyökeredzik. Lerobbant.}
{42100}{}{Liftajtó}
{42101}{}{Ez az ajtó vezet a lift motorjához. Ha használni akarod a liftet, először ezt az ajtót kell kinyitnod.}
{42200}{}{Cső}
{42201}{}{Egy fémcső. A további részletek már nem fontosak.}
{42300}{}{Talaj}
{42400}{}{Doboz}
{42500}{}{Doboz}
{42600}{}{Doboz}
{42700}{}{Doboz}
{42800}{}{Kövek}
{42801}{}{Apró kőpiramis. Nem túl izgalmas.}
{42900}{}{Kövek}
{42901}{}{Apró kőpiramis. Nem túl izgalmas.}
{43000}{}{Kövek}
{43001}{}{Kövek, kis csoportban. Egy cseppet sem érdekesek a számodra.}
{43100}{}{Kövek}
{43101}{}{Sok kavics együtt.}
{43200}{}{Kövek}
{43201}{}{Sok kavics együtt.}
{43300}{}{Kövek}
{43301}{}{Sok kavics együtt.}
{43400}{}{Kövek}
{43401}{}{Sok kavics együtt.}
{43500}{}{Kövek}
{43501}{}{Sok kavics együtt.}
{43600}{}{Menedék-ajtó}
{43601}{}{E Menedékajtó nagyon hasonlít a 13-as Menedék egyik ajtajához. Azonban ezt itt kikapcsolták.}
{43700}{}{Ajtó}
{43701}{}{Egy precízen elkészített fa ajtó, megerősítve egy-két dekoráló fémkapoccsal, ami majdnem hipnotikus kinézetet ad neki.}
{43800}{}{Ajtó}
{43801}{}{Egy precízen elkészített fa ajtó, megerősítve egy-két dekoráló fémkapoccsal, ami majdnem hipnotikus kinézetet ad neki.}
{43900}{}{Kádak}
{43901}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44000}{}{Kádak}
{44001}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44100}{}{Kádak}
{44101}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44200}{}{Kádak}
{44201}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44300}{}{Kádak}
{44301}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44400}{}{Kádak}
{44401}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44500}{}{Kádak}
{44501}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44600}{}{Kádak}
{44601}{}{Mindenféle kádak. Nem vagy benne teljesen biztos, de ezekben az óriási kádakban valami zöldes trutymót látsz, ami aligha tűnik fontosnak.}
{44700}{}{Fal}
{44800}{}{Ajtó}
{44801}{}{Egy biztonsági ajtó. Nagyon páncélozottnak tűnik.}
{44900}{}{Nukleáris robbanófej}
{45000}{}{Kut}
{45001}{}{Egy tipikus kút, amit az ember a semmi közepén találhat.}
{45100}{}{Pókerasztal}
{45101}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45200}{}{Pókerasztal}
{45201}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45300}{}{Pókerasztal}
{45301}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45400}{}{Pókerasztal}
{45401}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45500}{}{Pókerasztal}
{45501}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45600}{}{Pókerasztal}
{45601}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45700}{}{Pókerasztal}
{45701}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45800}{}{Pókerasztal}
{45801}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{45900}{}{Pókerasztal}
{45901}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{46000}{}{Pókerasztal}
{46001}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{46100}{}{Kő}
{46101}{}{Egy apró kövecske, teljesen lényegtelen a történet szempontjából.}
{46200}{}{Kő}
{46300}{}{Kő}
{46400}{}{Kő}
{46500}{}{Nyerőautomata}
{46501}{}{Csak a pénzt nyeli. Így van beállítva.}
{46600}{}{Nyerőautomata}
{46601}{}{Csak a pénzt nyeli. Így van beállítva.}
{46700}{}{Ajtó}
{46800}{}{Shaft}
{46900}{}{Shaft}
{47000}{}{Liftajtó}
{47100}{}{Ablak}
{47101}{}{Üveg helyett ebben az ablakban burkolólap van.}
{47200}{}{Ablak}
{47201}{}{Üveg helyett ebben az ablakban burkolólap van.}
{47300}{}{Ablak}
{47301}{}{Üveg helyett ebben az ablakban burkolólap van.}
{47400}{}{Ablak}
{47401}{}{Üveg helyett ebben az ablakban burkolólap van.}
{47500}{}{Ajtó}
{47501}{}{Ez egy görgős fém ajtó, amit belülről lereteszeltek.}
{47600}{}{Ajtó}
{47601}{}{Ez egy görgős fém ajtó, amit belülről lereteszeltek.}
{47700}{}{Ajtó}
{47701}{}{Nagy fémkerekes ajtó, amit a belső oldaláról lezártak. A felirat: "CSAK BERAKODÁS"}
{47800}{}{Ajtó}
{47801}{}{Ez egy görgős fém ajtó, amit belülről lereteszeltek.}
{47900}{}{Ajtó}
{47901}{}{Ez egy görgős fém ajtó, amit belülről lereteszeltek.}
{48000}{}{Ajtó}
{48001}{}{Nagy fémkerekes ajtó, amit a belső oldaláról lezártak. A felirat: "CSAK BERAKODÁS"}
{48100}{}{Ajtó}
{48101}{}{Ez az ajtó gyanúsan emlékeztet egy raktár ajtajára.}
{48200}{}{Ajtó}
{48201}{}{Ez az ajtó gyanúsan emlékeztet egy raktár ajtajára.}
{48300}{}{Szélkakas}
{48301}{}{This simple weather vane helps inhabitants of the wasteland study the weather.}
{48400}{}{Oltár}
{48401}{}{Egy primitív oltár, amit fából készítettek, majd lefestettek.}
{48500}{}{Pódium}
{48501}{}{Ez egy normál katedra, ideális a felszólalásokra.}
{48600}{}{Oltár}
{48700}{}{Monitor}
{48701}{}{Egy nagy fekete-fehér monitor. A vétel elég jó ahhoz képest, hogy épületen belül van és nincs antennája.}
{48800}{}{Monitor}
{48801}{}{Egy óriási monitor, ami FF (Fekete-Fehér). Egy csuhás figurát látsz, amint valamilyen vallásos imádságot mormol lázasan.}
{48900}{}{Erőtér}
{48901}{}{Ez egy nagyon erős energiamező.}
{49000}{}{Erőtér}
{49001}{}{Ez egy nagyon erős energiamező.}
{49100}{}{Erőtér}
{49101}{}{Ez egy nagyon erős energiamező.}
{49200}{}{Erőtér}
{49201}{}{Ez egy nagyon erős energiamező.}
{49300}{}{Asztal}
{49301}{}{Egy hétköznapi faasztal.}
{49400}{}{Asztal}
{49401}{}{Egy hétköznapi faasztal.}
{49500}{}{Asztal}
{49501}{}{Egy hétköznapi faasztal.}
{49600}{}{Asztal}
{49601}{}{Egy hétköznapi faasztal.}
{49700}{}{Asztal}
{49701}{}{Egy hétköznapi faasztal.}
{49800}{}{Asztal}
{49801}{}{Egy hétköznapi faasztal.}
{49900}{}{Kövek}
{49901}{}{Apró kőpiramis. Nem túl izgalmas.}
{50000}{}{Kövek}
{50001}{}{Apró kőpiramis. Nem túl izgalmas.}
{50100}{}{Kövek}
{50101}{}{Kövek, kis csoportban. Egy cseppet sem érdekesek a számodra.}
{50200}{}{Kövek}
{50201}{}{Sok kavics együtt.}
{50300}{}{Kövek}
{50301}{}{Sok kavics együtt.}
{50400}{}{Kövek}
{50401}{}{Sok kavics együtt.}
{50500}{}{Oltár}
{50501}{}{Egy primitív oltár, amit fából készítettek, majd lefestettek.}
{50600}{}{Oltár}
{50601}{}{Egy primitív oltár, amit fából készítettek, majd lefestettek.}
{50700}{}{Oltár}
{50701}{}{Egy primitív oltár, amit fából készítettek, majd lefestettek.}
{50800}{}{Oltár}
{50801}{}{Egy primitív oltár, amit fából készítettek, majd lefestettek.}
{50900}{}{Kavicsok}
{50901}{}{Ezt a nagy rakás kőtörmeléket a tető beomlott része alkotja. A köteled visszavezet a felszínre.}
{51000}{}{Kövek}
{51001}{}{fgfgfg}
{51100}{}{UNUSED.}
{51200}{}{UNUSED.}
{51300}{}{UNUSED.}
{51400}{}{UNUSED.}
{51500}{}{UNUSED.}
{51600}{}{Asztal}
{51601}{}{Ez a nagy asztal fontosnak néz ki. Talán valami találkozót szoktak itt tartani?}
{51700}{}{Asztal}
{51701}{}{Ez a nagy asztal fontosnak néz ki. Talán valami találkozót szoktak itt tartani?}
{51800}{}{Asztal}
{51801}{}{Ez a nagy asztal fontosnak néz ki. Talán valami találkozót szoktak itt tartani?}
{51900}{}{Asztal}
{51901}{}{Ez a nagy asztal fontosnak néz ki. Talán valami találkozót szoktak itt tartani?}
{52000}{}{Asztal}
{52001}{}{Ez a nagy asztal fontosnak néz ki. Talán valami találkozót szoktak itt tartani?}
{52100}{}{Asztal}
{52101}{}{Ez a nagy asztal fontosnak néz ki. Talán valami találkozót szoktak itt tartani?}
{52200}{}{Oltár}
{52201}{}{Egy oltár, amit az Acél Testvériség tervezett és készített (ki más?). A jelképük fémesen csillog rajta.}
{52300}{}{Oltár}
{52301}{}{Egy oltár, amit az Acél Testvériség tervezett és készített (ki más?). A jelképük fémesen csillog rajta.}
{52400}{}{Oltár}
{52401}{}{Egy oltár, amit az Acél Testvériség tervezett és készített (ki más?). A jelképük fémesen csillog rajta.}
{52500}{}{Pad}
{52501}{}{Egy nagyon divatos, de annál kényelmetlenebb padka. A seggem majd' szétnyomta.}
{52600}{}{Pódium}
{52601}{}{Egy aranyos fa emelvény. Egy súgógép is bele van építve, ami a beszélő felé néz.}
{52700}{}{Utánfutó}
{52701}{}{Egy karaván utánfutója, melyet egy régi autó roncsaiból tákoltak össze.}
{52800}{}{Utánfutó}
{52801}{}{Egy karaván utánfutója, melyet egy régi autó roncsaiból tákoltak össze.}
{52900}{}{Utánfutó}
{52901}{}{Egy karaván utánfutója, melyet egy régi autó roncsaiból tákoltak össze.}
{53000}{}{Utánfutó}
{53001}{}{Egy karaván utánfutója, melyet egy régi autó roncsaiból tákoltak össze.}
{53100}{}{Utánfutó}
{53101}{}{Egy karaván utánfutója, melyet egy régi autó roncsaiból tákoltak össze.}
{53200}{}{Utánfutó}
{53201}{}{Egy karaván utánfutója, melyet egy régi autó roncsaiból tákoltak össze.}
{53300}{}{Szőnyeg}
{53301}{}{Egy gyakorlószőnyeg.}
{53400}{}{Szőnyeg}
{53401}{}{Egy gyakorlószőnyeg.}
{53500}{}{Szőnyeg}
{53501}{}{Egy gyakorlószőnyeg.}
{53600}{}{Szőnyeg}
{53601}{}{Egy gyakorlószőnyeg.}
{53700}{}{Boksz-zsák}
{53701}{}{Ez egy IzomCsávó(tm) márkájú boksz-zsák.}
{53800}{}{Lépcsőzőgép}
{53801}{}{Gyakorlógép.}
{53900}{}{Lépcsőzőgép}
{54000}{}{Szobabicikli}
{54001}{}{Gyakorlógép.}
{54100}{}{Szobabicikli}
{54101}{}{Gyakorlógép.}
{54200}{}{Fekpad}
{54201}{}{Gyakorlógép.}
{54300}{}{Fekpad}
{54301}{}{Gyakorlógép.}
{54400}{}{Palánk}
{54401}{}{Ezek a kemény palánkok jól össze vannak erősítve.}
{54500}{}{Palánk}
{54501}{}{Ezek a kemény palánkok jól össze vannak erősítve.}
{54600}{}{Rulettasztal}
{54601}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{54700}{}{Rulettasztal}
{54701}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{54800}{}{Rulettasztal}
{54801}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{54900}{}{Rulettasztal}
{54901}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{55000}{}{Rulettasztal}
{55001}{}{Ez a kedvelt szerencsejátéknak ad otthont.}
{55100}{}{Hordó}
{55101}{}{Ezen az üres hordón a radioaktív lóhere látható az oldalára festve élénksárgával.}
{55200}{}{Hordó}
{55201}{}{Ebben a hordóban van valami sugárzó trutyesz. A radioaktív lóhere jele talán kicsit segít, hogy ez a trutymó vajon mi lehet.}
{55300}{}{Számítógép}
{55301}{}{Egy nagyon modern kinézetű számítógép.}
{55400}{}{Számítógép}
{55401}{}{Egy nagyon modern kinézetű számítógép.}
{55500}{}{Függőtartály}
{55501}{}{Valamiféle orvosi vagy kísérleti segédeszköz, olybá tűnik, hogy akár egy nagyobb méretű emberi testet is képes lenne tárolni.}
{55600}{}{Rossz függőtartály}
{55601}{}{Egy elromlott darab. Még mindig javítják.}
{55700}{}{Szuperszámítógép}
{55701}{}{Ez egy termetes szuperszámítógép. Valószínűleg az egyik leggyorsabb számítógép, amit valaha láttál.}
{55800}{}{Dobogó}
{55801}{}{Ezen a dobogón van a nagy szuperszámítógép a hűtőtartályok felett.}
{55900}{}{Don't use}
{56000}{}{Don't use}
{56100}{}{Ágy}
{56101}{}{Egy katonai emeletes ágy. Nagyon durvának látszik. Sőt, úgy tűnik, hogy még egy pénzérme is visszapattanna a takarókról.}
{56200}{}{Ágy}
{56201}{}{Egy katonai emeletes ágy. Nagyon durvának látszik. Sőt, úgy tűnik, hogy még egy pénzérme is visszapattanna a takarókról.}
{56300}{}{Ágy}
{56301}{}{Egy katonai emeletes ágy. Nagyon durvának látszik. Sőt, úgy tűnik, hogy még egy pénzérme is visszapattanna a takarókról.}
{56400}{}{Vezeték}
{56401}{}{Valami soros kábel.}
{56500}{}{Vezeték}
{56501}{}{Valami soros kábel.}
{56600}{}{Tábla}
{56601}{}{A táblán az áll, hogy "BÁR". A többi már magától értetődik.}
{56700}{}{Gerenda}
{56701}{}{Ez a vastag gerenda egy kráter felé van kirakva.}
{56800}{}{Gerenda}
{56801}{}{A gerendáról kötél lóg lefelé. Úgy néz ki, most már lemászhatsz a kráterba.}
{56900}{}{Polc}
{56901}{}{Csak egy nagyon üres fémpolcot látsz.}
{57000}{}{Polc}
{57001}{}{Csak egy nagyon üres fémpolcot látsz.}
{57100}{}{Polc}
{57101}{}{Csak egy nagyon üres fémpolcot látsz.}
{57200}{}{Polc}
{57201}{}{Csak egy nagyon üres fémpolcot látsz.}
{57300}{}{Bokor}
{57301}{}{Egy bokor, bakker.}
{57400}{}{Bokor}
{57401}{}{Gáz ez a gaz.}
{57500}{}{Bokor}
{57501}{}{Gáz ez a gaz.}
{57600}{}{Táj}
{57601}{}{Szép kilátás nyílik a Csonttelepre ebből a toronyból. Lassan már kezded érezni, hogy milyen magasan is vagy.}
{57700}{}{Táj}
{57701}{}{Nagyon szépen látható innen a Csonttelep.}
{57800}{}{Fal}
{57801}{}{A Katedrális oldala.}
{57900}{}{Fal}
{57901}{}{A Katedrális oldala.}
{58000}{}{Fal}
{58001}{}{A Katedrális oldala.}
{58100}{}{Ajtó}
{58101}{}{Egy ajtó, ami remekül mutat otthon egy cellában.}
{58200}{}{Tábla}
{58201}{}{A felirat szerint az üzletet "Pocsolyá"-nak hívják.}
{58300}{}{Létra}
{58301}{}{Ez a létra a lenn tátongó sötétségbe mered.}
{58400}{}{Létra}
{58401}{}{Ez a létra a lenn tátongó sötétségbe mered.}
{58500}{}{Gép}
{58501}{}{It looks like an old printing press or manufacturing doohickey.}
{58600}{}{Gép}
{58601}{}{It looks like an old printing press or manufacturing doohickey.}
{58700}{}{Gép}
{58701}{}{It looks like an old printing press or manufacturing doohickey.}
{58800}{}{Gép}
{58801}{}{It looks like an old printing press or manufacturing doohickey.}
{58900}{}{Gép}
{58901}{}{It looks like an old printing press or manufacturing doohickey.}
{59000}{}{Scrap Metal}
{59001}{}{Scrap Metal.}
{59100}{}{Asztal}
{59101}{}{Ez a fémből készült asztal látszólag nagyon jó állapotban van. Van egy lefolyó a közepén.}
{59200}{}{Asztal}
{59201}{}{Ez a fémből készült asztal látszólag nagyon jó állapotban van. Van egy lefolyó a közepén.}
{59300}{}{Asztal}
{59301}{}{Ezen a fémasztalon valami szerves tócsa terpeszkedik.}
{59400}{}{Asztal}
{59401}{}{Ezen a fémasztalon valami szerves tócsa terpeszkedik.}
{59500}{}{Asztal}
{59501}{}{Ezen a fémasztalon valami szerves tócsa terpeszkedik.}
{59600}{}{Hirdetőtábla}
{59601}{}{Különböző munkahirdetés van felragasztva a táblára. Látszólag elég gyakran használják.}
{59700}{}{Shack}
{59701}{}{This shack is over a hundred years old, but still in excellent condition.}
{59800}{}{Tábla}
{59801}{}{"Szatócsbolt".}
{59900}{}{Tábla}
{59901}{}{"Szatócsbolt".}
{60000}{}{Tábla}
{60001}{}{Az van rajta, hogy "Piac".}
{60100}{}{Medence}
{60101}{}{Nagyon egészségtelennek tűnik. Mielőtt fürdőt vennél, fel kellene venned egy páncélozott fürdőruhát.}
{60200}{}{Medence}
{60201}{}{Nagyon egészségtelennek tűnik. Mielőtt fürdőt vennél, fel kellene venned egy páncélozott fürdőruhát.}
{60300}{}{Medence}
{60301}{}{Nagyon egészségtelennek tűnik. Mielőtt fürdőt vennél, fel kellene venned egy páncélozott fürdőruhát.}
{60400}{}{Asztal}
{60401}{}{Fémesen csillogó asztal.}
{60500}{}{Asztal}
{60501}{}{Fémesen csillogó asztal.}
{60600}{}{Asztal}
{60601}{}{Fémesen csillogó asztal.}
{60700}{}{Asztal}
{60701}{}{Fémesen csillogó asztal.}
{60800}{}{Asztal}
{60801}{}{Ezt a fémasztalt nagyon nem gondozzák. A rozsda már teljesen átütött rajta.}
{60900}{}{Asztal}
{60901}{}{Nagyon jól nézne ki az asztal, ha nem lenne ennyire rozsdás.}
{61000}{}{Asztal}
{61001}{}{Nagyon jól nézne ki az asztal, ha nem lenne ennyire rozsdás.}
{61100}{}{Asztal}
{61101}{}{Nagyon jól nézne ki az asztal, ha nem lenne ennyire rozsdás.}
{61200}{}{Tűzhely}
{61201}{}{A tűz szelíden ég.}
{61300}{}{Tükör}
{61301}{}{Egy ideig nézegeted magadat.}
{61400}{}{Tükör}
{61401}{}{Egy jó ideig mustrálgatod a tükörképedet.}
{61500}{}{Lefolyó}
{61501}{}{A csap tökéletesen működik. Szép és tiszta.}
{61600}{}{WC}
{61601}{}{A WC mentes a kosztól. És le is lehet húzni.}
{61700}{}{Vizelde}
{61701}{}{Ebbe a vizeldébe még nyugodtan lehet csurgatni.}
{61800}{}{WC}
{61801}{}{Ha lenne egy WC-illatosítód, ez lenne a világ legjobb WC-je.}
{61900}{}{Lefolyó}
{61901}{}{A mosdó kifogástalan állapotban van.}
{62000}{}{Vizelde}
{62001}{}{A vizelde agyszerű állapotban van. Fél szemmel is tökéletes.}
{62100}{}{Zuhanyzó}
{62101}{}{Katonai zuhany. Szemérmes emberek alapból nem is használják.}
{62200}{}{Zuhanyzó}
{62201}{}{Katonai zuhany. Szemérmes emberek alapból nem is használják.}
{62300}{}{Zuhanyzó}
{62301}{}{Katonai zuhany. Szemérmes emberek alapból nem is használják.}
{62400}{}{Zuhanyzó}
{62401}{}{Katonai zuhany. Szemérmes emberek alapból nem is használják.}
{62500}{}{Zuhanyzó}
{62501}{}{Katonai zuhany. Szemérmes emberek alapból nem is használják.}
{62600}{}{Zuhanyzó}
{62601}{}{Katonai zuhany. Szemérmes emberek alapból nem is használják.}
{62700}{}{Ágy}
{62701}{}{Ez az ágy nagyon kényelmesnek látszik.}
{62800}{}{Ágy}
{62801}{}{Ez az ágy nagyon kényelmesnek látszik.}
{62900}{}{Ágy}
{62901}{}{Egy megerősített vázú emeletes ágy.}
{63000}{}{Ágy}
{63001}{}{Egy megerősített vázú emeletes ágy.}
{63100}{}{Ágy}
{63101}{}{Egy megerősített vázú emeletes ágy.}
{63200}{}{Terminál}
{63300}{}{Terminál}
{63400}{}{Zászló}
{63401}{}{Ez a zászló a Katedrális Gyermekeinek jelképe.}
{63500}{}{Zászló}
{63501}{}{Ez a zászló a Katedrális Gyermekeinek jelképe.}
{63600}{}{Zászló}
{63601}{}{Ez a zászló a Katedrális Gyermekeinek jelképe.}
{63700}{}{Számítógép}
{63701}{}{Egy hatalmas számítógép.}
{63800}{}{Számítógép}
{63801}{}{Egy hatalmas számítógép.}
{63900}{}{Számítógép}
{63901}{}{Egy hatalmas számítógép.}
{64000}{}{Terminál}
{64001}{}{A terminál egy nagy számítógéphez kapcsolódik.}
{64100}{}{Hulla}
{64101}{}{Úgy látszik, ez az ember kínok között halt meg.}
{64200}{}{Hulla}
{64201}{}{Úgy látszik, ez az ember kínok között halt meg.}
{64300}{}{Hulla}
{64301}{}{Úgy látszik, ez az ember kínok között halt meg.}
{64400}{}{Hulla}
{64401}{}{Úgy látszik, ez az ember kínok között halt meg.}
{64500}{}{Ajtó}
{64501}{}{Ez az elreteszelt ajtó tökéletesen megfelel cellaajtónak.}
{64600}{}{Terminál}
{64700}{}{Terminál}
{64800}{}{Targonca}
{64801}{}{A targonca nem működik.}
{64900}{}{Targonca}
{64901}{}{A targonca nem működik.}
{65000}{}{Berendezés}
{65100}{}{Orvosi asztal}
{65101}{}{Ez az asztal nagyon rozsdaette. Az asztal közepén lévő lyuk el van dugulva.}
{65200}{}{Orvosi asztal}
{65201}{}{Rettenetesen megfertőzte a rozsda.}
{65300}{}{Kapu}
{65301}{}{A kapun van egy retesz, ami fel és le jár.}
{65400}{}{Cső}
{65500}{}{Cső}
{65600}{}{Generátor}
{65601}{}{Egy Kandó Elek-Trobox típusú generátor. A háború utáni elterjedt tartalékgenerátor-fajta.}
{65700}{}{Tartály}
{65701}{}{Egy óriási víztartály. Megfigyeléseid alapján rendesen karbantartják és ez annyira fantasztikus!}
{65800}{}{Szekrény}
{65801}{}{Egy rendőrségi szekrény még Angliából, kb. 1960-ból.}
{65900}{}{Asztal}
{65901}{}{Egy ízlésesen elkészített asztal. Kézzel csináltak rajta mindent, de ettől függetlenül a legszebb, amit valaha láttál.}
{66000}{}{Asztal}
{66001}{}{Egy ízlésesen elkészített asztal. Kézzel csináltak rajta mindent, de ettől függetlenül a legszebb, amit valaha láttál.}
{66100}{}{Asztal}
{66101}{}{Egy ízlésesen elkészített asztal. Kézzel csináltak rajta mindent, de ettől függetlenül a legszebb, amit valaha láttál.}
{66200}{}{Szék}
{66201}{}{Egy gyönyörű szék.}
{66300}{}{Szék}
{66301}{}{Egy gyönyörű szék.}
{66400}{}{Szék}
{66401}{}{Egy gyönyörű szék.}
{66500}{}{Szék}
{66501}{}{Egy gyönyörű szék.}
{66600}{}{Szék}
{66601}{}{Egy gyönyörű szék.}
{66700}{}{Szék}
{66701}{}{Egy gyönyörű szék.}
{66800}{}{Szék}
{66801}{}{Egy gyönyörű szék.}
{66900}{}{Szék}
{66901}{}{Egy gyönyörű szék.}
{67000}{}{Szék}
{67001}{}{Egy gyönyörű szék.}
{67100}{}{Szék}
{67101}{}{Egy gyönyörű szék.}
{67200}{}{Szék}
{67201}{}{Egy gyönyörű szék.}
{67300}{}{Szék}
{67301}{}{Egy gyönyörű szék.}
{67400}{}{Szék}
{67401}{}{Egy gyönyörű szék.}
{67500}{}{Szék}
{67501}{}{Egy gyönyörű szék.}
{67600}{}{Szék}
{67601}{}{Egy gyönyörű szék.}
{67700}{}{Szék}
{67701}{}{Egy gyönyörű szék.}
{67800}{}{Ágy}
{67801}{}{Kifogástalan.}
{67900}{}{Ágy}
{67901}{}{Kifogástalan.}
{68000}{}{Ágy}
{68001}{}{Kifogástalan.}
{68100}{}{Ágy}
{68101}{}{Kifogástalan.}
{68200}{}{Kályha}
{68201}{}{Egy még most is használható fatüzelésű kályha.}
{68300}{}{Kályha}
{68301}{}{Egy még most is használható fatüzelésű kályha.}
{68400}{}{Kályha}
{68401}{}{Egy még most is használható fatüzelésű kályha.}
{68500}{}{Kályha}
{68501}{}{Egy még most is használható fatüzelésű kályha.}
{68600}{}{Törött oszlop}
{68700}{}{Lerombolt bejárat}
{68800}{}{Kövek}
{68801}{}{Ezek a kövek valamilyen alakzatot formálnak. Ez nem tűnik számodra természetesnek.}
{68900}{}{Kövek}
{68901}{}{Ezek a kövek valamilyen alakzatot formálnak. Ez nem tűnik számodra természetesnek.}
{69000}{}{WC}
{69001}{}{Egy egyszerű, de nagyszerű WC. Néhány levél van a lyukba dobva, ami megpróbálja elfedni az illatokat.}
{69100}{}{Hegy}
{69101}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{69200}{}{Hegy}
{69201}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{69300}{}{Hegy}
{69301}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{69400}{}{Hegy}
{69401}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{69500}{}{Hegy}
{69501}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{69600}{}{Hegy}
{69601}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{69700}{}{Trutymó}
{69701}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{69800}{}{Trutymó}
{69801}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{69900}{}{Trutymó}
{69901}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70000}{}{Trutymó}
{70001}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70100}{}{Trutymó}
{70101}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70200}{}{Trutymó}
{70201}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70300}{}{Trutymó}
{70301}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70400}{}{Trutymó}
{70401}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70500}{}{Trutymó}
{70501}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70600}{}{Trutymó}
{70601}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70700}{}{Trutymó}
{70701}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70800}{}{Trutymó}
{70801}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{70900}{}{Trutymó}
{70901}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71000}{}{Trutymó}
{71001}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71100}{}{Trutymó}
{71101}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71200}{}{Trutymó}
{71201}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71300}{}{Trutymó}
{71301}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71400}{}{Trutymó}
{71401}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71500}{}{Trutymó}
{71501}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71600}{}{Trutymó}
{71601}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71700}{}{Trutymó}
{71701}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71800}{}{Trutymó}
{71801}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{71900}{}{Trutymó}
{71901}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72000}{}{Trutymó}
{72001}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72100}{}{Trutymó}
{72101}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72200}{}{Trutymó}
{72201}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72300}{}{Trutymó}
{72301}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72400}{}{Trutymó}
{72401}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72500}{}{Trutymó}
{72501}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72600}{}{Trutymó}
{72601}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72700}{}{Trutymó}
{72701}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72800}{}{Trutymó}
{72801}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{72900}{}{Trutymó}
{72901}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73000}{}{Trutymó}
{73001}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73100}{}{Trutymó}
{73101}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73200}{}{Trutymó}
{73201}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73300}{}{Trutymó}
{73301}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73400}{}{Trutymó}
{73401}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73500}{}{Trutymó}
{73501}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73600}{}{Trutymó}
{73601}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73700}{}{Trutymó}
{73701}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73800}{}{Trutymó}
{73801}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{73900}{}{Trutymó}
{73901}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74000}{}{Trutymó}
{74001}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74100}{}{Trutymó}
{74101}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74200}{}{Trutymó}
{74201}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74300}{}{Trutymó}
{74301}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74400}{}{Trutymó}
{74401}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74500}{}{Trutymó}
{74501}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74600}{}{Trutymó}
{74601}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74700}{}{Trutymó}
{74701}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74800}{}{Trutymó}
{74801}{}{Nem látszik se egészségesnek, se szervetlennek, se átlagosnak.}
{74900}{}{Számítógép}
{74901}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75000}{}{Számítógép}
{75001}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75100}{}{Számítógép}
{75101}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75200}{}{Számítógép}
{75201}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75300}{}{Számítógép}
{75301}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75400}{}{Számítógép}
{75401}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75500}{}{Számítógép}
{75501}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75600}{}{Számítógép}
{75601}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75700}{}{Számítógép}
{75701}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75800}{}{Számítógép}
{75801}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{75900}{}{Számítógép}
{75901}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{76000}{}{Számítógép}
{76001}{}{A számítógépre rakódott truty-lé nagyon megnehezíti a használatát.}
{76100}{}{Monitorok}
{76101}{}{A rácsapódott nagy mennyiségű trutyi miatt semmit nem tudsz elolvasni a monitorokon.}
{76200}{}{Monitorok}
{76201}{}{A rácsapódott nagy mennyiségű trutyi miatt semmit nem tudsz elolvasni a monitorokon.}
{76300}{}{Monitorok}
{76301}{}{A rácsapódott nagy mennyiségű trutyi miatt semmit nem tudsz elolvasni a monitorokon.}
{76400}{}{Monitorok}
{76401}{}{A rácsapódott nagy mennyiségű trutyi miatt semmit nem tudsz elolvasni a monitorokon.}
{76500}{}{UNUSED ART}
{76600}{}{UNUSED ART}
{76700}{}{Padló}
{76800}{}{Bomba}
{76801}{}{Ez egy atombomba. Szerintem nem kellene tétlenül üldögélned! (a narrátor)}
{76900}{}{Bázis}
{76901}{}{Itt nyugszik az atombomba.}
{77000}{}{Számítógépes konzol}
{77001}{}{Ez az atombombát vezérlő számítógép. Nagyon levédettnek tűnik, és van egy nyílás rajta valami furcsa alakú kulcsnak.}
{77100}{}{Vezetékek}
{77101}{}{Ezek a vezetékek kötik a bombát a számítógéphez.}
{77200}{}{Szék}
{77201}{}{Semmi szokatlan.}
{77300}{}{Szék}
{77301}{}{Semmi szokatlan.}
{77400}{}{Szék}
{77401}{}{Semmi szokatlan.}
{77500}{}{Szék}
{77501}{}{Semmi szokatlan.}
{77600}{}{Szék}
{77601}{}{Semmi szokatlan.}
{77700}{}{Szék}
{77701}{}{Semmi szokatlan.}
{77800}{}{Szék}
{77801}{}{Semmi szokatlan.}
{77900}{}{Szék}
{77901}{}{Semmi szokatlan.}
{78000}{}{Pillér}
{78001}{}{Ezt azt oszlopot valaminek a megtámasztására használják.}
{78100}{}{Pillér}
{78101}{}{Ezt azt oszlopot valaminek a megtámasztására használják.}
{78200}{}{Pillér}
{78201}{}{Ezt azt oszlopot valaminek a megtámasztására használják.}
{78300}{}{Pillér}
{78301}{}{Ezt azt oszlopot valaminek a megtámasztására használják.}
{78400}{}{Ágy}
{78401}{}{Szánalmas, ahogy kinéz.}
{78500}{}{Ágy}
{78501}{}{Nincs valami komfortos kinézete.}
{78600}{}{Ágy}
{78601}{}{Az állapota válságos, de nem súlyos.}
{78700}{}{Ágy}
{78701}{}{Eléggé rosszul néz ki.}
{78800}{}{Monitorok}
{78801}{}{Ezek a monitorok ripityára vannak törve és nem is műkődnek.}
{78900}{}{Monitorok}
{78901}{}{Ezek a monitorok ripityára vannak törve és nem is műkődnek.}
{79000}{}{Monitorok}
{79001}{}{Ezek a monitorok ripityára vannak törve és nem is műkődnek.}
{79100}{}{Monitorok}
{79101}{}{Ezek a monitorok ripityára vannak törve és nem is műkődnek.}
{79200}{}{Szellőző}
{79201}{}{Csak egy nagyon parányi friss levegő érkezik ezen a szerkezeten keresztül.}
{79300}{}{Szellőző}
{79301}{}{Szinte alig érezhető friss levegő jön belőle.}
{79400}{}{Szellőző}
{79401}{}{Semmi friss levegő nem jő'.}
{79500}{}{Szellőző}
{79501}{}{Észrevétlenül kicsiny mennyiségű tiszta és friss levegőt érzel.}
{79600}{}{Asztal}
{79601}{}{Semmi feltűnő nincs ezen az asztalon, eltekintve attól, hogy már nagyon a végét járja.}
{79700}{}{Asztal}
{79701}{}{Az asztal romokban áll. Kész csoda, hogy még áll egyáltalán.}
{79800}{}{Asztal}
{79801}{}{Nagyon lepusztult státuszban van.}
{79900}{}{Asztal}
{79901}{}{Minek akarod átkutatni ezt az asztalt?}
{80000}{}{Monitorok}
{80001}{}{Az itt lévő monitorok képernyői megsemmisültek.}
{80100}{}{Monitorok}
{80101}{}{A monitorok képernyői megsérültek és éppen javítás alatt állnak.}
{80200}{}{Monitor}
{80201}{}{A képernyő össze van törve, a monitor pedig tönkrement.}
{80300}{}{Monitor}
{80301}{}{Ez a monitor szinte értéktelen egy elromlott képernyővel.}
{80400}{}{Számítógép}
{80401}{}{Használhatatlan.}
{80500}{}{Számítógép}
{80501}{}{Használhatatlan.}
{80600}{}{Számítógép}
{80601}{}{Használhatatlan.}
{80700}{}{Szék}
{80701}{}{El van rongyolódva.}
{80800}{}{Szék}
{80801}{}{El van rongyolódva.}
{80900}{}{Szék}
{80901}{}{El van rongyolódva.}
{81000}{}{Szék}
{81001}{}{El van rongyolódva.}
{81100}{}{Szellőző}
{81101}{}{Valami gondja van; javítás alatt áll.}
{81200}{}{Szellőző}
{81201}{}{Ez a példány nagyon súlyos károkat szenvedett el, nem lehet rendbehozni.}
{81300}{}{Szellőző}
{81301}{}{Ez a szellőztető nem teljesen működik.}
{81400}{}{Számítógép}
{81401}{}{Ez a számítógép alig-alig működik.}
{81500}{}{Számítógép}
{81501}{}{Ez a számítógép alig-alig működik.}
{81600}{}{Monitor}
{81601}{}{Ez a monitor se húzza már sokáig.}
{81700}{}{Monitor}
{81701}{}{Ez a monitor se húzza már sokáig.}
{81800}{}{Számítógép}
{81801}{}{Egyszerűen nem működik.}
{81900}{}{Számítógép}
{81901}{}{Egyszerűen nem működik.}
{82000}{}{Monitor}
{82001}{}{Képtelen!}
{82100}{}{Monitor}
{82101}{}{Képtelen!}
{82200}{}{Ajtó}
{82201}{}{Szemrevételezésed szerint ez egy nagyon szép ajtókeret. Sőt, eredeti funkcióját (mint az ajtó kerete) is nagyszerűen betölti.}
{82300}{}{Monitorok}
{82301}{}{Ezek a monitorok eléggé jó állapotban vannak (egyelőre).}
{82400}{}{Monitorok}
{82401}{}{Ezek a monitorok eléggé jó állapotban vannak (egyelőre).}
{82500}{}{Fal}
{82600}{}{Nagyajtó}
{82601}{}{Egy nagyon komoly és vaskos menedékajtó. Ez az ajtó áthatolhatatlannak látszik.}
{82700}{}{Könnyű}
{82701}{}{Egy biztonsági lámpa.}
{82800}{}{Könnyű}
{82801}{}{Egy biztonsági lámpa.}
{82900}{}{Pillér}
{82901}{}{Pillar.}
{83000}{}{Robottároló}
{83001}{}{Ez egy raktár. Amikor a robotok nincsenek szolgálatban, ide állnak be, kikapcsolnak, majd feltöltődnek.}
{83100}{}{Robottároló}
{83101}{}{Ez egy raktár. Amikor a robotok nincsenek szolgálatban, ide állnak be, kikapcsolnak, majd feltöltődnek.}
{83200}{}{Robottároló}
{83201}{}{Ez egy raktár. Amikor a robotok nincsenek szolgálatban, ide állnak be, kikapcsolnak, majd feltöltődnek.}
{83300}{}{Robottároló}
{83301}{}{Ez egy raktár. Amikor a robotok nincsenek szolgálatban, ide állnak be, kikapcsolnak, majd feltöltődnek.}
{83400}{}{Robottároló}
{83401}{}{Ez egy raktár. Amikor a robotok nincsenek szolgálatban, ide állnak be, kikapcsolnak, majd feltöltődnek.}
{83500}{}{Gép}
{83501}{}{A gép robotállomáson dolgozik valamit. Annyira nem tűnik érdekesnek.}
{83600}{}{Gép}
{83601}{}{Ez a gép csinál valamit robotok szervízállomásával. Nagyon nem tudott felajzani.}
{83700}{}{Csík}
{83800}{}{Csík}
{83900}{}{Csík}
{84000}{}{Csík}
{84100}{}{Csík}
{84200}{}{Csík}
{84300}{}{Csík}
{84400}{}{Csík}
{84500}{}{Csík}
{84600}{}{Csík}
{84700}{}{Csík}
{84800}{}{Ajtó}
{84801}{}{Egy nagyon-nagyon is átlagos fa ajtó.}
{84900}{}{Ajtó}
{84901}{}{Egy nagyon-nagyon is átlagos fa ajtó.}
{85000}{}{Ajtó}
{85001}{}{Egy nagyon-nagyon is átlagos fa ajtó.}
{85100}{}{Tábla}
{85101}{}{A tábla a "Baráti Kölcsön Bt."-é.}
{85200}{}{Embléma}
{85201}{}{Ez valami vallásos jelképnek tűnik.}
{85300}{}{Orvosi asztal}
{85301}{}{Ez pont úgy néz ki, mint egy egészségügyi vizsgálóasztal.}
{85400}{}{Tábla}
{85401}{}{Ez a neonfelirat a "Máltai Sólyom" hirdetésére szolgál.}
{85500}{}{Graffiti}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Tábla}
{86901}{}{Assz'ondja: "FEGYVEREK". Ott akkor bizonyára fegyvereket árulnak.}
{87000}{}{Tábla}
{87001}{}{A tábla szerint ez a "Rendőrség".}
{87100}{}{Tábla}
{87101}{}{Ez a "Hosszú-Távú Kereskedők" táblája.}
{87200}{}{Tábla}
{87201}{}{A táblán a betűk a következő szót formálják: "Fegyverkereskedők".}
{87300}{}{Tábla}
{87301}{}{Ez a "Karmazsin Karaván" kereskedelmi vállalat cégtáblája.}
{87400}{}{Tábla}
{87401}{}{"Kórház". Biztos jó lehet.}
{87500}{}{Tábla}
{87501}{}{Ön most a "Vászon Ház" tábláját olvassa fel a narrátorral.}
{87600}{}{Tábla}
{87601}{}{Ezen a semmitmondó táblácskán az olvasható, hogy "Bob Korábban Már Használt Autók Piaca".}
{87700}{}{Tábla}
{87701}{}{Ez a tábla a Vízkereskedőké, ami a Központ egyik kis cége.}
{87800}{}{Tojáshéj}
{87801}{}{Egy széttörött tojás darabjai.}
{87900}{}{Tojáshéj}
{87901}{}{Egy széttörött tojás darabjai.}
{88000}{}{Tojáshéj}
{88001}{}{Egy széttörött tojás darabjai.}
{88100}{}{Tojáshéj}
{88101}{}{Egy széttörött tojás darabjai.}
{88200}{}{Small rocks}
{88201}{}{Scattered small rocks.}
{88300}{}{Small rocks}
{88301}{}{Scattered small rocks.}
{88400}{}{Small rocks}
{88401}{}{Scattered small rocks.}
{88500}{}{Tojáshéj}
{88501}{}{Egy széttörött tojás darabjai.}
{88600}{}{Lámpaoszlop}
{88601}{}{Egy lámpaoszlop. Látszólag minden rendben van vele.}
{88700}{}{Tábla}
{88701}{}{A tábla szövege: "Panzió".}
{88800}{}{Gombák}
{88801}{}{Ez a cserép tele van trágyával, amiben boldogan növekvő gombákat látsz.}
{88900}{}{Gombák}
{88901}{}{Ez a cserép tele van trágyával, amiben boldogan növekvő gombákat látsz.}
{89000}{}{Csontváz}
{89100}{}{Tábla}
{89101}{}{Ez van ráírva: "Börtön".}
{89200}{}{Tábla}
{89201}{}{A tábla szerint ez a "Ürrgejuk" nevű kocsma és elmegyógyintézet.}
{89300}{}{Tábla}
{89301}{}{Ez a hirdetés a Penge márkájú borotvapengéé.}
{89400}{}{Zuhanyzó}
{89401}{}{Egy nagyjából tűrhető zuhanyzó.}
{89500}{}{Zuhanyzó}
{89501}{}{Egy nagyjából tűrhető zuhanyzó.}
{89600}{}{Tábla}
{89601}{}{Ez a "Baráti Kölcsön Bt." táblája.}
{89700}{}{Tábla}
{89701}{}{Ez a "Baráti Kölcsön Bt." táblája.}
{89800}{}{Plakát}
{89801}{}{Ez a plakát egy horrorfilmhez tartozik, még a háború előtti időkből.}
{89900}{}{Plakát}
{89901}{}{Ez a plakát egy horrorfilmhez tartozik, még a háború előtti időkből.}
{90000}{}{Pult}
{90001}{}{Egy urna pihen a bárpulton. Az urna egy kissé viharvertnek tűnik, de attól még értékes lehet.}
{90100}{}{Liftakna}
{90101}{}{Az aknában egy kötél lóg le a felsőbb szintről.}
{90200}{}{Liftakna}
{90201}{}{Egy kötél lóg lefelé az akna széléről.}
{90300}{}{Orvosi ágy}
{90301}{}{Az ágyhoz tartozik egy beépített kijelző, ami a páciens állapotát figyeli.}
{90400}{}{Vízpumpa}
{90401}{}{Ez a gép a vizet pumpálja fel az alacsonyabban fekvő helyekről.}
{90500}{}{Orvosi ágy}
{90501}{}{Az ágyhoz tartozik egy beépített kijelző, ami a páciens állapotát figyeli.}
{90600}{}{Energiapáncél-darabok}
{90601}{}{Ezek a részek alkotják a híres Energiapáncélt.}
{90700}{}{Könnyű}
{90701}{}{Ez az élénkvörös biztonsági lámpa folyamatosan villog.}
{90800}{}{Könnyű}
{90801}{}{Ez az élénkvörös biztonsági lámpa folyamatosan villog.}
{90900}{}{Szimbólum}
{91000}{}{Szimbólum}
{91100}{}{Szimbólum}
{91200}{}{Szimbólum}
{91300}{}{Szimbólum}
{91400}{}{Szimbólum}
{91500}{}{Kötél}
{91600}{}{Kötél}
{91700}{}{Kötél}
{91800}{}{Kötél}
{91900}{}{Kötél}
{92000}{}{Kötél}
{92100}{}{Kötél}
{92200}{}{Kötél}
{92300}{}{Kanyon}
{92400}{}{Kanyon}
{92500}{}{Kanyon}
{92600}{}{Kanyon}
{92700}{}{Kanyon}
{92800}{}{Kanyon}
{92900}{}{Kanyon}
{93000}{}{Kanyon}
{93100}{}{Barlang kövezet}
{93200}{}{Nyithatatlan ajtó}
{93201}{}{Úgy látszik, ennek az ajtónak nincs nyitómechanizmusa.}
{93300}{}{Lerombolt ajtó}
{93301}{}{Az ajtó ki lett robbantva.}
{93400}{}{Ajtó}
{93401}{}{Egy ajtó, bonyolult zárral.}
{93500}{}{Fáklya}
{93501}{}{Egy égő fáklya a falon.}
{93600}{}{Fáklya}
{93601}{}{Egy égő fáklya a falon.}
{93700}{}{Emlékmű}
{93800}{}{Emlékmű}
{93900}{}{Emlékmű}
{94000}{}{Koponyatartó}
{94001}{}{Egy rúd, amire emberi koponyák vannak függesztve.}
{94100}{}{Koponyatartó}
{94101}{}{Egy rúd, amire emberi koponyák vannak függesztve.}
{94200}{}{Koponyatartó}
{94201}{}{Egy rúd, amire emberi koponyák vannak függesztve.}
{94300}{}{Növény}
{94301}{}{}
{94400}{}{Növény}
{94500}{}{Fa}
{94600}{}{Fa}
{94700}{}{Fa}
{94800}{}{Ágy}
{94900}{}{Ágy}
{95000}{}{Lyuk}
{95001}{}{Egy gyanús lyuk a falban.}
{95100}{}{Kiemelkedő kőlap}
{95101}{}{Egy kibukkanó kőlap.}
{95200}{}{Tönkrement kőlap}
{95201}{}{Ez a kőlap már nem lát el semmilyen funkciót.}
{95300}{}{Benyomott kőlap}
{95301}{}{Egy lenyomódott kőlap.}
{95400}{}{Ajtó}
{95500}{}{Ajtó}
{95600}{}{Ajtó}
{95700}{}{Ajtó}
{95800}{}{Ajtó}
{95900}{}{Ajtó}
{96000}{}{Ajtó}
{96100}{}{Ajtó}
{96200}{}{Ajtó}
{96300}{}{Növény}
{96301}{}{Egy mutáns kukoricacsutka.}
{96400}{}{Növény}
{96401}{}{Egy mutáns kukoricacsutka.}
{96500}{}{Növény}
{96501}{}{Kukorica ala mutáció. Ez undorító.}
{96600}{}{Növény}
{96601}{}{Egy mutáns kukoricacsutka.}
{96700}{}{Növény}
{96701}{}{Egy mutáns kukoricacsutka.}
{96800}{}{Növény}
{96801}{}{Egy mutáns kukoricacsutka.}
{96900}{}{Fa támaszték}
{97000}{}{Fa támaszték}
{97100}{}{Fa támaszték}
{97200}{}{Fa támaszték}
{97300}{}{Fa támaszték}
{97400}{}{Fa támaszték}
{97500}{}{Sérült fa támaszték}
{97501}{}{Úgy látszik, ez a támaszték könnyen összeroppanna, ha egy kicsit nagyobb terhelés érné.}
{97600}{}{Beomlott padló}
{97601}{}{A kőpadló ezen a ponton omlott le az alatta lévő szintre.}
{97700}{}{Létra lefelé}
{97701}{}{Ez egy emberméretű nyílás, amiben egy létra vezet lefelé.}
{97800}{}{Ajtó}
{97900}{}{Fal}
{98000}{}{"5-ÖS REAKTOR"}
{98100}{}{Ajtó}
{98200}{}{Ajtó}
{98300}{}{Ajtó}
{98400}{}{Ajtó}
{98500}{}{Radioaktív trutyi}
{98600}{}{Radioaktív trutyi}
{98700}{}{Radioaktív trutyi}
{98800}{}{Radioaktív trutyi}
{98900}{}{Biztonsági ajtó}
{99000}{}{Menedék-ajtó}
{99100}{}{Rakodódaru}
{99200}{}{Rakodódaru}
{99300}{}{Kut}
{99400}{}{Kut}
{99500}{}{Melléképület}
{99600}{}{Lyuk}
{99601}{}{Nem látod a gödör mélyét.}
{99700}{}{Padlólap}
{99701}{}{Egy padlólapnak álcázott csapdát látsz.}
{99800}{}{Tönkrement padlólap}
{99801}{}{Ez a padlólapnak látszó csapda már nem jelenthet veszélyt neked.}
{99900}{}{Bekapcsolt padlólap}
{99901}{}{This floor plate trap has been triggered. Oops!}
{100000}{}{Szeszfőzde}
{100001}{}{Hm, ez egy fával tüzelt szeszkazán.}
{100100}{}{Radscorpion Parts}
{100101}{}{Nem látsz mást, csak egy halom radskorpió-darabot. Át vannak lyukasztva és egy kampót akasztottak beléjük.}
{100200}{}{Power plant Machinery}
{100201}{}{A reaktor egyik tartozéka, egy plutónium-gamma pajzs.}
{100300}{}{Power plant Machinery}
{100301}{}{A gép a reaktorhoz tartozik. Ez egy Jupiter térkiegyenlítő.}
{100400}{}{Power plant Machinery}
{100401}{}{Ez a reaktorhoz kapcsolódik. Egy uránrúd-kalibrátor.}
{100500}{}{Power plant Machinery}
{100501}{}{Ez egy neptúnium terelőlapát. A reaktor egyik gépe.}
{100600}{}{Erőművi gépezet}
{100601}{}{Saturn típusú kondenzátor, ami a reaktor eleme.}
{100700}{}{Erőművi pumpa}
{100701}{}{Ez a hűtést irányító pumpálógép a reaktor részeleme.}
{100800}{}{A brahmin oldala}
{100900}{}{Autó}
{101000}{}{Chrysalis}
{101001}{}{A Chrysalis autógyár "Highwayman" típusú modellje. A korához képest elég jó formában van.}
{101100}{}{Autó}
{101200}{}{Sírhely}
{101201}{}{Egy sírhely található itt.}
{101300}{}{Sírkő}
{101301}{}{Sírkő}
{101400}{}{Sírkő}
{101401}{}{Sírkő}
{101500}{}{Sírkő}
{101501}{}{Sírkő}
{101600}{}{Sírkő}
{101601}{}{Sírkő}
{101700}{}{Eke}
{101701}{}{Ezt ez ekét arra tervezték, hogy egy brahmin húzza.}
{101800}{}{Eke}
{101801}{}{Ezt ez ekét arra tervezték, hogy egy brahmin húzza.}
{101900}{}{Víz}
{102000}{}{Tábla}
{102001}{}{"New Reno"}
{102100}{}{Tábla}
{102101}{}{"New Reno"}
{102200}{}{Tábla}
{102201}{}{"New Reno"}
{102300}{}{Tábla}
{102301}{}{"New Reno"}
{102400}{}{Tábla}
{102401}{}{"New Reno"}
{102500}{}{Tábla}
{102501}{}{"New Reno"}
{102600}{}{Árnyék}
{102700}{}{Árnyék}
{102800}{}{Árnyék}
{102900}{}{Graffiti}
{103000}{}{Graffiti}
{103100}{}{Graffiti}
{103200}{}{Graffiti}
{103300}{}{Graffiti}
{103400}{}{Graffiti}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Graffiti}
{104800}{}{Graffiti}
{104900}{}{Graffiti}
{105000}{}{Graffiti}
{105100}{}{Graffiti}
{105200}{}{Graffiti}
{105300}{}{Graffiti}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Graffiti}
{105800}{}{Graffiti}
{105900}{}{Graffiti}
{106000}{}{Tábla}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Graffiti}
{107200}{}{Graffiti}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Graffiti}
{108800}{}{Graffiti}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Graffiti}
{109900}{}{Graffiti}
{110000}{}{Graffiti}
{110100}{}{Graffiti}
{110200}{}{Graffiti}
{110300}{}{Graffiti}
{110400}{}{Graffiti}
{110500}{}{Graffiti}
{110600}{}{Graffiti}
{110700}{}{Graffiti}
{110800}{}{Graffiti}
{110900}{}{Graffiti}
{111000}{}{Tábla}
{111100}{}{Tábla}
{111200}{}{Tábla}
{111300}{}{Tábla}
{111400}{}{Tábla}
{111500}{}{Tábla}
{111600}{}{Tábla}
{111700}{}{Tábla}
{111800}{}{Tapéta}
{111900}{}{Tapéta}
{112000}{}{Tapéta}
{112100}{}{Tapéta}
{112200}{}{Tapéta}
{112300}{}{Tapéta}
{112400}{}{Tapéta}
{112500}{}{Tapéta}
{112600}{}{Tapéta}
{112700}{}{Tapéta}
{112800}{}{Tapéta}
{112900}{}{Tapéta}
{113000}{}{Tapéta}
{113100}{}{Tapéta}
{113200}{}{Tapéta}
{113300}{}{Tapéta}
{113400}{}{Tapéta}
{113500}{}{Tapéta}
{113600}{}{Tapéta}
{113700}{}{Tapéta}
{113800}{}{Tapéta}
{113900}{}{Tapéta}
{114000}{}{Tapéta}
{114100}{}{Filmfelvevő}
{114200}{}{Koporsó}
{114300}{}{Koporsó}
{114400}{}{Koporsó}
{114500}{}{Koporsó}
{114600}{}{Acélrudak}
{114700}{}{Acélrudak}
{114800}{}{Steel Cover}
{114900}{}{Steel Cover}
{115000}{}{Lézeres csapda}
{115100}{}{Lézeres csapda}
{115200}{}{Csille}
{115300}{}{Csille acélrúddal}
{115400}{}{Csille dinamittal}
{115500}{}{"Zárva"}
{115600}{}{"Zárva"}
{115700}{}{"Bordélyház"}
{115800}{}{"Vic"}
{115900}{}{Fal}
{116000}{}{Fal}
{116100}{}{Retinaszkenner}
{116101}{}{Ez egy biztonsági berendezés, ami a retinák leolvasásán és ellenőrzésén alapul.}
{116200}{}{"Irányítószoba"}
{116300}{}{"Irányítószoba"}
{116400}{}{"Irányítószoba"}
{116500}{}{"Építkezés"}
{116600}{}{"Építkezés"}
{116700}{}{Gép}
{116701}{}{Egy üzemképtelen masinéria.}
{116800}{}{Gép}
{116801}{}{Egy üzemképtelen masinéria.}
{116900}{}{Ajtó}
{117000}{}{Ajtó}
{117100}{}{Rusting Pipes}
{117101}{}{A set of rusting old pipes.}
{117200}{}{Tartály}
{117300}{}{Tartályok}
{117400}{}{Tartályok}
{117500}{}{Tartályok}
{117600}{}{Szellőző}
{117700}{}{Szellőző}
{117800}{}{A "Hárfa" cégére}
{117900}{}{Fűrészbak}
{118000}{}{Fűrészbak}
{118100}{}{Fűrészbak}
{118200}{}{Szellőző}
{118300}{}{Szellőző}
{118400}{}{"Gépészbolt"}
{118500}{}{"Menedzseri iroda"}
{118600}{}{"Raktár"}
{118700}{}{"Sugárzásveszély!"}
{118800}{}{Gőz}
{118900}{}{Gép}
{118901}{}{Az erőmű egyik masinája.}
{119000}{}{Tartály}
{119100}{}{Tűz}
{119200}{}{Víz}
{119300}{}{"Prémvadász Város"}
{119400}{}{"Arany Gekkó"}
{119500}{}{"Fürdőház"}
{119600}{}{Barlangrajz}
{119700}{}{Barlangrajz}
{119800}{}{Barlangrajz}
{119900}{}{Barlangrajz}
{120000}{}{Tűzhely}
{120100}{}{Barlangfal}
{120200}{}{Barlangfal}
{120300}{}{Barlangfal}
{120400}{}{Barlangfal}
{120500}{}{Barlangfal}
{120600}{}{Barlangfal}
{120700}{}{Barlangfal}
{120800}{}{Barlangfal}
{120900}{}{Barlangfal}
{121000}{}{Barlangfal}
{121100}{}{Barlangfal}
{121200}{}{Barlangfal}
{121300}{}{Barlangfal}
{121400}{}{Barlangfal}
{121500}{}{Barlangfal}
{121600}{}{Karó}
{121601}{}{Úgy látszik, ebbe a karóba már belehúztak valakit!}
{121700}{}{Karó}
{121701}{}{Úgy látszik, ebbe a karóba már belehúztak valakit!}
{121800}{}{Karó}
{121801}{}{Úgy látszik, ebbe a karóba már belehúztak valakit!}
{121900}{}{Karó}
{121901}{}{Úgy látszik, ebbe a karóba már belehúztak valakit!}
{122000}{}{Karó}
{122001}{}{Úgy látszik, ebbe a karóba már belehúztak valakit!}
{122100}{}{Karó}
{122101}{}{Úgy látszik, ebbe a karóba már belehúztak valakit!}
{122200}{}{Karó}
{122201}{}{Egy koponya látható ízlésesen elhelyezve egy karó tetejébe.}
{122300}{}{Karó}
{122301}{}{Egy koponya látható ízlésesen elhelyezve egy karó tetejébe.}
{122400}{}{Karó}
{122401}{}{Úgy néz ki, ez a karó már csak a hozzátartozó fejet várja.}
{122500}{}{Karó}
{122501}{}{Úgy néz ki, ez a karó már csak a hozzátartozó fejet várja.}
{122600}{}{Karó}
{122601}{}{Úgy néz ki, ez a karó már csak a hozzátartozó fejet várja.}
{122700}{}{Karó}
{122701}{}{Úgy néz ki, ez a karó már csak a hozzátartozó fejet várja.}
{122800}{}{"Körözvény"}
{122801}{}{Ez a kép nagyon hasonlít rád! Pedig a sok akcióban elég nehéz lehetett elkapni a vonásaidat.}
{122900}{}{Padló}
{123000}{}{Kikapcsolt roboagy}
{123001}{}{Egy kissé szétszórt kibernetikus szerkezet.}
{123100}{}{Tarack}
{123101}{}{Ezt a furcsa valamit már láttad valahol. Hol is? Talán a történelem könyvedben. Igen, ez háború előtt ereklye. De hogy kerül ez ide?}
{123200}{}{Tábla}
{123300}{}{Tábla}
{123400}{}{Tábla}
{123500}{}{Tábla}
{123600}{}{Főkapcsoló}
{123700}{}{Kereszt}
{123800}{}{Kereszt}
{123900}{}{Kereszt}
{124000}{}{Kereszt}
{124100}{}{Kereszt}
{124200}{}{Kereszt}
{124300}{}{Benzintöltő}
{124400}{}{Benzintöltő}
{124500}{}{Benzintöltő}
{124600}{}{"Pep benzinkútja" cégér}
{124700}{}{Árnyék}
{124800}{}{Alom}
{124900}{}{Alom}
{125000}{}{Alom}
{125100}{}{Alom}
{125200}{}{Alom}
{125300}{}{Alom}
{125400}{}{"Dusty Ebédlője"}
{125500}{}{Bob és fia}
{125501}{}{Egy utcai árus standja.}
{125600}{}{Bob és fia}
{125601}{}{Egy utcai árus standja.}
{125700}{}{Bob és fia}
{125701}{}{Egy utcai árus standja.}
{125800}{}{Bob és fia}
{125801}{}{Egy utcai árus standja.}
{125900}{}{"ÚKK"}
{126000}{}{"Kongresszusi terem"}
{126100}{}{"Kongresszusi terem"}
{126200}{}{ÚKK plakát}
{126300}{}{ÚKK plakát}
{126400}{}{ÚKK plakát}
{126500}{}{ÚKK plakát}
{126600}{}{"Rawhide Szalon"}
{126700}{}{Tábla}
{126800}{}{Tábla}
{126900}{}{Tábla}
{127000}{}{Tábla}
{127100}{}{Tábla}
{127200}{}{Tábla}
{127300}{}{Kőrakás}
{127301}{}{Ezek a kövek valamit hordanak a szívük alatt.}
{127400}{}{Gerenda}
{127500}{}{Gerenda}
{127600}{}{Gerenda}
{127700}{}{Gerenda}
{127800}{}{Gerenda}
{127900}{}{Gerenda}
{128000}{}{Gerenda}
{128100}{}{Gerenda}
{128200}{}{Gerenda}
{128300}{}{Gerenda}
{128400}{}{Árnyék}
{128500}{}{Árnyék}
{128600}{}{Árnyék}
{128700}{}{Árnyék}
{128800}{}{Árnyék}
{128900}{}{Árnyék}
{129000}{}{Árnyék}
{129100}{}{Árnyék}
{129200}{}{Árnyék}
{129300}{}{Liftpálya}
{129400}{}{Benzintöltő}
{129500}{}{Benzintöltő}
{129600}{}{Benzintöltő}
{129700}{}{Kötél}
{129800}{}{Lyuk}
{129900}{}{Brahminhús}
{130000}{}{Brahminhús}
{130100}{}{Brahminhús}
{130200}{}{Brahminhús}
{130300}{}{Brahminhús}
{130400}{}{Brahminhús}
{130500}{}{Gerenda}
{130600}{}{Gerenda}
{130700}{}{Gerenda}
{130800}{}{Gerenda}
{130900}{}{Gerenda}
{131000}{}{Gerenda}
{131100}{}{Gerenda}
{131200}{}{Gerenda}
{131300}{}{Árnyék}
{131400}{}{Árnyék}
{131500}{}{Árnyék}
{131600}{}{Árnyék}
{131700}{}{Árnyék}
{131800}{}{Árnyék}
{131900}{}{Árnyék}
{132000}{}{Árnyék}
{132100}{}{Vér}
{132200}{}{Vér}
{132300}{}{Vér}
{132400}{}{Vér}
{132500}{}{Vér}
{132600}{}{Vér}
{132700}{}{Vér és csontok}
{132800}{}{Vér és csontok}
{132900}{}{Vér és csontok}
{133000}{}{A barlang szája}
{133100}{}{Felszerelés}
{133200}{}{Felszerelés}
{133300}{}{Felszerelés}
{133400}{}{Felszerelés}
{133500}{}{Számítógép}
{133501}{}{Egy menedékbeli terminál, rákapcsolódva a Menedék főszámítógépére.}
{133600}{}{Számítógép}
{133601}{}{Egy menedékbeli terminál, rákapcsolódva a Menedék főszámítógépére.}
{133700}{}{Menedékváros kapuja}
{133800}{}{Menedékváros kapuja}
{133900}{}{Fal}
{134000}{}{Fal}
{134100}{}{Fal}
{134200}{}{Fal}
{134300}{}{Fal}
{134400}{}{Fal}
{134500}{}{Fal}
{134600}{}{Fal}
{134700}{}{Ajtó}
{134800}{}{Kirobbantott ajtó}
{134900}{}{Ajtótörmelék}
{135000}{}{Épület}
{135100}{}{Épület}
{135200}{}{Épület}
{135300}{}{Épület}
{135400}{}{Épület}
{135500}{}{Épület}
{135600}{}{Épület}
{135700}{}{Épület}
{135800}{}{Ajtó}
{135900}{}{Templom}
{136000}{}{Templom}
{136100}{}{Templom}
{136200}{}{Templom}
{136300}{}{Templom}
{136400}{}{Templom}
{136500}{}{Tűzhely}
{136600}{}{Tűzhely}
{136700}{}{Tarack}
{136701}{}{Ezt a furcsa valamit már láttad valahol. Hol is? Talán a történelem könyvedben. Igen, ez háború előtt ereklye. De hogy kerül ez ide?}
{136800}{}{Templom}
{136900}{}{Templom}
{137000}{}{Hegy}
{137100}{}{Barlang}
{137200}{}{Ajtósín}
{137300}{}{Fáklya}
{137301}{}{Egy égő fáklya a falon.}
{137400}{}{Fáklya}
{137401}{}{Egy égő fáklya a falon.}
{137500}{}{Fáklya}
{137501}{}{Egy égő fáklya a falon.}
{137600}{}{Fáklya}
{137601}{}{Egy égő fáklya a falon.}
{137700}{}{Gépmadár}
{137701}{}{A large military aircraft.}
{137800}{}{Lerombolt ajtó}
{137801}{}{The rubble completely blocks the entrance.}
{137900}{}{Lerombolt ajtó}
{137901}{}{The rubble completely blocks the entrance.}
{138000}{}{Fal}
{138100}{}{Fal}
{138200}{}{Fal}
{138300}{}{Fal}
{138400}{}{Fal}
{138500}{}{Fal}
{138600}{}{Könnyű}
{138700}{}{Ajtó}
{138800}{}{Ajtó}
{138900}{}{Ajtó}
{139000}{}{Ajtó}
{139100}{}{Ajtó}
{139200}{}{Ajtó}
{139300}{}{Zászló}
{139400}{}{Pózna}
{139500}{}{Pózna}
{139600}{}{Zászló}
{139700}{}{Zászló}
{139800}{}{Pózna}
{139900}{}{Pózna}
{140000}{}{Zászló}
{140100}{}{Árnyék}
{140200}{}{Árnyék}
{140300}{}{Zászló}
{140400}{}{Zászló}
{140500}{}{Zászló}
{140600}{}{Zászló}
{140700}{}{"Cat's Paw"}
{140800}{}{"Cat's Paw"}
{140900}{}{Tábla}
{141000}{}{Jungle edzőterem cégére}
{141100}{}{Jungle edzőterem cégére}
{141200}{}{Jungle edzőterem cégére}
{141300}{}{"Renesco Patikája"}
{141400}{}{"New Reno-i fegyverbolt"}
{141500}{}{"Salvatore bárja"}
{141600}{}{Szobor}
{141700}{}{Raktárház ajtaja}
{141800}{}{Raktárház ajtaja}
{141900}{}{"Johnson doki"}
{142000}{}{"Seriff"}
{142100}{}{"Malamut Szalon"}
{142200}{}{"Morningstar bánya"}
{142300}{}{Kokoweef Mine Sign}
{142400}{}{Kokoweef Mine Sign}
{142500}{}{Kokoweef Mine Sign}
{142600}{}{Útjelző}
{142601}{}{Ez a fából készült tábla New Reno és a "Pokol" felé mutat. Arra gyanakszol, hogy felcserélték az irányokat.}
{142700}{}{"1"}
{142800}{}{"2"}
{142900}{}{"3"}
{143000}{}{"4"}
{143100}{}{"5"}
{143200}{}{"6"}
{143300}{}{Kötél}
{143301}{}{Ezzel a kötéllel át tudsz mászni a falon.}
{143400}{}{Ajtó}
{143500}{}{Ajtó}
{143600}{}{Ablak}
{143700}{}{Ablak}
{143800}{}{Ablak}
{143900}{}{Ablak}
{144000}{}{Ablak}
{144100}{}{Ablak}
{144200}{}{Ablak}
{144300}{}{Ablak}
{144400}{}{Ablak}
{144500}{}{Ablak}
{144600}{}{Ablak}
{144700}{}{Ablak}
{144800}{}{Medencelétra}
{144900}{}{Ajtó}
{145000}{}{Boltív}
{145100}{}{Boltív}
{145200}{}{Boltív}
{145300}{}{Boltív}
{145400}{}{Boltív}
{145500}{}{Boltív}
{145600}{}{Boltív}
{145700}{}{Boltív}
{145800}{}{Árnyék}
{145900}{}{Árnyék}
{146000}{}{Árnyék}
{146100}{}{Boltív}
{146200}{}{Boltív}
{146300}{}{Boltív}
{146400}{}{Árnyék}
{146500}{}{Árnyék}
{146600}{}{Kiskapu}
{146700}{}{Kiskapu}
{146800}{}{Parancsnoki szék}
{146801}{}{Ez az a hely, ahol általában a Felvigyázó ülni szokott.}
{146900}{}{Szakadék}
{147000}{}{Szakadék}
{147100}{}{Szakadék}
{147200}{}{Szakadék}
{147300}{}{A kaszinó bejárata}
{147400}{}{A kaszinó bejárata}
{147500}{}{Szőnyeg}
{147600}{}{A kaszinó bejárata}
{147700}{}{A kaszinó bejárata}
{147800}{}{A kaszinó bejárata}
{147900}{}{Kaszinóajtó}
{148000}{}{Kaszinóajtó}
{148100}{}{A kaszinó bejárata}
{148200}{}{A kaszinó bejárata}
{148300}{}{A kaszinó bejárata}
{148400}{}{A kaszinó bejárata}
{148500}{}{A kaszinó bejárata}
{148600}{}{A kaszinó bejárata}
{148700}{}{A kaszinó bejárata}
{148800}{}{A kaszinó bejárata}
{148900}{}{A kaszinó bejárata}
{149000}{}{A kaszinó bejárata}
{149100}{}{Kaszinóajtó}
{149200}{}{Kaszinóajtó}
{149300}{}{Falilámpa}
{149400}{}{Falilámpa}
{149500}{}{Falilámpa}
{149600}{}{Falilámpa}
{149700}{}{Falilámpa}
{149800}{}{Fal}
{149900}{}{Fal}
{150000}{}{Ventillátor}
{150100}{}{Ventillátor}
{150200}{}{Fire Ext}
{150300}{}{Fire Ext}
{150400}{}{Cső}
{150500}{}{Elosztó}
{150600}{}{Elosztó}
{150700}{}{Fal}
{150800}{}{Fal}
{150900}{}{Fal}
{151000}{}{Fal}
{151100}{}{Fal}
{151200}{}{Fal}
{151300}{}{Fal}
{151400}{}{Fal}
{151500}{}{Fal}
{151600}{}{Fa borítás}
{151700}{}{Fa borítás}
{151800}{}{Cső}
{151900}{}{Cső}
{152000}{}{Cső}
{152100}{}{Cső}
{152200}{}{Cső}
{152300}{}{Cső}
{152400}{}{Cső}
{152500}{}{Cső}
{152600}{}{Cső}
{152700}{}{Cső}
{152800}{}{Cső}
{152900}{}{Szellőztető}
{153000}{}{Szellőztető}
{153100}{}{Ajtó}
{153200}{}{Ajtó}
{153300}{}{Ajtó}
{153400}{}{Ajtó}
{153500}{}{Ajtó}
{153600}{}{Ajtó}
{153700}{}{Zuhanyzó}
{153800}{}{UNUSED.}
{153900}{}{UNUSED.}
{154000}{}{UNUSED.}
{154100}{}{UNUSED.}
{154200}{}{UNUSED.}
{154300}{}{UNUSED.}
{154400}{}{UNUSED.}
{154500}{}{UNUSED.}
{154600}{}{Hajófal}
{154700}{}{Hajófal}
{154800}{}{Erőtér}
{154900}{}{Erőtér}
{155000}{}{Szerv-eltávolító egység}
{155001}{}{A Menedék-Tek legújabb "Csináld Magad" típusú sebészeti egysége. A kívánt szervet automatikusan eltávolítja egy gombnyomásra.}
{155100}{}{Űrsikló}
{155200}{}{Űrsikló}
{155300}{}{Űrsikló}
{155400}{}{Űrsikló}
{155500}{}{Űrsikló}
{155600}{}{Űrsikló}
{155700}{}{Űrsikló}
{155800}{}{Űrsikló}
{155900}{}{Űrsikló}
{156000}{}{Űrsikló}
{156100}{}{Űrsikló}
{156200}{}{Űrsikló}
{156300}{}{Űrsikló}
{156400}{}{Űrsikló}
{156500}{}{Űrsikló}
{156600}{}{Árnyék}
{156700}{}{Árnyék}
{156800}{}{Árnyék}
{156900}{}{Árnyék}
{157000}{}{Árnyék}
{157100}{}{Árnyék}
{157200}{}{Trónus}
{157300}{}{Ajtó}
{157400}{}{Ajtó}
{157500}{}{Ajtó}
{157600}{}{Ajtó}
{157700}{}{Szellőztető}
{157800}{}{AutoDoki}
{157801}{}{This Auto-Doc is designed to heal illnesses and administer various drugs.}
{157900}{}{Szobor}
{157901}{}{Egy híres menedéklakó szobra.}
{158000}{}{Kőrakás}
{158100}{}{Erőtér}
{158101}{}{Egy erőtér állja az utadat.}
{158200}{}{Erőtér}
{158201}{}{Egy erőtér állja az utadat.}
{158300}{}{Erőtér}
{158301}{}{Egy erőtér állja az utadat.}
{158400}{}{Erőtér}
{158401}{}{Egy erőtér állja az utadat.}
{158500}{}{Tankhajo}
{158600}{}{Tankhajo}
{158700}{}{Tankhajo}
{158800}{}{Tankhajo}
{158900}{}{Tankhajo}
{159000}{}{Tankhajo}
{159100}{}{Tankhajo}
{159200}{}{Tankhajo}
{159300}{}{Tankhajo}
{159400}{}{Tankhajo}
{159500}{}{Tankhajo}
{159600}{}{Tankhajo}
{159700}{}{Tankhajo}
{159800}{}{Tankhajo}
{159900}{}{Tankhajo}
{160000}{}{Fal}
{160100}{}{Fal}
{160200}{}{Benyomódás a padlón}
{160300}{}{Kőpad}
{160400}{}{Kőpad}
{160500}{}{Füstölő}
{160600}{}{Parabola antenna}
{160700}{}{Parabola antenna}
{160800}{}{Árnyék}
{160900}{}{Dokk árnyék}
{161000}{}{Dokk árnyék}
{161100}{}{Dokk árnyék}
{161200}{}{Dokk árnyék}
{161300}{}{Gerenda}
{161400}{}{Gerenda}
{161500}{}{Dokk árnyék}
{161600}{}{Dokk árnyék}
{161700}{}{Dokk árnyék}
{161800}{}{Dokk árnyék}
{161900}{}{Lépcső}
{162000}{}{Kikapcsolt kiberkutya}
{162001}{}{Ez egy hatástalanított kiberkutya.}
{162100}{}{Lerombolt generátor}
{162101}{}{Egy szétvert áramgenerátort látsz.}
{162200}{}{Sín}
{162300}{}{Sín}
{162400}{}{Sín}
{162500}{}{Csille}
{162600}{}{Csille acélrúddal}
{162700}{}{Csille dinamittal}
{162800}{}{Lerobbant csille}
{162900}{}{Csille}
{163000}{}{Biliárdasztal}
{163100}{}{Biliárdasztal}
{163200}{}{Biliárdasztal}
{163300}{}{Biliárdasztal}
{163400}{}{Biliárdasztal}
{163500}{}{Biliárdasztal}
{163600}{}{Asztal}
{163700}{}{Zászló}
{163800}{}{Fal}
{163900}{}{Fal}
{164000}{}{Fal}
{164100}{}{Fal}
{164200}{}{Kiömlő nyílás}
{164300}{}{Asztal}
{164400}{}{Asztal}
{164500}{}{Lépcső lefelé}
{164600}{}{Lépcső felfelé}
{164700}{}{Lépcső felfelé}
{164800}{}{Lépcső felfelé}
{164900}{}{Reactor Core}
{165000}{}{Reactor Core}
{165100}{}{Reactor Core}
{165200}{}{"Karaván iroda"}
{165300}{}{Ravatal}
{165400}{}{Ravatal}
{165500}{}{Bányalift}
{165600}{}{Bányalift}
{165700}{}{Zászlórúd}
{165800}{}{ÚKK zászló}
{165900}{}{"Poseidon üzemanyag"}
{166000}{}{Lépcső lefelé}
{166100}{}{"Klinika"}
{166200}{}{"Nevelő Központ"}
{166300}{}{"Vámhivatal"}
{166400}{}{"Vámhivatal"}
{166500}{}{"Üdvözlő Hivatal"}
{166600}{}{"Boldog Harry"}
{166700}{}{"A lyuk"}
{166800}{}{"Információs Központ"}
{166900}{}{"Információs Központ"}
{167000}{}{"Menedékváros"}
{167100}{}{"Főtanács"}
{167200}{}{"Főtanács"}
{167300}{}{Karbantartó központ}
{167400}{}{"A Szalon"}
{167500}{}{"Csapszék"}
{167600}{}{"Westin marhatelep"}
{167700}{}{"Komfort Osztály"}
{167800}{}{"A Épület"}
{167900}{}{"B Épület"}
{168000}{}{Szolgaközvetítő Központ}
{168100}{}{Szolgaközvetítő Központ}
{168200}{}{"Komfort Hivatal"}
{168300}{}{"Komfort Hivatal"}
{168400}{}{Bányalift}
{168500}{}{Bányalift}
{168600}{}{Bányalift}
{168700}{}{Bányalift}
{168800}{}{Gépmadár}
{168900}{}{Gépmadár}
{169000}{}{Gépmadár}
{169100}{}{Gépmadár}
{169200}{}{Gépmadár}
{169300}{}{Árnyék}
{169400}{}{Árnyék}
{169500}{}{Árnyék}
{169600}{}{Árnyék}
{169700}{}{Strange machine, crashed}
{169800}{}{Strange machine, crashed}
{169900}{}{Strange machine, crashed}
{170000}{}{Strange machine, crashed}
{170100}{}{Strange machine, crashed}
{170200}{}{Strange machine, crashed}
{170300}{}{Árnyék}
{170400}{}{Árnyék}
{170500}{}{Árnyék}
{170600}{}{Lerombolt hid}
{170601}{}{Az Arroyo-híd maradványait látod. Most már nincs visszaút a faluba.}
{170700}{}{Lerombolt hid}
{170701}{}{Az Arroyo-híd maradványait látod. Most már nincs visszaút a faluba.}
{170800}{}{Kanyon}
{170900}{}{Ajtó}
{171000}{}{Ajtó}
{171100}{}{Fal}
{171200}{}{Fal}
{171300}{}{Fal}
{171400}{}{Fal}
{171500}{}{Fal}
{171600}{}{Fal}
{171700}{}{Fal}
{171800}{}{Fal}
{171900}{}{Szellőztető}
{172000}{}{Szellőztető}
{172100}{}{Állítólag golyóálló üveg}
{172101}{}{Állítólag törhetetlen üveg. Meg se próbáld!}
{172200}{}{Állítólag golyóálló üveg}
{172201}{}{Állítólag törhetetlen üveg. Meg se próbáld!}
{172300}{}{Állítólag golyóálló üveg}
{172301}{}{Állítólag törhetetlen üveg. Meg se próbáld!}
{172400}{}{Nehézlézer-löveg}
{172401}{}{The turret rotates in a menacing way.}
{172500}{}{Nehézlézer-löveg}
{172501}{}{The turret rotates in a menacing way.}
{172600}{}{Kövek}
{172700}{}{Kövek}
{172800}{}{Kövek}
{172900}{}{Kövek}
{173000}{}{Kövek}
{173100}{}{Kövek}
{173200}{}{Kövek}
{173300}{}{Kövek}
{173400}{}{Kövek}
{173500}{}{Kövek}
{173600}{}{Kövek}
{173700}{}{"Becky Kaszinója"}
{173800}{}{"Becky Kaszinója"}
{173900}{}{"Utolsó lehelet"}
{174000}{}{"Mama főztje"}
{174100}{}{"Rabszolga-kereskedő"}
{174200}{}{"Túlélő/Cucc"}
{174300}{}{"Tubby kocsmája"}
{174400}{}{"Tubby kocsmája"}
{174500}{}{A bányalift kapuja}
{174600}{}{Ventillátor}
{174700}{}{Ventillátor}
{174800}{}{Az elnök irodájának ajtaja}
{174900}{}{Ábra a szemről}
{175000}{}{Romok}
{175100}{}{A Végtelenség Őrzője}
{175200}{}{"Nem működik"}
{175300}{}{Beomlott padló}
{175400}{}{WC}
{175500}{}{Kereszt}
{175600}{}{Fal}
{175700}{}{Fal}
{175800}{}{Fal}
{175900}{}{Fal}
{176000}{}{Fal}
{176100}{}{Fal}
{176200}{}{Fal}
{176300}{}{Fal}
{176400}{}{Épület}
{176500}{}{Épület}
{176600}{}{Épület}
{176700}{}{Épület}
{176800}{}{Épület}
{176900}{}{Épület}
{177000}{}{Acéltámaszték}
{177100}{}{Acéltámaszték}
{177200}{}{Acéltámaszték}
{177300}{}{Víz}
{177400}{}{Víz}
{177500}{}{Víz}
{177600}{}{Víz}
{177700}{}{Víz}
{177800}{}{Víz}
{177900}{}{Vízesés}
{178000}{}{Út}
{178100}{}{Út}
{178200}{}{Út}
{178300}{}{Út}
{178400}{}{Út}
{178500}{}{Út}
{178600}{}{Út}
{178700}{}{Hídtámaszték}
{178800}{}{Hídtámaszték}
{178900}{}{Hídtámaszték}
{179000}{}{Kerítés}
{179100}{}{Lámpa}
{179200}{}{Lámpa}
{179300}{}{Döglött bálna}
{179301}{}{Úgy látszik, ez a bálna jó magasról eshetett le.}
{179400}{}{Döglött bálna}
{179401}{}{Úgy látszik, ez a bálna jó magasról eshetett le.}
{179500}{}{Bálnauszony}
{179501}{}{A döglött bálna uszonya.}
{179600}{}{Bálnaszem}
{179601}{}{A megboldogult bálna egyik szeme.}
{179700}{}{Bálnadarab}
{179701}{}{A bálna egyik darabja.}
{179800}{}{Bálnadarab}
{179801}{}{A bálna egyik darabja.}
{179900}{}{Bálnadarab}
{179901}{}{A bálna egyik darabja.}
{180000}{}{Bálnadarab}
{180001}{}{A bálna egyik darabja.}
{180100}{}{Bálnadarab}
{180101}{}{A bálna egyik darabja.}
{180200}{}{A Főnök lábai}
{180300}{}{Kövek}
{180400}{}{Kövek}
{180500}{}{Kövek}
{180600}{}{Kövek}
{180700}{}{"Tímár"}
{180800}{}{"Rose Panziója}
{180900}{}{"Vortis Holding"}
{181000}{}{"Vortis Holding"}
{181100}{}{"Nagy Wanamingo bánya"}
{181200}{}{"Ascorti Ásza"}
{181300}{}{Lezuhant űrhajó}
{181301}{}{Valamiféle űrsikló. Úgy látszik, nemrég pottyant ide.}
{181400}{}{Koporsó}
{181500}{}{"Marhatenyésztők Szövetsége"}
{181600}{}{"Mészárszék"}
{181700}{}{Palánk}
{181800}{}{Fa ajtó}
{181900}{}{Fa ajtó}
{182000}{}{Hűtő}
{182100}{}{Hűtő}
{182200}{}{Kályha}
{182300}{}{Kályha}
{182400}{}{Kályha}
{182500}{}{Kályha}
{182600}{}{Cucc}
{182700}{}{Cucc}
{182800}{}{Cucc}
{182900}{}{Cucc}
{183000}{}{Cucc}
{183100}{}{Cucc}
{183200}{}{Cucc}
{183300}{}{Cucc}
{183400}{}{Az elnök széke}
{183500}{}{Lépcső}
{183600}{}{Világtérkép}
{183700}{}{Szituációs térkép}
{183800}{}{Haditanácskozó asztal}
{183900}{}{Tanácskozó asztal}
{184000}{}{Tanácskozó asztal}
{184100}{}{Haditanácskozó asztal}
{184200}{}{Fa}
{184300}{}{Fa}
{184400}{}{Rámpa}
{184500}{}{Golden Globes Filmstúdió}
{184600}{}{Kormánykerék}
{184700}{}{Sebességszabályzó}
{184800}{}{Kommunikációs állomás}
{184900}{}{Számítógépes konzol}
{185000}{}{Zsalu}
{185100}{}{Gőz}
{185200}{}{An old motorcycle}
{185201}{}{An old pre-war motorcycle. It doesn't run anymore.}
{185300}{}{A water tank}
{185301}{}{A metal tower which holds drinkable water.}
{185400}{}{Mom's Orphanage Sign}
{185500}{}{Ventillátor}
{185600}{}{A healthy looking tree}
{185700}{}{A healthy looking tree}
{185800}{}{A healthy looking tree}
{185900}{}{A healthy looking tree}
{186000}{}{A healthy looking tree}
{186100}{}{A healthy looking shrub}
{186200}{}{Növény}
{186201}{}{A mutated cornstalk. It seems to be thriving under these conditions. This one is a different color than the others you have seen.}
{186300}{}{Fertile ground}
{186400}{}{Fertile ground}
{186500}{}{Fertile ground}
{186600}{}{USED ART}
{186601}{}{}
{186700}{}{USED ART}
{186701}{}{A throne for a leader or commander.}
{186800}{}{Air vent}
{186801}{}{A circular air vent to an underground facility.}
{186900}{}{Kötél}
{186901}{}{A rope leading to an overhead air vent.}
{187000}{}{Air Processing Vent}
{187001}{}{A vent used to filter air underground.}
{187100}{}{Szellőző}
{187101}{}{A vent used to purify air.}
{187200}{}{Brahmin sign}
{187201}{}{A sign giving instructions.}
{187300}{}{Brahmin sign}
{187301}{}{A sign giving a warning.}
{187400}{}{Crafting Machine}
{187401}{}{A machine with which you can make your own drugs.}
{187500}{}{Chemicals}
{187501}{}{Foul smelling gelatinous chemicals.}
{187600}{}{Chemicals}
{187601}{}{Foul smelling gelatinous chemicals.}
{187700}{}{Chemicals	}
{187701}{}{Foul smelling gelatinous chemicals.}
{187800}{}{Chemicals	}
{187801}{}{Foul smelling gelatinous chemicals.}
{187900}{}{Kötél}
{187901}{}{Rope to signify a non-walking area.}
{188000}{}{Kötél}
{188001}{}{Rope preventing access to certain areas.}
{188100}{}{Gallery Picture}
{188101}{}{A picture depicting The Mona Lisa.}
{188200}{}{Gallery Picture}
{188201}{}{A picture depicting the first moon walk.}
{188300}{}{Crafting Machine}
{188301}{}{A machine with which you can make your own drugs.}
{188400}{}{Fertile ground}
{188401}{}{Ground ready for planting.}
{188500}{}{Fertile ground}
{188501}{}{Ground ready for planting.}
{188600}{}{Parking sign}
{188601}{}{A sign designating areas to park.}
{188700}{}{Lift}
{188701}{}{An elevator to travel to another floor.}
{188800}{}{Hibernation computer}
{188801}{}{Computer controlling the hibernation vats.}
{188900}{}{A group of barrels}
{188901}{}{Barrels storing various chemicals.}
{189000}{}{A burning barrel}
{189001}{}{Apparently the sign says its flammable.}
{189100}{}{A barrel}
{189101}{}{A barrel filled with some sort of liquid.}
{189200}{}{A barrel}
{189201}{}{A barrel containing a thick noxious red liquid.}
{189300}{}{A barrel}
{189301}{}{A barrel with a biohazard warning label.}
{189400}{}{Növény}
{189401}{}{This plant appears to have some type of berry hanging from it.}
{189500}{}{A Tree}
{189600}{}{A toaster}
{189601}{}{A silver toaster sitting on a desk.}
{189700}{}{A hologram projector}
{189701}{}{Your basic HD 2000 hologram projector.}
{189800}{}{A hologram projector}
{189801}{}{Your basic HD 2000 hologram projector.}
{189900}{}{A hologram projector}
{189901}{}{Your basic HD 2000 hologram projector.}
{190000}{}{Árnyék}
{190001}{}{}
{190100}{}{Gépmadár}
{190200}{}{A Cryogenic Freezer}
{190201}{}{A freezer which can store a live human being. This one is open.}
{190300}{}{A Cryogenic Freezer}
{190301}{}{A freezer which can store a live human being. This one is closed.}
{190400}{}{A desk}
{190401}{}{A large, sturdy looking desk.}
{190500}{}{Hibernation Chamber}
{190501}{}{A hibernation chamber. A body of a white female is suspended inside.}
{190600}{}{Hibernation Chamber}
{190601}{}{A hibernation chamber. A body of a white male is suspended inside.}
{190700}{}{Hibernation Chamber}
{190701}{}{An open hibernation chamber. A body of a white female lies naked inside.}
{190800}{}{Hibernation Chamber}
{190801}{}{An open hibernation chamber. A body of a white male lies naked inside.}
{190900}{}{Hibernation Chamber}
{190901}{}{An open hibernation chamber. A body of a black male lies naked inside.}
{191000}{}{Hibernation Chamber}
{191001}{}{A hibernation chamber. A body of a black male is suspended inside.}
{191100}{}{Hibernation Chamber}
{191101}{}{An open hibernation chamber. It is empty.}
{191200}{}{A WattzMan 2000 electric chair}
{191300}{}{Imperial Shuttle}
{191301}{}{A space vehicle of some kind. It has a license plate that reads: EMPRRULZ!}
{191400}{}{Imperial Shuttle}
{191401}{}{A space vehicle of some kind. It has a license plate that reads: EMPRRULZ!}
{191500}{}{Millennium Falcon}
{191501}{}{It looks like a bucket of bolts. You spot a pair of fuzzy dice hanging from the rear-view mirror.}
{191600}{}{Burning brazier}
{191601}{}{This brazier is full of burning coals.}
{191700}{}{Bone}
{191701}{}{}
{191800}{}{Bone}
{191900}{}{Bone}
{192000}{}{Csontok}
{192001}{}{Scattered remains.}
{192100}{}{Csontok}
{192101}{}{Are these human!}
{192200}{}{Csontok}
{192201}{}{Scattered human bones.}
{192300}{}{Csontok}
{192400}{}{Csontok}
{192500}{}{Csontok}
{192501}{}{Scattered human bones.}
{192600}{}{Csontok}
{192601}{}{Scattered human remains.}
{192700}{}{Csontok}
{192701}{}{Are these human!}
{192800}{}{Csontok}
{192900}{}{Concrete barrier}
{193000}{}{Concrete barrier}
{193100}{}{Biztonsági ajtó}
{193101}{}{This door looks very secure.}
{193200}{}{Biztonsági ajtó}
{193201}{}{This rusty door still looks very secure.}
{193300}{}{Liftakna}
{193400}{}{Liftakna}
{193401}{}{The shaft is broken.}
{193500}{}{Liftakna}
{193501}{}{Egy kötél lóg lefelé az akna széléről.}
{193600}{}{Liftakna}
{193601}{}{The shaft has a broken elevator and rope.}
{193700}{}{Liftakna}
{193701}{}{The shaft is missing the elevator. Dangerous!}
{193800}{}{Rusting Pipes}
{193801}{}{A set of old rusting pipes.}
{193900}{}{Generátor}
{193901}{}{Egy Kandó Elek-Trobox típusú generátor. A háború utáni elterjedt tartalékgenerátor-fajta.}
{194000}{}{Generátor}
{194001}{}{A Wattz ElectroBox fuse box. Fairly standard as back-up generators before the war.}
{194100}{}{Electrical Machinery}
{194101}{}{This machine is buzzing with electricity.}
{194200}{}{Small Monitor}
{194201}{}{This small monitor appears to have someone talking.}
{194300}{}{Monitor}
{194301}{}{A large monitor, black and white only. This one has a woman lecturing on morals.}
{194400}{}{Monitor}
{194401}{}{A large monitor, black and white only. This one warns of fallout.}
{194500}{}{Monitor}
{194501}{}{A large monitor, black and white only. The strange film appears to be stuck in a loop.}
{194600}{}{Large Monitor}
{194601}{}{A large monitor, black and white only. This one has a figure in armor.}
{194700}{}{Monitor}
{194701}{}{A large monitor, black and white only. This one has a dignified, but simple looking man rambling on.}
{194800}{}{Monitor}
{194801}{}{A large monitor, black and white only. The picture is of a rotating cross and circle.}
{194900}{}{spare}
{195000}{}{spare}
{195100}{}{Árnyék}
{195200}{}{Árnyék}
{195300}{}{Large Sticky Mechanical Pump}
{195301}{}{You see a large mechanical pump covered in strange noxious biological goo.}
{195400}{}{Floor Grating}
{195401}{}{A rusting floor grating.}
{195500}{}{Large Mechanical Pump}
{195501}{}{A large mechanical pump rising up through a floor grating.}
{195600}{}{Large Sticky Mechanical Pump}
{195601}{}{You see a large mechanical pump covered in strange noxious biological goo.}
{195700}{}{Destroyed Sticky Mechanical Pump}
{195701}{}{You see a large mechanical pump covered in strange noxious biological goo. Its pumping days are over.}
{195800}{}{Destroyed Sticky Mechanical Pump}
{195801}{}{You see a large mechanical pump covered in strange noxious biological goo. Its pumping days are over.}
{195900}{}{Floor Cavity}
{196000}{}{Large Mechanical Pump}
{196001}{}{A large mechanical pump rising up through a floor grating.}
{196100}{}{Large Mechanical Pump}
{196101}{}{A large mechanical pump rising up through a floor grating.}
{196200}{}{Abroncsok}
{196201}{}{Egy rakás poros gumiabroncs. Vulkanizált és keményített fajta. Valószínűleg a hő által.}
{196300}{}{Rubber Tires}
{196301}{}{Two ancient rubber tires. They have vulcanized and hardened, probably due to the heat.}
{196400}{}{Rubber Tire}
{196401}{}{An ancient rubber tire. It has become vulcanized and hardened, probably due to the heat.}
{196500}{}{Large Turbine}
{196501}{}{A large spinning turbine.}
{196600}{}{Szellőző}
{196601}{}{Egy ventillátor, ami tisztítja és frissíti a bázis levegőjét.}
{196700}{}{Szellőző}
{196701}{}{Egy ventillátor, ami tisztítja és frissíti a bázis levegőjét.}
{196800}{}{Szellőztető}
{196900}{}{Szellőztető}
{197000}{}{Rusty Air Vent}
{197001}{}{This air vent is rusty and blocked.}
{197100}{}{Rusty Air Vent}
{197101}{}{This air vent is rusty and blocked.}
{197200}{}{Rusty Air Vent}
{197201}{}{This rusty air vent is blocked.}
{197300}{}{Fal}
{197400}{}{Fal}
{197500}{}{Fa borítás}
{197600}{}{Szellőző}
{197700}{}{Szellőző}
{197800}{}{Kut}
{197801}{}{Egy tipikus kút, amit az ember a semmi közepén találhat.}
{197900}{}{Lépcső}
{197901}{}{A set of broad stairs.}
{198000}{}{Broad Rusting Stairs}
{198001}{}{These stairs are rusting slowly away.}
{198100}{}{Broad Rusting Stairs}
{198101}{}{These stairs are rusting slowly away.}
{198200}{}{Small Stairs}
{198201}{}{Typical small stairs.}
{198300}{}{Small Rusting Stairs}
{198301}{}{These stairs are rusting away.}
{198400}{}{Jammed Fan}
{198401}{}{This fan has a piece of metal jamming the blades.}
{198500}{}{Air Processing Vent}
{198501}{}{Szabványos Menedék-Tek szellőzőrendszer.}
{198600}{}{Acélfal}
{198700}{}{Acélfal}
{198800}{}{Acélfal}
{198900}{}{Acélfal}
{199000}{}{Acélfal}
{199100}{}{Rusting Pipes}
{199200}{}{Csövek}
{199300}{}{Raktárház ajtaja}
{199400}{}{Raktárház ajtaja}
{199500}{}{Giant Copper Statue}
{199501}{}{This statue rises from out of the earth. It has the slight smell of Ape piss.}
{199600}{}{Giant Copper Statue}
{199601}{}{This statue rises from out of the earth. It has the slight smell of Ape piss.}
{199700}{}{Giant Copper Statue}
{199701}{}{This statue rises from out of the earth. It has the slight smell of Ape piss.}
{199800}{}{Giant Copper Statue}
{199801}{}{This statue rises from out of the earth. It has the slight smell of Ape piss.}
{199900}{}{Giant Copper Statue}
{199901}{}{This statue rises from out of the earth. It has the slight smell of Ape piss.}
{200000}{}{Árnyék}
{200001}{}{Árnyék}
{200100}{}{Árnyék}
{200200}{}{Függőtartály}
{200201}{}{Some sort of medical or experimental apparatus. This tank holds a strange green liquid.}
{200300}{}{Víztartály}
{200301}{}{Ebben az óriási tartályban folyadékot tárolnak. Esetünkben, (feltételezéseid szerint) ez eredetileg víztartály lenne.}
{200400}{}{Ajtó}
{200500}{}{EPA Globe}
{200501}{}{A rusting corporate logo.}
{200600}{}{Árnyék}
{200700}{}{Haditanácskozó asztal}
{200800}{}{Haditanácskozó asztal}
{200900}{}{Biztonsági ajtó}
{200901}{}{This door looks very secure.}
{201000}{}{EPA Sign}
{201100}{}{EPA Sign}
{201200}{}{EPA Plaque}
{201201}{}{A metal plaque with the letters EPA.}
{201300}{}{EPA Plaque}
{201301}{}{A metal plaque with the letters EPA.}
{201400}{}{Rusting EPA Plaque}
{201401}{}{This metal plaque is slowly rusting away.}
{201500}{}{Metal Plaque}
{201501}{}{A metal plaque with the number one.}
{201600}{}{Metal Plaque}
{201601}{}{A metal plaque with the number two.}
{201700}{}{Metal Plaque}
{201701}{}{A metal plaque with the number three.}
{201800}{}{Metal Plaque}
{201801}{}{A metal plaque with the number four.}
{201900}{}{Metal Plaque}
{201901}{}{A metal plaque with the number five.}
{202000}{}{Metal Plaque}
{202001}{}{A metal plaque with the number six.}
{202100}{}{Museum Picture}
{202200}{}{Museum Picture}
{202300}{}{Musuem Picture}
{202400}{}{EPA Globe}
{202401}{}{The EPA corporation logo.}
{202500}{}{Árnyék}
{202600}{}{Árnyék}
{202700}{}{Árnyék}
{202800}{}{Girlie Poster}
{202900}{}{Girlie Poster}
{203000}{}{Girlie Poster}
{203100}{}{Girlie Poster}
{203200}{}{Girlie Poster}
{203300}{}{Girlie Poster}
{203400}{}{Girlie Poster}
{203500}{}{Girlie Poster}
{203600}{}{Girlie Poster}
{203700}{}{Girlie Poster}
{203800}{}{Girlie Poster}
{203900}{}{Girlie Poster}
{204000}{}{Girlie Poster}
{204100}{}{Girlie Poster}
{204200}{}{Girlie Poster}
{204300}{}{Girlie Poster}
{204400}{}{Girlie Poster}
{204500}{}{Girlie Poster}
{204600}{}{}
{204601}{}{}
{204700}{}{Szőnyeg}
{204701}{}{An old woven floor rug.}
{204800}{}{Szőnyeg}
{204801}{}{An old woven floor rug.}
{204900}{}{Cserépedény}
{204901}{}{Nagyon ügyes volt, aki csinálta.}
{205000}{}{Cserépedény}
{205001}{}{Nagyon ügyes volt, aki csinálta.}
{205100}{}{Cserépedény}
{205101}{}{Nagyon ügyes volt, aki csinálta.}
{205200}{}{Cserépedény}
{205201}{}{Nagyon ügyes volt, aki csinálta.}
{205300}{}{Szellőztető}
{205400}{}{Szellőztető}
{205500}{}{Vault Outer Door}
{205501}{}{Ezen az ajtón keresztül lehet kijutni a menedékből a külvilágba.}
{205600}{}{Rusting Vault Outer Door}
{205601}{}{This large rusting door is the link between the vault and the outside world.}
{205700}{}{Rusting Vault Outer Door}
{205701}{}{This large rusting door is the link between the vault and the outside world.}
{205800}{}{Rusting Vault Outer Door}
{205801}{}{A nagy Menedék-ajtó irányító mechanizmusa megsérült a javítás során.}
{205900}{}{Rusting Vault Outer Door}
{205901}{}{The door mechanism has been disabled.}
{206000}{}{Vault Outer Door}
{206001}{}{Ezen az ajtón keresztül lehet kijutni a menedékből a külvilágba.}
{206100}{}{Cserépedény}
{206101}{}{Nagyon ügyes volt, aki csinálta.}
{206200}{}{Cserépedény}
{206201}{}{Nagyon ügyes volt, aki csinálta.}
{206300}{}{Cserépedény}
{206301}{}{Nagyon ügyes volt, aki csinálta.}
{206400}{}{Cserépedény}
{206401}{}{Nagyon ügyes volt, aki csinálta.}
{206500}{}{Fal}
{206600}{}{Erőtér}
{206700}{}{Metal Plaque}
{206701}{}{A metal plaque with the number 7.}
{206800}{}{Kövek}
{206801}{}{Baromi sok kő.}
{206900}{}{Kövek}
{206901}{}{Baromi sok kő.}
{207000}{}{Rusting Elevator}
{207001}{}{This rusting elevator travels between levels.}
{207100}{}{Dirty Bilge Water}
{207200}{}{Iron Vat}
{207201}{}{A huge iron vat with a strange green liquid.}
{207300}{}{Biztonsági ajtó}
{207301}{}{This door looks very secure.}
{207400}{}{Worn Rug}
{207401}{}{An old woven floor rug.}
{207500}{}{Worn Rug}
{207501}{}{An old woven floor rug.}
{207600}{}{NCR Picture}
{207601}{}{A picture of the NCR banner.}
{207700}{}{NCR Picture}
{207701}{}{A picture of the NCR banner.}
{207800}{}{NCR Picture}
{207801}{}{A picture of the NCR banner.}
{207900}{}{Hegy}
{207901}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{208000}{}{Hegy}
{208001}{}{Azok a távoli hegyoldalak elérhetetlennek látszanak.}
{208100}{}{Picture}
{208200}{}{Picture}
{208300}{}{Picture}
{208400}{}{Szellőző}
{208500}{}{Szellőző}
{208600}{}{Szellőző}
{208700}{}{Szellőző}
{208800}{}{Szellőző}
{208900}{}{Szellőző}
{209000}{}{Fa borítás}
{209100}{}{Fa borítás}
{209200}{}{Szellőző}
{209300}{}{Szellőző}
{209400}{}{Wall Pipes}
{209500}{}{Wall Pipes}
{209600}{}{Wall Pipes}
{209700}{}{Wall Pipes}
{209800}{}{Wall Pipes}
{209900}{}{Wall Pipes}
{210000}{}{Biztonsági ajtó}
{210001}{}{This metal door is embedded in the rock face.}
{210100}{}{Vault Outer Door}
{210101}{}{This vault door is embedded in the rock face of the mountain. It appears to have survived the blast of an atomic bomb.}
{210200}{}{Vault Outer Door}
{210201}{}{This large door is the link between the vault and the outside world. It has been scorched by a tremendous blast.}
{210300}{}{Barlang bejarat}
{210301}{}{The cave appears to open up into a larger network of caves.}
{210400}{}{Bejárati terminál}
{210401}{}{Ez a gép irányítja a menedék böszme nagy ajtaját. Ha működésre akarod bírni, meg kell adnod a helyes kódot.}
{210500}{}{Rusting Boat}
{210501}{}{This boat looks barely seaworthy.}
{210600}{}{Rusting Boat}
{210601}{}{This boat looks barely seaworthy.}
{210700}{}{Mooring Post}
{210701}{}{A rope leads from the mooring post to the boat.}
{210800}{}{Mooring Post}
{210801}{}{A rope leads from the mooring post to the boat.}
{210900}{}{Rusting Submarine Hatch}
{210901}{}{With a bit of effort this hatch can still be opened.}
{211000}{}{Rusting Submarine Tower}
{211001}{}{The ravages of time and salt water are slowly consuming this rusting hulk.}
{211100}{}{Rusting Submarine Tower}
{211101}{}{The ravages of time and salt water are slowly consuming this rusting hulk.}
{211200}{}{Rusting Ladder}
{211201}{}{The salt water is gradually dissolving the metal ladder.}
{211300}{}{Rusting Submarine Tower}
{211301}{}{The ravages of time and salt water are slowly consuming this rusting hulk.}
{211400}{}{Rusting Boat}
{211401}{}{This boat looks barely seaworthy.}
{211500}{}{Murky Ocean}
{211600}{}{Rusting Hull}
{211601}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{211700}{}{Rusting Hull}
{211701}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{211800}{}{Rusting Hull}
{211801}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{211900}{}{Murky Ocean}
{212000}{}{Rusting Hull}
{212001}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{212100}{}{Rusting Hull}
{212101}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{212200}{}{Murky Ocean}
{212300}{}{Murky Ocean}
{212400}{}{Murky Ocean}
{212500}{}{Murky Ocean}
{212600}{}{Murky Ocean}
{212700}{}{Rusting Hull}
{212701}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{212800}{}{Rusting Hull}
{212801}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{212900}{}{Rusting Boat}
{212901}{}{This boat looks barely seaworthy.}
{213000}{}{Murky Ocean}
{213100}{}{Rusting Hull}
{213101}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{213200}{}{Rusting Hull}
{213201}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{213300}{}{Murky Ocean}
{213400}{}{Murky Ocean}
{213500}{}{Murky Ocean}
{213600}{}{Rusting Hull}
{213601}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{213700}{}{Rusting Hull}
{213701}{}{The hull of the submarine lies submerged beneath the murky ocean.}
{213800}{}{Murky Ocean}
{213900}{}{Murky Ocean}
{214000}{}{Murky Ocean}
{214100}{}{Rusting Hull}
{214200}{}{Torpedo Launcher}
{214201}{}{These metal tubes are made up of a considerable number of interlocks. It looks like they're still in working condition.}
{214300}{}{Rusting Hull}
{214301}{}{Rusting Hull}
{214400}{}{Rusting Hull}
{214500}{}{Rusting Hull}
{214600}{}{Rusting Hull}
{214700}{}{Torpedoes}
{214701}{}{Torpedoes}
{214800}{}{Torpedoes}
{214801}{}{Torpedoes}
{214900}{}{Torpedoes}
{214901}{}{Torpedoes}
{215000}{}{Rusting Hull}
{215100}{}{Rusting Hull}
{215200}{}{Rusting Hull}
{215300}{}{Rusty Machinery}
{215400}{}{Rusty Machinery}
{215500}{}{Torpedoes}
{215501}{}{Torpedoes}
{215600}{}{Torpedoes}
{215601}{}{Torpedoes}
{215700}{}{Rusty Machinery}
{215800}{}{Rusting Hull}
{215900}{}{Rusty Machinery}
{216000}{}{Rusting Hull}
{216100}{}{Rusty Machinery}
{216200}{}{Rusty Machinery}
{216300}{}{Rusty Machinery}
{216400}{}{Rusty Machinery}
{216500}{}{Rusting Hull}
{216600}{}{Rusting Hull}
{216700}{}{Rusting Hull}
{216800}{}{Rusting Hull}
{216900}{}{Rusting Hull}
{217000}{}{Rusting Hull}
{217100}{}{Rusting Hull}
{217200}{}{Rusting Hull}
{217300}{}{Submarine Hatch}
{217400}{}{Szék}
{217500}{}{Szék}
{217600}{}{Poseidon Oil Sign}
{217601}{}{This old neon sign still has some life left in it.}
{217700}{}{Massive Steel Vault Doors}
{217701}{}{These steel doors are practically indestructible.}
{218800}{}{Sub Tower}
{218900}{}{Sub Tower}
{219000}{}{Lépcső}
{219001}{}{A set of wooden stairs.}
{219100}{}{Lépcső}
{219101}{}{A set of wooden stairs.}
{219200}{}{Lépcső}
{219201}{}{A set of wooden stairs.}
{219300}{}{Létra}
{219400}{}{Rusting Submarine Hatch}
{219500}{}{Rusting Submarine Hatch}
{219501}{}{With a bit of effort this hatch can still be opened.}
{219600}{}{AutoDoki}
{219700}{}{}
{219800}{}{"Körözvény"}
{219801}{}{A sketched portrait of a fugitive wanted by the local authorities.}
{219900}{}{Ventillátor}
{220000}{}{Jammed Fan}
{220100}{}{Rusty Steel Rail}
{220200}{}{Tábla}
{220201}{}{"Szatócsbolt".}
{220300}{}{Worn Rug}
{220301}{}{Egy normál szőnyeg. Valószínűleg tehetséges kezek terméke.}
{220400}{}{Glowing Bones}
{220401}{}{A large pile of glowing animal bones. At least, you think all the bones are animal...}
{220500}{}{Glowing Bones}
{220501}{}{A large pile of glowing animal bones. At least, you think all the bones are animal...}
{220600}{}{Glowing Bones}
{220601}{}{A very large pile of glowing bones. You cannot determine the species of the dead critters.}
{220700}{}{Glowing Bones}
{220701}{}{You think these might be Horned Kangaroo bones, but you cannot be sure. They are glowing and too weathered to make a final determination.}
{220800}{}{Glowing Bones}
{220801}{}{You see the bones of a large, glowing two-headed cow.}
{220900}{}{Barlangnyílás}
{220901}{}{A large amount of glowing rocks, far more than could ever be moved easily.}
{221000}{}{Glowing Metal Cover}
{221001}{}{A heavy glowing man-hole cover. It looks like it is in good shape, and that it was recently moved.}
{221100}{}{Glowing Sewer Hole}
{221101}{}{It looks like an access hole for the sewer system. It's glowing green!}
{221200}{}{Glowing Stalagmite}
{221201}{}{A natural extension of the rock floor. This one's glowing green!}
{221300}{}{Glowing Stalagmite}
{221301}{}{A natural extension of the rock floor. This one's glowing green!}
{221400}{}{Glowing Rock Column}
{221401}{}{This thick column of rock extends from floor to ceiling. It's glowing!}
{221500}{}{Glowing Rock Column}
{221501}{}{This thin column of rock extends from floor to ceiling. It's glowing!}
{221600}{}{Glowing Cave Wall}
{221700}{}{Glowing Cave Wall}
{221800}{}{Glowing Cave Wall}
{221900}{}{Glowing Cave Wall}
{222000}{}{Glowing Cave Wall}
{222100}{}{Glowing Cave Wall}
{222200}{}{Glowing Cave Wall}
{222300}{}{Glowing Cave Wall}
{222400}{}{Glowing Cave Wall}
{222500}{}{Glowing Cave Wall}
{222600}{}{Glowing Cave Wall}
{222700}{}{Glowing Cave Wall}
{222800}{}{Glowing Cave Wall}
{222900}{}{Glowing Cave Wall}
{223000}{}{Glowing Cave Wall}
{223100}{}{Glowing Rocks}
{223101}{}{A pile of glowing rocks. Not very interesting.}
{223200}{}{Glowing Rocks}
{223201}{}{A pile of glowing rocks. Not very interesting.}
{223300}{}{Glowing Rocks}
{223301}{}{A small pile of glowing rocks. Not in the least bit interesting to you.}
{223400}{}{Glowing Rocks}
{223401}{}{A very small pile of glowing rocks.}
{223500}{}{Glowing Rocks}
{223501}{}{A very small pile of glowing rocks.}
{223600}{}{Glowing Rocks}
{223601}{}{A very small pile of glowing rocks.}
{223700}{}{Glowing Rocks}
{223701}{}{A very small pile of glowing rocks.}
{223800}{}{Glowing Rocks}
{223801}{}{A pile of glowing rocks. Not very interesting.}
{223900}{}{Glowing Egg Shell}
{223901}{}{Pieces of a broken egg shell. It glows!}
{224000}{}{Glowing Egg Shell}
{224001}{}{Pieces of a broken egg shell. It glows!}
{224100}{}{Glowing Egg Shell}
{224101}{}{Pieces of a broken egg shell. It glows!}
{224200}{}{Glowing Egg Shell}
{224201}{}{Pieces of a broken egg shell. It glows!}
{224300}{}{Small glowing rocks}
{224301}{}{Scattered small glowing rocks.}
{224400}{}{Small glowing rocks}
{224401}{}{Scattered small glowing rocks.}
{224500}{}{Small glowing rocks}
{224501}{}{Scattered small glowing rocks.}
{224600}{}{Glowing Egg Shell}
{224601}{}{Pieces of a broken egg shell. It glows!}
{224700}{}{Glowing Wood Planks}
{224701}{}{Ezek a kemény palánkok jól össze vannak erősítve.}
{224800}{}{Glowing Wood Planks}
{224801}{}{Ezek a kemény palánkok jól össze vannak erősítve.}
{224900}{}{Létra}
{224901}{}{It's an old, glowing, fairly rickety ladder. It looks like it will barely support your weight.}
{225000}{}{Létra lefelé}
{225001}{}{Ez egy emberméretű nyílás, amiben egy létra vezet lefelé.}
{225100}{}{Glowing Rocks}
{225101}{}{You study the glowing rocks for a while, but they never move.}
{225200}{}{Glowing Rocks}
{225201}{}{You keep a close eye on these glowing rocks, in case they move to attack you.}
{225300}{}{Glowing Rocks}
{225301}{}{A large pile of glowing rocks. They look radioactive.}
{225400}{}{Glowing Rocks}
{225401}{}{A small pile of glowing rocks.}
{225500}{}{Glowing Rocks}
{225501}{}{A small pile of glowing rocks.}
{225600}{}{Glowing Rocks}
{225601}{}{A large pile of glowing rocks.}
{225700}{}{Glowing Rocks}
{225701}{}{A very large pile of glowing rocks. They look dangerous just sitting there.}
{225800}{}{Glowing Rocks}
{225801}{}{A large pile of glowing rocks. If you look closely, you can see the faces of little old men in the sides of the stones.}
{225900}{}{Glowing Rocks}
{225901}{}{Rocks, rocks, rocks! Everywhere you look, glowing rocks!}
{226000}{}{Glowing Rocks}
{226001}{}{A small pile of glowing rocks.}
{226100}{}{Glowing Rocks}
{226200}{}{Glowing Rocks}
{226300}{}{Glowing Rocks}
{226400}{}{Glowing Rocks}
{226500}{}{Glowing Rocks}
{226600}{}{Glowing Rocks}
{226700}{}{Glowing Rocks}
{226800}{}{Glowing Wall}
{226900}{}{Glowing Wall}
{227000}{}{Glowing Wall}
{227100}{}{Glowing Wall}
{227200}{}{Glowing Wall}
{227300}{}{Glowing Wall}
{227400}{}{Glowing Drain}
{227401}{}{Undorító bűz áramlik a csatornalefolyóból. Pár pillanat múlva már nem is tűnik annyira rossznak a szag.}
{227500}{}{Glowing Drain}
{227501}{}{You can barely make out some movement behind the grate covering this drain. You can see small green glowing eyes peering back at you. Rat eyes.}
{227600}{}{Glowing Drain}
{227601}{}{A lefolyóból csobogó víz hangja hallatszik, a szag pedig undorító.}
{227700}{}{Glowing Drain}
{227701}{}{Hallod a víz bugyogását a lefolyóban. Jó kis bukéja van!}
{227800}{}{Grimy Bed}
{227801}{}{Közelebbről megvizsgálva, úgy veszed észre, hogy az ágyneműt már nagyon-nagyon régen nem húzták újra.}
{227900}{}{Grimy Bed}
{227901}{}{Közelebbről megvizsgálva, úgy veszed észre, hogy az ágyneműt már nagyon-nagyon régen nem húzták újra.}
{228000}{}{Grimy Bed}
{228001}{}{Közelebbről megvizsgálva, úgy veszed észre, hogy az ágyneműt már nagyon-nagyon régen nem húzták újra.}
{228100}{}{Üveg}
{228101}{}{This glass is difficult to see through.}
{228200}{}{Üveg}
{228201}{}{This glass is difficult to see through.}
{228300}{}{Üveg}
{228301}{}{This glass is difficult to see through.}
{228400}{}{Üveg}
{228401}{}{This glass is barely transparent.}
{228500}{}{Üveg}
{228501}{}{This glass is barely transparent.}
{228600}{}{Üveg}
{228601}{}{This glass is barely transparent.}
{228700}{}{Fémajtó}
{228701}{}{A sturdy metal door.}
{228800}{}{Fémajtó}
{228801}{}{A sturdy metal door.}
{228900}{}{Guards Shack}
{228901}{}{A run down guards shack.}
{229000}{}{Guards Shack}
{229001}{}{A run down guards shack.}
{229100}{}{Green Bubbling Liquid}
{229101}{}{Green bubbling liquid. It smells strange.}
{229200}{}{Heavy Laser Tower}
{229201}{}{The laser turret rests on this concrete tower.}
{229300}{}{Nehézlézer-löveg}
{229301}{}{The turret rotates in a menacing way.}
{229400}{}{Heavy Laser Tower}
{229401}{}{The laser turret rests on this concrete tower.}
{229500}{}{Nehézlézer-löveg}
{229501}{}{The turret rotates in a menacing way.}
{229800}{}{Film Poster}
{229801}{}{An old tatered film poster. "Hobo With a Shotgun".}
{229900}{}{An odd looking creature}
{229901}{}{A dead body with plant growth wrapped around it.}
{230000}{}{An odd looking creature}
{230001}{}{A dead body with plant growth wrapped around it.}
{230100}{}{Füst}
{230200}{}{Füst}
{230300}{}{Flaming Brazier}
{230301}{}{This putrid oil brazier is an effective light source. The fumes can't help but burn your eyes and nostrils.}
{230400}{}{Tires}
{230401}{}{Old rubber tires sitting in the middle of some weeds.}
{230500}{}{Abroncsok}
{230501}{}{Egy rakás poros gumiabroncs. Vulkanizált és keményített fajta. Valószínűleg a hő által.}
{230600}{}{Abroncsok}
{230601}{}{Egy rakás poros gumiabroncs. Vulkanizált és keményített fajta. Valószínűleg a hő által.}
{230700}{}{Shattered Glass}
{230701}{}{Scattered shards of broken glass.}
{230800}{}{Rusting Vehicle}
{230801}{}{The sands are slowly swallowing this lost vehicle.}
{230900}{}{Autó}
{230901}{}{Ez az automobil rettentően néz ki. Gondolni se merj arra, hogy egyszer majd üzemképes lesz!}
{231000}{}{Autó}
{231001}{}{Ezt a rozsdás fémdarabot már nem lehet helyrerakni.}
{231100}{}{Autó}
{231101}{}{Minden jel arra utal, hogy ez a jármű már többet nem fog közlekedni. De tényleg.}
{231200}{}{Autó}
{231201}{}{Semmi esély arra, hogy ezt a szemétnek is alig nevezhető valamit valaki, valaha is vezetni fogja.}
{231300}{}{Asztal}
{231301}{}{Fából készült asztal.}
{231400}{}{Komód}
{231401}{}{Fából készült komód.}
{231500}{}{Komód}
{231501}{}{Fából készült komód.}
{231600}{}{Asztal}
{231601}{}{Egy közönséges asztal. Ha láttál egyet, láttad mindet.}
{231700}{}{Asztal}
{231701}{}{Egy közönséges asztal.}
{231800}{}{Asztal}
{231801}{}{Egy közönséges asztal.}
{231900}{}{Books}
{231901}{}{An assortment of books.}
{232000}{}{Boxes and Sacks}
{232001}{}{An assortment of boxes and sacks.}
{232100}{}{Metal Parts}
{232101}{}{An assortment of metal parts.}
{232200}{}{Books}
{232201}{}{An assortment of books.}
{232300}{}{Boxes and Sacks}
{232301}{}{An assortment of boxes and sacks.}
{232400}{}{Metal Parts}
{232401}{}{An assortment of metal parts.}
{232500}{}{Hordó}
{232501}{}{A barrel of smelly meaty bits.}
{232600}{}{Hordó}
{232601}{}{A barrel of smelly meaty bits.}
{232700}{}{Hordó}
{232701}{}{A barrel of smelly meaty bits.}
{232800}{}{Hordó}
{232801}{}{A barrel of smelly meaty bits.}
{232900}{}{Flies}
{233000}{}{Flies}
{233100}{}{Szellőző}
{233200}{}{Szellőző}
{233300}{}{Szellőző}
{233400}{}{Szellőző}
