{100}{}{Kézi lõfegyverek}
{101}{}{Nehéz lõfegyverek}
{102}{}{Energiafegyverek}
{103}{}{Pusztakezes.}
{104}{}{Közelharc}
{105}{}{Hajítás}
{106}{}{Elsõsegély}
{107}{}{Orvos}
{108}{}{Lopózás}
{109}{}{Zárak}
{110}{}{Lopás}
{111}{}{Csapdák}
{112}{}{Tudományok}
{113}{}{Javítás}
{114}{}{Beszéd}
{115}{}{Üzletelés}
{116}{}{Szerencsejáték}
{117}{}{Túlélés}
{200}{}{Kézi lõfegyverek használata, karbantartása és általános ismerete - pisztolyok, géppisztolyok és puskák.}
{201}{}{Nehéz lõfegyverek használata és karbantartása - gépágyúk, rakétavetõk, lángszórók, stb.}
{202}{}{The care and feeding of energy-based weapons. How to arm and operate weapons that use laser or plasma technology.}
{203}{}{A combination of martial arts, boxing and other hand-to-hand martial arts. Combat with your hands and feet.}
{204}{}{A nem távolsági fegyverek használata - kések, kalapácsok, lándzsák, bunkók, stb.}
{205}{}{Hajítófegyverek használatának képzettsége - dobókések, lándzsák és gránátok.}
{206}{}{General healing skill. Used to heal small cuts, abrasions and other minor ills. In game terms, the use of first aid can heal more hit points over time than just rest.}
{207}{}{The healing of major wounds and crippled limbs. Without this skill, it will take a much longer period of time to restore crippled limbs to use.}
{208}{}{A csendes mozgás és az észrevétlenség képessége. Ha sikeres, sokkal nehezebben vesznek észre. Nem tudsz egyszerre futni és lopakodni.}
{209}{}{Zárak kinyitása a megfelelõ kulcs híján. Tolvajkulcs vagy elektromos zárnyitó használata jelentõsen növeli ezt a képzettséget.}
{210}{}{The ability to make the things of others your own. Can be used to steal from people or places.}
{211}{}{The finding and removal of traps. Also the setting of explosives for demolition purposes.}
{212}{}{Tudományok, ismeretek gyûjtõképzettsége, mint például a számítás-technika, biológia, fizika és geológia.}
{213}{}{A Tudományok képzettség gyakorlati alkalmazása lerobbant, hibás berendezések, gépek vagy elektronikus eszközök javítására.}
{214}{}{A kommunikáció célratörõ és hatásos módja. Mások meggyõzése arról, hogy amit te mondasz az úgy is van. A leleplezõdés nélküli hazudozás képzettsége.}
{215}{}{Kereskedelem és minden hozzá kapcsolódó feladat. A megfelelõ képzettség, hogy drágán adj el, és olcsón vásárolj.}
{216}{}{A fogadás mikéntjének ismerete és gyakorlati alkalmazása. Kártya, kocka és egyéb hazárdjátékok ûzése.}
{217}{}{A pusztákon való túlélés gyakorlati alkalmazása. Magában foglalja az állatok és növények ismeretét.}
{300}{}{+ (4 x ÜG)}
{301}{}{+ (2 x ÜG)}
{302}{}{+ (2 x ÜG)}
{303}{}{+ (2 x (ÜG + ER))}
{304}{}{+ (2 x (ÜG + ER))}
{305}{}{+ (4 x ÜG)}
{306}{}{+ (2 x (ÉR + IN))}
{307}{}{+ (ÉR + IN)}
{308}{}{+ (3 x ÜG)}
{309}{}{+ (ÉR + ÜG)}
{310}{}{+ (3 x ÜG)}
{311}{}{+ (ÉR + ÜG)}
{312}{}{+ (4 x IN)}
{313}{}{+ (3 x IN)}
{314}{}{+ (5 x KA)}
{315}{}{+ (4 x KA)}
{316}{}{+ (5 x SZ)}
{317}{}{+ (2 x (KI + IN))}
{500}{}{%d életerõt gyógyítottál.}
{501}{}{Már makk egészséges vagy.}
{502}{}{%s makk egészségesnek látszik.}
{503}{}{Nem sikerült gyógyítanod.}
{505}{}{A képzettség használatáért %d TP-t kapsz.}
{510}{}{\nskill_use: invalid skill used.}
{512}{}{A halottakat képtelenség meggyógyítani.}
{513}{}{Hagyd a halottat békében nyugodni!}
{514}{}{Meghalt, nincs mit tenni.}
{520}{}{Meggyógyítottad a %s.}
{521}{}{Meggyógyítottad a %s.}
{525}{}{Nem sikerült meggyógyítani a %s.}
{526}{}{Nem sikerült meggyógyítani a %s.}
{530}{}{sérült szemet}
{531}{}{sérült bal karodat}
{532}{}{sérült jobb karodat}
{533}{}{sérült jobb lábadat}
{534}{}{sérült bal lábadat}
{550}{}{Nem sikerült feltörnöd a zárat.}
{551}{}{Nem találtál csapdát.}
{552}{}{Nem lettél okosabb.}
{553}{}{Nem tudod megjavítani.}
{570}{}{Lebuktál az áhított %s ellopása közben.}
{571}{}{Sikerült ellopnod: %s.}
{572}{}{Miközben a tiltott %s becsempészésén ügyködtél, sikeresen lebuktál.}
{573}{}{Sikerült becsempészned: %s.}
{590}{}{You've taxed your ability with that skill. Wait a while.}
{591}{}{Túl fáradt vagy.}
{592}{}{Belehalnál az erõfeszítésbe.}
{600}{}{Nem vagy elég képzett ilyen sérülések gyógyítására.}
{601}{}{Ezt a robotot már nem lehet megjavítani.}
{1000}{}{Hadd segítsek!}
{1001}{}{Nem látom akadályát...}
{1002}{}{Megvan!}
{1003}{}{Örülök, hogy segíthettem.}
{1004}{}{Oké.}
{1005}{}{Megpróbálom.}
{1100}{}{Ha van valami gond, csak szólj!}
{1101}{}{Megvan?}
{1102}{}{Ahogy akarod...}
{1103}{}{Gyerünk, próbáld meg!}
{1104}{}{Próbáld meg te!}
