{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia con servoarmadura.}
{102}{}{Ves a alguien que lleva una servoarmadura de diseño inusual. Lleva una insignia en el peto con la que no estás familiarizado.}
{103}{}{Sin novedad.}
{104}{}{A mí no me pasa nada, ¿y a ti?}
{105}{}{¿No deberías estar en tu puesto, soldado? No es buena idea estar vagando por aquí.}
{106}{}{No llevas el uniforme.}
{107}{}{Será mejor que te presentes ante el sargento y te vistas.}
{108}{}{Te la estás jugando al no llevar el uniforme. Será mejor que te presentes ante Intendencia.}
{109}{}{¿Quién demonios sois vosotros... ¡Alerta! ¡Intrusos!}
{110}{}{¡Hemos sufrido una infiltración! ¡Alerta!}
{111}{}{¡Múltiples intrusos! ¡Dad la alarma!}
{112}{}{¡Alerta de seguridad! ¡Sellad la base!}
{113}{}{¡Asegurad todas las estaciones! ¡Estamos en alerta!}
{114}{}{¡Alerta de intrusos! ¡Pasad a Código Rojo!}
{115}{}{¡Te aplastaremos!}
{116}{}{¡El Enclave dominará el mundo!}
{117}{}{¡Tú morirás y el Enclave sobrevivirá!}
{200}{}{...gilipollas...}
{201}{}{...si, será MEJOR que huyas...}
{202}{}{...qué lameculos...}
{203}{}{...¡sí, señor! ¡puto señor!...}
{300}{}{Espere. ¿Qué crees que estás haciendo con eso avión? No hay vuelos programados por varios días.}
{301}{}{¿Nrg?}
{302}{}{Soy consciente de esto.}
{303}{}{Lo siento. Sólo estaba mirando. Ya me marcho.}
{304}{}{Ha habido un cambio de planes. Estoy tomando este avión.}
{310}{}{¿Qué? Oh, ya veo. Mira, no lo toques. ¿Vale? Toques un otra vez y mueres.}
{311}{}{(Sonríes, y luego le atacas).}
{312}{}{(Te vas).}
{315}{}{Oh mierda, parece que tenemos un intruso. ¡Código Rojo! ¡Repito, código Rojo!}
{316}{}{Eso suena como un buena idea. Toques el avión de nuevo y pondré una bala en tu cabeza.}
{320}{}{Cierto. Y por lo tanto eres...}
{321}{}{Ya me iba. Siento molestarte.}
{322}{}{A punto de entregar un mensaje importante a la base principal.}
{323}{}{Oh, ¿de verdad? ¿Y qué dice ese mensaje?}
{324}{}{Es súper secreto. No puedo decírtelo.}
{325}{}{Te lo diré, pero es absolutamente esencial que no reveles esta información a nadie más, por miedo a un pánico masivo. Verá, se me ha llamado la atención que uno de los envíos de esclavos recientes está infectado con una cepa de virus desconocida y altamente mortal. *Debo* llegar a la base inmediatamente, o todos nuestras vidas podrían pederse. Ahora deja de perder mi tiempo, no hay un momento de sobra.}
{326}{}{Siiiiiiiiiiii, te creooooooooooo. Parece que tenemos una intrusa...}
{327}{}{¡Maldición! Ah, lo que sea. Nunca me dicen cosas por aquí. Bueno. Este en tu camino.}
{328}{}{Guau, eso suena mal. Será mejor que te muevas, no quiero esa mierda en mis manos. Eh, y no te preocupes, no se lo diré a nadie.}
{329}{}{[HECHO]}
{400}{}{[Después de una media hora de estar sentado en la oscura bodega de carga, sientes que la nave aterriza de nuevo en la tierra. Un momento después, la puerta de carga se abre y ves un escuadrón de soldados con servoarmaduras. Uno de ellos tarda en reaccionar y luego se vuelve hacia los demás.] ¡Mierda! ¡Uno de esos muti del Yermo se metio en el 'pájaro! ¡ALERTA! ¡Tenemos un intruso!}
{401}{}{[Después de una media hora de estar sentado en la oscura bodega de carga, sientes que la nave aterriza de nuevo en la tierra. Un momento después, la puerta de carga se abre y ves un escuadrón de soldados con servoarmadura. Uno de ellos tarda en reaccionar y luego se vuelve hacia los demás.] ¡Mierda! ¡Algunos de esos mutis del Yermo se metieron en el 'pájaro! ¡ALERTA! ¡Tenemos intrusos!}
{402}{}{[Saltas y miras cuántos puedes derribar antes de que te derriben.]}
{403}{}{[Levantas las manos en señal de rendición y esperas lo mejor.]}
{410}{}{Aw, no parece que el muti vaya a pelear. Tal vez deberíamos llevarlo al Comandante - ver qué quiere hacer al respecto.}
{411}{}{Aw, no parece que la muti vaya a pelear. Tal vez deberíamos llevarla al Comandante - ver qué quiere hacer al respecto.}
{412}{}{Aw, no parece que los mutis vayan a pelear. Tal vez deberíamos llevarlos al Comandante - ver qué quiere hacer al respecto.}
{420}{}{[Después de una media hora de estar sentado en la oscura bodega de carga, sientes que la nave aterriza de nuevo en la tierra. Un momento después, la puerta de carga se abre y ves a un escuadrón de soldados de Enclave. Uno de ellos te hace una doble impresión.] ¿Qué diablos estás haciendo aquí? No estabas autorizada para estar en esa misión. ¿Cuál es tu nombre, soldado?}
{421}{}{No importa cuál sea mi nombre, porque no estoy aquí para hablar. [Saltas y comienzas a luchar.]}
{422}{}{¿Yo? Oh, estoy, eh, * tos * murmurar * tos *. Aun así, no importa. De hecho, probablemente debería irme ahora. [Sales e intentas alejarte con indiferencia.]}
{423}{}{Mi nombre es }
{424}{}{. ¿Dónde estoy?}
{425}{}{No, ¿cuál es * tu * nombre, soldado? Me pusieron aquí para ponerte a prueba y debo decir que FALLASTE. ¡Si fuera un asesino suicida del Yermo, tú y toda tu compañia estarían muertos ahora mismo! Eso es inaceptable! ¡En formacion, soldado!}
{426}{}{Eh... mi nombre }
{427}{}{. ¡Me divierto en el pajaro de metal! ¡Vamos otra vez! ¡Quiero ir otra vez!}
{428}{}{No necesitas saber mi nombre. No me gustas. Yo mato. [Saltas y comienzas a luchar.]}
{430}{}{¿Qué estás, borracha? Estás en Navarro, por supuesto. Si tienes problemas de memoria, soldado, es posible que quieras que te revisen. Tal vez parte de esa radiación te lleguo.}
{440}{}{No me des esa mierda. Eres una de los nuevos reclutas, ¿verdad? Je. Esa boca inteligente tuya te causará todo tipo de problemas, y no puedo esperar para ver que suceda. Ahora vuelve a tu puesto, soldado.}
{450}{}{¡Señor! ¡Sí señor!}
{451}{}{¡Señora! ¡Si, señora!}
{460}{}{[El soldado mira a uno de sus camaradas.] Dios mío, el contacto con todos los mutis y la radiación que hay allí debe haberlo retrasado. ¿Lo ves? * Esa es * la razón por la que nunca me ofrezco voluntario para esas corridas al Yermo. De todos modos, saquemos a este estúpido bastardo de su miseria antes de que nos contamine.}
{461}{}{[El soldado mira a uno de sus camaradas.] Dios mío, el contacto con todos los mutis y la radiación debió haberla retrasado. ¿Lo ves? * Esa es * la razón por la que nunca me ofrezco voluntario para esas corridas al Yermo. De todos modos, saquemos a esta estúpida perra de su miseria antes de que ella nos contamine.}
