{100}{}{Ves a un sórdido comerciante en efectivo.}
{101}{}{Parece que compraría cualquier cosa sólo para hacer que la gente juegue aquí.}
{102}{}{¿qué quieres?}
{103}{}{Quiero comerciar con algunas cosas.}
{104}{}{Nada.}
{105}{}{quiero cositas brillantes.}
{106}{}{Marcho adiós yo.}
{107}{}{¿Algo más?}
{108}{}{Tengo algunas cosas más con las que comerciar.}
{109}{}{Quiero más cositas brillantes.}
