{100}{}{Ves a alguien que lleva una armadura de combate.}
{101}{}{Ves a un guardia.}
{102}{}{Parece estar aquí a la espera de que suceda algo.}
{103}{}{Sí, sí. Circula.}
{104}{}{Puedes estar seguro de que le gustas al señor Buster porque no tenemos que malgastar munición.}
{105}{}{Estoy aquí para patear culos y mascar chicle. La suerte que tienes es que aún me queda un chicle.}
{106}{}{¿Qué demonios estás mirando? Lárgate.}
{107}{}{Hey, I am not into that. Just make sure you keep a good distance from me.}
{108}{}{Sí, eso es, ven con papá. ¿Por qué no quedamos más tarde para tomar una copa?}
{109}{}{Cariño, preferiría acostarme con un brahmin antes de mirarte dos veces.}
{110}{}{Compra lo que sea y lárgate de aquí.}
