{100}{}{You see a tech.}
{101}{}{You see a computer tech.}
{102}{}{You see someone wearing a lab coat, complete with pocket protector and a stash of pens.}

{103}{}{Good day, soldier.}
{104}{}{Please don’t touch anything.}
{105}{}{You grunts are not supposed to be in here.}

{106}{}{You’re out of uniform. }
{107}{}{You better suit up. Armory is down the hall on the left.}
{108}{}{You’re taking a big chance being out of uniform. You better report to supply.}

{109}{}{Who the hell are you guys... Alert! Intruders!}
{110}{}{We’ve been infiltrated! Alert!}
{111}{}{Multiple intruders! Sound the alarm!}

{112}{}{Shit! Get the backups started.}
{113}{}{Shut down all classified operations.}
{114}{}{Secure the system and enable all security passwords.}

{115}{}{I’m a scientist, not a fighter!}
{116}{}{Pointy end with the laser diode goes toward the enemy. Then pull trigger.}
{117}{}{Help! Help! To the computer lab!}