{100}{}{You see bright, shiny tin man.}
{101}{}{A soldier in power armor.}
{102}{}{A soldier in some new type of power armor, you’d guess.}

{103}{}{Can you believe it? I got KP duty again!}
{104}{}{Word is the old man’s gonna issue leave to SF!}
{105}{}{To hell with waiting. I say we nuke all these primitives and get things over with.}
{106}{}{Got a light? Oh wait, never mind. Got one.}
{107}{}{Craps game behind the hanger tonight. Don’t let the CO know.}

{108}{}{Who the--? <zzzt> We got an intruder here!}
{109}{}{You there! Halt!}
{110}{}{Intruder on base!}

{111}{}{Wait you—oh, never mind. }
{112}{}{Look, better get your id. These false alarms got everybody jumpy.}
{113}{}{You’re supposed to be here, right? Damn these false alarm’s get on my nerves!}

{114}{}{Intruder’s over here! Get ‘em!}
{115}{}{There’s the intruder!}
{116}{}{Over here! Don’t let ‘em get away!}

{117}{}{We got an attack on the front. Send backup!}
{118}{}{Don’t let the intruder get to the gate!}
{119}{}{Die, primitive!}