# 0. Look
{100}{}{You see a bulletin board.}

{150}{}{There seem to be a few messages posted on it.}

# 1. Main Page
{200}{}{Den Bulletin: Maintained by Rebecca's Casino Bar, best drinks in the Den. }
{201}{}{Den Bulletin: Maintained by Rebecca's Casino Bar...}
{202}{}{[Someone has scribbled something on the side of this post.]}
{203}{}{[You notice that a part of this post has been torn off.]}
{204}{}{Slaver's Guild}
{205}{}{Bars & Gambling}
{206}{}{Dining}
{207}{}{Shops}

# 2. Slaver's Guild
{225}{}{The Slaver's Guild is the best and only supplier of slaves in the wastes.}

# 3. Slaver's - Continue
{250}{}{For employment opportunities, buying or selling of slaves, see Slave Master Metzger.}

# 4. Slaver's - Directions
{275}{}{The Slaver's Guild is located on the east side of town, past Becky's and Frankie's.}

# 5. Slaver's - Not selling
{300}{}{They are currently not selling slaves to the general public, due to increased demand.}

# 6. Bars and Gambling
{325}{}{[Two are listed.]}

# 7. Becky's Casino Bar
{350}{}{Rebecca's Casino Bar has both gambling and great affordable drinks.}

# 8. Becky's Directions.
{375}{}{We are located just east of here. We are the first building on the left as you enter town. Be sure to come by and say hello!}

# 9. Frankie's Message
{400}{}{Becky's a hore and her drinks is watered down! She's a krook and a lier! [The writing is barely legible.]}
{401}{}{[The message that was here is neatly torn off.]}

# 10. Dumb Board
{425}{}{Words words... by... words... Bar... words... in the Den.}
{426}{}{You find it all very confusing and your head starts to hurt.}

# 11. Frankie's
{450}{}{Frankie runs a bar, inn, and 'pleasure' business on the east side of town.}

# 12. Dining
{475}{}{Mom's is the only restaurant in the Den. She's located on the east side of town just south of the Slaver's Guild.}

# 13. Becky Dead
{500}{}{[It looks like someone tried to set it on fire. You can't make out any of the posts.]}

# 14. Shops
{525}{}{[There are three posts.]}

# 15. Tubby's
{550}{}{Tubby sells all sorts of items, but primarily drugs and ammo.}

# 16. Tubby's Directions
{575}{}{Tubby's is located west of this bulletin board. It's the first building on the right as you enter town.}

# 17. Flick
{600}{}{Flick sells various items out of his 'office' in the residential building directly south from here and right below Rebecca's Casino Bar.}

# 18. Smitty
{625}{}{Smitty is the local mechanic. He sometimes has things for sale.}

# 19. Smitty Directions
{650}{}{Smitty's located in the junkyard on the southwest corner of town.}

# MENU OPTIONS
{1000}{}{Continue}
{1010}{}{Directions:}
{1020}{}{Exit}
{1030}{}{Flick's}
{1040}{}{Frankie's}
{1050}{}{Rebecca's Casino Bar}
{1060}{}{Return to Main Page}
{1070}{}{Smitty}
{1080}{}{Special Note:}
{1090}{}{Tubby's}
