{100}{}{You see a little rugrat.}
{101}{}{You see Melchior, Jr.}

{150}{}{He seems like a smiley, big-eyed kid.}

{200}{}{Hello! I'm Melchior, Jr.}
{201}{}{My dad's a miner. His name is Melchior just like mine.}
{202}{}{My dad is a good miner, but he wants to be a magician.}
{203}{}{Daddy's stage name is Melchior the Magnificent.}
{204}{}{His best trick was pulling a rat out of a hat.}
{205}{}{He went away with some men dressed in metal clothes.}
{206}{}{I hope dad comes back soon. I miss his magic tricks.}
{207}{}{I'm going to be a great magician like my dad.}