{100}{}{The generator has a damaged circuit board. Maybe you could scavenge replacement parts from some junk.}
{101}{}{You see a generator.}
{102}{}{You see an EPA lighting generator.}
{103}{}{You see a generator that controls the lighting in the EPA.}
{104}{}{After a lengthy search, a circuit board with some damaged pieces is located. Maybe if some junk is found to scavenge through, some replacement parts could be obtained.}
{105}{}{There's the problem!}
{106}{}{The broken parts have been mended together and the generator is back online.}
{107}{}{Nothing wrong can be found with the generator. It just doesn't seem work.}
{108}{}{It's working. There's nothing else to do.}
{109}{}{Something doesn't seem right with this generator.}

{200}{}{*whirr*}
{201}{}{*bzzt*}

