{100}{}{You see a man in metal armor.}
{101}{}{You see Joshua.}
{102}{}{You see a man wearing metal armor with a lightning bolt insignia on it.}
{103}{}{Hello,}
{104}{}{. I'm Joshua. What can I do for you?}
{105}{}{How you know name?}
{106}{}{How do you know my name?}
{107}{}{Your recent activities have drawn attention to you. People talk and people listen, and word gets around. You need to remember that you are only one small fish in an ocean of sharks,}
{108}{}{.}
{109}{}{What that mean?}
{110}{}{What do you mean by that?}
{111}{}{Let's just say that you're the new kid on the block and you don't know what's going on in the neighborhood. There's a lot more going on than your simple quest...}
{112}{}{Go on.}
{113}{}{Go on, I'm listening.}
{114}{}{I've said enough for now. I think you should get about your business.}
{115}{}{Wait, me need ask question.}
{116}{}{Wait, I need to ask you some questions.}
{117}{}{All right, you're allowed one question. What will it be?}
{118}{}{You know where me find GECK?}
{119}{}{You know where me find Vault 13?}
{120}{}{Me look for trader name Vic. Where I find?}
{121}{}{Do you know where I can find a GECK?}
{122}{}{Do you know where I can find Vault 13?}
{123}{}{I'm looking for a trader named Vic. Do you know where I can find him?}
{124}{}{The GECKs were a standard issue item for all vaults. If memory serves me right they were to be used after the vault opened to rebuild civilization. I can only assume that one could be found in an unopened vault. Good luck,}
{125}{}{Thanks.}
{126}{}{I've heard plenty of tales about Vault 13 and none of them speak of its whereabouts. Good luck,}
{127}{}{Thanks.}
{128}{}{Vic has run afoul of the slaver's guild. You can find him there. Good luck,}
{129}{}{Wait! Where I find guild?}
{130}{}{Wait, can you tell me where the slaver's guild is?}
{131}{}{Hello again. I have nothing more to say to you.}
{132}{}{. Well... You've certainly come a long way from the simple tribesman. You should visit our New California Republic office some time. You might find it rewarding. Now, if you'll excuse me...}
{133}{}{Hello again. I have nothing more to say to you.}
{134}{}{Wait...}
{135}{}{That is a private office.}
{136}{}{There is nothing for you in there.}
{137}{}{This is private property, so move along.}