{100}{}{You see a friendly-looking punk.}
{101}{}{You see Marc.}
{102}{}{You see a friendly-looking punk.}
{103}{}{You son of a bitch - how could you do this to us?}
{104}{}{What can I do for ya, mama-jamma?}
{105}{}{What can I do ya for, mama-jamma?}
{106}{}{Ooh! Ooh! Aah!}
{107}{}{Who are you?}
{108}{}{What is this place?}
{109}{}{Who's in charge?}
{110}{}{Nothing. Bye.}
{111}{}{Hmm. Nope, sorry, can't help you with that. Maybe you should try someone else.}
{112}{}{Anks?}
{113}{}{I'm Marc. I'm the resident smart-ass and know-it-all.  ::he smiles::}
{114}{}{Oh. I have other questions.}
{115}{}{Bye.}
{116}{}{This is the Poseidon Marine Vessel Valdez - also called the PMV Valdez. If you want more information about the Valdez, the best person to ask is the Captain.}
{117}{}{The Captain? Who's that?}
{118}{}{I have other questions.}
{119}{}{Bye.}
{120}{}{In charge? No one's in charge of us.}
{121}{}{Where'd you all come from?}
{122}{}{I have other questions to ask you, then.}
{123}{}{Bye.}
{124}{}{The Captain is a tough-ass ol' military guy. He sits upstairs there and checks the place out. He's got some thorough knowledge about this ship.}
{125}{}{Thanks. I have more questions.}
{126}{}{Thanks. Bye.}
{127}{}{Oh, all over the wasteland. We'd heard things about San Francisco, passed down from our elders. Some of us have ancestors who used to live here before the great war.  You want to hear more?}
{128}{}{Yes.}
{129}{}{No, but I wanted to ask you something else.}
{130}{}{No, that's all.}
{131}{}{We're a band of musicians, tekheads, geeks, and artists. We thought we'd come back to someplace famous for artistic and personal freedom. I came here to spawn. Wanna hear more still?}
{132}{}{Yes.}
{133}{}{No, but I wanted to ask you something else.}
{134}{}{No, that's all.}
{135}{}{Well, when we got here, we figured we'd camp out here until we either figured out how to get this tanker moving again or until we thought of something else.}
{136}{}{Have you figured out how to move the tanker?}
{137}{}{Tell me about the Hubologists.}
{138}{}{Tell me about the Shi.}
{139}{}{I have other questions.}
{140}{}{Thanks. Bye.}
{141}{}{I think the Captain's figured out how to do it - but we need several elements first. We've basically given up on taking it for ourselves, to tell the truth - we've got other plans now.}
{142}{}{What are they?}
{143}{}{Where can I find the Captain?}
{144}{}{I wanted to ask something else.}
{145}{}{Bye.}
{146}{}{They're crazy. Don't trust them - unless you're mentally feeble or like being screwed over. They're interested only in your money and your soul, and there's a good chance they'll destroy the one to get at the other. I've seen it happen too many times.}
{147}{}{Have you figured out to move the tanker?}
{148}{}{Tell me about the Shi.}
{149}{}{I have other questions.}
{150}{}{Bye.}
{151}{}{They're a good sort, as far as they go. They're a little untrusting of outsiders, but then, that's not always such a bad attitude to take in these times. They've got some weird customs and they talk funny, but they're all right.}
{152}{}{Have you figured out to move the tanker?}
{153}{}{Tell me about the Hubologists.}
{154}{}{I have other questions.}
{155}{}{Bye.}
{156}{}{You want to know what our plans are? We're going to keep moving around until we can find a place that hasn't been screwed over by human greed and then we're going to try to set up a better society.}
{157}{}{Do you know how you're going to do that?}
{158}{}{I have other questions.}
{159}{}{Thanks. Bye.}
{160}{}{We're hoping that if we can avoid society's mistakes. Hell, things can't get much worse.}
{161}{}{Have you figured out to move the tanker?}
{162}{}{Tell me about the Hubologists.}
{163}{}{Tell me about the Shi.}
{164}{}{I have other questions.}
{165}{}{Thanks. Bye.}

{166}{}{You seen Badger's girlfriend around?}
{167}{}{I think I saw her go down below. There's a hole on the north side of this deck.}