{100}{}{You see a larger than average Ghoul.}
{101}{}{You see Zomak, known to some as the Destroyer.}
{102}{}{You see a big, burly, Ghoul whose face, beneath a sharply sloping forehead, reflects vast reserves of simpleminded superiority.}

{110}{}{Renew Comrade! I am Zomak. Some call me Zomak the Destroyer. What is your business here?}
{111}{}{Renew Comrade! What are you doing here? State your business to Zomak the Destroyer.}
{112}{}{Renu!}
{113}{}{Ook?}
{114}{}{I’m just looking around.}
{115}{}{I wish to Renew.}
{116}{}{I took a wrong turn.}

{120}{}{You should look somewhere else. Or Zomak will show you the stars.}

{130}{}{Then you must see him.}
{131}{}{Him? Where is him, I mean he?}
{132}{}{I’m not worthy of seeing him. Goodbye.}

{140}{}{He is the granter of enlightenment. It is he that promises Renewal to all who follow him.}
{141}{}{Well, I’m just about due for renewal. Where is he?}
{142}{}{Sounds like another nutcase to me. I’m outa here.}

{150}{}{Well, he’s right back…. Hey, just who are you anyway?}
{151}{}{I’m just a Wanderer.}
{152}{}{I am the Chosen One.}
{153}{}{I’m just here for my annual renewal.}
{154}{}{It’ll be OK. I just have to ask him a couple of questions.}

{160}{}{Well, wander on out of here then.}
{161}{}{Uh, OK. Goodbye.}

{170}{}{Well, in that case. Come on in. He’s right in the next room. Don’t keep him waiting.}
{171}{}{Not me, I’ll go right in. Goodbye.}
{172}{}{I might come back later. Goodbye.}

{180}{}{Well you should choose to leave. Get out of here.}
{181}{}{OK.}

{200}{}{Yes, you can all renew inside.}
{201}{}{OK.}

{210}{}{Ook? What do you mean by that? Are you dumb?}
{211}{}{Goop?}

{220}{}{Get out of here. The Brain doesn’t have time for the likes of you.}
{221}{}{OK. I’ll be going now.}

{230}{}{There’s nothing else down here but The Brain’s lair. Boy, are you dumb.}
{231}{}{The Brain?}
{232}{}{I was just testing you. You passed. Now let me in.}
{233}{}{I guess I got confused. Must be all this radiation. Goodbye.}

{240}{}{Oops. Uh, there’s nothing here. Nothing at all. Just go away now.}
{241}{}{You’re sure there’s nothing here?}
{242}{}{OK. Goodbye.}

{250}{}{Yup. I’m sure. Now get out.}
{251}{}{Well if you say so. Goodbye.}

{260}{}{Oh, heh, heh, Yeah. I knew that. Umm, well, err, did I pass? }
{261}{}{You sure did. Now let me in.}
{262}{}{No, you failed, and now I have to report you.}

{270}{}{OK, then. You can go right in.}
{271}{}{OK. Goodbye.}

{280}{}{You have the sign. Go right in.}
{281}{}{Gooo.}
{282}{}{The Sign?}
{283}{}{Fear the sign. Goodbye.}

{290}{}{Yes, the sacred talisman of renewal. Renew Comrade! Renew!}
{291}{}{Yes, Reno to you too. Goodbye.}

{300}{}{Renew Brother. You may pass.}
{301}{}{Renew Sister. You may pass.}