{100}{}{You see a dead body. It appears to have been chewed by animals.}
{101}{}{Upon closer inspection it appears this person was shot before being chewed by animals.}
{102}{}{You see the body of a young Broken Hills woman.}
{103}{}{There appears to be a piece of paper of some kind sticking through the lining of her clothing.}
{104}{}{Upon closer inspection it appears this person was shot before being chewed by animals.}