# 0. QUICK LOOK

# 0. LOOK
{150}{}{You see a lean, hungry-looking man. He has a haggard look, and a thin coat of stubble
 covers his chin.}
{151}{}{You see Pretty Boy Lloyd.}
{152}{}{You see Pretty Boy Lloyd. He is watching you warily.}

# 1. FLOAT DIALOGUES (WTG)
{200}{}{Gotta get outta town…}

# 2. INTRODUCTIONS IN IGNORANCE (WTG)
{210}{}{Who're you? What're you doing down here?!}
{211}{}{You again?! What're you doing down here?!}
{212}{}{Nuttin honey}
{213}{}{Me }
{214}{}{Wander off}
{215}{}{What are YOU doing down here?}
{216}{}{Calm down, friend, THEN we'll talk. Everything all right?}
{217}{}{You Lloyd? Pretty Boy Lloyd?}
{218}{}{Nothing. Just looking around. See you.}

# 3. NUTTIN' HONEY (2)
{225}{}{Well, get outta here. And don't you be telling anyone you saw me, you hear?}
{226}{}{Me here. Now me gone!}

# 4. ME X ME X ME X WHO U/WHO ARE YOU AND WHAT ARE YOU DOING DOWN HERE/CALM DOWN, FRIEND . . . (2, 28)
{230}{}{None of your business...friend. I suggest you just head right back up those stairs and forget
 we ever met.}
{231}{}{Me Forget. 4-get, four-git…uh…forget whut?}
{232}{}{Okee Dokee}
{233}{}{I don't care much for your suggestion…friend. What's the problem here?}
{234}{}{You sound like a man in trouble. I might be able to help you.}
{235}{}{You look like a man who values his privacy. For someone as talkative as I am, forgetting
 you could be very expensive.}

# 5. WHAT SEEMS TO BE THE PROBLEM HERE? [LLOYD NOT AFRAID] (4)
{245}{}{Problem? The problem's standing right in front of me. }
{246}{}{Now I'm not going to say it again, fella: Leave.}
{247}{}{Now I'm not going to say it again, sweetheart: Leave.}
{248}{}{You *threatening* me? Think VERY carefully before you answer.}

# 6. WHAT SEEMS TO BE THE PROBLEM HERE? [LLOYD AFRAID] (4)
{255}{}{Problem? No problem, friend, no problem at all. Just looking for a little privacy is all.}
{256}{}{Problem? No problem, sweetheart, no problem. Just looking for a little privacy is all.}
{257}{}{Problem? Not at all. Just looking for a little privacy is all. Still…it WAS rude of me to turn away such a lovely lady.}
{258}{}{I think you DO have a problem. See, all this privacy makes it hard for anyone to hear
 what's going on down here. Maybe I'll just kill you, eh?}
{260}{}{For someone as talkative as I am, privacy can be pretty expensive.}
{261}{}{All right then. Sorry to bother you.}
{262}{}{You're right. It WAS rude. I'll be going now.}

# 7. YOU THREATENING ME? [BAD, LLOYD NOT AFRAID] (5)
{270}{}{(Eyes narrow.) }
{271}{}{If you came down here looking for trouble, you hit the jackpot, friend. }
{272}{}{If you came down here looking for trouble, you hit the jackpot, sweetheart. }
{273}{}{Hope you done paid your respects…}
{274}{}{You want some trouble? You GOT troub --}

# 8. YOU THREATENING ME? [LLOYD SCARED SHITLESS] (5)
{283}{}{Uh...now, look…I'm not threatening anyone, and I'm certainly not looking for any trouble.}
{284}{}{I think you DO have a problem. See, all this privacy makes it difficult for anyone to hear
 what's going on down here. Maybe I'll just kill you, eh?}
{285}{}{You look like a man in trouble, and I might be able to help you. What do you say?}
{286}{}{You sound like a man who values his privacy. For someone as talkative as I am, forgetting
 you could be very expensive.}
{287}{}{All right then…sorry to bother you.}

# 9. THREATEN TO KILL LLOYD… [LLOYD NEGOTIATES] (6, 8)
{295}{}{Uh...hey, now…there's, uh, no need for that kind of talk. Maybe we can talk about something
 ELSE: how much your friend Lloyd can help you.}
{296}{}{I'm interested. You keep on talking.}
{297}{}{Not interested. I'm outta here.}
{298}{}{Forget it, Lloyd. Your number's up. Prepare to die.}

# 10. THREATEN TO KILL LLOYD… [LLOYD FREAKS] (6, 8, 12)
{305}{}{(The man's face turns pale. He swallows for a second…then lunges at you!)}
{306}{}{Son of a b -}

# 11. KEEP TALKING . . . (4, 5, 6, 8, 9)
{315}{}{I got some chips…maybe a little money can clear the air between us, keep everything civil?}
{316}{}{Fine. Give me everything you got.}
{318}{}{Keep your money. I'm outta here.}

# 12. FINE. GIVE ME EVERTHING YOU GOT . . . (11)
{325}{}{All right then, all right…(He reaches into pocket, pulls out some chips, then hands them over to you.)…now
 how about you take that money, head on upstairs and have a good time on Lloyd, you hear?}
{326}{}{Maybe you're deaf. I SAID, give me everything you got.}
{327}{}{Okay. Well, after I kill you.}
{328}{}{All right then. I'm outta here.}

# 13. I SAID, GIVE ME EVERTHING YOU GOT [LLOYD FRIGHTENED] (12)
{335}{}{Uh, now...that's all I got in the world, friend. I ain't got no more; I done gave it all
 to you.}
{336}{}{Don't screw with me, Lloyd. I KNOW you got
 more; you're a smart guy. Last chance: where's the rest?}
{337}{}{We'll see about that, Lloyd. I'm going to see what I find when I search your corpse.}

# 14. DON'T FUCK WITH ME LLOYD . . . (4, 5, 6, 8, 13)
{345}{}{I…I said…ehh…all right now…I know where you can find more cash…it ain't mine, see, and it's
 more trouble than it's worth, but you want it, it's yours.}
{346}{}{Could be I know where it is you can find some cash…it ain't mine, see, and it's more trouble
 than it's worth, but you want it, it's yours.}
{347}{}{Keep talking and keep it interesting.}
{348}{}{Actually, I was just kidding about giving you a chance, Lloyd. I'm just going to kill
 you and let the spirits sort it out.}
{349}{}{I'm not interested in your double-talk brahmin shit. I'm outta here.}

# 15. KEEP TALKING AND KEEP IT INTERESTING (14)
{355}{}{All right then…it's on the Golgotha plain south of Reno, buried in one of the
 graves. Only I know where it is, though.}
{357}{}{Tell me.}
{358}{}{That's the biggest load of…oh hell, I'm just going to kill you, Lloyd and let the spirits
 sort it out.}
{359}{}{Oh, forget this horseshit. I'm outta here.}

# 16. TELL ME WHERE THE MONEY IS (15, 24, 25)
{365}{}{Face the sign at the Golgotha crossroads, walk northwest until you hit the third grave, then
 head northeast until you hit the first stake. It's a grave near there, marked "Arch Stanton."
 Dig down about six feet, and you'll find it.}
{366}{}{Face sign, go northwest three graves, go northeast until the first stake, then look for
 "Arch Stanton"…all right, let's go, Lloyd. I need someone to dig, after all.}
{367}{}{All right then. I'm outta here. Make yourself scarce. (Let Lloyd leave.)}
{368}{}{That's all I needed to know…they'll be burying you at that grave in the morning.}

# 17. SHOW ME WHERE THE MONEY IS (15, 16, 24, 25)
{375}{}{(Lloyd looks like he's about to say something, thinks better of it, then nods.) All right
 then. Seems I got no choice. Let's go.}
{376}{}{I have some stuff to take care of first. You wait here, I'll be back in a hour. (Leave, hide
 outside room, then see if Lloyd leaves and follow him.)}
{377}{}{I have some stuff to take care of first. You wait here, I'll be back.}
{378}{}{I'm right behind you.}

# 18. YOU LOOK LIKE A MAN IN TROUBLE, AND I MIGHT BE ABLE TO HELP YOU. WHAT DO YOU SAY? (4, 5, 6, 8)
{385}{}{Hmmmmm. I don't know you, friend...but I'm thinking I'd like to. Name's Lloyd. Some call me Pretty Boy
 Lloyd, but that's them, not me.}
{386}{}{Hmmmmm. I don't know you, sweetheart...but I'm thinking I'd like to. Name's Lloyd. Some call me Pretty Boy
 Lloyd, but that's them, not me.}
{387}{}{Hmmmmm. 'm not fool enough to turn down help from a beautiful woman. Name's Lloyd. Some call me Pretty Boy
 Lloyd, but that's them, not me.}
{388}{}{Pleased to meet you. So...about my offer...?}

# 19. WHAT MISUNDERSTANDING? (36)
{395}{}{The Salvatore family and I had a…disagreement over my success at one of their gambling tables.
 I think the matter can only be settled by removing myself as far from New Reno as possible.}
{396}{}{Success at their gambling tables, eh? How much you win, Lloyd?}
{397}{}{How can I help?}
{398}{}{What's in it for me?}
{399}{}{I don't think I can help you, Lloyd. I think we better just forget we met. Goodbye.}

# 20. HOW CAN I HELP? (19)
{405}{}{Hmmmm…you look well-equipped to serve as a bodyguard. Help me get out of town. Escort me
 to the Gologtha plain to the south, and I can pay you some chips for your trouble.}
{407}{}{Done. Let's go. (Follow him.)}

# 21. SUCCESS AT THEIR GAMBLING TABLES . . . ? (19, 20)
{415}{}{(Pales, then regains composure.) Enough to get them mad. Most was spent in bribes keeping the Salvatore
 thugs off of my back long enough to slip down here and hide. I've been afraid to show myself in town…}
{416}{}{(Looks surprised, then regains composure.) Enough to get them mad. Most was spent in bribes keeping the Salvatore thugs off of
 my back long enough to slip down here and hide. I've been afraid to show myself in town…}
{417}{}{I'll help you, but I'll want half that money you won, Lloyd. Don't cheat me on this if you
 know what's good for you.}
{418}{}{Give me half of what you won at the tables, and I'll help you, Lloyd. It's a fair exchange
 to see that you get out of town in one piece.}
{419}{}{All right, I'll help you. Let's get outta here. (Follow him.)}
{420}{}{I don't think I can help you, Lloyd. Goodbye.}

# 22. GIVE ME HALF (21)
{425}{}{(Looks like he's about to say something, thinks better of it, then nods.) Seems I got no
 choice. Let's go.}
{427}{}{No, you wait here and keep quiet until I come back. I got to take care of some stuff, then
 I'll be back and we'll go on our field trip.}

# 23. YOU LLOYD? PRETTY BOY LLOYD? (2, 4)
{435}{}{(Stiffens.) Maybe. Who are you? I don't believe I've had the pleasure…}
{436}{}{(Stiffens, then raises an eyebrow.) Maybe. I'm certain I would have remembered you, miss.
 I don't believe I've had the pleasure…?}
{437}{}{Dispense with the bullshit, Lloyd. I'm here for the money you stole from Mr. Salvatore.}
{438}{}{Look, Lloyd, hand over the cash and I MIGHT forget I ever saw you until you're far away
 from here.}
{439}{}{Lloyd, Mr. Salvatore sent me here to get his money back and have me make an…example of you.
 It doesn't need to be that way...IF the two of us can come to an arrangement.}

# 24. DISPENSE WITH THE BULLSHIT (23, 28, 29, 31, 32, 33)
{445}{}{All right…all right now… (Swallows.) It's on the Golgotha plains south of Reno, buried in
 one of the graves. Only I know where it is, though.}
{446}{}{Show me.}
{448}{}{That's the biggest load of…oh hell, I'm just going to kill you and find the cash
 on my own.}

# 25. I MIGHT FORGET I EVER SAW YOU . . . (23)
{455}{}{Hmmmmmm. I don't think either one of us believes that… (Swallows.) But maybe I can trust you.
 The money's buried on the Golgotha plains south of Reno, in one of the graves. Only I know where
 it is, though.}
{459}{}{Oh, forget this horseshit. I'm leaving. Keep your cash and your secret and get out of my sight.}

# 26. ARRANGEMENT . . . (23, 29, 31)
{465}{}{Hmmmm. An 'arrangement' you say…all right, all right…what is it you want?}
{466}{}{I'll get you out of town for half of that money you won from Mr. Salvatore, Lloyd.}
{467}{}{I'll get you out of town in exchange for all the money you won from Mr. Salvatore, Lloyd.}
{468}{}{Aw, nevermind. I don't want anything - get outta here before I change my mind.
 (Pretend to leave, hide, then follow him.)}
{469}{}{Aw, nevemind. I don't want anything - get outta here before I change my mind.}

# 27. THE DEAL (26)
{475}{}{Well, now...hmmmm...seems I got no choice. I'm going to have to take you to where the money is,
 though, cause you won't find it otherwise. Let's go.}
{476}{}{I have some stuff to take care of first. You wait here, I'll be back in a hour. (Pretend to
 leave, hide, then follow him.)}
{477}{}{No, you wait here until I come back. I got to take care of some stuff, then I'll be back
 for you and we'll go on our field trip.}
{478}{}{I'm right behind you. (Follow him.)}

# 35. I'M HERE TO SHOW YOU OUTTA TOWN (WTG)
{555}{}{(Jumps.) Uh…ready to go?}
{556}{}{Yes. Let's go. (Follow him.)}
{557}{}{No, you wait here until I come back. I got to take care of some stuff first.}

# 36. YOU LOOK LIKE A MAN IN TROUBLE, AND I MIGHT BE ABLE TO HELP YOU. WHAT DO YOU SAY? (18)
{565}{}{And as for your offer, I COULD use some help. See, I need to get out of town, but things
 have been complicated because of a certain…misunderstanding...}
{566}{}{What misunderstanding?}

# 101. FLOAT (WTG)
{585}{}{Time to get the hell outta Reno…}
{586}{}{Damn box…}
{587}{}{Heavier than I remember…}

# 102. FLOAT (WTG)
{595}{}{Here we are…}
{596}{}{It's this one right here.}

# 103. HERE'S THE GRAVE (WTG)
{605}{}{Here we are…*whew*...the money's in…this grave here.}
{606}{}{Dig it up, Lloyd.}
{607}{}{Let me take a look at this grave first...}
{609}{}{Well, stand back and let me dig it out...}
{610}{}{Get outta here, Lloyd. This money's mine now.}

# 104. DIG IT UP, LLOYD (103)
{615}{}{(Looks winded.) As...part of your…guard duties, I'd…be grateful if you'd...dig it up.}
{616}{}{Uh...}
{617}{}{There's two types of people in this world, Lloyd. Those with loaded guns and those that dig.}
{620}{}{All right then, I'll do it…}

# 105. DIG IT UP, LLOYD (104, 109)
{625}{}{(Lloyd mumbles under his breath, then proceeds to dig.)}
{626}{}{(Lloyd mumbles under his breath, then proceeds to dig...carefully. Less than a minute
 later, he pulls out a landmine from beneath the dirt and sets it aside. He shrugs sheepishly.)}
{627}{}{Thaaat's it. You're doing great. Keep it up. Dig a little faster.}
{628}{}{Nice one, Lloyd. KEEP digging. Let's see what else is under there.}

# 106. LLOYD KEEPS DIGGING (105, 108)
{635}{}{(A half-hour later, Lloyd has dug away enough dirt to reveal a small
 manhole cover set into the ground...you're certain you wouldn't have found it if Lloyd hadn't told you about it.
 Lloyd takes a deep breath and wipes his forehead.) Old...fallout...shelter.}
{636}{}{(A half-hour later, you have dug away enough dirt to reveal a small manhole cover set into
 the ground. You wouldn't have found it if Lloyd didn't tell you where to dig. As you uncover it, Lloyd speaks.)
 It's an old fallout shelter. Found it a week ago while checking out the area.}
{637}{}{Well, let me open this up, and we'll get down to business.}
{638}{}{Open the manhole, Lloyd.}

# 107. EXAMINE THE GRAVE (103, 104)
{645}{}{(The dirt around the grave looks like it has been disturbed recently. For some reason, the
 distance Lloyd is standing for the grave makes you wonder if it hasn't been trapped.)}
{646}{}{I think you should dig, Lloyd.}
{647}{}{Hmmmm. Let me take a closer look at the grave...}
{648}{}{Stand back, Lloyd. I'm going to start digging.}

# 108. EXAMINE THE GRAVE (103, 104)
{655}{}{(The dirt around the grave looks like it has been disturbed recently. This would make
 sense if Lloyd buried the chips here.)}

# 109. LOOK FOR TRAPS (107)
{665}{}{(You make an examination of the site, and brush away the dirt. As you do, you notice a
 landmine buried in the dirt. You disarm it carefully and stow it in your pack.)}
{666}{}{Forget about this, Lloyd? Let's see if you can forget THIS, dead man.}
{667}{}{I think YOU should dig, Lloyd. Get to it.}
{668}{}{I'll let this pass, Lloyd...this time. Now stand back while I keep digging.}

# 110. MANHOLE COVER (106)
{675}{}{(The manhole cover opens with a rusty shriek, revealing a dark hole leading downwards.)}
{676}{}{Get in there, Lloyd.}
{677}{}{Stand back, Lloyd. I'm going in.}

# 111. MANHOLE COVER, LLOYD FIRST (110)
{685}{}{(Lloyd frowns, thinks about making a comment, then shrugs and climbs down into the manhole
 cover.)}
{686}{}{Hurry up, Lloyd.}
{687}{}{HEY LLOYD, CATCH! (Drop the landmine down the hole.)}
{688}{}{I'm coming down after you, Lloyd.}

# 112. WAIT . . . (111)
{695}{}{(You hear Lloyd grunting down below.) Hold on…almost got it… (There is the scraping of metal,
 then silence.)}
{696}{}{Get a move on, Lloyd. We haven't got all day.}
{698}{}{I'm coming down, Lloyd.}

# 113. MANHOLE COVER (111, 112)
{706}{}{All in a day's work...}

# 114. LLOYD, TAKE OFF (103, 107, 108, 109)
{715}{}{Right, right...all yours. No problem. I'm leaving. (Turns, then walks away.}
{716}{}{(Let him go.)}
{717}{}{(Shoot him in the back.)}

# GOLGOTHA ENTRANCE MESSAGE
{1000}{}{After a long hike, you reach the Golgotha foothills. Once there, Lloyd leads you to one
 of the graves.}
{1001}{}{You follow Lloyd to Golgotha. Once there, he digs up one of the graves.}
{1002}{}{You lose Lloyd once you get outside of New Reno.}
{1050}{}{You let Lloyd leave.}

# END LINES
{5213}{}{ Me }
{7213}{}{Who U}