{100}{}{You see a young woman in metal armor.}
{101}{}{You see Dalia.}
{102}{}{You see a pretty young woman dressed in metal armor. She watches her surroundings very
 carefully.}
{103}{}{Well, I'll be. How are you doing,} #continue to 153
{104}{}{You Dalia. Me remember you help.}
{105}{}{Things ok. Me go now.}
{106}{}{Dalia! Thanks to you, things worked out great.}
{107}{}{Things are fine, but I've got to go.}
{108}{}{Hey, I'm glad to hear that. It was my pleasure to do what I could for you. So, what can I help
 you with?}
{109}{}{Me got questions.}
{110}{}{Nothing. Me say hi.}
{111}{}{I have some questions for you.}
{112}{}{Nothing. But it's nice to see you again. Bye.}
{113}{}{What do you want to know?}
{114}{}{You prisoner.}
{115}{}{You leave when want?}
{116}{}{What know about D'claws?}
{117}{}{How you be here?}
{118}{}{Why you worry safe?}
{119}{}{Thanks. Me go.}
{120}{}{Are you a prisoner here?}
{121}{}{Can you leave anytime you want?}
{122}{}{What can you tell me about the deathclaws?}
{123}{}{How did you come to be here?}
{124}{}{Why are you worried about needing a place of safety?}
{125}{}{Thanks. I'll talk at you later.}
{126}{}{No, I'm not. I'm here of my own free will and I like it. I think this will be a safe place for
 me to stay for a while.}
{127}{}{Okay.}
{128}{}{Bye.}
{129}{}{All right.}
{130}{}{I see. Well, I'll be going then.}
{131}{}{Yeah, I've been told I'm free to go or stay. I'm staying for now.}
{132}{}{Me see.}
{133}{}{Okay then.}
{134}{}{I don't know any more about them than you do, I guess. I'm still trying to get used to
 them talking to me instead of tearing my head off and using it for a golf ball. It's scary, you know?}
{135}{}{Yeah, me bothered.}
{136}{}{Na, me used to it.}
{137}{}{Yes it is, in a lot of ways.}
{138}{}{No, I've come to accept it.}
{139}{}{After I left the Squat I didn't know what to do with myself. I figured I'd just drift into
 another town and another hired gun job... so I was wandering the desert trying to decide exactly where
 I should go. Well, one day I was looking for a good place to camp. It was getting late, and I didn't
 want to be out in the open after dark. Off in the distance a ways, I thought I saw a campfire -- so I
 decided to see who was there.}
{140}{}{Wow.}
{141}{}{That's interesting.}
{142}{}{When I let you by me in the Squat, I broke my contract with my employer. I was sure that I'd be
 hunted down and killed because of it. Seeing you here convinces me that I don't have to worry about
 that. I can only assume that my previous employer is no longer in any condition to be concerned with me
 or my whereabouts.}
{143}{}{You safe now. Dalia no worry.}
{144}{}{You're safe now, Dalia. You'll have no need to worry about any retribution.}
{145}{}{Thanks,} # continue 155
{146}{}{You welcome.}
{147}{}{Bye.}
{148}{}{You're welcome.}
{149}{}{I'll see ya.}
{150}{}{Hello.}
{151}{}{Hello again. How's it going?}
{152}{}{I have no quarrel with you. }

{153}{}{. I hope everything worked out for you at the Squat.}
{154}{}{So, I sneak up on this camp site and there are these two deathclaws sitting around the fire just
 chatting away. Idiot that I am, I let out a little cry of surprise, jumped up, and turned to run -- right
 into the arms of another deathclaw standing right behind me. Anyway, to make a long story short, it
 took awhile for me to realize that I wasn't about to be put on a spit and barbecued. Instead, I was
 brought here and 'interviewed' by Gruthar. Now I can live here if I want.}
{155}{}{. That takes a load off my mind.}