{100}{}{You see a plump, clerkish man.}
{101}{}{You see Nording the pay-clerk.}
{102}{}{You see a nervous, plump, little pigeon of a man.}
{103}{}{You can't be paid for abandoning the caravan.}
{104}{}{Uh, there were some things missing from the caravan. NCR bylaws don't allow me to pay a
 thief. Sorry.}
{105}{}{A thief? I resemble that remark, you damn ingrate! I'm leaving. Goodbye.}
{106}{}{Someday soon, you'll regret crossing me. Goodbye.}
{107}{}{I cannot reward such a catastrophic caravan. You will receive nothing from me.}
{108}{}{You cheap bastard! You'll pay for stiffing me. Goodbye.}
{109}{}{Well, sometimes you just get luckier than others. This was one of the unlucky times. Goodbye.}
{110}{}{That was a very unprofitable caravan. I cannot give you more than $500 as your share.}
{111}{}{Well, something is better than nothing, I guess. Goodbye.}
{112}{}{You lousy bastard! Nobody could have done a better job. You'll regret stiffing me. Goodbye.}
{113}{}{That wasn't too bad at all. Here's your $1500. I don't know when we'll find someone else to run
 the caravan, but if we do you can work for us again.}
{114}{}{I don't think I ever want to spend so much time looking at the ass-end of a brahmin again. Goodbye.}
{115}{}{That wasn't too bad at all. See you later. Goodbye.}
{116}{}{That was a good run, even though you lost Stanwell. Into every life a little rain must fall.
 Here's your $100, plus $50 from Stanwell's share.}
{117}{}{Nice to find someone who appreciates quality when he sees it. See you around, maybe. Goodbye.}
{118}{}{Always glad to make some extra money. Thanks, and goodbye.}
{119}{}{If you were in the NCR, you would be kept in a nice ward and not forced to make your own way in
 the world. At least we allowed you to travel safely. Goodbye.}
{120}{}{Ook?}
{121}{}{Damn shame that Stanwell got himself killed off. My name's Nording. I'll settle the debt.}
{122}{}{Uh, thanks.}