{100}{}{You see Amanda.}
{101}{}{You see a tired-looking woman. She looks like she has been crying.}
{102}{}{You see Amanda.}
{103}{}{You see a tired-looking woman. She looks like she has been crying.}
{104}{}{You see Amanda. She is looking much happier now that Joshua is free.}
{105}{}{You see Amanda.}
{106}{}{You see Amanda. She is looking much happier now that Joshua is free.}
{107}{}{Oh, Joshua...}
{108}{}{What am I going to do?}
{109}{}{The money's all run out...}
{110}{}{If only the Citizens would let him go...}
{111}{}{Joshua, I'm so glad you're free. I was so worried...}
{112}{}{I'm sorry, I don't have any handouts to give you.}
{113}{}{Please leave me alone, or I'll call the guards.}
{114}{}{What do you want?}
{115}{}{Are you okay? You look upset.}
{116}{}{Nothing. Sorry to disturb you.}
{117}{}{I...well, I...it's my husband Joshua. He...got into some trouble in...the bar. He accidentally struck a Citizen and was arrested. He didn't mean to, but he'd been drinking, and...}
{118}{}{Arrested? Where is he now?}
{119}{}{If he was drunk and attacked someone, then he should be arrested.}
{120}{}{I'm sorry to hear that. I hope they let him go.}
{121}{}{Inside the city, in the Servant Allocation Center...they said he could work off his prison sentence as a Servant, but that'll take years!}
{122}{}{What can be done?}
{123}{}{If he was drunk and attacked someone, then he should be arrested.}
{124}{}{I'm sorry to hear that. I hope they let him go.}
{125}{}{But it was an accident! I...he didn't mean to do it!}
{126}{}{Where is he now?}
{127}{}{He didn't mean to attack someone? Sure. Maybe this'll be a good lesson for you.}
{128}{}{I'm sorry to hear that. I hope they let him go.}
{129}{}{I don't have much money left, and we'll have to leave soon if we can't afford to pay the guards for protection. They said if we want to stay with Joshua, then they could make us Servants, too...}
{130}{}{That sounds like a solution. They treat Servants pretty well in Vault City, don't they?}
{131}{}{Let me see what I can do, okay? Maybe I can talk to someone at the Allocation Center.}
{132}{}{I could help you. But it's going to cost you.}
{133}{}{I'm sorry to hear that. I hope they let him go.}
{134}{}{I don't want my son to be raised as a slave! We came to Vault City because we heard it was a free city...but we get here...and there's all these laws, and payments to the guards and...it's nothing like what we were told.}
{135}{}{Let me see what I can do, okay? Maybe I can talk to someone at the Allocation Center.}
{136}{}{I'm sorry to hear that. I hope they let him go.}
{137}{}{The man in charge is Barkus, Officer Barkus. I couldn't even get inside the city to see him. I don't even know if Joshua is all right! I...}
{138}{}{Don't worry. I'll see what I can do.}
{139}{}{But I don't have much money and...}
{140}{}{I wasn't thinking about money.}
{141}{}{Never mind. Maybe I can talk to someone at the Allocation Center.}
{142}{}{I'm sorry to hear that, then. Maybe they'll just let him go. Good-bye.}
{143}{}{What do you m...? Oh, no. I...couldn't. I mean, I...}
{144}{}{Do you want your husband free or don't you? Your husband never has to know.}
{145}{}{Never mind. Maybe I can talk to someone at the Allocation Center.}
{146}{}{I'm sorry to hear that. It looks like you're husband's never going to be free. Good-bye.}
{147}{}{If you promise to free my husband, I...I...very well. I...close the tent flap. I...think my son is still playing outside, so we won't be disturbed.}
{148}{}{Don't you worry, I'll free your husband. After I receive my payment.}
{149}{}{Forget it. Maybe I can talk to someone at the Allocation Center.}
{150}{}{Never mind. Forget we met.}
{151}{}{Hey, what about me?!}
{152}{}{Please rescue Joshua. He's inside the City in the Servant Allocation Center.}
{153}{}{Thank you for rescuing my husband! Please...accept this as a reward. It's not much, but...}
{154}{}{Thank you again for rescuing my husband. We'll be moving on soon.}
{155}{}{Uh...thanks for rescuing my husband...please don't tell him what happened between us.}