{100}{}{You see an elderly man with deep wrinkles along his face. If he notices you looking at him, he gives no sign.}
{101}{}{You see Cassidy.}
{102}{}{You see an elderly man with deep wrinkles along his face. He nods at you.}
{103}{}{Well, now. I ain't seen you around before, stranger. Name's Cassidy. I run this place. What can I do for you?}
{104}{}{Well now, if it ain't the mysterious stranger. What can I do for you today?}
{105}{}{Ug Nog?}
{106}{}{Shamble off}
{107}{}{I'm looking for the Vault.}
{108}{}{You looking to get out of here yet?}
{109}{}{What have you got on tap?}
{110}{}{Anything interesting going on around here?}
{111}{}{Nothing today, thanks.}
{112}{}{Hit on the head a little too often, eh? Sorry, I don't speak imbecile.}
{113}{}{Bee-sil?}
{114}{}{Vault? Only Vault I know of is the one inside the city. Big friggin' hole...you can't miss it, trust me.}
{115}{}{What do you have to drink here?}
{116}{}{Anything interesting going on around here?}
{117}{}{Thanks for the directions. Goodbye.}
{118}{}{Beer for $20, shot of whiskey for $30. Nothing special. Why, you want something?}
{119}{}{I'm looking for the Vault.}
{120}{}{I'll take a beer.}
{121}{}{I'll take a shot.}
{122}{}{Anything interesting going on around here?}
{123}{}{Not really. Thanks anyway.}
{124}{}{"Interesting?" Heh. Friend, Vault City ain't an "interesting" place...unless the guards get bored, then you
 better take cover. Why you asking? You looking for something in this sinkhole?}
{125}{}{What do you have to drink here?}
{126}{}{Actually, I'm looking for the Vault.}
{127}{}{It can't be that bad here.}
{128}{}{Not really. Thanks anyway.}
{129}{}{Here you go. Drink up. It might help you forget where you are.}
{130}{}{This place can't be that bad.}
{131}{}{Thanks for the drink. I have to be going.}
{132}{}{Oh, really? Well, hell then, I must be mistaken, considering YOU'RE the authority and all. Guess you must have been napping during the raid last week?}
{133}{}{Raid?}
{134}{}{Aw, yeah, a beautiful sight it was. A guard patrol broke in here looking for "illegal substances." They busted down the door, busted up my stock, then busted up a few of my customers, too.}
{135}{}{What happened after that?}
{136}{}{Sorry to hear it. I'll talk to you later.}
{137}{}{After they hauled away this one guy, Joshua, for resisting arrest, they fined my ass for finding - get this - REAL whiskey on the premises. Nevermind that I got a permit from Stark three months before. Bastards.}
{138}{}{Whoa. No kidding.}
{139}{}{Sorry to hear it. I'll talk to you later.}
{140}{}{It gets better. Now I'm in debt to the guards for the fine, an' I had to buy a new case of alcohol from a merchant at triple my standard rate. I'm expecting the guards to come knocking again soon, just to bust my chops. }
{141}{}{What's it like most of the time?}
{142}{}{Hope things look up for you in the future. See you.}
{143}{}{Even the good days ain't worth a damn. The Citizens don't drink much, so I'm stuck here pouring drinks for merchants. The next cheap sonuvabitch who haggles for a drink is going to be wearing his ass as a hat.}
{144}{}{Why are you here if you hate it so much?}
{145}{}{Sorry to hear that. I'm looking for a Vault. Can you help me out?}
{146}{}{Sorry to hear it. Hope things get better.}
{147}{}{I have a bad heart. Need cardio booster shots to keep it beating. This city's the only place to get real medical care, so I thought I'd settle here, try and make a living.}
{148}{}{You sound pretty fed up with the place.}
{149}{}{I see. Say, I'm looking for a Vault. Can you help me out?}
{150}{}{Hope things get better for you from here on. See you.}
{151}{}{Makes me want to close up shop and let this City rot. Screw 'em all.}
{152}{}{Why don't you leave?}
{153}{}{Sorry to hear it. Hope things work out for you.}
{154}{}{Go into the wastes by myself? Ha! I'm sick of this place, but I ain't stupid.}
{155}{}{I'm heading out that way again. Why don't you come along?}
{156}{}{Well, good luck to you then.}
{157}{}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{158}{}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{159}{}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{160}{}{Naw...you look like you got enough of a crowd already.}
{161}{}{All right. Well, good luck.}
{162}{}{Forget I asked then, asshole. Go back to tending bar in this shitwater burg.}
{163}{}{Nevermind then. Your loss.}
{164}{}{Heh. You serious?}
{165}{}{Sure. Why the hell not? You look like you know how to take care of yourself in a fight.}
{166}{}{On second thought, it's pretty dangerous out there, especially for someone with heart trouble. You'd be better off here.}
{167}{}{All right, count me in.}
{168}{}{Let's hit it.}
{169}{}{}
{170}{}{}
{171}{}{What's up? You got that "I need to tell you something you might not like" look again.}
{172}{}{Yeah?}
{173}{}{What's up? You got that "I'm pulling rank" look again.}
{174}{}{I wanted to ask you some questions...}
{175}{}{You look like you've taken some damage. Use some stims and heal yourself.}
{176}{}{Cassidy, I need you to wait here until I come back.}
{177}{}{Put your weapon away.}
{178}{}{Stay close to me.}
{179}{}{Don't get too far away.}
{180}{}{We should spread out a bit.}
{181}{}{C'mon, Cassidy. Time to head out.}
{182}{}{Nothing, never mind.}

{261}{}{You want me to put a bullet in Myron's head, is that it? It'd be no trouble. Just give the word.}
{262}{}{What's on your mind?}
{263}{}{Why do you want to cap Myron?}
{264}{}{What weapons are you skilled with?}
{265}{}{Actually, I had something else I wanted you to do...}
{266}{}{Actually, I had something I wanted you to do...}
{267}{}{Nevermind. Let's move on.}
{268}{}{No, don't hurt Myron. Not today, anyway. I'll keep you posted.}
{269}{}{Well, shotguns and rifles, mostly...just personal preference. I ain't a bad shot with pistols, neither.}
{270}{}{Anything else?}
{271}{}{Okay. I had some other questions...}
{272}{}{All right. Just checking.}
{273}{}{If you ever need to learn somebody some manners up close and personal, slip me some brass knuckles, and I can tapdance on their face with my fists.}
{274}{}{Great. Anything else?}
{275}{}{Okay. I had some other questions...}
{276}{}{All right. Just checking.}
{277}{}{Uh, well...just between you and me, I can also use a spear pretty good. Me and my buddies used to hunt radscorpions with spears way back when...fact I'm alive and they ain't might tell you something.}
{278}{}{Nothing wrong with using a spear.}
{279}{}{Okay. I had some other questions...}
{280}{}{All right. Just checking.}
{281}{}{Says you. Just don't be calling me no tribal, and we'll get along just fine.}
{282}{}{Don't want people mistaking me for ol' Bone-nose over there. Heh-heh. I ain't never seen no tribal do something as dumb as jam a bone in his nose.}
{283}{}{Of course there isn't. Spear's a fine weapon. Lots of tribal friends of mine use 'em.}
{284}{}{Did you know that I am a "tribal?"}
{285}{}{Hmmm. Look, I had some other questions...}
{286}{}{All right. Thanks for the rundown.}
{287}{}{Aw, don't be playing with ol' Cassidy now. You ain't no tribal.}
{288}{}{Yes, I am.}
{289}{}{Whatever. Look, I had some other questions...}
{290}{}{Forget it. I don't want to get into this with you right now.}
{291}{}{Uh, well...damn it all, you can have my apology right here and now. I didn't mean any offense.}
{292}{}{Sure you didn't. Look, I had some other questions...}
{293}{}{Forget it. Let's move on.}
{294}{}{Well, now, before you go, I got a question for you. What are we doing out here? We seem to be running all over the place looking for something. Have we got some sort of plan?}
{295}{}{We're looking for a GECK - a Garden of Eden Creation Kit. My village needs it to restore their crops.}
{296}{}{We're going to the Vault, then return the GECK to my village.}
{297}{}{My village has been kidnapped. I'm trying to find out what happened to them.}
{298}{}{Them things come in kits now, huh? Man, the good book don't mention that, does it? Well, all right then. Let's get hunting.}
{299}{}{Huh. All right then, just checking.}
{300}{}{I wouldn't mind plugging a few holes in some kidnappers. A little frontier justice never hurt anyone...well, at least not me.}
{301}{}{All right. Let's go.}
{302}{}{The things that little cuss says ain't fit for decent ears.}
{303}{}{Especially a woman's.}
{304}{}{Why, Cassidy, I didn't know you cared. My heart's all a-flutter.}
{305}{}{So? What are you saying?}
{306}{}{You know, you cuss a lot, too, Cassidy.}
{307}{}{Tell me about it. Let's get going.}
{308}{}{Yeah, but when I do it, it's got style. He's just a little trash mouth.}
{309}{}{And I don't like the way he looks at you, neither.}
{310}{}{Why, Cassidy, I didn't know you cared. My heart's all a-flutter.}
{311}{}{So? What are you saying?}
{312}{}{Tell me about it. Let's get going.}
{313}{}{Now hold on, I didn't mean it like that.}
{314}{}{All I'm saying is that bona fide little asshole's gonna get his number clocked one day when it's just me and him and a hole in the desert.}
{315}{}{Well, life can be a harsh teacher on its own. I had some other questions for you...}
{316}{}{Well, he's bound to bite it any time now anyway. I wouldn't worry about it.}
{317}{}{Just calm down, Cassidy. Leave Myron alone.}
{318}{}{I hate this place.}
{319}{}{I was hoping we'd steer clear of this place for good.}
{320}{}{City of tight-asses...}
{321}{}{This place looks worse than Vault City.}
{322}{}{Good thing I checked my weapons before I came in here.}
{323}{}{If I kick the bucket, don't bury me here.}
{324}{}{Watch yourself around here. The locals ain't too friendly.}
{325}{}{Heh. Never thought I'd see San Francisco.}
{326}{}{Never thought you'd keep an old timer like me 'round this long. Let's get this job done and go home.}
{327}{}{Redding's a mining town. Gold, mostly. A lot of caravans came to Vault City from here.}
{328}{}{Broken Hills is a mining town...mostly uranium ore. It can be a rough place, so watch yourself.}
{329}{}{I got some poison runnin' through my system. Got any antidote?}
{330}{}{I'm glowing like a neon sign over here. Got any anti-radiation drugs?}
{331}{}{I'm hurting pretty bad over here. Got any stims?}
{332}{}{You keep your nose clean, Myron. I'm watching you.}
{333}{}{Step outta line, Myron, and I'm gonna cut you.}
{334}{}{Dammit, Lenny, you need a bath. Or some disinfectant.}
{335}{}{Ghoul-boy, you better keep your damn distance. Shoooo-weee, do you stink.}
{336}{}{That's the meanest-looking dog I've ever seen.}
{337}{}{Easy, pooch. Cassidy's your friend, all right?}
{338}{}{Wonder what that cyberdog eats. Humans, probably.}
{339}{}{If that cyberdog starts humping my leg, I'm gonna put it down.}
{340}{}{Ahhhh. Boy, am I glad they made millions of these things before the bomb dropped.}
{341}{}{Thanks, friend.}
{342}{}{Hope takin' these stims don't hurt my heart none...}
{343}{}{What th--?! No, my heart! I...*hrrrkkk*}
{344}{}{Sorry, I was just admirin' the view.}
{345}{}{Hell, I'll just stand over here, then.}
{346}{}{My apologies, friend. Didn't mean to block your way.}
{347}{}{Ahhhhh. That hit the spot. Thank you kindly.}
{348}{}{*Hic* Heh-heh. Nothing like some good ol' firewater to get the blood pumping.}
{349}{}{Thanks. Hell, you should take a swig, too.}
{350}{}{That's the Vault. Big friggin' thing, innit?}
{351}{}{You want me to join you again?}
{352}{}{I'm good to go whenever you are.}
{353}{}{Sure you don't need my help?}
{354}{}{I'm itching to get going.}
{355}{}{Sure could go for a smoke.}
{356}{}{Dad named me after some comic book character from before the war. Said he was a mean sonuvabitch, too.}
{357}{}{It's good to be traveling again. Living in Vault City was giving me an ulcer.}
{358}{}{Hope my heart doesn't act up while we're travelling...}
{359}{}{Sure could use a drink.}
{360}{}{Better check my gear again.}
{361}{}{Goddamn arthritis...}
{362}{}{If I was twenty years younger, I'd go east and explore the Midwest. Too late now, I s'pose.}
{363}{}{I hear they got twisters miles wide in the Midwest. It's a big ol' radioactive dustbowl now.}
{364}{}{Wonder if Texas survived the war...}
{365}{}{Thanks, friend. I...whoa. Now my vision's getting all cloudy.}
{366}{}{I heard this stuff makes you hallucin...whoa! Where the hell did all these snakes come from?!}
{367}{}{Whenever I take this stuff, I have flashbacks.}
{368}{}{Nothing like a little backwater tribal healing...}
{369}{}{I'm about due for some crutches and a wheelchair over here.}
{370}{}{Cassidy dies of a heart attack.}
{371}{}{You have convinced Cassidy to join your party.}
{372}{}{Just let me pop a heart pill first...} # Seraph's Code

{1000}{}{Well...all right, then. I'll wait here 'til you get back. }
{1100}{}{Sure. Can't promise I won't pull it out again if there's trouble, though.}
{1200}{}{All right, I'll stick close to you then. You must be expecting trouble.}
{1300}{}{All right, I'll keep some distance. Get a better vantage point that way.}
{1400}{}{All right, I'll be watching your back. You need me, holler, and I'll come running.}

{2000}{}{No offense or nothin', but you don't look too capable of leading anybody. It looks like the wastes would have you for dinner.}
{2100}{}{Naw, I don't travel with slavers. They have a nasty habit o' selling you when they get low on cash. No offense.}
{2200}{}{Naw, you have the look of somebody with one foot in the grave and the other in hell. I don't think I need to stain my reputation any more than it is.}
{2300}{}{Naw... you look like you got enough of a crowd already.}
{2400}{}{All right, then.}

{2999}{}{All right. Take care, then.}
{3000}{}{Let's head out.}
{3100}{}{Forget I asked then, asshole.}
{3200}{}{Never mind, then. Your loss.}

{4100}{}{Okay, everything's stitched up. I'm good to go.}
{4200}{}{Okay, pretty much everything is patched up.}
{4300}{}{That pretty much did it, but I could use a couple more stims.}
{4400}{}{I used what I could, but I'm still pretty messed up. If you got any more stims to spare, I could sure use 'em. I can still walk, though.}

{9999}{}{I wanted to ask you some questions...}
{10001}{}{Take some more stims and heal yourself.}
{10002}{}{Cassidy, I need you to wait here until I come back.}
{10003}{}{Put your weapon away.}
{10004}{}{Stay close to me.}
{10005}{}{Don't get too far away.}
{10006}{}{We should spread out a bit.}
{10100}{}{C'mon, Cassidy. Time to head out.}
{10007}{}{Let's head out then.}

# NEW TOM PARTY MEMBER ADDITIONS

# NODE 1007 WE NEED TO CHANGE DISTANCE
{20000}{}{All right, I'm listening.}

# NODE 1008 TALK ABOUT GEAR
{20001}{}{My gear? What about it?}

# NODE 1009 REMOVE ARMOR
{20002}{}{No problem. Too hot for that kinda gear, anyway. Makes me sweat like a New Reno whore.}

# NODE 1010 WHAT WEAPONS CAN YOU USE -- DAN NEEDS TO REPLACE THIS.

# NODE 1100 CAN'T JOIN PARTY BECAUSE LOW CHR -- DAN NEEDS TO REPLACE THIS.

# We need to change our distance from one another
{20003}{}{Let's try a different formation.}
# I need to talk to you about your gear.
{20004}{}{I need to talk to you about your gear.}
# On second thought, I think this distance is OK for now.
{20005}{}{Forget it. Let's stick to the formation we have now.}
# Actually, I guess there's nothing I need to really know right about your gear.
{20006}{}{Never mind. There's nothing I need to know about your gear.}
# I need to remove the armor that you're wearing.
{20007}{}{I need you to remove that armor you're wearing.}
# I need to know what kind of weapons you can use. Transplant original comment from Question Node Line: 264
