{100}{}{This terminal is displaying a series of glowing green bars that rise and fall irregularly.}
{101}{}{You see a Vault City medical terminal. }
{102}{}{This terminal is displaying a series of glowing green bars that rise and fall irregularly.}
{103}{}{You could glean more information from this terminal with a more scientific approach.}
{104}{}{You can't seem to figure out how this terminal works.}
{105}{}{Damn computers.}
{106}{}{You can't seem to figure out how this terminal works.}
{107}{}{Dumm cum-poo-terz}
{108}{}{You have logged into the Vault City Medical Database. Although the interface is difficult to
 understand, the database itself seems to be broken down into a series of archives.}
{109}{}{Search the archives for the location of Vaults.}
{110}{}{Search archives for any mention of the Garden of Eden Creation Kit.}
{111}{}{Search the medical database for anything of interest.}
{112}{}{Log off the terminal.}
{113}{}{You don't find any mention of Vaults in the database. It's mostly medical information relating
 to anatomy, known diseases, treatments, drugs, and implants.}
{114}{}{Search the archives for any mention of the Garden of Eden Creation Kit.}
{115}{}{Search the medical database for anything of interest.}
{116}{}{Log off the terminal.}
{117}{}{You don't find any mention of the GECK in the database. It's mostly medical archives relating to
 anatomy, known diseases, treatments, drugs, and implants.}
{118}{}{Search the archives for any mention of the Vaults.}
{119}{}{Search the medical database for anything of interest.}
{120}{}{Log off the terminal.}
{121}{}{You search the database, but the medical terminology is too cryptic to understand. If you knew
 more about the medical profession, it might not be a problem.}
{122}{}{Continue to search the computer archives.}
{123}{}{Log off the terminal.}
{124}{}{You search the database and are amazed by the information contained in the archives. The current
 research being conducted in Vault City is fascinating, and their medical technology is beyond anything you
 have ever seen.}
{125}{}{You search the database again but discover nothing new. The implant schematics were the most
 useful information in the archives. It's possible you missed something, but you think that's unlikely.}
{126}{}{You search the database... again... but discover nothing new. Maybe if you searched twenty
 more times, you might find something new.}
{127}{}{We were just kidding. There really is nothing more here. Maybe if you scoured the archives
 thirty more times, you might find something buried deep in one of the archives. Ha-ha.}
{128}{}{Uh... look. Go play the rest of the game. You can't stay cooped up in here forever.}
{129}{}{Fine. Keep looking. See if I care.}
{130}{}{You're just wasting your time.}
{131}{}{Your intelligence is 4, right?}
{132}{}{Cut it out.}
{133}{}{Why don't you go play with the nurse?}
{134}{}{There's nothing here!}
{135}{}{You search the archives and find nothing.}
{136}{}{You have searched this terminal 53 times. You have found nothing else of interest.}
{137}{}{Just had to do it one more time, didn't you? Sheesh.}
{138}{}{Okay, look. Here's the big secret. Be sure to go visit the main computer on level three after
 you finish the game. Now log off the terminal and go play outside.}
{139}{}{You search the archives and find nothing.}
{140}{}{Continue to search the archives.}
{141}{}{Search the database again to make sure you didn't miss anything.}
{142}{}{Continue to search the archives.}
{143}{}{Log off the terminal.}
{144}{}{You spend almost an hour studying the archives. As you delve deeper into the database, you come
 across a series of older archives that contain schematics for some sort of "combat implants."}
{145}{}{Study the implant information.}
{146}{}{The schematics detail an operation for grafting impact plates and thermal-dissipating membranes
 to a human skeleton, granting the subject resistance to physical trauma and heat. It looks like a
 complicated procedure.}
{147}{}{Make a note of it, then search the database for more information.}
{148}{}{Record the information, then log off the terminal.}
{149}{}{You have returned to the main menu. A series of archives and search programs are listed on the
 terminal screen.}
{150}{}{Search for any mention of Vault 13 in the archives.}
{151}{}{Search for any references to the Garden of Eden Creation Kit.}
{152}{}{Search the medical database for anything of interest.}
{153}{}{Log off the terminal.}
{200}{}{You finished studying the Vault City medical database.}
{201}{}{Your friend tries to interest you in the colored window box that goes BEEP BEEP, but you can't seem to figure out how to open it, so you eventually get bored and leave it alone.}
{202}{}{Wander off.}
{203}{}{*Beep*}
{204}{}{*Beeee-oop*}
{205}{}{*Dweeee-oop*}
{206}{}{*Bee-Oop*}
{207}{}{*Beep*}
{208}{}{PING!}
{209}{}{I'm sorry, Dave. I can't do that.}
{210}{}{Danger! Will Robinson!}
{211}{}{Thirty seconds to reach minimum safe distance.}
{212}{}{PING! I Say!}
{213}{}{Please remove your card to receive cash.}
{214}{}{Strange game. The only winning move is not to play.}