{100}{}{Armi leggere}
{101}{}{Armi pesanti}
{102}{}{Armi a energia}
{103}{}{Disarmato}
{104}{}{Armi da mischia}
{105}{}{Lanciare}
{106}{}{Pronto Soccorso}
{107}{}{Dottore}
{108}{}{Movimento Furtivo}
{109}{}{Scassinare}
{110}{}{Rubare}
{111}{}{Trappole}
{112}{}{Scienza}
{113}{}{Riparare}
{114}{}{Dialogare}
{115}{}{Barattare}
{116}{}{Gioco d'Azzardo}
{117}{}{Escursionista}
{200}{}{L'uso, la cura e la conoscenza generale di piccole armi da fuoco - pistole, mitragliette e fucili.}
{201}{}{L'utilizzo e la manutenzione di grosse armi - mitragliatrici, lanciarazzi, lanciafiamme e affini.}
{202}{}{La cura e l'alimentazione di armi a energia. Come caricare e usare armi che utilizzano la tecnologia laser o al plasma.}
{203}{}{Una combinazione di arti marziali, pugilato e altre tecniche di combattimento a mani nude.  Combattimento con pugni e calci.}
{204}{}{L'utilizzo di armi da mischia in un combattimento corpo a corpo - coltelli, martelli da guerra, lance, bastoni e cosi' via.}
{205}{}{L'abilita' di utilizzare armi da distanza a "propellente muscolare", come coltelli da lancio, lance e granate.}
{206}{}{Abilita' generica di cura.  Usata per curare piccoli tagli, abrasioni e altri piccoli malanni. In termini di gioco, l'uso del pronto soccorso puo' curare, nel tempo, piu' Punti Vita rispetto al semplice riposo.}
{207}{}{La cura di ferite gravi e arti menomati. Senza questa abilita', ci vorra' molto piu' tempo per recuperare l'uso di arti feriti.}
{208}{}{Movimento silenzioso e abilita' di passare inosservati. Se effettuato con successo, sara' molto piu' difficile localizzarti. Non si puo' correre e usare Movimento Furtivo allo stesso tempo.}
{209}{}{L'abilita' di aprire serrature senza l'apposita chiave. L'uso di un set da scassinatore o di un grimaldello elettronico migliorera' di molto questa abilita'.}
{210}{}{L'abilita' di fare tue le cose degli altri. Puo' essere usata per rubare da persone o luoghi.}
{211}{}{La ricerca e la rimozione di trappole. Comprende anche l'attivazione di esplosivi per scopi di demolizione.}
{212}{}{Comprende una gran quantita' di abilita' legate alla tecnologia, come l'informatica, la biologia, la fisica e la geologia.}
{213}{}{L'applicazione pratica dell'abilita' Scienza per riparare equipaggiamenti, macchinari e strumenti elettronici danneggiati.}
{214}{}{L'abilita' di comunicare in maniera pratica ed efficace. L'abilita' di convincere il prossimo che si e' nel giusto. L'abilita' di mentire senza esser scoperti.}
{215}{}{Compiti direttamente o indirettamente legati al commercio. L'abilita' di avere prezzi piu' alti per gli oggetti venduti, e prezzi piu' bassi per gli oggetti comprati.}
{216}{}{La conoscenza e le abilita' pratiche legate al gioco d'azzardo. La bravura con le carte, i dadi e altri giochi.}
{217}{}{Conoscenza pratica delle zone all'aperto e l'abilita' di vivere lontano dalla civilta'. La conoscenza di piante e animali.}
{300}{}{+ (4 x AG)}
{301}{}{+ (2 x AG)}
{302}{}{+ (2 x AG)}
{303}{}{+ (2 x (AG + FZ))}
{304}{}{+ (2 x (AG + FZ))}
{305}{}{+ (4 x AG)}
{306}{}{+ (2 x (PE + IN))}
{307}{}{+ (PE + IN)}
{308}{}{+ (3 x AG)}
{309}{}{+ (PE + AG)}
{310}{}{+ (3 x AG)}
{311}{}{+ (PE + AG)}
{312}{}{+ (4 x IN)}
{313}{}{+ (3 x IN)}
{314}{}{+ (5 x CR)}
{315}{}{+ (4 x CR)}
{316}{}{+ (5 x FT)}
{317}{}{+ (2 x (RE + IN))}
{500}{}{Curi %d Punti Vita.}
{501}{}{Sei gia' in piena salute.}
{502}{}{%s e' gia' a posto.}
{503}{}{Hai fallito nell'effettuare una qualsiasi cura.}
{505}{}{Guadagni %d PX per aver affinato la tua abilita'.}
{510}{}{\nskill_use: invalid skill used.}
{512}{}{Non puoi curare i morti.}
{513}{}{Lascia in pace i morti.}
{514}{}{E' morto, rassegnati.}
{520}{}{Ti sei curato %s.}
{521}{}{Hai curato %s.}
{525}{}{Non sei riuscito a curarti %s.}
{526}{}{Non sei riuscito a curare %s.}
{530}{}{l'occhio ferito}
{531}{}{il braccio sx menomato}
{532}{}{il braccio dx menomato}
{533}{}{la gamba dx menomata}
{534}{}{la gamba sx menomata}
{550}{}{Non sei riuscito a scassinare la serratura.}
{551}{}{Non sei riuscito a trovare trappole.}
{552}{}{Non sei riuscito ad imparare.}
{553}{}{Non puoi ripararlo.}
{570}{}{Sei stato beccato a rubare %s.}
{571}{}{Hai rubato %s.}
{572}{}{Sei stato beccato a sgraffignare %s.}
{573}{}{Hai sgraffignato %s.}
{590}{}{Hai sfruttato a fondo la tua abilita'. Aspetta un attimo.}
{591}{}{Sei troppo stanco.}
{592}{}{Lo sforzo potrebbe ucciderti.}
{600}{}{Non sei abbastanza abile per curare menomazioni agli arti.}
{601}{}{L'unita' robotica e' irreparabilmente danneggiata.}
{1000}{}{Lascia che ti aiuti.}
{1001}{}{Posso farlo.}
{1002}{}{Capito.}
{1003}{}{Felice di essere d'aiuto.}
{1004}{}{Okay.}
{1005}{}{Ci provero'.}
{1100}{}{Se hai problemi, dimmelo pure.}
{1101}{}{Capito?}
{1102}{}{Se e' questo che vuoi...}
{1103}{}{Va' avanti e provaci.}
{1104}{}{Prego, dopo di te.}
