{100}{}{You see an old mutant.}
{101}{}{You see an old mutant, a resident of Broken Hills.}
{102}{}{On closer examination, you see an aging mutant. The strength in the mutant’s muscles is still
 apparent, as is the defensive pride with which it carries itself.}

{103}{}{I think… that… the radon gas keeps the miners young.}
{104}{}{I’m losing my memories… it all comes back to me… wait…}
{105}{}{Have you heard that the humans are plotting to kill us?}
{106}{}{I wish we were more accepted by the humans. We’re human in our own way.}
{107}{}{How goes the world outside? I don’t hear much these days.}
{108}{}{Someone said the FEV that made us is making us senile.}
{109}{}{It all seems to be slipping away from me. I used to be strong and quick... now I am little more
 than a human, it seems.}
{110}{}{What does life matter when it all ends anyway?}

{132}{}{Who let those dogs out? I’ll crush them!}
{133}{}{Franc and Manson better stay in hiding… I’ll crush their skulls barehanded if I catch them.}
{134}{}{Franc. Manson. Scum o’ the earth.}
{135}{}{Little fuckwads are free to kill again, eh?}
{136}{}{We ought to get a search party going on those two.}
{137}{}{I ain’t gonna sleep easy ‘til those freaks are dead.}
{138}{}{There goes any thought of security.}
{139}{}{Well… ummm… who were you?}

{140}{}{Franc and Manson will behave? That’s a promise made in Stockton if I ever heard one.}
{141}{}{We’ll not be thanking you if those two shitheads cause more trouble, y’know.}
{142}{}{All right… I’m willing to give those two wankers a chance…}
{143}{}{How do I get home?}
{144}{}{Didn’t I just talk to you?}
{145}{}{I ain’t gonna sleep easy ‘til those freaks are dead.}
{146}{}{There goes any thought of security.}
{147}{}{Well… ummm… who were you?}

{148}{}{I knew it! I knew those gobs of shit had it in for us!}
{149}{}{I never did trust that Jacob bastard.}
{150}{}{So… humans try to kill us. Maybe we kill them instead.}
{151}{}{Ain’t all the humans’re doin’ this, right?}
{152}{}{Well, well, well… more human trickery?}
{153}{}{I lose more every day… my memories and my faith in humanity went today.}
{154}{}{You’re a good one, you are.}

{162}{}{Francis is impressed. So am I.}
{163}{}{How can a human beat a mutant arm-wrestling? Did you cheat?}
{164}{}{So how are you going to use your new prize?}
{165}{}{Strong. Very strong.}

{166}{}{Once you’ve known a mutie, you never go back.}
{167}{}{I hear you were nice and- yeah... for Francis.}
{168}{}{I’m surprised you’re even walking.}
{169}{}{Heh… Francis may be old, but he’s still got it!}

{170}{}{Those poor people.}
{171}{}{Being trapped underneath the ground…}
{172}{}{I said then, I said, "Jacob and Aileen are trouble. So’re Franc and Manson." But would anyone
 listen? Noooooo.}
{173}{}{Tunnels, eh? I always knew those bastards were rats and worms.}
{174}{}{So those bodies are what that stench was, huh?}

{175}{}{Why do you hurt us?}
{176}{}{Humans never trust me.}
{177}{}{Leave me alone.}
{178}{}{Why don’t you die already?}
{179}{}{Why is it that humans always crush what they fear?}
{180}{}{You are scum.}
{181}{}{Your life is worthless.}
{182}{}{You… I remember a person like you…}
{183}{}{I’m too old even to hate you.}