#############################################################
#  Message File: Klacanyn.msg                               #
#                                                           #
#  Created: August 18, 1998                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for the map script in describing #
#  what is happening when you first enter the map.          #
#############################################################

{100}{}{You have entered a canyon near Klamath.}