{100}{}{Vedi Jordan che fa roteare la sua lancia, come al solito.}
{101}{}{Vedi Jordan che fa roteare la sua lancia, come al solito.}
{102}{}{Buona fortuna!  Devo tornare ad allenarmi.}
{103}{}{Salve, Prescelto. Vedo che hai bisogno di un po' di allenamento. Posso aiutarti?}
{104}{}{Bene.}
{105}{}{No, Grazie.}
{106}{}{Ci servira' solo un po' di tempo.}
{107}{}{Ecco: hai imparato quello che potevo insegnarti a proposito del combattimento con le lance.}
{108}{}{Grazie, Jordan, i tuoi insegnamenti mi saranno di grande aiuto.}
