{100}{}{Vedi una Pianta dall'Essenza Oscura.}
{101}{}{These plants aren't just harmful to the garden. They also have the ability to attack humans
 and other creatures.}
{102}{}{Queste Piante dall'Essenza Oscura rappresentano uno strano esempio di mutazione. Non e' sicuro che siano mutate in questo modo per cause naturali.}
{103}{}{Non noti niente di particolare in queste piante - a parte il fatto che sono in grado di attaccare gli umani.}
{150}{}{Hai liberato il giardino da tutte le Piante dall'Essenza Oscura.}
