{100}{}{Vedi una donna di mezz'eta'.}
{101}{}{Vedi Rebecca.}
{102}{}{Vedi una donna di mezz'eta'. Pare abbia vissuto una vita di stenti; tuttavia conserva gran parte della bellezza che aveva in gioventu'.}
{103}{}{Ciao, mi chiamo Rebecca. Possiamo parlare in privato, per favore?}
{104}{}{Cosa parlare?}
{105}{}{Perche' bisogno parlare privato?}
{106}{}{Okay.}
{107}{}{No. Me va via.}
{108}{}{Scusa, non mi interessa.}
{109}{}{Di cosa vuoi parlarmi?}
{110}{}{Certo; dove possiamo andare per avere un po' di privacy?}
{111}{}{Perche' non vuoi che qualcuno ci senta?}
{112}{}{(sussurrando) Mia figlia e' scomparsa e mi serve aiuto per ritrovarla. Non posso parlarne qui. Possiamo andare in un posto piu' appartato?}
{113}{}{Okay.}
{114}{}{Perche' bisogno parlare privato?}
{115}{}{No, me va.}
{116}{}{D'accordo, andiamo.}
{117}{}{Perche' non vuoi che qualcuno ci senta?}
{118}{}{No grazie, non voglio essere coinvolto.}
{119}{}{(sussurrando) Forse penserai che io sia pazza, ma ho la sensazione di essere osservata in ogni momento. E' abbastanza preoccupante e mi rende un po' nervosa.}
{120}{}{Okay, noi andare privato.}
{121}{}{No tempo per malati in testa.}
{122}{}{D'accordo; dove possiamo andare?}
{123}{}{Scusami, ma non mi piace questa storia.}
{124}{}{Grazie; possiamo andare nella mia tenda.}
{125}{}{Okay.}
{126}{}{Qui dovremmo poter parlare.}
{127}{}{Okay, che problema?}
{128}{}{Me ha domande prima.}
{129}{}{Okay. Allora: cosa volevi dirmi di cosi' importante?}
{130}{}{Prima vorrei farti delle domande.}
{131}{}{Ho una figlia di nome Chrissy. La si potrebbe definire un "maschiaccio". Le piace andare in giro, esplorare e ficcare il naso un po' dappertutto. Ma Chrissy e' comunque una brava ragazza. Non combina guai, torna sempre a casa in orario e si e' dimostrata una signorina molto responsabile. Le lascio fare quasi sempre quello che vuole. La settimana scorsa Chrissy non e' tornata a casa. Ho chiesto in giro, ma nessuno sembra averla vista ne' sentita. Ho provato a cercarla da sola, ma Zeke - lui e' una sorta di... sindaco - mi ha fermato. Ha detto che non era sicuro per me andare a cercarla da sola e che avrebbe mandato alcuni dei suoi uomini. Ma nemmeno loro sono riusciti a trovarla e mi hanno detto che forse e' stata catturata dagli schiavisti.}
{132}{}{No, non vuole me coinvolto.}
{133}{}{Bisogna che pensa prima decidere.}
{134}{}{Ok, me sembra eroe da qualche giorno.}
{135}{}{Scusa, non mi interessa.}
{136}{}{Devo pensarci su.}
{137}{}{D'accordo, Rebecca. Cerchero' di aiutarti.}
{138}{}{Se ti aiuto, cosa avro' in cambio?}
{139}{}{Cosa vuoi sapere?}
{140}{}{Cosa succedere qui?}
{141}{}{Chi capo?}
{142}{}{Me cerca trovare Vault 13. Tu sapere dove essere?}
{143}{}{Parlare di Vault.}
{144}{}{Parlare di Darion.}
{145}{}{Grazie. Noi parla tuo problema?}
{146}{}{Cosa succede da queste parti?}
{147}{}{Chi e' che comanda qui?}
{148}{}{Sto cercando il Vault 13. Ne sai qualcosa?}
{149}{}{Parlami del vault.}
{150}{}{Allora... parlami di Darion.}
{151}{}{Grazie, Rebecca. Adesso parliamo del tuo problema.}
{152}{}{Noi chiamiamo questo posto 'Squat' perche' e abitato dai senzatetto di molte citta'. Non e' molto, ma e' tutto cio' che abbiamo. A ovest c'e' una citta' chiamata NCR. Il governo di quella citta' e' a conoscenza della nostra situazione ormai da diverso tempo, ma non ci ha mai fornito alcun tipo di aiuto o assistenza. Ultimamente hanno cominciato a rivendicare questa zona come la loro antica dimora e la rivogliono indietro.}
{153}{}{Okay.}
{154}{}{Cosa qui loro volere?}
{155}{}{Capisco.}
{156}{}{Cosa c'e' qui che desiderano cosi' tanto?}
{157}{}{Beh... qui c'e' un vault; credo sia il numero 15. Vogliono ripulirlo di tutte le antiche tecnologie che possono ancora trovarsi la' dentro.}
{158}{}{Ah. Me capisce.}
{159}{}{Sapevo che qui ci doveva essere qualcosa, oltre a questo gruppo di straccioni.}
{160}{}{Capito.}
{161}{}{Questo spiega molte cose. Sei stata di grande aiuto. Devo farti delle altre domande, pero'.}
{162}{}{Si tratta di Zeke. E' lui a capo di tutto, qui. Puoi trovarlo nell'edificio laggiu'. ::indica nord-est::}
{163}{}{Grazie. Chiede ancora.}
{164}{}{Grazie. Devo farti delle altre domande.}
{165}{}{Mi spiace, non ne ho idea. Forse a NCR sanno qualcosa. Laggiu' hanno un grande interesse per i vault, ultimamente.}
{166}{}{Okay, me fa.}
{167}{}{Andro' la', allora.}
{168}{}{Beh... non dovremmo parlarne, ma dato che mi serve il tuo aiuto... in questo momento Darion sta riparando il vault. E' il nostro benefattore. Quando il vault sara' completamente funzionante, noi tutti potremo spostarci al suo interno dove saremo al sicuro da predoni, schiavisti e gente simile. Per adesso ha riparato solamente i sistemi di erogazione di cibo e acqua, ma ci siamo quasi.}
{169}{}{Me vede. Bisogna sapere di piu'.}
{170}{}{Devo saperne di piu'.}
{171}{}{Non c'e' molto da dire, davvero. Darion non si fa mai vedere e non lascia mai il vault. Se ha qualcosa da dire, lo dice per bocca di Zeke. Io l'ho incontrato solo una volta e mi e' sembrato un tipo a posto.}
{172}{}{Okay.}
{173}{}{I tipi a posto non durano a lungo. Mi piacerebbe sapere qual e' il suo scopo.}
{174}{}{Capisco.}
{175}{}{Okay. Sei di grande aiuto.}
{176}{}{Non ho niente da darti se non la mia infinita gratitudine.}
{177}{}{E' piu' che sufficiente. Ti aiutero'.}
{178}{}{Dovrai farmi un'offerta migliore, se vuoi il mio aiuto.}
{179}{}{Crepi l'avarizia: ti aiutero'.}
{180}{}{Grazie mille. Non saro' mai in grado di ripagarti per questo. Ti aspettero' qui finche' non mi avrai riportato... Ehi, c'era qualcuno la' fuori che ci stava ascoltando! Ho visto la sua ombra sulla parete della tenda. E' appena andato da quella parte! :: indica nord-est:: Deve aver sentito tutto!}
{181}{}{Me ferma, no andare via!}
{182}{}{Tu no preoccupare, me trova ragazza.}
{183}{}{Ooops.}
{184}{}{Cerchero' di fermarlo.}
{185}{}{Non mi impediranno di trovare tua figlia.}
{186}{}{Oh, beh. Capita.}
{187}{}{Per favore, vattene.}
{188}{}{Ci hai pensato?}
{189}{}{Me chiede domande.}
{190}{}{No, ancora pensa.}
{191}{}{No, sto ancora valutando tutte le possibilita'.}
{192}{}{Vorrei farti delle domande.}
{193}{}{Hai cambiato idea? Mi aiuterai?}
{194}{}{No, mi spiace.}
{195}{}{Me aiuta.}
{196}{}{Si', ti aiutero'.}
{197}{}{Tu devi essere la persona che ha salvato mia figlia. Non ti potro' mai ripagare per la tua gentilezza. Grazie. Per favore aspetta qui: devo parlare con Chrissy e poi vorrei parlare con te.}
{198}{}{Hai salvato mia figlia. Non ti potro' mai ripagare per la tua gentilezza. Grazie. Per favore aspetta qui: devo parlare con Chrissy e poi vorrei parlare con te.}
{199}{}{Okay.}
{200}{}{Mia figlia mi ha detto tutto. Faccio fatica a credere che Darion sia un tale mostro, dopo tutto quello che ha fatto per noi. E pensare che lo stavamo aiutando a nascondere le sue malefatte! Ti garantisco che non lo aiuteremo un secondo di piu'. Ho gia' parlato con Zeke e vuole vederti. Dovresti andare da lui.}
{201}{}{Faccio fatica a credere che Darion sia un tale mostro, dopo tutto quello che ha fatto per noi. E pensare che lo stavamo aiutando a nascondere le sue malefatte! Ti garantisco che non lo aiuteremo un secondo di piu'. Andro' a parlare con Zeke e gli spieghero' ogni cosa. Sono sicura che vorra' vederti. Dovresti andare a parlare con lui, piu' tardi.}
{202}{}{Grazie.}
{203}{}{Spero tu riesca a trovare presto Chrissy.}
{204}{}{Me cerca.}
{205}{}{Continuero' a cercarla.}
{206}{}{Grazie per tutto quello che hai fatto per me.}
{207}{}{Non saprei dirti il motivo, ma io non credo che gli schiavisti l'abbiano catturata. Ho la strana sensazione
 che qualcos'altro stia succedendo. E poi c'e' questa sensazione di essere seguita. Ce l'ho da
 quando ho parlato con Zeke a proposito di Chrissy. Ho bisogno che qualcuno mi aiuti a trovare mia figlia,
 mi aiuterai? Ti prego.}
{208}{}{Continuano a mandare gente nel tentativo di scacciarci con le buone dalla nostra casa, ma non riescono a capire che non abbiamo un altro posto dove andare. Se ce ne andassimo da qui non saremmo in grado di sopravvivere.}
{209}{}{Sai, una cosa mi lascia perplessa: sono riusciti a riparare alcune cose, ma non le luci. Quel dannato posto e' illuminato esclusivamente da torce. Ad ogni modo, Darion non vuole che qualcuno sappia cosa sta succedendo nel vault. Teme che qualcuno potrebbe portarcelo via, se lo scoprissero. Per questo motivo ci ha detto di mandare via chiunque si faccia vivo - soprattutto se proveniente da NCR.}
