{100}{}{Vedi il terminale di un computer.}
{101}{}{Vedi il terminale del computer-biblioteca.}
{102}{}{Vedi un comune terminale di computer. Sembra funzionante e pronto a ricevere input.}
{103}{}{Accedi al computer e rapidamente passi in rassegna tutti i file disponibili. Trovi la posizione del Vault 13 e la ricopi nel tuo PIP-Boy.}
{104}{}{Hai delle difficolta' nell'accedere ai file.}
{106}{}{Oltre alla posizione del Vault 13, il computer non contiene altre informazioni utili.}
