{100}{}{Vedi un cliente dell'Hole.}
{150}{}{Questo tizio non e' certo un adone.}
{151}{}{Questo tipo ha solo un dente.}
{152}{}{[PARLA]}
{153}{}{Tua moglie e' davvero carina!}
{154}{}{Sta' lontano da noi.}
{155}{}{Ti piace, eh?}
{156}{}{Si', e' vero.}
{157}{}{Ci'.}
{158}{}{Vorrei tanto scoparmela.}
{159}{}{Fa' pure.}
{160}{}{OK. Sono 50$.}
{161}{}{Va bene, ma ti costera' 200$.}
{162}{}{Scordatelo! Sta' lontano da noi!}
{163}{}{OK.}
{164}{}{No.}
{165}{}{Perfetto! Adesso vieni con Billy, dolcezza.}
{166}{}{Adesso vattene.}
{167}{}{Grazie. Ciao.}
{168}{}{Addio.}
{169}{}{Aw, cavoli.}
{170}{}{[FATTO]}
{171}{}{Sono completamente sfinito.}
{172}{}{Tornero'.}
{173}{}{OK.}
{174}{}{Sei davvero carina.}
{175}{}{Sta' lontano da me.}
{176}{}{Dammi 200$ e potrai passare un po' di tempo con me.}
{177}{}{Costo 50$, Mac.}
{178}{}{Ih ih ih. Grazie.}
{179}{}{Non ho abbastanza soldi.}
{180}{}{Ok, 50$ allora.}
{181}{}{Peggio per te.}
{182}{}{Ci si vede.}
{183}{}{Non importunarmi. Sono alla ricerca di pollastrelle attraenti.}
{184}{}{Buona fortuna. Ti servira'.}
{185}{}{E io che sono, fegato macinato?}
{186}{}{Addio.}
{187}{}{Oooh. OK. Addio.}
{188}{}{[ti guarda dall'alto in basso] No. Il fegato macinato mi piace.}
{189}{}{Non voglio niente da te!}
{190}{}{Scusami, devo andare.}
{191}{}{Che peccato. Pensavo fossi carina.}
{203}{}{Voglio indietro i miei soldi.}
{204}{}{Non ti daro' nient'altro che un proiettile in testa.}
{205}{}{OK, ecco a te.}
{206}{}{Ehi.}
{207}{}{Oh suvvia, da' a }
{208}{}{ un'altra possibilita'.}
{209}{}{Vedo che non hai voglia di parlare con me. Me ne vado.}
{210}{}{Ti ho dato una possibilita' e tu l'hai sprecata.}
{211}{}{OK, ma ti chiedo solo un'altra possibilita'.}
{212}{}{Cosi' mi piaci.}
{213}{}{Mi tocchera' ucciderti, allora.}
{220}{}{Ehi, Frankie, prendo in prestito la stanza sul retro per un po'.}
{221}{}{Ehi, Frankie, guarda chi ho conquistato.}
{222}{}{Ehm, Frankie, se qualcuno... ehm... mi cerca, digli che torno presto.}
{223}{}{Seguimi.}
{224}{}{Dovrai aspettare. Parlero' con te piu' tardi.}
{225}{}{Non li ho.}
{300}{}{Cazzo, sono totalmente a pezzi.}
{301}{}{Wahoo.}
{302}{}{E' stato... e' stato... WOW!!!}
{303}{}{Mai vista una tipa piu' bollente.}
{304}{}{Cazzo, mi si sono rizzati tutti i capelli - beh, quei pochi che mi rimangono, almeno.}
{305}{}{Di sicuro e' meglio di un giro con Dave.}
{320}{}{Non male... Non male...}
{321}{}{Potrei anche pagare per rifarlo.}
{322}{}{Mmmm...}
{323}{}{Non male, non male.}
{324}{}{Dovremo rifarlo ancora e lavorare sulla... flessibilita'.}
{350}{}{Sembra proprio che dovro' tornare in modalita' Manuale.}
{351}{}{Sta' attenta che la porta non sbatta sul tuo CULO BASSO quando esci di qui!}
{352}{}{E' ora di finire quello che non sei nemmeno riuscita a cominciare!}
{370}{}{Oh, che bello.}
{371}{}{Billy adora queste cose.}
{372}{}{Ohhhh yeah.}
{373}{}{Bello.}
{374}{}{Jeezus e ramona.}
{375}{}{Santi Numi.}
{376}{}{Avrei dovuto portare qualche fazzoletto di carta.}
{377}{}{Hmmm, a chi potrei pensare adesso?}
{390}{}{Ehi, non vedi che sono occupato?}
{391}{}{Ehi, ehi, vattene al diavolo.}
{392}{}{Ehi, non sei riuscita a finire il lavoro, percio' vedi di andartene.}
{393}{}{Puoi andare a prendermi uno straccio e tornare in 5 minuti?}
{400}{}{Billy, sara' meglio che tu non faccia altri disastri su quel materasso!}
{401}{}{Ehi, Billy, ti serve uno straccio?}
{402}{}{Billy, hai la patta aperta. DI NUOVO!}
{403}{}{Ehi, Billy, dopo non scordarti di cambiare i pantaloni.}
{404}{}{Billy, hai mangiato delle ciambelle?}
{410}{}{Uhhh.}
{411}{}{Shucks}
{412}{}{Jeesh}
{413}{}{Eh, eh, eeeh...}
{414}{}{Eh?}
{500}{}{*SPUT, SPUT* Eccchhhh...}
{510}{}{Ehi, amico, che ne diresti di "noleggiarmi" la tua bella?}
{511}{}{Non puoi aspettare? Devo bere.}
{512}{}{Ehi, se mi vuoi parlare, sono all'Hole.}
{513}{}{Troviamo ci all'Hole e ti offriro' da bere. Che ne dici?}
{520}{}{Spiacente, ma ho fretta di tornare a casa. Mi e' appena arrivato un porno nuovo.}
{521}{}{Sono uhhh, stanco; per favore, lasciami andare a casa a uhhh, dormire...}
{522}{}{Sto andando al negozio di Dave. Ha una nuova sezione interamente dedicata al porno!}
{530}{}{Uhhh, no grazie. Non ho soldi da sprecare in questo modo.}
{540}{}{D'accordo, ti daro' un'altra possibilita'.}
