{100}{}{Vedi un abitante del Den.}
{101}{}{Vedi Fred.}
{102}{}{Vedi Fred. Indossa dei vestiti molto raffinati.}
{150}{}{Sembra sia impegnato a pensare a qualcosa.}
{151}{}{Sembra essere piuttosto soddisfatto del suo nuovo guardaroba.}
{200}{}{Un giorno riusciro' a fare il colpo grosso.}
{201}{}{Oh, lasciami in pace. Sono occupato.}
{202}{}{Il grande progetto...}
{203}{}{Lo scopriro', un giorno o l'altro...}
{204}{}{Perche' perdo sempre?}
{205}{}{I tavoli devono essere truccati, non c'e' altra spiegazione.}
{206}{}{...un giorno mettero' su un locale tutto mio.}
{207}{}{Mi comprero' dei vestiti nuovi.}
{220}{}{Ehi, amico! E' tardi. Lasciami in pace.}
{221}{}{No, non ho bisogno di compagnia.}
{222}{}{Ma lo sai che ore sono?}
{223}{}{Non ho niente per te.}
{224}{}{Torna a disturbarmi domattina. Sono stanco.}
{225}{}{Smamma.}
{226}{}{Non c'e' nessuno in casa.}
{227}{}{Non posso parlare. Mi sto preparando per andare a letto.}
{228}{}{Ehi, miss! E' tardi. Lasciami in pace.}
{240}{}{Non ho piu' un soldo! Lasciami in pace.}
{241}{}{Non c'e' da lavorare. Che cosa faro'?}
{242}{}{Non dirmi che ho altri debiti da saldare! Ahh!}
{243}{}{Adesso non riusciro' piu' a fare il colpo grosso.}
{244}{}{Sono totalmente al verde.}
{245}{}{Oh cavolo, mi servono un po' di soldi.}
{246}{}{Adesso non ce la faro' mai a comprarmi dei vestiti nuovi.}
{247}{}{Devo pensare ad un nuovo, grande progetto...}
{260}{}{Grazie per avermi aiutato con il pagamento!}
{261}{}{Mi hai davvero salvato la vita.}
{262}{}{Presto potro' ridarti i soldi.}
{263}{}{Sono sicuro che presto faro' una grossa vincita!}
{264}{}{Sei la prima persona che cerchero' quando avro' vinto.}
{275}{}{Il grande progetto e' cominciato!}
{276}{}{Grazie del prestito! I tuoi soldi sono in buone mani!}
{277}{}{Quei tavoli sono davvero difficili, ma non temere.}
{278}{}{Un giorno faro' una grossa vincita, grazie a te.}
{279}{}{Presto, molto presto, vincero'! Me lo sento.}
{280}{}{Ti ripaghero', lo giuro!}
{281}{}{Ho la netta sensazione che presto faro' una grossa vincita.}
{295}{}{Eh? Ti conosco? Che cosa vuoi?}
{296}{}{Perche' continui a darmi noia? Non ti conosco nemmeno. Va' a disturbare qualcun altro.}
{297}{}{Sono qui per ritirare dei soldi che devi a qualcuno.}
{298}{}{Nulla.}
{299}{}{Uk!}
{300}{}{Addio.}
{310}{}{EHI! Eccoti qua! Ti ho cercato dappertutto! Guarda un po' questi vestiti!}
{311}{}{Grazie ancora.}
{312}{}{Davvero niente male.}
{313}{}{Fanno davvero schifo!}
{314}{}{Yuk!}
{315}{}{Ug.}
{320}{}{Grazie. Grazie mille! Grazie a te, adesso ho quattro completi come questo!}
{321}{}{Alla fine sei riuscito a fare quella grossa vincita, eh?}
{322}{}{Allora... dove sono i miei soldi?}
{330}{}{Non ti piacciono i miei vestti? Sai, credo tu abbia ragione. Anche a me non piacciono. E' ora di comprarne di nuovi - tanto posso permettermelo!}
{331}{}{Alla fine sei riuscito a fare quella grossa vincita, eh?}
{332}{}{Allora... dove sono i miei soldi?}
{333}{}{Hmph.}
{340}{}{Ci stavo arrivando! Non vuoi lasciare nemmeno che mi crogioli nella mia gloria? Ho lavorato sodo per raggiungere questo risultato, sai?}
{341}{}{Lo so, scusami.}
{342}{}{Al diavolo. Dove sono i soldi che ti ho prestato?}
{343}{}{Non me ne frega un cazzo. Dove sono i miei soldi?}
{350}{}{Beh, eccoli. [Fred ti da' 500$] Un piccolo extra per esserti fidato di me. Beh, ci vediamo. Grazie ancora.}
{351}{}{Grazie!}
{352}{}{Bah.}
{360}{}{Grazie per avermi aiutato con quei soldi. Ha significato davvero molto per me, la fiducia di un completo sconosciuto. Lascia che ti dia questo.}
{361}{}{Okay.}
{362}{}{Non avresti dovuto.}
{363}{}{Uh.}
{370}{}{Ti devo molto. Ti sei fidato di me quando la fortuna mi aveva girato le spalle. Come piccolo segno della mia gratitudine, ho qualcosa che vorrei darti.}
{371}{}{Okay.}
{372}{}{Non avresti dovuto.}
{373}{}{Uh.}
{380}{}{Ecco. [Fred ti da' 1000$.] Spero ti siano d'aiuto. Sono sicuro che troverai il modo giusto per spenderli.}
{381}{}{Grazie, ma non posso accettare.}
{382}{}{Grazie.}
{383}{}{Non credo, ma li prendo lo stesso.}
{384}{}{Yum.}
{390}{}{Ecco. [Fred ti da' 2000$, 5 Celle di Fusione, 5 Celle di Energia e una granata al plasma.] Spero ti siano d'aiuto, almeno un po'.}
{391}{}{Grazie, ma non posso accettare.}
{392}{}{Grazie mille.}
{393}{}{Non credo, ma li prendo lo stesso.}
{394}{}{Yum.}
{400}{}{Cosa? Beh, okay, se proprio insisti. Grazie, grazie mille. Buona fortuna.}
{401}{}{Addio.}
{410}{}{Cos'e'? Ti sei fatto di qualche strana droga? Non hai l'aspetto di un drogato. Sparisci dalla mia vista, sballato che non sei altro.}
{411}{}{Sparisci!}
{412}{}{Ug.}
{420}{}{Di cosa stai parlando? Io non devo niente a nessuno. Di chi diavolo stai parlando?}
{421}{}{Gia', l'hai detto anche l'altra volta. Non so di cosa tu stia parlando. Chi e' questa persona immaginaria?}
{422}{}{Becky dice che le devi 500$.}
{423}{}{E' Becky che mi manda.}
{424}{}{Rebecca dice che ti ha prestato 200$.}
{430}{}{Oh, certo, come no? Rebecca mi ha prestato 200... Oh, aspetta. Forse - ummm...}
{431}{}{Mi ha detto di romperti il collo in caso tu non volessi pagare.}
{432}{}{Dammeli.}
{440}{}{Certo, come no? Non ho mai visto cosi' tanti soldi in vita mia.}
{441}{}{Hmmm.}
{442}{}{Oh.}
{450}{}{Certo! Non scherziamo. Becky non farebbe male ad una mosca. Lei e' sempre gentile con tutti.}
{451}{}{Beh, ti sbagli, coglione.}
{452}{}{Forse era qualcun altro.}
{460}{}{Dannazione. Credo tu abbia ragione, ma - sono quasi al verde. Non posso darti tutti quei soldi! Sai, devo anche mangiare.}
{461}{}{Scusa.}
{462}{}{Che disdetta.}
{470}{}{Oh, diamine. Posso a malapena darti 100$. Potresti pagare tu l'altra meta' per me? Ti prometto che te li ridaro'!}
{471}{}{No, mi spiace.}
{472}{}{Niente storie. Dammi l'intera cifra!}
{473}{}{Okay, d'accordo.}
{480}{}{Diamine. Tu mi vuoi rovinare! Beh, okay, ecco qua. Adesso sono completamente al verde.}
{481}{}{Oh, d'accordo. Ti aiutero' con il pagamento.}
{482}{}{Grazie. Amministra meglio i tuoi soldi, la prossima volta.}
{483}{}{E' un piacere fare affari con te.}
{490}{}{Te l'ho detto! Non posso! Morirei di fame se lo facessi. Oh, dai, non vuoi proprio aiutarmi?}
{491}{}{D'accordo. 100$ li metto io.}
{492}{}{No, mi spiace. E poi nemmeno ce li ho, quei soldi.}
{493}{}{Tornero'.}
{500}{}{Cosa? Davvero? Wow! Grazie mille, amico! Ecco 100$. Ti daro' gli altri 100 il piu' presto possibile!}
{501}{}{Cosa? Davvero? Wow! Grazie mille, miss! Ecco 100$. Ti daro' gli altri 100 il piu' presto possibile!}
{502}{}{Nessun problema.}
{503}{}{Farai meglio a ridarmeli.}
{510}{}{Oh, non temere. Lo faro'! Hai la mia parola che non me ne dimentichero', questa volta!}
{511}{}{Okay.}
{520}{}{Beh, sai una cosa? Quel centone mi dara' sicuramente un po', uhm... di tempo in piu'. Credi di potermene prestare ancora un po'?}
{521}{}{Quanto?}
{522}{}{Assolutamente no.}
{530}{}{Aspetta! Ho un'idea. Senti, io ti do 100$ e tu metti per me gli altri 100 che devo a Becky. Te li ridaro' presto.}
{531}{}{Okay, d'accordo.}
{532}{}{No.}
{540}{}{Solo 50$. Ti prego! Fa tutto parte del mio grande progetto!}
{541}{}{Okay.}
{542}{}{Ma questo mi lascerebbe con soltanto 50$ per pagare il tuo debito da 200.}
{543}{}{No.}
{550}{}{Cosa- uh... Diamine! Non te ne pentirai! Te lo giuro!}
{551}{}{Nessun problema.}
{560}{}{Uh, certo. Vedo che le tue doti matematiche - cioe', ti prego! Non e' molto per te, ne sono certo, ma per me sarebbe davvero molto.}
{561}{}{Okay.}
{562}{}{No.}
{570}{}{Certo... e io dovrei anche crederti? Tutti sanno che lei odia quel nome. Non mi inganni!}
{571}{}{Non le devo nulla.}
{572}{}{Dice che te ne sei dimenticato.}
{573}{}{Senti, non ho tempo per queste cose. Dammi quei dannati soldi!}
{574}{}{Rebecca mi ha detto che te li ha prestati un bel po' di tempo fa.}
{580}{}{Non me ne sono dimenticato! Io... aspetta. C'era quella volta che... non le ho ridato i soldi? Credevo di averlo fatto...}
{581}{}{No, non l'hai fatto. E' per questo che mi ha mandato da te.}
{582}{}{Dammi quei soldi. Vorrei andarmene da qui il piu' presto possibile.}
{590}{}{Non ricordo... Quel che e' certo e' che Becky in passato ha aiutato me e i miei amici.}
{591}{}{Dammi quei 200$.}
{592}{}{Dammi i soldi e basta.}
{600}{}{Lasciami in pace.}
{601}{}{Vabbe'.}
{602}{}{Okay.}
{610}{}{Uh. Ciao. Allora, uh, immagino tu voglia i soldi. Credi di potermi anticipare la meta'?}
{611}{}{No, mi dispiace.}
{612}{}{Se ti ha prestato 200$, devi ridarglieli tutti.}
{613}{}{Okay, d'accordo.}
