{100}{}{Vedi un uomo dall'aspetto minaccioso.}
{101}{}{Vedi Metzger, il Mastro Schiavista.}
{150}{}{Metzger e' il capo della Gilda degli Schiavisti.}
{200}{}{La pagherai per questo.}
{210}{}{What the fuck do you want? This is the Slaver's Guild, not some safe
 house for you fucking jetheads.}
{211}{}{Che cosa diavolo vuoi, brutta troia? Questa e' la Gilda degli Schiavisti e non un fottuto bordello.}
{212}{}{Che cosa diavolo vuoi, troia? Questa e' la Gilda degli Schiavisti e non un fottuto bordello.}
{213}{}{Stai cominciando a farmi incazzare. Che cosa diavolo vuoi, adesso?}
{214}{}{E adesso cosa c'e', cazzo?}
{215}{}{Cosa?}
{216}{}{Oh, farai meglio a fare in fretta.}
{217}{}{Sei qui per un cazzo di lavoro?}
{218}{}{Sto cominciando ad abituarmi al tuo brutto muso. Allora... c'e' una ragione per la quale ti trovi qui o no?}
{219}{}{Ti sembro forse il tuo fottuto paparino? Spero proprio di no. Adesso sputa il rospo, che cosa vuoi?}
{220}{}{Oh, guardate un po' chi c'e'... Credi di essere speciale o che? Parla o fila fuori di qui.}
{221}{}{E adesso cosa vuoi, schiavista?}
{222}{}{Hai intenzione di rimanere li' fermo, oppure prima o poi dirai qualcosa?}
{223}{}{Parla. Non ho tutta la giornata da dedicare a queste stronzate.}
{230}{}{Oh, e *chi* vorresti vendere? Spero tu non abbia intenzione di rivedere questa persona...}
{231}{}{Non hai nessuno che mi interessi. A me interessano soltanto le persone - persone *normali*, intendo.}
{232}{}{Fottuto imbecille, cosa credi che io sia, un fottuto negozio? Se hai uno schiavo da vendermi, fammelo sapere. Se vuoi vendere qualcos'altro, va' in un fottuto negozio.}
{233}{}{Miria}
{234}{}{Davin}
{235}{}{Vic}
{236}{}{Myron}
{237}{}{Cassidy}
{238}{}{Sulik}
{239}{}{Posso farti un'altra domanda, invece?}
{240}{}{Ho cambiato idea. Ci vediamo.}
{241}{}{Dex}
{242}{}{Cat Jules}
{243}{}{Kitsune}
{245}{}{Continua.}
{246}{}{Si'?}
{247}{}{Non sono il tuo fottuto servo, percio' sbrigati.}
{248}{}{Cosa c'e'? Non ho tutto il giorno.}
{249}{}{Spara.}
{250}{}{Forse.}
{255}{}{Ho qualcuno che vorrei vendere.}
{256}{}{A proposito di Vic...}
{257}{}{Sto cercando un mercante.}
{258}{}{Lara mi ha mandato a chiederti il permesso per attaccare Tyler.}
{259}{}{Posso entrare a far parte della gilda?}
{260}{}{Cosa puoi dirmi a proposito della vostra gilda?}
{261}{}{Vorrei partecipare ad un rastrellamento di schiavi.}
{262}{}{Nulla. Arrivederci.}
{263}{}{ vuole fare male.}
{264}{}{Na.}
{265}{}{I was looking over the slaves you got back there, but you see, I have very, uh...*selective* tastes, and none of
 them are quite what I'm looking for. Are these all the slaves you have to offer?}
{270}{}{Credi di potercela fare? Io non prendo il primo venuto... E che cazzo. Se sgarri, ti liquido all'istante. Dovrai farti fare un tatuaggio sulla fronte che ti identifichi come schiavista. E' permanente, percio' niente ripensamenti.}
{271}{}{E cosi' il nostro gentile fiorellino e' tornato... Hai cambiato idea, allora? Hai deciso di farti fare quel tatuaggio?}
{272}{}{Si', perche' no? Non hai bisogno di molto cervello per partecipare ad un raid. Tanto, se sgarri, ti liquido all'istante. Se pensi di potercela fare dovrai farti fare un tatuaggio sulla fronte che ti identifichi come schiavista.}
{273}{}{Cominciamo.}
{274}{}{Devo pensarci su. Tornero'.}
{275}{}{Meglio di no. Addio.}
{276}{}{Uya! [annuisci]}
{277}{}{No no no no no!}
{285}{}{Che cosa cazzo pensi che sia? Questa e' una gilda schiavista. Io mi occupo della compravendita di schiavi.}
{286}{}{Dove prendete gli schiavi?}
{287}{}{Vorrei unirmi a voi.}
{288}{}{Un'altra domanda, per favore.}
{289}{}{Oh, okay. Ciao.}
{300}{}{Oh, qui e la'. Principalmente raccogliamo primitivi; e nomadi, se ne incontriamo un gruppo.}
{301}{}{Sembra divertente. Come faccio a partecipare?}
{302}{}{Ho un'altra domanda.}
{303}{}{Oh, okay. Ciao.}
{310}{}{Chi l'avrebbe mai detto? Non hai nemmeno gridato. Sono fiero di te... e a dirla tutta, quel tatuaggio ti sta proprio bene. Fammi un fischio quando sei pronto per il tuo primo raid.}
{311}{}{Grazie. Ciao.}
{312}{}{Sono pronto anche subito.}
{313}{}{Me uccide ORA!}
{314}{}{Okey-Dokey.}
{320}{}{Due dei miei uomini ti porteranno a poca distanza dai tuoi obiettivi. La tua paga si basera' sul numero di schiavi che avrai catturato, ma cerca di coprire le spalle anche ai tuoi compagni. Se qualcuno rimane ucciso, la tua paga verra' ridotta drasticamente.}
{321}{}{Cazzo, abbiamo razziato tutto il razziabile. Adesso dobbiamo aspettare che qualche tribu' di primitivi ritorni in zona. Forse dovremmo cominciare ad allevarli.}
{322}{}{Mi spiace, tu proprio non funzioni. Troppe perdite, e questi sono affari. Ho bisogno di farli, i soldi, non di perderli.}
{323}{}{D'accordo. Sono pronto.}
{324}{}{Bene, puoi partire subito.}
{325}{}{Muoviti.}
{326}{}{Bene. Torna da me quando avrai finito.}
{327}{}{Okay.}
{328}{}{Uh.}
{340}{}{Uccidi solo quelli ostili. Se ti attaccano, uccidili. Non ho voglia di occuparmene in un secondo tempo, sarebbe un fottuto spreco di tempo e di energie. Una volta terminato il tuo lavoro, gli altri schiavisti ammasseranno e marchieranno quelli rimasti.}
{341}{}{Okay.}
{342}{}{Oh.}
{350}{}{Una volta che sara' cominciata la marchiatura degli schiavi, puoi anche tornare, se vuoi. E' necessario un addestramento speciale, per cui non provare a catturare gli altri da solo. Puoi fare tutto quello che vuoi, purche' le tue azioni non danneggino la merce.}
{351}{}{Okay.}
{352}{}{Ah-a.}
{360}{}{Ah, certo. E' piuttosto carina. Ti daro' }
{361}{}{Mi pare in salute. Potrei togliertelo dai piedi per, oh, diciamo }
{362}{}{Fottuto idiota. Cosa diavolo ti fa pensare che io possa volere indietro quell'imbecille? Ci ha impiegato secoli solo per riparare una dannata ricetrasmittente! Una ricetrasmittente! Tientelo. Non lo voglio piu' vedere qui in giro a spaccare qualcos'altro.}
{363}{}{Non so, questo mi pare un tantino troppo pelle e ossa... e' intelligente, dici? Forse potrebbe valere qualcosa. Ti daro' }
{364}{}{Questo sembra proprio essere un buon combattente. Hmm... }
{365}{}{Un altro primitivo. E questo sembra pure un fenomeno da baraccone. Tuttavia, sembra forte e questo aspetto potrebbe dargli un valore extra. }
{366}{}{Che ne diresti se ti vendessi qualcos'altro?}
{367}{}{Beh, allora vorrei farti un'altra domanda.}
{368}{}{Okay.}
{369}{}{Bene.}
{370}{}{Okay.}
{371}{}{Non li vale.}
{372}{}{No.}
{380}{}{D'accordo, ragazzi, mettetelo nel recinto.}
{381}{}{D'accordo, ragazzi, mettetela nel recinto.}
{382}{}{Bene, boss.}
{390}{}{Beh, non sprecare il mio fottuto tempo, allora. Torna a trovarmi quando avrai qualcuno da vendermi.}
{391}{}{Ho un'altra domanda da farti.}
{392}{}{Okay. Ciao.}
{400}{}{Cosa diavolo le e' saltato in testa, cosi' all'improvviso? Ho dato a quella puttanella una possibilita' proprio poco tempo fa. Non pensavo che avesse le palle per provarci.}
{401}{}{Di cosa stai parlando?}
{402}{}{Devo prenderlo come un si'?}
{410}{}{Oh, non giocare con me. So esattamente cosa sta progettando di fare. Poco tempo fa le ho dato una possibilita' e non l'ha accettata, ma se adesso pensa di potercela fare...}
{411}{}{Allora, e' okay?}
{420}{}{Beh, le avevo detto che l'offerta sarebbe rimasta aperta. Se lei pensa finalmente di poterlo battere e crede di essere piu' brava di lui a controllare la mia roba...}
{421}{}{Beh?}
{422}{}{Allora, questo e' un si'?}
{430}{}{Senti, non me ne frega un cazzo di chi fa la guardia alla mia roba. Almeno fino a quando la mia merce non viene danneggiata.}
{431}{}{Un'altra domanda, per favore.}
{432}{}{Okay, grazie.}
{440}{}{Che cosa cazzo mi chiedi? Ti sembro forse un fottuto... oh, aspetta. Probabilmente stai cercando Vic, giusto?}
{441}{}{E' lui quello 'specializzato' in tecnologia dei vault. O almeno cosi' dice lui. E' di mia proprieta', adesso. Non va da nessuna parte.}
{442}{}{Cosa mi puoi dire di lui?}
{443}{}{Si', e' lui.}
{444}{}{Posso vederlo?}
{445}{}{Perche' lo trattieni qui?}
{446}{}{Okay, grazie. Ci vediamo.}
{455}{}{Quello stronzo - mi ha venduto una ricetrasmittente che, a suo dire, mi avrebbe permesso di intercettare certe trasmissioni. Beh, non lo faceva. L'ho beccato mentre cercava di sgattaiolare fuori citta' prima che me ne accorgessi. Madornale errore. Nessuno puo' fregarmi. E' fortunato ad essere ancora vivo. }
{456}{}{Come ti ho gia' detto, deve prima riparare una cosa. Dopo di che... vedremo. }
{457}{}{Beh, finalmente e' riuscito a far funzionare quella dannata radio, ma questo non vuol dire che lo lascero' andar via cosi' facilmente. }
{458}{}{Ha pur sempre cercato di fottermi.}
{459}{}{Posso vederlo?}
{460}{}{Di che tipo di trasmissioni stai parlando?}
{461}{}{Okay, grazie.}
{462}{}{Un po' di soldi potrebbero servire a risolvere la questione?}
{463}{}{Di che tipo di trasmissioni stavi parlando?}
{475}{}{E perche'? Ah, cazzo, non importa. Cerca solo di non disturbarlo troppo mentre ripara quella dannata ricetrasmittente - e sara' meglio che la ripari in fretta. Sono stufo di mantenere quel fottuto pigrone.}
{476}{}{Perche' lo trattieni qui?}
{477}{}{Grazie.}
{485}{}{Quelle provenienti dall'Enclave e da New... ehi. Cazzo te ne frega? Questioni di affari. Ho bisogno di sapere se c'e' qualcuno che cerca di fottermi. Questo e' tutto quello che ti serve sapere.}
{486}{}{Fatti gli affari tuoi.}
{487}{}{Okay.}
{495}{}{Certo, ma ti costera' }
{496}{}{$}
{497}{}{Non possiamo metterci d'accordo in un altro modo?}
{498}{}{Okay. Ecco.}
{499}{}{Prima vorrei farti qualche altra domanda.}
{500}{}{Mi dispiace, adesso non posso permettermelo.}
{510}{}{Okay, e' tuo, ma porta il suo brutto muso fuori di qui prima che cambi idea e gli piazzi un proiettile in quella sua fottuta testa vuota.}
{511}{}{Prima posso farti qualche altra domanda?}
{512}{}{Grazie.}
{520}{}{Oh, si'. Possiamo metterci d'accordo eccome... Ti faro' uno sconto del 50% se fai in modo che il tempo che sto perdendo con te non sia del tutto sprecato...}
{521}{}{Farai meglio a smetterla di prendermi in giro, donnetta. La mia pazienza e' molto limitata.}
{522}{}{Solo se sarai gentile con me.}
{523}{}{Certo, perche' no?}
{524}{}{Magari piu' tardi.}
{530}{}{Oh, puoi starne certa.}
{531}{}{Bene.}
{540}{}{Ecco }
{541}{}{Ecco i tuoi }
{542}{}{Hai fatto un buon lavoro. Ecco }
{543}{}{Ecco i tuoi soldi, }
{544}{}{$}
{545}{}{Bene, stavolta sono }
{546}{}{Non e' stata molto dura, no? La prossima volta niente errori. Ecco }
{547}{}{$}
{548}{}{E dai! }
{549}{}{Ricorda: guarda le spalle agli altri schiavisti e uccidi solo gli schiavi ostili. Ecco }
{550}{}{Solo }
{551}{}{Hai intenzione di fare soldi o no? Mi stai facendo incazzare. Quanto potra' mai essere difficile? Adesso prendi i tuoi }
{552}{}{Quale cazzo e' il tuo problema? Non guadagni un cazzo, stavolta. Siamo qui per fare soldi, non per cazzeggiare.}
{553}{}{La prossima volta faro' meglio.}
{554}{}{Che generosita'...}
{555}{}{Grazie.}
{556}{}{Ug.}
{570}{}{Dannata troia, era la tua prima volta? Ma certo che era la tua prima volta!}
{571}{}{Dannata ragazza, era la tua prima volta?}
{572}{}{Non male, credo.}
{573}{}{Niente male... magari potremmo farlo ancora, in un'altra occasione.}
{574}{}{Cazzo! Che... soldi spesi bene.}
{575}{}{Cazzo! Sei la miglior scopatrice che abbia mai conosciuto... e si' che ne ho conosciute tante.}
{600}{}{FOTTUTO TESTA DI CAZZO! Come hai potuto abbandonare i tuoi compagni schiavisti la' fuori? [Ti sputa in faccia.] AMMAZZATELO!}
{601}{}{Ma... io...}
{602}{}{Benissimo, diamoci dentro.}
{620}{}{Beh, sono felice che tu sia riuscito a tornare.}
{621}{}{Si', e' stato un raid molto duro.}
{622}{}{Grazie. Le cose si sono messe piuttosto male, laggiu'.}
{623}{}{Agra Moo ne!}
{630}{}{Oh, vuoi dei soldi? Vuoi essere pagato?}
{631}{}{Yah.}
{632}{}{Ugh.}
{640}{}{Naturalmente mi piacerebbe MOLTISSIMO aiutarti, ma... c'e' un piccolo problema... un problema riguardo l'aver attaccato uno dei miei uomini.}
{641}{}{Mi dispiace! Io non volevo - cioe'... Ugh?}
{642}{}{Uh, oh.}
{650}{}{Oh, non preoccuparti. Credo proprio mi sia rimasta un po' di generosita' per pagarti - o meglio, per ri-pagarti. Ragazzi, e' giorno di paga.}
{651}{}{Oh, non preoccuparti. Credo proprio sicuro mi sia rimasta un po' di generosita' per pagarti - o meglio, per ri-pagarti. Ragazzi, fate fuori questa troia.}
{652}{}{Oops.}
{653}{}{Garaka!}
{654}{}{Uh... Grassie?}
{670}{}{Oh, ne sono certo. Questo tipo di lavoro non va preso alla leggera. Richiede fiducia e lealta'. Ognuno di noi guarda le spalle all'altro. E' una buona politica, non trovi?}
{671}{}{Credo di si'.}
{672}{}{Uh, cosa succede?}
{673}{}{Assolutamente.}
{680}{}{Credi di si'? Non pensavo che tu fossi cosi' sveglio. Sei davvero un fottuto testa di cazzo. [Metzger ti fissa, poi guarda le sue guardie e fa un cenno nella tua direzione.]}
{681}{}{Azioni?}
{682}{}{Cosa?}
{690}{}{Oh, allora non sei cosi' stupido come sembra. Beh, e' un vero peccato. Sai, ho questo dilemma che mi affligge. Qualcuno ha avuto il coraggio di attaccare i miei uomini.}
{691}{}{Davvero?}
{692}{}{E' stato un incidente!}
{700}{}{Davvero? Sono contento che tu sia d'accordo. Ora... cosa faresti se uno tradisse questa fiducia?}
{701}{}{Uh, gli darei un avvertimento?}
{702}{}{Ecco. Lascia che te lo mostri. [attacca]}
{703}{}{Gliela farei pagare.}
{710}{}{Davvero la pensi cosi'? Sicuro? Non saprei. Io stavo pensando a qualcosa di piu'... permanente. [con un ghigno demoniaco, Metzger guarda le sue guardie e fa un cenno con la testa.]}
{711}{}{Cosa?}
{712}{}{Oh, capperi...}
{720}{}{Sono felice che siamo d'accordo su questo punto. [Metzger guarda le sue guardie.] Ragazzi, e' giorno di paga.}
{721}{}{Uh...}
{730}{}{Si'. E' davvero un peccato. Questa persona sembra proprio che non capisca, ma penso che tra un po' lo fara'. [vedi Metzger fare un piccolo cenno con la mano ai suoi uomini.] Si comincia.}
{731}{}{Oh, davvero?}
{732}{}{Uh-oh.}
{740}{}{Si', temo che questi incidenti capitino piuttosto spesso da queste parti. Infatti, temo che ne accadra' un altro tra pochissimo. [Metzger sorride e fa un cenno con la testa ai suoi uomini.]}
{741}{}{Fatevi sotto!}
{742}{}{Non c'e' un altro modo per risolvere la questione, vero?}
{750}{}{Oh, ma questo sara' divertente. Credimi.}
{751}{}{Fottiti.}
{752}{}{Uh, okay.}
{800}{}{Hai ucciso il leader della Gilda degli Schiavisti.}
{900}{}{What you see is what you get. If you don't like my merchandise, then get the fuck out of my face and stop wasting my time.}
{901}{}{Uh, sorry. Let me ask you something else then.}
{902}{}{Right. I think I'll go then.}
{903}{}{Actually, I think I'm going to waste *you* and your whole sick fucking operation.}
{910}{}{This is all I've got in stock here, you picky fuck, but I've always got new merchandise coming in from my other slave camp.
 Maybe if you check back later, I'll have something that tickles your fancy -- but they're mostly ignorant tribals that all look the
 fucking same, so if that's not your thing, you might be shit outta luck.}
{911}{}{Look, this might be an unusual request, but I'd really like to get first dibs on any new merchandise you got. Is there some
 way I could go check out the stock at your other camp? Of course, I'd be willing to pay a premium price.}
{912}{}{Alright, I'll keep checking back then.}
{913}{}{Good, but next time do me a favor and don't waste my time unless you've got actual business to discuss.}
{914}{}{Premium price, huh? Now you're talking my kinda language. We usually handle sales here, but I suppose an exception could be made,
 as long as you're serious. I'll tell you how to get there, but you better keep it to your fucking self. I swear, if you turn out to be a
 spy for them fucking Rangers, I'll hunt you down and skin you alive. [You listen to his directions, and note the Slaver Camp's location in your Pip-Boy.]}
{915}{}{Got it. Let me ask you something else.}
{916}{}{Thanks. I'll be on my way now. Bye.}
{1360}{}{$ per lei. Che ne dici?}
{1361}{}{?}
{1363}{}{.}
{1364}{}{.}
{1365}{}{?}
{1496}{}{.}
{1540}{}{$. Un lavoro niente male.}
{1541}{}{$. Sei stato grande. Continua cosi'.}
{1542}{}{.}
{1543}{}{, }
{1544}{}{$. Non c'e' molto da sorridere, ma non potevi pretendere di piu'.}
{1545}{}{$. Un lavoro ben fatto.}
{1546}{}{.}
{1547}{}{$? Non male.}
{1548}{}{$? Puoi fare di meglio.}
{1549}{}{.}
{1550}{}{$! Pietoso! Rimettiti in riga o ti caccio.}
{1551}{}{$ e sparisci.}
{2540}{}{.}
{2543}{}{.}
{15401}{}{$. Un lavoro niente male, }
