{100}{}{Vedi uno schiavista.}
{150}{}{Sembra essere molto attento.}
{200}{}{Toccala ancora e ti stacco il braccio.}
{201}{}{Ti ho visto!}
{210}{}{La' dentro ci sono solo schiavi. E nient'altro.}
{211}{}{Gli schiavi non possono ricevere visite.}
{212}{}{Solo i membri della gilda possono entrare.}
{213}{}{Cerchi uno schiavo? Parla con Metzger.}
{214}{}{Parla con Metzger. Non puoi entrare nella gabbia degli schiavi.}
{215}{}{Che cosa ci fai qui? Sparisci.}
{216}{}{Sparisci, puttana. Gli schiavi non possono ricevere visite.}
{230}{}{Ehila', come butta?}
{231}{}{Oggi e' una vera barba.}
{232}{}{Spero ti piaccia fare parte della gilda.}
{233}{}{Il tuo tatuaggio e' venuto proprio bene.}
{234}{}{Hai partecipato all'ultimo raid?}
{235}{}{Ciao.}
{236}{}{Sei proprio il mio tipo.}
{237}{}{Una femmina schiavista - meriti rispetto.}
{238}{}{Ehila'.}
{239}{}{Butta bene.}
