{100}{}{Vedi un uomo enorme, dall'aspetto primitivo.}
{101}{}{Quest'uomo sembra discretamente forte e attento.}
{110}{}{Vedi una donna primitiva mingherlina.}
{111}{}{Sembra robusto, nonostante la sua stazza.}
{120}{}{Vedi un uomo dall'aspetto strano.}
{121}{}{Sembra terribilmente magro.}
{130}{}{Vedi un uomo dall'aspetto rozzo.}
{131}{}{Questo sembra essere discretamente forte.}
{140}{}{Vedi un uomo che indossa degli abiti consunti.}
{141}{}{He moves with suggesting speed.}
{150}{}{Vedi una donna molto sporca.}
{151}{}{Sembra che non si sia mai fatta un bagno in vita sua.}
{160}{}{Vedi una donna abbastanza robusta.}
{161}{}{Sembrerebbe essere una guerriera molto forte.}
{170}{}{Vedi una donna pelle e ossa.}
{171}{}{Questa qui non sembra amare troppo il pericolo.}
{200}{}{Morire!}
{201}{}{Dove essere?}
{202}{}{Me fare male te.}
{210}{}{Te la faro' pagare per questo!}
{211}{}{Dio maledica gli schiavisti!}
{212}{}{La pagherai per questo!}
{220}{}{Lasciare noi in pace!}
{221}{}{No fare bua!}
{222}{}{Noi no fatto male te!}
{223}{}{Io no combatte!}
{230}{}{Riconosco quel tatuaggio!}
{231}{}{No, vi prego!}
{232}{}{Vi prego, non uccidetemi!}
{233}{}{Non combattero'; non uccidetemi!}
{234}{}{Vi supplico, non voglio morire!}
{235}{}{Siete schiavisti, vero? O Dio...}
{245}{}{Silenzio! Loro vicino.}
{246}{}{Uccidere uomini cattivi.}
{247}{}{No prendere famiglia da me.}
{248}{}{Io proteggere famiglia.}
{249}{}{No deve trovare noi.}
{250}{}{Loro cattive persone.}
{260}{}{Gli schiavisti stanno arrivando. State tutti zitti.}
{261}{}{State pronti; credo siano vicini.}
{262}{}{Non mi arrendero' senza combattere.}
{263}{}{Non ci faranno schiavi.}
{264}{}{Quegli schiavisti la pagheranno per questo.}
{265}{}{Nessuno schiavista prendera' la mia famiglia.}
{270}{}{Loro no trovare me.}
{271}{}{Me deve nascondere. Me deve nascondere.}
{272}{}{Perche' loro volere fare male noi?}
{273}{}{Me spaventato.}
{274}{}{Me no combatte.}
{275}{}{Me vuole vivere.}
{276}{}{No fare male famiglia.}
{280}{}{Oh, merda!}
{281}{}{Perche' ci fanno questo?}
{282}{}{Che ne e' della mia famiglia?}
{283}{}{Non voglio morire.}
{284}{}{Non voglio diventare uno schiavo.}
{285}{}{Mi merito una vita migliore.}
{290}{}{Tu morire ora!}
{291}{}{Me uccide!}
{292}{}{Tu no fare male famiglia!}
{293}{}{Tu no prendere famiglia!}
{294}{}{Io protegge!}
{295}{}{Io fa male te!}
{296}{}{Tu pagare!}
{300}{}{Non prenderai la mia famigla, schiavista!}
{301}{}{Muori, feccia schiavista!}
{302}{}{La pagherai, bastardo!}
{303}{}{Lottero' fino all'ultimo per difendere la mia famigla!}
{304}{}{Non la passerai liscia!}
{305}{}{Non te ne andrai di qui portandoti via i miei amici!}
{310}{}{Ahhh!}
{311}{}{No uccidere! No uccidere!}
{312}{}{Basta!}
{313}{}{Aiutoooooo!}
{314}{}{Scappare!}
{315}{}{No fare questo!}
{320}{}{Scappate, se ci tenete alla pelle!}
{321}{}{Non lasciate che vi catturino!}
{322}{}{Schiavisti! Scappate!}
{323}{}{Qualcuno ci aiuti! Vi prego!}
{324}{}{Scappa, Marty!}
{325}{}{Ahhh!}
{326}{}{Fermate questa follia!}
{327}{}{Non abbiamo fatto nulla! Lasciateci in pace!}
