{100}{}{Questa citta' sembra essere un luogo pericoloso. Un buon posto dove possedere una pistola.}
{200}{}{Hai aiutato la banda di Lara a vincere la battaglia.}
{300}{}{Hai attaccato con successo la banda di Lara.}
{400}{}{Hai trovato il distillatore di Becky per Frankie.}
{500}{}{Hai distrutto il distillatore di Becky.}
{600}{}{Hai convinto Frankie a comprare il liquore da Becky.}
{700}{}{Hai portato a termine il tuo primo raid schiavista.}
{800}{}{Hai pagato a Rebecca il debito di Fred.}
{900}{}{Hai riportato il libro a Rebecca.}
{1000}{}{Hai riportato il medaglione ad Anna.}
{1100}{}{Sei riuscito ad entrare nella chiesa con l'inganno .}
{1200}{}{Hai consegnato il pranzo a Smitty.}
{1300}{}{Hai trovato una debolezza nella banda di Tyler.}
{1400}{}{Hai ottenuto l'autorizzazione all'attacco per la banda di Lara.}
