{100}{}{Vedi un uomo in Power-Armor.}
{101}{}{Questo e' Sir Galahad.}
{102}{}{Arrossisce quando si accorge che lo stai fissando.}
{103}{}{Sir Galahad, attento e pronto!}
{104}{}{Una volta ero prigioniero nel Castello Antrace.}
{105}{}{Sir Lancillotto venne a salvarmi. Che sia dannato!}
{106}{}{E pensare che avrei potuto essere un prigioniero. [Sniff]}
{200}{}{Ehi! Le tue mani sono gelide!}
{201}{}{Quello non ti appartiene.}
{202}{}{Ehi, quelle sono le mie cose!}
