{100}{}{Vedi un uomo che indossa una Power-Armot Ver.II. Non sembra molto amichevole.}
{101}{}{Vedi Kaga in una Power Armor Ver.II.}
{102}{}{Un grosso blocco di metallo con braccia e armi.}
{103}{}{Sono stanco di inseguirti. Facciamola finita.}
{104}{}{Questa e' l'ultima volta che incontrerai Kaga.}
{105}{}{Sei un moscerino al confronto di Kaga.}
{106}{}{Non vedo l'ora di spedirti alla tua prossima vita.}
{107}{}{Sei stato un nemico valoroso.}
{108}{}{Questa parte delle lande non ha bisogno di un benefattore come te.}
{109}{}{Dopo che ti avro' ucciso, io saro' la persona piu' temuta di questa parte delle lande.}
{110}{}{Non vedo l'ora di tornare al villaggio, ad Arroyo - per ridurlo in cenere.}
{111}{}{Kaga sara' famoso per averti ucciso.}
{120}{}{Kagaaaaaaaa!}
{150}{}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}
{160}{}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}
{200}{}{Ooglie?}
{201}{}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
