{100}{}{Vedi un vecchio raggrinzito che indossa un camice bianco.}
{101}{}{Questo e' il Dr. Fung.}
{102}{}{Vedi un vecchio raggrinzito che indossa un camice bianco.}
{103}{}{Posso aiutarti?}
{104}{}{Bua! Ouch! Owwwwwww!}
{105}{}{Si' - Sto male e mi pare che tu sia un dottore.}
{106}{}{Si'. Ho bisogno di un dottore per un mio amico.}
{107}{}{Hai degli stimpak? Vorrei comprarne qualcuno.}
{108}{}{Chi sei?}
{109}{}{Ho un amico cui manca la milza. Puoi aiutarlo?}
{110}{}{Cosa puoi dirmi di questo posto?}
{111}{}{Addio.}
{112}{}{Lascia che ti dia un'occhiata. Hmm. Si'. Naturalmente, c'e' il mio onorario...}
{113}{}{Quanto?}
{114}{}{Scordatelo.}
{115}{}{Lo posso curare... ad un prezzo, naturalmente.}
{116}{}{Quanto?}
{117}{}{Scordatelo.}
{118}{}{Chi sono io? Io sono il Dr. Fung. Insegno e curo.}
{119}{}{Dr. Fung? Conosci per caso Doc Holliday?}
{120}{}{Piacere di conoscerti. Ho bisogno di cure.}
{121}{}{Un mio amico ha bisogno di cure.}
{122}{}{Capisco. Grazie. Arrivederci.}
{123}{}{Holliday? Si'! Gli ho insegnato tutto quel che sa! Dove si trova adesso?}
{124}{}{Vive a Broken Hills.}
{125}{}{E' tornato a casa, allora. Spero abbia trovato pace, laggiu'.}
{126}{}{Credo di si'. Ho delle altre domande.}
{127}{}{Probabilmente si'. Devo andare. Arrivederci.}
{128}{}{Ti costera' 100$.}
{129}{}{Paghero'.}
{130}{}{Scordatelo.}
{131}{}{Sembra una cosa seria. Ti costera' 200$.}
{132}{}{Paghero'.}
{133}{}{Scordatelo.}
{134}{}{Queste ferite sono impressionanti. 300$ e' tutto quel che serve per assicurarti la mia assistenza.}
{135}{}{Paghero'.}
{136}{}{Scordatelo.}
{137}{}{Per tutti questi danni, temo che dovro' chiederti 400$.}
{138}{}{Paghero'.}
{139}{}{Scordatelo.}
{140}{}{Sara' meglio che tu ti sieda. Ti servira', quando sentirai la mia parcella. La cura di arti menomati costa 600$.}
{141}{}{Paghero'.}
{142}{}{Scordatelo.}
{158}{}{Cosa? Non hai i soldi? Come credi che io possa sopravvivere se mi chiedi di curarti gratuitamente?}
{159}{}{Hai degli stimpak?}
{160}{}{No, grazie.}
{161}{}{E' stato un piacere fare affari con te.}
{162}{}{Grazie.}
{163}{}{La tua offerta, purtroppo, non e' accettabile.}
{164}{}{Cosa ne dici di questo?}
{165}{}{E' tutto quello che ho intenzione di offrire. Ci vediamo.}
{166}{}{Stai male? Tsk, tsk. Quest'antico rimedio ti rimettera' in sesto. }
{167}{}{O-kay!}
{168}{}{}
{169}{}{Abbiamo finito. Adesso va' pure... e sta' attento!}
{170}{}{Acie!}
{171}{}{Hai bisogno d'altro?}
{172}{}{Ho bisogno di cure.}
{173}{}{Ho un amico che ha bisogno di cure.}
{174}{}{Chi sei?}
{175}{}{Parlami di questo posto.}
{176}{}{Ho un amico cui manca la milza. Puoi aiutarlo?}
{177}{}{No. Grazie lo stesso.}
{178}{}{Sei venuto dalla persona giusta. Vuoi sentire la versione lunga o quella corta, della storia?}
{179}{}{Quella lunga.}
{180}{}{Quella corta.}
{181}{}{Nessuna delle due. Ho delle altre domande, pero'.}
{182}{}{La nostra gente e' sbarcata qui dal sottomarino Shih-huang-ti, quando i missili esplosero sul mondo. Con l'aiuto di una setta, noi, gli Shi, ricostruimmo San Francisco. Questa e' la versione corta della storia.}
{183}{}{E la versione lunga, invece?}
{184}{}{Grazie. Ho delle altre domande.}
{185}{}{Grazie.}
{186}{}{La versione lunga e' questa: Noi ci troviamo qui perche' la nostra gente discende dall'equipaggio di un sottomarino nucleare, lo Shih-huang-ti. Quando i missili caddero durante il Grande Diluvio, i sistemi di bordo del nostro sottomarino rimasero danneggiati e noi andammo alla deriva nel buio per molti giorni.}
{187}{}{-avanti-}
{188}{}{Infine, giungemmo alla terraferma. Ci ritrovammo nei pressi delle rovine di San Francisco. Gran parte della citta' era andata distrutta nella guerra. Dovemmo ricostruire una societa' partendo dai pochi sopravvissuti che erano tornati, strisciando, nella citta'.}
{189}{}{-avanti-}
{190}{}{Ricostruimmo usando quello che riuscivamo a trovare, ma adesso abbiamo scienziati e teconolgie che il mondo intero ci invidia. Stiamo ricostruendo la civilta', cercando di evitare gli errori del passato.}
{191}{}{Capisco. Ho delle altre domande.}
{192}{}{Grazie. Ciao.}
{193}{}{Certo che posso. E dal momento che conosci Doc Holliday... lo faro' in nome dell'amicizia e nulla piu'. Di' al tuo amico senza milza di venire qui e io la rimettero' al suo posto per lui.}
{194}{}{Grazie! Ho delle altre domande.}
{195}{}{Grazie!}
{196}{}{Si'. Posso farlo. Ti costera' 1000$. Sull'unghia. Accetti?}
{197}{}{Si'.}
{198}{}{No.}
{199}{}{Di' al tuo amico di venire qui e io la rimettero' al suo posto per lui.}
{200}{}{Grazie. Ho delle altre domande.}
{201}{}{Grazie.}
{202}{}{Non posso fare nulla per lui, a meno che tu non abbia 1000$. Buona giornata.}
{203}{}{Buona giornata.}
{204}{}{Io non curo i nemici della mia gente. Accetta, ti prego, le mie piu' umili scuse.}
{205}{}{Onorevole signore, ti consiglio di rivolgerti ai dottori della tua setta.}
{206}{}{Cosa puoi dirmi a proposito degli innesti corazzati?}
{207}{}{Ho collaborato alla stesura dell'articolo sugli innesti corazzati. Tutto quel che serve sono le conoscenze da parte mia e i materiali da parte tua. Che tipo di innesti desideri?}
{208}{}{Che tipi di innesti esistono?}
{209}{}{Gli innesti dermici.}
{210}{}{Il potenziamento degli innesti dermici.}
{211}{}{Gli innesti Phoenix.}
{212}{}{Il potenziamento Phoenix.}
{213}{}{Umm... come non detto. Ho delle altre domande.}
{214}{}{Nessuno, in realta'. Arrivederci.}
{215}{}{Ci sono gli innesti dermici, che proteggono dal danno conseguente a urti e colpi. Se ti piace questo, siamo anche in grado di applicare un potenziamento. Ci sono anche gli innesti Phoenix, che proteggono dagli attacchi basati sulle alte temperature, e anche per questo esiste un potenziamento. Se ti interessano questi potenziamenti, naturalmente dovrai aspettare che il set base sia installato. E, prima che tu me lo chieda, si', puoi sottoporti a TUTTE e quattro le operazioni.}
{216}{}{Ottimo. Prendero' gli innesti dermici.}
{217}{}{Voglio gli innesti dermici.}
{218}{}{Dammi il potenziamento degli innesti dermici.}
{219}{}{Vorrei gli innesti Phoenix.}
{220}{}{E' ora di prendere il potenziamento Phoenix.}
{221}{}{Umm... come non detto. Ho delle altre domande.}
{222}{}{Nessuno, in realta'. Arrivederci.}
{223}{}{Eccellente. Mi serve un'armatura da combattimento e, oh, 5500$. Ti serviranno due giorni e la capacita' di non grattarti le croste.}
{224}{}{Cominciamo.}
{225}{}{Scordatelo. Addio.}
{226}{}{Il potenziamento degli innesti dermici, eh? Ti costera' diversi giorni della tua vita, 33000$, un'armatura da combattimento, e un assortimento nuovo di zecca di cicatrici che non perderai per tutto il resto della tua esistenza.}
{227}{}{E allora? Io posso permettermi TUTTO questo!}
{228}{}{Hmm. Non penso di voler pagare un prezzo cosi' alto. Addio.}
{229}{}{Se non ti dispiace perdere 8500$, un paio di giorni e un'armatura da combattimento, possiamo cominciare l'operazione anche subito.}
{230}{}{Legami al lettino, doc. Sono pronto.}
{231}{}{E' un pochino caro. Tornero' un'altra volta.}
{232}{}{Questa e' un'operazione molto impegnativa. Ti costera' la tua "bella presenza", un'armatura da combattimento e 49000$. Sei pronto ad investire tutto questo nell'operazione?}
{233}{}{Diavolo, si'. Cominciamo.}
{234}{}{Wow. E' davvero... caro. Tornero' un'altra volta.}
{235}{}{::scuote la testa:: Non giocare con me. Ti mancano gli ingredienti necessari. Presta piu' attenzione, la prossima volta. Adesso va', e torna quando potro' davvero aiutarti.}
{236}{}{Okay.}
{237}{}{Ecco fatto! Sei stato... potenziato. Ricorda... non grattare le croste a meno che tu non voglia che si aggiungano delle cicatrici al tuo improvvisamente-non-troppo-piacevole aspetto.}
{238}{}{Grazie, doc. Addio.}
{239}{}{Ho i soldi per quella milza.}
{240}{}{Possiamo parlare ancora a proposito degli innesti?}
