{100}{}{Vedi un anziano ghoul particolarmente basso.}
{101}{}{Vedi Lenny, l'assistente di Harold.}
{102}{}{Vedi un anziano ghoul di bassa statura. Sembra preoccupato.}
{110}{}{Ehila', il mio nome e' Lenny. C'come posso a'aiutarti?}
{111}{}{B'bentornato. Come p'posso aiutarti?}
{112}{}{M'mi hanno d'detto che tu sei il discendente dell'Abitante del Vault. Sai, ho i'incontrato l'Abitante del Vault, una v'volta.}
{113}{}{Ehila'. C'continuo a s'stupirmi della tua i'incredibile somiglianza con l'Abitante del Vault. C'cosa p'posso fare per te?}
{114}{}{Grenny? Heewo.}
{115}{}{Di che cosa ti occupi?}
{116}{}{Sono ferito. Puoi aiutarmi?}
{117}{}{Uno dei miei amici e' ferito. Puoi aiutarlo?}
{118}{}{I miei amici sono feriti. Puoi aiutarli?}
{119}{}{Lenny, hai mai sentito parlare di un qualcosa chiamato Kit di Creazione del Giardino dell'Eden?}
{120}{}{Hai incontrato il mio antenato?}
{121}{}{Stavo solo dando un'occhiata in giro. Ci vediamo.}
{122}{}{Puoi fornirmi assistenza medica?}
{125}{}{Si'. Cosa ti serve?}
{126}{}{Credo che per il momento non mi serva nulla.}
{130}{}{N'non a'avresti d'dovuto lasciare il tuo villaggio. T'tornatene a casa, adesso.}
{131}{}{Casa? Ciao.}
{140}{}{D'dovresti tornare a c'casa.}
{141}{}{N'non ho t'tempo da d'dedicarti.}
{142}{}{Sc'scio'. V'vattene!}
{150}{}{Un K'kit di C'creazione del G'giardino dell'Eden? Ho sentito d'dire che Vault City ne aveva uno. E' l'unico di c'cui abbia mai s'sentito parlare.}
{151}{}{Sono ferito. Puoi aiutarmi?}
{152}{}{Uno dei miei amici e' ferito. Puoi aiutarlo?}
{153}{}{Beh, l'Abitante del Vault, il mio antenato, disse che il Vault 13 ne aveva uno. Devo trovarlo.}
{154}{}{Credo sia tutto, per il momento. Ci vediamo.}
{160}{}{B'beh, p'per lo p'piu' a'aiuto H'harold. Qu'quando qualcuno rimane f'ferito, io lo c'curo.}
{161}{}{Aiuti Harold a fare cosa?}
{162}{}{Lascia che ti chieda qualcos'altro.}
{163}{}{Puoi guarire le persone?}
{164}{}{Sono ferito. Puoi aiutarmi?}
{165}{}{Uno dei miei amici e' ferito. Puoi aiutarlo?}
{166}{}{Me lo ricordero', in caso dovessi rimanere ferito. Grazie. Ci vediamo.}
{170}{}{F'fammi d'dare un'occhiata. C'credo di poterti aiutare.}
{171}{}{Mi costera' qualcosa?}
{172}{}{Grazie, Lenny. Vorrei chiederti qualcos'altro.}
{173}{}{Grazie, Lenny. Ci vediamo.}
{174}{}{P'posso aiutarti. M'ma ti c'costera' 30$. S'sai, p'per i medicinali.}
{175}{}{Non credo di aver bisogno del tuo aiuto, al momento. Ci vediamo.}
{180}{}{Beh, il t'tuo amico avrebbe p'proprio bisogno di un po' di aiuto. Io p'posso a'aiutarlo.}
{181}{}{S'sembra p'proprio che abbiano p'passato dei bei g'guai. P'posso metterli in sesto, pero'.}
{182}{}{Mi costera' qualcosa?}
{183}{}{Grazie, Lenny. Vorrei chiederti qualcos'altro.}
{184}{}{Grazie, Lenny. Ci vediamo.}
{185}{}{Il t'tuo amico e' ferito. Posso m'metterlo in s'sesto per 30$. Mi s'servono i soldi per i m'medicinali.}
{186}{}{In c'che guai vi siete c'cacciati, ragazzi? S'sembra p'proprio che abbiate bisogno di un po' di c'cure. Devo c'chiederti 60$ per c'curare tutti quanti.}
{187}{}{A me pare che il t'tuo amico sia a posto...}
{190}{}{B'beh. In realta' n'non ho *davvero* conosciuto l'Abitante del V'vault. Ma l'ho visto. Una volta. }
{191}{}{Hai visto l'Abitante del Vault? Dove?}
{192}{}{Oh, capisco. Beh, ho dei posti dove andare e cose da uccidere. Addio.}
{200}{}{Beh, p'prima della G'guerra e'ero un dottore.}
{201}{}{Prima della guerra? Ma devono essere passati almeno 160 anni da allora.}
{202}{}{Oh; bene, questo spiega tutto. Grazie. Ci vediamo.}
{210}{}{E' v'vero. M'ma pare che le r'radiazioni abbiano c'conferito a n'noi g'ghoul una maggiore aspettativa di v'vita. Certo, ci hanno tolto praticamente tutto il resto.}
{211}{}{Vi hanno tolto qualcosa?}
{212}{}{Sembra proprio che ogni cosa abbia in se' dei lati negativi e dei lati positivi. Ci vediamo.}
{220}{}{B'beh, s'si'. Sembriamo dei f'fenomeni da b'baraccone. Non a'abbiamo la pelle, santi numi!}
{221}{}{Beh, immagino che tu abbia visto giorni migliori...}
{222}{}{Come gruppo, non e' che siate proprio gli esseri piu' attraenti del pianeta. Ci vediamo.}
{230}{}{P'puoi dirlo f'forte. S'sarei disposto a r'restituire tutti questi anni pur di t'tornare ad essere una p'persona normale.}
{231}{}{Beh, credo non ci siano molte speranze...}
{232}{}{E ci credo. Arrivederci.}
{240}{}{Se q'quegli idioti di Vault City dividessero c'con noi la loro tecnologia medica, sono sicuro che p'potremmo eliminare l'eccesso di r'radiazioni e curarci.}
{241}{}{Non hanno intenzione di aiutarvi?}
{242}{}{Credo di aver sentito abbastanza. Ci vediamo.}
{250}{}{S'sei stato a Vault City, no? E allora d'dimmi quali chance tu pensi che p'possiamo avere di o'ottenere dell'a'aiuto da q'quei bigotti. S'sarebbe piu' facile vedere un c'cane di carta che i'insegue un g'gatto d'asbesto in mezzo all'inferno.}
{251}{}{Mi dispiace, ma credo tu abbia ragione. Vorrei chiederti qualcos'altro.}
{252}{}{Mi dispiace. Ci vediamo.}
{260}{}{N’no. La v'vita e' troppo breve -- eh eh... beh, per la m'maggior parte delle persone, almeno -- per p'preoccuparsi delle piccole cose. E sai una cosa? Sono tutte piccole cose. Non mi devi nulla.}
{261}{}{Grazie Lenny.}
{270}{}{E' s'stato molto t'tempo f'fa. In un posto c'chiamato N'necropolis. Molti di noi g'ghoul vivevano li'. Un giorno vidi qualcuno che c'correva attraverso la citta'.}
{271}{}{Che correva?}
{272}{}{Beh, credo di aver prestato fin troppa attenzione ai tuoi incerti ricordi. Ci vediamo.}
{280}{}{Si', che correva. Vedi, noi ghoul n'non possiamo c'correre m'molto, per cui ho c'capito subito che si trattava di uno s'straniero, quando l'ho visto. Mi e' p'passato cosi' v'vicino che l'avrei potuto toccare. Mi pento molto di non essermi unito al g'gruppo dell'Abitante del Vault...}
{281}{}{Volevi unirti al gruppo del mio trisavolo?}
{282}{}{Ma certo... e tu credi davvero che il mio antenato avrebbe permesso che uno sgorbio senza pelle come te si unisse al suo gruppo? Addio.}
{283}{}{Uh, beh, mi piacerebbe molto sentire l'intera storia, ma ho delle faccende da sbrigare. Addio.}
{290}{}{Si'. Ho avuto l'occasione della v'vita e l'ho sprecata.}
{291}{}{Che cosa vuoi dire?}
{292}{}{Beh, cosi' va il mondo. Addio.}
{300}{}{In s'seguito, mi e' stato d'detto che l'Abitante del Vault aveva riparato il nostro sistema idrico. L'Abitante del V'vault ci aveva salvato -- tutti. Capisci? Non aveva importanza il fatto che noi fossimo ghoul. Eravamo di nuovo p'persone normali. M'meritevoli di essere salvate.}
{301}{}{Il mio antenato ha fondato la nostra tribu'. La memoria di questi fatti e' onorata tra la mia gente.}
{302}{}{Beh, a me interessa solamente salvare la mia tribu'. Il resto del mondo puo' difendersi da solo. Addio.}
{310}{}{Tempo dopo, mi e' stato detto che l'Abitante del Vault aveva distrutto l'origine dell'esercito m'mutante. L'Abitante del Vault ci aveva salvati tutti. Uomini e ghoul, senza distinzioni... Avrei potuto avere un ruolo in tutto questo, ma mi manco' il c'coraggio. Non ho mai p'perdonato me stesso.}
{311}{}{Sto seguendo le orme del mio predecessore. Vorresti avere un'altra possibilita'? Vorresti unirti a me?}
{312}{}{Sono certo che il lavoro che svolgi qui, tra i ghoul, abbia un valore e un senso. E' stato bello sentirti parlare del mio antenato. Vorrei chiederti qualcos'altro.}
{313}{}{Beh, molte persone sono dei codardi fino al midollo. Non e' una cosa di cui vergognarsi troppo. Sei solamente un debole, ecco tutto. Addio.}
{314}{}{Spesso il giusto cammino non e' chiaro. In questo mondo tutti noi abbiamo il nostro scopo speciale. Grazie per avermi parlato del mio antenato. Ci vediamo.}
{320}{}{Sono p'piu' f'felice di un brahmin maschio in un campo pieno di mucche! Sarei o'onorato di unirmi a t'te. Saro' a'anche vecchio e non mi m'muovero' r'rapidamente, o almeno non troppo a lungo, ma sicuramente potro' r'rattoparti le f'ferite in caso di b'bisogno.}
{321}{}{Sono felice che tu possa unirti a me. Sono sicuro che le tue capacita' curative ci saranno molto utili.}
{322}{}{Hmm, potrebbe essere troppo dura per uno della tua eta'. Credo che faresti meglio a rimanere qui. Mi dispiace. Addio.}
{330}{}{Ho del lavoro da fare qui. Non p'posso unirmi a te.}
{331}{}{Sei c'completamente diverso dal tuo antenato. Tu d'disonori la sua m'memoria.}
{332}{}{H'hai molto da imparare riguardo alla v'vita. N'non mi piace cio' che hai i'imparato fino adesso.}
{333}{}{Mi rattrista sentire che non puoi unirti a me.}
{334}{}{Cavoli, e io che credevo che un pezzo di carne marcesente come te avrebbe fatto salti di gioia se qualcuno gli avesse offerto la possibilita' di andarsene da questa fogna fosforescente di citta'. Addio.}
{340}{}{A'aiuto H'harold ad amministrare la citta'. C'ci sono sempre molte pratiche burocratiche da sbrigare.}
{341}{}{Cos'altro hai detto che fai?}
{342}{}{Credo sia tutto, per ora. Arrivederci.}
{350}{}{N'non avevi a'abbastanza soldi... ma t'ti ho a'aiutato lo stesso. Non sopporto di vedere le p'persone s'soffrire.}
{351}{}{Non so come ringraziarti, Lenny. Adesso, pero', mi servirebbero delle altre informazioni.}
{352}{}{Grazie, Lenny. Ti devo proprio un favore. Ci vediamo.}
{360}{}{Ci s'sono gia' cosi' tante p'persone con te. N'non hai bisogno del mio a'aiuto. B'buona fortuna.}
{370}{}{Non avrei mai p'pensato di vivere abbastanza da vedere il g'giorno in cui mi sarei vergognato di partecipare alle tue a'azioni. Tu d'disonori la m'memoria dell'Abitante del Vault. B’dee-ya, b’dee-ya, addio.}
{371}{}{Sai, c'credevo che s'sarebbe stato bello v'viaggiare con t'te. Ma s'sei cocciuto e irascibile come un b'brahmin maschio con un c'cactus su per il culo. E non hai n'neppure un odore migliore. B’dee-ya, b’dee-ya, addio.}
{372}{}{Mi dispiace vederti andare via, Lenny.}
{373}{}{Non riesci a sopportarlo, eh? Beh, farai meglio a trascinare via la tua carcassa mezza marcia prima che io decida se l'ucciderti valga o meno una cartuccia.}
{374}{}{*Burp* Si', come no? Immagino che tu abbia altre cose da fare; ad esempio, passare tutto il tuo tempo libero a ricordare com'era bello avere una pelle che non assomiglia al cadavere vecchio di tre settimane di un animale schiacciato da un automobile in pieno luglio. Sparisci, fottuto sgorbio.}
{375}{}{Okay.}
{380}{}{C'cosa v'vuoi che f'faccia?}
{381}{}{Lenny, lo so che ce la stai mettendo tutta. Ma, ti prego, levati dalle scatole.}
{382}{}{Ho bisogno che tu combatta in modo diverso, Lenny.}
{383}{}{Vorrei che tu rimanessi qui.}
{384}{}{Medico, cura te stesso.}
{385}{}{Ho bisogno di un po' di cure, Lenny.}
{386}{}{Vorrei che tu curassi uno dei nostri amici.}
{387}{}{Vorrei che tu ci curassi tutti.}
{388}{}{Come andiamo, vecchio mio?}
{389}{}{Per adesso non mi serve nient'altro da te, Lenny.}
{400}{}{V'vuoi che c'combatta in modo d'diverso?}
{401}{}{Vorrei che tu ti posizionassi ad una distanza diversa.}
{402}{}{Vorrei che tu usassi la tua arma migliore.}
{403}{}{Vorrei che tu indossassi la tua armatura migliore.}
{404}{}{Vorrei che tu combattessi in modo diverso.}
{405}{}{Nulla.}
{410}{}{Q'quanto distante vuoi che mi m'metta? Sai che e' difficile per me s'starti dietro.}
{411}{}{Voglio che tu rimanga a poca distanza da me.}
{412}{}{Voglio che tu rimanga ad una distanza intermedia.}
{413}{}{Voglio che tu stia molto distante.}
{414}{}{Voglio che tu vada avanti in esplorazione.}
{415}{}{Nulla.}
{420}{}{C'cosa vuoi che f'faccia?}
{421}{}{Tieniti sulla difensiva, per adesso.}
{422}{}{Combatti pure normalmente.}
{423}{}{Combatti in maniera aggressiva.}
{424}{}{Nulla.}
{430}{}{Immagino che n'non si finisca mai d'di imparare... }
{431}{}{P'per qualche r'ragione non credo di aver a'afferrato il c'concetto.}
{432}{}{Okay.}
{440}{}{Oh, Okay. Aspettero' qu'qui finche' non sarai t'tornato. D'dammi la possibilita' di r'riposare le mie articolazioni d'doloranti.}
{441}{}{Fallo pure, Lenny. Ci vediamo.}
{442}{}{Dovresti aspettarmi qui; oh, e un'altra cosa...}
{443}{}{Nulla.}
{450}{}{D'devo p'prendere una p'pistola piu' g'grossa.}
{451}{}{Usa la tua arma migliore, Lenny.}
{461}{}{Indossa la tua armatura migliore, Lenny.}
{462}{}{Lenny, dopo che avrai indossato la tua armatura migliore, ci sarebbe qualcos'altro che vorrei tu facessi per me.}
{463}{}{Nulla.}
{470}{}{E' una b'buona idea. Mi s'stavo appunto domandando quando c'ci saremmo fermati per f'farlo. Mi fa p'proprio male.}
{471}{}{L'lascia che d'dia un'o'occhiata alle tue f'ferite.}
{472}{}{Sembra p'proprio che qualcuno abbia bisogno di essere r'rimesso a posto.}
{473}{}{Curati pure.}
{474}{}{Curati. Poi vorrei che tu facessi un'altra cosa...}
{475}{}{Curami, per favore.}
{476}{}{Curami. Poi vorrei che tu facessi un'altra cosa...}
{477}{}{Curaci, per favore.}
{478}{}{Curaci. Poi vorrei che tu facessi un'altra cosa...}
{479}{}{Nulla.}
{480}{}{N'non p'posso f'farlo. Non sono il t'tipo giusto per fare l'esploratore.}
{481}{}{Oh, okay. Non importa.}
{490}{}{Ti s'staro' a'appicciato.}
{491}{}{Adesso stammi vicino, Lenny.}
{492}{}{Stammi vicino. Vorrei anche che tu facessi qualcos'altro, per me...}
{493}{}{Nulla.}
{500}{}{Immagino che tu non voglia f'farci d'diventare un bersaglio t'troppo facile, eh?}
{501}{}{Non venire troppo vicino, Lenny. Voglio che facciano fatica a colpirci.}
{502}{}{Non avvicinarti troppo. Vorrei anche che tu facessi qualcos'altro, per me...}
{503}{}{Nulla.}
{510}{}{Okay, me ne s'staro' un p'pochino in disparte. S'sembra che i nemici cerchino di uccidere t'te, p'principalmente.}
{511}{}{Voglio che tu rimanga lontano per la tua incolumita'. Non ha assolutamente niente a che fare con il tuo odore.}
{512}{}{Prima di dividerci vorrei che tu facessi qualcosa per me.}
{513}{}{Nulla.}
{520}{}{N'nel corso degli a'anni ho imparato abbastanza b'bene a prendermi c'cura di me s'stesso.}
{521}{}{Nell'eventualita' di uno scontro armato, vorrei che tu fossi prudente.}
{522}{}{Voglio essere sicuro che non ti succeda nulla. Diamine, dopotutto sei un reperto archeologico. E un'altra cosa...}
{523}{}{Nulla.}
{530}{}{C'e' un solo m'modo di farlo.}
{531}{}{Combatti semplicemente come fai di solito e dovremmo essere a posto.}
{532}{}{Rilassati un po' e combatti normalmente. Un'altra cosa...}
{533}{}{Nulla.}
{540}{}{N'non p'posso farlo. Il s'solo combattere e' gia' uno s'sforzo quasi insopportabile per queste v'vecchie o'ossa.}
{541}{}{OK. Non importa.}
{1000}{}{C'cosa v'vuoi che f'faccia?}
{1100}{}{S'sto bene.}
{1200}{}{Ho una p'piccola f'ferita, ma credo di poter r'resistere.}
{1300}{}{E' una b'buona idea. Mi s'stavo appunto domandando quando c'ci saremmo fermati per f'farlo. Mi fa p'proprio male.}
{1400}{}{Ho un b'bisogno immediato di cure, oppure m'moriro'.}
{1500}{}{Oh, Okay. Aspettero' qu'qui finche' non sarai t'tornato. D'dammi la possibilita' di r'riposare le mie articolazioni d'doloranti.}
{1600}{}{Okay.}
{1700}{}{Ti s'staro' a'appicciato.}
{1800}{}{Immagino che tu non voglia f'farci d'diventare un bersaglio t'troppo facile, eh?}
{1900}{}{Okay, me ne s'staro' un p'pochino in disparte. S'sembra che i nemici cerchino di uccidere t'te, p'principalmente.}
{2000}{}{Ci s'sono gia' cosi' tante p'persone con te. N'non hai bisogno del mio a'aiuto. B'buona fortuna.}
{2100}{}{Non avrei mai p'pensato di vivere abbastanza da vedere il g'giorno in cui mi sarei vergognato di partecipare alle tue a'azioni. Tu d'disonori la m'memoria dell'Abitante del Vault. B’dee-ya, b’dee-ya, addio.}
{2200}{}{Non ero s'sicuro che saresti t'tornato.}
{2300}{}{P'perche' hai sempre c'cosi' fretta?}
{2301}{}{Oh, scusa. Mi tolgo di mezzo.}
{2302}{}{Fretta, fretta, fretta. OK, calmati, mi sposto. Scusa, non avevo intenzione di bloccarti la strada.}
{2303}{}{Mi spiace, non posso muovermi piu' velocemente. Mi tocchera' spostarmi, allora.}
{2304}{}{Oh, okay, mi spostero' barcollando.}
{2305}{}{Mi barcollero' qui, allora.}
{2306}{}{Non ho intenzione di esserti d'intralcio.}
{2307}{}{Oh, scusa.}
{3000}{}{Troppe brutte cose accadono intorno a te. Me ne vado prima che qualcosa accada anche a me.}
{3001}{}{Non aiutero' un assassino di bambini. Addio.}
{3002}{}{La tua sete di sangue mi spaventa. Non ti seguiro' piu'.}
{3003}{}{Non voglio avere niente a che fare con uno schiavista. Addio.}
{3004}{}{Sei un traditore! Hai distrutto la nostra centrale. Non ti aiutero'.}
{3005}{}{N'non voglio avere n'niente a che fare con t'te.}
{4000}{}{Beh, okay, ma di c'certo non mi va l'idea di essere l'lasciato qui tutto solo.}
{4001}{}{D'accordo, se tu p'pensi che sia davvero una b'buona idea.}
{4002}{}{Beh, non mi piace usare d'delle armi a meno che non ci sia c'costretto, ma immagino di sapere usare un coltello, credo. Posso usare una pistola, o almeno un tempo ne ero c'capace. Se proprio devo, credo di essere in grado di maneggiare una mitraglietta. Se solo non fossero cosi' rumorose. Sono un d'dottore, non un guerriero.}
{4003}{}{Gosh, spero di non averne bisogno.}
{4004}{}{Well, I don't like to use weapons unless I really have to, but I suppose I could use a knife, I think. I can use a spear, at least I used to be able to. If I really had to, I think I could handle a rifle. If only they weren't so loud. I'm a healer, not a fighter.}
{5000}{}{Credo di p'poter avere un arto r'rotto.}
{5001}{}{Credo di p'poter essere i'irradiato.}
{5002}{}{Credo di p'poter essere a'avvelenato.}
{5100}{}{I'm f'feeling a b'bit warm now.}
{5101}{}{That's b'better.}
{6000}{}{I need a professional opinion, Lenny. What do you know about managing a heart condition?}
{6001}{}{Can you tell me anything about these pills I found, Doc?}
{6010}{}{What seems to be the t'trouble? Your t'ticker ain't g'givin' out on you now, is it?}
{6011}{}{No, I was actually wondering if there was anything we could do for Cassidy.}
{6012}{}{No. I'm going to murder an infirmed old man and I was trying to come up with something more creative than sneaking up and popping a paper bag.}
{6013}{}{Just chalk it up to academic curiosity, I guess.}
{6020}{}{Heh. No need to get t'tetchy, now.}
{6021}{}{Well, mostly, it's just c'common sense stuff. Eatin' right, steerin' c'clear of the harder c'chems, that sorta thing. K'keepin' stress to a m'minimum. B'basically, livin' m'more like an old l'lady, and less like... well, us. Heh. O'course, the b'best thing you could d'do would probably be to t'tamp it down with some c'cardiac regulators, m'maybe some v'vasodilators.}
{6022}{}{Cardiac what now?}
{6023}{}{Hmm. Heart pills.}
{6030}{}{Let's see, now... (Lenny mutters to himself as he reads over the label.)}
{6040}{}{Heart pills. I guess what they're p'puttin' out in Vault City and NCR these d'days ain't much different than w'what we were usin' b'back before the w'war. Strong m'medicine. G'get a fella on that stuff, he'd have the h'heart of a m'mutant m'marathon runner. Heck, if he minded his d'doc and took 'em r'regular-like, he could probably live on hot b'buttered chems and n'not have to worry about it skippin' a s'single b'beat. Uh, n'not that I'd recommend that sort o' thing, of course. D'doctors orders are always supposed to be c'clean livin' and p'plenty of r'roughage, right?}
{6041}{}{Uh, right. Thanks, Lenny. Let me ask you about something else.}
{6042}{}{Are they dangerous at all? Any side-effects to look out for?}
{6043}{}{Do you think these could help Cassidy?}
{6050}{}{They could be j'just the thing, now that you m'mention it. In fact, I think they w'would be. He'd hafta be careful about a c'coupla' things, though.}
{6051}{}{Ad esempio?}
{6052}{}{I knew there'd be a catch.}
{6060}{}{Nothin' that'd be likely to c'come up t'too often. They've been known to c'cause dizziness. And y'you shouldn't t'take 'em with g'grapefruit juice, though I d'don't think that's gonna be m'much of a p'problem, these days. Unless that's what those l'lumpy g'green things are supposed to be. Hmmm... (Lenny puts a hand to his chin and stares off into space).}
{6061}{}{Lenny?}
{6070}{}{S'sorry. Oh! One more b'big one. Unless you're l'lookin' to meet a l'less-than-d'dignified end, you *do not* want to g'go mixin' those things with N'new Reno p'pep pills.}
{6071}{}{Pep... pills?}
{6072}{}{Bad reaction, then?}
{6080}{}{Ayup. Y'know, for when your l'little t'trooper won't st'stand at attention? T'technical n'name for 'em was "PDE-5 inhibitors" but t'times bein' what they are, and N'new Reno bein' what IT is... Anywho, where was I?}
{6081}{}{Ayup. Y'know, for when a man's l'little t'trooper won't st'stand at attention? T'technical n'name for 'em was "PDE-5 inhibitors" but t'times bein' what they are, and N'new Reno bein' what IT is... Anywho, where was I?}
{6082}{}{Oh, yeah. You g'get those two into your s'system together, and KER-BLAM! Your heart'll explode like a b'blood s'sausage. I remember d'doin' p'post-mortems on m'more than one poor g'geezer who was t'too b'busy sowing his oats to r'read a w'warning label.}
{6083}{}{Blood Sausage?}
{6084}{}{Huh. Good to know. Thanks a lot, Lenny.}
{6090}{}{Oh. Heh. Musta b'been a little before your t'time. Sorry. Anything else I can d'do for you?}
{6091}{}{Well, since you asked...}
{6092}{}{Nope, that'll do. Thanks, Lenny.}
