{100}{}{Vedi un umano dall'aria triste.}
{101}{}{Vedi Bitorzolo, l'amico e assistente di Skeeter.}
{102}{}{Vedi un umano molto magro, con gli occhi semichiusi e l'aria triste.}
{110}{}{Sei ridotto peggio di me. Povero idiota.}
{111}{}{Non ho tempo da perdere con gli idioti.}
{112}{}{Non sei molto piu' intelligente dei brahmin cui faccio la guardia.}
{113}{}{Non hai tutte le rotelle a posto, vero?}
{114}{}{Per Dio, sei piu' stupido di quanto pensassi.}
{120}{}{Ehila'. Mi chiamo Bitorzolo.}
{121}{}{E' un nome piuttosto insolito. Come mai ti chiami cosi'?}
{122}{}{Di che cosa ti occupi?}
{123}{}{Davvero carino... Bitorzolo. Uh, adesso devo andare.}
{130}{}{Beh, il mio nome vero e' John -- ma tutti qui mi chiamano Bitorzolo.}
{131}{}{Perche' proprio Bitorzolo?}
{132}{}{Beh, chi puo' biasimarli? Addio.}
{140}{}{Ehila'. Hai mai notato che ogni brahmin e' dotato di una sua propria personalita'? Beh, se ti capitera' di osservarli tanto a lungo quanto ho fatto io, te ne accorgerai di certo. }
{141}{}{Yup. Veramente incredibile. Davvero.}
{142}{}{Mu' mu'.}
{143}{}{Di che cosa ti occupi?}
{144}{}{Davvero interessante. Chi sei?}
{145}{}{Mi interessano alcune cose.}
{146}{}{Felice di averti conosciuto. Ci vediamo.}
{150}{}{Ehila'. Probabilmente sei qui per vedere Skeeter. Io non mi occupo di cose tecnologiche, sono qui solo per dargli una mano.}
{151}{}{Keeter. Heh, heh, heh.}
{152}{}{Chi sei?}
{153}{}{Di che cosa ti occupi?}
{154}{}{Ho qualche domanda per te.}
{155}{}{Oh, okay. Andro' a parlare con Skeeter, allora. Grazie.}
{160}{}{Ehila'. Dal momento che ti sei gia' invitato da solo ad entrare... cosa posso fare per te?}
{161}{}{Me fame.}
{162}{}{Uh, dov'e' Skeeter?}
{163}{}{Ho qualche domanda per te.}
{164}{}{Oh, scusa. Non avevo intenzione di essere scortese. Ci vediamo.}
{170}{}{Faccio la guardia ai brahmin o aiuto Skeeter nella sua officina.}
{171}{}{Chi e' Skeeter?}
{172}{}{Lascia che ti chieda qualcos'altro.}
{173}{}{Era tutto quello che mi serviva sapere, per il momento. Ci vediamo, Bitorzolo.}
{180}{}{Beh, e' una specie di presa in giro. Vedi, di solito i ghoul chiamano le persone come te e me "pelle-liscia". Ma i pelle-liscia di Vault City mi trattavano cosi' male che gli abitanti di qui pensano che io debba essere piu' bitorzoluto degli altri, per meritarmi un simile trattamento.}
{181}{}{Perche' ti trattavano male, a Vault City?}
{182}{}{Questo spiega molte cose. Ci vediamo.}
{190}{}{Beh, Skeeter e' una specie di meccanico. Smonta praticamente ogni cosa gli venga portata. Riesce anche a rimettere insieme la maggior parte di queste cose, o prima o dopo. Alcune cose funzionano anche meglio di quanto non facessero prima.}
{191}{}{Dove posso trovare Skeeter?}
{192}{}{Interessante. Lascia che ti chieda qualcos'altro.}
{193}{}{Credo sia tutto, per ora. Arrivederci.}
{200}{}{Beh, dicevano che non ero abbastanza umano per loro. Sono resistente alle radiazioni... perfetto per questo mondo. Ma a loro non piaceva. Mi trattavano come spazzatura.}
{201}{}{Davvero?}
{210}{}{Un giorno non ce l'ho piu' fatta. Decisi che morire nelle Lande sarebbe stato meglio che vivere con quegli stronzi di Vault City.}
{211}{}{Come mai sei finito qui, allora?}
{220}{}{Beh, una carovana proveniente da Broken Hills mi ha trovato e mi ha portato qui. Vivo a Gecko da allora. Una caratteristica dei ghoul di qui e' che a loro interessa soprattutto che tipo di persona sei dentro. E' come una grande famiglia.}
{221}{}{Broken Hills? E dove si trova?}
{222}{}{Interessante. Lascia che ti chieda qualcos'altro, pero'.}
{223}{}{Sono felice per te. Ci vediamo.}
{224}{}{Una famiglia di mostri. Non credo di voler sentire altro da te. Addio.}
{230}{}{Broken Hills e' il posto dal quale proviene tutto l'uranio che ci serve per il nostro reattore nucleare. Da quel che ho capito, sono i mutanti ad estrarre l'uranio. Ma lasciano che siano gli umani ad occuparsi degli scambi commerciali.}
{231}{}{Perche' hanno affidato il commercio agli umani?}
{240}{}{Cosa vuoi sapere?}
{241}{}{Sei davvero curioso, sai? Beh, okay. Che cosa vuoi sapere?}
{242}{}{E adesso cosa vuoi sapere?}
{243}{}{Cosa sono tutti quei rifiuti nel cortile?}
{244}{}{Di che cosa ti occupi?}
{245}{}{Chi e' Skeeter?}
{246}{}{E' successo niente di strano, da queste parti?}
{250}{}{Beh, il motivo e' che vendono l'uranio anche a Vault City. Gli abitanti di Vault City trattano come fosse un lebbroso chiunque non sia un umano "puro". E cosi' Broken Hills si affida a mercanti umani. Dovrebbe trattarsi di un tipo di nome Chad, credo.}
{251}{}{Chad, eh? Lo terro' a mente. Lascia che ti chieda qualcos'altro.}
{252}{}{Credo sia tutto, per ora. Arrivederci.}
{260}{}{Beh, una parte di questi rifiuti si e' accumulata durante la costruzione del reattore... prima della guerra. Il resto di questa roba? Non saprei dirtelo. Skeeter raccoglie qualsiasi cosa.}
{261}{}{Chi e' Skeeter?}
{262}{}{Interessante. Ho un'altra domanda da farti.}
{263}{}{Credo sia tutto, per il momento. Ci vediamo.}
{270}{}{E' proprio qui. Apri gli occhi e guardati un po' attorno. Tsk.}
{271}{}{Beh, di solito Skeeter e' nella sua officina. Subito a sud del reattore in costruzione. Non riesco quasi mai a farlo uscire da li'.}
{272}{}{Oh, grazie. Ci vediamo.}
{273}{}{Non so dove Skeeter sia stato, di recente.}
{280}{}{Beh, di solito mi faccio gli affari miei, ma a volte, a notte fonda, mi pare di sentire delle cose.}
{281}{}{Senti delle cose? Ad esempio?}
{282}{}{Aw, dai. A me puoi dirlo cos'hai sentito. Non lo diro' a nessuno.}
{283}{}{Anch'io, ma credo siano solo voci all'interno della mia testa.}
{290}{}{Beh, non ne sono sicuro, eh. Ma credo di aver sentito delle persone, o almeno: credo che fossero delle persone. Persone che andavano e venivano dal pozzo del reattore a tarda sera.}
{291}{}{Delle persone? Tutte le notti?}
{292}{}{Interessante. Lascia che ti chieda qualcos'altro.}
{300}{}{Non saprei dirlo. Si potrebbe pensare che io sia pazzo. Probabilmente e' solo il vento che passa tra i rifiuti.}
{301}{}{Ti ho gia' detto che non ho sentito nulla. Smettila di seccarmi con questa storia.}
{302}{}{Okay. Lascia che ti chieda qualcos'altro, allora.}
{310}{}{(Ti guarda dritto negli occhi) Senti delle voci nella testa? Ti dicono forse che tu sei il migliore di tutti? Ti dicono forse che un giorno la gente si inchinera' davanti alla tua grandezza? (sorride e annuisce)}
{311}{}{Uh, no. Veramente no.}
{312}{}{Uh, certo. Certo che le sento. Non succede a tutti?}
{320}{}{Bene. Cominciavo a preoccuparmi.}
{321}{}{Beh, grazie del pensiero. Lascia che ti faccia qualche domanda.}
{322}{}{Uh, certo. Beh, adesso credo proprio di dover andare. Ci vediamo.}
{330}{}{La prima volta che ti ho visto gia' sospettavo che tu potessi essere un tipo del genere, ma non ne ero sicuro. Adesso sparisci, maledetto svitato!}
{331}{}{Uh, certo. Come no? Addio.}
{332}{}{Beh, uno di noi e' uno svitato -- pero' credo che tu abbia fatto un po' di confusione.}
{340}{}{Beh, non so se fossero persone o cos'altro, ma di solito le sentivo una notte si' e una no. Rumori che andavano e venivano dal pozzo del reattore. Non so cosa stia succedendo, ma non voglio nemmeno saperlo.}
{341}{}{Credo che tu non abbia tutti i torti. Meglio non sapere cosa ci potrebbe essere, la' sotto.}
{342}{}{Grazie per le informazioni. Ci vediamo.}
{343}{}{Ma il pozzo del reattore non e' troppo radioattivo per permettere a qualcuno di vivere al suo interno?}
{350}{}{No, quella parte del reattore non era stata completata quando scoppio' la guerra.}
{351}{}{Oh, capisco. Hmm, parliamo di qualcos'altro, allora.}
