{100}{}{Vedi un mutante grosso e robusto con uno sguardo risoluto.}
{101}{}{Vedi una delle guardie della banca: un mutante grande e severo.}
{102}{}{Vedi una guardia attenta e ben armata; un mutante che impugna un'arma dall'aspetto piuttosto cattivo.}
{103}{}{Posso aiutarti?}
{104}{}{Agga agga!}
{105}{}{Me in edificio! Oooh!}
{106}{}{Stavo solo dando un'occhiata in giro.}
{107}{}{Err... no, niente. Davvero.}
{108}{}{Sono qui per parlare con i prigionieri.}
{109}{}{Avete mai pensato che forse state trattenendo i vostri prigionieri illegalmente?}
{110}{}{Oh, splendido, un altro della tua risma. Per favore, vattene.}
{111}{}{Aaaaahn!}
{112}{}{O-kay!}
{113}{}{Certo... beh, va' da qualche altra parte. Ci sono dei criminali qui dentro. Via.}
{114}{}{Oh. D'accordo.}
{115}{}{Possiamo aiutare chiunque venga qui per una ragione. Se non puoi essere aiutato, allora devi andartene. Vattene prima che ti aiutiamo noi.}
{116}{}{Mi state obbligando?}
{117}{}{Capito.}
{118}{}{Sei qui per parlare con loro, eh? Beh, puoi parlare con noi. Cos'hai da dirci?}
{119}{}{Avete mai considerato il fatto che li state trattenendo illegalmente?}
{120}{}{Assaggia questo, mutante!}
{121}{}{Niente. Adesso devo andare.}
{122}{}{Err... che cosa vuoi dire?}
{123}{}{Quello che voglio dire e' che non hanno commesso alcun crimine se non quello di aver espresso le loro idee. Hanno solamente parlato male dei mutanti. Non sto dicendo che non commetteranno alcun reato... ti piacerebbe essere incarcerato per un crimine che POTRESTI commettere, ma che di fatto NON hai commesso?}
{124}{}{Il potere crea le leggi. Io ho quel potere. Proprio qui.}
{125}{}{No, non mi piacerebbe, ma loro sono chiaramente pericolosi.}
{126}{}{Finche' non commettono reati, non possono essere giudicati colpevoli. Finche' non rivelano apertamente i loro progetti e iniziano a realizzare il reato, non sono colpevoli. Giusto?}
{127}{}{Pericolosi? Io sono pericoloso. Tu sei pericoloso. Eppure non siamo in cella.}
{128}{}{E allora?}
{129}{}{Ma... ma... d'accordo. Sono liberi. Ricorda che la responsbilita' e' tua. Spero solo che tu non ti sia sbagliato. Ecco la chiave.}
{130}{}{Questo e' tutto cio' che volevo. Ottimo. Grazie. Arrivederci.}
{131}{}{Certo, ma forse sarebbe meglio se lo fossimo. Al momento, loro lo sono. E ci rimarranno finche' qualcuno non potra' darmi un motivo migliore per farli uscire. Adesso... vattene.}
{132}{}{No.}
{133}{}{Okay.}
{134}{}{Percio' rimarranno in cella, per il momento. Dobbiamo proteggere la societa'. Adesso... vattene.}
{135}{}{No.}
{136}{}{Okay.}
{137}{}{Tu! Cosa diavolo stai facendo? Esci immediatamente da qui!}
{138}{}{Metti via quelle armi, amico. E subito.}
{139}{}{You again? Do you need something?}
{140}{}{Stavo solo dando un'occhiata in giro.}
{141}{}{Err... no, niente. Davvero.}
{142}{}{Sono qui per parlare con i prigionieri.}
{143}{}{Avete mai pensato che forse state trattenendo i vostri prigionieri illegalmente?}
{144}{}{Non dovresti gironzolare da queste parti. Vattene.}
{145}{}{Se mai riusciro' a scoprire dove sono scappati quei dannati prigionieri, le conseguenze saranno terribili!}
{150}{}{But... but... all right. They're out. You're accountable. I just hope you're right. Here is the... Hey, where'd my key go!? Shit, Marcus is gonna have my head if I lost that thing. Sorry, I gotta go.}
{151}{}{Okay.}
{152}{}{I actually took that key from you. What are going to do about it?}
