{100}{}{Vedi un vecchio con la barba incolta e un grosso naso rosso.}
{101}{}{Vedi Whiskey Bob.}
{110}{}{Ehila', il mio nome e' Whiskey Bob. Qual e' il tuo, compare?}
{111}{}{Che mi venga un colpo se non sei carina. Mi chiamo Bob, Whiskey Bob -- e tu?}
{112}{}{Whicky Gob? Zug, zug?}
{113}{}{Naso luccicoso (heh, heh)}
{114}{}{Me }
{115}{}{Vavia}
{120}{}{Non sei il tipo piu' sveglio sulla piazza, vero? Beh, e' stato comunque bello parlare con te. Ci vediamo.}
{121}{}{Dolcezza, mi spezzi il cuore ogni volta che apri bocca. Magari prima o poi potrei portarti a Trapper Town e mostrarti le mie acqueforti (heh, heh). Ciao, bambola.}
{130}{}{Beh, signore, forse ci rivedremo ancora da queste parti. Ciao.}
{131}{}{Beh, spero di rivederti ancora da queste parti, bambolina. Ciao.}
{140}{}{Humph, non ti voglio come compagno di bevute. Vai a farti fottere.}
{141}{}{Humph, preferisco andare alla Bath House di Sally piuttosto che spendere del tempo con te. Va' a quel paese.}
{150}{}{Ehila' straniero, il mio nome e' Whiskey Bob. Qual e' il tuo?}
{151}{}{Il mio nome e' }
{152}{}{. Felice di conoscerti, Whiskey Bob.}
{153}{}{Sono }
{154}{}{. Cosa succede qui in citta'?}
{155}{}{Non credo che tu abbia bisogno di conoscere il mio nome.}
{160}{}{E' sempre bello trovare un altro compagno di bevute. Mi vuoi offrire un bicchierino? Parlare mi fa venire una sete...}
{161}{}{Certo, Bob. Nessun problema.}
{162}{}{Non posso permettermelo, al momento.}
{163}{}{Non ho voglia di offrirti da bere, Whiskey Bob.}
{164}{}{Con un soprannome come il tuo, Whiskey Bob, forse dovresti essere tu quello che offre da bere.}
{170}{}{Grazie per il drink, compare. Ora che mi son bagnato il gorgozzule, sento di poterti parlare del mio piccolo problema. Ehi -- non e' che forse tu puoi aiutarmi?}
{171}{}{Beh, al momento sono piuttosto occupato. Non credo di poterti aiutare.}
{172}{}{Come posso aiutarti?}
{173}{}{Se non ci vuole troppo tempo, credo di poterti aiutare. Ad un prezzo, naturalmente.}
{174}{}{Forse potrei aiutarti, se non e' troppo pericoloso.}
{175}{}{E' successo qualcosa di strano in citta', ultimamente?}
{180}{}{Sembra proprio che le tue tasche siano piu' vuote del mio bicchiere. Non hai abbastanza soldi per offrire da bere al vecchio Bob.}
{181}{}{[AVANTI]}
{190}{}{Beh, vedi, ho una piccola attivita' e ho bisogno di un po' d'aiuto per starle dietro. Ho una distilleria illegale fuori citta' che ha bisogno di essere rifornita di legna abbastanza spesso. Dato che un gecko mi ha morso una gamba, non credo di riuscire a trascinarmi fino al posto in cui si trova la distilleria prima che finisca la legna. Se ti dico dove si trova, la riempiresti di legna per me? Sono pronto a darti 50$.}
{191}{}{Non sembra male -- dimmi di piu'.}
{192}{}{Non credo di volerlo fare. Mi spiace, Whiskey Bob.}
{200}{}{Allora: non ti servira' molto tempo e ti assicuro che non e' pericoloso. Vuoi saperne di piu' o no?}
{201}{}{OK, continua.}
{202}{}{Credo di aver sentito abbastanza. Ci vediamo.}
{210}{}{Mi sembra giusto. Sei un tipo sveglio, non c'e' dubbio. Eccoti qualcosa da bere. Adesso, in cambio, devi ascoltare il mio piccolo problema.}
{220}{}{Tutto quello che devi fare e' trovare una piccola capanna subito a sud della citta'. Entra e getta un po' di legna nel distillatore. Poi torna qui e ti daro' i tuoi soldi. Ma bisogna farlo entro domani, o la mia produzione giornaliera di "elisir" andra' a male.}
{221}{}{Sembra abbastanza facile. OK, lo faro'.}
{222}{}{Non ho voglia di aiutarti. Mi spiace, Bob.}
{223}{}{50$ non si avvicinano nemmeno lontanamente alla paga minima per un lavoro come questo.}
{230}{}{Lo farai? Benissimo. Ricorda, devi farlo presto o il mio "elisir" andra' a male. Grazie mille. Ci vediamo qui. A dopo.}
{231}{}{Nessun problema, Bob. Ci vediamo in giornata. }
{232}{}{Felice di aiutarti. Ma prima vorrei che tu mi dicessi cos'e' successo in citta' ultimamente.}
{240}{}{Beh, sei davvero abile nel contrattatare, non c'e' dubbio. OK, ti offro 55$. Lo farai?}
{241}{}{Ci hai provato, ma 50$ e' quanto vale questo lavoro per me. Diamine, non posso permettermi di pagarti un dollaro di piu'.}
{242}{}{OK, lo faro'.}
{243}{}{Non ho intenzione di farlo per quei soldi. Il mio tempo vale molto di piu'.}
{250}{}{Ehila', compare. Sei tornato a trovare Whiskey Bob, eh? Sei pronto a parlare di bevute, di affari e di amenita' simili?}
{251}{}{Ehila', ragazza mia. Vuoi parlare ancora con Whiskey Bob di liquori, di affari e amenita' simili? Puoi sederti sulle mie ginocchia, se vuoi... (heh, heh) Sto scherzando.}
{252}{}{Certo, Bob - parliamo di bevute e di affari.}
{253}{}{Credo di averne avuto abbastanza l'ultima volta.}
{260}{}{Ti sei occupato del distillatore? Nah, non credo che tu l'abbia ancora fatto. Torna quando avrai messo la legna in quella dannata caldaia.}
{270}{}{Qualcuno mi ha sfasciato il distillatore! E tu sei l'unica persona alla quale ne ho parlato. Cavoli, se solo fossi un po' piu' giovane e pieno di energie, non avrei problemi a darti una lezione. Sparisci dalla mia vista, doppiogiochista che non sei altro!}
{280}{}{Beh, grazie per aver rifornito di legna il distillatore. Eccoti i tuoi 50$. Hai qualche domanda alla quale potrei rispondere?}
{281}{}{Grazie. Adesso non avro' bisogno di zoppicare fin li' -- anche se mi e' costato 55$. Eccoti i tuoi soldi. Hai qualche domanda alla quale potrei rispondere?}
{282}{}{Si'. Dimmi cos'e' successo in citta' negli ultimi tempi.}
{283}{}{No grazie, Bob. Credo di sapere gia' tutto quello che mi serve.}
{290}{}{All sorts of things going on hereabouts lately. We've got }
{291}{}{Parlami degli attacchi contro i brahmin.}
{292}{}{Dimmi tutto quello che sai a proposito degli spiriti vaganti.}
{293}{}{Ratti giganteschi? *Devo* saperne di piu'.}
{294}{}{Un dente? Che tipo di dente?}
{295}{}{Persone scomparse? Dimmi di piu'.}
{296}{}{Un'altra cosa... Hai mai sentito parlare di un qualcosa chiamato Kit di Creazione del Giardino dell'Eden?}
{297}{}{Non credo di aver bisogno di sentire queste cose, per adesso.}
{298}{}{Ma certo, Bob... allora lascia che io ti racconti del pesce grande quanto me che ho pescato in un barile d'acqua piovana.}
{310}{}{Grazie per avermi dato una mano con il distillatore. Dovrei essere in grado di farcela da solo, quando la mia gamba sara' messa un po' meglio. Hai delle domande da fare a questo vecchio segugio da bar?}
{311}{}{Beh, stavo pensando ad alcune voci che ho sentito in citta'.}
{312}{}{Per il momento non credo di aver bisogno di altre informazioni, Bob.}
{320}{}{Si dice che delle creature che assomigliano ad insetti giganti umanoidi, con corazza e tutto il resto, aggrediscano nottetempo i brahmin. Tutto cio' che rimane sono i corpi squartati e orribilmente mutilati dei brahmin.}
{321}{}{Orribile.}
{330}{}{L'uomo-insetto e' stato visto da diverse persone, ma quello che l'ha visto meglio e' stato Torr, il ragazzo della Buckner. Cio' che ha visto lo ha spaventato cosi' tanto da fargli quasi perdere il senno... e non e' che prima il poveretto fosse molto dotato, da quel punto di vista.}
{331}{}{Incredibile! Lascia che ti chieda un'altra cosa.}
{332}{}{Credo sia tutto quello che mi serve sentire per adesso, arrivederci.}
{340}{}{C'e' un canyon poco a ovest della citta' nel quale e' stato visto un enorme bagliore, un paio di mesi fa. Da allora, di tanto in tanto, si sentono degli orribili lamenti provenire dal Canyon. I brahmin che si sono avventurati la' dentro non sono piu' tornati. Sono tutti troppo spaventati per avvicinarsi.}
{341}{}{Si', e' sicuramente un segno della presenza di fantasmi. Se solo aveste uno sciamano in gamba... Parliamo di qualcosa d'altro.}
{342}{}{Per adesso puo' bastare. Credo che meditero' per un po' alle cose che mi hai detto. Arrivederci.}
{350}{}{Beh, giu' a Trapper Town, subito ad ovest di qui, c'e' una zona che e' infestata dai ratti. Piu' ti spingi all'interno, piu' grossi diventano. In giro si dice che alla loro guida ci sia un enorme spirito-ratto. Alcuni trapper stanno pensando di abbandonare quel posto. Dicono che e' troppo pericoloso.}
{351}{}{Dei cacciatori esperti cacciati dai ratti? Sara' meglio parlare d'altro.}
{352}{}{Spaventati dai ratti. Hmm, deve trattarsi di ratti diversi da quelli che abbiamo dalle nostre parti. Ho sentito abbastanza. Arrivederci.}
{360}{}{Non un *dente*, - il *Den*. Non troverai mai un covo di feccia e malvagita' peggiore di questo posto. Ora... dov'e' che ne avevo sentito parlare? In ogni caso, e' un posto piuttosto selvaggio situato ad un paio di giorni a sud di Klamath. Laggiu', tutto puo' essere comprato ad un prezzo... persino degli schiavi. Ma devi stare molto attento quando ti trovi in quel luogo - ci sono un sacco di attaccabrighe che si portano dietro pericolose armi. Tuttavia, non credo che abbiano molto a che fare con noi; siamo troppo poveri.}
{361}{}{Credo che sarei abbastanza al sicuro in quel posto; so come cavarmela. Lascia che ti chieda qualcos'altro.}
{362}{}{Per adesso puo' bastare, Whiskey Bob. Arrivederci.}
{370}{}{Ultimamente, abbiamo avuto due casi di persone scomparse. Un mercante, chiamato Vic, specializzato in roba pre-bellica, e uno dei nostri migliori cacciatori.}
{371}{}{Dimmi di piu' riguardo al mercante chiamato... com'era? Vic?}
{372}{}{Vorrei sapere qualcosa di piu' sul cacciatore scomparso.}
{373}{}{Lascia che ti chieda qualcos'altro.}
{374}{}{Questo e' tutto quello che mi serviva sapere. Arrivederci, Whiskey Bob.}
{380}{}{Beh, Vic era un buon diavolo. Non gli piaceva molto lavorare, per cui si era specializzato in costose chincaglierie pre-belliche e andava a venderle al Den -- o addirittura le rifilava agli stupidi selvaggi spacciandole per sacre reliquie (ridacchia). Oops, senza offesa. Comunque, non lo vedo da un po'. L'ultima volta che ho avuto sue notizie, si diceva che fosse andato a sud per vendere della roba. Forse al Den.}
{381}{}{E cosa mi dici del cacciatore scomparso?}
{382}{}{Lascia che ti chieda qualcos'altro, Bob.}
{383}{}{Grazie, ho bisogno di riflettere sulle cose che mi hai detto. Arrivederci, Whiskey Bob.}
{390}{}{La persona piu' adatta a parlarti del trapper scomparso credo sia la signora Buckner. Lei e Smiley erano abbastanza intimi. Lui e' andato a nord per cercare una grotta di gecki dorati che nessuno ha mai trovato. E' successo un po' di tempo fa, ormai.}
{391}{}{Cosa mi dici del mercante scomparso?}
{392}{}{Hmm, interessante. Adesso parliamo di qualcos'altro.}
{393}{}{Per adesso puo' bastare. Arrivederci, Whiskey Bob.}
{400}{}{Speravo davvero che avresti tenuto fede alla tua promessa. Non sei andato al mio distillatore in tempo e la mia ultima "infornata" di liquore e' andata a farsi friggere! Non voglio avere piu' nulla a che fare con te e spero che nessun altro voglia averne.}
{401}{}{Ma io... io credevo di avere piu' tempo...}
{402}{}{Anche se avessi rifornito in tempo il distillatore, credo che il sapore non sarebbe stato tanto migliore.}
{403}{}{In ogni caso, il tuo liquore sa di piscio di cane.}
{404}{}{La legna non ha prodotto una fiamma della temperatura giusta per una corretta fermentazione.}
{410}{}{Non ho voglia di sentire le tue dannate scuse. Adesso sparisci dalla mia vista! Ma ti dico una cosa: prima che io muoia tutti sapranno quanto poco valore abbia la tua parola.}
{420}{}{Un Kit di Creazione del Giardino dell'Eden? Beh... penso di aver visto uno di quei cosi in una pagina di un vecchio catalogo che stavo leggendo durante una "seduta", qui dietro. Ma non ne so molto di piu', oltre a questo.}
{421}{}{Davvero? Mi piacerebbe vedere quel catalogo.}
{430}{}{Uh, (imbarazzato) ho usato quella pagina per eseguire una certa operazione, se capisci cosa intendo.}
{431}{}{Operazione? Oh, *quel* tipo di operazione. Io invece preferisco i vecchi quotidiani. Oh beh, parliamo di qualcos'altro, allora.}
{432}{}{Dannazione, credevo di esserci vicino. Credo di aver ricevuto abbastanza delusioni, per adesso. Arrivederci, Bob.}
{500}{}{Ehila', cosa posso fare per te?}
{501}{}{Cosa succede da queste parti?}
{502}{}{Nulla, grazie.}
{550}{}{Bob non sembra aver voglia di parlare con te.}
{2900}{}{Things have slowed down recently. Nothing really to tell ya.}
{2901}{}{brahmin mutilators}
{2902}{}{walking spirits}
{2903}{}{gigantical rats}
{2904}{}{missing people}
{2905}{}{. Some even say the Den's involved.}
