{100}{}{Vedi una persona che potrebbe essere un trapper.}
{101}{}{Vedi qualcuno che si sta riposando.}
{102}{}{Vedi un abitante.}
{103}{}{Vedi un lavoratore che si sta riposando.}
{104}{}{Vedi una persona che si sta gustando un drink.}
{150}{}{Sei nel locale sbagliato, eh?}
{151}{}{Non abbiamo bisogno di piantagrane, qui.}
{152}{}{Chi dice selvaggio dice danno.}
{153}{}{Fino a quando non avrai bevuto troppa acqua-di-fuoco...}
{154}{}{(mumble, mumble)…brutto muso fuori dal paese...}
{155}{}{Ecco un altro della banda dei Dunton.}
{156}{}{Cos'hai da guardare?}
{157}{}{Gira al largo.}
{158}{}{Offri a tutti un giro di bevute, straniero.}
{159}{}{Spero tu regga l'alcol.}
{160}{}{Non mi sembri un cannibale.}
{161}{}{Qui non c'e' posto per i tipi come te.}
{162}{}{Troppi stranieri ultimamente.}
{163}{}{Beh, almeno i tuoi denti non sono affilati.}
{164}{}{Possiamo scordarci la tranquillita'.}
{165}{}{Non dovresti avere un osso, infilato nel naso?}
{166}{}{(ti guarda e poi scuote la testa)}
{167}{}{(ti fa un gesto finemente volgare)}
{168}{}{Probabilmente sei tu il responsabile delle mutilazioni sui brahmin.}
{169}{}{Alcuni dei nostri cacciatori sono scomparsi; probabilmente tu sai il perche'.}
{170}{}{Ci sono degli uomini-insetto che si aggirano nei pressi della citta'.}
{171}{}{C'e' un fantasma nel canyon a est del paese.}
{172}{}{Non farti beccare dallo Spirito!}
{173}{}{Farai meglio a non rubare i nostri brahmin.}
{174}{}{Ti teniamo d'occhio.}
{201}{}{E' bello vedere facce nuove in citta'.}
{202}{}{Credo che i selvaggi non siano poi cosi' male.}
{203}{}{Offrici un giro di bevute!}
{204}{}{Salutaci Smiley, la' fuori... e anche Gimpy Jim.}
{205}{}{Potresti essere il gemello di Sulik.}
{206}{}{Hai gia' salutato Sulik?}
{207}{}{La caccia va bene, ultimamente.}
{208}{}{Credo che il tempo stia per cambiare.}
{209}{}{Ho messo giu' un bel po' di trappole a sud di qui.}
{210}{}{Se sei furbo, te ne starai lontano da quei Dunton.}
{211}{}{Se sei nervoso, prova la Bathhouse.}
{212}{}{Dirigiti a ovest per raggiungere Trapper Town, se hai bisogno di un posto dove dormire.}
{213}{}{Benvenuto, amico.}
{214}{}{Spero che la nostra citta' ti piaccia.}
{215}{}{Klamath e' un bel posto dove vivere.}
{216}{}{E' bello averti qui.}
{217}{}{(alza il boccale)}
{218}{}{(ti strizza l'occhio)}
{219}{}{Non andare in giro di notte.}
{220}{}{Ci sono degli uomini insetto nei pressi delle colline.}
{221}{}{Uno dei nostri migliori trapper e' scomparso.}
