{100}{}{Vedi una giovane donna, semplice ma ben piantata, che ha un'espressione torva sul volto.}
{101}{}{Vedi Maida Buckner, figlia della signora Buckner.}
{102}{}{Vedi una giovane donna, semplice ma ben piantata. Ti sta restituendo lo sguardo con un'espressione torva sul volto.}
{200}{}{Mi hai fatto davvero infuriare. Non voglio avere piu' niente a che fare con te. Vattene subito. Selvaggi, humph! (brontola, borbotta) ...incapaci, inutili, pigri...}
{201}{}{Sei addirittura piu' irritante di Sulik! Non ho tempo per parlare con te. Vattene.}
{202}{}{Neanch'io voglio avere nulla a che fare con te. Addio.}
{203}{}{Mi dispiace molto di averti fatta arrabbiare. E' che non conosco le vostre usanze. Stavo solo cercando di mostrarti rispetto alla maniera della mia tribu'.}
{204}{}{Gosh, sono davvero, davvero dispiaciuto. Dopotutto, sono solo un selvaggio ignorante. Potrai mai perdonarmi?}
{205}{}{Non sapevo cosa dire ad una persona cosi' attraente come te. Divento sempre nervoso quando sono vicino a una bella donna. Ti prego di accettare le mie scuse.}
{206}{}{E' solo che tu mi sembri cosi' bella e "civilizzata". Ero gelosa di te. Ti prego di perdonarmi. Ho cosi' tanto da imparare da donne come te...}
{210}{}{Ehila', il mio nome e' Maida Buckner. Aiuto mia madre nella gestione di questo locale, il Buckner. Posso aiutarti?}
{211}{}{Ungh?}
{212}{}{Me }
{213}{}{Focale? Bunker?}
{220}{}{Hmm - sembra proprio che il tuo ascensore non arrivi ai piani alti... Perche' non parli con mio fratello Torr? Ha una velocita' piu' simile alla tua. Addio.}
{230}{}{Il mio nome e' Maida Buckner; mi occupo del negozio e del bar. Non tollero che dei selvaggi facciano casino nel locale della mia famiglia. Quindi, farai meglio a stare molto attento quando ti trovi qui dentro, o finirai come Sulik. Cosa vuoi?}
{231}{}{Il mio nome e' Maida Buckner; mi occupo del negozio e del bar. Cosa desideri, amico?}
{232}{}{Ehila', carissimo amico. }
{233}{}{Come posso aiutarti?}
{234}{}{Beh, faresti meglio a comportarti in maniera piu' civile, d'ora in poi. Comunque: che cos'e' che vuoi? Come posso aiutarti?}
{235}{}{Ho qualche domanda per te.}
{236}{}{Sto cercando un posto dove riposare.}
{237}{}{Dovrei comprare delle cose.}
{238}{}{Vorrei bere qualcosa.}
{239}{}{Credo di non aver bisogno di nulla, per ora. Arrivederci.}
{240}{}{Domande, eh? Beh, allora sbrigati. Parlare con te non mi aiuta ad arrivare a fine mese.}
{241}{}{Ancora domande? Fammele, allora, e fa' in fretta.}
{242}{}{Hai mai sentito parlare di un qualcosa chiamato Kit di Creazione del Giardino dell'Eden?}
{243}{}{Parlami di Sulik.}
{244}{}{Potresti dirmi cos'e' successo ultimamente a Klamath?}
{245}{}{Che altre citta' ci sono qui vicino?}
{246}{}{Credo sia tutto, per ora. Arrivederci.}
{250}{}{Mia madre si occupa delle stanze. Dovresti parlare con lei, se ne vuoi una.}
{251}{}{Ok, grazie. Ci sarebbe qualcos'altro che vorrei sapere, pero'.}
{252}{}{Andro' a parlarne con lei, allora. Arrivederci.}
{260}{}{Vuoi barattare? Mi interessano pelli di gecko di buona qualita' e le acquisto a prezzi onesti.}
{261}{}{Vuoi comprare qualcosa? Spero che tu mi possa pagare con altre cose che non siano pelli di gecko: al momento siamo pieni di pelli.}
{262}{}{Si', vorrei fare qualche scambio.}
{263}{}{Veramente preferirei farti qualche domanda.}
{264}{}{Credo di non aver bisogno di comprare qualcosa, al momento. Arrivederci.}
{270}{}{L'unico modo che conosco per creare un Giardino dell'Eden e' con il caro, vecchio lavoro duro. E' una cosa che voi selvaggi sembra non riusciate a capire. Ma immagino che sia questa la differenza tra noi, gente civile, e voialtri.}
{271}{}{Uh, penso di si'. Parliamo di qualcos'altro, allora.}
{272}{}{Gee, credo di avere molto da imparare da voi. Un giorno, anch'io vorrei diventare una persona civile.}
{273}{}{Gente civile? Voi pensate di essere civili solo perche' vivete nelle rovine bruciate di una citta' che esisteva prima della guerra? Sara' meglio cambiare argomento...}
{274}{}{Credo di aver sentito abbastanza. Arrivederci.}
{280}{}{Bene, c'e' qualcos'altro che posso fare per te?}
{281}{}{Le pelli di gecko che ho adesso mi basteranno per un po' di tempo. Posso fare qualcos'altro per te?}
{282}{}{Veramente, ci sarebbe qualcos'altro che vorrei scambiare.}
{283}{}{Speravo tu mi facessi dei prezzi migliori. Di certo non e' a buon mercato. Parliamo di qualcos'altro.}
{284}{}{Sei una mercante tenace, ma giusta. Parliamo di qualcos'altro.}
{285}{}{E' tutto, per il momento. Arrivederci.}
{290}{}{Ci sono solo un paio di citta', qui vicino. Molto a sudest c'e' Redding, e il Den e' a qualche giorno di cammino verso sud. Ma, se fossi in te, io non andrei al Den.}
{291}{}{Perche' non dovrei andare al Den?}
{292}{}{Cosa mi sai dire delle tribu' della zona?}
{293}{}{Grazie per il consiglio. Parliamo di qualcos'altro.}
{294}{}{Questo e' tutto quello che mi serviva sapere, per il momento. Arrivederci.}
{300}{}{Beh, non ho considerato le tribu', quando mi hai chiesto di insediamenti civilizzati. Ma credo che ci sia un gruppo di selvaggi a nordovest -- e la tribu' di Sulik, molto a sud di qui.}
{301}{}{Divertente, la mia tribu' non considera le citta' pre-guerra, quando parliamo di luoghi civilizzati. Ma adesso parliamo di qualcos'altro.}
{302}{}{Oh, voi siete civili, certamente... e io non credo di voler diventare uno di voi. Parliamo di qualcos'altro.}
{303}{}{Parlami di Sulik.}
{304}{}{Che cosa mi sai dire riguardo al Den?}
{305}{}{Interessante. Lascia che ti chieda qualcos'altro, pero'.}
{310}{}{Il Den e' un brutto posto dove andare. La' i selvaggi ignoranti come te li fanno addirittura diventare degli schiavi. E' a circa una settimana a sud di qui, ma molti di quelli che ci sono andati non sono piu' tornati.}
{311}{}{Parlami delle tribu' locali.}
{312}{}{Sulik non e' tuo schiavo? Oppure lo tratti solamente come se lo fosse?}
{313}{}{Interessante. Lascia che ti chieda qualcos'altro, pero'.}
{320}{}{Sulik e' un selvaggio che lavora qui per saldare un debito che ha stupidamente contratto. Non abbiamo schiavi, qui a Klamath.}
{321}{}{Saldare un debito? Che cosa vuoi dire?}
{330}{}{Beh, vedi, una sera Sulik si e' infuriato e ha bevuto troppo. Poi, quando era bello ubriaco, ha pensato bene di sfasciarmi il locale. Ha fatto quasi 500$ di danni. E adesso mi aiuta per pagare le riparazioni.}
{331}{}{Perche' si e' infuriato a quel modo?}
{340}{}{Ha detto che aveva scoperto che sua sorella era stata rapita dagli schiavisti. Ma se vuoi saperne di piu' devi chiedere a lui. Rimarra' qui finche' non potra' pagare il resto dei danni che ha causato mentre era ubriaco.}
{341}{}{Per quanto tempo dovra' lavorare qui?}
{350}{}{Deve ancora pagarmi 350$. Se non fosse cosi' pigro e incapace, la cosa sarebbe piu' rapida. Non se ne andra' di qui finche non avra' saldato completamente il suo debito.}
{351}{}{Sono un sacco di soldi. Credo che rimarra' qui per molto tempo...}
{360}{}{Well, he may be slow, but he does sort of grow on you after a while. (looks away wistfully)...
(flustered) Now that's enough jaw flapping; do you need anything else?}
{361}{}{Vorrei sapere delle altre cose.}
{362}{}{E se qualcun altro volesse pagare i danni di Sulik?}
{363}{}{E' tutto, per il momento. Arrivederci.}
{370}{}{Non so proprio perche' qualcuno dovrebbe voler saldare il suo debito, ma si puo' fare. Il conto e' di 350$. Ma io non lo farei -- si caccerebbe di nuovo nei guai.}
{371}{}{Non mi piace che sia costretto a rimanere qui con una bigotta come te. Voglio saldare il debito per lui.}
{372}{}{Beh, sono sicuro che non se la passi male a lavorare per voi, ma vorrei comunque pagare i suoi danni. Penso che nessuno dovrebbe essere imprigionato come lui.}
{373}{}{Credo tu abbia ragione. E comunque non ho cosi' tanti soldi da spendere. Arrivederci.}
{380}{}{Beh, okay, allora. Se vuoi davvero pagare per i danni che ha fatto... immagino che sia una sorta di solidarieta' tra voi gente di tribu'.}
{381}{}{Si', voglio pagare. Ho abbastanza denaro per risarcirvi dei danni che ha provocato.}
{382}{}{Forse sono troppi soldi. Dopotutto non credo di voler pagare per i danni che ha fatto. Arrivederci.}
{390}{}{Devi essere matto. Saro' davvero felice quando quel dannato (sob) selvaggio (sob) se ne sara' andato (sob) da qui. (sob) }
{391}{}{(sob) Mi pare uno scambio equo: un fratello stupido per uno stupido (sob) selvaggio. Non mi manchera' per niente.}
{392}{}{Beh, per certi versi credo che a Sulik potrebbe mancare lo stare qui. Ma sono sicuro che torneremo a farvi visita, qualche volta. In questo momento, pero', ho bisogno di qualcosa.}
{393}{}{Credo che Sulik stara' molto meglio, lontano da te.}
{394}{}{Grazie; adesso credo sia meglio andare.}
{400}{}{Sei tornato, eh? Spero che tu ti stia occupando di Sulik. Sono certa che si sente perso senza di me che gli dico cosa fare.}
{401}{}{Sono tornato perche' mi serve qualcosa.}
{402}{}{Beh, sono sicuro di non poter essere cosi' bravo ad occuparmi di lui come hai fatto tu, ma ci provero'.}
{420}{}{A trapper named Smiley has gone missing. Momma sure is upset about that. I'm sure she would be grateful if
 someone found him.}
{421}{}{Well, have you seen Torr anywhere? It seems as though he's run off, and we're sure worried.}
{422}{}{OK, ne parlero' con la signora Buckner, allora. Lascia che ti chieda qualcos'altro.}
{423}{}{No, non ho visto Torr da nessuna parte. Se dovessi vederlo, ve lo faro' sapere. Lascia che ti chieda qualcos'altro.}
{424}{}{Well, Torr has been complaining about "Bug Men" scaring the brahmin. Not sure if I really believe all his stories,
 but someone or something has been rustling cattle here in town.}
{425}{}{I'll admit I haven't been paying too much attention to all the gossip around town. Head over to the Golden Gecko,
 I'm sure someone there might know a thing or two.}
{426}{}{Cattle rustling, huh? I'll look into this. Let me ask you something else, though.}
{427}{}{Interesting. Anything else I should know?}
{428}{}{Thanks for the tip. Let me ask you something else, though.}
{430}{}{Grazie per aver ritrovato mio fratello Torr. Mamma e io eravamo cosi' preoccupate... Cosa posso fare per te?}
{431}{}{Ancora grazie per aver ritrovato Torr. Cosa posso fare per te?}
{432}{}{E' stato un piacere aiutare Torr.}
{433}{}{Sono felice di aver trovato Torr, ma al momento non ho bisogno di nulla. Arrivederci.}
{434}{}{E' stato un piacere aiutarvi. Non e' che potreste farmi un favore e liberare Sulik come ricompensa per aver ritrovato tuo fratello?}
{440}{}{Hai visto mio fratello Torr da qualche parte? Ha perso altri brahmin e nostra madre l'ha sgridato. Dev'essere scappato di casa.}
{441}{}{Uh-oh, dove credi che possa essere andato?}
{442}{}{Mi dispiace. Pero' ho bisogno di farti qualche domanda.}
{450}{}{Non so con certezza dove sia finito, ma penso che possa essere andato in quel canyon del quale parlava sempre.}
{451}{}{Un canyon? Quale canyon?}
{460}{}{Beh, c'e' un canyon a est di dove facciamo pascolare i brahmin. Torr era solito uscirsene con delle storie assurde riguardanti uomini-insetto che provenivano da quella direzione. Diceva che erano gli uomini-insetto a mutilare i nostri brahmin. Quello stupido si e' spaventato da solo con quelle folli storie.}
{461}{}{Credo che chiunque si spaventerebbe a sentirle.}
{470}{}{Temo che possa essere andato al canyon per dimostrare il suo coraggio... Spero con tutto il cuore che qualcuno lo trovi prima che si faccia del male.}
{471}{}{Forse potrei provare a cercarlo.}
{472}{}{Mi dispiace davvero. Ma sono sicuro che sta bene. Ho bisogno di informazioni.}
{473}{}{Chissa' dov'e' finito quell'idiota di tuo fratello -- e chi se ne frega? Ho bisogno di informazioni.}
{480}{}{Ti sarei davvero grata se tu riuscissi a trovare mio fratello...}
{481}{}{Sarei felice di andare a cercarlo.}
{482}{}{Mi spiace, ma davvero non credo di averne il tempo. Addio.}
{500}{}{Grazie mille. Ritiro tutte le cose che ho detto a proposito dei selvaggi. Ti prego, ritrova mio fratello...}
{501}{}{Lo faro'; puoi contare su di me.}
{510}{}{Hai trovato mio fratello? Spero davvero che stia bene.}
{511}{}{No, non ancora. Comunque mi sono venute in mente altre domande da porti.}
{512}{}{Non ancora, lo sto ancora cercando.}
{520}{}{Vuoi bere? Sono 5$ per un bicchiere della migliore birra di casa Buckner.}
{521}{}{Ho proprio voglia di una bella birra. Riempimene un bicchiere.}
{522}{}{Vorrei offrire un giro di bevute a tutti i vostri clienti per presentarmi. Sono }
{523}{}{ da Arroyo.}
{524}{}{Non credo di volere un birra, dopotutto. Forse delle semplici informazioni mi basteranno.}
{530}{}{Un giro per tutti. Bene, bene - sei davvero generoso! Sono 30$.}
{531}{}{Bevete alla mia salute, gente. Ora, che ne diresti di darmi qualche informazione?}
{532}{}{Hmm... credo che invece mi faro' una bevuta da solo.}
{533}{}{Hmm... credo che delle informazioni saranno piu' che sufficienti, per adesso.}
{540}{}{Sembra proprio che tu non abbia abbastanza soldi. }
{541}{}{Uh, beh, magari chiedero' solo delle informazioni, allora.}
{542}{}{Oh, magari tornero' quando ne avro' di piu'. Arrivederci.}
{550}{}{Saro' davvero felice quando quel dannato (sob) selvaggio (sob) se ne sara' andato (sob) da qui. (sob) }
{600}{}{[AVANTI]}
{700}{}{I found out what's been happening to your brahmin.}
{701}{}{You have? That's great, but mom's the one you'll want to talk to about that.}
{702}{}{Sure, I'll go talk to her then.}
{710}{}{Cattle rustling? Any leads?}
{711}{}{Not really. I'm not even sure if there's a connection between this and the brahmin mutilations.}
{712}{}{Interesting. Any other local news I should know about?}
