{100}{}{Vedi un trapper sporco, con addosso degli abiti stracciati e macchiati di sangue. Sembra favorire leggermente una gamba rispetto all'altra.}
{101}{}{Vedi Smiley, il trapper. Sta zoppicando leggermente e non ha un'aria molto allegra.}
{102}{}{Vedi Smiley, il trapper. Sembra stare molto meglio dacche' l'hai salvato nelle grotte.}
{103}{}{Vedi un uomo di mezz'eta' che indossa i tipici vestiti da trapper, ma insanguinati e laceri. Non sembra stare molto bene.}
{104}{}{Vedi Smiley, il trapper. Sembra proprio che la sua salute sia migliorata dacche' l'hai salvato nella grotta.}
{110}{}{Ehi, straniero. La gente mi chiama Smiley. Sono davvero felice di vederti. Credevo proprio che sarei morto qui dentro! Sono messo male e da solo non riuscirei a farmi strada tra quelle dannate lucertole.}
{111}{}{Smiley, heh, heh, heh. Ook.}
{112}{}{Cosa fai qui?}
{113}{}{Felice di conoscerti, Smiley. Sara' meglio che adesso io me ne vada.}
{120}{}{Splendido. Un altro Torr. Io (indica se stesso) ho bisogno che tu (indica te) mi aiuti a uscire di qui (fa il gesto di camminare con due dita della mano).}
{121}{}{Andare? Ora? Ook }
{122}{}{ va. Cattive lucertole! Cattive!}
{130}{}{Si'! Esatto. Noi andare (fa ancora il gesto di camminare con le dita) insieme (unisce le mani). Proprio adesso!}
{131}{}{Smiley andare con }
{132}{}{ adesso.}
{133}{}{Smiley no andare con }
{134}{}{. No piace Smiley. Ciao ciao.}
{140}{}{Ehi! Aspetta! Non puoi lasciarmi qui da solo, in questo stato.}
{141}{}{Oh, scusa. Chissa' a cosa stavo pensando...}
{142}{}{Beh, immagino di no.}
{143}{}{Posso e lo faro'. Credo proprio che ti lascero' qui. Addio.}
{150}{}{Ho sempre catturato un maggior numero di gecki dorati nelle zone a nord e a ovest di Klamath. Percio' ho pensato che tutti i gecki dorati dovessero vivere da qualche parte non distante da li'.}
{151}{}{Sembra proprio che tu abbia fatto centro.}
{160}{}{Mi piacerebbe molto chiacchierare con te, ma prima vediamo di uscire da qui e *poi* potremo parlare. Okay?}
{161}{}{Uh, certo. Credo sia una buona idea.}
{162}{}{Solo una domanda, prima. Cosa sai a proposito di queste grotte?}
{170}{}{Sembra che io ci sia arrivato un po' troppo vicino, al centro. Sono entrato senza problemi, ma poi uno di quei dannati gecki mi e' piombato alle spalle ed e' andato dannatamente vicino allo staccarmi la gamba. Sono riuscito a malapena a trascinarmi fin qui.}
{171}{}{Mi domando perche' non ti abbiano finito...}
{180}{}{Beh, credo che a loro non piaccia molto camminare sopra quella sostanza fosforescente. Non posso certo biasimarli: brucia un casino se ti finisce sulla pelle. Ma questo non sembra impedire loro di bersi quella roba come se fosse la migliore birra del Buckner.}
{181}{}{Interessante.}
{190}{}{Abbiamo chiacchierato anche troppo. Adesso filiamocela da qui. Credo che insieme dovremmo essere in grado di uscire da qui senza problemi. Avrei proprio bisogno del tuo aiuto.}
{191}{}{Ok. Puoi unirti a me. Faro' in modo che tu esca da qui e che torni a Klamath sano e salvo. Scommetto che Ardin sara' felice di rivederti.}
{192}{}{Beh, OK. Ma non piagnucolare in continuazione chiedendo aiuto.}
{200}{}{Queste grotte sembrano essere una sorta di magazzino costruito prima dello scoppio della guerra. Credo che ci sia dell'altro sotto di noi, ma c'e' una strana serratura tek-no-logica nella porta. E poi ne ho avuto abbastanza di questo posto. Filiamocela da qui.}
{201}{}{OK.}
{210}{}{Whew. Credo di aver proprio consumato un paio di vite, stavolta. Perche' non vieni al locale delle Buckner, tra un po'? Faro' in modo che tu riceva una bella ricompensa per avermi salvato.}
{211}{}{Grazie, Smiley. L'ho fatto con piacere. Ci vediamo.}
{212}{}{OK, vedi un po' tu. Ci vediamo.}
{213}{}{Era ora che tu parlassi di ricompensa. E sara' bene che sia bella grossa. Arrivederci.}
{220}{}{Beh, ecco qua il mio amico stupidone. Grazie un casino. Ti saluto.}
{221}{}{Ehila', amico. Grazie ancora per avermi tirato fuori da quella brutta situazione. Posso fare qualcosa per te?}
{222}{}{Hai bisogno di qualcos'altro, amico?}
{223}{}{Beh, avrei un paio di domande a proposito della caccia al gecko.}
{224}{}{Ho un sacco di domande a proposito di questa zona.}
{225}{}{La signora Buckner e' contenta di riaverti con se'?}
{226}{}{No, pensavo solo di salutarti. Ci vediamo, Smiley. Ciao.}
{230}{}{Ti sono in debito per avermi salvato la pellaccia. Il minimo che posso fare per ricambiare e' insegnarti qualcosa.}
{231}{}{Insegnare?}
{232}{}{Grazie Smiley. Apprezzero' qualsiasi consiglio tu mi possa dare.}
{240}{}{Dal momento che quei gecki stavano per farmi la pelle, lascia che ti insegni come prendere la loro. Ecco cosa bisogna fare per scuoiarli nel modo corretto. (Smiley ti da' una dimostrazione) ...e quando li uccidi puoi prendere le loro pelli e venderle. OK?}
{241}{}{Urk. Bello, heh, heh, heh. Vendere. Heh, heh, heh. Ciao.}
{242}{}{Grazie, sono sicuro che questo mi tornera' utile. Parliamo di qualcos'altro, adesso.}
{243}{}{Grazie per avermi mostrato come farlo, Smiley. Credo che andro' a fare un po' di pratica su qualche gecko. Ci vediamo.}
{250}{}{Credo che adesso tu sappia abbastanza cose a proposito dei gecki. }
{251}{}{Eh, eh. Ormai credo che potresti essere *tu* ad insegnarmi qualcosa sui gecki. Non posso aiutarti.}
{252}{}{Beh, credo di essere la persona piu' esperta in fatto di gecki. Sai, sono stato cresciuto con latte di gecko. Ma ci vorranno un po' d'ore.}
{253}{}{Voglio imparare tutto quello che hai da insegnarmi a proposito dei gecki.}
{254}{}{Non credo di voler imparare qualcosa, in questo momento. Parliamo di qualcos'altro, piuttosto.}
{255}{}{Latte di gecko? Credevo che i gecki fossero dei rettili.}
{260}{}{Ci sono molte cose che devi imparare.}
{261}{}{Insegnami, o grande trapper.}
{262}{}{Uh, si'. Vai avanti. Ti ascolto.}
{263}{}{Bene, okay. Raccontami le tue storielle. Ti ascoltero'.}
{264}{}{Forse non ho bisogno di sapere queste cose. Arrivederci.}
{270}{}{Beh, vedi, le cose stanno piu' o meno cosi' - i gecki dorati e quelli normali sono praticamente le stesse bestie, ma quelli dorati hanno ricevuto una seconda passata di bastardaggine pura e genuina... (il tempo passa mentre impari varie nozioni riguardanti i gecki)}
{271}{}{E' stato splendido. Credo di sapere molte piu' cose sui gecki, adesso. Grazie. Arrivederci.}
{280}{}{Maida Buckner, la figlia della vedova Buckner, e' la persona alla quale devi rivolgerti per conoscere le notizie cittadine.}
{281}{}{Lascia che ti chieda qualcos'altro.}
{282}{}{Oh, capisco. Grazie. Arrivederci.}
{290}{}{La vedova Buckner e' cosi' dannatamente felice di vedermi che potrebbe diventare la signora Smiley in poco tempo. Stava persino dicendo qualcosa a proposito di darti una ricompensa per aver ritrovato il mio culo peloso e averlo riportato da lei.}
{291}{}{Sono felice per voi due. Vorrei chiederti qualcos'altro.}
{292}{}{E' meraviglioso. Andro' a parlare con lei. Arrivederci.}
{300}{}{Ehi, grazie per avermi salvato il culo. Faro' meglio a tornarmene in fretta a Klamath. Ci vediamo li'.}
{310}{}{Non preoccuparti per me. Posso farcela a tornare anche da solo.}
{320}{}{Guadagni }
{330}{}{ punti esperienza per aver salvato Smiley.}
