{100}{}{Vedi un vecchio. }
{101}{}{Vedi Cornelius.}
{102}{}{A parte l'espressione leggermente confusa del suo volto, non sembra esserci nulla di strano in lui.}
{150}{}{Benvenuto al Bed & Breakfast di Rose. Il mio nome e' Rose -- cioe', Cornelius -- e sono il proprietario di questo bed and breakfast. Posso aiutarti?}
{151}{}{Se sei tu il proprietario, allora perche' si chiama il Bed & Breakfast di ROSE?}
{152}{}{Sto cercando un orologio d'oro.}
{153}{}{Di che cosa ti occupi?}
{154}{}{Chi e' Rose?}
{155}{}{Vorrei una camera.}
{156}{}{Domande? Ti stavo chiedendo qualcosa? Ciao, il mio nome e' Cornelius.}
{162}{}{Hai seriamente bisogno d'aiuto, vecchio.}
{163}{}{Farrel ha il tuo orologio in una cassaforte a muro. Impicchiamolo.}
{164}{}{Ho trovato il tuo orologio nella casa di Farrel. Avevi ragione: e' stato Farrel a rubartelo.}
{165}{}{Pare che a rubare il tuo orologio sia stato un ratto molto attivo. L'ho trovato nel suo nido.}
{166}{}{Salve cumpa'! Ci siamo gia' visti da qualche parte?}
{176}{}{Mio Dio! Qualcuno ha ucciso Farrel, il mio migliore amico! L'intero paese sta cercando l'assassino. Lo linceremo non appena l'avremo beccato!}
{177}{}{Sono stato io ad ucciderlo. Adesso cosa pensi di fare, vecchio pazzo?}
{178}{}{Whoa! Guarda che ore sono. Devo proprio andare.}
{179}{}{Rose e' mia moglie; ho dato il suo nome a questo locale. Sapevi che ero sposato?}
{180}{}{Posso farti delle altre domande?}
{181}{}{ALLORA PERCHE' NON LO CHIEDI A QUEL BUONO A NULLA DI FARREL?! MAGARI LUI TI VENDERA' L'OROLOGIO CHE MI HA RUBATO! Adesso, se non ti dispiace, sono piuttosto occupato. Devo rasare i brahmin.}
{182}{}{Sono il proprietario di questo motel. Yep, questo posto andrebbe in rovina se non ci fossi io. Sei stato al gabinetto esterno? E' il piu' pulito gabinetto esterno che tu abbia mai visto. E' opera mia.}
{183}{}{Cos'ha a che fare l'avere un gabinetto esterno pulito con l'essere il proprietario di questo locale?}
{184}{}{Rose e' mia moglie. Si occupa della cucina. Non troverai cibo migliore da nessun'altra parte. Rose e' cosi' bella. La sposero', un giorno.}
{185}{}{Mi pareva tu avessi appena detto che Rose e' tua moglie.}
{186}{}{Ho una stanza. Dormo la'. Dove dormi tu?}
{187}{}{Non credo che tu abbia capito. Vorrei affittare una camera per la notte.}
{188}{}{Un momento fa, non ricordo quando... il mio migliore amico per 30... o erano 40 anni? Oh, non ha importanza, quello che importa e' che lui mi ha rubato il mio orologio d'oro da taschino. La mia famiglia se lo tramanda da cinque, no sei, err... quattro generazioni. Yep, mi ricordo perfettamente il momento in cui l'ho riposto sulla mia scrivania. Poi, quando ho guardato nuovamente sul tavolo da cucina, era sparito.}
{189}{}{OK, ti riportero' il tuo orologio.}
{190}{}{Hai provato a cercarlo sulla tua scrivania?}
{191}{}{Mi aiuterai? Splendido! Vai a dare una lezione a Farrel e riportami il mio orologio. Probabilmente l'ha nascosto bene. Percio' rivolta la sua casa da cima a fondo e cercalo.}
{192}{}{Di cosa stai parlando?}
{193}{}{Senti, non voglio avere nulla a che fare con questa storia.}
{194}{}{Uccidere Farrel, riportare orologio... giusto? Torno subito.}
{195}{}{Uccidere Farrel? Chi e' che vuole uccidere Farrel? E' il mio migliore amico! Impicchero' personalmente il primo farabutto che prova ad uccidere Farrel.}
{196}{}{Accetto questo lavoro, e mi aspetto un pagamento dopo averlo completato.}
{197}{}{Non ce la faccio piu'. Me ne vado.}
{198}{}{D'accordo, ti paghero'. Non appena avrai finito di pulire la stalla, torna qui.}
{199}{}{Ho un orologio. Era un orologio d'oro. Mi domando dove posso averlo messo...}
{200}{}{Si', si', si'. Ho guardato nel mio cassetto dei calzini. Non e' nemmeno li'.}
{201}{}{Staro' attento, in caso dovessi vedere il tuo orologio mentre sono in citta'.}
{202}{}{Non c'e' modo di aiutare un vecchio pazzo come te. Me ne vado.}
{203}{}{Lo sapevo che non potevo fidarmi di lui! Lo appendero' per le orecchie finche' non mi avra' ridato il mio orologio.}
{204}{}{Non c'e' niente li' dentro. Lo sceriffo Jo ed io ci abbiamo gia' guardato.}
{206}{}{Davvero? Lo sapevo! Gli daro' una lezione che non scordera' mai. Farai meglio a rimanere qui o potresti farti male.}
{207}{}{E' il mio orologio! Che cosa ci fai tu con il mio orologio? Ridammelo! [Ti strappa l'orologio dalle mani.] Credo sia meglio che tu te ne vada; non trattiamo molto bene i ladri, da queste parti.}
{208}{}{Bella gratitudine.}
{209}{}{Hai provato le omelette di Rose? Sono deliziose.}
{210}{}{Ho visto Jonny che giocava con il suo cane Laddie vicino al pozzo. Che bel bambino.}
{211}{}{Non recarti alla Fattoria Fantasma, a meno che tu non sia stanco di vivere.}
{212}{}{Miria e' una bella ragazza. Quand'era piccola giocavamo spesso al dottore.}
{213}{}{Davin e' un bel ragazzo. Mi chiedo perche' non assomigli per nulla a suo padre...}
{214}{}{Un giorno me ne stavo seduto sulla tazza e un grosso cane si e' arrampicato su dallo scarico. Mi ha fatto quasi venire un colpo.}
{215}{}{Grisham e' un brav'uomo. Ci vende gli scarti per darli da mangiare alla gallina gigante.}
{216}{}{Stai lontano dalla stia! Una volta ho quasi perso un braccio mentre davo da mangiare a quel coso.}
{217}{}{I cani di Rose sono cattivi, ma se tiro loro un po' di carne non mi badano.}
{218}{}{Farrel e' il migliore amico che ci sia.}
{219}{}{Laddie e' un cane intelligente. Gli parlo sempre.}
{220}{}{Ho sentito che Grisham sta cercando di far sposare i suoi figli. Mi domando se a Rose dispiacerebbe se prendessi un'altra moglie.}
{222}{}{Pog? A proposito: cos'e' successo a quel gioco? Beh, devo andare. Magari possiamo giocare dopo.}
{223}{}{HO TROVATO L'ASSASSINO! HA AMMESSO DI AVER UCCISO FARREL! PRENDETELO!}
{224}{}{HO TROVATO L'ASSASSINA! HA AMMESSO DI AVER UCCISO FARREL! PRENDETELA!}
{225}{}{Me uccide Farrel.}
{300}{}{[Hmmm... Sembra che certe parole lo colpiscano particolarmente.] Rose... Stanza... Proprietario...}
{301}{}{Ooga.}
{501}{}{L'ho sempre saputo che eri un ladro!}
{502}{}{Come hai potuto fare una cosa del genere al mio migliore amico?!}
{503}{}{Ti uccidero'!}
{504}{}{Appendero' la tua testa al muro come trofeo!}
{550}{}{Sembra essere immerso nei suoi pensieri, al momento.}
{600}{}{Hai ridato l'orologio a Cornelius.}
{650}{}{Hai risolto la disputa tra Cornelius e Farrel.}
