{100}{}{Vedi un ragazzino trasandato che lavora sodo e si prende cura dei brahmin.}
{101}{}{Vedi lo stalliere.}
{150}{}{Sembra essere occupato.}
{200}{}{Spiacente, le stalle sono piene. Dovrai cercare un posto da qualche altra parte.}
{201}{}{Adesso sono davvero impegnato.}
{250}{}{La puzza? Immagino che uno finisca per abituarsi, prima o poi...}
{251}{}{Non puzza cosi' tanto.}
{252}{}{Credo proprio che quest'anno non ci sara' bisogno di fertilizzare i campi. Grazie.}
{300}{}{Questo ha bisogno di un po' di fieno fresco.}
{301}{}{Devo andare a prendere ancora un po' d'acqua.}
{302}{}{Whew! E' ora di prendere il badile.}
{303}{}{Questo sembra a posto.}
{304}{}{Questo sara' meglio tenerlo d'occhio. Sembra un po' malato.}
{350}{}{Zzz... Sto dormendo... Zzz...}
{351}{}{*YAWN* Devo alzarmi presto.}
{352}{}{Ehi, sto ancora crescendo. Ho bisogno di dormire!}
{353}{}{Perche' non vai a parlare con qualcun altro?}
{354}{}{Cavoli, ho davvero sonno. Se solo qualcuno la smettesse di parlarmi...}
