{100}{}{Vedi Chris Wright.}
{150}{}{Vedi un ragazzo molto alto con i capelli alla mohicana. Ha addosso un quantita' notevole di catene e di cuoio.}
{151}{}{Vedi Chris Wright.}
{152}{}{Vedi Chris Wright. Sembra annoiarsi a morte.}
{200}{}{Ehi! }
{201}{}{Che ganzo, }
{202}{}{Sei un maranza, }
{203}{}{::Cheers::}
{204}{}{::Applaude::}
{205}{}{::Fischia::}
{215}{}{Come fai ad andare in bagno con quella roba indosso?}
{220}{}{Ehila', }
{221}{}{Che caldo infernale, eh, }
{222}{}{Ehila', }
{230}{}{Non riesco ancora a credere che papa' sia morto. Ci sono cosi' tante cose che avrei voluto dirgli...}
{235}{}{Smamma.}
{236}{}{Smamma. Faccio sul serio.}
{237}{}{Non ho nulla da dirti.}
{245}{}{Si'?}
{246}{}{Ehi! Come va, }
{247}{}{Ehi, ti ringrazio per aver scoperto chi ha ucciso Richard, }
{248}{}{. Ti dobbiamo un grosso favore, e gli Wright onorano sempre i loro debiti. Cosa posso fare per te?}
{249}{}{Mattah. Uomo e' Mattah!}
{250}{}{Hoobajuube}
{251}{}{-Allontanati-}
{252}{}{Chi sei?}
{253}{}{Veramente, si'. Sto cercando un lavoro. La Family Wright ha bisogno di un paio di braccia in piu'?}
{254}{}{Ho conosciuto tua mamma, sai?}
{255}{}{Puoi parlarmi di Richard?}
{256}{}{Niente, grazie. Scusa il disturbo.}
{265}{}{Smamma, ritardato. Non ho voglia ne' tempo di usare il linguaggio dei segni con te.}
{266}{}{-Allontanati-}
{275}{}{Sono Chris. Chris Wright. Della Famiglia Wright. Sei felice d'avermelo chiesto?}
{276}{}{Veramente, si'. Sto cercando un lavoro. La Family Wright ha bisogno di un paio di braccia in piu'?}
{277}{}{Famiglia Wright? E chi sarebbero?}
{278}{}{Chris Wright, eh? Ho conosciuto tua mamma, sai?}
{279}{}{Puoi dirmi cos'e' successo a tuo fratello Richard?}
{280}{}{Non molto. Scusa il disturbo.}
{290}{}{Non hai mai sentito parlare della Famiglia Wright? Devi aver passato troppo tempo nel deserto, allora. Gli Wright sono la piu' grossa famiglia criminale di Reno. Presto domineremo questa citta'.}
{291}{}{Davvero? Sembra proprio che la famiglia Wright abbia tutte le carte in regola. Avete bisogno di un paio di braccia in piu'?}
{292}{}{Actually, I got the impression they were one of the weakest of the families... I mean, they
 only deal in alcohol, they have no casino or drug trade, and their numbers are much less than
 other families.}
{293}{}{A proposito di famiglia... ho conosciuto tua madre.}
{294}{}{Puoi dirmi cos'e' successo a tuo fratello Richard?}
{295}{}{Davvero? Molto interessante... beh, scusa, ma devo andare.}
{305}{}{Ad esempio?}
{306}{}{Puoi dirmi qualcosa a proposito della famiglia Wright?}
{307}{}{La Family Wright ha bisogno di un paio di braccia in piu'?}
{308}{}{Ho conosciuto tua madre, non molto tempo fa. E' una bella signora.}
{309}{}{Puoi dirmi cos'e' successo a tuo fratello Richard?}
{310}{}{No, nessun'altra domanda. Sara' meglio che vada.}
{315}{}{(Il giovane si gira verso di te, ti guarda dall'alto in basso. I suoi occhi si fermano sul marchio che hai sulla fronte.) Guarda un po' chi abbiamo qui... (Sogghigna, poi sputa ai tuoi piedi) Perche' non ti rendi utile leccando via quello sputo da terra, schiavista?}
{316}{}{(Il giovane si gira verso di te e ti guarda dall'alto in basso.) Guarda un po' chi abbiamo qui... (Sogghigna, poi sputa ai tuoi piedi) Perche' non ti rendi utile leccando via quello sputo da terra, brutto pezzo di merda [FA]?}
{317}{}{Tiragli un calcio con lo stivale sul quale ha sputato.}
{318}{}{-Allontanati- }
{319}{}{Ignoralo. Per questa volta. }
{325}{}{Well... I...I mean, the Wright family... my family... might have an opening. I ain't promising nothing, but go to the mansion
 south of here, find my brother Keith and tell him I sent you. Name's Chris. Chris Wright.}
{326}{}{Uh, la famiglia Wright? E chi sarebbero?}
{327}{}{Wright, eh? Ho conosciuto tua madre.}
{328}{}{Puoi dirmi cos'e' successo a tuo fratello Richard?}
{329}{}{Grazie. Vado subito a parlare con lui.}
{335}{}{Nah, non credo proprio che abbiamo bisogno di altra gente. Quasi tutte le famiglie della citta' sono praticamente al completo.}
{336}{}{D'accordo.}
{345}{}{Oh, magnifico. Ha fatto la predica anche a te?}
{346}{}{Una specie. Non vuoi bene a tua madre?}
{347}{}{No. Di solito la fa?}
{348}{}{Veramente no. Scusa, adesso devo proprio andare. }
{355}{}{Cos'e' questo? Uno *scherzo*? Se e' cosi', sappi che e' molto lontano dall'essere divertente. Con la Famiglia Wright non si scherza, capito volpone?}
{356}{}{Scherzare? No, sono dannatamente *serio*.}
{357}{}{Si', mi dispiace. Non intendevo dire nulla di male. Senti, avrei delle altre domande…}
{358}{}{Si', alla perfezione. Credo sia meglio che me ne vada.}
{365}{}{(Alza le spalle.) Semplicemente non presta attenzione a quello che succede intorno a lei. Le voglio bene, certo, ma a volte e' piu' testarda di un mulo e piu' cieca di una talpa.}
{366}{}{Beh, non molto tempo fa, ha fatto dei casini con il nostro distillatore e ha mandato in malora l'intera distilleria, mandando all'aria i nostri affari! Le voglio bene, certo, ma ha volte e' piu' cieca di una talpa.}
{367}{}{Eh eh. E le assomiglia, anche.}
{368}{}{Cieca? Cosa vuoi dire?}
{369}{}{Oh. Avrei delle altre domande...}
{370}{}{Lo immagino. Beh, adesso devo andare. }
{380}{}{Va in giro a fare delle prediche sul peccato e robe del genere, ma non sa neppure cosa fa veramente nostro padre. O non lo sa, o fa finta di non saperlo.}
{381}{}{Cosa fa tuo padre?}
{382}{}{Hmmmm. Say, I had some other questions...}
{383}{}{Interessante. Beh, adesso devo andar. }
{390}{}{Distilla alcol, si occupa degli affari sporchi, elimina le persone che cercano di fregarlo... le solite cose da famiglia. La mamma andrebbe fuori di testa se si accorgesse di quello che succede davvero. E soprattutto si arrabbierebbe se scoprisse questa distilleria.}
{391}{}{E quanto potrebbe arrabbiarsi?}
{392}{}{Hmmmm. Say, I had some other questions...}
{393}{}{Interessante. Beh, adesso devo andar. }
{400}{}{Probabilmente abbastanza da spaccare questo posto… come minimo. Poi darebbe a tutti noi una bella strigliata e ci obbligherebbe a lunghe giornate di preghiera. Eh. }
{401}{}{Interesting. Say, I had some other questions...}
{402}{}{Hmmmmm. Grazie. }
{410}{}{Rich? Aw, you know, he was found like one of those Jet crashers, dead in one of the gutters. Near as we can
 figure, someone pumped him with drugs until he was dead.}
{411}{}{'Qualcuno' gli ha dato troppa droga? Come fate a dire che non e' morto di overdose perche' LUI ha preso troppa droga?}
{412}{}{Chi pensate possa averlo fatto?}
{413}{}{Mi dispiace. Avrei delle altre domande...}
{414}{}{Terribile. Senti, adesso devo andare. }
{420}{}{Cause he was a clean kid…Mom taught him THAT much. And if you feel like saying any different, maybe you and I
 should settle it right here.}
{421}{}{Non volevo insinuare nulla. Scusa se te ne ho parlato.}
{422}{}{Don't blind yourself to the possibility he might have been taking it. Jet is extremely addictive.}
{423}{}{Ascolta, *ragazzo*, se ci tieni alla pelle, smettila di prendertela a male ogni volta che una piccola verita' viene a galla e ti fa male.}
{424}{}{Chi pensate possa averlo fatto?}
{425}{}{Non voglio guai. Me ne vado. }
{435}{}{Certo... beh, vedi di stare in guardia. Discorsi del genere farebbero arrabbiare qualsiasi Wright, percio' non andare a in giro a dire simili fesserie, okay?}
{436}{}{Don't blind yourself to the possibility he might have been taking it. Jet is extremely addictive.}
{437}{}{Senti, RAGAZZO, non cercare di metterti contro uno come me. Se ci tieni alla pelle, smettila di prendertela a male ogni volta che una piccola verita' viene a galla e ti fa male.}
{438}{}{Scusa, non intendevo offendervi. Ascolta, avrei qualche altra domanda…}
{439}{}{Ho capito. Sara' meglio che vada. }
{445}{}{Sparisci. Non ho nient'altro da dirti.}
{446}{}{Aspetta, ho solo un'altra domanda da farti…}
{447}{}{Me ne vado, me ne vado. }
{455}{}{(Chris ti fissa per un attimo, poi si getta contro di te!)}
{456}{}{Allora e' COSI' che vogliamo METTERLA, eh? D'ACCORDO, DIAMOCI DENTRO, BRUTTO STR -- }
{465}{}{Io credo siano stati i Mordino; probabilmente uno dei loro spacciatori, se non addirittura un membro della famiglia. Quei bastardi producono tonnellate di Jet.}
{466}{}{Ho capito. Senti, avrei delle altre domande…}
{467}{}{Quale spacciatore pensi possa aver venduto il Jet a Richard?}
{468}{}{Capisco. Sara' meglio che vada. }
{475}{}{Potrebbe essere stato chiunque: Jagged Jimmy J, quel fottuto sfregiato all'angolo di Virgin Street, o Renesco 'the Rocketman', quel vecchio e viscido merdoso che vende il Jet accanto all'armeria nel West Side.}
{476}{}{Ci sono altri spacciatori?}
{477}{}{Ho capito. Senti, avrei delle altre domande…}
{485}{}{Ehi, amico, GRAZIE. }
{486}{}{Ehi, ragazza mia, GRAZIE. }
{487}{}{Hai scoperto chi ha ucciso mio fratello, e tutta la Famiglia Wright ti ringraziera', stanne certo. E non sara' un ringraziamento da poco, credimi.}
{488}{}{Ho capito. Ci becchiamo dopo, Chris. }
{495}{}{Jules at the head of town also sells Jet, but he mostly sells to tourists... then there's Little Jesus Mordino:
 he mighta pushed drugs on Rich while Rich was out alone. He hangs out at the Desperado.}
{496}{}{Ho capito. Senti, avrei delle altre domande…}
{497}{}{Jagged Jimmy J, Renesco the Rocketman, Jules e Little Jesus… Andro' a parlare con loro. Grazie delle informazioni, Chris. }
{1200}{}{! Sei stato grande a spazzare via l'Enclave!}
{1201}{}{! Sei forte!}
{1202}{}{!}
{1220}{}{. Cos'hai fatto di bello?}
{1221}{}{?}
{1222}{}{. Come vanno le cose?}
{1246}{}{? Ti trattano tutti col dovuto rispetto? Ti serve qualcosa?}
