{100}{}{Vedi una persona che indossa uno dei completi blu da vault.}
{101}{}{Vedi un cittadino dell'Enclave.}
{102}{}{Vedi un cittadino pallido, ma dall'aspetto sano.}
{103}{}{Ho bisogno di un po' di riposo.}
{104}{}{Mi domando quale filmato educativo sia in programmazione stasera?}
{105}{}{Che cosa sei?}
{106}{}{Il clima e' sempre lo stesso qui.}
{107}{}{Il Progetto procede bene.}
{108}{}{Mi dispiace per il Vice Presidente Bird.}
{109}{}{Il prossimo cambio non avvera' prima di qualche ora.}
{110}{}{Dio benedica l'America.}
{111}{}{Il Progetto e' la nostra salvezza.}
{112}{}{Sono davvero felice di non essere sul continente.}
{113}{}{E' solo un'altra esercitazione.}
{114}{}{Cos'e' tutta questa confusione?}
{115}{}{Questo e' l'allarme del reattore.}
{116}{}{Uh, oh.}
{117}{}{Sara' meglio che mi procuri un po' di Rad-X. Di nuovo...}
{118}{}{Quel coso continua a rompersi.}
{119}{}{Mi sento come se mi fossi scottato la pelle.}
{120}{}{Sbaglio, o qui dentro comincia a fare piu' caldo?}
{121}{}{This isn't good.}
{122}{}{Cazzo, cazzo, cazzo.}
{123}{}{Dov'e' la mia maschera antigas?}
{124}{}{C'e' uno strano odore nell'aria.}
{125}{}{Non mi sento troppo bene.}
{126}{}{L'aria mi sta bruciando la gola.}
{127}{}{Cavoli, ho una brutta pirosi.}
{128}{}{I miei polmoni sono in fiamme.}
{129}{}{Credo di aver bisogno di una boccata di aria fresca.}
{130}{}{Sbaglio, o si sta facendo buio qui dentro?}
{131}{}{Ho cosi' tanto sonno... devo dormire.}
{132}{}{Credo che mi siedero' per un attimo.}
{133}{}{Un'altra esercitazione?}
{134}{}{Mi e' parso di sentire degli spari.}
{135}{}{Ehi, chi sei tu?}
{136}{}{Alt! Chi va la'?}
{137}{}{Non ne posso piu' di tutte queste esercitazioni.}
{138}{}{Certo, come se io sapessi riconoscere un intruso.}
{139}{}{Non preoccupatevi.}
{140}{}{I soldati ci proteggeranno.}
{141}{}{Dov'e' un soldato quando serve?}
{142}{}{Devo solamente stare calmo - stare calmo.}
{143}{}{Non riusciro' a finirlo.}
{144}{}{Di sicuro mi piacerebbe essere da qualche altra parte.}
{145}{}{L'addetta al terminale era proprio carina.}
{146}{}{Questo non ha alcun senso.}
{147}{}{Non mi pagano abbastanza.}
{148}{}{Sto facendo il lavoro di tutti.}
{149}{}{Perche' le persone non fanno mai quello che si chiede loro?}
{150}{}{Se un terminale non risponde, dagli un calcio - e' un metodo che funziona sempre.}
{151}{}{Questo "Pong" e' un gran gioco. Spero che nessuno mi becchi.}
{152}{}{Ho bisogno di un po' di caffeina.}
