{100}{}{Vedi un uomo basso con i capelli neri e un sorriso gentile.}
{101}{}{Vedi Ascorti, il Sindaco di Redding.}
{102}{}{Vedi un uomo ben vestito, ma dall'aspetto viscido.}
{103}{}{Non stare li' impalato, amico.}
{104}{}{Se sei qui per tentare la fortuna, sei il benvenuto.}
{105}{}{Gioca o vattene.}
{106}{}{Sara' meglio che tu non faccia casino nel mio locale.}
{107}{}{Dovresti provare i tavoli, selvaggio.}
{108}{}{Dovresti provare le slot machine, selvaggio. C'e' un picco di magia positiva.}
{109}{}{Vacci piano con l'alcol, selvaggio.}
{110}{}{Ehila'; benvenuto nell'accogliente citta' di Redding... e benvenuto nel mio casino'. Ogni persona e' un Asso, qui all'Ascorti's Ace. Io sono Ascorti, il proprietario del casino' e il sindaco di questa ridente cittadina. }
{111}{}{Cosa puo' fare per te il sindaco Ascorti?}
{112}{}{Ci sono opportunita' di lavoro, qui a Redding?}
{113}{}{Cos'e' successo ultimamente in citta'?}
{114}{}{Ha mai sentito parlare di un qualcosa chiamato Kit di Creazione del Giardino dell'Eden?}
{115}{}{Di che cosa ti occupi?}
{116}{}{Stavo solo dando un'occhiata in giro, Sindaco. Ci vediamo.}
{117}{}{Gestisco questo casino' e faccio del mio meglio per mandare avanti questa citta'. Mi occupo di atti di proprieta' e cose simili. }
{118}{}{Atti di proprieta'? Proprieta' di cosa?}
{119}{}{Capisco; lasci che le chieda qualcos'altro, Sindaco.}
{120}{}{Atti di proprieta' come quello della Miniera Grande Wanamingo che vorrei comprare da te. Sei disposto a vendermelo?}
{121}{}{Forse. Quanto sarebbe disposto ad offrirmi?}
{122}{}{Forse. Prima vorrei chiederle qualcos'altro.}
{123}{}{Devo ancora prendere una decisione. Arrivederci, Sindaco.}
{124}{}{Beh, hai presente quello che ti ho venduto? Sai, quello per la Miniera del Grande Wanamingo?}
{125}{}{Oh, QUELL'atto di proprieta'. Ora ricordo. Lasci che le chieda qualcos'altro, Sindaco.}
{126}{}{Naturalmente - volevo solo sapere se aveva qualche altro affare da propormi. Beh, sara' meglio che vada a ripulire quella miniera, allora. Arrivederci.}
{127}{}{Avevo solo un atto di proprieta': quello della Miniera Grande Wanamingo che avevo dato a te e che poi mi hai rivenduto. Ricordi?}
{128}{}{Certo. Uh, lasci che le chieda qualcos'altro, Sindaco.}
{129}{}{Si', certamente. Volevo solo controllare. Arrivederci, sindaco Ascorti.}
{130}{}{Ogni tipo di proprieta' privata. Beh, al momento ho qui con me un atto di proprieta' che e' una vera cannonata...}
{131}{}{Di cosa si tratta?}
{132}{}{Non ne dubito, ma prima lasci che le chieda qualcos'altro, Sindaco.}
{133}{}{Hmm, credo che prima daro' un'occhiata alla citta', Sindaco. Arrivederci.}
{134}{}{E' l'atto di proprieta' della Miniera Grande Wanamingo che si trova subito fuori citta'. E posso vendertelo per soli 1.000$. E' un'offerta speciale; sei stato davvero fortunato a parlarmene oggi che sono in vena di generosita'.}
{135}{}{Sembrerebbe interessante. Mi dica di piu'.}
{136}{}{Dove sta l'inghippo, Sindaco?}
{137}{}{Al momento non credo di volerla comprare, Sindaco. Lasci che le chieda qualcos'altro.}
{138}{}{Beh, ci sono dei dannatissimi animali che infestano la miniera e che devono essere eliminati prima che le operazioni minerarie possano riprendere. Se tu comprassi l'atto di proprieta' - e poi uccidessi quegli animali - sarei ben felice di ricomprare la miniera da te ad un prezzo superiore.}
{139}{}{Un prezzo superiore? Quanto superiore?}
{140}{}{Perche' non se la disinfesta da solo, visto che vale cosi' tanto?}
{141}{}{Animali? Che tipo di animali?}
{142}{}{Nessun inghippo. Te lo assicuro. Devi solo scacciare degli abusivi che si sono stabiliti li' dentro. Non dovrebbero esserci problemi, per un cliente intraprendente come te. Posso dirti di piu', se vuoi.}
{143}{}{Okay, d'accordo. Mi dica di piu'.}
{144}{}{Non credo di voler essere coinvolto in questo genere di affari, Sindaco. Lasci che le chieda qualcos'altro.}
{145}{}{Capisco. Credo che lascero' quest'onere a qualcun altro. Arrivederci, Sindaco.}
{146}{}{Diamine, piu' del doppio. E' quello che ti meriti per il disturbo. Ma non posso darti di piu'. C'e' ancora un mucchio di lavoro da fare prima che la miniera possa tornare a generare dei profitti.}
{147}{}{Mi sta bene. Quanto ha detto che costava?}
{148}{}{Non credo di volerlo fare. Lasci che le chieda qualcos'altro, Sindaco.}
{149}{}{Per l'atto di proprieta' della Miniera Grande Wanamingo chiedo solo 1.000$. Lo vuoi?}
{150}{}{Si', comprero' l'atto.}
{151}{}{Mi piacerebbe comprare l'atto, ma, al momento, non ho abbastanza soldi con me. Lasci che le chieda qualcos'altro.}
{152}{}{Non credo di volerlo comprare, per il momento. Lasci che le chieda qualcos'altro.}
{153}{}{Magari un'altra volta, Sindaco. Arrivederci.}
{154}{}{Vado subito a registrare a tuo nome l'atto di proprieta' della Miniera Grande Wanamingo. Fammi sapere quando l'avrai ripulita e saro' felice di riacquistarla.}
{155}{}{Lo faro'. Ma prima lasci che le chieda qualcos'altro, Sindaco.}
{156}{}{Okay. A presto, Sindaco.}
{157}{}{Non posso farlo. Non sono un tipo che ama le situazioni pericolose. Mi conosco e so che il combattere non rientra nelle mie abilita'. Ma tu, tu mi sembri un hombre davvero in gamba. Questo dovrebbe essere un lavoretto proprio adatto a te.}
{158}{}{Forse. Quanto sarebbe disposto a pagarmi per riavere l'atto di proprieta' una volta che avro' ripulito la miniera?}
{159}{}{Forse si', forse no. Ci pensero'. Lasci che le chieda qualcos'altro, Sindaco.}
{160}{}{Non credo di avere tempo per farlo, al momento. Mi dispiace, signor Sindaco. Arrivederci.}
{161}{}{Allora, hai gia' ripulito la miniera?}
{162}{}{Certamente.}
{163}{}{Non ancora, ma lo faro'. Nel frattempo, lasci che le chieda qualcos'altro.}
{164}{}{Ci sto lavorando. Arrivederci, sindaco Ascorti.}
{165}{}{Sai, non credo che tu abbia fatto fuori tutti quei dannati Wanamingo. Faresti meglio a tornare nella miniera a controllare. Non la ricomprero' finche' tutti quei "cosi" non saranno morti.}
{166}{}{Capisco. Prima lasci che le chieda qualcos'altro, Sindaco.}
{167}{}{Beh, allora sara' meglio che io torni a controllare.}
{168}{}{Hai fatto davvero un ottimo lavoro, liberando la miniera da tutti quei dannati Wanamingo, ma temo che tu abbia un problema.}
{169}{}{Un problema? Di che genere?}
{170}{}{Hai ripulito completamente la miniera. Grazie mille. Sei pronto a vendermi l'atto di proprieta'? Ti daro' 2.500$.}
{171}{}{Non credo. Penso che lo terro' con me, per il momento. Arrivederci, Sindaco.}
{172}{}{Ci puo' scommettere. Saro' ben felice di disfarmi di questo atto di proprieta', sindaco Ascorti.}
{173}{}{Noi li chiamiamo Wanamingo. Sono una specie di creature totalmente assurde, con terribili denti e tentacoli o robe del genere. Non molto intelligenti, ma pericolosi a distanza ravvicinata.}
{174}{}{Capisco. E lei vuole che io me ne sbarazzi?}
{175}{}{Esatto. Lo sapevo che non eri poi cosi' tonto. Sai essere davvero sveglio quando ti ci metti.}
{176}{}{Gia'... Allora, cos'altro devo sopportare per far fruttare i miei 1.000$?}
{177}{}{La miniera era cosi' accogliente che qualcun altro vi si e' stabilito. Un tipo losco che risponde al nome di Frog Morton. Uh... e' insieme alla sua banda, da quel che ho sentito.}
{178}{}{Che razza di nome e' "Frog"?}
{179}{}{E in che modo questo sarebbe un mio problema?}
{180}{}{Ottimo, e cosa devo fare?}
{181}{}{Credo sia perche' ammazza le persone come mosche. E' un elemento davvero sgradevole e sta' sicuro che nessuno lo piangera'... e poi tu diventeresti un eroe. Ti piacerebbe diventare un eroe, vero?}
{182}{}{Forse, ma ancora non capisco come questo sia un problema mio.}
{183}{}{Si', certo. Che cosa devo fare?}
{184}{}{Credo di avere ancora delle pulizie di casa da fare. Tornero' quando avro' spaccato qualche altro grugno, Sindaco.}
{185}{}{Beh, finche' la miniera non sara' ripulita, io non posso far lavorare i minatori. Quindi, se hai intenzione di rivendermi la miniera, questo e' un problema tuo.}
{186}{}{Che razza di nome e' "Frog"?}
{187}{}{Ottimo. Che cosa devo fare?}
{188}{}{Sara' meglio che mi dia da fare, allora. Arrivederci, Sindaco.}
{189}{}{Credo che dovresti tornare alla Miniera Wanamingo e far fuori Frog e la sua banda. Quando l'avrai fatto, puoi tornare qui e io saro' ben felice di ricomprare la miniera.}
{190}{}{Non c'e' niente di facile al mondo, eh? Okay, Sindaco. Ci vediamo dopo. Ho degli affari da sbrigare.}
{191}{}{Sei pronto a rivendermi l'atto di proprieta' della Miniera Wanamingo?}
{192}{}{Certamente, Sindaco. Quanto ha detto che mi avrebbe dato?}
{193}{}{Non ancora, Sindaco. Arrivederci.}
{194}{}{Mi hanno detto che hai deciso di aiutare lo Sceriffo. Bene. Non mi posso permettere di concedere a quella parassita della vedova Rooney di occupare ancora la mia magnifica casa.}
{195}{}{Sta parlando di quella minuscola baracca fatiscente per la quale lei, signor Sindaco, esige un affitto esagerato?}
{196}{}{Lo credo. Quanto le deve?}
{197}{}{Beh, vedro' di fare il possibile. Lasci che le chieda qualcos'altro.}
{198}{}{Gia'. A proposito, chi e' lei?}
{199}{}{Preferisco definirla "accogliente", con un sistema di ventilazione stagionale. Ed e' pure piuttosto cara.}
{200}{}{Lo credo. Quante rate d'affitto arretrato le deve?}
{201}{}{Hmm, sara' meglio che io vada, Sindaco. Arrivederci.}
{202}{}{Vediamo un po'… la signora Rooney mi deve… si', ecco qua, 120$. Esatto. 120$.}
{203}{}{Cosi' poco? Ho quella somma proprio qui con me.}
{204}{}{Non e' poi molto. Lasci che le chieda qualcos'altro.}
{205}{}{Vedro' cosa posso fare per convincerla a pagare. Arrivederci.}
{206}{}{Molto bene. Adesso e' in regola. Grazie per aver saldato questo debito.}
{207}{}{Nessun problema. Lasci che le chieda qualcos'altro, pero'.}
{208}{}{Semplicemente, alcune persone sono piu' generose di altre. Arrivederci, Sindaco.}
{209}{}{Grazie per aver sgombrato la mia proprieta', Sceriffo. Adesso posso darla in affitto a qualcuno che sia davvero in grado di pagarla.}
{210}{}{Non mi sento molto fiero di quello che ho fatto.}
{211}{}{Non fa una grinza. }
{212}{}{Perche' no? Dovresti, invece. Buttando fuori la vedova Rooney, mi dai l'opportunita' di continuare a pagare i miei dipendenti. Se non li pagassi, le loro famiglie soffrirebbero la fame. E questo non e' giusto, no?}
{213}{}{Credo di no. Non avevo considerato la cosa sotto questo punto di vista. Ma non mi sento molto bene lo stesso.}
{214}{}{Non mi pare che lei abbia problemi, da questo punto di vista. Sono sicuro che il suo casino' abbia degli incassi non indifferenti.}
{215}{}{Ci vuole una grande forza di volonta' per fare la cosa giusta, anche quando il farlo causa dei rimorsi di coscienza. Tu hai fatto una cosa molto difficile, e l'hai fatta bene. Ti offro una birra.}
{216}{}{Grazie, Sindaco; e' davvero gentile da parte sua.}
{217}{}{Non credo di voler bere con lei. Ne' ora, ne' mai. Addio.}
{218}{}{Nessun problema. Sono felice di mantenere bagnata la gola dei rappresentanti della legge locali.}
{219}{}{Grazie ancora, Sindaco. Lasci che le chieda qualcos'altro.}
{220}{}{Grazie, Sindaco. Ci vediamo. Arrivederci.}
{221}{}{Oggi, forse, ma non sempre la fortuna mi sorride. Devo mantenere il bilancio in regola e magari guadagnarci qualcosa. Per pagare i miei dipendenti - e per assicurare una piccola rendita anche a me, naturalmente.}
{222}{}{Il ragionamento fila.}
{223}{}{Sei piu' spregevole di un culo di gecko. Ho sentito abbastanza. Addio.}
{224}{}{Volevo solo ringraziarti nuovamente per aver fatto la cosa giusta con la vedova Rooney. Non avevo certo intenzione di sbattere fuori di casa quella vecchia signora.}
{225}{}{Ciononostante, l'avrebbe fatto. Beh, parliamo di qualcos'altro.}
{226}{}{Per qualche motivo, sapevo che avrebbe detto una cosa del genere. Arrivederci, Sindaco.}
{227}{}{Ti sei spinto troppo oltre con la vedova Rooney. Non faceva del male a nessuno. Perche' l'hai uccisa?}
{228}{}{Se l'era cercata.}
{229}{}{E' stato un incidente.}
{230}{}{Se l'era cercata? Non era altro che una piccola, indifesa vecchina. Tu sei completamente pazzo. Adesso vattene da qui.}
{231}{}{Stai parlando con me?}
{232}{}{Stavo gia' per andarmene da questo tugurio, comunque. Addio.}
{233}{}{Un incidente? Non sono ancora riusciti a ritrovare tutti i pezzi del suo corpo. Sara' meglio che non ti capitino altri "incidenti" simili. Fanno male agli affari.}
{234}{}{Capisco. Lasci che le chieda qualcos'altro, Sindaco.}
{235}{}{La prossima volta staro' piu' attento.}
{236}{}{Si', sto parlando con te. Vedi qualcun altro qui con cui potrei parlare? Sparisci subito dal mio locale.}
{237}{}{*Tu* stai parlando con *me*?}
{238}{}{Sto andando, sto andando.}
{239}{}{Cosa? Sei sordo o soltanto stupido? *Io* sto parlando con *te*. Adesso vattene!}
{240}{}{Beh, devi proprio parlare con me, dal momento che non vedo nessun altro, qui.}
{241}{}{D'accordo. Me ne vado. Non farti venire un colpo. Addio.}
{242}{}{Sono tutti cosi' stupidi, nella tua tribu'? Adesso basta. Vuoi ballare? Allora balliamo. Guardie!}
{243}{}{Di sicuro stai parlando con me e non mi piace quello che stai dicendo.}
{244}{}{Whoa, ehi... calma, amico. Me ne stavo andando.}
{245}{}{Mi hanno detto che lavori per Earl Marion in veste di sceriffo ausiliario finche' non si sara' ripreso. Questo dovrebbe tenerti occupato per un po'. Non riesco a pensare a nessun altro lavoro per te, qui in citta'.}
{246}{}{Capisco. Lasci che le chieda qualcos'altro, sindaco Ascorti.}
{247}{}{Ehi, mi dica qualcosa riguardo ai proprietari delle miniere.}
{248}{}{Grazie lo stesso, Sindaco. Arrivederci.}
{249}{}{Mi hanno detto che hai fatto un ottimo lavoro, aiutando lo sceriffo Marion. La citta' e' piuttosto tranquilla da quando l'hai aiutato. Non riesco a pensare a nessun lavoro che possa sfruttare a dovere i tuoi talenti.}
{250}{}{Grazie, Sindaco. Detto da lei, ha un valore speciale. Lasci che le chieda qualcos'altro.}
{251}{}{Ehi, mi dica qualcosa riguardo ai proprietari delle miniere.}
{252}{}{Grazie lo stesso. Credo che levero' le tende, allora. Addio.}
{253}{}{So che lo sceriffo Earl Marion sta cercando qualcuno che lo sostituisca finche' la sua gamba non sara' guarita. Potresti provare a parlare con lui. Il suo ufficio e' subito a sud di qui, dall'altra parte della strada.}
{254}{}{Grazie della dritta. Prima che io vada, pero', lasci che le chieda qualcos'altro.}
{255}{}{Ehi, mi dica qualcosa riguardo ai proprietari delle miniere.}
{256}{}{Magari daro' un'occhiata laggiu', allora. Grazie.}
{257}{}{Beh, c'e' lo Sceriffo. Poi ci sono i proprietari delle miniere che cercano qualcuno che recuperi un qualche tipo di pezzo per una delle loro macchine. }
{258}{}{Cosa mi puo' dire dello Sceriffo?}
{259}{}{Cosa mi puo' dire dei proprietari delle miniere?}
{260}{}{Interessante. Lasci che le chieda qualcos'altro, Sindaco.}
{261}{}{Magari daro' un'occhiata in giro. Grazie e arrivederci.}
{262}{}{Diamine, e' vero. Ho sentito che hai gia' recuperato quel chip per uno di loro.}
{263}{}{Beh, mi parli dello Sceriffo, allora.}
{264}{}{Si', sono stato proprio io. Allora parliamo di qualcos'altro, Sindaco.}
{265}{}{Oh, pensavo ci fosse qualche novita'. Beh, arrivederci, allora.}
{266}{}{Non ne so molto. Dovresti andare a parlare o con "Dangerous" Dan McGrew della Miniera Morningstar, oppure con Marge LeBarge della Miniera Kokoweef. Entrambi si trovano a nord della zona dove ci troviamo noi ora, oltre il cimitero.}
{267}{}{Grazie. Ora... cosa mi puo' dire dello Sceriffo?}
{268}{}{Grazie. Lasci che le chieda qualcos'altro.}
{269}{}{Magari faro' un salto lassu' e andro' a parlare con loro. Grazie, Sindaco. Arrivederci.}
{270}{}{Ultimamente le nostre carovane d'oro hanno cominciato a subire dei ritardi perche' i minatori passano troppo tempo a "volare" con il Jet.}
{271}{}{Almost all of the miners are spending more time flying Jet than mining for gold... so our prices
 are up, and our exports are down. Bad for business all the way around.}
{272}{}{Tutti sono troppo fatti di Jet per lavorare con efficienza. L'estrazione d'oro e' calata del novanta percento e per questo siamo stati costretti ad aumentare i prezzi. Questa situazione non puo' durare.}
{273}{}{Sembra che tutti abbiano preso una partita di Jet tagliata male. Tutti i Jet-tossici abituali hanno intrapreso una specie di massiccia disintossicazione. Non so cosa sia successo, ma credo che le cose andranno per il meglio.}
{274}{}{Le cose sono tornate quasi alla normalita'. Tutti quelli che subivano gli effetti del Jet stanno guarendo. Anche la produzione delle nostre miniere e la frequenza delle spedizioni sono tornate a livelli normali. Sembra proprio che il peggio sia passato.}
{275}{}{Hmm. Interessante. Lasci che le chieda qualcos'altro, sindaco Ascorti.}
{276}{}{Capisco. Grazie per le informazioni, Sindaco. Arrivederci.}
{277}{}{Un Kit di Creazione per il Giardino dell'Eden? Credo che Vault City sia nata proprio grazie a uno di essi. Tutti i vault dovevano averne uno, in teoria, ma di sicuro qui nei paraggi non ne troverai.}
{278}{}{Oh, beh... Lasci che le chieda qualcos'altro, Sindaco.}
{279}{}{Sara' meglio che continui a cercare, allora. Grazie, sindaco Ascorti.}
