{100}{}{Vedi Madame Modjeska.}
{101}{}{Vedi Madame Modjeska.}
{102}{}{Voglio rimanere sola.}
{103}{}{Vattene, per favore.}
{104}{}{Non scocciarmi.}
{105}{}{Vattene.}
{106}{}{Non sopporto gli stupidi.}
{107}{}{La maggior parte del volgo lavora solo per procurarsi abbastanza Jet. Hanno bisogno di qualcosa che allontani i loro pensieri da questo posto.}
{108}{}{Lascia che ti chieda qualcos'altro.}
{109}{}{Jet? Cos'e' il Jet?}
{110}{}{Capisco. Arrivederci.}
{111}{}{Il Jet ha una sua utilita'. Tende a rendere le persone meno consapevoli dello squallore che le circonda.}
{112}{}{Lascia che ti chieda qualcos'altro.}
{113}{}{Jet? Cos'e' il Jet?}
{114}{}{Capisco. Arrivederci.}
{115}{}{Il Jet e' molto costoso, ultimamente. E' una cosa da criminali. A proposito... ho sentito che Ascorti, il nostro amato sindaco, si sta dando da fare per fornirci una maggior quantita' di Jet. Il solito eroe del popolo....}
{116}{}{Lascia che ti chieda qualcos'altro.}
{117}{}{Il sindaco Asc-torti? Di chi si tratta, esattamente?}
{118}{}{Jet? Cos'e' il Jet?}
{119}{}{Capisco. Arrivederci.}
{120}{}{Pare che tutti stiano male. L'ultima partita di Jet aveva qualcosa che li ha costretti a smettere di prendere quella roba. Io credo che torneranno al Jet piuttosto presto, pero'.}
{121}{}{Lascia che ti chieda qualcos'altro.}
{122}{}{Jet? Cos'e' il Jet?}
{123}{}{Capisco. Arrivederci.}
{124}{}{Pare proprio che la mia previsione fosse sbagliata. La maggior parte di quelli che usavano il Jet hanno smesso di farsi con quella roba. Dopo quell'ultima partita avariata, molti di noi non riescono nemmeno ad annusare quella roba senza sentirsi male.}
{125}{}{Lascia che ti chieda qualcos'altro.}
{126}{}{Jet? Cos'e' il Jet?}
{127}{}{Capisco. Arrivederci.}
{128}{}{Io sono... Madame Modjeska. Che cosa vuoi da me?}
{129}{}{Come posso aiutarla?}
{130}{}{Non ho tempo da perdere. Che cosa vuoi da Madame Modjeska?}
{131}{}{Al momento avrei altro da fare. Che cosa vuoi?}
{132}{}{Madame Modjeska e' indisposta, oggi. Che cosa vuoi da lei?}
{133}{}{Mi sento come se la mia testa stesse per spaccarsi in due. Che cosa vuoi da me?}
{134}{}{Io sono Madame Modjeska. Ex Jetomane, tra le altre cose. Adesso mi occupo d'altro. Penso che il Jet non faccia piu' per me. }
{135}{}{Cosa puo' fare Madame per te?}
{136}{}{Di cosa ti occupi, Madame Modjeska?}
{137}{}{Looks as though a lot of people here are drug-users. What's going on in town lately?}
{138}{}{Gira qualche voce interessante?}
{139}{}{Perche' ti chiamano Madame Modjeska?}
{140}{}{C'e' qualcosa che non va?}
{141}{}{Che cosa ti e' successo?}
{142}{}{Ultimamente non faccio molto. Una volta aiutavo Lou a gestire il Malamute Saloon - ma poi abbiamo litigato e io me ne sono andata.}
{143}{}{Lascia che ti chieda qualcos'altro.}
{144}{}{Capisco. Beh, questo e' tutto quello che volevo sapere. Arrivederci.}
{145}{}{L'argomento piu' gettonato e' sicuramente la politica. Ci si scalda sempre molto quando si discute di certi argomenti.}
{146}{}{La politica? Che cosa vuoi dire?}
{147}{}{Okay. Lascia che ti chieda qualcos'altro.}
{148}{}{Bene, questo e' tutto cio' che volevo sapere. Arrivederci.}
{149}{}{Una volta lavoravo al Malamute Saloon. Per questo motivo, la gente mi chiamava Madame. E il nome mi e' rimasto, sebbene io non lavori piu' in quel locale.}
{150}{}{E adesso dove lavori?}
{151}{}{Lascia che ti chieda qualcos'altro.}
{152}{}{Credo sia tutto, per adesso. Ci vediamo.}
{153}{}{Qualche giorno fa mi sono sparata una dose di Jet che mi ha fatto stare piuttosto male. Doveva essere una partita tagliata male. Non ho certo voglia di riprovarci. Oh beh, immagino che sia giunto il momento di attaccarsi di nuovo alla cara, vecchia bottiglia.}
{154}{}{Una brutta storia. Lascia che ti chieda qualcos'altro.}
{155}{}{Capisco. Beh, questo e' tutto quello che volevo sapere. Arrivederci.}
{156}{}{Mi sento meglio di quanto non sembri. Non molto, ma abbastanza.}
{157}{}{Cosa vuoi dire? Cos'e' successo?}
{158}{}{Hai mai visto un rodeo con i brahmin coperti di grasso?}
{159}{}{Certamente. Uh, decine di volte. Lascia che ti chieda qualcos'altro.}
{160}{}{No, non ho mai sentito parlare di una cosa del genere. Dimmi di piu'.}
{161}{}{Non so cosa questo abbia a che fare con la politica locale e non credo di volerlo sapere. Addio.}
{162}{}{Dopo quell'ultima partita di Jet tagliato male, ho smesso di prendere quella roba. Magari, quando mi sentiro' meglio, mi prendero' una bella sbronza. (Ride)}
{163}{}{Beh, buon per te... credo. Vorrei chiederti una cosa.}
{164}{}{Interessante. Beh, riprenditi in fretta. Ci vediamo.}
{165}{}{In pratica si ricopre di grasso un vitello di brahmin, e poi tutti cercano di catturare il vitello. Se non riesci a prenderlo tu, cerchi in tutti i modi di non farlo prendere nemmeno agli altri.}
{166}{}{Non capisco cosa questo abbia a che fare con la politica.}
{167}{}{Si', certo. Ho sentito abbastanza, Madame Modjeska. Ci vediamo.}
{168}{}{In questo gioco, Redding e' il brahmin coperto di grasso - e dorato, per di piu'. New Reno, la New California Republic, e Vault City stanno tutte cercando di catturarci... o almeno cercano di impedire alle altre di farlo.}
{169}{}{Che cosa vuoi dire?}
{170}{}{Bello. Beh, sara' meglio che vada, Madame. Grazie per le informazioni. Ci vediamo.}
{171}{}{Qui a Redding si estrae l'oro. Poi noi lo inviamo a New Reno, NCR e Vault City in cambio di vari beni di consumo. Ognuno di questi posti vorrebbe avere l'oro - e il commercio da esso derivato - tutto per se'.}
{172}{}{Perche' non vi attaccano e se lo prendono con la forza, allora?}
{173}{}{E chi non lo farebbe? Credo che cerchero' di trovare un po' d'oro anch'io. Grazie e arrivederci.}
{174}{}{Siamo abbastanza grandi e anche abbastanza distanti, il che rende l'invasione una tattica costosa e pericolosa. Sarebbe molto meglio se fossimo noi ad unirci a uno di loro di nostra volonta'.}
{175}{}{Che cosa vuoi dire?}
{176}{}{Il ragionamento fila. Grazie per avermi dato queste dritte. Ci vediamo.}
{177}{}{Le tre potenze stanno cercando di convincere Redding a scegliere con quale di loro allearsi. Tutte e tre hanno potenti alleati, qui in citta', e sembra che la faccenda stia per arrivare al dunque. Presto, Redding sara' costretta a fare una scelta.}
{178}{}{Una scelta?}
{179}{}{Chi lavora per chi?}
{180}{}{Denaro... Hmm. Beh, devo andare. Arrivederci.}
{181}{}{Lo strato di grasso sul vitello si sta assottigliando. Presto, una delle potenze sara' costretta a fare una mossa decisiva per prendere Redding prima che lo facciano le altre due. Quando cio' accadra', le persone, molte persone, soffriranno.}
{182}{}{Chi lavora per chi?}
{183}{}{Perche' una cosa del genere comporterebbe una danno per le persone?}
{184}{}{Grazie per le informazioni. Ci vediamo.}
{185}{}{Non sono sicura al cento per cento, ma credo che la situazione sia questa: Dan McGrew tifa New Reno, Marge LeBarge sta con NCR, Doc Johnson e' per Vault City, e il sindaco Ascorti non so da che parte stia.}
{186}{}{Come potrebbero queste persone aiutare una delle tre potenze a prendere il controllo della citta'?}
{187}{}{Chi e' Marge LeBarge?}
{188}{}{Chi e' Dan McGrew?}
{189}{}{Chi e' il dottor Johnson?}
{190}{}{Chi e' il sindaco Ascorti?}
{191}{}{Grazie per le informazioni. Ci vediamo.}
{192}{}{Le persone soffriranno perche' un cambiamento di questo tipo non avviene in modo indolore. E chi teme di non riuscire a vincere il premio, si mette in testa di fare in modo che anche gli altri non lo prendano. L'unico modo per evitare tutto cio' sarebbe quello di decidere con quale potenza andare e stringere rapidamente un'alleanza prima che gli altri si facciano sotto.}
{193}{}{Cosa pensi che succedera'?}
{194}{}{Capisco. Grazie. Arrivederci.}
{195}{}{Credo che la gente di qui seguira' le decisioni del sindaco Ascorti. E' un imbroglione, ma le persone si fidano di lui. E lui seguira' il piu' forte. Vedi, tutto cio' che e' buono per Ascorti lo sara' anche per Redding. Non credo che sia ancora riuscito a capire chi sia piu' vicino al vertice. Ma presto dovra' scegliere.}
{196}{}{Lascia che ti chieda qualcos'altro.}
{197}{}{Grazie per avermi fatto sapere cosa sta succedendo in citta'. Ci vediamo.}
{198}{}{Marge LeBarge e' la proprietaria della Miniera Kokoweef. Questa e la Morningstar sono le uniche due miniere rimaste aperte a Redding. Credo che Marge sia vicina a NCR. Non penso che il loro "puritanesimo" le piaccia, ma sa riconoscere il potere, quando lo vede.}
{199}{}{Chi e' Dan McGrew?}
{200}{}{Chi e' il dottor Johnson?}
{201}{}{Chi e' il sindaco Ascorti?}
{202}{}{Come potrebbero queste persone aiutare una delle tre potenze a prendere il controllo della citta'?}
{203}{}{Grazie per le informazioni. Ci vediamo.}
{204}{}{"Dangerous" Dan McGrew, ah, si'. E' il proprietario della Miniera Morningstar. Questa e la Kokoweef sono le uniche due miniere rimaste aperte a Redding. Credo che Dan penda piu' dalla parte di New Reno, se proprio devo buttarla la'. Gli piace che i suoi minatori siano drogati e felici.}
{205}{}{Chi e' Marge LeBarge?}
{206}{}{Chi e' il dottor Johnson?}
{207}{}{Chi e' il sindaco Ascorti?}
{208}{}{Come potrebbero queste persone aiutare una delle tre potenze a prendere il controllo della citta'?}
{209}{}{Grazie per le informazioni. Ci vediamo.}
{210}{}{Ascorti e' il sindaco. Ha un locale in centro, l'Ace. Si occupa della compravendita di un sacco di cose. Ha le mani in pasta praticamente in qualsiasi faccenda.}
{211}{}{Ascorti e' il sindaco di Redding. Ma non so dove sia finito. E da un po' che non lo vedo in giro.}
{212}{}{Lascia che ti chieda qualcos'altro.}
{213}{}{Credo di averti ascoltato abbastanza. Ci vediamo.}
{214}{}{Il Jet e' una droga meravigliosa che mi aiuta ad affrontare quest'esistenza miserabile, baby.}
{215}{}{Lascia che ti chieda qualcos'altro.}
{216}{}{Interessante. Grazie e arrivederci.}
{217}{}{Il Jet e' una droga che mi aiuta a sentirmi davvero viva. E' come se volassi nel cielo, col Jet.}
{218}{}{Lascia che ti chieda qualcos'altro.}
{219}{}{Interessante. Grazie e arrivederci.}
{220}{}{Mmmm, ti diro' cos'e' il Jet. E' una delizia, ecco cos'e'. Il Jet ha qualcosa da offrire per tutti.}
{221}{}{Lascia che ti chieda qualcos'altro.}
{222}{}{Interessante. Grazie e arrivederci.}
{223}{}{Il Jet *era* una cosa grandiosa. Adesso mi fa rivoltare lo stomaco come se fossi una vecchia lavatrice. Non consiglierei ad anima viva di provare l'ultima partita. Il Jet ha finito il suo carburante e si e' schiantato, baby.}
{224}{}{Certo, scusa se te l'ho chiesto. Lascia che ti chieda qualcos'altro.}
{225}{}{Interessante. Grazie e arrivederci.}
{226}{}{C'era qualcosa di dannatamente sbagliato nell'ultima partita di Jet che e' arrivata in citta'. Si e' schiantato al decollo, quel Jet. Credo che diro' addio ai miei "voli" quotidiani. Ubriacarsi, invece - ecco una cosa che non ti puo' tradire.}
{227}{}{Lascia che ti chieda qualcos'altro.}
{228}{}{Interessante. Grazie e arrivederci.}
{229}{}{Doc "Indolore" Johnson e' una specie di uomo del mistero. Non so da dove venga, ma sicuramente e' un vero dottore. L'unico posto dove puo' aver ricevuto un'educazione simile e' Vault City. Scommetto che e' stato piazzato qui per appoggiare i loro interessi. Tuttavia, deve aver proprio fatto incavolare qualcuno di importante, visto che l'hanno mandato qui; quei "cittadini" non amano molto il mondo esterno.}
{230}{}{Chi e' Marge LeBarge?}
{231}{}{Chi e' Dan McGrew?}
{232}{}{Chi e' il sindaco Ascorti?}
{233}{}{Come potrebbero queste persone aiutare una delle tre potenze a prendere il controllo della citta'?}
{234}{}{Grazie per le informazioni. Ci vediamo.}
{235}{}{Il sindaco e' un uomo che sa come giocare su due fronti diversi mentre ruba al centro. E' un uomo con pochi scrupoli, ma fara' cio' che e' giusto per Redding. Ovvero fara' cio' che gli permettera' di salvare i suoi interessi.}
{236}{}{Chi e' Marge LeBarge?}
{237}{}{Chi e' Dan McGrew?}
{238}{}{Chi e' il dottor Johnson?}
{239}{}{Come potrebbero queste persone aiutare una delle tre potenze a prendere il controllo della citta'?}
{240}{}{Grazie per le informazioni. Ci vediamo.}
