{100}{}{Vedi una giovane donna, un vero maschiaccio, vestita con un completo da lavoro.}
{101}{}{E' Dorothy, il meccanico cittadino.}
{102}{}{Dalla quantita' di olio e di sporco che ha addosso, si direbbe una patita delle riparazioni, soprattutto per il robot addetto alla manutenzione che la segue dappertutto.}
{103}{}{Mioddio, qualcuno deve fare qualcosa! Cosa faccio? Ho bisogno di aiuto, in fretta.}
{104}{}{Huh? Gug?}
{105}{}{Cosa sta succedendo?}
{106}{}{Tu viene con me. Ferma uomo cattivo. Ferma lui, no fare rompere macchina. Okay?}
{107}{}{Okay.}
{108}{}{No, me no viene.}
{109}{}{Oddio, e' Jack. Sta minacciando di far esplodere la centrale. Non c'e' piu' tempo, devi fermarlo per me. Puoi farlo, vero?}
{110}{}{Basta perdere tempo. Portami da lui.}
{111}{}{Non e' compito mio. Cercati qualcun altro.}
{112}{}{Ascolta - Jack e' all'interno. E' infuriato con la sua ex moglie. Le cose non gli vanno bene, ultimamente. Dice di avere una bomba. Se e' cosi', probabilmente l'ha piazzata vicino alla dinamo. Senti, vedi se puoi convincerlo a rinunciare al suo progetto, ma qualunque cosa tu faccia non permettere a quella bomba di esplodere!}
{113}{}{Come dovrei fare?}
{114}{}{Non preoccuparti, ci penso io.}
{115}{}{Non lo so! Sono solo il meccanico della citta'. Prova tu ad inventarti qualcosa!}
{116}{}{Merda! Ha danneggiato l'unita' centrale. Bisogna rimetterla in sesto prima che le cose vadano davvero male. Sei bravo a riparare le cose?}
{117}{}{Urrgh.}
{118}{}{Si'.}
{119}{}{No.}
{120}{}{A cosa stavo pensando?}
{121}{}{Senti, fa' tutto quello che puoi con il generatore. Io devo stabilizzare il nucleo. Hai circa 30 secondi, credo. Dopo di che sara' troppo tardi. Vieni, Toto.}
{122}{}{Cavoli! Allora sta' indietro. A meno che io non sia davvero fortunata, l'intero impianto esplodera'. Andiamo, Toto.}
{123}{}{L'hai riparata? Senza pezzi di ricambio? E' incredibile! Dove hai imparato a farlo?}
{124}{}{Huh-huh!}
{125}{}{Semplice abilita' manuale, ecco tutto.}
{126}{}{Ho capito. Tu sei uno di quei tipi un po' stupidi - come si chiamano...? Idioti sapienti. Beh, senti, idiota o no, ti meriti una ricompensa. RI-COM-PEN-SA - tu. Ti do dei bei libri. Vedi? Prendi soldi. Bene... immagino tu non sappia leggere.}
{127}{}{Guarda, non e' molto, ma ho qualche libro - vecchi manuali tecnici. Sono tuoi. Prendili.}
{128}{}{Ehi, guarda, Toto. E' lo straniero che ci ha aiutati. Grazie ancora, mister.}
{129}{}{Merda! La griglia e' completamente andata. Ci vorra' un sacco di tempo per ripararla. Non perdiamoci in chiacchiere. Vieni, Toto.}
{130}{}{Senti, non do la colpa a te di quello che e' successo, ma non sono proprio dell'umore giusto per chiacchierare.}
{131}{}{L'hai ucciso! Voglio dire: dovevi proprio ucciderlo? Non c'era un altro modo?}
{132}{}{Si'.}
{133}{}{No.}
{134}{}{Allora avresti dovuto provarci, invece di ucciderlo e basta. Fuori di qui, mostro che non sei altro!}
{135}{}{E' terribile. Mi domando cosa l'abbia spinto a farlo. La citta' ti deve dei ringraziamenti. Guarda, non e' molto, ma ecco alcuni manuali che avevo da parte. Magari puoi venderli.}
{136}{}{Non parlarmi, sporco assassino.}
{137}{}{Non posso fermarmi a chiacchierare, straniero. Il mio nome e' Dorothy, meccanico cittadino e questo e' Toto. Devo scappare.}
{138}{}{Non hai un modulatore ad Illudium Q-38, vero? Come immaginavo...}
{139}{}{Sei riuscito a convincerlo? Incredibile! La citta' ti deve davvero molto, mister. Guarda, non e' molto, ma ecco alcuni manuali che avevo da parte. Magari puoi venderli.}
{140}{}{Volevo solo farti sapere che sono ancora impressionata per quello che hai fatto con Jack. Io e Toto dobbiamo scappare adesso. Ciao!}
{141}{}{Merda! Ho solo un consiglio da darti: SCAPPA!}
{142}{}{Ehi, guarda, Toto. E' la straniera che ci ha aiutato. Grazie ancora, miss.}
{143}{}{Sei riuscita a convincerlo? Incredibile! La citta' ti deve davvero molto, miss. Guarda, non e' molto, ma ecco alcuni manuali che avevo da parte. Magari puoi venderli.}
{144}{}{Non perdere tempo! Fa sul serio.}
{145}{}{Devi fare qualcosa! Subito!}
{146}{}{Non startene li' impalato -- fermalo!}
{147}{}{Fuori di qui, sacco di merda di brahmin.}
{148}{}{Non parlare con me, codardo.}
{149}{}{Sei una persona inutile!!}
