{100}{}{Vedi una donna che indossa l'armatura corazzata di NCR.}
{101}{}{E' il capitano delle guardie.}
{102}{}{Sara' anche una donna, ma il fucile a pompa al suo fianco dice che si tratta di un osso duro.}
{103}{}{Mi dovrai scusare, sono una donna molto occupata. Non ho tempo per chiacchierare.}
{104}{}{Fatti gli affari tuoi rispettando la legge, straniero, e non ci saranno guai.}
{105}{}{Hai delle domande? Cerca lo sceriffo Dumont. Lui sapra' aiutarti.}
{106}{}{Le leggi sono affisse sulla bacheca pubblica - niente armi, niente alcolici, niente guai.}
{107}{}{Cosa posso fare per te, straniero?}
{108}{}{Ancora tu?}
{109}{}{Me entrare.}
{110}{}{Vorrei entrare a NCR.}
{111}{}{Nulla.}
{112}{}{Non andrai da nessuna parte finche' non avrai messo via quelle armi.}
{113}{}{Tutti sono tenuti a metter via le loro armi.}
{114}{}{Hmm...beh, sembreresti una persona abbastanza rispettabile. Qual e' il tuo nome? Devo metterlo nel registro.}
{115}{}{}
{116}{}{Ecco fatto, faro' aprire il cancello per te in un attimo.}
{117}{}{Non avvicinarti! Sei pregato di andartene immediatamente o ci saranno guai.}
