{100}{}{Sembra solo un altro tizio che ragiona piu' con i pugni che con la testa.}
{101}{}{Hmmm. Una delle guardie di Merk.}
{102}{}{Grosso. Robusto. Stupido. Gorilla.}
{103}{}{State indietro. Fate spazio a Mr. Merk.}
{104}{}{Uhh...}
{105}{}{Non sono autorizzato a parlare con nessuno quando sono in servizio.}
{106}{}{Dovessi darci dei problemi, io sono qui per risolverli. Capito?}
{107}{}{Perche' non smammi, okay?}
{108}{}{Non scocciarmi.}
{109}{}{Mr. Merk non vuole essere disturbato.}
