{100}{}{Vedi uno degli abitanti.}
{101}{}{Vedi un rappresentante della gente locale.}
{102}{}{L'aspetto di questa persona non ha nessun particolare di rilievo.}
{103}{}{Ahhh, lasciami in pace.}
{104}{}{Mi dispiace. Non lo rifaro' piu'.}
{105}{}{Stavo proprio per andarmene.}
{106}{}{Guardie, e' tornato!}
{107}{}{Lasciami in pace.}
{108}{}{Senti, neanch'io vorrei starti tra i piedi.}
{109}{}{Tu sei il male. Sei pregato di non parlare con me.}
{110}{}{Lascia in pace i nostri figli.}
{111}{}{Tu sei un criminale malato. Spero che le guardie ti becchino.}
{112}{}{Vattene via, okay?}
{113}{}{Ehi, non dovresti uccidere le persone - e soprattutto i bambini.}
{114}{}{Non credo che tu mi piaccia.}
{115}{}{Ehi, fammi sapere quando stai per andare fuori di matto.}
{116}{}{Devo andare.}
{117}{}{Chi diavolo credi di essere per venire in questa citta'?}
{118}{}{Vattene, prima che qualcuno si faccia male.}
{119}{}{Non mi piaci.}
{120}{}{I buoni uccideranno tutti quelli come te.}
{121}{}{Qual e' il tuo problema?}
{122}{}{Non possiamo semplicemente essere amici?}
{123}{}{Non parlarmi.}
{124}{}{Qualunque cosa tu voglia dirmi, dilla a qualcun altro.}
{125}{}{Non credo che tu sia cosi' duro.}
{126}{}{Perche' non te ne vai e basta?}
{127}{}{Bene, devo andare a prendere delle uova.}
{128}{}{Sai per caso come aprire una lattina dal verso giusto?}
{129}{}{Ehila'.}
{130}{}{Per favore, non disturbarmi: sono molto occupato.}
{131}{}{Mi domando se ci siano degli altri brahmin-burger al Dusty's.}
{132}{}{A volte mi chiedo dove io stia andando.}
{133}{}{Umm, grazie, devo proprio andare.}
{134}{}{Magari dopo potremmo pranzare insieme.}
{135}{}{Ohh, certo, tu sei quello nuovo.}
{136}{}{Dovresti parlare con lo sceriffo.}
{137}{}{Ho sentito che presto costruiranno delle altre case.}
{138}{}{La citta' e' piuttosto tranquilla da quando Dumont e' stato eletto.}
{139}{}{Buona giornata, straniero.}
{140}{}{Questo e' proprio un posticino tranquillo. Bello, eh?}
{141}{}{Sei nuovo? Fai un salto al Duppo's: mio cugino lavora li'.}
{142}{}{Ho sentito che le cose a sud non vanno bene. Quand'e' che il governo si decidera' a fare qualcosa?}
{143}{}{Vieni da nord? Non si vedono molti settentrionali da queste parti.}
{144}{}{Ho sentito dire che tutti quelli che vengono dalle Lande sono mutanti o selvaggi!}
{145}{}{Non ho tempo per chiacchierare. Devo andare al lavoro.}
{146}{}{C'e' una svendita da Duppo's? Oh, come non detto.}
