{100}{}{Vedi una persona che indossa dei vestiti da lavoro polverosi.}
{101}{}{Uno dei braccianti del ranch di Westin.}
{102}{}{Potrebbe essere un semplice bracciante, ma potrebbe anche essere un sicario. Sicuramente sembra pronto a cacciarsi nei guai.}
{103}{}{Che cosa ci fai qui?}
{104}{}{Parla con Felix se stai cercando un lavoro, straniero.}
{105}{}{Non ne posso piu' dei brahmin.}
{106}{}{Ho sentito che i Bishop ce l'hanno con il nostro capo.}
{107}{}{Se vuoi parlare con qualcuno, parla con il capomastro, Felix.}
{108}{}{You ain't with the Bishops, are you?}
{109}{}{Sappiamo che si e' trattato di un omicidio. Prenderemo quel verme, e la sua morte non sara' tanto rapida.}
{110}{}{Felix e' sicuro che ci siano i Bishop dietro a questa faccenda. Dice che devono aver assoldato qualcuno.}
{111}{}{Beh, credo sia tempo di levare le tende. Qui le cose stanno andando a rotoli.}
