{100}{}{Vedi un barista.}
{101}{}{Vedi un uomo alto che indossa un vestito elegante. Ha lo sguardo fisso davanti a se' e non presta attenzione ai clienti che gli stanno attorno.}
{102}{}{Vedi un barista.}
{103}{}{Quest'uomo e' imperturbabile. Se ti ha notato, non lo da' a vedere.}
{104}{}{Che ne dice di un bicchierino, eroe?}
{105}{}{Benvenuto, eroe. Prego, venga a sedersi qui al bancone.}
{106}{}{Prego! Prendi una sedia e riposati per un attimo!}
{107}{}{Buon giorno, Capitano.}
{108}{}{Vault City prevale, Capitano.}
{109}{}{Buongiorno, Cittadino.}
{110}{}{Vault City prevale, Cittadino.}
{111}{}{Un mutante! Guardie! Guardie!}
{112}{}{Un ghoul! Guardie! Guardie!}
{113}{}{Mi spiace, ma di sera il bar e' chiuso.}
{114}{}{Il bar e' chiuso. Tornero' a casa non appena avro' finito di compilare l'inventario.}
{115}{}{Ma non hai una casa dove andare?}
{116}{}{Benvenuto! Abbiamo tutti sentito parlare delle sue imprese contro l'Enclave. Posso portarle qualcosa da bere?}
{117}{}{Awnt-awnt}
{118}{}{-Allontanati-}
{119}{}{Cosa avete da bere?}
{120}{}{Vorrei alcune informazioni.}
{121}{}{Per oggi niente, grazie.}
{122}{}{Eh eh, "awnt-awnt" anche a te. Mi raccomando: fa' attenzione quando viaggi nelle Lande.}
{123}{}{Oonnt-oooont!}
{124}{}{-Allontanati-}
{125}{}{Cosa posso fare per lei, Capitano?}
{126}{}{Cosa posso fare per te, Cittadino?}
{127}{}{Si'? Posso aiutarla?}
{128}{}{Awnt-awnt}
{129}{}{-Allontanati-}
{130}{}{Cosa avete da bere?}
{131}{}{Vorrei alcune informazioni.}
{132}{}{Per oggi niente, grazie.}
{133}{}{Si', "awnt-awnt" anche a te. Aspetta qui un secondo mentre io chiamo le guardie per farti "awnt-awntare" fino al cancello.}
{134}{}{Urnt? Urnt-urnt.}
{135}{}{-Allontanati-}
{136}{}{"Una sete del demonio"? Che espressione... rozza.}
{137}{}{Abbiamo acqua minerale, acqua distillata e acqua frizzante. Abbiamo anche diverse qualita' di alcolici sintetici.}
{138}{}{Um... che tipo di alcolici sintetici avete?}
{139}{}{Uh, non avete degli alcolici veri?}
{140}{}{Un po' d'acqua andra' benissimo.}
{141}{}{Come non detto. Vorrei alcune informazioni.}
{142}{}{Per oggi niente, grazie.}
{143}{}{Molto bene, signore.}
{144}{}{Molto bene, signora.}
{145}{}{Che tipo d'acqua desidera? Minerale? Distillata? O frizzante? Ciascuna costa la modesta cifra di cinque dollari il bicchiere.}
{146}{}{Minerale, per favore.}
{147}{}{Provero' un po' di acqua distillata.}
{148}{}{Riempimi un bicchiere d'acqua frizzante.}
{149}{}{Che tipo di alcolici sintetici avete?}
{150}{}{Come non detto. Vorrei alcune informazioni.}
{151}{}{E' un po' troppo caro per me. Tornero' quando avro' qualche soldo in piu'.}
{152}{}{Credo che non prendero' nulla, grazie.}
{153}{}{Abbiamo i derivati sintetici H e T. Da poco e' disponibile una miscela gia' molto popolare, la "Alcol-Z", che ha un forte pseudo-sapore di pseudo-luppolo lasciato a fermentare pseudo-naturalmente. Ognuno di questi alcolici sintetici lo vendiamo a venti dollari la pinta.}
{154}{}{Come producete questi alcolici sintetici?}
{155}{}{Uh, non avete degli alcolici veri?}
{156}{}{Credo che prendero' solo un po' d'acqua.}
{157}{}{Hmmm. Provero' ad assaggiare questa deliziosa Alcol-Z.}
{158}{}{Lasciamo stare. Vorrei alcune informazioni.}
{159}{}{E' un po' troppo caro per me. Tornero' quando avro' qualche soldo in piu'.}
{160}{}{Per oggi niente, grazie.}
{161}{}{Desidera qualcos'altro?}
{162}{}{Vorrei dell'acqua, grazie.}
{163}{}{Che tipo di alcolici sintetici avete?}
{164}{}{Come non detto. Vorrei alcune informazioni.}
{165}{}{Per oggi niente, grazie.}
{166}{}{Si sente bene, signora? Sembra che tutta quell'Alcol-Z abbia avuto un qualche effetto su di lei. E' sicuro di volerne ancora?}
{167}{}{Si sente bene, signora? Sembra che tutta quell'Alcol-Z abbia avuto un qualche effetto su di lei. E' sicuro di volerne ancora?}
{168}{}{Desidera qualcos'altro?}
{169}{}{Non mi sento troppo bene... Sara' meglio che esca per un attimo da questo dialogo e vada a controllare il valore massimo dei miei punti vita.}
{170}{}{No, no, mi sento benissimo! Voglio solo uscire un attimo da questo dialogo e controllare il valore massimo dei miei punti vita.}
{171}{}{Credo che prendero' solo un po' d'acqua.}
{172}{}{Voglio ancora un goccetto di quella deliziosa Alcol-Z.}
{173}{}{Come producete questi alcolici sintetici?}
{174}{}{In realta', vorrei delle informazioni.}
{175}{}{Nient'altro per oggi, grazie.}
{176}{}{The Auto-Docs within Vault City can brew synthetic substitutes for otherwise addictive substances. As I understand it, these synthetics were used as placebos for drug addicts before the war.}
{177}{}{Sembri molto ferrato in materia di sostituti sintetici...}
{178}{}{Uh, non avete degli alcolici veri?}
{179}{}{Oh. Beh, allora prendero' un po' d'acqua.}
{180}{}{Hmmm. Provero' ad assaggiare questa Alcol-Z.}
{181}{}{Interessante. Senti, vorrei alcune informazioni...}
{182}{}{Capisco. Grazie per le informazioni. Ci vediamo.}
{183}{}{Sono stato il Servo del Dr. Troy per alcuni mesi, prima di essere assegnato qui. Per servirlo adeguatamente mi era richiesto un minimo di "know-how" informatico per accedere al database medico di Vault City.}
{184}{}{"Knock-out"? E per accedere al database dovevi mettere al tappeto il computer?}
{185}{}{Database medico?}
{186}{}{Interessante. Senti, vorrei alcune informazioni...}
{187}{}{Capisco. Grazie per le informazioni. Ci vediamo.}
{188}{}{Er... "know-how" significa "le cognizioni tecniche".}
{189}{}{Huh. Beh, se credi di riuscire a confondermi con questi paroloni, ti sbagli. Cos'e' che dicevi a proposito del database medico?}
{190}{}{Vorrei delle altre informazioni...}
{191}{}{Se ti nascondi dietro parole complicate per non parlare con me, allora me ne vado. A dopo.}
{192}{}{Si', alcuni dei computer situati al primo piano del Vault contengono un'estesa gamma di informazioni mediche. Piuttosto affascinante, non c'e' dubbio, anche se il gergo potrebbe risultare un po' ostico per chi non ha conoscenze di medicina.}
{193}{}{Gergo? E' la persona che si occupa dei computer?}
{194}{}{Interessante. Senti, vorrei alcune informazioni...}
{195}{}{Hmmmm. Magari andro' a darci un'occhiata.}
{196}{}{Uh, no. Per "gergo" s'intende il linguaggio, la terminologia, di solito riferiti ad una professione particolare.}
{197}{}{Uh, certo, certo. Volevo solo vedere se eri attento. Senti, vorrei alcune informazioni...}
{198}{}{Se lo dici tu. A me basta solo che questo tipo, Gergo, mi permetta di usare i computer, okay? Arrivederci.}
{199}{}{Se sta parlando di quello che nelle Lande spacciano per alcol, allora no.}
{200}{}{Non abbiamo mai sentito il bisogno di avvelenare il nostro organismo con quei miscugli pieni di batteri. Forse il bar nel Cortile e' meno... discriminante.}
{201}{}{Prendero' solo un po' d'acqua, allora.}
{202}{}{Aspetta un secondo. Che tipo di "alcolici sintetici" avete?}
{203}{}{Vorrei alcune informazioni.}
{204}{}{Andro' a darci un'occhiata, grazie.}
{205}{}{Forse andro' da qualche altra parte, allora.}
{206}{}{Forse dovrebbe recarsi al nostro Centro Informazioni, invece di starsene qui. Lo puo' trovare vicino ai cancelli cittadini. Adesso se ne vada... ho altri clienti.}
{207}{}{Aspetta, volevo qualcosa da bere. Che cosa avete? Ho una sete del demonio...}
{208}{}{No, credo che prima tu mi dirai quello che voglio sapere. E vedi anche di moderare il tono, se non vuoi avere guai.}
{209}{}{Bene. Allora, buona giornata.}
{210}{}{Certo. Che cosa le serve sapere, signore?}
{211}{}{Certo. Che cosa le serve sapere, signora?}
{212}{}{Certo. Che cosa le serve sapere, Capitano?}
{213}{}{Certo. Che cosa le serve sapere, Cittadino?}
{214}{}{Puoi dirmi chi e' il leader di Vault City?}
{215}{}{Puoi dirmi due parole riguardo alla pratica della schiavitu' qui a Vault City?}
{216}{}{Lasciamo perdere. Vorrei qualcosa da bere. Che cosa avete? Ho una sete del demonio...}
{217}{}{Per oggi niente, grazie.}
{218}{}{Beh, e' il Primo Cittadino Lynette, naturalmente. Ricopre questa carica da quasi due mandati. Sebbene debba comunque rendere conto al Consiglio, e' la responsabile primaria per quanto riguarda i punti fondamentali della legislazione di Vault City.}
{219}{}{Al Consiglio?}
{220}{}{Puoi dirmi due parole riguardo alla pratica della schiavitu' qui a Vault City?}
{221}{}{Lasciamo perdere. Vorrei qualcosa da bere. Che cosa avete? Ho una sete del demonio...}
{222}{}{Interessante. Grazie delle informazioni. Arrivederci.}
{223}{}{Si', esiste anche un Consiglio cittadino di Vault City. Il suo portavoce e' il Senatore McClure. (Si avvicina) McClure e il Primo Cittadino si sono scontrati parecchie volte, infatti.}
{224}{}{Davvero...?}
{225}{}{Puoi dirmi due parole riguardo alla pratica della schiavitu' qui a Vault City?}
{226}{}{Lasciamo perdere. Vorrei qualcosa da bere. Che cosa avete? Ho una sete del demonio...}
{227}{}{Interessante. Grazie delle informazioni. Arrivederci.}
{228}{}{Oh, si'. Ultimamente, alcuni Cittadini hanno chiesto a McClure e al Consiglio di annullare alcune delle decisioni del Primo Cittadino. E lasci che glielo dica, la cosa ha creato un bel po' di scalpore.}
{229}{}{Hmmm. Mi piacerebbe sapere qualcos'altro...}
{230}{}{Capisco. Beh, adesso vorrei bere qualcosa. Che cosa avete? Ho una sete del demonio...}
{231}{}{Interessante. Grazie delle informazioni. Arrivederci.}
{232}{}{Oh, no, no... it's not slavery. Those people you see working in the city are servants... myself included. We are treated very well here, taught to read and write, and given medical care, homes and food.}
{233}{}{Avete tutto tranne la liberta', eh?}
{234}{}{Se non avete nulla di cui lamentarvi, allora il problema non sussiste. Come non detto.}
{235}{}{Lasciamo perdere. Vorrei qualcosa da bere. Che cosa avete? Ho una sete del demonio...}
{236}{}{Capisco. Beh, grazie per aver parlato con me. Addio.}
{237}{}{Se non vuole ordinare qualcosa da bere, forse farebbe meglio ad andarsene, signora.}
{238}{}{Se non vuole ordinare qualcosa da bere, forse farebbe meglio ad andarsene, signore.}
{239}{}{Se non vi lamentate della vostra condizione di... servi, allora il problema non sussiste. Come non detto.}
{240}{}{Prendero' qualcosa da bere, allora. Che cosa avete? Ho una sete del demonio...}
{241}{}{Forse hai ragione. Buona giornata.}
{242}{}{D'accordo. C'e' qualcos'altro che posso fare per aiutarla?}
{243}{}{Prendero' qualcosa da bere, allora. Che cosa avete? Ho una sete del demonio...}
{244}{}{Non adesso. Buona giornata.}
{245}{}{Zzzzzz.}
