{100}{}{Vedi un uomo con lo sguardo allucinato. Malgrado i capelli spettinati e la barba incolta, i suoi abiti sembrano molto puliti e ben tenuti.}
{101}{}{Vedi Thomas Moore.}
{102}{}{Vedi Thomas Moore. Malgrado i capelli spettinati e la barba incolta, i suoi abiti sembrano molto puliti e ben tenuti.}
{103}{}{Salve e benvenuto, viaggiatore! Hai udito la parola, oggi?}
{104}{}{Uurmph}
{105}{}{Ecch}
{106}{}{Portzebie}
{107}{}{-Allontanati-}
{108}{}{Beh, no... non l'ho sentita.}
{109}{}{E tu saresti...?}
{110}{}{Uh, no, e non ne ho nemmeno voglia. Addio. }
{111}{}{La parola, amico mio... la parola e' EGOISMO. Mischiala con un sacco di alterigia, e che cosa ottieni? Vault City... in tutta la sua gloria ipocrita e schiavista.}
{112}{}{Perche' vivi in questa citta', se la odi cosi' tanto?}
{113}{}{Amen, fratello!}
{114}{}{Credo di aver sentito abbastanza. Ci vediamo.}
{115}{}{Va' a raccontare le tue assurdita' da qualche altra parte, amico... ne abbiamo gia' abbastanza.}
{116}{}{Si'! }
{117}{}{E' TEMPO di ascoltare il lamento dei nostri fratelli al di fuori di queste mura e di lasciarli entrare! Abbiamo cibo e rifugio in abbondanza anche per i nostri fratelli... non abbiamo bisogno di essere ricchi quando cosi' TANTA gente e' povera.}
{118}{}{Hai ragione!}
{119}{}{Finalmente qualcuno con un po' di ragione da vendere! Perche' altri devono soffrire, quando l'aiuto risiede all'interno di queste mura?}
{120}{}{Ho sentito abbastanza. Addio.}
{121}{}{Amico... mentre ti guardo io vedo FORZA. Io vedo FEDE. I miei occhi m'ingannano? O vedono forse un'anima gemella che abbraccia la mia stessa causa?}
{122}{}{Hai perfettamente ragione!}
{123}{}{Si'! Sappi che e' giunto il TEMPO... il tempo per questa citta', costruita sul peccato e la schiavitu', di aprire i suoi cancelli a tutti! }
{124}{}{Devo andare. E' stato bello parl... er, ascoltarti.}
{125}{}{Allora lascia che ti chieda questo, amico mio - fino a che PUNTO sei disposto a diffondere il verbo?}
{126}{}{Beh, dipende da quanti soldi hai con te... "amico".}
{127}{}{Nessuna distanza e' troppo grande... nessun fossato e' troppo largo, quando la causa e' giusta e il verbo veritiero. Qualunque cosa si debba fare, io la faro'!}
{128}{}{Non mi piace la piega che sta prendendo questa conversazione. Buona giornata.}
{129}{}{Anche se significasse l'esilio da quest'oasi?}
{130}{}{Questa non e' un'oasi, fratello mio. E' una citta', costruita sull'egoismo e sull'avarizia. Dev'essere salvata da se stessa... sotto questa luce, l'esilio e' forse un prezzo troppo alto da pagare? Io credo di no.}
{131}{}{Qualsiasi cosa pur di liberare dalle catene il mio prossimo!}
{132}{}{Non saprei... che cosa vuoi che faccia?}
{133}{}{Hmmm. Beh, dal momento che la metti su questo piano... no, credo di no. Buon giorno.}
{134}{}{(Si avvicina.) Ho una valigetta... contenente informazioni vitali per la nostra causa. La porteresti fino a New Reno per me? Lo farei io, ma i Cittadini mi tengono d'occhio...}
{135}{}{Quindi ammetti di avere dei legami con New Reno, eh? Questo ti costera'... "amico".}
{136}{}{Certo. Dammela pure.}
{137}{}{No, grazie... e' un pochino troppo rischioso per me. Considerami fuori.}
{138}{}{Eccola... consegnala ad un uomo, John Bishop, a New Reno. Cammina facendo attenzione, figliolo, e porta il verbo con te.}
{139}{}{Consegnare questa valigetta a John Bishop? Nessun problema.}
{140}{}{Il mio nome? Io sono Thomas Moore, predicatore del verbo e della verita'. E cosa ti porta oggi da me, amico? Tu CERCHI la parola?}
{141}{}{La parola?}
{142}{}{Uh, no, non oggi, grazie. Arrivederci.}
{143}{}{Anche chi sembra essere la creatura piu' innocente di questa terra potrebbe voler ingannare un messaggero del verbo... come faccio a sapere che tu sei un VERO credente?}
{144}{}{Tu sarai un vero credente quando ti infilero' il mio piede su per il culo!}
{145}{}{Io SONO un vero credente, fratello. Come posso dimostrarti la mia devozione?}
{146}{}{Io so che questa citta' ha costruito le sue fondamenta sul peccato e la schiavitu', e che solo i giusti potranno purificarla!}
{147}{}{Sai, magari potremmo parlarne un'altra volta.}
{148}{}{Ignorante infedele! Hai orecchie, ma non odi! Hai occhi, ma sei cieco! Sparisci dalla mia vista, lurido apostata!}
{149}{}{Lurido... uh... appost... aprostat... che? Nessuno puo' parlarmi a quel modo! Spero che tu non abbia dei familiari che possano sentire la tua mancanza, signor cadavere...}
{150}{}{Nessuno puo' parlarmi a quel modo, men che meno uno pseudo-predicatore da quattro soldi come te. Credo sia tempo di darti una lezione, cadavere.}
{151}{}{Calma. Me ne vado.}
{152}{}{Hmmmmmm. Bisogna guardarsi dai serpenti che ripetono il verbo, ma che albergano la menzogna nel loro cuore.}
{153}{}{Amen, fratello! }
{154}{}{Se non c'e' fiducia tra noi, sara' meglio che me ne vada. Addio.}
{155}{}{Uh... certo. Magari ne possiamo parlare piu' tardi.}
{156}{}{Cosa?! Come OSI ricattarmi, tu... tu... (Aggrotta le sopracciglia.) ...tu hai la mia piu' completa attenzione.}
{157}{}{Parliamo del pagamento, che ne dici?}
{158}{}{Beh... quale posto migliore ove predicare se non dove c'e' piu' bisogno di farsi ascoltare?}
{159}{}{Credo che tu abbia ragione. Chi sei?}
{160}{}{Porta la tua testimonianza, Fratello! Diffondi il verbo!}
{161}{}{Esatto! Questa citta' e' fondata sul peccato e la schiavitu', e c'e' bisogno della forza dei giusti per purificarla!}
{162}{}{Uh... giusto. Beh, e' stato bello parlare con te. Addio.}
{163}{}{Ecco... questa valigetta contiene il numero del mio conto in banca. Consegnala a John Bishop di New Reno, e lui ti dara' l'accesso al mio conto.}
{164}{}{Scordatelo. Credo che ti denuncero' lo stesso.}
{165}{}{Al diavolo il pagamento, allora. Non andro' a Reno.}
{166}{}{Ottimo! Ma sara' meglio che valga il tempo che perdo.}
{167}{}{Pare proprio che la natura ti abbia gia' punito, schiavista. Forse un giorno espierai le tue colpe.}
{168}{}{Eh... Non proprio. Sta' attento quando attraversi le Lande, mio semplice amico.}
{169}{}{Urf}
{170}{}{Allora, amico, ci hai ripensato?}
{171}{}{Ho pensato che proteggere il tuo segreto potrebbe farmi guadagnare un sacco di soldi. Hai capito quello che voglio dire?}
{172}{}{Ho visto la luce, fratello... cosa dovrei fare?}
{173}{}{No, spiacente. Buona giornata.}
{174}{}{Eh? Che cosa ci fai qui? Non hai consegnato...}
{175}{}{...la valigetta a Bishop? Beh, ci ho PROVATO... peccato che lui, dopo aver letto il messaggio che tu avevi messo nella valigetta, abbia PROVATO ad uccidermi. Piuttosto buffa come cosa, no? Spero che tu sia pronto a morire, Moore.}
{176}{}{L'ho fatto, ma sono tornato per riempirti di buchi e per coprire il tuo cadavere con una spanna di terra.}
{177}{}{Voglio solo assicurarmi che stai rigando dritto. Ci vediamo.}
{178}{}{Ah! Bentornato, compagno cercatore di verita'! Come posso aiutarti, oggi?}
{179}{}{Che cosa sai a proposito di NCR?}
{180}{}{Ho una domanda: perche' a Vault City sono presenti degli schiavi? Mi avevano detto che questa era una citta' libera.}
{181}{}{Voglio udire il verbo, fratello!}
{182}{}{Questa citta' e' fondata sul peccato e sulla schiavitu' e sono venuto a riportarla sulla retta via!}
{183}{}{Per oggi niente, grazie.}
{184}{}{So che stanno lottando per far rivivere la verita' e la giustizia, e che noi non alziamo un dito per aiutarli.}
{185}{}{Noi cosa potremmo fare, invece?}
{186}{}{Mi pare quasi un tradimento.}
{187}{}{Che peccato. Oh beh, addio.}
{188}{}{Potremmo spalancare i nostri cancelli e dare loro il benvenuto! Loro hanno bisogno del nostro aiuto, eppure CONTINUIAMO a girarci dall'altra parte, facendo finta di nulla!}
{189}{}{Amen! La tecnologia di Vault City dovrebbe essere condivisa col mondo e non essere disponibile solo per pochi eletti.}
{190}{}{Hmm... non saprei. Non ce la caviamo tanto male, qui. Abbiamo davvero bisogno di loro? Dopotutto, non farebbero altro che abbassare la nostra qualita' della vita... ci contaminerebbero, addirittura.}
{191}{}{Hmmm. Beh, e' una cosa sulla quale riflettere. Addio.}
{192}{}{Non posso risponderti, dal momento che una citta' fondata sulla schiavitu' non potra' mai essere libera veramente.}
{193}{}{Gia', ma di sicuro fanno dei bei soldoni, eh?}
{194}{}{Le tue parole... accendono qualcosa in me. Forse liberare gli schiavi e accoglierli come fratelli, sarebbe la cosa migliore per Vault City.}
{195}{}{Dovremmo liberare gli schiavi, e accoglierli come fratelli!}
{196}{}{Aw, non cercare di raccontarmi queste stronzate. La schiavitu'... e Vault City... esisteranno ancora per molto tempo.}
{197}{}{Discorso interessante. Magari ne possiamo parlare ancora in un'altra occasione.}
{198}{}{Vedo che sei un mercante di carne umana. Non ho NULLA da dire ad uno come te.}
{199}{}{Uurmph}
{200}{}{Ecch}
{201}{}{Portzebie}
{202}{}{-Allontanati-}
{203}{}{Ehi, mi sono finto uno schiavista solo per ottenere informazioni.}
{204}{}{Beh, io ho qualcosa da dire a te: perche' a Vault City ci sono gli schiavi? Mi avevano detto che questa era una citta' libera.}
{205}{}{Ehi, persino il mezzo piu' meschino giustifica un nobile fine.}
{206}{}{D'accordo, allora. Addio.}
{207}{}{E' bello vedere che l'intolleranza non muore mai. Buona giornata.}
{208}{}{Non c'e' differenza tra fingere e fare. Vade retro, schiavista.}
{209}{}{Ma mi sono reso conto dei miei errori!}
{210}{}{Adesso basta. E' ora di aprirti in due e vedere di cosa sei fatto...}
{211}{}{D'accordo.}
{212}{}{Non ho nulla da dire ad una persona che si macchia di azioni ripugnanti. Vattene.}
{213}{}{Vuoi un'azione ripugnante? Te lo FACCIO VEDERE io cos'e', un'azione ripugnante...}
{214}{}{Ho capito che la strada che avevo intrapreso era sbagliata. Sono venuto per pentirmi e per ascoltare il verbo!}
{215}{}{Il mio cuore era lacerato al pensiero dell'inumanita' dell'uomo nei confronti dell'uomo!}
{216}{}{D'accordo, allora. }
{217}{}{Ben ritrovato, compagno pellegrino! Hai consegnato le informazioni come ti avevo chiesto?}
{218}{}{Ben ritrovato, compagno pellegrino! Come posso aiutarti, oggi?}
{219}{}{Finiamola con le stronzate, "Tomcat". So tutto a proposito di te e dei tuoi "amici" giu' a NCR.}
{220}{}{Perche' lavori per NCR? Pensavo che tu fossi un uomo d'onore.}
{221}{}{Si'... sai, Bishop ha detto che lavori per NCR. E' vero?}
{222}{}{Si', volevo solo farti sapere che ho portato a termine il compito che mi avevi affidato.}
{223}{}{Mi fa piacere sentire che le mie parole hanno attecchito nel tuo cuore. Forse i nostri cammini si incroceranno ancora, un giorno.}
{224}{}{Forse. In alto i cuori, fratello.}
{225}{}{Arrivederci.}
{226}{}{NCR sta cercando di portare l'onore e un governo in tutta la California, e Vault City ha il potere per rendere possibile questo progetto! Pensa al bene che potremmo fare potendo contare sulla tecnologia di Vault City!}
{227}{}{Non me la dai a bere. Dovrei denunciarti a chi di dovere - a meno che, naturalmente, tu non voglia comprare il mio silenzio.}
{228}{}{Ma questa tecnologia appartiene a Vault City. Gli altri non hanno diritti su di essa.}
{229}{}{Niente di buono puo' venire dalle bugie e dal tradimento, Moore. Vault City ha mentito a se stessa per anni... non seguire il suo esempio, okay?}
{230}{}{Hmm. Dovro' pensarci su.}
{231}{}{Hai ragione. Scusa se ho dubitato di te.}
{232}{}{TUTTI gli uomini hanno il diritto di usufruire dei frutti del vecchio mondo. La tecnologia deve essere condivisa, non monopolizzata.}
{233}{}{Tu proprio non CAPISCI, vero, Moore? Forse un po' della buona vecchia "legge del piu' forte" ti inculchera' un po' di buon senso nella tua zucca vuota.}
{234}{}{Certo, certo... smettiamola con queste stronzate del "piu' santo di te". Dammi la grana, o ti denuncio.}
{235}{}{Dovro' pensarci su. Ci vediamo.}
{236}{}{Ti prego, consegna la valigetta a New Reno, amico. Ogni secondo e' prezioso!}
{237}{}{Cosa si puo' fare? Beh, diffondere il verbo dovrebbe essere sufficiente. Attraversa con attenzione e fermezza le lande, amico mio. Con il verbo come faro, non abbandonerai la giusta via.}
{238}{}{Grazie, fratello. Faro' come hai detto.}
{239}{}{Hai udito il verbo, oggi?}
{240}{}{Ascolta il verbo! Il verbo ti rendera' libero!}
{241}{}{La schiavitu' dannera' questa citta'!}
{242}{}{Dobbiamo aprire i cancelli di Vault City e accogliere il mondo esterno!}
{243}{}{Perche' non possiamo dividere la nostra ricchezza?! }
{244}{}{Non senti i lamenti di chi soffre all'esterno delle nostre mura?!}
