{100}{}{Vedi un prigioniero.}
{101}{}{Vedi uno straniero prigioniero.}
{102}{}{Beh, questa e' l'ultima volta che infrango il coprifuoco.}
{103}{}{Un'altra settimana e di nuovo al Centro di Collocamento...}
{104}{}{Meglio se sparisci, amico. Se ci vedono parlare, faranno passare a tutti e due un brutto quarto d'ora.}
{105}{}{Dannato Barkus, rinchiudermi qui dentro. Appena gli metto le mani addosso...}
{106}{}{Vorrei non essere mai venuto a Vault City. Citta' "libera"... che risate.}
{107}{}{Almeno il cibo non e' male.}
