{100}{}{Vedi un obice, modello SIAD-BG.}
{101}{}{Sebbene abbia un aspetto un po' cadente, pensi che possa ancora sparare. Se solo tu riuscissi a trovare un proiettile.}
{102}{}{Il meccanismo di fuoco si e' fuso. Adesso davanti a te c'e' soltanto un fermacarte da 2 tonnellate.}
{200}{}{L'obice e' gia' carico.}
{201}{}{Inserisci il proiettile nell'obice.}
{210}{}{Spari con l'obice alla porta, facendola saltare.}
{211}{}{L'obice non ha colpi in canna.}
{212}{}{Spari con l'obice.}
