{100}{}{Riesci ad aprire la serratura.}
{101}{}{Non riesci ad aprire la serratura.}
{102}{}{Chiudi a chiave l'oggetto.}
{103}{}{Non riesci a chiudere a chiave l'oggetto.}
{200}{}{ riesce ad aprire la serratura.}
{201}{}{ non riesce ad aprire la serratura.}
{202}{}{ chiude a chiave l'oggetto.}
{203}{}{ non riesce a chiudere a chiave l'oggetto.}
{300}{}{L'esplosione distrugge il lucchetto.}
{301}{}{L'esplosione non riesce a rompere il lucchetto.}
{400}{}{Riesci a forzare la serratura.}
{401}{}{Non riesci a forzare la serratura.}
{500}{}{ riesce a forzare la serratura.}
{501}{}{ non riesce a forzare la serratura.}
