{100}{}{Vedi una strana macchina. }
{101}{}{Vedi una slot machine. }
{102}{}{Vedi una scintillante slot machine. }
{103}{}{Vedi una luccicante slot machine. }
{130}{}{Ha tre occhi e un braccio.}
{140}{}{La puntata minima e' }
{141}{}{.}
{150}{}{Giureresti di averla beccata, con la coda dell'occhio, che ti stava guardando. }
{151}{}{La sua struttura lucente e la sua leva dorata scintillano sensualmente sotto le luci. }
{165}{}{E' fatta apposta per i giocatori accaniti. }
{180}{}{Il suo jackpot stratosferico sembra prepotentemente allettante. }
{200}{}{(La tua mano trema mentre cerchi le monete. La slot machine continua a sussurrarti.) *Vieni, zucchero...ecco...vieni adesso...non scherzare...*}
{201}{}{Vedi una slot machine. La sua struttura lucente e la sua leva dorata scintillano sensualmente sotto le luci. La sua fessura per le monete ti chiama a se', e senti il sangue fluire al volto per l'eccitazione.}
{202}{}{(La tua mano trema mentre cerchi le monete. La slot machine continua a sussurrarti.) *Vieni, dolcezza...ecco...impugna il manico...impugnalo saldamente...vieni adesso...*}
{250}{}{Inserisci }
{251}{}{. }
{252}{}{Gioca gli ultimi }
{253}{}{.}
{254}{}{Smetti di giocare.}
{255}{}{Sei al verde. Sei costretto a smettere di giocare.}
{256}{}{Smetti di giocare.}
{257}{}{Sei al verde. Sei costretto a smettere di giocare.}
{258}{}{Questo e' troppo! Me ne vado!}
{259}{}{Questo e' troppo! Me ne vado!}
{500}{}{Le finestrelle della slot machine iniziano a girare... }
{599}{}{... }
{600}{}{Niente. }
{601}{}{Una ciliegia. }
{602}{}{Due ciliegie. }
{603}{}{Tre }
{604}{}{JACKPOT! }
{605}{}{DOPPIO JACKPOT!!! }
{613}{}{. }
{700}{}{La vincita ammonta a }
{701}{}{.}
{1001}{}{ciliegia}
{1002}{}{arancia}
{1003}{}{prugna}
{1004}{}{campana}
{1005}{}{BAR}
{1006}{}{melone}
{1007}{}{sette}
{1101}{}{ciliegie}
{1102}{}{arance}
{1103}{}{prugne}
{1104}{}{campane}
{1105}{}{BAR}
{1106}{}{meloni}
{1107}{}{SETTE}
{2000}{}{*Vieni a giocare un po' con me, cowboy.*}
{2001}{}{*Ehila', marinaio.*}
{2002}{}{*Inserisci una moneta, tira la leva. Saro' carina con te.*}
{2003}{}{*Tick... Tick... Tiiiiick...*}
{2004}{}{*Ding*}
{2005}{}{*Bing*}
{2006}{}{*Kaaa-ching*}
{2007}{}{*Zzzzzzz*}
{2008}{}{*Ring-a-ling*}
{2009}{}{*Dingity-ding*}
{2010}{}{*Ehila', bellezza. Vieni a giocare con me.*}
{2011}{}{*Ehila', bellezza.*}
{2012}{}{*Sei proprio una cosettina carina. Perche' non vieni a giocare con me?*}
{2100}{}{Vedi una strana scatola di metallo dorato con tre occhi e un braccio. E' una delle cose piu' carine che tu abbia mai visto.}
{2101}{}{Me }
{2102}{}{ chi tu?}
{2103}{}{Me manca MAMMA. }
{2104}{}{ manca ARR-YO. Me vuole andare casa}
{2105}{}{(Le stringi la mano)}
{2106}{}{Tu essere strano mutante}
{2107}{}{Lode al Vault! Lode al Vault!}
{2108}{}{Essere tu Water-Chip?}
{2109}{}{(Allontanati, cerca altre cose luccicose)}
{2110}{}{Te ne vai.}
{2130}{}{La strana e carina scatola di metallo dorato con tre occhi e un braccio non risponde.}
{2131}{}{ME }
{2132}{}{! TU RISPONDERE ME!}
{2133}{}{(Le stringi la mano)}
{2134}{}{Me figlio di Abitante di Vault. Tu parlare me ORA.}
{2135}{}{Tu essere strano mutante}
{2136}{}{Essere tu Water-Chip?}
{2137}{}{(Allontanati, cerca altre cose luccicose)}
{2138}{}{(Te ne vai.)}
{2151}{}{Impugni il suo braccio e lo scuoti calorosamente. Appena la fai, si sente un *bzzzzzzz,* e la scatola parla! "Prego... inserire... monete."}
{2152}{}{Aighhhhh! Robot! Robot! Scappareeeeee}
{2153}{}{(Te ne vai.)}
{2175}{}{(Osservi la slot machine e ti rendi conto, maledicendo la tua poverta', che non hai abbastanza denaro per giocare. Sara' per la prossima volta...)}
{2176}{}{Te ne vai.}
{2185}{}{(La lucina "FUORI SERVIZIO" della slot machine si illumina ad intermittenza.)}
{2186}{}{Te ne vai.}
{2200}{}{(Puoi sentirla ridere di te.)}
{2201}{}{*Hehehe, perche' non ti arrendi, dolcezza?*}
{2202}{}{*Forse dovresti lasciare che sia qualcun altro a tirare la mia leva.*}
{2203}{}{(Una debole e folle risata proviene dalla macchina.)}
{2204}{}{(Senti la slot machine ridere di te.)}
{2205}{}{(La slot machine sogghigna.)}
{2206}{}{*Dai, perdente, non arrenderti*}
{2207}{}{*Ho avuto cio' che volevo da te, baby. Perche' non ti arrendi?*}
{2208}{}{*Spazzatura!*}
{2209}{}{*Sta' attenta che la porta del casino non ti sbatta contro il culo, mentre esci.*}
{2247}{}{*Aieeeeeeee! Cosih, dolcezzah! Oh dio, si'! Si'! SI', Ancora! Piu' veloce! Piu' forte! Che cosa stai aspettando?! Ancora!*}
{2248}{}{*Cosih, dolcezzah... continua a tirare la leva... piu' veloce, piu' forte, piu' veloce... dai...*}
{2249}{}{*Dai, dolcezza... succede a tutti, prima o poi... prova di nuovo... per favore...*}
{2250}{}{*Ti prego, non smettere proprio adesso, baby! Ho bisogno di te piu' che mai!*}
{2251}{}{*Dai, dolcezza... riprova... impugna il manico... stringilo con fermezza... dai...*}
{2252}{}{*Cosi' si fa... continua a tirare il manico... piu' veloce, piu' forte, piu' veloce... dai...*}
{2253}{}{*Ennnnghhhh! Cosi'! Chi e' il tuo paparino?! Chi e' il tuo paparino?!! Fallo ancora! Strattonalo piu' forte, questa volta! Piu' forte!*}
{2280}{}{(Vedi una slot machine. La sua struttura lucente e la sua leva dorata scintillano sensualmente sotto le luci di New Reno. La sua fessura per le monete ti chiama a se', e senti il sangue fluire al volto per l'eccitazione. Come la osservi, una delle sue tre finestrelle ti fa l'occhiolino. Dalla fessura per le monete senti provenire una voce gutturale.) *Beh, perbacco! Ehilaaaaaaa', zucchero. Hai voglia di far divertire una ragazza?*}
{2281}{}{(Vedi una slot machine. La sua struttura solida e ruvida e la sua leva dorata scintillano come un dio solare sotto le luci di New Reno. La sua fessura per le monete ti chiama a se', e senti il sangue fluire al volto per l'eccitazione. Come la osservi, improvvisamente una profonda voce maschile ti sussurra dalla fessura delle monete.) *Non vedo una ragazza bella come te da tempo... Vuoi tentare la fortuna?*}
{2282}{}{::Ti dai un pizzicotto::}
{2283}{}{Uh... hello?}
{2284}{}{::Respiri profondamente, te ne vai.::}
{2300}{}{*Sono ancora qui, carina.* (La slot machine abbassa la voce.) *Dai, vieni...vuoi giocare?*}
{2301}{}{*Sono ancora qui, zuccheroh.* (La slot machine abbassa la voce.) *Sei un gran pezzo d'uomo, lo sai? Vieni, dai... non vuoi mettere qualche monetina dentro di me?*}
{2302}{}{Chiiii *sei* tuuuuu?}
{2303}{}{Sherto che vojo sgiocarre con teee}
{2304}{}{Penso che sia meglio andarsene prima di fare qualcosa di cui potrei pentirmi. (Vai via.)}
{2305}{}{::Respiri profondamente, te ne vai.:: (Vai via.)}
{2320}{}{*Sono il tuo uomo ideale.* (La slot machine ti fa l'occhiolino.) *Dammi un po' di monete, e ti faro' provare piacere in modi che nessun uomo ha MAI usato prima.*}
{2321}{}{*Sono la tua donna ideale, zucchero. Tutto cio' che voglio e' un po' di attenzione. Puoi aiutarmi? Dai, solo una moneta o due?*}
{2322}{}{Nooon posssciamo sholo ppa..rlaree?}
{2340}{}{*Certo che possiamo, dolcezza, certo che possiamo.* (La slot machine sembra comprensiva.) *Cosa turba la tua piccola dolce testolina?*}
{2341}{}{*Certo che possiamo, zucchero, certo che possiamo.* (La slot machine sembra comprensiva.) *Che cosa ti turba, splendore?*}
{2342}{}{Me manca MAMMA e manca ARROYO e me......no trova GECK e...*sniff*}
{2343}{}{Me manca MAMMA e Arroyo stato ATTACCATO e me...no sa dove essere loro...e...*sniff*}
{2344}{}{Me deve riparare grande barca...e me no sa COME...e la muh-muh-mia Mamma ANDATA e ...*sniff*}
{2345}{}{Ho fiiinito il sgioco... e ora shto sholo vagabondando e... ho paura shia tutto ffinito e... *sniff*}
{2346}{}{E' che Fhallowt dueee non s'porta la mia sshcheda 3DFxxxxx e ho shpeso coshi' tanti *shooldi* per comprarla e *sniff*}
{2347}{}{Ho provato a creare un bbuon pe...personaggio ma... penso di aver shbajato *completamente* la dishtribusshione dei punti... e ora ho un pershonaggio di meeerda... e......*sniff*}
{2348}{}{Shto parlaando cooon una shlot mmaaashin, devo essher messoooh maleh.}
{2370}{}{*Su, su... non pensarci piu'... lascia fare tutto a me. Dai, appoggia la tua testa su di me. Ecco. Sfogati pure.*}
{2371}{}{*Su, su... non pensarci piu', zucchero... lascia fare tutto a me. Dai, appoggia la tua splendida testa su di me. Ecco. Sfogati pure.*}
{2372}{}{Grascie, shlot mashiiin *sniff* sei la migliore}
{2373}{}{Tu shei la shooola persona *buona* che ho incontrato finora... tu-tutti gli altri sono cosi' cattivi e hanno tentato di farmi *male* e di prendere i miei shooldi e...*sniff*}
{2380}{}{*Sei sicura di stare bene, dolcezza? Non mi sento tranquillo a lasciarti andare via da sola vedendoti in questo stato.*}
{2381}{}{(Appoggi la tua testa stanca sulla macchina.)}
{2382}{}{*Sei sicuro di stare bene, zucchero? Non mi sento tranquilla a lasciarti andare via da solo vedendoti in questo stato.*}
{2383}{}{Sto bbene...graascie per avver parlato cooon mee, shlot masciin ti amooooo}
{2400}{}{*Sei la sola eroina che abbiamo in questo piccolo mondo di bastardi e ladri! Adesso devi cercare di farti forza, hai capito, dolcezza?* (Si volta.) *Faresti meglio ad andartene prima che io cominci a comportarmi in maniera poco virile.*}
{2401}{}{(Una lacrima sembra formarsi in una delle finestrelle.) }
{2402}{}{*Sei il solo eroe che abbiamo in questo piccolo mondo di bastardi e ladri! Tu...tu...devi cercare di farti forza, hai capito, zucchero?* (Si volta.) *Faresti bene ad andartene prima che io cominci a piangere.*}
{2403}{}{Ciaooooo}
{3000}{}{E dai, }
{3001}{}{! A mio figlio serve un paio di scarpe nuove!}
{3002}{}{! A mio papa' serve un nuovo fucile al plasma!}
{4000}{}{Sembra ci sia qualcuno che sta bloccando la slot machine.}
{5000}{}{Incanti la macchina per farti dare tutte le sue monete.}
{5001}{}{La macchina sembra bloccata ma poi senti un rombo lontano tipo quello di una valanga di monete che iniziano ad uscire dal distributore automatico.}
{5002}{}{[Raccogli le monete e te ne vai.]}
