#############################################################
#  Cacería de esclavos (The Den)     		            #
#############################################################

# looks
# primitive
{100}{}{Ves a un hombre grande de aspecto primitivo.}
{101}{}{Ves a una esbelta mujer de aspecto primitivo.}

# nomads
{200}{}{Ves a un hombre de aspecto extraño.}
{201}{}{Ves a un hombre de aspecto harapiento.}
{202}{}{Ves a un hombre con la ropa hecha jirones.}

{210}{}{Ves a una mujer muy sucia.}
{211}{}{Ves a una mujer bastante sucia.}
{212}{}{Ves a una mujer esquelética.}

# 10. BF: Fleeing Primitive
{270}{}{Ellos no encontrar mi.}
{271}{}{Huir, huir.}
{272}{}{¿Por qué ellos hacer daño?}
{273}{}{Yo miedo.}
{274}{}{Yo no luchar}
{275}{}{Yo querer vivir.}
{276}{}{No herir familia.}

# 11. BF: Fleeing Nomad
{280}{}{Oh, ¡mierda!}
{281}{}{¿Por qué están haciendo esto?}
{282}{}{¿Y mi familia?}
{283}{}{No quiero morir.}
{284}{}{No quiero ser un esclavo.}
{285}{}{No me merezco esto.}

# 14. Fleeing Primitive
{300}{}{¡Ahhh!}
{301}{}{¡No matar! ¡No matar!}
{302}{}{¡Para!}
{303}{}{¡Ayudaaaa!}
{304}{}{¡Corred!}
{305}{}{¡Déjame en paz!}
{306}{}{¡No me hagas daño!}
{307}{}{¡Tu no daño a mí!}
{308}{}{¡No quiero luchar!}

# 15. Fleeing Nomad
{350}{}{¡Sálvese quien pueda!}
{351}{}{¡No dejéis que os atrapen!}
{352}{}{¡Esclavistas! ¡Huid!}
{353}{}{¡Que alguien me ayude! ¡Por favor!}
{354}{}{¡Huye, Marty!}
{355}{}{¡Ahhh!}
{356}{}{¡Detén esta locura!}
{357}{}{¡No te hemos hecho nada! ¡Déjanos en paz!}
{358}{}{¡Reconozco ese tatuaje!}
{359}{}{¡No, por favor!}
{360}{}{¡Por favor, no me mates!}
{361}{}{No quiero pelear; ¡no me mates!}
{362}{}{Por favor, ¡no quiero morir!}
{363}{}{Vosotros sois esclavistas, ¿no? Oh, Dios.}
