#############################################################
#  Message File: Door.msg                                   #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#       April 19,1998 nbk: added message line to be used    #
#                          for doors opened with keys.      #
#                                                           #
#  Created: September 26, 1997                              #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc
{100}{}{Ves una puerta de madera.}
{101}{}{Ves una puerta de metal.}

# description_proc

# Perception Check Critical Success
{102}{}{Ves una robusta puerta con una cerradura, que puede ser abierta con una ganzúa, y una trampa explosiva en el marco, que podrías ser capaz de forzar.}
{103}{}{Ves una robusta puerta con una cerradura y una trampa explosiva en el marco, que podrías ser capaz de forzar.}
{104}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente y una trampa explosiva en el marco, que podrías ser capaz de forzar.}
{105}{}{Ves una robusta puerta con una vieja y oxidada cerradura y una trampa explosiva en el marco, que podrías ser capaz de forzar.}

{106}{}{Ves una robusta puerta con una cerradura (que puede ser abierta con una ganzúa) y una trampa en el marco, que podrías ser capaz de forzar.}
{107}{}{Ves una robusta puerta con una cerradura y una trampa en el marco, que podrías ser capaz de forzar.}
{108}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente y una trampa en el marco, que podrías ser capaz de forzar.}
{109}{}{Ves una robusta puerta con una vieja y oxidada cerradura y una trampa en el marco, que podrías ser capaz de forzar.}

{110}{}{Ves una robusta puerta con una cerradura, que puede ser abierta con una ganzúa, y un cable cortado en el marco, que podrías ser capaz de forzar.}
{111}{}{Ves una robusta puerta con una cerradura y un cable arrancado en el marco, que podrías ser capaz de forzar.}
{112}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente y un cable arrancado en el marco, que podrías ser capaz de forzar.}
{113}{}{Ves una robusta puerta con una vieja y oxidada cerradura y un cable cortado en el marco, que podrías ser capaz de forzar.}

{114}{}{Ves una robusta puerta con una cerradura (que puede ser abierta con una ganzúa), que podrías ser capaz de forzar.}
{115}{}{Ves una robusta puerta con una cerradura, que podrías ser capaz de forzar.}
{116}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente, que podrías ser capaz de forzar.}
{117}{}{Ves una robusta puerta con una vieja y oxidada cerradura, que podrías ser capaz de forzar.}

# Perception Check Success

{118}{}{Ves una robusta puerta con una cerradura, que puede ser abierta con una ganzúa, y una trampa explosiva en el marco.}
{119}{}{Ves una robusta puerta con una cerradura  y una trampa explosiva en el marco.}
{120}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente y una trampa explosiva en el marco.}
{121}{}{Ves una robusta puerta con una vieja y oxidada cerradura y una trampa explosiva en el marco.}

{122}{}{Ves una robusta puerta con una cerradura, que puede ser abierta con una ganzúa, y una trampa en el marco.}
{123}{}{Ves una robusta puerta con una cerradura y una trampa en el marco.}
{124}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente y una trampa en el marco.}
{125}{}{Ves una robusta puerta con una vieja y oxidada cerradura y una trampa en el marco.}

{126}{}{Ves una robusta puerta con una cerradura, que puede ser abierta con una ganzúa, y un cable cortado en el marco.}
{127}{}{Ves una robusta puerta con una cerradura y un cable arrancado en el marco.}
{128}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente y un cable arrancado en el marco.}
{129}{}{Ves una robusta puerta con una vieja y oxidada cerradura y un cable cortado en el marco.}

{130}{}{Ves una robusta puerta con una cerradura, que puede ser abierta con una ganzúa.}
{131}{}{Ves una robusta puerta con una cerradura.}
{132}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente.}
{133}{}{Ves una robusta puerta con una vieja y oxidada cerradura.}

# Perception Check Critical Failure

{134}{}{Ves una puerta dañada con una cerradura, que puede ser abierta con una ganzúa, y una trampa explosiva en el marco.}
{135}{}{Ves una puerta dañada con una cerradura y una trampa explosiva en el marco.}
{136}{}{Ves una puerta dañada sin ningún mecanismo de apertura aparente y una trampa explosiva en el marco.}
{137}{}{Ves una puerta dañada con una vieja y oxidada cerradura y una trampa explosiva en el marco.}

{138}{}{Ves una puerta dañada con una cerradura, que puede ser abierta con una ganzúa, y una trampa en el marco.}
{139}{}{Ves una puerta dañada con una cerradura y una trampa en el marco.}
{140}{}{Ves una puerta dañada sin ningún mecanismo de apertura aparente y una trampa en el marco.}
{141}{}{Ves una puerta dañada con una vieja y oxidada cerradura y una trampa en el marco.}

{142}{}{Ves una puerta dañada con una cerradura, que puede ser abierta con una ganzúa, y un cable cortado en el marco.}
{143}{}{Ves una puerta dañada con una cerradura y un cable arrancado en el marco.}
{144}{}{Ves una puerta dañada sin ningún mecanismo de apertura aparente y un cable arrancado en el marco.}
{145}{}{Ves una puerta dañada con una vieja y oxidada cerradura y un cable cortado en el marco.}

{146}{}{Ves una puerta dañada con una cerradura, que puede ser abierta con una ganzúa.}
{147}{}{Ves una puerta dañada con una cerradura .}
{148}{}{Ves una puerta dañada sin ningún mecanismo de apertura aparente.}
{149}{}{Ves una puerta dañada con una vieja y oxidada cerradura.}

# Perception Check Failure

{150}{}{Ves una vieja puerta con una cerradura, que puede ser abierta con una ganzúa, y una trampa explosiva en el marco.}
{151}{}{Ves una vieja puerta con una cerradura y una trampa explosiva en el marco.}
{152}{}{Ves una vieja puerta sin ningún mecanismo de apertura aparente y una trampa explosiva en el marco.}
{153}{}{Ves una vieja puerta con una vieja y oxidada cerradura y una trampa explosiva en el marco.}

{154}{}{Ves una vieja puerta con una cerradura, que puede ser abierta con una ganzúa, y una trampa en el marco.}
{155}{}{Ves una vieja puerta con una cerradura y una trampa en el marco.}
{156}{}{Ves una vieja puerta sin ningún mecanismo de apertura aparente y una trampa en el marco.}
{157}{}{Ves una vieja puerta con una vieja y oxidada cerradura y una trampa en el marco.}

{158}{}{Ves una vieja puerta con una cerradura, que puede ser abierta con una ganzúa, y un cable cortado en el marco.}
{159}{}{Ves una vieja puerta con una cerradura y un cable arrancado en el marco.}
{160}{}{Ves una vieja puerta sin ningún mecanismo de apertura aparente y un cable arrancado en el marco.}
{161}{}{Ves una vieja puerta con una vieja y oxidada cerradura y un cable cortado en el marco.}

{162}{}{Ves una vieja puerta con una cerradura, que puede ser abierta con una ganzúa.}
{163}{}{Ves una vieja puerta con una cerradura.}
{164}{}{Ves una vieja puerta sin ningún mecanismo de apertura aparente.}
{165}{}{Ves una vieja puerta con una vieja y oxidada cerradura.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Activas la trampa y te hieres, perdiendo }
{167}{}{ puntos de salud.}

# NPC sets off the trap
{168}{}{ activa la trampa y se hiere, perdiendo }
{169}{}{ puntos de salud.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Abres la cerradura de la puerta con habilidad.}
{171}{}{Tu falta de habilidad ha atascado la cerradura la puerta.}
{172}{}{No logras abrir la cerradura de la puerta.}

# Lock Door
{189}{}{Abres la puerta con habilidad.}
{190}{}{No logras abrir la puerta.}

# Find Trap on the Door
{194}{}{Encuentras una trampa en la puerta.}
{195}{}{No logras encontrar ninguna trampa en la puerta.}

# Disarm the Trap on the Door
{196}{}{Desarmas la trampa con habilidad.}
{198}{}{No logras desarmar la trampa.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{ abre la cerradura de la puerta con habilidad.}
{174}{}{, con su falta de habilidad, ha atascado la cerradura de la puerta.}
{175}{}{ no logra abrir la cerradura de la puerta.}

# Lock Door
{191}{}{ abre la puerta con habilidad.}
{192}{}{ no logra abrir la puerta.}

# Find Trap on the Door
{199}{}{ encuentra una trampa en la puerta.}
{200}{}{ no logra encontrar ninguna trampa en la puerta.}

# Disarm the Trap on the Door
{201}{}{ desarma la trampa con habilidad.}
{202}{}{ no logra desarmar la trampa.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Rompes la cerradura de la puerta.}
{177}{}{Te lesionas la espalda mientras tratas de romper la cerradura y recibes un punto de daño.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Te lesionas la espalda mientras tratas de de romper la cerradura y recibes }
{179}{}{ puntos de daño.}
{180}{}{Estás demasiado débil para forzar la puerta.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ rompe la cerradura de la puerta.}
{182}{}{ se lesiona la espalda mientras trata de romper la cerradura y recibe un punto de daño.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ se lesiona la espalda mientras trata de romper la cerradura y recibe }
{184}{}{ puntos de daño.}

{185}{}{ está demasiado débil para forzar la cerradura.}
{186}{}{ se lesiona la espalda mientras trata de romper la cerradura y recibe un punto de daño.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ se lesiona la espalda mientras trata de romper la cerradura y recibe }
{188}{}{ puntos de daño.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Los explosivos no le han hecho ni un rasguño a la puerta.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{La puerta parece estar cerrada.}
{204}{}{Descubres una trampa en la puerta.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jam.

{205}{}{ descubre una trampa en la puerta.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Eres incapaz de poner una trampa en la puerta, porque ya está abierta.}

# NPC tries to set a trap on an open door
{207}{}{ es incapaz de poner una trampa en la puerta, porque ya está abierta.}

# Player tries to set a trap on a closed door
{208}{}{Colocas habilmente una trampa en la puerta.}
{209}{}{No consigues colocar correctamente la trampa en la puerta.}

# NPC tries to set a trap on a closed door
{210}{}{ coloca habilmente una trampa en la puerta.}
{211}{}{ no consigues colocar correctamente la trampa en la puerta.}

{300}{}{Abres la puerta.}
{301}{}{Cierras la puerta.}
{302}{}{Eres incapaz de echar el cerrojo en la puerta porque ya está abierta.}
{303}{}{Esa llave no encaja en la cerradura.}

# for broken doors
{320}{}{No hay forma de cerrar la puerta.}
{330}{}{La puerta está atascada.}

# Using a key on the door. (YES THIS IS A DUPLICATE BUT PLEASE DO NOT REMOVE..
# IT MOST LIKELY IS BEING USED BY A DOOR SCRIPT SOMEWHERE)
{400}{}{Abres la puerta.}

{414}{}{Ves una robusta puerta con una cerradura (que puede ser abierta con una ganzúa), que podrías ser capaz de forzar.}
{415}{}{Ves una robusta puerta con una cerradura, que podrías ser capaz de forzar.}
{416}{}{Ves una robusta puerta sin ningún mecanismo de apertura aparente, que podrías ser capaz de forzar.}
{417}{}{Ves una robusta puerta que podrías ser capaz de forzar.}

{500}{}{Esta puerta es demasiado pesada para forzarla.}
{501}{}{Parece que antes necesitarás hacer funcionar el generador.}
{502}{}{Ves: Puerta de ascensor.}
{503}{}{Parece que necesitas un aparato eléctrico para abrir esta cerradura.}