# quick look
{100}{}{Ves a un fan del boxeo, furibundo. }

# examine
{150}{}{Ves a un hombre de apariencia salvaje. Está gritando a voz en cuello de forma incomprensible.}
{151}{}{Ves a un fan del boxeo, furibundo. Está pidiendo sangre a gritos.}
{152}{}{Ves a una mujer de apariencia salvaje. Está gritando a voz en cuello de forma incomprensible.}
{153}{}{Ves a una fan del boxeo, furiosa. Está pidiendo sangre a gritos.}

# 1. FLOAT DIALOGUES [FAN=MALE, PC NOT A PRIZEFIGHTER]
{200}{}{¡Síiiiiiiiiiiiiii!}
{201}{}{::grito:: ::rugido:: ::grito::}
{202}{}{¡Mátale, }
{1202}{}{!}
{203}{}{¡Eres el mejor, }
{1203}{}{!}
{204}{}{¡Acaba con él, }
{1204}{}{!}
{205}{}{¡Sí! ¡Dale lo suyo!}
{206}{}{}
{1206}{}{ es el MEJOR. EL MEJOR.}
{207}{}{}
{1207}{}{!!!}
{208}{}{}
{1208}{}{, eres el elegido!}
{209}{}{}
{1209}{}{ es el mejor campeón de boxeo que haya visto.}
{210}{}{}
{1210}{}{ también es muy inteligente. Sabe cómo hacer daño a alguien.}
{211}{}{}
{1211}{}{ cuida a sus fans. No pasa de ellos como los demás boxeadores.}
{212}{}{}
{1212}{}{ es taaaan guapo.}
{213}{}{}
{1213}{}{ es taaaan varonil.}
{214}{}{Amo a }
{1214}{}{ ¡Aiiiieeeeeeeee!}
{215}{}{::alarido:: ::alarido::}
{216}{}{}
{1216}{}{ está cuidado y nutrido. Eso es lo que me dijo ayer por la noche.}

# 2. FLOAT DIALOGUES [FAN=MALE, PC = FEMALE OR MALE PRIZEFIGHTER]
{250}{}{}
{1250}{}{, eres el elegido!}
{251}{}{}
{1251}{}{ también es muy inteligente. Sabe cómo hacer daño a alguien.}
{252}{}{}
{1252}{}{ cuida a sus fans. No pasa de ellos como los demás boxeadores.}
{253}{}{He oído que }
{1253}{}{ era un desconocido, recién llegado del Yermo, antes de venir a boxear a Nuevo Reno.
 ¡Misterioso! ¡Mortal!}
{254}{}{¡Oh, Dios mío! }
{1254}{}{! ¡Fírmame un autógrafo!}
{255}{}{¡Pégame! ¡Pégame! ¡Quiero contarle a mis hijos que tú me golpeaste!}
{256}{}{¡Eres el mejor, }
{1256}{}{! ¡Mándalo al infierno!}
{257}{}{¡Mátalo, }
{1257}{}{!}
{258}{}{¡Eres el mejor, }
{1258}{}{!}
{259}{}{¡Acaba con él, }
{1259}{}{!}
{260}{}{¡Sí! ¡Dale lo suyo!}
{261}{}{}
{1261}{}{, eres el MEJOR. EL MEJOR.}
{262}{}{}
{1262}{}{!!!}
{263}{}{¡Síiiiiiiiiiiii!}
{264}{}{::grito:: ::rugido:: ::grito::}
{265}{}{}
{1265}{}{ es la mejor campeona de boxeo que haya visto.}
{266}{}{}
{1266}{}{, eres la mujer más dura del mundo!}
{267}{}{¡Eres más dura que Robin Givens!}
{268}{}{}
{1268}{}{, eres la elegida!}
{269}{}{}
{1269}{}{ también es muy inteligente. Sabe cómo hacer daño a alguien.}
{270}{}{}
{1270}{}{ cuida a sus fans. No pasa de ellos como los demás boxeadores.}
{271}{}{He oído que }
{1271}{}{ era una desconocida, recién llegada del Yermo, antes de venir a boxear a Nuevo Reno. ¡Es tan misteriosa!}

# 3. FLOAT DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{280}{}{¿Un beso de la suerte?}
{281}{}{}
{1281}{}{, eres el elegido!}
{282}{}{}
{1282}{}{ es taaaaan guapo.}
{283}{}{}
{1283}{}{ tiene la constitución de un tanque!}
{284}{}{}
{1284}{}{ también es muy inteligente. Sabe cómo hacer daño a alguien.}
{285}{}{}
{1285}{}{ cuida a sus fans. No pasa de ellos como los demás boxeadores.}
{286}{}{He oído que }
{1286}{}{ era un desconocido, recién llegado del Yermo, antes de venir a boxear a Nuevo Reno. ¡Misterioso! ¡Mortal!}
{287}{}{¡Oh, Dios mío! }
{1287}{}{! ¡Fírmame un autógrafo!}
{288}{}{¡Pégame! ¡Pégame! ¡Quiero contarle a mis hijos que tú me golpeaste!}
{289}{}{¡Eres el mejor, }
{1289}{}{! ¡Mándale al infierno!}
{290}{}{¡Mátale, }
{1290}{}{!}
{291}{}{¡Eres el mejor, }
{1291}{}{!}
{292}{}{¡Acaba con él, }
{1292}{}{!}
{293}{}{¡Sí! ¡Dale lo suyo!}
{294}{}{}
{1294}{}{, eres el MEJOR. EL MEJOR.}
{295}{}{}
{1295}{}{!!!}
{296}{}{¡Aiiiieeeeeeeee!}
{297}{}{::alarido:: ::alarido::}
{298}{}{}
{1298}{}{ es la mejor campeona de boxeo que haya visto.}
{299}{}{}
{1299}{}{, eres la mujer más dura del mundo!}
{300}{}{¡Eres más dura que Robin Givens!}
{301}{}{}
{1301}{}{, eres la elegida!}
{302}{}{}
{1302}{}{ también es muy inteligente. Sabe cómo hacer daño a alguien.}
{303}{}{}
{1303}{}{ cuida a sus fans. No pasa de ellos como los demás boxeadores.}
{304}{}{He oído que }
{1304}{}{ era una desconocida, recién llegada del Yermo, antes de venir a boxear a Nuevo Reno. ¡Es tan misteriosa!}

# 4. CLICK DIALOGUES [FAN=FEMALE OR MALE, PC NOT A PRIZEFIGHTER]
{320}{}{ matará a cualquiera que se interponga en su camino!}
{321}{}{ es el MEJOR. EL MEJOR.}
{322}{}{!!!}
{323}{}{ es el elegido!}
{324}{}{ es el mejor campeón de boxeo que haya visto.}
{325}{}{ también es muy inteligente. Sabe cómo hacer daño a alguien.}
{326}{}{ cuida a sus fans. No pasa de ellos como los demás boxeadores.}
{327}{}{ es taaaaaan guapo.}
{328}{}{ está cuidado y nutrido. Eso es lo que me dijo ayer por la noche.}

# 5. CLICK DIALOGUES [FAN=MALE, PC = PRIZEFIGHTER]
{350}{}{}
{1350}{}{, eres el elegido!}
{351}{}{Guardo un poco de tu sudor en una jarra, en mi casa.}
{352}{}{¡Oh, Dios mío! }
{1352}{}{! ¡Fírmame un autógrafo!}
{353}{}{¡Pégame! ¡Pégame! ¡Quiero contarle a mis hijos que tú me golpeaste!}
{354}{}{Eres el mejor, }
{1354}{}{! ¡Mándale al infierno!}
{355}{}{¡Eres el mejor, }
{1355}{}{!}
{356}{}{¡Dale lo suyo, }
{1356}{}{!}
{357}{}{}
{1357}{}{, eres el MEJOR. EL MEJOR.}
{358}{}{}
{1358}{}{!!!}
{359}{}{¡Síiiiiiiiiii!}
{360}{}{}
{1360}{}{, eres el mejor campeón de boxeo que haya visto.}
{361}{}{}
{1361}{}{, realmente sabes cómo hacer daño a alguien.}
{362}{}{}
{1362}{}{, realmente cuidas de tus fans. No pasas de ellos, como los demás boxeadores.}
{363}{}{He oído que eres un desconocido, procedente del Yermo, antes de que vinieras a boxear a Nuevo Reno. ¿De dónde eres?}
{364}{}{}
{1364}{}{, eres la mujer más dura del mundo!}
{365}{}{¡Eres más dura que Robin Givens!}
{366}{}{}
{1366}{}{, eres la elegida!}

# 6. CLICK DIALOGUES [FAN=FEMALE, PC = PRIZEFIGHTER]
{380}{}{¿Un beso de la suerte?}
{381}{}{}
{1381}{}{, eres el elegido!}
{382}{}{}
{1382}{}{, eres taaaaan guapo.}
{383}{}{::Parece debilitarse cuando hablas con ella::}
{384}{}{Guardo un poco de tu sudor en una jarra, en mi casa.}
{385}{}{¡Oh, Dios mío! }
{1385}{}{! ¡Fírmame un autógrafo!}
{386}{}{¡Pégame! ¡Pégame! ¡Quiero contarle a mis hijos que tú me golpeaste!}
{387}{}{Eres el mejor, }
{1387}{}{! ¡Mándale al infierno!}
{388}{}{¡Mátale, !}
{1388}{}{!}
{389}{}{¡Eres el mejor, }
{1389}{}{!}
{390}{}{¡Dale lo suyo, }
{1390}{}{!}
{391}{}{.}
{1391}{}{, eres el MEJOR. EL MEJOR.}
{392}{}{}
{1392}{}{!!!}
{393}{}{¡Aiiiieeeeeeeee!}
{394}{}{}
{1394}{}{, eres el mejor campeón de boxeo que haya visto.}
{395}{}{}
{1395}{}{, realmente sabes cómo herir a alguien.}
{396}{}{}
{1396}{}{, realmente cuidas de tus fans. No pasas de ellos, como los demás boxeadores.}
{397}{}{He oído que eres un desconocido, procedente del Yermo, antes de que vinieras a boxear a Nuevo Reno. ¿De dónde vienes?}
{398}{}{}
{1398}{}{, eres la mujer más dura del mundo!}
{399}{}{¡Eres más dura que Robin Givens!}
{400}{}{}
{1400}{}{, eres la elegida!}