# 0. QUICK LOOK, BOXES (WTG)
{100}{}{Ves varias cajas llenas de productos químicos.}

# 0. LOOK, BOXES (WTG)
{150}{}{Ves varias cajas llenas de productos químicos. No puedes identificarlos, pero han sido
 empaquetados *muy* cuidadosamente.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{175}{}{Ves un vertibird.}

# 1. QUICK LOOK, VERTIBIRD (WTG)
{199}{}{Ves un vertibird... una forma avanzada de helicóptero. Por desgracia, no tienes ni idea de
 cómo manejarlo. }

# 2. NORMAL ACTION SEQUENCE (WTG)
{200}{}{(Esos tipos me acojonan...)}
{000}{}{(Cierra el pico. Aquí vienen).}
{000}{}{*Zztttt* ¿Tenéis el cargamento que solicitamos? *Zzzttt**}
{000}{}{Sí, todos los productos químicos están aquí. Podéis comprobarlo si queréis.}
{000}{}{*Zztttt* Eso no será necesario. *Zzzttt**}
{000}{}{*Zztttt* Sabéis lo que ocurrirá si los productos no cumplen las especificaciones solicitadas.
 *Zzzttt**}
{000}{}{Claro, desde luego. Eh, ¿y habéis traído las iluminadoras...?}
{000}{}{*Zztttt* Las armas láser están en nuestra bahía de carga. *Zzzttt**}
{000}{}{*Zztttt* Para asegurar vuestra cooperación, transmitiremos la secuencia de armado cuando los
 productos químicos estén cargados. *Zzzttt**}
{000}{}{Eh... bien... de acuerdo entonces. Cargando, muchachos --}
{000}{}{*Zztttt* No. *Zzzttt**}
{000}{}{*Zztttt* Nosotros los cargaremos. *Zzzttt**}
{000}{}{Eh, vale... vale. Por supuesto. Dejadles espacio, muchachos.}
{000}{}{De acuerdo; estamos bien aquí. El resto de guardias... tú también, novato... volved a Reno.
 Nos reuniremos con vosotros.}

# 3. FLOAT SEQUENCE: INTRUDER (WTG)
{250}{}{¡Mira! ¡Alguien nos está vigilando!}
{000}{}{¡Matadlos!}
{000}{}{¡Parece que tenemos un espía...!}
{000}{}{*Zztttt* Misión abortada. Secuencia de carga comprometida. *Zzzttt**}
{000}{}{*Zztttt* Acabad con los enemigos, y después regresad a la base. *Zzzttt**}

# 4. FLOAT SEQUENCE: OUT OF POSITION WARNING (WTG)
{300}{}{No te acerques a esos tipos blindados. Te harán pedazos.}
{000}{}{Vuelve a la posición.}
{000}{}{Deja de moverte nerviosamente... a esos tipos blindados no les va a gustar.}

# 5. FLOAT SEQUENCE: OUT OF POSITION, FINAL (WTG)
{350}{}{¡Maldición! ¡¿Qué estás haciendo, tonto del culo?!}
{000}{}{¡Regresa a tu posición! ¿Qué demonios estás hac--?!}
{000}{}{*Zztttt* Misión abortada. Secuencia de carga comprometida. *Zzzttt**}
{000}{}{*Zztttt* Acabad con los enemigos, y después regresad a la base. *Zzzttt**}

# 6. VERTIBIRD SEQUENCE: (WTG)
{400}{}{[Parece que hay una puerta. ¿La abres y subes?]}
{000}{}{Sí.}
{000}{}{Te alejas.}
{000}{}{Abordas el vertibird.}
{000}{}{Lo dejas.}

# 7. VERTIBIRD: TAKE OFF (7)
{450}{}{[¡La puerta se cierra tras de ti, y el vertibird despega! ¡No puedes abrir la puerta!]}
{000}{}{Oh, oh}
{000}{}{Oh, mierda...}

# 8. DISPLAY TEXT: BOXES (WTG)
{500}{}{Estas cajas están llenas de latas de un metal fuerte. A juzgar por el cuidadoso empaquetado,
 sospechas que contienen alguna clase de productos químicos peligrosos. }