# 0. QUICK LOOK (WTG)
{100}{}{Ves al vigilante de sala del casino.}

# 0. LOOK (WTG)
{150}{}{Ves a un hombre bien vestido. Está supervisando el casino.}
{000}{}{Ves al vigilante de sala. Está supervisando el casino.}
{000}{}{Está supervisando el casino.}

# 1. FLOAT DIALOGUE: POWER ARMOR (WTG)
{200}{}{Eh… debes quitarte esa armadura.}
{000}{}{Eh, señor… o señora… deberá quitarse esa armadura.}
{000}{}{Señor… señora… no puede llevar eso en el casino.}

# 2. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{210}{}{Eh, ¿por qué está andando a hurtadillas, señor?}
{000}{}{Eh, ¿va de incógnito, señor?}

# 3. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, SNEAK (WTG)
{220}{}{Eh, ¿por qué está andando a hurtadillas, señora?}
{000}{}{Eh, ¿va de incógnito, señora?}

# 4. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{230}{}{Buenas tardes, [MM], señor.}
{000}{}{Buenas noches, [MM], señor.}

# 5. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO, NIGHT (WTG)
{240}{}{Buenas tardes, [MM], señora.}
{000}{}{Buenas noches, [MM], señora.}

# 6. FLOAT DIALOGUE: MALE, MADE MAN, SAME CASINO (WTG)
{250}{}{Buenos días, [MM], señor.}

# 7. FLOAT DIALOGUE: FEMALE, MADE MAN, SAME CASINO (WTG)
{260}{}{Buenos días, [MM], señora.}

# 8. FLOAT DIALOGUE: MALE, MADE MAN, NOT SAME CASINO (WTG)
{270}{}{Amigo, estás entrando en el casino equivocado.}
{000}{}{Será mejor que te vayas. Ahora.}
{000}{}{Este no es lugar para jugar con la vida de uno. Será mejor que te marches.}
{000}{}{Zorra, estás entrando en el casino equivocado.}

# 10. FLOAT DIALOGUE: MALE, PRIZEFIGHTER/PORN STAR (ARMED) (WTG)
{280}{}{Señor, lo siento, tendrá que guardar ese arma.}

# 11. FLOAT DIALOGUE: FEMALE, PRIZEFIGHTER (ARMED) (WTG)
{290}{}{Señora, lo siento, tendrá que guardar ese arma.}

# 12. FLOAT DIALOGUE: PORN STAR, FEMALE (ARMED) (WTG)
{300}{}{Cariño, lo siento, pero no puedes llevar armas en el casino. [Sonríe]. Ya eres lo bastante letal así.}

# 13. FLOAT DIALOGUE: PORN STAR, FEMALE (SNEAK) (WTG)
{310}{}{Cariño, con un cuerpo como ese, no podrás andar a hurtadillas por ninguna parte.}

# 14. FLOAT DIALOGUE: MALE, NO REP (ARMED) (WTG)
{320}{}{Tribal, será mejor que guardes ese arma *ahora mismo*.}

# 15. FLOAT DIALOGUE: MALE, NO REP (SNEAK) (WTG)
{330}{}{Tribal, será mejor que dejes esa mierda de andar a hurtadillas *ahora mismo*.}

# 16. MYRON, MORDINO (WTG)
{340}{}{[A Myron] Hey, hey… ¡Myron! Hace mucho tiempo que no te veía fuera del laboratorio.}
{000}{}{[A Myron] ¿Estás aquí para probar alguna nueva mercancía, Myron?}
{000}{}{[A Myron] ¡Hey! Entra, Myron.}

# 17. MARCUS (WTG)
{350}{}{[Señala a Marcus]. Nada de mutantes. Que espere fuera.}
{000}{}{[Señala a Marcus]. No me importa si tu amigo es uno de los X-Men, los mutantes esperan fuera.}
{000}{}{[Mira fijamente a Marcus]. Ese bicho raro mutante no puede entrar.}

# 18. ROBOBRAIN (WTG)
{360}{}{Nada de droides.}
{000}{}{No servimos a droides.}
{000}{}{Nada de droides. Que espere fuera.}

# 19. FLOAT DIALOGUE: FLAG: ENCLAVE DESTROYED IS TRUE  (WTG)
{370}{}{Se supone que no puedo charlar estando de servicio, pero me alegra que le patearas el culo al Enclave.}
{000}{}{Oye, [X]. Tómate un descanso de lo de salvar al mundo y diviértete un poco.}

# 20. FLOAT DIALOGUE: DAY (WTG)
{380}{}{Se necesitan más fichas en la mesa tres…}
{000}{}{Hay mucha gente hoy…}

# 21. FLOAT DIALOGUE: NIGHT (WTG)
{390}{}{Se necesitan más fichas en la mesa tres…}
{000}{}{Hay mucha gente esta noche…}

# 22. INTRO (WTG)
{400}{}{¡Oye, [X]! ¡He oído que fuiste tú quien envió al Enclave de una patada hasta la Edad de Piedra! [Su tono se vuelve formal]. Me han dado instrucciones de entregarte algunas fichas, cortesía del casino. Disfrútalas, caballero.}
{000}{}{¡Oye, [X]! ¡He oído que fuiste tú quien envió al Enclave de una patada hasta la Edad de Piedra! [Su tono se vuelve formal]. Me han dado instrucciones de entregarte algunas fichas, cortesía del casino. Disfrútalas, señora. [Te guiña un ojo].}
{000}{}{Oye, [X]. [Sonríe]. ¿Qué tal, jefe? ¿Necesita algo? ¿Una copa? ¿Una camarera?}
{000}{}{Oye, [X]. [Sonríe]. La chica más hermosa en el casino. ¿Necesitas algo? ¿Una copa? ¿Una mesa privada?}
{000}{}{[El vigilante de sala no aparta su mirada del suelo del casino]. ¿Qué puedo hacer por ti, amigo?}
{000}{}{[El vigilante de sala no aparta su mirada del suelo del casino]. ¿Qué puedo hacer por ti, guapa?}
{000}{}{Fooooooo foo foo fooooo}
{000}{}{Me marcho [Te vas].}
{000}{}{¿Quién eres?}
{000}{}{¿Qué casino es este?}
{000}{}{¿Puedes contarme algo sobre el casino?}
{000}{}{¿Conoces a alguien llamado Lloyd el Guapo?}
{000}{}{¿Quién es ese viejo de la máquina tragaperras?}
{000}{}{Ese cómico que tenéis en el escenario apesta. ¿Te importa si lo intento yo?}
{000}{}{Gracias. ¿Necesitas a alguien que baile durante la noche? No me importaría una participación limitada.}
{000}{}{Gracias, lo haré. [Te marchas].}
{000}{}{Nada, gracias. Perdón por molestarte. [Te marchas].}
{000}{}{Sólo comprobaba las cosas. Seguid así. [Te marchas].}

# 23. PORN STAR (WTG)
{420}{}{Hey, mirad quién está aquí! Hola, [PS]. [Sonríe]. Te doy la bienvenida a [CN]. Me encantan tus películas.}
{000}{}{Fooooooo foo foo fooooo}
{000}{}{Me marcho [Te vas].}
{000}{}{¿Quién eres?}
{000}{}{¿Qué casino es este?}
{000}{}{¿Puedes contarme algo sobre el casino?}
{000}{}{¿Conoces a alguien llamado Lloyd el Guapo?}
{000}{}{¿Quién es ese viejo de la máquina tragaperras?}
{000}{}{Gracias. ¿Necesitas a alguien que baile durante la noche? No me importaría una participación limitada.}
{000}{}{Gracias, me halaga. Sólo me he detenido a saludar. [Te marchas].}

# 24. I HAD SOME QUESTIONS (31, 32, 33, 34, 35, 36, 37, 38)
{440}{}{Dispara. ¿Qué quieres saber?}
{000}{}{Fooooooo foo foo fooooo}
{000}{}{Me marcho [Te vas].}
{000}{}{¿Quién eres?}
{000}{}{¿Qué casino es este?}
{000}{}{¿Puedes contarme algo sobre el casino?}
{000}{}{¿Conoces a alguien llamado Lloyd el Guapo?}
{000}{}{¿Quién es ese viejo de la máquina tragaperras?}
{000}{}{Ese cómico que tenéis en el escenario apesta. ¿Te importa si lo intento yo?}
{000}{}{Gracias. ¿Necesitas a alguien que baile durante la noche? No me importaría una participación limitada.}
{000}{}{Nada, gracias. Perdón por molestarte. [Te marchas].}
{000}{}{Sólo comprobaba las cosas. Seguid así. [Te marchas].}

# 25.  RETARD (22, 23, 24)
{460}{}{Eh, será mejor que se vaya ahora mismo, señor.}
{000}{}{Eh, será mejor que se vaya ahora mismo, señora.}
{000}{}{[Resopla]. Largo de aquí, retrasado.}
{000}{}{Mamá dice que yo soy especial}
{000}{}{Me marcho [Te vas].}

# 26.  MOM SAYS I WAS SPESHAL (25)
{470}{}{Sí, tu mamá dijo que yo también era especial. Y ahora haz una excursión… quizá ella esté en alguna parte de la calle Virgin.}
{000}{}{¡Oh, qué bien! Adiooos [Te marchas].}
{000}{}{Me marcho [Te vas].}

# 27.  WHO ARE YOU? (22, 23, 24, 29, 30, 31)
{480}{}{Soy el vigilante de sala. [Parece un poco irritado]. ¿Qué puedo hacer por ti?}
{000}{}{Gestiono esta planta del casino. Si necesitas algo, tan solo pregunta.}
{000}{}{¿Qué casino es este?}
{000}{}{¿Puedes contarme algo acerca del casino?}
{000}{}{Nada, gracias. Perdón por molestarte.}

# 28.  WHAT CASINO IS THIS? (22, 23, 24, 27)
{490}{}{El [CN]. Si necesitas algo, tan solo pregunta.}
{000}{}{El [CN]. Al menos, era así la última vez que comprobé el cartel de la entrada. [Frunce el ceño]. Y ahora, ¿qué puedo hacer por ti?}
{000}{}{¿Quién eres?}
{000}{}{Puedes contarme algo acerca del casino?}
{000}{}{Nada, gracias. Perdón por molestarte.}

# 29.  WHAT CAN YOU TELL ME ABOUT THIS CASINO? (22, 23, 24, 27, 28, 30)
{500}{}{Es el jodido mejor casino de la ciudad… pero soy un poco parcial. [Ríe]. ¿Quieres saber algo más?}
{000}{}{Es el jodido mejor casino de la ciudad, las mejores puñeteras mesas… y ahora, ¿por qué no te largas a comprobarlo? ¿De acuerdo?}
{000}{}{¿Quién eres?}
{000}{}{A quién pertenece este casino?}
{000}{}{De acuerdo, gracias. Lamento haberte molestado. [Te marchas].}

# 30.  WHO OWNS THIS CASINO? (29)
{510}{}{A la Familia [CA]. Insuflaron vida a este lugar, lo convirtieron en un auténtico punto de referencia de las noches, en una brillante joya en Nuevo Reno.}
{000}{}{A la Familia [CA]. ¿Eso es un problema? Porque si no estás aquí para apostar, entonces este no es lugar para ti. ¿Entendido?}
{000}{}{¿Quién eres?}
{000}{}{¿Puedes contarme algo acerca del casino?}
{000}{}{Ya veo. Gracias por tu tiempo. [Te marchas].}

# 31.  McGEE (22, 23, 24)
{520}{}{¿Ese tipo? ¿El Viejo McGee? El loco hijo de perra… ha estado jugando en esa máquina durante los últimos años, esperando el gran premio. Toda su fortuna debe estar dentro de esa cosa, pero no le devolverá ni una sola ficha.}
{000}{}{Ese tipo? ¿El Viejo McGee? Un loco hijo de perra, eso desde luego. Je. Seguro que le jodió que ganases su fortuna. Yo tendría cuidado con él.}
{000}{}{¿La máquina está trucada?}
{000}{}{Tenía algunas preguntas más…}
{000}{}{Gracias por la información. [Te marchas].}

# 32.  IS THE MACHINE RIGGED? (31)
{530}{}{[Niega con la cabeza]. Qué va, sólo es testaruda… igual que él. [Se encoge de hombros]. Probablemente podría repararse, pero no tenemos mecánicos de tragaperras que puedan arreglar esa maldita cosa.}
{000}{}{Tenía algunas preguntas más…}
{000}{}{Interesante. Gracias por la información. [Te marchas].}

# 33.  PRETTY BOY LLOYD? (22, 23, 24)
{540}{}{Sí, ese hijo de puta estuvo aquí hace una semana, desplumó unas mil fichas a una de las mesas, y luego se largó. No sé dónde está ahora, pero solía tener una habitación en el Desperado.}
{000}{}{Sí, cierto tipo con ese nombre alquiló una de las habitaciones de arriba... la 204. La tenía pagada, pero se largó hace unos días y nadie lo vio marcharse.}
{000}{}{El señor Salvatore mencionó que hubo una croupier en particular al que Lloyd le ganó el dinero. ¿A quién fue?}
{000}{}{Tenía algunas preguntas más…}
{000}{}{Gracias por la información. [Te marchas].}

# 34.  NIKKI? (33)
{550}{}{¿Nikki? [Comprueba la estancia]. Sí, está por allí, en la mesa central. ¿Hay alguna clase de problema?}
{000}{}{No hay problema. Sólo quiero reunirme con ella. Tenía algunas preguntas más…}
{000}{}{Gracias por la información. [Te marchas].}

# 35.  NIKKI DEAD (33)
{560}{}{Su nombre *era* Nikki. Solía trabajar aquí, pero se la cargaron… no hace mucho.}
{000}{}{Hmmm. ¿Te importa si te hago algunas preguntas más?}
{000}{}{Interesante. Gracias por la información. [Te marchas].}

# 36.  NIKKI RAN (33)
{570}{}{Se llamaba Nikki. Solía trabajar aquí, pero se largó hace poco tiempo. Hizo las maletas y desapareció.}
{000}{}{¿Te importa si te hago más preguntas?}
{000}{}{Interesante. Gracias por la información. [Te marchas].}

# 37.  NEED A DANCER (22, 23, 24)
{580}{}{Claro, sería bueno para el negocio. El vestuario está en la parte de atrás…}
{000}{}{[Actúas].}
{000}{}{No, ahora no. Tengo más preguntas…}
{000}{}{Ahora no, pero volveré más tarde. [Te marchas].}

# 38.  NEED A DANCER (22, 23, 24)
{590}{}{[Niega con la cabeza]. No, todavía nos estamos recuperando de tu última actuación. A lo mejor te interesa probar en alguno de los otros casinos.}
{000}{}{Está bien, gracias. Oye, tenía algunas otras preguntas…}
{000}{}{Vale… aunque *volveré*. [Te marchas].}

# 39.  PERFORM (37)
{600}{}{Parece que este no va a ser un mal negocio después de todo. [C] = fichas. No, nada malo.}
{000}{}{Lo del cuero fue un gran idea por tu parte.}
{000}{}{Ese gag de la pelota tampoco ha estado mal, la verdad.}
{000}{}{[Hecho].}

# 40.  PERFORM (22, 24)
{610}{}{Sí, apesta más que la mierda de brahmin. Aún así, ¿tú…? [Te mira de arriba abajo con escepticismo]. Bueno, qué demonios. Un poco de improvisación no hará daño, aunque es un público difícil… espero que lo hagas bien.}
{000}{}{Oh, lo haré bien… vas a comprobarlo.}