# QUICK LOOK
{100}{}{Ves a uno de los hijos de Wright. }

# LOOK (IF MALE) (WTG)
{150}{}{Ves a un chico pequeño de pelo negro.}
{151}{}{Ves a una chica pequeña de pelo negro. Tiene el pelo tan corto, que casi la confundes con un chico.}

{155}{}{Te saca la lengua.}
{156}{}{Te está mirando malhumorado.}
{157}{}{Te saca la lengua.}
{158}{}{Su pelo negro está tan corto, que puede usar, de modo muy conveniente, el modelo de personaje niño masculino.}
{159}{}{Te está mirando malhumorada.}

# 2. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{175}{}{Fallout 2, ofrecido en respuesta a la gran demanda de nadie.}
{176}{}{¡Oye! }
{177}{}{}
{178}{}{Gracias por salvarnos, }
{179}{}{Quiero salvar al mundo igual que tú cuando me haga mayor.}
{180}{}{¿Puedo ser un héroe como tú cuando me haga mayor?}
{181}{}{Quiero ser }

# 3. FLOAT [POWER ARMOR] (WTG)
{190}{}{¿Eres un ROBOT?}
{191}{}{¿Cómo haces pis dentro de esa cosa?}
{192}{}{¿Puedo cabalgar sobre tus hombros? ¿Porfaaaa?}
{193}{}{¿Quieres jugar con nosotros? ¿Porfaaaa?}

# 4. FLOAT AND CLICK [SLAVER OR BAD REP] (WTG)
{200}{}{Será mejor que corras antes de que mi papá te vea.}
{201}{}{Será mejor que corras antes de que mis hermanos te vean.}
{202}{}{Eres una persona mala. Mejor que te marches antes de que grite que estás aquí.}

# 5. FLOAT AND CLICK [SNEAKING] (WTG)
{210}{}{¡Te veo! ¡Te veo!}
{211}{}{¿Estás jugando a las escondidas? ¿Puedo jugar yo también?}

# 6. FLOAT COMMENTS [ROBOBRAIN + MARCUS] (WTG)
{215}{}{¡Mirad al robot! ¡Mirad al robot!}
{216}{}{¿Ese robot tiene deeentro un cerebro de verdad?}
{217}{}{Oooooooh. ¡Mirad al robot!}
{218}{}{¡Mirad al mutante! ¡Mirad al mutante!}
{219}{}{Mutante, tunante, mutante, tunante}
{220}{}{¿Eso es un mutante de verdaaad? Es feo-feo.}
{221}{}{Oooooooh. ¡Mirad al mutante!}
{222}{}{Ese mutante es GRANDE. Más grande que papá.}

# 7. FLOAT COMMENTS [LENNY + DOG] (WTG)
{230}{}{¡Necrófago! ¡Mirad es un necrófago!}
{231}{}{¡Aaaaaagh! ¡Necrófago! ¡Necrófago!}
{232}{}{¡Necrofagiiito, necrofagiiito, necrofagiiito!}
{233}{}{¡Mirad al perrito metálico!}
{234}{}{¡Perrito! ¡Aquí, perrito!}
{235}{}{¡Yo también quiero un perrito!}


# 10. FLOAT [ENCLAVE_DESTROYED = TRUE] (WTG)
{290}{}{Quiero salvar al mundo igual que tú cuando sea mayor.}
{291}{}{¿Puedo ser un héroe como tú cuando me haga mayor?}
{292}{}{Quiero ser como tú cuando sea mayor.}
{293}{}{¿Por qué tú quieres ser yo? Yo TONTO}
{294}{}{Una vez llevé un sombrero de cabeza de niña.}
{295}{}{Te alejas.}
{296}{}{Je je. Gracias, pequeño. Pero acepta un consejo de }
{297}{}{Persigue tus sueños. Podrás cumplir con tus objetivos. Yo soy la prueba viviente.}
{298}{}{Claro que puedes. Oye, siento lo que oí sobre tu hermano, Richie. ¿Sabes lo que le pasó?}
{299}{}{Una vez conduje a través de tres estados llevando la cabeza de esta niña como sombrero.}
{300}{}{(Le dejas que siga jugando).}
{301}{}{(La dejas seguir jugando).}

# 11. WHY YOU WANNA BE ME? ME DUMB. (10)
{310}{}{Oh, no! ¡Tú eres LISTO! Tú eres un HÉROE y eres VALIENTE y quiero ser como TÚ cuando sea mayor. Gracias por salvarnos, }
{311}{}{Graaaacias, persona p-pequeña. Haces }

# 12. FOLLOW YOUR DREAMS. (10)
{315}{}{Está bien, }
{316}{}{Ahora cuídate, ¿me oyes, pequeña? Tengo más cosas de héroe que hacer.}

# 13. I'VE GOT SOME THINGS TO DO. (12)
{320}{}{(El chico te detiene). Um… }
{321}{}{Eh… no. Lo prometo.}
{322}{}{Eh… no tan lejos como piensas.}
{323}{}{No te preocupes, pequeño. Volveré y te visitaré como un personaje distinto.}
{324}{}{No te preocupes, pequeño. No sentirás nada.}

# 14. UH, HARD DRIVE (13)
{330}{}{¿Soñaremos?}
{331}{}{Eh… desde luego. Claro que lo haréis.}
{332}{}{No tengo ni idea. A mí me parece que no sueño, así que probablemente tú tampoco. La vida es una putada, ¿eh?}

# 15. POWER ARMOR 1 (WTG)
{341}{}{¿Eres un r-robot?}
{344}{}{Je, je. Qué mono. No, no soy un robot, pequeño.}
{345}{}{No, no, soy una persona normal debajo de esta armadura. Por cierto, siento lo que oí acerca de tu hermano, Richie.
 ¿Sabes lo que le sucedió?}

# 16. WATZ A ROBOT?/YER DUMB, PEE-FACE/MOOTANT? (15, 25, 27, 29, 41)
{355}{}{Eres TONTO.}
{356}{}{TÚ TAMBIÉN.}
{357}{}{Lo mismo para ti, pero más.}
{358}{}{Eres más que tontoooo.}
{359}{}{El que lo huele debajo lo tiene.}
{360}{}{¡Rebota y en tu culo explota!}
{361}{}{Se aleja llorando.}

# 17. YER DUMBERR (16)
{370}{}{Eres el más tonto. ¡El más tonto!}

# 18. POOR RESPONSE (16, 17)
{395}{}{¡No, no, TONTO! (sale corriendo, Con sus carcajadas martirizando tus oídos).}
{396}{}{No quiero hablar con tú MÁS... *snfff*... yo... *snfff*... hago una FIESTA...
 con *snfff* PASTEL y HELADO... y tú NO puedes ir [Te marchas].}

# 19. YER DUMB-ESSTT-ERR (17)
{405}{}{(El niño parpadea, abre la boca y luego la cierra. Aparece una lágrima y empieza a sollozar).}
{406}{}{Jee jee YO gana}

# 20. I'M NOT A ROBOT (15, 28)
{410}{}{Oh (se queda pensando un momento, y luego te mira con los ojos entrecerrados). ¿Por qué tú NO eres un robot?}
{411}{}{Eh… porque… bueno, los robots y las personas tienen, eh… partes distintas.}
{412}{}{Tengo que irme.}

# 21. ROBOTS AND PEOPLE HAVE DIFFERENT PARTS (20)
{425}{}{Oh, ¿sí? (Parece sospechar). ¿Como cuales?}
{426}{}{Eh… bien… oye ¿tu mamá y tu papá no te han explicado todo esto?}
{427}{}{Eh… ¡anda! ¡Mira la hora que es! Tengo que irme.}

# 22. DIDN'T MOMMY AND DADDY EXPLAIN THIS TO YOU? (21)
{435}{}{¿Explicar el qué?}
{436}{}{Eh… bueno… los robots… tienen aceite dentro. Los humanos… bueno, los humanos… sangran.}

# 23. HUMANS BLEED (22)
{445}{}{Mamá y mis hermanas mayores sangran cada mes más o menos. Entonces se ponen realmente raras. Ojalá fueran robots.}
{446}{}{Eh… sí. Genial. Oye, tengo que irme: no le digas a tu mamá que he hablado contigo.}

# 24. POWER ARMOR 2 (WTG)
{456}{}{Sólo hago pis y m-me da igual el olor.}
{459}{}{Je, je. En realidad, me limito a orinar en la armadura, que lo recicla todo. ¿No es interesante?
 ¿Sabes lo que significa 'reciclar', pequeño?}
{460}{}{No con comodidad, eso seguro. Oye, siento lo que he oído acerca de tu hermano, Richie.
 ¿Sabes lo que le pasó?}

# 25. I PEE IN ARMOR (24)
{475}{}{Eso es ASQUEROSO.}
{476}{}{¡Sí! ¡Reciclar significa que bebes pis!}
{477}{}{TÚ eres asqueroso, cara de PIS}
{479}{}{Uh, je… je. En realidad no, significa…}

# 26. NO, ACTUALLY, IT MEANS . . . (25, 26)
{485}{}{¡Bebes pis! ¡Bebes pis!}
{486}{}{Eh, je… je… baja la voz, pequeño… reciclar no significa que beba p… bien, no EXACTAMENTE… verás…}
{487}{}{Dejas que el pequeño mierdecilla vuelva a jugar.}
{488}{}{(Te marchas).}

# 27. CLICK [ROBOBRAIN] (WTG)
{495}{}{¿Eso es un robot de VERDAD?}
{499}{}{¿El robocerebro? Pues sí, lo es.}
{500}{}{CREE que lo es. No me hagas hablar.}
{501}{}{Sí, pero no le molestes. Creo que quiere destruir a la raza humana.}
{502}{}{Sí, lo es. Oye, siento lo que he oído acerca de tu hermano, Richie. ¿Sabes lo que le pasó?}

# 28. CLICK [ROBOBRAIN] (27)
{515}{}{¿TÚ también eres un robot?}

# 29. CLICK [MARCUS] (WTG)
{525}{}{¿Es un mutante de VERDAD?}
{526}{}{Muuutante?}
{529}{}{Pues sí. Se llama Marcus. No te preocupes, que no muerde.}
{530}{}{Pues sí, ES un mutante. Dios, espero que no le apetezcan los niños pequeños.}
{531}{}{Pues sí. Un mutante MUY hambriento. Y justo ahora es momento de tomarse un tentempié. Qué conveniente.}
{532}{}{Pues sí. Oye, siento lo que he oído acerca de de tu hermano, Richie. ¿Sabes lo que le pasó?}

# 30. INTRO (WTG)
{540}{}{Se detiene y te mira.}
{541}{}{Hoooola}
{544}{}{Hola, hombrecillo.}
{545}{}{Hola, mujercita.}
{546}{}{Siento lo que he oído acerca de de tu hermano, Richie. ¿Sabes lo que le pasó?}

# 31. I DROVE THROUGH 3 STATES . . . (10, 15, 24, 27, 29 30, 41)
{555}{}{¿Estás enfermo?}
{556}{}{¿Por qué lo preguntas?}

# 32. WHY DO YOU ASK? (31)
{560}{}{PARECES enfermo.}
{561}{}{Estoy enfermo.}

# 33. I AM SICK. (32)
{565}{}{¿Has tomado una medicina?}
{566}{}{No hay medicina para lo que yo tengo.}

# 34. THERE IS NO MEDICINE FOR WHAT I HAVE. (33)
{570}{}{¿Quieres cantar?}
{571}{}{¿Cantar?}

# 35. SING? (34)
{575}{}{¿Conoces 'He's Got the Whole World in His Hands'?}
{576}{}{Sí, la conozco.}

# 36. YES, I DO. (35)
{580}{}{::Canta:: 'He's got the whole world in his hands. He's got the whole wide world in his hands'. Vamos.}
{581}{}{::Cantas:: He's got the whole world in his hands. He's got the whole wide world in his hands.}

# 37. SING TOGETHER (36)
{585}{}{::Cantáis juntos:: He's got the whole world in his hands. ::Poco a poco baja el tono de la canción:: He's got the whole world in his hands.}
{586}{}{Gracias por cantar conmigo. Volveré más tarde… si necesito un sombrero.}

# 38. HELLO, LITTLE MAN/WOMAN. (14, 37)
{590}{}{(El chico parpadea al verte).}
{591}{}{De acuerdo entonces. Hablaré contigo más tarde.}

# 39. TALK TO YOU LATER/LET HIM GO BACK TO PLAYING/THANKS FOR SINGING WITH ME (38)
{595}{}{(Sale corriendo).}

# 40. HELLO (MALE) (30, 40, 42)
{648}{}{Oh.}
{650}{}{¿En serio? ¿Qué más?}

# 41. CLICK [LENNY] (WTG)
{665}{}{¿Es un necrófago de VERDAD?}
{666}{}{¿Necr-rófago?}
{669}{}{Pues sí, sí que lo es. Se llama Lenny. No te preocupes, que no muerde.}
{670}{}{Pues sí, ES un necrófago. Dios, espero que no le apetezcan los niños pequeños.}
{671}{}{Pues sí. Un necrófago MUY hambriento. Y justo ahora es momento de tomarse un tentempié. Qué conveniente.}

# 42. HIS NAME IS MARCUS. (29, 40, 41)
{685}{}{Hola, mutante Mar-cus. Eres terriblemente grande. Je-je... y tu animación inquieta es divertida.}
{686}{}{Hola, necrófago Len-ee. Bue... de verdad que apestas.}
{687}{}{Claro que lo es, ¿verdad? Así que… qué pasa, muchacho?}
{688}{}{Claro que lo es, ¿verdad? Así que… qué pasa, muchacho?}
{689}{}{Bien, he de irme. Nos vemos más tarde.}

# 43. MARCUS/LENNY IS HUNGRY (29, 40, 41)
{695}{}{(El niño se pone pálido y luego echa a correr gritando).}
{696}{}{Je je je je. "¿Es un mutante de VERDAD?" Eso le enseñará a no hacer preguntas.}
{697}{}{¡Mutante "hambriento"! Noooo. Todo el mundo sabe que los mutantes no comen hum... eh, ¿por qué me miras así, Marcus?}
{698}{}{Je je je je. "¿Es un necrófago de VERDAD?" Eso le enseñará a no hacer preguntas.}
{699}{}{¡Necrófago "hambriento"! Noooo. Todo el mundo sabe que los mutantes no comen hum... eh, ¿por qué me miras así, Marcus?}

# 44. OD (10, 15, 24, 27, 29, 30, 40, 41)
{710}{}{Oh, oh. Papá está realmente enfadado porque no sabe quién mató a Richie. Dice que si alguna vez nos pilla
 tomando Jet, nos dará una paliza.}
{711}{}{¿Sabes QUIÉN podría haberle dado a Richie el Jet que lo mató?}
{712}{}{¿Sabes DÓNDE consiguió Richie ese Jet que lo mató?}
{713}{}{Dejas que el chico siga jugando.}

# 45. DO YOU KNOW WHO? (44, 46)
{720}{}{Uh-uh.}

# 46. DO YOU KNOW WHERE? (44, 45)
{730}{}{Uh-uh. Rondaba a menudo por la parte oeste de la ciudad, en la zona comercial, y papá nos dijo que no fuéramos por allí.}

# sleeping
{800}{}{*Shhh* Se supone que estoy durmiendo.}
{801}{}{Tengo que dormir un poco. Mañana voy a jugar mucho al juego del guerrero del insecto de metal.}
{802}{}{Si papá se entera de que no estoy durmiendo, se enfadará mucho, mucho.}

# 8/40. FLOAT [WRIGHT CHILDREN: BOYS] (WTG)
{900}{}{My ding-a-ling, my ding-a-ling.}
{901}{}{::Levanta un arma de juguete:: ¡Arriba las manos, bribón!}
{902}{}{Una buena acción merece otra, entre tus piernas tu madre se encuentra.}
{903}{}{Quiero ser un chulo cuando sea mayor.}
{904}{}{Gobernaré Nuevo Reno cuando sea mayor, igual que mi papá.}
{905}{}{Quiero un perrito. Papá dice que me conseguirá a una perra cuando sea mayor.}
{906}{}{Ojalá papá fuera tan genial como Tommy Pelotas.}
{907}{}{Tengo pene.}
# self_is_male ^
{908}{}{::Shriek::}
{909}{}{::Te saca la lengua::}
{910}{}{Papá llama a mamá fábrica de bebés.}
{911}{}{Papá dijo que nos azotará si alguna vez nos pilla tomando Jet.}
{912}{}{Papá dice que tenemos que tener cuidado cuando salgamos fuera.}
{913}{}{Papá nos va a azotar si volvemos a escaparnos.}
{914}{}{Papá ha enloquecido desde que murió mi hermano Richie.}
{915}{}{Papá está haciendo negocios otra vez.}
{916}{}{El Padre Tully es divertido cuando no puede andar en línea recta.}
{917}{}{Él tiene todo el mundo en sus manos… he's got the whole world in his hands…}
{918}{}{Hice caquita.}
{919}{}{Echo de menos a mi hermano, Richie. Murió porque tomó demasiado Jet.}
{920}{}{No he vuelto a ver a Christopher.}
{921}{}{Vi a Mikey besando a Mareee Mor-dino.}
{922}{}{Vi a mamá y a papá bailando uno encima del otro.}
{923}{}{Ojalá Christopher jugase conmigo.}
{924}{}{¡Kyle bebe su propio pis!}
{925}{}{Kyle tuvo diarrea.}
{926}{}{Nunca más, nunca más, enviad a Kyle a por más.}
{927}{}{¡Mírame! ¡Mírame!}
{928}{}{Mikey y Mareee estaban en un árbol, dándose un B-E-S-O.}
{929}{}{Milicent es una tacaña de primera.}
{930}{}{Leche, leche, limonada. Hacen algodón de azúcar en aquella balaustrada.}
{931}{}{Mamá y papá estaban otra vez hablando con Dios en la cama ayer por la noche.}
{932}{}{Mamá estaba llorando el otro día. Creo que es por lo que le pasó a mi hermano Richie.}
{933}{}{Mamá está muy triste desde que murió mi hermano Richie.}
{934}{}{Mommy ha ido a la iglesia otra vez.}
{935}{}{Nuestra familia es la mejor.}
{936}{}{Phfttttt}
{937}{}{¡Tonto del culo! ¡Tonto del culo!}
{938}{}{Tío Nick dice que blasfemar no es necesario. Tío Nick necesita salir más.}
{939}{}{¿Jugamos a tribales y esclavistas?}
{940}{}{Tenemos diecisiete hermanos y hermanas.}
{941}{}{Wheeeeeeee}
{942}{}{¡Tú lo eres!}
{943}{}{¡Tienes piojos!}
{944}{}{¡Pareces un escorpión rad!}
# self_is_female v
{945}{}{Voy a preguntarle a papá si puedo ser eso que llaman puta cuando sea mayor. Dice que realmente necesita una de eso.}
{946}{}{Quiero ser algo que llaman puta cuando sea mayor. Papá dice que necesitamos más de eso.}
{947}{}{Tengo vagina.}

# line endings
{1176}{}{! ¡Cuéntanos la historia del Enclave! Porfaaaaaa}
{1177}{}{! Yaaaaay!}
{1178}{}{!}
{1181}{}{ cuando crezca.}
{1296}{}{: puedes ser TODO lo que quieras cuando seas mayor.}
{1310}{}{. NUNCA te olvidaré.}
{1311}{}{ siente mejor. Gusto el salvarte}
{1315}{}{. no te olvidaré, lo prometo, aunque viva cien años.}
{1320}{}{? ¿Vas a borrarnos de tu disco duro ahora que has terminado el juego?}