# 0.  LOOK, CLOSED (WTG)
{100}{}{Ves una caja fuerte asegurada en la pared. Está cerrada.}

# 1.  LOOK, OPEN (WTG)
{150}{}{Ves una caja fuerte asegurada en la pared. Está abierta.}

# 2.  EXAMINE SAFE, CLOSED (WTG)
{200}{}{(Hay una pequeña puerta en la pared. ¡Ahí debe vivir una personita diminuta! Hay una rueda con números en el medio de la puerta).}
{000}{}{(Examinas la caja fuerte de la pared. Parece firmemente sujeta a la pared y tiene una rueda de combinación en el exterior).}
{000}{}{Llamas a la puerta}
{000}{}{Giras la rueda}
{000}{}{Te alejas}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda al azar.}
{000}{}{Examinas la caja en busca de trampas.}
{000}{}{Dejas la caja en paz.}

# 3.  SAFE IS OPEN (WTG, 7)
{220}{}{(Se escucha un CLIC, y la caja se abre).}
{000}{}{(La caja está abierta).}
{000}{}{(La puerta se balancea al abrirse. El interior de la casita es muuuuuy oscuro. Y pequeño).}
{000}{}{(¡La puerta se abre! El interior es muuuuuy oscuro. Y pequeño).}
{000}{}{Buscas gente en la casita.}
{000}{}{Te alejas.}
{000}{}{Saqueas la caja.}
{000}{}{Dejas la caja en paz.}

# 5.  CLICKING (2, 5, 6, 8)
{240}{}{(Giras la rueda lentamente durante varios minutos, pero no consigues nada).}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda al azar.}
{000}{}{Examinas la caja en busca de trampas.}
{000}{}{Dejas la caja en paz.}

# 6.  TRAPS . . . ? (2, 6, 8)
{260}{}{(No encuentras ninguna trampa en la caja).}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda al azar.}
{000}{}{Examinas la caja en busca de trampas, de nuevo.}
{000}{}{Dejas la caja en paz.}

# 7.  SPIN RANDOM, SUCCEED (2, 5, 6, 8, 9)
{270}{}{(Estás girando la rueda... ¡cuando de repente se escucha un CLIC, y la puerta se abre!)}
{000}{}{(Estás girando la rueda al azar, cuando de pronto llega a un número y... ¡se escucha un CLIC, y la caja se abre!)}
{000}{}{¿Hola? ¿Hooooolaaa? ¿Hay alguien en casa?}
{000}{}{Sí, soy un tipo con suerte...}

# 8.  SPIN RANDOM, FAIL (2, 5, 6, 8, 9)
{280}{}{(¡Giras la rueda, pero la puertecita no se quiere abrir!)}
{000}{}{(Giras la rueda durante varios minutos, pero no ocurre nada).}
{000}{}{Llamas a la puerta}
{000}{}{Sigues girando la rueda}
{000}{}{Te alejas}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Giras la rueda, escuchando los clics.}
{000}{}{Sigues girando la rueda al azar.}
{000}{}{Examinas la caja en busca de trampas.}
{000}{}{Dejas la caja en paz.}

# 9.  HELLO? (2, 8, 9)
{300}{}{(No escuchas a nadie, y no ves ningún timbre. Quizá no hay nadie en casa).}
{000}{}{(Nadie sale por la puerta).}
{000}{}{(Te empieza a doler la mano).}
{000}{}{(Si hay alguien en casa, no parece que quiera responder).}
{000}{}{Llamas a la puerta de nuevo.}
{000}{}{Giras la rueda.}
{000}{}{Te alejas.}