{100}{}{You see a guard.}
{101}{}{You see a guard in combat armor.}
{102}{}{You see someone wearing combat armor. There is an insignia on the breastplate
 that you are unfamiliar with.}

{103}{}{Nothing to report.}
{104}{}{Nothing going on with me, how 'bout you?}
{105}{}{Shouldn't you be at your post, soldier? It's not good to wander about here.}

{106}{}{You're out of uniform.}
{107}{}{You better report to the Sarge and get suited up.}
{108}{}{You're taking a big chance being out of uniform. You better report to supply.}

{109}{}{Who the hell are you guys... Alert! Intruders!}
{110}{}{We've been infiltrated! Alert!}
{111}{}{Multiple intruders! Sound the alarm!}

{112}{}{Security alert! Seal the base!}
{113}{}{Secure all stations! We're on alert}
{114}{}{Intruder alert! Go code red!}

{115}{}{We're going to put you under!}
{116}{}{The Enclave will rule the world!}
{117}{}{You die so that the Enclave will survive!}

{118}{}{Sorry, soldier. That area is off limits to base personnel. I have to ask you
 to leave.}
{119}{}{Doc want me kill D'claw. He no want do himself.}
{120}{}{Okay, me go.}
{121}{}{Doc wants me to kill the critter for him. He doesn't want to do it himself.}

{122}{}{I knew the bastard wouldn't have the balls to do it himself. Oh no, it's okay
 if one of us gets fucked up. (sigh) Oh well. Go on in and good luck, soldier.}
{123}{}{Thanks.}

{124}{}{Why are you looking at me like that, soldier?}
{125}{}{Me hear you call Snookie. That cute.}
{126}{}{I hear you're called Snookie. I think that's cute.}

{127}{}{What... He told you that? When I get off duty I'm going to kick his ass...
 Move along, soldier. And wipe that smirk off your face!}
{128}{}{Okay.}