# 0. Look
{100}{}{You see a guard.}
{101}{}{You see Marc, a guard.}
{102}{}{You see Marc, one of Tyler's guards.}

# 1. Door opened
{150}{}{Yo, Tyler!}

# 2. Hostile
{200}{}{What the…?}

# 3. Gang 1 Won War
{225}{}{I knew we could take those pussies.}
{226}{}{Thanks for the tip. That was some fun stuff.}
{227}{}{Too bad we killed them all. Now what are we to do?}
{228}{}{Are we hot or what?}
{229}{}{We're too good.}
{230}{}{We fucking kicked some ass! Fuck yeah!}

# 4. TRAP NO
{250}{}{Tyler's the one to talk to, not me, lady.}
{251}{}{What's up. You need something, you gotta talk to Tyler here.}
{252}{}{What you looking at?}
{253}{}{Tyler's the one to talk to, not me, man.}

# 5. TRAP SET
{255}{}{We're going to kick some ass tonight!}
{256}{}{Tonight's the night!}
{257}{}{I'm going to remember this night for sure.}
{258}{}{Don't even tell me they chickened out.}
{259}{}{Oh, I sure hope those fuckers show.}

# 6. TRAP NOSHOW
{260}{}{I knew those pussies wouldn't show.}
{261}{}{We should just go kick their asses just for thinking about fighting us.}
{262}{}{We would have ripped through them if they had showed.}
{263}{}{I could have taken them on by myself.}
{264}{}{Tyler and I would have kicked some serious ass.}