{100}{}{You see a lean, tan looking man.}
{101}{}{You see a farmer.}
{102}{}{You notice he has a farmer's tan.}
{103}{}{You arrived just in the nick of time. If you hadn't gotten here when you did...Well, let's just
 be thankful that you came when you did. We don't have much, but I'd like you to accept this as a
 reward for helping us. [He hands you something.]}
{104}{}{Thank you.}
{105}{}{Ug}
{106}{}{Thanks again for helping us.}
{107}{}{}
{108}{}{}
{109}{}{You just keep your hands where I can see them. We've been plagued by bandits lately, and I
 think you just might be one of them. What do you want?}
{110}{}{I just wanted to trade for supplies.}
{111}{}{I'm just passing through. I'll be on my way.}
{112}{}{Ug.}
{113}{}{Well, I guess there's no harm in that. Here's what I got to trade.}
{114}{}{[Barter]}
{115}{}{OK, now git!}
{116}{}{[Barter]}
{117}{}{I said git!}
{118}{}{}
{119}{}{[He relaxes a bit.] You're too stupid to be a bandit. Do you need supplies?}
{120}{}{Uh huh.}
{121}{}{Eh eh.}
{122}{}{Well then, we got no business. You just keep moving, then.}
{123}{}{[END]}
{124}{}{Leave my farm!}
{125}{}{Nobody is going to take my home from me.}
{126}{}{Filthy bandits.}
{127}{}{Get off my land.}
{128}{}{Can't trust anyone these days.}
{129}{}{Damn bandits.}
{130}{}{I've worked too hard to give up now.}
{131}{}{Maybe I'll farm elsewhere.}
{132}{}{I'm just a poor farmer.}
{133}{}{Please, don't burn my farm down.}
{134}{}{I didn't like farming anyway.}
{135}{}{I'll be back.}
{136}{}{Take my wife - please...}