{100}{}{A nomad.}
{101}{}{Nomad chieftain.}
{102}{}{By his dress and the way he carries himself, he must be a leader of some sort.}
{103}{}{Ah, a traveler. Be welcome to my humble tent. Take shade from the unending heat of the land.}
{104}{}{Thank you; I graciously accept your offer of shade.}
{105}{}{I must decline your offer. I am just passing through.}
{106}{}{Ooga.}
{107}{}{Be welcome, then. We have long been away from the 'civilized' lands. We are in need of
 certain items. Perhaps we might be able to trade?}
{108}{}{What do you have to trade?}
{109}{}{I have nothing to trade. Sorry.}
{110}{}{Perhaps another time, then? May your travels be free of danger.}
{111}{}{Bye.}
{112}{}{How unfortunate. Then rest and be welcome in my camp.}
{113}{}{Bye.}
{114}{}{My offer of shade has come too late for you. The sun must have boiled away words from your
 brain. I must be kind to those less fortunate than I. Stay as long you like in my camp, dimwitted one.}
{115}{}{Bye.}
{116}{}{Infidel!}
{117}{}{Why do you attack us?}
{118}{}{I will defend the tribe with my life!}
{119}{}{How dare you violate our hospitality.}
{120}{}{Be gone!}
{121}{}{Leave us.}
{122}{}{We are a peaceful tribe.}