{100}{}{You see a computer terminal.}
{101}{}{You see a Hubologist computer.}
{102}{}{You see a computer. It seems to be in good working order, though primitive.}
{103}{}{This unit not accepting commands. Goodbye.}
{104}{}{[Try as you might, you can't seem to break the encryption that controls this computer.]}
{105}{}{Log off.}
{106}{}{Welcome to HubLink.}
{107}{}{Please enter your commands now.}
{108}{}{Access database.}
{109}{}{Access controls.}
{110}{}{Log off.}
{111}{}{Select database.}
{112}{}{Research.}
{113}{}{Future goals.}
{114}{}{Finances.}
{115}{}{Back.}
{116}{}{[After wading through the religious gobbledygook, it appears that the Hubologists have created a means of hardening power armor. They have also found a way to compute launch trajectory, orbits, and spatial destinations. Further, it appears they're working on weather control.]}
{117}{}{Back.}
{118}{}{Log Off}
{119}{}{[You spend about half an hour reading about the goals AHS-9 is trying to achieve. In addition to enlightenment and reunion with the Star Father, it appears that he's also got no qualms about destroying humans who weren't with him from the beginning. He's a little crazy.]}
{120}{}{Back.}
{121}{}{Log Off.}
{122}{}{[The Hubologist Church appears to be hugely wealthy. The standard approach is to ask a new recruit to donate all his or her worldly possessions to the Church as a sign of good faith.  When someone isn't asked to do this, apparently it means the Hubologists aren't intending to deal fairly. They have a huge cache of loot stashed somewhere in the desert. You can't quite figure out the coordinates.]}
{123}{}{Back.}
{124}{}{Log Off.}
{125}{}{Controls accessed. Select operation.}
{126}{}{Format hard drive.}
{127}{}{Systems status check.}
{128}{}{Back.}
{129}{}{Log Off.}
{130}{}{Operation restricted. Consult system administrator. Logging off. Goodbye.}
{131}{}{-done-}
{132}{}{There doesn't seem to be an interface for that.}

{133}{}{ESS Quetzel fueled and ready to launch.}
{134}{}{ESS Quetzel unfueled.}
{135}{}{Mainframe operational. Pipeline operational. Reasearch stations operational. Repair center operational. Cameras operational.}
{136}{}{Back.}
{137}{}{Log off.}