{100}{}{You see someone whose skin has been very badly burnt. It seem to be standing guard here.}
{101}{}{You see a ghoul acting as a guard.}
{102}{}{You see someone whose skin seems to have been burned with radiation. That much radiation looks
 as though it should have killed it, but it seems well enough. It looks as though it's
 standing guard here.}

{110}{}{Welcome to the atomic power plant. Just a warning to you: if anything goes wrong while you’re
 inside, we’re going to blame you, smoothskin.}
{111}{}{Hello, friend. I have to let you know that if anything goes wrong, any non-ghouls -- like you --
 are going to be blamed.}
{112}{}{Blook?}
{113}{}{I’ll be careful. I’m looking for something, and I wonder if you could direct me.}
{114}{}{That’s only fair, I suppose. I’ll be careful. Goodbye.}

{120}{}{You’re back, huh? Take a wrong turn?}
{121}{}{Brugah.}
{122}{}{Actually, I do need directions to something else.}
{123}{}{I thought I saw people living in here. Is that safe?}
{124}{}{Uh, no. That’s all right. I’m just kind of looking around. Goodbye.}

{130}{}{Oh. Well, what did you want help finding? The reactor control room, the supply room, the robot
 control room, or the reactor pit?}
{131}{}{The reactor control room.}
{132}{}{The supply room.}
{133}{}{The robot control room.}
{134}{}{The reactor pit.}
{135}{}{I guess I don’t need directions after all. Goodbye.}

{140}{}{I think Jeremy has a key. The guards at the security doors have keys, as do some of the people
 that live here in the reactor.}
{141}{}{Interesting. Let me ask you something else.}
{142}{}{Thanks. That’s all I needed to know. Goodbye.}

{150}{}{The reactor pit is just past the control room and then past Festus’ room. But you’re going to
 need a Red Keycard to get in there.}
{151}{}{Where’s the reactor control Room?}
{152}{}{Interesting. Let me ask you something else.}
{153}{}{I need a keycard? How do I get one of those?}
{154}{}{Thanks. That’s all I needed to know. Goodbye.}

{160}{}{The supply room is through the door to the left of the one that you came into the building
 through. You need to talk to Jeremy in there if you want to get supplies.}
{161}{}{Thanks. I need to know where something else is, though.}
{162}{}{Thanks. That’s all I needed to know. Goodbye.}

{170}{}{Well, we tend to like the background radiation leakage here. The Glowing Ones really like it.
 None of us would feel very well without it.}
{171}{}{Interesting. Let me ask you something else.}
{172}{}{Background leakage?!?!}
{173}{}{Oh, okay. Well that’s all I needed to know. Goodbye.}

{180}{}{The reactor control room is through the door to the right of the one you entered the building
 through. Then through a door at the end. Past the Yellow Security Door. Then you go off to the right.
 You’ll need a keycard for the security door, though.}
{181}{}{Interesting. Let me ask you something else.}
{182}{}{I need a keycard? How do I get one of those?}
{183}{}{Thanks. That’s all I needed to know. Goodbye.}

{190}{}{Don’t know why you’d want to go there. Damn maintenance robot hasn’t worked right in years.
 It’s just past the reactor control room, though.}
{191}{}{Where’s the reactor control room?}
{192}{}{Interesting. Let me ask you something else.}
{193}{}{I need a keycard? How do I get one of those?}
{194}{}{Thanks. That’s all I needed to know. Goodbye.}

{200}{}{Well, I wouldn’t worry unless you plan to stay here for more than a couple of weeks. Most of
 the radiation that the reactor leaks goes into the coolant water, and we pump that back underground.
 The little bit that leaks aboveground just feels good to us, somehow.}
{201}{}{Oh, well, that doesn’t sound so bad. Let me ask you something else.}
{202}{}{Hmm, I think I better be moving along. Goodbye.}

{300}{}{Sure. What else would you like to know?}
{301}{}{I need directions to someplace else.}