{100}{}{A very active old man.}
{101}{}{Grisham.}
{102}{}{You can’t quite place him, but he looks familiar.}

{151}{}{I told you you’d get yours!}
{152}{}{Bwahahaha!}
{153}{}{Go away!}
{154}{}{I'm busy!}
{155}{}{I knew my daughter was odd.}
{156}{}{Different people, different tastes, I suppose.}
{157}{}{I think I’m going to be sick.}
{158}{}{I knew my son was odd.}

{159}{}{I guess you’re family, now.}
{160}{}{You take good care of my daughter.}
{161}{}{You take good care of my son.}

# Node 0
{162}{}{The name’s Grisham. Welcome to my slaughterhouse. You dropping off or picking up?}
{163}{}{I guess picking up? I’m interested in buying some traveling provisions.}
{164}{}{You wouldn’t have happened to have seen a gold watch lying around here somewhere?}
{350}{}{[Looking at Bessy] Dropping off.}

# Node 1
{165}{}{What can I do for you now?}
{166}{}{I would like to buy some of your famous jerky.}
{168}{}{Can you tell me a little bit about the slaughterhouse?}
{169}{}{I see the drought hasn’t affected your business yet.}
{360}{}{I'd like you to make some jerky for me.}

# Node 2
{170}{}{I knew you’d be able to handle it. Let’s see now, I owe you $1000 for completing the job. Of course, }
{171}{}{ brahmin got killed due to your carelessness. At $100 per brahmin your reward is }
{172}{}{. Don’t even bother to lie about the number of brahmin killed -- I had one of my boys follow you
 out and watch from a distance.}
{173}{}{You never said anything about charging me if any brahmin died!}
{174}{}{Why, you conniving, dried up old coot. Arg! Mark my words - this is the last time you get the best
 of me!}
{175}{}{Thanks, pops; pleasure doing business with ya.}

# Node 3
{176}{}{How dare you show your face around here. I lost ten brahmin due to your cowardice. However, if
 you wish to make amends, $1500 would do a lot to cover my losses.}
{177}{}{Those brahmin weren’t worth more than a $1000.}
{178}{}{I don’t have that kind of money, and if I did, I wouldn’t give it to a little trickster like
 you.}
{179}{}{I’ve left my money in my room; let me go get it for you.}

# Node 10
{180}{}{Ah! Of course, of course. Let’s see, for traveling, I recommend our world famous dried brahmin
 strips. Won’t spoil on the road and it’s tasty, too. Only $10 a package. You interested?}
{181}{}{Sounds good; give me one package.}
{182}{}{No thanks, maybe later. I would like to ask you some questions, though.}
{183}{}{A pleasure doing business with you. Is there anything else I can do for you?}
{185}{}{Wait! You look to be a capable traveler. I don’t suppose you’d be interested in making some
 money?}
{186}{}{Are you sure you’re not interested in making some money? I’m quite sure you’d be able to solve
 my problem quite easily.}
{187}{}{That depends. How much, what do I have to do, and most importantly, HOW MUCH?}
{188}{}{Smart as whip! You remind me of myself when I was young. Simple... some wild dogs have been
 coming down out of the hills lately looking for food. I think they find brahmin easy prey and have been
 attacking my herds nightly. Wipe out their pack, and I’ll give you $1000.}
{189}{}{You’re holding something back, you old coot. What’s the catch?}
{190}{}{Perceptive as well as smart. I knew I wouldn’t be able to pull anything on you. The catch is
 that for every brahmin you let get killed, I charge you $100. I pay well for success and I also charge
 for failure. That’s the risk you take working for me.}
{191}{}{Great! Head out to the pastures at night and kill the pack of wild dogs that are attacking my
 brahmin. Come back here when you finish the job.}
{192}{}{Great jumping horny jacko-snatchers! Is Cornelius still looking for his lost watch? Why can’t he
 accept that it’s gone? That dang watch never worked anyways, and I’ll be a brahmin’s uncle if it was
 actually made of gold. Give it up; you’ll never find it.}
{193}{}{Actually, Farrel asked me to look for it.}
{194}{}{Can I ask you a few more questions?}
{195}{}{Thanks all the same, but I’ll keep looking.}
{196}{}{I didn’t? Are you sure? I could have sworn I told ya... maybe next time you won’t go accepting
 jobs until you know all the details. Now if you don’t mind, I have other work to attend to.}
{197}{}{Hehehe. Now that all depends. Are you planning to stay in town much longer? Bwahahahaha!}
{198}{}{I see you’re no fool. OK - $1000 then, and we call it even. Shake on it.}
{199}{}{[SHAKE HANDS WITH GRISHAM]}
{200}{}{Now hold on a minute. Now that I think of it, those brahmin looked a bit thin. How about $750,
 instead?}
{201}{}{I changed my mind, I don’t want to pay you.}
{202}{}{[Gives you a big toothy smile] Good to see you’re a person of character.}
{203}{}{[Grisham turns beet red and talks to you with teeth clenched.] OK, $750 then. Give me the money!}
{204}{}{You know, $750 still seems kind of expensive. Those brahmin would have died anyway if the dogs
 didn’t get them first. But I’m not totally selfish; I’ll give you $50.}
{206}{}{FINE! GIVE ME THE MONEY AND GET OUT!}
{207}{}{[LEAVE WITHOUT PAYING]}
{208}{}{Mark my words, you’ll get yours. If not by me, then by someone else.}
{209}{}{[Grisham smiles at you in such a way that you involuntarily take a step back.] Why don’t you
 just keep your money? I have feeling you might have need of it later.}
{210}{}{Not much to tell. I run the slaughterhouse in Modoc; you want something slaughtered, you bring
 it to me. I’ll kill it for ya and make it into some of the best jerky you’ve ever tasted.}
{211}{}{What about the hides and other parts of the animal?}
{213}{}{Actually, it has kind of helped my business. Nobody has been able to grow sufficient
 food for their brahmin, so they are severely culling their herds. But that’s just a temporary thing;
 you have to look at the big picture. With the decline in the brahmin population, my business can only
 suffer.}
{215}{}{[Grisham walks around you, pokes you a couple of times and then opens you mouth and checks your
 teeth.] Ah! A fine, healthy specimen. You’ll do fine. Ahem… Bad doggies, killing good brahmin. Go kill
 the bad doggies for your friend Grisham. Grisham will give big reward. OK?}
{216}{}{No, me like doggies. Only bad man no like doggies. Me go away from bad man.}
{217}{}{I do it. Go there now!}
{218}{}{Good! Remember, bad things go ‘Woof! Woof!’ Good things go ‘Moo.’ Try not to kill the good things.}
{219}{}{You seem to be a little short of money. I don’t take credit and I certainly don’t believe in
 giving something for nothing.}
{221}{}{That’s what I get for sending a Neanderthal. Just go!}
{222}{}{Uh… snarf ick unga bunga. Now take your money and be a good little Neanderthal and leave.}
{223}{}{You are quick, aren’t you? Well, if you ask you can retrieve any part of the animal you want.
 Balthus will usually buy the hides, and Rose will buy whatever scraps you don’t want. She uses it to
 make soup and feed her dogs.}
{225}{}{You’ve got to be kidding. Everyone knows Farrel took the watch. Why would he ask you to search
 for it… unless Farrel didn’t steal the watch after all! Or maybe this is a trick to convince everyone
 he didn’t take it. I need to think this out.}
{228}{}{Boy, don’t even try to explain this. I don’t want to hear it. I’m gonna get the preacher, make
 this all lawful like, and you will leave and take my son with you when you go.}
{229}{}{I can’t say I’m not just a little turned on by this, but I can’t have her living in this house
 now that I’ve seen it. You two are going to have to get hitched and leave.}
{230}{}{You mind explaining what yer doing with my daughter?}
{231}{}{You mind explaining what yer doing with my son?}
{232}{}{Let me explain it to you gently, pops. There are these birds and bees, you see… }
{233}{}{I’m a doctor, and I was just giving her a complete physical.}
{234}{}{I’m a doctor, and I was just giving him a complete physical.}
{235}{}{This isn’t what it appears to be.}
{236}{}{That’s just great. I’m going to have a smart-ass as son-in-law. Well,, come on… son. Let’s get
 this over with.}
{237}{}{That’s just great. I’m going to have a smart-ass as a daughter-in-law. Well come on… daughter. Let’s get
 this over with.}
{238}{}{Let me see. It looked to me that you and my daughter were imitating the brahmin during mating
 season.}
{239}{}{Let me see - it looked to me that you and my son were doing the horizontal tango between the
 sheets.}
{240}{}{OK, maybe it is what it appears to be. But it’s only sex, it’s not like there’s love involved or
 anything.}
{241}{}{I understand perfectly. Hormones, and it being that special time of the year.}
{242}{}{I’m glad you understand.}
{243}{}{I understand. I hope you understand that you both are gonna hafta get hitched. Can’t have rumors
 flying about town, you know. Come along and let’s go get the preacher. Don’t make me fill ya full of
 buckshot.}
{244}{}{Really? Then why were you both naked?}
{245}{}{Germs? I mean GERMS! Very important to be clean when doing these examinations.}
{246}{}{Well as long as yer a doctor, I guess it’s OK. You best get dressed; rumors tend to start
 because of misunderstandings like this. While you’re here, I’ve been having these pains down in my
 anus and was wondering if you could take a look at it.}
{247}{}{Err… I’ll take a look at that later. I have another patient waiting for me. Bye.}
{248}{}{Yeah. Why don’t you just come with me to get the preacher? Don’t try anything funny, or you will
 need a doctor.}

{260}{}{I knew you’d be able to handle it. Let’s see now, I owe you $1000 for completing the job. Here
 you go.}

# rape script dialog
{300}{}{What the hell is going on here?}
{301}{}{Uhhh... Sir, I was just...}
{302}{}{You keep your damn hands off of her...}

#define wedding script dialog
{400}{}{What's going on in here?}
{402}{}{Holy shit! I knew }
{452}{}{ was different, but there's only one way to make this right!}
{403}{}{How dare you sully the honor of my }
{453}{}{. There's only one way to make this right!}
{404}{}{Uh, Jo, can we just skip to the vow tying parts?}
{406}{}{Boy...}
{407}{}{Missy...}
{410}{}{Don't make me make }
{460}{}{ a widow.}
{461}{}{ a widower.}
{412}{}{Miria}
{413}{}{Davin}

{220}{}{You're not going anywhere, boy!}
{221}{}{You're not going anywhere, missy!}

# Node 4
{500}{}{Why, that's a fine looking animal you have there. Should make some fine jerky. Tell you what,
 I'll just keep some of the jerky as payment. What do you say?}
{501}{}{No way! I love Bess. Nobody is going make jerky out of her.}
{502}{}{Sounds good to me. When can I come back to pick up my jerky?}
{503}{}{Forget it, gramps. I'm outta here.}

# Node 5
{510}{}{Oh… you're one of those. Wouldn't want to take your 'friend' away from you. Nights out in the
 desert would probably be awfully lonely without her. I don't have time for this; I have work to do.}

# Node 6
{515}{}{Great! Come back in about a week. You can pick up your jerky in the smokehouse located just
 outside of the slaughterhouse. I'll leave it in a sack for you. Good doing business with you.}

# Node 50
{600}{}{Howdy }
{1600}{}{. I hope you're taking good care of my daughter, Miria. She is the light of my life and it
 would break my heart if anything were to happen to her. Where is she by the way? I was sure hoping
 to see her again.}
{601}{}{Well, if it isn't }
{1601}{}{. How's the married life treating you? I see my son Davin isn't traveling with you. I sure
 do miss him. Maybe the next time you visit you can bring him along. It sure would make an old man
 happy if he could see his only son again.}
{602}{}{Uhhh, he's dead.}
{603}{}{Uhhh, she's dead.}
{604}{}{Miria was alive when I left her, but I'm pretty sure she's dead by now.}
{605}{}{Davin was alive when I left her, but I'm pretty sure she's dead by now.}
{606}{}{Davin , uhhh, couldn't make the trip, but I'll let him know you said, "Hi," when I see him again.}
{607}{}{Miria , uhhh, couldn't make the trip but I'll send her your love when I see her again.}

# Node 51
{700}{}{Aggg... [A shocked look comes over Grisham's face as he suddenly grasps his chest and collapses to the floor.]}

# Node 52
{750}{}{Well, I have to get back to work now. I'll see you around.}

{800}{}{You have saved Grisham's brahmin.}