# 0. QUICK LOOK
{100}{}{You see Miss Kitty.}

# 0. LOOK
{150}{}{You see a stunning woman. Despite her...revealing dress, her bearing is professional and businesslike.}

# 1. FLOAT [MALE, ENCLAVE IS DESTROYED]
{200}{}{First quarter revenues are up slightly…now, if we account for the increased tribute…}
{201}{}{If I catch her taking Jet, even a *whiff,* she's out of here…}
{202}{}{Monthly physicals are coming around again…right in time for the new caravan season.}
{203}{}{Need to get some more girls for that pool party at Bishop's…}
{204}{}{Damn Macrosoft spreadsheets…}
{205}{}{Spend so much time updating these spreadsheets, I don't get any REAL work done.}
{206}{}{Jules better send some horny…and wealthy…people this way soon.}

# 2. INTRO DIALOGUE (WTG)
{215}{}{(The woman before you is stunningly beautiful. As you address her, she looks up from her work, and
 smiles.) Ah, a new face! I'm Miss Kitty…welcome to the Cat's Paw.}
{216}{}{Hello again!}
{217}{}{Why, if it isn't Reno's most famous prizefighter!}
{218}{}{I wondered when Mr. }
{1218}{}{ would send you over…(Winks.)}
{219}{}{My, my, if isn't the star of the golden screen.}
{220}{}{ What's your pleasure today, sir?}
{221}{}{ What's your pleasure today, miss?}
{222}{}{preshshure?}
{223}{}{Yuu haf prettee hair}
{224}{}{Yuu said 'pleashure' Huh-Huh-Huh-Huh-Huh}
{225}{}{George sayz we gonna haf a few achers of owr own an' I shud keep away from yuu or he won't lemme
 play wit the rabbitz so me go now}
{226}{}{Jules told me to come here if I was looking for some…action.}
{227}{}{I'm looking for some…action.}
{228}{}{Actually, I'd like to ask you some questions.}
{229}{}{You know, I've been finding magazines named "Cat's Paw" throughout the desert, and I have no
 idea what they are. I have one right here.}
{230}{}{Here's that collection of Cat's Paw magazines you asked for.}
{231}{}{Nothing today, thanks.}

# 3. RETARD ANSWER (2)
{240}{}{(The pretty lady puts the palm of her hand on your forehead.) Oh, you poor thing…you can stay in here
 for a little while to get in from the heat, but you can't be here too long, okay? Promise me now.}
{241}{}{Okayy, pretty ladee fank you}

# 4. LOOKING FOR ACTION (2, 12)
{245}{}{(Smiles and winks.) Is that so? Well, then, you've come to the right place. Whatever your pleasure or
 fantasy, we can provide it…and don't be shy, we've heard it all. So, what would you like?}
{246}{}{Well, pardon me for coming on strong, but I'd like to get to know YOU better. What time do you get off?
 Uh, work, I mean.}
{247}{}{Depends…what's on the menu?}
{248}{}{I'd like to hook up my friend here with a little something special.}
{249}{}{I'd like to hook up one of my friends here. It's their…uh, birthday.}
{250}{}{I'd like to ask you some questions…}
{251}{}{Actually, I've changed my mind. Performance anxiety and all. Goodbye.}

# 5. ASK HER OUT (4)
{255}{}{I'm flattered, but…no. I can't.}
{256}{}{Aw, c'mon. Just a drink. No pressure. We'll have a great time.}
{257}{}{Look, if you don't like women, that's fine. Hell, I don't like most women I meet. We have something in
 common already.}
{258}{}{Hey, don't worry…I won't wear the power armor, okay?}
{259}{}{All right then. I'd like to ask you some questions…}
{260}{}{Sorry, didn't mean to pressure you. Goodbye.}

# 6. ASK HER OUT (5)
{265}{}{(Looks around, then leans in and whispers.) Look… come back after
 you've done what you've had to do to save your people, and then we'll talk, okay?}
{266}{}{All right then. I had some other questions…}
{267}{}{It's a date. See you then.}

# 7. MENU (6)
{275}{}{Well…(Ticks off the menu on her fingers.)…we have honey loving, the dipstick swirl, humjobs, and various
 other exotica. (Smiles.) Question is, what are YOU in the mood for?}
{276}{}{I'd like some…oral attention.}
{277}{}{Just some basic, raunchy, low-down, dirty sex oughta do me just fine.}
{278}{}{I'd like a full upper and lower body workout.}
{279}{}{Is it okay if I just, you know, talk with them?}
{280}{}{I have a special…dramatic…request.}

# 8. & 9 BLOWJOB (7)
{290}{}{All right then. }
{291}{}{(Winks.) That'll be no charge.}
{292}{}{That'll be }
{293}{}{Done. Here's the money.}
{294}{}{Can't argue about that price. Let's do it.}
{295}{}{Nevermind. I'd like to ask you some questions…}
{296}{}{I don't have enough money…maybe another time.}

# 10. TALK (7)
{320}{}{Why, of course you can. We call it the "Kesting special." }
{322}{}{Only costs }
{323}{}{Why do you call it that?}
{325}{}{Sounds like a deal. I'll take that then.}
{326}{}{Maybe some other time. I'd like to ask you some questions…}

# 11. KESTING (10)
{335}{}{Well…rumor has it there was once an employee of a famous computer company who enjoyed talking with
 others. (Shrugs.) }
{336}{}{By coincidence, he also only made }
{1336}{}{ chips a week.}
{337}{}{By coincidence, he also made no money at all, so talking was all he could afford.}
{338}{}{Oh. Well, sign me up for the talking session then. Here's the }
{340}{}{I think I'll pass. I'd like to ask you some questions…}

# 12. QUESTIONS (2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 18, 19, 20, 21, 23, 25, 28, 29, 30)
{350}{}{Yes?}
{351}{}{Well, there's no harm in asking…}
{352}{}{All right. (Smiles.) Answers might cost you, though…}
{353}{}{Sure. What questions did you have?}
{354}{}{I heard some of your girls are chosen to go…visit Myron.}
{355}{}{Jules told me to come here for some…action.}
{361}{}{Actually, I better be going.}

# 13. MENU (7)
{375}{}{Chances are that we can accommodate you. Your request would be…?}
{376}{}{I'd like my partner to dress up in a Vault jumpsuit, call me the "Vault Dweller," and I've got to find
 their "Vault Sex-Teen."}
{377}{}{I'd like to be "captured" by some ravishing she-mutant, then be forced to take a dip in her mutating "vat."}
{378}{}{I'd like to play the role of "Herk," a nubile young slave stolen from his village by a band of lusty
 female slavers. Here's the catch…he can only communicate using his BODY.}
{379}{}{I'd like to play the role of "Zena," a nubile young slave stolen from her village by a band of
 slavers. Here's the catch…she can only communicate using her BODY.}
{380}{}{I'd like to be "captured" by a sarcastic mutant lieutenant, interrogated roughly, then dunked
 in his mutating vats.}
{381}{}{You have any girls that look like Angela Bishop? I need to work off some excitement.}
{382}{}{You have any girls that look like Mrs. Bishop? I need to work off some excitement.}
{383}{}{I'd like to ask you some questions instead…}
{384}{}{Actually, Nevermind. I've got to go.}

# 14. FRIEND LAID (4, 12)
{395}{}{Of course. (Scans your companions.) Which one?}
{396}{}{Could you take care of Lenny? I don't think he's ever even kissed a girl.}
{397}{}{You got anyone who can, uh, "handle" Marcus?}
{398}{}{This little pervert Myron here.}
{399}{}{"Bone Nose" here, if you catch my drift. Heh heh.}
{400}{}{Cassidy here. I think it's been a while.}
{401}{}{Vic. "Trader" Vic.}
{402}{}{Can one of your girls read the dictionary to Robo Brain? It stimulates his brain center.}
{403}{}{Doc's looking to take a "temperature" or two.}
{404}{}{Davin here could use…a lot…more experience.}
{405}{}{Miria wants to take a walk on the wild side.}
{406}{}{Actually, no one, thanks.}

# 15. FRIEND LAID 2 (4, 12, 14)
{420}{}{This your friend here? (Looks your companion up and down, nods.) I think we can accommodate you… }
{421}{}{(Looks your companion up and down, nods.) I think we can accommodate you… }
{422}{}{ chips.}
{423}{}{Don't worry about the money. There's no charge.}
{424}{}{Okay. Here you go.}
{425}{}{Can't argue with that price. Done.}
{426}{}{Maybe later…look, I had some other questions.}
{427}{}{Hmmm. Maybe some other time when I have enough cash.}
{428}{}{Actually, I've changed my mind. Goodbye.}

# 16. CAT'S PAW (2, 12)
{440}{}{(Looks surprised.) Let me see. (Glances at magazine.) Well, well…you know, I had heard a rumor that
 - in the pre-war years -- the Cat's Paw was a publishing house…for pornographic materials.}
{441}{}{For pornogru - porn-o-gra - pornu - uh, a publishing house, you said?}
{442}{}{This place was a publishing house?}

# 17. CAT'S PAW 2 (16)
{450}{}{Yes…the rooms here were used for film shoots with models from across the world. (Seems entranced by the magazine.)
 Quite a little piece of history you have there.}
{451}{}{Well, you know, I just read this for the articles.}
{452}{}{I'm just glad to know what the damn thing is. It's irritating to keep examining it and getting
 that same message over and over. I'll probably STILL get it even though it's identified now.}

# 18. CAT'S PAW 2 (17)
{460}{}{You know…if you can bring me a complete set…say, ten issues, I'll buy them from you. They'd be good for
 a display, might attract customers. Are you interested?}
{461}{}{If I can FIND that many...say, I had some other questions…}
{462}{}{Actually, I happen to have ten right here.}
{463}{}{Sure. If I come across that many, I'll be sure to stop by.}

# 19. CAT'S PAW, SOLVED (2, 12, 18)
{470}{}{Wonderful! I'll give you $500 for the set.}
{471}{}{$500? After collecting ALL of these? No way. Make it a thousand.}
{472}{}{Sounds good. Here you go. But hey, careful with number five…the pages look like they are glued together.}
{473}{}{No, I think I'll keep them...say, I had some other questions…}
{474}{}{No thanks, I've become attached to them. Maybe some other time.}

# 20. CAT'S PAW, SOLVED (19)
{480}{}{Hmmmmm. Seven fifty, and you got a deal.}
{481}{}{$750? All right, then. They're yours.}
{482}{}{I think I'll keep them then...say, I had some other questions…}
{483}{}{Forget it. Maybe some other time.}

# 21. CAT'S PAW, SOLVED, 750 (20)
{490}{}{Here you go. (Counts out the money, hands it to you.) Thanks again.}
{491}{}{Say, I had some other questions…}
{492}{}{Not a problem. Goodbye.}

# 22. CAT'S PAW, SOLVED 2 (19)
{500}{}{Really? (Examines No. 5, then goes through the rest of your stack.) Hmmmm. Well, it looks like you have
 two of them, so you can have this one back…but let me get the stain out first.}
{501}{}{Okay. Uh…by the way, that stain isn't mine. I have no idea how it got there.}
{502}{}{Okay. Are you sure you can get that stain out? It looks glued in there pretty tight.}

# 23. CAT'S PAW, SOLVED 3 (22)
{510}{}{Happens all the time around here…(Miss Kitty starts cleaning the magazine.)…mostly to the sheets. That
 should do it...(Holds it up.)...good issue - has an article on energy weapons, it looks like. Here you go.}
{511}{}{I had some other questions…}
{512}{}{An article on energy weapons? Thanks. I might read it later on.}

# 24. ENCLAVE VICTORY SPEECH (WTG)
{520}{}{(As you speak, she looks up, startled.) You! You came back! I…I thought you might be dead. (She looks
 relieved.) I was so *worried.* Risking your life, taking on the Enclave…that's the bravest thing I've ever heard.}
{521}{}{(As you speak, she looks up, startled.) You! I've heard about you. (Her face beams with admiration.) Risking
 your life, taking on the Enclave…that's the bravest thing I've ever heard.}
{522}{}{! I'm glad you've come back again. Just having a hero like yourself around does wonders for business:
 risking your life, taking on the Enclave…That's the bravest thing I've ever heard.}
{523}{}{Shucks, Miss Kitty. It taint nothing nobody else wouldnta done in mah place.}
{524}{}{Daaaaamn right, baby. And that's the bravest thing you're ever gonna hear, cause I'm the BADDEST of
 the bad.}
{525}{}{It was nothing that any pissed-off woman who had her village kidnapped wouldn't have done.}
{526}{}{And that's the bravest thing you're EVER gonna hear about, cause I'm the BADDEST bitch
 in the wastes.}
{527}{}{Thanks. Just doing my job as a heroine.}
{528}{}{Thanks. Just doing my job as a hero.}
{529}{}{Kicking ass and taking names, that's my job.}

# 25. ENCLAVE VICTORY SPEECH (24)
{545}{}{You are so humble. }
{546}{}{You are so strong. So…confident. }
{547}{}{I LOVE that about you. (Makes sweeping gesture at Cat's Paw.) You are always welcome here, free of charge.}
{548}{}{So…how about that date we talked about way back when?}
{549}{}{So…how about…you know, you and me…like…you know.}
{550}{}{Baby, I got to feeling like a machine, and that's no way to feel. C'mere.}
{551}{}{Great! Look, I had some questions before I indulge myself…}
{552}{}{Thanks. I appreciate it, Miss Kitty.}
{553}{}{I expect nothing less. I'll collect later.}

# 26. ENCLAVE VICTORY SPEECH (25)
{565}{}{All right then, }
{566}{}{…let me just get my coat.}
{567}{}{No rush. Take your time.}
{568}{}{Good thing I've got my "coat" in my pocket. Heh-heh.}
{569}{}{Sure. But hurry up…we've got reservations at eight. In my PANTS.}
{570}{}{Sure. But hurry up…you and my tongue got reservations at eight.}

# 27. MACHINE (25)
{575}{}{Oh, }
{576}{}{, you Enclave-smashing animal…}
{577}{}{::Bwanbwan-bwan-ba-bwan oookwaka oookwaka::}

# 28. MYRON (12)
{585}{}{(Nods.) Yes, that's correct. We usually have to train them extensively to suppress their natural
 revulsion. It's almost a rite of passage now. Still, if a girl can abide Myron, it means she's tough…}
{586}{}{I'd like to meet him. Think I could volunteer to be his next "choice?"}
{587}{}{I see. I had some other questions…}
{588}{}{Hmmmm. Thanks for the information.}

# 29. EVALUATE (28)
{595}{}{(Studies you, then makes a circling gesture with her finger.) Turn around for me. Hmmmm… }
{596}{}{no, I don't think you'd make the cut. Maybe if you cleaned yourself up a little more, made
 yourself…presentable. Sorry.}
{597}{}{yes… yes, I think you'd do just fine. Are you interested in the job? All of my other girls
 are…sick of it.}
{598}{}{Sure.}
{599}{}{Hmmmph. I had some other questions…}
{600}{}{No, but I may ask again later. I had some other questions…}

# 30. EVALUATE (29)
{610}{}{(Nods.) Excellent. One of the Mordino lieutenants should be showing up soon. If you want to take a
 seat, I'll present you as one of the…applicants.}
{611}{}{All right…I'll wait for him.}
{612}{}{Actually, forget it. I had some other questions…}
{613}{}{Nevermind…I've changed my mind. Maybe some other time.}

# 31. STRANGE REQUEST (4, 12, 13, 14)
{620}{}{(Looks you up and down, then nods.) I think we can accommodate you… }
{621}{}{(Looks your companion up and down, then nods.) I think we can accommodate your friend… }
{623}{}{(Winks.) There's no charge, so don't sweat the money.}

# sex responses
{700}{}{Oooooh-yeah.}
{701}{}{Shag-a-riffic.}
{702}{}{Wow. That was deep.}
{703}{}{Wow.}
{704}{}{*Whew*}
# marcus
{705}{}{I sure hope I didn't get her pregnant.}

{710}{}{You talk for hours. The girls at the Cat's Paw have amazing insight into human nature.}
{711}{}{The Mordino lieutenant arrives, and seems impressed with you. He leads you north out of
 town to someplace called the "Stables."}

# party applause
# general
{720}{}{*whistles*}
{721}{}{*clap clap clap*}
{722}{}{Way to go!}
{723}{}{Wahoo.}
# spouse
{730}{}{*sob sob sob*}
{731}{}{I feel so... so cheated...}
# goris
{740}{}{*Grunt*}
# cyberdog
{750}{}{*Aaawoooo*}
# robobrain
{760}{}{*Bzzzt*}
# vic
{770}{}{Way to go, Boss! Ain't had sex myself in a loooooong time.}

{800}{}{You delivered the Cat's Paw magazines to Miss Kitty.}