# 0. QUICK LOOK (WTG)
{100}{}{You see Coffin Willie.}

# 0. LOOK (WTG)
{150}{}{You see an old, stinky, crusty ghoul. And boy, does he SMELL.}

# 1. DIG UP (WTG)
{200}{}{Whoa. This grave SMELLS.}
{201}{}{Oh, well…better keep digging.}
{202}{}{What th-?}
{203}{}{About friggin' time! Could you dig any SLOWER, idjit?}
{204}{}{Outta my way, smoothie.}
# lenny in party
{205}{}{D'dad?}
{206}{}{Not now, Lenny, I ain't in th' mood to be talkin'.}

# 2. CLICK/FLOAT (WTG)
{300}{}{Jest pop inta Reno fer a lil' drinking n' whoring, n' damned smoothies jam me inna goddamn grave…}
{301}{}{Good thing I ain't got no nose, or I woulda choked on my own stink.}
{302}{}{Ghouls don't get no damn r'spect.}
{303}{}{Just stopped in the city for a drink, n' those Reno assholes bury me alive.}
{304}{}{Nothing more boring than bein' in a coffin for months.}
{305}{}{Hands off, smoothie. I got places to go.}
{306}{}{Get your smoothie mitts offa me, smoothie.}

# HEADSTONE
{500}{}{The headstone reads: "Here lies the dumbest son of a bitch ever to set foot in New Reno."}

{550}{}{There's a horrible odor flowing from the grave.}

{600}{}{Hey!}
{601}{}{I ken hear someome movin' round out there!}
{602}{}{Don't step onna grave! It packs the dirt in!}
{603}{}{Quick, GET A SHOVEL!}
{604}{}{Would somebody dig me up already? I need a drink!}
{605}{}{That a worm I feel? Oh...nevermind.}