{100}{}{You see a somewhat plump, blonde secretary in a tight dress.}
{101}{}{You see the President's *personal* private secretary.}
{102}{}{You see a plump but not unattractive intern, uh, secretary. Her hair is a little mussed.}
{103}{}{Yeah? Whatcha want, honey?}
{104}{}{Not again, I just cleaned my dress.}
{105}{}{So what's Mr. Important up to?}
{106}{}{They don't call him *Dick* Richardson for nuthin'}
{107}{}{I do too know how to type.}
{108}{}{You oughta knock before barging in like that.}
{109}{}{I need some mouthwash.}
{110}{}{Where's that washcloth?}
{111}{}{I think it's time for a raise.}
{112}{}{Do those Secret Service agents always have to hover like that?}
{113}{}{Come back later. I'm gonna be busy in a minute here.}
{114}{}{I don't think I'll wash this dress - it might come in handy.}
{115}{}{The President says I kiss the best.}
{116}{}{You're not taping me, are you?}
{117}{}{Where are my kneepads? Heh, heh, just kidding.}