{100}{}{You see a plain-looking young man in respectable clothing.}
{101}{}{It's the building receptionist.}
{102}{}{There's nothing partiuclarly exceptional about the guy. He looks like the epitome of a budding bureaucrat.}
{103}{}{Welcome to Congress House. How can I help you?}
{104}{}{Back again, I see. How can I help you this time?}
{105}{}{Now, what can I do for you?}
{106}{}{Uhhh...}
{107}{}{Me see Tandi?}
{108}{}{Me see Tandi?}
{109}{}{I'm here to see President Tandi.}
{110}{}{Can you help me find Vault 13?}
{111}{}{Not unless you've got a GECK.}
{112}{}{I've got some important news for your boss.}
{113}{}{I'm here to see President Tandi.}
{114}{}{I'm here to see President Tandi.}
{115}{}{I'm looking for a job.}
{116}{}{What is this place?}
{117}{}{You can't.}
{118}{}{Me go away.}
{119}{}{Sorry, no public bathrooms here. Why don't you move along?}
{120}{}{Concerning?}
{121}{}{Hmmm... Why do you want see Madam President?}
{122}{}{Man say Tandi hire me.}
{123}{}{Little town in desert want make friends with Tandi.}
{124}{}{I heard your president's got a job to be done.}
{125}{}{The folks at Vault 15 want to make a deal.}
{126}{}{}
{127}{}{Such as?}
{128}{}{Someone's been selling her out.}
{129}{}{It's none of your business.}
{130}{}{That's nice. This isn't a hiring hall. Why don't you try downtown?}
{131}{}{This is the Congress House, law-making body for NCR.}
{132}{}{(Continue)}
{133}{}{13? Or did you mean 15?}
{134}{}{I said 13.}
{135}{}{15?}
{136}{}{No.}
{137}{}{(Continue)}
{138}{}{Oh, that. Talk to Mr. Gunther, in back.}
{139}{}{Vault 15? They want to make a deal? Interesting. In the back - talk to Gunther.}
{140}{}{You can tell her yourself. Just go and talk to Gunther.}
{141}{}{That doesn't sound good. Now excuse me, I have work to do.}
{142}{}{I have to tell her something.}
{143}{}{Fine. Tell her there's a spy in her office.}
{144}{}{You just tell her I want to see her. Understand?}
{145}{}{Well then, I can't help you with that.}
{146}{}{(Continue)}
{147}{}{Oh, nothing. My mistake. You said 13, right? Well, I don't know anything about that.}
{148}{}{(Continue)}

{149}{}{Me fix problem. Kill bad guy. Want money.}
{150}{}{Tell her I solved her squatter problem.}
{151}{}{Darion's dead? Oh, excuse me. Go right on in.}
{152}{}{You did? Well...I'm sure that's wonderful news. Did you learn anything else?}
{153}{}{No}
{154}{}{Yeah, there's something else -- something about a spy.}
{155}{}{What a rel-I mean, I'm glad it's all over. Go right on in.}

#messages for when the player is tampering with somthing he shouldn't
{500}{}{Excuse me, but you cannot enter there without permission.}
{501}{}{I have to ask you to stop tampering with that.}
{502}{}{This is your last warning - leave or be dealt with.}
{503}{}{Security, please remove our "guest".}