{100}{}{You see a big, dumb-looking and over-muscled lunk.}
{101}{}{It's Hoss}
{102}{}{He doesn't appear to be armed, with weapons or wit.}
{103}{}{Hey you, turd-face. I don't like you. I think you should buy me a drink.}
{104}{}{Hey baby, come on over here and I'll give you a nice big wet one.}
{105}{}{<Fart!>}
{106}{}{Bite me.}
{107}{}{I don't want any trouble.}
{108}{}{So you think you're tough? I'm gonna wipe your ass all over the floor. Bare fists, right here, right now.}
{109}{}{"I don't want any trouble!" Well, you're gonna have it. You either fight me or I'm gonna tell everybody what a spineless little baby you are. Bare fists, right here.}
{110}{}{Fine, let's dance.}
{111}{}{No really, I couldn't.}
{112}{}{Haw! What a joke. Get outta here, jellyfish.}
{113}{}{Ow! You broke my nose! I quit! Don't hit me anymore!}
{114}{}{Okay, I'm sorry. I was only joking. You won't have any more trouble from me...please, don't kill me!}
{115}{}{Hey, I'm backing off. Okay, don't hit me?}
