{100}{}{Looks like yet another barfly.}
{101}{}{Same drunk you saw last time.}
{102}{}{Doesn't look like the nicest of people, but with that much booze, who does?}
{103}{}{Look, I'm just drinking. Leave me alone.}
{104}{}{I don't talk to strangers. Bad for your health in this bar.}
{105}{}{I've heard about you. Damn, but aren't you in the wrong place!}
{106}{}{You want trouble? Go talk to Merk.}
{107}{}{Hey, good-looking, you want to go some place private and have a little fun?}
{108}{}{Don't talk to me! I don't want another beating.}
{109}{}{Damn cheap whiskey! You know, they serve the worst liquor here.}
{110}{}{Shit! I didn't mean to spill my drink on you. Let me clean that up. Sorry, sorry.}
{111}{}{Stay away from me!}
{112}{}{I've heard about you. Please don't hit me.}
{113}{}{New in town? Word is Merk's looking for some tough hombres.}
{114}{}{What are you, some kind of tough guy? Get outta my face!}
{115}{}{They shouldn't never have done that. Someday stranger, I'll have a gun and then I'll show 'em.}
{116}{}{How'd you like to be my love slave, pretty?}
{117}{}{Drinking and talking - hell, nothing exciting ever happens in this town.}
{118}{}{Go away, you're bothering me.}
{119}{}{Did you hear the one about...}
{120}{}{So I says to him, "Look," I says...}
{121}{}{Try the roasted mole-rat. It's the best around.}
{122}{}{Hi. What's your sign?}
{123}{}{If you're looking for work, stranger, go down to the Stockmen's.}
{124}{}{Shit! Did you see that?}
{125}{}{Oh man, I'm going to be sick.}
{126}{}{No more for me.}
{127}{}{Hey, mix me one of those!}
{128}{}{I had a Rad-a-Waster like that once...}