{100}{}{You see an active computer terminal.}
{101}{}{Looking closely at the terminal you notice sign stating "I*tel Inside".}
{102}{}{You are unable to read what is on the monitor.}

#NPC is unable to read what is on the monitor
{200}{}{ is unable to read what is on the monitor.}

{103}{}{Main Power = Offline                      
                       Backup power = Online
                                             Reinitiating Security Program    
                                  Warning - Low Power - Force Fields at 50%
                      Finished loading...
                                                  Skynet Security Check Point 1
                               Please Enter Password:_}
{104}{}{Skynet Security Check Point 1
                             Please Enter Password:_}
{105}{}{Tchaikovsky}
{106}{}{Open Says Me}
{107}{}{Sierra}
{108}{}{Armageddon}
{109}{}{Hack into security systems}
{110}{}{You don't have a clue. Exit.}
{113}{}{Force Fields Disabled - Level 1}
{115}{}{Exit}
{117}{}{Access to this terminal has been terminated.}
{119}{}{Exit}
{121}{}{Error 29
                                                            Unable to contact server
                                     Please reboot}
{123}{}{Exit}
{124}{}{Access Granted
                                                 Force Fields Level 1: Deactivated}
{125}{}{Exit}
{126}{}{Invalid Password
                                                      Access Denied
                                                      Please enter Password:_}
{127}{}{Tchaikovsky}
{128}{}{Open Says Me}
{129}{}{Sierra}
{130}{}{Armageddon}
{131}{}{Hack into Security Systems}
{132}{}{You don't have a clue. Exit.}
{133}{}{[Pressing <Ctrl><Alt><C> causes the program to crash. You hope the rest of the security measures are this easy to defeat.]}
{134}{}{Exit.}
{135}{}{Security Breach Level 1
                                   Activating Security Protocol
                                   User access to this terminal is terminated
                      End Transmission}
{136}{}{Exit}
{137}{}{Your ineptness has caused you to set off the alarm system.}
{138}{}{It's no use, the program is just too complicated for you to understand.}
{139}{}{Exit}

{300}{}{The computer seems to have some sort of defense mechanism.}
{301}{}{You are shocked for }
{302}{}{ is shocked for }
{303}{}{ points of damage.}