{100}{}{Ves a un jugador.}
{101}{}{A este jugador le está yendo extremadamente bien.}
{102}{}{Parece que está ganando, pero todo su dinero está sobre la mesa.}
{103}{}{Parece que está ganando, pero todo su dinero está sobre la mesa.}
{104}{}{Esta persona no parece estar ganando ni perdiendo.}
{105}{}{Esta persona hace tiempo que no gana.}
{106}{}{Parece que está a punto de echarse a llorar y de quedarse sin dinero.}
{107}{}{Parece estar muy enfadado y estar perdiendo mucho dinero.}
{200}{}{¡No me hagas daño!}
{201}{}{¡No dispares!}
{202}{}{¡No tengo dinero!}
{203}{}{¿Por qué has tenido que matar a la pobre Becky?}
{204}{}{¿Qué es lo que te hizo ella?}
{205}{}{¡No he hecho nada!}
{206}{}{Por favor, vete, no lo contaré a nadie.}
{300}{}{¡Sí! ¡Los dados me quieren!}
{301}{}{Oh, eso ha estado cerca.}
{302}{}{No me interrumpas. Vas a arruinar mi racha.}
{303}{}{¡Estoy en racha!}
{304}{}{¡Dinero, dinero, dinero!}
{305}{}{¡Adoro este juego!}
{306}{}{¿Lo has visto? ¡Sí!}
{307}{}{¡La ruleta es el mejor juego!}
{308}{}{Me está yendo bastante bien, ¿qué tal a ti?}
{309}{}{Me está yendo mejor de lo normal.}
{310}{}{Un gran sitio, ¿no crees?}
{311}{}{Las mesas de Becky son mejores que las de Nuevo Reno.}
{312}{}{¿Te gusta este juego? Es muy divertido.}
{313}{}{No he tenido una buena tirada desde hace un buen rato.}
{314}{}{Necesito una buena tirada.}
{315}{}{Bueno, al menos no estoy perdiendo.}
{316}{}{No me voy a ningún lado.}
{317}{}{Estoy en punto muerto.}
{318}{}{Tienes que jugar a los números.}
{319}{}{Apostar sólo al rojo o al negro no da ganancias.}
{320}{}{Los dados no se están portando.}
{321}{}{Estoy deprimido y esto no pinta bien.}
{322}{}{Espero que lo hagas mejor que yo.}
{323}{}{He tenido días mejores.}
{324}{}{Sé como jugar, honestamente.}
{325}{}{La suerte no está de cara hoy.}
{326}{}{Otro día de paga perdido para nada.}
{327}{}{¡Estoy casi arruinado!}
{328}{}{Maldición. Esto apesta.}
{329}{}{¿Por qué siempre tiene que pasarme esto a mí?}
{330}{}{No puedo ganar.}
{331}{}{Odio este juego.}
{400}{}{Maldición, ¡el de Becky era el único casino para apostar de la zona!}
{401}{}{Aléjate.}
{402}{}{¡No dispares!}
{403}{}{Por favor, déjanos en paz.}
{500}{}{No te pares aquí.}
{501}{}{Sigue moviéndote.}
{502}{}{¡VAMOS, 7!}
{503}{}{¡Sí!}
{504}{}{¡No pares!}
{505}{}{¡Becky! ¡Hoy voy a llevarme todo tu dinero!}
{506}{}{¡Woohoo! ¡He ganado!}
{507}{}{¡Dame otro buen rebote!}
{508}{}{¡Sí!}
{509}{}{¡Muy bien!}
{510}{}{Otra vez, vamos a verlo otra vez.}
{511}{}{Vamos.}
{512}{}{Es lo que quería.}
{513}{}{Casi.}
{514}{}{No está mal.}
{515}{}{¿Cómo ha podido pasar eso?}
{516}{}{Ups.}
{517}{}{Sin golpes, sin golpes. ¡Para!}
{518}{}{Bueno, el juego hace honor a su nombre.}
{519}{}{Tan sólo necesito ganar una grande.}
{520}{}{¡Cifras!}
{521}{}{¿Otra vez?}
{522}{}{Esto no pinta bien.}
{523}{}{¡La ruleta apesta!}
{524}{}{¡Becky! ¡Tus mesas me están matando!}
{525}{}{¿Estos dados están cargados o qué?}
{526}{}{¡Otra vez no!}
{527}{}{¿Por qué yo?}
{528}{}{¡Maldición! ¡Estaba tan cerca!}
{529}{}{Oh Dios, Dios, Jesús, ¡MÁTAME!}
{530}{}{¡Odio este juego!}
{531}{}{¡Maldición! ¡Ese era mi número en la última tirada!}
{532}{}{¿¿¿Otra vez negro!?!?}
{600}{}{¡Vete!}
{601}{}{¿Por qué has hecho eso?}
{602}{}{¡Vete!}
{603}{}{Detente, soy frágil.}
{604}{}{Yo no te haría algo así a ti.}
