{100}{}{Ves a un ermitaño.}
{101}{}{Ves a un ermitaño.}
{102}{}{Parece que no se haya lavado desde hace años.}
{103}{}{¿Tu adivinas porque soy ermitaño? [Parece que no haya hablado con nadie en años].}
{104}{}{¿Por qué?}
{105}{}{Sólo pasaba por aquí.}
{106}{}{Uhg.}
{107}{}{Quiero estar sólo.}
{108}{}{Dado que estoy aquí, quizá podamos hacer un trueque. Estoy seguro de que tengo alguna cosas que puedas querer.}
{109}{}{Entonces te dejaré solo.}
{110}{}{Comerciar. Después te dejo ir.}
{111}{}{De acuerdo, esto es lo que tengo para comerciar.}
{112}{}{Mejor me voy.}
{113}{}{Marcho ahora.}
{114}{}{Voy a irme ahora.}
{115}{}{Hmm... Me gustas. No aburro hablando. Quédate y comerciamos tú y yo.}
{116}{}{K'}
{117}{}{Yo ir.}
{118}{}{Buena charla. Ahora tú marchas. Estoy cansado.}
{119}{}{[FIN]}
{120}{}{Hablar me hace dolor de cabeza. Marcho.}
{121}{}{Hecho, yo hablo a tú.}
{122}{}{No hablar. Marcho.}
{123}{}{¡Vete!}
{124}{}{¡Déjame!}
{125}{}{¡Cómo te atreves a atacarme!}
{126}{}{Déjame en paz.}
{127}{}{Yo marcho.}
