{100}{}{Ves a un grupo de extraños bien armados.}
{101}{}{Siguen siendo un grupo de extraños bien armados.}
{102}{}{Portan armas limpias y bien brillantes y llevan una especie de placa en el pecho.}
{103}{}{Estamos buscando patrullas de esclavistas. ¿Has visto alguna, forastero?}
{104}{}{Saludos, forastero. Espero que no seas un esclavista... por tu propio bien.}
{105}{}{Me alegro de verte, forastero. No nos molestes y no habrá problemas.}
{106}{}{Somos los Rangers de la RNC. Hacemos del mundo un lugar mejor. Pensé que te gustaría saberlo.}
{107}{}{Somos Rangers. Matar esclavistas es lo nuestro.}
{108}{}{Maldito esclavista. ¡Vas a morir!}
{109}{}{Mierda... ¡te lo advertí!}
{110}{}{No necesitamos a los de tu clase por aquí... muere.}
{111}{}{Siempre las pistolitas... ¿Es qué nadie puede rendirse sin más?}
{112}{}{Bien, eso es... ¡comienza la temporada de caza!}
{113}{}{Oh... conseguiré refuerzos. ¡No te muevas!}
{114}{}{"Podemos con ellos" dijo. Claro…}
{115}{}{¡Au-au-au-au-au!}
{116}{}{¡Mierda! ¡Me largo de aquí!}
{117}{}{¡No pienso morir por esto!}
{118}{}{Veo que tienes un tatuaje ahí... la marca de los esclavistas. No serás un esclavista, ¿no?}
{119}{}{Sí.}
{120}{}{No.}
{121}{}{Qué mala suerte... para ti. Somos los Rangers de la RNC. ¿Has oído hablar de nosotros? Matamos esclavistas.}
{122}{}{Eres un mentiroso de mierda. ¡A por él!}
{123}{}{Saludos, forastero. Somos los Rangers de la RNC. ¿Quién eres tú?}
{124}{}{No es asunto tuyo.}
{125}{}{Sí, he oído hablar de ti. Eres un Ranger, ¿no?}
{126}{}{Sí.}
{127}{}{No es asunto tuyo.}
{128}{}{Bien, sé todo lo antisocial que quieras. Al menos no eres un esclavista. Adiós.}
{129}{}{Encantado de conocerte, camarada. Ten cuidado. Nos vemos.}
