{150}{}{Vete de nuestra tierra.}
{151}{}{Has entrado sin permiso.}
{152}{}{Esta es nuestra tierra.}
{153}{}{Que los espíritus del cielo se te meen encima.}
{154}{}{Que los espíritus de la tierra se te traguen.}
{155}{}{Que los espíritus del viento soplen una peste horrible en tu dirección.}
{156}{}{Los espíritus del agua te abandonan.}
{157}{}{Los grandes espíritus del fuego te maldicen.}
