{100}{}{Ves un Holograma.}
{101}{}{Tú ves al Director de Seguridad.}
{102}{}{Holograma 10001. Él supervisa la seguridad de la APA.}
{200}{}{¡Detener! No intentes acercarte más. Identifícate, intruso.}
{201}{}{Soy el Elegido de Arroyo. Estoy explorando la APA.}
{202}{}{No soy un intruso y ahora necesito irme.}
{203}{}{Soy }
{204}{}{y no estoy tratando de entrometerme, solo estoy explorando.}
{210}{}{¿¡Explorador!? ¿Explorando ... MI ... APA? ¿Cómo te atreves a tener la audacia de entrar aquí y pasear casualmente? ¡Vollidiot! Tengo muchas ganas de arrestarte y arrojarte el culo al zoológico de mascotas ¡darles un verdadero festín a los monstruos!}
{211}{}{¡No, espera! ¡No te estoy haciendo daño! Dejame explicar...}
{220}{}{No vas a ir a ningún lado rápido, Pisskopf. Nadie entra en MÍ APA sin explicarse. ¿Cómo sé que no eres un espía chino?}
{221}{}{Supongo que no. Pero si me das la oportunidad de explicarme, estoy seguro de que podemos solucionar todo este desastre.}
{222}{}{¿Y qué si soy yo? ¿Incluso importa? Su preciosa APA ya no es exactamente relevante. Es solo otra reliquia en descomposición de una edad perdida.}
{230}{}{Continúa entonces, Schwachkopf, explícate. Sin embargo, hazlo bien, ¡o haré que los robots te golpeen y te arrastren a la silla eléctrica!}
{231}{}{Bien. En primer lugar, no soy un espía chino, soy lo que podrías llamar un tribal. He sido elegido para embarcarme en una peligrosa búsqueda para salvar a mi tribu de la destrucción. Solo entré en este complejo con la esperanza de buscar algo que pudiera ayudarme en mi búsqueda.}
{232}{}{Que te den por culo. En serio, eres un * holograma *. Lo peor que puedes hacer es tratar de gritarme hasta la muerte, que parece que estás dando tu mejor tiro. En cuanto a esos montones de chatarra que llaman robots, podría estar un poco más intimidado si viera alguno por aquí que realmente funcione.}
{240}{}{¡Hurgar! Usted Pissnelke! ¿Cómo te atreves a desacreditar el nombre de la APA de esta manera? ¡Nadie quita un pedazo de papel de este edificio sin que yo lo diga! Sin embargo, haber ingresado tan lejos en la APA requeriría algo de habilidad ... tal vez podría encontrar un uso para usted después de todo.}
{241}{}{¿Eh?}
{242}{}{No, creo que buscaré algo más y me iré. ¡Adiós!}
{250}{}{¡Insolencia! ¡Qué insolencia de un Blödes Arschloch! Cuando comencé mi entrenamiento, la insolencia debía ser castigada. ¡Y castigados estábamos! Marca mis palabras scheisskopf, esa lengua bífida tuya algún día será tu muerte.}
{251}{}{Tal vez lo hará, tal vez lo hará. Y si ese día llegara, lo trataré allí mismo. Lo cierto es que no vendrá de ti. Eres un don nadie. No tiene nada más que gobernar, por eso cubre su tristeza con ira. ¿Cuánto tiempo han fallado los robots para responderte?}
{260}{}{Bueno, como ya habrás adivinado, los robots ya no funcionan aquí en la APA. Las consolas de la computadora ya no registran mis comandos verbales y no tengo un cuerpo para activar la consola. Yo ... no puedo asegurar nada adecuadamente. ¿Podrías arreglarme la computadora de control del robot? Necesito la habilidad de mandar a los robots para ... bueno, para cosas.}
{261}{}{Bien, ¿por qué no? Veré lo que puedo hacer.}
{262}{}{No, ahora no tengo tiempo. Adiós.}
{270}{}{Fick dich du verdammter Arschficker! Debería ... a ... [Suspira.] Tienes razón. Los robots ya no pueden entender lo que digo. ¡Se sientan allí inmóviles como malditos bolígrafos! Las computadoras han dejado de funcionar y, como holograma, no puedo tocar los teclados. Como he estado diciendo durante muchos años, todo este lugar necesita nivelación y reconstrucción. Tal vez algún día tenga el poder de hacer eso.}
{271}{}{¿Quizás podría ayudarte de alguna manera? Soy bastante bueno con las computadoras.}
{280}{}{Gracias. Si puede reparar la computadora de control del robot, le otorgaré acceso completo al ala de seguridad en el nivel rojo. Puedes tomar lo que quieras de las tiendas. Me temo que no tenemos uso para ellos ahora de todos modos.}
{281}{}{Gracias. Volveré cuando haya terminado.}
{290}{}{!Lech mich! No tengo nada más que decirte.}
{291}{}{Bien.}
{300}{}{¿Ya has logrado completar la tarea? * Los ojos brillan expectantes *}
{301}{}{No, aún no. Voy a seguir trabajando en ello.}
{310}{}{¿Ya están en línea las computadoras?}
{311}{}{Si. Los he reparado para ti. Puedes comandar los robots nuevamente.}
{320}{}{¡Excelente! ¡Brillante! ¡Puedo aplastar a esos tontos ahora! ¡La APA será limpiada una vez más! Muy bien, ahora tengo algo para ti. [Hablando con los robots] ¡Pon tu culo de metal en marcha y ven a darle a esta civilización una recompensa por servir a esta gran nación! [Un robot rueda hacia ti y te muestra una tarjeta. Una vez que tomas la tarjeta, la ves salir de la habitación. De alguna manera, tienes la impresión de que estos robots habrían sido más felices si los hubieras dejado inactivos.] Sigue tu camino ahora. Usted está despedido.}
{321}{}{Gracias.}
{322}{}{¿Despedido? ¿Qué soy yo, un guardia? Más tarde, viejo temporizador.}
{330}{}{¡Déjame!}
{331}{}{No quiero tener nada más que ver contigo.}
{332}{}{HAZLO TU MISMO!!!}
{333}{}{Ahora mismo estoy ocupado.}
{334}{}{Vuelve más tarde.}
{335}{}{¿No ves que estoy en la conferencia?}
{336}{}{¡Debemos destruir este lugar inmediatamente!}
{337}{}{¡Eso es absurdo!}
{338}{}{¡Nunca!}
{339}{}{Solo con la destrucción de lo viejo puede renacer lo nuevo.}
{340}{}{¿Todos a favor?}
{341}{}{¡Los robots deben ser reactivados!}
{342}{}{¡Débiles! ¡Todos ustedes!}
{343}{}{¡Nuestras defensas de armas necesitan urgentemente municiones!}
{344}{}{¡Si yo estuviera a cargo, las cosas realmente se harían por aquí!}
{345}{}{¡Callate!}
{400}{}{¿Arrestarme? Eres un holograma Ni siquiera puedes tocarme.}
{401}{}{Ya veo, ¡estoy lidiando con un maldito as inteligente aquí! ¿De verdad crees que no puedo vencer a una gallina como tú? Bueno, tal vez no pueda, ¡pero los malditos robots están aquí! Perderé la paciencia pronto. Comienzan a explicar mejor sus intenciones. ¿Cómo debo saber que no eres un espía chino?}
{410}{}{¿Eres tú quien volvió a conectar la computadora de control del robot?}
{411}{}{Así es.}
{412}{}{Eh... quizás.}
{413}{}{No. No era yo}
{420}{}{¡Nueces! Eres la única criatura de carne y hueso aquí, así que sé muy bien que eras tú.}
{421}{}{De acuerdo, bien, fui yo.}
