{100}{}{Eso es todo... creo.}
{101}{}{No, pero no puede... yo, bueno... hmmm...}
{102}{}{El cable azul a la vivienda roja...}
{103}{}{Estas mutaciones están progresando muy bien.}
{104}{}{No pasará mucho tiempo ahora.}
{105}{}{Sólo unas pocas gotas de HCl...}
{106}{}{Ves a un hombre en un traje de laboratorio.}
{107}{}{Vea El Médico.}
{108}{}{El principal - y único - Médico de la izquierda en la EPA.}
{109}{}{Sería imprudente ataque de mí.}
{120}{}{¿Sí?}
{121}{}{Hola, mi nombre es }
{122}{}{. ¿Quién eres?}
{123}{}{Perdona que te haya molestado. Adiós.}
{130}{}{Yo soy conocido como el Doctor.}
{131}{}{Oh, a la derecha. Entonces, ¿qué hacemos? ¿Por qué está usted aquí todo por tu cuenta? El resto del lugar parece desierto.}
{132}{}{De acuerdo, gracias.}
{140}{}{Veo que usted está adecuadamente cualificado en los caminos de la ciencia. Tal vez usted podría entender lo que yo hago aquí, después de todo. ¿Qué desea saber?}
{141}{}{¿Por qué estás aquí?}
{142}{}{¿Qué haces aquí?}
{150}{}{Lo siento, pero yo no creo que usted tiene las habilidades necesarias para entender lo que estoy haciendo aquí. Vuelve cuando estés mentalmente más fuerte.}
{151}{}{Whoa, sólo un minuto. Voy a ir a por cualquier cosa que me das!}
{152}{}{De acuerdo entonces. Adiós.}
{160}{}{Yo era parte del equipo de científicos que trabajó aquí en la EPA antes de la guerra. Por desgracia, ninguno de ellos era lo suficientemente hábil en las disciplinas científicas o poseía suficiente resolver y tuvo que abandonar. Ahora, yo soy el único que queda.}
{161}{}{Así que, ¿estás feliz con eso? Me refiero a que, siendo el único aquí?}
{170}{}{Nada quiero de verdad. Por el momento, me voy a llevar a cabo más investigación sobre genética de las criaturas que he creado con el fin de observar los efectos de la FEV en sus sistemas inmunológicos. Años atrás, he creado muchos nuevos medicamentos y adaptado varios otros, pero yo ya no lo hacen.}
{171}{}{Lo que acerca de las criaturas que ha creado?}
{172}{}{¿Qué tipos de medicamentos ha hecho?}
{180}{}{No, No puedes. Usted simplemente no son lo suficientemente capacitado en las maneras de ciencias biológicas y de mejoras. Ahora, si me disculpáis, estás perdiendo mi tiempo.}
{181}{}{Yo, ciertamente, no lo soy. Trate de mí.}
{190}{}{<sonrisas> Bueno, tal vez sea así. OK, si quieres, te voy a dar una oportunidad. ¿Qué te gustaría saber?}
{191}{}{¿Por qué estás aquí?}
{192}{}{¿Qué haces aquí?}
{200}{}{Por qué, por supuesto! Nadie to watch over me. Sin reglas de ningún tipo. Hago lo que quiero, cuando quiero. También, con sólo me dejó aquí, tengo acceso a todo el equipo que necesita. Cualquier otra cosa?}
{201}{}{¿Quiénes son las personas de allí, en esas jaulas?}
{202}{}{¿Qué es todo este divertido líquido de color que he visto alrededor de la EPA?}
{203}{}{De donde sacas todo el equipo de?}
{210}{}{Las primeras células encima de ese muro son algunos de los aldeanos que se paseaban por aquí por error y he capturado para su posterior uso en. El otro más fuerte de aspecto son mis propios guerreros para... situaciones de emergencia.}
{211}{}{...para su uso posterior? ¿A qué te refieres?}
{212}{}{Gracias. ¿Puedo preguntarte otra cosa?}
{213}{}{A la derecha. Gracias. Debo irme ahora.}
{220}{}{Productos químicos y tanques de FEV en su mayoría. Todo estaba contenida en grandes barriles de almacenamiento seguro aquí en la EPA. Desafortunadamente, no fue un accidente menor y una enorme fuga de productos químicos obligó a todos, excepto a aquellos daft hologramas para salir. Algunos de los productos químicos se han filtrado en los niveles inferiores. Yo estoy usando ahora es como en la experimentación de materiales. Hasta ahora, se proporcionan algunos resultados prometedores!}
{221}{}{Qué tipos de resultados? ¿Quieres decir que te has creado estas criaturas?}
{222}{}{Así que ¿de dónde sacas todo su equipo, que desde?}
{230}{}{Aquí en su mayoría. La EPA fue originalmente diseñado y amueblado con todo tipo de maquinaria y, dado que todos los otros científicos de la izquierda, ninguno de los que se ha utilizado alguna vez. Yo soy sólo se ejecuta fuera de un par de cosas ahora, después de tantos años...}
{231}{}{No importa. Debo irme ahora.}
{240}{}{Drogas? Docenas! A través de los años he creado mentats, buffout, estimulantes, botiquines médicos de diferentes puntos fuertes, psicópatas y muchos otros que no entienden. Yo ya no lo hacen, sin embargo. He creado el Señor Chemmie! robot a hacer eso por mí. Es en el complejo principal. Si usted tiene la inteligencia y las habilidades científicas que decir tiene, a continuación, siéntase libre de usar para hacer cualquier medicamento que usted desea.}
{241}{}{¿Qué clase de drogas especiales has creado?}
{242}{}{Donde puedo encontrar el Señor Chemmie!?}
{243}{}{Gracias. Decirme, ¿alguna vez has oído hablar de jet?}
{250}{}{Sí, he creado muchas criaturas mientras he estado en el de la EPA. Si eres una exploración de tipo, entonces usted puede venir a través de algunos de ellos en los desechos. Los centauros? Las moscas volantes? Los "Extranjeros"? Ellos vagan libremente por ahora en los desechos. Sólo he conservado algunos aquí y en la principal base para la futura referencia.}
{251}{}{Sólo un minuto. ¿Me estás diciendo que todas esas criaturas que hay, de esas cosas que están plagando la tierra y matando a inocentes fueron creados por usted?!}
{252}{}{Whoa, nota a sí mismo: no ira al Doctor. Adiós.}
{260}{}{'¿Qué quiero decir?' El Virus de Evolución Forzada, por supuesto! Estoy apenas comenzando a experimentar los efectos en los seres humanos. Todos hemos oído la historia de la Maestra. Yo estaba pensando en hacer algo similar a mí mismo. Un ejército de mi propio sería, sin duda, muy útil!}
{261}{}{No crees que es un poco inmoral? ¿Cómo se puede siquiera considerar que la horrible cosa?}
{262}{}{Acaba de llegar en torno a los seres humanos? Qué más has trabajado en ese entonces?}
{263}{}{Bien, buena suerte con eso. Debo irme ahora.}
{270}{}{Sí, supongo que puede. Usted me divierten muchísimo. ¿Qué otra cosa puedo contestar por usted? }
{271}{}{Háblame de nuevo sobre este gente.}
{272}{}{¿Qué es todo este divertido-líquido de color alrededor de la EPA?}
{273}{}{De donde sacas todo el equipo y suministros para sus experimentos?}
{280}{}{No, No, No. Antes de salir, tengo que preguntarte algo. Puedes hacer un pequeño favor para mí? Yo no abandonar la seguridad del almacén para el miedo de que las cosas sean robados. Necesito un poco de materias primas. ¿Podría usted ayudarme?}
{281}{}{Sí, supongo que sí. ¿Qué se necesita?}
{282}{}{No, yo estoy muy ocupado en este momento. Tal vez en algún otro momento.}
{290}{}{Sí, me preguntaba lo que el virus podría hacer en regular animales domésticos guardados en el almacenamiento de antes de la guerra. La cosa lamentable fue afectado sus ciclos reproductivos y se crían de manera muy rápida. He publicado en el gasta poco después me di cuenta de que.}
{291}{}{Eres un monstruo! No es de extrañar que nadie en el área sabe acerca de usted! Usted debe ser desechado.}
{292}{}{Bueno, no estoy de acuerdo con lo que están haciendo, pero no hay nada que yo pueda hacer al respecto. Adiós.}
{300}{}{Medicamentos especiales? Bueno, he estado desarrollando una nueva cosecha de marihuana. Es un pre-guerra de la droga que he encontrado en la deep freeze. Sólo tengo abono a pesar de las criaturas mutantes que usted ve aquí, lo que era más peligroso de lo que yo pensaba. Las primeras pruebas no fueron muy exitosos, de todos modos...}
{301}{}{Puedo conseguir algo de este medicamento?}
{302}{}{Por qué no estaban con éxito? Lo que pasó?}
{310}{}{El Señor Chemmie! se encuentra en la sección noreste de la parte baja de la EPA. O tal vez el noroeste... en Realidad, es en la planta superior. Oh, no puedo recordar nada más. Es un pedazo enorme de la maquinaria. No te lo puedes perder.}
{311}{}{A la derecha. Gracias. Usted mencionó que había creado algunos medicamentos especiales. Como qué?}
{320}{}{Fácilmente. Yo soy un científico. Eso es lo que yo hago. Los experimentos son mi vida. Aunque diferentes, en realidad, es sólo un experimento de otro tipo.}
{321}{}{Usted está jugando con cosas que no se debe alterar! ¿Qué pasa si las cosas van mal? Lo que si algunas de las personas que está trabajando en morir!?}
{330}{}{Eliminados! Oh, no. Yo no lo creo. Yo estoy haciendo el trabajo que me había contratado para hacer. Investigar y experimentar. Como pasa el tiempo, sin embargo, usted comenzará a correr de cosas para investigar, así que tienes que ser más liberal en sus ideas. Creo que alguna vez se llamó "pensamiento fuera de la caja'.}
{331}{}{He tenido suficiente de esto! Si nadie más va a dejar de usted, entonces voy.}
{332}{}{Usted está enfermo y me voy. Adiós.}
{340}{}{Sí, ¿por qué no? Ayudarse a sí mismo. Hay mucho en los cobertizos de almacenamiento en el nivel de la superficie. Yo creo que puede haber programado el Señor Chemmie! para hacerlo así. No tengo ninguna por aquí, ya que ocupa mucho espacio.}
{341}{}{Gracias! Usted decía hace un momento que no tuvieron éxito en los primeros ensayos? ¿Por qué es eso?}
{350}{}{Así, algunos de los sujetos de prueba tenido reacciones graves a los virus, pero esos no son ni siquiera vale la pena mencionar. Algunos errores aquí y allá, se espera que en nuestra línea de trabajo. Ahora, si me disculpáis, tengo cosas que hacer.}
{351}{}{Sí, supongo que yo también. Adiós.}
{360}{}{Y luego mueren. ¿Qué espera usted que yo haga? Esta es la forma en que uno hace el progreso.}
{361}{}{Monstruoso! Increíble! De morir - ¡ahora!}
{362}{}{No puedo soportar más esto. Adiós. No voy a estar de vuelta pronto.}
{370}{}{Jet? Sí, esa es la droga que más de Redding ha sido alta, si no me equivoco. Es un excepcional complejo compuesto y mis máquinas no pudieron reproducir incluso en su máxima potencia. Por qué? ¿Qué sabe usted de él?}
{371}{}{Bien, he aquí conmigo es creador.}
{380}{}{[*Brillan los ojos*] ¡de verdad!? Que? Puedo verlo? Tal vez hablar con él?}
{381}{}{Por supuesto. Su nombre es Myron. Él está aquí.}
{390}{}{Gracias por traer que Myron chico para mí. Él está muy bien informado! No se muy bien como intelectualmente experto como yo, a entender, pero bien, no obstante. Si alguna vez se quiere resolver abajo se puede venir aquí como mi aprendiz.}
{391}{}{No estoy seguro de que le gustaría ser alguien del aprendiz. Es mejor que estar pasando.}
{400}{}{Un momento, antes de ir. Por favor, tome esto como una muestra para llevar Myron aquí. No tengo uso para él.}
{401}{}{Hey, gracias. Um, ¿qué es?}
{410}{}{Es un Solar Abrasador. Fue un experimento de la mina. Se alimenta de la energía del sol y por lo tanto no hay municiones. Lo que realmente funciona y que será de gran utilidad para usted, estoy seguro de que, en las profundidades de los desechos. Esto requiere una nueva pregunta en realidad...}
{411}{}{¿Qué es eso?}
{420}{}{Parece un tipo de aventura. Yo estoy limitado a los motivos de la EPA para mirar a través de muchos de los experimentos, pero necesito un poco de equipo que se me ha agotado. Podría recoger un par de cosas para mí?}
{421}{}{Sí, supongo que sí. ¿Qué se necesita?}
{422}{}{No, estoy demasiado ocupado en el momento en el ahorro de mi pueblo. Tal vez en algún otro momento.}
{430}{}{Así, uno de los únicos animales que no he estudiado en detalle es el de Golden Gecko. Necesito un poco de material de investigación antes de que pueda ir a más. Podría recoger, digamos, 10 de golden gecko pieles y traerlos de vuelta aquí para mí? Estoy seguro de que podría encontrar algo aquí para dar.}
{431}{}{No hay problema. Estaré de vuelta tan pronto como los tengo.}
{432}{}{Ya tengo 10 pieles conmigo.}
{440}{}{[Mira para arriba en usted.] Qué?}
{441}{}{Uh, hola de nuevo. No he entendido que usted es la última vez que hablamos.}
{450}{}{Usted de nuevo? Qué quieres ahora?}
{451}{}{¿Qué haces aquí? Este lugar es como un pueblo fantasma.}
{460}{}{Si usted no desea ayudarme, por favor, que me dejes solo. O, ¿has decidido prestar sus habilidades?}
{461}{}{Sí. ¿Qué quieres que yo haga?}
{462}{}{No, pero tan pronto como yo soy libre voy a estar de vuelta para ayudar a usted.}
{470}{}{Hola. Han calmado en todo momento?}
{471}{}{No, yo estoy aquí para matarte. El mundo necesita menos gente como tú.}
{472}{}{Sí, supongo. Necesito hacerte unas preguntas.}
{480}{}{¿Qué desea? He experimentos para ver más, usted sabe!}
{481}{}{Me dicen acerca de los medicamentos que están tomando.}
{482}{}{Háblame de esa gente de nuevo.}
{483}{}{Estoy buscando trabajo. ¿Tienes alguno?}
{484}{}{De donde sacas todo su equipo, que desde?}
{490}{}{Han recogido las pieles como ya he solicitado?}
{491}{}{Si, aquí están.}
{492}{}{No, aún no.}
{500}{}{Maravilloso! Excelente! Déjame ver... ah sí, estos va a hacer muy bien! Ahora bien, ¿quieres otro trabajo?}
{501}{}{Sí, si tienes alguna otra cosa.}
{502}{}{Aún no, gracias. Adiós.}
{510}{}{Así, aunque la bodega es donde hago casi todos los de mi trabajo, tengo que entrar en el complejo principal de vez en cuando. Sin embargo, las luces se han fijado de manera permanente en el ajuste bajo. Solucionar esto para mí, para que yo pueda entrar en la EPA del propio edificio.}
{511}{}{No hay problema.}
{512}{}{Voy a volver a usted cuando tengo tiempo para hacerlo.}
{513}{}{Ya he hecho esto! Hubo algunos cables sueltos en la placa de circuitos principal y me maná-}
{520}{}{Ahora que has matado a todos mis guerreros, usted tiene más que demostrado que eres digno. Habría que considerar la posibilidad de trabajar para mí?}
{521}{}{Qué!? Trabajando para usted!? ¿Qué quieres que yo haga?}
{522}{}{No, gracias. Adiós.}
{530}{}{Ha resuelto el problema de la energía todavía?}
{531}{}{Sí, sí, sí, no necesito saber los detalles. Gracias. Ahora, todavía tengo una tarea más si usted desea llevar a cabo la misma.}
{532}{}{¿Qué es eso?}
{533}{}{No, sigo trabajando en ello.}
{540}{}{Estoy experimentando con un nuevo suero en el momento para mejorar la agilidad y conocimiento de las personas que les ayudan a sobrevivir en este mundo hostil. Usted iba a permitir que me trate sobre ti, ¿no?}
{541}{}{Bueno... supongo que sí, ¿qué daño podía hacer?}
{550}{}{Más de lo que alguna vez había creen que si sale mal... Ahora tienen todavía y vamos a llegar a esto!}
{551}{}{¡Eh, eh! Espere un minuto...}
{560}{}{Ah, ahí estás! De vuelta en la tierra de los vivos, veo! ¿Cómo te sientes?}
{561}{}{Uh, ¿bien por qué?}
{570}{}{Sólo se desmayó durante un par de horas, pero usted debe estar bien ahora. Indicaciones muestran que son mucho más alerta y sensible.}
{571}{}{¡Caray! Gracias, doctor.}
{580}{}{No hay problema. Si alguna vez necesitas algo, hágamelo saber.}
{581}{}{Eso haré. Adiós.}
{590}{}{Han decidido ayudar a mí todavía?}
{591}{}{Sí, yo te ayudaré. Voy a volver cuando se restablezca la alimentación.}
{592}{}{No, lo siento.}
{600}{}{Lo siento, pero no hay nada más que puedo hacer por ti ahora. No tengo más puestos de trabajo que queda por hacer. Gracias por tu ayuda.}
{601}{}{Entonces adiós.}
{602}{}{Sí, hubo algunos cables sueltos y yo tenía que encontrar algo de chatarra-}
{603}{}{¡NO! ¿Qué estás haciendo?}
{700}{}{Espera un segundo! Ustedes fueron parte de la *original* equipo?! Pero, que tiene que hacer casi 200 años de antigüedad!}
{701}{}{Bueno, supongo que es cierto, en un camino. Yo en realidad nació 202 años. Sin embargo, no hay manera de que yo podría haber vivido de esa larga a través de los medios normales.}
{702}{}{Continúa. Estoy escuchando.}
{703}{}{Cuando comenzó la guerra, el resto de los científicos y he usado el criogénico de almacenamiento de las cámaras. Hemos entregado más de control de la instalación a los hologramas y los robots, a continuación, poner de nosotros mismos en las cámaras a esperar lo peor de la destrucción.}
{704}{}{Pero, la gran guerra había terminado hace muchos, muchos años.}
{705}{}{Verdadero. Inicialmente se salió de la hibernación unos 90 años, y descubrió que este lugar se había deteriorado considerablemente. La mayoría de los otros científicos aquí seguido algunos de sus originales de investigación, ya que realmente no sabía qué otra cosa hacer.}
{706}{}{[MÁS]}
{707}{}{Yo no podía creer a sus científicos a la falta de visión... su falta total de imaginación! Tuvimos una oportunidad increíble para hacer algunas cosas increíbles. Tuvimos la oportunidad de rehacer las cosas como vimos al ajuste. Lamentablemente, mis compañeros pagado por su falta de visión...}
{708}{}{Has matado!?}
{709}{}{Comprensible.}
{710}{}{Por favor, continúa.}
{711}{}{No, yo no he matado a ellos. Pero yo no podía tener la estancia aquí de interferir con mis planes. Simplemente me manipuló aquí, así que decidieron irse.}
{712}{}{Bueno, que responde a una parte de la historia. Pero todavía hay algo que falta...}
{713}{}{Ah, sí. Lo siento por eso. A veces me voy por la tangente o mi mente divaga. Grandes mentes, ¿sabe usted? De todos modos, sigo a utilizar el tanque. He modificado un poco, sin embargo.}
{714}{}{¿Qué modificaciones se han hecho?}
{715}{}{Creo que ya he oído bastante. Adiós.}
{716}{}{Bien, la primera vez que se utilizó el criogénico de las cámaras, era como si me fui a dormir y se despertó. Pero, me di cuenta de que era una pérdida de tiempo. Puedo restablecer la configuración de la cámara para que yo pudiera usar durante años, en un momento, pero mantener mi mente consciente! Yo uso esos períodos prolongados a reflexionar sobre los proyectos actuales y pensar en nuevos experimentos. Al hacerlo, puedo ver los efectos a largo plazo de mi investigación.}
{717}{}{¿Alguna vez considerar la posibilidad de que tal vez el uso de la cámara como esta puede ser perjudicial para usted de alguna manera?}
{718}{}{Tonterías! Si de algo estoy mejorando. Puedo ver las cosas con tanta claridad, ahora, gracias a mi períodos de lucidez de la hibernación.}
{719}{}{Qué loon! Adiós.}
{720}{}{Que en realidad es una gran idea. Genio! Hey, ¿crees que yo podría ver este criogénico de la cámara?}
{721}{}{Lo que veo. Hablemos de otra cosa.}
{722}{}{Bueno, por supuesto. Es justo allí. Me había mudado aquí hace algún tiempo. Mantener la cámara en los subniveles de este centro no sólo era una buena idea.}
{723}{}{Interesante. Así que, ¿cómo funciona?}
{724}{}{Bueno, por supuesto, los principios científicos de la criogenia es bastante avanzada. Sin embargo, las funciones se rigen por el equipo aquí, es bastante fácil interfaz. [Toma un par de minutos que muestra cómo funciona el sistema.]}
{725}{}{Gracias por la información, Doctor. Supongo que todavía me gustaría saber acerca de un par de otras cosas.}
{726}{}{Gracias por la información, Doctor. Quién sabe? La información, como podría ser útil algún día. Adiós.}
{727}{}{Bueno, ya basta de chit-chat. Yo debería estar pasando. Adiós, Doctor.}
{728}{}{No, simplemente no se que hacer para que se queden aquí interferir con mis planes... no en todos los... [El Médico miradas pasado, aparentemente perdido en sus pensamientos.]}
{729}{}{Usted sabe, usted es un trenzado persona. Creo que me voy a tener que mostrar cómo 'experimento' en las personas. Tiempo para morir!}
{730}{}{Así que, ¿estás feliz con esta situación? Me refiero a que, siendo el único aquí?}
{731}{}{¿Qué más quieres saber?}
{800}{}{En realidad, espere un segundo. Te ves como un tipo de aventura. Yo podría tener un uso para alguien de sus habilidades.}
{801}{}{Claro. ¿Qué necesitas?}
{802}{}{No, gracias. Adiós.}
{803}{}{Bueno, yo estaba a cabo la recogida de muestras en uno de mis sitios de trabajo y me parece que han dejado una de mis herramientas. Normalmente
 Acabo de ir y obtener yo mismo, pero estoy muy ocupado en este momento y para la vida de mí no puedo recordar exactamente
 spot me dejó. En cualquier caso, hacia el noroeste de este edificio y usted encontrará el área donde dejé mi herramienta. Debe
 ser un pedazo de la torta.}
{804}{}{Me pondré a ello ahora mismo.}
{805}{}{No estoy interesado. Adiós.}
{806}{}{Bueno, a esperar. Está usted seguro de que no me ayuda con un poco de algo?}
{810}{}{Excelente! Ahora, debo volver al trabajo. [A sí mismo.] Todo va según el plan.}
{811}{}{[HECHO]}
{820}{}{Eso es muy malo. Bueno, debo volver al trabajo. [A sí mismo.] Casi lo tenía. Ahora, a dónde voy a encontrar a otro sujeto de prueba...}
{821}{}{[HECHO]}
{830}{}{[El hombre mira asustado.] Lo que los?!}
{831}{}{Todavía estoy buscando por su parte.}
{832}{}{Esta es tu herramienta. Pedazo de pastel de hecho.}
{833}{}{Estaba tratando de matarme por ahí? Que era un laberinto lleno de monstruos mutados. Esta no era una parte ordinaria
 trabajo de recuperación, ahora era él?}
{840}{}{Qué?! A mi me da que! [Él arrebató la herramienta de su mano.] Cómo hizo usted - Oh, no importa. De vuelta a la mesa de dibujo, a continuación,...}
{841}{}{[Ignorar el hombre de la reacción.] Bien, bien, si necesitas algo más, que me haga saber. Bye.}
{850}{}{Eso es ninguno de su negocio. [Le agarra la herramienta de su mano.] Ahora, fuera de aquí. Tengo cosas que hacer. [Mira
 lejos murmurando para sí mismo.]}
{851}{}{Lo que sea. Adiós.}
{852}{}{Yo no lo creo. Se trató de matarme y ahora voy a devolver el favor. Prepárate a morir!}
{860}{}{Uh, sí, por supuesto. Bien, llegar a ella.}
{861}{}{[HECHO]}
{900}{}{*Se queja*}
{901}{}{*A sí mismo* yo estaba seguro de que él no volvería.}
{1000}{}{Devolver el Médico olvidados de la herramienta.}
