{100}{}{Ves un Holograma.}
{101}{}{Ves al Director de Relaciones Públicas.}
{102}{}{Holograma 40011. Ella está a cargo de todas las giras y comunicados de prensa en la APA.}
{200}{}{[Este atractivo holograma femenino te saluda con una sonrisa amistosa.] Hola visitante, y bienvenido a la APA. ¿Como puedo ayudarte? El almuerzo se servirá en la cafetería a medio día para todos los empleados de la empresa.}
{201}{}{¿Qué? Oh no importa. ¿Quién eres tú?}
{202}{}{Necesito irme Adiós.}
{210}{}{¿Yo? Soy el holograma 40011, la directora de relaciones públicas. Organizo viajes, excursiones y otras cosas y me aseguro de que el lugar funcione sin problemas para el público en el día a día. El recorrido por el museo APA comenzará en breve. Por favor tenga sus pases listos.}
{211}{}{Eso suena como un trabajo fascinante. Adiós.}
{212}{}{Entonces, ¿podrías ayudarme con algo?}
{220}{}{Por supuesto. Me encantaría ayudar ¿Cómo puedo ayudarte? Los folletos turísticos se pueden encontrar en la oficina principal y en buzones en todo el APA.}
{221}{}{There's some doors around the complex that I can't open without speaking a password. I'd really like to get through them and see more of your facility. I don't suppose you know the password?}
{230}{}{Of course I know the password, but unfortunately, I'm unable to share it with you. I understand your enthusiasm for wanting to experience all that this great facility has to offer, but there are rules we must follow for your own safety. Remember everyone, we offer guided tours of our complex at predetermined times.}
{231}{}{Oh, you don't have to worry about my safety, I'm the Chosen One. Besides, when's the last time you had a *real* visitor? Do you really want to leave me disappointed?}
{232}{}{De acuerdo entonces. Adiós.}
{240}{}{Of course not. But, if I give you the password, then not only could I be endangering you, but I'd also be endangering the complex. Children, please do not taunt the holograms.}
{241}{}{How could that endanger the complex? I hate to break it to you lady, but this complex has already gone to hell and back. There's nothing here but hazardous chemicals and broken robots. Honestly, I don't see how I could possibly make matters worse.}
{242}{}{Olvídalo entonces.}
{250}{}{I... I don't know. I'd be defying protocol. But... perhaps if you could assist me with something. Visitors, please note that the blue level is restricted for reasons that are very uninteresting. There's no need to be curious about it.}
{251}{}{Ah, venga. Lo siento. Sólo dime lo que necesito saber.}
{260}{}{Ah yes, it looks much better in here now, thank you. The password is ABRE. Just speak clearly to the door and it
 will open. Now would everybody please...}
{261}{}{YES, we've heard you already. Thanks for the code. Goodbye.}
{270}{}{Hello again. What do you need? The EPA complex will be closed for the foreseeable future due to lack of staff.}
{271}{}{Now that I have more time, could you tell me what you do here?}
{272}{}{No importa.}
{280}{}{Welcome back, visitor. There isn't a tour at the moment, but if you'd like to wait around for enough visitors to arrive, I'd be happy to arrange one.}
{281}{}{I don't want to go on a tour, thanks. Goodbye.}
{282}{}{¿Puedes hacer algo por mí?}
{290}{}{Hello there. I'm a little busy at the moment designing a new tour program for the coming season. Could you come back later?}
{291}{}{I would, but I'm in too much of a hurry. You see, I *really* need the password for those doors. Would you please give it to me?}
{300}{}{Thanks again for your assistance, and please be responsible with the password I gave you. Remember, that's our little secret. Thank you for visiting the EPA, I hope you have a pleasant experience.}
{301}{}{Gracias. Adiós.}
{302}{}{Únete a nosotros alguna vez!}
{303}{}{Don't forget to visit the EPA souvenir stand.}
{310}{}{Do you think you could fix the lighting? It's improper for me to conduct tours through such a dimly lit complex.
 If you could brighten this place up for me, I'll give you the password. Please, remember to wash your hands thoroughly
 after visiting our petting zoo.}
{311}{}{Veré lo que puedo hacer.}
{312}{}{Nevermind. I'm not interested.}
{320}{}{The complex is still looking rather drab. You're still going to fix the lights, aren't you? Remember visitors, all waivers must be signed before the end of the tour.}
{321}{}{No te precupes. Estoy trabajando en ello.}
{322}{}{Me pondré con ello.}
{330}{}{We'd have more visitors if the grounds were clean.}
{331}{}{How am I supposed to conduct tours without proper lighting?}
{332}{}{Those plants are killing all potential tourists.}
{333}{}{All those broken down robots are *very* unsightly.}
{334}{}{10031, you've been useless for decades.}
{335}{}{All I'm saying, is that this place needs to be more presentable.}
{336}{}{Destroying the complex is not the answer.}
