{100}{}{El generador tiene dañada la placa de circuito. Tal vez usted podría compactar las piezas de recambio de algunos de basura.}
{101}{}{You see a generator.}
{102}{}{You see an EPA lighting generator.}
{103}{}{Usted ve un generador que controla la iluminación en la EPA.}
{104}{}{Después de una larga búsqueda, una placa de circuito con algunas piezas dañadas se encuentra. Tal vez si algunos de basura se encuentra a comerse a través de, algunas piezas de reemplazo puede ser obtenido.}
{105}{}{There's the problem!}
{106}{}{Las piezas rotas se han arreglado juntos y que el generador está de nuevo en línea.}
{107}{}{Nothing wrong can be found with the generator. It just doesn't seem work.}
{108}{}{It's working. There's nothing else to do.}
{109}{}{Something doesn't seem right with this generator.}
{200}{}{*whirr*}
{201}{}{*bzzt*}
