{100}{}{Bienvenidos a la EPA de Control del Robot Equipo. ¿Qué desea hacer?}
{101}{}{Comando De Robots.}
{102}{}{Ejecute verificación de diagnóstico.}
{103}{}{Te marchas.}
{104}{}{!ERROR! !ERROR! HA ENCONTRADO EL PROBLEMA DE LA TERMINACIÓN DE LA SECUENCIA!}
{105}{}{Volver al Menu Principal.}
{106}{}{Comprobación de diagnóstico de... de la placa de circuito de error....la sección cuatro... cables flojos.}
{107}{}{Hecho}
{108}{}{Es demasiado difícil para reparar esto.}
{109}{}{El fallo en el equipo es reparado y que la máquina vuelva a estar online.}
{110}{}{Bienvenidos a la EPA de Control del Robot Equipo. Usted ya no tiene la autorización de seguridad para el uso de estos archivos. La terminación de la secuencia.}
{111}{}{HECHO}
{112}{}{BEEP!}
{113}{}{BOOP!}
{114}{}{Bzzzt..}
{115}{}{Ya lo reparó.}
