{100}{}{Usted ve a una modificación de la Auto-Doc.}
{101}{}{Esta Auto-Doc parece haber sido modificado para realizar experimental modificaciones apariencia.}
{200}{}{[La máquina de direcciones cuando te acerques.] Bienvenido, Sujeto De Prueba. Gracias por el voluntariado de su carne para
 la ciencia. Por favor, paso dentro de mí y podemos empezar.}
{201}{}{Whoa, nunca me dijo que yo era voluntario nada. Ahora, antes de que me paso en cualquier lugar, ¿por qué no me dices exactamente lo que ustedes hacen?}
{202}{}{[Encogimiento de hombros.] Bien. [Paso a paso en el dispositivo.]}
{203}{}{Me tienes confundido con alguien más. Bye.}
{300}{}{Bienvenido de nuevo, Objeto de la Prueba. Por favor, paso dentro de mí y podemos empezar.}
{301}{}{Antes de que me paso en cualquier lugar, ¿por qué no me dices exactamente lo que ustedes hacen?}
{302}{}{Bien. [Paso a paso en el dispositivo.]}
{303}{}{Yo no lo creo. Bye.}
{400}{}{Yo soy el más reciente prototipo de Auto-Doc tecnología, desarrollada por el Dr. Wood. Me especializo en el extremo del cuerpo
 modificación-el último cambio de imagen. No hay necesidad de estar nervioso, como mi paciente tasa de mortalidad es significativamente menor
 que el anterior prototipo. No sea tímido, paso dentro de mí y podemos empezar.}
{401}{}{No estás tocando a mí. Bye.}
{402}{}{Me encantaría, pero que realmente necesita para ponerse en marcha. Lo siento.}
{403}{}{Bien. [Paso a paso en el dispositivo.]}
{410}{}{Por favor haga su selección. Debido a ser un prototipo, sólo puedo ofrecer opciones limitadas. Lo siento.}
{411}{}{Alterar El Género.}
{412}{}{Alterar La Raza. (Actualmente sólo Blanco Africano-Americanas o viceversa).}
{413}{}{Alterar Peinado (Regular Del Pelo).}
{414}{}{Alterar Peinado (Pelo Largo).}
{415}{}{Alterar Peinado (Calvo).}
{416}{}{Alterar Peinado (Cabello Rubio).}
{417}{}{Alterar Peinado (Pelo Rojo).}
{418}{}{En el segundo pensamiento, realmente no tengo tiempo para esto ahora mismo. Bye.}
{500}{}{Este procedimiento será de cuatro semanas para recuperarse y tiene un 50% de probabilidad de muerte. ¿Quieres empezar ahora?}
{501}{}{Hagámoslo.}
{502}{}{Sí. Finalmente, puedo ser la persona que siempre he estado en el interior.}
{503}{}{Eh, tal vez más tarde. Bye.}
{504}{}{Me deja elegir otro procedimiento.}
{505}{}{El infierno no! Me voy de aquí!}
{510}{}{Excelente elección. Este procedimiento será de dos semanas para recuperarse y tiene un 25% de probabilidad de muerte. ¿Quieres empezar ahora?}
{511}{}{Hagámoslo.}
{512}{}{Sí. Finalmente, puedo ser la persona que siempre he estado en el interior.}
{513}{}{Eh, tal vez más tarde. Bye.}
{514}{}{Me deja elegir otro procedimiento.}
{515}{}{El infierno no! Me voy de aquí!}
{520}{}{Excelente elección. Este procedimiento será de un día para recuperarse y tiene un 1% de probabilidad de muerte. ¿Quieres empezar ahora?}
{521}{}{Hagámoslo.}
{522}{}{Sí. Finalmente, puedo ser la persona que siempre he estado en el interior.}
{523}{}{Eh, tal vez más tarde. Bye.}
{524}{}{Me deja elegir otro procedimiento.}
{525}{}{El infierno no! Me voy de aquí!}
{600}{}{Felicitaciones! El experimento fue un éxito. Gracias, y disfruten de lo nuevo.}
{601}{}{[Salir.]}
{650}{}{Lo siento, este procedimiento en particular no está disponible actualmente para las hembras.}
{700}{}{Lo siento, pero algo salió terriblemente mal con el procedimiento. Pedimos disculpas por este inconveniente, pero gracias
 para el voluntariado para el bien de la ciencia.}
{701}{}{Oh, mierda...}
