{100}{}{Ves a un trabajador portuario. Mira cuando te acerques.}
{101}{}{Usted ve una melancolía trabajador portuario. Su tristeza ojos llenos de vista para arriba en usted como usted se enfoque.}
{200}{}{[Murmura para sí mismo.] Oh, qué atrocidades que hizo pobre Meng hacer en una vida pasada para merecer tal
 la desgracia? Ahora el lao wai viene a mí, y lo bueno que podía esperar de él? Ninguno, por supuesto. Ninguno...}
{201}{}{¿Por qué no salir de pobres Meng en paz? [Murmura para sí mismo.] No es que yo jamás he conocido la paz. O, si lo hice,
 luego es olvidado, como un sueño lejano...}
{202}{}{Uh, me parece que han cogido en un mal momento. Bye.}
{203}{}{¿Cuál es tu problema, Murmura?}
{204}{}{Me di cuenta de que parece estar molesto por algo. Me preguntaba si me podrían ayudar.}
{210}{}{Mi problema? [Ríe amargamente.] Loa wai, usted no desea saber mi problema. Para escuchar de dolores como el mío
 es olvidar el sonido de las risas de los niños, y el cálido abrazo de un amante. No, confía en mí, usted no desea echar un vistazo en mi Infierno personal.}
{211}{}{He visto un montón de cosas terribles en mi tiempo. Estoy seguro de que sea cual sea tu problema, yo puedo manejar esto.}
{212}{}{Usted piensa que *su* problemas son malos? Apuesto a que no *comparar* a las cosas que hemos sido a través de.}
{213}{}{Siento que las cosas han sido difíciles para usted, pero podría ayudar a hablar de ello. Si usted está dispuesto a hablar, entonces yo estoy dispuesto a escuchar.}
{214}{}{Todo derecho el Señor Melodrama, voy a salir ahora, antes de que usted me hace deprimido. Bye.}
{220}{}{Bien. Quieres saber mi problema. Yo se los diré. Hace dos años, mi hermano, que es muy similar a mí, tenía
 un romance con un local líder de la banda de la novia. El líder de la banda enteré de que mi hermano y huyeron de la ciudad. La banda
 me atrapó en su lugar, y, pensando que era mi hermano, que cortó mi pene como castigo. Ahora me mear a través de un tubo.}
{221}{}{Oh, bien ... }
{230}{}{Oh no! Aún no terminé. Luego mi hermosa novia me dejó, porque yo ya no era un "hombre de verdad" y no podía
 satisfacerla. Luego ella se casó con mi vecino de al lado, que también pasa a ser mi jefe. Ahora, todo el día en el trabajo, él me órdenes
 a su alrededor y se burla de mí con mis compañeros de trabajo. Y cada noche me debe tratar de quedarse dormido con el sonido de él haciendo el amor a la
 chica debería haber casado.}
{231}{}{Jajaja! Santa mierda, eres un perdedor. ¿Por qué no hacer usted mismo un favor y acaba de terminar esto?}
{232}{}{Yo, uh, wow, no estoy seguro de qué decir. Esa es una historia terrible.}
{233}{}{Siento que te haya pasado, Meng. La vida puede ser cruel, pero siempre se puede mejorar. Si yo fuera usted, me gustaría mover
 en algún otro lugar y encontrar un trabajo diferente. De lo contrario, usted nunca será capaz de seguir adelante.}
{240}{}{Sí. Sí, esto es lo que debería haber hecho hace mucho tiempo. Es la única manera de conservar lo poco honor que me han dejado.
 Gracias, lao wai. [Saca un cuchillo y rendijas de su garganta. Mirar como él rápidamente se desangra.]}
{241}{}{[HECHO]}
{250}{}{Sí. Esto me advirtió acerca de. Ahora, permítanme ser. No tengo nada más que decir.}
{251}{}{[HECHO]}
{260}{}{Tal vez tienes razón. Toda mi vida, he conocido nada pero el Shi. Pero no hay nada aquí para mí, pero la tristeza.
 Sí, creo que voy a salir en el mundo y forjar un nuevo destino. Incluso si los desechos que me ofrecen nada, pero un swift
 la muerte, que es preferible a permanecer aquí. Gracias, lao wai.}
{261}{}{Buena suerte, Meng. Espero sus fortunas a mejorar.}
{262}{}{Antes de comenzar a empacar, me preguntaba si usted podría responder a una pregunta o dos para mí?}
{270}{}{¿Por qué no? Yo soy de la ruptura de todos los vínculos con el Shi. Sus secretos ahora no significan nada para mí. Preguntar lo que quieras.}
{271}{}{¿Qué me puedes decir acerca de que custodiaba lancha por allí? }
{272}{}{Nunca la mente. Buena suerte en su nueva vida, Meng.}
{280}{}{El Shi uso que una lancha a motor para acceder a nuestro sueño tutor, el sub.}
{281}{}{¿Qué me puedes decir acerca de los sub?}
{290}{}{El Shi-Huang-Ti, es el submarino que llevó a nuestros antepasados a este lugar de una tierra lejana. En las secuelas
 de la Gran Guerra que perdió el poder y encalló en la bahía de San Francisco. El capitán Ye Li y su equipo, a continuación, hizo su camino
 a esta ciudad y se estableció lo que sería el Shi de la sociedad.}
{291}{}{Usted se refirió a él como un "sueño de tutor". ¿Qué quieres decir con eso?}
{300}{}{Como hibernar a un dragón cuyo ronca todavía puede producir fuego mortal -- el sub es inmóvil, pero no indefenso.
 El Shi ha estado trabajando en secreto, haciendo viajes clandestinos a la sub amparo de la noche. Sus armas
 ha reactivado y surly destruir cualquier no-Chino vasos sanguíneos que se atreven a navegar a través de esta bahía.}
{301}{}{Así que, digamos, *hipotéticamente*, si esa gran cisterna que está acoplado aquí donde probar y zarpar...}
{310}{}{Entonces... BOOM!}
{311}{}{Gotcha. Supongo que usted no sabe cómo yo podría desarmar a él?}
{320}{}{Sólo el Shi técnicos gustaría saber una cosa. Yo he dicho todo lo que sé.}
{321}{}{Gracias, Meng. Buena suerte con tu nueva vida.}
{330}{}{Ahora es el momento de comenzar de nuevo...}
{350}{}{Me dejan ser, lao wai.}
{400}{}{Usted convencer a Meng para seguir adelante con su vida.}
