{100}{}{Ves a una vándala.}
{101}{}{Ves a una vándala.}
{102}{}{Ves a una joven bastante bonita pero de apariencia desaprensiva.}
{103}{}{Apuesto a que mi novio me ofreció para compartirme.}
{104}{}{A veces me harta viajar.}
{105}{}{Seguro que sería agradable vivir aquí.}
{106}{}{Apuesto a que podríamos montar un buen escándalo.}
{107}{}{¿Has ido al oeste cruzando el mar alguna vez?}
{108}{}{Flirtearía contigo, pero es que no estoy interesada.}
{109}{}{::con sarcasmo:: Seguro que hay un montón de mujeres fuertes por aquí, ¿eh?}
{110}{}{¿Esperas que caiga rendida a tus pies? Despierta.}
{111}{}{¡Soy único! ¡Igual que los demás!}
{112}{}{A veces el hastiado cinismo del mundo me aburre.}
{113}{}{La próxima vez, quiero encontrarme con una tribu de góticos.}
{114}{}{He oído que el Emperador Shi es inhumanamente inteligente.}
{115}{}{Esos Shi tienen una pinta muy graciosa, la verdad.}
{116}{}{Soy de mente abierta, ¿eh?}
{117}{}{Mira a todos esos nuevos vagabundos. Imitadores.}
{118}{}{AHS-9 nos engañó y también te engañará a ti si se lo permites.}
{119}{}{Al próximo imbécil que me llame "zorra" lo dejo frito.}
{120}{}{¿Entonces cómo fue con un mutante?}
{121}{}{¿Te hizo daño ese muti grandullón de Francis?}
{122}{}{Me sorprende que puedas caminar después de lo que hizo Francis.}
{123}{}{Imagino que aún seguirás sangrando después de lo de Francis.}
{124}{}{No puedo creer que fueras incapaz de ayudar a Chip.}
{125}{}{Bastardo egoísta. Apostaría a que Chip tu hubiera ayudado.}
{126}{}{A todo el mundo le gustaba Chip. Tú no le gustas a nadie.}
{127}{}{Eres un pedazo de gilipollas, ¿verdad?}
{128}{}{¿Alguna vez piensas en alguien que no seas tú mismo?}
{129}{}{Oh, mira, es el "héroe".}
{130}{}{¡Oíd todos! ¡Es el cabrón egoísta!}
{131}{}{Oh, ¿otra vez tú? Como si todo el mundo quisiera hablar contigo.}
{132}{}{¡Odias a Chip!}
{133}{}{Mala suerte con lo del bazo.}
{134}{}{Apuesto a que alguien se comió el bazo de Chip.}
{135}{}{Me pregunto si Chip volverá a estar bien alguna vez.}
{136}{}{¡Creo que Chip es el mejor!}
{137}{}{¡Aunque no tenga bazo, lo haría con Chip sin pensarlo!}
{138}{}{Gracias por intentar traer de vuelta el bazo de Chip.}
{139}{}{Hiciste todo lo posible por Chip.}
{140}{}{Ahí va otro tópico sobre Chip.}
{141}{}{¿Me pregunto si el bazo sabía bien?}
{142}{}{¡Yay! ¡Ahora puedo tener a Chip y a su bazo!}
{143}{}{¡Voy a ver a Chip ahora mismo!}
{144}{}{¡Chip es el mejor!}
{145}{}{Me gustas. Eres bueno.}
{146}{}{Estoy contenta por Chip.}
{147}{}{Chip está completo ahora.}
{148}{}{¿Quieres pasar un buen rato con Chip y conmigo?}
{149}{}{Lo hiciste bien con lo del bazo de Chip.}
{150}{}{¡Qué desinteresado por tu parte!}
{151}{}{Suze ha vuelto! ¡Bien!}
{152}{}{Suze ha vuelto... ¡maldición!}
{153}{}{Suze siempre fue buena conmigo.}
{154}{}{Me gusta Suze.}
{155}{}{Gracias por salvarla.}
{156}{}{Algunas personas tienen que aprender a no vagabundear.}
{157}{}{¿Quién sabe?}
{158}{}{Pobre Badger. Tal vez necesite alguien que lo reconforte.}
{159}{}{Será mejor que me asegure que Badger está bien.}
{160}{}{Badger es guapo, pero no es un bombón.}
{161}{}{Me pregunto por qué Badger se pedorrea y eructa tanto.}
{162}{}{Badger probablemente se pedorrea porque está triste.}
{163}{}{Pobre Badger.}
{164}{}{Es duro este viejo mundo en el que vivimos.}
{165}{}{Suze debería haberlo pensado mejor.}
{166}{}{Si te vas a llevar el barco, deberíamos marcharnos.}
{167}{}{Lamento el estado del barco.}
{168}{}{Así que te vas a llevar el barco, ¿eh?}
{169}{}{El PMV Valdez es una buena nave: también fue un buen hogar.}
{170}{}{Supongo que es hora de empaquetar mis cosas.}
{171}{}{Disfruta del barco.}
{172}{}{Que tengas suerte buscando a tu gente.}
{173}{}{Ya me voy.}
{174}{}{Espero que podamos encontrar otro lugar donde vivir.}
{175}{}{Pobre Badger. Era realmente atractivo.}
{176}{}{¿Quién querría matar a Badger?}
{177}{}{Badger olía raro pero me gustaba.}
{178}{}{Había oído que Badger era gay, y resultaba que tenía una novia.}
{179}{}{Siempre había pensado que Badger era grosero, pero de forma linda.}
{180}{}{Apuesto a que Badger está alardeando con sus amigos.}
{181}{}{Badger... ::sniff::}
{182}{}{Badger parecía salido de un cuento de hadas.}
{183}{}{Gilipollas. ¿Por qué le mataste?}
{184}{}{¿Crees que vamos a unirnos a los Hubologistas ahora?}
{185}{}{Estúpido, estúpido títere.}
{186}{}{Los Hubologistas también te van a engañar a ti.}
{187}{}{¡Vete al infierno! ¡Vete al infierno y púdrete!}
{188}{}{Te odio.}
{189}{}{Apestas.}
{190}{}{¡Oveja ovejita ovejita!}
{191}{}{¡Cultista loco!}
{192}{}{Supongo que algunas personas son estúpidas desde que nacen.}
{193}{}{¡Vaya! ¡Es el idiota que no puede hablar consigo mismo!}
