{100}{}{You see a person in funny pajamas. He seems preoccupied.}
{101}{}{You see a Shi submarine technician.}
{150}{}{Uh, what are you doing, sneaking around like that?}
{151}{}{Are you some kind of spy?}
{200}{}{Esto sería más fácil si mi Chino fue mejor...}
{201}{}{Error de e/S!? ¿Cómo puede un sistema de guía de obtener un error de e/S!?}
{202}{}{001100010010011110100001101101110011? Dónde está mi código de error gráfico...}
{203}{}{Me gustaría que el FIB de la base de datos aún funcionaba. Eso sería hacer las cosas mucho más fácil.}
{300}{}{¿Qué quieres, lao wai? No puedes ver que estoy tratando de volver a configurar la orientación de los sistemas aquí?}
{301}{}{En realidad, eso es lo que estoy aquí. Tengo nuevas especificaciones para los sistemas, marcada por el Emperador, uh,
 personalmente. Puede que la entrada de ellos? Usted parece ser el que más sabe acerca de este subsistema.}
{302}{}{Es por eso que estoy aquí, me pueden ayudar con la configuración de los sistemas. Parece que la conexión entre la marina
 navegación subsistema y el transpondedor IFF finalmente murió, así que usted tiene que hacer una solución. Te importa si me ayuda?}
{303}{}{Sorry to bother you.}
{310}{}{Oh, he estado esperando para estas nuevas especificaciones para las edades! Usted debería haber estado aquí hace una semana, a pesar de que, cuando yo estaba trabajando en lo que queda de la batalla de la base de datos. Ahora tengo a reventar abrirlo de nuevo... Oh bien, la vida de una tecnología, supongo.}
{311}{}{Have fun. I'll see what else needs fixing.}
{320}{}{Apenas sé de usted! Para todos los que me conocen lao wai, podría ser algún tipo de espía extranjero, con ganas de deshabilitar este submarino, por lo que su plan de viajar a través de los mares a lugares extraños puede ser completado sin la torpedos hundimiento de su barco! Estoy seguro de que Ken Lee no dejar que un extraño junta directiva de la Shi-Huang-Ti con malas intenciones, así que lo siento, pero no puedo aceptar estas coordenadas si puedo formar parte de nuestra empresa líder en persona.}
{321}{}{Bueno, yo al menos ayudar con la configuración del submarino? Tengo algo de experiencia con los antiguos sistemas informáticos, lo suficiente como para entender cómo una de 200 años de vacío sistema de lámpara puede negarse a obedecer a su amo.}
{322}{}{Alright, sorry to bother you.}
{330}{}{Supongo que puede ser de ayuda, aquí, que lo intente. [El Shi tecnología le permite tomar la entrada. Después de unos momentos de familiarizarse con la interfaz de usuario, debe empezar a trabajar. Unos minutos más tarde no sólo se las arregló para volver a configurar los parámetros de orientación, por lo que el sub no se hunde el buque, sino también eliminar una falla en el sistema, evitando que los técnicos de acceso al subsistema fácilmente.]}
{331}{}{Bueno, ahí vamos. He corregido el sistema. No debería dar ningún problema ahora. Esperamos que va a ayudarle en su trabajo.}
{340}{}{Gracias por tu ayuda, es difícil encontrar un buen equipo de tecnología en estos días.}
{350}{}{Lo sentimos, pero no. Usted podría romper algo y vamos a perder el subsistema para el bien y soy yo *no* va a establecer el torpedo de adquisición de objetivos de los módulos con la mano. Así que, a menos que haya algo importante ** para mí, por favor, déjame volver a mi trabajo.}
{351}{}{En realidad, yo lo hago. Tengo nuevos parámetros de orientación para los torpedos, marcada con el Emperador, uh, sí. Eres el residente asistente de equipo, así que creo que puedo confiar en usted con esto.}
{352}{}{Sorry to bother you.}
{360}{}{No, yo no necesito ayuda o cualquier tipo de datos. Estoy aquí para trabajar y me impide trabajar, por lo que desaparece o voy a tener que *toma* de distancia!}
{361}{}{Sorry to bother you.}
{370}{}{Hey, I'm busy here.}
{371}{}{Sorry, I'm working.}
{400}{}{You tricked the technician into disabling the submarine.}
