{100}{}{Ves a una comerciante.}
{101}{}{Ves a Jenna, la comerciante.}
{102}{}{Ves a la guapa propietaria de una tienda.}
{103}{}{¡Hola! Soy Jenna. ¿Puedo ayudarte?}
{104}{}{Quiero yo información.}
{105}{}{¿Vendes cosas?}
{106}{}{No, marcho.}
{107}{}{Necesito cierta información.}
{108}{}{Desde luego, muéstrame lo que tienes a la venta.}
{109}{}{Ahora mismo no.}
{110}{}{He aprendido que cuanto menos sabes, más tiempo vives. No tengo más información para ti. ¿Te gustaría ver mis mercancías?}
{111}{}{Sí.}
{112}{}{No.}
{113}{}{Genial. Echa una vistazo.}
{114}{}{}
{115}{}{Vale.}
{116}{}{¿Algo más?}
{117}{}{Sí.}
{118}{}{No.}
{119}{}{Bueno, pues que tengas un buen día.}
{120}{}{}
{121}{}{Vale.}
{122}{}{Hola otra vez. ¿Hay algo más en lo que pueda ayudarte?}
{123}{}{Sí.}
{124}{}{No.}
{125}{}{Lo siento, pero está cerrado. Abro a las ocho; vuelve entonces.}
{126}{}{}
{127}{}{Vale.}
{128}{}{A ti no te atiendo. ¡Lárgate de mi tienda!}
{129}{}{}
{130}{}{Vale.}
{131}{}{Espero que ese cargamento llegue pronto.}
