{100}{}{You see a Hubologist guard.}
{101}{}{You see a well-armed person with a cruel look in their eyes.}
{110}{}{Ves a un Hubologista.}
{111}{}{Él está mirando a los distintos equipos de computación antes de él.}
{200}{}{Somos leales a AHS-9.}
{201}{}{The Star Father cares for all of us.}
{202}{}{Es aburrido aquí, pero es nuestro trabajo para ver más de las donaciones.}
{203}{}{Greetings friend.}
{300}{}{Don't mess with anything.}
