{100}{}{Ves a Algernon, un imbécil.}
{101}{}{Ves a Algernon.}
{150}{}{Ves a un sucio imbécil. Está meciendo los pies y haciendo ruiditos
 susurrantes para sí mismo.}
{151}{}{Ves a Algernon. Parece que esté jugando a Missile Command en su cabeza.}
{200}{}{Pew Pew}
{201}{}{¡Thoom!}
{202}{}{¡Zark! ¡Zark!}
{203}{}{¡Sssssshhhhhhuuuu... *BOOM!*}
{204}{}{¡Zap!}
{205}{}{¡Boooom! ¡Budda-budda-boom!}
{206}{}{Budda-budda-budda}
{207}{}{Budda-budda-budda}
{208}{}{¡Blammo! ¡Blam blam blam!}
{209}{}{¡Blam!}
{210}{}{¡Ptow! ¡Ptow!}
{211}{}{¡Phooom!}
{212}{}{¡Kablooie!}
{213}{}{Ratta-tatta-tatta}
{214}{}{Kaa-booom}
{220}{}{(Algernon te mira y de ofrece una sonrisa desdentada) ¡Boom! }
{221}{}{(El joven imbécil te mira con una sonrisa desdentada. Cosida en su camisa hay una pequeña etiqueta que pone "Algernon"
 en letra cursiva) ¡Boom! }
{222}{}{(Cuando ve tus armas, empieza a señalarlas excitado) ¡Boom!}
{223}{}{¡Boom!}
{224}{}{Te marchas.}
{225}{}{Eh... ¿quieres una de estas armas?}
{226}{}{Sí, un "boom" para ti también. Algernon, ¿puedes mejorar alguna de las cosas que tengo aquí?}
{227}{}{Eh, nada de "boom" ahora mismo, gracias. Adiós.}
{230}{}{¡Hunh! ¡Huh-huh! (Algernon ríe entre gorgojeos, y después te apunta con su dedo como si fuera un arma) ¡Blam Blam!}
{231}{}{¡Fallaste, Fallaste! ¡Toma esto! (Le apuntas con el dedo como si fuese una pistola) ¡POW! ¡POW!}
{232}{}{Ugh. Yo muerto. Ahora voy a lugar mejor.}
{235}{}{(Algernon dibuja una expresión sorprendida en su rostro, y después mira lentamente al lugar donde tú le has 'disparado'. De repente
 se tambalea, pone los ojos en blanco y cae al suelo, muerto)}
{236}{}{Eh, ¿Al? ¿Tú bien?}
{237}{}{Uh-oh.}
{240}{}{(No se mueve)}
{241}{}{(Le das unas palmadas)}
{245}{}{(No se levanta. Ni siquiera respira)}
{250}{}{(¿Qué quieres darle?)}
{251}{}{Dale una de tus pistolas.}
{252}{}{Dale uno de tus rifles.}
{253}{}{Dale tu combustible de lanzallamas.}
{254}{}{Dale una de tus armas mano a mano.}
{255}{}{Lo siento, creo que no tengo nada para darte, Al. Quizá la próxima vez.}
{256}{}{En realidad, no creo que darle cualquier clase de arma a lo que sin duda es un tarado sea una buena idea. Divertido, quizá, inteligente, no. Más tarde.}
{260}{}{(Al toma el objeto, y se le ilumina la mirada. Juguetea con él unos minutos, luego unos minutos más,
 luego otros más… una hora después, Al te lo devuelve asintiendo con la cabeza y con una sonrisa malvada) *Booooooom.*}
{261}{}{Dime... ¿puedes actualizar ESTO?}
{262}{}{Gracias, Al.}
{265}{}{[¿Cuál?]}
{266}{}{¿Tu .44 Mágnum?}
{267}{}{Tu Desert Eagle.}
{268}{}{Tu pistola láser Wattz 1000.}
{269}{}{Tu pistola de plasma Glock 86.}
{270}{}{Buscas en tu mochila y le das cualquier cosa...}
{271}{}{No importa, Al. Nos vemos.}
{272}{}{No importa, muchacho... no hay juguetes para ti hoy. Adiós.}
{276}{}{Tu rifle de caza Colt.}
{277}{}{Tu rifle de asalto AK-112.}
{278}{}{Tu FN FAL.}
{279}{}{Tu rifle láser Wattz 2000.}
{280}{}{Tu lanzallamas Flambe 450.}
{281}{}{Tu rifle de plasma.}
{291}{}{¿Quieres un trago de combustible para lanzallamas?}
{292}{}{Aquí hay algo de combustible para lanzallamas. ¿Puedes hacer algo con ello?}
{301}{}{Le das tu picana. Eh... después de asegurarte de que la toma por la empuñadura.}
{302}{}{Su BeatCo "Más Grande Frigger" El Poder Del Puño.}
{400}{}{Yo matado Al. Mejor marcho de aquí}
