{100}{}{Ves a un brahmin aparentemente enfermo.}
{150}{}{Ves a un brahmin enorme y aparentemente enfermo. Su tripa parece dilatada y sus ojos están inyectados en sangre.}
{151}{}{Ves a un brahmin enorme y aparentemente enfermo. Su tripa parece dilatada y sus ojos están inyectados en sangre. Parece muy enfermo. Quizá haya alguna forma de ayudarlo.}
{198}{}{::Rnnnrrrrr?::}
{199}{}{::Hrrnnnnr?::}
{200}{}{Moo}
{201}{}{Mooooooooo}
{202}{}{Moooo}
{203}{}{::Rnnr::}
{204}{}{::Rnnnrrrrr!!!::}
{205}{}{::Gnnnnnrrrr!!!::}
{206}{}{::Hrrnnnnr!!!::}
{225}{}{Has sacado algo que estaba alojado en el intestino del brahmin.}
{235}{}{Hay algo alojado en el intestino del brahmin, pero no has conseguido sacarlo.}
