{100}{}{Ves al vigilante de sala del casino.}
{150}{}{Ves a un hombre bien vestido. Está supervisando el casino.}
{200}{}{Eh… debes quitarte esa armadura.}
{210}{}{Eh, ¿por qué está andando a hurtadillas, señor?}
{220}{}{Eh, ¿por qué está andando a hurtadillas, señora?}
{230}{}{Buenas tardes, [MM], señor.}
{240}{}{Buenas tardes, [MM], señora.}
{250}{}{Buenos días, [MM], señor.}
{260}{}{Buenos días, [MM], señora.}
{270}{}{Amigo, estás entrando en el casino equivocado.}
{280}{}{Señor, lo siento, tendrá que guardar ese arma.}
{290}{}{Señora, lo siento, tendrá que guardar ese arma.}
{300}{}{Cariño, lo siento, pero no puedes llevar armas en el casino. [Sonríe]. Ya eres lo bastante letal así.}
{310}{}{Cariño, con un cuerpo como ese, no podrás andar a hurtadillas por ninguna parte.}
{320}{}{Tribal, será mejor que guardes ese arma *ahora mismo*.}
{330}{}{Tribal, será mejor que dejes esa mierda de andar a hurtadillas *ahora mismo*.}
{340}{}{[A Myron] Hey, hey… ¡Myron! Hace mucho tiempo que no te veía fuera del laboratorio.}
{350}{}{[Señala a Marcus]. Nada de mutantes. Que espere fuera.}
{360}{}{Nada de droides.}
{370}{}{Se supone que no puedo charlar estando de servicio, pero me alegra que le patearas el culo al Enclave.}
{380}{}{Se necesitan más fichas en la mesa tres…}
{390}{}{Se necesitan más fichas en la mesa tres…}
{400}{}{¡Oye, [X]! ¡He oído que fuiste tú quien envió al Enclave de una patada hasta la Edad de Piedra! [Su tono se vuelve formal]. Me han dado instrucciones de entregarte algunas fichas, cortesía del casino. Disfrútalas, caballero.}
{420}{}{Hey, mirad quién está aquí! Hola, [PS]. [Sonríe]. Te doy la bienvenida a [CN]. Me encantan tus películas.}
{440}{}{Dispara. ¿Qué quieres saber?}
{460}{}{Eh, será mejor que se vaya ahora mismo, señor.}
{470}{}{Sí, tu mamá dijo que yo también era especial. Y ahora haz una excursión… quizá ella esté en alguna parte de la calle Virgin.}
{480}{}{Soy el vigilante de sala. [Parece un poco irritado]. ¿Qué puedo hacer por ti?}
{490}{}{El [CN]. Si necesitas algo, tan solo pregunta.}
{500}{}{Es el jodido mejor casino de la ciudad… pero soy un poco parcial. [Ríe]. ¿Quieres saber algo más?}
{510}{}{A la Familia [CA]. Insuflaron vida a este lugar, lo convirtieron en un auténtico punto de referencia de las noches, en una brillante joya en Nuevo Reno.}
{520}{}{¿Ese tipo? ¿El Viejo McGee? El loco hijo de perra… ha estado jugando en esa máquina durante los últimos años, esperando el gran premio. Toda su fortuna debe estar dentro de esa cosa, pero no le devolverá ni una sola ficha.}
{530}{}{[Niega con la cabeza]. Qué va, sólo es testaruda… igual que él. [Se encoge de hombros]. Probablemente podría repararse, pero no tenemos mecánicos de tragaperras que puedan arreglar esa maldita cosa.}
{540}{}{Sí, ese hijo de puta estuvo aquí hace una semana, desplumó unas mil fichas a una de las mesas, y luego se largó. No sé dónde está ahora, pero solía tener una habitación en el Desperado.}
{550}{}{¿Nikki? [Comprueba la estancia]. Sí, está por allí, en la mesa central. ¿Hay alguna clase de problema?}
{560}{}{Su nombre *era* Nikki. Solía trabajar aquí, pero se la cargaron… no hace mucho.}
{570}{}{Se llamaba Nikki. Solía trabajar aquí, pero se largó hace poco tiempo. Hizo las maletas y desapareció.}
{580}{}{Claro, sería bueno para el negocio. El vestuario está en la parte de atrás…}
{590}{}{[Niega con la cabeza]. No, todavía nos estamos recuperando de tu última actuación. A lo mejor te interesa probar en alguno de los otros casinos.}
{600}{}{Parece que este no va a ser un mal negocio después de todo. [C] = fichas. No, nada malo.}
{610}{}{Sí, apesta más que la mierda de brahmin. Aún así, ¿tú…? [Te mira de arriba abajo con escepticismo]. Bueno, qué demonios. Un poco de improvisación no hará daño, aunque es un público difícil… espero que lo hagas bien.}
