{100}{}{Ves una caja fuerte asegurada en la pared. Está cerrada.}
{150}{}{Ves una caja fuerte asegurada en la pared. Está abierta.}
{200}{}{(Hay una pequeña puerta en la pared. ¡Ahí debe vivir una personita diminuta! Hay una rueda con números en el medio de la puerta).}
{220}{}{(Se escucha un CLIC, y la caja se abre).}
{230}{}{(Una inspección de cerca revela un pequeño cubo de explosivo plástico situado en el muro justo bajo la caja, preparado para saltar si el usuario introduce una combinación incorrecta. Estaba cubierto con una fina capa de yeso para disimular).}
{240}{}{(Giras la rueda lentamente durante varios minutos, pero no consigues nada).}
{250}{}{(No encuentras ninguna trampa en la caja).}
{260}{}{(Estás girando la rueda... ¡cuando de repente se escucha un CLIC, y la puerta se abre!)}
{270}{}{(¡Giras la rueda, pero la puertecita no se quiere abrir!)}
{290}{}{(No escuchas a nadie, y no ves ningún timbre. Quizá no hay nadie en casa).}
{300}{}{(Con precisión quirúrgica, desarmas el fusible y sacas el explosivo plástico de la pared. Ahora la trampa está desarmada).}
{310}{}{(Con precisión quirúrgica, abres el cebo y reajustas el disparador de la combinación. El propietario de esta caja se llevará
 una sorpresa cuando intente abrirla de nuevo).}
