{100}{}{Ves un terminal.}
{101}{}{Ves un terminal. Parece estar operativo.}
{102}{}{Ves un SmarTerminal DataPlex 2000, con 64k de RAM, lo último de lo último en tecnología de computadoras: qué mala suerte que ahora mismo no funcione.}
{103}{}{Ves un SmarTerminal DataPlex 2000, con 64k de RAM, lo último de lo último en tecnología de computadoras.}
{104}{}{Bienvenido a PoseidoNet. Introduce selección de Menú:}
{105}{}{Acceder.}
{106}{}{Ayuda.}
{107}{}{Finalizar sesión.}
{108}{}{Este terminal está reproduciendo una película india, pero es realmente aburrida.}
{109}{}{Este terminal está reproduciendo un programa de disparo sobre objetivos. Todo lo que puedes ver es una diana.}
{110}{}{Este terminal está mostrando alguna clase de arte moderno: una obra con diferentes barras de colores.}
{111}{}{Ves un terminal. Está mostrando pequeñas bombas verdes moviéndose en diagonal mientras cruzan la pantalla.}
{112}{}{Este terminal muestra un mensaje: "Ahora puede apagar el equipo". Te preguntas qué significa.}
{113}{}{Ves una imagen de puntos de luz rojos, verdes y azules combinándose para dibujar una imagen de algo…}
{114}{}{Un rostro horrible te está mirando. Oh, espera, este terminal está apagado.}
{115}{}{Esta ventana conduce a una oscura dimensión más allá del tiempo y el espacio.}
{116}{}{Este terminal tiene un mensaje; "la Carga de la Fenestra '98." El terminal está cubierto con una gruesa capa de polvo.}
{117}{}{Este terminal parece de la marca Apricot. Está ejecutando algo llamado Fallout 3. Caray, parece que es multijugador y en 3D.}
{118}{}{Introducir identificador de usuario:}
{119}{}{(Déjame probar esto) Lista de usuarios.}
{120}{}{(Me pregunto si esto funcionará) Smith, J.}
{121}{}{Atrás.}
{123}{}{Creo que será mejor hacer esto en algún otro lugar.}
{124}{}{Listado (el terminal muestra una lista de unos 500 nombres).}
{125}{}{Listado (el equipo muestra una lista de nombres).}
{126}{}{Seleccionar ID de usuario o Desconectarse:}
{127}{}{(Este tiene un acceso adecuado). Smith, J.}
{128}{}{(Esto se ve, por tipo especial.) Presidencial Clave De Seguridad Anular.}
{129}{}{(Este es mejor que el acceso medio). Murray, T.}
{130}{}{(Este tiene un buen acceso). Curling, Dr. C.}
{131}{}{(Este parece que debería tener un acceso realmente bueno). Bird, D.}
{132}{}{(Quizá debería intentarlo más tarde). Finalizar sesión.}
{133}{}{Seleccionar: }
{134}{}{O. C. N.: Operaciones de la central nuclear, }
{135}{}{¿Estado de seguridad?}
{136}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{137}{}{Estado de seguridad.}
{138}{}{Volver al ID de Usuario:}
{139}{}{Seleccionar: }
{140}{}{Nivel de seguridad: Estado actual, }
{141}{}{Unidad de guerra química: Informe de estado de proyecto, }
{142}{}{O. C. N.: Operaciones de la central nuclear, }
{143}{}{¿Estado de seguridad?}
{144}{}{Nivel de seguridad: Estado actual}
{145}{}{Descargar Unidad de guerra química: Informe de estado de proyecto}
{146}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{147}{}{Estado de seguridad.}
{148}{}{Volver al ID de Usuario:}
{149}{}{Seleccionar: }
{150}{}{Estado de la Nación: Estado actual, }
{151}{}{Listado de Términos, }
{152}{}{Nivel de seguridad: Estado actual, }
{153}{}{Unidad de guerra química: Informe de estado de proyecto, }
{154}{}{O. C. N.: Operaciones de la central nuclear, }
{155}{}{¿Estado de seguridad?}
{156}{}{Estado de la Nación: Estado actual}
{157}{}{Descargar lista de palabras.}
{158}{}{Nivel de seguridad: Estado actual}
{159}{}{Descargar Unidad de guerra química: Informe de estado de proyecto}
{160}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{161}{}{Estado de seguridad}
{162}{}{Volver al ID de Usuario:}
{163}{}{Seleccionar: ¿Estado de seguridad?}
{164}{}{Estado de seguridad}
{165}{}{Final De Acceso.}
{166}{}{Error de descarga - falta el archivo de Estado de Seguridad.}
{167}{}{Estado de la Nación: Estado actual}
{168}{}{Descargar lista de palabras.}
{169}{}{Nivel de seguridad: Estado actual.}
{170}{}{Descargar Unidad de guerra química: Informe de estado de proyecto}
{171}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{172}{}{Volver al ID de Usuario:}
{173}{}{Descarga completa.}
{174}{}{Descargar lista de palabras.}
{175}{}{Nivel de seguridad: Estado actual.}
{176}{}{Descargar Unidad de guerra química: Informe de estado de proyecto}
{177}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{178}{}{Estado de seguridad.}
{179}{}{Volver al ID de Usuario:}
{180}{}{Descarga completa.}
{181}{}{Estado de la Nación: Estado actual}
{182}{}{Nivel de seguridad: Estado actual.}
{183}{}{Descargar Unidad de guerra química: Informe de estado de proyecto}
{184}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{185}{}{Estado de seguridad.}
{186}{}{Volver al ID de Usuario:}
{187}{}{Nivel del cuartel de la guardia: Torretas de seguridad actualmente en estado Alerta Armada.}
{188}{}{Nivel del cuartel de la guardia: Torretas de seguridad actualmente en estado Normal.}
{189}{}{Nivel del cuartel de la guardia: Torretas de seguridad actualmente en estado Desactivación por Mantenimiento.}
{190}{}{Nivel de celdas de sujetos de prueba: Torretas de seguridad actualmente en estado Alerta Armada.}
{191}{}{Nivel de celdas de sujetos de prueba: Torretas de seguridad actualmente en estado Normal.}
{192}{}{Nivel de celdas de sujetos de prueba: Torretas de seguridad actualmente en estado Desactivación por Mantenimiento.}
{193}{}{Área de Proyectos de Investigación y Desarrollo: Torretas de seguridad actualmente en estado Alerta Armada.}
{194}{}{Área de Proyectos de Investigación y Desarrollo: Torretas de seguridad actualmente en estado Normal.}
{195}{}{Área de Proyectos de Investigación y Desarrollo: Torretas de seguridad actualmente en estado Desactivación por Mantenimiento.}
{196}{}{Área de oficinas ejecutivas: Torretas de seguridad actualmente en estado Alerta Armada.}
{197}{}{Área de oficinas ejecutivas: Torretas de seguridad actualmente en estado Normal.}
{198}{}{Área de oficinas ejecutivas: Torretas de seguridad actualmente en estado Desactivación por Mantenimiento.}
{199}{}{Nivel de Información y central nuclear: Torretas de seguridad actualmente en estado Alerta Armada.}
{200}{}{Nivel de Información y central nuclear: Torretas de seguridad actualmente en estado Normal.}
{201}{}{Nivel de Información y central nuclear: Torretas de seguridad actualmente en estado Desactivación por Mantenimiento.}
{202}{}{Ajustar el nivel de seguridad.}
{203}{}{Estado de la Nación: Estado actual}
{204}{}{Descargar lista de palabras.}
{205}{}{Descargar Unidad de guerra química: Informe de estado de proyecto}
{206}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{207}{}{Estado de seguridad.}
{208}{}{Volver al ID de Usuario:}
{209}{}{Descarga completa.}
{210}{}{Descargar el Estado de la Nación: el estado Actual.}
{211}{}{Descargar lista de palabras.}
{212}{}{Nivel de seguridad: Estado actual}
{213}{}{Descargar O. C. N.: Operaciones de la central nuclear}
{215}{}{Estado de seguridad.}
{216}{}{Volver al ID de Usuario:}
{217}{}{Descarga completa.}
{218}{}{Descargar el Estado de la Nación: el estado Actual.}
{219}{}{Descargar lista de palabras.}
{220}{}{Nivel de seguridad: Estado actual}
{221}{}{Descargar Unidad de guerra química: Informe de estado de proyecto}
{222}{}{Estado de seguridad.}
{223}{}{Volver al ID de Usuario:}
{224}{}{Este terminal está ejecutando actualmente un diagnóstico de alto nivel. Por favor, pruebe otro terminal. Gracias.}
{225}{}{Bienvenido al sistema de ayuda de PoseidoNet. Lamentamos que nuestros ficheros de ayuda estén actualmente desactualizados, y no disponibles. ¿Buscar actualización de ficheros de ayuda? (S/N)}
{226}{}{Sí.}
{227}{}{No, Atrás.}
{228}{}{Actualización de ficheros de ayuda no disponibles con la versión de prueba de PoseidoNet. Por favor, adquiera la versión completa para tener acceso total a todas las nuevas actualizaciones. Su período de prueba para PoseidoNet está caducado desde hace 59.439 días.}
{229}{}{Volver a Iniciar sesión.}
{230}{}{Finalizar sesión.}
{231}{}{Clave de acceso presidencial de anulación de seguridad: Anulación de seguridad requiere clave única de acceso presidencial. Opciones permitidas: Medidas anti-insurrección, Cierre de emergencia de sistemas defensivos.}
{232}{}{(Le echaré un vistazo a esto). Medidas anti-insurrección.}
{233}{}{(Le echaré un vistazo a esto). Cierre de emergencia de sistemas defensivos.}
{234}{}{(Quizá debería probar algo menos evidente). Volver al ID de Usuario.}
{235}{}{(No creo que quiera liarme con esto ahora mismo). Finalizar sesión.}
{236}{}{Medidas anti-insurrección. En caso de rebelión armada, La llave de seguridad presidencial permite activar los sistemas de seguridad para atacar a todas las unidades previamente leales pero ahora amenazantes, en una zona determinada. Los sistemas defensivos están programados para atacar a los enemigos más peligrosos en primer lugar. ¡Advertencia! Nivel operativo actual: sólo niveles de acceso!}
{237}{}{(Eso parece útil). Activar Protocolo de medidas anti-insurrección.}
{238}{}{(Quizá le de una oportunidad en otro momento). Atrás.}
{239}{}{(Ahora mismo no quiero seguir jugando con la computadora). Finalizar sesión.}
{240}{}{Llave de seguridad presidencial reconocida. Buenos días, señor Presidente... Protocolo de medidas anti-insurrección iniciado... Objetivo adquirido.}
{241}{}{(Creo que voy a volver a ver qué sucede).}
{242}{}{Llave de seguridad presidencial reconocida. Buenos días, señor Presidente... Protocolo de medidas anti-insurrección iniciado... **Error de funcionamiento**... Enlace de seguridad desconectado en este nivel. Por favor, envíe el formulario FG-I-106-32-0635 para la autorización de servicios de reparación. Gracias por usar otro excelente producto Vault-Tec. Buenos días.}
{243}{}{(Quizá funcione en los niveles de acceso. Hmm, eso debe significar la zona justo antes del muelle. Voy a tener que probarlo allí). Volver al ID de Usuario.}
{244}{}{(Me pregunto qué más puedo probar). Atrás.}
{245}{}{Llave de seguridad presidencial requerida para acceder a esta función. Llave no encontrada.}
{246}{}{(Me pregunto qué más puedo probar). Atrás.}
{247}{}{Cierre de emergencia de sistemas defensivos apaga temporalmente los sistemas de seguridad activos a la par y a un intervalo regular. El apagado inicia un procedimiento de diagnóstico de alto nivel antes de comenzar un reinicio automático de los sistemas de seguridad.}
{248}{}{(Eso parece algo que sería interesante probar). Activar Cierre de emergencia de sistemas defensivos.}
{249}{}{(Hmm, Quizá le de una oportunidad en otro momento). Atrás.}
{250}{}{(Ahora mismo no quiero seguir jugando con la computadora). Finalizar sesión.}
{251}{}{Llave de seguridad presidencial reconocida. Buenos días, señor Presidente... Cierre de emergencia de sistemas defensivos iniciado... ejecutando diagnóstico de alto nivel. Alpha... Bravo... Charlie...}
{252}{}{(Por alguna extraña razón, no me parece que quiera hacer esto ahora mismo). Atrás.}
{253}{}{(Será mejor que me ponga en movimiento, mientras esta cosa sigue ejecutando ese diagnóstico). Finalizar sesión.}
{254}{}{Llave de seguridad presidencial no reconocida. Acceso denegado.}
{255}{}{(Hmm, me pregunto si le puedo hacer creer al escáner que tengo la llave pirateando el archivo de acceso. Creo que lo voy a intentar).}
{256}{}{(Oh, en fin, valía la pena intentarlo). Atrás.}
{257}{}{De seguridad de la Clave de acceso Escáner mal funcionamiento señaló... Reinicializar escáner...}
{258}{}{(Ese es mi oportunidad, ahora si sólo puedo llegar a pensar que es reconocido Presidencial Clave...)}
{259}{}{(Maldita sea, así que no arriesga...) de nuevo.}
{260}{}{Escáner reinicializado. Volver a recorrer...}
{261}{}{(Este es el momento clave).-Escribes febrilmente.}
{262}{}{Detectado procedimiento ilegal. Denegados futuros accesos a este terminal… enviada alerta de mantenimiento.}
{263}{}{Maldición. Eso no es en absoluto lo que quería.}
{264}{}{Llave de seguridad presidencial reconocida. Buenos días, señor Presidente. (¡Sí! Ahora veamos lo que puedo hacer...)}
{265}{}{(¿Qué otra cosa puedo hacer?)}
{266}{}{De la Seguridad presidencial Clave reconocidos. Buen día, Señor Presidente... de Emergencia contrainsurgencia Protocolo iniciado... **Error** Meta que no se encuentra. Por favor, asegúrese de que los sensores funcionan correctamente. Si no, por favor envíe el formulario de FG-I-106-32-0635 para autorizar los servicios de reparación. Gracias por usar otra multa de Vault-Tec producto. Buen día.}
{267}{}{(Hmm... Quizá funcione cuando haya alguien allí. Voy a tener que probarlo más tarde). Volver al ID de Usuario.}
{268}{}{(Me pregunto qué más puedo probar). Atrás.}
