{100}{}{Ves a un hombre vestido con ropa de trabajo.}
{101}{}{Es comprador brahmin. Está esperando la caravana de Hal.}
{102}{}{Huele a brahmin.}
{113}{}{Vaya, todo se ha ido a la mierda! Me temo que no hay dinero en este viaje para ninguno de nosotros. Podemos estar contentos de seguir vivos.}
{114}{}{Bueno, los rancheros no están demasiado contentos: por el viaje nos dan 1.000 dólares. Mala suerte.}
{115}{}{Bien, tuviste mala suerte, pero lo hiciste bien. Aquí están los $2000 dólares por lo acordado.}
{116}{}{¡Cojones, lo hiciste simplemente bien! Aquí hay un bono de 1.000 dólares para ti. Eso, y 2.000 dólares son tu paga. ¡Redding, ándate con ojo esta noche!}
{118}{}{Eres la peor parodia de guardia que haya visto nunca. Lárgate de aquí.}
{119}{}{Que mal que Hal no lo logró.}
{120}{}{Lástima lo del Hal.}
{121}{}{Me alegra hacer negocios contigo.}
{213}{}{¡Vaya, Hal está muerto! ¡Y todo se ha ido a la mierda! Me temo que no habrá dinero para ninguno de nosotros. Podemos estar contentos de seguir vivos.}
{214}{}{¡Vaya, Hal está muerto! Y los rancheros no están contentos - tan solo $1000 dólares. Mala suerte.}
{215}{}{¡Maldita sea, Hal está muerto! Al menos los brahmin están bien. Aquí están los $2000 por lo acordado.}
{216}{}{¡Maldita sea, Hal está muerto! Aún así, te las arreglaste bien. Hay un bono de $1000 para ti. Eso y $2000 hacen tu paga. ¡Será mejor que Redding tenga cuidado esta noche!}
