{100}{}{Las criaturas venían del nordeste. No debería ser difícil rastrearlas hasta su nido. (Salir por el nordeste.)}
{101}{}{Vaya, esto sí que es aburrido. Espero que suceda algo.}
{102}{}{Mira qué hora es...}
{103}{}{Hmmm, esto abuuurre.}
{104}{}{Zzzz...Zzz... huhh, qu...?}
{105}{}{Mira - humano protege brahmin.}
{106}{}{Gruthar dice nosotros irnos. No herir humano.}
{107}{}{Mira. }
{108}{}{. Nosotros irnos.}
{109}{}{Raro. ¿Las cosas malas hablan?}
{110}{}{¿Garras mortales parlantes? Esto es de locos...}
