{100}{}{Supones que incluso con el pelo verde y el ceño fruncido, es la camarera de este antro.}
{101}{}{Esa es Mira. Está mezclando un Radesperdicio.}
{102}{}{Bien, es joven y atractiva, pero hay algo en su mirada que dice que no aguanta mierdas de nadie. La mirada, y las nudilleras de pinchos que lleva en una cadena alrededor de su cuello.}
{103}{}{Me llamo Mira. ¿Qué va a a ser, forastero?}
{104}{}{Hola otra vez. ¿Qué va a ser?}
{105}{}{Bebida.}
{106}{}{¿Refugio 13?}
{107}{}{GECK?}
{108}{}{No me importa. Dame el especial de la casa.}
{109}{}{Dame una cerveza.}
{110}{}{Información.}
{111}{}{Estoy buscando trabajo.}
{112}{}{¡Bien, no eres el único! Es sólo la forma en que me gustan.}
{113}{}{¿Has vuelto?}
{114}{}{Yubba.}
{115}{}{Vaya... te has encargado de Lenny. ¡Impresionante! Toma una copa a cuenta de la casa.}
{116}{}{Lo que hiciste con Lenny... ¡era malvado!}
{117}{}{Oh, un conversador impresionante. ¿Qué vas a tomar? ¿Un Radesperdicio? Sólo diez pavos.}
{118}{}{Sí.}
{119}{}{No.}
{120}{}{¿Quieres comprar una bebida? 10 dólares.}
{121}{}{Sí.}
{122}{}{No.}
{123}{}{¡Sirviendo un Radesperdicio! 10 dólares.}
{124}{}{Vale.}
{125}{}{¿Diez pavos? Demasiado para mí.}
{126}{}{Claro, un pavo.}
{127}{}{Vale.}
{128}{}{Demasiado dinero para mí.}
{129}{}{Puedes probar con Merk, en la sala de ahí atrás.}
{130}{}{Aquí no hay nada para ti, forastero.}
{131}{}{Gracias, supongo.}
{132}{}{¿Y entonces qué, forastero?}
{133}{}{¿Refugio 13?}
{134}{}{GECK?}
{135}{}{¿Tienes algo de tiempo para unas preguntas?}
{136}{}{Marcho, adiooos.}
{137}{}{Eso es todo.}
{138}{}{¡Largo de aquí, gorrón!}
{139}{}{Claro, tengo algo de tiempo. Eso es lo que se supone que hacen los camareros. Pero no te hagas ilusiones.}
{140}{}{Para ti, siempre tengo tiempo, corazón. ¿Qué quieres?}
{141}{}{Claro.}
{142}{}{Háblame sobre esta ciudad.}
{143}{}{¿Alguna vez has oído hablar del Refugio 13?}
{144}{}{Estoy buscando algo llamado GECK. ¿Sabes algo de eso?}
{145}{}{¿Cuál es el problema con ese tal Merk?}
{146}{}{Hay un policía en la ciudad que dice cosas bastante duras sobre ti. ¿Cuál es el problema?}
{147}{}{Bueno, eso acaba con nuestras suposiciones.}
{148}{}{Se llama RNC. Solía ser Arenas Sombrías, pero tras la muerte del Maestro, Aradesh y los demás fundaron la República. Ahora, RNC está justo en la frontera. Todo lo que hay al sur de aquí está bajo el mando de la República.}
{149}{}{Un consejo. No te ensucies las manos en la ciudad. Los tribunales no son demasiado amistosos con los de tu clase, si sabes a qué me refiero. Los Ciudadanos tienen más derechos que tú.}
{150}{}{Verás, eso es todo lo que tengo que decir al respecto.}
{151}{}{Hmm.}
{152}{}{Unas pocas preguntas más...}
{153}{}{Vaya, gracias. Recordaré eso.}
{154}{}{¿Eres otro de esos chiflados que buscan un tesoro perdido? Tienes que ir a ver a Bob el Trampero en el rancho de Westin. Siempre está hablando acerca de un tesoro. Aunque soportar sus historias sobrio es difícil.}
{155}{}{¿Trampero? Marcho yo.}
{156}{}{Unas pocas preguntas más...}
{157}{}{Vaya, gracias. Recordaré eso.}
{158}{}{Me dices cómo hacer la mezcla y te la haré.}
{159}{}{No bebida. GECK es... GECK.}
{160}{}{No es una bebida. Es un Kit de Creación del Jardín del Edén.}
{161}{}{Unas pocas preguntas más...}
{162}{}{Vaya, gracias. Recordaré eso.}
{163}{}{Es un gran tipo. Es mi jefe. ¿Qué esperas que diga?}
{164}{}{Unas pocas preguntas más...}
{165}{}{Vaya, gracias. Recordaré eso.}
{166}{}{Ese bastardo... no fue más que un divorcio problemático, eso es todo.}
{167}{}{Bien, ¿podemos hablar de otra cosa?}
{168}{}{Bueno, creo que me voy a ir.}
{169}{}{Oh, muy informativo. Mira, puedes probar con el doctor Henry en la ciudad, pero tengo otras cosas que hacer, Dumbo.}
{170}{}{¿Kit de Creación del Jardín del Edén? Suena a algo técnico. Puedes intentar buscar a Dorothy, la ingeniero de la ciudad. }
{171}{}{Unas pocas preguntas más...}
{172}{}{Vaya, gracias. Recordaré eso.}
{173}{}{Hmm... ¿trabajo? ¿Quieres trabajo? ¿Ayudar a Mira?}
{174}{}{Sí.}
{175}{}{No.}
{176}{}{Escucha: hombre malo hace daño a Mira. Hombre malo se llama Jack. Haces daño a hombre malo. Mira es como tú, y te da a ti arma bonita. ¿Bien?}
{177}{}{Sí.}
{178}{}{No.}
{179}{}{¡Bien! Mira tiene cuerda sobre muro. Vas por la noche. Encuentras la cuerda. Te cuelas. Vas al lugar grande por la puerta. Encuentras a Jack. Haces daño a Jack. Mira te da un arma.}
{180}{}{Vas por la noche. Encuentras la cuerda. Te cuelas. Vas al lugar grande por la puerta. Encuentras a Jack. Haces daño a Jack. Mira te da un arma. Ahora vete. Verme contigo... no bueno. Ayudas a Mira y vuelves. ¿Entendido?}
{181}{}{Mira ha oído que Jack recibió daño. Buen trabajo, Dumbo. Aquí está el arma, tú te la quedas. Gracias.}
{182}{}{Que te jodan a ti también. Nunca me libraré de ese bastardo.}
{183}{}{Tienes que hablar con Merk, pero no está aquí. Vuelve por la noche. Él prefiere las noches.}
{184}{}{No sé lo que le hiciste a Lenny, pero no me gustaría quedarme por aquí. No te va a hacer popular.}
{185}{}{Oye, te lo advertí. Oh, bueno...}
{186}{}{Eres Mira, ¿correcto? Cierto policía estaba diciendo algo sobre ti.}
{187}{}{¿Tú Mira? Jack Malo dice cosas.}
{188}{}{¿Ese bastardo de Jack? ¿Qué ha dicho ahora?}
{189}{}{Jack muerto. Hizo boom.}
{190}{}{Yo matado. Él hombre malo.}
{191}{}{No me preocuparía por ello. Está muerto. Se voló por los aires en la central eléctrica.}
{192}{}{Ahora no mucho. Lo he matado.}
{193}{}{¿Bromeas? Esa es la mejor noticia que he tenido en todo el día! Espero que su cerebro creara una bonita pintura para la pared. Ese maldito psicópata se lo merecía. Ten un Radesperdicio a mi cuenta.}
{194}{}{Gusta.}
{195}{}{Yo irme ahora.}
{196}{}{Gracias, supongo. Oye, ¿tienes un momento para una pregunta?}
{197}{}{Gracias. Sólo pensé que deberías saberlo.}
{198}{}{¿Lo hiciste? Oh, si no estuviera de servicio, saltaría por encima de esta barra y... bien, te besaría. El muy cabrón se lo merecía. De hecho, no se lo digas a nadie pero estaba esperando que algún tipo duro con pocas luces hiciera el trabajo por mí. Hasta tenía una pequeña recompensa guardada para ello.  Ahora es tuya: en lo que a mí respecta, te la has ganado.}
{199}{}{Gracias, supongo. Oye, ¿tienes un momento para una pregunta?}
{200}{}{Gracias. Sólo pensé que deberías saberlo.}
{201}{}{¡Dumbo, me has hecho la mujer más feliz de por aquí! Tengo un pequeño regalo para ti, justo aquí, tras la barra. Es todo tuyo.}
{202}{}{Me gusta Mira.}
{203}{}{Me gusta arma. Marcho yo, adiós.}
