{100}{}{Ves una puerta.}
{101}{}{Parece muy robusta.}
{102}{}{La puerta no parece ceder.}
{103}{}{(Notas un pequeño agujero en la puerta de donde parece proceder el sonido). ¿Hola?}
{104}{}{Uhh, ¿hola?}
{105}{}{¿Desde cuándo hablan las puertas?}
{106}{}{Uhh, hola.}
{107}{}{PEDAZO DE PANDILLA PROBLEMA.}
{108}{}{Click... (La puerta se desbloquea).}
{109}{}{Lo siento, no necesitamos nada de eso.}
{110}{}{La puerta está cerrada desde el otro lado. No parece haber nada de dónde agarrar.}
{111}{}{La puerta está pegada al marco y no hay lugar para colocar una trampa.}
{112}{}{La puerta cruje y se rompe por la presión.}
{113}{}{La puerta ya está desbloqueada.}
{114}{}{La puerta no te supone ningún desafío.}
{120}{}{¿Holla, Ra Ra?}
{121}{}{Jeje, puerta hablerta. ¡Hola!}
