{100}{}{You see a crate.}
{101}{}{A crate that appears to be full of stimpaks.}
{102}{}{Usted ve una caja llena de falsa inútil estimulantes.}
{200}{}{[Después de dar a la jaula de un breve vistazo, se determinó que hay cerca de cincuenta estimulantes en ello, al igual que el comerciante dijo.]}
{201}{}{[Examine them further.]}
{202}{}{[DONE.]}
{203}{}{Después de examinar de cerca, usted detecta nada inusual acerca de los estimulantes.}
{204}{}{[DONE.]}
{205}{}{Tras una inspección más cercana, estos estimulantes parecer un poco extraña para usted. Tome uno y rociar un poco de su líquido sobre la palma de su mano. Al oler el líquido carmesí, te das cuenta de lo que verdaderamente es: brahmán de la sangre.}
{206}{}{[DONE.]}
