{100}{}{You see an ancient looking tribal.}
{101}{}{You see the elderly chief of the tribe.}
{102}{}{[El viejo hombre fuma su pipa y la observa con ojos de color gris mate que parecen agujero en tu alma. Él mociones para que se sientan a través de él en el humo llena de tienda de campaña.] Gracias por traer a Kurisu de regreso a nuestro pueblo. [Toma un largo golpeó su pipa.] Los espíritus... tienen mucho que decir acerca de usted. Mucho, de hecho. Dime, ¿hay algo que usted necesita?}
{103}{}{[El viejo hombre fuma su pipa y la observa con ojos de color gris mate que parecen agujero en tu alma. Él mociones para que se sientan a través de él en el humo llena de tienda de campaña.] Estamos muy agradecidos por sus servicios, Errante. [Toma un largo golpeó su pipa.] Los espíritus... tienen mucho que decir acerca de usted. Mucho, de hecho. Dime, ¿qué te trae a nuestro pueblo?}
{104}{}{Welcome back, child. Was there something else you needed?}
{105}{}{What can this old man do for you?}
{106}{}{I am on a quest for the Holy GECK. Do you know anything about this?}
{107}{}{Estoy en busca de una mujer desaparecida. Ella es la hermana de mi amigo, Sulik.}
{108}{}{Is there anything else that needs to be done around here?}
{109}{}{No importa. Adiós.}
{110}{}{El Santo GECK... [Él toma un largo golpeó su pipa.] Hay una criatura que a veces nos cazar, a veces, caza de nosotros. Un gecko. No, tengo la sensación de que no es lo que usted busca. Me temo que tu Santo GECK está más allá de mi ken.}
{111}{}{Déjame hacerte otra pregunta.}
{112}{}{That's all I need to know. Bye.}
{120}{}{Sulik? [Él asiente con la cabeza.] Uno de nuestros mejores hombres. Igualmente hábiles en el arte de la caza, y el arte de la comunión con bonespirits. Él nos dejó para encontrar a su hermana, Kurisu, que nunca regresó de una cercanos de la tribu. Dime, hijo, ¿dónde está Sulik ahora?}
{121}{}{Oh, él está aquí. Hey, Sulik, ven aquí...}
{122}{}{Oh, él está bien. Yo le dije a esperar aunque tengo algunas cosas que hacer.}
{123}{}{Lo siento, pero está muerto.}
{124}{}{[Sulik y la tribu del jefe de intercambiar saludos.] Me da gran placer ver Sulik de nuevo. El bonespirits me dijo que había caído en problemas. Pero lo de su hermana, Kurisu?}
{125}{}{Es bueno saber que Sulik está bien. Estábamos preocupados de que él se metió en problemas. Así, su hermana que aún falta?
 Ella es también un miembro de nuestra tribu.}
{126}{}{[Él frunce el ceño y fuma su pipa en silencio por un largo tiempo. Sólo cuando se considere la posibilidad de salir. Finalmente habla.] El espíritu era fuerte con Sulik. Siempre he pensado, que un día podrían tomar mi lugar. Ahora, puedo ver a los espíritus tenía otros planes para Sulik. Pero lo de su hermana, Kurisu?}
{127}{}{Fue capturado por traficantes de esclavos. He ofrecido Sulik asistencia en la localización de ella. ¿Sabe usted algo que podría ayudar en la búsqueda?}
{128}{}{[Él cierra sus ojos por un largo tiempo. Tal como usted piensa que podría haber dormido, él comienza a hablar.] Los traficantes de esclavos son guiados por un hombre con un alma oscura. Metzger. Él habita en una de las ruinas de las cáscaras de la Vieja de las ciudades. La llaman la Den. [Abre los ojos.] Tal vez, él es la celebración de allí. El bonespirits decir nada más.}
{129}{}{Gracias. Deja que te pregunte algo más.}
{130}{}{Gracias, hijo, pero estoy contento. Tal vez otros no lo son tanto. Pida a los alrededores de la aldea.}
{140}{}{I look for GECK.}
{141}{}{I looking for missing woman. She sister of friend Sulik.}
{142}{}{Adiós.}
{150}{}{I ask more.}
{160}{}{Oh, él aquí. Sulik, jefe hombre quiere hablar.}
{161}{}{Oh, bueno. Él espera de mí.}
{162}{}{I sorry. He dead.}
{170}{}{Sí, los hombres malos, la tengo. Me ayuda Sulik. Usted sabe de donde es ella?}
{200}{}{Your evil ends here, slaver!}
{300}{}{[El viejo hombre fuma su pipa y los observa con gris opaco ojos que parecen agujero en tu alma. Él mociones para que se sientan a través de él en el humo llena de tienda de campaña.] Usted ha hecho una gran obra, niño. Oigo los gritos de muchos impíos bonespirits perdieron en la Gran Agua Salada. Ahora que has demostrado a ti mismo, que puedo compartir con ustedes el gran secreto final.}
{301}{}{Alright, finally! Let's hear it.}
{302}{}{Not interested, old man. Bye.}
{310}{}{[Toma un gran éxito fuera de su pipa, a continuación, cierra sus ojos. Después de un momento, él asiente con la cabeza.] Sí. Veo que el Gran Oso espíritu ha guiado su búsqueda, dando nueva vida a viejos huesos. Otros también. Quizás han venido a usted en una visión. Vienen de lejos, muy lejos... donde los mutantes no son permitidos.}
{311}{}{¿De qué demonios estás hablando?}
{312}{}{Sí, sí, tengo el Star Wars encuentro especial. No me digas que ese es el gran secreto final.}
{320}{}{El último secreto... el secreto más grande en todo el juego... es decir, [Como lo hace una pausa dramática, él toma otro golpe fuera de su pipa. De repente, el tubo se desliza de sus manos y cae en sus ropas, al instante de la ignición de él en llamas.]}
{321}{}{Fuck!}
