{100}{}{Usted ve un gordito comerciante con un parche.}
{101}{}{One-Eyed Roy le observa fijamente con su ojo bueno mientras se seca el sudor de su frente.}
{200}{}{[Como usted y Krom enfoque al sitio de la reunión, que es recibido por un gordito comerciante con un parche y un
 pequeño séquito de guardaespaldas. A pesar de que el comerciante está sudando mucho, él parece francamente alegre.]}
{201}{}{[MÁS]}
{202}{}{[Después de que el comerciante le da Krom un entusiasta saludo, se dirige a usted y se ve más. A pesar de su sonrisa
 nunca se tambalea, su mirada penetrante traiciona un indicio de sospecha.] Así Krom aquí dice que tengo que hacer negocios con usted el día de hoy.
 [Él se encoge de hombros.] La gente me llame Tuerto Roy, pero no puedo por la vida de averiguar por qué. [Ríe a carcajadas en su broma.]
 ¿Cuál es tu nombre, amigo?}
{203}{}{Soy }
{204}{}{ de Arroyo.}
{205}{}{. Ahora vamos a esta marcha.}
{210}{}{Un verdadero placer para meetcha, }
{211}{}{. Si no te importa me dijo, usted es un poco de un extraño tipo de tribal.}
{212}{}{Yo no soy tu media tribales. De hecho, yo soy el Elegido.}
{213}{}{No sé a qué te refieres. Yo sólo soy el promedio de Joe Tribales. Nada de extraño acerca de mí en absoluto.}
{214}{}{Oh, porque de lo que estoy usando? Usted ve, yo estoy tratando de establecer un nuevo tribal tendencia de la moda. Estoy cansado de los mismo ol'
 brahmán ocultar los pantalones con una correa en el pecho. Esa mirada es *tan* 2240.}
{215}{}{A quién llamas "un poco extraño", que tubby tuerto hijo de puta? [Ataque.]}
{220}{}{[Su sonrisa se tambalea un poco y él asiente con la cabeza.] Bien, a los negocios, a continuación,. Dime, amigo, ¿alguna vez has escuchado
 de un pequeño artículo llamado... un estimulante? [Como él dramáticamente habla de la última palabra, se produce un estimulante de su abrigo
 bolsillo y la sostiene como un maravilloso artefacto.]}
{230}{}{[Sus ojos se va y deja a un bajo silbido.] El Elegido, ¿eh? Además el color me impresionó. Ahora vamos a decir
 hemos de llegar a los negocios. Dime, amigo, ¿alguna vez has oído hablar de un pequeño artículo llamado... un estimulante? [Como él dramáticamente
 habla de la última palabra, se produce un estimulante de su bolsillo de la chaqueta y se sostiene como un maravilloso artefacto.]}
{240}{}{Lo que usted diga, amigo. Ahora vamos a ir al grano, vamos? ¿Alguna vez has oído hablar de un pequeño artículo llamado...
 un estimulante? [Como él dramáticamente habla de la última palabra, se produce un estimulante de su bolsillo de la chaqueta y la sostiene como una
 maravilloso artefacto.]}
{241}{}{Uh, sí. En realidad, son bastante comunes.}
{242}{}{Por supuesto. De hecho, yo atesoran las cosas. El infierno, estoy prácticamente un estimulante junkie.}
{243}{}{[Sacude la cabeza y mira fijamente el punto de maravilla.] Lo que es... stim-pak?}
{250}{}{[Él sonríe nerviosamente.] Yo no diría que eres *común*, pero son sin duda codiciado por nosotros civilizado de la gente.
 [Mira a Krom.] Y por una buena razón. Se puede ver, estos chicos poco a contener poderes curativos mágicos que se *astound*
 y *amaze* de ti. Por supuesto, las palabras no significan nada sin la prueba, así que me permita mostrar las maravillas de la estimulante en acción.}
{251}{}{[Sus ojos momentáneamente se endurece, pero rápidamente se recupera la compostura y se ve en Krom.] Se puede ver, estos chicos poco
 contienen poderes curativos mágicos que se *asombrar y sorprender a* de ti. Por supuesto, las palabras no significan nada sin pruebas, de modo que
 me mostrará las maravillas de la estimulante en acción.}
{252}{}{Una excelente pregunta de mi amigo! Un estimulante es una de las muchas maravillas que nos dejó el Viejo Mundo. Usted ve,
 estos chicos poco a contener poderes curativos mágicos que se *asombrar y sorprender a* de ti. Por supuesto, las palabras no significan nada sin
 la prueba, de modo que me permita mostrar las maravillas de la estimulante en acción.}
{253}{}{Esto debería ser interesante. Vamos a ver.}
{254}{}{Ya sé cómo funcionan, yo he utilizado yo mismo un montón de veces.}
{260}{}{[Sonríe antes de que usted y Krom, luego se vuelve hacia uno de sus guardaespaldas.] Warren, ven dame tu mano. [La guardia frunce el ceño,
 pero hace lo que él dice. Roy rápidamente saca un cuchillo y barras través de la parte superior de Warren en el brazo. Warren
 hace una mueca de dolor pero no grita. Roy sonríe a usted.] Como se puede ver, Warren tiene bastante desagradable gash aquí.}
{261}{}{[MÁS]}
{262}{}{Os aseguro, amigos, el corte, y Warren dolor, son muy auténtico. Usted puede ver que esto no es ningún truco de la cuchilla. [Él las manos
 el cuchillo para Krom, que apenas miradas en él antes de asintiendo con la cabeza y se la entregó de nuevo.] Pero ahora, miren. [Él inyecta el estimulante
 en Warren brazo. Casi al instante, el sangrado se detiene. Roy utiliza un sucio trapo para absorber a la mayoría de la sangre, revelando una
 herida que casi curado.]}
{263}{}{[MÁS]}
{264}{}{Ahora imagínese que la ventaja de tener estimulantes daría por encima de su rival tribus. Y a diferencia de la sanación
 el polvo que chicos como a la cerveza, el estimulante *no* causar somnolencia. De hecho, esta pequeña maravilla es completamente
 *sin* efectos secundarios. Pero yo sé lo que estás pensando, que debe costar una fortuna, ¿verdad? Mal. Porque me *gusta* usted,
 Estoy prácticamente de dar 'em lejos para nada.}
{270}{}{[Ignorando su comentario, sonríe antes de Krom, luego se vuelve hacia uno de sus guardaespaldas.] Warren, ven dame tu mano.
 [La guardia frunce el ceño, pero se hace lo que él dice. Roy rápidamente saca un cuchillo y barras través de la parte superior de Warren en el brazo.
 Warren hace una mueca de dolor pero no grita.] Como se puede ver, Warren tiene bastante desagradable gash aquí.}
{275}{}{¿Cuánto?}
{276}{}{Prácticamente regalando? Cuánto pides?}
{280}{}{Te voy a dar toda esta jaula llena de em-que es *cincuenta* estimulantes -, y todo lo que pido a cambio es un mísero *veinte*
 golden gecko de las pieles. Usted simplemente no puede vencer a un acuerdo como el que.}
{281}{}{[A Krom.] Él está en lo correcto, esa es una buena oferta. Genial, la verdad. [Roy.] Nosotros nos encargamos de hacerlo.}
{282}{}{Es un buen trato bien. Demasiado buena. ¿Cuál es la trampa?}
{283}{}{Te ofrecemos diez golden gecko pieles. No más.}
{284}{}{Déjame pensar en ello por un momento.}
{285}{}{No hay trato.}
{290}{}{[Roy ilumina el rostro.] Excelente opción! Es un trato entonces. [Los artículos son rápidamente intercambiados, a continuación, Roy se apresura
 a su próxima parada.]}
{300}{}{[Roy risas y miradas a sus guardaespaldas antes de regresar su mirada a usted.] Mira, una sola estimulante vale mucho
 más de una sola de oro pelt. Así que ya ves, ya estoy ofreciendo a usted en un escandaloso de descuento. Para pedir más a mí
 sería robo. Veinte de las pieles, o voy a pasar a una tribu que es más razonable.}
{301}{}{Bien. Nosotros nos encargamos de hacerlo.}
{302}{}{Entonces es mejor empezar a moverse. No hay trato.}
{303}{}{Déjame pensar un momento.}
{305}{}{[Roy, frunce el ceño y arañazos a su desaliñado cuello. Finalmente, dejó salir un largo suspiro.] Usted está matando a mí, sabes que?
 Pero como un favor a su tribu, voy a aceptar tu oferta. [Los artículos son rápidamente intercambiados, a continuación, Roy se apresura a su lado
 la parada.]}
{310}{}{[Él frunce el ceño.] No sé qué clase de idiota a su vez hacia abajo a un acuerdo como este. [Sacude la cabeza y vuelve
 para sus hombres.] Muy bien, vamos a ir. [Él la mirada en usted.] Y vete a la mierda por desperdiciar mi tiempo.}
{311}{}{[Vamos a salir de ellos.]}
{312}{}{[Atacas]}
{320}{}{No hay trampa, mi amigo. Yo simplemente ya tienen todos los estimulantes que yo necesito, así que yo soy la descarga de mi exceso de oferta.
 De oro de las pieles, en el otro lado... yo nunca podría tener suficiente de ellos. Seguro, cincuenta estimulantes valen mucho más que
 un mero veinte golden gecko pieles, pero estoy siendo realista. Yo no puede esperar que su tribu -- cazadores expertos, aunque estoy seguro de que
 usted está -- para tener un centenar de oro gecko oculta por ahí, así que estoy haciendo una más oferta razonable. *Eso* ¿por qué es
 un buen trato.}
{321}{}{[A Krom.] Él está en lo correcto, esa es una buena oferta. Genial, la verdad. [Roy.] Nosotros nos encargamos de hacerlo.}
{322}{}{Antes de estar de acuerdo con nada, me gustaría echar un vistazo a el resto de los bienes.}
{330}{}{[Sus ojos se estrecha ligeramente, entonces él sonríe.] Por supuesto. Están en esta jaula junto a mí.}
{331}{}{[HECHO]}
{340}{}{Bien, pero no tome demasiado tiempo. Tenemos otra parada para hacer antes de la noche.}
{350}{}{Bien, si estás hecho cachondeo, vamos a conseguir que este espectáculo en el camino. Yo soy un hombre ocupado.}
{351}{}{Bien. Vamos a aceptar el trato.}
{352}{}{No hay trato.}
{353}{}{Tengo que pensar en esto un poco más.}
{354}{}{Tengo una nueva oferta para usted: nos dan los estimulantes, y tendrás tu vida.}
{360}{}{Eres un hombre ocupado, ¿eh? Eres un mentiroso y un tramposo.}
{361}{}{Los estimulantes son falsos. No son sino hypodermics lleno de brahmán de la sangre. Estaban tratando de extraer esta tribu off.}
{362}{}{Tengo que pensar en esto un poco más.}
{363}{}{Bien. Vamos a aceptar el trato.}
{370}{}{[Él se mueve incómodamente, y proyecta una nerviosa mirada a Krom.] Wh-¿de qué estás hablando?}
{371}{}{Los estimulantes son falsos. No son sino hypodermics lleno de brahmán de la sangre. Estás tratando de extraer esta
 la tribu de descuento.}
{372}{}{Wha-eso es imposible. Usted vio la demostración. Ellos trabajan muy bien. Yo no voy a estar aquí y vamos a intentar
 y arruinar mi buen nombre.}
{373}{}{Seguro, el estimulante que se utiliza durante la manifestación fue real. Pero me gustaría ver que lo intente de nuevo usando uno de los estimulantes en ese cajón.}
{374}{}{A la mierda tu buen nombre. No va a ser de alguna utilidad para usted después de que estoy hecho. [Ataque.]}
{380}{}{[Él se burla.] Bien! Bien! Si usted dice que son falsos, entonces tal vez se. ¿Cómo debo saber? Yo no tenía la
 follando cosas, me compré 'em. Así que *estoy* el que fue estafado aquí-no a usted. Ahora, ya que no hay trato, yo no soy
 voy a perder mi tiempo aquí por más tiempo. Bye.}
{381}{}{[Vamos a salir de ellos.]}
{382}{}{[Atacas]}
{390}{}{Quién coño te crees que eres? [A su guardaespaldas.] Matar a estos maldita tribales!}
