{100}{}{Ves a un tribal.}
{101}{}{Usted ver a un miembro de la tribu.}
{102}{}{Una de las pocas personas que quedan en la tribu.}
{200}{}{No eres bienvenido aquí.}
{201}{}{Los espíritus no como usted.}
{202}{}{Vaya, outworlder.}
{203}{}{¿Por qué nos afligen?}
{204}{}{Bienvenido, guerrero.}
{205}{}{Usted siempre será bienvenido aquí.}
{206}{}{Los espíritus lo aceptan como uno de nosotros.}
{207}{}{Gracias por ayudarnos.}
{208}{}{Yo creía que todos los outworlders eran malas. No es así...}
{209}{}{No hagas eso.}
{210}{}{Los negreros no son bienvenidos aquí!}
{300}{}{Es un honor tenerlo aquí, héroe.}
{301}{}{Su derrota del Enclave deberá ser registrada en leyendas. Sus antepasados son orgullosos.}
