{100}{}{Ves a un guardia de aspecto severo.}
{101}{}{Ves a un guardia de Ciudad Refugio de aspecto cruel.}
{102}{}{Métete en tus asuntos.}
{103}{}{Creo que ya es hora de que te vayas.}
{104}{}{No me gusta tu aspecto.}
{105}{}{Cuídate.}
{106}{}{Hola, Ciudadano.}
{107}{}{Me alegra verte, Ciudadano.}
{108}{}{¿Un día ocupado, Ciudadano?}
{109}{}{Después de ti, Ciudadano.}
{110}{}{Hola, viajero.}
{111}{}{Métete en tus asuntos, Errante.}
{112}{}{No vagabundees.}
{113}{}{Habla con Wallace si quieres entrar en la ciudad.}
{114}{}{Nada que informar, capitán.}
{115}{}{Mantengo los ojos abiertos por aquí, capitán.}
{116}{}{Ciudad Refugio prevalece, capitán.}
{117}{}{Que le vaya bien, capitán.}
