{100}{}{Ves al bibliotecario jefe Kohl.}
{101}{}{Ves a un hombre de aspecto diplomático con un uniforme de Ciudad Refugio.}
{102}{}{Ves al bibliotecario jefe Kohl.}
{103}{}{Ves a un hombre de aspecto diplomático con un uniforme de Ciudad Refugio.}
{104}{}{He de asegurarme de que tus actos heroicos se registran en los archivos de Ciudad Refugio, }
{105}{}{¡Dios mío! ¡Un intruso! ¡Ayuda! ¡Guardias!}
{106}{}{¡Dios mío! ¡Un mutante en Ciudad Refugio! ¡Guardias! ¡Guardias!}
{107}{}{¡Dios mío! ¡Un necrófago en Ciudad Refugio! ¡Guardias! ¡Guardias!}
{108}{}{La Oficina de Información está cerrada durante la tarde. Vuelve por la mañana.}
{109}{}{La Oficina de Información está cerrada durante la tarde. Me marcharé a casa en cuanto haya ordenado todas estas listas.}
{110}{}{Shhhhh.}
{111}{}{Camina en silencio, por favor.}
{112}{}{Shhhhh.}
{113}{}{El silencio ES una virtud.}
{114}{}{Oh... ¡hola! ¿Te puedo ayudar en algo?}
{115}{}{¡Frazz-urb-luuw!}
{116}{}{Dejas de balbucear}
{117}{}{¿Qué lugar es éste?}
{118}{}{Nada. Perdón por molestarte.}
{119}{}{Eh... ¿perdóname?}
{120}{}{Cripple-cripple creep}
{121}{}{Dejas de balbucear}
{122}{}{Oh, Dios, debes ser uno de los siervos. ¡Realmente DEBERÍAS volver con el amo Barkus de inmediato, o se pondrá furioso!}
{123}{}{¡Vaaale!}
{124}{}{Este es el Centro de Información de Ciudad Refugio. ¿Es el lugar que estabas buscando?}
{125}{}{En realidad, sí. Tengo algunas preguntas que tal vez puedas contestarme.}
{126}{}{¿Centro de Información? ¿Tienes algún libro, o manuales?}
{127}{}{En realidad, no. Siento molestarte.}
{128}{}{Por desgracia, nuestros libros están siendo transcritos actualmente a formato electrónico. Los suplementos se están almacenando en la
 Oficina de Servicios, calle abajo. Deberías probar allí.}
{129}{}{¿Dónde están almacenados los libros en formato electrónico?}
{130}{}{¿No queda ningún libro?}
{131}{}{Oh. Tengo unas cuantas preguntas...}
{132}{}{Quizá debería mirar allí, entonces.}
{133}{}{Hola otra vez. ¿Necesitas ayuda para encontrar algo?}
{134}{}{Desde luego. ¿Qué preguntas tienes?}
{135}{}{¿Qué lugar es éste?}
{136}{}{¿Sabes dónde puedo encontrar un GECK?}
{137}{}{¿Sabes dónde podría encontrar el Refugio?}
{138}{}{Hoy nada, gracias.}
{139}{}{¿Un GECK? Ese nombre me es familiar. ¿Qué es lo que hace?}
{140}{}{Verás, no lo sé. Oí hablar de él a la Anciana de mi poblado, y supone que es algún tipo de panacea para nosotros.
 Yo soy un poco más escéptico.}
{141}{}{Realmente no lo sé.}
{142}{}{¿Puedo hacerte alguna otra pregunta?}
{143}{}{No importa. Quizá hablemos en algún otro momento.}
{144}{}{¿El Refugio? Mira, la entrada está justo al final de la calle... es el enorme agujero de la ladera de la montaña.}
{145}{}{¿Conoces algún otro Refugio?}
{146}{}{¿Puedo hacerte alguna otra pregunta?}
{147}{}{Gracias por las indicaciones.}
{148}{}{¿Otros Refugios? Hmmm. No, en realidad, no. Sé que se construyeron otros Refugios, pero nunca hemos encontrado ninguno de ellos.
 Tal vez haya alguna referencia sobre ellos en la computadora central del Refugio.}
{149}{}{¿Cómo puedo hacer para bajar el Refugio?}
{150}{}{¿Puedo hacerte alguna otra pregunta?}
{151}{}{Gracias por la información.}
{152}{}{Hmmmm. Bueno, verás, la computadora central del Refugio quizá tenga alguna información sobre ello. Guardamos la mayoría
 de los archivos más antiguos allí abajo.}
{153}{}{¿Cómo puedo hacer para bajar el Refugio?}
{154}{}{¿Puedo hacerte alguna otra pregunta?}
{155}{}{Gracias por la información.}
{156}{}{Bien, eres un Ciudadano de la comunidad, ¿cierto? Tienes permiso para bajar allí.}
{157}{}{Oh, ¿lo eres? Perdón, perdón... bueno, entonces, se te permite entrar sin problemas y usar la computadora.}
{158}{}{Bien, lo primero que necesitarías es ser un Ciudadano de Ciudad Refugio. Si quieres, podrías hacer el test de Ciudadanía... o aún mejor,
 hablar con la Primer Ciudadano Lynette. Estoy seguro de que hará una excepción en tu caso.}
{159}{}{Eh, pero yo soy Ciudadano.}
{160}{}{¿Puedo hacerte alguna otra pregunta?}
{161}{}{Gracias por la información.}
{162}{}{Sí, bueno, se está transcribiendo todo porque... hmmm. Esta es un tema delicado, pero creo que mi puesto en Ciudad Refugio se ha quedado obsoleto.}
{163}{}{¿Ob-so-leto? ¿Qué quieres decir?}
{164}{}{¿Obsoleto?}
{165}{}{Oh. Tenía algunas preguntas más...}
{166}{}{Lamento oír eso. Debo irme.}
{167}{}{Significa que mi puesto aquí ya no es necesario. Por el bien de todos.}
{168}{}{Están planteándose poner terminales informativos en cada hogar. Esos nuevos terminales estaría conectados al Servidor
 de Listas y a los Archivos de Información. Una vez se haya hecho, el centro de información... y yo... seremos innecesarios. Por el bien de
 todos, desde luego.}
{169}{}{¿Estás segura?}
{170}{}{Oh. Tenía algunas preguntas más...}
{171}{}{Lamento oír eso. Debo irme.}
{172}{}{Oh Dios, sí. La Primer Ciudadano raramente se equivoca en tales cuestiones. Aún así, sentiré dejar este lugar. He oído que hay un puesto esperándome en la Oficina de Listas.}
{173}{}{Oh. Bien, lamento oír que todos los libros han sido transcritos. Prefiero leer un libro que mirar un pantalla de computadora.}
{174}{}{Oh. Bien, lamento oír que todos los libros han sido transcritos. Prefiero leer un libro que mirar un pantalla de computadora.}
{175}{}{Oh. Tenía algunas preguntas más...}
{176}{}{Lamento oír eso. Debo irme.}
{177}{}{¡Así es como me siento yo también! No tengo nada contra el formato electrónico, pero hay cierta... solidez... en tener un libro en tus manos y pasar las páginas una a una. Hmmm. Ya sabes...}
{178}{}{¿Sí?}
{179}{}{Oh. Tenía algunas preguntas más...}
{180}{}{Lamento oír eso. Debo irme.}
{181}{}{Aún no han enviado todos los libros a la Oficina de Servicios. Sé que Randal no los echaría de menos si se los entrego a alguien que los aprecia... alguien como tú.}
{182}{}{Me encantaría tenerlos. Gracias.}
{183}{}{Entonces iré a buscarlos...}
{184}{}{De acuerdo.}
{185}{}{Aquí los tienes. Espero que disfrutes leyéndolos. Son algunos de mis favoritos... un poco técnicos, pero bastante buenos de todas formas.}
{186}{}{Gracias. ¿Te importa si te algo alguna otra pregunta?}
{187}{}{Genial. Iré a comprobarlo.}
{188}{}{Los libros se están registrando en uno de los terminales de la biblioteca del tercer nivel del Refugio.
 No recuerdo cuál... creo que no es uno de los del núcleo central.}
{189}{}{¿Por qué se está transcribiendo todo?}
{190}{}{¿Cómo puedo hacer para bajar el Refugio?}
{191}{}{Ya veo. ¿Te importa si te hago algunas preguntas más?}
{192}{}{Quizá debería ir a ver si puedo encontrarlo.}
{193}{}{! Bien hecho! Bravo!}
