{100}{}{Ves a Val. O Valerie. O como sea.}
{101}{}{Ves a una mujer de pelo castaño vestida con un uniforme marrón y una armadura metálica. Parece una mecánico.}
{102}{}{Ves a Val. O Valerie. O como sea.}
{103}{}{Ves a una mujer de pelo castaño vestida con un uniforme marrón y una armadura metálica. Parece una mecánico.}
{104}{}{Oh, hola, "papá".}
{105}{}{1 segundo}
{106}{}{Valerie. Me alegra verte de nuevo.}
{107}{}{Oh, uh, hola, papá. Me alegra verte. De verdad.}
{108}{}{1 segundo}
{109}{}{Hola, Valerie. También me alegra verte.}
{110}{}{Mejor que saques de aquí a ese mutante antes de que los guardias lo vean.}
{111}{}{Mejor que saques de aquí a ese necrófago antes de que los guardias lo vean.}
{112}{}{La estúpida broca ataca de nuevo...}
{113}{}{Ese torno necesita que lo engrasen de nuevo...}
{114}{}{Hace falta una lista de las piezas excedentes para la Primer Ciudadano.}
{115}{}{¡Funciona, estúpido montón de chatarra!}
{116}{}{Estoy rodeada de idiotas...}
{117}{}{¡Si tan solo tuviera las herramientas adecuadas!}
{118}{}{Voy a matar a ese mono calvo de la oficina de Compras...}
{119}{}{Es tarde. Vuelve por la mañana.}
{120}{}{La tienda está cerrada. Después de terminar esta lista para la Primer Ciudadano, me voy a casa.}
{121}{}{Estoy ocupada. Vuelve en uno o dos días, y ya debería terminarlo.}
{122}{}{Tengo todo un montón de material atrasado que hay que arreglar. Vuelve en uno o dos días.}
{123}{}{Vaya, si es el "jefe" de mi papá.}
{124}{}{¡¿Sí?!}
{125}{}{¿QUIERES algo, o tan solo te vas a quedar ahí embobado como un imbécil?}
{126}{}{Be-cil}
{127}{}{Dejas de balbucear}
{128}{}{Eh, tranquilidad. Sólo me había parado para ver qué es este lugar.}
{129}{}{Cuidado. Hoy no estoy de humor para chorradas.}
{130}{}{Estaba buscando el Refugio. ¿Puedes decirme dónde está?}
{131}{}{En realidad, ya me marchaba.}
{132}{}{Es ese gran agujero de la montaña del este, más allá de los dos guardias armados. ¿Hay algo más que quieras saber o puedo volver el trabajo?}
{133}{}{¿Qué lugar es éste?}
{134}{}{Cuidado. Hoy no estoy de humor para chorradas.}
{135}{}{Gracias por las indicaciones. Adiós.}
{136}{}{Como si Ciudad Refugio no tuviera bastantes brahmines humanos... mira, NO PUEDES ESTAR AQUÍ, ¿VALE? ¡Te puedes HACER DAÑO! ¡AHORA SAL DE AQUÍ! ¡FUERA!}
{137}{}{*Snfff* Tu muy tonta... *snff*... yo voy a lugar con fiesta y p-payasos... *snfff*... y helado... y pastel... ¡y no invito a gente lista como TÚ!}
{138}{}{Dejas de balbucear}
{139}{}{Sal de aquí. O llamaré a los guardias para que te ECHEN.}
{140}{}{Inténtalo. Me encantaría.}
{141}{}{De acuerdo, me marcho.}
{142}{}{Es el centro de mantenimiento para Ciudad Refugio. ¿O es que no has VISTO el enorme letrero del
 lateral del edificio?}
{143}{}{No, lo siento. Pensé que esto sería una tienda de alguna clase.}
{144}{}{Olvídalo. Perdona por molestarte.}
{145}{}{Tienes razón con lo de "alguna clase", de todos modos. Mira, ¿necesitas reparar algo o sólo quieres hacerme un montón de preguntas tontas?}
{146}{}{¿Qué es lo que reparas aquí?}
{147}{}{Cuidado. Hoy no estoy de humor para chorradas.}
{148}{}{Hoy sólo preguntas tontas, en realidad. Hablaré contigo más tarde.}
{149}{}{Dispensadores de alcohol sintético, radios, armas de fuego, piezas de torretas láser, monitores de computadora, lo que sea... cuando puedo conseguir las herramientas necesarias para hacer mi trabajo.}
{150}{}{¿Herramientas?}
{151}{}{Parece un trabajo duro. Te dejaré con ello.}
{152}{}{Ahora mismo, tengo un torno de metal que apenas funciona, mi llave inglesa se ha perdido... OTRA VEZ... y mis alicates se han quedado sin dientes.}
{153}{}{¿Puedo ayudarte con algo?}
{154}{}{¿Qué problema hay en conseguir más herramientas?}
{155}{}{De acuerdo entonces. Buenos días.}
{156}{}{¿Tú? Lo dudo.}
{157}{}{Bueno, tengo una llave y un par de alicates justo aquí.}
{158}{}{¿Podría conseguirte una llave nueva y un juego de alicates para ayudarte?}
{159}{}{¿Qué problema hay en conseguir más herramientas?}
{160}{}{Tan solo pensé que podría ofrecer ayuda. No importa entonces.}
{161}{}{El PROBLEMA es que no puedo simplemente salir a comprar una nuevas, tengo que solicitarlas de Ciudad Refugio. Eso supone rellenar como cinco mil millones de listas, por triplicado, y después ESPERAR.}
{162}{}{¿Entonces por qu --?}
{163}{}{Lamento esc --}
{164}{}{Maldición, solicité un set de herramientas Super-Rotura hace MESES, pero, como siempre, no aparecerá hasta que ya no lo necesite. Es una maravilla cómo marchan siempre las cosas por aquí...}
{165}{}{Quizá pueda ayudarte.}
{166}{}{Oh. Bueno, lamento oír eso. Quizá vuelva.}
{167}{}{¿Cómo?}
{168}{}{Bueno, tengo una llave y un par de alicates justo aquí.}
{169}{}{Tal vez podría ir a buscar alguna para traértela.}
{170}{}{¿Qué problema hay en conseguir más herramientas?}
{171}{}{Oh. Bien, olvídalo.}
{172}{}{No te lo voy a pedir de rodillas, pero si quieres hacerlo, adelante. Es tu tiempo, no el mío. Podría conseguir juntar algo para pagarte por las molestias.}
{173}{}{Si encuentro una llave y un par de alicates, te los traeré.}
{174}{}{¿En serio?}
{175}{}{Sí. Aquí están.}
{176}{}{Eh... gracias. Quiero decir, no son de lo mejor, pero servirán. Dónde... oh, no importa. No es importante. Aquí están unos cuantos pavos por las molestias.}
{177}{}{Gracias. Verás, tenía más preguntas...}
{178}{}{Tal vez podrías usas esas herramientas para arreglar esa actitud tuya.}
{179}{}{No hay problema. Encantado de ayudar.}
{180}{}{Sí, sí... mira, tengo trabajo que hacer. Vuelve dentro de uno o dos días, ¿vale? Tendré
 tiempo para charlar entonces.}
{181}{}{Nos vemos mañana, entonces.}
{182}{}{Eh, está bien. Volveré en uno o dos días. Adiós.}
{183}{}{No te lo vas a creer. Menos de un DÍA después de que me dieras esas herramientas, me llegó el set Super-Rotura que solicité. Pero no solo uno. Me envían CINCO. ¡¿Qué demonios funciona mal en la oficina de pedidos?!}
{184}{}{¿Podrías desprenderte de uno de esos sets de herramientas?}
{185}{}{¡¿Por qué no?! ¡¿Qué voy a hacer con CINCO?! ¡Tómalo! Te juro que voy a darle una paliza a alguien de la oficina de Listas por esto.}
{186}{}{Gracias. Verás, tenía más preguntas...}
{187}{}{Te lo agradezco. Le daré buen uso a este set.}
{188}{}{Oh, ya veo lo que es. Bien, ¿qué es lo que quieres?}
{189}{}{¿Qué? No tengo tiempo para charlar todo el día.}
{190}{}{¿Sí? ¿Qué?}
{191}{}{¿Puedes repararme algo?}
{192}{}{¿Qué tienes a la venta?}
{193}{}{¿Qué pasa entre tú y tu padre?}
{194}{}{No importa. Te dejaré que trabajes.}
{195}{}{Nada digno de mención. Vino aquí hace veinte años en uno de sus viajes de caravana, atontó a madre y se largó. Desde que pasó por aquí, no le había visto en unos cinco años. No me he perdido nada.}
{196}{}{Parece que tú y él tenéis algunas cosas de las que hablar.}
{197}{}{Oh. Bien, eh, tenía algunas preguntas más...}
{198}{}{No importa. Te dejaré que trabajes.}
{199}{}{No, no tenemos. Nos dijimos todo lo que había que decir hace mucho tiempo. }
{200}{}{¿Estás segura?}
{201}{}{De acuerdo entonces. Tenía algunas otras preguntas...}
{202}{}{Entonces de dejaré trabajar.}
{203}{}{Sí, estoy SEGURA. Bueno... excepto por el hecho de que creo que debería perder algo de peso. Tiene demasiados michelines. Y debería dejar de vagabundear por todo el Yermo vendiendo chatarra a los tribales. Eso es todo.}
{204}{}{Mira, estaba metido en problemas con los esclavistas, pero ahora está intentando recuperar el tiempo perdido. Pero tienes razón, debería perder algo de peso.}
{205}{}{Oh, eh, vale. Tenía algunas preguntas más...}
{206}{}{No importa. Te dejaré que trabajes.}
{207}{}{Je je. Tienes un lado sarcástico. Me gusta eso. En cuanto al viejo "papá"... bien... hmmm. Intentaré ser un poco más civilizada. Durante un tiempo, en todo caso.}
{208}{}{Um... asegúrate de mantenerte lejos de los problemas, ¿de acuerdo?}
{209}{}{Genial. Mira, tenía algo más que quería preguntarte...}
{210}{}{Haré todo lo que pueda. Tenía algo más que quería preguntarte...}
{211}{}{Eso es todo lo que pido. Te dejaré con tu trabajo.}
{212}{}{Lo intentaré. Parece que están donde quiera que vayamos. Nos vemos, Valerie.}
{213}{}{Mira, no tengo nada "a la venta". Esto no es una tienda. La mayoría de las cosas que arreglo aquí terminan en la oficina de Servicios... por la puerta y hacia la izquierda.}
{214}{}{Como dije ANTES, esto no es una tienda. Ve a la oficina de Servicios si quieres un arma. Vuelve aquí si quieres reparar algo.}
{215}{}{Oh. Bien, ¿entonces puedes repararme algo?}
{216}{}{¿Puedes repararme algo?}
{217}{}{Vale, vale. Adiós.}
{218}{}{Bueno... tal vez. Veamos qué tienes.}
{219}{}{Le enseñas tus pistolas.}
{220}{}{Le enseñas tus rifles.}
{221}{}{Le enseñas tu inventario general.}
{222}{}{No importa. Quería saber algo más...}
{223}{}{Quizá en algún otro momento.}
{224}{}{Podría instalar un cargador rápido en esa mágnum tuya por 800 dólares.}
{225}{}{Hmmmm. Esa Desert Eagle que tienes... Podría instalarle una recámara expandida, si quieres. Eso costaría 1.000 dólares.}
{226}{}{Mejora la mágnum.}
{227}{}{¿Qué dirías de 650 dólares por la mejora de la mágnum?}
{228}{}{Mejora la Desert Eagle.}
{229}{}{¿Qué dirías de 850 dólares por la Desert Eagle?}
{230}{}{Olvida las pistolas. ¿Puedes mejorar alguna de mis otras armas?}
{231}{}{Quería saber otra cosa...}
{232}{}{Volveré cuando tenga más dinero.}
{233}{}{Hmmm. Tal vez en algún otro momento.}
{234}{}{Ese rifle de asalto que tienes ahí... puedo instalarle una recámara expandida por 1.500 dólares.}
{235}{}{Hmmmm. Tengo una mira de visión nocturna que puedo instalar en ese FN FAL que tienes por 3.500 dólares.}
{236}{}{Coloca la recámara expandida en el rifle de asalto AK-112.}
{237}{}{¿Qué me dices de 1.350 dólares por mejorar el rifle de asalto?}
{238}{}{Instala la mira visión nocturna en el FN FAL.}
{239}{}{¿Qué me dices de 3.100 dólares por la mira de visión nocturna?}
{240}{}{¿Puedes mejorar una de mis otras armas?}
{241}{}{No importa. Quería algo más...}
{242}{}{En realidad, nada. Tengo que irme.}
{243}{}{Volveré cuando tenga más dinero para gastar.}
{244}{}{Supongo que podría darle vidilla a esa picana para ti. Te costará 750 dólares.}
{245}{}{Está bien. }
{246}{}{¿Qué me dices de 650 dólares?}
{247}{}{En realidad, ¿podrías mejorar alguna de mis otras armas, en su lugar?}
{248}{}{No importa. Quería algo más...}
{249}{}{En realidad, nada. Tengo que irme.}
{250}{}{Demasiado para mis posibilidades. Volveré cuando tenga más dinero.}
{251}{}{Veo que has aprendido algunos trucos de mi tacaño padre. Dame una hora, y estará listo...}
{252}{}{Vale, vale. Te pareces a mi tacaño padre. Dame una hora, y estará listo...}
{253}{}{De acuerdo, dame una hora, y estará listo...}
{254}{}{De acuerdo.}
{255}{}{Aquí está. ¿Algo más?}
{256}{}{Tenía algunas preguntas más...}
{257}{}{¿Puedes mejorar cualquier cosa que tenga?}
{258}{}{Nada más hoy. Gracias.}
{259}{}{¿Qué es lo que... eh... papá?}
{260}{}{¿Perdón?}
{261}{}{Uh, no, no lo soy. Quiero decir, no lo creo.}
{262}{}{¡¿Papá?!}
{263}{}{2 segundos}
{264}{}{¡¿Valerie?! Cariño, ¿eres tú?}
{265}{}{2 segundos}
{266}{}{¡¿Dónde demonios has estado?! ¿Todavía correteando por el Yermo, vendiendo chatarra brillante a los tribales?}
{267}{}{4 segundos}
{268}{}{Eh, je je... ignórala, jefe, no sabe lo que dice... Val, cariño... verás, había esclavistas y...}
{269}{}{4 segundos}
{270}{}{Corta el rollo, papá. ¿TODAVÍA sigues llamando a todo con el que te te encuentras "jefe"? Siempre he odiado eso de ti.}
{271}{}{4 segundos}
{272}{}{Valerie, cariño, por favor... déjame que te explique... verás...}
{273}{}{2 segundos, y apagado}
{274}{}{... y así es como salimos de La Guarida.}
{275}{}{2 segundos}
{276}{}{Menudo montón de mierda de brahmin.}
{277}{}{2 segundos}
{278}{}{¡Es la verdad!}
{279}{}{2 segundos}
{280}{}{No empieces. Me alegra que Madre no esté aquí para escuchar esto.}
{281}{}{2 segundos}
{282}{}{¿Qué? ¿Qué le ocurrió a tu madre?}
{283}{}{2 segundos}
{284}{}{Encefalitis. La pilló en el Yermo. Probablemente buscándote a TI.}
{285}{}{2 segundos}
{286}{}{Oh. Yo... uh... lo siento, Val.}
{287}{}{2 segundos}
{288}{}{Sólo bromeaba.}
{289}{}{2 segundos}
{290}{}{¡¿Qu -?!}
{291}{}{2 segundos}
{292}{}{En realidad murió envenenada por radiación. Bebió algo de agua sin filtrar del pozo del Patio.}
{293}{}{4 segundos}
{294}{}{¡¿Qu... qué?!}
{295}{}{2 segundos}
{296}{}{No fue por tu culpa. Había demasiados rads corriendo por su cuerpo como para que el doctor Troy pudiera salvarla. Brillaba como una lámpara.}
{297}{}{2 segundos}
{298}{}{Oh. Yo... bueno, yo...}
{299}{}{2 segundos}
{300}{}{No te preocupes. De todos modos ya estaba bastante chiflada antes de eso. Sólo era cuestión de tiempo.}
{301}{}{3 segundos}
{302}{}{Sigo lamentando no haber tenido la oportunidad de volver a verla.}
{303}{}{2 segundos}
{304}{}{No, claro. Solías llamarla 'víbora del desierto', ¿no?}
{305}{}{2 segundos}
{306}{}{Bueno... sí. Pero tú no deberías llamar a tu madre víb--}
{307}{}{2 segundos}
{308}{}{¿Por qué no? Era cierto. Podía ser una auténtica zorra cuando quería.}
{309}{}{3 segundos}
{310}{}{Eh... parece que te las has arreglado bien por ti misma. Has heredado de tu padre la facilidad para reparar cosas, por lo que parece.}
{311}{}{4 segundos}
{312}{}{Papá... apenas te puedes atar los cordones de los zapatos, así que mucho menos reparar cualquier cosa con piezas móviles.}
{313}{}{3 segundos}
{314}{}{¡¿Qu-?! ¡Venga ya!}
{315}{}{2 segundos}
{316}{}{Preguntemos a tu "jefe".}
{317}{}{2 segundos}
{318}{}{Bueno... puede reparar radios. Y cosas.}
{319}{}{Ub nuwb ub}
{320}{}{2 segundos}
{321}{}{Si le das TODAS las piezas, ¿verdad?}
{322}{}{Veo que viajas con gente un poco más inteligente que tú.}
{323}{}{2 segundos}
{324}{}{Bueno, sí.}
{325}{}{¿Ub nuwm ub?}
{326}{}{2 segundos}
{327}{}{¡Ja! Lo sabía. Descuidado, descuidado.}
{328}{}{Tu "jefe" probablemente es mejor reparando cosas que tú.}
{329}{}{2 segundos}
{330}{}{Bueno, Val, la última vez que te vi, apenas podías distinguir una tuerca de una llave.}
{331}{}{2 segundos}
{332}{}{Sigue así, papá, y NECESITARÁS una llave para sacarte mi bota de tu culo.}
{333}{}{2 segundos}
{334}{}{¡¿Ah, sí?! Bien, "cariño", así que mejor que tengas cuidado o -}
{335}{}{2 segundos}
{336}{}{¡Silencio! ¡Callaos los dos! Esto ha ido DEMASIADO LEJOS! Ahora, vamos, Vic, nos marchamos.}
{337}{}{UGRGHH! ¡VAMOS! ¡NO MAS HABLÁIS! ¡NOS VAMOS!}
{338}{}{3 segundos}
{339}{}{Hablaremos más tarde, Val.}
{340}{}{2 segundos}
{341}{}{Sí, claro, papá.}
{342}{}{2 segundos}
{343}{}{Desvanecimiento durante 3 segundos}
{344}{}{¡Vaya! Me alegra tenerte de vuelta. Lo último que supe es que viajabas por el sur, usando viejos petroleros y haciendo volar plataformas petrolíferas.}
{345}{}{¿Vuelves aquí en busca de un poco de paz y tranquilidad, señor Gran Héroe?}
{346}{}{¿Vuelves aquí en busca de un poco de paz y tranquilidad, señora Gran Heroína?}
{347}{}{¿He-roe? ¡Hey-hey! ¡Yup!}
{348}{}{Dejas de balbucear}
{349}{}{Pensé en volver y establecerme en Ciudad Refugio un tiempo. La paz y la tranquilidad tampoco hacen daño, claro. Pero primero necesitaba algo...}
{350}{}{Hoy nada, gracias. Cuídate.}
{351}{}{Bien, ten cuidado por aquí, ¿me oyes? No hagas volar Ciudad Refugio si puedes evitarlo. Y... oye, gracias por salvarnos a todos.}
{352}{}{¡C-claro! ¡Adióoos!}
{353}{}{Dejas de balbucear}
{354}{}{No importa. Hablaré contigo más tarde.}
{355}{}{Has ayudado a Valerie a conseguir herramientas nuevas.}
{356}{}{Has convencido a Val para que le diera a su padre una oportunidad.}
{357}{}{ ***DO NOT DELETE THE NEXT LINE (#358)! IT'S NEEDED FOR THE SCRIPT. DON'T BOTHER TRANSLATING THIS, EITHER***}
{358}{}{}
{359}{}{Oye, tengo esas herramientas que buscabas.}
{360}{}{No parece que tengas muchas de las cosas con las que podría jugar. Sobre todo pistolas, rifles, ese tipo de cosas.}
