{100}{}{Ves a un hombre vestido con una armadura de combate militar estándar.}
{101}{}{Parece sano, pero bastante desorientado.}
{102}{}{Oh, mi cabeza.}
{103}{}{¿Quién eres?}
{104}{}{Ug!}
{105}{}{Y-yo soy Dobbs… soldado raso de primera clase.}
{106}{}{¿Puedes decirme cómo llegaste aquí?}
{107}{}{Adiós.}
{108}{}{Estaba en una batalla. Sí, una batalla. Había disparos y explosiones por todas partes. Gente muriendo. Estaba asustado pero tenía que seguir luchando. Entonces hubo esa llamarada deslumbrante.}
{109}{}{¿Y qué sucedió después?}
{110}{}{Adiós,}
{111}{}{Lo siguiente que recuerdo es que veía mi cuerpo como si estuviera mirándolo desde fuera. Oía a los médicos decir que estaba muerto y entonces lanzaron mi cuerpo en un montón de otros cuerpos.}
{112}{}{¿Y entonces qué?}
{113}{}{Adiós.}
{114}{}{Llegaron algunos hombres y llevaron mi cuerpo a un laboratorio. Les oí decir algo acerca de intentar regenerar mi cuerpo sumergiéndolo en algo llamado gel biomédico.}
{115}{}{¿Qué más?}
{116}{}{Adiós.}
{117}{}{Y entonces desperté aquí. ¡Tengo que irme! Tengo que regresar con mi unidad.}
{118}{}{Adiós.}
{200}{}{¿Dónde estoy?}
{201}{}{Me duele la cabeza.}
{202}{}{¿Por qué estoy cubierto de porquería?}
{300}{}{Tengo que reunirme con mi unidad.}
{301}{}{Oh no! ¡Soy un Ausente Sin Permiso!}
{302}{}{¿Cuál es el camino al frente?}
{303}{}{Esto es para ti, Johnny.}
{400}{}{El soldado raso Dobbs experimenta el síndrome post-criogénico.}
