{100}{}{Ves a un guardia.}
{101}{}{Ves a un guardia con servoarmadura.}
{102}{}{Ves a alguien que lleva una servoarmadura de diseño inusual. Lleva una insignia en el peto con la que no estás familiarizado.}
{103}{}{Sin novedad.}
{104}{}{A mí no me pasa nada, ¿y a ti?}
{105}{}{¿No deberías estar en tu puesto, soldado? No es buena idea estar vagando por aquí.}
{106}{}{No llevas el uniforme.}
{107}{}{Será mejor que te presentes ante el sargento y te vistas.}
{108}{}{Te la estás jugando al no llevar el uniforme. Será mejor que te presentes ante Intendencia.}
{109}{}{¿Quién demonios sois vosotros... ¡Alerta! ¡Intrusos!}
{110}{}{¡Hemos sufrido una infiltración! ¡Alerta!}
{111}{}{¡Múltiples intrusos! ¡Dad la alarma!}
{112}{}{¡Alerta de seguridad! ¡Sellad la base!}
{113}{}{¡Asegurad todas las estaciones! ¡Estamos en alerta!}
{114}{}{¡Alerta de intrusos! ¡Pasad a Código Rojo!}
{115}{}{¡Te aplastaremos!}
{116}{}{¡El Enclave dominará el mundo!}
{117}{}{¡Tú morirás y el Enclave sobrevivirá!}
{200}{}{...gilipollas...}
{201}{}{...si, será MEJOR que huyas...}
{202}{}{...qué lameculos...}
{203}{}{...¡sí, señor! ¡puto señor!...}
{300}{}{Espere. ¿Qué crees que estás haciendo con eso avión? No hay vuelos programados por varios días.}
{301}{}{¿Nrg?}
{302}{}{Soy consciente de esto.}
{303}{}{Lo siento. Sólo estaba mirando. Ya me marcho.}
{304}{}{Ha habido un cambio de planes. Estoy tomando este avión.}
{310}{}{¿Qué? Oh, ya veo. Mira, no lo toques. ¿Vale? Toques un otra vez y mueres.}
{311}{}{(Sonríes, y luego le atacas).}
{312}{}{(Te vas).}
{315}{}{Oh mierda, parece que tenemos un intruso. ¡Código Rojo! ¡Repito, código Rojo!}
{316}{}{Eso suena como un buena idea. Toques el avión de nuevo y pondré una bala en tu cabeza.}
{320}{}{Cierto. Y por lo tanto eres...}
{321}{}{Ya me iba. Siento molestarte.}
{322}{}{A punto de entregar un mensaje importante a la base principal.}
{323}{}{Oh, ¿de verdad? ¿Y qué dice ese mensaje?}
{324}{}{Es súper secreto. No puedo decírtelo.}
{325}{}{Te lo diré, pero es absolutamente esencial que no reveles esta información a nadie más, por miedo a un pánico masivo. Verá, se me ha llamado la atención que uno de los envíos de esclavos recientes está infectado con una cepa de virus desconocida y altamente mortal. *Debo* llegar a la base inmediatamente, o todos nuestras vidas podrían pederse. Ahora deja de perder mi tiempo, no hay un momento de sobra.}
{326}{}{Siiiiiiiiiiii, te creooooooooooo. Parece que tenemos un intruso...}
{327}{}{¡Maldición! Ah, lo que sea. Nunca me dicen cosas por aquí. Bueno. Este en tu camino.}
{328}{}{Guau, eso suena mal. Será mejor que te muevas, no quiero esa mierda en mis manos. Eh, y no te preocupes, no se lo diré a nadie.}
{329}{}{[HECHO]}
{400}{}{[After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of power armored soldiers. One of them does a double take at you then
 turns to the others.] Holy shit! One of those mutie wastlanders stowed away in the 'bird! ALERT! We got an intruder!}
{401}{}{[After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of power armored soldiers. One of them does a double take at you then
 turns to the others.] Holy shit! Some of those mutie wastlanders stowed away in the 'bird! ALERT! We got intruders!}
{402}{}{[Jump out and see how many you can take down before they waste you.]}
{403}{}{[Raise hands in surrender and hope for the best.]}
{410}{}{Aw, it doesn't look like the mutie's gonna put up a fight. Maybe we should bring him to the Commander -- see
 what he wants to do about this.}
{411}{}{Aw, it doesn't look like the mutie's gonna put up a fight. Maybe we should bring her to the Commander -- see
 what he wants to do about this.}
{412}{}{Aw, it doesn't look like the muties are gonna put up a fight. Maybe we should bring them to the Commander -- see
 what he wants to do about this.}
{420}{}{[After a half hour of sitting in the dark cargo hold, you feel the craft touch down to earth once more. A moment
 later, the cargo door opens and you see a squad of Enclave soldiers. One of them does a double-take at you.] What the hell
 are you doing back here? You weren't authorized to be on that mission. What's your name, soldier?}
{421}{}{It doesn't matter what my name is, 'cause I'm not here to talk. [Jump out and start fighting.]}
{422}{}{Me? Oh, I'm, uh, *cough*mumble*cough*. Don't mind me, though. In fact, I should probably be going now.
 [Get out and attempt to walk away nonchalantly.]}
{423}{}{Mi nombre es }
{424}{}{¿Dónde estoy?}
{425}{}{No, what's *your* name, soldier? I was put here to test you and I gotta say you FAILED. If I were a wasteland
 suicide assassin you and your whole crew would be dead right now! That is unacceptable! Shape up, soldier!}
{426}{}{Eh... mi nombre }
{427}{}{. I take fun ride in metal birdie! Go again! Wanna go again!}
{428}{}{You not need know my name. I no like you. I kill. [Jump out and start fighting.]}
{430}{}{What are you, drunk? You're at Navarro, of course. If you're having memory problems, soldier, you might wanna go get yourself checked out. Maybe some of that radiation out there got to you.}
{440}{}{Don't give me that bullshit. You're one of the new recruits, aren't you? Heh. That smart mouth of yours is gonna land you in all sorts of trouble--and I can't wait to see it happen. Now get back to your post, soldier.}
{450}{}{¡Señor! ¡Sí señor!}
{451}{}{¡Señora! ¡Si, señora!}
{460}{}{[The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made him retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bastard out of his misery before he contaminates us.}
{461}{}{[The soldier looks at one of his comrades.] My God, contact with all the muties and radiation out there must have made her retarded. You see? *That's* why I never volunteer for those wasteland runs. Anyway, let's put this stupid bitch out of her misery before she contaminates us.}
