{100}{}{Ves a un hombre como un castillo de grande.}
{101}{}{Ves a un hombre como un castillo de grande.}
{102}{}{Es un gigante y probablemente se come a gente como tú para desayunar.}
{103}{}{Viejo, tu vendrás con nosotros.}
{104}{}{Déjanos en paz. Jamás apoyaré la causa de tus superiores.}
{105}{}{No lo voy a pedir otra vez. Ven ahora, o daré ejemplo contigo.}
{106}{}{Prefiero que lo que sé desaparezca conmigo en la tumba.}
{107}{}{Que así sea. Matadlos a todos.}
{108}{}{Esto no es asunto tuyo. Date la vuelta y vete.}
{109}{}{Pareces haber encontrado a la gente equivocada en el sitio equivocado.}
