{100}{}{Ves una computadora.}
{101}{}{Ves al señor Tramposo.}
{102}{}{Una computadora grande.}
{200}{}{Hola, soy el señor Tramposo. ¿Cómo puedo ayudarte?}
{201}{}{¿Qué haces?}
{210}{}{I make drugs! All kinds of drugs! When life gets you down, Mr. Chemmie is here to pick you up! How does Mr. Chemmie work?! It's simple! All you need is some scientific know-how and the right ingredients, then leave the rest up to me! Go on! Give me a try! And kids, remember to ask Mommy or Daddy for permission before playing with Mr. Chemmie!}
{211}{}{De acuerdo, probaré tu culo de nuevo.}
{212}{}{Quizá más tarde.}
{220}{}{¿Qué deseas localizar?}
{221}{}{Estimulante}
{222}{}{Superestimulante}
{223}{}{Veneno}
{224}{}{Hacer antídoto del veneno.}
{225}{}{Kit de primeros auxilios}
{226}{}{Bolsa de doctor}
{227}{}{Esteroides}
{228}{}{Mentats}
{229}{}{Psico}
{230}{}{Great choice! To make a Stimpak, please feed me: one Broc Flower, one Xander Root and one Empty Hypodermic needle! Yum-yum!}
{231}{}{Hacer que lo paguen.}
{232}{}{No, no los llevo encima ahora mismo.}
{233}{}{Vuelves al menú principal.}
{240}{}{Great choice! To make a Super Stimpak, please feed me: one ordinary Stimpak, one piece of Fruit and one Nuka Cola! Yum-yum!}
{241}{}{Superestimulante}
{250}{}{Great choice! To make Psycho, please feed me: one box of Mentats, one Buffout, one piece of Fruit and one Stimpak! Yum-yum!}
{251}{}{Que sea un trago de whisky.}
{260}{}{Great choice! To make some Mentats, please feed me: one First Aid Kit, one piece of Fruit, and one bottle of Booze! Yum-yum!}
{262}{}{Haz que me derrita.}
{263}{}{Salir.}
{270}{}{Great choice! To make a Doctor's Bag, please feed me: one Stimpak, one First Aid Kit, one Empty Hypodermic needle and one Poison Antidote! Yum-yum!}
{272}{}{Bolsa de doctor}
{280}{}{Great choice! To make a First Aid Kit, please feed me: one Stimpak, one Empty Hypodermic needle, one Poison Antidote and one Rad Away! Yum-yum!}
{282}{}{Kit de primeros auxilios}
{290}{}{Great choice! To make Poison, please feed me: one Empty Hypodermic needle, one Scorpion Tail and one Nuka Cola! Yum-yum!}
{292}{}{Yo tengo veneno.}
{300}{}{Great choice! To make Buffout, please feed me: one First Aid Kit, one bottle of Beer and one Nuka Cola! Yum-yum!}
{302}{}{Esteroides}
{310}{}{Great choice! To make Rad-X, please feed me: one First Aid Kit and one Nuka Cola! Yum-yum!}
{312}{}{Hazme esclavista.}
{320}{}{Great choice! To make Rad Away, please feed me: one Nuka Cola, one Empty Hypodermic needle and one Stimpak! Yum-yum!}
{322}{}{Yo me voy.}
{330}{}{Great choice! To make a Poison Antidote, please feed me: one Scorpion Tail and one bottle of Booze! Yum-yum!}
{331}{}{Hacer antídoto del veneno.}
{340}{}{Oh boy! A special request! What kind of special drug would you like Mr. Chemmie to create for you today?!}
{341}{}{Marijuana.}
{342}{}{Documentos del doctor}
{343}{}{My friend Cassidy has a problem with his heart. Can you make something to help him?}
{344}{}{Informe de sensores ambientales.}
{350}{}{This is your lucky day! I have enough chemicals in my storage tanks to make these! Would you like Mr. Chemmie to make them for you?!}
{351}{}{Bien.}
{352}{}{Volver al menú principal.}
{360}{}{Uh-oh! Sorry, but I no longer have the chemicals needed to create these!}
{370}{}{Selection created! That was fun! Please collect the item from the machine! Thank you for using Mr. Chemmie! Let's make drugs again sometime!}
{371}{}{Más preguntas.}
{375}{}{Mr. Chemmie loves to help! I can create a substance called nitroglycerin, which will control an irregular heartbeat and prevent heart attacks!}
{380}{}{Rad-X}
{381}{}{RadAway}
{382}{}{¿Algo más?}
{383}{}{Nada.}
{390}{}{This is your lucky day! I have just enough chemicals in my storage tanks to make one batch of ERSIs! Would you like Mr. Chemmie to make them for you?!}
{391}{}{Bien.}
{392}{}{Salir.}
