{100}{}{Force field control panel.}
{200}{}{You successfully disable the force field.}
{201}{}{You fail to disable the force field.}
{202}{}{You successfully enable the force field.}
{203}{}{You fail to enable the force field.}
{210}{}{ desactiva el campo de fuerza.}
{211}{}{ fails to disable the force field.}
{212}{}{ activa el campo de fuerza.}
{213}{}{ fails to enable the force field.}
{300}{}{Has destruido la computadora.}
