{100}{}{Ves un sistema de acceso sin teclado. En un cartel se lee "Usar FOB del petrolero aquí"}
{101}{}{Ves un sistema de acceso sin teclado. En un cartel se lee "Usar FOB del petrolero aquí"}
{102}{}{Esta consola tiene una placa negra con una luz roja encima. En un cartel se lee "Usar FOB del petrolero aquí"}
{103}{}{Esta consola tiene una placa negra con una luz verde encima. En un cartel se lee "Usar FOB del petrolero aquí"}
{104}{}{[click] La luz en el panel negro cambia a verde.}
{105}{}{[click] La luz en el panel negro cambia a rojo.}
{106}{}{No ocurre nada.}
{107}{}{Eso no funciona.}
{108}{}{Es un sistema de puerta remota sin teclado. Normalmente necesita algún tipo de llave magnética.}
