{100}{}{Ves un juego de química.}
{101}{}{Ves el 'Mi primer juego de química'.}
{102}{}{Ves el 'Mi primer juego de química', un juego de química que permite crear interesantes brebajes.}
{103}{}{¿Por dónde quieres empezar? Tienes cuatro líquidos en sus viales: rojo, azul, amarillo, y transparente.}
{104}{}{Por el rojo.}
{105}{}{Por el azul.}
{106}{}{Por el amarillo.}
{107}{}{Por el transparente.}
{108}{}{No hacer nada.}
{109}{}{Seleccionaste el rojo. ¿Con cuál quieres mezclarlo?}
{110}{}{Con el azul. Eso produce líquido púrpura.}
{111}{}{Con el amarillo. Eso produce líquido naranja.}
{112}{}{Con el transparente. Eso produce líquido rojo.}
{113}{}{Beberla.}
{114}{}{Con el azul. Esto, como ya sabrás, producirá Jet, una anfetamina adictiva… si aciertas con las dosis adecuadas.}
{115}{}{Con el amarillo. Tu mente científica comprende que esto producirá, si se mezcla bien, ácido clorhídrico.}
{116}{}{Con el transparente. Tus ojos entrenados saben que esto producirá una potente vitamina… pero sólo si mezclas las cantidades adecuadas.}
{117}{}{Parar ahora.}
{118}{}{Seleccionaste el azul. ¿Con cuál quieres mezclarlo?}
{119}{}{Con el rojo. Eso produce líquido purpura.}
{120}{}{Con el amarillo. Eso produce líquido verde.}
{121}{}{Con el transparente. Eso produce líquido azul.}
{122}{}{Con el rojo. Esto, como ya sabrás, producirá Jet, una anfetamina adictiva… si aciertas con las dosis adecuadas.}
{123}{}{Con el amarillo. Antes de mezclarlo, calculas la solución en tu cabeza. Sabes que producirá nitroglicerina, un explosivo.}
{124}{}{Con el transparente. Esto producirá una sustancia química tóxica que no sirve para nada excepto para enmascarar los efectos
 de la radiación.}
{125}{}{Beberla.}
{126}{}{Parar ahora.}
{127}{}{Seleccionaste el amarillo. ¿Con cuál quieres mezclarlo?}
{128}{}{Con el azul. Eso produce líquido verde.}
{129}{}{Con el rojo. Eso produce líquido naranja.}
{130}{}{Con el transparente. Eso produce líquido amarillo.}
{131}{}{Beberla.}
{132}{}{Con el azul. Antes de mezclarlo, calculas la solución en tu cabeza. Sabes que producirá nitroglicerina, un explosivo.}
{133}{}{Con el rojo. Tu buen ojo científico se da cuenta de que esto, si se mezcla bien, producirá ácido clorhídrico.}
{134}{}{Con el transparente. Sabes que esto producirá un débil veneno, si continúas.}
{135}{}{Parar ahora.}
{136}{}{Seleccionaste el líquido transparente. ¿Con cuál quieres mezclarlo?}
{137}{}{Con el azul, para producir azul.}
{138}{}{Con el rojo, para producir rojo.}
{139}{}{Con el amarillo, para producir amarillo.}
{140}{}{Beberla.}
{141}{}{Con el amarillo. Sabes que esto producirá un débil veneno, si continúas.}
{142}{}{Con el azul. Esto producirá una sustancia química tóxica que no sirve para nada excepto para enmascarar los efectos de la radiación.}
{143}{}{Con el rojo. Tus ojos entrenados saben que esto producirá una potente vitamina… pero sólo si mezclas las cantidades adecuadas.}
{144}{}{Parar ahora.}
{145}{}{Te las has arreglado para crear un interesante líquido púrpura. ¿Qué quieres hacer con él?}
{146}{}{Beberla.}
{147}{}{Ponerla en mi inventario.}
{148}{}{Mmmm. Un interesante color naranja. ¿Que vas a hacer con él?}
{149}{}{Beberla.}
{150}{}{Ponerla en mi inventario.}
{151}{}{Un intenso color rojo. ¿Ahora qué?}
{152}{}{Beberla.}
{153}{}{Ponerla en mi inventario.}
{154}{}{Da como resultado un tono verde apagado. ¿Ahora qué?}
{155}{}{Beberla.}
{156}{}{Guardarlo.}
{157}{}{Un interesante tono azul. ¿Qué vas a hacer?}
{158}{}{Beberla.}
{159}{}{Guardarla para más tarde.}
{160}{}{Esto amarillo parece orina y huele peor. ¿Que vas a hacer?}
{161}{}{Beberla.}
{162}{}{Guardarlo. Podría ser útil.}
{163}{}{Ahh, dulce éxito. Has fabricado Jet. Podrías ser muy popular en Nuevo Reno con esto. ¿Que vas a hacer con él?}
{164}{}{Beberla.}
{165}{}{Guardarlo para usarlo en algún bobo confiado.}
{166}{}{¡Oh, oh! ¡Has creado unos extraños gases tóxicos! Apenas lo hueles y caes al suelo. Te sientes hecho una mierda.}
{167}{}{[HECHO]}
{168}{}{Esta cosa parece potente. ¿Que vas a hacer con esto?}
{169}{}{Beberla.}
{170}{}{Guardarla para más tarde.}
{171}{}{¡Oh no! ¡Lo has mezclado demasiado! ¡Deshace el frasco y llega hasta tu mano! ¡Ouch!}
{172}{}{¡Has creado con éxito una fórmula explosiva!}
{173}{}{Beberla.}
{174}{}{Ponerla en mi inventario.}
{175}{}{Un meneo por aquí, un meneo por allá, y… uh-oh… ¡BOOM!}
{176}{}{¡Oh no! ¡Idiota! ¡Acabas de tragarte una fórmula explosiva!}
{177}{}{Te sientes un poco raro. No, te sientes muy raro. De hecho, sientes cómo tu corazón está acelerándose y el mundo se ralentiza y no sabes lo que está pasando y nadie puede ayudarte porque no sabes lo que es esto, ¡oh no, ten cuidado! ¡AAAAAAH! ¡¡¡ESTÁS ALUCINANDO!!!}
{178}{}{Haces muecas por el sabor y entonces te das cuenta de que te está quemando por dentro. Ouch. OUCH. ¡¡OUCH!! ¡Te está destrozando las entrañas! }
{179}{}{Es un poco terroso, pero te las arreglas para tragártelo. Extrañamente, te sientes un poco mejor ahora.}
{180}{}{Ahh, qué demonios. A pesar de su apariencia, te bebes el desagradable brebaje. Inmediatamente empiezas
 a escupir y a tener arcadas. ¡Has sido irradiado!}
{181}{}{[HECHO]}
{182}{}{Bien… de acuerdo. Recordando las cosas que bebiste cuando eras pequeño, inclinas el
 frasco hacia atrás y dejas que fluya. Tu estómago se hace un nudo cuando el fluido entra en él. Sientes
 como si acabaras de sufrir la picadura de un escorpión rad.}
{183}{}{Caramba, parece agua, por lo que tiene que ser igual de bueno, ¿no? Tan pronto como la cosa entra en tu garganta,
 te das cuenta de que has cometido un error. Esta cosa QUEMA. Sientes dolor durante mucho, mucho tiempo.}
{184}{}{Un poco de esto, un poco de aquello… espera un segundo… ¿por qué el frasco echa humo?… ¿qué ocurre? ¡OH NO! ¡El frasco revienta en tu cara!}
{185}{}{Mezclas los componentes con júbilo, esperando crear la mezcla correcta de sustancias químicas. Luego
 te sientas y esperas los resultados. Y esperas. Y esperas. El líquido se convierte en un algo apagado y cenagoso
 marrón. Es inútil.}
{186}{}{Te las has arreglado para crear una potente vitamina. ¿Que quieres hacer con ella?}
{187}{}{Beberla.}
{188}{}{Guardarla para más tarde.}
{189}{}{¡Has creado una toxina! ¡Vale! ¿Ahora qué?}
{190}{}{Beberla.}
{191}{}{Guardarla para más tarde.}
{192}{}{Has creado con éxito una fórmula que simula los efectos del envenenamiento por radiación. ¿Qué
 te gustaría hacer con ella?}
{193}{}{Beberla.}
{194}{}{Guardarla para más tarde.}
