{100}{}{Ves a un hombre preocupado.}
{101}{}{Ves a Dan, el marido preocupado.}
{102}{}{Ves a un hombre bien vestido cuya cara parece estar al borde de la histeria.}
{103}{}{¿Quién eres? ¿Qué estás haciendo en mi casa?}
{104}{}{¿Ack? ¿Oop?}
{105}{}{Soy }
{106}{}{Nadie importante.}
{107}{}{Estoy aquí para robarte.}
{108}{}{Nada. Nadie. Adiós.}
{109}{}{En mi casa no, por favor. Hay una calle afuera donde puedes dormir y hacer lo que sea que hace la gente "especial" como tú.}
{110}{}{¡Thppt!}
{111}{}{Genial, genial. Encantado de conocerte. [Parece distraído]. Hey, oye... eres un aventurero, ¿verdad?}
{112}{}{Sí.}
{113}{}{¿No reconoces a El Elegido?}
{114}{}{No.}
{115}{}{¿Qué te importa eso a ti?}
{116}{}{La razón por la que pregunto, es porque mi mujer ha desaparecido. No sé donde está. Lleva desaparecida días. He preguntado por toda la ciudad, y nadie la ha visto. ¿Podrías encontrarla por mí?}
{117}{}{¿Qué hay para mí?}
{118}{}{Miraré por ahí. ¿Qué aspecto tiene?}
{119}{}{No. Estoy ocupado.}
{120}{}{Puedo darte 500 dólares. Son los ahorros de mi vida.}
{121}{}{Eso es suficiente. Lo haré.}
{122}{}{No. No puedo hacerlo.}
{123}{}{Por favor. Por favor. Mi mujer... lo es todo para mí. Por favor.}
{124}{}{¡He dicho que no!}
{125}{}{Vale. Vale, pero deja de darme la lata.}
{126}{}{Aquí tienes el dinero. Ahora por favor, por favor, POR FAVOR... encuentra a mi mujer y dime dónde está. Quizá se haya ido a vivir con otro, quizás me haya dejado... pero necesito saberlo.}
{127}{}{Vale, amigo. ¿Qué aspecto tiene?}
{128}{}{Por supuesto. Lo haré lo mejor que pueda.}
{129}{}{::solloza descontroladamente durante unos momentos:: Muy bien. Vete. Y que sepas que me has roto el corazón.}
{130}{}{Nos vemos, perdedor.}
{131}{}{Es rubia, sexy, y tiene la mejor voz para cantar... La última vez que la vi estaba paseándose por esta zona. No le gustan los mutantes ni los necrófagos, por lo que no habrá estado cerca de uno de ellos. Nadie sabe a dónde fue. Ha desaparecido.}
{132}{}{Eso debería ser suficiente.}
{133}{}{¿Y bien? ¿La has encontrado? Me duele el corazón a cada momento.}
{134}{}{Lo siento, amigo, la sigo buscando.}
{135}{}{Sí, la he encontrado.}
{136}{}{No, todavía no. Seguiré buscando.}
{137}{}{Oh, mi dolorido corazón. Por favor, cuando la encuentres házmelo saber.}
{138}{}{Sí, por supuesto.}
{139}{}{En realidad, no voy a seguir buscándola.}
{140}{}{¿La has encontrado? ::sus ojos se iluminan:: ¿Dónde?}
{141}{}{¿Era una cachonda sin piernas?}
{142}{}{Encontré un grupo de personas muertas en los túneles bajo la ciudad. Ella estaba entre ellas. Lo siento.}
{143}{}{¿Que? ¡No! ¡Tenía unas piernas estupendas!}
{144}{}{Oh. Vale. Bueno, ya no tiene esas estupendas piernas. Fue atacada despiadadamente, y perdió las piernas. Está totalmente muerta, y sufrió antes de morir.}
{145}{}{Vale. Bueno, creo que la encontré en los túneles bajo la ciudad. Está muerta. Lo siento mucho.}
{146}{}{Gracias por decírmelo. Creo que voy a llorar.}
{147}{}{Sí, ve a llorar, nenaza perdedora.}
{148}{}{Lo siento, colega.}
{149}{}{¡Te odio! ¡Todos te odian! ¡Muere! ::sollozo::}
{150}{}{Encontré una carta en el cadáver de tu mujer. Indica que podría haber formado parte de una conspiración para matar a los mutantes de Broken Hills.}
{151}{}{¡Oh Dios mio! Yo... no puedo creerlo... No... [suspira profundamente]. Supongo que puede ser cierto. Parecía
 odiar a cada mutante y a cada necrófago con el que se cruzaba. Nunca supe por qué.}
{152}{}{Sea como fuere, quizá consideres que los asesinatos no terminan sólo con tu mujer. Si ella estuvo implicada, tú también puedes estarlo.}
{153}{}{¿No querrás decir que mi vida también está en peligro? Oh, vaya. Quizá tengas razón. He estado escuchando ruidos fuera
 de la casa por la noche. Susurros y pasos.}
{154}{}{Podría ser una buena idea abandonar este lugar. Vigila tus espaldas. Buena suerte.}
{155}{}{Muchas gracias por tu ayuda. No seguiré aquí por más tiempo.}
{156}{}{Has informado a Dan del asesinato de su mujer.}
{157}{}{.}
