{100}{}{Un viejo Highwayman destrozado.}
{110}{}{Este vehículo está en mucho peor estado de lo que parece... nada hará que vuelva a funcionar. Sin embargo, parece que una caja de repuestos de motor en el asiento trasero se ha conservado en buen estado.}
{111}{}{Este vehículo está en mal estado. Sin embargo, tiene un paquete en el asiento trasero.}
{112}{}{Este vehículo parece idéntico a los demás de enfrente. Parece que hay un paquete en el asiento trasero.}
{113}{}{Este viejo vehículo está en buen estado. Estás seguro de que podrías arreglarlo de algún modo. Si tan sólo tuvieras las piezas...}
{120}{}{El motor parece estar demasiado oxidado como para que pueda arreglarse. Mientras buscas por el coche, encuentras una lata de aditivo para gasolina que podría arder realmente bien.}
{121}{}{El motor no es más que un montón de hierros que se cae a pedazos en cuanto abres el capó.}
{122}{}{Este coche necesita un montón de reparaciones. No tienes la habilidad o las piezas necesarias para hacer funcionar esta cosa.}
{123}{}{Parece que esta belleza está casi a punto. Tan sólo unas pocas vueltas más en esta tuerca... (Te echas hacia atrás por la sorpresa cuando el motor se cae del coche convirtiéndose en montón de hierrajos oxidados).}
{130}{}{Encuentras un regulador de combustible en el asiento trasero.}
