{100}{}{Ves una computadora funcional.}
{101}{}{Este terminal parece controlar las puertas de este bloque de celdas.}
{200}{}{Welcome to PoseidoNet. This terminal controls the operations of the MK-17 Fusion Bomb. Current Status of bomb is: Deactivated.}
{201}{}{Activar Robot.}
{202}{}{Salir.}
{210}{}{Activation of the bomb requires two forms of security overrides. Override 1: Red Reactor Keycard, given only to
 top U.S. Research officials. Override 2: Presidential Security Passkey, given only to the President of the United States.}
{220}{}{Habla. No tengo todo el día para esta mierda.}
{221}{}{Pase rojo del reactor}
{222}{}{Keycard accepted. Security override 1 complete. Level 2 Security still activated.}
{223}{}{Pase Presidencial}
{224}{}{Parece que tanto viajar ha servido de algo.}
{225}{}{Keycard accepted. Security override 2 complete.}
{226}{}{Activar Robot.}
{227}{}{Salir.}
{228}{}{Bomb has been activated and will detonate in T-minus 5 min..Error in countdown procedure. Countdown restated at
 T-minus 5 seconds. Please make sure you are at least 80 miles from the blast area. Have a great day.}
{229}{}{¡Madre de Dios!}
