{100}{}{Ves a una corpulenta mujer de mediana edad sucia por polvo de roca.}
{101}{}{Ves a Marge LeBarge, propietaria de la mina Kokoweef.}
{102}{}{Ves a una mujer de aspecto fuerte y sólido con aire de autoridad.}
{103}{}{Lo siento, no tengo tiempo para temas de caridad ahora mismo.}
{104}{}{Vuelve cuando esa herida en tu cabeza haya sanado.}
{105}{}{Me sorprende que puedas caminar y hablar al mismo tiempo.}
{106}{}{Parece que tu cinturón no ha pasado por todas las presillas.}
{107}{}{No sois más que unos payasos escapados de un circo, ¿verdad?}
{108}{}{Ahora mismo no eres mi persona favorita.}
{109}{}{Oye, gracias por conseguirme ese chip de excavación. Ahora las cosas van realmente bien en la
 mina Kokoweef.}
{110}{}{Te daré 1.000 dólares por ese chip de excavación.}
{111}{}{¿Ha habido suerte con ese chip de excavación?}
{112}{}{Sí, bueno, lo lamento. Pero no puedes satisfacer a todo el mundo a la vez.}
{113}{}{Siempre satisface conseguir un trabajo tan bien pagado. Deja que te pregunte algo más.}
{114}{}{¿Cómo sabías que tengo un chip de excavación?}
{115}{}{¿Cuánto vale para ti?}
{116}{}{Si lo tuviese, estarías entre los primeros en saberlo.}
{117}{}{Creo que me voy a marchar ahora. Adiós.}
{118}{}{Oye, gracias por interrumpir esa pelea. A veces mis mineros se saltan un poco las normas, pero son
 buena gente cuando no están de Jet hasta arriba.}
{119}{}{Gracias por poner entre rejas a esos buscalíos de la Morningstar. Es donde merecen estar. ¿Cómo
 puedo ayudarte?}
{120}{}{No me puedo creer que pusieras a mis chicos entre rejas. Estoy segura de que esos malditos matones de la Morningstar
 comenzaron la pelea. ¿Y ahora qué quieres?}
{121}{}{Me gustaría que no hubieras encarcelado así a mis mineros. Simplemente enjaulando a esos hooligans de la Morningstar
 habría sido suficiente para mantener la paz en la ciudad. ¿Qué quieres?}
{122}{}{Desde luego sabes cómo apagar un incendio con gasolina, ¿eh? No hacía falta que muriera nadie por una pelea de bar.
 ¿Qué demonios quieres de mí, de todas formas?}
{123}{}{¿Quién eres?}
{124}{}{Quería preguntarte sobre algo.}
{125}{}{Sólo pasaba por aquí. Y creo que será mejor que siga andando. Adiós.}
{126}{}{Hola. Soy Marge. Marge LeBarge, y dirijo esta mina.}
{127}{}{¿Qué puede hacer Marge por ti?}
{128}{}{¿Qué extraéis aquí?}
{129}{}{¿Alguna vez has oído hablar de algo llamado Kit de Creación del Jardín del Edén?}
{130}{}{¿Eres nativa de Redding?}
{131}{}{¿Sabes algo acerca de algún trabajo o cualquier otra cosa que pase por aquí?}
{132}{}{Sólo echaba un pequeño vistazo. Adiós.}
{133}{}{Oro, por supuesto. Lo extraemos justo aquí, en la Kokoweef, y después lo enviamos a Ciudad Refugio, Nuevo Reno,
 y la República de Nueva California.}
{134}{}{¿Lo vendéis en todas partes?}
{135}{}{¿Por qué llamáis a vuestra mina Kokoweef?}
{136}{}{Déjame hacerte otra pregunta.}
{137}{}{Ya veo. Gracias. Eso es todo lo que necesitaba saber por ahora. Adiós.}
{138}{}{Claro que sí. A todo el mundo le gusta el oro. Deberías hablar con el organizador de caravanas, James Hoffy, si estás realmente
 interesado en ello.}
{139}{}{Déjame hacerte otra pregunta.}
{140}{}{Gracias, lo haré. Adiós.}
{141}{}{Un Kit de Creación del Jardín del Edén, ¿eh? Suena bastante impresionante. Si tuviera algo así seguro que no
 me encontrarías excavando entre el polvo para llegar a fin de mes, ¿no te parece?}
{142}{}{Supongo que no. Déjame preguntarte algo más.}
{143}{}{Sólo quería preguntar. Adiós.}
{144}{}{Diablos, no. Nací en el norte. Justo a la orilla de un lago. El lago LeBarge, se llamaba.}
{145}{}{Nunca había oído hablar de él. Déjame preguntarte otra cosa.}
{146}{}{Suena bien. Quizá vaya a la búsqueda de ese lugar. Adiós por ahora.}
{147}{}{Nada más que rumores.}
{148}{}{Bueno, siempre hay rumores... aunque yo tengo algo que hay que hacer.}
{149}{}{Volveré sobre eso. Pero deja que te pregunte sobre otra cosa.}
{150}{}{Háblame sobre los rumores.}
{151}{}{¿Qué tienes para hacer?}
{152}{}{Apuesto a que sí. Lo siento, pero estoy ocupado ahora mismo. Adiós.}
{153}{}{Tenemos una maravillosa enorme y vieja máquina excavadora en la mina. El problema es que el chip de control para ella
 ya no funciona. Necesito uno nuevo si quiero expandir mis operaciones.}
{154}{}{Eso es interesante pero, ¿cómo encajo yo en ello?}
{155}{}{La Gran Mina Wanamingo, al oeste de la ciudad, debería tener una de las mismas máquinas excavadoras.
 Lleva abandonada poco tiempo, así que supongo que aún podría haber un chip funcional en su
 maquinaria.}
{156}{}{Parece bastante fácil. ¿Por qué no lo habéis hecho ya?}
{157}{}{Porque no es tan sencillo. Verás, la Gran Mina Wanamingo está embrujada. La gente va allí y
 no regresa. Esa es la razón principal por la que está cerrada. Solía ser un lugar realmente productivo.
 Pero ya no.}
{158}{}{Así que quieres que consiga el chip de la máquina de excavación de esa mina. ¿Cuánto vale para ti?}
{159}{}{Te daré 1.000 dólares por ese chip. McGrew, de la Morningstar probablemente te ofrecería lo mismo,
 pero se lo entrega todo a esos malditos matones de Nuevo Reno. No puedo soportar a esos violentos bastardos. Así que deja que yo te dé
 el dinero, ¿vale?}
{160}{}{Veremos. Pero una cosa... es una buena cantidad de dinero. Esa mina debe ser bastante peligrosa.}
{161}{}{Bueno, no es un juego de niños, querido. Pero pareces alguien que puede cuidarse de
 sí mismo. De todas formas, me traes el chip y consigues el dinero. ¿Te interesa?}
{162}{}{Sí. Me interesa. Me apunto.}
{163}{}{Bien, pensaré en ello. Adiós por ahora.}
{164}{}{Genial. Cuanto antes estés aquí de vuelta con el chip de excavación, mejor.}
{165}{}{Veré lo que puedo hacer. Antes, déjame hacerte algunas otras preguntas.}
{166}{}{De acuerdo, ya nos veremos. Adiós.}
{167}{}{Bueno, siempre hay los rumores habituales de que van a apoderarse de Redding, o sobre wanamingos
 saliendo del cementerio por la noche. Diablos, incluso alguien dijo haber visto alguna clase de máquina
 voladora sobrevolando la zona hace unos meses.}
{168}{}{¿Sobre qué más tenías curiosidad?}
{169}{}{¿Qué has oído sobre eso de apoderarse?}
{170}{}{¿Qué es un wanamingo?}
{171}{}{¿Una máquina voladora?}
{172}{}{Supongo que la gente habla sobre las mismas cosas en todas partes. Hablemos de otro tema.}
{173}{}{Me encantaría escucharlo, pero tengo que irme. Adiós.}
{174}{}{Bueno, la gente siempre dice que Ciudad Refugio quiere controlarnos para quedarse con nuestro oro. O que una de las familias de
 Nuevo Reno quiere que todo el mundo esté enganchado a su droga para apoderarse de nosotros. O incluso que la RNC quiere anexionarnos.
 Te diré que la RNC es nuestra mejor apuesta, pero todos son iguales en lo que respecta a nuestro oro. Redding sigue siendo
 independiente, hasta ahora.}
{175}{}{¿Y sobre los demás rumores?}
{176}{}{Supongo que eso es todo lo que necesito saber por ahora. Adiós.}
{177}{}{Un wanamingo sólo es la bestia con más malas pulgas con la que te puedas topar. Alta como dos hombres, más fuerte que un brahmin
 macho, y con tentáculos llenos de ventosas en vez de brazos. Ni siquiera se le puede hacer daño con armas de fuego. Supuestamente, los indios
 los convocaron en venganza contra el hombre blanco por lo que pasó en la guerra. Aunque no pongo mucha fe en esa afirmación.}
{178}{}{¿Y sobre los demás rumores?}
{179}{}{Supongo que eso es todo lo que necesito saber por ahora. Adiós.}
{180}{}{Oh, sí. Bueno, un par de mis mineros estaban volando un poco (colocados, si sabes a
 qué me refiero) hace un tiempo. Juraron y perjuraron haber visto pasar una nave voladora, dirigiéndose hacia el suroeste.}
{181}{}{¿Y sobre los demás rumores?}
{182}{}{Supongo que eso es todo lo que necesito saber por ahora. Adiós.}
{183}{}{Bueno, Dan y sus chicos de la Morningstar favorecen a esos mafiosos de Nuevo Reno. Supongo que Redding será un gran barrio de adictos de Jet dentro de poco.}
{184}{}{En realidad no es asunto mío. Hablemos de otra cosa.}
{185}{}{Oh, bueno. Adiós.}
{186}{}{En una ciudad de este tamaño, todo el mundo sabe más de lo que quisiera de todos los demás. Así que, ¿qué te parece?}
{187}{}{¿Cuánto me vas a dar por él?}
{188}{}{1.000 dólares. Aquí y ahora. ¿Los quieres o no?}
{189}{}{Vale, me los quedaré. Aquí está el chip.}
{190}{}{Creo que no quiero venderlo ahora mismo.}
{191}{}{¿Crees que vas a conseguir una oferta mejor? Piénsalo de nuevo, amigo. No creo que eso vaya a suceder. Pero
 supongo que es tu tiempo.}
{192}{}{Está bien, te lo venderé a ti. Aquí está el chip.}
{193}{}{Creo que todavía quiero echar un vistazo por ahí antes de nada. Adiós.}
{194}{}{Has hecho la elección correcta. Gracias. Voy a poner eso en su lugar para que podamos poner a trabajar
 esa máquina excavadora.}
{195}{}{Genial. Oye, pero déjame hacerte alguna otra pregunta primero.}
{196}{}{Gracias por el dinero. Adiós.}
{197}{}{¿Sí? Vaya, gracias. Me estoy poniendo tierna y todo. ¿Qué es lo que quieres?}
{198}{}{Quiero preguntarte algo.}
{199}{}{Nada. Sólo estaba echando un vistazo. Adiós.}
{200}{}{¿Por qué no? En realidad, no sé de dónde surgió el nombre. Creo que siempre se ha llamado así.
 Incluso antes de que yo llegara aquí. Tiene una especie de soniquete romántico, ¿no? Ko-ko-weef. Sí, me sigue
 gustando cómo suena.}
{201}{}{Eh, sí. Vale. Eh, ¿qué decías que extraéis aquí?}
{202}{}{Oh. oh. Bueno, me iré ahora. Adiós.}
