{100}{}{}
{101}{}{Ves a un miembro de tu tribu.}
{102}{}{Ves a Martin.}
{103}{}{Ves a un Shi con el ceño fruncido.}
{110}{}{Be gone. I'm seeking council with the spirits and they don't like you, outworlder. If you must speak to me, do it another time.}
{111}{}{Um, tengo que irme. Adiós.}
{112}{}{Hmph. I didn't ask for your help, outworlder. I could have taken care of the well myself.}
{113}{}{Eh... gracias, amigo.}
{114}{}{Lo que sea. Me largo de aquí.}
{120}{}{¿Qué quieres?}
{121}{}{He oído que estás teniendo pequeños problemas con la mina.}
{130}{}{What's wrong? I dropped the rope, that's what's wrong. [He shifts uncomfortably.] I was fastening a new rope to the well and then I looked up and saw this fine young maiden stretching in the sunlight. Spirits of lust distracted me and the rope slipped from my hands and... What's it to you anyway, outworlder? Unless you got a new rope for me, you be wasting my time.}
{131}{}{Tendré que pensar en ello. Contactaré contigo.}
{132}{}{As a matter of fact, I do. I'll see if I can fix that well for you.}
{133}{}{Nope, I'm afraid you're just going to have to admit to the others what happened. Try to keep your spirits of lust under control next time. Bye.}
{140}{}{¿Qué coño quieres?}
{141}{}{No llevo ninguna encima, me temo.}
{142}{}{Does it look fixed to you? You're standing right next to the fucking thing. Jerk.}
{150}{}{¿Has hablado ya con la Anciana?}
{151}{}{Sí, tengo los planos del verti.}
{160}{}{[He glances at the well, then snickers.] What good is a rope if you don't have a bucket attached? Or do you outworlders drink by licking water off a wet rope? [He shakes his head and mutters something under his breath.] Just attach the bucket, and I'll see that you be gettin' a reward.}
{161}{}{Eso es.}
{162}{}{How 'bout *you* reattach the bucket, and I'll see if I can restrain myself from beating your ass.}
{170}{}{¿Por qué me atacas ahí?}
{171}{}{No, aún no.}
{172}{}{Does it *look* like I attached the bucket?}
{180}{}{So the well is fixed, yes? With the bucket attached and everything?}
{181}{}{Sí, quiero comerciar.}
{182}{}{...}
{190}{}{[The corner of his mouth twitches up into a hint of a smile.] Ah, I suppose you outworlders aren't all bad, after all. Here, take this money. The spirits tell me you be needing this more than I.}
{191}{}{Gracias.}
{200}{}{Tus ancestros te han abandonado.}
{201}{}{Gracias por tu ayuda.}
{202}{}{Me alegro de volver a verte.}
{210}{}{¡No vas a llevarte a mi familia, esclavista!}
{300}{}{All right, calm your spirits of anger. I'll do it myself. [He mumbles.] Crazy outworlder...}
{301}{}{[HECHO]}
{310}{}{[He narrows his eyes at you, then glances at the well.] No.}
{311}{}{Lo siento, no hablo en estúpido.}
{320}{}{Hey, did you hear me? I asked if the well be fixed yet.}
{321}{}{... [You sigh, then point at the well.]}
{330}{}{[He turns and looks at the well, then turns back to you.] Yeah, looks right an' proper now. Why not just say so? Here, take this money. The spirits tell me you be needing this more than I.}
{331}{}{[Coleccionas dinero y te alejas.]}
{400}{}{[As you're about to walk away, Marli looks at you closely and his eyes light up.] Ah! I see you have sub-machine gun. [He gazes longingly at the weapon.] We had one once, but Sulik always be hogging it. Got lost in a battle. Such a pity. My magic would be fearsome strong if I had a soul-taker such as that.}
{401}{}{If you want this one, you can have it. I'm sure I'll find another. [Hand Marli the SMG.]}
{402}{}{Just take it. I don't even want it after the eye raping you're giving it. [Hand Marli the SMG.]}
{403}{}{Yeah, I bet. Anyway, me and my soul-taker are going elsewhere now.}
{404}{}{Sigue atento. Adiós.}
{410}{}{[He grins like a maniac as he looks over the weapon.] Oh, you be a good friend to Marli, outworlder. Here, was saving this sweet bubble-water, but I think you should be having it. [He hands you a Nuka-Cola.] Now I be off to spit fiery death at some geckos. [He runs off to the hunting grounds.]}
{411}{}{My magic be fearsome now!}
{1000}{}{Has reparado el pozo.}
{2000}{}{Lo siento, tengo trabajo que hacer.}
{2001}{}{Sorry, I lost your sub-machine gun. That gecko be a fierce one.}
