{100}{}{You see a computer terminal.}
{101}{}{You see the chemistry workstation.}
{102}{}{You see a computer workstation.}
{103}{}{Hälsningar. Vänligen ange ditt lösenord för att bekräfta din identitet.}
{104}{}{? Me no understand big words.}
{105}{}{TIUASPO-Lo-Shi-S12908}
{106}{}{Hack into computer.}
{107}{}{Log Out.}
{108}{}{Chemistry Database: -Fuel and derivatives- -Polymers-}
{109}{}{Fuel and derivatives.}
{110}{}{Polymers.}
{111}{}{Deactivate workstation.}
{112}{}{Log Out.}
{113}{}{Please speak to the system administrator. Goodbye.}
{114}{}{Hack into computer.}
{115}{}{Lämna.}
{116}{}{Intruder alert activated. Shutting down. Have a nice day.}
{117}{}{[KLAR]}
{118}{}{(After sifting through the complex chemical formulae and lab notes, you come to the conclusion that the Shi have created a kind of fuel from plant extracts and sea life. Apparently, they have hooked into previously existing pipelines so they can transport fuel to a wide variety of destinations.)}
{119}{}{(You come across a vast array of complex chemical formulae and lab notes. You're not quite sure what all of this means.)}
{120}{}{Direct fuel to Poseidon tanker.}
{121}{}{Direct fuel to Hubologists.}
{122}{}{Tillbaka.}
{123}{}{(Once you have waded past the symbology and technical discussion, you discover that the Shi are working on a new kind of polymeric combat armor that is resistant to both flame and penetration. It is still years from completion. You also see mention of new weaponry and construction capabilities. Apparently the Shi have some plans for the future.)}
{124}{}{Tillbaka.}
{125}{}{Fuel directed accordingly. Storage tanks = Empty. Closing program.}
{126}{}{[KLAR]}
{127}{}{Fuel directed accordingly. Storage tanks = Empty. Closing program.}
{128}{}{[KLAR]}
{129}{}{Station deactivated.}
{130}{}{Activate station.}
{131}{}{Lämna.}
{132}{}{[Your random approach works wonders... you're in the machine!]}
{133}{}{[MER]}
{134}{}{The computer does not respond to any input.}
{135}{}{You can't seem to find anywhere to put that.}
{136}{}{Gissa lösenordet.}
{137}{}{Direct fuel along pipeline.}
{138}{}{Destination required.}
