{100}{}{You be needin' something?}
{101}{}{Yeah, I was wondering who you're guarding.}
{102}{}{Me? Oh no, I don't need anything. Bye.}
{103}{}{Who you guard?}
{104}{}{Hej då!}
{110}{}{I be guarding tribe's holy leader. He who walks with spirits. Much honor guarding him. Keep out unwanted, like you. Now leave.}
{111}{}{[KLAR]}
{120}{}{I say to leave, but you don't listen. I unleash spirits of fury when people don't listen. Suggest you get the feet movin'. Now.}
{121}{}{[KLAR]}
{130}{}{Heard about the good deeds you been doing. See I was wrong about you. Forgive me for being a rude man, fren. Go on in and peep the big man. He be waiting for you.}
{131}{}{Heard about the good deeds you been doing, fren. Go on in and peep the big man. He be waiting for you.}
{132}{}{Thank you.}
{133}{}{Thankee.}
{140}{}{Greetings, fren.}
{141}{}{How goes things, warrior?}
{142}{}{Go on in.}
{143}{}{Well met, warrior.}
{144}{}{Good to peep you again, fren.}
{260}{}{Me kill slaver!}
{300}{}{You see a strong looking tribal}
{301}{}{You see the guardian of the tribe leader.}
{302}{}{This man is watching you with a piercing gaze. Clearly, he is guarding someone important.}
{500}{}{You always be welcome here, hero.}
