#
# Messages for Prototypes
#
# strings
#
{10}{}{<Keine>}

#
# Material Types
#
{100}{}{Glas}
{101}{}{Metall}
{102}{}{Kunststoff}
{103}{}{Holz}
{104}{}{Erde}
{105}{}{Stein}
{106}{}{Zement}
{107}{}{Leder}

#
# Item Types
#
{150}{}{Rüstung}
{151}{}{Container}
{152}{}{Droge}
{153}{}{Waffe}
{154}{}{Munition}
{155}{}{Verschiedenes}
{156}{}{Schlüssel}

#
# Scenery Types
#
{200}{}{Portal}
{201}{}{Treppe}
{202}{}{Aufzug}
{203}{}{Leiter unten}
{204}{}{Leiter oben}
{205}{}{Normale Aussicht}

#
# Damage Code Types
#
{250}{}{normal_dam}
{251}{}{Laser}
{252}{}{Feuer}
{253}{}{Plasma}
{254}{}{elektrisch}
{255}{}{emp}
{256}{}{Explosion}

#
# Caliber Types for weapons
#
{300}{}{Keine}
{301}{}{Rakete}
{302}{}{Brennstoff für Flammenwerfer}
{303}{}{C-Energiezelle}
{304}{}{D-Energiezelle}
{305}{}{.223}
{306}{}{5mm}
{307}{}{Kal.40}
{308}{}{10mm}
{309}{}{Kal.44}
{310}{}{14mm}
{311}{}{12mm}
{312}{}{9mm}
{313}{}{Luftgewehr}
{314}{}{Kal.45}
{315}{}{2mm}
{316}{}{4,7mm, hülsenlos}
{317}{}{HN-Nadler}
{318}{}{7,62mm}

#
# Race Types
#
{350}{}{Kaukasisch}
{351}{}{Afrikanisch}

#
# Body Types
#
{400}{}{Zweifüßer}
{401}{}{Vierfüßer}
{402}{}{Robotisch}
#
# Kill Types names
#
# Note: These were moved to 1450+ to handle new ones!
{450}{}{Männer}
{451}{}{Frauen}
{452}{}{Kinder}
{453}{}{Supermutanten}
{454}{}{Ghuls}
{455}{}{Brahmin}
{456}{}{Radskorpione}
{457}{}{Ratten}
{458}{}{Floater}
{459}{}{Zentauren}
{460}{}{Roboter}
{461}{}{Hunde}
{462}{}{Gottesanbeterin}
{463}{}{Deathclaws}
{464}{}{Pflanze}
#{465}{}{}
#
# Kill type info descriptions
#
{465}{}{Diese Zeile zeigt die Zahl der männlichen Menschen, die du im Verlauf deines Abenteuers getötet hast.}
{466}{}{Diese Zeile zeigt die Zahl der weiblichen Menschen, die du im Verlauf deines Abenteuers getötet hast.}
{467}{}{Diese Zeile zeigt die Zahl der menschlichen Kleinkinder, die du im Verlauf deines Abenteuers getötet hast. Du Widerling.}
{468}{}{Die Zahl der Supermutanten, die du im Verlauf deines Abenteuers erledigt hast.}
{469}{}{Diese Zeile zeigt die Zahl der männlichen und weiblichen Ghulmutanten, die du im Verlauf deines Abenteuers getötet hast.}
{470}{}{Diese Zeile zeigt die Zahl der Brahmin (mutierte Kühe), die du im Verlauf deiner Reisen geschlachtet hast.}
{471}{}{Die Zahl der mutierten Radskorpione, die du im Verlauf deines Abenteuers niedergemacht hast.}
{472}{}{Die Zahl der Ratten, die du getötet hast. Enthält alle Mitglieder der Rattenfamilie.}
{473}{}{Dies ist die Zahl der mutierten Floater, die du niedergemacht hast.}
{474}{}{Dein Beitrag zur Verringerung mutierter Zentauren.}
{475}{}{Die Zahl der Roboter, die du zerstört oder zerlegt hast.}
{476}{}{Die Gesamtzahl der Hunde, die du in den großen Zwinger im Himmel geschickt hast.}
{477}{}{Diese Zeile zeigt die Zahl der toten Gottesanbeterinnen oder großer mutierter gottesanbeterartigen Insekten, die du bis jetzt zerquetscht hast.}
{478}{}{Diese Zeile zeigt, daß du die Deathclaw und eine beliebige Anzahl ihrer Nachkommen erledigt hast.}
{479}{}{Die Anzahl an Pflanzen, deren Streben zur Sonne du beendet hast.}

#
# Use text
#
{480}{}{Du siehst: %s.}

#
# Use Container text
#
{485}{}{Du durchsuchst %s.}
{486}{}{Du schließt %s.}
{487}{}{Verschlossen.} # new

#
# Look text
#
{490}{}{Du siehst: %s.}
{491}{}{Tot vor dir liegt: %s.}
{492}{}{Du siehst die Überreste von: %s.}
{493}{}{Du siehst nichts Ungewöhnliches.}

#
# Examine text
#
{500}{}{tot}
{501}{}{so gut wie tot}
{502}{}{schwer verletzt}
{503}{}{verletzt}
{504}{}{unverletzt}

#
# Examine text messages
#
{510}{}{RA-Mod: %d}
{511}{}{RV-Mod: %d}
{512}{}{Sch-Mod: %d/%d}
{518}{}{Du bist: %s}
{519}{}{%s %s }
{520}{}{Du bist: %s}
{521}{}{%s %s.}
{522}{}{Er ist: %s}
{523}{}{Sie ist %s}
{524}{}{Es ist %s}
# (note: hps are short for hit-points)
{525}{}{%s hat %d/%d Trefferpunkte.}
# (note: this is for guns that have ammo)
{526}{}{Es hat %d/%d Schuß %s.}
{530}{}{ und hat schwer verletzte Gliedmaßen.}  # These append to lines 500-504
{531}{}{, hat aber schwer verletzte Gliedmaßen.}
{532}{}{ und hast schwer verletzte Gliedmaßen.}
{533}{}{, hast aber schwer verletzte Gliedmaßen.}
# (note: hps are short for hit-points)
{535}{}{Er hat %d/%d Trefferpunkte}
{536}{}{Sie hat %d/%d Trefferpunkte}
{537}{}{Es hat %d/%d Trefferpunkte}
{540}{}{Es wiegt %d Pfund.}
{541}{}{Es wiegt %d Pfund.}
{544}{}{, }
{545}{}{.}
{546}{}{ und trägt: %s.}
{547}{}{ und trägt: %s mit %d/%d Schuß %s.}
{548}{}{Das Auto sieht nicht so aus, als würde es im Augenblick funktionieren.}
{549}{}{Das Auto läuft mit %d%% Energie.}

#
# Examine text error messages
#
{550}{}{Fehler: lookup_val ist außerhalb des Bereichs!}
{551}{}{Fehler: obj_examine: proto_ptr fehlgeschlagen!}

#
# Use text messages
#
{580}{}{Du benutzt %s.}
{581}{}{Du verwendest %s an %s.}
{582}{}{Das bewirkt nichts.}
{583}{}{Entsetzt merkst du, daß es schon tot ist.}
{584}{}{Als du es berührst, merkst du, daß es schon tot ist.}
{585}{}{Leider kommst du zu spät.} # This is relating to a critter being dead.
{586}{}{Das funktioniert nicht bei Toten.}
{587}{}{Du zündest die Leuchtrakete an.}
{588}{}{Die Leuchtrakete brennt schon.}
{589}{}{Du stellst den Timer ein.}
{590}{}{Der Timer tickt schon!}
{595}{}{Du lädst das Auto mit mehr Energie.}
{596}{}{Das Auto ist schon voll aufgeladen.}
{597}{}{Die Türöffnung scheint blockiert zu sein.}

#
# Experience-Point messages
#
{620}{}{Du erhältst %d Erfahrungspunkte für das Töten von: %s.}
{621}{}{%s verdienst du %d Erfahrungspunkte.}
{622}{}{Für den Sieg über deine Feinde}  # 622-626 prepend to line 621
{623}{}{Für das Erledigen deiner Gegner}
{624}{}{Da du siegreich aus dem Kampf hervorgegangen bist,}
{625}{}{Für die Vernichtung deiner Gegner}
{626}{}{Für die Vernichtung deiner Gegner, ohne einen Kratzer abzubekommen,}

#
# Dialog messages
#
{650}{}{[Fertig]}
{651}{}{[Weiter]}
{652}{}{Weiter}
{653}{}{[Zurück]}
{654}{}{Zurück}                                    # changed number from 653
{655}{}{Fortfahren}                                # new
{656}{}{Ähh...}                                    # new
{660}{}{Du siehst dort nichts.}
{661}{}{Zu weit weg.}
{670}{}{OK.}                                       # F2: Used in PM: CombatAI settings
{671}{}{Klar.}                                     # F2: Used in PM: CombatAI settings
{672}{}{Wie du meinst.}                            # F2: Used in PM: CombatAI settings
{673}{}{Wie du willst.}                            # F2: Used in PM: CombatAI settings
{674}{}{Ich versuch's.}                            # F2: Used in PM: CombatAI settings
{675}{}{Das kann ich nicht tun.}                   # F2: Used in PM: CombatAI settings
{676}{}{Ich glaube nicht, daß ich das tun kann.}   # F2: Used in PM: CombatAI settings
{677}{}{Arf!}                                      # F2: Used in PM: CombatAI settings -- RoboDog
{678}{}{Wuff!}                                     # F2: Used in PM: CombatAI settings -- RoboDog

#
# Not Enough AP message
#
{700}{}{Du hast nicht genügend Aktionspunkte.}
#
# Book messages
#
{800}{}{Du liest das Buch.}
{801}{}{Du erfährst nichts Neues.}
{802}{}{Du erfährst neue wissenschaftliche Informationen.}
{803}{}{Du lernst viel über die Reparatur elektronischer Geräte.}
{804}{}{Du lernst neue Arten, Verletzungen zu heilen.}
{805}{}{Du lernst, wie man besser mit Waffen umgeht.}
{806}{}{Du lernst viel über das Überleben in der Wildnis.}
#
# Use on messages (and some extra stuff that Jesse needed)
#
{900}{}{Der Vorrat in der Arzttasche geht zur Neige.}
{901}{}{Die Vorräte im Erste-Hilfe-Kasten gehen zur Neige.}
{902}{}{Das kannst du nicht während eines Kampfes machen.}
{903}{}{Diese Person will nicht mit dir handeln.}
{904}{}{Diese Person hat dir nichts zu erzählen.}
{905}{}{Du kannst dieses Objekt nicht nehmen. Du hast deine maximale Tragfähigkeit erreicht.}
{910}{}{Die Vorräte in der Sanitätertasche gehen zur Neige.}
{911}{}{Die Vorräte im Erste-Hilfe-Kasten für Feldärzte gehen zur Neige.}
{913}{}{Dieses Wesen kann nichts tragen.}


#
# Kill Types names
#
{1450}{}{Männer}
{1451}{}{Frauen}
{1452}{}{Kinder}
{1453}{}{Supermutanten}
{1454}{}{Ghuls}
{1455}{}{Brahmin}
{1456}{}{Radskorpione}
{1457}{}{Ratten}
{1458}{}{Floater}
{1459}{}{Zentauren}
{1460}{}{Roboter}
{1461}{}{Hunde}
{1462}{}{Gottesanbeterin}
{1463}{}{Deathclaws}
{1464}{}{Pflanzen}
{1465}{}{Geckos}
{1466}{}{Aliens}
{1467}{}{Riesenameisen}
{1468}{}{Big Bad Boß}
#
# Kill type info descriptions
#
{1469}{}{Diese Zeile zeigt die Zahl der männlichen Menschen, die du im Verlauf deines Abenteuers getötet hast.}
{1470}{}{Diese Zeile zeigt die Zahl der weiblichen Menschen, die du im Verlauf deines Abenteuers getötet hast.}
{1471}{}{Diese Zeile zeigt die Zahl der menschlichen Kleinkinder, die du im Verlauf deines Abenteuers getötet hast. Du Widerling.}
{1472}{}{Die Zahl der Supermutanten, die du im Verlauf deines Abenteuers erledigt hast.}
{1473}{}{Diese Zeile zeigt die Zahl der männlichen und weiblichen Ghulmutanten, die du im Verlauf deines Abenteuers getötet hast.}
{1474}{}{Diese Zeile zeigt die Zahl der Brahmin (mutierte Kühe), die du im Verlauf deiner Reisen geschlachtet hast.}
{1475}{}{Die Zahl der mutierten Radskorpione, die du im Verlauf deines Abenteuers niedergemacht hast.}
{1476}{}{Die Zahl der Ratten, die du getötet hast. Enthält alle Mitglieder der Rattenfamilie.}
{1477}{}{Dies ist die Zahl der mutierten Floater, die du niedergemacht hast.}
{1478}{}{Dein Beitrag zur Verringerung mutierter Zentauren.}
{1479}{}{Die Zahl der Roboter, die du zerstört oder zerlegt hast.}
{1480}{}{Die Gesamtzahl der Hunde, die du in den großen Zwinger im Himmel geschickt hast.}
{1481}{}{Diese Zeile zeigt die Zahl der toten Gottesanbeterinnen oder großer mutierter gottesanbeterartigen Insekten, die du bis jetzt zerquetscht hast.}
{1482}{}{Diese Zeile zeigt, daß du die Deathclaw und eine beliebige Anzahl ihrer Nachkommen erledigt hast.}
{1483}{}{Diese Zeile zeigt die Zahl der Pflanzen, die du aus dieser Welt herausgerissen hast.}
{1484}{}{Die Zahl niedlicher Echsen, die du aus dem Leben befördert hast.}
{1485}{}{Die Anzahl der durch deine Hand umgekommenen Aliens.}
{1486}{}{Die Anzahl an Insektoiden, die du im Ödland umgelegt hast.}
{1487}{}{Die Zahl an genetisch hochgezüchteten Cyborg-Bodyguards mit irrsinnigem Tötungsdrang, die du erledigt hast.}