{200}{}{Cavern Entrance}
{201}{}{Entrance}
{202}{}{Living Quarters}
{203}{}{Command Center}
{210}{}{Desert Entrance}
{211}{}{Caverns/Entrance}
{212}{}{Living Quarters}
{213}{}{Command Center}
{220}{}{Entrance}
{221}{}{Garden}
{222}{}{Brahmin Pen}
{230}{}{Entrance}
{231}{}{Crash House}
{232}{}{Casino}
{240}{}{Base}
{250}{}{Hotel}
{251}{}{Hall}
{252}{}{Watershed}
{260}{}{Entrance}
{261}{}{Downtown}
{262}{}{Heights}
{263}{}{Old Town}
{264}{}{Merchants}
{265}{}{Cave}
{270}{}{Entrance}
{271}{}{Level 1}
{272}{}{Level 2}
{273}{}{Level 3}
{274}{}{Level 4}
{280}{}{Entrance}
{281}{}{Stronghold Level 1}
{282}{}{Stronghold Level 2}
{283}{}{Vats Level 1}
{284}{}{Vats Level 2}
{290}{}{Crater}
{291}{}{Level 1}
{300}{}{Adytum}
{301}{}{Downtown}
{302}{}{Library}
{303}{}{Fortress}
{304}{}{Warehouse}
{310}{}{Entrance}
{311}{}{Interior}
{500}{}{Du erhälst 10,000 Erfahrungspunkte!}
{501}{}{Ruins}
{1000}{}{Desert}
{1001}{}{Mountains}
{1002}{}{City}
{1003}{}{Coast}
{1004}{}{Unbekannt}
