{100}{}{B?n th?y c?u em h? Nagor. B?n không th?y con chó Smoke c?a c?u ta đâu c?.}
{101}{}{B?n bi?t Nagor t? h?i c?n bé tí, và luôn giúp đ? c?u ta khi nào có th?.}
{102}{}{Ch? h?, r?t vui đư?c g?p ch?! Em c?n ch? giúp.}
{103}{}{Th? l?i nhưng tôi không có th?i gian.}
{104}{}{C?u c?n giúp g??}
{105}{}{V?y th? em s? t? đi đ?n đ?t hoang!}
{106}{}{Ch? đ?... c?u c?n giúp g? th??}
{107}{}{C? đi đi.}
{108}{}{Smoke đ? ch?y vào khu săn và v?n chưa quay v?. Gi? th? Morlis không đ? em đi t?m.
M? b?o ch? đó quá nguy hi?m và nó ch? là chó thôi, nhưng em đ?nh có th? nào em 
c?ng ph?i đi. Nhưng gi? có ch? r?i. Ch? có th? đi giúp và em s? không g?p
r?c r?i n?a.}
{109}{}{H?n r?i. Nhưng khu săn ? ch? nào?}
{110}{}{Đư?c r?i. Đ? tôi đi t?m nó gi? đây.}
{111}{}{Quên đi, tôi đâu có r?nh.}
{112}{}{Ch? làm sao th?, b? ăn đá ch?i vào đ?u à? Khu săn n?m cách xa l?u c?a
Hakunin, phía B?c c?a làng.}
{113}{}{Tôi s? s?m đưa nó quay v?.}
{114}{}{Ch? đ? t?m th?y Smoke chưa?}
{115}{}{V?n chưa. C?u nói khu săn ? đâu th? nh??}
{116}{}{Chưa.}
{117}{}{Ch? đ? t?m th?y Smoke chưa?}
{118}{}{Chưa. Tôi s? s?m quay l?i thôi.}
{119}{}{Tôi r?t ti?c nhưng nó ch?t r?i.}
{120}{}{Ch? ch? nói v?y v? ch? không mu?n đi t?m th? có! Em đéo s? Morlis nói g?,
em ph?i đi t?m nó đây.}
{121}{}{Nagor, n?u có chuy?n g? v?i c?u th? sao? D? Morlis s? ch? c?n l?i m?t m?nh và s?
bu?n l?m đ?y. C?u không mu?n làm d? bu?n ch?, đúng không?}
{122}{}{C? đi đi.}
{123}{}{Th?... không, em không mu?n làm vây. Đư?c r?i, em s? không đi, nhưng như v?y không công b?ng!}
{124}{}{Smoke s? ?n thôi. T?m bi?t.}
{125}{}{Ch? t?m th?y Smoke r?i! Cám ơn! Smoke, đ? chó hư!}
{126}{}{Không có g?. T?m bi?t.}
{127}{}{Cám ơn l?n n?a. Hi v?ng ch? có m?t chuy?n đi th?t vui!}
{128}{}{Em nh? Smoke quá. Sao ch? l?i không c?u nó ch?? Ch? là C?u tinh cơ mà.}
{129}{}{Tôi b?n, đ? đ?n. Đi ch? khác chơi đi.}
{130}{}{Tôi đi.}
{131}{}{Tôi s? đi t?m Smoke.}
{200}{}{Xin chào ch? h?... ?, ? em là C?u tinh. Em hi v?ng là ch? đ? t?m th?y GECK. Em nghe
m?i ngư?i nói nhi?u v? th?i k? khó khăn s?p đ?n r?i.}
{201}{}{Xin chào ch? h?... ?, ? em là C?u tinh. Em hi v?ng là ch? đ? t?m th?y GECK. Em nghe
m?i ngư?i nói nhi?u v? th?i k? khó khăn s?p đ?n r?i.}
{202}{}{Ng? v?n t?m, Nagor.}
{203}{}{Tôi v?n đang đi t?m, em h? ?.}
{204}{}{Chào m?ng tr? v?, anh h?. M?i th? ? nhà đang hơi lo?n. Anh đ? t?m th?y s? 13 th?n thành và
GECK chưa?}
{205}{}{Chào m?ng tr? v?, anh h?. M?i th? ? nhà đang hơi lo?n. Anh đ? t?m th?y s? 13 th?n thành và
GECK chưa?}
{206}{}{Me not find. Sorry.}
{207}{}{I'm sorry, Nagor. I'm still looking.}
{208}{}{Hello again, cousin. I guess you've noticed that things are really falling apart here. Please
 find the GECK. We are in desperate need!}
{209}{}{Hello again, cousin. I guess you've noticed that things are really falling apart here. Please
 find the GECK. We are in desperate need!}
{210}{}{Hi, cousin.}
{211}{}{Hi, cousin.}
{212}{}{You not sound like usual self.}
{213}{}{You don't sound like your usual self.}
{214}{}{I'm sorry, cousin. Things have been getting worse and worse since you last left. People are
 sick, the brahmin are dying and... I... my dog Smoke died - Morlis cooked him. I miss him so much. Sorry, but I can't
 really talk any more...}
{215}{}{I'm sorry, cousin. Things have been getting worse and worse since you last left. People are sick,
 the brahmin are dying and... I... my dog Smoke died. I miss him so much. Sorry, but I can't really
 talk any more...}
{300}{}{You see Nagor.}
{302}{}{Ch? h?, r?t vui đư?c g?p ch?! Em c?n ch? giúp.}
