{100}{}{Du siehst ein Grabkreuz.}
{101}{}{Auf dem Kreuz }
{102}{}{steht: "Hier liegt Bruder Gregory. Ein Mann, der keine Grenzen kannte."}
{103}{}{steht: "Tante Patty. Ein Glück, dass wir sie endlich los geworden sind."}
{104}{}{steht: "Hier liegt Per Joner. Starb einen Juwel zu kurz."}
{105}{}{steht: "Hier liegt Pater Michael. Gründer, Vater, Krieger."}
{106}{}{steht: "Ein Atheist. Verkleidet und ohne einen Platz zum hingehen."}
{107}{}{steht: "Hier liegt Johnny Yeast. Entschuldigt, dass ich nicht auferstanden bin."}
{108}{}{steht: "Mary Jane. Liebende Ehefrau und Mutter."}
{109}{}{steht: "'Schachmatt!' war der Ruf des geschätzten Old Jon. Auf dem Schachbrett des Lebens war er nur der Bauer.}
{110}{}{steht: "Sir John Seltsam — hier liegt ein Anwalt, und das ist Seltsam."}
{111}{}{steht: "Tränen können sie nicht wiederbringen — deshalb weine ich."}
{112}{}{steht: "Jeden Tag auf jede Art, werde ich besser und besser."}

{250}{}{gibt es keine Inschrift.}
{251}{}{ist nichts zu erkennen, es ist zersplittert und brüchig.}
{252}{}{steht der Name John Doe.}
{253}{}{wurden Name und Datum von der Witterung abgeschliffen.}
