{100}{}{Du siehst Mrs. Peterson.}
{101}{}{Du siehst eine junge gutaussehende Frau. Sie lächelt, als sie dich sieht.}

{200}{}{Willkommen in Abbey, Freund.}
{201}{}{Rede mit meinem Mann, wenn du etwas benötigst.}
{202}{}{Ist es nicht ein wundervoller Tag?}

{300}{}{Willkommen in Abbey, Freund.}
{301}{}{Rede mit meinem Mann, wenn du etwas benötigst.}
{302}{}{Ist es nicht ein bezaubernder Abend?}

{400}{}{Ich hab dir nichts zu sagen. Bitte geh weg.}