{100}{}{Du siehst einen Mönch am Computer.}
{101}{}{Du siehst Bruder Paul.}
{102}{}{Dieser Mönch sieht wie ein Computer-Guru aus.}
{200}{}{Hi!}
{201}{}{Hallo.}
{202}{}{Jetzt mach ich eine Sicherheitskopie von diesen Computer Dateien...}
{203}{}{Tut mir leid, aber ich habe keine Zeit mich mit jemandem zu unterhalten, der solch einen niedrigen Intellekt hat.}
{300}{}{Ja?}
{301}{}{Ihr Jungs habt ja 'ne Menge Computer hier.}
{302}{}{What can you tell me about the Abbey?}
{303}{}{Erzähl mir was über euer Oberhaupt.}
{304}{}{Hast du irgendwelche Infos über ein G.E.C.K.?}
{305}{}{Weißt du, wo ich Vault 13 finden kann?}
{306}{}{Tschüss.}
{307}{}{Ich bin auf der Suche nach einigen speziellen Informationen.}
{308}{}{Und das wäre?}
{400}{}{Ja, haben wir. Viel zu viele, meiner Meinung nach. Ich kann dir überhaupt nicht sagen, wie langweilig es ist, all diese Dateien jeden einzelnen Tag sichern zu müssen. Es gibt eben so viele Informationen zu bewahren, doch, selbstverständlich, muss es gemacht werden.}
{401}{}{Natürlich. Wie auch immer, ich habe einige andere Fragen.}
{402}{}{Wir sind eine unabhängige Gemeinschaft. Jeder ist hier willkommen, solange er sich benimmt.}
{403}{}{OK.}
{404}{}{Der Abt ist ein hochgeschätztes geistiges Oberhaupt, allerdings ist er etwas launisch seit wir Bruder Thomas an das Biest verloren haben.}
{405}{}{Was für eine Art Biest?}
{406}{}{I haven't seen it, personally--there's nothing in the world that could get me to go down there and explore those
 caverns--but if I had to guess, I'd say it's probably just some overgrown radscorpion.}
{407}{}{Wenn du es nicht gesehen hast, was bringt dich dazu, zu glauben, dass es ein Radskorpion ist?}
{408}{}{Weil Geräusche aus den Höhlen widerhallten — Geräusche von zuschnappenden Klauen und klappernden Beinen.}
{409}{}{Okay.}
{410}{}{In der Tat, die haben wir. Schau auf dem Computer da drüben nach. Hier, du kannst diese Karte benutzen, um Einsicht in unsere verschlüsselten Dateien zu erhalten. [Er gibt dir eine Zugangskarte.]}
{411}{}{Toll, vielen Dank!}
{412}{}{Ich weiß nichts über Vault 13, aber im Süden liegt Vault City. Vielleicht haben sie die Informationen, die du brauchst.}
{413}{}{Danke.}
{414}{}{Dieser Computer hier neben mir sollte die Informationen haben, die du suchst, aber du brauchst dafür eine Zugangskarte. Wir sind sehr wählerisch dabei, wem wir Zugang gewähren, aber, wenn du mit dem Abt sprichst, erteilt er dir vielleicht die Genehmigung.}
{415}{}{Ok, danke.}
{420}{}{Ich vermute, dass du über die lange Zeit eine Menge Bücher gelesen hast. Deshalb würde es mich interessieren, was die faszinierendste Sache ist, die du mir erzählen kannst?}
{421}{}{Hmm, mal sehen. Wusstest du, dass eine Kerbe im Baum die selbe Entfernung vom Boden beibehält, auch wenn der Baum wächst?}
{422}{}{Sicher. Wenn ich auf irgendetwas in der Richtung stoße, werde ich es dich sicher wissen lassen.}
{423}{}{Gut... ich hab noch ein paar Fragen.}
{424}{}{Würdest du das tun? Das würde ich sehr begrüßen.}
{425}{}{Kein Problem, ich hab noch ein paar andere Fragen.}
{426}{}{Jederzeit. Ok, man sieht sich.}
{430}{}{Ich hab etwas über Botanik herausgefunden, was dich interessieren könnte.}
{431}{}{Wirklich?! Das ist großartig. Bitte, zeigs mir, schnell!}
{432}{}{Faszinierend, ich werde diese Holo-Disk sofort auf den Computer kopieren. Ich danke dir das du dir die Zeit genommen hast das für mich zu finden. Vielen Dank!}
{433}{}{Siehst du... um die Lebensraumzerstörung und Artenausrottung zu verstehen, ist man auf einen akkuraten und kompletten Pflanzen- und Taxonomiekatalog angewiesen. Und das bedeutet dann, dass...}
{434}{}{Jederzeit. Ich hab noch ein paar andere Fragen.}
{435}{}{Kein Problem, wir sehn uns.}
{436}{}{Faszinierend! Ich danke dir, dass du dir die Zeit genommen hast, das für mich zu finden. Bitte geh und lade diese Informationen auf unsere Computer hoch.}
{437}{}{Kein Problem, ich mach das jetzt. Bis dann.}
{500}{}{Hör auf damit, du Idiot!}
{550}{}{Der Computer neben mir könnte ein paar Informationen darüber haben. Du hast ja jetzt die Zugangskarte also schau nach ob du was finden kannst.}
{600}{}{Der Abt hat mir die Erlaubnis gegeben den Computer hier zu benutzen.}
{601}{}{Ah ja, ich hab davon gehört was du getan hast. Danke das du dich darum gekümmert hast. Hier ist die Zugangskarte. [Er gibt dir die Karte.] Viel Spaß!}
{602}{}{Danke, wir sehn uns.}
{650}{}{Greetings traveler! I am Brother Paul and I am in charge of the collection of information for the Abbey. What can I do for you?}
{651}{}{Schön dich kennen zu lernen, Paul. Ich habe einige Fragen.}
{652}{}{Nichts, wir sehn uns.}
{4210}{}{Ah, Nein, ich kann nicht sagen, dass ich das wusste. Das ist... interessant.}
{4211}{}{Und hast du gewusst, dass eine Gurke aus 96% Wasser besteht?}
{4212}{}{Wahnsinn, 96%, pah? Faszinierend. Aber, äh, was ist eine Gurke?}
{4213}{}{Ich habe nie eine gesehen, aber ich habe über sie gelesen. [Er sieht sich nervös um und senkt seine Stimme.] Ich weiß, wir sollen diese Bücher eigentlich nicht wirklich studieren, aber, als ich ein Buch über Botanik übertrug, konnte ich mich einfach nicht mehr davon losreißen. Die Pflanzenwelt ist einfach faszinierend. Vielleicht, wenn du auf deinen Reisen irgendwelche Botanikinformation findest, könntest du sie mir bringen? Ich wäre überaus dankbar. Selbstverständlich muss das unser Geheimnis bleiben.}
{4220}{}{Ich denke nicht, dass ich deine Pflanzenbesessenheit unterstützen werde. Tut mir leid.}
{4221}{}{Oh, na dann. Gut. Vergiss dass ich gefragt habe.}
{4222}{}{Ich möchte dich noch was anderes fragen.}
