{100}{}{Du siehst einen Mönch.}
{101}{}{Du siehst eine heilige Frau.}
{102}{}{Du siehst einen gewöhnlichen Mönch von Abbey.}
{103}{}{Du siehst eine gewöhnliche Nonne von Abbey.}
{200}{}{Grüße.}
{201}{}{Welcome to the Abbey.}
{202}{}{Du solltest mit unserem Anführer reden, wenn du Informationen erhalten möchtest.}
{203}{}{Guten Tag... oder ist es schon Nacht?}
{204}{}{Es gibt soviel Arbeit, die getan werden muss.}
{205}{}{Life here at the Abbey is a peaceful one. Something rare in these wretched wastes.}
{500}{}{Hör auf damit!}
