{100}{}{Du siehst einen Khan-Gangster.}
{101}{}{Du siehst Phil, einen Khan-Wächter.}
{102}{}{Du siehst einen rauhbeinigen, jungen Mann in einer Metallrüstung. Er ist schwer bewaffnet.}
{103}{}{Ich sollte dich erschießen, aber ich bin neugierig, was du mir zu sagen hast.}
{104}{}{Ich suchen Spion. Da lang.}
{105}{}{Ich suchen verschwunden Mädchen. Wo kann finden?}
{106}{}{Ich aus Versehn hier. Ich gehn.}
{107}{}{Böse. Ich schießen tot.}
{108}{}{Oh, wir diskutiern?}
{109}{}{Ich suche einen Lauscher, der in diese Richtung gerannt ist.}
{110}{}{Ich suche ein verschwundenes Mädchen. Hast du sie gesehn?}
{111}{}{Tschuldigung, hab versehentlich den falschen Weg erwischt. Muß weiter.}
{112}{}{Du kannst mich mal. Gleich kriegst du ein Kugelfrühstück, Arschloch.}
{113}{}{Ich würde sagen, wir können darüber wie zivilisierte Menschen reden.}
{114}{}{Ah, das bin ich. Du hast mich gefunden, was kommt als nächstes?}
{115}{}{Warum folgen Rebecca?}
{116}{}{Jetzt wissen, daß nicht falsche Person erschießen. Danke!}
{117}{}{Nichts. Ich jetzt gehn.}
{118}{}{Warum spionierst du Rebecca hinterher?}
{119}{}{Ich wollte sichergehen, daß ich die richtige Person erschieße. Danke, schönen Tag noch.}
{120}{}{Hmm. Nichts. Ich werd jetzt gehen.}
{121}{}{Meinst du, du kannst hier einfach so reinschneien und bekommst alle Antworten auf deine Fragen? Na, was soll's. Du wirst sowieso sterben und ich fühle mich großmütig. Wir haben das Kind hier im Hinterzimmer eingesperrt und etwas Spaß mit ihr gehabt. Rebecca, die alte Kuh, hat versucht, sie zu finden, also haben wir sie im Auge behalten, um zu verhindern, daß sie uns zu sehr auf die Pelle rückt.}
{122}{}{Du krank in Kopf. Ich helfen - nehmen Kopf weg.}
{123}{}{Was meinen, Spaß haben mit Mädchen?}
{124}{}{Oh, dann klar. Ich gehn.}
{125}{}{Du bist ganz schön krank, ich werd dich schlafen legen.}
{126}{}{Schön, habt ein bißchen Spaß. Ich geh jetzt.}
{127}{}{Gib das Mädchen raus und wir können diesen Ort alle lebend verlassen.}
{128}{}{Denk darüber nach, wenn du tot bist, Idiot.}
{129}{}{}
{130}{}{}
{131}{}{Warum zur Hölle sollte ich das tun?}
{132}{}{Es ist gut für deine unsterbliche Seele.}
{133}{}{Weil ich das Schlimmste bin, das dir passieren kann. Gib sie raus, oder du wirst es bereuen.}
{134}{}{Wenn wir kämpfen, wird einer sterben. Ich möchte das genauso wenig wie du, also laß es uns friedlich zu Ende bringen, OK?}
{135}{}{Hör auf damit.}
{136}{}{}
{137}{}{}
{138}{}{Das hört sich wie eine Herausforderung an. Ich nehm sie an.}
{139}{}{}
{140}{}{}
{141}{}{Hmm... Ich... Ja, OK. Hier ist der Schlüssel zu ihrer Zelle. Sie ist im hinteren Raum der Hütte. Nimm sie und verschwinde und komm nie wieder. Wenn ich dich noch einmal hier sehe, verläßt nur einer lebend das Feld.}
{142}{}{Wir werden ja sehen, wer das hier überlebt.}
{143}{}{Danke, das war eine weise Entscheidung.}
{144}{}{Du wirst diesen Ort mit den Füßen zuerst in einem Kasten verlassen.}
{145}{}{}
{146}{}{}
{147}{}{Du meinst das Mädel, das hinten eingesperrt ist, mit der wir ein bißchen Spaß gehabt haben? Nein, ich hab sie nicht gesehen.}
{148}{}{Du krank in Kopf. Ich helfen - nehmen Kopf weg.}
{149}{}{Was meinen, Spaß haben mit Mädchen?}
{150}{}{Oh. Ich gehn dann.}
{151}{}{Du bist ganz schön krank, ich werd dich schlafen legen.}
{152}{}{Schön, habt ein bißchen Spaß. Ich geh jetzt.}
{153}{}{Gib das Mädchen raus und wir können diesen Ort alle lebend verlassen.}

{154}{}{Du bist also zurückgekommen. Wir werden ja sehn, wer den kürzeren zieht.}
{155}{}{Wir haben diese Schlampe Chrissy getötet und jetzt bist du an der Reihe.}
