{100}{}{Du siehst eine illegale Siedlerin.}
{101}{}{Du siehst Roberta, die Siedlerin.}
{102}{}{Du siehst eine Frau mittleren Alters mit abgetragenen Kleidern.}
{103}{}{Oh. Tut mir leid, aber ich hab dir nichts zu sagen. Bitte geh'.}
{104}{}{Bitte geh'. Ich möchte nicht belästigt werden.}
{105}{}{Danke, daß du Rebecca geholfen hast. Ich hab dich falsch eingeschätzt.}
{106}{}{Ich bin keine Gefahr für dich. Bitte laß mich am Leben.}
