{100}{}{Du siehst einen illegalen Siedler.}
{101}{}{Du siehst Sara, die illegale Siedlerin.}
{102}{}{Du siehst eine Frau mittleren Alters mit abgetragenen Kleidern.}
{103}{}{Bitte belästige mich nicht, ich hab echt viel zu tun.}
{104}{}{Geh' weg. Hier gibt's nichts für dich.}
{105}{}{Danke, dass du Rebecca geholfen hast. Es ist wunderbar, dass du das als Fremder getan hast.}
{106}{}{Ich bin keine Gefahr für dich. Bitte lass mich am Leben.}
