# 0. Look
{100}{}{Du siehst einen Sklavenhändler.}

{150}{}{Er scheint sich besonders für die Tür nebenan zu interessieren.}

# 1. Self Initiated Floats
{200}{}{Hey! Hände weg.}
{201}{}{Das ist es!}

# 2. Open Door 1 - Self Initiated Floats
{210}{}{Probleme?}
{211}{}{Am Üben?}
{212}{}{Hmmm.}

# 3. Open Door 2 - Self Initiated Floats (From 9, 16)
{220}{}{Hier, bitte.}

# 4. Starting Node (From Where to go)
{230}{}{Hey, wie geht's voran?}
{231}{}{Hey, du machst mit, wie? Cool. Hoffe, wir machen ein paar Sklavenjagden zusammen.}
{232}{}{Also, worüber möchtest du reden?}
{233}{}{Wer ist denn da drin?}
{234}{}{Über Vic...}
{235}{}{Gut, danke.}
{236}{}{Muß los.}
{237}{}{Wuk?}
{238}{}{Icko Viek?}
{239}{}{Ugruk.}
{240}{}{Ruru!}

# 5. Who's that? & About Vic... (From 4)
{250}{}{Er heißt Vic. Ein Händler, der was von meinem Boß kaputt gemacht hat, oder sowas
 ähnliches. Bin nicht sicher.}
{251}{}{Er heißt Vic. Ein Händler, der was von meinem Boß kaputt gemacht hat, oder sowas
 ähnliches. Bin nicht sicher.}
{252}{}{Ach, der? Ja, ein Händler. Ich glaube, er hat was kaputt gemacht, bin aber nicht sicher.
 Warum? Kennst du ihn?}
{253}{}{Ach, der? Ja, ein Händler. Ich glaube, er hat was kaputt gemacht, bin aber nicht sicher.
 Warum? Kennst du ihn?}
{254}{}{Ja?}
{255}{}{Warum bewachst du ihn?}
{256}{}{Wer ist dein Boß?}
{257}{}{Kann ich ihn sehen?}
{258}{}{Ich bin ziemlich geschickt, was Reparaturen angeht. Vielleicht kann ich helfen?}
{259}{}{Ich bin wissenschaftlich ziemlich begabt, vielleicht kann ich helfen?}
{260}{}{Die Tür ist abgeschlossen. Kannst du sie öffnen?}
{261}{}{Danke.}

# 6. Guard Will let PC see Vic. (From 18)
{275}{}{Gegen Bares. Du kannst mit ihm reden. Aber keine krummen Dinger. Er kann das Zimmer ohne
 Metzgers Einverständnis nicht verlassen.}
{276}{}{Du kannst mit ihm reden, OK? Keine krummen Dinger. Er kann das Zimmer ohne Metzgers 
 Einverständnis nicht verlassen.}
{277}{}{Okay.}

# 7. Why guarding Vic (From 5)
{285}{}{Um sicherzugehen, daß ihn keiner stört, während er für den Boß arbeitet, aber
 hauptsächlich, damit er nicht abhaut.}
{286}{}{Nur um sicherzugehen, daß er nicht abhaut, nehme ich an. Er hat das Funkgerät irgendwie
 repariert.}
{287}{}{Wer ist dein Boß?}
{288}{}{Kann ich ihn sehen?}
{289}{}{Kann ich ihn sehen?}
{290}{}{Okay, danke.}

# 8. Can I see him - Slaver (From 7)
{295}{}{Oh, sicher. Ich hab nicht gemeint, daß du ihn sehen darfst, du als Sklavenhändler und so.}
{296}{}{Oh, sicher. Ich nehme es an. Er ist nicht beschäftigt und er geht nicht weg, also
 schadet es wohl nicht.}
{297}{}{Kannst du dann vielleicht die Tür aufmachen?}
{298}{}{Okay, danke.}

# 9. Unlock door, Okay to see (From 5, 8)
{305}{}{Natürlich. Ich wußte nicht, daß du jetzt sofort mit ihm reden wolltest, entschuldige. Ich
 dachte nur, du wärst neugierig oder so.}
{306}{}{Danke.}

# 10. Who's your boss? (From 5, 7, 18)
{310}{}{Hä? Du hast einfach die Gewohnheit, dich an Orten herumzutreiben, die du nicht kennst?
 Das hier ist die Sklavenhändlergilde.}
{311}{}{Oh, dann wäre dein Boß also...}
{312}{}{Ach tatsächlich? Und ich dachte, ich wäre in Kansas.}
{313}{}{Okay, danke.}

# 11. Kansas (From 10)
{320}{}{Wo? Nein, noch nie gehört. Das ist Den. Kenn mich an diesem Ort nicht besonders aus, aber
 ich komm nicht viel raus. Tut mir leid.}
{321}{}{Idiot.}
{322}{}{Ah, okay, danke.}

# 12. Don't know Boss? (From 10)
{330}{}{Verdammt, Mann. Metzger ist der Sklavenhändlermeister. Er schmeißt den Laden hier.}
{331}{}{Verdammt, Lady. Das ist der letzte Ort, an dem eine Dame sich rumtreiben sollte. Metzger
 ist der Sklavenhändlermeister.}
{332}{}{Oh, wo ist sein Büro?}
{333}{}{Okay, Tschüß.}

# 13. Where's his office? (From 12)
{340}{}{Direkt durch die Hintertür dort.}
{341}{}{Danke.}

# 14. Dumb Exit (From 4, 15, 20)
{350}{}{Tut mir leid, ich verstehe nicht.}
{351}{}{Hmpf.}

# 15. Dumb Vic ? (From 4)
{360}{}{Tut mir leid, Vic bekommt keine Besuche.}
{361}{}{Ja, das ist Vic.}
{362}{}{Seve?}
{363}{}{Surek?}
{364}{}{Gooh.}

# 16. Dumb Can See Vic (From 15)
{370}{}{Sicher kannst du ihn sehen.}
{371}{}{Sicher kannst du ihn sehen. Ich schließe rasch für dich auf.}
{372}{}{Tank.}

# 17. Repair or Science skills (From 5)
{380}{}{Ach, wirklich? Ich bin sicher, der Boß würde es begrüßen. Solange er drin bleibt. Wir
 wollen nicht, daß er noch mal wegläuft.}
{381}{}{Danke.}

# 18. Can I see Vic? (From 5, 7)
{390}{}{Nein, tut mir leid. Er ist mit einer Arbeit für den Boß beschäftigt.}
{391}{}{Tut mir leid, das kann ich nicht machen. Direkte Anweisung vom Boß.}
{392}{}{Na, du hast mein Geld?}
{393}{}{Ich muß ihm nur ein paar Fragen stellen.}
{394}{}{Ach, komm schon. Laß mich doch schnell mit ihm reden, nur ganz kurz.}
{395}{}{Ja. Hier.}
{396}{}{Nein. Ich komm zurück.}
{397}{}{Wer ist dein Boß?}
{398}{}{Macht nichts. Tschüß.}

# 19. See Vic is Never (From )
{410}{}{Hör auf, mich zu belästigen. Red mit Metzger. Er ist der Boß.}
{411}{}{Laß mich in Ruhe! Was hast du für ein Problem?}
{412}{}{Ich sagte, rede mit Metzger!}
{413}{}{OK, gut! Du kannst mit ihm reden, aber mehr auch nicht! Er setzt keinen Fuß aus diesem
 Raum. Klar? Also, mach schon!}
{414}{}{Okay.}
{415}{}{Danke!}

# 20. Wuk? (From 4)
{430}{}{Ja, red mit Metzger. Ich bin sicher, er hat Arbeit. Ich glaube, er sagte, er brauche noch
 einen Mann.}
{431}{}{Ja, red mit Metzger. Ich bin sicher, er hat Arbeit. Er sagte, er brauche noch einen
 Mann... aber ich bin sicher, du reichst auch.}
{432}{}{Rede mit Metzger.}
{433}{}{Ruru?}
{434}{}{Hä?}
{435}{}{Oh.}

# 21. Hostile (From Where to go)
{450}{}{Schnappt ihn, Jungs.}
{451}{}{Schnappt sie, Jungs.}

# 22. Just a few questions. (From 18)
{460}{}{Er ist beschäftigt.}
{461}{}{Bitte, er wird den Raum nicht verlassen. Ich versprech's.}
{462}{}{Können wir uns nicht was überlegen... finanziell vielleicht?}
{463}{}{Okay, Tschüß.}

# 23. Bribe 1 (From 22)
{470}{}{Tja, äh... Ich weiß nicht. Ich denke es würde keinem schaden, wenn du mit ihm redest.
 $300 und ich laß dich rein.}
{471}{}{Du bist verrückt. Das ist zu viel!}
{472}{}{Scher dich zum Teufel, Freundchen!}
{473}{}{Sicher.}
{474}{}{Tut mir leid, kann ich mir nicht leisten.}

# 24. Fine. (From 22)
{480}{}{Phh! Ist mir doch egal!}
{481}{}{Okay.}
{482}{}{Fein.}

# 25. No. (From 23)
{490}{}{Nein, tut mir leid.}
{491}{}{Ich sagte nein. Und jetzt zieh Leine. Du mußt mit Metzger reden.}
{492}{}{Okay.}

# 26. Vic Free (From Where to go)
{500}{}{Schade, daß du dich uns nicht angeschlossen hast.}
{501}{}{Du solltest in die Gilde eintreten.}
{502}{}{Ich mach nur dieses Wachedings.}
{503}{}{Hoffe, Vic bringt das für dich in Ordnung.}
{504}{}{Vic legt sich hoffentlich für dich ins Zeug.}
{505}{}{Vielleicht krieg ich dich auf 'ner Jagd.}
{506}{}{Wie geht's.}
{507}{}{Hallo.}
