{100}{}{Ich fühle mich so seltsam... war das ihr Gärtner oder der Schwager des Cousins zweiten
 Grades ihres besten Freundes? Mein Kopf schmerzt.}
{101}{}{Das war wunderschön... aber er hat sie nicht verdient.}
{102}{}{<schnief, schnief>}
{103}{}{Warum höre ich nicht auf, diesen Mist zu lesen?}

{200}{}{Dir ist ganz warm und benommen, nachdem Du das Buch gelesen hast, aber Du kannst nichts Nützliches daraus ziehen. Allerdings glaubst du nun die Frauen besser zu verstehen.}

