{100}{}{Du siehst einen Banditen.}
{101}{}{Na, na, was haben wir denn da?}
{102}{}{Einfache Reisende, was? Gibt's ja nicht. Hilfe bei euren Wertsachen gefällig?}
{103}{}{Paß auf, wo du dich in Reno aufhältst, sonst könnte dir was zustoßen. Bleib mir bloß vom
 Leib.}
{104}{}{Hallo, }
{105}{}{.}
{106}{}{Was machst du hier draußen, }
{107}{}{?}
{108}{}{Wir sind nur hergekommen, um uns mal anzusehen, was du so treibst, }
{109}{}{. Schöner Tag heut, was, }
{110}{}{?}
{111}{}{Biste hier rausgekommen, um mal wegzukommen von dem Ganzen, }
{112}{}{? }
{113}{}{ fragt sich, was du vorhast, }
{114}{}{.}
