{100}{}{Du siehst einen ausgedienten silberfarbenen Toaster auf dem Tisch.}
{101}{}{Du siehst Den Tapferen Kleinen Toaster.}
{102}{}{TKT, dein quickfideler, wenn auch leicht nerviger, Frühstücksbegleiter.}
{200}{}{Heido Deedlie-Dou! Ich bin Der Tapfere Kleine Toaster, dein quickfideler Frühstücksbegleiter. Aber du kannst mich auch einfach TKT nennen. Sag, möchte jemand einen Toast?}
{201}{}{Nein danke, aber ich möchte ein paar Informationen.}
{202}{}{Nicht jetzt, ich muss weg.}
{210}{}{Kein, Problem! Ich habe fundierte Kenntnisse in Quantenmechanik, submolekularer Biologie und TV-Titelmelodien. Frag mich alles. Jedoch, darf ich dir zunächst eine Frage stellen?}
{211}{}{Ich denke schon. Was kann ich für dich tun?}
{220}{}{Bist du sicher das du keinen Toast willst?}
{221}{}{NEIN! Ich will keinen Toast. Keine Muffins, keine Butterkekse. Keine Semmeln, Brötchen, Baguette oder Bagel. Keine Croissants, keine Sauerteigfladen, keine Pfannkuchen, keine Kartoffelkuchen und definitiv keine verdammten Haferriegel!!!}
{230}{}{Ah! Du bist ein Waffelmensch!}
{231}{}{Oh, ich hab genug davon.}
{232}{}{[Frustriert klatschst du deine Hand auf die Stirn.] Ich muss gehen. Ich... ich muss jetzt irgendwo anders sein. Irgendwo nur nicht hier.}
{240}{}{Nein, warte. Es tut mir leid. Ich bin kein eindimensionaler toastbesessener Apparat. Was kann ich für dich tun?}
{241}{}{Ich brauch ein paar Infos über diesen Ort. Was kannst du mir darüber erzählen?}
{250}{}{Ich kann dir eines sagen: Das ist ein schrecklicher Ort für jemanden mit meinem Fachwissen über die Toastherstellung. Hast du
 gewusst, dass es weit über ein Jahrhundert her ist, seit ich das Vergnügen hatte, Toast für jemand zu machen? Du bist der erste
 Toastabnehmer, der seit dem Krieg hier vorbeikommt, und, hier kommt die totale Krönung: solltest du tatsächlich Toast wünschen, bin ich
 nicht einmal sicher, dass ich den Auftrag ausführen kann. Weißt du, ich fühle mich inwendig etwas angeschlagen. Es ist wirklich ziemlich peinlich.}
{251}{}{Das ist, äh, sehr tragisch. Also, warum bist du hier?}
{252}{}{Ah ja. Besten Dank für die Auskunft.}
{260}{}{Ich glaube er hat vor dem Unfall eine Lieferung Atemmasken erhalten. Einige Leute meinten, dass hauptsächlich durch seine Fehler der Unfall verursacht wurde.}
{261}{}{So, warum bist du hier?}
{262}{}{Danke für die Auskunft.}
{270}{}{Warum? Um deinen Morgen so fröhlich wie nur irgend möglich zu Gestalten! Sag, nach all diesem Gerede hast du nicht vielleicht ein bisschen Platz für
 Toast in deinem Magen, oder?}
{271}{}{Ich dachte wir wären damit fertig!! Ich bin nicht hungrig und werde das niemals sein. Also, warum bist du WIRKLICH hier?}
{280}{}{Schon gut, du musst nicht schreien. Man sollte niemals seinen Tag mit Wut beginnen. Ich wurde als Frühstücks- begleiter konzipiert,
 aber ich kann auch für Mittag- und Abendessen dienen. Es gibt keinen Zeitpunkt am Tag, an dem etwas Toast unpassend wäre. Wenn du dich
 fragst, wieso ich hier sitze und mir ein Kabel seitlich raushängt, nun, anscheinend wird Mr. Handy nicht immer seinem Namen gerecht - der
 Kerl machte genau mitten während meiner jährlichen Wartungsüberprüfung schlapp. Er hoppelte natürlich zu einer Wartungsbucht und ließ mich hier hängen.}
{281}{}{Aha, verstehe. Dann also danke für deine Zeit.}
{290}{}{Kein Problem. Schau mal wieder vorbei. Vielleicht hast du dann Appetit auf Toast.}
{291}{}{Bezweifle ich. Tschüss.}
{300}{}{Ich wusste du kommst wieder. Das tun sie immer. Also, möchtest du etwas Toast?}
{301}{}{Ich wusste du kommst wieder. Das tun sie immer. Und jetzt, da ich voll funktionsfähig bin, kann ich besseren Toast denn je herstellen. Also, möchtest du etwas Toast?}
{302}{}{Nicht jetzt. Ich muss dich noch was Anderes fragen.}
{303}{}{Nein. Ich muss weg.}
{310}{}{Sicher, was möchtest du wissen? Ich hoffe es geht um Toast.}
{311}{}{Was ist das für ein Ort?}
{312}{}{Schon gut. Tschüss.}
{350}{}{Hey! Du hast mich repariert! Ich wusste dass Mr. Handy seine Arbeit unerledigt ließ. Jetzt fühl ich mich besser denn je! Danke.}
{351}{}{Sicherlich, das ist das was ich tue. Bis später.}
{352}{}{Jetzt warte doch. Wenn du mich dich nicht mit Toast belohnen lässt, dann darf ich dir wenigstens einen kleinen Tipp geben.
 Du kennst doch diese Spielautomaten die in Kasinos stehen? Nun, Ich hab eine Methode errechnet, mit der du den Maschinen ihr Glück und
 ihr Geld rauben kannst. Ich hab einen IQ von 6000, weißt du? Wenn ich nicht gerade toaste, grüble ich eben an solchen Sachen herum.
 Dafür dass du mir geholfen hast, verrate ich dir diese geheimen Nummerncodes. Benutzt einfach so eine Maschine wie sonst auch und...}
{353}{}{[Mehr]}
{354}{}{...Und so einfach ist das. Du wirst in null Komma nichts Reich und kannst nach Herzenslust Toast essen.}
{355}{}{Danke. Ich schätze das sehr. Wiedersehen.}
{400}{}{Du hast den Toaster erfolgreich repariert.}
{401}{}{Dir gelingt es nicht den Toaster zu reparieren.}
{402}{}{Der Toaster ist bereits repariert.}
{403}{}{ repariert den Toaster mit Erfolg.}
{404}{}{ scheitert an der Reparatur des Toasters.}
