{100}{}{Du siehst einen funktionierenden Computer.}
{101}{}{Du siehst das Terminal für die streng geheimen Forschungen und Entwicklungen der EPA.}
{102}{}{Willkommen am Terminal für streng geheime Forschungen und Entwicklungen der EPA. Fehler - starte Prozedur für schnellen Zugriff.
 Bitte suchen sie nach etwas spezifischem.}
{103}{}{Nach irgendetwas wichtigem suchen.}
{104}{}{Abmelden.}
{105}{}{[Nach etwa einer halben Stunde stöberns, entdeckst du vier Dateien die dir nützlich erscheinen.] Bitte treffen Sie eine Wahl.}
{106}{}{Öffne FEV-Aufzeichnungen.}
{107}{}{Öffne Epilepsieheilung.}
{108}{}{Weitersuchen.}
{109}{}{Bitte treffen Sie eine Wahl.}
{110}{}{Als die Spannungen zwischen den USA und China weiter zunahmen, hatte unsere militärische Führung die begründete Befürchtung, das China biologische Kampfstoffe entwickeln und
 sie gegen US-Amerikanische Truppen einsetzen würde. Aufgrund dessen wurde West Tek, ein führendes HighTech- Rüstungsunternehmen unter Vertrag genommen
 um einen entgegenwirkenden Wirkstoff zu Entwickeln. Dies führte zu West Tek's Forschungen am Panimmunitäts-Virus-Projekt (PVP), mit der Absicht
 Soldaten eine virale Immunität zu verleihen, indem ihre DNA modifiziert wird. Während der PVP-Versuche im Jahre 2076, wurden ungewöhnliche Nebenwirkungen
 beobachtet. Die Versuchstiere wuchsen drastisch an und ihre Hirnfunktionen steigerten sich.}
{111}{}{[Mehr]}
{112}{}{Angesichts dieses Potenzials, übernahm die Armee sofort das Projekt und gab ihm den Namen FEV: Forcierendes- Evolutions-Virus.
 Nun nicht mehr nur auf Immunität gegen Viren und Krankheiten abzielend, sollte das FEV Soldaten potentiell in unnatürlich starke und intelligente 'Übermenschen' verwandeln.
 Nachdem die Tierversuche zu ihrem erwarteten Abschluss kamen, wurde die FEV-Forschung an ihren heutigen Standort, der Mariposa Militärbasis verlegt.
 Dort, so haben wir erfahren, setzt man die Versuche auf der nächste Stufe fort, indem sie streng geheime Versuche an militärischen Häftlingen durchführen. Wir warten unge- duldig auf die Ergebnisse dieser spannenden Experimente.}
{113}{}{Zurück.}
{120}{}{Einer unserer Forscher, Dr. Hodking, machte eine wundervolle Entdeckung in seinen jüngsten Forschungen bezüglich menschlicher
 Gehirnvorgänge zu verbalen Reaktionen. Durch das Wiederholen einer Serie von Buchstaben im dazugehörigem Tonfall, kann ein Zuhörer 
 augenscheinlich von einer Anzahl neurologischer Krankheiten, wie Autismus oder Epilepsie, geheilt werden. Dieser Aufzeichnung beiliegend;
 ist die exakte Abfolgekette der Buchstaben (und der dazugehörigen Betonung) die Dr. Hodkin in seinen Experimenten benutzte. Dies ist eine
 wunderbare Nachricht und ein großartiger Start zu weiteren Forschungen bezüglich der Behandlung chronisch-neurologischer Beschwerden.}
{121}{}{Das könnte nützlich sein. Notier dir die Abfolgekette und such nach was anderem.}
{130}{}{Du findest nichts weiter interessantes.}
{131}{}{Du findest noch immer nichts weiter interessantes.}
{132}{}{Wenn du noch ein bisschen mehr suchst, findest du vielleicht was.}
{133}{}{Vielleicht noch ein Versucht?}
{134}{}{Nach mühsamer Suche, stößt du auf eine versteckte Datei.}
{135}{}{Öffne Datei mit dem Namen: Massen-Fluoridierungs-Projekt.}
{136}{}{Im fortlaufendem Bestreben die Bürger der Vereinigten Staaten besser zu kontrollieren, führte der Versuch, alle verfügbaren
 Trinkwasseranlagen mit Natriumfluoriden zu Versetzen, umgehend zu Resultaten. Langzeitforschungen ergaben, dass die
 Testsubjekte "dümmer und gefügiger" wurden. Darüber hinaus wurden, in Verbindung mit den Natriumfluoriden, leichtgradige Schädigungen an
 einer spezifischen Stelle im Gehirn festgestellt. Diese Schädigung erschwert es einer betroffenen Person noch mehr, seine eigene Freiheit
 zu Verteidigen und sorgt dafür das der Einzelne, gegenüber Autoritäten, gefügiger wird.}
{137}{}{[Mehr]}
{138}{}{In unserem jüngsten Experiment, wählten wir General J. Ripper als Testobjekt aus. Anfangs hatte er von unseren Absichten
 keine Ahnung, aber anscheinend hat er nun die Finte gerochen. Er war besessen von dem Satz "kostbare Körperflüssigkeiten" und vermied jegliche
 Flüssigkeit, von der er nicht wusste woher sie stammte, zu trinken. Er gab sogar den Geschlechtsverkehr auf, aus Furcht davor das die Frauen
 nach der "Essenz des Lebens" trachten.}
{139}{}{Zurück.}
{150}{}{Öffne Geschlechtsumwandlung.}
{151}{}{Öffne Virusbelastete Fruchtfliegen.}
{160}{}{Dr. Glen Wood hat einen revolutionären Durchbruch bei seiner Forschung über Geschlechtsumwandlung erzielt, und er behauptet, dass es die Spionagebemühungen der Staaten revolutioniert. Mit einem simplen Verfahren, kann ein Mann eine Frau werden, oder umgekehrt. Dr. Wood bestand darauf, der erste zu sein, der sich dem radikalen Wandel unterzieht. Er hat darum gebeten, dass man ihn - oder sie, sobald die Operation vollendet wurde, mit Glenda anspricht.}
{170}{}{Die mutierten Fruchtfliegen übertragen jetzt erfolgreich das Virus. Aber, bevor wir sie auf feindlichem Boden ein- setzen, wurde beschlossen, dass wir sie zunächst in einer kleinen, isolierten amerikanische Gemeinde aussetzen, wo wir die Auswirkungen außerhalb der Laborumgebung beobachten können. Die zivilen Opfer, die sich aller Voraussicht nach dabei ergeben, sind bedauernswert, jedoch erforderlich. Außerdem wäre jeder wahre Amerikaner stolz darauf, sein Leben für das Wohl unserer großen Nation hinzugeben.}
{200}{}{Du erfährst die wahren Absichten hinter der Wasserflouridierung.}
{311}{}{Whirrrr....}
{312}{}{PIEP!!}
{313}{}{Klonk...}
{1311}{}{Nicht Aufgeben. Wenn es was gibt, finde ich es.}
