{100}{}{Willkommen am EPA-Roboterkontrollcomputer. Was möchten Sie tun?}
{101}{}{Roboter befehligen.}
{102}{}{Diagnoseprüfung durchlaufen.}
{103}{}{[Beenden.]}
{104}{}{!FEHLFUNKTION! !FEHLFUNKTION! FEHLER ENTDECKT   SEQUENZ ABGEBROCHEN!}
{105}{}{Zurück zum Hauptmenü}
{106}{}{Diagnoseprüfung... Schaltkreisfehler....Sektion Vier... unterbrochene Leitungen.}
{107}{}{[Fertig]}
{108}{}{Es ist zu schwierig den Fehler zu reparieren.}
{109}{}{Der Fehler im Computer ist behoben und die Maschine ist wieder online.}
{110}{}{Willkommen am EPA-Roboterkontrollcomputer. Sie haben keine gültige Sicherheitsauthorisierung um diese Daten zu benutzen. Sequenz abgebrochen.}
{111}{}{[Fertig]}
{112}{}{PIEP!}
{113}{}{BOOP!}
{114}{}{Bzzzt..}
