{100}{}{Du siehst einen Computer.}
{101}{}{Du siehst den EPA Museumscomputer.}

{200}{}{Willkommen im EPA Museum. Dieses Terminal wird Ihnen einen Film mittels
 einer spannenden neuen Holographietechnologie präsentieren! Der Film ist eine
 unterhaltsame und informative Vorrausschau auf die beängstigende, aber
 mögliche Realität einer postnuklearen Welt.}
{201}{}{[Film abspielen.]}
{202}{}{[Ausloggen.]}

{210}{}{[Das Terminal projiziert das Hologramm eines großen bebrillten Mannes in einem
 Laborkittel. Er winkt und lächelt freundlich in Deine Richtung] Hallo, ich bin Dr. Caleb 
 und ich werde Sie durch dieses Video eines post-holocaust Amerikas begleiten.}
{211}{}{[ Mehr.]}
{220}{}{[Ein Wohnzimmer materialisiert sich um DR. Caleb herum, in dem eine Familie
 sich entspannt auf den Abend vorbereitet. Dr. Caleb legt seine Hand auf den Kopf
 eines Hundes und lächelt Dich an.] Vater raucht seine Pfeiffe, Mutter liest in ihrem
 Kochbuch während der kleine Billy und Susi noch ein bißchen fernsehen vor dem
 Zubettgehen. Sie glauben, daß alles in Ordnung ist. Sie ignorieren die heulenden
 Sirenen, glauben, es sein nur eine weitere Übung. Oh, aber was ist das?}
{221}{}{[Mehr]}

{230}{}{[Durch das Hinterfenster siehst Du eine große Bombe auf dem Boden aufschlagen,
 die einen riesigen Atompilz hervorruft, der von einem grellen, blendendem Licht
 gefolgt wird.Nachdem das grelle Licht schwächer geworden ist, siehst Du Dr.
 Caleb in der verbrannten Ruine des Wohnzimmers stehen, umringt von der nun zu
 Skeletten verwandelten Familie] Uh-Oh, sieht aus, als ob die Roten nun die große
 Bombe gezündet hätten und die Johnsons waren doch nicht ganz so sicher, wie sie
 annahmen. Nun, was können wir von dem Fehler der Familie Johnson lernen?}
{231}{}{[Mehr]}

{240}{}{Das stimmt. Im Falle eines Nuklearkriegs, möchten Sie, daß Ihre Familie sicher
 ist, im Schutz eines Vault-Tec Bunkers. Vault-Tec hat 122 öffentliche Bunker,
 überall über unser großartiges Land verteilt, errichtet, so daß sich einer sicher auch
 in Ihrer Nachbarschaft befinden müßte. Wie Sie sich sicher vorstellen können, sind
 die Plätze nur sehr eingeschränkt verfügbar, so daß Sie Ihre Plätze noch heute
 reservieren sollten, um *Ihre* Familie nicht enden zu sehen, wie die Johnsons hier.
 [Dr. Caleb tätschelt den Kopf des Hundeskeletts. Dessen Schädel löst sich vom
 Torax und fällt auf den Boden. Ein Staubsaugerroboter schwebt herbei und saugt
 die Skelettreste auf.}
{241}{}{[Mehr]}

{250}{}{Sieht aus, als ob Mr. Handy dieses Stück (Film) rausschneiden muß, um *diesen*
 Schlamassel beseitigen zu können. [Dr. Caleb lacht als das Bild verschwindet und
 durch einen Text ersetzt wird.]: Danke fürs Zuschauen. Dieses Lernvideo wurde
 Ihnen präsentiert von den netten Leuten bei Vault-Tec. Vault-Tec, Amerikas
 ultimative Lösung, wenn es um Ihr zu Hause geht.}
{251}{}{[Ausloggen.]}