{100}{}{Du siehst eine unruhige Shi-Wache.}
{101}{}{Die Augen der Wache irren nervös durch die Dunkelheit.}

{200}{}{Dieser Ort ist heilig. Unglaublich furchterregend, aber heilig.}
{201}{}{Schauen wir, dass wir's hinter uns bringen.}
{202}{}{Ich fühle die Geister meiner Vorfahren in unserer Mitte.}
{203}{}{Los, mach dein Technologieding, damit wir zum Festland zurückkehren können.}
{204}{}{Hast du das gehört? Ich schwöre, ich habe etwas gehört.}
{205}{}{Warum werde immer ich dazu eingeteilt? }


