{100}{}{Du siehst einen alten verhutzelten Mann in einem weißen Kittel.}
{101}{}{Das ist Dr. Fung.}
{102}{}{Du siehst einen alten verhutzelten Mann in einem weißen Kittel.}
{103}{}{Kann ich dir irgendwie helfen?}
{104}{}{Aua! Autsch! Aaaaaah!}
{105}{}{Ja, ich bin verletzt und wie's aussieht, bist du Arzt.}
{106}{}{Ja. Mein Freund braucht dringend einen Arzt.}
{107}{}{Hast du Stimpaks? Ich möchte gern welche kaufen.}
{108}{}{Wer bist du?}
{109}{}{Einem Freund von mir fehlt die Milz. Kannst du ihm helfen?}
{110}{}{Was kannst du mir über diesen Ort hier sagen?}
{111}{}{Tschüss.}
{112}{}{Lass mich einen Blick darauf werfen. Hmm. Ja. Ich werde dir das natürlich berechnen.}
{113}{}{Wieviel?}
{114}{}{Vergiss es.}
{115}{}{Ich kann heilen... aber nur gegen Bezahlung, wenn du verstehst.}
{116}{}{Wieviel?}
{117}{}{Vergiss es.}
{118}{}{Wer ich bin? Ich bin Dr. Fung. Ich lehre und heile.}
{119}{}{Dr. Fung? Kennst du Doc Holliday?}
{120}{}{Sehr erfreut. Ich suche Heilung.}
{121}{}{Ein Freund von mir braucht Heilung.}
{122}{}{Alles klar. Danke. Wiedersehn.}
{123}{}{Holliday? Ja! Ich habe ihm alles beigebracht, was er weiß! Wo ist er jetzt?}
{124}{}{Er lebt in Broken Hills.}
{125}{}{Er ist also zurück nach Hause gegangen. Hoffentlich hat er dort Frieden gefunden.}
{126}{}{Ich glaube schon. Ich habe weitere Fragen.}
{127}{}{Wahrscheinlich. Ich muss jetzt gehen. Bis dann.}
{128}{}{Das macht 100 Dollar.}
{129}{}{In Ordnung.}
{130}{}{Vergiss es.}
{131}{}{Scheint was Ernstes zu sein. Das kostet 200 Dollar.}
{132}{}{In Ordnung.}
{133}{}{Vergiss es.}
{134}{}{Das sind schwere Verletzungen. Für nur 300 Dollar stehen dir meine Dienste zur Verfügung.}
{135}{}{In Ordnung.}
{136}{}{Vergiss es.}
{137}{}{Ich befürchte, dass ich für so schwere Verletzungen  400 Dollar verlangen muss.}
{138}{}{In Ordnung.}
{139}{}{Vergiss es.}
{140}{}{Setz dich lieber hin, bevor ich dir meinen Preis nenne. Verkrüppelte Gliedmaßen kosten 600 Dollar.}
{141}{}{In Ordnung.}
{142}{}{Vergiss es.}
{158}{}{Was? Du hast das Geld nicht? Was glaubst du denn, wie ich leben soll, wenn ich umsonst heile?}
{159}{}{Hast du Stimpaks?}
{160}{}{Nein, danke.}
{161}{}{Es war mir ein Vergnügen, mit dir Geschäfte zu machen.}
{162}{}{Danke.}
{163}{}{Dein Angebot ist leider inakzeptabel.}
{164}{}{Wie wär's damit?}
{165}{}{Das ist alles, was ich dir anbieten kann. Bis dann.}
{166}{}{Bist du verletzt? Ts-ts. Dieses alte Hausmittel wird helfen.}
{167}{}{O-K!}
{168}{}{}
{169}{}{Wir sind fertig. Geh jetzt und sei vorsichtig!}
{170}{}{Tanke!}
{171}{}{Brauchst du noch was?}
{172}{}{Ich brauche Heilung.}
{173}{}{Ein Freund von mir braucht Heilung.}
{174}{}{Wer bist du?}
{175}{}{Erzähl mir was über diesen Ort.}
{176}{}{Einem Freund von mir fehlt die Milz. Kannst du ihm helfen?}
{177}{}{Nein. Trotzdem danke.}
{178}{}{Hier bist du an der richtigen Adresse. Möchtest du die lange oder die kurze Version der Geschichte?}
{179}{}{Die lange.}
{180}{}{Die kurze.}
{181}{}{Weder noch. Ich habe aber andere Fragen.}
{182}{}{Als Raketen die Erde verwüsteten, strandete unser Volk mit dem U-Boot Shih-Huang-Ti an diesem Ort. Mit Hilfe eines Kults konnten wir, die Shi, San Francisco wieder aufbauen. Das ist die kurze Version.}
{183}{}{Und wie ist die lange Version?}
{184}{}{Danke. Ich habe noch weitere Fragen.}
{185}{}{Danke.}
{186}{}{Die lange Version ist folgende: Wir sind hier, weil wir die Nachkommen der Besatzung des Atom-U-Bootes Shih-Huang-Ti sind. Als die Raketen fielen,  während der Großen Flut, versagten die Systeme an Bord des U-Bootes, so dass wir viele Tage im Dunkeln herumtrieben.}
{187}{}{[Weiter]}
{188}{}{Schließlich trieben wir an Land. Wir befanden uns in der Nähe des zerstörten San Francisco. Der größte Teil der Stadt war im Krieg verwüstet worden. Also mussten wir mit den wenigen Überlebenden, die in die Stadt zurückgeirrt waren, eine neue Gesellschaft aufbauen.}
{189}{}{[Weiter]}
{190}{}{Zum Wiederaufbau nahmen wir alles, was wir finden konnten. Um unsere Wissenschaftler und unsere Technologie beneidet uns heute die ganze Welt. Wir bauen eine neue Zivilisation auf, ganz anders als es dieser grauenvolle Meister tat.}
{191}{}{Aha. Ich habe noch weitere Fragen.}
{192}{}{Danke. Tschüss.}
{193}{}{Natürlich kann ich das. Und weil du Doc Holliday kennst, werde ich es aus reiner Freundschaft machen. Bitte deinen milzlosen Freund, hierher zu kommen, dann werde ich ihm eine neue einsetzen.}
{194}{}{Danke! Ich habe weitere Fragen.}
{195}{}{Danke auch!}
{196}{}{Das ist kein Problem. Allerdings kostet es 1000 Dollar und zwar im voraus. Bist du einverstanden?}
{197}{}{Ja.}
{198}{}{Nein.}
{199}{}{Sag deinem Freund, er soll herkommen, dann werde ich ihm eine neue einsetzen.}
{200}{}{Danke. Ich habe noch weitere Fragen.}
{201}{}{Danke.}
{202}{}{Ich kann nichts für ihn tun, solange du die 1000 Dollar nicht hast. Auf Wiedersehen.}
{203}{}{Auf Wiedersehen.}
{204}{}{Ich behandle keine Feinde meines Volkes. Tut mir sehr leid.}
{205}{}{Ehrenwerter Herr, ich empfehle dir, einen Arzt aus deinem Kult aufzusuchen.}
{206}{}{Was weißt du über Rüstungsimplantate?}
{207}{}{Ich habe den Artikel über gepanzerte Implantate mitverfasst. Alles, was ich brauche ist mein Können und deine Materialien. Was für Implantate willst du?}
{208}{}{Was für welche gibt es denn?}
{209}{}{Standard-Hautstabilisatorimplantate.}
{210}{}{Die erweiterte Hautstabilisatorrüstung mit zusätzlichen Abwehrplatten.}
{211}{}{Phoenix-Implantate.}
{212}{}{Erweiterte Phoenix-Implantate mit zusätzlichen Wärmeableitern.}
{213}{}{Hmm... vergiss es. Ich habe weitere Fragen.}
{214}{}{Im Augenblick keine. Wiedersehn.}
{215}{}{Wir haben die Hautstabilisatorrüstung, die gegen Aufprallverletzungen schützt. Wenn dir das zusagt, können wir eine einfache Verstärkung hinzufügen. Wir haben auch Phoenix-Implantate, die gegen Hitzeverletzungen schützen und die auch aufgerüstet werden können. Wenn du dich für die Aufrüstung interessierst, musst du natürlich solange warten, bis das Basis-Set eingepflanzt ist. Und um deiner nächsten Frage zuvorzukommen: ja, du KANNST alle vier Operationen bekommen.}
{216}{}{Klasse. Ich nehme die Hautstabilisatorrüstung.}
{217}{}{Ich will die Hautstabilisatorrüstung.}
{218}{}{Gib mir die erweiterte Hautstabilisatorrüstung.}
{219}{}{Ich hätte gern die Phoenix-Implantate.}
{220}{}{Zeit für die erweiterten Phoenix-Implantate.}
{221}{}{Hmm... vergiss es. Ich habe weitere Fragen.}
{222}{}{Im Augenblick keine. Wiedersehn.}
{223}{}{Großartig. Dazu brauche ich eine Kampfrüstung und ach so, 5500 Dollar. Das  Ganze wird zwei Tage dauern und du darfst nicht am Schorf herumkratzen.}
{224}{}{Na, dann los.}
{225}{}{Vergiss es. Bis dann.}
{226}{}{Die Hautstabilisatorrüstung also? Das wird dich einige Tage deines Lebens kosten, außerdem noch 33000 Dollar, eine Kampfrüstung und eine Menge nagelneuer Narben, die du tragen wirst, solange du lebst.}
{227}{}{Ach ja? Das kann ich mir ALLES leisten.}
{228}{}{Hmm. Ich glaube kaum, dass ich soviel bezahlen will. Bis dann.}
{229}{}{Wenn du dich von 8500 Dollar, ein paar Tagen deines Lebens und  einem Kampfrüstungsset trennen kannst, können wir gleich mit der Operation beginnen}
{230}{}{Dann leg mal los, Doc. Ich bin bereit.}
{231}{}{Das ist aber ganz schön heftig. Ich werd's mir noch mal überlegen.}
{232}{}{Das ist eine schwierige Operation. Das wird dich dein "gutes Aussehen", eine Kampfrüstung und 49000 Dollar kosten. Bist du bereit, das anzulegen?}
{233}{}{Zur Hölle, ja. Packen wir's an.}
{234}{}{Wow. Das ist... teuer. Ich werd's mir noch mal überlegen.}
{235}{}{[Er schüttelt den Kopf] Treib keine Spielchen mit mir. Dir fehlen wichtige Bestandteile. Du solltest mir beim nächsten Mal besser zuhören. Geh jetzt und komm wieder, wenn ich dir helfen kann.}
{236}{}{OK.}
{237}{}{Alles klar! Du bist... gestärkt. Denk dran... wenn du zu deinem nunmehr nicht ganz so tollen Aussehen nicht auch noch hässliche Narben haben willst, dann darfst du den Schorf nicht aufkratzen.}
{238}{}{Danke, Doc. Bis dann.}
{239}{}{Ich habe das Geld für die Milz.}
{240}{}{Bist du wieder an Implantaten interessiert?}
