{100}{}{Du siehst einen fast kahlrasierten Vagabunden.}
{101}{}{Du siehst Ryan, den Brunnen der Weisheit.}
{102}{}{Du siehst einen Vagabunden, dem Frechheit und Gelächter ins Gesicht geschrieben steht.}
{103}{}{Du musst dich durch den Mist durchboxen, Mann.}
{104}{}{Dieser Ort ist ein Dreckloch.}
{105}{}{Ich werd's dir geben, bis aufs Blut. Wie? Hast du was gesagt?}
{106}{}{Ay caramba! Nalgas con queso!}
{107}{}{Wuh huh huh huh huh!}
{108}{}{Ich bin hier weg.}
{109}{}{Ich kannte Big Jesus Mordino schon, als er noch Baby Jesus war.}
{110}{}{Heilige Maria, Mutter Gottes!}
{111}{}{Ich bin Produzent. Ich mache Spiele. Spiele machen Spaß. Willst du nicht meine Spiele
 spielen? }
{112}{}{Heiße Sachen für heiße Typen...}
{113}{}{Man nennt mich den...POLNISCHEN HAMMER.}
{114}{}{Ich bin nach San Fran gekommen, um ein paar Spiele zu machen und ein bisschen auf den Putz
 zu hauen.}
{115}{}{Sommerliebe...}
{116}{}{Hola, Señor! Oder vielleicht Señorita?}
{117}{}{Paha!}
{118}{}{Mann...das hier ist wie ein Potemkinsches Dorf - viel Wind und nichts dahinter.}
{119}{}{Mein Freund Scott dachte, Potemkin sei die Hauptstadt von Altkalifornien. Ich schwör's
 dir!}
{120}{}{Diesem Chip würd ich gern 'ne Ladung heißen Glibber ins Gesicht blasen.}
{121}{}{Kumpel!}
{122}{}{Och, KOMM schon!}
{123}{}{Aggressssioooooon!}
{124}{}{Zwing mich nicht, das Schmollgesicht aufzusetzen.}
{125}{}{Jo, nich'?}
{126}{}{Ganz genau. Hä hä hä.}
