{100}{}{Du siehst einen PoseidoNet- Computer.}
{101}{}{Du siehst einen PoseidoNet- Computer.}
{102}{}{Du siehst einen PoseidoNet- Computer.}


{103}{}{::Piep:: Terminal-Störung. NavComp-Installation erforderlich. ::Piep::}
{104}{}{[Fertig]}
{105}{}{Willkommen bei PoseidoNet. Dieses Terminal überträgt nur Daten zwischen dem Tanker PHS Valdez und dem Dockturm. Befehl?}
{106}{}{Start.}
{107}{}{Status prüfen.}
{108}{}{Abmelden.}
{109}{}{-Treibstofftanks: Leer- -Laderaum: Leer- -Navigationscomputer: Nicht in Bereitschaft- -Leinen: Fest-}
{110}{}{[ZURÜCK]}
{111}{}{Abmelden.}
{112}{}{-Treibstofftanks: Voll- -Laderaum: Leer- -Navigationscomputer: Nicht in Bereitschaft- -Leinen: Fest-}
{113}{}{[ZURÜCK]}
{114}{}{Abmelden.}
{115}{}{FEHLER: Treibstofftanks leer.}
{116}{}{FEHLER: Navigationscomputer nicht in Bereitschaft.}

{117}{}{-Treibstofftanks: Leer- -Laderaum: Leer- -Navigationscomputer: In Bereitschaft- - Leinen: Fest-}
{118}{}{-Treibstofftanks: Voll- -Laderaum: Leer- -Navigationscomputer: In Bereitschaft- - Leinen: Fest-}

{119}{}{Du siehst einen PoseidoNet- Navigationscomputer.}

{129}{}{[Du gibst schnell die Sequenz zum Lösen der Leinen ein und das Schiff bewegt sich vom Landesteg weg.]}
{130}{}{[Fertig]}
{131}{}{Navigationscomputer online.}

{200}{}{ACHTUNG: U-Boot noch aktiv. Ausführung würde zur Zerstörung des Schiffes führen.}