{100}{}{Du siehst einen besonders kleinen, älteren Ghul.}
{101}{}{Du siehst Lenny, Harolds Assistenten.}
{102}{}{Du siehst einen kleinen, älteren Ghul. Er scheint in Gedanken versunken.}

{110}{}{Hallo. Ich heiße Lenny. W-was kann ich für d-dich tun?}
{111}{}{Hallo. W-was kann ich für dich t-tun?}
{112}{}{Ich hab gehört, du bist ein Nachkomme des Vaultbewohners. Weißt du, ich hab den Vaultbewohner einmal getroffen.}
{113}{}{Hallo. I-ich komme g-gar nicht drüber hin-hinweg, wie ähnlich d-du dem Vaultbewohner siehst. Wa-was kann ich f-für dich tun?}
{114}{}{Grenny? Heeo.}
{115}{}{Was machst du hier?}
{116}{}{Ich bin verletzt. Kannst du mir helfen?}
{117}{}{Einer meiner Freunde ist verletzt. Kannst du ihm helfen?}
{118}{}{Meine Freunde sind verletzt. Kannst du ihnen helfen?}
{119}{}{Lenny, hast du je von einem Garden-Eden-Creation-Kit gehört?}
{120}{}{Du hast meinen Vorfahren getroffen? }
{121}{}{Ich schau mich nur um. Tschüß.}
{122}{}{Kennst du dich mit Heilkunde aus?}

{125}{}{Ja. Was brauchst du?}
{126}{}{Ich denke, im Moment gar nichts.}

{130}{}{D-du hät-hättest dein Dorf n-nicht verl-lassen sollen. G-geh nach Hause.}
{131}{}{Nach Hause? Tschüß.}

{140}{}{D-du s-solltest nach H-hause gehn.}
{141}{}{Ich h-hab k-keine Zeit für dich.}
{142}{}{Sch-schuu! Geh weg!}

{150}{}{Ein G-garden-Eden-C-creation-Kit? Ich hab gehört, daß Vault City so was hatte. Das ist aber das einzige, von dem ich gehört hab.}
{151}{}{Ich bin verletzt. Kannst du mir helfen?}
{152}{}{Einer meiner Freunde ist verletzt. Kannst du ihm helfen?}
{153}{}{Also, mein Vorfahre, der Vaultbewohner, sagte, daß uns Vault 13 was schuldet. Ich muß die Vault finden.}
{154}{}{Das ist alles, was ich wissen muß. Tschüß.}

{160}{}{Ja, i-ich helf H-harold meistens. W-wenn L-leute verletzt w-werden, h-helf ich ihnen.}
{161}{}{Wobei hilfst du Harold?}
{162}{}{Ich möcht dich noch was andres fragen.}
{163}{}{Du kannst Leute heilen?}
{164}{}{Ich bin verletzt. Kannst du mir helfen?}
{165}{}{Einer meiner Freunde ist verletzt. Kannst du ihm helfen?}
{166}{}{Das muß ich mir merken, wenn ich verwundet werde. Danke. Tschüß.}

{170}{}{L-laß mich m-mal sehn. Ich g-glaub, ich kann dir helfen.}
{171}{}{Was wird mich das kosten?}
{172}{}{Danke, Lenny. Ich möcht dich noch was anderes fragen.}
{173}{}{Danke, Lenny. Tschüß.}
{174}{}{Ich k-kann dir helfen. Aber es k-kostet dich $30. F-für die Versorgung.}
{175}{}{Ich glaub, im Moment brauch ich deine Hilfe nicht. Tschüß.}

{180}{}{Dein F-freund könnte ein wenig H-hilfe gebrauchen. Ich k-könnt ihm h-helfen.}
{181}{}{S-sieht so aus, als h-hättet ihr Ärger gehabt. Ich k-krieg sie wieder hin.}
{182}{}{Was wird mich das kosten?}
{183}{}{Danke, Lenny. Ich hab noch 'ne Frage.}
{184}{}{Danke, Lenny. Tschüß.}
{185}{}{Dein F-freund ist verletzt. Ich könnt ihn f-für $30 heilen. Das Geld b-brauch ich für M-medikamente.}
{186}{}{Was ist denn mit euch p-passiert? S-sieht a-aus, als könntet ihr wirklich 'n-n A-arzt vertragen. F-für $60 heile ich euch alle auf einmal.}
{187}{}{Dein F-freund scheint ganz OK zu sein.}

{190}{}{Äh, ich hab den V-Vaultbewohner nie kennengerlernt. Aber ich hab ihn einmal gesehen.}
{191}{}{Du hast den Vaultbewohner gesehen? Wo?}
{192}{}{Oh, ich verstehe. Ich muß noch woanders hin und einige Dinge erledigen. Tschüß.}

{200}{}{V-vor dem K-krieg war ich Arzt.}
{201}{}{Vor dem Krieg? Das muß ja 160 Jahre her sein.}
{202}{}{Das erklärt einiges. Danke. Tschüß.}

{210}{}{Das stimmt. A-aber die R-radioaktive Strahlung scheint uns Ghuls ein längeres Leben zu geben. Aber a-alles andere ist vernichtet.}
{211}{}{Vernichtet?}
{212}{}{Alles hat seine guten und schlechten Seiten. Tschüß.}

{220}{}{J-ja. W-wir sehn aus w-wie verdammte M-mißgeburten. Wir h-haben k-keine Haut, zum Teufel.}
{221}{}{Ja, ich denke, du hast schon besser Zeiten erlebt.}
{222}{}{Ihr seid nicht gerade die schönsten auf diesem Planeten. Tschüß.}

{230}{}{D-das kannst du laut sagen. Ich würd all d-diese Jahre g-geben, um wieder ein n-normaler Mensch z-zu sein.}
{231}{}{Da besteht nicht viel Hoffnung, denk ich.}
{232}{}{Das glaub ich. Tschüß.}

{240}{}{Wenn diese I-idioten in Vault City ihre M-medizintechnologie mit uns teilen w-würden, k-könnten wir bestimmt die überschüssige R-radioaktivität b-beseitigen und w-wir könnten geheilt werden.}
{241}{}{Sie wollen euch nicht helfen?}
{242}{}{Ich glaub, ich hab genug gehört. Tschüß.}

{250}{}{D-du warst in Vault City? D-dann sag mir, f-für wie wahrscheinlich d-du's hältst, von diesen Bastarden Hilfe zu bekommen. G-genausogut kann ein P-papierhund eine Asbestkatze durch die Hölle jagen.}
{251}{}{Tut mir leid, das hören zu müssen, aber ich glaub, du hast recht. Ich hab noch 'ne Frage.}
{252}{}{Tut mir leid, das zu hören. Tschüß.}

{260}{}{N-nein. D-das Leben ist zu kurz - he, he - naja, z-zumindest für die m-meisten Leute -, um vor diesen kleinen Dingen Angst zu haben. Weißt du was? Das ist alles Kleinkram. Das k-kostet nichts.}
{261}{}{Danke Lenny.}

{270}{}{Es i-ist lange her. Der Ort h-hieß N-nekropolis. V-viele von uns Ghuls haben d-dort gelebt. Eines Tages habe ich jemanden durch die Stadt rennen sehen.}
{271}{}{Rennen?}
{272}{}{Ich glaub, ich hab genug von deinen verschwommenen Erinnerungen. Tschüß.}

{280}{}{Ja, rennen. Weißt du, w-wir Ghuls k-können nicht mehr rennen. Also wußte ich, d-daß es ein Fremder sein muß, als ich ihn sah. Er kam so dicht heran, daß ich ihn b-beinahe anfassen konnte. Ich hätt mich dem V-Vaultbewohner anschließen sollen...}
{281}{}{Du wolltest dich meinem Ahnen anschließen?}
{282}{}{Haha, als ob mein Vorfahr das einer klumpigen Mißgeburt wie dir erlaubt hätte. Tschüß.}
{283}{}{Äh, ich würde schon gern die ganze Geschichte hören, aber ich hab noch einiges zu erledigen. Tschüß.}

{290}{}{Ja, ich h-hatte die Chance m-meines Lebens und ich hab sie vertan.}
{291}{}{Was meinst du damit?}
{292}{}{Tja, das Leben ist hart. Tschüß.}

{300}{}{Sp-später hab ich g-gehört, daß der Vaultbewohner unser Wassersystem repariert hat. Der V-Vaultbewohner hat uns gerettet - uns alle. Verstehst du? Es spielte keine Rolle, daß wir Ghuls waren. Dieses eine M-mal hat es keine Rolle gespielt. W-wir waren Menschen, die es wert waren, ge-gerettet zu werden.}
{301}{}{Mein Vorfahr gründete unsere Sippe. Wir gedenken seiner in Ehren.}
{302}{}{Mir geht es nur darum, meine Sippe zu retten. Der Rest der Welt kann sich selbst verteidigen. Tschüß.}

{310}{}{Sp-päter hörte ich, daß der Vaultbewohner die Quelle der M-mutantenarmee zerstört hat. Der Vaultb-bewohner hat uns alle gerettet. Menschen und Ghuls... Ich hä-hätte dabei sein können, aber mir f-fehlte der M-mut. Ich hab mir das nie v-verziehen.}
{311}{}{Ich trete in die Fußstapfen meines Vorfahren. Möchtest du eine zweite Chance? Willst du mitkommen?}
{312}{}{Ich bin sicher, daß die Arbeit, die du hier unter den Ghuls verrichtest von hohem Wert und großer Bedeutung ist. Es war schön, von meinem Vorfahren zu hören. Ich möcht dich noch was fragen.}
{313}{}{Viele Leute sind eigentlich tief im Inneren Feiglinge. Das ist nichts, wofür man sich schämen sollte. Du bist nur schwach. Tschüß.}
{314}{}{Oft ist der rechte Weg nicht zu erkennen. Jedes Leben hat seinen Sinn. Danke, daß du mir von meinem Vorfahren erzählt hast. Tschüß.}

{320}{}{Ich bin g-glücklicher als ein B-brahminbulle auf einer Weide voller Brahminkühe. I-ich wär sehr stolz, w-wenn ich dich b-begleiten dürfte. Ich b-bin vielleicht alt und k-kann mich nicht m-mehr so schnell bewegen, j-jedenfalls nicht la-lang. Aber ich k-kann dich s-sicher zusam-menflicken, wenn du's n-nötig hast.}
{321}{}{Ich freue mich, daß du mich begleiten kannst. Ich bin sicher, deine Heilkräfte werden sehr nützlich sein.}
{322}{}{Hmm, vielleicht ist das zu beschwerlich für jemanden in deinem Alter. Ich denke, du solltest besser hier bleiben. Tut mir leid. Tschüß.}

{330}{}{Ich habe hier was zu tun. Ich k-kann dich nicht begleiten.}
{331}{}{Du ähnelst d-deinem Vorfahren überhaupt nicht. D-du entwürdigst sein Andenken.}
{332}{}{D-du mußt noch v-viel über das Leben lernen. W-was du b-bisher gelernt hast, g-gefällt mir nicht.}
{333}{}{Schade, daß du mich nicht begleiten kannst.}
{334}{}{Herrgott, man sollte meinen, ein Stück vergammeltes Fleisch wie du würde die Gelegenheit beim Schopf packen, um aus dieser verstrahlten Jauchegrube von Stadt rauszukommen! Tschüß.}

{340}{}{I-ch helfe H-harold, die Stadt zu v-verwalten. D-da ist immer P-papierkram zu erledigen.}
{341}{}{Und was sagtest du, machst du hier sonst noch?}
{342}{}{Fürs erste hab ich genug Informationen. Tschüß.}

{350}{}{Du hattest n-nicht genug G-geld... aber ich h-hab dir t-trotzdem geholfen. Ich e-ertrag es einfach n-nicht, Leute mit Sch-schmerzen zu sehn.}
{351}{}{Ich kann dir gar nicht genug danken, Lenny. Aber ich bräuchte noch ein paar Informationen von dir.}
{352}{}{Danke, Lenny. Ich schuld dir was. Tschüß.}

{360}{}{Hier s-sind so viele L-leute. D-du brauchst m-meine Hilfe n-nicht. V-viel Glück.}

{370}{}{Ich hätt n-nicht gedacht, daß ich den Tag erlebe, an d-dem ich mich für das w-was du
 tust sch-schämen würde. Du bist eine Schande für den Vaultbewohner. Wiedersehn.}
{371}{}{Weißt d-du, ich d-dacht, es würde Spaß m-machen, m-mit dir herumzureisen, aber du b-bist nur ein gewöhnliches und mürrisches B-Brahmin mit 'nem K-kaktus im Hintern. Und du r-riechst auch nicht viel besser. Tschüß.}
{372}{}{Schade, daß du gehst, Lenny.}
{373}{}{Du wirst damit nicht fertig, wie? Du solltest deinen halb verrotteten Kadaver hier schleunigst weg bewegen, bevor ich mir überlege, ob es mir eine Kugel wert ist, dir das Licht auszuknipsen.}
{374}{}{Rülps Jaja, wie auch immer, ich denke, du hast anderes zu tun, zum Beispiel deine Zeit an Erinnerungen zu verschwenden, wie es war, eine Haut zu haben, die nicht so aussieht, wie die eines drei Monate alten Verkehrstoten im Juli. Verschwinde hier, du verdammte Mißgeburt.}
{375}{}{OK.}

{380}{}{W-was soll i-ich m-machen?}
{381}{}{Lenny, ich weiß ja, daß du dir Mühe gibst. Aber geh mir bitte trotzdem aus dem Weg.}
{382}{}{Du mußt anders Kämpfen, Lenny.}
{383}{}{Du mußt hier warten.}
{384}{}{Arzt, heil dich selbst.}
{385}{}{Du mußt mich heilen, Lenny.}
{386}{}{Du mußt einige unserer Freunde heilen, Lenny.}
{387}{}{Du mußt uns heilen.}
{388}{}{Wie geht's dir, altes Haus?}
{389}{}{Im Moment brauch ich deine Hilfe nicht, Lenny.}

{400}{}{Ich soll a-anders kämpfen?}
{401}{}{Ändere deinen Abstand.}
{402}{}{Benutz deine beste Waffe.}
{403}{}{Leg deine beste Rüstung an.}
{404}{}{Du mußt anders kämpfen.}
{405}{}{Mach dir nichts draus.}

{410}{}{W-wie weit s-soll ich denn weg s-sein? Du weißt ja, daß ich n-nicht so sch-schnell a-aufholen kann.}
{411}{}{Du sollst nur ein wenig weiter von mir weg bleiben.}
{412}{}{Bleib auf mittlerem Abstand.}
{413}{}{Bleib auf größerem Abstand.}
{414}{}{Du mußt die Lage auskundschaften.}
{415}{}{Mach dir nichts draus.}

{420}{}{W-was s-soll ich m-machen?}
{421}{}{Du mußt jetzt defensiv kämpfen.}
{422}{}{Du mußt jetzt normal kämpfen.}
{423}{}{Du mußt jetzt aggressiv kämpfen.}
{424}{}{Mach dir nichts draus.}

{430}{}{Du k-kannst sogar einem a-alten Hasen noch n-neue Tricks beibringen. W-was für ein Schlag.}
{431}{}{Irgendwie h-hab ich den r-richtigen Dreh noch nicht raus.}
{432}{}{OK.}

{440}{}{Oh, OK. Ich w-warte hier, bis du z-zurück bist. Dann können sich meine m-müden Glieder etwas ausruhen.}
{441}{}{Tu das Lenny. Tschüß.}
{442}{}{Du solltest hier warten; äh, und noch was...}
{443}{}{Mach dir nichts draus.}

{450}{}{Ich b-brauch eine g-größere Waffe.}
{451}{}{Nimm deine beste Waffe, Lenny.}
{461}{}{Leg deine beste Rüstung an, Lenny.}
{462}{}{Lenny, nachdem du deine beste Rüstung angelegt hast, müßtest du noch was andres für mich tun.}
{463}{}{Mach dir nichts draus.}

{470}{}{Das ist eine gute Idee. Ich h-hab mich schon g-gefragt, wann wir d-dafür anhalten. Mi-mir tut j-jedenfalls a-alles weh.}
{471}{}{L-laß mich deine W-unden mal ansehen.}
{472}{}{Sieht so aus, als m-müßt ich j-jemanden zusammenf-flicken.}
{473}{}{Mach schon, heil dich selbst.}
{474}{}{Heil dich selbst und dann möcht ich dich bitten, noch was anderes zu tun.}
{475}{}{Mach schon, heil mich bitte.}
{476}{}{Heil mich und dann müßtest du noch was für mich tun.}
{477}{}{Mach schon, heil uns.}
{478}{}{Heil uns und dann müßtest du noch etwas für mich tun.}
{479}{}{Mach dir nichts draus.}

{480}{}{D-das kann ich nicht. I-ich bin w-wirklich kein g-guter Späher.}
{481}{}{Oh, OK. Macht nichts.}

{490}{}{Ich bleib dicht bei dir.}
{491}{}{Bleib dicht bei mir, Lenny.}
{492}{}{Bleib dicht bei mir und dann müßtest du noch was anderes tun.}
{493}{}{Mach dir nichts draus.}

{500}{}{W-wir wollen ihnen k-keine zu einfache Z-zielscheibe bieten, was?}
{501}{}{Nicht zu dicht ran, Lenny. Sie sollen's nicht so leicht haben, uns zu treffen.}
{502}{}{Komm nicht zu dicht ran. Du mußt noch was anderes für mich tun.}
{503}{}{Mach dir nichts draus.}

{510}{}{OK, ich b-bleib etwas zurück. Scheint, als w-wollten die meisten L-leute dich töten.}
{511}{}{Bitte bleib zurück, zu deiner eigenen Sicherheit. Es hat nichts damit zu tun, wie du riechst.}
{512}{}{Bevor wir uns verteilen, mußt du noch was für mich tun.}
{513}{}{Mach dir nichts draus.}

{520}{}{Mit den Jahren h-hab ich g-ganz gut gelernt, auf m-mich selbst aufzupassen.}
{521}{}{Ich möcht nur, daß du vorsichtig bist, wenn wir in Kämpfe geraten.}
{522}{}{Ich möcht nur, daß dir nichts passiert. Du bist schließlich eine Antiquität. Eins noch...}
{523}{}{Mach dir nichts draus.}

{530}{}{Die einzige M-möglichkeit.}
{531}{}{Kämpfe so, wie du es gewohnt bist, dann schaffen wir es schon.}
{532}{}{Sei einfach locker und kämpfe wie immer. Eins noch...}
{533}{}{Mach dir nichts draus.}

{540}{}{Ich k-kann nicht. Daß diese alten Knochen ü-überhaupt noch k-kämpfen, ist schon ein W-wunder.}
{541}{}{OK. Macht nichts.}

{1000}{}{W-was soll i-ich m-machen?}

{1100}{}{Mir g-geht es gut.}
{1200}{}{Ich bin l-leicht verletzt, aber ich k-kann weiter machen.}
{1300}{}{Das ist eine gute Idee. Ich h-hab mich schon g-gefragt, wann wir d-dafür anhalten. Mi-mir tut j-jedenfalls a-alles weh.}
{1400}{}{Ich b-brauche Heilung, oder ich st-terbe.}

{1500}{}{Oh, OK. Ich w-warte hier, bis du z-zurück bist. Dann können sich meine m-müden Glieder etwas ausruhen.}

{1600}{}{OK.}

{1700}{}{Ich bleib dicht bei dir.}
{1800}{}{W-wir wollen ihnen k-keine zu einfache Z-zielscheibe bieten, was?}
{1900}{}{OK, ich b-bleib etwas zurück. Scheint, als w-wollten die meisten L-leute dich töten.}

{2000}{}{Hier sind so v-viele Leute. Du brauchst m-meine Hilfe nicht mehr. Ich wünsche dir v-viel Glück.}
{2100}{}{Ich hätt n-nicht gedacht, daß ich den Tag erlebe, an d-dem ich mich für das w-was du
 tust sch-schämen würde. Du bist eine Schande für den Vaultbewohner. Wiedersehn.}
{2200}{}{Ich w-wußte nicht, ob du z-zurückkommst.}

{2300}{}{Nur nicht drängeln.}
{2301}{}{Oh, tut mir leid. Ich mach ja schon Platz.}
{2302}{}{Drängel, drängel, drängel. OK, kein Problem, ich mach Platz. Tut mir leid, wußte nicht, daß ich dir den Weg versperre.}
{2303}{}{Tut mir leid, aber ich kann einfach nicht schneller gehen. Dann mach ich eben Platz.}
{2304}{}{Oh, okay, ich torkele ja schon aus dem Weg.}
{2305}{}{Dann torkele ich eben einfach nach hier.}
{2306}{}{Hatte nicht vor, zum Hindernis zu werden.}
{2307}{}{Oh, tut mir leid.}

{3000}{}{In deiner Nähe passiert einfach zuviel Unschönes. Ich hau ab, bevor mir auch so was passiert.}
{3001}{}{Ich werde keinem Kindermörder helfen. Tschüß.}
{3002}{}{Deine Blutgier macht mir Angst. Werd dir nicht länger folgen.}
{3003}{}{Will nichts mit 'nem Sklavenhändler zu tun haben. Mach's gut.}
{3004}{}{Du Verräter! Du hast unser Kraftwerk zerstört. Ich werde dir nicht helfen.}
{3005}{}{Ich m-möchte nichts mit dir zu t-tun haben.}

{4000}{}{Okay, aber du kannst mich hier doch nicht ganz allein lassen.}
{4001}{}{Sicher, wenn du das wirklich für eine so gute Idee hältst.}
{4002}{}{Na ja, ich wende nicht gerne Waffen an, außer, wen es wirklich sein muß, aber ich glaube, ich könnte mit einem Messer umgehen, denke ich. Ich kann mit einer Pistole umgehen, jedenfalls konnte ich das früher. Wenn es wirklich sein müßte, könnte ich schon mit einer MP umgehen, glaube ich. Wenn die nur nicht so viel Krach machen würden. Ich bin ein Heiler, kein Kämpfer.}
{4003}{}{Mann, ich hoffe, ich brauch das nie.}

#added by killap - NPC info
{5000}{}{Ich g-glaub ich hab m-mir da was geb-brochen.}
{5001}{}{Ich g-glaub ich bin v-verstrahlt.}
{5002}{}{Ich g-glaub ich w-wurde verg-giftet.}
