{100}{}{Du siehst einen verwelkten, alten Ghul.}
{101}{}{Du siehst einen von mehreren alten Ghuls, die sich in diesem Haus niederlassen.}
{102}{}{Ich bin so müde.}
{103}{}{So müde, müde zu warten, müde auf Dich zu wa-har-ten.}
{104}{}{Wann ist Schlafenszeit?}
{105}{}{Was ist das für ein fürchterlicher Gestank? Oh, das bin ich.}
{106}{}{Ist es schon 4 Uhr? Ich will mein Abendessen!}
{107}{}{Wow, Ich hab mir schon seit fast einer Stunde keine Hüfte gebrochen!}
{108}{}{Hat irgend jemand meine Zähne gesehen?}
{109}{}{Wo ist mein Fuß?}
{110}{}{Tod! Ich bin der, den Du haben willst! Komm hier her!}
{111}{}{Hallo, Billy! Ich bin so froh, dass Du zurückgekommen bist, um mich zu besuchen.}
{112}{}{Alt werden ist kein Picknick.}
{113}{}{Huch! Meine Gedärme!}
{114}{}{Hat irgend jemand eine Windel?}
{115}{}{Ich könnte eine Menge Weisheit weitergeben, aber ich hab keine Lust dazu.}
{116}{}{Die Ghuls von heutzutage... bäh!}
{117}{}{Keinen Respekt... keiner hat mehr Respekt heutzutage.}
{118}{}{Ich erinnere mich, wie der alte Set...}
{119}{}{Frag mich, wie's dem alten Jed in Gecko ergeht.}
{120}{}{Magst Du Mutanten? Ich schon.}
{121}{}{Ich mag Kartoffeln! Ich mag sie gestampft! Ich mag sie fritiert!}
{122}{}{Ich hab Hunger!}
{123}{}{Ich wünschte, wir hätten hier ein paar Pflanzen.}
{124}{}{Ich mag es nicht draußen zu sein.}
{125}{}{Die alte Uranium Mine wird bald dicht machen.}
{126}{}{Du bist nicht aus Vault City, nicht wahr?}
{127}{}{Ich erinner mich noch, wie wir gegen die Glowin' Ones gekämpft haben unter Necropolis...
 das waren noch Zeiten...}
{128}{}{Lasst mich mal davon erzählen, wie wir die Vault geöffnet haben...}
{129}{}{...was wollte ich sagen?}
{130}{}{::gähn::}
{131}{}{::pffffft::}
{132}{}{Ich hab niemanden irgend etwas zu sagen!}
{133}{}{Ich brauche ein Nickerchen.}
{134}{}{Es ist kalt und die Wölfe sind hinter mir her.}
{135}{}{Wenn Hunde sterben, wedeln sie noch stundenlang mit ihrem Schwanz!}
