{100}{}{Du siehst einen lächelnden Mann in einer schwarzen Lederrüstung.}
{101}{}{Du siehst Steve, den Begrüßer von Broken Hills.}
{102}{}{Du siehst einen freundlichen Mann in einer schwarzen Lederrüstung. Er sieht aus, als ob er den ganzen Tag hier stünde und auf jemanden warten würde, mit dem er reden kann.}

{103}{}{Hallo! Ich heiße Steve. Ich kann dir alles Wissenswerte über diese schöne Stadt hier sagen. Kann ich dir vielleicht einen Weg erklären oder dir sonstwie helfen?}
{104}{}{Dah...}
{105}{}{Rogen-Filz?}
{106}{}{Erzähl mir was über die Stadt.}
{107}{}{Wer wohnt hier alles?}
{108}{}{Wer ist hier verantwortlich?}
{109}{}{Was gibt's Neues?}
{110}{}{Was für Dienstleistungen bietet die Stadt?}
{111}{}{Nöö, tut mir leid.}

{112}{}{Ach je. Noch so ein armer Sproß aus der Öde. Komm ruhig näher. Du wirst sehen, daß wir hier genauso gastfreundlich sind wie die anderen Städte im Ödland.}
{113}{}{Stiiieew!}

{114}{}{Das stimmt. Viel Glück, Wanderer. Und auf Wiedersehen.}
{115}{}{Liederfeen!}

{116}{}{Broken Hills. Das ist hier eine Bergarbeiterstadt. Wir graben Sachen aus und dann verkaufen wir sie.}
{117}{}{Braben?}
{118}{}{Ferklauf!}

{119}{}{Genau. Aus der Erde. Wir haben eine Mine. Ich glaube aber nicht, daß sie da Arbeit für dich haben. Wenn du Arbeit suchst, kannst du mit dem Ausrüster reden.}
{120}{}{Oh-kay.}
{121}{}{Sachen verkaufen?}

{122}{}{Wir verkaufen unsere Ausgrabungen an die anderen Städte im Umkreis. Sie können damit etwas anfangen. Wenn du etwas verkaufen möchtest, kannst du dich an die ganzen Kaufleute der Stadt wenden. Jetzt muß ich aber wieder an die Arbeit. Sei vorsichtig und benimm dich, ja?}
{123}{}{Oh-kay! Tschüüüüß!}

{124}{}{Jetzt muß ich aber wieder an die Arbeit. Sei vorsichtig und benimm dich, ja?}
{125}{}{Schon wieder du? Na, du weißt ja, was du zu tun hast - schön vorsichtig sein. Also dann!}
{126}{}{Oh-kay! Tschüüüüß!}

{127}{}{Steck deine Waffen weg. So lange du mir die ins Gesicht hältst, kriegst du von mir gar keine Antworten.}

{128}{}{Wir wohnen hier in einer kleinen Bergarbeiterstadt. Vor ein paar Jahrzehnten wurde die Stadt von unserem Sheriff Marcus und einem Mann namens Jacob gegründet. Die beiden haben den Ort ausgewählt, weil es hier Uranvorkommen gibt. Möchtest du sonst noch etwas wissen?}
{129}{}{Ja.}
{130}{}{Nein.}

{131}{}{Wir sind eine Gemeinschaft aus Menschen, Mutanten und Ghuls. Hier gibt es keine Rassenprobleme wie in Vault City. In unseren Augen sind alle gleich.}
{132}{}{Du lebst mit Mutanten zusammen? Weißt du denn nicht, wie grausam sie sind?}
{133}{}{Gleich?}
{134}{}{Danke. Tschüß.}

{135}{}{Offiziell hat Sheriff Marcus hier das Sagen. Er hat die Stadt mitgegründet und hilft uns in Krisensituationen. Aber eigentlich hat jeder in der Stadt eine eigene Stimme.}
{136}{}{Das klingt aber unrealistisch.}
{137}{}{Das hört sich nach einer guten Methode an, eine Stadt zu verwalten.}
{138}{}{Weiter.}
{139}{}{Der Mitbegründer der Stadt ist immer noch Sheriff? Dann muß er aber ganz schön alt sein.}
{140}{}{Danke. Tschüß.}

{141}{}{Abgesehen davon, daß die Mutanten alle TOT sind und diese Stadt VERLOREN ist...}
{142}{}{Abgesehen davon, daß die Mutanten tot sind und unsere einzige Einkommensquelle zerstört ist...}
{143}{}{Abgesehen davon, daß du ein Held bist, weil du uns die Korruption in unserer Mitte vor Augen geführt hast...}
{144}{}{Abgesehen davon, daß wir seit der Flucht von Franc und Manson gemerkt haben, daß sich ein Krebsgeschwür unter uns befindet ...}
{145}{}{Abgesehen von Chads Betrug an der Stadt und deiner Gerechtigkeit - für die wir alle sehr dankbar sind -- }
{146}{}{Eigentlich nicht viel.}
{147}{}{Ich habe noch mehr Fragen.}
{148}{}{Tschüß.}

{149}{}{Ach, du schon wieder.}
{150}{}{Hallo.}
{151}{}{Willkommen zu Hause.}
{152}{}{Du willst noch mehr wissen?}
{153}{}{Was gibt's Neues?}
{154}{}{Wer ist hier verantwortlich?}
{155}{}{Erzähl mir was über die Stadt.}
{156}{}{Wer wohnt hier alles?}
{157}{}{Was für Dienstleistungen bietet die Stadt?}
{158}{}{Nein danke.}

{159}{}{Wir leben von der Veredelung des Erzes, das wir in den Bergen abbauen und an die umliegenden Städte wie Vault City, Gecko und die New California Republic verkaufen. Ein wenig verwenden wir auch für die Stromversorgung der Stadt. Weiter?}
{160}{}{Ja.}
{161}{}{Nein.}

{162}{}{Alle sind gleich. Wir sind alle aus Menschen entstanden, im Inneren sind wir alle gleich. Es wäre dumm zu behaupten, daß jemand nur wegen seines Aussehens grausam ist.}
{163}{}{Du bezeichnest mich als Ignoranten?}
{164}{}{Ganz richtig.}
{165}{}{Nicht unbedingt. Wer weiß denn schon, was das Virus, durch das er zum Mutanten wurde, in seinem Gehirn angerichtet hat?}
{166}{}{Egal. Tschüß.}

{167}{}{Für unsere Zwecke läuft aber alles bestens. Außerdem ist Marcus sehr fair.}
{168}{}{Wo kann ich Marcus denn finden?}
{169}{}{Tschüß.}

{170}{}{Er ist auch alt, aber immer noch sehr rüstig. Er ist ja auch ein Mutant und die leben anscheinend länger als die Menschen.}
{171}{}{Ihr laßt die Stadt von einem MUTANTEN verwalten? Ja seid ihr denn verrückt?}
{172}{}{Tatsächlich? Ich hätte gedacht, daß die meisten inzwischen gestorben sind.}
{173}{}{Ein Mutant als Sheriff also. Ich wette, daß die meisten Bürger hier ganz schön gesetzestreu sind. Das läuft sicher ganz gut.}
{174}{}{Tschüß.}

{175}{}{Tja, und jetzt halten wir uns hier über Wasser, gestalten unsere eigene Version von Zivilisation und versuchen alles, damit wir uns nicht Vault City oder der NCR unterwerfen müssen. Deren Regierungstil gefällt uns nämlich nicht. Das ist alles.}
{176}{}{Klasse. Ich habe noch mehr Fragen.}
{177}{}{Danke. Tschüß.}

{178}{}{Wenn du weiterhin glauben willst, daß du den Charakter einer Person an ihrem Äußeren festmachen kannst, dann bist du tatsächlich ein Ignorant.}
{179}{}{Laß mich doch in Ruhe, Mann. DU bist hier der Ignorant.}
{180}{}{Na gut. Vielleicht hast du recht.}

{181}{}{Egal, das war sowieso schon alles, was ich sagen wollte. Willkommen in Broken Hills.}
{182}{}{Warte mal.}
{183}{}{Tschüß.}

{184}{}{Wenn die Mutanten uns ans Leder wollten, dann hätten sie uns schon längst angegriffen. Die leben ja auch nicht ewig, die meisten von ihnen werden sogar allmählich senil. Die erreichen ihre Ziele auch nicht leichter, wenn sie eine Gemeinschaft aufbauen.}
{185}{}{Da kannst du recht haben.}
{186}{}{Aber grausam sind sie trotzdem.}
{187}{}{Tschüß.}

{188}{}{Meine Güte, je länger ich mit dir rede, desto blöder komme ich mir vor. Mit deiner Einstellung wirst du es in Broken Hills nicht leicht haben. Und jetzt mußt du mich entschuldigen, ich habe nämlich zu arbeiten.}
{189}{}{Idiot.}
{190}{}{Zeit zu sterben, Vollidiot.}

{191}{}{Wir haben hier eine Mine, eine Raffinerie, eine Taverne, ein Hotel - da gibt es übrigens im Moment keinen Besitzer, deswegen lassen wir die Leute umsonst da wohnen - ein Krankenhaus, einen Gemischtwarenladen und einen Alchemistenladen. Wir bauen unser Gemüse selbst an.}
{192}{}{OK. Ich hab noch ein paar Fragen.}
{193}{}{Tschüß.}

{194}{}{Tja, das trifft schon auf einige zu. Mutanten sind ja unfruchtbar... habe ich jedenfalls gehört, deswegen sterben sie aus. Die übrigen hier scheinen außerdem allmählich senil zu werden. Außer Marcus natürlich, der ist noch genauso fit wie sonst.}
{195}{}{Wo finde ich Marcus denn?}
{196}{}{Ich habe noch mehr Fragen.}
{197}{}{Tschüß.}

{198}{}{Marcus, bist du dir wirklich sicher, daß du nicht noch ein bißchen länger unser Anführer sein willst?}
{199}{}{Marcus: Da seh ich keine Zukunft drin. Wird schon ohne mich gehen.}
{200}{}{[Weiter]}

{201}{}{Hör mal Freundchen, wir brauchen dich hier nicht. Du hast schon genug Schaden angerichtet.}
{202}{}{[Fertig]}

{300}{}{Normalerweise ist Marcus bei der Bank zu finden, die dient gleichzeitig auch als Sicherheitsgefängnis, oder im Gefängnis selbst. Manchmal ist er auch in der Taverne oder zu Hause, aber meistens arbeitet er.}

{301}{}{Was'n Hammer!}
{302}{}{Verdammt!}
{303}{}{Hurra!}
{304}{}{Nichtsnutze!}
{305}{}{Verdammter Bastard!}
