#############################################################
#  Message File: mcChild.msg                                 #
#                                                           #
#       Body Type: CHILD                                    #
#       Combat AI: Flee                                     #
#       Weapons: None                                       #
#       HP: 20                                              #
#       Skills to note: None                                #
#                                                           #
#  Log:                                                     #
#                                                           #
#  Created: January 13, 1998                                #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for describing the NPC when      #
#  glanced and and examined.                                #
#############################################################
{100}{}{Ein kleiner Junge.}
{101}{}{Ein kleines Mädchen.}

{120}{}{Ein kleiner Junge. Er sieht verspielt aus.}
{121}{}{Ein kleines Mädchen. Es sieht verspielt aus.}
#############################################################
#  The following lines are floaters for children            #
#############################################################
{150}{}{Friß mich nicht!}
{151}{}{Iiihh! Der schwarze Mann!}
{152}{}{Papa sagt, daß du böse bist.}
{153}{}{Iiiihh! Schnell weg!}
{154}{}{Du machst mir Angst.}
{155}{}{Schau mich nicht so an.}
{156}{}{Ich soll nicht mit Wilden reden.}
{157}{}{Blödmann.}
{158}{}{Meine Mama sagt, du frißt mich, wenn ich böse bin.}
{159}{}{Ich hab keine Angst vor dir!}
{160}{}{Hiiilfe!}
{161}{}{Es verfolgt mich!}
{162}{}{Tu mir bitte nicht weh!}
{163}{}{Faß mich nicht an!}
{164}{}{Iiiiiiiihhhh!}
{165}{}{Ich hasse dich!}
{166}{}{Mami, Mami, Mami!}
{167}{}{Laß mich in Ruh!}
{168}{}{Du stinkst!}

{170}{}{Hallo.}
{171}{}{Magst du mit mir spielen?}
{172}{}{Steckst du dir wirklich einen Knochen durch die Nase?}
{173}{}{Warum siehst du so komisch aus?}
{174}{}{Meine Mama sagt, du bist primitiv.}
{175}{}{Frißt dein Stamm keine Menschen mehr?}
{176}{}{Wer hat dich so komisch angezogen?}
{177}{}{Du bist bestimmt netter als du aussiehst.}
{178}{}{Spielen wir Fangen. Du bist dran.}
{179}{}{So schlecht riechst du gar nicht.}
{180}{}{Hast du meinen unsichtbaren Freund gesehen?}
{181}{}{Ich möchte in der Welt herumreisen, wenn ich so alt bin wie du.}
{182}{}{Du bist ein netter Wilder, nicht so wie die anderen.}
{183}{}{Beim Baden aber bestimmt.}
{184}{}{Du bist klüger als Torr.}
{185}{}{Ist die Klinge da richtig scharf?}
{186}{}{Wenn ich erwachsen bin, möchte ich sein wie du.}
{187}{}{Mein Hund liebt Dörrfleisch.}
{188}{}{Ich hab 'nen Glitzerstein.}
{189}{}{Hast du meinen unsichtbaren Freund gesehen?}

{190}{}{Darf ich zu deinem Stamm gehören?}
{191}{}{Du bist nett.}
{192}{}{Du siehst komisch aus.}
{193}{}{Was hast'n da an?}
{194}{}{Ich möchte auf 'nem Brahmin reiten!}
{195}{}{Bist du von weit weg?}
{196}{}{Uuuiii! Ha Ha Ha}
{197}{}{Geh nicht weg!}
{198}{}{Hast du was zum Essen?}
{199}{}{Stör ich dich?}
{200}{}{Wo gehst du hin?}
{201}{}{Kann ich mitkommen?}
{202}{}{Wie alt bist du?}
{203}{}{Wie heißt du?}
{204}{}{Magst du Kinder?}
{205}{}{Was ist das?}
{206}{}{Magst du mit mir spielen?}
{207}{}{Was machst'n du?}
{208}{}{Hast du Käfer gesehen?}
{209}{}{Wo hast du das her?}
{210}{}{Darf ich das haben?}
{211}{}{Was machst'n du so?}
{212}{}{Ich kann ganz schnell rennen. Willste mal sehen?}
{213}{}{Schau! Schau her!}
{214}{}{Mami sagt, ich red zu viel.}
{215}{}{Wo wohnst du?}
{216}{}{Hiiii! Hiiii!}
{217}{}{Bleibst du hier?}
{218}{}{Hast du Kinder?}
{219}{}{Warum bist du hergekommen?}
{220}{}{Ich mag dich.}
{221}{}{Magst du mich?}
{222}{}{Bist du verheiratet?}
{223}{}{Eins, zwei, drei, uuiiih!}

{300}{}{Fremder!}
