{100}{}{Ein sehr reger alter Mann.}
{101}{}{Grisham.}
{102}{}{Du kannst ihn nicht zuordnen, doch er kommt dir bekannt vor.}
{151}{}{Ich hab doch gesagt, du kommst auch noch dran!}
{152}{}{Buahahaha!}
{153}{}{Hau ab!}
{154}{}{Ich hab zu tun!}
{155}{}{Ich hab doch gewusst, dass meine Tochter etwas seltsam ist.}
{156}{}{Ich finde über Geschmack kann man sich streiten.}
{157}{}{Ich glaub, mir wird übel.}
{158}{}{Ich hab doch gewusst, dass mein Sohn etwas seltsam ist.}
{159}{}{Kümmer dich gut um meine Tochter.}
{160}{}{Ich schätze du gehörst jetzt zur Familie.}
{161}{}{Kümmer dich gut um meinen Sohn.}
{162}{}{Ich heiße Grisham. Willkommen in meinem Schlachthaus. Willst du was abliefern oder mitnehmen?}
{163}{}{Mitnehmen wohl eher. Ich möchte Reiseproviant kaufen.}
{164}{}{Du hast hier nicht zufällig eine goldene Uhr rumliegen sehen?}
{165}{}{Was kann ich jetzt für dich tun?}
{166}{}{Ich möchte etwas von deinem berühmten Schnetzelfleisch kaufen.}
{168}{}{Kannst du mir etwas über das Schlachthaus erzählen?}
{169}{}{Die Dürre hat dein Geschäft anscheinend noch nicht beeinträchtigt.}
{170}{}{Ich hab gewusst, dass du das schaffst. Mal sehen, ich schulde dir $1000 für den Job. Allerdings sind, }
{171}{}{ Brahmin wegen deiner Nachlässigkeit umgekommen. Bei $100 pro Brahmin beträgt deine Belohnung }
{172}{}{. Versuch nicht zu lügen, wie viele Brahmin umgekommen sind, einer meiner Jungs ist dir gefolgt und hat dich beobachtet.}
{173}{}{Du hast kein Wort davon gesagt, dass ich für tote Brahmin zahlen muss!}
{174}{}{Du hinterhältiger, vertrockneter alter Sack. Aahh! Merk's dir: Das ist das letzte Mal, dass du mich reinlegst!}
{175}{}{Danke, Opa, es war mir ein Vergnügen.}
{176}{}{Wie kannst du es wagen, hier noch mal aufzutauchen! Wegen deiner Feigheit habe ich zehn Brahmin verloren. Wenn du das aber gutmachen willst - $1500 würden einen Großteil meiner Verluste abdecken.}
{177}{}{Die Brahmin waren nicht mehr als $1000 wert.}
{178}{}{So viel Geld hab ich nicht und wenn, würd ich's nie einem Beutelschneider wie dir geben.}
{179}{}{Ich hab mein Geld im Zimmer gelassen, ich hol's schnell.}
{180}{}{Ah! Natürlich, natürlich. Mal sehen, für unterwegs empfehle ich unsere weltberühmten gedörrten Brahminstreifen. Sehr haltbar und schmecken lecker. Nur $10 pro Packung. Interessiert?}
{181}{}{Klingt gut. Gib mir eine Packung.}
{182}{}{Nein, danke. Später vielleicht. Aber ich möchte dir ein paar Fragen stellen.}
{183}{}{Es war mir ein Vergnügen. Kann ich noch etwas für dich tun?}
{185}{}{Warte! Du scheinst ein fähiger Reisender zu sein. Du willst nicht zufällig ein bisschen Geld verdienen?}
{186}{}{Bist du sicher, dass du dir kein Geld verdienen willst? Ich bin sicher, dass du mein Problem ganz einfach lösen könntest.}
{187}{}{Kommt darauf an, wieviel, was ich tun muss und vor allem WIEVIEL?}
{188}{}{Schlau wie ein Fuchs! Genau wie ich, als ich noch jung war. Also, das ist so: in letzter Zeit kommen ständig ein paar Wildhunde auf der Suche nach Nahrung von den Hügeln runter. Die Brahmin sind leichte Beute für sie und so greifen sie nachts meine Herden an. Erledige das Rudel und du kriegst $1000.}
{189}{}{Du verheimlichst was, du alter Sack. Wo ist der Haken?}
{190}{}{Nicht nur schlau, sondern auch aufmerksam. Dacht ich mir doch, dass man dich nicht reinlegen kann. Der Haken ist, dass ich dir für jedes Brahmin, das umkommt, $100 in Rechnung stelle. Ich zahl gut für gute Arbeit, aber ich verlang auch was, wenn Du Murks machst. Das ist das Risiko, wenn du für mich arbeitest.}
{191}{}{Super! Geh nachts zu den Weiden und erledige das Rudel wilder Hunde, die meine Brahmin angreifen. Komm wieder, wenn du den Job erledigt hast.}
{192}{}{Ach du Dickesscheißliebesbisschen! Sucht Cornelius immer noch nach der Uhr? Warum findet er sich nicht damit ab, dass sie weg ist? Die blöde Uhr hat sowieso nie funktioniert und ich möcht ein Brahmin sein, wenn die aus Gold war. Gib's auf, die findest du nie.}
{193}{}{Farrel hat mich gebeten, sie zu suchen.}
{194}{}{Kann ich dir noch ein paar Fragen stellen?}
{195}{}{Danke trotzdem, aber ich such weiter.}
{196}{}{Hab ich nicht? Bist du sicher? Ich hätte drauf schwören können. Vielleicht nimmst du das nächste Mal erst dann 'nen Job an, wenn du genau Bescheid weißt. Und jetzt, wenn du so gut wärst, ich hab zu tun.}
{197}{}{Hähähä. Kommt ganz drauf an. Willst du noch länger hier im Ort bleiben? Buahahahaha!}
{198}{}{Ich seh schon, du bist nicht auf den Kopf gefallen. OK, $1000 und wir sind quitt. Schlag ein.}
{199}{}{[SCHÜTTEL GRISHAMS HAND]}
{200}{}{Moment mal. Wenn ich so drüber nachdenke, die Brahmin sahen recht dünn aus. Wie wär's mit $750?}
{201}{}{Ich hab's mir überlegt, ich will dich nicht bezahlen.}
{202}{}{[Zeigt dir ein großes breites Grinsen] Schön zu sehen, dass du eine Person mit Charakter bist.}
{203}{}{[Grisham bekommt einen hochroten Kopf und spricht durch zusammengebissene Zähne.] OK, $750. Gib mir das Geld!}
{204}{}{Also weißt du, $750 ist immer noch ziemlich teuer. Die Brahmin wären auch gestorben, wenn die Hunde sie nicht erwischt hätten. Aber ich bin kein Egoist, ich geb dir $50.}
{206}{}{GUT! GIB MIR DAS GELD UND HAU AB!}
{207}{}{[GEH OHNE ZU ZAHLEN]}
{208}{}{Merk's dir: Du kommst auch noch dran. Wenn nicht durch mich, dann durch jemand anders.}
{209}{}{[Grisham grinst dich so an, dass du unwillkürlich einen Schritt zurücktrittst.] Warum behältst du dein Geld nicht einfach. Ich habe so das Gefühl, du wirst es später noch brauchen.}
{210}{}{Da gibt's nicht viel zu erzählen. Ich leite das Schlachthaus in Modoc. Willst du was geschlachtet haben, bring's mir, ich erledig's und mach das beste Schnetzelfleisch daraus, das du je kriegen wirst.}
{211}{}{Wie steht's mit den Häuten und den anderen Tierteilen?}
{213}{}{Sie war sogar ganz gut für mein Geschäft. Niemand schafft es, genügend Nahrung für die Brahmin anzubauen, also lassen die ihre Herden in großem Ausmaß schlachten. Aber das geht vorbei, man muss das im Zusammenhang sehen. Wenn die Brahmin weniger werden, kann mein Geschäft nur drunter leiden.}
{215}{}{[Grisham geht um dich herum, piekst dich ein paar Mal, öffnet deinen Mund und prüft deine Zähne.] Ah! Ein gutes, gesundes Exemplar. Du bist geeignet. Ähem ... Böse Hundis töten gute Brahmin. Geh töten böse Hundis für Freund Grisham. Grisham dir geben gute Belohnung. OK?}
{216}{}{Nein, ich mögen Hundis. Nur böse Männer Hundis nicht mögen. Ich gehen weg von böser Mann.}
{217}{}{Ich mach's. Geh sofort!}
{218}{}{Gut! Denk dran: Böse Viecher machen "Wuff! Wuff!", gute Viecher machen "Muuh". Du nicht töten gute Viecher.}
{219}{}{Du scheinst knapp bei Kasse zu sein. Ich gebe keinen Kredit und ich glaube ganz sicher nicht daran, etwas für nichts herzugeben.}
{221}{}{Das hat man davon, wenn man einen Neandertaler schickt. Verschwinde!}
{222}{}{Äh... snarf ick unga bunga. Jetzt nimm dein Geld, sei ein guter Neandertaler und verschwinde.}
{223}{}{Du bist clever. Wenn du schon fragst, du kannst jedes Teil vom Tier behalten, das du willst. Balthas kauft normalerweise die Häute und Rose kauft die Reste, die du nicht willst. Sie macht daraus Suppe und Futter für ihre Hunde.}
{225}{}{Du machst wohl Witze. Jeder weiß, dass Farrel die Uhr hat. Warum sollte er dich bitten, danach zu suchen ... außer, Farrel hat die Uhr gar nicht geklaut! Oder vielleicht ist es ein Trick, um alle zu überzeugen, dass er's nicht war. Darüber muss ich nachdenken.}
{228}{}{Junge, versuch gar nicht erst, mir das zu erklären, ich will's nicht hören. Ich hol den Priester, mach das irgendwie rechtmäßig und du haust ab und nimmst meinen Sohn mit, wenn du gehst.}
{229}{}{Ich könnte nicht sagen, dass mich das nicht ein bisschen anmacht, aber ich kann sie nicht bei mir im Haus haben, jetzt, da ich das gesehen habe. Ihr beide müsst heiraten und dann abhauen.}
{230}{}{Kannst du mir erklären, was du da mit meiner Tochter machst?}
{231}{}{Kannst du mir erklären, was du da mit meinem Sohn machst?}
{232}{}{Ich werd's dir langsam erklären, Opa. Also, es gibt Bienlein und Vöglein... }
{233}{}{Ich bin Arzt und wollte sie nur mal gründlich durchchecken.}
{234}{}{Ich bin Ärztin und wollte ihn nur mal gründlich durchchecken.}
{235}{}{Es ist nicht so, wie es aussieht.}
{236}{}{Na klasse. Jetzt krieg ich 'nen Klugscheißer als Schwiegersohn. Komm schon... Sohn. Bringen wir's hinter uns.}
{237}{}{Na klasse. Jetzt krieg ich 'ne Klugscheißerin als Schwiegertochter. Komm schon... Tochter. Bringen wir's hinter uns.}
{238}{}{Mal sehen. Es sah so aus, als ob du und meine Tochter die Brahmin während der Paarungszeit nachmachen würdet.}
{239}{}{Mal sehen. Es sah so aus, als ob du und mein Sohn 'nen Horizontaltango unterm Bettuch tanzen würdet.}
{240}{}{OK, vielleicht ist es doch so, wie es aussieht. Es geht aber nur um Sex, nicht um Liebe oder sowas.}
{241}{}{Ich verstehe. Hormone und so und außerdem ist ja gerade diese Jahreszeit.}
{242}{}{Ich bin froh, dass du das verstehst.}
{243}{}{Ich verstehe. Und ihr versteht hoffentlich, dass ihr beide unter die Haube müsst. Ich kann mir kein Gerede in der Stadt leisten. Kommt mit, wir gehen zum Priester. Ich hab keine Lust, euch mit Schrot vollzupumpen.}
{244}{}{Ach wirklich? Warum wart ihr dann beide nackt?}
{245}{}{Bakterien? Ich meine BAKTERIEN! Sehr wichtig, bei diesen Untersuchungen sauber zu sein.}
{246}{}{Na ja, wenn du 'n Arzt bist, ist es wohl OK. Zieht euch schnell an, mit solchen Missverständnissen fängt Gerede immer an. Wenn du schon da bist, ich hab in letzter Zeit so Schmerzen im Hintern, vielleicht kannst du dir das mal ansehen.}
{247}{}{Ähh ... das schau ich mir später mal an. Ein anderer Patient wartet noch auf mich. Tschüss.}
{248}{}{Ja. Warum kommst du nicht mit, den Priester holen. Versuch keine krummen Dinger, sonst brauchst du 'nen Doktor.}
{260}{}{Ich hab gewusst, dass du das schaffst. Mal sehen, ich schulde dir $1000 für den Job. Da hast du's.}
{300}{}{Was zum Teufel ist hier los?}
{301}{}{Ähhh... Sir, ich wollte nur...}
{302}{}{Lass bloß deine Pfoten von ihr...}
{350}{}{[Mit Blick auf Bessy.] Abliefern.}
{360}{}{Ich hätte gern, dass du etwas Schnetzelfleisch für mich machst.}
{400}{}{Was ist hier los?}
{402}{}{Ach du Scheiße! Ich hab gewusst, dass }
{403}{}{Wie kannst du die Ehre von }
{404}{}{Äh, Jo, können wir das Blabla am Anfang nicht einfach überspringen?}
{406}{}{Junge...}
{407}{}{Mädel...}
{410}{}{Zwing mich nicht }
{412}{}{Miria}
{413}{}{Davin}
{414}{}{Oh, Bo, können wir den Teil mit dem Ehegelöbnis nicht einfach überspingen?}
{420}{}{Du gehst niergendwo hin Junge!}
{421}{}{Du gehst niergendwo hin Mädel!}
{452}{}{ anders ist, aber das ist nur auf eine Art zu richten!}
{453}{}{. besudeln! Das ist nur auf eine Art zu richten!}
{460}{}{ zur Witwe machen.}
{461}{}{ zum Witwer machen.}
{500}{}{Da hast du aber ein schönes Tier. Gibt gutes Schnetzelfleisch. Pass auf, ich behalt was vom Schnetzelfleisch als Zahlung. Was meinst du?}
{501}{}{Niemals! Ich liebe Bess. Aus der macht niemand Schnetzelfleisch.}
{502}{}{Klingt gut. Wann kann ich mir das Schnetzelfleisch abholen?}
{503}{}{Vergiss es, Opa. Ich verschwinde.}
{510}{}{Ach ... so einer bist du. Ich möcht dir deine "Freundin" nicht wegnehmen. Die Nächte in der Wüste wären wahrscheinlich ganz schön einsam ohne sie. Für sowas hab ich keine Zeit, ich hab zu tun.}
{515}{}{Super! Komm in einer Woche wieder. Du kannst dir das Schnetzelfleisch in der Räucherkammer gleich neben dem Schlachthaus abholen. Ich lass es dort in einem Sack. War mir ein Vergnügen.}
{600}{}{Hallo }
{601}{}{Na, ist das nicht }
{602}{}{Ähhhm, er ist tot.}
{603}{}{Ähhhm, sie ist tot.}
{604}{}{Miria lebte zwar noch, als ich sie verließ, aber jetzt ist sie bestimmt tot.}
{605}{}{Davin lebte zwar noch, als ich ihn verließ, aber jetzt ist er bestimmt tot.}
{606}{}{Davin, äh, konnte nicht mitkommen, aber ich werd ihm deine Grüße ausrichten, wenn ich ihn wiedersehe.}
{607}{}{Miria, äh, konnte nicht mitkommen, aber ich werd ihr deine Grüße ausrichten, wenn ich sie wiedersehe.}
{700}{}{Aggghh... [Grishams Gesicht zeigt einen entsetzten Ausdruck, als er sich plötzlich an die Brust greift und zusammenbricht.]}
{750}{}{OK, ich muss jetzt wieder an die Arbeit. Bis später mal.}
{800}{}{Du hast Grishams Brahmin gerettet.}
{1101}{}{Du siehst Onkel Biff.}
{1155}{}{Ich weiß meine Nichte war sonderbar.}
{1156}{}{Ich finde über Geschmack kann man sich streiten.}
{1157}{}{Ich bin froh das Grisham nicht mehr am Leben ist um das mit anzusehen.}
{1158}{}{Ich weiß mein Neffe war sonderbar.}
{1159}{}{Ich schätze du gehörst jetzt zur Familie.}
{1160}{}{Pass gut auf meine Nichte auf.}
{1161}{}{Pass gut auf meinem Neffen auf.}
{1228}{}{Junge, versuche erst gar nicht mir das zu erklären. Ich will das nicht hören. Ich geh 'n Priester holen, um das hier nach Gesetz ablaufen zu lassen, wenn er fertig ist nimmst du meinen Neffen und verschwindest.}
{1229}{}{Ich kann nicht leugnen dass mich das nicht anmacht, aber ich muss das tun was Grisham getan hätte. Ihr zwei werdet heiraten und dann gehen.}
{1230}{}{Könntest du mir mal erklären, was du mit meiner Nichte machst?}
{1231}{}{Könntest du mir mal erklären, was du mit meinem Neffen machst?}
{1232}{}{Lass es mich dir einfach erklären Onkel, es gibt da die Vöglein und die Bienen, du weißt schon }
{1236}{}{Na Klasse. Jetzt krieg ich 'nen Klugscheißer als Verwandten. Komm schon... Neffe. Bringen wir's hinter uns.}
{1237}{}{Na Klasse. Jetzt krieg ich 'nen Klugscheißer als Verwandten. Komm schon... Nichte. Bringen wir's hinter uns.}
{1238}{}{Mal sehen. Es sah so aus, als ob du und meine Nichte die Paarungszeit der Brahmins nachgemacht hättet.}
{1239}{}{Mal sehen. Es sah so aus, als ob du und mein Neffe 'nen Horizontalen Tango unterm Betttuch tanzen würdet.}
{1403}{}{Wie kannst du nur die Ehre meines Bruders besudeln }
{1412}{}{Tochter.}
{1413}{}{Sohn.}
{1600}{}{. Ich hoffe, du passt gut auf meine Tochter Miria auf. Sie ist das Licht meines Lebens, und es würde mir das Herz brechen, wenn ihr etwas zustoßen würde. Wo ist sie eigentlich? Ich wollte sie eigentlich wiedersehen.}
{1601}{}{. Wie bekommt dir das Eheleben denn so? Wie ich sehe, reist mein Sohn Davin nicht mit dir zusammen. Ich vermisse ihn schon sehr. Vielleicht kannst du ihn ja beim nächsten Besuch mitbringen. Das wär eine große Freude für einen alten Mann, wenn er seinen einzigen Sohn wiedersehen könnte.}
