# Flee
{100}{}{Lauf!}
{101}{}{Hilfe!}
{102}{}{Wir werden von den Oberflächlern angegriffen.}
{103}{}{Laßt uns in Ruhe.}
{104}{}{Können wir nicht einfach alle friedlich miteinander umgehen?}

# Attack
{150}{}{Verschwindet dahin, wo ihr hergekommen seid.}
{151}{}{Wir wollen euch hier nicht.}
{152}{}{Ihr Oberflächler seid doch alle gleich.}
{153}{}{Es gibt kein Entkommen.}

# General Dialogue (above ground)
{200}{}{Grrrr.}
{201}{}{Buh!}
{202}{}{Stöööhhnnn.}
{203}{}{*Klonk*}
{204}{}{*Klink*}

# General Dialogue (below ground)
{250}{}{Früher einmal lebten wir über der Erde.}
{251}{}{Wie sieht es über der Erde aus?}
{252}{}{Es ist alles so GROSS da oben.}
{253}{}{Wie sieht die Sonne aus?}
{254}{}{Hallo, Oberflächler.}

{300}{}{Ich wußte das wir dir vertrauen konnten.}
{301}{}{Danke für deine Hilfe.}
{302}{}{Erfreut dich wiederzusehen.}