# 0. QUICK LOOK
{100}{}{Du siehst Eldridge.}

# 0. LOOK
{150}{}{Du siehst einen schwer bewaffneten, fettverschmierten Mann. Er sieht sich seine Waffensammlung an den Wänden mit verträumtem Lächeln an.}
{151}{}{Du siehst Eldridge. Er sieht sich seine Waffensammlung mit verträumtem Lächeln an.}

# 1. FALLOUT2 = ENCLAVE_DESTROYED (WTG)
{200}{}{Glückwunsch, Held! Hast du gut gemacht!}
{201}{}{::Feuert einmal in die Luft, beginnt zu tröten und zu brüllen:: Die Enklave is' TOT! TOT! TOT! Jippieeeh!}
{202}{}{::Ding-dong, die Enklave is' tot, die Enklave is' tot... ::}
{203}{}{Enklave is' 'n guter Grund für jeden Bürger, 'ne Waffe tragen zu dürfen.}
{204}{}{Nächstes Mal geh nich' zur Enklave, ohne vorher hier vorbeizuschau'n... ich sorg schon dafür, daß du alle Feuerwaffen hast, die du BRAUCHST.}

# 2. POWER ARMOR (WTG)
{210}{}{Heeeiiiliger Jesus, Maria und Josef - 'ne Powerrüstung!}
{211}{}{Wowiiiiee. ::Reibt sich die Augen:: Das 'ne Powerrüstung?!}
{212}{}{Kneif mich mal einer. Is' das 'ne POWERRÜSTUNG?}
{213}{}{Triff mich der Schlag im Stehen! Eine Powerrüstung! In Reno!}
{214}{}{Verkaufst du mir die Powerrüstung, Freund?!! Hey! Irgend jemand zu Hause?!!}

# 3. NORMAL FLOATS (WTG)
{220}{}{'Ne 9mm is' OK, aber 'ne Kaliber 233 hat mannstoppende Wirkung...}
{221}{}{Eigentlich will ich ja 'n Red-Ryder-Luftgewehr.}
{222}{}{Ich hoff nur, daß niemand vor mir 'n Turboplasmagewehr in die Finger bekommt...}
{223}{}{Ich frag mich nur, wo die Salvatores diese Laserwaffen herhaben...}
{224}{}{Hab letzte Nacht wieder von Plasmawaffen geträumt...}
{225}{}{Sieh besser zu, daß diese Ladung Gewehrpatronen für die Wrights reinkommt...}
{226}{}{Ich hoffe nur, die Mordinos haben genug Gold, um ihre Bestellung zu bezahlen...}
{227}{}{Diese Waffe? Die kann 'n Loch durch 'ne Metallwand stanzen, kann die.}
{228}{}{Der Junge is' 'n Genie... möchte man kaum glauben, wenn man ihn so anschaut...}
{229}{}{Führ besser mal die Hunde aus, bevor die noch überall hinpinkeln.}
{230}{}{Diese ungewaschenen Dörfler horten viele Waffen... is' 'ne rauhe Bande. }
{231}{}{Wenn mich doch nur jemand überfallen würde - dann könnt ich ihn erschießen.}
{232}{}{Muß hier bald mal 'n bißchen Ordnung schaffen.}
{233}{}{Kann die Gang-Jagd nächste Woche kaum erwarten.}
{234}{}{Ich hab MPs, Pistolen, Dynamit, Granaten... und trotzdem kommen hier die Leute rein und wollen Schwerter und Armbrüste. }

# 4. INTRO (WTG)
{240}{}{Willkommen, Held! Wirklich klasse Arbeit, was du mit der Enklave gemacht hast... hast uns allen den Hintern gerettet, jawohl, und dafür dank ich dir. Eldridge heiß ich. Biste vielleicht auf der Suche nach 'n bißchen Eisen, um dein Holster zu füllen?}
{241}{}{Willkommen, der Herr... Eldridge heiß ich. Biste vielleicht auf der Suche nach 'n bißchen Eisen, um dein Holster zu füllen?}
{242}{}{Willkommen, Reisender... Eldridge heiß ich. Biste vielleicht auf der Suche nach 'n bißchen Eisen, um dein Holster zu füllen?}
{243}{}{Ernnnnh? Hollll-sterrr?}
{244}{}{Hängt davon ab, was du so verkaufst.}

# 5. INTRO, FALLOUT 2 (WTG, 4)
{250}{}{Willkommen, Held! Wirklich klasse Arbeit, was du mit der Enklave gemacht hast... hast uns allen den Hintern gerettet, jawohl, und dafür dank ich dir.}
{251}{}{Wenn du was siehst, das du magst, laß es mich wissen, dann machen wir dir 'n *Spezialrabatt* aus, alles klar?}
{252}{}{Aaaalles klar}
{253}{}{Geh weiter}
{254}{}{Klasse! Kann ich mal sehen, was du so am Lager hast?}
{255}{}{Ich weiß ja nicht, ob du mir helfen kannst... Ich such was Bestimmtes.}
{256}{}{Mein Boß... }
{262}{}{Exzellent... kann ich mal deine Sonderposten sehen?}
{257}{}{Jules hat mir gesagt, ich soll hierher kommen, wenn ich 'ne Waffe suche.}
{258}{}{Kaufen die Salvatores ihre Lichtwerfer hier?}
{259}{}{Ich habe dir die Laserpistole gebracht, die ich dir versprochen habe.}
{260}{}{Kannst du Waffen aufrüsten?}
{261}{}{Dann komm ich noch mal wieder, um mich umzuschauen.}

# 6. INTRO (WTG, 9, 10, 11, 12, 13, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26)
{270}{}{Hier im Waffenladen von New Reno haben wir die aktuellen Geräte zum Personenschutz, die man braucht, um irgendwelche feigen Spinner unter die Erde zu bringen. (Lächelt böse.)}
{272}{}{Na, hallöchen, Freund. Was kann ich für dich tun?}
{273}{}{Zum Beispiel?}
{274}{}{Kram ich mögen Kram du auch mögen Kram?}
{276}{}{Dann bist du genau der Mann, den ich suche. Kann ich mal sehen, was du so am Lager hast?}
{277}{}{Kann ich mal sehen, was du so am Lager hast?}
{286}{}{Kann ich mal deine Sonderposten sehen?}
{283}{}{Kannst du Waffen ändern oder aufrüsten?}
{284}{}{Ich bin gerade nicht interessiert, danke.}
{285}{}{Heute nichts, danke.}

# 7. RETARD (4, 5, 6, 19, 20)
{300}{}{Siehst du irgend etwas Glänzendes, das du möchtest? Komm schon, irgendwas muß dich doch interessieren.}
{301}{}{Äh... sicher, sicher. (Sieht dich kritisch an.) Du erinnerst mich an meinen Sklaven, Al. Möchtest du mal sehen, was wir so am Lager haben, Freundchen?}
{302}{}{Jah}
{303}{}{Will was NICHT Lager}
{304}{}{Nee}

# 8. JULES (5, 6)
{310}{}{Jules hat dich also hergeschickt, hm? }
{311}{}{Is' ja auch langsam Zeit, daß der faule Hund was tut für sein Geld... also was kann ich für dich tun, Mister?}
{312}{}{Is' ja auch langsam Zeit, daß der faule Hund was tut für sein Geld... 'tschuldige die Ausdrucksweise. Was kann ich denn für dich tun, Frollein?}

# 9. CAN YOU UPGRADE WEAPONS, ALGERNON DEAD (5, 6, 8)
{330}{}{Nein, nein... wir haben das mal gemacht, aber... (sieht gequält aus) ...na ja, da war so ein Unfall... und nu machen wir das eben nich' mehr. Kann ich vielleicht was anderes für dich tun?}
{331}{}{Also gut. Ich interessier mich da für noch was...}

# 10. CAN YOU MODIFY OR UPGRADE WEAPONS? (5, 6, 8, 11, 12, 13, 17)
{340}{}{Klar können wir das. Was willste denn aufgemöbelt haben?}
{1340}{}{Klar können wir das. (Wirft einen Blick auf deine Ausrüstung.) Aber sieht nicht so aus, als ob du was hättest, an dem ich rumfummeln könnte. Bring mir 'ne Jungfrau... äh, ich mein, "normale" Pistolen und Gewehre, und dann könnt ich dir vielleicht sogar helfen.}
{341}{}{Kannst du irgend etwas mit den Pistolen anfangen, die ich hier habe?}
{342}{}{Eins meiner Gewehre könnte noch 'n paar Extras gebrauchen.}
{343}{}{Kannst du irgend etwas mit diesem Elektrostab hier anfangen?}
{344}{}{Na, egal. Ich hab da an noch etwas Interesse...}
{345}{}{Eigentlich nichts heute.}
{1345}{}{Also gut. Ich interessier mich da für noch etwas...}
{1346}{}{Das werde ich tun. Wiedersehn.}

# 11. PISTOLS MENU (10)
{350}{}{(Entdeckt deine Magnum.) Ich kann in diese Magnum einen Schnellader einbauen, und zwar für $}
{351}{}{Diese Desert Eagle, die du da hast... wenn du willst, kann ich ihr Magazin erweitern, und zwar für $}
{352}{}{Bau einen Schnellader in die Magnum ein.}
{353}{}{Erweitere das Magazin dieser Desert Eagle hier.}
{354}{}{Eigentlich hab ich da an eine andere Waffe gedacht...}
{355}{}{Ach was. Ich wollte noch etwas anderes...}
{356}{}{Eigentlich gar nichts davon. Ich muß gehen.}
{357}{}{Das ist ein bißchen happig. Ich komm zurück, wenn ich mehr Geld habe.}

# 12. RIFLES MENU (10)
{365}{}{(Sieht sich dein Gewehr genau an, nickt.) }
{366}{}{Ich kann an dieses Jagdgewehr da ein Zielfernrohr anbauen, und zwar für $}
{367}{}{Dieses Sturmgewehr, das du da hast... ich kann das Magazin erweitern, für $}
{368}{}{Ich hab ein Nachtsicht-Zielfernrohr, das ich in diese FN FAL da einbauen kann, für $}
{369}{}{Also gut... bau in das Colt-Jagdgewehr ein Zielfernrohr ein.}
{370}{}{Erweitere das Magazin des AK-112-Sturmgewehrs.}
{371}{}{Bau dieses Nachtsicht-Zielfernrohr in die FN FAL ein.}

# 13. MELEE MENU (10)
{385}{}{Du willst, daß ich diesen Elektroschocker aufmotze? Ich kann ihn dir ÜBERLADEN, und zwar für $}
{386}{}{Sicher.}

# 14. RETURN ITEMS MENU (11, 12, 13)
{395}{}{(Eldridge nimmt die Waffe, untersucht sie kritisch.) Also gut... wart 'nen Augenblick, und ich seh, was ich für dich tun kann. (Er verschwindet nach hinten.)}
{396}{}{Okay.}

# 15. RETURN ITEMS MENU (14)
{400}{}{(Du wartest...)}
{401}{}{Du wartest...}

# 16. RETURN ITEMS MENU (15)
{405}{}{(Und wartest immer noch...)}
{406}{}{Dum-di-dum-di-dum...}

# 17. RETURN ITEMS MENU (16)
{410}{}{(Du bist am Einschlafen, als Eldridge endlich zurückkommt.) Tut mir leid, daß du so lange warten mußtest... hier. Damit solltest du es jedem Spinner geben können, der versucht, dir auf den Schatten zu treten.}
{411}{}{Danke. Kannst auch noch andere Waffen von mir aufrüsten?}
{412}{}{Danke. Ich wollte da noch etwas...}
{413}{}{Danke. Ich geh es mal ausprobieren.}

# 18. I'M LOOKING FOR SOMETHING SPECIAL (5, 6, 7, 8)
{420}{}{Oh... wir sind also ein kritischer Kunde, was? Tja, manchmal machen's auch ein paar nette Teile in unsere Stadt... das hier, zum Beispiel. (Hält etwas... Seltsames hoch.) Echte Vorkriegstechnik. Is' das nix?}
{423}{}{Äh... klar, das ist schon "etwas". Kann ich's mir mal anschauen?}
{424}{}{Klar. Ich interessier mich aber für etwas anderes...}
{425}{}{Kein Interesse. Trotzdem danke.}

# 19. MODULE 2 (18)
{430}{}{(Es ist ein hübsches Plastikquadrat mit Löchern und Metallinien überall. Es sind einige seltsame Wortsymbole darauf geschrieben. Es sieht aus wie eine Art mechanischer Toast, und dir läuft das Wasser im Munde zusammen.)}
{431}{}{(Es sieht aus wie eine Schaltplatine. Sie ist etwas staubig, aber noch in guter Verfassung. Sieht aus wie ein Teil von... etwas. Auf die Schaltplatine ist 'Vault-Tec-Stimmerkennungsmodul' gedruckt.)}
{432}{}{(Es ist eine komplizierte Schaltplatine. Ein Speicherchip ist integriert, und an der Seite sind eine Reihe von Computer- anschlüssen, inklusive einem In- und einem Output. Auf die Platine ist 'Vault-Tec-Stimmerkennungsmodul' gedruckt.)}
{433}{}{Ich wollen lecker Platte}
{434}{}{Ich wollen was andres}
{435}{}{Ich wollen gehn}
{436}{}{"Vault-Tec"? Das *muß* was Wichtiges sein. Wieviel willst du?}
{437}{}{Wird ja auch Zeit... wieviel willst du für dieses Modul?}
{438}{}{Nein danke, ich möchte etwas anderes...}
{439}{}{Nicht heute, danke.}

# 20. BUY IT (19, 20)
{450}{}{Dreitausend Mäuse. Nimm es oder laß es.}
{451}{}{Das letzte Mal: dreitausend Mäuse. Nimm es oder laß es.}
{452}{}{Aaaalso guuuut.}
{454}{}{Spring ihm an den Hals und nimm den mechanischen Toast}
{455}{}{Lasses}
{457}{}{Äh, das is' 'n bißchen viel. Wie wär's mit... 1500?}
{458}{}{Nein danke. Ich wollte etwas anderes...}
{459}{}{Ich laß es sein.}

# 21. BUY IT (20)
{470}{}{$2500. Und das ist mein letztes Angebot.}
{471}{}{Also gut, also gut. Hier hast du.}
{472}{}{Dann vergiß es. Ich wollte etwas anderes...}
{473}{}{Nein danke. Man sieht sich.}
{474}{}{Das ist mir zuviel. Laß uns noch mal darüber reden, wenn ich etwas mehr Geld habe.}

# 22. BUY IT (20, 21)
{480}{}{(Lächelt, reibt sich die Hände, während du das Geld auf den Tisch legst.) Also gut, hier hast du's. }
{481}{}{(Denkt einen Moment darüber nach, sieht dich prüfend an, nickt dann.) Also gut... ist praktisch geschenkt, aber da hast du. (Gibt dir das Modul, nimmt dein Geld.) }
{482}{}{Kann ich noch was für dich tun?}
{485}{}{Ja, ich interessiere mich da für noch etwas...}
{486}{}{Heute nichts mehr, danke.}

# 23. CAN I BUY LASER PISTOLS HERE? (5, 6, 8)
{495}{}{(Blinzelt überrascht, lacht dann.) Ha! Nein, nein... diese Waffen sind schon was anderes, was? Ich WÜRDE ja gern eine in meine Finger bekommen... sieh dir mal die Reichweite an, die Kraft, die Feuergeschwindigkeit... (Starrt in die Ferne, seufzt.)}
{496}{}{Und wenn ich dir nun anbiete, dir eine zu besorgen?}
{497}{}{Wär schon nett, eine zu haben. Sag mal, ich wollte da noch was anderes...}
{498}{}{Na ja. Ich mußte mal fragen. Danke, Eldridge.}

# 24. WHAT IF I GOT YOU ONE? (23)
{505}{}{(Schielt dich an, als ob er entscheidet, ob er dir trauen kann.) Ich würde nicht nein sagen... wenn du das, na, im Stillen tätest. Ich würd dich für den Ärger bezahlen... (runzelt die Stirn) ...falls du mir keinen MACHST.}
{506}{}{Das macht keinen Ärger... ich hab eine dabei. Hier ist sie.}
{507}{}{Ich tu's. Aber vorher will ich noch etwas anderes...}
{508}{}{Na, was soll's. Vielleicht kannst du mir mit etwas anderem helfen...}
{509}{}{Mach ich. Ich treib dir eine auf und komme dann damit zurück.}
{510}{}{Das kann ich nicht versprechen... Ärger scheint mein ständiger Begleiter zu sein. Man sieht sich, Eldridge.}

# 25. LASER PISTOL RETRIEVED? (5, 6, 8, 24)
{520}{}{Na, da wird doch der Hund in der Pfanne verrückt!}
{521}{}{Teufel auch! Ich halte mein Versprechen, hier ist etwas für den Ärger...}
{522}{}{(Gibt dir einen Haufen Chips, nimmt die Pistole.) Mist... sieht komisch aus, oder? (Untersucht den Lauf.) Hmmm...}
{523}{}{Ich wollte noch etwas anderes...}
{524}{}{Ist mir eine Freude, mit dir zu handeln, Eldridge. Viel Spaß.}

# 26. REP: MADE MAN (5, 6, 8)
{530}{}{(Eldridge sieht dich von oben bis unten an, und sein Ton wird respektvoller.) Klar, na sicher. Laß mich dir unsere Sonderposten zeigen... natürlich zu Sonderpreisen.}
{532}{}{Eigentlich interessiere ich mich für etwas anderes...}
{533}{}{Was soll's. Ich komm zurück.}

# 27. AFTER HOURS (Dogs Barking)
{545}{}{Haltet die Schnauze, ihr Hunde, hört ihr?}
{546}{}{Haltet die Schnauze, ihr winselnden Köter!}
{547}{}{Kreaturen der Nacht... haltet die Schnauze!}
{548}{}{Packard! Buck! Missy! Ihr haltet besser alle die Schnauze, oder ich komm euch da gleich rein!}
{549}{}{Vermaledeite Hunde!}
{550}{}{Noch ein einziges WUFF von euch, und ich komm euch da rein!}

# 28. DOOR
{560}{}{Was, glaubst du, ich hätte die Augen verbunden?}
{561}{}{Hände weg von der Tür!}
{562}{}{Laß bloß die Tür in Ruhe.}
{563}{}{Du berührst die Tür, und danach berührst du nie wieder was.}
{564}{}{Seltsam, die letzte Person, die diese Tür angefaßt hat, liegt jetzt auf Golgotha begraben. Faß die nicht noch mal an.}

# 29. ROOM:
{575}{}{Da drin hast du nichts zu suchen! Raus! Raus da!}
{576}{}{Du hast keinen Zutritt da hinten! Raus!}
{577}{}{Raus aus dem Hinterzimmer, bevor ich dich durchlöchere!}
{578}{}{Wenn du da hinten drin bleibst, benutze ich dich als Zielübung!}

{600}{}{Junge, wir haben geschlossen... }
{601}{}{Mädchen, wir haben geschlossen...}
{610}{}{Ich schlag dir vor, daß du da schnell rauskommst, bevor ich dich totschieße.}

{700}{}{Elende Hunde! Ich geh zurück ins Bett.}
{701}{}{Dumme Hunde! Morgen früh schläfere ich euch ein.}
{702}{}{Haltet ihr blöden Hunde endlich die Schnauze! So blöd wär niemand, in ein Waffengeschäft einzubrechen!}

{800}{}{Du hast Eldridge eine Laserpistole geliefert.}

# END LINES
{5256}{}{...hat mir gesagt, ich sollte mal reinschauen, und daß du mich schon "ausrüsten" würdest.}
{5500}{}{.}



#added by killap
{801}{}{Hey, seh ich aus wie ne Art Zauberer? Du brauchst erst eine Waffe wenn du sie Aufrüsten willst. Jetzt hau ab und find ne Knarre die ich Aufrüsten kann... Meine Güte!}
{802}{}{Komm wieder wenn du die Kohle hast.}