# QUICK LOOK
{100}{}{Du siehst eine Mieze.}

# 1. LOOK (PLAYER IS MALE)
{150}{}{Du siehst eine halbwegs attraktive Frau. Sie scheint dich abzuschätzen.}
{151}{}{Du siehst eine Mieze. Sie scheint sich zu fragen, ob sie sich um dich kümmern soll oder nicht.}

# 2. LOOK (PLAYER IS FEMALE)
{160}{}{Du siehst eine halbwegs attraktive Frau. Sie sieht dich an, als ob du eine Rivalin wärst.}
{161}{}{Du siehst eine Mieze. Sie sieht dich an, als ob du eine Rivalin wärst.}

# 3. [ENCLAVE DESTROYED]
{200}{}{Oh mein…Er ist es. } 
{201}{}{Du bist der größte Hengst der Welt.}
{200}{}{::KICHER::} 
{203}{}{Wie ich höre, suchen die Brüder nach dir. Die wollen 'nen Film über dein Abenteuer drehen.}
{204}{}{Yeah, }
{205}{}{::Claps::}
{206}{}{::Cheers::}
{207}{}{Oh my…it's her. }
{208}{}{Weg da, Mädel!}
{209}{}{::Gives you the thumbs up sign::}

# 4. [POWER ARMOR]
{225}{}{Kommt gar nicht in Frage. Mit dem Ding nicht. NIEMALS.}
{226}{}{Wie zum Geier gehst du mit dem Ding ins Bad?}
{227}{}{Ist das etwa wie ein Vibrator?}
{228}{}{Ist das etwa ein neuartiges Ganzkörperkondom?}

# 5. [MALE, PORN STAR]
{235}{}{Brauchst du irgendwas, }
{236}{}{Hier drüben }
{237}{}{Da! Das ist er!}
{238}{}{Es ist }
{239}{}{Ich wünschte, ich könnte 'ne Szene mit dir machen, }
{240}{}{That boy really brings on the cream.}
{241}{}{He can give me a purple mushroom anytime.}
{242}{}{Nasty little crotch cobra you've got there.}

# 6. [PORN STAR, FEMALE]
{245}{}{Need anything, }
{246}{}{If I have to take care of one more actor today, I'm going to throw up.}
{247}{}{Gar nicht so einfach, 'ne Mieze zu sein.}
{248}{}{I hear the Families are getting tense again.}
{249}{}{Letzte Woche trat ich Jules in die Kronjuwelen.}
{250}{}{I wish the Brothers would let me act.}
{251}{}{I don't know what the Corsican Brothers SEE in her…}

# 7. [MALE, PRIZEFIGHTER]
{255}{}{Oh my…it's him. }
{256}{}{Sieh dir diese Muskeln an! Da werde ich ganz schwach…}
{257}{}{He's built like a tank. Check out that barrel.}
{258}{}{Check out the barrel on that tank…}
{259}{}{He's all mine…}
{260}{}{::Sigh::}
{261}{}{That boy really brings on the cream.}
{262}{}{Nasty little crotch cobra you've got there.}

# 8. [FEMALE, PRIZEFIGHTER]
{270}{}{Oh mein…sie ist es. }
{271}{}{Willkommen im Studio, meine Dame.}
{270}{}{Oh my…it's her. }
{271}{}{Welcome to the studio, ma'am.}
{272}{}{She looks so…(shivers)…dangerous.}
{273}{}{She's pretty sexy.}
{274}{}{Hello, ma'am. Let me know if I can help you with anything.}

# 9. [MALE, MADE MAN/BERSERKER]
{280}{}{Oh mein…er ist es. }
{281}{}{Willkommen im Studio, mein Herr.}
{282}{}{He looks so…(shivers)…dangerous.}
{283}{}{That's one badass if I ever saw one.}
{284}{}{That boy really brings on the cream.}
{285}{}{Nasty little crotch cobra he's got there.}

# 10. [FEMALE, MADE MAN/BERSERKER]
{290}{}{Oh mein…sie ist es. }
{291}{}{Willkommen im Studio, meine Dame.}
{292}{}{She looks so…(shivers)…dangerous.}
{293}{}{Sie ist sehr sexy.}
{294}{}{Hello, ma'am. Let me know if I can help you with anything.}

# 11. [MALE, NO REP + MYRON]
{300}{}{Oh, Mist! Es ist Myron! Lauf!}
{301}{}{Crap! It's Myron. Stay calm…he can smell fear.}
{302}{}{Du solltest Myron besser von mir fernhalten.}
{303}{}{Myron, you better stay the HELL away from me.}
{304}{}{Wenn Myron hier anfängt zu arbeiten, dann bin ich weg.}
{305}{}{Myron, have you passed the five second mark yet?}
{306}{}{Myron, you better get out of here before the Brothers see you.}

# 12. FLOAT/[LEATHER]
{315}{}{Don't these leather freaks know that they're supposed to be here on Wednesdays?}
{316}{}{Spitze. Noch so 'n SM-Spielchen.}
{317}{}{Oooooh, schwarzes Leder. Nun, DAS ist neu.}
{318}{}{Leder und Fesseln sind bei uns erst nächste Woche dran.}
{319}{}{Toll, noch so ein Leder-Häschen.}
{320}{}{Leder-Häschen, das Casting ist am Mittwoch, verstanden?}

# 13. [NO REP + BONENOSE]
{325}{}{Wenn ich mich heute um noch einen Schauspieler kümmern muß, muß ich mich übergeben.}
{326}{}{Ich hab gehört, daß sich in den Familien wieder was zusammenbraut.}
{327}{}{Der Typ mit dem Knochen in der Nase ist irgendwie süß. So auf 'ne sadomasochistische Art.}
{328}{}{Sieh dir den Wilden mit dem Knochen in der Nase gut an. Der bringt's noch mal weit.}
{329}{}{Na toll. NOCH 'ne Mieze. So wie die aussieht, arbeitet die bestimmt für den halben Preis.}
{330}{}{Who's the guy with the bone in his nose?}
{331}{}{Check out the tribal with the bone in his nose. He'll go far.}
{332}{}{Whoa, I've seen accidents on the set, but never a guy who got a bone caught in his nose.}
{333}{}{I wish the Brothers would let me act.}
{334}{}{::Glares at you::}
{335}{}{Great. ANOTHER fluffer. She'll probably work for half price from the look of her.}
{336}{}{Wer ist die denn?}
{337}{}{Wer bist du denn?}

# 14. [NO REP]
{345}{}{Wenn ich mich heute um noch einen Schauspieler kümmern muß, muß ich mich übergeben.}
{346}{}{Gar nicht so einfach, 'ne Mieze zu sein.}
{347}{}{I hear the Families are getting tense again.}
{348}{}{I kicked Jules in his family jewels last week.}
{349}{}{I wish the Brothers would let me act.}
{350}{}{Na toll. NOCH 'ne Mieze. So wie die aussieht, arbeitet die bestimmt für den halben Preis.}
{351}{}{::Glares at you::}
{352}{}{Wer ist die denn?}
{353}{}{Wer bist du denn?}

# 15. [ENCLAVE DESTROYED]
{360}{}{Die Enklave? Präsident? Erzähl mir die ganze Geschichte.}
{361}{}{Tom French scripted me. He has soft, gentle hands.}
{362}{}{They were still fighting the WAR?! Really! Good thing you wasted those bastards.}
{363}{}{You are a total badass. I mean, you start from a simple spear-chucking tribal - no offense - and go on to save the whole world. You kick ass. End of story.}
{365}{}{Erzähl mir alles über deinen Kampf gegen die Enklave...ich hol dir 'n kaltes Bier.}
{366}{}{I hear the Brothers are looking for you. They want to do a film based on your adventure.}

# 16. [PORN STAR]
{370}{}{Ooops. I dropped something in your pants. Let me get it.}
{371}{}{Ähm, du möchtest nicht zufällig einen saufen gehen, oder? Und wie wär's mit 'nem bißchen Liebe?}
{372}{}{How do you keep so fit?}
{373}{}{Can I have your autograph? On my chest?}
{374}{}{You being helped, }
{375}{}{I'll need some help with that barrel of yours.}
{376}{}{I hear you're very…hard to work with.}
{377}{}{I heard you cop an attitude, then you cop a feel. Fine by me.}
{378}{}{I'm really happy to know you! I mean, wow, you're }
{379}{}{Um, I know there's no filming going on, but do you need a fluffer anyway?}
{380}{}{Need someone to take care of that for you?}
{381}{}{Need a moist towelette, }
{382}{}{I loved you in Great Balls for Hire.}
{383}{}{I loved you in Good Will Humping.}
{384}{}{You were great in Pokeahotass.}
{385}{}{You were great in Vault Sexteen. Inspired, even.}
{386}{}{I haven't seen the Brothers around…try the office, maybe?}
{387}{}{Any chance you could talk the Corsican Brothers into letting me act?}
{388}{}{Fluffers have the important job of keeping the actors hard.}
{389}{}{Could I act in your next movie?}
{390}{}{I don't want to be a fluffer all my life. No, really.}
{391}{}{I'm just doing this to pay for school.}
{392}{}{My boyfriend doesn't know I work here.}
{393}{}{Hum job? I'll tell you about them some other time.}
{394}{}{My boyfriend doesn't know I work here.}
{395}{}{I wish some of the actors would shower. I mean a regular shower.}
{396}{}{I really want to act.}
{397}{}{My girlfriend doesn't know I work here.}
{398}{}{Gibst du mir ein Autogramm?}
{399}{}{Ähm, du möchtest nicht zufällig einen saufen gehen, oder? Wenn du an Frauen interessiert bist, heißt das.}
{400}{}{::Ignores you::}

# 17. [PRIZEFIGHTER]
{420}{}{Möchtest du mit mir in den Ring steigen, Champion?}
{421}{}{Nice unit you got there.}
{422}{}{Need someone to take care of that for you, champ?}
{423}{}{Getting out of boxing and into porn? Same thing, different stage.}
{424}{}{Are you getting into the business, too? Welcome aboard, champ.}
{425}{}{Getting into the business? Well, at least you won't have to start where I am.}
{426}{}{Me? I'm a fluffer. Sometimes.}
{427}{}{Fluffers have the important job of keeping the actors hard.}
{428}{}{The Brothers say I'm in-valuable. That's why they sleep with me so much.}
{429}{}{You should go into porn. You got the body for it.}
{430}{}{Wanna box?}
{431}{}{Hum job? I'll tell you about them some other time.}
{432}{}{Watch out for the Masticator. He's a real jerk. He tried to bite my ear off once.}
{433}{}{Hallo, Lady. Kann ich dir helfen mit…*irgendwas?*}
{434}{}{Ähm, wenn du später noch ein bißchen Gesellschaft suchst, Lady…}
{435}{}{Do you want the usual, ma'am?}

# 18. [MADE MAN]
{450}{}{Hallo, der Herr. Kann ich dir helfen mit…*irgendwas?*}
{451}{}{If you're looking for a little company later…}
{452}{}{Do you want the usual, sir?}
{453}{}{Need someone to take care of that for you?}
{454}{}{Put in a good word with the boss for me?}
{455}{}{Are you thinking of getting into the business, too?}
{456}{}{You should go into porn. You got the body for it.}
{457}{}{Hum job? I'll tell you about them some other time.}
{458}{}{Hello, ma'am. Can I help you with…*anything?*}
{459}{}{Ähm, wenn du später noch ein bißchen Gesellschaft suchst, Lady…}
{460}{}{Do you want the usual, ma'am?}

# 19. [BONE-NOSE]
{465}{}{Nein danke. Ich könnte ja mit meinem Lippenstift mehr Spaß haben.}
{466}{}{You? Sorry, I'll NEVER be that desperate.}
{467}{}{Äh, überkompensiert dein Freund mit dem Knochen in der Nase vielleicht was?}
{468}{}{Hat dein Freund mit dem Knochen in der Nase 'ne Freundin?}
{469}{}{Dein Freund mit dem Knochen in der Nase ist irgendwie süß. So auf 'ne sadomasochistische Art.}
{470}{}{Wer ist denn dein süßer Freund mit dem Knochen in der Nase?}
{471}{}{Tell the tribal with the bone in his nose that he'll go far in this industry.}
{472}{}{Whoa, I've seen accidents on the set, but never a guy who got a bone caught in his nose.}
{473}{}{I haven't seen the Brothers around…try the office, maybe?}
{474}{}{Fluffers have the important job of keeping the actors hard.}
{475}{}{I really want to act.}
{476}{}{I don't want to be a fluffer all my life. No, really.}
{477}{}{My boyfriend doesn't know I work here.}
{478}{}{Are you being helped?}
{479}{}{If you're looking for a job, talk to the Brothers.}
{480}{}{I'm just doing this to pay for college.}
{481}{}{I'd bang Avellone for free.}
{482}{}{It's not that I don't want to talk to you, but...oh, wait that IS it.}
{483}{}{I need to lie down.}
{484}{}{Hum job? I'll tell you about them some other time.}
{485}{}{You don't have a problem with skin flicks, do you?}
{486}{}{You the new fluffer?}
{487}{}{Got a towel? One of the actors had an…accident.}
{488}{}{Just don't bite the actors, and you should do fine.}
{489}{}{I wish some of the actors would shower. I mean a regular shower.}
{490}{}{Ähm, bist du neu hier?}
{491}{}{Salzmilch? Man gewöhnt sich dran.}

# 20. [NO REP]
{500}{}{Nein danke. Ich könnte ja mit meinem Lippenstift mehr Spaß haben.}
{501}{}{You? Sorry, I'll NEVER be that desperate.}
{502}{}{I haven't seen the Brothers around…try the office, maybe?}
{503}{}{Fluffers have the important job of keeping the actors hard.}
{504}{}{I really want to act.}
{505}{}{I don't want to be a fluffer all my life. No, really.}
{506}{}{My boyfriend doesn't know I work here.}
{507}{}{Are you being helped?}
{508}{}{If you're looking for a job, talk to the Brothers.}
{509}{}{I'm just doing this to pay for college.}
{510}{}{I'd bang Avellone for free.}
{511}{}{It's not that I don't want to talk to you, but...oh, wait that IS it.}
{512}{}{I need to lie down.}
{513}{}{Hum job? I'll tell you about them some other time.}
{514}{}{You don't have a problem with skin flicks, do you?}
{515}{}{You the new fluffer?}
{516}{}{Got a towel? One of the actors had an…accident.}
{517}{}{Just don't bite the actors, and you should do fine.}
{518}{}{I wish some of the actors would shower. I mean a regular shower.}
{519}{}{Ähm, bist du neu hier?}
{520}{}{Salzmilch? Man gewöhnt sich dran.}

{1200}{}{. Ihr wißt schon - hat der Enklave in den Hintern getreten.}
{1204}{}{! Was 'ne Art, der Enklave eins überzuziehen!}
{1207}{}{. Ihr wißt schon - hat der Enklave in den Hintern getreten.}
{1235}{}{?}
{1236}{}{!}
{1238}{}{!}
{1239}{}{.}
{1245}{}{?}
{1255}{}{.}
{1270}{}{.}
{1280}{}{.}
{1290}{}{.}
{1374}{}{?}
{1378}{}{!}
{1381}{}{?}