# 0. QUICK LOOK (WTG)
{100}{}{Du siehst Vater Tully.}

# 0. LOOK (WTG)
{150}{}{Du siehst einen älteren Mann in brauner Kutte und mit Whiskeyflecken auf den Wangen. Er wirkt in weeeenig wackelig auf den Beinen.}
{151}{}{Du siehst Vater Tully. Er sieht aus, als ob er sich ein paar hinter die Binde gekippt hat.}

# 1. FLOAT: NORMAL COMMENTS (WTG)
{200}{}{Ich bin richtig gesegnet.}
{201}{}{Und die Frauen sollten mich mit einem heiligen Kuß grüßen.}
{202}{}{Ich trink mir den Teufel aus dem Leib, wenn ich muß.}
{203}{}{Eine wahre Predigt hat keine Worte...}
{204}{}{Ich fühl den Himmel in mir.}
{205}{}{Verdammt, ich werd nüchtern. Ich brauch 'n Drink.}
{206}{}{Warum rutscht'n der Boden so weg...}
{207}{}{'Ne Flasche Alk und ich werd mit lockerer Zungen reden.}
{208}{}{'N Viertelchen Alk würd diesen Teufel in meinem Kopf umbringen.}
{209}{}{Ooohhh. 'Ne Stunde, seit ich den letzten Schluck hatte...}
{210}{}{Zeit, einen tiefen Schluck heiligen Geist zu trinken.}
{211}{}{Ich trinke im Namen aller Dinge, die heilig sind.}

# 2. FLOAT PORN STAR [FEMALE] (WTG)
{220}{}{Willsse wissen, was die Kirche zu Fellatio sagt?}
{221}{}{Sünde! Verderbnis! Äh... was machst'n später?}
{222}{}{Miststück! Dirne! Leichtes Mädchen! Äh... was machst'n später?}

# 3.  INTRO, FALLOUT2 FLAG = ENCLAVE_DESTROYED (WTG)
{225}{}{Wie geht's? Kenn ich dich? }
{226}{}{Grüssse... was kann Vater Tully für dich tun...}
{227}{}{Du die Enklave wie 'n Sturm zertreten... äh, wie 'n Wurm? Bist 'n Held.}
{228}{}{Ich Heeeld}
{229}{}{Ich Tschüssi.}
{230}{}{Ich hab die Enklave auseinandergenommen, ja. Die haben angefangen — ich hab's beendet. Aber versteh mich nicht falsch, Vater. Ich bin nur ein Mann, der versucht, seinen Weg in dieser erbarmungslosen Welt zu gehen... ich bin kein Held.}
{231}{}{Ich hab die Enklave auseinandergenommen, ja. Die haben angefangen — ich hab's beendet. Aber versteh mich nicht falsch, Vater. Ich bin nur eine Frau, die versucht, ihren Weg in dieser erbarmungslosen Welt zu gehen... ich bin keine Heldin.}
{232}{}{Ich geh dann mal lieber, Vater. War nett, dich zu riech... äh, mit dir zu reden.}

# 4.  I GOT A HINTBOOK FOR YOU (3)
{235}{}{Du bissn HELD. Ich hab was für dich. Weiß nich', was es zuerst war, aber ich glaub, du kannsses brauchen.}
{236}{}{Ich nehmen}
{237}{}{Ich nicht brauchen... ich wollen raus}
{238}{}{Klar. Ich nehm alles, was du mir gibst, Vater. Äh, na ja, solange es nichts Unanständiges ist.}
{239}{}{Äh... nein danke, Vater. Ich muß jetzt wirklich los.}

# 5.  HERE'S THE HINTBOOK (4)
{240}{}{(Tully geht zu einer Bank rüber, reißt ein Brett vom Sitz und zieht ein dreckiges Taschenbuch darunter hervor.) Da, bitte. Issn bißchen dreckig, aber... (Gibt es dir.)}
{241}{}{Danke}
{242}{}{Danke, Vater. Glaub ich.}

# 6.  NO HINTBOOK/POST HINTBOOK (3, 5)
{245}{}{Du bissn Held. Du hasses verdient. Nich' viele Spieler bringen die Tage ihr Spiel zu ENDE, aber du bist den ganzen Weg gegangen. Ich bin stolz auf dich. Ganz NEW RENO is' stolz auf dich.}
{246}{}{Dankäh, Vader. Schüs}
{247}{}{Danke, Vater. Paß auf dich auf, hörst du?}

# 7.  INTRO (WTG)
{250}{}{Grüße, mein Sohn. Was kann Vater Tully in dieser wunner-, wunnerschön' Reno-Nacht für dich tun?}
{251}{}{Grüße, mein Sohn. Was kann Vater Tully an diesem wunner-, wunnerschön' Reno-Tag für dich tun?}
{252}{}{Hä-hä. Du stinken wie Brennerei. Du stinken wie Pipi}
{253}{}{Ich wie Mister Sonne}
{254}{}{Naa-aacht.}
{255}{}{Äh, eigentlich isses ja Tag, Vater.}
{256}{}{Äh, eigentlich isses ja Nacht, Vater.}
{257}{}{Wer bist du denn?}
{258}{}{Bist du betrunken?}
{259}{}{"Vater" Tully, hä? Machst du auch Scheidungen?}
{261}{}{Sag mal, ich hab dir was Alk mitgebracht, Vater. Können wir 'n Moment reden...?}
{262}{}{Nichts. Tut mir leid, daß ich dich belästige.}

# 8.  HEE HEE. YOU STINK LIKE STILL. YOU STINK LIKE PEE (7)
{270}{}{(Schnuppert an seinen Achselhöhlen, dann an seiner Kutte.) Meine Güte, ich riech wirklich streng, was? Himmel, ich stinke wie 'ne Brennerei! Mach mich besser sauber, bevor Mrs. Wright mich erwischt...}
{271}{}{Tschüssi Pipimann.}

# 9.  UH, ACTUALLY, IT'S NIGHT/DAY TIME, FATHER (7)
{275}{}{Himmel, muß verschlafen haben... hätte's doch sonst bemerkt... was zum Teufel hab ich grad gesagt?}

# 10. WHO ARE YOU? (7, 9)
{290}{}{Vater Tully, zu dein' Diensten. Bin das geistliche Oberhaupt der guten L... naja, der Leute in New Reno.}
{291}{}{Und das kannst du nur erreichen, indem du dich betrinkst?}
{292}{}{Ich hab da ein paar Fragen über New Reno...}
{295}{}{Ach so. Na, danke für das Gespräch.}

# 11. ARE YOU DRUNK? (7, 9, 10)
{300}{}{Keineswegs! FRÜHER hab ich's mi'm Alkohol gehabt, aber die Abstinenzler-Vereinigung hat mir geholfen, diese schreggliche Gewohnheit aufßugeben!}
{301}{}{Die Abstinen—?}
{302}{}{Oh. Ich hab nicht —}
{303}{}{Aufzu —?}

# 12.  TEMPERANCE UNION/MISSUS WRIGHT (16)
{305}{}{Absinenßler-Vereinigung, Mrsss. Wright... is' doch dasselbe. Versucht, New Reno zu sssäubern. Hat wirklich gute Arbeit geleissstet bei mir.}
{306}{}{Aber sicher. Ich hab da noch ein paar Fragen...}

# 13.  QUESTIONS . . . (10, 12, 16, 20)
{315}{}{Fragen? Kann nich' behaupten, daß ich zuviel weiß. Frach trotzdem.}
{316}{}{Hast du schon mal von Vault 13 gehört?}
{317}{}{Ich bin hier, weil ich meine Sippe suche. Sie sind aus meinem Dorf entführt worden.}
{318}{}{Du weißt nicht zufällig, wie man einen Öltanker repariert, oder?}
{319}{}{Hast du schon mal was von einem GECK gehört?}
{320}{}{Kannst du mir etwas über New Reno erzählen?}
{323}{}{Vielleicht komm ich noch mal wieder, wenn du ein bißchen trockener bist.}

# 14.  I'M ON A QUEST TO FIND THE GECK . . . (13)
{325}{}{Tja... Reno... is'... na, es is'...}
{326}{}{Ein Garten-Eden-Erschtellungskitt? Kann nich' behaupten, dassich das schon mal gehört hab. Tja, außer...}
{327}{}{Vault 13? Keine Ahnung... tja, ich mein, im Norden von hier gibt's Vault City. Is' das vielleicht das, wonach de suchst? Hey, jetzt, wo ich darüber nachdenke...}
{328}{}{Sklavenhännler vielleicht? Hab gehört, daß die da 'ne Menge ihrer Vorräte herbekommen... naja, außer...}
{329}{}{Tanker? So 'n Ding mit Leinen und 'nem Faß? Darüber weiß ich nich' viel... na ja... außer...}
{330}{}{Ja...?}

# 15.  YES . . . ? (14)
{335}{}{Sag mal, entschuldige, wenn ich frage, aber du hast nicht zufällig ein Fläschchen dabei? Ich brauch was für die Messe... und äh, mein Hals issn bißchen trocken.}
{336}{}{Klar. Hier, bitte.}
{337}{}{Hab ich nicht, tut mir leid.}
{338}{}{Ich könnte ja was holen gehen, wenn du willst.}

# 16. ARE YOU DRUNK? (11)
{440}{}{Jetzt bin ich auf dem geraden und beschwerlichen Weg, das verdank ich Mrs. Wright... die Gute. Bin schon seit min'stens einem... äh, Monat trocken. Oder war's doch 'ne Woche? Äh, Mist, ich weiß es nich' mehr. }
{441}{}{'Ne Woche is' wohl 'n bißchen übertrieben. Sag mal, ich hab da noch ein paar Fragen...}
{442}{}{Trocken wie Sand, was? Wie viele Finger halte ich hoch?}
{443}{}{Abstinenzler-Vereinigung?}
{444}{}{Mrs. Wright?}
{445}{}{Vielleicht komm ich noch mal wieder, wenn du nüchtern bist.}

# 17. ROB THE POOR BOX (27)
{450}{}{(Tully stolpert über die Sammelbüchse neben dem Podium und fischt darin herum.) }
{451}{}{Äh... hmmnn. (Seine Hand kommt leer wieder heraus.) Hab leider gerade gar keine Chips.}
{452}{}{Hmnnn. Hier haste... (Er gibt dir ein paar Chips.) Gesegnet seien die Armen. Geh, gib's im Namen von allem aus, was heilig ist.}
{453}{}{Trotzdem danke, Vater. Ich werd sehen, ob ich etwas Alk auftreiben kann.}
{454}{}{Danke, Vater. Ich komm bald mit dem Alk zurück.}

# 18. BISHOP, THE SCOOP (30)
{460}{}{Schenkt seiner Frau und Tochter keine zwei Sekunden... kein Wunder, daß die ganz wiiild geworden sind. Hä-hä... kommt alles bei der Beichte raus, verstehste...}
{461}{}{Oh, und was sagt Mr. Bishop so bei der Beichte?}
{462}{}{Oh, und was sagt Mrs. Bishop so bei der Beichte?}
{463}{}{Was sagt Mrs. Bishop so bei der Beichte? Sie spricht doch nicht über mich, oder... ich meine, weil es da nichts zu erzählen gibt. Alles Lügen.}
{464}{}{Oh, und was sagt Bishops Tochter in der Beichte?}
{465}{}{Äh, was sagt Bishops Tochter in der Beichte? Nichts über mich hof... äh, nichts Schlimmes, hoffe ich.}
{466}{}{Kann ich mir vorstellen. Kann ich dir noch ein paar Fragen stellen, Vater?}

# 19. BISHOP AND VAULT CITY (32)
{470}{}{Nee, Vault City hat gesagt, er soll's sich in den HINTERN stecken. Also... kurz danach wird Vault City plötzlich ständig überfall'n. Schnell. Schmerzhaft. Un' die ganze Zeit sitzt da Bishop und sagt, ich KÖNNT euch ja helfen, WENN ihr euch mit New Reno ssusammentut.}
{471}{}{Hmmm. Was kannst du mir noch über die Bishops erzählen?}
{472}{}{Bishop versucht es also mit Erpressung? Ein paar Überfälle, ein paar Tote und Vault City könnte sich mit New Reno anfreunden. Nich' besonders subtil, aber wirkungsvoll. Was kannst du mir noch über die Bishops erzählen?}
{473}{}{Das klingt nach 'ner seltsamen Taktik... ich meine, ist doch viel wahrscheinlicher, daß Vault City anderswo Hilfe sucht, bevor sie Bishops Druck nachgeben. Was kannst du mir noch über die Bishops erzählen?}
{474}{}{Das klingt nach 'ner seltsamen Taktik... ich meine, ist doch viel wahrscheinlicher, daß Vault City anderswo Hilfe sucht... in der NCR, zum Beispiel... bevor sie Bishops Druck nachgeben. Was kannst du mir noch über die Bishops erzählen?}
{475}{}{Kann ich dir noch ein paar Fragen stellen, Vater?}
{476}{}{Sehr interessant, Vater. Danke für das Gespräch.}

# 20.  HOW MANY FINGERS AM I HOLDING UP? (16)
{480}{}{(Starrt deine Hand an.) Sinnas sechs? Oder sinnas drei...}
{481}{}{Sehr gut. Ist beides richtig. Sag mal, ich hab da noch ein paar Fragen...}
{482}{}{Kannst du auch Scheidungen aussprechen?}
{484}{}{Vielleicht komm ich wieder, wenn du nüchtern bist.}

# 21. CAN YOU DO DIVORCES? (7, 9, 10, 13, 20)
{490}{}{Hol's der Teufel, 'türlich kann ich das! Reno war sogar schon vorm Großen Knall die Stadt der Scheidungen. }
{491}{}{Is' das die Torte, von der du dich trennen willst? }
{492}{}{Is' das der Hengst, von dem du dich trennen willst? }
{493}{}{(Sieht einen Moment verwirrt aus, während er euch beide anstarrt. Dann zuckt er mit den Schultern, trinkt.)}
{494}{}{Kannste wetten. Können wir gleich anfangen?}
{495}{}{Vielleicht... ich denk noch darüber nach. Ich könnte aber wiederkommen.}

# 22. YOU BET. CAN WE START NOW? (21)
{500}{}{Tja, sieht so aus, als ob ich mein Gebetbuch mit dem ganzen offissiell'n Kram verlegt hab...}
{501}{}{Vergiß doch das Buch. Hier hast du 'n bißchen Schnaps. Kannst du dir nicht was ausdenken?}
{502}{}{Hier hast du 'n bißchen Alk. Kannst du dir nicht was ausdenken?}
{503}{}{Vergiß doch das Buch. Wenn ich dir 'ne Flasche bringe, kannst du dir dann vielleicht was ausdenken?}
{504}{}{Wenn ich dir 'ne Flasche bringe, kannst du dir dann vielleicht was ausdenken?}
{505}{}{Oh, na gut. Vielleicht findet sich das Buch ja wieder ein.}

# 23. IF I BRING YOU A BOTTLE, CAN YOU JUST MAKE SOMETHING UP? (22)
{510}{}{Tja, das wär nich' richtig... es sei denn, der Alk is' richtich gut.}
{511}{}{Keine Angst. Ich komm wieder.}
{512}{}{Tja, ich kann welchen holen gehen. Aber dann brauch ich erst ein paar Chips.}

# 24. HERE'S SOME HOOCH. CAN YOU JUST MAKE SOMETHING UP? (22)
{520}{}{Klar! Laß mich das hier erst austrinken, das Feuer anheizen... (trinkt beängstigend schnell) ...also gut, kommt hier vor, ihr zwei...}
{521}{}{Tretet näher...}

# 25. NO HOOTCH ON ME, I'M AFRAID (15, 28)
{530}{}{Oh. Also gut. Fragen kostet nichts... also... äh... tut mir leid, wer bist du doch gleich?}
{531}{}{Weißt du, ich könnte dir etwas Alk besorgen, wenn du willst.}

# 26. I COULD GO SNAG SOME, IF YOU WANT (15, 25, 28)
{540}{}{Ja, das is' 'ne gute Idee! Sei dreifach gesssegnet! Äh... ich weiß sufällig einen ORT östlich von hier, beim alten Bahnhof, da verkaufense das Weihwasser, dassich brauch.}
{541}{}{OK. Ich geh was holen. Bin gleich wieder da.}
{542}{}{OK. Ich geh welches holen. Aber ich brauch dafür ein paar Chips.}

# 27. I'LL NEED SOME chipS TO BUT HOOTCH (23, 26)
{550}{}{'Türlich, 'türlich... Chips, Chips... wo hab ich nur die Chips... (Seine Augen fallen auf die Sammelbüchse neben dem Podium.) Ah! Warum hab ich da nich' gleich dran gedacht... Warte 'n Momentchen...}
{551}{}{Warte geduldig, daß er etwas aus der Sammelbüchse nimmt.}
{552}{}{Äh, mach dir nichts draus, Vater. Die Runde geb ich aus.}

# 28.  MAIN QUESTION NODE (18, 19, 33, 34, 35, 36, 37, 40, 41, 42, 43, 44, 45, 46, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57)
{560}{}{(Vater Tully sieht die nun leere Flasche in seiner Hand an.) Sag mal, ich will ja nich'aufdringlich sein, Freund: haste nich' zufällig noch 'ne Flasche von dem edlen Tropfen dabei? Das Ganze macht mich richtig durstig.}

# 29. BROUGHT SOME HOOCH. CAN I TALK TO YOU . . . ? (7, 9, 10)
{570}{}{Vielen herzlichen Dank! (Nimmt 'ne Flasche, trinkt einen Schluck.) Ahhh... tut mir leid... worüber zum Teufel haben wir gerade geredet?}
{571}{}{Äh... naja, also, klar! (Nimmt 'ne Flasche.) Ich rühr das Zeug normalerweise nich' an, weißte... (Nimmt einen tiefen Schluck.) ...ahhhh... ähm, tut mir leid, was hab ich gerade gesagt?}
{572}{}{Äh... verdammt nett von dir! (Nimmt 'ne Flasche.) Ich trink normalerweise nich' so viel, weißte... (Nimmt einen langen Schluck.) Ahhhh... tut mir leid, was hab ich gerade gesagt?}
{573}{}{Du hast gerade über die Familie Bishop geredet.}
{574}{}{Du hast gerade über die Familie Wright geredet.}
{575}{}{Du hast gerade über die Familie Mordino geredet.}
{576}{}{Du hast gerade über die Familie Salvatore geredet.}
{578}{}{Du hast gerade über Richard Wrights Tod geredet.}
{579}{}{Ich komm zurück, wenn du nüchtern bist.}

# 30. TALK TO ME ABOUT FAMILY BISHOP . . . (19, 29, 33, 34, 35)
{590}{}{Äh? Die Bishops, genau... machthungrig, die ganze Sippe, liegt denen im Blut. Es is' nur, der alte John Bishop is' so damit beschäftigt, die Stadt an sich zu reißen, dasser sich nich' um seine Geschäfte zu Hause kümmert...}
{591}{}{Geschäfte zu Hause?}

# 31. OH, WHAT DOES MR. BISHOP SAY IN THE CONFESSIONAL . . . ? (18)
{600}{}{Tja, nich' so viel, aber AUSSERHALB der Beichte hör ich so manches über den alten Bishop. Verschlagener Teufel. Hat 'n eisernen Willen, den hat er... ganz schön hart. Ich glaub, der steckt hinner den Überfäll'n auf Vault City... haste davon gehört?}
{601}{}{Nein.}
{602}{}{Ja.}
{603}{}{Nun mal langsam, Vater. Die Art Gerede könnte dich in dieser Stadt den Kopf kosten...}
{604}{}{Hör mal, vielleicht komm ich wieder, wenn du nüchtern bist.}

# 32. NO/YES/KEEP YOUR VOICE DOWN (31)
{610}{}{(Ignoriert dich.) Siehste, vor 'n paar Monaten schickte der olle Bishop 'ne Karawane nach Vault City und SCHLUG eine Vernunftehe zwischen Vault City und New Reno VOR.}
{611}{}{Haben sie sich geeinigt?}
{612}{}{Und sie haben sich nicht geeinigt?}

# 33. WHAT DOES MRS. BISHOP SAY IN CONFESSIONAL? (18)
{620}{}{Was man so erwarten kann von 'ner vernachlässigten Frau mit 'nem Körper, dessen Kurven Blinde heilen könnten. Hauptsächlich Ehebruch. Ich mein, haste ihren Vorbau GESEHN? Meine Güte!}
{621}{}{Äh... was kannst du mir sonst noch über die Bishops erzählen, Vater?}
{622}{}{Ja, sie hat 'n netten Vorbau. Ich meine... was man so hört. Äh, was kannst du mir sonst noch über die Bishops erzählen, Vater?}
{623}{}{Äh... sie hat nicht zufällig gesagt, mit WEM sie Ehebruch begangen hat, oder, Vater?}
{625}{}{Stimmt. Tja, danke für das Gespräch.}

# 34. OH, WHAT DOES BISHOP'S DAUGHTER SAY IN THE CONFESSIONAL? (18)
{630}{}{Oooh, süüüüße kleine Angela? Kleine Hexe kommt der Sache schon näher! Das Mädchen hat zu viele Hummeln im Hintern. Immer am Rumtreiben, treibt's mit 'nem Helfer ihres Vaters, pumpt sich voll Jet...}
{631}{}{Äh, treibt's mit 'nem Helfer ihres Vaters? Hat sie gesagt, mit wem?}
{632}{}{Jet?}
{633}{}{Klingt ja wie 'ne tolle Familie. Was kannst du mir sonst noch über die Bishops erzählen?}
{634}{}{Ich hab noch ein paar Fragen, Vater...}
{635}{}{Tja, so sind Kinder nun mal. Also, danke für das Gespräch.}

# 35. DID SHE SAY WHO? (33, 34)
{640}{}{Wer? Sicher hatse das erzählt, aber die Liste derer, mit denen sie es NICHT getrieben hat, wär einfacher aufzuzählen. Sie erzählt's jedem, gibt damit an. Sag mal... wie war doch gleich dein Name?}
{641}{}{Äh, nichts... was kannst du mir sonst noch über die Bishops erzählen, Vater?}
{642}{}{Ich? Mönche im Zölibat, so wie ich, haben keine Namen. Sag mal, ich hab da noch ein paar Fragen, Vater...}
{643}{}{Ich? Nonnen im Zölibat, so wie ich, haben keine Namen. Sag mal, ich hab da noch ein paar Fragen, Vater...}
{644}{}{Ich sprech später mit dir, Vater.}

# 36. JET? (34, 48, 49, 50, 56)
{650}{}{Teufelsblut! Verderben! Faule Sekrete direkt vom Busen des Bösen!}
{651}{}{Du magst also kein Jet?}
{652}{}{Äh, ja. Busen des Bösen. Kann ich dir noch ein paar Fragen stellen, Vater?}
{653}{}{Also gut. Ich sprech dich später, Vater.}

# 37. SO . . . YOU DON'T LIKE JET? (36)
{660}{}{Das Jet bringt uns noch mal alle um. Kann mir kein anderes Zeugs vorstellen...(Trinkt, stößt auf.)...das mehr Schaden anrichtet als Jet... Tötet Körper und Geist. Diese elenden Mordinos...}
{661}{}{Was war das mit den Mordinos?}
{663}{}{Äh, ich würd mir die Flasche das nächste Mal ein bißchen länger aufheben, Vater. Ich sprech dich später.}

# 38. TALK TO ME ABOUT FAMILY WRIGHT (29)
{670}{}{Hä-hä! Wright, was? (Lächelt, wackelt mit den Augenbrauen.) Laß mich dir ein wenig über die WRIGHTS erzählen... das is' 'ne zweischneidige Angelegenheit - 'ne Bande gieriger Trunkenbolde und strenger Puritaner!}
{671}{}{Ach, wirklich?}
{672}{}{Ich glaub, ich hab genug gehört, Vater. Danke für das Gespräch.}

# 39. FAMILY WRIGHT, 2 (38, 40, 41, 42, 43)
{680}{}{Bei den Wrights kommen die Kinder raus wie am Fließband... der olle Orville Wright will wohl die Welt wieder be-völ-kern. Ich hoffe nur, daß Mrs. Wright der Belastung standhält. Hä-hä. Und die Sachen, die die so in der Beichte SAGEN...}
{681}{}{Ach, tatsächlich? Was sagt denn Mrs. Wright so in der Beichte?}
{682}{}{Ach, tatsächlich? Was sagt denn der olle ORVILLE Wright so in der Beichte?}
{683}{}{Was kontrolliert die Wright-Familie in New Reno?}
{684}{}{Oh, ich wette, das ist spannend. Vielleicht können wir uns ja ein anderes Mal darüber unterhalten.}


# 40. OH, WHAT DOES MISSUS WRIGHT SAY IN THE CONFESSIONAL? (39, 42)
{690}{}{ETHYL Wright? Die gute Frau! Hält mich dem Alkohol fern und auf'm geraden und beschwerlichen Weg. (Nimmt einen Schluck.) Die kann dir die Sünde austreiben, kann die... zum Teufel, wovon hab ich grad geredet?}
{691}{}{Von Mrs. Wright in der Beichte...}
{692}{}{Du hast gerade über die Wright-Familie gesprochen...}
{693}{}{Vergiß es. Ich hab noch ein paar Fragen...}
{694}{}{Nichts groß, glaub ich. Danke für das Gespräch.}

# 41. ABOUT MISSUS WRIGHT IN THE CONFESSIONAL? (40)
{700}{}{Oh, richtig, richtig. Tja, äh, in der Beichte hat sie nich' viel zu erzähl'n. Hauptsächlich Schuldgefühle, wenn sie Käfer zertreten hat... oder, daß ihr die Liebe mit ihrem Mann zu viel Spaß macht. Hä-hä. (Nimmt einen Schluck.) Ich liiiebe Schuld.}
{701}{}{Ich hab da noch ein paar Fragen über die Wrights...}
{702}{}{Ach so. Ich hab da noch ein paar andere Fragen...}
{703}{}{Man sieht's. Danke für das Gespräch.}

# 42. WHAT DOES MR. WRIGHT IN THE CONFESSIONAL? (39, 43)
{710}{}{Der olle Orville? Tja, der hat 'ne Menge Schuld auf seinen Schultern lasten. Verstehste, er hat seiner Frau versprochen, aus'm Akoholgeschäft auszusteigen, aber er hat 'ne geheime Brennerei im Bahnhof hinterm Haus! Wenn sie das rausfindet, schlägt sie ihn grün und blau...}
{711}{}{Hä-hä, jetzt kommt der witzige Teil... verstehste, der olle Wright hat seiner Frau versprochen, aus'm Akoholgeschäft auszusteigen, aber er hat 'ne geheime Brennerei im Bahnhof hinterm Haus! Wenn sie das rausfindet, schlägt sie ihn grün und blau...}
{712}{}{Erzähl mir über Mrs. Wright...}
{713}{}{Erzähl mir mehr über die Wrights...}
{715}{}{Eine geheime Brennerei im Bahnhof hinterm Haus, was? Sehr interessant, Vater. Danke für die Info.}

# 43. WHAT DO THE WRIGHTS CONTROL? (39)
{720}{}{Nix! (Nimmt einen Schluck.) Das ist die schwächste Familie, weil sie nur Alkohol brau'n. Damit machen die kaum 'nen Pfennig. Die anderen Familien kaufen ihnen den Al-lohol hauptsächlich aus Mitleid ab.}
{721}{}{Woher kommt denn dieser Alkohol?}
{722}{}{Interessant. Erzähl mir mehr über die Wrights...}
{724}{}{Sehr interessant, Vater. Danke für die Info.}

# 44. TALK TO ME ABOUT FAMILY MORDINO (29, 37)
{730}{}{Die Mordinos? (Hält drei Finger hoch.) Da gibt's zwei von. (Hält die Hand hoch.) Big Jeesus... (Hält die Hand niedrig.) ...un' Little Jeesus. Vater und Sohn. Die kontrolliern das Jet und die Frauen in Reno.}
{731}{}{Erzähl mir was über Big Jesus.}
{732}{}{Erzähl mir was über Little Jesus.}
{733}{}{Sie sind also die Jet-Quelle und kontrollieren die meisten Nutten in New Reno?}

# 45. TELL ME ABOUT BIG JESUS (44, 46)
{740}{}{Jesus? Ganz schlimmer Bursche... (Nimmt einen Schluck, spült damit die Backen aus.) Handelt mit Sklaven, Jet und Nutten. Der einzige, der noch schlimmer is', is' sein dreckiger kleiner Sohn.}
{741}{}{Sein Sohn?}
{742}{}{Jesus Mordino Senior kontrolliert also das Jet und die Nutten in New Reno?}
{743}{}{Tolle Familie. Kann ich dir noch ein paar Fragen stellen, Vater?}
{744}{}{Wie der Vater, so der Sohn. Tja, danke für das Gespräch, Vater.}

# 46. TELL ME ABOUT LITTLE JESUS (44, 45)
{750}{}{Little Jesus? Mistkerl! Der is' wie 'n Präriefloh, saugt Blut aus der Arbeit seines Vaters. Wenn der erst übernimmt, wird das 'ne böse Sache für ganz Reno. Das könnt der nich' zusammenhalten, Jet, Nutten... würd alles zusammenfallen.}
{752}{}{Die Mordinos sind die Quelle des Jets und der meisten Nutten in New Reno?}
{754}{}{Genau wie du in ein paar Minuten. Tja, danke für das Gespräch.}

# 47. MORDINO BUSINESS (44, 45, 46)
{760}{}{(Tully starrt dich an.) }
{761}{}{Jaaa... (Lächelt, leckt sich die Lippen.) ...Huhhrennn... (Beginnt, den Flaschenhals zu streicheln.)}
{762}{}{Äh, Vater? Und das Jet?}
{763}{}{Ich glaub, ich geh dann lieber. Danke für das Gespräch, Vater.}

# 48. DRUGS? (47)
{770}{}{Äh? Jet... äh... ja... Dreckiges Jet. Die machen damit schreckliche Sachen, schrecklich... Redding... die Ställe. (Nimmt einen Schluck.) Alles für Gold...}
{772}{}{Was ist mit Redding?}
{773}{}{Was ist mit den Ställen?}
{775}{}{Interessant. Danke für das Gespräch, Vater.}

# 49. REDDING? (48, 50)
{780}{}{(Macht eine Gehbewegung mit zwei Fingern.) Jet aus der Stadt raus, nach Redding. Gold aus Redding raus, zu den Mordinos. (Nimmt einen Schluck.) Bergarbeiter sterben, Mordinos lügen.}
{782}{}{Was hast du über die Ställe gesagt?}
{784}{}{Die Mordinos verkaufen also Jet an Redding, was? Interessant. Danke, Vater.}

# 50. STABLES? (48, 49)
{790}{}{Mordinos haben 'ne... Farm... außerhalb der Stadt. Halten da Sklaven. Testen... Jet... an ihnen. Bringt sie massenweise um. (Schaudert.) Nur die Mordinos wissen, wo die Ställe sind.}
{792}{}{Was hast du gerade über Redding gesagt?}
{794}{}{Die Mordinos testen Jet an Sklaven, was? Interessant. Danke, Vater.}

# 51. TALK TO ME ABOUT FAMILY SALVATORE (29)
{800}{}{Ich hab über die Salvatores geredet? (Blinzelt, zuckt mit den Schultern, trinkt.) Kann mir nich' vorstell'n, was ich gesagt hab. Die Familie is' still wie der Tod. Und du willst ihnen auch nich' gerade begegnen... weißte warum?}
{803}{}{Im Moment ist mir das eigentlich egal, Vater. Kann ich dir noch ein paar Fragen stellen?}
{804}{}{Hör mal, vielleicht komm ich wieder, wenn du nüchtern bist.}

# 52. [YES/NO] SALVATORE (51)
{810}{}{(Lallt betrunken weiter.) Weil sie Waffen ham, wie Feuer vom Himmel, Waffen, wie sie noch niemand in New Reno oder sonstwo GESEHN hat. Schießen Lichtblitsse, schneiden 'n Mann in zwei Hälften, lassen ihn im Staub zuckend liegen.}
{811}{}{Schießen Lichtblitze?}
{812}{}{Schießen Lichtblitze? Du meinst Laserwaffen?}
{814}{}{Wow... vielleicht sollte ich mal versuchen, an so ein Ding zu kommen. Tja, danke für das Gespräch.}

# 53. LASERS (52)
{820}{}{So nennt man sie glaub ich... La-ser... aber für mich sind's die Waffen des Teufels, faule Lichtwerfer, Werkzeuge, die nur den Tod bringen sollen!}
{821}{}{Ja, natürlich, Vater. Werkzeuge des Teufels und das alles. Was denken denn die anderen Familien so über diese "Lichtwerfer"?}
{823}{}{Werkzeuge des Teufels, was? Vielleicht sollte ich mal versuchen, an so ein Ding zu kommen. Tja, danke für das Gespräch.}

# 54. TELL ME MORE ABOUT THE SALVATORES (52, 53)
{830}{}{Einer dieser Lichtwerfer kann ein Dutzend Männer töten... Andere Familien ham früher mit den Salvatores gekämpft, aber jetzt legt sich niemand mehr mit ihn'n an. Is' so 'ne Art Frieden... gut, solang's anhält, denk ich.}
{831}{}{Wer hat denn bei den Salvatores das Sagen, Vater?}
{833}{}{Wahrscheinlich. Tja, danke für das Gespräch, Vater.}

# 55. WHO'S IN CHARGE? (54)
{840}{}{Louie... LOUIS... Salvatore hat das Sagen. (Leert die Flasche, hustet etwas.) Krüppel. Braucht 'n Sauerstoffgerät zum Atmen... seine Lungen sind im Eimer. Bleibt immer im Obergeschoß von seinem Laden, kommt nie runter.}
{841}{}{Interessant. Kann ich dir noch ein paar Fragen stellen, Vater?}
{842}{}{Hmmmm. Ein Sauerstoffgerät, was? Interessant. Tja, danke für das Gespräch, Vater.}

# 56. TELL ME ABOUT RICHARD . . . (29)
{850}{}{Der arme Junge... Jet hat ihn seiner Familie entrissen, jawohl. Teufelszeug! Das schlimmste Gift für'n Kopf, dasses je gab...}
{852}{}{Weißt du, woher Richard das Jet hatte, das ihn umgebracht hat?}
{853}{}{Ich hab da noch ein paar Fragen...}
{854}{}{Ach so. Tja, danke für das Gespräch, Vater.}

# 57. WHERE RICHARD GOT THE JET . . . (56)
{860}{}{Er kann es von jedem in New Reno gehabt ham! Da gibt's 'ne Apotheke gleich über die Straße, die wird von 'nem Jet-Händler betrieben und wenn der keins verkauft, kannste du jeden auf der Straße fragen! Verdammtes Jet!}
{862}{}{Die Apotheke über die Straße? Seh ich mir mal an. Danke für das Gespräch, Vater.}

# 101. FLOAT TEXT FOR DIVORCE (WTG?)
{957}{}{Also gut, höhhr zu...}
{958}{}{::Nimmt einen Schluck::}
{959}{}{::Trinkt weiter, leert die Flasche::}
{960}{}{...kraft des mir verziehenen Amtes erkläre ich euch zu geschiedenen Leuten.}
{961}{}{Du darfst die Braut jetzt treten. Den Bräutigam. Wie auch immer.}
{962}{}{::Macht eine wegwischende Bewegung::}
{963}{}{Ughhhhh}
{964}{}{Sssssschnarrrrrchhhhh}

# 102. CLICK TEXT AFTER TULLY HAS PASSED OUT (WTG)
{967}{}{Sssssschnarrrrrchhhhh}
{968}{}{Oh, nich... Mrs. Wright, nein... sznnzzzz}
{969}{}{Ssssstopp, Mrs. Wright, ich bin 'n Mann der Kirche}
{970}{}{Verderbtheit... Sünde... zzzz... so viel Schpaßsss}
{971}{}{Klar bin ich nüchtahn gebliem}

# 103. Going to go pass out
{1000}{}{Oh Gott segne dich mein... *RÜLPS*}
{1001}{}{Zuviel getrunken... von diesem Blut... OH HIMMEL, *RÜLLLLLPS*.}
{1002}{}{Oh Gott *RÜLPSSS*}
{1003}{}{Oh Jesus, Maria und Josef, ich trink nie mehr so viel.}
{1004}{}{Ich steh morgen lieber früh auf und geh zur Beichte.}
{1005}{}{Vielleicht leg ich mich einfach 'ne Weile hin.}

#killap - expansion pack
{2000}{}{Ich muss sagen, Vater, New Reno ist nicht gerade der erste Ort, wo ich erwarten würde einen Prediger zu finden.}
{2001}{}{Wo gibts 'n schöneren Ort? Aussserdem, so sicher wie das Amen in der Kirche, hätt'ns mich nich mehr lang in'm verdamdn Abbey geduldet. Bah! Lass s' ihr friedlisches, faades Kloster b'haltn. Wer brauchts? Hah? Ich nich! Aber weißte was? Diese Mönche können echt guten Alk machen. Oh Mann, denn besten Al-lohol auf Gottes Erde. (Er leckt sich die Lippen.) D'alte Samuel und ich, wir hatt'n ne Menge Spasss mit dem Alk, ich sag's dir.}
{2002}{}{Alkohol in einem Kloster. Interessant, ich glaube diesen Ort muss ich einmal besuchen. Kannst du mir den Standort auf meiner Landkarte zeigen?}
{2003}{}{In Ordnung, wenn ich dein besoffenes Geschwafel richtig verstehe, dann kommst du von einer Art Kloster, wo du mit einem Kerl namens Samuel jede Menge gesoffen hast. Vater, wenn du mir diesen Ort auf meiner Karte zeigst, dann kann ich vielleicht deinen Freund besuchen und etwas von dem Alkohol, von dem du so begeistert bist, probieren.}
{2004}{}{(Du nimmst deinen PIPBoy raus und hältst ihn Pfarrer Tully hin, damit er dir die Koordinaten auf der Karte zeigt. Zuerst deutet er auf den Ozean, dann auf irgendeinen Gebirgszug im Süden. Nachdem er dir dann fast das Auge ausgestochen hat, platziert er endlich seinen Finger an der Nordostecke der Landkarte.) Jaah, da is 's Kloster.}
{2005}{}{Vielen Dank Vater. Ich habe aber noch ein paar Fragen...}
{2006}{}{Danke. Aber eines möchte ich noch wissen, warum hast du Abbey verlassen?}
{2007}{}{Danke Vater. Ich muss jetzt gehen.}
{2008}{}{Naja, das isch laaaang her. Ich hab das noch nich alles auf d' Reihe bracht. Das war bevor d' Engel Mrs. Wright mich wieder auf 'n rechten Weg brachte. Tja schau, d' Mönche war'n nich sehr erfreut über meine wüssnn Manier'n. Ich un' Bruder Samuel, wir war'n manchmal ssiemlich verrückt. Hehe, einmal Nachts, schlichen Sammy un' ich ssu'n schlafenden Mönchen, un' tauch'n ihre Hände in Schüsseln mit warmen Wasser. Sogar beim Abt! Ha! Das war'n noch Zeiten, ich sag's dir.}
{2009}{}{Das ist ziemlich kindisch Vater. Ich denke, sie haben dich wahrscheinlich rausgeworfen.}
{20091}{}{Hah! Das ist klassisch. Ich zog den gleichen Streich mit meinem Neffen Feargus durch, und als er aufwachte und dachte er hat sich angepisst, begann er zu heulen — es war großartig. Wie auch immer, haben sie dich am Ende rausgeschmissen?}
{2010}{}{Richtig. Ich hab genug von diesen Amateur Saufgeschichten. Man sieht sich Vater.}
{2011}{}{Ich meinn'nich dass s' misch *rausgeworfen* ham... aber sie wollt'n mich dooodsicher nich mehr in ihrer Nähe ham - nich nach d' Nacht, als ich Ohnmächtig wurd' un' unabsich-lich eins von d' Bücherregale abgefackelt hab. Mann, du hättest 's Gesicht vom Abt sehen soll'n... wenn er 'n bischschen mehr Rügg-grat g'habt hätt, hätt er mich s-sicher auf-hängt. Ha! Drum bin ich abghaun, und auf nimmerwiedersehn! Ssicher, der suuper Fus'l fehlt mir sssiemlich. Un' Samuel, es wär' schön zu wiss'n wie's 'm alten Knabn jetz geht.}
{2012}{}{Ich bin ziemlich viel unterwegs, wenn mich meine Reisen wieder nach Abbey führen, sehe ich vielleicht nach deinem Freund Samuel. Mann, vielleicht bringe ich dir sogar etwas von diesem Fusel.}
{2013}{}{Ahh, könnsch'de, biitte? Das würd mich glücklicher mach'n als 'ne gesunde Reno Hure. Danke Freund.}
{2014}{}{Kein Problem. Ich habe aber noch ein paar andere Fragen...}
{2015}{}{Sicher. Man sieht sich.}
{2016}{}{Ich reise viel umher, wenn ich also wieder nach Abbey komme, kann ich dir vielleicht ein paar Flaschen mitbringen.}
{2017}{}{Interessant. Man sieht sich.}

{2020}{}{Abbey, hm? Da war ich schon einmal. Tatsächlich habe ich dort einen gewissen Samuel getroffen, der sich fast genauso wie du benommen hat.}
{2021}{}{Samuel!? Ha! Wie gehts dem Kerl? Issn paar Jahre her, dass ich 'n gesehn hab. Er säuft noch immer, oder?}
{2022}{}{Ja, er riecht genauso streng nach Alkohol wie du.}
{3022}{}{Um ehrlich zu sein, er ist tot.}
{2023}{}{Ah, das is' gut. Gut zu hören, dasser Ok is'. Wenn du ihn wieder siehst, sag ihm Hallo von mir. Also... (Er klatscht die Hände zusammen und reibt sie begierig.) Nun, has'du auch was von'm berühmten Schnaps mitgenommen, als du dort warst?}
{2024}{}{Ja, ich hab hier was davon.}
{2025}{}{Hab ich, hab ihn aber schon getrunken. Wow das ist echt hartes Zeug.}
{2026}{}{Nein, hab ich nicht.}
{2027}{}{Kein Grund mir's unner d' Nase zu reib'n. Is lange her, seit ich sowas hatte... Ich hätte wirklich gern ein, zwei Flaschen davon. Wäre es möglich, dass du nochmal in Abbey vorbeischaust?}
{2028}{}{Das is sehr schade. Is lange her, seit ich was davon hatte. Ich hätte gern ein, zwei Flaschen davon. Wäre es möglich, dass du nochmal in Abbey vorbeischaust?}
{2029}{}{Is schon lange her, dass ich davon was hatte. Willst du mit mir teilen?}
{2030}{}{Wir werden sehen. Falls ich wieder vorbeikomme, werde ich versuchen daran zu denken, dir etwas mitzunehmen. Man sieht sich Vater.}
{2031}{}{Wahrscheinlich nicht. Also dann, ich muss gehen.}
{2032}{}{Vielleicht. Ich werde für dich ein paar mitnehmen, wenn ich wieder dort vorbeikomme. Ich hätte aber noch ein paar Fragen...}
{2033}{}{Sicher. Hier hast du.}
{2034}{}{Ich denke eigentlich, dass ich sie noch behalte. Ich muß weiter. Tschüss.}
{2035}{}{Sicher. Für einen guten Preis versteht sich.}
{2036}{}{(Vater Tully reißt dir die Flasche aus der Hand und nimmt einen großen Schluck.) Oh jaah, genau so wie ich's in Erinnerung hab. (Er nimmt noch ein paar Schluck, er winkt dir schwach zu und wankt dann ins Hinterzimmer. Du hörst erst ein Ächzen und dann ein Plumpsgeräusch.)}
{2037}{}{(Vater Tully öffnet die Sammelbüchse, nimmt eine Handvoll Chips heraus und gibt sie dir. Du nickst und gibst ihm die Flasche. Er reißt sie dir aus der Hand und nimmt einen großen Schluck.) Oh jaah, genau so wie ichs in Erinnerung hab. (Er nimmt noch ein paar Schluck, er winkt dir schwach zu und wankt dann ins Hinterzimmer. Du hörst erst ein Ächzen und dann ein Plumpsgeräusch.)}
 
{2040}{}{Abbey, hm? Da war ich schon einmal, aber ich kann mich nicht erinnern, dass ich da einem Samuel begegnet bin.}
{2041}{}{Er is'n guter Kumpel. Wenn du ihm wieder mal über 'n Weg läufst, lass ihn wiss'n dassich 'n schönes Leben in New Reno hab. Ich hab ihn nich'mehr gesehen seit ich Abbey verlass'n hab.}
{2042}{}{Sicher. Aber eines würde mich noch interessieren, wieso hast du Abbey verlassen?}

{2045}{}{Wirklich? Das ist so schade. Er warn guter Kumpel. Ich werde ihn vermissen.}
{2046}{}{Ja. Ich habe aber noch ein paar andere Fragen...}
{2047}{}{Ich war noch nie ein guter Trauergast. Man sieht sich.}

{2050}{}{Es würde mich interessieren, warum du die Abbey verlassen hast?}

{2060}{}{Ich habe mit Bruder Samuel gesprochen. Er trinkt sich immer noch das Hirn weg.}
{2061}{}{Ich hab eine Flasche von dem berühmten Schnaps aus Abbey.}
{2062}{}{Hehe, guter oller Sam. Das is' gut ssu wiss'n. Irgen'wann sollt'ich mal versuchen wieder hin ssugeh'n.}
{2063}{}{Gut, man sieht sich wieder Vater.}
{2064}{}{Ich habe auch noch ne Flasche von dem berühmten Schnaps aus Abbey den du wolltest.}
{2065}{}{Hehe, guter oller Sam. Das is' gut ssu wiss'n. Irgen'wann sollt'ich mal versuchen wieder hin ssugeh'n.}

{3000}{}{Du hast sowohl Vater Tully als auch Bruder Samuel über den Verbleib des anderen aufgeklärt.}
{3001}{}{Du hast eine Flasche des berühmten Schnapses aus Abbey zu Vater Tully gebracht.}
