{100}{}{Du siehst Louis Salvatore.}
{150}{}{Du siehst einen älteren, gut gekleideten Gentleman. Er trägt ein Sauerstoffgerät und scheint nur schwer atmen zu können.}
{151}{}{Du siehst Louis Salvatore. Er trägt ein Sauerstoffgerät und scheint nur schwer atmen zu können.}
{200}{}{*Hust*}
{201}{}{::euch::}
{202}{}{*Hust* *Hust*}
{210}{}{Wachen! Wa...*Hust* *Hust*...Wachen!}
{215}{}{(Salvatore dreht sich mit steinerner Mine zu dir um. Er betrachtet dich den Bruchteil einer Sekunde, dann macht er eine seltsame Bewegung mit der Hand. Sofort geht ein Alarm im Kasino los.)}
{216}{}{Auuuhh! Leiser stellen! Tut Ohren weh! TUT OHREN WEH!}
{217}{}{KANN NICHT BEI KLINGELN SPRECHEN. ABSTELLEN, DANN REDEN}
{218}{}{Ich werd dich jetzt zum KRÜPPEL machen, Alter! Du wirst nie wieder gehen können!}
{219}{}{Ich weiß, dass ich erst um Erlaubnis hätte bitten müssen...}
{220}{}{Mist!}
{221}{}{Äh, sag mir bitte, dass das der Zimmerservice war.}
{230}{}{(Der ältere Mann sieht zu dir auf. Sein Gesicht ist abgezehrt und voller Leberflecken. Er hält eine Atemmaske in der Hand, die an ein Sauerstoffgerät neben ihm angeschlossen ist.) Was...willst du von mir?}
{231}{}{Ich wollen...weiß nicht, was wollen}
{232}{}{Ich wollen}
{233}{}{Ich }
{234}{}{[[Verschwinde]]}
{235}{}{Ich habe Informationen für dich.}
{236}{}{Ich habe Informationen, Mr. Salvatore.}
{237}{}{Ich suche Arbeit.}
{238}{}{Die Charakterstärke und Fairneß von Mr. Salvatore sind überall bekannt. Ich möchte für dich arbeiten.}
{239}{}{Ich wollte wissen, woher die Lichtwerfer stammen.}
{240}{}{Es heißt, dass du den Sohn von Mr. Wright hast vergiften lassen. Warum?}
{241}{}{Ich bin glaube ich im falschen Zimmer. Entschuldigung.}
{250}{}{Ich hab dir erzählt, warum der Junge umgebracht wurde. Das wird niemals aus diesem Zimmer dringen. (Salvatore macht eine seltsame Bewegung mit der Hand. Sofort geht ein Alarm im Kasino los.)}
{251}{}{(Salvatore betrachtet dich für einen Sekundenbruchteil angeekelt, dann macht er eine seltsame Bewegung mit der Hand. Sofort geht ein Alarm im Kasino los.)}
{254}{}{Ich werd dich jetzt zum KRÜPPEL machen, Alter! Du wirst nie wieder gehen können!}
{270}{}{(Nimmt einen tiefen Zug aus der Maske und schüttelt dann den Kopf.) Du hast nichts...das ich wissen müsste, }
{271}{}{Ähm, ich habe mich ja gar nicht vorgestellt. Woher weißt du, wie ich heiße?}
{272}{}{Äh, OK. Also, ich suche Arbeit.}
{276}{}{Ich scheine wohl in das falsche Zimmer geraten zu sein. Tut mir leid.}
{290}{}{(Sieht dich eine Minute schweigend an. Er ist über deine Frage entweder amüsiert oder verärgert...das ist schwer zu sagen.) Also noch mal, }
{291}{}{Äh...hmmm. Also, äh, ich suche Arbeit.}
{305}{}{(Nimmt einen Zug aus der Atemmaske und lächelt.) Natürlich...suchst du Arbeit. Und WARUM sollte ich dich einstellen?}
{306}{}{Och, warum nicht? Nenn eine Arbeit und ich mach sie. Ich bin fleißig und hab die Fähigkeit, Sachen zu Ende zu bringen.}
{307}{}{He. Hab ich gesagt, dass ich Arbeit suche? Ich wollte eigentlich sagen, dass ich jetzt gehe.}
{315}{}{(Nimmt einen Zug aus der Atemmaske und lächelt.) Natürlich...Aber ich verlange einen Beweis...für deine Loyalität. Einen Beweis dafür...dass du für uns arbeiten willst.}
{316}{}{Was soll ich denn tun?}
{317}{}{Was soll ich denn tun, Mr. Salvatore? Ich mach's, egal was es ist?}
{325}{}{(Schüttelt leicht den Kopf.) Deine Naivität ist...hier fehl am Platze. Worte reichen da nicht: Du willst für Louis Salvatore arbeiten? Dann muss ich wissen, inwieweit ich mich auf dich verlassen kann.}
{326}{}{Hör mal, du kannst auf mich ZÄHLEN.}
{327}{}{Lass es mich beweisen. Gib mir eine Aufgabe.}
{335}{}{(Nimmt einen tiefen Zug aus der Atemmaske.) Da gibt es einen...Mann...der seine...Fingerfertigkeit mit Karten dazu...verwendet hat, mir eine beträchtliche Summe zu stehlen. Ich will, dass er getötet und das gestohlene Geld zurückgebracht wird.}
{336}{}{Wer ist dieser Dieb?}
{338}{}{Wieviel hat er denn gestohlen?}
{339}{}{Das ist eine schwere Aufgabe: Kann ich dafür eine der Laserwaffen haben, die deine Familie verwendet?}
{340}{}{Äh, ich bin kein Vertragskiller. Ich gehe jetzt.}
{350}{}{Mason kennt die...Einzelheiten. (Nickt zum Ausgang.) Geh jetzt.}
{351}{}{Also gut.}
{352}{}{Danke, Mr. Salvatore. Ich gehe Mason fragen.}
{360}{}{Dann kannst du...mir nicht nützen. Geh jetzt.}
{361}{}{Äh, Moment...ich hab's mir überlegt. Ich mach es doch.}
{362}{}{Verschwinde leise und unauffällig.}
{370}{}{(Verengt die Augen zu Schlitzen. Seine nächsten Worte kommen als stoßweises Zischen.) ::Du hast dich noch nicht BEWIESEN.:: Geh jetzt zu Mason. Er kennt die...Einzelheiten deiner Aufgabe.}
{371}{}{Alles klar. Vergiss die Pistolen erst mal.}
{372}{}{Verstehe, Mr. Salvatore. Entschuldige die Frage. Ich gehe jetzt zu Mason.}
{373}{}{Also: Wenn du mich nicht entsprechend bewaffnest, dann kann ich auch nicht weiter für dich arbeiten.}
{380}{}{Geh jetzt zu Mason. Er kennt die...Einzelheiten deiner Aufgabe.}
{385}{}{(Salvatore sieht zu dir auf und nimmt einen Zug aus der Atemmaske.) Hast...du dich des Diebs entledigt?}
{386}{}{Nee...Lloyd hat die Stadt mit dem Geld verlassen.}
{387}{}{Hab ich. Die Geier sind jetzt wahrscheinlich schon dabei, ihn zu verdauen.}
{388}{}{Noch nicht.}
{389}{}{Nein, Mr. Salvatore. Lloyd hat die Stadt mit dem Geld verlassen.}
{390}{}{Ja. Ich hab an ihm ein Exempel statuiert, Mr. Salvatore.}
{391}{}{Noch nicht, Mr. Salvatore.}
{400}{}{Aber...du hast Mason erzählt, dass du deine Aufgabe abgeschlossen hast.}
{401}{}{Ach so, ja, aber...}
{405}{}{(Legt seine Finger zusammen.) Und...das Geld. Konnte es sichergestellt werden?}
{406}{}{Nein, das Geld konnte ich nicht finden.}
{407}{}{Nein, Lloyd hatte es schon ausgegeben.}
{408}{}{Ja.}
{410}{}{Nein, Mr. Salvatore, das Geld konnte ich nicht finden.}
{411}{}{Nein, Mr. Salvatore, Lloyd hatte es schon ausgegeben.}
{412}{}{Ja, Mr. Salvatore.}
{420}{}{Deine Anweisung lautete darauf, das gestohlene Geld zurückzubringen. Hast du das nicht getan?}
{421}{}{Also, nein, weil --}
{422}{}{Äh, ich habe das Geld --}
{423}{}{Weißt du, ich kann --}
{430}{}{Ich werde das Geld jetzt holen.}
{431}{}{Also, das hab ich jetzt nicht bei mir...}
{432}{}{Gib ihm 250 Chips.}
{433}{}{Gib ihm 500 Chips.}
{434}{}{Gib ihm 750 Chips.}
{435}{}{Gib ihm 1000 Chips.}
{436}{}{Gib ihm 1000 Chips. (Das ist der richtige Betrag.)}
{437}{}{(Unternimm einen Fluchtversuch.)}
{450}{}{Diese Summe...ist nicht die Summe, die mir gestohlen wurde. Vielleicht weißt du nicht, wieviel mir gestohlen wurde. Oder vielleicht versuchst du, mich zu betrügen. Wie dem auch sei...}
{451}{}{Oh, da hab ich mich wohl verzählt...}
{455}{}{(Salvatore nickt, während du ihm das Geld vorzählst. Nach der Hälfte unterbricht er dich.) Die...restliche Hälfte gehört dir.}
{456}{}{Oh, vielen Dank.}
{468}{}{Danke, Mr. Salvatore.}
{475}{}{(Mr. Salvatore nimmt einen Zug aus der Atemmaske.) Ich habe noch eine Sache...um die du dich kümmern müsstest.}
{476}{}{Klar, warum nicht? Was ist es denn - noch was mit Umbringen und Zurückholen?}
{477}{}{Ich bin daran interessiert, Mr. Salvatore. Was soll ich tun?}
{478}{}{Nein, ich will keine Leute mehr umlegen. Ich zieh mich aus diesem Geschäft zurück.}
{479}{}{Keine weiteren Aufträge für mich, Mr. Salvatore. Ich muss jetzt gehen.}
{485}{}{Jemand in meinem ...Distrikt hat mir noch nicht die Abgaben gezahlt, die...ich für meine Dienste fordere. Du sollst das Geld abholen. Wenn er sich wehrt, sagst du ihm, du seist mein...Stellvertreter in dieser Angelegenheit. Mason kennt die Einzelheiten.}
{487}{}{Ja, Mr. Salvatore. Ich geh zu ihm.}
{488}{}{Nein danke, Erpressungen mache ich nicht.}
{495}{}{Du...lügst mich an. Ich weiß, dass er noch lebt.}
{500}{}{Hast du getan, was dir befohlen wurde?}
{501}{}{Ja, Mr. Salvatore, ich habe die Abgabe eingetrieben, wie gewünscht.}
{502}{}{Ja, ich habe die "Abgabe" hier.}
{503}{}{Noch nicht. Ich hab den Alten noch nicht dazu gebracht, es rüberzuschieben.}
{504}{}{Noch nicht, Mr. Salvatore. Wenn ich wiederkomme, habe ich es bei mir.}
{515}{}{Du hast Mason erzählt, du hättest meine Abgabe eingetrieben. Etwa nicht?}
{525}{}{Na gut. (Er wartet.)}
{527}{}{Gib ihm 900 Chips.}
{528}{}{Gib ihm 800 Chips.}
{529}{}{Ich habe das Geld jetzt nicht BEI mir...}
{540}{}{Diese Summe...ist nicht die Summe, die mir gestohlen wurde. Vielleicht weißt du nicht, wie hoch der Betrag ist. Oder vielleicht versuchst du, mich zu betrügen. Wie dem auch sei...}
{545}{}{(Salvatore nickt dir zu, als du ihm das Geld gibst.) Das hast du...gut gemacht. 25% gehören dir.}
{546}{}{(Salvatore nickt dir zu, als du ihm das Geld gibst.) Das hast du...ganz gut gelöst. Du hast dir 10% davon verdient.}
{555}{}{(Nimmt einen Zug aus der Atemmaske.) Du hast...getan, was ich von dir verlangt habe. Ich kann deine Dienste jetzt...nicht mehr brauchen. (Zeigt zum Ausgang.) Geh jetzt.}
{556}{}{Äh...OK.}
{557}{}{Könnte ich als Teilzahlung eine dieser Laserpistolen haben, bevor ich gehe?}
{565}{}{(Nimmt einen tiefen Atemzug aus der Maske.) Ich habe noch eine...Angelegenheit, in der ich deine Hilfe brauchen könnte.}
{566}{}{Klar. Warum nicht? Was ist es denn?}
{568}{}{Nein, Erpressung mache ich nicht. Damit habe ich abgeschlossen.}
{575}{}{Eine...sensible Transaktion soll bald stattfinden. Ich benötige dazu eine zusätzliche...Wache, um sicherzustellen, dass alles glatt geht. Sprich Mason darauf an und tu, was er sagt.}
{576}{}{Was ist das für eine Transaktion?}
{577}{}{Wo findet diese Transaktion statt?}
{578}{}{Kann ich eine von diesen Laserwaffen habe, die sie verwenden?}
{579}{}{Ich kann leider nicht an der Mission teilnehmen, Mr. Salvatore. Ich muss weiter.}
{585}{}{Mason kennt alle...Einzelheiten. Geh jetzt.}
{595}{}{Diesmal ja. Aber du wirst auch noch andere Waffen tragen. Besprich die Einzelheiten mit Mason. Er wird dir auch einen der Lichtwerfer geben.}
{596}{}{Alles klar.}
{605}{}{Setz dich, }
{607}{}{Es wäre eine Ehre für mich, Mr. Salvatore.}
{608}{}{Ich kann nicht. Ich habe noch andere Verpflichtungen. Trotzdem vielen Dank für das Angebot.}
{610}{}{Es wäre eine Ehre für mich, Mr. Salvatore, aber ich kann leider nicht. Ich habe noch Verpflichtungen einer anderen Familie gegenüber...das gilt vor allem für meine Mutter.}
{615}{}{Das ist...sehr schade. Ich kann es nicht riskieren, dass du...kein Stillschweigen bewahrst über das, was du in der Wüste gesehen hast. Auf Wiedersehen, }
{616}{}{He! Moment mal...!}
{617}{}{Ach ja? Nur los damit, dann bring ich ihre gesamte Familie einen nach dem anderen um.}
{620}{}{Schön. Du musst einen Namen auswählen...}
{621}{}{Wie wär's mit...}
{630}{}{(Nickt) Das ist ein...guter Name. Sprich jetzt mit Mason. Er hat etwas für dich.}
{640}{}{Sei gegrüßt, }
{645}{}{Ich benötige deine Dienste nicht mehr, }
{650}{}{...}
{651}{}{...harkkk...}
{652}{}{...*keuch*...ich...*hust*...*röchel*...}
{653}{}{...nein...ich...*harrkkk*}
{654}{}{...Hilfe...*keuch*...bitte...}
{655}{}{...Mitleid...}
{656}{}{*keuch*}
{657}{}{...ich...}
{658}{}{...ich...}
{659}{}{::Hört auf zu atmen.::}
{660}{}{Heh-heh. Ich liebe es, alte Leute umzubringen.}
{675}{}{(Mr. Salvatore sieht dich lange Zeit schweigend an und spricht dann.) Wir Salvatores...wir werden die Herrschaft in New Reno übernehmen. Wenn zur Erreichung dieses Ziels ein Junge sterben muss, wird es...so geschehen. Einen anderen Grund gibt es nicht.}
{676}{}{Was hat denn der Mord an Wrights Sohn mit der Herrschaft in New Reno zu tun? Das ist doch völlig SINNLOS.}
{677}{}{Du hast den SOHN von jemandem umgebracht, Salvatore. Da hättest du genausogut gleich dein Todesurteil unterschreiben können...}
{678}{}{Alles klar. Ich wollte nur wissen, warum du es getan hast.}
{800}{}{Du hast das Oberhaupt der Familie Salvatore ermordet.}
{825}{}{Du hast das Oberhaupt der Familie Salvatore umgelegt.}
{850}{}{Du hast die "Situation" mit Lloyd geklärt.}
{875}{}{Du hast die "Abgabe" für Mr. Salvatore eingetrieben.}
{900}{}{Du bist ein Mitglied der Familie Salvatore geworden.}
{925}{}{Du hast die geheime Transaktion erfolgreich abgeschlossen.}
{5233}{}{! Wer du}
{5270}{}{. Also...was WILLST du von mir?}
{5290}{}{: Was...WILLST du von mir?}
{5605}{}{. Du hast...alles erledigt, um das ich dich gebeten habe. Ich würde dich gern in die Familie Salvatore aufnehmen, damit du einer...meiner Männer wirst.}
{5640}{}{.}
{5645}{}{.}
