{100}{}{Du siehst...Sheb.}

{150}{}{Du siehst einen mageren Mann in leuchtend blauer Kleidung. Und als ob seine Kleidung nicht schon schreiend genug wäre, brüllt er auch noch aus Leibeskräften.}

{200}{}{Beute, Beute, Beu-te!}
{201}{}{Nur her mit euch, Beutefreunde!}
{202}{}{Hier im Cat's Paw halbieren wir die Preise!}
{203}{}{Macht uns ein Angebot für unsere erstklassige Beuteauswahl! Alles muß raus hier!}
{204}{}{Wir haben weiße Beute, schwarze Beute, Beute aus dem Süden, Beute aus dem Norden...}
{205}{}{Wir haben heiße Beute, kalte Beute, frische Beute, wir haben...::schnüff::...*stinkige* Beute...}
{206}{}{Wir haben Stammesbeute, Mutantenbeute, Radskorpionbeute, Roboterbeute.}
{207}{}{Wir haben sogar Brahminbeute, Ghulbeute und Deathclawbeute.}
{208}{}{Los jetzt, wollt ihr Beute? Nur herein, Beutefreunde!}
{209}{}{Wenn wir's nicht haben, wollt ihr es auch nicht! Nur herein, Beutefreunde!}
{210}{}{Beutekäufer aufgepaßt! Nutzt unseren Beuteausverkauf!}
{211}{}{Kauft ein Beutestück zum regulären Preis, dann gibt's noch ein Beutestück der gleichen oder einer niedrigeren Preiskategorie für nur einen Chip!}
{212}{}{Kauft Beute für nur einen Chip!}
{213}{}{Wenn ihr irgendwo billigere Beute findet...SEID IHR GUT!}
