{100}{}{Du siehst einen kleinen Mann mit einem Buch in den Händen.}
{101}{}{Du siehst Joseph, den Kräutersammler.}
{102}{}{Du siehst einen kleinen Mann mit einem Buch, das den Titel "Kräuter und ihre heilende Wirkung" trägt.}
{103}{}{Hallo, ich bin Joseph, der Kräutersammler. Womit kann ich dienen?}
{104}{}{Hab Aua. Du helfen?}
{105}{}{Fühl schlecht. Du helfen?}
{106}{}{Ich lahm, du helfen?}
{107}{}{Hab Fragen. OK?}
{108}{}{Tut leid. Ich gehn.}
{109}{}{Ich bin verletzt, kannst du mir helfen?}
{110}{}{Ich fühl mich elend, kannst du mir helfen?}
{111}{}{Ich bin verstümmelt, kannst du mir helfen?}
{112}{}{Ich möchte dich was fragen.}
{113}{}{Ich wollte nur mal Hallo sagen.}
{114}{}{Aber sicher. Hmmm. Nimm was hiervon. Ich trage diesen Balsam auf die Wunde auf. Und jetzt leg dich hin und ruh dich für einige Stunden aus.}
{115}{}{Danke. Wieder-sehn.}
{116}{}{Danke Doc. Ich fühl mich schon viel besser.}
{117}{}{Klar, sicher. Hmmm. Das wird 'ne Weile dauern. Du mußt über Nacht bleiben. Trink das — alles. Ich weiß, daß es schrecklich schmeckt. Und jetzt leg dich hin. Ich weck dich morgen früh.}
{118}{}{Ich fühlen gut. Tschüß.}
{119}{}{Danke, das hat geholfen.}
{120}{}{Tut mir leid, aber ich bin kein Mediziner und ich kann keine Operation durchführen. Ich schlag vor, du gehst in eine der größeren Städte und suchst einen Chirurgen auf. Versuch's mal in der New California Republic. Das ist östlich von hier.}
{121}{}{OK. Wiedersehn.}
{122}{}{Na gut. Danke trotzdem.}
{123}{}{Was möchtest du wissen?}
{124}{}{Du Gefangener?}
{125}{}{Du gehn hier wenn wollen?}
{126}{}{Was wissen über Todkrallen?}
{127}{}{Wie du kommen her?}
{128}{}{Ich gehn.}
{129}{}{Bist du ein Gefangener?}
{130}{}{Kannst du gehn, wenn du willst?}
{131}{}{Was kannst du mir über die Deathclaws sagen?}
{132}{}{Wie bist du hier her gekommen?}
{133}{}{Danke für die Informationen; ich geh jetzt los.}
{134}{}{Nein, ich bin kein Gefangener. Ich bleib, weil ich hier gebraucht werde. Ich hab mich damit abgefunden, daß einige meiner Patienten Deathclaws sind.}
{135}{}{OK. Muß mehr wissen.}
{136}{}{Danke. Tschüß.}
{137}{}{Das ist sehr lobenswert von dir.}
{138}{}{Verstehe.}
{139}{}{Das kann ich nicht ganz nachvollziehen, aber es ist ja dein Leben.}
{140}{}{Ja, das kann ich und ich tu es oft. Ich muß von Zeit zu Zeit Kräuter sammeln und ich wurde noch nie behindert. Ich hab mich immer gefragt, ob die Deathclaws mir heimlich folgen und ob sie mich aufhalten würden, wenn ich versuchen würde zu fliehen. Also hab ich eines Tages die Probe aufs Exempel gemacht.}
{141}{}{Ich verstehn. Jetzt gehn.}
{142}{}{Ich noch Fragen.}
{143}{}{Du bist ein unnötiges Risiko eingegangen und hattest Glück, daß es geklappt hat.}
{144}{}{Alles klar.}
{145}{}{Gute Idee. Gut, daß es funktioniert hat.}
{146}{}{Laß mich mal sehn... Deathclaws scheinen mutierte Jackson-Chamäleons zu sein - von der gehörnten Art. Viele Ähnlichkeiten, sind noch deutlich zu sehen, aber die Unterschiede überwiegen. Der Mutationsfaktor ist ziemlich hoch. Diese Spezies ist hochintelligent. Sie haben etwa den IQ eines Achtjährigen. Einige Exemplare erreichen sogar das normale Intelligenzniveau eines erwachsenen Menschen. Ihre Lernfähigkeit ist sehr hoch und sie verfügen über abstraktes Denkvermögen.}
{147}{}{Oh... du sagen.}
{148}{}{Muß gehn.}
{149}{}{A-ha.}
{150}{}{Wow, ich bin beeindruckt von deinem Wissen.}
{151}{}{Hört sich für mich wie ein Haufen Blödsinn an.}
{152}{}{Ich war eines Abends dabei, einige Kräuter zu sammeln, als eine Stimme aus der Dunkelheit rief: 'Ich hab dich beobachtet und ich weiß, daß du ein Heiler bist. Hast du dich deiner Kunst so sehr verschrieben, daß du auch eine fremde Kreatur heilen würdest? Jemanden, den viele als Feind bezeichnen würden?'}
{153}{}{Ugh.}
{154}{}{Danke. Ich wohl gehn.}
{155}{}{Was für eine Verschwendung - du könntest anderswo so vielen anderen helfen.}
{156}{}{Du bist wahrlich ein engagierter Mann, der Anerkennung verdient.}
{157}{}{Interessant.}
{158}{}{Jemandem wie dir werde ich bestimmt nicht helfen. Verschwinde.}

{159}{}{Ich bin in eine andere Stadt gereist und bin dort für eine Woche oder so geblieben und kam dann zurück. Als ich ankam, wurde ich freundlich empfangen. Gruthar, der Rudelsführer, kam persönlich und dankte mir, daß ich zurückgekommen war. Nein, ich bin auf jeden Fall aus freien Stücken hier.}

{160}{}{Obwohl sie keine Stimmbänder haben, scheinen die Deathclaws die menschliche Sprache fast wie ein Papagei nachzuahmen. Ich habe noch nicht herausgefunden, wie das genau funktioniert. Mehr kann ich also noch nicht sagen. Sozial gesehen, sind sie Rudeltiere mit einem sehr strikten Verhaltenscode. Sie werden von einem 'Alpha-Männchen' geführt, das vom gesamten Rudel bestimmt wird. Sie sind extrem loyal, was das Rudel insgesamt angeht. Sie sehen es als eine große Sippe und haben nicht wie die Menschen mehrere kleine Familien.}
{161}{}{Ihr Sinn für Recht und Unrecht ist sehr stark ausgeprägt. Sie folgen einem Verhaltenscode, dessen Einhaltung vom gesamten Rudel gesichert wird. Soweit ich das beurteilen kann, werden Probleme im Rudel nie mit Gewalt gelöst. Ich habe noch nie erlebt, daß ein 'Kapitalverbrechen' begangen wurde, also kann ich nicht sagen, wie sie damit umgehen. Hmmm. Das ist momentan alles, was mir einfällt. Ich hoffe, das hilft dir weiter.}

{162}{}{Ich habe geantwortet, daß ich alles Leben respektiere und mein Bestes geben würde, einen Verletzten zu heilen, unabhängig, wer oder was er ist. Phhh! Ich dachte, es wäre ein Dieb oder Gauner, der verletzt worden war und einen Doktor brauchte. Du kannst dir nicht vorstellen, wie verblüfft ich war, als dann einige Deathclaws mit einem verletzten Artgenossen aus der Dunkelheit kamen. Jemand hatte ihn zusammengeschossen. Ich sagte ihnen, daß ich an Ort und Stelle nichts machen könne. Also verbanden sie mir die Augen und brachten mich hierher. Seitdem bin ich hier.}