{100}{}{Du siehst einen dünnen, nervös wirkenden Mann.}
{101}{}{Du siehst den "Schmerzlosen Doc Johnson", den Arzt von Redding.}
{102}{}{Du siehst einen knochigen, nervösen Typ mit hervorstehenden Augen.}
{103}{}{Dein Kopf ist größer, als ich gedacht hätte.}
{104}{}{Deine zusammengewachsenen Augenbrauen bestätigen meine Vermutung.}
{105}{}{Du hast eine sehr ausgeprägte Sagittalnaht.}
{106}{}{Ich frage mich, ob deine Schädelkapazität durch längere Strahlenaussetzung so reduziert
 wurde.}
{107}{}{Hier gibt's kein Essen. Hau ab!}
{108}{}{Schusch, schusch!}
{109}{}{Geh zurück in die Wildnis, wo du herkommst.}
{110}{}{Wenn die Sippenangehörigen nur so passiv wie Brahmin wären, dann könnten sie auch ebenso
 nützlich sein.}
{111}{}{Siehst so aus, als ob du beim Richtigen gelandet bist. Ich bin Doc Johnson und ich
 flicke dich schon wieder zusammen.}
{112}{}{Hallo, du da, hast du deinen Freund hierher gebracht, damit ich ihn wieder
 zusammenflicke? Ich bin der Schmerzlose Doc Johnson und ich werd mich schon darum kümmern.}
{113}{}{Sieht so aus, als ob ihr irgendwo den kürzeren gezogen hättet. Ich bin Doc Johnson
 und ich kann euch wieder zusammenflicken, wenn ihr wollt.}
{114}{}{Hallo; Ich bin Doc Johnson, und meiner professionellen Meinung nach siehst du nicht so
 ganz gut aus. Soll ich dich wieder hinbiegen?}
{115}{}{Hallo, ich bin Doc Johnson. Ich muß mir deinen Freund etwas genauer anschauen, wenn ich
 das wieder hinbekommen soll. Sieht gar nicht gut aus.}
{116}{}{Was ihr Kerle euch auch eingefangen habt, ich kann das sicher wieder in Ordnung bringen.
 Ich bin Doc Johnson.}
{117}{}{Ziemlich zerschunden, was? Na, laß Doc Johnson mal schauen. Ganz ruhig jetzt. Das ist
 mein Beruf.}
{118}{}{Was habt ihr denn angestellt? Laßt den alten Doc Johnson mal nachschauen.}
{119}{}{Danke, Doc. Wieviel kostet uns das?}
{120}{}{Ich wollte eigentlich nur ein paar Vorräte kaufen.}
{121}{}{Im Moment brauche ich Heilung nicht so dringend wie ein paar Antworten auf meine Fragen.}
{122}{}{Nett, dich zu treffen, aber eine Heilung ist jetzt nicht so dringend. Trotzdem danke,
 Doc. Wiedersehen.}
{123}{}{Das kostet $50 und ich flicke dich so zusammen, daß du so gut wie neu aussiehst.}
{124}{}{Kostet dich $50 um deinen Freund wieder zusammengeflickt zu bekommen. So gut wie neu,
 das garantiere ich.}
{125}{}{Hier ist dein Geld, Doc.}
{126}{}{Das kann ich mir im Moment leider nicht leisten. Tut mir leid, Doc, vielleicht das
 nächste Mal.}
{127}{}{$50, was? Vielleicht lasse ich das später mal machen. Wiedersehen, Doc.}
{128}{}{Ich sag euch was, ich gebe euch Gruppenrabatt, so, wie ihr ausseht. $100 und ich flicke
 euch alle wieder zusammen.}
{129}{}{Hier ist dein Geld, Doc. Dann mal los.}
{130}{}{Das können wir uns, glaub ich, im Moment nicht leisten. Tut mir leid, Doc, vielleicht
 ein anderes Mal.}
{131}{}{$100, was? Vielleicht lassen wir das später mal machen. Wiedersehn, Doc.}
{132}{}{Sieht so aus, als ob es dir nicht allzu gut geht. Ich kann dein Leiden für $100 heilen.
 Willst du, daß ich es mal probiere?}
{133}{}{Deinem Freund geht es aber gar nicht gut. Ich glaube, ich kann sein Leiden für $100
 lindern. Soll ich es mal probieren?}
{134}{}{Ich hoffe, du probierst es nicht nur, Doc. Hier ist dein Geld.}
{135}{}{Das kann ich mir im Moment leider nicht leisten. Tut mir leid, Doc, vielleicht das
 nächste Mal.}
{136}{}{$100, was? Vielleicht lasse ich das später mal machen. Wiedersehen, Doc.}
{137}{}{Was für ein Rudel kranker Welpen. Naja, ich kann versuchen, eure Leiden zu heilen,
 aber das kostet euch $150. Soll ich mich mal dran versuchen?}
{138}{}{Ja, bitte. Hier ist dein Geld, Doc.}
{139}{}{Das können wir uns im Moment nicht leisten. Tut mir leid, Doc, vielleicht ein
 anderes Mal.}
{140}{}{$150, was? Vielleicht lasse ich das später mal machen. Wiedersehen, Doc.}
{141}{}{Ich würde dir wirklich gern helfen, aber du hast nicht genug Geld. Medikamente kosten
 nunmal was.}
{142}{}{Aaach, komm schon, Doc. Wir brauchen deine Hilfe.}
{143}{}{Ich komme wieder, wenn ich mehr Geld habe. Wiedersehn.}
{144}{}{Na gut, OK. Dieses eine Mal tue ich's - aber das nächste Mal hast du besser das Geld
 dabei und bezahlst mich.}
{145}{}{Das hat einmal funktioniert... Wie gesagt, dieses Mal brauche ich das Geld. In dieser
 Welt ist nichts umsonst - das schließt auch mich nicht aus.}
{146}{}{Danke, Doc. Ich weiß das wirklich zu schätzen. Das nächste Mal bringe ich Bares mit.
 Versprochen.}
{147}{}{Ich hab schon ein schlechtes Gewissen, daß ich mich so aufdränge. Ich komme besser
 zurück, wenn ich Geld habe, um dich zu bezahlen.}
{148}{}{OK, tut mir leid. Aber bevor ich gehe, laß mich etwas fragen.}
{149}{}{OK, OK. Ich bin ja schon unterwegs. Wiedersehn, Doc.}
{150}{}{Tut mir leid. Kein Geld, keine Behandlung. Ich kann nicht Medikamente an jeden austeilen,
 der danach fragt. Dann wäre ich innerhalb einer Woche pleite. Komm wieder, wenn du das Geld
 für meine Bezahlung hast.}
{151}{}{Ich hab kein Bargeld, aber dafür hab ich Zeug zum Tauschen. Kann ich nicht irgend etwas
 gegen deine Behandlung eintauschen?}
{152}{}{Bevor ich gehe, laß mich dich noch etwas fragen.}
{153}{}{OK, ich werde versuchen, etwas Geld zusammenzubekommen. Wiedersehn.}
{154}{}{Was möchtest du denn wissen?}
{155}{}{Was denn jetzt noch?}
{156}{}{Ich glaub, ich habe eine Lösung für das Jet-Problem, das du hier hast.}
{157}{}{Ich habe gehört, daß Redding in der letzten Zeit Probleme mit seinen Exporten hatte.}
{158}{}{Ich könnte wirklich ein bißchen Heilung gebrauchen.}
{159}{}{Ich frag mich nur, was in der letzten Zeit so in der Stadt los war.}
{160}{}{Warum nennt man dich den "Schmerzlosen Doc Johnson"?}
{161}{}{Hast du Medikamente zum Tauschen?}
{162}{}{Ich hab mich nur umgesehen. Wiedersehn, Doc.}
{163}{}{Wonach sieht das hier aus? Nach einem Gemischtwarenladen? Nein, ich handele nicht mit
 medizinischen Dienstleistungen. Ich will einfach nur in ehrlichen Golddollars bezahlt werden,
 vielen Dank. Komm zurück, wenn du welche hast.}
{164}{}{Na gut. Ich verstehe schon. Wiedersehn.}
{165}{}{Ich könnte dich vielleicht mit ein paar Medikamenten versorgen, laß mal sehen, was
 du hast.}
{166}{}{OK, Doc.}
{167}{}{Ich meinte doch nicht gleich jetzt. Ich wollte nur wissen, ob du überhaupt etwas hast,
 womit du handeln kannst. Ich hab aber einige Fragen.}
{168}{}{Oh, ich brauche im Moment nichts. Bis später, Doc.}
{169}{}{Hast du alles bekommen, was du brauchst?}
{170}{}{Na, und? Hat's das gebracht?}
{171}{}{Tja, eigentlich würde ich gern noch einen Blick auf deinen Kram werfen.}
{172}{}{Danke, Doc. Laß mich dich noch etwas fragen.}
{173}{}{Allerdings, Doc. Danke. Auf Wiedersehen.}
{174}{}{Da hast du. Alles besser. Hat das geholfen?}
{175}{}{Eigentlich wollte ich dir ein paar Fragen stellen.}
{176}{}{Wird gehen. Danke, Doc.}
{177}{}{Das würde ich nicht zu lange vernachlässigen. Manche Wunden fangen an zu eitern, das ist
 ziemlich eklig. Und dann hätten wir da noch Wundbrand. Klar, in letzter Zeit habe ich meine
 Messer auch nich' mehr so oft geschwungen, wie ich's gern hätte. Roste langsam etwas ein. Ich
 sag dir was, laß es doch einfach so lange siffen, wie du magst. Vielleicht kann ich ja später
 wieder in Übung kommen.}
{178}{}{Ach so. Während ich eitere, laß mich dich etwas fragen.}
{179}{}{Äh, naja, ich werde drüber nachdenken. Wiedersehn, Doc.}
{180}{}{In letzter Zeit scheinen immer mehr Bergarbeiter immer länger auf Jet zu fliegen als zu
 arbeiten. Wenn das so weitergeht, kommt Reddings Goldproduktion noch zum Stillstand. New Reno
 scheint das allerdings nichts auszumachen.}
{181}{}{Alle Bergarbeiter hier arbeiten nur gerade so viel, daß sie sich ihren nächsten Schuß
 Jet leisten können. Die Produktion ist ganz schön zurückgegangen. Wenn das so weitergeht,
 gehört Redding bald New Reno.}
{182}{}{Alles, was die Bergarbeiter in letzter Zeit hier tun, ist Jet nehmen. Es gräbt kaum
 noch jemand nach Gold. Ich mach mir Sorgen, daß New Reno die Stadt bald in der Tasche hat. Ich
 wünschte wirklich, daß es einen Weg gäbe, diesem Jet bald ein Ende zu bereiten.}
{183}{}{Was hat denn New Reno damit zu tun?}
{184}{}{Woher kommt denn das Jet?}
{185}{}{Ach so. Laß mich dich noch was fragen.}
{186}{}{Danke für die Information. Man sieht sich, Doc. Wiedersehn.}
{187}{}{Hallo. Ich bin der Schmerzlose Doc Johnson. Was kann ich für dich tun?}
{188}{}{Was kann der alte Doc Johnson denn diesmal für dich tun?}
{189}{}{Hey, Doc. Ich wollte dir nur einige Fragen stellen.}
{190}{}{Ich hab mich gerade gefragt, ob du irgendwelche Medikamente hast, die ich mit dir
 tauschen kann.}
{191}{}{Doc, ich habe da etwas über spezielle Rüstungsimplantate gehört. Weißt du was darüber?}
{192}{}{Ich hab mich nur umgesehen, Doc. Nett, dich zu treffen. Wiedersehn.}
{193}{}{Dank dir kriege ich dieses Jet-Problem in den Griff. Dieses Gegenmittel, das ich in
 die Jet-Lieferung gemischt habe, setzt diese Jet-Piloten wirklich alle gründlich auf den Boden
 zurück.}
{194}{}{Ich bin froh, daß es funktioniert. Laß mich dich noch etwas fragen.}
{195}{}{Schöpfen denn die Leute keinen Verdacht, wenn ihnen von dem Jet schlecht wird, das du
 ihnen verkauft hast?}
{196}{}{Bin froh, daß es funktioniert, Doc. Ich muß dann mal los. Wiedersehn.}
{197}{}{Mit Hilfe des Gegenmittels, das du mir gebracht hast, gehören die Probleme mit Jet in
 Redding jetzt der Vergangenheit an. Sieht so aus, als ob New Reno sich einen anderen Weg
 ausdenken muß, wie sie uns einkassieren können.}
{198}{}{Ich bin froh, daß ich helfen konnte. Laß mich dich noch etwas fragen.}
{199}{}{Haben denn die Leute keinen Verdacht geschöpft, als ihnen von dem Jet schlecht wurde,
 das du ihnen verkauft hast?}
{200}{}{Was hat denn New Reno damit zu tun gehabt?}
{201}{}{Bin froh, daß es funktioniert hat, Doc. Dann Tschüß.}
{202}{}{Eine Lösung? Was meinst du?}
{203}{}{Ich meine, daß ich ein Mittel gegen Jet habe. Es ist von Dr. Troy aus Vault City und
 es sollte eigentlich das Jet-Problem lösen, daß ihr hier habt.}
{204}{}{Och, nichts. Laß mich dich noch etwas fragen, Doc.}
{205}{}{Allerdings, zuviel Jet, zu wenig Arbeit... aber wo hast du das gehört?}
{206}{}{McClure aus Vault City hat's mir erzählt.}
{207}{}{Ich hab nur ein Gerücht gehört, das ist alles.}
{208}{}{Ist nicht so wichtig. Laß mich dich noch etwas fragen.}
{209}{}{New Reno verkauft Jet ziemlich billig. Jet macht richtig süchtig, schlimmer als alles,
 was du je gesehen hast. Die denken sich, wenn erst mal genug Leute in einer Gegend Jet nehmen,
 werden sie alles tun, um mehr zu bekommen. Das bedeutet, daß sie de facto die Kontrolle über so
 eine Gegend haben - wie in Redding.}
{210}{}{Ach so. Laß mich dich noch etwas fragen, Doc.}
{211}{}{Wenn du also nicht möchtest, daß New Reno Redding kontrolliert, wer soll dann deiner
 Meinung nach das Ruder hier übernehmen?}
{212}{}{Danke für die Erklärung, Doc. Wiedersehen.}
{213}{}{Das gesamte Jet hier in der Stadt kommt von der Mordino-Familie in New Reno. Es kommt
 in der Regel in großen Paketen an und ich fülle es dann in Ampullen für die Leute... so daß ich
 dann alles hier verkaufe.}
{214}{}{Daraus mußt du ja einen ganz schönen Gewinn schlagen.}
{215}{}{Dann mußt du dich mit den Leuten in New Reno ja wirklich gut verstehen.}
{216}{}{Ach so. Laß mich dich noch was fragen.}
{217}{}{Hast du dann auch etwas Jet für mich da?}
{218}{}{Eigentlich nicht. Die sind es wahrscheinlich so sehr gewohnt, daß ich das Jet für die
 Süchtigen aufbereite, daß sie daran keine unnötigen Gedanken verschwenden. Ich mach das schon
 eine ganze Weile und ich bin schon lange der Arzt hier.}
{219}{}{Ich bin froh, daß es dich nicht in Schwierigkeiten gebracht hat. Laß mich dich noch
 was fragen, Doc.}
{220}{}{Gut, ich wette, die Sache könnte ziemlich häßlich werden, wenn sie jemals Verdacht
 schöpfen. Na dann, Wiedersehn, Doc.}
{221}{}{Naja, jeder will einen Teil des Goldes hier in Redding, also werden wir über kurz oder
 lang von irgend jemandem kontrolliert werden. Ich möchte nur, daß jemand über Redding
 entscheidet, der das Beste für uns tut.}
{222}{}{Und wer glaubst du, ist das?}
{223}{}{So wie ich das sehe, hat Redding die beste Chance, wenn Vault City hier das Ruder
 übernimmt. Da komme ich her, ich habe also wahrscheinlich Vorurteile, aber ich glaube wirklich,
 daß Vault City den Bürgern von Redding besser helfen kann.}
{224}{}{Und warum?}
{225}{}{Weil sie in Vault City gerecht und human sind. So wären sie auch Redding gegenüber.
 Da bin ich mir sicher.}
{226}{}{Vault City kümmert sich schon gut um seine Bürger, aber andere werden wie Dreck
 behandelt.}
{227}{}{Ach so, Doc. Ja, das klingt logisch.}
{228}{}{Sie werden schon bald merken, was die Vorteile sind. Ich bin sicher, daß sie die
 Verwaltung von Vault City mit offenen Armen begrüßen werden - äh, naja, letztendlich
 jedenfalls.}
{229}{}{Ach so. Tja, laß mich dich über etwas anderes befragen als über Politik.}
{230}{}{Hmm, ich weiß ja nicht so recht. Wiedersehn.}
{231}{}{Das ist Unsinn. Vault City gewährt seinen Bürgern besondere Privilegien, aber nur, weil
 sie besser qualifiziert sind, diese Dinge zu genießen, als diese barbarischen Nicht-Bürger.
 Außerdem kann sich jeder für das Bürgerrecht von Vault City qualifizieren, wenn er die
 Prüfungen besteht.}
{232}{}{Ich bin mir nicht so sicher, wie die Leute hier in Redding auf eine Vault City
 Herrschaft reagieren würden.}
{233}{}{Ja, zweifellos. Wiedersehn, Doc.}
{234}{}{Füllen und Verteilen der Jet-Ampullen ist ein Gefallen für die Leute von Redding. Ich
 mache damit keine Geschäfte. Wenn ich es nicht täte, würde irgendso ein Quacksalber die Droge
 mit verkeimter, rostiger Ausrüstung aufbereiten. Danach würde ich die Bevölkerung nie wieder
 gesund kriegen.}
{235}{}{Was für'n netter Kerl du doch bist, Doc. Das finde ich toll. Laß mich dich noch etwas
 fragen.}
{236}{}{Wie *nobel* von dir, Doc.}
{237}{}{Das ist interessant. Man sieht sich, Doc. Wiedersehn.}
{238}{}{Ich wär dir dankbar, wenn du nicht so sarkastisch wärst. Nenn mich ruhig nobel, wenn du
 willst, ich ziehe den Ausdruck praktisch vor. Die Minenbesitzer zahlen mir ein Gehalt, damit
 ich die Bergarbeiter relativ gesund und arbeitsfähig halte. Wenn ich jemand anderen mit dem Jet
 arbeiten ließe, könnte ich nie den Job machen, für den ich bezahlt werde.}
{239}{}{Ach so. Na gut, dann laß mich dich noch etwas fragen.}
{240}{}{Hmm, danke, daß du mir das erzählt hast. Wiedersehn, Doc.}
{241}{}{Dr. Troy? Den kenn ich. Ein toller und begabter Arzt. Wir haben zusammen gearbeitet,
 als ich noch in Vault City war. Erzähl mir von diesem Gegenmittel.}
{242}{}{Du hast mal in Vault City gearbeitet?}
{243}{}{Dr. Troy sagte, ich sollte dir das Gegenmittel bringen und daß du schon wüßtest, was du
 damit zu tun hättest.}
{244}{}{Ja, da habe ich meine Ausbildung zum Arzt erhalten. Ich bin Bürger von Vault City.
 Ich habe aber festgestellt, daß viele andere Orte in der Welt mein medizinisches Können nötiger
 hatten als Vault City. So bin ich hier gelandet. Und jetzt zu diesem Gegenmittel...}
{245}{}{Dr. Troy sagte, ich sollte dir das Gegenmittel bringen und daß du schon wüßtest, was du
 damit zu tun hättest.}
{246}{}{In der Tat. Also gib's mir schon.}
{247}{}{Hier ist es, Doc.}
{248}{}{Nicht so schnell, Doc. Was ist es dir denn wert?}
{249}{}{Ich glaube, ich gebe es dir erst mal noch nicht. Man sieht sich, Doc. Wiedersehn.}
{250}{}{Was es mir wert ist? Du kleine Kröte, ich sollte...}
{251}{}{Immer mit der Ruhe, Doc, solche Reden machen mich ganz schwach und zitterig. Ich könnte
 leicht etwas fallen lassen... wie zum Beispiel diese Flasche mit dem Gegenmittel.}
{252}{}{OK, OK. Hey, ich hab doch nur Spaß gemacht. Hier ist es.}
{253}{}{Dankeschön. Ich werde dafür sorgen, daß die Bergarbeiter mit ihrer nächsten Ladung Jet
 ein kleines *Extra* bekommen.}
{254}{}{Werden die denn keinen Verdacht schöpfen, Doc?}
{255}{}{Ich bin froh, daß ich helfen konnte. Laß mich dich noch was fragen, Doc.}
{256}{}{Gut, ich mag es nämlich gar nicht, ständig überall diese Jet-Piloten rumfliegen
 zu sehen. Wiedersehen, Doc und alles Gute.}
{257}{}{OK, du hast gewonnen. Ich geb dir $2000 dafür. Das ist alles, was ich habe.}
{258}{}{Dann wird's das wohl tun müssen. OK, hier ist es, Doc.}
{259}{}{Ich werde es, glaub ich, noch eine Weile behalten. Wiedersehn, Doc.}
{260}{}{Das kannst du ruhig tun, aber einen besseren Preis kriegst du doch nicht von mir. Das ist
 nämlich wirklich alles, was ich habe.}
{261}{}{Na gut, OK, dann nehme ich eben die $2000. Hier ist das Gegenmittel, Doc.}
{262}{}{Wir werden sehen. Wiedersehn, Doc.}
{263}{}{Ich kenne McClure. Er ist im Stadtrat von Vault City. Was hat er dir erzählt?}
{264}{}{Daß die Produktion der Goldminen zurückgeht und der Goldpreis dafür nach oben schießt.}
{265}{}{Ich weiß nicht so recht, ob ich dir das sagen soll.}
{266}{}{Oh? Und was besagt dieses Gerücht?}
{267}{}{Daß die Produktion der Goldminen zurückgeht und der Goldpreis dafür nach oben schießt.}
{268}{}{Ach, nur den üblichen Mist. Hey, laß mich dich noch etwas fragen, Doc.}
{269}{}{Das ist wahr. Die Bergarbeiter nehmen nur noch Jet und arbeiten deshalb kaum. Das
 bedeutet, daß der Export im Keller ist und die Preise in den Wolken sind. Diese Situation kann
 nicht mehr lange anhalten.}
{270}{}{Das klingt nicht gut. Hmm, laß mich dich noch etwas fragen.}
{271}{}{Das klingt nicht gut, Doc. Wiedersehn.}
{272}{}{Ich heiße so, weil meine Patienten in der Regel ohnmächtig werden, bevor sie zuviel
 schreien können. Ist nur so 'ne Art Witz.}
{273}{}{Ach so. Naja, das ist, äh, beruhigend. Glaub ich. Laß mich dich noch etwas fragen.}
{274}{}{Ich glaube, ich muß los. Gerade fällt mir da so'n wichtiger Termin ein, bei, äh,
 irgend jemandem. Äh, Wiedersehn, Doc.}
{275}{}{Du kannst es mir ruhig sagen. Ich bin Arzt.}
{276}{}{Oh, ja. Na gut, OK. Er hat mir gesagt, daß die Goldproduktion hier in Redding sehr flau
 ist und die Preise sehr hoch sind.}
{277}{}{Darüber habe ich auch etwas gelesen. Das ist gar nicht so schwer, wenn man die Ausbildung
 hat. Und die Ausrüstung natürlich.}
{278}{}{Hast du alles, was du für diese Operation brauchst?}
{279}{}{Fast alles. Ich habe das Können und die Ausbildung, aber die Implantate habe ich nicht.}
{280}{}{Und was bedeutet das?}
{281}{}{Das bedeutet, wir werden improvisieren müssen. Ich glaube, ich kann alles, was ich
 brauche, von einer Standard-Kampfrüstung bekommen. Ich kann die Schlagschutzplatten und auch
 die Thermalzellen von der Rüstung nehmen.}
{282}{}{Klasse. Du kannst es also machen?}
{283}{}{Naja - aber wenn ich zuviel Rüstung reinpacke, wird der Patient sicher keine
 Schönheitswettbewerbe gewinnen.}
{284}{}{Das ist mir egal; mich interessiert nur der Schutz. Was genau kannst du tun?}
{285}{}{Tatsächlich gibt es vier verschiedene Operationen, die durchgeführt werden können. Da ist
 einmal die Hautstabilisatorrüstung, die gegen Aufprall schützt; dann sind da die
 Phoenix-Rüstungsimplantate, die vor Hitze schützen. Für beide gibt es außerdem eine
 Abwehrverstärkung. Bevor du eine Abwehrverstärkung bekommen kannst, brauchst du aber erst mal
 die Grundrüstung.}
{286}{}{Über welche Operation möchtest du etwas wissen?}
{287}{}{Ich glaube, so etwas möchte ich nicht machen lassen. Laß mich dich etwas anderes fragen.}
{288}{}{Erzähl mir über die Implantate; ich glaube, ich will die Operation.}
{289}{}{Ich weiß eigentlich schon genug. Ich muß erst mal darüber nachdenken. Wiedersehen.}
{290}{}{Und an welcher Operation bist du interessiert?}
{291}{}{Die Hautstabilisatorrüstung.}
{292}{}{Das Phoenix-Rüstungsimplantat.}
{293}{}{Die Abwehrverstärkung für die Hautstabilisatorrüstung.}
{294}{}{Die Abwehrverstärkung für die Phoenix-Rüstungsimplantate.}
{295}{}{Doc, ich glaube, ich möchte dich lieber über etwas weniger... äh, Eindringliches befragen.}
{296}{}{Ich will über die Operation im Moment lieber doch nichts hören. Wiedersehn.}
{297}{}{Soweit ich informiert bin, bietet dir die Hautstabilisatorrüstung 5 % Schutz gegen
 normalen und explosionsbedingten Schaden - zusätzlich zu jeder anderen Rüstung, die du gerade
 trägst. Die Operation dauert etwa 2 Tage und man braucht die Teile einer Kampfrüstung. Das Ganze
 kostet dann $5.000. Diese Prozedur ist eigentlich recht simpel... glaube ich. Hmm, vielleicht
 behältst du nicht einmal allzu viele Narben zurück.}
{298}{}{Das klingt toll, Doc. Das machen wir. Ich hasse es nämlich wie die Pest, ständig
 angeschossen, gestochen und in die Luft gesprengt zu werden.}
{299}{}{Erzähl mir noch etwas von den anderen Operationen, Doc.}
{300}{}{Dann komm ich zurück, wenn ich mehr Geld habe, Doc. Wiedersehn.}
{301}{}{Dann komm ich zurück, wenn ich eine Kampfrüstung aufgetrieben habe, Doc. Wiedersehn.}
{302}{}{Ich glaub, ich will das jetzt doch nicht machen. Wiedersehn, Doc.}
{303}{}{Du brauchst aber erst die Hautstabilisatorrüstung, bevor ich dir die Abwehrverstärkung
 einpflanzen kann. Aber ich sage dir trotzdem, wie sie dann wirken sollte. Mit der
 Abwehrverstärkung bekommst du insgesamt eine 10 %ige Widerstandskraft gegen normale
 und explosionsbedingte Schäden, zusätzlich zu jeder Rüstung, die du gerade trägst. Die
 Operation dauert ein paar Tage und kostet $30.000. Außerdem wird es deinem Aussehen
 nicht eben zuträglich sein. Mit all diesen Abwehrplatten unter der Haut wirst du ziemlich
 eckig aussehen, wenn auch irgendwie stromlinienförmig. Andererseits, schließlich mag doch jeder
 den Anblick eines neuen Autos. Ich werd versuchen, dir keine Heckflossen zu verpassen.}
{304}{}{Mit der Abwehrverstärkung solltest du insgesamt eine 10 %ige Widerstandskraft gegen
 normale und explosionsbedingte Schäden bekommen - zusätzlich zu jeder Rüstung, die du
 gerade trägst. Die Operation dauert ein paar Tage und kostet $30.000. Außerdem wird es deinem
 Aussehen nicht eben zuträglich sein. Mit all diesen Abwehrplatten unter der Haut wirst du
 ziemlich eckig aussehen, wenn auch irgendwie stromlinienförmig. Andererseits, schließlich mag
 doch jeder den Anblick eines neuen Autos. Ich werd versuchen, dir keine Heckflossen zu verpassen.
 Bist du bereit?}
{305}{}{Das hört sich toll an, Doc. Das machen wir. Ich werd sowieso alle Nase lang angegriffen
 und da macht es mir nichts aus, wenn ich auch so aussehe.}
{306}{}{Erzähl mir noch etwas von den anderen Operationen, Doc.}
{307}{}{Dann komm ich zurück, wenn ich mehr Geld habe, Doc. Wiedersehn.}
{308}{}{Dann komm ich zurück, wenn ich eine Kampfrüstung aufgetrieben habe, Doc. Wiedersehn.}
{309}{}{Ich glaub, ich will das jetzt doch nicht machen. Wiedersehn, Doc.}
{310}{}{Den Berichten zufolge geben die Phoenix-Rüstungsimplantate dir eine 5 %ige
 Widerstandskraft gegen Hitzeschäden (Feuer, Laser und Plasma) - zusätzlich zu jeder Rüstung,
 die du gerade trägst. Die Operation dauert einige Tage und man braucht die wärmeableitenden
 Membranen einer Kampfrüstung. Das Ganze kostet $8.000. Aber mach dir keine Sorgen, diese
 Operation sollte *eigentlich* nur ganz geringe Narben hinterlassen - jedenfalls habe ich das so
 gelesen.}
{311}{}{Das hört sich toll an. Doc. Dann müßte ich mir wahrhaftig keine Sorgen mehr um 
zusätzlichen Sonnenschutz machen.}
{312}{}{Erzähl mir noch etwas von den anderen Operationen, Doc.}
{313}{}{Dann komm ich zurück, wenn ich mehr Geld habe, Doc. Wiedersehn.}
{314}{}{Dann komm ich zurück, wenn ich eine Kampfrüstung aufgetrieben habe, Doc. Wiedersehn.}
{315}{}{Ich glaub, ich will das jetzt doch nicht machen. Wiedersehn, Doc.}
{316}{}{Du brauchst die Phoenix-Rüstungsimplantate, bevor ich dir die Abwehrverstärkung
 einpflanzen kann. Aber ich sag dir trotzdem, wie sie sich auswirken sollte.
 Die Abwehrverstärkung sollte dir insgesamt eine 10 %ige Widerstandskraft gegen Hitzeschäden
 (Feuer, Laser und Plasma) bieten - zusätzlich zu jeder Rüstung, die du gerade trägst. Die
 Operation dauert einige Tage und kostet $48.000. Außerdem wird es deinem Aussehen nicht eben
 zuträglich sein. All diese Schichten von Wärmeableitfolien unter der Haut werden dir ein etwas
 klumpiges Aussehen verleihen, etwa so wie ein zu prall gefüllter Strudel.}
{317}{}{Die Abwehrverstärkung der Phoenix-Implantate sollte dir insgesamt eine 10 %ige
 Widerstandskraft gegen Hitzeschäden (Feuer, Laser und Plasma) bieten - zusätzlich zu jeder
 Rüstung, die du gerade trägst. Die Operation dauert einige Tage und kostet $48.000. Außerdem
 wird sie deinem Aussehen nicht eben zuträglich sein. All diese Schichten von Wärmeableitfolien
 unter der Haut werden dir ein etwas klumpiges Aussehen verleihen, etwa so wie ein zu prall
 gefüllter Strudel? Bist du bereit}
{318}{}{Hört sich toll an, Doc. Das machen wir.}
{319}{}{Erzähl mir noch etwas von den anderen Operationen, Doc.}
{320}{}{Dann komm ich zurück, wenn ich mehr Geld habe, Doc. Wiedersehn.}
{321}{}{Dann komm ich zurück, wenn ich eine Kampfrüstung aufgetrieben habe, Doc. Wiedersehn.}
{322}{}{Ich glaub, ich will das jetzt doch nicht machen. Wiedersehn, Doc.}
{323}{}{Na bitte, das war es schon. Die Operation war ein Erfolg. Jetzt solltest du dir über
 Stöße und blaue Flecken nicht mehr allzu viele Sorgen machen müssen. Die Schwellung und
 Empfindlichkeit gibt sich in ein paar Tagen.}
{324}{}{Ich hätte nie gedacht, daß unter deiner Haut Platz für so viele Abwehrplatten sein
 könnte, aber jetzt bist du gut gewappnet. Du siehst nur ein bißchen aus wie Frankensteins
 Monster, aber du solltest auch genauso zäh sein. Äh, versuch am besten, die Sonne etwas zu
 meiden, bis der Schorf so weit ab ist.}
{325}{}{Das ist mir ziemlich gut gelungen, finde ich. Die Phoenix-Rüstung hat sich viel besser
 implantieren lassen, als ich dachte. Das Brennen und Jucken sollte in ein paar Wochen
 nachlassen... wenn sich dein Körper erst mal an die Faser gewöhnt hat.}
{326}{}{Na, wachen wir wieder auf? Du bist prall gefüllt mit Wärmeableitfolien und Membranen.
 In ein paar Wochen siehst du nicht mehr ganz so klumpig aus, aber du wirst auch keine
 Schönheitswettbewerbe mehr gewinnen. Versuch am besten, nicht an der Eiterkruste um die
 Drainage-Einschnitte zu pulen, solange sie noch eitern und nässen.}
{327}{}{Danke für den guten Rat, Doc. Das ist toll. Hey, laß mich dich noch was fragen.}
{328}{}{Danke für die prima Handarbeit, Doc. Ich mach mich dann mal lieber auf den Weg.
 Wiedersehn.}
{329}{}{Du bringst das Jet-Heilmittel zu Dr. John.}
