{100}{}{Du siehst einen großen Mann mit einem riesigen, unförmigen Bauch.}
{101}{}{Du siehst Hakeswill, einen Arbeiter aus der Morningstar-Mine.}
{102}{}{Du siehst einen Mann mit gelbsüchtiger Haut, einer Narbe um den Hals und einem riesigen
 Bauch.}
{103}{}{Hey, du, was glaubst du, was du da machst?}
{104}{}{Hakeswill wird's dich lehren, aber hallo.}
{105}{}{Blöde Spinner, allesamt.}
{106}{}{Erweis den höherstehenden den nötigen Respekt.}
{107}{}{Liebst du deine Mutter?}
{108}{}{Hau ab, du.}
{109}{}{Hier ist kein Platz für solche wie dich.}
{110}{}{Wir wissen schon, wie man mit deinesgleichen umgeht.}
{111}{}{Was glotzt 'n so?}
{112}{}{Beweg dich, du, bevor ich die Geduld verliere.}
{113}{}{Eines Tages werde ich dich schon erwischen.}
{114}{}{Du kannst mich nicht umbringen. Das haben schon andere vor dir versucht.}
{115}{}{Ich komm hier wieder raus. Wirst sehen.}
{116}{}{Die Schlampe hat's nicht anders verdient.}
{117}{}{Was ich mit dieser Ollen gemacht hab, ist noch gar nichts gegen das, was ich mit dir
 vorhab.}
{118}{}{Ich heb mir einen flachköpfigen Nagel für dich auf.}
{119}{}{Ich bin gottverdammt unbesiegbar, das bin ich. Und hier wird es mich auch nicht lange
 halten.}
{120}{}{Das war schlau von dir.}
{121}{}{Obidiahs Mutter liebt ihn.}
{122}{}{Nächstes Mal kümmere ich mich um Lou.}
{123}{}{Du bist schlauer, als du aussiehst.}
{124}{}{Blöde Ollen, die sind alle gleich. Wo ist mein Rasiermesser?}
{125}{}{Hab gehört, daß vielleicht jemand mit dem alten Hakeswill sprechen will. Ein Freiwilliger,
 der Obidiah das Gesetz lehren will. Bist du das?}
{126}{}{Ich such den Bergarbeiter, der Lous Mädchen entstellt hat. Hört sich mir ganz so an, als
 ob du das gerade zugegeben hast.}
{127}{}{Ich bringe das Gesetz zu dir. Das 10 mm Gesetz, um genau zu sein.}
{128}{}{Könnte sein. Was weißt du über die Sache?}
{129}{}{Nein, Sir, hä, hä. Das würd ich nicht tun. W'wiedersehen...Sir.}
{130}{}{Ich hab die Schlampe geschnitten. Die hat 'nen Fehler gemacht, hat sie nämlich.}
{131}{}{Einen Fehler?}
{132}{}{Mir egal, was sie dir getan hat. Du bist ein toller Hund und ich bin derjenige, der dich
 einschläfern wird.}
{133}{}{Du hast den Fehler gemacht, du verrückter Schwachkopf. Ich bringe dich ins Gefängnis und
 dann kommst du vor Gericht und an den Galgen.}
{134}{}{Ins Gefängnis? Ich komme friedlich mit. Hat ja keinen Sinn, Ärger zu machen. Trotzdem,
 die Schlampe hat bekommen, was sie verdient hat. Mich kannst du nicht umbringen. Ich bin
 unbesiegbar, aber die anderen Bergarbeiter kannst du so sicher verärgern. Du hast keine Augen im
 Hinterkopf, oder?}
{135}{}{Ich kann schon auf mich aufpassen. Im übrigen bin ich hier der Sheriff und ich bring dich
 hinter Gitter.}
{136}{}{Wenn ich es mir überlege, habe ich eine noch bessere Idee. Warum spare ich den guten
 Leuten in Redding nicht einfach Zeit und Ärger und bringe dich gleich hier und jetzt um?}
{137}{}{Ich will nicht alle anderen Morningstar-Bergarbeiter verärgern. Dieses Mal kommst du mit
 einer Warnung davon. Aber wenn du das noch mal machst...}
{138}{}{Oh, danke, Mister. Jawohl, Sir Obidiah wird aufpassen, Sir. Danke.}
{139}{}{Danke, Madame. Ja, Madame. Obidiah wird schon aufpassen, Madame. Danke.}
{140}{}{Sieh bloß zu, daß du dich zusammenreißt. Ich will sowas nicht noch mal hören.
 Wiedersehn.}
{141}{}{Sie hat sich über meine Ma lustig gemacht. Niemand macht sich über Hakeswills Ma lustig.
 Sie ist das einzig Gute in dieser ganzen verdorbenen Welt.}
{142}{}{Ist mir egal, warum du's getan hast. Du kommst mit mir zum Gefängnis. Jetzt gleich.}
{143}{}{Deine Ma hätte eine zuverlässigere Empfängnisverhütung benutzen sollen.}
{144}{}{Sie hat sich über deine Mutter lustig gemacht? Das ist aber wirklich nicht nett. Trotzdem
 hast du überreagiert.}
{145}{}{Na gut, hab ich. Aber die Jungs und ich hier in der Morningstar finden, daß hätt sie
 nicht tun dürfen. Aber ich versprech, es wird nicht wieder vorkommen.}
{146}{}{Tja, ich sollte dich einlochen dafür, daß du dem Mädchen das halbe Gesicht entstellt hast
 - aber solang du das nicht zur Gewohnheit machst... Diesmal laß ich dich noch mal davonkommen.}
{147}{}{Ich bin sicher, die Geschworenen werden das berücksichtigen. Ich loch dich trotzdem ein.}
{148}{}{Wenn die anderen Bergarbeiter dieselbe brutale Einstellung haben wie du, dann tut ihnen
 das Exempel nur gut, das ich an dir statuieren werde.}
