{100}{}{Du siehst ein rotznäsiges kleines Gör.}
{101}{}{Das Kind von Vizepräsident Carlson}
{102}{}{Ein völlig verzogener Steppke, und obendrein auch noch fett.}
{103}{}{Du mußt lieb zu mir sein, weil mein Papi Vizepräsident Carlson ist! Wer bist du?}
{104}{}{[Spielername]}
{105}{}{Ich gehör zur Wache von deinem Papi. }
{106}{}{Wo ist dein Papi?}
{107}{}{Siehst du das Messer hier? Du wärst nicht das erste Kind, dem ich den Bauch aufschlitze. Aber vielleicht das häßlichste.}
{108}{}{Ich bin dein schlimmster Alptraum, Zwerg.}
{109}{}{Tut mir leid, Kind, ich hab zu tun.}
{110}{}{? Was für ein beschissener Name. Du hast einen blöden Namen! Einen saublöden Namen!}
{111}{}{Dann mußt du doppelt so lieb zu mir sein, oder ich sag's meinem Papi.}
{112}{}{Oh? Wie wär's, wenn ich (flüster).}
{113}{}{Gut. Oh, Junge.}
{114}{}{Er ist drin in seinem Büro. Er ist da immer drin.}
{115}{}{Wo ist sein Büro?}
{116}{}{Okay. Danke.}
{117}{}{Am Wassertank. Ich spiel da manchmal. Ich guck ihm heimlich zu, wenn er arbeitet.}
{118}{}{Du bist wohl eine kleine Nervensäge, was?}
{119}{}{Danke, Kleiner. Du hast mir sehr geholfen.}
{120}{}{Du bist nicht lieb, du bist böse! Ich sag's meinem Vati!}
{121}{}{Hey, du schon wieder. Was machst du?}
{122}{}{Geh und frag deinen Vater, ob ich mal mit ihm reden kann.}
{123}{}{Sag deinem Vater, ich bringe Neuigkeiten über Mr. Bishop. Kannst du dir das merken?}
{124}{}{Pfnah.}
{125}{}{Du hast Matsch in der Birne! Matschbirne!}
{126}{}{Okay.}
{127}{}{Neuigkeiten über Mr. Mishop. Richtig?}
{128}{}{Nicht schlecht.}
{129}{}{Vati sagt, er hat keine Zeit.}
{130}{}{Ich hab's Vati gesagt. Ich glaub, Vati mag dich nicht.}
{131}{}{Vati sagt, du kannst reinkommen.}
{132}{}{Ich hab Vati gesagt, daß du böse warst.}
{133}{}{Genau, ich bin das Schreckmonster, und ich freß dich auf mit Haut und Haar.}
{134}{}{Du hast mich falsch verstanden, Kind.}
{135}{}{Ich soll nicht mit dir reden}
{136}{}{Mein Vati ist tot. Warum hast du ihn nicht gerettet?}
