{100}{}{Du siehst einen bulligen Mann in Lederklamotten.}
{101}{}{Das ist Felix, der Vorarbeiter auf der Ranch.}
{102}{}{Dieser Genosse ist sichtlich robuster und gelassener als die übrigen, die hier herumhängen.}
{103}{}{Was kann ich für dich tun, Fremdling?}
{104}{}{Du schon wieder?}
{105}{}{Nnja.}
{106}{}{Der Sheriff meinte, ich soll hier mal vorbeischauen. Mr. Westin hätte eventuell Arbeit für mich, meint er.}
{107}{}{Ich bin hier, um mit dem Chef zu reden.}
{108}{}{Ich such Arbeit.}
{109}{}{Ich bin auf der Suche nach Vault 13.}
{110}{}{Sehe mich nur um.}
{111}{}{Großartig, schon wieder so ein Trottel. Ich nehme an, du willst den Chef sprechen?}
{112}{}{Ah-ha.}
{113}{}{Neee.}
{114}{}{Gut. Geh rein.}
{115}{}{Es ist schon spät. Komm morgen früh wieder her.}
{116}{}{Also dann, raus mit dir.}
{117}{}{Dumont, wie? Das soll mir genügen. Mr. Westin ist drin.}
{118}{}{Entzückend. Mr. Westin redet nicht mit jedem. Willst du was Bestimmtes von ihm?}
{119}{}{Ich bin auf der Suche nach Vault 13.}
{120}{}{Was ist, wenn ich sage, daß Bishop in New Reno mich geschickt hat, ihn umzubringen?}
{121}{}{Oh, nein.}
{122}{}{Heiliger Bimbam! Noch so ein Spinner. Du würdest dich bestimmt ganz wunderbar mit Pökel-Bob verstehen. Geh mal hin zu ihm.}
{123}{}{Wer?}
{124}{}{Mir reicht's. Ich gehe.}
{125}{}{Pökel-Bob - drüben in den Stallungen. Mr. Westin läßt ihn da wohnen. Und jetzt hab ich genug Zeit mit dir vergeudet.}
{126}{}{Besten Dank.}
{127}{}{Wenn dem so ist, müssen wir dich wohl töten.}
{128}{}{Besprechung zu Ende?}
{129}{}{Westin. Arbeit. Ich}
{130}{}{Ich gehn.}
{131}{}{Gut. Wenn er dir Arbeit geben will, dann sollst du Arbeit kriegen!

Irgendwas oder Irgendwer töten Muh-Muhs. Kommen mit mir. Du wachen. Passen auf auf Muh-Muhs. Machen Chef froh. Okay?}
{132}{}{Okay}
{133}{}{Nein. Ich nix töten.}
{134}{}{Schon wieder hier? Fertig mit der Arbeit?}
{135}{}{Ja.}
{136}{}{Nein.}
{137}{}{Ja, er hat Anweisung erteilt. Er erwartet dich.}
{138}{}{HE DU! Geh da weg!}
{139}{}{Okay.}
{140}{}{Fahr zur Hölle!}
#addons
{141}{}{Ja. Er will mit dir über die Probleme mit den Brahmin reden.}
{142}{}{Ja. Ich mach mich davon.}
{143}{}{Richtig. Irgendwas oder Irgendwer hat Brahmin an der West-Passage getötet. Ich bringe dich dorthin und du kümmerst dich darum. Los geht's.}
{144}{}{Vergiß es!}

{145}{}{Mr. Westin erwartet dich.}
{146}{}{Nun, wir hatten da einige Problem mit Viechern, aber das hat aufgehört. Du kannst mit Westin reden, wenn du willst.}
{147}{}{Ich komme aus Vault City und bin geschäftlich hier.}
{500}{}{Wag es nicht, diese Tür noch mal anzufassen, sonst gibt's Saures. Verstanden, Kumpel?}
