{100}{}{Du siehst einen gut gekleideten Mann von schwerem Körperbau, der sich mit bedächtiger Langsamkeit bewegt.}
{101}{}{Das ist Merk - die Leute in dieser Gegend hier nennen ihn einfach nur "Der Mann".}
{102}{}{Es geht eine arrogante Kälte von diesem Burschen aus. Man hat das Gefühl, dass ihm nicht mehr an dir liegt als an der Schmeißfliege, die er soeben zwischen den Fingern zerdrückt hat.}
{103}{}{Dich hab ich doch im Film gesehen! Und, was steht heute so auf dem Programm?}
{104}{}{Was soll das, willst du mir auf die Nerven gehen? Mach, dass du hier rauskommst.}
{105}{}{Tut mir leid, aber ich muss mich um meine Geschäfte kümmern.}
{106}{}{Komm ins Rawhide, wenn du was Geschäftliches mit mir zu bereden hast. Ansonsten lass mich in Ruhe.}
{107}{}{Kenn ich dich nicht von der Leinwand? Nicht ohne, was du so, ähm, vorzuweisen hast.}
{108}{}{Du hast da so was im Blick. Schau mal im Rawhide vorbei - jemanden wie dich kann ich immer gebrauchen.}
{109}{}{Menschenskinder, was riecht hier denn so? Irgendwas ist hier doch gerade reingelatscht.}
{110}{}{Bring mir einen neuen Whiskey - aber ein bisschen dalli.}
{111}{}{Ich hab grade keine Zeit.}
{112}{}{Ich bin hier zu Gast. Geh mir nicht auf den Wecker.}
{113}{}{Hey, hast einen niedlichen Hintern, Kleine. Wusste gar nicht, dass Carlson so viel Geschmack hat.}
{114}{}{Ich mach hier keine Geschäfte.}
{115}{}{Ich kenn dich nicht. Ich bin ein ehrlicher Geschäftsmann.}
{116}{}{So eine Pfeife aber auch. Hau ab und lass mich in Ruhe.}
{117}{}{So, so, dann hat sich die Kleine also doch noch durchgerungen, zu mir zu kommen, wie?}
{118}{}{Um das mal klarzustellen: Ich weiß von überhaupt nichts.}
{119}{}{Ich glaub nicht, dass der Vize es besonders schätzt, wenn du seine Gäste belästigt.}
{120}{}{Verdammt guter Fusel, den sie einem hier vorsetzen.}
{121}{}{Geh mir aus der Sonne!}
{122}{}{Wenn du mit jemand reden willst, dann kauf dir einen Freund.}
{123}{}{Ich geb weder Wegbeschreibungen noch Almosen. Zisch ab.}
{124}{}{Was soll das werden - eine Spendenaktion?}
{125}{}{Ich bin Merk. Worum geht's?}
{126}{}{Du schon wieder?}
{127}{}{Pass auf, was du sagt, oder es könnte sehr unerfreulich für dich werden.}
{128}{}{Urt.}
{129}{}{Ich such Arbeit.}
{130}{}{Aus gewöhnlich gut unterrichteten Kreisen hört man, dass du der richtige Mann fürs Geschäftliche bist.}
{131}{}{Es heißt, du bist der Mann, der mein Auto geklaut hat.}
{132}{}{Ich bräuchte da mal ein paar Infos.}
{133}{}{Es heißt, du weißt da so das eine oder andere. Zum Beispiel über Sachen, die aus Autos verschwunden sind.}
{134}{}{Du schon wieder? Hast du die Sache erledigt?}
{135}{}{Glabb.}
{136}{}{Nein.}
{137}{}{Ich hätte da noch ein paar Fragen.}
{138}{}{Hmm...stark. Beschränkt... Wenn du 'nen Job willst, rede mit Mira. Verstanden? Mi-ra. Da drüben.}
{139}{}{Du machst wohl gern Radau, wie? Wirft mal bitte jemand diesen Haufen Brahminkacke hier raus!}
{140}{}{Bist du wirklich so bescheuert zu glauben, ich würde jedem x-beliebigen einen Job geben? Wenn du für mich arbeiten willst, muss du erst mal beweisen, dass du was taugst.}
{141}{}{Wie wär's, wenn ich kurz mal Lenny da abknalle? Der hätte es verdient.}
{142}{}{Wie meinst du das: Beweisen?}
{143}{}{Kennst du zufällig jemand, der eine Portion Jet gebrauchen könnte?}
{144}{}{Hör zu, ich bin}
{145}{}{Ich hab's gar nicht nötig, dir irgendwas zu beweisen. Vergiss es, du fette Kröte.}
{146}{}{Das war dieser gottverdammte Skeeter, stimmt's? Dieser dreckige kleine Junkie quatscht mir ein bisschen zuviel. Hör mal zu - du ziehst ihn aus dem Verkehr - nur als kleinen Gefallen - und hinterher reden wir weiter.}
{147}{}{Topp!}
{148}{}{Oh Mann - so kaltblütig bin ich nicht!}
{149}{}{Du wirst jedenfalls als größter Schwachkopf aller Zeiten in die Geschichte eingehen. Leute -}
{150}{}{Interessant. Und wer erzählt so was?}
{151}{}{Ich lass mich nicht von dir verarschen, Fettwanst. Wenn ich meine Sachen nicht zurückkriege, kannst du dich schon mal für deine Beerdigung feinmachen.}
{152}{}{Wie nett. Beantwortest du mir jetzt meine Frage oder nicht?}
{153}{}{Ach, ich hab das nur gerüchtehalber so gehört. Wollte nur mal gucken, wie du reagierst.}
{154}{}{Nehmen wir mal an, ich weiß etwas. Und weiter?}
{155}{}{Wenn da also jemandem seine Sachen abhanden gekommen sind, glaubst du, es wäre möglich sie zurückzukaufen?}
{156}{}{Ich will meinen Krempel wiederhaben, Fetti!}
{157}{}{Und wenn ich zu den Bullen gehe?}
{158}{}{Ich hab die Schnauze voll. Leute - begleitet unseren Gast nach draußen.}
{159}{}{Ich glaube nicht, dass Lenny davon sonderlich begeistert wäre.}
{160}{}{Kann gut sein, aber ich hab nicht vor, ihn nach seiner Meinung zu fragen.}
{161}{}{Ganz wie du möchtest.}
{162}{}{Stimmt. Wurde schon etwas langweilig hier. Zeit für etwas Abwechslung. Auf, Lenny, töte diesen}
{163}{}{Es gibt da ein paar Problemchen, die aus der Welt geschafft sein wollen.}
{164}{}{Und das wäre?}
{165}{}{Jet? Soll das ein Vorschlag sein...?}
{166}{}{Mein Freund hier weiß, wie man's macht. Interessiert?}
{167}{}{Was Verbotenes? Nein, das wär nichts für mich.}
{168}{}{Faszinierend. Ich geb dir 1000 Dollar für seine Dienste - für immer.}
{169}{}{Topp!}
{170}{}{Nein, das kann ich einem Freund nicht antun.}
{171}{}{Sieht so aus, als könnten wir miteinander ins Geschäft kommen. Ich sag dir, worum es sich dreht: In der Stadt gibt's einen durchgeknallten Wissenschaftler namens Dr. Henry. Der hat ein paar Unterlagen, an die ich gerne rankommen würde. Ich zahl dir 1000 Dollar dafür. Ach ja, Dr. Henry soll übrigens nichts zustoßen. Den können wir noch ganz gut gebrauchen - lebend. Interessiert?}
{172}{}{Ich bin dabei.}
{173}{}{Ohne mich. Ist nicht mein Stil.}
{174}{}{Gratis gibt's die Info aber nicht. Hab ich mich klar genug ausgedrückt?}
{175}{}{"Weisheit ist mit Gold nicht aufzuwiegen."}
{176}{}{Hier sind 50 Dollar.}
{177}{}{Vergiss es.}
{178}{}{Ach, du bist das.}
{179}{}{Weiter}
{180}{}{Wenn du meine ganz persönliche Meinung hören willst: Für mich bist du ein Haufen Dreck.}
{181}{}{Wusst ich's doch gleich, dass du eine Pfeife bist.}
{182}{}{Schon gut. Kein Problem. Ich will keinen Ärger. Pass auf, ich sag meinen Jungs, dass sie das Zeug wieder dahin tun, wo sie's herhaben.}
{183}{}{Besser so. Wenn nicht, komm ich wieder.}
{184}{}{Erzähl mir doch keinen Scheiß!}
{185}{}{So jemand wäre vielleicht sogar dazu imstande.}
{186}{}{Und jetzt würde ich vorschlagen, dass du gehst.}
{187}{}{Von mir aus, geh zu den Herren in Uniform. Du hast ja sicherlich auch Beweise für deine wilden Anschuldigungen.}
{188}{}{Ja, sicher.}
{189}{}{Macht nichts.}
{190}{}{Da wäre zum Beispiel diese verdammte Hubologin in der Stadt, die mir ganz gewaltig auf den Senkel geht. Wenn dieser Störfaktor ausgeschaltet ist, komm wieder her, dann reden wir weiter.}
{191}{}{Schon so gut wie erledigt. Ich hab da so meine Methoden zum Ruhigstellen, aber...was ist eine Hubologin und wo finde ich sie?}
{192}{}{Wie kannst du's wagen, wider den wahren Glauben zu reden!}
{193}{}{Tut mir leid, in religiöse Auseinandersetzungen mische ich mich grundsätzlich nicht ein.}
{194}{}{Je nun, ich bin Gelehrter. Wie lautet deine Frage?}
{195}{}{Frage weiter.}
{196}{}{Ich bin auf der Suche nach Vault 13.}
{197}{}{Schon mal was von einem GECK gehört?}
{198}{}{Was weißt über diese Gruppe namens Ranger?}
{199}{}{Was kannst du mir über einen Typen namens Westin erzählen?}
{200}{}{Ich suche nach Informationen über Vizepräsident Carlson.}
{201}{}{Das war's.}
{202}{}{Der Tarif gilt nur für eine Frage. Wenn du mehr wissen willst, kostet dich das noch mal 50 Dollar.}
{203}{}{Okay, hier.}
{204}{}{Ich habe alle Fakten, die ich brauche.}
{205}{}{Wie's der Zufall will, hätte ich da grade eine Karte mit dem Weg zu Vault 13. Kostet ganze 1000 Kröten. Interessiert?}
{206}{}{Klar. Die nehm ich.}
{207}{}{Und 'ne Brücke hast du bestimmt auch noch zu verkaufen.}
{208}{}{Vielleicht später.}
{209}{}{Ist das so eine Art Droge aus New Reno? Ich hab noch nie was davon gehört.}
{210}{}{Is' nich'. Ich hab aber noch mehr Fragen.}
{211}{}{Das ist alles, was ich wissen wollte.}
{212}{}{Diese Schweine? Die sollen sich hier bloß nicht blicken lassen, sonst kriegen sie ein paar Löcher.}
{213}{}{Sehr informativ. Noch 'ne Frage.}
{214}{}{Das ist alles, was ich wissen wollte.}
{215}{}{Der Rancher, was? Der kam hier irgendwann mal rein, kurz vorm Abnippeln. Der Doktor aus der Stadt musste mit irgendwelchen Tabletten anrücken - Westin hat's wohl mit dem Herzen. Das Geschäft ging ziemlich schlecht für den Rest des Abends.}
{216}{}{Danke für die Info. Ich hätte da noch ein paar weitere Fragen.}
{217}{}{Das ist alles, was ich wissen wollte.}
{218}{}{Als rechtschaffener Bürger begrüße ich Carlsons Widerstand gegen die Einflussnahme durch New Reno in dieser Gegend. Nachdem Westin nun tot ist, unterstütze ich den Vizepräsidenten hier und da in wenig in Sicherheitsfragen.}
{219}{}{Sieht wohl so aus, als würde ich dem Mann nie begegnen. Ich hab schon eine Menge über ihn gehört.}
{220}{}{Das ist alles, was ich wissen wollte.}
{221}{}{War's das?}
{222}{}{Nein, ich hab noch mehr Fragen.}
{223}{}{Ja, das wär's fürs erste gewesen.}
{224}{}{Man muss alles mal versuchen. Vault 13 ist hier der totale Kult. Sie haben sogar eine Statue für so einen Knaben aufgestellt, der angeblich von da stammt. Mehr kann ich dazu nicht sagen.}
{225}{}{Ich hab dir eine Karte zu dem Zweck verkauft. Nimm einfach die.}
{226}{}{Die Karte hat's nicht getan? Tut mir aufrichtig leid. Der Typ hat geschworen, dass sie echt ist. Woher hätte ich das wissen sollen? Ich hab keine Ahnung, wo Vault 13 ist.}
{227}{}{Ich hab noch ein paar Fragen.}
{228}{}{Das ist alles, was ich wissen muss.}
{229}{}{Pass mal auf: Ich finde, du machst deine Arbeit ziemlich gut und Carlson braucht noch ein paar Wachleute. Warte ein wenig ab und hast den Job.}
{230}{}{Ich bin dabei, Merk.}
{231}{}{Ich brauche keinen Job. Aber trotzdem danke.}
{232}{}{Bestens. Komm wieder her, wenn du fertig bist.}
{233}{}{Das ist sehr unangenehm. Jungs, tötet ihn und holt euch das Beweismaterial.}
{234}{}{Deine kläglichen Versuche, mich einzuschüchtern, haben etwas Lächerliches. Ich schlage vor, du gehst jetzt lieber, bevor mir dieses Theater zum Hals raushängt.}
{235}{}{Ah, ich bin schon vollständig im Bilde. Hast du Interesse an einem Job?}
{236}{}{Ja, das kommt mir gerade recht. Ich hab's satt, mir alles in den Schoß fallen zu lassen.}
{237}{}{Nein.}
{238}{}{Was zum Teufel machst du hier in meinem Laden?}
{239}{}{Ich war wohl ein bisschen neben der Rolle. Soll nicht wieder vorkommen. Ich würde gern kurz mit dir reden, wenn du Zeit hast.}
{240}{}{Ich mach, was ich will, du Rattengesicht.}
{241}{}{Mach, dass du hier rauskommst, du Warzenschwein!}
{242}{}{Was hast du dann hier verloren, Blödmann? Wenn du mir imponieren willst, musst du erst mal was leisten!}
{243}{}{Bevor du deinen Job nicht gemacht hast, rede ich kein Wort mehr mit dir!}
{244}{}{Du enttäuschst mich. Ich kann ziemlich ungehalten werden, wenn man mich enttäuscht. Aber bei dir will ich eine Ausnahme machen. Hau einfach ab und lass dich nie wieder hier blicken, dann vergessen wir die ganze Sache.}
{245}{}{Und, wie stehen die Geschäfte in Sachen Dr. Henry?}
{246}{}{Ja, ich hab die Unterlagen für dich.}
{247}{}{Nein.}
{248}{}{Ach, an so einem Tag kann man ja richtig gute Laune kriegen. Bringen wir also die Angelegenheit zum Abschluss.}
{249}{}{Es ist mir zu Ohren gekommen, dass der genialische Doktor im Laufe deines Besuches verschieden ist. So haben wir nicht gewettet. Angesichts dieses in wirtschaftlicher Hinsicht schweren Schlages für mich muss ich auf einer Rückzahlung bestehen.}
{250}{}{Ich geb dir einfach 500 Mäuse und dann Schwamm über die ganze Geschichte.}
{251}{}{Fahr zur Hölle.}
{252}{}{Na dann, viel Erfolg für alles Weitere. Ich nehme nicht an, dass wir je wieder was miteinander zu tun haben.}
{253}{}{Geht in Ordnung.}
{254}{}{Einverstanden - aber nur, weil ich dich sympathisch finde. Wenn du einen guten Rat brauchst: Lass dich hier nicht so bald wieder blicken.}
{255}{}{Ich hab eine Idee: Ich leg dich einfach um, nehm mir mein Geld und kassier eine Belohnung. Dazu ist man schließlich ein rechtschaffener Bürger.}
{256}{}{Du schon wieder! STIRB!}
{257}{}{Hab ich dir nicht gesagt, du sollst mich gefälligst in Ruhe lassen?}
{258}{}{ und ich bin ein absolut ungenießbarer Mistkerl. Da kannst du jeden fragen.}
{259}{}{ Typ.}
{260}{}{ Mieze.}
{261}{}{Ein Hubologe ist ein religiöser Fanatiker, der ins Irrenhaus gehört. Trifft man bei der Kirche in der Stadt an.}
{262}{}{Bin schon unterwegs.}
{263}{}{Ich rede erst wieder mit dir, wenn der Job gemacht ist! Ich brauch die Unterlagen von Dr. Henry und zwar auf der Stelle, klar?}
{264}{}{Nein, aber ich brauche ein paar Informationen.}
{265}{}{Ich weiß ganz genau, dass Lennys Tod kein Unfall war, du Drecksack.}
{266}{}{Aber diese Karte war eine Fälschung.}
{267}{}{Und wie ist das mit dem Geld, das ich dir gegeben habe?}
{268}{}{Wie schon gesagt, es tut mir leid, dass es nicht geklappt hat.}
{269}{}{Mein Vorschlag wäre der: Zum Ausgleich für den ganzen Ärger, den ich hatte, puste ich dir mit dieser Kugel hier das Hirn weg.}
{270}{}{Hmmpfh.}
{271}{}{Du hast das Problem mit den Hubologen für Merk "erledigt".}
{272}{}{Du hast die Papiere von Dr. Henry beschafft.}
{300}{}{Wo zum Teufel glaubst du eigentlich gehst du hin?! Versuch das nochmal und du kriegst den Arsch voll.}
{301}{}{Ich habe dich gewarnt!}
