{100}{}{Es ist ein Haufen alter Klamotten, in dem möglicherweise eine Person drinsteckt.}
{101}{}{Du siehst Ratch, der sich wahrscheinlich gerade entlaust.}
{102}{}{Vielleicht ist es ein Mensch, vielleicht auch ein Mutant. Fest steht auf jeden Fall, daß
 "es" ganz, ganz furchtbar stinkt.}
{103}{}{Müll zu verkaufen, Müll zu verkaufen. Sieh ihn dir an, mach mir ein Angebot.}
{104}{}{Klar, von mir aus.}
{105}{}{A-ha.}
{106}{}{Was gibt's denn hier zu kaufen?}
{107}{}{Du siehst so aus, als wärst du geschickt mit den Händen. Du hast doch Hände, oder?}
{108}{}{Ich hab fünf Dollar. Hast du guten Tratsch auf Lager?}
{109}{}{Auf Wiedersehen.}
{110}{}{Siehst du das hier? Das ist mein liebstes Stück - Edna. Ich geb jedem meiner Stücke 'n
 Namen, weiß du - sie sind wie Kinder für mich. Ich verkaufe sie nur sehr ungern, aber von
 irgendwas muß man ja leben.}
{111}{}{Du bringst meine Kinder völlig durcheinander!}
{112}{}{Ja, in Ordnung. Hier ist ein Fünfer. Hast du guten Tratsch auf Lager?}
{113}{}{Na gut - du bist ja ganz schön schräg drauf! Ich mach meine Einkäufe besser woanders.}
{114}{}{Laß mich dein Angebot noch mal ansehen.}
{115}{}{Ich und Edna gehen jetzt wohl besser.}
{116}{}{Gott sei Dank hat der Fremde dich nicht gekauft, mein Kind... Meine Sachen sind wie
 Kinder für mich, weißt du.}
{117}{}{Ähm - selbstverständlich.}
{118}{}{Ich geh dann wohl besser.}
{119}{}{Ich kann alle möglichen Sachen reparieren. Hab mir 'n Gebläse geholt, das gute Stück
 heißt Claudia, paßt in praktisch jedes Auto  - die fahren damit mindestens doppelt so gut.
 Kostet bloß tausend Dollar. Interessiert?}
{120}{}{Dummkopf, darüber haben wir schon gesprochen.}
{121}{}{Aber logisch, Claudia ist genau mein Typ von -...was auch immer.}
{122}{}{Vielleicht was anderes.}
{123}{}{Hab gehört, hier in der Stadt gibt's 'n Arzt, angeblich 'ne Art Wunderheiler. Ich glaub
 das ja nicht so ganz...}
{124}{}{Da wäre da noch Pökel. Der alte Trottel behauptet, er hätt eine Goldmine entdeckt...}
{125}{}{Miss Dorothy und Toto waren letzte Woche hier draußen. Die waren auf der Suche nach
 Ersatzteilen für das Kraftwerk. Ich hatt allerdings nicht das Richtige für sie...}
{126}{}{In der Stadt geht das Gerücht um, daß das mit Westin kein Unfall war. Die Leute sagen, es sind zu viele verdächtige Fremde unterwegs...}
{127}{}{Danke für das Geld, aber mehr weiß ich nicht.}
{128}{}{Hier ist noch mal ein Fünfer.}
{129}{}{Kann ich mir deine Sachen ansehen?}
{130}{}{Na denn, besten Dank für die Auskunft.}
{131}{}{Gib mir sechs Stunden. Bis dahin hab ich's fertig.}
{132}{}{Vorher muß ich dich noch mal kurz um deine Aufmerksamkeit bitten.}
{133}{}{Geht klar. Wir sehen uns dann nachher.}
{134}{}{Komm zurück, wenn du wieder flüssig bist. Wahrscheinlich hab ich's dann noch.}
{135}{}{Na schön.}
{136}{}{Bis dann.}
{137}{}{Da ist sie! Claudia ist fertig montiert.}
{138}{}{Gib mir noch ein wenig Zeit. Ich arbeite immer noch an dem verflixten Ding.}
{139}{}{Au weia! Ich glaub nicht, daß ich ein Ersatzhirn für dich habe.}
