{100}{}{Als sich deine Augen an die Dunkelheit gewöhnt haben, siehst du offenbar die Auswirkungen von einem Einsturz. Ein wehrloser Krieger liegt auf dem Boden und kämpft mit einem großen Felsen, um sein Bein zu befreien, während gerade ein goldener Gecko auf ihn losstürzt. Der Körper eines anderen Kriegers liegt regungslos in der Nähe.}
{101}{}{Lauf los und versuch den Krieger zu retten.}
{102}{}{Bleib stehen und beobachte, was geschieht.}

{200}{}{Wenn ich sterbe, dann werde ich wie ein wahrer Krieger sterben.}
{201}{}{Aaahh!}
