{100}{}{Du siehst einen Bürger in einem hellen blauen Overall. Es sieht wie Vaultbewohner-Overall aus, aber es ist keine
 Nummer hinten drauf.}
{101}{}{Du siehst einen Bürger von Vault City.}
{102}{}{Du siehst einen Bürger in einem hellen blauen Overall. Es sieht wie Vaultbewohner-Overall aus, aber es ist keine
 Nummer hinten drauf.}

{103}{}{::Beifall::}
{104}{}{Es ist der Held! Schau!}
{105}{}{Wie ich gesagt habe! Es ist der Held, hier, in Vault City!}
{106}{}{Guten Tag, Hauptmann.}
{107}{}{Vault City wird bestehen, Hauptmann.}
{108}{}{Guten Tag, Bürger.}
{109}{}{Vault City wird bestehen, Bürger.}
{110}{}{Ein Mutant! Wache! Wache!}
{111}{}{Ein Ghul! Wache! Wache!}
{112}{}{Wie bist Du in dieses Gemäuer gekommen?}
{113}{}{Verzeihung, hast Du einen Tagesausweis? }
{114}{}{Hmmmph. Noch ein Outsider.}
{115}{}{Scheint, als ob mehr und mehr Outsiders ihren Weg in dieses Gemäuer finden...}
{116}{}{Ich hoffe wirklich, daß Du einen Tagesausweis hast.}
{117}{}{Scheint, als ob sie in letzter Zeit für so ziemlich *jeden* Outsider einen Tagesausweis ausstellen...}
{118}{}{Ich habe von Deinen mutigen Taten gehört. Du hast Vault City einen großen Dienst geleistet...und der Welt.}
{119}{}{Dein Kampf gegen die Enklave hat selbst die Erstbürgerin beeindruckt.}
{120}{}{Ich habe gehört, daß Du soweit nach Süden bis San...Fran...Cisco gereist bist. Ist das wahr?}
{121}{}{Vielleicht *sollte* Vault City Outsider begrüßen. }
{122}{}{Ist das wahr? Hat die alte Weltregierung immer noch Krieg geführt?}
{123}{}{Du solltest Deine Reisen im  Vault City-Computer festhalten, damit andere darüber lesen können.}
{124}{}{Du darfst gerne solange bleiben, wie Du möchtest, Held.}
{125}{}{Du solltest Deine Heldentaten gegen die Enklave in einer schönen, ordentlichen Liste festhalten.}
{126}{}{*Gähn*...hrmnnn? Ja? Was ist das?}
{127}{}{Es ist ein bißchen spät für Besucher. }
{128}{}{Die MEISTEN Bürger würden zu dieser Stunde schlafen.}
{129}{}{Schlafen? Nein, nicht mehr.}
{130}{}{Bitte... komm am Morgen wieder. Morgen wird es ein langer Tag, weil ich die Listen machen muß.}
{131}{}{Guten Tag, Hauptmann.}
{132}{}{Vault City wird bestehen, Hauptmann.}
{133}{}{Kann ich Dir einen Donut bringen, Hauptmann?}
{134}{}{Stimmt was nicht, Hauptmann?}
{135}{}{Ich hoffe, keiner dieser dreckigen Outsiders macht Dir Ärger, Hauptmann.}
{136}{}{Kennen sie irgendwelche Geschichten über die Outsiderwelt, Hauptmann?}
{137}{}{Guten Tag, Bürger.}
{138}{}{Vault City wird bestehen, Bürger.}
{139}{}{Ich fühle mich doppelt gut. Und Du?}
{140}{}{Als ein Bürger ist ein Teil unserer bürgerlichen Pflichten die Erstellung und Wartung von Listen.}
{141}{}{Ich habe fast den ganzen Tag damit verbracht, die Liste für den ProKonsul zu machen und zu kontrollieren. Ich liebe
 es, Listen zu erstellen.}
{142}{}{Ich arbeite im Listenbüro. Die meisten von uns tun das. Wir hier in Vault City *lieben* es, Listen zu erstellen.}
{143}{}{Ich habe fast den ganzen Tag damit verbracht, diese Liste für das Listenbüro auf den neuesten Stand zu bringen. Es
 war gute, ehrliche, produktive Arbeit.}
{144}{}{Ich habe gehört, daß Du tatsächlich in die Outsiderwelt gereist bist. Wie hast Du bei diesen dreckigen Outsidern überlebt?}
{145}{}{Oh! Du bist der neue Bürger. Willkommen in Vault City.}
{146}{}{Brauchst Du eine Bleibe, während Du in der Stadt bist?}
{147}{}{Dem Rat liegen unsere Interessen am Herzen.}
{148}{}{Wir müssen darauf achten, unsere schöne Stadt sauber zu halten.}
{149}{}{Unsere Diener? Oh, wir benutzen sie für untergeordnete Aufgaben.}
{150}{}{Dieses Treffen des Rates gestern waren sehr produktiv. Wir haben eine *Menge* von Listen erstellt. Wir hier in
 Vault City lieben es, Listen zu erstellen.}
{151}{}{Ja?}
{152}{}{Kann ich Dir irgendwie helfen...Outsider?}
{153}{}{Verzeihung, hast Du etwas gesagt?}
{154}{}{Ich? Ich gehe meinen Geschäften nach. Solltest Du vielleicht auch.}
{155}{}{Kann ich bitte Deinen Tagesausweis sehen?}
{156}{}{Oh... Entschuldigung. Ich hatte Dich fast für einen Diener gehalten.}
{157}{}{Ich habe jetzt gerade wirklich keine Zeit, mit einem Outsider zu reden. Geh' bitte weg.}
{158}{}{Kannst Du bitte Abstand halten?}
{159}{}{Bitte steh' dort drüben hin.}
{160}{}{Die Diener geben uns mehr Zeit für die wichtigeren Angelegenheiten. Hauptsächlich Listen erstellen.}
{161}{}{Die Diener? Oh, wir benutzen sie für untergeordnete Aufgaben.}
{162}{}{Ja, ich kann riechen... äh, sehen, daß Du ein Outsider bist.}
{163}{}{Du bist ein Outsider? Wie putzig.}

