{100}{}{Du siehst Lydia.}
{101}{}{Du siehst eine braunhaarige Frau, die braunes Drillichzeug und einen Metallpanzer trägt.
 Sie scheint die Barkeeperin zu sein.}
{102}{}{Du siehst Lydia.}
{103}{}{Du siehst eine braunhaarige Frau, die braunes Drillichzeug und einen Metallpanzer trägt.
 Sie scheint die Barkeeperin zu sein.}
{104}{}{Willkommen! Möchtest du etwas trinken, Auserwähltes Wesen?}
{105}{}{Willkommen, Auserwähltes Wesen! Bitte, setz dich.}
{106}{}{Bitte! Setz dich und ruh dich ein wenig aus!}
{107}{}{Es ist das Auserwählte Wesen! Alle mal herhören: Hier ist der HELD von Fallout 2!}
{108}{}{Schönen Tag noch, Hauptmann.}
{109}{}{Vault City lebe hoch, Hauptmann.}
{110}{}{Guten Tag, Bürger.}
{111}{}{Vault City lebe hoch, Bürger.}
{112}{}{Ein Mutant! Wache! Wache!}
{113}{}{Ein Ghul! Wache! Wache!}
{114}{}{Wir haben geschlossen. Komm morgen wieder.}
{115}{}{Tut mir leid. Aber die Bar ist schon geschlossen. Komm morgen wieder.}
{116}{}{Wir haben geschlossen. Ich stelle nur noch eine Inventarliste zusammen und dann mach ich
 zu.}
{117}{}{He da, Auserwähltes Wesen! Wir haben gerade über deine Abenteuer geredet... darf ich dir
 einen ausgeben?}
{118}{}{Dwinkie-winkie, ich mach stinkie }
{119}{}{[Verschwinde.]}
{120}{}{Was gibt's hier denn hier im Ausschank?}
{121}{}{Ich brauche ein paar Auskünfte.}
{122}{}{Ich hab die Ladung Alkohol dabei, die du angefordert hast.}
{123}{}{Im Augenblick nichts, danke.}
{124}{}{Wuähh... das rieche ich! Ähh, vielen Dank fürs Retten der Welt und so.}
{125}{}{Stinkie-blinkie, zwinkie-zwinkie!}
{126}{}{[Verschwinde.]}
{127}{}{Mag ja sein, daß du die Welt gerettet hast, aber ein begnadeter Poet bist du nicht
 gerade. Und jetzt mach die Fliege.}
{128}{}{Flinkie-flinkie, klinkie-klinkie!}
{129}{}{[Verschwinde.]}
{130}{}{Hör zu, nimm das und verschwinde, verstanden? Das sollte dir für ne Weile den Hals
 stopfen.}
{131}{}{Dankie-wankie, Blinkie-Stinkie.}
{132}{}{[Verschwinde.]}
{133}{}{Ahem... was kann ich für dich tun, Hauptmann?}
{134}{}{Was kann ich für dich tun, Bürger?}
{135}{}{Ja? Kann ich etwas für dich tun?}
{136}{}{Tun? Tuhn? Tuh? Titatuh un aus bis duh.}
{137}{}{[Verschwinde.]}
{138}{}{Was gibt's hier denn hier im Ausschank?}
{139}{}{Ich brauche ein paar Auskünfte.}
{140}{}{Ich hab die Ladung Alkohol dabei, die du angefordert hast.}
{141}{}{Im Augenblick nichts, danke.}
{142}{}{Wirklich sehr interessant. Einen Augenblick mal... das möchten sich die Wachleute sicher
 auch nicht entgehen lassen.}
{143}{}{Wachleute, Schwachbräute. Lachläute. Leute, läute, bin ich toll...}
{144}{}{[Verschwinde.]}
{145}{}{Wir haben synthetische Biere und Schnäpse... Wodka-H und Tequila-Derivat W und W2. Ach ja,
 und Wasser. Und Brahmin-Milch. Bier und Schnaps kosten zehn Mäuse, Wasser oder Milch drei.}
{146}{}{Nämlich?}
{147}{}{Äh, habt ihr auch was mit richtigem Alkohol?}
{148}{}{Ich könnte mich für ein synthetisches Bier erwärmen.}
{149}{}{Synthetischer Wodka wäre jetzt genau das Richtige.}
{150}{}{Tequila W2, bitte.}
{151}{}{Wasser, bitte.}
{152}{}{Brahmin-Milch, bitte.}
{153}{}{Eigentlich brauche ich nur ein paar Auskünfte.}
{154}{}{Ich komm noch mal wieder, wenn ich mehr Geld habe.}
{155}{}{Ich glaube, ich nehme lieber gar nichts, vielen Dank.}
{156}{}{Die Brahmin-Milch gibt's aber nicht frisch gezapft... jedenfalls nicht vom Faß. Ich müßte
 dann mal kurz raus und schnell welche besorgen.}
{157}{}{Prima. Ich warte solange. Ich hab tierisch Lust auf ein Glas frische Milch. Mmmmmmmm.
 Das wär jetzt genau das Richtige.}
{158}{}{Dann nehme ich lieber was anderes.}
{159}{}{Naja, macht nichts. Ich brauche ein paar Auskünfte.}
{160}{}{Vergiß es. Ich komm ein andermal wieder.}
{161}{}{Bitte schön. Sonst noch was?}
{162}{}{Äh, habt ihr auch was mit richtigem Alkohol?}
{163}{}{Ich könnte mich für ein synthetisches Bier erwärmen.}
{164}{}{Synthetischer Wodka wäre jetzt genau das Richtige.}
{165}{}{Tequila W2, bitte.}
{166}{}{Wasser, bitte.}
{167}{}{Brahmin-Milch, bitte.}
{168}{}{Eigentlich brauche ich nur ein paar Auskünfte.}
{169}{}{Ich komm noch mal wieder, wenn ich mehr Geld habe.}
{170}{}{Ich glaube, ich nehme lieber gar nichts, vielen Dank.}
{171}{}{Ach so? Zum Beispiel?}
{172}{}{Wer ist hier in Vault City der Boß?}
{173}{}{Wo ist die Vault?}
{174}{}{Kannst du mir was über die Sklavenhaltung in Vault City erzählen?}
{175}{}{Hat Vault City viel Kontakt mit der Außenwelt?}
{176}{}{Was gibt's denn hier im Ausschank?}
{177}{}{Ich hab die Ladung Alkohol dabei, die du angefordert hast.}
{178}{}{Na dann, alles klar. Schönen Tag noch.}
{179}{}{Äh, Erstbürgerin Lynette... Du bist doch Bürger, oder?}
{180}{}{Erstbürgerin Lynette. Wenn du mit ihr reden willst: Sie ist im Ratsgebäude, in der
 Nordstadt.}
{181}{}{Ich möchte noch was wissen...}
{182}{}{Alles klar. Dann geh ich jetzt zu ihr und rede mit ihr.}
{183}{}{Ähh, das ist die große Öffnung in der Felswand am Berg im Osten... sag mal, du bist doch
 Bürger, oder?}
{184}{}{Die große Öffnung in der Felswand am Berg im Osten. Man kann sie gar nicht übersehen. Man
 kommt aber auch nicht rein, wenn man kein Bürger ist.}
{185}{}{Ich möchte noch was wissen...}
{186}{}{Aber ich bin Bürger!}
{187}{}{Ja, danke, ich werd' mich schon zurechtfinden. Das werd ich mir mal ansehen.}
{188}{}{Hmmm. Danke für die Auskunft.}
{189}{}{Natürlich bist du einer. Ich würde lieber aufpassen, bei wem ich das behaupte, "Bürger".
 Sonst merkt noch einer, daß du gestohlene Papiere beim Halsabschneider Skeev gekauft hast. Halt
 dich lieber bedeckt, kapiert?}
{190}{}{Äh, OK. Da wäre noch was...}
{191}{}{Oh. Vielen Dank für den Hinweis.}
{192}{}{Also zuerst mal: Red hier in der Gegend besser nicht von "Sklaverei", wenn du nicht eine
 Menge Ärger an den Hals kriegen willst. Man nennt sie "Diener", nicht Sklaven. Das nur als Tip.}
{193}{}{Hab schon kapiert. Aber ich möchte noch was andres wissen...}
{194}{}{Danke. Das werd ich mir merken.}
{195}{}{Nicht viel. Der meiste Kontakt mit Outsidern, den wir haben, ist mit Händlern, die mit
 den Karawanen auf der großen Runde über Broken Hills, New Reno und Redding her kommen. Der
 einzige Ort außerhalb der Karawanenroute, den ich kenne, ist Gecko.}
{196}{}{Erzähl mir was über Broken Hills.}
{197}{}{Erzähl mir was über New Reno.}
{198}{}{Erzähl mir was über Redding.}
{199}{}{Erzähl mir was über Gecko.}
{200}{}{Ich möchte noch was wissen...}
{201}{}{Danke für die Auskunft.}
{202}{}{Das ist eine Bergbausiedlung wie Redding, liegt aber ganz unten im Süden. Von da kriegen
 wir eine Menge von unserem Uran her.}
{203}{}{Erzähl mir was über New Reno.}
{204}{}{Erzähl mir was über Redding.}
{205}{}{Erzähl mir was über Gecko.}
{206}{}{Ich möchte noch was wissen...}
{207}{}{Danke für die Auskunft.}
{208}{}{Es liegt eine Ecke südwestlich von hier. Über Reno hört man viel Widersprüchliches.
 Manche Händler, besonders die Sklavenhändler, finden es toll da. Andere... eher nicht. Man sich
 da wohl gut amüsieren... aber es soll auch sehr gefährlich sein.}
{209}{}{Erzähl mir was über Broken Hills.}
{210}{}{Erzähl mir was über Redding.}
{211}{}{Erzähl mir was über Gecko.}
{212}{}{Ich möchte noch was wissen...}
{213}{}{Danke für die Auskunft.}
{214}{}{Das ist eine Bergbausiedlung ganz weit im Westen. In letzter Zeit sind von da kaum noch
 Karawanen gekommen, weswegen ein paar große Tiere anfangen, sich Sorgen zu machen. Besonders
 Stadtrat McClure.}
{215}{}{Erzähl mir was über Broken Hills.}
{216}{}{Erzähl mir was über New Reno.}
{217}{}{Erzähl mir was über Gecko.}
{218}{}{Ich möchte noch was wissen...}
{219}{}{Danke für die Auskunft.}
{220}{}{Eine Ghulsiedlung weniger als eine Tagesreise nordöstlich von hier, soviel ich weiß. Man
 munkelt, daß sie auf jeden Reisenden Jagd machen, der in ihr Gebiet kommt. Am besten bleibt man
 da weg.}
{221}{}{Erzähl mir was über Broken Hills.}
{222}{}{Erzähl mir was über New Reno.}
{223}{}{Erzähl mir was über Redding.}
{224}{}{Ich möchte noch was wissen...}
{225}{}{Danke für die Auskunft.}
{226}{}{Warum? Suchst du was, was ein bißchen stärker reinhaut, als dieses synthetische Zeugs?}
{227}{}{Vielleicht. Synthetischer Alkohol bringt's nun mal einfach nicht.}
{228}{}{Eigentlich nicht. Ich brauchte nur ein paar Auskünfte...}
{229}{}{Heut nicht.}
{230}{}{Wohl wahr. Ich hatte mal einen, äh, ich kannte mal einen Händler, der hatte ne Flasche
 Maddog 30/30. Ziemlich bitteres Zeug... brannte wie Feuer, war aber wenigstens mal was anderes.}
{231}{}{Und was ist mit dem Geheimvorrat von diesem "Händler" passiert?}
{232}{}{Ich brauche ein paar Auskünfte.}
{233}{}{Aha. War nett, sich mit dir zu unterhalten.}
{234}{}{Er wurde getrunken. Jedenfalls habe ich das gehört. Es gab noch ein paar andere "Spezies"
 hier in Vault City, die dem Händler beim Austrinken halfen. Die haben gut gezahlt dafür, daß
 sie zur Abwechslung mal was Richtiges trinken konnten.}
{235}{}{Das glaub ich. Hör mal, ich könnte unter Umständen leicht noch mehr echten Alk
 besorgen. Ich bin schon öfters im Ödland gewesen und da kommt man leicht an Alkohol.}
{236}{}{Ich brauche ein paar Auskünfte.}
{237}{}{Aha. War nett, sich mit dir zu unterhalten.}
{238}{}{Wirklich? Naja, wenn du ein bißchen echten Sprit abzugeben hätten, dann würde ich dafür
 schon was springen lassen. Wenn du es für dich behältst. Und die Ware irgendwie durch's Tor
 schmuggelst.}
{239}{}{Wieviel echten Alkohol bräuchtest du denn?}
{240}{}{Sagen wir, eine Kiste mit zehn Flaschen Schnaps und zehn Flaschen Bier. Und schlepp mir
 keinen radioaktiven Fusel aus Gecko an. Nur guten alten "Bölkstoff", kapiert?}
{241}{}{Zufällig hab ich genau diese Menge da.}
{242}{}{Ich könnt dir vielleicht was besorgen. Ich brauchte nur ein paar Auskünfte...}
{243}{}{Hmmmm. Ich denk mal darüber nach und meld mich dann wieder bei dir.}
{244}{}{Ausgezeichnet! Hier ist was für dich... Das ist der doppelte Betrag dessen was die Ware wert ist.
 Und diese Transaktion hat niemals stattgefunden, verstanden?}
{245}{}{Kein Problem. Hey, ich wollte doch ein paar Auskünfte...}
{246}{}{Danke. Es ist wirklich ein Vergnügen, mit dir Geschäfte zu machen.}
{247}{}{Näh, was im Ödland als Alkohol gilt, ist hier in Vault City verboten. Ich möchte lieber
 gar nicht wissen, wie das zusammengepanscht wird. Was möchtest du denn nun trinken,
 Hauptmann...?}
{248}{}{Ab und zu ein bißchen richtiger Alkohol, das ist schon OK. Klar, man wird davon benebelt,
 aber das kann einem bei zuviel Heilpulver auch passieren.}
{249}{}{Dann nehme ich einfach was anderes.}
{250}{}{Dann vergiß es. Ich bräuchte da ein paar Auskünfte...}
{251}{}{Aha. Trotzdem vielen Dank.}
{252}{}{Davon weiß ich nichts. Ich verkaufe hier nur synthetischen Alkohol. Wenn es hier in Vault City richtigen Alkohol geben würde, wär ich die letzte, die darüber Bescheid wüßte.}
{253}{}{Dann vergiß es. Ich bräuchte da ein paar Auskünfte...}
{254}{}{Aha. Trotzdem vielen Dank.}
{255}{}{Ich... verstehe. Naja, äh... paß auf dich auf. OK?}
{256}{}{Dankie-wankie, Blinkie-Stinkie.}
{257}{}{[Verschwinde.]}
{258}{}{Zzzzzzz.}