{100}{}{Du siehst einen kräftigen Mann in Arbeitskleidung. Er blickt starr zu Boden.}
{101}{}{Du siehst einen Vault City-Sklaven.}
{102}{}{Du siehst einen kräftigen Mann in Arbeitskleidung. Er blickt starr zu Boden.}
{103}{}{Du siehst eine gesund aussehende Frau in Arbeitskleidung. Sie blickt starr zu Boden.}
{104}{}{Du siehst einen Vault City-Sklaven.}
{105}{}{Du siehst eine gesund aussehende Frau in Arbeitskleidung. Sie blickt starr zu Boden.}
{106}{}{Ich habe von deinen mutigen Taten gehört. Du hast Vault City und der ganzen Welt damit
 einen großen Dienst erwiesen.}
{107}{}{Dein Kampf gegen die Enklave hat sogar die Erstbürgerin beeindruckt.}
{108}{}{Ich wünschte, ich könnte dir irgendwas geben... für alles, was du für uns getan hast,
 aber ich habe nichts... außer "Danke" zu sagen.}
{109}{}{Die anderen Diener werden mich darum beneiden, daß ich mit dem Held des Ödlandes sprechen
 durfte.}
{110}{}{Ja, Hauptmann?}
{111}{}{Hauptmann?}
{112}{}{Wünschst du, daß ich eine Arbeit für dich ausführe, Hauptmann?}
{113}{}{Hast du eine Anweisung für mich, Hauptmann?}
{114}{}{Tut mir leid, Hauptmann. Ich werde mir in Zukunft mehr Mühe geben.}
{115}{}{Tut mir leid, Hauptmann. Ich werde in Zukunft aufmerksamer sein.}
{116}{}{Ja, Bürger?}
{117}{}{Bürger?}
{118}{}{Wünschst du, daß ich eine Arbeit für dich ausführe, Bürger?}
{119}{}{Hast du eine Anweisung für mich, Bürger?}
{120}{}{Tut mir leid, Bürger. Ich werde mir in Zukunft mehr Mühe geben.}
{121}{}{Tut mir leid, Bürger. Ich werde in Zukunft aufmerksamer sein.}
{122}{}{Mutanten sind in der Stadt nicht zugelassen!}
{123}{}{Wenn die Wachen deinen Mutanten sehen, werfen sie dich raus.}
{124}{}{Mutanten sind in der Stadt nicht zugelassen! Sofort raus!}
{125}{}{Ghuls sind in der Stadt nicht zugelassen!}
{126}{}{Wenn die Wachen deinen Ghul sehen, werfen sie dich raus.}
{127}{}{Ghuls sind in der Stadt nicht zugelassen! Sofort raus!}
{128}{}{Ja, ich habe bereits einen Besitzer. Meine Papiere liegen beim Amt für Dienerzuteilung.}
{129}{}{Bitte laß mich in Frieden. Ich bin Vault City-Diener.}
{130}{}{Bitte hilf mir: Hast du zwei Kinder gesehen, dunkelhaarig...? Die sind vor zwei Jahren
 von anderen Sklavenhändlern mitgenommen und im Norden verkauft worden.}
{131}{}{Bitte... ich darf mit niemandem reden.}
{132}{}{Wenn mich ein Bürger dabei erwischt, wie ich mit einem Sklavenhändler rede, werde ich
 bestraft.}
{133}{}{Die Wachen melden mich, wenn ich mit dir weiterrede.}
{134}{}{Ich kann nicht mit dir reden. Ich muß arbeiten.}
{135}{}{Bitte geh, Sklavenhändler. Sonst krieg ich Ärger.}
{136}{}{Abhauen? Ich... ich hab noch nie versucht, abzuhauen. Mir geht's doch gut hier.}
{137}{}{Die Bürger haben gesagt, wenn ich hart genug arbeite, kann *ich* eines Tages auch Bürger
 werden.}
{138}{}{Die Bürger sagen: "Arbeit ist keine Schande".}
{139}{}{Die Bürger sagen, daß sie durch uns mehr Zeit für die wichtigen Dinge hätten.}
{140}{}{Ich hatte Glück, daß in Bürgerstadt Diener gebraucht wurden. Sonst wäre ich in New Reno
 gelandet.}
{141}{}{Wenn Diener gewissenhaft arbeiten, werden sie von Bürgerstadt mit Extrarationen belohnt.}
{142}{}{Ich habe gehört, daß sie in New Reno grauenhafte Sachen mit den Sklaven machen.}
{143}{}{Die Bürger haben meine ganze Sippe in die Stadt geholt, damit wir hier als Diener
 arbeiten. }
{144}{}{Die Bürger haben mich aus dem Ödland geholt und mir Lesen beigebracht.}
{145}{}{Die Bürger behandeln mich sehr gut. Das Essen hier ist prima.}
{146}{}{Ich darf nicht mit Außenweltlern sprechen.}
{147}{}{Zuerst hab ich meine Familie vermißt, doch das ist schon viele Jahre her.}
{148}{}{Ich stamme aus einem Sippendorf im Norden. Hier geht es mir besser.}
{149}{}{Zuerst bin ich in Den gefangengehalten worden. Zum Glück bin ich hier gelandet.}
{150}{}{Ich habe gehört, die Erstbürgerin würde manchmal den Dienern gegenüber ausrasten.}
{151}{}{Ich kann nicht mit dir reden. Ich muß arbeiten.}
{152}{}{Ich muß in einer Stunde fertig sein.}
{153}{}{Reden mit Outsidern ist nicht gestattet.}
{154}{}{Abhauen? Warum?}
{155}{}{Ja? Kann ich etwas für dich tun?}
{156}{}{Es ist schon sehr lange her, daß ich von den Sklavenhändlern gefangen wurde. Kann mich
 kaum noch dran erinnern.}
{157}{}{Ich hatte zwei Kinder, aber die sind nach Norden geschickt worden. Hoffentlich kommen sie
 irgendwann hierher.}
{158}{}{Tut mir leid, aber ich hab keine Zeit zum Reden.}
