{100}{}{Du siehst einen fröhlichen jungen Mann.}
{101}{}{Du siehst Steve, einen Begrüßungsunteroffizier von Vault City.}
{102}{}{Er blickt ausdruckslos.}
{103}{}{Hallo und herzlich willkommen in Vault City, dem schönsten Ort in New California!
 Mein Name ist Steve... womit kann ich dir dienen?}
{104}{}{Ist dieser ganze eingezäunte Bereich etwa die Stadt?}
{105}{}{Was meinst du mit "schönster Ort"?}
{106}{}{Ich suche die Vault. Kannst du mir sagen, wo sie ist?}
{107}{}{Wiedersehn.}
{108}{}{Ähhh... [Liest aus dem Handbuch ab.] Ähhh... diese Frage
 ist nicht vorgesehen. Hier steht keine passende Antwort drin.}
{109}{}{Hast du überhaupt von irgendwas 'ne Ahnung?}
{110}{}{Trotzdem vielen Dank.}
{111}{}{[Schaut in sein Handbuch.] Wenn der Außenweltler... das
 bist du... dich beleidigt... das bin ich... dann verweise ihn an den Haupt-
 Begrüßungsoffizier. Oh... ich verweise dich an Melinda, die Haupt-
 Begrüßungsoffizierin.}
{112}{}{Dann rede ich eben mit ihr.}
{113}{}{Willkommen im Amt für Begrüßungsangelegenheiten. Ich heiße Steve.}
{114}{}{Entschuldigung, aber ich habe zu tun. }
