{100}{}{Du siehst einen Bürger in einem leuchtendblauen Overall. Sieht aus wie ein
 Vaultbewohner-Overall, aber ohne Nummer auf dem Rücken.}
{101}{}{Du siehst einen Bürger von Vault City.}
{102}{}{Du siehst einen Bürger in einem leuchtendblauen Overall. Sieht aus wie ein
 Vaultbewohner-Overall, aber ohne Nummer auf dem Rücken.}
{103}{}{::Klatscht::}
{104}{}{Da ist der Held! Sieh mal!}
{105}{}{Ungelogen! Das ist der Held, hier, in Vault City!}
{106}{}{Schönen Tag noch, Hauptmann.}
{107}{}{Vault City lebe hoch, Hauptmann.}
{108}{}{Guten Tag, Bürger.}
{109}{}{Vault City lebe hoch, Bürger.}
{110}{}{Ein Mutant! Wache! Wache!}
{111}{}{Ein Ghul! Wache! Wache!}
{112}{}{Wie kommt man in die Stadt rein?}
{113}{}{Entschuldigung, hast du einen Tagesausweis? }
{114}{}{Grummel. Schon wieder ein Outsider.}
{115}{}{Sieht so aus, als würden sie immer mehr Outsider in die Stadt reinlassen...}
{116}{}{Ich will doch sehr hoffen, daß du einen Tagesausweis hast.}
{117}{}{Sieht aus, als würden die in letzter Zeit so ziemlich *jedem* Outsider einen Tagesausweis
 geben.}
{118}{}{Ich habe von deinen mutigen Taten gehört. Du hast Vault City und der ganzen Welt damit
 einen großen Dienst erwiesen.}
{119}{}{Dein Kampf gegen die Enklave hat sogar die Erstbürgerin beeindruckt.}
{120}{}{Ich habe gehört, du seist bis ganz runter in den Süden, bis nach San...Fran...zisco
 gereist. Stimmt das?}
{121}{}{Vielleicht sollte Vault City ja wirklich outsider-freundlicher werden. }
{122}{}{Stimmt das? Hat die alte Regierung den Krieg immer noch weitergeführt?}
{123}{}{Du solltest deine Reisen im Computer von Vault City dokumentieren, damit sie jeder dort
 nachlesen kann.}
{124}{}{Du bist herzlich eingeladen, solange zu bleiben, wie du möchtest, Held.}
{125}{}{Du solltest deine Heldentaten gegen die Enklave als nette kleine Liste veröffentlichen.}
{126}{}{*Gähn*...Hmmmmm? Ja? Was gibt's?}
{127}{}{Bißchen spät für einen Besuch. }
{128}{}{Die MEISTEN Bürger würden um die Zeit schon schlafen.}
{129}{}{Schlafen? Nein, jetzt nicht mehr.}
{130}{}{Komm bitte morgen früh wieder. Ich muß morgen den ganzen Tag über Listen zusammenstellen.}
{131}{}{Schönen Tag noch, Hauptmann.}
{132}{}{Vault City lebe hoch, Hauptmann.}
{133}{}{Darf ich dir einen Kuchen bringen, Hauptmann?}
{134}{}{Stimmt was nicht, Hauptmann?}
{135}{}{Es macht doch wohl hoffentlich keiner von diesen verlausten Outsidern Ärger?}
{136}{}{Kannst du uns was über die Außenwelt erzählen, Hauptmann?}
{137}{}{Guten Tag, Bürger.}
{138}{}{Vault City lebe hoch, Bürger.}
{139}{}{Ich fühle mich supergut und du?}
{140}{}{Als Bürger ist es unsere Pflicht, Listen zu erstellen und zu pflegen.}
{141}{}{Ich habe heute den ganzen Tag lang die Liste für den Prokonsul fertiggemacht und sie dann
 überprüft. Ich lege wahnsinnig gern Listen an.}
{142}{}{Ich arbeite im Listenamt. Die meisten Leute arbeiten da. Wir Vaultstädter *lieben*
 Listenschreiben.}
{143}{}{Ich hab heute fast den ganzen Tag lang diese Liste für das Listenbüro auf den neuesten
 Stand gebracht. Eine anständige, ehrenvolle und kreative Arbeit}
{144}{}{Man sagt, du wärst wirklich in der Außenwelt herumgereist. Wie konntest du denn bloß
 unter diesen ganzen dreckigen Outsidern überleben?}
{145}{}{Oh! Du bist der neue Bürger. Willkommen in Vault City.}
{146}{}{Weißt du schon, wo du wohnen wirst, solange du hier bist?}
{147}{}{Der Rat meint es wirklich gut mit uns.}
{148}{}{Wir müssen alle dafür sorgen, daß unsere schöne Stadt sauber bleibt.}
{149}{}{Die Diener? Die machen bei uns die Dreckarbeit.}
{150}{}{Bei der Ratstagung von gestern ist ziemlich viel herausgekommen. Wir haben *jede Menge*
 Listen geschrieben. Wir Vaultstädter lieben das Listenschreiben.}
{151}{}{Ja?}
{152}{}{Kann ich dir irgendwie behilflich sein... Outsider?}
{153}{}{Wie bitte, hast du was gesagt?}
{154}{}{Wer, ich? Ich hab hier was zu erledigen. Vielleicht solltest du dich auch um deine
 eigenen Angelegenheiten kümmern.}
{155}{}{Kann ich bitte deinen Tagesausweis sehen?}
{156}{}{Oh... Entschuldigung. Fast hätte ich dich für einen Diener gehalten.}
{157}{}{Ich hab im Moment wirklich keine Zeit, mit einem Outsider zu plaudern. Bitte geh weiter.}
{158}{}{Würdest du gefälligst mehr Abstand halten?}
{159}{}{Stell dich bitte da drüben hin.}
{160}{}{Dank der Diener können wir unsere Zeit für wichtigere Dinge verwenden. Vor allem zum
 Anfertigen von Listen.}
{161}{}{Die Diener? Die machen bei uns die Dreckarbeit.}
{162}{}{Klar. Das riecht...äh, sieht man doch, daß du ein Outsider bist.}
{163}{}{Du bist ein Outsider? Wie drollig.}