{100}{}{Você vê alguém na armadura de energia.}
{101}{}{Você vê o intendente.}
{102}{}{Você vê alguém vestindo uma armadura de poder de um design incomum.
  Há uma insígnia no peitoral a qual você não conhece.}
{103}{}{Quem diabos são vocês... Alerta! Intrusos na base!}
{104}{}{O que ... Eu posso ver por que você está aqui. Você obviamente quer
  se livrar desse terno antigo que você está vestindo.}
{105}{}{Por que você está fora de uniforme, soldado?}
{106}{}{Morra!}
{107}{}{Uh... sim.}
{108}{}{Uh...}
{109}{}{Eu novo aqui.}
{110}{}{Eu não sou um soldado!}
{111}{}{Hum, bem...}
{112}{}{Eu sou novo aqui.}
{113}{}{Eu não sou um de seus soldados!}
{114}{}{Uh, o que? Não pode pensar em uma boa desculpa? Eu estou esperando, soldado!}
{115}{}{Ainda não tenho uniforme.}
{116}{}{Eu não tenho um uniforme ainda.}
{117}{}{Você é um pouco do lento, não é? (suspiro) Bem, isso é
  não é sua culpa. Eu tenho um irmão como você. De qualquer forma, você é novo aqui?
  Não lembro de te ver antes.}
{118}{}{Você é novo por aqui? Eu não lembro de ter visto você antes.}
{119}{}{Sim! Eu novo aqui!}
{120}{}{Sim, eu sou novo aqui.}
{121}{}{Bem, você precisa cuidar do seu problema padrão, então. Vá para o arsenal,
  prepare-se e tire sua arma. Você deve se reportar ao sargento Drill
  depois.}
{122}{}{Obrigado!}
{123}{}{Seja bem-vindo. Agora sai daqui. Tenho trabalho a fazer e eu
  não quer ser perturbado.}
{124}{}{Eu estou ocupado agora. Volte mais tarde.}
{125}{}{Olá, recrute. Acabei de receber uma chamada do seu sargento. Ele diz
  Eu devo te equipar e mandar de volta para ele. Esta certo?}
{126}{}{Sim.}
{127}{}{Esta base está em alerta e não reconheço você. Me mostre seu
  papéis, soldado.}
{128}{}{Mim não ter documentos com eu.}
{129}{}{Eu não precisa documentos!}
{130}{}{Eu não estou com meus documentos comigo. Eles estão no meu armário.}
{131}{}{Documentos? Eu tenho seus documentos bem aqui!}
{132}{}{Resposta errada. Você deve levar seus papéis com você em todos os momentos
  e você deve saber disso!}
{133}{}{Oops.}
