{200}{}{Se eu amarrar uma corda com isso, eu provavelmente poderia descer lá.}
{201}{}{Alguma corda definitivamente seria útil aqui.}
{300}{}{Isso deve resolver.}
{301}{}{Eu já coloquei a corda.}
{302}{}{Você amarra a corda a uma das barras do respiradouro e solta o resto da corda para baixo. Você ouve um baque quando ele atinge
  o fundo.}
{400}{}{Você entra em um dos sistemas de ventilação da EPA. Você pode ouvir vários insetos correndo sobre.}
