{100}{}{Você vê uma pessoa com pijama engraçado.}
{101}{}{Você vê um cidadão Shi.}
{102}{}{Esta pessoa parece diferente de todos que você já viu antes. Eles não parecem se importar muito sobre você.}
{103}{}{Você não é um espião?}
{104}{}{Quem é você?}
{105}{}{Peixes e algas. Isso é tudo o que temos.}
{106}{}{Ha ha! Olhe os divertidos olhos redondos!}
{107}{}{Você parece um Hubologista.}
{108}{}{Nos deixe em paz.}
{109}{}{Vida longa ao Dragão!}
{110}{}{Abaixo Lo Pan!}
{111}{}{O Dragão é um herói.}
{112}{}{Tome cuidado com Lo Pan. Ele é encrenca.}
{113}{}{Esses punks são sempre tão altos.}
{114}{}{Trabalho, trabalho, trabalho. Arroz, arroz, arroz. ::suspiro::}
{115}{}{Não existe mais na vida do que isso?}
{116}{}{Nós somos mais espertos do que você pensa.}
{117}{}{Olha! Um lao wai!}
{118}{}{Eu não acho que gosto de você.}
{119}{}{Você me da medo.}
{120}{}{Não me machuque, por favor.}
{121}{}{Eu aposto que Lo Pan iria gostar de você.}
{122}{}{Por favor não cause problemas.}
{123}{}{Eu aprecio a vida. Eu é que não vou me arriscaria em perdê-la atoa.}
{124}{}{Essas terras de ninguém estão ficando cada vez mais assustadoras.}
{125}{}{Senhor... sim, senhor... tchau, senhor.}
{126}{}{Ha ha! Aquele bastardo do Lo Pan está morto!}
{127}{}{Você nos salvou!}
{128}{}{Lo Pan está morto!}
{129}{}{Agora para os Hubologistas!}
{130}{}{Olhe para esse olhos-redondos engraçado!}
{131}{}{Você parece um Hubologista.}
{132}{}{Nos deixe em paz.}
{133}{}{Vida longa ao Dragão!}
{134}{}{Vida longa ao Imperador!}
{135}{}{Trabalho, trabalho, trabalho. Arroz, arroz, arroz. ::suspiro::}
{136}{}{Não existe mais na vida do que isso?}
{137}{}{O Dragão... está morto...}
{138}{}{Oh não! O Dragão está morto!}
{139}{}{A vida não tem significado.}
{140}{}{Nós sobreviveremos... por pouco.}
{141}{}{Oh, agora quem poderá nos defender?}
{142}{}{Os nossos sonhos morreram com o Dragão.}
{143}{}{Não faz sentido.}
{144}{}{Ensinaremos nossas crianças a ser como o Dragão.}
{145}{}{Nós devemos criar novos sonhos agora.}
{146}{}{O arauto do Emperador! Morto!}
{147}{}{O que acontece agora?}
{148}{}{Só espero que os selvagens não nos invadam agora!}
{149}{}{Os bons sempre morrem jovens.}
{150}{}{Espero que possamos sobreviver ao inverno sem Ken Lee.}
{151}{}{Ouvi dizer que Ken Lee foi o único que manteve o Imperador em linha.}
{152}{}{Ouvi dizer que o Imperador era apenas uma fachada para Ken Lee. }
{153}{}{Trabalho, trabalho, trabalho. Arroz, arroz, arroz. ::suspiro::}
{154}{}{Não existe mais na vida do que isso?}
{155}{}{Nós somos mais espertos do que você pensa.}
{156}{}{Vejam! Um forasteiro!}
{164}{}{Você matou AHS-9? Bom trabalho!}
{165}{}{Aqueles Hubologistas me dão arrepios.}
{166}{}{Honorável visitante, você nos prestou um grande serviço.}
{167}{}{Morte aos Hubologistas!}
{168}{}{Talvez isso faça com que esses Hubologistas saiam logo fora daqui.}
{169}{}{Estúpidos Hubologistas, nem podem proteger seu próprio líder.}
{170}{}{Só espero que os Hubologistas não venham atrás de vingança.}
{171}{}{Parece que você não é um espião afinal de contas.}
{172}{}{Filho de um porco! Morra!}
{173}{}{Você tem desonrado a sua família!}
{174}{}{Deixe-nos em paz, lao wai!}
{175}{}{Você não fez danos suficientes?}
{176}{}{Eu odeio você!}
{177}{}{Deixe essa cidade!}
{178}{}{Vá para casa, para o seu povo!}
{179}{}{Não obscureça minha vida com seu rosto!}
{180}{}{O que será necessário para se livrar de você?}
{181}{}{Ajuda! Ajuda!}
