name: pr

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Fallout tests
        uses: BGforgeNet/fallout-tests@main
        with:
          scripts_h: scripts_src/headers/scripts.h
          scripts_lst: data/scripts/scripts.lst
          scripts_dir: scripts_src
          dialog_dir: data/text/english/dialog
          worldmap_path: false

      - name: Poify/Unpoify test
        uses: BGforgeNet/msg2po@master
        with:
          poify: true
          unpoify: true
          single_commit: false
          poify_commit: false
          unpoify_commit: false
          dir2msgstr: true
          dir2msgstr_commit: false
